### ISSUE TITLE
high-performance serializable distributed transactions are not available to the masses

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#10000]
Please follow the steps below to help us help you.
1. Please supply the header (i.e. the first few lines) of your most recent
   log file **for each node in your cluster**. On most unix-based systems
   running with defaults, this boils down to the output of

```
I161014 21:28:18.777136 1 server/server.go:556  [n1] advertising CockroachDB node at localhost:26257
build:      beta-20161013-156-gd32e492-dirty @ 2016/10/15 01:03:52 (go1.7.1)
admin:      http://localhost:8080
sql:        postgresql://root@localhost:26257?sslmode=disable
logs:       cockroach-data/logs
store[0]:   path=cockroach-data
status:     restarted pre-existing node
clusterID:  {38c5da7c-6a9e-4eca-ab0a-5e03a7661d86}
nodeID:     1
I161014 21:28:18.781694 75 sql/event_log.go:94  [n1] Event: "node_restart", target: 1, info: {Descriptor:{NodeID:1 Address:{NetworkField:tcp AddressField:localhost:26257} Attrs: Locality:} ClusterID:{UUID:38c5da7c-6a9e-4eca-ab0a-5e03a7661d86} StartedAt:1476494898776507556}
```
1. Please describe the issue you observed:
- What did you do?
  I've talked to programmers in various companies and observed that the vague concept of "consistency" was always on their minds, as the databases they're using are forcing them into awkward tradeoffs when needing to operate at larger scale or provide reliability guarantees.
- What did you expect to see?
  Scalability, survivability, and SQL, while always maintaining strong consistency, should be available to all.
- What did you see instead?
  A hodgepodge of home-grown solutions, each with their own gaping holes.

**Comment by petermattis** [comment]
Let's get this fixed!
