### ISSUE TITLE
kv: don't step read timestamp for read committed AOST txns

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#100154]
From the Read Committed RFC:

> The [`AS OF SYSTEM TIME`](https://www.cockroachlabs.com/docs/stable/as-of-system-time.html) clause can be added to individual statements or to entire read-only transactions, instructing CockroachDB to read at a historical MVCC snapshot. This is an important feature that underpins follower reads.
> 
> In some regard, such a feature is incompatible with the Read Committed isolation level, which captures a new MVCC snapshot for each statement in a transaction. For this reason, PostgreSQL disallows the use of `SET TRANSACTION SNAPSHOT` (analogous to `AS OF SYSTEM TIME`) in Read Committed transactions. When issued, an error is returned:
> ```
> ERROR:  a snapshot-importing transaction must have isolation level SERIALIZABLE or REPEATABLE READ
> ```
> 
> Proscribing `AS OF SYSTEM TIME` in Read Committed transactions would cause confusion and inconvenience for users of CockroachDB, especially when attempting to use follower reads. Instead of banning it, the syntax will be accepted and the transaction will be promoted to a read-only, serializable transaction[^6] with the specified fixed read timestamp across all statements, which matches the user’s intent. Such transactions are not subject to retry errors.
> 
> [^6]: read-only, serializable isolation transactions are equivalent to read-only, snapshot isolation transactions.

Jira issue: CRDB-26576

Epic CRDB-26546

**Comment by rafiss** [comment]
There are a few cases where I think it will be tricky to promote. I expect it to be possible with some light refactoring, but a bigger concern I have is UX confusion. The two most trivial cases I'm thinking of:
```
root@localhost:26257/defaultdb> begin as of system time '-5s';
BEGIN

root@localhost:26257/defaultdb  OPEN> set transaction_isolation = 'read committed';
SET
```
and
```
root@localhost:26257/defaultdb> begin isolation level read committed;
BEGIN

root@localhost:26257/defaultdb  OPEN> set transaction as of system time '-5s';
SET TRANSACTION
```

Is there a strong reason not to just ban these kinds of usages? In some sense, an explicit error may be more clear than automatically promoting a transaction behind the scenes. (In fact, maybe you could say the same about automatically promoting a transaction started with `begin isolation level read committed as of system time '-5s'`.)

**Comment by nvanbenschoten** [comment]
> Is there a strong reason not to just ban these kinds of usages?

I don't think we want to ban this kind of usage, because it would complicate the use of follower reads for users that set a default transaction isolation level of read committed. Ideally, it would just work and be made to be sane.

That said, we could reconsider how this is made to work. Instead of explicitly changing the isolation level, we could also have the KV transaction detect when its timestamp has been fixed and _not_ advance its read snapshot on statement boundaries (https://github.com/cockroachdb/cockroach/issues/100133). I think this would just work for transactions that are also read-only and with no uncertainty interval (those that call `Txn.SetFixedTimestamp`), because these transactions never experience transaction retry errors.
