### ISSUE TITLE
kv: implement replicated key-level locks

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#100193]
Related to #52768.
Related to #75456.

Ignoring intents, CockroachDB currently only supports the unreplicated lock durability. Consequently, `FOR UPDATE` locks are subtly best-effort; it is possible for a client to unknowingly lose a lock (violates mutual exclusion) and even still commit (violates isolation). 

The best-effort nature of these locks is surprising for Serailizable transactions and a correctness hazard for Snapshot and Read Committed transactions.

We should implement the `Replicated` lock strength:
https://github.com/cockroachdb/cockroach/blob/2414bbadfb48015de9bc7444bc4379881d7c3f90/pkg/kv/kvserver/concurrency/lock/locking.proto#L187-L210

We should then address https://github.com/cockroachdb/cockroach/issues/100194.

Jira issue: CRDB-26577

Epic CRDB-26544

**Comment by nvanbenschoten** [comment]
The API for replicated key-level locks will look similar to the API for unreplicated key-level locks. `GetRequest`, `ScanRequest`, and `ReverseScanRequest` will all receive a new `KeyLockingDurability lock.Durability` field that lives beside their existing `KeyLocking lock.Strength` (rename to `KeyLockingStrength`?) field.

**Comment by arulajmani** [comment]
The only thing that's left here is https://github.com/cockroachdb/cockroach/issues/111536, which I've pulled out into its own issue. @nvanbenschoten closing this out, like we spoke about offline. This was fun!
