### ISSUE TITLE
kvnemesis: step read committed read snapshot

### ISSUE THREAD

**Issue by nvb** [cockroachdb/cockroach#100170]
We should extend kvnemesis to step the read snapshot in read committed transactions.

From the Read Committed RFC:
> The framework will be updated to step read committed transactions through multiple read snapshots, mimicking the style of use expected from SQL when encountering statement boundaries.

Jira issue: CRDB-26562

Epic CRDB-26548

**Comment by nvanbenschoten** [comment]
Transactions in kvnemesis are configured in "auto-stepping" mode, so the transaction's read snapshot will be stepped automatically on each batch. There remaining work to do here would be to validate non-locking reads from these intermediate read snapshots. That work is tracked in https://github.com/cockroachdb/cockroach/issues/114262.
