### ISSUE TITLE
perf: AbortCache check causes RocksDB read on every transaction

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#10016]
From the code:

```
// The AbortCache sets markers for aborted transactions to provide
// protection against an aborted but active transaction not reading
// values it wrote (due to its intents having been removed).
```

We check the `AbortCache` on both read and write transactions by making a call to `Replica.checkIfTxnAborted` which calls `AbortCache.Get` which in turn calls `engine.MVCCGetProto` to get the "abort cache entry". In the vast majority of cases, no abort cache entry is present. It seems likely that there is something we can do to optimize for that case. Disabling the abort cache (which is only feasible for testing) gives a 2% speedup to `block_writer` tests.

**Comment by bdarnell** [comment]
Note that the rocksdb bloom filter should already keep us from going to disk in most cases, so the savings here are the cgo overhead and the occasional bloom filter false positive.

I think that mirroring the entire abort cache into memory is probably too expensive for high-contention workloads, but something simple like storing the original timestamp of the most recent aborted transaction for the range should work and give us most of the benefit.

**Comment by petermattis** [comment]
We now avoid the AbortCache checks for 1PC transactions and for read-only transactions. I don't think there is anything left to do here.
