### ISSUE TITLE
sqlproxy/acl: TestDenylistLogic is flakey

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#100295]
**Describe the problem**

```
    file_test.go:259:
          Error Trace:  github.com/cockroachdb/cockroach/pkg/ccl/sqlproxyccl/acl/file_test.go:259
          Error:        An error is expected but got nil.
          Test:         TestDenylistLogic
```

https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_BazelUnitTests/9279269?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_BazelUnitTests/9357267?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

Jira issue: CRDB-26344

**Comment by jaylim-crl** [comment]
I can't reproduce this locally, even with stress, but I added a commit here, which should hopefully help with this: https://github.com/cockroachdb/cockroach/pull/100315. Do reopen this again if we still see the flakes once that commit is in. We should get more observability then.
