### ISSUE TITLE
sql: open a logging span for internal uses of SQL

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#10025]
Requested by @RaduBerinde in https://github.com/cockroachdb/cockroach/pull/10024#issuecomment-254201627

Regarding `makePlanner()` and `makeInternalPlanner()`: 
_We should at least plumb a Tracer or AmbientContext somehow so we can open a span._

cc @andreimatei @RaduBerinde

**Comment by RaduBerinde** [comment]
`SchemaChanger` and `LeaseManager` should have `AmbientContext`s. Then we will hopefully be able to pass or use an ambient for all internal uses.

**Comment by knz** [comment]
@tamird says we should look again at #4869 and see if we could capture internal sql uses via a driver connection.

**Comment by andreimatei** [comment]
So why didn't we open a span in #10024, in `makePlanner()`? Actually I think we should have `makePlanner` (which is only used for bounded internal operations) take a ctx, and have the caller open/finish that span. Why do we need to plumb an AmbientContext?

And how is the behaviour of `makePlanner` related to `SchemaChanger` and `LeaseManager`?

**Comment by knz** [comment]
Both schemachanger and leasemanager use the "internal executor" which is nothing more than a spontanous planner (without an executor pointer, even). In the case of schemachanger there are multiple layers of intermediary structs and callbacks where there is no context plumbed yet.

**Comment by RaduBerinde** [comment]
@andreimatei Right now you don't have any context when you call into `makePlanner` so you don't have a tracer to open a span. `SchemaManager` and LeaseManagers are the main users of `makePlanner` for which it's difficult to come up with a context. So I think we need those to have `AmbientContext`s (they probably should regardless of this issue).

We don't need to pass the ambient itself to `makePlanner` - `SchemaManager` and `LeaseManager` can use their ambients to create a suitable context.

**Comment by knz** [comment]
@andreimatei I think your recent changes have fixed this right?
