### ISSUE TITLE
sql: RETURNS TABLE not supported for UDFs

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#100226]
**Describe the problem**

Trying to create a UDF with `RETURNS TABLE` currently results in a syntax error.

**To Reproduce**

Run the following in `cockroach demo` on master / 23.1:
```
CREATE FUNCTION sum_n_product_with_tab (x int)
RETURNS TABLE(sum int, product int) AS $$
    SELECT $1 + tab.y, $1 * tab.y FROM tab;
$$ LANGUAGE SQL;
```
On CRDB it results in this error:
```
invalid syntax: statement ignored: at or near "table": syntax error
SQLSTATE: 42601
DETAIL: source SQL:
CREATE FUNCTION sum_n_product_with_tab (x int)
RETURNS TABLE(sum int, product int) AS $$
        ^
HINT: try \h CREATE FUNCTION
```

**Expected behavior**

This works on Postgres, so we should support it. But in the meantime, at least we should return an unimplemented error with an appropriate issue number.

Jira issue: CRDB-26307

gz#20015

**Comment by rytaft** [comment]
@mgartner I put this in 23.1 since I'm not sure if you care about telemetry for this feature? If not, feel free to move this to backlog.

**Comment by giangpham712** [comment]
@fqazi This affects efcore.pg tests
