### ISSUE TITLE
ui: transaction marked as `Executing` when the respective session is idle

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#100236]
When looking at the active transaction executions, I see something like this

![Screenshot from 2023-03-30 19-18-15](https://user-images.githubusercontent.com/377201/228985630-420b657d-05b8-4e41-b29f-36bedc1cbf01.png)

Here, the `SHOW database` one is a session that's currently idle. I think the `Executing` label is misleading, if not straight-up incorrect. Is this the same label I would have seen if a statement was actually running?
I think something like `idle` would be a better label.

Jira issue: CRDB-26315

**Comment by maryliag** [comment]
Likely the statement was being executed when we retrieve the status, but it finished after.
The issue his is just confirming this is the expected behaviour.
