### ISSUE TITLE
logictest: `query [types] nodeidx` does not seem to work as expected

### ISSUE THREAD

**Issue by xinhaoz** [cockroachdb/cockroach#100331]
[This test](https://github.com/cockroachdb/cockroach/pull/100221/files#diff-ff572f052a2c4f40cd4a964479b73e9119702d6df94374bdcec8c4146586d8a9) checks some queries made against a mixed version cluster. The summary of the test is that it generates 1 'query insight' into node 0 (22.2) and 1 query insight for node 1 (23.1), and checks that requesting cluster-wide insights in a mixed version cluster succeeds. 

Prior to applying the other changes in the patch,  line 66-67, which checks requesting cluster-wide insights using a 22.2 node in a mixed version state, should have caused a node panic. The test linked uses `user root nodeidx=i` to change which node to query from, but before that I was using `query [types] nodeidx=i`. Using nodeidx with query did not cause my test to fail as expected.  Only after switching all instances (except for checking the binary version in the beginning) to use `user root nodeidx` did the test fail.

Jira issue: CRDB-26374

**Comment by rafiss** [comment]
I can't reproduce what you're seeing. I applied this diff:
```
diff --git a/pkg/sql/logictest/testdata/logic_test/mixed_version_insights_queries b/pkg/sql/logictest/testdata/logic_test/mixed_version_insights_queries
index 9f078adf7d3..6ded8e2ef91 100644
--- a/pkg/sql/logictest/testdata/logic_test/mixed_version_insights_queries
+++ b/pkg/sql/logictest/testdata/logic_test/mixed_version_insights_queries
@@ -60,10 +60,10 @@ SELECT count(*) > 0 FROM crdb_internal.node_execution_insights
 ----
 true

-user root nodeidx=0

 # Verify issuing insights cluster-wide fanout from 22.2 causes no problems.
-query B
+query B nodeidx=0
 SELECT count(*) > 0 FROM crdb_internal.cluster_execution_insights
 ----
 true
```

And I reverted all your non-test changed. The test failed, which seems like the expected result.

**Comment by xinhaoz** [comment]
This was the test I had before:
```
# LogicTest: cockroach-go-testserver-upgrade-to-master

# Verify that all nodes are running 22.2 binaries.

query T nodeidx=0
SELECT crdb_internal.node_executable_version()
----
22.2

query T nodeidx=1
SELECT crdb_internal.node_executable_version()
----
22.2

query T nodeidx=2
SELECT crdb_internal.node_executable_version()
----
22.2

upgrade 1

# Test that there are no problems reading from insights tables in mixed version state.

# Insert some insights into nodes of both versions.


query B nodeidx=0
select pg_sleep(1)
----
true


query B nodeidx=1
select pg_sleep(1)
----
true


# Sleep to ensure our queries above are written to the insights system.
sleep 3s


# Verify we have insights in each node.


query B nodeidx=0
SELECT count(*) > 0 FROM crdb_internal.node_execution_insights
----
true


query B nodeidx=1
SELECT count(*) > 0 FROM crdb_internal.node_execution_insights
----
true


# Verify issuing insights cluster-wide fanout from 22.2 causes no problems.
query B nodeidx=0
SELECT count(*) > 0 FROM crdb_internal.cluster_execution_insights
----
true


# Verify issuing insights cluster-wide fanout from 23.1 causes no problems.
query B nodeidx=1
SELECT count(*) > 0 FROM crdb_internal.cluster_execution_insights
----
true

```


With no use of `user root` at all.
