### ISSUE TITLE
sqlstats: bound cardinality of persisted fingerprints

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#100318]
**Is your feature request related to a problem? Please describe.**

We've observed apps generating thousands of unique statement fingerprints per-hour, and our current policies to flush sql stats to system tables (happens through some rate-limiter when the in-memory cache gets full) can still result in a large number of rows in the table. We should fix that. Recently we lowered the GC TTL for these tables to 1h (https://github.com/cockroachdb/cockroach/pull/100141/files) to reduce the garbage accumulated on a per-row basis, but the high-cardinality is still a problem. Some internal discussion [here](https://cockroachlabs.slack.com/archives/C02HWA24541/p1680277765409229) and [here](https://cockroachlabs.slack.com/archives/C0159JK877C/p1660753268957129).

Jira issue: CRDB-26367

**Comment by maryliag** [comment]
No longer a priority
