### ISSUE TITLE
Joint COPY perf investigation with KV team

### ISSUE THREAD

**Issue by DingDLu** [cockroachdb/cockroach#100338]
Created this issue as part of 23.2 planning

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Jira issue: CRDB-26378

Epic CRDB-25320

**Comment by mgartner** [comment]
Closing for now. I don't believe we have any plans for this in the near future.
