### ISSUE TITLE
ui: use go/build to load the UI package 

### ISSUE THREAD

**Issue by maxlang** [cockroachdb/cockroach#10038]
As per @tamird's comments in #10037, the ui folder was moved and the development mode failed silently.

**Comment by petermattis** [comment]
@tamird Is there a concrete action here? If not, let's close.

**Comment by tamird** [comment]
There is, and I have a branch locally. It's not something I'm actively working on, but we don't need to close this.

**Comment by tamird** [comment]
Heh, this was accidentally fixed by 3c8b033e2ed2f54e853cef6095cf427e540be3af.
