### ISSUE TITLE
storage: range keys / tombstones are enabled in a mixed 22.2 / 23.1 cluster

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/cockroach#100303]
**Describe the problem**

Range keys are written to a cluster with nodes of mixed versions (22.2.x and 23.1.x). The intention is to only start writing these key kinds after 23.1 is finalized.

**To Reproduce**

Start with a cluster at version 22.2.x. Partially upgrade the cluster to 23.1, resulting in a mixed version cluster. Create and drop a database, resulting in range tombstones being written.

**Expected behavior**

There should be no range keys present in the cluster until the cluster version is finalized as 23.1.

**Additional data / screenshots**

In the following, four of eight nodes were updated to 23.1.0-alpha.7 around 3/29 22:00, which correlates with when we started writing these keys.

<img width="1065" alt="Screenshot 2023-03-31 at 7 35 27 AM" src="https://user-images.githubusercontent.com/804457/229150580-b1dc48ce-7034-4080-af0d-d575f9794990.png">

**Environment:**

Latest `master`.

Jira issue: CRDB-26352

Epic CRDB-20465

**Comment by jbowens** [comment]
Reopening until the 23.1 backport #100746 is merged.
