### ISSUE TITLE
REPEATABLE READ isolation level mapped to SERIALIZABLE

### ISSUE THREAD

**Issue by alamaison** [cockroachdb/cockroach#10049]
When setting the isolation level to `REPEATABLE READ`, it gets set to `SERIALIZABLE`, rather than `SNAPSHOT`, which is what `REPEATABLE READ` means in postgres.  Is this intentional?

Repro:

run psql
execute

```
BEGIN;
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
SHOW TRANSACTION ISOLATION LEVEL;
```

Output:

```
TRANSACTION ISOLATION LEVEL 
-----------------------------
 SERIALIZABLE
```

**Comment by tschottdorf** [comment]
https://github.com/cockroachdb/cockroach/issues/3527

**Comment by alamaison** [comment]
So you mean the bug is really with Postgres?

**Comment by tschottdorf** [comment]
It seems like it to me, though I haven't looked into what Postgres does here. Would be curious to hear their argument.

From https://www.microsoft.com/en-us/research/publication/a-critique-of-ansi-sql-isolation-levels/:

>
A3: r1[P]...w2[y in P]...c2...r1[P]...c1 (Phantom)
A5B: r1[x]...r2[y]...w1[y]...w2[x]...(c1 and c2 occur)
(Write Skew)

>
Snapshot Isolation cannot experience the A3 anomaly. A
transaction rereading a predicate after an update by
another will always see the same old set of data items. But
the REPEATABLE READ isolation level can experience A3
anomalies. Snapshot Isolation histories prohibit histories
with anomaly A3, but allow A5B, while REPEATABLE
READ does the opposite.

**Comment by knz** [comment]
Hi @alamaison, what do you think would be the best course of action from this point?

**Comment by alamaison** [comment]
My selfish preference would be for consistency with Postgres.  In favour of that point-of-view is that people don't agree on a precise REPEATABLE READ and tend to assume something with fewer guarantees that snapshot isolation.  Therefore they wouldn't be surprised by that behaviour.

**Comment by andreimatei** [comment]
Note that the upcoming rewrite of the txn docs (re-)include a phrase about this.
See https://reviewable.io/reviews/cockroachdb/docs/672#- and search for "Despite similarity in names".

**Comment by sploiselle** [comment]
Documented [here](https://www.cockroachlabs.com/docs/transactions.html#aliases).
