### ISSUE TITLE
sql: missing implementation for SUM(interval)

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#10040]
Trying to compute the SUM aggregate over  an `INTERVAL` column yields:
`pq: unknown signature for sum: sum(interval)`

**Comment by yznming** [comment]
@andreimatei maybe i can try to fix it.

**Comment by andreimatei** [comment]
Thanks @yznming but I just went ahead and added it myself, as I needed it for something else I was doing.
One other thing I've missed just now is an implementation of `to_char()` for dates, referenced 
https://github.com/cockroachdb/cockroach/issues/3781
and
attempted here https://github.com/cockroachdb/cockroach/pull/7976

**Comment by yznming** [comment]
@andreimatei got it, I will try to implement  to_char(interval, text)

**Comment by yznming** [comment]
@andreimatei Got it. We are going to implement the to_char(timestamps, text) compatible with PG style, right? As I know, the PG supports lots kind of date time formats, and implements a complex parser framework(more than 1k C code). I'm sorry that I have no idea to implements it in a easy way. I would appreciate if you could suggest more advice here, thanks.

**Comment by andreimatei** [comment]
Sorry, I don't have any suggestions And I'm not really familiar with what `to_char()` supports in Postgres. But FWIW we'd accept an incomplete implementation; supporting most common formats is better than nothing.

**Comment by bdarnell** [comment]
`to_char(timestamp)` is very complicated. @andreimatei Do you specifically need `to_char()` or can you use `strftime()` instead (which we already support)? 

I don't think partial support for `to_char()` is a good idea. We should either support the whole thing to be compatible with postgres, or we should leave it out and tell people to use `strftime()` instead.

**Comment by bdarnell** [comment]
There's also discussion of this in #9790.

**Comment by andreimatei** [comment]
ah, we have `experimental_strftime` :). I missed that. Yeah, that's probably good enough.
I guess if we have this, partial support of something else is indeed not a good idea.

**Comment by knz** [comment]
@andreimatei could you PR your sum(interval)? I happen to want to use it too :)
