### ISSUE TITLE
sql:  support OUT, INOUT argmode in UDF 

### ISSUE THREAD

**Issue by lyang24** [cockroachdb/cockroach#100405]
**Is your feature request related to a problem? Please describe.**
In crdb 21.3 users cannot define UDFs with OUT, INOUT param.
For an example:
```
CREATE FUNCTION add_em (IN x int, IN y int, OUT sum int)
AS 'SELECT x + y'
LANGUAGE SQL;
```
resulted in 
`invalid syntax: statement ignored: at or near "out": syntax error: unimplemented: this syntax`.

**Describe the solution you'd like**
would like crdb to support UDFs creation with `OUT `and `INOUT ` arg mode.
example behavior in postgresSql
```
postgres=# CREATE FUNCTION add_em (IN x int, IN y int, OUT sum int)
AS 'SELECT x + y'
LANGUAGE SQL;
CREATE FUNCTION
```

**Additional context**
[postgres docs](https://www.postgresql.org/docs/current/sql-createfunction.html)

Epic: CRDB-30611
Jira issue: CRDB-26414

**Comment by rharding6373** [comment]
Thanks for the report! This is a feature that has been on our minds as we expand UDF functionality, but it appears we did not have an issue to track it until now.

**Comment by rharding6373** [comment]
Related issue: https://github.com/cockroachdb/cockroach/issues/87705

**Comment by rharding6373** [comment]
I've documented some of the "interesting" behavior of OUT/INOUT params that I've experimented with so far: https://gist.github.com/rharding6373/15f7384dea9f604b556edbfd27ee29b7
