### ISSUE TITLE
cli: strings that look like numbers are aligned incorrectly

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#10042]
Looks like some pretty printer somewhere is overzealous in recognizing numbers, and aligns them right instead of left. This most annoyingly happens when the apparent numbers are a result of a `substr()` operation, and some results suddenly get aligned differently than the rest.

We should look at the type of the result, if at all possible, or at least at all the results in that column.

```
root@:26258> SELECT '0'::text as XXXXX;
+-------+
| XXXXX |
+-------+
|     0 |
+-------+
(1 row)
root@:26258> SELECT '0s'::text as XXXXX;
+-------+
| XXXXX |
+-------+
| 0s    |
+-------+
```

**Comment by knz** [comment]
This is a "feature" of the upstream package https://github.com/olekukonko/tablewriter/.

**Comment by a6802739** [comment]
@andreimatei , I could try to fix it now.

**Comment by andreimatei** [comment]
@a6802739 that'd be great! :)
But note what @knz said above, about the problem being upstream. Looking at the README of that tablewriter, I see "Support custom alignment" as a TODO. Maybe this bug plays into that.

**Comment by a6802739** [comment]
@andreimatei, thanks for you reference. could you please help me review the PR #10052 that intend to fix the issue #9220, I would appreciate it.

**Comment by knz** [comment]
@a6802739 We really like your participation, but please refrain from creating links between issues that are wholly unrelated like this. 

If you want someone to look at one of your PRs, send us a message on Gitter or post a comment on the PR where you want attention, with a mention of the person ("@" followed by their username). 

Right now you have created a link between PR 10052 and 10042 which will now be displayed by Github forever. That was unnecessary and is also somewhat distracting.

**Comment by a6802739** [comment]
@knz , sorry for what I have done.

I apologize for this mistake I have made.

Thanks for your remind.

**Comment by knz** [comment]
Don't worry about it :)
We all make mistakes!
