### ISSUE TITLE
`unaccent()` function strips spaces

### ISSUE THREAD

**Issue by coreh** [cockroachdb/cockroach#100407]
**Describe the problem**

The `unaccent()` function seems to be [discarding space characters](https://github.com/cockroachdb/cockroach/blob/1e27c65fb5a3810a5e2285cf07b45d95d401cca6/pkg/util/unaccent/unaccent.go#L431), which as far as I can tell is not the expected behavior in PostgreSQL.

**To Reproduce**

Run the following query:

```sql
SELECT unaccent('Héllô Wõrld!');
```

**Expected behavior**

```
Hello World!
```

**Observed behavior**

```
HelloWorld!
```

**Environment:**
- CockroachDB CCL v22.2.7 (x86_64-pc-linux-gnu, built 2023/03/28 19:47:29, go1.19.6)
- `cockroach sql`, macOS 13.2.1, version details:
  - Build Tag:        v22.2.6
  - Build Time:       2023/03/03 19:41:42
  - Distribution:     CCL
  - Platform:         darwin amd64 (x86_64-apple-darwin19)
  - Go Version:       go1.19.4
  - C Compiler:       Clang 10.0.0 
  - Build Commit ID:  d5a076f2953c0712193b8cbe08bbb682563c5675
  - Build Type:       release

Jira issue: CRDB-26415

**Comment by semnell** [comment]
Is there any reason this hasn't been done yet? This seems incredibly easy (the removal of 1 line of code).
