### ISSUE TITLE
bulk, tracing: clean up TracingAggregator

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#100438]
Quoting Andrei from [here](https://github.com/cockroachdb/cockroach/pull/98831#pullrequestreview-1361984655):

> I think better yet by reworking the `TracingAggregator` to not call `SetLazyTag` from the event handler.
Instead, I think it'd be better if `TracingAggregator` would attach one single lazy tag at construction time
(instead of attaching them dynamically, one lazy tag per "event tag") , and the lazy tag would be in charge
of iterating through the `b.mu.aggregatedEvents` map and rendering all the events.

Jira issue: CRDB-26435

**Comment by adityamaru** [comment]
The tracing aggregator no longer implements the LazyTag interface so closing this as won't fix.
