### ISSUE TITLE
opt: infinite recursion between EliminateGroupByProject and PruneGroupByCols

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#100478]
Some queries can cause the optimizer to recurse indefinitley between two normalization rules, `EliminateGroupByProject` and `PruneGroupByCols`. Below is an optimizer test that reproduces the infinite recursion:

```
exec-ddl
CREATE TABLE p (
  region STRING NOT NULL,
  id INT,
  PRIMARY KEY (region, id),
  UNIQUE INDEX p_id_idx (id)
)
----

exec-ddl
CREATE TABLE c (
  region STRING NOT NULL,
  id INT PRIMARY KEY,
  p_id INT NOT NULL,
  FOREIGN KEY (region, p_id) REFERENCES p (region, id)
)
----

norm
SELECT p.id FROM p JOIN c ON p_id = p.id GROUP BY p.id
----
```

Jira issue: CRDB-26457

**Comment by DrewKimball** [comment]
@mgartner are you looking at this one? If not I can take it.

**Comment by mgartner** [comment]
@DrewKimball it's all yours :)

**Comment by msirek** [comment]
I'm unable to reproduce this. Not sure what I'm doing wrong.  I'm running the exact optimizer test posted above against the latest master.

**Comment by mgartner** [comment]
It's still reproducing for me on master@`3d96b136c`. How are you running the test? If you're running it in a way such that the [`crdb_test` build flag](https://github.com/cockroachdb/cockroach/blob/f606f150c132e9d4dfa1bc849b64d873d3f7ab08/pkg/util/buildutil/crdb_test_on.go#L12) is not used, then the error will not trigger because we simply stop recursing when we detect a cycle and silently move on with optimization:

https://github.com/cockroachdb/cockroach/blob/2014cf267d18b2c701f8e894cc74d85ff27d6a91/pkg/sql/opt/norm/factory.go#L400-L412

**Comment by mgartner** [comment]
If you run with `./dev test` it should work, for example: `./dev test './pkg/sql/opt/norm' -f 'TestNormRules/__test'`.

**Comment by msirek** [comment]
I was able to reproduce it with that `dev test` statement, but not in Goland.  Maybe my Goland environment is not correct.

**Comment by mgartner** [comment]
@msirek maybe your missing `-tags=crdb_test` in "Go tool arguments"?

<img width="701" alt="image" src="https://user-images.githubusercontent.com/1128750/230397047-5720d17d-933f-4be9-8266-f6e77e4460a3.png">
