### ISSUE TITLE
jwtauthccl: timeout in TestSubjectCheck

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#100546]
Test timed out here: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/9415433?showRootCauses=true&expandBuildProblemsSection=true&expandBuildChangesSection=true&expandBuildTestsSection=true

Jira issue: CRDB-26482

**Comment by rytaft** [comment]
cc @kpatron-cockroachlabs

**Comment by yuzefovich** [comment]
dup of #100356
