### ISSUE TITLE
sql: distsql planning should avoid sending flows to SQL servers in the process of starting up, and in the process of shutting down

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#100578]
New description: we would like a new field in the sql instances table that indicates node readiness.

This would not be set to "ready" before server startup has completed; and it would also be set to a different value during graceful shutdown.

Distsql planning should avoid nodes based on that field.

----

Original title: **jobs,upgrades: deadlock during migrations when initializing multiple servers for 1 tenant**

**Describe the problem**

While investigating #100436 I discovered the following deadlock:

1. create a new tenant record; no server running yet. At this point the tenant keyspace is empty *and it has not run its migrations yet*
2. start **two or more servers for that tenant simultaneously**  (this is important)
3. observe: often, the tenant servers deadlock.

The underlying problem is the following:

- when the tenant servers **begin** their startup, they immediately populate a SQL instance row in the liveness table. **However at that time they are not yet ready to process SQL queries because their migrations have not run yet**
- then, one of the two will start running the upgrade migrations.
- one of these migrations will need a distsql distributed query. That, in turn, will fail because the other server(s) are not yet ready to accept distsql execution:

```
I230404 10:23:32.796367 15064 upgrade/upgrademanager/manager.go:235 ⋮ [T2,n2] 534  the last permanent upgrade (v1000022.2-94) does not appear to have completed; attempting to run all upgrades
I230404 10:23:32.796659 15064 upgrade/upgrademanager/manager.go:278 ⋮ [T2,n2] 535  running permanent upgrade for version 0.0-2
I230404 10:23:32.824530 15776 1@circuitbreaker/circuitbreaker.go:322 ⋮ [T2,n2] 545  circuitbreaker: ‹rpc 127.0.0.1:64403 [n1]› tripped: unable to look up descriptor for n1: non existent SQL instance
I230404 10:23:32.824557 15776 1@circuitbreaker/circuitbreaker.go:447 ⋮ [T2,n2] 546  circuitbreaker: ‹rpc 127.0.0.1:64403 [n1]› event: ‹BreakerTripped›
W230404 10:23:32.824573 15776 sql/colflow/colrpc/outbox.go:189 ⋮ [T2,n2,intExec=‹select-job›,f‹0f758d2f›,distsql.stmt=‹WITH latestpayload AS (SELECT job_id, value FROM system.job_info AS payload WHERE (info_key = '_') AND (job_id = $1) ORDER BY written DESC LIMIT _), latestprogress AS (SELECT job_id, value FROM system.job_info AS progress WH
ERE (info_key = '_') AND (job_id = $1) ORDER BY written DESC LIMIT _) SELECT status, payload.value AS payload, progress.value AS progress, claim_session_id, COALESCE(last_run, created), COALESCE(num_runs, _) FROM system.jobs AS j INNER JOIN latestpayload AS payload ON j.id =›,distsql.gateway=‹2›,distsql.appname=‹$ internal-select-job›,distsq
l.txn=‹b8a5af83-f1f1-4364-9074-5e4bc41d66f5›,streamID=‹9›] 547  Outbox Dial connection error, distributed query will fail: unable to look up descriptor for n1: non existent SQL instance
```

**Expected behavior**

DistSQL should recognize when other SQL instances are not yet ready to process queries and not attempt to use them.

Alternatively we could disable DistSQL entirely during upgrade migrations; but that seems undesirable because certain migrations rewrite tables and that would benefit from the extra concurrency.

Jira issue: CRDB-26509

Epic CRDB-39091

**Comment by knz** [comment]
I discovered this in TestServerControllerMultiNodeTenantStartup.

The reason why this doesn't seem to fail in our other tests is that the other tests either don't use multi-node clusters, or only start 1 tenant server at a time. In that case there is no trouble.

**Comment by knz** [comment]
We discussed internally. The focus should really be here:
> DistSQL should recognize when other SQL instances are not yet ready to process queries and not attempt to use them.

What we miss is a new **status column in the sql liveness table** which informs when an instance _exists_ but is _not yet ready_ (or not any more).

This column would be updated during server startup, and also during graceful drain.

We probably would benefit from this as well in the single-tenant case.

**Comment by mgartner** [comment]
@yuzefovich does it make sense to include this in some of the multi-tenant work this cycle?

**Comment by yuzefovich** [comment]
Yeah, I believe I'll be working on this for 23.2.

**Comment by dt** [comment]
I would love to chat, or review a doc, before impl here kicks off since I have a hope that we could use the opportunity to switch the roles of liveness and instance tables while we’re messing with them

**Comment by yuzefovich** [comment]
@dt would you be so kind to write down here, at the high level, what we talked about last week please?

**Comment by mgartner** [comment]
@yuzefovich was this recently addressed by retrying?

**Comment by yuzefovich** [comment]
This was mostly addressed, yes, but more work remains on reducing the likelihood and the duration of the time interval when these retries are needed. Some more context can be found in https://cockroachlabs.atlassian.net/browse/CRDB-26692?focusedCommentId=184545
> - introduce “draining” state to SQL instances to allow for remote DistSQL work to be scheduled / completed.
> - reduce the time it takes for the in-memory instance cache to find out that a SQL instance is no longer available for DistSQL planning. At some David shared his vision with me that we’d be able to reduce this window from current 45s to something on the order of 7s (this will require adjusting the system tables). We won’t get to it in 23.2 timeframe.

(Perhaps more.) We don't plan to do more work in 23.2 on this, so I'll move to next release.
