### ISSUE TITLE
jwtauthccl: timeout in TestSubjectMappingCheck

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#100547]
Test timed out here: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/9416599?showRootCauses=true&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

Jira issue: CRDB-26483

**Comment by rytaft** [comment]
cc @kpatron-cockroachlabs

**Comment by yuzefovich** [comment]
dup of #100356
