### ISSUE TITLE
Incorrect result by subquery and join

### ISSUE THREAD

**Issue by DerZc** [cockroachdb/cockroach#100561]
**Describe the problem**

consider the following program:

```
CREATE DATABASE database1;
USE database1;

CREATE TABLE t0 (c0 SERIAL2);
CREATE TABLE t1 (c0 BYTES);

UPSERT INTO t1 (rowid) VALUES(1);

SELECT temp_table3.c2, temp_table3.c0 FROM (SELECT t1.c0 AS c0, t1.rowid AS c2 FROM t0 FULL OUTER JOIN t1 ON true ) AS temp_table3, t1 WHERE (temp_table3.c2) = (t1.rowid);  -- 1 | NULL

WITH temp_table3(c0, c2) AS (SELECT t1.c0 AS c0, t1.rowid AS c2 FROM t0 FULL OUTER JOIN t1 ON true ) SELECT ALL temp_table3.c2, temp_table3.c0 FROM temp_table3, t1 WHERE (temp_table3.c2) = (t1.rowid);  -- empty result
```

There two queries are equivalent and just put the subquery at different place. but the second query has empty results. I manually analyze it and think it should have the same result with the first query.

Also, if I remove the output column `temp_table3.c0` of the second query, it will have `1` as result. This should not affect the result.

**To Reproduce**

this bug can reproduce with the last commit version (07c7d4b) and last release version (v22.2.7).

I run the cockroachdb in a single machine and execute this program with CLI

**Expected behavior**
The second query has the same results with the first one.

**Environment:**
 - CockroachDB version [last commit version and last release version]
 - Server OS: [ubuntu 22.04]
 - Client app [CLI]

Jira issue: CRDB-26494

**Comment by yuzefovich** [comment]
Thanks for the report! Indeed, both queries seem to be equivalent, and I believe they should return 1 row in the result. I also confirmed that this bug is present on master, 22.2.6, and 22.1.13, so it's not a recent regression.

**Comment by DerZc** [comment]
Thank you for your confirmation. Very happy this report was helpful to you.

**Comment by mgartner** [comment]
Here's a simplified reproduction:

```sql
CREATE TABLE a (a INT);
CREATE TABLE bc (b INT, c INT);

INSERT INTO bc (b) VALUES(1);

SELECT * FROM (
  SELECT bc.c + 1 AS y, bc.b + 1 AS x
  FROM a FULL OUTER JOIN bc ON true
) tmp, bc
WHERE tmp.x = bc.b + 1;
```

It returns a single row in Postgres but no rows in CRDB.

**Comment by mgartner** [comment]
The bug is in the `RejectNullsProject` rule. In some cases it can create null-rejecting filters for all of the columns that are candidates for null-rejection, not just the ones that can _actually_ be null-rejected. The fix should be fairly simple.

I'm still trying to figure out how easy it is to hit this bug. It's been present since the `RejectNullsProject` rule was introduced in 20.2, which tells me that it's very rare. It's also difficult to concoct other reproductions.
