### ISSUE TITLE
multiregionccl: TestRegionalByRowTablesInTheSystemDatabase flaked

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#100504]
https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/9407697?showRootCauses=false&expandBuildProblemsSection=true&expandBuildTestsSection=true (in the CI for https://github.com/cockroachdb/cockroach/pull/100374)

```
Failed
=== RUN   TestRegionalByRowTablesInTheSystemDatabase
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/4e205632d040cd50e013d41c1f6bd71a/logTestRegionalByRowTablesInTheSystemDatabase127028194
    test_log_scope.go:79: use -show-logs to present logs inline
    regional_by_row_system_database_test.go:48: error executing 'ALTER DATABASE system SET PRIMARY REGION "us-east1";': pq: multi region system database is not supported
```

cc @ajwerner is this similar to https://github.com/cockroachdb/cockroach/issues/100404 ?

Jira issue: CRDB-26469

**Comment by ajwerner** [comment]
This was just a bug in that PR because I had not also backported https://github.com/cockroachdb/cockroach/pull/99713. I added that commit to the backport. Closing this issue.
