### ISSUE TITLE
storage: Excessive cgo memory usage

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#10050]
On delta, nodes are using 14GB (of 16GB total) in cgo memory usage and some nodes are consistently running out of memory completely. The rocksdb cache is configured to use 4GB (i.e. 25% of the total). These nodes are configured with two stores each, but even doubling the cache for the two stores would not account for all the memory used.

From the jemalloc profile:
```
(jeprof) top
Total: 13701.3 MB
 12415.8  90.6%  90.6%  13667.9  99.8% rocksdb::ReadBlockContents
  1252.1   9.1%  99.8%   1252.1   9.1% rocksdb::UncompressBlockContents
    12.1   0.1%  99.8%     12.1   0.1% rocksdb::::ShardedLRUCache::Insert
    10.5   0.1%  99.9%   5185.7  37.8% rocksdb::::ReadBlockFromFile
     3.5   0.0%  99.9%      3.5   0.0% std::string::_Rep::_S_create
     2.3   0.0% 100.0%      2.3   0.0% rocksdb::Arena::AllocateNewBlock
     1.0   0.0% 100.0%   9554.2  69.7% rocksdb::BlockBasedTable::Open
     1.0   0.0% 100.0%   1056.4   7.7% rocksdb::BlockBasedTable::CreateIndexReader
     0.5   0.0% 100.0%      0.5   0.0% rocksdb::CreateDBStatistics
     0.5   0.0% 100.0%      4.0   0.0% rocksdb::ReadProperties
```

This SVG shows that a couple of different code paths are responsible for the memory: 4GB comes from the cockroachdb DBIterNext function, and 9GB in the rocksdb TableCache code: https://www.dropbox.com/s/ao7z1un32b6jkah/jeprof-20161018.svg?dl=0

**Comment by petermattis** [comment]
Ah, the 9GB of data allocated via the `BlockBasedTable::Open` path is for "index" blocks which we currently have configured to reside outside of the block-cache (there are performance reasons for doing this). The upshot is that we have 4GB in the block-cache and 9GB outside of the block-cache (which is pinned in memory). I'm curious why the table index data is so large as I recall looking at this in the past and seeing that it was a reasonable size.

**Comment by petermattis** [comment]
I had a calculation at one point to estimate the size of the index and filter data from the raw data. I need to resurrect/recreate that formula and make sure that it is in line with what we're seeing on delta.

**Comment by petermattis** [comment]
The size of index data in an sstable is `num_data_blocks * (avg_key_size + 20)`. The size of filter data is `num_entries * 2.5`. When the value size is small, the filter size tends to dominate. On delta we see that the filter is `2.2% * data_size`. 

We currently have our bloom filter configured to use 10 bits (1.25 bytes) per key, so I'm not quite sure why the filter is using almost exactly double that number. The 10 bits per key value translates into ~1% false positive hit rate according to the RocksDB docs. We could reduce the number of bits per key, but that seems fraught.

Update: Ah, figured out why we're actually using 20 bits per key for filtering. We have `BlockBasedTableOptions::whole_key_filtering` set to true which means we had a bloom filter entry for both the whole key and the extracted prefix. `whole_key_filtering` is used to speed up `Get` which we don't use. I think we can cut our filter size in half by disabling that without any performance impact.

**Comment by petermattis** [comment]
The math to compute the false positive rate for a bloom filter is:

```
m = ceil((n * log(p)) / log(1.0 / (pow(2.0, log(2.0)))));
k = round(log(2.0) * m / n);
```

Where:

```
n Number of items in the filter
p Probability of false positives, float between 0 and 1 or a number indicating 1-in-p
m Number of bits in the filter
k Number of hash functions
```

This is more or less the math used in RocksDB. Here are the false positive rates for various bits per key:

```
5  - 9%
6  - 6%
7  - 3.5%
8  - 2.2%
9  - 1.3%
10 - 0.9%
```

When a false positive occurs we fall back to searching in the index. This isn't horrible as the index is still in memory.

**Comment by petermattis** [comment]
A more radical thought is to completely disable the bloom filters. Some simple testing shows a modest performance hit (~3%) to disabling the bloom filters, which can be more than alleviated with other performance work such as #9993. The question is whether the workloads (`block_writer` and `photos`) in my simple testing are representative. I should probably run the `sql` and `storage/engine` benchmarks as well.

**Comment by bdarnell** [comment]
> When a false positive occurs we fall back to searching in the index. This isn't horrible as the index is still in memory.

A false positive means scanning the index and reading at least one block from disk, doesn't it? The index only contains block boundaries. 

> The question is whether the workloads (block_writer and photos) in my simple testing are representative. I should probably run the sql and storage/engine benchmarks as well.

`block_writer` is write-only so it shouldn't see much benefit from the bloom filters (just the reads that the system does internally during writes). For read-heavy workloads I think the bloom filters make a huge difference (I know they did in bigtable). In bigtable bloom filters were opt-in on a per-table basis, and the memory they used was properly accounted for in your project's memory budget.

**Comment by petermattis** [comment]
> A false positive means scanning the index and reading at least one block from disk, doesn't it? The index only contains block boundaries.

Yes, you'd need to read at least one block as well.

> `block_writer` is write-only so it shouldn't see much benefit from the bloom filters (just the reads that the system does internally during writes). 

As mentioned elsewhere, the bloom filters primarily help with the internal reads the system does during writes.

> In bigtable bloom filters were opt-in on a per-table basis, and the memory they used was properly accounted for in your project's memory budget.

If we set the `cache_index_and_filter_blocks` the index and filter blocks would be placed in the block-cache. Or is "properly accounted for in your project's memory budget" referring to something else.

**Comment by bdarnell** [comment]
> Or is "properly accounted for in your project's memory budget" referring to something else.

I meant that everything was tracked on a per-project/per-table basis: you could find out how much memory was being used in the cluster for bloom filters of tables belonging to project X (and conversely, assuming you had the budget for it, you were guaranteed that your bloom filters would be loaded without relying on the whims of the cache). Our monolithic rocksdb doesn't let us track things at that level.
