### ISSUE TITLE
roachtest: refactor actual tags assigned to tests

### ISSUE THREAD

**Issue by smg260** [cockroachdb/cockroach#100605]
Today, when working with roachtest tags: 
- If a roachtest has no user assigned tag, the "default" tag is added
- All "default" tagged roachtests are assumed to run on GCE
- Said roachtests run daily, unless user tagged "weekly"
- Only tests tagged "aws" will run on AWS ([recently updated from a gnarly name regex](https://github.com/cockroachdb/cockroach/pull/99402))

This is confusing in several ways:
- Inconsistency in selecting jobs for different clouds. GCE and local is assumed, AWS is explicit
- Cadence is specified by "weekly" or "aws-weekly" (gce again implied)
- If a user adds any "tag", it will have the unexpected consequence of stopping the test from being assigned the "default" tag, which would then exclude it from running in GCE 

The existing tags should be refactored to make it easy for a user or TC job to select relevant roachtests. Some things that can be implemented:
- Explicitly naming clouds (no more assume GCE)
- Adopt a "cloud-cadence" tag and assign to all tests. e.g. `aws-weekly,gce-daily`. This would allow us to categorise tests easily according to existing TeamCity jobs (gce/aws daily/weekly)
- Sensible tags added at runtime (like what we do now for "default"). e.g. If no cloud-cadence tags, add "all-daily" tag to run on as default. 

We could also more narrowly selecting relevant tests, and skip logging"Ignored" tests in the TC UI. `roachtest run tag:aws-daily` would show *only* those that are supposed to run. 

Jira issue: CRDB-26519

**Comment by RaduBerinde** [comment]
I'd be willing to look at fixing this mess. @smg260 could you explain exactly how the current logic works? Specifically, I'd like to fill in this table of what tags are required for a test to run. I started with my current hunches based on looking at the scripts but these might be wrong, please take a look and help me correct them.

|    | GCE | AWS | 
|---| --- | --- |
| Nightly  |  aws or default or no tags | aws |
| Weekly  | weekly | aws-weekly |

**Comment by RaduBerinde** [comment]
What are the other tags (like `smoketest`, `orm` used for?) Are there builds that select for those tags?

**Comment by RaduBerinde** [comment]
Here's my current thinking. We replace the tags with two separate concepts:
 - `CompatibleClouds`: a subset of `[local, gce, aws]`, all of them by default. Test definitions can use convenience constants like `OnlyGCE`, `NoAWS`.
 - `TestSuites`: a set of "test suites" that the test is part of. By default `[nightly]`. Other values can be `weekly`, `release-qualification` etc

You can run roachtest using specific test name(s) OR by specifying `--suite X` which will select all tests in that suite which are compatible with the `--cloud`.

Going over all the test definitions will be tedious, but it doesn't have to be error-prone: I can keep the tags while developing and add an assertion that the values of the new fields are consistent with the tags. I can remove the tags afterwards.

**Comment by srosenberg** [comment]
> What are the other tags (like `smoketest`, `orm` used for?) Are there builds that select for those tags?

That's essentially the problem with the current implementation of `tags`; anyone can add a tag, and its meaning is very loosely defined. I am not aware of how these specific tags are used. If there is no mention of them in CI scripts, then `git blame` is probably the best way to find out their intended use cases.

**Comment by renatolabs** [comment]
> Here's my current thinking. We replace the tags with two separate concepts:

Dropping by to say the change you propose would be a huge improvement, thanks for looking into this.

**Comment by smg260** [comment]
The `default` tag is added by roachtest if no other tags are present [1].

The concept of compatible clouds would be welcome, and is covered in a separate issue [2], linked above already.

There is no doubt that tags are (mis)used today, but I think when used properly for searching and categorising, it can still prove useful. 

A few examples:

-  list/run all tests owned by a particular team; `roachtest list tag:owner-cdc`
-  perhaps using it to label all benchmarks, which can then be selected in combination with team tags above
-  individual teams labelling a selection of tests to run more frequently as smoke tests for changes

Of course, this all depends on maintaining the tags. I don't feel it necessary to remove them, but do agree that depending on them for other programmatic or scripting use cases (like in CI), is confusing and unclear. 


[1] - [default tags](https://github.com/cockroachdb/cockroach/blob/685ce2c6ccd6b9b371b361553b6273e3c464ee8a/pkg/cmd/roachtest/test_registry.go#L136-L138)

[2] - [compatible clouds](https://github.com/cockroachdb/cockroach/blob/685ce2c6ccd6b9b371b361553b6273e3c464ee8a/pkg/cmd/roachtest/test_registry.go#L136-L138)

**Comment by RaduBerinde** [comment]
> The default tag is added by roachtest if no other tags are present [1].

Yes, but `default` is also added manually (e.g. `registry.Tags(`default`, `orm`),`) in a lot of cases which adds to the confusion.

I'm not convinced generic, arbitrary string tags are the best way to solve the examples you quoted. If we want an owner, we should have an `Owner` field. If we want some flags (like is-benchmark or whatnot), those can just be bools in a struct. Selections of tests would be solved by the test suites I mentioned.

**Comment by smg260** [comment]
Agreed - I'm not saying it's a good implementation, and I'm in support of your proposal. I was just pointing out that tags as a concept, taken as simple metadata, could have a place.
