### ISSUE TITLE
util/metric: agg histogram shows monotonically increasing values

### ISSUE THREAD

**Issue by jayshrivastava** [cockroachdb/cockroach#100630]
I've created two histograms. One is a [normal histogram](https://github.com/jayshrivastava/cockroach/commit/5bb34fa6dd428879463b0095dd47c5c6a84f0af7) and one is an [agg histogram](https://github.com/jayshrivastava/cockroach/blob/5bb34fa6dd428879463b0095dd47c5c6a84f0af7/pkg/ccl/changefeedccl/metrics.go#L597-L603). Calling `RecordValue` on the normal histogram results in the graph looking like this:
<img width="1008" alt="image" src="https://user-images.githubusercontent.com/18633281/229897664-a48737fe-dc5d-4ea9-9812-977ecccd7c50.png">
The value on the Y axis is reset back to 0 after some time. I can call `RecordValue` and have the new values show up on the graph. 

The agg histogram looks like this: 
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/18633281/229897470-ca1b17c6-0e63-446b-84d7-f95a561c5cd8.png">
The problem is the graph shows the maximal value seen since I started the node (24.78s) even though I've called `RecordValue` with lower values. The graph only changes when I call `RecordValue` with a larger value than 24.78s.

It seems that the agg histogram is persisting data when it should not be.

Jira issue: CRDB-26530

**Comment by samiskin** [comment]
<img width="1006" alt="Screenshot 2023-04-18 at 3 35 15 PM" src="https://user-images.githubusercontent.com/6236424/232886187-a738e94e-8431-4ad3-80fb-c39ccff7c9f7.png">

@jayshrivastava  seems to be able to descend for me when I have:
```
    <LineGraph
      title="Commit Latency"
      tooltip={`The difference between an event's MVCC timestamp and the time it was acknowledged as received by the downstream sink.`}
      isKvGraph={false}
      sources={storeSources}
    >
      <Axis units={AxisUnits.Duration} label="commit latency">
        <Metric
          name="cr.node.changefeed.commit_latency-p99"
          title="99th Percentile"
          downsampleMax
        />
        <Metric
          name="cr.node.changefeed.commit_latency-p90"
          title="90th Percentile"
          downsampleMax
        />
        <Metric
          name="cr.node.changefeed.commit_latency-p50"
          title="50th Percentile"
          downsampleMax
        />
      </Axis>
    </LineGraph>,
```

Maybe its just to do with p99 🤔

**Comment by jayshrivastava** [comment]
This is the exact code I had. Interesting... https://github.com/jayshrivastava/cockroach/commit/5bb34fa6dd428879463b0095dd47c5c6a84f0af7#diff-ec033be3bf0ce6dd0ca1f16617e9cb9f183bf4b8e9dfc3bf1cb49403e1893e7e

**Comment by samiskin** [comment]
@jayshrivastava I tried again where both had the same data 
```
ca.recentKVCount++
ca.metrics.CommitLatency2.RecordValue(timeutil.Since(event.Timestamp().GoTime()).Nanoseconds())
ca.sliMetrics.CommitLatency.RecordValue(timeutil.Since(event.Timestamp().GoTime()).Nanoseconds())
```
And got this:
<img width="658" alt="Screenshot 2023-04-19 at 12 38 49 PM" src="https://user-images.githubusercontent.com/6236424/233142710-fe97f574-2a59-4561-8f64-c9d37c07d4c8.png">

The AggHistogram value seems to be averaged across a longer period of time compared to the Histogram, but it does still go down and match the value I'd expect for an averaged version of the Histogram values, so perhaps its safe enough for #98086

**Comment by jayshrivastava** [comment]
@samiskin Ack! Since we don't have a repro, I'll close this issue.
