### ISSUE TITLE
jobs: `waitForJobs` hangs on server shutdown

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#100660]
Found while stressing `TestServerControllerMultiNodeTenantStartup`. This is blocking progress on #100436.

If the `poll-show-jobs` query is unable to reach the remote server while the server is shutting down, the retry loop in `waitForJobs()` never terminates and the graceful shutdown of the jobs registry deadlocks.

This particular issue is a variant of the more general problem described in #100659.

Jira issue: CRDB-26538

**Comment by adityamaru** [comment]
@knz based on Radu's latest comments on https://github.com/cockroachdb/cockroach/issues/100659 do you still think this issue is because of the `StartWithCtx` API?

**Comment by knz** [comment]
No; also I found the cause of the problem and fixing it in a different PR. (#101296) Nothing left to do here.
