### ISSUE TITLE
cdc: case insensitive sink config

### ISSUE THREAD

**Issue by HonoreDB** [cockroachdb/cockroach#100706]
See https://github.com/cockroachlabs/support/issues/2208

Since most of our WITH options are now case-insensitive, it's surprising when the sink JSON config isn't. For enums in particular like compression codecs, we should either be case insensitive or have better error messages that list all valid values. 

Jira issue: CRDB-26587

Epic CRDB-8667

**Comment by amruss** [comment]
Can we assume every option is case insensitive? We could manually determine which ones are case insensitive and which are not
