### ISSUE TITLE
sql: Hibernate should work with CockroachDB

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#10079]
Hibernate currently works to a certain degree with Cockroach, but it breaks down when it attempts to use the Postgres JDBC driver to perform complicated metadata reflection. We should get it fully working.

Blocking Issues:
- [x] #10072 (`pg_type`)
- [x] #10073 (`pg_am`)
- [x] #10074 (`pg_description`)
- [x] #10075 (`pg_proc`)
- [x] #10076 (`pg_database`)
- [x] #10077 (`pg_roles`)
- [x] #10078 (`pg_settings`)
- [x] #10416 (`pg_index`)
- [x] #10521 (`pg_depend`)
- [x] #9990 (full support for OIDs)
- [x] #10633 (ensure that common implicit cross-joins don't explode)
Non-Blocking Issues:
- [ ] #8862

**Comment by cuongdo** [comment]
Thanks for filing these issues @nvanbenschoten. Would you mind indicating which ones are appropriate for SQL newbie / starter projects?

**Comment by nvanbenschoten** [comment]
All of the blocking issues should be appropriate for people new to SQL. The non-blocking issues are both a little larger in scope, and will require a deeper understanding of the SQL code.

**Comment by a6802739** [comment]
@nvanbenschoten, maybe I could fix some blocking Issues :)

**Comment by nvanbenschoten** [comment]
@a6802739 Would you want to try tackling #10078?

**Comment by a6802739** [comment]
@nvanbenschoten, yeah, I would like to do that.

**Comment by crackerplace** [comment]
@nvanbenschoten I would like to work on one issue among these.Could you let me know any one.Thanks.

**Comment by cuongdo** [comment]
This works now, with docs and a CI test in `examples-orms`
