### ISSUE TITLE
schemachangerccl: TestBackupMixedVersionElements skipped

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/cockroach#100732]
Skipped in #100326 to unblock a release blocker. The test appears to hang waiting for a GC job to complete during upgrade.

https://teamcity.cockroachdb.com/viewLog.html?buildId=9440279&tab=buildResultsDiv&buildTypeId=Cockroach_Ci_TestsGcpLinuxX8664BigVm_CclUnitTests

Jira issue: CRDB-26602

**Comment by fqazi** [comment]
This is linked to waitForDelRangeInGCJob including jobs in the state SchemaChangeGCProgress_WAITING_FOR_CLEAR state, which includes things waiting for GC TTL. Not sure what would have prevented these from being counted before, except for the cluster setting state that made this upgrade a no-op.
