### ISSUE TITLE
kv: audit kv upgrade tests

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#100721]
See #100552.

The following are owned by kv:

- [ ] TestLoadBasedRebalancingObjective (Austen)
- [ ] TestRebalanceObjectiveManager (Austen)
- [x] TestStoreConfig (Nathan)
- [x] TestDeclareKeysResolveIntent (Arul)

See https://github.com/cockroachdb/cockroach/issues/100552#issuecomment-1497376722 for @aliher1911's audit of the replication tests.

Jira issue: CRDB-26598

**Comment by kvoli** [comment]
TestLoadBasedRebalancingObjective only uses the version (v22.2) to test the version gate as one of the sub-tests.
TestRebalanceObjectiveManager ditto.
