### ISSUE TITLE
cdc: add Azure Event Hub endpoint to Kafka tests

### ISSUE THREAD

**Issue by shermanCRL** [cockroachdb/cockroach#100815]
**Is your feature request related to a problem? Please describe.**

We’d like to document official support for Azure Event Hubs. They [promise Kafka compatibility](https://learn.microsoft.com/en-us/azure/event-hubs/azure-event-hubs-kafka-overview) and @dbist has [demonstrated compatibility with CRDB](https://dzone.com/articles/using-cockroachdb-cdc-with-azure-event-hubs).

**Describe the solution you'd like**

Use an Azure Event Hubs endpoint in our Kafka tests.

Epic CRDB-18958

Jira issue: CRDB-26638

**Comment by amruss** [comment]
Blocked by: https://github.com/cockroachdb/cockroach/issues/105580
