### ISSUE TITLE
cli: add flag for external address for internode-communication

### ISSUE THREAD

**Issue by spencerkimball** [cockroachdb/cockroach#1008]
This will be necessary for spanning cloud service infrastructure.

**Comment by petermattis** [comment]
@spencerkimball Can you clarify or close this issue?

**Comment by tamird** [comment]
We want to advertise a different address than the one used for listening, so that nodes with non-routable local IPs which have separate routable external IPs can be reached. This was discussed in this week's core meeting.

**Comment by spencerkimball** [comment]
Why wouldn't you just set --host=<external IP>?

**Comment by tamird** [comment]
You would, but that would stop your instance from listening on all interfaces, which you may still want.

**Comment by tamird** [comment]
Come to think of it, specifying the host alone may not be enough in the presence of bespoke port forwarding rules. cc @mberhault

**Comment by mberhault** [comment]
we have a few issues with addresses:
* the machine itself may not know its externally-reachable address, at least not through the standard networking stack. This means that we may need to listen on all interfaces
* what address is used to contact the machine is important. usually, external addresses will be just an alias for internal ones when firewalls are open. However, gossip address caching may have stricter requirements. @spencerkimball knows best about that
* all addresses (and dns aliases used) must be in the certificate. that's not related to the `--host` flag, but it does matter. This means that all addresses listed by the node itself must be in the cert, and all addresses in the cert must reach a bound interface

As for ports, I haven't run into port forwarding that re-assigns the port, only forward connections. They usually use the internal address, and the only issue there is making sure the load balancer is in the certificate.

**Comment by tamird** [comment]
> and all addresses in the cert must reach a bound interface

I don't think that's true. The cert may include unused addresses.

**Comment by mberhault** [comment]
well, yes, but then you won't connect to anything.
I meant any address you use to connect to a node (internal, external, dns alias, etc...) must be in the cert and ultimately end up at a real address that we listen on. In the case of google's TCP-level load balancer that's really tricky since they do some weird network-stack level aliasing to make it look like the load balancer address is on the current machine, but you can't bind to it.

**Comment by tamird** [comment]
OK, here's what I'd propose for now:
- only listen on loopback in dev mode
- listen on all interfaces otherwise
- `--host` flag controls advertised address, defaulting to hostname

The port issue still bothers me, though, and makes me think we need to return to a `addr` flag for the advertised address.

**Comment by mberhault** [comment]
Are you concerned about port forwarding where the external and internal ports differ?
I think the only issue there would be the gossip cache. When you're trying to reach a node, you'll always do host:port together, so as long at the network permits it, you're fine.

**Comment by tamird** [comment]
> Are you concerned about port forwarding where the external and internal ports differ?

Yes.

> I think the only issue there would be the gossip cache. When you're trying to reach a node, you'll always do host:port together, so as long at the network permits it, you're fine.

Right, but you'll be using the port advertised by the node. If the node doesn't know its external port, you won't reach anything.

**Comment by spencerkimball** [comment]
@tamird is this still an open issue?

**Comment by tamird** [comment]
Yep

**Comment by tamird** [comment]
Waiting on #4269 before addressing this.

**Comment by mberhault** [comment]
CC @sploiselle 

Sean and I were going over the certs docs and ran into this problem: to be able to listen on all interfaces, you need to make sure the certificate is valid for whatever the local hostname is.

**Comment by sploiselle** [comment]
CC @jseldess
