### ISSUE TITLE
storage: TestCreateCheckpoint_SpanConstrained skipped

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/cockroach#100935]
There appears to be some kind of race in the span-restrained checkpoint code. The checkpoints produced are sometimes unable to be opened.

https://github.com/cockroachdb/cockroach/issues/100919#issuecomment-1500520547

Jira issue: CRDB-26706

**Comment by jbowens** [comment]
hey @RaduBerinde do you mind taking a look at this unit test?

**Comment by RaduBerinde** [comment]
Looking into the checkpoint from a reproduction, I see this:
```
$ cockroach debug pebble manifest check MANIFEST-000001 
MANIFEST-000001: offset: 32543 err: pebble/record: invalid chunk
```

I think the record writer is more complicated internally than I thought. It might not be ok to create a new writer to append a record to an existing file.

**Comment by RaduBerinde** [comment]
Indeed, the record format excepts full blocks except the last one. I think the fix here is to use the log reader and a log writer instead of copying the file, after which it's ok to continue using that writer to add one more record.

**Comment by RaduBerinde** [comment]
Looking at the record code some more, I believe the record reader is only bothered when the appended record data crosses a 32KB block boundary. This explains why this wasn't caught by any of the checkpoint tests in Pebble.
