### ISSUE TITLE
sql: either unexport Executor or remove the Executor reference from Session.

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#10096]
Currently there is both an Executor pointer in `sql.Session` and the API to use the executor is `executor.DoStuff(session, ...)`. The redundancy of information is confusing.

It also seems that this executor reference in `Session` is not used for much; we can find it used only for:
- `e.TxnAbortCount.Inc(1)` in `session.txnState.updateStateAndCleanupOnErr()`  (this could be passed explicitly in arguments, since this method is always only called from other executor method)
- `p.session.executor.virtualSchemas` in `planner.virtualSchemas()` (this dependency could be dropped by hosting the virtualSchemas reference directly in the session objects, which may make sense in the future if we support per-session virtual tables.)

This suggests the executor pointer in Session could be removed, which would incidentally remove an argument from a few function in `pgwire`.

Alternatively, if we find it interesting to link the session to a particular executor (which makes some sense, if we squint enough) then we could unexport the methods of Executor and have Session be the only interface exported by `sql`, with appropriate prepare/execute entry points.

**Comment by a6802739** [comment]
@knz , maybe I could  try it.

**Comment by a6802739** [comment]
@knz, we should close this issue now.

**Comment by knz** [comment]
Yes, thanks for the heads up.
