### ISSUE TITLE
sql: add support for default udf params

### ISSUE THREAD

**Issue by rharding6373** [cockroachdb/cockroach#100962]
CRDB should support DEFAULT parameters in user-defined functions, as defined in the [postgres specs](https://www.postgresql.org/docs/15/sql-createfunction.html).

An example use case:
```
CREATE FUNCTION foo(a int, b int DEFAULT 2, c int DEFAULT 3)
RETURNS int
LANGUAGE SQL
AS $$
    SELECT $1 + $2 + $3;
$$;
```

Jira issue: CRDB-26711

**Comment by PhysicsACE** [comment]
Hey, I was interested in this issue and have a working protype. Could I make a PR?

**Comment by rharding6373** [comment]
Hi @PhysicsACE, yes, we'd welcome a PR to add support for default params! If this is your first time contributing to CRDB, you may find our wiki helpful: https://wiki.crdb.io/wiki/spaces/CRDB/pages/181633464/Your+first+CockroachDB+PR

Please add me as a reviewer when you're ready. Thank you!
