### ISSUE TITLE
sql: don't log failed parse attempts as error-level

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#101005]
Currently, we log all parse failures at error severity to the SQL_EXEC channel. This is undesirable - error severity should indicate errors from the perspective of CockroachDB, not from the perspective of a user. As an operator, it's confusing to have non exceptional conditions at error level in the logs.

We should instead log these at info level at most.

Jira issue: CRDB-26743

**Comment by rafiss** [comment]
Could you share an example or a link to a splunk search? I tried [this](https://cockroachlabsgcp.splunkcloud.com/en-US/app/search/search?q=search%20index%3D%22cc-app-crdb*%22%20%20severity%3D%22ERROR%22%20%7C%20stats%20count%20by%20file&display.page.search.mode=smart&dispatch.sample_ratio=1&workload_pool=standard_perf&earliest=1680825600&latest=1680989140&display.general.type=statistics&display.page.search.tab=statistics&display.statistics.sortColumn=count&display.statistics.sortDirection=desc&sid=1680989189.214354) and didn't see it.

**Comment by rafiss** [comment]
Oh, is it [these](https://cockroachlabsgcp.splunkcloud.com/en-US/app/search/search?q=search%20index%3D%22cc-app-crdb*%22%20%20severity%3D%22ERROR%22%20%20file%3D%22sql%2Fpgwire%2Fconn.go%22&earliest=1680825600&latest=1680989140&sid=1680989263.214377&display.page.search.mode=verbose&dispatch.sample_ratio=1&workload_pool=standard_perf)?

**Comment by jordanlewis** [comment]
Yes, the second link is what I'm referring to.
