### ISSUE TITLE
sql: Pass around a plan construction context rather than sticking options into the planner

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#10107]
#10097 adds a new parameter to the planner (`skipSelectPrivilegeChecks`) for the sole purpose of affecting the construction of a query plan. There's also the `avoidCachedDescriptors`, which similarly affects how plans are constructed.

Rather than putting these things into the planner struct itself, it would be cleaner to pass down a construction context object containing any parameters used during plan construction.

**Comment by jordanlewis** [comment]
@RaduBerinde please close if appropriate, thanks!

**Comment by RaduBerinde** [comment]
Yeah I will close this because there's a bunch of messy stuff like that in the planner, and hopefully we'll be able to clean some of it up once we remove the heuristic planning code.
