### ISSUE TITLE
sql: Role memberships are not being granted to users

### ISSUE THREAD

**Issue by plusiv** [cockroachdb/cockroach#101022]
**Describe the problem**

I've created a role called `ci_cd` to create databases and users. The role was created with the `CREATEDB`, `CREATELOGIN` and `CREATEROLE` options but seems like those roles options are not applied when creating a user and granting membership to the role for creating more users and databases.

**To Reproduce**
```sql
CREATE ROLE ci_cd WITH CREATEROLE CREATELOGIN CREATEDB;
CREATE USER IF NOT EXISTS scriptor;
GRANT ci_cd TO scriptor;
```

When login with the user `scriptor`:
```sql
CREATE DATABASE IF NOT EXISTS bank;
ERROR: permission denied to create database
SQLSTATE: 42501
```
```sql
CREATE USER IF NOT EXISTS bank_dev;
ERROR: user scriptor does not have CREATEROLE privilege
SQLSTATE: 42501
```

**Expected behavior**
The user `scriptor` is able to create users and databases.

**Environment:**
 - CockroachDB version: v22.2.2
 - Server OS: Ubuntu 22.04, Kubernetes Cluster
 - Client app: cockroach sql

**Additional context**
I want an user for ci/cd purposes to be able to create and grant users, databases, etc...

Jira issue: CRDB-26757

**Comment by rafiss** [comment]
Thanks for filing this issue!

The behavior you describe is expected. See these docs: https://www.cockroachlabs.com/docs/stable/create-role.html#considerations

> Role options of a role are not inherited by any of its members.

Role options behave this way in PostgreSQL too.
