### ISSUE TITLE
sql: inconsistent comparisons of NaN

### ISSUE THREAD

**Issue by eisenstatdavid** [cockroachdb/cockroach#10109]
The issue on my mind at present is the following inconsistency between sorting and scanning an index, but in general, we're not handling NaN comparisons very well.

```
root@:26257> CREATE DATABASE foo;
CREATE DATABASE
root@:26257> CREATE TABLE foo.bar (baz INT PRIMARY KEY, quux FLOAT);
CREATE TABLE
root@:26257> INSERT INTO foo.bar VALUES (1, 0/0), (2, -1), (3, 1), (4, 0/0);
INSERT 4
root@:26257> SELECT quux FROM foo.bar ORDER BY quux;
+------+
| quux |
+------+
| NaN  |
|   -1 |
|    1 |
| NaN  |
+------+
(4 rows)
root@:26257> CREATE INDEX splat ON foo.bar (quux);
CREATE INDEX
root@:26257> SELECT quux FROM foo.bar ORDER BY quux;
+------+
| quux |
+------+
| NaN  |
| NaN  |
|   -1 |
|    1 |
+------+
(4 rows)
```

**Comment by petermattis** [comment]
`NaN` has a deterministic encoding (and thus sorting) in indexes. That's unfortunately different from normal `NaN` comparisons. I suppose we could fix non-index `NaN` comparison to be deterministic for sorting purposes. Though I could also see an argument for not doing anything.

**Comment by eisenstatdavid** [comment]
I don't think making these queries consistent is a high priority, but I am concerned that `.Compare` doesn't fulfill its contract when there are NaNs.

**Comment by petermattis** [comment]
Yeah, `DFloat.Compare` is almost certainly doing the wrong thing:

```
func TestDFloatCompare(t *testing.T) {
	nan := DFloat(math.NaN())
	testdata := []struct {
		a DFloat
		b DFloat
	}{
		{nan, 1},
		{nan, nan},
		{1, nan},
	}
	for _, d := range testdata {
		fmt.Printf("(%v).Compare(%v) == %d\n",
			d.a, d.b, d.a.Compare(&d.b))
	}
}
```

```
=== RUN   TestDFloatCompare
(NaN).Compare(1) == 0
(NaN).Compare(NaN) == 0
(1).Compare(NaN) == 0
```

This argues for making the ordering of NaNs deterministic in `DFloat.Compare`.

**Comment by eisenstatdavid** [comment]
This was fixed by the commit above.
