### ISSUE TITLE
cli: localhost not set to default in commands

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/cockroach#10119]
When trying to run commands on a secure cluster, you must add the `--host=localhost` flag, otherwise you receive `Error: rpc error: code = 13 desc = connection error: desc = "transport: tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config"`

### Steps to repro

1. On GCE: `cockroach start --background --ca-cert=certs/ca.cert --cert=certs/node1.cert --key=certs/node1.key --advertise-host=10.138.0.2`
2. `cockroach node status --ca-cert=certs/ca.cert --cert=certs/root.cert --key=certs/root.key`

### Expected behavior

The `cockroach node status` command runs

### Actual beavior

You receive `Error: rpc error: code = 13 desc = connection error: desc = "transport: tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config"`

However, you can resolve this issue by running the command as:
`cockroach node status --ca-cert=certs/ca.cert --cert=certs/root.cert --key=certs/root.key --host=localhost`

**Comment by tamird** [comment]
Should be an easy one. @asubiotto care to take it?
