### ISSUE TITLE
storage: background corruption should fatal the node

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/cockroach#101101]
Currently, when an iterator encounters a corruption error (eg, an sstable block checksum failure), the node is fataled with a descriptive error message. However if a background process like a compaction encounters a compaction error, the error is logged and the node continues. If the background process was a compaction, the same compaction is likely to be retried over and over unproductively. See cockroachdb/pebble#270. See #67568 for automatic recovery from corruption.

We should fatal the process in these background corruption cases.

Jira issue: CRDB-26803

**Comment by a-robinson** [comment]
+1 for this, it'd be a big improvement. I saw a situation recently where a node hit a checksum failure during compaction and just kept retrying the same compaction over and over. The whole time there were a bunch of new files accumulating in L0 and operations on the node just kept getting slower and slower as a result. Crashing would have been far preferable.
