### ISSUE TITLE
stress: stress tests use up all inodes and do not complete

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#10113]
The stress test machines are consistently running out of inodes and failing to complete. I believe the culprit is #9940, which caused logs to be written to a fresh directory in `/tmp` on each test invocation.

The log directories in `/tmp` need to be cleaned up somehow to avoid this problem.

**Comment by knz** [comment]
I think this issue was solved via #10675, which now automatically removes the temp dir at the end of a successful test. How can I check?

**Comment by jordanlewis** [comment]
I think so too. It's hard to reproduce this because the test infrastructure changed so I'm just going to close.
