### ISSUE TITLE
ttl: remove deprecated TTLSpec.AOST field

### ISSUE THREAD

**Issue by ecwall** [cockroachdb/cockroach#101104]
This change removes `TTLSpec.AOST` in 24.1 which was needed for 22.2/23.1, 22.2/23.2 compatibility.

Jira issue: CRDB-26804

Epic CRDB-18322

**Comment by rafiss** [comment]
As per the new support for version skipping (see https://groups.google.com/a/cockroachlabs.com/g/eng/c/Y-YahlK5jsE/m/X2u6KOdwAQAJ), I think we need to wait until the 23.2 release is out to do this.

**Comment by ecwall** [comment]
Putting on hold until 24.1 then.
