### ISSUE TITLE
backupccl: long filenames in testdata prevent cloning repo on Windows

### ISSUE THREAD

**Issue by celiala** [cockroachdb/cockroach#101116]
For 23.1, [Windows bincheck](https://github.com/cockroachdb/cockroach/actions/runs/4472689494) is failing for 23.1 alphas:

[Windows bincheck](https://github.com/cockroachdb/cockroach/actions/runs/4472689494):
```
unable to create file pkg/ccl/backupccl/testdata/restore_mid_schema_change/exports/after/22.2/midaddcol/2023/03/10-143353.06/progress/BACKUP-CHECKPOINT-13cdcfcdccd2cfccd2cecfdfcecbc5ccccc5caccd1cdc9cbc8cbccdfd4cfcfcfcfdfaaabbcdf92c2d4c9ced1cac7cdcfc6cacccccbfffe: Filename too long
```

The issue here is that you cannot clone the repo on a windows machine, because the filenames in some of our tests are very long.

* Note that this has no effect on a released windows binary -- produced from a clone of the repo on a linux-machine release CI. The binary doesn't care about our testdata files, but it does mean you can't check out the code and build your own on windows dev machine

From Slack thread https://cockroachlabs.slack.com/archives/C2C5FKPPB/p1681145421364329?thread_ts=1681143838.819519&cid=C2C5FKPPB

Jira issue: CRDB-26811

**Comment by celiala** [comment]
long filename was introduced in https://github.com/cockroachdb/cockroach/pull/95023#issuecomment-1476948156

**Comment by celiala** [comment]
resolved via https://github.com/cockroachdb/cockroach/issues/101060

**Comment by celiala** [comment]
this is a separate issue from https://github.com/cockroachdb/cockroach/issues/101060. updated issue description and removed DR labels as discussed in Slack thread https://cockroachlabs.slack.com/archives/C2C5FKPPB/p1681145421364329?thread_ts=1681143838.819519&cid=C2C5FKPPB

**Comment by celiala** [comment]
adding potential idea for fixing

> we could zip up our test fixtures and have the test unzip them

**Comment by matthewtodd** [comment]
Per the [release runbook](https://cockroachlabs.atlassian.net/wiki/spaces/RE/pages/2857500774/Phase+3+Publish#10.-Check-Binaries), just chiming in that the [Windows bincheck](https://github.com/cockroachdb/cockroach/actions/runs/4691805212) for v23.1.0-beta.1 (expectedly) failed because of these long filenames.

**Comment by rail** [comment]
I just verified that bincheck ran without any issues on 23.1.0-beta.3. Running `git config --system core.longpaths true` before cloning the repo helped to bypass the default limitation.
