### ISSUE TITLE
storage: remove need for RANGEDELs in snapshot ingestions

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/cockroach#101228]
**Is your feature request related to a problem? Please describe.**

Currently, when a node ingests a snapshot for a range, a range del is written first, ensuring that existing data in the LSM is dropped. The new data is written on top. This can potentially result in a buildup of range dels, which can degrade performance. Performance can be especially bad in the case where a Pebble snapshot pins range dels, as these allow for higher range del counts relative to the bytes estimates. If these range dels overlap with others, performance can degrade in an O(n^2) fashion (n == range del fragment count).

With the new VirtualSSTs and "excise" features shipping in 23.2, we can consider eliminating our reliance of RANGEDELs in snapshot ingestions. 

**Describe the solution you'd like**

Instead of writing a RANGEDEL, the ingest would assert what ranges it wants cleared, and we would do the usual seek logic to decide whether the range was already clear in all levels, or needed virtualization to excise keys.

Jira issue: CRDB-26872

**Comment by itsbilal** [comment]
This was completed at the same time as https://github.com/cockroachdb/cockroach/issues/115432 .
