### ISSUE TITLE
sql: support outbound FKs on TTL tables

### ISSUE THREAD

**Issue by ecwall** [cockroachdb/cockroach#101225]
Outbound foreign keys are unaffected by rows being deleted from the TTL table itself and should be easier to support than inbound foreign keys.

Jira issue: CRDB-26871

Epic CRDB-26101

**Comment by simplenotezy** [comment]
@ecwall In which version will thsi be supported?

I am getting error:

```
[0A000] ERROR: relation "refresh_token" (6696): unimplemented: foreign keys from table with TTL "refresh_token" are not permitted Hint: You have attempted to use a feature that is not yet implemented. See: https://go.crdb.dev/issue-v/76407/v22.2
```

With a FK on refresh_token like this:

```
FOREIGN KEY (user_region, user_id) REFERENCES "user" (region, id) ON DELETE CASCADE ON UPDATE CASCADE
```

If I understood https://github.com/cockroachdb/cockroach/issues/76407?version=v22.2#issuecomment-1098692273 correctly, would it work if we removed the ON DELETE CASCADE?

**Comment by ecwall** [comment]
> @ecwall In which version will thsi be supported?

Outbound foreign keys are supported in [v22.2.9](https://www.cockroachlabs.com/docs/releases/v22.2#v22-2-9-sql-language-changes) and [v23.1.2](https://www.cockroachlabs.com/docs/releases/v23.1#v23-1-2-sql-language-changes).

> If I understood https://github.com/cockroachdb/cockroach/issues/76407 correctly, would it work if we removed the ON DELETE CASCADE?
It isn't related to whether you use `ON DELETE CASCADE` or not with the outbound foreign key. The complexity around `ON DELETE CASCADE` only applies to inbound foreign keys, but all foreign keys were initially unsupported for simplicity.
