### ISSUE TITLE
ui: on secure cluster, UI loads but has significant errors

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/cockroach#10120]
After standing up a secure cluster (specifically on GCE), the Admin UI successfully loads but the `health` check continually 500s and there's no data present in the UI.

Glad to repro in person because there are a large number of steps required to get the secure cluster up which haven't been published yet.

**Comment by jseldess** [comment]
@maxlang, @mrtracy, any ideas about what's causing this? We don't want to release secure cloud deployment docs until this works as expected.

**Comment by tamird** [comment]
FYI this does not reproduce locally, so there's definitely some reproduction steps missing here. My first suspicion would be GCE's firewall, FWIW.

**Comment by sploiselle** [comment]
superseded by #10374
