### ISSUE TITLE
storage: investigate/tune Raft election timeout setting

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#10133]
From a comment on #9380, @bdarnell said:

> I thought I remember reading a recommendation of 150-300ms for the heartbeat interval in the raft paper, but I can't find that now and don't remember what kind of network it was assuming.
> The raft thesis recommends an election timeout of 10-20x the network RTT, which probably implies heartbeat intervals of 3-5x RTT. However, we may want to recommend larger intervals since we run many instances of raft.

Can/should we set the election timeout based on the measured RTT? We need all of the replicas for a range to agree on the heartbeat interval and election timeout.

**Comment by bdarnell** [comment]
As long as we build in some hysteresis we could set this based on gossiped RTT (replicas don't have to be perfectly in sync; we just need to ensure that the heartbeat/election timeout ratio doesn't get out of range, so we could make slow adjustments). This is probably a good idea to support high-latency networks without interfering with response time for low-latency networks (although it would be a bit surprising for CPU/network usage to increase on lower-latency networks. We'd at least need a floor on the heartbeat interval to guard against excessive heartbeating)

**Comment by petermattis** [comment]
Marking as Later, though we might need to do this sooner to support geographically distributed clusters.
