### ISSUE TITLE
cli: process doesn't handle SIGTERM while trying to join cluster on startup

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#10138]
Start a cockroach process and try to join it to a port that isn't listening:

```
./cockroach start --logtostderr --join=localhost:2628 --store=./initially-empty-dir
```

The process will get in an endless retry loop, repeatedly complaining about its inability to connect to the join target with log messages like:

```
I161021 15:00:57.121690 69 /Users/alex/go/src/google.golang.org/grpc/clientconn.go:667  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:26258: getsockopt: connection refused"; Reconnecting to {"localhost:26258" <nil>}
```

Pressing CTRL+C has no effect on the process while it's in this state, no matter how many times I press it, even though pressing it twice is typically supposed to bring the process down immediately. Similarly, running `./cockroach quit` on it just hangs and running `kill <pid>` on it also has no effect.

**Comment by a-robinson** [comment]
It looks like this came up previously (https://github.com/cockroachdb/cockroach/issues/4435) and was fixed (https://github.com/cockroachdb/cockroach/pull/4427) but is broken again.

**Comment by a6802739** [comment]
@a-robinson, I could have a see for it.

**Comment by a-robinson** [comment]
If you want to attack it, you'll want to take a look at how `signalCh` is used in `pkg/cli/start.go`. We don't pay attention to anything on that channel until after finishing initialization.

However, this change may require some care to ensure that moving the signal handling earlier is actually safe. I haven't checked into that.
