### ISSUE TITLE
ERROR: internal error: parentID 58 does not exist

### ISSUE THREAD

**Issue by lzj594969317** [cockroachdb/cockroach#101411]
SQLSTATE: XX000
DETAIL: stack trace:
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/tabledesc/structured.go:1453: validateCrossReferences()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/tabledesc/structured.go:1440: Validate()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/catalogkv/catalogkv.go:286: validateDescriptor()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/catalogkv/catalogkv.go:432: GetAllDescriptors()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:1552: GetAllDescriptors()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:1886: forEachTableDescWithTableLookupInternal()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:1827: forEachTableDescAllWithTableLookup()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:1806: forEachTableDescAll()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/crdb_internal.go:405: func52()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/virtual_schema.go:492: 1()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/virtual_table.go:122: func3()
/usr/local/go/src/runtime/asm_amd64.s:1357: goexit()

HINT: You have encountered an unexpected error.

Please check the public issue tracker to check whether this problem is
already tracked. If you cannot find it there, please report the error
with details by creating a new issue.

If you would rather not post publicly, please contact us directly
using the support form.

We appreciate your feedback.

Jira issue: CRDB-26930

**Comment by rafiss** [comment]
Thanks for the report! Can you please share the command you ran that resulted in this error?

Also, did you do anything else before? We want to be able to reproduce the error in our own environment.
