### ISSUE TITLE
Eliminate edge case in cluster joining on Kubernetes

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#10140]
We [currently have a potential edge case in our config for Kubernetes](https://github.com/cockroachdb/cockroach/blob/40ca0df38dd77aab414cf185684ac8fef5498d6c/cloud/kubernetes/cockroachdb-petset.yaml#L97) that would cause the first node to disregard all the others and form its own separate cluster.

This case could be triggered if the persistent volume for the first node gets wiped somehow, because the first node determines whether to create a new database or join an existing one by checking the data on its persistent volume.

I'm working on a [Helm chart](https://github.com/kubernetes/charts) and figure it'd be nice for us to fix this issue before spreading around a near-duplicate config to yet another place that we'd have to update later.

I've been playing around with some different possibilities this afternoon, and everything kind of feels like overkill, but we should be able to use an init container to check for peers, only initializing a new cluster if there aren't any peers. It'd be nicer if there was a way to find peers from the cockroachdb/cockroach docker image rather than having to use a different image, though.

cc @tschottdorf in case he had specific plans for this.

**Comment by tschottdorf** [comment]
No specific plan, but I don't think using another container is such a bad idea (it's often awkward to cram random functionality into the main image).

Suppose you *could* use the cockroach binary for discovery to some extent: `docker run [...] cockroachdb/cockroach node ls` gives you a good idea about whether there's a cluster. Where it fails is that in the case of that command spuriously failing, you don't want to assume there isn't one.

Checking for peers inside of kubernetes sounds more like something that could make use of a general-purpose init container (i.e. not one specific to cockroach, one that various services can use for their discovery needs). I guess you'd want to query one of their APIs, right?

**Comment by a-robinson** [comment]
Yeah, I put something together on Friday that uses the Kubernetes-owned/maintained ["peer-finder" image](https://github.com/kubernetes/contrib/tree/master/pets/peer-finder) in an init container that they use in some of their examples for that purpose. I'll polish it off and send it out when I have some spare time.

Although even with that, I suppose there's still a very remote possibility of problems if:

1. All of the pet instances are brought down (e.g. datacenter power failure)
1. The first pet's data is lost
1. The first pet is the first one brought back up, so it doesn't find any peers and thus decides to initialize a new cluster

I'm not sure how much we can do about that given the current APIs, though. Hopefully I'm misunderstanding init containers and they actually only get run the very first time the first pet comes up, but I'd naively expect that they at least get run each time one of the pets has to be rescheduled on a new node.

cc @bprashanth in case this issue of having to initialize the first node in a special way only the very first time it's run isn't unique to us.

**Comment by bprashanth** [comment]
can you designate a special role to index 0? 
init containers run once per pet, don't run when container in pod is restarted, do run when pod is rescheduled.

**Comment by a-robinson** [comment]
Can you explain what you mean by "designate a special role"?

To summarize, the main thing we'd like to do is detect whether a cluster already exists when the 0'th pet comes up. That's easy as long as its PV stays around, but if the data ever somehow gets lost then we want to make sure that we still know to rejoin the existing cluster rather than create a new one.

**Comment by tschottdorf** [comment]
Looks like what you really want is to find out if any of the pets already exist (whether they're running or not), i.e. whether there is any PV allocated to any node in the PetSet.

**Comment by tschottdorf** [comment]
If you had that, then you wouldn't need to special case node zero at all. Though in reality, I think node zero would always be the one that would get to seed a cluster, at least unless k8 changes up the order in which things happen.

**Comment by a-robinson** [comment]
Fixed by #10268
