### ISSUE TITLE
changefeedccl: Bug in logging of emitted bytes

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#101676]
See: https://cockroachlabs.atlassian.net/servicedesk/customer/portal/4/BI-1115?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJxc2giOiI0YmEyMWUxMTFlNGZhY2U0NjFlZDZmZWRhNWE1Mzk1NWE5NjQ1ODdkZThlMTZjMjY5ZTAxMGIwM2JiODlmOWY2IiwiaXNzIjoic2VydmljZWRlc2stand0LXRva2VuLWlzc3VlciIsImNvbnRleHQiOnsidXNlciI6IjEwMjk3IiwiaXNzdWUiOiJCSS0xMTE1In0sImV4cCI6MTY4NDE3ODE4NiwiaWF0IjoxNjgxNzU4OTg2fQ.GuBYz5DyP6jv7PvWf99sPPj1eU9M6xyrPlBPkReM55c

We're seeing a cluster log negative emitted bytes, which should not happen

Jira issue: CRDB-27085

**Comment by amruss** [comment]
Note from Aaron: we use -1 value for compressed bytes in a place, that could be leaking through
Could also point to something with IOPS accounting

**Comment by jayshrivastava** [comment]
https://github.com/cockroachdb/cockroach/pull/98575 did not get backported, but we definitely should have backported it. Without this change, any aggregator emitting more than 2.6GB in 24h will overflow.

**Comment by jayshrivastava** [comment]
This was fixed by the above PR.
