### ISSUE TITLE
storage: unexpected Raft re-proposals during split transaction

### ISSUE THREAD

**Issue by spencerkimball** [cockroachdb/cockroach#10160]
@bdarnell this simple test (just add it to the `pkg/sql` directory) exhibits behavior I'm not understanding. I have a triplicated cluster and create a table. I then wait for the table to be split along the expected boundary. **Most** times I run it, it takes 3-5s waiting for Raft reproposals. I've done a fair bit of digging, and it's very consistent what happens. The lost Raft batch includes just the start of the txn, which adjust the LHS `RangeDescriptor`. After a few hours tracking it this far, I felt like it'd be more reasonable to turn this over to the expert.

Sometimes it takes about 10s to run (seems to be a race related to not adding to the split queue), and other times it takes 25s to run (not sure about that case as it's rare and I lost the logs).

```
package sql_test

import (
	"context"
	"testing"

	"github.com/cockroachdb/cockroach/pkg/base"
	"github.com/cockroachdb/cockroach/pkg/keys"
	"github.com/cockroachdb/cockroach/pkg/testutils/sqlutils"
	"github.com/cockroachdb/cockroach/pkg/testutils/testcluster"
	"github.com/cockroachdb/cockroach/pkg/util"
	"github.com/cockroachdb/cockroach/pkg/util/leaktest"
	"github.com/cockroachdb/cockroach/pkg/util/log"
	"github.com/pkg/errors"
)

func TestSlowSplit(t *testing.T) {
	defer leaktest.AfterTest(t)()

	// Create a command filter which prevents EndTransaction from succeeding.
	tableStartKey := keys.MakeTablePrefix(51 /* initial table ID */)
	testClusterArgs := base.TestClusterArgs{
		ReplicationMode: base.ReplicationAuto,
	}
	tc := testcluster.StartTestCluster(t, 3, testClusterArgs)
	defer tc.Stopper().Stop()
	if err := tc.WaitForFullReplication(); err != nil {
		t.Error(err)
	}

	sqlDB := sqlutils.MakeSQLRunner(t, tc.Conns[0])

	_ = sqlDB.Exec(`CREATE DATABASE test`)
	_ = sqlDB.Exec(`CREATE TABLE test.t (k SERIAL PRIMARY KEY, v INT)`)
	log.Infof(context.TODO(), "created table")

	// Wait for new table to split.
	util.SucceedsSoon(t, func() error {
		desc, err := tc.LookupRange(keys.MakeRowSentinelKey(tableStartKey))
		if err != nil {
			t.Fatal(err)
		}
		if !desc.StartKey.Equal(tableStartKey) {
			log.Infof(context.TODO(), "waiting on split results")
			return errors.Errorf("expected range start key %s; got %s", tableStartKey, desc.StartKey)
		}
		return nil
	})
}
```

**Comment by tschottdorf** [comment]
You've ruled out `WaitForFullReplication` as the culprit, right? That thing is *slow*.

**Comment by petermattis** [comment]
The time is spent in the `util.SuceedsSoon`. I'll take a look.

**Comment by petermattis** [comment]
Looks like we're splitting `r7` off from `r6` before the Raft group for `r6` has initialized which is causing the proposal for the split to not go through initially. I would have expected eager campaigning of `r6` to take effect here. Still digging into what is going wrong.

**Comment by petermattis** [comment]
Well, one part of the problem is definitely due to not campaigning the idle `r6` replica. I can force that campaigning to happen and the test time in the good case drops to `<0.5s`

**Comment by petermattis** [comment]
Eager campaigning of idle replicas is not being performed because the initial store used for bootstrapping the cluster is only used temporarily in `node.go:bootstrapCluster` and then another store is created. Thus, the store on node 1 used by the test cluster never has `Store.Bootstrap` called and so we don't set `Store.idleReplicaElectionTime.at` to the bootstrap time.

**Comment by spencerkimball** [comment]
@petermattis I'm reopening this issue. Recall in the original description that we sometimes experience 10s delays due to split queue mishaps. This is the cause of @tamird's issue #10184.

What's happening is as follows:

- Splits for the first range `[M{in-ax}]` at keys `[/Table/11/0 /Table/12/0 /Table/13/0 /Table/14/0]` go into the split queue.
- Within the split queue:
  - Split proceeds at `/Table/11/0`
  - Split proceeds at `/Table/12/0`
  - Split proceeds at `/Table/13/0`
  - Split proceeds at `/Table/14/0`
- Splits for the range `/Table/14-Max` at keys `[/Table/50/0]` go into split queue
  - Split starts at `/Table/50/0`
- Table `51` gets created and the config is gossiped, causing it to be added to split queue, but the replica is already active, so it's ignored
- Split finishes at `/Table/50/0`, replica exits split queue

So then we need to wait for the next scan interval for the range to be reconsidered for splitting.

**Comment by petermattis** [comment]
The unexpected reproposals were fixed. Now to fix the slow splits.

**Comment by tamird** [comment]
Is this also the same as #9624, #9673, and (the current blocker in) #8057?

**Comment by petermattis** [comment]
This doesn't help #9624. That seems to be a different problem. I'll take a look.
