### ISSUE TITLE
23.1 Acceptance testing: Workload Insight Type Filter is cut off

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#101725]
Go to our 23.1 testing cluster. Go to Insights page. Go to Filters and Workload Insights Type. View the following drop-down that is cut off:

<img width="1139" alt="image" src="https://user-images.githubusercontent.com/81193618/232785188-1bb56f28-11d0-449f-b4db-8c3bbda3c330.png">

Jira issue: CRDB-27108

**Comment by florence-crl** [comment]
This looks like it may be cut off as well:
<img width="604" alt="Screenshot 2023-05-22 at 6 19 17 PM" src="https://github.com/cockroachdb/cockroach/assets/58752716/da1fee2d-7389-4c34-817a-15a7a03327cb">
