### ISSUE TITLE
23.1 Acceptance Testing: Missing other column sorts for the Search Criteria

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#101817]
Go to 23.1 test cluster. Go to SQL Activity. The Search Criteria is missing the "More" fly out. This is a slight regression from the previous UX and is necessary for cases where users would like to Sort based on another column outside the top 6 commonly sorted columns.

[Figma link
](https://www.figma.com/file/GWC9SPIpoMCgrC5cBrbUnj/23.1_SQL-Obs-Index-Details-%26-SQL-Activity?type=design&node-id=1645-130170&t=1mnA26nWXlS1FNeT-0)

<img width="460" alt="image" src="https://github.com/cockroachdb/cockroach/assets/81193618/5a1610b5-8912-47e3-bd30-339672b2d07b">

When 'None' is selected, TOP would be disabled.

FYI @dongniwang @maryliag 

Jira issue: CRDB-27136

**Comment by maryliag** [comment]
This is being tracked as part of the new design on #98891 (which is not yet completed). But since that is the only part missing from the new design, I will close that one as completed and keep this one to work on just the missing part.
