### ISSUE TITLE
log: add consistent tagging of failed assertions that are alertworthy

### ISSUE THREAD

**Issue by dhartunian** [cockroachdb/cockroach#102041]
Sometimes in production we have situations that don't rise to the level of `panic` (programmer error) or `Fatalf` (node should crash) but still want to alert the operator that something serious is going on that requires immediate attention. This cannot be simply codified into an `ERROR` severity log since not all `ERROR` level lines rise to the level of requiring operator involvement.

This ticket tracks consistent messaging for these types of errors so that they can be alerted upon easily. This can be done either through a log tag, or through some pre-set formatting structure in the error message.

Jira issue: CRDB-27233

**Comment by joshimhoff** [comment]
CC @nvanbenschoten as this relates to an idea from Nathan / KV re: building a better assertion framework for roachprod-based tests.

**Comment by nvanbenschoten** [comment]
There's a thread about better, easier runtime assertion in https://github.com/cockroachdb/cockroach/issues/94986. As that thread discusses, the three considerations are 1) ergonomics, 2) cost in production, and 3) effect in production.

I'm bullish that if we get the framework right, we'll see quick adoption of assertions throughout the codebase. This is what we saw with the adoption of the `testify/require` library. The library was easy enough to use that developers began reaching for it in place of older approaches. In fact, it was so low enough that developers began writing better tests with more assertions.

**Comment by srosenberg** [comment]
> I think the specific concept missing is "assertion has failed that indicates a code bug somewhere in CRDB period, but no need to crash the node given details of the assertion failure".

So, are we merely hinting at a new log-level? I can't say I've come across other systems that sandwich a new log-level between `WARN`, `ERROR`, and `FATAL`. If I understand the ask, we want to easily surface some assertion failures without crashing a node?
It's worth noting that non-fatal assertions can be rather counter-productive [1], which is one of the reasons you don't seem them in the wild.

[1] https://blog.mozilla.org/nnethercote/2011/06/07/what-is-the-point-of-non-fatal-assertions/

**Comment by srosenberg** [comment]
> This is what we saw with the adoption of the testify/require library. The library was easy enough to use that developers began reaching for it in place of older approaches. In fact, it was so low enough that developers began writing better tests with more assertions.

That's great to hear! However, we should also be wary of the error-prone API which comes with the testify/require library, e.g. [1], [2].

[1] https://github.com/cockroachdb/cockroach/issues/101028
[2] https://github.com/cockroachdb/cockroach/issues/100796

**Comment by dhartunian** [comment]
There is a bunch of working going on in #94986 to support better runtime assertions. Closing this as duplicate.
