### ISSUE TITLE
sql: enforce_home_region seems to be partially ignored for mutations

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#102048]
I've found that we are inconsistent in enforcing the home region on mutation statements. For updates or deletes that need to access remote data as part of their initial scan, we return an error if the data is not found in the local region. However, directly inserting or updating data in remote regions does not cause an error (e.g., `UPDATE t SET crdb_region = 'us-east1' WHERE crdb_region = 'us-west1';` causes no error as long as I run it from 'us-west1'). Constraint checks (uniqueness checks and FK checks) that must access a remote region also do not cause a "no home region" error.

What is the desired behavior here? cc @msirek 

Adding the docs-known-limitation label in the meantime.

Jira issue: CRDB-27239

**Comment by msirek** [comment]
> What is the desired behavior here? cc @msirek

@rytaft
The desired behavior is to error out with a `Query has no home region` error.

The fix for this is not in the v23.1.0-beta.2 build.
Here are the relevant backports:
https://github.com/cockroachdb/cockroach/pull/101708
https://github.com/cockroachdb/cockroach/pull/101697
