### ISSUE TITLE
stats: exclude `system.job_info` from auto stats collection

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#102036]
For the same reasons explained in https://github.com/cockroachdb/cockroach/pull/80887#pullrequestreview-961170782 we should consider excluding the `system.job_info` from automatic statistics collection. This table will be written frequently by jobs running in the cluster since it is where the payload and progress of jobs is stored.

Jira issue: CRDB-27240

**Comment by dt** [comment]
I'm not convinced we should do this (or should have excluded jobs in #80887 for that matter, at least without checking with jobs people). We have pretty complicated queries on the jobs tables at this point which I don't really expect humans to accurately optimize for all data distributions, i.e. exactly the kind of thing an optimizer armed with stats will do for us.

**Comment by dt** [comment]
I don't have strong opinions about disabling stats or not on this table -- it has effectively just two columns -- a (compound) key and a value and the access is very intentionally KV-ish with the PK being the only index, so I could take or leave stats here. My slight preference would be to have them on just so it behaves like any other table and we don't have a weird surprise later, but they don't seem particularly important either way here. On system.jobs otoh, I'm pretty sure we want to do the opposite of this issue and _remove_ the opt-out which I've filed as https://github.com/cockroachdb/cockroach/issues/102213

**Comment by adityamaru** [comment]
I'm going to drop the GA-blocker label on this issue based on our conversation in the jobs meeting. The reason this issue was opened was because the internal test cluster had a few failing auto stats job on the `job_info` table that failed because of an out-of-memory error. I agree with @dt that we should investigate enabling stats on these tables as we have more and more complex queries run against them.

**Comment by DrewKimball** [comment]
Closing after discussion in the queries meeting - it seems like this won't be necessary.
