### ISSUE TITLE
roach{prod,test}: reduce noise in SSH log artifacts

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/cockroach#102184]
**Is your feature request related to a problem? Please describe.**

Currently, when roachtest issues a command against a cluster, the SSH logs are retained. These logs are _very_ verbose, and hamper investigations when the user has to pick through these logs to find output pertinent to an investigation.

Some product feedback from an internal user:

> i don't need tcp logs or cipher negotiation -- we're not testing SSH itself here. i just need the outcome. and the fact it echo's the script back makes it really, really easy to mis-read

**Describe the solution you'd like**

Consider making the SSH logs less verbose. This improves the signal to noise ratio.

Jira issue: CRDB-27330

**Comment by smg260** [comment]
The existing logs are already sequestered into a separate ssh subdirectory so as not to pollute the main logs and are preserved in the spirit of collecting as much information as possible about a failure.

They are, however, verbose and rarely contain useful information for the majority of errors. Some simple usability improvements should help:

1 - Only preserving the logs for potential ssh flakes, which will get directed to the test-eng team
2 - Generify the message to state that "verbose logs preserved" (or something to that effect), so it doesn't seem like we are directing the user to look there.
