### ISSUE TITLE
changefeedccl: add healthy_ranges metric 

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#102146]
We’re proposing adding a healthy_ranges metric that tracks the % of ranges that are “up to date” with their checkpoints (maybe if they’re less than a minute behind, they’re considered up to date). Using this in lieu of max_changefeed_behind would allow you to (1) have very tight SLAs - the SLA could be 99.9% healthy ranges (2) allow you still do alerting on the slowest ranges - you could say alert if less than 100% of ranges are healthy for more than 5 minutes at a time (we should probably make this configurable).

Jira issue: CRDB-27306

Epic CRDB-8669

**Comment by amruss** [comment]
@samiskin would this be backportable?

**Comment by samiskin** [comment]
Haven't looked into if there would be any weird quirks, but I think it should be fine to backport

**Comment by miretskiy** [comment]
@jayshrivastava  -- reassigning to you, and I think this can be closed.
