### ISSUE TITLE
Unexpected results of `CASE` and `BETWEEN`

### ISSUE THREAD

**Issue by DerZc** [cockroachdb/cockroach#102110]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**

Consider the following program:
```
USE test;
DROP DATABASE IF EXISTS database9 CASCADE;
CREATE DATABASE database9;
USE database9;

SET CLUSTER SETTING diagnostics.reporting.enabled    = false;
SET CLUSTER SETTING diagnostics.reporting.send_crash_reports = false;
SET CLUSTER SETTING sql.metrics.statement_details.plan_collection.enabled = 'off';
SET CLUSTER SETTING sql.stats.automatic_collection.enabled = 'off';
SET CLUSTER SETTING timeseries.storage.enabled = 'off';
set experimental_enable_hash_sharded_indexes='on';

CREATE TABLE t1 (c0 TIMESTAMPTZ, c1 VARBIT(101) DEFAULT (B'111111111'));
UPSERT INTO t1 (c0) VALUES(TIMESTAMPTZ '1969-12-10T06:25:44');
INSERT INTO t1 (c1) VALUES(NULL);

SELECT t1.c0 AS c1, t1.c1 AS c2 FROM t1 WHERE ((((t1.c0) IS NULL)) :::BOOL);

CREATE TABLE temp_table1 (c1 TIMESTAMPTZ, c2 BIT);
INSERT INTO temp_table1 SELECT t1.c0 AS c1, t1.c1 AS c2 FROM t1 WHERE ((((t1.c0) IS NULL)) :::BOOL);
SELECT t1.c0 FROM t1, temp_table1 WHERE (t1.c1) NOT BETWEEN (t1.c1) AND (CASE  WHEN NULL THEN temp_table1.c2 ELSE t1.c1 END);
DROP TABLE temp_table1;
```

I get the following result for these two queries:
```
> SELECT t1.c0 AS c1, t1.c1 AS c2 FROM t1 WHERE ((((t1.c0) IS NULL)) :::BOOL);
   c1  |  c2
-------+-------
  NULL | NULL
(1 row)

Time: 0ms

> SELECT t1.c0 FROM t1, temp_table1 WHERE (t1.c1) NOT BETWEEN (t1.c1) AND (CASE  WHEN NULL THEN temp_table1.c2 ELSE t1.c1 END);
            c0
--------------------------
  1969-12-10 06:25:44+00
(1 row)

Time: 1ms
```

But in the second query, the `CASE` statement `(CASE  WHEN NULL THEN temp_table1.c2 ELSE t1.c1 END)` should always return `t1.c1`, so the condition `(t1.c1) NOT BETWEEN (t1.c1) AND (CASE  WHEN NULL THEN temp_table1.c2 ELSE t1.c1 END)` should always return false. This query should have empty results.

I tried this query `WITH temp_table1(c1, c2)  AS (SELECT t1.c0 AS c1, t1.c1 AS c2 FROM t1 WHERE ((((t1.c0) IS NULL)) :::BOOL)) SELECT t1.c0 FROM t1, temp_table1 WHERE (t1.c1) NOT BETWEEN (t1.c1) AND (CASE  WHEN NULL THEN temp_table1.c2 ELSE t1.c1 END);` and these two queries should be equivalent. This query has empty results.

I build CockroachDB from the last commit version https://github.com/cockroachdb/cockroach/commit/1f3419e178bdba544f74d9c9e14a4682efd18028

**Expected behavior**
The second query has empty results.

**Environment:**
 - CockroachDB version https://github.com/cockroachdb/cockroach/commit/1f3419e178bdba544f74d9c9e14a4682efd18028
 - Server OS: Ubuntu 22.04
 - Client app: CLI

Jira issue: CRDB-27285

**Comment by Xiang-Gu** [comment]
Looks like the SQL query returns an incorrect result, adding @cockroachdb/sql-queries to take a further look.

**Comment by mgartner** [comment]
Thanks for the report!

Here's a simplifed reproduction:

```sql
CREATE TABLE t1 (v VARBIT);
INSERT INTO t1 VALUES (B'11');

CREATE TABLE t2 (b BIT);
INSERT INTO t2 VALUES (NULL);

SELECT t1.v FROM t1, t2
WHERE t1.v NOT BETWEEN t1.v AND
  (CASE WHEN NULL THEN t2.b ELSE t1.v END);
```

On CRDB v22.2.6, v22.1.13, v21.2.17, and v21.1.21 the query returns a single row, while on Postgres, no rows are returned.

The query plan is: 

```
  inner-join (cross)
   ├── columns: v:1
   ├── immutable
   ├── stats: [rows=330000]
   ├── cost: 5477.37872
   ├── distribution: us-east1
   ├── scan t2
   │    ├── stats: [rows=1000]
   │    ├── cost: 1064.42
   │    ├── distribution: us-east1
   │    └── unfiltered-cols: (5-8)
   ├── select
   │    ├── columns: v:1
   │    ├── immutable
   │    ├── stats: [rows=330, distinct(1)=100, null(1)=0]
   │    ├── cost: 1094.65
   │    ├── distribution: us-east1
   │    ├── scan t1
   │    │    ├── columns: v:1
   │    │    ├── stats: [rows=1000, distinct(1)=100, null(1)=10]
   │    │    ├── cost: 1084.62
   │    │    ├── distribution: us-east1
   │    │    └── prune: (1)
   │    └── filters
   │         └── ((v:1 IS NOT DISTINCT FROM CAST(NULL AS VARBIT)) AND CAST(NULL AS BOOL)) OR (v:1 > v:1::BIT) [outer=(1), immut
able, constraints=(/1: (/NULL - ])]
   └── filters (true)
```

The filters look incorrect:

```sql
((v:1 IS NOT DISTINCT FROM CAST(NULL AS VARBIT)) AND CAST(NULL AS BOOL)) OR (v:1 > v:1::BIT)
```

Specifically, `v > v::BIT` will return true because the case to `BIT` strips away all but one bit from a `VARBIT`. It seems like some normalization rules are applying that shouldn't be applied.

I'll dig in some more and try to figure out if expressionsn with other column types are affected.

**Comment by mgartner** [comment]
Here's another reproduction with different column types:

```sql
CREATE TABLE t1 (t TEXT);
INSERT INTO t1 VALUES ('aa');

CREATE TABLE t2 (c CHAR);
INSERT INTO t2 VALUES (NULL);
```
