### ISSUE TITLE
sql: fix flaky COPY tests

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#10219]
See: https://reviewable.io/reviews/cockroachdb/cockroach/10197#-KUvX92nEkgRRdB5VliK:-KUvX92nEkgRRdB5VliL:bttvbyh

**Comment by spencerkimball** [comment]
@mjibson I'm closing this as the line referenced in the linked code review is no longer current in the code. Please reopen and update as necessary.
