### ISSUE TITLE
gossip: consider enforcing that no more than two CockroachDB binary versions are active in a cluster at once

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#10212]
In planning cluster upgrade hooks (#9404), we take it as an assumption that clusters shouldn't be running more than two different binary versions at once, since that would imply that two different upgrades were happening at once. This isn't strictly required for anything at the moment, but is a good practice to follow and is something that we could perhaps automatically enforce for users' safety.

@tamird suggested using a mechanism along the lines of our approach to managing SQL schema leases to prevent letting nodes start join a cluster with a third version.

**Comment by bdarnell** [comment]
We now validate cluster versions when nodes connect to each other.
