### ISSUE TITLE
bazel: linter rules are not applied to files generated from non-.go templates

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#102191]
**Describe the problem**

Found [here](https://github.com/cockroachdb/cockroach/pull/101930#issuecomment-1520816909): At least the go code derived from `.y` files doesn't get subject to our linter rules with bazel CI.

(It does with github CI).

This is a problem because if this code contains code that violates our lint rules, the lack of linter when we remove github CI will mean we get invalid code in production.

**To Reproduce**

Introduce an invalid call to `errors.New` in `sql.y` and observe that no lint error is reported.

**Expected behavior**

All go code generated from templates that have not yet been linted already, must be linted as well.

cc @rickystewart 

Jira issue: CRDB-27332

**Comment by knz** [comment]
@rickystewart asks:

> If we can find a list of which "generated code" files should and should not be linted, then it'll be easy to apply it. I suspect that we have not fully thought through which "generated code" files are and are not lint-worthy.

I'd take it from the other hand. The baseline is what we had originally: TestRoachVet was applying the linter to _all files_ whether they were auto-generated or not.

Avoiding the linter for _some_ files is an **optimization**. As in all engineerings we must be careful to limit the scope of the optimization to only the cases where it's known to be safe.

So my proposed course of action is this:
1. apply the linter to all generated files by default.
2. on an ad-hoc basis, select generated files that we can avoid linting **after we have a guarantee that their source template is being linted already** (e.g. many files in sql/opt are generated from a template with file name `_tmpl.go` and I am assuming these get linted already. But generally, we shoulnd't assume.)

**Comment by rickystewart** [comment]
> The baseline is what we had originally: TestRoachVet was applying the linter to all files whether they were auto-generated or not.

This is not ever how TestRoachVet worked. TestRoachVet [blindly ignores](https://github.com/cockroachdb/cockroach/blob/4751d63a2f18a4c6581435fe2bc3e40ccf7b18fe/pkg/testutils/lint/lint_test.go#L2252) lint failures in generated files.

**Comment by knz** [comment]
It ignores them in files called `*_generated.go`.  Not all generated files follow this pattern.

One additional consideration is that if we approach this via a "extra lint list", we run into the following problem: if someone in the future adds a _new_ generation rule, and they forget to add their new generated files to the "extra lint list", we're going to get bad code in prod too. 

The suggestion to use an explicit "do-not-lint list" would avoid that problem.

**Comment by knz** [comment]
Here's the rationale for the TestRoachVet rules:

- `.[eo]g.go`: this is because they are generated from `_tmpl.go` files which are linted already.
- `.pb.*.go`: this is because `.proto` files do not contain human-written Go code to start with. 
- `_generated.go`: this is because _originally_ all the `_generated.go` are generated indirectly from .proto files so the reasoning above applies.
  - However sadly I am noticing some of the `_generated.go` files now include human-written code that was not linted already. So the problem we're discussing here applies to those too.

**Comment by rickystewart** [comment]
> It ignores them in files called *_generated.go. Not all generated files follow this pattern.

We ignore `*_generated.go` files, `.eg.go`, `.og.go`, and all protobuf generated files. True that not all generated files fit into one of these categories, but the overwhelming majority of them do.

Note that the `nogo_config.json` file [applies these same exclusions](https://github.com/cockroachdb/cockroach/blob/4751d63a2f18a4c6581435fe2bc3e40ccf7b18fe/build/bazelutil/nogo_config.json#L4).

I would prefer we keep the discussion factual rather than basing this on what we think TestRoachVet "should have" been doing all along.

**Comment by knz** [comment]
>  we keep the discussion factual 

The fact is that if generated code contains invalid uses of `errors.New` or `log.Info` etc functions, with correctness as determined by the linter, and we embark this generated code in production, this can incur PII leakage from customers and cost us big $$ fines.

If the discussion we are having now brings us to the realization that we **incorrectly** excluded certain files from the previous linter, and therefore _also_ incorrectly excluded them from the new linter, that's a good thing (more knowledge = good) and that does not invalidate the point made in the title of this issue:

"linter rules are not applied to files generated from non-.go templates"

This is the issue that remains to be fixed.

**Comment by rickystewart** [comment]
I sent out #102714, which increases the coverage of the linter to some generated code that was not being caught before.

Clarifying a point about "templates". As far as `nogo` is concerned, we lint files only when they are actually compiled into a `go_library`. This means we are not linting "templates", we only ever lint code that we are compiling (i.e., code after generation).

I have not updated the `nogo_config.json` to remove "legacy" exclusions of `.eg.go` files, protobuf files, `_generated.go` files, etc. These can be addressed in follow-ups, especially if we can identify specific files that are not linted which should be going forward.
