### ISSUE TITLE
cluster-ui: `read-members` error fetching table grants from sql-over-http API

### ISSUE THREAD

**Issue by THardy98** [cockroachdb/cockroach#102204]
**Describe the problem**

Version: 23.1

Encountering an error when loading the table details page on our 23.1 test cluster:

![image (5)](https://user-images.githubusercontent.com/15315413/234137842-1013dc5e-8000-4c92-925d-b02d0ec1961a.png)

Response payload:
```
{"error":{"code":"XXUUU","message":"executing stmt 2: run-query-via-api: read-members: batch timestamp 1681781325.979933937,0 must be after replica GC threshold 1681921008.470061491,0","severity":"ERROR","source":{"file":"internal.go","line":863,"function":"1"}},"num_statements":10,"execution":{"txn_results":[{"statement":1,"tag":"SELECT","start":"2023-04-24T23:29:07.626700443Z","end":"2023-04-24T23:29:07.627448108Z","rows_affected":0,"columns":[{"name":"table_id","type":"OID","oid":26}],"rows":[{"table_id":"24"}]},{"statement":2,"tag":"SELECT","start":"2023-04-24T23:29:07.627449304Z","end":"2023-04-24T23:29:07.665350338Z","rows_affected":0,"error":{"code":"XXUUU","message":"executing stmt 2: run-query-via-api: read-members: batch timestamp 1681781325.979933937,0 must be after replica GC threshold 1681921008.470061491,0","severity":"ERROR","source":{"file":"internal.go","line":863,"function":"1"}}}]}}
```

The issue is caused when querying for the table's grants using the sql-over-http API from cluster-ui:
```
SELECT grantee as user, array_agg(privilege_type) as privileges 
         FROM [SHOW GRANTS ON TABLE %1] group by grantee
```

where we error reading role memberships:
https://github.com/cockroachdb/cockroach/blob/767567947661267dbcd3f666d45d2a72210b9b44/pkg/sql/information_schema.go#L2764

Jira issue: CRDB-27337

**Comment by rafiss** [comment]
Have we only reproduced in the long running test cluster? Or does this happen on any 23.1 cluster?

**Comment by maryliag** [comment]
I believe we saw it happening a couple of times, but just on the long running cluster

**Comment by rafiss** [comment]
Are there other issues in the cluster that are affecting GC? Perhaps the KV team would know.

**Comment by THardy98** [comment]
Does the query in question look suspicious to you? It seems innocuous to me

**Comment by THardy98** [comment]
This isn't an issue with the sql-over-http API or the console specifically.

From my testing, you can't `SHOW GRANTS ON <table name>` for *any* table on the 23.1 test cluster. To reproduce, run the aforementioned query for any table in the CLI.

Will file follow-up issue(s) for this.

**Comment by THardy98** [comment]
Closing this due to the follow-up issues mentioned above.
