### ISSUE TITLE
Composite Type and UDF bug following UPDATE

### ISSUE THREAD

**Issue by codingconcepts** [cockroachdb/cockroach#102227]
**Describe the problem**

When using a combination of composite types and UDFs, a bug occurs whereby CockroachDB can no longer find the UDF.

**To Reproduce**

Setup cluster (v23.1.0-alpha.8):
```
cockroach demo --no-example-database --insecure
```

Create table and insert data:
``` sql
CREATE TYPE amount AS ("value" INT, "currency" STRING, "minor_units" INT);

CREATE TABLE "purchase" (
    "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "amount" amount NOT NULL,
    "timestamp" TIMESTAMP NOT NULL DEFAULT now()
);

INSERT INTO "purchase" (amount) VALUES
    ((1000,  'GBP', 100)),  -- Pound Sterling
    ((10,    'YEN', 1)),    -- Japanese Yen
    ((10000, 'BHD', 1000)); -- Bahraini Dinar
```

Create UDF:
``` sql
CREATE FUNCTION decimal_amount(a amount) RETURNS DECIMAL(10, 2) IMMUTABLE LANGUAGE SQL AS $$                                                    
    SELECT (a)."value" / (a)."minor_units";
$$;
```

Test the UDF:
``` sql
SELECT
    id,
    decimal_amount(amount) AS amount,
    (amount).currency
FROM purchase;

                   id                  | amount | currency
---------------------------------------+--------+-----------
  844a20b3-3ea5-4307-b6b9-52d9d97d4479 |  10.00 | YEN
  d7d872bb-a1f2-4cbb-aac1-ed8d501f0c26 |  10.00 | GBP
  e62dfbf3-b0b9-4905-b73e-10caac2acf77 |  10.00 | BHD
```

Update one of the composite type values (e.g. increase BHD minor units):
``` sql
UPDATE purchase
SET amount = ((amount).value, (amount).currency, 10000)
WHERE (amount).currency = 'BHD';
```

Try to call the UDF again:
``` sql
SELECT
    id,
    decimal_amount(amount) AS amount,
    (amount).currency
FROM purchase;

ERROR: function decimal_amount(amount) does not exist: function undefined
SQLSTATE: 42883
```

**Expected behavior**
Updating the value a composite type does not affect my ability to call a UDF that makes use of it.

**Environment:**
Build Tag:        v23.1.0-alpha.8
Build Time:       2023/03/27 15:55:37
Distribution:     CCL
Platform:         darwin arm64 (aarch64-apple-darwin21.2)
Go Version:       go1.19.4
C Compiler:       Clang 10.0.0 
Build Commit ID:  85b01cee0722c81b538e4155267979faae225c9b
Build Type:       release

Jira issue: CRDB-27354

**Comment by msirek** [comment]
I was able to reproduce this on the latest master, ced134707ca0b934da4a4997fc1357cfe7c42d07
