### ISSUE TITLE
Getting "Can't load plugin: sqlalchemy.dialects:cockroachdb.psycopg2" error while trying to use cockroachDB in a lambda

### ISSUE THREAD

**Issue by minjie0501** [cockroachdb/cockroach#102247]
**Describe the problem**

Getting "Can't load plugin: sqlalchemy.dialects:cockroachdb.psycopg2" error while trying to connect to a cockroachDB in an AWS lambda function using SQL Alchemy. I use the sqlalchemy-cockroachdb dialect and my connection string looks like this: "cockroachdb://username:password@host:port/defaultdb". Locally everything works fine. I have psycopg2 installed using https://github.com/jkehler/awslambda-psycopg2.

**Environment:**
AWS Lambda
Runtime: Python 3.9
Architecture: arm64

Jira issue: CRDB-27364

**Comment by rafiss** [comment]
dupe of https://github.com/cockroachdb/sqlalchemy-cockroachdb/discussions/210
