### ISSUE TITLE
2x performance regression when querying table metadata in v23.1b2

### ISSUE THREAD

**Issue by bobvawter** [cockroachdb/cockroach#102259]
I’m seeing a 2x performance regression in retrieving table metadata in 23.1, compared to 22.2.

The test creates an increasing number of simple tables like so:
```
create = fmt.Sprintf("CREATE TABLE %%s (val %s primary key, k int)", tc.columnType)
```

And then calling:

```
SELECT schema_name, table_name FROM [SHOW TABLES FROM %s] WHERE type = 'table'
```

which then describes each table by

```
WITH
pk_name AS (
	SELECT constraint_name FROM [SHOW CONSTRAINTS FROM %[1]s]
	WHERE constraint_type = 'PRIMARY KEY'),
pks AS (
	SELECT column_name, seq_in_index FROM [SHOW INDEX FROM %[1]s]
	JOIN pk_name ON (index_name = constraint_name)
	WHERE NOT storing),
cols AS (
	SELECT column_name, data_type, generation_expression != '' AS ignored
	FROM [SHOW COLUMNS FROM %[1]s]),
ordered AS (
	SELECT column_name, min(ifnull(pks.seq_in_index, 2048)) AS seq_in_index FROM
	cols LEFT JOIN pks USING (column_name)
    GROUP BY column_name)
SELECT cols.column_name, pks.seq_in_index IS NOT NULL, cols.data_type, cols.ignored
FROM cols
JOIN ordered USING (column_name)
LEFT JOIN pks USING (column_name)
ORDER BY ordered.seq_in_index, cols.column_name
```

which is where the increasing slowness is coming from.  So, I can fix the test by dropping the tables between iterations, but the above query is slower in 23.1 than it is in 22.2.

Full test here:
https://github.com/cockroachdb/cdc-sink/blob/aef6305feadc2bd46788c0e6230b2b4f82742c46/internal/target/apply/apply_test.go#L198

This difference in behavior occurs on my laptop, as well as the GitHub test runners.  The single-node cockroach processes are started as: `cockroach start-single-node --store type=mem,size=2G --insecure --advertise-addr 127.0.0.1 `.

V23.1b2 - store type=mem:

```
=== RUN   TestAllDataTypes/uuid_null
    apply_test.go:364: CREATE TABLE in 1.82441075s
    --- PASS: TestAllDataTypes/uuid_null (1.83s)
```

![Screenshot 2023-04-25 at 13 09 34](https://user-images.githubusercontent.com/1158548/234355556-826834df-e296-4ea1-9516-665fdd9002f9.png)

v22.2:

```
=== RUN   TestAllDataTypes/uuid_null
    apply_test.go:364: CREATE TABLE in 774.311834ms
    --- PASS: TestAllDataTypes/uuid_null (0.78s)
```

![Screenshot 2023-04-25 at 13 13 18](https://user-images.githubusercontent.com/1158548/234355839-a4f6870e-913c-45ee-89ec-6eb252234cdc.png)

Jira issue: CRDB-27370

Epic CRDB-27601

**Comment by bobvawter** [comment]
Interestingly, adding a `DROP TABLE` at the end of each test doesn't maintain the performance, there's still a decay.  If I create a new database for each loop, I get consistent performance.  v23.1 is still much slower than v22.2:

v23.1:

![Screenshot 2023-04-25 at 18 00 35](https://user-images.githubusercontent.com/1158548/234413939-10940ba6-0253-4bd5-a3a1-ede401a60fe6.png)

v22.2:

![Screenshot 2023-04-25 at 18 02 10](https://user-images.githubusercontent.com/1158548/234414204-704fae91-3079-476d-bbf8-3e9fc87c42f2.png)

**Comment by fqazi** [comment]
@Xiang-Gu Tried on the latest 23.1.0 that doesn't resolve it, let me take a stab and profiling this scenario.

**Comment by fqazi** [comment]
I'm going to remove the GA blocker tag from this issue since this seems to be visible with either a large number of tables (>10k) or ones with less linear access patterns (i.e. this test creates a new database + table each time). Some of this is the impact of reading zone configs, comments and descriptors together when we scan in this scenario. We will attempt to reduce it in a future point release.

**Comment by rafiss** [comment]
Thanks @fqazi! if we have the results from the profile, can you attach it here so it's easier to pick up the investigation?

**Comment by fqazi** [comment]
Actually, let me dig some more @rafiss. The scenario from Bob is different, and I don't think it is schema causing this problem (the descriptor stuff isn't where the slow down is coming from)

**Comment by fqazi** [comment]
Digging further, this is coming from changes to SHOW INDEX

**Comment by fqazi** [comment]
@rafiss So part of the SHOW INDEX regression stems from the changes in:
https://github.com/cockroachdb/cockroach/commit/b80c3d7c743e970d291fab700e2d6a54909cdadd

**Comment by rafiss** [comment]
@fqazi thanks, that's a good find.

can you attach the profile you captured? i'd like to see which part of that is slow.

**Comment by fqazi** [comment]
This regression no longer seems reproducible and the entire suite is taking ~23 seconds here. @bobvawter Feel free to re-open if its not sorted, but we optimized some of internal tables being used here
