### ISSUE TITLE
insights webpage crash

### ISSUE THREAD

**Issue by carr123** [cockroachdb/cockroach#102323]
crdb version:  22.2.7 and 22.2.8    linux-amd64

on the console webpage,  Insights  tab -> schema Insights.   web page crashed.

reporting js error : 

this.isOptionSelected = (ze, le) = > {
  const Ye = le.split(",")
  return Ye.length > 0 && Ye.includes(ze)
}

Cannot read properties of undefined (reading 'split') at ve.isOptionSelected 

Jira issue: CRDB-27395

**Comment by yuzefovich** [comment]
cc @maryliag

**Comment by carr123** [comment]
> Hi @carr123, thank you for reporting this! Two questions for you that will help us diagnose this:
> 
> 1. Can you confirm that you're seeing the error you reported on version 22.2.8?
> 2. Are you running CockroachDB yourself, or did you access the console webpage through CockroachCloud?
> 
> Thanks!

hi,  first time i saw this issue on version 22.2.7,  recently i upgrade the cluster to 22.2.8.  problem still there.
i'm deploying crdb myself,  using binary from  official release, running a 3-node cluster. 

BTW, it seems when there's no data in the "schema Insights" page, it crashed. i don't remember how to reproduce.
i also saw some font files can not be accessed by the chrome webbrowser.

**Comment by maryliag** [comment]
Hi @carr123 ! 
I want to let you know the fix was [merged](https://github.com/cockroachdb/cockroach/pull/102381) and it will be available on the next 22.2 release (22.2.9) schedule to be published on May 8th.
