### ISSUE TITLE
cdc: Fail job that does not make forward progress for days

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#102341]
Recent changes were added to ensure that paused changefeed
jobs will eventually expire PTS records and fail.

It appears we should extend this functionality to the running changefeed jobs.
If the PTS record is not advanced for long time and falls too far behind, 
fail changefeed.

On the one hand, stuck changefeeds should be a condition that is being monitored
for.  However, if it isn't and we allow substantial amount of GC accumulation to occur,
releasing so much data could destabilize the cluster.

It is better to set some conservative thresholds  (e.g. 2-3 days) and remove
PTS record + fail the changefeed if no progress is made.

Jira issue: CRDB-27402

**Comment by miretskiy** [comment]
https://github.com/cockroachlabs/support/issues/2263

**Comment by amruss** [comment]
Gonna put this on the jobs board to consider as a general rule for all jobs

**Comment by amruss** [comment]
Addressed: https://github.com/cockroachdb/cockroach/pull/103539
