### ISSUE TITLE
jobs: protected timestamp metrics not reporting correctly

### ISSUE THREAD

**Issue by mwang1026** [cockroachdb/cockroach#102369]
In the our 23.1 test cluster, a changefeed was paused on 4/21. We expected the PTS metric to be exploding but... it's 0, as well as paused changefeed metric is 0.

See slack thread for details in #23-1-test-cluster channel

Jira issue: CRDB-27413

**Comment by irfansharif** [comment]
It was reporting correctly. https://cockroachlabs.slack.com/archives/C04QZ9Z1QR1/p1682538439242039?thread_ts=1682537396.948229&cid=C04QZ9Z1QR1.
