### ISSUE TITLE
pebble: ingestion can break sequence number invariant

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/cockroach#102326]
This is a placeholder for cockroachdb/pebble#2196.

Jira issue: CRDB-27396

**Comment by bananabrick** [comment]
@nicktrav Does this have to be a release blocker? Bug has existed for multiple releases by this point.

**Comment by nicktrav** [comment]
Note that this is not a _release_ blocker. It was marked as a _GA_ blocker to incentivize / remind us to fix this before we ship 23.1, on the back of a [similar](https://github.com/cockroachdb/cockroach/issues/101896) GA blocker.

There is more context around the motivations [here](https://cockroachlabs.slack.com/archives/C0366GQV668/p1678297597990449) (internal).

**Comment by jbowens** [comment]
This is being deferred to 23.1.1. We don't believe it's possible to exercise this bug in Cockroach, because external synchronization prevents writing the same key concurrently.

**Comment by jbowens** [comment]
Fixed in #102882.
