### ISSUE TITLE
23.1 Acceptance testing: Provide a clear tool tip to describe Idle time in the console

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#102361]
We should provide a tool tip that describes what idle time (Client Wait Time) is measuring and how users should take action. This is especially useful for the case of statements. Users look at statements in isolation so seeing a high idle time may mislead them into thinking there is an issue with CRDB where they should then be looking at the transaction in the context of their application workload. 

Tool tip: The wait time for this statement on the client. This time measures the time spent waiting for the client to send the statement while holding the transaction open. A high wait time indicates that you should revisit the entire transaction and [batch your statements](https://www.cockroachlabs.com/docs/stable/transactions.html#batched-statements).

We should also consider moving idle latency (renamed to Client Wait Time) to another chart to avoid confusing users who is using the Statement Time chart to correlate with other metrics in the console. Idle latency does not correlate with statement service latency or statement time on the overview page.

Related issue: https://github.com/cockroachdb/cockroach/pull/91098

Jira issue: CRDB-27411

**Comment by glennfawcett** [comment]
This needs to be RENAMED as well as documented.  Having this show up as IDLE is totally misleading.  There are waits on resources.... IO, Network, Locks, Admission Queues, ....

If we can get timings for IO, Network, Locks, .... then it should be illustrated as such.  Otherwise, please show it as "Other Wait" times.

**Comment by kevin-v-ngo** [comment]
Tool tip: The wait time for this statement on the client. This time measures the time spent waiting for the client to send the statement while holding the transaction open. A high wait time indicates that you should revisit the entire transaction and [batch your statements](https://www.cockroachlabs.com/docs/stable/transactions.html#batched-statements).

@florence-crl let me know if anything should be adjusted. Thanks!
