### ISSUE TITLE
sql: SHOW CREATE VIEW shouldn't require privileges on anything other than the view itself

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#10245]
The comment [here](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/show.go#L302) says you need any privilege on the target view, which is true. But you also need `SELECT` privileges on all tables/views reference by the view's `SELECT` statement.

**Comment by a-robinson** [comment]
The comment is right, it's the behavior that's wrong :) Thanks for catching and filing the issue!

**Comment by a-robinson** [comment]
Also leaving myself a reminder here to update the show-create-view.md documentation file once this behavior has been fixed.
