### ISSUE TITLE
roachtest: acceptance/version-upgrade is flaky

### ISSUE THREAD

**Issue by renatolabs** [cockroachdb/cockroach#102431]
There's still a flake related to partial index visibility that comes up in `acceptance/version-upgrade`:

> ` "message": "***UNEXPECTED ERROR; Received an unexpected execution error.: ERROR: unimplemented: partially visible indexes are not yet supported (SQLSTATE 0A000)",`

Example from a recent bors run: <https://teamcity.cockroachdb.com/viewLog.html?buildId=9839037&buildTypeId=Cockroach_BazelEssentialCi>.

Related: #102200.

cc @fqazi @rytaft 

Jira issue: CRDB-27443

**Comment by rytaft** [comment]
I'm not sure why we're still generating partially visible indexes in the multi-version cluster. Any ideas, @fqazi? In the meantime, I opened https://github.com/cockroachdb/cockroach/pull/102497 to stop the flake.

**Comment by rytaft** [comment]
I know why -- operation_generator.go also calls randgen, which wasn't updated. Will fix that now.
