### ISSUE TITLE
sql: add pg_catalog.pg_views metadata table

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#10240]
Postgres provides an `information_schema.views` table: https://www.postgresql.org/docs/9.1/static/infoschema-views.html

And a `pg_catalog.pg_views` table: https://www.postgresql.org/docs/9.1/static/view-pg-views.html

These would make it easier to reflect on views. 

@a-robinson

**Comment by mtMabo** [comment]
@jseldess  @a-robinson  
I'm working on this issue, pls refer to #8675.  Thanks.

**Comment by jseldess** [comment]
Thanks, @mtMabo!

@nvanbenschoten, feel free to close this since https://github.com/cockroachdb/cockroach/issues/8675 seems to cover all remaining tables.

**Comment by nvanbenschoten** [comment]
That issue is only covering the `information_schema`, so we can keep this open to cover `pg_catalog.pg_views`.
