### ISSUE TITLE
Add a pgvector-like capability to enable semantic search

### ISSUE THREAD

**Issue by mgoddard** [cockroachdb/cockroach#102664]
Having support for vector data types and operations such as exact and approximate nearest neighbor search, L2 distance, inner product, and cosine distance on these would open up semantic search use cases for users of CockroachDB.

This is the PostgreSQL implementation: https://github.com/pgvector/pgvector

With the rise of large language models (LLMs) and vector databases, this capability may become increasingly relevant to users of CockroachDB.

Jira issue: CRDB-27577

**Comment by rytaft** [comment]
cc @DingDLu

**Comment by OndraZizka** [comment]
Same wish / question here - any chance CockroachDB could deliver the vector indexing functionality?

**Comment by michae2** [comment]
[triage] now that we have some vector support in v24.2, closing this. there will be a separate issue for indexing vectors.
