### ISSUE TITLE
storage: sstables virtual SQL table

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/cockroach#102604]
This is a bit of a wishlist item, but it would be nice if we could query the sstables as a virtual SQL table. The various sstable properties could be exposed through this same interface.

Current Progress So Far: 
- [x] add `approximateSpanBytes` row on cockroach side
- [x] add `WithApproximateSpanBytes` filter option on pebble side
- [x] create set generating function (cockroach)
- [x] figure out iterator structure to display rows (cockroach)
- [x] make RPC request to retrieve information from Pebble (cockroach)
- [x] add sstable filter option (pebble)

Jira issue: CRDB-27555

**Comment by RaduBerinde** [comment]
@jbowens @nicktrav @RahulAggarwal1016 I figured we should brainstorm in more detail. I am pasting a more detailed description from @nicktrav and there are some questions below to think about.

> One way of making these summary statistics more readily available is to allow a user to run a builtin SQL command from a SQL shell - e.g. SELECT * FROM crdb_internal.engine_stats WHERE start_key > ‘\x00’ AND end_key < ‘\xff’. The builtin would return SSTable level properties from the tables that match the predicates, presented in a row-oriented format (e.g. one row per node, store, SSTable tuple with a JSON blob of the table stats and properties).
> 
> This command would ideally avoid needing to scan through actual data. Instead, the command could leverage the in-memory table stats maintained in Pebble. This would allow for a relatively fast and inexpensive means of taking our a read state on the DB, and iterating over tables that match the various predicates.

Should the API use raw keys or should it use SQL-level values (e.g. table + PK)? In the latter case, it might make more sense to extend `SHOW RANGES` instead of a new construct. That said, we can use `SHOW RANGES WITH KEYS` to get the raw keys so a raw key API would be fine too.

I assume we want to return info about relevant SSTables from all replicas? Would it be important to make it easily visible in the result whether an SSTable is from a replica or from the leaseholder?

**Comment by jbowens** [comment]
> Should the API use raw keys or should it use SQL-level values (e.g. table + PK)? In the latter case, it might make more sense to extend SHOW RANGES instead of a new construct. That said, we can use SHOW RANGES WITH KEYS to get the raw keys so a raw key API would be fine too.

I vote raw keys; there have been instances where we've wanted better observability into the liveness range's on-disk data, which wouldn't be expressible with the high-level SQL values. I think this is always what some other storage internal funcs use (`compact_engine_span`).

> I assume we want to return info about relevant SSTables from all replicas?

If a query filters on store ID, is it possible to apply that filter before the fan out, or would that be impossible or too tricky through `crdb_internal`? If it's too tricky, then I think the caller should have to pass a single store ID and operators can always construct queries to query every store.

> Would it be important to make it easily visible in the result whether an SSTable is from a replica or from the leaseholder?

I don't think it's too important, as long as we can look up whether the relevant store is leaseholder for a particular range somewhere (I think we have this, but IDK where).

----

We have an existing [DB.SSTables](https://pkg.go.dev/github.com/cockroachdb/pebble#DB.SSTables) function that we can use and build off. We want to expose sstable properties, but it's a bit unfortunate that this would require loading every table in the database even if we might only want properties for some tables.

**Comment by RaduBerinde** [comment]
Thanks!  The problem with the virtual table proposal is that we don't really support doing anything smart with range filters (for the key). The only thing we can optimize is strict equality on a column.

I believe it would be more appropriate to have a couple of built-in functions along the lines of:
```
# Returns stats for all sstables (on all nodes and stores) that intersect this key range.
SELECT crdb_internal.engine_stats('startkey', 'endkey')

# Returns stats for all sstables on the given store that intersect this key range.
SELECT crdb_internal.engine_stats('startkey', 'endkey', store-id)
```

Two proposals for what these functions output:
 1. multiple rows with one JSON object per row (one for each SSTable).
 2. an ARRAY of JSON objects, one JSON object for each SStable. Note that an array can easily be converted in multiple rows by wrapping the function call in `unnest()`.


> I don't think it's too important, as long as we can look up whether the relevant store is leaseholder for a particular range somewhere (I think we have this, but IDK where).

`SHOW RANGES` presents all this information.

**Comment by RaduBerinde** [comment]
> If we output rows, would it make sense to put some mandatory fields as top-level columns (eg, level, file number, size, etc)?

I'll need to investigate if it's possible to have a set-generating-function that can be unnested to multiple columns.

> The DB.SSTables function currently returns the sstables as an array of slices. Do we need an iterator-style interface for SQL to consume, or would SQL end up pulling all the returned sstable metadata into memory at once regardless?

I think we can start by just pulling all metadata into memory and reassess if performance is an issue. Isn't this metadata already in memory inside Pebble?

**Comment by jbowens** [comment]
> I think we can start by just pulling all metadata into memory and reassess if performance is an issue.

Sounds good.

>  Isn't this metadata already in memory inside Pebble?

All the `FileMetadata` is, but the 'properties' from the properties block are only in-memory for tables that are currently in the table cache.

**Comment by RaduBerinde** [comment]
> All the FileMetadata is, but the 'properties' from the properties block are only in-memory for tables that are currently in the table cache.

And FileMetadata would be sufficient to filter out based on what intersects a key range, right? It  sounds like the best API would be one that allows you to specify a key range of interest. We could extend `SSTables` like that.

**Comment by RaduBerinde** [comment]
I am writing down here some pointers around existing functionality that has some overlap with what we're trying to implement.

#### Set-generating functions

The proposed `crdb_internal.engine_stats` is a set-generating function (SRF). It will be useful to look at how other set-generating functions are defined and maybe play around with how they work. Some examples:
 - [unnest](https://github.com/cockroachdb/cockroach/blob/4539072e48942b77721b1e3044235c1013266dc4/pkg/sql/sem/builtins/generator_builtins.go#L281) is a function that takes an array and returns each element as a different row. Example:
```sql
demo@127.0.0.1:26257/demoapp/defaultdb> SELECT unnest(ARRAY[1,2,3]);                                                                                                                                                                                                                                                                                    
  unnest
----------
       1
       2
       3
(3 rows)

# Can also be used as if it's a table:
demo@127.0.0.1:26257/demoapp/defaultdb> SELECT * FROM unnest(ARRAY[1,2,3]);                                                                                                                                                                                                                                                                             
  unnest
----------
       1
       2
       3
(3 rows)
```

- [json_populate_recordset](https://github.com/cockroachdb/cockroach/blob/4539072e48942b77721b1e3044235c1013266dc4/pkg/sql/sem/builtins/generator_builtins.go#L389) is an example of an SRF that returns "labeled tuples" which can be treated like multiple columns; some examples in [the tests](https://github.com/cockroachdb/cockroach/blob/255bc76d4d440c0d3c4e4ef2497a139464fd387e/pkg/sql/logictest/testdata/logic_test/json_builtins#L1339)
- [pg_get_keywords](https://github.com/cockroachdb/cockroach/blob/4539072e48942b77721b1e3044235c1013266dc4/pkg/sql/sem/builtins/generator_builtins.go#L231) is another example of a multi-column SRF. Try to run `SELECT pg_get_keywords()` and `SELECT * FROM pg_get_keywords()` in `cockroach demo`.


#### Issuing RPCs out to other nodes

Our proposed function will need to send an RPC to each node to retrieve the relevant SSTables. An existing function that issues an RPC is [crdb_internal.compact_engine_span](https://github.com/cockroachdb/cockroach/blob/774684db08286129e97b9e2a4b8162c198ac947c/pkg/sql/sem/builtins/builtins.go#L6557). The implementation calls out to the [StorageEngineClient](https://github.com/cockroachdb/cockroach/blob/213da1f9fb591d90dcea6590b31da8c55b0756f9/pkg/kv/kvserver/storage_engine_client.go#L33) which is handled on the other side in [the stores server](https://github.com/cockroachdb/cockroach/blob/5b6302b2ed2a83f49b55329ce3cac5f6135d0aea/pkg/kv/kvserver/stores_server.go#L145).

There will be some additional work to plumb through the list of all nodes. But as a start, we can first implement a version of `crdb_internal.engine_stats` that takes the node ID and the store ID (just like `compact_engine_span` does), e.g. `SELECT * FROM crdb_internal.engine_stats(node-id, store-id, start-key, end-key)`.


#### Pebble side

The stores server code above will call out to Pebble, specifically [DB.SSTables](https://github.com/cockroachdb/pebble/blob/25a8e9bb8d9586e5090979f24dec11712e9f4b3c/db.go#L1912). It would be good to add an `SSTablesOption` that filters the tables on a key span; we can perform the filtering using only the `FileMetadata` and avoid unnecessary `getTableProperties` calls.

**Comment by RaduBerinde** [comment]
@jbowens what exactly do we want in the json? Everything that is inside `sstable.Properties`?

**Comment by jbowens** [comment]
yeah, everything in the SSTableInfo, including the entire `sstable.Properties` I think

**Comment by jbowens** [comment]
Following up on the variant of this function that does not take a node ID: I don't think fanning out to all nodes will work well, because even nodes that don't have a replica overlapping the provided key range may have sstables overlapping the key range (which then contain no data within range). This is likely to be more confusing than helpful.

Personally, I'm okay with just the node-targeted version and requiring some SQL foo to combine it with SHOW RANGES as necessary. @RaduBerinde Thoughts?

A second thought motivated by the above: I think we should also include an 'ApproximateSpanBytes' field that captures the approximate number of bytes that overlap the provided key span for each sstable. This would need to be enabled through another `SSTableOption` passed to `DB.SSTables`. If an sstable is wholly contained within the key range, its entire size would be used. If it partially overlaps the key range, we can `(*sstable.Reader).EstimateDiskUsage` which cheaply consults the index blocks only. See https://github.com/cockroachdb/pebble/blob/9642416a948c8911152fafa0ffc4c12a3edeec8f/db.go#L1995-L2020

**Comment by RaduBerinde** [comment]
In general - given that this is something aimed to be useful for escalations, we need to make it as easy as possible to minimize back and forth (since we won't be running it ourselves in most cases).

**Comment by RahulAggarwal1016** [comment]
would these changes be in a separate pr? i.e. should I try to merge the pr I currently have open?

**Comment by RaduBerinde** [comment]
Yes, we do want the variant that you already implemented.

**Comment by RahulAggarwal1016** [comment]
for adding the `ApproximateSpanBytes`, how should that value be returned from `DB.SSTables()`, should it be added as a new property on `SSTableInfo.Properties`?
