### ISSUE TITLE
sql: don't double parse decimals in AS OF

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#10260]
See: https://reviewable.io/reviews/cockroachdb/cockroach/10242#-KV479e1-il0bR3xmnji:-KV4E5ZelwdknWOnCF_C:b-1t4bve

**Comment by a6802739** [comment]
@mjibson, ok , I could try it.

**Comment by mjibson** [comment]
Closing this because this is a tiny performance gain for a rarely-used feature and it removes many kinds of usable expressions.
