### ISSUE TITLE
sql: provide tooling to ease onboarding of data into cockroachdb

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#10261]
We should take heed of Microsoft's success in the 90's: make a great tool but also make great import filters to convert foreign data to get it into CockroachDB. The more tools we provide to get the data inside a DB, the less tools users will have to make themselves and thus the lower the barrier to adoption becomes.

Some suggestions:
- import from CDF http://cdf.gsfc.nasa.gov/
- import from XML

A couple suggestions by @glycerine in #4213:
- import from CSV
- import from messagepack
- import from JSON
- import from TMFRAME https://github.com/glycerine/tmframe

**Comment by glycerine** [comment]
Being able to load CSV and JSON are probably top of my list in terms of usefulness.

**Comment by mjibson** [comment]
Can you give examples of tools that produce such CSV or JSON output?

**Comment by glycerine** [comment]
@mjibson I hope you are trolling. These are the single most ubiquitous formats for data in general.

**Comment by mjibson** [comment]
My question was not trolling. If we are to write importers for this data, it is important to know how that data deals with: delimiters, escaping delimiters, escapes, newlines, quotes, column names, table names, non-ASCII characters, arbitrary bytes, numbers with large exponents, floating point NaN and infinity, byte arrays, dates, timestamps, etc. While CSV and JSON are well defined, importing them into a database that has a much larger range of types than either of those formats is not simple. I'm interested in specific tools people already use for existing databases so we can be sure to exercise the edge cases and support them correctly. I spend a fair amount of my time working on SQL correctness, data import, and double round-tripping data to make sure we don't incorrectly parse anything. We'll need to do the same verification here.

**Comment by aaronwinter** [comment]
@mjibson FWIW, Neo4j has developed two import tools that only work on CSV files. Granted they are in a different problem domain though it might indicate there is at least somewhat of an industry demand for supporting this data format in particular.

The first tool is a Cypher (graph query language) command `LOAD CSV` which targets "medium sized datasets" and the other tool is a batch import binary for larger data sets (or "super huge data sets" as they say :smile_cat: ). 

I agree with all your points and Neo4j despite having a smaller spectrum of data types available also recommend their users to perform data validation before uploading their CSVs. See:

> Real world data is messy. Don’t assume what someone told you is in a CSV file is actually, in there, don’t rely on format descriptions, consistency or correct quoting. Only trust data validity that you checked yourself.

They also list common pitfalls, I think that might interest you.

[0] - `LOAD CSV` : https://neo4j.com/developer/guide-import-csv/
[1] - `neo4j-import`: https://neo4j.com/developer/guide-import-csv/#_super_fast_batch_importer_for_huge_datasets

**Comment by dianasaur323** [comment]
@knz, @jseldess is going to take an intermediate step by surfacing our docs on importing CSVs more prominently. Only a first step, but I believe appropriate for our current timeline.

**Comment by vivekmenezes** [comment]
I think we should close this issue. It's not actionable and we're making strides to improve migration from mysql in release 2.1

**Comment by knz** [comment]
Meta-issues are not meant to be actionable, but instead to refer to more specific issues with descriptions of work.

Compatibility with mysql is just 1 of the various linked issues. If you want to close this one at least create 1 specific issue for each of the avenues mentioned in the original description.

**Comment by vivekmenezes** [comment]
I'm not closing this issue because creating an issue for each of the individual ones doesn't make sense at this time. Thanks!
