### ISSUE TITLE
storage: restarting node without its data causes other nodes to get stuck

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#10266]
What I did:
1. Created a 3-node insecure cluster on build beta-20161013-297-g33c94fa
2. Opened up a SQL shell on the first node and ran `SHOW DATABASES;` and `CREATE DATABASE foo;`
3. Killed the first node
4. Created a new node with the same hostname as the original first node ("cockroachdb-0.cockroachdb.default.svc.cluster.local", this was on kubernetes) but with an empty/new data directory
5. Open up a SQL shell against any of the 3 nodes and run `SHOW DATABASES;`

This returns the error `pq: store 1 not found` on all of the cockroachdb nodes. This error sticks around for more than 5 minutes after taking down the old node and bringing up the new one. In fact, it didn't go away for a solid 10 minutes, so it seems as though it may be permanent.

I decided to restart the new node. Shutting it down immediately caused the other 2 nodes to start working again, and the new node worked fine as well when it came back up. I've attached the logs for the new node both times that it came up as well as one of the other nodes.

It looks like this error has been seen before in #5056/#5166, but those have both been long closed.

[node0-attempt1.txt](https://github.com/cockroachdb/cockroach/files/556367/node0-attempt1.txt)
[node0-attempt2.txt](https://github.com/cockroachdb/cockroach/files/556366/node0-attempt2.txt)
[node1.txt](https://github.com/cockroachdb/cockroach/files/556368/node1.txt)

**Comment by a-robinson** [comment]
The new node was unable to ever properly join the cluster due to the same error:

```
I161027 15:36:11.134071 94 sql/event_log.go:94  [n4] Event: "node_join", target: 4, info: {Descriptor:{NodeID:4 Address:{NetworkField:tcp AddressField:cockroachdb-0.cockroachdb.default.svc.cluster.local:26257} Attrs: Locality:} ClusterID:{UUID:c30883ca-7391-4e3c-9898-1ce56d4fafbb} StartedAt:1477582571132467568}
W161027 15:36:11.137094 94 server/node.go:766  [n4] node=4: unable to log node_join event: store 1 not found
I161027 15:36:11.137499 91 gossip/gossip.go:271  [n4] NodeID set to 4
I161027 15:36:11.137865 91 server/node.go:543  [n4] bootstrapped store [n4,s4]
W161027 15:36:11.138471 91 server/node.go:553  [n4] error writing node summary after store bootstrap: store 1 not found
I161027 15:36:11.194651 94 sql/event_log.go:94  [n4] Event: "node_join", target: 4, info: {Descriptor:{NodeID:4 Address:{NetworkField:tcp AddressField:cockroachdb-0.cockroachdb.default.svc.cluster.local:26257} Attrs: Locality:} ClusterID:{UUID:c30883ca-7391-4e3c-9898-1ce56d4fafbb} StartedAt:1477582571132467568}
W161027 15:36:11.195065 94 server/node.go:766  [n4] node=4: unable to log node_join event: store 1 not found
I161027 15:36:11.300599 94 sql/event_log.go:94  [n4] Event: "node_join", target: 4, info: {Descriptor:{NodeID:4 Address:{NetworkField:tcp AddressField:cockroachdb-0.cockroachdb.default.svc.cluster.local:26257} Attrs: Locality:} ClusterID:{UUID:c30883ca-7391-4e3c-9898-1ce56d4fafbb} StartedAt:1477582571132467568}
W161027 15:36:11.301270 94 server/node.go:766  [n4] node=4: unable to log node_join event: store 1 not found
[...]
```

**Comment by a-robinson** [comment]
Judging by the repeated errors on node 1, there appears to have been some confusion in the raft layer:

```
W161027 15:48:28.249160 894 storage/store.go:2830  [n2,s2] got error from range 0, replica {1 1 0}: storage/raft_transport.go:247: unable to accept Raft message from {NodeID:2 StoreID:2 ReplicaID:0}: no handler registered for {NodeID:1 StoreID:1 ReplicaID:0}
```

**Comment by a-robinson** [comment]
Coming back to this, I repro'd it on the first try and the cluster is very confused:

<img width="1293" alt="screen shot 2016-11-01 at 11 06 47 am" src="https://cloud.githubusercontent.com/assets/7085343/19894413/53e3c674-a023-11e6-8bdd-8a3f81b24320.png">

**Comment by a-robinson** [comment]
cockroachdb-0 and cockroachdb-1 have recovered and started working, but cockroachdb-2 is still unhappy with the "store 1 not found" error. Digging in more today.

**Comment by a-robinson** [comment]
So, judging by the logs, it appears as though what happened in this case was something like this:

1. I wiped cockroachdb-0's data directory and shut it down, effectively removing node 0 from the cluster
1. cockroachdb-0 restarted with its empty data directory
1. cockroachdb-0 started back up and connected to gossip with its new ID (4)
1. cockroachdb-2's raft layer was in a retry loop of trying to talk to node ID 0. Its Gossip struct still had state around for node 0 (due to the 5 minute timeout on nodes being removed), so the call to Gossip.GetNodeIDAddress from RaftTransport.connectAndProcess (via its resolver) still returns the hostname of cockroachdb-0
1. The GRPCDial to cockroachdb-0 in RaftTransport.connectAndProcess succeeds due to cockroachdb-0 being back up again
1. RaftTransport.connectAndProcess considers the connection established and moves on to running RaftTransport.processQueue, where things go poorly because it thinks it's talking to node 1 while it's actually talking to node 4
1. The raft processing apparently never gives up despite the repeated errors, leaving the node permanently broken until either it or cockroachdb-0 gets restarted

**Comment by a-robinson** [comment]
Also, for the record, I've repurposed this issue from being about the error bubbling up to being about the underlying issue with restarting a node. The error leaking into SQL can be tracked as part of #5452

**Comment by petermattis** [comment]
@tamird is probably as familiar as I am and has more time to look at this.

**Comment by a-robinson** [comment]
I talked with @tamird  this afternoon, and he thinks that we should expand HandleRaftResponse to understand this error and be capable of returning an error to processQueue to indicate that the queue should stop using the current connection. And once that's done, get a test in place for this using the TestCluster infrastructure.

I'll start working on this soon unless anyone else has a hankering to do so.
