### ISSUE TITLE
sql: INSERT ON CONFLICT DO NOTHING returns 1 row affected on conflict

### ISSUE THREAD

**Issue by asubiotto** [cockroachdb/cockroach#10264]
Trying to insert a row into a table with an `INSERT INTO ON CONFLICT DO NOTHING` statement where we would expect a conflict returns that one row was affected. See the response to the second `INSERT INTO ON CONFLICT DO NOTHING` statement.

![image](https://cloud.githubusercontent.com/assets/10560359/19770207/6ee56b80-9c2c-11e6-822d-3fbcb9e16f9d.png)

Postgres returns 0 rows affected:

![image](https://cloud.githubusercontent.com/assets/10560359/19770590/d4a0ac36-9c2d-11e6-8483-c0567be7e791.png)

**Comment by spencerkimball** [comment]
ping. @asubiotto could you update this issue? Should it remain 1.0 milestone?

**Comment by asubiotto** [comment]
There are more important things to tackle right now. Moved to after and unassigned.

**Comment by knz** [comment]
I fixed this in #23373.
