### ISSUE TITLE
schema: update redaction for precondition error message

### ISSUE THREAD

**Issue by rimadeodhar** [cockroachdb/cockroach#102757]
**Describe the problem**

The error message for invalid descriptor generated by the [upgrade precondition check](https://github.com/cockroachdb/cockroach/blob/3688055c09cd32f1186624a1ccc3fe35e5a0cffd/pkg/upgrade/upgrades/precondition_before_starting_an_upgrade.go#L64-L64) is heavily redacted making the redacted version unusable. We should examine the message and ensure the redacted log message is actionable as well.

Jira issue: CRDB-27638

Epic CRDB-27642

**Comment by abarganier** [comment]
The error message being written is a raw string, so it's expected that it'd be fully redacted. We'd need to create a type for the error message that [implements the `SafeFormatter` interface](https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/1824817806/Log+and+error+redactability#When-to-use-SafeFormatter-vs-SafeValue) to reduce the redaction here, AFAIK. 

Can we have some examples of what these error messages look like? It's possible that redaction markers are being inserted properly when the error message is first generated, but the fact that we're *then* dealing with a raw string later is what's causing the message to be fully redacted.

**Comment by rimadeodhar** [comment]
An example of what this error message looks like:
```
W230418 12:50:56.605205 1804865 upgrade/upgrademanager/manager.go:114 ⋮ [n9,intExec=‹set-version›,migration-mgr] 16163 +‹invalid descriptor: system.public.tenant_settings (50) because 'no matching name info found in non-dropped database "defaultdb"'›
```

**Comment by rimadeodhar** [comment]
@abarganier: Based on the [document](https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/1824817806/Log+and+error+redactability#When-to-use-SafeFormatter-vs-SafeValue) you linked above, looks like using `redact.StringBuilder` [here](https://github.com/cockroachdb/cockroach/blob/3688055c09cd32f1186624a1ccc3fe35e5a0cffd/pkg/upgrade/upgrades/precondition_before_starting_an_upgrade.go#L64-L64) instead of `string.Builder` should work here. Does that seem right to you?

**Comment by knz** [comment]
All this code has been deleted in v23.1, as it pertains to migration code to v22.2. Do we still need/want to update the logging in the v22.2 branch?

**Comment by knz** [comment]
@smcvey requests that we do the patch on the 22.2 branch (and perhaps 22.1 if the code is there too) since we have customers who will need to upgrade into 22.2 before they hop to 23.1.

**Comment by rimadeodhar** [comment]
@knz thanks Raphael for checking. Re: my previous question, would it be sufficient to use redact.StringBuilder here?

**Comment by knz** [comment]
> Re: my previous question, would it be sufficient to use redact.StringBuilder here?

No it would not be sufficient. 

That is because the `invalid_objects` vtable does not sufficiently distinguish private vs public details in the "reason" column. The proper fix needs to inline the logic of the vtable into the migration check, to further detail the "reason" field using finer-grained `redact.StringBuilder` / `RedactableString`.

Alternatively you could work to add a hidden column to `invalid_objects` that repeats the "reason" column as a `RedactableString` and use that in the migration check.

In any case the current `invalid_objects` vtable is insufficient.

**Comment by knz** [comment]
fixed here https://github.com/cockroachdb/cockroach/pull/104048
