### ISSUE TITLE
ui: SQL system information needed by the UI should be accessible through SQL statements

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#10271]
I believe there are a number of instances where the UI backend has built its own custom logic to query the schema. As a result, we have bugs such as https://github.com/cockroachdb/cockroach/issues/9689 crop up. Let us standardize on SQL as much as possible, and whenever a UI feature is unavailable through SQL, figure out how we can add it to SQL first.

**Comment by mrtracy** [comment]
I think you misunderstand that bug; that occurs when the frontend tries to query _statistics_ about virtual tables, such as their size and range count. The tables do not actually exist, so they do not have any keys, and attempts to query range data thus fail. We are not querying the schema in a non-standard way: we are attempting to compute information about tables that is separate from the schema.

**Comment by vivekmenezes** [comment]
How about we place computing this information about tables under SQL. Perhaps we need something similar to pg stats. See how you can query the number of rows in a table: There are two ways, one transactionally, and the other is through the stats framework that provides estimates.

http://stackoverflow.com/questions/2596670/how-do-you-find-the-row-count-for-all-your-tables-in-postgres

**Comment by mrtracy** [comment]
I assume that the new title more reflects the concern - that SQL-related information in the UI should always be available through a SQL query, and that the Admin API should just defer to the SQL query.

Note that in cases like fast table statistics (the system affected by #9689), I don't think the implementation of the actual computation would be appreciably different. That said, this probably _will_ cut down on bugs, assuming that it raises awareness of UI concerns for developers working in the SQL system.

**Comment by knz** [comment]
This has been advanced tremendously, insofar that there is now a strong PM / eng discipline to reflect items in the UI. There are now more specific github issues to act on this. This issue has completed its purpose.
