### ISSUE TITLE
75% increase in Django test suite run time between CockroachDB 22.2 and 23.1

### ISSUE THREAD

**Issue by timgraham** [cockroachdb/cockroach#102851]
**Describe the problem**

The full Django test suite as run by TeamCity for https://github.com/cockroachdb/django-cockroachdb/ takes around 40 minutes for CockroachDB 22.2.x. 

The same run as of CockroachDB 23.1 rc2 takes around 70 minutes, down from around 90 minutes at 23.1 beta 3, before the fix for https://github.com/cockroachdb/cockroach/issues/100871.

You can see the various builds at https://github.com/cockroachdb/django-cockroachdb/pull/279.

(I couldn't identify the cause of the regression during the 23.1 development cycle as there were months when the Django test suite wouldn't run without error due to https://github.com/cockroachdb/cockroach/issues/94337.)

I generated a slow query log with threshold 1000ms for CockraochDB 22.2.8 and CockroachDB nightly (v23.1.0-alpha.8-dev-3f8cb919339a7f19bd3d20c86488d6a46af9fb7f @ 2023/05/05 23:26:11) (the nightly build gives a similar total run time as 23.1 rc2.) 

22.2.8: 423 queries with total time of 8.7 minutes
Nightly: 460 queries with total time of 10.1 minutes

This result suggests to me that there may be some other cause besides simply slow queries (though it's possible there are a lot of queries with sub-1-second run time that are accounting for the difference). I'm happy to continue investigating with a pointer in the right direction, or perhaps it would be more efficient for the CockroachDB developers to take it from here.

Jira issue: CRDB-27689

**Comment by fqazi** [comment]
@timgraham Does falling back get_table_list to the 22.2 method help? The old method doesn't fetch comments, and I wonder if that makes a big dent. We have changed how comments are scanned, and as a side effect, we are reading all descriptors now. I'm trying out optimization so we don't scan everything when obj_description is invoked.

**Comment by timgraham** [comment]
Yes, disabling supports for comments reduces the run time on 23.1/nightly to 55 minutes, down from 70 minutes, but still up from 40 minutes for 22.2.

**Comment by fqazi** [comment]
@timgraham I'm going to address the comment fetching aspect, which got it down to around ~47 minutes for me locally. I'll see if there are other things to attack here. Thanks for testing it out

**Comment by fqazi** [comment]
I'll adjust the PR I have to keep this one open as well, since it won't fully eliminate the timing I think

**Comment by timgraham** [comment]
Did you have comments enabled in django-cockroachdb when you tested locally (as in https://github.com/cockroachdb/django-cockroachdb/pull/279)? I'm not seeing much improvement with CockroachDB nightly (70 minutes) vs. 23.1.1 [which I believe doesn't have your fix here] (75 minutes) (see builds at https://github.com/cockroachdb/django-cockroachdb/pull/282).

**Comment by fqazi** [comment]
Let me go and analyze this again. I used your pull request but it might have been disabled there temporarily

**Comment by timgraham** [comment]
I'm seeing a speed-up of perhaps a couple of minutes after Rafi's last change in CRDB nightly and 23.1.5, but it's rather insignificant compared to the total regression in 23.1.x of around 30 minutes. As noted earlier in https://github.com/cockroachdb/cockroach/issues/102851#issuecomment-1540343729, even with the comments queries disabled, the runtime of Django's test suite with CockroachDB 23.1.5 is around 60 minutes compared to 40 minutes with 22.2.x. The builds were run today at https://github.com/cockroachdb/django-cockroachdb/pull/279.

**Comment by rafiss** [comment]
Thanks for checking again. To move forward on this, could you measure which steps of the test suite are slow, capture any slow queries, and report these in a new issue?

**Comment by timgraham** [comment]
As I wrote in this issue's description, I previously didn't have much luck identifying the cause of the slowness and those last efforts didn't feel very efficient, particularly if CockroachDB developers have better tools and more experience with profiling. I can try again if you like but some more specific advice might be helpful.

**Comment by rafiss** [comment]
My suggestion is to measure where the time is going in the Django test suite. Is it test setup? Is it specific tests that take longer?

After we have that narrowed down, then we can capture the queries that are running in that part of the test by using The SQL Exec log: https://www.cockroachlabs.com/docs/v23.1/logging#sql_exec

Also, I see shorter run times in our TeamCity nightly job:
- on master, 31 minutes: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10813231?buildTab=tests&showLog=10813231_7024_2317.7024&logFilter=debug&logView=linear
- on 23.1, 29 minutes: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/10813255?buildTab=tests&status=all&name=django&showLog=10813255_5063_2447.5063&logFilter=debug&logView=linear
