### ISSUE TITLE
Unexpected results of `IN` with redundant values list 

### ISSUE THREAD

**Issue by DerZc** [cockroachdb/cockroach#102864]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

Consider the following program:
```
SET CLUSTER SETTING diagnostics.reporting.enabled    = false;
SET CLUSTER SETTING diagnostics.reporting.send_crash_reports = false;
SET CLUSTER SETTING sql.metrics.statement_details.plan_collection.enabled = 'off';
SET CLUSTER SETTING sql.stats.automatic_collection.enabled = 'off';
SET CLUSTER SETTING timeseries.storage.enabled = 'off';
set experimental_enable_hash_sharded_indexes='on';

CREATE TABLE t0 (c0 INT4);
INSERT INTO t0 (rowid, c0) VALUES(0, 0);
INSERT INTO t0 (c0) VALUES(5);

SELECT t0.c0, t0.rowid FROM t0 WHERE ((NULL)OR((t0.c0) IN ((VALUES (0::bigint), (862827606027206657::bigint)))));
SELECT t0.c0, t0.rowid FROM t0 WHERE ((NULL)OR((t0.c0) IN (SELECT ALL t0.rowid AS c0 FROM t0 WHERE true)));
```
The first query is equivalent to the second one, as there is only one value `0` that appear in the `c0` and `rowid` in the same time. So these two query should both return one row. But the first query return an empty result.

I tried to remove the redundant value in the first query like `SELECT t0.c0, t0.rowid FROM t0 WHERE ((NULL)OR((t0.c0) IN ((VALUES (0::bigint)))));`, then it can return correct result.

**Expected behavior**
The first query return one row.

**Environment:**
 - CockroachDB version https://github.com/cockroachdb/cockroach/commit/adad57859a5281e2846082761c8232890b3d2a68
 - Server OS: [Ubuntu 22.04]
 - Client app [CLI]

Jira issue: CRDB-27698

**Comment by mgartner** [comment]
Thanks for the report!

A simplified reproduction:

```sql
CREATE TABLE t (c INT4);
INSERT INTO t (c) VALUES (0);

SELECT c FROM t
WHERE c IN (0, 862827606027206657::INT8);

SELECT c FROM t
WHERE c IN (0);
```

It looks like this bug was introduced in v21.1. I've confirmed it's present v21.1.21 and later, and not present in v20.2.19.

**Comment by mgartner** [comment]
The query plan looks fine, so my guess is that there is a bug in the evaluation of `IN` with differing types, `INT4` vs `INT8`.

```
  select
   ├── columns: c:1(int4!null)
   ├── stats: [rows=20, distinct(1)=2, null(1)=0]
   ├── cost: 1098.65
   ├── distribution: us-east1
   ├── scan t
   │    ├── columns: c:1(int4)
   │    ├── stats: [rows=1000, distinct(1)=100, null(1)=10]
   │    ├── cost: 1088.62
   │    ├── distribution: us-east1
   │    └── prune: (1)
   └── filters
        └── in [type=bool, outer=(1), constraints=(/1: [/0 - /0] [/862827606027206657 - /862827606027206657]; tight)]
             ├── variable: c:1 [type=int4]
             └── tuple [type=tuple{int4, int4}]
                  ├── const: 0 [type=int]
                  └── const: 862827606027206657 [type=int]
```

**Comment by yuzefovich** [comment]
The bug likely has been present since #50337 when optimized `SelectIn` vectorized operator was introduced. Indeed, we're taking INT8 (which is `int64`) and converting it to `int32` here https://github.com/cockroachdb/cockroach/blob/19e57552fcfa8bb6f07945f699e67f3b8179be89/pkg/sql/colexec/select_in.eg.go#L1299-L1318

> do you have a sense for where in the stack the fix for this should happen?

I think we should just go for the quick fix and do as you're suggesting - simply upcast everything to `int64` in `selectInOpInt64`. We'll remove some code and will only need to be careful to call correct method when unwrapping `coldata.Vec`.

**Comment by mgartner** [comment]
SGTM. We should make a separate issue for the incorrect typing of the IN expression. That might fall under the meta issue #75101.

**Comment by DerZc** [comment]
There is a similar case, I guess they have the same reason.

The following program return an empty result, although the `CASE` always return `t1.c0`:
```
CREATE TABLE t1 (c0 VARBIT(172));
INSERT INTO t1 (c0) VALUES(B'1');

SELECT * FROM t1 WHERE t1.c0 IN (CASE WHEN false THEN t1.c0::BIT(172) ELSE t1.c0 END);
```

After analysis, I found this test case more similar with https://github.com/cockroachdb/cockroach/issues/78331, because I get the following results:
```
> SELECT CASE WHEN false THEN t1.c0::BIT(172) ELSE t1.c0 END FROM t1;
                                                                                       c0
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
(1 row)

Time: 0ms

> SELECT * FROM t1;
  c0
------
   1
(1 row)

Time: 0ms
```

**Comment by yuzefovich** [comment]
> We should make a separate issue for the incorrect typing of the IN expression. That might fall under the meta issue https://github.com/cockroachdb/cockroach/issues/75101.

FWIW postgres does allow the implicit upcast without encountering the "out of range" error, so I'm thinking that perhaps a separate issue is not warranted? @mgartner WDYT?

**Comment by mgartner** [comment]
>FWIW postgres does allow the implicit upcast without encountering the "out of range" error, so I'm thinking that perhaps a separate issue is not warranted? @mgartner WDYT?

Good point. Agreed!
