### ISSUE TITLE
bazel: print path to test log and crdb server logs after stress failure

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#102879]
Currently after a `./dev ... --stress` run fails (at least on a panic), the stack trace will get printed to stdout, but no paths to the failed test log in `cockroach/_bazel` or the cockroach server logs in the `test_temdir`. Instead, the test failure investigator must try to manually pattern match the failed test run to one of the server/test logs to investigate further. 

I have seen workarounds that involve passing `--show-logs` or `--verbose`, but passing these flags may prevent test failure reproduction, especially when `--race` is also passed. 

The lack of this feature slowed down my investigation of https://github.com/cockroachdb/cockroach/issues/102286, for example.

Jira issue: CRDB-27710

Epic CRDB-17171

**Comment by msbutler** [comment]
@rickystewart I'm still having trouble with the new `./dev stress`.

Here's [one way ](https://github.com/cockroachdb/cockroach/issues/110350#issuecomment-1716397645)to repro this on your gce worker.

**Comment by rickystewart** [comment]
@msbutler Did you look at the `test.log` file for the test run that failed?

**Comment by msbutler** [comment]
Yup, just dm'd you the log

**Comment by msbutler** [comment]
closing for now since this isn't a dev inf issue. may reopen once i understand why the path to the server logs are not getting written in test.log
