### ISSUE TITLE
cdc: support composite types in parquet

### ISSUE THREAD

**Issue by HonoreDB** [cockroachdb/cockroach#102904]
See https://github.com/cockroachdb/cockroach/issues/102903. I haven't looked into the canonical way to serialize these in Parquet but I imagine there is one.

Jira issue: CRDB-27719

Epic CRDB-27835

**Comment by jayshrivastava** [comment]
Closed by https://github.com/cockroachdb/cockroach/pull/104528, https://github.com/cockroachdb/cockroach/pull/103589, https://github.com/cockroachdb/cockroach/pull/103293
