### ISSUE TITLE
sql: composite types have unqualified `information_schema.columns.crdb_sql_type`

### ISSUE THREAD

**Issue by michae2** [cockroachdb/cockroach#102922]
User-defined enum types have a fully qualified name in `information_schema.columns.crdb_sql_type`, but user-defined composite types have an unqualified name. This interferes with adding composite types to our version of SQLSmith and the tests that depend on it.

Here's a demonstration:

```sql
CREATE TYPE a AS ENUM ('a');
CREATE TYPE b AS (b INT);
CREATE TABLE cd (c a, d b);
SELECT column_name, crdb_sql_type FROM information_schema.columns WHERE table_name = 'cd' AND is_hidden = 'NO';
```

returns:

```
demo@127.0.0.1:26257/demoapp/defaultdb> SELECT column_name, crdb_sql_type FROM information_schema.columns WHERE table_name = 'cd' AND is_hidden = 'NO';
  column_name |   crdb_sql_type
--------------+---------------------
  c           | defaultdb.public.a
  d           | B
(2 rows)
```

Jira issue: CRDB-27731

**Comment by mgartner** [comment]
@michae2 are you still working on this, or should we put this in Bugs To Fix or Backlog?
