### ISSUE TITLE
storage: multiraft TODOs

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#1029]
- [ ] create heartbeat tests with unreachable nodes, also test the "real" RaftTransport in presence of failures
- [ ] panic on sendMessage which is not a heartbeat but addresses dummy group
- [ ] report unreachable when a Raft message can't be sent (in server/raft_transport)

**Comment by tamird** [comment]
@tschottdorf can you update or close this, now that multiraft isn't a thing?

**Comment by bdarnell** [comment]
Multiraft isn't a package, but I'd say it's still a thing; the concepts still apply to the raft usage in the storage directory.

**Comment by bdarnell** [comment]
#7735 fixes the trivial part of this issue, and the other parts are split out into #7731 and #7732.
