### ISSUE TITLE
opt: insert on conflict fails to build virtual column

### ISSUE THREAD

**Issue by DrewKimball** [cockroachdb/cockroach#102909]
**Describe the problem**

A customer found that a complex insert statement with an `ON CONFLICT` clause was hitting an `ambiguous column` error, despite the column in question not being referenced in the statement. The following is a reduced reproduction. Note the second timestamp column `ts2` that is being set to the same expression that is used as the default value for `ts`, which is the column referenced by the virtual column. If either expression (default or SET) is modified, the query no longer fails.

**To Reproduce**

```
exec-ddl
CREATE TABLE t (
      id INT PRIMARY KEY,
      ts TIMESTAMP NULL DEFAULT timezone(NULL, current_timestamp()),
      computed FLOAT AS (extract('year', ts)) VIRTUAL,
      ts2 TIMESTAMP NULL
);
----

norm
INSERT INTO t(id)
SELECT * FROM (SELECT 0 AS id) AS input_table
ON CONFLICT (id) DO UPDATE SET ts2 = timezone(NULL, current_timestamp());
----
error (42702): column reference "ts" is ambiguous (candidates: excluded.ts, t.ts)
```

Jira issue: CRDB-27723

**Comment by mgartner** [comment]
Slightly reduced this further:

```
CREATE TABLE t (
  id INT PRIMARY KEY,
  a INT NULL DEFAULT 1,
  b INT NULL,
  c INT GENERATED ALWAYS AS (a+b) STORED
);

INSERT INTO t(id) VALUES (0)
ON CONFLICT (id) DO UPDATE SET b = 1;
```

**Comment by mgartner** [comment]
This has been present since v20.2. The root cause could be present in older versions, but computed columns, which are required in these reproductions, were introduced in v20.2.
