### ISSUE TITLE
sql: document the parameters for all functions

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#10292]
Since #9766 we can document functions by naming the parameters and providing a description _in the code_.
Today user twrobel on the Forum highlighted that `regexp_replace` for example is not yet annotated:
https://forum.cockroachlabs.com/t/psa-new-tag-ux-surprise-on-github/330/2?u=knz

`regexp_replace` should be annotated accordingly and probably the other built-in functions that don't have these annotations yet as well, and the docs site generation should be extended to use the additional metadata when generating the functions page.

**Comment by jseldess** [comment]
@dt, do you have an open issue for hooking function argument names and descriptions into the docs?

**Comment by dt** [comment]
not yet, let's co-opt this one.

**Comment by jseldess** [comment]
Thanks, @dt!

**Comment by jseldess** [comment]
@dt, any updates on this? Not urgent, but once this is in place, we can start chipping away at the descriptions.

**Comment by dt** [comment]
@mjibson just added the names of arguments to the generated docs, so all that's left is the prose. https://github.com/cockroachdb/docs/pull/851

**Comment by dt** [comment]
with cockroachdb/docks#917 (and #12284), most of the plumbing blocking this this is done, so now we can start actually filling in the Info fields and having the docs reflect that, which I believe @sploiselle has already started on.

**Comment by sploiselle** [comment]
Confirmed. Working on this.

**Comment by jseldess** [comment]
Think this is done and can be closed, @sploiselle?

**Comment by sploiselle** [comment]
Closed by #12533
