### ISSUE TITLE
cli/sql: feature request: report the txn status in prompt

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#10290]
Currently when a user has a long interactive session it can become confusing/uncertain whether there is a transaction currently ongoing server-side.

The CLI shell could request the current transaction status just before each prompt and use that to adapt the prompt. For example:

```
root@:26257    >SELECT 1;
...
root@:26257    >BEGIN;
BEGIN
root@:26257 TXN> 
root@:26257 TXN> SELECT foo FROM nonexistent;
pq: table 'nonexistent' not found
root@:26257 ERR> 
root@:26257 ERR> SELECT 1;
pq: transaction aborted, ignoring statements
root@:26257 ERR> 
root@:26257 ERR> ROLLBACK;
ROLLBACK
root@:26257    > 
```

To achieve this two steps are needed:
1. a new SHOW variable must probably be introduced to report the current txn status
2. the CLI shell must be extended to issue  SHOW in between prompts, like it does already for SYNTAX.

**Comment by yznming** [comment]
@knz maybe I can try to fix it.

**Comment by knz** [comment]
I'm ok with you looking at this but please base your contribution off #10187  thanks.

**Comment by knz** [comment]
ok the other PR is merged you're good to go.

**Comment by yznming** [comment]
@knz if the transaction is in the error status, the `show` statement would executes failed too. it seams like that using the `show` statement to get the transaction status is not suitable here.

**Comment by knz** [comment]
Ok thanks for this initial investigation. In the future it would be best to make SHOW for session/txn variables able to run even if the transaction status is aborted. 
However for now you can still make this workfor now: when the CLI sends SHOW and receives an error back from the server, you can check the error and see if the error contains the message "transaction is aborted", then use this information.

**Comment by yznming** [comment]
@knz I think we don't need introduce a new `SHOW` statement to check current transaction status. We can add a new variable`txnState` to `cliState` to trace the transaction status. The `txnState` is inited with `txnIdle` status at the beginning, and transfer to `txnRunning` status at `doCheckStatement()` if it meets a `BEGIN` statment. if the statements contain `COMMIT`, `txnState=txnIdle`.
```
for _, stmt := range parsedStmts {
		switch stmt.(type) {
		case *parser.BeginTransaction:
			c.txnState = txnRunning
		case *parser.CommitTransaction, *parser.RollbackTransaction:
			c.txnState = txnIdle
		}
	}
```
The `txnState` would be set as `txnError` only if `txnState==txnRunning` and executes statement  error in `doRunStatement()`.
```
c.exitErr = runQueryAndFormatResults(c.conn, os.Stdout, makeQuery(c.concatLines), cliCtx.prettyFmt)
	if c.exitErr != nil {
		fmt.Fprintln(osStderr, c.exitErr)
		if c.errExit {
			return cliStop
		}
		if c.txnState == txnRunning {
			c.txnState = txnError
		}
	}
```
What do you think?

**Comment by knz** [comment]
This is a clever idea, worth a try. There are a couple corner cases that will need careful attention though:
- you need to distinguish 4 txn states: Open, Aborted, RetryWait, None
- SAVEPOINT-related syntax also changes the transaction state (RetryWait)
- you must distinguish errors due to connection close and reopen (this cancel the txn status to None) from processing errors (Abort)

**Comment by yznming** [comment]
@knz sorry that txn states tracker doesn't work. Since:
1. if the client disables the syntax checking, it can not recognize the type of statement. 
2. so many uncertain errors that would not abort transaction need to be excluded. such as:`Un-support error`.
I think we'd better move back to the old way.

**Comment by yznming** [comment]
@knz still have one questions: the  `show` statement is run transactionally, so the returning of  transaction status is always `OPEN`. I think maybe we can export the transaction status from driver layer(`pq` package). any ideas to export the status from `pq` package?
```
// pq/conn.go
const (
	txnStatusIdle                transactionStatus = 'I'
	txnStatusIdleInTransaction   transactionStatus = 'T'
	txnStatusInFailedTransaction transactionStatus = 'E'
)

func (s transactionStatus) String() string {
	switch s {
	case txnStatusIdle:
		return "idle"
	case txnStatusIdleInTransaction:
		return "idle in transaction"
	case txnStatusInFailedTransaction:
		return "in a failed transaction"
	default:
		errorf("unknown transactionStatus %d", s)
	}

	panic("not reached")
}
```

**Comment by knz** [comment]
Yes you are right `SET` is always run transactionally. This is not so easy as I had initially envisioned.

To answer your question, the `pq` package does not currently expose `conn.txnStatus`. We could provide a custom version however this would be insufficient for the issue at hand: we could not use it to distinguish between the states "RetryWait" and "Open" (pg does not know about "RetryWait").

The way forward is really to:
1. add a new Statement type in `sql/parser`
2. add a new parser rule in `sql/parser/sql.y` to generate objects of this new type
3. add a special case for this in Executor's `execStmtsInCurrentTxn()`  to recognize the new type and perform the appropriate logic, without using the planNode infrastructure at all.

Does this make sense to you? If you feel it is too complicated, let me know.

**Comment by yznming** [comment]
@knz, got it. I think I can try to fix it.
