### ISSUE TITLE
time out in TestAmbiguousCommit

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#10299]
Found in:
https://teamcity.cockroachdb.com/viewLog.html?buildId=38189&buildTypeId=Cockroach_UnitTests

`panic: test timed out after 2m0s`

**Comment by jordanlewis** [comment]
There are several other occurrences of this test being flaky - see the [TestAmbiguousCommit test history](https://teamcity.cockroachdb.com/project.html?projectId=Cockroach&tab=testDetails&testNameId=-915042077452365588#analysis).

**Comment by vivekmenezes** [comment]
Another new test that is flaky which again points to a need to change our
process. We need a new script that looks at every PR with new tests and
runs stress on those tests before allowing the PR to merge. Do we have an
issue on this?

**Comment by jordanlewis** [comment]
@tamird is working on this, I believe.
