### ISSUE TITLE
sql: support collecting a statement bundle for a specific gist

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#103018]
**Is your feature request related to a problem? Please describe.**
A particular statement fingerprint often has a few different query plans that are used at execution time. In the DB Console, these are represented by different gists. When debugging an issue, sometimes we have reason to believe that a particular query plan is problematic, so it would be nice to selectively collect a statement bundle for a particular gist. 

We already have the ability to conditionally collect statement bundles for high-latency query executions, but the target gist may not necessarily have higher latency. In that case, it's difficult to get a bundle for a very rare gist.

**Describe the solution you'd like**
Make it possible to collect a statement bundle for a specific gist.

Jira issue: CRDB-27794

**Comment by cucaroach** [comment]
Leaving this with cluster obs team, reach out to SQL Queries if any help is needed.

**Comment by maryliag** [comment]
Work completed
