### ISSUE TITLE
Write a tool that can be used to find the mismatched key values that cause mismatched fingerprints

### ISSUE THREAD

**Issue by rhu713** [cockroachdb/cockroach#103072]
In backup/restore tests we often use `SHOW EXPERIMENTAL_FINGERPRINTS` when comparing backed up and restored data. But in the case where fingerprints are mismatched, it's often difficult to determine exactly which keys or values caused the mismatch, especially for large datasets. Write a tool that can be used to bisect and find the mismatch.

Epic: [CRDB-27758](https://cockroachlabs.atlassian.net/browse/CRDB-27758)

Jira issue: CRDB-27822

**Comment by msbutler** [comment]
closing on https://github.com/cockroachdb/cockroach/pull/104918

To compare keys, the test needs to grab backups of the two states that ought to be equal, like https://github.com/cockroachdb/cockroach/pull/110033
