### ISSUE TITLE
Expand backup nemesis and round trip tests

### ISSUE THREAD

**Issue by rhu713** [cockroachdb/cockroach#103071]
Expand `TestTenantBackupNemeis` and `TestBackupRestoreRandomDataRoundtrips` to include test cases where keys can have large revision histories, and cases where the elastic CPU limiter is actively preempting backup related work.

Epic: [CRDB-27758](https://cockroachlabs.atlassian.net/browse/CRDB-27758)

Jira issue: CRDB-27821

Epic CRDB-31689

**Comment by msbutler** [comment]
Closing as not planned and because the roundtrip roachtests add the coverage the issue is describing
