### ISSUE TITLE
kvserver: Update snapshot strategy for disaggregated ingests

### ISSUE THREAD

**Issue by itsbilal** [cockroachdb/cockroach#103028]
The kvBatchSnapshotStrategy needs to be updated to recognize where the sending/recipient nodes are both using the same shared.Storage, and if so, use the new skip-shared iteration mode in `db.ScanInternal` to produce a list of shared sstable metadatas as well as some flat non-shared sstables that sit on top of them.

On the recipient side, these shared sstable metadata structs can be ingested into Pebble using the new `IngestAndExcise` command (see https://github.com/cockroachdb/pebble/issues/2520 , which this issue has a dependency on).

Jira issue: CRDB-27800

**Comment by itsbilal** [comment]
As mentioned in cockroachdb/pebble#2538, we should call the new `IngestAndExcise` even if there are no shared files, to avoid the need to write a range tombstone.

**Comment by sumeerbhola** [comment]
Do we have a list of all the users of Pebble snapshots and how they will be affected by excise removing things under them? Copying some text from https://github.com/cockroachdb/pebble/issues/2424 where we started listing these and also discussing whether the use of Pebble snapshots was necessary.

> Pebble snapshots will only be valid if we have not excised a keyspan from the LSM, which we will be doing when dropping a CockroachDB range. So the current uses of Pebble snapshots will need to ensure that the CockroachDB range is still present.
> - Sending range snapshots will be cheaper since most of the data is sitting in shared sstables, and does not need to be iterated over, hence using a Pebble snapshot may be unnecessary (more in https://github.com/cockroachdb/pebble/issues/2424#issuecomment-1492395412, 
> - ... mvccGCQueue: does it need a consistent state using a snapshot, or can afford to use multiple iterators when scanning a range. 
> - snapshots related to the TSDB: https://github.com/cockroachdb/cockroach/blob/ee9831d3151b3a559495bc001b9d4b661cf046b1/pkg/kv/kvserver/ts_maintenance_queue.go#L151-L156. That use of a snapshot looks wholly unnecessary. (*ts.DB).MaintainTimeSeries [passes it into (*ts.DB).findTimeSeries](https://github.com/cockroachdb/cockroach/blob/4d987b3f0788c98fa358715b336a1c55e254ee50/pkg/ts/maintenance.go#L57-L60), which [uses it once](https://github.com/cockroachdb/cockroach/blob/a36d88bebd1d26161c3c7327b86af72fca88fc2c/pkg/ts/pruning.go#L67) to create an iterator to find the names of the time series.

**Comment by itsbilal** [comment]
@sumeerbhola Thanks for linking that! Looks like the TS maintenance queue no longer uses a snapshot. The use of a snapshot to send a KV snapshot is likely okay for the purposes of this issue as we are guaranteed that we won't be clearing the replica until that replication is complete.

The only other use of a snapshot I can see is the GC queue. I couldn't find anything else from an audit of the code.
