### ISSUE TITLE
release-23.1: flake in TestAcquireLeaseTimeout

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#103179]
Found here:
https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/10042078?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

```
=== RUN   TestAcquireLeaseTimeout
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/33f576194975d55328ba8cc9ee712e65/logTestAcquireLeaseTimeout1038275390
    test_log_scope.go:79: use -show-logs to present logs inline
    client_lease_test.go:1359: blocked lease request for r64
*
* INFO: slow quiesce. stack traces:
* [...]
```

cc @erikgrinaker for triage

Jira issue: CRDB-27872

**Comment by erikgrinaker** [comment]
Resolved by #103075.
