### ISSUE TITLE
bazel: UnusedLint CI check flaked on 23.1

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#103136]
A [CI build on 23.1](https://teamcity.cockroachdb.com/viewLog.html?buildId=10038906&buildTypeId=Cockroach_BazelEssentialCi) failed due to a UnusedLint flake related downloading some java package. Rerunning CI passed.

Jira issue: CRDB-27848

Epic CRDB-15060

**Comment by rickystewart** [comment]
Not much to do about this at this time -- the logs are gone and Unused Lint doesn't even exist as part of CI any more.
