### ISSUE TITLE
storage: the GC queue processing is very chatty in logs

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#10325]
I had let a cluster to run idle and I just noticed that when the GC kicked in my logs were spammed with the "GC completed" messages *multiple times per second*. I didn't use any verbosity flags.

Indeed in `storage/gc_queue.go:325`: 
```
        queueCtx := gcq.AnnotateCtx(context.TODO())
        log.Infof(queueCtx, "completed with stats %+v", info)
        log.Eventf(ctx, "completed with stats %+v", info)
```

no condition on log.V for log.Infof(). Is this intentional?

**Comment by tschottdorf** [comment]
This should print once per Replica on which `GC` is run, but I added that before you put in our `GCQueue` metrics. With that done, I think it's fine to relax this logging.
