### ISSUE TITLE
backupccl,cloud: review cluster settings for deprecation

### ISSUE THREAD

**Issue by shermanCRL** [cockroachdb/cockroach#103213]
Cluster settings abound! Let’s audit cluster settings related to backup & restore to see if they should still exist.

I think bool settings are a good place to start. Check these searches:
- [Backup & restore](https://github.com/search?q=repo%3Acockroachdb%2Fcockroach+settings.RegisterBoolSetting+path%3Apkg%2Fccl%2Fbackupccl&type=code)
- [Cloud storage](https://github.com/search?q=repo%3Acockroachdb%2Fcockroach+settings.RegisterBoolSetting+path%3Apkg%2Fcloud&type=code)

Rough criteria are:

- Has defaulted to true for a long time, say 2 major versions.
  - Ditto for false!
- We don’t see a reason that a user would or should ever change the setting moving forward.

We do want to keep settings around for new functionality that needs maturing (i.e. feature flags), or known cases of a client needing to do things differently than default.

Let’s call out / debate individual settings as comments.

Jira issue: CRDB-27886

**Comment by msbutler** [comment]
@shermanCRL I wonder if we should use this issue to track instead? https://github.com/cockroachdb/cockroach/issues/87356

**Comment by shermanCRL** [comment]
Oh. Hey. Yup.

Closing as dup.
