### ISSUE TITLE
cli/sql: missing results with multi-statement queries

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#10326]
Compare:
```
root@:26257> SELECT 1; select 2;
+---+                                                                                                                                                                                         | 1 |
+---+
| 1 |
+---+
(1 row)
+---+
| 2 |
+---+
| 2 |
+---+
(1 row)
```
(This is OK, and what we have in tests already)

```
root@:26257> select 1; selecT * from system.users;
+---+
| 1 |
+---+
| 1 |
+---+
(1 row)
root@:26257>  
```

The results from the 2nd select are missing!

I have checked that the two statements are indeed sent to the server (so says Executor verbose logging), that the two result sets are indeed sent back through the wire (so says pgwire verbose logging) but that lib/pq's Query/Next only returns *one* result set to the client.

So I fear the bug is in lib/pq.

**Comment by petermattis** [comment]
The second result set is empty (at least, it's empty in a newly created cluster). Perhaps we don't have a way of indicating that through the `lib/pq` interface.

**Comment by knz** [comment]
Yes it is empty, but if I enter "select * from system.users" on a line of its own, then I do get an empty table printed out. The problem seems to occur when a result set is empty *after* another non-empty one.

**Comment by petermattis** [comment]
@knz Right. My point was that we should be looking at the handling of empty results sets in `cockroachdb/pq` (not `lib/pq`) when multiple results are returned and that this is not a more general problem with multiple results (e.g. `select 1; select * from system.eventlog` works fine).

**Comment by mjibson** [comment]
Go 1.8 has support for this and I have a PR out to add it: https://github.com/lib/pq/pull/532

**Comment by petermattis** [comment]
I recall that the support for multiple results I added to `cockroachdb/pq` was more involved than your PR. Would be good to figure out why. Could just be that you're a better programmer than me, though I recall trying to make the connection recover in case the user did not consume all of the result sets.

**Comment by mjibson** [comment]
I didn't consider what happens if the user doesn't consume all result sets. But I added a test to that PR and it still works correctly. Having a new API in database/sql is probably what makes this easier to do.
