### ISSUE TITLE
kv: monitor memory usage by KV batches and write intents

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#10320]
Pursuant to #8691 we need to extend the monitoring to KV batches and write intents, which are currently unaccounted for. This is needed to ensure in particular that INSERT/UPDATE touching many rows don't blow up the coordinating node's memory.

Jira issue: CRDB-6138

**Comment by cuongdo** [comment]
@knz would you still advocate for fixing this in 1.0?

**Comment by dianasaur323** [comment]
@cuongdo @knz I'm going to assign this! If it's not a blocker for 1.0, we could also stick it into the Q2 2017 milestone, but leaving it to you two to decide.

**Comment by knz** [comment]
cc @andreimatei 
I am not planning to work on this any time soon (Also Andrei helped me understand that the scope of the issue is larger than what the small description would otherwise suggest)

**Comment by knz** [comment]
Issue added to #8879

**Comment by tschottdorf** [comment]
I feel bad kicking this can down the road once more, but realistically this isn't going to happen for 2.1.

**Comment by joshimhoff** [comment]
Is the current state that we don't account for memory usage that happens at KV level? Asking for oncall understanding.

**Comment by knz** [comment]
yes correct

**Comment by jordanlewis** [comment]
The SQL portion of this is done - we have memory monitoring in place for the KV batches that SQL sends and receives. As such I've updated the title of this issue to be about kv.
