### ISSUE TITLE
jobs details refreshing with executing job

### ISSUE THREAD

**Issue by maryliag** [cockroachdb/cockroach#103206]
When a job is still being executed we want to keep refreshing the details endpoint to get the data, but that refresh should be done in the background, without interfering with results already displayed.
Currently when the new refresh starts the pages goes back to a loading state
example: https://www.loom.com/share/1824befa84a04a0891e1163226f0a4eeza

Jira issue: CRDB-27885

**Comment by xinhaoz** [comment]
Shoot, my bad. I introduced this by accident in this PR: https://github.com/cockroachdb/cockroach/commit/9d64c7fc9243b3a631462ba726d43a1d3e6a4b6a#diff-09da33ea6445e45b3297128512a6c0fad08b57b3d2e44396a0265dea5e9e1b62L168.
We need to add the `&& !this.props.jobRequest.data` to the `isLoading` declaration.
