### ISSUE TITLE
sql: panic due to inconsistent descriptor state

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#10322]
https://teamcity.cockroachdb.com/viewLog.html?buildId=38866&tab=buildResultsDiv&buildTypeId=Cockroach_Nightlies_RandomSyntaxTests is a very interesting test failure. Stack trace copied below.

The error appears to be a failed call to `desc.GetTable()`, but the result isn't checked since it is assumed (due to the case switch above it) that everything already has the correct type. I looked into it but couldn't figure out what was going on. I also attempted to reproduce locally but was unable after running RSG for an hour or so.

My current best explanations are:

1. Some transient bit flip error or some other hardware-related thing.
1. A race condition where a descriptor was being renamed or a table dropped and a database added or something in another goroutine.

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
    panic: ALTER INDEX IF EXISTS BIGINT RENAME TO TREAT: runtime error: invalid memory address or nil pointer dereference [recovered]
    panic: ALTER INDEX IF EXISTS BIGINT RENAME TO TREAT: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1b4 pc=0x98be42]

goroutine 22024 [running]:
panic(0x16b8660, 0xc420f2ad00)
    /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc4201c2000)
    /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:185 +0x6e
panic(0x16b8660, 0xc420f2ad00)
    /usr/local/go/src/runtime/panic.go:458 +0x243
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements.func1(0xc424f5d7d5, 0x2c)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:414 +0x149
panic(0x16db680, 0xc420012130)
    /usr/local/go/src/runtime/panic.go:458 +0x243
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*TableDescriptor).MaybeUpgradeFormatVersion(0x0, 0x1784480)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/structured.go:345 +0x22
github.com/cockroachdb/cockroach/pkg/sql.(*planner).getDescriptor(0xc42685b2f8, 0x2325920, 0xc42159c280, 0x2337780, 0xc424a87440, 0x0, 0x6, 0x74)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/descriptor.go:211 +0x2b3
github.com/cockroachdb/cockroach/pkg/sql.(*planner).getTableOrViewDesc(0xc42685b2f8, 0xc423399180, 0x8b1845, 0xc4216bb6a0, 0x6)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/table.go:146 +0x1e0
github.com/cockroachdb/cockroach/pkg/sql.(*planner).getTableDesc(0xc42685b2f8, 0xc423399180, 0x942260, 0x2319b60, 0x2)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/table.go:158 +0x39
github.com/cockroachdb/cockroach/pkg/sql.(*planner).mustGetTableDesc(0xc42685b2f8, 0xc423399180, 0xc4216bb6a0, 0x6, 0x2)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/table.go:197 +0x39
github.com/cockroachdb/cockroach/pkg/sql.(*planner).findTableContainingIndex(0xc42685b2f8, 0xc425bcb045, 0x5, 0xc424f5d7eb, 0x6, 0x0, 0x0, 0x0)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/table.go:556 +0x13d
github.com/cockroachdb/cockroach/pkg/sql.(*planner).expandIndexName(0xc42685b2f8, 0xc422bf3860, 0x5d1010, 0x27, 0x22a3ae16)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/table.go:585 +0xaa
github.com/cockroachdb/cockroach/pkg/sql.(*planner).RenameIndex(0xc42685b2f8, 0xc42208fa60, 0xc4255a0f00, 0xc423e4c258, 0xf07282, 0xc4208ec100)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/rename.go:254 +0x53
github.com/cockroachdb/cockroach/pkg/sql.(*planner).newPlan(0xc42685b2f8, 0x7f7d1fd13bf8, 0xc42208fa60, 0x0, 0x0, 0x0, 0xc423957301, 0x48, 0x0, 0xecfa8b944, ...)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:287 +0x1f3
github.com/cockroachdb/cockroach/pkg/sql.(*planner).makePlan(0xc42685b2f8, 0x7f7d1fd13bf8, 0xc42208fa60, 0x845401, 0xc42667eaa0, 0xc4ffffffff, 0x0, 0x2)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:219 +0x70
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmt(0xc4202b7a40, 0x7f7d1fd13bf8, 0xc42208fa60, 0xc42685b2f8, 0xc423e4c501, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1151 +0xc2
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmtInOpenTxn(0xc4202b7a40, 0x7f7d1fd13bf8, 0xc42208fa60, 0xc42685b2f8, 0x101, 0xc42685b268, 0x0, 0x0, 0x0, 0x0, ...)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1042 +0x2c0
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmtsInCurrentTxn(0xc4202b7a40, 0xc421925a80, 0x1, 0x1, 0xc42685b2f8, 0xc42685b268, 0x101, 0x6, 0xc423e4cf58, 0x60ca4a, ...)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:789 +0x34f
github.com/cockroachdb/cockroach/pkg/sql.runTxnAttempt(0xc4202b7a40, 0xc42685b2f8, 0x1, 0xc42685b268, 0xc421925b10, 0xc421925a80, 0x1, 0x1, 0x0, 0x0, ...)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:714 +0xeb
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execRequest.func2(0xc424cf34a0, 0xc421925b10, 0x4000000000000000, 0x0)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:576 +0x22f
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).Exec(0xc424cf34a0, 0xc423b40101, 0xc4200191c0, 0xc423b4f0e0, 0x0, 0x0)
    /go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:518 +0x215
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execRequest(0xc4202b7a40, 0xc42685b200, 0xc424f5d7d5, 0x2c, 0x0, 0x0, 0x0, 0x0, 0xc423e4d700)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:590 +0x572
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements(0xc4202b7a40, 0xc42685b200, 0xc424f5d7d5, 0x2c, 0x0, 0x0, 0x0, 0x0, 0xc424f5d700)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:420 +0x11f
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).executeStatements(0xc420a88780, 0x7f7d1fde92c0, 0xc4256b7050, 0xc424f5d7d5, 0x2c, 0x0, 0x0, 0x0, 0x0, 0xaca801, ...)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:654 +0x94
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).handleSimpleQuery(0xc420a88780, 0x7f7d1fde92c0, 0xc4256b7050, 0xc420a887a8, 0x31, 0x0)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:328 +0xb3
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve(0xc420a88780, 0x7f7d1fde92c0, 0xc4256b7050, 0xc42667eac0, 0x0, 0x0)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:280 +0x820
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn(0xc42019bb00, 0x7f7d1fde92c0, 0xc4256b7050, 0x2336620, 0xc4241ad880, 0x0, 0x0)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:245 +0x63e
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func8.1(0x2336680, 0xc425a44790)
    /go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:488 +0x106
github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1(0xc4201c2000, 0xc4201701b8, 0x2336680, 0xc425a44790, 0xc420554020)
    /go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:136 +0x95
created by github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith
    /go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:138 +0x277
```

**Comment by knz** [comment]
Prior to that the log is littered with errors accessing SystemConfigSpan:
```
E161031 04:01:42.657537 96 storage/replica.go:3643  [n1,s1,r1/1:/{Min-Table/11}] could not load SystemConfig span: must retry later due to intent on SystemConfigSpan
```

**Comment by knz** [comment]
cc @paperstreet and @petermattis as you have been the latest people looking at this particular code (sql.getDescriptor).

**Comment by knz** [comment]
1) Could it be as simple as checking for `table == nil` *before* calling `table.MaybeUpgradeFormatVersion()`?
2) which scenario makes it possible for the table descriptor to be absent (table == nil) although the descriptor key is present?

**Comment by petermattis** [comment]
> Some transient bit flip error or some other hardware-related thing.

Very doubtful.

> A race condition where a descriptor was being renamed or a table dropped and a database added or something in another goroutine.

Does the RSG test use concurrency? It would be helpful if the RSG test printed out the statements it was executing before executing them. Perhaps it is and I'm just not seeing it on the teamcity link.

**Comment by vivekmenezes** [comment]
The code in getDescriptor is very odd. It is checking for the nil descriptor in both the table and database case. In the table case it runs `MaybeUpgradeFormatVersion` before checking if it's nil. This code is definitely broken. It should either not check that the descriptors are nil, or check them before using them.

**Comment by paperstreet** [comment]
Yeah, seems like the MaybeUpgradeFormatVersion call is a bit too early and should be after the nil check. Almost certainly my fault

Down in (*KeyValue).ValueProto, it has `if kv.Value == nil { msg.Reset() }`, so I think it means the descriptor key was _not_ present

**Comment by knz** [comment]
dan I am assigning to you since you claimed expertise over this code :)
Feel free to change the assignment though.

**Comment by mjibson** [comment]
RSG runs many goroutines in parallel. Printing statements before it executes them hasn't been done because it could result in tens of thousands of statements since the tests are run for 10 minutes each. It could be done but this is only the second bug of this kind (a race) that RSG has found. Most of the time printing just the exact statement is enough.

**Comment by knz** [comment]
Repro in https://teamcity.cockroachdb.com/viewLog.html?buildId=47548&tab=buildResultsDiv&buildTypeId=Cockroach_Nightlies_RandomSyntaxTests

**Comment by knz** [comment]
I made an attempt at fixing this in #10674.

However I now have troubles coming up with a reliable test for this. In which scenario would the problem come? I *think* the issue occurs when the table is replaced with something that is not a table concurrently with the offending getDescriptor() calls runs. What test scenario could reliably reproduce this?

**Comment by mjibson** [comment]
Since RSG has now found this twice, I think we could modify RSG to print all statements it is executing into a log, and then let it run for a few hours until it finds this bug. This may produce a small set of statements that we can run in a stress test that could find this bug in a quick amount of time.

**Comment by knz** [comment]
@mjibson @vivekmenezes my theory about this is that the table is substituted by an index of the same name concurrently with a query that extracts the descriptor (i.e. DROP TABLE; CREATE INDEX). This is because the offending code first does getAllDescriptors() then later getTable(); and getAllDescriptors() AFAIK is not cached, so there's a window in between for a race.

If that theory is true, a simple log of all the operations performed will not be sufficient to reproduce the issue, unless we can produce one log per RSG thread with timestamps.

**Comment by knz** [comment]
Another repro: https://teamcity.cockroachdb.com/viewLog.html?buildId=47549&buildTypeId=Cockroach_Nightlies_AllNightlyTests

**Comment by mjibson** [comment]
The log can contain timestamps and (manually-assigned) goroutine IDs so these can be tracked, yes. If you think this is worth doing I'll work on it.

**Comment by vivekmenezes** [comment]
The descriptor being inspected here can only have a database or a table within it. Here we have a descriptor with type table with a nil value, so somewhere in our code we are writing a nil value to the descriptor. I think this can be fixed via inspecting the code.

**Comment by knz** [comment]
Who are the people with the most knowledge of this area? (area = descriptor handling, descriptor protos, leases) 
I could have a look but I have many questions.

**Comment by vivekmenezes** [comment]
I think what we need to do here is change WrapDescriptor to check if it is
wrapping a nil value and panic when it does. that way we know the code path
that is writing the nil value.

**Comment by paperstreet** [comment]
I'm not sure it's writing a nil descriptor. I've been assuming it's being called with an ID and expecting that ID to be a table, but it's actually a database. Which likely points to a race condition somewhere

**Comment by mjibson** [comment]
Here's a trace of this happening for a `DROP INDEX` with many of the recent completed queries. There are also some other in-flight queries not listed there.

https://gist.github.com/mjibson/36de86eccd61d1feecdbd3eed217cd11

**Comment by knz** [comment]
I have removed the proximal cause of panics via #10674 but since the root cause is not yet identified I am leaving this issue open.

**Comment by mjibson** [comment]
I did some further tests and found that when this occurs it is because `desc` is `nil`, not just the other type.

**Comment by vivekmenezes** [comment]
can we experiment with adding a panic when we write a nil descriptor?

**Comment by vivekmenezes** [comment]
Are we still able to reproduce this?

**Comment by mjibson** [comment]
Unknown. We would have to revert #10674 and see if it pops up again. I'm +1 on doing that if someone is interested in looking deeper.

**Comment by vivekmenezes** [comment]
I'm assuming you are also saying that you can't reproduce this issue? Not
the panic, but the nil reference.

**Comment by mjibson** [comment]
It's unknown if the nil reference is still being reproduce or not. We could add in a special check in the RSG tests that look for that error string and fail on it. That's probably the best way to see if the underlying cause is still around.

**Comment by vivekmenezes** [comment]
+1 on adding something that will allow us to reproduce this. Thanks!

**Comment by dianasaur323** [comment]
@knz Given you provided a fix on this earlier, let's look into testing for this specific error. I'm assigning you, but please feel free to re-assign. I think it would be good to put a test in place here.

**Comment by mjibson** [comment]
This is too old to care about anymore.
