### ISSUE TITLE
cli: Remove special handling of `cockroach user set --password=-`

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#10329]
#10175 brought to my attention that if the user's password is set to `-` via the command line, we read the password from stdin instead. We shouldn't be doing this - the password should be completely opaque. If we want to support this, it should be via a separate flag like `--password-from-file` which could take either a filename or `-`.

**Comment by a6802739** [comment]
@bdarnell , I could fix it after #10175 was merged.

**Comment by irfansharif** [comment]
@asubiotto this can be closed now.
