### ISSUE TITLE
Only admins can run Alter Range...Relocate

### ISSUE THREAD

**Issue by Arivijay** [cockroachdb/cockroach#103345]
**Describe the problem**

Only admins can run Alter Range...Relocate. 
Reference https://www.cockroachlabs.com/docs/stable/alter-range.html#required-privileges 
However, customer requests that AppDBAs who aren't admins should have the ability to do this.
It would be nice if ZONECONFIG or another system privilege would enable this for non-admins.

**Environment:**
 - CockroachDB version 22.2.7

Jira issue: CRDB-27956

**Comment by rafiss** [comment]
this was fixed by https://github.com/cockroachdb/cockroach/pull/110084 and has been backported to 23.1. if there is still an issue, please reopen.

if a finer grained privilege is needed, then I think the KV team should be involved.
