### ISSUE TITLE
schemachanger: Support CREATE DATABASE

### ISSUE THREAD

**Issue by Xiang-Gu** [cockroachdb/cockroach#103324]
We should support `CREATE DATABASE` as much as we can in the declarative schema changer.

Jira issue: CRDB-27948

Epic CRDB-25313

**Comment by rafiss** [comment]
re-opening since the PR is being reverted due to these flakes:
- https://github.com/cockroachdb/cockroach/issues/116840
- https://github.com/cockroachdb/cockroach/issues/116837
- https://github.com/cockroachdb/cockroach/issues/116829
