### ISSUE TITLE
export: parquet causes node to OOM

### ISSUE THREAD

**Issue by jayshrivastava** [cockroachdb/cockroach#103317]
It looks like we are not performing sufficient memory accounting when using `EXPORT INTO` with parquet.

See 
- https://github.com/cockroachlabs/support/issues/2303
- https://github.com/cockroachlabs/support/issues/2247

Jira issue: CRDB-27942

**Comment by jayshrivastava** [comment]
There are two issues to tackle: 
1. Update EXPORT to use the new parquet writer in `util/parquet`
2. Ensure memory is being accounted before by `EXPORT` 
3. Once (1) is done and has been baking in the main branch for a while, we can completely clean up the old parquet code and remove the old dependencies from this repo.

**Comment by jayshrivastava** [comment]
Deferring the last step to these sub issues: 
- https://github.com/cockroachdb/cockroach/issues/104278
- https://github.com/cockroachdb/cockroach/issues/104279

**Comment by amruss** [comment]
@jayshrivastava do you think the lack of memory accounting is a severe issue? Should we deal with this this release?

**Comment by jayshrivastava** [comment]
@amruss I think it's worth fixing this release, at least for EXPORT INTO PARQUET. The change should be similar to https://github.com/cockroachdb/cockroach/pull/63192, which is not a huge change.

**Comment by jayshrivastava** [comment]
Closing and removing the backport tags for these reasons:
- EXPORT will be deprecated in favor of changefeeds or limited to small sizes https://github.com/cockroachdb/cockroach/issues/105297 
- The change in https://github.com/cockroachdb/cockroach/pull/105064, which will be rolled out in 23.2 depends on the new, memory-efficient parquet library. We are not confident in backporting the library because the change is very big https://github.com/cockroachdb/cockroach/pull/105287.
