### ISSUE TITLE
roachtest: acceptance/mixed version flaked on master

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#103452]
See CI flake [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=10114577&problemId=11989). Error that bubbled up:
```
(mixedversion.go:399).Run: mixed-version test failure while running step 19 (run "run backup"): pq: relation "table2" (184): PARTITION table2_part0: unimplemented: unable to encode JSON as a table key

```

Jira issue: CRDB-28007

**Comment by renatolabs** [comment]
It seems to me that the schemachange workload is generating schemas that should not be valid in mixed-version (specifically, that partition involving a JSONB column).

@fqazi could you take a look?

Also, maybe a noob question, but why is the backup step failing, and not the corresponding `CREATE TABLE`?

**Comment by fqazi** [comment]
@renatolabs Let me a dig a bit

**Comment by fqazi** [comment]
I think https://github.com/cockroachdb/cockroach/pull/101932 will also a bit beneficial here, but I don't think it will eliminate this
