### ISSUE TITLE
dbconsole: database page fails to load for non-admin users

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#103443]
I created a non-admin user and granted it VIEWACTIVITY but not the admin role.

When navigating to the db list I see the following:
![image](https://github.com/cockroachdb/cockroach/assets/642886/f17926c8-670b-4624-8347-c1249d01ab57)
![image](https://github.com/cockroachdb/cockroach/assets/642886/f2a1ae18-ca29-4445-96b8-9e67805a3e3a)

**Expected behavior**

A non-privileged user should be able to see the db list with just the DBs they have access to.

Jira issue: CRDB-28004

**Comment by knz** [comment]
This is v23.1 by the way.

cc @kevin-v-ngo @j82w for triage.

**Comment by knz** [comment]
Note: this used to work for v22.1. So marking as regression.

**Comment by maryliag** [comment]
another error also being displayed (Serverless):
`Error Loading databases: Error: Error while retrieving database details information: only users with the ZONECONFIG privilege or the admin role can read crdb_internal.ranges_no_leases`

**Comment by knz** [comment]
It's unclear why the serverless error only mentions ZONECONFIG, whereas in the code it also mentions VIEWACTIVITY.

Maybe this test was using an older version of crdb under the hood?

**Comment by THardy98** [comment]
Below are PRs that allow users with restricted permissions to still view the databases pages:

Databases Page Improvement: https://github.com/cockroachdb/cockroach/pull/109245
Database Detail Page Improvement: https://github.com/cockroachdb/cockroach/pull/109432
Table Detail Page Improvement (database table page - specifically relevant to this issue): https://github.com/cockroachdb/cockroach/pull/109521

**Comment by THardy98** [comment]
Closing the issue per the PRs listed above
