### ISSUE TITLE
Mark webhook and pub/sub performance cluster settings as public

### ISSUE THREAD

**Issue by kathancox** [cockroachdb/cockroach#103470]
**Describe the problem**

The two new cluster settings for webhook and Pub/Sub performance improvements are both marked as `public` `f`.
`changefeed.new_webhook_sink_enabled`
`changefeed.new_pubsub_sink_enabled`

Can we mark those as `public` `t` given we want users to enable these for the performance improvements? This will also pull the settings through to the cluster settings doc page. 

Note: these will be documented within the CDC docs too, but users may look for the settings on within the main cluster settings list.

Jira issue: CRDB-28019

Epic CRDB-13237

**Comment by amruss** [comment]
We're removing these settings in 23.2 so closing the issue
