### ISSUE TITLE
sql: investigate using []byte instead of string for the parser

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#10345]
This would be useful for the client when we check for isEndOfStatement and in the upcoming backup code to prevent lots of byte -> string copies.

**Comment by knz** [comment]
@justinj just made the observation to me that the slicing and other string manipulations we do in the parser should not cause copies in the common case (deriving a new `string` from a sub-string of another just creates another slice header, does not copy the data).

@mjibson do you recall more specifically what you had in mind?

**Comment by mjibson** [comment]
This issue is old enough we should just close it. There are much more interesting and useful performance problems to look at.
