### ISSUE TITLE
Misalignment of action button and different treatments for the select dropdowns on SQL activity page 

### ISSUE THREAD

**Issue by dongniwang** [cockroachdb/cockroach#103473]
- The `Apply` button in the search criteria section is misaligned with the rest of the row. 
- Time Range selector box has a lighter outline than Top and By selectors. Heights for these selector boxes are also different, seems like time range selector is slightly larger visually. 

See screenshot below. This screenshot is captured this morning using chrome. 

![image (3)](https://github.com/cockroachdb/cockroach/assets/24943812/a8e82a10-084a-40d3-9356-54613f69560f)

Jira issue: CRDB-28021

**Comment by maryliag** [comment]
Fixed on https://github.com/cockroachdb/cockroach/pull/102650
