### ISSUE TITLE
sql: Give AmbiguousResultError a PG error code

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#10354]
Clients need to be able to recognize the AmbiguousResultError, but currently the only way to do that is with a string comparison on the message (which changed in #10279. The old message was documented in last week's release notes). We should give it a proper error code for clients to use. Looks like [postgres](https://www.postgresql.org/docs/9.6/static/errcodes-appendix.html) defines a suitable one already: `08007 transaction_resolution_unknown`.

**Comment by andreimatei** [comment]
If we do this, should we also return this code for other "internal errors" that happen when running a COMMIT/RELEASE or an implicit sql transaction?
And another thing I wonder is whether we'd mention this error code in our transactions docs, given that the client driver can also return ambiguous errors that are outside our control.

**Comment by bdarnell** [comment]
Yes, the client driver can return ambiguous errors outside our control, but those will generally come in the form of a `ConnectionError` exception (or whatever the language's error-handling idiom requires). Our current ambiguous result error looks exactly like all our unambiguous failures (except for the message text), so we need to give it a different error code.

As for other errors, where an applicable error code exists, it's nice to use it, but it's only necessary to the extent that we expect client code to handle the error differently. We can expect client code to (sometimes) retry on AmbiguousResultError, so it needs to be distinguishable (or we could just close the connection which would turn AmbiguousResultError into the ConnectionError that the client must already be able to handle, but that's pretty ugly). Most other errors are fine being lumped in to a generic InternalError from the application's perspective.

**Comment by andreimatei** [comment]
But my point is that, if we indeed expect applications to handle the code for `AmbiguousResultError`, then we should also use the code for other *ambiguous* errors that happen on `COMMIT`. Not sure how to interpret your message on whether you agree with this or not :)

**Comment by bdarnell** [comment]
Yes, any ambiguous error should get the same error code. What else is ambiguous? (are you referring to RPC errors, etc?)

**Comment by andreimatei** [comment]
Yup, I'm thinking of RPC errors. I thought we return `AmbiguousResultError` in very specific circumstances, but now I'm looking at the code and it seems that the `DistSender` returns it precisely for RPC errors. So I guess we're good, never mind me.

**Comment by dianasaur323** [comment]
@bdarnell I'm going to assign this to you for now - I'm not sure if this is still an issue given the age of it, but it does seem like something we should clean up before 1.0?
