### ISSUE TITLE
Error when viewing DB in UI

### ISSUE THREAD

**Issue by jrote1** [cockroachdb/cockroach#103501]
I'm getting an error when trying to view the database page, i'm not sure what's causing this but i'm happy to provide any log files that are required. All other databases can be viewed in the UI, it's just this one with the error

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**

I'm not sure what caused this error I just created a database and imported a postgres backup

**Additional data / screenshots**
<img width="1747" alt="image" src="https://github.com/cockroachdb/cockroach/assets/4202486/37540669-6666-4b29-b690-54e2db36c370">
<img width="879" alt="image" src="https://github.com/cockroachdb/cockroach/assets/4202486/bafee313-1754-4818-85bc-a8f8f7bfcc85">

All nodes are live with no errors
<img width="1333" alt="image" src="https://github.com/cockroachdb/cockroach/assets/4202486/fdb29091-f56e-4aa5-8938-701f0138772f">

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version: 23.1.1
 - Server OS: Linux/Docker
 - Client app: UI

**Additional context**
Unable to view the DB page

Jira issue: CRDB-28035

**Comment by jrote1** [comment]
I think this is related to #103443

**Comment by florence-crl** [comment]
cc @kevin-v-ngo for triage
I also think this is related to #103443 
In 23.1.1 with a single-node secure local cluster with a non-admin user without VIEWACTIVITY privilege, I also get the error:
```
This page had an unexpected error while loading databases.
 Reload this page
```

From the Console:
```
Failed to load resource: the server responded with a status of 403 (Forbidden)
bundle.js:1895 Error Loading databases: Error: Error while retrieving database details information:  only users with MODIFYCLUSTERSETTING, MODIFYSQLCLUSTERSETTING or VIEWCLUSTERSETTING system privileges are allowed to read crdb_internal.cluster_settings
a @ bundle.js:1895
:8080/_status/nodes_ui:1     Failed to load resource: the server responded with a status of 401 (Unauthorized)
:8080/api/v2/sql/:1     Failed to load resource: the server responded with a status of 401 (Unauthorized)
shared.js:77 Uncaught Error: Attempting to use a disconnected port object
    at a.post (shared.js:77:1110937)
    at e.post (shared.js:77:86484)
    at Object.getTabInfo (shared.js:77:1078778)
    at s.getLogoUrls (shared.js:77:1117878)
    at Nt.PageMonitor.H (shared.js:77:1239941)
    at b (shared.js:77:24341)
    at Nt.PageMonitor.trigger (shared.js:77:23693)
    at Nt.PageMonitor.scan (shared.js:77:1233628)
    at Object.onChange (shared.js:77:1232061)
    at u (shared.js:77:112987)
2bundle.js:1895 Error Loading databases: RequestError: Unauthorized
```

This is a regression, because in 22.2.9, I get the info message:
```
RequestError: this operation requires the VIEWACTIVITY system privilege [Learn more](https://www.cockroachlabs.com/docs/stable/ui-overview.html#db-console-access)
```

**Comment by THardy98** [comment]
Are you able to load the page successfully as admin/root user or a user with `VIEWACTIVITY` privilege?

My suspicion is that this isn't related to https://github.com/cockroachdb/cockroach/issues/103443 but would like to see if that is the case.

**Comment by florence-crl** [comment]
ok, I gave a non-admin user the following privilege:
```
grant SYSTEM VIEWACTIVITY to max;
```
In 23.1.1

<img width="969" alt="Screenshot 2023-05-23 at 9 21 22 AM" src="https://github.com/cockroachdb/cockroach/assets/58752716/627f4567-57a6-4c30-a39f-2d5b8fd34869">

From console:
```
5bundle.js:1895 Error Loading databases: Error: Error while retrieving database details information:  crdb_internal.get_database_id()
a @ bundle.js:1895
bundle.js:1895 Error Loading databases: Error: Error while retrieving database details information:  only users with MODIFYCLUSTERSETTING, MODIFYSQLCLUSTERSETTING or VIEWCLUSTERSETTING system privileges are allowed to read crdb_internal.cluster_settings
a @ bundle.js:1895
499Failed to decode downloaded font: <URL>
499OTS parsing error: invalid sfntVersion: -2147375342
bundle.js:1895 Error Loading databases: Error: Error while retrieving database details information:  crdb_internal.get_database_id()
a @ bundle.js:1895
:8080/_status/nodes_ui:1     Failed to load resource: the server responded with a status of 401 (Unauthorized)
2bundle.js:1895 Error Loading databases: Error: Error while retrieving database details information:  crdb_internal.get_database_id()
```
<img width="675" alt="Screenshot 2023-05-23 at 9 17 50 AM" src="https://github.com/cockroachdb/cockroach/assets/58752716/7812abdb-0cda-436f-9747-2b0d9633a691">

From console:
```
Failed to load resource: the server responded with a status of 401 (Unauthorized)
:8080/_admin/v1/settings?unredacted_values=true:1     Failed to load resource: the server responded with a status of 403 (Forbidden)
5bundle.js:1895 Error Loading databases: Error: Error while retrieving database details information:  crdb_internal.get_database_id()
a @ bundle.js:1895
bundle.js:1895 Error Loading databases: Error: Error while retrieving database details information:  only users with MODIFYCLUSTERSETTING, MODIFYSQLCLUSTERSETTING or VIEWCLUSTERSETTING system privileges are allowed to read crdb_internal.cluster_settings
```

In 22.2.9

<img width="763" alt="Screenshot 2023-05-23 at 9 24 07 AM" src="https://github.com/cockroachdb/cockroach/assets/58752716/9e955d3f-6ae5-4fde-8c4e-60647316f07c">

Snippet from console:
```
bundle.js:1895 Error Loading databases: Error: Error while retrieving database details information:  crdb_internal.get_database_id()
a @ bundle.js:1895
:8080/_status/nodes_ui:1     Failed to load resource: the server responded with a status of 401 (Unauthorized)
2bundle.js:1895 Error Loading databases: Error: Error while retrieving database details information:  crdb_internal.get_database_id()

GET https://localhost:8081/_admin/v1/settings?unredacted_values=true 403 (Forbidden)
kn @ bundle.js:27177
wn @ bundle.js:27177
(anonymous) @ bundle.js:27182
(anonymous) @ bundle.js:27324
(anonymous) @ bundle.js:27188
V @ bundle.js:15458
(anonymous) @ bundle.js:27325
(anonymous) @ bundle.js:16850
(anonymous) @ bundle.js:27324
dispatch @ bundle.js:15458
(anonymous) @ bundle.js:27182
bundle.js:27177     GET https://localhost:8081/_admin/v1/settings?unredacted_values=true 403 (Forbidden)
```

**Comment by jrote1** [comment]
@THardy98  i'm logged in as an admin and am seeing the following error in the console
<img width="915" alt="image" src="https://github.com/cockroachdb/cockroach/assets/4202486/acd1756d-6e48-4c0a-ac75-ba6e1b725158">
with the following error observed in the sql request
```
{
   "code":"XXUUU",
   "message":"executing stmt 7: run-query-via-api: error requesting iterating nodes for span stats from node 1 (NODE_STATUS_LIVE): grpc: invalid key-range specified (start \u003e end) [code 2/Unknown]",
   "severity":"ERROR",
   "source":{
      "file":"status.go",
      "line":2886,
      "function":"func1"
   }
}
```
Also i'm only getting this error for a specific DB the rest are working okay, if there's any over information I can provide please just let me know
<img width="1570" alt="image" src="https://github.com/cockroachdb/cockroach/assets/4202486/e769bef0-b783-4785-9581-c20003b51c06">

**Comment by jrote1** [comment]
It looks like this is the offending statement as it's statement 7 in the list, but i'll confirm by running it when I get back later
```
SELECT
  sum(range_count) as range_count,
  sum(approximate_disk_bytes) as approximate_disk_bytes,
  sum(live_bytes) as live_bytes,
  sum(total_bytes) as total_bytes
FROM crdb_internal.tenant_span_stats((SELECT crdb_internal.get_database_id('nextcloud')))
```

**Comment by THardy98** [comment]
@florence-crl my mistake, non-admin users need at least both `VIEWACTIVITY` and `VIEWCLUSTERSETTING` privileges to view the databases pages.

@jrote1 Yes this is what I was thinking was causing the problem, this is not a privilege issue.

@jbowens this looks similar to the key-range ordering issue we encountered before. Key ordering issues would occur when we [tried to get disk size](https://github.com/cockroachdb/cockroach/blob/84dbb3e60346cb69f991100e88297a9b355175e5/pkg/server/span_stats_server.go#L220), though it could also be occuring when we [try to get mvcc stats](https://github.com/cockroachdb/cockroach/blob/84dbb3e60346cb69f991100e88297a9b355175e5/pkg/server/span_stats_server.go#L183).

**Comment by jbowens** [comment]
@THardy98 the bug fix was only backported to the release-23.1 branch and not release.23.1.0, so it won’t be fixed until 23.1.2

**Comment by jrote1** [comment]
@jbowens  @THardy98  does this mean this is expected to be fixed in the next release? If so do you have a release date and i'm happy to respond if the issue is fixed :)

**Comment by jrote1** [comment]
@THardy98 i've updated to the latest version and the issue is fixed. Thanks for your help
