### ISSUE TITLE
TestTenantZip: erase non-deterministic goroutine dump outputs from test assertions

### ISSUE THREAD

**Issue by abarganier** [cockroachdb/cockroach#103517]
**Describe the problem**

In our debug.zip tests, we make assertions against the debug zip output. To avoid failing each time there's expected variance in the output (e.g. # of profiles collected), we use a [function to erase the non-deterministic bits of the output](https://github.com/cockroachdb/cockroach/blob/cc29fe03d437325fc7f0865e5c258d10c1407c1b/pkg/cli/zip_test.go#L330) to avoid frequent failures with these tests.

It seems that we're missing a piece, though. Goroutine dumps are not handled in this function, meaning we sometimes see failures such as:
```
    zip_tenant_test.go:66:
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/6731/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/cli/cli_test_/cli_test.runfiles/com_github_cockroachdb_cockroach/pkg/cli/testdata/zip/testzip_tenant:1:
        output didn't match expected:
        @@ -135,12 +135,17 @@
         [node 1] requesting stacks... received response... writing binary output: debug/nodes/1/stacks.txt... done
         [node 1] requesting stacks with labels... received response... writing binary output: debug/nodes/1/stacks_with_labels.txt... done
         [node 1] requesting heap profile... received response... writing binary output: debug/nodes/1/heap.pprof... done
         [node 1] requesting heap file list... received response... done
         [node ?] ? heap profiles found
        +[node 1] retrieving goroutine_dump.2023-05-12T20_26_14.809.double_since_last_dump.000001044.txt.gz... received response... done
         [node 1] requesting goroutine dump list... received response... done
        -[node 1] 0 goroutine dumps found
        +[node 1] 3 goroutine dumps found
        +[node 1] retrieving goroutine_dump.2023-05-12T20_26_14.809.double_since_last_dump.000001044.txt.gz... received response... done
        +[node 1] writing dump... writing binary output: debug/nodes/1/goroutines/goroutine_dump.2023-05-12T20_26_14.809.double_since_last_dump.000001044.txt.gz... done
        +[node 1] writing dump... writing binary output: debug/nodes/1/goroutines/memprof.2023-05-12T20_26_14.839.72774600.pprof... done
        +[node 1] writing dump... writing binary output: debug/nodes/1/goroutines/memstats.2023-05-12T20_26_14.861.233189376.txt... done
         [node 1] requesting log file ...
         [node 1] 0 log file ...
         [node 1] requesting ranges... received response...
         [node 1] requesting ranges: last request failed: rpc error: ...
         [node 1] requesting ranges: creating error output: debug/nodes/1/ranges.err.txt... done
```

We should add a clause to the existing function to target the followin types of lines in the output:

1. `[node ?] N goroutine dumps found`
2. `[node ?] retrieving goroutine_dump.???.txt.gz... received response... done`
3. `[node ?] writing dump... writing binary output: ???... done`

**To Reproduce**

Run the test enough times, and eventually you will see these failures. It is dependent on whether the goroutine dumper throughout the lifetime of the test server was triggered or not (on many runs, no goroutine dumps are generated, so there's no failures).

Jira issue: CRDB-28051

**Comment by ericharmeling** [comment]
I believe this is fixed by the following two commits:

- https://github.com/cockroachdb/cockroach/commit/2ee4e49f8ace367b76f2bac375ecd5a00ddcaa05
- https://github.com/cockroachdb/cockroach/commit/f9ebb048c8666fec4cf15a6c9978fd74877682bb
