### ISSUE TITLE
Create a roachtest for backup with revision history

### ISSUE THREAD

**Issue by rhu713** [cockroachdb/cockroach#103509]
Create a roachtest for backup with revision history. This test should backup and restore under a workload and compare fingerprints of the original and restored data. We should try to hit the following items in the test:
- Extreme revisions-per-key roachtest
- Metamorphic on pagination
- Metamorphic on elastic CPU
- Maybe have a custom rate limiter

Epic [#27758](https://cockroachlabs.atlassian.net/browse/CRDB-27758)

Jira issue: CRDB-28045

Epic CRDB-31689

**Comment by dt** [comment]
holding off on this as unplanned until we decide if we're changing revision history
