### ISSUE TITLE
Links on Used Indexes column on Statement Fingerprint Details, Explain Plan tab are broken

### ISSUE THREAD

**Issue by florence-crl** [cockroachdb/cockroach#103595]
**Describe the problem**

[PR 92463](https://github.com/cockroachdb/cockroach/pull/92463) added the Used Indexes column to the Statement Fingerprint Details page with links to the table or index details pages. However, the link to the table details page gives an error and the link to the index details page does not give data.

**To Reproduce**

For example,
"Good" path:
If you go to the index rides.rides_pkey via Databases > Tables > Table: "public"."rides" > Index: rides_pkey, you go to the following "good" url which gives data: 
http://localhost:8080/#/database/movr/table/%22public%22.%22rides%22/index/rides_pkey

"Bad" path:
While if you click on the index from the Statement fingerprint details page, Explain Plan tab, from the Used Indexes column, you go to the following "bad" url which gives no data:
http://localhost:8080/#/database/[%22movr%22]/table/rides/index/rides_pkey
The bread crumb path shows: Databases > Tables > Table:rides > Index: rides_pkey.

Also if you click on the table, you go the following "bad" url which gives an error:
http://localhost:8080/#/database/[%22movr%22]/table/rides
`This page had an unexpected error while loading databases. Reload this page`

**Expected behavior**
From the Used Indexes column, the links to the table and index details pages gives same data as going from the Databases link on the left nav menu.

**Environment:**
 - CockroachDB version: 23.1.1
 - Server OS: Mac
 - Client app: DB Console

Jira issue: CRDB-28092

**Comment by florence-crl** [comment]
In 23.1.4, from the Used Indexes column, the links to the table and index details pages gives same data as going from the Databases link on the left nav menu. For example, 

The links from the Used Indexes column look like:
http://localhost:8080/#/database/movr/table/user_promo_codes
http://localhost:8080/#/database/movr/table/user_promo_codes/index/user_promo_codes_pkey

while the the links from the Databases link on the left nav menu look like:
http://localhost:8080/#/database/movr/table/%22public%22.%22user_promo_codes%22
http://localhost:8080/#/database/movr/table/%22public%22.%22user_promo_codes%22/index/user_promo_codes_pkey

Closing this issue.

**Comment by florence-crl** [comment]
In 23.1.4, the issue has re-appeared with links having `["<database name>"]` causing page errors.

**Comment by xinhaoz** [comment]
This was fixed by https://github.com/cockroachdb/cockroach/pull/105351.
The links use the database name from the `metadata` column, which was previously using the incorrect aggregate function when reading from the activity table.
