### ISSUE TITLE
export GOMAXPROCS=100 leads to test failures

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#1035]
$export GOMAXPROCS=100

and run

$make

FAIL	github.com/cockroachdb/cockroach/kv	5.837s
exit status 2
FAIL	github.com/cockroachdb/cockroach/multiraft	7.403s
go build testmain: /usr/local/Cellar/go/1.4.2/libexec/pkg/tool/darwin_amd64/6l: signal: interrupt
make: *** [test] Error 1

I suppose this might be okay so close if you don't care.

**Comment by tschottdorf** [comment]
Hey Vivek, when a test error occurs try to figure out the specific test that failed (though there may not be one here, since the test catches an interrupt signal, but that could be you CTRL-C'ing it.

I've just tried to reproduce this and most of the time the test passes, but I did get this:

```
L="INFO" T="5/14 09:34:32.154" F="kv.go:111" Msg="failed AdminSplit: range_command.go:866: split at k
ey \"q\" failed: \"\\x00\\x00meta1\\xff\\xff\" is not valid range metadata key: body of range lookup
is >= KeyMax"
--- FAIL: TestMultiRangeScanWithMaxResults-100 (0.04s)
        server_test.go:427: range_command.go:866: split at key "q" failed: "\x00\x00meta1\xff\xff" is not valid range metadata key: body of range lookup is >= KeyMax
```

but that's a failure in `server`, not `kv` or `multiraft`.

**Comment by vivekmenezes** [comment]
Hey I can take a look at this and see what the problem is. It was very
reproducable on my machine.

**Comment by tschottdorf** [comment]
Today I'm getting errors more frequently. Here's the condensed output:

```
	range_test.go:1060: test 2: should not have been able to execute cmd2
	leaktest.go:136: Test appears to have leaked a range command:
	range_test.go:1340: expected all incremented values to be 1; got 3
	range_test.go:1359: expected sum of all increments to be 1325; got 1323
	leaktest.go:136: Test appears to have leaked a range command:
	client_range_tree_test.go:655: using pseudo random number generator with seed -4986661529669538700
	leaktest.go:136: Test appears to have leaked a range command:
	metrics_test.go:303: expected histogram1_sum to be 331132, instead was 0
	metrics_test.go:307: expected histogram1_agg_avg to be 110030, instead was 0
	metrics_test.go:311: expected histogram1_count to be 3, instead was 0
```

it was created with `grep -E "^\t[a-zA-Z]" log | uniq`. In particular the `range_test:1340` error is worrying.

**Comment by tschottdorf** [comment]
@tamird is working this on #1406.
