### ISSUE TITLE
sql: 0::decimal/infinity returns 0E-2019 instead of 0

### ISSUE THREAD

**Issue by otan** [cockroachdb/cockroach#103633]
In PG:

```
otan=# select 0::decimal/'infinity';
 ?column?
----------
        0
(1 row)
```

In CRDB:

```
root@:26257/defaultdb> select 0::decimal/'infinity';
  ?column?
------------
  0E-2019
(1 row)


Time: 1ms total (execution 1ms / network 1ms)
```

The reason why it uses `E-2019` is because it uses the [HighPrecisionCtx](https://github.com/cockroachdb/cockroach/blob/b6f9e62b9940da5989f91b25019fb4574924163b/pkg/sql/sem/tree/decimal.go#L37-L38) to divide. We should probably not do that (or make the `apd` library not do that in `Divide`)

Note this is reporting correctly for non-infinity:
```
root@:26257/defaultdb> select 0 / 5::decimal;
  ?column?
------------
         0
(1 row)


Time: 1ms total (execution 1ms / network 0ms)
```

Issue from https://github.com/cockroachdb/cockroach/pull/102299

Jira issue: CRDB-28105

**Comment by yuzefovich** [comment]
Known issue #40929

**Comment by otan** [comment]
#40929 seems like it's a panic, which i can't repro. nonetheless, the result is incorrect
