### ISSUE TITLE
testserver: TestServer should work with ManualClocks

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#10361]
Currently there's no way to directly control the clock of a `TestServer` (and also a `TestCluster`), so tests that need to advance time have to do hacks like inserting messages into the cluster that pretend they're from the future (to update the hlc), or manually expire SQL leases, or otherwise use `multiTestContext`.

There's testing knobs in `StoreTestingKnobs` related to the `MaxOffset` handling that should go away once this is done.

**Comment by tbg** [comment]
Going to close this. It's unclear that this is even a good idea (if you ask me it's clear that it's a bad idea to use manual clocks in something as high level as a TestServer; we have plenty of code that deals in durations and gets fatally thrown off when the clock is manual).
