### ISSUE TITLE
jobs: potential issue/race in job shutdown

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#103687]
Not clear if this is jobs issue; might be some other issue, possibly with sql executor.
Pretty hard, but possible (>30 minutes) to reproduce on the master (using gce worker).

./dev test --stress --race  --stress-args="-p 20" pkg/ccl/changefeedccl --filter TestAlterChangefeedSetDiffOption --show-logs 2>&1 | tee /tmp/stress

It's a changefeed test; but the failures happen always when the changefeed job finished; and we are clearing out job claim
as part of job cancellation.
[stress_master.log](https://github.com/cockroachdb/cockroach/files/11520326/stress_master.log)

Stress run log attached.

Jira issue: CRDB-28136

**Comment by tbg** [comment]
Relevant part:

```
==================
WARNING: DATA RACE
Write at 0x00c0079d2f88 by goroutine 5602:
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnSpanRefresher).splitEndTxnAndRetrySend()
      github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go:411 +0x764
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnSpanRefresher).maybeRefreshAndRetrySend()
      github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go:337 +0x5f5
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnSpanRefresher).sendLockedWithRefreshAttempts()
      github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go:275 +0x7bd
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnSpanRefresher).SendLocked()
      github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go:148 +0x1e6
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnCommitter).SendLocked()
      github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_committer.go:190 +0x3e1
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnPipeliner).SendLocked()
      github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go:292 +0x245
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnSeqNumAllocator).SendLocked()
      github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_seq_num_allocator.go:105 +0xd4
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnHeartbeater).SendLocked()
      github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater.go:246 +0x7cc
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*TxnCoordSender).Send()
      github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_coord_sender.go:529 +0x9b2
  github.com/cockroachdb/cockroach/pkg/kv.(*DB).sendUsingSender()
      github.com/cockroachdb/cockroach/pkg/kv/db.go:1006 +0x190
  github.com/cockroachdb/cockroach/pkg/kv.(*Txn).Send()
      github.com/cockroachdb/cockroach/pkg/kv/txn.go:1091 +0x334
  github.com/cockroachdb/cockroach/pkg/kv.(*Txn).commit()
      github.com/cockroachdb/cockroach/pkg/kv/txn.go:707 +0x224
  github.com/cockroachdb/cockroach/pkg/kv.(*Txn).Commit()
      github.com/cockroachdb/cockroach/pkg/kv/txn.go:722 +0xaf
  github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).commitSQLTransactionInternal()

```

racing with the race transport. @pavelkalinnikov could be something for KV Shared Secondary rotation.

**Comment by nvanbenschoten** [comment]
This appears to be fallout from https://github.com/cockroachdb/cockroach/pull/103241.

**Comment by miretskiy** [comment]
It does appear that this race transport copies the slice, but retries on the client (which ought to be allowed) can mutate inner state.

**Comment by andrewbaptist** [comment]
I saw a similar issue [here](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelExtendedCi/10333836?showRootCauses=true&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true
):

I tried running the test manually
`./dev test --stress --race pkg/kv/kvserver/liveness -f TestGetActiveNodes`
But was getting some issues running on my GCE worker. The error from that log is:

```
WARNING: DATA RACE
Write at 0x00c00383f958 by goroutine 115272:
  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnSpanRefresher).splitEndTxnAndRetrySend()
```

**Comment by dt** [comment]
Think I just hit this as well in https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelExtendedCi/10532728?buildTab=tests&expandedTest=build%3A%28id%3A10532725%29%2Cid%3A593 on https://github.com/cockroachdb/cockroach/pull/104829
