### ISSUE TITLE
cli/doctor: use AOST when fetching tables for doctor cluster commands

### ISSUE THREAD

**Issue by fqazi** [cockroachdb/cockroach#103608]
Currently, the debug doctor command doesn't use AS OF SYSTEM TIME when reading system.jobs, system.descriptors, system.namespace so there is a potential risk of contention on these tables when validating against a database. To minimize this risk even further, we can use an AOST clause on the queries used to fetch these tables for the doctor commands.

Jira issue: CRDB-28095

**Comment by postamar** [comment]
We should consider doing the same when collecting debug zips with `debug zip`.
