### ISSUE TITLE
rpc: grpc-gateway loopback conn mistakenly uses onlyOnceDialer and causes sticky permanent RPC errors

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#103762]
**Describe the problem**

The rpc-gateway connection (used by our HTTP interfaces) uses a loopback connector. This is mistakenly configured in v23.1 to use "onlyOnceDialer", a mechanism through which a connection is not re-attempted if it fails.

The result is that when a cluster is overloaded, the loopback connection may fail once (due to a timeout) and then it will fail forever after, causing most of the HTTP interfaces to become unusable.

xref https://github.com/cockroachdb/cockroach/issues/103692#issuecomment-1558797640
xref https://github.com/cockroachdb/cockroach/issues/99261#issuecomment-1555052563

**To Reproduce**

Overload a v23.1 cluster and use the HTTP connection until it fails once.
Then the failure will persist forever until the node is restarted.

**Expected behavior**

The loopback connection should be retried if it fails (i.e. not use onlyOnceDialer)

Jira issue: CRDB-28178
Epic: CRDB-28893

**Comment by erikgrinaker** [comment]
Reopening until 23.1 backport is merged.

**Comment by erikgrinaker** [comment]
Backport merged.
