### ISSUE TITLE
ui: create a set of QA steps to walk through for the UI before each beta release

### ISSUE THREAD

**Issue by maxlang** [cockroachdb/cockroach#10372]
In order to ensure the UI is working as expected, it would be nice to have a brief set of steps to run through before each beta release.

cc @mrtracy

**Comment by dianasaur323** [comment]
@mrtracy This seems like a value add, but also not a blocker for the 1.0 milestone. I'm going to shift it over to Q2 2017. Let's try to have some sort of QA process at that point. Feel free to move back into 1.0 if you disagree.

**Comment by dianasaur323** [comment]
Let's close for now, and if we need to, open up a new issue? This seems very dated at this point.
