### ISSUE TITLE
Unexpected results related to `INDEX`

### ISSUE THREAD

**Issue by DerZc** [cockroachdb/cockroach#103755]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**
Consider the following program:
```
USE test;
DROP DATABASE IF EXISTS database7 CASCADE;
CREATE DATABASE database7;
USE database7;

SET CLUSTER SETTING diagnostics.reporting.enabled    = false;
SET CLUSTER SETTING diagnostics.reporting.send_crash_reports = false;
SET CLUSTER SETTING sql.metrics.statement_details.plan_collection.enabled = 'off';
SET CLUSTER SETTING sql.stats.automatic_collection.enabled = 'off';
SET CLUSTER SETTING timeseries.storage.enabled = 'off';
set experimental_enable_hash_sharded_indexes='on';


CREATE TABLE t1 (c0 INT4);
CREATE INDEX ON t1(c0) USING HASH WITH BUCKET_COUNT=794;
INSERT INTO t1 (c0) VALUES(-10), (-20);

SELECT t1.c0 FROM t1 WHERE ((((t1.c0)<(0)))OR((t1.c0) IN ((VALUES (2)))));
SELECT t1.c0 FROM t1 WHERE ((((t1.c0)<(0)))OR((t1.c0) IN (SELECT COUNT(t1.c0) FROM t1)));
```
I got the following results:
```
> SELECT t1.c0 FROM t1 WHERE ((((t1.c0)<(0)))OR((t1.c0) IN ((VALUES (2)))));
  c0
------
(0 rows)

Time: 1ms

> SELECT t1.c0 FROM t1 WHERE ((((t1.c0)<(0)))OR((t1.c0) IN (SELECT COUNT(t1.c0) FROM t1)));
  c0
-------
  -20
  -10
(2 rows)

Time: 5ms
```
As there are only two rows in `t1.c0`, so these two queries are equivalent. As `(t1.c0)<(0)` is always true, so the first query should not have empty results. 

Although there is `IN` expression, but different from https://github.com/cockroachdb/cockroach/issues/102864 that there is no type cast, and if I remove `USING HASH WITH BUCKET_COUNT=794` in `CREATE INDEX`, then the first query can generate correct results.

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

I can reproduce with the latest commit version https://github.com/cockroachdb/cockroach/commit/a1b8517dd93d386fdf6b170982c604e6396b50e9

**Expected behavior**
The first query generate non-empty results.

**Environment:**
 - CockroachDB version https://github.com/cockroachdb/cockroach/commit/a1b8517dd93d386fdf6b170982c604e6396b50e9
 - Server OS: Ubuntu 22.04
 - Client app: CLI

Jira issue: CRDB-28176

**Comment by rytaft** [comment]
Thanks for the report, @DerZc! I've confirmed I can reproduce this on master. Thankfully I *cannot* reproduce on the latest 22.2 or 23.1 release.
