### ISSUE TITLE
stability: Poor performance of race-enabled build

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#10388]
On rho, upgrading from 5bc7bf1f0b to 7915024962 (race-enabled builds) caused performance to plummet, from ~130 inserts per second to ~6. Raft elections are twice as frequent as before (about 10 MsgVote and 10 MsgVoteResp messages per second), and msgProp is 5 times more common (~35 vs ~7). 

Perhaps the biggest problem is `cmdQMu` contention. Messages like this are not uncommon:

    cockroach@104.196.147.189: W161102 09:06:12.118239 147887 storage/replica.go:551  [n3,s3,r5973/2:/System/tsd/cr.node.txn.resta…] cmdQMu: mutex held by github.com/cockroachdb/cockroach/pkg/storage.(*Replica).beginCmds for 982.044622ms (>500ms):

and the 95th percentile mutex duration is 900µs, up from 20µs (other mutex metrics haven't changed significantly).

**Comment by bdarnell** [comment]
`rho` has gone into days-long periods of single-digit (but non-zero) qps before, so it's not necessarily related to this new build. Performance suddenly drops, then suddenly recovers. Transitions between the high and low performance stats often occur with restarts, but sometimes the performance changes even though the nodes are up continuously. It looks like the high-performance state is the anomaly; we've spent maybe 20% of our time in that state in the last month.

**Comment by petermattis** [comment]
Did we ever figure out what was happening here? Looking at `rho` right now, performance is between 20-30 ops/sec.

**Comment by bdarnell** [comment]
We never investigated this, and I'm not sure if it's worth it. Race builds will always be slow and their performance is somewhat mysterious (there's a report that race builds have actually gotten substantially slower for some applications in go 1.8)

**Comment by dianasaur323** [comment]
@bdarnell @petermattis given the outstanding question of whether or not we should even investigate, I'll close this for now. However, feel free to re-open and add to the 1.0 milestone if necessary?
