### ISSUE TITLE
cdc: unskip cdc/bank on arm64

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#103888]
We’re soon going to start running metamorphic arm64 clusters in roachtest nightlies… the cdc roachtest has been disabled on arm64 [1] a while ago. The story now is confluent-cli is available on arm [2]. It would be nice to unskip cdc on arm.
[1] https://github.com/cockroachdb/cockroach/pull/89211
[2] https://s3-us-west-2.amazonaws.com/confluent.cloud/confluent-cli/archives/latest/confluent_latest_linux_arm64.tar.gz

Jira issue: CRDB-28241

Epic CRDB-9179

**Comment by srosenberg** [comment]
> We’re soon going to start running metamorphic arm64 clusters in roachtest nightlies…

To clarify, after this PR [1] is merged, any roachtest is a candidate for arm64 unless its `ClusterSpec.Arch` says otherwise.

[1]

**Comment by srosenberg** [comment]
`cdc/mixed-versions` is also dependent on confluent cli,

```
  | Wraps: (3) /mnt/data1/confluent/install.sh /mnt/data1/confluent returned
  |   | stderr:
  |   |
  |   | stdout:
  |   | We don't know how to install the confluent CLI for "linux/aarch64"
```

**Comment by srosenberg** [comment]
More CDC roachtests had to be disabled on arm64 [1]. Here is the full set,

```
find pkg/cmd/roachtest/tests -name cdc.go |xargs grep -B 4 AMD64 |grep Name
		Name:      "cdc/initial-scan-only",
		Name:      "cdc/tpcc-1000",
		Name:      "cdc/tpcc-1000/sink=null",
		Name:      "cdc/initial-scan",
		Name:      "cdc/sink-chaos",
		Name:      "cdc/crdb-chaos",
		Name:      "cdc/cloud-sink-gcs/rangefeed=true",
		Name:      "cdc/pubsub-sink",
		Name:      "cdc/pubsub-sink/assume-role",
		Name:      "cdc/cloud-sink-gcs/assume-role",
		Name:      "cdc/webhook-sink",
		Name:      "cdc/kafka-oauth",
		Name:  "cdc/bank"
```

It would be nice to get everything running on arm64 soon. Please let @cockroachdb/test-eng know if you need any help.

[1] https://github.com/cockroachdb/cockroach/pull/104303/files#diff-7276eae775645763129d898332c5c5b40465682ae914ff892ea48d2efe89532a
