### ISSUE TITLE
changefeedccl: connecting to azure event hubs through kafka api broken

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#103832]
See: https://cockroachlabs.atlassian.net/wiki/spaces/CDC/pages/3020292162/Azure+Event+Hubs+Beta+Testing or https://dzone.com/articles/using-cockroachdb-cdc-with-azure-event-hubs 

Creating a changefeed into azure event hubs via their kafka api no longer works, you now get an `client/metadata got error from broker -1 while fetching metadata: read tcp ‹10.142.0.89:52980› -\u003e ‹20.42.68.75:9093›: read: connection reset by peer` error.

From[ this issue](https://github.com/liliankasem/sarama-eventhub-kafka/issues/1) someone had a couple of years ago using sarama + event hubs, it looks like the SASL versions between sarama and event hubs might not match up. I tested with a few different versions of CRDB and got the same error, so the change would have been on the event hub side.

Jira issue: CRDB-28225

Epic CRDB-18958

**Comment by samiskin** [comment]
I didn't end up hitting this issue when i went through the steps from https://dzone.com/articles/using-cockroachdb-cdc-with-azure-event-hubs via a roachprod azure cluster 🤔 , was able to receive messages

<img width="512" alt="Screenshot 2023-06-26 at 1 28 33 PM" src="https://github.com/cockroachdb/cockroach/assets/6236424/01d0488a-c05b-4367-9b81-cee8ea66a022">

**Comment by samiskin** [comment]
I noticed that this setting specifically says "Local" Authentication, so perhaps it only works when running under the same Azure organization.
<img width="454" alt="Screenshot 2023-06-26 at 1 39 54 PM" src="https://github.com/cockroachdb/cockroach/assets/6236424/8a4e072b-8f3d-4830-a1e5-3487fb2accb5">

**Comment by samiskin** [comment]
^ Scratch that, confirmed it works even if I run from a normal non-azure machine 🤔

**Comment by jayshrivastava** [comment]
Looks like a customer ran into this on 22.2.10 https://github.com/cockroachlabs/support/issues/2476

**Comment by jayshrivastava** [comment]
I get this error upon creating the changefeed in a local cluster. 
```
ERROR: connecting to kafka: jayants-test-event-hubs.servicebus.windows.net:9093: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)
```

**Comment by amruss** [comment]
Closing this: we discovered that the issue is because using the kafka endpoint requires a standard plan - it is not supported on the basic plan.
