### ISSUE TITLE
sql: set `trace.redactable.enabled` to true by default on the master branch

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#103883]
Since it was introduced this cluster setting defaults to 'false', because until v22.x we had concerns about performance.

Since then, we have made some improvements about tracing performance, so we are considering enabling this by default tentatively.

After this PR merges, we will monitor the roachperf dashboards. It can be reverted if performance is found to be altered unacceptably (in which case the tracing perf work can be re-prioritized).

Epic: CRDB-27642

Jira issue: CRDB-28238

**Comment by michae2** [comment]
I'm definitely in favor, but I wonder about this part:

> After this PR merges, we will monitor the roachperf dashboards. It can be reverted if performance is found to be altered unacceptably (in which case the tracing perf work can be re-prioritized).

Do any of the roachperf workloads run with tracing enabled? If not, will this monitoring actually catch a regression in tracing performance?

**Comment by knz** [comment]
> Do any of the roachperf workloads run with tracing enabled?

The concern here is the effect of `trace.redactable.enabled` when tracing is *not* otherwise enabled. i.e. does it impact performance in the common case of non-tracing queries.

This is relevant because even when tracing is not enabled we have 1) random sampling of sql statements where tracing is enabled, to generate sql stats 2) different processing of data structures in the tracer / context spans, which are always enabled (for SQL query stats)..
