### ISSUE TITLE
kv: properly handle ambiguous errors that occur alongside commits

### ISSUE THREAD

**Issue by AlexTalks** [cockroachdb/cockroach#103817]
As observed in the wild (#67765), in autonomous simulation testing [(internal link)](https://cockroachlabs.atlassian.net/l/cp/fddPBH6M), and in our own reproductions (#103123, #103756), we have several bugs relating to the way we handle ambiguous errors in KV batches that commit, potentially manifesting as `transaction unexpectedly committed` errors (which will cause a node crash), or as transactions that are incorrectly reported to the client as failed when they may actually be end up being explicitly committed.

These ambiguous errors - i.e., a network error on one of a transaction's `BatchRequest` RPCs that cannot be determined to if it has succeeded or failed - are inherent to any distributed system, but need to be handled properly in order to avoid issues with our implementation of the [parallel commit protocol](https://github.com/cockroachdb/cockroach/blob/cff0eb801aea96cb01d4a9d792cc24b6cf8ea4aa/docs/tla-plus/ParallelCommits/ParallelCommits.tla). When one of these errors occurs in the `DistSender` on a batch that contains an `EndTxn` request, we currently attempt to elide the error like so:

https://github.com/cockroachdb/cockroach/blob/775b005927ee65a7af3b9cd4078d607c770244d6/pkg/kv/kvclient/kvcoord/dist_sender.go#L2235-L2237

While we attempt to reissue (potentially: idempotently replay) any failed `BatchRequest`s, sending them to subsequent replicas in the replica set in an attempt to sidestep the ambiguous error, this can run into problems:
* If the transaction actually _did_ succeed in all of its writes, the transaction would be implicitly committed (and in transaction state `STAGING`) despite the ambiguous error.
* In this state, some other operation encountering the transaction record (e.g. contending on keys) may explicitly commit it via a `RecoverTxn` request.  
* Since the transaction coordinator is unaware of this recovery, it may result in a duplicate `EndTxn` request at a higher timestamp (`transaction unexpectedly committed`) or even fail on the reissued request, reporting a transaction failure to the client for a transaction that was ultimately committed.

This should be fixed for both correctness in the near term, and improvement in the longer term. A discussed approach is as follows:

**Near Term**:
As a quicker fix, we should avoid attempting to sidestep the ambiguous errors on batches with commits in the `DistSender` and instead propagate them as `AmbiguousResultError`s. 
* This avoids the potential issues caused by reissuing the requests after the ambiguous error, and indicates to the client that the transaction's commit state needs to be independently validated.
* This approach should be validated that it does not cause a marked increase in unnecessary/avoidable `AmbiguousResultError`s, and should be tested using the data-driven test reproductions linked above.

**Medium Term**:
We should be able to avoid raising all RPC failures as `AmbiguousResultError`s, and minimize the cases to only those necessary by "remembering" the earlier ambiguity in retrying our failed writes and rejecting them as non-idempotent if they change the timestamp of a transaction that may already be implicitly committed.
* This avoids potentially reporting a transaction as incorrectly "failed" or "double committing", instead returning an ambiguous error only in the necessary cases, indicating to the client that the transaction's commit state needs to be idependently validated. 

**Longer Term**:
See #108342.

Jira issue: CRDB-28217

**Comment by AlexTalks** [comment]
It is worth noting here that the final agreed-upon approach forms a significant improvement over the original "near-term" approach suggested here by minimizing the cases that should result in an `AmbiguousResultError` to the minimum necessary.  This approach only raises ambiguous errors when a retried write shouldn't be considered idempotent, and is implemented in #107658.

A potential longer-term improvement could be considered also - described in #108342, we could add support for querying intents for ambiguous writes from the DistSender, potentially allowing us to eliminate certain cases of `AmbiguousResultError`s and instead allowing us to report the transaction as successfully committed. This is not required to fix the existing issue, however, but could be a potential enhancement.

**Comment by daniel-crlabs** [comment]
Affects this customer: https://cockroachdb.zendesk.com/agent/tickets/19344

**Comment by daniel-crlabs** [comment]
Affects this customer: https://cockroachdb.zendesk.com/agent/tickets/19344
