### ISSUE TITLE
storage: prevent startup after physical corruption

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/cockroach#103899]
Replication-level corruption results in crashing the node, but also the writing of a special file (`base.PreventedStartupFile`) to prevent node startup:

https://github.com/cockroachdb/cockroach/blob/df21930f8ecb3d250c2cb90741cc03bd16c8444f/pkg/kv/kvserver/replica_corruption.go#L57-L69

This is done because the node requires manual intervention. Today, corruption of physical media (eg, bit rot resulting in node-local data loss) similarly requires manual intervention to replace the node. Although we hope to support automatic recovery of physical corruption from other replicas some day (#67568), in the meantime we require the node with local corruption be decommissioned and replaced. We should consider writing `base.PreventedStartupFile` before crashing these nodes to prevent automatic restarting of a node that we have every expectation will crash again.

Jira issue: CRDB-28250

**Comment by nicktrav** [comment]
@RahulAggarwal1016 is going to pick this one up. Thanks, Rahul!
