### ISSUE TITLE
changefeedccl: pts records are unlinked when altering changefeeds

### ISSUE THREAD

**Issue by jayshrivastava** [cockroachdb/cockroach#103855]
There are some code paths https://github.com/cockroachdb/cockroach/blob/eba2e605f265c8d1f470b228b8715ff59bc56e40/pkg/ccl/changefeedccl/alter_changefeed_stmt.go#L743-L752 where we create a new progress without copying the PTS record from the old one. This can cause changefeeds to lose track of their PTS records and end up creating new ones.

Jira issue: CRDB-28230

Epic CRDB-14988

**Comment by jayshrivastava** [comment]
Leaving this issue open because we need to decided what the best approach is for cleaning up the old records. Discussion in https://github.com/cockroachlabs/support/issues/2319

**Comment by shermanCRL** [comment]
Is this closeable?

**Comment by jayshrivastava** [comment]
We should keep it open. We still have to add some code to delete the old PTS records.

**Comment by jayshrivastava** [comment]
https://github.com/cockroachdb/cockroach/pull/118772
