### ISSUE TITLE
kvserver: avoid quadratic growth of raft log under unavailability

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#103908]
When a range is unable to make progress, every couple of ticks we "repropose" (= re-add to the log) everything that is inflight. Assuming a steady arrival rate 1 of requests to be replicated, at time T approximately T requests will be inflight, but the number of raft log entries waiting to be replicated is ~T^2.

We should fix this, i.e. bring it down such that the log grows only linearly in this case.

x-ref https://github.com/cockroachdb/cockroach/issues/98563, #102956

Jira issue: CRDB-28255

Epic CRDB-25287

**Comment by erikgrinaker** [comment]
We should make sure the solution here also addresses lease requests. In particular with expiration-based leases, where the Raft scheduler will eagerly attempt to acquire leases if the range doesn't have one:

https://github.com/cockroachdb/cockroach/blob/ff8ccbe880427a3a4cdf3c95a99d7b52cf3c3d43/pkg/kv/kvserver/replica_raft.go#L1228-L1244

**Comment by tbg** [comment]
Looking at the initial problem (quadratic log growth under linear arrival rate of requests), it is difficult to avoid this in all cases (unless we're willing to make invasive changes) but there are likely good heuristics we should be using (and currently aren't). The basic problem is that `RawNode` doesn't give us a cheap way to tell whether something is in the log.

True, it does return `ErrProposalDropped` in which case we know _for sure_ it's not in the log. But absence of `ErrProposalDropped` can still mean that the proposal is not in the log. Concretely, this happens during raft forwarding: if the local `RawNode` isn't (or isn't considering itself) the leader but it remembers the "current" leader, it will relay the `MsgProp` to that peer. There is no backpropagation of whether the leader then inserted it into the log (or if the message reached the leader in the first place; the leader may have crashed). So often it is in the log, but we don't know at which position (since it's not in the local log at least for some time), but not always.
The local `RawNode` may also consider itself the leader, but a later leader then overwrites it with a competing log entry. So in this case it "was" in the log at some point, but then it drops out of the log again and never commits.

`RawNode` doesn't let us track directly what's in the log and as evident by the examples above, it's not always known locally. If we had an architecture where we never use raft forwarding, we could, in principle, track the log position of the proposal (which may be unset if the proposal is not in the log). Rather than reproposing blindly on a timer, we could be event-driven and reinsert to the log whenever the log entry we are tracking is replaced by an unrelated entry. We could track this since we own the `raft.Storage` implementation.

Unfortunately, raft proposal forwarding is currently used for leases. To request a lease, a raft leader needs to be active. That leader may be on a different node than that requesting the lease. The proposed leaseholder will hand a proposal requesting the lease to its local `RawNode`, which forwards it to the Raft leader. From there, it is distributed into the log. Once applied on the Raft leader, we'll try to colocate Raft leadership and the lease by transferring the Raft leader to the leaseholder (this is initiated by the Raft leader on `(*Replica).tick`). Long story short, we need to re-vamp our lease protocol.

There is at least one more case where we rely on proposal forwarding, the replica circuit breaker probes (`ProbeRequest`) being one of them. We can identify any additional ones by checking if any other requests [bypass the leaseholder check](https://github.com/cockroachdb/cockroach/blob/832332205aa272160a43beb5869d5cba31342616/pkg/kv/kvpb/api.go#L67). All such commands need to move to above-Raft RPCs directed at the Raft leader, i.e. the "forwarding" code needs to be lifted above raft.

----

Moving on to tactical things we can do. Once https://github.com/cockroachdb/cockroach/pull/100083 merges, it'll be easier to distinguish commands that are _definitely_ not in the log (A) from commands that were _definitely_ forwarded (B) from commands that were (at least for now) locally inserted (C). We can then have different policies for each:

- A: if definitely not in the log, repropose once leader changes.
- C: if definitely forwarded, repropose after a timeout (i.e. keep current default behavior), pessimistically transition to A on leader change (and repropose, which may transition into either A, B, or C)
- if (at least at some point) inserted into local leader log, don't repropose but pessimistically revert to state A if leader changes

Unfortunately, this won't change the worst-case behavior, but it should reduce both the magnitude and frequency of this in practice.

**Comment by erikgrinaker** [comment]
> Long story short, we need to re-vamp our lease protocol.

Placeholder issue: https://github.com/cockroachdb/cockroach/issues/105172

**Comment by tbg** [comment]
https://github.com/cockroachdb/cockroach/pull/105896 has now merged, so with replica circuit breakers enabled, the growth will be linear. Due to competing priorities, that's likely where things will remain for now.

**Comment by tbg** [comment]
In fact, since we enabled `CheckQuorum`, even the linear growth is gone. In a true loss of quorum, after a few seconds no Replica will be in StateLeader any more, meaning all log entries are dropped unconditionally. So there is no more log growth.

With #105896 being backported, I think we are in a position to close this.
