### ISSUE TITLE
distsql: outer joins, distinction between ON and WHERE conditions

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#10394]
This is a follow up on #10346, there is the following unaddressed complication with outer joins. 

Consider this example:

```sql
CREATE TABLE U (K INT, A INT, B INT);
CREATE TABLE V (K INT, C INT, D INT);

INSERT INTO U VALUES (1, 2, 2);
INSERT INTO V VALUES (1, 3, 3);

SELECT * FROM U FULL OUTER JOIN V ON U.K=V.K AND U.A>V.C;
```

In our case the streams will be ordered by K, but the rest of the expression `(U.A>V.C)` will have to be evaluated (like the filter). With inner joins, there is no difference between an `ON` condition and `WHERE` condition, but with outer joins there is. The example above results in:
```
 k | a | b | k | c | d 
---+---+---+---+---+---
 1 | 2 | 2 |   |   |  
   |   |   | 1 | 3 | 3
```
With the condition moved to `WHERE (SELECT * FROM U FULL OUTER JOIN V ON U.K=V.K WHERE U.A > V.C;)` we get no results.

In general this means we will need both an `ON` expression and a `WHERE` expression in the spec (but we should disallow setting both if the join is inner).

**Comment by dianasaur323** [comment]
This seems like an odd ux quirk that we can clean up for the 1.0. @knz I believe you have been doing work on joins - mind taking a look?

**Comment by RaduBerinde** [comment]
This is fixed. The expression in the joiner spec has been switched to be an `ON` expression; filtering (`WHERE`) is supported on all processors as part of the `PostProcessSpec`.
