### ISSUE TITLE
Investigate high CPU usage scanning large JSONB columns

### ISSUE THREAD

**Issue by msirek** [cockroachdb/cockroach#103960]
**Describe the problem**
Scanning rows with large JSONB columns over 10MB can be very expensive. This issue is opened to investigate why reading large JSONB column data is so expensive and if it is related to #87587

Related to support issue https://github.com/cockroachlabs/support/issues/2322

Jira issue: CRDB-28272

**Environment:**
 - CockroachDB version 22.1.x, 22.2.x

**Comment by michae2** [comment]
[triage meeting] we should change this issue to be an investigation of why scanning of large JSONB values is CPU-intensive, rather than changing cost model or statistics. next step is to come up with a repro.

**Comment by msirek** [comment]
I tried reproducing the CPU profile seen in https://github.com/cockroachlabs/support/issues/2322, but have been unsuccessful so far.

Here is the test info:

1. Download and untar the test files bundle [large_json_test.tar.gz](https://github.com/cockroachdb/cockroach/files/11655164/large_json_test.tar.gz)
2. Start CRDB 22.2.9
3. cd large_json_test
4. Upload JSON files to the server via: `cockroach userfile upload large-file.json --insecure` and `cockroach userfile upload CardTypes.json --insecure`
5. `chmod +x setup test`
6. Run the setup script: `.\setup`
7. Run the test script and capture a CPU profile while it's running: `.\test`
