### ISSUE TITLE
roachtest: ClusterSpec should support user-specified clouds _compatible_ with a test

### ISSUE THREAD

**Issue by srosenberg** [cockroachdb/cockroach#104029]
Currently, roachtests don't have an established mechanism for specifying a set of cloud providers which are _compatible_ with a given test. Theoretically, a roachtest should be cloud-agnostic since it doesn't directly interact with cloud APIs, a task that's delegated to roachprod. In practice, several roachtests may in fact be _incompatible_ with a set of cloud providers. E.g.,

* `schemachange/mixed-versions-compat` uses `gsutil` to copy corpus data from a GCS bucket [1]
* `restore` variant uses AWS-specific zones [2]
* variants of `clearrange` and `yscb/A` use ZFS, available only in GCE [3], [4], [5]

Note, while `gsutil` in the first example may seem like a superficial incompatibility, in reality large-scale backup/restore tests may induce large _egress_ if data is pulled from a cloud provider, different from where the test is scheduled to execute. Hence, we need to ensure, either data is sufficiently replicated (i.e., local to the test's cloud provider), or the test is specified to be incompatible with the cloud providers which lack the required test data (fixtures).
In practice, there may be additional, albeit rare reasons for incompatibility; e.g., quota, price, specific machine type, etc.

Consequently, there must be an established mechanism, both for specifying when a test is incompatible with a cloud provider, and for skipping the test from executing against all incompatible cloud providers. Currently, `ClusterSpec.Cloud` denotes the cloud provider that's been provided via `roachtest run --cloud`, _not_ a compatible cloud provider, specified by the test author. That is, the framework makes an implicit (and wrong) assumption that every test should be executable against `ClusterSpec.Cloud`. As a further confounding factor, CI uses `tags` to select roachtests per given cloud provider [6].

As for skipping incompatible tests, test authors came up with ad hoc workarounds, e.g., [7], [8], thereby complicating both the setup logic, as well as, future refactoring.

[1] https://github.com/cockroachdb/cockroach/blob/87c677569f7af6e72834d68e67493efbd72971ac/pkg/cmd/roachtest/tests/mixed_version_decl_schemachange_compat.go#L67-L70
[2] https://github.com/cockroachdb/cockroach/blob/87c677569f7af6e72834d68e67493efbd72971ac/pkg/cmd/roachtest/tests/restore.go#L299-L304
[3] https://github.com/cockroachdb/cockroach/blob/87c677569f7af6e72834d68e67493efbd72971ac/pkg/cmd/roachtest/tests/clearrange.go#L56
[4] https://github.com/cockroachdb/cockroach/blob/87c677569f7af6e72834d68e67493efbd72971ac/pkg/cmd/roachtest/tests/ycsb.go#L118
[5] https://github.com/cockroachdb/cockroach/blob/87c677569f7af6e72834d68e67493efbd72971ac/pkg/cmd/roachtest/spec/cluster_spec.go#L271-L274
[6] https://github.com/cockroachdb/cockroach/blob/87c677569f7af6e72834d68e67493efbd72971ac/build/teamcity/util/roachtest_util.sh#L66-L77
[7] https://github.com/cockroachdb/cockroach/blob/87c677569f7af6e72834d68e67493efbd72971ac/pkg/cmd/roachtest/tests/ycsb.go#L50-L53
[8] https://github.com/cockroachdb/cockroach/blob/87c677569f7af6e72834d68e67493efbd72971ac/pkg/cmd/roachtest/tests/restore.go#L725-L727

Jira issue: CRDB-28322

**Comment by srosenberg** [comment]
Tagging (pun intended) relevant issues,

- https://github.com/cockroachdb/cockroach/issues/100605
- https://github.com/cockroachdb/cockroach/issues/99951

Based on an earlier discussion within TestEng, tags shouldn't be using for capturing (compatibility) semantics; they are merely metadata for labeling/organizing (e.g., grouping) roachtests.

**Comment by srosenberg** [comment]
> I think that if there is a separate "cloud compatibility" field in the test spec (as proposed in https://github.com/cockroachdb/cockroach/issues/100605), the ClusterSpec in the test registry should not have a Cloud field at all.

Logically, it makes sense.  However, we may need to refactor `clusterImpl`; it's currently agnostic to `TestSpec`, but it needs to differentiate between `local` and actual cloud, in some cases.

**Comment by RaduBerinde** [comment]
Another super confusing thing is that the registry "leaks" the cloud that we are using through the `ClusterSpec` and some registration code uses it to tweak the test settings depending on the cloud:

https://github.com/cockroachdb/cockroach/blob/c34dd5f1eb1ebeb9618d8009585f7810804c2bbf/pkg/cmd/roachtest/tests/tpcc.go#L538

https://github.com/cockroachdb/cockroach/blob/c34dd5f1eb1ebeb9618d8009585f7810804c2bbf/pkg/cmd/roachtest/tests/tpcc.go#L862

This is crazy; test registration should not depend on the flags. If we need different parameters, we should simply define two different tests.

**Comment by RaduBerinde** [comment]
Yes. As a first step, we should make sure none of the code registering tests looks at the `.Cloud` field. We should be able to do that once we have a cloud compatibility field.
