### ISSUE TITLE
Populate INFORMATION_SCHEMA.ROUTINES and PARAMETERS

### ISSUE THREAD

**Issue by lukaseder** [cockroachdb/cockroach#104083]
**Describe the solution you'd like**

For increased PostgreSQL compatibility, it would be useful to have user defined functions be listed in `INFORMATION_SCHEMA.ROUTINES` and `PARAMETERS`:

```sql
create function f (i text) returns text as $$ select i $$ language sql;
select * from information_schema.routines;
```

This just produces an empty result.

**Describe alternatives you've considered**

I can obviously reverse engineer `pg_catalog.pg_proc`:

```sql
select * from pg_catalog.pg_proc where proname = 'f'
```

But I find that table much less user friendly than the `INFORMATION_SCHEMA` one.

**Additional context**

This is for jOOQ source code generation: https://github.com/jOOQ/jOOQ/issues/13947

Jira issue: CRDB-28347

Epic CRDB-27601

**Comment by lukaseder** [comment]
The workaround is probably to copy paste the PostgreSQL definition of the views and inline those wherever `ROUTINES` and `PARAMETERS` are referenced:
https://github.com/postgres/postgres/blob/master/src/backend/catalog/information_schema.sql

**Comment by haquem1** [comment]
@lukaseder I'd like to give this a shot. Just getting started in OSS and looking to level up my SQL foundational skills for data platforms!
