### ISSUE TITLE
TestDockerCLI_test_demo_global/test_demo_global.tcl/runMode=docker timed out

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#104097]
See flake here [TestDockerCLI_test_demo_global/test_demo_global.tcl/runMode=docker](https://teamcity.cockroachdb.com/viewLog.html?buildId=10313689&buildTypeId=Cockroach_BazelEssentialCi#testNameId7323311535510811050)

Jira issue: CRDB-28353

**Comment by rafiss** [comment]
Could be related to https://github.com/cockroachdb/cockroach/issues/99768

**Comment by rafiss** [comment]
https://github.com/cockroachdb/cockroach/issues/99768 was resolved, and interacts with this test, so closing to see if the flake is gone.
