### ISSUE TITLE
storage: potential anomaly when txn timestamp is bumped by ts cache

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#10401]
- client starts txn at ts=1
- client writes and applyTimestampCache bumps the write to ts=2
- client receives no response with its request, keeps thinking ts=1 is the
  current timestamp
- client commits at ts=1
- one of its writes is at ts=2, and there is no correct way of resolving the
  situation; either the write is lost or it commits, invalidating a prior read.

Happens in tests in `AdminSplit` transactions.

**Comment by tschottdorf** [comment]
See #10402 on repro.

**Comment by dianasaur323** [comment]
@petermattis not sure if this is still an issue, but assigning to you for now!

**Comment by petermattis** [comment]
With the following patch:

```diff
diff --git a/pkg/storage/replica.go b/pkg/storage/replica.go
index 3c48d9f..50b3a0e 100644
--- a/pkg/storage/replica.go
+++ b/pkg/storage/replica.go
@@ -2258,7 +2258,7 @@ func (r *Replica) tryExecuteWriteBatch(
                                        // AdminSplit transactions. Very bad.
                                        //
                                        // See #10401.
-                                       log.Warningf(ctx, "assertion failed: transaction updated by "+
+                                       log.Fatalf(ctx, "assertion failed: transaction updated by "+
                                                "timestamp cache, but transaction returned in response; "+
                                                "updated timestamp would have been lost (recovered): "+
                                                "%s in batch %s", ba.Txn, ba,
```

`make stress PKG=./storage/ TESTS=TestReplicaTimestampCacheBumpNotLost` ran for 23m without failure. Reassigning to @spencerkimball who has a deeper knowledge of anomalies like this. Perhaps something was fixed in this area such as our addition of ambiguous results.

**Comment by spencerkimball** [comment]
I don't believe this should ever be an issue both with changes made around what we're allowed to return due to `AmbiguousResultErrors` and also changes for prop-eval-kv. I'm submitting a change to turn this into a fatal assertion.
