### ISSUE TITLE
TestActiveRecord flaked on master

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#104098]
See flake here https://teamcity.cockroachdb.com/viewLog.html?buildId=10313689&buildTypeId=Cockroach_BazelEssentialCi

Jira issue: CRDB-28354

**Comment by Dedej-Bergin** [comment]
I hit this issue again:

https://github.com/cockroachdb/cockroach/actions/runs/8745739841/job/24001320901

**Comment by XiaochenCui** [comment]
> See flake here https://teamcity.cockroachdb.com/viewLog.html?buildId=10313689&buildTypeId=Cockroach_BazelEssentialCi
> 
> Jira issue: [CRDB-28354](https://cockroachlabs.atlassian.net/browse/CRDB-28354)

hi, @msbutler 
the teamcity link appears 404

**Comment by rimadeodhar** [comment]
Closing as stale.
