### ISSUE TITLE
demo: demo with global hangs when using the latest build

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#104175]
Demo with `--global` hangs when using the latest build. It will not start and must be manually quit:

```sql ./cockroach demo --global --nodes 9 --no-example-database --insecure```
```
./cockroach version
Build Tag:        v23.1.0-alpha.8-dev
Build Time:
Distribution:     CCL
Platform:         darwin amd64
Go Version:       go1.19.4
C Compiler:       Apple LLVM 14.0.3 (clang-1403.0.22.14.1)
Build Commit ID:
Build Type:
```
I think this has to do with the `--global` flag as the following does work ```./cockroach demo --nodes 9 --no-example-database --insecure```
However, this same statement works fine on 23.1.2.

Jira issue: CRDB-28388

**Comment by rafiss** [comment]
This is working now; closing.
