### ISSUE TITLE
MODIFYCLUSTERSETTING should only allow view of sql.defaults.* 22.2+

### ISSUE THREAD

**Issue by data-matt** [cockroachdb/cockroach#104156]
**Is your feature request related to a problem? Please describe.**
Previously we asked to make the 22.2+ MODIFYCLUSTERSETTING the same as 22.1.

I guess the description from the previous ticket didn't make clear that, we don't want users to be able to view or read cluster settings outside of sql.defaults.*

Please adjust sql.auth.modify_cluster_setting_applies_to_all.enabled

**Describe the solution you'd like**
Only allow users to see the settings in sql.defaults.* 

**Describe alternatives you've considered**
At the minimum we can discuss hiding the license key from the cluster settings.

**Additional context**
[Add any other context or screenshots about the feature request here.
](https://github.com/cockroachdb/cockroach/issues/96172)

Jira issue: CRDB-28376

**Comment by rafiss** [comment]
I found that v23.1 also has a similar bug. The MODIFYSQLCLUSTERSETTING that was added in https://github.com/cockroachdb/cockroach/pull/97521 will also need to be fixed. Example:
```
root@localhost:26257/defaultdb> create user testuser;
CREATE ROLE

Time: 50ms total (execution 50ms / network 0ms)

root@localhost:26257/defaultdb> grant system modifysqlclustersetting to testuser;
GRANT

Time: 32ms total (execution 32ms / network 0ms)

root@localhost:26257/defaultdb> set role testuser;
SET

Time: 2ms total (execution 2ms / network 0ms)

root@localhost:26257/defaultdb> show cluster settings;
-- this shows all the cluster settings, but it should only show the sql.defaults ones.
```

**Comment by Santamaura** [comment]
@rafiss do we have a way to check if a user has a specific privilege ignoring if they have elevated access (e.g. admin)? In order to do this, we would need to filter `crdb_internal.cluster_settings` rows if (in 23.1+) the user has specifically `MODIFYSQLCLUSTERSETTING` or (in 22.2) if the user has specifically `MODIFYCLUSTERSETTING`. Maybe I missed it but I don't see a way to currently check this.

**Comment by Santamaura** [comment]
Eh I guess we can throw in a check to see if they are admin as well

**Comment by thtruo** [comment]
Had separate convos offline, but adding back for continuity - 

In the case where a non-admin user has `MODIFYSQLCLUSTERSETTING` and `VIEWCLUSTERSETTING`, that user will be able to see all cluster settings but only edit `sql.default.*` settings.

If an administrator wants to prevent this user from viewing non `sql.default.*` settings, then they would simply remove `VIEWCLUSTERSETTING` for this user.

**Comment by rafiss** [comment]
re-opening until the 23.1 backport is done
