### ISSUE TITLE
ccl/sqlproxyccl: TestACLWatcher flaked on 23.1

### ISSUE THREAD

**Issue by DrewKimball** [cockroachdb/cockroach#104105]
See flake here: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/10314192?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true&logFilter=debug

Jira issue: CRDB-28356

**Comment by DrewKimball** [comment]
cc @jaylim-crl for triage

**Comment by jaylim-crl** [comment]
Thanks - will take a look.

**Comment by bananabrick** [comment]
Another flake here: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsGcpLinuxX8664BigVm_CclUnitTests/10436666?showRootCauses=false&expandBuildChangesSection=true&expandBuildTestsSection=true

**Comment by rytaft** [comment]
This happened to me again: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/10653101?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

**Comment by jaylim-crl** [comment]
I look into this again, and I managed to reproduce this locally on my linux machine. Will put up a fix shortly.
