### ISSUE TITLE
distsql: DatumToEncDatum() should be replaced/merged with SetDatum()

### ISSUE THREAD

**Issue by arjunravinarayan** [cockroachdb/cockroach#10411]
`DatumToEncDatum()` simply throws an error when it encounters a `Datum` of type `DNull`, as the correct type cannot be inferred from the raw `Datum`. In that case, the `EncDatum`s type must be inferred through some other fashion, and the resulting code looks almost identical to `EncDatum.SetDatum()`. Therefore, replace all uses of `DatumToEncDatum` with `SetDatum()`, and merge the two functions.

cc @irfansharif @RaduBerinde: if I'm missing something here, please let me know.

**Comment by RaduBerinde** [comment]
By the way, we may want to change `SetDatum/SetEncoded/SetFromBuffer` to return an `EncDatum` insead of being mutators. Seems like it would make things more clear (right now it's not obvious that if you call both `SetDatum` and `SetEncoded`, only the last one matters).

**Comment by irfansharif** [comment]
I think you mean `Datum` of type `TypeNull` (`pkg/sql/parser/datum.go`).
also note that `EncDatum.SetDatum()` currently has the signature `SetDatum(ColumnType_Kind, parser.Datum)` with `TypeNull` not being a `ColumnType` (`pkg/sql/parser/col_types.go`), `EncDatum.Type` is a `ColumnType_Kind`.

I do have a question though, is it ever the case that `EncDatum.Datum` is of a type `TypeNull`?

**Comment by RaduBerinde** [comment]
Right, `DNull` is a datum of type `TypeNull`.

No, an `EncDatum` must always have a well-defined type (even if it is null).

One reason null is not an EncDatum type is that a distsql stream assumes all "rows" (EncDatum tuples) to have the same types - we only send out the types of the first row. So we can't have different types on different rows.

**Comment by irfansharif** [comment]
@arjunravinarayan: any updates on this? running into some of the same issues mentioned here and am thinking to remove `DatumToEncDatum()` as you suggested, unless you've already done the same.

**Comment by arjunravinarayan** [comment]
This is done in #10550. I can extract the relevant code for you in a
separate PR ASAP if you would like. Otherwise should be merged within a day
or so.

**Comment by irfansharif** [comment]
cool! and no, no worries I'll just cherry-pick/rebase for the time being. thanks.
