### ISSUE TITLE
kvflowcontrol,kvserver: fast follow-on work

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#104154]
**Is your feature request related to a problem? Please describe.**

This issue tracks deferred work from PRs that introduced replication admission control (https://github.com/cockroachdb/cockroach/issues/95563, https://github.com/cockroachdb/cockroach/pull/98308). This list is sourced partly using checked-in TODOs (`$ rg "#95563" --before-context 4`).

- [x] https://github.com/cockroachdb/cockroach/issues/102683
- [x] ~Export metric to track total AddSST bandwidth, both proposed and applied (this was prototyped in [#93102](#93102), `addsstable.{proposal,application}_bytes`)~
  - The aggregated elastic flow tokens deducted metric works well as a substitute
- [x] https://github.com/cockroachdb/cockroach/issues/105508
  - [ ] ~[TODO](https://github.com/irfansharif/cockroach/blob/230309.integrate-kvflowcontrol/pkg/kv/kvserver/kvflowcontrol/kvflowcontrol.go#L314): Eliminate heap allocation in `kvflowcontrol.ContextWithMeta`~
  - [ ] [TODO](https://github.com/irfansharif/cockroach/blob/230309.integrate-kvflowcontrol/pkg/util/admission/work_queue.go#L559-L562): Write microbenchmark for allocation profile of `WorkQueue.Admit`, and optionally improve it.
- [x] [TODO](https://github.com/irfansharif/cockroach/blob/230309.integrate-kvflowcontrol/pkg/kv/kvserver/kvflowcontrol/kvflowcontrol.go#L64-L68): Eliminate OOM possibility when `kvadmission.flow_control.mode = apply_to_elastic`. 
- [x] [TODO](https://github.com/irfansharif/cockroach/blob/94aa8906e8f5ac62a929ebecefc43f818e5a6978/pkg/kv/kvserver/raft_transport.go#L770-L774): Add a byte/count limit to how many flow token dispatches can be added to a raft message
- [x] Surface some kvflowcontrol metrics in the admin UI.
- [ ] Address remaining performance cuts identified in #109833.
- [ ] Dump vtable state in debug.zip
- [ ] Don't use flow tokens (or AC really) for lease requests (see [this comment](https://github.com/cockroachdb/cockroach/pull/104026#issuecomment-1568254247)).
- [ ] Don't use flow tokens or AC when writing to system tables (especially around writes to cluster settings)
- [ ] [TODO](https://github.com/irfansharif/cockroach/blob/230309.integrate-kvflowcontrol/pkg/util/admission/work_queue.go#L627-L635): Fix over-admission due to AC token acquisition fast path.
- [ ] [TODO](https://github.com/irfansharif/cockroach/blob/94aa8906e8f5ac62a929ebecefc43f818e5a6978/pkg/kv/kvserver/kvflowcontrol/kvflowcontrol.go#L238-L246): Remove `O(local stores)` lookup for flow control handles.

Epic [CRDB-25348](https://cockroachlabs.atlassian.net/browse/CRDB-25348)

Jira issue: CRDB-28374

Epic CRDB-25348

**Comment by aadityasondhi** [comment]
Discussed offline with @sumeerbhola, closing this issue as the remaining tweaks here are those we don't want to invest time into.
