### ISSUE TITLE
Run descriptor validation checks periodically to find any corrupted descriptors and provide logs/alerts or auto-repair

### ISSUE THREAD

**Issue by dikshant** [cockroachdb/cockroach#104266]
We should automatically run debug doctor or something equivalent periodically in CRDB itself. Should the result of this uncover any descriptor corruption, we should notify the users with proper logging or alerts. For known cases of corruption, we should also investigate if it is feasible to automatically apply a fix.

Jira issue: CRDB-28437

Epic CRDB-28665

**Comment by rafiss** [comment]
We may need to rescope this as a higher-level epic, since making the checks work against older binaries needs some extra thought.

**Comment by ecwall** [comment]
I think we can automate this in patches by keeping track of what fixes we ran in a new table. It would be similar to upgrades, but the order would not matter.

**Comment by rafiss** [comment]
Another approach here is to set up a background task that runs once a day or so, and checks the `crdb_internal.invalid_objects` table. Then we can have it update a metric that counts the number of rows in the table; if the metric goes above 0, it should show up in our SLI reviews. It can also log the `invalid_objects` as well.

**Comment by rafiss** [comment]
I think we can close this ticket now that https://github.com/cockroachdb/cockroach/pull/108559 is resolved. @dikshant do you agree?

**Comment by chrisseto** [comment]
Mind reader. I was just about to ask the same question. I'd vote for closing this and we can open a new one if we want to alert end users or add in auto-repair.

Do we think there will be any situations where we'd prompt the user about an opt-in repair that we wouldn't feel confident in applying automatically?

**Comment by dikshant** [comment]
Thanks for the work on this. This is good to close!
