### ISSUE TITLE
creating a docker data only container

### ISSUE THREAD

**Issue by cloudmode** [cockroachdb/cockroach#1042]
I've been trying to create a docker data only container, in order to be able to use the docker volumes-from option, so I can re-use data between tests. The problem I'm running into is that when the certs are initialized in the origin data container, subsequent sharing of the container results in TLS erros.

The origin docker data container is created using:

docker run -t -i -p 8080:8080  -v /roach/db -v /cockroach/certs --name roachdb cockroachdb/cockroach shell

 and the following commands are executed inside the shell before the container is suspended:

./cockroach cert create-ca
./cockroach cert create-node 127.0.0.1 localhost $(hostname)
./cockroach init --stores=ssd=/roach/db

subsequent containers are started with:

docker run -t -i -p 8080:8080  --volumes-from=roachdb cockroachdb/cockroach shell

and in the shell

./cockroach start --stores=ssd=/roach/db --gossip=self:// &

result in errors:

L="INFO" T="5/15 19:15:28.783" F="range.go:921" Msg="gossiping first range from store 1, range 1"
L="INFO" T="5/15 19:15:28.783" F="node.go:386" Msg="node connected via gossip and verified as part of cluster \"a6ba9337-c7ca-476a-9c67-65ca6d39979a\""
L="INFO" T="5/15 19:15:28.783" F="node.go:249" Msg="Started node with [[ssd]=/roach/db] engine(s) and attributes []"
L="INFO" T="5/15 19:15:28.783" F="server.go:174" Msg="starting https server at 7a4b39dc7ded:8080"
L="INFO" T="5/15 19:15:38.785" F="client.go:132" Msg="x509: certificate is valid for localhost, 061bb1c8d944, not 7a4b39dc7ded"
L="INFO" T="5/15 19:15:38.785" F="retry.go:101" Msg="client 7a4b39dc7ded:8080 connection failed; retrying in 1s"
I0515 19:15:38.796676      11 server.go:1775] http: TLS handshake error from 172.17.0.41:42693: remote error: bad certificate

Am I going the wrong way on this?

**Comment by MBerhault** [comment]
You need to make sure the hostname or IP of the interface you are listening
on is part of the "create-node" command.
You also need to make sure the dns name or IP used to connect to it from
other nodes or clients is listed.

For a simple example of multi-node docker setup on a single machine, look
at cockroachdb/cockroach/run/local_cluster.sh
What we do there is specify --addr=<hostname-N> when starting the node, and
pass <hostname-N> to create-cert for all N nodes.

This way, we can use a data container that contains certs valid for all
hosts. Obviously, a real deployment will only want to share the CA and have
different server certs for each node, but in this case it's probably fine.

**Comment by cloudmode** [comment]
Excellent. Thanks. That got me going. I changed the create-node command in the data volume to:

./cockroach cert create-node 127.0.0.1 localhost

which is all I need for a single-node test.

**Comment by cloudmode** [comment]
oh, and I added the --addr argument to start:

./cockroach start --stores=ssd=/roach/db --addr=localhost:8080 --gossip=self:/

**Comment by tschottdorf** [comment]
Looks like this is resolved. If not, please yell at me.
