### ISSUE TITLE
automatically run debug doctor periodically on Cockroach Cloud clusters

### ISSUE THREAD

**Issue by dikshant** [cockroachdb/cockroach#104267]
We should run debug doctor periodically on CockroachCloud and surface any clusters with descriptor corruption issues. This will help us root out clusters with corruption earlier and catch them before they get a chance to break upgrades.

Some items to check before rolling it out:
- [ ] Figure out an appropriate schedule.
- [ ] Confirm that running debug doctor doesn't affect foreground traffic. Maybe the job could skip running `doctor` if the cluster load is high.

Jira issue: CRDB-28438

**Comment by rafiss** [comment]
Closing this in favor of CC-24803 and CRDB-29106, since this is being tracked in Jira now.
