### ISSUE TITLE
util/parquet: support required repetitions

### ISSUE THREAD

**Issue by jayshrivastava** [cockroachdb/cockroach#104279]
By default the library treats all columns as nullable, even when they are not. It would be ideal to treat columns as not nullable if specified. 

Jira issue: CRDB-28443

**Comment by miretskiy** [comment]
I'm not sure how important it is to support this feature.  On the one hand: yes, if the database says "not null", it'd be nice
to say that.  However, database schema can change; constraints can be dropped.  Having all fields nullable in parquet
(i.e. optional) is actually a good thing -- it's sort of similar to how protocol buffers should evolve over time -- make all fields optional.  If the field is not optional, enforce in code.

**Comment by amruss** [comment]
Closing this. What we do with avro is to treat every field as optional, this allows flexibility over time
