### ISSUE TITLE
distsql: Set operations (UNION, INTERSECT, EXCEPT)

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#10432]
Implementation of a processor "core" type from #7587. 
Set operations would include `UNION`, `UNION ALL`, `INTERSECT`, `INTERSECT ALL`, `EXCEPT`, `EXCEPT ALL`.

This processor, like join processors, would have two input streams and one output stream. Some of existing processor core type implementations under `pkg/sql/distsql` and spec definitions in `pkg/sql/distsql/processors.proto` can be used for reference.

**Comment by a6802739** [comment]
@irfansharif , I could have a look on it.

**Comment by irfansharif** [comment]
@a6802739: go for it! let me know if you need any pointers.

**Comment by a6802739** [comment]
@irfansharif , okay, thanks a lot. At first, I'll have a see on it.

**Comment by a6802739** [comment]
@irfansharif,  should I add a `Message SetSpec` in `pkg/sql/distsql/processors.proto`, and generate a new struct `Seter` under `pkg/sql/distsql`?

how could I associate struct `Seter` to the `input stream` and `out stream`, And how could I specify the input `colum` we are going to process?
should I just implement the interface `processor`?

**Comment by irfansharif** [comment]
hey @a6802739,

for the spec definition going with `SetSpec` would be best, this would internally specify which operation to apply (`UNION, INTERSECT, EXCEPT`). As for the struct itself going with a simple `type set struct { ... }` should suffice (under `pkg/sql/distsql/set.go`). 

> And should I just translate `sql/union.go` to `distsql/union.go`?

I would the implementations would function similarly but keep in mind under `distsql` we're operating under the abstraction that we simply operate on _streams_. There's also a lot of additional baggage in `sql/union.go` given our current structure constructing a `planNode` to evaluate queries which we don't need to satisfy here. 

As far as your questions concerning `aggregator.go`, feel free to ping me on [gitter](https://gitter.im/cockroachdb/cockroach) @irfansharif and will be happy to walk you through it there just for the sake of not polluting this thread. for reference I would advise you to look at `distinct.go` as opposed to `aggregator.go`, it's more pertinent to `Set` as compared to `aggregator` responsible for grouping aggregators (`SUM`, `AVG`, etc).

**Comment by irfansharif** [comment]
cc @arjunravinarayan, given you expressed interest in taking this on as well.

**Comment by RaduBerinde** [comment]
This issue has two parts:
 - physical processor implementation for set operations
 - physical planning for set operations

The first would be better as a one-off project for someone who is not familiar with distsql. The latter is not very difficult but it requires understanding a lot of the existing planning code.

**Comment by arjunravinarayan** [comment]
Hey @a6802739, what's your status on this? I'm thinking of taking this one on since it's been sitting here for a while, unless you've already done some work on this.

**Comment by dianasaur323** [comment]
@arjunravinarayan looks like you've already done a lot of work towards implementing SET processors. Do you think supporting it in DistSQL by 1.0 is still possible?

**Comment by arjunravinarayan** [comment]
Yes, we can support it in 1.0.

**Comment by cuongdo** [comment]
is this still making it into 1.1?

**Comment by arjunravinarayan** [comment]
Yes, this and merge join planning are next up after I merge the external storage PR.

**Comment by vivekmenezes** [comment]
I believe we're punting on some of this right? @arjunravinarayan feel free to not assign a milestone to this issue.

**Comment by asubiotto** [comment]
Just a note that there is some demand for this: there's a customer that's running into issues running `UNION` through local sql (memory blow-up) that would be resolved if we supported `UNION` in distsql.

**Comment by RaduBerinde** [comment]
Union in particular should be a very easy thing to add (just join multiple streams).

**Comment by RaduBerinde** [comment]
Actually, UNION can be implemented by UNION ALL (merging streams) plus a DISTINCT stage.

**Comment by arjunravinarayan** [comment]
We also have to investigate and add tests when considering the treatment of NULLs, as raised by #20090.

**Comment by arjunravinarayan** [comment]
I did some spelunking, and [Markus Winand](http://modern-sql.com/concept/null#distinct) points out that NULLs in group operations are supposed to sort into a single group, and that the SQL:2016 standard has a longer section on this, that we should ensure we are in compliance with (SQL:2016-2: §4.1.5 and SQL:2016-2: §9.12).

**Comment by solongordon** [comment]
`UNION` and `UNION ALL` are complete. Holding off on `INTERSECT` and `EXCEPT` for now to work on higher priority items.

**Comment by vivekmenezes** [comment]
abhishek has been assigned this issue to complete the work on INTERSECT and EXCEPT
