### ISSUE TITLE
roachtest: non-deterministic NPE in test_runner results in panic

### ISSUE THREAD

**Issue by srosenberg** [cockroachdb/cockroach#104385]
The following sequence of events triggers a nil pointer dereference, resulting in panic, consequently crashing `roachtest`, leaving any running clusters behind,

- a selected test and an existing cluster are compatible, allowing the test to _reuse_ the cluster
- an attempt to reuse the cluster (`c.Wipe`) fails
- an attempt to create a fresh cluster using `testToRun.alloc`
- fresh cluster creation fails, resulting in `cfg.alloc.Release()` where `cfg.alloc == nil` [1]

Below is the stacktrace yielding `panic`,

```
runtime error: invalid memory address or nil pointer dereference
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  |   GOROOT/src/runtime/panic.go:884
  | runtime.panicmem
  |   GOROOT/src/runtime/panic.go:260
  | runtime.sigpanic
  |   GOROOT/src/runtime/signal_unix.go:835
  | github.com/cockroachdb/cockroach/pkg/util/quotapool.(*IntAlloc).Release
  |   github.com/cockroachdb/cockroach/pkg/util/quotapool/intpool.go:56
  | main.(*clusterFactory).newCluster
  |   main/pkg/cmd/roachtest/cluster.go:1139
  | main.defaultClusterAllocator.func1
  |   main/pkg/cmd/roachtest/test_runner.go:450
  | main.(*testRunner).runWorker
  |   main/pkg/cmd/roachtest/test_runner.go:664
  | main.(*testRunner).Run.func1
  |   main/pkg/cmd/roachtest/test_runner.go:304
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  |   github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470
  | runtime.goexit
  |   GOROOT/src/runtime/asm_amd64.s:1594
```

In case of cluster reuse, `testToRun.alloc` is nil, which is what gets assigned into `cfg.alloc` (used by `newCluster`). The bug has been lurking for > 1 year, at least since the change in [2]. Somewhat surprising, we haven't seen it in the wild until a few days ago; that's more than 1000 (nightly) runs, which is fairly low to trigger the above conditions.

[1] https://github.com/cockroachdb/cockroach/blob/530e2ef6d3e974202b2015c22c7ea9eb1c20a29e/pkg/cmd/roachtest/cluster.go#L1145
[2] https://github.com/cockroachdb/cockroach/pull/73706

Jira issue: CRDB-28497

**Comment by renatolabs** [comment]
Some real-world occurrences:

release-23.1: https://teamcity.cockroachdb.com/viewLog.html?buildId=11485027&buildTypeId=Cockroach_Nightlies_RoachtestNightlyGceBazel

master: https://teamcity.cockroachdb.com/viewLog.html?buildId=11485001&buildTypeId=Cockroach_Nightlies_RoachtestNightlyGceBazel

**Comment by renatolabs** [comment]
`test_runner.go` is an intense file, took me a while to understand what's going on. I _think_ there might be another bug with cluster reuse here:

https://github.com/cockroachdb/cockroach/blob/a17ec11f0bfe2cf752366d8f92c597313428a822/pkg/cmd/roachtest/test_runner.go#L686-L687

I don't see where "above" the non-reusable cluster would have been destroyed.

**Comment by srosenberg** [comment]
> `test_runner.go` is an intense file, took me a while to understand what's going on. I _think_ there might be another bug with cluster reuse here:
> 
> https://github.com/cockroachdb/cockroach/blob/a17ec11f0bfe2cf752366d8f92c597313428a822/pkg/cmd/roachtest/test_runner.go#L686-L687
> 
> I don't see where "above" the non-reusable cluster would have been destroyed.

I think it gets destroyed at the start of the iteration; look for `ReusePolicyNone`.

**Comment by renatolabs** [comment]
`ReusePolicyNone` deals with tests that explicitly ask for clusters to not be reused; `getTestToRun` will destroy the cluster, but I'm talking about this scenario:

* c1 is the cluster a certain worker is using.
* `getTestToRun` returns a test that _is_ compatible with c1 (`canReuseCluster: true`).
* We try to reuse the cluster by wiping it; it fails.
* We create a new cluster c2, and that succeeds.

In this scenario, I don't see where c1 is destroyed.

**Comment by srosenberg** [comment]
> In this scenario, I don't see where c1 is destroyed.

You're right, I don't see it either. It looks like a leak since `c` gets reassigned once a fresh cluster is successfully created. The invariant that we'd like to hold at all times: `c != nil => F(cluster_destroy) && c = nil => F(cluster_alloc)`, where `F` is borrowed from LTL [1], denoting "finally some predicate holds". I don't see how this invariant is maintained. In the refactoring PR [2], which I really need to revisit (hopefully soon 🤞), this case is handled correctly [2].

[1] https://en.wikipedia.org/wiki/Linear_temporal_logic
[2] https://github.com/cockroachdb/cockroach/pull/101814/files#diff-1e3ec1fc5bade2df4b8681c44959be2a390f703839f30a979da98f963769c9fcR873-R875
