### ISSUE TITLE
backupccl: tenant restore doesn't handle 22.2 style manifests

### ISSUE THREAD

**Issue by stevendanna** [cockroachdb/cockroach#104308]
**Describe the problem**

In 23.1 the canonical field for the ID and DataState of a tenant moved, with the old fields being renamed to DeprecatedID and DeprecatedDataState.

While we updated the code that writes the manifest. We did not update all of the code that reads the manifest. As a result, code reading the manifest during RESTORE or SHOW BACKUP would attempt to restore tenants with an ID of 0.

Jira issue: CRDB-28451

**Comment by adityamaru** [comment]
Closing since the fix is merged
