### ISSUE TITLE
sqlstats: explore alternatives to cleaning up sql stats tables

### ISSUE THREAD

**Issue by xinhaoz** [cockroachdb/cockroach#104330]
Currently we have 2 ways in which the sql stats tables get cleaned up:
- Through the automated cleanup jobs, which run delete stmts for the oldest entries based on the row limits of each table
- Resetting sql stats either through UI or cli (`crdb_internal.reset_sql_stats()`) - truncates each table

We should explore more flexible options to cleanup or compact sql stats when users would like to shrink their tables while still retaining some data.

Related issue(s):

- https://github.com/cockroachdb/cockroach/issues/80523

Jira issue: CRDB-28471

**Comment by maryliag** [comment]
No longer a priority
