### ISSUE TITLE
multi-tenant: benchmark single-tenant vs shared-process multi-tenant

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#104379]
In 23.1 in #87610 we ran some sanity checks that the performance of shared-process multi-tenant (aka UA) doesn't regress significantly when comparing against single-tenant. This issue tracks performing a more rigorous analysis as well as setting up roachtest/roachperf to track the performance of UA on a regular basis.

Jira issue: CRDB-28494
Epic: CRDB-26687

----

Using ae5a1cba0274bbd864e8177e70c062512c037e15.

Comparison of `pkg/bench` benchmarks of single node single-tenant vs single pod shared-process multi-tenant is [here](https://gist.github.com/yuzefovich/1b8d9b4d11663c3d209735bac05fd0ee) (memory [diff](https://gist.github.com/yuzefovich/48fe6dae4e8b76341c995157923b8f63)). It shows that there are some regressions, mostly around 10% but up to 30% in some cases.

`tpccbench/nodes=3`:
<details>
<summary>shows about 5% hit (avg over 10 runs)</summary>

`tpccbench/nodes=3/cpu=4`:
- single-tenant: **577.5**
- shared-process multi-tenant: **550**

`tpccbench/nodes=3/cpu=16`:
- single-tenant: **2083.5**
- shared-process multi-tenant: **1981.5**

(Note that I tried both secure and insecure multi-tenant configs, but there was no significant difference.)
</details>

`kv0`
<details>
<summary>regression around 2-3% (avg over 10 runs)</summary>

single-tenant vs shared-process multi-tenant
```
kv0/enc=false/nodes=1: 6930.7 vs 6761.3 
kv0/enc=false/nodes=1/cpu=32: 18488.0 vs 18087.6
kv0/enc=false/nodes=3: 10804.5 vs 10411.9
kv0/enc=false/nodes=3/cpu=32: 30554.9 vs 30331.2
```

</details>

`kv95`
<details>
<summary>regression around 6-8% (avg over 10 runs)</summary>

single-tenant vs shared-process multi-tenant
```
kv95/enc=false/nodes=1: 10962.3 vs 10170.6
kv95/enc=false/nodes=1/cpu=32: 36410.4 vs 33477.7
kv95/enc=false/nodes=3: 19645.2 vs 18538.0
kv95/enc=false/nodes=3/cpu=32: 62703.0 vs 58006.3
```

</details>

`multitenant/tpch` (single node TPCH):
<details>
<summary>effectively no difference (avg over 25 runs)</summary>

```
Q1:	before: 6.29s	after: 6.29s	 0.06%
Q2:	before: 4.25s	after: 4.22s	 -0.69%
Q3:	before: 4.43s	after: 4.42s	 -0.19%
Q4:	before: 1.45s	after: 1.45s	 -0.25%
Q5:	before: 2.81s	after: 2.85s	 1.39%
Q6:	before: 7.67s	after: 7.60s	 -0.84%
Q7:	before: 7.33s	after: 7.08s	 -3.46%
Q8:	before: 1.11s	after: 1.14s	 2.49%
Q9:	before: 9.03s	after: 9.42s	 4.38%
Q10:	before: 2.00s	after: 1.99s	 -0.60%
Q11:	before: 1.05s	after: 1.08s	 2.35%
Q12:	before: 8.06s	after: 8.09s	 0.37%
Q13:	before: 2.34s	after: 2.35s	 0.29%
Q14:	before: 0.75s	after: 0.75s	 0.05%
Q15:	before: 4.05s	after: 4.07s	 0.43%
Q16:	before: 0.98s	after: 0.98s	 0.82%
Q17:	before: 0.29s	after: 0.28s	 -1.12%
Q18:	before: 4.14s	after: 4.07s	 -1.47%
Q19:	before: 0.53s	after: 0.53s	 1.14%
Q20:	before: 17.75s	after: 17.31s	 -2.49%
Q21:	before: 7.45s	after: 7.05s	 -5.31%
Q22:	before: 0.66s	after: 0.63s	 -3.41%
```
</details>

`tpchvec` (3 node TPCH):
<details>
<summary>effectively no difference, (avg over 50 runs) on da4a10b178c95cf68467e13ba4c5cab4a81d60ec</summary>

```
Q1:	before: 2.86s	after: 2.95s	 3.09%
Q2:	before: 2.95s	after: 2.95s	 -0.20%
Q3:	before: 2.29s	after: 2.19s	 -4.10%
Q4:	before: 1.56s	after: 1.59s	 1.61%
Q5:	before: 2.35s	after: 2.31s	 -1.92%
Q6:	before: 4.00s	after: 3.97s	 -0.88%
Q7:	before: 5.01s	after: 4.98s	 -0.52%
Q8:	before: 1.01s	after: 1.00s	 -1.03%
Q9:	before: 5.08s	after: 4.81s	 -5.29%
Q10:	before: 1.92s	after: 1.97s	 2.94%
Q11:	before: 0.85s	after: 0.85s	 -0.54%
Q12:	before: 4.10s	after: 3.91s	 -4.49%
Q13:	before: 0.96s	after: 0.99s	 2.80%
Q14:	before: 0.42s	after: 0.42s	 0.24%
Q15:	before: 2.28s	after: 2.25s	 -1.30%
Q16:	before: 0.83s	after: 0.78s	 -5.68%
Q17:	before: 0.22s	after: 0.22s	 0.63%
Q18:	before: 1.81s	after: 1.79s	 -0.86%
Q19:	before: 0.44s	after: 0.44s	 0.96%
Q20:	before: 8.46s	after: 9.52s	 12.55%
Q21:	before: 4.55s	after: 4.39s	 -3.63%
Q22:	before: 0.52s	after: 0.50s	 -3.97%
```
</details>

**Comment by yuzefovich** [comment]
I spent some time trying to find the reason for the [regression](https://gist.github.com/yuzefovich/1b8d9b4d11663c3d209735bac05fd0ee) on end-to-end micro-benchmarks but came up empty-handed (these benchmarks are so quick that CPU profiles don't show any meaningful difference). It also seems like the regression gets smaller (in relative terms - in percentages) the longer the operation takes. In other words, most double-digit regressions are on operations that take 1ms or less whereas for operations that take longer, the regressions are mostly in single-digits. Perhaps this is due to some fixed internal overhead of the shared-process multi-tenant (e.g. some proxying or additional checks)?

@stevendanna @knz @ajstorm thoughts? Is it worth for me to continue looking for the root cause of the perf hit (my intuition says "no" given that on macrobenchmarks the regression is in single-digits)? Please take a look at the numbers in the issue description. Are there other benchmarks you'd be interested to see?

**Comment by ajstorm** [comment]
Sorry for the delay in responding.  As mentioned in the weekly today, I think we're good putting this aside for now and deciding whether or not to revisit later in the cycle.  Before we do that though, it would be good to get a multi-node TPC-H result.

**Comment by yuzefovich** [comment]
Thanks for the suggestion (I also thought about doing this but forgot).

As it turns out, there is a very noticeable perf difference (mostly negative) on 3 node cluster when running TPCH (avg over 50 runs of `tpchvec` roachtest):
```
Q1:	before: 2.97s	after: 3.38s	 13.92%
Q2:	before: 2.98s	after: 4.91s	 64.88%
Q3:	before: 2.57s	after: 3.57s	 39.24%
Q4:	before: 1.65s	after: 1.02s	 -38.59%
Q5:	before: 2.46s	after: 1.94s	 -20.93%
Q6:	before: 4.20s	after: 4.03s	 -4.25%
Q7:	before: 5.19s	after: 4.71s	 -9.23%
Q8:	before: 1.01s	after: 0.93s	 -7.46%
Q9:	before: 5.26s	after: 7.37s	 40.18%
Q10:	before: 1.97s	after: 1.59s	 -19.21%
Q11:	before: 0.87s	after: 0.82s	 -6.07%
Q12:	before: 4.24s	after: 3.87s	 -8.79%
Q13:	before: 1.06s	after: 1.82s	 72.05%
Q14:	before: 0.42s	after: 0.56s	 31.63%
Q15:	before: 2.33s	after: 2.13s	 -8.72%
Q16:	before: 0.84s	after: 0.90s	 7.56%
Q17:	before: 0.23s	after: 0.35s	 54.20%
Q18:	before: 1.80s	after: 2.12s	 17.50%
Q19:	before: 0.45s	after: 0.82s	 81.53%
Q20:	before: 9.21s	after: 12.05s	 30.82%
Q21:	before: 4.63s	after: 4.42s	 -4.45%
Q22:	before: 0.53s	after: 0.78s	 48.26%
```
The good news is that the hit can be partially mediated by the KV projection pushdown that I had been working on (the comparison is "single-tenant" vs "shared-process multi-tenant with pushdown enabled"):
```
Q1:	before: 2.97s	after: 3.12s	 5.31%
Q2:	before: 2.98s	after: 3.52s	 18.25%
Q3:	before: 2.57s	after: 2.82s	 9.74%
Q4:	before: 1.65s	after: 0.99s	 -40.42%
Q5:	before: 2.46s	after: 1.91s	 -22.38%
Q6:	before: 4.20s	after: 3.95s	 -6.04%
Q7:	before: 5.19s	after: 4.65s	 -10.39%
Q8:	before: 1.01s	after: 0.80s	 -20.12%
Q9:	before: 5.26s	after: 6.69s	 27.29%
Q10:	before: 1.97s	after: 1.59s	 -19.48%
Q11:	before: 0.87s	after: 0.81s	 -7.47%
Q12:	before: 4.24s	after: 3.78s	 -11.03%
Q13:	before: 1.06s	after: 1.65s	 56.67%
Q14:	before: 0.42s	after: 0.43s	 0.61%
Q15:	before: 2.33s	after: 2.09s	 -10.34%
Q16:	before: 0.84s	after: 0.79s	 -6.11%
Q17:	before: 0.23s	after: 0.24s	 5.51%
Q18:	before: 1.80s	after: 1.63s	 -9.50%
Q19:	before: 0.45s	after: 0.53s	 18.78%
Q20:	before: 9.21s	after: 11.35s	 23.23%
Q21:	before: 4.63s	after: 4.33s	 -6.37%
Q22:	before: 0.53s	after: 0.53s	 0.91%
```

<details>
<summary>Here is shared process MT: KV pushdown disabled vs KV pushdown enabled</summary>

```
Q1:	before: 3.38s	after: 3.12s	 -7.56%
Q2:	before: 4.91s	after: 3.52s	 -28.28%
Q3:	before: 3.57s	after: 2.82s	 -21.18%
Q4:	before: 1.02s	after: 0.99s	 -2.97%
Q5:	before: 1.94s	after: 1.91s	 -1.83%
Q6:	before: 4.03s	after: 3.95s	 -1.87%
Q7:	before: 4.71s	after: 4.65s	 -1.28%
Q8:	before: 0.93s	after: 0.80s	 -13.67%
Q9:	before: 7.37s	after: 6.69s	 -9.20%
Q10:	before: 1.59s	after: 1.59s	 -0.33%
Q11:	before: 0.82s	after: 0.81s	 -1.49%
Q12:	before: 3.87s	after: 3.78s	 -2.45%
Q13:	before: 1.82s	after: 1.65s	 -8.94%
Q14:	before: 0.56s	after: 0.43s	 -23.56%
Q15:	before: 2.13s	after: 2.09s	 -1.78%
Q16:	before: 0.90s	after: 0.79s	 -12.71%
Q17:	before: 0.35s	after: 0.24s	 -31.58%
Q18:	before: 2.12s	after: 1.63s	 -22.98%
Q19:	before: 0.82s	after: 0.53s	 -34.57%
Q20:	before: 12.05s	after: 11.35s	 -5.80%
Q21:	before: 4.42s	after: 4.33s	 -2.01%
Q22:	before: 0.78s	after: 0.53s	 -31.94%
```

</details>

<details>
<summary>Here is single tenant: KV pushdown disabled vs KV pushdown enabled</summary>

```
Q1:	before: 2.97s	after: 3.05s	 2.95%
Q2:	before: 2.98s	after: 2.78s	 -6.44%
Q3:	before: 2.57s	after: 2.43s	 -5.11%
Q4:	before: 1.65s	after: 1.63s	 -1.26%
Q5:	before: 2.46s	after: 2.42s	 -1.51%
Q6:	before: 4.20s	after: 4.08s	 -2.91%
Q7:	before: 5.19s	after: 5.12s	 -1.34%
Q8:	before: 1.01s	after: 0.97s	 -3.22%
Q9:	before: 5.26s	after: 5.15s	 -2.13%
Q10:	before: 1.97s	after: 1.96s	 -0.76%
Q11:	before: 0.87s	after: 0.86s	 -1.72%
Q12:	before: 4.24s	after: 4.18s	 -1.42%
Q13:	before: 1.06s	after: 1.07s	 1.27%
Q14:	before: 0.42s	after: 0.41s	 -2.93%
Q15:	before: 2.33s	after: 2.30s	 -1.31%
Q16:	before: 0.84s	after: 0.82s	 -1.84%
Q17:	before: 0.23s	after: 0.21s	 -6.73%
Q18:	before: 1.80s	after: 1.55s	 -14.08%
Q19:	before: 0.45s	after: 0.44s	 -2.27%
Q20:	before: 9.21s	after: 9.05s	 -1.70%
Q21:	before: 4.63s	after: 4.54s	 -1.86%
Q22:	before: 0.53s	after: 0.51s	 -3.21%
```

</details>

These numbers confirm suspicions that @stevendanna had that the distributed case could be worse for shared-process MT.

**Comment by yuzefovich** [comment]
@knz I tried manually adding locality flags to the nodes in TPCH 3 node runs, but that didn't seem to change the numbers.
<details>
<summary>diff</summary>

```
diff --git a/pkg/cmd/roachtest/tests/tpchvec.go b/pkg/cmd/roachtest/tests/tpchvec.go
index 1c8bbc756af..d6f74011657 100644
--- a/pkg/cmd/roachtest/tests/tpchvec.go
+++ b/pkg/cmd/roachtest/tests/tpchvec.go
@@ -591,7 +591,11 @@ func runTPCHVec(
        firstNode := c.Node(1)
        c.Put(ctx, t.Cockroach(), "./cockroach", c.All())
        c.Put(ctx, t.DeprecatedWorkload(), "./workload", firstNode)
-       c.Start(ctx, t.L(), option.DefaultStartOptsNoBackups(), install.MakeClusterSettings())
+       for i := 1; i <= tpchVecNodeCount; i++ {
+               startOpts := option.DefaultStartOptsNoBackups()
+               startOpts.RoachprodOpts.ExtraArgs = append(startOpts.RoachprodOpts.ExtraArgs, fmt.Sprintf("--locality=node=%d", i))
+               c.Start(ctx, t.L(), startOpts, install.MakeClusterSettings(), c.Node(i))
+       }
 
        var conn *gosql.DB
        var disableMergeQueue bool
```

</details>

In any case, I don't think we can explain this perf diff due to DistSQL physical planning because in the mixed-process mode when locality filter is empty (which is not true only for bulk operations right now) we map the SQL instance ID to the host node ID: https://github.com/cockroachdb/cockroach/blob/7cbcd3f55c4a88e3e08247ded01a7b40ef5d833e/pkg/sql/distsql_physical_planner.go#L1409-L1411

Does this sound right to you?

**Comment by knz** [comment]
At this time I do not think that our automation to run TPC-H is able to report meaningful data for side-by-side performance comparisons. There are just too many non-deterministic variables (data layout on disk; cache locality; CPU-memory affinity, etc); any difference in results cannot be clearly attributed to one architectural parameter vs another. It would take hundreds of runs before we can start seeing some data among the statistical noise. Which makes it very $$ and time expensive to use for our roadmap work.

In short: TPC-H no good for comparative benchmarking here.

I think we should let TPC-H sleep a bit until we investigate what is going on with the kv, ycsb and tpcc benchmarks instead.

I would also recommend that we come back to the microbenchmarks and extend them to get meaningful cpu profiles. The way I would do this is as follows:
- manually instrument the code to start capturing a cpu profile when the benchmark starts
- artificially constrain the benchmark to last more than X seconds (to make it significant). I believe there are command-line flags for this but otherwise we can also do this in the code.

**Comment by ajstorm** [comment]
@knz I agree with your concerns around TPC-H.  That being said, it seems pretty risky to ignore TPC-H, as there could be significant regressions present there.  Is it worth spending a time-boxed amount of time (say, 2 days) to try and rule out the most significant of the impacts your raise (data layout) by applying zone configs which will ensure consistent data placement?

**Comment by knz** [comment]
> it seems pretty risky to ignore TPC-H

I am not suggesting to "ignore" it. I am pointing out that _we cannot get useful data out of it until we learn how to rule out its many non-deterministic variables_. As of this writing, neither you nor I know how to do that. This is why I suggest to start with a focus on where we know how to proceed.

Concurrently with the above, I agree it would do us well to gather more experience from the perf (ex)v-team to see how to best proceed.

**Comment by knz** [comment]
The issue with data layout is not just zone configs and locality, it is also:
- non-determinism in KV range placement onto nodes
- non-determinism in placement of heap memory allocations by the Go runtime (TPC-H perf is surprisingly sensitive to that too)

One way to reduce variance on the first point would be to initialize the data; then disable the KV allocator (&merge/split queues); then stop the cluster; then save the store directories as baseline; then run the two variants of the benchmark with a cluster restored from the (common) store directories.

**Comment by knz** [comment]
The other thing to point out is that it's not clear (to me, currently) whether the problems exposed by TPC-H wouldn't be exposed by our various other benchmarks.

FWIW, when the KV team makes significant (perf-impacting) changes, TPC-H is not where design qualification is done.

**Comment by ajstorm** [comment]
> One way to reduce variance on the first point would be to initialize the data; then disable the KV allocator (&merge/split queues); then stop the cluster; then save the store directories as baseline; then run the two variants of the benchmark with a cluster restored from the (common) store directories.

I was thinking that if we had a 3 node cluster with single node in each of 3 localities, we set RF=1, and we forced leaseholders and replicas to be placed appropriately, we could force the ranges to be in certain locations.  Maybe that's a naive view however.

> The other thing to point out is that it's not clear (to me, currently) whether the problems exposed by TPC-H wouldn't be exposed by our various other benchmarks.

That's a fair point.  I was suggesting TPC-H only because I know that it will leverage DistSQL, and we had concerns that there _could_ be DistSQL/pushdown related performance concerns.  If we think that there's a better way to test the impact of DistSQL, then I'd be in favour of that.

**Comment by yuzefovich** [comment]
> It would take hundreds of runs before we can start seeing some data among the statistical noise.

The numbers I shared are the average over 50 runs, and now I've done 3 attempts, and all show the same - that for some queries we see a speed up, for others we see a slowdown. Here is the average over 150 runs (using the same cockroach binary but different roachtest binaries):
```
Q1:	before: 2.86s	after: 3.07s	 7.19%
Q2:	before: 2.72s	after: 4.43s	 63.05%
Q3:	before: 2.44s	after: 3.46s	 41.66%
Q4:	before: 1.58s	after: 1.00s	 -36.67%
Q5:	before: 2.37s	after: 1.90s	 -19.75%
Q6:	before: 4.10s	after: 3.91s	 -4.58%
Q7:	before: 5.04s	after: 4.55s	 -9.70%
Q8:	before: 0.97s	after: 0.91s	 -5.74%
Q9:	before: 5.07s	after: 7.16s	 41.06%
Q10:	before: 1.88s	after: 1.55s	 -17.52%
Q11:	before: 0.85s	after: 0.79s	 -6.26%
Q12:	before: 4.05s	after: 3.89s	 -3.95%
Q13:	before: 0.98s	after: 1.53s	 55.19%
Q14:	before: 0.41s	after: 0.55s	 33.37%
Q15:	before: 2.27s	after: 2.13s	 -6.47%
Q16:	before: 0.82s	after: 0.86s	 4.91%
Q17:	before: 0.22s	after: 0.34s	 51.26%
Q18:	before: 1.85s	after: 2.08s	 12.81%
Q19:	before: 0.44s	after: 0.77s	 76.06%
Q20:	before: 8.58s	after: 11.71s	 36.45%
Q21:	before: 4.55s	after: 4.36s	 -4.16%
Q22:	before: 0.52s	after: 0.74s	 42.76%
```

> to rule out its many non-deterministic variables
> disable the KV allocator (&merge/split queues)

I've been using `tpchvec` roachtest which does disable the merge queue.

> I would also recommend that we come back to the microbenchmarks and extend them to get meaningful cpu profiles.

I agree that the microbenchmarks would make it a lot easier to iterate. So far I've only looked at single node microbenchmark comparison, and we probably don't have an existing microbenchmark that would be roughly similar to what TPCH queries are doing.

I'll spend some time today to reproduce the TPCH difference on a 3 node cluster manually while fixing the placement of the ranges. I'm pretty sure that I'll see the same difference, so I'll investigate from there. Ideally, I'll be able to create a microbenchmark that reproduces the difference we see in `tpchvec` runs.

**Comment by yuzefovich** [comment]
I think I found the difference - indeed, it is in the DistSQL physical planner. We currently have this bit that if we only chose a single SQL instance to perform the scan, then we will reassign the spans to the gateway:
https://github.com/cockroachdb/cockroach/blob/9ed5fde0eed94386d78a293c4f3dd402c98aea9a/pkg/sql/distsql_physical_planner.go#L1359-L1364

As a result, in single-tenant mode we can get a distributed plan whereas in the shared-process multi-tenant mode - for the same range placement - we could get a local plan. Re-running `tpchvec` to confirm this.

**Comment by yuzefovich** [comment]
Indeed, with that logic removed, TPCH numbers show effectively noise:
```
Q1:	before: 2.76s	after: 3.08s	 11.31%
Q2:	before: 2.88s	after: 2.98s	 3.49%
Q3:	before: 2.18s	after: 2.09s	 -4.18%
Q4:	before: 1.53s	after: 1.52s	 -0.55%
Q5:	before: 2.27s	after: 2.28s	 0.41%
Q6:	before: 4.00s	after: 3.98s	 -0.49%
Q7:	before: 5.01s	after: 4.89s	 -2.44%
Q8:	before: 1.00s	after: 1.02s	 1.72%
Q9:	before: 5.12s	after: 5.17s	 1.06%
Q10:	before: 1.90s	after: 1.90s	 -0.15%
Q11:	before: 0.84s	after: 0.83s	 -0.76%
Q12:	before: 4.02s	after: 3.98s	 -0.87%
Q13:	before: 1.00s	after: 1.02s	 2.44%
Q14:	before: 0.42s	after: 0.42s	 0.81%
Q15:	before: 2.26s	after: 2.25s	 -0.49%
Q16:	before: 0.83s	after: 0.76s	 -7.76%
Q17:	before: 0.22s	after: 0.22s	 1.00%
Q18:	before: 1.83s	after: 1.81s	 -0.90%
Q19:	before: 0.44s	after: 0.44s	 0.09%
Q20:	before: 8.34s	after: 9.09s	 8.99%
Q21:	before: 4.52s	after: 4.31s	 -4.55%
Q22:	before: 0.51s	after: 0.49s	 -3.43%
```

**Comment by knz** [comment]
Fantastic finding! Thanks for the extra work.
