### ISSUE TITLE
cockroachdb provide customer with enhanced job tracking capabilities

### ISSUE THREAD

**Issue by lyang24** [cockroachdb/cockroach#104387]
**Is your feature request related to a problem? Please describe.**
When users of crdb made changes to their schema or creating/ modifying changefeed, its very hard for them to programmatically track the status of the job as the client do not know job identifier (job id).

We build a service that provide api based predefined abstracted operations as a service on top of crdb. One of our features to customer is schema change and we are responsible to report schema change status to our customers. We have to generate ddl queries such as `CREATE TABLE T{UUID}(a INT, b INT); ALTER TABLE T{UUID} TO REAL_TABLE_NAME ` just to be able to programmtically track the job by querying for the job status at system.jobs table.

we want an enhanced interface where customers can made changes and be able to track their jobs easily.

**Describe the solution you'd like**
Just a couple of ideas:
- Crdb provide some syntax that allow query that associate with job creation to return the generated job ids.
- Add a new column [job_tags] in system.jobs, and syntax to allow users to append tags to potentially generated jobs for better batch job management/ tracking. i.e. microsoft t-sql users can create jobs with [description and category_name](https://learn.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-add-job-transact-sql?view=sql-server-ver16).

**Describe alternatives you've considered**

**Additional context**

Jira issue: CRDB-28499

**Comment by rafiss** [comment]
@dt says that this is more of a sql-foundations issue, not a jobs issue. You can already create a changefeed or backup or restore using the DETACHED syntax, which gives you back the job ID immediately. You can then use that to find and inspect the job.

Schema change jobs are the odd one out here in that they do not offer a "return me your job ID" option, but that isn't a limitation of the jobs system.

**Comment by rafiss** [comment]
The commend above is for the first part of the request, about returning the job ID.

For the other request:
> Add a new column [job_tags] in system.jobs, and syntax to allow users to append tags to potentially generated jobs for better batch job management/ tracking. i.e. microsoft t-sql users can create jobs with [description and category_name](https://learn.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-add-job-transact-sql?view=sql-server-ver16).

Take a look at https://github.com/cockroachdb/cockroach/issues/91419 for a similar issue, and please leave comments there if you have other ideas.

**Comment by lyang24** [comment]
> The comment above is for the first part of the request, about returning the job ID.
> 
> For the other request:
> 
> > Add a new column [job_tags] in system.jobs, and syntax to allow users to append tags to potentially generated jobs for better batch job management/ tracking. i.e. microsoft t-sql users can create jobs with [description and category_name](https://learn.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-add-job-transact-sql?view=sql-server-ver16).
> 
> Take a look at #91419 for a similar issue, and please leave comments there if you have other ideas.

Thanks a lot for helping, 

- The second request is a duplicate #91419 is exactly what my company need. I will follow up there.
- DETACHED looks great that we can fetch the job id and store in our state!
- Is is possible to add "return me your job ID" option to schema changer? does it breaks postgres protocol? I would like to close this ticket and open a ticket on this one cc @Xiang-Gu
