### ISSUE TITLE
roachprod: c.ParallelE goroutine leak

### ISSUE THREAD

**Issue by srosenberg** [cockroachdb/cockroach#104316]
I happened to debug an unrelated issue which required SIGQUIT. Upon examining the goroutine dump, I noticed a large number of goroutines inside `ParallelE` which appear to be leaked. E.g., the goroutine below is waiting indefinitely to send `err` from `runWithMaybeRetry` on the unbuffered channel [1], 

```
1: chan send [1615 minutes] [Created by install.(*SyncedCluster).ParallelE.func1 @ cluster_synced.go:2595]
    runtime      proc.go:363              gopark(func(0x1f4), Pointer(0x0), waitReason(0x0))
    runtime      chan.go:259              chansend(*hchan(#8397), Pointer(#748), true)
    runtime      chan.go:145              chansend1(*hchan(#96), Pointer(#5697))
    install      cluster_synced.go:2601   (*SyncedCluster).ParallelE.func1.1(0)
    install      cluster_synced.go:2605   (*SyncedCluster).ParallelE.func1.2()
    runtime      asm_amd64.s:1594         goexit()
```

The above goroutine will never return if the following case [2] is taken first. (Note that it's non-deterministic owing to the semantics of `select`.)

[1] https://github.com/cockroachdb/cockroach/blob/c8c8869d8223e65eb4e6e6c32a9f8680a9e68f36/pkg/roachprod/install/cluster_synced.go#L2601
[2] https://github.com/cockroachdb/cockroach/blob/c8c8869d8223e65eb4e6e6c32a9f8680a9e68f36/pkg/roachprod/install/cluster_synced.go#L2653

Jira issue: CRDB-28457

**Comment by smg260** [comment]
Leaked goroutines are no longer showing. Marking as fixed by #104915
