### ISSUE TITLE
cli/debug: create an analog of 'tsdump' for SQL stats

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#104442]
This is an idea proposed by @tbg 

We could be delivering an equivalent of `cockroach debug tsdump` for SQL stats. See this wiki page for context: https://cockroachlabs.atlassian.net/wiki/spaces/CKB/pages/2284880796/Exporting+Importing+Timeseries+from+a+Cluster 

This would make it possible:

- to take a copy of the SQL stats o11y data from a running cluster (even one with partial unavailability).
- to restore that copy into an instance of cockroach demo (like what is possible for timeseries already via `COCKROACH_DEBUG_TS_IMPORT_FILE` - [ref](https://cockroachlabs.atlassian.net/wiki/spaces/CKB/pages/2284880796/Exporting+Importing+Timeseries+from+a+Cluster#Importing-Filtered-Timeseries)) and navigate it through the DB Console there.

Which problems this would help solve

- get/gain access to SQL stats of prod clusters during support escalations.
- get/gain access to SQL stats from old/previous-version CRDB for which event export (new OSA) has not been implemented yet.
- enable archival of historical SQL stats.
- enable “snapshot” of SQL stats when running tests/experiments.

Possible deliverables

- a cockroach debug sub-command which scrapes the SQL stats tables into a format that can be restored elsewhere.
- a mechanism inside cockroach demo akin to COCKROACH_DEBUG_TS_IMPORT_FILE able to load the SQL stats dump in-place with the system tables already pre-created in the demo cluster.

Acceptance criteria

- User can point the new cockroach debug command to the SQL interface of an existing cluster (either 22.x or 23.x) with admin user credentials and obtain a SQL stats dump.
- User can then use another cockroach command (e.g. cockroach demo) to load the stats dump.
- User can then use DB Console locally to navigate their local copy of the SQL stats.

Epic: CRDB-20791

Jira issue: CRDB-28532

**Comment by knz** [comment]
Through internal discussion with @j82w and others, it appears that this work would be somewhat redundant with the other work proposed in INI-212.

**Comment by maryliag** [comment]
No longer a priority
