### ISSUE TITLE
docs: Add note to metrics dashboard docs about interpreting certain graphs at different time resolutions

### ISSUE THREAD

**Issue by Santamaura** [cockroachdb/cockroach#104437]
**Is your feature request related to a problem? Please describe.**
Comes from https://cockroachlabs.atlassian.net/browse/CC-24662.

**Describe the solution you'd like**
We should add a note (perhaps here?: https://www.cockroachlabs.com/docs/stable/ui-hardware-dashboard.html) mentioning that some graphs (such as Disk Writes/Reads) may not show identical values when changing the time window since the rate at different time resolutions could be different.

**Describe alternatives you've considered**

**Additional context**

Jira issue: CRDB-28529

**Comment by mikeCRL** [comment]
Moved Jira copy to DOC project and closing this one as it's no longer linked.
