### ISSUE TITLE
Error when querying enum field using IntelliJ IDEA/Datagrip

### ISSUE THREAD

**Issue by SButterfly** [cockroachdb/cockroach#104403]
**Describe the problem**

When running the SQL query "SELECT * FROM db.tbl;" in Datagrip on a CockroachDB database, I encountered the following error when attempting to retrieve a value from an enum field:
```java
<failed to load>
java.lang.NullPointerException: Cannot invoke "String.endsWith(String)" because "pgTypeName" is null
	at org.postgresql.jdbc.TypeInfoCache.getSQLType(TypeInfoCache.java:308)
	at org.postgresql.jdbc.PgResultSet.initSqlType(PgResultSet.java:3087)
	at org.postgresql.jdbc.PgResultSet.getSQLType(PgResultSet.java:3075)
	at org.postgresql.jdbc.PgResultSet.internalGetObject(PgResultSet.java:196)
	at org.postgresql.jdbc.PgResultSet.getObject(PgResultSet.java:2936)
	in JdbcHelperImpl.getObject(JdbcHelperImpl.java:331)
```

**To Reproduce**

- Connect to a CockroachDB database in Datagrip
- create an enum type and a table with enum value and insert some mock data
- Run the SQL query "SELECT * FROM alak_db.metric__metrics;"
- Observe the error message in the enum field value

**Expected behavior**
I should be able to query the database without encountering errors, including when retrieving values from enum fields.

**Additional data / screenshots**
The issue is the copy-paste from https://youtrack.jetbrains.com/issue/DBE-17454

**Environment:**

- Datagrip version: 2022.3.3, DB-223.8617.3
- Operating system: Ubuntu 22.04.1 LTS  
- Database: CockroachDB CCL v22.2.3 (x86_64-pc-linux-gnu, built 2023/01/23 19:11:57, go1.19.1)
- DatabaseDriver: PostgreSQL JDBC Driver (ver. 42.6.0, JDBC4.2)

Jira issue: CRDB-28510

**Comment by rafiss** [comment]
I tried the following, and it worked fine. I used CockroachDB v22.2.1, PGJDBC 42.6.0, and GoLand 2023.1.2 (which includes DataGrip).

```
create type e as enum('a');

create table enum_tab (a int primary key, b e);

insert into enum_tab values (1, 'a');

select * from enum_tab;
```

Can you provide more precise instructions that reproduce the problem. Also, can you try a more recent version of DataGrip?

**Comment by SButterfly** [comment]
@rafiss After some testing I figured out that exception only appear if you are connecting tables from another database.
Steps to reproduce:
```
create database other_db;
create type other_db.e as enum('a');
create table other_db.enum_tab (a int primary key, b other_db.e);
insert into other_db.enum_tab values (1, 'a');
select * from other_db.enum_tab;
```

I tested in:
DBMS: PostgreSQL (ver. 13.0.0)
Case sensitivity: plain=lower, delimited=exact
Driver: PostgreSQL JDBC Driver (ver. 42.6.0, JDBC4.2)
Effective version: CockroachDB (ver. 22.2.3)

IntelliJ IDEA 2023.1.3 (Ultimate Edition)
Build #IU-231.9161.38, built on June 20, 2023

**Comment by ecwall** [comment]
When you run `SELECT * FROM other_db.enum_tab;`, DataGrip is also preparing this query
```
SELECT n.nspname = ANY (current_schemas(true)), n.nspname, t.typname 
FROM pg_catalog.pg_type AS t 
JOIN pg_catalog.pg_namespace AS n ON t.typnamespace = n.oid 
WHERE t.oid = $1;
```
Then binding the OID of the enum type: `100106` (`SELECT oid FROM pg_catalog.pg_type WHERE typname='e';`).

I looks like that OID can only be used with that query from inside its own database so the query returns 0 rows in `defaultdb` and 1 row in `other_db`.

**Comment by ecwall** [comment]
Added a comment here https://youtrack.jetbrains.com/issue/DBE-17454/DataGrip-Error-when-querying-enum-field-with-CockroachDB-database#focus=Comments-27-7981230.0-0 with a possible solution.
