### ISSUE TITLE
Show System Grants Errors - User Lacks SELECT Privilege on 'privileges' Relation 

### ISSUE THREAD

**Issue by Arivijay** [cockroachdb/cockroach#104412]
**Describe the problem**

Despite our doc stating that no privileges are required to execute "show system grants", the command isn't functioning as expected when "show system grants" for the logged in user is executed.

Link to the doc: [](https://www.cockroachlabs.com/docs/stable/show-system-grants.html#required-privileges)

fbtcrdbadmin@34.82.243.36:26257/defaultdb> show system grants for fbtcrdbadmin;
ERROR: user fbtcrdbadmin does not have SELECT privilege on relation privileges
SQLSTATE: 42501
fbtcrdbadmin@34.82.243.36:26257/defaultdb> show system grants;
ERROR: user fbtcrdbadmin does not have SELECT privilege on relation privileges
SQLSTATE: 42501
fbtcrdbadmin@34.82.243.36:26257/defaultdb>

**Environment:**
 CockroachDB version 23.1.1

Jira issue: CRDB-28517

Epic CRDB-27601

**Comment by rafiss** [comment]
@ecwall Could you take a look at addressing this? We'll need to backport a fix as well. Right now, SHOW SYSTEM GRANTS is implemented by delegating to `system.privileges`, which requires admin privileges.

We should change this by making a new crdb_internal table that reads from system.privileges using the internal executor. Then SHOW SYSTEM GRANTS can delegate to that crdb_internal table instead.
