### ISSUE TITLE
cloud,backupccl: userfile occasionally returning zero-byte file during restore

### ISSUE THREAD

**Issue by stevendanna** [cockroachdb/cockroach#104561]
**Describe the problem**

In tests, we've seen checksum mismatches come in one of two forms:

```
 pq: reading backup checkpoint: checksum mismatch; expected 1e5d7654, got e3b0c442
```

(for example: https://github.com/cockroachdb/cockroach/issues/102868)

or 

```
    backup_test.go:10946: expected error '', got: pq: reading backup checkpoint: checksum mismatch; expected , got 35415f1f
```

(for example: https://github.com/cockroachdb/cockroach/issues/104010)

In the first case, e3b0c442 is the SHA512 of an empty file:

```
> printf "" | shasum -a 256 | cut -c1-8
e3b0c442
```

In the second case the missing "expected" field is the result of reading no bytes out of the -CHECKSUM file.

We don't know yet if an empty file is actually being written or if this is a userfile bug.

Jira issue: CRDB-28602

**Comment by stevendanna** [comment]
One possibility is that this is caused by transaction retries along the write path. Locally, I was able to quickly reproduce a similar error by forcing the internal executor to randomly inject a retriable error.

Looking at the code, our write path is not very robust to transaction retries.

For instance, we call WriteChunk inside a txn that can be retried: 
https://github.com/cockroachdb/cockroach/blob/d802aaf53fe178e7c9a5bfec6dff94131e55da3a/pkg/cloud/userfile/filetable/file_table_read_writer.go#L581

But the ChunkWriter has internal state that gets advanced on very call to that function: 

https://github.com/cockroachdb/cockroach/blob/d802aaf53fe178e7c9a5bfec6dff94131e55da3a/pkg/cloud/userfile/filetable/file_table_read_writer.go#L478

**Comment by adityamaru** [comment]
@stevendanna updated release blocker to only block 22.2 until we backport.

**Comment by adityamaru** [comment]
all backports have been merged!
