### ISSUE TITLE
High memory usage on cluster

### ISSUE THREAD

**Issue by fphilippon** [cockroachdb/cockroach#10453]
Hi!

On our three node cluster we have an high memory usage (up to 40GB RSS) then the instance is automatically restarted and the memory usage keep growing up.

We are using the beta-20161027 version on CentOS 7.2 distro (with a recent kernel 4.4.x).

We did a heap dump using pprof. Please find it attached.

[heap svg](https://github.com/cockroachdb/cockroach/files/570947/heap.zip)
[pprof.localhost:8083.inuse_objects.inuse_space.009.pb.gz](https://github.com/cockroachdb/cockroach/files/570950/pprof.localhost.8083.inuse_objects.inuse_space.009.pb.gz)

Many thanks for your help guys!

**Comment by bdarnell** [comment]
20% of your memory was allocated in raftpb.Entry.Unmarshal, which was also the biggest consumer of memory in #10458. However, you're also seeing a lot of memory in `encodeRaftCommand`, which wasn't present in that issue. 

What kind of load is the cluster under? How quickly does the RSS grow after a restart?

How big was the RSS when this profile was taken? The Go heap was only 22MB, so the rest of the memory must have been either on the C side or in goroutine stacks.  If you grep for "runtime stats" in your server's logs, you'll see lines like this; can you post one of these from your servers? (ideally the last one before a crash)

    I161106 04:34:55.670159 324 server/status/runtime.go:228  runtime stats: 7.7 GiB RSS, 2055 goroutines, 870 MiB/390 MiB/1.7 GiB GO alloc/idle/total, 4.7 GiB/6.2 GiB CGO alloc/total, 163147.06cgo/sec, 5.64/0.63 %(u/s)time, 0.00 %gc (4x)

The memory improvements in the 1027 beta only take effect after a rocksdb compaction. If you upgraded in place from 1013, then you may be seeing the effects of that.

**Comment by fphilippon** [comment]
The kind of load we have is like 60-70 reads per second across all nodes and an average of 10 inserts per second.

After a restart the RSS grows quickly (~+1GB/hour)

Please find below a snapshot of memory usage graph.
https://snapshot.raintank.io/dashboard/snapshot/T1agy47pVyUkczCh2YuFdz0aUP17LdWb

Please also find last runtime stats logs from a server before a crash:

`I161107 05:55:00.074001 247 server/status/runtime.go:228  runtime stats: 41 GiB RSS, 184 goroutines, 44 MiB/361 MiB/480 MiB GO alloc/idle/total, 32 GiB/41 GiB CGO alloc/total, 74860.76cgo/sec, 0.68/0.87 %(u/s)time, 0.02 %gc (12x)`

Indeed we upgraded in place from 1013, how could we trigger the rocksdb compaction? Should we test from scratch by deleting all existing data?

Thanks for your help :)

**Comment by bdarnell** [comment]
You can run a compaction by stopping each server and running `cockroach debug compact /path/to/data/directory`, although I don't think it will actually fix the problem until #10532 is in. If you don't mind starting over from scratch, that's the simplest way to make sure you're no longer affected by the 1013 bug.

**Comment by fphilippon** [comment]
I did a test using 20161103 release and with a fresh start i still have instances getting restarted.

I also spotted the following stacktrace when the node reached the maximum memory allocated (--cache for rocksdb and --sql-max-memory set to 8gb) : 

`I161115 17:53:03.258727 153 server/status/runtime.go:228  runtime stats: 8.3 GiB RSS, 172 goroutines, 24 MiB/8.2 MiB/54 MiB GO alloc/idle/total, 6.2 GiB/8.1 GiB CGO alloc/total, 1539.69cgo/sec, 0.21/0.04 %(u/s)time, 0.00 %gc (13x)
W161115 17:53:04.869119 242 storage/replica.go:528  [n3,s3,r7/3:/Table/5{1-2}] raftMu: mutex held by github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReady for 773.878422ms (>500ms):
goroutine 242 [running]:
runtime/debug.Stack(0x1d169c8, 0x1d16a08, 0x47)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x79
github.com/cockroachdb/cockroach/pkg/util/syncutil.ThresholdLogger.func1(0x2e207296)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/syncutil/timedmutex.go:65 +0xe1
github.com/cockroachdb/cockroach/pkg/util/syncutil.(*TimedMutex).Unlock(0xc420871c78)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/syncutil/timedmutex.go:92 +0x80
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReady(0xc420871c00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1975 +0xee
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processReady(0xc42025e380, 0x7)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3143 +0x13e
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4203ed040, 0xc420438a20)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:230 +0x28c
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2()
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:181 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420438a20, 0xc420138020)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x7d
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x66
I161115 17:53:07.729674 144 storage/replica_proposal.go:292  [n3,s3,r16/3:/System/tsd/cr.store.range.sp…] new range lease replica {3 3 3} 2016-11-15 16:53:05.682763251 +0000 UTC 11.295487015s following replica {1 1 1} 2016-11-15 16:52:02.162511958 +0000 UTC 1m3.520251293s [physicalTime=2016-11-15 16:53:07.729616112 +0000 UTC]
I161115 17:53:13.258051 150 gossip/gossip.go:425  [n3] gossip status (ok, 3 nodes)
gossip client (1/3 cur/max conns)`

This stacktrace keeps showing until node got restarted later:

`I161116 09:53:54.607637 238 storage/replica_proposal.go:292  [n3,s3,r43/3:/System/tsd/cr.node.sys.rss/…] new range lease replica {3 3 3} 2016-11-16 08:53:38.881900225 +0000 UTC 24.969834191s following replica {2 2 2} 2016-11-16 08:52:44.464700959 +0000 UTC 54.417199266s [physicalTime=2016-11-16 08:53:54.607310115 +0000 UTC]
I161116 09:53:55.237299 233 storage/replica_proposal.go:341  [n3,s3,r41/3:/System/tsd/cr.store.mutex.sc…] range [n3,s3,r41/3:/System/tsd/cr.store.mutex.sc…]: transferring raft leadership to replica ID 1
I161116 09:54:03.263795 153 server/status/runtime.go:228  runtime stats: 13 GiB RSS, 171 goroutines, 41 MiB/429 MiB/535 MiB GO alloc/idle/total, 7.5 GiB/9.7 GiB CGO alloc/total, 68011.74cgo/sec, 0.47/0.21 %(u/s)time, 0.00 %gc (8x)
I161116 09:54:04.630295 262 storage/replica_proposal.go:292  [n3,s3,r16/3:/System/tsd/cr.store.range.sp…] new range lease replica {3 3 3} 2016-11-16 08:53:33.880284109 +0000 UTC 39.997327865s following replica {2 2 2} 2016-11-16 08:52:33.792803552 +0000 UTC 1m0.087480557s [physicalTime=2016-11-16 08:54:04.63011109 +0000 UTC]`

Thanks for your help!

**Comment by oldmantaiter** [comment]
Seeing this on a brand new cluster with no databases or data and no clients querying it.  Left it alone overnight after installing (binary) so I could play with it in the morning.

`161118 13:14:34.529648 124 server/status/runtime.go:228  runtime stats: 2.7 GiB RSS, 95 goroutines, 11 MiB/19 MiB/44 MiB GO alloc/idle/total, 1.9 GiB/2.5 GiB CGO alloc/total, 437.90cgo/sec, 0.01/0.00 %(u/s)time, 0.00 %gc (2x)`

This is with the latest stable beta (20161103). Let me know if there is any info I can provide.

<img width="919" alt="screen shot 2016-11-18 at 8 17 54 am" src="https://cloud.githubusercontent.com/assets/2213247/20431375/a58a14be-ad67-11e6-8204-2a6b6b1643cd.png">

**Comment by petermattis** [comment]
@oldmantaiter Did the memory usage eventually level off? By default a cockroach node uses 1/4 of physical memory for the RocksDB block cache. This shows up as "CGO alloc" in the stats. Even on an idle cluster there is background activity that is performing internal metrics collection. You can try setting the cache size lower using the `--cache-size` flag to `cockroach start`. 

Perhaps we should output the configured cache size in that `runtime.go` log line.

**Comment by oldmantaiter** [comment]
@petermattis - Ah, yes it did, my bad, I should have investigated further before falsely reporting this, sorry! - Good to know about the cache size though, that will definitely come in handy

**Comment by petermattis** [comment]
Looks like this issue was adequately addressed, but never closed.
