### ISSUE TITLE
changefeedccl: support metrics labels on datadog

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#104616]
This came from a customer request, they would like to be able to support metrics labels as tags in datadog. 

Jira issue: CRDB-28636

Epic CRDB-28633

**Comment by asg0451** [comment]
i think we support the relevant metric labels already on datadog. Do we have any specific examples of this not working? cc @awoods187 @rohan-joshi

**Comment by awoods187** [comment]
cc @kevin-v-ngo

**Comment by asg0451** [comment]
@kathancox i just noticed this issue is referenced in the docs: https://www.cockroachlabs.com/docs/v24.2/create-and-configure-changefeeds#known-limitations

can we remove this bit?
