### ISSUE TITLE
 panic: "unexpected leftover memory" error during graceful shutdown

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#10466]
Seen on my local single-node instance, built at commit bfea8d95e15d0534b539584830ee3b62aa5ceccf. I used Ctrl+C to shutdown the instance, and while it was shutting down, it panic'ed:

```
I161101 17:53:12.782849 1035 cli/start.go:401  0 running tasks
W161101 17:53:12.870667 1034 cli/start.go:382  timed out waiting for 1 open connections to drain
I161101 17:53:12.870702 1034 util/stop/stopper.go:363  stop has been called, stopping or quiescing all running tasks
panic: unexpected leftover memory: 142 bytes [recovered]
	panic: unexpected leftover memory: 142 bytes

goroutine 112 [running]:
panic(0x50ec360, 0xc4205fc6d0)
	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:500 +0x1a1
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc4204a7050)
	/Users/alex/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:185 +0x6e
panic(0x50ec360, 0xc4205fc6d0)
	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:458 +0x243
github.com/cockroachdb/cockroach/pkg/sql/mon.(*MemoryUsageMonitor).StopMonitor(0xc42022d150, 0x9843168, 0xc42034fd80)
	/Users/alex/go/src/github.com/cockroachdb/cockroach/pkg/sql/mon/mem_usage.go:130 +0x2a2
github.com/cockroachdb/cockroach/pkg/sql.(*Session).Finish(0xc42022c900, 0xc4203d6a00)
	/Users/alex/go/src/github.com/cockroachdb/cockroach/pkg/sql/session.go:193 +0x99
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).finish(0xc42011c180, 0x9843000, 0xc42054f8c0)
	/Users/alex/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:154 +0x7e
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn(0xc42014aba0, 0x9843000, 0xc42054f8c0, 0x5ac2ea0, 0xc420412160, 0x5aab1a0, 0xc4205791d0)
	/Users/alex/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:247 +0x6bd
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func8.1(0x5ac2ea0, 0xc420412160)
	/Users/alex/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:492 +0x106
github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1(0xc4204a7050, 0xc42012e268, 0x5ac2ea0, 0xc420412160, 0xc4202c8000)
	/Users/alex/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:136 +0x95
created by github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith
	/Users/alex/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:138 +0x277
```

Ctrl+F doesn't find any log messages from the mem_usage.go file. @knz, is this just a side effect of not being able to drain the 1 open SQL connection or is it that already accounted for?

**Comment by knz** [comment]
Please provide some more info. 

In the trace you're giving, the SQL connection is being drained all right, the stack trace comes from pgwire shutting down the session -- probably as a result of seeing its context canceled.

Can you repro reliably? If so please repro with `--vmodule=mem_usage=2` on the server and we'll track these bytes from there.

**Comment by a-robinson** [comment]
I'll see if I can repro with the mem_usage logging turned up.

I know nothing else about why this happened -- I often just have a single-node server running in the background to occasionally run commands against, and I don't remember how long this was running for, what I ran against it, or even why it stopped.

**Comment by a-robinson** [comment]
Alright, I don't think it's actually the same case that triggered the first panic, but in trying to recreate it I found a different case that repros reliably :)

Trying to create a view that reads from a virtual table whose name is already in use reliably causes a leftover memory panic. For example, on a fresh cluster:

```
root@:26257> create database foo;
connection lost; opening new connection and resetting session parameters...
CREATE DATABASE
root@:26257> create view foo.views as select schemaname, viewname, definition from pg_catalog.pg_views;
CREATE VIEW
root@:26257> create view foo.views as select schemaname, viewname, definition from pg_catalog.pg_views;
driver: bad connection
```

Generates this log output:
[log.txt](https://github.com/cockroachdb/cockroach/files/575763/log.txt)

**Comment by a-robinson** [comment]
To clarify, it doesn't matter whether or not the existing conflicting relation is a view or a table, it only matters that the new view being created reads from a virtual table. It looks as though we're not properly getting rid of the virtual table's plan info:

```
I161107 10:33:31.830956 197 sql/mon/mem_usage.go:518  [n1,client=127.0.0.1:64118,user=root] txn: now at 184 bytes (+184) - sql/mon.(*MemoryMonitor).GrowAccount:sql/mon.(*BoundAccount).Grow:sql.(*RowContainer).AddRow:sql.virtualTableEntry.getPlanInfo.func1.1:sql.glob..func24.1
```

**Comment by knz** [comment]
Ok I know how to investigate this. Thanks!

**Comment by a-robinson** [comment]
Changed the name of the issue to reflect the more specific problem being fixed. I'll open a new issue with more details if I'm ever able to get a repro along the lines of the first one I saw, which was definitely different from this.

**Comment by knz** [comment]
Yes sorry I was perhaps a bit hasty by writing in #10527 that the PR would fix this issue. It's clearly not the right cause-effect relationship. Perhaps we should split the concerns, restore the original title, keep the initial description, and move the CREATE-related issues to the commit message of #10527 to justify it better. How does that sound?

**Comment by a-robinson** [comment]
Works for me

**Comment by a-robinson** [comment]
Closing due to staleness and lack of details - I haven't seen this again since the initial report.
