### ISSUE TITLE
kvserver: export latency histogram for time spent waiting for latches

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#104682]
This would have come in handy in numerous internal incidents.

Jira issue: CRDB-28667

Epic CRDB-34227

**Comment by mzone242** [comment]
Hello, @annabelto and I would like to take this issue. We are Masters students at The University of Texas at Austin and are looking to contribute to an open source project concerned with distributed systems for our coursework in the subject.

Can you also provide some more information on the deliverables of this issue? We are unable to see the internal Jira ticket associated with this. Specifically we're curious about what was previously attempted/implemented in the associated mentioned issues.

**Comment by mzone242** [comment]
That would be great, thank you!

**Comment by nvanbenschoten** [comment]
Hi @mzone242, thanks for the interest in CockroachDB! Unfortunately, we are planning on working on this issue in the next few weeks, so it's not a great first issue to get familiar with the codebase like I originally thought it would be.

I took a look and another issue which might be interesting to you is https://github.com/cockroachdb/cockroach/issues/103839. It's another improvement to observability, intended to make unhealthy node logging easier to understand in securing conscious environments which require log redaction.
