### ISSUE TITLE
cdc: surface repetitive or likely permanent errors

### ISSUE THREAD

**Issue by shermanCRL** [cockroachdb/cockroach#104628]
**Is your feature request related to a problem? Please describe.**

Changefeeds have switched to [“default retryable” on error](https://github.com/cockroachdb/cockroach/pull/92824). This is good!

We have a new problem, perhaps, that errors will retry a lot or indefinitely. This likely means the error is de facto permanent -- maybe a config problem, auth, etc.

**Describe the solution you'd like**

These situations should be surfaced to the user.

I don’t know how! The starting place would be to define “too repetitive” or “probably permanent”. The surfacing could be a metric? An alert in DB Console?

Jira issue: CRDB-28643

**Comment by amruss** [comment]
Closing this, its too vague. We do have: https://github.com/cockroachdb/cockroach/pull/103539
