### ISSUE TITLE
storage: investigate up-replicating before removing dead nodes

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#10476]
`Allocator.ComputeAction` currently prioritizes removing dead nodes over adding a new replica. When a node has been down for 5m all of the replicas on the node are considered dead. With the current prioritization, `replicateQueue` will queue up any range with a replica on that node for removal of the dead replica. These removals can happen very quickly in comparison to up-replication: we can process the removals almost as fast as the scanner can scan ranges. If the dead node recovers we'll have generated a large body of up-replication work.

I'm not sure of the historical reason for the current prioritization, but it seems preferable to add a new replica to these ranges before removing the dead replica. 

Cc @BramGruneir, @mrtracy, @cockroachdb/stability

**Comment by bdarnell** [comment]
The historical reason is that prior to preemptive snapshots, upreplicating first would immediately make the range unavailable until the snapshot had been processed. The range would go from 2/3 replicas to 2/4, until the snapshot brings it back to 3/4 and the dead node can be removed.

Now with preemptive snapshots, it's better to upreplicate first (and this was always part of the plan but got forgotten along the way). Now the range configuration stays at 2/3 until the snapshot has been processed, so the replica changes can quickly transition from 2/3 to 3/4 to 3/3.

**Comment by petermattis** [comment]
Another thought is to adjust the relative priorities. Currently we have:

```
	removeDeadReplicaPriority  float64 = 10000
	addMissingReplicaPriority  float64 = 1000
	removeExtraReplicaPriority float64 = 100
```

The problem with this prioritization is that if we have 2 ranges, one which requires the removal of the dead replica and another which requires the addition of a missing replica we'll always process the dead replica removal first, perhaps starving the addition of the missing replica for a long time. We can change the relative priority of dead-removal and add-missing-replica:

```
	addMissingReplicaPriority  float64 = 10000
	removeDeadReplicaPriority  float64 = 1000
	removeExtraReplicaPriority float64 = 100
```

With this prioritization, in the earlier scenario we'll adding the missing replica first, then perform the dead replica removal on the other range which will cause that range to be re-enqueued for addition of a missing replica.

This is a trivial change to make and ensures that dead replica removal doesn't get too far in advance of the up-replication work it is creating.
