### ISSUE TITLE
ts: only issue DeleteRange requests when pruning if there is something to delete

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#10479]
Discovered while investigating  #10409.

`tsdb.PruneTimeSeries` issues a `DeleteRange` request for every time series name it encounters regardless of whether there is any data to delete. It seems possible to enhance `tsdb.findTimeSeries` to only return time series which have data that needs to be pruned. When seeking to the next time series name we could "back up" (using `rocksdb.Iterator.Prev`) to find the oldest key for the previous time series and determine if any data needs to be deleted.

**Comment by petermattis** [comment]
@spencerkimball didn't you fix this?

**Comment by spencerkimball** [comment]
Yes #11762
