### ISSUE TITLE
Add file based credentials to implicit auth path in Azure

### ISSUE THREAD

**Issue by rhu713** [cockroachdb/cockroach#104751]
Add the ability to specify a path using an environment variable pointing to a well-known file with credentials. Read this credentials file while resolving the credentials chain in Azure storage and KMS similar to `GOOGLE_APPLICATION_CREDENTIALS` in GCP or `~/.aws/credentials` in AWS.

Jira issue: CRDB-28708

Epic CRDB-18955

**Comment by davidwding** [comment]
I'm doing some work on this and I'm nearing the point where I need to decide on naming conventions for all of this. Does the following seem reasonable:

- Have the credentials file specified by an environment variable with name AZURE_APPLICATION_CREDENTIALS
- The credentials file should have the following format (inspired by [AWS](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html)):
```
azure_tenant_id=FOOFOO
azure_client_id=BARBAR
azure_clients_secret=BAZBAZ
```

Are there any fields I've missed?
