### ISSUE TITLE
go get cockroachdb hangs indefinitely

### ISSUE THREAD

**Issue by crackerplace** [cockroachdb/cockroach#10477]
- What did you do?

I am trying to setup the development environment for cockroachdb.With go get I am able to get other go packages.Somehow its not responding for cockroachdb

When I run the below command ,it hangs indefinitely.I tried even waiting for 2 hours,but still it just hangs.
**Command** : go get -d -x -v github.com/cockroachdb/cockroach
**Output** :
github.com/cockroachdb/cockroach (download)
cd .
git clone https://github.com/cockroachdb/cockroach /home/OSS/go/src/github.com/cockroachdb/cockroach

- What did you expect to see?
I expected to see the package downloaded

- What did you see instead?
It just hangs on.

Is there any other way to setup and build cockroachdb in my local system ?

Thanks

**Comment by bdarnell** [comment]
You can do what `go get` would do by hand:

    mkdir -p ~/go/src/github.com/cockroachdb
    cd ~/go/src/github.com/cockroachdb
    git clone https://github.com/cockroachdb/cockroach

I wouldn't expect this to fix the problem, but it will show you more detail about what's going on.

**Comment by OpsMx** [comment]
ok.This looks like some issue with go get taking long time to dowload certain github packages.

**Comment by crackerplace** [comment]
ok.Looks like there is some issue with **go get** as certain github packages are taking very long time to download.
