### ISSUE TITLE
sql/kv: don't step external read snapshot on volatile UDF execution

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#104847]
In https://github.com/cockroachdb/cockroach/issues/100133 / https://github.com/cockroachdb/cockroach/pull/104362, we added support for per-statement read snapshots under Read Committed by updating the `Txn.Step` API to advance the transaction's read timestamp. This is correct for most callers of the API, but it appears that the following caller only wants to advance the txn's visibility of its own writes, not all other writes:
https://github.com/cockroachdb/cockroach/blob/bc1a2a0f6cbf0da870123ff0a07a67cd254be8ed/pkg/sql/routine.go#L173-L179

This might motivate an expansion of the Step API. For example, we may want it to take a flag that indicates whether only the txn's internal read seq should be advanced or whether its internal read seq and its external read timestamp should be advanced (assuming Read Committed).

Jira issue: CRDB-28746

**Comment by michae2** [comment]
> I don't believe this is true, unless I'm misunderstanding what you mean. Future invocations of the UDF (or other UDFs) need to see all the writes of previous invocations of the UDF. Here's an example in Postgres:

I think future invocations of the UDF would still see all the writes of previous invocations **from the same txn**. (This issue is about the UDF seeing writes from *other txns*.)

**Comment by nvanbenschoten** [comment]
Right, when invoking volatile UDFs, all transactions will `Step` and see prior writes from the same transaction. So the example from https://github.com/cockroachdb/cockroach/issues/104847#issuecomment-1599330186 will work in all isolation levels because the `UPDATE`s are all part of the same transaction.

The question here is whether Read Committed txns (and only RC txns) should _also_ step their external read snapshot when invoking volatile UDFs, so that each UDF gets an updated view of all other transactions in the system each time it is run. My understanding is that this is how PG works, but to do so they then play a subtle dance of snapshot management to restore the prior read snapshot when back in the calling statement's context.

There are a few reasons why we might want to diverge from this behavior:
- it's unclear whether applications actually need this behavior
- it's odd that the behavior of volatile UDFs would differ depending on the isolation level. If someone is actually relying on this external visibility, then their UDF will only work under RC and would be entirely broken under stronger isolation levels
- it would be quite difficult to support this behavior. We won't easily be able to restore a prior snapshot once the transaction's external read snapshot has been advanced. This would require a lot of infrastructure that we don't currently have
- unlike PG, CRDB is going to provide a true consistent read snapshot across an entire statement. In such a world, does it make sense for UDFs to break this snapshot? In other words, is a divergence here just a continuation of our primary deviation from PG, or something new? 

Answering the first question is probably the place to start. Are we aware of any UDFs that rely on seeing newly committed rows from other transactions ("new" relative to the start of their current statement)? The only example I've been able to come up with that might make some sense is a "succeeds soon" condition where a statement hangs in a backoff loop, repeatedly executing a volatile UDF until it observes some other txn commit.

**Comment by michae2** [comment]
> Answering the first question is probably the place to start. Are we aware of any UDFs that rely on seeing newly committed rows from other transactions ("new" relative to the start of their current statement)? The only example I've been able to come up with that might make some sense is a "succeeds soon" condition where a statement hangs in a backoff loop, repeatedly executing a volatile UDF until it observes some other txn commit.

I think this is exactly the type of use we will (eventually) find in the wild. Some volatile UDF being called in a PLpgSQL loop waiting for another transaction to commit.
