### ISSUE TITLE
makefile: replace the makefile with a stub GNUMakefile and clean up supporting tools

### ISSUE THREAD

**Issue by jlinder** [cockroachdb/cockroach#104804]
This issue covers the final work to retire the old `make`-based build system and provide pointers to the Bazel-based build system. 

It involves at least these steps:

- Clean up the TC agent packer build scripts to remove the `build/builder.sh` and make-related things it includes (this might need to be done after Assistance Support ends for 22.1 since it is the last release that used Make for the release process).
- References to the `build/builder.sh` file: remove them or update them to reference / use the bazel build process.
- Remove the `build/builder.sh` file, [builder](https://github.com/cockroachdb/cockroach/tree/master/build/builder) directory and any other releated code.
- Any other references to or uses of the `make`-based build process in the repo: remove them or update them to the Bazel-based process.
- Update all remaining references in the wiki about the make-based system to reference bazel instead or note which branches the make commands/flows work with.
- Replace the `makefile` with a stub `GNUmakefile` to point all usage to `./dev`

Epic: CRDB-8349

Jira issue: CRDB-28733

**Comment by rickystewart** [comment]
@knz I'm going to close this out and file a follow-up issue for the remaining items.

**Comment by rickystewart** [comment]
#110669
