### ISSUE TITLE
Multi Tenant Servers Can Skip Upgrades

### ISSUE THREAD

**Issue by JeffSwenson** [cockroachdb/cockroach#104884]
There is a rare bug impacting the Serverless upgrade from 22.2 to 23.1. It was only triggered once when we upgraded our staging clusters and the staging clusters contain a few thousand tenants for scale testing purposes. Out of the thousands of staging Serverless clusters, only one skipped an upgrade job, which caused the cluster to enter a crash loop.

[This is the implementation of algorithm for stepping a version gate](https://github.com/cockroachdb/cockroach/blob/3d4db0a846c07fbf2efb8e0eb87a0023c1ccab71/pkg/upgrade/upgrademanager/manager.go#L359). Each version v has a fence version v' that is 1 internal version less than v. The fence version is used to implement a barrier when upgrading a cluster.

A high level overview of the algorithm is: 
1. Send an RPC to each sql server activating version v'
2. Run the upgrade job attached to v
3. Send an RPC to each sql server activating version v
4. Set the cluster setting version to v

There is a bug in the implementation that only impacts multi-tenant clusters. On the first upgrade applied by the loop, the [mustPersistFenceVersion branch](https://github.com/cockroachdb/cockroach/blob/3d4db0a846c07fbf2efb8e0eb87a0023c1ccab71/pkg/upgrade/upgrademanager/manager.go#L547) updates the system setting.

The purpose of the branch is to ensure that no servers running the old binary can start up. But it is setting the cluster setting version to `v`. If the binary crashes before running the upgrade for `v`, then when the server restarts, it reads the setting version `v` and ends up skipping the upgrade when the upgrade resumes.

Judging by the name of the `mustPersistFenceVersion` variable, I think the bug is a simple typo and updateSystemVersionSetting was intended to be called with the fence version `v'`.

Jira issue: CRDB-28765

**Comment by michae2** [comment]
It looks like this is close to going in, so I propose we hold the v23.1.4 release to make sure we pick it up.
