### ISSUE TITLE
storage: allow Raft snapshots if they are required for forward progress

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#10483]
Discovered while investigating #10409.

Snapshots, both preemptive (for up-replication and rebalancing) and Raft initiated, are limited to 1 outstanding per store. This can lead to scenarios in which a cluster is wedged. Consider a 3-node cluster where nodes 1 and 2 have been initialized and node 3 is trying to join:

1. The replicate queue on node 1 begins the up-replication of range 1 to node 2.
2. A snapshot of range 1 is generated at index 100 and sent to node 2.
3. More requests arrive at range 1 bumping the raft log index up to 200.
4. The preemptive snapshot for range 1 is applied and node 2.
5. Node 2 is added to the set of replicas for range 1.
6. The raft log for range 2 is truncated to index 200.
7. The replicate queue on node 2 begins the up-replication of range 2 to node 2.
8. A snapshot of range 2 is generated and sent to node 2.

At this point, range 1 is unusable because we need a quorum of nodes to proceed and only the replica on node 1 is current while the replica on node 2 is at index 100. Raft notices this and tries to send Raft log entries, finds they have been truncated and tries to send a snapshot. But we can't send a snapshot because there is one already outstanding for range 2. And notice that the up-replication of range 2 will never complete because in order to do so it needs to update the meta records which currently reside on range 1.

I propose defense in depth regarding this scenario. One defense is minimizing or eliminating the window where log truncation can cause a problem (see #10482). Another is to always allow Raft initiated snapshots to proceed if the Replica they are being performed does not have a quorum of nodes at the commit index. This can occur for a small window of time after up-replication. 

Cc @bdarnell, @cockroachdb/stability

**Comment by bdarnell** [comment]
The up-replication of range 2 will never complete while range 1 is unavailable, but the snapshot transmission should still be able to complete, which will free up the snapshot slot and give range 1 another shot at it. We don't guarantee that this process is starvation-free, but I'd still expect range 1 to be able to make progress sooner or later, instead of getting permanently stuck.

We should definitely remove the use of the `Commit` index in `raftLogQueue` - it's being used because it's simpler than computing the log position acknowledged by a quorum, but that's not true in the presence of a replication change so we should compute the position of a quorum of the current replicas directly.

**Comment by petermattis** [comment]
> The up-replication of range 2 will never complete while range 1 is unavailable, but the snapshot transmission should still be able to complete, which will free up the snapshot slot and give range 1 another shot at it.

Except that's not what happens because we don't release the snapshot slot for range 2 until the up-replication is complete. See the `defer r.OutSnapClose()` call in `Replica.ChangeReplicas()`. That looks easy enough to change. 

> We should definitely remove the use of the Commit index in raftLogQueue - it's being used because it's simpler than computing the log position acknowledged by a quorum.

I seem to recall we also thought the Commit index would always equal the quorum commit index. At least I certainly did.

**Comment by bdarnell** [comment]
> I seem to recall we also thought the Commit index would always equal the quorum commit index. At least I certainly did.

Yes, me too; it's such a natural assumption that I didn't even consciously consider it. But it makes sense that if a node fails just after casting its vote, the command is still committed but we now have less than a majority that have acknowledged it. 

We might want to consider this in rebalancing: don't remove a replica that is a necessary part of the current quorum. But it can be tricky to tell which nodes are necessary as the acknowledged indexes are always changing (and you'll go through at least two more rounds of consensus before the ChangeReplicas completes), so we'd need some sort of heuristic to tell when a replica is far enough behind that the other replicas should not be removed.
