### ISSUE TITLE
storage: only up-replicate if there are at least 3 nodes in a cluster

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#10480]
Discovered while investigating #10409.

When a new cluster starts up it goes through a small window where there are only 2 nodes in the system. `replicateQueue` will currently start up-replicating ranges when that occurs. We should wait until a 3rd node joins the cluster to begin up-replication to minimize the time window when ranges are in the risky 2 replica state.

Similarly, in a 3-node cluster we shouldn't down-replicate to 2 replicas when one of the nodes dies until a new node joins the cluster. Down-replicating eagerly merely adds to the recovery time if the dead node revives.

**Comment by tamird** [comment]
Pedantic nit: shouldn't we wait until there are 3 usable candidates for a
range to replicate it, rather than relying on the total number of nodes?

**Comment by petermattis** [comment]
@tamird Yes.
