### ISSUE TITLE
cluster-ui, quick-win: memoized columns on databases and database table page

### ISSUE THREAD

**Issue by THardy98** [cockroachdb/cockroach#104873]
On the databases and database table pages, we added the table columns to the component's state in order to only re-compute these columns when specific props had changed. On both these pages, we only add a column for index recommendations when the `showIndexRecommendations` prop is true.

We can remove this from component state and simplify this logic by memoizing these columns using `React.memo` or `createSelector`.

Jira issue: CRDB-28763

**Comment by maryliag** [comment]
No longer a priority
