### ISSUE TITLE
stability: gamma node persistently wedged

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#10494]
One node on gamma got wedged somehow and abruptly stopped processing queries (QPS after this point was not quite zero, but only a few queries per minute):

![image](https://cloud.githubusercontent.com/assets/160562/20045792/2ec996aa-a4df-11e6-8a64-94eea5b376b4.png)

Since then, its goroutine count has been steadily increasing, and it's crashed and restarted twice (looks like it'll crash every ~6 hours), so whatever it's stuck on is persistent:

![image](https://cloud.githubusercontent.com/assets/160562/20045876/792565da-a4df-11e6-92e7-b7024394bc43.png)

**Comment by bdarnell** [comment]
Looks like all of its replicas unquiesced at once (and then stayed that way. Why aren't they going back to quiescent after restart due to lazy loading?):

![image](https://cloud.githubusercontent.com/assets/160562/20046283/f27f67a2-a4e2-11e6-983c-372cbf8b1b06.png)

At the same time, it lost all its leaderships:

![image](https://cloud.githubusercontent.com/assets/160562/20046313/2385988a-a4e3-11e6-9c4f-c12eedd55cc7.png)

And started receiving snapshots as quickly as it could apply them:

![image](https://cloud.githubusercontent.com/assets/160562/20046321/42f02e74-a4e3-11e6-8aa2-d285dc45fe9c.png)

Just before all of this happened, the CPU load flattened out at 3.0, suggesting that three threads might have reached some critical saturation point (although there is not a clear upward trend before this):

![image](https://cloud.githubusercontent.com/assets/160562/20046346/842fd074-a4e3-11e6-8ee1-109209884781.png)

Now, CPU usage is dominated by applying all those snapshots and sending heartbeats for the unquiesced ranges. It's sending a lot of heartbeat messages, but no responses (indicating that it's not receiving any heartbeat requests):

![image](https://cloud.githubusercontent.com/assets/160562/20046379/f30aa168-a4e3-11e6-97cb-317c5ac9d61f.png)

Other nodes are responding to its heartbeats, though:

![image](https://cloud.githubusercontent.com/assets/160562/20046393/17a435f2-a4e4-11e6-8b73-49e82a2ebcaf.png)

Cluster-wide traffic looks strange: we saw a drop in queries per second but an increase in transactions per second, and bytes in/out swapped. Did something change with the load generators on gamma around that time?

![image](https://cloud.githubusercontent.com/assets/160562/20046421/806f87d0-a4e4-11e6-977f-403fbbb60511.png)

**Comment by bdarnell** [comment]
OK, we see block writer throughput drop to zero:

```
277h38m35s:   28.0/sec (5359107 total errors)
277h38m36s:   23.0/sec (5359107 total errors)
277h38m37s:   65.0/sec (5359107 total errors)
277h38m38s:   22.0/sec (5359107 total errors)
277h38m39s:   43.0/sec (5359107 total errors)
277h38m40s:   23.0/sec (5359107 total errors)
277h38m41s:   24.0/sec (5359107 total errors)
277h38m42s:   55.0/sec (5359107 total errors)
277h38m43s:   47.0/sec (5359107 total errors)
277h38m44s:   46.0/sec (5359107 total errors)
277h38m45s:   10.0/sec (5359107 total errors)
277h38m46s:    0.0/sec (5359107 total errors)
277h38m47s:    0.0/sec (5359107 total errors)
277h38m48s:    0.0/sec (5359107 total errors)
277h38m49s:    0.0/sec (5359107 total errors)
277h38m50s:    0.0/sec (5359107 total errors)
277h38m51s:    0.0/sec (5359107 total errors)
277h38m52s:    0.0/sec (5359107 total errors)
277h38m53s:    0.0/sec (5359107 total errors)
277h38m54s:    0.0/sec (5359107 total errors)
277h38m55s:    0.0/sec (5359107 total errors)
```

And an improvement in photos performance at the same time:

```
I161106 14:41:48.835934 23 user.go:123  7831632 ops, 2 no-user, 8433 no-photo, 3110
245 errs (0.00/s)
I161106 14:41:58.835949 23 user.go:123  7831632 ops, 2 no-user, 8433 no-photo, 3110
245 errs (0.00/s)
I161106 14:42:08.835911 23 user.go:123  7831632 ops, 2 no-user, 8433 no-photo, 3110
245 errs (0.00/s)
I161106 14:42:18.835946 23 user.go:123  7831632 ops, 2 no-user, 8433 no-photo, 3110
245 errs (0.00/s)
I161106 14:42:28.835947 23 user.go:123  7831632 ops, 2 no-user, 8433 no-photo, 3110
245 errs (0.00/s)
I161106 14:42:38.835915 23 user.go:123  7831632 ops, 2 no-user, 8433 no-photo, 3110
245 errs (0.00/s)
I161106 14:42:48.835950 23 user.go:123  7831650 ops, 2 no-user, 8433 no-photo, 3110
245 errs (1.80/s)
I161106 14:42:58.835940 23 user.go:123  7831702 ops, 2 no-user, 8433 no-photo, 3110
245 errs (5.20/s)
I161106 14:42:59.405700 24 user.go:158  failed to run create comment op for 98300: 
pq: result is ambiguous
I161106 14:43:08.835946 23 user.go:123  7831747 ops, 2 no-user, 8433 no-photo, 3110
246 errs (4.50/s)
I161106 14:43:18.836003 23 user.go:123  7831789 ops, 2 no-user, 8433 no-photo, 3110
246 errs (4.20/s)
I161106 14:43:28.835969 23 user.go:123  7831836 ops, 2 no-user, 8433 no-photo, 3110
246 errs (4.70/s)
I161106 14:43:38.835958 23 user.go:123  7831888 ops, 2 no-user, 8433 no-photo, 3110
246 errs (5.20/s)
I161106 14:43:48.836001 23 user.go:123  7831932 ops, 2 no-user, 8433 no-photo, 3110
246 errs (4.40/s)
```

So it looks like block_writer and photos are competing for resources and for whatever reason these problems are bringing block_writer to a halt and letting photos pick up the slack.

**Comment by petermattis** [comment]
The problematic machine on gamma is `104.196.174.155`. Right now, I can't even ssh to that machine.

**Comment by petermattis** [comment]
From the serial console for that node:

```
Nov  7 16:16:01 cockroach-gamma-2 kernel: [9244950.886856] Out of memory: Kill process 3537 (cockroach) score 927 or sacrifice child
Nov  7 16:16:01 cockroach-gamma-2 kernel: [9244950.894989] Killed process 3537 (cockroach) total-vm:16631136kB, anon-rss:14728696kB, file-rss:0kB
```

**Comment by bdarnell** [comment]
It [recovered](https://monitoring.gce.cockroachdb.com/dashboard/snapshot/fzahY6yZz9QUYoyZe0w2oeoCk1BLwNh7), apparently on its own. 

At 18:30, it reacquired a bunch of raft leaderships simultaneously, gradually lost them over the next few hours, then started gradually regaining them.

![image](https://cloud.githubusercontent.com/assets/160562/20089687/95ad47e2-a5c3-11e6-8852-a72ddc88aa8a.png)

During that decline, the replica GC queue was working and destroyed nearly half of this node's replicas (but this can't be the cause of the decline above because we wouldn't be GCing a replica we just became leader of)

![image](https://cloud.githubusercontent.com/assets/160562/20089716/b09ba2e2-a5c3-11e6-8430-c606d0f92dc9.png)

The range lease graph is bumpier than the raft leader graph above:

![image](https://cloud.githubusercontent.com/assets/160562/20089774/fda78fce-a5c3-11e6-86b3-df25cee8ee28.png)

The replica quiescence graph is very interesting during this time:

![image](https://cloud.githubusercontent.com/assets/160562/20089758/ed01ba82-a5c3-11e6-8347-892c05182647.png)

In the logs, we see a lock held for 46 seconds at the 18:30 mark:

```
logs/cockroach.stderr.6:W161107 18:31:26.109924 205 storage/replica.go:537  [n8,s7,r2731/1:/Table/55/1/121{44873…-56079…}] raftMu: mutex held by github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReady for 46.063313679s (>500ms):
logs/cockroach.stderr.6:W161107 18:31:26.109983 203 storage/replica.go:537  [n8,s7,r10818/1:/Table/55/1/731{15526…-26694…}] raftMu: mutex held by github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReady for 46.045400726s (>500ms):
logs/cockroach.stderr.6:W161107 18:31:26.110370 202 storage/replica.go:537  [n8,s7,r9839/1:/Table/55/1/596{58112…-69338…}] raftMu: mutex held by github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReady for 46.021562688s (>500ms):
logs/cockroach.stderr.6:W161107 18:31:26.110941 204 storage/replica.go:537  [n8,s7,r10802/1:/Table/55/1/1{199925…-201040…}] raftMu: mutex held by github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReady for 46.048029853s (>500ms):
logs/cockroach.stderr.6:W161107 18:31:26.111127 200 storage/replica.go:537  [n8,s7,r2213/1:/Table/55/1/700{76759…-87929…}] raftMu: mutex held by github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReady for 46.050459859s (>500ms):
logs/cockroach.stderr.6:W161107 18:31:26.111543 61563 storage/replica.go:537  [n8,s7,r10643/1:/Table/55/1/559{72439…-83677…}] raftMu: mutex held by github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRaftRequest for 52.148587161s (>500ms):
logs/cockroach.stderr.6:W161107 18:31:26.121846 206 storage/replica.go:537  [n8,s7,r403/1:/Table/52/1/"{OO\x92…-S\xb9\…}] raftMu: mutex held by github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReady for 46.056530353s (>500ms):
logs/cockroach.stderr.6:W161107 18:31:26.407302 223 storage/replica.go:537  [n8,s7,r10919/4:/Table/55/1/220{24135…-35254…}] raftMu: mutex held by github.com/cockroachdb/cockroach/pkg/storage.(*Store).RemoveReplica for 47.208720102s (>500ms):
logs/cockroach.stderr.6:W161107 18:31:27.149828 74915 storage/replica.go:537  [n8,s7,r2265/?:/Table/53/1/"{́\xa0…-\xccĬ…}] raftMu: mutex held by github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRaftRequest for 44.021766823s (>500ms):
```

That was apparently caused by 350k-key RemoveReplica:

    W161107 18:31:26.280307 223 storage/engine/rocksdb.go:1010  batch [357429/23938763/0] commit took 43.530565998s (>500ms):

There's a lot of these messages in the logs, and the same replicas being added to the replica GC queue many times before actually being deleted

```
I161107 18:30:39.608704 42190 storage/store.go:2964  [n8,s7] [n8,s7,r2819/1:/Table/55/1/4{485155…-597747…}]: added to replica GC queue (peer suggestion)
I161107 18:30:39.610512 42236 storage/store.go:2964  [n8,s7] [n8,s7,r8977/1:/Table/55/1/772{48924…-60183…}]: added to replica GC queue (peer suggestion)
I161107 18:30:39.618688 42043 storage/store.go:2964  [n8,s7] [n8,s7,r3084/1:/Table/55/1/41{67733…-79042…}]: added to replica GC queue (peer suggestion)
```

The replica GC queue was busy for a long time, but the problems also existed prior to the GC queue being busy.

![image](https://cloud.githubusercontent.com/assets/160562/20089987/5101a1e0-a5c5-11e6-90ec-921d67590d9a.png)

**Comment by petermattis** [comment]
@bdarnell I believe `COCKROACH_ENABLE_FAST_CLEAR_RANGE` addresses the remove replica slowness mentioned above. Is there anything else to do here?

**Comment by bdarnell** [comment]
My last comment says "the problems also existed prior to the GC queue being busy", so I'm not sure that FAST_CLEAR_RANGE will fix it, but I also don't think there's much value in keeping this old issue open.
