### ISSUE TITLE
sql: support aggregate functions with secondary arguments

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#10495]
We need aggregates with secondary arguments, 
needed to implement the more general function STRING_AGG (
https://www.postgresql.org/docs/9.2/static/functions-aggregate.html ) - #26737

Implementation-wise we could assume as a startin point that aggregation occurs always on the first argument; and use the values after the first as initializer arguments for the aggregate function object.

**Comment by yznming** [comment]
@knz I can try to fix it.

**Comment by knz** [comment]
ok!

**Comment by yznming** [comment]
@knz do you have any advice no how to get the delimiter if the second argument is a expression?
```
postgres=# select string_agg(name, (case when id>2 then '|' else ']' end)) from t
;
 string_agg
------------
 ss]sss|fww
(1 row)
```

**Comment by knz** [comment]
If you integrate the code like for other aggregate functions, the 2nd argument is already pre-evaluated.

So if you look at the other functions in `sql/parser/builtins.go` you see they use `args[0]`, `args[1]`, etc. for example `overlay`. You can convert the argument to `*DString` directly.

**Comment by heyihong** [comment]
Hi @knz , is this issue still open and unassigned? I'd like to try to fix it if possible.

**Comment by knz** [comment]
Yes the issue is still open an unassigned.

**Comment by cristhiank** [comment]
+1 for this issue. The Java JDBC Driver relies on the string_agg function to get the sql keywords as you can see in [this](https://github.com/pgjdbc/pgjdbc/blob/b1581e99b6da96b6e44753ce231ec3acf9869fea/pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java#L260) link.

**Comment by knz** [comment]
cc @awoods187 for prioritization.
