### ISSUE TITLE
sql: use memo metadata to add UDFs to statement bundle

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#104976]
We currently add UDFs to a statement bundle's schema.sql file with string matching:

https://github.com/cockroachdb/cockroach/blob/dea1354cbb2a992e714244691b3ecc85fcfc02b1/pkg/sql/explain_bundle.go#L832

Instead, we should use the metadata in the memo to determine which UDFs are relevant to the query. 

As an added bonus, it would be great to ensure that UDFs referenced in table expressions are included in statement bundles. For example:

```sql
CREATE FUNCTION add_one(x INT) RETURNS INT IMMUTABLE LANGUAGE SQL AS 'SELECT x + 1';

CREATE TABLE t (
  a INT,
  b INT AS (add_one(a)) STORED
);

EXPLAIN ANALYZE (DEBUG) SELECT * FROM t;
```

The `add_one` UDF should be included in the statement bundle.

Jira issue: CRDB-28808

**Comment by michae2** [comment]
Might be done?
