### ISSUE TITLE
db-console: unify routing on databases pages to with CC console

### ISSUE THREAD

**Issue by THardy98** [cockroachdb/cockroach#105011]
Currently, the databases pages on DB/CC console have different routing. Specifically, CC console paths take the form of:
`databases/<database name>/<schema name>/<table name>/<index name>`
while on DB console, paths take the form of:
`database/<database name>/table/<fully qualified table name>/index/<index name>`

The main pain point here is the difference between:
`<schema name>/<table name>`
and
`<fully qualified table name>`

Using the fully qualified table name becomes pretty cumbersome to work with once we take into account safely quoting it for SQL usage. In order to safely quote the fully qualified name, we first need to safely quote the schema name, then the table name, then we can construct the fully qualified name. From there, we are stuck using a safely quoted fully qualified name everywhere in the UI (i.e. `"schemaName"."tableName"`), as we currently do not have a way to reverse the safe quoting logic (we shouldn't need to). 

This means:
- we no longer have a way to easily get the original schema or table names (aside from `split` on the `.` between the names, which is error-prone)
- we lose the ability to get a table's schema/table name from the URL (instead we have to parse it from the fully qualified table name)
- we already get data from the server in the form of ` table_schema, table_name`, but we have to construct the fully qualified table name purely for routing purposes

We should unify the routing for these paths to follow CC console, which helps reduce the amount of code and maintain consistency between the two platforms.

Jira issue: CRDB-28823

**Comment by nkodali** [comment]
Closing as this is no longer relevant given the new databases page on 24.3.
