### ISSUE TITLE
storage: don't remove a replica that is a necessary part of current quorum

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#10506]
Per @bdarnell's [comment on #10483](https://github.com/cockroachdb/cockroach/issues/10483#issuecomment-258734351):

> We might want to consider this in rebalancing: don't remove a replica that is a necessary part of the current quorum. But it can be tricky to tell which nodes are necessary as the acknowledged indexes are always changing (and you'll go through at least two more rounds of consensus before the ChangeReplicas completes), so we'd need some sort of heuristic to tell when a replica is far enough behind that the other replicas should not be removed.

**Comment by a6802739** [comment]
@petermattis, I'm interested in this part. Could I have a see on this?

**Comment by petermattis** [comment]
@a6802739 Thanks for volunteering, but we haven't seen an urgent need for this yet (i.e. we haven't seen this problem in real clusters) and the part of the system that needs to be modified is seeing other changes at this time.

**Comment by a6802739** [comment]
oh, got it. Is there any other issues about `rebalance` or `storage` that I could start with?

**Comment by petermattis** [comment]
@a6802739 Let me take a look around. Rebalancing and the `storage` package are particularly sensitive from a stability perspective which necessitates serializing certain bits of work there.

**Comment by petermattis** [comment]
We now avoid transferring a lease to a replica that is behind. Similar smarts could be used to avoid removing a replica that is a necessary part of quorum.

**Comment by dianasaur323** [comment]
@petermattis I'm going to move this out of the 1.0 milestone for now and into Q2 2017. It seems like an interesting optimization, but not necessary for the 1.0 particularly given how much work we've already done here. Please move back if you disagree.

**Comment by petermattis** [comment]
This isn't an optimization, but a data availability issue. If we remove a replica that is a necessary part of the quorum, we could leave the range in a fragile state such that a node outage causes the range to become unavailable.

The code to avoid removing a replica that is a necessary part of quorum is likely small. As mentioned in one of the comments above, we already have the opposite heuristic to avoid transferring a replica to a lease that is too far behind.

**Comment by dianasaur323** [comment]
Got it, in that case it makes total sense to leave this in 1.0. I'm going to assign you on it. Mwahaha...

**Comment by petermattis** [comment]
I took a look at this last week and it was more involved than I thought. Punting to 1.1.
