### ISSUE TITLE
TestBackupMixedVersionElements_base_add_column_with_stored flaked on master

### ISSUE THREAD

**Issue by herkolategan** [cockroachdb/cockroach#105057]
See CI flake:

[TestBackupMixedVersionElements_base_add_column_with_stored](https://teamcity.cockroachdb.com/viewLog.html?buildId=10563281&tab=buildResultsDiv&buildTypeId=Cockroach_Ci_TestsGcpLinuxX8664BigVm_CclUnitTests#testNameId8387439225146341446)

[teamcity.cockroachdb.com/viewLog.html?buildId=10563281&tab=buildResultsDiv&buildTypeId=Cockroach_Ci_TestsGcpLinuxX8664BigVm_CclUnitTests](https://teamcity.cockroachdb.com/viewLog.html?buildId=10563281&tab=buildResultsDiv&buildTypeId=Cockroach_Ci_TestsGcpLinuxX8664BigVm_CclUnitTests)

Jira issue: CRDB-28842

**Comment by rafiss** [comment]
similar problem as https://github.com/cockroachdb/cockroach/issues/103896

**Comment by rafiss** [comment]
seems fixed by https://github.com/cockroachdb/cockroach/pull/105222 and https://github.com/cockroachdb/cockroach/pull/105191
