### ISSUE TITLE
c2c: better abstractions in physical replication setup

### ISSUE THREAD

**Issue by shermanCRL** [cockroachdb/cockroach#105067]
Our runbook for physical replication setup ([internal doc](https://docs.google.com/document/d/1vTX6N72J0yL2dDVdyJg063gC761QdZcMQ3ADthFYi8g/edit?usp=sharing)) is proving to be error prone for (so far internal) users. Certs are definitely part of it, getting various params right on connection strings, etc.

We do have some nice abstraction in `--config-profile replication-source`. Can we further automate it? Not just to save keystrokes, but to catch things that can go wrong, and either remediate or give users better instructions.

For v23.1, can we package up a `physical-replication.sh`? It wouldn’t necessarily have to be a supported public resource, but delivered to select users in private preview.

Could we expand `roachprod`?

For v23.2, perhaps it can go into the CLI `cockroach demo --physical-replication`

Jira issue: CRDB-28846
Epic CRDB-25146

**Comment by msbutler** [comment]
I'm unassigning myself from this as i've got higher priority stuff to work on over the next weeks. 

Further, I'm not entirely sure how generalizable a script could be here -- customers run stuff very different environments. Also, I feel like runbook scripting is more of a Customer Success task, no?

**Comment by shermanCRL** [comment]
Thanks, makes sense.

I hear you on a runbook being something for folks other than the implementers. But I think de facto it won’t move forward if we don’t move it forward. Also, it’s been a great lesson for us in terms of UX / acceptance testing.
