### ISSUE TITLE
kvserver: replica circuit breakers counterproductive under partial partitions

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#105167]
Consider this partial network partition:

```
         (gateway)
             n1
            /  \
           /    \
(leader) n2 xxxx n3 (leaseholder)
```

The leaseholder on n3 will be unable to propose writes to the leader on n1. With expiration-based leases, the lease will eventually expire, and get picked up by n2.

However, this scenario will cause n3's replica circuit breakers to fire, and the circuit breaker errors were specifically designed not to be retried. If n3 happens to have the lowest latency from n1's point of view, it will keep sending requests to n3 and immediately error out, before discovering the new lease on n2, resulting in permanent unavailabilty.

Jira issue: CRDB-28906

Epic CRDB-25200

**Comment by erikgrinaker** [comment]
Here's an example from running `failover/partial/lease-leader/lease=expiration` with `kv.replica_circuit_breaker.slow_replication_threshold = '10s'`. The leader and lease move just fine, but client requests still error out on the partitioned replica.

```
root@localhost:26257/defaultdb> select count(*) from kv.kv;                                                                                                                       
ERROR: replica unavailable: (n4,s4):4 unable to serve request to r378:/Table/106/1/-9{112802142307066208-094373826549114608} [(n6,s6):5, (n5,s5):2, (n4,s4):4, next=6, gen=30, sticky=9223372036.854775807,2147483647]: closed timestamp: 1687244453.964574387,0 (2023-06-20 07:00:53); raft status: {"id":"4","term":8,"vote":"0","commit":109,"lead":"0","raftState":"StatePreCandidate","applied":109,"progress":{},"leadtransferee":"0"}: operation "probe" timed out after 10s (given timeout 10s): result is ambiguous: after 10.00s of attempting command: context deadline exceeded
```

**Comment by erikgrinaker** [comment]
We're probably hitting the lease acquisition path, which errors out with the replica circuit breaker error here:

https://github.com/cockroachdb/cockroach/blob/6661c461617c714ee491cf3a0da39dd5ab151dbb/pkg/kv/kvserver/replica_range_lease.go#L1263-L1265

This error causes the DistSender to error out too, without trying other replicas or learning that this node is no longer the leaseholder.

**Comment by tbg** [comment]
Good catch - though is this really "counter-productive" and not just "not ideal yet"? Without replica circuit breakers, wouldn't we just get stuck on that replica since it would try to acquire a new lease? That seems like a worse failure mode (if the Replica knew a valid leader, I hope it would redirect).

I agree that DistSender handling of `ReplicaUnavailableError` (RUE) is insufficient. It should at the very least evict the cached leaseholder and try other replicas, though that again can subvert the fail-fast behavior. At some point DistSender probably needs a per-Replica circuit breaker to suitably limit the replicas it is willing to try. The fact that it will always try the local replica first when no leader is known is problematic.

**Comment by erikgrinaker** [comment]
> Without replica circuit breakers, wouldn't we just get stuck on that replica since it would try to acquire a new lease?

No, the lease acquisition would time out after a few seconds, and we'd return a NLHE to the DistSender. It would then go on to try other replicas until it discovered the leaseholder, updating its cache and resolving the problem. With circuit breakers, the DistSender will keep erroring indefinitely.

> It should at the very least evict the cached leaseholder and try other replicas, though that again can subvert the fail-fast behavior.

Yeah. We can probably handle it as a `sendError` in the DistSender, which I _think_ should end up with a permanent error once it tries all replicas (although reading the code I'm no longer so sure).

**Comment by erikgrinaker** [comment]
> That is at least the behavior I remember

Yeah, but I think that may be retried higher up the stack, after refreshing the descriptor.

**Comment by erikgrinaker** [comment]
This issue is mostly subsumed by #118266, will submit a fix for both shortly.
