### ISSUE TITLE
sql: add support for ARRAY operators and functions

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#10519]
Subissue of #2115.
See:
- https://www.postgresql.org/docs/9.6/static/functions-array.html 
- https://www.postgresql.org/docs/9.6/static/functions-comparisons.html

We currently have basic support for ARRAYs at the SQL interpreter level, but we do not support operators or functions acting on these arrays. 

The only operator needed immediately for Hibernate is `ANY` and the only function needed is `array_upper`.

**Comment by a6802739** [comment]
@nvanbenschoten, could I tackle this?

**Comment by nvanbenschoten** [comment]
Hi @a6802739, thanks for the interest, but I'm actually already working on this. I'd suggest you check out #10416, if @cuongdo hasn't already begun working on the issue.

**Comment by cuongdo** [comment]
I haven't started on #10416 yet, @a6802739. So, check it out and let us know if you want to tackle that issue.

**Comment by a6802739** [comment]
@cuongdo，yeah, I will try to fix #10416.

**Comment by knz** [comment]
Do we still have a need for ANY?

**Comment by nvanbenschoten** [comment]
@knz, yes, we still have a need for ANY. Now that #10717 is going in, it will be possible to generalize my previous work on the issue. I'll send out a change shortly.
