### ISSUE TITLE
acceptance: plumb contexts and improve stopper discipline

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#10510]
Our acceptance tests are currently a disaster with respect to contexts, cancellation, and timeouts. In many cases, we do odd things like create RPC clients in a loop, each time creating and destroying a stopper.

We should clean this up, primarily by plumbing contexts through everything so that we can have sane timeouts for things, and secondarily by associating a stopper with each test (or with the entire suite, in place of the `stopper chan struct{}` that we currently have).

**Comment by a6802739** [comment]
@tamird, I want to have a see on it. But I couldn't quite understand what you say, could you give me some examples?

**Comment by tamird** [comment]
@a6802739 great! Sure, basically if you grep for `context.TODO()` or `context.Background()` in `pkg/acceptance` you'll find a _ton_ of instances; what we want to do is reduce the number of places where we create these contexts and instead create them at the top level and pass them down into various methods. For a specific example, look at `cluster.Consistent()` - that function should take a context instead of calling `context.Background()`. Does that make sense?

**Comment by a6802739** [comment]
@tamird , you mean replace these `context.TODO()` or `context.Background()` with parameter like `context` which was generated by top level invoking?

**Comment by tamird** [comment]
Yep.

**Comment by a6802739** [comment]
@tamird, okay, I will try it.

**Comment by a6802739** [comment]
@tamird, I have a confusion here. 

If I use `stoppper := stop.NewStopper` to replace `stopper chan struct{}`, because `stopper chan struct{}` is a global variable, when should I run `stopper.Stop()` then? Or just when we receive a `interrupt` signal?

About `context` variable, should we generate a new `ctx` variable before we begin the test?

**Comment by tamird** [comment]
Indeed, probably only when we receive a signal.

Yep, creating a context when the test begins is probably the way to go.
