### ISSUE TITLE
sql: add support for ARRAY indexing

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#10518]
Subissue of #2115.
See https://www.postgresql.org/docs/9.6/static/arrays.html#ARRAYS-ACCESSING.

We currently have basic support for ARRAYs at the SQL interpreter level, but we do not support array indexing. We should add this support to permit proper functionality of Hibernate.

**Comment by knz** [comment]
wasn't this fixed by #10669?

**Comment by knz** [comment]
Closing this for now, re-open if I misunderstood something.

**Comment by nvanbenschoten** [comment]
The change you referenced added support for indexing array expressions, but not array columns. I'm going to reopen this for now and close it once that second need is met.

**Comment by knz** [comment]
Oh I just opened #11790 to react to Jordan's question on this. What do we do? Close one of the issues as dup of the other?

**Comment by nvanbenschoten** [comment]
Yes it looks like this can be closed in favor of the more specific issue. Thanks!
