### ISSUE TITLE
sql: table descriptor validator should ensure that all columns are in primary index key or store columns

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#105182]
A primary index should include every column in the table in either the `KeyColumnIDs` field or the `StoreColumnIDs` field (though I'm not sure this is true during schema migrations - is it?). It would be great if [`validateTableIndexes`](https://github.com/cockroachdb/cockroach/blob/c94698a190622e706dfce7c0b1475f04d31dafe9/pkg/sql/catalog/tabledesc/validate.go#L1278) guaranteed this invariant.

Jira issue: CRDB-28914

Epic CRDB-28665

**Comment by rafiss** [comment]
There already is a PostDeserializationChange for this. there should be validation too

**Comment by rafiss** [comment]
actually I thought https://github.com/cockroachdb/cockroach/pull/86071 had validation for this

let me read this more closely tomorrow
