### ISSUE TITLE
sql: add support for Set Returning (Generator) Functions

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#10520]
See https://www.postgresql.org/docs/9.6/static/functions-srf.html.

`generate_series` is needed for Hibernate.

@knz you mentioned you had thought of this before. Any thoughts here?

**Comment by knz** [comment]
Yes I found myself wanting of what they call `generate_series()` (I was thinking of `iota`), but also a VALUES clause with a repetition factor.

As to implementation: these are data sources, not "functions". The way this is plugged is by making FuncExpr implement the TableExpr interface and make the code in `data_source.go` look up functions from a set of "builtin generators" just next to / together with the lookup for virtual tables. 

I also see from the pg doc "WITH ORDINALITY" which, despite being grouped with set returning functions, is a rather different cattle of fish (and would probably be handled with a new planNode in our case tucked after limitNode).

**Comment by cuongdo** [comment]
how much effort do you think this is? can someone who's relatively new to our SQL code tackle this?

**Comment by knz** [comment]
Its easy to moderate. Yes I think it's appropriate for a sql beginner.

**Comment by nvanbenschoten** [comment]
It would be nice to have a somewhat general solution for this issue. Postgres supports a number of other functions that can return multiple rows, such as `regexp_matches` and `regexp_split_to_table` (see https://www.postgresql.org/docs/9.6/static/functions-matching.html). While we don't need to support these right away, it would be wise to create the requisite infrastructure to support functions like these when we get around to them.

@knz confirmed my guess about the way we'd want to support this (ie. implement them as `planDataSource`s), and I agree with his later assessment. I also have a sneaking suspicion that we may be able to share some code with virtual tables.

**Comment by knz** [comment]
Also `unnest` for #5582
