### ISSUE TITLE
Sentry: db.go:812: log.Fatal: pebble: fatal commit error: write ×: disk quota exceeded
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/pebble.(*DB).applyInternal
  | 	github.com...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#105264]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4265050312/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4265050312/?referrer=webhooks_plugin)

Panic Message:

```
db.go:812: log.Fatal: pebble: fatal commit error: write ×: disk quota exceeded
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/pebble.(*DB).applyInternal
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go:812
  | github.com/cockroachdb/pebble.(*DB).Apply
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go:747
  | github.com/cockroachdb/pebble.(*Batch).Commit
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/batch.go:1155
  | github.com/cockroachdb/cockroach/pkg/storage.(*pebbleBatch).Commit
  | 	github.com/cockroachdb/cockroach/pkg/storage/pebble_batch.go:556
  | github.com/cockroachdb/cockroach/pkg/storage.WriteSyncNoop
  | 	github.com/cockroachdb/cockroach/pkg/storage/engine.go:1399
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/liveness.(*NodeLiveness).updateLiveness.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/liveness/liveness.go:1309
  | github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight.(*Group).doCall.func1
  | 	github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight/singleflight.go:387
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTask
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:305
  | github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight.(*Group).doCall
  | 	github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight/singleflight.go:386
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (2) secondary error attachment
  | write ×: disk quota exceeded
  | (1) attached stack trace
  |   -- stack trace:
  |   | github.com/cockroachdb/pebble/vfs.(*syncingFile).Write
  |   | 	github.com/cockroachdb/pebble/vfs/external/com_github_cockroachdb_pebble/vfs/syncing_file.go:67
  |   | github.com/cockroachdb/pebble/record.(*LogWriter).flushBlock
  |   | 	github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go:551
  |   | github.com/cockroachdb/pebble/record.(*LogWriter).flushPending
  |   | 	github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go:520
  |   | github.com/cockroachdb/pebble/record.(*LogWriter).flushLoop
  |   | 	github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go:466
  |   | runtime/pprof.Do
  |   | 	GOROOT/src/runtime/pprof/runtime.go:40
  |   | github.com/cockroachdb/pebble/record.NewLogWriter.func2
  |   | 	github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go:351
  |   | runtime.goexit
  |   | 	GOROOT/src/runtime/asm_amd64.s:1594
  | Wraps: (2) write ×
  | Wraps: (3) disk quota exceeded
  | Error types: (1) *withstack.withStack (2) *fs.PathError (3) syscall.Errno
Wraps: (3) log.Fatal: pebble: fatal commit error: write ×: disk quota exceeded
Error types: (1) *withstack.withStack (2) *secondary.withSecondaryError (3) *errutil.leafError
-- report composition:
*errutil.leafError: log.Fatal: pebble: fatal commit error: write ×: disk quota exceeded
*secondary.withSecondaryError: details for github.com/cockroachdb/errors/withstack/*withstack.withStack:::
db.go:812: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#1594L1593-L1595](GOROOT/src/runtime/asm_amd64.s#1594L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/util/syncutil/singleflight/singleflight.go#386L385-L387](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/util/syncutil/singleflight/singleflight.go#386L385-L387)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/util/stop/stopper.go#305L304-L306](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/util/stop/stopper.go#305L304-L306)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/util/syncutil/singleflight/singleflight.go#387L386-L388](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/util/syncutil/singleflight/singleflight.go#387L386-L388)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/kv/kvserver/liveness/liveness.go#1309L1308-L1310](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/kv/kvserver/liveness/liveness.go#1309L1308-L1310)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/storage/engine.go#1399L1398-L1400](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/storage/engine.go#1399L1398-L1400)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/storage/pebble_batch.go#556L555-L557](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/storage/pebble_batch.go#556L555-L557)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/batch.go#1155L1154-L1156](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/batch.go#1155L1154-L1156)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#747L746-L748](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#747L746-L748)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#812L811-L813](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#812L811-L813)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/util/syncutil/singleflight/singleflight.go in pkg/util/syncutil/singleflight.(*Group).doCall at line 386
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunTask at line 305
pkg/util/syncutil/singleflight/singleflight.go in pkg/util/syncutil/singleflight.(*Group).doCall.func1 at line 387
pkg/kv/kvserver/liveness/liveness.go in pkg/kv/kvserver/liveness.(*NodeLiveness).updateLiveness.func1 at line 1309
pkg/storage/engine.go in pkg/storage.WriteSyncNoop at line 1399
pkg/storage/pebble_batch.go in pkg/storage.(*pebbleBatch).Commit at line 556
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/batch.go in github.com/cockroachdb/pebble.(*Batch).Commit at line 1155
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go in github.com/cockroachdb/pebble.(*DB).Apply at line 747
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go in github.com/cockroachdb/pebble.(*DB).applyInternal at line 812
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v23.1.3 |
| Go Version | go1.19.4 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.3 |
| Cockroach SHA | c663f843fa3e1a87855a18f9678291f35eeef394 |
| # of CPUs | 8 |
| # of Goroutines | 563 |

Jira issue: CRDB-28951

**Comment by yuzefovich** [comment]
dup of #86703
