### ISSUE TITLE
ui: users without `system.table_statistics` privileges cannot view database table page

### ISSUE THREAD

**Issue by THardy98** [cockroachdb/cockroach#105292]
**Describe the problem**

Currently, users without `system.table_statistics` `SELECT` privilege cannot use the database table page as the query error causes the entire page to render a fallback error component.

The page should be able to render as normally, displaying the table statistics as unavailable

Jira issue: CRDB-28966

**Comment by rafiss** [comment]
Note that v23.1.11 will have a `VIEWSYSTEMTABLE` system privilege.

If you do `GRANT SYSTEM VIEWSYSTEMTABLE TO user`, that user will have the SELECT privilege on all system tables.

**Comment by THardy98** [comment]
Below are PRs that allow users with restricted permissions to still view the databases pages:

Databases Page Improvement: https://github.com/cockroachdb/cockroach/pull/109245
Database Detail Page Improvement: https://github.com/cockroachdb/cockroach/pull/109432
Table Detail Page Improvement (database table page - specifically relevant to this issue): https://github.com/cockroachdb/cockroach/pull/109521
