### ISSUE TITLE
Sentry: db.go:812: log.Fatal: pebble: fatal commit error: write ×: disk quota exceeded
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/pebble.(*DB).applyInternal
  | 	github.com...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#105265]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4265053338/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4265053338/?referrer=webhooks_plugin)

Panic Message:

```
db.go:812: log.Fatal: pebble: fatal commit error: write ×: disk quota exceeded
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/pebble.(*DB).applyInternal
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go:812
  | github.com/cockroachdb/pebble.(*DB).Apply
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go:747
  | github.com/cockroachdb/pebble.(*DB).Set
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go:600
  | github.com/cockroachdb/cockroach/pkg/storage.(*Pebble).put
  | 	github.com/cockroachdb/cockroach/pkg/storage/pebble.go:1608
  | github.com/cockroachdb/cockroach/pkg/storage.(*Pebble).PutUnversioned
  | 	github.com/cockroachdb/cockroach/pkg/storage/pebble.go:1585
  | github.com/cockroachdb/cockroach/pkg/storage.(*putBuffer).putInlineMeta
  | 	github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:1393
  | github.com/cockroachdb/cockroach/pkg/storage.mvccPutInternal
  | 	github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:1810
  | github.com/cockroachdb/cockroach/pkg/storage.mvccPutUsingIter
  | 	github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:1548
  | github.com/cockroachdb/cockroach/pkg/storage.MVCCPut
  | 	github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:1465
  | github.com/cockroachdb/cockroach/pkg/storage.MVCCPutProto
  | 	github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:847
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).setLastReplicaGCTimestamp
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica.go:1380
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*replicaGCQueue).process
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_gc_queue.go:264
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*baseQueue).processReplica.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/queue.go:1012
  | github.com/cockroachdb/cockroach/pkg/util/contextutil.RunWithTimeout
  | 	github.com/cockroachdb/cockroach/pkg/util/contextutil/context.go:91
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*baseQueue).processReplica
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/queue.go:971
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*baseQueue).processLoop.func2.1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/queue.go:882
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (2) secondary error attachment
  | write ×: disk quota exceeded
  | (1) attached stack trace
  |   -- stack trace:
  |   | github.com/cockroachdb/pebble/vfs.(*syncingFile).Write
  |   | 	github.com/cockroachdb/pebble/vfs/external/com_github_cockroachdb_pebble/vfs/syncing_file.go:67
  |   | github.com/cockroachdb/pebble/record.(*LogWriter).flushBlock
  |   | 	github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go:551
  |   | github.com/cockroachdb/pebble/record.(*LogWriter).flushPending
  |   | 	github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go:520
  |   | github.com/cockroachdb/pebble/record.(*LogWriter).flushLoop
  |   | 	github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go:466
  |   | runtime/pprof.Do
  |   | 	GOROOT/src/runtime/pprof/runtime.go:40
  |   | github.com/cockroachdb/pebble/record.NewLogWriter.func2
  |   | 	github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go:351
  |   | runtime.goexit
  |   | 	GOROOT/src/runtime/asm_amd64.s:1594
  | Wraps: (2) write ×
  | Wraps: (3) disk quota exceeded
  | Error types: (1) *withstack.withStack (2) *fs.PathError (3) syscall.Errno
Wraps: (3) log.Fatal: pebble: fatal commit error: write ×: disk quota exceeded
Error types: (1) *withstack.withStack (2) *secondary.withSecondaryError (3) *errutil.leafError
-- report composition:
*errutil.leafError: log.Fatal: pebble: fatal commit error: write ×: disk quota exceeded
*secondary.withSecondaryError: details for github.com/cockroachdb/errors/withstack/*withstack.withStack:::
db.go:812: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#1594L1593-L1595](GOROOT/src/runtime/asm_amd64.s#1594L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/util/stop/stopper.go#470L469-L471](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/util/stop/stopper.go#470L469-L471)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/kv/kvserver/pkg/kv/kvserver/queue.go#882L881-L883](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/kv/kvserver/pkg/kv/kvserver/queue.go#882L881-L883)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/kv/kvserver/pkg/kv/kvserver/queue.go#971L970-L972](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/kv/kvserver/pkg/kv/kvserver/queue.go#971L970-L972)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/util/contextutil/context.go#91L90-L92](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/util/contextutil/context.go#91L90-L92)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/kv/kvserver/pkg/kv/kvserver/queue.go#1012L1011-L1013](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/kv/kvserver/pkg/kv/kvserver/queue.go#1012L1011-L1013)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/kv/kvserver/pkg/kv/kvserver/replica_gc_queue.go#264L263-L265](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/kv/kvserver/pkg/kv/kvserver/replica_gc_queue.go#264L263-L265)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/kv/kvserver/pkg/kv/kvserver/replica.go#1380L1379-L1381](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/kv/kvserver/pkg/kv/kvserver/replica.go#1380L1379-L1381)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/storage/mvcc.go#847L846-L848](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/storage/mvcc.go#847L846-L848)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/storage/mvcc.go#1465L1464-L1466](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/storage/mvcc.go#1465L1464-L1466)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/storage/mvcc.go#1548L1547-L1549](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/storage/mvcc.go#1548L1547-L1549)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/storage/mvcc.go#1810L1809-L1811](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/storage/mvcc.go#1810L1809-L1811)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/storage/mvcc.go#1393L1392-L1394](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/storage/mvcc.go#1393L1392-L1394)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/storage/pebble.go#1585L1584-L1586](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/storage/pebble.go#1585L1584-L1586)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/storage/pebble.go#1608L1607-L1609](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/storage/pebble.go#1608L1607-L1609)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#600L599-L601](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#600L599-L601)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#747L746-L748](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#747L746-L748)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#812L811-L813](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#812L811-L813)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 470
pkg/kv/kvserver/pkg/kv/kvserver/queue.go in pkg/kv/kvserver.(*baseQueue).processLoop.func2.1 at line 882
pkg/kv/kvserver/pkg/kv/kvserver/queue.go in pkg/kv/kvserver.(*baseQueue).processReplica at line 971
pkg/util/contextutil/context.go in pkg/util/contextutil.RunWithTimeout at line 91
pkg/kv/kvserver/pkg/kv/kvserver/queue.go in pkg/kv/kvserver.(*baseQueue).processReplica.func1 at line 1012
pkg/kv/kvserver/pkg/kv/kvserver/replica_gc_queue.go in pkg/kv/kvserver.(*replicaGCQueue).process at line 264
pkg/kv/kvserver/pkg/kv/kvserver/replica.go in pkg/kv/kvserver.(*Replica).setLastReplicaGCTimestamp at line 1380
pkg/storage/mvcc.go in pkg/storage.MVCCPutProto at line 847
pkg/storage/mvcc.go in pkg/storage.MVCCPut at line 1465
pkg/storage/mvcc.go in pkg/storage.mvccPutUsingIter at line 1548
pkg/storage/mvcc.go in pkg/storage.mvccPutInternal at line 1810
pkg/storage/mvcc.go in pkg/storage.(*putBuffer).putInlineMeta at line 1393
pkg/storage/pebble.go in pkg/storage.(*Pebble).PutUnversioned at line 1585
pkg/storage/pebble.go in pkg/storage.(*Pebble).put at line 1608
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go in github.com/cockroachdb/pebble.(*DB).Set at line 600
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go in github.com/cockroachdb/pebble.(*DB).Apply at line 747
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go in github.com/cockroachdb/pebble.(*DB).applyInternal at line 812
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v23.1.3 |
| Go Version | go1.19.4 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.3 |
| Cockroach SHA | c663f843fa3e1a87855a18f9678291f35eeef394 |
| # of CPUs | 12 |
| # of Goroutines | 485 |

Jira issue: CRDB-28952

**Comment by erikgrinaker** [comment]
There isn't much to be done here. The node ran out of disk (it hit the quota allocated by the operator).
