### ISSUE TITLE
sql: support []int type

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#10523]
This is needed for Hibernate.

`pg_constraint.conkey` and `pg_constraint.confkey` are currently `STRING`s, but need to be indexable `[]int` fields.

Example query (notice the `WHERE` clause):
```
SELECT ...
FROM  pg_catalog.pg_namespace pkn, pg_catalog.pg_class pkc, pg_catalog.pg_attribute pka,  pg_catalog.pg_namespace fkn, pg_catalog.pg_class fkc, pg_catalog.pg_attribute fka,  pg_catalog.pg_constraint con,  pg_catalog.generate_series(1, 32) pos(n),  pg_catalog.pg_depend dep, pg_catalog.pg_class pkic
WHERE .. AND pka.attnum = con.confkey[pos.n] AND ... AND fka.attnum = con.conkey[pos.n]
....
```

**Comment by cuongdo** [comment]
Note that this also requires adding support for creating `[]int` fields in `CREATE TABLE`, because our virtual tables are created that way.

**Comment by knz** [comment]
I just discussed this with Nathan, he thinks I'm in a better position to achieve this. Are you ok with that?

**Comment by cuongdo** [comment]
Sure, though I do have some code to extend `parser.{TypeArray/DArray}` to
handle arrays of different types. I've removed the assumption that all
arrays contain just `string`s. Shall I submit the PR for that, or do you
want to take over that work?

**Comment by knz** [comment]
On 09-11-16 23:23, Cuong Do wrote:
> Sure, though I do have some code to extend `parser.{TypeArray/DArray}` to
> handle arrays of different types. I've removed the assumption that all
> arrays contain just `string`s. Shall I submit the PR for that, or do you
> want to take over that work?

Well if you already have the code ready, that's GREAT!

Just make the PR and let nathan have a look. You got our back!

-- 
Raphael 'kena' Poss

**Comment by cuongdo** [comment]
The second part of the change is to support `int[]` column types, which are
needed, because the `pg_catalog` tables are all created using `CREATE
TABLE`. There are some fields in one of those tables that has an `int[]`
column type. So, work is needed to wire up the SQL grammar to support the
`int[]` type. I've started that work, but since this is my first time
touching the SQL grammar, I'm not sure how much more work remains there.

**Comment by knz** [comment]
On 09-11-16 23:29, Cuong Do wrote:
> I've started that work, but since this is my first time
> touching the SQL grammar, I'm not sure how much more work remains there.

Oh ok thanks. Let Nathan or me know if you need anything explained.

-- 
Raphael 'kena' Poss
