### ISSUE TITLE
roachtest/cluster: ConnE should be aware of port customization

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#105230]
**Describe the problem**

The `(Cluster).ConnE` interface does not correctly handle a cluster that was started with non-default port.

**Expected behavior**

The function should be able to know that the port was customized, and use that one instead.

See https://github.com/cockroachdb/cockroach/pull/105223 for an example of when we had to workaround this.

Jira issue: CRDB-28930

**Comment by renatolabs** [comment]
Could this be consolidated with #104692?

**Comment by rafiss** [comment]
Seems like it could for sure. I wasn't aware of that issue, thanks!

cc @herkolategan since I see you're working with port management (https://cockroachlabs.slack.com/archives/C02P01CDKKP/p1687358001467229)

**Comment by herkolategan** [comment]
@rafiss Thanks for pointing it out, I'll try and aim to extend our current solution to include flexibility around the base port (system tenant) as well.

**Comment by renatolabs** [comment]
This has been fixed for a while, closing.
