### ISSUE TITLE
Sentry: syncing_file.go:67: write ×: disk quota exceeded
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | github.com/cockroachdb/cockroach/pkg/s...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#105263]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4265049999/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4265049999/?referrer=webhooks_plugin)

Panic Message:

```
syncing_file.go:67: write ×: disk quota exceeded
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | github.com/cockroachdb/cockroach/pkg/storage.(*pebbleBatch).SyncWait
  | 	github.com/cockroachdb/cockroach/pkg/storage/pebble_batch.go:605
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/logstore.(*SyncWaiterLoop).waitLoop
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/logstore/sync_waiter.go:95
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/logstore.(*SyncWaiterLoop).Start.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/logstore/sync_waiter.go:84
  | [...repeated from below...]
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/pebble/vfs.(*syncingFile).Write
  | 	github.com/cockroachdb/pebble/vfs/external/com_github_cockroachdb_pebble/vfs/syncing_file.go:67
  | github.com/cockroachdb/pebble/record.(*LogWriter).flushBlock
  | 	github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go:551
  | github.com/cockroachdb/pebble/record.(*LogWriter).flushPending
  | 	github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go:520
  | github.com/cockroachdb/pebble/record.(*LogWriter).flushLoop
  | 	github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go:466
  | runtime/pprof.Do
  | 	GOROOT/src/runtime/pprof/runtime.go:40
  | github.com/cockroachdb/pebble/record.NewLogWriter.func2
  | 	github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go:351
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (3) write ×
Wraps: (4) disk quota exceeded
Error types: (1) *withstack.withStack (2) *withstack.withStack (3) *fs.PathError (4) syscall.Errno
-- report composition:
syscall.Errno
*fs.PathError
syncing_file.go:67: *withstack.withStack (top exception)
panic.go:884: *withstack.withStack (1)
(check the extra data payloads)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#1594L1593-L1595](GOROOT/src/runtime/asm_amd64.s#1594L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/util/stop/stopper.go#470L469-L471](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/util/stop/stopper.go#470L469-L471)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/kv/kvserver/logstore/sync_waiter.go#84L83-L85](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/kv/kvserver/logstore/sync_waiter.go#84L83-L85)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/kv/kvserver/logstore/sync_waiter.go#95L94-L96](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/kv/kvserver/logstore/sync_waiter.go#95L94-L96)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/storage/pebble_batch.go#605L604-L606](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/storage/pebble_batch.go#605L604-L606)
[GOROOT/src/runtime/panic.go#884L883-L885](GOROOT/src/runtime/panic.go#884L883-L885)
[GOROOT/src/runtime/asm_amd64.s#1594L1593-L1595](GOROOT/src/runtime/asm_amd64.s#1594L1593-L1595)
[github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go#351L350-L352](github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go#351L350-L352)
[GOROOT/src/runtime/pprof/runtime.go#40L39-L41](GOROOT/src/runtime/pprof/runtime.go#40L39-L41)
[github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go#466L465-L467](github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go#466L465-L467)
[github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go#520L519-L521](github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go#520L519-L521)
[github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go#551L550-L552](github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go#551L550-L552)
[github.com/cockroachdb/pebble/vfs/external/com_github_cockroachdb_pebble/vfs/syncing_file.go#67L66-L68](github.com/cockroachdb/pebble/vfs/external/com_github_cockroachdb_pebble/vfs/syncing_file.go#67L66-L68)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 470
pkg/kv/kvserver/logstore/sync_waiter.go in pkg/kv/kvserver/logstore.(*SyncWaiterLoop).Start.func1 at line 84
pkg/kv/kvserver/logstore/sync_waiter.go in pkg/kv/kvserver/logstore.(*SyncWaiterLoop).waitLoop at line 95
pkg/storage/pebble_batch.go in pkg/storage.(*pebbleBatch).SyncWait at line 605
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go in github.com/cockroachdb/pebble/record.NewLogWriter.func2 at line 351
GOROOT/src/runtime/pprof/runtime.go in runtime/pprof.Do at line 40
github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go in github.com/cockroachdb/pebble/record.(*LogWriter).flushLoop at line 466
github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go in github.com/cockroachdb/pebble/record.(*LogWriter).flushPending at line 520
github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go in github.com/cockroachdb/pebble/record.(*LogWriter).flushBlock at line 551
github.com/cockroachdb/pebble/vfs/external/com_github_cockroachdb_pebble/vfs/syncing_file.go in github.com/cockroachdb/pebble/vfs.(*syncingFile).Write at line 67
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v23.1.3 |
| Go Version | go1.19.4 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.3 |
| Cockroach SHA | c663f843fa3e1a87855a18f9678291f35eeef394 |
| # of CPUs | 8 |
| # of Goroutines | 563 |

Jira issue: CRDB-28950

**Comment by yuzefovich** [comment]
dup of #86703
