### ISSUE TITLE
metrics: Monitor /proc/diskstats

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#10533]
When running on linux, we should read `/proc/diskstats` (hopefully via some existing library) periodically and create metrics for the I/O of the disk(s) that contain our store(s). These metrics would be useful to show in the UI.

**Comment by a6802739** [comment]
@bdarnell, I could have a see for this.

**Comment by bdarnell** [comment]
Cool, go ahead.

**Comment by dianasaur323** [comment]
Assigning to @mberhault. I think having the I/O metrics would be good for 1.0, and we can punt on having them show up in the admin UI until Q2 2017. Please re-adjust and re-assign if you disagree.

**Comment by petermattis** [comment]
Not sure if we need this for 1.0. We could recommend running the [Prometheus node_exporter](https://github.com/prometheus/node_exporter).

If we do add disk metrics, we could use the Prometheus [collector](https://github.com/prometheus/node_exporter/tree/master/collector) for grabbing them.

**Comment by dianasaur323** [comment]
Ok, I was unaware that we could pull those metrics easily. Let's move this out!

**Comment by mberhault** [comment]
This was added in https://github.com/cockroachdb/cockroach/pull/27137
