### ISSUE TITLE
sql: version gating for new UDF features

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#105365]
For newly added UDF features in v23.2, determine if we need to version gate them and do so. See https://github.com/cockroachdb/cockroach/pull/90842 and https://github.com/cockroachdb/cockroach/pull/92957 for example of version-gating features.

Jira issue: CRDB-29000

**Comment by michae2** [comment]
[notes from triage] Looks like this has been fixed by https://github.com/cockroachdb/cockroach/pull/112148 plus some other PRs, closing.
