### ISSUE TITLE
ui: Explain plan show P90, P95, P99

### ISSUE THREAD

**Issue by j82w** [cockroachdb/cockroach#105371]
The explain plan should show the P90, P95, P99 per a plan. The information should be available in the statistics table already. This is needed to better help understand the latency difference between plans. 

<img width="2447" alt="Screenshot 2023-06-22 at 2 20 22 PM" src="https://github.com/cockroachdb/cockroach/assets/8868107/e59ae3d9-410c-4b2c-924b-7af474bb5766">

Jira issue: CRDB-29003

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[17474](https://cockroachdb.zendesk.com/agent/tickets/17474) has been linked to this issue.
