### ISSUE TITLE
Expiration based leases: scalability + performance testing for 23.2

### ISSUE THREAD

**Issue by williamkulju** [cockroachdb/cockroach#105350]
To the extent expiration based leases will have an impact on scalability + performance, we want to do some internal testing to understand the scale at which things start to degrade (if at all) and how quickly so that we can enable Field engineers to advise customers adopting 23.2 when they should / should not turn on expiration based leases and what the trade-offs might be. 

This issue tracks that internal test work. The output of this work should be test results that show scale / performance for a variety of representative S/M/L workloads with and without expiration based leases enabled.

Jira issue: CRDB-28997

Epic CRDB-25212

**Comment by erikgrinaker** [comment]
Cost results in https://docs.google.com/spreadsheets/d/1eM-K2S77azUipbItpU7wK7z8jEgAiaVpzKjqfgMznSQ/edit#gid=0.

> The output of this work should be test results that show scale / performance for a variety of representative S/M/L workloads with and without expiration based leases enabled.

The costs scale with replica density, independently of workload.
