### ISSUE TITLE
kvflowcontroller: mutex contention

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#105508]
`kv0/enc=false/nodes=3/cpu=96` is showing significant mutex contention on `kvflowcontroller.Controller.mu`:

<img width="1213" alt="Screenshot 2023-06-24 at 15 41 42" src="https://github.com/cockroachdb/cockroach/assets/644420/fc789813-0ef4-4c68-b3a5-4940328bf7f1">

This is possibly the cause of a significant performance regression on this benchmark:

<img width="788" alt="Screenshot 2023-06-24 at 15 42 40" src="https://github.com/cockroachdb/cockroach/assets/644420/6a72fcd0-77da-4349-9c1d-6b7043b4c587">

Jira issue: CRDB-29088

**Comment by irfansharif** [comment]
Clawed back the throughput loss with https://github.com/cockroachdb/cockroach/pull/106466.

<img width="1665" alt="image" src="https://github.com/cockroachdb/cockroach/assets/10536690/974244d8-517f-4196-a218-9dc5d20b6be4">
