### ISSUE TITLE
ci: add Azure CLI and credentials to roachtest nightly workers

### ISSUE THREAD

**Issue by samiskin** [cockroachdb/cockroach#105580]
Discussion: https://cockroachlabs.slack.com/archives/C023S0V4YEB/p1687811956702389

To support running roachtests that hit Azure Event Hub endpoints, the CDC team would like the machines running the roachtest code to have access to the Azure CLI and be logged in (`az login`).

This would allow us to run commands such as `az eventhubs namespace authorization-rule keys list` to read the credentials we need  (ex: https://github.com/cockroachdb/cockroach/pull/105576).

Jira issue: CRDB-29111

Epic CRDB-29896

**Comment by amruss** [comment]
@rail is this going to be worked on ahead of 23.2?

**Comment by healthy-pod** [comment]
This work is in-progress and we aim to get done before the week of Sep 18.
