### ISSUE TITLE
roachtest: ensure goroutines in MixedVersionCDC finish before test harness returns.

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#105556]
In #105401, we discovered the mixed version cdc roachtest driver does not explicitly wait for all goroutines to get fixed. For starters, see this naive and incorrect implementation[ here](https://github.com/cockroachdb/cockroach/pull/105401#discussion_r1242282051).

Jira issue: CRDB-29107

**Comment by renatolabs** [comment]
Closing as this no longer applies now that the mixed-version CDC test has been adapted to run on the `mixedversion` framework.
