### ISSUE TITLE
storage: panic: mutex held for > 100ms

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#10567]
mutex held by github.com/cockroachdb/cockroach/pkg/storage.(*storeReplicaVisitor).Visit for 100.926538ms (>100ms):

https://teamcity.cockroachdb.com/viewLog.html?buildId=43819&buildTypeId=Cockroach_Nightlies_RandomSyntaxTests

Found with RSG.

**Comment by jordanlewis** [comment]
That message is merely a warning. The actual panic is the following:

```
0:16:56]W161109 05:16:56.595257 238201 util/hlc/hlc.go:145  backward time jump detected (-0.368028 seconds)
[00:16:56]panic: pq: storage/store.go:2246: rejecting command with timestamp in the future: 1478668616963260583 (367.66607ms ahead)
```

Unfortunately, this might be an artifact of Azure's seemingly poor VM clocks.

**Comment by a-robinson** [comment]
I came here to say what @jordanlewis said. The mutex stack dump isn't a correctness issue, the clock is the problem.

**Comment by RaduBerinde** [comment]
Normally a monotonic timer source should be used for this kind of "delta" calculations. Unfortunately there isn't a standard one in Go (https://github.com/golang/go/issues/12914). That discussion mentions a package: https://github.com/aristanetworks/goarista/tree/master/monotime

**Comment by mjibson** [comment]
Doh. Thanks for the correction. Closing because I'm just assuming this is an Azure problem.

**Comment by RaduBerinde** [comment]
Filed #10572 for my previous comment.
