### ISSUE TITLE
kvserver: fix txn/intent cleanup on client context cancellation

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#105615]
In `TestReliableIntentCleanup` we've seen (#66895) that intent and txn cleanup doesn't always happen in cases where the client goes away before/during txn finalization. It should.

These cases (`finalize: cancel` and `cancelAsync`) have been skipped in the test. They should be re-enabled, and should not be flaky after many runs.

Jira issue: CRDB-29128

**Comment by arulajmani** [comment]
Closing in favour of https://github.com/cockroachdb/cockroach/issues/66895.
