### ISSUE TITLE
sql: allow updates to remove multiregion or convert to single region easily

### ISSUE THREAD

**Issue by fqazi** [cockroachdb/cockroach#105623]
For certain use cases, customers need the ability to restore multi-region databases onto a single region cluster, and if they are doing this for the purpose of testing, they may not have a full enterprise license in these environments. To help support this use case, we should consider one of the following options:

- Add a new option to strip region information on restore (or at the very least get it into a single region)
- Add a cluster setting escape hatch which lets them do the invalid update by skipping all validation (the end result is unsupported)
- Lift the licensing limitation if you have only a single valid region (this is tricky, but I think doable)

Previously, this worked fine, but with PR https://github.com/cockroachdb/cockroach/pull/86538 we started adding more validation that prevents this.

Also see https://github.com/cockroachdb/cockroach/issues/100913 and https://github.com/cockroachdb/cockroach/issues/103290 for other fallout from that PR.

Jira issue: CRDB-29129

Epic CRDB-27601

gz#18650

**Comment by rafiss** [comment]
Let's see which option @dikshant would like when he's back, and also see his opinion on priority of this.

**Comment by dikshant** [comment]
I think stripping the region info here would be the best way forward.
