### ISSUE TITLE
schema: schema change restart loop with fatal error

### ISSUE THREAD

**Issue by ecwall** [cockroachdb/cockroach#105632]
The schema backfiller can get stuck in a retry loop if its batch timestamp is before the GC TTL timestamp https://github.com/cockroachlabs/support/issues/2412#issuecomment-1609529779

It should either update the timestamp (is this possible?) or the job should fail with this error instead of continually retrying.

It should be possible to test this with a testing knob that sets the batch timestamp that the job uses to before the GC TTL timestamp.

Jira issue: CRDB-29132

Epic CRDB-35306

**Comment by rafiss** [comment]
The problem here might be that the error is retryable, but CREATE MATERIALIZED VIEW could be running with a fixed timestamp, so retrying will not work.

Let's check this theory. If so, we should change the logic to stop retrying if the timestamp is fixed.

**Comment by ajwerner** [comment]
For everything other than `CREATE MATERIALIZED VIEW` and `CREATE TABLE AS`, I think the retry is the right behavior. The bad behavior is the exponential backoff. For `CREATE MATERIALIZED VIEW` and `CREATE TABLE AS`, the right answer is almost certainly to lay down a protected timestamp. See https://github.com/cockroachdb/cockroach/pull/89540. The infrastructure exists to make this all work. cc @fqazi

**Comment by ajwerner** [comment]
Also yes, what Rafi says is a reasonable short-term solution. Probably best to do both.
