### ISSUE TITLE
jobs: migration to add job_type causes too much contention

### ISSUE THREAD

**Issue by jayshrivastava** [cockroachdb/cockroach#105663]
See https://cockroachlabs.slack.com/archives/C04N0AS14CT/p1687897409947369.

The migration which adds `job_type` to `system.jobs` attempts to do it on one transaction. This locks up the whole jobs table. We should batch these updates. 

Jira issue: CRDB-29143

**Comment by jayshrivastava** [comment]
cc @alyshanjahani-crl

**Comment by dt** [comment]
I'm removing `release-blocker` for 23.1 since this isn't a regression compared to existing 23.1 releases so we don't need to hold up any pending patch releases while we work on the fix.
