### ISSUE TITLE
ui: be able to select specific time range and a way to enlarge the graph for better viewing

### ISSUE THREAD

**Issue by chinglinwen** [cockroachdb/cockroach#10560]
I found these two problems while I using the UI graph to diagnose something

The mouse is so hard to move accurate when the interval is large, When the interval is small (and view it at later( 1 hour later viewing 10 minutes graph) the detail is missed

So two of issue here

1. To be able to select specific time range ( say absolute start time - > absolute end time ) accurate to seconds is sensible ( the maximum range in a day is sensible too )

2. A way(say a click) to enlarge the graph ( for the difficulty of mouse moving for the unit of second) ( and may easier  to see more detail when it in large ) 

Version:

```
Build Tag:   beta-20161027
Build Time:  2016/10/27 13:34:56
Platform:    linux amd64
Go Version:  go1.7.3
C Compiler:  gcc 4.9.2
```

**Comment by dianasaur323** [comment]
@chinglinwen Thanks for your feedback! We are actually going to be building a revamp of our admin UI going forward, so I'm going to close out this issue for now.
