### ISSUE TITLE
sql: TestValidateMixedVersionElements_drop_column_with_index timeout

### ISSUE THREAD

**Issue by rharding6373** [cockroachdb/cockroach#105724]
TestValidateMixedVersionElements_drop_column_with_index timed out after 15m in this TC run (the changes in the PR are unrelated): https://teamcity.cockroachdb.com/viewLog.html?buildId=10704945&buildTypeId=Cockroach_BazelEssentialCi

Jira issue: CRDB-29163

**Comment by rafiss** [comment]
We can't repro since after https://github.com/cockroachdb/cockroach/pull/106411 was merged.
