### ISSUE TITLE
ui: overview page email signup missing background color

### ISSUE THREAD

**Issue by j82w** [cockroachdb/cockroach#105740]
There is text above the capacity usage `Keep up-to-date with CockroachDB software releases and best practices.` that is very hard to read. It seems like the background color is missing for the overview page.
<img width="2297" alt="Screenshot 2023-06-28 at 11 35 04 AM" src="https://github.com/cockroachdb/cockroach/assets/8868107/3699075e-b0ec-4aa7-8b73-d18f0f3a63c2">

Jira issue: CRDB-29170

**Comment by joshimhoff** [comment]
@dhartunian @maryliag, does this PR fix a "serious issue" as per the policy (https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/1043235321/Database+Backport+Patch+Policy#Getting-your-backport-reviewed)?

>  Backports should only be created for serious
issues or test-only changes.
