### ISSUE TITLE
server: add tests for sql activity page endpoints during upgrade

### ISSUE THREAD

**Issue by xinhaoz** [cockroachdb/cockroach#105763]
We've previously had issues (ex. https://github.com/cockroachdb/cockroach/issues/105761) where we've missed some version gating which caused the page to fail to load during upgrades. We should add tests to ensure that our SQL activity pages and endpoints are reachable in mixed versions, especially now that we are using multiple tables in the pages (persisted and in-memory). It's crucial to ensure the page can be used for troubleshooting during upgrades. 

Jira issue: CRDB-29179

**Comment by maryliag** [comment]
No longer a priority
