### ISSUE TITLE
use monotonic timer for time delta calculations

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#10572]
Things like timeouts or `mutex held X for Yms` should not be using `time.Now` which is dependent on the system clock. Most unix systems have support for a monotonic timer which can be reliably used for time period calculations.

Unfortunately there isn't a standard one in Go (golang/go#12914). But that discussion mentions a package which makes use of an internal `runtime.nanotime` fuction which uses a monotonic timer when available: https://github.com/aristanetworks/goarista/tree/master/monotime

Note that a monotonic timer can't be used for txn timestamps or things like that.

**Comment by tamird** [comment]
Well, I started looking into this a bit, and unfortunately it's not as easy as I'd hoped. We use time.Time for time delta calculations in all kinds of fun ways, including the return value of `context.Context.Deadline()`, which we then compare to the local clock reading.

Sad to say, I'm not seeing a nice way out of this one. Ideas?

**Comment by petermattis** [comment]
The easy solution is to wait for go1.9 and the `time` support for [monotonic clocks](https://github.com/golang/go/issues/12914).

Closing as I don't think there is anything easy to do on our end.

**Comment by RaduBerinde** [comment]
Once we are on 1.9, it might be a good idea to have a goroutine monitor the system clock periodically and panic if it sees the clock jumping back or forward by more than the allowed clock skew.

**Comment by tamird** [comment]
We already have this code in timeutil.Now, though it currently only logs a warning.

**Comment by RaduBerinde** [comment]
I think you mean `hlc` stuff not `timeutil`. It only detects backward jumps though, and not with any degree of reliability - if I turn the clock back 1s and then I wait 1s before doing anything that requires reading the clock, it won't get detected (I think).

**Comment by tamird** [comment]
You're right on both counts.
