### ISSUE TITLE
server: TestClusterVersionUpgrade is flaky

### ISSUE THREAD

**Issue by renatolabs** [cockroachdb/cockroach#105756]
First observed this failure in a PR that changed unrelated code [1]. I was also able to reproduce the failure by stressing the test with the command below:

```console
./dev test ./pkg/server -f TestClusterVersionUpgrade --stress --ignore-cache --cpus 16 --timeout 10m
--- FAIL: TestClusterVersionUpgrade (1.50s)
    test_log_scope.go:167: test logs captured to: /tmp/cockroach/_tmp/5b2c9b3a394428c7572d34050aad8975/logTestClusterVersionUpgrade502772899
    test_log_scope.go:81: use -show-logs to present logs inline
    testcluster.go:417: pq: n3 required, but unavailable
    panic.go:522: -- test log scope end --
FAIL

ERROR: exit status 1

288 runs completed, 1 failures, over 7m30s
```

Assigning to @cockroachdb/dev-inf following the CODEOWNERS file. Feel free to reassign as you see fit.

[1] <https://teamcity.cockroachdb.com/viewLog.html?buildId=10715979&buildTypeId=Cockroach_BazelEssentialCi>

Jira issue: CRDB-29176

**Comment by erikgrinaker** [comment]
@andrewbaptist may want to have a look at this

**Comment by andrewbaptist** [comment]
Fixed by https://github.com/cockroachdb/cockroach/pull/105572

There was an issue with the way upgrades were detecting liveness after restarts.
