### ISSUE TITLE
roachtest: include link to testeng grafana in issue posts

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/cockroach#105894]
This is a wishlist feature request: When a roachtest fails and its metrics were reported to the testeng grafana instance, it would be very helpful in triaging if the posted GitHub issue could include a link to the grafana with the relevant cluster and test timeframe selected. As an example, a failure from a disk stall could easily be determined just by looking at the fsync latency.

Jira issue: CRDB-29261

**Comment by tbg** [comment]
Good idea! I wish the test-eng data lived on CentMon so we could use the standard set of Investigation Dashboards for it, too.

**Comment by tbg** [comment]
Some breadcrumbs. Roachtest's entry point for posting issues is here

https://github.com/cockroachdb/cockroach/blob/3266026f39ef3587515af2cf17a6635d88ea6949/pkg/cmd/roachtest/github.go#L215-L221

We'd probably put this link in the `HelpCommand`:

https://github.com/cockroachdb/cockroach/blob/3266026f39ef3587515af2cf17a6635d88ea6949/pkg/cmd/roachtest/github.go#L195-L204

So basically the task is to write code that generates the link

```
https://grafana.testeng.crdb.io/d/crdb-console/crdb-console-overview?orgId=1&from=<FROMEPOCHSECONDS>&to=<TOEPOCHSECONDS>&var-cluster=<CLUSTERNAME>
```

and renders it inline via `HelpCommandAsLink`.

While we're here, it might be useful to pull out the `HelpCommand` impl into a free-standing function and to write unit tests for it (perhaps a small one using `echotest`)[^1].

[^1]: [here's an example of how echotest works](https://github.com/cockroachdb/cockroach/blob/227fbe78ba7e96ce15cd57b22f9dbd965700b854/pkg/kv/kvserver/concurrency/poison/error_test.go#L29-L39).

**Comment by tbg** [comment]
One small trailer of an idea, instead of hard-linking the test-eng grafana, we could use a vanity URL instead using https://go.crdb.dev/, which allows rewrites. I just set one up:

https://go.crdb.dev/p/roachfana/silvano-cluster/1689957243817/1689957733137

So the link is `https://go.crdb.dev/p/roachfana/<clustername>/<fromts>/<tots>`.
