### ISSUE TITLE
Provide the ability for users to create and delete databases in the console

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#105886]
Users should be able to easily manage their clusters and workloads directly in the console. This issue tracks the ability to add and delete databases in the console.

Note: The CC console originally provided this capability but this feature was removed due to performance and stability issues with the Databases page.

Jira issue: CRDB-29257

**Comment by cjireland** [comment]
It I were being a stickler here I would not want developers creating DB, indexes or indeed dropping them via the UI. This is stuff they should put in source control and release properly. 

How about (just) giving them a drop-down to copy the CREATE DATABASE sql or Liquibase cfg, CC API TerraForm, or suchlike. They can then deploy that via their approved routes (e.g. a PR).

Better still, a way to control whether the option to create/drop is available (role permission?). The default should be NO and so developers get the "copy syntax dropdown" but no execute option.

**Comment by garycarr** [comment]
If the functionality is not be added soon then I think Cockroach should make clear somewhere in the UI or guides that this function is deliberately omitted.  Considering that you can add a new database Via `Connect` in the serverless UI I spent a lot of time looking for the same option in Dedicated server, to eventually open a ticket and be told by support that it no longer exists
