### ISSUE TITLE
Re-queue ranges on certain processing errors

### ISSUE THREAD

**Issue by MBerhault** [cockroachdb/cockroach#1058]
for example: when the first node scans the first range, it will fail to replicate due to lack of other replicas available.
This should be retried soonish (faster than the regular scan), or when we notice new nodes (this might be a bit heavy-handed).

**Comment by bdarnell** [comment]
I'll work on this (and making the scanner more responsive for small clusters generally) today.

**Comment by spencerkimball** [comment]
Ben, here are my thoughts on fixing up the scanner for small clusters. Use
or don't use as you see fit.

   - Have a maximum time to pause between processing ranges; this will
   cause scanner to finish early for small clusters.
   - If scanner finishes early, it should simply wait after the "last"
   range in the iterator to fill up the time allotted to one full scan.
   - Provide a manual "kick" mechanism for scanner which we can call when
   new nodes appear in gossip, nodes are marked as "down", nodes are marked as
   "dead", etc.
   - If the scanner is in the end-of-iteration wait, the kick ends the wait
   immediately and restarts scan from beginning.

**Comment by MBerhault** [comment]
I think the scanner if too abstract a concept for some of the things it does. The data GC scan that actually goes through the entire range data is much more expensive than the replica queue which just looks at range metadata.

A few things we should change:
- rate-limit range scanning based on the work it does (eg: bytes/s for the data GC). meaning that we may do 100 ranges/sec for replication, but only 10/min for GC.
- consider a lot of the errors just retries. If we fail to allocate due to not enough replicas, we should not consider this an arbitrary error. Instead, we should pop the range back into the queue.
- the rates should dictate how long things take. rate = remaining_ranges_work_size / remaining_time_until_max_interval, and bracket the rates by a min/max

For tiny clusters, all we need is the following:
- the min rate means that we'll never slow down to a crawl even if we have a single range with little data
- to avoid constantly looping on a single range, make the min_interval 5 seconds or something. we can sleep that much.

**Comment by spencerkimball** [comment]
On Tue, May 19, 2015 at 11:33 AM, MBerhault <notifications@github.com>
wrote:

> I think the scanner if too abstract a concept for some of the things it
> does. The data GC scan that actually goes through the entire range data is
> much more expensive than the replica queue which just looks at range
> metadata.
>
> A few things we should change:
>
>    - rate-limit range scanning based on the work it does (eg: bytes/s for
>    the data GC). meaning that we may do 100 ranges/sec for replication, but
>    only 10/min for GC.
>
> The amount of work that is done to determine that a range shouldn't be
verified or GC'd is trivial--it's doing a quick check on timestamps.
Creating another scanner which considers these ranges more slowly won't
make an appreciable difference except add complexity. We definitely DO NOT
do a data GC scan as often as we do a replicate check--we only consider
whether they should or should not be done as frequently. As an extreme
case, a data GC scan will never be done for a range whose data is quiescent.

There is already a mechanism within queues which will slow down the speed
at which ranges which are queued are processed.


>    - consider a lot of the errors just retries. If we fail to allocate
>    due to not enough replicas, we should not consider this an arbitrary error.
>    Instead, we should pop the range back into the queue.
>
> I was thinking something along the lines of a short list mechanism for
queues which we can use to table ranges on certain types of errors--they're
not retried immediately, but certain events will set them up for
re-processing immediately. Just re-queueing them right now will mean a busy
loop.

>
>    - the rates should dictate how long things take. rate =
>    remaining_ranges_work_size / remaining_time_until_max_interval, and bracket
>    the rates by a min/max
>
> For tiny clusters, all we need is the following:
>
>    - the min rate means that we'll never slow down to a crawl even if we
>    have a single range with little data
>
> You seem to be conflating amount of data in a range with number of ranges
in a scan. Or I'm confused.

**Comment by MBerhault** [comment]
Ok, let me try to take it from the top.
We currently have the scanner itself which just passes ranges to queues.

Each queue gets to decide at that moment whether to add the range, regardless of the current queue size.
It then processes the ranges in the queue using its own timer to decide how much to sleep between ranges.

All this works as a basic work scheduler, but is far from providing guarantees on how often we'll perform work for individual ranges.

I would propose something like this instead, which reuses a lot of the existing code:
- recompute priorities much more frequently (eg: as long as computing priorities is cheap, we should try to do all ranges within 30s or so, more if it gets pricey). 
- events trigger priority computation for potentially-affected ranges (this is just to cut down on the 30s. if quick scans of priorities are cheap, then just make the scanner loop even faster might be the only thing needed)
- each queue should do its own rate-limiting as mentioned before. we'll want safety margins around min/max rate as well as a min loop duration (to avoid busy loops) but that's about it.

**Comment by tamird** [comment]
@bdarnell can this be closed now that https://github.com/cockroachdb/cockroach/pull/1066 is merged?

**Comment by bdarnell** [comment]
Yeah, I think so. #1066 was meant to be a short-term fix but it seems to work well enough and it's not clear what a long-term fix would be.
