### ISSUE TITLE
persistedsqlstats: TestSQLStatsPersistedLimitReached flakes under stress and Bazel Essential CI

### ISSUE THREAD

**Issue by zachlite** [cockroachdb/cockroach#105846]
https://github.com/cockroachdb/cockroach/pull/105825 skips the test explicitly under stress, but we need to de-flake the stress test so this test can always be run.

Jira issue: CRDB-29231

**Comment by rafiss** [comment]
This also fails under Bazel Essential CI, without stress.
```
    flush_test.go:517:
          Error Trace:  pkg/sql/sqlstats/persistedsqlstats/persistedsqlstats_test_test/pkg/sql/sqlstats/persistedsqlstats/flush_test.go:517
          Error:        "16" is not less than or equal to "15"
          Test:         TestSQLStatsPersistedLimitReached
```

https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/10735309?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

**Comment by tbg** [comment]
Also happened [here](https://github.com/cockroachdb/cockroach/pull/105876) https://teamcity.cockroachdb.com/viewLog.html?buildId=10742161&tab=buildResultsDiv&buildTypeId=Cockroach_UnitTests_BazelUnitTests
