### ISSUE TITLE
Sentry: manager.go:272: snap must not be nil
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#105967]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4288972880/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4288972880/?referrer=webhooks_plugin)

Panic Message:

```
manager.go:272: snap must not be nil
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).SendWithWriteBytes.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_send.go:121
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:890
  | [...repeated from below...]
Wraps: (2) assertion failure
Wraps: (3) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/spanlatch.(*Manager).CheckOptimisticNoConflicts
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/spanlatch/manager.go:272
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/concurrency.(*latchManagerImpl).CheckOptimisticNoConflicts
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/concurrency/latch_manager.go:41
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/concurrency.(*Guard).CheckOptimisticNoConflicts
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/concurrency/concurrency_manager.go:734
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).executeReadOnlyBatch
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_read.go:142
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).executeBatchWithConcurrencyRetries
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go:481
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).SendWithWriteBytes
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go:176
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).SendWithWriteBytes
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_send.go:205
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Stores).SendWithWriteBytes
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/stores.go:203
  | github.com/cockroachdb/cockroach/pkg/server.(*Node).batchInternal
  | 	github.com/cockroachdb/cockroach/pkg/server/node.go:1108
  | github.com/cockroachdb/cockroach/pkg/server.(*Node).Batch
  | 	github.com/cockroachdb/cockroach/pkg/server/node.go:1161
  | github.com/cockroachdb/cockroach/pkg/roachpb._Internal_Batch_Handler.func1
  | 	github.com/cockroachdb/cockroach/pkg/roachpb/bazel-out/k8-opt/bin/pkg/roachpb/roachpb_go_proto_/github.com/cockroachdb/cockroach/pkg/roachpb/api.pb.go:9619
  | github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor.ServerInterceptor.func1
  | 	github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go:96
  | google.golang.org/grpc.chainUnaryInterceptors.func1.1
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1117
  | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func3
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:263
  | google.golang.org/grpc.chainUnaryInterceptors.func1.1
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1120
  | github.com/cockroachdb/cockroach/pkg/rpc.kvAuth.unaryInterceptor
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/auth.go:73
  | google.golang.org/grpc.chainUnaryInterceptors.func1.1
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1120
  | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func1.1
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:232
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:341
  | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func1
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:230
  | google.golang.org/grpc.chainUnaryInterceptors.func1.1
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1120
  | google.golang.org/grpc.chainUnaryInterceptors.func1
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1122
  | github.com/cockroachdb/cockroach/pkg/roachpb._Internal_Batch_Handler
  | 	github.com/cockroachdb/cockroach/pkg/roachpb/bazel-out/k8-opt/bin/pkg/roachpb/roachpb_go_proto_/github.com/cockroachdb/cockroach/pkg/roachpb/api.pb.go:9621
  | google.golang.org/grpc.(*Server).processUnaryRPC
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1283
  | google.golang.org/grpc.(*Server).handleStream
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1620
  | google.golang.org/grpc.(*Server).serveStreams.func1.2
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:922
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (4) snap must not be nil
Error types: (1) *withstack.withStack (2) *assert.withAssertionFailure (3) *withstack.withStack (4) *errutil.leafError
-- report composition:
*errutil.leafError: snap must not be nil
manager.go:272: *withstack.withStack (top exception)
*assert.withAssertionFailure
panic.go:884: *withstack.withStack (1)
(check the extra data payloads)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L921-L923](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L921-L923)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1619-L1621](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1619-L1621)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1282-L1284](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1282-L1284)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/roachpb/bazel-out/k8-opt/bin/pkg/roachpb/roachpb_go_proto_/github.com/cockroachdb/cockroach/pkg/roachpb/api.pb.go#L9620-L9622](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/roachpb/bazel-out/k8-opt/bin/pkg/roachpb/roachpb_go_proto_/github.com/cockroachdb/cockroach/pkg/roachpb/api.pb.go#L9620-L9622)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1121-L1123](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1121-L1123)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1119-L1121](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1119-L1121)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/rpc/pkg/rpc/context.go#L229-L231](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/rpc/pkg/rpc/context.go#L229-L231)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/util/stop/stopper.go#L340-L342](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/util/stop/stopper.go#L340-L342)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/rpc/pkg/rpc/context.go#L231-L233](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/rpc/pkg/rpc/context.go#L231-L233)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1119-L1121](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1119-L1121)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/rpc/pkg/rpc/auth.go#L72-L74](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/rpc/pkg/rpc/auth.go#L72-L74)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1119-L1121](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1119-L1121)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/rpc/pkg/rpc/context.go#L262-L264](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/rpc/pkg/rpc/context.go#L262-L264)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1116-L1118](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1116-L1118)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go#L95-L97](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go#L95-L97)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/roachpb/bazel-out/k8-opt/bin/pkg/roachpb/roachpb_go_proto_/github.com/cockroachdb/cockroach/pkg/roachpb/api.pb.go#L9618-L9620](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/roachpb/bazel-out/k8-opt/bin/pkg/roachpb/roachpb_go_proto_/github.com/cockroachdb/cockroach/pkg/roachpb/api.pb.go#L9618-L9620)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/server/node.go#L1160-L1162](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/server/node.go#L1160-L1162)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/server/node.go#L1107-L1109](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/server/node.go#L1107-L1109)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/pkg/kv/kvserver/stores.go#L202-L204](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/pkg/kv/kvserver/stores.go#L202-L204)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/pkg/kv/kvserver/store_send.go#L204-L206](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/pkg/kv/kvserver/store_send.go#L204-L206)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go#L175-L177](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go#L175-L177)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go#L480-L482](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go#L480-L482)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/pkg/kv/kvserver/replica_read.go#L141-L143](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/pkg/kv/kvserver/replica_read.go#L141-L143)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/concurrency/concurrency_manager.go#L733-L735](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/concurrency/concurrency_manager.go#L733-L735)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/concurrency/latch_manager.go#L40-L42](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/concurrency/latch_manager.go#L40-L42)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/spanlatch/manager.go#L271-L273](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/spanlatch/manager.go#L271-L273)
[GOROOT/src/runtime/panic.go#L889-L891](GOROOT/src/runtime/panic.go#L889-L891)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/pkg/kv/kvserver/store_send.go#L120-L122](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/pkg/kv/kvserver/store_send.go#L120-L122)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L921-L923](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L921-L923)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1619-L1621](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1619-L1621)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1282-L1284](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1282-L1284)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/roachpb/bazel-out/k8-opt/bin/pkg/roachpb/roachpb_go_proto_/github.com/cockroachdb/cockroach/pkg/roachpb/api.pb.go#L9620-L9622](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/roachpb/bazel-out/k8-opt/bin/pkg/roachpb/roachpb_go_proto_/github.com/cockroachdb/cockroach/pkg/roachpb/api.pb.go#L9620-L9622)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1121-L1123](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1121-L1123)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1119-L1121](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1119-L1121)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/rpc/pkg/rpc/context.go#L229-L231](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/rpc/pkg/rpc/context.go#L229-L231)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/util/stop/stopper.go#L340-L342](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/util/stop/stopper.go#L340-L342)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/rpc/pkg/rpc/context.go#L231-L233](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/rpc/pkg/rpc/context.go#L231-L233)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1119-L1121](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1119-L1121)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/rpc/pkg/rpc/auth.go#L72-L74](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/rpc/pkg/rpc/auth.go#L72-L74)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1119-L1121](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1119-L1121)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/rpc/pkg/rpc/context.go#L262-L264](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/rpc/pkg/rpc/context.go#L262-L264)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1116-L1118](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1116-L1118)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go#L95-L97](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go#L95-L97)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/roachpb/bazel-out/k8-opt/bin/pkg/roachpb/roachpb_go_proto_/github.com/cockroachdb/cockroach/pkg/roachpb/api.pb.go#L9618-L9620](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/roachpb/bazel-out/k8-opt/bin/pkg/roachpb/roachpb_go_proto_/github.com/cockroachdb/cockroach/pkg/roachpb/api.pb.go#L9618-L9620)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/server/node.go#L1160-L1162](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/server/node.go#L1160-L1162)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/server/node.go#L1107-L1109](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/server/node.go#L1107-L1109)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/pkg/kv/kvserver/stores.go#L202-L204](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/pkg/kv/kvserver/stores.go#L202-L204)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/pkg/kv/kvserver/store_send.go#L204-L206](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/pkg/kv/kvserver/store_send.go#L204-L206)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go#L175-L177](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go#L175-L177)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go#L480-L482](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go#L480-L482)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/pkg/kv/kvserver/replica_read.go#L141-L143](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/pkg/kv/kvserver/replica_read.go#L141-L143)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/concurrency/concurrency_manager.go#L733-L735](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/concurrency/concurrency_manager.go#L733-L735)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/concurrency/latch_manager.go#L40-L42](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/concurrency/latch_manager.go#L40-L42)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/spanlatch/manager.go#L271-L273](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/spanlatch/manager.go#L271-L273)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.(*Server).serveStreams.func1.2 at line 922
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.(*Server).handleStream at line 1620
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.(*Server).processUnaryRPC at line 1283
pkg/roachpb/bazel-out/k8-opt/bin/pkg/roachpb/roachpb_go_proto_/github.com/cockroachdb/cockroach/pkg/roachpb/api.pb.go in pkg/roachpb._Internal_Batch_Handler at line 9621
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.chainUnaryInterceptors.func1 at line 1122
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.chainUnaryInterceptors.func1.1 at line 1120
pkg/rpc/pkg/rpc/context.go in pkg/rpc.NewServerEx.func1 at line 230
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunTaskWithErr at line 341
pkg/rpc/pkg/rpc/context.go in pkg/rpc.NewServerEx.func1.1 at line 232
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.chainUnaryInterceptors.func1.1 at line 1120
pkg/rpc/pkg/rpc/auth.go in pkg/rpc.kvAuth.unaryInterceptor at line 73
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.chainUnaryInterceptors.func1.1 at line 1120
pkg/rpc/pkg/rpc/context.go in pkg/rpc.NewServerEx.func3 at line 263
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.chainUnaryInterceptors.func1.1 at line 1117
pkg/util/tracing/grpcinterceptor/grpc_interceptor.go in pkg/util/tracing/grpcinterceptor.ServerInterceptor.func1 at line 96
pkg/roachpb/bazel-out/k8-opt/bin/pkg/roachpb/roachpb_go_proto_/github.com/cockroachdb/cockroach/pkg/roachpb/api.pb.go in pkg/roachpb._Internal_Batch_Handler.func1 at line 9619
pkg/server/node.go in pkg/server.(*Node).Batch at line 1161
pkg/server/node.go in pkg/server.(*Node).batchInternal at line 1108
pkg/kv/kvserver/pkg/kv/kvserver/stores.go in pkg/kv/kvserver.(*Stores).SendWithWriteBytes at line 203
pkg/kv/kvserver/pkg/kv/kvserver/store_send.go in pkg/kv/kvserver.(*Store).SendWithWriteBytes at line 205
pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go in pkg/kv/kvserver.(*Replica).SendWithWriteBytes at line 176
pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go in pkg/kv/kvserver.(*Replica).executeBatchWithConcurrencyRetries at line 481
pkg/kv/kvserver/pkg/kv/kvserver/replica_read.go in pkg/kv/kvserver.(*Replica).executeReadOnlyBatch at line 142
pkg/kv/kvserver/concurrency/concurrency_manager.go in pkg/kv/kvserver/concurrency.(*Guard).CheckOptimisticNoConflicts at line 734
pkg/kv/kvserver/concurrency/latch_manager.go in pkg/kv/kvserver/concurrency.(*latchManagerImpl).CheckOptimisticNoConflicts at line 41
pkg/kv/kvserver/spanlatch/manager.go in pkg/kv/kvserver/spanlatch.(*Manager).CheckOptimisticNoConflicts at line 272
GOROOT/src/runtime/panic.go in runtime.gopanic at line 890
pkg/kv/kvserver/pkg/kv/kvserver/store_send.go in pkg/kv/kvserver.(*Store).SendWithWriteBytes.func1 at line 121
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.(*Server).serveStreams.func1.2 at line 922
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.(*Server).handleStream at line 1620
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.(*Server).processUnaryRPC at line 1283
pkg/roachpb/bazel-out/k8-opt/bin/pkg/roachpb/roachpb_go_proto_/github.com/cockroachdb/cockroach/pkg/roachpb/api.pb.go in pkg/roachpb._Internal_Batch_Handler at line 9621
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.chainUnaryInterceptors.func1 at line 1122
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.chainUnaryInterceptors.func1.1 at line 1120
pkg/rpc/pkg/rpc/context.go in pkg/rpc.NewServerEx.func1 at line 230
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunTaskWithErr at line 341
pkg/rpc/pkg/rpc/context.go in pkg/rpc.NewServerEx.func1.1 at line 232
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.chainUnaryInterceptors.func1.1 at line 1120
pkg/rpc/pkg/rpc/auth.go in pkg/rpc.kvAuth.unaryInterceptor at line 73
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.chainUnaryInterceptors.func1.1 at line 1120
pkg/rpc/pkg/rpc/context.go in pkg/rpc.NewServerEx.func3 at line 263
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.chainUnaryInterceptors.func1.1 at line 1117
pkg/util/tracing/grpcinterceptor/grpc_interceptor.go in pkg/util/tracing/grpcinterceptor.ServerInterceptor.func1 at line 96
pkg/roachpb/bazel-out/k8-opt/bin/pkg/roachpb/roachpb_go_proto_/github.com/cockroachdb/cockroach/pkg/roachpb/api.pb.go in pkg/roachpb._Internal_Batch_Handler.func1 at line 9619
pkg/server/node.go in pkg/server.(*Node).Batch at line 1161
pkg/server/node.go in pkg/server.(*Node).batchInternal at line 1108
pkg/kv/kvserver/pkg/kv/kvserver/stores.go in pkg/kv/kvserver.(*Stores).SendWithWriteBytes at line 203
pkg/kv/kvserver/pkg/kv/kvserver/store_send.go in pkg/kv/kvserver.(*Store).SendWithWriteBytes at line 205
pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go in pkg/kv/kvserver.(*Replica).SendWithWriteBytes at line 176
pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go in pkg/kv/kvserver.(*Replica).executeBatchWithConcurrencyRetries at line 481
pkg/kv/kvserver/pkg/kv/kvserver/replica_read.go in pkg/kv/kvserver.(*Replica).executeReadOnlyBatch at line 142
pkg/kv/kvserver/concurrency/concurrency_manager.go in pkg/kv/kvserver/concurrency.(*Guard).CheckOptimisticNoConflicts at line 734
pkg/kv/kvserver/concurrency/latch_manager.go in pkg/kv/kvserver/concurrency.(*latchManagerImpl).CheckOptimisticNoConflicts at line 41
pkg/kv/kvserver/spanlatch/manager.go in pkg/kv/kvserver/spanlatch.(*Manager).CheckOptimisticNoConflicts at line 272
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v22.2.9 |
| Go Version | go1.19.6 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v22.2.9 |
| Cockroach SHA | 1b11ca676513ae073ea696c7cc3123d2684bc4bd |
| # of CPUs | 48 |
| # of Goroutines | 328 |

Jira issue: CRDB-29294

**Comment by yuzefovich** [comment]
dup of #81937
