### ISSUE TITLE
(creatingcontainererror) zen-metastoredb-0 

### ISSUE THREAD

**Issue by agborntui** [cockroachdb/cockroach#105926]
**Describe the problem**
Hi Team! I'm installing WSA instances(wsa-health..wsa-secure..wsa-automation) I ran into this error on this pod (creatingcontainererror) zen-metastoredb-0  please any though on this? this installation is on OCP on Vsphere.

<img width="1203" alt="Pasted Graphic 9" src="https://github.com/cockroachdb/cockroach/assets/85638689/86d1c7aa-8385-4121-ad78-2b6685ccdc33">

Add any other context about the problem here.<img width="1770" alt="Pasted Graphic 10" src="https://github.com/cockroachdb/cockroach/assets/85638689/0abbc439-707b-44f0-bcda-c5a9d88ca999">

Jira issue: CRDB-29275

**Comment by agborntui** [comment]
Hi Team! any solutions with the above issue?

**Comment by jbowens** [comment]
Hi @agborntui, It appears there's an issue with your storage volume. This error is reporting that the database was unable to write to disk for 20s.

**Comment by agborntui** [comment]
please any recommendation?

**Comment by jbowens** [comment]
Sorry, we don’t provide support for host environments. Maybe OCP or vSphere support can help you debug what’s happening to your disk.
