### ISSUE TITLE
doc: 'NEW SCHEMA CHANGE' missing from 

### ISSUE THREAD

**Issue by ecwall** [cockroachdb/cockroach#105918]
`NEW SCHEMA CHANGE`, `MIGRATION`, `ROW LEVEL TTL` (maybe more?) missing from `SHOW JOBS` `jop_type` values in documentation: https://www.cockroachlabs.com/docs/stable/show-jobs.html#response

Jira issue: CRDB-29271

**Comment by rafiss** [comment]
@ecwall could you file this at https://github.com/cockroachdb/docs instead?

**Comment by ecwall** [comment]
Created https://github.com/cockroachdb/docs/issues/17483
