### ISSUE TITLE
Sentry: type_desc.go:701: type × (59112): referencing × 59451 was dropped without dependency unlinking
(1) keys: [sql.schema.validation_errors.write.backward_references.type sql.schema.validation_er...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#105941]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4286703067/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4286703067/?referrer=webhooks_plugin)

Panic Message:

```
type_desc.go:701: type × (59112): referencing × 59451 was dropped without dependency unlinking
(1) keys: [sql.schema.validation_errors.write.backward_references.type sql.schema.validation_errors.write.backward_references.type]
Wraps: (2) secondary error attachment
  | type × (59118): referencing × 59451 was dropped without dependency unlinking
  | (1) keys: [sql.schema.validation_errors.write.backward_references.type]
  | Wraps: (2) attached stack trace
  |   -- stack trace:
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate.(*validationErrorAccumulator).decorate
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate/validate.go:244
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate.(*validationErrorAccumulator).Report
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate/validate.go:173
  |   | [...repeated from below...]
  | Wraps: (3) type × (59118)
  | Wraps: (4) assertion failure
  | Wraps: (5) attached stack trace
  |   -- stack trace:
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/typedesc.(*immutable).ValidateBackReferences
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/typedesc/type_desc.go:701
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate.Validate.func3
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate/validate.go:101
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate.(*validationErrorAccumulator).validateDescriptorsAtLevel
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate/validate.go:189
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate.Validate
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate/validate.go:96
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).Validate
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/validate.go:35
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).ValidateUncommittedDescriptors
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/validate.go:62
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).commitSQLTransactionInternal
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:975
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).commitSQLTransaction
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:886
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:538
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:131
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2428
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:130
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1972
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1976
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1898
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:857
  |   | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:728
  |   | runtime.goexit
  |   | 	GOROOT/src/runtime/asm_amd64.s:1594
  | Wraps: (6) referencing × 59451 was dropped without dependency unlinking
  | Error types: (1) *telemetrykeys.withTelemetry (2) *withstack.withStack (3) *errutil.withPrefix (4) *assert.withAssertionFailure (5) *withstack.withStack (6) *errutil.leafError
Wraps: (3) keys: [sql.schema.validation_errors.write.backward_references.type]
Wraps: (4) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate.(*validationErrorAccumulator).decorate
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate/validate.go:244
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate.(*validationErrorAccumulator).Report
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate/validate.go:173
  | [...repeated from below...]
Wraps: (5) type × (59112)
Wraps: (6) assertion failure
Wraps: (7) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/typedesc.(*immutable).ValidateBackReferences
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/typedesc/type_desc.go:701
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate.Validate.func3
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate/validate.go:101
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate.(*validationErrorAccumulator).validateDescriptorsAtLevel
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate/validate.go:189
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate.Validate
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate/validate.go:96
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).Validate
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/validate.go:35
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).ValidateUncommittedDescriptors
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/validate.go:62
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).commitSQLTransactionInternal
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:975
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).commitSQLTransaction
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:886
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:538
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:131
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2428
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:130
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1972
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1976
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1898
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:857
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:728
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (8) referencing × 59451 was dropped without dependency unlinking
Error types: (1) *telemetrykeys.withTelemetry (2) *secondary.withSecondaryError (3) *telemetrykeys.withTelemetry (4) *withstack.withStack (5) *errutil.withPrefix (6) *assert.withAssertionFailure (7) *withstack.withStack (8) *errutil.leafError
-- report composition:
*errutil.leafError: referencing × 59451 was dropped without dependency unlinking
type_desc.go:701: *withstack.withStack (top exception)
*assert.withAssertionFailure
*errutil.withPrefix: type × (59112)
validate.go:244: *withstack.withStack (1)
*telemetrykeys.withTele...
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/pgwire/conn.go#L727-L729](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/pgwire/conn.go#L727-L729)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/conn_executor.go#L856-L858](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/conn_executor.go#L856-L858)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/conn_executor.go#L1897-L1899](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/conn_executor.go#L1897-L1899)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/conn_executor.go#L1975-L1977](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/conn_executor.go#L1975-L1977)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/conn_executor.go#L1971-L1973](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/conn_executor.go#L1971-L1973)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/conn_executor_exec.go#L129-L131](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/conn_executor_exec.go#L129-L131)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/conn_executor_exec.go#L2427-L2429](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/conn_executor_exec.go#L2427-L2429)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/conn_executor_exec.go#L130-L132](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/conn_executor_exec.go#L130-L132)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/conn_executor_exec.go#L537-L539](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/conn_executor_exec.go#L537-L539)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/conn_executor_exec.go#L885-L887](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/conn_executor_exec.go#L885-L887)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/conn_executor_exec.go#L974-L976](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/conn_executor_exec.go#L974-L976)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/catalog/descs/validate.go#L61-L63](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/catalog/descs/validate.go#L61-L63)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/catalog/descs/validate.go#L34-L36](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/catalog/descs/validate.go#L34-L36)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/catalog/internal/validate/validate.go#L95-L97](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/catalog/internal/validate/validate.go#L95-L97)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/catalog/internal/validate/validate.go#L188-L190](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/catalog/internal/validate/validate.go#L188-L190)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/catalog/internal/validate/validate.go#L100-L102](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/catalog/internal/validate/validate.go#L100-L102)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/catalog/typedesc/type_desc.go#L700-L702](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/catalog/typedesc/type_desc.go#L700-L702)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/catalog/internal/validate/validate.go#L172-L174](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/catalog/internal/validate/validate.go#L172-L174)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/catalog/internal/validate/validate.go#L243-L245](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/catalog/internal/validate/validate.go#L243-L245)
[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/pgwire/conn.go#L727-L729](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/pgwire/conn.go#L727-L729)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/conn_executor.go#L856-L858](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/conn_executor.go#L856-L858)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/conn_executor.go#L1897-L1899](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/conn_executor.go#L1897-L1899)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/conn_executor.go#L1975-L1977](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/conn_executor.go#L1975-L1977)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/conn_executor.go#L1971-L1973](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/conn_executor.go#L1971-L1973)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/conn_executor_exec.go#L129-L131](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/conn_executor_exec.go#L129-L131)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/conn_executor_exec.go#L2427-L2429](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/conn_executor_exec.go#L2427-L2429)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/conn_executor_exec.go#L130-L132](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/conn_executor_exec.go#L130-L132)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/conn_executor_exec.go#L537-L539](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/conn_executor_exec.go#L537-L539)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/conn_executor_exec.go#L885-L887](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/conn_executor_exec.go#L885-L887)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/conn_executor_exec.go#L974-L976](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/conn_executor_exec.go#L974-L976)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/catalog/descs/validate.go#L61-L63](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/catalog/descs/validate.go#L61-L63)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/catalog/descs/validate.go#L34-L36](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/catalog/descs/validate.go#L34-L36)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/catalog/internal/validate/validate.go#L95-L97](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/catalog/internal/validate/validate.go#L95-L97)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/catalog/internal/validate/validate.go#L188-L190](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/catalog/internal/validate/validate.go#L188-L190)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/catalog/internal/validate/validate.go#L100-L102](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/catalog/internal/validate/validate.go#L100-L102)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/catalog/typedesc/type_desc.go#L700-L702](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/catalog/typedesc/type_desc.go#L700-L702)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommandsAsync.func1 at line 728
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 857
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 1898
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 1976
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd.func1 at line 1972
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 130
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithProfiling at line 2428
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt.func1 at line 131
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 538
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).commitSQLTransaction at line 886
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).commitSQLTransactionInternal at line 975
pkg/sql/catalog/descs/validate.go in pkg/sql/catalog/descs.(*Collection).ValidateUncommittedDescriptors at line 62
pkg/sql/catalog/descs/validate.go in pkg/sql/catalog/descs.(*Collection).Validate at line 35
pkg/sql/catalog/internal/validate/validate.go in pkg/sql/catalog/internal/validate.Validate at line 96
pkg/sql/catalog/internal/validate/validate.go in pkg/sql/catalog/internal/validate.(*validationErrorAccumulator).validateDescriptorsAtLevel at line 189
pkg/sql/catalog/internal/validate/validate.go in pkg/sql/catalog/internal/validate.Validate.func3 at line 101
pkg/sql/catalog/typedesc/type_desc.go in pkg/sql/catalog/typedesc.(*immutable).ValidateBackReferences at line 701
pkg/sql/catalog/internal/validate/validate.go in pkg/sql/catalog/internal/validate.(*validationErrorAccumulator).Report at line 173
pkg/sql/catalog/internal/validate/validate.go in pkg/sql/catalog/internal/validate.(*validationErrorAccumulator).decorate at line 244
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommandsAsync.func1 at line 728
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 857
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 1898
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 1976
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd.func1 at line 1972
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 130
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithProfiling at line 2428
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt.func1 at line 131
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 538
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).commitSQLTransaction at line 886
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).commitSQLTransactionInternal at line 975
pkg/sql/catalog/descs/validate.go in pkg/sql/catalog/descs.(*Collection).ValidateUncommittedDescriptors at line 62
pkg/sql/catalog/descs/validate.go in pkg/sql/catalog/descs.(*Collection).Validate at line 35
pkg/sql/catalog/internal/validate/validate.go in pkg/sql/catalog/internal/validate.Validate at line 96
pkg/sql/catalog/internal/validate/validate.go in pkg/sql/catalog/internal/validate.(*validationErrorAccumulator).validateDescriptorsAtLevel at line 189
pkg/sql/catalog/internal/validate/validate.go in pkg/sql/catalog/internal/validate.Validate.func3 at line 101
pkg/sql/catalog/typedesc/type_desc.go in pkg/sql/catalog/typedesc.(*immutable).ValidateBackReferences at line 701
```

### Tags

| Tag | Value |
| --- | --- |
| Command | start-single-node |
| Environment | v22.2.6 |
| Go Version | go1.19.4 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v22.2.6 |
| Cockroach SHA | d5a076f2953c0712193b8cbe08bbb682563c5675 |
| # of CPUs | 8 |
| # of Goroutines | 583 |

Jira issue: CRDB-29278

**Comment by yuzefovich** [comment]
dup of #91972
