### ISSUE TITLE
roachtest: use CentMon for Grafana observability

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#106057]
**Is your feature request related to a problem? Please describe.**

It has been great to have full access to historical metrics for all roachtests through a central location (grafana.testeng.crdb.io). However, it would be even better if the data were available through CentMon, as that's where the most up to date dashboards live.

**Describe the solution you'd like**

**Describe alternatives you've considered**

If we auto-synced the CentMon dashboards over, I'd be happy as well. However, as far as I can tell, copying dashboards around between Grafana instances is a real PITA because the data source UIDs don't match, version incompatibilities exist, etc.

**Additional context**

cc @ericharmeling @herkolategan 

Jira issue: CRDB-29373

**Comment by ericharmeling** [comment]
Closing this issue in favor of https://cockroachlabs.atlassian.net/browse/CRDB-31301.
