### ISSUE TITLE
Sentry: db.go:44: pebble: closed
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | github.com/cockroachdb/pebble.(*DB).newIterInternal
  | 	github...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#106060]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4291574474/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4291574474/?referrer=webhooks_plugin)

Panic Message:

```
db.go:44: pebble: closed
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | github.com/cockroachdb/pebble.(*DB).newIterInternal
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go:872
  | github.com/cockroachdb/pebble.(*Batch).NewIter
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/batch.go:851
  | github.com/cockroachdb/cockroach/pkg/storage.(*pebbleIterator).initReuseOrCreate
  | 	github.com/cockroachdb/cockroach/pkg/storage/pebble_iterator.go:188
  | github.com/cockroachdb/cockroach/pkg/storage.(*pebbleBatch).NewMVCCIterator
  | 	github.com/cockroachdb/cockroach/pkg/storage/pebble_batch.go:186
  | github.com/cockroachdb/cockroach/pkg/storage.newMVCCIterator
  | 	github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:930
  | github.com/cockroachdb/cockroach/pkg/storage.MVCCPut
  | 	github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:1327
  | github.com/cockroachdb/cockroach/pkg/storage.MVCCPutProto
  | 	github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:841
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/stateloader.StateLoader.SetLease
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/stateloader/stateloader.go:176
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/batcheval.evalNewLease
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/batcheval/cmd_lease.go:128
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/batcheval.RequestLease
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/batcheval/cmd_lease_request.go:163
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.evaluateCommand
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_evaluate.go:520
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.evaluateBatch
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_evaluate.go:287
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).evaluateWriteBatchWrapper
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go:668
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).evaluateWriteBatchWithServersideRefreshes
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go:628
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).evaluateWriteBatch
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go:438
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).evaluateProposal
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go:711
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).requestToProposal
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go:799
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).evalAndPropose
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:119
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).executeWriteBatch
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go:174
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).executeBatchWithConcurrencyRetries
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go:481
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).SendWithWriteBytes
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go:180
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).Send
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go:115
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*pendingLeaseRequest).requestLease
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_range_lease.go:550
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*pendingLeaseRequest).requestLeaseAsync.func2
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_range_lease.go:401
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:489
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/pebble.(*DB).Close
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go:1239
  | github.com/cockroachdb/cockroach/pkg/storage.(*Pebble).Close
  | 	github.com/cockroachdb/cockroach/pkg/storage/pebble.go:1123
  | github.com/cockroachdb/cockroach/pkg/server.(*stickyInMemEnginesRegistryImpl).deleteEngine
  | 	github.com/cockroachdb/cockroach/pkg/server/sticky_engine.go:186
  | github.com/cockroachdb/cockroach/pkg/server.(*stickyInMemEnginesRegistryImpl).CloseAllStickyInMemEngines
  | 	github.com/cockroachdb/cockroach/pkg/server/sticky_engine.go:176
  | github.com/cockroachdb/cockroach/pkg/cli/democluster.(*transientCluster).Start.func3.1
  | 	github.com/cockroachdb/cockroach/pkg/cli/democluster/demo_cluster.go:286
  | github.com/cockroachdb/cockroach/pkg/util/stop.CloserFn.Close
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:107
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Stop
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:558
  | github.com/cockroachdb/cockroach/pkg/cli/democluster.(*transientCluster).Close
  | 	github.com/cockroachdb/cockroach/pkg/cli/democluster/demo_cluster.go:811
  | github.com/cockroachdb/cockroach/pkg/cli.runDemoInternal
  | 	github.com/cockroachdb/cockroach/pkg/cli/demo.go:372
  | github.com/cockroachdb/cockroach/pkg/cli.runDemo
  | 	github.com/cockroachdb/cockroach/pkg/cli/demo.go:210
  | github.com/cockroachdb/cockroach/pkg/cli.init.5.func1
  | 	github.com/cockroachdb/cockroach/pkg/cli/demo.go:59
  | github.com/cockroachdb/cockroach/pkg/cli/clierrorplus.MaybeDecorateError.func1
  | 	github.com/cockroachdb/cockroach/pkg/cli/clierrorplus/decorate_error.go:71
  | github.com/spf13/cobra.(*Command).execute
  | 	github.com/spf13/cobra/external/com_github_spf13_cobra/command.go:856
  | github.com/spf13/cobra.(*Command).ExecuteC
  | 	github.com/spf13/cobra/external/com_github_spf13_cobra/command.go:974
  | github.com/spf13/cobra.(*Command).Execute
  | 	github.com/spf13/cobra/external/com_github_spf13_cobra/command.go:902
  | github.com/cockroachdb/cockroach/pkg/cli.Run
  | 	github.com/cockroachdb/cockroach/pkg/cli/cli.go:300
  | github.com/cockroachdb/cockroach/pkg/cli.doMain
  | 	github.com/cockroachdb/cockroach/pkg/cli/cli.go:143
  | github.com/cockroachdb/cockroach/pkg/cli.Main
  | 	github.com/cockroachdb/cockroach/pkg/cli/cli.go:68
  | main.main
  | 	main/pkg/cmd/cockroach/main.go:26
  | [...repeated from below...]
Wraps: (3) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/pebble.init
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go:44
  | runtime.doInit
  | 	GOROOT/src/runtime/proc.go:6348
  | runtime.doInit
  | 	GOROOT/src/runtime/proc.go:6325
  | runtime.doInit
  | 	GOROOT/src/runtime/proc.go:6325
  | runtime.doInit
  | 	GOROOT/src/runtime/proc.go:6325
  | runtime.doInit
  | 	GOROOT/src/runtime/proc.go:6325
  | runtime.doInit
  | 	GOROOT/src/runtime/proc.go:6325
  | runtime.doInit
  | 	GOROOT/src/runtime/proc.go:6325
  | runtime.doInit
  | 	GOROOT/src/runtime/proc.go:6325
  | runtime.main
  | 	GOROOT/src/runtime/proc.go:233
  | runtime.goexit
  | 	src/runtime/asm_arm64.s:1172
Wraps: (4) pebble: closed
Error types: (1) *withstack.withStack (2) *withstack.withStack (3) *withstack.withStack (4) *errutil.leafError
-- report composition:
*errutil.leafError: pebble: closed
db.go:44: *withstack.withStack (top exception)
db.go:1239: *withstack.withStack (1)
panic.go:884: *withstack.withStack (2)
(check the extra data payloads)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_arm64.s#L1171-L1173](src/runtime/asm_arm64.s#L1171-L1173)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/util/stop/stopper.go#L488-L490](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/util/stop/stopper.go#L488-L490)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/kv/kvserver/pkg/kv/kvserver/replica_range_lease.go#L400-L402](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/kv/kvserver/pkg/kv/kvserver/replica_range_lease.go#L400-L402)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/kv/kvserver/pkg/kv/kvserver/replica_range_lease.go#L549-L551](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/kv/kvserver/pkg/kv/kvserver/replica_range_lease.go#L549-L551)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go#L114-L116](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go#L114-L116)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go#L179-L181](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go#L179-L181)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go#L480-L482](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go#L480-L482)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go#L173-L175](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go#L173-L175)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L118-L120](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L118-L120)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go#L798-L800](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go#L798-L800)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go#L710-L712](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go#L710-L712)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go#L437-L439](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go#L437-L439)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go#L627-L629](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go#L627-L629)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go#L667-L669](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go#L667-L669)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/kv/kvserver/pkg/kv/kvserver/replica_evaluate.go#L286-L288](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/kv/kvserver/pkg/kv/kvserver/replica_evaluate.go#L286-L288)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/kv/kvserver/pkg/kv/kvserver/replica_evaluate.go#L519-L521](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/kv/kvserver/pkg/kv/kvserver/replica_evaluate.go#L519-L521)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/kv/kvserver/batcheval/cmd_lease_request.go#L162-L164](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/kv/kvserver/batcheval/cmd_lease_request.go#L162-L164)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/kv/kvserver/batcheval/cmd_lease.go#L127-L129](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/kv/kvserver/batcheval/cmd_lease.go#L127-L129)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/kv/kvserver/stateloader/stateloader.go#L175-L177](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/kv/kvserver/stateloader/stateloader.go#L175-L177)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/storage/mvcc.go#L840-L842](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/storage/mvcc.go#L840-L842)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/storage/mvcc.go#L1326-L1328](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/storage/mvcc.go#L1326-L1328)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/storage/mvcc.go#L929-L931](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/storage/mvcc.go#L929-L931)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/storage/pebble_batch.go#L185-L187](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/storage/pebble_batch.go#L185-L187)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/storage/pebble_iterator.go#L187-L189](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/storage/pebble_iterator.go#L187-L189)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/batch.go#L850-L852](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/batch.go#L850-L852)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L871-L873](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L871-L873)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
[src/runtime/asm_arm64.s#L1171-L1173](src/runtime/asm_arm64.s#L1171-L1173)
[GOROOT/src/runtime/proc.go#L249-L251](GOROOT/src/runtime/proc.go#L249-L251)
[main/pkg/cmd/cockroach/main.go#L25-L27](main/pkg/cmd/cockroach/main.go#L25-L27)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/cli/cli.go#L67-L69](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/cli/cli.go#L67-L69)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/cli/cli.go#L142-L144](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/cli/cli.go#L142-L144)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/cli/cli.go#L299-L301](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/cli/cli.go#L299-L301)
[github.com/spf13/cobra/external/com_github_spf13_cobra/command.go#L901-L903](github.com/spf13/cobra/external/com_github_spf13_cobra/command.go#L901-L903)
[github.com/spf13/cobra/external/com_github_spf13_cobra/command.go#L973-L975](github.com/spf13/cobra/external/com_github_spf13_cobra/command.go#L973-L975)
[github.com/spf13/cobra/external/com_github_spf13_cobra/command.go#L855-L857](github.com/spf13/cobra/external/com_github_spf13_cobra/command.go#L855-L857)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/cli/clierrorplus/decorate_error.go#L70-L72](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/cli/clierrorplus/decorate_error.go#L70-L72)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/cli/demo.go#L58-L60](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/cli/demo.go#L58-L60)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/cli/demo.go#L209-L211](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/cli/demo.go#L209-L211)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/cli/demo.go#L371-L373](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/cli/demo.go#L371-L373)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/cli/democluster/demo_cluster.go#L810-L812](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/cli/democluster/demo_cluster.go#L810-L812)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/util/stop/stopper.go#L557-L559](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/util/stop/stopper.go#L557-L559)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/util/stop/stopper.go#L106-L108](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/util/stop/stopper.go#L106-L108)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/cli/democluster/demo_cluster.go#L285-L287](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/cli/democluster/demo_cluster.go#L285-L287)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/server/sticky_engine.go#L175-L177](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/server/sticky_engine.go#L175-L177)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/server/sticky_engine.go#L185-L187](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/server/sticky_engine.go#L185-L187)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/storage/pebble.go#L1122-L1124](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/storage/pebble.go#L1122-L1124)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L1238-L1240](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L1238-L1240)
[src/runtime/asm_arm64.s#L1171-L1173](src/runtime/asm_arm64.s#L1171-L1173)
[GOROOT/src/runtime/proc.go#L232-L234](GOROOT/src/runtime/proc.go#L232-L234)
[GOROOT/src/runtime/proc.go#L6324-L6326](GOROOT/src/runtime/proc.go#L6324-L6326)
[GOROOT/src/runtime/proc.go#L6324-L6326](GOROOT/src/runtime/proc.go#L6324-L6326)
[GOROOT/src/runtime/proc.go#L6324-L6326](GOROOT/src/runtime/proc.go#L6324-L6326)
[GOROOT/src/runtime/proc.go#L6324-L6326](GOROOT/src/runtime/proc.go#L6324-L6326)
[GOROOT/src/runtime/proc.go#L6324-L6326](GOROOT/src/runtime/proc.go#L6324-L6326)
[GOROOT/src/runtime/proc.go#L6324-L6326](GOROOT/src/runtime/proc.go#L6324-L6326)
[GOROOT/src/runtime/proc.go#L6324-L6326](GOROOT/src/runtime/proc.go#L6324-L6326)
[GOROOT/src/runtime/proc.go#L6347-L6349](GOROOT/src/runtime/proc.go#L6347-L6349)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L43-L45](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L43-L45)
</details>

```
src/runtime/asm_arm64.s in runtime.goexit at line 1172
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 489
pkg/kv/kvserver/pkg/kv/kvserver/replica_range_lease.go in pkg/kv/kvserver.(*pendingLeaseRequest).requestLeaseAsync.func2 at line 401
pkg/kv/kvserver/pkg/kv/kvserver/replica_range_lease.go in pkg/kv/kvserver.(*pendingLeaseRequest).requestLease at line 550
pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go in pkg/kv/kvserver.(*Replica).Send at line 115
pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go in pkg/kv/kvserver.(*Replica).SendWithWriteBytes at line 180
pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go in pkg/kv/kvserver.(*Replica).executeBatchWithConcurrencyRetries at line 481
pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go in pkg/kv/kvserver.(*Replica).executeWriteBatch at line 174
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).evalAndPropose at line 119
pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go in pkg/kv/kvserver.(*Replica).requestToProposal at line 799
pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go in pkg/kv/kvserver.(*Replica).evaluateProposal at line 711
pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go in pkg/kv/kvserver.(*Replica).evaluateWriteBatch at line 438
pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go in pkg/kv/kvserver.(*Replica).evaluateWriteBatchWithServersideRefreshes at line 628
pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go in pkg/kv/kvserver.(*Replica).evaluateWriteBatchWrapper at line 668
pkg/kv/kvserver/pkg/kv/kvserver/replica_evaluate.go in pkg/kv/kvserver.evaluateBatch at line 287
pkg/kv/kvserver/pkg/kv/kvserver/replica_evaluate.go in pkg/kv/kvserver.evaluateCommand at line 520
pkg/kv/kvserver/batcheval/cmd_lease_request.go in pkg/kv/kvserver/batcheval.RequestLease at line 163
pkg/kv/kvserver/batcheval/cmd_lease.go in pkg/kv/kvserver/batcheval.evalNewLease at line 128
pkg/kv/kvserver/stateloader/stateloader.go in pkg/kv/kvserver/stateloader.StateLoader.SetLease at line 176
pkg/storage/mvcc.go in pkg/storage.MVCCPutProto at line 841
pkg/storage/mvcc.go in pkg/storage.MVCCPut at line 1327
pkg/storage/mvcc.go in pkg/storage.newMVCCIterator at line 930
pkg/storage/pebble_batch.go in pkg/storage.(*pebbleBatch).NewMVCCIterator at line 186
pkg/storage/pebble_iterator.go in pkg/storage.(*pebbleIterator).initReuseOrCreate at line 188
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/batch.go in github.com/cockroachdb/pebble.(*Batch).NewIter at line 851
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go in github.com/cockroachdb/pebble.(*DB).newIterInternal at line 872
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
src/runtime/asm_arm64.s in runtime.goexit at line 1172
GOROOT/src/runtime/proc.go in runtime.main at line 250
main/pkg/cmd/cockroach/main.go in main.main at line 26
pkg/cli/cli.go in pkg/cli.Main at line 68
pkg/cli/cli.go in pkg/cli.doMain at line 143
pkg/cli/cli.go in pkg/cli.Run at line 300
github.com/spf13/cobra/external/com_github_spf13_cobra/command.go in github.com/spf13/cobra.(*Command).Execute at line 902
github.com/spf13/cobra/external/com_github_spf13_cobra/command.go in github.com/spf13/cobra.(*Command).ExecuteC at line 974
github.com/spf13/cobra/external/com_github_spf13_cobra/command.go in github.com/spf13/cobra.(*Command).execute at line 856
pkg/cli/clierrorplus/decorate_error.go in pkg/cli/clierrorplus.MaybeDecorateError.func1 at line 71
pkg/cli/demo.go in pkg/cli.init.5.func1 at line 59
pkg/cli/demo.go in pkg/cli.runDemo at line 210
pkg/cli/demo.go in pkg/cli.runDemoInternal at line 372
pkg/cli/democluster/demo_cluster.go in pkg/cli/democluster.(*transientCluster).Close at line 811
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).Stop at line 558
pkg/util/stop/stopper.go in pkg/util/stop.CloserFn.Close at line 107
pkg/cli/democluster/demo_cluster.go in pkg/cli/democluster.(*transientCluster).Start.func3.1 at line 286
pkg/server/sticky_engine.go in pkg/server.(*stickyInMemEnginesRegistryImpl).CloseAllStickyInMemEngines at line 176
pkg/server/sticky_engine.go in pkg/server.(*stickyInMemEnginesRegistryImpl).deleteEngine at line 186
pkg/storage/pebble.go in pkg/storage.(*Pebble).Close at line 1123
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go in github.com/cockroachdb/pebble.(*DB).Close at line 1239
src/runtime/asm_arm64.s in runtime.goexit at line 1172
GOROOT/src/runtime/proc.go in runtime.main at line 233
GOROOT/src/runtime/proc.go in runtime.doInit at line 6325
GOROOT/src/runtime/proc.go in runtime.doInit at line 6325
GOROOT/src/runtime/proc.go in runtime.doInit at line 6325
GOROOT/src/runtime/proc.go in runtime.doInit at line 6325
GOROOT/src/runtime/proc.go in runtime.doInit at line 6325
GOROOT/src/runtime/proc.go in runtime.doInit at line 6325
GOROOT/src/runtime/proc.go in runtime.doInit at line 6325
GOROOT/src/runtime/proc.go in runtime.doInit at line 6348
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go in github.com/cockroachdb/pebble.init at line 44
```

### Tags

| Tag | Value |
| --- | --- |
| Command | demo |
| Environment | v22.2.6 |
| Go Version | go1.19.4 |
| Platform | darwin arm64 |
| Distribution | CCL |
| Cockroach Release | v22.2.6 |
| Cockroach SHA | d5a076f2953c0712193b8cbe08bbb682563c5675 |
| # of CPUs | 10 |
| # of Goroutines | 5194 |

Jira issue: CRDB-29376

**Comment by yuzefovich** [comment]
dup of #86703
