### ISSUE TITLE
storage: TestReplicateQueueRebalance flaky with 10-node cluster

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#10600]
`TestReplicateQueueRebalance` currently uses a 5-node cluster. If that is changed to a 10-node cluster the test becomes flaky. The primary symptom is an inability for the 10-node cluster to startup (i.e. we never get to the loop where we're waiting for rebalancing to finish). Though I've also seen a simple failure to achieve balancing (replica counts of `[6 3 3 3 4 3 3 0 3 3]`). This deserves investigation.

Depends on #10464.

**Comment by cuongdo** [comment]
This also seems currently flaky. I got this error during a CI run for an unrelated change (to a shell script):

```
(new) TestReplicateQueueRebalance 
	testing.go:117: storage/replicate_queue_test.go:103, condition failed to evaluate within 45s: not balanced: [8 10 2 2 8]
```

**Comment by tamird** [comment]
The issue-filing problem was hopefully fixed in https://github.com/cockroachdb/cockroach/commit/3b78f37c98716aad21703e8790125bd824b3fd65.

**Comment by petermattis** [comment]
I believe this flakiness is fixed, though other flakiness in this test remains. See of #11592.
