### ISSUE TITLE
kvcoord/(mux)rangefeed: when changefeed job is cancelled distsender.rangefeed.total_ranges doesn't go down

### ISSUE THREAD

**Issue by aliher1911** [cockroachdb/cockroach#106152]
DistSender maintains a gauge metric showing number of active rangefeeds on the client side. This metric is increased when each feed covering single range is created and decreased when it is cancelled or restarted.

This behaviour seem broken as the gauge doesn't go down if rangefeed is stopped by client by cancelling context. That kind of cancellation happens when changefeed jobs are paused or cancelled.

Note that there may be other effects of rangefeed not being released correctly as this is just manifestation of rangefeed lifecycle management being broken.

**Environment:**
 - CockroachDB version 23.1.4 and likely earlier ones

Jira issue: CRDB-29429

Epic CRDB-26372

**Comment by miretskiy** [comment]
Quite honestly, I'm not sure if this issue is applicable to regular rangefeed:
```
// Register partial range feed with registry.
active := newActiveRangeFeed(span, startAfter, rr, ds.metrics.RangefeedRanges)
defer active.release()
```

Counter is incremented when new registration created, and is always decremented through defer.

The issue might be specific to mux.
