### ISSUE TITLE
foreign keys not included in information_schema.key_column_usage

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/cockroach#10615]
### Steps to repro

1. Create tables with foreign keys:
   ```
   CREATE TABLE customers (
    id INT PRIMARY KEY,
    name STRING(50)
   );
   CREATE TABLE orders (
    customer INT, 
    id INT,
    total DECIMAL(20, 5), 
    PRIMARY KEY (customer, id), 
    CONSTRAINT fk_customer FOREIGN KEY (customer) REFERENCES customers
   ) INTERLEAVE IN PARENT customers (customer) ;
   ```

2. Look for the foreign key constraint in `information_schema.key_column_usage`:
   ```
   SELECT * FROM information_schema.key_column_usage WHERE CONSTRAINT_NAME='fk_customer';
   ```

### Expected result

Row containing `information_schema.key_column_usage.CONSTRAINT_NAME` = `fk_customer` is returned.

### Actual result

No rows are returned.

**Comment by nvanbenschoten** [comment]
More specifically, the issue is that foreign keys are not included in the table when they use the primary key index. Fix incoming.
