### ISSUE TITLE
kvnemesis: `config change rejected by raft; please retry`

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#106172]
See https://github.com/cockroachdb/cockroach/issues/106104#issuecomment-1621930790
            

Jira issue: CRDB-29438

**Comment by tbg** [comment]
Related, just seen [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=10793479&buildTypeId=Cockroach_BazelEssentialCi)

```
=== RUN   TestLogGrowthWhenRefreshingPendingCommands
    test_log_scope.go:167: test logs captured to: /artifacts/tmp/_tmp/39e6f725772aee4e6ba4d8fdfd598f8c/logTestLogGrowthWhenRefreshingPendingCommands4259310833
    test_log_scope.go:81: use -show-logs to present logs inline
    client_raft_test.go:1744: could not add [n2,s2 n3,s3 n4,s4 n5,s5] replicas to range containing "a": AdminChangeReplicas error: change replicas of r64 failed: kv/kvserver/replica_proposal_buf.go:609: config change rejected by raft; please retry
        (1) AdminChangeReplicas error: change replicas of r64 failed: kv/kvserver/replica_proposal_buf.go:609: config change rejected by raft; please retry
          | -- cause hidden behind barrier
          | AdminChangeReplicas error: change replicas of r64 failed: kv/kvserver/replica_proposal_buf.go:609: config change rejected by raft; please retry
          | (1) attached stack trace
          |   -- stack trace:
          |   | github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).changeReplicas
          |   | 	github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:795
          |   | github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).addReplica
          |   | 	github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:805
          |   | github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).AddVoters
          |   | 	github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:823
          |   | github.com/cockroachdb/cockroach/pkg/testutils/testcluster.(*TestCluster).AddVotersOrFatal
          |   | 	github.com/cockroachdb/cockroach/pkg/testutils/testcluster/testcluster.go:947
          |   | github.com/cockroachdb/cockroach/pkg/kv/kvserver_test.TestLogGrowthWhenRefreshingPendingCommands
          |   | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver_test/pkg/kv/kvserver/client_raft_test.go:1744
          |   | testing.tRunner
          |   | 	GOROOT/src/testing/testing.go:1446
```

**Comment by yuzefovich** [comment]
Another instance of [this](https://github.com/cockroachdb/cockroach/issues/106172#issuecomment-1622449744) [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=10795483&buildTypeId=Cockroach_BazelEssentialCi).

**Comment by tbg** [comment]
The problem is interesting. `TestLogGrowthWhenRefreshingPendingCommands` sets up aggressive reproposals, and flakes very quickly as of #106104. My understand is that the mechanism is the following:

- we propose conf change X
- raft sets `pendingConfIndex` to the resulting lastIndex, say, 26.
- we flush the proposal to raft again.
- raft sees that there is a pending conf change at index 26 and so it drops the proposal[^1]
- we detect that (thanks to #106104) and fail the proposal
- a moment later, the proposal becomes effective anyway (i.e. the conf change applies).

In particular, the caller believes the conf change didn't go through, but it actually did. So if it retries, it will hit a hard error, because the descriptor now already reflects the change they're trying to make.

This is all pretty messy. Since CockroachDB serializes configuration changes above raft and thus isn't worried about them being incompatible with each other, the right fix might be to disable the checks inside of raft. If raft wanted to carry out these checks properly, it would really need to synthesize the entire sequence of pending log changes (incl unstable log) and verify the incoming change on top of that. Building this is hardly worth our while.

I'll note that this is all exacerbated caused by the different implementation of conf changes in etcd-io/raft compared to the raft thesis. In the latter, conf changes become active once they are appended to the log. So the window for this bug is smaller with append-time conf changes, though it is still there.

I'll do something tactical to stop the flakes (basically partial revert of #106104 since the original bug was pretty rare) for now.

[^1]: https://github.com/etcd-io/raft/blob/4abd9e927c6d5db930dfdb80237ac584449aeec7/raft.go#L1255-L1256

**Comment by knz** [comment]
also here: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/10805911?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

**Comment by msbutler** [comment]
just failed on `TestLogGrowthWhenRefreshingPendingCommands` this [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=10807988&buildTypeId=Cockroach_BazelEssentialCi)

@tbg perhaps worth skipping this test?

**Comment by erikgrinaker** [comment]
This will flake across all kinds of tests. We're reverting in #106267.

**Comment by tbg** [comment]
Closing since we reverted.
