### ISSUE TITLE
sql: flake in TestStreamerTightBudget

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#106120]
Found here: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/10777834?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

```
=== RUN   TestStreamerTightBudget
    test_log_scope.go:167: test logs captured to: /artifacts/tmp/_tmp/68623fbceec3275976bd7b2c9026005a/logTestStreamerTightBudget4205368234
    test_log_scope.go:81: use -show-logs to present logs inline
    mem_limit_test.go:201:
          Error Trace:  github.com/cockroachdb/cockroach/pkg/sql/mem_limit_test.go:201
          Error:        "2.1" is not greater than or equal to "2.7"
          Test:         TestStreamerTightBudget
          Messages:     unexpectedly high memory usage
```

Jira issue: CRDB-29413

**Comment by knz** [comment]
cc @mgartner for triage

**Comment by yuzefovich** [comment]
It is an extremely rare flake that I'm not able to repro. The last time it was reported was a year ago over in #84083 and I failed to reproduce it then too. I don't really have any theories on why this happens, so closing as unreproducible.
