### ISSUE TITLE
sql: support overloads for builtins with array args

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#10619]
After #10523 (support for `[]int` columns) goes in, we'll want builtins such as `array_length`, `array_upper`, and `array_lower` to work with both `[]string` and `[]int` arguments. With our current overload resolution mechanisms, this doesn't seem possible.

**Comment by a6802739** [comment]
@cuongdo, @nvanbenschoten, Could I have a try for it?

**Comment by nvanbenschoten** [comment]
Hey @a6802739, thanks for the interest, but I currently already have a working fix for this.
