### ISSUE TITLE
Sentry: db.go:44: pebble: closed
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | github.com/cockroachdb/pebble.(*DB).Apply
  | 	github.com/cockr...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#106109]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4293624632/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4293624632/?referrer=webhooks_plugin)

Panic Message:

```
db.go:44: pebble: closed
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | github.com/cockroachdb/pebble.(*DB).Apply
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go:702
  | github.com/cockroachdb/pebble.(*Batch).Commit
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/batch.go:1049
  | github.com/cockroachdb/cockroach/pkg/storage.(*pebbleBatch).Commit
  | 	github.com/cockroachdb/cockroach/pkg/storage/pebble_batch.go:545
  | github.com/cockroachdb/cockroach/pkg/storage.WriteSyncNoop
  | 	github.com/cockroachdb/cockroach/pkg/storage/engine.go:1243
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/liveness.(*NodeLiveness).updateLiveness.func1.1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/liveness/liveness.go:1289
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:341
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/liveness.(*NodeLiveness).updateLiveness.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/liveness/liveness.go:1287
  | github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight.(*Group).doCall
  | 	github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight/singleflight.go:128
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/pebble.(*DB).Close
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go:1239
  | github.com/cockroachdb/cockroach/pkg/storage.(*Pebble).Close
  | 	github.com/cockroachdb/cockroach/pkg/storage/pebble.go:1068
  | github.com/cockroachdb/cockroach/pkg/server.(*stickyInMemEnginesRegistryImpl).deleteEngine
  | 	github.com/cockroachdb/cockroach/pkg/server/sticky_engine.go:186
  | github.com/cockroachdb/cockroach/pkg/server.(*stickyInMemEnginesRegistryImpl).CloseAllStickyInMemEngines
  | 	github.com/cockroachdb/cockroach/pkg/server/sticky_engine.go:176
  | github.com/cockroachdb/cockroach/pkg/cli/democluster.(*transientCluster).Start.func3.1
  | 	github.com/cockroachdb/cockroach/pkg/cli/democluster/demo_cluster.go:286
  | github.com/cockroachdb/cockroach/pkg/util/stop.CloserFn.Close
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:107
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Stop
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:558
  | github.com/cockroachdb/cockroach/pkg/cli/democluster.(*transientCluster).Close
  | 	github.com/cockroachdb/cockroach/pkg/cli/democluster/demo_cluster.go:811
  | github.com/cockroachdb/cockroach/pkg/cli.runDemoInternal
  | 	github.com/cockroachdb/cockroach/pkg/cli/demo.go:372
  | github.com/cockroachdb/cockroach/pkg/cli.runDemo
  | 	github.com/cockroachdb/cockroach/pkg/cli/demo.go:210
  | github.com/cockroachdb/cockroach/pkg/cli.init.5.func1
  | 	github.com/cockroachdb/cockroach/pkg/cli/demo.go:59
  | github.com/cockroachdb/cockroach/pkg/cli/clierrorplus.MaybeDecorateError.func1
  | 	github.com/cockroachdb/cockroach/pkg/cli/clierrorplus/decorate_error.go:71
  | github.com/spf13/cobra.(*Command).execute
  | 	github.com/spf13/cobra/external/com_github_spf13_cobra/command.go:856
  | github.com/spf13/cobra.(*Command).ExecuteC
  | 	github.com/spf13/cobra/external/com_github_spf13_cobra/command.go:974
  | github.com/spf13/cobra.(*Command).Execute
  | 	github.com/spf13/cobra/external/com_github_spf13_cobra/command.go:902
  | github.com/cockroachdb/cockroach/pkg/cli.Run
  | 	github.com/cockroachdb/cockroach/pkg/cli/cli.go:298
  | github.com/cockroachdb/cockroach/pkg/cli.doMain
  | 	github.com/cockroachdb/cockroach/pkg/cli/cli.go:141
  | github.com/cockroachdb/cockroach/pkg/cli.Main
  | 	github.com/cockroachdb/cockroach/pkg/cli/cli.go:66
  | main.main
  | 	main/pkg/cmd/cockroach/main.go:26
  | [...repeated from below...]
Wraps: (3) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/pebble.init
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go:44
  | runtime.doInit
  | 	GOROOT/src/runtime/proc.go:6340
  | runtime.doInit
  | 	GOROOT/src/runtime/proc.go:6317
  | runtime.doInit
  | 	GOROOT/src/runtime/proc.go:6317
  | runtime.doInit
  | 	GOROOT/src/runtime/proc.go:6317
  | runtime.doInit
  | 	GOROOT/src/runtime/proc.go:6317
  | runtime.doInit
  | 	GOROOT/src/runtime/proc.go:6317
  | runtime.doInit
  | 	GOROOT/src/runtime/proc.go:6317
  | runtime.doInit
  | 	GOROOT/src/runtime/proc.go:6317
  | runtime.main
  | 	GOROOT/src/runtime/proc.go:233
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (4) pebble: closed
Error types: (1) *withstack.withStack (2) *withstack.withStack (3) *withstack.withStack (4) *errutil.leafError
-- report composition:
*errutil.leafError: pebble: closed
db.go:44: *withstack.withStack (top exception)
db.go:1239: *withstack.withStack (1)
panic.go:884: *withstack.withStack (2)
(check the extra data payloads)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/util/syncutil/singleflight/singleflight.go#L127-L129](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/util/syncutil/singleflight/singleflight.go#L127-L129)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/kv/kvserver/liveness/liveness.go#L1286-L1288](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/kv/kvserver/liveness/liveness.go#L1286-L1288)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/util/stop/stopper.go#L340-L342](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/util/stop/stopper.go#L340-L342)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/kv/kvserver/liveness/liveness.go#L1288-L1290](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/kv/kvserver/liveness/liveness.go#L1288-L1290)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/storage/engine.go#L1242-L1244](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/storage/engine.go#L1242-L1244)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/storage/pebble_batch.go#L544-L546](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/storage/pebble_batch.go#L544-L546)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/batch.go#L1048-L1050](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/batch.go#L1048-L1050)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L701-L703](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L701-L703)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[GOROOT/src/runtime/proc.go#L249-L251](GOROOT/src/runtime/proc.go#L249-L251)
[main/pkg/cmd/cockroach/main.go#L25-L27](main/pkg/cmd/cockroach/main.go#L25-L27)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/cli/cli.go#L65-L67](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/cli/cli.go#L65-L67)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/cli/cli.go#L140-L142](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/cli/cli.go#L140-L142)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/cli/cli.go#L297-L299](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/cli/cli.go#L297-L299)
[github.com/spf13/cobra/external/com_github_spf13_cobra/command.go#L901-L903](github.com/spf13/cobra/external/com_github_spf13_cobra/command.go#L901-L903)
[github.com/spf13/cobra/external/com_github_spf13_cobra/command.go#L973-L975](github.com/spf13/cobra/external/com_github_spf13_cobra/command.go#L973-L975)
[github.com/spf13/cobra/external/com_github_spf13_cobra/command.go#L855-L857](github.com/spf13/cobra/external/com_github_spf13_cobra/command.go#L855-L857)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/cli/clierrorplus/decorate_error.go#L70-L72](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/cli/clierrorplus/decorate_error.go#L70-L72)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/cli/demo.go#L58-L60](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/cli/demo.go#L58-L60)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/cli/demo.go#L209-L211](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/cli/demo.go#L209-L211)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/cli/demo.go#L371-L373](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/cli/demo.go#L371-L373)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/cli/democluster/demo_cluster.go#L810-L812](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/cli/democluster/demo_cluster.go#L810-L812)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/util/stop/stopper.go#L557-L559](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/util/stop/stopper.go#L557-L559)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/util/stop/stopper.go#L106-L108](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/util/stop/stopper.go#L106-L108)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/cli/democluster/demo_cluster.go#L285-L287](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/cli/democluster/demo_cluster.go#L285-L287)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/server/sticky_engine.go#L175-L177](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/server/sticky_engine.go#L175-L177)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/server/sticky_engine.go#L185-L187](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/server/sticky_engine.go#L185-L187)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/storage/pebble.go#L1067-L1069](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/storage/pebble.go#L1067-L1069)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L1238-L1240](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L1238-L1240)
[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[GOROOT/src/runtime/proc.go#L232-L234](GOROOT/src/runtime/proc.go#L232-L234)
[GOROOT/src/runtime/proc.go#L6316-L6318](GOROOT/src/runtime/proc.go#L6316-L6318)
[GOROOT/src/runtime/proc.go#L6316-L6318](GOROOT/src/runtime/proc.go#L6316-L6318)
[GOROOT/src/runtime/proc.go#L6316-L6318](GOROOT/src/runtime/proc.go#L6316-L6318)
[GOROOT/src/runtime/proc.go#L6316-L6318](GOROOT/src/runtime/proc.go#L6316-L6318)
[GOROOT/src/runtime/proc.go#L6316-L6318](GOROOT/src/runtime/proc.go#L6316-L6318)
[GOROOT/src/runtime/proc.go#L6316-L6318](GOROOT/src/runtime/proc.go#L6316-L6318)
[GOROOT/src/runtime/proc.go#L6316-L6318](GOROOT/src/runtime/proc.go#L6316-L6318)
[GOROOT/src/runtime/proc.go#L6339-L6341](GOROOT/src/runtime/proc.go#L6339-L6341)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L43-L45](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L43-L45)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/util/syncutil/singleflight/singleflight.go in pkg/util/syncutil/singleflight.(*Group).doCall at line 128
pkg/kv/kvserver/liveness/liveness.go in pkg/kv/kvserver/liveness.(*NodeLiveness).updateLiveness.func1 at line 1287
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunTaskWithErr at line 341
pkg/kv/kvserver/liveness/liveness.go in pkg/kv/kvserver/liveness.(*NodeLiveness).updateLiveness.func1.1 at line 1289
pkg/storage/engine.go in pkg/storage.WriteSyncNoop at line 1243
pkg/storage/pebble_batch.go in pkg/storage.(*pebbleBatch).Commit at line 545
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/batch.go in github.com/cockroachdb/pebble.(*Batch).Commit at line 1049
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go in github.com/cockroachdb/pebble.(*DB).Apply at line 702
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
GOROOT/src/runtime/proc.go in runtime.main at line 250
main/pkg/cmd/cockroach/main.go in main.main at line 26
pkg/cli/cli.go in pkg/cli.Main at line 66
pkg/cli/cli.go in pkg/cli.doMain at line 141
pkg/cli/cli.go in pkg/cli.Run at line 298
github.com/spf13/cobra/external/com_github_spf13_cobra/command.go in github.com/spf13/cobra.(*Command).Execute at line 902
github.com/spf13/cobra/external/com_github_spf13_cobra/command.go in github.com/spf13/cobra.(*Command).ExecuteC at line 974
github.com/spf13/cobra/external/com_github_spf13_cobra/command.go in github.com/spf13/cobra.(*Command).execute at line 856
pkg/cli/clierrorplus/decorate_error.go in pkg/cli/clierrorplus.MaybeDecorateError.func1 at line 71
pkg/cli/demo.go in pkg/cli.init.5.func1 at line 59
pkg/cli/demo.go in pkg/cli.runDemo at line 210
pkg/cli/demo.go in pkg/cli.runDemoInternal at line 372
pkg/cli/democluster/demo_cluster.go in pkg/cli/democluster.(*transientCluster).Close at line 811
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).Stop at line 558
pkg/util/stop/stopper.go in pkg/util/stop.CloserFn.Close at line 107
pkg/cli/democluster/demo_cluster.go in pkg/cli/democluster.(*transientCluster).Start.func3.1 at line 286
pkg/server/sticky_engine.go in pkg/server.(*stickyInMemEnginesRegistryImpl).CloseAllStickyInMemEngines at line 176
pkg/server/sticky_engine.go in pkg/server.(*stickyInMemEnginesRegistryImpl).deleteEngine at line 186
pkg/storage/pebble.go in pkg/storage.(*Pebble).Close at line 1068
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go in github.com/cockroachdb/pebble.(*DB).Close at line 1239
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
GOROOT/src/runtime/proc.go in runtime.main at line 233
GOROOT/src/runtime/proc.go in runtime.doInit at line 6317
GOROOT/src/runtime/proc.go in runtime.doInit at line 6317
GOROOT/src/runtime/proc.go in runtime.doInit at line 6317
GOROOT/src/runtime/proc.go in runtime.doInit at line 6317
GOROOT/src/runtime/proc.go in runtime.doInit at line 6317
GOROOT/src/runtime/proc.go in runtime.doInit at line 6317
GOROOT/src/runtime/proc.go in runtime.doInit at line 6317
GOROOT/src/runtime/proc.go in runtime.doInit at line 6340
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go in github.com/cockroachdb/pebble.init at line 44
```

### Tags

| Tag | Value |
| --- | --- |
| Command | demo |
| Environment | v22.2.0 |
| Go Version | go1.19.1 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v22.2.0 |
| Cockroach SHA | 77667a1b0101cd323090011f50cf910aaa933654 |
| # of CPUs | 2 |
| # of Goroutines | 289 |

Jira issue: CRDB-29408

**Comment by yuzefovich** [comment]
dup of #86703
