### ISSUE TITLE
sql: flakes caused by leaked goroutine `diskHealthCheckingFile` in tests

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#106119]
Found e.g. in https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_BazelUnitTests/10777271?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

```
    explain_test.go:559: Leaked goroutine: goroutine 45013 [select]:
        github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker.func1()
          github.com/cockroachdb/pebble/vfs/external/com_github_cockroachdb_pebble/vfs/disk_health.go:172 +0xdc
        created by github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker
          github.com/cockroachdb/pebble/vfs/external/com_github_cockroachdb_pebble/vfs/disk_health.go:167 +0x5d
```

The routine needs either to shut down cleanly, or be declared as a possible leak in package `leaktest`.

This typically happens when an engine isn't closed during test tear-down. The following tests have been identified (via #106195):

- [ ] `pkg/sql/colexec.TestExternalDistinct`
- [ ] `pkg/sql/colexec.TestSpillingBuffer`
- [ ] `pkg/sql/colcontainer/colcontainer_test.TestPartitionedDiskQueueSimulatedExternal`

Jira issue: CRDB-29411

**Comment by jbowens** [comment]
Typically this is caused by some higher-level code using the Engine’s filesystem after the engine has been closed, causing these goroutines to be recreated. Maybe we should detect this within the Engine and error with an explanatory error message.

**Comment by nicktrav** [comment]
I updated the description to mention the tests caught by https://github.com/cockroachdb/cockroach/pull/106195.
