### ISSUE TITLE
Sentry: migrations.go:563: log.Fatal: not enough time left on migration lease, terminating for safety
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/startupmigrati...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#106209]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4296344123/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4296344123/?referrer=webhooks_plugin)

Panic Message:

```
migrations.go:563: log.Fatal: not enough time left on migration lease, terminating for safety
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/startupmigrations.(*Manager).EnsureMigrations.func2
  | 	github.com/cockroachdb/cockroach/pkg/startupmigrations/migrations.go:563
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:489
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (2) log.Fatal: not enough time left on migration lease, terminating for safety
Error types: (1) *withstack.withStack (2) *errutil.leafError
-- report composition:
*errutil.leafError: log.Fatal: not enough time left on migration lease, terminating for safety
migrations.go:563: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/util/stop/stopper.go#L488-L490](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/util/stop/stopper.go#L488-L490)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/startupmigrations/migrations.go#L562-L564](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/startupmigrations/migrations.go#L562-L564)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 489
pkg/startupmigrations/migrations.go in pkg/startupmigrations.(*Manager).EnsureMigrations.func2 at line 563
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v22.2.0 |
| Go Version | go1.19.1 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v22.2.0 |
| Cockroach SHA | 77667a1b0101cd323090011f50cf910aaa933654 |
| # of CPUs | 40 |
| # of Goroutines | 289 |

Jira issue: CRDB-29447

**Comment by yuzefovich** [comment]
dup of #57113
