### ISSUE TITLE
c2c: report replication lag more accurately

### ISSUE THREAD

**Issue by lidorcarmel** [cockroachdb/cockroach#106213]
slack: https://cockroachlabs.slack.com/archives/C054X9T82AU/p1688578078263589

we saw that in a tiny cluster the replication lag was just over 3 seconds, but if we checkpoint every 10 seconds then such short lag doesn't make sense, so something is not right.

Jira issue: CRDB-29448

**Comment by stevendanna** [comment]
I believe I fixed this in 681a015c7f13125ca237d8111e7bb6727fb220b8 but and then subsequently @msbutler removed this metric. So, this can be closed.
