### ISSUE TITLE
multitenant: TestTenantUpgradeFailure/upgrade_tenant_have_it_crash_then_resume flaked on master

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#106279]
See flake [here ](https://teamcity.cockroachdb.com/viewLog.html?buildId=10804367&buildTypeId=Cockroach_BazelEssentialCi)

Jira issue: CRDB-29478
Epic: CRDB-18499

**Comment by healthy-pod** [comment]
While this failure did not reproduce locally, another failure reproduces (see logs below). This may or may not be a failure, it might just be a need to make the expected error expect more cases.

[TestTenantUpgradeFailure.log](https://github.com/cockroachdb/cockroach/files/11985909/TestTenantUpgradeFailure.log)

**Comment by tbg** [comment]
I also got this in https://teamcity.cockroachdb.com/viewLog.html?buildId=10865118&buildTypeId=Cockroach_BazelEssentialCi, are we fixing ASAP or skipping?

**Comment by msbutler** [comment]
hit this once again [here.](https://teamcity.cockroachdb.com/viewLog.html?buildId=10866869&buildTypeId=Cockroach_BazelEssentialCi). Going to skip.

**Comment by yuzefovich** [comment]
Documenting failure modes observed so far:
- initial [report](https://github.com/cockroachdb/cockroach/issues/106279#issue-1791649849) from Michael:
```
Error Trace:	pkg/ccl/kvccl/kvtenantccl/upgradeccl/upgradeccl_test_test/pkg/ccl/kvccl/kvtenantccl/upgradeccl/tenant_upgrade_test.go:244
        	            				pkg/ccl/kvccl/kvtenantccl/upgradeccl/upgradeccl_test_test/pkg/ccl/kvccl/kvtenantccl/upgradeccl/tenant_upgrade_test.go:347
        	Error:      	Received unexpected error:
        	            	migration-job-find-already-completed: failed to connect to n1 at 127.0.0.1:42029: initial connection heartbeat failed: grpc: connection error: desc = "error reading server preface: http2: frame too large" [code 14/Unavailable]
```
- [reproduction](https://github.com/cockroachdb/cockroach/issues/106279#issuecomment-1626071406) from Ahmad:
```
I230707 20:26:25.928348 22 testutils/testcluster/testcluster.go:145  [-] 5682  TestCluster quiescing nodes
     tenant_upgrade_test.go:340: expected query 'SET CLUSTER SETTING version = $1' error '.*(database is closed|failed to connect|closed network connection|upgrade      failed due to transient SQL servers)+', got: pq: migration-job-mark-job succeeded: tenant-side-limiter pool closed: shutting down
```
- [reproduction](https://github.com/cockroachdb/cockroach/issues/106279#issuecomment-1630582198) from Tobi:
```
    sql_runner.go:313: error executing 'SELECT count(*) FROM system.sql_instances WHERE session_id IS NOT NULL': pq: failed to connect to n1 at 127.0.0.1:37095: initial connection heartbeat failed: grpc: connection error: desc = "error reading server preface: http2: frame too large" [code 14/Unavailable]
```
- [2nd reproduction](https://github.com/cockroachdb/cockroach/issues/106279#issuecomment-1631068841) from Michael:
```
    sql_runner.go:313: error executing 'SELECT count(*) FROM system.sql_instances WHERE session_id IS NOT NULL': pq: failed to connect to n2 at 127.0.0.1:37551: initial connection heartbeat failed: grpc: client cluster ID "fbc7e75d-63c9-44f4-8124-c3efdf9d5265" doesn't match server cluster ID "7d710a5e-a37a-43ff-ac9a-ace152e5b8f0" [code 2/Unknown]
```

**Comment by knz** [comment]
I might have found the problem and will queue a patch in #107659.
