### ISSUE TITLE
sql: TestValidateMixedVersionElements_drop_multiple_columns_separate_statements  flaked

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#106315]
See flake [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=10804196&buildTypeId=Cockroach_BazelEssentialCi)

Jira issue: CRDB-29501

**Comment by rafiss** [comment]
Test logs are in `bazel-testlogs/pkg/sql/schemachanger/schemachanger_test/shard_1_of_16/test.log`

That points to CRDB logs in `tmp/_tmp/24477c4276b6f65cd49d6f82cc146a3a/logTestValidateMixedVersionElements_drop_multiple_columns_separate_statements3288707207/schemachangertest.log`

```
W230706 12:14:44.689329 316257 kv/kvserver/intentresolver/intent_resolver.go:826 â‹® [-] 179  failed to gc transaction record: could not GC completed transaction anchored at /Table/15/1/â€¹880067491110027265â€º: node unavailable; try another peer
I230706 12:14:44.689623 314700 sql/stats/automatic_stats.go:572 â‹® [T1,n1] 180  quiescing auto stats refresher
I230706 12:14:44.689966 314250 server/start_listen.go:103 â‹® [T1,n1] 181  server shutting down: instructing cmux to stop accepting
W230706 12:14:44.690294 314670 sql/sqlliveness/slinstance/slinstance.go:334 â‹® [T1,n1] 182  exiting heartbeat loop
W230706 12:14:44.690307 314670 sql/sqlliveness/slinstance/slinstance.go:321 â‹® [T1,n1] 183  exiting heartbeat loop with error: node unavailable; try another peer
E230706 12:14:44.690321 314670 server/server_sql.go:514 â‹® [T1,n1] 184  failed to run update of instance with new session ID: node unavailable; try another peer
E230706 12:14:44.690763 316156 jobs/registry.go:1004 â‹® [T1,n1] 185  error getting live session: node unavailable; try another peer
```

Could it relate to liveness, similar to https://github.com/cockroachdb/cockroach/issues/105756? Tagging the KV team for help, but feel free to reassign if that's not it.

**Comment by tbg** [comment]
The snippet above is just server shutdown after the test fails, I don't think it points at KV in particular. You will see this on each and every server shutdown.

I got a similar flake [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=10804390&buildTypeId=Cockroach_UnitTests_BazelUnitTests&tab=buildResultsDiv&branch_Cockroach_Ci_TestsGcpLinuxX8664BigVm=staging), not in the exact same test but still, note the weird exit 1

https://teamcity.cockroachdb.com/repository/download/Cockroach_UnitTests_BazelUnitTests/10804390:id/bazel-testlogs/pkg/sql/schemachanger/schemachanger_test/shard_8_of_16/test.log

**Comment by tbg** [comment]
Just noticed in the above logs in the build log,

> [Run unit tests] I230706 14:18:25.256501 1 util/log/log_bridge.go:81  [-] 1  bad log format: ERROR: exit status 3

Not sure if that's a red herring, probably is, comes from here https://github.com/cockroachdb/cockroach/blob/e57ace1cbcd39013fbd246309839065e847955f7/pkg/util/log/log_bridge.go#L94

**Comment by irfansharif** [comment]
Just in case this was https://github.com/cockroachdb/cockroach/issues/106078, I took a look at the logs. I'm not finding the "operating on a closed handle" logging that would suggest the same mutex leak.

**Comment by rafiss** [comment]
We'll take this back over. There are 13 other open issues relating to this flake. https://github.com/cockroachdb/cockroach/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+TestValidateMixedVersionElements

**Comment by rafiss** [comment]
We can't repro since after https://github.com/cockroachdb/cockroach/pull/106411 was merged.
