### ISSUE TITLE
cdc: Audit AssertionFailed error usages and treat those as terminal errors

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#106385]
We use AssertionFailed errors messages in many places -- incorrectly so.
AssertionFailed should be just that -- a precondition failure such that when
retried with the same input, would result in the same error happening again.

We should audit/fix misuses of this error type and ensure that assertion
failures are treated as terminal changefeed errors.

Jira issue: CRDB-29546

**Comment by amruss** [comment]
Looks like it should be closed already
