### ISSUE TITLE
sql: v23.1.5: UDF descriptor no found

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#106388]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4300193921/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4300193921/?referrer=webhooks_plugin)

Panic Message:

```
errors.go:90: referenced descriptor ID 255: descriptor not found
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.wrapError
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_query.go:173
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.catalogQuery.processDescriptorResultRow
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_query.go:116
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.catalogQuery.query
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_query.go:75
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.catalogReader.GetByIDs
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_reader.go:277
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.(*cachedCatalogReader).GetByIDs
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_reader_cached.go:340
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.getDescriptorsByID
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:207
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.getDescriptorByName
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:406
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.ByNameGetter.Schema
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/getters.go:269
  | github.com/cockroachdb/cockroach/pkg/sql.(*schemaResolver).LookupSchema
  | 	github.com/cockroachdb/cockroach/pkg/sql/schema_resolver.go:196
  | github.com/cockroachdb/cockroach/pkg/sql.maybeLookUpUDF
  | 	github.com/cockroachdb/cockroach/pkg/sql/schema_resolver.go:536
  | github.com/cockroachdb/cockroach/pkg/sql.(*schemaResolver).ResolveFunction
  | 	github.com/cockroachdb/cockroach/pkg/sql/schema_resolver.go:441
  | github.com/cockroachdb/cockroach/pkg/sql.(*optCatalog).ResolveFunction
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt_catalog.go:343
  | github.com/cockroachdb/cockroach/pkg/sql/opt.(*Metadata).CheckDependencies
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/metadata.go:448
  | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*Memo).IsStale
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/memo/memo.go:381
  | github.com/cockroachdb/cockroach/pkg/sql.(*optPlanningCtx).buildExecMemo
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:545
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).makeOptimizerPlan
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:240
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).makeExecPlan
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1978
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1484
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:964
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:142
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2986
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:141
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2181
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2186
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2103
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:900
  | [...repeated from below...]
Wraps: (3) referenced descriptor ID 255
Wraps: (4) secondary error attachment
  | failed to find descriptor [255]
  | (1) attached stack trace
  |   -- stack trace:
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.requiredError
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_query.go:215
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.build
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_query.go:187
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.catalogQuery.processDescriptorResultRow
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_query.go:114
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.catalogQuery.query
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_query.go:75
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.catalogReader.GetByIDs
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_reader.go:277
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.(*cachedCatalogReader).GetByIDs
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_reader_cached.go:340
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.getDescriptorsByID
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:207
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.getDescriptorByName
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:406
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.ByNameGetter.Schema
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/getters.go:269
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*schemaResolver).LookupSchema
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/schema_resolver.go:196
  |   | github.com/cockroachdb/cockroach/pkg/sql.maybeLookUpUDF
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/schema_resolver.go:536
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*schemaResolver).ResolveFunction
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/schema_resolver.go:441
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*optCatalog).ResolveFunction
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/opt_catalog.go:343
  |   | github.com/cockroachdb/cockroach/pkg/sql/opt.(*Metadata).CheckDependencies
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/opt/metadata.go:448
  |   | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*Memo).IsStale
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/opt/memo/memo.go:381
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*optPlanningCtx).buildExecMemo
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:545
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*planner).makeOptimizerPlan
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:240
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).makeExecPlan
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1978
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1484
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:964
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:142
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2986
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:141
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_exec...
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/pgwire/conn.go#L309-L311](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/pgwire/conn.go#L309-L311)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/conn_executor.go#L899-L901](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/conn_executor.go#L899-L901)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/conn_executor.go#L2102-L2104](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/conn_executor.go#L2102-L2104)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/conn_executor.go#L2185-L2187](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/conn_executor.go#L2185-L2187)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/conn_executor.go#L2180-L2182](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/conn_executor.go#L2180-L2182)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/conn_executor_exec.go#L140-L142](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/conn_executor_exec.go#L140-L142)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/conn_executor_exec.go#L2985-L2987](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/conn_executor_exec.go#L2985-L2987)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/conn_executor_exec.go#L141-L143](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/conn_executor_exec.go#L141-L143)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/conn_executor_exec.go#L963-L965](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/conn_executor_exec.go#L963-L965)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/conn_executor_exec.go#L1483-L1485](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/conn_executor_exec.go#L1483-L1485)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/conn_executor_exec.go#L1977-L1979](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/conn_executor_exec.go#L1977-L1979)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/plan_opt.go#L239-L241](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/plan_opt.go#L239-L241)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/plan_opt.go#L544-L546](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/plan_opt.go#L544-L546)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt/memo/memo.go#L380-L382](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt/memo/memo.go#L380-L382)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt/metadata.go#L447-L449](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt/metadata.go#L447-L449)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt_catalog.go#L342-L344](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt_catalog.go#L342-L344)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/schema_resolver.go#L440-L442](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/schema_resolver.go#L440-L442)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/schema_resolver.go#L535-L537](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/schema_resolver.go#L535-L537)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/schema_resolver.go#L195-L197](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/schema_resolver.go#L195-L197)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/catalog/descs/getters.go#L268-L270](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/catalog/descs/getters.go#L268-L270)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/catalog/descs/descriptor.go#L405-L407](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/catalog/descs/descriptor.go#L405-L407)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/catalog/descs/descriptor.go#L206-L208](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/catalog/descs/descriptor.go#L206-L208)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/catalog/internal/catkv/catalog_reader_cached.go#L339-L341](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/catalog/internal/catkv/catalog_reader_cached.go#L339-L341)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/catalog/internal/catkv/catalog_reader.go#L276-L278](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/catalog/internal/catkv/catalog_reader.go#L276-L278)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/catalog/internal/catkv/catalog_query.go#L74-L76](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/catalog/internal/catkv/catalog_query.go#L74-L76)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/catalog/internal/catkv/catalog_query.go#L115-L117](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/catalog/internal/catkv/catalog_query.go#L115-L117)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/catalog/internal/catkv/catalog_query.go#L172-L174](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/catalog/internal/catkv/catalog_query.go#L172-L174)
[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[GOROOT/src/runtime/proc.go#L232-L234](GOROOT/src/runtime/proc.go#L232-L234)
[GOROOT/src/runtime/proc.go#L6325-L6327](GOROOT/src/runtime/proc.go#L6325-L6327)
[GOROOT/src/runtime/proc.go#L6325-L6327](GOROOT/src/runtime/proc.go#L6325-L6327)
[GOROOT/src/runtime/proc.go#L6325-L6327](GOROOT/src/runtime/proc.go#L6325-L6327)
[GOROOT/src/runtime/proc.go#L6325-L6327](GOROOT/src/runtime/proc.go#L6325-L6327)
[GOROOT/src/runtime/proc.go#L6325-L6327](GOROOT/src/runtime/proc.go#L6325-L6327)
[GOROOT/src/runtime/proc.go#L6348-L6350](GOROOT/src/runtime/proc.go#L6348-L6350)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/catalog/errors.go#L89-L91](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/catalog/errors.go#L89-L91)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommandsAsync.func1 at line 310
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 900
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 2103
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 2186
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd.func1 at line 2181
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 141
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithProfiling at line 2986
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt.func1 at line 142
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 964
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchToExecutionEngine at line 1484
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).makeExecPlan at line 1978
pkg/sql/plan_opt.go in pkg/sql.(*planner).makeOptimizerPlan at line 240
pkg/sql/plan_opt.go in pkg/sql.(*optPlanningCtx).buildExecMemo at line 545
pkg/sql/opt/memo/memo.go in pkg/sql/opt/memo.(*Memo).IsStale at line 381
pkg/sql/opt/metadata.go in pkg/sql/opt.(*Metadata).CheckDependencies at line 448
pkg/sql/opt_catalog.go in pkg/sql.(*optCatalog).ResolveFunction at line 343
pkg/sql/schema_resolver.go in pkg/sql.(*schemaResolver).ResolveFunction at line 441
pkg/sql/schema_resolver.go in pkg/sql.maybeLookUpUDF at line 536
pkg/sql/schema_resolver.go in pkg/sql.(*schemaResolver).LookupSchema at line 196
pkg/sql/catalog/descs/getters.go in pkg/sql/catalog/descs.ByNameGetter.Schema at line 269
pkg/sql/catalog/descs/descriptor.go in pkg/sql/catalog/descs.getDescriptorByName at line 406
pkg/sql/catalog/descs/descriptor.go in pkg/sql/catalog/descs.getDescriptorsByID at line 207
pkg/sql/catalog/internal/catkv/catalog_reader_cached.go in pkg/sql/catalog/internal/catkv.(*cachedCatalogReader).GetByIDs at line 340
pkg/sql/catalog/internal/catkv/catalog_reader.go in pkg/sql/catalog/internal/catkv.catalogReader.GetByIDs at line 277
pkg/sql/catalog/internal/catkv/catalog_query.go in pkg/sql/catalog/internal/catkv.catalogQuery.query at line 75
pkg/sql/catalog/internal/catkv/catalog_query.go in pkg/sql/catalog/internal/catkv.catalogQuery.processDescriptorResultRow at line 116
pkg/sql/catalog/internal/catkv/catalog_query.go in pkg/sql/catalog/internal/catkv.wrapError at line 173
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
GOROOT/src/runtime/proc.go in runtime.main at line 233
GOROOT/src/runtime/proc.go in runtime.doInit at line 6326
GOROOT/src/runtime/proc.go in runtime.doInit at line 6326
GOROOT/src/runtime/proc.go in runtime.doInit at line 6326
GOROOT/src/runtime/proc.go in runtime.doInit at line 6326
GOROOT/src/runtime/proc.go in runtime.doInit at line 6326
GOROOT/src/runtime/proc.go in runtime.doInit at line 6349
pkg/sql/catalog/errors.go in pkg/sql/catalog.init at line 90
```

### Tags

| Tag | Value |
| --- | --- |
| Command | start-single-node |
| Environment | v23.1.5 |
| Go Version | go1.19.10 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.5 |
| Cockroach SHA | 72556c6b5dc0d4ed1a0202bc4176586956d54739 |
| # of CPUs | 12 |
| # of Goroutines | 472 |

Jira issue: CRDB-29549

**Comment by msirek** [comment]
This may be unactionable.
I tried creating a UDF and a prepared statement that calls it, then execute it over and over.
In a connection on another node I drop the UDF. 
But I get the error:
`ERROR: descriptor is being dropped`
followed by
`ERROR: function 117 does not exist: function undefined`
instead of this internal error and call stack.

**Comment by rharding6373** [comment]
This may be in SQL Foundations purview.

**Comment by DrewKimball** [comment]
I notice the `NewUndefinedFunctionError` function is never used. Other schema objects have similar functions that are used when a descriptor lookup results in "descriptor not found". Maybe we forgot to do this for functions?

**Comment by chengxiong-ruan** [comment]
> I notice the NewUndefinedFunctionError function is never used. Other schema objects have similar functions that are used when a descriptor lookup results in "descriptor not found". Maybe we forgot to do this for functions?

Good catch. We do have another helper func for function resolution [here](https://github.com/cockroachdb/cockroach/blob/9db3a0eaf6cf0f669352a09c7798c41b21a3a4bd/pkg/sql/schema_resolver.go#L517-L517). It's likely a leftover not cleaned up after some refactoring. I'll delete that.

**Comment by rafiss** [comment]
closing due to staleness
