### ISSUE TITLE
Sentry: panic.go:884: panic: ×
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).regi...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#106328]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4298697977/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4298697977/?referrer=webhooks_plugin)

Panic Message:

```
panic.go:884: panic: ×
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).registerWithRangefeedRaftMuLocked
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_rangefeed.go:408
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).RangeFeed
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_rangefeed.go:219
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).RangeFeed
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store.go:2849
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Stores).RangeFeed
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/stores.go:228
  | github.com/cockroachdb/cockroach/pkg/server.(*Node).RangeFeed
  | 	github.com/cockroachdb/cockroach/pkg/server/node.go:1462
  | github.com/cockroachdb/cockroach/pkg/rpc.internalClientAdapter.RangeFeed.func2.1
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:1163
  | github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor.StreamServerInterceptor.func1
  | 	github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go:164
  | github.com/cockroachdb/cockroach/pkg/rpc.serverStreamInterceptorsChain.run.func1
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:978
  | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func4
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:285
  | github.com/cockroachdb/cockroach/pkg/rpc.serverStreamInterceptorsChain.run.func1
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:981
  | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func2.1
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:252
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:322
  | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:251
  | github.com/cockroachdb/cockroach/pkg/rpc.serverStreamInterceptorsChain.run.func1
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:981
  | github.com/cockroachdb/cockroach/pkg/rpc.serverStreamInterceptorsChain.run
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:983
  | github.com/cockroachdb/cockroach/pkg/rpc.internalClientAdapter.RangeFeed.func2
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:1168
  | runtime.goexit
  | 	src/runtime/asm_amd64.s:1594
Wraps: (2) panic: ×
Error types: (1) *withstack.withStack (2) *errutil.leafError
-- report composition:
*errutil.leafError: panic: ×
panic.go:884: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_amd64.s#L1593-L1595](src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/358e0d87912365b8976c55ab9b3292e999cf720d/pkg/rpc/pkg/rpc/context.go#L1167-L1169](https://github.com/cockroachdb/cockroach/blob/358e0d87912365b8976c55ab9b3292e999cf720d/pkg/rpc/pkg/rpc/context.go#L1167-L1169)
[https://github.com/cockroachdb/cockroach/blob/358e0d87912365b8976c55ab9b3292e999cf720d/pkg/rpc/pkg/rpc/context.go#L982-L984](https://github.com/cockroachdb/cockroach/blob/358e0d87912365b8976c55ab9b3292e999cf720d/pkg/rpc/pkg/rpc/context.go#L982-L984)
[https://github.com/cockroachdb/cockroach/blob/358e0d87912365b8976c55ab9b3292e999cf720d/pkg/rpc/pkg/rpc/context.go#L980-L982](https://github.com/cockroachdb/cockroach/blob/358e0d87912365b8976c55ab9b3292e999cf720d/pkg/rpc/pkg/rpc/context.go#L980-L982)
[https://github.com/cockroachdb/cockroach/blob/358e0d87912365b8976c55ab9b3292e999cf720d/pkg/rpc/pkg/rpc/context.go#L250-L252](https://github.com/cockroachdb/cockroach/blob/358e0d87912365b8976c55ab9b3292e999cf720d/pkg/rpc/pkg/rpc/context.go#L250-L252)
[https://github.com/cockroachdb/cockroach/blob/358e0d87912365b8976c55ab9b3292e999cf720d/pkg/util/stop/stopper.go#L321-L323](https://github.com/cockroachdb/cockroach/blob/358e0d87912365b8976c55ab9b3292e999cf720d/pkg/util/stop/stopper.go#L321-L323)
[https://github.com/cockroachdb/cockroach/blob/358e0d87912365b8976c55ab9b3292e999cf720d/pkg/rpc/pkg/rpc/context.go#L251-L253](https://github.com/cockroachdb/cockroach/blob/358e0d87912365b8976c55ab9b3292e999cf720d/pkg/rpc/pkg/rpc/context.go#L251-L253)
[https://github.com/cockroachdb/cockroach/blob/358e0d87912365b8976c55ab9b3292e999cf720d/pkg/rpc/pkg/rpc/context.go#L980-L982](https://github.com/cockroachdb/cockroach/blob/358e0d87912365b8976c55ab9b3292e999cf720d/pkg/rpc/pkg/rpc/context.go#L980-L982)
[https://github.com/cockroachdb/cockroach/blob/358e0d87912365b8976c55ab9b3292e999cf720d/pkg/rpc/pkg/rpc/context.go#L284-L286](https://github.com/cockroachdb/cockroach/blob/358e0d87912365b8976c55ab9b3292e999cf720d/pkg/rpc/pkg/rpc/context.go#L284-L286)
[https://github.com/cockroachdb/cockroach/blob/358e0d87912365b8976c55ab9b3292e999cf720d/pkg/rpc/pkg/rpc/context.go#L977-L979](https://github.com/cockroachdb/cockroach/blob/358e0d87912365b8976c55ab9b3292e999cf720d/pkg/rpc/pkg/rpc/context.go#L977-L979)
[https://github.com/cockroachdb/cockroach/blob/358e0d87912365b8976c55ab9b3292e999cf720d/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go#L163-L165](https://github.com/cockroachdb/cockroach/blob/358e0d87912365b8976c55ab9b3292e999cf720d/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go#L163-L165)
[https://github.com/cockroachdb/cockroach/blob/358e0d87912365b8976c55ab9b3292e999cf720d/pkg/rpc/pkg/rpc/context.go#L1162-L1164](https://github.com/cockroachdb/cockroach/blob/358e0d87912365b8976c55ab9b3292e999cf720d/pkg/rpc/pkg/rpc/context.go#L1162-L1164)
[https://github.com/cockroachdb/cockroach/blob/358e0d87912365b8976c55ab9b3292e999cf720d/pkg/server/node.go#L1461-L1463](https://github.com/cockroachdb/cockroach/blob/358e0d87912365b8976c55ab9b3292e999cf720d/pkg/server/node.go#L1461-L1463)
[https://github.com/cockroachdb/cockroach/blob/358e0d87912365b8976c55ab9b3292e999cf720d/pkg/kv/kvserver/pkg/kv/kvserver/stores.go#L227-L229](https://github.com/cockroachdb/cockroach/blob/358e0d87912365b8976c55ab9b3292e999cf720d/pkg/kv/kvserver/pkg/kv/kvserver/stores.go#L227-L229)
[https://github.com/cockroachdb/cockroach/blob/358e0d87912365b8976c55ab9b3292e999cf720d/pkg/kv/kvserver/pkg/kv/kvserver/store.go#L2848-L2850](https://github.com/cockroachdb/cockroach/blob/358e0d87912365b8976c55ab9b3292e999cf720d/pkg/kv/kvserver/pkg/kv/kvserver/store.go#L2848-L2850)
[https://github.com/cockroachdb/cockroach/blob/358e0d87912365b8976c55ab9b3292e999cf720d/pkg/kv/kvserver/pkg/kv/kvserver/replica_rangefeed.go#L218-L220](https://github.com/cockroachdb/cockroach/blob/358e0d87912365b8976c55ab9b3292e999cf720d/pkg/kv/kvserver/pkg/kv/kvserver/replica_rangefeed.go#L218-L220)
[https://github.com/cockroachdb/cockroach/blob/358e0d87912365b8976c55ab9b3292e999cf720d/pkg/kv/kvserver/pkg/kv/kvserver/replica_rangefeed.go#L407-L409](https://github.com/cockroachdb/cockroach/blob/358e0d87912365b8976c55ab9b3292e999cf720d/pkg/kv/kvserver/pkg/kv/kvserver/replica_rangefeed.go#L407-L409)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
</details>

```
src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/rpc/pkg/rpc/context.go in pkg/rpc.internalClientAdapter.RangeFeed.func2 at line 1168
pkg/rpc/pkg/rpc/context.go in pkg/rpc.serverStreamInterceptorsChain.run at line 983
pkg/rpc/pkg/rpc/context.go in pkg/rpc.serverStreamInterceptorsChain.run.func1 at line 981
pkg/rpc/pkg/rpc/context.go in pkg/rpc.NewServerEx.func2 at line 251
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunTaskWithErr at line 322
pkg/rpc/pkg/rpc/context.go in pkg/rpc.NewServerEx.func2.1 at line 252
pkg/rpc/pkg/rpc/context.go in pkg/rpc.serverStreamInterceptorsChain.run.func1 at line 981
pkg/rpc/pkg/rpc/context.go in pkg/rpc.NewServerEx.func4 at line 285
pkg/rpc/pkg/rpc/context.go in pkg/rpc.serverStreamInterceptorsChain.run.func1 at line 978
pkg/util/tracing/grpcinterceptor/grpc_interceptor.go in pkg/util/tracing/grpcinterceptor.StreamServerInterceptor.func1 at line 164
pkg/rpc/pkg/rpc/context.go in pkg/rpc.internalClientAdapter.RangeFeed.func2.1 at line 1163
pkg/server/node.go in pkg/server.(*Node).RangeFeed at line 1462
pkg/kv/kvserver/pkg/kv/kvserver/stores.go in pkg/kv/kvserver.(*Stores).RangeFeed at line 228
pkg/kv/kvserver/pkg/kv/kvserver/store.go in pkg/kv/kvserver.(*Store).RangeFeed at line 2849
pkg/kv/kvserver/pkg/kv/kvserver/replica_rangefeed.go in pkg/kv/kvserver.(*Replica).RangeFeed at line 219
pkg/kv/kvserver/pkg/kv/kvserver/replica_rangefeed.go in pkg/kv/kvserver.(*Replica).registerWithRangefeedRaftMuLocked at line 408
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
```

### Tags

| Tag | Value |
| --- | --- |
| Command | demo |
| Environment | v23.1.0 |
| Go Version | go1.19.4 |
| Platform | windows amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.0 |
| Cockroach SHA | 358e0d87912365b8976c55ab9b3292e999cf720d |
| # of CPUs | 12 |
| # of Goroutines | 936 |

Jira issue: CRDB-29508

**Comment by yuzefovich** [comment]
unsure what the error is, unactionable
