### ISSUE TITLE
sql: introduce a new predicate structure to replace usingPredicate

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#10630]
There needs to be a new join predicate structure to replace usingPredicate that describes a join using an equality relation between columns on the left and right. The new predicate, let's call this the  `equalityPredicate` extends `usingPredicate` by allowing the *names* of the join columns on the left and right to differ.

Once this predicate exists, the following needs to happen:
1. the constructor for USING must be changed to use `equalityPredicate`
2. after #10618 is merged, the hash join must be used for `equalityPredicate` as well.

for the purpose of EXPLAIN we can then describe the equalityPredicate using the following syntax: `ON EQUALS(left columns..., right columns...)`

**Comment by knz** [comment]
@irfansharif do you think you could take this one after you're done with #10618? I think it's going to be easy for you since all of this is still fresh in your mind.

**Comment by irfansharif** [comment]
@knz: I doubt I will be able to give time to this immediately but I'll be happy to take this on in the interim (i.e. while working on distsql planning). alternatively I noticed @a6802739 expressed interest, I'd be happy to look over the work there before passing it along for further review.

**Comment by knz** [comment]
Thanks! Let's see what songhao makes of this.

**Comment by a6802739** [comment]
@knz, if I use `ON EQUALS(left columns..., right columns...)` to print the `format`,  how could I format the print `left columns` or `right columns`, obviously we can't use `,` as the decollator of each element in `left columns`.

**Comment by knz** [comment]
Use spaces.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
