### ISSUE TITLE
sql: add repair query for rewriting primary indexes (with missing columns)

### ISSUE THREAD

**Issue by fqazi** [cockroachdb/cockroach#106336]
Previously, it was possible in Cockroach 22.2 to enter scenarios where columns for a primary index only existed within a secondary index after an add column operation. This was a bug that was introduced because we incorrectly interpreted PRIMARY INDEXES (see: https://github.com/cockroachdb/cockroach/issues/97526). While we can offer a manual repair query + UPDATE operations to fix tables, a builtin for this repair would be more effective and user-friendly (since this could require a bulk operation).

Jira issue: CRDB-29513

Epic CRDB-28665

**Comment by rafiss** [comment]
We have not seen a need to add this builtin, since although this type of corruption is possible, we have not yet seen any cases of it. We can reopen this later if needed.
