### ISSUE TITLE
sql: replace JOIN ... ON with equality operations to JOIN with an equalityPredicate

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#10631]
After  #10630 is addressed, queries of the form `a JOIN b ON a.x = b.y` must be replaced by `a JOIN b ON EQUALS(x, y)`

This must detect cases where the ON predicate, after normalization to disjunctive normal form, has a single conjunction and only contains equality test between left and right columns, and replace these cases only. Other cases can remain as `onPredicate`.

**Comment by a6802739** [comment]
@knz, I want to tackle this, colud I?

**Comment by knz** [comment]
You can but then you need to do #10630 first.

**Comment by a6802739** [comment]
@knz, okay, I will try it.

**Comment by a6802739** [comment]
@knz, A little confusion here.

`a JOIN b ON a.x = b.y` is standard SQL statement, why we should change it to `a JOIN b ON EQUALS(x, y)`?

**Comment by RaduBerinde** [comment]
@a6802739 I think what is meant here is that internally we should detect instances like `a.x = b.y` (inside `ON` clause, and also in `WHERE` clause if doing inner joins) and convert them to an `equalityPredicate`. 

`ON EQUALS` would show up when `EXPLAIN`ing the statement, similar to the test case you added in #10672.

Hope that makes sense.

**Comment by RaduBerinde** [comment]
Also note that ideally in cases like `ON a.x = b.y AND a.x + a.y = b.z` we should extract the `equalityPredicate` for `a.x = b.y` and leave `a.x + a.y = b.z` as an `onPredicate` but I'm not sure the join code support multiple predicates without extra work.

**Comment by a6802739** [comment]
@RaduBerinde, got it. Thanks a lot.

**Comment by knz** [comment]
So @RaduBerinde  let's not make this issue more complicated than it is. 
For now I am only targeting the use case in #10633 which is (as I gathered by discussion) the most common.

So to keep the issue focused and tractable I suggest the following:
- a ON predicate containing a single equality test between a column on the left and a column on the right is replaced entirely by ON EQUALS
- (optionally) an ON predicate containing an AND of *only* equalities between left and right is replaced entirely by ON EQUALS - and I say optional because the use case in #10633 and related issues does not need this!
- *everything else* (including mixes of balanced and non-balanced equality predicates, like suggested in https://github.com/cockroachdb/cockroach/issues/10631#issuecomment-260537971) is left alone untouched.

**Comment by a6802739** [comment]
@knz, So should I walk through `expr parser.Expr` and parse out `Equal expr` and `left colnames` and `right colnames`?

**Comment by knz** [comment]
no need to walk. the starting point should be simple like this:
```
if c, ok := expr.(*parser.ComparisonExpr); ok && c.Operator == parser.Eq { 
   left, ok := c.Left.(*parser.ColumnItem) // Perhaps you need IndexedVar here, not sure
   if !ok { return }
   right, ok := c.Right.(*parser.ColumnItem) // Perhaps IndexedVar here too
   if ! ok {  return }
   /* check here that left and right are for the same tables as the JOIN -- this is where the most complexity occurs */
  /* replace the using predicate */
}

**Comment by a6802739** [comment]
@knz, got it. thanks a lot.

**Comment by a6802739** [comment]
hey, @knz, a new problem here.

how could I deal with SQL statement like 
`SELECT * FROM twocolumn JOIN onecolumn AS a (b) ON a.b = twocolumn.x;`
because In `equalityPredicate`, it just could process `table alias`, how could I deal with `column alias`?

**Comment by knz** [comment]
After `analyzeExpr` the `filter` expression contains `IndexedVar` to
refer to columns. The column names then have disappeared.
The IndexedVar has an attribute `Idx`, which can refer either to the
left or right data sources of the join. How do you know which one? It
depends on the value: if `Idx` is between 0 and `len(left.Columns())`
then it references the left data source, if it is between
`len(left.Columns())` and `len(left.Columns())+len(right.Columns())`
then it references the right data source.

So if you find a `ComparisonExpr` with two `IndexedVar` operands, and
the `Idx` attributes refer to the left and the right data sources, then
you know that the comparison is appropriate for ON EQUALS.

**Comment by knz** [comment]
Also you can reuse the `Idx` values from the `IndexedVar` directly to construct the list of columns in the equalityPredicate.

**Comment by a6802739** [comment]
@knz, In this example
`SELECT * FROM twocolumn JOIN onecolumn AS a (b) ON a.b = twocolumn.x`

`a.b` and `twocolumn.x` will all turn to `IndexedVar ` after `analyzeExp`, right?

so for `a.b`, it should change to `a.x` in `makeEqualityPredicate`, right?

**Comment by knz** [comment]
To make this change, please ignore for now the problem of deciding appropriate names for `leftColNames` and `rightColNames`. This is a separate problem for which I am already working on a solution (#10729). 

For now concentrate on replacing ComparisonExpr{Eq, IndexedVar, IndexedVar}, and simply move the `Idx` attribute from the left and right `IndexedVar` into the arrays `leftUsingIndices` and `rightUsingIndices`.

If you get this to work, then your work on this issue is complete, even if `EXPLAIN` cannot print the resulting column names properly.

**Comment by a6802739** [comment]
@knz, thanks for you help.

**Comment by a6802739** [comment]
@knz, I met with a new problem now.
In the test case for `SELECT * FROM (onecolumn CROSS JOIN twocolumn JOIN onecolumn AS a(b) ON a.b=twocolumn.x JOIN twocolumn AS c(d,e) ON a.b=c.d AND c.d=onecolumn.x) LIMIT 1;`

it returns nothing.

```
+---+---+---+---+---+---+
| x | x | y | b | d | e |
+---+---+---+---+---+---+
+---+---+---+---+---+---+
```
if I excute `SELECT * FROM onecolumn CROSS JOIN twocolumn JOIN onecolumn AS a (b) ON a.b = twocolumn.x;`, the result is :
```
+------+--------------------+----+----+
|  x   |         x          | y  | b  |
+------+--------------------+----+----+
|   44 | 193999790389166081 | 51 | 44 |
|   44 | 193999790389166081 | 53 | 42 |
| NULL | 193999790389231617 | 51 | 44 |
| NULL | 193999790389231617 | 53 | 42 |
|   42 | 193999790389264385 | 51 | 44 |
|   42 | 193999790389264385 | 53 | 42 |
+------+--------------------+----+----+
```
the result for column `x` is not right.
when I debug this SQL, I found in `select.go`, in function `Next()`, I print the result for `s.source.plan.Values()`, and it's okay, it's just like below.
```
[44 193999790389166081 44 51 193999695668117505 44 193999790389166081]
```
then, I found in `select.go`, in function `renderRow`, I change `s.render` to `parser.IndexedVar`, I found the `Idx` is not right, it's just like below
```
0 1 3 5
```
So, it get wrong column from above row result.

I don't konw where did the `Idx` of `s.render` will be assign, and what is the relationship between this `Idx` with `sourceColumns`, `sourceAliases` in `makeEqualityPredicate`?

I wonder If I could send my work with a PR now, And ask you to point me out what should I do to deal with this problem.

sorry to bother you. And thanks for you kind explaination before again.

**Comment by knz** [comment]
I'll be looking at this tomorrow.
