### ISSUE TITLE
Support Range Quarantine

### ISSUE THREAD

**Issue by JeffSwenson** [cockroachdb/cockroach#106317]
There was a recent issue in a Serverless host cluster where one range had a corrupt end key and attempting to load the range caused all kv servers serving the range to crash loop (https://github.com/cockroachdb/cockroach/issues/104796). At the time, mitigating the issue required deploying a custom build that was capable of handling the key corruption. Ideally there would be a general tool that allows us to mitigate an issue impacting a single range without requiring a custom binary. 

One idea would be a way to "quarantine" a bad range. A quarantined range would be treated as unavailable and kv servers would avoid serving or querying the range. This is intended as an emergency mitigation tool that can be used to avoid issues caused by a range with corrupt state committed to the raftlog or pebble.

The ability to quarantine a range would be useful in Serverless clusters, since each range belongs to a single tenant, and it is okay to make a tenant completely unavailable if it protects the availability of all other tenants in the cluster.

Jira issue: CRDB-29502

**Comment by tbg** [comment]
Related issues:

https://github.com/cockroachdb/cockroach/issues/62199
https://github.com/cockroachdb/cockroach/issues/75944

**Comment by tbg** [comment]
Closing for https://github.com/cockroachdb/cockroach/issues/62199.
