### ISSUE TITLE
Sentry: errors.go:83: referenced descriptor ID 2015: descriptor not found
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/i...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#106425]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4300825585/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4300825585/?referrer=webhooks_plugin)

Panic Message:

```
errors.go:83: referenced descriptor ID 2015: descriptor not found
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.wrapError
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_query.go:128
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.catalogQuery.processDescriptorResultRow
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_query.go:111
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.catalogQuery.query
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_query.go:73
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.catalogReader.GetDescriptorEntries
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_reader.go:224
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.(*StoredCatalog).EnsureFromStorageByIDs
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/stored_catalog.go:308
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.getDescriptorsByID
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:191
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).getDescriptorByID
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:88
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).getDescriptorByName
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:336
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).getSchemaByName
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/schema.go:73
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).GetImmutableSchemaByName
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/schema.go:61
  | github.com/cockroachdb/cockroach/pkg/sql.(*schemaResolver).LookupSchema
  | 	github.com/cockroachdb/cockroach/pkg/sql/schema_resolver.go:132
  | github.com/cockroachdb/cockroach/pkg/sql.(*schemaResolver).ResolveFunction
  | 	github.com/cockroachdb/cockroach/pkg/sql/schema_resolver.go:416
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*ResolvableFunctionReference).Resolve
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/function_name.go:113
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*scope).VisitPre
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scope.go:1061
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.WalkExpr
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/walk.go:825
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*scope).walkExprTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scope.go:428
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*scope).resolveType
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scope.go:467
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).analyzeSelectList
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/project.go:160
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).analyzeProjectionList
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/project.go:94
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildSelectClause
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:1059
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildSelectStmtWithoutParens
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:996
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildSelect.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:965
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).processWiths
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/with.go:117
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildSelect
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:964
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:316
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmtAtRoot
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:256
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).Build
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:230
  | github.com/cockroachdb/cockroach/pkg/sql.(*optPlanningCtx).buildReusableMemo
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:418
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).prepareUsingOptimizer
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:156
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).populatePrepared
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:308
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).prepare.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:260
Wraps: (3) referenced descriptor ID 2015
Wraps: (4) secondary error attachment
  | failed to find descriptor [2015]
  | (1) attached stack trace
  |   -- stack trace:
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.requiredError
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_query.go:172
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.build
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_query.go:142
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.catalogQuery.processDescriptorResultRow
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_query.go:109
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.catalogQuery.query
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_query.go:73
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.catalogReader.GetDescriptorEntries
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_reader.go:224
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.(*StoredCatalog).EnsureFromStorageByIDs
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/stored_catalog.go:308
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.getDescriptorsByID
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:191
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).getDescriptorByID
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:88
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).getDescriptorByName
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:336
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).getSchemaByName
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/schema.go:73
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).GetImmutableSchemaByName
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/schema.go:61
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*schemaResolver).LookupSchema
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/schema_resolver.go:132
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*schemaResolver).ResolveFunction
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/schema_resolver.go:416
  |   | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*ResolvableFunctionReference).Resolve
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/function_name.go:113
  |   | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*scope).VisitPre
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scope.go:1061
  |   | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.WalkExpr
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/walk.go:825
  |   | github.com/cockroachdb/cockroach/pkg/sql/o...
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/conn_executor_prepare.go#L264-L266](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/conn_executor_prepare.go#L264-L266)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/conn_executor_prepare.go#L259-L261](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/conn_executor_prepare.go#L259-L261)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/conn_executor_prepare.go#L307-L309](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/conn_executor_prepare.go#L307-L309)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/plan_opt.go#L155-L157](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/plan_opt.go#L155-L157)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/plan_opt.go#L417-L419](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/plan_opt.go#L417-L419)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/opt/optbuilder/builder.go#L229-L231](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/opt/optbuilder/builder.go#L229-L231)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/opt/optbuilder/builder.go#L255-L257](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/opt/optbuilder/builder.go#L255-L257)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/opt/optbuilder/builder.go#L315-L317](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/opt/optbuilder/builder.go#L315-L317)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/opt/optbuilder/select.go#L963-L965](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/opt/optbuilder/select.go#L963-L965)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/opt/optbuilder/with.go#L116-L118](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/opt/optbuilder/with.go#L116-L118)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/opt/optbuilder/select.go#L964-L966](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/opt/optbuilder/select.go#L964-L966)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/opt/optbuilder/select.go#L995-L997](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/opt/optbuilder/select.go#L995-L997)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/opt/optbuilder/select.go#L1058-L1060](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/opt/optbuilder/select.go#L1058-L1060)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/opt/optbuilder/project.go#L93-L95](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/opt/optbuilder/project.go#L93-L95)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/opt/optbuilder/project.go#L159-L161](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/opt/optbuilder/project.go#L159-L161)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/opt/optbuilder/scope.go#L466-L468](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/opt/optbuilder/scope.go#L466-L468)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/opt/optbuilder/scope.go#L427-L429](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/opt/optbuilder/scope.go#L427-L429)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/sem/tree/walk.go#L824-L826](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/sem/tree/walk.go#L824-L826)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/opt/optbuilder/scope.go#L1060-L1062](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/opt/optbuilder/scope.go#L1060-L1062)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/sem/tree/function_name.go#L112-L114](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/sem/tree/function_name.go#L112-L114)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/schema_resolver.go#L415-L417](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/schema_resolver.go#L415-L417)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/schema_resolver.go#L131-L133](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/schema_resolver.go#L131-L133)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/catalog/descs/schema.go#L60-L62](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/catalog/descs/schema.go#L60-L62)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/catalog/descs/schema.go#L72-L74](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/catalog/descs/schema.go#L72-L74)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/catalog/descs/descriptor.go#L335-L337](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/catalog/descs/descriptor.go#L335-L337)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/catalog/descs/descriptor.go#L87-L89](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/catalog/descs/descriptor.go#L87-L89)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/catalog/descs/descriptor.go#L190-L192](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/catalog/descs/descriptor.go#L190-L192)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/catalog/internal/catkv/stored_catalog.go#L307-L309](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/catalog/internal/catkv/stored_catalog.go#L307-L309)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/catalog/internal/catkv/catalog_reader.go#L223-L225](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/catalog/internal/catkv/catalog_reader.go#L223-L225)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/catalog/internal/catkv/catalog_query.go#L72-L74](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/catalog/internal/catkv/catalog_query.go#L72-L74)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/catalog/internal/catkv/catalog_query.go#L110-L112](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/catalog/internal/catkv/catalog_query.go#L110-L112)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/catalog/internal/catkv/catalog_query.go#L127-L129](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/catalog/internal/catkv/catalog_query.go#L127-L129)
[src/runtime/asm_arm64.s#L1171-L1173](src/runtime/asm_arm64.s#L1171-L1173)
[GOROOT/src/runtime/proc.go#L232-L234](GOROOT/src/runtime/proc.go#L232-L234)
[GOROOT/src/runtime/proc.go#L6324-L6326](GOROOT/src/runtime/proc.go#L6324-L6326)
[GOROOT/src/runtime/proc.go#L6324-L6326](GOROOT/src/runtime/proc.go#L6324-L6326)
[GOROOT/src/runtime/proc.go#L6324-L6326](GOROOT/src/runtime/proc.go#L6324-L6326)
[GOROOT/src/runtime/proc.go#L6324-L6326](GOROOT/src/runtime/proc.go#L6324-L6326)
[GOROOT/src/runtime/proc.go#L6324-L6326](GOROOT/src/runtime/proc.go#L6324-L6326)
[GOROOT/src/runtime/proc.go#L6324-L6326](GOROOT/src/runtime/proc.go#L6324-L6326)
[GOROOT/src/runtime/proc.go#L6324-L6326](GOROOT/src/runtime/proc.go#L6324-L6326)
[GOROOT/src/runtime/proc.go#L6324-L6326](GOROOT/src/runtime/proc.go#L6324-L6326)
[GOROOT/src/runtime/proc.go#L6324-L6326](GOROOT/src/runtime/proc.go#L6324-L6326)
[GOROOT/src/runtime/proc.go#L6347-L6349](GOROOT/src/runtime/proc.go#L6347-L6349)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/catalog/errors.go#L82-L84](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/catalog/errors.go#L82-L84)
</details>

```
pkg/sql/conn_executor_prepare.go in pkg/sql.(*connExecutor).prepare at line 265
pkg/sql/conn_executor_prepare.go in pkg/sql.(*connExecutor).prepare.func2 at line 260
pkg/sql/conn_executor_prepare.go in pkg/sql.(*connExecutor).populatePrepared at line 308
pkg/sql/plan_opt.go in pkg/sql.(*planner).prepareUsingOptimizer at line 156
pkg/sql/plan_opt.go in pkg/sql.(*optPlanningCtx).buildReusableMemo at line 418
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).Build at line 230
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).buildStmtAtRoot at line 256
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).buildStmt at line 316
pkg/sql/opt/optbuilder/select.go in pkg/sql/opt/optbuilder.(*Builder).buildSelect at line 964
pkg/sql/opt/optbuilder/with.go in pkg/sql/opt/optbuilder.(*Builder).processWiths at line 117
pkg/sql/opt/optbuilder/select.go in pkg/sql/opt/optbuilder.(*Builder).buildSelect.func1 at line 965
pkg/sql/opt/optbuilder/select.go in pkg/sql/opt/optbuilder.(*Builder).buildSelectStmtWithoutParens at line 996
pkg/sql/opt/optbuilder/select.go in pkg/sql/opt/optbuilder.(*Builder).buildSelectClause at line 1059
pkg/sql/opt/optbuilder/project.go in pkg/sql/opt/optbuilder.(*Builder).analyzeProjectionList at line 94
pkg/sql/opt/optbuilder/project.go in pkg/sql/opt/optbuilder.(*Builder).analyzeSelectList at line 160
pkg/sql/opt/optbuilder/scope.go in pkg/sql/opt/optbuilder.(*scope).resolveType at line 467
pkg/sql/opt/optbuilder/scope.go in pkg/sql/opt/optbuilder.(*scope).walkExprTree at line 428
pkg/sql/sem/tree/walk.go in pkg/sql/sem/tree.WalkExpr at line 825
pkg/sql/opt/optbuilder/scope.go in pkg/sql/opt/optbuilder.(*scope).VisitPre at line 1061
pkg/sql/sem/tree/function_name.go in pkg/sql/sem/tree.(*ResolvableFunctionReference).Resolve at line 113
pkg/sql/schema_resolver.go in pkg/sql.(*schemaResolver).ResolveFunction at line 416
pkg/sql/schema_resolver.go in pkg/sql.(*schemaResolver).LookupSchema at line 132
pkg/sql/catalog/descs/schema.go in pkg/sql/catalog/descs.(*Collection).GetImmutableSchemaByName at line 61
pkg/sql/catalog/descs/schema.go in pkg/sql/catalog/descs.(*Collection).getSchemaByName at line 73
pkg/sql/catalog/descs/descriptor.go in pkg/sql/catalog/descs.(*Collection).getDescriptorByName at line 336
pkg/sql/catalog/descs/descriptor.go in pkg/sql/catalog/descs.(*Collection).getDescriptorByID at line 88
pkg/sql/catalog/descs/descriptor.go in pkg/sql/catalog/descs.getDescriptorsByID at line 191
pkg/sql/catalog/internal/catkv/stored_catalog.go in pkg/sql/catalog/internal/catkv.(*StoredCatalog).EnsureFromStorageByIDs at line 308
pkg/sql/catalog/internal/catkv/catalog_reader.go in pkg/sql/catalog/internal/catkv.catalogReader.GetDescriptorEntries at line 224
pkg/sql/catalog/internal/catkv/catalog_query.go in pkg/sql/catalog/internal/catkv.catalogQuery.query at line 73
pkg/sql/catalog/internal/catkv/catalog_query.go in pkg/sql/catalog/internal/catkv.catalogQuery.processDescriptorResultRow at line 111
pkg/sql/catalog/internal/catkv/catalog_query.go in pkg/sql/catalog/internal/catkv.wrapError at line 128
src/runtime/asm_arm64.s in runtime.goexit at line 1172
GOROOT/src/runtime/proc.go in runtime.main at line 233
GOROOT/src/runtime/proc.go in runtime.doInit at line 6325
GOROOT/src/runtime/proc.go in runtime.doInit at line 6325
GOROOT/src/runtime/proc.go in runtime.doInit at line 6325
GOROOT/src/runtime/proc.go in runtime.doInit at line 6325
GOROOT/src/runtime/proc.go in runtime.doInit at line 6325
GOROOT/src/runtime/proc.go in runtime.doInit at line 6325
GOROOT/src/runtime/proc.go in runtime.doInit at line 6325
GOROOT/src/runtime/proc.go in runtime.doInit at line 6325
GOROOT/src/runtime/proc.go in runtime.doInit at line 6325
GOROOT/src/runtime/proc.go in runtime.doInit at line 6348
pkg/sql/catalog/errors.go in pkg/sql/catalog.init at line 83
```

### Tags

| Tag | Value |
| --- | --- |
| Command | start-single-node |
| Environment | v22.2.9 |
| Go Version | go1.19.6 |
| Platform | darwin arm64 |
| Distribution | CCL |
| Cockroach Release | v22.2.9 |
| Cockroach SHA | 1b11ca676513ae073ea696c7cc3123d2684bc4bd |
| # of CPUs | 10 |
| # of Goroutines | 2426 |

Jira issue: CRDB-29562

**Comment by msirek** [comment]
dup of #106388
