### ISSUE TITLE
cmd/zerosum: 0 QPS after node restart

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#10643]
```
~ zerosum -m 3 -n 4 -c simple
...
chaos: killing node 1 for 20s
...
chaos: starting node 1
...
used
     36s     35580       25533    134.5       32       41       43       48          25 41 37 41
     37s     35580       25533      0.0       32       42       45       -1              0 0 0 0
     38s     35580       25533      0.0       32       45       46       49          25 42 38 42
     39s     35580       25533      0.0       32       45       48       -1              0 0 0 0
     40s     35580       25533      0.0       32       48       50       52          25 45 41 45
_elapsed__accounts_________ops__ops/sec___errors___splits____xfers___ranges_____________replicas
     41s     35580       25533      0.0       32       49       51       55          26 47 44 48
     42s     35580       25533      0.0       32       51       52       -1              0 0 0 0
     43s     35580       25533      0.0       32       52       52       58          27 50 46 51
     44s     35580       25533      0.0       32       55       55       59          31 50 44 52
     45s     35580       25533      0.0       32       59       57       62          34 53 46 53
     46s     35580       25533      0.0       32       59       59       66          36 53 52 57
     47s     36146       26113    579.0       32       60       60       67          37 54 53 57
```

This didn't happen a few months ago. I've tried disabling both quiescence and coalesced heartbeats, but the problem still occurs. The restarted node isn't able to make progress because remote nodes are not talking to it. One problem causing this was #10642, but the above run was taken with that PR. Now it looks like remote nodes are periodically trying to send requests after the node restarts, but the requests are failing with `grpc: the connection is unavailable`. As far as I can tell, the connection is ok. I haven't tracked down yet why grpc is returning that error.

Cc @tamird

**Comment by tamird** [comment]
Are you bisecting?

**Comment by petermattis** [comment]
> Are you bisecting?

I haven't tried yet. Guess I should.

**Comment by petermattis** [comment]
With 2504845195388d0e5405f061a149e76bfcfb9302 (Aug 2), there is either no hiccup on restart or a small 2-3 sec one.

**Comment by petermattis** [comment]
The longer hiccup was introduced by f74137a33251e1a42b3becd1c2cc73b8335dd007. Perhaps grpc internally has some sort of backoff for retrying on a connection.

**Comment by petermattis** [comment]
> Perhaps grpc internally has some sort of backoff for retrying on a connection.

That looks to be exactly what is going on. Connection retries are performed with an exponential backoff that has the following default settings:

```
	DefaultBackoffConfig = BackoffConfig{
		MaxDelay:  120 * time.Second,
		baseDelay: 1.0 * time.Second,
		factor:    1.6,
		jitter:    0.2,
	}
```

Instrumenting the grpc code I see lines like:

```
I161111 21:13:01.566321 33 /Users/pmattis/Development/go/src/google.golang.org/grpc/clientconn.go:655  grpc: connecting(6): 19.890601s
```

This indicates this is the 6th retry and that grpc will sleep 19.9s after the connection failure before performing another retry. I'm going to try adjust the backoff settings to see if it eliminates the problem I'm seeing. Note that the max-backoff is 2min. Seems like we could easily hit that when a node is taken down for a significant period of time and then we'd get a strange situation where a node comes back and can send RPCs to other nodes but other nodes can't send RPCs to it.
