### ISSUE TITLE
kvserver: add test to verify tryReproposeWithNewLeaseIndex behaviour

### ISSUE THREAD

**Issue by aliher1911** [cockroachdb/cockroach#106504]
This PR https://github.com/cockroachdb/cockroach/pull/106502 removes a flaky integration test that verified reproposals with new lease index doesn't break pipelined writes (errors of this type are correctly handled below request evaluation).
Removed integration test was too high level to pinpoint this use case and precisely filter all other associated failure modes.
Test was originally introduced in https://github.com/cockroachdb/cockroach/pull/35261 and PR has context on what test verifies and motivation for it.

This reproposal functionality is not covered by any tests as of now.

Jira issue: CRDB-29593

**Comment by erikgrinaker** [comment]
Conservatively marking as blocker, to improve reproposal confidence before the release.

**Comment by erikgrinaker** [comment]
We won't have time to get to this, dropping GA-blocker.

**Comment by pavelkalinnikov** [comment]
#113658 essentially fixes this.
