### ISSUE TITLE
add cypress tests to TeamCity

### ISSUE THREAD

**Issue by maryliag** [cockroachdb/cockroach#106584]
We have cypress on CRDB but they're not automatically run anywhere. We should have it on TeamCity or at least on a nightly test.

CC already have that running nightly so it can be used as an example, but that one points to existing clusters on staging, which we don't want to do for this case because we want to test the UI for DB Console.

Jira issue: CRDB-29632

Epic CRDB-42448

**Comment by dhartunian** [comment]
I am working to get the `run_cypress` bazel rule working (50% of the way there) so ideally this will require no additional work from testeng.
