### ISSUE TITLE
ui: TC check reports spurious changes in embedded.go

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#10650]
https://teamcity.cockroachdb.com/viewLog.html?buildId=46385&tab=buildResultsDiv&buildTypeId=Cockroach_UnitTests_Check

An error is reported telling me that `embedded.go` has changed although I made no changes there.

**Comment by tamird** [comment]
Gah, I think this is my fault due to updates to
https://github.com/github/fetch/pull/351

**Comment by tamird** [comment]
Anyway, a rebase should fix it.

**Comment by tamird** [comment]
https://github.com/cockroachdb/cockroach/commit/137f8809da335e9a3c57357d58ed90b40b4b7459
