### ISSUE TITLE
Sentry: func_resolver.go:61: function × does not exist
(1)
Wraps: (2)
Wraps: (3) assertion failure
Wraps: (4) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/ccl/chang...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#106592]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4308048482/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4308048482/?referrer=webhooks_plugin)

Panic Message:

```
func_resolver.go:61: function × does not exist
(1)
Wraps: (2)
Wraps: (3) assertion failure
Wraps: (4) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/cdceval.(*CDCFunctionResolver).ResolveFunction
  | 	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/cdceval/func_resolver.go:61
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*ResolvableFunctionReference).Resolve
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/function_name.go:113
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*scope).VisitPre
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scope.go:1061
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.WalkExpr
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/walk.go:825
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*ComparisonExpr).Walk
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/walk.go:191
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.WalkExpr
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/walk.go:828
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*NotExpr).Walk
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/walk.go:430
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.WalkExpr
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/walk.go:828
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*scope).walkExprTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scope.go:428
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*scope).resolveType
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scope.go:467
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*ScalarBuilder).Build
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scalar.go:1035
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).ConstrainPrimaryIndexSpanByExpr
  | 	github.com/cockroachdb/cockroach/pkg/sql/constraint.go:90
  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/cdceval.constrainSpansBySelectClause
  | 	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/cdceval/constraint.go:98
  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/cdceval.NormalizeAndValidateSelectForTarget
  | 	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/cdceval/validation.go:112
  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.validateAndNormalizeChangefeedExpression
  | 	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_stmt.go:914
  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.createChangefeedJobRecord
  | 	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_stmt.go:427
  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.changefeedPlanHook.func1
  | 	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_stmt.go:187
  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.changefeedPlanHook.func2
  | 	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_stmt.go:314
  | github.com/cockroachdb/cockroach/pkg/sql.(*hookFnNode).startExec.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/planhook.go:199
  | runtime.goexit
  | 	src/runtime/asm_amd64.s:1594
Wraps: (5) function × does not exist
Error types: (1) *colexecerror.notInternalError (2) *changefeedbase.taggedError (3) *assert.withAssertionFailure (4) *withstack.withStack (5) *errutil.leafError
-- report composition:
*errutil.leafError: function × does not exist
func_resolver.go:61: *withstack.withStack (top exception)
*assert.withAssertionFailure
*changefeedbase.taggedError
*colexecerror.notInternalError
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_amd64.s#L1593-L1595](src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/planhook.go#L198-L200](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/planhook.go#L198-L200)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/ccl/changefeedccl/changefeed_stmt.go#L313-L315](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/ccl/changefeedccl/changefeed_stmt.go#L313-L315)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/ccl/changefeedccl/changefeed_stmt.go#L186-L188](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/ccl/changefeedccl/changefeed_stmt.go#L186-L188)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/ccl/changefeedccl/changefeed_stmt.go#L426-L428](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/ccl/changefeedccl/changefeed_stmt.go#L426-L428)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/ccl/changefeedccl/changefeed_stmt.go#L913-L915](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/ccl/changefeedccl/changefeed_stmt.go#L913-L915)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/ccl/changefeedccl/cdceval/validation.go#L111-L113](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/ccl/changefeedccl/cdceval/validation.go#L111-L113)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/ccl/changefeedccl/cdceval/constraint.go#L97-L99](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/ccl/changefeedccl/cdceval/constraint.go#L97-L99)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/constraint.go#L89-L91](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/constraint.go#L89-L91)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/opt/optbuilder/scalar.go#L1034-L1036](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/opt/optbuilder/scalar.go#L1034-L1036)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/opt/optbuilder/scope.go#L466-L468](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/opt/optbuilder/scope.go#L466-L468)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/opt/optbuilder/scope.go#L427-L429](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/opt/optbuilder/scope.go#L427-L429)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/sem/tree/walk.go#L827-L829](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/sem/tree/walk.go#L827-L829)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/sem/tree/walk.go#L429-L431](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/sem/tree/walk.go#L429-L431)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/sem/tree/walk.go#L827-L829](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/sem/tree/walk.go#L827-L829)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/sem/tree/walk.go#L190-L192](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/sem/tree/walk.go#L190-L192)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/sem/tree/walk.go#L824-L826](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/sem/tree/walk.go#L824-L826)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/opt/optbuilder/scope.go#L1060-L1062](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/opt/optbuilder/scope.go#L1060-L1062)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/sem/tree/function_name.go#L112-L114](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/sem/tree/function_name.go#L112-L114)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/ccl/changefeedccl/cdceval/func_resolver.go#L60-L62](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/ccl/changefeedccl/cdceval/func_resolver.go#L60-L62)
</details>

```
src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/sql/planhook.go in pkg/sql.(*hookFnNode).startExec.func1 at line 199
pkg/ccl/changefeedccl/changefeed_stmt.go in pkg/ccl/changefeedccl.changefeedPlanHook.func2 at line 314
pkg/ccl/changefeedccl/changefeed_stmt.go in pkg/ccl/changefeedccl.changefeedPlanHook.func1 at line 187
pkg/ccl/changefeedccl/changefeed_stmt.go in pkg/ccl/changefeedccl.createChangefeedJobRecord at line 427
pkg/ccl/changefeedccl/changefeed_stmt.go in pkg/ccl/changefeedccl.validateAndNormalizeChangefeedExpression at line 914
pkg/ccl/changefeedccl/cdceval/validation.go in pkg/ccl/changefeedccl/cdceval.NormalizeAndValidateSelectForTarget at line 112
pkg/ccl/changefeedccl/cdceval/constraint.go in pkg/ccl/changefeedccl/cdceval.constrainSpansBySelectClause at line 98
pkg/sql/constraint.go in pkg/sql.(*planner).ConstrainPrimaryIndexSpanByExpr at line 90
pkg/sql/opt/optbuilder/scalar.go in pkg/sql/opt/optbuilder.(*ScalarBuilder).Build at line 1035
pkg/sql/opt/optbuilder/scope.go in pkg/sql/opt/optbuilder.(*scope).resolveType at line 467
pkg/sql/opt/optbuilder/scope.go in pkg/sql/opt/optbuilder.(*scope).walkExprTree at line 428
pkg/sql/sem/tree/walk.go in pkg/sql/sem/tree.WalkExpr at line 828
pkg/sql/sem/tree/walk.go in pkg/sql/sem/tree.(*NotExpr).Walk at line 430
pkg/sql/sem/tree/walk.go in pkg/sql/sem/tree.WalkExpr at line 828
pkg/sql/sem/tree/walk.go in pkg/sql/sem/tree.(*ComparisonExpr).Walk at line 191
pkg/sql/sem/tree/walk.go in pkg/sql/sem/tree.WalkExpr at line 825
pkg/sql/opt/optbuilder/scope.go in pkg/sql/opt/optbuilder.(*scope).VisitPre at line 1061
pkg/sql/sem/tree/function_name.go in pkg/sql/sem/tree.(*ResolvableFunctionReference).Resolve at line 113
pkg/ccl/changefeedccl/cdceval/func_resolver.go in pkg/ccl/changefeedccl/cdceval.(*CDCFunctionResolver).ResolveFunction at line 61
```

### Tags

| Tag | Value |
| --- | --- |
| Command | start-single-node |
| Environment | v22.2.9 |
| Go Version | go1.19.6 |
| Platform | darwin amd64 |
| Distribution | CCL |
| Cockroach Release | v22.2.9 |
| Cockroach SHA | 1b11ca676513ae073ea696c7cc3123d2684bc4bd |
| # of CPUs | 16 |
| # of Goroutines | 551 |

Jira issue: CRDB-29636

**Comment by yuzefovich** [comment]
unactionable
