### ISSUE TITLE
kvserver: latch latency metric

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#106500]
**Is your feature request related to a problem? Please describe.**

We could add a metric that measures latch latencies.

See https://github.com/cockroachdb/cockroach/pull/105045

**Describe the solution you'd like**

See https://github.com/cockroachdb/cockroach/pull/105045#pullrequestreview-1498649040

**Describe alternatives you've considered**

The metric may not be as useful as is expected to mainly be dominated by replication latencies (which we have[^1]). In cases where a read hotspot overwhelms disks, evaluation latencies (which we also have) should be good enough to register something.

So I'm not sure if we need this metric, but it's sometimes hard to tell ahead of time.

[^1]: https://github.com/cockroachdb/cockroach/pull/106094

**Additional context**

Abandoned the PR above due to competing priorities (and since it wasn't measuring the right thing).

Jira issue: CRDB-29592

**Comment by nvanbenschoten** [comment]
Agreed on the usefulness of this. We're also tracking in https://github.com/cockroachdb/cockroach/issues/104682, so I'll consolidate there.
