### ISSUE TITLE
Sentry: cmd_recover_txn.go:132: programming error: timestamp change by implicitly committed transaction: 1689016881.919482399,2->1689016873.001130312,0
(1) attached stack trace
  -- stack trace:
  | g...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#106543]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4306141890/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4306141890/?referrer=webhooks_plugin)

Panic Message:

```
cmd_recover_txn.go:132: programming error: timestamp change by implicitly committed transaction: 1689016881.919482399,2->1689016873.001130312,0
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/colflow/colrpc.(*Inbox).Next.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/colrpc/inbox.go:342
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.ExpectedError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:203
  | github.com/cockroachdb/cockroach/pkg/sql/colflow/colrpc.(*Inbox).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/colrpc/inbox.go:401
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:116
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:124
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*ParallelUnorderedSynchronizer).Init.func1.1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/parallel_unordered_synchronizer.go:191
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*ParallelUnorderedSynchronizer).init.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/parallel_unordered_synchronizer.go:255
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (2)
Wraps: (3) tags: [n28,client=136.34.222.20:58330,user=×,f×,distsql.stmt=×,distsql.gateway=×,distsql.appname=×,distsql.txn=×,streamID=×,received-error]
Wraps: (4) tags: [n×,f×,distsql.stmt=×,distsql.gateway=×,distsql.appname=×,distsql.txn=×,streamID=×,sent-error=×]
Wraps: (5)
Wraps: (6)
Wraps: (7)
Wraps: (8)
  | (opaque error wrapper)
  | type name: github.com/cockroachdb/cockroach/pkg/sql/colexecerror/*colexecerror.StorageError
Wraps: (9) assertion failure
Wraps: (10)
  | (opaque error wrapper)
  | type name: github.com/cockroachdb/errors/withstack/*withstack.withStack
  | reportable 0:
  |
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/batcheval.RecoverTxn
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/batcheval/cmd_recover_txn.go:132
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.evaluateCommand
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_evaluate.go:520
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.evaluateBatch
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_evaluate.go:287
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).evaluateWriteBatchWrapper
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go:668
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).evaluateWriteBatchWithServersideRefreshes
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go:628
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).evaluateWriteBatch
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go:438
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).evaluateProposal
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go:727
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).requestToProposal
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go:815
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).evalAndPropose
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:119
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).executeWriteBatch
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go:174
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).executeBatchWithConcurrencyRetries
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go:487
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).SendWithWriteBytes
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go:180
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).SendWithWriteBytes
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_send.go:205
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Stores).SendWithWriteBytes
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/stores.go:203
  | github.com/cockroachdb/cockroach/pkg/server.(*Node).batchInternal
  | 	github.com/cockroachdb/cockroach/pkg/server/node.go:1108
  | github.com/cockroachdb/cockroach/pkg/server.(*Node).Batch
  | 	github.com/cockroachdb/cockroach/pkg/server/node.go:1161
  | github.com/cockroachdb/cockroach/pkg/rpc.makeInternalClientAdapter.func1
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:724
  | github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor.ServerInterceptor.func1
  | 	github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go:96
  | github.com/cockroachdb/cockroach/pkg/rpc.bindUnaryServerInterceptorToHandler.func1
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:795
  | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func3
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:263
  | github.com/cockroachdb/cockroach/pkg/rpc.bindUnaryServerInterceptorToHandler.func1
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:795
  | github.com/cockroachdb/cockroach/pkg/rpc.kvAuth.unaryInterceptor
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/auth.go:73
  | github.com/cockroachdb/cockroach/pkg/rpc.bindUnaryServerInterceptorToHandler.func1
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:795
  | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func1.1
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:232
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:341
  | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func1
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:230
  | github.com/cockroachdb/cockroach/pkg/rpc.bindUnaryServerInterceptorToHandler.func1
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:795
  | github.com/cockroachdb/cockroach/pkg/rpc.makeInternalClientAdapter.func2
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:734
  | github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor.ClientInterceptor.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go:226
  | github.com/cockroachdb/cockroach/pkg/rpc.getChainUnaryInvoker.func1
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:879
  | github.com/cockroachdb/cockroach/pkg/rpc.makeInternalClientAdapter.func3
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:764
  | github.com/cockroachdb/cockroach/pkg/rpc.internalClientAdapter.Batch
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:887
Wraps: (11) programming error: timestamp change by implicitly committed transaction: 1689016881.919482399,2->1689016873.001130312,0
Error types: (1) *withstack.withStack (2) *colexecerror.notInternalError (3) *contexttags.withContext (4) *contexttags.withContext (5) *colexecerror.notInternalError (6) *colexecerror.notInternalError (7) *colexecerror.notInternalError (8) *errbase.opaqueWrapper (9) *assert.withAssertionFailure (10) *errbase.opaqueWrapper (11) *errutil.leafError
-- report composition:
*errutil.leafError: programming error: timestamp change by implicitly committed transaction: 1689016881.919482399,2->1689016873.001130312,0
cmd_recover_txn.go:132: *withstack.withStack (top exception)
*assert.withAssertionFailure
*colexecerror.StorageError...
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/sql/colexec/parallel_unordered_synchronizer.go#L254-L256](https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/sql/colexec/parallel_unordered_synchronizer.go#L254-L256)
[https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/sql/colexec/parallel_unordered_synchronizer.go#L190-L192](https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/sql/colexec/parallel_unordered_synchronizer.go#L190-L192)
[https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/sql/colflow/stats.go#L123-L125](https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/sql/colflow/stats.go#L123-L125)
[https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/sql/colflow/stats.go#L115-L117](https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/sql/colflow/stats.go#L115-L117)
[https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/sql/colflow/colrpc/inbox.go#L400-L402](https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/sql/colflow/colrpc/inbox.go#L400-L402)
[https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/sql/colexecerror/error.go#L202-L204](https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/sql/colexecerror/error.go#L202-L204)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
[https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/sql/colflow/colrpc/inbox.go#L341-L343](https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/sql/colflow/colrpc/inbox.go#L341-L343)
[https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/rpc/pkg/rpc/context.go#L886-L888](https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/rpc/pkg/rpc/context.go#L886-L888)
[https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/rpc/pkg/rpc/context.go#L763-L765](https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/rpc/pkg/rpc/context.go#L763-L765)
[https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/rpc/pkg/rpc/context.go#L878-L880](https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/rpc/pkg/rpc/context.go#L878-L880)
[https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go#L225-L227](https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go#L225-L227)
[https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/rpc/pkg/rpc/context.go#L733-L735](https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/rpc/pkg/rpc/context.go#L733-L735)
[https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/rpc/pkg/rpc/context.go#L794-L796](https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/rpc/pkg/rpc/context.go#L794-L796)
[https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/rpc/pkg/rpc/context.go#L229-L231](https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/rpc/pkg/rpc/context.go#L229-L231)
[https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/util/stop/stopper.go#L340-L342](https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/util/stop/stopper.go#L340-L342)
[https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/rpc/pkg/rpc/context.go#L231-L233](https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/rpc/pkg/rpc/context.go#L231-L233)
[https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/rpc/pkg/rpc/context.go#L794-L796](https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/rpc/pkg/rpc/context.go#L794-L796)
[https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/rpc/pkg/rpc/auth.go#L72-L74](https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/rpc/pkg/rpc/auth.go#L72-L74)
[https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/rpc/pkg/rpc/context.go#L794-L796](https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/rpc/pkg/rpc/context.go#L794-L796)
[https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/rpc/pkg/rpc/context.go#L262-L264](https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/rpc/pkg/rpc/context.go#L262-L264)
[https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/rpc/pkg/rpc/context.go#L794-L796](https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/rpc/pkg/rpc/context.go#L794-L796)
[https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go#L95-L97](https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go#L95-L97)
[https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/rpc/pkg/rpc/context.go#L723-L725](https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/rpc/pkg/rpc/context.go#L723-L725)
[https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/server/node.go#L1160-L1162](https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/server/node.go#L1160-L1162)
[https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/server/node.go#L1107-L1109](https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/server/node.go#L1107-L1109)
[https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/kv/kvserver/pkg/kv/kvserver/stores.go#L202-L204](https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/kv/kvserver/pkg/kv/kvserver/stores.go#L202-L204)
[https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/kv/kvserver/pkg/kv/kvserver/store_send.go#L204-L206](https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/kv/kvserver/pkg/kv/kvserver/store_send.go#L204-L206)
[https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go#L179-L181](https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go#L179-L181)
[https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go#L486-L488](https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go#L486-L488)
[https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go#L173-L175](https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go#L173-L175)
[https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L118-L120](https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L118-L120)
[https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go#L814-L816](https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go#L814-L816)
[https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go#L726-L728](https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go#L726-L728)
[https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go#L437-L439](https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go#L437-L439)
[https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go#L627-L629](https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go#L627-L629)
[https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go#L667-L669](https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go#L667-L669)
[https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/kv/kvserver/pkg/kv/kvserver/replica_evaluate.go#L286-L288](https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/kv/kvserver/pkg/kv/kvserver/replica_evaluate.go#L286-L288)
[https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/kv/kvserver/pkg/kv/kvserver/replica_evaluate.go#L519-L521](https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/kv/kvserver/pkg/kv/kvserver/replica_evaluate.go#L519-L521)
[https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/kv/kvserver/batcheval/cmd_recover_txn.go#L131-L133](https://github.com/cockroachdb/cockroach/blob/15505faf5a63b374b40b2d8b02e035e5f2e31180/pkg/kv/kvserver/batcheval/cmd_recover_txn.go#L131-L133)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/sql/colexec/parallel_unordered_synchronizer.go in pkg/sql/colexec.(*ParallelUnorderedSynchronizer).init.func1 at line 255
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colexec/parallel_unordered_synchronizer.go in pkg/sql/colexec.(*ParallelUnorderedSynchronizer).Init.func1.1 at line 191
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).Next at line 124
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).next at line 116
pkg/sql/colflow/colrpc/inbox.go in pkg/sql/colflow/colrpc.(*Inbox).Next at line 401
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.ExpectedError at line 203
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
pkg/sql/colflow/colrpc/inbox.go in pkg/sql/colflow/colrpc.(*Inbox).Next.func1 at line 342
pkg/rpc/pkg/rpc/context.go in pkg/rpc.internalClientAdapter.Batch at line 887
pkg/rpc/pkg/rpc/context.go in pkg/rpc.makeInternalClientAdapter.func3 at line 764
pkg/rpc/pkg/rpc/context.go in pkg/rpc.getChainUnaryInvoker.func1 at line 879
pkg/util/tracing/grpcinterceptor/grpc_interceptor.go in pkg/util/tracing/grpcinterceptor.ClientInterceptor.func2 at line 226
pkg/rpc/pkg/rpc/context.go in pkg/rpc.makeInternalClientAdapter.func2 at line 734
pkg/rpc/pkg/rpc/context.go in pkg/rpc.bindUnaryServerInterceptorToHandler.func1 at line 795
pkg/rpc/pkg/rpc/context.go in pkg/rpc.NewServerEx.func1 at line 230
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunTaskWithErr at line 341
pkg/rpc/pkg/rpc/context.go in pkg/rpc.NewServerEx.func1.1 at line 232
pkg/rpc/pkg/rpc/context.go in pkg/rpc.bindUnaryServerInterceptorToHandler.func1 at line 795
pkg/rpc/pkg/rpc/auth.go in pkg/rpc.kvAuth.unaryInterceptor at line 73
pkg/rpc/pkg/rpc/context.go in pkg/rpc.bindUnaryServerInterceptorToHandler.func1 at line 795
pkg/rpc/pkg/rpc/context.go in pkg/rpc.NewServerEx.func3 at line 263
pkg/rpc/pkg/rpc/context.go in pkg/rpc.bindUnaryServerInterceptorToHandler.func1 at line 795
pkg/util/tracing/grpcinterceptor/grpc_interceptor.go in pkg/util/tracing/grpcinterceptor.ServerInterceptor.func1 at line 96
pkg/rpc/pkg/rpc/context.go in pkg/rpc.makeInternalClientAdapter.func1 at line 724
pkg/server/node.go in pkg/server.(*Node).Batch at line 1161
pkg/server/node.go in pkg/server.(*Node).batchInternal at line 1108
pkg/kv/kvserver/pkg/kv/kvserver/stores.go in pkg/kv/kvserver.(*Stores).SendWithWriteBytes at line 203
pkg/kv/kvserver/pkg/kv/kvserver/store_send.go in pkg/kv/kvserver.(*Store).SendWithWriteBytes at line 205
pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go in pkg/kv/kvserver.(*Replica).SendWithWriteBytes at line 180
pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go in pkg/kv/kvserver.(*Replica).executeBatchWithConcurrencyRetries at line 487
pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go in pkg/kv/kvserver.(*Replica).executeWriteBatch at line 174
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).evalAndPropose at line 119
pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go in pkg/kv/kvserver.(*Replica).requestToProposal at line 815
pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go in pkg/kv/kvserver.(*Replica).evaluateProposal at line 727
pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go in pkg/kv/kvserver.(*Replica).evaluateWriteBatch at line 438
pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go in pkg/kv/kvserver.(*Replica).evaluateWriteBatchWithServersideRefreshes at line 628
pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go in pkg/kv/kvserver.(*Replica).evaluateWriteBatchWrapper at line 668
pkg/kv/kvserver/pkg/kv/kvserver/replica_evaluate.go in pkg/kv/kvserver.evaluateBatch at line 287
pkg/kv/kvserver/pkg/kv/kvserver/replica_evaluate.go in pkg/kv/kvserver.evaluateCommand at line 520
pkg/kv/kvserver/batcheval/cmd_recover_txn.go in pkg/kv/kvserver/batcheval.RecoverTxn at line 132
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v22.2.11 |
| Go Version | go1.19.6 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v22.2.11 |
| Cockroach SHA | 15505faf5a63b374b40b2d8b02e035e5f2e31180 |
| # of CPUs | 32 |
| # of Goroutines | 6440 |

Jira issue: CRDB-29610

**Comment by yuzefovich** [comment]
dup of #105332
