### ISSUE TITLE
Sentry: default_exprs.go:92: failed to type check the cast of × to ×: ×(): cannot determine type of empty array. Consider casting to the desired type, for example ARRAY[]::int[]
(1)
Wraps: (2) asse...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#106577]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4307347592/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4307347592/?referrer=webhooks_plugin)

Panic Message:

```
default_exprs.go:92: failed to type check the cast of × to ×: ×(): cannot determine type of empty array. Consider casting to the desired type, for example ARRAY[]::int[]
(1)
Wraps: (2) assertion failure
Wraps: (3) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/schemaexpr.MakeDefaultExprs
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/schemaexpr/default_exprs.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/backfill.(*ColumnBackfiller).InitForLocalUse
  | 	github.com/cockroachdb/cockroach/pkg/sql/backfill/backfill.go:191
  | github.com/cockroachdb/cockroach/pkg/sql.columnBackfillInTxn
  | 	github.com/cockroachdb/cockroach/pkg/sql/backfill.go:2866
  | github.com/cockroachdb/cockroach/pkg/sql.runSchemaChangesInTxn
  | 	github.com/cockroachdb/cockroach/pkg/sql/backfill.go:2488
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).writeTableDescToBatch
  | 	github.com/cockroachdb/cockroach/pkg/sql/table.go:299
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).writeTableDesc
  | 	github.com/cockroachdb/cockroach/pkg/sql/table.go:285
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).writeSchemaChange
  | 	github.com/cockroachdb/cockroach/pkg/sql/table.go:255
  | github.com/cockroachdb/cockroach/pkg/sql.(*alterTableNode).startExec
  | 	github.com/cockroachdb/cockroach/pkg/sql/alter_table.go:852
  | github.com/cockroachdb/cockroach/pkg/sql.startExec.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan.go:519
  | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:112
  | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:299
  | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:79
  | github.com/cockroachdb/cockroach/pkg/sql.walkPlan
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:43
  | github.com/cockroachdb/cockroach/pkg/sql.startExec
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan.go:522
  | github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Start
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:174
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Columnarizer).Init
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/columnarizer.go:183
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).init
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:94
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).Init
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:103
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).init.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:245
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).init
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:244
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:278
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:325
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:902
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1913
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll.func3
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1645
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1648
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2103
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1656
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:964
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:142
Wraps: (4) failed to type check the cast of × to ×
Wraps: (5) ×(): cannot determine type of empty array. Consider casting to the desired type, for example ARRAY[]::int[]
  | -- cause hidden behind barrier
  | ×(): cannot determine type of empty array. Consider casting to the desired type, for example ARRAY[]::int[]
  | (1) candidate pg code: 22023
  | Wraps: (2) attached stack trace
  |   -- stack trace:
  |   | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FuncExpr).TypeCheck
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/type_check.go:1082
  |   | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.TypeCheck
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/type_check.go:273
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/schemaexpr.MakeDefaultExprs
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/schemaexpr/default_exprs.go:82
  |   | github.com/cockroachdb/cockroach/pkg/sql/backfill.(*ColumnBackfiller).InitForLocalUse
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/backfill/backfill.go:191
  |   | github.com/cockroachdb/cockroach/pkg/sql.columnBackfillInTxn
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/backfill.go:2866
  |   | github.com/cockroachdb/cockroach/pkg/sql.runSchemaChangesInTxn
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/backfill.go:2488
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*planner).writeTableDescToBatch
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/table.go:299
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*planner).writeTableDesc
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/table.go:285
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*planner).writeSchemaChange
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/table.go:255
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*alterTableNode).startExec
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/alter_table.go:852
  |   | github.com/cockroachdb/cockroach/pkg/sql.startExec.func2
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/plan.go:519
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal.func1
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:112
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:299
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:79
  |   | github.com/cockroachdb/cockroach/pkg/sql.walkPlan
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:43
  |   | github.com/cockroachdb/cockroach/pkg/sql.startExec
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/plan.go:522
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Start
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:174
  |   | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Columnarizer).Init
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/columnarizer.go:183
  |   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).init
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:94
  |   | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  |   | github.com/co...
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/conn_executor_exec.go#L141-L143](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/conn_executor_exec.go#L141-L143)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/conn_executor_exec.go#L963-L965](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/conn_executor_exec.go#L963-L965)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/conn_executor_exec.go#L1655-L1657](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/conn_executor_exec.go#L1655-L1657)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/conn_executor_exec.go#L2102-L2104](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/conn_executor_exec.go#L2102-L2104)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/distsql_running.go#L1647-L1649](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/distsql_running.go#L1647-L1649)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/distsql_running.go#L1644-L1646](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/distsql_running.go#L1644-L1646)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/distsql_running.go#L1912-L1914](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/distsql_running.go#L1912-L1914)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/distsql_running.go#L901-L903](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/distsql_running.go#L901-L903)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/colflow/vectorized_flow.go#L324-L326](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/colflow/vectorized_flow.go#L324-L326)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/colflow/flow_coordinator.go#L277-L279](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/colflow/flow_coordinator.go#L277-L279)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/colflow/flow_coordinator.go#L243-L245](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/colflow/flow_coordinator.go#L243-L245)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/colflow/flow_coordinator.go#L244-L246](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/colflow/flow_coordinator.go#L244-L246)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/colflow/stats.go#L102-L104](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/colflow/stats.go#L102-L104)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/colflow/stats.go#L93-L95](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/colflow/stats.go#L93-L95)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/colexec/columnarizer.go#L182-L184](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/colexec/columnarizer.go#L182-L184)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/plan_node_to_row_source.go#L173-L175](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/plan_node_to_row_source.go#L173-L175)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/plan.go#L521-L523](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/plan.go#L521-L523)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/walk.go#L42-L44](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/walk.go#L42-L44)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/walk.go#L78-L80](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/walk.go#L78-L80)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/walk.go#L298-L300](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/walk.go#L298-L300)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/walk.go#L111-L113](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/walk.go#L111-L113)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/plan.go#L518-L520](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/plan.go#L518-L520)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/alter_table.go#L851-L853](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/alter_table.go#L851-L853)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/table.go#L254-L256](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/table.go#L254-L256)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/table.go#L284-L286](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/table.go#L284-L286)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/table.go#L298-L300](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/table.go#L298-L300)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/backfill.go#L2487-L2489](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/backfill.go#L2487-L2489)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/backfill.go#L2865-L2867](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/backfill.go#L2865-L2867)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/backfill/backfill.go#L190-L192](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/backfill/backfill.go#L190-L192)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/catalog/schemaexpr/default_exprs.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/catalog/schemaexpr/default_exprs.go#L91-L93)
</details>

```
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt.func1 at line 142
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 964
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchToExecutionEngine at line 1656
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithDistSQLEngine at line 2103
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRunAll at line 1648
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRunAll.func3 at line 1645
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRun at line 1913
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).Run at line 902
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlow).Run at line 325
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).Run at line 278
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).init at line 244
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).init.func1 at line 245
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).Init at line 103
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).init at line 94
pkg/sql/colexec/columnarizer.go in pkg/sql/colexec.(*Columnarizer).Init at line 183
pkg/sql/plan_node_to_row_source.go in pkg/sql.(*planNodeToRowSource).Start at line 174
pkg/sql/plan.go in pkg/sql.startExec at line 522
pkg/sql/walk.go in pkg/sql.walkPlan at line 43
pkg/sql/walk.go in pkg/sql.(*planVisitor).visit at line 79
pkg/sql/walk.go in pkg/sql.(*planVisitor).visitInternal at line 299
pkg/sql/walk.go in pkg/sql.(*planVisitor).visitInternal.func1 at line 112
pkg/sql/plan.go in pkg/sql.startExec.func2 at line 519
pkg/sql/alter_table.go in pkg/sql.(*alterTableNode).startExec at line 852
pkg/sql/table.go in pkg/sql.(*planner).writeSchemaChange at line 255
pkg/sql/table.go in pkg/sql.(*planner).writeTableDesc at line 285
pkg/sql/table.go in pkg/sql.(*planner).writeTableDescToBatch at line 299
pkg/sql/backfill.go in pkg/sql.runSchemaChangesInTxn at line 2488
pkg/sql/backfill.go in pkg/sql.columnBackfillInTxn at line 2866
pkg/sql/backfill/backfill.go in pkg/sql/backfill.(*ColumnBackfiller).InitForLocalUse at line 191
pkg/sql/catalog/schemaexpr/default_exprs.go in pkg/sql/catalog/schemaexpr.MakeDefaultExprs at line 92
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v23.1.4 |
| Go Version | go1.19.4 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.4 |
| Cockroach SHA | cf85e8ad48bb7a8afd821863d4f345baafa4a1b6 |
| # of CPUs | 48 |
| # of Goroutines | 826 |

Jira issue: CRDB-29625

**Comment by yuzefovich** [comment]
dup of #98047
