### ISSUE TITLE
Allow for the cockroach homebrew tab to install arbitrary versions

### ISSUE THREAD

**Issue by Scalahansolo** [cockroachdb/cockroach#106616]
This Issue has been opened on the github issue page for the tap for over 3 years, and has gotten no traction.

https://github.com/cockroachdb/homebrew-tap/issues/42

For something as foundational as a database, the homebrew tap should really allow for dictating the version, with the default being the latest.

Jira issue: CRDB-29643

**Comment by knz** [comment]
fixed via https://github.com/cockroachdb/homebrew-tap/pull/158
