### ISSUE TITLE
Sentry: error.go:89: unexpected error from the vectorized engine: runtime error: slice bounds out of range [::104] with capacity 0
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trac...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#106649]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4309066278/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4309066278/?referrer=webhooks_plugin)

Panic Message:

```
error.go:89: unexpected error from the vectorized engine: runtime error: slice bounds out of range [::104] with capacity 0
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:89
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | runtime.goPanicSlice3Acap
  | 	GOROOT/src/runtime/panic.go:173
  | github.com/cockroachdb/cockroach/pkg/col/coldata.(*element).getNonInlined
  | 	github.com/cockroachdb/cockroach/pkg/col/coldata/bytes.go:106
  | github.com/cockroachdb/cockroach/pkg/col/coldata.(*Bytes).copyElements
  | 	github.com/cockroachdb/cockroach/pkg/col/coldata/bytes.go:286
  | github.com/cockroachdb/cockroach/pkg/col/coldata.(*Bytes).AppendSlice
  | 	github.com/cockroachdb/cockroach/pkg/col/coldata/bytes.go:404
  | github.com/cockroachdb/cockroach/pkg/col/coldata.(*memColumn).Append
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/col/coldata/vec.eg.go:251
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils.(*AppendOnlyBufferedBatch).AppendTuples.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils/utils.go:209
  | github.com/cockroachdb/cockroach/pkg/sql/colmem.(*Allocator).PerformAppend
  | 	github.com/cockroachdb/cockroach/pkg/sql/colmem/allocator.go:457
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils.(*AppendOnlyBufferedBatch).AppendTuples
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils/utils.go:207
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.spool_false
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/colexec/sorttopk.eg.go:332
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*topKSorter).spool
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/colexec/sorttopk.eg.go:73
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*topKSorter).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/sorttopk.go:165
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk.(*diskSpillerBase).Next.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk/disk_spiller.go:198
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk.(*diskSpillerBase).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk/disk_spiller.go:196
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*OrderedSynchronizer).Next
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/colexec/ordered_synchronizer.eg.go:106
  | github.com/cockroachdb/cockroach/pkg/sql/colexecop.(*noopOperator).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecop/operator.go:391
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecbase.(*simpleProjectOp).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecbase/simple_project.go:124
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*limitOp).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/limit.go:47
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).nextAdapter
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:252
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:256
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:299
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:320
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:757
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1764
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1472
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1597
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1200
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:694
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:131
Wraps: (3) unexpected error from the vectorized engine
Wraps: (4) runtime error: slice bounds out of range [::104] with capacity 0
  | -- cause hidden behind barrier
  | runtime error: slice bounds out of range [::104] with capacity 0
  | (1) runtime error: slice bounds out of range [::104] with capacity 0
  | Error types: (1) runtime.boundsError
Error types: (1) *assert.withAssertionFailure (2) *withstack.withStack (3) *errutil.withPrefix (4) *barriers.barrierErr
-- report composition:
*barriers.barrierErr: masked error: runtime error: slice bounds out of range [::104] with capacity 0
*errutil.withPrefix: unexpected error from the vectorized engine
error.go:89: *withstack.withStack (top exception)
*assert.withAssertionFailure
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/conn_executor_exec.go#L130-L132](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/conn_executor_exec.go#L130-L132)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/conn_executor_exec.go#L693-L695](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/conn_executor_exec.go#L693-L695)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/conn_executor_exec.go#L1199-L1201](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/conn_executor_exec.go#L1199-L1201)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/conn_executor_exec.go#L1596-L1598](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/conn_executor_exec.go#L1596-L1598)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/distsql_running.go#L1471-L1473](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/distsql_running.go#L1471-L1473)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/distsql_running.go#L1763-L1765](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/distsql_running.go#L1763-L1765)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/distsql_running.go#L756-L758](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/distsql_running.go#L756-L758)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/colflow/vectorized_flow.go#L319-L321](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/colflow/vectorized_flow.go#L319-L321)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/colflow/flow_coordinator.go#L298-L300](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/colflow/flow_coordinator.go#L298-L300)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/colflow/flow_coordinator.go#L255-L257](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/colflow/flow_coordinator.go#L255-L257)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/colflow/flow_coordinator.go#L251-L253](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/colflow/flow_coordinator.go#L251-L253)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/colexec/limit.go#L46-L48](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/colexec/limit.go#L46-L48)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/colexec/colexecbase/simple_project.go#L123-L125](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/colexec/colexecbase/simple_project.go#L123-L125)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/colexecop/operator.go#L390-L392](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/colexecop/operator.go#L390-L392)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/bazel-out/k8-opt/bin/pkg/sql/colexec/ordered_synchronizer.eg.go#L105-L107](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/bazel-out/k8-opt/bin/pkg/sql/colexec/ordered_synchronizer.eg.go#L105-L107)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/colexec/colexecdisk/disk_spiller.go#L195-L197](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/colexec/colexecdisk/disk_spiller.go#L195-L197)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/colexec/colexecdisk/disk_spiller.go#L197-L199](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/colexec/colexecdisk/disk_spiller.go#L197-L199)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/colexec/sorttopk.go#L164-L166](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/colexec/sorttopk.go#L164-L166)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/bazel-out/k8-opt/bin/pkg/sql/colexec/sorttopk.eg.go#L72-L74](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/bazel-out/k8-opt/bin/pkg/sql/colexec/sorttopk.eg.go#L72-L74)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/bazel-out/k8-opt/bin/pkg/sql/colexec/sorttopk.eg.go#L331-L333](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/bazel-out/k8-opt/bin/pkg/sql/colexec/sorttopk.eg.go#L331-L333)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/colexec/colexecutils/utils.go#L206-L208](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/colexec/colexecutils/utils.go#L206-L208)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/colmem/allocator.go#L456-L458](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/colmem/allocator.go#L456-L458)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/colexec/colexecutils/utils.go#L208-L210](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/colexec/colexecutils/utils.go#L208-L210)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/bazel-out/k8-opt/bin/pkg/col/coldata/vec.eg.go#L250-L252](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/bazel-out/k8-opt/bin/pkg/col/coldata/vec.eg.go#L250-L252)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/col/coldata/bytes.go#L403-L405](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/col/coldata/bytes.go#L403-L405)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/col/coldata/bytes.go#L285-L287](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/col/coldata/bytes.go#L285-L287)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/col/coldata/bytes.go#L105-L107](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/col/coldata/bytes.go#L105-L107)
[GOROOT/src/runtime/panic.go#L172-L174](GOROOT/src/runtime/panic.go#L172-L174)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/colexecerror/error.go#L88-L90](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/colexecerror/error.go#L88-L90)
</details>

```
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt.func1 at line 131
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 694
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchToExecutionEngine at line 1200
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithDistSQLEngine at line 1597
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRunAll at line 1472
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRun at line 1764
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).Run at line 757
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlow).Run at line 320
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).Run at line 299
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).next at line 256
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).nextAdapter at line 252
pkg/sql/colexec/limit.go in pkg/sql/colexec.(*limitOp).Next at line 47
pkg/sql/colexec/colexecbase/simple_project.go in pkg/sql/colexec/colexecbase.(*simpleProjectOp).Next at line 124
pkg/sql/colexecop/operator.go in pkg/sql/colexecop.(*noopOperator).Next at line 391
bazel-out/k8-opt/bin/pkg/sql/colexec/ordered_synchronizer.eg.go in pkg/sql/colexec.(*OrderedSynchronizer).Next at line 106
pkg/sql/colexec/colexecdisk/disk_spiller.go in pkg/sql/colexec/colexecdisk.(*diskSpillerBase).Next at line 196
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colexec/colexecdisk/disk_spiller.go in pkg/sql/colexec/colexecdisk.(*diskSpillerBase).Next.func1 at line 198
pkg/sql/colexec/sorttopk.go in pkg/sql/colexec.(*topKSorter).Next at line 165
bazel-out/k8-opt/bin/pkg/sql/colexec/sorttopk.eg.go in pkg/sql/colexec.(*topKSorter).spool at line 73
bazel-out/k8-opt/bin/pkg/sql/colexec/sorttopk.eg.go in pkg/sql/colexec.spool_false at line 332
pkg/sql/colexec/colexecutils/utils.go in pkg/sql/colexec/colexecutils.(*AppendOnlyBufferedBatch).AppendTuples at line 207
pkg/sql/colmem/allocator.go in pkg/sql/colmem.(*Allocator).PerformAppend at line 457
pkg/sql/colexec/colexecutils/utils.go in pkg/sql/colexec/colexecutils.(*AppendOnlyBufferedBatch).AppendTuples.func1 at line 209
bazel-out/k8-opt/bin/pkg/col/coldata/vec.eg.go in pkg/col/coldata.(*memColumn).Append at line 251
pkg/col/coldata/bytes.go in pkg/col/coldata.(*Bytes).AppendSlice at line 404
pkg/col/coldata/bytes.go in pkg/col/coldata.(*Bytes).copyElements at line 286
pkg/col/coldata/bytes.go in pkg/col/coldata.(*element).getNonInlined at line 106
GOROOT/src/runtime/panic.go in runtime.goPanicSlice3Acap at line 173
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1 at line 89
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v22.2.9 |
| Go Version | go1.19.6 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v22.2.9 |
| Cockroach SHA | 1b11ca676513ae073ea696c7cc3123d2684bc4bd |
| # of CPUs | 12 |
| # of Goroutines | 817 |

Jira issue: CRDB-29655

**Comment by yuzefovich** [comment]
lots of badness on this cluster, unactionable
