### ISSUE TITLE
sql: CREATE TABLE AS and REFRESH MATERIALIZED VIEW with some expressions fail in the face of transaction retries

### ISSUE THREAD

**Issue by stevendanna** [cockroachdb/cockroach#106696]
**Describe the problem**

`CREATE TABLE AS` and `REFRESH MATERIALIZED VIEW` built from expressions that are not guaranteed to return the same value on subsequent calls can fail with the following error in the face of transaction retries:

```
        (XXUUU) addsstable [/Table/116/1/-9222809086901354496/0,/Table/116/1/-9222809086901354496/0/NULL): checking for key collisions: ingested key collides with an existing one: /Table/116/1/-9222809086901354496/0
```

The error comes from AddSSTable because despite the fact that we set DisallowShadowingBelow to a value that allows for retries, the values must still match. As explained in a code comment in the bulk row writer, the DisallowedShadowing check is required:

```
			// We disallow shadowing here to ensure that we report errors when builds
			// of unique indexes fail when there are duplicate values. Note that while
			// the timestamp passed does allow shadowing other writes by the same job,
			// the check for allowed shadowing also requires the values match, so a
			// conflicting unique index entry would still be rejected as its value
			// would point to a different owning row.
			DisallowShadowingBelow: writeTS,
````

This was found as part of #106417 and not in the wild. It isn't clear to me that such retries are very likely given that both used a fixed timestamp scan that is likely to be some time in the past.

Jira issue: CRDB-29682

**Comment by mgartner** [comment]
@stevendanna do you have a reproduction for this? It sounds like the materialized view backfill doesn't restart from the beginning when it encounters a txn retry. cc @cockroachdb/sql-foundations

**Comment by rafiss** [comment]
If we can find a way to repro and test this, let's work on a fix for this. @stevendanna let us know if you have any pointers.

**Comment by stevendanna** [comment]
I hope to merge part of a PR today that should give you an easy way to reproduce this. If that doesn't merge, I should be able to create a small unit tests that reproduces this.
