### ISSUE TITLE
streamingreplication: hide progress bar after initial scan

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#106677]
![image](https://github.com/cockroachdb/cockroach/assets/13264141/7bec6ca4-ddef-48b1-a5ed-3363d71df696)

Having a progress bar after the initial scan makes no sense, and the fact that it hangs around at 0% progress made me think something was wrong (when it wasn't). We should have the status as "running" like we do with changefeeds after initial scan.

Jira issue: CRDB-29673

Epic CRDB-26968

**Comment by stevendanna** [comment]
Going to close this. We decided to use the progress bar for cutover rather than the initial scan for now. We can revisit that decision in the future though.
