### ISSUE TITLE
sql: temp table can still persist when parent database is dropped

### ISSUE THREAD

**Issue by chengxiong-ruan** [cockroachdb/cockroach#106606]
**Describe the problem**
In https://github.com/cockroachlabs/support/issues/2421 we saw an case where the parent database of a temporary table was dropped but the temp table descriptor still exists. We don't see a way how this can be reproduced. That would be the 1st step.

Jira issue: CRDB-29639

**Comment by rafiss** [comment]
Let's see if we can reproduce this. If we are unable to, we can leave this as a tracking issue in case this reoccurs in the future.

**Comment by rafiss** [comment]
Looks like we tracked this down in https://github.com/cockroachdb/cockroach/issues/108751, so I'll close this.
