### ISSUE TITLE
sql: Standardize SQL error format using PG's structured errors

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#10668]
Discussed in https://github.com/cockroachdb/cockroach/pull/10585#issuecomment-260117743.

Through Postgres' SQL wire protocol, errors are returned in a structured manner that allows for a number of [optional fields](https://www.postgresql.org/docs/current/static/protocol-error-fields.html). These fields include error *hints* and *details*. Because these are structured, frontend applications are able to display this auxiliary error information in interesting ways that string concatenation does not permit. We should investigate making our error reporting more structured and exposing the extra fields through [`v3Conn.sendErrorWithCode`](https://github.com/cockroachdb/cockroach/blob/131cf68bb47fa583d54182960c2bbc4289ee8dfb/pkg/sql/pgwire/v3.go#L778.).

**Comment by a6802739** [comment]
@nvanbenschoten, Colud I have a see on it?

**Comment by nvanbenschoten** [comment]
@a6802739 it's all yours if you want it! This may not be directly straightforward and will require designing a solution so that structured errors are usable in SQL code without being required.

I envision this being an extension of the work we've done with [`ErrorWithPGCode`](https://github.com/cockroachdb/cockroach/blob/29c56f913922b9c7fc6de546f397dff9ca4208c4/pkg/sql/sqlbase/errors.go#L44).
