### ISSUE TITLE
builtins, storage: create builtin (or other functionality accessible from testing) to trigger pebble flush

### ISSUE THREAD

**Issue by xinhaoz** [cockroachdb/cockroach#106619]
It would be convenient for tests that check `ApproximateDiskBytes` returned from pebble to have a non-zero value. Currently these tests need to either wait out a long timeout, or force the flush in some roundabout way. 

Jira issue: CRDB-29645

**Comment by xinhaoz** [comment]
I was able to flush pretty easily through accessing each store in the test cluster directly. Not sure if this is actually necessary.

**Comment by jbowens** [comment]
Closing this one out. I think today we have two ways higher-level tests can induce a flush:

- Grabbing a handle on the `Engine` and explicitly triggering a flush.
- Using the `crdb_internal.compact_engine_span` builtin to trigger a manual compaction over the key range, which should trigger a flush as well.

Feel free to re-open if there are other instances where the above options aren't workable!
