### ISSUE TITLE
rpc: leaked "conn state watcher" goroutines on flapping RPC connections

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#106773]
In a testing cluster containing a host with a flapping NIC, we saw an unbounded number of goroutines accumulate in `rpc.Context` "conn state watcher" goroutines.
```
405: select [13~830 minutes] [Created by stop.(*Stopper).RunAsyncTaskEx @ stopper.go:461]
    grpc                      clientconn.go:515                     (*ClientConn).WaitForStateChange(*, {#4, *}, 2)
    rpc                       context.go:2592                       (*Context).runHeartbeat.func3({#4, *})
    stop                      stopper.go:470                        (*Stopper).RunAsyncTaskEx.func2()
67812: select [57~818 minutes] [Created by stop.(*Stopper).RunAsyncTaskEx @ stopper.go:461]
    grpc                      clientconn.go:515                     (*ClientConn).WaitForStateChange(*, {#4, *}, 4)
    rpc                       context.go:2592                       (*Context).runHeartbeat.func3({#4, *})
    stop                      stopper.go:470                        (*Stopper).RunAsyncTaskEx.func2()
```
[goroutines.zip](https://github.com/cockroachdb/cockroach/files/12043041/goroutines.zip)

Note that some stacks have a `sourceState` argument of `Ready` while most have an argument of `Shutdown`.

During this time, we see RPC heartbeat loops starting and exiting.

<img width="669" alt="Screenshot 2023-07-13 at 2 24 28 PM" src="https://github.com/cockroachdb/cockroach/assets/5438456/195c742c-39c6-4753-9b64-0d2e286980b5">

Are we missing graceful shutdown logic? We don't see a leak in "rpc heartbeat" goroutines, so they must be handling the shutdown correctly.

cc. @tbg 

Jira issue: CRDB-29710

**Comment by andrewbaptist** [comment]
@erikgrinaker Do you want to take a quick look at this. The problem is in the way we are handling the conn state watcher. I believe that the problem is that we transition from Ready to Shutdown (or passes through TransientFailure, but so fast that we don't catch it), but that state is not handled by this thread, so it sits forever in the `WaitForStateChange` waiting for it to go to another state. This will never happen

 It seems like the code should be:

```
if st == connectivity.TransientFailure || st == connectivity.Shutdown {
}
```

or simply remove the if block completely as any transition out of Ready is treated as a failure.

I just wanted to make sure I'm not missing something, but I can create a quick patch for this if you are busy.

**Comment by erikgrinaker** [comment]
I won't have time to dig into this.

**Comment by andrewbaptist** [comment]
This appears to be fixed as a result of the work done in #99191. We no longer are launching these goroutines. There is a different goroutine launched, but it is consistently closed.

**Comment by erikgrinaker** [comment]
Should we look into a backportable change for past releases?

**Comment by andrewbaptist** [comment]
We could make a simple change as I suggested above. I don't know how common this happens in practice, but it does seem like it could be a problem in certain network configurations. I think the risk/reward trade-off here is probably right to make a change in 23.1 at least. Thoughts?

**Comment by erikgrinaker** [comment]
Yeah, let's do it, thanks for the PR.
