### ISSUE TITLE
Add a check in debug doctor for a cluster at risk of indexes with invalid encoding

### ISSUE THREAD

**Issue by smcvey** [cockroachdb/cockroach#106794]
**Is your feature request related to a problem? Please describe.**
Please add an additional check to `cockroach debug doctor` which checks the descriptors looking for tables that are at risk of invalid encoding.

**Additional context**
We only need to have this check in the latest 23.1 binary, there's no need to backport it to earlier versions.

Jira issue: CRDB-29717

Epic CRDB-28665

**Comment by rafiss** [comment]
Related to https://github.com/cockroachdb/cockroach/issues/106739 also.
