### ISSUE TITLE
SQL Stats collection affecting foreground traffic during node drains.

### ISSUE THREAD

**Issue by aliher1911** [cockroachdb/cockroach#106763]
While investigating flakiness of roachtest kv/gracefuldraining/nodes=3 I found that stat collection jobs are affecting foreground SQL traffic.

What this test does is runs kv0 (write only) workload with 1000QPS limit. While running the workload it drains one node, stops it, starts again and repeats. Since we are doing graceful drains, we don't expect foreground traffic to be affected. Test is capturing workload QPS every 10 seconds and expects it to stay above 900. 

When stats collection is enabled, test frequently fails because QPS timeseries looks like:
```
[{TimestampNanos:1689260610000000000 Value:994.8000000000001}
 {TimestampNanos:1689260620000000000 Value:991.4000000000001}
 {TimestampNanos:1689260630000000000 Value:988.2}
 {TimestampNanos:1689260640000000000 Value:991.1}
 {TimestampNanos:1689260650000000000 Value:983.3}
 {TimestampNanos:1689260660000000000 Value:992.6}
 {TimestampNanos:1689260670000000000 Value:990.9000000000001}
 {TimestampNanos:1689260680000000000 Value:993}
 {TimestampNanos:1689260690000000000 Value:995.6}
 {TimestampNanos:1689260700000000000 Value:996.2}
 {TimestampNanos:1689260710000000000 Value:998}
 {TimestampNanos:1689260720000000000 Value:996.5}
 {TimestampNanos:1689260730000000000 Value:997.5}
 {TimestampNanos:1689260740000000000 Value:998.5}
 {TimestampNanos:1689260750000000000 Value:992.6}
 {TimestampNanos:1689260760000000000 Value:993.1}
 {TimestampNanos:1689260770000000000 Value:992.3}
 {TimestampNanos:1689260780000000000 Value:993.5}
 {TimestampNanos:1689260790000000000 Value:817.7}
 {TimestampNanos:1689260800000000000 Value:836.9000000000001}]
```
Where you can see occasional dips in write performance.

Setting `sql.stats.automatic_collection.enabled` to false makes QPS much more consistent and staying reliably above 990. 
There's a pending PR https://github.com/cockroachdb/cockroach/pull/106596 to disable that by default as the test is meant to test replica draining, but the effects of stats jobs on foreground traffic are concerning.

It is possible that this happens when stats jobs are being preempted.

Jira issue: CRDB-29707

**Comment by michae2** [comment]
@aliher1911 if you still have the test running, does increasing `sql.stats.automatic_collection.max_fraction_idle` from the default of 0.9 to something higher, say 0.95, help reduce the impact?

**Comment by aliher1911** [comment]
That's a roachtest which doesn't run very long. I've been stressing it more and managed to make it fail even without stats. It might be environment dependent. Nevertheless if I run multiple times on the single cluster and they may fail 3/10 times with stats and don't fail without. But if I recreate cluster I may end up with instance that will fail without stats half of runs.
So stats probably push it too far in terms of flakiness. But the problem is probably not stats themselves. I'll try few more things to try to see what causes the slowness.

**Comment by mgartner** [comment]
We would expect stats collection to affect foreground traffic during collection. If stats are affecting foreground traffic when collection is not running, that would be unexpected, and we would want to look into this more. Is it just collection affecting foreground traffic?

**Comment by rharding6373** [comment]
@aliher1911 If you have more information that will help us investigate, please reopen this issue. Thanks!
