### ISSUE TITLE
kvserver: Switch to using EventuallyFileOnlySnapshots for consistency checker and mvcc GC

### ISSUE THREAD

**Issue by itsbilal** [cockroachdb/cockroach#106775]
Currently, the replica consistency checker uses a long lived Pebble snapshot for checking consistency between replicas. It grabs this snapshot at the same index across all replicas, with some coordination over Raft. The MVCC GC queue also uses a pebble snapshot.

However, since `IngestAndExcise` as well as https://github.com/cockroachdb/cockroach/pull/105839 break the guarantees traditionally provided by snapshots in Pebble, we need to get users of Pebble snapshots onto other abstractions with similar guarantees. A long-lived iterator is one option, however consistency checking can be really slow and long-lived so the behaviour of iterators around pinning memtables is really not desirable here. An `EventuallyFileOnlySnapshot` would serve the consistency checker and MVCC GC queue very well.

This change asks for a wholesale move of the consistency checker and MVCC GC queue to `EventuallyFileOnlySnapshot` to allow for broader use of `IngestAndExcise` in reducing write-amp in Pebble.

Dependency (and more context) in https://github.com/cockroachdb/pebble/issues/2740

Jira issue: CRDB-29712

**Comment by jbowens** [comment]
Is there already an issue for switching MVCC GC over?

**Comment by itsbilal** [comment]
@jbowens I updated this issue to also cover the MVCC GC case. Both should be easy to handle at the same time.
