### ISSUE TITLE
log: Unnecessary temp dir creation

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#10670]
Since #9940, every `cockroach` invocation has created a temporary directory that it never cleans up (and usually never uses). This directory creation needs to be postponed to the point where we know whether it will be used or not. (if we create it at all. It may be better to just turn off logging if we don't have a log destination configured than to write to an undiscoverable directory)

**Comment by jordanlewis** [comment]
See also #10113, although the proximal cause of that was fixed.
