### ISSUE TITLE
Support CIDR data type

### ISSUE THREAD

**Issue by giangpham712** [cockroachdb/cockroach#106756]
**Is your feature request related to a problem? Please describe.**
CIDR data type is currently not supported by CockroachDB. This causes a number of tests in efcore.pg library to fail when running against CockroachDB

Example SQL used for creating the test table

```
CREATE TABLE "NetTestEntities" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Inet" inet,
    "Cidr" cidr NOT NULL,
    "Macaddr" macaddr,
    "Macaddr8" macaddr8,
    "TextInet" text,
    "TextMacaddr" text,
    CONSTRAINT "PK_NetTestEntities" PRIMARY KEY ("Id")
);

```

**Additional context**

Jira issue: CRDB-29704

**Comment by yuzefovich** [comment]
dup of #18846
