### ISSUE TITLE
<jemalloc>: Unsupported system page size with cockroach 23.1.5

### ISSUE THREAD

**Issue by fveauvy** [cockroachdb/cockroach#106745]
**Describe the problem**

I'm getting an error when running cockroachdb v23.1.5 linux-arm64. I'm using an [Asahi Linux](https://asahilinux.org/) kernel (6.3.0-asahi-10-1-ARCH) running on a Mac M1 mini.

Cockroach fails with :

```
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
runtime/cgo: malloc failed: Cannot allocate memory
```

Note that I don't get this error using the version 22.2.11 Docker image : [cockroachdb/cockroach:arm64-v22.2.11](https://hub.docker.com/layers/cockroachdb/cockroach/arm64-v22.2.11/images/sha256-aebccc9f7d2177cee6ff7e8904545ad92d64ed247bda5f2836de35b09aa68f69?context=explore)

**To Reproduce**

Using Asahi Linux on a Apple Silicon Mac :

1. `docker pull cockroachdb/cockroach:23.1.5`
2. `docker volume create roach-single`
3. `docker run -it -v "roach-single:/cockroach/cockroach-data" cockroachdb/cockroach:23.1.5 start-single-node --insecure`
4. You'll see the error mentioned above in the console output

**Expected behavior**

Since cockroach 22.2.11 is working fine on linux/arm64 with Linux Asahi, I think it should also run with 23.1.5.

**Additional data / screenshots**

Here are some related links and issues : 

![CleanShot 2023-07-13 at 11 52 13](https://github.com/cockroachdb/cockroach/assets/38651917/a9f18f85-2180-4ba0-a2e9-9e4778f5440d)

 - https://github.com/cockroachdb/cockroach/issues/84971#issuecomment-1629588873
 - https://asahilinux.org/2022/03/asahi-linux-alpha-release/
 - https://github.com/jemalloc/jemalloc/issues/467
 - https://github.com/redis/redis/pull/11407
 - https://github.com/sharkdp/fd/issues/1085

**Additional context**

We're migrating our CI/CD pipeline to use GitHub Actions Self-Hosted Runners. For some reasons, we want to use Linux and our available Mac Mini M1 in order to run testing workflows that includes CockroachDB services.

Jira issue: CRDB-29697

**Comment by RaduBerinde** [comment]
To fix this, we need to configure jemalloc to support a larger page size (`--with-lg-page=16`). However, in some cases that setting caused problems, at least a while back - #81581.

**Comment by RaduBerinde** [comment]
@fveauvy I will try to tweak the jemalloc build settings for ARM to support larger pages. I do want to point out though that for now ARM support is best-effort and we don't recommend using it for production. We have filed internal tickets to improve the documentation to be more clear about this.

**Comment by RaduBerinde** [comment]
@fveauvy Hopefully the next 23.1.x release works.

**Comment by pawalt** [comment]
FYI this is fixed for me on the most recent version of CRDB. I'm also on Asahi kernel `6.5.0-asahi`. This is the command that passed for me:

```
sudo docker run -it -v "roach-single:/cockroach/cockroach-data" cockroachdb/cockroach:v23.1.13 start-single-node --insecure
```

Thanks for the help @RaduBerinde

**Comment by RaduBerinde** [comment]
Thanks @pawalt!  I will close this then.
