### ISSUE TITLE
benchmarks: BenchmarkMVCCDeleteRange1Version8Bytes_RocksDB fails intermittently

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#10678]
Seen in [Benchmark build #168](https://teamcity.cockroachdb.com/viewLog.html?buildId=47093&buildTypeId=Cockroach_BenchmarkTests&tab=artifacts):
```
BenchmarkMVCCBatchTimeSeries282_RocksDB-16                 	    3000	    482765 ns/op	   32225 B/op	       6 allocs/op
--- FAIL: BenchmarkMVCCDeleteRange1Version8Bytes_RocksDB
	bench_test.go:488: mvcc_data_1_9362_8/000067.sst: 17954/4096 copied
```

**Comment by tamird** [comment]
This is pretty odd. That failure message suggests that the thing that was copied had a different size than the source of the copy. This suggests a troubling bug somewhere upstream of us, though I haven't been able to reproduce this at all.

**Comment by jordanlewis** [comment]
Similar failure seen again:

```
--- FAIL: BenchmarkMVCCDeleteRange1Version256Bytes_RocksDB
    bench_test.go:488: mvcc_data_1_1724_256/000066.sst: 130974/98225 copied
```

**Comment by dianasaur323** [comment]
Closing due to age of issue and convo with @jordanlewis . Please feel free to re-open.
