### ISSUE TITLE
stability: Figure out non-zero rate of consistency check failures without corresponding log messages

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#10677]
On one of our test clusters (cyan), the counter for consistency check queue failures is non-zero even though we don't see any messages in the logs indicating consistency check failures. We should figure out why this is and whether it's behaving the way we want.

**Comment by a-robinson** [comment]
It turns out this is due to the `baseQueue` processing infrastructure. If it's [unable to get the lease on a replica when processing it](https://github.com/cockroachdb/cockroach/blob/master/pkg/storage/queue.go#L534), we [count that as an error against the queue that's trying to process the replica](https://github.com/cockroachdb/cockroach/blob/master/pkg/storage/queue.go#L564).

This seems undesirable. If I understand correctly, it isn't truly an error to not be able to get the lease at this point in time, and it certainly isn't indicative of a problem occurring in the underlying queue implementation.

The question I'm not as sure of is whether this error is worth recording in a separate metric or just not tracking in a metric at all. @petermattis?

**Comment by petermattis** [comment]
What are the errors that are occurring? `NotLeaseHolderError` is already ignored and that's the only error I would expect.

**Comment by a-robinson** [comment]
They're all "range %d not found" errors. For example:

```
E161114 10:21:36.735306 151 storage/queue.go:568  [n5,replica consistency chec
ker,s5,r3231/1:/Table/51/1/776{76380…-98950…}] [n5,s5,r3231/1:/Table/51/1/776{76380…-98950…}]: could
 not obtain lease: range 3231 was not found
```

**Comment by petermattis** [comment]
Hmm, I've seen those too (locally) and have been meaning to track them down. Do you mind tracking down why that error is occurring? Was the replica marked as destroyed?

**Comment by a-robinson** [comment]
Sure, I'll get to the bottom of them.

**Comment by a-robinson** [comment]
All the instances I looked into were just due to being added to the replica GC queue (by peer suggestion) immediately before getting processed by the consistency checker. And if you compare the graphs for consistency queue failures with when the replica GC queue was active, they line up quite well:

<img width="1042" alt="screen shot 2016-11-14 at 2 41 29 pm" src="https://cloud.githubusercontent.com/assets/7085343/20279969/9cb95940-aa78-11e6-8522-ec3bb2b97552.png">

**Comment by a-robinson** [comment]
My assumption is that there isn't anything incorrect about that behavior. You could argue that once we add a replica to the GC queue we might want to skip putting that replica through the other queues as an optimization, but there doesn't appear to be anything truly wrong with what's going on.

**Comment by petermattis** [comment]
Perhaps `baseQueue.processReplica` should consider `RangeNotFound` errors "harmless" as well.
