### ISSUE TITLE
sql: show indexes with invalid encoding type in invalid_objects and DB console

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#106739]
**Is your feature request related to a problem? Please describe.**
https://github.com/cockroachdb/cockroach/issues/97526 was a bug where secondary indexes can have the wrong encoding type. In some cases, it can lead to incorrect data being returned. There should be a way to easily detect if this problem is occurring in the cluster. It's even worse if a column is added to this invalid secondary index.

**Describe the solution you'd like**
We don't want to backport extra validation, since that could cause existing queries to fail. But we should have another way to get these invalid indexes in the crdb_internal.invalid_objects table, and alert the user in some way that the problem exists.

Jira issue: CRDB-29696

Epic CRDB-28665

**Comment by fqazi** [comment]
Opened a tracking issue for the console side: https://github.com/cockroachdb/cockroach/issues/107568
