### ISSUE TITLE
sql: CREATE STATISTICS can produce more than 1 stats entry in the face of rare transaction retry

### ISSUE THREAD

**Issue by stevendanna** [cockroachdb/cockroach#106810]
**Describe the problem**

During testing with randomly injected transactions, I've observed that a CREATE STATS call can occasionally result in duplicate stats entries.

I believe the problem is that if this transaction retries:

https://github.com/nvanbenschoten/cockroach/blob/cad1df0063889f9e61207f33f1f2b341afa27eae/pkg/sql/create_stats.go#L615-L658

The entire distsql flow re-runs.  But, the distsql flow inserts the stats via a different transaction:

https://github.com/nvanbenschoten/cockroach/blob/cad1df0063889f9e61207f33f1f2b341afa27eae/pkg/sql/rowexec/sample_aggregator.go#L439

I haven't confirmed this completely. Rather, I just set the debug names on a few transactions and observed which ones were retried during the failure.

Since CREATE STATISTICS already isn't transactional (for instance, CREATE STATISTICS inside an explicit transaction does not respect a ROLLBACK), it isn't clear to me this is much of a bug, but it does still seems surprising.

Note also that I've only reproduced this synthetically via injected retry errors.  It isn't clear to me that the transaction is actually very likely to retry so I'm skeptical this has much real-world exposure.

Jira issue: CRDB-29723

**Comment by michae2** [comment]
Nice find!

This is surprising, but after thinking about it, I'm not sure it would actually break anything. AFAICT it would be equivalent to running `CREATE STATISTICS` twice in very short succession, which would be expensive in terms of performance but shouldn't cause any logical errors.

> Note also that I've only reproduced this synthetically via injected retry errors. It isn't clear to me that the transaction is actually very likely to retry so I'm skeptical this has much real-world exposure.

We go to pains to avoid retries (this transaction always uses AOST) so this should be difficult to hit without injected retry errors.

**Comment by mgartner** [comment]
Closing because, as far as we know, this has no negative consequences.
