### ISSUE TITLE
spanconfigsqlwatcherccl: TestSQLWatcherMultiple gets confused watching over secondary tenants

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#106821]
Informs #76378

**Describe the problem**

When `TestSQLWatcherMultiple` is run over a secondary tenant, it fails some of its conditions, e.g.:
```
    sqlwatcher_test.go:345:
                Error Trace:    pkg/ccl/spanconfigccl/spanconfigsqlwatcherccl/spanconfigsqlwatcherccl_test/pkg/ccl/spanconfigccl/spanconfigsqlwatcherccl/sqlwatcher_test.go:345
                                                        GOROOT/src/runtime/asm_amd64.s:1594
                Error:          Not equal:
                                expected: 1
                                actual  : 0
                Test:           TestSQLWatcherMultiple
```

**How to reproduce**

Replace `TestDoesNotWorkWithSecondaryTenantsButWeDontKnowWhyYet` by `TestTenantAlwaysEnabled` and run the test.

**Expected solution**

The test code should function and succeeds whether or not the watcher is run over a secondary tenant.

Jira issue: CRDB-29730

**Comment by knz** [comment]
Similarly TestSQLWatcherOnEventError hangs in that case.

The other watcher tests are similarly affected.

**Comment by arulajmani** [comment]
Given this is in the SQLWatcher, which is owned by SQL foundations, I'm going to move it to their triage queue and un-assign KV.
