### ISSUE TITLE
UI Console: Statements: Identical Queries are not aggregated when "Application Names" column is removed

### ISSUE THREAD

**Issue by world2mark** [cockroachdb/cockroach#106836]
UI Console --> SQL Activity --> Statements: Identical Queries are not aggregated across **Application Names**

in **V23.1.5**, I have multiple replicas of apps, each listed separately while running the same queries.  When I remove the **Application Name** column, I am expecting the UI to summarize the rows into a single row, with proper total execution-count, proper weighted-average for statement times, and all the other columns totalled accordingly.  Instead I get separate rows for all replicas of the same query and it's difficult if not impossible to perform analytics on which queries are impacting a cluster.

In **V22.2.6**, there is no Application Name column so the statement (fingerprints) are summarized properly as a single row.

While we appreciate the new app-name column, the UI does not update/summarize the stats when I remove that column.

Jira issue: CRDB-29736

**Comment by maryliag** [comment]
Showing/Hiding a column should not affect the results being displayed. Is not a selection on aggregation.
Closing as this is working as expecting and not a priority to be changed.
