### ISSUE TITLE
raftMu: mutex held by github.com/cockroachdb/cockroach/pkg/storage.(*Store).RemoveReplica ...

### ISSUE THREAD

**Issue by youngl98** [cockroachdb/cockroach#10684]
Hi,

I am running a 3 secure node cockroach.  The following is the WARNING message I see at least one of the nodes that has the following stacktrace in the WARNING log.

What does this mean?  What should I do?

Also I am attaching the WARNING log files from all three roach nodes...

[cockroach.WARNING.zip](https://github.com/cockroachdb/cockroach/files/590074/cockroach.WARNING.zip)

Please follow the steps below to help us help you.

1. Please supply the header (i.e. the first few lines) of your most recent
   log file **for each node in your cluster**. On most unix-based systems
   running with defaults, this boils down to the output of

     grep -F '[config]' cockroach-data/logs/cockroach.INFO

> I161114 02:26:58.021200 1 util/log/clog.go:988  [config] file created at: 2016/11/14 02:26:58
> I161114 02:26:58.021200 1 util/log/clog.go:988  [config] running on machine: sl73commapd002
> I161114 02:26:58.021200 1 util/log/clog.go:988  [config] binary: CockroachDB beta-20161110 (linux amd64, built 2016/11/10 19:35:51, go1.7.3)
> I161114 02:26:58.021200 1 util/log/clog.go:988  [config] arguments: [/var/cockroach/bin/cockroach start --http-port=8080 --store=path=/var/cockroach/cockroach-data --store=path=/usr/mware/cockroachdb-store --key=/var/cockroach/certs/sl73commapd002.key]

   When log files are not available, supply the output of `cockroach version`
   and all flags/environment variables passed to `cockroach start` instead.

2. Please describe the issue you observed:

This snippet is from the cockroach.WARNING file:

`cockroach.WARNING -> /var/cockroach/cockroach-data/logs/cockroach.sl73commapd002.younglee.log.WARNING.2016-11-14T02_26_58Z.1471`

> W161114 02:27:07.900392 61 storage/replica.go:554  [n1,s1,r1/6:/{Min-System/tsd/c…}] raftMu: mutex held by github.com/cockroachdb/cockroach/pkg/storage.(*Store).RemoveReplica for 640.72205ms (>500ms):
> goroutine 61 [running]:
> runtime/debug.Stack(0x1d55cd8, 0x1d55d18, 0x43)
>         /usr/local/go/src/runtime/debug/stack.go:24 +0x79
> github.com/cockroachdb/cockroach/pkg/util/syncutil.ThresholdLogger.func1(0x2630a482)
>         /go/src/github.com/cockroachdb/cockroach/pkg/util/syncutil/timedmutex.go:65 +0xe1
> github.com/cockroachdb/cockroach/pkg/util/syncutil.(*TimedMutex).Unlock(0xc420283478)
>         /go/src/github.com/cockroachdb/cockroach/pkg/util/syncutil/timedmutex.go:92 +0x80
> github.com/cockroachdb/cockroach/pkg/storage.(*Store).RemoveReplica(0xc420378a80, 0xc420283400, 0x1, 0x270bef0, 0x0, 0x0, 0xc4221a3800, 0x2d, 0x30, 0xc420d65e60, ...)
>         /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:1958 +0x105
> github.com/cockroachdb/cockroach/pkg/storage.(*replicaGCQueue).process(0xc420126df0, 0x7f5edb8c22e8, 0xc4228a88a0, 0x1486c8e8335d2290, 0x0, 0xc420283400, 0xc420d9a000, 0x19, 0x20, 0x0, ...)
>         /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_gc_queue.go:189 +0x54c
> github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processReplica(0xc4201d6690, 0x7f5edb8c1780, 0xc4221a33e0, 0xc420283400, 0xc420014f00, 0x0, 0x0)
>         /go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:541 +0x415
> github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1.2()
>         /go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:473 +0xa2
> github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTask(0xc420492090, 0xc422689e68, 0x0, 0x0)
>         /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:224 +0x100
> github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1()
>         /go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:477 +0x321
> github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420492090, 0xc42091e1c0)
>         /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x7d
> created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
>         /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x66
> E161114 02:27:08.146044 63 storage/queue.go:568  [n1,timeSeriesMaintenance,s1,r145/5:/System/tsd/cr.store.rocksdb.…] [n1,s1,r145/5:/System/tsd/cr.store.rocksdb.…]: could not obtain lease: range 145 was not found

- What did you do?
nothing

- What did you expect to see?
don't know

- What did you see instead?

**Comment by petermattis** [comment]
Hi @youngl98,

Thanks for the report. This is debug logging to help us track down the causes of holding mutexes for excessively long durations.

**Comment by youngl98** [comment]
Thanx for the update .  Closing the issue
