### ISSUE TITLE
spanconfigsplitterccl: TestDataDriven is brittle (perhaps due to weakness in spanconfigtestcluster? unsure)

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#106818]
Informs #76378 

**Describe the problem**

When `TestDataDriven` is run with a random test tenant server assigned, the test crashes with a nil pointer exception.

It's unclear what is happening. 

**To Reproduce**

Replace the use of `TestDoesNotWorkWithSecondaryTenantsButWeDontKnowWhyYet` by `TestTenantAlwaysEnabled` and run the test.

**Expected behavior**

From a **test quality** perspective, if the test code lands in an unsupported configuration it should fail with `t.Fatal` not with a crash.

Jira issue: CRDB-29728

**Comment by knz** [comment]
Ditto in spanconfigsqltranslatorccl.

**Comment by rafiss** [comment]
@andrewbaptist I noticed you moved this to the SQL Foundations team. Could you provide a few more details? I don't think our team has worked on this test before, but if the error is pointing towards something in the SQL Foundations area we can take a look.
