### ISSUE TITLE
multitenant: `PartitionSpans()` does not observe scattered leaseholders after `ALTER TABLE ... SCATTER`

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#106825]
I observe the following unexpected behavior in this [branch](https://github.com/cockroachdb/cockroach/pull/106767) where I deflake `TestTenantStreamingMultipleNodes`.

After an **app tenant** successfully calls `ALTER TABLE SPLIT ... ; ALTER TABLE SCATTER ...`  on a table, a **system tenant** dsp.PartitionSpans() call on the app tenant key span observes the split points but not the scattered leaseholders, i.e. it returns that a single node is "responsible" for the whole tenant key span. I observe this behavior even after inserting a 5 second sleep between the scatter call and when the system tenant calls `PartitionSpans()` during the `CREATE TENANT ... FROM REPLICATION STREAM`. If `dsp.PartitionedSpans()` does not return multiple nodes, this test will fail here:https://github.com/cockroachdb/cockroach/blob/8026bdf599611f4c978437d382755ad2493a2a8b/pkg/ccl/streamingccl/streamingest/replication_stream_e2e_test.go#L705

Funny enough, the problem goes away if the app tenant calls `SHOW RANGES FROM DATABASE d WITH DETAILS` between the `SCATTER` and the `partitionedSpans` call.

To reproduce this red-green behavior, run the following on your gceworker:

`./dev test pkg/ccl/streamingccl/streamingest -f TestTenantStreamingMultipleNodes --stress --cpus=8`

This should pass indefinitely on the latest sha in that[ branch ](https://github.com/cockroachdb/cockroach/pull/106767)(with the `SHOW RANGES` call), and should fail after a few runs on the second commit (with the 5 second sleep) 

Happy to provide additional context on this test.

Jira issue: CRDB-29732

**Comment by knz** [comment]
This looks like a stale entry in the range descriptor cache, that gets refreshed when SHOW RANGES WITH DETAILS asks it to do some extra work.

This is a KV issue.

**Comment by andrewbaptist** [comment]
Looking at this a little bit, it is not clear to me that this is a problem. If a scatter request happens, the client/range cache won't know about it until it needs to "use" the ranges. Calling something like `SELECT COUNT(*) FROM d.scattered` will force usage of the range and it will then detect and correctly update its cache. We intentionally don't proactively update our cache. There is possibly an argument to be made that `SHOW RANGES` should bypass the cache and read directly from KV every time, but I'm not sure if that is the desired behavior.

**Comment by knz** [comment]
It feels like it's PartitionSpan that is using the cache and SHOW RANGES is not.
I feel like the solution here is to refresh the cache in the test so that PartitionSpans sees the updated ranges.

**Comment by andrewbaptist** [comment]
I agree it is PartionSpans not the SHOW RANGES as I initially thought. I'm trying to figure out if we should try and "intercept" a `SCATTER` or `SPLIT AT` command and evict from the cache any ranges that overlap. That would help the "common" case where the same client that issued the split/scatter next issues a command that expects to see the impact on SQL planning, but I'm not sure its worth the effort.

**Comment by arulajmani** [comment]
> I agree it is PartionSpans not the SHOW RANGES as I initially thought. I'm trying to figure out if we should try and "intercept" a SCATTER or SPLIT AT command and evict from the cache any ranges that overlap. That would help the "common" case where the same client that issued the split/scatter next issues a command that expects to see the impact on SQL planning, but I'm not sure its worth the effort.

I agree, this doesn't feel worth the effort. These operations are rare enough and the range cache trends in the right direction. 

Does simply wrapping the distsql query inside of a succeeds soon help? Or, maybe running the query twice -- once to prime the cache and another time to actually do the test.

**Comment by andrewbaptist** [comment]
In this specific test, the test is creating a C2C replication and wants to see it run in parallel from all nodes in the source cluster to the destination cluster. Because it uses the DistSQL which relies on cached data in `PartitionSpans` to make the streaming decisions it makes bad decisions and all the streaming happens from the first node.

The test "passes" as all the data is correctly transferred, but the data uses the old cache.  But it fails when it tries to verify that multiple client nodes were used. 

I will take a look at @knz suggestion to add a "EvictRange" test interface.

**Comment by andrewbaptist** [comment]
Closing this issue. Adding the interface and being able to call this effectively would require a lot of rework. Short term the answer of just scanning the ranges using `SHOW RANGES` seems effective for tests and this isn't something we expect to see in real deployments.

**Comment by knz** [comment]
@msbutler do you feel you have enough information to make these tests robust?
