### ISSUE TITLE
kvprober: flake in TestProberDoesReadsAndWrites

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#106835]
Found here on an unrelated PR: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/10915083?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildTestsSection=true

```
=== RUN   TestProberDoesReadsAndWrites/all_ranges_are_unavailable_for_Gets_only
    kvprober_integration_test.go:167:
          Error Trace:  github.com/cockroachdb/cockroach/pkg/kv/kvprober_test/pkg/kv/kvprober/kvprober_integration_test.go:167
          Error:        Not equal:
                        expected: 10
                        actual  : 11
          Test:         TestProberDoesReadsAndWrites/all_ranges_are_unavailable_for_Gets_only
    --- FAIL: TestProberDoesReadsAndWrites/all_ranges_are_unavailable_for_Gets_only (1.79s)
```

Jira issue: CRDB-29735

**Comment by shralex** [comment]
Hi @joshimhoff, can you take a look ?

**Comment by joshimhoff** [comment]
Yes! Will fix promptly. Made a small test change in https://github.com/cockroachdb/cockroach/pull/104365/ that probably has led to this flake.

**Comment by joshimhoff** [comment]
https://github.com/cockroachdb/cockroach/pull/106828
