### ISSUE TITLE
serverccl: `TestAdminAPIDataDistributionPartitioning` fails on secondary tenants

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#106897]
Epic CRDB-38970
Issue uncovered by #106898.
Informs #76378.

**Describe the problem**

When `TestAdminAPIDataDistributionPartitioning` is modified to use a secondary tenant, the API fails to return the right zone config results. This suggests that the underlying "data distribution" HTTP API does not function properly on secondary tenants.

**To Reproduce**

On top of the branch from #106898, modify the test and replace `TestIsForStuffThatShouldWorkWithSecondaryTenantsButDoesntYet` by `TestTenantAlwaysEnabled`.

**Expected behavior**

The test should work the same regardless of whether a secondary tenant is used or not.
(The test should succeed when the parameter `DefaultTestTenant`  is omitted entirely, which makes it default to `TestTenantProbabilistic`).

Jira issue: CRDB-29754

**Comment by knz** [comment]
Agreed, this is not CY work.

**Comment by shubhamdhama** [comment]
This should be fixed with #128578
