### ISSUE TITLE
kvserver: avoid ignored snapshot when snap index < raft's PendingSnapshot index

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#106813]
**Describe the problem**

See https://github.com/cockroachdb/cockroach/blob/2b91c3829270eb512c5380201c26a3d838fc567a/pkg/kv/kvserver/raft_snapshot_queue.go#L131-L144

and https://github.com/etcd-io/raft/blob/4dc30c9d116ec5297b5afd30c9f6663a9dafc191/raft.go#L1446-L1457

We can fix this by picking up https://github.com/etcd-io/raft/pull/84 and then we should be able to remove the workaround in the first snippet, and together with https://github.com/cockroachdb/cockroach/pull/106793 that _should_ result in a system in which snapshots are never wasted (except in the one remaining case: a log truncation cuts the snapshot off from the leader's log, which in itself requires existing protection mechanisms to fail[^1]).

[^1]: https://github.com/cockroachdb/cockroach/blob/ed6f26856fbfbab3eab4f062621e0db1031bd612/pkg/kv/kvserver/replica_raft.go#L1879-L1896

Jira issue: CRDB-29725

Epic CRDB-32846

**Comment by tbg** [comment]
This can be closed after #104588, see https://github.com/cockroachdb/cockroach/issues/104588#issuecomment-1649420281

**Comment by tbg** [comment]
Assuming sufficient validation, can also close https://github.com/cockroachdb/cockroach/issues/87553.

**Comment by erikgrinaker** [comment]
I'll pick up https://github.com/etcd-io/raft/pull/84 and get it in behind an opt-in flag.
