### ISSUE TITLE
kv: TestGetSSTableMetricsSingleNode flaked under race on master

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#106817]
See failure [here.](https://teamcity.cockroachdb.com/viewLog.html?buildId=10905204&buildTypeId=Cockroach_BazelExtendedCi)

Jira issue: CRDB-29727

**Comment by miraradeva** [comment]
@msbutler is this a KV test? Sorry, I'm fairly new to how the ownership of these tests works. Trying to pick one to work on.

**Comment by msbutler** [comment]
ah, i took a closer look at git blame and it looks like @RahulAggarwal1016 added this a little while ago. Reassigning to him.
