### ISSUE TITLE
c2c: TestTenantStreamingUnavailableStreamAddress flaked on master

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#106865]
See flake [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=10918917&buildTypeId=Cockroach_BazelEssentialCi)

Jira issue: CRDB-29745

**Comment by lidorcarmel** [comment]
stressed for 2 hours, didn't fail, closing.

**Comment by lidorcarmel** [comment]
and no artifacts so not much to do without a repro.

**Comment by sumeerbhola** [comment]
seems to be flaking on my PR https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/10945736?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildTestsSection=true in case you find anything useful in artifacts

**Comment by yuzefovich** [comment]
I hit this [too](https://teamcity.cockroachdb.com/viewLog.html?buildId=10947569&buildTypeId=Cockroach_BazelEssentialCi) on an unrelated PR.

**Comment by mgartner** [comment]
Hit here too: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/10948970?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

```
=== RUN   TestTenantStreamingUnavailableStreamAddress
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/90c1b75d835f45b8488807abb5b1092d/logTestTenantStreamingUnavailableStreamAddress2608397732
    test_log_scope.go:79: use -show-logs to present logs inline
    replication_stream_e2e_test.go:514: error executing 'SELECT * FROM d.t1': pq: failed to connect to n1 at 127.0.0.1:39983: initial connection heartbeat failed: grpc: connection error: desc = "transport: error while dialing: dial tcp 127.0.0.1:39983: connect: connection refused" [code 14/Unavailable]
    panic.go:522: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/90c1b75d835f45b8488807abb5b1092d/logTestTenantStreamingUnavailableStreamAddress2608397732
--- FAIL: TestTenantStreamingUnavailableStreamAddress (39.34s)
```
