### ISSUE TITLE
sql: speed up TestValidationWithProtectedTS under multi-tenancy

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#106960]
When #106883 merges, `TestValidationWithProtectedTS` can be executed against the default test tenant. However, it seems like the test is noticeably slower in this setup. This issue tracks investigating whether it is expected and speeding up the test if possible.

Jira issue: CRDB-29777
Epic: CRDB-18499

**Comment by rafiss** [comment]
Do you have data on how much slower? Curious how high we should prioritize this.

**Comment by yuzefovich** [comment]
I ran the test a few times w/ and w/o the default test tenant, and the run times vary significantly, but it seems like it goes up from less than a minute to 3-5 minutes.

**Comment by yuzefovich** [comment]
Some concrete numbers: running `./dev test pkg/sql -f=TestValidationWithProtectedTS -v --stream-output --show-logs --ignore-cache --stress --cpus=5` on M1:
- no test tenant:
```
15 runs so far, 0 failures, over 2m50s
```
- with test tenant
```
5 runs so far, 0 failures, over 6m0s
```

**Comment by knz** [comment]
Is it still slow if we reduce the closed ts interval to 100ms (from its 3s default)?

**Comment by yuzefovich** [comment]
> Is it still slow if we reduce the closed ts interval to 100ms (from its 3s default)?

Reducing `kv.closed_timestamp.target_duration` doesn't seem to make any impact on this test.

**Comment by DrewKimball** [comment]
Saw a timeout in CI running with a multitenant configuration: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/11184495?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

**Comment by cucaroach** [comment]
Pile on: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/11195030?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

**Comment by adityamaru** [comment]
anotha one: https://teamcity.cockroachdb.com/viewLog.html?buildId=11197733&buildTypeId=Cockroach_BazelEssentialCi

**Comment by rafiss** [comment]
@fqazi can you work on this after your current issues, since I think you have the most context from https://github.com/cockroachdb/cockroach/pull/106181 ?

**Comment by fqazi** [comment]
Yeah, let me dig into this since I'm freeing up

**Comment by rafiss** [comment]
I found that it it's much slower when running with metamorphic constants. This random seed reproduces the slowness (238 seconds on my laptop):
```
./dev test pkg/sql -v -f=TestValidationWithProtectedTS --ignore-cache -- --test_env='COCKROACH_TEST_TENANT=true' --test_env=COCKROACH_INTERNAL_DISABLE_METAMORPHIC_TESTING=false --test_env=COCKROACH_RANDOM_SEED=1740493024399897407
```

If I apply this diff, the same command takes 160 seconds on my laptop.
```
diff --git a/pkg/sql/row/kv_batch_fetcher.go b/pkg/sql/row/kv_batch_fetcher.go
index 832915b804f..4f7118e128d 100644
--- a/pkg/sql/row/kv_batch_fetcher.go
+++ b/pkg/sql/row/kv_batch_fetcher.go
@@ -51,11 +51,7 @@ func getKVBatchSize(forceProductionKVBatchSize bool) rowinfra.KeyLimit {
 	return defaultKVBatchSize
 }
 
-var defaultKVBatchSize = rowinfra.KeyLimit(util.ConstantWithMetamorphicTestValue(
-	"kv-batch-size",
-	int(rowinfra.ProductionKVBatchSize), /* defaultValue */
-	1,                                   /* metamorphicValue */
-))
+var defaultKVBatchSize = rowinfra.ProductionKVBatchSize
 
 // sendFunc is the function used to execute a KV batch; normally
 // wraps (*kv.Txn).Send.
```

I thought that using the `ForceProductionValues` would fix it too, but for some reason this does not help with the slowness.
```
			SQLEvalContext: &eval.TestingKnobs{
				ForceProductionValues: true,
			},
```
