### ISSUE TITLE
sql: support APPLICATION_NAME variable

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#10694]
Several SQL clients that support postgres [(including the popular SQL Workbench/J](http://www.sql-workbench.net/)) try to set the `APPLICATION_NAME` variable when they start up to improve query logging on the server. Cockroach does not recognize the existence of this variable, leading these clients to fail to connect.

It would be nice if most database clients that work with postgres also work with Cockroach. We should add support for `APPLICATION_NAME`, even if it's practically a write-only variable that doesn't affect any internals.

**Comment by a6802739** [comment]
@jordanlewis， I could have a look on it.

**Comment by yznming** [comment]
@jordanlewis I can try to fix it.

**Comment by knz** [comment]
@yznming: yes you can!

For this let's make the implementation simple and just recognize the statement (accept the variable name in `sql/set.go`) without doing anything. Just like what we do already for `EXTRA_FLOAT_DIGITS`.

**Comment by yznming** [comment]
@knz got it. thx
