### ISSUE TITLE
changefeedccl: enable declarative schema changes in tests

### ISSUE THREAD

**Issue by jayshrivastava** [cockroachdb/cockroach#106906]
`disableDeclarativeSchemaChangesForTest` is set in a few tests even though declarative schema changes are used in production. We should remove this and alter our tests to reflect the correct behavior. 

Jira issue: CRDB-29758

Epic CRDB-9179

**Comment by jayshrivastava** [comment]
@Xiang-Gu Pointed out that the declarative schema change can always be toggled off via a cluster setting. We should have them run with both schema changers instead of only the declarative one.

**Comment by miretskiy** [comment]
@jayshrivastava any updates on this issue?

**Comment by jayshrivastava** [comment]
Yeah I plan to close it via https://github.com/cockroachdb/cockroach/pull/108043. I'll go ahead and publish that PR now.

**Comment by miretskiy** [comment]
Nice.
