### ISSUE TITLE
serverccl: TestVerifyPassword/some_admin_with_empty_password_should_fail fails with secondary tenants

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#106903]
Epic: CRDB-26687
Emerged from #106905.
Informs #76378.

**Describe the problem**

The sub-test `some_admin_with_empty_password_should_fail` in `TestVerifyPassword` fails when pointed to a secondary tenant.

This is surprising (and possibly indicative of a security bug) given the other sub-tests pass successfully.

**To Reproduce**

On top of the #106905 branch,  modify the test to replace `TestDoesNotWorkWithSecondaryTenantsButWeDontKnowWhyYet` by `TestTenantAlwaysEnabled`.

**Expected behavior**

The test should work the same whether or not a secondary tenant is used.
In an ideal world the parameter `DefaultTestTenant` is omitted and the default value `Probabilistic` can be used.

Jira issue: CRDB-29757

**Comment by DrewKimball** [comment]
Just saw this flake: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsGcpLinuxX8664BigVm_CclUnitTests/11000472?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

**Comment by DrewKimball** [comment]
Another here: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsGcpLinuxX8664BigVm_CclUnitTests/11000840?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

**Comment by yuzefovich** [comment]
Taking a look since I recently touched it.

**Comment by yuzefovich** [comment]
I can't repro on master. It looks likely it's caused by #107235 that was in the bors batch.

**Comment by DrewKimball** [comment]
>I can't repro on master. It looks likely it's caused by https://github.com/cockroachdb/cockroach/pull/107235 that was in the bors batch.

Didn't see that, good catch.
