### ISSUE TITLE
storage: replica scanner queue pacing is not flexible

### ISSUE THREAD

**Issue by spencerkimball** [cockroachdb/cockroach#10693]
The scanner is nice because it moves along ahead of potentially slow queues, always adding new replicas to keep only the highest priority replicas in each queue's priority heap.

So just setting a really slow scanner to avoid re-processing a given replica (say for time series or consistency checks) means that you have no way to find out about a replica whose state indicates it should be queued for some other reason. While we add replicas manually in cases where it makes sense, that mechanism doesn't survive restarts.

I'm not comfortable with consistency checks constantly underway in a production clusters. They should probably happen every 10 days or 30 days once proposer-evaluated KV and some months of good stability are behind us. However, our current scanner mechanism only allows us to slow down the rate at which we consider a replica, as opposed to slowing down the rate that any replica is re-processed. They're different.

I think we should have one scanner, as it was originally designed, and then a means to limit how fast ranges are re-processed.

**Comment by spencerkimball** [comment]
+cc @petermattis 

I'm not far from a solution and I'd hate to just throw away all of the work I already did in #10665

**Comment by bdarnell** [comment]
I agree that the current scanner/queue system is flawed, but I'm not following your example. The consistency checker queue always schedules every range at equal priority, so running a slower scanner for the consistency checker seems more or less equivalent to any other way we could rate limit that queue. I see your point for other queues with more interesting shouldQueue/priority implementations, though.

**Comment by spencerkimball** [comment]
The consistency queue as an example isn't as interesting as time series could be, for example. Right now we don't attach any priority to time series but we probably should. If we set a priority proportional to how big a task the `DeleteRange` cleanup is likely to be, we could process in the order that frees up the most space fastest.

We currently don't have a metric which would suggest priority for consistency checks, but I wouldn't be surprised if one comes along at some point.

**Comment by bdarnell** [comment]
Maybe, but I think it's telling that the first two uses you've come up with for this minInterval feature are ones where we don't do anything with priority. I think this is an argument for two different kinds of queues/scanners/whatevers: a priority queue where we expect to see significant value from repolling a prioritization function more frequently than we can process ranges, and a simpler non-prioritized queue that just iterates over everything and emphasizes processing everything at a stable frequency.

**Comment by spencerkimball** [comment]
As I mentioned in #10665 comments, the consistency check in particular actually benefits from a priority. Specifically one computed from the time since last processing.

In your suggested update to have "a non-prioritized queue that just iterates over everything ... at a stable frequency", you'd need a last processed time anyway.

**Comment by bdarnell** [comment]
But if it iterates over everything in a stable order, then you naturally hit everything in order of the last processed time. My thinking is that we'd pick a random range to start with at process start and then iterate in order from there. It's true that this isn't persistent so you wouldn't be guaranteed to hit everything if your nodes restart frequently, but I don't think that's worth the cost of making this state persistent.

**Comment by petermattis** [comment]
@spencerkimball The flexible pacing was implemented. Is there anything else to do here?

**Comment by spencerkimball** [comment]
This is done until and unless we decide something isn't working with the scanner / queue interaction.
