### ISSUE TITLE
server: `TestAdminAPIStatementDiagnosticsBundle` does not work with secondary tenants

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#106930]
Epic: CRDB-26687
Issue uncovered by  #106931.
Informs #76378.

**Describe the problem**

When `TestAdminAPIStatementDiagnosticsBundle` is modified to use a secondary tenant, the test fails with a 404 error on one of the API endpoints. This suggests that the underlying "stmt bundle retrieval" HTTP API does not function properly on secondary tenants.

**To Reproduce**

On top of the branch from #106931, modify the test and replace `TestDoesNotWorkWithSecondaryTenantsButWeDontKnowWhyYet` by `TestTenantAlwaysEnabled`.

**Expected behavior**

The test should work the same regardless of whether a secondary tenant is used or not.
(The test should succeed when the parameter `DefaultTestTenant`  is omitted entirely, which makes it default to `TestTenantProbabilistic`).

Jira issue: CRDB-29768

**Comment by dhartunian** [comment]
Test passes on my machine. Am I missing other edits?

```
~/go/src/github.com/cockroachdb/cockroach 20230717-diag-api* ≡
❯ ./dev test pkg/server --filter=TestAdminAPIStatementDiagnosticsBundle
$ bazel test pkg/server:all --test_env=GOTRACEBACK=all --test_filter=TestAdminAPIStatementDiagnosticsBundle --test_sharding_strategy=disabled --test_output errors
INFO: Invocation ID: 1b098f80-2c19-4b66-aadf-4a5471e29f10
INFO: Analyzed 2 targets (0 packages loaded, 0 targets configured).
INFO: Found 1 target and 1 test target...
INFO: Elapsed time: 0.989s, Critical Path: 0.31s
INFO: 3 processes: 2 remote cache hit, 1 internal.
//pkg/server:server_test                                        (cached) PASSED in 7.2s

Executed 0 out of 1 test: 1 test passes.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
INFO: Build Event Protocol files produced successfully.
INFO: Build completed successfully, 3 total actions

~/go/src/github.com/cockroachdb/cockroach 20230717-diag-api* ≡
❯ git diff
diff --git a/pkg/server/admin_test.go b/pkg/server/admin_test.go
index 5ec9b1d34a4..010f8771e9c 100644
--- a/pkg/server/admin_test.go
+++ b/pkg/server/admin_test.go
@@ -367,7 +367,7 @@ func TestAdminAPIStatementDiagnosticsBundle(t *testing.T) {
                // tenants already. Yet this test fails if we enable the test
                // tenant here, with a 404 error on one of the API endpoints. This
                // needs to be investigated.
-               DefaultTestTenant: base.TestDoesNotWorkWithSecondaryTenantsButWeDontKnowWhyYet(106930),
+               DefaultTestTenant: base.TestTenantAlwaysEnabled,
        })
        defer s.Stopper().Stop(context.Background())


```

**Comment by knz** [comment]
After the refactor i merged yesterday,  this test doesn't fail anymore! :tada: 
(I don't know why exactly, but oh well. Happy nonetheless we have one less thing to look at.)

**Comment by knz** [comment]
Oh lol I spoke too soon.

I'm getting a panic now. I'll clarify in the original PR.

**Comment by knz** [comment]
aha, we're fine after all. it's a different test that gets the panic.

**Comment by knz** [comment]
@dhartunian for your entertainment (no action needed on your part): https://github.com/cockroachdb/cockroach/pull/106931
