### ISSUE TITLE
sql/importer: TestRandomParquetExports flakes

### ISSUE THREAD

**Issue by renatolabs** [cockroachdb/cockroach#106909]
```console
./dev test ./pkg/sql/importer/ -f TestRandomParquetExports --ignore-cache --stress --cpus 16 --timeout 10m
--- FAIL: TestRandomParquetExports (2.39s)
    test_log_scope.go:167: test logs captured to: /tmp/cockroach/_tmp/73dfce30b9a5630b1b4dabed3c94b32c/logTestRandomParquetExports3282656100
    test_log_scope.go:81: use -show-logs to present logs inline
    exportparquet_test.go:257: exporting as parquet from random table with schema: 
         [["t ab le1" CREATE TABLE public."t ab le1" (
                rowid INT8 NOT VISIBLE NOT NULL DEFAULT unique_rowid(),
                CONSTRAINT "t ab le1_pkey" PRIMARY KEY (rowid ASC)
        )]]
    exportparquet_test.go:104: 
                Error Trace:    github.com/cockroachdb/cockroach/pkg/sql/importer_test/pkg/sql/importer/exportparquet_test.go:104
                                                        github.com/cockroachdb/cockroach/pkg/sql/importer_test/pkg/sql/importer/exportparquet_test.go:267
                Error:          Received unexpected error:
                                strconv.Atoi: parsing "": invalid syntax
                Test:           TestRandomParquetExports
    panic.go:522: -- test log scope end --
FAIL
I230717 13:48:59.298028 1 (gostd) testmain.go:261  [-] 1  Test //pkg/sql/importer:importer_test exited with error code 1


ERROR: exit status 1

40 runs completed, 1 failures, over 11s
```

Also seen in CI: https://teamcity.cockroachdb.com/viewLog.html?buildId=10919135&buildTypeId=Cockroach_BazelEssentialCi. 

Jira issue: CRDB-29760

**Comment by yuzefovich** [comment]
The failure can be reproduced with:
```
./dev test ./pkg/sql/importer/ -f TestRandomParquetExports -- --test_env=COCKROACH_RANDOM_SEED=-8479984470487885576
```
It actually hits `missing type oid metadata. ensure the writer is configured to write reader metadata. see NewWriter() and buildutil.CrdbTestBuild` assertion error being introduced in #106939.

**Comment by jayshrivastava** [comment]
`missing type oid metadata. ensure the writer is configured to write reader metadata. see NewWriter() and buildutil.CrdbTestBuild` will be hit every time unless `buildutil.CrdbTestBuild` is true. This requires you to pass `--crdb_test` to `./dev test` when running it locally.

**Comment by yuzefovich** [comment]
I believe `crdb_test` flag is passed implicitly for all `dev test` invocations (unless `--crdb_test_off` is included).

**Comment by yuzefovich** [comment]
Sorry, I think my [comment](https://github.com/cockroachdb/cockroach/issues/106909#issuecomment-1638782360) was misleading: I hit that error when running via GoLand debugger in which case `crdb_test` wasn't specified. When running the test via the terminal, it fails with:
```
    exportparquet_test.go:104: 
        	Error Trace:	github.com/cockroachdb/cockroach/pkg/sql/importer_test/pkg/sql/importer/exportparquet_test.go:104
        	            				github.com/cockroachdb/cockroach/pkg/sql/importer_test/pkg/sql/importer/exportparquet_test.go:267
        	Error:      	Received unexpected error:
        	            	strconv.Atoi: parsing "": invalid syntax
        	Test:       	TestRandomParquetExports
    panic.go:522: -- test log scope end --
```
In the debugger (before #106939) I saw that `typFamiliesMeta` was `nil`. In any case, @jayshrivastava you probably have the most context to investigate this further.

**Comment by jayshrivastava** [comment]
Ack ty. I can repro Renato's error via the terminal with the random seen. One day we'll figure out how to set `crdb_test` in the ide :)
