### ISSUE TITLE
test: `maybe_stressrace` does not target unskipped tests

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#106914]
In this[ pr,](https://github.com/cockroachdb/cockroach/pull/106853) I unskip `TestStreamingAutoReplan`, but the `maybe_stressrace` job does not stress this test. See job history[ here](https://teamcity.cockroachdb.com/viewType.html?buildTypeId=Cockroach_Ci_Tests_MaybeStressrace&branch_Cockroach_Ci_Tests=106853&tab=buildTypeStatusDiv) (note those fast build times) and an example of the [build log](https://teamcity.cockroachdb.com/viewLog.html?buildId=10941829&buildTypeId=Cockroach_Ci_Tests_MaybeStressrace&tab=buildLog&branch_Cockroach_Ci_Tests=106853). (See the "golang tests not found log line". ) (See the "golang tests not found "). 

My [read](https://cockroachlabs.slack.com/archives/C05B1BPMJLE/p1689249153328559?thread_ts=1689241930.883679&cid=C05B1BPMJLE) of our exended ci code is that this test should have been stressed. This bug could be causing flaky tests leaking onto master. 

Jira issue: CRDB-29764

**Comment by rickystewart** [comment]
Looks like `github-pull-request-make` has logic explicitly for this, but it only recognizes `t.Skip()` rather than `skip.(whatever)`. I'll make a little PR to add this.
