### ISSUE TITLE
sql: add current_schema built-in function

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#10704]
This is needed for Hibernate.

Note that Postgres provides two ways to use `current_schema`:

1. `SELECT current_schema;`
2. `SELECT current_schema();`

Hibernate only seems to use the latter, so that's what we'll support for now.

**Comment by tazjin** [comment]
(Note: Let me know if I should file a new issue for this)

This fails for me still on an application ([Keycloak](http://www.keycloak.org/)) that [according to its documentation](https://keycloak.gitbooks.io/documentation/server_installation/topics/database.html) uses Hibernate.

Using Cockroach 1.0 and Keycloak, I get:

```
Error executing SQL select current_schema: ERROR: column name "current_schema" not found
```

And that error seems to stem from `SELECT current_schema;` (not `()`):

```
root@cockroachdb-public:26257/keycloak> select current_schema();
+------------------+
| current_schema() |
+------------------+
| keycloak         |
+------------------+
(1 row)
root@cockroachdb-public:26257/keycloak> SELECT current_schema;
pq: column name "current_schema" not found
```
