### ISSUE TITLE
sql: bikeshed on renaming ColumnType, ColumnType_Kind, ColumnType_Kind_value

### ISSUE THREAD

**Issue by arjunravinarayan** [cockroachdb/cockroach#10705]
`ColumnType`, `ColumnType_Kind`, `ColumnType_Kind_value` are badly named. It abuses the term `Kind` (`ColumnType_Kind` is not a kind[1]), it is just the base type). `ColumnType` is currently a wrapper around `ColumnType_Kind` with some additional metadata specific to certain types (for instance, `DECIMAL` and `FLOAT` use the `Precision` metadata).

`ColumnType_Kind_value` is an unfortunate effect of the fact that any `XXX` enum protos generate maps for `XXX_name` and `XXX_value`, but we should choose proto names being mindful of the fact that this is going to happen. and that it will be confusing to have `_value` appended to something named `XXXType_Kind`, because `XXXType_Kind_value` starts to sound like a cruel joke on type theorists.

I propose that we rename the protos in the following way:

Rename `ColumnType_Kind` -> `ColumnBaseType`. To achieve this, we move the `enum` proto in `sql/structured.proto` which is currently defined inside `ColumnType` outside (otherwise it is saddled with the `ColumnType_` prefix).

`ColumnType` stays the same.

Sadly, we are saddled with the `_value` suffixes, but `ColumnBaseType_value` is somewhat acceptable.

This is somewhat cleaner. A column has a `ColumnType`, which has a `ColumnBaseType` (`INT`, `DECIMAL`, `DATE`, etc.), which is potentially annotated with some other information, such as a `Precision`, or a `Width`. Sadly, this isn't statically type checkable as we don't have option types. Ideally we'd have the equivalent of the following OCaml type: 
`type ColumnType = BOOL | INT of width | FLOAT of precision | DECIMAL of width * precision | ...`

If anyone has strong objections to such a renaming, or a better proposal with better names, or some secret protobuf powers that would get us option times, I'd be happy to hear it. I am happy to carry out the renaming myself once we have consensus. I hope that we don't have too much bikeshedding on this...

cc @knz @RaduBerinde @paperstreet @andreimatei 

[1]: https://en.wikipedia.org/wiki/Kind_(type_theory)

**Comment by RaduBerinde** [comment]
Sounds good to me. I wouldn't worry about the XXX_values stuff, that is
mostly internal to protobuf code (we use it in a couple of places for
convenience but it shouldn't be a factor in naming).

**Comment by knz** [comment]
Add these:

Package parser -> package lang

Normalize -> simplify

Analyze ( package SQL)-> normalize



-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by arjunravinarayan** [comment]
Thanks for the additional suggestions, @knz, I will do those as well! I'm just going to cc @nvanbenschoten and @dt to see if they have any objections before I begin working on a PR that does all of this renaming.

**Comment by knz** [comment]
Also don't forget to do this in separate commits, so we don't mix file renames with changes inside the files :)
