### ISSUE TITLE
roachtest/cdc: remove dependency on golang

### ISSUE THREAD

**Issue by jayshrivastava** [cockroachdb/cockroach#107088]
Do we need to install Golang here? Are there any steps in this roachtest which are unnecessary? https://github.com/cockroachdb/cockroach/blob/87a4282030ea50f74ac09eeed5630fec358c0e74/pkg/cmd/roachtest/tests/cdc.go#L187

This step can cause the test to flake as seen in https://github.com/cockroachdb/cockroach/issues/107061

Jira issue: CRDB-29885

Epic CRDB-9179

**Comment by amruss** [comment]
Maybe this is an ask for the test-infra team? Flake/failure to install should be treated as a retryable error

**Comment by amruss** [comment]
Or infra should build/distribute binaries

**Comment by jayshrivastava** [comment]
Golang is not the only issue. We also install confluent / kafka etc.

**Comment by amruss** [comment]
We could also make it more obvious on failures that it was an installer failure, that would save a lot of time

**Comment by jayshrivastava** [comment]
I think this is okay to close. Maybe we can skip the installation step by using something which is already installed, but whatever is installed might change in the future. With https://github.com/cockroachdb/cockroach/pull/107271, installing go should be more durable, so we should see less test failures due to that. Also, even if the test fails due to installing go, we will get a clear error message.
