### ISSUE TITLE
kvcoord/rangefeed: consider mux rangefeed mixed-version safety

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#107158]
In #105270, we enabled mux rangefeeds by default. However, these have several known issues. We should consider gating the default value on a cluster version, to ensure we don't trigger known bugs in previous versions.

Jira issue: CRDB-29921

Epic CRDB-26372

**Comment by tbg** [comment]
cc @cockroachdb/cdc since Erik typo'ed

**Comment by erikgrinaker** [comment]
Mux has been disabled by default: #109165
