### ISSUE TITLE
sql.stats.response.show_internal.enabled does not work with activity tables

### ISSUE THREAD

**Issue by j82w** [cockroachdb/cockroach#107186]
The statement_activity and transaction_activity tables are the cached top queries from statement_statistics. The activity tables do not include internal queries in the cache. If `sql.stats.response.show_internal.enabled` the activity page will not show any results from the internal tables. There should be a check [here](https://github.com/cockroachdb/cockroach/blob/30acaf93015008a672667c0d3fdc00ac95f446a6/pkg/server/combined_statement_stats.go#L102) if the cluster is true fall back to the statement_statistics table. 

A workaround is to query more than the top 500 results. 

Jira issue: CRDB-29937

**Comment by maryliag** [comment]
No longer a priority
