### ISSUE TITLE
sql: support tsrange and tstzrange type

### ISSUE THREAD

**Issue by giangpham712** [cockroachdb/cockroach#107256]
**Is your feature request related to a problem? Please describe.**

Support timestamp range types:

tsrange — Range of timestamp without time zone
tstzrange — Range of timestamp with time zone

**Additional context**
This type not being supported currently affects a number of tests in efcore.pg library

Jira issue: CRDB-29967

**Comment by rafiss** [comment]
I'll close this issue in favor of https://github.com/cockroachdb/cockroach/issues/27791. Please watch that for any future updates, but right now we don't have plans to work on this.
