### ISSUE TITLE
kvclient/kvcoord: mux rangefeed stuck watcher is very aggressive

### ISSUE THREAD

**Issue by stevendanna** [cockroachdb/cockroach#107261]
**Describe the problem**

_This is mildly speculative based on some incomplete code reading and observing some roachtest failures._

The mux rangefeed code restarts rangefeeds for inactivity based on whether or not the resolved timestamp for that feed is further behind realtime than the configured threshold.

https://github.com/cockroachdb/cockroach/blob/0c9f44f71afc75f8ee047399f7de81839e3104d1/pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go#L610-L620

This is problematic during a catch-ups can, no checkpoints are emitted until the end of the catchup scan process.  This means that the stuck threshold is also a hard limit on the time we can spend doing a catchup scan.

Jira issue: CRDB-29970

**Comment by miretskiy** [comment]
Mux rangefeed stuck watcher should be disabled; it's kinda broken.
Also, I do have a high hope that https://github.com/cockroachdb/cockroach/pull/106053 will fix stuckness once and for all.
