### ISSUE TITLE
roachtest: always pass connection info to commands

### ISSUE THREAD

**Issue by herkolategan** [cockroachdb/cockroach#107244]
There are a few places where `ssh` commands are invoked in `roachtests` that do not pass the `pgurls` or a port or any other connection info and rely on the defaults (usually `DefaultSQLPort = 26257`).

This will create problems when we start allowing custom ports and different instance types to run on different ports, or with secure clusters where more than just the connection info is required.

It's already possibly to partially recreate the issue with local clusters by creating a local cluster before running `roachtests` locally on a different local cluster. The first cluster will cause the ports of the next cluster to be at an offset and any commands assuming defaults will fail.

The change required here is to find all commands or areas that rely on defaults for connecting to be updated.
An example of a recent change doing the same: https://github.com/cockroachdb/cockroach/pull/106890

As a suggestion maybe a helper function to pass information along with in a standardized form could be useful, although not all commands may take the same form of arguments.

Jira issue: CRDB-29959

**Comment by srosenberg** [comment]
Resolved by https://github.com/cockroachdb/cockroach/pull/119310
