### ISSUE TITLE
Long query planning time on large LIMIT with small table and hinted LEFT LOOKUP JOIN

### ISSUE THREAD

**Issue by leiffoged** [cockroachdb/cockroach#107290]
**Describe the problem**

Saw an interesting issue today where application code generated a large limit (`LIMIT 9007199254740991` instead of using no limit). This issue only seemed to reproduce when joining on a second table with a hinted `LEFT LOOKUP JOIN`.

The application code has since been fixed to omit the limit, but still thought this was a strange issue.

**To Reproduce**

(table/column names changed, but query is the same)

```
SELECT
  a.id, e.email
FROM
  books@author_index AS a
  LEFT LOOKUP JOIN user_accounts AS e ON e.id = a.id
    AS OF SYSTEM TIME '1689877278231790424.0000000000'
WHERE
  a.author_name = 'Steve Smith'
ORDER BY
  a.author_name DESC, a.id DESC
LIMIT
  9007199254740991
```

Takes ~800ms to generate a query plan.

```
SELECT
  a.id, e.email
FROM
  books@author_index AS a
  LEFT LOOKUP JOIN user_accounts AS e ON e.id = a.id
    AS OF SYSTEM TIME '1689877278231790424.0000000000'
WHERE
  a.author_name = 'Steve Smith'
ORDER BY
  a.author_name DESC, a.id DESC
```

Takes <1ms to generate a query plan.

There are ~88 results for both queries.

The long query planning time also goes away if I replace the hinted "LEFT LOOKUP JOIN" with a "JOIN".

Jira issue: CRDB-29979

**Comment by michae2** [comment]
@leiffoged thank you very much for filing the issue. Would you be willing to capture and share a statement diagnostics bundle for the slow planning query? That would help us reproduce the issue. It can be done in a few different ways:
- by appending `EXPLAIN ANALYZE (DEBUG)` to the beginning of the query when executed via the command line interface
- through the [diagnostics](https://www.cockroachlabs.com/docs/v23.1/ui-statements-page#diagnostics) tab of the statement fingerprint page in the DB Console

(Note that the bundle will contain detailed information about the table. If you're willing to send it, but not via GitHub, you can upload it to [our secure dropbox](https://upload.cockroachlabs.com/dropzone/michae2).)

**Comment by michae2** [comment]
@leiffoged were you ever able to get a statement bundle for this query?

If not, the schemas of `books` and `user_accounts` would help.

**Comment by michae2** [comment]
Closing for now. @leiffoged please reopen whenever you have more debugging info available.
