### ISSUE TITLE
core: improve debugging capabilities

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#10736]
It's getting more and more difficult to debug problems that involve tracing calls/requests/interactions across nodes and time, or even to see basic information easily.

We need to expose various logical parts of the system better.
For example:
* drill down into a range: See its replicas, replica status, raft status, various queues, and even better would be its history (rebalance history, split history with links to the original range)
* queue status: better listing of finished and pending work for queues
* ongoing (or particularly long-running) operations on a given range. requestz is convenient, but the entry point when debugging a problem may well be elsewhere (eg: we have a sql key experiencing issues, or an unavailable range). Listing long-running requests in a range page would make it much simpler.

This kind of work is heavily split between the admin UI (CC: @kuanluo) and code (eg: persisting information about various operations, properly extracting relevant info from raft/gossip)

**Comment by mberhault** [comment]
CC: @bdarnell, @petermattis. I'm sure you have more ideas to throw in here, this is just a starting point.

**Comment by petermattis** [comment]
I've found `/debug/events` for queues somewhat useless recently. Too many useless messages obscure the ones you're looking for. It's easier to enable `--vmodule` and look at logs.

I wonder if we could expose some of this data via a `crdb_internal` table. Cc @knz.

**Comment by knz** [comment]
On 16-11-16 21:58, Peter Mattis wrote:
> I wonder if we could expose some of this data via a |crdb_internal|
> table. Cc @knz <https://github.com/knz>.
> 

That's a curious idea. What interface did you have in mind? A virtual
table holding all the events currently available via /debug/events?

-- 
Raphael 'kena' Poss

**Comment by petermattis** [comment]
> A virtual table holding all the events currently available via /debug/events.

I was thinking of exposing queue state and replica/range state. I'm not sure what support for the virtual table stuff has for filtering. This might be very inefficient if we have to fully populate the table before filtering.

**Comment by knz** [comment]
We could make a custom execution node for this source with a cursor and filter so it doesn't need to be prepopulated. Like a scanNode but for internal stuff.

**Comment by mberhault** [comment]
A simple first pass would be to make the raft and gossip debug pages more readable, highlighting relevant information, allowing query parameters for range IDs, links to nodes, etc... these pages are mostly ungrokable by anyone not intimately familiar with the code.

I can probably whip that up with "crappy html" (TM).

For range history, @petermattis mentioned a range event table somewhere. We should make use of it.

**Comment by petermattis** [comment]
```
root@:26257> show columns from system.rangelog;
+--------------+-----------+-------+----------------+
|    Field     |   Type    | Null  |    Default     |
+--------------+-----------+-------+----------------+
| timestamp    | TIMESTAMP | false | NULL           |
| rangeID      | INT       | false | NULL           |
| storeID      | INT       | false | NULL           |
| eventType    | STRING    | false | NULL           |
| otherRangeID | INT       | true  | NULL           |
| info         | STRING    | true  | NULL           |
| uniqueID     | INT       | false | unique_rowid() |
+--------------+-----------+-------+----------------+
(7 rows)
```

**Comment by mberhault** [comment]
A few more specific things that would be nice:
* list of unavailable ranges
* list of ranges with leader-not-leaseholder

both with links to the full range descriptor. Would make it easier to track. eg: https://github.com/cockroachdb/cockroach/issues/13506

**Comment by dianasaur323** [comment]
@mberhault is there still outstanding work related to this issue? Looks like you've already done part of the suggested work in your February commits.

**Comment by mberhault** [comment]
Quite a bit, but this is a longer term debugging tools issue. I'll lower the priority.

@BramGruneir: do you have somewhere you're tracking these?

**Comment by BramGruneir** [comment]
I wasn't, I just created one: #14671

**Comment by dianasaur323** [comment]
Thanks both!

**Comment by BramGruneir** [comment]
I'm going to close this since #14671 captures the work that needs to be done.
