### ISSUE TITLE
sql: support the pg extended syntax for CREATE DATABASE

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#10734]
Reported in #5582:
```
ERROR:  syntax error at or near "TEMPLATE"
CREATE DATABASE postgrex_test TEMPLATE=template0 ENCODING='UTF8' LC_COLLATE='en_US.UTF-8' LC_CTYPE='en_US.UTF-8';
```

1) Although we do not support the TEMPLATE parameter, in the particular case where the argument is `template0` we can ignore it, as it simply indicates to create a "blank" database. (`template0` is pg's empty database, clients typically use it explicitly because pg also allows configuration to override the default used when no template is specified)

2) ENCODING, LC_COLLATE and LC_CTYPE can be checked for correctness (assert that their values are compatible with the current CockroachDB code, which is the case here) an then safely ignored.

So to address this issue we can simply accept the extended syntax, do some sanity check on it and then process it as a regular `CREATE DATABASE`.

**Comment by knz** [comment]
Also from https://github.com/cockroachdb/cockroach/issues/5582#issuecomment-261332810:
```
ERROR XX000 (internal_error): syntax error at or near "UTF8"
CREATE DATABASE "test_dev" ENCODING 'UTF8'
```

the "=" is optional.

**Comment by bdarnell** [comment]
CockroachDB currently uses the `C` collation, not `en_US` (`en_US` is case-insensitive; I don't know if there are other differences):

```
root@:26257> select 'a' > 'A';
+-----------+
| 'a' > 'A' |
+-----------+
| true      |
+-----------+
(1 row)

root@:26257> SELECT 'a' collate en_US > 'A' collate en_US;
+--------------------------------+
| 'a' COLLATE en_US > 'A' COLLATE en_US |
+--------------------------------+
| false                          |
+--------------------------------+
(1 row)
```

So we'd have to reject a database creation that asked for `en_US` collation until we fully support this mode.

**Comment by knz** [comment]
Thanks Ben for explaining. 
I have checked and indeed en_US uses the [ISO 14651](https://en.wikipedia.org/wiki/ISO_14651) collation (common to many languages) with some extensions. We do support that for the COLLATE keyword but we're not able to propagate a database-wide setting to every session.

@tlvenn can you comment on this? Is the setting of the default locale to en_US and its collation properties critical to your application?

**Comment by tlvenn** [comment]
@knz it does not matter as far as Ecto/Postgrex is concerned, only encoding is explicitly set when creating a database.
