### ISSUE TITLE
storage: metrics inaccurate when nodes are down

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#10731]
<img width="287" alt="screen shot 2016-11-16 at 10 47 02 am" src="https://cloud.githubusercontent.com/assets/6201335/20353847/1b438bd8-abea-11e6-8759-22d36f46dbb7.png">

The blip in the above graph occurred when a node was taken down. The above graph is for range allocator stats and the blip is in the "noop" metric. I believe we're summing this metric across nodes, but when a node goes down we stop updating the metric for the down node. The other nodes in the cluster take over responsibility for the ranges on the down node and what we end up seeing is a blip like the above which is very misleading. This is just one example of this phenomenon. It also happens for the total range count.

**Comment by petermattis** [comment]
Poking around in Grafana, I would have thought that we could treat null values as zero in order to get the desired behavior. But that doesn't work.

**Comment by mberhault** [comment]
I don't think this is still a thing.
