### ISSUE TITLE
cli: add replica count to `cockroach node status`

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/cockroach#10738]
Notably missing from `cockroach node status` is a count of the number of replicas on a node, which displays in the Admin UI. (`cockroach node status` identifies the number of replicas the node is a leader on, but not the total number of replicas it stores).

Having greater alignment between `cockroach node status` and the Admin UI, in general, is desirable because it gives users a CLI alternative to opening the Admin UI.

**Comment by a-robinson** [comment]
Fixed by https://github.com/cockroachdb/cockroach/pull/23162
