### ISSUE TITLE
Increase test coverage for schema changes

### ISSUE THREAD

**Issue by maryliag** [cockroachdb/cockroach#107448]
Increase test coverage for schema changes, including running operations:
- [ ] while schema changes are in progress
- [ ] on databases that just completed a schema change

Jira issue: CRDB-30047

Epic CRDB-19168

**Comment by rafiss** [comment]
@maryliag just to confirm - is this issue filed as a result of https://github.com/cockroachdb/cockroach/issues/107357

Notes:
- We have the `schemachange/during/tpcc` roachtest, but it only uses deterministic schema changes.
- We have the `schemachange/random-load` test which does random schema changes, but currently INSERTs are disabled. (https://github.com/cockroachdb/cockroach/issues/91863)
- We have the `ExecuteWithDMLInjection` helper for testing the new declarative schema changer.

So to resolve this, I think we should either work on https://github.com/cockroachdb/cockroach/issues/91863 or update the `ExecuteWithDMLInjection` test that would have caught the bug. We almost added the test in https://github.com/cockroachdb/cockroach/pull/98692 so we might need to resurrect that work.

**Comment by maryliag** [comment]
Yes, this was created as a result of #107357, but I assume could be other cases with similar issue

**Comment by rafiss** [comment]
closing in favor of https://github.com/cockroachdb/cockroach/issues/108181 and https://github.com/cockroachdb/cockroach/issues/91863 (added O-postmortem to #91863)
