### ISSUE TITLE
increase test coverage for migration of older versions

### ISSUE THREAD

**Issue by maryliag** [cockroachdb/cockroach#107451]
Increase test coverage that would also test migrations from older versions  (e.g. 22.1) to a new one (e.g. 23.1)
that would have caught errors such as the one here: https://github.com/cockroachdb/cockroach/pull/106359

Jira issue: CRDB-30049

Epic CRDB-9179

**Comment by miretskiy** [comment]
I think we're good here.  Going to close; @jayshrivastava feel free to reopen if you feel strongly.
