### ISSUE TITLE
Run nightly benchmark for row level TTL

### ISSUE THREAD

**Issue by rimadeodhar** [cockroachdb/cockroach#107496]
We should run a nightly benchmark for row level TTL using the workload added in https://github.com/cockroachdb/cockroach/pull/87449.

Jira issue: CRDB-30081

**Comment by dikshant** [comment]
It would also be good to have a foreground workload on these tests and measure how much they are impacted. For example, what does the P95 INSERT/SELECT/UPDATE look like when TTL is running.

**Comment by rafiss** [comment]
The `ttlbench` workload in https://github.com/cockroachdb/cockroach/pull/87449 just tests the TTL job itself.

The `ttllogger` workload (https://github.com/cockroachdb/cockroach/blob/master/pkg/workload/ttllogger/ttllogger.go) is one that tests TTL while INSERTs are happening.

Both of these are valuable. For the nightly, lets see if we can use those or extend them further to reproduce issues like https://github.com/cockroachdb/cockroach/issues/98722

**Comment by rafiss** [comment]
https://github.com/cockroachlabs/support/issues/2469 has examples of the kind of behavior we want to test in our nightlies.
