### ISSUE TITLE
cli: double-escaping quotes in json in sql display_format

### ISSUE THREAD

**Issue by rharding6373** [cockroachdb/cockroach#107518]
**Describe the problem**

In https://github.com/cockroachlabs/support/issues/2486 we encountered an issue with the CLI where some JSON was being double-escaped when using the sqlReporter in sql display format mode. This only happens when the JSON contains invalid utf8 codes.

**To Reproduce**

In demo:

```
\set display_format sql
-- This is an invalid character encoding.
SELECT (e'{"a": "b\u0099c"}')::JSONB;                                   
--CREATE TABLE results (
--  jsonb STRING
--);

--INSERT INTO results VALUES (e'{\\"a\\": \\"b\\u0099c\\"}');
-- 1 row

-- Try to select the output in the VALUES clause as json.
-- Alternatively, you could try to directly copy-paste the output
-- from the previous command.
SELECT (e'{\\"a\\": \\"b\\u0099c\\"}')::JSONB;
--...|{\"a\": \"b\u0099|...
--...|.^...............|...: invalid JSON token
--SQLSTATE: 22P02

```

**Expected behavior**
The output in sql display format should be able to round trip without error.

**Additional data / screenshots**
From the linked issue:
[0] https://github.com/cockroachdb/cockroach/blob/9d976cbcf5b0bf031a5d831daf47abeacdfd974d/pkg/cli/clisqlexec/format_value.go#L48
[1] https://github.com/cockroachdb/cockroach/blob/9d976cbcf5b0bf031a5d831daf47abeacdfd974d/pkg/cli/clisqlexec/format_sql.go#L51

Here's what's happening in the surrounding code for the example select:

* The caller of [0] is iterating over the values in the rows returned from the database. This output is valid.
* We format the value "into a string suitable for displaying to the user"
* Since it's not valid utf8, we go to line [0]. The %+q escapes all the quotes. This output is also valid.
* When using the sql display_format, we use sqlReporter which ends up escaping all the backslashes in line [1]. Now we get our invalid, double-slashed output.

**Environment:**
 - CockroachDB version 22.2.6, 23.1.5
 - Client app cockroach sql

Jira issue: CRDB-30089

**Comment by sajdakabir** [comment]
@rafiss  can I work on this issue?

**Comment by foehammer127** [comment]
@rharding6373 @rafiss  The current solution that I have is to change the [EncodeSQLStringWithFlags](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/lexbase/encode.go#L138C10-L138C10l) function, so it does not escape backslashes that are escaping other characters, but I fear that this would cause undefined behavior, and slow down the efficiency of the function. 

Would this be acceptable?

**Comment by rharding6373** [comment]
We will welcome any PR from community members to fix this issue, thanks!

Instead of changing `EncodeSQLStringWithFlags` to always not escape backslashes used as escapes, maybe introducing a flag to control that behavior and then using that flag when we call `EncodeSQLStringWithFlags` from [sqlReporter](https://github.com/cockroachdb/cockroach/blob/master/pkg/cli/clisqlexec/format_sql.go#L51) would be more prudent.

**Comment by foehammer127** [comment]
> Instead of changing EncodeSQLStringWithFlags to always not escape backslashes used as escapes, maybe introducing a flag to control that behavior and then using that flag when we call EncodeSQLStringWithFlags from sqlReporter would be more prudent.

Thanks

**Comment by chanYe-EAST** [comment]
@rharding6373 Hi, I made a quick draft to address this issue. I referred the postgresql [doc](http://www.postgresql.org/docs/9.4/static/sql-syntax-lexical.html) to determine whether backslashes are used for escaping. I've taken into account various cases, including unicode, hexa bytes, octal bytes, and other escaping sequences. Could you please review the code and provide feedback? Thanks.

**Comment by rharding6373** [comment]
@chanYe-EAST Thanks for the contribution. I will review it this week.
