### ISSUE TITLE
roachtest: bump AWS provisioned write bandwidth for all restore tests

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#107609]
**Describe the problem**

A number of restore tests are failing on AWS with OOMs in the replication layer.

While we improve the memory accounting in the replication layer, it's not useful for these tests to keep failing.

We are fairly confident that the ooms can be traced to disk overload. Default AWS provisioned gp3 volumes come with combined read+write throughput of 125mb/s, which is routinely maxed out in tests. Combined with load imbalances in the cluster, this can lead to OOMs in the replication layer today.

We should double the provisioned write bandwidth and make sure that this is the default on AWS for the restore tests. This should be easy, as these tests have their own little framework (i.e. all tests go through a central code path).

Holistically addressing the OOMs is tracked in [CRDB-25503](https://cockroachlabs.atlassian.net/browse/CRDB-25503).

Jira issue: CRDB-30126

**Comment by pavelkalinnikov** [comment]
@cockroachdb/disaster-recovery @msbutler What limits the rate of writes in `restore` tests? Can we reduce it a bit so that we don't eat up all the disk throughput as on [this](https://github.com/cockroachdb/cockroach/issues/106496#issuecomment-1668087987) graph?

**Comment by msbutler** [comment]
@pavelkalinnikov At the sql level, nothing limits the write rate of restore. At the kvserver level, there are a few things that I'm less familiar with. I know Irfan recently set the concurrentAddSStable limiter to default off on master (not on 23.1) https://github.com/cockroachdb/cockroach/pull/104861.

Since this test can max out disk throughput, it seems reasonable to use beefier hardware. I'm going to chat with my team about it tomorrow.

**Comment by pavelkalinnikov** [comment]
@msbutler The prototype for provisioning for extra throughput is in #108427. I've tested it and compared 125 and 250 MB/s, see the above message. At 125 we're maxing out the throughput, at 250 we have some leeway, so I think we should be good with 250?

**Comment by pavelkalinnikov** [comment]
Reopening this issue, to bump throughput in other tests too.

Currently, other `restore` tests (even small 400GB ones) max out the 125 MB/s throughput, e.g. see `restore/tpce/400GB/aws/nodes=4/cpus=8`: https://github.com/cockroachdb/cockroach/issues/106248#issuecomment-1673632320.

On GCE, a same scale test `restore/tpce/400GB/gce/nodes=4/cpus=8` gets disks with larger throughput which is not usually maxed out:

<img width="1625" alt="Screenshot 2023-08-22 at 09 43 31" src="https://github.com/cockroachdb/cockroach/assets/3757441/04a3372e-5b9b-4f48-9ba4-11b942d66ef0">

@msbutler I think we should bump throughput to 250 MB/s on all AWS `restore` tests, as this issue originally suggested. This would both reduce likelihood of OOMs, and will bring some parity between tests.
