### ISSUE TITLE
serverutils: merge StartTenant and StartSharedProcessTenant

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#107695]
(Followup to  #107612)

1. there should be just 1 method instead of 2 -- with the deployment mode set as parameter.
2. the name is wrong - it does not "start a tenant", it starts the _service_ for a tenant.

Epic CRDB-31933
xref #107058.
xref #106772.

Jira issue: CRDB-30163

**Comment by stevendanna** [comment]
Closing for now. I think we we probably want to do a new pass of considering the TestServer API and then generate work items as appropriate.
