### ISSUE TITLE
roachprod: remove andrei-jepsen

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#107608]
See: https://github.com/cockroachdb/cockroach/pull/106352#pullrequestreview-1517566232
            

Jira issue: CRDB-30125

**Comment by tbg** [comment]
The PR is in https://github.com/cockroachdb/cockroach/pull/106501 but need to synchronize the merge with also deleting the project.

**Comment by rickystewart** [comment]
Done.
