### ISSUE TITLE
rangefeed: when rangefeed retries replica error it can use stale range descriptor

### ISSUE THREAD

**Issue by aliher1911** [cockroachdb/cockroach#107610]
When testing rangefeed metrics fix in https://github.com/cockroachdb/cockroach/pull/107384 following behaviour was observed:

Test performs a table split at multiple points, then it creates a rangefeed over the data. Test also sets a knob to inject error (kvpb.NewError(&kvpb.StoreNotFoundError{})) in rangefeed to verify feed restart is handled correctly and metrics are updated.

What happened in practice is that during retry, range cache was returning pre-split range descriptor. Subsequent retry was rejected by node as requested range didn't match actual range. That would in turn cause range cache to get invalidated and rangefeed request would succeed on next retry.

While there's no correctness issue in this behaviour, it is surprising that we didn't invalidate range descriptor eagerly. There may be an opportunity to improve this behaviour and remove unnecessary roundtrip.

Jira issue: CRDB-30127

**Comment by erikgrinaker** [comment]
For `StoreNotFoundError`, we explicitly do not instruct the caller to evict the range cache. Might be as simple as returning `evict: true` in that case.

https://github.com/cockroachdb/cockroach/blob/64cfbb2e7f33c8e1d3b783d7273cb4f14d544eb3/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L535-L540

On the corresponding DistSender handling, there's a TODO about this:

https://github.com/cockroachdb/cockroach/blob/64cfbb2e7f33c8e1d3b783d7273cb4f14d544eb3/pkg/kv/kvclient/kvcoord/dist_sender.go#L2405-L2411

**Comment by aliher1911** [comment]
Yeah, seem that absence of evict is an oversight here. In reality it is likely a no-issue because we shouldn't get a StoreNotFound errors if descriptors are correct.
