### ISSUE TITLE
backupccl: TestBackupRestoreTenant timed out on `WaitForTenantReadiness`

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#107669]
Run: https://teamcity.cockroachdb.com/viewLog.html?buildId=11074294&buildTypeId=Cockroach_BazelEssentialCi

The call over here - https://github.com/cockroachdb/cockroach/blob/9c510f9abdcd0d52e04f620ce5fa283c54d6ef46/pkg/ccl/backupccl/backup_test.go#L7358 seems to be stuck in this select clause - https://github.com/cockroachdb/cockroach/blob/ecc50b7a1936328f1e0add890bff05ef820c2344/pkg/server/testserver.go#L1048. I haven't dug beyond that yet. I'll post more updates as I do.

Jira issue: CRDB-30152

**Comment by mgartner** [comment]
Hit this here too: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/11087213?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

**Comment by adityamaru** [comment]
@mgartner it should be skipped now if you rebase. I have a fix open but might take a day or so to get the reviews I need.
