### ISSUE TITLE
SHOW STATISTICS displays timestamp in timezone set by the user

### ISSUE THREAD

**Issue by thtruo** [cockroachdb/cockroach#107651]
**Is your feature request related to a problem? Please describe.**
See https://github.com/cockroachdb/cockroach/issues/107644 
This request is specific to  making `SHOW STATISTICS` display timestamp values that obey the timezone set by the user.

**Describe the solution you'd like**
When a user sets their timezone to a non-UTC value for their session in the database, `SHOW STATISTICS` should display timestamp fields in that selected timezone.

See https://github.com/cockroachdb/cockroach/pull/107988 for an example of how to test this.

cc @DingDLu  

Jira issue: CRDB-30147

Epic CRDB-24406

**Comment by mgartner** [comment]
The type of the `created` column is a timestampe w/o time zone, which we should change to a timestamp w/ time zone.

```sql
select pg_typeof(created) from [show statistics for table t];
--            pg_typeof
-- -------------------------------
--   timestamp without time zone
--   timestamp without time zone
-- (2 rows)
```

**Comment by michae2** [comment]
@thtruo what's the priority of this? Can we do this in 24.1?

**Comment by michae2** [comment]
It sounds like we have committed to do this in v23.2.

**Comment by mgartner** [comment]
@thtruo can we get some explanation explaining why this is urgently needed for 23.2?

**Comment by kevin-v-ngo** [comment]
Hi @mgartner, this is a customer commit. I'll send you over the specification.
