### ISSUE TITLE
c2c: after cutover, all backup jobs should fail and scheduled backups should continue running with failing jobs in the new tenant

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#107751]
Once the application tenant comes online after cutover, all paused and running backup jobs should get cancelled and all backup schedules should continue running and attempting failed backup jobs. If the source application tenant were still online and running the backup job, we wouldn't want both the source and destination tenants writing to the same backup collection. It should be on the user of the new tenant to start a new scheduled backup, or if we create a new cmd, ALTER the existing backup. 

We'd like the scheduled backup to continue running on the new tenant, to ensure the dba gets alerted on the failed backups. 

Running and scheduled backups will fail once https://github.com/cockroachdb/cockroach/issues/108028 completes. Further logic is required to cancel paused backup jobs.

Jira issue: CRDB-30184

Epic CRDB-26968

**Comment by msbutler** [comment]
related to umbrella issue #107089

**Comment by shermanCRL** [comment]
@kathancox This should be documented clearly in the section about cutover for C2C.

**Comment by msbutler** [comment]
@kathancox @shermanCRL no docs action needed right now, as I haven't even started the work to address this issue.

**Comment by msbutler** [comment]
we decided on a different ux:
- https://github.com/cockroachdb/cockroach/pull/111578
- https://github.com/cockroachdb/cockroach/issues/108028
