### ISSUE TITLE
sql: add SHOW VIEW statement

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/cockroach#10771]
There are `SHOW <foo>` statements for most objects, but not views. Suggesting to add `SHOW VIEW FROM...`, which would look something like:
```
SELECT view_definition AS definition FROM information_schema.views WHERE table_schema = <database> AND table_name = <table>
```

**Comment by yznming** [comment]
@nvanbenschoten @sploiselle I can start to fix this issue now.

**Comment by yznming** [comment]
@sploiselle if you mean `SHOW VIEW` shows the definition of a view,  I think the `SHOW CREATE VIEW` can satisfy your requirement.

**Comment by a-robinson** [comment]
We *could* make `SHOW VIEW` as an alias for `SHOW CREATE VIEW`, but I'm not sure how much we want to be in the business of our creating our own new SQL syntax. `SHOW CREATE VIEW` is what MySQL offers, and I can't find anything about any database supporting `SHOW VIEW`.

What do you think, @sploiselle?

**Comment by sploiselle** [comment]
Ah. Views display in `SHOW TABLES` as tables and `SHOW CREATE VIEW` surfaces the statement used to create it. This can be closed without any action since most folks will probably find this less surprising than I did.

CC: @a-robinson @yznming
