### ISSUE TITLE
cli: TestUnavailableZip flakes

### ISSUE THREAD

**Issue by lidorcarmel** [cockroachdb/cockroach#107738]
1: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/11089094?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

2: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/11087369?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

Jira issue: CRDB-30178

**Comment by yuzefovich** [comment]
It seems possible that 6035b1a5f63090acc2f11418484906174c47e399 that introduced (or exposed) this flake, I'll take a look.

**Comment by ericharmeling** [comment]
@yuzefovich TestUnavailableZip flakes predate https://github.com/cockroachdb/cockroach/pull/107470.

I am assigned to a couple here:
- https://github.com/cockroachdb/cockroach/issues/106961
- https://github.com/cockroachdb/cockroach/issues/105800

**Comment by yuzefovich** [comment]
Thanks, this issue seems to be a timeout, likely the same as #105800.

**Comment by ericharmeling** [comment]
This should be fixed by https://github.com/cockroachdb/cockroach/pull/107199.

Backport to 23.1, 22.2 forthcoming.
