### ISSUE TITLE
roachtest: add + fix elastic-backup test equivalent for AWS

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#107770]
**Is your feature request related to a problem? Please describe.**

See this [internal discussion](https://cockroachlabs.slack.com/archives/C057ULDSKC0/p1690325346921249). When running backups to AWS, there are CPU-intensive stack frames that don't currently integrate with the elastic CPU limiter. 
- https://github.com/cockroachdb/cockroach/blob/212d1e97c7304f513578e5d87864e1080b7f68d6/pkg/ccl/backupccl/file_sst_sink.go#L255 is a tight loop that needs to integrate with the CPU limiter
- https://github.com/cockroachdb/cockroach/blob/7a84fe8a51e40d2b4f2278c5ed20aef7df34237a/pkg/cloud/amazon/s3_storage.go#L707 is CPU intensive — the underlying S3 library is computing shasums locally before uploading, which probably should acquire elastic CPU tokens somehow

These make for a large difference between the CPU consumption that the elastic CPU limiter sees and is able to clamp down, vs. what is actually observed. We're off by a factor of 6.5x below, for example:

![image](https://github.com/cockroachdb/cockroach/assets/10536690/3e1dac16-9961-40d8-afde-9273918e4136)

We should have a roachtest to capture this variant, and add the missing integrations.

Jira issue: CRDB-30187

Epic CRDB-34249

**Comment by aadityasondhi** [comment]
I am seeing a similar pattern on GCE as well. Although here the aggregate CPU utilization seems to stay high regardless. This is when running `admission-control/elastic-backup`.

<img width="1667" alt="image" src="https://github.com/cockroachdb/cockroach/assets/20070511/96d9b5d9-4e03-4df8-9d2d-6fca539cc6cf">

**Comment by aadityasondhi** [comment]
On AWS, looks similar:

<img width="1665" alt="image" src="https://github.com/cockroachdb/cockroach/assets/20070511/91c3d6ad-0630-4fd3-95f4-3bf9ef62c4a1">

**Comment by irfansharif** [comment]
@aadityasondhi: https://github.com/cockroachdb/cockroach/pull/108231 is an old PR that might help in the AWS case, if you want to consider taking it over the finish line.

**Comment by irfansharif** [comment]
BTW, from what I remember, I didn't merge that PR because even after those integrations (which are good to have), there was still high latency during backups. i.e. it wasn't due to high scheduling latency. See https://github.com/cockroachdb/cockroach/issues/108790 and https://github.com/cockroachdb/cockroach/issues/115190.

**Comment by aadityasondhi** [comment]
Ack. Thanks for the info.

After TPCE workload finished, so only backups running now on the cluster:

<img width="1671" alt="image" src="https://github.com/cockroachdb/cockroach/assets/20070511/ababc40a-8cd1-4d7b-82bc-b6e48d1532c8">

**Comment by aadityasondhi** [comment]
With https://github.com/cockroachdb/cockroach/pull/118605 and https://github.com/cockroachdb/cockroach/pull/121025 merged, this issue can now be closed. In an [internal discussion](https://cockroachlabs.slack.com/archives/C01SRKWGHG8/p1711382805776809), we decided not to patch the aws-sdk library to avoid an unnecessary fork of the sdk. We can revisit this at a later point if we decide it is worthwhile to do so in the future.
