### ISSUE TITLE
kv: add metrics for RPCs

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#10770]
Add metrics for `DistSender` RPCs. Total sent. Local RPCs. Retries. Perhaps NotLeaseHolder errors.

**Comment by a6802739** [comment]
@petermattis, you mean add `Total sent`, `Local RPCs`, `Retries`, `NotLeaseHolder` statisc? Maybe I could do that thing.

**Comment by petermattis** [comment]
Yes. We don't currently have metrics in `DistSender` and I was just brainstorming some of the info I'd like to see. In particular, yesterday I was debugging a problem where we appear to have excessive `Retries`. It would be interesting to know the fraction of retries to total RPCs. Similarly, it would be interesting to know how often the local RPC optimization is being used. Lastly, reads and writes need to be sent to the lease holder, so how often are we sending RPCs that are return a `NotLeaseHolderError` indicating we targeted the wrong replica.

**Comment by a6802739** [comment]
@petermattis, thanks for your reference.

So, how could I log this metrics in `DistSender` out?

**Comment by petermattis** [comment]
@a6802739 You'll need to plumb a `metric.Registry` into `DistSender` and then create a variety of `metric.Counter` objects. See `storage/metrics.go` for an example pattern to follow. As long as you're using the same metric Registry as the rest of the process, the stats will automatically be collected and exported.

**Comment by a6802739** [comment]
@petermattis got it. thanks a lot.

**Comment by a6802739** [comment]
@petermattis, should I just use `metric.Counter`  or use `CounterWithRates`like in `kv/txn_coord_sender.go`.

I want to ask a question, maybe it's uncorrelated to this issue. what's the difference between `metric.Gauge` and `metric.Counter`?

**Comment by bdarnell** [comment]
[This document](https://prometheus.io/docs/concepts/metric_types/) describes the difference between the metric types. 

I think we want to make a new registry in the DistSender (not a global), following the same pattern as StoreMetrics.

**Comment by mberhault** [comment]
Is the idea here to have custom metrics, or to try and grab grpc-level metrics? If the latter, this can be done through client and server interceptors.

**Comment by a6802739** [comment]
@bdarnell, thanks for your reference. 
@mberhault, I think it's not a grpc-level metric, it's just plumbed in structure`DistSender`.

**Comment by tamird** [comment]
I agree that we should be using interceptors for this, and as such,
this is blocked on #9697.

**Comment by petermattis** [comment]
> I agree that we should be using interceptors

How can GRPC interceptors give us metrics about the number of `DistSender` retries? I'm not familiar with GRPC interceptors, but they also don't seem to apply to number of local calls (which avoid GRPC) and `NotLeaseHolder` errors.

**Comment by tamird** [comment]
Good point, we can't get all the dist sender metrics with interceptors.
