### ISSUE TITLE
sql,kv: teach crdb_internal.cluster_locks about locking strengths

### ISSUE THREAD

**Issue by arulajmani** [cockroachdb/cockroach#107766]
**Describe the problem**

`crdb_internal.cluster_locks` is powered by the `QueryLocksRequest`. However, no strength information is returned in its response. Instead, all unreplicated locks are assumed to be of the `Exclusive` kind. See: 

https://github.com/cockroachdb/cockroach/blob/bac4c7949a2621da62da3bdb31924a2e7c51d5bc/pkg/sql/crdb_internal.go#L7658

This is busted in a couple of ways. One is that Intents now have a different locking strength (`lock.Intent`) as opposed to `lock.Exclusive`. Additionally, with the introduction of `SHARED` locks, we can no longer rely on unreplicated locks in the lock table to be of strength `lock.Exclusive`. 

We should teach `QueryLocksRequest` about locking strengths and use this information to correctly populate the strength column in `crdb_internal.cluster_locks`.

Jira issue: CRDB-30185

**Comment by lyang24** [comment]
we used to use exclusive as lock strength default. In the case of a lock that is not held, should we keep use exclusive as lock strength? or does None make more sense?

**Comment by arulajmani** [comment]
> In the case of a lock that is not held, should we keep use exclusive as lock strength?

Are you referring to the case where a lock is claimed but not held yet? If so, I think using the strength the request is trying to acquire the lock with is the right strength to use. This information should be stored on the `queuedGuard.mode` field.

**Comment by lyang24** [comment]
> Are you referring to the case where a lock is claimed but not held yet?
yes thanks for the guidance. I have made changes accordingly.

**Comment by lyang24** [comment]
a lot of rapid development taken place at lock_table.go
now the LockState concept is replaced keyLocks and txnLock, where KeyLocks has an one to many relationship with txnLock. 

would this be a good strategy to determine lock strength of the KeyLock
`iterate all holder's lock strength and pick the highest`
