### ISSUE TITLE
TypeError: Cannot assign to read only property 'fixedWindowEnd' of object '#<Object>'

### ISSUE THREAD

**Issue by gtr** [cockroachdb/cockroach#107886]
**Describe the problem**

A type error was discovered on Datadog.

**To Reproduce**

Although the Datadog error says it was encountered on the SQL Activity page, the [replay](https://cockroachlabs-prod.datadoghq.com/rum/sessions?query=%28%40view.name%3A%28%22%2Fcluster%2F%3Acluster%2Finsights%22%20OR%20%22%2Fcluster%2F%3Acluster%2Fdatabases%22%20OR%20%22%2Fcluster%2F%3Acluster%2Fdatabases%2F%3Adb%22%20OR%20%22%2Fcluster%2F%3Acluster%2Fdatabases%2F%3Adb%2F%3Aschema%2F%3Atable%22%20OR%20%22%2Fcluster%2F%3Acluster%2Fsql-activity%22%29%20OR%20%40view.error.count%3A%3E0%20%40view.name%3A%28%22%2Fcluster%2F%3Acluster%2Finsights%22%20OR%20%22%2Fcluster%2F%3Acluster%2Fdatabases%22%20OR%20%22%2Fcluster%2F%3Acluster%2Fdatabases%2F%3Adb%22%20OR%20%22%2Fcluster%2F%3Acluster%2Fdatabases%2F%3Adb%2F%3Aschema%2F%3Atable%22%20OR%20%22%2Fcluster%2F%3Acluster%2Fsql-activity%22%29%29%20%40view.name%3A%22%2Fcluster%2F%3Acluster%2Fsql-activity%22%20%40type%3Aview&cols=&event=AgAAAYmTNHYN5UFxFAAAAAAAAAAYAAAAAEFZbVROSUpjQUFBNF9DOWszQll4ekFBRwAAACQAAAAAMDE4OTkzYzUtNzIzYS00ZTFhLWFkMzUtODQ3NDQ0ZWJiMzEx&index=%2A&p_tab=replay&sort_by=%40view.error.count&sort_order=desc&type=rum&viz=stream&from_ts=1690372800000&to_ts=1690416000000&live=false) shows that it happens in the login page when the user selects to login via Google. 

```
TypeError: Cannot assign to read only property 'fixedWindowEnd' of object '#<Object>'
  at se.changeTimeScale @ https://cockroachlabs.cloud/assets/admin-ui-23-1.f0bdaf0bc394a52e75b6.js:2063:4352
  at updateRequestParams @ https://cockroachlabs.cloud/assets/admin-ui-23-1.f0bdaf0bc394a52e75b6.js:2063:4631
  at Object.Zi @ https://cockroachlabs.cloud/assets/common.2b9e5d8b1e36eebe89c9.js:734:9379
  at it @ https://cockroachlabs.cloud/assets/common.2b9e5d8b1e36eebe89c9.js:734:9540
  at on @ https://cockroachlabs.cloud/assets/common.2b9e5d8b1e36eebe89c9.js:734:9602
  at _r @ https://cockroachlabs.cloud/assets/common.2b9e5d8b1e36eebe89c9.js:734:29004
  at Gr @ https://cockroachlabs.cloud/assets/common.2b9e5d8b1e36eebe89c9.js:734:29456
  at <anonymous> @ https://cockroachlabs.cloud/assets/common.2b9e5d8b1e36eebe89c9.js:734:34844
  at hn @ https://cockroachlabs.cloud/assets/common.2b9e5d8b1e36eebe89c9.js:738:18970
  at rr @ https://cockroachlabs.cloud/assets/common.2b9e5d8b1e36eebe89c9.js:734:8538
```

**Additional data / screenshots**

- Datadog [error](https://cockroachlabs-prod.datadoghq.com/rum/sessions?query=%28%40view.name%3A%28%22%2Fcluster%2F%3Acluster%2Finsights%22%20OR%20%22%2Fcluster%2F%3Acluster%2Fdatabases%22%20OR%20%22%2Fcluster%2F%3Acluster%2Fdatabases%2F%3Adb%22%20OR%20%22%2Fcluster%2F%3Acluster%2Fdatabases%2F%3Adb%2F%3Aschema%2F%3Atable%22%20OR%20%22%2Fcluster%2F%3Acluster%2Fsql-activity%22%29%20OR%20%40view.error.count%3A%3E0%20%40view.name%3A%28%22%2Fcluster%2F%3Acluster%2Finsights%22%20OR%20%22%2Fcluster%2F%3Acluster%2Fdatabases%22%20OR%20%22%2Fcluster%2F%3Acluster%2Fdatabases%2F%3Adb%22%20OR%20%22%2Fcluster%2F%3Acluster%2Fdatabases%2F%3Adb%2F%3Aschema%2F%3Atable%22%20OR%20%22%2Fcluster%2F%3Acluster%2Fsql-activity%22%29%29%20%40view.name%3A%22%2Fcluster%2F%3Acluster%2Fsql-activity%22%20%40type%3Aview&cols=&event=AgAAAYmTNHYN5UFxFAAAAAAAAAAYAAAAAEFZbVROSUpjQUFBNF9DOWszQll4ekFBRwAAACQAAAAAMDE4OTkzYzUtNzIzYS00ZTFhLWFkMzUtODQ3NDQ0ZWJiMzEx&index=%2A&p_tab=error_details&sort_by=%40view.error.count&sort_order=desc&type=rum&viz=stream&from_ts=1690372800000&to_ts=1690416000000&live=false)

**Environment:**
 - Linux x86_64
 - Chrome 114.0.0.0

Jira issue: CRDB-30242

**Comment by maryliag** [comment]
Fixed by https://github.com/cockroachdb/cockroach/pull/106623
