### ISSUE TITLE
roachtest: grafana link does not have cluster name

### ISSUE THREAD

**Issue by annrpom** [cockroachdb/cockroach#107894]
Currently (as of 07/28/23), in a roachtest failure on 23.2 (like #107862), the generated Grafana link in the "Help" section redirects you to cockroachlabs.com - instead of testeng Grafana. 

Looking at the issue linked above as an example, we see the following vanity link for Grafana: https://go.crdb.dev/p/roachfana//1690711427218/1690713270780

Instead, we should be seeing the following:
https://go.crdb.dev/p/roachfana/teamcity-11114747-1690696061-26-n5cpu4/1690711427218/1690713270780

The cluster name seems to be empty - `clusterName` in `generateHelpCommand`.

Jira issue: CRDB-30247

**Comment by renatolabs** [comment]
`generateHelpCommand` is called by `(*githubIssues).createPostRequest`:

https://github.com/cockroachdb/cockroach/blob/509f8c8ee5c7c9d13c46e60436c5dbb3363cfeea/pkg/cmd/roachtest/github.go#L221

The `clusterName` variable passed to it is the variable associated with the `--cluster` roachtest command line flag:

https://github.com/cockroachdb/cockroach/blob/509f8c8ee5c7c9d13c46e60436c5dbb3363cfeea/pkg/cmd/roachtest/main.go#L184-L189

That variable will only be set if the `roachtest` call was passed the `--cluster` argument, which is not the case in TeamCity nightly builds (in that case, clusters are created by the test runner as tests run).

Luckily, the `githubIssues` struct already includes a handle to the `cluster` used in the run, so we can change the `generateHelpCommand` call to pass `g.cluster.Name()` instead.

@annrpom do you have the time to make that change? Let me know if the above is not clear.

**Comment by annrpom** [comment]
@renatolabs it is clear - thank you! my reasoning for why i thought it was not being populated was ultimately incorrect (sob sob), but i do have a draft PR up: https://github.com/cockroachdb/cockroach/pull/107984

if/when you have the time, would you be able to address [my comment/question](https://github.com/cockroachdb/cockroach/pull/107984#issuecomment-1661019665) about the guard i put for when a cluster creation fails (where i made the behavior == no grafana link) :>

thank you for taking your time to explain this to me/look over things!
