### ISSUE TITLE
UI: TypeError: v.ts.fixedWindowEnd.tz is not a function

### ISSUE THREAD

**Issue by gtr** [cockroachdb/cockroach#107841]
**Describe the problem**

A type error was encountered in the SQL Activity page and discovered on Datadog.

**To Reproduce**

The replay isn't available and the raw stack trace isn't very helpful:

```
TypeError: v.ts.fixedWindowEnd.tz is not a function
  at b @ https://cockroachlabs.cloud/assets/admin-ui-23-1.f0bdaf0bc394a52e75b6.js:1889:2459
  at df @ https://cockroachlabs.cloud/assets/common.470adad0ae11ad662401.js:734:54525
  at Lp @ https://cockroachlabs.cloud/assets/common.470adad0ae11ad662401.js:738:9098
  at Dh @ https://cockroachlabs.cloud/assets/common.470adad0ae11ad662401.js:738:987
  at $h @ https://cockroachlabs.cloud/assets/common.470adad0ae11ad662401.js:738:915
  at Wp @ https://cockroachlabs.cloud/assets/common.470adad0ae11ad662401.js:738:767
  at Nh @ https://cockroachlabs.cloud/assets/common.470adad0ae11ad662401.js:736:10972
  at <anonymous> @ https://cockroachlabs.cloud/assets/common.470adad0ae11ad662401.js:734:39368
  at p.unstable_runWithPriority @ https://cockroachlabs.cloud/assets/common.470adad0ae11ad662401.js:791:4022
  at ds @ https://cockroachlabs.cloud/assets/common.470adad0ae11ad662401.js:734:39146
```

Looking at the [pretty stack trace](https://cockroachlabs-prod.datadoghq.com/rum/sessions?query=-%40error.source%3Anetwork%20%40view.name%3A%28%22%2Fcluster%2F%3Acluster%2Finsights%22%20OR%20%22%2Fcluster%2F%3Acluster%2Fdatabases%22%20OR%20%22%2Fcluster%2F%3Acluster%2Fdatabases%2F%3Adb%22%20OR%20%22%2Fcluster%2F%3Acluster%2Fdatabases%2F%3Adb%2F%3Aschema%2F%3Atable%22%20OR%20%22%2Fcluster%2F%3Acluster%2Fsql-activity%22%29%20%40error.source%3Aconsole%20%40type%3Aerror&cols=&event=AgAAAYmdqC3lq_RxGwAAAAAAAAAYAAAAAEFZbWRxRFd3QUFCUC1JT0l0V0Y5eEFBTgAAACQAAAAAMDE4OTllMGItZGI1Yy00MDEwLTlhMGEtZmFlMDc0NzU5MGFj&index=%2A&type=rum&viz=stream&from_ts=1690560000000&to_ts=1690567200000&live=false), it looks like the error is thrown in the `moment.js` module. Based on that and the `.tz` call on `fixedWindowEnd`, the theory is that at some point during our switch to use `moment-timezone`, we are calling `moment` instead of `moment-timezone`.

Additional data / screenshots

- [Datadog error](https://cockroachlabs-prod.datadoghq.com/rum/sessions?query=-%40error.source%3Anetwork%20%40view.name%3A%28%22%2Fcluster%2F%3Acluster%2Finsights%22%20OR%20%22%2Fcluster%2F%3Acluster%2Fdatabases%22%20OR%20%22%2Fcluster%2F%3Acluster%2Fdatabases%2F%3Adb%22%20OR%20%22%2Fcluster%2F%3Acluster%2Fdatabases%2F%3Adb%2F%3Aschema%2F%3Atable%22%20OR%20%22%2Fcluster%2F%3Acluster%2Fsql-activity%22%29%20%40error.source%3Aconsole%20%40type%3Aerror&cols=&event=AgAAAYmdqC3lq_RxGwAAAAAAAAAYAAAAAEFZbWRxRFd3QUFCUC1JT0l0V0Y5eEFBTgAAACQAAAAAMDE4OTllMGItZGI1Yy00MDEwLTlhMGEtZmFlMDc0NzU5MGFj&index=%2A&type=rum&viz=stream&from_ts=1690560000000&to_ts=1690567200000&live=false) 

Environment:

CockroachDB version: Cockroach Serverless
Server OS: Mac OS X 10.15.7

Jira issue: CRDB-30210

**Comment by gtr** [comment]
The only place (apart from tests) where we're currently importing the `moment` module is in `pkg/ui/workspaces/cluster-ui/src/api/types.ts`.

**Comment by maryliag** [comment]
Fixed by https://github.com/cockroachdb/cockroach/pull/106623
