### ISSUE TITLE
insecure flag naming issue

### ISSUE THREAD

**Issue by tlvenn** [cockroachdb/cockroach#10780]
I have a little trouble with the naming of the insecure flag because it only works semantically speaking when the assumption is that only the app (cockroachdb) can secure the communication between nodes and clients.

However, if such security is being provided one layer below with a software defined network then it forces us to use this `--insecure` flag which just feels wrong to me.

For example, I am using Docker swarm mode and I have an overlay encrypted network.

I completely understand why it was named that way and why one must be explicit about it as a pretty effective way to make sure the user understand what he is asking for but it does lead to an awkward feeling when you are running your db in prod with such named `insecure` flag ;)

Maybe we could have an alias such as `--without-tls` or something similar ?

**Comment by bdarnell** [comment]
The hesitation you're feeling about running in production with `--insecure` is a good thing! Relying on network-level security is an assumption that people [often come to regret](http://www.androidauthority.com/ssl-added-removed-google-mocks-nsa-crypto-code-easter-egg-390162/). It's more than just "without TLS" - in insecure mode, there is no authentication at all; anyone on the network can connect as `root`. The existence of a less-pejorative alias can only serve to make it easier for people to run in a badly insecure state. If you trust your network enough to decline the security that your database offers, then you'll just have to get past that awkward feeling about the name of the flag you use to disable it.

**Comment by tlvenn** [comment]
Fair enough @bdarnell :)

I should had mentioned I have a dedicated encrypted network for cockroach services.
With Flannel, Calico and the like, more and more people will rely on SDN to secure their services because it creates one single point of control no matter the nature of your services.

My understanding of the `--insecure` flag was that no encryption would be provided and there is no node identity check either. I didn't understand that it would mean no authentication at all when a client is connecting to the cluster...

**Comment by tlvenn** [comment]
On a side note, docker should provide some PKI infra for services out of box in a not so distant future which should help running a secure cockroachdb cluster without much pain:
> https://github.com/docker/docker/issues/26915

**Comment by tlvenn** [comment]
Regarding the authentification, actually my understanding is currently since there is no password support, effectively there is no auth if there is no client cert used. However, as soon as password support lands, authentification should be enforced even when `--insecure` flag is used. Is this assumption correct @bdarnell ?

**Comment by bdarnell** [comment]
We do not currently enforce password authentication in insecure mode either. Maybe we should, but for now our plan is to treat TLS as required for any production deployment.

(The reason why it's not trivial to simply enable passwords without TLS is that we decided that `root` should not be allowed to have a password, and should only authenticate via a certificate. This means that `root` has no way to authenticate when TLS is not used. We could allow root to have a password only in insecure mode, but we don't want to complicate our authentication code for a mode that we don't fully endorse)

**Comment by tlvenn** [comment]
I think it would be best to enforce password auth in insecure mode and as far as user `root` is concerned, you would not be able to connect with it over the wire if there is no TLS, only by using cockroach sql locally on one of the cluster node. Would that be reasonable ?

For security reason, maybe also enforce that you cant connect from a client using a password less user unless it's done locally. This rule would cover the `root` use case just fine as far as the system does not let you assign a password to the `root` user.

**Comment by bdarnell** [comment]
Yes, there are reasonable policies we could implement here. But I know from painful experience that every single line of code in security-critical authentication flows is a potential source of catastrophic bugs, so I think we'd need a much stronger justification to implement an in-between kinda-secure mode. Just use TLS! (and the onus is on us to provide tools and/or instructions to make that easier instead of leaving it to our users to figure out how to make it work)
