### ISSUE TITLE
DISTINCT ON query with ORDER BY expression with non-default NULLS FIRST/LAST errors out

### ISSUE THREAD

**Issue by msirek** [cockroachdb/cockroach#107848]
**Describe the problem**
The following errors out on CRDB, but succeeds in postgres:
```sql
CREATE TABLE t1 (id int, str text);
CREATE TABLE t2 (id int, num int);
SELECT
DISTINCT ON (COALESCE(t2.id, t1.id))
t1.id,
t1.str
FROM t1 JOIN t2 ON t1.id = t2.id
ORDER BY COALESCE(t2.id, t1.id) DESC NULLS FIRST;

error (42P10): SELECT DISTINCT ON expressions must match initial ORDER BY expressions
```
 #107842 Fixes the ORDER BY column case. This issue is opened to handle all other cases where we order by an expression.

**Environment:**
 - CockroachDB version: All versions, v23.1 and prior

Jira issue: CRDB-30214

**Comment by yuzefovich** [comment]
Closing as a dup of #107516
