### ISSUE TITLE
sql: built-in function for bitwise OR of inputs with arbitrary length

### ISSUE THREAD

**Issue by rharding6373** [cockroachdb/cockroach#107821]
A user requested a built-in function that will allow bitwise OR of bit strings that may be arbitrary different lengths. The current workaround is to use `lpad`, but the implementation is bulky and returns a larger bit string than necessary, and assumes unsigned data:

```
lpad(input1::text, 64, '0')::bit(64) | lpad(input2::text, 64, '0')::bit(64)
```

For example:

```
SELECT lpad('1001'::text, 64, '0')::bit(64) | lpad('10'::text, 64, '0')::bit(64);
                              ?column?
--------------------------------------------------------------------
  0000000000000000000000000000000000000000000000000000000000001011
```

When ideally we would just output `1011`.

Jira issue: CRDB-30205

**Comment by yuzefovich** [comment]
This is closed by #107863, right @rharding6373?
