### ISSUE TITLE
multi-tenant: Node filtering by locality doesn't work in a multi-tenant demo cluster

### ISSUE THREAD

**Issue by ajstorm** [cockroachdb/cockroach#107975]
If you try to look at the "Nodes filtered by locality (regex)" option under "Advanced Debug" in a multi-tenant demo cluster, you'll see:

![image (3)](https://github.com/cockroachdb/cockroach/assets/18447034/7f906cc2-615c-48d4-b901-54ef99b43e7f)

and the loading continues indefinitely. 

If this option doesn't work, it should be removed from the MT UI.

Jira issue: CRDB-30275
Epic: CRDB-12100

**Comment by stevendanna** [comment]
This page works if the tenant has `can_view_node_info`. The failure mode here isn't really idea, but given that this is the same as the failure mode for other pages where we don't have the permission, I'm going to move this from the "Required for 23.2" into the backlog.

**Comment by ajstorm** [comment]
Does it make sense to add `can_view_node_info` to the `replication-source` config profile in 23.2?

**Comment by stevendanna** [comment]
Hrm......it should be there: https://github.com/cockroachdb/cockroach/blob/release-23.2/pkg/configprofiles/profiles.go#L113
