### ISSUE TITLE
sql: add a cluster setting to opt into read committed syntax

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#107980]
In v23.1, using READ COMMITTED would always be implicitly promoted to SERIALIZABLE.

After the v23.2 changes for READ COMMITTED, we should make sure that this is still the case, since it is still a preview feature. An example for why we need it is since we have banned schema changes under READ COMMITTED, statements that previously worked in 23.1 could suddenly start failing once the upgrade is finalized and READ COMMITTED transactions are used.

Some tools (e.g. DMS in https://github.com/cockroachdb/cockroach/issues/107683), use READ COMMITTED.

To support them, we will add a new cluster setting that preserves the 23.1 behavior of automatically promoting READ COMMITTED to SERIALIZABLE. That setting should be on by default.

** Example of what this setting would do **
```
-- name of the setting to be determined later.
SET CLUSTER SETTING sql.txn.always_use_serializable = true;

BEGIN TRANSACTION ISOLATION LEVEL READ COMMITTED;
SHOW transaction_isolation;
-- returns SERIALIZABLE. this is the 23.1 behavior.
COMMIT;


SET CLUSTER SETTING sql.txn.always_use_serializable = false;

BEGIN TRANSACTION ISOLATION LEVEL READ COMMITTED;
SHOW transaction_isolation;
-- returns READ COMMITTED.
COMMIT;
```

Jira issue: CRDB-30278

Epic CRDB-26546

**Comment by michae2** [comment]
Do we already have a version gate for read committed? If not, maybe it would be good to include it when we add this setting.

**Comment by rafiss** [comment]
> Do we already have a version gate for read committed? If not, maybe it would be good to include it when we add this setting.

yes we already have that
