### ISSUE TITLE
sql: function oidvectortypes is not supported

### ISSUE THREAD

**Issue by giangpham712** [cockroachdb/cockroach#107942]
The oidvectortypes function, mostly used by psql \df, formats types separated by spaces

In efcore.pg library, the following SQL query is used to list all user-defined functions and procedures

```
SELECT 'DROP ROUTINE "' || nspname || '"."' || proname || '"(' || oidvectortypes(proargtypes) || ');' FROM pg_proc
JOIN pg_namespace AS ns ON ns.oid = pg_proc.pronamespace
WHERE
        nspname NOT IN ('pg_catalog', 'information_schema') AND
    NOT EXISTS (
            SELECT * FROM pg_depend AS dep
            WHERE dep.classid = (SELECT oid FROM pg_class WHERE relname = 'pg_proc') AND
                    dep.objid = pg_proc.oid AND
                    deptype = 'e');
```

`oidvectortypes` is currently not available in CockroachDB. Can this be done in a different way?

This is affecting tests in efcore.pg library

@fqazi  

Jira issue: CRDB-30265

Epic CRDB-27601

**Comment by fqazi** [comment]
Let us prioritize this, but I think we can get this implemented.

**Comment by rafiss** [comment]
In PG, this is defined here: https://github.com/postgres/postgres/blob/c27f8621eedf744a7bc80e37dd2d3f0f559edf1b/src/backend/utils/adt/format_type.c#L443-L484
