### ISSUE TITLE
ui: TypeError: re.toNumber is not a function

### ISSUE THREAD

**Issue by zachlite** [cockroachdb/cockroach#107905]
Observed on [Datadog](https://cockroachlabs-prod.datadoghq.com/rum/sessions?query=-%40error.source%3A%28agent%20OR%20report%29%20%40view.url_path_group%3A%28%22%2Fcluster%2F%3F%2Fstatement%2Ftrue%2F%3F%22%20OR%20%22%2Fcluster%2F%3F%2Fstatement%2Ffalse%2F%3F%22%20OR%20%22%2Fcluster%2F%3F%2Fsql-activity%22%29%20-%40error.message%3A%22console%20error%3A%20Moment%20Timezone%20has%20no%20data%20for%20UTC.%20See%20http%3A%2F%2Fmomentjs.com%2Ftimezone%2Fdocs%2F%23%2Fdata-loading%2F.%22%20%40type%3Aerror&cols=&event=AgAAAYl6c7DJM7oznQAAAAAAAAAYAAAAAEFZbDZjN1U0QUFCUkY2cDBXNlQwcVFBRAAAACQAAAAAMDE4OTdhZGUtNzJkNC00YWUwLTkxYWItYjExYWNiZjBkMTJk&integration_id=real_user_monitoring&integration_short_name=rum_sessions_with_errors&sort_by=time&sort_order=desc&viz=stream&from_ts=1689566400000&to_ts=1689998340000&live=false) on the SQL activity page

```
TypeError: re.toNumber is not a function
  at Object.cell @ https://cockroachlabs.cloud/assets/admin-ui-23-1.f0bdaf0bc394a52e75b6.js:1874:77275
  at Object.cell @ https://cockroachlabs.cloud/assets/admin-ui-23-1.f0bdaf0bc394a52e75b6.js:2007:6550
  at <anonymous> @ https://cockroachlabs.cloud/assets/admin-ui-23-1.f0bdaf0bc394a52e75b6.js:2007:5174
  at Array.map @ <anonymous>
  at I @ https://cockroachlabs.cloud/assets/admin-ui-23-1.f0bdaf0bc394a52e75b6.js:2007:5031
  at df @ https://cockroachlabs.cloud/assets/common.2b9e5d8b1e36eebe89c9.js:734:54525
  at Lp @ https://cockroachlabs.cloud/assets/common.2b9e5d8b1e36eebe89c9.js:738:9098
  at Dh @ https://cockroachlabs.cloud/assets/common.2b9e5d8b1e36eebe89c9.js:738:987
  at $h @ https://cockroachlabs.cloud/assets/common.2b9e5d8b1e36eebe89c9.js:738:915
  at Wp @ https://cockroachlabs.cloud/assets/common.2b9e5d8b1e36eebe89c9.js:738:767
```

I suspect this is related to #106323 

Jira issue: CRDB-30252

**Comment by johndunderhill** [comment]
I am seeing this in the console.  Prevents me from viewing active sessions.  Let me know if you want more info.

**Comment by johndunderhill** [comment]
I'm on CockroachDB Serverless Google Cloud, v23.1.8.  I'm a customer.

The issue is consistent.  In my account, I go to the Overview page for my cluster, click Open Sessions, and it says "Something went wrong."  This occurs on Chrome and Firefox, and in clean sessions (no cookies or cache).

![image](https://github.com/cockroachdb/cockroach/assets/25628891/cf477e9c-3414-4d5a-a3d5-9d870f3b187a)
