### ISSUE TITLE
sql: TestTenantLogic_alter_table/99764 column "crdb_internal_idx_expr" does not exist

### ISSUE THREAD

**Issue by ecwall** [cockroachdb/cockroach#108096]
Flaky test in https://teamcity.cockroachdb.com/viewLog.html?buildId=11168437&buildTypeId=Cockroach_BazelEssentialCi

```
Failed
=== RUN   TestTenantLogic_alter_table/99764
    logic.go:3109: 
        
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/7637/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/ccl/logictestccl/tests/3node-tenant/3node-tenant_test_/3node-tenant_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/alter_table:2846: 
        expected success, but found
        (42703) column "crdb_internal_idx_expr" does not exist
        column_resolver.go:196: in NewUndefinedColumnError()
    logic.go:2081: 
         pq: column "crdb_internal_idx_expr" does not exist
[23:51:50] --- done: /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/7637/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/ccl/logictestccl/tests/3node-tenant/3node-tenant_test_/3node-tenant_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/alter_table with config 3node-tenant: 571 tests, 2 failures
[23:51:52] --- total progress: 571 statements
--- total: 571 tests, 2 failures
    --- FAIL: TestTenantLogic_alter_table/99764 (0.11s)
```

Jira issue: CRDB-30314

**Comment by Xiang-Gu** [comment]
I wasn't able to reproduce this error when running this subtest on `relase-22.2` branch with `--stress` for >30 minutes. The line number suggests that the failing stmt is `CREATE TABLE t_99764 (i INT PRIMARY KEY, j INT, UNIQUE (j, CAST(j AS STRING)), FAMILY "primary" (i, j));`, which uses legacy schema changer. Unfortunately, the logs don't contain stack traces or anything helpful. I also looked at this test's history and it has failed only once in the past 1000 calls. For now, it remains a mystery but I am not too concerned about it bc of the extremely low frequency; It might also be a symptom of something else completely unrelated to schema. I am going to leave it open and work on something else now. If it didn't flake for another week or so, then let's close it.

**Comment by rafiss** [comment]
Closing as per above comment.
