### ISSUE TITLE
c2c/changefeedccl: after cutover, app tenant changefeeds should (probably) immediately pause

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#108031]
After c2c cutover, app tenant changefeeds currently resume. This doesn't seem great, as the source app tenant changefeeds could also be writing to the same sink(s). The dest side changefeeds should probably pause, prompting the user to manually configure the src and dst app tenant changefeeds.

The CDC team should make the final call on how this should work. For added context, here's how DR is thinking about backup and restore jobs, post cutover:
- https://github.com/cockroachdb/cockroach/issues/107876
- https://github.com/cockroachdb/cockroach/issues/107751

Also note that one of the invariants of c2c is that the source side app tenant should not be affected by physical replication, so we wouldn't want to automatically modify its changefeeds.

Jira issue: CRDB-30295

**Comment by amruss** [comment]
@msbutler we fail the changefeed if the cluster ids dont match, is that not sufficient?

**Comment by dt** [comment]
Perfect, sounds good. Up to you if you want to change that hard terminal failure to a pause-with-reason to give them a chance to resume it again if they actually want it running on the restored/cutover cluster.
