### ISSUE TITLE
util/must: consider performance implications

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#108169]
The `must` package isn't suitable for use in hot paths. The main problem is that it takes printf-style format args as `[]interface{}`:

https://github.com/cockroachdb/cockroach/blob/32504778bdc173d4b6ce3e446b681b5d8c0baba2/pkg/util/must/must.go#L265-L275

This has a couple of problems: the interface boxing incurs an allocation for certain types, and arguments can escape to the heap. One might hope that the compiler deferred the boxing until after the `a == b` condition when inlining, but no such luck.

Most likely, the better option is to significantly simplify the API. Something basically similar to:

```go
if a != b {
  return must.Fail(ctx, "a=%v != b=%v", a, b)
}
```

This only incurs the cost of boxing on the unhappy path, and the heap escape can similarly be deferred by copying the format args value in the branch.

However, let's consider some other options here, and see if we can come up with something suitable.

Jira issue: CRDB-30342

**Comment by erikgrinaker** [comment]
I'll point out that we only incur the boxing allocation for objects or large values, so this is still fine as long as we don't pass those. But it's easy to get wrong. We could consider adding a linter or runtime check, and a wrapper function to override the check. But it's not exactly ergonomic.

We could consider a secondary API to decorate the error, but this won't work with fatal assertions since they'll fail before:

```go
if err := must.Equal(ctx, a, b, "format"); err != nil {
  return must.Decorate(err, "%v", arg)
}
```

Generics won't help us here, since variadic arguments would require the same type for all arguments in that case, and we can't be generic over `fmt.Stringer` since primitive types don't implement it.

```
func Equal[T comparable, A fmt.Stringer](ctx context.Context, a, b T, format string, args ...A) error // no bueno
```

Another option would be to use code generation to generate code which only incurs the boxing cost on failures. Again, not very ergonomic. We could also pass a closure to generate the format args, but that's not ergonomic either, and likely comes with its own performance penalty.

**Comment by rickystewart** [comment]
> Generics won't help us here, since variadic arguments would require the same type for all arguments in that case, and we can't be generic over fmt.Stringer since primitive types don't implement it.

[Guy with no knowledge of Go generics voice] Can you define your own interface which is "either `fmt.Stringer` or `bool`, `string`, `int8`, `uint8`, etc..."

**Comment by rickystewart** [comment]
Maybe the interface boxing still kicks in in that case.

The `must` functions could also take a single literal string instead of a format string and arguments, meaning you could proactively call `fmt.Sprintf()` if you *need* the format string behavior. I suppose that proactively calling `fmt.Sprintf()` would also be slow in hot paths, but presumably you just wouldn't do this in hot code paths -- and to be fair the fact that the `Sprintf()` is "outside of the `must` function" at least means it's obvious when you're doing extra work.

**Comment by erikgrinaker** [comment]
Closing, we'll need a different API, deferring to #94986.
