### ISSUE TITLE
Schema: Add comparator testing in logic tests

### ISSUE THREAD

**Issue by rimadeodhar** [cockroachdb/cockroach#108183]
We should add comparator checks for logic tests where we run the same test with the legacy schema changer and the declarative schema changer. These tests should check that the end state of the data and descriptors after the schema changes are the same for both. This will alert us in events where there is a divergence in the logic between the two schema changers. The legacy schema changer will treated as the ground truth for such tests.

Jira issue: CRDB-30354

Epic CRDB-30346

**Comment by Xiang-Gu** [comment]
I'm starting to look into and proto typing comparator testing in general (https://github.com/cockroachdb/cockroach/issues/108529). Assigning this to myself.
