### ISSUE TITLE
sql: TestDropTableWhileUpgradingFormat is flaky

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#108130]
```
Failed
=== RUN   TestDropTableWhileUpgradingFormat
    test_log_scope.go:167: test logs captured to: /artifacts/tmp/_tmp/c7b6bba0d3ea3d90d4850a610de17c50/logTestDropTableWhileUpgradingFormat3298517991
    test_log_scope.go:81: use -show-logs to present logs inline
    drop_test.go:829: expecting 100 keys, but found 0
    panic.go:522: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/c7b6bba0d3ea3d90d4850a610de17c50/logTestDropTableWhileUpgradingFormat3298517991
--- FAIL: TestDropTableWhileUpgradingFormat (2.45s)
```

https://teamcity.cockroachdb.com/viewLog.html?buildId=11178819&buildTypeId=Cockroach_BazelEssentialCi

https://teamcity.cockroachdb.com/viewLog.html?buildId=11119785&tab=buildResultsDiv&buildTypeId=Cockroach_UnitTests_BazelUnitTests

cc: @chengxiong-ruan 

Jira issue: CRDB-30325

**Comment by chengxiong-ruan** [comment]
Thanks for filing the issue. This seems very odd because the key counting fail after the rows has been committed. We could add some retries (SucceedSoon) to deflake it.

**Comment by yuzefovich** [comment]
I'll close this as a dup of #108340 (since that issue is auto-filed and can be piled on).
