### ISSUE TITLE
sql: support nchar (as an alias?)

### ISSUE THREAD

**Issue by giangpham712** [cockroachdb/cockroach#108159]
**Is your feature request related to a problem? Please describe.**
nchar type is not available in CockroachDB. 

**Describe the solution you'd like**
Can we support it as an alias to the real types

NCHAR(n) n < 256 => CHAR
NCHAR(n) n >= 256 => VCHAR, STRING

**Additional context**
This affects tests in efcore.pg (can be worked-around)

@fqazi 

Jira issue: CRDB-30337

**Comment by fqazi** [comment]
Let's triage this, but this is more in the realm of MS-SQL compatibility, so I think there are going to be no plans to fix this one. I think an alias won't be sufficient from a correctness viewpoint since NCHAR implies UTF-16 encoding (for more complex use cases).

**Comment by rafiss** [comment]
I agree, since Postgres does not have `nchar`, I don't think we should add it to CockroachDB either. I'll close this, but @giangpham712 if you can give more details about this, feel free to comment. What do the EFCore tests do when running against Postgres?
