### ISSUE TITLE
Schema: Add support for UPDATES/DELETEs and non empty tables within schema DML injection tests

### ISSUE THREAD

**Issue by rimadeodhar** [cockroachdb/cockroach#108181]
Extend DML injection for the declarative schema changer to do the following

- Add UPDATES/DELETE into existing tests (constraints, ADD/DROP column, CREATE/DROP index)
- Start using non-empty tables for end-to-end testing for some tests

Testing was written in https://github.com/cockroachdb/cockroach/pull/98692 but this never got merged.

The bug came up in this support case: https://github.com/cockroachlabs/support/issues/2457. The above testing would have prevented the escalation.

Jira issue: CRDB-30351

Epic CRDB-30350

**Comment by fqazi** [comment]
We need to add the following coverage:
1. Ensure that tables are populated before any schema change
2. Manipulate existing and new rows with DML during the schema change at each stage
3. Better validation to ensure that **no** data loss occurs during these schema changes (i.e. something better than counts)

Currently, the coverage here is pretty limited and amounts to:

1. Start with an empty tables
2. IUD some random arbitrary rows during the schema change
3. Do very minimal validation based on row counts

This means it's possible to have data loss bugs when there is existing data or if the manipulation leads to corruption.
