### ISSUE TITLE
dbconsole ui: after setting ui timezone cluster setting to EDT non-admin users continue to see UTC

### ISSUE THREAD

**Issue by thtruo** [cockroachdb/cockroach#108117]
**Describe the problem**

CockroachDB v23.1 introduces a way [view timestamps in DB Console in your preferred timezone](https://www.cockroachlabs.com/docs/stable/ui-overview#db-console-timezone-configuration) using the `ui.display_timezone` cluster setting.

Setting this cluster setting to a non-UTC timezone results in admin users seeing the preferred timezone. However, non-admin users will continue to see UTC timezone, which is an unexpected result. All users (including non-admin users) should see timestamps in the preferred timezone when using the DB Console for that cluster. 

**To Reproduce**

1. Create an admin user 
2. As the *admin* user, run `SET CLUSTER SETTING ui.display_timezone = 'america/new_york';`
3. As an *admin* user, log into the DB Console to verify that timestamps in fact get displayed in EDT (not UTC)
4. For sanity, log into the DB Console as another *admin* user to also verify timestamps get displayed in EDT (not UTC)
5. Now, log into the DB Console as a *non-admin* user. You will see that timestamps get displayed as UTC - this is unexpected!

Example screenshots
* Here is what a *non-admin* user sees (unexpected behavior)
<img width="1007" alt="Screenshot 2023-08-03 at 11 08 32 AM" src="https://github.com/cockroachdb/cockroach/assets/1474303/5abb6147-e590-4c5f-a517-cdeec0375c15">

* Here is what an *admin* user sees (expected behavior)
<img width="1059" alt="Screenshot 2023-08-03 at 11 10 58 AM" src="https://github.com/cockroachdb/cockroach/assets/1474303/d7f76369-9ffd-4456-9d19-98f597592d75">

**Expected behavior**
When a user configures the DB Console timezone display

```SET CLUSTER SETTING ui.display_timezone = 'america/new_york';```

All users accessing the DB Console should see timestamps displayed in that time zone (EDT).

**Environment:**
 - CockroachDB version v23.1.5 and v23.1.6

Jira issue: CRDB-30320

**Comment by thtruo** [comment]
cc @kevin-v-ngo for triage - this was an issue @Leeeeeeeroy-Jenkins encountered with a customer

**Comment by thtruo** [comment]
@THardy98 assigning to you as the Cluster Obs L2

**Comment by THardy98** [comment]
@thtruo or @Leeeeeeeroy-Jenkins  do you know if the non-admin user has `VIEWCLUSTERSETTING` permission?

My immediate suspicion is that the non-admin user doesn't have VIEWCLUSTERSETTING permission, so when they try to read it from the console, it's an undefined value and we default back to UTC.
