### ISSUE TITLE
Two `ALTER` commands on a single line fail

### ISSUE THREAD

**Issue by smcvey** [cockroachdb/cockroach#108253]
**Describe the problem**

Having two `ALTER` commands on the same line produces the error message:

```
ERROR: unexpected value: raw_bytes:"z\311\346;\003\020\200\200\200@\030\200\200\200\200\002\"\004\010\220\277\005(\003P\000X\000x\001" timestamp:<>
```

**To Reproduce**

```
root@localhost:26257/defaultdb> ALTER RANGE default CONFIGURE ZONE USING gc.ttlseconds = 90000; ALTER RANGE default CONFIGURE ZONE USING gc.ttlseconds = 90000;                                                                                             
CONFIGURE ZONE 1
ERROR: unexpected value: raw_bytes:"z\311\346;\003\020\200\200\200@\030\200\200\200\200\002\"\004\010\220\277\005(\003P\000X\000x\001" timestamp:<>
```

However, both `ALTER` commands do take effect despite the error message.  For example, running this will show both 70000 and 60000:

```
ALTER RANGE default CONFIGURE ZONE USING gc.ttlseconds = 70000; SHOW ZONE CONFIGURATIONS; ALTER RANGE default CONFIGURE ZONE USING gc.ttlseconds = 60000; SHOW ZONE CONFIGURATIONS;
```

**Expected behavior**
I would expect both `ALTERS` to return two `CONFIGURE ZONE 1` messages.

**Environment:**
 - CockroachDB version: All 23.1.x
 
**Additional context**
Low impact, just the ominous error message.

Jira issue: CRDB-30386

Epic CRDB-27601

**Comment by dikshant** [comment]
Appears to be an issue with the SQL CLI. Using 22.2 CLI with 23.1 CRDB Server produces the following result:
```
root@localhost:26257/defaultdb> ALTER RANGE default CONFIGURE ZONE USING gc.ttlseconds = 90000; ALTER RANGE default CONFIGURE ZONE USING gc.ttlseconds = 90000;
CONFIGURE ZONE 1
CONFIGURE ZONE 1

Note: timings for multiple statements on a single line are not supported. See https://go.crdb.dev/issue-v/48180/v22.2.
```

**Comment by rafiss** [comment]
Internal slack discussion: https://cockroachlabs.slack.com/archives/CHVV403F0/p1691270552695919

```
CPut /Table/5/1/0/2/1 -> {\x00\x00\x00\x00\x03\x10\x80\x80\x80@\x18\x80\x80\x80\x80\x02\"\x04\b\x90\xbf\x05(\x01P\x00X\x00x\x01 0,0}, expValue: {\x00\x00\x00\x00\x03\x10\x80\x80\x80@\x18\x80\x80\x80\x80\x02\"\x03\b\xc0p(\x01P\x00X\x00x\x01 0,0}
CPut /Table/5/1/0/2/1 -> {\x00\x00\x00\x00\x03\x10\x80\x80\x80@\x18\x80\x80\x80\x80\x02\"\x04\b\x90\xbf\x05(\x01P\x00X\x00x\x01 0,0}, expValue: {\x00\x00\x00\x00\x03\x10\x80\x80\x80@\x18\x80\x80\x80\x80\x02\"\x03\b\xc0p(\x01P\x00X\x00x\x01 0,0}
```
> It looks like the expected values are the same for both statements’ CPuts. Where does the ALTER SET ZONE CONFIGURATION stmt pull the expected value from? If it’s from gossip or some other source that won’t read the first uncommitted write, then this behavior would be explained.

**Comment by rafiss** [comment]
Faizan pointed out that it might be related to caching we added to the Collection.
