### ISSUE TITLE
sql/row: TestRowFetcherReset timed out

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#108247]
See https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/11200233?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

Jira issue: CRDB-30382

**Comment by DrewKimball** [comment]
This was run with a multitenant configuration, maybe we can lump it in with other multitenant timeouts?

**Comment by yuzefovich** [comment]
I'll close this opportunistically as a hardware change [problem](https://cockroachlabs.slack.com/archives/C023S0V4YEB/p1691416850224069).
