### ISSUE TITLE
sql: TestBackupSuccess_base_alter_table_multiple_commands is flaky

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#108221]
Seen here: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/11197865?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildProblemsSection=true&expandBuildTestsSection=true

Jira issue: CRDB-30366

**Comment by jbowens** [comment]
And here: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/11198814?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildTestsSection=true&expandBuildProblemsSection=true

**Comment by mgartner** [comment]
I don't think this is flaky, just broken. I can't get it to pass in CI after 10+ re-runs.

**Comment by rharding6373** [comment]
Another failure: https://teamcity.cockroachdb.com/viewLog.html?buildId=11199019&buildTypeId=Cockroach_Ci_TestsGcpLinuxX8664BigVm_CclUnitTests&tab=buildResultsDiv

The test is timing out:
[shard 7](https://teamcity.cockroachdb.com/repository/download/Cockroach_Ci_TestsGcpLinuxX8664BigVm_CclUnitTests/11199019:id/bazel-testlogs/pkg/ccl/schemachangerccl/schemachangerccl_test/shard_7_of_48/test.log):
```
=== RUN   TestBackupSuccessMixedVersion_base_alter_table_alter_primary_key_drop_rowid/post_commit_stage_10_of_15
panic: test timed out after 14m55s
```

[shard 16](https://teamcity.cockroachdb.com/repository/download/Cockroach_Ci_TestsGcpLinuxX8664BigVm_CclUnitTests/11199019:id/bazel-testlogs/pkg/ccl/schemachangerccl/schemachangerccl_test/shard_16_of_48/test.log):
```
=== RUN   TestBackupSuccess_base_alter_table_multiple_commands/post_commit_stage_18_of_31
panic: test timed out after 14m55s
```

There don't appear to be any changes to the testdata directory in 2 weeks, so something else caused the test time to go over the test timeout, maybe.

**Comment by otan** [comment]
maybe #108238 is the CI issue

**Comment by pavelkalinnikov** [comment]
Multiple tests under `TestBackupSuccessMixedVersion_base_alter_table_alter_primary_key_drop_rowid` failed [here](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/11230787?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildTestsSection=true&expandBuildProblemsSection=true).
