### ISSUE TITLE
pkg/sql/schemachanger/scbuild/scbuild_test: TestBuildIsMemoryMonitored failed

### ISSUE THREAD

**Issue by koorosh** [cockroachdb/cockroach#108293]
`pkg/sql/schemachanger/scbuild/scbuild_test.TestBuildIsMemoryMonitored` [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/11199965?buildTab=tests&expandedTest=build%3A%28id%3A11199943%29%2Cid%3A181792) on release-23.1 @ 5230230a98d2669b294bc564bc2d5c1b1fbd2f88

Jira issue: CRDB-30415

**Comment by rafiss** [comment]
this timed out, and likely caused by https://cockroachlabs.slack.com/archives/CJ0H8Q97C/p1691424868840639?thread_ts=1691421937.376619&cid=CJ0H8Q97C
