### ISSUE TITLE
acceptance: TestCompose/ComposeGSSPython failed

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#108248]
See https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/11204775?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

Jira issue: CRDB-30383

**Comment by rafiss** [comment]
```
python_1     | Password for tester@MY.EX: 
python_1     | Creating test user
python_1     | psql: could not connect to server: Connection refused
python_1     | 	Is the server running on host "cockroach" (192.168.16.3) and accepting
python_1     | 	TCP/IP connections on port 26257?
cockroach_1  | *
cockroach_1  | * WARNING: Running a server without --sql-addr, with a combined RPC/SQL listener, is deprecated.
cockroach_1  | * This feature will be removed in a later version of CockroachDB.
cockroach_1  | *
```

Theory: is the `python` container trying to connect to CRDB before the `cockroach` container is ready to serve SQL connections?

**Comment by rafiss** [comment]
There was an infra change on Friday that caused various timeouts and flakes. https://cockroachlabs.slack.com/archives/CJ0H8Q97C/p1691424868840639?thread_ts=1691421937.376619&cid=CJ0H8Q97C

I'm going to consider this as related to that issue, but we can reopen if needed.
