### ISSUE TITLE
Set public = t for sql.telemetry.query_sampling.max_event_frequency cluster setting

### ISSUE THREAD

**Issue by florence-crl** [cockroachdb/cockroach#108385]
This setting needs to be documented according to [DOC-8029](https://cockroachlabs.atlassian.net/browse/DOC-8029):

```
sql.telemetry.query_sampling.max_event_frequency
```

However it is not publicly documented on [the cluster settings page](https://www.cockroachlabs.com/docs/v23.1/cluster-settings) because it has public = f in crdb_internal.cluster_settings. The cluster settings page is automatically generated with settings where public = t.

Describe the solution you'd like
Please set public = t for the above cluster setting.

**Comment by emilaleksanteri** [comment]
Is this one still open and could I take this issue?
