### ISSUE TITLE
perf: multi-range request performance is very bad

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#10833]
<img width="932" alt="screen shot 2016-11-19 at 2 33 04 pm" src="https://cloud.githubusercontent.com/assets/6201335/20457941/29526352-ae65-11e6-8392-c97fd0326242.png">

The above graph was taken from a freshly created 3-node cluster with 3 block_writers configured `--batch 10`. The initial peak of performance occurs when there is only 1 range in the `datablocks.blocks` table. When that range splits, performance drops from ~990 ops/sec to ~330 ops/sec. When the 2 ranges split into 4, performance drops again to ~40 ops/sec.

Cc @cockroachdb/stability, @spencerkimball

**Comment by bdarnell** [comment]
Which commit was this running? Specifically, was the NoopRequest command queue change in or out (#10832)? That change removed a major bottleneck for multi-range operations.

**Comment by petermattis** [comment]
I believe this was running on my PR that reverted the NoopRequest command queue change. So recent master. You're correct that those NoopRequests are a serious bottleneck for multi-range operations and my other testing where I've left that fix in don't show this performance degradation.

**Comment by bdarnell** [comment]
OK, so I guess we should close this until we have something more actionable. (I'm sure there's more work to be done for multi-range request performance)
