### ISSUE TITLE
opt: add variable or hint to favor lookup joins for INSERT ON CONFLICT arbiter check

### ISSUE THREAD

**Issue by michae2** [cockroachdb/cockroach#108338]
`INSERT ... ON CONFLICT` internally checks an arbiter index before modifying the target table. This check is sometimes performed as a hash join over a full scan if it looks cheap enough to the optimizer. For example, this performs a full scan of `a`:

```sql
CREATE TABLE a (a INT PRIMARY KEY);
INSERT INTO a SELECT 2 * generate_series(0, 999);
ANALYZE a;
INSERT INTO a SELECT generate_series(0, 999) ON CONFLICT DO NOTHING;
```

The plan:

```
demo@127.0.0.1:26257/demoapp/defaultdb> EXPLAIN INSERT INTO a SELECT generate_series(0, 999) ON CONFLICT DO NOTHING;
                                           info
-------------------------------------------------------------------------------------------
  distribution: local
  vectorized: true

  • insert
  │ into: a(a)
  │ auto commit
  │ arbiter indexes: a_pkey
  │
  └── • distinct
      │ estimated row count: 7
      │ distinct on: generate_series
      │ nulls are distinct
      │
      └── • hash join (anti)
          │ estimated row count: 9
          │ equality: (generate_series) = (a)
          │ right cols are key
          │
          ├── • project set
          │   │ estimated row count: 10
          │   │
          │   └── • emptyrow
          │
          └── • scan
                estimated row count: 1 (100% of the table; stats collected 3 seconds ago)
                table: a@a_pkey
                spans: FULL SCAN
(27 rows)
```

Sometimes we'd like to force a lookup join instead of a hash join over a full scan, but currently there is no way to do this. One idea is to add a session variable analogous to `prefer_lookup_joins_for_fks` but for arbiter checks instead of FK checks. Another idea is to expand the `ON CONSTRAINT a_pkey` syntax to support index flag hints like `ON CONSTRAINT a_pkey@{NO_FULL_SCAN}`.

Jira issue: CRDB-30430

**Comment by mgartner** [comment]
I think #137984 addressed this, correct @rytaft?

**Comment by rytaft** [comment]
Yes it did. It's not specific to the arbiter check since it avoids all full scans in mutation queries, but I think it addresses the need here. Closing.
