### ISSUE TITLE
kvclient: v23.1.8: attempting to append refresh spans after the tracked timestamp has moved forward

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#108440]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4383065146/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4383065146/?referrer=webhooks_plugin)

Panic Message:

```
txn_interceptor_span_refresher.go:650: attempting to append refresh spans after the tracked timestamp has moved forward. batchTimestamp: 1691589809.933718037,0 refreshedTimestamp: 1691589810.014246522,1
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnSpanRefresher).assertRefreshSpansAtInvalidTimestamp
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go:650
  | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnSpanRefresher).importLeafFinalState
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go:690
  | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*TxnCoordSender).UpdateRootWithLeafFinalState
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_coord_sender.go:1279
  | github.com/cockroachdb/cockroach/pkg/kv.(*Txn).UpdateRootWithLeafFinalState
  | 	github.com/cockroachdb/cockroach/pkg/kv/txn.go:1303
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLReceiver).pushMeta
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1339
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLReceiver).Push
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1421
  | github.com/cockroachdb/cockroach/pkg/sql/execinfra.Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/execinfra/base.go:195
  | github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBaseNoHelper).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:726
  | github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:575
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:310
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:902
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).planAndRunPostquery
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:2165
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).planAndRunChecksInParallel.func5
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:2250
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).planAndRunChecksInParallel.func6
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:2301
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (3) attempting to append refresh spans after the tracked timestamp has moved forward. batchTimestamp: 1691589809.933718037,0 refreshedTimestamp: 1691589810.014246522,1
Error types: (1) *assert.withAssertionFailure (2) *withstack.withStack (3) *errutil.leafError
-- report composition:
*errutil.leafError: attempting to append refresh spans after the tracked timestamp has moved forward. batchTimestamp: 1691589809.933718037,0 refreshedTimestamp: 1691589810.014246522,1
txn_interceptor_span_refresher.go:650: *withstack.withStack (top exception)
*assert.withAssertionFailure
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/util/stop/stopper.go#L469-L471](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/util/stop/stopper.go#L469-L471)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/sql/distsql_running.go#L2300-L2302](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/sql/distsql_running.go#L2300-L2302)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/sql/distsql_running.go#L2249-L2251](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/sql/distsql_running.go#L2249-L2251)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/sql/distsql_running.go#L2164-L2166](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/sql/distsql_running.go#L2164-L2166)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/sql/distsql_running.go#L901-L903](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/sql/distsql_running.go#L901-L903)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/sql/colflow/vectorized_flow.go#L309-L311](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/sql/colflow/vectorized_flow.go#L309-L311)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/sql/flowinfra/flow.go#L574-L576](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/sql/flowinfra/flow.go#L574-L576)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/sql/execinfra/processorsbase.go#L725-L727](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/sql/execinfra/processorsbase.go#L725-L727)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/sql/execinfra/base.go#L194-L196](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/sql/execinfra/base.go#L194-L196)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/sql/distsql_running.go#L1420-L1422](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/sql/distsql_running.go#L1420-L1422)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/sql/distsql_running.go#L1338-L1340](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/sql/distsql_running.go#L1338-L1340)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/txn.go#L1302-L1304](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/txn.go#L1302-L1304)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L1278-L1280](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L1278-L1280)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go#L689-L691](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go#L689-L691)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go#L649-L651](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go#L649-L651)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 470
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).planAndRunChecksInParallel.func6 at line 2301
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).planAndRunChecksInParallel.func5 at line 2250
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).planAndRunPostquery at line 2165
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).Run at line 902
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlow).Run at line 310
pkg/sql/flowinfra/flow.go in pkg/sql/flowinfra.(*FlowBase).Run at line 575
pkg/sql/execinfra/processorsbase.go in pkg/sql/execinfra.(*ProcessorBaseNoHelper).Run at line 726
pkg/sql/execinfra/base.go in pkg/sql/execinfra.Run at line 195
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLReceiver).Push at line 1421
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLReceiver).pushMeta at line 1339
pkg/kv/txn.go in pkg/kv.(*Txn).UpdateRootWithLeafFinalState at line 1303
pkg/kv/kvclient/kvcoord/txn_coord_sender.go in pkg/kv/kvclient/kvcoord.(*TxnCoordSender).UpdateRootWithLeafFinalState at line 1279
pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go in pkg/kv/kvclient/kvcoord.(*txnSpanRefresher).importLeafFinalState at line 690
pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go in pkg/kv/kvclient/kvcoord.(*txnSpanRefresher).assertRefreshSpansAtInvalidTimestamp at line 650
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v23.1.8 |
| Go Version | go1.19.10 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.8 |
| Cockroach SHA | 2c1d4afd2c2de091a00a4dba4392ceeaf8504a95 |
| # of CPUs | 2 |
| # of Goroutines | 394 |

Jira issue: CRDB-30474

**Comment by yuzefovich** [comment]
Based on the discussion in #108853, it seems likely that the parallel execution of postqueries is to blame.

**Comment by nvanbenschoten** [comment]
From https://github.com/cockroachdb/cockroach/issues/108853#issuecomment-1696135044:

> However, I don't think the explanation here directly explains https://github.com/cockroachdb/cockroach/issues/108440 as well. Parallel execution of postqueries appears to be related to that sentry issue, but the symptoms there look almost like a RootTxn was used concurrently with a LeafTxn. Either `forwardRefreshTimestampOnRefresh` or `forwardRefreshTimestampOnResponse` must have been called on a RootTxn while a LeafTxn was outstanding.

**Comment by yuzefovich** [comment]
Hm, I looked over the code multiple times, and I don't see the problem. I agree with Nathan it appears that we must have called `forwardRefreshTimestampOnRefresh` or `forwardRefreshTimestampOnResponse` on the RootTxn (these methods don't get called on the LeafTxns) while there was a LeafTxn outstanding (which later produced the LeafTxnFinalState).

Re: (from #108853):
> Another place where similar concurrency takes place is `UpdateRootWithLeafFinalState` call in `DistSQLReceiver.pushMeta` - multiple parallel checks can call that, is that problematic too?

I looked over `UpdateRootWithLeafFinalState` and didn't find anything concerning.

In the last 90 days on sentry we've seen this issue occur 8 times ([7](https://cockroach-labs.sentry.io/issues/4319811807/?query=is%3Aunresolved+%22attempting+to+append+refresh+spans%22&referrer=issue-stream&statsPeriod=90d&stream_index=2) and [1](https://cockroach-labs.sentry.io/issues/4383065146/?query=is%3Aunresolved+%22attempting+to+append+refresh+spans%22&referrer=issue-stream&statsPeriod=90d&stream_index=3) on two different clusters, the latter being on CC) around parallel postqueries and  [435](https://cockroach-labs.sentry.io/issues/4235464108/?query=is%3Aunresolved+%22attempting+to+append+refresh+spans%22&referrer=issue-stream&statsPeriod=90d&stream_index=0) times on a different cluster without parallel postqueries (but with the internal executor).

Unfortunately, I don't think we'll be able to make progress on this without a reliable repro, so closing as unreproducible.
