### ISSUE TITLE
sql: DROP TYPE CASCADE is not yet supported

### ISSUE THREAD

**Issue by giangpham712** [cockroachdb/cockroach#108431]
**Describe the problem**

DROP TYPE CASCADE is not yet supported

Sample SQL:

```
DROP TYPE "public"."Mood" CASCADE
```

**Additional context**
This affects efcore.pg tests

@fqazi 

Jira issue: CRDB-30468

**Comment by giangpham712** [comment]
This issue has been tracked by another ticket https://github.com/cockroachdb/cockroach/issues/51480

**Comment by rafiss** [comment]
Closing in favor of https://github.com/cockroachdb/cockroach/issues/51480

For the purpose of EFCore testing, we should skip the tests that require `DROP TYPE CASCADE`
