### ISSUE TITLE
TryDecorrelateScalarGroupBy related issue

### ISSUE THREAD

**Issue by chaiyi123** [cockroachdb/cockroach#108423]
TryDecorrelateScalarGroupBy "pushes down" a Join into a ScalarGroupBy operator. 
if we use the RowNumber operator to uniquely number the rows, and at this point, the pushed down expression is hashjoin during execution.
The result will be a disorder in the rownum column, causing the operator that aggregates according to rownum to be hashaggregate.
Causes the order of the any_not_null aggregated result set to be random for each execution.
If you perform a sum operation on the float type later.When precision is lost, the result of each execution is different.
such:
group                                         |                     |                                                                                                                                       
      │                                            |aggregate 0          |any_not_null                                                                                                                           
      │                                            |aggregate 1          |sum(any_not_null)                                                                                                                      
      │                                            |group by             |any_not_null                                                                                                                           
      └── render                                   |                     |                                                                                                                                       
           │                                       |any_not_null         |any_not_null                                                                                                                           
           │                                       |any_not_null         |any_not_null                                                                                                                           
           └── group                               |                     |                                                                                                                                       
                │                                  |aggregate 0          |rownum                                                                                                                                 
                │                                  |aggregate 1          |any_not_null(current)                                                                                                                  
                │                                  |aggregate 2          |any_not_null(typename)                                                                                                                 
                │                                  |group by             |rownum                                                                                                                                 
                └── render                         |                     |                                                                                                                                       
                     │                             |typename             |typename                                                                                                                               
                     │                             |current              |current                                                                                                                                
                     │                             |rownum               |rownum                                                                                                                                 
                     └── hash-join               |                     |             
                                    │              |type                 |inner                                                                                                                                  
                                    │              |equality             |(deviceid, modelid) = (deviceid, modelid)                                                                                              
                                    │              |right cols are key   |                     
                                    ├── ordinality |                     |                                                                                                                                       
                                    │    └──scan|                     |                                                                                                                                       
                                    │              |table                |MeterSuper@primary
                                    └── scan       |                     |                                                                                                                                       
                                                   |table                |device@device_auto_index_fk_modelid_ref_devicemodel                                                                                    
                                                   |spans                |FULL SCAN      

May I ask how to solve this problem?Looking forward to your reply

Jira issue: CRDB-30462

**Comment by mgartner** [comment]
@chaiyi123 do you have an example of SQL that produces an incorrect result? I believe that you're suggesting that an incorrect result is possible because of the problem you describe.

**Comment by mgartner** [comment]
@chaiyi123 just checking in - did you have an example of a query that produces incorrect results?

**Comment by yuzefovich** [comment]
Please reach out if you can provide an example, otherwise we're closing this as unactionable.
