### ISSUE TITLE
sql: use Gets in lookup and index joins whenever possible

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#108489]
When evaluating the lookup joins if `LookupColumnsAreKey` is set, I believe it'd be valid to use `Get` requests for tables with a single column family in all cases. In particular, currently if we're looking up into the secondary non-UNIQUE index, we issue a `Scan` request, but given lookup columns form a key, we know that the lookup will result in at most one KV, so I believe it'd be safe to use a `Get` request.

We should also audit the index join in case we can use `Get` requests in more cases there too.

We should think through whether presence of NULLs would affect this proposal.

Jira issue: CRDB-30490

**Comment by yuzefovich** [comment]
Over in #111173 I spent some time attempting to address this issue only to realize that it doesn't seem possible to use Gets when looking up into non-unique secondary indexes. The problem is that for such indexes we append the primary key columns as the index key "suffix", and we don't know values of those columns to be able to generate the correct key for the Get.

Consider the following setup and the query:
```sql
CREATE TABLE t1 (k1 INT PRIMARY KEY, FAMILY (k1));
CREATE TABLE t2 (k2 INT PRIMARY KEY, i2 INT, u2 INT, INDEX (i2, u2), UNIQUE INDEX (u2), FAMILY (k2, i2, u2));
INSERT INTO t1 VALUES (2);
INSERT INTO t2 VALUES (1, 2, 3);

SELECT k2 FROM t1 INNER LOOKUP JOIN t2 ON i2 = k1 AND u2 = 3 WHERE k1 = 2;
```
This is the case this issue talks about (lookup into non-unique secondary index but with "lookup columns are key" attribute). 

After having scanned `t1` and using the constant value for `u2`, we know that we need to lookup into index on `(i2, u2)` for which `i2 = k1 = 2, u2 = 3` (i.e. `/Table/t2/Index/2/2/3`). Currently we construct a Scan of `/Table/t2/Index/2/2/{3-4}`. The actual key at which the KV is stored in the secondary index is `/Table/t2/Index/2/2/3/1/0` (`k2 = 1` is PK and `/0` for family ID), and there doesn't appear to be a way to come up with that key from `/Table/t2/Index/2/2/3` since we don't know the value of PK. The Scan does contain the actual key, so no issue there.

(In theory, we could take advantage of "lookup columns are key" to set the limit on the BatchRequest since we know that each span will result in at most one row (i.e. at most # column families KVs); however, setting those limits would disable the parallelism that is currently present in the join reader, and I'd guess the parallelism is much more important for performance rather than short-circuiting each Scan a bit earlier.)

I'm inclined to close this issue as unachievable, but I see that @michae2 mentioned it over in #107961, so it'd be good to sanity check this reasoning.

**Comment by michae2** [comment]
> I'm inclined to close this issue as unachievable, but I see that @michae2 mentioned it over in https://github.com/cockroachdb/cockroach/pull/107961, so it'd be good to sanity check this reasoning.

I think your reasoning is correct. It's fine to close this.
