### ISSUE TITLE
After dropping a table/relation in Cockroach 23.1, the `\d table` command can start to fail for every execution

### ISSUE THREAD

**Issue by nexdrew** [cockroachdb/cockroach#108482]
**Describe the problem**

We recently began upgrading our Cockroach clusters from 22.2 to 23.1. We ran into an issue with one of our non-production clusters getting hung up on one of the internal upgrade finalization jobs but were able to get past it with help from support. Regardless, on all of the clusters we have upgraded so far (2 clusters on Linux/Ubuntu and 1 cluster on Docker-on-Mac) or created fresh on version 23.1.8 (1 cluster on Docker-on-Mac) and applied our schema changes (which include several creates, alters, and some drops), I get errors trying to use the [`\d <pattern>` command](https://www.cockroachlabs.com/docs/v23.1/cockroach-sql#commands) like this:

```
root@localhost:26257/api> \d org
ERROR: descriptor is being dropped
```

which eventually turns into this (after the descriptor is dropped, I suppose):

```
root@localhost:26257/api> \d org
ERROR: relation "[113]" does not exist
SQLSTATE: 42P01
```

Listing relations via `\d` (by itself) works, but using the command to display columns for a table (e.g. `\d table_name` or `\d+ table_name`) always produces an error, regardless of the table/pattern used.

**To Reproduce**

Perhaps it is related to dropping a table.

The simplest reproduction I have is creating two tables, dropping one of them, and then trying `\d table2`.

1. Start a local cluster of 3 nodes in Docker using the [docker-compose.yml file here](https://gist.github.com/nexdrew/1aa7537438dd90de049c98ee81ef03d8) and running `docker compose up -d`
2. Initialize the cluster via `docker exec -it db1 ./cockroach init --insecure`
3. Create a database via `docker exec -it db1 ./cockroach sql --insecure -e 'CREATE DATABASE IF NOT EXISTS api;'`
4. Open a sql shell via `docker exec -it db1 ./cockroach sql --insecure -d api`
5. Create a table via `CREATE TABLE table1 (id STRING(36) NOT NULL PRIMARY KEY);`
6. Create another table via `CREATE TABLE table2 (id STRING(36) NOT NULL PRIMARY KEY);`
7. Drop the first table via `DROP TABLE table1;`
8. Describe the 2nd table via `\d table2`
9. Get error `ERROR: descriptor is being dropped` (and eventually `ERROR: relation "[107]" does not exist`)

If it doesn't error for you the first time around, trying recreating the dropped table and then dropping the other one. Eventually one of the `\d table_name` commands will start to fail.

**Expected behavior**

I expect the `\d table2` command to work, displaying output like the following:

```
Table "public.table2"
  Column |   Type   | Collation | Nullable | Default
---------+----------+-----------+----------+----------
  id     | text(40) |           | not null |
(1 row)
                  Indexes
-------------------------------------------
  table2_pkey PRIMARY KEY, btree (id ASC)
(1 row)
```

**Environment:**
 - CockroachDB version: 23.1.8
 - Server OS: macOS 13.5, Docker 24.0.5
 - Client app: sql shell via `cockroach sql`

**Additional context**

Instead of being able to use `\d table_name`, it is a minor inconvenience having to use `show columns from table_name;` instead, but this is a regression and "breaks" compatibility with Postgres.

Jira issue: CRDB-30488

Epic CRDB-27601

**Comment by rafiss** [comment]
Thanks for the report! We'll investigate this, and until we fix it, a workaround is to use the commands `SHOW TABLES;`, `SHOW COLUMNS FROM table2;` and `SHOW INDEXES FROM table2;`

**Comment by nexdrew** [comment]
> a workaround is to use the commands `SHOW TABLES;`, `SHOW COLUMNS FROM table2;` and `SHOW INDEXES FROM table2;`

Yep, that's what I've been using.

Please let me know if you have problems reproducing the error following my steps above, or if you would just like more information from me.

Thanks @rafiss

**Comment by rafiss** [comment]
Notes for how we probably will need to resolve this: let's track down the internal query that `\d` uses. It should be hitting a virtual table in either pg_catalog or information_schema. The `populate` function for that virtual table is likely not skipping dropped tables correctly.

**Comment by knz** [comment]
@nexdrew properly identified that this is related to  #108813.
