### ISSUE TITLE
row: v22.2.12: index out of range in getSpanID in txnKVStreamer

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#108572]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4386912966/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4386912966/?referrer=webhooks_plugin)

Panic Message:

```
error.go:89: unexpected error from the vectorized engine: runtime error: index out of range [1] with length 1
(1)
Wraps: (2)
Wraps: (3)
Wraps: (4) assertion failure
Wraps: (5) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:89
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | runtime.goPanicIndex
  | 	GOROOT/src/runtime/panic.go:113
  | github.com/cockroachdb/cockroach/pkg/sql/row.(*txnKVStreamer).getSpanID
  | 	github.com/cockroachdb/cockroach/pkg/sql/row/kv_batch_streamer.go:109
  | github.com/cockroachdb/cockroach/pkg/sql/row.(*txnKVStreamer).proceedWithLastResult
  | 	github.com/cockroachdb/cockroach/pkg/sql/row/kv_batch_streamer.go:121
  | github.com/cockroachdb/cockroach/pkg/sql/row.(*txnKVStreamer).nextBatch
  | 	github.com/cockroachdb/cockroach/pkg/sql/row/kv_batch_streamer.go:177
  | github.com/cockroachdb/cockroach/pkg/sql/row.(*txnKVStreamer).nextBatch
  | 	github.com/cockroachdb/cockroach/pkg/sql/row/kv_batch_streamer.go:194
  | github.com/cockroachdb/cockroach/pkg/sql/row.(*KVFetcher).NextKV
  | 	github.com/cockroachdb/cockroach/pkg/sql/row/kv_fetcher.go:264
  | github.com/cockroachdb/cockroach/pkg/sql/row.(*Fetcher).nextKey
  | 	github.com/cockroachdb/cockroach/pkg/sql/row/fetcher.go:665
  | github.com/cockroachdb/cockroach/pkg/sql/row.(*Fetcher).startScan
  | 	github.com/cockroachdb/cockroach/pkg/sql/row/fetcher.go:635
  | github.com/cockroachdb/cockroach/pkg/sql/row.(*Fetcher).StartScan
  | 	github.com/cockroachdb/cockroach/pkg/sql/row/fetcher.go:492
  | github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*rowFetcherStatCollector).StartScan
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowexec/stats.go:103
  | github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*joinReader).readInput
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowexec/joinreader.go:999
  | github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*joinReader).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowexec/joinreader.go:731
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Columnarizer).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/columnarizer.go:243
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:116
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:124
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*allSpooler).spool
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/sort.go:136
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*sortOp).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/sort.go:280
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk.(*diskSpillerBase).Next.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk/disk_spiller.go:198
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk.(*diskSpillerBase).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk/disk_spiller.go:196
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:116
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:124
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Materializer).next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:286
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Materializer).nextAdapter
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:311
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Materializer).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:317
  | github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*inputStatCollector).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowexec/stats.go:69
  | github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*joinReader).readInput
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowexec/joinreader.go:846
Wraps: (6) unexpected error from the vectorized engine
Wraps: (7) runtime error: index out of range [1] with length 1
  | -- cause hidden behind barrier
  | runtime error: index out of range [1] with length 1
  | (1) runtime error: index out of range [1] with length 1
  | Error types: (1) runtime.boundsError
Error types: (1) *colexecerror.notInternalError (2) *colexecerror.notInternalError (3) *colexecerror.notInternalError (4) *assert.withAssertionFailure (5) *withstack.withStack (6) *errutil.withPrefix (7) *barriers.barrierErr
-- report composition:
*barriers.barrierErr: masked error: runtime error: index out of range [1] with length 1
*errutil.withPrefix: unexpected error from the vectorized engine
error.go:89: *withstack.withStack (top exception)
*assert.withAssertionFailure
*colexecerror.notInternalError
*colexecerror.notInternalError
*colexecerror.notInternalError
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/rowexec/joinreader.go#L845-L847](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/rowexec/joinreader.go#L845-L847)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/rowexec/stats.go#L68-L70](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/rowexec/stats.go#L68-L70)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/colexec/materializer.go#L316-L318](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/colexec/materializer.go#L316-L318)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/colexec/materializer.go#L310-L312](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/colexec/materializer.go#L310-L312)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/colexec/materializer.go#L285-L287](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/colexec/materializer.go#L285-L287)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/colflow/stats.go#L123-L125](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/colflow/stats.go#L123-L125)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/colflow/stats.go#L115-L117](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/colflow/stats.go#L115-L117)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/colexec/colexecdisk/disk_spiller.go#L195-L197](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/colexec/colexecdisk/disk_spiller.go#L195-L197)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/colexec/colexecdisk/disk_spiller.go#L197-L199](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/colexec/colexecdisk/disk_spiller.go#L197-L199)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/colexec/sort.go#L279-L281](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/colexec/sort.go#L279-L281)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/colexec/sort.go#L135-L137](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/colexec/sort.go#L135-L137)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/colflow/stats.go#L123-L125](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/colflow/stats.go#L123-L125)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/colflow/stats.go#L115-L117](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/colflow/stats.go#L115-L117)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/colexec/columnarizer.go#L242-L244](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/colexec/columnarizer.go#L242-L244)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/rowexec/joinreader.go#L730-L732](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/rowexec/joinreader.go#L730-L732)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/rowexec/joinreader.go#L998-L1000](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/rowexec/joinreader.go#L998-L1000)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/rowexec/stats.go#L102-L104](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/rowexec/stats.go#L102-L104)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/row/fetcher.go#L491-L493](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/row/fetcher.go#L491-L493)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/row/fetcher.go#L634-L636](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/row/fetcher.go#L634-L636)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/row/fetcher.go#L664-L666](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/row/fetcher.go#L664-L666)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/row/kv_fetcher.go#L263-L265](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/row/kv_fetcher.go#L263-L265)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/row/kv_batch_streamer.go#L193-L195](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/row/kv_batch_streamer.go#L193-L195)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/row/kv_batch_streamer.go#L176-L178](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/row/kv_batch_streamer.go#L176-L178)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/row/kv_batch_streamer.go#L120-L122](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/row/kv_batch_streamer.go#L120-L122)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/row/kv_batch_streamer.go#L108-L110](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/row/kv_batch_streamer.go#L108-L110)
[GOROOT/src/runtime/panic.go#L112-L114](GOROOT/src/runtime/panic.go#L112-L114)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/colexecerror/error.go#L88-L90](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/colexecerror/error.go#L88-L90)
</details>

```
pkg/sql/rowexec/joinreader.go in pkg/sql/rowexec.(*joinReader).readInput at line 846
pkg/sql/rowexec/stats.go in pkg/sql/rowexec.(*inputStatCollector).Next at line 69
pkg/sql/colexec/materializer.go in pkg/sql/colexec.(*Materializer).Next at line 317
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colexec/materializer.go in pkg/sql/colexec.(*Materializer).nextAdapter at line 311
pkg/sql/colexec/materializer.go in pkg/sql/colexec.(*Materializer).next at line 286
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).Next at line 124
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).next at line 116
pkg/sql/colexec/colexecdisk/disk_spiller.go in pkg/sql/colexec/colexecdisk.(*diskSpillerBase).Next at line 196
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colexec/colexecdisk/disk_spiller.go in pkg/sql/colexec/colexecdisk.(*diskSpillerBase).Next.func1 at line 198
pkg/sql/colexec/sort.go in pkg/sql/colexec.(*sortOp).Next at line 280
pkg/sql/colexec/sort.go in pkg/sql/colexec.(*allSpooler).spool at line 136
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).Next at line 124
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).next at line 116
pkg/sql/colexec/columnarizer.go in pkg/sql/colexec.(*Columnarizer).Next at line 243
pkg/sql/rowexec/joinreader.go in pkg/sql/rowexec.(*joinReader).Next at line 731
pkg/sql/rowexec/joinreader.go in pkg/sql/rowexec.(*joinReader).readInput at line 999
pkg/sql/rowexec/stats.go in pkg/sql/rowexec.(*rowFetcherStatCollector).StartScan at line 103
pkg/sql/row/fetcher.go in pkg/sql/row.(*Fetcher).StartScan at line 492
pkg/sql/row/fetcher.go in pkg/sql/row.(*Fetcher).startScan at line 635
pkg/sql/row/fetcher.go in pkg/sql/row.(*Fetcher).nextKey at line 665
pkg/sql/row/kv_fetcher.go in pkg/sql/row.(*KVFetcher).NextKV at line 264
pkg/sql/row/kv_batch_streamer.go in pkg/sql/row.(*txnKVStreamer).nextBatch at line 194
pkg/sql/row/kv_batch_streamer.go in pkg/sql/row.(*txnKVStreamer).nextBatch at line 177
pkg/sql/row/kv_batch_streamer.go in pkg/sql/row.(*txnKVStreamer).proceedWithLastResult at line 121
pkg/sql/row/kv_batch_streamer.go in pkg/sql/row.(*txnKVStreamer).getSpanID at line 109
GOROOT/src/runtime/panic.go in runtime.goPanicIndex at line 113
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1 at line 89
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v22.2.12 |
| Go Version | go1.19.6 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v22.2.12 |
| Cockroach SHA | feededb3d12a703bada7699b65ad1e191f97a91b |
| # of CPUs | 8 |
| # of Goroutines | 3342 |

Jira issue: CRDB-30524

**Comment by yuzefovich** [comment]
I think it's possible that #115569 fixed this, so closing optimistically.
