### ISSUE TITLE
multiregion: v23.1.6: duplicate region × found in super region ×

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#108556]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4386539462/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4386539462/?referrer=webhooks_plugin)

Panic Message:

```
region_config.go:464: duplicate region × found in super region ×
(1)
Wraps: (2) assertion failure
Wraps: (3) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/multiregion.ValidateSuperRegions
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/multiregion/region_config.go:464
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/multiregion.ValidateRegionConfig
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/multiregion/region_config.go:391
  | github.com/cockroachdb/cockroach/pkg/sql.SynthesizeRegionConfig
  | 	github.com/cockroachdb/cockroach/pkg/sql/region_util.go:1455
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).refreshZoneConfigsForTables
  | 	github.com/cockroachdb/cockroach/pkg/sql/region_util.go:1022
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).addSuperRegion
  | 	github.com/cockroachdb/cockroach/pkg/sql/alter_database.go:1908
  | github.com/cockroachdb/cockroach/pkg/sql.(*alterDatabaseAddSuperRegion).startExec
  | 	github.com/cockroachdb/cockroach/pkg/sql/alter_database.go:1601
  | github.com/cockroachdb/cockroach/pkg/sql.startExec.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan.go:519
  | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:112
  | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:299
  | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:79
  | github.com/cockroachdb/cockroach/pkg/sql.walkPlan
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:43
  | github.com/cockroachdb/cockroach/pkg/sql.startExec
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan.go:522
  | github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Start
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:174
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Columnarizer).Init
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/columnarizer.go:183
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).init
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:94
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).Init
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:103
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).init.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:245
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).init
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:244
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:278
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:325
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:902
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1913
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll.func3
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1645
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1648
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2103
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1656
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:964
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:142
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2986
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:141
Wraps: (4) duplicate region × found in super region ×
Error types: (1) *colexecerror.notInternalError (2) *assert.withAssertionFailure (3) *withstack.withStack (4) *errutil.leafError
-- report composition:
*errutil.leafError: duplicate region × found in super region ×
region_config.go:464: *withstack.withStack (top exception)
*assert.withAssertionFailure
*colexecerror.notInternalError
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/conn_executor_exec.go#L140-L142](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/conn_executor_exec.go#L140-L142)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/conn_executor_exec.go#L2985-L2987](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/conn_executor_exec.go#L2985-L2987)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/conn_executor_exec.go#L141-L143](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/conn_executor_exec.go#L141-L143)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/conn_executor_exec.go#L963-L965](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/conn_executor_exec.go#L963-L965)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/conn_executor_exec.go#L1655-L1657](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/conn_executor_exec.go#L1655-L1657)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/conn_executor_exec.go#L2102-L2104](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/conn_executor_exec.go#L2102-L2104)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/distsql_running.go#L1647-L1649](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/distsql_running.go#L1647-L1649)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/distsql_running.go#L1644-L1646](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/distsql_running.go#L1644-L1646)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/distsql_running.go#L1912-L1914](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/distsql_running.go#L1912-L1914)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/distsql_running.go#L901-L903](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/distsql_running.go#L901-L903)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/colflow/vectorized_flow.go#L324-L326](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/colflow/vectorized_flow.go#L324-L326)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/colflow/flow_coordinator.go#L277-L279](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/colflow/flow_coordinator.go#L277-L279)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/colflow/flow_coordinator.go#L243-L245](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/colflow/flow_coordinator.go#L243-L245)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/colflow/flow_coordinator.go#L244-L246](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/colflow/flow_coordinator.go#L244-L246)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/colflow/stats.go#L102-L104](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/colflow/stats.go#L102-L104)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/colflow/stats.go#L93-L95](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/colflow/stats.go#L93-L95)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/colexec/columnarizer.go#L182-L184](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/colexec/columnarizer.go#L182-L184)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/plan_node_to_row_source.go#L173-L175](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/plan_node_to_row_source.go#L173-L175)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/plan.go#L521-L523](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/plan.go#L521-L523)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/walk.go#L42-L44](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/walk.go#L42-L44)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/walk.go#L78-L80](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/walk.go#L78-L80)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/walk.go#L298-L300](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/walk.go#L298-L300)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/walk.go#L111-L113](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/walk.go#L111-L113)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/plan.go#L518-L520](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/plan.go#L518-L520)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/alter_database.go#L1600-L1602](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/alter_database.go#L1600-L1602)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/alter_database.go#L1907-L1909](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/alter_database.go#L1907-L1909)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/region_util.go#L1021-L1023](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/region_util.go#L1021-L1023)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/region_util.go#L1454-L1456](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/region_util.go#L1454-L1456)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/catalog/multiregion/region_config.go#L390-L392](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/catalog/multiregion/region_config.go#L390-L392)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/catalog/multiregion/region_config.go#L463-L465](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/catalog/multiregion/region_config.go#L463-L465)
</details>

```
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 141
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithProfiling at line 2986
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt.func1 at line 142
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 964
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchToExecutionEngine at line 1656
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithDistSQLEngine at line 2103
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRunAll at line 1648
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRunAll.func3 at line 1645
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRun at line 1913
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).Run at line 902
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlow).Run at line 325
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).Run at line 278
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).init at line 244
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).init.func1 at line 245
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).Init at line 103
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).init at line 94
pkg/sql/colexec/columnarizer.go in pkg/sql/colexec.(*Columnarizer).Init at line 183
pkg/sql/plan_node_to_row_source.go in pkg/sql.(*planNodeToRowSource).Start at line 174
pkg/sql/plan.go in pkg/sql.startExec at line 522
pkg/sql/walk.go in pkg/sql.walkPlan at line 43
pkg/sql/walk.go in pkg/sql.(*planVisitor).visit at line 79
pkg/sql/walk.go in pkg/sql.(*planVisitor).visitInternal at line 299
pkg/sql/walk.go in pkg/sql.(*planVisitor).visitInternal.func1 at line 112
pkg/sql/plan.go in pkg/sql.startExec.func2 at line 519
pkg/sql/alter_database.go in pkg/sql.(*alterDatabaseAddSuperRegion).startExec at line 1601
pkg/sql/alter_database.go in pkg/sql.(*planner).addSuperRegion at line 1908
pkg/sql/region_util.go in pkg/sql.(*planner).refreshZoneConfigsForTables at line 1022
pkg/sql/region_util.go in pkg/sql.SynthesizeRegionConfig at line 1455
pkg/sql/catalog/multiregion/region_config.go in pkg/sql/catalog/multiregion.ValidateRegionConfig at line 391
pkg/sql/catalog/multiregion/region_config.go in pkg/sql/catalog/multiregion.ValidateSuperRegions at line 464
```

### Tags

| Tag | Value |
| --- | --- |
| Command | demo |
| Environment | v23.1.6 |
| Go Version | go1.19.10 |
| Platform | darwin arm64 |
| Distribution | CCL |
| Cockroach Release | v23.1.6 |
| Cockroach SHA | 3bacdbe302c436675605f3256025829e63c45330 |
| # of CPUs | 10 |
| # of Goroutines | 3376 |

Jira issue: CRDB-30518

**Comment by rafiss** [comment]
Simple repro:
```
./cockroach demo --global --nodes=9

> ALTER DATABASE defaultdb set PRIMARY REGION 'us-east1';
> alter database defaultdb add super region 's' values 'us-east1', 'europe-west1', 'europe-west1';

*
* ERROR: Queued as error df939b19f2ae4392a091bf1b53a3f8f0
*
ERROR: internal error: duplicate region europe-west1 found in super region s
SQLSTATE: XX000
DETAIL: stack trace:
github.com/cockroachdb/cockroach/pkg/sql/catalog/multiregion/region_config.go:464: ValidateSuperRegions()
github.com/cockroachdb/cockroach/pkg/sql/catalog/multiregion/region_config.go:391: ValidateRegionConfig()
github.com/cockroachdb/cockroach/pkg/sql/region_util.go:1455: SynthesizeRegionConfig()
github.com/cockroachdb/cockroach/pkg/sql/region_util.go:1022: refreshZoneConfigsForTables()
github.com/cockroachdb/cockroach/pkg/sql/alter_database.go:1908: addSuperRegion()
github.com/cockroachdb/cockroach/pkg/sql/alter_database.go:1601: startExec()
github.com/cockroachdb/cockroach/pkg/sql/plan.go:519: func2()
github.com/cockroachdb/cockroach/pkg/sql/walk.go:112: func1()
github.com/cockroachdb/cockroach/pkg/sql/walk.go:299: visitInternal()
github.com/cockroachdb/cockroach/pkg/sql/walk.go:79: visit()
github.com/cockroachdb/cockroach/pkg/sql/walk.go:43: walkPlan()
github.com/cockroachdb/cockroach/pkg/sql/plan.go:522: startExec()
github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:174: Start()
github.com/cockroachdb/cockroach/pkg/sql/colexec/columnarizer.go:183: Init()
github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:94: init()
github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92: CatchVectorizedRuntimeError()
github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:103: Init()
github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:245: func1()
github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92: CatchVectorizedRuntimeError()
github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:244: init()
github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:278: Run()
github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:325: Run()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:902: Run()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1913: PlanAndRun()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1645: func3()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1648: PlanAndRunAll()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2103: execWithDistSQLEngine()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1656: dispatchToExecutionEngine()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:964: execStmtInOpenState()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:142: func1()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2986: execWithProfiling()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:141: execStmt()
```

**Comment by fqazi** [comment]
Merged via: https://github.com/cockroachdb/cockroach/pull/110083
