### ISSUE TITLE
cluster settings: add setting class to naming

### ISSUE THREAD

**Issue by j82w** [cockroachdb/cockroach#108508]
Problem: 
Cluster settings have [3 options](https://github.com/cockroachdb/cockroach/blob/a598a75435f6426236dde569191fbd95871f24ae/pkg/settings/setting.go#L114), and there is no way for users and/or engineers to know which setting is for which tenant. This causes confusion and requires either trying it on each of the different tenants or looking up the code to see what the settings option is specified in the code. 

Solution:
Add the cluster setting type to the cluster naming. Existing cluster settings can not be renamed because it would be a breaking change. The way to workaround this 
1. Define the new naming schema and force all new cluster settings to follow it to stop the issue from growing. 
2. Add alias support to the cluster naming. That way all existing settings can be renamed to the new format, but still support the original name. 

```go
// SystemOnly settings are associated with single-tenant clusters and host
// clusters. Settings with this class do not exist on non-system tenants and
// can only be used by the system tenant.
SystemOnly Class = iota

// TenantReadOnly settings are visible to non-system tenants but cannot be
// modified by the tenant. Values for these settings are set from the system
// tenant and propagated from the host cluster.
TenantReadOnly

// TenantWritable settings are visible to and can be modified by non-system
// tenants. The system can still override these settings; the overrides are
// propagated from the host cluster.
TenantWritable
```

Jira issue: CRDB-30501
Epic: CRDB-6671

**Comment by knz** [comment]
We have addressed this issue in the following ways:

- there is a new CLI command `cockroach gen settings-list --show-class`  that displays which setting has which class, so someone doesn't need to look at the source code.
- we have greatly enhanced the explanation of which class is for which purpose, through extensive docstrings in settings/setting.go
- we have created a framework to rename setting, and defined a more comprehensive naming guide on the public wiki https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/3151757461/Guidelines+for+Cluster+Settings+CLI+flags+and+Env+vars

The one thing we have decided NOT to do was to include the class as part of the setting name. It's unclear what actual user problem this would solve, AND it would introduce a new problem: it would require us to teach the user what this means and i would make it hard(er) to change the class in the future.
