### ISSUE TITLE
Sentry: replica_proposal.go:531: log.Fatal: checksum for AddSSTable at index term 8, index 86 does not match; at proposal time 44d74f4d (1154961229), now 33a0d680 (866178688)
(1) attached stack trace
...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#108674]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4391422541/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4391422541/?referrer=webhooks_plugin)

Panic Message:

```
replica_proposal.go:531: log.Fatal: checksum for AddSSTable at index term 8, index 86 does not match; at proposal time 44d74f4d (1154961229), now 33a0d680 (866178688)
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.addSSTablePreApply
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go:531
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*replicaAppBatch).runPreApplyTriggersAfterStagingWriteBatch
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_application_state_machine.go:663
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*replicaAppBatch).Stage
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_application_state_machine.go:553
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply.mapCmdIter
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply/cmd.go:184
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply.(*Task).applyOneBatch
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply/task.go:279
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply.(*Task).ApplyCommittedEntries
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply/task.go:246
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:1049
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReady
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:668
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processReady
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:641
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).worker
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:308
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:489
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (2) log.Fatal: checksum for AddSSTable at index term 8, index 86 does not match; at proposal time 44d74f4d (1154961229), now 33a0d680 (866178688)
Error types: (1) *withstack.withStack (2) *errutil.leafError
-- report composition:
*errutil.leafError: log.Fatal: checksum for AddSSTable at index term 8, index 86 does not match; at proposal time 44d74f4d (1154961229), now 33a0d680 (866178688)
replica_proposal.go:531: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/util/stop/stopper.go#L488-L490](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/util/stop/stopper.go#L488-L490)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L307-L309](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L307-L309)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L640-L642](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L640-L642)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L667-L669](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L667-L669)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L1048-L1050](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L1048-L1050)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/kv/kvserver/apply/task.go#L245-L247](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/kv/kvserver/apply/task.go#L245-L247)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/kv/kvserver/apply/task.go#L278-L280](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/kv/kvserver/apply/task.go#L278-L280)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/kv/kvserver/apply/cmd.go#L183-L185](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/kv/kvserver/apply/cmd.go#L183-L185)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/kv/kvserver/pkg/kv/kvserver/replica_application_state_machine.go#L552-L554](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/kv/kvserver/pkg/kv/kvserver/replica_application_state_machine.go#L552-L554)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/kv/kvserver/pkg/kv/kvserver/replica_application_state_machine.go#L662-L664](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/kv/kvserver/pkg/kv/kvserver/replica_application_state_machine.go#L662-L664)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go#L530-L532](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go#L530-L532)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 489
pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go in pkg/kv/kvserver.(*raftScheduler).worker at line 308
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).processReady at line 641
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).handleRaftReady at line 668
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked at line 1049
pkg/kv/kvserver/apply/task.go in pkg/kv/kvserver/apply.(*Task).ApplyCommittedEntries at line 246
pkg/kv/kvserver/apply/task.go in pkg/kv/kvserver/apply.(*Task).applyOneBatch at line 279
pkg/kv/kvserver/apply/cmd.go in pkg/kv/kvserver/apply.mapCmdIter at line 184
pkg/kv/kvserver/pkg/kv/kvserver/replica_application_state_machine.go in pkg/kv/kvserver.(*replicaAppBatch).Stage at line 553
pkg/kv/kvserver/pkg/kv/kvserver/replica_application_state_machine.go in pkg/kv/kvserver.(*replicaAppBatch).runPreApplyTriggersAfterStagingWriteBatch at line 663
pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go in pkg/kv/kvserver.addSSTablePreApply at line 531
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v22.2.12 |
| Go Version | go1.19.6 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v22.2.12 |
| Cockroach SHA | feededb3d12a703bada7699b65ad1e191f97a91b |
| # of CPUs | 32 |
| # of Goroutines | 552 |

Jira issue: CRDB-30581

**Comment by yuzefovich** [comment]
unactionable
