### ISSUE TITLE
Sentry: replica_raftstorage.go:569: log.Fatal: unable to load replica state: open ×: stale NFS file handle
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/kv/kvser...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#108687]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4393252530/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4393252530/?referrer=webhooks_plugin)

Panic Message:

```
replica_raftstorage.go:569: log.Fatal: unable to load replica state: open ×: stale NFS file handle
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).applySnapshot
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raftstorage.go:569
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:927
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processRaftSnapshotRequest.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:465
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).withReplicaForRequest
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:343
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processRaftSnapshotRequest
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:406
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).receiveSnapshot
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_snapshot.go:1091
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).HandleSnapshot.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:211
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:322
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).HandleSnapshot
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:208
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*RaftTransport).RaftSnapshot
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/raft_transport.go:382
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver._MultiRaft_RaftSnapshot_Handler
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/bazel-out/k8-opt/bin/pkg/kv/kvserver/kvserver_go_proto_/github.com/cockroachdb/cockroach/pkg/kv/kvserver/storage_services.pb.go:263
  | github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor.StreamServerInterceptor.func1
  | 	github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go:164
  | google.golang.org/grpc.chainStreamInterceptors.func1.1
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1482
  | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func4
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:285
  | google.golang.org/grpc.chainStreamInterceptors.func1.1
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1485
  | github.com/cockroachdb/cockroach/pkg/rpc.kvAuth.streamInterceptor
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/auth.go:167
  | google.golang.org/grpc.chainStreamInterceptors.func1.1
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1485
  | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func2.1
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:252
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:322
  | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:251
  | google.golang.org/grpc.chainStreamInterceptors.func1.1
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1485
  | google.golang.org/grpc.chainStreamInterceptors.func1
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1487
  | google.golang.org/grpc.(*Server).processStreamingRPC
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1636
  | google.golang.org/grpc.(*Server).handleStream
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1717
  | google.golang.org/grpc.(*Server).serveStreams.func1.2
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:965
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (2) secondary error attachment
  | open ×: stale NFS file handle
  | (1) attached stack trace
  |   -- stack trace:
  |   | github.com/cockroachdb/pebble/vfs.defaultFS.Open
  |   | 	github.com/cockroachdb/pebble/vfs/external/com_github_cockroachdb_pebble/vfs/vfs.go:226
  |   | github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFS).Open
  |   | 	github.com/cockroachdb/pebble/vfs/external/com_github_cockroachdb_pebble/vfs/disk_health.go:680
  |   | github.com/cockroachdb/pebble/vfs.(*enospcFS).Open
  |   | 	github.com/cockroachdb/pebble/vfs/external/com_github_cockroachdb_pebble/vfs/disk_full.go:223
  |   | github.com/cockroachdb/pebble/objstorage.(*Provider).vfsOpenForReading
  |   | 	github.com/cockroachdb/pebble/objstorage/external/com_github_cockroachdb_pebble/objstorage/vfs.go:21
  |   | github.com/cockroachdb/pebble/objstorage.(*Provider).OpenForReadingMustExist
  |   | 	github.com/cockroachdb/pebble/objstorage/external/com_github_cockroachdb_pebble/objstorage/provider.go:256
  |   | github.com/cockroachdb/pebble.(*tableCacheValue).load
  |   | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/table_cache.go:935
  |   | github.com/cockroachdb/pebble.(*tableCacheShard).findNode.func2
  |   | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/table_cache.go:707
  |   | runtime/pprof.Do
  |   | 	GOROOT/src/runtime/pprof/runtime.go:40
  |   | github.com/cockroachdb/pebble.(*tableCacheShard).findNode
  |   | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/table_cache.go:706
  |   | github.com/cockroachdb/pebble.(*tableCacheShard).newIters
  |   | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/table_cache.go:374
  |   | github.com/cockroachdb/pebble.(*tableCacheContainer).newIters
  |   | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/table_cache.go:139
  |   | github.com/cockroachdb/pebble.(*levelIter).loadFile
  |   | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/level_iter.go:669
  |   | github.com/cockroachdb/pebble.(*levelIter).SeekPrefixGE
  |   | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/level_iter.go:752
  |   | github.com/cockroachdb/pebble.(*mergingIter).seekGE
  |   | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go:1044
  |   | github.com/cockroachdb/pebble.(*mergingIter).SeekPrefixGE
  |   | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go:1120
  |   | github.com/cockroachdb/pebble/internal/keyspan.(*InterleavingIter).SeekPrefixGE
  |   | 	github.com/cockroachdb/pebble/internal/keyspan/external/com_github_cockroachdb_pebble/internal/keyspan/interleaving_iter.go:293
  |   | github.com/cockroachdb/pebble.(*Iterator).SeekPrefixGE
  |   | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/iterator.go:1412
  |   | github.com/cockroachdb/cockroach/pkg/storage.(*pebbleIterator).SeekGE
  |   | 	github.com/cockroachdb/cockroach/pkg/storage/pebble_iterator.go:333
  |   | github.com/cockroachdb/cockroach/pkg/storage.(*pebbleMVCCScanner).get
  |   | 	github.com/cockroachdb/cockroach/pkg/storage/pebble_mvcc_scanner.go:559
  |   | github.com/cockroachdb/cockroach/pkg/storage.mvccGetWithValueHeader
  |   | 	github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:1162
  |   | github.com/cockroachdb/cockroach/pkg/storage.MVCCGetWithValueHeader
  |   | 	github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:1087
  |   | github.com/cockroachdb/cockroach/pkg/storage.MVCCGet
  |   | 	github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:1057
  |   | github.com/cockroachdb/cockroach/pkg/storage.MVCCGetProto
  |   | 	github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:816
  |   | github.com/cockroachdb/cockroach/pkg/kv/kvserver/stateloader.StateLoader.LoadLease
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/stateloader/stateloader.go:159
  |   | github.com/cockroachdb/cockroach/pkg/kv/kvserver/stateloader.StateLoader.Load
  |   | 	github.com/coc...
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L964-L966](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L964-L966)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1716-L1718](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1716-L1718)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1635-L1637](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1635-L1637)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1486-L1488](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1486-L1488)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1484-L1486](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1484-L1486)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/rpc/pkg/rpc/context.go#L250-L252](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/rpc/pkg/rpc/context.go#L250-L252)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/util/stop/stopper.go#L321-L323](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/util/stop/stopper.go#L321-L323)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/rpc/pkg/rpc/context.go#L251-L253](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/rpc/pkg/rpc/context.go#L251-L253)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1484-L1486](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1484-L1486)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/rpc/pkg/rpc/auth.go#L166-L168](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/rpc/pkg/rpc/auth.go#L166-L168)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1484-L1486](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1484-L1486)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/rpc/pkg/rpc/context.go#L284-L286](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/rpc/pkg/rpc/context.go#L284-L286)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1481-L1483](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1481-L1483)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go#L163-L165](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go#L163-L165)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/bazel-out/k8-opt/bin/pkg/kv/kvserver/kvserver_go_proto_/github.com/cockroachdb/cockroach/pkg/kv/kvserver/storage_services.pb.go#L262-L264](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/bazel-out/k8-opt/bin/pkg/kv/kvserver/kvserver_go_proto_/github.com/cockroachdb/cockroach/pkg/kv/kvserver/storage_services.pb.go#L262-L264)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/pkg/kv/kvserver/raft_transport.go#L381-L383](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/pkg/kv/kvserver/raft_transport.go#L381-L383)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L207-L209](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L207-L209)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/util/stop/stopper.go#L321-L323](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/util/stop/stopper.go#L321-L323)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L210-L212](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L210-L212)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/pkg/kv/kvserver/store_snapshot.go#L1090-L1092](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/pkg/kv/kvserver/store_snapshot.go#L1090-L1092)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L405-L407](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L405-L407)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L342-L344](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L342-L344)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L464-L466](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L464-L466)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L926-L928](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L926-L928)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/pkg/kv/kvserver/replica_raftstorage.go#L568-L570](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/pkg/kv/kvserver/replica_raftstorage.go#L568-L570)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.(*Server).serveStreams.func1.2 at line 965
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.(*Server).handleStream at line 1717
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.(*Server).processStreamingRPC at line 1636
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.chainStreamInterceptors.func1 at line 1487
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.chainStreamInterceptors.func1.1 at line 1485
pkg/rpc/pkg/rpc/context.go in pkg/rpc.NewServerEx.func2 at line 251
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunTaskWithErr at line 322
pkg/rpc/pkg/rpc/context.go in pkg/rpc.NewServerEx.func2.1 at line 252
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.chainStreamInterceptors.func1.1 at line 1485
pkg/rpc/pkg/rpc/auth.go in pkg/rpc.kvAuth.streamInterceptor at line 167
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.chainStreamInterceptors.func1.1 at line 1485
pkg/rpc/pkg/rpc/context.go in pkg/rpc.NewServerEx.func4 at line 285
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.chainStreamInterceptors.func1.1 at line 1482
pkg/util/tracing/grpcinterceptor/grpc_interceptor.go in pkg/util/tracing/grpcinterceptor.StreamServerInterceptor.func1 at line 164
pkg/kv/kvserver/bazel-out/k8-opt/bin/pkg/kv/kvserver/kvserver_go_proto_/github.com/cockroachdb/cockroach/pkg/kv/kvserver/storage_services.pb.go in pkg/kv/kvserver._MultiRaft_RaftSnapshot_Handler at line 263
pkg/kv/kvserver/pkg/kv/kvserver/raft_transport.go in pkg/kv/kvserver.(*RaftTransport).RaftSnapshot at line 382
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).HandleSnapshot at line 208
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunTaskWithErr at line 322
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).HandleSnapshot.func1 at line 211
pkg/kv/kvserver/pkg/kv/kvserver/store_snapshot.go in pkg/kv/kvserver.(*Store).receiveSnapshot at line 1091
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).processRaftSnapshotRequest at line 406
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).withReplicaForRequest at line 343
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).processRaftSnapshotRequest.func1 at line 465
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked at line 927
pkg/kv/kvserver/pkg/kv/kvserver/replica_raftstorage.go in pkg/kv/kvserver.(*Replica).applySnapshot at line 569
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v23.1.8 |
| Go Version | go1.19.10 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.8 |
| Cockroach SHA | 2c1d4afd2c2de091a00a4dba4392ceeaf8504a95 |
| # of CPUs | 6 |
| # of Goroutines | 437 |

Jira issue: CRDB-30591

**Comment by yuzefovich** [comment]
dup of #86703
