### ISSUE TITLE
kvserver: consider increasing closed timestamp interval defaults

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#108656]
Currently, we publish rangefeed closed timestamp updates every 200ms. This is controlled by two settings:

* `kv.rangefeed.closed_timestamp_refresh_interval = 0` (defaults to `kv.closed_timestamp.side_transport_interval`)
* `kv.closed_timestamp.side_transport_interval = '200ms'`

For the purposes of rangefeeds, this is overly aggressive, and can lead to excessive load with large numbers of ranges (see #96395). The target duration `kv.closed_timestamp.target_duration = '3s'` is one order of magnitude larger than the refresh interval, and the default changefeed `min_checkpoint_frequency = '30s'` is two orders of magnitude larger.

We should increase the default of either `kv.rangefeed.closed_timestamp_refresh_interval` or `kv.closed_timestamp.side_transport_interval` to e.g. 1 second, which is still sufficient for rangefeeds, and can significantly reduce CPU usage on nodes with many replicas.

Preferably `kv.closed_timestamp.side_transport_interval`, since users may already have set this higher (e.g. to 30 seconds), and defaulting `kv.rangefeed.closed_timestamp_refresh_interval` to e.g. 1 second instead of the side transport interval can cause significant load increases when the effective default changes from 30 seconds to 1 second.

Jira issue: CRDB-30568

Epic CRDB-26372

**Comment by erikgrinaker** [comment]
cc @cockroachdb/cdc

**Comment by erikgrinaker** [comment]
With 60k replicas per node and an idle changefeed, increasing `kv.rangefeed.closed_timestamp_refresh_interval` to 1s reduces CPU usage from 50% to 20%. The side transport overhead is negligible even at 200ms, about 3.85% of the remaining 20% CPU usage. Additionally increasing `kv.closed_timestamp.side_transport_interval` to 1s did not have noticable impact on node CPU.

<img width="927" alt="Screenshot 2023-08-12 at 13 39 49" src="https://github.com/cockroachdb/cockroach/assets/644420/10fa1ea1-88b6-45b4-ac62-d0e40ffadd8f">

Keeping `kv.closed_timestamp.side_transport_interval` at 200ms by default `kv.rangefeed.closed_timestamp_refresh_interval` would probably be better for follower read latency. However, if we go for changing the `kv.rangefeed.closed_timestamp_refresh_interval` then we'll have to notify/educate users to reset `kv.closed_timestamp.side_transport_interval` and instead use `kv.rangefeed.closed_timestamp_refresh_interval` to control rangefeed closed timestamps.

@nvanbenschoten What's your take on this wrt. follower reads?

**Comment by nvanbenschoten** [comment]
> With 60k replicas per node and an idle changefeed, increasing kv.rangefeed.closed_timestamp_refresh_interval to 1s reduces CPU usage from 50% to 20%. The side transport overhead is negligible even at 200ms, about 3.85% of the remaining 20% CPU usage. Additionally increasing kv.closed_timestamp.side_transport_interval to 1s did not have noticable impact on node CPU.

This matches expectations and was good to confirm. As we have seen in other tests, the dominant CPU cost is from the `closedts-rangefeed-updater`'s fanout of checkpoints to each rangefeed (`O(num_ranges_with_rangefeeds)`), not from the closed timestamp side transport (`~O(1)`).

I'd suggest we increase the default of `kv.rangefeed.closed_timestamp_refresh_interval` to 1s (or even more, e.g. 3s) but don't touch `kv.closed_timestamp.side_transport_interval`. `kv.closed_timestamp.side_transport_interval` has more dependencies and wider effects. It affects the lag time for follower reads on REGIONAL tables and the lead time of writes on GLOBAL tables (and by extension their commit wait duration). Also, even if we were ok with those effects, migrating in a change to the closed timestamp interval may prove difficult for mixed-version clusters.

One thing to confirm with either of these changes is that it doesn't negatively impact end-to-end CDC latency. My rough understanding is that without https://github.com/cockroachdb/cockroach/pull/99890, we wait for checkpoints in the CDC processor before joining updates with their SQL schema and publishing them. That's likely not the full story, so it's worth getting a better understanding from the experts (@miretskiy) of the effect that increasing `kv.rangefeed.closed_timestamp_refresh_interval` will have on changefeeds.

**Comment by erikgrinaker** [comment]
Thanks, I think we'll go with `kv.rangefeed.closed_timestamp_refresh_interval = '1s'` here then, and call it out in release notes. When combined with mux and the rangefeed scheduler prototype we're down to 10% idle CPU, and I'm optimistic we can get this down below 5% with further optimization.

@miretskiy has wanted to reduce the frequency here as well, but would be good to get his input on this.

**Comment by miretskiy** [comment]
> One thing to confirm with either of these changes is that it doesn't negatively impact end-to-end CDC latency. 

@nvanbenschoten my understanding, perhaps incorrect, was that we've been using this setting as some sort of a proxy for changefeed latency; in reality this does not preclude changefeed from receiving the event -- all that this setting is doing is 
making changefeed checkpoint lag a bit further behind -- how much? probably negligible since  long time ago I slowed checkpoint rate to 30s by default.   In short, I think it's a good move, but we do have some customers where we need to communicate this change.

**Comment by erikgrinaker** [comment]
I think what @nvanbenschoten is referring to is [`changefeed.experimental_poll_interval`](https://github.com/cockroachdb/cockroach/blob/4445c5926fbde33aeace6bb4e1cebdcfbb4ca756/pkg/ccl/changefeedccl/changefeedbase/settings.go#L25-L31). Changefeeds poll table descriptors every second to monitor for schema changes, and buffer events until the next poll. This is orthogonal to rangefeed resolved timestamps.

I tested this by running a changefeed with `min_checkpoint_frequency = '5s'` and `kv.rangefeed.closed_timestamp_refresh_interval = '30s'`, and events were emitted within seconds.
