### ISSUE TITLE
ui: DBConsole incorrectly displays "Completion Time" for running job

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#108635]
"Completion Time" incorrectly displays current time for running job:
<img width="1357" alt="Screenshot 2023-08-11 at 4 14 34 PM" src="https://github.com/cockroachdb/cockroach/assets/54641364/8d595c92-6bca-4591-89c5-cac02bdce33f">

Easiest way to repro: start job that runs for long time, for example (assuming demo db):
`CREATE CHANGEFEED FOR vehicles INTO 'null://'`
This new job should not have completion time displayed (since this is a forever running changefeed).

Jira issue: CRDB-30560

**Comment by maryliag** [comment]
Issue fixed.
