### ISSUE TITLE
sql: CREATE DOMAIN is not yet supported

### ISSUE THREAD

**Issue by giangpham712** [cockroachdb/cockroach#108659]
Trying to run the following SQL
```
CREATE DOMAIN non_nullable_int AS int NOT NULL;
```

returns error `ERROR: at or near "as": syntax error: unimplemented: this syntax`

**Additional context**
This affects efcore.pg tests

@fqazi 

Jira issue: CRDB-30571

**Comment by rafiss** [comment]
I will close this and we will track it in https://github.com/cockroachdb/cockroach/issues/27796 instead.

For now, let's skip the EFCore tests that need `DOMAIN`.
