### ISSUE TITLE
Sentry: panic.go:884: runtime error: slice bounds out of range [122:15]
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | runtime.goPanicSliceB
  ...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#108705]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4394303631/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4394303631/?referrer=webhooks_plugin)

Panic Message:

```
panic.go:884: runtime error: slice bounds out of range [122:15]
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | runtime.goPanicSliceB
  | 	GOROOT/src/runtime/panic.go:153
  | github.com/cockroachdb/cockroach/pkg/util/encoding.DecodeUntaggedBytesValue
  | 	github.com/cockroachdb/cockroach/pkg/util/encoding/encoding.go:2709
  | github.com/cockroachdb/cockroach/pkg/sql/rowenc/valueside.DecodeUntaggedDatum
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowenc/valueside/decode.go:64
  | github.com/cockroachdb/cockroach/pkg/sql/rowenc/valueside.Decode
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowenc/valueside/decode.go:42
  | github.com/cockroachdb/cockroach/pkg/sql/rowenc.(*EncDatum).EnsureDecoded
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowenc/encoded_datum.go:256
  | github.com/cockroachdb/cockroach/pkg/sql/row.(*Fetcher).NextRowDecodedInto
  | 	github.com/cockroachdb/cockroach/pkg/sql/row/fetcher.go:1175
  | github.com/cockroachdb/cockroach/pkg/sql/backfill.(*ColumnBackfiller).RunColumnBackfillChunk
  | 	github.com/cockroachdb/cockroach/pkg/sql/backfill/backfill.go:357
  | github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*columnBackfiller).runChunk.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowexec/columnbackfiller.go:132
  | github.com/cockroachdb/cockroach/pkg/kv.runTxn.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:980
  | github.com/cockroachdb/cockroach/pkg/kv.(*Txn).exec
  | 	github.com/cockroachdb/cockroach/pkg/kv/txn.go:961
  | github.com/cockroachdb/cockroach/pkg/kv.runTxn
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:979
  | github.com/cockroachdb/cockroach/pkg/kv.(*DB).TxnWithAdmissionControl
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:942
  | github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*columnBackfiller).runChunk
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowexec/columnbackfiller.go:114
  | github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*backfiller).mainLoop
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowexec/backfiller.go:154
  | github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*backfiller).doRun
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowexec/backfiller.go:107
  | github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*backfiller).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowexec/backfiller.go:95
  | github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:480
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:731
  | github.com/cockroachdb/cockroach/pkg/sql.(*SchemaChanger).distColumnBackfill.func3
  | 	github.com/cockroachdb/cockroach/pkg/sql/backfill.go:1348
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutorFactory).DescsTxn.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1453
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutorFactory).DescsTxnWithExecutor.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1420
  | github.com/cockroachdb/cockroach/pkg/kv.runTxn.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:980
  | github.com/cockroachdb/cockroach/pkg/kv.(*Txn).exec
  | 	github.com/cockroachdb/cockroach/pkg/kv/txn.go:961
  | github.com/cockroachdb/cockroach/pkg/kv.runTxn
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:979
  | github.com/cockroachdb/cockroach/pkg/kv.(*DB).TxnWithAdmissionControl
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:942
  | github.com/cockroachdb/cockroach/pkg/kv.(*DB).Txn
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:921
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutorFactory).DescsTxnWithExecutor
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1412
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutorFactory).DescsTxn
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1448
  | github.com/cockroachdb/cockroach/pkg/sql.(*SchemaChanger).txn
  | 	github.com/cockroachdb/cockroach/pkg/sql/schema_changer.go:2475
  | github.com/cockroachdb/cockroach/pkg/sql.(*SchemaChanger).distColumnBackfill
  | 	github.com/cockroachdb/cockroach/pkg/sql/backfill.go:1307
  | github.com/cockroachdb/cockroach/pkg/sql.(*SchemaChanger).truncateAndBackfillColumns
  | 	github.com/cockroachdb/cockroach/pkg/sql/backfill.go:2236
Wraps: (2) runtime error: slice bounds out of range [122:15]
Error types: (1) *withstack.withStack (2) runtime.boundsError
-- report composition:
runtime.boundsError
panic.go:884: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/sql/backfill.go#L2235-L2237](https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/sql/backfill.go#L2235-L2237)
[https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/sql/backfill.go#L1306-L1308](https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/sql/backfill.go#L1306-L1308)
[https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/sql/schema_changer.go#L2474-L2476](https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/sql/schema_changer.go#L2474-L2476)
[https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/sql/internal.go#L1447-L1449](https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/sql/internal.go#L1447-L1449)
[https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/sql/internal.go#L1411-L1413](https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/sql/internal.go#L1411-L1413)
[https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/kv/db.go#L920-L922](https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/kv/db.go#L920-L922)
[https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/kv/db.go#L941-L943](https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/kv/db.go#L941-L943)
[https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/kv/db.go#L978-L980](https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/kv/db.go#L978-L980)
[https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/kv/txn.go#L960-L962](https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/kv/txn.go#L960-L962)
[https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/kv/db.go#L979-L981](https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/kv/db.go#L979-L981)
[https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/sql/internal.go#L1419-L1421](https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/sql/internal.go#L1419-L1421)
[https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/sql/internal.go#L1452-L1454](https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/sql/internal.go#L1452-L1454)
[https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/sql/backfill.go#L1347-L1349](https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/sql/backfill.go#L1347-L1349)
[https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/sql/distsql_running.go#L730-L732](https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/sql/distsql_running.go#L730-L732)
[https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/sql/flowinfra/flow.go#L479-L481](https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/sql/flowinfra/flow.go#L479-L481)
[https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/sql/rowexec/backfiller.go#L94-L96](https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/sql/rowexec/backfiller.go#L94-L96)
[https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/sql/rowexec/backfiller.go#L106-L108](https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/sql/rowexec/backfiller.go#L106-L108)
[https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/sql/rowexec/backfiller.go#L153-L155](https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/sql/rowexec/backfiller.go#L153-L155)
[https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/sql/rowexec/columnbackfiller.go#L113-L115](https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/sql/rowexec/columnbackfiller.go#L113-L115)
[https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/kv/db.go#L941-L943](https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/kv/db.go#L941-L943)
[https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/kv/db.go#L978-L980](https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/kv/db.go#L978-L980)
[https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/kv/txn.go#L960-L962](https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/kv/txn.go#L960-L962)
[https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/kv/db.go#L979-L981](https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/kv/db.go#L979-L981)
[https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/sql/rowexec/columnbackfiller.go#L131-L133](https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/sql/rowexec/columnbackfiller.go#L131-L133)
[https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/sql/backfill/backfill.go#L356-L358](https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/sql/backfill/backfill.go#L356-L358)
[https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/sql/row/fetcher.go#L1174-L1176](https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/sql/row/fetcher.go#L1174-L1176)
[https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/sql/rowenc/encoded_datum.go#L255-L257](https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/sql/rowenc/encoded_datum.go#L255-L257)
[https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/sql/rowenc/valueside/decode.go#L41-L43](https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/sql/rowenc/valueside/decode.go#L41-L43)
[https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/sql/rowenc/valueside/decode.go#L63-L65](https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/sql/rowenc/valueside/decode.go#L63-L65)
[https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/util/encoding/encoding.go#L2708-L2710](https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/util/encoding/encoding.go#L2708-L2710)
[GOROOT/src/runtime/panic.go#L152-L154](GOROOT/src/runtime/panic.go#L152-L154)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
</details>

```
pkg/sql/backfill.go in pkg/sql.(*SchemaChanger).truncateAndBackfillColumns at line 2236
pkg/sql/backfill.go in pkg/sql.(*SchemaChanger).distColumnBackfill at line 1307
pkg/sql/schema_changer.go in pkg/sql.(*SchemaChanger).txn at line 2475
pkg/sql/internal.go in pkg/sql.(*InternalExecutorFactory).DescsTxn at line 1448
pkg/sql/internal.go in pkg/sql.(*InternalExecutorFactory).DescsTxnWithExecutor at line 1412
pkg/kv/db.go in pkg/kv.(*DB).Txn at line 921
pkg/kv/db.go in pkg/kv.(*DB).TxnWithAdmissionControl at line 942
pkg/kv/db.go in pkg/kv.runTxn at line 979
pkg/kv/txn.go in pkg/kv.(*Txn).exec at line 961
pkg/kv/db.go in pkg/kv.runTxn.func1 at line 980
pkg/sql/internal.go in pkg/sql.(*InternalExecutorFactory).DescsTxnWithExecutor.func2 at line 1420
pkg/sql/internal.go in pkg/sql.(*InternalExecutorFactory).DescsTxn.func1 at line 1453
pkg/sql/backfill.go in pkg/sql.(*SchemaChanger).distColumnBackfill.func3 at line 1348
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).Run at line 731
pkg/sql/flowinfra/flow.go in pkg/sql/flowinfra.(*FlowBase).Run at line 480
pkg/sql/rowexec/backfiller.go in pkg/sql/rowexec.(*backfiller).Run at line 95
pkg/sql/rowexec/backfiller.go in pkg/sql/rowexec.(*backfiller).doRun at line 107
pkg/sql/rowexec/backfiller.go in pkg/sql/rowexec.(*backfiller).mainLoop at line 154
pkg/sql/rowexec/columnbackfiller.go in pkg/sql/rowexec.(*columnBackfiller).runChunk at line 114
pkg/kv/db.go in pkg/kv.(*DB).TxnWithAdmissionControl at line 942
pkg/kv/db.go in pkg/kv.runTxn at line 979
pkg/kv/txn.go in pkg/kv.(*Txn).exec at line 961
pkg/kv/db.go in pkg/kv.runTxn.func1 at line 980
pkg/sql/rowexec/columnbackfiller.go in pkg/sql/rowexec.(*columnBackfiller).runChunk.func1 at line 132
pkg/sql/backfill/backfill.go in pkg/sql/backfill.(*ColumnBackfiller).RunColumnBackfillChunk at line 357
pkg/sql/row/fetcher.go in pkg/sql/row.(*Fetcher).NextRowDecodedInto at line 1175
pkg/sql/rowenc/encoded_datum.go in pkg/sql/rowenc.(*EncDatum).EnsureDecoded at line 256
pkg/sql/rowenc/valueside/decode.go in pkg/sql/rowenc/valueside.Decode at line 42
pkg/sql/rowenc/valueside/decode.go in pkg/sql/rowenc/valueside.DecodeUntaggedDatum at line 64
pkg/util/encoding/encoding.go in pkg/util/encoding.DecodeUntaggedBytesValue at line 2709
GOROOT/src/runtime/panic.go in runtime.goPanicSliceB at line 153
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
```

### Tags

| Tag | Value |
| --- | --- |
| Command | start-single-node |
| Environment | v22.2.3 |
| Go Version | go1.19.1 |
| Platform | linux arm64 |
| Distribution | CCL |
| Cockroach Release | v22.2.3 |
| Cockroach SHA | 81a114c2bc2ef8ef76fe3809d0469319c7e82635 |
| # of CPUs | 7 |
| # of Goroutines | 441 |

Jira issue: CRDB-30605

**Comment by yuzefovich** [comment]
unactionable with no repro
