### ISSUE TITLE
testutils: do not require CCL import or enterprise license to test with secondary tenants

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#108761]
(Discussed with @yuzefovich)

Prior to this patch, for test tenant servers to be automatically used two conditions needed to hold:

- the CCL package(s) needed to be imported.
- an enterprise license needed to be set (usually via `ccl.TestingEnableEnterprise()`)

While we want these conditions to hold to start separate-process SQL servers in production, they do not need to be verified in unit tests. Also ever since #98203 was merged, the CCL import is not necessary at all.

Epic: CRDB-18499

Jira issue: CRDB-30626

**Comment by yuzefovich** [comment]
> Also ever since #98203 was merged, the CCL import is not necessary at all.

Can you expand on this a bit? I thought that in my own previous attempts at enabling the CCL license everywhere (as opposed to removing the license check) I still needed to import CCL package since otherwise I still saw warnings about preventing default test tenant from being started.

**Comment by knz** [comment]
> I still needed to import CCL package since otherwise I still saw warnings about preventing default test tenant from being started.

This check is what this PR is removing.
