### ISSUE TITLE
backupccl: ensure ALTER BACKUP SCHEDULE can be used to produce a one off backup

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#108857]
Once a customer has resolved an issue that caused their scheduled backups to fail, they should be able to manually trigger a one off backup in their schedule instead of waiting for the next scheduled backup to run. Currently, they can run `ALTER BACKUP SCHEDULE` to modify the schedule to run asap, and then run `ALTER BACKUP SCHEDULE` to return the schedule to the normal cadence. This workflow should be tested. Alternatively, we could add an `ALTER BACKUP SCHEDULE with start_one_off_full_backup` cmd too.

Jira issue: CRDB-30667

**Comment by dt** [comment]
Essentially this is just a shorthand for `UPDATE system.scheduled_jobs SET next_run = now() WHERE id = <full backup schedule id>` right? maybe `EXECUTE BACKUP SCHEDULE x`? Or if we want to stay under ALTER, maybe `ALTER BACKUP SCHEDULE x RUN IMMEDIATELY` ?

**Comment by msbutler** [comment]
I think so. I don't want users manipulating system tables. 

A user was complaining about their incremental backup schedule failing due to an old pts record failure after they ran that exact command, presumably on their inc schedule. I'm unsure if that system table update would screw up pts management--haven't looked closely at the code.

**Comment by dt** [comment]
https://github.com/cockroachdb/cockroach/pull/112118
