### ISSUE TITLE
Sentry: cmd_recover_txn.go:132: programming error: timestamp change by implicitly committed transaction: 1692258792.309848718,2->1692258775.358472952,0
(1)
Wraps: (2) assertion failure
Wraps: (3)
  | ...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#108893]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4401087676/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4401087676/?referrer=webhooks_plugin)

Panic Message:

```
cmd_recover_txn.go:132: programming error: timestamp change by implicitly committed transaction: 1692258792.309848718,2->1692258775.358472952,0
(1)
Wraps: (2) assertion failure
Wraps: (3)
  | (opaque error wrapper)
  | type name: github.com/cockroachdb/errors/withstack/*withstack.withStack
  | reportable 0:
  |
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/batcheval.RecoverTxn
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/batcheval/cmd_recover_txn.go:132
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.evaluateCommand
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_evaluate.go:520
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.evaluateBatch
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_evaluate.go:287
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).evaluateWriteBatchWrapper
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go:668
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).evaluateWriteBatchWithServersideRefreshes
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go:628
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).evaluateWriteBatch
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go:438
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).evaluateProposal
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go:716
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).requestToProposal
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go:804
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).evalAndPropose
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:119
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).executeWriteBatch
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go:174
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).executeBatchWithConcurrencyRetries
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go:481
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).SendWithWriteBytes
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go:180
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).SendWithWriteBytes
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_send.go:205
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Stores).SendWithWriteBytes
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/stores.go:203
  | github.com/cockroachdb/cockroach/pkg/server.(*Node).batchInternal
  | 	github.com/cockroachdb/cockroach/pkg/server/node.go:1108
  | github.com/cockroachdb/cockroach/pkg/server.(*Node).Batch
  | 	github.com/cockroachdb/cockroach/pkg/server/node.go:1161
  | github.com/cockroachdb/cockroach/pkg/roachpb._Internal_Batch_Handler.func1
  | 	github.com/cockroachdb/cockroach/pkg/roachpb/bazel-out/k8-opt/bin/pkg/roachpb/roachpb_go_proto_/github.com/cockroachdb/cockroach/pkg/roachpb/api.pb.go:9619
  | github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor.ServerInterceptor.func1
  | 	github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go:96
  | google.golang.org/grpc.chainUnaryInterceptors.func1.1
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1117
  | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func3
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:263
  | google.golang.org/grpc.chainUnaryInterceptors.func1.1
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1120
  | github.com/cockroachdb/cockroach/pkg/rpc.kvAuth.unaryInterceptor
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/auth.go:73
  | google.golang.org/grpc.chainUnaryInterceptors.func1.1
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1120
  | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func1.1
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:232
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:341
  | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func1
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:230
  | google.golang.org/grpc.chainUnaryInterceptors.func1.1
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1120
  | google.golang.org/grpc.chainUnaryInterceptors.func1
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1122
  | github.com/cockroachdb/cockroach/pkg/roachpb._Internal_Batch_Handler
  | 	github.com/cockroachdb/cockroach/pkg/roachpb/bazel-out/k8-opt/bin/pkg/roachpb/roachpb_go_proto_/github.com/cockroachdb/cockroach/pkg/roachpb/api.pb.go:9621
  | google.golang.org/grpc.(*Server).processUnaryRPC
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1283
  | google.golang.org/grpc.(*Server).handleStream
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1620
  | google.golang.org/grpc.(*Server).serveStreams.func1.2
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:922
Wraps: (4) programming error: timestamp change by implicitly committed transaction: 1692258792.309848718,2->1692258775.358472952,0
Error types: (1) *colexecerror.StorageError (2) *assert.withAssertionFailure (3) *errbase.opaqueWrapper (4) *errutil.leafError
-- report composition:
*errutil.leafError: programming error: timestamp change by implicitly committed transaction: 1692258792.309848718,2->1692258775.358472952,0
cmd_recover_txn.go:132: *withstack.withStack (top exception)
*assert.withAssertionFailure
*colexecerror.StorageError
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L921-L923](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L921-L923)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1619-L1621](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1619-L1621)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1282-L1284](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1282-L1284)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/roachpb/bazel-out/k8-opt/bin/pkg/roachpb/roachpb_go_proto_/github.com/cockroachdb/cockroach/pkg/roachpb/api.pb.go#L9620-L9622](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/roachpb/bazel-out/k8-opt/bin/pkg/roachpb/roachpb_go_proto_/github.com/cockroachdb/cockroach/pkg/roachpb/api.pb.go#L9620-L9622)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1121-L1123](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1121-L1123)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1119-L1121](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1119-L1121)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/rpc/pkg/rpc/context.go#L229-L231](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/rpc/pkg/rpc/context.go#L229-L231)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/util/stop/stopper.go#L340-L342](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/util/stop/stopper.go#L340-L342)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/rpc/pkg/rpc/context.go#L231-L233](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/rpc/pkg/rpc/context.go#L231-L233)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1119-L1121](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1119-L1121)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/rpc/pkg/rpc/auth.go#L72-L74](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/rpc/pkg/rpc/auth.go#L72-L74)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1119-L1121](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1119-L1121)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/rpc/pkg/rpc/context.go#L262-L264](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/rpc/pkg/rpc/context.go#L262-L264)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1116-L1118](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1116-L1118)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go#L95-L97](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go#L95-L97)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/roachpb/bazel-out/k8-opt/bin/pkg/roachpb/roachpb_go_proto_/github.com/cockroachdb/cockroach/pkg/roachpb/api.pb.go#L9618-L9620](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/roachpb/bazel-out/k8-opt/bin/pkg/roachpb/roachpb_go_proto_/github.com/cockroachdb/cockroach/pkg/roachpb/api.pb.go#L9618-L9620)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/server/node.go#L1160-L1162](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/server/node.go#L1160-L1162)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/server/node.go#L1107-L1109](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/server/node.go#L1107-L1109)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/pkg/kv/kvserver/stores.go#L202-L204](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/pkg/kv/kvserver/stores.go#L202-L204)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/pkg/kv/kvserver/store_send.go#L204-L206](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/pkg/kv/kvserver/store_send.go#L204-L206)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go#L179-L181](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go#L179-L181)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go#L480-L482](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go#L480-L482)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go#L173-L175](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go#L173-L175)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L118-L120](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L118-L120)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go#L803-L805](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go#L803-L805)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go#L715-L717](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go#L715-L717)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go#L437-L439](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go#L437-L439)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go#L627-L629](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go#L627-L629)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go#L667-L669](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go#L667-L669)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/pkg/kv/kvserver/replica_evaluate.go#L286-L288](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/pkg/kv/kvserver/replica_evaluate.go#L286-L288)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/pkg/kv/kvserver/replica_evaluate.go#L519-L521](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/pkg/kv/kvserver/replica_evaluate.go#L519-L521)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/batcheval/cmd_recover_txn.go#L131-L133](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/kv/kvserver/batcheval/cmd_recover_txn.go#L131-L133)
</details>

```
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.(*Server).serveStreams.func1.2 at line 922
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.(*Server).handleStream at line 1620
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.(*Server).processUnaryRPC at line 1283
pkg/roachpb/bazel-out/k8-opt/bin/pkg/roachpb/roachpb_go_proto_/github.com/cockroachdb/cockroach/pkg/roachpb/api.pb.go in pkg/roachpb._Internal_Batch_Handler at line 9621
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.chainUnaryInterceptors.func1 at line 1122
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.chainUnaryInterceptors.func1.1 at line 1120
pkg/rpc/pkg/rpc/context.go in pkg/rpc.NewServerEx.func1 at line 230
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunTaskWithErr at line 341
pkg/rpc/pkg/rpc/context.go in pkg/rpc.NewServerEx.func1.1 at line 232
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.chainUnaryInterceptors.func1.1 at line 1120
pkg/rpc/pkg/rpc/auth.go in pkg/rpc.kvAuth.unaryInterceptor at line 73
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.chainUnaryInterceptors.func1.1 at line 1120
pkg/rpc/pkg/rpc/context.go in pkg/rpc.NewServerEx.func3 at line 263
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.chainUnaryInterceptors.func1.1 at line 1117
pkg/util/tracing/grpcinterceptor/grpc_interceptor.go in pkg/util/tracing/grpcinterceptor.ServerInterceptor.func1 at line 96
pkg/roachpb/bazel-out/k8-opt/bin/pkg/roachpb/roachpb_go_proto_/github.com/cockroachdb/cockroach/pkg/roachpb/api.pb.go in pkg/roachpb._Internal_Batch_Handler.func1 at line 9619
pkg/server/node.go in pkg/server.(*Node).Batch at line 1161
pkg/server/node.go in pkg/server.(*Node).batchInternal at line 1108
pkg/kv/kvserver/pkg/kv/kvserver/stores.go in pkg/kv/kvserver.(*Stores).SendWithWriteBytes at line 203
pkg/kv/kvserver/pkg/kv/kvserver/store_send.go in pkg/kv/kvserver.(*Store).SendWithWriteBytes at line 205
pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go in pkg/kv/kvserver.(*Replica).SendWithWriteBytes at line 180
pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go in pkg/kv/kvserver.(*Replica).executeBatchWithConcurrencyRetries at line 481
pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go in pkg/kv/kvserver.(*Replica).executeWriteBatch at line 174
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).evalAndPropose at line 119
pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go in pkg/kv/kvserver.(*Replica).requestToProposal at line 804
pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go in pkg/kv/kvserver.(*Replica).evaluateProposal at line 716
pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go in pkg/kv/kvserver.(*Replica).evaluateWriteBatch at line 438
pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go in pkg/kv/kvserver.(*Replica).evaluateWriteBatchWithServersideRefreshes at line 628
pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go in pkg/kv/kvserver.(*Replica).evaluateWriteBatchWrapper at line 668
pkg/kv/kvserver/pkg/kv/kvserver/replica_evaluate.go in pkg/kv/kvserver.evaluateBatch at line 287
pkg/kv/kvserver/pkg/kv/kvserver/replica_evaluate.go in pkg/kv/kvserver.evaluateCommand at line 520
pkg/kv/kvserver/batcheval/cmd_recover_txn.go in pkg/kv/kvserver/batcheval.RecoverTxn at line 132
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v22.2.9 |
| Go Version | go1.19.6 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v22.2.9 |
| Cockroach SHA | 1b11ca676513ae073ea696c7cc3123d2684bc4bd |
| # of CPUs | 24 |
| # of Goroutines | 1145 |

Jira issue: CRDB-30691

**Comment by yuzefovich** [comment]
dup of #107860
