### ISSUE TITLE
Sentry: error.go:89: unexpected error from the vectorized engine: runtime error: index out of range [137] with length 117
(1)
Wraps: (2)
Wraps: (3) assertion failure
Wraps: (4) attached stack trace
  ...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#108887]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4400864770/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4400864770/?referrer=webhooks_plugin)

Panic Message:

```
error.go:89: unexpected error from the vectorized engine: runtime error: index out of range [137] with length 117
(1)
Wraps: (2)
Wraps: (3) assertion failure
Wraps: (4) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:89
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | runtime.goPanicIndex
  | 	GOROOT/src/runtime/panic.go:113
  | github.com/cockroachdb/cockroach/pkg/sql/row.(*txnKVStreamer).getSpanID
  | 	github.com/cockroachdb/cockroach/pkg/sql/row/kv_batch_streamer.go:109
  | github.com/cockroachdb/cockroach/pkg/sql/row.(*txnKVStreamer).proceedWithLastResult
  | 	github.com/cockroachdb/cockroach/pkg/sql/row/kv_batch_streamer.go:121
  | github.com/cockroachdb/cockroach/pkg/sql/row.(*txnKVStreamer).nextBatch
  | 	github.com/cockroachdb/cockroach/pkg/sql/row/kv_batch_streamer.go:177
  | github.com/cockroachdb/cockroach/pkg/sql/row.(*txnKVStreamer).nextBatch
  | 	github.com/cockroachdb/cockroach/pkg/sql/row/kv_batch_streamer.go:194
  | github.com/cockroachdb/cockroach/pkg/sql/row.(*KVFetcher).NextKV
  | 	github.com/cockroachdb/cockroach/pkg/sql/row/kv_fetcher.go:264
  | github.com/cockroachdb/cockroach/pkg/sql/row.(*Fetcher).nextKey
  | 	github.com/cockroachdb/cockroach/pkg/sql/row/fetcher.go:665
  | github.com/cockroachdb/cockroach/pkg/sql/row.(*Fetcher).startScan
  | 	github.com/cockroachdb/cockroach/pkg/sql/row/fetcher.go:635
  | github.com/cockroachdb/cockroach/pkg/sql/row.(*Fetcher).StartScan
  | 	github.com/cockroachdb/cockroach/pkg/sql/row/fetcher.go:492
  | github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*joinReader).readInput
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowexec/joinreader.go:999
  | github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*joinReader).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowexec/joinreader.go:731
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Columnarizer).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/columnarizer.go:243
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*HashRouter).processNextBatch
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/routers.go:657
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*HashRouter).Run.func1.1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/routers.go:579
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*HashRouter).Run.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/routers.go:617
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*HashRouter).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/routers.go:574
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlowCreator).setupRouter.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:809
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlowCreatorHelper).accumulateAsyncComponent.func1.1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:1344
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (5) unexpected error from the vectorized engine
Wraps: (6) runtime error: index out of range [137] with length 117
  | -- cause hidden behind barrier
  | runtime error: index out of range [137] with length 117
  | (1) runtime error: index out of range [137] with length 117
  | Error types: (1) runtime.boundsError
Error types: (1) *colexecerror.notInternalError (2) *colexecerror.notInternalError (3) *assert.withAssertionFailure (4) *withstack.withStack (5) *errutil.withPrefix (6) *barriers.barrierErr
-- report composition:
*barriers.barrierErr: masked error: runtime error: index out of range [137] with length 117
*errutil.withPrefix: unexpected error from the vectorized engine
error.go:89: *withstack.withStack (top exception)
*assert.withAssertionFailure
*colexecerror.notInternalError
*colexecerror.notInternalError
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/colflow/vectorized_flow.go#L1343-L1345](https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/colflow/vectorized_flow.go#L1343-L1345)
[https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/colflow/vectorized_flow.go#L808-L810](https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/colflow/vectorized_flow.go#L808-L810)
[https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/colflow/routers.go#L573-L575](https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/colflow/routers.go#L573-L575)
[https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/colflow/routers.go#L616-L618](https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/colflow/routers.go#L616-L618)
[https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/colflow/routers.go#L578-L580](https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/colflow/routers.go#L578-L580)
[https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/colflow/routers.go#L656-L658](https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/colflow/routers.go#L656-L658)
[https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/colexec/columnarizer.go#L242-L244](https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/colexec/columnarizer.go#L242-L244)
[https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/rowexec/joinreader.go#L730-L732](https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/rowexec/joinreader.go#L730-L732)
[https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/rowexec/joinreader.go#L998-L1000](https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/rowexec/joinreader.go#L998-L1000)
[https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/row/fetcher.go#L491-L493](https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/row/fetcher.go#L491-L493)
[https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/row/fetcher.go#L634-L636](https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/row/fetcher.go#L634-L636)
[https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/row/fetcher.go#L664-L666](https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/row/fetcher.go#L664-L666)
[https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/row/kv_fetcher.go#L263-L265](https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/row/kv_fetcher.go#L263-L265)
[https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/row/kv_batch_streamer.go#L193-L195](https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/row/kv_batch_streamer.go#L193-L195)
[https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/row/kv_batch_streamer.go#L176-L178](https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/row/kv_batch_streamer.go#L176-L178)
[https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/row/kv_batch_streamer.go#L120-L122](https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/row/kv_batch_streamer.go#L120-L122)
[https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/row/kv_batch_streamer.go#L108-L110](https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/row/kv_batch_streamer.go#L108-L110)
[GOROOT/src/runtime/panic.go#L112-L114](GOROOT/src/runtime/panic.go#L112-L114)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
[https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/colexecerror/error.go#L88-L90](https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/colexecerror/error.go#L88-L90)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlowCreatorHelper).accumulateAsyncComponent.func1.1 at line 1344
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlowCreator).setupRouter.func1 at line 809
pkg/sql/colflow/routers.go in pkg/sql/colflow.(*HashRouter).Run at line 574
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colflow/routers.go in pkg/sql/colflow.(*HashRouter).Run.func1 at line 617
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colflow/routers.go in pkg/sql/colflow.(*HashRouter).Run.func1.1 at line 579
pkg/sql/colflow/routers.go in pkg/sql/colflow.(*HashRouter).processNextBatch at line 657
pkg/sql/colexec/columnarizer.go in pkg/sql/colexec.(*Columnarizer).Next at line 243
pkg/sql/rowexec/joinreader.go in pkg/sql/rowexec.(*joinReader).Next at line 731
pkg/sql/rowexec/joinreader.go in pkg/sql/rowexec.(*joinReader).readInput at line 999
pkg/sql/row/fetcher.go in pkg/sql/row.(*Fetcher).StartScan at line 492
pkg/sql/row/fetcher.go in pkg/sql/row.(*Fetcher).startScan at line 635
pkg/sql/row/fetcher.go in pkg/sql/row.(*Fetcher).nextKey at line 665
pkg/sql/row/kv_fetcher.go in pkg/sql/row.(*KVFetcher).NextKV at line 264
pkg/sql/row/kv_batch_streamer.go in pkg/sql/row.(*txnKVStreamer).nextBatch at line 194
pkg/sql/row/kv_batch_streamer.go in pkg/sql/row.(*txnKVStreamer).nextBatch at line 177
pkg/sql/row/kv_batch_streamer.go in pkg/sql/row.(*txnKVStreamer).proceedWithLastResult at line 121
pkg/sql/row/kv_batch_streamer.go in pkg/sql/row.(*txnKVStreamer).getSpanID at line 109
GOROOT/src/runtime/panic.go in runtime.goPanicIndex at line 113
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1 at line 89
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v22.2.8 |
| Go Version | go1.19.6 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v22.2.8 |
| Cockroach SHA | 9a7c644e565b21d29db26a0a82524a00809d0a8c |
| # of CPUs | 16 |
| # of Goroutines | 1686 |

Jira issue: CRDB-30686

**Comment by yuzefovich** [comment]
dup of #108572
