### ISSUE TITLE
cluster-ui: transactions details page call for insights loads all insights

### ISSUE THREAD

**Issue by gtr** [cockroachdb/cockroach#108868]
**Describe the problem**

When loading the transaction details page and populating the transaction insights, we make a call to the transaction execution insights table each time without filtering for the specific transaction ID. The query looks something like this:

```sql
SELECT 
  session_id,
  txn_id,
  encode(txn_fingerprint_id, 'hex')  AS txn_fingerprint_id,
  implicit_txn,
  rpad(query, 800, '') AS query,
  start_time,
  end_time,
  app_name,
  user_name,
  rows_read,
  rows_written,
  priority,
  retries,
  contention,
  last_retry_reason,
  problems,
  causes,
  stmt_execution_ids,
  cpu_sql_nanos,
  last_error_code,
  status
FROM
  (
    SELECT DISTINCT ON (txn_fingerprint_id, problems, causes)
      *
    FROM
      crdb_internal.cluster_txn_execution_insights
    WHERE app_name NOT LIKE '$ internal%'
    AND txn_id != '00000000-0000-0000-0000-000000000000'
    AND start_time >= '2023-06-15T19:37:51.000Z'
    AND end_time <= '2023-08-16T19:37:51.000Z'
    ORDER BY txn_fingerprint_id, problems, causes, end_time DESC
  )
```

**To Reproduce**

1. Go to the transactions overview page in SQL Activity
2. Click on any transaction, open the network tab and observe the call to `api/v2/sql/` with the above SQL query every time the page is loaded

**Expected behavior**
This is related to https://github.com/cockroachdb/cockroach/issues/108540. The statements details page does not make the same expensive call to /api/v2/sql and instead uses the statements details API for its statement ID. We should either implement a new endpoint for transaction details or modify the query for the transactions details page to filter by the transaction ID so that don't make an expensive call. In one of our escalations, we observed the following limit exceeded error as a result:
```
"error": {
    "code":"XXUUU",
    "message":"executing stmt 1: max result size exceeded",
    "severity":"ERROR",
    "source":{
      "file":"api_v2_sql.go","line":383,"function":"1"
    }
  },
```

Jira issue: CRDB-30673

**Comment by maryliag** [comment]
No longer a priority
