### ISSUE TITLE
sql: support PostgreSQL syntax for creating `index ... using hash(column)`

### ISSUE THREAD

**Issue by giangpham712** [cockroachdb/cockroach#108882]
CockroachDB's current syntax for creating index using hash is as follows

```
CREATE INDEX name ON table (column) USING HASH;
```

while that in PostgreSQL is

```
CREATE INDEX name ON table (column) USING HASH(column);
```

This syntax is consistent with those for creating other types of index that are working with CockroachDB such as

```
CREATE INDEX ix_gin ON "IndexSortOrder" USING gin (c);
CREATE INDEX ix_gist ON "IndexSortOrder" USING gist (c);
```

**Additional context**
This issue affects some efcore.pg tests

@fqazi 

Jira issue: CRDB-30683

**Comment by rafiss** [comment]
The postgres syntax is actually doing something a bit different than CRDB.

- In postgres, `USING HASH(column)` creates an index on that column, with the hash algorithm.
- in CRDB, `USING HASH` creates a hash-sharded index, which generates a new column. See https://www.cockroachlabs.com/docs/stable/hash-sharded-indexes

So I don't think we will be able to resolve this easily.

**Comment by msirek** [comment]
Closing issue.  CRDB is working as designed, and has different behavior than Postgress here.
