### ISSUE TITLE
Sentry: execplan.go:1793: unable to vectorize execution plan: unexpectedly different number of columns are output: expected [], actual [×]
(1) tags: [n1,client=127.0.0.1:49678,hostssl,user=×,receive...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#108932]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4402610413/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4402610413/?referrer=webhooks_plugin)

Panic Message:

```
execplan.go:1793: unable to vectorize execution plan: unexpectedly different number of columns are output: expected [], actual [×]
(1) tags: [n1,client=127.0.0.1:49678,hostssl,user=×,received-error]
Wraps: (2) tags: [n×,f×,distsql.stmt=×
  | ×,distsql.gateway=×,distsql.appname=×,distsql.txn=×,sent-error=×]
Wraps: (3)
  | (opaque error wrapper)
  | type name: github.com/cockroachdb/errors/withstack/*withstack.withStack
  | reportable 0:
  |
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlowCreator).setupFlow.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:1240
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlowCreator).setupFlow
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:1170
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Setup
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:269
  | github.com/cockroachdb/cockroach/pkg/sql/distsql.(*ServerImpl).setupFlow
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql/server.go:429
  | github.com/cockroachdb/cockroach/pkg/sql/distsql.(*ServerImpl).SetupFlow.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql/server.go:661
  | github.com/cockroachdb/cockroach/pkg/sql/distsql.(*ServerImpl).SetupFlow
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql/server.go:689
  | github.com/cockroachdb/cockroach/pkg/sql/execinfrapb._DistSQL_SetupFlow_Handler.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/bazel-out/k8-opt/bin/pkg/sql/execinfrapb/execinfrapb_go_proto_/github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/api.pb.go:602
  | github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor.ServerInterceptor.func1
  | 	github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go:96
  | google.golang.org/grpc.chainUnaryInterceptors.func1.1
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1162
  | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func3
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:276
  | google.golang.org/grpc.chainUnaryInterceptors.func1.1
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1165
  | github.com/cockroachdb/cockroach/pkg/rpc.kvAuth.unaryInterceptor
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/auth.go:105
  | google.golang.org/grpc.chainUnaryInterceptors.func1.1
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1165
  | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func1.1
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:243
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:322
  | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func1
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:241
  | google.golang.org/grpc.chainUnaryInterceptors.func1.1
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1165
  | google.golang.org/grpc.chainUnaryInterceptors.func1
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1167
  | github.com/cockroachdb/cockroach/pkg/sql/execinfrapb._DistSQL_SetupFlow_Handler
  | 	github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/bazel-out/k8-opt/bin/pkg/sql/execinfrapb/execinfrapb_go_proto_/github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/api.pb.go:604
  | google.golang.org/grpc.(*Server).processUnaryRPC
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1340
  | google.golang.org/grpc.(*Server).handleStream
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1713
  | google.golang.org/grpc.(*Server).serveStreams.func1.2
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:965
  | runtime.goexit
  | 	src/runtime/asm_arm64.s:1172
Wraps: (4) unable to vectorize execution plan
Wraps: (5) assertion failure
Wraps: (6)
  | (opaque error wrapper)
  | type name: github.com/cockroachdb/errors/withstack/*withstack.withStack
  | reportable 0:
  |
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colbuilder.NewColOperator
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colbuilder/execplan.go:1793
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlowCreator).setupFlow.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:1235
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlowCreator).setupFlow
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:1170
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Setup
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:269
  | github.com/cockroachdb/cockroach/pkg/sql/distsql.(*ServerImpl).setupFlow
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql/server.go:429
  | github.com/cockroachdb/cockroach/pkg/sql/distsql.(*ServerImpl).SetupFlow.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql/server.go:661
  | github.com/cockroachdb/cockroach/pkg/sql/distsql.(*ServerImpl).SetupFlow
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql/server.go:689
  | github.com/cockroachdb/cockroach/pkg/sql/execinfrapb._DistSQL_SetupFlow_Handler.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/bazel-out/k8-opt/bin/pkg/sql/execinfrapb/execinfrapb_go_proto_/github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/api.pb.go:602
  | github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor.ServerInterceptor.func1
  | 	github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go:96
  | google.golang.org/grpc.chainUnaryInterceptors.func1.1
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1162
  | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func3
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:276
  | google.golang.org/grpc.chainUnaryInterceptors.func1.1
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1165
  | github.com/cockroachdb/cockroach/pkg/rpc.kvAuth.unaryInterceptor
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/auth.go:105
  | google.golang.org/grpc.chainUnaryInterceptors.func1.1
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1165
  | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func1.1
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:243
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:322
  | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func1
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:241
  | google.golang.org/grpc.chainUnaryInterceptors.func1.1
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1165
  | google.golang.org/grpc.chainUnaryInterceptors.func1
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1167
  | github.com/cockroachdb/cockroach/pkg/sql/execinfrapb._DistSQL_SetupFlow_Handler
  | 	github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/bazel-out/k8-opt/bin/pkg/sql/execinfrapb/execinfrapb_go_proto_/github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/api.pb.go:604
  | google.golang.org/grpc.(*Server).processUnaryRPC
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1340
  | google.golang.org/grpc.(*Server).handleStream
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1713
  | google.golang.org/grpc.(*Server).serveStreams.func1.2
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:965
  | runtime.goexit
  | 	src/runtime/asm_arm64.s:1172
Wraps: (7) unexpectedly different number of columns are output: expected [], actual [×]
Error types: (1) *contexttags.withContext (2) *contexttags.withContext (3...
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_arm64.s#L1171-L1173](src/runtime/asm_arm64.s#L1171-L1173)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L964-L966](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L964-L966)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1712-L1714](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1712-L1714)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1339-L1341](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1339-L1341)
[https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/sql/execinfrapb/bazel-out/k8-opt/bin/pkg/sql/execinfrapb/execinfrapb_go_proto_/github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/api.pb.go#L603-L605](https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/sql/execinfrapb/bazel-out/k8-opt/bin/pkg/sql/execinfrapb/execinfrapb_go_proto_/github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/api.pb.go#L603-L605)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1166-L1168](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1166-L1168)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1164-L1166](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1164-L1166)
[https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/rpc/pkg/rpc/context.go#L240-L242](https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/rpc/pkg/rpc/context.go#L240-L242)
[https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/util/stop/stopper.go#L321-L323](https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/util/stop/stopper.go#L321-L323)
[https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/rpc/pkg/rpc/context.go#L242-L244](https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/rpc/pkg/rpc/context.go#L242-L244)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1164-L1166](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1164-L1166)
[https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/rpc/pkg/rpc/auth.go#L104-L106](https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/rpc/pkg/rpc/auth.go#L104-L106)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1164-L1166](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1164-L1166)
[https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/rpc/pkg/rpc/context.go#L275-L277](https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/rpc/pkg/rpc/context.go#L275-L277)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1161-L1163](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1161-L1163)
[https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go#L95-L97](https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go#L95-L97)
[https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/sql/execinfrapb/bazel-out/k8-opt/bin/pkg/sql/execinfrapb/execinfrapb_go_proto_/github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/api.pb.go#L601-L603](https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/sql/execinfrapb/bazel-out/k8-opt/bin/pkg/sql/execinfrapb/execinfrapb_go_proto_/github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/api.pb.go#L601-L603)
[https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/sql/distsql/server.go#L688-L690](https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/sql/distsql/server.go#L688-L690)
[https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/sql/distsql/server.go#L660-L662](https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/sql/distsql/server.go#L660-L662)
[https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/sql/distsql/server.go#L428-L430](https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/sql/distsql/server.go#L428-L430)
[https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/sql/colflow/vectorized_flow.go#L268-L270](https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/sql/colflow/vectorized_flow.go#L268-L270)
[https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/sql/colflow/vectorized_flow.go#L1169-L1171](https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/sql/colflow/vectorized_flow.go#L1169-L1171)
[https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/sql/colflow/vectorized_flow.go#L1239-L1241](https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/sql/colflow/vectorized_flow.go#L1239-L1241)
[src/runtime/asm_arm64.s#L1171-L1173](src/runtime/asm_arm64.s#L1171-L1173)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L964-L966](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L964-L966)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1712-L1714](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1712-L1714)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1339-L1341](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1339-L1341)
[https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/sql/execinfrapb/bazel-out/k8-opt/bin/pkg/sql/execinfrapb/execinfrapb_go_proto_/github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/api.pb.go#L603-L605](https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/sql/execinfrapb/bazel-out/k8-opt/bin/pkg/sql/execinfrapb/execinfrapb_go_proto_/github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/api.pb.go#L603-L605)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1166-L1168](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1166-L1168)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1164-L1166](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1164-L1166)
[https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/rpc/pkg/rpc/context.go#L240-L242](https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/rpc/pkg/rpc/context.go#L240-L242)
[https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/util/stop/stopper.go#L321-L323](https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/util/stop/stopper.go#L321-L323)
[https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/rpc/pkg/rpc/context.go#L242-L244](https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/rpc/pkg/rpc/context.go#L242-L244)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1164-L1166](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1164-L1166)
[https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/rpc/pkg/rpc/auth.go#L104-L106](https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/rpc/pkg/rpc/auth.go#L104-L106)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1164-L1166](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1164-L1166)
[https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/rpc/pkg/rpc/context.go#L275-L277](https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/rpc/pkg/rpc/context.go#L275-L277)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1161-L1163](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1161-L1163)
[https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go#L95-L97](https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go#L95-L97)
[https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/sql/execinfrapb/bazel-out/k8-opt/bin/pkg/sql/execinfrapb/execinfrapb_go_proto_/github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/api.pb.go#L601-L603](https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/sql/execinfrapb/bazel-out/k8-opt/bin/pkg/sql/execinfrapb/execinfrapb_go_proto_/github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/api.pb.go#L601-L603)
[https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/sql/distsql/server.go#L688-L690](https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/sql/distsql/server.go#L688-L690)
[https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/sql/distsql/server.go#L660-L662](https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/sql/distsql/server.go#L660-L662)
[https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/sql/distsql/server.go#L428-L430](https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/sql/distsql/server.go#L428-L430)
[https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/sql/colflow/vectorized_flow.go#L268-L270](https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/sql/colflow/vectorized_flow.go#L268-L270)
[https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/sql/colflow/vectorized_flow.go#L1169-L1171](https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/sql/colflow/vectorized_flow.go#L1169-L1171)
[https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/sql/colflow/vectorized_flow.go#L1234-L1236](https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/sql/colflow/vectorized_flow.go#L1234-L1236)
[https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/sql/colexec/colbuilder/execplan.go#L1792-L1794](https://github.com/cockroachdb/cockroach/blob/ff8937c8a23177a67afeb6e65c8d1b13285c2922/pkg/sql/colexec/colbuilder/execplan.go#L1792-L1794)
</details>

```
src/runtime/asm_arm64.s in runtime.goexit at line 1172
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.(*Server).serveStreams.func1.2 at line 965
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.(*Server).handleStream at line 1713
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.(*Server).processUnaryRPC at line 1340
pkg/sql/execinfrapb/bazel-out/k8-opt/bin/pkg/sql/execinfrapb/execinfrapb_go_proto_/github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/api.pb.go in pkg/sql/execinfrapb._DistSQL_SetupFlow_Handler at line 604
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.chainUnaryInterceptors.func1 at line 1167
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.chainUnaryInterceptors.func1.1 at line 1165
pkg/rpc/pkg/rpc/context.go in pkg/rpc.NewServerEx.func1 at line 241
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunTaskWithErr at line 322
pkg/rpc/pkg/rpc/context.go in pkg/rpc.NewServerEx.func1.1 at line 243
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.chainUnaryInterceptors.func1.1 at line 1165
pkg/rpc/pkg/rpc/auth.go in pkg/rpc.kvAuth.unaryInterceptor at line 105
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.chainUnaryInterceptors.func1.1 at line 1165
pkg/rpc/pkg/rpc/context.go in pkg/rpc.NewServerEx.func3 at line 276
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.chainUnaryInterceptors.func1.1 at line 1162
pkg/util/tracing/grpcinterceptor/grpc_interceptor.go in pkg/util/tracing/grpcinterceptor.ServerInterceptor.func1 at line 96
pkg/sql/execinfrapb/bazel-out/k8-opt/bin/pkg/sql/execinfrapb/execinfrapb_go_proto_/github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/api.pb.go in pkg/sql/execinfrapb._DistSQL_SetupFlow_Handler.func1 at line 602
pkg/sql/distsql/server.go in pkg/sql/distsql.(*ServerImpl).SetupFlow at line 689
pkg/sql/distsql/server.go in pkg/sql/distsql.(*ServerImpl).SetupFlow.func1 at line 661
pkg/sql/distsql/server.go in pkg/sql/distsql.(*ServerImpl).setupFlow at line 429
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlow).Setup at line 269
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlowCreator).setupFlow at line 1170
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlowCreator).setupFlow.func1 at line 1240
src/runtime/asm_arm64.s in runtime.goexit at line 1172
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.(*Server).serveStreams.func1.2 at line 965
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.(*Server).handleStream at line 1713
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.(*Server).processUnaryRPC at line 1340
pkg/sql/execinfrapb/bazel-out/k8-opt/bin/pkg/sql/execinfrapb/execinfrapb_go_proto_/github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/api.pb.go in pkg/sql/execinfrapb._DistSQL_SetupFlow_Handler at line 604
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.chainUnaryInterceptors.func1 at line 1167
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.chainUnaryInterceptors.func1.1 at line 1165
pkg/rpc/pkg/rpc/context.go in pkg/rpc.NewServerEx.func1 at line 241
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunTaskWithErr at line 322
pkg/rpc/pkg/rpc/context.go in pkg/rpc.NewServerEx.func1.1 at line 243
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.chainUnaryInterceptors.func1.1 at line 1165
pkg/rpc/pkg/rpc/auth.go in pkg/rpc.kvAuth.unaryInterceptor at line 105
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.chainUnaryInterceptors.func1.1 at line 1165
pkg/rpc/pkg/rpc/context.go in pkg/rpc.NewServerEx.func3 at line 276
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.chainUnaryInterceptors.func1.1 at line 1162
pkg/util/tracing/grpcinterceptor/grpc_interceptor.go in pkg/util/tracing/grpcinterceptor.ServerInterceptor.func1 at line 96
pkg/sql/execinfrapb/bazel-out/k8-opt/bin/pkg/sql/execinfrapb/execinfrapb_go_proto_/github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/api.pb.go in pkg/sql/execinfrapb._DistSQL_SetupFlow_Handler.func1 at line 602
pkg/sql/distsql/server.go in pkg/sql/distsql.(*ServerImpl).SetupFlow at line 689
pkg/sql/distsql/server.go in pkg/sql/distsql.(*ServerImpl).SetupFlow.func1 at line 661
pkg/sql/distsql/server.go in pkg/sql/distsql.(*ServerImpl).setupFlow at line 429
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlow).Setup at line 269
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlowCreator).setupFlow at line 1170
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlowCreator).setupFlow.func1 at line 1235
pkg/sql/colexec/colbuilder/execplan.go in pkg/sql/colexec/colbuilder.NewColOperator at line 1793
```

### Tags

| Tag | Value |
| --- | --- |
| Command | demo |
| Environment | v23.1.7 |
| Go Version | go1.19.10 |
| Platform | darwin arm64 |
| Distribution | CCL |
| Cockroach Release | v23.1.7 |
| Cockroach SHA | ff8937c8a23177a67afeb6e65c8d1b13285c2922 |
| # of CPUs | 10 |
| # of Goroutines | 5566 |

Jira issue: CRDB-30704

**Comment by yuzefovich** [comment]
dup of #108901
