### ISSUE TITLE
improve consistency on SQL Activity

### ISSUE THREAD

**Issue by maryliag** [cockroachdb/cockroach#108989]
Scenario: a fingerprint gets executed 1k times per day.
On `statement_activity`, we are able to keep the data for that fingerprint for 2 days.
On `statement_statistics` we had data for several days, but the limit of the table was reached, so older data had to be deleted and now only data for the past day is available.

If a user selects see past day: it will return the results from `statement_activity`, since the selected period existed there, and we will show 2k.
If a user selects past week: the `statement_activity` doesn't have this entire period, so it will return the results from `statement_statistics`, and that only had the last day, so it will return 1k.

So for the user, it shows past day 2k and past week 1k, which is confusing.
We need to improve this experience.

Possible solution:
- Delete the data based on TTL and have the same value for all tables
- Some union when the main table is selected
- Show warning/info message.

Jira issue: CRDB-30734

**Comment by andy-kimball** [comment]
IMO, combining the data is not useful if there's still data missing. I need confidence that I have all the data, or I can reach incorrect conclusions about my workload. We should always show a warning if there may be data missing. Furthermore, the warning should tell the user how to increase their data retention limit.

**Comment by andy-kimball** [comment]
One thing I don't understand, how come we don't _combine_ rows, i.e. consolidate hourly into daily, daily into weekly, etc. The granularity would go down, but at least we wouldn't completely lose data. There are usually going to be a fairly small set of fingerprints, so it won't use much storage if we keep longer term rows for each unique fingerprint.

**Comment by maryliag** [comment]
> how come we don't combine rows

that will be accomplish when we migrate to use the observability service, so improvements on retention and granularity are part of the roadmap.
