### ISSUE TITLE
sql: allow safer rollbacks for DROP INDEX in legacy schema changer

### ISSUE THREAD

**Issue by fqazi** [cockroachdb/cockroach#109037]
We ran into a scenario where `CREATE INDEX ...; DROP INDEX `issued in a single statement was cancelled in the job phase. The legacy schema changer logic for DROP INDEX currently will never roll back this operation intentionally since, in some cases, it would mean recreating the index. However, we can do a bit better here since if only the metadata part of the drop is committed, we can, at least from a usability standpoint, undo that operation. Versus, the index disappears anyway after the job is rolled back in all cases.

Jira issue: CRDB-30747

Epic CRDB-34099

**Comment by dikshant** [comment]
@fqazi is this still an issue on the declarative schema changer?

**Comment by fqazi** [comment]
No the declarative one will handle this gracefully. It will only undo the metadata operation and not waste time doing a backfill.
