### ISSUE TITLE
sql/catalog: Add a cluster version for system / internal database descriptors

### ISSUE THREAD

**Issue by fqazi** [cockroachdb/cockroach#109039]
We have no way of tracking system table versions, making schema changes to them extremely difficult to reason about what a transaction would see. To help make things easier, we should introduce a cluster version field into the database descriptor, as system tables are modified within any system database, and these versions will be bumped up. This allows the database code to correctly confirm in a transaction-aware manner if changes are fully visible at a given time for the transaction, which is crucial.

Jira issue: CRDB-30748

Epic CRDB-31701

**Comment by rafiss** [comment]
These documents have more information:
- https://docs.google.com/document/d/1MZbpQta9YOiCet0CZlTdfH-ATnp2pWbEJBlQlUhXZfo/edit
- https://docs.google.com/document/d/1zzuggP5woIAoJ9iaena4nl5kOBItPE9bmi_BdOgV0mw/edit#heading=h.ki2zg9qekqab

**Comment by rafiss** [comment]
@fqazi I see that the database descriptor already has a `ClusterVersion` field. Do you know what that one is used for?
https://github.com/cockroachdb/cockroach/blob/95dcf06ec7d3ba2cea59c7ce608162f2be71681d/pkg/sql/catalog/dbdesc/database_desc.go#L59

**Comment by fqazi** [comment]
@rafiss That is just the original version of the descriptor before any changes can be made since it's mutable (normally used to detect version bumps, etc..).
