### ISSUE TITLE
sql: (*DArray).Next() returns incorrect value

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#10902]
From the @nvanbenschoten's code review comments for #10584:

    Could you open an issue to change this? The next value in an array should be the array appended with the minimum value of the parameterized data type (like strings or bytes), because they are not fixed length.

in reference to:

https://github.com/cockroachdb/cockroach/blob/4ebb5528e758c06c960e44fc697b7e1642d31dc1/pkg/sql/parser/datum.go#L1573

**Comment by petermattis** [comment]
@justinj Given the potential for user data badness, can you triage us this issue ASAP and determine if it is exercisable via a SQL query?

**Comment by justinj** [comment]
I don't see how it could be - array ordering in Cockroach isn't exposed to users at all so there should be no way to observe this (though I maybe be wrong and there maybe be another way, @knz?).

**Comment by asubiotto** [comment]
I believe #10475 fixed this.
