### ISSUE TITLE
pkg/base: base_test fails if no network access

### ISSUE THREAD

**Issue by rickystewart** [cockroachdb/cockroach#109052]
Looks like `TestValidateAddrs/23/{nonexistent.example.com:26257_____}` fails.

```
    addr_validation_test.go:169: expected error "no such host", got invalid --listen-addr: lookup nonexistent.example.com on 169.254.169.254:53: dial udp 169.254.169.254:53: connect: network is unreachable
```

Epic: CRDB-8308

Jira issue: CRDB-30751

**Comment by rickystewart** [comment]
The ownership here may be a bit fuzzy. Tagging @knz since this test case apparently originates from him.

**Comment by knz** [comment]
Yes that test needs access to a valid dns resolver because it checks for resolution error.

(Note how it uses example.com to be guaranteed to get an error)

It's possible to use a local dns server with no internet access as long as it responds with errors to those queries.

**Comment by rickystewart** [comment]
The test is a unit test, so it shouldn't have a dependency on random stuff from the internet.

> It's possible to use a local dns server with no internet access

If you update the test to do so, then that seems fine -- until that point it seems the test should be skipped? Or there should be an opt-in configuration to run "integration-style tests".

**Comment by rickystewart** [comment]
You can also mock out the lookup. Or delete the sub-test -- I wonder if it actually provides any value, or if it's possible for it to fail in a way that is meaningful and representative of an actual bug. Of course the lookup for a non-existent domain will fail -- what do we get from checking?

**Comment by knz** [comment]
The test is checking the text of the error encountered so that it matches what we have in documentation. I don't find it superfluous.

I welcome your suggestions on how to mock this. (I am also not the owner of this code currently so my attention here will be best effort. Ask @nkodali if there's any urgency)

**Comment by rickystewart** [comment]
> I welcome your suggestions on how to mock this.

Instead of directly using `net.Resolver`, use a mock object behind an interface. That object needs `LookupPort` and `LookupIPAddr` methods. For the production case, you would just use the `DefaultResolver`. For testing, use a fake object that doesn't do actual DNS lookups. Functions in `net` like `SplitHostPort` would help with implementation. In the error case being discussed, you just need to make sure `LookupIPAddr` returns an error `"no such host"`, which is exactly what the [actual implementation does](https://cs.opensource.google/go/go/+/master:src/net/net.go;l=617?q=%22no%20such%20host%22&ss=go%2Fgo).
