### ISSUE TITLE
ttl: `ttl_expire_after` and `ttl_expiration_expression` should not be allowed to be set at the same time

### ISSUE THREAD

**Issue by Xiang-Gu** [cockroachdb/cockroach#109138]
We support two ways to effect row-level ttl: `ttl_expire_after` and `ttl_expiration_expression`.

Today, we support both to be set at the same time on one table. Although there is nothing wrong per se (we can still define the expected behavior in this case) but it is confusing and bug prune. I think it's best that we disallow this case.

PS: a bug that currently exists as a result of allowing both to be set:
If we create a table with both parameter set, `RESET (ttl_expire_after)` will remove the whole TTL configuration but the expected behavior is to just remove `ttl_expire_after` because we'd still have `ttl_expiration_expression` to vest TTL on this table. I guess this bug existed bc previously, we only support `ttl_expire_after` and resetting it means remove/disable TTL on this table so it makes sense to remove TTL configuration altogether. Later, when we added support for `ttl_expiration_expression`, we forget to amend that behavior.

Jira issue: CRDB-30800

Epic CRDB-29110

**Comment by dikshant** [comment]
We should now allow both at the same time. If ttl_expire_after is set, and someone tries to set ttl_expiration_expression we should emit and error saying both cannot be set at the same time, please remove ttl_expire_after and vice versa.
