### ISSUE TITLE
storage: `TestFileRegistryKeepOldFilesAndSync` fails under remote execution

### ISSUE THREAD

**Issue by rickystewart** [cockroachdb/cockroach#109176]
EngFlow link: https://tanzanite.cluster.engflow.com/invocation/878da7b3-e648-4037-8cb2-52516441d2d5
Reproduction command: `bazel test //pkg/storage:storage_test --config engflow --config crosslinux --jobs 400 --config cibase --test_filter=TestFileRegistryKeepOldFilesAndSync --test_arg -show-logs`

I don't see anything in the logs, so if something is failing it's not clear what it is.

https://cockroachlabs.atlassian.net/wiki/spaces/devinf/pages/3141107902/How+to+reproduce+a+test+failure+on+EngFlow

Epic: CRDB-8308

Jira issue: CRDB-30809

**Comment by sumeerbhola** [comment]
Trying to reproduce but running into difficulties with TLS certificate needed for remote execution.

```
$ bazel test //pkg/storage:storage_test --config engflow --config crosslinux --jobs 400 --config cibase --test_filter=TestFileRegistryKeepOldFilesAndSync --test_arg -show-logs
INFO: Invocation ID: 30088e9f-f4fb-4c1d-8b29-b18e0d4a9ff6
ERROR: Failed to query remote execution capabilities: PERMISSION_DENIED: You must provide a client TLS certificate with a Common Name (CN); for Bazel, use --tls_client_certificate and --tls_client_key
INFO: Streaming build results to: https://tanzanite.cluster.engflow.com/invocation/30088e9f-f4fb-4c1d-8b29-b18e0d4a9ff6

$ cd
$ mkdir mycerts
$ openssl genrsa -out mycerts/ca.key 2048
Generating RSA private key, 2048 bit long modulus
..................................................................................................................................+++++
...........................................................................................................+++++
e is 65537 (0x10001)

$ openssl req -new -x509 -sha256 -config mycerts/ca.cnf -key mycerts/ca.key -out mycerts/ca.crt -days 3650

$ openssl x509 -noout -subject -in mycerts/ca.crt 
subject= /O=sumeer-org

$ cd -

$ bazel test //pkg/storage:storage_test --config engflow --config crosslinux --jobs 400 --config cibase --test_filter=TestFileRegistryKeepOldFilesAndSync --test_arg -show-logs --tls_client_certificate ~/mycerts/ca.crt --tls_client_key ~/mycerts/ca.key 
INFO: Invocation ID: f5eb7b14-0ec7-4062-861b-6270111be34b
ERROR: Failed to query remote execution capabilities: Failed to init TLS infrastructure using '/Users/sumeer/mycerts/ca.crt' as client certificate: File does not contain valid private key: /Users/sumeer/mycerts/ca.key
ERROR: Failed to init TLS infrastructure using '/Users/sumeer/mycerts/ca.crt' as client certificate: File does not contain valid private key: /Users/sumeer/mycerts/ca.key

$ openssl rsa -in ~/mycerts/ca.key -text
RSA Private-Key: (2048 bit)
<snip>
```

**Comment by rickystewart** [comment]
Hi @sumeerbhola. The [documentation I linked](https://cockroachlabs.atlassian.net/wiki/spaces/devinf/pages/3141107902/How+to+reproduce+a+test+failure+on+EngFlow) describes how to get the cert you need.

**Comment by rickystewart** [comment]
> @rickystewart do you know how much memory these remote machines are allowing the test to use?

Let me have a look. It is probably very limited.

**Comment by rickystewart** [comment]
@sumeerbhola It's 3.5GB. How much memory would be required to do everything this test is trying to do?

**Comment by sumeerbhola** [comment]
> How much memory would be required to do everything this test is trying to do?

Less than 1GB, even accounting for the 2 copies of the data kept in a `memFile`.

The total allocated is much higher because slices are getting re-allocated via append up to a size of ~134MB, and memFiles are being deleted -- according to pprof the alloc_space is ~20GB. Is it possible that the garbage collector is not collecting aggressively enough because it thinks the memory limit is higher than 3.5GB?

**Comment by rickystewart** [comment]
I wonder if the TestMVCCHistories thing is a dupe of #110403.
