### ISSUE TITLE
sql: boostrap a user-controlled o11y db for SQL obs

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#109125]
See [internal proposal](https://docs.google.com/document/d/1MZbpQta9YOiCet0CZlTdfH-ATnp2pWbEJBlQlUhXZfo/edit).

Jira issue: CRDB-30793

Epic CRDB-31701

**Comment by fqazi** [comment]
Both options are reasonable, but the second option won't be needed once the mixed version state is gone/removed for good. I can't think of any other choices since we would need to influence name resolution, and the scope has to be narrow.

**Comment by maryliag** [comment]
No longer a priority
