### ISSUE TITLE
Errors printed to stderr on node shutdown

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#10910]
When starting a local node and then shutting it down, I've been seeing the following messages printed to stderr:

```
~$ cockroach quit --port=26259
initiating graceful shutdown of server
I161121 10:36:40.019589 26 http2_client.go:1053  transport: http2Client.notifyError got notified that the client transport was broken EOF.
I161121 10:36:40.020156 1 util/stop/stopper.go:396  stop has been called, stopping or quiescing all running tasks
I161121 10:36:40.020238 36 /Users/jesseseldess/src/google.golang.org/grpc/clientconn.go:667  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp: operation was canceled"; Reconnecting to {"localhost:26259" <nil>}
I161121 10:36:40.020262 36 /Users/jesseseldess/src/google.golang.org/grpc/clientconn.go:767  grpc: addrConn.transportMonitor exits due to: grpc: the connection is closing
ok
server drained and shutdown completed
```

So @tamird helped me bisect to find the first commit exhibiting this behavior. Starting at `beta-20161027`, which doesn't exhibit this behavior, and continuing until the most recent commit, which does exhibit this behavior, I ran the following:

```
git bisect run sh -c make build && rm -rf cockroach-data && ./cockroach start --background  && ./cockroach node status && ! ./cockroach quit 2>&1 | grep -F "all running tasks"
```

And b00cf84b22f042d9bc39181ff24c643e217e760f seems to be the commit that introduced the issue:

```
b00cf84b22f042d9bc39181ff24c643e217e760f is the first bad commit
commit b00cf84b22f042d9bc39181ff24c643e217e760f
Author: Raphael 'kena' Poss <knz@cockroachlabs.com>
Date:   Mon Nov 14 13:30:58 2016 +0000

    log: cleanup the handling of logging in tests.

    Prior to this patch, if no logging output directory is specified and
    there is no store configured on the command line (the default in most
    tests), logging would silently create an output directory in the
    system-wide temporary directory. This caused test logging output to be
    undiscoverable, and, since this directory was never removed, would
    cause stress test to exhaust the filesystem's inode supply.

    This patch improves upon this behavior as follows:

    - a logging output directory is not any more created automatically.

    - during normal logging, if no output directory is set, logging goes
      to stderr automatically instead.

    - a new struct testLogScope is introduced, intended to be used by
      util/log tests to scope their logging output to the duration of the
      test. This automatically creates a temporary directory named after
      the test and removes it when the test complete, only when the test
      has failed.

    - as a side effect, the tests in pkg/cli are simplified, and a bug in
      the implementation of TestUserInsecure that would
      non-deterministically cause TestDumpRow to fail has been fixed.

:040000 040000 5a581bf4657bf3df78304f4a86a2bea998f56856 1163f96d5fd4b680262382692a84e5476e6bbfc2 M	pkg
```

**Comment by tamird** [comment]
Perhaps this was intended; in particular, b00cf84's commit message calls out
> during normal logging, if no output directory is set, logging goes to stderr automatically instead.

which appears to be what you're seeing here.

**Comment by jseldess** [comment]
Oh, so the `--log-dir` default is no longer `<first-store-dir>/logs`? We now expect that directory to be set explicitly; otherwise, we print to stderr? Why?

**Comment by knz** [comment]
The messages you are seeing are output by the client (the `cockroach quit` command), not the server.

Right now this works as intended: prior to the change in `b00cf84` the logging messages printed by the `cockroach quit` command were simply ... lost. Now at least you can see them.

What behavior do you recommend here? The client program may run on a different machine, so it will not have access to the store directory to log its messages in there.

**Comment by jseldess** [comment]
Ah, ok. The docs say that logs are written to `$TMPDIR` for all commands other than `start`. So now, if no log dir is set on the `quit` command, errors get printed to `stderr`,  is that right? Is that true of all other client commands as well? 

This change does make sense to me now. 

Now the question is: What are those errors telling the user? What action needs to be taken, if any?

**Comment by knz** [comment]
There is one issue to fix in the product right now: these messages logged by `cockroach quit` do not say anything useful and should simply not be emitted at all.

**Comment by jseldess** [comment]
OK, @knz, that was my initial suspicion: that the errors perhaps shouldn't be printed to stderr. Feel free to repurpose this issue, if you like.

**Comment by knz** [comment]
for docs, it is true that messages used to go to `$TMPDIR` *but* they would really go to a sub-directory of `$TMPDIR` and it was impossible to predict which sub-directory. Also the files were not removed automatically, causing literally too many files to be created during tests (so much the OS would break). That's why we changed it.
