### ISSUE TITLE
ui: type check target pulls 178MB off a 3rd party vendor upon every CI run, and fails if upstream is unavailable

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#109154]
This is a variant of #51543 and is currently causing flakes in CI.

**Describe the problem**

The `pkg/ui/workspaces/e2e-tests` target downloads the following URL *every time it runs*:

```
https://download.cypress.io/desktop/10.3.0?platform=linux&arch=x64
```

I went and checked and that is a 178MB archive to download (compressed).

The archive is not cached, unlike the builder image, so that's a mandatory ingress cost on every CI run. 

Moreover, today the upstream HTTP server is saying "no" and is causing all the CI runs to fails. ([example](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/11421071?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true))
![image](https://github.com/cockroachdb/cockroach/assets/642886/d3c8e516-a4f4-41d2-9982-77fe4c52f9d5)

**Expected behavior**

The archive should be embedded in the builder image, and/or the fetch should use a cached copy if it was already downloaded earlier on the TC agent.

(At the very least we should be fetching from a proxy cache inside the CRL infra so that the CI downloads are internal to GCP).

cc @sjbarag @jlinder  @rickystewart for triage.

Epic DEVINF-109

Jira issue: CRDB-30805

**Comment by rickystewart** [comment]
For CI, this should be fixed by #109157. Please re-open if the problem seems to recur.
