### ISSUE TITLE
Sentry: builtins.go:5462: log.Fatal: force_log_fatal(): ×
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/sem/builtins.glob..func249
  | 	github.com/cockroachd...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#109297]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4413897377/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4413897377/?referrer=webhooks_plugin)

Panic Message:

```
builtins.go:5462: log.Fatal: force_log_fatal(): ×
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/sem/builtins.glob..func249
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/builtins/builtins.go:5462
  | github.com/cockroachdb/cockroach/pkg/sql/sem/eval.(*evaluator).EvalFuncExpr
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/eval/expr.go:479
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FuncExpr).Eval
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/sem/tree/eval_expr_generated.go:276
  | github.com/cockroachdb/cockroach/pkg/sql/sem/eval.Expr
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/eval/expr.go:26
  | github.com/cockroachdb/cockroach/pkg/sql.(*valuesNode).startExec
  | 	github.com/cockroachdb/cockroach/pkg/sql/values.go:84
  | github.com/cockroachdb/cockroach/pkg/sql.startExec.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan.go:519
  | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:112
  | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:299
  | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:79
  | github.com/cockroachdb/cockroach/pkg/sql.walkPlan
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:43
  | github.com/cockroachdb/cockroach/pkg/sql.startExec
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan.go:522
  | github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Start
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:175
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Columnarizer).Init
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/columnarizer.go:183
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).init
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:94
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).Init
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:103
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).init.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:245
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).init
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:244
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:278
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:324
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:902
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1913
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll.func3
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1645
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1648
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2155
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1709
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1036
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:142
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:3086
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:141
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2182
Wraps: (2) log.Fatal: force_log_fatal(): ×
Error types: (1) *withstack.withStack (2) *errutil.leafError
-- report composition:
*errutil.leafError: log.Fatal: force_log_fatal(): ×
builtins.go:5462: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/conn_executor.go#L2181-L2183](https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/conn_executor.go#L2181-L2183)
[https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/conn_executor_exec.go#L140-L142](https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/conn_executor_exec.go#L140-L142)
[https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/conn_executor_exec.go#L3085-L3087](https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/conn_executor_exec.go#L3085-L3087)
[https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/conn_executor_exec.go#L141-L143](https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/conn_executor_exec.go#L141-L143)
[https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/conn_executor_exec.go#L1035-L1037](https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/conn_executor_exec.go#L1035-L1037)
[https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/conn_executor_exec.go#L1708-L1710](https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/conn_executor_exec.go#L1708-L1710)
[https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/conn_executor_exec.go#L2154-L2156](https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/conn_executor_exec.go#L2154-L2156)
[https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/distsql_running.go#L1647-L1649](https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/distsql_running.go#L1647-L1649)
[https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/distsql_running.go#L1644-L1646](https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/distsql_running.go#L1644-L1646)
[https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/distsql_running.go#L1912-L1914](https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/distsql_running.go#L1912-L1914)
[https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/distsql_running.go#L901-L903](https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/distsql_running.go#L901-L903)
[https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/colflow/vectorized_flow.go#L323-L325](https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/colflow/vectorized_flow.go#L323-L325)
[https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/colflow/flow_coordinator.go#L277-L279](https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/colflow/flow_coordinator.go#L277-L279)
[https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/colflow/flow_coordinator.go#L243-L245](https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/colflow/flow_coordinator.go#L243-L245)
[https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/colflow/flow_coordinator.go#L244-L246](https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/colflow/flow_coordinator.go#L244-L246)
[https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/colflow/stats.go#L102-L104](https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/colflow/stats.go#L102-L104)
[https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/colflow/stats.go#L93-L95](https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/colflow/stats.go#L93-L95)
[https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/colexec/columnarizer.go#L182-L184](https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/colexec/columnarizer.go#L182-L184)
[https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/plan_node_to_row_source.go#L174-L176](https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/plan_node_to_row_source.go#L174-L176)
[https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/plan.go#L521-L523](https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/plan.go#L521-L523)
[https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/walk.go#L42-L44](https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/walk.go#L42-L44)
[https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/walk.go#L78-L80](https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/walk.go#L78-L80)
[https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/walk.go#L298-L300](https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/walk.go#L298-L300)
[https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/walk.go#L111-L113](https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/walk.go#L111-L113)
[https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/plan.go#L518-L520](https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/plan.go#L518-L520)
[https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/values.go#L83-L85](https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/values.go#L83-L85)
[https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/sem/eval/expr.go#L25-L27](https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/sem/eval/expr.go#L25-L27)
[https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/bazel-out/k8-opt/bin/pkg/sql/sem/tree/eval_expr_generated.go#L275-L277](https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/bazel-out/k8-opt/bin/pkg/sql/sem/tree/eval_expr_generated.go#L275-L277)
[https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/sem/eval/expr.go#L478-L480](https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/sem/eval/expr.go#L478-L480)
[https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/sem/builtins/builtins.go#L5461-L5463](https://github.com/cockroachdb/cockroach/blob/4a78b6ee6751192113afd24e6de40f30262f0d0b/pkg/sql/sem/builtins/builtins.go#L5461-L5463)
</details>

```
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd.func1 at line 2182
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 141
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithProfiling at line 3086
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt.func1 at line 142
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 1036
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchToExecutionEngine at line 1709
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithDistSQLEngine at line 2155
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRunAll at line 1648
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRunAll.func3 at line 1645
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRun at line 1913
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).Run at line 902
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlow).Run at line 324
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).Run at line 278
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).init at line 244
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).init.func1 at line 245
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).Init at line 103
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).init at line 94
pkg/sql/colexec/columnarizer.go in pkg/sql/colexec.(*Columnarizer).Init at line 183
pkg/sql/plan_node_to_row_source.go in pkg/sql.(*planNodeToRowSource).Start at line 175
pkg/sql/plan.go in pkg/sql.startExec at line 522
pkg/sql/walk.go in pkg/sql.walkPlan at line 43
pkg/sql/walk.go in pkg/sql.(*planVisitor).visit at line 79
pkg/sql/walk.go in pkg/sql.(*planVisitor).visitInternal at line 299
pkg/sql/walk.go in pkg/sql.(*planVisitor).visitInternal.func1 at line 112
pkg/sql/plan.go in pkg/sql.startExec.func2 at line 519
pkg/sql/values.go in pkg/sql.(*valuesNode).startExec at line 84
pkg/sql/sem/eval/expr.go in pkg/sql/sem/eval.Expr at line 26
bazel-out/k8-opt/bin/pkg/sql/sem/tree/eval_expr_generated.go in pkg/sql/sem/tree.(*FuncExpr).Eval at line 276
pkg/sql/sem/eval/expr.go in pkg/sql/sem/eval.(*evaluator).EvalFuncExpr at line 479
pkg/sql/sem/builtins/builtins.go in pkg/sql/sem/builtins.glob..func249 at line 5462
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v23.1.9 |
| Go Version | go1.19.10 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.5-811-g4a78b6ee67 |
| Cockroach SHA | 4a78b6ee6751192113afd24e6de40f30262f0d0b |
| # of CPUs | 8 |
| # of Goroutines | 779 |

Jira issue: CRDB-30855

**Comment by yuzefovich** [comment]
expected behavior
