### ISSUE TITLE
catalog/lease: make some tests work with test tenant

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#109385]
The following tests will be skipped when #108762 merges:
- `TestReadBeforeDrop`
- `TestTableCreationPushesTxnsInRecentPast`
- `TestTxnObeysTableModificationTime`

Jira issue: CRDB-30894
Epic: CRDB-26687

**Comment by rafiss** [comment]
Let's try to timebox this and see if we can unskip any of these.
