### ISSUE TITLE
Sentry: log.go:479: log.Fatal: entries[37:6130) is unavailable from storage
(1) attached stack trace
  -- stack trace:
  | go.etcd.io/raft/v3.(*raftLog).slice
  | 	go.etcd.io/raft/v3/external/io_etcd_...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#109328]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4414952628/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4414952628/?referrer=webhooks_plugin)

Panic Message:

```
log.go:479: log.Fatal: entries[37:6130) is unavailable from storage
(1) attached stack trace
  -- stack trace:
  | go.etcd.io/raft/v3.(*raftLog).slice
  | 	go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/log.go:479
  | go.etcd.io/raft/v3.(*raftLog).entries
  | 	go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/log.go:413
  | go.etcd.io/raft/v3.(*raft).maybeSendAppend
  | 	go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/raft.go:586
  | go.etcd.io/raft/v3.(*raft).sendAppend
  | 	go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/raft.go:560
  | go.etcd.io/raft/v3.stepLeader
  | 	go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/raft.go:1404
  | go.etcd.io/raft/v3.(*raft).Step
  | 	go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/raft.go:1156
  | go.etcd.io/raft/v3.(*RawNode).Step
  | 	go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/rawnode.go:124
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).stepRaftGroup.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:596
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).withRaftGroupLocked.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:1982
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).withRaftGroupLocked
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:1983
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).withRaftGroup
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:2028
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).stepRaftGroup
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:574
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processRaftRequestWithReplica
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:388
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processRequestQueue.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:591
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).withReplicaForRequest
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:343
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processRequestQueue
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:589
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftSchedulerShard).worker
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:376
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).Start.func2
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:302
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (2) log.Fatal: entries[37:6130) is unavailable from storage
Error types: (1) *withstack.withStack (2) *errutil.leafError
-- report composition:
*errutil.leafError: log.Fatal: entries[37:6130) is unavailable from storage
log.go:479: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/util/stop/stopper.go#L469-L471](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/util/stop/stopper.go#L469-L471)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L301-L303](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L301-L303)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L375-L377](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L375-L377)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L588-L590](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L588-L590)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L342-L344](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L342-L344)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L590-L592](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L590-L592)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L387-L389](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L387-L389)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L573-L575](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L573-L575)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L2027-L2029](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L2027-L2029)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L1982-L1984](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L1982-L1984)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L1981-L1983](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L1981-L1983)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L595-L597](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L595-L597)
[go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/rawnode.go#L123-L125](go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/rawnode.go#L123-L125)
[go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/raft.go#L1155-L1157](go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/raft.go#L1155-L1157)
[go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/raft.go#L1403-L1405](go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/raft.go#L1403-L1405)
[go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/raft.go#L559-L561](go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/raft.go#L559-L561)
[go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/raft.go#L585-L587](go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/raft.go#L585-L587)
[go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/log.go#L412-L414](go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/log.go#L412-L414)
[go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/log.go#L478-L480](go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/log.go#L478-L480)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 470
pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go in pkg/kv/kvserver.(*raftScheduler).Start.func2 at line 302
pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go in pkg/kv/kvserver.(*raftSchedulerShard).worker at line 376
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).processRequestQueue at line 589
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).withReplicaForRequest at line 343
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).processRequestQueue.func1 at line 591
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).processRaftRequestWithReplica at line 388
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).stepRaftGroup at line 574
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).withRaftGroup at line 2028
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).withRaftGroupLocked at line 1983
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).withRaftGroupLocked.func1 at line 1982
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).stepRaftGroup.func1 at line 596
go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/rawnode.go in go.etcd.io/raft/v3.(*RawNode).Step at line 124
go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/raft.go in go.etcd.io/raft/v3.(*raft).Step at line 1156
go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/raft.go in go.etcd.io/raft/v3.stepLeader at line 1404
go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/raft.go in go.etcd.io/raft/v3.(*raft).sendAppend at line 560
go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/raft.go in go.etcd.io/raft/v3.(*raft).maybeSendAppend at line 586
go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/log.go in go.etcd.io/raft/v3.(*raftLog).entries at line 413
go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/log.go in go.etcd.io/raft/v3.(*raftLog).slice at line 479
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v23.1.2 |
| Go Version | go1.19.4 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.2 |
| Cockroach SHA | 810d4f27a7f02b9cc2750cab654ed1c62ac3e75a |
| # of CPUs | 16 |
| # of Goroutines | 511 |

Jira issue: CRDB-30879

**Comment by yuzefovich** [comment]
same cluster as #109327
