### ISSUE TITLE
cluster-ui: remove uses of `withTimeout` on sql-over-http calls

### ISSUE THREAD

**Issue by THardy98** [cockroachdb/cockroach#109436]
**Describe the problem**

Currently, sql-over-http calls using `withTimeout` use two timeouts in a single network call:
- `withTimeout`: assigns a promise timeout for the network request
- as part of the request payload, we specify a timeout for query execution

The misalignment is confusing, unnecessary, and not the intended timeout functionality.

Instead, we should specify a single timeout that captures both network and query latency. We can do this by specifying a timeout in the [header of the request](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Keep-Alive), consequently, usages of `withTimeout` on sql-over-http calls should be removed.

Jira issue: CRDB-30925

**Comment by maryliag** [comment]
No longer a priority
