### ISSUE TITLE
sql: v22.2.6-custom: CC: non-nullable column with no value

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#109493]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4420077052/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4420077052/?referrer=webhooks_plugin)

Panic Message:

```
fetcher.go:1237: Non-nullable column "×:×" with no value! Index scanned was × with the index key columns (×) and the values (×)
(1)
Wraps: (2)
Wraps: (3) assertion failure
Wraps: (4) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/row.(*Fetcher).finalizeRow
  | 	github.com/cockroachdb/cockroach/pkg/sql/row/fetcher.go:1237
  | github.com/cockroachdb/cockroach/pkg/sql/row.(*Fetcher).NextRow
  | 	github.com/cockroachdb/cockroach/pkg/sql/row/fetcher.go:1084
  | github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*joinReader).performLookup
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowexec/joinreader.go:1013
  | github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*joinReader).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowexec/joinreader.go:733
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Columnarizer).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/columnarizer.go:243
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.getNext_false
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/colexec/hash_aggregator.eg.go:546
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*hashAggregator).Next
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/colexec/hash_aggregator.eg.go:90
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk.(*diskSpillerBase).Next.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk/disk_spiller.go:198
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk.(*diskSpillerBase).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk/disk_spiller.go:196
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexechash.(*HashTable).FullBuild
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexechash/hashtable.go:491
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecjoin.(*hashJoiner).build
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecjoin/hashjoiner.go:329
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecjoin.(*hashJoiner).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecjoin/hashjoiner.go:291
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk.(*diskSpillerBase).Next.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk/disk_spiller.go:198
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk.(*diskSpillerBase).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk/disk_spiller.go:196
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.spool_false
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/colexec/sorttopk.eg.go:320
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*topKSorter).spool
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/colexec/sorttopk.eg.go:73
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*topKSorter).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/sorttopk.go:165
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk.(*diskSpillerBase).Next.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk/disk_spiller.go:198
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk.(*diskSpillerBase).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk/disk_spiller.go:196
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Materializer).next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:286
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Materializer).nextAdapter
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:311
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Materializer).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:317
  | github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*joinReader).readInput
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowexec/joinreader.go:846
  | github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*joinReader).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowexec/joinreader.go:731
  | github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*joinReader).readInput
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowexec/joinreader.go:846
  | github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*joinReader).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowexec/joinreader.go:731
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Columnarizer).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/columnarizer.go:243
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils.(*BatchSchemaSubsetEnforcer).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils/operator.go:204
Wraps: (5) Non-nullable column "×:×" with no value! Index scanned was × with the index key columns (×) and the values (×)
Error types: (1) *colexecerror.notInternalError (2) *colexecerror.notInternalError (3) *assert.withAssertionFailure (4) *withstack.withStack (5) *errutil.leafError
-- report composition:
*errutil.leafError: Non-nullable column "×:×" with no value! Index scanned was × with the index key columns (×) and the values (×)
fetcher.go:1237: *withstack.withStack (top exception)
*assert.withAssertionFailure
*colexecerror.notInternalError
*colexecerror.notInternalError
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/colexec/colexecutils/operator.go#L203-L205](https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/colexec/colexecutils/operator.go#L203-L205)
[https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/colexec/columnarizer.go#L242-L244](https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/colexec/columnarizer.go#L242-L244)
[https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/rowexec/joinreader.go#L730-L732](https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/rowexec/joinreader.go#L730-L732)
[https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/rowexec/joinreader.go#L845-L847](https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/rowexec/joinreader.go#L845-L847)
[https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/rowexec/joinreader.go#L730-L732](https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/rowexec/joinreader.go#L730-L732)
[https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/rowexec/joinreader.go#L845-L847](https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/rowexec/joinreader.go#L845-L847)
[https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/colexec/materializer.go#L316-L318](https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/colexec/materializer.go#L316-L318)
[https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/colexec/materializer.go#L310-L312](https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/colexec/materializer.go#L310-L312)
[https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/colexec/materializer.go#L285-L287](https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/colexec/materializer.go#L285-L287)
[https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/colexec/colexecdisk/disk_spiller.go#L195-L197](https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/colexec/colexecdisk/disk_spiller.go#L195-L197)
[https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/colexec/colexecdisk/disk_spiller.go#L197-L199](https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/colexec/colexecdisk/disk_spiller.go#L197-L199)
[https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/colexec/sorttopk.go#L164-L166](https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/colexec/sorttopk.go#L164-L166)
[https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/bazel-out/k8-opt/bin/pkg/sql/colexec/sorttopk.eg.go#L72-L74](https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/bazel-out/k8-opt/bin/pkg/sql/colexec/sorttopk.eg.go#L72-L74)
[https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/bazel-out/k8-opt/bin/pkg/sql/colexec/sorttopk.eg.go#L319-L321](https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/bazel-out/k8-opt/bin/pkg/sql/colexec/sorttopk.eg.go#L319-L321)
[https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/colexec/colexecdisk/disk_spiller.go#L195-L197](https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/colexec/colexecdisk/disk_spiller.go#L195-L197)
[https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/colexec/colexecdisk/disk_spiller.go#L197-L199](https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/colexec/colexecdisk/disk_spiller.go#L197-L199)
[https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/colexec/colexecjoin/hashjoiner.go#L290-L292](https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/colexec/colexecjoin/hashjoiner.go#L290-L292)
[https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/colexec/colexecjoin/hashjoiner.go#L328-L330](https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/colexec/colexecjoin/hashjoiner.go#L328-L330)
[https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/colexec/colexechash/hashtable.go#L490-L492](https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/colexec/colexechash/hashtable.go#L490-L492)
[https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/colexec/colexecdisk/disk_spiller.go#L195-L197](https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/colexec/colexecdisk/disk_spiller.go#L195-L197)
[https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/colexec/colexecdisk/disk_spiller.go#L197-L199](https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/colexec/colexecdisk/disk_spiller.go#L197-L199)
[https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/bazel-out/k8-opt/bin/pkg/sql/colexec/hash_aggregator.eg.go#L89-L91](https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/bazel-out/k8-opt/bin/pkg/sql/colexec/hash_aggregator.eg.go#L89-L91)
[https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/bazel-out/k8-opt/bin/pkg/sql/colexec/hash_aggregator.eg.go#L545-L547](https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/bazel-out/k8-opt/bin/pkg/sql/colexec/hash_aggregator.eg.go#L545-L547)
[https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/colexec/columnarizer.go#L242-L244](https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/colexec/columnarizer.go#L242-L244)
[https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/rowexec/joinreader.go#L732-L734](https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/rowexec/joinreader.go#L732-L734)
[https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/rowexec/joinreader.go#L1012-L1014](https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/rowexec/joinreader.go#L1012-L1014)
[https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/row/fetcher.go#L1083-L1085](https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/row/fetcher.go#L1083-L1085)
[https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/row/fetcher.go#L1236-L1238](https://github.com/cockroachdb/cockroach/blob/a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c/pkg/sql/row/fetcher.go#L1236-L1238)
</details>

```
pkg/sql/colexec/colexecutils/operator.go in pkg/sql/colexec/colexecutils.(*BatchSchemaSubsetEnforcer).Next at line 204
pkg/sql/colexec/columnarizer.go in pkg/sql/colexec.(*Columnarizer).Next at line 243
pkg/sql/rowexec/joinreader.go in pkg/sql/rowexec.(*joinReader).Next at line 731
pkg/sql/rowexec/joinreader.go in pkg/sql/rowexec.(*joinReader).readInput at line 846
pkg/sql/rowexec/joinreader.go in pkg/sql/rowexec.(*joinReader).Next at line 731
pkg/sql/rowexec/joinreader.go in pkg/sql/rowexec.(*joinReader).readInput at line 846
pkg/sql/colexec/materializer.go in pkg/sql/colexec.(*Materializer).Next at line 317
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colexec/materializer.go in pkg/sql/colexec.(*Materializer).nextAdapter at line 311
pkg/sql/colexec/materializer.go in pkg/sql/colexec.(*Materializer).next at line 286
pkg/sql/colexec/colexecdisk/disk_spiller.go in pkg/sql/colexec/colexecdisk.(*diskSpillerBase).Next at line 196
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colexec/colexecdisk/disk_spiller.go in pkg/sql/colexec/colexecdisk.(*diskSpillerBase).Next.func1 at line 198
pkg/sql/colexec/sorttopk.go in pkg/sql/colexec.(*topKSorter).Next at line 165
bazel-out/k8-opt/bin/pkg/sql/colexec/sorttopk.eg.go in pkg/sql/colexec.(*topKSorter).spool at line 73
bazel-out/k8-opt/bin/pkg/sql/colexec/sorttopk.eg.go in pkg/sql/colexec.spool_false at line 320
pkg/sql/colexec/colexecdisk/disk_spiller.go in pkg/sql/colexec/colexecdisk.(*diskSpillerBase).Next at line 196
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colexec/colexecdisk/disk_spiller.go in pkg/sql/colexec/colexecdisk.(*diskSpillerBase).Next.func1 at line 198
pkg/sql/colexec/colexecjoin/hashjoiner.go in pkg/sql/colexec/colexecjoin.(*hashJoiner).Next at line 291
pkg/sql/colexec/colexecjoin/hashjoiner.go in pkg/sql/colexec/colexecjoin.(*hashJoiner).build at line 329
pkg/sql/colexec/colexechash/hashtable.go in pkg/sql/colexec/colexechash.(*HashTable).FullBuild at line 491
pkg/sql/colexec/colexecdisk/disk_spiller.go in pkg/sql/colexec/colexecdisk.(*diskSpillerBase).Next at line 196
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colexec/colexecdisk/disk_spiller.go in pkg/sql/colexec/colexecdisk.(*diskSpillerBase).Next.func1 at line 198
bazel-out/k8-opt/bin/pkg/sql/colexec/hash_aggregator.eg.go in pkg/sql/colexec.(*hashAggregator).Next at line 90
bazel-out/k8-opt/bin/pkg/sql/colexec/hash_aggregator.eg.go in pkg/sql/colexec.getNext_false at line 546
pkg/sql/colexec/columnarizer.go in pkg/sql/colexec.(*Columnarizer).Next at line 243
pkg/sql/rowexec/joinreader.go in pkg/sql/rowexec.(*joinReader).Next at line 733
pkg/sql/rowexec/joinreader.go in pkg/sql/rowexec.(*joinReader).performLookup at line 1013
pkg/sql/row/fetcher.go in pkg/sql/row.(*Fetcher).NextRow at line 1084
pkg/sql/row/fetcher.go in pkg/sql/row.(*Fetcher).finalizeRow at line 1237
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v22.2.6-1-ga1fc98954a |
| Go Version | go1.19.4 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v22.2.6-1-ga1fc98954a |
| Cockroach SHA | a1fc98954a5ea0f507653b3ceb2432b6d19bfc3c |
| # of CPUs | 8 |
| # of Goroutines | 1110 |

Jira issue: CRDB-30950

**Comment by yuzefovich** [comment]
unactionable

**Comment by yuzefovich** [comment]
This is in a CC cluster, trying to determine which one in https://cockroachlabs.slack.com/archives/C01C3B15GQ1/p1692986402773049

**Comment by rharding6373** [comment]
This error is usually indicative of a split row in a table with multiple column families.

I followed up on the internal channel here: https://cockroachlabs.slack.com/archives/C0247P9988N/p1693338026286099

**Comment by yuzefovich** [comment]
unactionable
