### ISSUE TITLE
Sentry: db.go:742: log.Fatal: resource temporarily unavailable
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/pebble.(*DB).Apply
  | 	github.com/cockroachdb/pebble/external/com_...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#109403]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4416856069/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4416856069/?referrer=webhooks_plugin)

Panic Message:

```
db.go:742: log.Fatal: resource temporarily unavailable
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/pebble.(*DB).Apply
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go:742
  | github.com/cockroachdb/pebble.(*DB).Set
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go:554
  | github.com/cockroachdb/cockroach/pkg/storage.(*Pebble).put
  | 	github.com/cockroachdb/cockroach/pkg/storage/pebble.go:1320
  | github.com/cockroachdb/cockroach/pkg/storage.(*Pebble).PutUnversioned
  | 	github.com/cockroachdb/cockroach/pkg/storage/pebble.go:1297
  | github.com/cockroachdb/cockroach/pkg/storage.(*putBuffer).putInlineMeta
  | 	github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:1259
  | github.com/cockroachdb/cockroach/pkg/storage.mvccPutInternal
  | 	github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:1672
  | github.com/cockroachdb/cockroach/pkg/storage.mvccPutUsingIter
  | 	github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:1410
  | github.com/cockroachdb/cockroach/pkg/storage.MVCCPut
  | 	github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:1329
  | github.com/cockroachdb/cockroach/pkg/storage.MVCCPutProto
  | 	github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:841
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).WriteLastUpTimestamp
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store.go:2753
  | github.com/cockroachdb/cockroach/pkg/server.(*Server).PreStart.func10.1
  | 	github.com/cockroachdb/cockroach/pkg/server/server.go:1571
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Stores).VisitStores.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/stores.go:150
  | github.com/cockroachdb/cockroach/pkg/util/syncutil.(*IntMap).Range
  | 	github.com/cockroachdb/cockroach/pkg/util/syncutil/int_map.go:352
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Stores).VisitStores
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/stores.go:149
  | github.com/cockroachdb/cockroach/pkg/server.(*Server).PreStart.func10
  | 	github.com/cockroachdb/cockroach/pkg/server/server.go:1570
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/liveness.(*NodeLiveness).updateLivenessAttempt
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/liveness/liveness.go:1397
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/liveness.(*NodeLiveness).updateLiveness
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/liveness/liveness.go:1304
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/liveness.(*NodeLiveness).heartbeatInternal
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/liveness/liveness.go:960
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/liveness.(*NodeLiveness).Start.func1.1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/liveness/liveness.go:775
  | github.com/cockroachdb/cockroach/pkg/util/contextutil.RunWithTimeout
  | 	github.com/cockroachdb/cockroach/pkg/util/contextutil/context.go:91
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/liveness.(*NodeLiveness).Start.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/liveness/liveness.go:758
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:489
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (2) secondary error attachment
  | resource temporarily unavailable
  | (1) resource temporarily unavailable
  | Error types: (1) syscall.Errno
Wraps: (3) log.Fatal: resource temporarily unavailable
Error types: (1) *withstack.withStack (2) *secondary.withSecondaryError (3) *errutil.leafError
-- report composition:
*errutil.leafError: log.Fatal: resource temporarily unavailable
*secondary.withSecondaryError
db.go:742: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/util/stop/stopper.go#L488-L490](https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/util/stop/stopper.go#L488-L490)
[https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/kv/kvserver/liveness/liveness.go#L757-L759](https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/kv/kvserver/liveness/liveness.go#L757-L759)
[https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/util/contextutil/context.go#L90-L92](https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/util/contextutil/context.go#L90-L92)
[https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/kv/kvserver/liveness/liveness.go#L774-L776](https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/kv/kvserver/liveness/liveness.go#L774-L776)
[https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/kv/kvserver/liveness/liveness.go#L959-L961](https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/kv/kvserver/liveness/liveness.go#L959-L961)
[https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/kv/kvserver/liveness/liveness.go#L1303-L1305](https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/kv/kvserver/liveness/liveness.go#L1303-L1305)
[https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/kv/kvserver/liveness/liveness.go#L1396-L1398](https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/kv/kvserver/liveness/liveness.go#L1396-L1398)
[https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/server/server.go#L1569-L1571](https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/server/server.go#L1569-L1571)
[https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/kv/kvserver/pkg/kv/kvserver/stores.go#L148-L150](https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/kv/kvserver/pkg/kv/kvserver/stores.go#L148-L150)
[https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/util/syncutil/int_map.go#L351-L353](https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/util/syncutil/int_map.go#L351-L353)
[https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/kv/kvserver/pkg/kv/kvserver/stores.go#L149-L151](https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/kv/kvserver/pkg/kv/kvserver/stores.go#L149-L151)
[https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/server/server.go#L1570-L1572](https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/server/server.go#L1570-L1572)
[https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/kv/kvserver/pkg/kv/kvserver/store.go#L2752-L2754](https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/kv/kvserver/pkg/kv/kvserver/store.go#L2752-L2754)
[https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/storage/mvcc.go#L840-L842](https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/storage/mvcc.go#L840-L842)
[https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/storage/mvcc.go#L1328-L1330](https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/storage/mvcc.go#L1328-L1330)
[https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/storage/mvcc.go#L1409-L1411](https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/storage/mvcc.go#L1409-L1411)
[https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/storage/mvcc.go#L1671-L1673](https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/storage/mvcc.go#L1671-L1673)
[https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/storage/mvcc.go#L1258-L1260](https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/storage/mvcc.go#L1258-L1260)
[https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/storage/pebble.go#L1296-L1298](https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/storage/pebble.go#L1296-L1298)
[https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/storage/pebble.go#L1319-L1321](https://github.com/cockroachdb/cockroach/blob/81a114c2bc2ef8ef76fe3809d0469319c7e82635/pkg/storage/pebble.go#L1319-L1321)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L553-L555](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L553-L555)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L741-L743](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L741-L743)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 489
pkg/kv/kvserver/liveness/liveness.go in pkg/kv/kvserver/liveness.(*NodeLiveness).Start.func1 at line 758
pkg/util/contextutil/context.go in pkg/util/contextutil.RunWithTimeout at line 91
pkg/kv/kvserver/liveness/liveness.go in pkg/kv/kvserver/liveness.(*NodeLiveness).Start.func1.1 at line 775
pkg/kv/kvserver/liveness/liveness.go in pkg/kv/kvserver/liveness.(*NodeLiveness).heartbeatInternal at line 960
pkg/kv/kvserver/liveness/liveness.go in pkg/kv/kvserver/liveness.(*NodeLiveness).updateLiveness at line 1304
pkg/kv/kvserver/liveness/liveness.go in pkg/kv/kvserver/liveness.(*NodeLiveness).updateLivenessAttempt at line 1397
pkg/server/server.go in pkg/server.(*Server).PreStart.func10 at line 1570
pkg/kv/kvserver/pkg/kv/kvserver/stores.go in pkg/kv/kvserver.(*Stores).VisitStores at line 149
pkg/util/syncutil/int_map.go in pkg/util/syncutil.(*IntMap).Range at line 352
pkg/kv/kvserver/pkg/kv/kvserver/stores.go in pkg/kv/kvserver.(*Stores).VisitStores.func1 at line 150
pkg/server/server.go in pkg/server.(*Server).PreStart.func10.1 at line 1571
pkg/kv/kvserver/pkg/kv/kvserver/store.go in pkg/kv/kvserver.(*Store).WriteLastUpTimestamp at line 2753
pkg/storage/mvcc.go in pkg/storage.MVCCPutProto at line 841
pkg/storage/mvcc.go in pkg/storage.MVCCPut at line 1329
pkg/storage/mvcc.go in pkg/storage.mvccPutUsingIter at line 1410
pkg/storage/mvcc.go in pkg/storage.mvccPutInternal at line 1672
pkg/storage/mvcc.go in pkg/storage.(*putBuffer).putInlineMeta at line 1259
pkg/storage/pebble.go in pkg/storage.(*Pebble).PutUnversioned at line 1297
pkg/storage/pebble.go in pkg/storage.(*Pebble).put at line 1320
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go in github.com/cockroachdb/pebble.(*DB).Set at line 554
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go in github.com/cockroachdb/pebble.(*DB).Apply at line 742
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v22.2.3 |
| Go Version | go1.19.1 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v22.2.3 |
| Cockroach SHA | 81a114c2bc2ef8ef76fe3809d0469319c7e82635 |
| # of CPUs | 8 |
| # of Goroutines | 366 |

Jira issue: CRDB-30903

**Comment by yuzefovich** [comment]
dup of #86703
