### ISSUE TITLE
kv95/enc=false/nodes=3/cpu=96 regression on July 17, 2023

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#109443]
**Describe the problem**

`kv95/enc=false/nodes=3/cpu=96` had a regression in July. QPS dropped from ~185k down to ~150k.

**To Reproduce**

See https://roachperf.crdb.dev/?filter=&view=kv95%2Fenc%3Dfalse%2Fnodes%3D3%2Fcpu%3D96&tab=gce

Jira issue: CRDB-30926

**Comment by smg260** [comment]
I also ran this test against latest master with the above commit (#106944)  and its subsequent "partial revert" commit (#107207), reverted. 

Result: `179597.8 ops/s` - in line with the higher pre-regression throughput.

**Comment by smg260** [comment]
Not so fast...

Same code -

via gce-worker
<img width="1553" alt="image" src="https://github.com/cockroachdb/cockroach/assets/25202158/5c944ec3-5612-438d-abfc-a07d1068ae39">


via CI
<img width="1601" alt="image" src="https://github.com/cockroachdb/cockroach/assets/25202158/944c4d97-cf20-4ded-936b-7ccf2924b0d1">

**Comment by smg260** [comment]
The start regression date lead to the bisect identifying the above commit, which did cause a regression, but that commit was subsequently fixed, which means something else was introduced.

So we again bisect, but with a new starting good commit (the fix for above: `f52fe97ad8`) and the same known bad commit (`06b5ba78883`). 

Specifying `--first-parent`, bisect only follows the first parent of merge commits, resulting in the offending merge commit below. 
```
2023-08-25T20:07:04Z   Bisecting regression in [kv95/enc=false/nodes=3/cpu=96] using commit range [f52fe97ad8b (known good),c6f4c0ed6e3 (known bad)]
2023-08-25T20:07:04Z   Thresholds [good >= 179696, bad <= 144555]
2023-08-25T20:24:11Z   [e23993ff117] avg ops/s: [143712]. Auto marked as bad.
2023-08-25T20:52:30Z   [b005e97c4ba] avg ops/s: [178173]. User marked as good. Threshold updated.
2023-08-25T20:52:30Z   Bisection complete. Suspect commit:

commit e23993ff117521c5bf72390c46f589b275af9747
Merge: b005e97c4ba a792cd30a86 466c4e9b709 8e4578b0e20 db4be30fa87 fb97251da55 a05d100dfae f52fe97ad8b
Author: craig[bot] <bors@cockroachlabs.com>
Date:   Wed Jul 19 22:12:33 2023 +0000

    Merge #106860 #106912 #107099 #107170 #107189 #107197 #107207

<... truncated >
```

This is a relatively large batch, and we run the roachtest against each hash until we find the one with a decreased throughput. In this case,  `a792cd30a86` with `~150k`.

For sanity, we check other hashes in the batch. The first "hump" is `a792cd30a86`, clearly less than the others.
<img width="1454" alt="image" src="https://github.com/cockroachdb/cockroach/assets/25202158/e8ee5de5-6d45-46fb-b18e-99a9defaa066">


```
commit a792cd30a864cae879f8f91040b7394304ee3572
Author: j82w <jwilley@cockroachlabs.com>
Date:   Fri Jul 14 15:03:47 2023 -0400

    ssmemstorage: improve lock contention on RecordStatement

    1. The stats object lock was being held even during the insights event
    creation and insert which has it's own lock. The insights logic is now
    moved above the stats lock.
    2. Moved latency calculation outside the stats lock.
    3. Moved error code calculation outside the stats lock.
    4. ss_mem_storage converted to use a RWMutex. Each object in the map
    has it's own lock. Read lock allows mulitple threads to read from the
    map at the same time which is the common case. Writes are only done the
    first time a statement is seen.

    Fixes: #106789, Fixes: #55285

    Release note (performance improvement): Reduced lock contention on
    `ssmemstorage.RecordStatement`. This is useful for workloads that
    execute the same statement concurrently on the same SQL instance.
```

**Comment by rafiss** [comment]
Very nice investigation! a792cd30a864cae879f8f91040b7394304ee3572 is work from the @cockroachdb/cluster-observability team.

**Comment by maryliag** [comment]
that's curious, specially because the benchmark done on that commit shows performance improvements:
https://github.com/cockroachdb/cockroach/pull/106860

cc @j82w

**Comment by srosenberg** [comment]
> that's curious, specially because the benchmark done on that commit shows performance improvements

Unfortunately, this is a great example where microbenchmarks are insufficient. They are great for establishing a relative change (wrt baseline), but we can't rely on them to tell us about absolute performance. Below is a summary of my investigation.

### Investigation

Below, we refer to [a792cd3](https://github.com/cockroachdb/cockroach/commit/a792cd30a864cae879f8f91040b7394304ee3572) as the `bad` run; the `good` run is [f52fe97a](f52fe97ad8b98112f54b0c49165625fc16db1b94). (I've simply cherry-picked the bad run on top of the good run.)

#### CPU Profile

First, the CPU profiles didn't yield any obvious insights (e.g., system is overloaded). However, we can clearly see that the `bad` run is burning ~10% more cpu utilization. Given the context of the change in that commit, it's a hint that the additional cpu cycles are spent on acquiring mutexes.

<img width="1793" alt="cpu_good_run" src="https://github.com/cockroachdb/cockroach/assets/1616764/649ff165-fc92-4055-8564-cf621fb18d00">

<img width="1799" alt="cpu_bad_run" src="https://github.com/cockroachdb/cockroach/assets/1616764/f8114bd1-1a33-4ec7-8995-c0e0d0dff236">

#### Mutex Profile

Indeed, the mutex profiles are very telling.

<img width="1732" alt="mutex_good_run_flame" src="https://github.com/cockroachdb/cockroach/assets/1616764/8025bb32-3cc8-4ad0-b778-5fad141a5ba4">

<img width="1727" alt="mutex_bad_run_flame" src="https://github.com/cockroachdb/cockroach/assets/1616764/d8c7a811-fc52-4989-a50a-c9a16e9e6d56">

**Comment by srosenberg** [comment]
**NOTE**: there appears to be a latent bug which invokes `getStatsForStmtWithKeyLocked ` without a mutex [1].

[1] https://github.com/cockroachdb/cockroach/blob/91907b3e326ae42effdfcac43e0bad0ea2d33d3c/pkg/sql/sqlstats/ssmemstorage/ss_mem_storage.go#L279

**Comment by j82w** [comment]
@srosenberg should I revert the PR?
