### ISSUE TITLE
demo: regression: unclear error on startup if port is in use

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#109460]
**Describe the problem**

If the port is already in use, `demo` shows an error message that is hard to interpret:
```
❯ ./cockroach demo
*
* ERROR: server 0 stopped prematurely
*
ERROR: server 0 stopped prematurely
Failed running "demo"
```

**To Reproduce**

In one shell: `./cockroach start-single-node --insecure`
In another: `./cockroach demo`

**Expected behavior**
The error should say the port is in use. The message that used to be shown is:
```
❯ ./cockroach demo
*
* ERROR: listen tcp 127.0.0.1:26257: bind: address already in use
*
ERROR: cannot dial server.
Is the server running?
If the server is running, check --host client-side and --advertise server-side.

listen tcp 127.0.0.1:26257: bind: address already in use
Failed running "demo"
```

**Environment:**
Tried locally on da1dc5ef861

~Could this relate to https://github.com/cockroachdb/cockroach/pull/108566 ?~
Same error when running on the commit right before this PR.

Jira issue: CRDB-30936

**Comment by rafiss** [comment]
A bisect shows that 49374d4f9efa5a98b91c9ab65a12eed43782f41c is the commit that causes this regression. cc @knz in case you have any immediate thoughts on how to improve this. Otherwise I will look into this later this week.

**Comment by mgartner** [comment]
I think this should be considered a release-blocker, so I've added the label. But please let me know if you disagree.

**Comment by rafiss** [comment]
Moving to multitenant board as per: https://cockroachlabs.slack.com/archives/C02HWA24541/p1694717385012059
