### ISSUE TITLE
`--format` Flag for "cockroach debug merge-logs" Command Not Working as Intended

### ISSUE THREAD

**Issue by NigelNavarro** [cockroachdb/cockroach#109453]
**Describe the problem**

When attempting to use the `--format` flag to format the results of the merge-logs output to JSON, several errors arose, namely:

* `ERROR: error while processing file /debug/nodes/11/logs/cockroach.examplecluster1.cockroachdb.2023-08-22T23_21_42Z.1320513.log: invalid character 'a' looking for beginning of value`

and

* `ERROR: error while processing file /debug/nodes/11/logs/cockroach.examplecluster1.cockroachdb.2023-08-22T23_21_42Z.1320513.log: json: cannot unmarshal number into Go value of type log.JSONEntry`

In order to *Workaround* the issue, I had to use `--format crdb-v1` instead. Given that the logs files themselves read something like: `I230822 20:17:24.252127 757 util/log/file_sync_buffer.go:238 ⋮ [T1,config] log format (utf8=✓): json `, having to use `crdb-v1` is a bit counter-intuitive

**To Reproduce**

1. Download a v23.1 binary (in my case, I used `cockroach-v23.1.4.darwin-10.9-amd64`)
2. Obtain a Debug Zip file for analysis, either through assistance with TSEs or by reproduction of a local cluster
3. Attempt to use `cockroach debug merge-logs /{filepath}/cockroach*.log --format json` and review the terminal output
4. Repeat command but add in any other additional parameters, like the use of `--from` or `--to`, and output to  file `> /{filepath}/results.json`
5. Repeat steps 3 and 4 cyclically until you are able to view the various errors mentioned above.

**Expected behavior**

`--format json` should be able to format the output of the Debug Zip log files into JSON format without errors.

Please reach out if you have any additional questions or concerns. Thank you for taking a look!

Jira issue: CRDB-30931

**Comment by abarganier** [comment]
I think this might be a misunderstanding of the `--format` flag.

`--format` appears to specify the input format, not the output format.

For example, if I set up a demo cluster via:
```
cockroach start-single-node --insecure --log='{ file-defaults: { format: "json" } }'
```

My logs are output as the CRDB json format.

If I then point `cockroach debug merge-logs /my/log/dir/*.log --format=json`, it successfully merges them.

For example, this error:
```
ERROR: invalid character 'I' looking for beginning of value
```

`I` is the first character of an INFO log line in the `crdb-v2` format (which is what the input format is that generated this error). We're telling merge-logs to expect JSON. So, this error is saying "I'm expecting JSON, but no valid JSON begins with `I`".

This is documented in the CLI command's help text:
```
$ ./cockroach debug merge-logs -h
...
  cockroach debug merge-logs <log file globs> [flags]

Flags:
      ...
      --format string             log format of the input files
```

**Comment by abarganier** [comment]
(Marking as closed, but reopen if needed)

**Comment by ricardocrdb** [comment]
Perhaps you can clarify then what the `log format` in the log itself means from the debug zip, as that is what I checked when using the `--format` flag, and based my `cockroach debug merge-logs` on that parameter.

```
I230822 20:43:29.636052 1 util/log/file_sync_buffer.go:238 ⋮ [T1,config] binary: CockroachDB CCL v23.1.5 (x86_64-pc-linux-gnu, built 2023/07/01 01:33:00, go1.19.10)
I230822 20:43:29.636056 1 util/log/file_sync_buffer.go:238 ⋮ [T1,config] arguments: [‹/usr/local/bin/cockroach› ‹start› ‹redacted>]
I230822 20:43:29.636082 1 util/log/file_sync_buffer.go:238 ⋮ [T1,config] log format (utf8=✓): json
```

**Comment by abarganier** [comment]
@ricardocrdb can you provide some more details?

1. What is the log config for the cluster that the debug zip was taken from?
2. Which log file did this come from? Seems like `cockroach.log`, but just wanted to confirm. 

Additionally, if you could provide the debug zip in question that would be very helpful in understanding the situation.
