### ISSUE TITLE
dbconsole: cluster metrics became unavailable

### ISSUE THREAD

**Issue by srosenberg** [cockroachdb/cockroach#109532]
All of cluster metrics in the dbconsole became unavailable at some point. That point seems to correspond to an increase in the number of databases created. The screenshot below shows there was an error returning results from `system.eventlog` although that appears to be orthogonal, 

<img width="1904" alt="max_result_size_exceeded" src="https://github.com/cockroachdb/cockroach/assets/1616764/fcd9a0a3-8e09-411b-a70c-ec575dbf18c3">

After the initial triage by `#cluster-observability`, it appears the issue might lie with `/ts/query`'s backend.

Slack thread: https://cockroachlabs.slack.com/archives/C0159JK877C/p1692759171209549

Jira issue: CRDB-30966

**Comment by dhartunian** [comment]
From cluster settings on DB Console:
<img width="1810" alt="Screenshot 2023-08-25 at 18 22 49" src="https://github.com/cockroachdb/cockroach/assets/986307/a447c9f2-e6cb-4efb-a413-f09a05af142c">

someone disabled timeseries storage in the cluster settings.

Not 100% sure why the metrics stopped recording earlier, but perhaps the setting could have been written to multiple times or toggled on/off for a bit.
<img width="2168" alt="Screenshot 2023-08-25 at 18 23 10" src="https://github.com/cockroachdb/cockroach/assets/986307/9254535a-5fe5-493f-bd25-997a4e3ebfcd">

**Comment by srosenberg** [comment]
Thanks David! That's really odd... it wouldn't have been disabled intentionally afaict. I assume we don't have the audit trail to see how this change happened?

**Comment by srosenberg** [comment]
Ok, I found the culprit. Technically, it was me running `SQLancer`, so I'll blame `SQLancer` :) It disables TSDB unconditionally,

https://github.com/sqlancer/sqlancer/blob/f852f8cc08a98db34d40d20011b7c8fe47abf453/src/sqlancer/cockroachdb/CockroachDBProvider.java#L143
