### ISSUE TITLE
sql: v22.2.8: panic in processNamespaceResultRow

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#109502]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4420578675/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4420578675/?referrer=webhooks_plugin)

Panic Message:

```
panic.go:884: ×
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | github.com/cockroachdb/cockroach/pkg/kv.(*KeyValue).ValueInt
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:108
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.catalogQuery.processNamespaceResultRow
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_query.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.catalogQuery.query
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_query.go:71
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.catalogReader.ScanAll
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_reader.go:130
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.(*StoredCatalog).EnsureAllDescriptors
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/stored_catalog.go:159
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).GetAllDescriptors
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:436
  | github.com/cockroachdb/cockroach/pkg/sql.glob..func28
  | 	github.com/cockroachdb/cockroach/pkg/sql/crdb_internal.go:522
  | github.com/cockroachdb/cockroach/pkg/sql.(*virtualDefEntry).makeConstrainedRowsGenerator.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/virtual_schema.go:803
  | github.com/cockroachdb/cockroach/pkg/sql.setupGenerator.func3
  | 	github.com/cockroachdb/cockroach/pkg/sql/virtual_table.go:127
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:489
  | runtime.goexit
  | 	src/runtime/asm_arm64.s:1172
Wraps: (2) ×
Error types: (1) *withstack.withStack (2) *errors.errorString
-- report composition:
*errors.errorString
panic.go:884: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_arm64.s#L1171-L1173](src/runtime/asm_arm64.s#L1171-L1173)
[https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/util/stop/stopper.go#L488-L490](https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/util/stop/stopper.go#L488-L490)
[https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/virtual_table.go#L126-L128](https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/virtual_table.go#L126-L128)
[https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/virtual_schema.go#L802-L804](https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/virtual_schema.go#L802-L804)
[https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/crdb_internal.go#L521-L523](https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/crdb_internal.go#L521-L523)
[https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/catalog/descs/collection.go#L435-L437](https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/catalog/descs/collection.go#L435-L437)
[https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/catalog/internal/catkv/stored_catalog.go#L158-L160](https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/catalog/internal/catkv/stored_catalog.go#L158-L160)
[https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/catalog/internal/catkv/catalog_reader.go#L129-L131](https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/catalog/internal/catkv/catalog_reader.go#L129-L131)
[https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/catalog/internal/catkv/catalog_query.go#L70-L72](https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/catalog/internal/catkv/catalog_query.go#L70-L72)
[https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/catalog/internal/catkv/catalog_query.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/sql/catalog/internal/catkv/catalog_query.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/kv/db.go#L107-L109](https://github.com/cockroachdb/cockroach/blob/9a7c644e565b21d29db26a0a82524a00809d0a8c/pkg/kv/db.go#L107-L109)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
</details>

```
src/runtime/asm_arm64.s in runtime.goexit at line 1172
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 489
pkg/sql/virtual_table.go in pkg/sql.setupGenerator.func3 at line 127
pkg/sql/virtual_schema.go in pkg/sql.(*virtualDefEntry).makeConstrainedRowsGenerator.func1 at line 803
pkg/sql/crdb_internal.go in pkg/sql.glob..func28 at line 522
pkg/sql/catalog/descs/collection.go in pkg/sql/catalog/descs.(*Collection).GetAllDescriptors at line 436
pkg/sql/catalog/internal/catkv/stored_catalog.go in pkg/sql/catalog/internal/catkv.(*StoredCatalog).EnsureAllDescriptors at line 159
pkg/sql/catalog/internal/catkv/catalog_reader.go in pkg/sql/catalog/internal/catkv.catalogReader.ScanAll at line 130
pkg/sql/catalog/internal/catkv/catalog_query.go in pkg/sql/catalog/internal/catkv.catalogQuery.query at line 71
pkg/sql/catalog/internal/catkv/catalog_query.go in pkg/sql/catalog/internal/catkv.catalogQuery.processNamespaceResultRow at line 92
pkg/kv/db.go in pkg/kv.(*KeyValue).ValueInt at line 108
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
```

### Tags

| Tag | Value |
| --- | --- |
| Command | start-single-node |
| Environment | v22.2.8 |
| Go Version | go1.19.6 |
| Platform | darwin arm64 |
| Distribution | CCL |
| Cockroach Release | v22.2.8 |
| Cockroach SHA | 9a7c644e565b21d29db26a0a82524a00809d0a8c |
| # of CPUs | 10 |
| # of Goroutines | 359 |

Jira issue: CRDB-30957

**Comment by yuzefovich** [comment]
```
demo@127.0.0.1:26257/defaultdb> select crdb_internal.decode_plan_gist('AgGG////HwYAkiACAAADFAAGAgIBBQIGAg==');
                crdb_internal.decode_plan_gist
--------------------------------------------------------------
  • lookup join
  │ table: descriptor@primary
  │ equality: (table_id) = (id)
  │ equality cols are key
  │
  └── • filter
      │
      └── • virtual table
            table: @tables_database_name_idx (partial index)
            spans: 1+ spans
(10 rows)
```

**Comment by rafiss** [comment]
We should change the error so that it doesn't get redacted. Without that, it's hard to debug anything there.
