### ISSUE TITLE
Sentry: grant_revoke_system.go:204: no tables found
(1)
Wraps: (2) assertion failure
Wraps: (3) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*changeNonDescripto...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#109503]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4420698963/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4420698963/?referrer=webhooks_plugin)

Panic Message:

```
grant_revoke_system.go:204: no tables found
(1)
Wraps: (2) assertion failure
Wraps: (3) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*changeNonDescriptorBackedPrivilegesNode).makeSystemPrivilegeObject
  | 	github.com/cockroachdb/cockroach/pkg/sql/grant_revoke_system.go:204
  | github.com/cockroachdb/cockroach/pkg/sql.(*changeNonDescriptorBackedPrivilegesNode).startExec
  | 	github.com/cockroachdb/cockroach/pkg/sql/grant_revoke_system.go:51
  | github.com/cockroachdb/cockroach/pkg/sql.startExec.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan.go:518
  | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:112
  | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:297
  | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:79
  | github.com/cockroachdb/cockroach/pkg/sql.walkPlan
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:43
  | github.com/cockroachdb/cockroach/pkg/sql.startExec
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan.go:521
  | github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Start
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:147
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Columnarizer).Init
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/columnarizer.go:178
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).Init
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:90
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).init.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:247
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).init
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:246
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:291
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:320
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:695
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1611
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1334
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1541
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1177
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:687
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:129
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2382
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:128
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execPortal
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:218
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1998
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2000
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1846
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:828
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:728
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (4) no tables found
Error types: (1) *colexecerror.notInternalError (2) *assert.withAssertionFailure (3) *withstack.withStack (4) *errutil.leafError
-- report composition:
*errutil.leafError: no tables found
grant_revoke_system.go:204: *withstack.withStack (top exception)
*assert.withAssertionFailure
*colexecerror.notInternalError
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/pgwire/conn.go#L727-L729](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/pgwire/conn.go#L727-L729)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/conn_executor.go#L827-L829](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/conn_executor.go#L827-L829)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/conn_executor.go#L1845-L1847](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/conn_executor.go#L1845-L1847)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/conn_executor.go#L1999-L2001](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/conn_executor.go#L1999-L2001)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/conn_executor.go#L1997-L1999](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/conn_executor.go#L1997-L1999)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/conn_executor_exec.go#L217-L219](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/conn_executor_exec.go#L217-L219)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/conn_executor_exec.go#L127-L129](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/conn_executor_exec.go#L127-L129)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/conn_executor_exec.go#L2381-L2383](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/conn_executor_exec.go#L2381-L2383)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/conn_executor_exec.go#L128-L130](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/conn_executor_exec.go#L128-L130)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/conn_executor_exec.go#L686-L688](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/conn_executor_exec.go#L686-L688)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/conn_executor_exec.go#L1176-L1178](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/conn_executor_exec.go#L1176-L1178)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/conn_executor_exec.go#L1540-L1542](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/conn_executor_exec.go#L1540-L1542)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/distsql_running.go#L1333-L1335](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/distsql_running.go#L1333-L1335)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/distsql_running.go#L1610-L1612](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/distsql_running.go#L1610-L1612)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/distsql_running.go#L694-L696](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/distsql_running.go#L694-L696)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/colflow/vectorized_flow.go#L319-L321](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/colflow/vectorized_flow.go#L319-L321)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/colflow/flow_coordinator.go#L290-L292](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/colflow/flow_coordinator.go#L290-L292)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/colflow/flow_coordinator.go#L245-L247](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/colflow/flow_coordinator.go#L245-L247)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/colflow/flow_coordinator.go#L246-L248](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/colflow/flow_coordinator.go#L246-L248)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/colflow/stats.go#L89-L91](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/colflow/stats.go#L89-L91)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/colexec/columnarizer.go#L177-L179](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/colexec/columnarizer.go#L177-L179)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/plan_node_to_row_source.go#L146-L148](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/plan_node_to_row_source.go#L146-L148)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/plan.go#L520-L522](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/plan.go#L520-L522)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/walk.go#L42-L44](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/walk.go#L42-L44)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/walk.go#L78-L80](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/walk.go#L78-L80)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/walk.go#L296-L298](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/walk.go#L296-L298)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/walk.go#L111-L113](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/walk.go#L111-L113)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/plan.go#L517-L519](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/plan.go#L517-L519)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/grant_revoke_system.go#L50-L52](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/grant_revoke_system.go#L50-L52)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/grant_revoke_system.go#L203-L205](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/grant_revoke_system.go#L203-L205)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommandsAsync.func1 at line 728
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 828
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 1846
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 2000
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd.func2 at line 1998
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execPortal at line 218
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 128
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithProfiling at line 2382
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt.func1 at line 129
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 687
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchToExecutionEngine at line 1177
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithDistSQLEngine at line 1541
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRunAll at line 1334
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRun at line 1611
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).Run at line 695
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlow).Run at line 320
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).Run at line 291
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).init at line 246
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).init.func1 at line 247
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).Init at line 90
pkg/sql/colexec/columnarizer.go in pkg/sql/colexec.(*Columnarizer).Init at line 178
pkg/sql/plan_node_to_row_source.go in pkg/sql.(*planNodeToRowSource).Start at line 147
pkg/sql/plan.go in pkg/sql.startExec at line 521
pkg/sql/walk.go in pkg/sql.walkPlan at line 43
pkg/sql/walk.go in pkg/sql.(*planVisitor).visit at line 79
pkg/sql/walk.go in pkg/sql.(*planVisitor).visitInternal at line 297
pkg/sql/walk.go in pkg/sql.(*planVisitor).visitInternal.func1 at line 112
pkg/sql/plan.go in pkg/sql.startExec.func2 at line 518
pkg/sql/grant_revoke_system.go in pkg/sql.(*changeNonDescriptorBackedPrivilegesNode).startExec at line 51
pkg/sql/grant_revoke_system.go in pkg/sql.(*changeNonDescriptorBackedPrivilegesNode).makeSystemPrivilegeObject at line 204
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v22.2.0 |
| Go Version | go1.19.1 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v22.2.0 |
| Cockroach SHA | 77667a1b0101cd323090011f50cf910aaa933654 |
| # of CPUs | 8 |
| # of Goroutines | 401 |

Jira issue: CRDB-30958

**Comment by yuzefovich** [comment]
dup of #99233
