### ISSUE TITLE
server: the DataDistribution RPC API is not available to secondary tenants

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#109501]
**Is your feature request related to a problem? Please describe.**

when e.g. TestAdminAPIDataDistribution is pointed to a secondary tenant (based on #108762), it fails:
```
    storage_inspection_test.go:273: status: 501 Not Implemented, content-type: application/json, body: {
          "error": "method DataDistribution not implemented",
          "code": 12,
          "message": "method DataDistribution not implemented",
          "details": [
          ]
        }, error: <nil>
```

**Describe the solution you'd like**

The DataDistribution API should be available for secondary tenants (and reveal ranges that contain the tenant's keyspace only).

Epic CRDB-38968

Jira issue: CRDB-30956

**Comment by shubhamdhama** [comment]
This test should be fixed if we fix #97942 which has more context about this issue.
