### ISSUE TITLE
Sentry: txn_coord_sender.go:996: log.Fatal: transaction unexpectedly committed, ba: Put [/Table/119/7/×/×,/Min), EndTxn(commit) [/Table/119/8/×], [txn: 82cd0778]. txn: "sql txn" meta={id=82cd0778 k...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#109520]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4421471129/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4421471129/?referrer=webhooks_plugin)

Panic Message:

```
txn_coord_sender.go:996: log.Fatal: transaction unexpectedly committed, ba: Put [/Table/119/7/×/×,/Min), EndTxn(commit) [/Table/119/8/×], [txn: 82cd0778]. txn: "sql txn" meta={id=82cd0778 key=/Table/119/8/× pri=0.00506053 epo=0 ts=1692987645.425924729,1 min=1692987638.228744160,12 seq=2} lock=true stat=COMMITTED rts=1692987645.425924729,1 wto=false gul=1692987638.728744160,12 int=2 ifw=1: TransactionStatusError: already committed (REASON_TXN_COMMITTED)
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.sanityCheckErrWithTxn
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_coord_sender.go:996
  | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*TxnCoordSender).updateStateLocked
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_coord_sender.go:948
  | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*TxnCoordSender).Send
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_coord_sender.go:531
  | github.com/cockroachdb/cockroach/pkg/kv.(*DB).sendUsingSender
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:1001
  | github.com/cockroachdb/cockroach/pkg/kv.(*Txn).Send
  | 	github.com/cockroachdb/cockroach/pkg/kv/txn.go:1060
  | github.com/cockroachdb/cockroach/pkg/kv.sendAndFill
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:831
  | github.com/cockroachdb/cockroach/pkg/kv.(*Txn).Run
  | 	github.com/cockroachdb/cockroach/pkg/kv/txn.go:675
  | github.com/cockroachdb/cockroach/pkg/kv.(*Txn).CommitInBatch
  | 	github.com/cockroachdb/cockroach/pkg/kv/txn.go:723
  | github.com/cockroachdb/cockroach/pkg/sql.(*tableWriterBase).finalize
  | 	github.com/cockroachdb/cockroach/pkg/sql/tablewriter.go:230
  | github.com/cockroachdb/cockroach/pkg/sql.(*updateNode).BatchedNext
  | 	github.com/cockroachdb/cockroach/pkg/sql/update.go:201
  | github.com/cockroachdb/cockroach/pkg/sql.(*rowCountNode).startExec
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_batch.go:173
  | github.com/cockroachdb/cockroach/pkg/sql.startExec.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan.go:518
  | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:112
  | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:299
  | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:79
  | github.com/cockroachdb/cockroach/pkg/sql.walkPlan
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:43
  | github.com/cockroachdb/cockroach/pkg/sql.startExec
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan.go:521
  | github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Start
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:172
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*FlowCoordinator).Start.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:121
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*FlowCoordinator).Start
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:120
  | github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBaseNoHelper).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:736
  | github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:575
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:311
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:902
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1928
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll.func3
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1645
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1648
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2095
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1648
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:963
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:141
Wraps: (2) secondary error attachment
  | transaction unexpectedly committed, ba: Put [/Table/119/7/×/×,/Min), EndTxn(commit) [/Table/119/8/×], [txn: 82cd0778]. txn: "sql txn" meta={id=82cd0778 key=/Table/119/8/× pri=0.00506053 epo=0 ts=1692987645.425924729,1 min=1692987638.228744160,12 seq=2} lock=true stat=COMMITTED rts=1692987645.425924729,1 wto=false gul=1692987638.728744160,12 int=2 ifw=1: TransactionStatusError: already committed (REASON_TXN_COMMITTED)
  | (1) assertion failure
  | Wraps: (2) issue: https://github.com/cockroachdb/cockroach/issues/67765
  |   | detail: you have encountered a known bug in CockroachDB, please consider reporting on the Github issue or reach out via Support. This assertion can be disabled by setting the environment variable COCKROACH_DISABLE_COMMIT_SANITY_CHECK=true
  | Wraps: (3) attached stack trace
  |   -- stack trace:
  |   | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.sanityCheckErrWithTxn
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_coord_sender.go:983
  |   | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*TxnCoordSender).updateStateLocked
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_coord_sender.go:948
  |   | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*TxnCoordSender).Send
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_coord_sender.go:531
  |   | github.com/cockroachdb/cockroach/pkg/kv.(*DB).sendUsingSender
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:1001
  |   | github.com/cockroachdb/cockroach/pkg/kv.(*Txn).Send
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/txn.go:1060
  |   | github.com/cockroachdb/cockroach/pkg/kv.sendAndFill
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:831
  |   | github.com/cockroachdb/cockroach/pkg/kv.(*Txn).Run
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/txn.go:675
  |   | github.com/cockroachdb/cockroach/pkg/kv.(*Txn).CommitInBatch
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/txn.go:723
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*tableWriterBase).finalize
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/tablewriter.go:230
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*updateNode).BatchedNext
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/update.go:201
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*rowCountNode).startExec
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/plan_batch.go:173
  |   | github.com/cockroachdb/cockroach/pkg/sql.startExec.func2
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/plan.go:518
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal.func1
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:112
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:299
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:79
  |   | github.com/cockroachdb/cockroach/pkg/sql.walkPlan
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:43
  |   | github.com/cockroachdb/cockroach/pkg/sql...
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/sql/conn_executor_exec.go#L140-L142](https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/sql/conn_executor_exec.go#L140-L142)
[https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/sql/conn_executor_exec.go#L962-L964](https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/sql/conn_executor_exec.go#L962-L964)
[https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/sql/conn_executor_exec.go#L1647-L1649](https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/sql/conn_executor_exec.go#L1647-L1649)
[https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/sql/conn_executor_exec.go#L2094-L2096](https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/sql/conn_executor_exec.go#L2094-L2096)
[https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/sql/distsql_running.go#L1647-L1649](https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/sql/distsql_running.go#L1647-L1649)
[https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/sql/distsql_running.go#L1644-L1646](https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/sql/distsql_running.go#L1644-L1646)
[https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/sql/distsql_running.go#L1927-L1929](https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/sql/distsql_running.go#L1927-L1929)
[https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/sql/distsql_running.go#L901-L903](https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/sql/distsql_running.go#L901-L903)
[https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/sql/colflow/vectorized_flow.go#L310-L312](https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/sql/colflow/vectorized_flow.go#L310-L312)
[https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/sql/flowinfra/flow.go#L574-L576](https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/sql/flowinfra/flow.go#L574-L576)
[https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/sql/execinfra/processorsbase.go#L735-L737](https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/sql/execinfra/processorsbase.go#L735-L737)
[https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/sql/colflow/flow_coordinator.go#L119-L121](https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/sql/colflow/flow_coordinator.go#L119-L121)
[https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/sql/colflow/flow_coordinator.go#L120-L122](https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/sql/colflow/flow_coordinator.go#L120-L122)
[https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/sql/plan_node_to_row_source.go#L171-L173](https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/sql/plan_node_to_row_source.go#L171-L173)
[https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/sql/plan.go#L520-L522](https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/sql/plan.go#L520-L522)
[https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/sql/walk.go#L42-L44](https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/sql/walk.go#L42-L44)
[https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/sql/walk.go#L78-L80](https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/sql/walk.go#L78-L80)
[https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/sql/walk.go#L298-L300](https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/sql/walk.go#L298-L300)
[https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/sql/walk.go#L111-L113](https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/sql/walk.go#L111-L113)
[https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/sql/plan.go#L517-L519](https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/sql/plan.go#L517-L519)
[https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/sql/plan_batch.go#L172-L174](https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/sql/plan_batch.go#L172-L174)
[https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/sql/update.go#L200-L202](https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/sql/update.go#L200-L202)
[https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/sql/tablewriter.go#L229-L231](https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/sql/tablewriter.go#L229-L231)
[https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/kv/txn.go#L722-L724](https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/kv/txn.go#L722-L724)
[https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/kv/txn.go#L674-L676](https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/kv/txn.go#L674-L676)
[https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/kv/db.go#L830-L832](https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/kv/db.go#L830-L832)
[https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/kv/txn.go#L1059-L1061](https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/kv/txn.go#L1059-L1061)
[https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/kv/db.go#L1000-L1002](https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/kv/db.go#L1000-L1002)
[https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L530-L532](https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L530-L532)
[https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L947-L949](https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L947-L949)
[https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L995-L997](https://github.com/cockroachdb/cockroach/blob/00f65ea04077b4256b4a351fd2703b81c7caed1e/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L995-L997)
</details>

```
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt.func1 at line 141
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 963
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchToExecutionEngine at line 1648
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithDistSQLEngine at line 2095
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRunAll at line 1648
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRunAll.func3 at line 1645
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRun at line 1928
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).Run at line 902
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlow).Run at line 311
pkg/sql/flowinfra/flow.go in pkg/sql/flowinfra.(*FlowBase).Run at line 575
pkg/sql/execinfra/processorsbase.go in pkg/sql/execinfra.(*ProcessorBaseNoHelper).Run at line 736
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*FlowCoordinator).Start at line 120
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*FlowCoordinator).Start.func1 at line 121
pkg/sql/plan_node_to_row_source.go in pkg/sql.(*planNodeToRowSource).Start at line 172
pkg/sql/plan.go in pkg/sql.startExec at line 521
pkg/sql/walk.go in pkg/sql.walkPlan at line 43
pkg/sql/walk.go in pkg/sql.(*planVisitor).visit at line 79
pkg/sql/walk.go in pkg/sql.(*planVisitor).visitInternal at line 299
pkg/sql/walk.go in pkg/sql.(*planVisitor).visitInternal.func1 at line 112
pkg/sql/plan.go in pkg/sql.startExec.func2 at line 518
pkg/sql/plan_batch.go in pkg/sql.(*rowCountNode).startExec at line 173
pkg/sql/update.go in pkg/sql.(*updateNode).BatchedNext at line 201
pkg/sql/tablewriter.go in pkg/sql.(*tableWriterBase).finalize at line 230
pkg/kv/txn.go in pkg/kv.(*Txn).CommitInBatch at line 723
pkg/kv/txn.go in pkg/kv.(*Txn).Run at line 675
pkg/kv/db.go in pkg/kv.sendAndFill at line 831
pkg/kv/txn.go in pkg/kv.(*Txn).Send at line 1060
pkg/kv/db.go in pkg/kv.(*DB).sendUsingSender at line 1001
pkg/kv/kvclient/kvcoord/txn_coord_sender.go in pkg/kv/kvclient/kvcoord.(*TxnCoordSender).Send at line 531
pkg/kv/kvclient/kvcoord/txn_coord_sender.go in pkg/kv/kvclient/kvcoord.(*TxnCoordSender).updateStateLocked at line 948
pkg/kv/kvclient/kvcoord/txn_coord_sender.go in pkg/kv/kvclient/kvcoord.sanityCheckErrWithTxn at line 996
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v23.1.1 |
| Go Version | go1.19.4 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.1 |
| Cockroach SHA | 00f65ea04077b4256b4a351fd2703b81c7caed1e |
| # of CPUs | 32 |
| # of Goroutines | 3359 |

Jira issue: CRDB-30963

**Comment by yuzefovich** [comment]
dup of #67765
