### ISSUE TITLE
sql: difference function returns text instead of integer

### ISSUE THREAD

**Issue by giangpham712** [cockroachdb/cockroach#109666]
**Describe the problem**

Given a table as follows

```
CREATE TABLE public."FuzzyStringMatchTestEntities" (
  "Id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "Text" STRING NULL,
  CONSTRAINT "PK_FuzzyStringMatchTestEntities" PRIMARY KEY ("Id" ASC)
)
```

The following query

```
SELECT difference(f."Text", 'target')
 FROM "FuzzyStringMatchTestEntities" AS f;
```

returns result

```
  difference
--------------
  0
  0
  0
  0
  0
  0
  0
  0
  0
```

but the values are `text` instead of integer, while the function `levenshtein` returns integer

**Additional context**
What was the impact?

This affects efcore.pg tests

@fqazi 

Jira issue: CRDB-31041

**Comment by fqazi** [comment]
@giangpham712 That definitely does not match the documentation and should be an easy fix.
