### ISSUE TITLE
server: TestStatusGetFiles failed

### ISSUE THREAD

**Issue by jayshrivastava** [cockroachdb/cockroach#109698]
https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/11544101?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

Jira issue: CRDB-31058

**Comment by ericharmeling** [comment]
I'm not able to reproduce this locally, but it looks like `TestStatusGetFiles/goroutines` doesn't account for the scenario when goroutine count is above `server.goroutine_dump.num_goroutines_threshold` (and then has an additional dump file in the `goroutine_dump` directory). Going to open a fix shortly.

**Comment by wenyihu6** [comment]
Flaked on unrelated PR https://teamcity.cockroachdb.com/viewLog.html?buildId=11561727&buildTypeId=Cockroach_BazelEssentialCi
