### ISSUE TITLE
kv: latching changes to support replicated shared locks

### ISSUE THREAD

**Issue by arulajmani** [cockroachdb/cockroach#109668]
**Describe the problem**

When acquiring replicated shared locks, 2 requests on the same key and from the same transaction need to be isolated from one another. That requires the latching semantics for shared locks, introduced in https://github.com/cockroachdb/cockroach/pull/109633, to change slightly. 

As described in the shared locks RFC, in addition to a read latch with timestamp `hlc.MaxTimestamp`, we'll also want to acquire a non-MVCC write latch on a transaction specific local key. The RFC proposes something like `/Local/LockTable/<key>/<txnid>`, which would work for `GetRequests`.

For `{, Rev}ScanRequests` we might need something different, as two locking `{,Rev}ScanRequests` with different start/end keys might have overlapping keys that they're both trying to lock. A non-MVCC write latch on something like `/Local/LockTable/SharedLock/<txnid>` might work, however, it means that there can only ever be a single shared locking request per transaction per range that's evaluating. This is likely sufficient for now, given how we construct batches in the `DistSender`. 

cc @nvanbenschoten 

Jira issue: CRDB-31042

Epic CRDB-26544

**Comment by nvanbenschoten** [comment]
> For {, Rev}ScanRequests we might need something different, as two locking {,Rev}ScanRequests with different start/end keys might have overlapping keys that they're both trying to lock.

Great point. A non-mvcc write latch on a synthetic key like `/Local/LockTable/SharedLock/<txnid>` makes sense to me.
