### ISSUE TITLE
storage: add replicated locks to storage metamorphic testing

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#109650]
As part of https://github.com/cockroachdb/cockroach/issues/100193, we should add replicated locks to the metamorphic testing in `pkg/storage/metamorphic`. In practice, this would mean exercising the two new functions added in https://github.com/cockroachdb/cockroach/pull/110323.

Jira issue: CRDB-31034

**Comment by nicktrav** [comment]
Note for @bananabrick - might also be worth taking a look at #96290, and address while we're in here.
