### ISSUE TITLE
storage: mechanism for more aggressive rebalancing after splits

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#10967]
Restore will pre-split all the ranges that it's about to import, then use DistSender to split up the work to the leaseholders. This obviously works best if the replicas and leaseholders are spread out across the cluster after they split. Any ideas how we could accomplish that?

**Comment by bdarnell** [comment]
A manual split indicates an intent to grow, so maybe the rebalancer should treat ranges that were recently manually split as larger than they are (or, when we have load-based rebalancing, we could give them an artificially high load score instead of artificially increasing their size).

**Comment by danhhz** [comment]
@petermattis did you do any additional pondering on this?

@bdarnell relatedly, we don't want to send out the requests until the leaseholders are rebalanced. is there some better way to wait for that than looping and examining the range descriptors until some heuristic is met?

**Comment by petermattis** [comment]
No, I haven't done any additional pondering on this. The rebalancer will already balance the newly split ranges even though they are empty. And that rebalancing will happen quickly as we add both the left and right hand sides of the split to the `replicateQueue` after the split completes. The problem to solve is adding a mechanism to wait for that rebalancing to occur. And ditto for the lease rebalancing. Some sort of `AdminWaitForRebalance`. But I'm not sure what the semantics would be.

**Comment by petermattis** [comment]
@danhhz, @RaduBerinde Does https://github.com/cockroachdb/cockroach/pull/14146 cover this issue sufficiently?

**Comment by RaduBerinde** [comment]
Seems to me that the SCATTER functionality would cover it..

**Comment by danhhz** [comment]
Yeah, SCATTER would do it. @RaduBerinde I'm going to assign this to you to close when you implement SCATTER. Or if you already have this tracked somewhere else, feel free to close as a dup

**Comment by dianasaur323** [comment]
@RaduBerinde looks like you just merged a basic implementation of SCATTER recently. I'm going to close out, but feel free to re-open if you would like.
