### ISSUE TITLE
Populate pg_class and pg_attribute with composite types

### ISSUE THREAD

**Issue by lukaseder** [cockroachdb/cockroach#109675]
**Is your feature request related to a problem? Please describe.**

When creating a composite type like this:

```sql
create type u as (i int, j int);
```

I expect it to appear in `pg_class` with `relkind = 'c'`, as well as its attributes in `pg_attribute`. Currently, both tables from the `pg_catalog` don't list the composite type. It is only listed in `pg_type`

**Describe the solution you'd like**

Implement PostgreSQL compatibility in order to allow for reverse engineering user defined types.

**Describe alternatives you've considered**

**Additional context**

Bonus points if `INFORMATION_SCHEMA.USER_DEFINED_TYPES` and `INFORMATION_SCHEMA.ATTRIBUTES` are also populated:

- https://github.com/cockroachdb/cockroach/issues/109603

But the `pg_catalog` tables are more important, I think.

Jira issue: CRDB-31048

**Comment by rafiss** [comment]
Thanks for the report! Yes, it was an oversight that composite types were not included here. Enum types do show up correctly though.
