### ISSUE TITLE
sql: panic due to incomplete name resolution in VALUES

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#10960]
https://teamcity.cockroachdb.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=55431#_focus=4128

````
panic: ( VALUES ( @ 485 ) ): indexed var must be bound to a container before type resolution
````

**Comment by knz** [comment]
Found with RSG.

**Comment by tamird** [comment]
Am I missing it, or was the query not logged here?

**Comment by knz** [comment]
the query was logged: it's just `VALUES ( @ 485 )`
