### ISSUE TITLE
INSERT ... ON CONFLICT does not allow selection of partial index as arbiter index

### ISSUE THREAD

**Issue by msirek** [cockroachdb/cockroach#109681]
**Describe the problem**
Our [syntax](https://www.cockroachlabs.com/docs/v23.1/sql-grammar#on_conflict) for ON CONFLICT supports:
`( name_list ) opt_where_clause`, but this optional WHERE clause following the name list has no effect.
In Postgres, it affects whether we choose a partial index as an arbiter index, for example:
```sql
CREATE TABLE a (a INT PRIMARY KEY, b INT);
CREATE UNIQUE INDEX ON a(a) WHERE b<>2;

INSERT INTO a(a,b) values(1, 1);
INSERT INTO a(a,b) values(2, 2);
-- With the WHERE clause
EXPLAIN INSERT INTO a(a,b) VALUES(2,3) ON CONFLICT(a) WHERE b<>2 DO UPDATE SET b=3;
                   QUERY PLAN
------------------------------------------------
 Insert on a  (cost=0.00..0.01 rows=0 width=0)
   Conflict Resolution: UPDATE
   Conflict Arbiter Indexes: a_pkey, a_a_idx
   ->  Result  (cost=0.00..0.01 rows=1 width=8)

-- Without the WHERE clause
EXPLAIN INSERT INTO a(a,b) VALUES(2,3) ON CONFLICT(a) DO UPDATE SET b=3;
                   QUERY PLAN
------------------------------------------------
 Insert on a  (cost=0.00..0.01 rows=0 width=0)
   Conflict Resolution: UPDATE
   Conflict Arbiter Indexes: a_pkey
   ->  Result  (cost=0.00..0.01 rows=1 width=8)
```
But in CRDB, using the same setup, the WHERE clause doesn't cause index `a_a_idx` to be used:
```sql
EXPLAIN INSERT INTO a(a,b) VALUES(2,3) ON CONFLICT(a) WHERE b<>2 DO UPDATE SET b=3;
   • upsert
  │ into: a(a, b)
  │ auto commit
  │ arbiter indexes: a_pkey
  │
  └── • render
      │
      └── • render
          │
          └── • cross join (left outer)
              │
              ├── • values
              │     size: 2 columns, 1 row
              │
              └── • scan
                    missing stats
                    table: a@a_pkey
                    spans: [/2 - /2]
                    locking strength: for update
```
The docs should be updated to indicate this WHERE clause has no effect.
Also, from support issue https://github.com/cockroachlabs/support/issues/2565 :
> The documentation seems to misleading as https://www.cockroachlabs.com/docs/v23.1/sql-grammar#on_conflict shows that WHERE clause is allowed while https://www.cockroachlabs.com/docs/v23.1/insert#on-conflict-clause does not. Notice there is no "where" clause on the last webpage. Why is this the case?

Jira issue: CRDB-31053

**Comment by mgartner** [comment]
Using the partial index as an arbiter in the example is unnecessary. We only need to use the primary key as an arbiter because it maintains the uniqueness of `a` across all rows, not just rows where `b <> 2`. This is described in more detail here: https://github.com/cockroachdb/cockroach/blob/fad7ac8303582228b010375c60820d4a6a798570/pkg/sql/opt/optbuilder/mutation_builder_arbiter.go#L128-L152

If a partial unique index is the only possible arbiter, it will be selected. For example:

```sql
CREATE TABLE t (
  a INT PRIMARY KEY,
  b INT,
  UNIQUE INDEX (b) WHERE b <> 0
);

EXPLAIN INSERT INTO T VALUES (1, 2)
ON CONFLICT (b) WHERE b <> 0 DO UPDATE SET b = 3;
--                          info
-- ------------------------------------------------------
--   distribution: local
--   vectorized: true
-- 
--   • upsert
--   │ into: t(a, b)
--   │ auto commit
--   │ arbiter indexes: t_b_key
--   │
--   └── • render
--       │
--       └── • render
--           │
--           └── • cross join (right outer)
--               │
--               ├── • scan
--               │     missing stats
--               │     table: t@t_b_key (partial index)
--               │     spans: [/2 - /2]
--               │
--               └── • values
--                     size: 2 columns, 1 row
```

Not sure if there's a good way to explain this at the docs level, but the gist of it is that the optimizer will only use the arbiters necessary for correctness.

**Comment by mgartner** [comment]
Important points from the [Postgres docs](https://www.postgresql.org/docs/current/sql-insert.html#SQL-ON-CONFLICT) that explain why the non-partial arbiter can always be selected when given a `WHERE` clause:

> `conflict_target` can perform unique index inference. When performing inference, it consists of one or more index_column_name columns and/or index_expression expressions, and an optional index_predicate. All table_name unique indexes that, without regard to order, contain exactly the conflict_target-specified columns/expressions are inferred (chosen) as arbiter indexes. If an index_predicate is specified, it must, as a further requirement for inference, satisfy arbiter indexes. **Note that this means a non-partial unique index (a unique index without a predicate) will be inferred (and thus used by `ON CONFLICT`) if such an index satisfying every other criteria is available. If an attempt at inference is unsuccessful, an error is raised.**

> `index_predicate`
>
> Used to allow inference of partial unique indexes. **Any indexes that satisfy the predicate (which need not actually be partial indexes) can be inferred. Follows `CREATE INDEX` format. `SELECT` privilege on any column appearing within index_predicate is required.**

**Comment by msirek** [comment]
Doc JIRA for this issue:
https://cockroachlabs.atlassian.net/browse/DOC-8696

**Comment by msirek** [comment]
Closing this issue as it will be handled via the DOC JIRA
