### ISSUE TITLE
stability: goroutine spike after restarting down node

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#10968]
On `blue`, when a node is killed and kept down for a few minutes, upon restart it sees a spike in goroutines:

<img width="935" alt="screen shot 2016-11-22 at 3 27 19 pm" src="https://cloud.githubusercontent.com/assets/6201335/20540776/7adf4d9c-b0c8-11e6-9a0b-25d265a2dc67.png">

All 3 spikes below correspond to a node being restarted. The bulk of the goroutines have a single stack trace:

```
6644: select [0~1 minutes] [Created by grpc.(*Server).serveStreams.func1 @ server.go:423]
    storage             replica.go:921               (*Replica).redirectOnOrAcquireLease(*, #84539, *, *)
    storage             replica.go:1808              (*Replica).tryAddWriteCmd(*, #84539, *, *, *, #131, *, *, 0, *, ...)
    storage             replica.go:1706              (*Replica).addWriteCmd(*, #84539, *, *, *, #131, *, *, 0, *, ...)
    storage             replica.go:1173              (*Replica).Send(*, #84539, *, *, *, #131, *, *, 0, *, ...)
    storage             store.go:2387                (*Store).Send(#1222, #84539, *, *, *, #131, *, *, 0, *, ...)
    storage             stores.go:187                (*Stores).Send(#305, #84539, *, 0, 0, #131, *, *, 0, *, ...)
    server              node.go:819                  (*Node).batchInternal.func1(0, 0)
    stop                stopper.go:245               (*Stopper).RunTaskWithErr(#550, *, 0, 0)
    server              node.go:830                  (*Node).batchInternal(#407, #84539, *, *, *, *, *)
    server              node.go:850                  (*Node).Batch(#407, #84539, *, *, *, *, *)
    roachpb             api.pb.go:1522               _Internal_Batch_Handler(#39, #407, #84539, *, *, 0, 0, 0, *, *)
    grpc                server.go:611                (*Server).processUnaryRPC(#676, #97, *, *, #753, #65, 0, 0, 0)
    grpc                server.go:769                (*Server).handleStream(#676, #97, *, *, 0)
    grpc                server.go:422                (*Server).serveStreams.func1.1(*, #676, #97, *, *)
```

This count is somewhat surprising because the local `block_writer` will only send 64 concurrent requests, so other nodes must be directing traffic at this newly restarted node. I instrumented the binary at some point and could definitively see that the requests were coming from remote notes. In #10427 I experiment with increasing `kv.defaultSendNextTimeout` without noticeable improvement, but perhaps it is worth trying that again. Another question is why these goroutines are blocked for so long. Aren't the RPCs cancelled eventually?

**Comment by petermattis** [comment]
When we call `Transport.SendNext` we fire off an RPC but I don't see where we ever cancel that RPC. I think `DistSender.sendRPC` needs to create a context using `context.WithCancel` and cancel the context tree when it returns.

**Comment by petermattis** [comment]
Yep, that seems to fix the problem.

**Comment by tamird** [comment]
Nice!
