### ISSUE TITLE
storage: TestReplicateQueueDownReplicate is slow

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#10964]
#10624 replaced `TestStoreRangeDownReplicate` with `TestReplicateQueueDownReplicate`; the former was more aggressive in forcing the scanner to run, but the latter does not do this. The result is that the new is 5x slower than the old.

Perhaps the solution is as simple as restoring this line: https://github.com/cockroachdb/cockroach/pull/10624/files#diff-b1bd51088f60beeacafe950f5bc700f8L1216.

**Comment by bdarnell** [comment]
This test is no longer unreasonably slow.
