### ISSUE TITLE
stability: investigate query dip after 10 min node outage

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#10972]
A 6min chaos node outage on `blue` caused an dip in query performance after the node restarted:

<img width="935" alt="screen shot 2016-11-22 at 9 40 58 pm" src="https://cloud.githubusercontent.com/assets/6201335/20549677/953e05aa-b0fc-11e6-8d1b-ca837c6973de.png">

The node restarted at 22:47:? which corresponds with when the initial dip in performance. Performance then recovered and dipped again. The queue metrics show:

<img width="933" alt="screen shot 2016-11-22 at 9 41 37 pm" src="https://cloud.githubusercontent.com/assets/6201335/20549709/c989bf48-b0fc-11e6-88c1-73d18b5dcfbb.png">

The initial bump in replicate activity after the node had been down for 5min is expected. But what is that second bump that starts at 22:50. The down node has been up for 2+ min at that point. Per node metrics show the replica GC queue activity was all on the down node which is to be expected.

The down node shows the following replicate queue activity:

<img width="937" alt="screen shot 2016-11-22 at 9 47 06 pm" src="https://cloud.githubusercontent.com/assets/6201335/20549763/49c0e772-b0fd-11e6-8e11-25c00313e62a.png">

So it was queueing up replicas for processing but never actually spending any time processing them. Perhaps it wasn't able to acquire the lease.

**Comment by petermattis** [comment]
A 10min chaos event on `blue` caused a dip in performance both while the node was dead and then while it was recovering:

<img width="933" alt="screen shot 2017-04-05 at 3 12 50 pm" src="https://cloud.githubusercontent.com/assets/6201335/24722928/868a94f8-1a13-11e7-86ac-a807b4990e6c.png">

Initially, recovery looked good with the under-replicated ranges dropping to 0 around 18:43. But then additional badness started happening at 18:50.

<img width="934" alt="screen shot 2017-04-05 at 3 13 17 pm" src="https://cloud.githubusercontent.com/assets/6201335/24722941/8cf6039a-1a13-11e7-8fdf-6d303668c55a.png">

<img width="932" alt="screen shot 2017-04-05 at 3 13 25 pm" src="https://cloud.githubusercontent.com/assets/6201335/24722960/9c7c4cb6-1a13-11e7-92dd-3c0107c80680.png">

We can also see the badness in the node liveness graph. The resuscitated node started failing node liveness heartbeats at 18:50 and then had a number of other blips before eventually recovering for good.

<img width="936" alt="screen shot 2017-04-05 at 3 14 32 pm" src="https://cloud.githubusercontent.com/assets/6201335/24723005/cc46e08c-1a13-11e7-8c22-e37ad099849d.png">

The replica leaseholders graph showed that the recovering node initially started getting leases, then shed them all rapidly when the liveness heartbeats failed.

<img width="933" alt="screen shot 2017-04-05 at 3 13 03 pm" src="https://cloud.githubusercontent.com/assets/6201335/24723046/ed4cca4e-1a13-11e7-89ae-9211c390ab54.png">

Still poking around the graphs to see if anything else jumps out.

**Comment by petermattis** [comment]
Looks like there is some sort of RPC problem when the node liveness failures occur. During another chaos event on `blue`, I see the recovering node is doing fine and then boom, various slow request errors along with:

```
I170406 15:40:14.301949 422847 vendor/google.golang.org/grpc/server.go:752  grpc: Server.processUnaryRPC failed to write status: stream error: code = DeadlineExceeded desc = "context deadline exceeded"
```

I wonder of the stream and connection window size settings are proving problematic.

**Comment by andreimatei** [comment]
I think they are. The context deadline exceeded error is likely just our
heartbeats not making it across.
I'm fixing that in:
https://reviewable.io/reviews/cockroachdb/cockroach/14424#-

The next thing I was going to do is make the conn win size a multiple of
the per stream one, or in fact get rid of the per-connection window
altogether if I can convince Ben.

**Comment by petermattis** [comment]
> The next thing I was going to do is make the conn win size a multiple of
the per stream one, or in fact get rid of the per-connection window
altogether if I can convince Ben.

How were you going to do that?

**Comment by andreimatei** [comment]
Just like you've done it... Change the constants in grpc.

**Comment by petermattis** [comment]
Notice in the Raft Log graph above how the "raft log behind" metric initially shrinks rapidly when the dead node comes back, then has a period of flatness before another spike. I think this is yet more indication of RPC problems.

**Comment by petermattis** [comment]
> Just like you've done it... Change the constants in grpc.

I tried setting the connection window size to 8MB. It didn't help.

**Comment by petermattis** [comment]
I still haven't tracked down where the RPC problem is coming from. I'm experimenting with rate limiting the bandwidth we use for sending snapshots. Initial testing with a limit of 2 MB/sec shows this to significantly less the performance impact of the rebalance traffic when a node is declared dead.

**Comment by petermattis** [comment]
Note to self: my experiment uses a single bandwidth limit for both preemptive and Raft snapshots, but we probably want to allow Raft snapshots to be given more bandwidth.

**Comment by petermattis** [comment]
Here are graphs from a 10 min chaos event with experimental code which limits preemptive snapshots to 2 MB/sec and Raft snapshots to 4 MB/sec:

<img width="932" alt="screen shot 2017-04-06 at 11 07 28 pm" src="https://cloud.githubusercontent.com/assets/6201335/24784040/f2ce6986-1b1d-11e7-9692-a5fe9c5a98a7.png">

<img width="931" alt="screen shot 2017-04-06 at 11 07 36 pm" src="https://cloud.githubusercontent.com/assets/6201335/24784041/f4fb2b54-1b1d-11e7-8f5c-1d53b9072025.png">

<img width="932" alt="screen shot 2017-04-06 at 11 07 47 pm" src="https://cloud.githubusercontent.com/assets/6201335/24784042/f702b598-1b1d-11e7-8d39-8556a86ffc24.png">

The throughput impact of the node outage was significantly reduced and the node liveness failures disappeared which seems to indicate they were related to either overwhelming the gRPC connection or some bug in gRPC. I'm going to dig into this more tomorrow to try and better understand where the node liveness failures were coming from.
