### ISSUE TITLE
spanconfig: Liveness range could be split unintentionally

### ISSUE THREAD

**Issue by aliher1911** [cockroachdb/cockroach#109887]
Changes to remove protected timestamps from system ranges introduced a bug where liveness range could be split by a split queue based on zone configs.

Discovered in backports where splitting liveness is hard no and causes panic:
https://github.com/cockroachdb/cockroach/issues/109871

Other places in code doesn't expect liveness to be a single range and would fail in unexpected ways.

Jira issue: CRDB-31139

**Comment by arulajmani** [comment]
This is quite possibly https://github.com/cockroachdb/cockroach/issues/104195

**Comment by aliher1911** [comment]
See Arul's comment above.
