### ISSUE TITLE
Sentry: panic.go:884: panic: ×
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | github.com/cockroachdb/pebble/internal/cache.(*refcnt).acquire
 ...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#109984]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4450791859/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4450791859/?referrer=webhooks_plugin)

Panic Message:

```
panic.go:884: panic: ×
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | github.com/cockroachdb/pebble/internal/cache.(*refcnt).acquire
  | 	github.com/cockroachdb/pebble/internal/cache/external/com_github_cockroachdb_pebble/internal/cache/refcnt_normal.go:32
  | github.com/cockroachdb/pebble/internal/cache.(*Value).acquire
  | 	github.com/cockroachdb/pebble/internal/cache/external/com_github_cockroachdb_pebble/internal/cache/value.go:39
  | github.com/cockroachdb/pebble/internal/cache.(*entry).acquireValue
  | 	github.com/cockroachdb/pebble/internal/cache/external/com_github_cockroachdb_pebble/internal/cache/entry.go:152
  | github.com/cockroachdb/pebble/internal/cache.(*shard).Get
  | 	github.com/cockroachdb/pebble/internal/cache/external/com_github_cockroachdb_pebble/internal/cache/clockpro.go:120
  | github.com/cockroachdb/pebble/internal/cache.(*Cache).Get
  | 	github.com/cockroachdb/pebble/internal/cache/external/com_github_cockroachdb_pebble/internal/cache/clockpro.go:742
  | github.com/cockroachdb/pebble/sstable.(*Reader).readBlock
  | 	github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader.go:2767
  | github.com/cockroachdb/pebble/sstable.(*singleLevelIterator).readBlockWithStats
  | 	github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader.go:583
  | github.com/cockroachdb/pebble/sstable.(*singleLevelIterator).loadBlock
  | 	github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader.go:498
  | github.com/cockroachdb/pebble/sstable.(*singleLevelIterator).skipForward
  | 	github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader.go:1167
  | github.com/cockroachdb/pebble/sstable.(*singleLevelIterator).Next
  | 	github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader.go:1133
  | github.com/cockroachdb/pebble.(*levelIter).Next
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/level_iter.go:806
  | github.com/cockroachdb/pebble.(*mergingIter).nextEntry
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go:555
  | github.com/cockroachdb/pebble.(*mergingIter).Next
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go:1107
  | github.com/cockroachdb/pebble.(*lazyCombinedIter).Next
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/range_keys.go:620
  | github.com/cockroachdb/pebble.(*Iterator).nextUserKey
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/iterator.go:636
  | github.com/cockroachdb/pebble.(*Iterator).findNextEntry
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/iterator.go:507
  | github.com/cockroachdb/pebble.(*Iterator).NextWithLimit
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/iterator.go:1597
  | github.com/cockroachdb/pebble.(*Iterator).Next
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/iterator.go:1490
  | github.com/cockroachdb/cockroach/pkg/storage.(*pebbleIterator).Next
  | 	github.com/cockroachdb/cockroach/pkg/storage/pebble_iterator.go:426
  | github.com/cockroachdb/cockroach/pkg/storage.(*intentInterleavingIter).Next
  | 	github.com/cockroachdb/cockroach/pkg/storage/intent_interleaving_iter.go:819
  | github.com/cockroachdb/cockroach/pkg/storage.computeStatsForIterWithVisitors
  | 	github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:5524
  | github.com/cockroachdb/cockroach/pkg/storage.ComputeStatsWithVisitors
  | 	github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:5476
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/rditer.ComputeStatsForRangeWithVisitors
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/rditer/stats.go:38
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).sha512
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_consistency.go:700
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).computeChecksumPostApply.func2.1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_consistency.go:829
  | github.com/cockroachdb/cockroach/pkg/util/contextutil.RunWithTimeout
  | 	github.com/cockroachdb/cockroach/pkg/util/contextutil/context.go:91
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).computeChecksumPostApply.func2
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_consistency.go:821
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:489
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (2) panic: ×
Error types: (1) *withstack.withStack (2) *errutil.leafError
-- report composition:
*errutil.leafError: panic: ×
panic.go:884: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/util/stop/stopper.go#L488-L490](https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/util/stop/stopper.go#L488-L490)
[https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/kv/kvserver/pkg/kv/kvserver/replica_consistency.go#L820-L822](https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/kv/kvserver/pkg/kv/kvserver/replica_consistency.go#L820-L822)
[https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/util/contextutil/context.go#L90-L92](https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/util/contextutil/context.go#L90-L92)
[https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/kv/kvserver/pkg/kv/kvserver/replica_consistency.go#L828-L830](https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/kv/kvserver/pkg/kv/kvserver/replica_consistency.go#L828-L830)
[https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/kv/kvserver/pkg/kv/kvserver/replica_consistency.go#L699-L701](https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/kv/kvserver/pkg/kv/kvserver/replica_consistency.go#L699-L701)
[https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/kv/kvserver/rditer/stats.go#L37-L39](https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/kv/kvserver/rditer/stats.go#L37-L39)
[https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/storage/mvcc.go#L5475-L5477](https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/storage/mvcc.go#L5475-L5477)
[https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/storage/mvcc.go#L5523-L5525](https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/storage/mvcc.go#L5523-L5525)
[https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/storage/intent_interleaving_iter.go#L818-L820](https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/storage/intent_interleaving_iter.go#L818-L820)
[https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/storage/pebble_iterator.go#L425-L427](https://github.com/cockroachdb/cockroach/blob/07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1/pkg/storage/pebble_iterator.go#L425-L427)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/iterator.go#L1489-L1491](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/iterator.go#L1489-L1491)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/iterator.go#L1596-L1598](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/iterator.go#L1596-L1598)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/iterator.go#L506-L508](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/iterator.go#L506-L508)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/iterator.go#L635-L637](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/iterator.go#L635-L637)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/range_keys.go#L619-L621](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/range_keys.go#L619-L621)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go#L1106-L1108](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go#L1106-L1108)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go#L554-L556](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go#L554-L556)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/level_iter.go#L805-L807](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/level_iter.go#L805-L807)
[github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader.go#L1132-L1134](github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader.go#L1132-L1134)
[github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader.go#L1166-L1168](github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader.go#L1166-L1168)
[github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader.go#L497-L499](github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader.go#L497-L499)
[github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader.go#L582-L584](github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader.go#L582-L584)
[github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader.go#L2766-L2768](github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader.go#L2766-L2768)
[github.com/cockroachdb/pebble/internal/cache/external/com_github_cockroachdb_pebble/internal/cache/clockpro.go#L741-L743](github.com/cockroachdb/pebble/internal/cache/external/com_github_cockroachdb_pebble/internal/cache/clockpro.go#L741-L743)
[github.com/cockroachdb/pebble/internal/cache/external/com_github_cockroachdb_pebble/internal/cache/clockpro.go#L119-L121](github.com/cockroachdb/pebble/internal/cache/external/com_github_cockroachdb_pebble/internal/cache/clockpro.go#L119-L121)
[github.com/cockroachdb/pebble/internal/cache/external/com_github_cockroachdb_pebble/internal/cache/entry.go#L151-L153](github.com/cockroachdb/pebble/internal/cache/external/com_github_cockroachdb_pebble/internal/cache/entry.go#L151-L153)
[github.com/cockroachdb/pebble/internal/cache/external/com_github_cockroachdb_pebble/internal/cache/value.go#L38-L40](github.com/cockroachdb/pebble/internal/cache/external/com_github_cockroachdb_pebble/internal/cache/value.go#L38-L40)
[github.com/cockroachdb/pebble/internal/cache/external/com_github_cockroachdb_pebble/internal/cache/refcnt_normal.go#L31-L33](github.com/cockroachdb/pebble/internal/cache/external/com_github_cockroachdb_pebble/internal/cache/refcnt_normal.go#L31-L33)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 489
pkg/kv/kvserver/pkg/kv/kvserver/replica_consistency.go in pkg/kv/kvserver.(*Replica).computeChecksumPostApply.func2 at line 821
pkg/util/contextutil/context.go in pkg/util/contextutil.RunWithTimeout at line 91
pkg/kv/kvserver/pkg/kv/kvserver/replica_consistency.go in pkg/kv/kvserver.(*Replica).computeChecksumPostApply.func2.1 at line 829
pkg/kv/kvserver/pkg/kv/kvserver/replica_consistency.go in pkg/kv/kvserver.(*Replica).sha512 at line 700
pkg/kv/kvserver/rditer/stats.go in pkg/kv/kvserver/rditer.ComputeStatsForRangeWithVisitors at line 38
pkg/storage/mvcc.go in pkg/storage.ComputeStatsWithVisitors at line 5476
pkg/storage/mvcc.go in pkg/storage.computeStatsForIterWithVisitors at line 5524
pkg/storage/intent_interleaving_iter.go in pkg/storage.(*intentInterleavingIter).Next at line 819
pkg/storage/pebble_iterator.go in pkg/storage.(*pebbleIterator).Next at line 426
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/iterator.go in github.com/cockroachdb/pebble.(*Iterator).Next at line 1490
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/iterator.go in github.com/cockroachdb/pebble.(*Iterator).NextWithLimit at line 1597
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/iterator.go in github.com/cockroachdb/pebble.(*Iterator).findNextEntry at line 507
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/iterator.go in github.com/cockroachdb/pebble.(*Iterator).nextUserKey at line 636
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/range_keys.go in github.com/cockroachdb/pebble.(*lazyCombinedIter).Next at line 620
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go in github.com/cockroachdb/pebble.(*mergingIter).Next at line 1107
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go in github.com/cockroachdb/pebble.(*mergingIter).nextEntry at line 555
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/level_iter.go in github.com/cockroachdb/pebble.(*levelIter).Next at line 806
github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader.go in github.com/cockroachdb/pebble/sstable.(*singleLevelIterator).Next at line 1133
github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader.go in github.com/cockroachdb/pebble/sstable.(*singleLevelIterator).skipForward at line 1167
github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader.go in github.com/cockroachdb/pebble/sstable.(*singleLevelIterator).loadBlock at line 498
github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader.go in github.com/cockroachdb/pebble/sstable.(*singleLevelIterator).readBlockWithStats at line 583
github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader.go in github.com/cockroachdb/pebble/sstable.(*Reader).readBlock at line 2767
github.com/cockroachdb/pebble/internal/cache/external/com_github_cockroachdb_pebble/internal/cache/clockpro.go in github.com/cockroachdb/pebble/internal/cache.(*Cache).Get at line 742
github.com/cockroachdb/pebble/internal/cache/external/com_github_cockroachdb_pebble/internal/cache/clockpro.go in github.com/cockroachdb/pebble/internal/cache.(*shard).Get at line 120
github.com/cockroachdb/pebble/internal/cache/external/com_github_cockroachdb_pebble/internal/cache/entry.go in github.com/cockroachdb/pebble/internal/cache.(*entry).acquireValue at line 152
github.com/cockroachdb/pebble/internal/cache/external/com_github_cockroachdb_pebble/internal/cache/value.go in github.com/cockroachdb/pebble/internal/cache.(*Value).acquire at line 39
github.com/cockroachdb/pebble/internal/cache/external/com_github_cockroachdb_pebble/internal/cache/refcnt_normal.go in github.com/cockroachdb/pebble/internal/cache.(*refcnt).acquire at line 32
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
```

### Tags

| Tag | Value |
| --- | --- |
| Command | start-single-node |
| Environment | v22.2.2 |
| Go Version | go1.19.1 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v22.2.2 |
| Cockroach SHA | 07a53a36601e9ca5fcffcff55f69b43c6dfbf1c1 |
| # of CPUs | 4 |
| # of Goroutines | 305 |

Jira issue: CRDB-31200

**Comment by yuzefovich** [comment]
dup of #84971
