### ISSUE TITLE
kvserver: v22.2.13: panic in sendQueuedHeartbeats

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#109942]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4447098745/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4447098745/?referrer=webhooks_plugin)

Panic Message:

```
panic.go:884: runtime error: invalid memory address or nil pointer dereference
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | runtime.panicmem
  | 	GOROOT/src/runtime/panic.go:260
  | runtime.sigpanic
  | 	GOROOT/src/runtime/signal_unix.go:835
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).sendQueuedHeartbeats
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:910
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).coalescedHeartbeatsLoop
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:831
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:489
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (2) runtime error: invalid memory address or nil pointer dereference
Error types: (1) *withstack.withStack (2) runtime.errorString
-- report composition:
runtime.errorString
panic.go:884: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/util/stop/stopper.go#L488-L490](https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/util/stop/stopper.go#L488-L490)
[https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L830-L832](https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L830-L832)
[https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L909-L911](https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L909-L911)
[GOROOT/src/runtime/signal_unix.go#L834-L836](GOROOT/src/runtime/signal_unix.go#L834-L836)
[GOROOT/src/runtime/panic.go#L259-L261](GOROOT/src/runtime/panic.go#L259-L261)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 489
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).coalescedHeartbeatsLoop at line 831
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).sendQueuedHeartbeats at line 910
GOROOT/src/runtime/signal_unix.go in runtime.sigpanic at line 835
GOROOT/src/runtime/panic.go in runtime.panicmem at line 260
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
```

### Tags

| Tag | Value |
| --- | --- |
| Command | start-single-node |
| Environment | v22.2.13 |
| Go Version | go1.19.6 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v22.2.13 |
| Cockroach SHA | c9cdbe4417ec387382cf6c0edafee51b3d58e278 |
| # of CPUs | 16 |
| # of Goroutines | 409 |

Jira issue: CRDB-31170

**Comment by pavelkalinnikov** [comment]
The nil pointer dereference is on a metric update line: https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/kv/kvserver/store_raft.go#L910

**Comment by pavelkalinnikov** [comment]
Can't see how this can happen. The metrics are created in `NewStore()`, then `Store.Start()` kicks off `processRaft()` which kicks of this heartbeats goroutine.

Probably unactionable.

**Comment by pavelkalinnikov** [comment]
The `uptime` label is <10s. So this is likely happening on the server startup.

**Comment by pavelkalinnikov** [comment]
Could also be a corrupted memory.
