### ISSUE TITLE
CockroachDB doesn't return ErrorResponse if client sends a startup message with invalid database name

### ISSUE THREAD

**Issue by giangpham712** [cockroachdb/cockroach#109992]
**Describe the problem**
With PosgreSQL, when client sends a startup message with invalid database name, the response will be ErrorResponse as specified here (https://www.postgresql.org/docs/current/protocol-flow.html). CockroachDB still returns a ReadyForQuery response

**Additional context**
This affects efcore.pg tests

@fqazi 

Jira issue: CRDB-31206

**Comment by rafiss** [comment]
Let's add a test for this in pkg/sql/pgwire/testdata/pgtest - let me know if you need help with the syntax for these tests.

**Comment by fqazi** [comment]
@giangpham712 Can you share the connection string for when this happens? Trying to figure out where things are going off the rails

**Comment by giangpham712** [comment]
@fqazi It could be something like this

```Host=localhost;Username=crdb_tests;Port=26257;Include Error Detail=True;Timeout=300;Command Timeout=300;Options="-c null_ordered_last=true";Database=BatchingTest;Pooling=False;Multiplexing=False```

**Comment by rafiss** [comment]
@fqazi maybe this related to mixed-case names specifically?

**Comment by fqazi** [comment]
No, case sensitivity also works fine if I try this in the pg_wire tests for CRDB. Let me try using Npgsql and seeing if that exhibits this problem

**Comment by fqazi** [comment]
@giangpham712 I tried the following sequence and still see the correct error in .NET (i.e. invalid database names error out correctly):

```
var connString = "Host=localhost;Username=root;Port=26257;Database=Defaultdb";
await using var conn = new NpgsqlConnection(connString);
await conn.OpenAsync();
```
