### ISSUE TITLE
rpc: window size initialization performs logging at init time

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#109900]
Found by @erikgrinaker [here](https://github.com/cockroachdb/cockroach/issues/84638#issuecomment-1697396705)

The init vars in rpc/settings.go perform logging at init time. This is undesirable because it prevents the log output from going to the right place.

Epic: CRDB-28893

Jira issue: CRDB-31144

**Comment by abarganier** [comment]
IMO, this should be solved via https://github.com/cockroachdb/cockroach/issues/110028.
