### ISSUE TITLE
intervalstyle variable not applied when variable set on database

### ISSUE THREAD

**Issue by hendrikheil** [cockroachdb/cockroach#109990]
**Describe the problem**

We are using the interval data type to store durations in a table. We're using the ISO8601 format to ensure all of our systems can easily understand the values. We just noticed the returned values are returned in the Postgres abbreviated style, which we have found no code or spec for to parse correctly. Unfortunately, we are not able to alter any cluster variables or set session variables (as we use PHP for one of the reading systems).

We tried to set the intervalstyle as a setting on the database, but it doesn't seem to get used for the returned values on tables in the database.

Ideally we'd be able to specify the intervalstyle on the column definition itself, so we wouldn't have to worry about the context that our queries get ran in, but I'm not sure that is a feasible option.

**To Reproduce**
1. Create CockroachDB cluster
2. Create any database
3. Create Table in new database with INTERVAL column
4. ALTER DATABASE and set intervalstyle variable to 'iso_8601';
5. Disconnect and connect again
6. SELECT from new database

Values are returned as Postgres abbreviated intervalstyle

**Expected behavior**

Values should be returned as ISO8601 interval style (i.e. P1M instead of "1 mon")

**Additional data / screenshots**
```sql
CREATE DATABASE example;

CREATE TABLE example.durations (
  id UUID PRIMARY KEY,
  min INTERVAL,
  max INTERVAL
);

INSERT INTO example.durations (id, min, max) VALUES (gen_random_uuid(), 'P1D', 'P1M');

SELECT * FROM example.durations;

ALTER DATABASE example SET intervalstyle = 'iso_8601';

// Disconnect and re-connect to make sure the variable is applied

SELECT * FROM example.durations;
```

**Environment:**
 - CockroachDB version: v23.1.8
 - Server OS: Docker on MacOS, Apple Silicon
 - Client app:`cockroach sql`, PHP PDO

Jira issue: CRDB-31205

**Comment by rafiss** [comment]
Thanks for the bug report.

- Are you connecting using the `root` user? THe `root` user is exempt from session variable defaults that are configured in this way.
- Also, can you share the connection string you used?

**Comment by hendrikheil** [comment]
During development, we are indeed connecting over `root` as we can declaratively connect to it, when our docker stack is being created. Thats probably the reason why we couldn't see anything change when we altered the database.

We did work around this issue by just having a computed column that returns it in the right format. And we'll probably stick with that since we try not to create special context requirements.

Would it be an option to store the intervalstyle directly with the column? It felt like the most natural and most flexible approach to this. If it's not off the table, I'd maybe take a look and see if we could contribute?

**Comment by rafiss** [comment]
One option you might be able to use is the builtin function: `to_char_with_style(interval_val, style)`. If you call this function you can explicitly control how an interval is formatted into a string.

> Would it be an option to store the intervalstyle directly with the column?

I don't think I understand this option well. Could you give an example of what you mean?

**Comment by hendrikheil** [comment]
That is what we are using through a computed column as of right now. It's requires us to write a bit of weird casting logic, as we write to a different column than what we are reading from.

What I had expected to see as an option instead of intervalstyle being a setting, was the ability to define how the intervalstyle is returned on a per column basis.

```
CREATE TABLE durations (
  id UUID PRIMARY KEY,
  min INTERVAL('iso_8601'),
  max INTERVAL('iso_8601'),
);
```

In terms of making this compatible with the current settings, I would expect this to be more specific than a cluster or role setting. So if no style is specified the cluster defaults get used (as is the behavior right now), however if you do specify one, it uses that style for the column, no matter the cluster setting.

I think this would be particularly useful, as it allows a user to determine the representation in a query, based on the schema and not on the context/cluster of where that schema is created.

**Comment by rafiss** [comment]
> What I had expected to see as an option instead of intervalstyle being a setting, was the ability to define how the intervalstyle is returned on a per column basis.

The one issue with that is that it's not really standard SQL. We usually try to match the PostgreSQL syntax, which does not do that. Also in this case I don't think anything in the SQL grammar allows for strings inside of a type modifier, like `INTERVAL('iso_8601')`.

> I think this would be particularly useful, as it allows a user to determine the representation in a query, based on the schema and not on the context/cluster of where that schema is created.

Does the suggestion above to use `to_char_with_style(interval_val, style)` satisfy this use case? You can define a computed column, like:
```
CREATE TABLE durations (
  id UUID PRIMARY KEY,
  min INTERVAL,
  max INTERVAL,
  min_formatted STRING AS (to_char_with_style(min, 'iso_8601')) VIRTUAL,
  max_formatted STRING AS (to_char_with_style(max, 'iso_8601')) VIRTUAL
);
```

Or you can use the `to_char_with_style` function from the SELECT queries that you create.

**Comment by rafiss** [comment]
Closing as per above comment. Please let me know if `to_char_with_style` does not work for you.
