### ISSUE TITLE
Sentry: txn.go:775: deadline below read timestamp is nonsensical; txn has would have no chance to commit. Deadline: 1693763450.283915469,0. Read timestamp: 1693766530.254361547,2 Previous Deadline: 16...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#109983]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4450709210/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4450709210/?referrer=webhooks_plugin)

Panic Message:

```
txn.go:775: deadline below read timestamp is nonsensical; txn has would have no chance to commit. Deadline: 1693763450.283915469,0. Read timestamp: 1693766530.254361547,2 Previous Deadline: 1693763450.283915469,0.
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/kv.(*Txn).UpdateDeadline
  | 	github.com/cockroachdb/cockroach/pkg/kv/txn.go:775
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*leasedDescriptors).maybeUpdateDeadline
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/leased_descriptors.go:220
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).MaybeUpdateDeadline
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:152
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).handleAutoCommit
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2171
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState.func7
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:518
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:743
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:131
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2428
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:130
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1973
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1977
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1898
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:857
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:730
  | runtime.goexit
  | 	src/runtime/asm_arm64.s:1172
Wraps: (3) deadline below read timestamp is nonsensical; txn has would have no chance to commit. Deadline: 1693763450.283915469,0. Read timestamp: 1693766530.254361547,2 Previous Deadline: 1693763450.283915469,0.
Error types: (1) *assert.withAssertionFailure (2) *withstack.withStack (3) *errutil.leafError
-- report composition:
*errutil.leafError: deadline below read timestamp is nonsensical; txn has would have no chance to commit. Deadline: 1693763450.283915469,0. Read timestamp: 1693766530.254361547,2 Previous Deadline: 1693763450.283915469,0.
txn.go:775: *withstack.withStack (top exception)
*assert.withAssertionFailure
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_arm64.s#L1171-L1173](src/runtime/asm_arm64.s#L1171-L1173)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/pgwire/conn.go#L729-L731](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/pgwire/conn.go#L729-L731)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/conn_executor.go#L856-L858](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/conn_executor.go#L856-L858)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/conn_executor.go#L1897-L1899](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/conn_executor.go#L1897-L1899)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/conn_executor.go#L1976-L1978](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/conn_executor.go#L1976-L1978)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/conn_executor.go#L1972-L1974](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/conn_executor.go#L1972-L1974)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/conn_executor_exec.go#L129-L131](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/conn_executor_exec.go#L129-L131)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/conn_executor_exec.go#L2427-L2429](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/conn_executor_exec.go#L2427-L2429)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/conn_executor_exec.go#L130-L132](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/conn_executor_exec.go#L130-L132)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/conn_executor_exec.go#L742-L744](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/conn_executor_exec.go#L742-L744)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/conn_executor_exec.go#L517-L519](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/conn_executor_exec.go#L517-L519)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/conn_executor_exec.go#L2170-L2172](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/conn_executor_exec.go#L2170-L2172)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/catalog/descs/collection.go#L151-L153](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/catalog/descs/collection.go#L151-L153)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/catalog/descs/leased_descriptors.go#L219-L221](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/catalog/descs/leased_descriptors.go#L219-L221)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/kv/txn.go#L774-L776](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/kv/txn.go#L774-L776)
</details>

```
src/runtime/asm_arm64.s in runtime.goexit at line 1172
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommandsAsync.func1 at line 730
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 857
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 1898
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 1977
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd.func1 at line 1973
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 130
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithProfiling at line 2428
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt.func1 at line 131
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 743
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState.func7 at line 518
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).handleAutoCommit at line 2171
pkg/sql/catalog/descs/collection.go in pkg/sql/catalog/descs.(*Collection).MaybeUpdateDeadline at line 152
pkg/sql/catalog/descs/leased_descriptors.go in pkg/sql/catalog/descs.(*leasedDescriptors).maybeUpdateDeadline at line 220
pkg/kv/txn.go in pkg/kv.(*Txn).UpdateDeadline at line 775
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v22.2.7 |
| Go Version | go1.19.6 |
| Platform | linux arm64 |
| Distribution | CCL |
| Cockroach Release | v22.2.7 |
| Cockroach SHA | cbe33971930ee972e639203a73f14240b92aeff4 |
| # of CPUs | 8 |
| # of Goroutines | 454 |

Jira issue: CRDB-31199

**Comment by yuzefovich** [comment]
dup of #76727
