### ISSUE TITLE
SHOW RANGES FROM DATABASE fails with insufficient bytes to decode uvarint

### ISSUE THREAD

**Issue by j82w** [cockroachdb/cockroach#110051]
The ListDatabases call in a single region host failed with:
```
failed to load regions: ERROR: recv msg error: rpc error: code = Unauthenticated desc = requested key span /Tenant/51{1-2} not fully contained in tenant keyspace /Tenant/{511-err:insufficient bytes to decode uvarint value: "\x02"}
```

https://teamcity.cockroachdb.com/buildConfiguration/Internal_ManagedService_IntegrationTestStaging/11616107?expandBuildProblemsSection=true&hideProblemsFromDependencies=false&expandBuildTestsSection=true&hideTestsFromDependencies=false&expandBuildChangesSection=true

https://teamcity.cockroachdb.com/buildConfiguration/Internal_ManagedService_IntegrationTestStaging/11626412?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildProblemsSection=true&expandBuildTestsSection=true
tenant id 109 is a uvarint boundary

The code was added in: https://github.com/cockroachlabs/managed-service/pull/10834 from query:
```sql
SELECT 
  DISTINCT split_part(
    split_part(
      unnest(replica_localities), 
      ',', 
      1
    ), 
    '=', 
    2
  ) AS region 
FROM 
  [SHOW RANGES 
FROM 
  DATABASE %1]
```

It's likely the same issue as: https://github.com/cockroachdb/cockroach/issues/104928
Related internal chat: https://cockroachlabs.slack.com/archives/C02P01CDKKP/p1693827854236639

Jira issue: CRDB-31246
Epic: CRDB-26091

**Comment by knz** [comment]
@stevendanna , @yuzefovich and I investigated this. We found two separate issues:

- the error _message_ is worrying/confusing because of a pretty-print shortcoming #110192
- the actual error is caused by a bug in the RPC authorization code. This bug had been flagged during the work on PR #104974 but wasn't fixed at the time.

I'll send a PR.
