### ISSUE TITLE
sql: support ALTER TABLE ... ALTER COLUMN ... SET INCREMENT BY...

### ISSUE THREAD

**Issue by giangpham712** [cockroachdb/cockroach#110011]
**Is your feature request related to a problem? Please describe.**
support `support ALTER TABLE ... ALTER COLUMN ... SET INCREMENT BY...

Example

`ALTER TABLE "People" ALTER COLUMN "Id" SET INCREMENT BY 2`

**Additional context**
This affects efcore.pg tests

@fqazi 

Jira issue: CRDB-31218

**Comment by fqazi** [comment]
Closing in favour of: https://github.com/cockroachdb/cockroach/issues/110010 since these are related
