### ISSUE TITLE
sql: support ALTER TABLE ... ALTER COLUMN ... {ADD | SET} GENERATED ... 

### ISSUE THREAD

**Issue by giangpham712** [cockroachdb/cockroach#110010]
**Is your feature request related to a problem? Please describe.**
support `ALTER TABLE ... ALTER COLUMN ... {ADD | SET} GENERATED ...`

**Describe the solution you'd like**
Similar to PostgreSQL

`ALTER [ COLUMN ] column_name ADD GENERATED { ALWAYS | BY DEFAULT } AS IDENTITY [ ( sequence_options ) ]`

`ALTER [ COLUMN ] column_name { SET GENERATED { ALWAYS | BY DEFAULT } | SET sequence_option | RESTART [ [ WITH ] restart ] }`

Also, the related syntax should be covered:
`ALTER TABLE "People" ALTER COLUMN "Id" SET INCREMENT BY 2`

https://www.postgresql.org/docs/current/sql-altertable.html

**Additional context**
This affects efcore.pg tests

@fqazi 

Jira issue: CRDB-31217

**Comment by fqazi** [comment]
@giangpham712 Let's skip this test for now, and we can definitely add this syntax, but not realistic for 23.1
