### ISSUE TITLE
sql/schemachanger: CREATE INDEX with partial indexes with concurrent inserts can fail

### ISSUE THREAD

**Issue by fqazi** [cockroachdb/cockroach#110198]
Previously, when the declarative schema changer was creating temporary indexes for partial indexes, the index expression was not copied over. As a result, when new inserts came in during index creation, we would capture writes which were not relevant to the index partial expression. This would cause partial index creation to fail during validation since the combined merged index (backfilled and temporary index) would have extra rows.

Jira issue: CRDB-31317

Epic CRDB-30350

**Comment by daniel-crlabs** [comment]
@fqazi Any idea when this fix will be released? We have customers running into this issue `duplicate key value violates unique constraint` and having to disable it with what's shown below (customer is on `23.1.11`)

```
SET use_declarative_schema_changer = off;
```

Once the customers do the above they are able to create the index. Are there any negative consequences to disabling the declarative schema changer in this scenario (creating indexes)? Can they safely move forward with `SET use_declarative_schema_changer = off` for any session where they this king of index? Example below:

```
CREATE INDEX index_name_here 
ON table_name_here (bucketnum, keyname) 
WHERE (validstate = 3) AND (versioned = true);
```

**Comment by daniel-crlabs** [comment]
Thank you, I'll let them know.
