### ISSUE TITLE
debug zip: make option to "opt out" of stack dumps

### ISSUE THREAD

**Issue by abarganier** [cockroachdb/cockroach#110103]
**Is your feature request related to a problem? Please describe.**
The `/debug/stacks/<node_id>` endpoint called by debug zip is a heavyweight, "stop the world" operation that uses the `runtime.Stack()` function. Stopping the world on a production cluster can lead to large momentary spikes in SQL Service Latency, which is disruptive especially on larger clusters/workloads.

**Describe the solution you'd like**
Create an option to avoid the pulling of the `/debug/stacks/<node_id>` dumps made by `debug zip`. This will give users the option to take a debug zip with a minimized performance impact.

Jira issue: CRDB-31269

**Comment by dt** [comment]
Should this be revised from “opt-in “ to “allow…opt out” based on discussion in #110177 ?

**Comment by abarganier** [comment]
@dt yup! Just revised the issue & patched the PR as such.

**Comment by djshow832** [comment]
I guess you're encountering an issue similar to that of TiDB: https://github.com/pingcap/tidb/issues/48695: `/pprof/goroutines/debug=1` works fine but `debug=2` causes STW.

I saw that `stacks_with_labels.txt` requests stacks with `debug=1`, which is fine. However, the option you added in https://github.com/cockroachdb/cockroach/pull/110177 also affects `stacks_with_labels.txt`.

When the server has many goroutines but the user wants to query the goroutines, he could fetch `stacks_with_labels.txt` with little effect but now he's in a dilemma.
