### ISSUE TITLE
Change default row level TTL cron job to run every 4 hours instead of every hour

### ISSUE THREAD

**Issue by dikshant** [cockroachdb/cockroach#110132]
Currently the row level TTL job runs every hour. This is suboptimal as gc.ttl is 4 hour by default. Running it more frequently within that window means having to scan over a larger number of delete tombstones. We should default to 4 hours to match gc.ttl in this case so we have less things to scan.

Jira issue: CRDB-31278

Epic CRDB-27601

**Comment by rafiss** [comment]
We might want to add something so that the "every 4 hour" schedule falls on a random minute in the hour. We have something similar for `@hourly` schedules.

**Comment by rafiss** [comment]
Confirmed with @dikshant offline that we can use `@daily` here. The benefit is that `@daily` already has the logic to pick a random time of day, instead of running at `00:00` every day.
