### ISSUE TITLE
sql: v22.2.13: nil searchPath when resolving builtin func definition in prepared stmt

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#110259]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4464015249/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4464015249/?referrer=webhooks_plugin)

Panic Message:

```
conn_executor.go:880: runtime error: invalid memory address or nil pointer dereference
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:880
  | [...repeated from below...]
Wraps: (2) while executing: EXECUTE _ (add(_, _))
Wraps: (3) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:880
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | runtime.panicmem
  | 	GOROOT/src/runtime/panic.go:260
  | runtime.sigpanic
  | 	GOROOT/src/runtime/signal_unix.go:835
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.GetBuiltinFuncDefinition
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/function_definition.go:436
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.GetBuiltinFuncDefinitionOrFail
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/function_definition.go:394
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*ResolvableFunctionReference).Resolve
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/function_name.go:105
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FuncExpr).TypeCheck
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/type_check.go:1039
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.TypeCheck
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/type_check.go:273
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/schemaexpr.SanitizeVarFreeExpr
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/schemaexpr/expr.go:440
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).fillInPlaceholders
  | 	github.com/cockroachdb/cockroach/pkg/sql/execute.go:56
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:437
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:131
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2440
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:130
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2129
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2133
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2054
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:882
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:769
  | runtime.goexit
  | 	src/runtime/asm_arm64.s:1172
Wraps: (4) runtime error: invalid memory address or nil pointer dereference
Error types: (1) *withstack.withStack (2) *safedetails.withSafeDetails (3) *withstack.withStack (4) runtime.errorString
-- report composition:
runtime.errorString
conn_executor.go:880: *withstack.withStack (top exception)
*safedetails.withSafeDetails: while executing: EXECUTE _ (add(_, _))
conn_executor.go:880: *withstack.withStack (1)
(check the extra data payloads)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_arm64.s#L1171-L1173](src/runtime/asm_arm64.s#L1171-L1173)
[https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/pgwire/conn.go#L768-L770](https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/pgwire/conn.go#L768-L770)
[https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/conn_executor.go#L881-L883](https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/conn_executor.go#L881-L883)
[https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/conn_executor.go#L2053-L2055](https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/conn_executor.go#L2053-L2055)
[https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/conn_executor.go#L2132-L2134](https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/conn_executor.go#L2132-L2134)
[https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/conn_executor.go#L2128-L2130](https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/conn_executor.go#L2128-L2130)
[https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/conn_executor_exec.go#L129-L131](https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/conn_executor_exec.go#L129-L131)
[https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/conn_executor_exec.go#L2439-L2441](https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/conn_executor_exec.go#L2439-L2441)
[https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/conn_executor_exec.go#L130-L132](https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/conn_executor_exec.go#L130-L132)
[https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/conn_executor_exec.go#L436-L438](https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/conn_executor_exec.go#L436-L438)
[https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/execute.go#L55-L57](https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/execute.go#L55-L57)
[https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/catalog/schemaexpr/expr.go#L439-L441](https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/catalog/schemaexpr/expr.go#L439-L441)
[https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/sem/tree/type_check.go#L272-L274](https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/sem/tree/type_check.go#L272-L274)
[https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/sem/tree/type_check.go#L1038-L1040](https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/sem/tree/type_check.go#L1038-L1040)
[https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/sem/tree/function_name.go#L104-L106](https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/sem/tree/function_name.go#L104-L106)
[https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/sem/tree/function_definition.go#L393-L395](https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/sem/tree/function_definition.go#L393-L395)
[https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/sem/tree/function_definition.go#L435-L437](https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/sem/tree/function_definition.go#L435-L437)
[GOROOT/src/runtime/signal_unix.go#L834-L836](GOROOT/src/runtime/signal_unix.go#L834-L836)
[GOROOT/src/runtime/panic.go#L259-L261](GOROOT/src/runtime/panic.go#L259-L261)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
[https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/conn_executor.go#L879-L881](https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/conn_executor.go#L879-L881)
</details>

```
src/runtime/asm_arm64.s in runtime.goexit at line 1172
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommandsAsync.func1 at line 769
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 882
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 2054
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 2133
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd.func1 at line 2129
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 130
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithProfiling at line 2440
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt.func1 at line 131
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 437
pkg/sql/execute.go in pkg/sql.(*planner).fillInPlaceholders at line 56
pkg/sql/catalog/schemaexpr/expr.go in pkg/sql/catalog/schemaexpr.SanitizeVarFreeExpr at line 440
pkg/sql/sem/tree/type_check.go in pkg/sql/sem/tree.TypeCheck at line 273
pkg/sql/sem/tree/type_check.go in pkg/sql/sem/tree.(*FuncExpr).TypeCheck at line 1039
pkg/sql/sem/tree/function_name.go in pkg/sql/sem/tree.(*ResolvableFunctionReference).Resolve at line 105
pkg/sql/sem/tree/function_definition.go in pkg/sql/sem/tree.GetBuiltinFuncDefinitionOrFail at line 394
pkg/sql/sem/tree/function_definition.go in pkg/sql/sem/tree.GetBuiltinFuncDefinition at line 436
GOROOT/src/runtime/signal_unix.go in runtime.sigpanic at line 835
GOROOT/src/runtime/panic.go in runtime.panicmem at line 260
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn.func1 at line 880
```

### Tags

| Tag | Value |
| --- | --- |
| Command | demo |
| Environment | v22.2.13 |
| Go Version | go1.19.6 |
| Platform | darwin arm64 |
| Distribution | CCL |
| Cockroach Release | v22.2.13 |
| Cockroach SHA | c9cdbe4417ec387382cf6c0edafee51b3d58e278 |
| # of CPUs | 10 |
| # of Goroutines | 379 |

Jira issue: CRDB-31349

**Comment by fqazi** [comment]
@andyyang890 We just need to check if the search path is nil inside: GetBuiltinFuncDefinition and handle that gracefully

**Comment by rafiss** [comment]
closing due to staleness and since this was from an older release
