### ISSUE TITLE
c2c: slow quiesce failure TestDataDriven/initial_scan_spanconfigs : rangefeed client hangs on close

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#110350]
See CI failure [here.](https://teamcity.cockroachdb.com/viewLog.html?buildId=11722902&buildTypeId=Cockroach_BazelEssentialCi). I think the relevant goroutine points to a slow rangefeed.Close() in the c2c eventStream.

```
goroutine 40449 [chan receive, 14 minutes]:
github.com/cockroachdb/cockroach/pkg/kv/kvclient/rangefeed.(*RangeFeed).Close.func1()
	github.com/cockroachdb/cockroach/pkg/kv/kvclient/rangefeed/rangefeed.go:258 +0x3c
sync.(*Once).doSlow(0x0?, 0x0?)
	GOROOT/src/sync/once.go:74 +0xc2
sync.(*Once).Do(...)
	GOROOT/src/sync/once.go:65
github.com/cockroachdb/cockroach/pkg/kv/kvclient/rangefeed.(*RangeFeed).Close(0xc00b68c220?)
	github.com/cockroachdb/cockroach/pkg/kv/kvclient/rangefeed/rangefeed.go:256 +0x47
github.com/cockroachdb/cockroach/pkg/ccl/streamingccl/streamproducer.(*eventStream).Close(0xc00b401c00, {0x7a393b0, 0xc0099c34a0})
	github.com/cockroachdb/cockroach/pkg/ccl/streamingccl/streamproducer/event_stream.go:234 +0x4d
github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*projectSetProcessor).close(0xc0060c5200)
	github.com/cockroachdb/cockroach/pkg/sql/rowexec/project_set.go:345 +0x9a
github.com/cockroachdb/cockroach/pkg/sql/rowexec.newProjectSetProcessor.func1()
	github.com/cockroachdb/cockroach/pkg/sql/rowexec/project_set.go:105 +0x1d
github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBaseNoHelper).moveToTrailingMeta(0xc0060c5200)
	github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:689 +0x3b8
github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBaseNoHelper).DrainHelper(0xc0060c5200)
	github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:570 +0x196
github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*projectSetProcessor).Next(0xc0060c5200)
	github.com/cockroachdb/cockroach/pkg/sql/rowexec/project_set.go:328 +0x1f4
github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBaseNoHelper).DrainHelper(0xc007076000)
	github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:566 +0x12e
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Columnarizer).DrainMeta(0xc007076000)
	github.com/cockroachdb/cockroach/pkg/sql/colexec/columnarizer.go:285 +0x211
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*invariantsChecker).DrainMeta(0xc00c3ea800)
	github.com/cockroachdb/cockroach/pkg/sql/colexec/invariants_checker.go:119 +0x3c
github.com/cockroachdb/cockroach/pkg/sql/colexecop.MetadataSources.DrainMeta.func1()
	github.com/cockroachdb/cockroach/pkg/sql/colexecop/operator.go:464 +0x6b
github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError(0xc011feada0?)
	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92 +0x62
github.com/cockroachdb/cockroach/pkg/sql/colexecop.MetadataSources.DrainMeta({0xc00ee7c140?, 0x7a78800?, 0xc00d59fd40?})
	github.com/cockroachdb/cockroach/pkg/sql/colexecop/operator.go:462 +0x8a
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).Run(0xc00eee0fa0, {0x7a39308?, 0xc009f94780?})
...
```

Jira issue: CRDB-31392

**Comment by msbutler** [comment]
@miretskiy do you know of any recent rangefeed work that could have caused this?

**Comment by msbutler** [comment]
aha, I thought of one theory (without evidence) for why this could be occurring: this unit test doesn't manually shut down the replication stream, so maybe some context cancellation wires are getting crossed somewhere.

**Comment by msbutler** [comment]
I can repro this failure via
```
git checkout 746388795af76a43cc21d072d06bc646b8179374
./dev test pkg/ccl/streamingccl/streamingest -f TestDataDriven/initial_scan_span_configs --stress --timeout 120s
```

**Comment by msbutler** [comment]
Opened https://github.com/cockroachdb/cockroach/pull/110504 to deflake this test, but there still may be some deadlock problem in rangefeed.Close()

**Comment by miretskiy** [comment]
> @miretskiy do you know of any recent rangefeed work that could have caused this?

There is plenty; but not where you're seeing this.  This seems to be the rangefeed library (not to be confused with the "dist sender rangefeed") that seems stuck.

**Comment by miretskiy** [comment]
This happen after mux was turned on?

**Comment by msbutler** [comment]
I see a mux rangefeed goroutine in the dump....so, yes?
```
* goroutine 29278 [semacquire, 2 minutes]:
* sync.runtime_Semacquire(0xc00335f860?)
* 	GOROOT/src/runtime/sema.go:62 +0x27
* sync.(*WaitGroup).Wait(0xb470301?)
* 	GOROOT/src/sync/waitgroup.go:116 +0x4b
* golang.org/x/sync/errgroup.(*Group).Wait(0xc00bf42700)
* 	golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:53 +0x27
* github.com/cockroachdb/cockroach/pkg/util/ctxgroup.Group.Wait({0xc00bf42700?, {0x7a39308?, 0xc00fa9dae0?}})
* 	github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:144 +0x4a
* github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.muxRangeFeed({0x7a393b0, 0xc00103d7d0}, {0x1, 0x1, 0x1, 0x0, {0x0, 0x0, 0x0}}, {0xc00bf42680, ...}, ...)
* 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go:102 +0x490
* github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).RangeFeedSpans(0xc00f33d600, {0x7a39308, 0xc00fa9d810}, {0xc00bf42680?, 0x1, 0x1}, 0xc0099b7bc0, {0xc00bf42300, 0x3, 0x4})
* 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go:234 +0x490
* github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).RangeFeed(0x582ea80?, {0x7a39308, 0xc00fa9d810}, {0xc00b737080, 0x1, 0x2?}, {0xd04b5c?, 0x0?, 0x0?}, 0xc0099b7bc0, ...)
* 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go:183 +0x29a
* github.com/cockroachdb/cockroach/pkg/kv/kvclient/rangefeed.(*dbAdapter).RangeFeed(0x1e3b040?, {0x7a39308?, 0xc00fa9d810?}, {0xc00b737080?, 0xc009a47fd0?, 0x1269c26?}, {0x7a393b0?, 0xb7371a0?, 0xc0?}, 0xc0099b7bc0, ...)
* 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/rangefeed/db_adapter.go:79 +0x65
* github.com/cockroachdb/cockroach/pkg/kv/kvclient/rangefeed.(*RangeFeed).run.func1({0x7a39308?, 0xc00fa9d810?})
* 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/rangefeed/rangefeed.go:314 +0xb2
* github.com/cockroachdb/cockroach/pkg/util/ctxgroup.Group.GoCtx.func1()
* 	github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:168 +0x25
* golang.org/x/sync/errgroup.(*Group).Go.func1()
* 	golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:75 +0x64
* created by golang.org/x/sync/errgroup.(*Group).Go
* 	golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:72 +0xa5
```

**Comment by miretskiy** [comment]
Just guessing here: 
```
	if err := f.stopper.RunAsyncTask(ctx, "rangefeed", runWithFrontier); err != nil {
		f.cancel()
		return err
	}
```
(that's in the rangefeed.go... Shouldn't we use WithCancelOnQuiesce here?)

**Comment by dt** [comment]
@msbutler do you have the rest of the stack dump?

**Comment by dt** [comment]
@miretskiy we do don't we? one line above?
https://github.com/cockroachdb/cockroach/blob/00cbb307b7b42f0556f5a3703dd9e5ba9b4ab48f/pkg/kv/kvclient/rangefeed/rangefeed.go#L244-L248

**Comment by msbutler** [comment]
@dt writing something up now and plan to hand off to kv and the rangefeed scalability team

**Comment by msbutler** [comment]
Handing this off to kv and posting in the rangefeed-scalablity channel about this.

To summarize: when the test ends, there's an active c2c job running. When the test runner shuts down a test server, the test occasionally fails because of a slow quiesce message. To repro the slowness (without waiting for the quiesce timeout), run [this.](https://github.com/cockroachdb/cockroach/issues/110350#issuecomment-1716397645)

The goroutine dump points to rangefeed.Close hanging here:
https://github.com/cockroachdb/cockroach/blob/3722fc1ae0a9d1ddc2de21bc298667580acd5ba1/pkg/ccl/streamingccl/streamproducer/event_stream.go#L234

Looking a little further in the rangefeed client library, the goroutine dump indicates we're waiting in `rangefeed.Close()` for this stopper channel:
https://github.com/cockroachdb/cockroach/blob/5c2f80caf469daf2eafbc7663bab23ba23895395/pkg/kv/kvclient/rangefeed/rangefeed.go#L258

That stopper channel closes when `rangefeed.run()` returns, but the dump indicates that it has not returned as its waiting on the `processEvents` goroutine to finish.
https://github.com/cockroachdb/cockroach/blob/5c2f80caf469daf2eafbc7663bab23ba23895395/pkg/kv/kvclient/rangefeed/rangefeed.go#L320
example stack in the dump
```
goroutine 428 [sync.Cond.Wait, 1 minutes]:
sync.runtime_notifyListWait(0xc006065390, 0x1)
  GOROOT/src/runtime/sema.go:527 +0x14c
sync.(*Cond).Wait(0xc000c6c780?)
  GOROOT/src/sync/cond.go:70 +0x8c
github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*Scheduler).processEvents(0xc0063e20c0, {0x7a4e820, 0xc0010f98c0})
  github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed/scheduler.go:295 +0x4a6
github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*Scheduler).Start.func1({0x7a4e820, 0xc0010f98c0})
  github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed/scheduler.go:162 +0x11f
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
  github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:484 +0x146
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx
  github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:475 +0x43b
  ```

Figuring out why processEvents is hanging is beyond my pay grade, so I'm handing over to kv.

Some things to note:
-  I don't think this is a mux rangefeed problem. If I set `changefeed.mux_rangefeed.enabled` to false during test cluster startup, the test still hangs.
- if the c2c shuts job down cleanly via job completion, I don't see this hanging behavior. I may deflake this test by cleanly shutting down the job. Obviously this [patch](https://github.com/cockroachdb/cockroach/pull/110504) would not solve this bug here.

**Comment by dt** [comment]
> sync.Cond.Wait

Is this just the usual "condition variables don't compose with context cancellation which is why we don't use them" issue?

**Comment by miretskiy** [comment]
> > sync.Cond.Wait
> 
> Is this just the usual "condition variables don't compose with context cancellation which is why we don't use them" issue?

worth checking -- esp since this is new code; but I'm not sure that's the case.  it's just a standard producer/consumer
patter where consumer (processEvents) is getting signaled if the processor stopped.

**Comment by erikgrinaker** [comment]
Why is this using the rangefeed scheduler at all? It's disabled by default, and I don't believe we've enabled any metamorphism. Did y'all explicitly enable it or something?

**Comment by erikgrinaker** [comment]
Ah, I guess we start the scheduler regardless, but don't actually use it for any rangefeeds unless the setting is enabled. So this is just failing to shut down an idle scheduler. I guess this is all the motivation we need for https://github.com/cockroachdb/cockroach/issues/110634 @aliher1911.

**Comment by msbutler** [comment]
a heads up that i've bors'd a[ pr](https://github.com/cockroachdb/cockroach/pull/110504) that will deflake this test. You can still repro the bug on a checked out branch.

https://github.com/cockroachdb/cockroach/issues/110350#issuecomment-1716397645
