### ISSUE TITLE
upgrade: automated catalog repairs incorrectly removes TTL from the table descriptor

### ISSUE THREAD

**Issue by ecwall** [cockroachdb/cockroach#110363]
During a cluster upgrade TTL is incorrectly removed from table descriptors [here](https://github.com/cockroachdb/cockroach/blob/v23.1.9/pkg/sql/catalog/tabledesc/table_desc_builder.go#L250) because the TTL job schedule ID from the table descriptor is incorrectly being searched for in a set of job IDs [here](https://github.com/cockroachdb/cockroach/blob/v23.1.9/pkg/sql/sem/builtins/builtins.go#L5216).

Later on when the TTL job runs, it panics (stack trace here https://github.com/cockroachlabs/support/issues/2593#issuecomment-1713899436) and crashes the node.

**Remove the TTL "repair" for now:** https://cockroachlabs.slack.com/archives/C05RE28U495/p1694456292147979?thread_ts=1694454150.432349&cid=C05RE28U495

See also:
https://github.com/cockroachlabs/support/issues/2593#issuecomment-1714377621

Jira issue: CRDB-31400

**Comment by celiala** [comment]
I'm going to reopen this issue until the backport to 23.1 has merged, fyi @ecwall @rafiss

**Comment by celiala** [comment]
I think all backports are merged - I'll go ahead an close this now, fyi @ecwall @rafiss
