### ISSUE TITLE
Sentry: db.go:742: log.Fatal: no data available
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/pebble.(*DB).Apply
  | 	github.com/cockroachdb/pebble/external/com_github_cockroac...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#110318]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4467415671/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4467415671/?referrer=webhooks_plugin)

Panic Message:

```
db.go:742: log.Fatal: no data available
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/pebble.(*DB).Apply
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go:742
  | github.com/cockroachdb/pebble.(*DB).Set
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go:554
  | github.com/cockroachdb/cockroach/pkg/storage.(*Pebble).put
  | 	github.com/cockroachdb/cockroach/pkg/storage/pebble.go:1404
  | github.com/cockroachdb/cockroach/pkg/storage.(*Pebble).PutUnversioned
  | 	github.com/cockroachdb/cockroach/pkg/storage/pebble.go:1381
  | github.com/cockroachdb/cockroach/pkg/storage.(*putBuffer).putInlineMeta
  | 	github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:1263
  | github.com/cockroachdb/cockroach/pkg/storage.mvccPutInternal
  | 	github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:1676
  | github.com/cockroachdb/cockroach/pkg/storage.mvccPutUsingIter
  | 	github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:1414
  | github.com/cockroachdb/cockroach/pkg/storage.MVCCPut
  | 	github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:1333
  | github.com/cockroachdb/cockroach/pkg/storage.MVCCPutProto
  | 	github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:841
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).setLastReplicaGCTimestamp
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica.go:1196
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*replicaGCQueue).process
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_gc_queue.go:263
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*baseQueue).processReplica.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/queue.go:997
  | github.com/cockroachdb/cockroach/pkg/util/contextutil.RunWithTimeout
  | 	github.com/cockroachdb/cockroach/pkg/util/contextutil/context.go:91
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*baseQueue).processReplica
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/queue.go:956
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*baseQueue).processLoop.func2.1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/queue.go:874
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:489
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (2) secondary error attachment
  | no data available
  | (1) no data available
  | Error types: (1) syscall.Errno
Wraps: (3) log.Fatal: no data available
Error types: (1) *withstack.withStack (2) *secondary.withSecondaryError (3) *errutil.leafError
-- report composition:
*errutil.leafError: log.Fatal: no data available
*secondary.withSecondaryError
db.go:742: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/util/stop/stopper.go#L488-L490](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/util/stop/stopper.go#L488-L490)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/kv/kvserver/pkg/kv/kvserver/queue.go#L873-L875](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/kv/kvserver/pkg/kv/kvserver/queue.go#L873-L875)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/kv/kvserver/pkg/kv/kvserver/queue.go#L955-L957](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/kv/kvserver/pkg/kv/kvserver/queue.go#L955-L957)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/util/contextutil/context.go#L90-L92](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/util/contextutil/context.go#L90-L92)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/kv/kvserver/pkg/kv/kvserver/queue.go#L996-L998](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/kv/kvserver/pkg/kv/kvserver/queue.go#L996-L998)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/kv/kvserver/pkg/kv/kvserver/replica_gc_queue.go#L262-L264](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/kv/kvserver/pkg/kv/kvserver/replica_gc_queue.go#L262-L264)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/kv/kvserver/pkg/kv/kvserver/replica.go#L1195-L1197](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/kv/kvserver/pkg/kv/kvserver/replica.go#L1195-L1197)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/storage/mvcc.go#L840-L842](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/storage/mvcc.go#L840-L842)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/storage/mvcc.go#L1332-L1334](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/storage/mvcc.go#L1332-L1334)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/storage/mvcc.go#L1413-L1415](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/storage/mvcc.go#L1413-L1415)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/storage/mvcc.go#L1675-L1677](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/storage/mvcc.go#L1675-L1677)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/storage/mvcc.go#L1262-L1264](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/storage/mvcc.go#L1262-L1264)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/storage/pebble.go#L1380-L1382](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/storage/pebble.go#L1380-L1382)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/storage/pebble.go#L1403-L1405](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/storage/pebble.go#L1403-L1405)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L553-L555](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L553-L555)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L741-L743](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L741-L743)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 489
pkg/kv/kvserver/pkg/kv/kvserver/queue.go in pkg/kv/kvserver.(*baseQueue).processLoop.func2.1 at line 874
pkg/kv/kvserver/pkg/kv/kvserver/queue.go in pkg/kv/kvserver.(*baseQueue).processReplica at line 956
pkg/util/contextutil/context.go in pkg/util/contextutil.RunWithTimeout at line 91
pkg/kv/kvserver/pkg/kv/kvserver/queue.go in pkg/kv/kvserver.(*baseQueue).processReplica.func1 at line 997
pkg/kv/kvserver/pkg/kv/kvserver/replica_gc_queue.go in pkg/kv/kvserver.(*replicaGCQueue).process at line 263
pkg/kv/kvserver/pkg/kv/kvserver/replica.go in pkg/kv/kvserver.(*Replica).setLastReplicaGCTimestamp at line 1196
pkg/storage/mvcc.go in pkg/storage.MVCCPutProto at line 841
pkg/storage/mvcc.go in pkg/storage.MVCCPut at line 1333
pkg/storage/mvcc.go in pkg/storage.mvccPutUsingIter at line 1414
pkg/storage/mvcc.go in pkg/storage.mvccPutInternal at line 1676
pkg/storage/mvcc.go in pkg/storage.(*putBuffer).putInlineMeta at line 1263
pkg/storage/pebble.go in pkg/storage.(*Pebble).PutUnversioned at line 1381
pkg/storage/pebble.go in pkg/storage.(*Pebble).put at line 1404
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go in github.com/cockroachdb/pebble.(*DB).Set at line 554
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go in github.com/cockroachdb/pebble.(*DB).Apply at line 742
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v22.2.12 |
| Go Version | go1.19.6 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v22.2.12 |
| Cockroach SHA | feededb3d12a703bada7699b65ad1e191f97a91b |
| # of CPUs | 16 |
| # of Goroutines | 468 |

Jira issue: CRDB-31376

**Comment by yuzefovich** [comment]
dup of #86703
