### ISSUE TITLE
Integer Overflow with Index Hints

### ISSUE THREAD

**Issue by bajinsheng** [cockroachdb/cockroach#110409]
**Describe the problem**

For the same query, running with an index hint returns an error, while running without the hint returns the correct result.

**To Reproduce**

```sql
CREATE TABLE t1 (c0 VARBIT(134), c1 DECIMAL);
CREATE TABLE t3 (c0 TIMESTAMP);
CREATE TABLE t5 (c0 BIT(184));

INSERT INTO t1 (rowid, c1) VALUES(-2125308029, -1799230729);
INSERT INTO t1 (c1) VALUES(-1584079189);
INSERT INTO t3 (rowid, c0) VALUES(-367137600, TIMESTAMP '1970-01-26T01:27:10');
CREATE INDEX ON t1(rowid);

SELECT * FROM t5, t1, t3 WHERE (t3.rowid > SOME (48544246, 1140549043*t1.rowid)); -- {}
SELECT * FROM t1 @{FORCE_INDEX=t1_pkey,DESC}, t5, t3 WHERE (t3.rowid > SOME (48544246, 1140549043*t1.rowid)); -- {ERROR: integer out of range}
```

**Expected behavior**
The second query should return the result as well?

**Additional data / screenshots**

**Environment:**
 - CockroachDB version [ CockroachDB CCL v23.2.0-alpha.00000000-dev-d7738743c955be36b1c9304a40d9e4e7b3edc4ad]
 - Server OS: [Linux/Ubuntu]
 - Client app [`cockroach sql`]

**Additional context**

Jira issue: CRDB-31408

**Comment by mgartner** [comment]
I don't think this is a bug. The optimizer generally does not guarantee the order in which expressions or rows are evaluated, with a few exceptions. Therefore, it is perfectly valid for this query to error some of the time.

A similar case has the same error in Postgres, FWIW:

```
CREATE TABLE t1 (rowid INT8, c0 VARBIT(134), c1 DECIMAL);
CREATE TABLE t3 (rowid INT8, c0 TIMESTAMP);
CREATE TABLE t5 (rowid INT8, c0 BIT(184));

INSERT INTO t1 (rowid, c1) VALUES(-2125308029, -1799230729);
INSERT INTO t1 (rowid, c1) VALUES(967638252729237505, -1584079189);
INSERT INTO t3 (rowid, c0) VALUES(-367137600, TIMESTAMP '1970-01-26T01:27:10');
CREATE INDEX ON t1(rowid);

SELECT * FROM t5, t1, t3 WHERE (t3.rowid > SOME (ARRAY[48544246, 1140549043*t1.rowid]));
```
