### ISSUE TITLE
Ensure CREATE SCHEMA are tested under random schema workload

### ISSUE THREAD

**Issue by Xiang-Gu** [cockroachdb/cockroach#110473]
We implemented/supported CREATE SCHEMA in declarative schema changer during the development cycle for v23.2. We should update the random schema workload to generate and test those cases.

Jira issue: CRDB-31448

Epic CRDB-19168

**Comment by rimadeodhar** [comment]
Support for CREATE SEQUENCE has already been added https://github.com/cockroachdb/cockroach/issues/107361
