### ISSUE TITLE
Ensure ALTER TABLE multiple commands are tested under random schema workload

### ISSUE THREAD

**Issue by Xiang-Gu** [cockroachdb/cockroach#110472]
We implemented/supported ALTER TABLE with multiple ADD COLUMN, DROP COLUMN, ALTER PK commands in declarative schema changer during development cycle for v23.2. We should update the random schema workload to generate and test those cases.

Jira issue: CRDB-31447

Epic CRDB-19168

**Comment by rafiss** [comment]
closing in favor of https://github.com/cockroachdb/cockroach/issues/122249
