### ISSUE TITLE
Ability to flush `security_certificate_expiration_client` metric cache without restarting nodes

### ISSUE THREAD

**Issue by lancel66** [cockroachdb/cockroach#110493]
**Is your feature request related to a problem? Please describe.**
When using the `security_certificate_expiration_client` metric and the certificate id is rotated, the old cert is cached. This results in the `min()` expiry alert being triggered even though the old cert is no longer being used. 

**Describe the solution you'd like**
The operator would like a way to flush the cache so that it can start fresh with new certificates going forward. This would also allow verification that the certificate rotation was successful.

**Describe alternatives you've considered**
Currently, the only way to flush the cache is to restart nodes, which is disruptive to high-traffic clusters.

Jira issue: CRDB-31459
Epic: CRDB-28893

**Comment by rafiss** [comment]
CRDB responds to the SIGHUP signal by refreshing the certificates it has loaded in memory. It could also refresh this certificate cache at the same time.
