### ISSUE TITLE
sql: reduce log frequency of `statistics discarded due to memory limit`

### ISSUE THREAD

**Issue by j82w** [cockroachdb/cockroach#110454]
Problem:
When the statistics memory limit is hit a log message is emitted. This log
occurs for every transaction. This can cause a flood of messages causing 
memory issues, contention, and is not useful at that frequency.

Solution:
Add an internal cluster setting `sql.metrcs.discarded_stats_log.interval` 
to limit how often the log message occurs. 

Informs: https://cockroachlabs.atlassian.net/browse/SREOPS-7255

Jira issue: CRDB-31437

**Comment by maryliag** [comment]
is this a dup of https://github.com/cockroachdb/cockroach/issues/98818 ?
