### ISSUE TITLE
Sentry: crash_reporting.go:390: flow 98ccc2bf: unexpected 51200 leftover bytes
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/util/log/logcrash.ReportOrPanic
  | 	...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#110482]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4472811959/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4472811959/?referrer=webhooks_plugin)

Panic Message:

```
crash_reporting.go:390: flow 98ccc2bf: unexpected 51200 leftover bytes
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/util/log/logcrash.ReportOrPanic
  | 	github.com/cockroachdb/cockroach/pkg/util/log/logcrash/crash_reporting.go:390
  | github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).doStop
  | 	github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:592
  | github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).Stop
  | 	github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:565
  | github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Cleanup
  | 	github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:699
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Cleanup
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:416
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll.func4
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1662
  | github.com/cockroachdb/cockroach/pkg/sql.(*cleanupFuncStack).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/prepared_stmt.go:251
  | github.com/cockroachdb/cockroach/pkg/sql.(*portalPauseInfo).cleanupAll
  | 	github.com/cockroachdb/cockroach/pkg/sql/prepared_stmt.go:373
  | github.com/cockroachdb/cockroach/pkg/sql.(*PreparedPortal).close
  | 	github.com/cockroachdb/cockroach/pkg/sql/prepared_stmt.go:224
  | github.com/cockroachdb/cockroach/pkg/sql.(*prepStmtNamespace).closeAllPortals
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1814
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).commitSQLTransactionInternal
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1301
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).commitSQLTransaction
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1234
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:768
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:142
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2986
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:141
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2181
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2186
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2103
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:900
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:310
  | runtime.goexit
  | 	src/runtime/asm_arm64.s:1172
Wraps: (2) flow 98ccc2bf: unexpected 51200 leftover bytes
Error types: (1) *withstack.withStack (2) *errutil.leafError
-- report composition:
*errutil.leafError: flow 98ccc2bf: unexpected 51200 leftover bytes
crash_reporting.go:390: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_arm64.s#L1171-L1173](src/runtime/asm_arm64.s#L1171-L1173)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/pgwire/conn.go#L309-L311](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/pgwire/conn.go#L309-L311)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/conn_executor.go#L899-L901](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/conn_executor.go#L899-L901)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/conn_executor.go#L2102-L2104](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/conn_executor.go#L2102-L2104)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/conn_executor.go#L2185-L2187](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/conn_executor.go#L2185-L2187)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/conn_executor.go#L2180-L2182](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/conn_executor.go#L2180-L2182)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/conn_executor_exec.go#L140-L142](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/conn_executor_exec.go#L140-L142)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/conn_executor_exec.go#L2985-L2987](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/conn_executor_exec.go#L2985-L2987)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/conn_executor_exec.go#L141-L143](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/conn_executor_exec.go#L141-L143)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/conn_executor_exec.go#L767-L769](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/conn_executor_exec.go#L767-L769)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/conn_executor_exec.go#L1233-L1235](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/conn_executor_exec.go#L1233-L1235)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/conn_executor_exec.go#L1300-L1302](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/conn_executor_exec.go#L1300-L1302)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/conn_executor.go#L1813-L1815](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/conn_executor.go#L1813-L1815)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/prepared_stmt.go#L223-L225](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/prepared_stmt.go#L223-L225)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/prepared_stmt.go#L372-L374](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/prepared_stmt.go#L372-L374)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/prepared_stmt.go#L250-L252](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/prepared_stmt.go#L250-L252)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/distsql_running.go#L1661-L1663](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/distsql_running.go#L1661-L1663)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/colflow/vectorized_flow.go#L415-L417](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/colflow/vectorized_flow.go#L415-L417)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/flowinfra/flow.go#L698-L700](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/sql/flowinfra/flow.go#L698-L700)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/util/mon/bytes_usage.go#L564-L566](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/util/mon/bytes_usage.go#L564-L566)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/util/mon/bytes_usage.go#L591-L593](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/util/mon/bytes_usage.go#L591-L593)
[https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/util/log/logcrash/crash_reporting.go#L389-L391](https://github.com/cockroachdb/cockroach/blob/3bacdbe302c436675605f3256025829e63c45330/pkg/util/log/logcrash/crash_reporting.go#L389-L391)
</details>

```
src/runtime/asm_arm64.s in runtime.goexit at line 1172
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommandsAsync.func1 at line 310
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 900
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 2103
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 2186
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd.func1 at line 2181
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 141
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithProfiling at line 2986
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt.func1 at line 142
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 768
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).commitSQLTransaction at line 1234
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).commitSQLTransactionInternal at line 1301
pkg/sql/conn_executor.go in pkg/sql.(*prepStmtNamespace).closeAllPortals at line 1814
pkg/sql/prepared_stmt.go in pkg/sql.(*PreparedPortal).close at line 224
pkg/sql/prepared_stmt.go in pkg/sql.(*portalPauseInfo).cleanupAll at line 373
pkg/sql/prepared_stmt.go in pkg/sql.(*cleanupFuncStack).run at line 251
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRunAll.func4 at line 1662
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlow).Cleanup at line 416
pkg/sql/flowinfra/flow.go in pkg/sql/flowinfra.(*FlowBase).Cleanup at line 699
pkg/util/mon/bytes_usage.go in pkg/util/mon.(*BytesMonitor).Stop at line 565
pkg/util/mon/bytes_usage.go in pkg/util/mon.(*BytesMonitor).doStop at line 592
pkg/util/log/logcrash/crash_reporting.go in pkg/util/log/logcrash.ReportOrPanic at line 390
```

### Tags

| Tag | Value |
| --- | --- |
| Command | start-single-node |
| Environment | v23.1.6 |
| Go Version | go1.19.10 |
| Platform | darwin arm64 |
| Distribution | CCL |
| Cockroach Release | v23.1.6 |
| Cockroach SHA | 3bacdbe302c436675605f3256025829e63c45330 |
| # of CPUs | 10 |
| # of Goroutines | 447 |

Jira issue: CRDB-31452

**Comment by yuzefovich** [comment]
dup of #110486
