### ISSUE TITLE
Re-review PR #105832 and confirm full test coverage

### ISSUE THREAD

**Issue by Xiang-Gu** [cockroachdb/cockroach#110476]
#105832 added functionalities to automatically repair certain types of descriptor corruptions during an upgrade. In light of [a recent incident](https://cockroachlabs.slack.com/archives/CSPK16V51/p1694449185677029) caused by a bug in that PR but undetected during developement/review. We'd like to re-review that PR to see if we could find out any potential issues/bugs.

The goal is not just to read the PR again, but to confirm that the PR has test coverage for all types of corruption types it will automatically repair.

Jira issue: CRDB-31449

Epic CRDB-28665

**Comment by rafiss** [comment]
@fqazi and I will review this, though if you have any ideas or thoughts, please feel free to share also!

**Comment by fqazi** [comment]
The big gap in the PR was that we only validated the cases that should *cause* repairs, not the cases where the repair should not apply (which was the case that caused us trouble) :(.

**Comment by rafiss** [comment]
Signing off on the other modifications and test coverage in that PR. the other case all check descriptor ID references, or job IDs.
