### ISSUE TITLE
kv: correctly handle lock promotion from SHARED to EXCLUSIVE/INTENT

### ISSUE THREAD

**Issue by arulajmani** [cockroachdb/cockroach#110435]
**Describe the problem**

Locks on a key can be promoted from weaker lock strength to higher lock strengths by re-acquisition. The easiest way to think about this is performing a `SELECT FOR SHARE` followed by a `SELECT FOR UPDATE` or write to the same key. 

Shared locks are compatible with each other, which means multiple transactions can hold shared locks on a particular key. By extension, multiple transactions may attempt to promote their shared lock to something stronger, which can lead to deadlock scenarios. This hazard is best described in the motivation for `UPDATE` locks:

https://github.com/cockroachdb/cockroach/blob/b5cef207d5b5905f8a845da5795f1231c7c7545c/pkg/kv/kvserver/concurrency/lock/locking.proto#L66-L90

There's two things to handle when dealing with shared -> exclusive/intent lock promotions:

1. We should be able to detect the deadlock scenario described above and abort either of the 2 transactions.
2. The ordering of `queuedLockingRequests` should avoid deadlocks, when possible[*].

This issue is about doing both. However, until then, all lock promotion requests should be rejected.

----

 [*] Consider the following construction. Note that the current queueing order of `queuedLockingRequests` is based a request's sequence number, which is assigned when a request enters the lock table, from a monotonically increasing counter.

```
key: a
- locks: [txn1 shared]
- queuedLockingRequests: [r1: txn2 exclusive <seq: 2>] [r2: txn1 exclusive <seq: 3>]
```

This is an avoidable deadlock, induced by the queueing order of the `queuedLockingRequest's` lock wait queue. 

@nvanbenschoten and I previously discussed how to get around this issue, and one way to do so is by changing the lock wait queue's ordering property -- instead of ordering just by sequence number, we could instead order requests by (alreadyHoldsLock, SequenceNumber). Doing this in the above example would mean r2 would sort before r1, and we'd avoid the deadlock.

Jira issue: CRDB-31427
Epic: CRDB-34172

**Comment by michae2** [comment]
Here's a demonstration:

```sql
CREATE TABLE ab (a INT PRIMARY KEY, b INT);
INSERT INTO ab VALUES (0, 1);
SET CLUSTER SETTING sql.txn.read_committed_isolation.enabled = true;

-- session 1
SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL READ COMMITTED;
BEGIN;
SELECT * FROM ab FOR SHARE;

-- session 2
SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL READ COMMITTED;
-- this blocks on the shared lock
SELECT * FROM ab FOR UPDATE;

-- session 1 again
-- this fails with "ERROR: lock promotion from Shared to Exclusive is not allowed"
SELECT * FROM ab FOR UPDATE;
```

**Comment by tyranron** [comment]
Did this make into 23.2.3? Cannot track any tags on the https://github.com/cockroachdb/cockroach/commit/5ae79f13b1d942482c1964d4b1b7af6da46832ce.
