### ISSUE TITLE
sql: non-deterministic allocation of desc IDs after a 3-node TestCluster initialization

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#110499]
**Describe the problem**

Found in #110242: after the TestDataDriven initializes a 3-node cluster (and NOT in the 1-node case), the test sometime fails while expecting the initial table to be generated with ID N, and sees instead ID N+1 or N+2.

This only occurs in CI -- cannot be reproduced locally under stress.

We can work around the issue by normalizing the expected table ID in the test (to become agnostic of the numeric value) **however the fact that there is unstable ID allocaiton in a 3-node TestCluster is abnormal and unexpected.**

**To Reproduce**

Take the code from #110492
Remove the ID normalization that was added in that PR.
Then exercise the test in CI (presumably it does not fail when run locally)

**Expected behavior**

We want to understand what is the source of the non-determinism here.

(NB: this issue is not about fixing the situation for the tests. The proper longer-term fix will be a combination of #110491  and ensure that all test expectations use names from that change.)

Jira issue: CRDB-31461

**Comment by rafiss** [comment]
I think we figured this one out - @ecwall fixed this by making the test use the `TransactionalDescIDGenerator ` https://github.com/cockroachdb/cockroach/pull/110829
