### ISSUE TITLE
kv: TestKVNemesisMultiNode failed in CI

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#110457]
https://teamcity.cockroachdb.com/viewLog.html?buildId=11740779&buildTypeId=Cockroach_BazelEssentialCi

Jira issue: CRDB-31440

**Comment by andrewbaptist** [comment]
dupe of #110519

**Comment by nvanbenschoten** [comment]
Closing as a duplicate of https://github.com/cockroachdb/cockroach/issues/110519.
