### ISSUE TITLE
kvserver: verify roachpb.Value checksums when building snapshots

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#110572]
With storage corruption, it's possible for the corruption to spread via Raft snapshots before the consistency checker detects it. We saw this possibly happen in https://github.com/cockroachlabs/support/issues/2583. To avoid this, we should check roachpb.Value checksums when sending snapshots.

Related to #93519.

Jira issue: CRDB-31510

**Comment by erikgrinaker** [comment]
> one solution is for each compaction/flush to verify the sstable after it has written it

I think we want CRDB-level verification here rather than Pebble-level verification though (i.e. end-to-end roachpb.Value checksums rather than SST checksums). In the motivating case here, the SST was presumably intact (otherwise Pebble would have errored when opening it), so the corruption likely happened below Raft replication but above Pebble. Are you suggesting some sort of hook where CRDB can verify roachpb.Value checksums during or after the SST is written?

**Comment by jbowens** [comment]
@erikgrinaker We’re looking at replacing roachpb.Value checksums with per-KV checksums that are end-to-end and fill existing roachpb.Value checksum gaps (they’re not used for MVCC tombstones, Pebble tombstones, timeseries keys, internal key trailers, etc.). Pebble will have direct support for accepting checksums from Cockroach, persisting them, verifying them in persisted data, and surfacing them back out the other end. We’re still exploring designs and some of the thinking is captured in that google doc and some in #111001.

**Comment by erikgrinaker** [comment]
Ah, I see, promising! I imagine this will still be some ways off, i.e. not shipping in 24.1? In that case, we'll probably want to add roachpb.Value checksum verification in the interim, as a cheap guard.

**Comment by lyang24** [comment]
Hi, I would like to contribute to this issue.

trying to decipher of the information provided - we want to add a verification on roachpb.Value when building snapshots to catch data corruption issues before consistent checker.

from reading the code I gathered these information:
- [building snapshots](https://github.com/lyang24/cockroach/blob/aa6d150bd6e25be23d3dafb7432f806bc6bb553c/pkg/kv/kvserver/store_snapshot.go#L695-L922)
- [roachpb.Value verify checksum verification](https://github.com/lyang24/cockroach/blob/b468d1a9248994bd32b8254370fdde483bf31cb2/pkg/roachpb/data.go#L319-L333)
- [how does consistency checker get checksums](https://github.com/lyang24/cockroach/blob/3f0b37af29fd4eb15599c44d73dc237dd33e0b1a/pkg/kv/kvserver/replica_consistency.go#L387-L431)

I wonder if convert the value from the [visitor] (https://github.com/lyang24/cockroach/blob/aa6d150bd6e25be23d3dafb7432f806bc6bb553c/pkg/kv/kvserver/store_snapshot.go#L777-L818) and convert the `[]bytes` into roachpb.Value and call the `verify` method is in the ball park of the end goal here?
