### ISSUE TITLE
"git pull" has one problem

### ISSUE THREAD

**Issue by fjjiaboming** [cockroachdb/cockroach#1105]
.git/hooks/post-merge: line 9: glock: command not found

when I do git pull.

**Comment by ngaut** [comment]
You could install glock manually. Please refer to https://github.com/robfig/glock

**Comment by bdarnell** [comment]
You need to have `$GOPATH/bin` on your `$PATH`. Once you have that everything should be set up automatically the first time you run `make`.

**Comment by fjjiaboming** [comment]
@ngaut   Thanks. 
@bdarnell  I have already added the path.

**Comment by petermattis** [comment]
`glock` is installed by `build/devbase/godeps.sh` which should be run the first time you run `make`. And the `make` invocation is also what installs the `post-merge` git hook. So mildly confusing how you got into this state, but manually running `build/devbase/godeps.sh` might fix it.
