### ISSUE TITLE
changefeedccl: Add syntax for newly supported sinks

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#110558]
We need to add a new sink syntax format for multiple sinks in 23.2. Batching them into one issue as they should probably be done together:
- https://github.com/cockroachdb/cockroach/issues/105226
- https://github.com/cockroachdb/cockroach/issues/103901

Jira issue: CRDB-31504

**Comment by wenyihu6** [comment]
Closed as completed by https://github.com/cockroachdb/cockroach/pull/115806.
