### ISSUE TITLE
Add test to check nested calls to encrypt/decrypt work as expected

### ISSUE THREAD

**Issue by rimadeodhar** [cockroachdb/cockroach#110615]
We should add a test to verify calling column level encryption/decryption built ins in a nest way works as expected.

Jira issue: CRDB-31524

**Comment by andyyang890** [comment]
Considering that each layer of encrypt/decrypt calls is independent from each other, I'm not really sure this is a useful case to test. You can consider the output of the first layer of encryption to be a fresh input to the second layer and so as long as one layer of encryption/decryption works then it should work for any number of layers.

Was there a particular concern about multiple encryption that we wanted to test?

**Comment by rafiss** [comment]
I think the fuzz testing you've done, and the point you make about how the input to the function is independent of where the input came from are enough reason to close this.
