### ISSUE TITLE
X.509: Extend SQL user mapping to include multiple certificate attributes and not just CN

### ISSUE THREAD

**Issue by sheaffej** [cockroachdb/cockroach#110616]
A CockroachDB enterprise customer requests extending the X.509 certificate authentication system to be able to identify SQL users by a hash of specific certificate attributes and values instead of just the CN= attribute.

Simple example:

```
CREATE USER app_user_2343423 WITH SUBJECT
'O="ACME, Inc.", OU="Order Processing Team", UID=32b5546c-f019-448c-9cd4-1394f6d3a478, CN=root';
```

In this case, if the cert presented by the client has:
```
O=ACME, Inc.
OU=Order Processing Team
UID=32b5546c-f019-448c-9cd4-1394f6d3a478
CN=root
```
Then it will be used to authenticate the SQL user `app_user_2343423`.

The list of required cert attributes would be organization defined, and could include any combination of attributes. In the example above, CN=root was used specifically to illustrate a point that this certificate would not be used to log in the SQL `root` user.

**Justification:**

Some companies have internal CAs that must be used for all certificate-based authentication, and the specific enterprise customer who requested this has a CA that does not use CN= to uniquely identify a principle. The CA instead uses a combination of OU= and UID= to uniquely identify a principle, and therefore allows the certificate requestor to request any value for CN=.

This request has similar motivations to other requests submitted:
https://github.com/cockroachdb/cockroach/issues/50719
https://github.com/cockroachdb/cockroach/issues/28408

The common problem here is a mismatch between what the CA uses to uniquely identify a principle (i.e. OU=, UID= ) and what CockroachDB expects to be the unique principle name (i.e. CN= ). 

Since the CA is used company-wide at the center of this enterprise company's security infrastructure, it's not feasible for them to change the processes around how the CA issues certificates (specifically forcing the principle to put their unique identity in the CN). However if CockroachDB could be extended to consider multiple attributes in the X.509 certificate when identifying the SQL user to authenticate, then CockroachDB could be used with CAs that use other attributes other than CN to uniquely identify a principle.

Jira issue: CRDB-31525

gz#18603

Epic CRDB-34126

**Comment by knz** [comment]
The ask is generally reasonable, although we would probably implement this using a combination of the ident_map and HBA systems.

Something like:

```sql
set cluster setting server.host_based_authentication.configuration = '
host all all all cert map=acme,ident=x509_fields
';

set cluster setting server.identity_map.configuration = '
acme "O="ACME, Inc.", OU="Order Processing Team", UID=(.*), CN=root"  app_user_\1
';
```

i.e.
- use `map=acme` to point the HBA matching rule to a set of rules in identity_map
- new HBA config option `ident=x509_fields` which feeds the X509 field representation as input to the identity map algorithm
- ident map in `identity_map` cluster setting matches the X509 field names to a SQL username using a regexp as usual

**Comment by knz** [comment]
I wonder however, if their customer is very attached to their corporate IT requirements, if they would be satisfied in a solution here without also solving #50719 . Thoughts?

**Comment by sheaffej** [comment]
@knz good question. I recommend we focus on this issue (https://github.com/cockroachdb/cockroach/issues/110616), and then we could consider closing/canceling https://github.com/cockroachdb/cockroach/issues/50719. 

https://github.com/cockroachdb/cockroach/issues/50719 was an issue I filed for the same customer, for the same underlying problem they have described in this issue. But https://github.com/cockroachdb/cockroach/issues/50719 was my attempt at proposing a solution 3 years ago.

This issue (https://github.com/cockroachdb/cockroach/issues/110616) was a direct request by the customer this month, and matches how they handle their corporate certs with Oracle today.

**Comment by dikshant** [comment]
https://github.com/cockroachdb/cockroach/pull/119958 was recently merged so we now have the ability to match on SUBJECT.
