### ISSUE TITLE
schema: Update mixed version tests for decl. schema changer

### ISSUE THREAD

**Issue by rimadeodhar** [cockroachdb/cockroach#110613]
We have expanded DDLs supported by the decl. schema changer in 22.2, 23.1 and 23.2. However, this mixed version tests haven't been updated to cover the new DDLs supported. We should expand the coverage of those mixed version tests to cover everything that declarative schema changer does.

Jira issue: CRDB-31522

**Comment by rafiss** [comment]
This should be covered by CRDB-19168, which is the epic to add more DDLs to the schema change workload. Once it's in the workload, the mixed-version workload tests will automatically start testing it.
