### ISSUE TITLE
Sentry: panic.go:884: panic: ×
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).regi...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#110725]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4480492309/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4480492309/?referrer=webhooks_plugin)

Panic Message:

```
panic.go:884: panic: ×
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).registerWithRangefeedRaftMuLocked
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_rangefeed.go:416
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).rangeFeedWithRangeID
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_rangefeed.go:228
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).RangeFeed
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_rangefeed.go:139
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).RangeFeed
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store.go:3163
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Stores).RangeFeed
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/stores.go:252
  | github.com/cockroachdb/cockroach/pkg/server.(*Node).singleRangeFeed
  | 	github.com/cockroachdb/cockroach/pkg/server/node.go:1319
  | github.com/cockroachdb/cockroach/pkg/server.(*Node).RangeFeed
  | 	github.com/cockroachdb/cockroach/pkg/server/node.go:1313
  | github.com/cockroachdb/cockroach/pkg/roachpb._Internal_RangeFeed_Handler
  | 	github.com/cockroachdb/cockroach/pkg/roachpb/bazel-out/k8-opt/bin/pkg/roachpb/roachpb_go_proto_/github.com/cockroachdb/cockroach/pkg/roachpb/api.pb.go:9627
  | github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor.StreamServerInterceptor.func1
  | 	github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go:163
  | google.golang.org/grpc.chainStreamInterceptors.func1.1
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1408
  | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func4
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:272
  | google.golang.org/grpc.chainStreamInterceptors.func1.1
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1411
  | github.com/cockroachdb/cockroach/pkg/rpc.kvAuth.streamInterceptor
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/auth.go:99
  | google.golang.org/grpc.chainStreamInterceptors.func1.1
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1411
  | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func2.1
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:241
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:341
  | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:240
  | google.golang.org/grpc.chainStreamInterceptors.func1.1
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1411
  | google.golang.org/grpc.chainStreamInterceptors.func1
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1413
  | google.golang.org/grpc.(*Server).processStreamingRPC
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1549
  | google.golang.org/grpc.(*Server).handleStream
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1624
  | google.golang.org/grpc.(*Server).serveStreams.func1.2
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:922
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (2) panic: ×
Error types: (1) *withstack.withStack (2) *errutil.leafError
-- report composition:
*errutil.leafError: panic: ×
panic.go:884: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L921-L923](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L921-L923)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1623-L1625](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1623-L1625)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1548-L1550](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1548-L1550)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1412-L1414](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1412-L1414)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1410-L1412](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1410-L1412)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/rpc/pkg/rpc/context.go#L239-L241](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/rpc/pkg/rpc/context.go#L239-L241)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/util/stop/stopper.go#L340-L342](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/util/stop/stopper.go#L340-L342)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/rpc/pkg/rpc/context.go#L240-L242](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/rpc/pkg/rpc/context.go#L240-L242)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1410-L1412](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1410-L1412)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/rpc/pkg/rpc/auth.go#L98-L100](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/rpc/pkg/rpc/auth.go#L98-L100)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1410-L1412](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1410-L1412)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/rpc/pkg/rpc/context.go#L271-L273](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/rpc/pkg/rpc/context.go#L271-L273)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1407-L1409](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1407-L1409)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go#L162-L164](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go#L162-L164)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/roachpb/bazel-out/k8-opt/bin/pkg/roachpb/roachpb_go_proto_/github.com/cockroachdb/cockroach/pkg/roachpb/api.pb.go#L9626-L9628](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/roachpb/bazel-out/k8-opt/bin/pkg/roachpb/roachpb_go_proto_/github.com/cockroachdb/cockroach/pkg/roachpb/api.pb.go#L9626-L9628)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/server/node.go#L1312-L1314](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/server/node.go#L1312-L1314)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/server/node.go#L1318-L1320](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/server/node.go#L1318-L1320)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/kv/kvserver/pkg/kv/kvserver/stores.go#L251-L253](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/kv/kvserver/pkg/kv/kvserver/stores.go#L251-L253)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/kv/kvserver/pkg/kv/kvserver/store.go#L3162-L3164](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/kv/kvserver/pkg/kv/kvserver/store.go#L3162-L3164)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/kv/kvserver/pkg/kv/kvserver/replica_rangefeed.go#L138-L140](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/kv/kvserver/pkg/kv/kvserver/replica_rangefeed.go#L138-L140)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/kv/kvserver/pkg/kv/kvserver/replica_rangefeed.go#L227-L229](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/kv/kvserver/pkg/kv/kvserver/replica_rangefeed.go#L227-L229)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/kv/kvserver/pkg/kv/kvserver/replica_rangefeed.go#L415-L417](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/kv/kvserver/pkg/kv/kvserver/replica_rangefeed.go#L415-L417)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.(*Server).serveStreams.func1.2 at line 922
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.(*Server).handleStream at line 1624
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.(*Server).processStreamingRPC at line 1549
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.chainStreamInterceptors.func1 at line 1413
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.chainStreamInterceptors.func1.1 at line 1411
pkg/rpc/pkg/rpc/context.go in pkg/rpc.NewServerEx.func2 at line 240
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunTaskWithErr at line 341
pkg/rpc/pkg/rpc/context.go in pkg/rpc.NewServerEx.func2.1 at line 241
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.chainStreamInterceptors.func1.1 at line 1411
pkg/rpc/pkg/rpc/auth.go in pkg/rpc.kvAuth.streamInterceptor at line 99
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.chainStreamInterceptors.func1.1 at line 1411
pkg/rpc/pkg/rpc/context.go in pkg/rpc.NewServerEx.func4 at line 272
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.chainStreamInterceptors.func1.1 at line 1408
pkg/util/tracing/grpcinterceptor/grpc_interceptor.go in pkg/util/tracing/grpcinterceptor.StreamServerInterceptor.func1 at line 163
pkg/roachpb/bazel-out/k8-opt/bin/pkg/roachpb/roachpb_go_proto_/github.com/cockroachdb/cockroach/pkg/roachpb/api.pb.go in pkg/roachpb._Internal_RangeFeed_Handler at line 9627
pkg/server/node.go in pkg/server.(*Node).RangeFeed at line 1313
pkg/server/node.go in pkg/server.(*Node).singleRangeFeed at line 1319
pkg/kv/kvserver/pkg/kv/kvserver/stores.go in pkg/kv/kvserver.(*Stores).RangeFeed at line 252
pkg/kv/kvserver/pkg/kv/kvserver/store.go in pkg/kv/kvserver.(*Store).RangeFeed at line 3163
pkg/kv/kvserver/pkg/kv/kvserver/replica_rangefeed.go in pkg/kv/kvserver.(*Replica).RangeFeed at line 139
pkg/kv/kvserver/pkg/kv/kvserver/replica_rangefeed.go in pkg/kv/kvserver.(*Replica).rangeFeedWithRangeID at line 228
pkg/kv/kvserver/pkg/kv/kvserver/replica_rangefeed.go in pkg/kv/kvserver.(*Replica).registerWithRangefeedRaftMuLocked at line 416
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
```

### Tags

| Tag | Value |
| --- | --- |
| Command | demo |
| Environment | v22.2.0 |
| Go Version | go1.19.1 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v22.2.0 |
| Cockroach SHA | 77667a1b0101cd323090011f50cf910aaa933654 |
| # of CPUs | 2 |
| # of Goroutines | 568 |

Jira issue: CRDB-31579

**Comment by yuzefovich** [comment]
unactionable
