### ISSUE TITLE
sql: pg_typeof always return bigint for small integer values

### ISSUE THREAD

**Issue by giangpham712** [cockroachdb/cockroach#110785]
**Describe the problem**

Queries such as

```
SELECT CASE
    WHEN g0."Nickname" IS NOT NULL AND g0."SquadId" IS NOT NULL THEN (g0."Nickname", pg_typeof(5))
    ELSE NULL
END
FROM "Gears" AS g
LEFT JOIN "Gears" AS g0 ON g."HasSoulPatch"
ORDER BY g0."Nickname" NULLS FIRST;
```

returns

```
          case
-------------------------
  NULL
  NULL
  NULL
  (Baird,bigint)
  (Baird,bigint)
  ("Cole Train",bigint)
  ("Cole Train",bigint)
...
```

**Additional context**
This affects efcore.pg tests

@fqazi 

Jira issue: CRDB-31614

**Comment by rafiss** [comment]
The underlying reason for this is https://github.com/cockroachdb/cockroach/issues/48613 and https://github.com/cockroachdb/cockroach/issues/58252. We won't be able to address these easily. For now would you be able to skip the test, or adjust the expectation for CRDB?
