### ISSUE TITLE
ttl: handleTTLStorageParamChange might return incorrect `descriptorChanged` value

### ISSUE THREAD

**Issue by Xiang-Gu** [cockroachdb/cockroach#110727]
Following up discussion in https://github.com/cockroachdb/cockroach/pull/110252, [here](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/alter_table.go#L474-L484) is an example where a mutation is enqueued and `descriptorChanged` is set to true (ALTER PK is achieved by enqueuing a PrimaryIndexSwap mutation).

The reason such an issue is filed is concerning `handleTTLStorageParamChange()`,  in which `descriptorChanged` can be false even if a mutation is enqueued.

**Comment by rafiss** [comment]
@Xiang-Gu is there any risk in just fixing this so `descriptorChanged` is set appropriately?

**Comment by rafiss** [comment]
> [here](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/alter_table.go?rgh-link-date=2023-09-15T16%3A29%3A15Z#L474-L484) is an example where a mutation is enqueued and descriptorChanged is set to true

Looking at this closer, it seems like `p.AlterPrimaryKey` does _both_: it modifies the descriptor directly, and also enqueues a mutation. As Evan mentioned elsewhere, based on the usage of `descriptorChanged`, it only needs to be set if no mutations are added: https://github.com/cockroachdb/cockroach/blob/1755d671f15bfa3a4d111678aca5d022e1a3163a/pkg/sql/alter_table.go#L849
