### ISSUE TITLE
ttljob: investigate "could not register flowID because the registry is draining" error

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#110823]
A cluster encountered this error:
```
ROW LEVEL TTL job 899375493495848962: stepping through state failed with unexpected error: could not register flowID because the registry is draining
(1)
```

https://cockroachlabsgcp.splunkcloud.com/en-US/app/search/search?earliest=1694444400&latest=1695052327&q=search%20index%3Dcc-app-crdb*%20severity%3DERROR%20%22row%20level%20ttl%22%20%22stepping%20through%20state%20failed%22%20%7C%20timechart%20span%3D1h%20count%20by%20friendly_id&display.page.search.mode=verbose&dispatch.sample_ratio=1&display.general.type=statistics&display.page.search.tab=events&workload_pool=standard_perf&sid=1695052417.480201

We may be missing a check for how the job should behave when a node is shutting down, or there may be an underlying issue with the flow registry. Investigate the error and check if the SQL Queries team can help. If this is expected, then let's not log it as an error.

Jira issue: CRDB-31638

**Comment by rafiss** [comment]
@mgartner could you help us determine how to handle the `could not register flowID because the registry is draining` error that comes from DistSQL? Is it something that doesn't need to be logged as an error?

**Comment by mgartner** [comment]
cc @yuzefovich do you happen to know?

**Comment by yuzefovich** [comment]
Here is the full stack trace:
```
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowRegistry).RegisterFlow
  | 	github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow_registry.go:303
  | github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).StartInternal
  | 	github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:407
  | github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:474
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:757
  | github.com/cockroachdb/cockroach/pkg/sql/ttl/ttljob.rowLevelTTLResumer.Resume.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/ttl/ttljob/ttljob.go:339
  | github.com/cockroachdb/cockroach/pkg/sql/ttl/ttljob.rowLevelTTLResumer.Resume
  | 	github.com/cockroachdb/cockroach/pkg/sql/ttl/ttljob/ttljob.go:351
  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine.func2
  | 	github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1267
  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine
  | 	github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1268
  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).runJob
  | 	github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:410
  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).resumeJob.func1
  | 	github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:330
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:489
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (3) could not register flowID because the registry is draining
```
I believe that this tells us is that the node that was chosen to be the gateway for the TTL job is in "draining" state. (This is the case since the error originates directly from `Run` - `StartInternal` - `RegisterFlow` code path rather than something that involves an inbox / outbox pair.)

Other jobs (e.g. import and backup/restore) use `joberror.IsPermanentBulkJobError` helper to see if it's a permanent job error and return a job retryable error if not. I think we need to do similar in the TTL job code path.

**Comment by rafiss** [comment]
I'm closing this as won't fix, since this error hasn't appeared in 3 months, so it doesn't seem worth prioritizing.

**Comment by rafiss** [comment]
Happened again here: https://cockroachlabsgcp.splunkcloud.com/en-US/app/search/search?earliest=-7d%40h&latest=now&q=search%20index%3Dcc-app-crdb*%20severity%3DERROR%20%22row%20level%20ttl%22%20%22stepping%20through%20state%20failed%22%20%7C%20timechart%20span%3D1h%20count%20by%20friendly_id&display.page.search.mode=verbose&dispatch.sample_ratio=1&display.general.type=statistics&display.page.search.tab=events&sid=1705422359.939408&workload_pool=standard_perf

I'll check where we can mark this error as retryable.
