### ISSUE TITLE
backupccl: v23.1.8: found MULTIREGION_ENUM on non-multi-region database

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#110847]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4487112681/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4487112681/?referrer=webhooks_plugin)

Panic Message:

```
restore_job.go:1026: found MULTIREGION_ENUM on non-multi-region database ×
(1)
Wraps: (2) assertion failure
Wraps: (3) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/ccl/backupccl.createImportingDescriptors.func1
  | 	github.com/cockroachdb/cockroach/pkg/ccl/backupccl/restore_job.go:1026
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).DescsTxn.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1610
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).txn.func4
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1698
  | github.com/cockroachdb/cockroach/pkg/kv.runTxn.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:965
  | github.com/cockroachdb/cockroach/pkg/kv.(*Txn).exec
  | 	github.com/cockroachdb/cockroach/pkg/kv/txn.go:928
  | github.com/cockroachdb/cockroach/pkg/kv.runTxn
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:964
  | github.com/cockroachdb/cockroach/pkg/kv.(*DB).TxnWithAdmissionControl
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:927
  | github.com/cockroachdb/cockroach/pkg/kv.(*DB).Txn
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:902
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).txn
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1686
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).DescsTxn
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1608
  | github.com/cockroachdb/cockroach/pkg/ccl/backupccl.createImportingDescriptors
  | 	github.com/cockroachdb/cockroach/pkg/ccl/backupccl/restore_job.go:998
  | github.com/cockroachdb/cockroach/pkg/ccl/backupccl.(*restoreResumer).doResume
  | 	github.com/cockroachdb/cockroach/pkg/ccl/backupccl/restore_job.go:1562
  | github.com/cockroachdb/cockroach/pkg/ccl/backupccl.(*restoreResumer).Resume
  | 	github.com/cockroachdb/cockroach/pkg/ccl/backupccl/restore_job.go:1499
  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine.func2
  | 	github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1628
  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine
  | 	github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1629
  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).runJob
  | 	github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:474
  | github.com/cockroachdb/cockroach/pkg/jobs.(*StartableJob).Start.func2
  | 	github.com/cockroachdb/cockroach/pkg/jobs/jobs.go:978
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (4) found MULTIREGION_ENUM on non-multi-region database ×
Error types: (1) *colexecerror.notInternalError (2) *assert.withAssertionFailure (3) *withstack.withStack (4) *errutil.leafError
-- report composition:
*errutil.leafError: found MULTIREGION_ENUM on non-multi-region database ×
restore_job.go:1026: *withstack.withStack (top exception)
*assert.withAssertionFailure
*colexecerror.notInternalError
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/util/stop/stopper.go#L469-L471](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/util/stop/stopper.go#L469-L471)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/jobs/jobs.go#L977-L979](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/jobs/jobs.go#L977-L979)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/jobs/adopt.go#L473-L475](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/jobs/adopt.go#L473-L475)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/jobs/registry.go#L1628-L1630](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/jobs/registry.go#L1628-L1630)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/jobs/registry.go#L1627-L1629](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/jobs/registry.go#L1627-L1629)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/ccl/backupccl/restore_job.go#L1498-L1500](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/ccl/backupccl/restore_job.go#L1498-L1500)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/ccl/backupccl/restore_job.go#L1561-L1563](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/ccl/backupccl/restore_job.go#L1561-L1563)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/ccl/backupccl/restore_job.go#L997-L999](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/ccl/backupccl/restore_job.go#L997-L999)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/sql/internal.go#L1607-L1609](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/sql/internal.go#L1607-L1609)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/sql/internal.go#L1685-L1687](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/sql/internal.go#L1685-L1687)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/db.go#L901-L903](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/db.go#L901-L903)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/db.go#L926-L928](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/db.go#L926-L928)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/db.go#L963-L965](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/db.go#L963-L965)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/txn.go#L927-L929](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/txn.go#L927-L929)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/db.go#L964-L966](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/db.go#L964-L966)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/sql/internal.go#L1697-L1699](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/sql/internal.go#L1697-L1699)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/sql/internal.go#L1609-L1611](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/sql/internal.go#L1609-L1611)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/ccl/backupccl/restore_job.go#L1025-L1027](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/ccl/backupccl/restore_job.go#L1025-L1027)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 470
pkg/jobs/jobs.go in pkg/jobs.(*StartableJob).Start.func2 at line 978
pkg/jobs/adopt.go in pkg/jobs.(*Registry).runJob at line 474
pkg/jobs/registry.go in pkg/jobs.(*Registry).stepThroughStateMachine at line 1629
pkg/jobs/registry.go in pkg/jobs.(*Registry).stepThroughStateMachine.func2 at line 1628
pkg/ccl/backupccl/restore_job.go in pkg/ccl/backupccl.(*restoreResumer).Resume at line 1499
pkg/ccl/backupccl/restore_job.go in pkg/ccl/backupccl.(*restoreResumer).doResume at line 1562
pkg/ccl/backupccl/restore_job.go in pkg/ccl/backupccl.createImportingDescriptors at line 998
pkg/sql/internal.go in pkg/sql.(*InternalDB).DescsTxn at line 1608
pkg/sql/internal.go in pkg/sql.(*InternalDB).txn at line 1686
pkg/kv/db.go in pkg/kv.(*DB).Txn at line 902
pkg/kv/db.go in pkg/kv.(*DB).TxnWithAdmissionControl at line 927
pkg/kv/db.go in pkg/kv.runTxn at line 964
pkg/kv/txn.go in pkg/kv.(*Txn).exec at line 928
pkg/kv/db.go in pkg/kv.runTxn.func1 at line 965
pkg/sql/internal.go in pkg/sql.(*InternalDB).txn.func4 at line 1698
pkg/sql/internal.go in pkg/sql.(*InternalDB).DescsTxn.func1 at line 1610
pkg/ccl/backupccl/restore_job.go in pkg/ccl/backupccl.createImportingDescriptors.func1 at line 1026
```

### Tags

| Tag | Value |
| --- | --- |
| Command | start-single-node |
| Environment | v23.1.8 |
| Go Version | go1.19.10 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.8 |
| Cockroach SHA | 2c1d4afd2c2de091a00a4dba4392ceeaf8504a95 |
| # of CPUs | 16 |
| # of Goroutines | 487 |

Jira issue: CRDB-31647

**Comment by msbutler** [comment]
This is most likely a sentry report of the following escalation https://cockroachdb.zendesk.com/agent/tickets/18650, where a user attempted to restore a MR backup onto a single region cluster. 

cc @cockroachdb/sql-foundations in case they want to look at this report.
