### ISSUE TITLE
c2c: large fingerprint with revision history can fail because it scans data eligible for gc

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#110811]
Large fingerprints that scan tables with revision history and a low ttl can fail with an error that looks like:
```
batch timestamp 1694754479.017002000,1 must be after replica GC threshold 1694770486.168134968,0
```
This error indicates that the fingerprint is scanning data eligible for gc. 

To fix, we'll need to lay a Protected Timestamp on the span we're fingerprinting. To easily manage this PTS, we ought to jobify the fingerprinting command. 

Jira issue: CRDB-31629

**Comment by dt** [comment]
> we ought to jobify the fingerprinting command.

Eh, can we make the PTS be owned by the session or something instead? A job is a pretty heavy handed solution and tends to make it slower to get the result; I'm hesitant to use a job unless we need persisted state and durable execution.

**Comment by msbutler** [comment]
I like the idea of jobifying fingerprinting for the same reason we wanted to jobify export: it's a long running query, that takes the around the time a backup would, so its more susceptible to ephemeral errors.

**Comment by msbutler** [comment]
assigning to @adityamaru because he knows how to implement it
