### ISSUE TITLE
Set public = t for sql.stats.aggregation.interval cluster setting

### ISSUE THREAD

**Issue by florence-crl** [cockroachdb/cockroach#110941]
This setting needs to be documented according to [DOC-8201](https://cockroachlabs.atlassian.net/browse/DOC-8201):

```
sql.stats.aggregation.interval
```

However it is not publicly documented on [the cluster settings page](https://www.cockroachlabs.com/docs/v23.1/cluster-settings) because it has public = f in `crdb_internal.cluster_settings`. The cluster settings page is automatically generated with settings where public = t.

Describe the solution you'd like
Please set public = t for the above cluster setting.

Jira issue: CRDB-31682

**Comment by maryliag** [comment]
the reason we don't make it public is because we don't recommend this value being changed, and there would be other places that need to be adjusted if this value changed.
So I will close this issue as we don't want to make this public (at least in the near future)
