### ISSUE TITLE
upgrades: Add sanity check that we only repair descriptors that show up in invalid_objects table.

### ISSUE THREAD

**Issue by rimadeodhar** [cockroachdb/cockroach#110906]
We should add a sanity check within the automated descriptor corruption repair that ensures we only attempt repairs for descriptors that show up in the `invalid_objects` table.

Jira issue: CRDB-31670

**Comment by rimadeodhar** [comment]
Follow up for https://cockroachlabs.atlassian.net/wiki/spaces/SQLEXP/pages/edit-v2/3170337096

**Comment by rafiss** [comment]
We could also consider using the repairable_catalog_corruptions table.

**Comment by rafiss** [comment]
I see that the repair step already has this: https://github.com/cockroachdb/cockroach/blob/be961bf36f01162a0787c6d81be2d2be1016ff58/pkg/upgrade/upgrades/first_upgrade.go#L58C1-L61C4

That check should cause the code to short-circuit for any descriptor that is not invalid. Let's confirm if that is true - if so, we could try adding a test to assert that, and close this out.
