### ISSUE TITLE
spanconfig: remove systemSpanConfigStore

### ISSUE THREAD

**Issue by andrewbaptist** [cockroachdb/cockroach#110999]
`systemSpanConfigStore` is no longer required

TODO: Fill in details of why.

Jira issue: CRDB-31708

**Comment by arulajmani** [comment]
Copy pasting my comment from #110253:

I don't think that's quite right -- systemSpanConfigStore is used by protected timestamps, and that things legit. I don't think we want to get rid of it.

I meant we should get rid of the SystemConfig(see pkg/config/system.go) which was used by KV to access zone configurations prior to the introduction of SpanConfigurations. Sorry for not being clearer, these are confusingly named.
