### ISSUE TITLE
Sentry: store_raft.go:466: log.Fatal: while applying snapshot: while ingesting [× × × × × ×]: link × ×: operation not permitted
(1) attached stack trace
  -- stack trace:
  | github.com/cockro...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#110954]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4490613360/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4490613360/?referrer=webhooks_plugin)

Panic Message:

```
store_raft.go:466: log.Fatal: while applying snapshot: while ingesting [× × × × × ×]: link × ×: operation not permitted
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processRaftSnapshotRequest.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:466
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).withReplicaForRequest
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:343
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processRaftSnapshotRequest
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:406
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).receiveSnapshot
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_snapshot.go:1091
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).HandleSnapshot.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:211
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:322
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).HandleSnapshot
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:208
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*RaftTransport).RaftSnapshot
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/raft_transport.go:382
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver._MultiRaft_RaftSnapshot_Handler
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/bazel-out/k8-opt/bin/pkg/kv/kvserver/kvserver_go_proto_/github.com/cockroachdb/cockroach/pkg/kv/kvserver/storage_services.pb.go:263
  | github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor.StreamServerInterceptor.func1
  | 	github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go:164
  | google.golang.org/grpc.chainStreamInterceptors.func1.1
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1482
  | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func4
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:285
  | google.golang.org/grpc.chainStreamInterceptors.func1.1
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1485
  | github.com/cockroachdb/cockroach/pkg/rpc.kvAuth.streamInterceptor
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/auth.go:167
  | google.golang.org/grpc.chainStreamInterceptors.func1.1
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1485
  | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func2.1
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:252
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:322
  | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:251
  | google.golang.org/grpc.chainStreamInterceptors.func1.1
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1485
  | google.golang.org/grpc.chainStreamInterceptors.func1
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1487
  | google.golang.org/grpc.(*Server).processStreamingRPC
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1636
  | google.golang.org/grpc.(*Server).handleStream
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1717
  | google.golang.org/grpc.(*Server).serveStreams.func1.2
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:965
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (2) secondary error attachment
  | while applying snapshot: while ingesting [× × × × × ×]: link × ×: operation not permitted
  | (1) attached stack trace
  |   -- stack trace:
  |   | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:928
  |   | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processRaftSnapshotRequest.func1
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:465
  |   | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).withReplicaForRequest
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:343
  |   | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processRaftSnapshotRequest
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:406
  |   | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).receiveSnapshot
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_snapshot.go:1091
  |   | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).HandleSnapshot.func1
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:211
  |   | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr
  |   | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:322
  |   | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).HandleSnapshot
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:208
  |   | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*RaftTransport).RaftSnapshot
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/raft_transport.go:382
  |   | github.com/cockroachdb/cockroach/pkg/kv/kvserver._MultiRaft_RaftSnapshot_Handler
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/bazel-out/k8-opt/bin/pkg/kv/kvserver/kvserver_go_proto_/github.com/cockroachdb/cockroach/pkg/kv/kvserver/storage_services.pb.go:263
  |   | github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor.StreamServerInterceptor.func1
  |   | 	github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go:164
  |   | google.golang.org/grpc.chainStreamInterceptors.func1.1
  |   | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1482
  |   | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func4
  |   | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:285
  |   | google.golang.org/grpc.chainStreamInterceptors.func1.1
  |   | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1485
  |   | github.com/cockroachdb/cockroach/pkg/rpc.kvAuth.streamInterceptor
  |   | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/auth.go:167
  |   | google.golang.org/grpc.chainStreamInterceptors.func1.1
  |   | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1485
  |   | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func2.1
  |   | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:252
  |   | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr
  |   | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:322
  |   | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func2
  |   | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:251
  |   | google.golang.org/grpc.chainStreamInterceptors.func1.1
  |   | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1485
  |   | google.golang.org/grpc.chainStreamInterceptors.func1
  |   | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1487
  |   | google.golang.org/grpc.(*Server).processStreamingRPC
  |   | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1636
  |   | google.golang.org/grpc.(*Server).handleStream
  |   | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1717
  |   | google.golang.org/grpc.(*Server).serveStreams.func1.2
  |   | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:965
  | Wraps: (2) while applying snapshot
  | Wraps: (3) attached stack trace
  |   -- stack trace:
  |   | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).applySnapshot
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raftstorage.go:558
  |   | git...
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L964-L966](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L964-L966)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1716-L1718](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1716-L1718)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1635-L1637](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1635-L1637)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1486-L1488](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1486-L1488)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1484-L1486](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1484-L1486)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/rpc/pkg/rpc/context.go#L250-L252](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/rpc/pkg/rpc/context.go#L250-L252)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/util/stop/stopper.go#L321-L323](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/util/stop/stopper.go#L321-L323)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/rpc/pkg/rpc/context.go#L251-L253](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/rpc/pkg/rpc/context.go#L251-L253)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1484-L1486](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1484-L1486)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/rpc/pkg/rpc/auth.go#L166-L168](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/rpc/pkg/rpc/auth.go#L166-L168)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1484-L1486](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1484-L1486)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/rpc/pkg/rpc/context.go#L284-L286](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/rpc/pkg/rpc/context.go#L284-L286)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1481-L1483](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1481-L1483)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go#L163-L165](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go#L163-L165)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/kv/kvserver/bazel-out/k8-opt/bin/pkg/kv/kvserver/kvserver_go_proto_/github.com/cockroachdb/cockroach/pkg/kv/kvserver/storage_services.pb.go#L262-L264](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/kv/kvserver/bazel-out/k8-opt/bin/pkg/kv/kvserver/kvserver_go_proto_/github.com/cockroachdb/cockroach/pkg/kv/kvserver/storage_services.pb.go#L262-L264)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/kv/kvserver/pkg/kv/kvserver/raft_transport.go#L381-L383](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/kv/kvserver/pkg/kv/kvserver/raft_transport.go#L381-L383)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L207-L209](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L207-L209)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/util/stop/stopper.go#L321-L323](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/util/stop/stopper.go#L321-L323)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L210-L212](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L210-L212)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/kv/kvserver/pkg/kv/kvserver/store_snapshot.go#L1090-L1092](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/kv/kvserver/pkg/kv/kvserver/store_snapshot.go#L1090-L1092)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L405-L407](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L405-L407)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L342-L344](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L342-L344)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L465-L467](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L465-L467)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.(*Server).serveStreams.func1.2 at line 965
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.(*Server).handleStream at line 1717
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.(*Server).processStreamingRPC at line 1636
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.chainStreamInterceptors.func1 at line 1487
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.chainStreamInterceptors.func1.1 at line 1485
pkg/rpc/pkg/rpc/context.go in pkg/rpc.NewServerEx.func2 at line 251
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunTaskWithErr at line 322
pkg/rpc/pkg/rpc/context.go in pkg/rpc.NewServerEx.func2.1 at line 252
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.chainStreamInterceptors.func1.1 at line 1485
pkg/rpc/pkg/rpc/auth.go in pkg/rpc.kvAuth.streamInterceptor at line 167
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.chainStreamInterceptors.func1.1 at line 1485
pkg/rpc/pkg/rpc/context.go in pkg/rpc.NewServerEx.func4 at line 285
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.chainStreamInterceptors.func1.1 at line 1482
pkg/util/tracing/grpcinterceptor/grpc_interceptor.go in pkg/util/tracing/grpcinterceptor.StreamServerInterceptor.func1 at line 164
pkg/kv/kvserver/bazel-out/k8-opt/bin/pkg/kv/kvserver/kvserver_go_proto_/github.com/cockroachdb/cockroach/pkg/kv/kvserver/storage_services.pb.go in pkg/kv/kvserver._MultiRaft_RaftSnapshot_Handler at line 263
pkg/kv/kvserver/pkg/kv/kvserver/raft_transport.go in pkg/kv/kvserver.(*RaftTransport).RaftSnapshot at line 382
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).HandleSnapshot at line 208
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunTaskWithErr at line 322
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).HandleSnapshot.func1 at line 211
pkg/kv/kvserver/pkg/kv/kvserver/store_snapshot.go in pkg/kv/kvserver.(*Store).receiveSnapshot at line 1091
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).processRaftSnapshotRequest at line 406
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).withReplicaForRequest at line 343
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).processRaftSnapshotRequest.func1 at line 466
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v23.1.9 |
| Go Version | go1.19.10 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.9 |
| Cockroach SHA | 28b2e767986169df857f5f2cd1790d71ac633395 |
| # of CPUs | 2 |
| # of Goroutines | 299 |

Jira issue: CRDB-31685

**Comment by yuzefovich** [comment]
dup of #86703
