### ISSUE TITLE
ttl: Add TTL to random test workloads

### ISSUE THREAD

**Issue by rimadeodhar** [cockroachdb/cockroach#110928]
As a follow up from this PM, we need to add tests to our random test workloads to run on tables with TTL enabled.

Jira issue: CRDB-31678

**Comment by rafiss** [comment]
fadfd2ac3911d26ecb532765c1b49ce2fc5bbe54 was merged, and it runs TTL while TPCC is running, so we can consider this sufficiently tested now.
