### ISSUE TITLE
kvserver: v23.1.8: fatal: Unsafe timestamp cache update! Cannot add timestamp after evaluating Delete

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#110960]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4491228066/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4491228066/?referrer=webhooks_plugin)

Panic Message:

```
replica_tscache.go:49: log.Fatal: Unsafe timestamp cache update! Cannot add timestamp 1695214044.946309297,2 to timestamp cache after evaluating Delete [/Table/11/2/×/×/×/×/×/×,/Min), EndTxn(commit) [/Table/11/2/×/×/×/×/×/×], [txn: a1e11fef], [can-forward-ts] (resp=×; err=<nil>) with lease expiration 1695214043.469648334,0. The timestamp cache update could be lost of a non-cooperative lease change.
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).addToTSCacheChecked
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_tscache.go:49
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).updateTimestampCache.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_tscache.go:69
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).updateTimestampCache
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_tscache.go:140
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*endCmds).done
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go:1283
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*ProposalData).finishApplication
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go:144
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*replicatedCmd).AckOutcomeAndFinish
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_application_cmd.go:147
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply.forEachAppliedCmdIter
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply/cmd.go:264
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply.(*Task).applyOneBatch
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply/task.go:301
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply.(*Task).ApplyCommittedEntries
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply/task.go:251
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:1012
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReady
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:725
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processReady
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:646
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftSchedulerShard).worker
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:395
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).Start.func2
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:302
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (2) log.Fatal: Unsafe timestamp cache update! Cannot add timestamp 1695214044.946309297,2 to timestamp cache after evaluating Delete [/Table/11/2/×/×/×/×/×/×,/Min), EndTxn(commit) [/Table/11/2/×/×/×/×/×/×], [txn: a1e11fef], [can-forward-ts] (resp=×; err=<nil>) with lease expiration 1695214043.469648334,0. The timestamp cache update could be lost of a non-cooperative lease change.
Error types: (1) *withstack.withStack (2) *errutil.leafError
-- report composition:
*errutil.leafError: log.Fatal: Unsafe timestamp cache update! Cannot add timestamp 1695214044.946309297,2 to timestamp cache after evaluating Delete [/Table/11/2/×/×/×/×/×/×,/Min), EndTxn(commit) [/Table/11/2/×/×/×/×/×/×], [txn: a1e11fef], [can-forward-ts] (resp=×; err=<nil>) with lease expiration 1695214043.469648334,0. The timestamp cache update could be lost of a non-cooperative lease change.
replica_tscache.go:49: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/util/stop/stopper.go#L469-L471](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/util/stop/stopper.go#L469-L471)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L301-L303](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L301-L303)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L394-L396](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L394-L396)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L645-L647](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L645-L647)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L724-L726](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L724-L726)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L1011-L1013](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L1011-L1013)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/apply/task.go#L250-L252](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/apply/task.go#L250-L252)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/apply/task.go#L300-L302](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/apply/task.go#L300-L302)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/apply/cmd.go#L263-L265](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/apply/cmd.go#L263-L265)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/pkg/kv/kvserver/replica_application_cmd.go#L146-L148](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/pkg/kv/kvserver/replica_application_cmd.go#L146-L148)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go#L143-L145](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go#L143-L145)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go#L1282-L1284](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go#L1282-L1284)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/pkg/kv/kvserver/replica_tscache.go#L139-L141](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/pkg/kv/kvserver/replica_tscache.go#L139-L141)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/pkg/kv/kvserver/replica_tscache.go#L68-L70](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/pkg/kv/kvserver/replica_tscache.go#L68-L70)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/pkg/kv/kvserver/replica_tscache.go#L48-L50](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/pkg/kv/kvserver/replica_tscache.go#L48-L50)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 470
pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go in pkg/kv/kvserver.(*raftScheduler).Start.func2 at line 302
pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go in pkg/kv/kvserver.(*raftSchedulerShard).worker at line 395
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).processReady at line 646
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).handleRaftReady at line 725
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked at line 1012
pkg/kv/kvserver/apply/task.go in pkg/kv/kvserver/apply.(*Task).ApplyCommittedEntries at line 251
pkg/kv/kvserver/apply/task.go in pkg/kv/kvserver/apply.(*Task).applyOneBatch at line 301
pkg/kv/kvserver/apply/cmd.go in pkg/kv/kvserver/apply.forEachAppliedCmdIter at line 264
pkg/kv/kvserver/pkg/kv/kvserver/replica_application_cmd.go in pkg/kv/kvserver.(*replicatedCmd).AckOutcomeAndFinish at line 147
pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go in pkg/kv/kvserver.(*ProposalData).finishApplication at line 144
pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go in pkg/kv/kvserver.(*endCmds).done at line 1283
pkg/kv/kvserver/pkg/kv/kvserver/replica_tscache.go in pkg/kv/kvserver.(*Replica).updateTimestampCache at line 140
pkg/kv/kvserver/pkg/kv/kvserver/replica_tscache.go in pkg/kv/kvserver.(*Replica).updateTimestampCache.func1 at line 69
pkg/kv/kvserver/pkg/kv/kvserver/replica_tscache.go in pkg/kv/kvserver.(*Replica).addToTSCacheChecked at line 49
```

### Tags

| Tag | Value |
| --- | --- |
| Command | start-single-node |
| Environment | v23.1.8 |
| Go Version | go1.19.10 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.8 |
| Cockroach SHA | 2c1d4afd2c2de091a00a4dba4392ceeaf8504a95 |
| # of CPUs | 4 |
| # of Goroutines | 343 |

Jira issue: CRDB-31688

**Comment by yuzefovich** [comment]
dup of #100619 which was closed on 22.1, perhaps we need to re-evaluate that
