### ISSUE TITLE
Performance test `crdb_internal.invalid_objects` on clusters with large numbers of descriptors

### ISSUE THREAD

**Issue by chrisseto** [cockroachdb/cockroach#111065]
In 23.2 and 23.1 via a backport, `crdb_internal.invalid_objects` is periodically scanned with `AS OF SYSTEM TIME`.

To ensure that this isn’t going to be an issue for existing clusters, we should check on the performance of `crdb_internal.invalid_objects` while a workload is running.

I plan to omit tests that include invalid objects. This is because more work will be done on valid objects as we'll be running the entirety of validation on them. If we have concerns about memory usage, we can add cases for that as well.

For completion, I'll be testing across the following axes:
* Workload(s): 
  * None
  * TPCC
  * Schema change
* Queries:
  * `SELECT * FROM crdb_internal.invalid_object`
  * `SELECT SUM(*) FROM crdb_internal.invalid_object`
  * `SELECT * FROM crdb_internal.invalid_object AS OF SYSTEM TIME '-1s'`
  *  `SELECT SUM(*) FROM crdb_internal.invalid_object AS OF SYSTEM TIME '-1s'`
* \# of Descriptors (Or initial descriptors in the case of workload/schemachange):
  * 100
  * 500
  * 1000
  * 2000
  * 4000 (Uncertain if this is needed or even recommended)

Jira issue: CRDB-31751

**Comment by rimadeodhar** [comment]
cc @rafiss, this issue looks at perf testing for the 23.1 backport. Please take a look at the outlined plan to ensure it looks sufficient.

**Comment by rafiss** [comment]
This looks good. One addition we might consider is to also add a microbenchmark unit test that performs this work on a cluster (with no concurrent load, but with many descriptors.)

To facilitate testing, consider using the `crdb_internal.generate_test_objects` builtin function.

**Comment by chrisseto** [comment]
This ended up being handled within a slack conversation between Rafi, Rima, and myself. For posterity, I'm adding our findings here and closing out this issue.

We were more concerned about schema telemetry job than the `crdb_internal.invalid_objects` table. The job uses `AS OF SYSTEM TIME` queries and [limits it's results 1000](https://github.com/cockroachdb/cockroach/commit/a49fe07c20358dc479a748f19f76dcd68a6670f1#diff-025f1b729bf3ff3a1cf3d97a5f599e93722c6fd25c4a208055db468f435aacbfR83). Notably, it will still iterate across all descriptors within a cluster to generate the list from which 1000 results are pulled.

Using `cockroach demo`, I tacked on a couple thousand tables. The concern is more so about the scanning of descriptors than running the actual validation logic. Therefore we considered having a single facetted descriptor set valid.

```
demo@127.0.0.1:26257/demoapp/movr> SELECT * FROM "".crdb_internal.invalid_objects AS OF SYSTEM TIME '-1s';
  id | database_name | schema_name | obj_name | error
-----+---------------+-------------+----------+--------
(0 rows)

Time: 28.722s total (execution 28.722s / network 0.000s)

demo@127.0.0.1:26257/demoapp/movr> SELECT COUNT(*) FROM system.descriptor;
  count
---------
  17297
(1 row)

Time: 20ms total (execution 19ms / network 0ms)

demo@127.0.0.1:26257/demoapp/movr>
```

The results were not incredible but also not worrying. 17K is a very high number of descriptors and the telemetry job runs once a week. All that to say, we think the performance of `crdb_internal.invalid_objects` is acceptable for now.
