### ISSUE TITLE
Sentry: db.go:742: log.Fatal: no data available
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/pebble.(*DB).Apply
  | 	github.com/cockroachdb/pebble/external/com_github_cockroac...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#111180]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4501962108/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4501962108/?referrer=webhooks_plugin)

Panic Message:

```
db.go:742: log.Fatal: no data available
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/pebble.(*DB).Apply
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go:742
  | github.com/cockroachdb/pebble.(*DB).Set
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go:554
  | github.com/cockroachdb/cockroach/pkg/storage.(*Pebble).put
  | 	github.com/cockroachdb/cockroach/pkg/storage/pebble.go:1404
  | github.com/cockroachdb/cockroach/pkg/storage.(*Pebble).PutUnversioned
  | 	github.com/cockroachdb/cockroach/pkg/storage/pebble.go:1381
  | github.com/cockroachdb/cockroach/pkg/storage.(*putBuffer).putInlineMeta
  | 	github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:1263
  | github.com/cockroachdb/cockroach/pkg/storage.mvccPutInternal
  | 	github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:1676
  | github.com/cockroachdb/cockroach/pkg/storage.mvccPutUsingIter
  | 	github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:1414
  | github.com/cockroachdb/cockroach/pkg/storage.MVCCPut
  | 	github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:1333
  | github.com/cockroachdb/cockroach/pkg/storage.MVCCPutProto
  | 	github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:841
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).WriteLastUpTimestamp
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store.go:2817
  | github.com/cockroachdb/cockroach/pkg/server.(*Server).PreStart.func10.1
  | 	github.com/cockroachdb/cockroach/pkg/server/server.go:1584
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Stores).VisitStores.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/stores.go:150
  | github.com/cockroachdb/cockroach/pkg/util/syncutil.(*IntMap).Range
  | 	github.com/cockroachdb/cockroach/pkg/util/syncutil/int_map.go:352
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Stores).VisitStores
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/stores.go:149
  | github.com/cockroachdb/cockroach/pkg/server.(*Server).PreStart.func10
  | 	github.com/cockroachdb/cockroach/pkg/server/server.go:1583
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/liveness.(*NodeLiveness).updateLivenessAttempt
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/liveness/liveness.go:1421
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/liveness.(*NodeLiveness).updateLiveness
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/liveness/liveness.go:1328
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/liveness.(*NodeLiveness).heartbeatInternal
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/liveness/liveness.go:981
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/liveness.(*NodeLiveness).Heartbeat
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/liveness/liveness.go:894
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*pendingLeaseRequest).requestLease
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_range_lease.go:467
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*pendingLeaseRequest).requestLeaseAsync.func2
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_range_lease.go:401
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:489
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (2) secondary error attachment
  | no data available
  | (1) no data available
  | Error types: (1) syscall.Errno
Wraps: (3) log.Fatal: no data available
Error types: (1) *withstack.withStack (2) *secondary.withSecondaryError (3) *errutil.leafError
-- report composition:
*errutil.leafError: log.Fatal: no data available
*secondary.withSecondaryError
db.go:742: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/util/stop/stopper.go#L488-L490](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/util/stop/stopper.go#L488-L490)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/kv/kvserver/pkg/kv/kvserver/replica_range_lease.go#L400-L402](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/kv/kvserver/pkg/kv/kvserver/replica_range_lease.go#L400-L402)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/kv/kvserver/pkg/kv/kvserver/replica_range_lease.go#L466-L468](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/kv/kvserver/pkg/kv/kvserver/replica_range_lease.go#L466-L468)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/kv/kvserver/liveness/liveness.go#L893-L895](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/kv/kvserver/liveness/liveness.go#L893-L895)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/kv/kvserver/liveness/liveness.go#L980-L982](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/kv/kvserver/liveness/liveness.go#L980-L982)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/kv/kvserver/liveness/liveness.go#L1327-L1329](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/kv/kvserver/liveness/liveness.go#L1327-L1329)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/kv/kvserver/liveness/liveness.go#L1420-L1422](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/kv/kvserver/liveness/liveness.go#L1420-L1422)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/server/server.go#L1582-L1584](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/server/server.go#L1582-L1584)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/kv/kvserver/pkg/kv/kvserver/stores.go#L148-L150](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/kv/kvserver/pkg/kv/kvserver/stores.go#L148-L150)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/util/syncutil/int_map.go#L351-L353](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/util/syncutil/int_map.go#L351-L353)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/kv/kvserver/pkg/kv/kvserver/stores.go#L149-L151](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/kv/kvserver/pkg/kv/kvserver/stores.go#L149-L151)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/server/server.go#L1583-L1585](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/server/server.go#L1583-L1585)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/kv/kvserver/pkg/kv/kvserver/store.go#L2816-L2818](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/kv/kvserver/pkg/kv/kvserver/store.go#L2816-L2818)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/storage/mvcc.go#L840-L842](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/storage/mvcc.go#L840-L842)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/storage/mvcc.go#L1332-L1334](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/storage/mvcc.go#L1332-L1334)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/storage/mvcc.go#L1413-L1415](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/storage/mvcc.go#L1413-L1415)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/storage/mvcc.go#L1675-L1677](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/storage/mvcc.go#L1675-L1677)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/storage/mvcc.go#L1262-L1264](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/storage/mvcc.go#L1262-L1264)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/storage/pebble.go#L1380-L1382](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/storage/pebble.go#L1380-L1382)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/storage/pebble.go#L1403-L1405](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/storage/pebble.go#L1403-L1405)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L553-L555](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L553-L555)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L741-L743](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L741-L743)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 489
pkg/kv/kvserver/pkg/kv/kvserver/replica_range_lease.go in pkg/kv/kvserver.(*pendingLeaseRequest).requestLeaseAsync.func2 at line 401
pkg/kv/kvserver/pkg/kv/kvserver/replica_range_lease.go in pkg/kv/kvserver.(*pendingLeaseRequest).requestLease at line 467
pkg/kv/kvserver/liveness/liveness.go in pkg/kv/kvserver/liveness.(*NodeLiveness).Heartbeat at line 894
pkg/kv/kvserver/liveness/liveness.go in pkg/kv/kvserver/liveness.(*NodeLiveness).heartbeatInternal at line 981
pkg/kv/kvserver/liveness/liveness.go in pkg/kv/kvserver/liveness.(*NodeLiveness).updateLiveness at line 1328
pkg/kv/kvserver/liveness/liveness.go in pkg/kv/kvserver/liveness.(*NodeLiveness).updateLivenessAttempt at line 1421
pkg/server/server.go in pkg/server.(*Server).PreStart.func10 at line 1583
pkg/kv/kvserver/pkg/kv/kvserver/stores.go in pkg/kv/kvserver.(*Stores).VisitStores at line 149
pkg/util/syncutil/int_map.go in pkg/util/syncutil.(*IntMap).Range at line 352
pkg/kv/kvserver/pkg/kv/kvserver/stores.go in pkg/kv/kvserver.(*Stores).VisitStores.func1 at line 150
pkg/server/server.go in pkg/server.(*Server).PreStart.func10.1 at line 1584
pkg/kv/kvserver/pkg/kv/kvserver/store.go in pkg/kv/kvserver.(*Store).WriteLastUpTimestamp at line 2817
pkg/storage/mvcc.go in pkg/storage.MVCCPutProto at line 841
pkg/storage/mvcc.go in pkg/storage.MVCCPut at line 1333
pkg/storage/mvcc.go in pkg/storage.mvccPutUsingIter at line 1414
pkg/storage/mvcc.go in pkg/storage.mvccPutInternal at line 1676
pkg/storage/mvcc.go in pkg/storage.(*putBuffer).putInlineMeta at line 1263
pkg/storage/pebble.go in pkg/storage.(*Pebble).PutUnversioned at line 1381
pkg/storage/pebble.go in pkg/storage.(*Pebble).put at line 1404
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go in github.com/cockroachdb/pebble.(*DB).Set at line 554
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go in github.com/cockroachdb/pebble.(*DB).Apply at line 742
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v22.2.12 |
| Go Version | go1.19.6 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v22.2.12 |
| Cockroach SHA | feededb3d12a703bada7699b65ad1e191f97a91b |
| # of CPUs | 16 |
| # of Goroutines | 511 |

Jira issue: CRDB-31806

**Comment by yuzefovich** [comment]
dup of #86703
