### ISSUE TITLE
kv: compatible requests should be released when a request drops out of lock wait queue

### ISSUE THREAD

**Issue by arulajmani** [cockroachdb/cockroach#111144]
**Describe the problem**

Consider the following construction:

```
key A: 
- [holder: (req1: Shared, txn1)]
- wait queue: [(req2: Exclusive, txn2), (req3: Shared, txn3), (req4: Shared txn4)] 
```

If the exclusive locking request, req2, drops out of the wait queue (say it's session gets killed or whatever), the shared locking requests (req3 and req4) no longer need to wait -- they're compatible with the lock holder, and the request they were waiting on (req2) has dropped out. They should be allowed to proceed. This doesn't happen currently.

Jira issue: CRDB-31788

**Comment by nvanbenschoten** [comment]
The two pieces of logic that may be related to this are:
https://github.com/cockroachdb/cockroach/blob/695eaf6108934a3d145f41345a8dbe02381ea1fc/pkg/kv/kvserver/concurrency/lock_table.go#L3410-L3417

https://github.com/cockroachdb/cockroach/blob/695eaf6108934a3d145f41345a8dbe02381ea1fc/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L354-L371
