### ISSUE TITLE
roachtest: add team VM labels

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#111107]
Roachtests have teams associated with them. This team label should be added to the list of Cloud tags to help with cost accounting.

Could you please add the team name as a Cloud label under the key "engteam"? So, we'd have a tag like "engteam:disaster-recovery" for example.

Jira issue: CRDB-31768

**Comment by nameisbhaskar** [comment]
This is completed as a part of https://github.com/cockroachdb/cockroach/issues/129955
