### ISSUE TITLE
roachperf: Run workloads comparing single tenant and MT configurations

### ISSUE THREAD

**Issue by ajstorm** [cockroachdb/cockroach#111129]
We currently have no roachperf coverage which compares single tenant and MT performance.  It's important that we add this before we ship so that we catch any glaring performance issues around shared process multi-tenancy.

Epic: CRDB-18499

Jira issue: CRDB-31781

**Comment by yuzefovich** [comment]
#104703 added the following configs that now show up on roachperf:
- **KV0**
  - `kv0/enc=false/nodes=1/cpu=8`
    - [single-tenant](https://roachperf.crdb.dev/?filter=&view=kv0%2Fenc%3Dfalse%2Fnodes%3D1&tab=gce)
    - [UA](https://roachperf.crdb.dev/?filter=&view=kv0%2Fenc%3Dfalse%2Fnodes%3D1%2Fmt-shared-process&tab=gce)
  - `kv0/enc=false/nodes=1/cpu=32`
    - [single-tenant](https://roachperf.crdb.dev/?filter=&view=kv0%2Fenc%3Dfalse%2Fnodes%3D1%2Fcpu%3D32&tab=gce)
    - [UA](https://roachperf.crdb.dev/?filter=&view=kv0%2Fenc%3Dfalse%2Fnodes%3D1%2Fcpu%3D32%2Fmt-shared-process&tab=gce)
  - `kv0/enc=false/nodes=3/cpu=8`
    - [single-tenant](https://roachperf.crdb.dev/?filter=&view=kv0%2Fenc%3Dfalse%2Fnodes%3D3&tab=gce)
    - [UA](https://roachperf.crdb.dev/?filter=&view=kv0%2Fenc%3Dfalse%2Fnodes%3D3%2Fmt-shared-process&tab=gce)
  - `kv0/enc=false/nodes=3/cpu=32`
    - [single-tenant](https://roachperf.crdb.dev/?filter=&view=kv0%2Fenc%3Dfalse%2Fnodes%3D3%2Fcpu%3D32&tab=gce)
    - [UA](https://roachperf.crdb.dev/?filter=&view=kv0%2Fenc%3Dfalse%2Fnodes%3D3%2Fcpu%3D32%2Fmt-shared-process&tab=gce)
- **KV95** 
  - `kv95/enc=false/nodes=1/cpu=8`
    - [single-tenant](https://roachperf.crdb.dev/?filter=&view=kv95%2Fenc%3Dfalse%2Fnodes%3D1&tab=gce)
    - [UA](https://roachperf.crdb.dev/?filter=&view=kv95%2Fenc%3Dfalse%2Fnodes%3D1%2Fmt-shared-process&tab=gce)
  - `kv95/enc=false/nodes=1/cpu=32`
    - [single-tenant](https://roachperf.crdb.dev/?filter=&view=kv95%2Fenc%3Dfalse%2Fnodes%3D1%2Fcpu%3D32&tab=gce)
    - [UA](https://roachperf.crdb.dev/?filter=&view=kv95%2Fenc%3Dfalse%2Fnodes%3D1%2Fcpu%3D32%2Fmt-shared-process&tab=gce)
  - `kv95/nodes=3/cpu=8`
    - [single-tenant](https://roachperf.crdb.dev/?filter=&view=kv95%2Fenc%3Dfalse%2Fnodes%3D3&tab=gce)
    - [UA](https://roachperf.crdb.dev/?filter=&view=kv95%2Fenc%3Dfalse%2Fnodes%3D3%2Fmt-shared-process&tab=gce)
  - `kv95/enc=false/nodes=3/cpu=32`
    - [single-tenant](https://roachperf.crdb.dev/?filter=&view=kv95%2Fenc%3Dfalse%2Fnodes%3D3%2Fcpu%3D32&tab=gce)
    - [UA](https://roachperf.crdb.dev/?filter=&view=kv95%2Fenc%3Dfalse%2Fnodes%3D3%2Fcpu%3D32%2Fmt-shared-process&tab=gce)
- **TPCCBENCH**
  - `tpccbench/nodes=3/cpu=4`
    - [single-tenant](https://roachperf.crdb.dev/?filter=&view=tpccbench%2Fnodes%3D3%2Fcpu%3D4&tab=gce)
    - [UA](https://roachperf.crdb.dev/?filter=&view=tpccbench%2Fnodes%3D3%2Fcpu%3D4%2Fmt-shared-process&tab=gce)
  - `tpccbench/nodes=3/cpu=16`
    - [single-tenant](https://roachperf.crdb.dev/?filter=&view=tpccbench%2Fnodes%3D3%2Fcpu%3D16&tab=gce)
    - [UA](https://roachperf.crdb.dev/?filter=&view=tpccbench%2Fnodes%3D3%2Fcpu%3D16%2Fmt-shared-process&tab=gce)

(That PR also added some `multitenant/tpch` and `tpchvec` configs which require manual, more involved comparison, and the results don't show up on roachperf.)

**Comment by ajstorm** [comment]
Thanks @yuzefovich.  I'm closing this issue as a result.  We'll manually monitor the performance of MT vs single tenant clusters for the time being, as currently the automation in roachperf isn't available.
