### ISSUE TITLE
kv: reads rolled back by savepoints are not refreshed

### ISSUE THREAD

**Issue by miraradeva** [cockroachdb/cockroach#111228]
**Describe the problem**

When a read occurs between a `SAVEPOINT x` and a `ROLLBACK TO SAVEPOINT x`, the read is first added to the set of refresh spans for the txn, and then [removed from that set when the savepoint is rolled back](https://github.com/cockroachdb/cockroach/blob/master/pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go#L798-L803). If the txn's read and write timestamps diverge, this read will not be refreshed, which can be seen as a serializability violation.

Going back to the [commit that introduced this change](https://github.com/cockroachdb/cockroach/pull/45566), it seems like there was a reason for having this behavior. In short, if the client encounters a serializability error after creating a savepoint, they should be able to roll back to it and retry only a small amount of work, instead of retrying the entire txn. Currently, the only errors that can be recovered from by a savepoint rollback are [`ConditionFailedError` and `LockConflictError`](https://github.com/cockroachdb/cockroach/blob/master/pkg/kv/kvpb/errors.go#L111); in particular, recovering from a serializability error is not allowed. So the vision of the initial implementation didn't really come to life.

Moreover, the current behavior doesn't match the corresponding postgres behavior, which [ensures the rolled back reads can be serialized](https://github.com/postgres/postgres/blob/master/src/backend/storage/lmgr/README-SSI#L461-L467).

**To Reproduce**
A simple write skew example with and without a savepoint can illustrate the issue.

```sql
create table kv (k int primary key, v int);
insert into kv values (1, 1);
insert into kv values (2, 2);

-- session 1
begin;
select * from kv where k = 1;

-- session 2
begin;
-- savepoint a;
select * from kv where k = 2;
-- rollback to savepoint a;

-- session 1
update kv set v = v+1 where k = 2;

-- session 2
update kv set v = v+1 where k = 1;

-- session 1
commit;

-- session 2
commit;
ERROR: restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE - failed preemptive refresh due to encountered recently written committed value /Tenant/2/Table/112/1/2/0
```

Without the two savepoint lines in session 2, committing the second transaction results in a serializability error. But with the savepoint and rollback added, both txns commit successfully.

In postgres, this example returns a serializability error with or without savepoints.

**Additional context**
This issue came out of the work to add savepoint support in kvnemesis. With sufficiently high probabilities for savepoint operations, kvnemesis encounters cases of non-serializable reads within a few hundred runs.

It's not clear if this has any impact on customer workloads, or if it's represented in any of the test workloads we run.

Jira issue: CRDB-31829

**Comment by miraradeva** [comment]
Yes, I think so, though I've never done it before, so I'm not really sure where that data is.

**Comment by yuzefovich** [comment]
Hm, telemetry provides an incomplete picture (if a cluster is behind a firewall or has diagnostics disabled, then we won't know anything about that cluster). To me it seems that Queries team won't have bandwidth to rework this feature. Perhaps introducing a session variable that controls the behavior here at the KV level could be good (or maybe if `enforce_home_region` is `true`, then the old behavior is preserved - i.e. reuse existing session variable).

This feature was advocated for by @andy-kimball, so let's see what he thinks about the disabling the feature and consulting the telemetry to see the impact.

**Comment by miraradeva** [comment]
@yuzefovich and @andy-kimball any thoughts on disabling just the experimental `enforce_home_region_follower_reads_enabled` feature?

**Comment by yuzefovich** [comment]
I'm not right person to make this determination. cc @mgartner @michae2 @DingDLu

**Comment by mgartner** [comment]
`enforce_home_region_follower_reads_enabled` is disabled by default, so users have to explicitly opt into it.

**Comment by andy-kimball** [comment]
I don't think we have users using this feature yet, and if it's broken, we should definitely disable or remove it. The ability to automatically determine the home region was the less important part of the feature anyway; users can generally do it themselves.
