### ISSUE TITLE
Enable statement bundle cancellation in the console for the viewactivity system privilege

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#111270]
Allow users with the VIEWACTIVITY system privilege to cancel statement bundles.

Jira issue: CRDB-31848

Epic: CRDB-32130

**Comment by xinhaoz** [comment]
Just adding to this ticket that VIEWACTVITY users can currently request / view bundles they are unable to cancel requests.

**Comment by kevin-v-ngo** [comment]
Thanks Xin. Going to update this issue.
