### ISSUE TITLE
Sentry: error.go:89: unexpected error from the vectorized engine: runtime error: slice bounds out of range [::-9081481605317360328]
(1)
Wraps: (2)
Wraps: (3)
Wraps: (4) assertion failure
Wraps: (5) at...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#111250]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4504156568/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4504156568/?referrer=webhooks_plugin)

Panic Message:

```
error.go:89: unexpected error from the vectorized engine: runtime error: slice bounds out of range [::-9081481605317360328]
(1)
Wraps: (2)
Wraps: (3)
Wraps: (4) assertion failure
Wraps: (5) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:89
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | runtime.goPanicSlice3Acap
  | 	GOROOT/src/runtime/panic.go:173
  | github.com/cockroachdb/cockroach/pkg/col/coldata.(*element).getNonInlined
  | 	github.com/cockroachdb/cockroach/pkg/col/coldata/bytes.go:107
  | github.com/cockroachdb/cockroach/pkg/col/coldata.(*element).get
  | 	github.com/cockroachdb/cockroach/pkg/col/coldata/bytes.go:102
  | github.com/cockroachdb/cockroach/pkg/col/coldata.(*Bytes).Get
  | 	github.com/cockroachdb/cockroach/pkg/col/coldata/bytes.go:187
  | github.com/cockroachdb/cockroach/pkg/sql/colconv.ColVecToDatum
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/colconv/vec_to_datum.eg.go:2642
  | github.com/cockroachdb/cockroach/pkg/sql/colconv.ColVecToDatumAndDeselect
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/colconv/vec_to_datum.eg.go:258
  | github.com/cockroachdb/cockroach/pkg/sql/colconv.(*VecToDatumConverter).ConvertBatchAndDeselect
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/colconv/vec_to_datum.eg.go:177
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Materializer).next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:252
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Materializer).nextAdapter
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:272
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Materializer).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:278
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*FlowCoordinator).next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:128
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*FlowCoordinator).nextAdapter
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:145
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*FlowCoordinator).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:150
  | github.com/cockroachdb/cockroach/pkg/sql/execinfra.Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/execinfra/base.go:195
  | github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBaseNoHelper).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:726
  | github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:575
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:309
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:902
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1913
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll.func3
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1645
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1648
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2155
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1709
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1036
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:142
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:3086
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:141
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2182
Wraps: (6) unexpected error from the vectorized engine
Wraps: (7) runtime error: slice bounds out of range [::-9081481605317360328]
  | -- cause hidden behind barrier
  | runtime error: slice bounds out of range [::-9081481605317360328]
  | (1) runtime error: slice bounds out of range [::-9081481605317360328]
  | Error types: (1) runtime.boundsError
Error types: (1) *colexecerror.notInternalError (2) *colexecerror.notInternalError (3) *colexecerror.notInternalError (4) *assert.withAssertionFailure (5) *withstack.withStack (6) *errutil.withPrefix (7) *barriers.barrierErr
-- report composition:
*barriers.barrierErr: masked error: runtime error: slice bounds out of range [::-9081481605317360328]
*errutil.withPrefix: unexpected error from the vectorized engine
error.go:89: *withstack.withStack (top exception)
*assert.withAssertionFailure
*colexecerror.notInternalError
*colexecerror.notInternalError
*colexecerror.notInternalError
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/conn_executor.go#L2181-L2183](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/conn_executor.go#L2181-L2183)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/conn_executor_exec.go#L140-L142](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/conn_executor_exec.go#L140-L142)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/conn_executor_exec.go#L3085-L3087](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/conn_executor_exec.go#L3085-L3087)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/conn_executor_exec.go#L141-L143](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/conn_executor_exec.go#L141-L143)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/conn_executor_exec.go#L1035-L1037](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/conn_executor_exec.go#L1035-L1037)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/conn_executor_exec.go#L1708-L1710](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/conn_executor_exec.go#L1708-L1710)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/conn_executor_exec.go#L2154-L2156](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/conn_executor_exec.go#L2154-L2156)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/distsql_running.go#L1647-L1649](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/distsql_running.go#L1647-L1649)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/distsql_running.go#L1644-L1646](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/distsql_running.go#L1644-L1646)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/distsql_running.go#L1912-L1914](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/distsql_running.go#L1912-L1914)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/distsql_running.go#L901-L903](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/distsql_running.go#L901-L903)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/colflow/vectorized_flow.go#L308-L310](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/colflow/vectorized_flow.go#L308-L310)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/flowinfra/flow.go#L574-L576](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/flowinfra/flow.go#L574-L576)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/execinfra/processorsbase.go#L725-L727](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/execinfra/processorsbase.go#L725-L727)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/execinfra/base.go#L194-L196](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/execinfra/base.go#L194-L196)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/colflow/flow_coordinator.go#L149-L151](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/colflow/flow_coordinator.go#L149-L151)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/colflow/flow_coordinator.go#L144-L146](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/colflow/flow_coordinator.go#L144-L146)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/colflow/flow_coordinator.go#L127-L129](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/colflow/flow_coordinator.go#L127-L129)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/colexec/materializer.go#L277-L279](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/colexec/materializer.go#L277-L279)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/colexec/materializer.go#L271-L273](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/colexec/materializer.go#L271-L273)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/colexec/materializer.go#L251-L253](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/colexec/materializer.go#L251-L253)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/bazel-out/k8-opt/bin/pkg/sql/colconv/vec_to_datum.eg.go#L176-L178](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/bazel-out/k8-opt/bin/pkg/sql/colconv/vec_to_datum.eg.go#L176-L178)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/bazel-out/k8-opt/bin/pkg/sql/colconv/vec_to_datum.eg.go#L257-L259](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/bazel-out/k8-opt/bin/pkg/sql/colconv/vec_to_datum.eg.go#L257-L259)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/bazel-out/k8-opt/bin/pkg/sql/colconv/vec_to_datum.eg.go#L2641-L2643](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/bazel-out/k8-opt/bin/pkg/sql/colconv/vec_to_datum.eg.go#L2641-L2643)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/col/coldata/bytes.go#L186-L188](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/col/coldata/bytes.go#L186-L188)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/col/coldata/bytes.go#L101-L103](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/col/coldata/bytes.go#L101-L103)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/col/coldata/bytes.go#L106-L108](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/col/coldata/bytes.go#L106-L108)
[GOROOT/src/runtime/panic.go#L172-L174](GOROOT/src/runtime/panic.go#L172-L174)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/colexecerror/error.go#L88-L90](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/colexecerror/error.go#L88-L90)
</details>

```
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd.func1 at line 2182
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 141
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithProfiling at line 3086
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt.func1 at line 142
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 1036
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchToExecutionEngine at line 1709
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithDistSQLEngine at line 2155
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRunAll at line 1648
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRunAll.func3 at line 1645
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRun at line 1913
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).Run at line 902
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlow).Run at line 309
pkg/sql/flowinfra/flow.go in pkg/sql/flowinfra.(*FlowBase).Run at line 575
pkg/sql/execinfra/processorsbase.go in pkg/sql/execinfra.(*ProcessorBaseNoHelper).Run at line 726
pkg/sql/execinfra/base.go in pkg/sql/execinfra.Run at line 195
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*FlowCoordinator).Next at line 150
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*FlowCoordinator).nextAdapter at line 145
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*FlowCoordinator).next at line 128
pkg/sql/colexec/materializer.go in pkg/sql/colexec.(*Materializer).Next at line 278
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colexec/materializer.go in pkg/sql/colexec.(*Materializer).nextAdapter at line 272
pkg/sql/colexec/materializer.go in pkg/sql/colexec.(*Materializer).next at line 252
bazel-out/k8-opt/bin/pkg/sql/colconv/vec_to_datum.eg.go in pkg/sql/colconv.(*VecToDatumConverter).ConvertBatchAndDeselect at line 177
bazel-out/k8-opt/bin/pkg/sql/colconv/vec_to_datum.eg.go in pkg/sql/colconv.ColVecToDatumAndDeselect at line 258
bazel-out/k8-opt/bin/pkg/sql/colconv/vec_to_datum.eg.go in pkg/sql/colconv.ColVecToDatum at line 2642
pkg/col/coldata/bytes.go in pkg/col/coldata.(*Bytes).Get at line 187
pkg/col/coldata/bytes.go in pkg/col/coldata.(*element).get at line 102
pkg/col/coldata/bytes.go in pkg/col/coldata.(*element).getNonInlined at line 107
GOROOT/src/runtime/panic.go in runtime.goPanicSlice3Acap at line 173
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1 at line 89
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v23.1.10 |
| Go Version | go1.19.10 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.10 |
| Cockroach SHA | 6bd6e0c65a2eba531e7a8412d63988abb5b50120 |
| # of CPUs | 48 |
| # of Goroutines | 733 |

Jira issue: CRDB-31835

**Comment by yuzefovich** [comment]
Looks like either integer overflow or memory corruption (less likely), but unactionable
