### ISSUE TITLE
Collect feature telemetry usage for pg_crypto functions

### ISSUE THREAD

**Issue by dikshant** [cockroachdb/cockroach#111323]
We should collect feature telemetry for the encrypt/decrypt{_iv} functions as well as rest of the cryptographic functions we have added:
https://www.cockroachlabs.com/docs/stable/functions-and-operators#cryptographic-functions

This can go into sql.builtins.crypto.func_name

We might have to check the current way of how other built ins are done if already and follow that convention suffixed by .crypto.func_name

Jira issue: CRDB-31857

Epic CRDB-10655

**Comment by andyyang890** [comment]
We discussed this offline and decided to rely on log based telemetry for 23.2, closing for now.
