### ISSUE TITLE
Automatically update the timestamp

### ISSUE THREAD

**Issue by NC-Cj** [cockroachdb/cockroach#111333]
**I want some columns of the data table to be automatically updated based on the last data row update, without the specified update that is displayed.**

```sql
CREATE TABLE tags
(
    id         BIGINT PRIMARY KEY DEFAULT unique_rowid(),
    tag_name   VARCHAR,
    created_at TIMESTAMP          DEFAULT now() not null,
    updated_at TIMESTAMPTZ        DEFAULT current_timestamp not null
);


update tags set tag_name='new_name' where id=123456789;

```

**Expected to happen:**

Update a piece of data without specifying updated_at. After a piece of data is changed, the updated_at time is automatically updated.

**What I got:**

Update a piece of data without specifying updated_at, but after this piece of data is changed, updated_at is not updated, only the field value of set is updated.

**PS:**

I don't think you need to manually create triggers to implement this feature?

Jira issue: CRDB-31862

**Comment by rafiss** [comment]
This is possible using an ON UPDATE expression. See these docs: https://www.cockroachlabs.com/docs/stable/create-table#on-update-expressions
