### ISSUE TITLE
roachtest: switch to regional buckets in GCE; MR is no longer free wrt egress

### ISSUE THREAD

**Issue by srosenberg** [cockroachdb/cockroach#111371]
As of last year, GCE decided to charge for egress, when reading from a multi-regional (MR) bucket [1]. AWS' s3 doesn't even support multi-regional buckets. (Technically, it supports cross-regional replication, but the bucket is always pinned to a specific region.) In light of the above, we are going to stick with _regional_ buckets for roachtest, across all providers. The reduction in egress (cost) also facilitates better resource load-balancing across regions; e.g., our local SSD quota has been steadily running low in `us-east1`, while the request to increase it, continues to linger; moving a small percentage of clusters to `us-central1` alleviates the quota issue.

[1]https://cloud.google.com/storage/pricing-announce#network

Jira issue: CRDB-31875

**Comment by msbutler** [comment]
fixture migration has complete and old bucket has been deleted. closing.
