### ISSUE TITLE
sql/stats: flake in TestStatsAreDeletedForDroppedTables

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#111509]
Found here: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelExtendedCi/11986420?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

```
=== RUN   TestStatsAreDeletedForDroppedTables/limit
    delete_stats_test.go:748: error executing 'ANALYZE t2;': pq: batch timestamp 1696004024.883056660,0 must be after replica GC threshold 1696004025.161557973,0
```

Jira issue: CRDB-31940

**Comment by michae2** [comment]
We were wondering if this was a dupe of https://github.com/cockroachdb/cockroach/issues/109380 but it looks like it failed after the skip mentioned in that issue was added.
