### ISSUE TITLE
schemafeed: flake/timeout in TestTableHistoryIngestionTracking

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#111572]
Found here: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/12012382?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

```
=== RUN   TestTableHistoryIngestionTracking
panic: test timed out after 4m55s
running tests:
  TestTableHistoryIngestionTracking (4m55s)
```

Jira issue: CRDB-31973

**Comment by rafiss** [comment]
The stuck goroutine is:
```
goroutine 104 [select, 4 minutes]:
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/schemafeed.(*schemaFeed).waitForTS(0xc0010a3900, {0x7a171d0, 0xc00022a000}, {0x8, 0x0, 0x0})
	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/schemafeed/pkg/ccl/changefeedccl/schemafeed/schema_feed.go:555 +0x317
github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/schemafeed.TestTableHistoryIngestionTracking.func7()
	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/schemafeed/pkg/ccl/changefeedccl/schemafeed/schema_feed_test.go:137 +0x6a
created by github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/schemafeed.TestTableHistoryIngestionTracking
	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/schemafeed/pkg/ccl/changefeedccl/schemafeed/schema_feed_test.go:137 +0x13a5
```

There might be a race in this part of the test code: https://github.com/cockroachdb/cockroach/blob/98d28a4c30f50ecd8f4e61eb285da627dabd3adc/pkg/ccl/changefeedccl/schemafeed/schema_feed_test.go#L117-L123

The context could be cancelled before the goroutine is executed.

**Comment by rafiss** [comment]
Actually I think my last comment is wrong - that part of the code doesn't seem racy.

I am able to reproduce this using: `./dev test --stress --race pkg/ccl/changefeedccl/schemafeed -f=TestTableHistoryIngestionTracking`
