### ISSUE TITLE
sql: flake in TestTenantLogic_new_schema_changer

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#111589]
Found here: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/12017189?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildTestsSection=true

```
=== RUN   TestTenantLogic_new_schema_changer/drop_database
    logic.go:2961: let $desc_count_pre_drop = 111
[16:53:42] --- progress: /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/1004/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/ccl/logictestccl/tests/3node-tenant/3node-tenant_test_/3node-tenant_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/new_schema_changer: 209 statements
    logic.go:2961: let $desc_count_post_drop = 97
    logic.go:2915:
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/1004/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/ccl/logictestccl/tests/3node-tenant/3node-tenant_test_/3node-tenant_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/new_schema_changer:804: select 111-97
        expected:
            13
        but found (query options: "") :
            14
    logic.go:2172:
         /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/1004/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/ccl/logictestccl/tests/3node-tenant/3node-tenant_test_/3node-tenant_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/new_schema_changer:809: too many errors encountered, skipping the rest of the input
```

Jira issue: CRDB-31980

**Comment by rafiss** [comment]
I don't see a clear lead on this one. The test is checking the difference between the number of descriptors before and after dropping a database and schema. I'm not sure how that could be non-deterministic, so let's see if this reproduces.

https://github.com/cockroachdb/cockroach/blob/98d28a4c30f50ecd8f4e61eb285da627dabd3adc/pkg/sql/logictest/testdata/logic_test/new_schema_changer#L774-L806

**Comment by knz** [comment]
could it be an instance of the planning retry bug that @yuzefovich just discovered?

**Comment by yuzefovich** [comment]
Seems unlikely because it requires that a distributed query results in an error (which usually involves a node crash) and the distsql physical planning was such that it used `scanNode.spans` directly (in this case we have `select count(*)` with no limit, so a new slice of `roachpb.Span`s should be allocated during physical planning).

**Comment by msbutler** [comment]
hit this here https://teamcity.cockroachdb.com/viewLog.html?buildId=12057906&buildTypeId=Cockroach_BazelEssentialCi

**Comment by msbutler** [comment]
is it worth skipping while people rush to get things in before branch cut?

**Comment by mgartner** [comment]
Saw this in another CI run here: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/12105975?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

**Comment by RaduBerinde** [comment]
I saw this multiple times today, once here: https://teamcity.cockroachdb.com/viewLog.html?buildId=12208956&buildTypeId=Cockroach_BazelEssentialCi

Please skip if it can't be fixed easily.
