### ISSUE TITLE
sql: improve index selection based on filters

### ISSUE THREAD

**Issue by rharding6373** [cockroachdb/cockroach#111515]
**Describe the problem**

In https://cockroachdb.zendesk.com/agent/tickets/18778 we resolved a slow update workload by introducing a new index, but we had to force the index in order to use it although performance was 6x+ better. The purpose of this issue is to investigate whether there are improvements we can make to the optimizer to pick the better index for this particular use case.

**To Reproduce**

```
SET CLUSTER SETTING sql.stats.system_tables_autostats.enabled = false;
CREATE TABLE dest (source_id INT, source_val STRING);
CREATE TABLE source (id INT, val STRING);
CREATE INDEX dest_idx1 ON dest (source_id) STORING (source_val);
CREATE INDEX dest_idx2 ON dest (source_val, source_id);
CREATE INDEX source_idx ON source (id) STORING (val);
ALTER TABLE dest INJECT STATISTICS '[
    {
        "avg_size": 20,
        "columns": [
            "source_id"
        ],
        "created_at": "2023-01-01 00:00:00.000000",
        "distinct_count": 40000,
        "name": "__auto__",
        "null_count": 0,
        "row_count": 1000000 
    },
{
        "avg_size": 1,
        "columns": [
            "source_val"
        ],
        "created_at": "2023-01-01 00:00:00.000000",
        "distinct_count": 2464,
        "histo_col_type": "",
        "name": "__auto__",
        "null_count": 990000,
        "row_count": 1000000 
    }
]';
ALTER TABLE source INJECT STATISTICS '[
    {
        "avg_size": 20,
        "columns": [
            "id"
        ],
        "created_at": "2023-01-01 00:00:00.000000",
        "distinct_count": 499000,
        "name": "__auto__",
        "null_count": 0,
        "row_count": 500000
    },
    {
        "avg_size": 50,
        "columns": [
            "val"
        ],
        "created_at": "2023-01-01 00:00:00.000000",
        "distinct_count": 400000,
        "name": "__auto__",
        "null_count": 0,
        "row_count": 500000
    }
]';

EXPLAIN (OPT) 
UPDATE dest 
SET source_val = source.val 
FROM source 
WHERE dest.source_id = source.id AND source_val IS NULL 
LIMIT 10000;
```

**Expected behavior**
The plan in the above example includes:
```
        ├── limit
        │    ├── inner-join (lookup dest@dest_idx1)
        │    │    ├── scan source
        │    │    └── filters
        │    │         └── source_val IS NULL
        │    └── 10000
```

But if you force the index using `UPDATE dest@dest_idx2`, it will scan the the table `dest` first before doing a lookup join on `source`. This behavior is potentially more desirable, since in the motivating example the workload was executing these updates until no `source_val` was null. As the workload progresses (and stats become stale), if we scan `source` first, we may have to perform many lookups to find an appropriate number of non-null `dest` values. By using the index whose first column is `source_val`, we're able to do a constrained scan and thus fewer lookups.

**Additional data / screenshots**
Internal slack thread about motivating issue: https://cockroachlabs.slack.com/archives/CHZ2NF811/p1695946105240299

**Environment:**
This repros on master.

Jira issue: CRDB-31943

**Comment by yuzefovich** [comment]
[triage meeting] putting it into 24.1 bucket to spend some time to investigate the root cause (perhaps it's a known issue) and then we'll re-prioritize.
