### ISSUE TITLE
kvserver: 23.2 replication microbenchmark regressions

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#111561]
Preliminary results were posted in https://docs.google.com/spreadsheets/d/1xYiEZlqL9tukSgZENvZIxgIHxrwo7c_PKFDdXCP6QkA/edit#gid=5. These may be fairly old, but we should look into the replication-related regressions until newer results are ready. These may or may not be false positives. In no particular order:

- [x] `kvserver/ReplicaProposal` @pavelkalinnikov
  - #113043
  - #113150
  - #113229
  - #113742
  - Performance diff is within a reasonable error margin.
- [x] `kvserver/BumpSideTransportClosed` @erikgrinaker
  - 15% regression, unknown cause, small in absolute terms
  - Benchmark sensitive to Go runtime: regressed from 220ns on 1.19 to 250ns on 1.20; went back to 220ns on 1.21.
- [x] `kvserver/raftentry/EntryCache` @pavelkalinnikov
  - single-digit % CPU regression. Hard to attribute to anything except Go runtime changes
  - Quite a bit more time spent in `raftpb.(*Entry).Size()`: 3.62s -> 4.48s
- [x] `kvserver/raftentry/EntryCacheClearTo` @pavelkalinnikov
  - Same as `kvserver/raftentry/EntryCache`
  - Particularly, more time is spent in proto size computation
- [x] `kvserver/logstore/LogStore_StoreEntries` @pavelkalinnikov
  - #113043
  - One more [finding](https://github.com/cockroachdb/cockroach/issues/111561#issuecomment-1790622372), fixed in #113742.
- [x] `kvserver/StoreRangeMerge` @erikgrinaker
  - ~10% allocs/op increase, but highly unreliable -- alloc/op and time decreased, and we don't particularly care about allocs/op here anyway.
  - @pavelkalinnikov measured after all the fixes. Allocations dropped to roughly level; but the 23.1 measurement is unreliable. CPU is still up by a couple of percent, but that's probably fine.
- [x] `kvserver/closedts/tracker/HeapTracker` @erikgrinaker
  - fixed in recent benchmarks

Jira issue: CRDB-31969

**Comment by erikgrinaker** [comment]
Weekly microbenchmark results are available in [#perf-ops](https://cockroachlabs.slack.com/archives/C05SHB3GAGP).

**Comment by erikgrinaker** [comment]
Here's the latest KV microbenchmark results (compared with 23.1): https://docs.google.com/spreadsheets/d/12cla5YkEpAd1gX3nMushoN354yuurO67k7PfPs5wI64/edit#gid=5

**Comment by erikgrinaker** [comment]
Looked at `BumpSideTransportClosed`. No significant profile changes nor code changes -- Go runtime change? ~15% diff, small in absolute terms, but higher variance.

```
name                        old time/op  new time/op  delta
BumpSideTransportClosed-24   225ns ± 0%   261ns ±11%  +16.38%  (p=0.000 n=9+10)
```

Before: [cpu-before.pprof.gz](https://github.com/cockroachdb/cockroach/files/13127348/cpu-before.pprof.gz)

<img width="1349" alt="Screenshot 2023-10-24 at 22 51 52" src="https://github.com/cockroachdb/cockroach/assets/644420/16dd4c33-f33a-426b-92d9-d17985261a9c">

After: [cpu-after.pprof.gz](https://github.com/cockroachdb/cockroach/files/13127357/cpu-after.pprof.gz)

<img width="1352" alt="Screenshot 2023-10-24 at 22 51 40" src="https://github.com/cockroachdb/cockroach/assets/644420/792a1eeb-3f11-47cb-ab8e-5859b94aa585">

**Comment by pavelkalinnikov** [comment]
For `kvserver/logstore/LogStore_StoreEntries` allocations regression, there is a difference between `23.1` and `master`:

<img width="1916" alt="Screenshot 2023-10-25 at 13 14 22" src="https://github.com/cockroachdb/cockroach/assets/3757441/3a05cf7a-f0b5-4824-8b6a-6ed39a338775">

<img width="961" alt="Screenshot 2023-10-25 at 13 14 28" src="https://github.com/cockroachdb/cockroach/assets/3757441/d26d9405-f5f3-4cdc-b13f-04d5840fde0f">

We're seeing that allocations doubled to 2 allocs/op because there is a new allocation in `clusterversion` package.

**Comment by jbowens** [comment]
> @jbowens Has storage.newPebbleBatch started using [this](https://github.com/cockroachdb/cockroach/blob/e8367041383e1123b2f71cfd4b54439ab4ac56b8/pkg/storage/pebble_batch.go#L119) version check recently?

Yeah, that version check is new in 23.2. It's unfortunate that allocates. I suppose we could subscribe to cluster version progressions (IIRC there's an API to do this), and stash the current cluster version on the Engine for use in `newBatch`.

**Comment by pavelkalinnikov** [comment]
@jbowens I think #113043 should fix the thing.

**Comment by erikgrinaker** [comment]
I wonder if it's worth running some of these benchmarks with different Go versions, since we're not able to find clear explanations for a couple of these regressions. If there is a performance regression in Go itself then we'd probably want to know about that.

**Comment by pavelkalinnikov** [comment]
In `ReplicaProposal` benchmark (which is more like an end-to-end thing), the `IsActive` allocations add up as 1% of all allocations:

<img width="962" alt="Screenshot 2023-10-26 at 13 23 33" src="https://github.com/cockroachdb/cockroach/assets/3757441/0b70f595-f43e-4809-9f25-461b1edd45af">

The remaining ~10% difference is yet to be explained.

**Comment by pavelkalinnikov** [comment]
@erikgrinaker Given the above, I suspect that Raft stack cost got increased, so the thing you observed `kvserver/StoreRangeMerge` is probably impacted too.

**Comment by sumeerbhola** [comment]
> The notable addition is updateProposalQuotaRaftMuLocked. Added recently with the replication admission control? CC @sumeerbhola

Can you post a link to the "after" memory profile file?

**Comment by aadityasondhi** [comment]
> The notable addition is `updateProposalQuotaRaftMuLocked`. Added recently with the replication admission control?

Took a quick look in the code. Tracking those down `updateProposalQuotaRaftMuLocked`, I see most of the new allocs come from this bit of code with all the `get` functions. Maybe we can do something about it.

https://github.com/cockroachdb/cockroach/blob/master/pkg/kv/kvserver/flow_control_replica_integration.go#L298-L302

**Comment by kvoli** [comment]
> Another one is the error handling bonanza in HandleRaftRequestSent. Added recently in https://github.com/cockroachdb/cockroach/pull/105122 and https://github.com/cockroachdb/cockroach/pull/105267. Gut feeling is that we should not see these errors in this test. CC @kvoli as reviewer of these PRs - if you remember the context, are these errors in the profile legit?


Unlikely to see the errors in actual deployments as they are created for missing/unexpected `locality` specification. 

We can drop them, seeing they are used only in `VInfof(5,...)` -- and either check `V(5)` before doing work, or entirely.

- https://github.com/cockroachdb/cockroach/issues/111148
- https://github.com/cockroachdb/cockroach/issues/111142

**Comment by erikgrinaker** [comment]
@pavelkalinnikov We're planning to cut the .0 branch today, can we get the remaining fixes backported before then?

**Comment by pavelkalinnikov** [comment]
There is only #113043. I probably can workaround the linter and land it today.

**Comment by pavelkalinnikov** [comment]
[New](https://docs.google.com/spreadsheets/d/1uFVOtAtla43a5EC7Q-SMouA69g9-emnezGG_YpuydHc/edit#gid=5) results from this Monday. These don't yet contain the proto Unmarshal fix, but some/all other optimizations should be in already.

**Comment by pavelkalinnikov** [comment]
Taking another (first one was [here](https://github.com/cockroachdb/cockroach/issues/111561#issuecomment-1779144975)) look at `LogStore_StoreEntries` after all the fixes.

`23.1`:
```
BenchmarkLogStore_StoreEntries/bytes=1.0_KiB
BenchmarkLogStore_StoreEntries/bytes=1.0_KiB-24                   924716              1267 ns/op             157 B/op          0 allocs/op
BenchmarkLogStore_StoreEntries/bytes=256_KiB
BenchmarkLogStore_StoreEntries/bytes=256_KiB-24                    31063             38715 ns/op             239 B/op          0 allocs/op
BenchmarkLogStore_StoreEntries/bytes=512_KiB
BenchmarkLogStore_StoreEntries/bytes=512_KiB-24                     9567            121584 ns/op             558 B/op          0 allocs/op
BenchmarkLogStore_StoreEntries/bytes=1.0_MiB
BenchmarkLogStore_StoreEntries/bytes=1.0_MiB-24                     1256            855636 ns/op         2207006 B/op          4 allocs/op
BenchmarkLogStore_StoreEntries/bytes=2.0_MiB
BenchmarkLogStore_StoreEntries/bytes=2.0_MiB-24                      572           1848153 ns/op         4655889 B/op          5 allocs/op
```

`master`:
```
BenchmarkLogStore_StoreEntries/bytes=1.0_KiB
BenchmarkLogStore_StoreEntries/bytes=1.0_KiB-24                   705525              1429 ns/op             333 B/op          1 allocs/op
BenchmarkLogStore_StoreEntries/bytes=256_KiB
BenchmarkLogStore_StoreEntries/bytes=256_KiB-24                    28836             40695 ns/op             402 B/op          1 allocs/op
BenchmarkLogStore_StoreEntries/bytes=512_KiB
BenchmarkLogStore_StoreEntries/bytes=512_KiB-24                     9249            120265 ns/op             576 B/op          1 allocs/op
BenchmarkLogStore_StoreEntries/bytes=1.0_MiB
BenchmarkLogStore_StoreEntries/bytes=1.0_MiB-24                     1346            844536 ns/op         2187245 B/op          4 allocs/op
BenchmarkLogStore_StoreEntries/bytes=2.0_MiB
BenchmarkLogStore_StoreEntries/bytes=2.0_MiB-24                      645           1716122 ns/op         4522320 B/op          5 allocs/op
```

The "big" tests are even. The "small" tests allocate a bit more, and therefore are slower. Figuring out the reason now.

**Comment by erikgrinaker** [comment]
I'm not sure we necessarily care about this allocation. The IO cost of log appends is probably high enough that the allocation doesn't make a significant difference, and this cost is constant for all appended entries. This benchmark uses an in-memory engine, which hides the IO cost (and we're only benchmarking the inner logic).

I suppose we could pool these to amortize the allocation cost though.

**Comment by pavelkalinnikov** [comment]
Yeah, feel similarly. I guess we can leave it then, just need to be mindful that it might impact other microbenchmarks that are yet to be investigated.

**Comment by erikgrinaker** [comment]
Can you try to pool them and see if it makes any difference on `BenchmarkKV/Insert` in `pkg/sql/tests`?

**Comment by pavelkalinnikov** [comment]
Turns out there is a simple fix, so we're just fixing the thing.
#113742

**Comment by pavelkalinnikov** [comment]
The repl-specific part is done. If there is any Go-/proto-induced regression, the impact of it should be investigated on a broader scope.
