### ISSUE TITLE
sql: add foreign key references to stmt bundle schema

### ISSUE THREAD

**Issue by rharding6373** [cockroachdb/cockroach#111585]
Today, statement bundles of queries that may involve foreign key cascades may not include target tables of the cascade. That is, we include the parent table in schema.sql, but not the child tables that may reference it. For example, in https://github.com/cockroachlabs/support/issues/2630 there was a delete with multiple cascades to different tables, but none of the relevant child tables are included in the schema. We should look into adding this to the statement bundle.

Jira issue: CRDB-31977
Epic: CRDB-34181

**Comment by rytaft** [comment]
[offline discussion] we think this was already done by Becca (at least for the case of FKs that aren't self-referencing)
