### ISSUE TITLE
license: Update the license metadata to add an additional parameter

### ISSUE THREAD

**Issue by mwang1026** [cockroachdb/cockroach#111501]
Today, in addition to the actual "key" uuid itself, the encrypted license object also includes some metadata:

- License Type
- Issued To
- Expires

Requirements
- Add an additional piece of metadata, of type `String` called `Uses`.
- Keys generated with the `Uses` metadata should be "backward compatible" (e.g. usable with older version) and/or we should have clear idea of which versions they're compatible with
- Backported and/or usable on all supported CRDB versions (22.2, 23.1, forthcoming 23.2)
- CRL has a way to, given a key, inspect the metadata

Jira issue: CRDB-31935

**Comment by dt** [comment]
#111836
