### ISSUE TITLE
tabledesc: validate the KeyColumnIDs + KeySuffixColumnIDs contains all PK columns

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#111677]
We should validate that KeyColumnIDs union KeySuffixColumnIDs contains all PK columns here: https://github.com/cockroachdb/cockroach/blob/7e4233d09edef5420b8f12d917112ce762ac1855/pkg/sql/catalog/tabledesc/validate.go#L1277

This would have likely helped debug an invalid system table descriptor struct, see https://cockroachlabs.slack.com/archives/C01RX2G8LT1/p1696010172771349.

Jira issue: CRDB-32013

**Comment by rafiss** [comment]
This validation was added in https://github.com/cockroachdb/cockroach/pull/105828 which will be in 23.2.

**Comment by mgartner** [comment]
Is this validation performed on system table descriptors, like the one described in the Slack link? If it is, I'd be curious to know why it didn't catch the bad descriptor before the more confusing execution-time error. cc @zachlite
