### ISSUE TITLE
backupccl: flaky TestDataDriven_restore_regionless_mixed_version

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#111789]
Noticed in: https://teamcity.cockroachdb.com/viewLog.html?buildId=12055175&buildTypeId=Cockroach_BazelEssentialCi

@annrpom assigning this to you, since you've been around that code recently!

Jira issue: CRDB-32071

**Comment by annrpom** [comment]
ah rip i need to use expect-error-regex. should've caught that, but thank you for assigning me @adityamaru !
