### ISSUE TITLE
cluster-ui: update tooltips on db pages to reflect logical/physical span stats

### ISSUE THREAD

**Issue by THardy98** [cockroachdb/cockroach#111752]
With the changes from [this PR](https://github.com/cockroachdb/cockroach/pull/108852) to return _logical_ span statistics along with _physical_ span statistics, we should distinguish this clearly in our tooltips where these metrics are surface (primarily, the database pages). Currently, it is not clear which metrics are pre/post replicated and which are logical/physical.

Jira issue: CRDB-32059

**Comment by nkodali** [comment]
Closing as this is no longer relevant given the new databases page on 24.3.
