### ISSUE TITLE
sql/sem/tree: `if` with identical `then` and `else` blocks in `sql/sem/tree/expr.go`

### ISSUE THREAD

**Issue by chavacava** [cockroachdb/cockroach#111779]
https://github.com/cockroachdb/cockroach/blob/2da2993c4ad5a7b07a80ae42ba3f78e8018d9e64/pkg/sql/sem/tree/expr.go#L803-L815

Both branches of the conditional at line 803 are identical.

(found by [revive](https://github.com/mgechev/revive) while testing it on cockroach code base)

Jira issue: CRDB-32066

**Comment by yuzefovich** [comment]
Thanks for filing the issue! Please feel free to open up a PR to remove this duplication.
