### ISSUE TITLE
sql: v22.2.14: could not find ... in enum × representation with arrays

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#111799]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4526136718/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4526136718/?referrer=webhooks_plugin)

Panic Message:

```
error.go:89: unexpected error from the vectorized engine: could not find [× × ×] in enum × representation × ×
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:89
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.InternalError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:195
  | github.com/cockroachdb/cockroach/pkg/sql/colfetcher.(*ColBatchScan).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colfetcher/colbatch_scan.go:111
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils.(*CancelChecker).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils/cancel_checker.go:59
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:116
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:124
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils.(*vectorTypeEnforcer).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils/operator.go:135
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecbase.constInt64Op.Next
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/colexec/colexecbase/const.eg.go:368
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils.(*vectorTypeEnforcer).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils/operator.go:135
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*defaultBuiltinFuncOperator).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/builtin_funcs.go:46
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecsel.(*selGTInt64Int64ConstOp).Next
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/colexec/colexecsel/selection_ops.eg.go:43791
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecbase.(*simpleProjectOp).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecbase/simple_project.go:124
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*limitOp).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/limit.go:47
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:116
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:124
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).nextAdapter
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:252
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:256
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:299
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:320
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:757
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1764
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1472
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1599
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1202
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:694
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:131
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2440
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:130
Wraps: (3) unexpected error from the vectorized engine
Wraps: (4) could not find [× × ×] in enum × representation × ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | -- cause hidden behind barrier
  | could not find [× × ×] in enum × representation × ×
  | (1)
  | Wraps: (2) attached stack trace
  |   -- stack trace:
  |   | github.com/cockroachdb/cockroach/pkg/sql/types.(*T).EnumGetIdxOfPhysical
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/types/pkg/sql/types/types.go:2577
  |   | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.GetEnumComponentsFromPhysicalRep
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/datum.go:4670
  |   | github.com/cockroachdb/cockroach/pkg/sql/rowenc/valueside.DecodeUntaggedDatum
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/rowenc/valueside/decode.go:213
  |   | github.com/cockroachdb/cockroach/pkg/sql/rowenc/valueside.decodeArray
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/rowenc/valueside/array.go:88
  |   | github.com/cockroachdb/cockroach/pkg/sql/rowenc/valueside.DecodeUntaggedDatum
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/rowenc/valueside/decode.go:205
  |   | github.com/cockroachdb/cockroach/pkg/sql/colencoding.DecodeTableValueToCol
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colencoding/value_encoding.go:114
  |   | github.com/cockroachdb/cockroach/pkg/sql/colfetcher.(*cFetcher).processValueBytes
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colfetcher/cfetcher.go:1180
  |   | github.com/cockroachdb/cockroach/pkg/sql/colfetcher.(*cFetcher).processValue
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colfetcher/cfetcher.go:981
  |   | github.com/cockroachdb/cockroach/pkg/sql/colfetcher.(*cFetcher).NextBatch
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colfetcher/cfetcher.go:760
  |   | github.com/cockroachdb/cockroach/pkg/sql/colfetcher.(*ColBatchScan).Next
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colfetcher/colbatch_scan.go:109
  |   | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils.(*CancelChecker).Next
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils/cancel_checker.go:59
  |   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).next
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:116
  |   | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  |   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).Next
  | ...
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor_exec.go#L129-L131](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor_exec.go#L129-L131)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor_exec.go#L2439-L2441](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor_exec.go#L2439-L2441)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor_exec.go#L130-L132](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor_exec.go#L130-L132)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor_exec.go#L693-L695](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor_exec.go#L693-L695)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor_exec.go#L1201-L1203](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor_exec.go#L1201-L1203)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor_exec.go#L1598-L1600](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor_exec.go#L1598-L1600)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/distsql_running.go#L1471-L1473](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/distsql_running.go#L1471-L1473)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/distsql_running.go#L1763-L1765](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/distsql_running.go#L1763-L1765)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/distsql_running.go#L756-L758](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/distsql_running.go#L756-L758)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colflow/vectorized_flow.go#L319-L321](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colflow/vectorized_flow.go#L319-L321)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colflow/flow_coordinator.go#L298-L300](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colflow/flow_coordinator.go#L298-L300)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colflow/flow_coordinator.go#L255-L257](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colflow/flow_coordinator.go#L255-L257)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colflow/flow_coordinator.go#L251-L253](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colflow/flow_coordinator.go#L251-L253)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colflow/stats.go#L123-L125](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colflow/stats.go#L123-L125)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colflow/stats.go#L115-L117](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colflow/stats.go#L115-L117)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexec/limit.go#L46-L48](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexec/limit.go#L46-L48)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexec/colexecbase/simple_project.go#L123-L125](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexec/colexecbase/simple_project.go#L123-L125)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/bazel-out/k8-opt/bin/pkg/sql/colexec/colexecsel/selection_ops.eg.go#L43790-L43792](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/bazel-out/k8-opt/bin/pkg/sql/colexec/colexecsel/selection_ops.eg.go#L43790-L43792)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexec/builtin_funcs.go#L45-L47](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexec/builtin_funcs.go#L45-L47)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexec/colexecutils/operator.go#L134-L136](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexec/colexecutils/operator.go#L134-L136)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/bazel-out/k8-opt/bin/pkg/sql/colexec/colexecbase/const.eg.go#L367-L369](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/bazel-out/k8-opt/bin/pkg/sql/colexec/colexecbase/const.eg.go#L367-L369)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexec/colexecutils/operator.go#L134-L136](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexec/colexecutils/operator.go#L134-L136)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colflow/stats.go#L123-L125](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colflow/stats.go#L123-L125)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colflow/stats.go#L115-L117](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colflow/stats.go#L115-L117)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexec/colexecutils/cancel_checker.go#L58-L60](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexec/colexecutils/cancel_checker.go#L58-L60)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colfetcher/colbatch_scan.go#L110-L112](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colfetcher/colbatch_scan.go#L110-L112)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexecerror/error.go#L194-L196](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexecerror/error.go#L194-L196)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexecerror/error.go#L88-L90](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexecerror/error.go#L88-L90)
</details>

```
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 130
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithProfiling at line 2440
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt.func1 at line 131
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 694
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchToExecutionEngine at line 1202
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithDistSQLEngine at line 1599
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRunAll at line 1472
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRun at line 1764
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).Run at line 757
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlow).Run at line 320
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).Run at line 299
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).next at line 256
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).nextAdapter at line 252
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).Next at line 124
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).next at line 116
pkg/sql/colexec/limit.go in pkg/sql/colexec.(*limitOp).Next at line 47
pkg/sql/colexec/colexecbase/simple_project.go in pkg/sql/colexec/colexecbase.(*simpleProjectOp).Next at line 124
bazel-out/k8-opt/bin/pkg/sql/colexec/colexecsel/selection_ops.eg.go in pkg/sql/colexec/colexecsel.(*selGTInt64Int64ConstOp).Next at line 43791
pkg/sql/colexec/builtin_funcs.go in pkg/sql/colexec.(*defaultBuiltinFuncOperator).Next at line 46
pkg/sql/colexec/colexecutils/operator.go in pkg/sql/colexec/colexecutils.(*vectorTypeEnforcer).Next at line 135
bazel-out/k8-opt/bin/pkg/sql/colexec/colexecbase/const.eg.go in pkg/sql/colexec/colexecbase.constInt64Op.Next at line 368
pkg/sql/colexec/colexecutils/operator.go in pkg/sql/colexec/colexecutils.(*vectorTypeEnforcer).Next at line 135
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).Next at line 124
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).next at line 116
pkg/sql/colexec/colexecutils/cancel_checker.go in pkg/sql/colexec/colexecutils.(*CancelChecker).Next at line 59
pkg/sql/colfetcher/colbatch_scan.go in pkg/sql/colfetcher.(*ColBatchScan).Next at line 111
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.InternalError at line 195
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1 at line 89
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v22.2.14 |
| Go Version | go1.19.6 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v22.2.14 |
| Cockroach SHA | af6752b2faf39115fd322e9db76421e71b76507d |
| # of CPUs | 2 |
| # of Goroutines | 482 |

Jira issue: CRDB-32075

**Comment by DrewKimball** [comment]
Unable to reproduce.
