### ISSUE TITLE
`if` with identical `then` and `else` blocks in `pkg/util/encoding/encoding_test.go`

### ISSUE THREAD

**Issue by chavacava** [cockroachdb/cockroach#111898]
https://github.com/cockroachdb/cockroach/blob/2da2993c4ad5a7b07a80ae42ba3f78e8018d9e64/pkg/util/encoding/encoding_test.go#L961-L967

It seems the `else` block should use the _descending_ versions of _EncodeBitArray_ and _DecodeBitArray_:
```go
if dir == Ascending {
    buf = EncodeBitArrayAscending(nil, test)
    remainder, x, err = DecodeBitArrayAscending(buf)
} else {
    buf = EncodeBitArrayDescending(nil, test)
    remainder, x, err = DecodeBitArrayDescending(buf)
}
```

(found by [revive](https://github.com/mgechev/revive) while testing it on cockroach code base)

Jira issue: CRDB-32122

**Comment by rickystewart** [comment]
This code is not owned by dev-inf.

**Comment by yuzefovich** [comment]
Thanks for opening up this issue! I agree that this is a mistake in the test - please feel free to open up a PR to address it 😃
