### ISSUE TITLE
ui: jobs page lists erroneous completion time

### ISSUE THREAD

**Issue by stevendanna** [cockroachdb/cockroach#111869]
**Describe the problem**

The Jobs page lists a Completed Time even when the job isn't finished:

<img width="1448" alt="Screenshot 2023-10-05 at 21 33 41" src="https://github.com/cockroachdb/cockroach/assets/852371/b3f477ef-4790-41bc-80c2-87a9517d0c5d">

The actual completion time (finished) is not set:

```
-[ RECORD 5 ]
job_id               | 905928855706632193
job_type             | CHANGEFEED
description          | CREATE CHANGEFEED FOR TABLE users INTO 'null:'
statement            | 
user_name            | demo
descriptor_ids       | {106}
status               | running
running_status       | running: resolved=1696538637.746067000,0
created              | 2023-10-05 20:32:26.297209+00
started              | 2023-10-05 20:32:26.312285+00
finished             | NULL
modified             | 2023-10-05 20:44:30.824021+00
fraction_completed   | NULL
high_water_timestamp | 1696538667645146000.0000000000
error                | 
coordinator_id       | 1
trace_id             | 1818017730987099505
last_run             | 2023-10-05 20:32:26.312286+00
next_run             | 2023-10-05 20:32:56.312286+00
num_runs             | 1
execution_errors     | NULL
execution_events     | NULL
```

I think this is probably because we call TimestampToMoment on the Finshed field:

https://github.com/cockroachdb/cockroach/blob/36e97fa12e8a591937926d22019a6228f6cb87dd/pkg/ui/workspaces/cluster-ui/src/jobs/jobsPage/jobsTable.tsx#L223

which returns the current time if null is given:

https://github.com/cockroachdb/cockroach/blob/36e97fa12e8a591937926d22019a6228f6cb87dd/pkg/ui/workspaces/cluster-ui/src/util/convert.ts#L51

Jira issue: CRDB-32105

**Comment by maryliag** [comment]
Closing as a dup of #109204, which is solved by #110366
