### ISSUE TITLE
Multiple Active Portals error when using Statement.setMaxRows() [Postgres JDBC driver]

### ISSUE THREAD

**Issue by browland** [cockroachdb/cockroach#111853]
**Describe the problem**

We're using Cockroach V23.1.10, along with the Postgres JDBC driver version 42.6.0.

We're using Spring Batch, specifically the `JdbcPagingItemReader`.  When reading a page of results, it calls `Statement.setMaxRows()` with the chunk size we've configured.  We provide the SQL query to get the page, and this happens to have a `LIMIT` clause set (we're using keyset pagination as recommended).  When this is done within a transaction, any subsequent query within the same transaction fails due to "Multiple Active Portals not supported" error.  

I've seem similar bugs reported, but we're definitely consuming the full `ResultSet` from the first query and closing it.

We can work around the issue by creating a patched version of the Spring Batch class `JdbcPagingItemReader`, with the call to `Statement.setMaxRows()` removed.

The documentation for `Statement.setMaxRows()` says it `Retrieves the maximum number of rows that a ResultSet object produced by this Statement object can contain. If this limit is exceeded, the excess rows are silently dropped.`. This doesn't seem to suggest a cursor would be created.  Additionally, we're providing a LIMIT clause equal to the value passed to setMaxSize() and we're consuming all the results, yet a cursor appears to be left open.

**To Reproduce**

I'll also provide code, but here are the steps:

1. Ensure you are within a transaction - `Connection.setAutocommit(false)`
2. Execute a query with a LIMIT clause while also setting `Statement.setMaxRows()` to the same value as specified by the `LIMIT`
3. Consume the entire `ResultSet`, close it, and close the corresponding `Statement`
4. Create a new `Statement` and run a second query within the same transaction
5. Regardless of what the second query is, we get the "Multiple Active Portals not supported" error.

**Expected behavior**
We should be able to perform additional queries within the same transaction, as we've consumed all results from the query and closed the `ResultSet` and `Statement`.

**Additional data / screenshots**
The issue can be reproduced with this code:

```
import java.sql.*;

/**
 * Create a database named 'test', and ensure you have a user named 'test' (or modify the connection URL to match the 
 * user/database name you're using).
 * 
 * Then create a table:
 *
 * CREATE TABLE TEST (id INT8 NOT NULL);
 * INSERT INTO TEST VALUES (1);
 * 
 * Now run this class.
 */
public class Reproduce {
    private static final String CONNECTION_STRING = "jdbc:postgresql://localhost:26257/test?user=test";

    public static void main(String[] args) throws SQLException {
        Connection conn = null;
        Statement stmnt;
        ResultSet rs;

        try {
            // Create a connection and ensure we use transactions
            conn = DriverManager.getConnection(CONNECTION_STRING);
            conn.setAutoCommit(false);

            // Execute first query and consume all results
            stmnt = conn.createStatement();
            stmnt.setMaxRows(1);
            rs = stmnt.executeQuery("select * from test limit 1");
            consumeResultsAndClose(rs, stmnt);

            // Execute the second query to trigger the issue
            stmnt = conn.createStatement();
            rs = stmnt.executeQuery("select * from test limit 1");
            consumeResultsAndClose(rs, stmnt);
        } finally {
            if (conn != null) {
                conn.close();
            }
        }
    }

    private static void consumeResultsAndClose(ResultSet rs, Statement stmnt) throws SQLException {
        // Ensure ResultSet read fully
        while(rs.next());

        rs.close();
        stmnt.close();
    }
}
```
This code fails due to:
```
Exception in thread "main" org.postgresql.util.PSQLException: ERROR: unimplemented: multiple active portals not supported, please set session variable multiple_active_portals_enabled to true. Note: this feature is in preview
  Detail: cannot perform operation sql.PrepareStmt while a different portal is open
  Hint: You have attempted to use a feature that is not yet implemented.
See: https://go.crdb.dev/issue-v/40195/v23.1
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:498)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:415)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:335)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:321)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:297)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:246)
	at Reproduce.main(Reproduce.java:34)
```

**Environment:**
 - CockroachDB version V23.1.10
 - Server OS: Docker container running Red Hat Enterprise Linux 8.7
 - Client app: Java - Postgres JDBC driver version 42.6.0

**Additional context**
We're unable to use Spring Batch with JDBC without a workaround to patch one of the Spring Batch classes.  In contrast, we're able to use Spring Batch with the Oracle DB without modifications.

Thanks in advance for taking a look into this.

Jira issue: CRDB-32097

**Comment by dikshant** [comment]
Please set `multiple_active_portals_enabled=true` as a session variable. It is also [described](https://www.cockroachlabs.com/docs/v23.1/postgresql-compatibility#multiple-active-portals) in our docs.

**Comment by dikshant** [comment]
However we need to validate if `stmnt.close();` closes the portal.

**Comment by rafiss** [comment]
Please try the suggestion above. I will close this, but if it doesn't work, then feel free to re-open.
