### ISSUE TITLE
roachprod: azure credential refresh using cli

### ISSUE THREAD

**Issue by smg260** [cockroachdb/cockroach#111843]
Roachtest users have the option to authenticate to the Azure SDK via providing environment variables (secret), or having the `az` cli tool installed, and authenticating with that before hand.

In the latter case, the token provided expires after 1 hour, as CLI commands are supposed to be short lived. When running multiple roachtests, this duration can easily be passed. 

We should ensure that the token is refreshed before expiry, to prevent authentication errors on running roachtests.

Jira issue: CRDB-32091

**Comment by srosenberg** [comment]
Related to: https://github.com/cockroachdb/cockroach/issues/77614
