### ISSUE TITLE
Sentry: error.go:89: unexpected error from the vectorized engine: could not find [× × × × × × × × × × ×] in enum × representation × ×
(1) assertion failure
Wraps: (2) attached stack trac...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#111800]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4526144662/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4526144662/?referrer=webhooks_plugin)

Panic Message:

```
error.go:89: unexpected error from the vectorized engine: could not find [× × × × × × × × × × ×] in enum × representation × ×
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:89
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.InternalError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:195
  | github.com/cockroachdb/cockroach/pkg/sql/colfetcher.(*ColIndexJoin).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colfetcher/index_join.go:228
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils.(*CancelChecker).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils/cancel_checker.go:59
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:116
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:124
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).nextAdapter
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:252
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:256
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:299
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:320
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:757
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1764
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1472
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1599
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1202
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:694
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:131
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2440
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:130
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execPortal
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:220
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2207
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2209
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2054
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:882
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:769
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (3) unexpected error from the vectorized engine
Wraps: (4) could not find [× × × × × × × × × × ×] in enum × representation × ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | -- cause hidden behind barrier
  | could not find [× × × × × × × × × × ×] in enum × representation × ×
  | (1)
  | Wraps: (2) attached stack trace
  |   -- stack trace:
  |   | github.com/cockroachdb/cockroach/pkg/sql/types.(*T).EnumGetIdxOfPhysical
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/types/pkg/sql/types/types.go:2577
  |   | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.GetEnumComponentsFromPhysicalRep
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/datum.go:4670
  |   | github.com/cockroachdb/cockroach/pkg/sql/rowenc/valueside.DecodeUntaggedDatum
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/rowenc/valueside/decode.go:213
  |   | github.com/cockroachdb/cockroach/pkg/sql/rowenc/valueside.decodeArray
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/rowenc/valueside/array.go:88
  |   | github.com/cockroachdb/cockroach/pkg/sql/rowenc/valueside.DecodeUntaggedDatum
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/rowenc/valueside/decode.go:205
  |   | github.com/cockroachdb/cockroach/pkg/sql/colencoding.DecodeTableValueToCol
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colencoding/value_encoding.go:114
  |   | github.com/cockroachdb/cockroach/pkg/sql/colfetcher.(*cFetcher).processValueBytes
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colfetcher/cfetcher.go:1180
  |   | github.com/cockroachdb/cockroach/pkg/sql/colfetcher.(*cFetcher).processValue
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colfetcher/cfetcher.go:981
  |   | github.com/cockroachdb/cockroach/pkg/sql/colfetcher.(*cFetcher).NextBatch
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colfetcher/cfetcher.go:760
  |   | github.com/cockroachdb/cockroach/pkg/sql/colfetcher.(*ColIndexJoin).Next
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colfetcher/index_join.go:226
  |   | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils.(*CancelChecker).Next
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils/cancel_checker.go:59
  |   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).next
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:116
  |   | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  |   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).Next
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:124
  |   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).nextAdapter
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:252
  |   | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  |   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).next
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:256
  |   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).Run
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:299
  |   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Run
  |   | 	github.com/cockro...
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/pgwire/conn.go#L768-L770](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/pgwire/conn.go#L768-L770)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor.go#L881-L883](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor.go#L881-L883)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor.go#L2053-L2055](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor.go#L2053-L2055)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor.go#L2208-L2210](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor.go#L2208-L2210)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor.go#L2206-L2208](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor.go#L2206-L2208)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor_exec.go#L219-L221](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor_exec.go#L219-L221)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor_exec.go#L129-L131](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor_exec.go#L129-L131)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor_exec.go#L2439-L2441](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor_exec.go#L2439-L2441)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor_exec.go#L130-L132](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor_exec.go#L130-L132)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor_exec.go#L693-L695](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor_exec.go#L693-L695)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor_exec.go#L1201-L1203](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor_exec.go#L1201-L1203)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor_exec.go#L1598-L1600](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor_exec.go#L1598-L1600)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/distsql_running.go#L1471-L1473](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/distsql_running.go#L1471-L1473)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/distsql_running.go#L1763-L1765](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/distsql_running.go#L1763-L1765)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/distsql_running.go#L756-L758](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/distsql_running.go#L756-L758)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colflow/vectorized_flow.go#L319-L321](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colflow/vectorized_flow.go#L319-L321)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colflow/flow_coordinator.go#L298-L300](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colflow/flow_coordinator.go#L298-L300)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colflow/flow_coordinator.go#L255-L257](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colflow/flow_coordinator.go#L255-L257)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colflow/flow_coordinator.go#L251-L253](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colflow/flow_coordinator.go#L251-L253)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colflow/stats.go#L123-L125](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colflow/stats.go#L123-L125)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colflow/stats.go#L115-L117](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colflow/stats.go#L115-L117)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexec/colexecutils/cancel_checker.go#L58-L60](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexec/colexecutils/cancel_checker.go#L58-L60)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colfetcher/index_join.go#L227-L229](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colfetcher/index_join.go#L227-L229)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexecerror/error.go#L194-L196](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexecerror/error.go#L194-L196)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexecerror/error.go#L88-L90](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexecerror/error.go#L88-L90)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommandsAsync.func1 at line 769
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 882
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 2054
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 2209
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd.func2 at line 2207
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execPortal at line 220
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 130
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithProfiling at line 2440
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt.func1 at line 131
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 694
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchToExecutionEngine at line 1202
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithDistSQLEngine at line 1599
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRunAll at line 1472
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRun at line 1764
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).Run at line 757
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlow).Run at line 320
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).Run at line 299
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).next at line 256
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).nextAdapter at line 252
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).Next at line 124
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).next at line 116
pkg/sql/colexec/colexecutils/cancel_checker.go in pkg/sql/colexec/colexecutils.(*CancelChecker).Next at line 59
pkg/sql/colfetcher/index_join.go in pkg/sql/colfetcher.(*ColIndexJoin).Next at line 228
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.InternalError at line 195
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1 at line 89
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v22.2.14 |
| Go Version | go1.19.6 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v22.2.14 |
| Cockroach SHA | af6752b2faf39115fd322e9db76421e71b76507d |
| # of CPUs | 2 |
| # of Goroutines | 490 |

Jira issue: CRDB-32076

**Comment by yuzefovich** [comment]
dup of #111799
