### ISSUE TITLE
kvserver: Evaluate the cost of checking whether a span config update is a PTS update before enqueuing

### ISSUE THREAD

**Issue by shralex** [cockroachdb/cockroach#111837]
We've recently made a change where we only enqueue updates that aren't a PTS change.  The remaining question is the cost of this check.

Jira issue: CRDB-32087

**Comment by andrewbaptist** [comment]
The initial test on this was not looking good - there was a big performance hit when making a "no-op" span config change on a system with 2M ranges. I didn't capture CPU and it was hard to reproduce.
![image](https://github.com/cockroachdb/cockroach/assets/46975918/74a5578e-ffef-41d7-9310-c27821becd73)

**Comment by andrewbaptist** [comment]
I reran this test on a cluster without rangefeeds and running at a "normal" usage level. I grabbed a few CPU profiles before and after running the change, and watched the latency. There was no noticeable change in P99 latency and the CPU profiles looked good.
