### ISSUE TITLE
clusterversion: remove old guidance to delete gates older than "5 releases" ago

### ISSUE THREAD

**Issue by celiala** [cockroachdb/cockroach#111889]
### What
Remove the check that [forces the deletion of old version gates as part of creating gates for the upcoming release](https://github.com/cockroachdb/cockroach/blob/master/pkg/clusterversion/keyed_versions.go#L82-L93), i.e. "found versions that are always active because 2.23 is already released; these should be removed".

### Why
- We've intentionally decoupled the two tasks of deleting old gates from minting the upcoming release, so that the release team can focus on minting the release, and delegate the deletion of old gates to those team owners (see process from 22.2 https://github.com/cockroachdb/cockroach/issues/95530)
- The error message is giving incorrect guidance. The `0.0-` gates noted in the `TestVersionsAreValid` failure message are [VPrimordial gates](https://github.com/cockroachdb/cockroach/blob/master/pkg/clusterversion/cockroach_versions.go#L544-L545), which [should never be removed](https://github.com/cockroachdb/cockroach/blob/master/pkg/clusterversion/cockroach_versions.go#L176-L178).
- The old rule assumed that versions more than 5 releases ago had to be removed. But this rule no longer applies, now that we've since [modified the schedule for when we advance minBinary](https://cockroachlabs.atlassian.net/wiki/spaces/RE/pages/3197665321/Schedule+for+advancing+BinaryMinSupportedVersionKey+a.k.a.+minBinary).

### More Context

This [check was triggered](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/12045194?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildDeploymentsSection=true&expandBuildTestsSection=true) while attempting to [add the version gate to mint V23_2](https://github.com/cockroachdb/cockroach/pull/111729/files#diff-8f32466c40e6960b988c87d7e2453c01a591d420af123f0963959da8e580f2e4).

Error message:

```
Failed
=== RUN   TestVersionsAreValid
    cockroach_versions_test.go:26:
          Error Trace:  github.com/cockroachdb/cockroach/pkg/clusterversion/pkg/clusterversion/cockroach_versions_test.go:26
          Error:        Received unexpected error:
                        found versions that are always active because 2.23 is already released; these should be removed:
                        (1) attached stack trace
                          -- stack trace:
                          | github.com/cockroachdb/cockroach/pkg/clusterversion.keyedVersions.Validate
                          |   github.com/cockroachdb/cockroach/pkg/clusterversion/pkg/clusterversion/keyed_versions.go:106
                          | github.com/cockroachdb/cockroach/pkg/clusterversion.TestVersionsAreValid
                          |   github.com/cockroachdb/cockroach/pkg/clusterversion/pkg/clusterversion/cockroach_versions_test.go:26
                          | testing.tRunner
                          |   GOROOT/src/testing/testing.go:1576
                          | runtime.goexit
                          |   src/runtime/asm_amd64.s:1598
                        Wraps: (2) found versions that are always active because 2.23 is already released; these should be removed:
                          | introduced in 22.1: 0.0-2
                          | introduced in 22.1: 0.0-4
                          | introduced in 22.1: 0.0-6
                          | introduced in 22.1: 0.0-8
                          | introduced in 22.1: 0.0-10
                          | introduced in 22.1: 0.0-12
                          | introduced in 22.1: 0.0-424242
                        Error types: (1) *withstack.withStack (2) *errutil.leafError
          Test:         TestVersionsAreValid
--- FAIL: TestVersionsAreValid (0.02s)
```

Jira issue: CRDB-32114

**Comment by RaduBerinde** [comment]
This check does not account for permanent upgrades, I agree it should just be removed.
