### ISSUE TITLE
upgrades: use `GetSystemDatabaseSchemaVersion` instead of querying `pg_attribute`

### ISSUE THREAD

**Issue by healthy-pod** [cockroachdb/cockroach#111894]
`addRootUser` queries `pg_attribute` to determine whether the `role_id` and `member_id` columns are present because it can't rely on version gates against active cluster version (https://github.com/cockroachdb/cockroach/issues/106764).

After #111404, we can get the actual schema version of the system database. We should depend on this version in checking whether the columns above are present or not.

Since some tests bootstrap with versions less than current master (or 23.2 in the future), we have to wait until minimum supported binary version aka minimum version at which tests can bootstrap is 23.2 before making this change.

Jira issue: CRDB-32120

**Comment by rafiss** [comment]
Since these columns are added during the v23.1 upgrade finalization, I think we can just safely remove these gates once the min binary version is bumped to 23.2.

**Comment by rafiss** [comment]
I'm going to close this, since we are soon going to remove code relating to the 22.2/23.1 mixed version state.
