### ISSUE TITLE
sql: activity update job reduce memory usage

### ISSUE THREAD

**Issue by j82w** [cockroachdb/cockroach#111866]
The activity update job query can cause very large arrays to be created with the `array_agg`. There are some statements that have over 9k+ rows which can consume a lot of memory.  This can be optimized with a new function which aggregates the data into a single instance and avoid the need for converting it to an array.

Jira issue: CRDB-32104

**Comment by yuzefovich** [comment]
Re-opened to block 23.1.12 to include #112323.

**Comment by yuzefovich** [comment]
Backport has been merged.
