### ISSUE TITLE
backupccl: add a schema change workload to mixed version backup roachtest

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#111890]
Currently, the mixed version backup roachtest runs tpcc and kv -- neither of these workloads run schema changes during the workload. We ought add more large scale test coverage around backup-restore X schema changes.

Jira issue: CRDB-32115

Epic CRDB-31689

**Comment by stevendanna** [comment]
@adityamaru says that we should check in with the the tooling that foundations has already built around this.
