### ISSUE TITLE
kvserver: use simulator to evaluate 23.2 allocation changes

### ISSUE THREAD

**Issue by shralex** [cockroachdb/cockroach#111838]
We should use the Simulator to evaluate any 23.2 changes, related to MR or other.

Jira issue: CRDB-32088

**Comment by kvoli** [comment]
I went through allocator related changes since `2023-03-01` on the `release-23.2` branch and flagged any that would be candidates for additional simulator testing:

- ed5175253df75879c39d3c8ec155364852167ea1
- 8478b85bae45bfdc8e206a8409fc173d58afe1f8
- 1fac2f88c6b47aca25f1542a95f2b789d750f505
- 9ed70271734d0871254626d7909cb48fcb348d78
- 3e3a9b1e535833db50797895f82a68362f3dd3ed
- a944e57b35248f993156f70b2db0a24d0fcbfe6a

**Comment by kvoli** [comment]
Mapping the commits to their respective pull requests and adding some additional information on the change, and level of testing (inc simulator) currently:

- #111609
	- https://github.com/cockroachdb/cockroach/issues/106192 extended the simulator testing for added coverage of constraint violation. The issue isn't complete, but the changes have been evaluated reasonably well with the existing simulator changes done here.
- #108197
    - PR changes desc/span config to be passed through the allocator, instead of called ad-hoc when needed. Added testing coverage could be modifying the descriptor underneath repeatedly and checking for spurious results. This is a low priority candidate.
- #107507
    - There is no lease preference testing in the simulator currently. This is a good candidate. The conformance assertions include constraints, under(over) replication and unavailable ranges. It would be reasonable to extend the conformance assertions to include lease preferences.
- #106202
    - TBD
- #105924
    - Made a threshold a cluster setting. This could be verified further via an explicit datadriven test which modifies the cluster setting, this is lower relative priority.
-  #98889
    - Good candidate for testing. A bad distribution after this change is a bimodal distribution with many ranges. Where there are equally hot ranges (n>1/threshold), and dormant ranges. In this case, the store rebalancer could never kick in to move load, where it previously would. The benefit of this change is greater stability.
