### ISSUE TITLE
sql: implement the logic to add a constraint to a join

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#11192]
For #10633 we need a primitive that can add a new comparison to an existing join operation.
(later we actually need to do this for any data source, but for #10633 joins are sufficient)

The primitive should be a new method `joinNode.addFilter` defined as follows:
```go
func (n *joinNode) addFilter(newFilter parser.ComparisonExpr) bool
```

The behavior should be defined as follows: 
- if `newFilter.Operator != Eq`, then return false
- if the left and right operands are not IndexedVar, then return false
- if the left and right operands are referring to the same side of the join, then return false
- otherwise, given the left and right operands `x` and `y` transform the join predicate as follows:

  - `crossPredicate` -> `ON EQUALS ((x), (y))`, return true
  - `onPredicate{filter:E}` -> `onPredicate{filter:AndExpr{Left:E, Right:newFilter}}`, return true
  - `ON EQUALS ((a, b, c...), (u, v, w...))` -> `ON EQUALS ((a, b, c, ..., x), (u, v, w..., y))`, then return true

In any case the method must not change the set of result columns (which columns are present in the result of the join)

**Comment by knz** [comment]
@a6802739 you have previously expressed interest in this area of the code and shown a lot of skill too! Is this an issue you'd like to work on?

**Comment by a6802739** [comment]
@knz, thanks, I can have a try for it.

**Comment by a6802739** [comment]
@knz,  I could not quite understand `given the left and right operands x and y transform the join predicate`.

Do you mean transform `crossPredicate` to `equalityPredicate` or just update the `Explain` function of `crossPredicate `?

And, How does `ON EQUALS ((a, b, c...), (u, v, w...)) -> ON EQUALS ((a, b, c, ..., x), (u, v, w..., y))` this happen? Could you please have a more concrete explanation for this? And also for this `onPredicate{filter:E} -> onPredicate{filter:AndExpr{Left:E, Right:newFilter}}`?

Sorry to bother you.

**Comment by knz** [comment]
1) yes the predicate object must be replaced entirely, for example replace `crossPredicate` to `equalityPredicate`.

2) for this substitution: `ON EQUALS ((a, b, c...), (u, v, w...)) -> ON EQUALS ((a, b, c, ..., x), (u, v, w..., y))` what happens is that the two additional columns received as argument must be added to the existing `equalityPredicate` object, i.e. one more item must be added to the `leftEqualityIndices`/`rightEqualityIndices` arrays. (also the column names)

3) the replacement of `ON` is so that if we add the predicate `x = y` to `ON a = 3 OR b = 4` the result is `ON (a = 3 OR b = 4) AND (x = y)`

Is this more clear?

**Comment by a6802739** [comment]
@knz, it's much clear now. Thanks for your guidance.

**Comment by a6802739** [comment]
@knz, where should I use this function now?
