### ISSUE TITLE
kv: next() and prev() should ignore NoopRequests

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#11195]
Extracted from https://github.com/cockroachdb/cockroach/issues/10427#issuecomment-262431117

`kv.next()` and `kv.prev()` attempt to find the next key in a batch to seek to. However, they don't skip NoopRequests (whose keys are empty) so it ends up iterating through all range descriptors in order. 

This is the second recent issue where NoopRequests and their dummy keys are processed as if they were real (#10470), so we should probably audit all the places where we iterate over the requests of a batch to ensure NoopRequests are being handled correctly.

**Comment by petermattis** [comment]
Yeah, that's not good. `NoopRequests` are unfortunate in that they require checks in lots of places. Can you remind me why we have them? I seem to recall something about error indexes.

**Comment by bdarnell** [comment]
NoopRequests are there so that the DistSender can match up responses to their original requests by zipping all the sub-responses back together (this matters both for error reporting and for recombining the responses to range ops like Scan). An alternative would be to attach an "OrigIndex" to each request in the batch and propagate that index in the response (both for regular responses and for errors). I don't know if it's worth making that change now or if we should just audit all loops over this field. We could also make NoopRequest.Header panic instead of being a dummy implementation, which would make it easier to catch these bugs.

**Comment by petermattis** [comment]
> I don't know if it's worth making that change now or if we should just audit all loops over this field. 

Probably safer to audit all of the existing loops, though I would have preferred the alternative approach (keeping track of the index for each request) if we were starting from scratch. Seems like the batch splitting and combining is all contained within `kv/dist_sender.go`, yet the `NoopRequest` approach spills out to other areas of code.

**Comment by bdarnell** [comment]
Turns out there's not a bug here, for a couple of reasons: First, `kv.next` and `kv.prev` do the right things with NoopRequests and their empty keys (although this is purely by accident). Second, I don't think they ever even see NoopRequests (These functions are a part of the DistSender's process for splitting batches, which is before any NoopRequests are introduced). 

I think the trace messages I saw in the above-linked comment (in which we appeared to be doing multiple descriptor lookups per RPC) was actually an artifact of the way we send rpcs in parallel when we can (which uses a separate context).

Anyway, I've added some more testing and assertions around the use of NoopRequests to make sure we don't accidentally treat a NoopRequest as an access to KeyMin any more.

**Comment by petermattis** [comment]
Btw, I think we should get rid of Noop{Request,Response} for performance reasons. Consider a batch with 10 PutRequests all to different ranges. With NoopRequest, this will translate into 10 new batch requests each with 10 requests, for a total of 100 requests in total. The encoding/decoding/allocation overhead is non-trivial.

**Comment by petermattis** [comment]
An even better example are the periodic timeseries merge operations. For example `[n8,ts-poll] sending RPC for batch: 1 Merge, 349 Noop`.
