### ISSUE TITLE
storage: show in logs when crdb_internal.compact_engine_span is called

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#111954]
This would be useful for debugging escalations. There are probably other built-ins it could apply to.

Informs https://github.com/cockroachlabs/support/issues/2640

Jira issue: CRDB-32152

Epic CRDB-40360

**Comment by RaduBerinde** [comment]
A more specific suggestion is to plumb this information to Pebble and annotate compaction-related Pebble logs with the reason for the compaction.

**Comment by mzone242** [comment]
Hello, @annabelto and I would like to take this issue. We are Masters students at The University of Texas at Austin and are looking to contribute to an open source project concerned with distributed systems for our coursework in the subject.

Can you also provide some more background information on this issue? We are unable to see the internal Jira ticket associated with this or the associated support issue.

**Comment by RaduBerinde** [comment]
Sorry, yes, you can take this issue. There is not much background to provide, we just want to log a message when a manual compaction is triggered. It can be done either in Pebble or in Cockroach.

**Comment by nicktrav** [comment]
Closed by #118719.
