### ISSUE TITLE
sql: v23.1.2: no Annotations provided panic when logging COPY

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#112058]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4536559325/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4536559325/?referrer=webhooks_plugin)

Panic Message:

```
format.go:349: no Annotations provided
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:890
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.NewFmtCtx
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/format.go:349
  | github.com/cockroachdb/cockroach/pkg/sql.formatStmtKeyAsRedactableString
  | 	github.com/cockroachdb/cockroach/pkg/sql/exec_util.go:3609
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).getCommonSQLEventDetails
  | 	github.com/cockroachdb/cockroach/pkg/sql/event_log.go:193
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).logEventsWithOptions
  | 	github.com/cockroachdb/cockroach/pkg/sql/event_log.go:224
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).logEventsOnlyExternally
  | 	github.com/cockroachdb/cockroach/pkg/sql/exec_log.go:501
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).maybeLogStatementInternal
  | 	github.com/cockroachdb/cockroach/pkg/sql/exec_log.go:381
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).maybeLogStatement
  | 	github.com/cockroachdb/cockroach/pkg/sql/exec_log.go:169
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCopyIn.func4
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2989
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCopyIn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:3150
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2355
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2096
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:892
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:767
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:890
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | [...repeated from below...]
Wraps: (3) assertion failure
Wraps: (4) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.NewFmtCtx
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/format.go:349
  | github.com/cockroachdb/cockroach/pkg/sql.formatStmtKeyAsRedactableString
  | 	github.com/cockroachdb/cockroach/pkg/sql/exec_util.go:3609
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).getCommonSQLEventDetails
  | 	github.com/cockroachdb/cockroach/pkg/sql/event_log.go:193
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).logEventsWithOptions
  | 	github.com/cockroachdb/cockroach/pkg/sql/event_log.go:224
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).logEventsOnlyExternally
  | 	github.com/cockroachdb/cockroach/pkg/sql/exec_log.go:501
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).maybeLogStatementInternal
  | 	github.com/cockroachdb/cockroach/pkg/sql/exec_log.go:381
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).maybeLogStatement
  | 	github.com/cockroachdb/cockroach/pkg/sql/exec_log.go:169
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCopyIn.func4
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2989
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCopyIn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:3150
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2355
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2096
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:892
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:767
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (5) no Annotations provided
Error types: (1) *withstack.withStack (2) *withstack.withStack (3) *assert.withAssertionFailure (4) *withstack.withStack (5) *errutil.leafError
-- report composition:
*errutil.leafError: no Annotations provided
format.go:349: *withstack.withStack (top exception)
*assert.withAssertionFailure
conn_executor.go:890: *withstack.withStack (1)
conn_executor.go:890: *withstack.withStack (2)
(check the extra data payloads)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/pgwire/conn.go#L766-L768](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/pgwire/conn.go#L766-L768)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/conn_executor.go#L891-L893](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/conn_executor.go#L891-L893)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/conn_executor.go#L2095-L2097](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/conn_executor.go#L2095-L2097)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/conn_executor.go#L2354-L2356](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/conn_executor.go#L2354-L2356)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/conn_executor.go#L3149-L3151](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/conn_executor.go#L3149-L3151)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/conn_executor.go#L2988-L2990](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/conn_executor.go#L2988-L2990)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/exec_log.go#L168-L170](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/exec_log.go#L168-L170)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/exec_log.go#L380-L382](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/exec_log.go#L380-L382)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/exec_log.go#L500-L502](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/exec_log.go#L500-L502)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/event_log.go#L223-L225](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/event_log.go#L223-L225)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/event_log.go#L192-L194](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/event_log.go#L192-L194)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/exec_util.go#L3608-L3610](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/exec_util.go#L3608-L3610)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/sem/tree/format.go#L348-L350](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/sem/tree/format.go#L348-L350)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/conn_executor.go#L889-L891](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/conn_executor.go#L889-L891)
[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/pgwire/conn.go#L766-L768](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/pgwire/conn.go#L766-L768)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/conn_executor.go#L891-L893](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/conn_executor.go#L891-L893)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/conn_executor.go#L2095-L2097](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/conn_executor.go#L2095-L2097)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/conn_executor.go#L2354-L2356](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/conn_executor.go#L2354-L2356)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/conn_executor.go#L3149-L3151](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/conn_executor.go#L3149-L3151)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/conn_executor.go#L2988-L2990](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/conn_executor.go#L2988-L2990)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/exec_log.go#L168-L170](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/exec_log.go#L168-L170)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/exec_log.go#L380-L382](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/exec_log.go#L380-L382)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/exec_log.go#L500-L502](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/exec_log.go#L500-L502)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/event_log.go#L223-L225](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/event_log.go#L223-L225)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/event_log.go#L192-L194](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/event_log.go#L192-L194)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/exec_util.go#L3608-L3610](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/exec_util.go#L3608-L3610)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/sem/tree/format.go#L348-L350](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/sem/tree/format.go#L348-L350)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/conn_executor.go#L889-L891](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/conn_executor.go#L889-L891)
[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/pgwire/conn.go#L766-L768](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/pgwire/conn.go#L766-L768)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/conn_executor.go#L891-L893](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/conn_executor.go#L891-L893)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/conn_executor.go#L2095-L2097](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/conn_executor.go#L2095-L2097)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/conn_executor.go#L2354-L2356](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/conn_executor.go#L2354-L2356)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/conn_executor.go#L3149-L3151](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/conn_executor.go#L3149-L3151)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/conn_executor.go#L2988-L2990](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/conn_executor.go#L2988-L2990)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/exec_log.go#L168-L170](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/exec_log.go#L168-L170)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/exec_log.go#L380-L382](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/exec_log.go#L380-L382)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/exec_log.go#L500-L502](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/exec_log.go#L500-L502)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/event_log.go#L223-L225](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/event_log.go#L223-L225)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/event_log.go#L192-L194](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/event_log.go#L192-L194)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/exec_util.go#L3608-L3610](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/exec_util.go#L3608-L3610)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/sem/tree/format.go#L348-L350](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/sem/tree/format.go#L348-L350)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommandsAsync.func1 at line 767
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 892
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 2096
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 2355
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCopyIn at line 3150
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCopyIn.func4 at line 2989
pkg/sql/exec_log.go in pkg/sql.(*planner).maybeLogStatement at line 169
pkg/sql/exec_log.go in pkg/sql.(*planner).maybeLogStatementInternal at line 381
pkg/sql/exec_log.go in pkg/sql.(*planner).logEventsOnlyExternally at line 501
pkg/sql/event_log.go in pkg/sql.(*planner).logEventsWithOptions at line 224
pkg/sql/event_log.go in pkg/sql.(*planner).getCommonSQLEventDetails at line 193
pkg/sql/exec_util.go in pkg/sql.formatStmtKeyAsRedactableString at line 3609
pkg/sql/sem/tree/format.go in pkg/sql/sem/tree.NewFmtCtx at line 349
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn.func1 at line 890
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommandsAsync.func1 at line 767
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 892
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 2096
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 2355
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCopyIn at line 3150
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCopyIn.func4 at line 2989
pkg/sql/exec_log.go in pkg/sql.(*planner).maybeLogStatement at line 169
pkg/sql/exec_log.go in pkg/sql.(*planner).maybeLogStatementInternal at line 381
pkg/sql/exec_log.go in pkg/sql.(*planner).logEventsOnlyExternally at line 501
pkg/sql/event_log.go in pkg/sql.(*planner).logEventsWithOptions at line 224
pkg/sql/event_log.go in pkg/sql.(*planner).getCommonSQLEventDetails at line 193
pkg/sql/exec_util.go in pkg/sql.formatStmtKeyAsRedactableString at line 3609
pkg/sql/sem/tree/format.go in pkg/sql/sem/tree.NewFmtCtx at line 349
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn.func1 at line 890
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommandsAsync.func1 at line 767
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 892
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 2096
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 2355
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCopyIn at line 3150
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCopyIn.func4 at line 2989
pkg/sql/exec_log.go in pkg/sql.(*planner).maybeLogStatement at line 169
pkg/sql/exec_log.go in pkg/sql.(*planner).maybeLogStatementInternal at line 381
pkg/sql/exec_log.go in pkg/sql.(*planner).logEventsOnlyExternally at line 501
pkg/sql/event_log.go in pkg/sql.(*planner).logEventsWithOptions at line 224
pkg/sql/event_log.go in pkg/sql.(*planner).getCommonSQLEventDetails at line 193
pkg/sql/exec_util.go in pkg/sql.formatStmtKeyAsRedactableString at line 3609
pkg/sql/sem/tree/format.go in pkg/sql/sem/tree.NewFmtCtx at line 349
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v23.1.2 |
| Go Version | go1.19.4 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.2 |
| Cockroach SHA | 810d4f27a7f02b9cc2750cab654ed1c62ac3e75a |
| # of CPUs | 4 |
| # of Goroutines | 435 |

Jira issue: CRDB-32215

**Comment by yuzefovich** [comment]
This one has been fixed in 23.1.3 via #103738.
