### ISSUE TITLE
 could not get total system memory:open /proc/meminfo: too many open files

### ISSUE THREAD

**Issue by chenqunjian** [cockroachdb/cockroach#112079]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

76.6/58.1 %(u/s)time, 0.1 %gc (12x), 119 MiB/12 MiB (r/w)net
I231010 01:21:13.767446 791 gossip/gossip.go:557  [n1] gossip status (ok, 3 nodes)
gossip client (1/3 cur/max conns)
  3: 172.17.0.116:6257 (25m11s: infos 4544/3653 sent/received, bytes 1212870B/1458669B sent/received)
gossip server (1/3 cur/max conns, infos 12352/16226 sent/received, bytes 4604017B/4992364B sent/received)
  2: 172.17.0.115:6257 (24m6s)
I231010 01:21:14.831101 728 storage/compactor/compactor.go:329  [n1,s1,compactor] purging suggested compaction for range /Table/140/1/"20231009"/2023101007/"100305860421"/"F"/"F_CNC1"/0 - /Table/146 that contains live data
I231010 01:21:20.384089 795 server/status/runtime.go:500  [n1] runtime stats: 22 GiB RSS, 981 goroutines, 650 MiB/567 MiB/1.5 GiB GO alloc/idle/total, 16 GiB/21 GiB CGO alloc/total, 158207.4 CGO/sec, 798.9/58.6 %(u/s)time, 0.1 %gc (14x), 102 MiB/19 MiB (r/w)net
I231010 01:21:30.403034 795 server/status/runtime.go:500  [n1] runtime stats: 22 GiB RSS, 996 goroutines, 537 MiB/674 MiB/1.5 GiB GO alloc/idle/total, 16 GiB/21 GiB CGO alloc/total, 87757.9 CGO/sec, 720.0/61.3 %(u/s)time, 0.1 %gc (13x), 160 MiB/20 MiB (r/w)net
I231010 01:21:40.424269 795 server/status/runtime.go:500  [n1] runtime stats: 22 GiB RSS, 985 goroutines, 555 MiB/662 MiB/1.5 GiB GO alloc/idle/total, 16 GiB/21 GiB CGO alloc/total, 75740.5 CGO/sec, 634.0/60.4 %(u/s)time, 0.1 %gc (10x), 104 MiB/12 MiB (r/w)net
E231010 01:21:49.738702 3475294 sql/conn_executor.go:545  [n1,client=192.168.13.221:36364,user=fanuc_edbf10f8737241ca] error setting up client session: invalid value for parameter "TimeZone": "Asia/Shanghai"
I231010 01:21:50.445495 795 server/status/runtime.go:500  [n1] runtime stats: 22 GiB RSS, 983 goroutines, 635 MiB/576 MiB/1.5 GiB GO alloc/idle/total, 16 GiB/21 GiB CGO alloc/total, 54501.7 CGO/sec, 746.8/55.9 %(u/s)time, 0.1 %gc (13x), 98 MiB/20 MiB (r/w)net
I231010 01:22:00.485562 795 server/status/runtime.go:500  [n1] runtime stats: 22 GiB RSS, 992 goroutines, 823 MiB/466 MiB/1.5 GiB GO alloc/idle/total, 17 GiB/21 GiB CGO alloc/total, 163907.2 CGO/sec, 665.7/60.4 %(u/s)time, 0.2 %gc (11x), 128 MiB/14 MiB (r/w)net
I231010 01:22:10.505100 795 server/status/runtime.go:500  [n1] runtime stats: 22 GiB RSS, 979 goroutines, 695 MiB/544 MiB/1.5 GiB GO alloc/idle/total, 16 GiB/21 GiB CGO alloc/total, 132882.2 CGO/sec, 648.8/57.5 %(u/s)time, 0.1 %gc (11x), 115 MiB/11 MiB (r/w)net
I231010 01:22:13.767446 791 gossip/gossip.go:557  [n1] gossip status (ok, 3 nodes)
gossip client (1/3 cur/max conns)
  3: 172.17.0.116:6257 (26m11s: infos 4713/3766 sent/received, bytes 1237859B/1479279B sent/received)
gossip server (1/3 cur/max conns, infos 12691/16451 sent/received, bytes 4654143B/5028274B sent/received)
  2: 172.17.0.115:6257 (25m6s)
I231010 01:22:20.525761 795 server/status/runtime.go:500  [n1] runtime stats: 22 GiB RSS, 975 goroutines, 747 MiB/482 MiB/1.5 GiB GO alloc/idle/total, 16 GiB/21 GiB CGO alloc/total, 111613.0 CGO/sec, 777.2/59.2 %(u/s)time, 0.1 %gc (13x), 122 MiB/19 MiB (r/w)net
E231010 01:22:24.456621 3492185 storage/replica_proposal.go:207  [n1,s1,r391674/3:/Table/1649/1/"20220820"/"100…] IO error: While open a file for random read: /var/lib/cockdb/DB/11933381.sst: Too many open files
E231010 01:22:26.261462 3493208 storage/replica_proposal.go:207  [n1,s1,r67770/3:/Table/606/1/"20210420"/"…] IO error: While open a file for random read: /var/lib/cockdb/DB/16979222.sst: Too many open files
E231010 01:22:26.457082 3492863 storage/replica_proposal.go:207  [n1,s1,r442169/3:/Table/1300/1/"100300110583"/…] IO error: While open a file for random read: /var/lib/cockdb/DB/16983062.sst: Too many open files
E231010 01:22:26.458016 3492941 storage/consistency_queue.go:137  [n1,consistencyChecker,s1,r442169/3:/Table/1300/1/"100300110583"/…] computing own checksum: rpc error: code = Unknown desc = no checksum found (ID = e21a48d7-16df-42b7-9639-609ae34202f2)
E231010 01:22:26.458035 3492941 storage/queue.go:829  [n1,consistencyChecker,s1,r442169/3:/Table/1300/1/"100300110583"/…] computing own checksum: rpc error: code = Unknown desc = no checksum found (ID = e21a48d7-16df-42b7-9639-609ae34202f2)
E231010 01:22:26.630108 797 server/status/recorder.go:436  [n1,summaries] could not get total system memory:open /proc/meminfo: too many open files
E231010 01:22:26.648559 797 server/status/recorder.go:477  [n1,summaries] Could not record status summaries: Store 1 could not return descriptor, error: open /var/lib/cockdb/DB: too many open files
E231010 01:22:30.526023 795 server/status/runtime.go:411  [n1] unable to get mem usage: open /proc/18769/statm: too many open files
E231010 01:22:30.526042 795 server/status/runtime.go:415  [n1] unable to get cpu usage: open /proc/18769/stat: too many open files
E231010 01:22:30.526064 795 server/status/runtime.go:426  [n1] unable to get file descriptor usage: open /proc/18769/limits: too many open files
W231010 01:22:30.526081 795 server/status/runtime.go:433  [n1] problem fetching disk stats: open /proc/diskstats: too many open files; disk stats will be empty.
W231010 01:22:30.526093 795 server/status/runtime.go:454  [n1] problem fetching net stats: open /proc/net/dev: too many open files; net stats will be empty.
I231010 01:22:30.526571 795 server/status/runtime.go:500  [n1] runtime stats: 0 B RSS, 979 goroutines, 777 MiB/460 MiB/1.5 GiB GO alloc/idle/total, 16 GiB/21 GiB CGO alloc/total, 24156.3 CGO/sec, -229320.1/-21236.3 %(u/s)time, 0.1 %gc (10x), 0 B/0 B (r/w)net
E231010 01:22:31.240193 3495716 sql/conn_executor.go:545  [n1,client=192.168.13.221:36412,user=fanuc_edbf10f8737241ca] error setting up client session: invalid value for parameter "TimeZone": "Asia/Shanghai"
E231010 01:22:31.826995 3495993 sql/conn_executor.go:545  [n1,client=192.168.13.223:44324,user=fanuc_edbf10f8737241ca] error setting up client session: invalid value for parameter "TimeZone": "Asia/Shanghai"
W231010 01:22:33.767519 790 server/node.go:799  [n1] [n1,s1]: unable to compute metrics: open /var/lib/cockdb/DB: too many open files
E231010 01:22:36.244334 3499194 storage/replica_proposal.go:207  [n1,s1,r401220/3:/Table/1302/1/"100305860426"/…] IO error: While open a file for random read: /var/lib/cockdb/DB/16982827.sst: Too many open files
E231010 01:22:36.629842 797 server/status/recorder.go:436  [n1,summaries] could not get total system memory:open /proc/meminfo: too many open files
E231010 01:22:36.643033 797 server/status/recorder.go:477  [n1,summaries] Could not record status summaries: Store 1 could not return descriptor, error: open /var/lib/cockdb/DB: too many open files
E231010 01:22:39.829893 3502509 storage/replica_proposal.go:207  [n1,s1,r190632/3:/Table/1302/1/"10030586020…] IO error: While open a file for random read: /var/lib/cockdb/DB/16982827.sst: Too many open files
E231010 01:22:40.526787 795 server/status/runtime.go:411  [n1] unable to get mem usage: open /proc/18769/statm: too many open files
E231010 01:22:40.526801 795 server/status/runtime.go:415  [n1] unable to get cpu usage: open /proc/18769/stat: too many open files
E231010 01:22:40.526815 795 server/status/runtime.go:426  [n1] unable to get file descriptor usage: open /proc/18769/limits: too many open files
W231010 01:22:40.526830 795 server/status/runtime.go:433  [n1] problem fetching disk stats: open /proc/diskstats: too many open files; disk stats will be empty.
W231010 01:22:40.526840 795 server/status/runtime.go:454  [n1] problem fetching net stats: open /proc/net/dev: too many open files; net stats will be empty.
I231010 01:22:40.527361 795 server/status/runtime.go:500  [n1] runtime stats: 0 B RSS, 973 goroutines, 782 MiB/460 MiB/1.5 GiB GO alloc/idle/total, 16 GiB/21 GiB CGO alloc/total, 45716.7 CGO/sec, 0.0/0.0 %(u/s)time, 0.1 %gc (10x), 0 B/0 B (r/w)net
E231010 01:22:41.349644 3503589 sql/conn_executor.go:545  [n1,client=192.168.13.223:44376,user=fanuc_edbf10f8737241ca] error setting up client session: invalid value for parameter "TimeZone": "Asia/Shanghai"
E231010 01:22:47.829352 3506850 storage/replica_proposal.go:207  [n1,s1,r34061/3:/Table/265/1/"{SH100…-T0001…}] IO error: While open a file for random read: /var/lib/cockdb/DB/16735275.sst: Too many open files
E231010 01:22:49.810135 3507245 sql/conn_executor.go:545  [n1,client=192.168.13.221:36436,user=fanuc_edbf10f8737241ca] error setting up client session: invalid value for parameter "TimeZone": "Asia/Shanghai"
E231010 01:22:50.021974 3502329 sql/distsqlrun/server.go:614  [n1] flow c20d479e-0b75-414c-920a-649cfba34ae4 not found
E231010 01:22:50.022005 3502328 sql/distsqlrun/server.go:614  [n1] flow c20d479e-0b75-414c-920a-649cfba34ae4 not found
I231010 01:22:50.550514 795 server/status/runtime.go:500  [n1] runtime stats: 22 GiB RSS, 968 goroutines, 983 MiB/283 MiB/1.5 GiB GO alloc/idle/total, 16 GiB/21 GiB CGO alloc/total, 134939.4 CGO/sec, 230696.2/21328.7 %(u/s)time, 0.1 %gc (11x), 311 MiB/38 MiB (r/w)net
I231010 01:23:00.571230 795 server/status/runtime.go:500  [n1] runtime stats: 22 GiB RSS, 983 goroutines, 878 MiB/375 MiB/1.5 GiB GO alloc/idle/total, 16 GiB/21 GiB CGO alloc/total, 161779.5 CGO/sec, 670.3/57.7 %(u/s)time, 0.1 %gc (11x), 141 MiB/12 MiB (r/w)net
I231010 01:23:10.593487 795 server/status/runtime.go:500  [n1] runtime stats: 22 GiB RSS, 964 goroutines, 781 MiB/514 MiB/1.5 GiB GO alloc/idle/total, 16 GiB/21 GiB CGO alloc/total, 227279.0 CGO/sec, 557.8/58.4 %(u/s)time, 0.1 %gc (8x), 62 MiB/14 MiB (r/w)net
I231010 01:23:13.767559 791 gossip/gossip.go:557  [n1] gossip status (ok, 3 nodes)
gossip client (1/3 cur/max conns)
  3: 172.17.0.116:6257 (27m11s: infos 4880/3871 sent/received, bytes 1262748B/1498918B sent/received)
gossip server (1/3 cur/max conns, infos 13021/16665 sent/received, bytes 4703391B/5062962B sent/received)
  2: 172.17.0.115:6257 (26m6s)
W231010 01:23:13.767680 791 server/node.go:768  [n1] problem getting store descriptor for store cluster_id:f7afd5ce-8dea-4764-ac64-caf6a7a17548 node_id:1 store_id:1 : open /var/lib/cockdb/DB: too many open files
I231010 01:23:20.612581 795 server/status/runtime.go:500  [n1] runtime stats: 22 GiB RSS, 966 goroutines, 686 MiB/582 MiB/1.5 GiB GO alloc/idle/total, 16 GiB/21 GiB CGO alloc/total, 133368.6 CGO/sec, 834.2/56.9 %(u/s)time, 0.2 %gc (14x), 148 MiB/21 MiB (r/w)net
I231010 01:23:23.839395 3530690 sql/lease.go:1790  refreshing table: 526 lease failed: lease-insert: IO error: While open a file for random read: /var/lib/cockdb/DB/16984012.sst: Too many open files
E231010 01:23:26.630322 797 server/status/recorder.go:436  [n1,summaries] could not get total system memory:open /proc/meminfo: too many open files
E231010 01:23:26.674129 797 server/status/recorder.go:477  [n1,summaries] Could not record status summaries: Store 1 could not return descriptor, error: open /var/lib/cockdb/DB: too many open files
E231010 01:23:30.612892 795 server/status/runtime.go:411  [n1] unable to get mem usage: open /proc/18769/statm: too many open files
E231010 01:23:30.612903 795 server/status/runtime.go:415  [n1] unable to get cpu usage: open /proc/18769/stat: too many open files
E231010 01:23:30.612915 795 server/status/runtime.go:426  [n1] unable to get file descriptor usage: open /proc/18769/limits: too many open files
W231010 01:23:30.612927 795 server/status/runtime.go:433  [n1] problem fetching disk stats: open /proc/diskstats: too many open files; disk stats will be empty.
W231010 01:23:30.612935 795 server/status/runtime.go:454  [n1] problem fetching net stats: open /proc/net/dev: too many open files; net stats will be empty.
I231010 01:23:30.613353 795 server/status/runtime.go:500  [n1] runtime stats: 0 B RSS, 963 goroutines, 867 MiB/498 MiB/1.5 GiB GO alloc/idle/total, 17 GiB/21 GiB CGO alloc/total, 48758.1 CGO/sec, -233276.4/-21549.5 %(u/s)time, 0.1 %gc (6x), 0 B/0 B (r/w)net
W231010 01:23:33.767531 790 server/node.go:799  [n1] [n1,s1]: unable to compute metrics: open /var/lib/cockdb/DB: too many open files
E231010 01:23:34.655874 3535874 storage/replica_proposal.go:207  [n1,s1,r428035/3:/Table/1300/1/"100305860096"/…] IO error: While open a file for random read: /var/lib/cockdb/DB/16982895.sst: Too many open files
E231010 01:23:34.656144 3535914 storage/consistency_queue.go:137  [n1,consistencyChecker,s1,r428035/3:/Table/1300/1/"100305860096"/…] computing own checksum: rpc error: code = Unknown desc = no checksum found (ID = 8200e928-bbe9-44f1-9249-d3e01468319e)
E231010 01:23:34.656159 3535914 storage/queue.go:829  [n1,consistencyChecker,s1,r428035/3:/Table/1300/1/"100305860096"/…] computing own checksum: rpc error: code = Unknown desc = no checksum found (ID = 8200e928-bbe9-44f1-9249-d3e01468319e)
E231010 01:23:36.630018 797 server/status/recorder.go:436  [n1,summaries] could not get total system memory:open /proc/meminfo: too many open files
E231010 01:23:36.639262 797 server/status/recorder.go:477  [n1,summaries] Could not record status summaries: Store 1 could not return descriptor, error: open /var/lib/cockdb/DB: too many open files
E231010 01:23:40.613478 795 server/status/runtime.go:411  [n1] unable to get mem usage: open /proc/18769/statm: too many open files
E231010 01:23:40.613489 795 server/status/runtime.go:415  [n1] unable to get cpu usage: open /proc/18769/stat: too many open files
E231010 01:23:40.613501 795 server/status/runtime.go:426  [n1] unable to get file descriptor usage: open /proc/18769/limits: too many open files
W231010 01:23:40.613512 795 server/status/runtime.go:433  [n1] problem fetching disk stats: open /proc/diskstats: too many open files; disk stats will be empty.
W231010 01:23:40.613521 795 server/status/runtime.go:454  [n1] problem fetching net stats: open /proc/net/dev: too many open files; net stats will be empty.
I231010 01:23:40.613958 795 server/status/runtime.go:500  [n1] runtime stats: 0 B RSS, 975 goroutines, 858 MiB/470 MiB/1.5 GiB GO alloc/idle/total, 17 GiB/21 GiB CGO alloc/total, 6564.1 CGO/sec, 0.0/0.0 %(u/s)time, 0.1 %gc (12x), 0 B/0 B (r/w)net
E231010 01:23:42.420184 3540505 storage/replica_proposal.go:207  [n1,s1,r228663/3:/Table/1302/1/"1003001100…] IO error: While open a file for random read: /var/lib/cockdb/DB/16978985.sst: Too many open files
I231010 01:23:42.454141 563 storage/store.go:2507  [n1,s1,r651940/3:/Table/1649/1/"202310{10…-09…}] removing replica r651899/3
W231010 01:23:43.767785 790 server/node.go:799  [n1] [n1,s1]: unable to compute metrics: open /var/lib/cockdb/DB: too many open files
I231010 01:23:44.838898 728 storage/compactor/compactor.go:329  [n1,s1,compactor] purging suggested compaction for range /Table/1649/1/"20231009"/"100300110092"/1916-03-25T14:00:58.999999999Z/"PROG" - /Table/1649/1/"20231009"/"100300110195"/1916-03-25T13:25:31.999999999Z/"PROG"/0 that contains live data
E231010 01:23:46.629834 797 server/status/recorder.go:436  [n1,summaries] could not get total system memory:open /proc/meminfo: too many open files
E231010 01:23:46.638717 797 server/status/recorder.go:477  [n1,summaries] Could not record status summaries: Store 1 could not return descriptor, error: open /var/lib/cockdb/DB: too many open files
E231010 01:23:48.724016 3546709 sql/conn_executor.go:545  [n1,client=192.168.13.221:36458,user=fanuc_edbf10f8737241ca] error setting up client session: invalid value for parameter "TimeZone": "Asia/Shanghai"
E231010 01:23:48.756249 3546429 sql/conn_executor.go:545  [n1,client=192.168.13.223:44630,user=fanuc_edbf10f8737241ca] error setting up client session: invalid value for parameter "TimeZone": "Asia/Shanghai"
E231010 01:23:50.021995 3538272 sql/distsqlrun/server.go:614  [n1] flow c0faf8a9-90a6-4cab-b534-ae8ff5f74897 not found
E231010 01:23:50.022089 3538271 sql/distsqlrun/server.go:614  [n1] flow c0faf8a9-90a6-4cab-b534-ae8ff5f74897 not found
I231010 01:23:50.635266 795 server/status/runtime.go:500  [n1] runtime stats: 22 GiB RSS, 962 goroutines, 1.0 GiB/261 MiB/1.5 GiB GO alloc/idle/total, 17 GiB/21 GiB CGO alloc/total, 45537.1 CGO/sec, 234794.9/21751.4 %(u/s)time, 0.1 %gc (14x), 314 MiB/44 MiB (r/w)net
E231010 01:23:54.194360 17 storage/engine/rocksdb.go:129  [rocksdb] [/go/src/github.com/cockroachdb/cockroach/c-deps/rocksdb/db/db_impl_compaction_flush.cc:1610] Waiting after background flush error: IO error: While open a file for appending: /var/lib/cockdb/DB/16984037.sst: Too many open filesAccumulated background error counts: 1
E231010 01:23:54.195438 543 util/log/crash_reporting.go:546  [n1,s1,r651863/1:/Table/1{1/1/370/…-2}] Reported as error 37eeda050cee44709d8693cb70841052
F231010 01:23:54.195442 543 storage/store.go:3695  [n1,s1,r651863/1:/Table/1{1/1/370/…-2}] while committing batch: while committing batch: IO error: While open a file for appending: /var/lib/cockdb/DB/16984037.sst: Too many open files
goroutine 543 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0xc000528300, 0xc0005283c0, 0x53db200, 0x10)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:1020 +0xd4
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x5b65b00, 0xc000000004, 0x53db2ad, 0x10, 0xe6f, 0xc022625a40, 0xb9)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:876 +0x95a
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x3a49c80, 0xc0176e4060, 0x4, 0x2, 0x32c4cc2, 0x6, 0xc031285eb0, 0x2, 0x2)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:85 +0x2d8
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x3a49c80, 0xc0176e4060, 0x1, 0x4, 0x32c4cc2, 0x6, 0xc031285eb0, 0x2, 0x2)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:71 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(0x3a49c80, 0xc0176e4060, 0x32c4cc2, 0x6, 0xc031285eb0, 0x2, 0x2)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:182 +0x7e
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processReady(0xc0010f4000, 0x3a49c80, 0xc0176e4060, 0x9f257)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3695 +0x4f4
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc00172c080, 0x3a49c80, 0xc006ad2c90)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:214 +0x258
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x3a49c80, 0xc006ad2c90)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:165 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc00b3501f0, 0xc000b32000, 0xc00b3501e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:200 +0xe1
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:193 +0xa8

****************************************************************************

This node experienced a fatal error (printed above), and as a result the
process is terminating.

Fatal errors can occur due to faulty hardware (disks, memory, clocks) or a
problem in CockroachDB. With your help, the support team at Cockroach Labs
will try to determine the root cause, recommend next steps, and we can
improve CockroachDB based on your report.

Please submit a crash report by following the instructions here:

    https://github.com/cockroachdb/cockroach/issues/new/choose

If you would rather not post publicly, please contact us directly at:

    support@cockroachlabs.com

The Cockroach Labs team appreciates your feedback.

**Expected behavior**

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version [v19.1.3]
 - Server OS: [e.g. Linux/Distrib]
 - Client app [e.g. `cockroach sql`, JDBC, ...]

**Additional context**
What was the impact?

Jira issue: CRDB-32226

**Comment by chenqunjian** [comment]
![image](https://github.com/cockroachdb/cockroach/assets/19268457/2faa05ca-0d2c-4cbc-9daa-8456781a0cb0)
I have configured enough, but I still have the above problem。

**Comment by erikgrinaker** [comment]
Hi @chenqunjian. You can try setting the limit to unlimited. But this also depends on how you're deploying and running CockroachDB (e.g. launching manually, via systemd, etc) -- you will need to set the limit in such a way that it is properly applied to the CockroachDB process. There is more information on doing this in our [documentation](https://www.cockroachlabs.com/docs/stable/recommended-production-settings#file-descriptors-limit).

We're unfortunately unable to provide user support via GitHub. If you have further questions or problems, you can try asking in our [community Slack](https://cockroachdb.slack.com/) or [forum](https://forum.cockroachlabs.com/?_gl=1*13vio93*_ga*MTgwOTgyMTk0LjE2MzE3OTExMTI.*_ga_WPTKE58Z5D*MTY5NjkyNjg1MC4xOTQuMS4xNjk2OTI3MzI0LjAuMC4w), or consider purchasing a support agreement.
