### ISSUE TITLE
kvflowcontrol: do not apply limits when CPU usage cannot be accessed

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#112044]
**Describe the problem**

I have a local roachprod cluster that is stuck while creating tenants / ranges with the following log spam:\
```
I231009 15:16:44.568931 1155 kv/kvserver/kvflowcontrol/kvflowcontroller/kvflowcontroller_metrics.go:277 ⋮ [-] 9215  stream t1/s1 was blocked: durations: tokens deducted: regular 0 B elastic 0 B
I231009 15:16:44.568960 1155 kv/kvserver/kvflowcontrol/kvflowcontroller/kvflowcontroller_metrics.go:277 ⋮ [-] 9216  stream t1/s2 was blocked: durations: tokens deducted: regular 0 B elastic 0 B
I231009 15:16:44.568975 1155 kv/kvserver/kvflowcontrol/kvflowcontroller/kvflowcontroller_metrics.go:277 ⋮ [-] 9217  stream t1/s3 was blocked: durations: tokens deducted: regular 0 B elastic 0 B
```

for what it's worth, on this machine it's not possible to read CPU usage
```
E231009 15:16:30.905522 742 1@server/status/runtime.go:501 ⋮ [T1,Vsystem,n1] 9213  unable to get CPU capacity: failed to read cpu,cpuacct cgroup from cgroups file: ‹/proc/self/cgroup›: open ‹/proc/self/cgroup›: no such file or directory
```

I am ready to accept  that the flow control cannot work properly when CPU usage cannot be read, but it should degrade gracefully (i.e. with no limit) instead of making everything crawl to a halt.

**Expected behavior**

No flow control applied on this system

Jira issue: CRDB-32209

**Comment by erikgrinaker** [comment]
@aadityasondhi @sumeerbhola Do you want to have an initial look at this?

**Comment by knz** [comment]
Internal thread https://cockroachlabs.slack.com/archives/CAC6K3SLU/p1696864728460709

So apparently failure to sample the CPU usage should have no effect. So it's unclear where the cause is.

**Comment by knz** [comment]
i'll close this until i have a repro.
