### ISSUE TITLE
changefeedccl: v22.2.10: expected to find column -1 in NewEventDescriptor

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#112081]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4537280362/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4537280362/?referrer=webhooks_plugin)

Panic Message:

```
event.go:243: expected to find column -1
(1)
Wraps: (2)
Wraps: (3) assertion failure
Wraps: (4) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/cdcevent.NewEventDescriptor
  | 	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/cdcevent/event.go:243
  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/cdceval.newEventDescriptorForTarget
  | 	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/cdceval/validation.go:202
  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/cdceval.NormalizeAndValidateSelectForTarget
  | 	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/cdceval/validation.go:103
  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.validateAndNormalizeChangefeedExpression
  | 	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_stmt.go:914
  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.createChangefeedJobRecord
  | 	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_stmt.go:427
  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.changefeedPlanHook.func1
  | 	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_stmt.go:187
  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.changefeedPlanHook.func2
  | 	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_stmt.go:314
  | github.com/cockroachdb/cockroach/pkg/sql.(*hookFnNode).startExec.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/planhook.go:199
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (5) expected to find column -1
Error types: (1) *colexecerror.notInternalError (2) *changefeedbase.taggedError (3) *assert.withAssertionFailure (4) *withstack.withStack (5) *errutil.leafError
-- report composition:
*errutil.leafError: expected to find column -1
event.go:243: *withstack.withStack (top exception)
*assert.withAssertionFailure
*changefeedbase.taggedError
*colexecerror.notInternalError
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/62a0f7dd692b164236a0a540c9f4ed70b3db817b/pkg/sql/planhook.go#L198-L200](https://github.com/cockroachdb/cockroach/blob/62a0f7dd692b164236a0a540c9f4ed70b3db817b/pkg/sql/planhook.go#L198-L200)
[https://github.com/cockroachdb/cockroach/blob/62a0f7dd692b164236a0a540c9f4ed70b3db817b/pkg/ccl/changefeedccl/changefeed_stmt.go#L313-L315](https://github.com/cockroachdb/cockroach/blob/62a0f7dd692b164236a0a540c9f4ed70b3db817b/pkg/ccl/changefeedccl/changefeed_stmt.go#L313-L315)
[https://github.com/cockroachdb/cockroach/blob/62a0f7dd692b164236a0a540c9f4ed70b3db817b/pkg/ccl/changefeedccl/changefeed_stmt.go#L186-L188](https://github.com/cockroachdb/cockroach/blob/62a0f7dd692b164236a0a540c9f4ed70b3db817b/pkg/ccl/changefeedccl/changefeed_stmt.go#L186-L188)
[https://github.com/cockroachdb/cockroach/blob/62a0f7dd692b164236a0a540c9f4ed70b3db817b/pkg/ccl/changefeedccl/changefeed_stmt.go#L426-L428](https://github.com/cockroachdb/cockroach/blob/62a0f7dd692b164236a0a540c9f4ed70b3db817b/pkg/ccl/changefeedccl/changefeed_stmt.go#L426-L428)
[https://github.com/cockroachdb/cockroach/blob/62a0f7dd692b164236a0a540c9f4ed70b3db817b/pkg/ccl/changefeedccl/changefeed_stmt.go#L913-L915](https://github.com/cockroachdb/cockroach/blob/62a0f7dd692b164236a0a540c9f4ed70b3db817b/pkg/ccl/changefeedccl/changefeed_stmt.go#L913-L915)
[https://github.com/cockroachdb/cockroach/blob/62a0f7dd692b164236a0a540c9f4ed70b3db817b/pkg/ccl/changefeedccl/cdceval/validation.go#L102-L104](https://github.com/cockroachdb/cockroach/blob/62a0f7dd692b164236a0a540c9f4ed70b3db817b/pkg/ccl/changefeedccl/cdceval/validation.go#L102-L104)
[https://github.com/cockroachdb/cockroach/blob/62a0f7dd692b164236a0a540c9f4ed70b3db817b/pkg/ccl/changefeedccl/cdceval/validation.go#L201-L203](https://github.com/cockroachdb/cockroach/blob/62a0f7dd692b164236a0a540c9f4ed70b3db817b/pkg/ccl/changefeedccl/cdceval/validation.go#L201-L203)
[https://github.com/cockroachdb/cockroach/blob/62a0f7dd692b164236a0a540c9f4ed70b3db817b/pkg/ccl/changefeedccl/cdcevent/event.go#L242-L244](https://github.com/cockroachdb/cockroach/blob/62a0f7dd692b164236a0a540c9f4ed70b3db817b/pkg/ccl/changefeedccl/cdcevent/event.go#L242-L244)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/sql/planhook.go in pkg/sql.(*hookFnNode).startExec.func1 at line 199
pkg/ccl/changefeedccl/changefeed_stmt.go in pkg/ccl/changefeedccl.changefeedPlanHook.func2 at line 314
pkg/ccl/changefeedccl/changefeed_stmt.go in pkg/ccl/changefeedccl.changefeedPlanHook.func1 at line 187
pkg/ccl/changefeedccl/changefeed_stmt.go in pkg/ccl/changefeedccl.createChangefeedJobRecord at line 427
pkg/ccl/changefeedccl/changefeed_stmt.go in pkg/ccl/changefeedccl.validateAndNormalizeChangefeedExpression at line 914
pkg/ccl/changefeedccl/cdceval/validation.go in pkg/ccl/changefeedccl/cdceval.NormalizeAndValidateSelectForTarget at line 103
pkg/ccl/changefeedccl/cdceval/validation.go in pkg/ccl/changefeedccl/cdceval.newEventDescriptorForTarget at line 202
pkg/ccl/changefeedccl/cdcevent/event.go in pkg/ccl/changefeedccl/cdcevent.NewEventDescriptor at line 243
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v22.2.10 |
| Go Version | go1.19.6 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v22.2.10 |
| Cockroach SHA | 62a0f7dd692b164236a0a540c9f4ed70b3db817b |
| # of CPUs | 16 |
| # of Goroutines | 13932 |

Jira issue: CRDB-32227

**Comment by miretskiy** [comment]
Would be helpful to annotate this error with the statement that was used to produce it.

**Comment by miretskiy** [comment]
I don't think it's a crash actually -- it's the telemetry that treats assertion fail errors as an error.  At least that's what I think is happening.
