### ISSUE TITLE
Sentry: db.go:747: log.Fatal: read-only file system
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/pebble.(*DB).Apply
  | 	github.com/cockroachdb/pebble/external/com_github_cock...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#112045]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4536112026/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4536112026/?referrer=webhooks_plugin)

Panic Message:

```
db.go:747: log.Fatal: read-only file system
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/pebble.(*DB).Apply
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go:747
  | github.com/cockroachdb/pebble.(*Batch).Commit
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/batch.go:1049
  | github.com/cockroachdb/cockroach/pkg/storage.(*pebbleBatch).Commit
  | 	github.com/cockroachdb/cockroach/pkg/storage/pebble_batch.go:546
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:987
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReady
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:668
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processReady
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:641
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).worker
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:308
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:489
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (2) secondary error attachment
  | read-only file system
  | (1) read-only file system
  | Error types: (1) syscall.Errno
Wraps: (3) log.Fatal: read-only file system
Error types: (1) *withstack.withStack (2) *secondary.withSecondaryError (3) *errutil.leafError
-- report composition:
*errutil.leafError: log.Fatal: read-only file system
*secondary.withSecondaryError
db.go:747: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/util/stop/stopper.go#L488-L490](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/util/stop/stopper.go#L488-L490)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L307-L309](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L307-L309)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L640-L642](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L640-L642)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L667-L669](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L667-L669)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L986-L988](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L986-L988)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/storage/pebble_batch.go#L545-L547](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/storage/pebble_batch.go#L545-L547)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/batch.go#L1048-L1050](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/batch.go#L1048-L1050)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L746-L748](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L746-L748)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 489
pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go in pkg/kv/kvserver.(*raftScheduler).worker at line 308
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).processReady at line 641
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).handleRaftReady at line 668
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked at line 987
pkg/storage/pebble_batch.go in pkg/storage.(*pebbleBatch).Commit at line 546
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/batch.go in github.com/cockroachdb/pebble.(*Batch).Commit at line 1049
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go in github.com/cockroachdb/pebble.(*DB).Apply at line 747
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v22.2.14 |
| Go Version | go1.19.6 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v22.2.14 |
| Cockroach SHA | af6752b2faf39115fd322e9db76421e71b76507d |
| # of CPUs | 64 |
| # of Goroutines | 641 |

Jira issue: CRDB-32210

**Comment by yuzefovich** [comment]
dup of #86703
