### ISSUE TITLE
IMPORT failed on tables with columns of []UDT type

### ISSUE THREAD

**Issue by Xiang-Gu** [cockroachdb/cockroach#112100]
slack thread https://cockroachlabs.slack.com/archives/C04U1BTF8/p1696452709535389 seems to discover a bug in the IMPORT code when the table contains a column is of type ARRAY of user-defined-type. The error message is something like 
```
error parsing row 2: parse "completedTutorialTasks" as gather.public."TutorialTask"[]: type "gather.public.\"TutorialTask\"" does not exist (row: 4e5b42b2-4cc6-4442-95e2-65dbbf123405,foo,"ARRAY['RwPlaygroundMove':::gather.public."TutorialTask",'RwPlaygroundExploreLobby':::gather.public."TutorialTask"]"
```

I was able to reproduce this and I feel like we can reproduce it with a smaller example as long as there are
- a user-defined type `typ`
- a table with a column of type []typ (i.e. an array of some user defined type)
- export to a cloud storage (s3 or gs) and then import from it

Jira issue: CRDB-32235

**Comment by evangeline** [comment]
While trying to work around this problem, we noticed another potential bug. To repro:

- Set up the database as described above
- Instead of importing a table with column Type[], import a table with column String[] instead.
- The import job will complete successfully, but the rows will be broken with the error:

```
[XX000] ERROR: internal error: unexpected error from the vectorized engine: could not find [69 110 103 105 110 101 101 114 105 110 103] in enum "gather.public.\"TutorialTask\"" representation PhysicalReps: [[16] [32] [64] [96] [128] [144] [160] [192] [224]]; LogicalReps: [RwPlaygroundExploreLobby RwPlaygroundMove ...] goroutine 96319 [running]: runtime/debug.Stack() GOROOT/src/runtime/debug/stack.go:24 +0x65 github.com/cockroachdb/cockroach/pkg/sql/types.(*T).EnumGetIdxOfPhysical(0xc009634e40, {0xc006057052, 0xb, 0xfae}) github.com/cockroachdb/cockroach/pkg/sql/types/pkg/sql/types/types.go:2582 +0x ...
```

I would've expected the import job to fail in this case.

**Comment by DrewKimball** [comment]
Possibly related sentry issue: https://github.com/cockroachdb/cockroach/issues/111799
