### ISSUE TITLE
testcluster: startup takes time waiting for replication to complete

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#11212]
The TestCluster takes around 150ms on my machine waiting for replication to complete. occasionally, I'm seeing it wait for 2 seconds.

**Comment by bdarnell** [comment]
In #11647 you said that (unmerged) PR was the cause. So can this issue be closed now?

**Comment by vivekmenezes** [comment]
So while I haven't seen this on master, here's the deal with this issue

on seeing a trace of the ChangeReplicas transaction

`
I161202 12:17:57.528793 40 storage/replica_command.go:3347  ChangeReplicas trace:
     0.058ms      0.000ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/replica_command.go 3271: attempting txn
     0.089ms      0.031ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/range_iter.go 146: querying next range at /Table/14
     0.096ms      0.039ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/range_iter.go 155: meta descriptor lookup
     0.108ms      0.050ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/range_cache.go 298: looked up range descriptor from cache
     0.173ms      0.115ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/dist_sender.go 1066: sending RPC for batch: 1 Get
     0.509ms      0.452ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/dist_sender.go 1091: RPC reply: (err: key range /Table/14-/Table/14/NULL outside of bounds of range /Table/13-/Table/14)
     0.518ms      0.460ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/dist_sender.go 1093: application error: key range /Table/14-/Table/14/NULL outside of bounds of range /Table/13-/Table/14
     0.536ms      0.479ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/dist_sender.go 863: reply error [txn: e606aed5], Get [/Local/Range/"\x96"/RangeDescriptor,/Min): key range /Table/14-/Table/14/NULL outside of bounds of range /Table/13-/Table/14
     0.556ms      0.499ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/range_cache.go 237: evicting cached range descriptor with 2 replacements
     0.572ms      0.514ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/dist_sender.go 911: likely split; resending batch to span: key range /Table/14-/Table/14/NULL outside of bounds of range /Table/13-/Table/14
     0.579ms      0.522ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/range_iter.go 146: querying next range at /Table/14
     0.585ms      0.527ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/range_iter.go 155: meta descriptor lookup
     0.594ms      0.537ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/range_cache.go 298: looked up range descriptor from cache
     0.609ms      0.551ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/dist_sender.go 1066: sending RPC for batch: 1 Get
     0.686ms      0.628ms        event:node.Batch
     0.695ms      0.638ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] server/node.go 815: 1 Get
     0.702ms      0.644ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/stores.go 181: read has no clock uncertainty
     0.711ms      0.654ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/store.go 2391: executing 1 requests
     0.721ms      0.664ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/replica.go 1217: read-only path
     0.729ms      0.671ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/replica.go 1668: command queue
     0.737ms      0.679ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/replica.go 1676: waiting for read lock
     0.777ms      0.720ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/replica.go 1717: read completed
     0.869ms      0.811ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/dist_sender.go 1091: RPC reply: (err: <nil>), *roachpb.GetResponse
     1.022ms      0.964ms    event:util/log/log.go 88: storage/replica_command.go:3282 [n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] change replicas: read existing descriptor range_id:5 start_key:"\226" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
     1.099ms      1.041ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/range_iter.go 146: querying next range at /Table/14
     1.106ms      1.048ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/range_iter.go 155: meta descriptor lookup
     1.115ms      1.058ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/range_cache.go 298: looked up range descriptor from cache
     1.130ms      1.073ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/dist_sender.go 1066: sending RPC for batch: 1 CPut, 1 BeginTxn
     1.216ms      1.158ms        event:node.Batch
     1.226ms      1.168ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] server/node.go 815: 1 CPut, 1 BeginTxn
     1.233ms      1.175ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/stores.go 181: read has no clock uncertainty
     1.243ms      1.185ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/store.go 2391: executing 2 requests
     1.252ms      1.195ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/replica.go 1214: read-write path
     1.260ms      1.202ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/replica.go 1832: command queue
     1.279ms      1.221ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/replica.go 1900: raft
     1.406ms      1.349ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/replica.go 3161: processing command 4e89980196704aa0: maxLeaseIndex=1
     1.417ms      1.359ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/replica.go 3244: applying command
     1.651ms      1.593ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/dist_sender.go 1091: RPC reply: (err: <nil>), *roachpb.BeginTransactionResponse, *roachpb.ConditionalPutResponse
     1.675ms      1.618ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/txn_coord_sender.go 905: coordinator spawns
     1.814ms      1.756ms    event:util/log/log.go 88: storage/replica_command.go:3297 [n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] range modified first 775.041µs
     2.014ms      1.956ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/range_iter.go 146: querying next range at /Table/2/1/0/"system"/3/1
     2.020ms      1.963ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/range_iter.go 155: meta descriptor lookup
     2.042ms      1.985ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80,range-lookup] kv/dist_sender.go 1066: sending RPC for batch: 1 RngLookup
     2.225ms      2.167ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80,range-lookup] kv/dist_sender.go 1091: RPC reply: (err: <nil>), *roachpb.RangeLookupResponse
     2.238ms      2.180ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/range_cache.go 383: looked up range descriptor
     2.249ms      2.192ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80,range-lookup] kv/dist_sender.go 1066: sending RPC for batch: 1 RngLookup
     2.714ms      2.656ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80,range-lookup] kv/dist_sender.go 1091: RPC reply: (err: <nil>), *roachpb.RangeLookupResponse
     2.771ms      2.714ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/range_cache.go 383: looked up range descriptor
     2.792ms      2.734ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/dist_sender.go 1066: sending RPC for batch: 1 Get
     2.861ms      2.803ms        event:node.Batch
     2.873ms      2.815ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] server/node.go 815: 1 Get
     2.880ms      2.822ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/stores.go 181: read has no clock uncertainty
     2.891ms      2.833ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/store.go 2391: executing 1 requests
     2.902ms      2.844ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/replica.go 1217: read-only path
     2.910ms      2.852ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/replica.go 1668: command queue
     2.919ms      2.861ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/replica.go 1676: waiting for read lock
     2.955ms      2.897ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/replica.go 1717: read completed
     3.048ms      2.990ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/dist_sender.go 1091: RPC reply: (err: <nil>), *roachpb.GetResponse
     3.194ms      3.137ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/range_iter.go 146: querying next range at /Table/3/1/1/2/1
     3.201ms      3.143ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/range_iter.go 155: meta descriptor lookup
     3.222ms      3.164ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/range_cache.go 298: looked up range descriptor from cache
     3.235ms      3.177ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/dist_sender.go 1066: sending RPC for batch: 1 Get
     3.315ms      3.258ms        event:node.Batch
     3.325ms      3.267ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] server/node.go 815: 1 Get
     3.341ms      3.284ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/stores.go 181: read has no clock uncertainty
     3.352ms      3.294ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/store.go 2391: executing 1 requests
     3.363ms      3.305ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/replica.go 1217: read-only path
     3.371ms      3.313ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/replica.go 1668: command queue
     3.388ms      3.331ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/replica.go 1676: waiting for read lock
     3.439ms      3.381ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/replica.go 1717: read completed
     3.550ms      3.493ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/dist_sender.go 1091: RPC reply: (err: <nil>), *roachpb.GetResponse
     3.724ms      3.666ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/range_iter.go 146: querying next range at /Table/2/1/1/"rangelog"/3/1
     3.730ms      3.673ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/range_iter.go 155: meta descriptor lookup
     3.740ms      3.682ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/range_cache.go 298: looked up range descriptor from cache
     3.753ms      3.696ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/dist_sender.go 1066: sending RPC for batch: 1 Get
     3.821ms      3.764ms        event:node.Batch
     3.830ms      3.773ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] server/node.go 815: 1 Get
     3.837ms      3.780ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/stores.go 181: read has no clock uncertainty
     3.847ms      3.790ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/store.go 2391: executing 1 requests
     3.858ms      3.800ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/replica.go 1217: read-only path
     3.865ms      3.807ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/replica.go 1668: command queue
     3.873ms      3.815ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/replica.go 1676: waiting for read lock
     3.906ms      3.849ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/replica.go 1717: read completed
     4.006ms      3.948ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/dist_sender.go 1091: RPC reply: (err: <nil>), *roachpb.GetResponse
     4.158ms      4.100ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/range_iter.go 146: querying next range at /Table/3/1/13/2/1
     4.165ms      4.108ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/range_iter.go 155: meta descriptor lookup
     4.175ms      4.117ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/range_cache.go 298: looked up range descriptor from cache
     4.188ms      4.130ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/dist_sender.go 1066: sending RPC for batch: 1 Get
     4.268ms      4.211ms        event:node.Batch
     4.279ms      4.221ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] server/node.go 815: 1 Get
     4.285ms      4.228ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/stores.go 181: read has no clock uncertainty
     4.295ms      4.237ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/store.go 2391: executing 1 requests
     4.307ms      4.250ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/replica.go 1217: read-only path
     4.315ms      4.257ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/replica.go 1668: command queue
     4.323ms      4.265ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/replica.go 1676: waiting for read lock
     4.359ms      4.301ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/replica.go 1717: read completed
     4.449ms      4.391ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/dist_sender.go 1091: RPC reply: (err: <nil>), *roachpb.GetResponse
     4.818ms      4.760ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/range_iter.go 146: querying next range at /Table/13/1/2016-12-02T17:17:55.86363Z/198668045085245440/0
     4.825ms      4.767ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/range_iter.go 155: meta descriptor lookup
     4.835ms      4.778ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/range_cache.go 298: looked up range descriptor from cache
     4.850ms      4.792ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/dist_sender.go 1066: sending RPC for batch: 5 CPut
     4.931ms      4.874ms        event:node.Batch
     4.941ms      4.883ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] server/node.go 815: 5 CPut
     4.948ms      4.890ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/stores.go 181: read has no clock uncertainty
     4.958ms      4.900ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/store.go 2391: executing 5 requests
     4.968ms      4.910ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/replica.go 1214: read-write path
     4.980ms      4.922ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/replica.go 1832: command queue
     4.995ms      4.937ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/replica.go 1900: raft
     5.149ms      5.091ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/replica.go 3161: processing command 7b4fa5d0e8765c28: maxLeaseIndex=8
     5.160ms      5.102ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/replica.go 3244: applying command
     5.399ms      5.341ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/dist_sender.go 1091: RPC reply: (err: <nil>), *roachpb.ConditionalPutResponse, *roachpb.ConditionalPutResponse, *roachpb.ConditionalPutResponse, *roachpb.ConditionalPutResponse, *roachpb.ConditionalPutResponse
     5.576ms      5.518ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/range_iter.go 146: querying next range at /Meta2/Max
     5.583ms      5.525ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/range_iter.go 155: meta descriptor lookup
     5.593ms      5.536ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/range_cache.go 298: looked up range descriptor from cache
     5.602ms      5.544ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/range_iter.go 146: querying next range at /Meta2/Max
     5.612ms      5.555ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/range_iter.go 155: meta descriptor lookup
     5.623ms      5.566ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/range_cache.go 298: looked up range descriptor from cache
     5.639ms      5.582ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/dist_sender.go 1066: sending RPC for batch: 1 Put
   508.530ms    508.472ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/dist_sender.go 1080: timeout
  1010.606ms   1010.548ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/dist_sender.go 1080: timeout
  1511.928ms   1511.871ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/dist_sender.go 1080: timeout
  1662.676ms   1662.619ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/dist_sender.go 1091: RPC reply: (err: <nil>), *roachpb.PutResponse
  1662.717ms   1662.659ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/range_iter.go 146: querying next range at /Table/14
  1662.745ms   1662.688ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/range_iter.go 155: meta descriptor lookup
  1662.766ms   1662.709ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/range_cache.go 298: looked up range descriptor from cache
  1662.796ms   1662.738ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/dist_sender.go 1066: sending RPC for batch: 1 EndTxn
  1662.932ms   1662.874ms        event:node.Batch
  1662.951ms   1662.893ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] server/node.go 815: 1 EndTxn
  1662.963ms   1662.905ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/stores.go 181: read has no clock uncertainty
  1662.983ms   1662.925ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/store.go 2391: executing 1 requests
  1663.006ms   1662.948ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/replica.go 1214: read-write path
  1663.021ms   1662.963ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/replica.go 1832: command queue
  1663.049ms   1662.991ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/replica.go 1900: raft
  1663.413ms   1663.355ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/replica.go 3161: processing command 03ee69fcc04ca0c7: maxLeaseIndex=2
  1663.445ms   1663.387ms        event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/replica.go 3244: applying command
  1664.134ms   1664.076ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/dist_sender.go 1091: RPC reply: (err: <nil>), *roachpb.EndTransactionResponse
  1664.173ms   1664.115ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] kv/txn_coord_sender.go 562: coordinator stops
  1664.480ms   1664.422ms    event:util/log/log.go 88: storage/replica_command.go:3330 [n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] range modified second 1.663407343s
  1664.520ms   1664.462ms    event:[n1,replicate,s1,r5/1:/{Table/14-Max},@c4200a2d80] storage/replica_command.go 3343: txn complete
I161202 12:17:57.529592 40 storage/replica_raftstorage.go:466  [n1,replicate,s1,r4/1:/Table/1{3-4},@c4202d0480] generated preemptive snapshot 6e34e4cf at index 20
`

the delay is occurring in 

`func (ds *DistSender) sendToReplicas(`

I've added some more events to this and I'll add a commit later to this issue. 

occasionally a RPC with 1 Put takes like 1.6 seconds to return and it returns without an error. What's surprising is it returns with no Spans, so the trace is empty. See the Spans for the other RPCs are all nicely filled out.

**Comment by petermattis** [comment]
I just tested `TestBasicAutoReplication` and it reliably (99 out of 100 runs) takes 0.5s to run. I'm going to file a separate issue about the one super-long run.
