### ISSUE TITLE
sql: extract DTable-typed render expressions as cross-join

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#11215]
Assuming here #11214 has been merged.

If the clause `SELECT e` is used and `e` is an expression of type `DTable`, then the query should be transposed to `SELECT * FROM e`. 

Needed to support `SELECT generate_series(...)` and `SELECT unnest(...)`.

Reported in https://github.com/cockroachdb/cockroach/issues/5582#issuecomment-261254147.

**Comment by knz** [comment]
The reference to cross joins in the title of the issue is because 

`SELECT a,b,c, generate_series(...) FROM x` 

is equivalent to 

 `SELECT a,b,c,tmp.* FROM x, generate_series(...) as tmp`.

i.e. the render should be extracted into the FROM clause by turning it into a cross join.

**Comment by knz** [comment]
cc @cuongdo @nvanbenschoten

**Comment by jordanlewis** [comment]
Along with this transformation, we should consider whether we'd like to limit the positions in which DTable-returning builtins (aka set-returning functions or SRFs) can be invoked. At the moment, for instance, we allow users to call them from `ORDER BY` expressions but not `GROUP BY` expressions. I don't imagine we care to support either of these use cases, but it's worth thinking about.

Postgres has a [function](https://github.com/postgres/postgres/blob/d43a619c60405ecda275ca9e3ac9ead242e20ecb/src/backend/parser/parse_func.c#L2058) that checks to see whether SRFs are located in a valid spot. We probably need to implement something similar to this as well, although it's not clear to me whether we have the infrastructure for performing such a check easily at the moment.
