### ISSUE TITLE
schemachanger: TestBackupSuccessMixedVersion and TestBackupRollbacksMixedVersion fail with min supported version 23.1

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#112208]
`TestBackupSuccessMixedVersion_base_create_function_in_txn` and `TestBackupRollbacksMixedVersion_base_add_column_default_unique` tests fail once the minimum supported version is bumped to 23.1. I couldn't figure out right away how to fix them. I will be skipping them for now.

More details in this build:
https://teamcity.cockroachdb.com/viewLog.html?buildId=12145489&buildTypeId=Cockroach_BazelEssentialCi

Jira issue: CRDB-32294

**Comment by fqazi** [comment]
The failure is linked to https://github.com/cockroachdb/cockroach/commit/02705f7aee19e86462948cfd636f26400ced194c, which will eventually fail once the validation logic executes
