### ISSUE TITLE
multitenant: TestTenantUpgradeFailure fails when min version is bumped to 23.1

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#112209]
`TestTenantUpgradeFailure` seems to rely on a release version existing strictly between the minimum supported version and the current version. This is no longer true once we bump the minimum supported version to 23.1 (for the 23.2 release).

Jira issue: CRDB-32295

**Comment by yuzefovich** [comment]
Indeed, based on the last [time](https://github.com/cockroachdb/cockroach/issues/98555#issuecomment-1516689274) we adjusted this test, it assumes that there exists such a `v1` that `v0 < v1 < v2`, and `v1` and `v2` only differ in `Internal` whereas `v0` is the previous "major" release version. This state implies that we need to have `V23_2` and `V24_1Start` defined, and then the test will work (which I verified).

I don't see an easy way to refactor this unit test to remove this assumption (but I'm not familiar with the upgrades). To me it seems like this test can be skipped until `V23_2 = (23 : 2 : 0)` and `V24_1Start = (23 : 2 : 2)` are defined. cc @ajstorm @stevendanna in case you have opinions.

**Comment by RaduBerinde** [comment]
Cool, I will reenable on master when I bump the version.

**Comment by yuzefovich** [comment]
Thanks Radu, I'll assign the issue to you then.

**Comment by stevendanna** [comment]
@RaduBerinde It looks like maybe this was fixed here: https://github.com/cockroachdb/cockroach/commit/f74fff67fdee#diff-47be6646fc129bea75b3b9999532a6dafb4f609cdbdb23234bd308f5fd2e4364L408 or am I misunderstanding?

**Comment by RaduBerinde** [comment]
Right, thanks!
