### ISSUE TITLE
schemachanger: TestCompareLegacyAndDeclarative failed under stressrace on 23.2

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#112301]
See CI flake [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=12161739&buildTypeId=Cockroach_BazelExtendedCi).

Jira issue: CRDB-32343

**Comment by DrewKimball** [comment]
Saw it here: https://github.com/cockroachdb/cockroach/pull/112327
and here as well: https://github.com/cockroachdb/cockroach/pull/112337
