### ISSUE TITLE
Sentry: store_remove_replica.go:120: log.Fatal: replica descriptor's ID has changed (3 >= 2)
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).re...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#112304]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4545665227/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4545665227/?referrer=webhooks_plugin)

Panic Message:

```
store_remove_replica.go:120: log.Fatal: replica descriptor's ID has changed (3 >= 2)
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).removeInitializedReplicaRaftMuLocked
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_remove_replica.go:120
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).RemoveReplica
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_remove_replica.go:51
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*replicaGCQueue).process
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_gc_queue.go:321
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*baseQueue).processReplica.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/queue.go:1012
  | github.com/cockroachdb/cockroach/pkg/util/contextutil.RunWithTimeout
  | 	github.com/cockroachdb/cockroach/pkg/util/contextutil/context.go:91
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*baseQueue).processReplica
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/queue.go:971
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*baseQueue).processLoop.func2.1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/queue.go:882
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (2) log.Fatal: replica descriptor's ID has changed (3 >= 2)
Error types: (1) *withstack.withStack (2) *errutil.leafError
-- report composition:
*errutil.leafError: log.Fatal: replica descriptor's ID has changed (3 >= 2)
store_remove_replica.go:120: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/util/stop/stopper.go#L469-L471](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/util/stop/stopper.go#L469-L471)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/kv/kvserver/pkg/kv/kvserver/queue.go#L881-L883](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/kv/kvserver/pkg/kv/kvserver/queue.go#L881-L883)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/kv/kvserver/pkg/kv/kvserver/queue.go#L970-L972](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/kv/kvserver/pkg/kv/kvserver/queue.go#L970-L972)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/util/contextutil/context.go#L90-L92](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/util/contextutil/context.go#L90-L92)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/kv/kvserver/pkg/kv/kvserver/queue.go#L1011-L1013](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/kv/kvserver/pkg/kv/kvserver/queue.go#L1011-L1013)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/kv/kvserver/pkg/kv/kvserver/replica_gc_queue.go#L320-L322](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/kv/kvserver/pkg/kv/kvserver/replica_gc_queue.go#L320-L322)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/kv/kvserver/pkg/kv/kvserver/store_remove_replica.go#L50-L52](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/kv/kvserver/pkg/kv/kvserver/store_remove_replica.go#L50-L52)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/kv/kvserver/pkg/kv/kvserver/store_remove_replica.go#L119-L121](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/kv/kvserver/pkg/kv/kvserver/store_remove_replica.go#L119-L121)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 470
pkg/kv/kvserver/pkg/kv/kvserver/queue.go in pkg/kv/kvserver.(*baseQueue).processLoop.func2.1 at line 882
pkg/kv/kvserver/pkg/kv/kvserver/queue.go in pkg/kv/kvserver.(*baseQueue).processReplica at line 971
pkg/util/contextutil/context.go in pkg/util/contextutil.RunWithTimeout at line 91
pkg/kv/kvserver/pkg/kv/kvserver/queue.go in pkg/kv/kvserver.(*baseQueue).processReplica.func1 at line 1012
pkg/kv/kvserver/pkg/kv/kvserver/replica_gc_queue.go in pkg/kv/kvserver.(*replicaGCQueue).process at line 321
pkg/kv/kvserver/pkg/kv/kvserver/store_remove_replica.go in pkg/kv/kvserver.(*Store).RemoveReplica at line 51
pkg/kv/kvserver/pkg/kv/kvserver/store_remove_replica.go in pkg/kv/kvserver.(*Store).removeInitializedReplicaRaftMuLocked at line 120
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v23.1.5 |
| Go Version | go1.19.10 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.5 |
| Cockroach SHA | 72556c6b5dc0d4ed1a0202bc4176586956d54739 |
| # of CPUs | 8 |
| # of Goroutines | 490 |

Jira issue: CRDB-32346

**Comment by yuzefovich** [comment]
unactionable
