### ISSUE TITLE
kv: a replayed write can cause an infinite lock discovery loop

### ISSUE THREAD

**Issue by miraradeva** [cockroachdb/cockroach#112409]
**Describe the problem**
Suppose `txn1` writes to a key, and that write is replayed for some reason at a higher timestamp; this can happen if `txn1` was pushed in between the write and the replay. The first time `txn1` writes at `ts1`, it creates a new intent with `ts1` and a corresponding lock table replicated lock (with the caveat that to actually add the lock table entry some other request needs to wait on that lock). When `txn1` replays the write at `ts3` (where `ts1 < ts3`), the intent is not updated [because the seq num and value are the same](https://github.com/cockroachdb/cockroach/blob/master/pkg/storage/mvcc.go#L1970) as the first write. But [the lock table entry's ts gets forwarded](https://github.com/cockroachdb/cockroach/blob/master/pkg/kv/kvserver/concurrency/lock_table.go#L1227) to `ts3`. Now we have a mismatch, which can lead to problems.

Suppose `txn2` tries to read the same key at `ts2`, where `ts1 < ts2 < ts3`. It scans the lock table and finds no conflict because `ts2 < ts3`. It goes on to evaluate and discovers a conflicting intent at `ts1`. `Txn2`'s read tries to add the discovered intent but the lock table doesn't update the ts from `ts3` to `ts1` because timestamps are not allowed to regress. Now `txn2`'s read is stuck in an infinite loop of re-discovering the lock and not being able to update it in the lock table.

To turn this situation into a deadlock, we just need to add a dependency of `txn1` on `txn2`; e.g. `txn1` tries to write to a different key that `txn2` has a lock on. `Txn1` will keep pushing `txn2` unsuccessfully because txn2 is alive and heartbeating while stuck in the loop above.

**To Reproduce**
See #112410 for a unit test repro.

**Expected behavior**
The lock table replicated lock's and stored intent' timestamps should match. We can probably do this in a few ways:
1. [Implemented in #112410] When a write is replayed, in addition to checking that the seqNum, epuch and value are the same, also check that the timestamp is the same. If the new timestamp is greater than the old timestamp, rewrite the intent. We don't want to add an entry in the intent history, so one option is to reuse the logic in intent resolution ( for the case of an intent whose txn's timestamp was pushed).
2. When an intent is written, communicate back to the lock table what timestamp it was written at. The txn info that we currently communicate is not enough because in the case of a replayed write with a higher timestamp, the txn timestamp is higher than the intent timestamp. Maybe just a boolean would be enough to indicate if the intent was updated or not.
3. We can use a mechanism similar to the recently-added [replayWriteTimestampProtection](https://github.com/cockroachdb/cockroach/blob/master/pkg/storage/mvcc.go#L2068), which will fail the replay at a new timestamp. This doesn't seem great as it will cause the txn to retry.

**Additional context**
This issue is the reason for the timeouts in kvnemesis (#111352). The bug is not new (even though there were some refactors in the area like #110145) but the addition of replicated and shared locks introduced more locks in the lock table and made it easier for this issue to manifest.

Jira issue: CRDB-32407

**Comment by nvanbenschoten** [comment]
This is being discussed in https://cockroachlabs.slack.com/archives/C04AFSL6E3C/p1698082912184179.
