### ISSUE TITLE
mixed-version framework: logs misleading binary versions after upgrade to `<current>`

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#112431]
While investigating #112373, I noticed the following in the test log:

the pre test plan stated the following: where current is `release-23.2`
```
├── upgrade nodes :1-4 from "23.1.11" to "<current>"
  1    │   ├── restart node 4 with binary version <current> (24)
  2    │   ├── restart node 2 with binary version <current> (25)
  3    │   ├── restart node 3 with binary version <current> (26)
  4    │   ├── run "verify some backups" (27)
  5    │   ├── restart node 1 with binary version <current> (28)
  6    │   └── run "plan and run backups" (29)
```

But around these steps, the following was printed for the binary version:
```
[mixed-version-test/29_run-plan-and-run-backups] 10:18:57 runner.go:382: ---------- STARTING (29): run "plan and run backups" ----------
[mixed-version-test/29_run-plan-and-run-backups] 10:18:57 runner.go:396: binary versions: [1: 23.1-38, 2: 23.1-38, 3: 23.1-38, 4: 23.1-38]
[mixed-version-test/29_run-plan-and-run-backups] 10:18:57 runner.go:397: cluster versions: [1: 23.1, 2: 23.1, 3: 23.1, 4: 23.1]
```

notice that the binary version is `23.1-38`, which actually translates to `release-23.2`. This seems misleading.

I'm unsure if this is test code issue or if I should move this to the release team board. I'll let @renatolabs give his two cents.

Jira issue: CRDB-32418

**Comment by renatolabs** [comment]
Could you elaborate a bit more? By step 29, all nodes have been restarted and are running the `current` version (i.e., release-23.2), as you mentioned. Isn't it expected that their binary versions would be `23.1-38`, the latest binary version in release-23.2 at the moment?

**Comment by msbutler** [comment]
I think a lay person (a db engineer (me) investigating a test failure, or even tse looking at some logs) conceptualizes this binary version :
```
	{
		Key:     V23_2_UDFMutations,
		Version: roachpb.Version{Major: 23, Minor: 1, Internal: 38},
	},
```

as a 23.2 binary, in an unfinalized state. So, when when I saw the log for `23.1-38`, I initially thought this binary was running off of some 23.1 patch release. 

Perhaps the solution here is more education. We could even tweak how we stringify `keyedVersion` to be more user friendly: that keyed version could stringify to `23.1-38 (unfinalized 23.2)`. IDK. We have bigger fish to fry now.

**Comment by msbutler** [comment]
Yeah, i think your proposed change to the test would be helpful, but certainly not high priority!
