### ISSUE TITLE
Sentry: conn_executor.go:880: runtime error: slice bounds out of range [:-2079557684]
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#112534]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4553736770/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4553736770/?referrer=webhooks_plugin)

Panic Message:

```
conn_executor.go:880: runtime error: slice bounds out of range [:-2079557684]
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:880
  | [...repeated from below...]
Wraps: (2) while executing: SELECT _._ AS _, max(_._) AS _, min(_._) AS _, min(_._) AS _, min(_._) AS _, min(_._) AS _, min(_._) AS _, array_agg(_._) AS _, count(*) AS _ FROM _ AS _ INNER MERGE JOIN _ AS _ ON (_._ = _._) AND (_._ = _._) INNER JOIN _ AS _ ON (_._ = _._) AND (_._ = '_') WHERE (_._ = $1) GROUP BY _._ ORDER BY _ ASC LIMIT $1 OFFSET $1
Wraps: (3) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:880
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Wait
  | 	github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:511
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:58
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:58
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:58
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:58
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | runtime.goPanicSliceAcap
  | 	GOROOT/src/runtime/panic.go:139
  | github.com/apache/arrow/go/arrow/array.(*Binary).ValueBytes
  | 	github.com/apache/arrow/go/arrow/array/external/com_github_apache_arrow_go_arrow/array/binary.go:83
  | github.com/cockroachdb/cockroach/pkg/col/colserde.(*ArrowBatchConverter).ArrowToBatch
  | 	github.com/cockroachdb/cockroach/pkg/col/colserde/arrowbatchconverter.go:429
  | github.com/cockroachdb/cockroach/pkg/col/colserde.(*FileDeserializer).GetBatch
  | 	github.com/cockroachdb/cockroach/pkg/col/colserde/file.go:250
  | github.com/cockroachdb/cockroach/pkg/sql/colcontainer.(*diskQueue).Dequeue
  | 	github.com/cockroachdb/cockroach/pkg/sql/colcontainer/diskqueue.go:777
  | github.com/cockroachdb/cockroach/pkg/sql/colcontainer.(*PartitionedDiskQueue).Dequeue
  | 	github.com/cockroachdb/cockroach/pkg/sql/colcontainer/partitionedqueue.go:295
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk.(*partitionerToOperator).Next.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk/utils.go:67
  | github.com/cockroachdb/cockroach/pkg/sql/colmem.(*Allocator).PerformOperation
  | 	github.com/cockroachdb/cockroach/pkg/sql/colmem/allocator.go:432
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk.(*partitionerToOperator).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk/utils.go:66
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*OrderedSynchronizer).Next
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/colexec/ordered_synchronizer.eg.go:106
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk.(*externalSorter).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk/external_sort.go:432
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk.(*diskSpillerBase).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk/disk_spiller.go:211
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:116
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:124
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*OrderedSynchronizer).Next
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/colexec/ordered_synchronizer.eg.go:106
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:116
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:124
  | github.com/cockroachdb/cockroach/pkg/sql/colexecop.(*noopOperator).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecop/operator.go:393
Wraps: (4) runtime error: slice bounds out of range [:-2079557684]
Error types: (1) *withstack.withStack (2) *safedetails.withSafeDetails (3) *withstack.withStack (4) runtime.boundsError
-- report composition:
runtime.boundsError
conn_executor.go:880: *withstack.withStack (top exception)
*safedetails.withSafeDetails: while executing: SELECT _._ AS _, max(_._) AS _, min(_._) AS _, min(_._) AS _, min(_._) AS _, min(_._) AS _, min(_._) AS _, array_agg(_._) AS _, count(*) AS _ FROM _ AS _ INNER MERGE JOIN _ AS _ ON (_._ = _._) AND (_._ = _._) INNER JOIN _ AS _ ON (_._ = _._) AND (_._ = '_') WHERE (_._ = $1) GROUP BY _._ ORDER BY _ ASC LIMIT $1 OFFSET $1
conn_executor.go:880: *withstack.withStack (1)
(check the extra data payloads)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexecop/operator.go#L392-L394](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexecop/operator.go#L392-L394)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colflow/stats.go#L123-L125](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colflow/stats.go#L123-L125)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colflow/stats.go#L115-L117](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colflow/stats.go#L115-L117)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/bazel-out/k8-opt/bin/pkg/sql/colexec/ordered_synchronizer.eg.go#L105-L107](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/bazel-out/k8-opt/bin/pkg/sql/colexec/ordered_synchronizer.eg.go#L105-L107)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colflow/stats.go#L123-L125](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colflow/stats.go#L123-L125)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colflow/stats.go#L115-L117](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colflow/stats.go#L115-L117)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexec/colexecdisk/disk_spiller.go#L210-L212](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexec/colexecdisk/disk_spiller.go#L210-L212)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexec/colexecdisk/external_sort.go#L431-L433](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexec/colexecdisk/external_sort.go#L431-L433)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/bazel-out/k8-opt/bin/pkg/sql/colexec/ordered_synchronizer.eg.go#L105-L107](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/bazel-out/k8-opt/bin/pkg/sql/colexec/ordered_synchronizer.eg.go#L105-L107)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexec/colexecdisk/utils.go#L65-L67](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexec/colexecdisk/utils.go#L65-L67)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colmem/allocator.go#L431-L433](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colmem/allocator.go#L431-L433)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexec/colexecdisk/utils.go#L66-L68](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexec/colexecdisk/utils.go#L66-L68)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colcontainer/partitionedqueue.go#L294-L296](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colcontainer/partitionedqueue.go#L294-L296)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colcontainer/diskqueue.go#L776-L778](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colcontainer/diskqueue.go#L776-L778)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/col/colserde/file.go#L249-L251](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/col/colserde/file.go#L249-L251)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/col/colserde/arrowbatchconverter.go#L428-L430](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/col/colserde/arrowbatchconverter.go#L428-L430)
[github.com/apache/arrow/go/arrow/array/external/com_github_apache_arrow_go_arrow/array/binary.go#L82-L84](github.com/apache/arrow/go/arrow/array/external/com_github_apache_arrow_go_arrow/array/binary.go#L82-L84)
[GOROOT/src/runtime/panic.go#L138-L140](GOROOT/src/runtime/panic.go#L138-L140)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexecerror/error.go#L57-L59](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexecerror/error.go#L57-L59)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexecerror/error.go#L57-L59](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexecerror/error.go#L57-L59)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexecerror/error.go#L57-L59](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexecerror/error.go#L57-L59)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexecerror/error.go#L57-L59](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexecerror/error.go#L57-L59)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/flowinfra/flow.go#L510-L512](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/flowinfra/flow.go#L510-L512)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor.go#L879-L881](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor.go#L879-L881)
</details>

```
pkg/sql/colexecop/operator.go in pkg/sql/colexecop.(*noopOperator).Next at line 393
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).Next at line 124
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).next at line 116
bazel-out/k8-opt/bin/pkg/sql/colexec/ordered_synchronizer.eg.go in pkg/sql/colexec.(*OrderedSynchronizer).Next at line 106
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).Next at line 124
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).next at line 116
pkg/sql/colexec/colexecdisk/disk_spiller.go in pkg/sql/colexec/colexecdisk.(*diskSpillerBase).Next at line 211
pkg/sql/colexec/colexecdisk/external_sort.go in pkg/sql/colexec/colexecdisk.(*externalSorter).Next at line 432
bazel-out/k8-opt/bin/pkg/sql/colexec/ordered_synchronizer.eg.go in pkg/sql/colexec.(*OrderedSynchronizer).Next at line 106
pkg/sql/colexec/colexecdisk/utils.go in pkg/sql/colexec/colexecdisk.(*partitionerToOperator).Next at line 66
pkg/sql/colmem/allocator.go in pkg/sql/colmem.(*Allocator).PerformOperation at line 432
pkg/sql/colexec/colexecdisk/utils.go in pkg/sql/colexec/colexecdisk.(*partitionerToOperator).Next.func1 at line 67
pkg/sql/colcontainer/partitionedqueue.go in pkg/sql/colcontainer.(*PartitionedDiskQueue).Dequeue at line 295
pkg/sql/colcontainer/diskqueue.go in pkg/sql/colcontainer.(*diskQueue).Dequeue at line 777
pkg/col/colserde/file.go in pkg/col/colserde.(*FileDeserializer).GetBatch at line 250
pkg/col/colserde/arrowbatchconverter.go in pkg/col/colserde.(*ArrowBatchConverter).ArrowToBatch at line 429
github.com/apache/arrow/go/arrow/array/external/com_github_apache_arrow_go_arrow/array/binary.go in github.com/apache/arrow/go/arrow/array.(*Binary).ValueBytes at line 83
GOROOT/src/runtime/panic.go in runtime.goPanicSliceAcap at line 139
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1 at line 58
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1 at line 58
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1 at line 58
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1 at line 58
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
pkg/sql/flowinfra/flow.go in pkg/sql/flowinfra.(*FlowBase).Wait at line 511
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn.func1 at line 880
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v22.2.14 |
| Go Version | go1.19.6 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v22.2.14 |
| Cockroach SHA | af6752b2faf39115fd322e9db76421e71b76507d |
| # of CPUs | 16 |
| # of Goroutines | 3334 |

Jira issue: CRDB-32476

**Comment by yuzefovich** [comment]
unactionable
