### ISSUE TITLE
Sentry: crash_reporting.go:390: got a span level timestamp 1697620828.203773054,0 for × that is less than the initial high-water 1697624267.363352466,0
(1) attached stack trace
  -- stack trace:
  | ...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#112595]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4555778595/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4555778595/?referrer=webhooks_plugin)

Panic Message:

```
crash_reporting.go:390: got a span level timestamp 1697620828.203773054,0 for × that is less than the initial high-water 1697624267.363352466,0
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/util/log/logcrash.ReportOrPanic
  | 	github.com/cockroachdb/cockroach/pkg/util/log/logcrash/crash_reporting.go:390
  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*changeFrontier).noteAggregatorProgress
  | 	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_processors.go:1180
  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.(*changeFrontier).Next
  | 	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_processors.go:1146
  | github.com/cockroachdb/cockroach/pkg/sql/execinfra.Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/execinfra/base.go:195
  | github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBaseNoHelper).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:726
  | github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:575
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:902
  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.startDistChangefeed.func3
  | 	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_dist.go:323
  | github.com/cockroachdb/cockroach/pkg/util/ctxgroup.Group.GoCtx.func1
  | 	github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:168
  | golang.org/x/sync/errgroup.(*Group).Go.func1
  | 	golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:75
  | runtime.goexit
  | 	src/runtime/asm_arm64.s:1172
Wraps: (2) got a span level timestamp 1697620828.203773054,0 for × that is less than the initial high-water 1697624267.363352466,0
Error types: (1) *withstack.withStack (2) *errutil.leafError
-- report composition:
*errutil.leafError: got a span level timestamp 1697620828.203773054,0 for × that is less than the initial high-water 1697624267.363352466,0
crash_reporting.go:390: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_arm64.s#L1171-L1173](src/runtime/asm_arm64.s#L1171-L1173)
[golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go#L74-L76](golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go#L74-L76)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/util/ctxgroup/ctxgroup.go#L167-L169](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/util/ctxgroup/ctxgroup.go#L167-L169)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/ccl/changefeedccl/changefeed_dist.go#L322-L324](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/ccl/changefeedccl/changefeed_dist.go#L322-L324)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/distsql_running.go#L901-L903](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/distsql_running.go#L901-L903)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/flowinfra/flow.go#L574-L576](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/flowinfra/flow.go#L574-L576)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/execinfra/processorsbase.go#L725-L727](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/execinfra/processorsbase.go#L725-L727)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/execinfra/base.go#L194-L196](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/execinfra/base.go#L194-L196)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/ccl/changefeedccl/changefeed_processors.go#L1145-L1147](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/ccl/changefeedccl/changefeed_processors.go#L1145-L1147)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/ccl/changefeedccl/changefeed_processors.go#L1179-L1181](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/ccl/changefeedccl/changefeed_processors.go#L1179-L1181)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/util/log/logcrash/crash_reporting.go#L389-L391](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/util/log/logcrash/crash_reporting.go#L389-L391)
</details>

```
src/runtime/asm_arm64.s in runtime.goexit at line 1172
golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go in golang.org/x/sync/errgroup.(*Group).Go.func1 at line 75
pkg/util/ctxgroup/ctxgroup.go in pkg/util/ctxgroup.Group.GoCtx.func1 at line 168
pkg/ccl/changefeedccl/changefeed_dist.go in pkg/ccl/changefeedccl.startDistChangefeed.func3 at line 323
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).Run at line 902
pkg/sql/flowinfra/flow.go in pkg/sql/flowinfra.(*FlowBase).Run at line 575
pkg/sql/execinfra/processorsbase.go in pkg/sql/execinfra.(*ProcessorBaseNoHelper).Run at line 726
pkg/sql/execinfra/base.go in pkg/sql/execinfra.Run at line 195
pkg/ccl/changefeedccl/changefeed_processors.go in pkg/ccl/changefeedccl.(*changeFrontier).Next at line 1146
pkg/ccl/changefeedccl/changefeed_processors.go in pkg/ccl/changefeedccl.(*changeFrontier).noteAggregatorProgress at line 1180
pkg/util/log/logcrash/crash_reporting.go in pkg/util/log/logcrash.ReportOrPanic at line 390
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v23.1.10 |
| Go Version | go1.19.10 |
| Platform | linux arm64 |
| Distribution | CCL |
| Cockroach Release | v23.1.10 |
| Cockroach SHA | 6bd6e0c65a2eba531e7a8412d63988abb5b50120 |
| # of CPUs | 3 |
| # of Goroutines | 2159 |

Jira issue: CRDB-32511

**Comment by yuzefovich** [comment]
dup of #77485
