### ISSUE TITLE
sql/catalog/lease: TestLeaseRenewedAutomatically is flaky

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#112550]
https://teamcity.cockroachdb.com/viewLog.html?buildId=12221306&buildTypeId=Cockroach_BazelExtendedCi

Maybe we just want to skip it under race.

Jira issue: CRDB-32488

**Comment by rafiss** [comment]
I see that TestLeaseManagerReacquire took 8 minutes to run. The cause of the failure here is that package-wide test timeout. So making `TestLeaseManagerReacquire` faster would be another way to resolve this.

**Comment by rafiss** [comment]
there is a more interesting failure here: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_Tests_MaybeStress/12576909?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

```
=== RUN   TestLeaseRenewedAutomatically
    test_log_scope.go:170: test logs captured to: /artifacts/tmp/_tmp/ce8d73b4a4081f39d36a7fa2c2508fcc/logTestLeaseRenewedAutomatically2623214687
    test_log_scope.go:81: use -show-logs to present logs inline
    test_server_shim.go:165: automatically injected an external process virtual cluster under test; see comment at top of test_server_shim.go for details.
    lease_test.go:1361: expected repeated lease acquisition to not block, but blockCount is: 1
    panic.go:522: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/ce8d73b4a4081f39d36a7fa2c2508fcc/logTestLeaseRenewedAutomatically2623214687
--- FAIL: TestLeaseRenewedAutomatically (12.78s)
```

**Comment by michae2** [comment]
Saw this again here:

https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelExtendedCi/13000619?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

**Comment by rafiss** [comment]
failed here: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/13504395?expandBuildProblemsSection=true&hideProblemsFromDependencies=false&expandBuildTestsSection=true&hideTestsFromDependencies=false&expandBuildChangesSection=true
```
lease_test.go:1361: expected repeated lease acquisition to not block, but blockCount is: 1
```
