### ISSUE TITLE
sql: investigate Non-nullable column "‹×›:‹×›" with no value! error

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#112537]
The error was seen once in this Splunk search: https://cockroachlabsgcp.splunkcloud.com/en-US/app/search/search?earliest=-7d%40h&latest=now&q=search%20index%3Dcc-app-crdb*%20%22non-nullable%20column%22%20%22with%20no%20value!%22%20%7C%20timechart%20span%3D1h%20count%20by%20friendly_id&display.page.search.mode=verbose&dispatch.sample_ratio=1&display.general.type=statistics&display.page.search.tab=events&sid=1697553032.122951&workload_pool=standard_perf

Let's track this down:
- Check with SQL Queries and TSE to see if they have heard of this instance of the error already.
- Check if the Serverless cluster still exists.
- If TSE wants to investigate, use https://su.cockroachlabs.cloud/ to try to find which piece of data is invalid.

Jira issue: CRDB-32479

**Comment by yuzefovich** [comment]
dup of #113013
