### ISSUE TITLE
kv/kvserver: TestGossipHandlesReplacedNode fails under stress

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#112551]
https://teamcity.cockroachdb.com/viewLog.html?buildId=12221306&buildTypeId=Cockroach_BazelExtendedCi

```
    testcluster.go:686: timed out waiting for 4 store descriptors: map[1:{} 2:{} 3:{}]
```

Jira issue: CRDB-32489

**Comment by pavelkalinnikov** [comment]
[Failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/12347341?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildTestsSection=true) in CI today too.

**Comment by kvoli** [comment]
Assigning P3, appears as a testing issue with port re-use, see https://github.com/andrewbaptist/cockroach/commit/2376beb0c594a22894449e3dd7231d732c15a5a9.
