### ISSUE TITLE
scplan: create `scplan/internal/rules/release_23_2`

### ISSUE THREAD

**Issue by Xiang-Gu** [cockroachdb/cockroach#112571]
The declarative schema changer maintains dep-rule between releases by grouping all rules present in each release in a separate directory. Now that branch `release-23.2` is cut, we should create one for it on master. 

Note: It's currently not doable as cluster version `V24_1` does not exist yet on master

Jira issue: CRDB-32498

**Comment by rafiss** [comment]
@Xiang-Gu the version should exist now, since https://github.com/cockroachdb/cockroach/pull/112271 was merged.

I believe resolving this issue should also resolve https://github.com/cockroachdb/cockroach/issues/112376.
