### ISSUE TITLE
Allow the ability to make the system database tables a global table

### ISSUE THREAD

**Issue by dikshant** [cockroachdb/cockroach#112583]
23.2 allows us to make system database tables (namespace, descriptor) etc a global table on Serverless clusters. We should allow this in other setups as well (dedicated, self-hosted). This will help with speeding up driver/ORM introspection queries in multi-region clusters that can otherwise roundtrip across many different regions.

Jira issue: CRDB-32505

**Comment by rafiss** [comment]
This is a duplicate of https://github.com/cockroachdb/cockroach/issues/63365
