### ISSUE TITLE
Sentry: sideload.go:25: loading sideloaded data: sideloaded file not found
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | go.etcd.io/raft/v3.(*...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#112647]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4557047803/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4557047803/?referrer=webhooks_plugin)

Panic Message:

```
sideload.go:25: loading sideloaded data: sideloaded file not found
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | go.etcd.io/raft/v3.(*raftLog).slice
  | 	go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/log.go:507
  | go.etcd.io/raft/v3.(*raftLog).nextCommittedEnts
  | 	go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/log.go:235
  | go.etcd.io/raft/v3.(*RawNode).readyWithoutAccept
  | 	go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/rawnode.go:144
  | go.etcd.io/raft/v3.(*RawNode).Ready
  | 	go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/rawnode.go:132
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked.func2
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:777
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).withRaftGroupLocked.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:1994
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).withRaftGroupLocked
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:1995
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:769
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReady
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:725
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processReady
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:646
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftSchedulerShard).worker
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:395
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).Start.func2
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:302
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/logstore.MaybeInlineSideloadedRaftCommand
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/logstore/sideload.go:209
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/logstore.LoadEntries.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/logstore/logstore.go:546
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/raftlog.Visit
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/raftlog/iterator.go:145
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/logstore.LoadEntries
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/logstore/logstore.go:573
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*replicaRaftStorage).Entries
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raftstorage.go:87
  | go.etcd.io/raft/v3.(*raftLog).slice
  | 	go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/log.go:501
  | go.etcd.io/raft/v3.(*raftLog).nextCommittedEnts
  | 	go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/log.go:235
  | go.etcd.io/raft/v3.(*RawNode).readyWithoutAccept
  | 	go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/rawnode.go:144
  | go.etcd.io/raft/v3.(*RawNode).Ready
  | 	go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/rawnode.go:132
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked.func2
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:777
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).withRaftGroupLocked.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:1994
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).withRaftGroupLocked
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:1995
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:769
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReady
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:725
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processReady
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:646
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftSchedulerShard).worker
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:395
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).Start.func2
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:302
  | [...repeated from below...]
Wraps: (3) loading sideloaded data
Wraps: (4) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/logstore.init
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/logstore/sideload.go:25
  | runtime.doInit
  | 	GOROOT/src/runtime/proc.go:6349
  | runtime.doInit
  | 	GOROOT/src/runtime/proc.go:6326
  | runtime.doInit
  | 	GOROOT/src/runtime/proc.go:6326
  | runtime.doInit
  | 	GOROOT/src/runtime/proc.go:6326
  | runtime.doInit
  | 	GOROOT/src/runtime/proc.go:6326
  | runtime.main
  | 	GOROOT/src/runtime/proc.go:233
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (5) sideloaded file not found
Error types: (1) *withstack.withStack (2) *withstack.withStack (3) *errutil.withPrefix (4) *withstack.withStack (5) *errutil.leafError
-- report composition:
*errutil.leafError: sideloaded file not found
sideload.go:25: *withstack.withStack (top exception)
*errutil.withPrefix: loading sideloaded data
sideload.go:209: *withstack.withStack (1)
panic.go:884: *withstack.withStack (2)
(check the extra data payloads)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/util/stop/stopper.go#L469-L471](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/util/stop/stopper.go#L469-L471)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L301-L303](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L301-L303)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L394-L396](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L394-L396)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L645-L647](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L645-L647)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L724-L726](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L724-L726)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L768-L770](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L768-L770)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L1994-L1996](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L1994-L1996)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L1993-L1995](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L1993-L1995)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L776-L778](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L776-L778)
[go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/rawnode.go#L131-L133](go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/rawnode.go#L131-L133)
[go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/rawnode.go#L143-L145](go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/rawnode.go#L143-L145)
[go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/log.go#L234-L236](go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/log.go#L234-L236)
[go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/log.go#L506-L508](go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/log.go#L506-L508)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/util/stop/stopper.go#L469-L471](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/util/stop/stopper.go#L469-L471)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L301-L303](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L301-L303)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L394-L396](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L394-L396)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L645-L647](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L645-L647)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L724-L726](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L724-L726)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L768-L770](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L768-L770)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L1994-L1996](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L1994-L1996)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L1993-L1995](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L1993-L1995)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L776-L778](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L776-L778)
[go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/rawnode.go#L131-L133](go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/rawnode.go#L131-L133)
[go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/rawnode.go#L143-L145](go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/rawnode.go#L143-L145)
[go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/log.go#L234-L236](go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/log.go#L234-L236)
[go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/log.go#L500-L502](go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/log.go#L500-L502)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/kvserver/pkg/kv/kvserver/replica_raftstorage.go#L86-L88](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/kvserver/pkg/kv/kvserver/replica_raftstorage.go#L86-L88)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/kvserver/logstore/logstore.go#L572-L574](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/kvserver/logstore/logstore.go#L572-L574)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/kvserver/raftlog/iterator.go#L144-L146](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/kvserver/raftlog/iterator.go#L144-L146)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/kvserver/logstore/logstore.go#L545-L547](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/kvserver/logstore/logstore.go#L545-L547)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/kvserver/logstore/sideload.go#L208-L210](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/kvserver/logstore/sideload.go#L208-L210)
[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[GOROOT/src/runtime/proc.go#L232-L234](GOROOT/src/runtime/proc.go#L232-L234)
[GOROOT/src/runtime/proc.go#L6325-L6327](GOROOT/src/runtime/proc.go#L6325-L6327)
[GOROOT/src/runtime/proc.go#L6325-L6327](GOROOT/src/runtime/proc.go#L6325-L6327)
[GOROOT/src/runtime/proc.go#L6325-L6327](GOROOT/src/runtime/proc.go#L6325-L6327)
[GOROOT/src/runtime/proc.go#L6325-L6327](GOROOT/src/runtime/proc.go#L6325-L6327)
[GOROOT/src/runtime/proc.go#L6348-L6350](GOROOT/src/runtime/proc.go#L6348-L6350)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/kvserver/logstore/sideload.go#L24-L26](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/kvserver/logstore/sideload.go#L24-L26)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 470
pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go in pkg/kv/kvserver.(*raftScheduler).Start.func2 at line 302
pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go in pkg/kv/kvserver.(*raftSchedulerShard).worker at line 395
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).processReady at line 646
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).handleRaftReady at line 725
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked at line 769
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).withRaftGroupLocked at line 1995
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).withRaftGroupLocked.func1 at line 1994
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked.func2 at line 777
go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/rawnode.go in go.etcd.io/raft/v3.(*RawNode).Ready at line 132
go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/rawnode.go in go.etcd.io/raft/v3.(*RawNode).readyWithoutAccept at line 144
go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/log.go in go.etcd.io/raft/v3.(*raftLog).nextCommittedEnts at line 235
go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/log.go in go.etcd.io/raft/v3.(*raftLog).slice at line 507
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 470
pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go in pkg/kv/kvserver.(*raftScheduler).Start.func2 at line 302
pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go in pkg/kv/kvserver.(*raftSchedulerShard).worker at line 395
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).processReady at line 646
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).handleRaftReady at line 725
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked at line 769
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).withRaftGroupLocked at line 1995
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).withRaftGroupLocked.func1 at line 1994
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked.func2 at line 777
go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/rawnode.go in go.etcd.io/raft/v3.(*RawNode).Ready at line 132
go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/rawnode.go in go.etcd.io/raft/v3.(*RawNode).readyWithoutAccept at line 144
go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/log.go in go.etcd.io/raft/v3.(*raftLog).nextCommittedEnts at line 235
go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/log.go in go.etcd.io/raft/v3.(*raftLog).slice at line 501
pkg/kv/kvserver/pkg/kv/kvserver/replica_raftstorage.go in pkg/kv/kvserver.(*replicaRaftStorage).Entries at line 87
pkg/kv/kvserver/logstore/logstore.go in pkg/kv/kvserver/logstore.LoadEntries at line 573
pkg/kv/kvserver/raftlog/iterator.go in pkg/kv/kvserver/raftlog.Visit at line 145
pkg/kv/kvserver/logstore/logstore.go in pkg/kv/kvserver/logstore.LoadEntries.func1 at line 546
pkg/kv/kvserver/logstore/sideload.go in pkg/kv/kvserver/logstore.MaybeInlineSideloadedRaftCommand at line 209
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
GOROOT/src/runtime/proc.go in runtime.main at line 233
GOROOT/src/runtime/proc.go in runtime.doInit at line 6326
GOROOT/src/runtime/proc.go in runtime.doInit at line 6326
GOROOT/src/runtime/proc.go in runtime.doInit at line 6326
GOROOT/src/runtime/proc.go in runtime.doInit at line 6326
GOROOT/src/runtime/proc.go in runtime.doInit at line 6349
pkg/kv/kvserver/logstore/sideload.go in pkg/kv/kvserver/logstore.init at line 25
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v23.1.11 |
| Go Version | go1.19.10 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.11 |
| Cockroach SHA | 62ad175cbc0e9041d993ea1cc911e07d279671f5 |
| # of CPUs | 2 |
| # of Goroutines | 204 |

Jira issue: CRDB-32529

**Comment by yuzefovich** [comment]
dup of #113135
