### ISSUE TITLE
Sentry: catch.go:29: runtime error: index out of range [37] with length 16
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/util/errorut...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#112769]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4561822696/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4561822696/?referrer=webhooks_plugin)

Panic Message:

```
catch.go:29: runtime error: index out of range [37] with length 16
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/util/errorutil.ShouldCatch
  | 	github.com/cockroachdb/cockroach/pkg/util/errorutil/catch.go:29
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).Build.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:212
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | runtime.goPanicIndex
  | 	GOROOT/src/runtime/panic.go:113
  | github.com/cockroachdb/cockroach/pkg/sql.(*optTable).Column
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt_catalog.go:1195
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildPartialIndexPredicate.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/partial_index.go:151
  | github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).Replace
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go:23134
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildPartialIndexPredicate.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/partial_index.go:158
  | github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).replaceFiltersExpr
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go:24152
  | github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).Replace
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go:22544
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildPartialIndexPredicate.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/partial_index.go:158
  | github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).Replace
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go:22799
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildPartialIndexPredicate.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/partial_index.go:158
  | github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).Replace
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go:22551
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildPartialIndexPredicate.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/partial_index.go:158
  | github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).Replace
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go:22875
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildPartialIndexPredicate.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/partial_index.go:158
  | github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).replaceScalarListExpr
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go:24236
  | github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).Replace
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go:23477
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildPartialIndexPredicate.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/partial_index.go:158
  | github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).Replace
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go:22969
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildPartialIndexPredicate.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/partial_index.go:158
  | github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).replaceScalarListExpr
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go:24236
  | github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).Replace
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go:22915
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildPartialIndexPredicate.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/partial_index.go:158
  | github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).replaceScalarListExpr
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go:24236
  | github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).Replace
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go:22529
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildPartialIndexPredicate.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/partial_index.go:158
  | github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).Replace
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go:22875
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildPartialIndexPredicate.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/partial_index.go:158
  | github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).Replace
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go:23424
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildPartialIndexPredicate.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/partial_index.go:158
Wraps: (3) runtime error: index out of range [37] with length 16
  | -- cause hidden behind barrier
  | runtime error: index out of range [37] with length 16
  | (1) runtime error: index out of range [37] with length 16
  | Error types: (1) runtime.boundsError
Error types: (1) *assert.withAssertionFailure (2) *withstack.withStack (3) *barriers.barrierErr
-- report composition:
*barriers.barrierErr: masked error: runtime error: index out of range [37] with length 16
catch.go:29: *withstack.withStack (top exception)
*assert.withAssertionFailure
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/opt/optbuilder/partial_index.go#L157-L159](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/opt/optbuilder/partial_index.go#L157-L159)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L23423-L23425](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L23423-L23425)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/opt/optbuilder/partial_index.go#L157-L159](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/opt/optbuilder/partial_index.go#L157-L159)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L22874-L22876](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L22874-L22876)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/opt/optbuilder/partial_index.go#L157-L159](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/opt/optbuilder/partial_index.go#L157-L159)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L22528-L22530](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L22528-L22530)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L24235-L24237](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L24235-L24237)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/opt/optbuilder/partial_index.go#L157-L159](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/opt/optbuilder/partial_index.go#L157-L159)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L22914-L22916](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L22914-L22916)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L24235-L24237](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L24235-L24237)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/opt/optbuilder/partial_index.go#L157-L159](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/opt/optbuilder/partial_index.go#L157-L159)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L22968-L22970](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L22968-L22970)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/opt/optbuilder/partial_index.go#L157-L159](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/opt/optbuilder/partial_index.go#L157-L159)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L23476-L23478](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L23476-L23478)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L24235-L24237](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L24235-L24237)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/opt/optbuilder/partial_index.go#L157-L159](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/opt/optbuilder/partial_index.go#L157-L159)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L22874-L22876](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L22874-L22876)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/opt/optbuilder/partial_index.go#L157-L159](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/opt/optbuilder/partial_index.go#L157-L159)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L22550-L22552](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L22550-L22552)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/opt/optbuilder/partial_index.go#L157-L159](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/opt/optbuilder/partial_index.go#L157-L159)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L22798-L22800](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L22798-L22800)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/opt/optbuilder/partial_index.go#L157-L159](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/opt/optbuilder/partial_index.go#L157-L159)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L22543-L22545](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L22543-L22545)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L24151-L24153](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L24151-L24153)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/opt/optbuilder/partial_index.go#L157-L159](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/opt/optbuilder/partial_index.go#L157-L159)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L23133-L23135](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L23133-L23135)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/opt/optbuilder/partial_index.go#L150-L152](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/opt/optbuilder/partial_index.go#L150-L152)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/opt_catalog.go#L1194-L1196](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/opt_catalog.go#L1194-L1196)
[GOROOT/src/runtime/panic.go#L112-L114](GOROOT/src/runtime/panic.go#L112-L114)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/opt/optbuilder/builder.go#L211-L213](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/opt/optbuilder/builder.go#L211-L213)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/util/errorutil/catch.go#L28-L30](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/util/errorutil/catch.go#L28-L30)
</details>

```
pkg/sql/opt/optbuilder/partial_index.go in pkg/sql/opt/optbuilder.(*Builder).buildPartialIndexPredicate.func2 at line 158
bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go in pkg/sql/opt/norm.(*Factory).Replace at line 23424
pkg/sql/opt/optbuilder/partial_index.go in pkg/sql/opt/optbuilder.(*Builder).buildPartialIndexPredicate.func2 at line 158
bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go in pkg/sql/opt/norm.(*Factory).Replace at line 22875
pkg/sql/opt/optbuilder/partial_index.go in pkg/sql/opt/optbuilder.(*Builder).buildPartialIndexPredicate.func2 at line 158
bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go in pkg/sql/opt/norm.(*Factory).Replace at line 22529
bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go in pkg/sql/opt/norm.(*Factory).replaceScalarListExpr at line 24236
pkg/sql/opt/optbuilder/partial_index.go in pkg/sql/opt/optbuilder.(*Builder).buildPartialIndexPredicate.func2 at line 158
bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go in pkg/sql/opt/norm.(*Factory).Replace at line 22915
bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go in pkg/sql/opt/norm.(*Factory).replaceScalarListExpr at line 24236
pkg/sql/opt/optbuilder/partial_index.go in pkg/sql/opt/optbuilder.(*Builder).buildPartialIndexPredicate.func2 at line 158
bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go in pkg/sql/opt/norm.(*Factory).Replace at line 22969
pkg/sql/opt/optbuilder/partial_index.go in pkg/sql/opt/optbuilder.(*Builder).buildPartialIndexPredicate.func2 at line 158
bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go in pkg/sql/opt/norm.(*Factory).Replace at line 23477
bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go in pkg/sql/opt/norm.(*Factory).replaceScalarListExpr at line 24236
pkg/sql/opt/optbuilder/partial_index.go in pkg/sql/opt/optbuilder.(*Builder).buildPartialIndexPredicate.func2 at line 158
bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go in pkg/sql/opt/norm.(*Factory).Replace at line 22875
pkg/sql/opt/optbuilder/partial_index.go in pkg/sql/opt/optbuilder.(*Builder).buildPartialIndexPredicate.func2 at line 158
bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go in pkg/sql/opt/norm.(*Factory).Replace at line 22551
pkg/sql/opt/optbuilder/partial_index.go in pkg/sql/opt/optbuilder.(*Builder).buildPartialIndexPredicate.func2 at line 158
bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go in pkg/sql/opt/norm.(*Factory).Replace at line 22799
pkg/sql/opt/optbuilder/partial_index.go in pkg/sql/opt/optbuilder.(*Builder).buildPartialIndexPredicate.func2 at line 158
bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go in pkg/sql/opt/norm.(*Factory).Replace at line 22544
bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go in pkg/sql/opt/norm.(*Factory).replaceFiltersExpr at line 24152
pkg/sql/opt/optbuilder/partial_index.go in pkg/sql/opt/optbuilder.(*Builder).buildPartialIndexPredicate.func2 at line 158
bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go in pkg/sql/opt/norm.(*Factory).Replace at line 23134
pkg/sql/opt/optbuilder/partial_index.go in pkg/sql/opt/optbuilder.(*Builder).buildPartialIndexPredicate.func2 at line 151
pkg/sql/opt_catalog.go in pkg/sql.(*optTable).Column at line 1195
GOROOT/src/runtime/panic.go in runtime.goPanicIndex at line 113
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).Build.func1 at line 212
pkg/util/errorutil/catch.go in pkg/util/errorutil.ShouldCatch at line 29
```

### Tags

| Tag | Value |
| --- | --- |
| Command | start-single-node |
| Environment | v23.1.11 |
| Go Version | go1.19.10 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.11 |
| Cockroach SHA | 62ad175cbc0e9041d993ea1cc911e07d279671f5 |
| # of CPUs | 24 |
| # of Goroutines | 507 |

Jira issue: CRDB-32584

**Comment by yuzefovich** [comment]
unactionable
