### ISSUE TITLE
Sentry: format.go:349: no Annotations provided
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
  | 	github.com/cockroachdb/cockroach/p...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#112819]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4563423838/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4563423838/?referrer=webhooks_plugin)

Panic Message:

```
format.go:349: no Annotations provided
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:900
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.NewFmtCtx
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/format.go:349
  | github.com/cockroachdb/cockroach/pkg/sql.formatStmtKeyAsRedactableString
  | 	github.com/cockroachdb/cockroach/pkg/sql/exec_util.go:3634
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).getCommonSQLEventDetails
  | 	github.com/cockroachdb/cockroach/pkg/sql/event_log.go:190
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).logEventsWithOptions
  | 	github.com/cockroachdb/cockroach/pkg/sql/event_log.go:221
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).logOperationalEventsOnlyExternally
  | 	github.com/cockroachdb/cockroach/pkg/sql/exec_log.go:427
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).maybeLogStatementInternal
  | 	github.com/cockroachdb/cockroach/pkg/sql/exec_log.go:403
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).maybeLogStatement
  | 	github.com/cockroachdb/cockroach/pkg/sql/exec_log.go:134
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine.func4.1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1561
  | github.com/cockroachdb/cockroach/pkg/sql.(*cleanupFuncStack).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/prepared_stmt.go:272
  | github.com/cockroachdb/cockroach/pkg/sql.(*portalPauseInfo).cleanupAll
  | 	github.com/cockroachdb/cockroach/pkg/sql/prepared_stmt.go:395
  | github.com/cockroachdb/cockroach/pkg/sql.(*PreparedPortal).close
  | 	github.com/cockroachdb/cockroach/pkg/sql/prepared_stmt.go:245
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).deletePortal
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:577
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execBind
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:385
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2321
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2105
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:902
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:310
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:900
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | [...repeated from below...]
Wraps: (3) assertion failure
Wraps: (4) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.NewFmtCtx
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/format.go:349
  | github.com/cockroachdb/cockroach/pkg/sql.formatStmtKeyAsRedactableString
  | 	github.com/cockroachdb/cockroach/pkg/sql/exec_util.go:3634
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).getCommonSQLEventDetails
  | 	github.com/cockroachdb/cockroach/pkg/sql/event_log.go:190
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).logEventsWithOptions
  | 	github.com/cockroachdb/cockroach/pkg/sql/event_log.go:221
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).logOperationalEventsOnlyExternally
  | 	github.com/cockroachdb/cockroach/pkg/sql/exec_log.go:427
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).maybeLogStatementInternal
  | 	github.com/cockroachdb/cockroach/pkg/sql/exec_log.go:403
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).maybeLogStatement
  | 	github.com/cockroachdb/cockroach/pkg/sql/exec_log.go:134
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine.func4.1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1561
  | github.com/cockroachdb/cockroach/pkg/sql.(*cleanupFuncStack).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/prepared_stmt.go:272
  | github.com/cockroachdb/cockroach/pkg/sql.(*portalPauseInfo).cleanupAll
  | 	github.com/cockroachdb/cockroach/pkg/sql/prepared_stmt.go:395
  | github.com/cockroachdb/cockroach/pkg/sql.(*PreparedPortal).close
  | 	github.com/cockroachdb/cockroach/pkg/sql/prepared_stmt.go:245
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).deletePortal
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:577
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execBind
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:385
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2321
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2105
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:902
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:310
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (5) no Annotations provided
Error types: (1) *withstack.withStack (2) *withstack.withStack (3) *assert.withAssertionFailure (4) *withstack.withStack (5) *errutil.leafError
-- report composition:
*errutil.leafError: no Annotations provided
format.go:349: *withstack.withStack (top exception)
*assert.withAssertionFailure
conn_executor.go:900: *withstack.withStack (1)
conn_executor.go:900: *withstack.withStack (2)
(check the extra data payloads)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/pgwire/conn.go#L309-L311](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/pgwire/conn.go#L309-L311)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L901-L903](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L901-L903)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L2104-L2106](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L2104-L2106)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L2320-L2322](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L2320-L2322)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor_prepare.go#L384-L386](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor_prepare.go#L384-L386)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor_prepare.go#L576-L578](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor_prepare.go#L576-L578)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/prepared_stmt.go#L244-L246](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/prepared_stmt.go#L244-L246)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/prepared_stmt.go#L394-L396](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/prepared_stmt.go#L394-L396)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/prepared_stmt.go#L271-L273](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/prepared_stmt.go#L271-L273)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor_exec.go#L1560-L1562](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor_exec.go#L1560-L1562)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/exec_log.go#L133-L135](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/exec_log.go#L133-L135)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/exec_log.go#L402-L404](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/exec_log.go#L402-L404)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/exec_log.go#L426-L428](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/exec_log.go#L426-L428)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/event_log.go#L220-L222](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/event_log.go#L220-L222)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/event_log.go#L189-L191](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/event_log.go#L189-L191)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/exec_util.go#L3633-L3635](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/exec_util.go#L3633-L3635)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/sem/tree/format.go#L348-L350](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/sem/tree/format.go#L348-L350)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L899-L901](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L899-L901)
[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/pgwire/conn.go#L309-L311](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/pgwire/conn.go#L309-L311)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L901-L903](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L901-L903)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L2104-L2106](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L2104-L2106)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L2320-L2322](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L2320-L2322)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor_prepare.go#L384-L386](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor_prepare.go#L384-L386)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor_prepare.go#L576-L578](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor_prepare.go#L576-L578)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/prepared_stmt.go#L244-L246](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/prepared_stmt.go#L244-L246)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/prepared_stmt.go#L394-L396](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/prepared_stmt.go#L394-L396)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/prepared_stmt.go#L271-L273](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/prepared_stmt.go#L271-L273)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor_exec.go#L1560-L1562](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor_exec.go#L1560-L1562)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/exec_log.go#L133-L135](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/exec_log.go#L133-L135)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/exec_log.go#L402-L404](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/exec_log.go#L402-L404)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/exec_log.go#L426-L428](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/exec_log.go#L426-L428)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/event_log.go#L220-L222](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/event_log.go#L220-L222)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/event_log.go#L189-L191](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/event_log.go#L189-L191)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/exec_util.go#L3633-L3635](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/exec_util.go#L3633-L3635)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/sem/tree/format.go#L348-L350](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/sem/tree/format.go#L348-L350)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L899-L901](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L899-L901)
[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/pgwire/conn.go#L309-L311](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/pgwire/conn.go#L309-L311)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L901-L903](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L901-L903)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L2104-L2106](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L2104-L2106)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L2320-L2322](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L2320-L2322)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor_prepare.go#L384-L386](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor_prepare.go#L384-L386)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor_prepare.go#L576-L578](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor_prepare.go#L576-L578)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/prepared_stmt.go#L244-L246](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/prepared_stmt.go#L244-L246)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/prepared_stmt.go#L394-L396](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/prepared_stmt.go#L394-L396)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/prepared_stmt.go#L271-L273](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/prepared_stmt.go#L271-L273)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor_exec.go#L1560-L1562](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor_exec.go#L1560-L1562)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/exec_log.go#L133-L135](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/exec_log.go#L133-L135)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/exec_log.go#L402-L404](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/exec_log.go#L402-L404)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/exec_log.go#L426-L428](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/exec_log.go#L426-L428)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/event_log.go#L220-L222](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/event_log.go#L220-L222)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/event_log.go#L189-L191](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/event_log.go#L189-L191)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/exec_util.go#L3633-L3635](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/exec_util.go#L3633-L3635)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/sem/tree/format.go#L348-L350](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/sem/tree/format.go#L348-L350)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommandsAsync.func1 at line 310
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 902
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 2105
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 2321
pkg/sql/conn_executor_prepare.go in pkg/sql.(*connExecutor).execBind at line 385
pkg/sql/conn_executor_prepare.go in pkg/sql.(*connExecutor).deletePortal at line 577
pkg/sql/prepared_stmt.go in pkg/sql.(*PreparedPortal).close at line 245
pkg/sql/prepared_stmt.go in pkg/sql.(*portalPauseInfo).cleanupAll at line 395
pkg/sql/prepared_stmt.go in pkg/sql.(*cleanupFuncStack).run at line 272
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchToExecutionEngine.func4.1 at line 1561
pkg/sql/exec_log.go in pkg/sql.(*planner).maybeLogStatement at line 134
pkg/sql/exec_log.go in pkg/sql.(*planner).maybeLogStatementInternal at line 403
pkg/sql/exec_log.go in pkg/sql.(*planner).logOperationalEventsOnlyExternally at line 427
pkg/sql/event_log.go in pkg/sql.(*planner).logEventsWithOptions at line 221
pkg/sql/event_log.go in pkg/sql.(*planner).getCommonSQLEventDetails at line 190
pkg/sql/exec_util.go in pkg/sql.formatStmtKeyAsRedactableString at line 3634
pkg/sql/sem/tree/format.go in pkg/sql/sem/tree.NewFmtCtx at line 349
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn.func1 at line 900
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommandsAsync.func1 at line 310
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 902
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 2105
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 2321
pkg/sql/conn_executor_prepare.go in pkg/sql.(*connExecutor).execBind at line 385
pkg/sql/conn_executor_prepare.go in pkg/sql.(*connExecutor).deletePortal at line 577
pkg/sql/prepared_stmt.go in pkg/sql.(*PreparedPortal).close at line 245
pkg/sql/prepared_stmt.go in pkg/sql.(*portalPauseInfo).cleanupAll at line 395
pkg/sql/prepared_stmt.go in pkg/sql.(*cleanupFuncStack).run at line 272
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchToExecutionEngine.func4.1 at line 1561
pkg/sql/exec_log.go in pkg/sql.(*planner).maybeLogStatement at line 134
pkg/sql/exec_log.go in pkg/sql.(*planner).maybeLogStatementInternal at line 403
pkg/sql/exec_log.go in pkg/sql.(*planner).logOperationalEventsOnlyExternally at line 427
pkg/sql/event_log.go in pkg/sql.(*planner).logEventsWithOptions at line 221
pkg/sql/event_log.go in pkg/sql.(*planner).getCommonSQLEventDetails at line 190
pkg/sql/exec_util.go in pkg/sql.formatStmtKeyAsRedactableString at line 3634
pkg/sql/sem/tree/format.go in pkg/sql/sem/tree.NewFmtCtx at line 349
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn.func1 at line 900
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommandsAsync.func1 at line 310
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 902
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 2105
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 2321
pkg/sql/conn_executor_prepare.go in pkg/sql.(*connExecutor).execBind at line 385
pkg/sql/conn_executor_prepare.go in pkg/sql.(*connExecutor).deletePortal at line 577
pkg/sql/prepared_stmt.go in pkg/sql.(*PreparedPortal).close at line 245
pkg/sql/prepared_stmt.go in pkg/sql.(*portalPauseInfo).cleanupAll at line 395
pkg/sql/prepared_stmt.go in pkg/sql.(*cleanupFuncStack).run at line 272
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchToExecutionEngine.func4.1 at line 1561
pkg/sql/exec_log.go in pkg/sql.(*planner).maybeLogStatement at line 134
pkg/sql/exec_log.go in pkg/sql.(*planner).maybeLogStatementInternal at line 403
pkg/sql/exec_log.go in pkg/sql.(*planner).logOperationalEventsOnlyExternally at line 427
pkg/sql/event_log.go in pkg/sql.(*planner).logEventsWithOptions at line 221
pkg/sql/event_log.go in pkg/sql.(*planner).getCommonSQLEventDetails at line 190
pkg/sql/exec_util.go in pkg/sql.formatStmtKeyAsRedactableString at line 3634
pkg/sql/sem/tree/format.go in pkg/sql/sem/tree.NewFmtCtx at line 349
```

### Tags

| Tag | Value |
| --- | --- |
| Command | mt start-sql |
| Environment | v23.1.11 |
| Go Version | go1.19.10 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.11 |
| Cockroach SHA | 62ad175cbc0e9041d993ea1cc911e07d279671f5 |
| # of CPUs | 32 |
| # of Goroutines | 373 |

Jira issue: CRDB-32614

**Comment by yuzefovich** [comment]
dup of #112058
