### ISSUE TITLE
Sentry: error.go:89: unexpected error from the vectorized engine: RangeIterator failed to seek to /Table/123/11/×/×: failed to connect to n25 at ×: ×: ×
(1) assertion failure
Wraps: (2) attached ...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#112892]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4568612316/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4568612316/?referrer=webhooks_plugin)

Panic Message:

```
error.go:89: unexpected error from the vectorized engine: RangeIterator failed to seek to /Table/123/11/×/×: failed to connect to n25 at ×: ×: ×
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:89
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.InternalError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:195
  | github.com/cockroachdb/cockroach/pkg/sql/colfetcher.(*ColIndexJoin).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colfetcher/index_join.go:222
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils.(*CancelChecker).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils/cancel_checker.go:59
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).nextAdapter
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:252
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:256
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:299
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:320
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:757
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1764
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1472
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1599
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1202
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:694
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:131
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2440
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:130
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2129
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2133
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2054
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:882
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:769
  | runtime.goexit
  | 	src/runtime/asm_arm64.s:1172
Wraps: (3) unexpected error from the vectorized engine
Wraps: (4) RangeIterator failed to seek to /Table/123/11/×/×: failed to connect to n25 at ×: ×: ×
  | -- cause hidden behind barrier
  | RangeIterator failed to seek to /Table/123/11/×/×: failed to connect to n25 at ×: ×: ×
  | (1) attached stack trace
  |   -- stack trace:
  |   | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*RangeIterator).Seek
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/range_iter.go:227
  |   | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvstreamer.(*Streamer).Enqueue
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvstreamer/streamer.go:544
  |   | github.com/cockroachdb/cockroach/pkg/sql/row.(*txnKVStreamer).SetupNextFetch
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/row/kv_batch_streamer.go:94
  |   | github.com/cockroachdb/cockroach/pkg/sql/row.(*KVFetcher).SetupNextFetch
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/row/kv_fetcher.go:295
  |   | github.com/cockroachdb/cockroach/pkg/sql/colfetcher.(*cFetcher).StartScan
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colfetcher/cfetcher.go:514
  |   | github.com/cockroachdb/cockroach/pkg/sql/colfetcher.(*ColIndexJoin).Next
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colfetcher/index_join.go:215
  |   | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils.(*CancelChecker).Next
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils/cancel_checker.go:59
  |   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).nextAdapter
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:252
  |   | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  |   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).next
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:256
  |   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).Run
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:299
  |   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Run
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:320
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:757
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1764
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1472
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1599
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1202
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:694
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:131
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2440
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:130
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2129
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2133
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2054
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:882
  |   | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsy...
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_arm64.s#L1171-L1173](src/runtime/asm_arm64.s#L1171-L1173)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/pgwire/conn.go#L768-L770](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/pgwire/conn.go#L768-L770)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor.go#L881-L883](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor.go#L881-L883)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor.go#L2053-L2055](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor.go#L2053-L2055)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor.go#L2132-L2134](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor.go#L2132-L2134)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor.go#L2128-L2130](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor.go#L2128-L2130)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor_exec.go#L129-L131](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor_exec.go#L129-L131)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor_exec.go#L2439-L2441](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor_exec.go#L2439-L2441)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor_exec.go#L130-L132](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor_exec.go#L130-L132)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor_exec.go#L693-L695](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor_exec.go#L693-L695)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor_exec.go#L1201-L1203](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor_exec.go#L1201-L1203)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor_exec.go#L1598-L1600](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/conn_executor_exec.go#L1598-L1600)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/distsql_running.go#L1471-L1473](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/distsql_running.go#L1471-L1473)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/distsql_running.go#L1763-L1765](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/distsql_running.go#L1763-L1765)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/distsql_running.go#L756-L758](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/distsql_running.go#L756-L758)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colflow/vectorized_flow.go#L319-L321](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colflow/vectorized_flow.go#L319-L321)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colflow/flow_coordinator.go#L298-L300](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colflow/flow_coordinator.go#L298-L300)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colflow/flow_coordinator.go#L255-L257](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colflow/flow_coordinator.go#L255-L257)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colflow/flow_coordinator.go#L251-L253](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colflow/flow_coordinator.go#L251-L253)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexec/colexecutils/cancel_checker.go#L58-L60](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexec/colexecutils/cancel_checker.go#L58-L60)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colfetcher/index_join.go#L221-L223](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colfetcher/index_join.go#L221-L223)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexecerror/error.go#L194-L196](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexecerror/error.go#L194-L196)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
[https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexecerror/error.go#L88-L90](https://github.com/cockroachdb/cockroach/blob/af6752b2faf39115fd322e9db76421e71b76507d/pkg/sql/colexecerror/error.go#L88-L90)
</details>

```
src/runtime/asm_arm64.s in runtime.goexit at line 1172
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommandsAsync.func1 at line 769
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 882
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 2054
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 2133
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd.func1 at line 2129
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 130
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithProfiling at line 2440
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt.func1 at line 131
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 694
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchToExecutionEngine at line 1202
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithDistSQLEngine at line 1599
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRunAll at line 1472
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRun at line 1764
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).Run at line 757
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlow).Run at line 320
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).Run at line 299
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).next at line 256
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).nextAdapter at line 252
pkg/sql/colexec/colexecutils/cancel_checker.go in pkg/sql/colexec/colexecutils.(*CancelChecker).Next at line 59
pkg/sql/colfetcher/index_join.go in pkg/sql/colfetcher.(*ColIndexJoin).Next at line 222
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.InternalError at line 195
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1 at line 89
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v22.2.14 |
| Go Version | go1.19.6 |
| Platform | linux arm64 |
| Distribution | CCL |
| Cockroach Release | v22.2.14 |
| Cockroach SHA | af6752b2faf39115fd322e9db76421e71b76507d |
| # of CPUs | 4 |
| # of Goroutines | 378 |

Jira issue: CRDB-32666

**Comment by yuzefovich** [comment]
unactionable
