### ISSUE TITLE
upgrades: audit that V23_2_GrantExecuteToPublic handles restoration

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#112866]
As part #112842, we are doing an audit of all 23.2 upgrades to see if they alter persisted state that can also be written by restore. The upgrade associated V23_2_GrantExecuteToPublic appears to manipulate descriptors. Does the manipulation it performs need to be performed on restored descriptors as well?

Jira issue: CRDB-32650

**Comment by mgartner** [comment]
> Does the manipulation it performs need to be performed on restored descriptors as well?

Yes, I think so. Thanks for pointing this out.
