### ISSUE TITLE
Metrics 'forward' button does not go to the latest point in time

### ISSUE THREAD

**Issue by smcvey** [cockroachdb/cockroach#112847]
**Describe the problem**

In some circumstances, clicking the 'Forward' arrow button on the Metrics page doesn't take the user to the same point as the 'Now' button would.

**To Reproduce**

1. Load up the Metrics page, stay on the default 10 minute interval.
2. Click the back button several times.
3. Wait a few minutes.
4. Attempt to click the forward button as many times as allowed.
5. Click the 'Now' button.  You'll see that the graphs seen by clicking the forward button are not the same as 'Now' (because clicking Forward doesn't go all the way forward).

**Expected behavior**
You should be able to click forward to get to the latest graphs.

**Additional data / screenshots**

These are the back and forward buttons as mentioned above:

![image](https://github.com/cockroachdb/cockroach/assets/28270695/0d5501fd-e30b-4ed0-99a8-8459426ed288)

This is what happens after clicking Forward as much as possible:

![image (1)](https://github.com/cockroachdb/cockroach/assets/28270695/9bbf09d2-f069-4a95-bbb9-b03b5a741c9e)

And then after clicking Now, note the graphs change (they should've been the same):

![image (2)](https://github.com/cockroachdb/cockroach/assets/28270695/bb8593ee-8628-4474-8813-7b1219a3eac6)

**Environment:**
 - CockroachDB version: v23.2

**Additional context**
Cosmetic/Usability.

Jira issue: CRDB-32638

**Comment by kevin-v-ngo** [comment]
Hi @smcvey, can you help us understand why was this tagged as a release blocker? TIA

**Comment by smcvey** [comment]
Hi @kevin-v-ngo.  I'm following the process described in https://docs.google.com/document/d/15zIOxUb0G_cB6gbl4Q8gC3lM6yyt_qq5r7PBsPuiq7I/edit which determines that any issues raised are marked as release blocker.  The author of the process is William Kulju, so he should be able to provide you with more insight.

**Comment by williamkulju** [comment]
@kevin-v-ngo More context: We're opening all issues as release blockers by default (to be consistent with what test-eng does when they open an issue for a failing test). However, it is up to the discretion of triage teams to remove that tag if they deem appropriate.
