### ISSUE TITLE
c2c: TestStreamPartition/stream-table-cursor-error timed out due to mux rangefeed shutdown 

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#112966]
On an unrelated pr on 23.2, I saw this CI failure [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=12320228&buildTypeId=Cockroach_BazelEssentialCi).

The test timed out while waiting to observe an error returned by the producer side event stream:
https://github.com/cockroachdb/cockroach/blob/7d9dcd80896150354da7b74aafd13efd662f18f6/pkg/ccl/streamingccl/streamproducer/replication_stream_test.go#L397

The event stream failed to close at this select statement:
https://github.com/cockroachdb/cockroach/blob/2e0f18b45ff13ddd94f6ac613c5c0f39ed2a9729/pkg/ccl/streamingccl/streamproducer/event_stream.go#L230

Given that the test is expecting an error, we should expect the rangefeed to encounter an error and shut down the event stream via
https://github.com/cockroachdb/cockroach/blob/2e0f18b45ff13ddd94f6ac613c5c0f39ed2a9729/pkg/ccl/streamingccl/streamproducer/event_stream.go#L117
- in other words, when the rangefeed returns, an error sent to the error channel, allowing `Next()` to return and allowing the event stream to shut down.

But, it seems a mux rangefeed failed to close for 14 mins according to this stack, so I think this a mux rangefeed shutdown bug:
```
goroutine 20648 [semacquire, 14 minutes]:
sync.runtime_Semacquire(0xc000306680?)
	GOROOT/src/runtime/sema.go:62 +0x27
sync.(*WaitGroup).Wait(0xc004788001?)
	GOROOT/src/sync/waitgroup.go:116 +0x4b
golang.org/x/sync/errgroup.(*Group).Wait(0xc0055e9740)
	golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:53 +0x27
github.com/cockroachdb/cockroach/pkg/util/ctxgroup.Group.Wait({0xc0055e9740?, {0x7a4f258?, 0xc00609d540?}})
	github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:144 +0x4a
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.muxRangeFeed({0x7a4f300, 0xc008d2ab40}, {0x1, 0x1, 0x0, 0x0, {0x0, 0x0, 0x0, 0x0}}, ...)
	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go:101 +0x490
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).RangeFeedSpans(0xc004bb3080, {0x7a4f258, 0xc00609c0a0}, {0xc0055e96c0?, 0x1, 0x1}, 0xc00710f080, {0xc002b231a0, 0x2, 0x2})
	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go:226 +0x3b8
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).RangeFeed(0x5830360?, {0x7a4f258, 0xc00609c0a0}, {0xc0089f2e40, 0x1, 0x2?}, {0xcda83c?, 0x97555f0?, 0xc0?}, 0xc00710f080, ...)
	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go:177 +0x29a
github.com/cockroachdb/cockroach/pkg/kv/kvclient/rangefeed.(*dbAdapter).RangeFeed(0x1ff7800?, {0x7a4f258?, 0xc00609c0a0?}, {0xc0089f2e40?, 0xc002651fd0?, 0x1242b86?}, {0x7a4f300?, 0x89f3050?, 0xc0?}, 0xc00710f080, ...)
	github.com/cockroachdb/cockroach/pkg/kv/kvclient/rangefeed/db_adapter.go:79 +0x65
github.com/cockroachdb/cockroach/pkg/kv/kvclient/rangefeed.(*RangeFeed).run.func1({0x7a4f258?, 0xc00609c0a0?})
	github.com/cockroachdb/cockroach/pkg/kv/kvclient/rangefeed/rangefeed.go:310 +0xb2
github.com/cockroachdb/cockroach/pkg/util/ctxgroup.Group.GoCtx.func1()
	github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:168 +0x25
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:72 +0xa5
```

Jira issue: CRDB-32699

**Comment by stevendanna** [comment]
@msbutler Before spending too much time on this. Note that we deleted this test on master because it is pretty fundamentally flawed. You might have hit: https://github.com/cockroachdb/cockroach/issues/111146#issuecomment-1736079680

**Comment by msbutler** [comment]
likely a test infra flake
