### ISSUE TITLE
Slack link in README.md invalid

### ISSUE THREAD

**Issue by sat-h** [cockroachdb/cockroach#113085]
**Describe the problem**

The Slack link found in two locations within README.md is invalid. If I get a correct link, I would be happy to fix it.

https://github.com/cockroachdb/cockroach/blob/68ad71d1b8fd96261a37163e31f2caa72a5ae387/README.md?plain=1#L72C33-L72C60

https://github.com/cockroachdb/cockroach/blob/68ad71d1b8fd96261a37163e31f2caa72a5ae387/README.md?plain=1#L87C190-L87C217

Jira issue: CRDB-32742

**Comment by ZhouXing19** [comment]
Hello @sat-h, thanks for reporting this issue.
Could you elaborate on the issue you saw with this `https://go.crdb.dev/p/slack` link? From my end, opening it with the google chrome browser redirects me to the correct slack channel, but wondering there's any missed use case that we can improve.

**Comment by sat-h** [comment]
Hi @ZhouXing19, thank you for your response. I  have attached a screenshot of the error I get when clicking on the link on chrome on android. 

![Screenshot_20231030-182244.png](https://github.com/cockroachdb/cockroach/assets/66668841/8de6d776-21b1-4b17-92af-92be2763ffc1)

**Comment by maryliag** [comment]
Hi @sat-h, the link was correct, but the expiration date needed to be updated, so we did that and no changes on the code are required!
Thank you for bringing this to us! It should be working now!

**Comment by sat-h** [comment]
@maryliag Good to know it's working now. I've joined the channel.
