### ISSUE TITLE
ui: db console metrics page ‘now’ button breaks when zoomed-in

### ISSUE THREAD

**Issue by williamkulju** [cockroachdb/cockroach#113091]
Per @sean- Repro steps are:
- Went back in time on a 1d window
- zoomed in to a specific window of time
- Clicked on Now and the data doesn't change.  Every time I click on Now, the URL changes but the data visualizations don't.

See screencaps for details

![image](https://github.com/cockroachdb/cockroach/assets/110843721/e1d0bee3-a3a0-4760-90eb-fb20deeef0a7)
![image](https://github.com/cockroachdb/cockroach/assets/110843721/977ada43-2f82-454c-82f5-ece2ac2a9ccd)
![image](https://github.com/cockroachdb/cockroach/assets/110843721/1cdadbc0-3812-40e6-832c-9ce1dc7c9579)

Jira issue: CRDB-33063

**Comment by koorosh** [comment]
To clarify expected behavior, when user clicks "Now" button, it is expected:
- to change timewindow with duration the same as previously selected timewindow;
- it will be fixed time window that doesn't update to include latest updates;
