### ISSUE TITLE
Sentry: panic.go:884: node unavailable; try another peer
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | github.com/cockroachdb/cockroach/pkg/in...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#113182]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4578197095/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4578197095/?referrer=webhooks_plugin)

Panic Message:

```
panic.go:884: node unavailable; try another peer
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | github.com/cockroachdb/cockroach/pkg/internal/client/requestbatcher.New
  | 	github.com/cockroachdb/cockroach/pkg/internal/client/requestbatcher/batcher.go:217
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/intentresolver.New
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/intentresolver/intent_resolver.go:232
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).Start
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store.go:1915
  | github.com/cockroachdb/cockroach/pkg/server.(*Node).start
  | 	github.com/cockroachdb/cockroach/pkg/server/node.go:513
  | github.com/cockroachdb/cockroach/pkg/server.(*Server).PreStart
  | 	github.com/cockroachdb/cockroach/pkg/server/server.go:1699
  | github.com/cockroachdb/cockroach/pkg/cli.createAndStartServerAsync.func1.2
  | 	github.com/cockroachdb/cockroach/pkg/cli/start.go:810
  | github.com/cockroachdb/cockroach/pkg/cli.createAndStartServerAsync.func1
  | 	github.com/cockroachdb/cockroach/pkg/cli/start.go:858
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (2) node unavailable; try another peer
Error types: (1) *withstack.withStack (2) *kvpb.NodeUnavailableError
-- report composition:
*kvpb.NodeUnavailableError
panic.go:884: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/cli/start.go#L857-L859](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/cli/start.go#L857-L859)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/cli/start.go#L809-L811](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/cli/start.go#L809-L811)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/server/server.go#L1698-L1700](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/server/server.go#L1698-L1700)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/server/node.go#L512-L514](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/server/node.go#L512-L514)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/pkg/kv/kvserver/store.go#L1914-L1916](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/pkg/kv/kvserver/store.go#L1914-L1916)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/intentresolver/intent_resolver.go#L231-L233](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/kv/kvserver/intentresolver/intent_resolver.go#L231-L233)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/internal/client/requestbatcher/batcher.go#L216-L218](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/internal/client/requestbatcher/batcher.go#L216-L218)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/cli/start.go in pkg/cli.createAndStartServerAsync.func1 at line 858
pkg/cli/start.go in pkg/cli.createAndStartServerAsync.func1.2 at line 810
pkg/server/server.go in pkg/server.(*Server).PreStart at line 1699
pkg/server/node.go in pkg/server.(*Node).start at line 513
pkg/kv/kvserver/pkg/kv/kvserver/store.go in pkg/kv/kvserver.(*Store).Start at line 1915
pkg/kv/kvserver/intentresolver/intent_resolver.go in pkg/kv/kvserver/intentresolver.New at line 232
pkg/internal/client/requestbatcher/batcher.go in pkg/internal/client/requestbatcher.New at line 217
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v23.1.8 |
| Go Version | go1.19.10 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.8 |
| Cockroach SHA | 2c1d4afd2c2de091a00a4dba4392ceeaf8504a95 |
| # of CPUs | 4 |
| # of Goroutines | 130 |

Jira issue: CRDB-32789

**Comment by yuzefovich** [comment]
unactionable
