### ISSUE TITLE
storage: MVCCClearTimeRange doesn't clear replicated locks

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#113116]
`MVCCClearTimeRange` goes through effort to return a `LockConflictError` if it finds intents in its time range, but not below or above the range. It currently ignores other forms of replicated locks. This does not seem great, as it risks stranding locks on keys without values.

What should we do here? The easiest approach would be to add a `ScanLocks` at the top of `MVCCClearTimeRange` and return a `LockConflictError` if there are any locks/intents in the key span, regardless of lock strength. This will allow the locks/intents to be resolved. It's the same approach we take for most other bulk KV operations like `ClearRange` and `AddSSTable`. However, this would undermine the time-range filtering that `MVCCClearTimeRange` is currently doing for intents. Is that ok? Is it important that `MVCCClearTimeRange` not disrupt intents at earlier or later timestamps?

Relevant TODO:
https://github.com/cockroachdb/cockroach/blob/42a22e69788a22851fc09fc57a20dcbf63d00a75/pkg/storage/mvcc_stats_test.go#L1772-L1773

cc. @dt @erikgrinaker 

Jira issue: CRDB-32752

**Comment by erikgrinaker** [comment]
I don't know the motivation for the historic behavior, but currently the only user of `MVCCClearTimeRange` is C2C replication cutover, and the target cluster can't have any intents by definition (we don't propagate them across rangefeeds), so we're free to change the semantics here.

Doing a `ScanLocks` seems reasonable to me. That would also allow us to omit the intent interleaving iterator (if we add an option for it to `NewMVCCIncrementalIterator`), which should provide a nice speedup. @stevendanna and @msbutler are currently looking to optimize `RevertRange` performance, so I'm sure they'd appreciate this.

**Comment by stevendanna** [comment]
Another use we'll have sometime soon is something like `crdb_internal.revert_tenant_to_timestamp`.  However, even in this case I believe are eventual idea will be that the tenant span needs to be "offline" before we allow the user to use it. So, I can't see why we would care about leaving intents undisturbed.

**Comment by nicktrav** [comment]
I talked to @nvanbenschoten about the ownership of this - this going to be addressed by KV. Updating labels and boards to reflect.
