### ISSUE TITLE
sql: investigate possible planning time increase after changing the primary index

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#113180]
In https://github.com/cockroachlabs/support/issues/2675, a customer reported the following:
- Create table and primary index
- Change primary index, preserving the old as a unique index
- Observe query planning time increase overtime (not immediately after any of these schema changes)
- Drop original index and observe planning time decrease immediately

We should investigate whether we can reproduce it ourselves and the reason for why this occurs.

Jira issue: CRDB-32787

**Comment by mgartner** [comment]
On my M1 Mac I noticed no planning time difference with a simple table and query:

```sql
CREATE TABLE t (
  k INT PRIMARY KEY,
  a INT NOT NULL,
  b INT,
  c INT,
  d INT,
  e INT,
  f INT,
  UNIQUE INDEX (a),
  INDEX (b),
  INDEX (c),
  INDEX (f, e, a) STORING (b)
);

EXPLAIN ANALYZE
SELECT * FROM t
WHERE a IN (5, 10, 20) AND b > 0 AND c > 0;

ALTER TABLE t ALTER PRIMARY KEY USING COLUMNS (a);

EXPLAIN ANALYZE
SELECT * FROM t
WHERE a IN (5, 10, 20) AND b > 0 AND c > 0;

DROP INDEX t_k_key;

EXPLAIN ANALYZE
SELECT * FROM t
WHERE a IN (5, 10, 20) AND b > 0 AND c > 0;
```

**Comment by yuzefovich** [comment]
On the [zendesk](https://cockroachdb.zendesk.com/agent/tickets/18996) ticket the customer hypothesized that it might have to do something with table statistics. They also mentioned "dropping [the index[ decreased the latency, but creating the index didn't immediately increase latency". It might be worth reading through that ticket to gain more context. Perhaps we should just talk directly to the customer / interact directly with their cluster (with their permission) given that they are in CC.

**Comment by mgartner** [comment]
Let's try to reproduction in earnest once more to try to get to the bottom of this.

**Comment by mgartner** [comment]
Closing this - not a top priority.
