### ISSUE TITLE
Sentry: txn_coord_sender_savepoints.go:190: operation invalid for finalized txns
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/kv/kvc...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#113154]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4577161775/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4577161775/?referrer=webhooks_plugin)

Panic Message:

```
txn_coord_sender_savepoints.go:190: operation invalid for finalized txns
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*TxnCoordSender).assertNotFinalized
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_coord_sender_savepoints.go:190
  | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*TxnCoordSender).RollbackToSavepoint
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_coord_sender_savepoints.go:103
  | github.com/cockroachdb/cockroach/pkg/kv.(*Txn).RollbackToSavepoint
  | 	github.com/cockroachdb/cockroach/pkg/kv/txn.go:1559
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execRollbackToSavepointInAbortedState
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_savepoints.go:287
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInAbortedState
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1717
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:138
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1920
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1924
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1846
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:828
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:728
  | runtime.goexit
  | 	src/runtime/asm_amd64.s:1594
Wraps: (3) operation invalid for finalized txns
Error types: (1) *assert.withAssertionFailure (2) *withstack.withStack (3) *errutil.leafError
-- report composition:
*errutil.leafError: operation invalid for finalized txns
txn_coord_sender_savepoints.go:190: *withstack.withStack (top exception)
*assert.withAssertionFailure
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_amd64.s#L1593-L1595](src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/pgwire/conn.go#L727-L729](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/pgwire/conn.go#L727-L729)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/conn_executor.go#L827-L829](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/conn_executor.go#L827-L829)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/conn_executor.go#L1845-L1847](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/conn_executor.go#L1845-L1847)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/conn_executor.go#L1923-L1925](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/conn_executor.go#L1923-L1925)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/conn_executor.go#L1919-L1921](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/conn_executor.go#L1919-L1921)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/conn_executor_exec.go#L137-L139](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/conn_executor_exec.go#L137-L139)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/conn_executor_exec.go#L1716-L1718](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/conn_executor_exec.go#L1716-L1718)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/conn_executor_savepoints.go#L286-L288](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/sql/conn_executor_savepoints.go#L286-L288)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/kv/txn.go#L1558-L1560](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/kv/txn.go#L1558-L1560)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/kv/kvclient/kvcoord/txn_coord_sender_savepoints.go#L102-L104](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/kv/kvclient/kvcoord/txn_coord_sender_savepoints.go#L102-L104)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/kv/kvclient/kvcoord/txn_coord_sender_savepoints.go#L189-L191](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/kv/kvclient/kvcoord/txn_coord_sender_savepoints.go#L189-L191)
</details>

```
src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommandsAsync.func1 at line 728
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 828
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 1846
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 1924
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd.func1 at line 1920
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 138
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInAbortedState at line 1717
pkg/sql/conn_executor_savepoints.go in pkg/sql.(*connExecutor).execRollbackToSavepointInAbortedState at line 287
pkg/kv/txn.go in pkg/kv.(*Txn).RollbackToSavepoint at line 1559
pkg/kv/kvclient/kvcoord/txn_coord_sender_savepoints.go in pkg/kv/kvclient/kvcoord.(*TxnCoordSender).RollbackToSavepoint at line 103
pkg/kv/kvclient/kvcoord/txn_coord_sender_savepoints.go in pkg/kv/kvclient/kvcoord.(*TxnCoordSender).assertNotFinalized at line 190
```

### Tags

| Tag | Value |
| --- | --- |
| Command | start-single-node |
| Environment | v22.2.0 |
| Go Version | go1.19.1 |
| Platform | darwin amd64 |
| Distribution | CCL |
| Cockroach Release | v22.2.0 |
| Cockroach SHA | 77667a1b0101cd323090011f50cf910aaa933654 |
| # of CPUs | 16 |
| # of Goroutines | 501 |

Jira issue: CRDB-32777

**Comment by yuzefovich** [comment]
dup of #93905
