### ISSUE TITLE
bootstrap: some system tables don't inherit constraints/preferences from system database

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#113296]
The following tables don't inherit constraints and lease preferences from the system database zone config by default:

* `replication_constraint_stats `
* `replication_stats`
* `tenant_usage`

This is inconvenient since users must explicitly set constraints and lease preferences for these specific tables in addition to the system zone.

This is likely because these default zone configs are not created via `NewZoneConfig` (which enables inheritance by default), nor derived from the default system zone configs, but instantiated directly with inheritance defaulting to `false`:

https://github.com/cockroachdb/cockroach/blob/a87f0c71ab05a1569641744cb687e8c913d46f1b/pkg/sql/catalog/bootstrap/metadata.go#L541-L550

The tell-tale sign is that `SHOW ZONE CONFIGURATIONS` will show explicit empty constraints/preferences for these tables, but not for other system tables -- compare e.g.:

```
ALTER TABLE system.public.replication_stats CONFIGURE ZONE USING
    gc.ttlseconds = 600,
    constraints = '[]',
    lease_preferences = '[]';


ALTER TABLE system.public.statement_statistics CONFIGURE ZONE USING
    gc.ttlseconds = 3600;
```

We'll likely need to both fix the initial creation to inherit, and also add a migration to fix these in existing clusters.

---

Addendum 2024-02-16: It would also be nice while we are cleaning all this up to add a migration to lower the gc.ttl of `system.lease` as well. See [this thread](https://cockroachlabs.slack.com/archives/C04N0AS14CT/p1708104269274429?thread_ts=1708103486.280399&cid=C04N0AS14CT).

---

Jira issue: CRDB-32857

Epic CRDB-33032

**Comment by rafiss** [comment]
@dikshant should this be a blocker for the 23.2 release? Also, since this needs a migration to fix, we won't be able to backport it to older releases.

**Comment by dikshant** [comment]
Waiting to hear the urgency around needing a GA blocker label on this.

**Comment by dikshant** [comment]
Right now we don't have an urgency to get this in 23.2 so making this a GA blocker is not needed. The customer has a workaround and we can tackle this in 24.1.

Context: https://cockroachlabs.slack.com/archives/C0168LW5THS/p1698684261310569
