### ISSUE TITLE
storage: pebble: internal/arenaskl: slice bounds out of range [:-8]

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#113289]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4586582109/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4586582109/?referrer=webhooks_plugin)

Panic Message:

```
panic.go:884: runtime error: slice bounds out of range [:-8]
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | runtime.goPanicSliceAcap
  | 	GOROOT/src/runtime/panic.go:139
  | github.com/cockroachdb/pebble/internal/arenaskl.(*Skiplist).findSpliceForLevel
  | 	github.com/cockroachdb/pebble/internal/arenaskl/external/com_github_cockroachdb_pebble/internal/arenaskl/skl.go:416
  | github.com/cockroachdb/pebble/internal/arenaskl.(*Iterator).seekForBaseSplice
  | 	github.com/cockroachdb/pebble/internal/arenaskl/external/com_github_cockroachdb_pebble/internal/arenaskl/iterator.go:262
  | github.com/cockroachdb/pebble/internal/arenaskl.(*Iterator).SeekGE
  | 	github.com/cockroachdb/pebble/internal/arenaskl/external/com_github_cockroachdb_pebble/internal/arenaskl/iterator.go:105
  | github.com/cockroachdb/pebble/internal/arenaskl.(*Iterator).SeekPrefixGE
  | 	github.com/cockroachdb/pebble/internal/arenaskl/external/com_github_cockroachdb_pebble/internal/arenaskl/iterator.go:124
  | github.com/cockroachdb/pebble.(*mergingIter).seekGE
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go:1044
  | github.com/cockroachdb/pebble.(*mergingIter).SeekPrefixGE
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go:1120
  | github.com/cockroachdb/pebble.(*lazyCombinedIter).SeekPrefixGE
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/range_keys.go:565
  | github.com/cockroachdb/pebble.(*Iterator).SeekPrefixGE
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/iterator.go:1412
  | github.com/cockroachdb/cockroach/pkg/storage.(*pebbleIterator).SeekGE
  | 	github.com/cockroachdb/cockroach/pkg/storage/pebble_iterator.go:333
  | github.com/cockroachdb/cockroach/pkg/storage.(*pebbleMVCCScanner).get
  | 	github.com/cockroachdb/cockroach/pkg/storage/pebble_mvcc_scanner.go:559
  | github.com/cockroachdb/cockroach/pkg/storage.mvccGetWithValueHeader
  | 	github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:1162
  | github.com/cockroachdb/cockroach/pkg/storage.MVCCGetWithValueHeader
  | 	github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:1087
  | github.com/cockroachdb/cockroach/pkg/storage.MVCCGet
  | 	github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:1057
  | github.com/cockroachdb/cockroach/pkg/storage.MVCCGetProto
  | 	github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:816
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).getQueueLastProcessed
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica.go:1390
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*mvccGCQueue).shouldQueue
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/mvcc_gc_queue.go:264
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*baseQueue).maybeAdd
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/queue.go:700
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.baseQueueHelper.MaybeAdd
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/queue.go:573
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*baseQueue).MaybeAddAsync.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/queue.go:625
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*baseQueue).Async.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/queue.go:612
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (2) runtime error: slice bounds out of range [:-8]
Error types: (1) *withstack.withStack (2) runtime.boundsError
-- report composition:
runtime.boundsError
panic.go:884: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/util/stop/stopper.go#L469-L471](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/util/stop/stopper.go#L469-L471)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/queue.go#L611-L613](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/queue.go#L611-L613)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/queue.go#L624-L626](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/queue.go#L624-L626)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/queue.go#L572-L574](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/queue.go#L572-L574)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/queue.go#L699-L701](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/queue.go#L699-L701)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/mvcc_gc_queue.go#L263-L265](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/mvcc_gc_queue.go#L263-L265)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/replica.go#L1389-L1391](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/replica.go#L1389-L1391)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/storage/mvcc.go#L815-L817](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/storage/mvcc.go#L815-L817)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/storage/mvcc.go#L1056-L1058](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/storage/mvcc.go#L1056-L1058)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/storage/mvcc.go#L1086-L1088](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/storage/mvcc.go#L1086-L1088)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/storage/mvcc.go#L1161-L1163](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/storage/mvcc.go#L1161-L1163)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/storage/pebble_mvcc_scanner.go#L558-L560](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/storage/pebble_mvcc_scanner.go#L558-L560)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/storage/pebble_iterator.go#L332-L334](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/storage/pebble_iterator.go#L332-L334)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/iterator.go#L1411-L1413](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/iterator.go#L1411-L1413)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/range_keys.go#L564-L566](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/range_keys.go#L564-L566)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go#L1119-L1121](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go#L1119-L1121)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go#L1043-L1045](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go#L1043-L1045)
[github.com/cockroachdb/pebble/internal/arenaskl/external/com_github_cockroachdb_pebble/internal/arenaskl/iterator.go#L123-L125](github.com/cockroachdb/pebble/internal/arenaskl/external/com_github_cockroachdb_pebble/internal/arenaskl/iterator.go#L123-L125)
[github.com/cockroachdb/pebble/internal/arenaskl/external/com_github_cockroachdb_pebble/internal/arenaskl/iterator.go#L104-L106](github.com/cockroachdb/pebble/internal/arenaskl/external/com_github_cockroachdb_pebble/internal/arenaskl/iterator.go#L104-L106)
[github.com/cockroachdb/pebble/internal/arenaskl/external/com_github_cockroachdb_pebble/internal/arenaskl/iterator.go#L261-L263](github.com/cockroachdb/pebble/internal/arenaskl/external/com_github_cockroachdb_pebble/internal/arenaskl/iterator.go#L261-L263)
[github.com/cockroachdb/pebble/internal/arenaskl/external/com_github_cockroachdb_pebble/internal/arenaskl/skl.go#L415-L417](github.com/cockroachdb/pebble/internal/arenaskl/external/com_github_cockroachdb_pebble/internal/arenaskl/skl.go#L415-L417)
[GOROOT/src/runtime/panic.go#L138-L140](GOROOT/src/runtime/panic.go#L138-L140)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 470
pkg/kv/kvserver/pkg/kv/kvserver/queue.go in pkg/kv/kvserver.(*baseQueue).Async.func1 at line 612
pkg/kv/kvserver/pkg/kv/kvserver/queue.go in pkg/kv/kvserver.(*baseQueue).MaybeAddAsync.func1 at line 625
pkg/kv/kvserver/pkg/kv/kvserver/queue.go in pkg/kv/kvserver.baseQueueHelper.MaybeAdd at line 573
pkg/kv/kvserver/pkg/kv/kvserver/queue.go in pkg/kv/kvserver.(*baseQueue).maybeAdd at line 700
pkg/kv/kvserver/pkg/kv/kvserver/mvcc_gc_queue.go in pkg/kv/kvserver.(*mvccGCQueue).shouldQueue at line 264
pkg/kv/kvserver/pkg/kv/kvserver/replica.go in pkg/kv/kvserver.(*Replica).getQueueLastProcessed at line 1390
pkg/storage/mvcc.go in pkg/storage.MVCCGetProto at line 816
pkg/storage/mvcc.go in pkg/storage.MVCCGet at line 1057
pkg/storage/mvcc.go in pkg/storage.MVCCGetWithValueHeader at line 1087
pkg/storage/mvcc.go in pkg/storage.mvccGetWithValueHeader at line 1162
pkg/storage/pebble_mvcc_scanner.go in pkg/storage.(*pebbleMVCCScanner).get at line 559
pkg/storage/pebble_iterator.go in pkg/storage.(*pebbleIterator).SeekGE at line 333
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/iterator.go in github.com/cockroachdb/pebble.(*Iterator).SeekPrefixGE at line 1412
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/range_keys.go in github.com/cockroachdb/pebble.(*lazyCombinedIter).SeekPrefixGE at line 565
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go in github.com/cockroachdb/pebble.(*mergingIter).SeekPrefixGE at line 1120
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go in github.com/cockroachdb/pebble.(*mergingIter).seekGE at line 1044
github.com/cockroachdb/pebble/internal/arenaskl/external/com_github_cockroachdb_pebble/internal/arenaskl/iterator.go in github.com/cockroachdb/pebble/internal/arenaskl.(*Iterator).SeekPrefixGE at line 124
github.com/cockroachdb/pebble/internal/arenaskl/external/com_github_cockroachdb_pebble/internal/arenaskl/iterator.go in github.com/cockroachdb/pebble/internal/arenaskl.(*Iterator).SeekGE at line 105
github.com/cockroachdb/pebble/internal/arenaskl/external/com_github_cockroachdb_pebble/internal/arenaskl/iterator.go in github.com/cockroachdb/pebble/internal/arenaskl.(*Iterator).seekForBaseSplice at line 262
github.com/cockroachdb/pebble/internal/arenaskl/external/com_github_cockroachdb_pebble/internal/arenaskl/skl.go in github.com/cockroachdb/pebble/internal/arenaskl.(*Skiplist).findSpliceForLevel at line 416
GOROOT/src/runtime/panic.go in runtime.goPanicSliceAcap at line 139
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
```

### Tags

| Tag | Value |
| --- | --- |
| Command | start-single-node |
| Environment | v23.1.2 |
| Go Version | go1.19.4 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.2 |
| Cockroach SHA | 810d4f27a7f02b9cc2750cab654ed1c62ac3e75a |
| # of CPUs | 24 |
| # of Goroutines | 498 |

Jira issue: CRDB-32850

**Comment by jbowens** [comment]
Note to whoever looks at this: on master and release-23.2 branches this particular panic is not possible because the trailer is not stored within the key byte slice; it's lifted up on to the `arenaskl.node` struct. So you'll need to make sure to code read on the `crl-release-23.1` branch.

**Comment by sumeerbhola** [comment]
It should not be possible for `keySize` to be 0, given that it is initialized using
```
func (k InternalKey) Size() int {
	return len(k.UserKey) + 8
}
```

I'm going to categorize this as memory corruption.
