### ISSUE TITLE
kv: possible batch mutation during commit [inconsistent batch count]

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#113268]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4583696564/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4583696564/?referrer=webhooks_plugin)

Panic Message:

```
db.go:811: log.Fatal: pebble: fatal commit error: pebble: inconsistent batch count: 7046526 vs 7046582
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/pebble.(*DB).applyInternal
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go:811
  | github.com/cockroachdb/pebble.(*DB).Apply
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go:746
  | github.com/cockroachdb/pebble.(*Batch).Commit
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/batch.go:1109
  | github.com/cockroachdb/cockroach/pkg/storage.(*pebbleBatch).Commit
  | 	github.com/cockroachdb/cockroach/pkg/storage/pebble_batch.go:549
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*replicaAppBatch).ApplyToStateMachine
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_app_batch.go:562
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply.(*Task).applyOneBatch
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply/task.go:290
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply.(*Task).ApplyCommittedEntries
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply/task.go:251
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:1005
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReady
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:718
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processReady
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:646
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftSchedulerShard).worker
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:395
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).Start.func2
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:302
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (2) secondary error attachment
  | pebble: inconsistent batch count: 7046526 vs 7046582
  | (1) forced error mark
  |   | ×
  |   | github.com/cockroachdb/errors/withstack/*withstack.withStack::
  | Wraps: (2) attached stack trace
  |   -- stack trace:
  |   | github.com/cockroachdb/pebble/internal/base.CorruptionErrorf
  |   | 	github.com/cockroachdb/pebble/internal/base/external/com_github_cockroachdb_pebble/internal/base/error.go:27
  |   | github.com/cockroachdb/pebble.(*memTable).apply
  |   | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/mem_table.go:224
  |   | github.com/cockroachdb/pebble.(*DB).commitApply
  |   | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go:831
  |   | github.com/cockroachdb/pebble.(*commitPipeline).Commit
  |   | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/commit.go:317
  |   | github.com/cockroachdb/pebble.(*DB).applyInternal
  |   | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go:808
  |   | github.com/cockroachdb/pebble.(*DB).Apply
  |   | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go:746
  |   | github.com/cockroachdb/pebble.(*Batch).Commit
  |   | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/batch.go:1109
  |   | github.com/cockroachdb/cockroach/pkg/storage.(*pebbleBatch).Commit
  |   | 	github.com/cockroachdb/cockroach/pkg/storage/pebble_batch.go:549
  |   | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*replicaAppBatch).ApplyToStateMachine
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_app_batch.go:562
  |   | github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply.(*Task).applyOneBatch
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply/task.go:290
  |   | github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply.(*Task).ApplyCommittedEntries
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply/task.go:251
  |   | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:1005
  |   | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReady
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:718
  |   | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processReady
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:646
  |   | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftSchedulerShard).worker
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:395
  |   | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).Start.func2
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:302
  |   | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  |   | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470
  |   | runtime.goexit
  |   | 	GOROOT/src/runtime/asm_amd64.s:1594
  | Wraps: (3) pebble: inconsistent batch count: 7046526 vs 7046582
  | Error types: (1) *markers.withMark (2) *withstack.withStack (3) *errutil.leafError
Wraps: (3) log.Fatal: pebble: fatal commit error: pebble: inconsistent batch count: 7046526 vs 7046582
Error types: (1) *withstack.withStack (2) *secondary.withSecondaryError (3) *errutil.leafError
-- report composition:
*errutil.leafError: log.Fatal: pebble: fatal commit error: pebble: inconsistent batch count: 7046526 vs 7046582
*secondary.withSecondaryError: details for github.com/cockroachdb/errors/withstack/*withstack.withStack:::
db.go:811: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/util/stop/stopper.go#L469-L471](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/util/stop/stopper.go#L469-L471)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L301-L303](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L301-L303)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L394-L396](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L394-L396)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L645-L647](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L645-L647)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L717-L719](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L717-L719)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L1004-L1006](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L1004-L1006)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/apply/task.go#L250-L252](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/apply/task.go#L250-L252)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/apply/task.go#L289-L291](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/apply/task.go#L289-L291)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/replica_app_batch.go#L561-L563](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/replica_app_batch.go#L561-L563)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/storage/pebble_batch.go#L548-L550](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/storage/pebble_batch.go#L548-L550)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/batch.go#L1108-L1110](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/batch.go#L1108-L1110)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L745-L747](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L745-L747)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L810-L812](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L810-L812)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 470
pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go in pkg/kv/kvserver.(*raftScheduler).Start.func2 at line 302
pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go in pkg/kv/kvserver.(*raftSchedulerShard).worker at line 395
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).processReady at line 646
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).handleRaftReady at line 718
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked at line 1005
pkg/kv/kvserver/apply/task.go in pkg/kv/kvserver/apply.(*Task).ApplyCommittedEntries at line 251
pkg/kv/kvserver/apply/task.go in pkg/kv/kvserver/apply.(*Task).applyOneBatch at line 290
pkg/kv/kvserver/pkg/kv/kvserver/replica_app_batch.go in pkg/kv/kvserver.(*replicaAppBatch).ApplyToStateMachine at line 562
pkg/storage/pebble_batch.go in pkg/storage.(*pebbleBatch).Commit at line 549
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/batch.go in github.com/cockroachdb/pebble.(*Batch).Commit at line 1109
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go in github.com/cockroachdb/pebble.(*DB).Apply at line 746
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go in github.com/cockroachdb/pebble.(*DB).applyInternal at line 811
```

### Tags

| Tag | Value |
| --- | --- |
| Command | start-single-node |
| Environment | v23.1.2 |
| Go Version | go1.19.4 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.2 |
| Cockroach SHA | 810d4f27a7f02b9cc2750cab654ed1c62ac3e75a |
| # of CPUs | 6 |
| # of Goroutines | 480 |

Jira issue: CRDB-32838

**Comment by erikgrinaker** [comment]
@pavelkalinnikov Can you have a look at this when you get a chance?

**Comment by pavelkalinnikov** [comment]
@jbowens Does this error happen only at a single-batch scale? Can it happen that some batch somewhere else is modified while committing, but our batch happens to notice this?

**Comment by jbowens** [comment]
Single batch scale, although batches are pooled, so it could conceivably be the result of a batch elsewhere receiving writes after it’s been closed and reused.
