### ISSUE TITLE
roachtest: backup-restore/mixed-version failed

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#113218]
See original failure message here https://github.com/cockroachdb/cockroach/issues/112373#issuecomment-1782758711

Jira issue: CRDB-32817

**Comment by renatolabs** [comment]
FWIW, the OOM in the failure linked above is an instance of #103481, which was closed as "not-planned".

**Comment by msbutler** [comment]
aha. I missed that. closing this then.
