### ISSUE TITLE
clusterversion: proto Unmarshal on each version check

### ISSUE THREAD

**Issue by pavelkalinnikov** [cockroachdb/cockroach#113385]
As discovered in #111561, the [IsActive](https://github.com/cockroachdb/cockroach/blob/4aa59bcc053a5ace5a0e9ea818b3d3d572b4eabe/pkg/clusterversion/clusterversion.go#L238-L241) cluster version check is on many hot paths. Today it [incurs](https://github.com/cockroachdb/cockroach/blob/71aaf665b6348b9b6e40f38a669bb68f83ea97cd/pkg/clusterversion/setting.go#L140) a protobuf `Unmarshal`, which until recently also allocated (#113043) and amounted as much as 1% of allocations in some tests.

While we got rid of the allocation, we should take it further and be able to do the cluster version checks without unmarshaling protos in the first place.

@dt says:

> we could also just move clusterversion.proto into another package that pkg/settings is allowed to depend on and then store a *ClusterVersion in the atomic instead of a []byte so there'd be no unmarshal -- allocating or otherwise -- on the hot path.

Jira issue: CRDB-32919

**Comment by pavelkalinnikov** [comment]
@dt you had some thoughts on layering here between `clusterversion` and cluster settings packages. Mind elaborating?

**Comment by RaduBerinde** [comment]
I think we can fix this nicely by always storing the unmarshalled `ClusterVersion` in the generic `interface{}` slot.

**Comment by RaduBerinde** [comment]
> @dt you had some thoughts on layering here between clusterversion and cluster settings packages. Mind elaborating?

Maybe @dt has a better idea but I believe we can go a long way if we just separate the protobuf to another package that both packages can use `ClusterVersion`. We keep relearning the lesson to always have a separate package for protos :)

**Comment by RaduBerinde** [comment]
Or maybe we want to move all settings related stuff to `settings` and allow that to depend on `clusterversion`
