### ISSUE TITLE
roachtestutil/mixedversion: inconsistent node IDs

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#113384]
The test in #113222, using the `mixedversion` framework, has inconsistent node IDs. This is confusing to debug, and also breaks assertions that rely on the `node` attribute matching the node ID (typically used for zone configs).

In the cluster I'm currently looking at, nodes are running with these command line arguments:

```
erik     26259 13.4  0.6 2471300 454604 pts/0  Sl   09:06   3:28 /home/erik/local/3/v22.2.13/cockroach start --certs-dir /home/erik/local/3/certs --log file-defaults: {dir: '/home/erik/local/3/logs', exit-on-error: false} --listen-addr=:29000 --http-addr=:29001 --join=127.0.0.1:29004 --store path=/home/erik/local/3/data,attrs=store1:node3:node3store1 --cache=6% --locality=cloud=local,region=local,zone=local --max-sql-memory=6% --pid-file /home/erik/local/3/logs/cockroach.pid
erik     26260 11.7  0.6 1971700 415572 pts/0  Sl   09:06   3:02 /home/erik/local/1/v22.2.13/cockroach start --certs-dir /home/erik/local/1/certs --log file-defaults: {dir: '/home/erik/local/1/logs', exit-on-error: false} --listen-addr=:29004 --http-addr=:29005 --join=127.0.0.1:29004 --store path=/home/erik/local/1/data,attrs=store1:node1:node1store1 --cache=6% --locality=cloud=local,region=local,zone=local --max-sql-memory=6% --pid-file /home/erik/local/1/logs/cockroach.pid
erik     26276 11.3  0.6 2592180 448480 pts/0  Sl   09:06   2:55 /home/erik/local/4/v22.2.13/cockroach start --certs-dir /home/erik/local/4/certs --log file-defaults: {dir: '/home/erik/local/4/logs', exit-on-error: false} --listen-addr=:29006 --http-addr=:29007 --join=127.0.0.1:29004 --store path=/home/erik/local/4/data,attrs=store1:node4:node4store1 --cache=6% --locality=cloud=local,region=local,zone=local --max-sql-memory=6% --pid-file /home/erik/local/4/logs/cockroach.pid
erik     27056 10.3  0.7 1954836 488868 pts/0  Sl   09:07   2:38 /home/erik/local/2/v23.1.1/cockroach start --certs-dir /home/erik/local/2/certs --log file-defaults: {dir: '/home/erik/local/2/logs', exit-on-error: false} --listen-addr=:29002 --http-addr=:29003 --join=127.0.0.1:29004 --store path=/home/erik/local/2/data,attrs=store1:node2:node2store1 --cache=25% --locality=cloud=local,region=local,zone=local --max-sql-memory=25% --pid-file /home/erik/local/2/logs/cockroach.pid
```

From the DB console, I can map port numbers to node IDs:

* n1: port 29004
* n2: port 29000
* n3: port 29002
* n4: port 29006

Cross-referencing with the command-line args, we find two issues:

1. Node attributes and `~/local/<nodeid>` directories do not correspond with the actual node IDs -- e.g. the real n3 is located in `~/local/2` and has node attribute `node2`.

2. All nodes have attribute `store1`, even though the actual store IDs correspond with the real node ID.

I think this happens because the framework explicitly sets `Sequential: false`, which means all nodes will join the cluster concurrently and race for node ID allocation. The `store1` attribute may be a separate bug.

https://github.com/cockroachdb/cockroach/blob/df141ea4b984effa91f39b115443ec74ddc1aa3a/pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go#L715

Jira issue: CRDB-32918

**Comment by erikgrinaker** [comment]
As seen in #113387, this appears to be a problem with the pre-created fixtures used for the nodes. Will hand this off to @renatolabs.

**Comment by renatolabs** [comment]
Ack, thanks for the report! I'll do my best to address this in the next couple of days.

**Comment by renatolabs** [comment]
Why do you believe the problem is with the fixtures? After a quick look at this, my impression was that the problem is indeed with our starting of these nodes concurrently. I think there are ways to work around this issue.

**Comment by erikgrinaker** [comment]
When starting the first node by itself (Sequential: true), it didn't have quorum on the system ranges, because n2 and n3 were unavailable. This is presumably because the fixtures were already populated with multiple nodes in range descriptors.

I don't know how these are generated. It's possible that we strip the store-local keys such that nodes will allocate new IDs when joining, but we'll still need a quorum to do so I believe.

**Comment by renatolabs** [comment]
> This is presumably because the fixtures were already populated with multiple nodes in range descriptors.

Yeah, I understand that. I was wondering if you were saying they shouldn't (is that even possible?) by opening this issue.

> but we'll still need a quorum to bootstrap I believe.

One option I'm considering is to always start nodes sequentially and only allow concurrency in initialization / setup steps. Seems like having node IDs _not_ match hostnames shouldn't be allowed due to how confusing it is.

> All nodes have attribute store1, even though the actual store IDs correspond with the real node ID.

I believe this has always been the case, if I understand it correctly. There's a comment about it in the corresponding code:

https://github.com/cockroachdb/cockroach/blob/0045f69f3e7f15b41eda768eb1136e0f7c91bfa7/pkg/roachprod/install/cockroach.go#L874-L880

**Comment by erikgrinaker** [comment]
> I was wondering if you were saying they shouldn't (is that even possible?) by opening this issue.

I just want the node IDs to match the label/directory/hostname. 😄

I figured we'd run into a problem when we need to get multiple nodes online before we can allocate node IDs and also prevent them from racing for node IDs. But maybe we don't, I don't know the details here.
