### ISSUE TITLE
changefeedccl: initial protected timestamp does not match cursor

### ISSUE THREAD

**Issue by jayshrivastava** [cockroachdb/cockroach#113492]
<img width="1289" alt="image" src="https://github.com/cockroachdb/cockroach/assets/18633281/3481ca0b-efe7-4fe4-90aa-998a5957a446">

Jira issue: CRDB-33019

**Comment by miretskiy** [comment]
Can you say more? When changefeed is created, a new record is also created.  What is the mismatch you're talking about?

**Comment by miretskiy** [comment]
I think it actually works as intended.  I think this tiny table checkpoints almost immediately, and updates highwatermark accordingly.

**Comment by wenyihu6** [comment]
Discussed in meetings and closing as no apparent issues. I will re-sync with Jay after he is back and re-open if needed.
