### ISSUE TITLE
TransactionRetryError missing error info

### ISSUE THREAD

**Issue by williamkulju** [cockroachdb/cockroach#113496]
A community user is reporting the following error: "TransactionRetryError: retry txn (RETRY_SERIALIZABLE - failed preemptive refresh - unknown error: <nil>)." The user is saying there isn't sufficient info in this message or our docs for a user to debug what is going on. 

According to @nvanbenschoten "The error message itself does look like a bug. We’re shadowing the non-nil refreshErr *roachpb.Error with a nil refreshErr *roachpb.RefreshFailedError."  Note this issue is already fixed on master (as part of this [larger](https://github.com/cockroachdb/cockroach/pull/108190/commits/65a25b327ce5b8e941d2b2e30660072d2b2dc9a3) change) so the error message fix would only need to be backported to 23.1.x and below. Additionally, we should see if we can do a better job documenting what this error means and how to work around it.

Jira issue: CRDB-33023

**Comment by nvanbenschoten** [comment]
Fixed by https://github.com/cockroachdb/cockroach/pull/113895.
