### ISSUE TITLE
changefeedccl: changefeed expression is removed after altering changefeed

### ISSUE THREAD

**Issue by jayshrivastava** [cockroachdb/cockroach#113491]
See https://github.com/cockroachlabs/support/issues/2697

<img width="823" alt="image" src="https://github.com/cockroachdb/cockroach/assets/18633281/c1e9d1ba-d579-4668-9bbd-2b4989024732">

Jira issue: CRDB-33018

**Comment by miretskiy** [comment]
This is a known limitation: Going to close #82491 (as you can see it's a very old issue referencing predicates and projections)

**Comment by jayshrivastava** [comment]
Closing as dupe of 82491
