### ISSUE TITLE
metrics: DB Console incorrectly aggregates CPU stats from tenants into system Hardware dashboard 

### ISSUE THREAD

**Issue by dhartunian** [cockroachdb/cockroach#113559]
**Describe the problem**

When running a shared-process virtualized cluster, the CPU Percent metric in DB Console's dashboard shows an aggregated number from **both** the application and system tenant. This is incorrect because they share the process and are both measuring **the same CPU metric**.

**To Reproduce**

**Expected behavior**

System tenant hardware dashboard should just show the system tenant's hardware metrics instead of aggregating across tenants.

**Additional data / screenshots**

![Screenshot 2023-11-01 at 10 37 36](https://github.com/cockroachdb/cockroach/assets/986307/0aa6e6cf-0c11-4ad5-9e4b-be8de3d469a4)

Same cluster's `_status/vars`

<img width="1271" alt="Screenshot 2023-11-01 at 15 19 24" src="https://github.com/cockroachdb/cockroach/assets/986307/075dce5c-5533-4910-a1c0-819fa45deeae">

**Environment:**
 - CockroachDB version: 23.1.11
 - Server OS: Linux
 - Client app: DB console

Jira issue: CRDB-33048

**Comment by dhartunian** [comment]
This is fixed in 23.2 here: https://github.com/cockroachdb/cockroach/pull/109727. The change was done after a bunch of work was shipped to add a tenant selector to the DB Console. Due to the low usage of multi-tenancy in 23.1 my instinct is not to backport this fix since it would likely carry with it 3 other PRs to add a feature. Customers who scrape metrics with Prometheus would not see this problem.

**Comment by erikgrinaker** [comment]
Makes sense, let's close this out.
