### ISSUE TITLE
storage: benchmark low raft tick interval

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#1135]
When set low (10ms in #1131), raft tick intervals can cause issues due to the amount of work being done.
We should benchmark this and attempt to resolve any performance issues.

**Comment by bdarnell** [comment]
With #1133, the worst problems caused by a tick interval that is too small should be solved, but we should still test and make sure, so I'm leaving this bug open.

**Comment by bdarnell** [comment]
I think we can close this: a tick interval of 10ms is pretty crazy; we're more likely to increase the tick interval than decrease it again.
