### ISSUE TITLE
backupccl: verify that stored procedures play nice with backup restore

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#113535]
As far as I can tell, we currently don't explicitly test how stored procedures behave during backup and restore -- i.e. If the user backs up a database with  a stored procedure, and then restores it, does the stored procedure still work as expected?.

Jira issue: CRDB-33042

**Comment by mgartner** [comment]
@msbutler Do the tests in #113714 alleviate your concerns, or did you have additional tests in mind?

**Comment by msbutler** [comment]
Just gave that Pr a look. Looks great! thank you for doing this.

**Comment by mgartner** [comment]
Fixed by #113714.
