### ISSUE TITLE
kvserver/reports: replication report update can get stuck in retry loop

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#113669]
On a 23.2-alpha.5 test cluster, we saw a CPU outlier node spend 15% of a profile spinning on a replication reports range iterator retry loop:

<img width="1390" alt="Screenshot 2023-11-02 at 14 16 08" src="https://github.com/cockroachdb/cockroach/assets/644420/c040c80c-8e4f-4bce-b4f4-ba139662c60b">

https://github.com/cockroachdb/cockroach/blob/7e4233d09edef5420b8f12d917112ce762ac1855/pkg/kv/kvserver/reports/reporter.go#L582-L588

This logic only runs on the meta1 leaseholder, and this node hadn't had a meta1 replica for about 16 hours.

I think there's been discussions about removing replication reports outright? Either way, we'll want a fix for this in existing versions.

Jira issue: CRDB-33101

**Comment by andrewbaptist** [comment]
Should we tag this as a release-blocker for 23.2?

**Comment by erikgrinaker** [comment]
Pretty sure this is a pre-existing problem. Have anyone made any changes here for 23.2?
