### ISSUE TITLE
kvserver: v22.2.0: fatal: trying to bump to ts <= ba.Timestamp

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#113648]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4594647625/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4594647625/?referrer=webhooks_plugin)

Panic Message:

```
replica_batch_updates.go:227: log.Fatal: trying to bump to 1698867551.088882683,1 <= ba.Timestamp: 1698902784.108914188,0
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.tryBumpBatchTimestamp
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_batch_updates.go:227
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.canDoServersideRetry
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_evaluate.go:609
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).evaluateWriteBatchWithServersideRefreshes
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go:638
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).evaluateWriteBatch
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go:432
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).evaluateProposal
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go:660
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).requestToProposal
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go:748
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).evalAndPropose
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:112
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).executeWriteBatch
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go:168
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).executeBatchWithConcurrencyRetries
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go:480
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).SendWithWriteBytes
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go:179
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).SendWithWriteBytes
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_send.go:204
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Stores).SendWithWriteBytes
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/stores.go:227
  | github.com/cockroachdb/cockroach/pkg/server.(*Node).batchInternal
  | 	github.com/cockroachdb/cockroach/pkg/server/node.go:1090
  | github.com/cockroachdb/cockroach/pkg/server.(*Node).Batch
  | 	github.com/cockroachdb/cockroach/pkg/server/node.go:1139
  | github.com/cockroachdb/cockroach/pkg/rpc.makeInternalClientAdapter.func1
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:724
  | github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor.ServerInterceptor.func1
  | 	github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go:95
  | github.com/cockroachdb/cockroach/pkg/rpc.bindUnaryServerInterceptorToHandler.func1
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:795
  | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func3
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:263
  | github.com/cockroachdb/cockroach/pkg/rpc.bindUnaryServerInterceptorToHandler.func1
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:795
  | github.com/cockroachdb/cockroach/pkg/rpc.kvAuth.unaryInterceptor
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/auth.go:73
  | github.com/cockroachdb/cockroach/pkg/rpc.bindUnaryServerInterceptorToHandler.func1
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:795
  | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func1.1
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:232
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:341
  | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func1
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:230
  | github.com/cockroachdb/cockroach/pkg/rpc.bindUnaryServerInterceptorToHandler.func1
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:795
  | github.com/cockroachdb/cockroach/pkg/rpc.makeInternalClientAdapter.func2
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:734
  | github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor.ClientInterceptor.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go:225
  | github.com/cockroachdb/cockroach/pkg/rpc.getChainUnaryInvoker.func1
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:879
  | github.com/cockroachdb/cockroach/pkg/rpc.makeInternalClientAdapter.func3
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:764
  | github.com/cockroachdb/cockroach/pkg/rpc.internalClientAdapter.Batch
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:887
  | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*grpcTransport).sendBatch
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/transport.go:211
  | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*grpcTransport).SendNext
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/transport.go:190
Wraps: (2) log.Fatal: trying to bump to 1698867551.088882683,1 <= ba.Timestamp: 1698902784.108914188,0
Error types: (1) *withstack.withStack (2) *errutil.leafError
-- report composition:
*errutil.leafError: log.Fatal: trying to bump to 1698867551.088882683,1 <= ba.Timestamp: 1698902784.108914188,0
replica_batch_updates.go:227: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/kv/kvclient/kvcoord/transport.go#L189-L191](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/kv/kvclient/kvcoord/transport.go#L189-L191)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/kv/kvclient/kvcoord/transport.go#L210-L212](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/kv/kvclient/kvcoord/transport.go#L210-L212)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/rpc/pkg/rpc/context.go#L886-L888](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/rpc/pkg/rpc/context.go#L886-L888)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/rpc/pkg/rpc/context.go#L763-L765](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/rpc/pkg/rpc/context.go#L763-L765)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/rpc/pkg/rpc/context.go#L878-L880](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/rpc/pkg/rpc/context.go#L878-L880)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go#L224-L226](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go#L224-L226)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/rpc/pkg/rpc/context.go#L733-L735](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/rpc/pkg/rpc/context.go#L733-L735)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/rpc/pkg/rpc/context.go#L794-L796](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/rpc/pkg/rpc/context.go#L794-L796)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/rpc/pkg/rpc/context.go#L229-L231](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/rpc/pkg/rpc/context.go#L229-L231)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/util/stop/stopper.go#L340-L342](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/util/stop/stopper.go#L340-L342)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/rpc/pkg/rpc/context.go#L231-L233](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/rpc/pkg/rpc/context.go#L231-L233)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/rpc/pkg/rpc/context.go#L794-L796](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/rpc/pkg/rpc/context.go#L794-L796)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/rpc/pkg/rpc/auth.go#L72-L74](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/rpc/pkg/rpc/auth.go#L72-L74)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/rpc/pkg/rpc/context.go#L794-L796](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/rpc/pkg/rpc/context.go#L794-L796)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/rpc/pkg/rpc/context.go#L262-L264](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/rpc/pkg/rpc/context.go#L262-L264)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/rpc/pkg/rpc/context.go#L794-L796](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/rpc/pkg/rpc/context.go#L794-L796)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go#L94-L96](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go#L94-L96)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/rpc/pkg/rpc/context.go#L723-L725](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/rpc/pkg/rpc/context.go#L723-L725)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/server/node.go#L1138-L1140](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/server/node.go#L1138-L1140)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/server/node.go#L1089-L1091](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/server/node.go#L1089-L1091)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/kv/kvserver/pkg/kv/kvserver/stores.go#L226-L228](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/kv/kvserver/pkg/kv/kvserver/stores.go#L226-L228)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/kv/kvserver/pkg/kv/kvserver/store_send.go#L203-L205](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/kv/kvserver/pkg/kv/kvserver/store_send.go#L203-L205)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go#L178-L180](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go#L178-L180)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go#L479-L481](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go#L479-L481)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go#L167-L169](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go#L167-L169)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L111-L113](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L111-L113)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go#L747-L749](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go#L747-L749)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go#L659-L661](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go#L659-L661)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go#L431-L433](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go#L431-L433)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go#L637-L639](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go#L637-L639)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/kv/kvserver/pkg/kv/kvserver/replica_evaluate.go#L608-L610](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/kv/kvserver/pkg/kv/kvserver/replica_evaluate.go#L608-L610)
[https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/kv/kvserver/pkg/kv/kvserver/replica_batch_updates.go#L226-L228](https://github.com/cockroachdb/cockroach/blob/77667a1b0101cd323090011f50cf910aaa933654/pkg/kv/kvserver/pkg/kv/kvserver/replica_batch_updates.go#L226-L228)
</details>

```
pkg/kv/kvclient/kvcoord/transport.go in pkg/kv/kvclient/kvcoord.(*grpcTransport).SendNext at line 190
pkg/kv/kvclient/kvcoord/transport.go in pkg/kv/kvclient/kvcoord.(*grpcTransport).sendBatch at line 211
pkg/rpc/pkg/rpc/context.go in pkg/rpc.internalClientAdapter.Batch at line 887
pkg/rpc/pkg/rpc/context.go in pkg/rpc.makeInternalClientAdapter.func3 at line 764
pkg/rpc/pkg/rpc/context.go in pkg/rpc.getChainUnaryInvoker.func1 at line 879
pkg/util/tracing/grpcinterceptor/grpc_interceptor.go in pkg/util/tracing/grpcinterceptor.ClientInterceptor.func2 at line 225
pkg/rpc/pkg/rpc/context.go in pkg/rpc.makeInternalClientAdapter.func2 at line 734
pkg/rpc/pkg/rpc/context.go in pkg/rpc.bindUnaryServerInterceptorToHandler.func1 at line 795
pkg/rpc/pkg/rpc/context.go in pkg/rpc.NewServerEx.func1 at line 230
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunTaskWithErr at line 341
pkg/rpc/pkg/rpc/context.go in pkg/rpc.NewServerEx.func1.1 at line 232
pkg/rpc/pkg/rpc/context.go in pkg/rpc.bindUnaryServerInterceptorToHandler.func1 at line 795
pkg/rpc/pkg/rpc/auth.go in pkg/rpc.kvAuth.unaryInterceptor at line 73
pkg/rpc/pkg/rpc/context.go in pkg/rpc.bindUnaryServerInterceptorToHandler.func1 at line 795
pkg/rpc/pkg/rpc/context.go in pkg/rpc.NewServerEx.func3 at line 263
pkg/rpc/pkg/rpc/context.go in pkg/rpc.bindUnaryServerInterceptorToHandler.func1 at line 795
pkg/util/tracing/grpcinterceptor/grpc_interceptor.go in pkg/util/tracing/grpcinterceptor.ServerInterceptor.func1 at line 95
pkg/rpc/pkg/rpc/context.go in pkg/rpc.makeInternalClientAdapter.func1 at line 724
pkg/server/node.go in pkg/server.(*Node).Batch at line 1139
pkg/server/node.go in pkg/server.(*Node).batchInternal at line 1090
pkg/kv/kvserver/pkg/kv/kvserver/stores.go in pkg/kv/kvserver.(*Stores).SendWithWriteBytes at line 227
pkg/kv/kvserver/pkg/kv/kvserver/store_send.go in pkg/kv/kvserver.(*Store).SendWithWriteBytes at line 204
pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go in pkg/kv/kvserver.(*Replica).SendWithWriteBytes at line 179
pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go in pkg/kv/kvserver.(*Replica).executeBatchWithConcurrencyRetries at line 480
pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go in pkg/kv/kvserver.(*Replica).executeWriteBatch at line 168
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).evalAndPropose at line 112
pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go in pkg/kv/kvserver.(*Replica).requestToProposal at line 748
pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go in pkg/kv/kvserver.(*Replica).evaluateProposal at line 660
pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go in pkg/kv/kvserver.(*Replica).evaluateWriteBatch at line 432
pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go in pkg/kv/kvserver.(*Replica).evaluateWriteBatchWithServersideRefreshes at line 638
pkg/kv/kvserver/pkg/kv/kvserver/replica_evaluate.go in pkg/kv/kvserver.canDoServersideRetry at line 609
pkg/kv/kvserver/pkg/kv/kvserver/replica_batch_updates.go in pkg/kv/kvserver.tryBumpBatchTimestamp at line 227
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v22.2.0 |
| Go Version | go1.19.1 |
| Platform | linux arm64 |
| Distribution | CCL |
| Cockroach Release | v22.2.0 |
| Cockroach SHA | 77667a1b0101cd323090011f50cf910aaa933654 |
| # of CPUs | 4 |
| # of Goroutines | 320 |

Jira issue: CRDB-33088

**Comment by nvanbenschoten** [comment]
Fixed by https://github.com/cockroachdb/cockroach/pull/101583.
