### ISSUE TITLE
P99 spikes when hydrating new nodes

### ISSUE THREAD

**Issue by williamkulju** [cockroachdb/cockroach#113720]
@sean-  observed a latency spike when adding new nodes to the 23.2 large scale test cluster. See screen shot below. @andrewbaptist said he thinks this is due to the fact that multi-store rebalance thresholds are not set well.  He suggested turning that down to something like 64MB / num_stores_per_node to see if it does better. However, even after setting kv.snapshot_rebalance.max_rate = '1MiB', p99 latency remained elevated around 32ms, up from ~6-8ms. Andrew also said the ideal fix was probably to handle this in AC

![image](https://github.com/cockroachdb/cockroach/assets/110843721/b5f0d877-d026-4553-99c6-afb4c908ee38)

Jira issue: CRDB-33121

**Comment by sumeerbhola** [comment]
Closing this in the absence of clarification on https://cockroachlabs.slack.com/archives/C05VAJ5H3QS/p1699297259154569?thread_ts=1698867425.896539&cid=C05VAJ5H3QS
