### ISSUE TITLE
sql/schemachanger: apply admission control to index merging

### ISSUE THREAD

**Issue by fqazi** [cockroachdb/cockroach#113705]
Previously, admission control was only applied to the scan portion of the index merge operation, and the correct flag was never passed on the actual writes done by this operation. Update this code to pass the same flags as the scan.

The existing scan sets a priority flag:
https://github.com/cockroachdb/cockroach/blob/299f41ea88bdcf0d82295e8655dc7d948f38f57a/pkg/sql/backfill/mvcc_index_merger.go#L301

The actual merges themselves don't:
https://github.com/cockroachdb/cockroach/blob/299f41ea88bdcf0d82295e8655dc7d948f38f57a/pkg/sql/backfill/mvcc_index_merger.go#L351C15-L351C15

In our scale testing we are seeing performance tank during the merge phase.

Jira issue: CRDB-33117

**Comment by sumeerbhola** [comment]
We should backport this to 23.1 and 22.2.

**Comment by williamkulju** [comment]
should this be tagged as a 23.2 release blocker?
