### ISSUE TITLE
sql: v23.1.11: closed-session-cache: no bytes in account to release

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#113994]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4611592931/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4611592931/?referrer=webhooks_plugin)

Panic Message:

```
crash_reporting.go:390: closed-session-cache: no bytes in account to release, current 564563, free 3674937295934325754
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/util/log/logcrash.ReportOrPanic
  | 	github.com/cockroachdb/cockroach/pkg/util/log/logcrash/crash_reporting.go:390
  | github.com/cockroachdb/cockroach/pkg/util/mon.(*BoundAccount).Shrink
  | 	github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:915
  | github.com/cockroachdb/cockroach/pkg/sql.NewClosedSessionCache.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/closed_session_cache.go:78
  | github.com/cockroachdb/cockroach/pkg/util/cache.(*baseCache).removeElement
  | 	github.com/cockroachdb/cockroach/pkg/util/cache/cache.go:325
  | github.com/cockroachdb/cockroach/pkg/util/cache.(*baseCache).evict
  | 	github.com/cockroachdb/cockroach/pkg/util/cache/cache.go:340
  | github.com/cockroachdb/cockroach/pkg/util/cache.(*baseCache).add
  | 	github.com/cockroachdb/cockroach/pkg/util/cache/cache.go:249
  | github.com/cockroachdb/cockroach/pkg/util/cache.(*baseCache).Add
  | 	github.com/cockroachdb/cockroach/pkg/util/cache/cache.go:209
  | github.com/cockroachdb/cockroach/pkg/sql.(*ClosedSessionCache).add
  | 	github.com/cockroachdb/cockroach/pkg/sql/closed_session_cache.go:104
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2092
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2108
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).runWithEx.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:175
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (2) closed-session-cache: no bytes in account to release, current 564563, free 3674937295934325754
Error types: (1) *withstack.withStack (2) *errutil.leafError
-- report composition:
*errutil.leafError: closed-session-cache: no bytes in account to release, current 564563, free 3674937295934325754
crash_reporting.go:390: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/internal.go#L174-L176](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/internal.go#L174-L176)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L2107-L2109](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L2107-L2109)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L2091-L2093](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L2091-L2093)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/closed_session_cache.go#L103-L105](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/closed_session_cache.go#L103-L105)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/util/cache/cache.go#L208-L210](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/util/cache/cache.go#L208-L210)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/util/cache/cache.go#L248-L250](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/util/cache/cache.go#L248-L250)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/util/cache/cache.go#L339-L341](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/util/cache/cache.go#L339-L341)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/util/cache/cache.go#L324-L326](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/util/cache/cache.go#L324-L326)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/closed_session_cache.go#L77-L79](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/closed_session_cache.go#L77-L79)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/util/mon/bytes_usage.go#L914-L916](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/util/mon/bytes_usage.go#L914-L916)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/util/log/logcrash/crash_reporting.go#L389-L391](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/util/log/logcrash/crash_reporting.go#L389-L391)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/sql/internal.go in pkg/sql.(*InternalExecutor).runWithEx.func1 at line 175
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 2108
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run.func1 at line 2092
pkg/sql/closed_session_cache.go in pkg/sql.(*ClosedSessionCache).add at line 104
pkg/util/cache/cache.go in pkg/util/cache.(*baseCache).Add at line 209
pkg/util/cache/cache.go in pkg/util/cache.(*baseCache).add at line 249
pkg/util/cache/cache.go in pkg/util/cache.(*baseCache).evict at line 340
pkg/util/cache/cache.go in pkg/util/cache.(*baseCache).removeElement at line 325
pkg/sql/closed_session_cache.go in pkg/sql.NewClosedSessionCache.func2 at line 78
pkg/util/mon/bytes_usage.go in pkg/util/mon.(*BoundAccount).Shrink at line 915
pkg/util/log/logcrash/crash_reporting.go in pkg/util/log/logcrash.ReportOrPanic at line 390
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v23.1.11 |
| Go Version | go1.19.10 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.11 |
| Cockroach SHA | 62ad175cbc0e9041d993ea1cc911e07d279671f5 |
| # of CPUs | 4 |
| # of Goroutines | 361 |

Jira issue: CRDB-33287

**Comment by yuzefovich** [comment]
not sure what's wrong here, unactionable
