### ISSUE TITLE
admission: include request priority and queue name in WorkQueue tracing

### ISSUE THREAD

**Issue by sumeerbhola** [cockroachdb/cockroach#113990]
trace statements like
```
work kv deadline expired while waiting: deadline: 2023-10-14 10:20:57.098424558 +0000 UTC m=+377.360809249, start: 2023-10-14 10:19:57.098548 +0000 UTC m=+317.360932704, dur: 1m0.039413971s
```
don't tell us whether it was a store queue (and elastic or regular) or the CPU queue.

Jira issue: CRDB-33285

**Comment by sumeerbhola** [comment]
Also, the error when exceeding deadline for flow control tokens is unhelpful. It should include all the information in the preceding log statement https://github.com/cockroachdb/cockroach/blob/d9296a0787e9f3a0e8483a13a13688ce229d3284/pkg/kv/kvserver/kvflowcontrol/kvflowcontroller/kvflowcontroller.go#L205

**Comment by aadityasondhi** [comment]
Since both https://github.com/cockroachdb/cockroach/pull/114664 and https://github.com/cockroachdb/cockroach/pull/115262 have been merged and backported to relevant branches, this issue is now resolved.
