### ISSUE TITLE
sql: PartitionSpans for a large number of spans can result in  a node hotspot on the gateway

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#114079]
Bulk jobs and SQL queries share the same underlying infrastructure to partition a set of spans and find appropriate nodes based on the passed in configurations. In https://github.com/cockroachlabs/support/issues/2659 we noticed a case where a `BACKUP WITH EXECUTION LOCALITY` could end up getting all the spans handed to the gateway node, causing a severe degradation in performance.

In the escalation above we saw that the oracle that determines the node to send a span to returned instances that did not match our locality filter. This is not on its own a bug in the oracle because there could be several reasons such as no replicas in the region with the locality filter, or txn timestamps not being old enough to be served by follower reads. Since none of our eligible instances could be picked, we ended up choosing the gateway for every span - https://github.com/cockroachdb/cockroach/blob/94f3605d13d334cb5804949d61ece91786b2e397/pkg/sql/distsql_physical_planner.go#L1639. 

This bias towards the gateway makes sense for most OLTP SQL queries as explained by @rharding6373 and @yuzefovich over here - https://cockroachlabs.slack.com/archives/C01RX2G8LT1/p1699395502272229?thread_ts=1699393510.164829&cid=C01RX2G8LT1. Bulk jobs (backup, restore, CDC, PCR) however rely entirely on this partitioning to divide their work, and do not have an external load balancer they can rely on. Presumably, OLAP queries with thousands of spans would run into a similar hotspot problem.

A proposed solution would be to add a heuristic that defaults to the gateway up until some threshold, after which we randomly distribute the remaining spans to other healthy instances in our set of eligible instances. In an ideal world we'd have a `(1/n) * number of spans` division of work where n = number of healthy, eligible instances, so we could say that if the gateway has been assigned 3 * (1 / n) spans because of no better choice,  we start round robin assigning to other eligible instances.

Jira issue: CRDB-33325

**Comment by miretskiy** [comment]
I want to chime in here -- it's not only DR jobs that are impacted, but also CDC (and we also have escalations around this issue)

**Comment by adityamaru** [comment]
reopening until the backport lands
