### ISSUE TITLE
changefeedccl: enhance "advanced-changefeed-configuration" doc

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#114157]
This is really docs issue.
We should add a KB section, and also update advanced changefeed configuration 
section wrt to running large scale changefeeds.
https://www.cockroachlabs.com/docs/v23.1/advanced-changefeed-configuration

23.2 is shipping with LOTS of changes to improve performance characteristics
of large scale changefeeds.  
Even 23.1 can be tuned to improve scalability and reduce the changefeed impact on the cluster sql latency.

Over the past few releases, we have been working on a new subsystem, called MuxRangefeed
that unlock higher levels of scalability.   The functionality is enabled via cluster settings,
and should be considered in preview mode.  However, given the extensive amount of testing
performed, we recommend this be enable for large scale changefeed workloads (though smaller
installations might also benefit).

* Enable mux rangefeed via `kv.changefeed.mux_rangefeed.enabled = true` setting.  After changing this setting, pause/resume any currently running changefeeds.
* If the workload does not utilize follower reads (i.e. does not rely on issuing reads AS OF SYSTEM TIME), then it might make sense to increase the `kv.rangefeed.closed_timestamp_refresh_interval` to  '10s', or even '30s' (anything beyond that is diminishing return).
* Consider slowing down changefeed checkpoints.  Large scale changefeeds spend quite a bit of time (and CPU) managing internal state; slowing down the rate of checkpoints (at the cost of more expensive restarts, because if changefeed restarts, it will necessarily need to transmit more data): Increase the default 30 second frequency to few minutes -- maybe 3-5m by adding `min_checkpoint_frequency='5m'` option to changefeeds.  To do that, you can pause changefeed, ALTER CHANGEFEED, then resume the changefeed.

In 23.2 clusters:
Enable rangefeed scheduler by setting `kv.rangefeed.scheduler.enabled = true`

Jira issue: CRDB-33371

**Comment by kathancox** [comment]
@miretskiy has the scheduler been turned on by default https://github.com/cockroachdb/cockroach/pull/114410?

If so, do we want to make any reference to how rangefeed scheduling is now improved... perhaps not?

**Comment by kathancox** [comment]
Closing this issue in favor of this docs issue: [DOC-9300](https://cockroachlabs.atlassian.net/browse/DOC-9300)
Updates needed to the advanced changefeed docs with input needed from cdc eng, which will be tracked in that docs issue.
