### ISSUE TITLE
Sentry: grant_revoke_system.go:204: no tables found
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*changeNonDescriptorBackedPriv...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#114124]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4615860430/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4615860430/?referrer=webhooks_plugin)

Panic Message:

```
grant_revoke_system.go:204: no tables found
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*changeNonDescriptorBackedPrivilegesNode).makeSystemPrivilegeObject
  | 	github.com/cockroachdb/cockroach/pkg/sql/grant_revoke_system.go:204
  | github.com/cockroachdb/cockroach/pkg/sql.(*changeNonDescriptorBackedPrivilegesNode).startExec
  | 	github.com/cockroachdb/cockroach/pkg/sql/grant_revoke_system.go:51
  | github.com/cockroachdb/cockroach/pkg/sql.startExec.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan.go:518
  | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:112
  | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:297
  | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:79
  | github.com/cockroachdb/cockroach/pkg/sql.walkPlan
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:43
  | github.com/cockroachdb/cockroach/pkg/sql.startExec
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan.go:521
  | github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Start
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:166
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*FlowCoordinator).Start.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:122
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*FlowCoordinator).Start
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:121
  | github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBaseNoHelper).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:728
  | github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:480
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:307
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:733
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1728
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1445
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1587
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1201
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:696
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:131
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2428
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:130
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1973
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1977
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1898
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:857
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:730
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (3) no tables found
Error types: (1) *assert.withAssertionFailure (2) *withstack.withStack (3) *errutil.leafError
-- report composition:
*errutil.leafError: no tables found
grant_revoke_system.go:204: *withstack.withStack (top exception)
*assert.withAssertionFailure
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/pgwire/conn.go#L729-L731](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/pgwire/conn.go#L729-L731)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/conn_executor.go#L856-L858](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/conn_executor.go#L856-L858)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/conn_executor.go#L1897-L1899](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/conn_executor.go#L1897-L1899)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/conn_executor.go#L1976-L1978](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/conn_executor.go#L1976-L1978)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/conn_executor.go#L1972-L1974](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/conn_executor.go#L1972-L1974)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/conn_executor_exec.go#L129-L131](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/conn_executor_exec.go#L129-L131)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/conn_executor_exec.go#L2427-L2429](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/conn_executor_exec.go#L2427-L2429)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/conn_executor_exec.go#L130-L132](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/conn_executor_exec.go#L130-L132)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/conn_executor_exec.go#L695-L697](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/conn_executor_exec.go#L695-L697)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/conn_executor_exec.go#L1200-L1202](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/conn_executor_exec.go#L1200-L1202)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/conn_executor_exec.go#L1586-L1588](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/conn_executor_exec.go#L1586-L1588)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/distsql_running.go#L1444-L1446](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/distsql_running.go#L1444-L1446)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/distsql_running.go#L1727-L1729](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/distsql_running.go#L1727-L1729)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/distsql_running.go#L732-L734](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/distsql_running.go#L732-L734)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/colflow/vectorized_flow.go#L306-L308](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/colflow/vectorized_flow.go#L306-L308)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/flowinfra/flow.go#L479-L481](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/flowinfra/flow.go#L479-L481)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/execinfra/processorsbase.go#L727-L729](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/execinfra/processorsbase.go#L727-L729)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/colflow/flow_coordinator.go#L120-L122](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/colflow/flow_coordinator.go#L120-L122)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/colflow/flow_coordinator.go#L121-L123](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/colflow/flow_coordinator.go#L121-L123)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/plan_node_to_row_source.go#L165-L167](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/plan_node_to_row_source.go#L165-L167)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/plan.go#L520-L522](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/plan.go#L520-L522)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/walk.go#L42-L44](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/walk.go#L42-L44)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/walk.go#L78-L80](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/walk.go#L78-L80)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/walk.go#L296-L298](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/walk.go#L296-L298)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/walk.go#L111-L113](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/walk.go#L111-L113)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/plan.go#L517-L519](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/plan.go#L517-L519)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/grant_revoke_system.go#L50-L52](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/grant_revoke_system.go#L50-L52)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/grant_revoke_system.go#L203-L205](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/grant_revoke_system.go#L203-L205)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommandsAsync.func1 at line 730
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 857
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 1898
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 1977
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd.func1 at line 1973
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 130
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithProfiling at line 2428
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt.func1 at line 131
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 696
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchToExecutionEngine at line 1201
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithDistSQLEngine at line 1587
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRunAll at line 1445
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRun at line 1728
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).Run at line 733
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlow).Run at line 307
pkg/sql/flowinfra/flow.go in pkg/sql/flowinfra.(*FlowBase).Run at line 480
pkg/sql/execinfra/processorsbase.go in pkg/sql/execinfra.(*ProcessorBaseNoHelper).Run at line 728
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*FlowCoordinator).Start at line 121
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*FlowCoordinator).Start.func1 at line 122
pkg/sql/plan_node_to_row_source.go in pkg/sql.(*planNodeToRowSource).Start at line 166
pkg/sql/plan.go in pkg/sql.startExec at line 521
pkg/sql/walk.go in pkg/sql.walkPlan at line 43
pkg/sql/walk.go in pkg/sql.(*planVisitor).visit at line 79
pkg/sql/walk.go in pkg/sql.(*planVisitor).visitInternal at line 297
pkg/sql/walk.go in pkg/sql.(*planVisitor).visitInternal.func1 at line 112
pkg/sql/plan.go in pkg/sql.startExec.func2 at line 518
pkg/sql/grant_revoke_system.go in pkg/sql.(*changeNonDescriptorBackedPrivilegesNode).startExec at line 51
pkg/sql/grant_revoke_system.go in pkg/sql.(*changeNonDescriptorBackedPrivilegesNode).makeSystemPrivilegeObject at line 204
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v22.2.7 |
| Go Version | go1.19.6 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v22.2.7 |
| Cockroach SHA | cbe33971930ee972e639203a73f14240b92aeff4 |
| # of CPUs | 2 |
| # of Goroutines | 375 |

Jira issue: CRDB-33353

**Comment by yuzefovich** [comment]
dup of #93417
