### ISSUE TITLE
Sentry: db.go:747: log.Fatal: write ×: stale NFS file handle
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/pebble.(*DB).Apply
  | 	github.com/cockroachdb/pebble/external/com_g...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#114183]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4617959977/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4617959977/?referrer=webhooks_plugin)

Panic Message:

```
db.go:747: log.Fatal: write ×: stale NFS file handle
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/pebble.(*DB).Apply
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go:747
  | github.com/cockroachdb/pebble.(*Batch).Commit
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/batch.go:1049
  | github.com/cockroachdb/cockroach/pkg/storage.(*pebbleBatch).Commit
  | 	github.com/cockroachdb/cockroach/pkg/storage/pebble_batch.go:546
  | github.com/cockroachdb/cockroach/pkg/storage.WriteSyncNoop
  | 	github.com/cockroachdb/cockroach/pkg/storage/engine.go:1246
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/liveness.(*NodeLiveness).updateLiveness.func1.1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/liveness/liveness.go:1313
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:341
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/liveness.(*NodeLiveness).updateLiveness.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/liveness/liveness.go:1311
  | github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight.(*Group).doCall
  | 	github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight/singleflight.go:128
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (2) secondary error attachment
  | write ×: stale NFS file handle
  | (1) attached stack trace
  |   -- stack trace:
  |   | github.com/cockroachdb/pebble/vfs.(*syncingFile).Write
  |   | 	github.com/cockroachdb/pebble/vfs/external/com_github_cockroachdb_pebble/vfs/syncing_file.go:68
  |   | github.com/cockroachdb/pebble/record.(*LogWriter).flushPending
  |   | 	github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go:513
  |   | github.com/cockroachdb/pebble/record.(*LogWriter).flushLoop
  |   | 	github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go:453
  |   | runtime/pprof.Do
  |   | 	GOROOT/src/runtime/pprof/runtime.go:40
  |   | github.com/cockroachdb/pebble/record.NewLogWriter.func2
  |   | 	github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go:329
  |   | runtime.goexit
  |   | 	GOROOT/src/runtime/asm_amd64.s:1594
  | Wraps: (2) write ×
  | Wraps: (3) stale NFS file handle
  | Error types: (1) *withstack.withStack (2) *fs.PathError (3) syscall.Errno
Wraps: (3) log.Fatal: write ×: stale NFS file handle
Error types: (1) *withstack.withStack (2) *secondary.withSecondaryError (3) *errutil.leafError
-- report composition:
*errutil.leafError: log.Fatal: write ×: stale NFS file handle
*secondary.withSecondaryError: details for github.com/cockroachdb/errors/withstack/*withstack.withStack:::
db.go:747: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/89df73b7e738a6dd87bf83d891726bb9a317d18f/pkg/util/syncutil/singleflight/singleflight.go#L127-L129](https://github.com/cockroachdb/cockroach/blob/89df73b7e738a6dd87bf83d891726bb9a317d18f/pkg/util/syncutil/singleflight/singleflight.go#L127-L129)
[https://github.com/cockroachdb/cockroach/blob/89df73b7e738a6dd87bf83d891726bb9a317d18f/pkg/kv/kvserver/liveness/liveness.go#L1310-L1312](https://github.com/cockroachdb/cockroach/blob/89df73b7e738a6dd87bf83d891726bb9a317d18f/pkg/kv/kvserver/liveness/liveness.go#L1310-L1312)
[https://github.com/cockroachdb/cockroach/blob/89df73b7e738a6dd87bf83d891726bb9a317d18f/pkg/util/stop/stopper.go#L340-L342](https://github.com/cockroachdb/cockroach/blob/89df73b7e738a6dd87bf83d891726bb9a317d18f/pkg/util/stop/stopper.go#L340-L342)
[https://github.com/cockroachdb/cockroach/blob/89df73b7e738a6dd87bf83d891726bb9a317d18f/pkg/kv/kvserver/liveness/liveness.go#L1312-L1314](https://github.com/cockroachdb/cockroach/blob/89df73b7e738a6dd87bf83d891726bb9a317d18f/pkg/kv/kvserver/liveness/liveness.go#L1312-L1314)
[https://github.com/cockroachdb/cockroach/blob/89df73b7e738a6dd87bf83d891726bb9a317d18f/pkg/storage/engine.go#L1245-L1247](https://github.com/cockroachdb/cockroach/blob/89df73b7e738a6dd87bf83d891726bb9a317d18f/pkg/storage/engine.go#L1245-L1247)
[https://github.com/cockroachdb/cockroach/blob/89df73b7e738a6dd87bf83d891726bb9a317d18f/pkg/storage/pebble_batch.go#L545-L547](https://github.com/cockroachdb/cockroach/blob/89df73b7e738a6dd87bf83d891726bb9a317d18f/pkg/storage/pebble_batch.go#L545-L547)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/batch.go#L1048-L1050](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/batch.go#L1048-L1050)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L746-L748](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L746-L748)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/util/syncutil/singleflight/singleflight.go in pkg/util/syncutil/singleflight.(*Group).doCall at line 128
pkg/kv/kvserver/liveness/liveness.go in pkg/kv/kvserver/liveness.(*NodeLiveness).updateLiveness.func1 at line 1311
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunTaskWithErr at line 341
pkg/kv/kvserver/liveness/liveness.go in pkg/kv/kvserver/liveness.(*NodeLiveness).updateLiveness.func1.1 at line 1313
pkg/storage/engine.go in pkg/storage.WriteSyncNoop at line 1246
pkg/storage/pebble_batch.go in pkg/storage.(*pebbleBatch).Commit at line 546
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/batch.go in github.com/cockroachdb/pebble.(*Batch).Commit at line 1049
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go in github.com/cockroachdb/pebble.(*DB).Apply at line 747
```

### Tags

| Tag | Value |
| --- | --- |
| Command | start-single-node |
| Environment | v22.2.16 |
| Go Version | go1.19.6 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v22.2.16 |
| Cockroach SHA | 89df73b7e738a6dd87bf83d891726bb9a317d18f |
| # of CPUs | 2 |
| # of Goroutines | 280 |

Jira issue: CRDB-33384

**Comment by yuzefovich** [comment]
dup of #86703
