### ISSUE TITLE
multitenant: Remove dropdown from DB Console when on a non-UA cluster

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#114168]
See: https://cockroachlabs.slack.com/archives/C05VAJ5H3QS/p1699495881149839?thread_ts=1699471492.039549&cid=C05VAJ5H3QS

We have a bug where for single-tenant clusters, they see a tenant dropdown menu in the UI. This should not happen.

Jira issue: CRDB-33377

**Comment by dhartunian** [comment]
I cannot reproduce this on latest `release-23.2` branch using a secure cluster and `start-single-node`.

**Comment by amruss** [comment]
Reopening, this is popping back up again: https://cockroachlabs.slack.com/archives/C063CP41TG9/p1701450260389879

**Comment by amruss** [comment]
We're also leaking in the SQL shell: 
![image](https://github.com/cockroachdb/cockroach/assets/13264141/96e44bf3-53e7-4732-a2e2-3106c0240083)

**Comment by dhartunian** [comment]
@amruss do you have a reproduction for this issue? I'm still unable to create a repro on my end. Starting a blank cluster does not show the tenant dropdown, nor does it leak the `system` tenant in the SQL shell. I've tried to play around with my cookie settings to force it to show up when it shouldn't and I can't do that either. If there's a roachprod cluster where this is happening or on some other test cluster, just point me to it and I can try to track it down.

**Comment by celiala** [comment]
removing GA-blocker label as well (as per Slack thread: https://cockroachlabs.slack.com/archives/C063CP41TG9/p1702699835346909?thread_ts=1702681134.189089&cid=C063CP41TG9)

**Comment by dhartunian** [comment]
@amruss is it possible this ticket is regarding the tenant dropdown on the metrics page? I realized the discussion never clarifies what actual UI element is the problem.

Also, if there's a change necessary in the SQL shell, can you file a separate ticket and route to SQL team?
