### ISSUE TITLE
DB Console Transaction Details page Statement Fingerprints table does not aggregate by Application Name

### ISSUE THREAD

**Issue by florence-crl** [cockroachdb/cockroach#114254]
**Describe the problem**

DB Console Transaction Details page Statement Fingerprints table does not aggregate by Application Name.

The Statements page shows the same fingerprint (`select pg_sleep(_)`) run by 3 times each by 2 different applications (`shell1` and `shell2`):

![Screenshot 2023-11-10 at 1 53 06 PM](https://github.com/cockroachdb/cockroach/assets/58752716/309cef55-efac-485a-8ad3-1a759adbb605)

The Transactions page similarly shows the same fingerprint (`select pg_sleep(_)`) run by 3 times each by 2 different applications (`shell1` and `shell2`):

![Screenshot 2023-11-10 at 1 53 30 PM](https://github.com/cockroachdb/cockroach/assets/58752716/35ecb791-24ac-40c8-ad77-1b36dc3d9207)

If you click on the first row (`shell2`) to go to the Transactions details page, you see that Application Name is `shell2`, but in the Statement Fingerprints table on the bottom of the page, you see 1 row with Application Name `shell1` with 6 executions.  This is not what I expected. I expected 1 row with Application Name `shell2` with 3 executions.

![Screenshot 2023-11-10 at 1 53 57 PM](https://github.com/cockroachdb/cockroach/assets/58752716/e14f09b8-f3a0-47af-87bc-37e370d44ff2)

**To Reproduce**

```
# with cockroach-v23.2.0-alpha.6.darwin-11.0-arm64
cockroach start-single-node --http-addr=localhost:8080 --listen-addr=localhost:36257 --sql-addr=localhost:26257 --insecure --background

cockroach sql --insecure --port=26257
#shell1
SET application_name = 'shell1';  -- to distinguish between transactions
select pg_sleep(1); -- odd numbers
select pg_sleep(11); -- odd numbers
select pg_sleep(13); -- odd numbers

cockroach sql --insecure --port=26257
#shell2
SET application_name = 'shell2';  -- to distinguish between transactions
select pg_sleep(2); -- even numbers
select pg_sleep(12); -- even numbers
select pg_sleep(14); -- even numbers
```

**Expected behavior**
In the Transaction Details page, I expected the Statement Fingerprints row Application Name and Execution Count to match the row in the Transactions Overview page that I click on.

**Environment:**
 - CockroachDB version v23.2.0-alpha.6
 - Server OS: mac arm
 - Client app `cockroach sql`

Jira issue: CRDB-33422

**Comment by xinhaoz** [comment]
backport 23.1
