### ISSUE TITLE
Scalar correlated subquery error for more than one rows returned is raised prematurely

### ISSUE THREAD

**Issue by lukaseder** [cockroachdb/cockroach#114227]
**Describe the problem**

Under certain conditions, the optimiser seems to choose to materialise a scalar subquery before correlating it properly, leading to a prematurely raised error:

> SQL Error [21000]: ERROR: more than one row returned by a subquery used as an expression

**To Reproduce**

```sql
create table a (a int not null primary key);
create table b (b int not null references a, x varchar(10) not null);

insert into a values (1),(2),(3);
insert into b values (1, 'x'),(2, 'y'),(3, 'z'),(3, 'a');

select *
from a
where a.a = (select 1)
and (
  select x
  from b
  where b.b = a.a
) = 'x';
```

The fact that there are two rows with `b.b = 3` seems to be the culprit here. Yes, the scalar subquery could raise this error, and it should if the predicate filtered for `a.a = 3`, but it doesn't. For `a.a = 1`, the query should work, and in fact, it does. I had to trick the optimiser with the `a.a = (select 1)` subquery to cause the problem. Using `a.a = ?` (a JDBC bind variable) also reproduces it. There are probably other ways, too.

I'm guessing that the optimiser executes the correlated subquery first, and the more selective predicate second, only.

**Expected behavior**

I'd expect this query to return `1`, as it does on at least MySQL, Oracle, PostgreSQL, SQL Server. The scalar subquery check should be invoked only if it must logically occur from the actual result set.

Perhaps, the optimiser could flag some operation for potentially risky, but raise the error only if the subquery actually does produce multiple rows.

**Environment:**
 - CockroachDB version: CockroachDB CCL v23.1.8 (x86_64-pc-linux-gnu, built 2023/08/04 18:11:44, go1.19.10)
 - Server OS: Linux in Docker
 - Client app: JDBC

Jira issue: CRDB-33407

**Comment by mgartner** [comment]
The optimizer makes no guarantees about specific optimizations occurring, such as the ones you're implying, like evaluating the `a.a = 1` filter and short-circuiting before executing the correlated subquery, or pushing a `b.b = 1` filter into the subquery based on the `a.a = b.b` equality. Providing such guarantees would eliminate many of the freedoms that make the optimizer effective. It would produce worse plans in general if it had to make these kinds of promises. With very few exceptions, it reserves the right to apply or not apply optimizations regardless of the side-effects.

The only sure-fire way to prevent errors in cases like this is to ensure that the subquery will never produce more than one row. There's a number of ways to do this, such as adding a `LIMIT 1` clause or an explicit filter:

```sql
-- Add b.b = (select 1).
select * from a
where a.a = (select 1)
  and (
    select x
    from b
    where b.b = a.a and b.b = (select 1)
  ) = 'x';

-- Or use a CTE.
with s1 as (select 1)
select * from a
where a.a = (select * from s1)
  and (
    select x
    from b
    where b.b = a.a and b.b = (select * from s1)
  ) = 'x';

-- Adding a filter works for prepared statements too.
prepare p as
select * from a
where a.a = $1
  and (
    select x
    from b
    where b.b = a.a and b.b = $1
  ) = 'x';

execute p(1);
```

All that being said, new optimizations have been added in v23.2 that will prevent this error in this specific case, most importantly the changes in #100881.

I'm going to close this, but please let us know if you have further questions.
