### ISSUE TITLE
sql: support COPY ... (ENCODING ...)

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#114200]
Support the ENCODING option for COPY. 

This specifies how the file is encoded. In CRDB, we can only can support 'utf8', so if someone specifies a different encoding, the command should return an error.

https://www.postgresql.org/docs/current/sql-copy.html

See https://github.com/cockroachdb/cockroach/pull/59790 for an example of how to add an option. 

Epic CRDB-18320

Jira issue: CRDB-33390

**Comment by moohbr** [comment]
Hi! Can I take it?

**Comment by moohbr** [comment]
@rafiss

**Comment by rafiss** [comment]
sure, feel free to submit a PR. see these guidelines: https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/73072641

**Comment by jerinthomas1404** [comment]
> @moohbr Are you still working on it?

**Comment by jerinthomas1404** [comment]
@rafiss Can I take up this issue?

**Comment by rafiss** [comment]
sure, feel free to submit a PR! see these guidelines: https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/73072641

**Comment by lpessoa** [comment]
@jerinthomas1404 are you already working on this one?

**Comment by mendaxjerin** [comment]
@lpessoa I haven't started

**Comment by andrew-delph** [comment]
@lpessoa , @mendaxjerin , @jerinthomas1404 ,
Has this task been started?

**Comment by lpessoa** [comment]
> @lpessoa , @mendaxjerin , @jerinthomas1404 ,
> Has this task been started?

I have already started on some code. Already implemented the changes in the grammar file and in the `copy_from` and `copy` (followed the sample provided by @rafiss )

Gonna look at tests next

**Comment by mendaxjerin** [comment]
You can complete it. I'll take up something else
