### ISSUE TITLE
Sentry: memo.go:412: cannot overwrite × / × (92.1966667) with × /  (×)
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/opt/memo...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#114231]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4620709414/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4620709414/?referrer=webhooks_plugin)

Panic Message:

```
memo.go:412: cannot overwrite × / × (92.1966667) with × /  (×)
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*Memo).SetBestProps
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/memo/memo.go:412
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:818
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:803
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:803
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:803
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:803
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:803
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:803
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:803
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).Optimize
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:274
  | github.com/cockroachdb/cockroach/pkg/sql.(*optPlanningCtx).reuseMemo
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:507
  | github.com/cockroachdb/cockroach/pkg/sql.(*optPlanningCtx).buildExecMemo
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:537
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).makeOptimizerPlan
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:240
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).makeExecPlan
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2028
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1537
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1036
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:142
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:3083
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:141
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execPortal
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:247
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2288
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2290
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2105
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:902
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:310
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (3) cannot overwrite × / × (92.1966667) with × /  (×)
Error types: (1) *assert.withAssertionFailure (2) *withstack.withStack (3) *errutil.leafError
-- report composition:
*errutil.leafError: cannot overwrite × / × (92.1966667) with × /  (×)
memo.go:412: *withstack.withStack (top exception)
*assert.withAssertionFailure
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/pgwire/conn.go#L309-L311](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/pgwire/conn.go#L309-L311)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor.go#L901-L903](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor.go#L901-L903)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor.go#L2104-L2106](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor.go#L2104-L2106)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor.go#L2289-L2291](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor.go#L2289-L2291)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor.go#L2287-L2289](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor.go#L2287-L2289)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor_exec.go#L246-L248](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor_exec.go#L246-L248)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor_exec.go#L140-L142](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor_exec.go#L140-L142)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor_exec.go#L3082-L3084](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor_exec.go#L3082-L3084)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor_exec.go#L141-L143](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor_exec.go#L141-L143)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor_exec.go#L1035-L1037](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor_exec.go#L1035-L1037)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor_exec.go#L1536-L1538](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor_exec.go#L1536-L1538)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor_exec.go#L2027-L2029](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor_exec.go#L2027-L2029)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/plan_opt.go#L239-L241](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/plan_opt.go#L239-L241)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/plan_opt.go#L536-L538](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/plan_opt.go#L536-L538)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/plan_opt.go#L506-L508](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/plan_opt.go#L506-L508)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/opt/xform/optimizer.go#L273-L275](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/opt/xform/optimizer.go#L273-L275)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/opt/xform/optimizer.go#L802-L804](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/opt/xform/optimizer.go#L802-L804)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/opt/xform/optimizer.go#L802-L804](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/opt/xform/optimizer.go#L802-L804)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/opt/xform/optimizer.go#L802-L804](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/opt/xform/optimizer.go#L802-L804)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/opt/xform/optimizer.go#L802-L804](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/opt/xform/optimizer.go#L802-L804)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/opt/xform/optimizer.go#L802-L804](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/opt/xform/optimizer.go#L802-L804)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/opt/xform/optimizer.go#L802-L804](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/opt/xform/optimizer.go#L802-L804)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/opt/xform/optimizer.go#L802-L804](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/opt/xform/optimizer.go#L802-L804)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/opt/xform/optimizer.go#L817-L819](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/opt/xform/optimizer.go#L817-L819)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/opt/memo/memo.go#L411-L413](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/opt/memo/memo.go#L411-L413)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommandsAsync.func1 at line 310
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 902
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 2105
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 2290
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd.func2 at line 2288
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execPortal at line 247
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 141
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithProfiling at line 3083
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt.func1 at line 142
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 1036
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchToExecutionEngine at line 1537
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).makeExecPlan at line 2028
pkg/sql/plan_opt.go in pkg/sql.(*planner).makeOptimizerPlan at line 240
pkg/sql/plan_opt.go in pkg/sql.(*optPlanningCtx).buildExecMemo at line 537
pkg/sql/plan_opt.go in pkg/sql.(*optPlanningCtx).reuseMemo at line 507
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).Optimize at line 274
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 803
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 803
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 803
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 803
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 803
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 803
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 803
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 818
pkg/sql/opt/memo/memo.go in pkg/sql/opt/memo.(*Memo).SetBestProps at line 412
```

### Tags

| Tag | Value |
| --- | --- |
| Command | mt start-sql |
| Environment | v23.1.12 |
| Go Version | go1.19.13 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.11-596-gfb1ed73d9d8 |
| Cockroach SHA | fb1ed73d9d88f459c3cda5866fae29831cce06b4 |
| # of CPUs | 32 |
| # of Goroutines | 464 |

Jira issue: CRDB-33409

**Comment by yuzefovich** [comment]
dup of #96225
