### ISSUE TITLE
kv: include locking strength and durability in Get/Scan/RevScan SafeFormat

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#114475]
Similar to some of the other special-casing in `BatchRequest.SafeFormat`, we would benefit from adding locking strength and locking durability for locking Get/Scan/RevScan requests.

We can clean up the code while here as well. One idea is to introduce an optional extension interface for Request types to allow them to perform custom formatting. Something like:
```go
type safeFormatterRequest interface {
	Request
	redact.SafeFormatter
}
```
`BatchRequest.SafeFormat` could use this if available and default to its own formatting if not.

Jira issue: CRDB-33526

**Comment by lyang24** [comment]
> for locking Get/Scan/RevScan requests.
just curious can this be interpreted as only display str and durability when lock strength != None

**Comment by nvanbenschoten** [comment]
Yes, exactly. We don't need to display anything new if lock strength == None.
