### ISSUE TITLE
logstore: sideloaded storage dirs not synced

### ISSUE THREAD

**Issue by pavelkalinnikov** [cockroachdb/cockroach#114411]
The filesystem metadata for the sideloaded storage (sub-)directories is not synced when [files](https://github.com/cockroachdb/cockroach/blob/3c05e281fb93b566b781fa0b645dd0104335f4d4/pkg/kv/kvserver/logstore/sideload_disk.go#L100) or [directories](https://github.com/cockroachdb/cockroach/blob/3c05e281fb93b566b781fa0b645dd0104335f4d4/pkg/kv/kvserver/logstore/sideload_disk.go#L80) are added or removed. The sideloaded files are then used as raft log entries, and are required to be accessible. Safety properties of raft depend on the durability of these files.

However, in presence of power outages, or OS crashes, not syncing the filesystem can lead to losing these files.

Example "data loss" I observed in a minimal unit-test using the [strict](https://github.com/cockroachdb/pebble/blob/124486b0f85d75a0c695cb65703c5495eec66c99/vfs/mem_fs.go#L33-L56) `vfs.MemFS` in-memory testing file system.

<details>
<summary>Before crash</summary>

```
    5801    000002.log
      37    000005.log
     115    000006.log
    2946    000008.sst
      16    CURRENT
       0    LOCK
     350    MANIFEST-000001
    2554    OPTIONS-000003
      10    STORAGE_MIN_VERSION
            auxiliary/
              sideloading/       * this entire substructure
                r0XXXX/          * is not synced up to auxiliary directory
                  r68/           * so it can be lost on crash
    1012            i23.t6       * and it does so below
              sstsnapshot/
       0    marker.format-version.000015.016
       0    marker.manifest.000001.MANIFEST-000001
```

</details>

<details>
<summary>After crash</summary>

```
    5730    000002.log
      16    CURRENT
       0    LOCK
      46    MANIFEST-000001
    2554    OPTIONS-000003
      10    STORAGE_MIN_VERSION
            auxiliary/
       0    marker.format-version.000015.016
       0    marker.manifest.000001.MANIFEST-000001
```

</details>

Jira issue: CRDB-33498

**Comment by erikgrinaker** [comment]
Should this really be a blocker? This is a pre-existing bug that's been there forever afaik.

**Comment by pavelkalinnikov** [comment]
This is done and backported to `23.2`. Still need to backport to `23.1` and `22.2`, but leaving to bake in `master` and `23.2` first. So leaving this open for now.

**Comment by erikgrinaker** [comment]
We usually don't leave the issue open once it's fixed on `master` and the current release branch, but I'll leave that to you.

**Comment by pavelkalinnikov** [comment]
Ah ok, thanks for the clarification. Closing this, and will backport asynchronously.
