### ISSUE TITLE
Sentry: sequence.go:366: no table name found to match input ×
(1)
Wraps: (2) assertion failure
Wraps: (3) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/s...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#114463]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4634583489/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4634583489/?referrer=webhooks_plugin)

Panic Message:

```
sequence.go:366: no table name found to match input ×
(1)
Wraps: (2) assertion failure
Wraps: (3) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/seqexpr.findUniqueBestMatchingForTableName
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/seqexpr/sequence.go:366
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/seqexpr.seqNameToIDMappingInExpr
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/seqexpr/sequence.go:291
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/seqexpr.UpgradeSequenceReferenceInExpr
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/seqexpr/sequence.go:225
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/tabledesc.maybeUpgradeSequenceReferenceForTable
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/tabledesc/table_desc_builder.go:903
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/tabledesc.maybeUpgradeSequenceReference
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/tabledesc/table_desc_builder.go:860
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/tabledesc.(*tableDescriptorBuilder).RunRestoreChanges
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/tabledesc/table_desc_builder.go:166
  | github.com/cockroachdb/cockroach/pkg/ccl/backupccl.maybeUpgradeDescriptors
  | 	github.com/cockroachdb/cockroach/pkg/ccl/backupccl/restore_planning.go:784
  | github.com/cockroachdb/cockroach/pkg/ccl/backupccl.doRestorePlan
  | 	github.com/cockroachdb/cockroach/pkg/ccl/backupccl/restore_planning.go:1669
  | github.com/cockroachdb/cockroach/pkg/ccl/backupccl.restorePlanHook.func2
  | 	github.com/cockroachdb/cockroach/pkg/ccl/backupccl/restore_planning.go:1174
  | github.com/cockroachdb/cockroach/pkg/sql.(*hookFnNode).startExec.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/planhook.go:199
  | runtime.goexit
  | 	src/runtime/asm_arm64.s:1172
Wraps: (4) no table name found to match input ×
Error types: (1) *colexecerror.notInternalError (2) *assert.withAssertionFailure (3) *withstack.withStack (4) *errutil.leafError
-- report composition:
*errutil.leafError: no table name found to match input ×
sequence.go:366: *withstack.withStack (top exception)
*assert.withAssertionFailure
*colexecerror.notInternalError
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_arm64.s#L1171-L1173](src/runtime/asm_arm64.s#L1171-L1173)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/planhook.go#L198-L200](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/planhook.go#L198-L200)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/ccl/backupccl/restore_planning.go#L1173-L1175](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/ccl/backupccl/restore_planning.go#L1173-L1175)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/ccl/backupccl/restore_planning.go#L1668-L1670](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/ccl/backupccl/restore_planning.go#L1668-L1670)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/ccl/backupccl/restore_planning.go#L783-L785](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/ccl/backupccl/restore_planning.go#L783-L785)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/catalog/tabledesc/table_desc_builder.go#L165-L167](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/catalog/tabledesc/table_desc_builder.go#L165-L167)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/catalog/tabledesc/table_desc_builder.go#L859-L861](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/catalog/tabledesc/table_desc_builder.go#L859-L861)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/catalog/tabledesc/table_desc_builder.go#L902-L904](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/catalog/tabledesc/table_desc_builder.go#L902-L904)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/catalog/seqexpr/sequence.go#L224-L226](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/catalog/seqexpr/sequence.go#L224-L226)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/catalog/seqexpr/sequence.go#L290-L292](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/catalog/seqexpr/sequence.go#L290-L292)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/catalog/seqexpr/sequence.go#L365-L367](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/sql/catalog/seqexpr/sequence.go#L365-L367)
</details>

```
src/runtime/asm_arm64.s in runtime.goexit at line 1172
pkg/sql/planhook.go in pkg/sql.(*hookFnNode).startExec.func1 at line 199
pkg/ccl/backupccl/restore_planning.go in pkg/ccl/backupccl.restorePlanHook.func2 at line 1174
pkg/ccl/backupccl/restore_planning.go in pkg/ccl/backupccl.doRestorePlan at line 1669
pkg/ccl/backupccl/restore_planning.go in pkg/ccl/backupccl.maybeUpgradeDescriptors at line 784
pkg/sql/catalog/tabledesc/table_desc_builder.go in pkg/sql/catalog/tabledesc.(*tableDescriptorBuilder).RunRestoreChanges at line 166
pkg/sql/catalog/tabledesc/table_desc_builder.go in pkg/sql/catalog/tabledesc.maybeUpgradeSequenceReference at line 860
pkg/sql/catalog/tabledesc/table_desc_builder.go in pkg/sql/catalog/tabledesc.maybeUpgradeSequenceReferenceForTable at line 903
pkg/sql/catalog/seqexpr/sequence.go in pkg/sql/catalog/seqexpr.UpgradeSequenceReferenceInExpr at line 225
pkg/sql/catalog/seqexpr/sequence.go in pkg/sql/catalog/seqexpr.seqNameToIDMappingInExpr at line 291
pkg/sql/catalog/seqexpr/sequence.go in pkg/sql/catalog/seqexpr.findUniqueBestMatchingForTableName at line 366
```

### Tags

| Tag | Value |
| --- | --- |
| Command | start-single-node |
| Environment | v22.2.6 |
| Go Version | go1.19.4 |
| Platform | linux arm64 |
| Distribution | CCL |
| Cockroach Release | v22.2.6 |
| Cockroach SHA | d5a076f2953c0712193b8cbe08bbb682563c5675 |
| # of CPUs | 4 |
| # of Goroutines | 320 |

Jira issue: CRDB-33520

**Comment by yuzefovich** [comment]
dup of #93465
