### ISSUE TITLE
Sentry: encoding.go:842: error in argument for ×: unsupported OID 100133 with format code FormatText
(1) candidate pg code: 08P01
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cock...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#114536]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4637757925/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4637757925/?referrer=webhooks_plugin)

Panic Message:

```
encoding.go:842: error in argument for ×: unsupported OID 100133 with format code FormatText
(1) candidate pg code: 08P01
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execBind.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:480
  | [...repeated from below...]
Wraps: (3) error in argument for ×
Wraps: (4) assertion failure
Wraps: (5) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire/pgwirebase.DecodeDatum
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/pgwirebase/encoding.go:842
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execBind.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:472
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execBind
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:489
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2321
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2105
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:902
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:310
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (6) unsupported OID 100133 with format code FormatText
Error types: (1) *pgerror.withCandidateCode (2) *withstack.withStack (3) *errutil.withPrefix (4) *assert.withAssertionFailure (5) *withstack.withStack (6) *errutil.leafError
-- report composition:
*errutil.leafError: unsupported OID 100133 with format code FormatText
encoding.go:842: *withstack.withStack (top exception)
*assert.withAssertionFailure
*errutil.withPrefix: error in argument for ×
conn_executor_prepare.go:480: *withstack.withStack (1)
*pgerror.withCandidateCode: 08P01
(check the extra data payloads)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/pgwire/conn.go#L309-L311](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/pgwire/conn.go#L309-L311)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor.go#L901-L903](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor.go#L901-L903)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor.go#L2104-L2106](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor.go#L2104-L2106)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor.go#L2320-L2322](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor.go#L2320-L2322)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor_prepare.go#L488-L490](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor_prepare.go#L488-L490)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor_prepare.go#L479-L481](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor_prepare.go#L479-L481)
[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/pgwire/conn.go#L309-L311](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/pgwire/conn.go#L309-L311)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor.go#L901-L903](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor.go#L901-L903)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor.go#L2104-L2106](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor.go#L2104-L2106)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor.go#L2320-L2322](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor.go#L2320-L2322)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor_prepare.go#L488-L490](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor_prepare.go#L488-L490)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor_prepare.go#L471-L473](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor_prepare.go#L471-L473)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/pgwire/pgwirebase/encoding.go#L841-L843](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/pgwire/pgwirebase/encoding.go#L841-L843)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommandsAsync.func1 at line 310
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 902
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 2105
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 2321
pkg/sql/conn_executor_prepare.go in pkg/sql.(*connExecutor).execBind at line 489
pkg/sql/conn_executor_prepare.go in pkg/sql.(*connExecutor).execBind.func2 at line 480
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommandsAsync.func1 at line 310
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 902
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 2105
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 2321
pkg/sql/conn_executor_prepare.go in pkg/sql.(*connExecutor).execBind at line 489
pkg/sql/conn_executor_prepare.go in pkg/sql.(*connExecutor).execBind.func2 at line 472
pkg/sql/pgwire/pgwirebase/encoding.go in pkg/sql/pgwire/pgwirebase.DecodeDatum at line 842
```

### Tags

| Tag | Value |
| --- | --- |
| Command | mt start-sql |
| Environment | v23.1.12 |
| Go Version | go1.19.13 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.11-596-gfb1ed73d9d8 |
| Cockroach SHA | fb1ed73d9d88f459c3cda5866fae29831cce06b4 |
| # of CPUs | 32 |
| # of Goroutines | 296 |

Jira issue: CRDB-33549

**Comment by yuzefovich** [comment]
dup of #113723
