### ISSUE TITLE
roachtest: properly set `CompatibleClouds` on tests that specify a zone

### ISSUE THREAD

**Issue by renatolabs** [cockroachdb/cockroach#114524]
Some tests are only meant to run on AWS but are still scheduled to run on GCP due to previous limitations in roachtest (#104029). In particular, if the test specifies a region (AWS-specific), it leads to deterministic "cluster creation errors" since the region name will be invalid.

Recent example: https://github.com/cockroachdb/cockroach/issues/108629#issuecomment-1813220904

Now that we have the ability, we should be setting the `CompatibleClouds` field on these tests to the proper cloud.

Jira issue: CRDB-33545

**Comment by renatolabs** [comment]
This is still a quick win, but blocked by the removal of the requirement that `TestSpec.Suite` is compatible with `TestSpec.Tags`: we might remove the requirement, or tags altogether.

[Internal thread](https://cockroachlabs.slack.com/archives/C01UDP33CCS/p1701291424395749).

**Comment by srosenberg** [comment]
Partially fixed by https://github.com/cockroachdb/cockroach/pull/115997
