### ISSUE TITLE
backupccl: follower reads not considered during distsql planning

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#114528]
During DistSQL planning the `followerReadOracle` is only picked under some conditions outlined over here - https://github.com/cockroachdb/cockroach/blob/cf5c2caa84c635acbc22e73c8f2db35aa9de6c71/pkg/ccl/kvccl/kvfollowerreadsccl/followerreads.go#L196-L196. One of the conditions is `txn != nil`. Both backup and changefeed do not plan their DistSQL flows in the scope of a txn, and so pass in nil txns to `dsp. SetupAllNodesPlanningWithOracle`. This means that we always pick the `binPackingOracle` instead that prefers leaseholders - https://github.com/cockroachdb/cockroach/blob/3111a55e91dba9a88931fda725b767163c981ae7/pkg/sql/physicalplan/replicaoracle/oracle.go#L270.

When a backup is run with execution locality it constrains the execution and planning of the backup to only the nodes in the specified region. If the user has configured the backup to run in a non-primary region with follower replicas, we should be picking these replicas instead of reaching out to the leaseholders in the primary region. This way users can avoid backups interfering with foreground traffic. This is not likely today because of our inability to use the `followerReadOracle`.

The likely fix for this bug is to plumb a timestamp or txn from backup, cdc flow planning to where we can decide to use follower reads or not. 

Jira issue: CRDB-33547

**Comment by jayshrivastava** [comment]
@adityamaru Can we close this issue? 

We have https://github.com/cockroachdb/cockroach/issues/114611 to track this on the CDC side. Bulk supports follower reads now. https://github.com/cockroachdb/cockroach/pull/114710

**Comment by dt** [comment]
re-opening until backports merge.
