### ISSUE TITLE
ccl/streamingcc/streamingest: flake in TestStreamingMismatchedMRDatabase

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#114669]
Seen [in CI](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/12730208?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true) on a [backport PR to `release-23.2`](https://github.com/cockroachdb/cockroach/pull/114630). The error is: 

```
testutils.go:259: error scanning '&{0xc0081e4480 <nil>}': pq: replicated tenant "destination" (2) has not yet recorded a retained timestamp
    panic.go:522: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/9123429c6af248433c654f2266a4ee8c/logTestStreamingMismatchedMRDatabase3032403816
--- FAIL: TestStreamingMismatchedMRDatabase (10.76s)
```

Jira issue: CRDB-33617

**Comment by yuzefovich** [comment]
Hit it too on a backport [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=12736845&buildTypeId=Cockroach_BazelEssentialCi)
