### ISSUE TITLE
Sentry: types.go:1130: tuple contents and labels must be of same length: [], [×]
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/t...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#114635]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4641361643/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4641361643/?referrer=webhooks_plugin)

Panic Message:

```
types.go:1130: tuple contents and labels must be of same length: [], [×]
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/types.MakeLabeledTuple
  | 	github.com/cockroachdb/cockroach/pkg/sql/types/pkg/sql/types/types.go:1130
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.typeCheckSameTypedTupleExprs
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/type_check.go:2637
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.TypeCheckSameTypedExprs
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/type_check.go:2360
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*IfErrExpr).TypeCheck
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/type_check.go:1249
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.TypeCheck
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/type_check.go:273
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*scope).resolveType
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scope.go:468
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).analyzeSelectList
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/project.go:161
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).analyzeProjectionList
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/project.go:95
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildSelectClause
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:1071
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildSelectStmtWithoutParens
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:1008
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildSelect.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:977
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).processWiths
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/with.go:117
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildSelect
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:976
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:316
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmtAtRoot
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:256
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).Build
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:230
  | github.com/cockroachdb/cockroach/pkg/sql.(*optPlanningCtx).buildExecMemo
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:561
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).makeOptimizerPlan
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:232
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).makeExecPlan
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1475
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1086
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:694
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:131
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2440
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:130
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2129
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2133
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2054
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:882
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:769
  | runtime.goexit
  | 	src/runtime/asm_arm64.s:1172
Wraps: (3) tuple contents and labels must be of same length: [], [×]
Error types: (1) *assert.withAssertionFailure (2) *withstack.withStack (3) *errutil.leafError
-- report composition:
*errutil.leafError: tuple contents and labels must be of same length: [], [×]
types.go:1130: *withstack.withStack (top exception)
*assert.withAssertionFailure
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_arm64.s#L1171-L1173](src/runtime/asm_arm64.s#L1171-L1173)
[https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/pgwire/conn.go#L768-L770](https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/pgwire/conn.go#L768-L770)
[https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/conn_executor.go#L881-L883](https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/conn_executor.go#L881-L883)
[https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/conn_executor.go#L2053-L2055](https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/conn_executor.go#L2053-L2055)
[https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/conn_executor.go#L2132-L2134](https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/conn_executor.go#L2132-L2134)
[https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/conn_executor.go#L2128-L2130](https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/conn_executor.go#L2128-L2130)
[https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/conn_executor_exec.go#L129-L131](https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/conn_executor_exec.go#L129-L131)
[https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/conn_executor_exec.go#L2439-L2441](https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/conn_executor_exec.go#L2439-L2441)
[https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/conn_executor_exec.go#L130-L132](https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/conn_executor_exec.go#L130-L132)
[https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/conn_executor_exec.go#L693-L695](https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/conn_executor_exec.go#L693-L695)
[https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/conn_executor_exec.go#L1085-L1087](https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/conn_executor_exec.go#L1085-L1087)
[https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/conn_executor_exec.go#L1474-L1476](https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/conn_executor_exec.go#L1474-L1476)
[https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/plan_opt.go#L231-L233](https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/plan_opt.go#L231-L233)
[https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/plan_opt.go#L560-L562](https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/plan_opt.go#L560-L562)
[https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/opt/optbuilder/builder.go#L229-L231](https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/opt/optbuilder/builder.go#L229-L231)
[https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/opt/optbuilder/builder.go#L255-L257](https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/opt/optbuilder/builder.go#L255-L257)
[https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/opt/optbuilder/builder.go#L315-L317](https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/opt/optbuilder/builder.go#L315-L317)
[https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/opt/optbuilder/select.go#L975-L977](https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/opt/optbuilder/select.go#L975-L977)
[https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/opt/optbuilder/with.go#L116-L118](https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/opt/optbuilder/with.go#L116-L118)
[https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/opt/optbuilder/select.go#L976-L978](https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/opt/optbuilder/select.go#L976-L978)
[https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/opt/optbuilder/select.go#L1007-L1009](https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/opt/optbuilder/select.go#L1007-L1009)
[https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/opt/optbuilder/select.go#L1070-L1072](https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/opt/optbuilder/select.go#L1070-L1072)
[https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/opt/optbuilder/project.go#L94-L96](https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/opt/optbuilder/project.go#L94-L96)
[https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/opt/optbuilder/project.go#L160-L162](https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/opt/optbuilder/project.go#L160-L162)
[https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/opt/optbuilder/scope.go#L467-L469](https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/opt/optbuilder/scope.go#L467-L469)
[https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/sem/tree/type_check.go#L272-L274](https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/sem/tree/type_check.go#L272-L274)
[https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/sem/tree/type_check.go#L1248-L1250](https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/sem/tree/type_check.go#L1248-L1250)
[https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/sem/tree/type_check.go#L2359-L2361](https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/sem/tree/type_check.go#L2359-L2361)
[https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/sem/tree/type_check.go#L2636-L2638](https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/sem/tree/type_check.go#L2636-L2638)
[https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/types/pkg/sql/types/types.go#L1129-L1131](https://github.com/cockroachdb/cockroach/blob/c9cdbe4417ec387382cf6c0edafee51b3d58e278/pkg/sql/types/pkg/sql/types/types.go#L1129-L1131)
</details>

```
src/runtime/asm_arm64.s in runtime.goexit at line 1172
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommandsAsync.func1 at line 769
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 882
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 2054
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 2133
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd.func1 at line 2129
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 130
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithProfiling at line 2440
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt.func1 at line 131
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 694
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchToExecutionEngine at line 1086
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).makeExecPlan at line 1475
pkg/sql/plan_opt.go in pkg/sql.(*planner).makeOptimizerPlan at line 232
pkg/sql/plan_opt.go in pkg/sql.(*optPlanningCtx).buildExecMemo at line 561
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).Build at line 230
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).buildStmtAtRoot at line 256
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).buildStmt at line 316
pkg/sql/opt/optbuilder/select.go in pkg/sql/opt/optbuilder.(*Builder).buildSelect at line 976
pkg/sql/opt/optbuilder/with.go in pkg/sql/opt/optbuilder.(*Builder).processWiths at line 117
pkg/sql/opt/optbuilder/select.go in pkg/sql/opt/optbuilder.(*Builder).buildSelect.func1 at line 977
pkg/sql/opt/optbuilder/select.go in pkg/sql/opt/optbuilder.(*Builder).buildSelectStmtWithoutParens at line 1008
pkg/sql/opt/optbuilder/select.go in pkg/sql/opt/optbuilder.(*Builder).buildSelectClause at line 1071
pkg/sql/opt/optbuilder/project.go in pkg/sql/opt/optbuilder.(*Builder).analyzeProjectionList at line 95
pkg/sql/opt/optbuilder/project.go in pkg/sql/opt/optbuilder.(*Builder).analyzeSelectList at line 161
pkg/sql/opt/optbuilder/scope.go in pkg/sql/opt/optbuilder.(*scope).resolveType at line 468
pkg/sql/sem/tree/type_check.go in pkg/sql/sem/tree.TypeCheck at line 273
pkg/sql/sem/tree/type_check.go in pkg/sql/sem/tree.(*IfErrExpr).TypeCheck at line 1249
pkg/sql/sem/tree/type_check.go in pkg/sql/sem/tree.TypeCheckSameTypedExprs at line 2360
pkg/sql/sem/tree/type_check.go in pkg/sql/sem/tree.typeCheckSameTypedTupleExprs at line 2637
pkg/sql/types/pkg/sql/types/types.go in pkg/sql/types.MakeLabeledTuple at line 1130
```

### Tags

| Tag | Value |
| --- | --- |
| Command | start-single-node |
| Environment | v22.2.13 |
| Go Version | go1.19.6 |
| Platform | darwin arm64 |
| Distribution | CCL |
| Cockroach Release | v22.2.13 |
| Cockroach SHA | c9cdbe4417ec387382cf6c0edafee51b3d58e278 |
| # of CPUs | 10 |
| # of Goroutines | 358 |

Jira issue: CRDB-33604

**Comment by yuzefovich** [comment]
fixed later
