### ISSUE TITLE
sql: stored procedures should be explainable

### ISSUE THREAD

**Issue by DrewKimball** [cockroachdb/cockroach#114674]
Currently, it is not possible to view the plan of a stored procedure call, or to collect a statement bundle for one:
```
root@localhost:26257/system/defaultdb> explain analyze (debug) call arr_var();
ERROR: statement ignored: at or near "call": syntax error
SQLSTATE: 42601
DETAIL: source SQL:
explain analyze (debug) call arr_var()
                        ^
HINT: try \h <SELECTCLAUSE>
root@localhost:26257/system/defaultdb> explain call arr_var();
ERROR: statement ignored: at or near "call": syntax error
SQLSTATE: 42601
DETAIL: source SQL:
explain call arr_var()
        ^
HINT: try \h EXPLAIN
```
Postgres doesn't allow explaining a CALL statement either, but it seems worth it to remove this limitation anyway, since otherwise it's a pretty large gap in observability.

Jira issue: CRDB-33619

**Comment by michae2** [comment]
Observability of stored procedures came up during our team premortem, so tagging this and bumping up the priority.
