### ISSUE TITLE
Database recommendations icon surfaces “Encountered Network errors”

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#114689]
On our scale testing cluster, the database recommendations icon surfaces “Encountered Network errors” for the KV and System Database.

Visit the Databases page on our scale cluster and notice the following:

<img width="710" alt="image" src="https://github.com/cockroachdb/cockroach/assets/81193618/95a99ec8-0e45-4e67-a12f-2d1f62f648f8">

Jira issue: CRDB-33629

**Comment by xinhaoz** [comment]
Closing with followups: https://github.com/cockroachdb/cockroach/issues/120064
