### ISSUE TITLE
roachtest: temporarily disable assertions & add `B-metamorphic`, `B-coverage` labels

### ISSUE THREAD

**Issue by srosenberg** [cockroachdb/cockroach#114615]
As of [1], roughly half of the nightly roachtests are executed with a binary which was built with the `crdb_test` tag. This enables extensive and sometimes expensive assertion/invariant checking _as well as_ metamorphic constants/settings. Inevitably, some of the metamoprhic settings and expensive assertions have resulted in an uptick of roachtest flakes. After the discussion in [2], the team decided to disable assertions until after the 23.2 stability period.

Furthermore, in order to easily differentiate between test failure modes, we will add `B-metamorphic` and `B-coverage` labels; see [3] for the definition of label prefixes.

[1] https://github.com/cockroachdb/cockroach/pull/111949
[2] https://cockroachlabs.slack.com/archives/C0366GQV668/p1700158481517979
[3] https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/122060807/GitHub+Issue+Labels

Jira issue: CRDB-33599

**Comment by renatolabs** [comment]
Closing this, as I believe all of the changes proposed in the issue description have been merged at this point.
