### ISSUE TITLE
Cannot Refresh SQL Activity "Active executions"

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#114691]
Use our scale testing cluster, navigate to the SQL Activity page, toggle to Active Executions, and attempt to click the Refresh button:

<img width="1007" alt="image" src="https://github.com/cockroachdb/cockroach/assets/81193618/378c323c-4ab6-45b9-b4fa-f148e721ca13">

Jira issue: CRDB-33631

**Comment by maryliag** [comment]
to clarify: the refresh does work, is just the cursor that is not using pointer, so make it look like to not clickable, but when clicking the data gets refreshed as expected
