### ISSUE TITLE
intrusion/server: filter destination clusters that are locked in the x-cluster restore modal

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#114799]
Currently we do not filter out clusters that are locked by an ongoing operation in the restore modal picker during a x-cluster restore. This can allow users to kickoff another cluster restore while a previous restore has left the cluster in a bad state. Doing so could interfere with cluster state making it impossible for the first restore to cleanly revert on failure.

1. We should double check where we take a lock so as to prevent a concurrent cluster restore from running _any_ operations before acquiring a lock.

2. We should add more filters to what clusters we display in the restore modal.

Jira issue: CRDB-33686

**Comment by benbardin** [comment]
we track cloud issues in JIRA
