### ISSUE TITLE
Support json for --format flag in cockroach sql

### ISSUE THREAD

**Issue by dikshant** [cockroachdb/cockroach#114762]
cockroach sql supports --format flag that outputs to csv, tsv, tables, raw etc. We should add a json option to output json. 

For now this can be workaround by using csv/tsv and using a csv/tsv tool to redirect output.

Jira issue: CRDB-33665

**Comment by rafiss** [comment]
We do have the `ndjson` format, but it wasn't added to the help text: https://github.com/cockroachdb/cockroach/pull/77808

I will add it.

**Comment by rafiss** [comment]
This is the docs issue: https://github.com/cockroachdb/docs/issues/16964
