### ISSUE TITLE
mixedversion: support setting certain cluster settings randomly

### ISSUE THREAD

**Issue by renatolabs** [cockroachdb/cockroach#114723]
It would be a good feature to support randomly setting certain cluster settings that are expected to have no impact on _most_ tests. Settings would be introduced at a random point in the test (whenever they are available) and could optionally be unset as well.

One example of such setting is `kv.expiration_leases_only.enabled` (see #112226). Tests would have the option to disable this behaviour of the test if what it does is incompatible with the cluster setting.

### Other options considered:

* **Making this a roachtest default behaviour**: this would be ideal (as it would apply to every test, not just mixedversion tests). In fact, there's already an API to do this for the expiration-based leases mentioned above (see `TestSpec.ExpirationLeases`). However, roachtest does not currently have the notion of "version" when starting cockroach processes. As a consequence, we can't reliably use that API since the version we are starting might not support the cluster setting.

* **Relying on metamorphic builds of cockroach**: This should eventually be supported, but there's still work to be done to fully integrate metamorphic builds in regular roachtest runs. Supporting them in mixedversion is still in the more distant future, so it will be nice to have something that works until we get there.

Jira issue: CRDB-33654

**Comment by srosenberg** [comment]
This might belong to a separate issue, but it appears that we may want to have a dedicated API for setting cluster settings, random or not. This would prevent user errors like the one fixed in [1].

[1] https://github.com/cockroachdb/cockroach/pull/117236#issue-2062449817
