### ISSUE TITLE
sql: ignore trailing whitespace in varchar

### ISSUE THREAD

**Issue by rharding6373** [cockroachdb/cockroach#114862]
Repro:
```
CREATE TEMP TABLE VARCHAR_TBL(f1 varchar(1));
INSERT INTO VARCHAR_TBL (f1) VALUES ('c     '); -- succeeds in postgres
-- ERROR:  value too long for type VARCHAR(1) 
```

It appears that postgres does not allow whitespace preceeding or between characters, but ignores trailing whitespace when more characters than the varchar size are provided.

Found in pg_regress varchar

Jira issue: CRDB-33723

**Comment by chanYe-EAST** [comment]
Hi, I have created a draft PR to address this issue.

I referenced the [Postgres code](https://github.com/postgres/postgres/blob/d053a879bb360fb72c46de2a013e741d3f7c9e8d/src/backend/utils/adt/varchar.c#L465-L481) and now it seems to work the same as in Postgres.

```
INSERT INTO VARCHAR_TBL (f1) VALUES ('c     ');
INSERT 0 1
--- postgres=# INSERT INTO VARCHAR_TBL (f1) VALUES ('c     ');
--- INSERT 0 1

INSERT INTO VARCHAR_TBL (f1) VALUES (e'c\u0020');
INSERT 0 1
--- postgres=# INSERT INTO VARCHAR_TBL (f1) VALUES (e'c\u0020');
--- INSERT 0 1

INSERT INTO VARCHAR_TBL (f1) VALUES (e'\uAC01 ');
INSERT 0 1
--- postgres=# INSERT INTO VARCHAR_TBL (f1) VALUES (e'\uAC01 ');
--- INSERT 0 1
```

However, I'm not sure if it can simply be handled in one line using the `strings.TrimRight()`. If that is allowed, it would be a better choice.

Could you please review this PR?
