### ISSUE TITLE
multi-tenant: performance test multiple shared-process tenant side-by-side

### ISSUE THREAD

**Issue by ajstorm** [cockroachdb/cockroach#114864]
We don't have a good feel for how multiple workloads will behave when run side-by-side in shared-process tenants.  We should test this so that we have a better feel for how it'll work if/when customers get into this situation.

Epic: CRDB-31933

Jira issue: CRDB-41678

**Comment by stevendanna** [comment]
I'm going to close this for now. This is worth re-opening if we ever choose to prioritise fuller multi-tenant support.
