### ISSUE TITLE
sql: include distsql diagrams for statements within routine 

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#114827]
Consider the following statements:

```sql
CREATE TABLE t (a INT, b INT);
CREATE TABLE p (a INT PRIMARY KEY, b INT);
CREATE TABLE c (a INT REFERENCES p(a), b INT);

CREATE FUNCTION f(INT, INT) RETURNS VOID AS $$
  INSERT INTO t VALUES ($1, $2);
  INSERT INTO c VALUES ($1, $2);
$$ LANGUAGE SQL;

INSERT INTO p VALUES (1, 10);

-- Collect a statement bundle for a query that runs a function once.
EXPLAIN ANALYZE (DEBUG) SELECT f(1, 20);
```

Currently, the created statement bundle only include a single distsql diagram for the `SELECT` statement, but no additional diagrams for the `INSERT` statements that are also executed. I expect them to be included, like we do for apply-joins. This would give us visibility into the optimized plans for each invocation of the function.

Jira issue: CRDB-33703
Epic CRDB-34181

**Comment by yuzefovich** [comment]
Distsql diagrams for each "plan" within each function invocation are already included into `trace.txt` and `trace-jaeger.json` files (similar to apply joins). I do have a minor improvement to include the stringified expression that corresponds to each stmt in the routine as the SQL string in the diagram. Will send a patch shortly and we can discuss there.
