### ISSUE TITLE
schemachanger: split and scatter before index is being backfilled or written to

### ISSUE THREAD

**Issue by Xiang-Gu** [cockroachdb/cockroach#114996]
In https://github.com/cockroachdb/cockroach/pull/94703, we added split and scatter calls in declarative schema changer when creating a new index (primary, secondary, or temporary) before it's backfilled or written to. One question is [here](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/schemachanger/scexec/exec_deferred_mutation.go#L206-L208) which further leads to [this block of code](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/index_split_scatter.go#L53-L62). The code begs a few questions:
1. Why is temporary index excluded from being splitted and scattered?
2. Why do we only call split without following up with a scatter call?
3. Why do we choose to only split at the beginning of the index span? Is it enough?

@kvoli and I recently sit down to look at the behavior of `ALTER TABLE ADD COLUMN` in the scale cluster that sparked those questions. It seems 
1. temporary index shouldn't be excluded (and it won't hurt too much to also split&scatter on temporary indexes) bc in a real cluster the concurrent writes that go to a temporary index (when new primary index is being backfilled) can be also large; 
2. it's just wrong to call only split but not scatter afterwards; 
3. for temporary indexes, we don't know how large its index span will be (it will be whatever concurrent writes are). Understandably, we don't know where and how many time to split, so it is fair to just split it once at the beginning of index span (better than not splitting at all at least).

cc @fqazi we'd like to hear your thoughts too

Jira issue: CRDB-33830

Epic CRDB-37763

**Comment by nvanbenschoten** [comment]
> for temporary indexes, we don't know how large its index span will be (it will be whatever concurrent writes are). Understandably, we don't know where and how many time to split, so it is fair to just split it once at the beginning of index span (better than not splitting at all at least).

Splitting off the index into a single range is not going to accomplish very much. It will still lead to a consolidation of the workload onto a single node, which can be pretty catastrophic at scale.

We could take inspiration from `TRUNCATE`, which has a similar problem and solves this by sampling the splits of the original index and choosing and amount proportional to the number of nodes in the cluster. See `copySplitPointsToNewIndexes` and `PreservedSplitCountMultiple`.

**Comment by Xiang-Gu** [comment]
I'd like to add more info about repro and impact of this issue with a few metrics to help triage the severity of this issue and its prioritization.

### Repro
The issue was first observed on the `seanc-crdb23210tb` cluster which has over 3TiB data in one table (the `kv.kv` table) and is running the `kv` workload with ~34K QPS (half reads, half writes)
<img width="1661" alt="Screenshot 2023-11-27 at 3 57 32 PM" src="https://github.com/cockroachdb/cockroach/assets/36337582/1203648a-079c-49bf-8cc4-9675752ecc02">
<img width="971" alt="Screenshot 2023-11-27 at 3 56 13 PM" src="https://github.com/cockroachdb/cockroach/assets/36337582/029c58ee-d0ab-4858-9ce4-985fc7eefb08">
On such a cluster with heavy foreground traffic (especially high write traffic) and on such a huge table, if we perform 
```
ALTER TABLE kv.public.kv ADD COLUMN expire_ttl TIMESTAMPTZ DEFAULT statement_timestamp() - '7 days'
```
below are impact we are going to observe while this `ADD COLUMN` is running (btw, it took 25h to finish).

### Impact
1. Foreground QPS drop (drops to 1/6 of before)
<img width="968" alt="Screenshot 2023-11-27 at 3 19 22 PM" src="https://github.com/cockroachdb/cockroach/assets/36337582/3db9780e-8830-4fb3-99dd-3f285ef19ffd">

2. Storage flushes (3 out of 12 nodes see significant higher flushes -- implying more writes happen to those 3 nodes)
<img width="968" alt="Screenshot 2023-11-27 at 3 49 20 PM" src="https://github.com/cockroachdb/cockroach/assets/36337582/17ac9348-e8af-45d9-9e62-c6f88b81189f">

3. Storage Read Amplification (consistent with the above, 3 out of 12 nodes see much higher read amp than other nodes)
<img width="975" alt="Screenshot 2023-11-27 at 3 50 01 PM" src="https://github.com/cockroachdb/cockroach/assets/36337582/e8e92db2-d307-473d-883e-86bd626d45a0">

One particular concern is metric 2 and 3, which suggests there is some kind of "workload imbalance" in the cluster. Namely, node 3, 8, and 8 are processing significantly more writes than other nodes in the storage level. Ideally, in a "workload balanced" world, all 12 nodes should shoulder similar load.

### Theory of the reason of the load imbalance
One theory for the load imbalance is the *temporary index* used during the `ADD COLUMN`. A temporary index is created to accept incoming writes to the table while the new primary index is being backfilled from the old primary index (so that it can be merged onto the new primary index to account for the deltas happened in the backfilling period). @kvoli (and others) thinks all the writes to this temporary index is being handled by 3 nodes and those nodes only. So, what could have happened is that writes going to the temporary index is initially in a range handled by triplet (n3,n8,n10), and since the table is big and concurrent writes are also frequent, a considerable amount of data is written to this temporary index. Initially, those writes go to a range handled by this triplet. The range keeps growing and be split into two (or more) ranges, but the load balancer in KV, which aims to move ranges around for a balanced load across all nodes in cluster, picks randomly among *all* ranges in the triplets, rather than among only ranges of this temporary index, and distribute to other nodes. It's thus likely that the temporary index range(s) remain on the same triplet and all the incoming writes to this temporary index keep hitting the same triplets.

This sounds a plausible explanation to me, and to address it, we can call "Split" and "Scatter" -- both of which are KV APIs that signal to KV layer that we want to split ranges at provided split points and scatter ranges to different nodes in the cluster -- on the temporary index when it's created, such that any writes to this temporary index would be processed by various triplets in the cluster. The difficulty, however, is we don't know what split points to pick a priori that would be "representative"/"helpful" of the future writes to this temporary index. This is why we created this issue in the first place.

**Comment by fqazi** [comment]
I have a very early prototype for this that we are testing on an internal scale testing cluster: https://github.com/cockroachdb/cockroach/compare/master...fqazi:cockroach:hackySplitForIndexes
