### ISSUE TITLE
kv: add `txn.commits_read_only` metric

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#114984]
We have client-side metrics for `txn.commits` and `txn.commits1PC`. We should add a `txn.commits_read_only` metric that parallels these metrics and is incremented by transactions which hit the `finalizeNonLockingTxnLocked` path.

@lyang24 do you want to take this one?

Jira issue: CRDB-33828

**Comment by lyang24** [comment]
Yes, thank you!

**Comment by nvanbenschoten** [comment]
> but read only request can also take shared locks no

At this level, "read only" and "non locking" are synonymous. For example, a transaction that has been started with `BEGIN READ ONLY` cannot perform `SELECT FOR SHARE`.
