### ISSUE TITLE
roachtest: use single-region Google Cloud Storage buckets for test fixtures

### ISSUE THREAD

**Issue by DuskEagle** [cockroachdb/cockroach#115009]
`gs://cockroach-fixtures` is a [multi-region](https://cloud.google.com/storage/docs/locations) bucket used for storing test fixtures.

[Google recently announced a change to the pricing of multiregion buckets](https://cloud.google.com/storage/pricing-announce), which came into effect on our account on September 1. The key thing that has changed is:

> Reading data in a Cloud Storage bucket located in a multi-region from a Google Cloud service located in a region on the same continent will no longer be free; instead, such moves will be priced the same as general data moves between different locations on the same continent.

With this change, as of September 1, we are paying an additional $6000/month to transfer data out of this bucket.

<img width="611" alt="Screenshot 2023-11-22 at 16 59 34" src="https://github.com/cockroachdb/cockroach/assets/7644598/0c877f3a-b4c7-40cd-b337-89add39294c2">

To eliminate these costs, we should move the fixtures to one or more single-region buckets, [like we do for some regions in AWS](https://github.com/cockroachdb/cockroach/issues/105968). 

Jira issue: CRDB-33835

**Comment by srosenberg** [comment]
Duplicates https://github.com/cockroachdb/cockroach/issues/111371
