### ISSUE TITLE
Collect telemetry using feature counters when someone executes a transaction with a mix of DDL and DML

### ISSUE THREAD

**Issue by dikshant** [cockroachdb/cockroach#115012]
We need to understand the extent at which our customers are using or trying to use DDL and DML statements in a single transactions. For example this simple case is supported:

```
root@localhost:26257/system/defaultdb> CREATE TABLE t (a INT);
CREATE TABLE

Time: 48ms total (execution 48ms / network 0ms)

root@localhost:26257/system/defaultdb> BEGIN;
BEGIN

Time: 0ms total (execution 1ms / network 0ms)

root@localhost:26257/system/defaultdb  OPEN> ALTER TABLE t ADD COLUMN b INT;
ALTER TABLE

Time: 16ms total (execution 16ms / network 0ms)

root@localhost:26257/system/defaultdb  OPEN> INSERT INTO t (a) VALUES (1);
INSERT 0 1

Time: 4ms total (execution 4ms / network 0ms)

root@localhost:26257/system/defaultdb  OPEN> COMMIt;
COMMIT

Time: 582ms total (execution 582ms / network 0ms)

root@localhost:26257/system/defaultdb> SELECT * FROM t;
  a |  b
----+-------
  1 | NULL
(1 row)

Time: 1ms total (execution 0ms / network 0ms)
```

In such cases we should emit telemetry for a feature counter: `sql.schema.ddl_dml_transaction_success`

If there are cases where we emit a warning or do not support we should also log:
`sql.schema.ddl_dml_transaction_failure`

We should also measure DDL only transactions:
`sql.schema.ddl_transaction_success`

Similarly for failures
`sql.schema.ddl_transaction_failure`

Jira issue: CRDB-33841

Epic CRDB-31282

**Comment by rafiss** [comment]
We should be able to do this by comparing the number of DDL statements in the transaction versus the number of total statements in the transaction. I believe we have both of these values tracked in our code already, but if not that's there, we can add that.

**Comment by rafiss** [comment]
The final names we went with are:
- `sql.schema.transaction.mixed_ddl_dml.success`
- `sql.schema.transaction.mixed_ddl_dml.failure`
- `sql.schema.transaction.ddl_only.success`
- `sql.schema.transaction.ddl_only.failure`
