### ISSUE TITLE
observability: statement times chart presents inaccurate y-axis

### ISSUE THREAD

**Issue by ajstorm** [cockroachdb/cockroach#115091]
On the CCT cluster, in the application tenant, when I examine the SQL Activity for an IMPORT statement I see the following chart for statement times:

<img width="738" alt="image" src="https://github.com/cockroachdb/cockroach/assets/18447034/6a01d1bb-7238-4172-bc80-25d50697c681">

The green dot is highlighting a bar, which the y-axis shows to be at `0:00 UTC`, yet the data point is in fact at `5:00 UTC`.

I'm not sure if this is a GA blocker, but marking it as such for triage purposes.

Jira issue: CRDB-33881

**Comment by koorosh** [comment]
x-axis of the charts displays time in local timezone but tooltip shows UTC.
![Screenshot 2023-11-28 at 16 09 34](https://github.com/cockroachdb/cockroach/assets/3106437/38dd5964-c95e-4792-8e91-7c11f86c988e)
