### ISSUE TITLE
multitenant: tenant dropdown is not always visible

### ISSUE THREAD

**Issue by ajstorm** [cockroachdb/cockroach#115095]
In debugging a [problem](https://cockroachlabs.slack.com/archives/C063CP41TG9/p1701013490274639) today, we encountered an issue where the tenant dropdown wasn't available on the console of a UA cluster.  When entering into incognito mode, the dropdown appeared, implying that something went bad with the cookie. 

It's possible that this is somehow related to https://github.com/cockroachdb/cockroach/issues/96355, but also possible that it's a new issue.  

Jira issue: CRDB-33883

Epic CRDB-34076

**Comment by maryliag** [comment]
Dropdown is created [here](https://github.com/cockroachdb/cockroach/blob/69b9cac43b7b50fdc0d19cecc71c8d5142bace77/pkg/ui/workspaces/db-console/src/views/app/components/tenantDropdown/tenantDropdown.tsx#L23) and we don't show the dropdown under these conditions [here](https://github.com/cockroachdb/cockroach/blob/69b9cac43b7b50fdc0d19cecc71c8d5142bace77/pkg/ui/workspaces/db-console/src/views/app/components/tenantDropdown/tenantDropdown.tsx#L43).

I was able to repro this when using my "normal" tabs, but not with incognito, which means that the cookies I have while running demo locally (just a regular cluster on insecure mode), could be affecting the values when I try to open a real cluster.

**Comment by dhartunian** [comment]
@maryliag can you dump your session cookies that reproduce the problem? This is the `session` and the `tenant` cookie.

**Comment by maryliag** [comment]
`session`: `"CIKAlPGj+srjDBIQvG+VmwDMw8ncZf8AF87kaw==,system"`
`tenant`: `system`
