### ISSUE TITLE
kv: skip locked does not work correctly with read committed

### ISSUE THREAD

**Issue by arulajmani** [cockroachdb/cockroach#115057]
**Describe the problem**

Currently, when a skip locked request is evaluating, it only checks for in-memory exclusive and shared locks. Notably, it does not check for replicated locks. As a result, read committed transactions (which have a potential to acquire replicated locks) do not work well with `SKIP LOCKED`.

Related to https://github.com/cockroachdb/cockroach/issues/110743

Jira issue: CRDB-33860

Epic CRDB-34172

**Comment by nvanbenschoten** [comment]
@arulajmani until we address it, should we add in a patch to reject this combination? We had been considering this to be almost as much work as fixing this, but I think it might actually just be a matter of catching `LockConflictErrors` coming from `acquireLocksOnKeys` for `SkipLocked` Get/Scan/RevScans and turning these into unsupported errors.

This wouldn't support non-locking skip-locked requests, but that's not a combination that's actually used by SQL.

**Comment by michae2** [comment]
After talking with @arulajmani and @nvanbenschoten, removing the GA-blocker label. We'll rely on documenting this initially, and maybe @nvanbenschoten's suggestion above if we can get to it.

**Comment by michae2** [comment]
The limitation to document is that SELECT statements using SKIP LOCKED will not yet always skip over replicated locks (which are the kind used by read committed transactions).

**Comment by mikeCRL** [comment]
@arulajmani Do you know if the [suggested limitation](https://github.com/cockroachdb/cockroach/issues/115057#issuecomment-1852789205) will be making it into 23.2 GA? I'm writing up the Known Limitations and it looks like the answer will impact the entry for https://github.com/cockroachdb/cockroach/issues/115057.
