### ISSUE TITLE
cli,server: set reasonable GOGC by default

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#115164]
We started setting a reasonable default value for the `GOMEMLIMIT` env var in 2e6ae8065c5ba267b969582544532e06d6feaee0. Doing so has reduced OOMs without introducing issues.

We should do the same for the `GOGC` env var, using the [debug.SetGCPercent](https://pkg.go.dev/runtime/debug#SetGCPercent) API.

To do this, we need to pick a reasonable value for the configuration. 100% (the current default) isn't great because it often runs into the problem described in [this blog post](https://blog.twitch.tv/en/2019/04/10/go-memory-ballast-how-i-learnt-to-stop-worrying-and-love-the-heap/) which results in an overactive GC. A larger value (e.g. 900%) would avoid some of these issues with small heaps on large systems. Alternatively, we could disable the GC percent heuristic (`GOGC=off`) and rely entirely on the `GOMEMLIMIT` to bound memory, if we trust that it has been configured correctly.

https://tip.golang.org/doc/gc-guide serves as a good reference for GC knobs.

Jira issue: CRDB-33918

Epic CRDB-32846

**Comment by yuzefovich** [comment]
I think in the past, before we had `GOMEMLIMIT` knob, a few times we recommended _lowering_ `GOGC` (to, say, `50%`) in hopes of preventing some OOMs. However, now that we have the soft memory limit in place, your proposal to increase `GOGC` seems good.

**Comment by nvanbenschoten** [comment]
Some further discussion about GC assist in https://github.com/golang/go/issues/56966#issuecomment-1847961673.
