### ISSUE TITLE
observability: SQL Activity page is missing some statements

### ISSUE THREAD

**Issue by ajstorm** [cockroachdb/cockroach#115168]
On the CCT cluster, while investigating an issue with impactful IMPORTs, we noticed that some of the IMPORTs which occur on the cluster are not present in the SQL Activity page's "Statement Times" chart.  

As an example, here's the chart for the last hour for the statement 

`IMPORT INTO order_line CSV DATA ($1, $1, $1, $1, $1, $1, $1, $1, $1, $1, $1, $1, $1, $1, $1) WITH OPTIONS ("nullif" = '_')`

<img width="916" alt="image" src="https://github.com/cockroachdb/cockroach/assets/18447034/06846aa6-493b-4b3e-8b5e-da46dd6c9fde">

While there's a problem in this chart's y-axis not matching up with the data points (due to https://github.com/cockroachdb/cockroach/issues/115091), you can see that the last data point (accurately in UTC) represents that an IMPORT job completed between 13:00 and 14:00 UTC.  The problem is that the chart shows that no IMPORT statements on the order_line table completed between 11:00 and 13:00 UTC.  If we compare this to the jobs table however, we can see that a job started and completed in that period:

<img width="1494" alt="image" src="https://github.com/cockroachdb/cockroach/assets/18447034/e5d615bc-d9cf-4293-be93-cf76c7eead6d">

Jira issue: CRDB-33920

**Comment by koorosh** [comment]
@ajstorm , can you provide some additional details on this issue:
1. is there a corresponding record on Jobs table to last datapoint between 13:00 and 14:00 UTC?
2. there's also a graph that shows execution counts on Statement details page, it would be nice to know the number of executions between 13:00 and 14:00 UTC?

There's an assumption that statistics are flushed with delay and can be put into next timewindow.
Thanks!

**Comment by ajstorm** [comment]
@koorosh it might be easiest if you login to the console yourself to investigate further.  I'll send you the login info in Slack.
