### ISSUE TITLE
sql: clarify text in pg_lsn error message

### ISSUE THREAD

**Issue by rharding6373** [cockroachdb/cockroach#115136]
The following error message differs between postgres and crdb:

```
SELECT '0/16AE7F7'::pg_lsn - 'NaN'::numeric; 
-- postgres: ERROR:  cannot subtract NaN to pg_lsn
-- crdb: ERROR:  cannot add NaN to pg_lsn
```

Found in pg_regress pg_lsn

Jira issue: CRDB-33907

**Comment by da-ket** [comment]
Hello, I have tried to resolve the issue without changing the code's flow.
