### ISSUE TITLE
cdceval: v23.1.12: index out of range when accessing Annotations.Get

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#115245]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4680709795/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4680709795/?referrer=webhooks_plugin)

Panic Message:

```
catch.go:29: runtime error: index out of range [0] with length 0
(1)
Wraps: (2)
Wraps: (3) assertion failure
Wraps: (4) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/util/errorutil.ShouldCatch
  | 	github.com/cockroachdb/cockroach/pkg/util/errorutil/catch.go:29
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).Build.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:212
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | runtime.goPanicIndex
  | 	GOROOT/src/runtime/panic.go:113
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*Annotations).Get
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/annotation.go:53
  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/cdceval.rowEvalContextFromEvalContext
  | 	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/cdceval/expr_eval.go:523
  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/cdceval.cdcTimestampBuiltin.func1
  | 	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/cdceval/functions.go:166
  | github.com/cockroachdb/cockroach/pkg/sql/sem/eval.(*evaluator).EvalFuncExpr
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/eval/expr.go:483
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FuncExpr).Eval
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/sem/tree/eval_expr_generated.go:276
  | github.com/cockroachdb/cockroach/pkg/sql/sem/eval.Expr
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/eval/expr.go:26
  | github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*CustomFuncs).FoldFunction
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/norm/fold_constants_funcs.go:694
  | github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).ConstructFunction
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go:20489
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildFunction
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scalar.go:571
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildScalar
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scalar.go:334
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildProjectionList
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/project.go:206
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildSelectClause
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:1150
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildSelectStmtWithoutParens
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:1069
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildSelect.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:1038
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).processWiths
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/with.go:116
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildSelect
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:1037
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:332
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmtAtRoot
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:272
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).Build
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:246
  | github.com/cockroachdb/cockroach/pkg/sql.(*optPlanningCtx).buildExecMemo
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:576
  | github.com/cockroachdb/cockroach/pkg/sql.PlanCDCExpression
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_plan_changefeed.go:113
  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/cdceval.normalizeExpression
  | 	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/cdceval/plan.go:85
  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/cdceval.NormalizeExpression.func1
  | 	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/cdceval/plan.go:51
  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/cdceval.withPlanner.func1
  | 	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/cdceval/plan.go:187
  | github.com/cockroachdb/cockroach/pkg/sql.DescsTxn.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/exec_util.go:3695
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).DescsTxn.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1610
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).txn.func4
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1698
  | github.com/cockroachdb/cockroach/pkg/kv.runTxn.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:970
Wraps: (5) runtime error: index out of range [0] with length 0
  | -- cause hidden behind barrier
  | runtime error: index out of range [0] with length 0
  | (1) runtime error: index out of range [0] with length 0
  | Error types: (1) runtime.boundsError
Error types: (1) *colexecerror.notInternalError (2) *changefeedbase.taggedError (3) *assert.withAssertionFailure (4) *withstack.withStack (5) *barriers.barrierErr
-- report composition:
*barriers.barrierErr: masked error: runtime error: index out of range [0] with length 0
catch.go:29: *withstack.withStack (top exception)
*assert.withAssertionFailure
*changefeedbase.taggedError
*colexecerror.notInternalError
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/kv/db.go#L969-L971](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/kv/db.go#L969-L971)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/internal.go#L1697-L1699](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/internal.go#L1697-L1699)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/internal.go#L1609-L1611](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/internal.go#L1609-L1611)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/exec_util.go#L3694-L3696](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/exec_util.go#L3694-L3696)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/ccl/changefeedccl/cdceval/plan.go#L186-L188](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/ccl/changefeedccl/cdceval/plan.go#L186-L188)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/ccl/changefeedccl/cdceval/plan.go#L50-L52](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/ccl/changefeedccl/cdceval/plan.go#L50-L52)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/ccl/changefeedccl/cdceval/plan.go#L84-L86](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/ccl/changefeedccl/cdceval/plan.go#L84-L86)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/distsql_plan_changefeed.go#L112-L114](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/distsql_plan_changefeed.go#L112-L114)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/plan_opt.go#L575-L577](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/plan_opt.go#L575-L577)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/opt/optbuilder/builder.go#L245-L247](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/opt/optbuilder/builder.go#L245-L247)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/opt/optbuilder/builder.go#L271-L273](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/opt/optbuilder/builder.go#L271-L273)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/opt/optbuilder/builder.go#L331-L333](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/opt/optbuilder/builder.go#L331-L333)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/opt/optbuilder/select.go#L1036-L1038](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/opt/optbuilder/select.go#L1036-L1038)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/opt/optbuilder/with.go#L115-L117](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/opt/optbuilder/with.go#L115-L117)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/opt/optbuilder/select.go#L1037-L1039](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/opt/optbuilder/select.go#L1037-L1039)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/opt/optbuilder/select.go#L1068-L1070](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/opt/optbuilder/select.go#L1068-L1070)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/opt/optbuilder/select.go#L1149-L1151](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/opt/optbuilder/select.go#L1149-L1151)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/opt/optbuilder/project.go#L205-L207](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/opt/optbuilder/project.go#L205-L207)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/opt/optbuilder/scalar.go#L333-L335](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/opt/optbuilder/scalar.go#L333-L335)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/opt/optbuilder/scalar.go#L570-L572](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/opt/optbuilder/scalar.go#L570-L572)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L20488-L20490](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L20488-L20490)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/opt/norm/fold_constants_funcs.go#L693-L695](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/opt/norm/fold_constants_funcs.go#L693-L695)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/sem/eval/expr.go#L25-L27](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/sem/eval/expr.go#L25-L27)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/bazel-out/k8-opt/bin/pkg/sql/sem/tree/eval_expr_generated.go#L275-L277](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/bazel-out/k8-opt/bin/pkg/sql/sem/tree/eval_expr_generated.go#L275-L277)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/sem/eval/expr.go#L482-L484](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/sem/eval/expr.go#L482-L484)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/ccl/changefeedccl/cdceval/functions.go#L165-L167](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/ccl/changefeedccl/cdceval/functions.go#L165-L167)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/ccl/changefeedccl/cdceval/expr_eval.go#L522-L524](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/ccl/changefeedccl/cdceval/expr_eval.go#L522-L524)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/sem/tree/annotation.go#L52-L54](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/sem/tree/annotation.go#L52-L54)
[GOROOT/src/runtime/panic.go#L112-L114](GOROOT/src/runtime/panic.go#L112-L114)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/opt/optbuilder/builder.go#L211-L213](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/opt/optbuilder/builder.go#L211-L213)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/util/errorutil/catch.go#L28-L30](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/util/errorutil/catch.go#L28-L30)
</details>

```
pkg/kv/db.go in pkg/kv.runTxn.func1 at line 970
pkg/sql/internal.go in pkg/sql.(*InternalDB).txn.func4 at line 1698
pkg/sql/internal.go in pkg/sql.(*InternalDB).DescsTxn.func1 at line 1610
pkg/sql/exec_util.go in pkg/sql.DescsTxn.func1 at line 3695
pkg/ccl/changefeedccl/cdceval/plan.go in pkg/ccl/changefeedccl/cdceval.withPlanner.func1 at line 187
pkg/ccl/changefeedccl/cdceval/plan.go in pkg/ccl/changefeedccl/cdceval.NormalizeExpression.func1 at line 51
pkg/ccl/changefeedccl/cdceval/plan.go in pkg/ccl/changefeedccl/cdceval.normalizeExpression at line 85
pkg/sql/distsql_plan_changefeed.go in pkg/sql.PlanCDCExpression at line 113
pkg/sql/plan_opt.go in pkg/sql.(*optPlanningCtx).buildExecMemo at line 576
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).Build at line 246
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).buildStmtAtRoot at line 272
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).buildStmt at line 332
pkg/sql/opt/optbuilder/select.go in pkg/sql/opt/optbuilder.(*Builder).buildSelect at line 1037
pkg/sql/opt/optbuilder/with.go in pkg/sql/opt/optbuilder.(*Builder).processWiths at line 116
pkg/sql/opt/optbuilder/select.go in pkg/sql/opt/optbuilder.(*Builder).buildSelect.func1 at line 1038
pkg/sql/opt/optbuilder/select.go in pkg/sql/opt/optbuilder.(*Builder).buildSelectStmtWithoutParens at line 1069
pkg/sql/opt/optbuilder/select.go in pkg/sql/opt/optbuilder.(*Builder).buildSelectClause at line 1150
pkg/sql/opt/optbuilder/project.go in pkg/sql/opt/optbuilder.(*Builder).buildProjectionList at line 206
pkg/sql/opt/optbuilder/scalar.go in pkg/sql/opt/optbuilder.(*Builder).buildScalar at line 334
pkg/sql/opt/optbuilder/scalar.go in pkg/sql/opt/optbuilder.(*Builder).buildFunction at line 571
bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go in pkg/sql/opt/norm.(*Factory).ConstructFunction at line 20489
pkg/sql/opt/norm/fold_constants_funcs.go in pkg/sql/opt/norm.(*CustomFuncs).FoldFunction at line 694
pkg/sql/sem/eval/expr.go in pkg/sql/sem/eval.Expr at line 26
bazel-out/k8-opt/bin/pkg/sql/sem/tree/eval_expr_generated.go in pkg/sql/sem/tree.(*FuncExpr).Eval at line 276
pkg/sql/sem/eval/expr.go in pkg/sql/sem/eval.(*evaluator).EvalFuncExpr at line 483
pkg/ccl/changefeedccl/cdceval/functions.go in pkg/ccl/changefeedccl/cdceval.cdcTimestampBuiltin.func1 at line 166
pkg/ccl/changefeedccl/cdceval/expr_eval.go in pkg/ccl/changefeedccl/cdceval.rowEvalContextFromEvalContext at line 523
pkg/sql/sem/tree/annotation.go in pkg/sql/sem/tree.(*Annotations).Get at line 53
GOROOT/src/runtime/panic.go in runtime.goPanicIndex at line 113
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).Build.func1 at line 212
pkg/util/errorutil/catch.go in pkg/util/errorutil.ShouldCatch at line 29
```

### Tags

| Tag | Value |
| --- | --- |
| Command | start-single-node |
| Environment | v23.1.12 |
| Go Version | go1.19.13 |
| Platform | windows amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.12 |
| Cockroach SHA | d7e9824b4cd6ebf7a8548156f2a772ae6648257d |
| # of CPUs | 20 |
| # of Goroutines | 485 |

Jira issue: CRDB-34067

**Comment by yuzefovich** [comment]
This has been seen on at least one CC cluster.

**Comment by miretskiy** [comment]
Got repro.
