### ISSUE TITLE
Sentry: raft.go:1700: log.Fatal: 6e state.commit 3347447 is out of range [0, 0]
(1) attached stack trace
  -- stack trace:
  | go.etcd.io/etcd/raft/v3.(*raft).loadState
  | 	go.etcd.io/etcd/raft/v3/ex...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#115328]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4684700399/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4684700399/?referrer=webhooks_plugin)

Panic Message:

```
raft.go:1700: log.Fatal: 6e state.commit 3347447 is out of range [0, 0]
(1) attached stack trace
  -- stack trace:
  | go.etcd.io/etcd/raft/v3.(*raft).loadState
  | 	go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700
  | go.etcd.io/etcd/raft/v3.newRaft
  | 	go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:349
  | go.etcd.io/etcd/raft/v3.NewRawNode
  | 	go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/rawnode.go:48
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).withRaftGroupLocked
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:1791
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).maybeInitializeRaftGroup
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_init.go:285
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*baseQueue).maybeAdd
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/queue.go:665
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.baseQueueHelper.MaybeAdd
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/queue.go:572
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*baseQueue).MaybeAddAsync.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/queue.go:624
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*baseQueue).Async.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/queue.go:611
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:489
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (2) log.Fatal: 6e state.commit 3347447 is out of range [0, 0]
Error types: (1) *withstack.withStack (2) *errutil.leafError
-- report composition:
*errutil.leafError: log.Fatal: 6e state.commit 3347447 is out of range [0, 0]
raft.go:1700: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/util/stop/stopper.go#L488-L490](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/util/stop/stopper.go#L488-L490)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/kv/kvserver/pkg/kv/kvserver/queue.go#L610-L612](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/kv/kvserver/pkg/kv/kvserver/queue.go#L610-L612)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/kv/kvserver/pkg/kv/kvserver/queue.go#L623-L625](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/kv/kvserver/pkg/kv/kvserver/queue.go#L623-L625)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/kv/kvserver/pkg/kv/kvserver/queue.go#L571-L573](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/kv/kvserver/pkg/kv/kvserver/queue.go#L571-L573)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/kv/kvserver/pkg/kv/kvserver/queue.go#L664-L666](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/kv/kvserver/pkg/kv/kvserver/queue.go#L664-L666)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/kv/kvserver/pkg/kv/kvserver/replica_init.go#L284-L286](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/kv/kvserver/pkg/kv/kvserver/replica_init.go#L284-L286)
[https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L1790-L1792](https://github.com/cockroachdb/cockroach/blob/d5a076f2953c0712193b8cbe08bbb682563c5675/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L1790-L1792)
[go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/rawnode.go#L47-L49](go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/rawnode.go#L47-L49)
[go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go#L348-L350](go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go#L348-L350)
[go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go#L1699-L1701](go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go#L1699-L1701)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 489
pkg/kv/kvserver/pkg/kv/kvserver/queue.go in pkg/kv/kvserver.(*baseQueue).Async.func1 at line 611
pkg/kv/kvserver/pkg/kv/kvserver/queue.go in pkg/kv/kvserver.(*baseQueue).MaybeAddAsync.func1 at line 624
pkg/kv/kvserver/pkg/kv/kvserver/queue.go in pkg/kv/kvserver.baseQueueHelper.MaybeAdd at line 572
pkg/kv/kvserver/pkg/kv/kvserver/queue.go in pkg/kv/kvserver.(*baseQueue).maybeAdd at line 665
pkg/kv/kvserver/pkg/kv/kvserver/replica_init.go in pkg/kv/kvserver.(*Replica).maybeInitializeRaftGroup at line 285
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).withRaftGroupLocked at line 1791
go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/rawnode.go in go.etcd.io/etcd/raft/v3.NewRawNode at line 48
go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go in go.etcd.io/etcd/raft/v3.newRaft at line 349
go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go in go.etcd.io/etcd/raft/v3.(*raft).loadState at line 1700
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v22.2.6 |
| Go Version | go1.19.4 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v22.2.6 |
| Cockroach SHA | d5a076f2953c0712193b8cbe08bbb682563c5675 |
| # of CPUs | 48 |
| # of Goroutines | 791 |

Jira issue: CRDB-33982

**Comment by yuzefovich** [comment]
too old
