### ISSUE TITLE
sql: join hint to fix join order without fixing join algorithm

### ISSUE THREAD

**Issue by michae2** [cockroachdb/cockroach#115308]
Our current join hints (`a INNER HASH JOIN b`, `a LEFT LOOKUP JOIN b`, etc.) fix both the join order and the join algorithm. It would be nice to also have a join hint that fixes the join order but not the algorithm. [MySQL](https://dev.mysql.com/doc/refman/8.0/en/join.html) has a `STRAIGHT_JOIN` syntax that does this, so maybe the hint could be something like `a STRAIGHT JOIN b` or `a INNER STRAIGHT JOIN b` or `a STRAIGHT_JOIN b` etc.

Jira issue: CRDB-33972

**Comment by michae2** [comment]
> Hi, I'm interested to contribute to this!

Awesome! Thank you @kevinmingtarja! I think one way to approach this would be to copy the `INNER HASH JOIN` hint all the way from [the parser](https://github.com/cockroachdb/cockroach/blob/c441a2c6c4f9ce8a7673b6a96ea6763e405d635c/pkg/sql/parser/sql.y#L13747-L13750) to [the AST](https://github.com/cockroachdb/cockroach/blob/c441a2c6c4f9ce8a7673b6a96ea6763e405d635c/pkg/sql/sem/tree/select.go#L634-L640) to [the optimizer](https://github.com/cockroachdb/cockroach/blob/c441a2c6c4f9ce8a7673b6a96ea6763e405d635c/pkg/sql/opt/optbuilder/join.go#L57-L93) and then modify it to use [a new flag that disallows all IntoLeft joins](https://github.com/cockroachdb/cockroach/blob/c441a2c6c4f9ce8a7673b6a96ea6763e405d635c/pkg/sql/opt/memo/expr.go#L500-L523).

(Also, if you haven't already, please take a look at [Contributing to CockroachDB](https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/73204033/Contributing+to+CockroachDB).)

**Comment by michae2** [comment]
(Assigning @kevinmingtarja so that we remember that he has a nice PR going for this! 🙂)

**Comment by kevinmingtarja** [comment]
Thanks @michae2! I've been pretty busy with other stuff, but I've taken note of your comments on the PR and I plan to address those by early next week.
