### ISSUE TITLE
sql: query hint to preserve original join order of query

### ISSUE THREAD

**Issue by michae2** [cockroachdb/cockroach#115309]
(Thanks to @drewdeally for this.)

[Oracle](https://github.com/cockroachdb/cockroach/issues/new?assignees=&labels=C-enhancement&projects=&template=feature_request.md&title=) has an `ORDERED` hint that fixes the join order of the query to match the order in the FROM clause. I think this would be equivalent to running the query with `SET reorder_joins_limit = 0;`. It might be nice to support such a query hint, maybe in the form of [a pg_hint_plan-style hint](https://github.com/cockroachdb/cockroach/issues/115306).

Jira issue: CRDB-33973

**Comment by mgartner** [comment]
[SQL Server](https://learn.microsoft.com/en-us/sql/t-sql/queries/hints-transact-sql-query?view=sql-server-ver16#force-order) has the `FORCE ORDER` option that does this. Example from [this post](https://www.sqlserver.info/syntax/force-order-query-hint/):

```sql
SELECT	*
FROM	Habitat H 
INNER	JOIN AnimalHabitat AH ON H.HabitatID = AH.HabitatID
INNER	JOIN Animal A ON AH.AnimalID = A.AnimalID
OPTION	(FORCE ORDER)
```

**Comment by mgartner** [comment]
This is supported as of #116013 with the `STRAIGHT` join hint.
