### ISSUE TITLE
sql: redact sensitive cluster settings by default

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#115356]
The following settings should not have their values revealed when using `SHOW CLUSTER SETTING`.

~Later on, we can add a privilege to view the unredacted value. For now, let's redact them unconditionally.~ See below; we will use `MODIFYCLUSTERSETTING`.

- server.oidc_authentication.client_id 
- server.oidc_authentication.client_secret

Epic: CRDB-33480

Jira issue: CRDB-33993

**Comment by rafiss** [comment]
synced with @dikshant - since we want to include this in 23.2, I'll mark this is a GA-blocker so we don't need to do a backport to a patch release later that is a backward-incompatible change.

**Comment by dikshant** [comment]
Redact only these:
server.oidc_authentication.client_id
server.oidc_authentication.client_secret

After much internal discussion we don't think enterprise license is secretive enough to redact. And even then there are a bunch of places (eg DB Console) where it is exposed.

For now we can put them behind MODIFYCLUSTERSETTING. That way only the individual responsible for setting them is able to see them for troubleshooting etc.

**Comment by rafiss** [comment]
Removing GA-blocker - since this is going to use MODIFYCLUSTERSETTING to determine if redaction is needed, we can introduce a new cluster setting that also can be used to opt-out of any redaction at all. This makes this change backportable.
