### ISSUE TITLE
sql: detect broken TCP client connections sooner

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#115422]
If a TCP connection is abandoned without being explicitly closed by the remote peer via a TCP RST packet, we rely on TCP keepalives to probe the connection and close it after some time of inactivity. This can happen e.g. if the remote host crashes (including the OS), if the network link stops sending traffic, or if some network device drops the connection without closing it.

If this is not detected promptly, it can cause a transaction to suddenly halt while open. This is dangerous if the transaction has taken out locks (i.e. made any writes), since it will block other transactions from accessing the locked rows until it's closed and rolled back, causing contention pileups that last for several minutes.

We need to detect such broken TCP connections sooner and close them, such that the transactions are rolled back and the locks released.

By default, the Linux kernel will probe the connection only after 2 hours of inactivity, and then send 9 probes every 75 seconds before closing the connection if no response is received:

```
# NB: roachprod clusters use different defaults
$ sysctl -a | grep tcp_keepalive
net.ipv4.tcp_keepalive_intvl = 75
net.ipv4.tcp_keepalive_probes = 9
net.ipv4.tcp_keepalive_time = 7200
```

However, we set an explicit 1 minute keepalive time and interval on the socket:

https://github.com/cockroachdb/cockroach/blob/c0d5d08756a9ac2b7a92619b6fbb209f6e1fc44c/pkg/server/tcp_keepalive_manager.go#L56-L68

https://github.com/cockroachdb/cockroach/blob/c0d5d08756a9ac2b7a92619b6fbb209f6e1fc44c/pkg/server/tcp_keepalive_manager.go#L34

But this only sets `TCP_KEEPIDLE` and `TCP_KEEPINTVL` to 1 minute each (i.e. the time before the first probe and the interval between probes), while the number of probes `TCP_KEEPCNT` is not modified and remains at its default 9. So it takes as long as 10 minutes before we detect the connection failure and close it.

We should:

1. Reconsider the value of `TCP_KEEPIDLE` and `TCP_KEEPINTVL` to be more aggressive.
2. Set `TCP_KEEPCNT` to a lower value, and make it configurable.
3. Consider making `COCKROACH_SQL_TCP_KEEP_ALIVE` a cluster setting, if we can easily do so.

Something like `TCP_KEEPIDLE=20s`, `TCP_KEEPINTVL=20s`, `TCP_KEEPCNT=3` might make sense. This will close the connection after 1 minute, having sent 3 probes.

## Repro

Here's a repro showing the transaction holding locks for 10 minutes after the connection is broken (by stopping traffic with iptables):

```
roachprod create grinaker-tcp -n 3
roachprod run grinaker-tcp 'sudo sysctl net.ipv4.tcp_keepalive_time=7200 net.ipv4.tcp_keepalive_probes=9 net.ipv4.tcp_keepalive_intvl=75'
roachprod stage grinaker-tcp release v22.2.13
roachprod start grinaker-tcp
roachprod sql grinaker-tcp:1

create table test (id int primary key, value string not null);
insert into test values (1, 'a'), (2, 'b'), (3, 'c');
```

Now, create a separate SQL session across the network from n1 to n2, begin a transaction, and update row 2 to take out a lock:

```
$ roachprod ip grinaker-tcp:2
10.142.1.183
$ roachprod ssh grinaker-tcp:1
$ cockroach sql --url postgres://root@10.142.1.183:26257?sslmode=disable
> begin;
OPEN> update test set value = 'foo' where id = 2;
```

Do not close this session. Open a new session, trigger lock contention by reading the table, and inspect the locks and transaction:

```
$ roachprod sql grinaker-tcp:1
> select * from test;
^C
attempting to cancel query...
ERROR: query execution canceled
SQLSTATE: 57014

> \x
> select * from crdb_internal.cluster_locks;
-[ RECORD 1 ]
range_id        | 53
table_id        | 104
database_name   | defaultdb
schema_name     | public
table_name      | test
index_name      | 
lock_key        | \xf0898a88
lock_key_pretty | /Table/104/1/2/0
txn_id          | 1f9d294e-19a8-402d-97f7-6afc7d6ffab0
ts              | 2023-12-01 14:02:04.940638
lock_strength   | Exclusive
durability      | Replicated
granted         | t
contended       | f
duration        | 00:00:52.908026

> select * from crdb_internal.cluster_transactions where id = '1f9d294e-19a8-402d-97f7-6afc7d6ffab0';
-[ RECORD 1 ]
id                     | 1f9d294e-19a8-402d-97f7-6afc7d6ffab0
node_id                | 2
session_id             | 179cb9eda2f914080000000000000002
start                  | 2023-12-01 14:00:19.97722
txn_string             | "sql txn" meta={id=1f9d294e key=/Table/104/1/2/0 pri=0.00467454 epo=0 ts=1701439324.940637758,2 min=1701439219.977209358,0 seq=1} lock=true stat=PENDING rts=1701439219.977209358,0 wto=false gul=1701439220.477209358,0
application_name       | $ cockroach sql
num_stmts              | 3
num_retries            | 0
num_auto_retries       | 0
last_auto_retry_reason | 

> select * from crdb_internal.cluster_sessions where kv_txn = '1f9d294e-19a8-402d-97f7-6afc7d6ffab0';
-[ RECORD 1 ]
node_id            | 2
session_id         | 179cb9eda2f914080000000000000002
user_name          | root
client_address     | 10.142.1.187:50232
application_name   | $ cockroach sql
active_queries     | 
last_active_query  | SHOW database
num_txns_executed  | 4
session_start      | 2023-12-01 13:59:49.531789
active_query_start | NULL
kv_txn             | 1f9d294e-19a8-402d-97f7-6afc7d6ffab0
alloc_bytes        | 40960
max_alloc_bytes    | 40960
status             | IDLE
session_end        | NULL
```

Note the client address 10.142.1.187:50232, which is from n1. Let's break the connection by dropping all packets sent across it:

```
roachprod ssh grinaker-tcp:1
sudo iptables -A OUTPUT -p tcp --sport 50232 -j DROP
sudo iptables -A INPUT -p tcp --dport 50232 -j DROP
```

Observe the transaction still remaining open and holding locks for the next 10 minutes:

```
> select *, now() - start as duration from crdb_internal.cluster_transactions where id = '1f9d294e-19a8-402d-97f7-6afc7d6ffab0';
-[ RECORD 1 ]
id                     | 1f9d294e-19a8-402d-97f7-6afc7d6ffab0
node_id                | 2
session_id             | 179cb9eda2f914080000000000000002
start                  | 2023-12-01 14:00:19.97722
txn_string             | "sql txn" meta={id=1f9d294e key=/Table/104/1/2/0 pri=0.00467454 epo=0 ts=1701439324.940637758,2 min=1701439219.977209358,0 seq=1} lock=true stat=PENDING rts=1701439219.977209358,0 wto=false gul=1701439220.477209358,0
application_name       | $ cockroach sql
num_stmts              | 3
num_retries            | 0
num_auto_retries       | 0
last_auto_retry_reason | 
duration               | 00:10:44.790427

> select * from crdb_internal.cluster_locks;                                                                                    
-[ RECORD 1 ]
range_id        | 53
table_id        | 104
database_name   | defaultdb
schema_name     | public
table_name      | test
index_name      | 
lock_key        | \xf0898a88
lock_key_pretty | /Table/104/1/2/0
txn_id          | 1f9d294e-19a8-402d-97f7-6afc7d6ffab0
ts              | 2023-12-01 14:02:04.940638
lock_strength   | Exclusive
durability      | Replicated
granted         | t
contended       | f
duration        | 00:08:18.424636
```

Jira issue: CRDB-34025

Epic CRDB-35306

**Comment by cty123** [comment]
I think the cluster setting `sql.defaults.idle_in_transaction_session_timeout` is designed to handle the case you brought up(even though the default value is 0s, meaning it never timesout a transaction). In your repro, if you set this `sql.defaults.idle_in_transaction_session_timeout` to, let's say, 30s, would you still see the lock being held after 10mins?

Anyway, I think your proposal is still valid, from DB user perspective, it doesn't make much sense to wait for 10mins to evict a dead connections, when users are using connection pool. But with `sql.defaults.idle_in_transaction_session_timeout` already in place, the keep alive should aim more towards effectively managing broken connection than aborting long idling transactions, which means we don't need to be too aggressive. I am thinking maybe lowering `TCP_KEEPCNT`(like setting it to 3) along is enough.

**Comment by fqazi** [comment]
The setting in question is completely busted, we don't properly set any of the KEEPALIVE settings on connections because of a **bad** cast

https://github.com/cockroachdb/cockroach/blob/315c305f36bf8d91cf4dae5ad78e0784756de44c/pkg/server/tcp_keepalive_manager.go#L45

So, the code in question never detects TCP connections and we have been using the GO language default of 15 seconds for a while now 😱

**Comment by erikgrinaker** [comment]
I don't think that's accurate, TCP socket stats confirm that client connections use a 1 minute keepalive.
