### ISSUE TITLE
kv: add network errors and drops metrics

### ISSUE THREAD

**Issue by nvb** [cockroachdb/cockroach#115458]
Cockroach currently exposes network IO stats using `gopsutil/net` library, which exports [these IO counters](https://pkg.go.dev/github.com/shirou/gopsutil/net#IOCountersStat) after reading from `/proc/net/dev`. This code in CRDB which uses this library is around here:
https://github.com/cockroachdb/cockroach/blob/146b425eea85d8cc8dc113b5758819609bb021bb/pkg/server/status/runtime.go#L556-L559

We don't currently make use of all counters.

For the sake of network debugging, we should expose the following four metrics, pulling from their corresponding fields:
- `sys.host.net.recv.err`
- `sys.host.net.recv.drop`
- `sys.host.net.send.err`
- `sys.host.net.send.drop`

We can then add some new graphs to the `Network` dashboard in the debug console.

Jira issue: CRDB-34046

Epic CRDB-34227

**Comment by nvanbenschoten** [comment]
@lyang24 want to take this one?

**Comment by nvanbenschoten** [comment]
After we do this, we should also look into what we can pull out and expose from `/proc/net/netstat` and `/proc/net/tcp`.
