### ISSUE TITLE
storage: rework storage block device charts to show breakdown of IO / bandwidth

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/cockroach#115434]
On our Storage dashboard in the DB Console, we have charts for host-level block device metrics. We also have application layer metrics for compactions, flushes, WAL writes, and ingestions. There are also other users of disk IO and bandwidth (e.g. spill to disk, crdb node logging).

To make it simple to correlate spikes in aggregate throughput with the Pebble / Cockroach function, we should:
- Ensure we have all sources accounted for,
- Have something like a stacked line chart that shows the breakdown.

In an ideal world, where Cockroach is the only process using the filesystem, the sum of the parts should equal the whole. If we have confidence in this, we can spot cases where another process on the host is eating up disk IO and b/w.

Known sources of writes:

- WAL writes
- Compactions
- Flushes
- Sideloaded sstables (for ingestion)
- Snapshots (for ingestion)
- SQL row-based spill to disk
- SQL columnar-vectorized spill to disk
- CRDB node logging
- Encryption-at-rest registry
- Pebble manifest

Jira issue: CRDB-34033

Epic CRDB-34247

**Comment by jbowens** [comment]
I wonder how much re-writing the same pages of the WAL contributes to under-counting write bandwidth. If the workload is not offering enough load to fill a page on every Sync, we may write the same page many times. I believe our existing metrics only account the logical bytes written.

**Comment by jbowens** [comment]
Linking to #112877 — File deletions are another source of write bandwidth, but how much is hard to tell and dependent on filesystem internals. We can at least include a metric indicating how many file bytes we're deleting.
