### ISSUE TITLE
Provide a way for users to hide or redact specific cluster settings that are considered sensitive 

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#115436]
Cluster settings and their values are viewed and modified for a variety of reasons by different groups in an organization. Some cluster settings are considered sensitive to a group, while others are not. 

We cannot redact and mask specific cluster setting values in the console and SHOW command that are considered sensitive where it's 'all or nothing' when using [system privileges](https://www.cockroachlabs.com/docs/stable/security-reference/authorization#supported-privileges) (e.g., VIEWCLUSTERSETTING)

This issue tracks providing a capability to hide sensitive cluster settings. Ideally, we have a flexible and scalable approach that allows users to specify their sensitive cluster settings depending on their requirements and environments.

Known sensitive cluster settings include:

- server.oidc_authentication.client_id	
- server.oidc_authentication.client_secret

Jira issue: CRDB-34034

**Comment by kevin-v-ngo** [comment]
https://github.com/cockroachdb/cockroach/pull/115851

**Comment by rafiss** [comment]
Does this cover any additional work beyond https://github.com/cockroachdb/cockroach/issues/115356 and the PR that resolves it (https://github.com/cockroachdb/cockroach/pull/115851)?
