### ISSUE TITLE
sql: TestSpanResolverUsesCaches flakes under stress race

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#115553]
See CI flake [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=12972382&buildTypeId=Cockroach_BazelExtendedCi).

Jira issue: CRDB-34096

**Comment by yuzefovich** [comment]
Unfortunately, the artifacts from this run have been purged. I also couldn't quickly reproduce this either. We have this:
```
panic: test timed out after 3m36s
running tests:
	TestSpanResolverUsesCaches (2s)
```
which suggests that it was other tests that were quite slow. One of them `TestFakeSpanResolver` is now skipped under race as of 5cf65fb818a7bcf12b347edd23492e684fc77dde. Others that appear to take non-trivial amount of time is `TestSingleArgumentDistAggregateFunctions` and `TestTwoArgumentRegressionAggregateFunctions`. Both of these only use a single test server but have many sub-tests. If we see this problem again, we can consider removing some of the subtests.
