### ISSUE TITLE
sql: allow dropping enum value when this type is referenced by a function

### ISSUE THREAD

**Issue by Xiang-Gu** [cockroachdb/cockroach#115612]
If we want to drop a value from a enum type, we must ensure nothing is using that value. Presently, our logic to check nothing is using the to-be-dropped value assumes that only a table will depend on a enum type ([here](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/type_change.go#L761)). This is incorrect because a UDF can also depend on a value (in its input arguments, and/or return argument, and/or body).

E.g.
```
CREATE TYPE typ AS ENUM ('1', '2', '3');

CREATE FUNCTION f1(IN x typ) RETURNS VOID LANGUAGE SQL AS $$ SELECT NULL $$; -- input

CREATE FUNCTION f2(IN x typ) RETURNS typ LANGUAGE SQL AS $$ SELECT NULL $$; -- input, output

CREATE FUNCTION f3(IN x typ) RETURNS typ LANGUAGE SQL AS $$ SELECT '3'::typ $$; -- input, out, body

ALTER TYPE typ DROP VALUE '3';
ERROR: could not validate enum value removal for "3": relation "[106]" does not exist
SQLSTATE: 42P01
```

We need to augment the dependency checking logic for removing a enum value such that if the depending descriptor is a function, then we can only allow such value dropping if 
 1. that value is not used as default value for any input arguments, AND
 2. that value is not used in the function body

Informs #114844 

Jira issue: CRDB-34125

Epic CRDB-19497

**Comment by rimadeodhar** [comment]
CockroachDB doesn't currently support default value for UDF arguments so we only need to check if the value is being used within the function body.
