### ISSUE TITLE
storage: TestFileRegistryRollover fails under remote execution

### ISSUE THREAD

**Issue by rickystewart** [cockroachdb/cockroach#115617]
This seems to happen mostly, or entirely, under `race`.

[Example invocation](https://tanzanite.cluster.engflow.com/invocations/default/664ea78e-40a4-4e00-bc76-05ed574dcd8a)

The results are consistent with an OOM.

Jira issue: CRDB-34128

Epic CRDB-8308

**Comment by sumeerbhola** [comment]
See conversation in https://cockroachlabs.slack.com/archives/CAC6K3SLU/p1701465928660419
Also relates to https://github.com/cockroachdb/cockroach/issues/109176#issuecomment-1693339744
