### ISSUE TITLE
kvserver: remove Raft migrations during replica initialization

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#115869]
We currently have multiple Raft replica migrations that are performed during store initialization. These are no longer needed after nodes have started on 23.1 at least once.

We should remove these, as they have a non-negligible cost and have occasionally been seen to take over a minute. We should also add corresponding assertions for the invariants that the migrations are meant to ensure.

https://github.com/cockroachdb/cockroach/blob/bf76e36422cb1cde1908ba5d8cdc7c15f6fbbd29/pkg/kv/kvserver/kvstorage/init.go#L417-L455
 https://github.com/cockroachdb/cockroach/blob/bf76e36422cb1cde1908ba5d8cdc7c15f6fbbd29/pkg/kv/kvserver/kvstorage/init.go#L508-L536

Jira issue: CRDB-34262

**Comment by williamkulju** [comment]
Link to relevant thread is [here](https://cockroachlabs.slack.com/archives/C05VAJ5H3QS/p1702054567062869?thread_ts=1701798934.553419&cid=C05VAJ5H3QS)
