### ISSUE TITLE
Sentry: log.go:380: log.Fatal: entries[3335:7658) is unavailable from storage
(1) attached stack trace
  -- stack trace:
  | go.etcd.io/etcd/raft/v3.(*raftLog).slice
  | 	go.etcd.io/etcd/raft/v3/exter...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#115892]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4710317438/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4710317438/?referrer=webhooks_plugin)

Panic Message:

```
log.go:380: log.Fatal: entries[3335:7658) is unavailable from storage
(1) attached stack trace
  -- stack trace:
  | go.etcd.io/etcd/raft/v3.(*raftLog).slice
  | 	go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/log.go:380
  | go.etcd.io/etcd/raft/v3.(*raftLog).nextEnts
  | 	go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/log.go:183
  | go.etcd.io/etcd/raft/v3.newReady
  | 	go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/node.go:560
  | go.etcd.io/etcd/raft/v3.(*RawNode).readyWithoutAccept
  | 	go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/rawnode.go:134
  | go.etcd.io/etcd/raft/v3.(*RawNode).Ready
  | 	go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/rawnode.go:126
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked.func2
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:713
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).withRaftGroupLocked.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:1814
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).withRaftGroupLocked
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:1815
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:707
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReady
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:668
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processReady
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:641
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).worker
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:308
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:489
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (2) log.Fatal: entries[3335:7658) is unavailable from storage
Error types: (1) *withstack.withStack (2) *errutil.leafError
-- report composition:
*errutil.leafError: log.Fatal: entries[3335:7658) is unavailable from storage
log.go:380: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/89df73b7e738a6dd87bf83d891726bb9a317d18f/pkg/util/stop/stopper.go#L488-L490](https://github.com/cockroachdb/cockroach/blob/89df73b7e738a6dd87bf83d891726bb9a317d18f/pkg/util/stop/stopper.go#L488-L490)
[https://github.com/cockroachdb/cockroach/blob/89df73b7e738a6dd87bf83d891726bb9a317d18f/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L307-L309](https://github.com/cockroachdb/cockroach/blob/89df73b7e738a6dd87bf83d891726bb9a317d18f/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L307-L309)
[https://github.com/cockroachdb/cockroach/blob/89df73b7e738a6dd87bf83d891726bb9a317d18f/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L640-L642](https://github.com/cockroachdb/cockroach/blob/89df73b7e738a6dd87bf83d891726bb9a317d18f/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L640-L642)
[https://github.com/cockroachdb/cockroach/blob/89df73b7e738a6dd87bf83d891726bb9a317d18f/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L667-L669](https://github.com/cockroachdb/cockroach/blob/89df73b7e738a6dd87bf83d891726bb9a317d18f/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L667-L669)
[https://github.com/cockroachdb/cockroach/blob/89df73b7e738a6dd87bf83d891726bb9a317d18f/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L706-L708](https://github.com/cockroachdb/cockroach/blob/89df73b7e738a6dd87bf83d891726bb9a317d18f/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L706-L708)
[https://github.com/cockroachdb/cockroach/blob/89df73b7e738a6dd87bf83d891726bb9a317d18f/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L1814-L1816](https://github.com/cockroachdb/cockroach/blob/89df73b7e738a6dd87bf83d891726bb9a317d18f/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L1814-L1816)
[https://github.com/cockroachdb/cockroach/blob/89df73b7e738a6dd87bf83d891726bb9a317d18f/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L1813-L1815](https://github.com/cockroachdb/cockroach/blob/89df73b7e738a6dd87bf83d891726bb9a317d18f/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L1813-L1815)
[https://github.com/cockroachdb/cockroach/blob/89df73b7e738a6dd87bf83d891726bb9a317d18f/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L712-L714](https://github.com/cockroachdb/cockroach/blob/89df73b7e738a6dd87bf83d891726bb9a317d18f/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L712-L714)
[go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/rawnode.go#L125-L127](go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/rawnode.go#L125-L127)
[go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/rawnode.go#L133-L135](go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/rawnode.go#L133-L135)
[go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/node.go#L559-L561](go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/node.go#L559-L561)
[go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/log.go#L182-L184](go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/log.go#L182-L184)
[go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/log.go#L379-L381](go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/log.go#L379-L381)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 489
pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go in pkg/kv/kvserver.(*raftScheduler).worker at line 308
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).processReady at line 641
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).handleRaftReady at line 668
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked at line 707
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).withRaftGroupLocked at line 1815
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).withRaftGroupLocked.func1 at line 1814
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked.func2 at line 713
go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/rawnode.go in go.etcd.io/etcd/raft/v3.(*RawNode).Ready at line 126
go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/rawnode.go in go.etcd.io/etcd/raft/v3.(*RawNode).readyWithoutAccept at line 134
go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/node.go in go.etcd.io/etcd/raft/v3.newReady at line 560
go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/log.go in go.etcd.io/etcd/raft/v3.(*raftLog).nextEnts at line 183
go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/log.go in go.etcd.io/etcd/raft/v3.(*raftLog).slice at line 380
```

### Tags

| Tag | Value |
| --- | --- |
| Command | start-single-node |
| Environment | v22.2.16 |
| Go Version | go1.19.6 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v22.2.16 |
| Cockroach SHA | 89df73b7e738a6dd87bf83d891726bb9a317d18f |
| # of CPUs | 16 |
| # of Goroutines | 384 |

Jira issue: CRDB-34270

**Comment by yuzefovich** [comment]
unactionable
