### ISSUE TITLE
Sentry: filenames.go:147: log.Fatal: 000328.sst:
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/pebble/internal/base.MustExist
  | 	github.com/cockroachdb/pebble/internal/base/e...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#116010]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4715442209/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4715442209/?referrer=webhooks_plugin)

Panic Message:

```
filenames.go:147: log.Fatal: 000328.sst:
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/pebble/internal/base.MustExist
  | 	github.com/cockroachdb/pebble/internal/base/external/com_github_cockroachdb_pebble/internal/base/filenames.go:147
  | github.com/cockroachdb/pebble/objstorage.(*Provider).vfsOpenForReading
  | 	github.com/cockroachdb/pebble/objstorage/external/com_github_cockroachdb_pebble/objstorage/vfs.go:24
  | github.com/cockroachdb/pebble/objstorage.(*Provider).OpenForReadingMustExist
  | 	github.com/cockroachdb/pebble/objstorage/external/com_github_cockroachdb_pebble/objstorage/provider.go:256
  | github.com/cockroachdb/pebble.(*tableCacheValue).load
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/table_cache.go:935
  | github.com/cockroachdb/pebble.(*tableCacheShard).findNode.func2
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/table_cache.go:707
  | runtime/pprof.Do
  | 	GOROOT/src/runtime/pprof/runtime.go:40
  | github.com/cockroachdb/pebble.(*tableCacheShard).findNode
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/table_cache.go:706
  | github.com/cockroachdb/pebble.(*tableCacheShard).newIters
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/table_cache.go:374
  | github.com/cockroachdb/pebble.(*tableCacheContainer).newIters
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/table_cache.go:139
  | github.com/cockroachdb/pebble.(*levelIter).loadFile
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/level_iter.go:669
  | github.com/cockroachdb/pebble.(*levelIter).SeekPrefixGE
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/level_iter.go:752
  | github.com/cockroachdb/pebble.(*mergingIter).seekGE
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go:1044
  | github.com/cockroachdb/pebble.(*mergingIter).SeekPrefixGE
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go:1120
  | github.com/cockroachdb/pebble.(*lazyCombinedIter).SeekPrefixGE
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/range_keys.go:565
  | github.com/cockroachdb/pebble.(*Iterator).SeekPrefixGE
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/iterator.go:1412
  | github.com/cockroachdb/cockroach/pkg/storage.(*pebbleIterator).SeekGE
  | 	github.com/cockroachdb/cockroach/pkg/storage/pebble_iterator.go:333
  | github.com/cockroachdb/cockroach/pkg/storage.(*intentInterleavingIter).SeekGE
  | 	github.com/cockroachdb/cockroach/pkg/storage/intent_interleaving_iter.go:482
  | github.com/cockroachdb/cockroach/pkg/storage.mvccGetMetadata
  | 	github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:1263
  | github.com/cockroachdb/cockroach/pkg/storage.mvccPutInternal
  | 	github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:1784
  | github.com/cockroachdb/cockroach/pkg/storage.mvccPutUsingIter
  | 	github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:1548
  | github.com/cockroachdb/cockroach/pkg/storage.mvccConditionalPutUsingIter
  | 	github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:2397
  | github.com/cockroachdb/cockroach/pkg/storage.MVCCConditionalPut
  | 	github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:2341
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/batcheval.ConditionalPut
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/batcheval/cmd_conditional_put.go:63
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.evaluateCommand
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_evaluate.go:526
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.evaluateBatch
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_evaluate.go:294
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).evaluateWriteBatchWrapper
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go:708
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).evaluateWriteBatchWithServersideRefreshes
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go:668
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).evaluateWriteBatch
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go:442
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).evaluateProposal
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go:756
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).requestToProposal
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go:844
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).evalAndPropose
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:123
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).executeWriteBatch
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go:176
Wraps: (2) secondary error attachment
  | readdirent ×: operation not permitted
  | (1) attached stack trace
  |   -- stack trace:
  |   | github.com/cockroachdb/pebble/vfs.defaultFS.List
  |   | 	github.com/cockroachdb/pebble/vfs/external/com_github_cockroachdb_pebble/vfs/vfs.go:266
  |   | github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFS).List
  |   | 	github.com/cockroachdb/pebble/vfs/external/com_github_cockroachdb_pebble/vfs/disk_health.go:661
  |   | github.com/cockroachdb/pebble/vfs.(*enospcFS).List
  |   | 	github.com/cockroachdb/pebble/vfs/external/com_github_cockroachdb_pebble/vfs/disk_full.go:324
  |   | github.com/cockroachdb/pebble/internal/base.MustExist
  |   | 	github.com/cockroachdb/pebble/internal/base/external/com_github_cockroachdb_pebble/internal/base/filenames.go:141
  |   | github.com/cockroachdb/pebble/objstorage.(*Provider).vfsOpenForReading
  |   | 	github.com/cockroachdb/pebble/objstorage/external/com_github_cockroachdb_pebble/objstorage/vfs.go:24
  |   | github.com/cockroachdb/pebble/objstorage.(*Provider).OpenForReadingMustExist
  |   | 	github.com/cockroachdb/pebble/objstorage/external/com_github_cockroachdb_pebble/objstorage/provider.go:256
  |   | github.com/cockroachdb/pebble.(*tableCacheValue).load
  |   | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/table_cache.go:935
  |   | github.com/cockroachdb/pebble.(*tableCacheShard).findNode.func2
  |   | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/table_cache.go:707
  |   | runtime/pprof.Do
  |   | 	GOROOT/src/runtime/pprof/runtime.go:40
  |   | github.com/cockroachdb/pebble.(*tableCacheShard).findNode
  |   | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/table_cache.go:706
  |   | github.com/cockroachdb/pebble.(*tableCacheShard).newIters
  |   | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/table_cache.go:374
  |   | github.com/cockroachdb/pebble.(*tableCacheContainer).newIters
  |   | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/table_cache.go:139
  |   | github.com/cockroachdb/pebble.(*levelIter).loadFile
  |   | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/level_iter.go:669
  |   | github.com/cockroachdb/pebble.(*levelIter).SeekPrefixGE
  |   | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/level_iter.go:752
  |   | github.com/cockroachdb/pebble.(*mergingIter).seekGE
  |   | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go:1044
  |   | github.com/cockroachdb/pebble.(*mergingIter).SeekPrefixGE
  |   | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go:1120
  |   | github.com/cockroachdb/pebble.(*lazyCombinedIter).SeekPrefixGE
  |   | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/range_keys.go:565
  |   | github.com/cockroachdb/pebble.(*Iterator).SeekPrefixGE
  |   | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/iterator.go:1412
  |   | github.com/cockroachdb...
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go#L175-L177](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go#L175-L177)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L122-L124](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L122-L124)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go#L843-L845](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go#L843-L845)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go#L755-L757](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go#L755-L757)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go#L441-L443](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go#L441-L443)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go#L667-L669](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go#L667-L669)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go#L707-L709](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go#L707-L709)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/kv/kvserver/pkg/kv/kvserver/replica_evaluate.go#L293-L295](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/kv/kvserver/pkg/kv/kvserver/replica_evaluate.go#L293-L295)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/kv/kvserver/pkg/kv/kvserver/replica_evaluate.go#L525-L527](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/kv/kvserver/pkg/kv/kvserver/replica_evaluate.go#L525-L527)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/kv/kvserver/batcheval/cmd_conditional_put.go#L62-L64](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/kv/kvserver/batcheval/cmd_conditional_put.go#L62-L64)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/storage/mvcc.go#L2340-L2342](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/storage/mvcc.go#L2340-L2342)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/storage/mvcc.go#L2396-L2398](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/storage/mvcc.go#L2396-L2398)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/storage/mvcc.go#L1547-L1549](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/storage/mvcc.go#L1547-L1549)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/storage/mvcc.go#L1783-L1785](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/storage/mvcc.go#L1783-L1785)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/storage/mvcc.go#L1262-L1264](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/storage/mvcc.go#L1262-L1264)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/storage/intent_interleaving_iter.go#L481-L483](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/storage/intent_interleaving_iter.go#L481-L483)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/storage/pebble_iterator.go#L332-L334](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/storage/pebble_iterator.go#L332-L334)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/iterator.go#L1411-L1413](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/iterator.go#L1411-L1413)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/range_keys.go#L564-L566](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/range_keys.go#L564-L566)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go#L1119-L1121](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go#L1119-L1121)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go#L1043-L1045](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go#L1043-L1045)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/level_iter.go#L751-L753](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/level_iter.go#L751-L753)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/level_iter.go#L668-L670](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/level_iter.go#L668-L670)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/table_cache.go#L138-L140](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/table_cache.go#L138-L140)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/table_cache.go#L373-L375](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/table_cache.go#L373-L375)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/table_cache.go#L705-L707](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/table_cache.go#L705-L707)
[GOROOT/src/runtime/pprof/runtime.go#L39-L41](GOROOT/src/runtime/pprof/runtime.go#L39-L41)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/table_cache.go#L706-L708](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/table_cache.go#L706-L708)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/table_cache.go#L934-L936](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/table_cache.go#L934-L936)
[github.com/cockroachdb/pebble/objstorage/external/com_github_cockroachdb_pebble/objstorage/provider.go#L255-L257](github.com/cockroachdb/pebble/objstorage/external/com_github_cockroachdb_pebble/objstorage/provider.go#L255-L257)
[github.com/cockroachdb/pebble/objstorage/external/com_github_cockroachdb_pebble/objstorage/vfs.go#L23-L25](github.com/cockroachdb/pebble/objstorage/external/com_github_cockroachdb_pebble/objstorage/vfs.go#L23-L25)
[github.com/cockroachdb/pebble/internal/base/external/com_github_cockroachdb_pebble/internal/base/filenames.go#L146-L148](github.com/cockroachdb/pebble/internal/base/external/com_github_cockroachdb_pebble/internal/base/filenames.go#L146-L148)
</details>

```
pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go in pkg/kv/kvserver.(*Replica).executeWriteBatch at line 176
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).evalAndPropose at line 123
pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go in pkg/kv/kvserver.(*Replica).requestToProposal at line 844
pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go in pkg/kv/kvserver.(*Replica).evaluateProposal at line 756
pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go in pkg/kv/kvserver.(*Replica).evaluateWriteBatch at line 442
pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go in pkg/kv/kvserver.(*Replica).evaluateWriteBatchWithServersideRefreshes at line 668
pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go in pkg/kv/kvserver.(*Replica).evaluateWriteBatchWrapper at line 708
pkg/kv/kvserver/pkg/kv/kvserver/replica_evaluate.go in pkg/kv/kvserver.evaluateBatch at line 294
pkg/kv/kvserver/pkg/kv/kvserver/replica_evaluate.go in pkg/kv/kvserver.evaluateCommand at line 526
pkg/kv/kvserver/batcheval/cmd_conditional_put.go in pkg/kv/kvserver/batcheval.ConditionalPut at line 63
pkg/storage/mvcc.go in pkg/storage.MVCCConditionalPut at line 2341
pkg/storage/mvcc.go in pkg/storage.mvccConditionalPutUsingIter at line 2397
pkg/storage/mvcc.go in pkg/storage.mvccPutUsingIter at line 1548
pkg/storage/mvcc.go in pkg/storage.mvccPutInternal at line 1784
pkg/storage/mvcc.go in pkg/storage.mvccGetMetadata at line 1263
pkg/storage/intent_interleaving_iter.go in pkg/storage.(*intentInterleavingIter).SeekGE at line 482
pkg/storage/pebble_iterator.go in pkg/storage.(*pebbleIterator).SeekGE at line 333
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/iterator.go in github.com/cockroachdb/pebble.(*Iterator).SeekPrefixGE at line 1412
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/range_keys.go in github.com/cockroachdb/pebble.(*lazyCombinedIter).SeekPrefixGE at line 565
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go in github.com/cockroachdb/pebble.(*mergingIter).SeekPrefixGE at line 1120
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go in github.com/cockroachdb/pebble.(*mergingIter).seekGE at line 1044
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/level_iter.go in github.com/cockroachdb/pebble.(*levelIter).SeekPrefixGE at line 752
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/level_iter.go in github.com/cockroachdb/pebble.(*levelIter).loadFile at line 669
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/table_cache.go in github.com/cockroachdb/pebble.(*tableCacheContainer).newIters at line 139
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/table_cache.go in github.com/cockroachdb/pebble.(*tableCacheShard).newIters at line 374
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/table_cache.go in github.com/cockroachdb/pebble.(*tableCacheShard).findNode at line 706
GOROOT/src/runtime/pprof/runtime.go in runtime/pprof.Do at line 40
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/table_cache.go in github.com/cockroachdb/pebble.(*tableCacheShard).findNode.func2 at line 707
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/table_cache.go in github.com/cockroachdb/pebble.(*tableCacheValue).load at line 935
github.com/cockroachdb/pebble/objstorage/external/com_github_cockroachdb_pebble/objstorage/provider.go in github.com/cockroachdb/pebble/objstorage.(*Provider).OpenForReadingMustExist at line 256
github.com/cockroachdb/pebble/objstorage/external/com_github_cockroachdb_pebble/objstorage/vfs.go in github.com/cockroachdb/pebble/objstorage.(*Provider).vfsOpenForReading at line 24
github.com/cockroachdb/pebble/internal/base/external/com_github_cockroachdb_pebble/internal/base/filenames.go in github.com/cockroachdb/pebble/internal/base.MustExist at line 147
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v23.1.9 |
| Go Version | go1.19.10 |
| Platform | linux arm64 |
| Distribution | CCL |
| Cockroach Release | v23.1.9 |
| Cockroach SHA | 28b2e767986169df857f5f2cd1790d71ac633395 |
| # of CPUs | 6 |
| # of Goroutines | 405 |

Jira issue: CRDB-34376

**Comment by yuzefovich** [comment]
unactionable
