### ISSUE TITLE
graphs fail on some error and never come back

### ISSUE THREAD

**Issue by MBerhault** [cockroachdb/cockroach#1160]
See screenshot:
![image](https://cloud.githubusercontent.com/assets/5901480/7842644/8f121604-0472-11e5-84e8-e5987cb8f727.png)

**Comment by MBerhault** [comment]
errors can and probably will happen, but we should probably not display them, or at the very least reload the graph.

**Comment by tamird** [comment]
@MBerhault @mrtracy did you ever get to the bottom of this?

**Comment by mrtracy** [comment]
This was actually fixed that day by #1164
