### ISSUE TITLE
sql: LIMIT not properly applied in INSERT

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#11617]
What did I do:
```
EXPLAIN INSERT INTO foo SELECT * FROM foo LIMIT 20
```

What did I see:
```
0 insert
1 scan
```

What did I expect:
```
0 insert
1 limit
2 scan
```

Note that `INSERT INTO foo SELECT * FROM (SELECT * FROM foo LIMIT 20)` does work properly.

**Comment by knz** [comment]
Note the problem is not with EXPLAIN; the problem is that the select clause after INSERT does not take its LIMIT clause into account properly, resulting in it inserting more rows than specified.

**Comment by yznming** [comment]
@knz I can try to fix it.

**Comment by knz** [comment]
Yes probably this is in your skill set now.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
