### ISSUE TITLE
Support `ALTER COLUMN SET DEFAULT` in declarative schema changer

### ISSUE THREAD

**Issue by Xiang-Gu** [cockroachdb/cockroach#116247]
Let's implement `ALTER TABLE ... ALTER COLUMN .. SET DEFAULT ...` in declarative schema changer. Similarly to the instructions given in #115374, we can start by implementing the logic in the builder layer.

Epic: CRDB-31283

Jira issue: CRDB-34538

**Comment by Xiang-Gu** [comment]
let's ensure we correctly implement to avoid the dangling back-references in the type (if this table's default expression references a type descriptor) as in https://github.com/cockroachdb/cockroach/issues/91972

**Comment by andrew-delph** [comment]
pr: https://github.com/cockroachdb/cockroach/pull/115889
