### ISSUE TITLE
jobs: v23.1.12: nil pointer in Registry.withSession

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#116334]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4722959937/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4722959937/?referrer=webhooks_plugin)

Panic Message:

```
panic.go:884: runtime error: invalid memory address or nil pointer dereference
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | runtime.panicmem
  | 	GOROOT/src/runtime/panic.go:260
  | runtime.sigpanic
  | 	GOROOT/src/runtime/signal_unix.go:839
  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).withSession
  | 	github.com/cockroachdb/cockroach/pkg/jobs/registry.go:997
  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).Start.func11
  | 	github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1012
  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).Start.func8
  | 	github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1130
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (2) runtime error: invalid memory address or nil pointer dereference
Error types: (1) *withstack.withStack (2) runtime.errorString
-- report composition:
runtime.errorString
panic.go:884: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/util/stop/stopper.go#L469-L471](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/util/stop/stopper.go#L469-L471)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/jobs/registry.go#L1129-L1131](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/jobs/registry.go#L1129-L1131)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/jobs/registry.go#L1011-L1013](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/jobs/registry.go#L1011-L1013)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/jobs/registry.go#L996-L998](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/jobs/registry.go#L996-L998)
[GOROOT/src/runtime/signal_unix.go#L838-L840](GOROOT/src/runtime/signal_unix.go#L838-L840)
[GOROOT/src/runtime/panic.go#L259-L261](GOROOT/src/runtime/panic.go#L259-L261)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 470
pkg/jobs/registry.go in pkg/jobs.(*Registry).Start.func8 at line 1130
pkg/jobs/registry.go in pkg/jobs.(*Registry).Start.func11 at line 1012
pkg/jobs/registry.go in pkg/jobs.(*Registry).withSession at line 997
GOROOT/src/runtime/signal_unix.go in runtime.sigpanic at line 839
GOROOT/src/runtime/panic.go in runtime.panicmem at line 260
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
```

### Tags

| Tag | Value |
| --- | --- |
| Command | start-single-node |
| Environment | v23.1.12 |
| Go Version | go1.19.13 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.12 |
| Cockroach SHA | d7e9824b4cd6ebf7a8548156f2a772ae6648257d |
| # of CPUs | 12 |
| # of Goroutines | 405 |

Jira issue: CRDB-34585

**Comment by dt** [comment]
This stack trace doesn't look right; the last line number points to a closing bracket, not a line that de-ref's any pointers, and there are no defers in the function either. Nothing is jumping out about the other implicated lines either: the stack trace says the `cancelLoopTask` in the loop is in the call stack, but we also see it invoked above the loop so it doesn't seem like we're passing a nil ctx or fn. I don't think we have enough information here to take any further action.
