### ISSUE TITLE
Null Values in Identity Column Attributes When Created Without Sequence Options

### ISSUE THREAD

**Issue by andrew-delph** [cockroachdb/cockroach#116327]
**Describe the problem**

There seems to be a discrepancy in the behavior of identity columns in when they are created without specifying sequence options.

**To Reproduce**

1. Create a table with an identity column without any sequence options:
`
CREATE TABLE test_table (id SERIAL PRIMARY KEY, a int GENERATED ALWAYS AS IDENTITY, b int GENERATED ALWAYS AS IDENTITY (START WITH 5));
`
2. Execute a query on information_schema.columns for identity attributes:
`SELECT table_name, column_name, identity_start, identity_increment, identity_maximum, identity_minimum, identity_cycle FROM information_schema.columns WHERE table_name = 'test_table';`

**Expected behavior**
All identity attributes (identity_start, identity_increment, identity_maximum, identity_minimum, identity_cycle) should have default values, similar to how column b is handled when created with specific sequence options.

**Additional Context**
I have initiated a pull request [link](https://github.com/andrew-delph/cockroach/pull/4/files), which partially addresses this issue. The PR sets `GeneratedAsIdentitySequenceOption` to an empty string in cases where no options are provided. This adjustment results in the default values being applied to the information_schema for identity columns. However, further refinements seem necessary. Specifically, when altering sequence options, there appears to be a lack of a mechanism to merge `GeneratedAsIdentitySequenceOption` (a string) with the new `tree.SequenceOptions`. This suggests that additional fixes might be required to fully resolve the issue.

Jira issue: CRDB-34582

**Comment by yuzefovich** [comment]
IIRC #115889 resolved this
