### ISSUE TITLE
put acceptance test grinds to a standstill/oom error due to range split intents

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#1163]
see #1150 for first investigation (which sparked #1161 and #1150), further comments go here.

Basically the put test will, once splits are happening, lose a lot of velocity due to a massive amount of push congestion on the range descriptors (while the update transaction is running), eventually sucking up all memory or simply not making progress at all.

`TESTS=TestPut TESTTIMEOUT=24h TESTFLAGS="-d 600s" acceptance/run.sh`

can be used to see this. Usually the first split happens in under a minute; on my machine everything crashes/stops making progress at ~32k keys, though the logs look horrible way earlier.

The following comes in handy (run after the test has started):

`export CONTAINER=$(docker ps --no-trunc | grep data0 | awk '{print $1}') && docker logs -f $CONTAINER 2>&1 | tee acceptance.log`

**Comment by petermattis** [comment]
I tried to make the problem occur faster by setting `RangeMaxBytes` in `Store.BootstrapRange` to `2MB`.  The test still makes progress up to somewhere around ~40k keys after having split ~70-80 times. Perhaps the splitting isn't the cause of the eventual wedging.

**Comment by tschottdorf** [comment]
I'm looking at this again. So far can only note that once you turn off splits, the thing breezes through. Turning on splits but keeping it single-node also seems to remove the problem. When broken, I've been seeing the DistSender repeatedly (forever) sending clients to the wrong range (the one before the split), and launching ten thousands of goroutines (from `Range.handleSkippedIntents`) in the progress. Will continue cornering this.

**Comment by tschottdorf** [comment]
#1655 fixed one bug that could happen here (the gc queue would read inconsistent meta descriptors, which could cause it to consider the right side of a split collectable) but there are plenty of issues left:

* the new range can't make Raft progress until about 2 seconds after it's created. Not new: #1384. This negatively influences:
* the command queue can fill up pretty quickly while the split transaction is running. in particular, the `EndTransaction` call itself may get stuck in it so long that the `DistSender` abandons the request (actually not before sending the request to the other peers, which aren't leaders - doesn't help) and retries. That means that the split is carried out, but `DistSender` doesn't know until it retries the command **successfully**. But the split has been carried out, so `DistSender`'s cache is now stale, but the intent likely still there (because resolving it is async, and the command queue is congested). So now the retry and a bunch of range lookups have to make it through Raft before `EndTransaction` hits the response cache, and will time out at the `DistSender` a lot of times until it gets lucky. As if that weren't enough, we also have leader leases, and if the time spent in Raft is higher than the lease duration, your chance of failing when you're about to be applied is two out of three (because in this test, range leadership jumps randomly; we're writing at all nodes and have no concept of stickyness)
* That in turn spawns a lot of goroutines because any time we hit the intent, there's a new one and we're retrying in a hot-loop at this point. They also congest the command queue more, commands will now wait for a couple of seconds and pretty much everything times out.

I suspect that this is enough to completely congest everything permanently, until OOM occurs. Things to do:

- fix #1384
- avoid launching a lot of async resolvers for ignored intents: `handleSkippedIntents` could check the command queue and not try to resolve if there's something blocking in it already (this assumes of course that `handleSkippedIntents` is only called after the command that collected the intents left the command queue)
- use hard timeouts on individual requests only as a last resort on the sending side - much time is spent on the nodes, not in transit (not only in tests like these when there is contention). Instead, make use of the fact that all clients send through our `rpc` package to keep better node health there, taking into account all traffic from/to it (based on last response, connection status, average peer latency). See #1633.
- for requests which need to go to a leader, **only** try to send to it. Our `rpc` wrapping should make sure we find out quickly if we don't make it there, at which point we clear out the cache and retry (randomly).
- both the range descriptor cache and the leader cache are racy in the sense that work is done a lot of times (i.e. a missing descriptor causes all requests to query them when really they should wait for the first; for the leader cache all requests will fire randomly until the first `NotLeaderError` comes back - that could also just block other requests). Of course, leadership should be stable anyways, having to fire randomly every second isn't a good long-term option.
- once we pass a deadline along with the `context.Context`, aggressively cancel commands when they expire (in particular, store-level retry loops, maybe Raft but it's impossible to un-propose anything). This is probably a finer point, but worth thinking about when the more obvious issues are under control and serves to make sure that we don't run things on the node that `DistSender` has already given up on.


There's a [Trace](https://gist.github.com/tschottdorf/a9908067dae02160bd76) here that contains most of the above information. Just sort it to order it absolutely with respect to time.

I'm going to eyeball which of the above is the worst offender and tackle that (plus play around with not resolving intents asynchronously, which shouldn't be necessary if the txn coordinator's cleanup goes through fine, at least on the put test).

**Comment by bdarnell** [comment]
Another meta-issue: for production use, timeouts need to be set high enough that they are only reached in exceptional situations. Our timeouts are generally too low for the current performance of the system. On the other hand, for testing purposes it's good to use timeouts that are both unrealistically high (to detect and prevent death-spiral issues like this) and unrealistically low (to ensure that we do not rely too much on timeout-based retries).

Do you know what makes the EndTransaction call take so long? If it's the response cache, we should prioritize the work to purge response cache entries once the clients have consumed the response (@spencerkimball has talked about this, but I don't think there's a tracking issue yet). 

There seem to be several places where statelessness hurts us: intent resolution, range descriptor caching, and leader caching. A general read-through cache or similar abstraction might be useful here.

**Comment by tschottdorf** [comment]
it's pretty much all of the above points, but in particular the full command queue (due to slow Raft elections) and the low timeout in `rpc/send.go` leading to a stale descriptor entry with the `EndTransaction` call still running (but the Txn committed). Then there's also the issue that the intent isn't seen at the `DistSender` level except by 50% of PushTxn-related lookups (so basically nothing compared to all the other stuff frantically retrying), and that those lookups race (so whenever you get lucky, likely the wrong thing by a non-PushTxn will overwrite it immediately).
I'm working on a small change to dump traces periodically when the request runs for too long so that I can actually track the call when it goes *horribly* wrong (so far I've only seen traces where it went pretty badly, but eventually made it - say after 18 seconds).

**Comment by tschottdorf** [comment]
With RPC timeouts practically disabled (and some other tweaks) the Put test runs smoother. Now it dies because of RocksDB:

```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
SIGABRT: abort
PC=0x7f80b77c5107
signal arrived during cgo execution
```

approximately 127k keys in.

**Comment by tschottdorf** [comment]
We'll also need a little bit more Raft logging since congestion seems to hit it fairly hard as well:

```
Name                 Origin             Ts               Dur           Desc
        File
c548178739974282.35  roach0.local:8080  17:09:38.816464  2.419918382s  node
        server/node.go:467
c548178739974282.35  roach0.local:8080  17:09:38.816518  2.419825814s  ·executing Put
        storage/store.go:1261
c548178739974282.35  roach0.local:8080  17:09:38.816527  17.829µs      ··command queue
        storage/range.go:685
c548178739974282.35  roach0.local:8080  17:09:38.816549  3.389µs       ··checking leader lease
        storage/range.go:380
c548178739974282.35  roach0.local:8080  17:09:38.816559  2.41977914s   ··raft                                storage/range.go:727
c548178739974282.35  roach0.local:8080  17:09:41.236055  83.335µs      ···applying Put                       storage/range.go:806
c548178739974282.35  roach0.local:8080  17:09:41.236376  0             ·error: *proto.RangeKeyMismatchError  server/node.go:473
```

**Comment by tamird** [comment]
@tschottdorf what's the status of this?

**Comment by tschottdorf** [comment]
unfinished. This is one of the tests that stresses various parts of the system and easily clogs. I haven't run it in a while, but definitely will again with the batch-related refactors. But the original issue (that it crashes due to intents) is resolved, so let's close this and reopen another with specific issues as we find them.
