### ISSUE TITLE
BUG: ADD COLUMN does not populate column default

### ISSUE THREAD

**Issue by kf6nux** [cockroachdb/cockroach#116301]
# steps to reproduce

I found a bug where ADD COLUMN does not populate column default.
I expect these two actions to be equivalent:

**Action 1** (two schema change jobs):
```SQL
ALTER TABLE tab 
  ADD COLUMN col BOOL NOT NULL DEFAULT true;
ALTER TABLE tab
  ALTER COLUMN col DROP DEFAULT, 
  ALTER COLUMN col DROP NOT NULL;
  ```
**Action 2** (one schema change job):
```SQL
ALTER TABLE tab 
  ADD COLUMN col BOOL NOT NULL DEFAULT true, 
  ALTER COLUMN col DROP DEFAULT, 
  ALTER COLUMN col DROP NOT NULL;
```
  
**Post Action 1:**
  ```SQL
  SELECT COUNT(*) from tab where col = true;                                                                                                        
   count
-----------
1805612
  ```
  i.e. count == total rows at time of schema change
  
**Post Action 2:**
  ```SQL
  SELECT COUNT(*) from tab where col = true;                                                                                                        
   count
-----------
0
  ```
i.e. count always == 0, regardless of rows present in table

# versions
Server 
```
V23.1.12
```
Client 
```
Build Tag:        v23.1.4
Build Time:       2023/06/16 20:54:39
Distribution:     CCL
Platform:         darwin amd64 (x86_64-apple-darwin19)
Go Version:       go1.19.4
C Compiler:       Clang 10.0.0 
Build Commit ID:  cf85e8ad48bb7a8afd821863d4f345baafa4a1b6
Build Type:       release
Enabled Assertions: false
```

Jira issue: CRDB-34565

**Comment by Xiang-Gu** [comment]
I don't think this is a bug; in your scenario 2 where you put all three cmds in one statement where you created a column with default (and not null) and then drop the default (and not null). The net effect is that you are saying you just want to create a column without any default (nor not null).
In your scenario 1, however, you first added the column with default (and not null) and wait for it to complete. This will trigger a backfill with the 'true' default value filled on this new column on all rows. Later, when you drop the default (and not null) on the column, no data got changed, and you thus see all rows with `true` on the new column.

**Comment by annrpom** [comment]
closing since this seems resolved - feel free to reopen if there's anything else we missed

**Comment by kf6nux** [comment]
I think this is an obvious footgun.
If I ran into it, others probably will as well.

If this is going to be treated as a conflicting statement where CRDB optimizes out a portion of the schema change instruction, it should reject the schema change request rather than disregard the intent of the statement.

**Comment by kf6nux** [comment]
> feel free to reopen
@annrpom I don't think I have permissions to re-open the issue.

**Comment by Xiang-Gu** [comment]
@kf6nux I understood your point. Maybe we can open a Doc issue to make this more explicit. 
@rmloveland Do you think we can add some clarifying sentences somewhere about multiple-cmds-in-one-stmt could have cancelling effects?

**Comment by fqazi** [comment]
I think other point is that, the first set of operations are two implicit transactions versus the second case where you have a implicit single transaction. From a transactional view point the second case is more a question of what happens when both operations are atomic, and a valid answer maybe they get cancelled.

**Comment by kf6nux** [comment]
If documenting the footgun is the desired path, I'm guessing the place to document it would be in the [subcommands section of Alter Table](https://www.cockroachlabs.com/docs/v23.1/alter-table#subcommands).
Perhaps a WARNING section above the existing TIP section along the lines of:
> WARNING: 
> If multiple subcommands conflict, the db may either reject the entire statement or use the final resulting schema as the only schema change to be processed.
