### ISSUE TITLE
Transition from AWS SDK V1 to V2

### ISSUE THREAD

**Issue by udnay** [cockroachdb/cockroach#116320]
CRDB currently uses the [AWS SDK V1 for go](https://github.com/aws/aws-sdk-go) which does not support some features, for example [multi-region access points for s3](https://docs.aws.amazon.com/sdkref/latest/guide/feature-s3-mrap.html). 

CRDB already uses [AWS SDK V2](https://github.com/aws/aws-sdk-go-v2) for some DMS integrations and testing.

**Describe the solution you'd like**
We standardize S3 and KMS access through V2 of the SDK and remove V1 of the SDK. We would need to migrate [s3_storage.go](https://github.com/cockroachdb/cockroach/blob/28457a0ac0464f58fe617728139bd1134dbe75ca/pkg/cloud/amazon/s3_storage.go) and [aws_kms.go](https://github.com/cockroachdb/cockroach/blob/28457a0ac0464f58fe617728139bd1134dbe75ca/pkg/cloud/amazon/aws_kms.go) plus tests over to the new SDK.

Jira issue: CRDB-34577

**Comment by adityamaru** [comment]
I'm not sure we want this marked as quick-win/starter, this is on the DR roadmap for 24.1 and have chalked out time to work on it early on in the release.

**Comment by andrewbaptist** [comment]
Makes sense! I didn't realize this was on a roadmap. It seemed "self contained" enough that it might have been a good project. We are trying to tag these types of issues in KV to have projects for either community contributions or new engineers/interns.

**Comment by adityamaru** [comment]
This is almost done in https://github.com/cockroachdb/cockroach/pull/115628, I'm going to tentatively reassign this to @stevendanna since he was reviewing the PR.
