### ISSUE TITLE
pkg/util/metric: reuse same Histogram window for each quantile calculation

### ISSUE THREAD

**Issue by abarganier** [cockroachdb/cockroach#116325]
**Is your feature request related to a problem? Please describe.**
When TSDB scrapes metrics registries, it doesn't store histograms in their entirety. Instead, we calculate a [predefined set of quantiles](https://github.com/cockroachdb/cockroach/blob/50a47aa0b457821da7ec3831f32eee8d397fe4d0/pkg/util/metric/metric.go#L1052-L1061) against the latest histogram window, and store the quantiles instead. 

When doing so, currently we're writing the latest histogram window **once per quantile calculation**. Beyond being wasteful & contributing heavily to the overall # of heap allocations, it also means that each quantile calculation is computed against a potentially different histogram window, providing inconsistent results.

**Describe the solution you'd like**
When calculating quantiles for TSDB we should:
1. Only grab the current histogram window **once** to calculate quantiles against.
2. Use the same histogram window for all quantile calculations, to ensure consistent results.

Jira issue: CRDB-34580

**Comment by petermattis** [comment]
The recorder code currently converts to a prometheus metric for the calls to `Total` and `MeanWindowed` as well. Whatever is done here should optimize for a single prometheus metric conversion per `extractValue()` call. As I'm sure you know, there are multiple implementations of `WindowedHistogram` so a modest amount of thought needs to be applied.

**Comment by yuzefovich** [comment]
Re-opening until #116581 is backported to 23.2.0-rc branch (which I think was the intention for this issue).

**Comment by michae2** [comment]
Nice job @abarganier!
