### ISSUE TITLE
backupccl: goroutine spike during backup

### ISSUE THREAD

**Issue by andrewbaptist** [cockroachdb/cockroach#116470]
**Describe the problem**

When a backup is taken on a system with a large number of ranges, we see a spike in goroutines and a consequent increase in latency on the system. This can cause AC to kick in and make the impact worse.

**To Reproduce**

Create a cluster with a large number of ranges:
```
roachprod create -n 13 $CLUSTER --local-ssd
# This works fine
# roachprod stage $CLUSTER release v23.1.12 

gsutil cp gs://cockroach-release-artifacts-staged-prod/cockroach-v23.2.0-beta.2.linux-amd64.tgz ./
roachprod  put $CLUSTER artifacts/cockroach-v23.2.0-beta.2.linux-amd64/cockroach

roachprod start $CLUSTER:1-12
roachprod ssh $CLUSTER:1 "./cockroach workload init kv {pgurl:1} --splits 20000"
```

Start a workload with a relatively low throughput but let it run for about 30 minutes tto get sufficient data:
```
roachprod ssh $CLUSTER:13 "./cockroach workload run kv {pgurl:1-12} --concurrency 256 --max-block-bytes=16384 --max-rate 5000"
```

Start a backup job
```
BACKUP INTO 'gs://cockroachdb-backup-testing/roachprod-scheduled-backups/backup-test?AUTH=implicit' AS OF SYSTEM TIME '2023-12-14 16:08:00.004526+00';
```

**Expected behavior**
For a heavily loaded system, it is expected that there will be some slowdown during a backup, so they are typically scheduled at night. The impact is too large and is caused by the high number of goroutines on the leaseholder of the meta1 range. 

**Additional data / screenshots**

**Environment:**
Tested on 23.1 and 23.2. 
In 23.1 - there is minimal impact from the backup and goroutines spike evenly across the cluster, in 23.2 there is a large impact on the leaseholder of the meta1 range: 
23.1:
<img width="877" alt="image" src="https://github.com/cockroachdb/cockroach/assets/46975918/225c22e5-1bb0-40f8-bc9e-e92e5b50b230">
<img width="873" alt="image" src="https://github.com/cockroachdb/cockroach/assets/46975918/9badf171-0d10-4581-b1d3-d71a358636fe">

23.2
<img width="868" alt="image" src="https://github.com/cockroachdb/cockroach/assets/46975918/33e7f7b9-be5c-429c-be0c-ce942f1ed23a">
<img width="864" alt="image" src="https://github.com/cockroachdb/cockroach/assets/46975918/4c4a197a-676f-40a4-af3d-6a60462ff204">

**Additional context**
Attached is the goroutine dump for 23.2 
Non-leaseholder node:
[goroutine-DR.txt](https://github.com/cockroachdb/cockroach/files/13677355/goroutine-DR.txt)

Leaseholder node:
[goroutine-DR.txt](https://github.com/cockroachdb/cockroach/files/13677403/goroutine-DR.txt)

Jira issue: CRDB-34636

**Comment by dt** [comment]
What do we think the misbehavior of backup is here? 

>  spike in goroutines and a consequent increase in latency on the system

I see 9 goroutines with "backupccl" in their stack, only one of which is runnable. Is one runnable goroutine a spike?

**Comment by andrewbaptist** [comment]
I haven't had enough time to track down the root cause of this, but it is significantly different in 23.1 and 23.2. In 23.1 we see a small but even goroutine spike across all nodes while in 23.2 we see a large number of runnable goroutines on the one node - (~80 extra). I haven't figured out why it is causing the concentrated spike.

**Comment by dt** [comment]
Hm. The _one_ that is runnable is interesting. Specifically, it is on this line:

```
rdi, err := flowCtx.Cfg.ExecutorConfig.(*sql.ExecutorConfig).RangeDescIteratorFactory.NewIterator(ctx, fullSpan)
```

When I look at the implementation of this function, it scans the entirety of the rangedescs:
```go
err := i.Scan(ctx, 0 /* pageSize */, func() {
		rangeDescriptors = rangeDescriptors[:0] // retryable
	}, span, func(descriptors ...roachpb.RangeDescriptor) error {
		rangeDescriptors = append(rangeDescriptors, descriptors...)
		return nil
	})
```
https://github.com/dt/cockroach/blob/master/pkg/util/rangedesc/rangedesc.go#L208-L221

This seems... less than idea?

**Comment by dt** [comment]
It looks like `RangeDescIteratorFactory.NewIterator` should just read some page-worth of range descs into a buffer, hand out results from the buffer until it is exhausted, then have a `fill` method it calls to refill it with the next page as needed, instead of eagerly reading the entire span into a single slice.

**Comment by andrewbaptist** [comment]
Fixed by https://github.com/cockroachdb/cockroach/pull/116562
