### ISSUE TITLE
enable hashjoin is not supported

### ISSUE THREAD

**Issue by SilicalNZ** [cockroachdb/cockroach#116508]
```sql
SET enable_hashjoin = off;                                                                                                                                                                                                    
ERROR: unimplemented: the configuration setting "enable_hashjoin" is not supported
SQLSTATE: 0A000
HINT: You have attempted to use a feature that is not yet implemented.

Please check the public issue tracker to check whether this problem is
already tracked. If you cannot find it there, please report the errora
with details by creating a new issue.
```

I see this was previously reported in this issue, but seems to have been closed without being resolved;
https://github.com/cockroachdb/cockroach/issues/20544

This is helpful to have for debugging optimization strategies.

**Comment by yuzefovich** [comment]
What are you trying to achieve?

We don't have a way to force or prohibit a particular join type at the session level, but we do have join hints (see [docs](https://www.cockroachlabs.com/docs/v23.2/cost-based-optimizer#join-hints)) that you can apply on a per query basis - e.g. `SELECT * FROM t1 INNER HASH JOIN t2 ON t1.k1 = t2.k2` will force the usage of the hash join algorithm.

I don't think we'll want to expose a session variable to force a particular join type, so I'm closing this issue (happy to continue the discussion though to help you find a reasonable workaround).
