### ISSUE TITLE
log: allow a user to filter all logging and limit the amount of logging data preserved

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#11654]
Two issues reported in https://forum.cockroachlabs.com/t/how-to-start-cdb-without-info-or-warning-logs/371:

- currently it is not possible to filter out which logging levels are written to files. Although it is possible to select which severity is printed to stderr, it is not possible to do so with files.

- ~~if there is at least one on-disk store, it is not possible to disable the output of logs to files entirely (e.g. `--log-dir=""` will cause a logging directory to be selected automatically, and `--log-dir=/dev/null` fails with an error).~~ (this has been fixed already)

- when logs are output to files, it is not possible to constrain how much log data is preserved over time.

**Comment by dianasaur323** [comment]
@knz I'm going to assign you to this one. It seems to make sense to support this usability feature in the 1.0, but also not necessarily a blocker. We can leave it in for 1.0 for now, and you can move it out if you think that would be more appropriate.
