### ISSUE TITLE
workload/schemachange: failures when run concurrently with upgrade migrations

### ISSUE THREAD

**Issue by renatolabs** [cockroachdb/cockroach#116586]
We have seen a number of flakes (and a few different failure modes) when running the `schemachange` workload concurrently with upgrade migrations (to 22.2, 23.1 and master/23.2). In order to stop flakes, we stopped running `schemachange` during migrations in `acceptance/version-upgrade`, but we should eventually enable it again once the failures are addressed.

See [this comment](https://github.com/cockroachdb/cockroach/issues/116304#issuecomment-1856520474) for more details.

Jira issue: CRDB-34676

**Comment by rafiss** [comment]
We should reenable this once https://github.com/cockroachdb/cockroach/issues/116649 is resolved.

**Comment by celiala** [comment]
(perhaps https://github.com/cockroachdb/cockroach/pull/116587 can be reverted, now that https://github.com/cockroachdb/cockroach/issues/116649 is resolved?)

**Comment by renatolabs** [comment]
It's a good question. There have a been a number of changes recently to the schemachange workload that weren't backported, so maybe we should reenable it just for the previous->master upgrade.

I'll defer to @cockroachdb/sql-foundations for the official answer.
