### ISSUE TITLE
Sentry: error.go:89: unexpected error from the vectorized engine: runtime error: slice bounds out of range [26:25]
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.co...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#116652]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4734766792/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4734766792/?referrer=webhooks_plugin)

Panic Message:

```
error.go:89: unexpected error from the vectorized engine: runtime error: slice bounds out of range [26:25]
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:89
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | runtime.goPanicSliceB
  | 	GOROOT/src/runtime/panic.go:153
  | github.com/cockroachdb/cockroach/pkg/util/encoding.DecodeUntaggedBytesValue
  | 	github.com/cockroachdb/cockroach/pkg/util/encoding/encoding.go:2709
  | github.com/cockroachdb/cockroach/pkg/sql/rowenc/valueside.DecodeUntaggedDatum
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowenc/valueside/decode.go:64
  | github.com/cockroachdb/cockroach/pkg/sql/rowenc/valueside.Decode
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowenc/valueside/decode.go:42
  | github.com/cockroachdb/cockroach/pkg/sql/rowenc.(*EncDatum).EnsureDecoded
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowenc/encoded_datum.go:256
  | github.com/cockroachdb/cockroach/pkg/sql/rowenc.EncDatumRowToDatums
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowenc/encoded_datum.go:486
  | github.com/cockroachdb/cockroach/pkg/sql.(*rowContainerIterator).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/buffer_util.go:172
  | github.com/cockroachdb/cockroach/pkg/sql.(*scanBufferNode).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/buffer.go:90
  | github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:211
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Columnarizer).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/columnarizer.go:243
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:116
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:124
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecsel.(*selGETimestampTimestampConstOp).Next
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/colexec/colexecsel/selection_ops.eg.go:56081
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecsel.(*selEQInt64Int64ConstOp).Next
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/colexec/colexecsel/selection_ops.eg.go:5767
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:116
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:124
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*ParallelUnorderedSynchronizer).Init.func1.1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/parallel_unordered_synchronizer.go:191
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*ParallelUnorderedSynchronizer).init.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/parallel_unordered_synchronizer.go:255
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (3) unexpected error from the vectorized engine
Wraps: (4) runtime error: slice bounds out of range [26:25]
  | -- cause hidden behind barrier
  | runtime error: slice bounds out of range [26:25]
  | (1) runtime error: slice bounds out of range [26:25]
  | Error types: (1) runtime.boundsError
Error types: (1) *assert.withAssertionFailure (2) *withstack.withStack (3) *errutil.withPrefix (4) *barriers.barrierErr
-- report composition:
*barriers.barrierErr: masked error: runtime error: slice bounds out of range [26:25]
*errutil.withPrefix: unexpected error from the vectorized engine
error.go:89: *withstack.withStack (top exception)
*assert.withAssertionFailure
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/colexec/parallel_unordered_synchronizer.go#L254-L256](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/colexec/parallel_unordered_synchronizer.go#L254-L256)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/colexec/parallel_unordered_synchronizer.go#L190-L192](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/colexec/parallel_unordered_synchronizer.go#L190-L192)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/colflow/stats.go#L123-L125](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/colflow/stats.go#L123-L125)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/colflow/stats.go#L115-L117](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/colflow/stats.go#L115-L117)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/bazel-out/k8-opt/bin/pkg/sql/colexec/colexecsel/selection_ops.eg.go#L5766-L5768](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/bazel-out/k8-opt/bin/pkg/sql/colexec/colexecsel/selection_ops.eg.go#L5766-L5768)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/bazel-out/k8-opt/bin/pkg/sql/colexec/colexecsel/selection_ops.eg.go#L56080-L56082](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/bazel-out/k8-opt/bin/pkg/sql/colexec/colexecsel/selection_ops.eg.go#L56080-L56082)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/colflow/stats.go#L123-L125](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/colflow/stats.go#L123-L125)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/colflow/stats.go#L115-L117](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/colflow/stats.go#L115-L117)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/colexec/columnarizer.go#L242-L244](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/colexec/columnarizer.go#L242-L244)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/plan_node_to_row_source.go#L210-L212](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/plan_node_to_row_source.go#L210-L212)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/buffer.go#L89-L91](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/buffer.go#L89-L91)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/buffer_util.go#L171-L173](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/buffer_util.go#L171-L173)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/rowenc/encoded_datum.go#L485-L487](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/rowenc/encoded_datum.go#L485-L487)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/rowenc/encoded_datum.go#L255-L257](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/rowenc/encoded_datum.go#L255-L257)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/rowenc/valueside/decode.go#L41-L43](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/rowenc/valueside/decode.go#L41-L43)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/rowenc/valueside/decode.go#L63-L65](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/rowenc/valueside/decode.go#L63-L65)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/util/encoding/encoding.go#L2708-L2710](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/util/encoding/encoding.go#L2708-L2710)
[GOROOT/src/runtime/panic.go#L152-L154](GOROOT/src/runtime/panic.go#L152-L154)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/colexecerror/error.go#L88-L90](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/colexecerror/error.go#L88-L90)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/sql/colexec/parallel_unordered_synchronizer.go in pkg/sql/colexec.(*ParallelUnorderedSynchronizer).init.func1 at line 255
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colexec/parallel_unordered_synchronizer.go in pkg/sql/colexec.(*ParallelUnorderedSynchronizer).Init.func1.1 at line 191
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).Next at line 124
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).next at line 116
bazel-out/k8-opt/bin/pkg/sql/colexec/colexecsel/selection_ops.eg.go in pkg/sql/colexec/colexecsel.(*selEQInt64Int64ConstOp).Next at line 5767
bazel-out/k8-opt/bin/pkg/sql/colexec/colexecsel/selection_ops.eg.go in pkg/sql/colexec/colexecsel.(*selGETimestampTimestampConstOp).Next at line 56081
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).Next at line 124
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).next at line 116
pkg/sql/colexec/columnarizer.go in pkg/sql/colexec.(*Columnarizer).Next at line 243
pkg/sql/plan_node_to_row_source.go in pkg/sql.(*planNodeToRowSource).Next at line 211
pkg/sql/buffer.go in pkg/sql.(*scanBufferNode).Next at line 90
pkg/sql/buffer_util.go in pkg/sql.(*rowContainerIterator).Next at line 172
pkg/sql/rowenc/encoded_datum.go in pkg/sql/rowenc.EncDatumRowToDatums at line 486
pkg/sql/rowenc/encoded_datum.go in pkg/sql/rowenc.(*EncDatum).EnsureDecoded at line 256
pkg/sql/rowenc/valueside/decode.go in pkg/sql/rowenc/valueside.Decode at line 42
pkg/sql/rowenc/valueside/decode.go in pkg/sql/rowenc/valueside.DecodeUntaggedDatum at line 64
pkg/util/encoding/encoding.go in pkg/util/encoding.DecodeUntaggedBytesValue at line 2709
GOROOT/src/runtime/panic.go in runtime.goPanicSliceB at line 153
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1 at line 89
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v22.2.7 |
| Go Version | go1.19.6 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v22.2.7 |
| Cockroach SHA | cbe33971930ee972e639203a73f14240b92aeff4 |
| # of CPUs | 4 |
| # of Goroutines | 504 |

Jira issue: CRDB-34703

**Comment by yuzefovich** [comment]
unactionable
