### ISSUE TITLE
storage: separate out concurrency limit for download-only compactions

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#116679]
We may elect to run these at higher concurrency since getting data local can have a larger benefit on foreground traffic than normal compaction that just reduce read-amp. A separate limit would also simplify the interactions of dynamic adjustments.

Jira issue: CRDB-34713

**Comment by jbowens** [comment]
We need to be careful to not exhaust available write bandwidth. This is the reason we don't default to higher compaction concurrency already today.

**Comment by RaduBerinde** [comment]
Fixed by https://github.com/cockroachdb/pebble/pull/3445.
