### ISSUE TITLE
stability: delta node experiencing wedged proposals

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#11667]
At least one node on `delta` is experiencing wedged proposals. This is visible in the [`/debug/requests`](https://github.com/cockroachdb/cockroach/files/617451/_debug_requests.htm.zip) page on `104.196.175.87`:

For one of the requests, there have been at least 499 `retry proposal` events, 483 for `reasonTicks`, 15 for `reasonSnapshotApplied` and 1 for `reasonNewLeader`. 

These wedged proposals were noticed when investigating spiky performance that started occurring shortly after the last round of splits:

<img width="844" alt="screen shot 2016-11-28 at 3 56 06 pm" src="https://cloud.githubusercontent.com/assets/6201335/20685649/37ea9c0c-b583-11e6-919c-77c5cecec69d.png">

<img width="936" alt="screen shot 2016-11-28 at 3 54 23 pm" src="https://cloud.githubusercontent.com/assets/6201335/20685648/37ea2b64-b583-11e6-96e4-dc78e62e44b5.png">

**Comment by petermattis** [comment]
The range mentioned in the above `/debug/requests` (`r272`) seems to have cleared itself, but another range is now having problems (`r36`). The Raft page shows:

```
"state": {
                "raftAppliedIndex": "2026373",
                "leaseAppliedIndex": "2019578",
                "desc": {
                  "rangeId": "36",
                  "startKey": "u4n9O/msQZbmtCYSMTdkMTQzZTAtZTU0Yi00YTczLWI5ZjItZThjYjlmMzg3OGJkAAH3Alc=",
                  "endKey": "u4n9PDof2k/Hxf8SYzYzNzk0MjItZGFjMS00YmFlLTg3YjUtZjUyMmM3ZGI3ODkzAAH4AQr+",
                  "replicas": [
                    {
                      "nodeId": 2,
                      "storeId": 4,
                      "replicaId": 1
                    },
                    {
                      "nodeId": 4,
                      "storeId": 7,
                      "replicaId": 2
                    },
                    {
                      "nodeId": 7,
                      "storeId": 13,
                      "replicaId": 3
                    }
                  ],
                  "nextReplicaId": 4
                },
```

The interesting bit to me about this is that the current replicas were the original replicas for this range. And notice that `leaseAppliedIndex` is significantly less than `raftAppliedIndex`. I think that implies that nothing is going through for this range.

Cc @cockroachdb/stability

**Comment by petermattis** [comment]
I wonder if there is a problem with `AdminTransferLease`. I need to step away for a bit, but if anyone else has the time we should look to see if there is lease activity immediately preceding the ranges getting wedged. I think we log when leases are acquired.

**Comment by petermattis** [comment]
Finally looked at the logs briefly. Perhaps these really slow snapshot applications are causing problems:

```
I161128 21:45:42.673801 103820339 storage/replica_raftstorage.go:629  [n4,s7,r40/2:/Table/51/1/{285454…-303465…}] applied Raft snapshot in 10484ms [clear=6009ms batch=2202ms entries=0ms commit=2272ms]
```

Grep'ing the logs on `104.196.175.87` shows we're applying Raft snapshots very frequently. I believe we don't throttle Raft snapshot application.

**Comment by petermattis** [comment]
The number of "Normal" snapshots (a.k.a. Raft initiated snapshots) is way too high on `delta`:

<img width="931" alt="screen shot 2016-11-29 at 10 00 24 am" src="https://cloud.githubusercontent.com/assets/6201335/20714695/c8543842-b61a-11e6-88f8-b0023f0d82ea.png">

**Comment by tamird** [comment]
The proposal death spiral just reproduced in https://teamcity.cockroachdb.com/downloadBuildLog.html?buildId=71140

heads up, this is a 70MB log file.

**Comment by petermattis** [comment]
FYI, @tamird's comment is that the infinite reproposal problem seems to reproduce on top of #11699. With that PR, run:

```
make stress PKG=./storage TESTS=TestRemovePlaceholderRace TESTTIMEOUT=30s
```

I'm investigating, though probably won't get too far tonight.

Cc @cockroachdb/stability, @bdarnell

**Comment by bdarnell** [comment]
We're applying snapshots repeatedly for the same range in some cases:

```
I161129 21:25:37.913225 192460351 storage/replica_raftstorage.go:629  [n4,s7,r487/4:/Table/51/1/53{41633…-50511…}] applied Raft snapshot in 27138ms [clear=17914ms batch=1612ms entries=0ms commit=7377ms]
I161129 21:25:55.292077 192465067 storage/replica_raftstorage.go:629  [n4,s7,r487/4:/Table/51/1/53{41633…-50511…}] applied Raft snapshot in 14587ms [clear=8627ms batch=2411ms entries=0ms commit=3531ms]
I161129 21:26:30.154896 192467584 storage/replica_raftstorage.go:629  [n4,s7,r487/4:/Table/51/1/53{41633…-50511…}] applied Raft snapshot in 22980ms [clear=14483ms batch=5074ms entries=0ms commit=3218ms]
I161129 21:26:59.983206 192475227 storage/replica_raftstorage.go:629  [n4,s7,r487/4:/Table/51/1/53{41633…-50511…}] applied Raft snapshot in 16911ms [clear=10562ms batch=4004ms entries=0ms commit=2296ms]
I161129 21:27:27.106213 192478966 storage/replica_raftstorage.go:629  [n4,s7,r487/4:/Table/51/1/53{41633…-50511…}] applied Raft snapshot in 20153ms [clear=12622ms batch=4402ms entries=0ms commit=3115ms]
I161129 21:27:54.538680 192484887 storage/replica_raftstorage.go:629  [n4,s7,r487/4:/Table/51/1/53{41633…-50511…}] applied Raft snapshot in 19837ms [clear=11316ms batch=3851ms entries=1ms commit=4371ms]
I161129 21:28:22.068905 192487230 storage/replica_raftstorage.go:629  [n4,s7,r487/4:/Table/51/1/53{41633…-50511…}] applied Raft snapshot in 21001ms [clear=15201ms batch=2861ms entries=0ms commit=2871ms]
```

This death spiral can occur any time the rate of growth in the raft log allows it to reach the upper limit in less time than it takes to transfer and apply a snapshot. The most general solution to this problem requires introducing backpressure so that the raft log stops growing when we're trying to catch up a node that is behind but responsive via a snapshot. (we can't usefully throttle raft snapshot application; we have to throttle the operations that are responsible for the log growth or the nodes that are behind will just fall further behind).

We could also consider a node unhealthy when it needs multiple raft snapshots and start rebalancing away from it, but it's unclear how much of a difference that would make in this case. 

In this case it's significant that the problems started after a round of splits. In [`getTruncatableIndexes`](https://github.com/cockroachdb/cockroach/blob/6c69da91b3b660f58d1026ed4bb8a707b559e854/pkg/storage/raft_log_queue.go#L103-L106), we set the target raft log size to the *smaller* of the current data size of the range and its configured maximum. After a split, the current size drops, triggering a round of more aggressive log truncations. If a replica was falling behind, this could be enough to tip it over into the snapshot death spiral. Making this logic less sensitive to splits would alleviate the problem (it was based on the unverified assumption that applying a 32MB snapshot would be less expensive than replaying 32MB of logs), although if we're so close to the tipping point that a split will send us into a death spiral then we still won't have a comfortable safety margin. 

(Also note that RaftAppliedIndex and LeaseAppliedIndex aren't counting the same things, so it's normally for RAI to be greater than LAI. As long as both values are increasing over time the range is making progress)

**Comment by petermattis** [comment]
> Making this logic less sensitive to splits would alleviate the problem (it was based on the unverified assumption that applying a 32MB snapshot would be less expensive than replaying 32MB of logs)

I'm 90% sure that applying a 32MB snapshot is an order of magnitude faster than replaying 32MB of Raft logs. I would be very surprised to find differently. It certainly is curious that this started happening at the latest round of splits, but usually the Raft log is kept well under 1 MB so I'm not seeing how the splits could have caused additional truncation, but perhaps there is a bug there.

> we can't usefully throttle raft snapshot application; we have to throttle the operations that are responsible for the log growth or the nodes that are behind will just fall further behind

Performing a lot of concurrent Raft snapshot applications on a given node could cause severe slowness. Wouldn't it be better to serialize their application?

**Comment by bdarnell** [comment]
> usually the Raft log is kept well under 1 MB so I'm not seeing how the splits could have caused additional truncation, but perhaps there is a bug there.

Yeah, we seem to have lost the logging of how big the snapshot is. But we do know that applying this snapshot is taking 20 seconds, so either it's big or it's causing some severe I/O thrashing.

> Wouldn't it be better to serialize their application?

Yes, it would probably help, but if raft snapshots are sent then that means we're falling behind. Serializing the application of the snapshots will help some ranges but push others even further behind. That would probably be better than the current situation and may even be enough to let the system recover, but it may just reorder things without fixing the real problems.

**Comment by bdarnell** [comment]
> Yeah, we seem to have lost the logging of how big the snapshot is.

Nevermind, I can't grep today. You're right; the raft log is small and it's all real data. So it doesn't look like splits are the issue. 

```
I161129 21:28:07.693849 192487992 storage/replica_raftstorage.go:621  [n4,s8,r810/8:/Table/51/1/57{76441…-85464…}] applying Raft snapshot at index 403127 (id=cfd75e78, encoded size=60339004, 58 rocksdb batches, 108 log entries)
I161129 21:28:22.386711 192487992 storage/replica_raftstorage.go:629  [n4,s8,r810/8:/Table/51/1/57{76441…-85464…}] applied Raft snapshot in 14693ms [clear=9204ms batch=2770ms entries=0ms commit=2552ms]
```

**Comment by petermattis** [comment]
I think I reproduced the excessive Raft snapshot problem locally. This was done via:

```
~ rm -fr cockroach-data/ && COCKROACH_ENABLE_LEASE_REBALANCING=true roachdemo -n 3 -- --logtostderr --vmodule=raft_log_queue=1
...
~ block_writer -tolerate-errors
```

After a period of time I saw:

```
I161130 10:37:37.338763 484004 storage/replica_raftstorage.go:631  [n1,s1,r8/1:/Table/51/1/{460607…-575464…},@c420d9f680] applying Raft snapshot at index 102599 (id=35edc661, encoded size=38448374, 37 rocksdb batches, 3 log entries)
I161130 10:37:39.387180 487559 storage/replica_raftstorage.go:631  [n1,s1,r8/1:/Table/51/1/{460607…-575464…},@c420d9f680] applying Raft snapshot at index 102947 (id=b4e01ce8, encoded size=38738903, 37 rocksdb batches, 39 log entries)
I161130 10:37:41.744668 491585 storage/replica_raftstorage.go:631  [n1,s1,r8/1:/Table/51/1/{460607…-575464…},@c420d9f680] applying Raft snapshot at index 103393 (id=0c33fe11, encoded size=39021786, 38 rocksdb batches, 17 log entries)
I161130 10:37:44.046476 495808 storage/replica_raftstorage.go:631  [n1,s1,r8/1:/Table/51/1/{460607…-575464…},@c420d9f680] applying Raft snapshot at index 103914 (id=9f12a79b, encoded size=39395385, 38 rocksdb batches, 17 log entries)
```

So 4 Raft snapshots in rapid succession for the `r8`. During this time period, I can see that `n2` is still performing Raft log truncations:

```
I161130 10:37:38.450348 25813 storage/replica_raftstorage.go:466  [n2,s2,r8/3:/Table/51/1/{460607…-575464…},@c4202f7680] generated Raft snapshot b4e01ce8 at index 102947
I161130 10:37:38.813659 110 storage/raft_log_queue.go:219  [n2,raftlog,s2,r8/3:/Table/51/1/{460607…-575464…},@c4202f7680] truncating raft log 102909-103029
I161130 10:37:39.386643 25814 storage/store.go:3161  [n2,s2,r8/3:/Table/51/1/{460607…-575464…},@c4202f7680] streamed snapshot: kv pairs: 54145, log entries: 39
I161130 10:37:39.387180 487559 storage/replica_raftstorage.go:631  [n1,s1,r8/1:/Table/51/1/{460607…-575464…},@c420d9f680] applying Raft snapshot at index 102947 (id=b4e01ce8, encoded size=38738903, 37 rocksdb batches, 39 log entries)
```

So we generated a snapshot at index 102947, then truncated the Raft log past that index and then applied the snapshot, guaranteeing that we would need to generate another snapshot. Something is clearly fouled up with the raft log truncation heuristics. I need to add a bit more debugging info to track this down.

**Comment by petermattis** [comment]
Another observation: we didn't experience any of these Raft snapshots until after Raft leadership was transferred (following the transfer of a lease). Perhaps the truncation heuristics are doing the wrong thing shortly after a leadership transfer occurs.

**Comment by petermattis** [comment]
Ah, we're messing up `Replica.mu.raftLogSize` somewhere:

```
I161130 12:24:56.464254 118 storage/raft_log_queue.go:242  [n1,raftlog,s1,r9/1:/Table/51/1/{689749…-805702…},@c422dda000] truncating raft log 49904-50025: raftLogSize=152313 targetSize=35099829 commit=50025 quorum=50025 progress=map[3:50025 1:50026 2:50025]
I161130 12:24:56.571160 84 storage/replica_proposal.go:400  [n1,s1,r9/1:/Table/51/1/{689749…-805702…},@c422dda000] range [n1,s1,r9/1:/Table/51/1/{689749…-805702…}]: transferring raft leadership to replica ID 3
I161130 12:24:56.975852 197 storage/raft_log_queue.go:242  [n2,raftlog,s2,r9/3:/Table/51/1/{689749…-805702…},@c420b53680] truncating raft log 50025-50129: raftLogSize=61890767 targetSize=35170855 commit=50129 quorum=50129 progress=map[3:50129 1:50129 2:50129]
```

Before the leadership transferred `raftLogSize` was `152313`. Afterwards it was `61890767`. Since we incrementally update this field it will likely never go back to zero. When `raftLogSize` is greater than `targetSize` we truncate to the quorum index instead of holding on to the Raft log.

**Comment by petermattis** [comment]
We only adjust `Replica.mu.raftLogSize` on the leaseholder, not followers. So after transferring a lease the new leaseholder's `raftLogSize` value will be completely whack.

**Comment by petermattis** [comment]
This problem is exacerbated by lease rebalancing which is currently off by default. I'm not sure if this is a new problem, but I don't think it should hold up the beta. 

@mberhault Can you wipe / restart delta with lease rebalancing disabled?

**Comment by mberhault** [comment]
delta is back up after wipe with lease rebalancing disabled.
