### ISSUE TITLE
Sentry: default_exprs.go:92: executing declarative schema change PostCommitPhase stage 2 of 7 with 1 BackfillType op (rollback=false) for ALTER TABLE: failed to type check the cast of × to ×: ×(): ...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#116655]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4734943464/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4734943464/?referrer=webhooks_plugin)

Panic Message:

```
default_exprs.go:92: executing declarative schema change PostCommitPhase stage 2 of 7 with 1 BackfillType op (rollback=false) for ALTER TABLE: failed to type check the cast of × to ×: ×(): cannot determine type of empty array. Consider casting to the desired type, for example ARRAY[]::int[]
(1)
  | (opaque error wrapper)
  | type name: github.com/cockroachdb/errors/withstack/*withstack.withStack
  | reportable 0:
  |
  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scerrors.EventLogger.HandlePanicAndLogError
  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scerrors/errors.go:81
  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scrun.executeStage
  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scrun/scrun.go:205
  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scrun.RunSchemaChangesInJob.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scrun/scrun.go:139
  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scdeps.(*jobExecutionDeps).WithTxnInJob.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scdeps/run_deps.go:144
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).DescsTxn.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1610
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).txn.func4
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1698
  | github.com/cockroachdb/cockroach/pkg/kv.runTxn.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:970
  | github.com/cockroachdb/cockroach/pkg/kv.(*Txn).exec
  | 	github.com/cockroachdb/cockroach/pkg/kv/txn.go:928
  | github.com/cockroachdb/cockroach/pkg/kv.runTxn
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:969
  | github.com/cockroachdb/cockroach/pkg/kv.(*DB).TxnWithAdmissionControl
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:932
  | github.com/cockroachdb/cockroach/pkg/kv.(*DB).Txn
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:907
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).txn
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1686
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).DescsTxn
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1608
  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scdeps.(*jobExecutionDeps).WithTxnInJob
  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scdeps/run_deps.go:109
  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scrun.RunSchemaChangesInJob
  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scrun/scrun.go:135
  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scjob.(*newSchemaChangeResumer).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scjob/job.go:114
  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scjob.(*newSchemaChangeResumer).Resume
  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scjob/job.go:45
  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine.func2
  | 	github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1628
  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine
  | 	github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1629
  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).runJob
  | 	github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:474
  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).resumeJob.func2
  | 	github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:388
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (2) executing declarative schema change PostCommitPhase stage 2 of 7 with 1 BackfillType op (rollback=false) for ALTER TABLE
Wraps: (3) assertion failure
Wraps: (4)
  | (opaque error wrapper)
  | type name: github.com/cockroachdb/errors/withstack/*withstack.withStack
  | reportable 0:
  |
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/schemaexpr.MakeDefaultExprs
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/schemaexpr/default_exprs.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/backfill.constructExprs
  | 	github.com/cockroachdb/cockroach/pkg/sql/backfill/backfill.go:568
  | github.com/cockroachdb/cockroach/pkg/sql/backfill.(*IndexBackfiller).InitForDistributedUse.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/backfill/backfill.go:671
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).Txn.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1620
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).txn.func4
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1698
  | github.com/cockroachdb/cockroach/pkg/kv.runTxn.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:970
  | github.com/cockroachdb/cockroach/pkg/kv.(*Txn).exec
  | 	github.com/cockroachdb/cockroach/pkg/kv/txn.go:928
  | github.com/cockroachdb/cockroach/pkg/kv.runTxn
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:969
  | github.com/cockroachdb/cockroach/pkg/kv.(*DB).TxnWithAdmissionControl
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:932
  | github.com/cockroachdb/cockroach/pkg/kv.(*DB).Txn
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:907
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).txn
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1686
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).Txn
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1621
  | github.com/cockroachdb/cockroach/pkg/sql/backfill.(*IndexBackfiller).InitForDistributedUse
  | 	github.com/cockroachdb/cockroach/pkg/sql/backfill/backfill.go:661
  | github.com/cockroachdb/cockroach/pkg/sql/rowexec.newIndexBackfiller
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowexec/indexbackfiller.go:86
  | github.com/cockroachdb/cockroach/pkg/sql/rowexec.NewProcessor
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowexec/processors.go:220
  | github.com/cockroachdb/cockroach/pkg/sql/rowflow.(*rowBasedFlow).makeProcessorAndOutput
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowflow/row_based_flow.go:241
  | github.com/cockroachdb/cockroach/pkg/sql/rowflow.(*rowBasedFlow).setupProcessors
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowflow/row_based_flow.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/rowflow.(*rowBasedFlow).Setup
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowflow/row_based_flow.go:74
  | github.com/cockroachdb/cockroach/pkg/sql/distsql.(*ServerImpl).setupFlow
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql/server.go:429
  | github.com/cockroachdb/cockroach/pkg/sql/distsql.(*ServerImpl).SetupLocalSyncFlow
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql/server.go:597
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).setupFlows
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:459
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:859
  | github.com/cockroachdb/cockroach/pkg/sql.(*IndexBackfillPlanner).plan.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/index_backfiller.go:227
  | github.com/cockroachdb/cockroach/pkg/sql.(*IndexBackfillPlanner).BackfillIndexes
  | 	github.com/cockroachdb/cockroach/pkg/sql/index_backfiller.go:138
  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scexec.runBackfill
  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scexec/exec_backfill.go:367
  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scexec.runBackfiller.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scexec/exec_backfill.go:329
  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scexec.forEachProgressConcurrently.func1.1
  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scexec/exec_backfill.go:257
  | github.com/cockroachdb/cockroach/pkg/util/ctxgroup.Group.GoCtx.func1
  | 	github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:168
  | golang.org/x/sync/errgroup.(*Group).Go.func1
  | 	golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:75
  | runtime.goexit
  | 	GOROOT/s...
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/util/stop/stopper.go#L469-L471](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/util/stop/stopper.go#L469-L471)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/jobs/adopt.go#L387-L389](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/jobs/adopt.go#L387-L389)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/jobs/adopt.go#L473-L475](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/jobs/adopt.go#L473-L475)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/jobs/registry.go#L1628-L1630](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/jobs/registry.go#L1628-L1630)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/jobs/registry.go#L1627-L1629](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/jobs/registry.go#L1627-L1629)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/schemachanger/scjob/job.go#L44-L46](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/schemachanger/scjob/job.go#L44-L46)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/schemachanger/scjob/job.go#L113-L115](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/schemachanger/scjob/job.go#L113-L115)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/schemachanger/scrun/scrun.go#L134-L136](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/schemachanger/scrun/scrun.go#L134-L136)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/schemachanger/scdeps/run_deps.go#L108-L110](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/schemachanger/scdeps/run_deps.go#L108-L110)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/internal.go#L1607-L1609](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/internal.go#L1607-L1609)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/internal.go#L1685-L1687](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/internal.go#L1685-L1687)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/db.go#L906-L908](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/db.go#L906-L908)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/db.go#L931-L933](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/db.go#L931-L933)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/db.go#L968-L970](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/db.go#L968-L970)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/txn.go#L927-L929](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/txn.go#L927-L929)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/db.go#L969-L971](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/db.go#L969-L971)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/internal.go#L1697-L1699](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/internal.go#L1697-L1699)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/internal.go#L1609-L1611](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/internal.go#L1609-L1611)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/schemachanger/scdeps/run_deps.go#L143-L145](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/schemachanger/scdeps/run_deps.go#L143-L145)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/schemachanger/scrun/scrun.go#L138-L140](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/schemachanger/scrun/scrun.go#L138-L140)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/schemachanger/scrun/scrun.go#L204-L206](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/schemachanger/scrun/scrun.go#L204-L206)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/schemachanger/scerrors/errors.go#L80-L82](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/schemachanger/scerrors/errors.go#L80-L82)
[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go#L74-L76](golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go#L74-L76)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/util/ctxgroup/ctxgroup.go#L167-L169](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/util/ctxgroup/ctxgroup.go#L167-L169)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/schemachanger/scexec/exec_backfill.go#L256-L258](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/schemachanger/scexec/exec_backfill.go#L256-L258)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/schemachanger/scexec/exec_backfill.go#L328-L330](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/schemachanger/scexec/exec_backfill.go#L328-L330)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/schemachanger/scexec/exec_backfill.go#L366-L368](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/schemachanger/scexec/exec_backfill.go#L366-L368)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/index_backfiller.go#L137-L139](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/index_backfiller.go#L137-L139)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/index_backfiller.go#L226-L228](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/index_backfiller.go#L226-L228)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/distsql_running.go#L858-L860](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/distsql_running.go#L858-L860)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/distsql_running.go#L458-L460](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/distsql_running.go#L458-L460)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/distsql/server.go#L596-L598](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/distsql/server.go#L596-L598)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/distsql/server.go#L428-L430](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/distsql/server.go#L428-L430)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/rowflow/row_based_flow.go#L73-L75](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/rowflow/row_based_flow.go#L73-L75)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/rowflow/row_based_flow.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/rowflow/row_based_flow.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/rowflow/row_based_flow.go#L240-L242](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/rowflow/row_based_flow.go#L240-L242)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/rowexec/processors.go#L219-L221](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/rowexec/processors.go#L219-L221)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/rowexec/indexbackfiller.go#L85-L87](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/rowexec/indexbackfiller.go#L85-L87)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/backfill/backfill.go#L660-L662](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/backfill/backfill.go#L660-L662)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/internal.go#L1620-L1622](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/internal.go#L1620-L1622)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/internal.go#L1685-L1687](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/internal.go#L1685-L1687)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/db.go#L906-L908](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/db.go#L906-L908)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/db.go#L931-L933](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/db.go#L931-L933)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/db.go#L968-L970](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/db.go#L968-L970)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/txn.go#L927-L929](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/txn.go#L927-L929)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/db.go#L969-L971](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/kv/db.go#L969-L971)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/internal.go#L1697-L1699](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/internal.go#L1697-L1699)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/internal.go#L1619-L1621](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/internal.go#L1619-L1621)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/backfill/backfill.go#L670-L672](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/backfill/backfill.go#L670-L672)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/backfill/backfill.go#L567-L569](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/backfill/backfill.go#L567-L569)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/catalog/schemaexpr/default_exprs.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/catalog/schemaexpr/default_exprs.go#L91-L93)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 470
pkg/jobs/adopt.go in pkg/jobs.(*Registry).resumeJob.func2 at line 388
pkg/jobs/adopt.go in pkg/jobs.(*Registry).runJob at line 474
pkg/jobs/registry.go in pkg/jobs.(*Registry).stepThroughStateMachine at line 1629
pkg/jobs/registry.go in pkg/jobs.(*Registry).stepThroughStateMachine.func2 at line 1628
pkg/sql/schemachanger/scjob/job.go in pkg/sql/schemachanger/scjob.(*newSchemaChangeResumer).Resume at line 45
pkg/sql/schemachanger/scjob/job.go in pkg/sql/schemachanger/scjob.(*newSchemaChangeResumer).run at line 114
pkg/sql/schemachanger/scrun/scrun.go in pkg/sql/schemachanger/scrun.RunSchemaChangesInJob at line 135
pkg/sql/schemachanger/scdeps/run_deps.go in pkg/sql/schemachanger/scdeps.(*jobExecutionDeps).WithTxnInJob at line 109
pkg/sql/internal.go in pkg/sql.(*InternalDB).DescsTxn at line 1608
pkg/sql/internal.go in pkg/sql.(*InternalDB).txn at line 1686
pkg/kv/db.go in pkg/kv.(*DB).Txn at line 907
pkg/kv/db.go in pkg/kv.(*DB).TxnWithAdmissionControl at line 932
pkg/kv/db.go in pkg/kv.runTxn at line 969
pkg/kv/txn.go in pkg/kv.(*Txn).exec at line 928
pkg/kv/db.go in pkg/kv.runTxn.func1 at line 970
pkg/sql/internal.go in pkg/sql.(*InternalDB).txn.func4 at line 1698
pkg/sql/internal.go in pkg/sql.(*InternalDB).DescsTxn.func1 at line 1610
pkg/sql/schemachanger/scdeps/run_deps.go in pkg/sql/schemachanger/scdeps.(*jobExecutionDeps).WithTxnInJob.func1 at line 144
pkg/sql/schemachanger/scrun/scrun.go in pkg/sql/schemachanger/scrun.RunSchemaChangesInJob.func1 at line 139
pkg/sql/schemachanger/scrun/scrun.go in pkg/sql/schemachanger/scrun.executeStage at line 205
pkg/sql/schemachanger/scerrors/errors.go in pkg/sql/schemachanger/scerrors.EventLogger.HandlePanicAndLogError at line 81
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go in golang.org/x/sync/errgroup.(*Group).Go.func1 at line 75
pkg/util/ctxgroup/ctxgroup.go in pkg/util/ctxgroup.Group.GoCtx.func1 at line 168
pkg/sql/schemachanger/scexec/exec_backfill.go in pkg/sql/schemachanger/scexec.forEachProgressConcurrently.func1.1 at line 257
pkg/sql/schemachanger/scexec/exec_backfill.go in pkg/sql/schemachanger/scexec.runBackfiller.func2 at line 329
pkg/sql/schemachanger/scexec/exec_backfill.go in pkg/sql/schemachanger/scexec.runBackfill at line 367
pkg/sql/index_backfiller.go in pkg/sql.(*IndexBackfillPlanner).BackfillIndexes at line 138
pkg/sql/index_backfiller.go in pkg/sql.(*IndexBackfillPlanner).plan.func2 at line 227
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).Run at line 859
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).setupFlows at line 459
pkg/sql/distsql/server.go in pkg/sql/distsql.(*ServerImpl).SetupLocalSyncFlow at line 597
pkg/sql/distsql/server.go in pkg/sql/distsql.(*ServerImpl).setupFlow at line 429
pkg/sql/rowflow/row_based_flow.go in pkg/sql/rowflow.(*rowBasedFlow).Setup at line 74
pkg/sql/rowflow/row_based_flow.go in pkg/sql/rowflow.(*rowBasedFlow).setupProcessors at line 92
pkg/sql/rowflow/row_based_flow.go in pkg/sql/rowflow.(*rowBasedFlow).makeProcessorAndOutput at line 241
pkg/sql/rowexec/processors.go in pkg/sql/rowexec.NewProcessor at line 220
pkg/sql/rowexec/indexbackfiller.go in pkg/sql/rowexec.newIndexBackfiller at line 86
pkg/sql/backfill/backfill.go in pkg/sql/backfill.(*IndexBackfiller).InitForDistributedUse at line 661
pkg/sql/internal.go in pkg/sql.(*InternalDB).Txn at line 1621
pkg/sql/internal.go in pkg/sql.(*InternalDB).txn at line 1686
pkg/kv/db.go in pkg/kv.(*DB).Txn at line 907
pkg/kv/db.go in pkg/kv.(*DB).TxnWithAdmissionControl at line 932
pkg/kv/db.go in pkg/kv.runTxn at line 969
pkg/kv/txn.go in pkg/kv.(*Txn).exec at line 928
pkg/kv/db.go in pkg/kv.runTxn.func1 at line 970
pkg/sql/internal.go in pkg/sql.(*InternalDB).txn.func4 at line 1698
pkg/sql/internal.go in pkg/sql.(*InternalDB).Txn.func1 at line 1620
pkg/sql/backfill/backfill.go in pkg/sql/backfill.(*IndexBackfiller).InitForDistributedUse.func1 at line 671
pkg/sql/backfill/backfill.go in pkg/sql/backfill.constructExprs at line 568
pkg/sql/catalog/schemaexpr/default_exprs.go in pkg/sql/catalog/schemaexpr.MakeDefaultExprs at line 92
```

### Tags

| Tag | Value |
| --- | --- |
| Command | start-single-node |
| Environment | v23.1.11 |
| Go Version | go1.19.10 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.11 |
| Cockroach SHA | 62ad175cbc0e9041d993ea1cc911e07d279671f5 |
| # of CPUs | 12 |
| # of Goroutines | 485 |

Jira issue: CRDB-34706

**Comment by yuzefovich** [comment]
dup of #114316
