### ISSUE TITLE
changefeedccl: v23.1.2: unable to determine result columns

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#116625]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4731565506/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4731565506/?referrer=webhooks_plugin)

Panic Message:

```
distsql_plan_changefeed.go:168: unable to determine result columns
(1)
Wraps: (2)
Wraps: (3) assertion failure
Wraps: (4) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.PlanCDCExpression
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_plan_changefeed.go:168
  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/cdceval.normalizeExpression
  | 	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/cdceval/plan.go:85
  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/cdceval.NormalizeExpression.func1
  | 	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/cdceval/plan.go:51
  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/cdceval.withPlanner.func1
  | 	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/cdceval/plan.go:187
  | github.com/cockroachdb/cockroach/pkg/sql.DescsTxn.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/exec_util.go:3670
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).DescsTxn.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1594
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).txn.func4
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1682
  | github.com/cockroachdb/cockroach/pkg/kv.runTxn.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:965
  | github.com/cockroachdb/cockroach/pkg/kv.(*Txn).exec
  | 	github.com/cockroachdb/cockroach/pkg/kv/txn.go:928
  | github.com/cockroachdb/cockroach/pkg/kv.runTxn
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:964
  | github.com/cockroachdb/cockroach/pkg/kv.(*DB).TxnWithAdmissionControl
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:927
  | github.com/cockroachdb/cockroach/pkg/kv.(*DB).Txn
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:902
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).txn
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1670
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).DescsTxn
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1592
  | github.com/cockroachdb/cockroach/pkg/sql.DescsTxn
  | 	github.com/cockroachdb/cockroach/pkg/sql/exec_util.go:3669
  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/cdceval.withPlanner
  | 	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/cdceval/plan.go:171
  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/cdceval.NormalizeExpression
  | 	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/cdceval/plan.go:47
  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.validateAndNormalizeChangefeedExpression
  | 	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_stmt.go:1034
  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.createChangefeedJobRecord
  | 	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_stmt.go:492
  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.changefeedPlanHook.func1
  | 	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_stmt.go:191
  | github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl.changefeedPlanHook.func2
  | 	github.com/cockroachdb/cockroach/pkg/ccl/changefeedccl/changefeed_stmt.go:343
  | github.com/cockroachdb/cockroach/pkg/sql.(*hookFnNode).startExec.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/planhook.go:205
  | runtime.goexit
  | 	src/runtime/asm_amd64.s:1594
Wraps: (5) unable to determine result columns
Error types: (1) *colexecerror.notInternalError (2) *changefeedbase.taggedError (3) *assert.withAssertionFailure (4) *withstack.withStack (5) *errutil.leafError
-- report composition:
*errutil.leafError: unable to determine result columns
distsql_plan_changefeed.go:168: *withstack.withStack (top exception)
*assert.withAssertionFailure
*changefeedbase.taggedError
*colexecerror.notInternalError
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_amd64.s#L1593-L1595](src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/planhook.go#L204-L206](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/planhook.go#L204-L206)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/ccl/changefeedccl/changefeed_stmt.go#L342-L344](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/ccl/changefeedccl/changefeed_stmt.go#L342-L344)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/ccl/changefeedccl/changefeed_stmt.go#L190-L192](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/ccl/changefeedccl/changefeed_stmt.go#L190-L192)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/ccl/changefeedccl/changefeed_stmt.go#L491-L493](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/ccl/changefeedccl/changefeed_stmt.go#L491-L493)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/ccl/changefeedccl/changefeed_stmt.go#L1033-L1035](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/ccl/changefeedccl/changefeed_stmt.go#L1033-L1035)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/ccl/changefeedccl/cdceval/plan.go#L46-L48](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/ccl/changefeedccl/cdceval/plan.go#L46-L48)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/ccl/changefeedccl/cdceval/plan.go#L170-L172](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/ccl/changefeedccl/cdceval/plan.go#L170-L172)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/exec_util.go#L3668-L3670](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/exec_util.go#L3668-L3670)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/internal.go#L1591-L1593](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/internal.go#L1591-L1593)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/internal.go#L1669-L1671](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/internal.go#L1669-L1671)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/db.go#L901-L903](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/db.go#L901-L903)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/db.go#L926-L928](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/db.go#L926-L928)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/db.go#L963-L965](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/db.go#L963-L965)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/txn.go#L927-L929](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/txn.go#L927-L929)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/db.go#L964-L966](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/db.go#L964-L966)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/internal.go#L1681-L1683](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/internal.go#L1681-L1683)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/internal.go#L1593-L1595](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/internal.go#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/exec_util.go#L3669-L3671](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/exec_util.go#L3669-L3671)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/ccl/changefeedccl/cdceval/plan.go#L186-L188](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/ccl/changefeedccl/cdceval/plan.go#L186-L188)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/ccl/changefeedccl/cdceval/plan.go#L50-L52](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/ccl/changefeedccl/cdceval/plan.go#L50-L52)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/ccl/changefeedccl/cdceval/plan.go#L84-L86](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/ccl/changefeedccl/cdceval/plan.go#L84-L86)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/distsql_plan_changefeed.go#L167-L169](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/sql/distsql_plan_changefeed.go#L167-L169)
</details>

```
src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/sql/planhook.go in pkg/sql.(*hookFnNode).startExec.func1 at line 205
pkg/ccl/changefeedccl/changefeed_stmt.go in pkg/ccl/changefeedccl.changefeedPlanHook.func2 at line 343
pkg/ccl/changefeedccl/changefeed_stmt.go in pkg/ccl/changefeedccl.changefeedPlanHook.func1 at line 191
pkg/ccl/changefeedccl/changefeed_stmt.go in pkg/ccl/changefeedccl.createChangefeedJobRecord at line 492
pkg/ccl/changefeedccl/changefeed_stmt.go in pkg/ccl/changefeedccl.validateAndNormalizeChangefeedExpression at line 1034
pkg/ccl/changefeedccl/cdceval/plan.go in pkg/ccl/changefeedccl/cdceval.NormalizeExpression at line 47
pkg/ccl/changefeedccl/cdceval/plan.go in pkg/ccl/changefeedccl/cdceval.withPlanner at line 171
pkg/sql/exec_util.go in pkg/sql.DescsTxn at line 3669
pkg/sql/internal.go in pkg/sql.(*InternalDB).DescsTxn at line 1592
pkg/sql/internal.go in pkg/sql.(*InternalDB).txn at line 1670
pkg/kv/db.go in pkg/kv.(*DB).Txn at line 902
pkg/kv/db.go in pkg/kv.(*DB).TxnWithAdmissionControl at line 927
pkg/kv/db.go in pkg/kv.runTxn at line 964
pkg/kv/txn.go in pkg/kv.(*Txn).exec at line 928
pkg/kv/db.go in pkg/kv.runTxn.func1 at line 965
pkg/sql/internal.go in pkg/sql.(*InternalDB).txn.func4 at line 1682
pkg/sql/internal.go in pkg/sql.(*InternalDB).DescsTxn.func1 at line 1594
pkg/sql/exec_util.go in pkg/sql.DescsTxn.func1 at line 3670
pkg/ccl/changefeedccl/cdceval/plan.go in pkg/ccl/changefeedccl/cdceval.withPlanner.func1 at line 187
pkg/ccl/changefeedccl/cdceval/plan.go in pkg/ccl/changefeedccl/cdceval.NormalizeExpression.func1 at line 51
pkg/ccl/changefeedccl/cdceval/plan.go in pkg/ccl/changefeedccl/cdceval.normalizeExpression at line 85
pkg/sql/distsql_plan_changefeed.go in pkg/sql.PlanCDCExpression at line 168
```

### Tags

| Tag | Value |
| --- | --- |
| Command | start-single-node |
| Environment | v23.1.2 |
| Go Version | go1.19.4 |
| Platform | darwin amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.2 |
| Cockroach SHA | 810d4f27a7f02b9cc2750cab654ed1c62ac3e75a |
| # of CPUs | 10 |
| # of Goroutines | 420 |

Jira issue: CRDB-34692

**Comment by jayshrivastava** [comment]
Given the OS is darwin and this was `start-single-node`, it looks like someone must have been testing a CCL binary.
