### ISSUE TITLE
sql: make `VALID UNTIL 'infinity'` work the same way as `VALID UNTIL NULL`

### ISSUE THREAD

**Issue by chrisseto** [cockroachdb/cockroach#116714]
Creating a role that's `VALID UNTIL 'infinity'` will break selects from `pg_catalog.pg_roles`.

```sql
create role chris VALID UNTIL 'infinity';                                                                                                                 
show roles;
select * from pg_catalog.pg_roles;
ERROR: timestamp "294277-01-01T00:00:00Z" exceeds supported timestamp bounds                                                                                                                              
```

This can be worked around by instead using the syntax `VALID UNTIL NULL`. However, this is not an obvious solution.

Until #41564 has been resolved, we should special case `VALID UNTIL 'infinity'` to act the same way as `VALID UNTIL NULL`.

Jira issue: CRDB-34732

**Comment by Kouddo** [comment]
Hey, I'd be interested in contributing to this! Does anyone have any guidance on where I could start

**Comment by zyf123123** [comment]
Hi,I'm new to CRDB and find something to contribute, Can I try this one?

**Comment by zyf123123** [comment]
I have already commit a PR for this issue, please review my code. Thank you!

**Comment by rafiss** [comment]
https://github.com/cockroachdb/cockroach/pull/127141has resolved this by making `infinity` a valid timestamp.
