### ISSUE TITLE
workload/schemachange: enable `COMMENT ON`

### ISSUE THREAD

**Issue by chrisseto** [cockroachdb/cockroach#116795]
As of https://github.com/cockroachdb/cockroach/pull/115360, `COMMENT ON` is support in the RSW but disabled by default due to a known bug: https://github.com/cockroachdb/cockroach/issues/72820

This is a tracking issue for enabling `COMMENT ON` after or in tandem with fixing the https://github.com/cockroachdb/cockroach/issues/72820.

Jira issue: CRDB-34779

Epic CRDB-19168

**Comment by rafiss** [comment]
re-opening due to https://github.com/cockroachdb/cockroach/pull/118963
