### ISSUE TITLE
Sentry: validate.go:158: relation × (1480): depends-on relation × (203) has no corresponding depended-on-by back reference
(1)
Wraps: (2) keys: [sql.schema.validation_errors.read.backward_references...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#116781]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4739096169/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4739096169/?referrer=webhooks_plugin)

Panic Message:

```
validate.go:158: relation × (1480): depends-on relation × (203) has no corresponding depended-on-by back reference
(1)
Wraps: (2) keys: [sql.schema.validation_errors.read.backward_references.relation sql.schema.validation_errors.read.backward_references.relation]
Wraps: (3) secondary error attachment
  | relation × (1480): depends-on relation × (1479) has no corresponding depended-on-by back reference
  | (1) keys: [sql.schema.validation_errors.read.backward_references.relation]
  | Wraps: (2) attached stack trace
  |   -- stack trace:
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate.(*validationErrorAccumulator).decorate
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate/validate.go:256
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate.(*validationErrorAccumulator).Report
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate/validate.go:186
  |   | [...repeated from below...]
  | Wraps: (3) relation × (1480)
  | Wraps: (4) assertion failure
  | Wraps: (5) attached stack trace
  |   -- stack trace:
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog.ValidateOutboundTableRefBackReference
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/validate.go:158
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/tabledesc.(*wrapper).ValidateBackReferences
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/tabledesc/validate.go:284
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate.Validate.func3
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate/validate.go:114
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate.(*validationErrorAccumulator).validateDescriptorsAtLevel
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate/validate.go:202
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate.Validate
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate/validate.go:109
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).Validate
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/validate.go:40
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).finalizeDescriptors
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:660
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.getDescriptorsByID
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:220
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).aggregateAllLayers
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:1022
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).GetAllInDatabase
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:865
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).GetAllDescriptorsForDatabase
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:1049
  |   | github.com/cockroachdb/cockroach/pkg/sql.forEachTableDescWithTableLookupInternal
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:2533
  |   | github.com/cockroachdb/cockroach/pkg/sql.forEachTableDescWithTableLookup
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:2511
  |   | github.com/cockroachdb/cockroach/pkg/sql.glob..func259.1
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/pg_catalog.go:3215
  |   | github.com/cockroachdb/cockroach/pkg/sql.forEachDatabaseDesc
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:2367
  |   | github.com/cockroachdb/cockroach/pkg/sql.glob..func259
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/pg_catalog.go:3203
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*virtualDefEntry).getPlanInfo.func1.1
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/virtual_schema.go:678
  |   | github.com/cockroachdb/cockroach/pkg/sql.setupGenerator.func3
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/virtual_table.go:127
  |   | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  |   | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470
  |   | runtime.goexit
  |   | 	GOROOT/src/runtime/asm_amd64.s:1594
  | Wraps: (6) depends-on relation × (1479) has no corresponding depended-on-by back reference
  | Error types: (1) *telemetrykeys.withTelemetry (2) *withstack.withStack (3) *errutil.withPrefix (4) *assert.withAssertionFailure (5) *withstack.withStack (6) *errutil.leafError
Wraps: (4) keys: [sql.schema.validation_errors.read.backward_references.relation]
Wraps: (5) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate.(*validationErrorAccumulator).decorate
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate/validate.go:256
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate.(*validationErrorAccumulator).Report
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate/validate.go:186
  | [...repeated from below...]
Wraps: (6) relation × (1480)
Wraps: (7) assertion failure
Wraps: (8) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/catalog.ValidateOutboundTableRefBackReference
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/validate.go:158
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/tabledesc.(*wrapper).ValidateBackReferences
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/tabledesc/validate.go:284
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate.Validate.func3
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate/validate.go:114
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate.(*validationErrorAccumulator).validateDescriptorsAtLevel
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate/validate.go:202
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate.Validate
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate/validate.go:109
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).Validate
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/validate.go:40
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).finalizeDescriptors
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:660
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.getDescriptorsByID
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:220
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).aggregateAllLayers
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:1022
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).GetAllInDatabase
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:865
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).GetAllDescriptorsForDatabase
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:1049
  | github.com/cockroachdb/cockroach/pkg/sql.forEachTableDescWithTableLookupInternal
  | 	github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:2533
  | github.com/cockroachdb/cockroach/pkg/sql.forEachTableDescWithTableLookup
  | 	github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:2511
  | github.com/cockroachdb/cockroach/pkg/sql.glob..func259.1
  | 	github.com/cockroachdb/cockroach/pkg/sql/pg_catalog.go:3215
  | github.com/cockroachdb/cockroach/pkg/sql.forEachDatabaseDesc
  | 	github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:2367
  | github.com/cockroachdb/cockroach/pkg/sql.glob..func259
  | 	github.com/cockroachdb/cockroach/pkg/sql/pg_catalog.go:3203
  | github.com/cockroachdb/cockroach/pkg/sql.(*virtualDefEntry).getPlanInfo.func1.1
  | 	github.com/cockroachdb/cockroach/pkg/sql/virtual_schema.go:678
  | github.com/cockroachdb/cockroach/pkg/sql.setupGenerator.func3
  | 	github.com/cockroachdb/cockroach/pkg/sql/virtual_table.go:127
  | ...
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/util/stop/stopper.go#L469-L471](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/util/stop/stopper.go#L469-L471)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/virtual_table.go#L126-L128](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/virtual_table.go#L126-L128)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/virtual_schema.go#L677-L679](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/virtual_schema.go#L677-L679)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/pg_catalog.go#L3202-L3204](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/pg_catalog.go#L3202-L3204)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/information_schema.go#L2366-L2368](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/information_schema.go#L2366-L2368)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/pg_catalog.go#L3214-L3216](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/pg_catalog.go#L3214-L3216)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/information_schema.go#L2510-L2512](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/information_schema.go#L2510-L2512)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/information_schema.go#L2532-L2534](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/information_schema.go#L2532-L2534)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/catalog/descs/collection.go#L1048-L1050](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/catalog/descs/collection.go#L1048-L1050)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/catalog/descs/collection.go#L864-L866](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/catalog/descs/collection.go#L864-L866)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/catalog/descs/collection.go#L1021-L1023](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/catalog/descs/collection.go#L1021-L1023)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/catalog/descs/descriptor.go#L219-L221](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/catalog/descs/descriptor.go#L219-L221)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/catalog/descs/descriptor.go#L659-L661](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/catalog/descs/descriptor.go#L659-L661)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/catalog/descs/validate.go#L39-L41](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/catalog/descs/validate.go#L39-L41)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/catalog/internal/validate/validate.go#L108-L110](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/catalog/internal/validate/validate.go#L108-L110)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/catalog/internal/validate/validate.go#L201-L203](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/catalog/internal/validate/validate.go#L201-L203)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/catalog/internal/validate/validate.go#L113-L115](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/catalog/internal/validate/validate.go#L113-L115)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/catalog/tabledesc/validate.go#L283-L285](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/catalog/tabledesc/validate.go#L283-L285)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/catalog/internal/validate/validate.go#L185-L187](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/catalog/internal/validate/validate.go#L185-L187)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/catalog/internal/validate/validate.go#L255-L257](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/catalog/internal/validate/validate.go#L255-L257)
[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/util/stop/stopper.go#L469-L471](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/util/stop/stopper.go#L469-L471)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/virtual_table.go#L126-L128](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/virtual_table.go#L126-L128)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/virtual_schema.go#L677-L679](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/virtual_schema.go#L677-L679)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/pg_catalog.go#L3202-L3204](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/pg_catalog.go#L3202-L3204)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/information_schema.go#L2366-L2368](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/information_schema.go#L2366-L2368)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/pg_catalog.go#L3214-L3216](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/pg_catalog.go#L3214-L3216)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/information_schema.go#L2510-L2512](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/information_schema.go#L2510-L2512)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/information_schema.go#L2532-L2534](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/information_schema.go#L2532-L2534)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/catalog/descs/collection.go#L1048-L1050](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/catalog/descs/collection.go#L1048-L1050)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/catalog/descs/collection.go#L864-L866](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/catalog/descs/collection.go#L864-L866)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/catalog/descs/collection.go#L1021-L1023](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/catalog/descs/collection.go#L1021-L1023)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/catalog/descs/descriptor.go#L219-L221](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/catalog/descs/descriptor.go#L219-L221)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/catalog/descs/descriptor.go#L659-L661](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/catalog/descs/descriptor.go#L659-L661)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/catalog/descs/validate.go#L39-L41](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/catalog/descs/validate.go#L39-L41)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/catalog/internal/validate/validate.go#L108-L110](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/catalog/internal/validate/validate.go#L108-L110)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/catalog/internal/validate/validate.go#L201-L203](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/catalog/internal/validate/validate.go#L201-L203)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/catalog/internal/validate/validate.go#L113-L115](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/catalog/internal/validate/validate.go#L113-L115)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/catalog/tabledesc/validate.go#L283-L285](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/catalog/tabledesc/validate.go#L283-L285)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/catalog/validate.go#L157-L159](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/catalog/validate.go#L157-L159)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 470
pkg/sql/virtual_table.go in pkg/sql.setupGenerator.func3 at line 127
pkg/sql/virtual_schema.go in pkg/sql.(*virtualDefEntry).getPlanInfo.func1.1 at line 678
pkg/sql/pg_catalog.go in pkg/sql.glob..func259 at line 3203
pkg/sql/information_schema.go in pkg/sql.forEachDatabaseDesc at line 2367
pkg/sql/pg_catalog.go in pkg/sql.glob..func259.1 at line 3215
pkg/sql/information_schema.go in pkg/sql.forEachTableDescWithTableLookup at line 2511
pkg/sql/information_schema.go in pkg/sql.forEachTableDescWithTableLookupInternal at line 2533
pkg/sql/catalog/descs/collection.go in pkg/sql/catalog/descs.(*Collection).GetAllDescriptorsForDatabase at line 1049
pkg/sql/catalog/descs/collection.go in pkg/sql/catalog/descs.(*Collection).GetAllInDatabase at line 865
pkg/sql/catalog/descs/collection.go in pkg/sql/catalog/descs.(*Collection).aggregateAllLayers at line 1022
pkg/sql/catalog/descs/descriptor.go in pkg/sql/catalog/descs.getDescriptorsByID at line 220
pkg/sql/catalog/descs/descriptor.go in pkg/sql/catalog/descs.(*Collection).finalizeDescriptors at line 660
pkg/sql/catalog/descs/validate.go in pkg/sql/catalog/descs.(*Collection).Validate at line 40
pkg/sql/catalog/internal/validate/validate.go in pkg/sql/catalog/internal/validate.Validate at line 109
pkg/sql/catalog/internal/validate/validate.go in pkg/sql/catalog/internal/validate.(*validationErrorAccumulator).validateDescriptorsAtLevel at line 202
pkg/sql/catalog/internal/validate/validate.go in pkg/sql/catalog/internal/validate.Validate.func3 at line 114
pkg/sql/catalog/tabledesc/validate.go in pkg/sql/catalog/tabledesc.(*wrapper).ValidateBackReferences at line 284
pkg/sql/catalog/internal/validate/validate.go in pkg/sql/catalog/internal/validate.(*validationErrorAccumulator).Report at line 186
pkg/sql/catalog/internal/validate/validate.go in pkg/sql/catalog/internal/validate.(*validationErrorAccumulator).decorate at line 256
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 470
pkg/sql/virtual_table.go in pkg/sql.setupGenerator.func3 at line 127
pkg/sql/virtual_schema.go in pkg/sql.(*virtualDefEntry).getPlanInfo.func1.1 at line 678
pkg/sql/pg_catalog.go in pkg/sql.glob..func259 at line 3203
pkg/sql/information_schema.go in pkg/sql.forEachDatabaseDesc at line 2367
pkg/sql/pg_catalog.go in pkg/sql.glob..func259.1 at line 3215
pkg/sql/information_schema.go in pkg/sql.forEachTableDescWithTableLookup at line 2511
pkg/sql/information_schema.go in pkg/sql.forEachTableDescWithTableLookupInternal at line 2533
pkg/sql/catalog/descs/collection.go in pkg/sql/catalog/descs.(*Collection).GetAllDescriptorsForDatabase at line 1049
pkg/sql/catalog/descs/collection.go in pkg/sql/catalog/descs.(*Collection).GetAllInDatabase at line 865
pkg/sql/catalog/descs/collection.go in pkg/sql/catalog/descs.(*Collection).aggregateAllLayers at line 1022
pkg/sql/catalog/descs/descriptor.go in pkg/sql/catalog/descs.getDescriptorsByID at line 220
pkg/sql/catalog/descs/descriptor.go in pkg/sql/catalog/descs.(*Collection).finalizeDescriptors at line 660
pkg/sql/catalog/descs/validate.go in pkg/sql/catalog/descs.(*Collection).Validate at line 40
pkg/sql/catalog/internal/validate/validate.go in pkg/sql/catalog/internal/validate.Validate at line 109
pkg/sql/catalog/internal/validate/validate.go in pkg/sql/catalog/internal/validate.(*validationErrorAccumulator).validateDescriptorsAtLevel at line 202
pkg/sql/catalog/internal/validate/validate.go in pkg/sql/catalog/internal/validate.Validate.func3 at line 114
pkg/sql/catalog/tabledesc/validate.go in pkg/sql/catalog/tabledesc.(*wrapper).ValidateBackReferences at line 284
pkg/sql/catalog/validate.go in pkg/sql/catalog.ValidateOutboundTableRefBackReference at line 158
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v23.1.12 |
| Go Version | go1.19.13 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.12 |
| Cockroach SHA | d7e9824b4cd6ebf7a8548156f2a772ae6648257d |
| # of CPUs | 4 |
| # of Goroutines | 403 |

Jira issue: CRDB-34773

**Comment by yuzefovich** [comment]
dup of #116782
