### ISSUE TITLE
ui: storage metrics don't properly render in the application tenant

### ISSUE THREAD

**Issue by ajstorm** [cockroachdb/cockroach#116732]
Some of the storage charts don't render in the application tenant, but display properly in the system tenant.

<img width="1695" alt="image" src="https://github.com/cockroachdb/cockroach/assets/18447034/64e047b9-6dfe-4d2e-8be5-9a21d5ffa1f7">

<img width="1671" alt="image" src="https://github.com/cockroachdb/cockroach/assets/18447034/328ef4a4-2e56-4dd0-bd9f-43caff7b173d">

Jira issue: CRDB-34735

**Comment by ajstorm** [comment]
Will be addressed by https://github.com/cockroachdb/cockroach/pull/114730

**Comment by stevendanna** [comment]
Will be closed by https://github.com/cockroachdb/cockroach/pull/116779

**Comment by dt** [comment]
116779
