### ISSUE TITLE
Receiving wrong values when selecting specific fields form a JSONB column

### ISSUE THREAD

**Issue by jaads** [cockroachdb/cockroach#116851]
**Describe the problem**

When selecting fields form a JSONB column, I receive the wrong values. 

**To Reproduce**

1. Set up CockroachDB cluster
2. Send SQL commands step by step described [here](https://www.cockroachlabs.com/docs/stable/jsonb#create-a-table-with-a-jsonb-column) 
3. Notice the wrong output trying to receive multiple specific fields in [this step](https://www.cockroachlabs.com/docs/stable/jsonb#retrieve-a-specific-field-from-jsonb-data) 

the result looks like this:

||?column? | ?column?|
|-- | --| --|
|1 | Brooklyn | Brooklyn|
|2 | NYC | NYC|

**Expected behavior**
I would expect the values stated in the docs, so those:

||?column? | ?column?|
|-- | --| --|
|1 | Ernie | Brooklyn|
|2 | Lola | NYC|

**Additional data / screenshots**
<img width="1017" alt="Screenshot 2023-12-20 at 11 41 33" src="https://github.com/cockroachdb/cockroach/assets/34009329/ffbac605-53d3-4ba0-9f2a-fd3e9c9ca36c">

**Environment:**
Serverless, Google Cloud. v23.1.13

Jira issue: CRDB-34813

**Comment by ajwerner** [comment]
I think this might be a bug in the web beta shell when the columns end up with the same name rather than being a database bug. Try:

```sql
select user_profile->>'location' as location, profile->>'first_name' as first_name from users;
```

**Comment by yuzefovich** [comment]
cc @lassenordahl

**Comment by lassenordahl** [comment]
Awesome thanks for the heads up @jaads!

I think we'll need to make some updates on the end of `crdb` here to handle this. Seems like the API is aggregating the columns. We might need to provide some sort of key for matching columns to differentiate it, or however the current shell works under the hood.

<img width="458" alt="Screenshot 2023-12-21 at 9 55 40 AM" src="https://github.com/cockroachdb/cockroach/assets/13127625/87ef6c05-cb86-43fa-b4f9-4c879377bd2b">

<img width="1053" alt="Screenshot 2023-12-21 at 9 50 37 AM" src="https://github.com/cockroachdb/cockroach/assets/13127625/e5439bfc-cdbc-4b22-b337-bcb854b1743a">

On the end of Console, I could remove duplicate columns and add an alert to make it clearer that the columns are duplicated. Then we wouldn't render the _wrong_ values per say and indicate we'd need an alias.
