### ISSUE TITLE
sql: `ORDER BY RANDOM()` doesn't work in union query

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#11698]
Given the table
```sql
CREATE TABLE user_edge (
  source_id INT,
  destination_id INT,
  PRIMARY KEY (source_id, destination_id)
);
INSERT INTO user_edge VALUES (1,2), (1,3), (1,4), (2,1);
```

The following query produces the same result every time:
```
SELECT * FROM (SELECT source_id, destination_id FROM users_edge EXCEPT SELECT destination_id, source_id FROM users_edge) AS t ORDER BY RANDOM();
```

It seems that the `ORDER BY` clause is being ignored.

This query behaves as I expected in postgres (the rows are shuffled).

**Comment by knz** [comment]
This is a side effect of the optimization introduced in 68502db227bd0e9f405ba253462b4e9a71b24b4f. Fixing it now.
