### ISSUE TITLE
sql: investigate possible bug with auto commit on last cascade

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#117092]
We might have a long-standing bug around this comment
https://github.com/cockroachdb/cockroach/blob/4f31fbae529e459c00ef2490e193c0c246e8d0f9/pkg/sql/distsql_running.go#L2091-L2096

In particular, it seems possible that we can specify `allowAutoCommit = true` for the last cascade in the plan when there are no checks, but if that `PlanFn` produces some checks, then we mistakenly allowed auto commit for that cascade.

Jira issue: CRDB-34975

**Comment by michae2** [comment]
[triage] @yuzefovich do you have an idea for how we would demonstrate a problem with this / repro it?

**Comment by yuzefovich** [comment]
I don't think it's an actual issue. I misread this boolean as having the final say on whether the cascade can autocommit or not whereas at this point we can only disable autocommit and later, during the execbuild, we _might_ enable that, depending on other conditions. I'll add some commentary as part of #117093.
