### ISSUE TITLE
Put test: raft id allocations 1 -> 2 -> 11 -> 12 -> 3

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#1170]
during acceptance put test with added logging. NewRange is (except for the first one) only called via range splits, and those allocate RaftIDs via id_alloc.go. I've added more logging about the actual alloc calls to make sure this isn't a side effect of some other problem.

> 09:03 $ grep NewRange tmp.log
W0528 12:03:55.105464       1 range.go:218] TOBIAS NewRange raft_id:1 start_key:"" end_key:"\377\377" replicas:<node_id:"\001" store_id:"\001" attrs:<> >
W0528 12:04:34.829378       1 range.go:218] TOBIAS NewRange raft_id:2 start_key:"00008021" end_key:"\377\377" replicas:<node_id:"\001" store_id:"\001" attrs:<> > replicas:<node_id:"\002" store_id:"\002" attrs:<attrs:"ssd" > > replicas:<node_id:"\003" store_id:"\003" attrs:<attrs:"ssd" > >
W0528 12:04:34.829508       1 range_command.go:944] TOBIAS NewRange done
W0528 12:04:59.341861       1 range.go:218] TOBIAS NewRange raft_id:11 start_key:"00016251" end_key:"\377\377" replicas:<node_id:"\001" store_id:"\001" attrs:<> > replicas:<node_id:"\002" store_id:"\002" attrs:<attrs:"ssd" > > replicas:<node_id:"\003" store_id:"\003" attrs:<attrs:"ssd" > >
W0528 12:04:59.341964       1 range_command.go:944] TOBIAS NewRange done
W0528 12:05:27.406489       1 range.go:218] TOBIAS NewRange raft_id:12 start_key:"00024313" end_key:"\377\377" replicas:<node_id:"\001" store_id:"\001" attrs:<> > replicas:<node_id:"\002" store_id:"\002" attrs:<attrs:"ssd" > > replicas:<node_id:"\003" store_id:"\003" attrs:<attrs:"ssd" > >
W0528 12:05:27.406700       1 range_command.go:944] TOBIAS NewRange done
W0528 12:05:52.595428       1 range.go:218] TOBIAS NewRange raft_id:3 start_key:"00032417" end_key:"\377\377" replicas:<node_id:"\001" store_id:"\001" attrs:<> > replicas:<node_id:"\002" store_id:"\002" attrs:<attrs:"ssd" > > replicas:<node_id:"\003" store_id:"\003" attrs:<attrs:"ssd" > >
W0528 12:05:52.595542       1 range_command.go:944] TOBIAS NewRange done

**Comment by petermattis** [comment]
Doesn't happen every time, but I just had raft-id allocations of `1 -> 2 -> 11` occur. With some added logging I can see that the only id's reserved on the `data0` node were `[2, 10]` and the only id allocated was `2`. I'm guessing that the split which generated raft-id `11` occurred on another node. In which case this order of raft-id allocations could make sense.

**Comment by tschottdorf** [comment]
Yeah, it's actually okay. Each node grabs 10 IDs, so they will jump around a bit if different nodes go for it.
