### ISSUE TITLE
sql: DROP DATABASE can hang forever in waitForOneVersion

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#11701]
I discovered this while trying to update `TestLogic` to re-use database infrastructure between subtests. Could be related to #7648, and possibly #10830.

To reproduce, add the following text to the bottom of `sql/testdata/datetime`:

```
statement ok
DROP DATABASE test
```

and execute `make test PKG=./pkg/sql TESTFLAGS=-v TESTS=TestLogic/datetime`. You'll see the test hang. The goroutine that is causing the hang has the following stack trace:
```
goroutine 173 [runnable]:
github.com/cockroachdb/cockroach/pkg/util/retry.(*Retry).Next(0xc421178718, 0xc4200171a8)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/util/retry/retry.go:128 +0x1a5
github.com/cockroachdb/cockroach/pkg/sql.LeaseStore.waitForOneVersion(0x5da2e40, 0xc4205fa500, 0x3ff0000000000000, 0x2faf080, 0x12a05f200, 0x40000000000000
00, 0x0, 0x0, 0x0, 0xc42000dac0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/lease.go:262 +0x16a
github.com/cockroachdb/cockroach/pkg/sql.(*SchemaChanger).waitToUpdateLeases(0xc420fb8400, 0xc400000037, 0x148ba2ffb149746b, 0x1)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/schema_changer.go:434 +0xf5
github.com/cockroachdb/cockroach/pkg/sql.SchemaChanger.exec(0x37, 0x1, 0x5da2e40, 0xc4205fa500, 0x3ff0000000000000, 0x2faf080, 0x12a05f200, 0x4000000000000
000, 0x0, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/schema_changer.go:234 +0x9b6
github.com/cockroachdb/cockroach/pkg/sql.(*schemaChangerCollection).execSchemaChanges(0xc4204a3b90, 0xc4200e0580, 0xc4204a3c70, 0xc4209d82d0, 0x1, 0x1)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/session.go:480 +0x2fa
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execRequest(0xc4200e0580, 0xc4204a3b00, 0xc420d0efc8, 0x12, 0x0, 0x0, 0x0, 0x0, 0xc420ff9400)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:674 +0xb91
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements(0xc4200e0580, 0xc4204a3b00, 0xc420d0efc8, 0x12, 0x0, 0x0, 0x0, 0x0, 0xc420d0ef00)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:430 +0x11f
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).executeStatements(0xc420d13c00, 0x5dbb500, 0xc420199710, 0xc420d0efc8, 0x12, 0x0, 0x0, 0x0, 0x0,0
x453a901, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:746 +0x94
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).handleSimpleQuery(0xc420d13c00, 0x5dbb500, 0xc420199710, 0xc420d13c28, 0x17, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:420 +0xb3
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve(0xc420d13c00, 0x5dbb500, 0xc420199710, 0x5400, 0xc4200ba138, 0x5dbb500, 0xc4202b8870, 0x0,0
x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:347 +0x8b6
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn(0xc4200ba000, 0x5dbb500, 0xc4202b8870, 0x5dc19a0, 0xc420478700, 0x0, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:309 +0x999
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func8.1(0x5dc2720, 0xc42088e160)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/server/server.go:504 +0x106
github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1(0xc4200de090, 0xc42016e160, 0x5dc2720, 0xc42088e160, 0xc420275760)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:136 +0x95
created by github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:138 +0x277
```

**Comment by vivekmenezes** [comment]
This problem occurs when using subqueries in SQL such as

`INSERT INTO kv (k,v) VALUES (1, cluster_logical_timestamp()-(select mints from m));`

https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/subquery.go#L326

is where we make a copy of the planner for a subquery, and subsequently, add all leases acquired by the subquery to the new planner's leases slice. This however doesn't update the original planner's leases slice, so when the original query that uses the subquery completes, its call to releaseLeases() doesn't release leases acquired by the subquery.

**Comment by knz** [comment]
Thanks vivek for finding this bug. I'm going to check the subquery code and see why that was necessary and report my results.

**Comment by knz** [comment]
There was a comment in the previous implementation that explains the situation, I'm fishing out and cooking a simple fix.

**Comment by vivekmenezes** [comment]
Thanks for cooking up a fix. I think we need to add some code to the test
framework that checks that all leases have been released. I suppose we can
execute that after every statement, or at the end of each test file.

**Comment by jordanlewis** [comment]
I could be wrong, but I believe that #11719 might take care of checking that the leases have been released because it will drop all outstanding databases. I think those drops will hang if leases haven't been released, like in this issue.

**Comment by knz** [comment]
Yes I agree nevertheless I think this particular fix deserves a dedicated test.

**Comment by vivekmenezes** [comment]
I think it's okay to drop all outstanding databases with a comment that it also tests that the leases have been released. So patching the fix to jordan's change is acceptable IMHO. I think once you've dropped the databases, you can check that the leases table is empty as another check.
