### ISSUE TITLE
roachtest: using custom AdminUIPort breaks automated prometheus scraping

### ISSUE THREAD

**Issue by srosenberg** [cockroachdb/cockroach#117125]
Per [1], in order to support multiple tenants on the same host, a unique, custom SQLPort is assigned (instead of `DefaultSQLPort`), similarly for `DefaultAdminUIPort`. The latter breaks current integration with Prometheus' service discovery which is configured to scrape on `DefaultAdminUIPort` (26258). Per [2], some tests revert to it via an explicit call to `SetDefaultAdminUIPort`. Otherwise, a custom AdminUIPort is used, in which case the metrics no longer show up in Grafana. Thus, a number of roachtest failures are now without metrics; e.g., grafana link in [3] yields no data.

[1] https://github.com/cockroachdb/cockroach/issues/111052
[2] https://github.com/cockroachdb/cockroach/pull/114097
[3] https://github.com/cockroachdb/cockroach/issues/116992

Jira issue: CRDB-34993

**Comment by nameisbhaskar** [comment]
Solution doc: https://cockroachlabs.atlassian.net/wiki/spaces/~7120207825326fb5e546c194029506f2c5335e/pages/3458531376/Dynamic+Scrape+Configs+on+Prometheus+for+Roachprod
