### ISSUE TITLE
Sentry: panic.go:884: runtime error: slice bounds out of range [-1659895273:]
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | runtime.goPanicSli...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#117257]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4796689406/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4796689406/?referrer=webhooks_plugin)

Panic Message:

```
panic.go:884: runtime error: slice bounds out of range [-1659895273:]
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | runtime.goPanicSliceB
  | 	GOROOT/src/runtime/panic.go:153
  | github.com/cockroachdb/pebble/sstable.(*blockIter).SeekGE
  | 	github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/block.go:666
  | github.com/cockroachdb/pebble/sstable.(*singleLevelIterator).seekGEHelper
  | 	github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader.go:860
  | github.com/cockroachdb/pebble/sstable.(*singleLevelIterator).SeekGE
  | 	github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader.go:753
  | github.com/cockroachdb/pebble.(*levelIter).SeekGE
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/level_iter.go:735
  | github.com/cockroachdb/pebble.(*mergingIter).seekGE
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go:1046
  | github.com/cockroachdb/pebble.(*mergingIter).SeekGE
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go:1108
  | github.com/cockroachdb/pebble.(*Iterator).SeekGEWithLimit
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/iterator.go:1257
  | github.com/cockroachdb/pebble.(*Iterator).SeekGE
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/iterator.go:1141
  | github.com/cockroachdb/cockroach/pkg/storage.(*pebbleIterator).SeekGE
  | 	github.com/cockroachdb/cockroach/pkg/storage/pebble_iterator.go:335
  | github.com/cockroachdb/cockroach/pkg/ts.(*DB).findTimeSeries
  | 	github.com/cockroachdb/cockroach/pkg/ts/pruning.go:70
  | github.com/cockroachdb/cockroach/pkg/ts.(*DB).MaintainTimeSeries
  | 	github.com/cockroachdb/cockroach/pkg/ts/maintenance.go:57
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*timeSeriesMaintenanceQueue).process
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/ts_maintenance_queue.go:154
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*baseQueue).processReplica.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/queue.go:1012
  | github.com/cockroachdb/cockroach/pkg/util/contextutil.RunWithTimeout
  | 	github.com/cockroachdb/cockroach/pkg/util/contextutil/context.go:91
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*baseQueue).processReplica
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/queue.go:971
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*baseQueue).processLoop.func2.1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/queue.go:882
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470
  | runtime.goexit
  | 	src/runtime/asm_arm64.s:1172
Wraps: (2) runtime error: slice bounds out of range [-1659895273:]
Error types: (1) *withstack.withStack (2) runtime.boundsError
-- report composition:
runtime.boundsError
panic.go:884: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_arm64.s#L1171-L1173](src/runtime/asm_arm64.s#L1171-L1173)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/util/stop/stopper.go#L469-L471](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/util/stop/stopper.go#L469-L471)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/kv/kvserver/pkg/kv/kvserver/queue.go#L881-L883](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/kv/kvserver/pkg/kv/kvserver/queue.go#L881-L883)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/kv/kvserver/pkg/kv/kvserver/queue.go#L970-L972](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/kv/kvserver/pkg/kv/kvserver/queue.go#L970-L972)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/util/contextutil/context.go#L90-L92](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/util/contextutil/context.go#L90-L92)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/kv/kvserver/pkg/kv/kvserver/queue.go#L1011-L1013](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/kv/kvserver/pkg/kv/kvserver/queue.go#L1011-L1013)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/kv/kvserver/pkg/kv/kvserver/ts_maintenance_queue.go#L153-L155](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/kv/kvserver/pkg/kv/kvserver/ts_maintenance_queue.go#L153-L155)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/ts/maintenance.go#L56-L58](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/ts/maintenance.go#L56-L58)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/ts/pruning.go#L69-L71](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/ts/pruning.go#L69-L71)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/storage/pebble_iterator.go#L334-L336](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/storage/pebble_iterator.go#L334-L336)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/iterator.go#L1140-L1142](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/iterator.go#L1140-L1142)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/iterator.go#L1256-L1258](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/iterator.go#L1256-L1258)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go#L1107-L1109](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go#L1107-L1109)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go#L1045-L1047](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go#L1045-L1047)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/level_iter.go#L734-L736](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/level_iter.go#L734-L736)
[github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader.go#L752-L754](github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader.go#L752-L754)
[github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader.go#L859-L861](github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader.go#L859-L861)
[github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/block.go#L665-L667](github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/block.go#L665-L667)
[GOROOT/src/runtime/panic.go#L152-L154](GOROOT/src/runtime/panic.go#L152-L154)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
</details>

```
src/runtime/asm_arm64.s in runtime.goexit at line 1172
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 470
pkg/kv/kvserver/pkg/kv/kvserver/queue.go in pkg/kv/kvserver.(*baseQueue).processLoop.func2.1 at line 882
pkg/kv/kvserver/pkg/kv/kvserver/queue.go in pkg/kv/kvserver.(*baseQueue).processReplica at line 971
pkg/util/contextutil/context.go in pkg/util/contextutil.RunWithTimeout at line 91
pkg/kv/kvserver/pkg/kv/kvserver/queue.go in pkg/kv/kvserver.(*baseQueue).processReplica.func1 at line 1012
pkg/kv/kvserver/pkg/kv/kvserver/ts_maintenance_queue.go in pkg/kv/kvserver.(*timeSeriesMaintenanceQueue).process at line 154
pkg/ts/maintenance.go in pkg/ts.(*DB).MaintainTimeSeries at line 57
pkg/ts/pruning.go in pkg/ts.(*DB).findTimeSeries at line 70
pkg/storage/pebble_iterator.go in pkg/storage.(*pebbleIterator).SeekGE at line 335
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/iterator.go in github.com/cockroachdb/pebble.(*Iterator).SeekGE at line 1141
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/iterator.go in github.com/cockroachdb/pebble.(*Iterator).SeekGEWithLimit at line 1257
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go in github.com/cockroachdb/pebble.(*mergingIter).SeekGE at line 1108
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go in github.com/cockroachdb/pebble.(*mergingIter).seekGE at line 1046
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/level_iter.go in github.com/cockroachdb/pebble.(*levelIter).SeekGE at line 735
github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader.go in github.com/cockroachdb/pebble/sstable.(*singleLevelIterator).SeekGE at line 753
github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader.go in github.com/cockroachdb/pebble/sstable.(*singleLevelIterator).seekGEHelper at line 860
github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/block.go in github.com/cockroachdb/pebble/sstable.(*blockIter).SeekGE at line 666
GOROOT/src/runtime/panic.go in runtime.goPanicSliceB at line 153
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
```

### Tags

| Tag | Value |
| --- | --- |
| Command | start-single-node |
| Environment | v23.1.13 |
| Go Version | go1.19.13 |
| Platform | linux arm64 |
| Distribution | CCL |
| Cockroach Release | v23.1.13 |
| Cockroach SHA | 8d065df26e25a762a1abbbf2b1e475456b341a00 |
| # of CPUs | 5 |
| # of Goroutines | 351 |

Jira issue: CRDB-35088

**Comment by yuzefovich** [comment]
unactionable
