### ISSUE TITLE
storage: crash in single-node setup: "failed liveness heartbeat"

### ISSUE THREAD

**Issue by benmargolin** [cockroachdb/cockroach#11726]
1. Please supply the header (i.e. the first few lines) of your most recent
   log file **for each node in your cluster**. 

I'm running a single node. Note that I've since upped the file descriptor limit as well. I have run `echo 'num_replicas: 1' | cockroach zone set .default -f -` on this node; here's the output of `cockroach zone get .default`:

> .default
> range_min_bytes: 1048576
> range_max_bytes: 67108864
> gc:
>   ttlseconds: 86400
> num_replicas: 1
> constraints: []

Logs:

**INFO log (start):**

> I161130 19:15:07.258202 1 util/log/clog.go:988  [config] file created at: 2016/11/30 19:15:07
> I161130 19:15:07.258202 1 util/log/clog.go:988  [config] running on machine: sonicfe
> I161130 19:15:07.258202 1 util/log/clog.go:988  [config] binary: CockroachDB beta-20161103 (linux amd64, built 2016/11/03 15:03:54, go1.7.3)
> I161130 19:15:07.258202 1 util/log/clog.go:988  [config] arguments: [cockroach start --store=/home/sonic/cockroach-data/ --http-port 8280]
> I161130 19:15:07.258202 1 util/log/clog.go:988  line format: [IWEF]yymmdd hh:mm:ss.uuuuuu goid file:line msg
> I161130 19:15:07.258201 1 cli/start.go:299  CockroachDB beta-20161103 (linux amd64, built 2016/11/03 15:03:54, go1.7.3)
> I161130 19:15:07.360102 1 cli/backtrace.go:40  backtrace disabled: stat /opt/backtrace/bin/ptrace: no such file or directory
> I161130 19:15:07.360163 1 cli/start.go:315  starting cockroach node
> W161130 19:15:07.360517 1 server/server.go:154  [n?] running in insecure mode, this is strongly discouraged. See --insecure.
> I161130 19:15:07.360837 1 gossip/gossip.go:237  [n?] initial resolvers: []
> W161130 19:15:07.360852 1 gossip/gossip.go:1055  [n?] no resolvers found; use --join to specify a connected node
> W161130 19:15:07.365081 1 server/config.go:309  soft open file descriptor limit 4096 is under the recommended limit 15000; this may decrease performance
> please see https://www.cockroachlabs.com/docs/recommended-production-settings.html for more details
> I161130 19:15:07.365126 1 storage/engine/rocksdb.go:326  opening rocksdb instance at "/home/sonic/cockroach-data/"
> I161130 19:15:07.388154 1 server/config.go:443  1 storage engine initialized
> I161130 19:15:07.390772 1 base/node_id.go:62  [n1] NodeID set to 1
> I161130 19:15:07.425588 1 storage/store.go:1173  [n1] [n1,s1]: failed initial metrics computation: [n1,s1]: system config not yet available
> I161130 19:15:07.425623 1 server/node.go:433  [n1] initialized store [n1,s1]: {Capacity:10432602112 Available:4361822208 RangeCount:0}
> I161130 19:15:07.425677 1 server/node.go:318  [n1] node ID 1 initialized
> I161130 19:15:07.425798 1 gossip/gossip.go:280  [n1] NodeDescriptor set to node_id:1 address:<network_field:"tcp" address_field:"localhost:26257" > attrs:<> locality:<> 
> I161130 19:15:07.425919 1 storage/stores.go:296  [n1] read 0 node addresses from persistent storage
> I161130 19:15:07.426106 1 server/node.go:563  [n1] connecting to gossip network to verify cluster ID...
> I161130 19:15:07.426131 1 server/node.go:584  [n1] node connected via gossip and verified as part of cluster {"9887cce0-ddb5-403e-8ea6-8b22d3e643f0"}
> I161130 19:15:07.426158 1 server/node.go:368  [n1] node=1: started with [[]=/home/sonic/cockroach-data/] engine(s) and attributes []
> I161130 19:15:07.426213 1 server/server.go:605  [n1] starting http server at localhost:8280
> I161130 19:15:07.426224 1 server/server.go:606  [n1] starting grpc/postgres server at localhost:26257
> I161130 19:15:07.426235 1 server/server.go:607  [n1] advertising CockroachDB node at localhost:26257
> I161130 19:15:07.426249 1 server/server.go:627  [n1] sleeping for 188.319137ms to guarantee HLC monotonicity
> I161130 19:15:07.494383 58 sql/event_log.go:95  [n1] Event: "node_restart", target: 1, info: {Descriptor:{NodeID:1 Address:{NetworkField:tcp AddressField:localhost:26257} Attrs: Locality:} ClusterID:{UUID:9887cce0-ddb5-403e-8ea6-8b22d3e643f0} StartedAt:1480533307426135258}
> I161130 19:15:17.427621 56 storage/store.go:3732  [n1,s1] sstables (read amplification = 3):
> 4 [ 113K  1 ]: 113K
> 5 [  17M  1 ]: 17M
> 6 [ 391M 10 ]: 128M 127M 115M 17M 616K 548K 513K 469K 234K 214K

**INFO log (end):**

> I161130 19:34:57.428137 60 server/status/runtime.go:228  runtime stats: 1.1 GiB RSS, 59 goroutines, 399 MiB/382 MiB/818 MiB GO alloc/idle/total, 306 MiB/346 MiB CGO alloc/total, 1279.60cgo/sec, 0.04/0.00 %(u/s)time, 0.00 %gc (2x)
> I161130 19:35:07.426616 57 gossip/gossip.go:425  [n1] gossip status (ok, 1 node)
> gossip client (0/3 cur/max conns)
> gossip server (0/3 cur/max conns, infos 0/0 sent/received, bytes 0B/0B sent/received)
> I161130 19:35:07.428075 60 server/status/runtime.go:228  runtime stats: 1.1 GiB RSS, 60 goroutines, 630 MiB/154 MiB/818 MiB GO alloc/idle/total, 307 MiB/346 MiB CGO alloc/total, 777.00cgo/sec, 0.03/0.00 %(u/s)time, 0.00 %gc (0x)
> W161130 19:35:07.432663 52 storage/store.go:1231  [n1,s1] error gossiping system config: range 21: replica {1 1 1} not lease holder; <nil> is
> I161130 19:35:10.225365 14562 util/stop/stopper.go:396  stop has been called, stopping or quiescing all running tasks
> I161130 19:35:10.225401 189 http2_server.go:276  transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:26257->127.0.0.1:58613: use of closed network connection
> I161130 19:35:10.225552 91 http2_client.go:1053  transport: http2Client.notifyError got notified that the client transport was broken EOF.
> I161130 19:35:10.226255 86 /go/src/google.golang.org/grpc/clientconn.go:667  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp [::1]:26257: getsockopt: connection refused"; Reconnecting to {"localhost:26257" <nil>}
> I161130 19:35:10.226345 14505 http2_server.go:276  transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:26257->127.0.0.1:58743: use of closed network connection
> E161130 19:35:10.226656 59 storage/node_liveness.go:141  [n1,hb] failed liveness heartbeat: failed to send RPC: sending to all 1 replicas failed; last error: range 1: replica {1 1 1} not lease holder; <nil> is
> W161130 19:35:10.227638 61 ts/db.go:113  [n1,ts-poll] error writing time series data: failed to send RPC: sending to all 1 replicas failed; last error: range 112: replica {1 1 1} not lease holder; <nil> is
> I161130 19:35:10.227702 14562 util/stop/stopper.go:468  quiescing; tasks left:
> 51     kv/dist_sender.go:815
> 1      ts/db.go:115
> I161130 19:35:10.227793 86 /go/src/google.golang.org/grpc/clientconn.go:767  grpc: addrConn.transportMonitor exits due to: context canceled
> I161130 19:35:10.227848 14562 util/stop/stopper.go:468  quiescing; tasks left:
> 41     kv/dist_sender.go:815
> 1      ts/db.go:115
> I161130 19:35:10.227927 14562 util/stop/stopper.go:468  quiescing; tasks left:
> 17     kv/dist_sender.go:815
> 1      ts/db.go:115
> I161130 19:35:10.228124 1 cli/start.go:394  initiating graceful shutdown of server
> I161130 19:35:10.228795 14562 storage/engine/rocksdb.go:389  closing rocksdb instance at "/home/sonic/cockroach-data/"
> I161130 19:35:10.265323 1 cli/start.go:431  server drained and shutdown completed

**WARNING log:**

> margolin@sonicfe:/home/sonic/cockroach-data/logs/old$ cat cockroach.sonicfe.margolin.log.WARNING.2016-11-30T19_15_07Z.23258
> W161130 19:15:07.360518 1 util/log/clog.go:988  [config] file created at: 2016/11/30 19:15:07
> W161130 19:15:07.360518 1 util/log/clog.go:988  [config] running on machine: sonicfe
> W161130 19:15:07.360518 1 util/log/clog.go:988  [config] binary: CockroachDB beta-20161103 (linux amd64, built 2016/11/03 15:03:54, go1.7.3)
> W161130 19:15:07.360518 1 util/log/clog.go:988  [config] arguments: [cockroach start --store=/home/sonic/cockroach-data/ --http-port 8280]
> W161130 19:15:07.360518 1 util/log/clog.go:988  line format: [IWEF]yymmdd hh:mm:ss.uuuuuu goid file:line msg
> W161130 19:15:07.360517 1 server/server.go:154  [n?] running in insecure mode, this is strongly discouraged. See --insecure.
> W161130 19:15:07.360852 1 gossip/gossip.go:1055  [n?] no resolvers found; use --join to specify a connected node
> W161130 19:15:07.365081 1 server/config.go:309  soft open file descriptor limit 4096 is under the recommended limit 15000; this may decrease performance
> please see https://www.cockroachlabs.com/docs/recommended-production-settings.html for more details
> W161130 19:35:07.432663 52 storage/store.go:1231  [n1,s1] error gossiping system config: range 21: replica {1 1 1} not lease holder; <nil> is
> E161130 19:35:10.226656 59 storage/node_liveness.go:141  [n1,hb] failed liveness heartbeat: failed to send RPC: sending to all 1 replicas failed; last error: range 1: replica {1 1 1} not lease holder; <nil> is
> W161130 19:35:10.227638 61 ts/db.go:113  [n1,ts-poll] error writing time series data: failed to send RPC: sending to all 1 replicas failed; last error: range 112: replica {1 1 1} not lease holder; <nil> is

2. Please describe the issue you observed:

Server quit unexpectedly.

- What did you do?

Unsure what triggered it, server gets queries from a webapp. Manually restarting cockroach seemed to work.

**Comment by a-robinson** [comment]
Thanks for the bug report, @benmargolin! The logs make it look like this wasn't the first time that the node had been started up. Can you outline the steps you took before starting it up this time?

@cockroachdb/stability any idea why the only node in a single node cluster wouldn't be the lease holder?

**Comment by petermattis** [comment]
> I161130 19:35:10.225365 14562 util/stop/stopper.go:396 stop has been called, stopping or quiescing all running tasks

@benmargolin This line makes me suspect that you hit `ctrl-C` in the terminal running `cockroach` or you ran `cockroach quit`.

**Comment by benmargolin** [comment]
Yes I'm certain I had done 'cockroach quit' in the past, and that might be a result of the log messages there (and not it being immediately before a crash). Now I've set the TZ on my server properly so I don't have to confuse myself translating from UTC, which may have been an issue. After this kind of crash previously, I **don't** remember seeing anything in the logs of interest, so yes that might be a bit of a red herring.

I always start it with a script that just basically does "cockroach start --store=/home/sonic/cockroach-data/ --http-port 8280". I generally only run the script after it's crashed, though; I don't _typically_ quit it.

**Comment by petermattis** [comment]
> I161130 19:35:10.228124 1 cli/start.go:394 initiating graceful shutdown of server
> ...
> I161130 19:35:10.265323 1 cli/start.go:431 server drained and shutdown completed

I think you must have accidentally invoked `cockroach quit`. The above lines (at the end of your INFO log) indicates that a graceful shutdown was requested and performed.

**Comment by bdarnell** [comment]
> any idea why the only node in a single node cluster wouldn't be the lease holder?

If the clock moves backwards, then the lease can't be reacquired until the old node has expired. So if in the process of changing the time zone you set the clock back 8 hours, the cluster is dead for 8 hours until we've caught back up with the former time. Changing the time zone isn't *supposed* to change the clock, but things can be [complicated](https://help.ubuntu.com/community/UbuntuTime#Multiple_Boot_Systems_Time_Conflicts). 

If you're starting the process manually in a terminal, closing the terminal or losing an ssh connection could also terminate the process (which I think would result in the "graceful shutdown" messages seen here). You may need to run `cockroach` under a process manager (systemd/upstart/supervisord/etc, or just init.d scripts) or, for a quick hack, in `tmux` or `screen`.

**Comment by dianasaur323** [comment]
I'm going to close this issue for now as it's pretty old and it doesn't seem to require any actionable fixes. Feel free to re-open if you disagree.
