### ISSUE TITLE
sql: support `SECURITY DEFINER` in UDFs and stored procedures

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#117290]
For stored procedures and UDFs, we currently only support the default privilege setting of `SECURITY INVOKER`, which executes the routines with the privileges of the user invoking them. We should add support for `SECURITY DEFINER`. From the [Postgres docs](https://www.postgresql.org/docs/current/sql-createfunction.html):

> `SECURITY DEFINER` specifies that the function is to be executed with the privileges of the user that owns it.

Jira issue: CRDB-35108

gz#19883

**Comment by amruss** [comment]
This is preventing a customer from being able to use stored procs. @DingDLu is this something yall could pick up for 24.2?

**Comment by mgartner** [comment]
Closing in favor of #121514.
