### ISSUE TITLE
gossip: move traffic to a different connection class

### ISSUE THREAD

**Issue by andrewbaptist** [cockroachdb/cockroach#117395]
**Is your feature request related to a problem? Please describe.**
In large clusters, the gossip traffic can make up a significant portion of the total network traffic. See #117393 for more details. While this needs to be addressed, short term it makes sense to send gossip on a different network connectinon class than the `System` class.  This will prevent the `System` class from being overwhelmed.

**Describe the solution you'd like**
The Gossip client currently uses `GRPCUnvalidatedDial` to [connect to the server ](https://github.com/cockroachdb/cockroach/blob/d1c1727e0fc5c3b8d3d97a48fbaabf3bf1f3a9fc/pkg/gossip/client.go#L103). 

It woudl be best to seperate this to either the `Default` class or a new `Gossip` class which is not shared with other traffic.

**Describe alternatives you've considered**
As mentioned above the gossip traffic overhead on the cluster should be reduced, but this is a longer term project.

**Additional context**
We haven't seen this cause problems in practice, but addressing this can make the `System` connection more stable.

Jira issue: CRDB-35150

**Comment by erikgrinaker** [comment]
> either the Default class

Gossip traffic is somewhat latency-sensitive, right? The default class can see latencies of several seconds under load (which is why we have a 6 second RPC heartbeat timeout). We should probably opt for a separate class to reduce the latency on gossip traffic.

**Comment by erikgrinaker** [comment]
In fact, it almost certain is latency-sensitive, because we use it to determine node liveness. So we should not use the default class for it.

**Comment by erikgrinaker** [comment]
>In large clusters, the gossip traffic can make up a significant portion of the total network traffic. See https://github.com/cockroachdb/cockroach/issues/117393 for more details.

>200 sending nodes * 10 disks/node * 200 receiving nodes * 6 hops * 1KB * 1/10 sec = 240MB/s 
>in total of gossip traffic on the cluster.

That only works out to about 6 KB/s per RPC connection though:

10 disks/node * 6 hops * 1 KB * 1/10 sec = 6 KB/s

The problem isn't really the per-connection volume, it's the aggregate volume because of the n^2 scaling. 6 KB/s doesn't seem worth a separate connection class.

Does that sound about right?

**Comment by andrewbaptist** [comment]
I think you are missing a factor of 200 in your calculation. Every node is receiving every other stores StoreDescriptor at least once every 10 seconds (and I think because of the extra hops they will sometimes see it multiple times, but I'm not 100% sure). So at a minimum they will see:

2000 stores * 1 KB * 1/10 sec = 200 KB/s but I think it is considerably higher than this in practice. I'm going to see if I can get access to a live customer cluster with this type of setup to look at the gossip traffic rate.

**Comment by erikgrinaker** [comment]
Yeah, let's get some numbers on the volume here. 200 KB/s is miniscule in terms of system class impact.

**Comment by erikgrinaker** [comment]
No compelling evidence that there's enough gossip traffic to justify a separate connection class. Let's reopen if we can demonstrate otherwise.
