### ISSUE TITLE
observability: pretty print system.span_configurations.txt and system.descriptor.txt in debug.zip

### ISSUE THREAD

**Issue by shralex** [cockroachdb/cockroach#117428]
It is possible to use "cockroach debug decode-key" but it would be much better if the files were readable instead of hex, especially for debugging in escalations. 

Jira issue: CRDB-35172
Epic: CRDB-32134

**Comment by shralex** [comment]
Same issue with job ids in various files like protected_timestamp records file etc.

**Comment by kevin-v-ngo** [comment]
Do we know of any performance implications or issues with `cockroach debug decode-key`?

**Comment by koorosh** [comment]
Should it be readable by default or optionally with provided flag (ie. `cockroach debug zip --decode-descriptor-key`)?
