### ISSUE TITLE
storage: enable EFOS, excise on snapshot, ingest splitting performance regressions

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#117494]
See https://cockroachlabs.slack.com/archives/C05SHB3GAGP/p1704727315971649?thread_ts=1704720001.230629&cid=C05SHB3GAGP

And https://docs.google.com/spreadsheets/d/1G6JyuumetcpfRB2thIkXtTgYZCVeXShYPdbncwoLRM8/edit#gid=6

**I've tracked all the regressions below to #117116.**

### `BenchmarkQueryCache`

<img width="351" alt="image" src="https://github.com/cockroachdb/cockroach/assets/1128750/cc690d57-cc83-4d14-a177-47a7afe47020">

### `BenchmarkFKInsert`

<img width="354" alt="image" src="https://github.com/cockroachdb/cockroach/assets/1128750/4a173f20-06e1-44c5-a47d-73701ff262dd">

### `BenchmarkResolveFunction`

<img width="352" alt="image" src="https://github.com/cockroachdb/cockroach/assets/1128750/8a771387-c18a-4c75-8dd0-7745cd68e65c">

### `BenchmarkSequenceIncrement`

<img width="363" alt="image" src="https://github.com/cockroachdb/cockroach/assets/1128750/c971c6ce-d1e6-47ee-a00a-6e7e13920446">

Jira issue: CRDB-35215

**Comment by mgartner** [comment]
Let's first determine if these regressions are present on the release-23.2 and RC branches, or master only.

**Comment by mgartner** [comment]
cc @cockroachdb/storage for awareness of the large `BenchmarkSequenceIncrement` regression due to https://github.com/cockroachdb/cockroach/commit/945b21bf862d3f240cd0308f6740895af5988c6a.

**Comment by mgartner** [comment]
I've removed the `release-blocker` label because the settings that caused these regressions are disabled by default on 23.2.

**Comment by jbowens** [comment]
@mgartner Are you cool with queries taking this back as a task to update relevant benchmarks to not [time TestCluster shutdown](https://github.com/cockroachdb/cockroach/pull/117116#issuecomment-1881802423)?
