### ISSUE TITLE
sql: logic tests have gotten slower

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#11746]
The Logic test has gotten slower recently. It used to be around 20s, now (as of `296322e`) it's around 40-50s. #11719 is going to improve the test by reusing the infrastructure for each subtest, but I think we should investigate the slowdown either way.

I suspect there are multiple changes that made this slower over time.  I tried to git bisect and found one, details below. I'll try to bisect and find more.

https://github.com/cockroachdb/cockroach/commit/131cf68bb47fa583d54182960c2bbc4289ee8dfb

With this commit, TestLogic consistently takes 34s. With the preceding commit (`c72565a`), it takes 27s.  

Here are times for each subtest side-by-side: https://gist.github.com/RaduBerinde/5298dc8958097872b8493d3c67662046

@asubiotto can you investigate?

**Comment by asubiotto** [comment]
cc @jordanlewis 

The culprit is password hashing when creating `TestUser` since it happens on every logic test setup. The best thing to do is to just create `TestUser` once in #11719 when we spin up the server rather than on every logic test.

**Comment by jordanlewis** [comment]
Makes sense - I'll make sure to add this to my PR. Note that it's actually still blocked on #10830.

**Comment by RaduBerinde** [comment]
Thanks @asubiotto. I will see if I can find other commits that account for the rest of the increase.

**Comment by RaduBerinde** [comment]
I found another commit that increased from 36s to 40s:

https://github.com/cockroachdb/cockroach/commit/32a00c6b2af53be368bb17dd594fb347f1b74746

Here's the detailed subtest side-by-side with the previous commit:
https://gist.github.com/RaduBerinde/c7c93769ed7a58b861d2502769bffe3d

@knz: is it possible to make the new test faster?

**Comment by knz** [comment]
On 02-12-16 02:18, RaduBerinde wrote:
> @knz <https://github.com/knz>: is it possible to make the new test faster?

yes (just adjust the delays in there) but the faster we make it the more
likely it is to become flaky. I'm not sure what is the proper trade-off.
What does your experience tell you?

**Comment by RaduBerinde** [comment]
I don't understand the test fully. In general adding tests that sleep for seconds very quickly adds up so we should avoid it if possible (e.g. maybe a dedicated test with a manual clock rather than a logic test?). If not, I would just find the smallest interval that passes `make stress` and then increase that value by a factor.

**Comment by bdarnell** [comment]
Why are we setting a password on TestUser in the logic tests in the first place? Those tests don't log in with a password.

We could also export the BcryptCost setting and reduce it in tests, which would speed up the (non-logic) tests that *do* use passwords.

**Comment by RaduBerinde** [comment]
Good point - are we hashing an empty password here? If we really need to do that, we can just precalculate the hash of the empty password.

**Comment by RaduBerinde** [comment]
@asubiotto adding the lines below makes the sql tests ~7 seconds faster and they still pass. Is doing this correct? (if yes I'll open a PR)

```go
func HashPassword(password string) ([]byte, error) {
+	if password == "" {
+		return []byte{}, nil
+	}
```

**Comment by asubiotto** [comment]
Yes, we're hashing an empty password and it is unnecessary since users that have empty passwords use cert authentication. The change above works. Thanks for this!
