### ISSUE TITLE
sql: improve query performance in v24.1

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#117546]
This issue will serve as a placeholder for performance improvements we plan to make during the 24.1 release cycle. A large focus will be on reducing planning time--especially for queries with many joins-- but there may be improvements we can make to execution as well. One idea for reducing planning time is described in #117284.

Jira issue: CRDB-35243

Epic CRDB-35941

**Comment by mgartner** [comment]
Existing PRs that contribute to this work include: #117558, #117456, #117649, #118553, #118604, #118556, #118683, #118684, #118788, #118910, #118923, #119094, and #119095.

The major outstanding work is implementing [generic query plans](https://github.com/cockroachdb/cockroach/pull/117284).
