### ISSUE TITLE
Implement ALTER DATABASE ... CONFIGURE ZONE USING ... in declarative schema changer

### ISSUE THREAD

**Issue by Xiang-Gu** [cockroachdb/cockroach#117574]
This issue tracks our progress of supporting zone configs in declarative schema changer and let's concretize it into implementing `ALTER DATABASE ... CONFIGURE ZONE` stmt in declarative schema changer.

Epic: CRDB-31473

Jira issue: CRDB-35252

**Comment by annrpom** [comment]
Closing as fixed by https://github.com/cockroachdb/cockroach/pull/121026
