### ISSUE TITLE
sql: add randomized testing for gist decoding

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#117634]
**Is your feature request related to a problem? Please describe.**
We have found that there are cases where decoding a gist can cause panics when the encoded format doesn't exactly match what is expected by the code. For example, see https://github.com/cockroachdb/cockroach/issues/113900. This is especially likely when decoding a gist that was encoded by a different version of CockroachDB.

The DB console performs gist decoding of sampled queries, making it likely that a customer might run into this issue in production.

**Describe the solution you'd like**
We'd like to discover cases where gist decoding can cause panics so they can be fixed *before* customers run into them in production. One idea is to randomly generate queries using sqlsmith, encode them as a gist, and then make sure they can be decoded without a panic. We could also write this as a mixed version roach test.

Jira issue: CRDB-35283

**Comment by mgartner** [comment]
@yuzefovich are you still planning on doing this during 24.1 stability, or should we push to the backlog or 24.2?
