### ISSUE TITLE
raft: 100000001 received msgApp rejection

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#1176]
run
```
#!/bin/sh

killall -9 cockroach
for i in 1 2 3; do
  rm -rf /tmp/data${i}
  if [ $i -eq 1 ]; then
    ./cockroach init --stores=ssd=/tmp/data${i}
  fi
  ./cockroach start --verbosity=1 --scan-interval=1s --stores=ssd=/tmp/data${i} --gossip=:8001 --addr=:800${i} --insecure &> log${i} &
done
```

and the leader's log fills with:

>
I0528 10:55:40.708232   59487 raft.go:517] raft: 100000001 received msgApp rejection(lastindex: 2421) from 200000002 for index 2422
I0528 10:55:40.805071   59487 raft.go:517] raft: 100000001 received msgApp rejection(lastindex: 2423) from 200000002 for index 2424
I0528 10:55:40.805156   59487 raft.go:517] raft: 100000001 received msgApp rejection(lastindex: 2423) from 300000003 for index 2424
I0528 10:55:40.805596   59487 raft.go:517] raft: 100000001 received msgApp rejection(lastindex: 2424) from 200000002 for index 2425
I0528 10:55:40.805779   59487 raft.go:517] raft: 100000001 received msgApp rejection(lastindex: 2424) from 300000003 for index 2425
I0528 10:55:42.816474   59487 raft.go:517] raft: 100000001 received msgApp rejection(lastindex: 2437) from 200000002 for index 2438
I0528 10:55:43.710897   59487 raft.go:517] raft: 100000001 received msgApp rejection(lastindex: 2441) from 200000002 for index 2442

there are roughly as many of those messages as there are log entries. Leadership is stable; I've checked at verbosity 5.

**Comment by bdarnell** [comment]
Interesting. Looks like messages are being processed out of order by the transport (a v=5 log would show for sure). I've been looking at other issues related to the raft transport (redundant messages, etc); I think I'm going to overhaul it after the alpha. In the meantime, these messages are mostly harmless. Raft retries and recovers (as you can see by the increasing index), but it's less efficient than it would be if messages were in order.

**Comment by tschottdorf** [comment]
I've looked at this a little more and I think (but please confirm) that this isn't an "error" in the transport, but a side-effect of relentlessly doing fire-and-forget. We call `client.Go` in the correct order, but the messages may be received in a different order on the remote.
I've checked this by [adding code](https://gist.github.com/tschottdorf/bb752a691a196104f344) in `raft_transport.go` which verifies that the append requests are strictly ascending without gaps (panicking when it happens). The result is that it panics right after the first remote has rejected an MsgApp and messages with lower index are re-sent, not before. I've looked at the logs quite a bit too, and it seems to me that there's no other explanation other than that `client.Go` reorders them. Which is also not an error, it just seems surprising that it would actually happen in practice.
I also only see when I run the cluster locally on my bare metal (without boot2docker), so this is probably highly sensitive to timing. I'll ignore it for now.

**Comment by es-chow** [comment]
I observed this MsgApp rejection in my setting,too. The reason may be RPC service side process the MsgApp out of order as RPC server will start a go route for each message. But I cannot figure out a solution now. The following snippet is from net/rpc/server.go
```go
func (server *Server) ServeCodec(codec ServerCodec) {
        sending := new(sync.Mutex)
        for {
                service, mtype, req, argv, replyv, keepReading, err := server.readRequest(codec)
                if err != nil {
                        if debugLog && err != io.EOF {
                                log.Println("rpc:", err)
                        }
                        if !keepReading {
                                break
                        }
                        // send a response if we actually managed to read a header.                                                                                               
                        if req != nil {
                                server.sendResponse(sending, req, invalidRequest, codec, err.Error())
                                server.freeRequest(req)
                        }
                        continue
                }
                go service.call(server, sending, mtype, req, argv, replyv, codec)
        }
        codec.Close()
}
```

**Comment by es-chow** [comment]
maybe we can change serveConn in cockroach/rpc/server.go to call ServeRequest other than ServeCodec, so no go routine involved.

**Comment by petermattis** [comment]
I don't think we want to change server-side handling of RPCs to be single-threaded. Let's figure out a different way to solve this.

**Comment by bdarnell** [comment]
Raft messages are already effectively single-threaded (one thread per store), since the RaftMessage RPC handler doesn't really do anything but pass the incoming message onto a channel to be read by the multiraft thread. Writes are also serialized by raft, so it might be reasonable to not create goroutines in the rpc layer, and instead wait until we decide that the RPC is for a read (which is the only thing that we can effectively parallelize now).

But in the short term I think the best fix is to make a batch version of RaftMessageRequest so that all the messages that come out of raft in one batch are sent as a unit and handled in order.

**Comment by petermattis** [comment]
The goroutine creation happens within the stdlib `net/rpc` code making it hard to avoid without forking that code. Certainly could be done, just feels a bit ugly.

**Comment by tamird** [comment]
Now that we've gone and forked that code, I think this is good to close.
