### ISSUE TITLE
roachtest: port smoketest/secure/multitenant to new APIs

### ISSUE THREAD

**Issue by herkolategan** [cockroachdb/cockroach#117674]
See the parent issue [1] for details.
Test location: `pkg/cmd/roachtest/tests/smoketest_secure.go`

[1] https://github.com/cockroachdb/cockroach/issues/115867

Epic: [CRDB-31933](https://cockroachlabs.atlassian.net/browse/CRDB-31933)

Jira issue: CRDB-35300

**Comment by renatolabs** [comment]
@herkolategan I think the right move is actually to delete the `smoketest_secure.go` file instead 😄

The tests in that file are _very_ basic (to the extent that they shouldn't even be roachtests), and many other tests in the nightly suite should have failed if the functionality they test was not working.

Thoughts?
