### ISSUE TITLE
trace: add ability to automatically trigger verbose logging on matching spans

### ISSUE THREAD

**Issue by dhartunian** [cockroachdb/cockroach#117624]
**Is your feature request related to a problem? Please describe.**
Today, we disable verbose logging in spans by default unless a user enables tracing or runs a statement diagnostic etc. There are, however, many spans which run very infrequently or very slowly that could easily handle verbose logging without taking a performance hit.

A user should be able to set up some allowlists which permit spans matching the list to always be verbose by default. This would collect helpful logs for certain operations all the time allowing for easier debugging.

**Describe the solution you'd like**
A possible implementation is a regular expression in a cluster setting which can be updated at runtime. When spans are created, their names can be matched against the regex and verbose logging can be enabled if the match is successful.

Jira issue: CRDB-35276

Epic CRDB-35278

**Comment by abarganier** [comment]
Had a chat with @dt today, a couple notes.

* The primary surface used by the DR team to consume traces are `crdb_internal.cluster_inflight_traces`. If debugging issues in test clusters, the Jaeger and/or OpenTelemetry Collector may be used.
    * Also we should ensure that what we do here impacts statement bundles, although those might already be verbose (need to check on this). 
* Enhancements of surfaces to consume traces is out of scope for this request.
* Something like a cluster setting of vmodule-like interface for setting a list of op names to mark verbose (and all its children) is the right idea.

I'm going to look into the vmodule interface to see if there's anything there that'd fit this well, but if not I'll opt for the cluster setting. Whether we use regex or a comma-separated list of op names will depend on performance considerations. Adding a list of names to a set and doing O(1) lookups against it might be necessary if the O(n) regex evaluation is too slow.

**Comment by abarganier** [comment]
Regarding the vmodule stuff, I noticed that it allows regex-like patterns to be passed (e.g. `*`, `?`, etc).

This motivates me to try to get regex working. I'm going to go ahead with a cluster setting for this approach. This means the config will apply cluster-wide.

**Comment by abarganier** [comment]
This was implemented via https://github.com/cockroachdb/cockroach/pull/118984

Closing.
