### ISSUE TITLE
import: v23.1.13: ReturnType called on TypedExpr with empty typeAnnotation on a subquery

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#117724]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4853567853/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4853567853/?referrer=webhooks_plugin)

Panic Message:

```
expr.go:152: ReturnType called on TypedExpr with empty typeAnnotation. Was the underlying Expr type-checked before asserting a type of TypedExpr?
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | [...repeated from below...]
Wraps: (2) assertion failure
Wraps: (3) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.typeAnnotation.assertTyped
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/expr.go:152
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*Subquery).TypeCheck
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/type_check.go:1503
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*overloadTypeChecker).typeCheckOverloadedExprs
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/overload.go:842
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*BinaryExpr).TypeCheck
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/type_check.go:320
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*overloadTypeChecker).typeCheckOverloadedExprs
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/overload.go:842
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FuncExpr).TypeCheck
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/type_check.go:1081
  | github.com/cockroachdb/cockroach/pkg/sql/importer.readPostgresStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/importer/read_import_pgdump.go:787
  | github.com/cockroachdb/cockroach/pkg/sql/importer.readPostgresCreateTable
  | 	github.com/cockroachdb/cockroach/pkg/sql/importer/read_import_pgdump.go:513
  | github.com/cockroachdb/cockroach/pkg/sql/importer.parseAndCreateBundleTableDescs
  | 	github.com/cockroachdb/cockroach/pkg/sql/importer/import_job.go:911
  | github.com/cockroachdb/cockroach/pkg/sql/importer.(*importResumer).parseBundleSchemaIfNeeded
  | 	github.com/cockroachdb/cockroach/pkg/sql/importer/import_job.go:781
  | github.com/cockroachdb/cockroach/pkg/sql/importer.(*importResumer).Resume
  | 	github.com/cockroachdb/cockroach/pkg/sql/importer/import_job.go:113
  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine.func2
  | 	github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1630
  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine
  | 	github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1631
  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).runJob
  | 	github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:474
  | github.com/cockroachdb/cockroach/pkg/jobs.(*StartableJob).Start.func2
  | 	github.com/cockroachdb/cockroach/pkg/jobs/jobs.go:978
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (4) ReturnType called on TypedExpr with empty typeAnnotation. Was the underlying Expr type-checked before asserting a type of TypedExpr?
Error types: (1) *withstack.withStack (2) *assert.withAssertionFailure (3) *withstack.withStack (4) *errutil.leafError
-- report composition:
*errutil.leafError: ReturnType called on TypedExpr with empty typeAnnotation. Was the underlying Expr type-checked before asserting a type of TypedExpr?
expr.go:152: *withstack.withStack (top exception)
*assert.withAssertionFailure
panic.go:884: *withstack.withStack (1)
(check the extra data payloads)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/util/stop/stopper.go#L469-L471](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/util/stop/stopper.go#L469-L471)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/jobs/jobs.go#L977-L979](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/jobs/jobs.go#L977-L979)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/jobs/adopt.go#L473-L475](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/jobs/adopt.go#L473-L475)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/jobs/registry.go#L1630-L1632](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/jobs/registry.go#L1630-L1632)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/jobs/registry.go#L1629-L1631](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/jobs/registry.go#L1629-L1631)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/importer/import_job.go#L112-L114](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/importer/import_job.go#L112-L114)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/importer/import_job.go#L780-L782](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/importer/import_job.go#L780-L782)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/importer/import_job.go#L910-L912](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/importer/import_job.go#L910-L912)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/importer/read_import_pgdump.go#L512-L514](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/importer/read_import_pgdump.go#L512-L514)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/importer/read_import_pgdump.go#L786-L788](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/importer/read_import_pgdump.go#L786-L788)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/sem/tree/type_check.go#L1080-L1082](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/sem/tree/type_check.go#L1080-L1082)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/sem/tree/overload.go#L841-L843](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/sem/tree/overload.go#L841-L843)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/sem/tree/type_check.go#L319-L321](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/sem/tree/type_check.go#L319-L321)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/sem/tree/overload.go#L841-L843](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/sem/tree/overload.go#L841-L843)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/sem/tree/type_check.go#L1502-L1504](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/sem/tree/type_check.go#L1502-L1504)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/sem/tree/expr.go#L151-L153](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/sem/tree/expr.go#L151-L153)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/util/stop/stopper.go#L469-L471](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/util/stop/stopper.go#L469-L471)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/jobs/jobs.go#L977-L979](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/jobs/jobs.go#L977-L979)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/jobs/adopt.go#L473-L475](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/jobs/adopt.go#L473-L475)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/jobs/registry.go#L1630-L1632](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/jobs/registry.go#L1630-L1632)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/jobs/registry.go#L1629-L1631](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/jobs/registry.go#L1629-L1631)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/importer/import_job.go#L112-L114](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/importer/import_job.go#L112-L114)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/importer/import_job.go#L780-L782](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/importer/import_job.go#L780-L782)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/importer/import_job.go#L910-L912](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/importer/import_job.go#L910-L912)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/importer/read_import_pgdump.go#L512-L514](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/importer/read_import_pgdump.go#L512-L514)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/importer/read_import_pgdump.go#L786-L788](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/importer/read_import_pgdump.go#L786-L788)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/sem/tree/type_check.go#L1080-L1082](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/sem/tree/type_check.go#L1080-L1082)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/sem/tree/overload.go#L841-L843](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/sem/tree/overload.go#L841-L843)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/sem/tree/type_check.go#L319-L321](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/sem/tree/type_check.go#L319-L321)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/sem/tree/overload.go#L841-L843](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/sem/tree/overload.go#L841-L843)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/sem/tree/type_check.go#L1502-L1504](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/sem/tree/type_check.go#L1502-L1504)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/sem/tree/expr.go#L151-L153](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/sem/tree/expr.go#L151-L153)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 470
pkg/jobs/jobs.go in pkg/jobs.(*StartableJob).Start.func2 at line 978
pkg/jobs/adopt.go in pkg/jobs.(*Registry).runJob at line 474
pkg/jobs/registry.go in pkg/jobs.(*Registry).stepThroughStateMachine at line 1631
pkg/jobs/registry.go in pkg/jobs.(*Registry).stepThroughStateMachine.func2 at line 1630
pkg/sql/importer/import_job.go in pkg/sql/importer.(*importResumer).Resume at line 113
pkg/sql/importer/import_job.go in pkg/sql/importer.(*importResumer).parseBundleSchemaIfNeeded at line 781
pkg/sql/importer/import_job.go in pkg/sql/importer.parseAndCreateBundleTableDescs at line 911
pkg/sql/importer/read_import_pgdump.go in pkg/sql/importer.readPostgresCreateTable at line 513
pkg/sql/importer/read_import_pgdump.go in pkg/sql/importer.readPostgresStmt at line 787
pkg/sql/sem/tree/type_check.go in pkg/sql/sem/tree.(*FuncExpr).TypeCheck at line 1081
pkg/sql/sem/tree/overload.go in pkg/sql/sem/tree.(*overloadTypeChecker).typeCheckOverloadedExprs at line 842
pkg/sql/sem/tree/type_check.go in pkg/sql/sem/tree.(*BinaryExpr).TypeCheck at line 320
pkg/sql/sem/tree/overload.go in pkg/sql/sem/tree.(*overloadTypeChecker).typeCheckOverloadedExprs at line 842
pkg/sql/sem/tree/type_check.go in pkg/sql/sem/tree.(*Subquery).TypeCheck at line 1503
pkg/sql/sem/tree/expr.go in pkg/sql/sem/tree.typeAnnotation.assertTyped at line 152
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 470
pkg/jobs/jobs.go in pkg/jobs.(*StartableJob).Start.func2 at line 978
pkg/jobs/adopt.go in pkg/jobs.(*Registry).runJob at line 474
pkg/jobs/registry.go in pkg/jobs.(*Registry).stepThroughStateMachine at line 1631
pkg/jobs/registry.go in pkg/jobs.(*Registry).stepThroughStateMachine.func2 at line 1630
pkg/sql/importer/import_job.go in pkg/sql/importer.(*importResumer).Resume at line 113
pkg/sql/importer/import_job.go in pkg/sql/importer.(*importResumer).parseBundleSchemaIfNeeded at line 781
pkg/sql/importer/import_job.go in pkg/sql/importer.parseAndCreateBundleTableDescs at line 911
pkg/sql/importer/read_import_pgdump.go in pkg/sql/importer.readPostgresCreateTable at line 513
pkg/sql/importer/read_import_pgdump.go in pkg/sql/importer.readPostgresStmt at line 787
pkg/sql/sem/tree/type_check.go in pkg/sql/sem/tree.(*FuncExpr).TypeCheck at line 1081
pkg/sql/sem/tree/overload.go in pkg/sql/sem/tree.(*overloadTypeChecker).typeCheckOverloadedExprs at line 842
pkg/sql/sem/tree/type_check.go in pkg/sql/sem/tree.(*BinaryExpr).TypeCheck at line 320
pkg/sql/sem/tree/overload.go in pkg/sql/sem/tree.(*overloadTypeChecker).typeCheckOverloadedExprs at line 842
pkg/sql/sem/tree/type_check.go in pkg/sql/sem/tree.(*Subquery).TypeCheck at line 1503
pkg/sql/sem/tree/expr.go in pkg/sql/sem/tree.typeAnnotation.assertTyped at line 152
```

### Tags

| Tag | Value |
| --- | --- |
| Command | start-single-node |
| Environment | v23.1.13 |
| Go Version | go1.19.13 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.13 |
| Cockroach SHA | 8d065df26e25a762a1abbbf2b1e475456b341a00 |
| # of CPUs | 4 |
| # of Goroutines | 334 |

Jira issue: CRDB-35321

**Comment by DrewKimball** [comment]
This is another location where we call `TypeCheck` outside of the optbuilder:
https://github.com/cockroachdb/cockroach/blob/cc4fdffa8532d16544c48ef036689763f737dc6b/pkg/sql/importer/read_import_pgdump.go#L784-L796
