### ISSUE TITLE
build: TestStyle/TestMetacheck is excessively slow

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#11779]
```
~ make check
...
    --- PASS: TestStyle/TestMetacheck (207.07s)
```

**Comment by tamird** [comment]
@dominikh this seems to be a consequence of the new lintutil API which we moved to in https://github.com/cockroachdb/cockroach/pull/11759.

I did a bit of testing - when I modify `metacheck` to only run one of the three linters, the results are:
```
simple.NewChecker(),      // (31.95s)
staticcheck.NewChecker(), // (20.52s)
unused.NewLintChecker(unusedChecker), // (25.60s)
```
When I combine two checkers, things go off the rails: `simple` + `staticcheck` = `(269.20s)`.

I'm still running the other combinations, but something whacky is definitely going on here.

**Comment by dominikh** [comment]
I cannot reproduce the issue. Using your exact version of metacheck from the linked-to PR, it takes ~25 seconds to check the Go standard library. Running the 3 checks separately, I get 9.5s, 20s and 11.5s respectively. 

If anything, I am surprised that in your case, running the 3 separately, both simple and unused take longer to run than staticcheck.

**Comment by dominikh** [comment]
Also, the three tools should not be able to influence each other. They just contribute init functions and lists of checks to run. Are you sure that your environment is sane and the timing information you gathered are accurate?

**Comment by tamird** [comment]
Odd; I must have messed up the original measurements - it seems that `staticcheck` alone is responsible for all the slowdown. By itself, it now takes 4 minutes.

**Comment by dominikh** [comment]
Can you tell me the set of packages it is run on, so I can debug this locally?

**Comment by tamird** [comment]
`github.com/cockroachdb/cockroach/pkg/...`
