### ISSUE TITLE
storage: add action metrics for replica GC queue

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#11784]
The current replica GC queue stats show the number of replicas processed and the time that took, but not how many times `Store.RemoveReplica` as been called. This is similar to #11753 which added stats for the various actions taken by the replicate queue.

**Comment by petermattis** [comment]
Note that what I'm asking for here is slightly different than the existing `StoreMetrics.RangeRemoves` metric. That metric is powered by the `ChangeReplicas` operation and notes when a replica is removed from a range's descriptor. The replica GC queue metric will track when the replica data is deleted from disk.

**Comment by tamird** [comment]
Yep, understood. I'll add this shortly.
