### ISSUE TITLE
roachprod: indefinite cluster

### ISSUE THREAD

**Issue by herkolategan** [cockroachdb/cockroach#117805]
In order to support long running test clusters on roachprod without having to manage expiry a new feature should be added to enable creating indefinite clusters.

Preferably this option should be guarded by a proper warning and confirmation and reported to roachprod status channels on each GC to inform everyone that the cluster is still running at cost.

Epic: CRDB-33832

Jira issue: CRDB-35368

**Comment by renatolabs** [comment]
Is this a required feature? I'm wondering if we would be better off just setting a really long expiry time (1 year+) and setting up reminders through other means (builtin Slack reminders, calendar reminders, etc) to extend the expiry as needed well in advance (i.e., first reminder a month before expiry).

**Comment by herkolategan** [comment]
Fair enough. It came up in a discussion, but it is a very specific feature for a limited use. Schedules should suffice.
