### ISSUE TITLE
kv: add unit testing for `constraintsCheckFn` impls

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#117891]
The following four functions are used to implement `constraintsCheckFn`s:
- `allocateConstraintsCheck`
- `replaceConstraintsCheck`
- `removeConstraintsCheck`
- `rebalanceFromConstraintsCheck`

They are tested, but from far away. Their logic is too complex to not have unit tests that directly wrap them. We should add some.

This would have caught https://github.com/cockroachdb/cockroach/issues/117886.

Jira issue: CRDB-35413

**Comment by kvoli** [comment]
`allocateConstraintsCheck` and `removeConstraintsCheck` both have existing unit tests:

https://github.com/cockroachdb/cockroach/blob/695f7efa3fca5e13668baa418dc4f4450ac9677b/pkg/kv/kvserver/allocator/allocatorimpl/allocator_scorer_test.go#L727-L727

https://github.com/cockroachdb/cockroach/blob/695f7efa3fca5e13668baa418dc4f4450ac9677b/pkg/kv/kvserver/allocator/allocatorimpl/allocator_scorer_test.go#L960-L960
