### ISSUE TITLE
build: investigate popular deployment packages

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#11783]
Suggested by @jpalandri on gitter: 

see: http://snapcraft.io 

> you bundle the dependencies you need in the exact version you need them - nothing to worry about the 'host' OS
and you decide when your users update by pushing new versions in the stable channel
you could also pipe your trunk/master branch into the edge channel, allowing people to always taste the latest flavour of what you're working on
(all this automatically built and pushed, of course )

The suggested starting point:
> you can take the snapcraft tour http://snapcraft.io/create/ and ping us when (if ) you ever feel blocked - we're on #snapcraft on irc or in rocket.ubuntu.com (itself a snap )

**Comment by vbmade2000** [comment]
I can take this issue if you don't mind.

**Comment by dt** [comment]
@vbmade2000 Great! Recently, discussion of snap packaging has moved over on the forums -- might be good to chime in there with a plan: https://forum.cockroachlabs.com/t/packaging-crdb-for-ubuntu/446

**Comment by petermattis** [comment]
In addition to Snap packages, we should also investigate other package managers such as DEB and RPM.

**Comment by kannanlakshmi** [comment]
@petermattis yes DEB and RPM are on the 2.1 roadmap https://airtable.com/tblD3oZPLJgGhCmch/viw7QvkUF4f3UBRCd/reczbosRzSmYMRwkm

**Comment by mberhault** [comment]
@kannanlakshmi: this is a very vague issue. Are there product priorities for package manager?

**Comment by kannanlakshmi** [comment]
DEB RPM package managers was on 2.1 roadmap but got de-prioritized to other things. So, no not a product priority at the moment. This can be closed for now.

**Comment by Dmole** [comment]
This should really be re-opend as it's a set and forget task that will let users not get stuck in 1998 before package management. Applying security and bug fixes to software you want people to actually use needs to be automated or trivial.

**Comment by ltworf** [comment]
If they hadn't forked internally a bunch of libraries it could just be packaged as a normal debian package and be added to debian. But with the library fork it becomes kind of a mess. For security reasons only important enough projects that do this are allowed into debian.
