### ISSUE TITLE
CockroachDB favicon does not render for DB Console running v23.1.13

### ISSUE THREAD

**Issue by lancel66** [cockroachdb/cockroach#117876]
**Describe the problem**

CockroachDB favicon does not render for DB Console running v23.1.13

![image (3)](https://github.com/cockroachdb/cockroach/assets/8233381/b9a6826f-77df-4199-bc3c-d0b8645bb7cb)

**To Reproduce**

Upgrade from v22.2.x

**Expected behavior**
Favicon restored

**Additional context**
Operator Inconvenienced 

Jira issue: CRDB-35397

**Comment by Tomburgs** [comment]
we're having the same issue. literally unusable.
