### ISSUE TITLE
sql/catalog/lease: TestLeaseRenewedPeriodically prone to stalling under `deadlock` when cluster virtualization is used, apparently only under remote execution

### ISSUE THREAD

**Issue by rickystewart** [cockroachdb/cockroach#117929]
Under `deadlock`, this test is prone to stalling. I think the problem is isolated to when cluster virtualization is randomly injected (i.e., reproduce with `--test_env=COCKROACH_TEST_TENANT=true`), and does not reproduce locally but only under remote execution. Locally, I see the test is substantially slower when cluster virtualization is enabled, but it does not last 20+ minutes.

[Sample link on EngFlow](https://tanzanite.cluster.engflow.com/invocations/default/d935f665-b229-47e2-8bd4-3230b5624aca?testReportShard=33&testReportRun=3&testReportAttempt=0#targets-Ly9wa2cvc3FsL2NhdGFsb2cvbGVhc2U6bGVhc2VfdGVzdA==)

I can't parse much from the logs but I see that we're stuck waiting for some signals and/or mutexes?

```
goroutine 10 [syscall, 24 minutes]:
os/signal.signal_recv()
	GOROOT/src/runtime/sigqueue.go:152 +0x29
os/signal.loop()
	GOROOT/src/os/signal/signal_unix.go:23 +0x13
created by os/signal.Notify.func1.1 in goroutine 50
	GOROOT/src/os/signal/signal.go:151 +0x1f

goroutine 17671989 [semacquire, 23 minutes]:
sync.runtime_Semacquire(0x18?)
	GOROOT/src/runtime/sema.go:62 +0x25
sync.(*WaitGroup).Wait(0x47ecc0?)
	GOROOT/src/sync/waitgroup.go:116 +0x48
```

Relates to https://github.com/cockroachdb/cockroach/issues/112957

Jira issue: CRDB-35418

Epic CRDB-8308

**Comment by rafiss** [comment]
We should make sure that the test is overriding cluster settings in a way that works for cluster virtualization.

**Comment by rickystewart** [comment]
FYI: Going to try un-skipping this test pre-emptively in #119244.

**Comment by fqazi** [comment]
@rickystewart Does that mean we haven't seen this again after https://github.com/cockroachdb/cockroach/pull/119244 was merged?

**Comment by rickystewart** [comment]
I haven't seen this test fail recently. I'm OK with closing this.
