### ISSUE TITLE
Sentry: crash_reporting.go:390: flow d45f0639: unexpected 40960 leftover bytes
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/util/log/logcrash.ReportOrPanic
  | 	...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#117980]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4895204143/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4895204143/?referrer=webhooks_plugin)

Panic Message:

```
crash_reporting.go:390: flow d45f0639: unexpected 40960 leftover bytes
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/util/log/logcrash.ReportOrPanic
  | 	github.com/cockroachdb/cockroach/pkg/util/log/logcrash/crash_reporting.go:390
  | github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).doStop
  | 	github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:592
  | github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).Stop
  | 	github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:565
  | github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Cleanup
  | 	github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:699
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Cleanup
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:416
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll.func4
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1662
  | github.com/cockroachdb/cockroach/pkg/sql.(*cleanupFuncStack).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/prepared_stmt.go:251
  | github.com/cockroachdb/cockroach/pkg/sql.(*portalPauseInfo).cleanupAll
  | 	github.com/cockroachdb/cockroach/pkg/sql/prepared_stmt.go:373
  | github.com/cockroachdb/cockroach/pkg/sql.(*PreparedPortal).close
  | 	github.com/cockroachdb/cockroach/pkg/sql/prepared_stmt.go:224
  | github.com/cockroachdb/cockroach/pkg/sql.(*prepStmtNamespace).closeAllPortals
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1807
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).commitSQLTransactionInternal
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1301
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).commitSQLTransaction
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1234
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).handleAutoCommit
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2728
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2332
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2097
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:893
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:778
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (2) flow d45f0639: unexpected 40960 leftover bytes
Error types: (1) *withstack.withStack (2) *errutil.leafError
-- report composition:
*errutil.leafError: flow d45f0639: unexpected 40960 leftover bytes
crash_reporting.go:390: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/pgwire/conn.go#L777-L779](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/pgwire/conn.go#L777-L779)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/conn_executor.go#L892-L894](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/conn_executor.go#L892-L894)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/conn_executor.go#L2096-L2098](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/conn_executor.go#L2096-L2098)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/conn_executor.go#L2331-L2333](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/conn_executor.go#L2331-L2333)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/conn_executor_exec.go#L2727-L2729](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/conn_executor_exec.go#L2727-L2729)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/conn_executor_exec.go#L1233-L1235](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/conn_executor_exec.go#L1233-L1235)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/conn_executor_exec.go#L1300-L1302](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/conn_executor_exec.go#L1300-L1302)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/conn_executor.go#L1806-L1808](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/conn_executor.go#L1806-L1808)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/prepared_stmt.go#L223-L225](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/prepared_stmt.go#L223-L225)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/prepared_stmt.go#L372-L374](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/prepared_stmt.go#L372-L374)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/prepared_stmt.go#L250-L252](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/prepared_stmt.go#L250-L252)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/distsql_running.go#L1661-L1663](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/distsql_running.go#L1661-L1663)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/colflow/vectorized_flow.go#L415-L417](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/colflow/vectorized_flow.go#L415-L417)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/flowinfra/flow.go#L698-L700](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/flowinfra/flow.go#L698-L700)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/util/mon/bytes_usage.go#L564-L566](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/util/mon/bytes_usage.go#L564-L566)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/util/mon/bytes_usage.go#L591-L593](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/util/mon/bytes_usage.go#L591-L593)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/util/log/logcrash/crash_reporting.go#L389-L391](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/util/log/logcrash/crash_reporting.go#L389-L391)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommandsAsync.func1 at line 778
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 893
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 2097
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 2332
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).handleAutoCommit at line 2728
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).commitSQLTransaction at line 1234
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).commitSQLTransactionInternal at line 1301
pkg/sql/conn_executor.go in pkg/sql.(*prepStmtNamespace).closeAllPortals at line 1807
pkg/sql/prepared_stmt.go in pkg/sql.(*PreparedPortal).close at line 224
pkg/sql/prepared_stmt.go in pkg/sql.(*portalPauseInfo).cleanupAll at line 373
pkg/sql/prepared_stmt.go in pkg/sql.(*cleanupFuncStack).run at line 251
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRunAll.func4 at line 1662
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlow).Cleanup at line 416
pkg/sql/flowinfra/flow.go in pkg/sql/flowinfra.(*FlowBase).Cleanup at line 699
pkg/util/mon/bytes_usage.go in pkg/util/mon.(*BytesMonitor).Stop at line 565
pkg/util/mon/bytes_usage.go in pkg/util/mon.(*BytesMonitor).doStop at line 592
pkg/util/log/logcrash/crash_reporting.go in pkg/util/log/logcrash.ReportOrPanic at line 390
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v23.1.4 |
| Go Version | go1.19.4 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.4 |
| Cockroach SHA | cf85e8ad48bb7a8afd821863d4f345baafa4a1b6 |
| # of CPUs | 12 |
| # of Goroutines | 942 |

Jira issue: CRDB-35442

**Comment by yuzefovich** [comment]
dup of #110486
