### ISSUE TITLE
pkg/ccl/serverccl/statusccl/statusccl_test: TestTenantStatusAPI/tenant_cancel_session failed

### ISSUE THREAD

**Issue by abarganier** [cockroachdb/cockroach#117938]
pkg/ccl/serverccl/statusccl/statusccl_test.TestTenantStatusAPI [failed](https://tanzanite.cluster.engflow.com/invocations/default/05b0e99b-d107-4e85-a3f1-e9a9d88b8559?testReportRun=3&testReportShard=1&testReportAttempt=1#targets-Ly9wa2cvY2NsL3NlcnZlcmNjbC9zdGF0dXNjY2w6c3RhdHVzY2NsX3Rlc3Q=) on master @ [53e4efd389167110d687e5dea8bf915fe2582a25](https://github.com/cockroachdb/cockroach/commits/53e4efd389167110d687e5dea8bf915fe2582a25):

```
=== RUN   TestTenantStatusAPI
    test_log_scope.go:170: test logs captured to: outputs.zip/logTestTenantStatusAPI126773897
    tenant_status_test.go:141: -- test log scope end --
CREATE UNIQUE INDEX test_pkey ON test_db1.public.test USING btree (k ASC)test logs left over in: outputs.zip/logTestTenantStatusAPI126773897
--- FAIL: TestTenantStatusAPI (983.90s)
=== RUN   TestTenantStatusAPI/tenant_cancel_session
    tenant_status_test.go:1073: error executing 'SELECT session_id FROM crdb_internal.cluster_sessions WHERE status = 'ACTIVE' OR status = 'IDLE'': read tcp 127.0.0.1:60764->127.0.0.1:40353: read: connection reset by peer
    tenant_status_test.go:1114: 
        	Error Trace:	pkg/ccl/serverccl/statusccl/statusccl_test/pkg/ccl/serverccl/statusccl/tenant_status_test.go:1114
        	            				pkg/ccl/serverccl/statusccl/statusccl_test/pkg/ccl/serverccl/statusccl/tenant_status_test.go:94
        	Error:      	Condition never satisfied
        	Test:       	TestTenantStatusAPI/tenant_cancel_session
    --- FAIL: TestTenantStatusAPI/tenant_cancel_session (7.00s)
```
Parameters:

- `attempt=1`
- `race=true`
- `run=3`
- `shard=1`

Jira issue: CRDB-35425

**Comment by rickystewart** [comment]
@abarganier Not sure why this is being posted now, but this is a failure from a month ago. The issue might be exclusive to the EngFlow environment as we had it configured back last month. A lot of changes have been made since then and I have not seen failures of this test since then. However, if this test shouldn't be running under `race` at all, the `skip.UnderStressRace` could be replaced with `skip.UnderRace`.

**Comment by abarganier** [comment]
@rickystewart thanks for the context. This got mixed into https://github.com/cockroachdb/cockroach/issues/116863 and I didn't pay attention to the last failure date as I was splitting the failure out into this new ticket.

I think this test should be fine to run under race. Since the test hasn't failed since the EngFlow env changes, I'm going to close for now. We'll take another look if we see new failures. Thanks again.
