### ISSUE TITLE
pcr: failback timestamp may not be protected

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#117984]
If we send a heartbeat saying we've consumed up to T5 in the consumer job, currently the producer will accordingly move its protected timestamp to T5. If we then cutover to T4 on our consumer, and subsequently attempt to reverse the replication direction, we will need to revert the former producer to the cutover time -- T4 -- before it can begin consuming the reversed flow from the new producer as of the time it cutover. However the protected timestamp on the former producer was previously advanced to T5, meaning this T4 timestamp to which it now needs to revert is unprotected and this revet may fail.

Jira issue: CRDB-35443

**Comment by msbutler** [comment]
Currently the producer side PTS is pushed using the replicated time sent by the consumer[ here](https://github.com/msbutler/cockroach/blob/master/pkg/ccl/streamingccl/streamproducer/stream_lifetime.go#L147). The consumer specifically sends the persisted replicated time [here](https://github.com/msbutler/cockroach/blob/master/pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go#L310). But, the dba is allowed to cutover to the destination side _retained_ time (determined by the pts on the destination side), which can be earlier than the producer side PTS managed by the heartbeat sender.

To address this issue, i think the destination side heartbeat sender needs to begin sending timestamps of the destination side _retained time_ pts not the _replicated_ time, if we want any eligible cutover time to be protected on the producer. But, that would mean protecting _a lot_ of producer mvcc history...

**Comment by msbutler** [comment]
^Before we do the above, a more immediate problem is ensuring we can failback after CUTOVER FROM LATEST. To ensure this, we must require that the heartbeat time stamp sent by the consumer is never greater than the cutover timestamp.

**Comment by azhu-crl** [comment]
Closing the issue as it's been addressed by the following PRs:
https://github.com/cockroachdb/cockroach/pull/125578
https://github.com/cockroachdb/cockroach/pull/127892
