### ISSUE TITLE
ui: cpu/mem stats (particularly RocksDB)

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#1179]
See `runtime.NumGoroutines` and `runtime.MemStats`. We don't need all of the detail in `runtime.MemStats` collected. @mberhault can probably remember what we've done previously. We also need to figure out how to measure the memory used by RocksDB which won't show up in the go memory stats. Perhaps via `syscall.GetRusage`. Or if we're running on linux (as we'll be under docker), we can look at `/proc/<pid>/mem`.

**Comment by MBerhault** [comment]
We'll probably want runtime.NumCgoCall as well.

of the stuff in [MemStats](http://golang.org/pkg/runtime/#MemStats), we'll want at least:
* Current usage (useful if grabbed frequently)

  Alloc      uint64 // bytes allocated and still in use
  HeapAlloc    uint64 // bytes allocated and still in use

* Total alloc and GC (total counts, don't need them frequently)

  TotalAlloc uint64 // bytes allocated (even if freed)
  Sys        uint64 // bytes obtained from system (sum of XxxSys below)
  HeapSys      uint64 // bytes obtained from system
  HeapReleased uint64 // bytes released to the OS
  PauseTotalNs uint64
  NumGC        uint32

I think that's about right.

**Comment by petermattis** [comment]
Might also want to grab CPU utilization. Looking around the nets I see https://github.com/cloudfoundry/gosigar which parses CPU/Mem info from /proc.

**Comment by bdarnell** [comment]
We should use getrusage to measure our own cpu usage. Gosigar collects the system-wide CPU usage, which might be helpful but is less important (and is it even meaningful in a container, or is "system-wide" limited to our own container?)

**Comment by petermattis** [comment]
Gosigar looks like it reads both system-wide and per-process cpu info. Here is the per-process impl on linux: https://github.com/cloudfoundry/gosigar/blob/master/sigar_linux.go#L246

**Comment by tschottdorf** [comment]
Updated the title to draw attention to the biggest part that's left in the dark now that we're logging Go-related stuff in `server/node.go` regularly (not to TimeSeries yet, though). See #1217.

**Comment by petermattis** [comment]
`rocksdb::Cache` has `GetUsage()` method. There are also a whole bunch of rocksdb statistics such as cache hit/miss, bytes read/written, etc. We probably only want a subset of the rocksdb statistics.

**Comment by petermattis** [comment]
@cuongdo Much of this issue has been done. I think getting some basic stats from RocksDB is the final part to address. In particular, I'd like to track the cache memory usage, though there might be other interesting bits to collect as well. I can point you to where to get this info.

**Comment by cuongdo** [comment]
Do we just want to record RocksDB stats to the time-series data and provide visibility through status server endpoints and server log messages? 

Or, do we also want to expose somewhere in the UI?

**Comment by petermattis** [comment]
Not sure if the RocksDB cache size needs to be exposed in the UI. I was thinking of recording it to the time-series data much like the Go Runtime stats.
