### ISSUE TITLE
kv: number of ranges grows linearly after upgrade to 24.1 

### ISSUE THREAD

**Issue by ajstorm** [cockroachdb/cockroach#118134]
We recently upgraded the DRT cluster from 23.2 to master (24.1) and when the upgrade was finalized, we observed that the number of ranges on the cluster started growing linearly.

![image](https://github.com/cockroachdb/cockroach/assets/18447034/22cd6b63-8145-480d-ac6a-f077c7e66688)

The DRT cluster runs a workload where a new tpcc database is created and populated, then the workload is run for an hour, and finally the database is dropped before the cycle repeats.  This is expected to create MVCC garbage but that garbage is also expected to be cleaned up.  

Something seems to have broken in master where now that cleanup is no longer happening (or not happening completely).

This is being discussed in greater detail [here](https://cockroachlabs.slack.com/archives/C05FHJJ0MD0/p1705671015242739).

Jira issue: CRDB-35565

**Comment by joshimhoff** [comment]
@andrewbaptist, under what conditions would this bug affect a 24.1 prod CC cluster? Is a certain kind of workload needed?

**Comment by joshimhoff** [comment]
(Plz ignore my earlier comment. Thought this was 23.2 but it is 24.1.)
