### ISSUE TITLE
online restore: add ability to filter out some keys in spans by timestamp suffix

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#118279]
Restoring a table that was importing when it was backed up is not straightforward; the content of the table is not consistent mid-import so it cannot be restored to that state. The import job that would have moved it to a consistent state is not restored -- and even if it was, it has no expectation of being able to run on the restoring cluster, and the fact that restored data is written with timestamps as of the time at which it was restored makes such a job impossible to revert if it cannot succeed anyway. 

Historically, we have addressed this in one of two ways: not restoring the table at all, or restoring it but to its pre-import state, even though that was not its state as of when it was backed up. 

The former had some downsides. While it is true that the importing table was not available when the backup was created and is similarly not available when the backup is restored, there is a subtle difference between these two cases: in the backed up database or cluster, the table _would later be available_, when the running import job finished or rolled back, but there is no such expectation of future availability if the restored database or cluster where the table is omitted. This is a subtle difference, but could be significant; it could be a particularly unpleasant surprise when you restore a whole backup only to discover that since it was made while an import was running the entire table into which that important is writing is completely gone. 

Instead, RESTORE was previously extended to restore importing tables to their pre-import state, even though that was not the state in which they were when backed up. This was done by eliding any keys in the table that were written by the import, as determined by their timestamp suffixes being greater than the time at which the import started, which is recorded in the table descriptor when the import starts.

Online restore has to solve the same problem. The old behavior of omitting importing tables is a simple solution for the first iteration, but for the reasons described above, it would be preferable to instead match the  behavior of more recent versions of RESTORE and filter the import's keys out of the table. Doing so during an online restore would require extending pebble read-time key manipulations -- i.e. prefix and suffix rewriting -- to include suffix-based key eliding/filtering. 

Jira issue: CRDB-35660

**Comment by msbutler** [comment]
fixed by https://github.com/cockroachdb/cockroach/pull/120407
