### ISSUE TITLE
roachprod: manage clusters with MIGs on GCE

### ISSUE THREAD

**Issue by herkolategan** [cockroachdb/cockroach#118207]
Add the ability to create and manage clusters in `roachprod` using a GCE feature called managed instance groups (MIGs) [1]. MIGs require VMs to conform to an instance template, created before the MIG can be created. This allows the group to easily replace or add new virtual machines based on the template.

GCE supports both stateless and stateful MIGs. Stateful MIGs are a better fit for our application and allows retaining certain resources in the event a VM is replaced.

MIGs are required before we can proceed with features for expanding (growing), load-balancing or health monitoring clusters. 
This feature only requires current functionality to work with MIGs by passing a flag to `roachprod` to indicate that the cluster should be managed by a MIG. Once base support for MIGs have been built follow-up changes can implement the benefits provided by MIGs.

[1] https://cloud.google.com/compute/docs/instance-groups

Epic: [CRDB-33832](https://cockroachlabs.atlassian.net/browse/CRDB-33832)

Jira issue: CRDB-35610

**Comment by renatolabs** [comment]
@herkolategan should we close this issue? If not, what else do you think is necessary?
