### ISSUE TITLE
kvclient: DistSender must retry replica circuit breaker errors

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#118266]
It's possible for a replica circuit breaker to trip even though the range is fully functional. The only criteria is that a replica proposal (e.g. a lease request) does not succeed in 60 seconds. This can happen e.g. if the replica is partitioned away from the leader, if the replica is stale and no longer part of the range, if the replica has stalled, etc.

If a DistSender encounters this replica (e.g. it's cached as the previous leaseholder, or it happens to be the first replica it attempts) then it will return an error to the client immediately, without trying other replicas. This can lead to the range appearing unavailable to clients using this DistSender, even though the range itself may be fully functional.

The DistSender needs to retry circuit breaker errors by moving onto the next replica in line. If the range is in fact unavailable, then there are two possibilities: either each retry must wait for the next replicas's circuit breaker to trip in sequence (1 minute per replica), or all replica's circuit breakers are already tripped in which case we'll incur RTT latencies for each replica. This seems acceptable, considering the alternative is permanent unavailability, and an optimization to attempt replicas in parallel can be considered separately (e.g. #109320).

Jira issue: CRDB-35649

**Comment by miraradeva** [comment]
Related to this issue, @kvoli, @nvanbenschoten and I also talked about potentially rejecting lease acquisition requests from the catching-up node. Currently, if the node doesn't know who the leader is, we will still [let the lease acquisition request through](https://github.com/cockroachdb/cockroach/blob/59ad05a0e43d4c00307a0011d80e76f50549eb39/pkg/kv/kvserver/replica_proposal_buf.go#L685), and it could hang if the node is still catching up.

Instead, we can reject the proposal immediately, similarly to the [known-leader case](https://github.com/cockroachdb/cockroach/blob/59ad05a0e43d4c00307a0011d80e76f50549eb39/pkg/kv/kvserver/replica_proposal_buf.go#L703), and return a `NotALeaseholderError`. This would have the same effect as retrying the circuit-breaker errors at different replicas, and will also avoid the initial 60s of unavailability while we wait for the circuit breaker to trip.

**Comment by erikgrinaker** [comment]
Good idea, I'll have a look at #118435 once I get back to this issue.
