### ISSUE TITLE
sql,jobs: AUTO CREATE STATS jobs cleanup can abandon job_info rows

### ISSUE THREAD

**Issue by stevendanna** [cockroachdb/cockroach#118582]
**Describe the problem**

The AUTO CREATE STATS jobs has code to detect concurrent creation of a status job for a given table and exit with an error to avoid having duplicate stats jobs. Unfortunately, that code then deletes the job from the system.jobs table in an effort to avoid confusing error messages going to the user:

https://github.com/cockroachdb/cockroach/blob/cc4fdffa8532d16544c48ef036689763f737dc6b/pkg/sql/create_stats.go#L160-L170

This code fails to clean up the related system.job_info rows.  Those rows will never be cleaned up because our job-gc maintenance routine only cleans up jobs that are listed in the jobs table.

In a large cluster with many tables, this can result in a very large job_info table, slowing down jobs related queries substantially.

Jira issue: CRDB-35798

gz#20135

**Comment by msbutler** [comment]
keeping this open until all backports merge

**Comment by stevendanna** [comment]
All backports are merged. We should probably open another issue for the cleanup code.
