### ISSUE TITLE
roachtest: improve acceptance tests organization and running time

### ISSUE THREAD

**Issue by renatolabs** [cockroachdb/cockroach#118513]
The `Local roachtest` build is one of the longest running parts of CI[^1]. This build consists of a mostly ad-hoc set of roachtests that are run in roachtest's `local` mode on every PR:

https://github.com/cockroachdb/cockroach/blob/38dd16aac9b0b1e167c9ec6d16ccaf30789be25a/build/teamcity/cockroach/ci/tests/local_roachtest_impl.sh#L24

Added to this, tests in this selector pass the vast majority of times, providing very little signal of correctness of the code being tested. In order to better organize our acceptance tests and reduce the time spent on this build (and consequently in CI as well), we propose the following improvements:

* [ ] Constrain this build to only `acceptance` tests. In addition, the set of tests should be selected not by a name pattern, as currently done, but by a roachtest suite[^2].
* [ ] `acceptance/version-upgrade` is one of the longest acceptance tests currently. This test can be made shorter in CI by only performing a single upgrade when running in `local` mode[^3].

[^1]: see [internal thread](https://cockroachlabs.slack.com/archives/C023S0V4YEB/p1706309987998099).
[^2]: [type definition](https://github.com/cockroachdb/cockroach/blob/38dd16aac9b0b1e167c9ec6d16ccaf30789be25a/pkg/cmd/roachtest/registry/test_spec.go#L289-L296).
[^3]: Passing the `NumUpgrades(1)` option when the test is [instantiated](https://github.com/cockroachdb/cockroach/blob/38dd16aac9b0b1e167c9ec6d16ccaf30789be25a/pkg/cmd/roachtest/tests/versionupgrade.go#L103-L106).

Jira issue: CRDB-35765

**Comment by rickystewart** [comment]
> Constrain this build to only acceptance tests.

FYI: I've already done this in the new [script](https://github.com/cockroachdb/cockroach/blob/391b57fa806abe9d655c786712d6e8ea388c9b3a/build/github/local-roachtest.sh#L38) for the GitHub Actions build. I did not do anything else on this work item including this part: "the set of tests should be selected not by a name pattern, as currently done, but by a roachtest suite". I also did not propagate the change back to TC.
