### ISSUE TITLE
jobs: break up pts management poller

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#118512]
The job system contains an[ internal poller ](https://github.com/cockroachdb/cockroach/blob/master/pkg/jobs/metricspoller/job_statistics.go#L100)that scans and cancels active jobs which contain a pts that is older than a specified limit. We discovered in a[ support ticket](https://github.com/cockroachlabs/support/issues/2805) that the poller uses a single txn to scan over much of the job table, pts table, and job info table and also cancel any job (i.e. update the job table) with a pts  that is too old. This long running txn is prone to conflicting with other txns that touch the same key space. In this support ticket, we observed this txn being perpetually pushed, causing deadlock on the job system. To fix, we ought break this txn into much smaller txns, perhaps one for each job.

Jira issue: CRDB-35764

**Comment by stevendanna** [comment]
I wonder how bad this transaction would have been if not in the presence of the other bugs we found in that support ticket.  However, it still seems prudent to restructure this so that we aren't involving so many keys related to different jobs in the same transaction.

**Comment by msbutler** [comment]
closing, as https://github.com/cockroachdb/cockroach/pull/118979 has merged
