### ISSUE TITLE
db-console: option to sort metric chart by node value 

### ISSUE THREAD

**Issue by kvoli** [cockroachdb/cockroach#118645]
**Is your feature request related to a problem? Please describe.**

In large clusters it is difficult to discern the node associated with a series in metric charts. In many cases there are outliers on specific metrics such as latency. Identifying which node corresponds to which series quickly is useful.

e.g. finding the highest valued nodes here is a non-trivial endeavor:

![image](https://github.com/cockroachdb/cockroach/assets/39606633/e6239523-d086-4b66-93b7-eab1e35a53eb)

**Describe the solution you'd like**

Add the ability to sort console timeseries metric chart legends by value.

**Describe alternatives you've considered**

Alternatively, a hover/click on a specific line could reveal that node's ID.

Jira issue: CRDB-35820

Epic CRDB-37557

**Comment by RaduBerinde** [comment]
Would it be possible to look at this soon? It might be an easy win.

**Comment by dhartunian** [comment]
@kvoli @RaduBerinde can y'all take a look at https://github.com/cockroachdb/cockroach/pull/127786 and let me know if that helps with this problem? Sorting the legend is a bit more involved so just wondering if the hover feature can do the job here.

**Comment by RaduBerinde** [comment]
The hover feature is great, as is the isolation of a single graph. Yes, I would say that addresses this problem.

**Comment by kvoli** [comment]
Looks good to me, it appears much easier to find the node you're looking for.
