### ISSUE TITLE
SQL Shell does not show failed transaction

### ISSUE THREAD

**Issue by smcvey** [cockroachdb/cockroach#118776]
**Describe the problem**

The Cockroach Cloud SQL Shell tool doesn't report a failed transaction correctly.  Instead, it shows "Successful" when it should not.

**To Reproduce**

Consider these commands on the regular `cockroach sql` client which attempts to drop the primary key constraint:

```
CREATE TABLE t(id UUID PRIMARY KEY, other_id UUID NOT NULL);

BEGIN;
ALTER TABLE t DROP CONSTRAINT t_pkey; -- Will initially show as success
COMMIT; -- At this point you receive an error message because of the attempted removal of the primary index.
```

On the SQL Shell:

```
CREATE TABLE t(id UUID PRIMARY KEY, other_id UUID NOT NULL);
```

```
ALTER TABLE t DROP CONSTRAINT t_pkey; 
```

The above shows as Successful, but it actually has failed behind the scenes.

<img width="1507" alt="Screenshot 2024-02-05 at 19 29 55" src="https://github.com/cockroachdb/cockroach/assets/28270695/64b18a3e-7a95-4677-8fdf-347097fb5298">

**Expected behavior**
A failed transaction should be clearly highlighted.

**Environment:**
 - CockroachDB version: 23.1.14 Serverless

**Additional context**
Causes confusion to the user.

Jira issue: CRDB-35899

Jira issue: CRDB-41872

**Comment by jordanlewis** [comment]
@smcvey closing this in favor of a new internal ticket I've tagged you on.
