### ISSUE TITLE
Stores tab shows -2 as IntentCount

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#1189]
http://i.imgur.com/RtPv1yT.png

it only happens on the second node during the Put test, which has a lot of other problems (#1163, #1185) so this may just be fallout of more general problems.

**Comment by tschottdorf** [comment]
cc @mrtracy

**Comment by tschottdorf** [comment]
I should mention that this seems to happen consistently on my linux laptop, and I can't observe #1185. So everything runs smoothly, it's really only the intent count which baselines at -2 instead of 0, only on the second node.

**Comment by BramGruneir** [comment]
What are we looking at for here?  The -2 intent count?


On Thu, May 28, 2015 at 9:33 PM, Tobias Schottdorf <notifications@github.com

**Comment by tschottdorf** [comment]
Uhm, yeah, I thought the title kind of gave that away. ;)

**Comment by BramGruneir** [comment]
That's what I get for not reading the title of the email.  Strange. 
Can you check the responses from the query in the debugging network tab?  See if it is returning -2s?

**Comment by tschottdorf** [comment]
Yeah, it's returned in the JSON.

**Comment by BramGruneir** [comment]
well ok then, it's an error in time series then.  Matt can investigate when he gets back from vacation.

**Comment by MBerhault** [comment]
oh yeah. oops, that was a dup.
Anyway, here's the query/response:
Request:
```
{"start_nanos":1433180591905000000,"end_nanos":1433181191905000000,"queries":[{"name":"cr.store.intentcount.3","aggregator":1}]}
```
Response:
```
{
  "results": [
    {
      "name": "cr.store.intentcount.3",
      "sources": [
        ""
      ],
      "aggregator": 1,
      "datapoints": [
        {
          "timestamp_nanos": 1433180825000000000,
          "value": -1
        },
        {
          "timestamp_nanos": 1433180835000000000,
          "value": -1
        },
        {
          "timestamp_nanos": 1433180845000000000,
          "value": -1
        },
        {
          "timestamp_nanos": 1433180855000000000,
          "value": -1
        },
etc...
```

**Comment by tschottdorf** [comment]
I'm close to resolving this.
