### ISSUE TITLE
kvclient: add new DistSender metrics

### ISSUE THREAD

**Issue by arulajmani** [cockroachdb/cockroach#118926]
**Describe the problem**

@andrewbaptist and I spoke about this on a call earlier today. We should add new DistSender metrics for:

- The number of replicas that we sent RPCs to in `sendToReplicas`
- The number of meta2 lookups performed by the DistSender

Jira issue: CRDB-35958

**Comment by andrewbaptist** [comment]
Looking more into this, I think we already have these two metrics today

`TransportSent = distsender.rpc.sent`
`RangeLookups = distsender.rangelookups`

Closing as already implemented.
