### ISSUE TITLE
Cannot delete ambiguous indexes

### ISSUE THREAD

**Issue by avgupta456** [cockroachdb/cockroach#119069]
**Describe the problem**

If there are two indexes on two tables with the same name, running `DROP INDEX {index_name}` does not work and returns the error `ERROR: index name "{index_name}" is ambiguous (found in  {table1} and {table2})`. There doesn't appear to be a way to ever delete these indexes once created.

**To Reproduce**

Create two indexes on different tables with the exact same name. Try deleting one or both of them.

**Expected behavior**

There should be a way to specify the schema and table to delete a specific index.

**Environment:**
 - Client version: CockroachDB CCL v23.1.13 (aarch64-apple-darwin21.2, built 2023/12/01 22:05:49, go1.19.13)
 - Server version: CockroachDB CCL v23.1.14 (x86_64-pc-linux-gnu, built 2024/01/16 12:37:52, go1.19.13)

Jira issue: CRDB-36020

**Comment by fqazi** [comment]
Use the alternate syntax documented at: https://www.cockroachlabs.com/docs/stable/drop-index. This is DROP INDEX <tableName>@<indexName>.
