### ISSUE TITLE
roachprod: add load balancer support

### ISSUE THREAD

**Issue by herkolategan** [cockroachdb/cockroach#119009]
With the addition of [1] we can now utilise load balancers (on GCP), by pointing the load balancer backend towards the MIGs of a cluster. Load balancers also have health monitoring capabilities. These can be set to monitor the SQL / TCP ports of a cockroach cluster to detect when a node is no longer available.

The ability to set up a load balancer should come after a service is available on the cluster. By service we refer to a SQL process is running on the cluster and listening on a given port. The service could either be for a tenant, or the host cluster. It makes sense to only add a load balancer after we have some services, as we need to specify which ports the load balancer will manage.

The load balancer should have a specific name format that includes the target service and cluster. This will make it easier to clean up the corresponding resources as well as identify what the load balancer is serving.

Finally, setting up load balancers on Google Cloud creates a few resources: health checks, backend services, and proxies
These resources will have to be cleaned up either when a cluster is destroyed, no matter the state of the cluster.

[1] https://github.com/cockroachdb/cockroach/issues/118207

Epic: [CRDB-33832](https://cockroachlabs.atlassian.net/browse/CRDB-33832)

Jira issue: CRDB-35988

**Comment by renatolabs** [comment]
@herkolategan should we close this issue?
