### ISSUE TITLE
ui: obtain redacted statement diagnostics bundles from the DB console

### ISSUE THREAD

**Issue by michae2** [cockroachdb/cockroach#119040]
In 23.1 we added the ability to collect redacted statement diagnostics bundles using `EXPLAIN ANALYZE (DEBUG, REDACT)` which was tracked by https://github.com/cockroachdb/cockroach/issues/68570 and https://github.com/cockroachdb/cockroach/issues/98817.

In order to make collection of these redacted bundles easier, we should add a redaction option to the DB console's existing UI for bundle collection.

We should probably also add a redaction option to `crdb_internal.request_statement_bundle()`.

Jira issue: CRDB-35994

Epic CRDB-37557

**Comment by michae2** [comment]
In 23.1 we also added:
- redacted query plans using `EXPLAIN (REDACT)`
- redacted create statements using `SHOW CREATE ... WITH REDACT`

Maybe these should also be exposed through the DB console somehow?

**Comment by yuzefovich** [comment]
#123859 made all the necessary changes to the backend (added new overloads to `crdb_internal.request_statement_bundle` builtin as well as extended the server API). The remaining work is left on the frontend side of things will be tackled by the Observability team (currently planned for second half of the year), so I'm removing this from the Queries board.
