### ISSUE TITLE
sql: deadlock on crdb_internal.leases when allow_role_memberships_to_change_during_transaction is enabled

### ISSUE THREAD

**Issue by annrpom** [cockroachdb/cockroach#119253]
We added a session variable, `allow_role_memberships_to_change_during_transaction` that can be used to make the granting and revoking of role memberships faster (#98370).  Unfortunately, we run into a footgun with this setting on when querying an internal `leases` table. In short, the issue is that we try to drop a lease that we hold a lock to.

To reproduce:

```
demo@127.0.0.1:26257/movr> SET allow_role_memberships_to_change_during_transaction = true;
SET

Time: 0ms total (execution 0ms / network 0ms)

demo@127.0.0.1:26257/movr> SELECT * FROM crdb_internal.leases; 
```

And observe hanging - along with followed connections to this node not being able to connect.
N.B. connecting as admin (root, node) will not reproduce this issue - since the auth check short-circuits.

As @fqazi explained further:

So, the crdb_internal.lease will hold the following locks:

```
=> Lease manager
  => Descriptor
      => Descriptor Version
```

As a part of visiting leases we run an authorization check, which with that setting will attempt to release the lease on `system.role_members`, which will need a lock on that descriptor inside the lease manger. 

Jira issue: CRDB-36114

Epic CRDB-35306

**Comment by annrpom** [comment]
We have seen this occur with https://github.com/cockroachlabs/support/issues/2824

**Comment by fqazi** [comment]
Leaving open until the backports get merged

**Comment by fqazi** [comment]
Backports are all merged
