### ISSUE TITLE
kvserver: account for replica rangefeed cpu load

### ISSUE THREAD

**Issue by kvoli** [cockroachdb/cockroach#119390]
A rangefeed is associated with a replica has associated scheduler overhead. This issue is to account for the rangefeed CPU usage per replica.

The solution should include the CPU usage in the raft cpu usage (renaming to a more appropriate replica usage), or introduce a new CPU counter:

https://github.com/cockroachdb/cockroach/blob/7214f530055b267ee65b2b4fb65885f0ee584d9e/pkg/kv/kvserver/load/record_replica_load.go#L47

Jira issue: CRDB-36179

Epic CRDB-37617

**Comment by nicktrav** [comment]
Merging into #106146.
