### ISSUE TITLE
o11y: error 53200 when querying jobs table on DRT cluster

### ISSUE THREAD

**Issue by ajstorm** [cockroachdb/cockroach#119384]
On node 4 of the DRT cluster, we're currently unable to query the jobs table:

![image](https://github.com/cockroachdb/cockroach/assets/18447034/d9b02b55-6578-46ee-8028-8fb5eaba07b2)

In the logs we see

```
W240220 13:38:07.531620 386241686 sql/crdb_internal.go:1189 ⋮ [T3,Vapplication,client-tenant=‹3›,n4,intExec=‹admin-jobs›] 299597  error closing an iterator: ‹crdb-internal-jobs-table›: ‹system-jobs-scan›: scan with start key /Tenant/3/Table/53/1: root: memory budget exceeded: 10240 bytes requested, 7991296000 currently allocated, 7991304192 bytes in budget
W240220 13:38:07.531620 386241686 sql/crdb_internal.go:1189 ⋮ [T3,Vapplication,client-tenant=‹3›,n4,intExec=‹admin-jobs›] 299597 +HINT: ‹Consider increasing --max-sql-memory startup parameter.›
E240220 13:38:07.536326 386241593 server/admin.go:2291 ⋮ [T3,Vapplication,client-tenant=‹3›,n4] 299598  ‹admin-jobs›: ‹crdb-internal-jobs-table›: ‹system-jobs-scan›: scan with start key /Tenant/3/Table/53/1: root: memory budget exceeded: 10240 bytes requested, 7991296000 currently allocated, 7991304192 bytes in budget
```

The table can be queried successfully from the sql shell.

I've saved off the logs on node 4 so they don't get overwritten (`cockroach.cct-232-0004.ubuntu.2024-02-20T13_03_18Z.1639320.log.saved`)

Jira issue: CRDB-36175

**Comment by ajstorm** [comment]
There were 3 nodes down on the cluster at the time.  Now that those nodes are back up, the page renders successfully.  Would the above behaviour be expected in a cluster which is partially down?  What's odd is that I was able to query the table directly when the cluster was partially down.

**Comment by yuzefovich** [comment]
This has also been discussed on [slack](https://cockroachlabs.slack.com/archives/C063CP41TG9/p1708437151838229). I agree with Steven that at this point we don't have profiles, logs, etc to say definitively what was using SQL memory, but the error seems expected given that some operation used up 7GiB of RAM on one node.

What would have helped is if we had `memmonitoring` profiler enabled in the application tenant. Currently we disable all "runtime stats" profilers in shared-process config, and it makes sense for all proper "runtime stats", but the memory accounting profiler dumps the state of SQL accounting system, so we only get system tenant's view which is insufficient. (This profiler was added recently in #114275.)
