### ISSUE TITLE
obs: export metrics about non-GC-related stop-the-world pauses

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#119319]
We are in the process of integrating the new [`runtime/metrics`](https://pkg.go.dev/runtime/metrics) package into CockroachDB's metrics in https://github.com/cockroachdb/cockroach/pull/118875, as part of addressing https://github.com/cockroachdb/cockroach/issues/88178.

Once the PR has merged, we should hook into some of the other metrics exposed by `runtime/metrics`.

One interesting set of metrics which we don't currently export though other means is non-GC-related stop-the-world pauses. This includes stop-the-world pauses due to goroutine profiles (with `debug=2`), calls to `runtime.ReadMemStats`, and others.

Specifically, we should export the following four metrics:
```
/sched/pauses/stopping/gc:seconds
/sched/pauses/stopping/other:seconds
/sched/pauses/total/gc:seconds
/sched/pauses/total/other:seconds
```

The two "gc" metrics here can replace existing metrics powered by `debug.ReadGCStats`. The two "other" metrics here will be new.

We should then expose them on the **Runtime** dashboard.

cc. @srosenberg @lyang24 

Jira issue: CRDB-36145

Epic CRDB-37617

**Comment by nvanbenschoten** [comment]
These metrics were only [exported in Go 1.22](https://tip.golang.org/doc/go1.22), so we'll need to wait for the upgrade to that Go version. It should happen before CRDB v24.1.

**Comment by shralex** [comment]
@lyang24 please consider taking this one once the upgrade to Go 1.22 is completes. Please feel free to decline if you're too busy with other stuff! https://github.com/cockroachdb/cockroach/pull/118873

**Comment by nvanbenschoten** [comment]
From @lyang24 on Slack:
> for the 4 metrics mentioned in the ticket are float64historams do we want to represtent them as time per percentiles? or we can do an estimated total.

I think estimated totals (expressed in nanoseconds) make sense, like you are doing for `/sched/pauses/total/gc:seconds` in https://github.com/cockroachdb/cockroach/pull/122463.
