### ISSUE TITLE
failed node liveness heartbeat: operation "node liveness heartbeat" timed out after 4.5s

### ISSUE THREAD

**Issue by chenqunjian** [cockroachdb/cockroach#119354]
**Describe the problem**

failed node liveness heartbeat: operation "node liveness heartbeat" timed out after 4.5s

**To Reproduce**

**Additional data / screenshots**
failed node liveness heartbeat: operation "node liveness heartbeat" timed out after 4.5s

Please submit this message at

  https://github.com/cockroachdb/cockroach/issues/new/choose

along with

	https://yourhost:8080/#/reports/range/410980

and the following Raft status: {"id":"3","term":21465,"vote":"1","commit":883643,"lead":"0","raftState":"StatePreCandidate","applied":883643,"progress":{},"leadtransferee":"0"}
W240219 07:27:00.091088 163 gossip/gossip.go:1499  [n1] first range unavailable; resolvers exhausted
W240219 07:27:00.382314 6664 server/node.go:880  [n1,summaries] health alerts detected: {Alerts:[{StoreID:0 Category:METRICS Description:liveness.heartbeatfailures Value:1 XXX_NoUnkeyedLiteral:{} XXX_sizecache:0} {StoreID:1 Category:METRICS Description:ranges.underreplicated Value:67 XXX_NoUnkeyedLiteral:{} XXX_sizecache:0} {StoreID:1 Category:METRICS Description:requests.slow.lease Value:2 XXX_NoUnkeyedLiteral:{} XXX_sizecache:0} {StoreID:1 Category:METRICS Description:requests.slow.raft Value:2 XXX_NoUnkeyedLiteral:{} XXX_sizecache:0}] XXX_NoUnkeyedLiteral:{} XXX_sizecache:0}
I240219 07:27:00.448335 14360 internal/client/txn.go:618  [n1] async rollback failed: aborted during DistSender.Send: context deadline exceeded
I240219 07:27:01.948385 6669 storage/node_liveness.go:775  [n1,hb] retrying liveness update after storage.errRetryLiveness: result is ambiguous (context done during DistSender.Send: context deadline exceeded)
W240219 07:27:01.948413 6669 storage/node_liveness.go:523  [n1,hb] slow heartbeat took 4.5s
W240219 07:27:01.948448 6669 storage/node_liveness.go:463  [n1,hb] failed node liveness heartbeat: operation "node liveness heartbeat" timed out after 4.5s
I240219 07:27:03.972859 6662 server/status/runtime.go:500  [n1] runtime stats: 1.1 GiB RSS, 616 goroutines, 451 MiB/121 MiB/682 MiB GO alloc/idle/total, 432 MiB/562 MiB CGO alloc/total, 3213.6 CGO/sec, 206.4/23.4 %(u/s)time, 0.0 %gc (2x), 1.9 MiB/9.1 MiB (r/w)net
I240219 07:27:04.949172 14465 internal/client/txn.go:618  [n1] async rollback failed: aborted during DistSender.Send: context deadline exceeded
I240219 07:27:06.448804 6669 storage/node_liveness.go:775  [n1,hb] retrying liveness update after storage.errRetryLiveness: result is ambiguous (context done during DistSender.Send: context deadline exceeded)
W240219 07:27:06.448830 6669 storage/node_liveness.go:523  [n1,hb] slow heartbeat took 4.5s
W240219 07:27:06.448842 6669 storage/node_liveness.go:463  [n1,hb] failed node liveness heartbeat: operation "node liveness heartbeat" timed out after 4.5s
I240219 07:27:09.449358 14676 internal/client/txn.go:618  [n1] async rollback failed: aborted during DistSender.Send: context deadline exceeded
I240219 07:27:10.949331 6669 storage/node_liveness.go:775  [n1,hb] retrying liveness update after storage.errRetryLiveness: result is ambiguous (context done during DistSender.Send: context deadline exceeded)
W240219 07:27:10.949353 6669 storage/node_liveness.go:523  [n1,hb] slow heartbeat took 4.5s
W240219 07:27:10.949370 6669 storage/node_liveness.go:463  [n1,hb] failed node liveness heartbeat: operation "node liveness heartbeat" timed out after 4.5s
W240219 07:27:13.644536 167 storage/closedts/provider/provider.go:156  [ct-closer] unable to move closed timestamp forward: not live
W240219 07:27:13.821995 6466 storage/replica_range_lease.go:982  [n1,s1,r2/1:/System/NodeLiveness{-Max}] have been waiting 1m0s attempting to acquire lease
W240219 07:27:13.823304 13701 storage/replica_write.go:199  [n1,s1,r2/1:/System/NodeLiveness{-Max}] have been waiting 60.00s for proposing command RequestLease [/System/NodeLiveness,/Min).
This range is likely unavailable.
Please submit this message at

  https://github.com/cockroachdb/cockroach/issues/new/choose

along with

	https://yourhost:8080/#/reports/range/2

**Environment:**
 - CockroachDB version [v19.1.3]
 - Server OS: [e.g. Linux/Distrib]
 - Client app [e.g. `cockroach sql`, JDBC, ...]

**Additional context**
What was the impact?

Jira issue: CRDB-36165

**Comment by erikgrinaker** [comment]
Hi @chenqunjian.

This looks like either the node is partitioned away from the rest of the cluster, or some ranges in the cluster have lost quorum since not enough nodes are available. Please make sure all nodes are running and that the network between them works.

I'm afraid we can't offer operational support via GitHub, but you can find other support resources here: https://www.cockroachlabs.com/docs/stable/support-resources

>CockroachDB version [v19.1.3]

I'll add this version has been unsupported since 2021. We currently offer assistance support for versions 22.2 and later. We recommend you upgrade to a newer version once the problem has been resolved.
