### ISSUE TITLE
changefeedccl: set or defend `registered.schema.after` for all envelope types

### ISSUE THREAD

**Issue by rharding6373** [cockroachdb/cockroach#119428]
In the avro encoder, we sometimes use `registered.schema.after` without checking for nil, leading to a node panic. This is only set when using the `wrapped` envelope type. For other envelope types, we should either set this or audit the code to defensively check for nil values before using `after`.

More context in https://github.com/cockroachlabs/support/issues/2833

Jira issue: CRDB-36193

**Comment by wenyihu6** [comment]
Do we want to backport the fix to 22.2? The customer seems to be using 22.2 in https://github.com/cockroachlabs/support/issues/2833.

**Comment by andyyang890** [comment]
22.2 is past its maintenance window so probably not. See https://www.cockroachlabs.com/docs/releases/release-support-policy
