### ISSUE TITLE
catalog/lease: counting leases leads to full table scans

### ISSUE THREAD

**Issue by fqazi** [cockroachdb/cockroach#119456]
Previously, the WaitForOneVersions / WaitForNoVersion queries would only do a primary index scan to confirm that the old version of descriptors were gone. In 23.1 we made the system.leases table regional by row, which meant that allow rows are now prefixed with a region, causing these queries to turn into full table scans. In the single region case we can eliminate this regression by always requesting the default primary region during the scans and restore the original performance.

Jira issue: CRDB-36208

**Comment by fqazi** [comment]
Merged: https://github.com/cockroachdb/cockroach/pull/119464 and https://github.com/cockroachdb/cockroach/pull/119466

**Comment by Arivijay** [comment]
Hi @fqazi,
In which release will this fix will be available?

**Comment by fqazi** [comment]
Should be available in the following up coming releases: 23.2.3 and 23.1.17
