### ISSUE TITLE
storage: TestMVCCStatsRandomized fails on latest master

### ISSUE THREAD

**Issue by lyang24** [cockroachdb/cockroach#119409]
**Describe the problem**

TestMVCCStatsRandomized fails on master with a specific random seed with diff in GCBytesAge.

   --- FAIL: TestMVCCStatsRandomized/userspace/inline=false (0.01s)

Expected :enginepb.MVCCStats{ContainsEstimates:0, LastUpdateNanos:288013817178, LockAge:0, GCBytesAge:0, LiveBytes:0, LiveCount:0, KeyBytes:0, KeyCount:0, ValBytes:0, ValCount:0, IntentBytes:0, IntentCount:0, LockBytes:0, LockCount:0, RangeKeyCount:1, RangeKey ...

Actual   :enginepb.MVCCStats{ContainsEstimates:0, LastUpdateNanos:288013817178, LockAge:0, GCBytesAge:-143, LiveBytes:0, LiveCount:0, KeyBytes:0, KeyCount:0, ValBytes:0, ValCount:0, IntentBytes:0, IntentCount:0, LockBytes:0, LockCount:0, RangeKeyCount:1, Range ...

**To Reproduce**

https://github.com/lyang24/cockroach/blob/6540aa6d400cf27a4ac869dbf1c756face253c8f/pkg/storage/mvcc_stats_test.go#L2213
changes the seed to `-5510781042947318778` to repo

**Expected behavior**
test to pass

**Environment:**
 - CockroachDB version lastest master

Jira issue: CRDB-36181

**Comment by erikgrinaker** [comment]
Thanks! Looks like an issue with a GC request.

```
    mvcc_stats_test.go:1886: 287.995550338,1 GC txn=<none>
        	284.439941738,0
        	stats delta: {ContainsEstimates:0 LastUpdateNanos:0 LockAge:0 GCBytesAge:101897 LiveBytes:0 LiveCount:0 KeyBytes:-52 KeyCount:-1 ValBytes:-349 ValCount:-4 IntentBytes:0 IntentCount:0 LockBytes:0 LockCount:0 RangeKeyCount:0 RangeKeyBytes:0 RangeValCount:0 RangeValBytes:0 SysBytes:0 SysCount:0 AbortSpanBytes:0}
        absolute: {ContainsEstimates:0 LastUpdateNanos:0 LockAge:0 GCBytesAge:-5903 LiveBytes:0 LiveCount:0 KeyBytes:0 KeyCount:0 ValBytes:0 ValCount:0 IntentBytes:0 IntentCount:0 LockBytes:0 LockCount:0 RangeKeyCount:1 RangeKeyBytes:20 RangeValCount:1 RangeValBytes:0 SysBytes:0 SysCount:0 AbortSpanBytes:0}
    mvcc_stats_test.go:1889: 
        	Error Trace:	github.com/cockroachdb/cockroach/pkg/storage/mvcc_stats_test.go:79
        	            				github.com/cockroachdb/cockroach/pkg/storage/mvcc_stats_test.go:1889
        	            				github.com/cockroachdb/cockroach/pkg/storage/mvcc_stats_test.go:2241
        	            				github.com/cockroachdb/cockroach/pkg/testutils/subtest.go:28
        	Error:      	Not equal: 
        	            	expected: enginepb.MVCCStats{ContainsEstimates:0, LastUpdateNanos:288013817178, LockAge:0, GCBytesAge:0, LiveBytes:0, LiveCount:0, KeyBytes:0, KeyCount:0, ValBytes:0, ValCount:0, IntentBytes:0, IntentCount:0, LockBytes:0, LockCount:0, RangeKeyCount:1, RangeKeyBytes:20, RangeValCount:1, RangeValBytes:0, SysBytes:0, SysCount:0, AbortSpanBytes:0}
        	            	actual  : enginepb.MVCCStats{ContainsEstimates:0, LastUpdateNanos:288013817178, LockAge:0, GCBytesAge:-143, LiveBytes:0, LiveCount:0, KeyBytes:0, KeyCount:0, ValBytes:0, ValCount:0, IntentBytes:0, IntentCount:0, LockBytes:0, LockCount:0, RangeKeyCount:1, RangeKeyBytes:20, RangeValCount:1, RangeValBytes:0, SysBytes:0, SysCount:0, AbortSpanBytes:0}
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -4,3 +4,3 @@
        	            	  LockAge: (int64) 0,
        	            	- GCBytesAge: (int64) 0,
        	            	+ GCBytesAge: (int64) -143,
        	            	  LiveBytes: (int64) 0,
```

**Comment by pav-kv** [comment]
The first commit on which this test fails at this rand seed is 2ce4ebf0. The commit, however, modifies the test, so the fact that the test does not fail on the same seed at the commit before it, does not strongly indicate that this commit broke this test - it might be that this seed just generates a different test.

@miraradeva Do you have an intuition here whether the commit could have broken the test?
