### ISSUE TITLE
backupccl: consider a more lenient retry policy for backup

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#119691]
Similar to recent [improvements](https://github.com/cockroachdb/cockroach/pull/118982) to restore, we should consider modifying backup's retry policy to:
1) retry all backup processor errors if the backup processor has made progress
2) reset to retry counter if the distsql flow has made progress

Hopefully, this would avoid backup failures on what seem to be ephemeral errors that aren't in our retryable errors whitelist. E.g. https://github.com/cockroachdb/cockroach/issues/119617

Jira issue: CRDB-36285

**Comment by lyang24** [comment]
Hi @msbutler, This issues looks interesting may i take an attempt at this one?

From last pr the restore job store determine progress by comparing `resumer.job.Progress().Details.(*jobspb.Progress_Restore).Restore.Checkpoint`. I wonder how to do the same thing to backups - the backup progress struct in jobs.pb is empty.

**Comment by msbutler** [comment]
@lyang24 go for it!

**Comment by lyang24** [comment]
Thanks! Is it a good idea to determine backup progress by comparing prev and current `backupManifest.EntryCounts` from manifest files? cc @msbutler
