### ISSUE TITLE
roachprod: add VM label for "spot" instance

### ISSUE THREAD

**Issue by srosenberg** [cockroachdb/cockroach#119629]
To facilitate tracking (billing) spend and preemption frequency of "spot" instances, we should add a VM label. Staying consistent with the current labeling scheme where boolean-valued labels are added iff the value is `true`, it should suffice to add `spot: true`. Below is a snapshot of current VM labels in GCE; same labels are also used with other clouds (AWS and Azure).

<img width="1007" alt="VM_labels" src="https://github.com/cockroachdb/cockroach/assets/1616764/3ecdca4b-c04a-4871-a7d6-2de0b9439bb4">

<br>
<br>

**NOTE**: let's also update `PrintDetails` in [`cluster_cloud.go`](https://github.com/cockroachdb/cockroach/blob/c9c3cc5f3c3a4a6ab556f4b9d5b6ec0381901bdb/pkg/roachprod/cloud/cluster_cloud.go#L159) to append the `spot` column, when relevant. To make it easier to `grep`, we can elide the column if the cluster isn't using spot instances.

Jira issue: CRDB-36220

**Comment by nameisbhaskar** [comment]
For the second requirement, I will use the “spot” keyword in the column for easy grep. The column value will be populated only if it is a spot instance.
