### ISSUE TITLE
sql: improve output table of SHOW GRANTS

### ISSUE THREAD

**Issue by fabiog1901** [cockroachdb/cockroach#119775]
The output table of command `SHOW GRANTS` lists object in a hierarchical fashion: `database_name`, `schema_name`, `relation_name`. 

Recently however, we have introduced 3 more object types - `TYPE`, `FUNCTION`, `EXTERNAL CONNECTION` - and these are listed under the `relation_name` column, which is slightly incorrect.

This FR to request a review of the output table and consider maybe using a `object_type` and `object_name` to identify the object as a UDF, TYPE or TABLE.

[slack](https://cockroachlabs.slack.com/archives/C0168LW5THS/p1709134204416699)

Jira issue: CRDB-36306

Epic CRDB-37763

**Comment by zyf123123** [comment]
Should we modify 
```database_name  schema_name  table_name  grantee   privilege_type  is_grantable```
into 
```database_name  schema_name  object_name  object_type  grantee   privilege_type  is_grantable```
or something else? I think many logictest format need to modify
