### ISSUE TITLE
sql: SHOW TYPES only shows ENUM types, not composite types

### ISSUE THREAD

**Issue by fabiog1901** [cockroachdb/cockroach#119734]
The command `SHOW TYPES` only shows ENUM types, not composite types:

```
root@localhost:26257/defaultdb> CREATE TYPE IF NOT EXISTS my_point AS (x INT, y INT);                                                                                  
CREATE TYPE

Time: 138ms total (execution 138ms / network 0ms)

root@localhost:26257/defaultdb> show types;                                                                                                                            
SHOW TYPES 0

Time: 34ms total (execution 34ms / network 0ms)

root@localhost:26257/defaultdb> CREATE TYPE weekend AS ENUM ('sunday', 'saturday');                                                                                    
CREATE TYPE

Time: 98ms total (execution 97ms / network 0ms)

root@localhost:26257/defaultdb> show types;                                                                                                                            
  schema |  name   | owner
---------+---------+--------
  public | weekend | root
(1 row)
```

[slack](https://cockroachlabs.slack.com/archives/C0168LW5THS/p1709138092182219)

---

To resolve this, we need to update the delegate query for `SHOW TYPES` here: https://github.com/cockroachdb/cockroach/blob/8e5f8913a01bb897ee0b4275ef8c4680ff68d179/pkg/sql/delegate/show_types.go#L21-L31

Rather than just delegate to `SHOW ENUMS`, let's try starting with [the query](https://github.com/cockroachdb/cockroach/blob/8e5f8913a01bb897ee0b4275ef8c4680ff68d179/pkg/sql/delegate/show_enums.go#L43) used in `SHOW ENUMS`, and modify it so that composite types are included too.

Use the pg_catalog documentation to see what changes to the query are needed. It looks like we'll need to change the filter on `pg_type.typtype` to include composite types: https://www.postgresql.org/docs/current/catalog-pg-type.html

Jira issue: CRDB-36293

Epic CRDB-37763

**Comment by rimadeodhar** [comment]
We need to expand this delegated query to return composite types here https://github.com/cockroachdb/cockroach/blob/306298c993e4bfbd8ee0cd38fc84264c1ee0d11c/pkg/sql/delegate/show_types.go#L22.
