### ISSUE TITLE
stmtbundle: fully specify inverted index definition

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#119788]
When attempting to recreate the bundle from [here](https://github.com/cockroachlabs/support/issues/2846#issue-2161547699) (after having adjusted `env.sql` to go around #119786), we run into
```
ERROR: data type text has no default operator class for access method "gin"
SQLSTATE: 42704
HINT: You must specify an operator class for the index (did you mean gin_trgm_ops?)
Failed running "debug statement-bundle recreate"
```
The fix is to include `gin_trgm_ops` into the definition of the INVERTED INDEXes. We should change `schema.sql` to already contain this.

Jira issue: CRDB-36315

**Comment by michae2** [comment]
I think this is a dupe of #109201
