### ISSUE TITLE
roachprod: replace Provider "unimplemented" panics

### ISSUE THREAD

**Issue by herkolategan** [cockroachdb/cockroach#119857]
Currently `roachprod` providers will panic when an unimplemented method is called, for a feature the provider does not support. This is generally not a problem when using `roachprod` from the CLI. But it does present a problem in `roachtest` which could fail a whole suite if a test is accidentally or suite/CI setup is accidentally utilising something that is not implemented for the provider.

The suggestion here is that we update the panics to rather be errors, so that the test suite can continue running and only the affected test is interrupted.

Jira issue: CRDB-36355

**Comment by srosenberg** [comment]
Is this a hypothetical scenario, or did you encounter one of these panics in a `roachtest`?

**Comment by renatolabs** [comment]
> Is this a hypothetical scenario, or did you encounter one of these panics in a `roachtest`?

I believe this was created from the discussion on #119382, so it's hypothetical. I figured we have been adding more GCE-specific logic recently, and if a mistake happens and we attempt to call one of these unsupported methods on a different cloud, it's better to fail cluster creation than to halt the entire run.

Low priority improvement.
