### ISSUE TITLE
Sentry: panic.go:884: runtime error: slice bounds out of range [:97116000] with capacity 18 (1) attached stack trace   -- stack trace:   | runtime.gopanic   | 	GOROOT/src/runtime/panic.go:884   | runt...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#119834]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5029050082/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5029050082/?referrer=webhooks_plugin)

Panic Message:

```
panic.go:884: runtime error: slice bounds out of range [:97116000] with capacity 18
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | runtime.goPanicSliceAcap
  | 	GOROOT/src/runtime/panic.go:139
  | github.com/cockroachdb/pebble.(*levelIter).SeekPrefixGE
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/level_iter.go:799
  | github.com/cockroachdb/pebble.(*mergingIter).seekGE
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go:1044
  | github.com/cockroachdb/pebble.(*mergingIter).SeekPrefixGE
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go:1120
  | github.com/cockroachdb/pebble.(*lazyCombinedIter).SeekPrefixGE
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/range_keys.go:565
  | github.com/cockroachdb/pebble.(*Iterator).SeekPrefixGE
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/iterator.go:1412
  | github.com/cockroachdb/cockroach/pkg/storage.(*pebbleIterator).SeekGE
  | 	github.com/cockroachdb/cockroach/pkg/storage/pebble_iterator.go:333
  | github.com/cockroachdb/cockroach/pkg/storage.(*pebbleMVCCScanner).get
  | 	github.com/cockroachdb/cockroach/pkg/storage/pebble_mvcc_scanner.go:559
  | github.com/cockroachdb/cockroach/pkg/storage.mvccGetWithValueHeader
  | 	github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:1158
  | github.com/cockroachdb/cockroach/pkg/storage.MVCCGetWithValueHeader
  | 	github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:1083
  | github.com/cockroachdb/cockroach/pkg/storage.MVCCGet
  | 	github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:1053
  | github.com/cockroachdb/cockroach/pkg/storage.MVCCGetProto
  | 	github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:816
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/logstore.StateLoader.LoadRaftTruncatedState
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/logstore/stateloader.go:91
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/stateloader.StateLoader.Load
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/stateloader/stateloader.go:88
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/kvstorage.Replica.Load
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/kvstorage/init.go:346
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).Start
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store.go:1991
  | github.com/cockroachdb/cockroach/pkg/server.(*Node).start
  | 	github.com/cockroachdb/cockroach/pkg/server/node.go:528
  | github.com/cockroachdb/cockroach/pkg/server.(*Server).PreStart
  | 	github.com/cockroachdb/cockroach/pkg/server/server.go:1726
  | github.com/cockroachdb/cockroach/pkg/cli.createAndStartServerAsync.func1.2
  | 	github.com/cockroachdb/cockroach/pkg/cli/start.go:819
  | github.com/cockroachdb/cockroach/pkg/cli.createAndStartServerAsync.func1
  | 	github.com/cockroachdb/cockroach/pkg/cli/start.go:867
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (2) runtime error: slice bounds out of range [:97116000] with capacity 18
Error types: (1) *withstack.withStack (2) runtime.boundsError
-- report composition:
runtime.boundsError
panic.go:884: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/cli/start.go#L866-L868](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/cli/start.go#L866-L868)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/cli/start.go#L818-L820](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/cli/start.go#L818-L820)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/server/server.go#L1725-L1727](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/server/server.go#L1725-L1727)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/server/node.go#L527-L529](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/server/node.go#L527-L529)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/kv/kvserver/pkg/kv/kvserver/store.go#L1990-L1992](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/kv/kvserver/pkg/kv/kvserver/store.go#L1990-L1992)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/kv/kvserver/kvstorage/init.go#L345-L347](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/kv/kvserver/kvstorage/init.go#L345-L347)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/kv/kvserver/stateloader/stateloader.go#L87-L89](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/kv/kvserver/stateloader/stateloader.go#L87-L89)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/kv/kvserver/logstore/stateloader.go#L90-L92](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/kv/kvserver/logstore/stateloader.go#L90-L92)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/storage/mvcc.go#L815-L817](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/storage/mvcc.go#L815-L817)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/storage/mvcc.go#L1052-L1054](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/storage/mvcc.go#L1052-L1054)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/storage/mvcc.go#L1082-L1084](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/storage/mvcc.go#L1082-L1084)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/storage/mvcc.go#L1157-L1159](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/storage/mvcc.go#L1157-L1159)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/storage/pebble_mvcc_scanner.go#L558-L560](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/storage/pebble_mvcc_scanner.go#L558-L560)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/storage/pebble_iterator.go#L332-L334](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/storage/pebble_iterator.go#L332-L334)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/iterator.go#L1411-L1413](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/iterator.go#L1411-L1413)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/range_keys.go#L564-L566](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/range_keys.go#L564-L566)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go#L1119-L1121](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go#L1119-L1121)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go#L1043-L1045](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go#L1043-L1045)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/level_iter.go#L798-L800](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/level_iter.go#L798-L800)
[GOROOT/src/runtime/panic.go#L138-L140](GOROOT/src/runtime/panic.go#L138-L140)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/cli/start.go in pkg/cli.createAndStartServerAsync.func1 at line 867
pkg/cli/start.go in pkg/cli.createAndStartServerAsync.func1.2 at line 819
pkg/server/server.go in pkg/server.(*Server).PreStart at line 1726
pkg/server/node.go in pkg/server.(*Node).start at line 528
pkg/kv/kvserver/pkg/kv/kvserver/store.go in pkg/kv/kvserver.(*Store).Start at line 1991
pkg/kv/kvserver/kvstorage/init.go in pkg/kv/kvserver/kvstorage.Replica.Load at line 346
pkg/kv/kvserver/stateloader/stateloader.go in pkg/kv/kvserver/stateloader.StateLoader.Load at line 88
pkg/kv/kvserver/logstore/stateloader.go in pkg/kv/kvserver/logstore.StateLoader.LoadRaftTruncatedState at line 91
pkg/storage/mvcc.go in pkg/storage.MVCCGetProto at line 816
pkg/storage/mvcc.go in pkg/storage.MVCCGet at line 1053
pkg/storage/mvcc.go in pkg/storage.MVCCGetWithValueHeader at line 1083
pkg/storage/mvcc.go in pkg/storage.mvccGetWithValueHeader at line 1158
pkg/storage/pebble_mvcc_scanner.go in pkg/storage.(*pebbleMVCCScanner).get at line 559
pkg/storage/pebble_iterator.go in pkg/storage.(*pebbleIterator).SeekGE at line 333
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/iterator.go in github.com/cockroachdb/pebble.(*Iterator).SeekPrefixGE at line 1412
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/range_keys.go in github.com/cockroachdb/pebble.(*lazyCombinedIter).SeekPrefixGE at line 565
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go in github.com/cockroachdb/pebble.(*mergingIter).SeekPrefixGE at line 1120
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go in github.com/cockroachdb/pebble.(*mergingIter).seekGE at line 1044
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/level_iter.go in github.com/cockroachdb/pebble.(*levelIter).SeekPrefixGE at line 799
GOROOT/src/runtime/panic.go in runtime.goPanicSliceAcap at line 139
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
```

### Tags

| Tag | Value |
| --- | --- |
| Command | start-single-node |
| Environment | v23.1.13 |
| Go Version | go1.19.13 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.13 |
| Cockroach SHA | 8d065df26e25a762a1abbbf2b1e475456b341a00 |
| # of CPUs | 12 |
| # of Goroutines | 150 |

Jira issue: CRDB-36338

**Comment by yuzefovich** [comment]
unactionable
