### ISSUE TITLE
util/log: allow `file-permissions` field in log config to set "other" file permissions

### ISSUE THREAD

**Issue by xinhaoz** [cockroachdb/cockroach#119888]
The umask for a cockroachdb process is set to be `00007` to disallow `other` file permissions from being readable/writable on creation. This makes sense for most configurations. However, we introduced the `file-permissions` log config field that should allow users to set other permissions. This is currently broken due to using `OpenFile` to create the log files, which always applies the umask after. We can simply apply the desired permissions after creating the file with something like `chmod`.

See:
https://github.com/cockroachdb/cockroach/blob/1629e11a6101cabf5feb3364cc8c2b51c8f8791b/pkg/util/log/file.go#L319

As a part of this ticket, any log config code currently using `644` as a default should use `640` as the default so that the change above does not default log files to world readable.

Jira issue: CRDB-36368

Epic CRDB-21266

**Comment by abarganier** [comment]
@cockroachdb/security we'd like to get an opinion on this approach - to respect the `file-permissions` log config parameter literally (and apply it directly via `os.Chmod` when creating the files), which means ignoring the umask.

**Comment by bdarnell** [comment]
I think if the user explicitly asks for a file with permissions that exceed the umask, we should give them what they ask for. The umask is a default, not a limit. (The alternative of asking any user who wants to have some log files that are other-readable to modify their umask is clearly risky since other files could end up other-readable by default)

**Comment by abarganier** [comment]
Thanks for the input @bdarnell - sounds like applying the permissions literally via `os.Chmod` is the right approach. The Observability team will make the fix.
