### ISSUE TITLE
changefeedccl: allow individual changefeed jobs to configure filtering 

### ISSUE THREAD

**Issue by andyyang890** [cockroachdb/cockroach#119891]
In 23.2, changefeeds would unconditionally filter out events that originated from a session that had the `disable_changefeed_replication` session variable set or row-level TTL deletes if the `sql.ttl.changefeed_replication.disabled` cluster setting was set.

In 24.1, we want to allow changefeeds to individually configure whether they will respect the filtering settings (i.e. a changefeed can be configured to ignore the session variable/cluster setting and emit events for all changes).

Jira issue: CRDB-36370

Epic CRDB-34240

**Comment by data-matt** [comment]
Hey @andyyang890, could this be backported to 23.2? thanks

**Comment by andyyang890** [comment]
Hey @data-matt, I believe we deliberately chose to not backport this to 23.2 because we did not want to add a new changefeed option mid-release. If there's a pressing need to backport this, would you mind starting a Slack discussion in `#cdc` so that we can discuss it with the rest of the team?
