### ISSUE TITLE
storage: test coalesced heartbeat failure during raft leader replica GC

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#11988]
#11985 fixed an issue where a store would send a coalesced heartbeat and store a slice of remote replica IDs which are unreachable according to the raft transport, then one of that store's heartbeat-sending replicas (i.e. a raft leader) would be removed by the replica GC queue, and then the store would attempt to retrieve the raft leader replica from the replicas map (in order to report the unreachable replicas to it) and crash, since the replica had been removed.

#11985 stopped short of testing this, but we should add a test (especially considering how light the testing of failed coalesced heartbeats already is). Here's a rough cut of such a test:
```go
// TestReportUnreachableRemoveRace adds and removes the raft leader replica
// repeatedly while one of its peers is unreachable in an attempt to expose
// races (primarily in asynchronous coalesced heartbeats).
func TestReportUnreachableRemoveRace(t *testing.T) {
	defer leaktest.AfterTest(t)()
	mtc := startMultiTestContext(t, 3)
	defer mtc.Stop()

	const rangeID = roachpb.RangeID(1)
	mtc.replicateRange(rangeID, 1, 2)

	for i := 0; i < 1; i++ {
		for idx, store := range mtc.stores {
			repl, err := store.GetReplica(rangeID)
			if err != nil {
				t.Fatal(err)
			}
			if repl.RaftStatus().SoftState.RaftState == raft.StateLeader {
				for _, toStore := range mtc.stores {
					if toStore == store {
						continue
					}
					log.Infof(repl.AnnotateCtx(context.TODO()), "leader=%s follower=%s", store, toStore)
					cb := mtc.transport.GetCircuitBreaker(toStore.Ident.NodeID)
					cb.Break()
					mtc.unreplicateRange(rangeID, idx)
					cb.Reset()
					mtc.replicateRange(rangeID, idx)
					break
				}
			}
		}
	}
}
```

**Comment by dianasaur323** [comment]
@tamird I'm assuming we haven't added this yet - let's do something for this in Q3 2017?

**Comment by cuongdo** [comment]
assigning to @petermattis for 1.1 triage

**Comment by petermattis** [comment]
@tamird Can you take another whack at making the test work and/or close this issue? Seems hard to tickle the problematic code, so perhaps a bit of restructuring is in order to extract the notification of unreachable remote replicas into something that is directly callable.
