### ISSUE TITLE
backupccl/console: don't report estimated time remaining if progress is less than <5%

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#119873]
If backup progress is less than 5%, the estimated time remaining reported in the db console is bogus. We shouldn't display it in this case. More specifically, we ought to implement the following policy: 

- If we have >5% progress off of which to make an educated guess, and that guess is a minute or more, show the exact estimate.
- If we our guess is less than a minute, say "a minute or less" rather than some "exact" number of seconds, since these guesses just aren't that precise and end up looking "wrong" more than write if we claim they are.
- If we have <5% progress, we don't know enough to make a guess yet; just show the percentage and bar for now.

Jira issue: CRDB-36365

**Comment by sbshah97** [comment]
Hi I'm a new contributor, is this something I can take up ?

**Comment by msbutler** [comment]
@sbshah97 apologies, we're going to take this one. thanks for you interest in contributing!
