### ISSUE TITLE
SQL: Expression-based Indexes Not Used When Expected.

### ISSUE THREAD

**Issue by gmcquillan** [cockroachdb/cockroach#119849]
**Describe the problem**

Our data is not case sensitive. So in our Postgres Envrionment we have an expression-based index to compare the UPPER(colVal) with whatever input we have (which we also run though UPPER. e.g.:

```sql
SELECT id FROM my_schema.my_table WHERE upper(my_table.domain) = upper('00007707c6a9493cbbf6705e14cc12ba.com');
```
We get a response in about 10-20 seconds with about 7GB of data in this table across 13 CRDB nodes.:

```
    id
-----------
  8715438
(1 row)

Time: 12.630s total (execution 12.459s / network 0.171s)
```

Whereas, an exact match on the same data takes 3ms. 

```
SELECT id FROM my_schema.my_table WHERE subscriptions.domain = '00007707c6a9493cbbf6705e14cc12ba.com';                                                          
    id
-----------
  8715438
(1 row)

Time: 174ms total (execution 3ms / network 171ms)
```

In Postgres, these queries would be similarly fast, as the planner will see that the `UPPER` function is being applied to a column that has an expression-based index, and it'd just compare the value of `UPPER(input)` to data in that index.

```
mydb=# \timing
Timing is on.
mydb=# SELECT id FROM  my_schema.my_table  WHERE upper(my_table.domain) = upper('00007707c6a9493cbbf6705e14cc12ba.com'); 
   id    
---------
 8715438
(1 row)

Time: 0.452 ms
```

Here's what Postgres' `EXPLAIN ANALYZE` looks like for this query (same data):
```
cert=# EXPLAIN ANALYZE SELECT id FROM my_schema.my_table  WHERE upper(my_table.domain) = upper('00007707c6a9493cbbf6705e14cc12ba.com'); 
                                                           QUERY PLAN                                                            
---------------------------------------------------------------------------------------------------------------------------------
 Index Scan using upper_case_domain on my_table  (cost=0.55..8.57 rows=1 width=4) (actual time=0.066..0.067 rows=1 loops=1)
   Index Cond: (upper((domain)::text) = '00007707C6A9493CBBF6705E14CC12BA.COM'::text)
 Planning Time: 0.117 ms
 Execution Time: 0.087 ms
(4 rows)
```

Compare with the plan:

```
EXPLAIN (verbose) SELECT id FROM my_schema.my_table WHERE upper(my_table.domain) = upper('00007707c6a9493cbbf6705e14cc12ba.com');                   
                                                                    info
--------------------------------------------------------------------------------------------------------------------------------------------
  distribution: full
  vectorized: true

  • project
  │ columns: (id)
  │
  └── • filter
      │ columns: (id, domain)
      │ estimated row count: 237,051
      │ filter: upper(domain) = '00007707C6A9493CBBF6705E14CC12BA.COM'
      │
      └── • scan
            columns: (id, domain)
            estimated row count: 711,154 (100% of the table; stats collected 39 minutes ago; using stats forecast for 1 day in the future)
            table: my_Table@subscriptions_domain_key
            spans: FULL SCAN
(16 rows)

Time: 199ms total (execution 2ms / network 197ms)
```

With CRDB, we seem to be skipping that index during planning, and doing a full table scan and running UPPER on every single `domain` column in the entire table. Compared with Postgres this is a *27,686x performance decrease* (for precisely the same corpus of dat). Most other queries are fine for this cluster, but it seems like these queries where there is an expression in the index definition mean that the index is ignored.

However, even if we force our query to use this index, we still result in a full tablescan:

```
gmcquillan@10.164.0.106:26257/cert> EXPLAIN (verbose) SELECT id FROM cert_subscription_service.subscriptions@upper_case_domain WHERE upper(cert_subscription_service.subscriptions.domain) = upper('00007707c6a9493cbbf6705e14cc12ba.com'); 
                                                                      info
------------------------------------------------------------------------------------------------------------------------------------------------
  distribution: local
  vectorized: true

  • project
  │ columns: (id)
  │
  └── • filter
      │ columns: (id, domain)
      │ estimated row count: 237,051
      │ filter: upper(domain) = '00007707C6A9493CBBF6705E14CC12BA.COM'
      │
      └── • index join
          │ columns: (id, domain)
          │ estimated row count: 711,154
          │ table: subscriptions@subscriptions_id_pk
          │ key columns: id
          │
          └── • scan
                columns: (id)
                estimated row count: 711,154 (100% of the table; stats collected 47 minutes ago; using stats forecast for 1 day in the future)
                table: subscriptions@upper_case_domain
                spans: FULL SCAN
(22 rows)

Time: 171ms total (execution 2ms / network 169ms)
```

Notice we have an extra step of jointing against our index -- but the resulting plan still yields a table scan (which is what we cannot understand -- and why we're filing this ticket).

See the execution performance (essentially the same):

```
SELECT id FROM my_schema.my_table@upper_case_domain WHERE upper(my_table.domain) = upper('00007707c6a9493cbbf6705e14cc12ba.com');                   
    id
-----------
  8715438
(1 row)

Time: 14.212s total (execution 14.040s / network 0.172s)
```

**To Reproduce**

1. Create the table with the index definitions:
```CREATE TABLE my_schema.my_table (
  id INT8 NOT NULL DEFAULT nextval('my_schema.my_table'::REGCLASS),
  domain VARCHAR NOT NULL,
  CONSTRAINT my_table_id_pk PRIMARY KEY (id ASC),
  UNIQUE INDEX my_table_domain_key (domain ASC),
  INDEX upper_case_domain (upper(domain::STRING) ASC),
)
```
2. Fill it with enough data that we should be confident that our planner should never select table scans.
3. Observe queries such as:
```
 SELECT id FROM my_schema.my_table WHERE upper(my_table.domain) = upper('00007707c6a9493cbbf6705e14cc12ba.com'); 
```
4. Confirm that  `EXPLAIN (VERBOSE) SELECT id FROM my_schema.my_table WHERE upper(my_table.domain) = upper('00007707c6a9493cbbf6705e14cc12ba.com'); ` still yields a table scan.
5. Compare with sub-millisecond performance in Postgres.

**Expected behavior**
We expect that expression indexes are used to by-pass Table scans.

**Environment:**
 - CockroachDB version [e.g. 2.0.x]:  v23.1.11
 - Server OS: [e.g. Linux/Distrib]: mixed -  CentOS7/Google Container Optimized Linux
 - Client app [e.g. `cockroach sql`, JDBC, ...]: JDBC, and `cockroach sql`

**Additional context**
Eventually, a small, but steady stream of these queries started to overwhelm nodes and created instability in the cluster. To the tune of maybe 1-2 QPS, we started seeing nodes die. We're investigating spending more time on limiting the amount of RAM that the CRDB processes will be using, but this query should not be generating so much work, so this is why we're filing this ticket.

Obviously, having a sequential int id is not ideal for CRDB, but this is a system being migrated as-is from a production Postgres installation. At the moment, it's not possible to change the IDs to be randomly generated.

For now, we're going to explore in parallel if we can avoid the case insensitivity query, but this seems like a feature that everybody should want to work correctly in CRDB.

We're also going to schedule an upgrade. It looks like we're a couple of months behind, but we don't see anything in the release notes that include changes to indexes that *look* like would change this behavior for us. Please let us know if that is not the case.

Jira issue: CRDB-36350

**Comment by gmcquillan** [comment]
I also wonder if the root cause for this is the same as for #119831

**Comment by michae2** [comment]
Hi @gmcquillan, thanks for opening an issue. If the query is changed to have a cast, just like the expression index, is it able to use the index? I.e. does the following use the index?

```sql
SELECT id FROM my_schema.my_table WHERE upper(my_table.domain::STRING) = upper('00007707c6a9493cbbf6705e14cc12ba.com'::STRING); 
```

**Comment by gmcquillan** [comment]
@michae2, Yeah, that bring the execution back down to 3ms, which is the same as a straight index equality.

Here's our plan output:

```
EXPLAIN (VERBOSE) SELECT id FROM my_schema.my_table WHERE UPPER(my_schema.my_table.domain::STRING) = UPPER('00007707c6a9493cbbf6705e14cc12ba.com'::STRING);   
                                                               info
-----------------------------------------------------------------------------------------------------------------------------------
  distribution: local
  vectorized: true

  • scan
    columns: (id)
    estimated row count: 1 (<0.01% of the table; stats collected 29 minutes ago; using stats forecast for 19 hours in the future)
    table: my_table@upper_case_domain
    spans: /"00007707C6A9493CBBF6705E14CC12BA.COM"-/"00007707C6A9493CBBF6705E14CC12BA.COM"/PrefixEnd
(8 rows)

Time: 207ms total (execution 17ms / network 190ms)
```

**Comment by DrewKimball** [comment]
This is expected behavior, since the expression in the query must exactly match the index expression. Removing the cast from the index expression would cause the original example to work as expected.

**Comment by gmcquillan** [comment]
Fine to leave it closed to me. 

However, I'd argue that requiring explicit type casting to match an obvious data type that works fine in Postgres is a bug, but I've got everything I need to work around this.

**Comment by DrewKimball** [comment]
>However, I'd argue that requiring explicit type casting to match an obvious data type that works fine in Postgres is a bug, but I've got everything I need to work around this.

This is a good point. Here's a similar issue related to partial index expressions: https://github.com/cockroachdb/cockroach/issues/97961

Did your original Postgres schema include a cast as well? I'm asking because the `STRING` data type only exists in CRDB.
