### ISSUE TITLE
optbuilder: v23.1.3: nil pointer in buildUpdateCascadeMutationInput

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#119980]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5040650537/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5040650537/?referrer=webhooks_plugin)

Panic Message:

```
catch.go:29: while building cascade expression: runtime error: invalid memory address or nil pointer dereference
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder.(*cascadeBuilder).planCascade
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/cascades.go:271
  | [...repeated from below...]
Wraps: (2) while building cascade expression
Wraps: (3) assertion failure
Wraps: (4) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/util/errorutil.ShouldCatch
  | 	github.com/cockroachdb/cockroach/pkg/util/errorutil/catch.go:29
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.buildCascadeHelper.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/fk_cascade.go:899
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | runtime.panicmem
  | 	GOROOT/src/runtime/panic.go:260
  | runtime.sigpanic
  | 	GOROOT/src/runtime/signal_unix.go:835
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildUpdateCascadeMutationInput
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/fk_cascade.go:851
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*onUpdateCascadeBuilder).Build.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/fk_cascade.go:652
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.buildCascadeHelper
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/fk_cascade.go:907
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*onUpdateCascadeBuilder).Build
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/fk_cascade.go:641
  | github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder.(*cascadeBuilder).planCascade
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/cascades.go:259
  | github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder.(*cascadeBuilder).setupCascade.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/cascades.go:168
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunCascadesAndChecks
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1977
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1678
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2103
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1656
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:964
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:142
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2986
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:141
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2175
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2180
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2097
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:893
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:778
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (5) runtime error: invalid memory address or nil pointer dereference
  | -- cause hidden behind barrier
  | runtime error: invalid memory address or nil pointer dereference
  | (1) runtime error: invalid memory address or nil pointer dereference
  | Error types: (1) runtime.errorString
Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *assert.withAssertionFailure (4) *withstack.withStack (5) *barriers.barrierErr
-- report composition:
*barriers.barrierErr: masked error: runtime error: invalid memory address or nil pointer dereference
catch.go:29: *withstack.withStack (top exception)
*assert.withAssertionFailure
*errutil.withPrefix: while building cascade expression
cascades.go:271: *withstack.withStack (1)
(check the extra data payloads)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/pgwire/conn.go#L777-L779](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/pgwire/conn.go#L777-L779)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/conn_executor.go#L892-L894](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/conn_executor.go#L892-L894)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/conn_executor.go#L2096-L2098](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/conn_executor.go#L2096-L2098)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/conn_executor.go#L2179-L2181](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/conn_executor.go#L2179-L2181)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/conn_executor.go#L2174-L2176](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/conn_executor.go#L2174-L2176)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/conn_executor_exec.go#L140-L142](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/conn_executor_exec.go#L140-L142)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/conn_executor_exec.go#L2985-L2987](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/conn_executor_exec.go#L2985-L2987)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/conn_executor_exec.go#L141-L143](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/conn_executor_exec.go#L141-L143)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/conn_executor_exec.go#L963-L965](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/conn_executor_exec.go#L963-L965)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/conn_executor_exec.go#L1655-L1657](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/conn_executor_exec.go#L1655-L1657)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/conn_executor_exec.go#L2102-L2104](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/conn_executor_exec.go#L2102-L2104)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/distsql_running.go#L1677-L1679](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/distsql_running.go#L1677-L1679)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/distsql_running.go#L1976-L1978](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/distsql_running.go#L1976-L1978)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/opt/exec/execbuilder/cascades.go#L167-L169](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/opt/exec/execbuilder/cascades.go#L167-L169)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/opt/exec/execbuilder/cascades.go#L270-L272](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/opt/exec/execbuilder/cascades.go#L270-L272)
[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/pgwire/conn.go#L777-L779](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/pgwire/conn.go#L777-L779)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/conn_executor.go#L892-L894](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/conn_executor.go#L892-L894)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/conn_executor.go#L2096-L2098](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/conn_executor.go#L2096-L2098)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/conn_executor.go#L2179-L2181](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/conn_executor.go#L2179-L2181)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/conn_executor.go#L2174-L2176](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/conn_executor.go#L2174-L2176)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/conn_executor_exec.go#L140-L142](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/conn_executor_exec.go#L140-L142)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/conn_executor_exec.go#L2985-L2987](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/conn_executor_exec.go#L2985-L2987)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/conn_executor_exec.go#L141-L143](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/conn_executor_exec.go#L141-L143)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/conn_executor_exec.go#L963-L965](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/conn_executor_exec.go#L963-L965)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/conn_executor_exec.go#L1655-L1657](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/conn_executor_exec.go#L1655-L1657)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/conn_executor_exec.go#L2102-L2104](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/conn_executor_exec.go#L2102-L2104)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/distsql_running.go#L1677-L1679](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/distsql_running.go#L1677-L1679)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/distsql_running.go#L1976-L1978](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/distsql_running.go#L1976-L1978)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/opt/exec/execbuilder/cascades.go#L167-L169](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/opt/exec/execbuilder/cascades.go#L167-L169)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/opt/exec/execbuilder/cascades.go#L258-L260](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/opt/exec/execbuilder/cascades.go#L258-L260)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/opt/optbuilder/fk_cascade.go#L640-L642](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/opt/optbuilder/fk_cascade.go#L640-L642)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/opt/optbuilder/fk_cascade.go#L906-L908](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/opt/optbuilder/fk_cascade.go#L906-L908)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/opt/optbuilder/fk_cascade.go#L651-L653](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/opt/optbuilder/fk_cascade.go#L651-L653)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/opt/optbuilder/fk_cascade.go#L850-L852](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/opt/optbuilder/fk_cascade.go#L850-L852)
[GOROOT/src/runtime/signal_unix.go#L834-L836](GOROOT/src/runtime/signal_unix.go#L834-L836)
[GOROOT/src/runtime/panic.go#L259-L261](GOROOT/src/runtime/panic.go#L259-L261)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/opt/optbuilder/fk_cascade.go#L898-L900](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/sql/opt/optbuilder/fk_cascade.go#L898-L900)
[https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/util/errorutil/catch.go#L28-L30](https://github.com/cockroachdb/cockroach/blob/c663f843fa3e1a87855a18f9678291f35eeef394/pkg/util/errorutil/catch.go#L28-L30)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommandsAsync.func1 at line 778
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 893
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 2097
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 2180
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd.func1 at line 2175
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 141
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithProfiling at line 2986
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt.func1 at line 142
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 964
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchToExecutionEngine at line 1656
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithDistSQLEngine at line 2103
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRunAll at line 1678
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRunCascadesAndChecks at line 1977
pkg/sql/opt/exec/execbuilder/cascades.go in pkg/sql/opt/exec/execbuilder.(*cascadeBuilder).setupCascade.func1 at line 168
pkg/sql/opt/exec/execbuilder/cascades.go in pkg/sql/opt/exec/execbuilder.(*cascadeBuilder).planCascade at line 271
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommandsAsync.func1 at line 778
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 893
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 2097
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 2180
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd.func1 at line 2175
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 141
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithProfiling at line 2986
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt.func1 at line 142
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 964
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchToExecutionEngine at line 1656
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithDistSQLEngine at line 2103
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRunAll at line 1678
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRunCascadesAndChecks at line 1977
pkg/sql/opt/exec/execbuilder/cascades.go in pkg/sql/opt/exec/execbuilder.(*cascadeBuilder).setupCascade.func1 at line 168
pkg/sql/opt/exec/execbuilder/cascades.go in pkg/sql/opt/exec/execbuilder.(*cascadeBuilder).planCascade at line 259
pkg/sql/opt/optbuilder/fk_cascade.go in pkg/sql/opt/optbuilder.(*onUpdateCascadeBuilder).Build at line 641
pkg/sql/opt/optbuilder/fk_cascade.go in pkg/sql/opt/optbuilder.buildCascadeHelper at line 907
pkg/sql/opt/optbuilder/fk_cascade.go in pkg/sql/opt/optbuilder.(*onUpdateCascadeBuilder).Build.func1 at line 652
pkg/sql/opt/optbuilder/fk_cascade.go in pkg/sql/opt/optbuilder.(*Builder).buildUpdateCascadeMutationInput at line 851
GOROOT/src/runtime/signal_unix.go in runtime.sigpanic at line 835
GOROOT/src/runtime/panic.go in runtime.panicmem at line 260
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
pkg/sql/opt/optbuilder/fk_cascade.go in pkg/sql/opt/optbuilder.buildCascadeHelper.func1 at line 899
pkg/util/errorutil/catch.go in pkg/util/errorutil.ShouldCatch at line 29
```

### Tags

| Tag | Value |
| --- | --- |
| Command | start-single-node |
| Environment | v23.1.3 |
| Go Version | go1.19.4 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.3 |
| Cockroach SHA | c663f843fa3e1a87855a18f9678291f35eeef394 |
| # of CPUs | 4 |
| # of Goroutines | 545 |

Jira issue: CRDB-36423

**Comment by yuzefovich** [comment]
Let's closing this as unactionable too
