### ISSUE TITLE
backfill: v23.1.9: CREATE INDEX: validation of index × failed: expected 0 rows, found 4

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#119940]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5039443183/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5039443183/?referrer=webhooks_plugin)

Panic Message:

```
backfill.go:1745: executing declarative schema change PostCommitPhase stage 7 of 7 with 1 ValidationType op (rollback=false) for CREATE INDEX: validation of index × failed: expected 0 rows, found 4
(1)
  | (opaque error wrapper)
  | type name: github.com/cockroachdb/errors/withstack/*withstack.withStack
  | reportable 0:
  |
  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scerrors.EventLogger.HandlePanicAndLogError
  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scerrors/errors.go:81
  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scrun.executeStage
  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scrun/scrun.go:205
  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scrun.RunSchemaChangesInJob.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scrun/scrun.go:139
  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scdeps.(*jobExecutionDeps).WithTxnInJob.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scdeps/run_deps.go:144
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).DescsTxn.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1610
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).txn.func4
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1698
  | github.com/cockroachdb/cockroach/pkg/kv.runTxn.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:970
  | github.com/cockroachdb/cockroach/pkg/kv.(*Txn).exec
  | 	github.com/cockroachdb/cockroach/pkg/kv/txn.go:928
  | github.com/cockroachdb/cockroach/pkg/kv.runTxn
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:969
  | github.com/cockroachdb/cockroach/pkg/kv.(*DB).TxnWithAdmissionControl
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:932
  | github.com/cockroachdb/cockroach/pkg/kv.(*DB).Txn
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:907
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).txn
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1686
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).DescsTxn
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1608
  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scdeps.(*jobExecutionDeps).WithTxnInJob
  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scdeps/run_deps.go:109
  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scrun.RunSchemaChangesInJob
  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scrun/scrun.go:135
  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scjob.(*newSchemaChangeResumer).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scjob/job.go:114
  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scjob.(*newSchemaChangeResumer).Resume
  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scjob/job.go:45
  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine.func2
  | 	github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1628
  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine
  | 	github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1629
  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).runJob
  | 	github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:474
  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).resumeJob.func2
  | 	github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:388
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470
  | runtime.goexit
  | 	src/runtime/asm_arm64.s:1172
Wraps: (2) executing declarative schema change PostCommitPhase stage 7 of 7 with 1 ValidationType op (rollback=false) for CREATE INDEX
Wraps: (3) assertion failure
Wraps: (4)
  | (opaque error wrapper)
  | type name: github.com/cockroachdb/errors/withstack/*withstack.withStack
  | reportable 0:
  |
  | github.com/cockroachdb/cockroach/pkg/sql.ValidateInvertedIndexes.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/backfill.go:1745
  | github.com/cockroachdb/cockroach/pkg/util/ctxgroup.Group.GoCtx.func1
  | 	github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:168
  | golang.org/x/sync/errgroup.(*Group).Go.func1
  | 	golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:75
  | runtime.goexit
  | 	src/runtime/asm_arm64.s:1172
Wraps: (5) validation of index × failed: expected 0 rows, found 4
Error types: (1) *errbase.opaqueWrapper (2) *errutil.withPrefix (3) *assert.withAssertionFailure (4) *errbase.opaqueWrapper (5) *errutil.leafError
-- report composition:
*errutil.leafError: validation of index × failed: expected 0 rows, found 4
backfill.go:1745: *withstack.withStack (top exception)
*assert.withAssertionFailure
*errutil.withPrefix: executing declarative schema change PostCommitPhase stage 7 of 7 with 1 ValidationType op (rollback=false) for CREATE INDEX
errors.go:81: *withstack.withStack (1)
(check the extra data payloads)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_arm64.s#L1171-L1173](src/runtime/asm_arm64.s#L1171-L1173)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/util/stop/stopper.go#L469-L471](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/util/stop/stopper.go#L469-L471)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/jobs/adopt.go#L387-L389](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/jobs/adopt.go#L387-L389)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/jobs/adopt.go#L473-L475](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/jobs/adopt.go#L473-L475)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/jobs/registry.go#L1628-L1630](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/jobs/registry.go#L1628-L1630)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/jobs/registry.go#L1627-L1629](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/jobs/registry.go#L1627-L1629)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/schemachanger/scjob/job.go#L44-L46](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/schemachanger/scjob/job.go#L44-L46)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/schemachanger/scjob/job.go#L113-L115](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/schemachanger/scjob/job.go#L113-L115)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/schemachanger/scrun/scrun.go#L134-L136](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/schemachanger/scrun/scrun.go#L134-L136)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/schemachanger/scdeps/run_deps.go#L108-L110](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/schemachanger/scdeps/run_deps.go#L108-L110)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/internal.go#L1607-L1609](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/internal.go#L1607-L1609)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/internal.go#L1685-L1687](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/internal.go#L1685-L1687)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/kv/db.go#L906-L908](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/kv/db.go#L906-L908)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/kv/db.go#L931-L933](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/kv/db.go#L931-L933)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/kv/db.go#L968-L970](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/kv/db.go#L968-L970)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/kv/txn.go#L927-L929](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/kv/txn.go#L927-L929)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/kv/db.go#L969-L971](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/kv/db.go#L969-L971)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/internal.go#L1697-L1699](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/internal.go#L1697-L1699)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/internal.go#L1609-L1611](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/internal.go#L1609-L1611)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/schemachanger/scdeps/run_deps.go#L143-L145](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/schemachanger/scdeps/run_deps.go#L143-L145)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/schemachanger/scrun/scrun.go#L138-L140](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/schemachanger/scrun/scrun.go#L138-L140)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/schemachanger/scrun/scrun.go#L204-L206](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/schemachanger/scrun/scrun.go#L204-L206)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/schemachanger/scerrors/errors.go#L80-L82](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/schemachanger/scerrors/errors.go#L80-L82)
[src/runtime/asm_arm64.s#L1171-L1173](src/runtime/asm_arm64.s#L1171-L1173)
[golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go#L74-L76](golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go#L74-L76)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/util/ctxgroup/ctxgroup.go#L167-L169](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/util/ctxgroup/ctxgroup.go#L167-L169)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/backfill.go#L1744-L1746](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/backfill.go#L1744-L1746)
</details>

```
src/runtime/asm_arm64.s in runtime.goexit at line 1172
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 470
pkg/jobs/adopt.go in pkg/jobs.(*Registry).resumeJob.func2 at line 388
pkg/jobs/adopt.go in pkg/jobs.(*Registry).runJob at line 474
pkg/jobs/registry.go in pkg/jobs.(*Registry).stepThroughStateMachine at line 1629
pkg/jobs/registry.go in pkg/jobs.(*Registry).stepThroughStateMachine.func2 at line 1628
pkg/sql/schemachanger/scjob/job.go in pkg/sql/schemachanger/scjob.(*newSchemaChangeResumer).Resume at line 45
pkg/sql/schemachanger/scjob/job.go in pkg/sql/schemachanger/scjob.(*newSchemaChangeResumer).run at line 114
pkg/sql/schemachanger/scrun/scrun.go in pkg/sql/schemachanger/scrun.RunSchemaChangesInJob at line 135
pkg/sql/schemachanger/scdeps/run_deps.go in pkg/sql/schemachanger/scdeps.(*jobExecutionDeps).WithTxnInJob at line 109
pkg/sql/internal.go in pkg/sql.(*InternalDB).DescsTxn at line 1608
pkg/sql/internal.go in pkg/sql.(*InternalDB).txn at line 1686
pkg/kv/db.go in pkg/kv.(*DB).Txn at line 907
pkg/kv/db.go in pkg/kv.(*DB).TxnWithAdmissionControl at line 932
pkg/kv/db.go in pkg/kv.runTxn at line 969
pkg/kv/txn.go in pkg/kv.(*Txn).exec at line 928
pkg/kv/db.go in pkg/kv.runTxn.func1 at line 970
pkg/sql/internal.go in pkg/sql.(*InternalDB).txn.func4 at line 1698
pkg/sql/internal.go in pkg/sql.(*InternalDB).DescsTxn.func1 at line 1610
pkg/sql/schemachanger/scdeps/run_deps.go in pkg/sql/schemachanger/scdeps.(*jobExecutionDeps).WithTxnInJob.func1 at line 144
pkg/sql/schemachanger/scrun/scrun.go in pkg/sql/schemachanger/scrun.RunSchemaChangesInJob.func1 at line 139
pkg/sql/schemachanger/scrun/scrun.go in pkg/sql/schemachanger/scrun.executeStage at line 205
pkg/sql/schemachanger/scerrors/errors.go in pkg/sql/schemachanger/scerrors.EventLogger.HandlePanicAndLogError at line 81
src/runtime/asm_arm64.s in runtime.goexit at line 1172
golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go in golang.org/x/sync/errgroup.(*Group).Go.func1 at line 75
pkg/util/ctxgroup/ctxgroup.go in pkg/util/ctxgroup.Group.GoCtx.func1 at line 168
pkg/sql/backfill.go in pkg/sql.ValidateInvertedIndexes.func2 at line 1745
```

### Tags

| Tag | Value |
| --- | --- |
| Command | start-single-node |
| Environment | v23.1.9 |
| Go Version | go1.19.10 |
| Platform | darwin arm64 |
| Distribution | CCL |
| Cockroach Release | v23.1.9 |
| Cockroach SHA | 28b2e767986169df857f5f2cd1790d71ac633395 |
| # of CPUs | 10 |
| # of Goroutines | 445 |

Jira issue: CRDB-36403

**Comment by rafiss** [comment]
Closing since we don't have a way to investigate this without a repro. It looks like this was not a production cluster, since the command is `start-single-node`.
