### ISSUE TITLE
identity_map matching of certificate names doesn't work

### ISSUE THREAD

**Issue by mohan-crdb** [cockroachdb/cockroach#120034]
**Describe the problem**

identity_map matching of certificate names doesn't work

error:-
```
failed to validate certificate 0 in file client.rdr1t_user.crt: client certificate has principals ["S31VSZkcS194MXYPQWD4MVbqLlbY+c/fkeka/qAdSSb9wmvjUdiPjWAgp8IFUsE|"], expected "rdr1t_user"
```

**Observation/Investigation:**

We suggested to use HBA and identity map configurations for authenticating to CockroachDB using a certificate with CN that does not match the SQL user as this is preferable over the `--cert-principal-map` flag that can be passed to cockroach start since it can be configured via a cluster setting and does not need a process restart.

To set this up, we followed the below steps:
 
- [CN] Common name from certificate
- [SQL user] SQL username in CRDB
 
Steps:

1. Create SQL user
2. Create certificate
3. Get CN from certificate
4. Set identity map and host-based authentication variables, both are required (note: CN must be all lower-case):
```
SET CLUSTER SETTING server.identity_map.configuration='
crdb [CN|lower] [SQL user]
';
 
SET CLUSTER SETTING server.host_based_authentication.configuration='
hostssl all [CN|lower] all cert map=crdb
';
```
5. Make sure to provider the username and path to the correct certificate in the connection string, e.g., `cockroach sql --url "postgres://[url-encoded CN]@[CRDB_HOST]:26257?sslcert=[url-encoded path to client .crt]&sslkey=[url-encoded path to .key]&sslmode=verify-full&sslrootcert=[url-encoded path to ca.crt]"`

After testing we found out that it works on 22.2 but it doesn't work on 23.1.x

The issue seems to have been introduced in [this PR](https://github.com/cockroachdb/cockroach/issues/93637) which first appeared in 23.1. It changed the way that system identities (e.g., those provided via the Common Name in the TLS certificate) get mapped to SQL users. Previously, there was a 1:1 mapping between system identity and SQL user. However, in the Postgresql identity maps, a system identity can be mapped to multiple SQL users and vice versa. This change was intended to fix that behavior to allow many-to-many mappings

We identified that there are several tests introduced to cover this scenario. However, those tests inject the system identity rather than read it from the certificate. This is test-only code that passes but when using an actual certificate this fails.

**To Reproduce**

Please refer to to internal request: https://github.com/cockroachlabs/support/issues/2858 for more information

**Related issue:** 
- https://github.com/cockroachdb/cockroach/issues/93637
- https://cockroachlabs.atlassian.net/browse/CRDB-22446

**Expected behavior**
identity_map matching of certificate names should work

**Additional data / screenshots**
n/a

**Environment:**
 - CockroachDB version 23.1.11

**Additional context**
What was the impact?

Please refer to to internal request: https://github.com/cockroachlabs/support/issues/2858 for more information

Jira issue: CRDB-36427

Jira issue: CRDB-36439

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[20249](https://cockroachdb.zendesk.com/agent/tickets/20249) has been linked to this issue.

**Comment by inata4** [comment]
@yecs1999 can you please take a look at this escalation?
Thanks!
