### ISSUE TITLE
storage: add metric for stuck/wedged operations

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#12001]
During processing of a request, there are several places an operation can either block for a long period of time or retry excessively. We should add a handful of metrics to instrument those places to catch operations that are taking longer than some threshold value (e.g. `60s`). Some examples of places to instrument: waiting in the command queue, waiting trying to acquire the lease, waiting for Raft to process a request, and waiting at the `DistSender` for an RPC to return. I'm thinking of the corresponding metrics as being part of a group: `requests.wedged.{commandqueue,lease,raft,distsender}`.

See #12000.

Cc @cockroachdb/stability

**Comment by petermattis** [comment]
@tamird Can you write up your suggestion for how to generalize this to all operations?

**Comment by tamird** [comment]
I think the best we can do is a metric for the total time spent in the command queue. We'd have to poll the command queue and mark each command with a last-polled time, with a final poll when the command exits the command queue. We'll need a count of total commands through the command queue as well to normalize this metric against load.

Or something like that.

**Comment by petermattis** [comment]
That sounds both a lot more complex and not as targeted as the metrics I'm proposing.
