### ISSUE TITLE
storage: consider using range keys for MVCCDeleteRangeUsingPredicate 

### ISSUE THREAD

**Issue by itsbilal** [cockroachdb/cockroach#120061]
Currently, MVCCDeleteRangeUsingPredicate (used for import rollbacks) only uses range keys for long runs of deleted keys that match the predicate. The predicate is usually whether keys fall within a given timestamp range, or match an import epoch in the value header. If we can move the predicate into the range key's value, we can greatly speed up range key rollback at the expense of slower reads due to the lack of range key masking.

As part of this issue, we'd need to update MVCC read paths to check for predicated range keys, and also update MVCCDeleteRangeUsingPredicate to write those range keys. Pebble-side changes are out of scope for this issue.

Jira issue: CRDB-36456

**Comment by jbowens** [comment]
> slower reads due to the lack of range key masking.

When a significant volume is deleted, reads will be _significantly_ slower. At first glance it seems like reads would be too slow to make this approach viable?

**Comment by itsbilal** [comment]
Closing as this was already considered but the performance and complexity cost to readers is too high to make the lack of range-key masking worthwhile.
