### ISSUE TITLE
teamcity: failed tests: acceptance/TestNodeRestart

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#12015]
Found here:
https://teamcity.cockroachdb.com/viewQueued.html?itemId=80621

Lots of ` grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:33130: getsockopt: connection refused"; Reconnecting to {"127.0.0.1:33130" <nil>}`
As if the docker networking was broken.

**Comment by tamird** [comment]
This seems to be happening pretty often.

**Comment by knz** [comment]
First investigation steps show that the error is not happening in the node containers but rather in the Docker client library ran by the cluster code in `acceptance/cluster/localcluster.go`. 

It seems to be that `ContainerKill` becomes confused. Now investigating further.

**Comment by a-robinson** [comment]
@knz are you still looking into this or do you need backup?

**Comment by knz** [comment]
yeah backup here would be welcome. I'm staring at this code and I'm not even sure what I'm looking at.
(My analysis so far: The chaos monkey for that test uses Kill on the container and then at the end of the test when the code in localcluster.go tries to Kill it again it gets wedged. Not sure why though.)

**Comment by tamird** [comment]
The actual failure:
```
--- FAIL: acceptance (proposer evaluated kv)/TestNodeRestart (15.342s)
	cluster.go:77: failed to send RPC: rpc error: code = 14 desc = grpc: the connection is unavailable

```

If I had to guess, the downed node is returning a "connection refused", which is being treated as non-temporary by GRPC, and we just need a retry loop in the caller to `cluster.Consistent`.
