### ISSUE TITLE
storage: crossversion metamorphic test failure [pebble#3386]

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/cockroach#120185]
cockroachdb/pebble#3386

Jira issue: CRDB-36533

**Comment by jbowens** [comment]
The above failure was actually while running the `crl-release-21.2` test binary with a clean store. It's uncertain whether later releases or master are affected by the same issue, whatever it is.

**Comment by itsbilal** [comment]
Closing as this was found to be isolated to 21.2. See discussion in https://github.com/cockroachdb/pebble/issues/3386
