### ISSUE TITLE
sql: create cache for virtual tables

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#12025]
Now that OID typecasts (#11717) need to do a virtual table lookup to succeed, we should be caching the virtual table contents to prevent wasted computation.

**Comment by nvanbenschoten** [comment]
Closing as https://github.com/cockroachdb/cockroach/pull/21609 got us 80% of the way towards eliminating all redundant computation and https://github.com/cockroachdb/cockroach/issues/22504 should make up the rest of the work here.
