### ISSUE TITLE
storage,allocator,online-restore?: node rebalanced to zero replicas, reporting 95% full

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#120217]
I haven't dug into this yet. This cluster ran an online restore of a tenant, using copy compactions. I paused the job as some nodes approached running out of disk due to #120182, to wait to see if compactions/rebalancing fixed it. After several hours I noticed n7 was still marked as 95% full, but had 0 replicas on it?

<img width="1609" alt="Screenshot 2024-03-11 at 11 22 00 AM" src="https://github.com/cockroachdb/cockroach/assets/15615/e805b438-0ff3-4e3f-8c50-f94771a6e270">

It seems possible the inputs to allocation decisions are incorrect in the face of external files, but I would have expected them to be removed during the rebalance, so perhaps we're leaking SSTs?

Jira issue: CRDB-36548

Epic CRDB-40359

**Comment by dt** [comment]
The console isn't lying/wrong; the node _is_ using all that space and is out of space:

```
ubuntu@ua-2-0007:~$ ls /mnt/data1/cockroach/*.sst | wc -l
36376
ubuntu@ua-2-0007:~$ du -sch /mnt/data1/cockroach/*.sst | tail -n1
4.8T	total
```

**Comment by dt** [comment]
[n7 store dir listing](https://github.com/cockroachdb/cockroach/files/14563323/ls.txt)
[n7 manifest.zip](https://github.com/cockroachdb/cockroach/files/14563327/n7.manifest.zip)
[n7 pebble log 1.zip](https://github.com/cockroachdb/cockroach/files/14563346/n7.pebble.log.1.zip)
[n7 pebble log 2.zip](https://github.com/cockroachdb/cockroach/files/14563348/n7.pebble.log.2.zip)
[n7 pebble log 3.zip](https://github.com/cockroachdb/cockroach/files/14563350/n7.pebble.log.3.zip)
[n7 text pebble logs.zip](https://github.com/cockroachdb/cockroach/files/14563372/n7.text.pebble.logs.zip)

**Comment by itsbilal** [comment]
unfortunately without the zombie table info from the LSM stats, it's going to be hard to take any action here. We suspect that this is from one longstanding EFOS on a slow consistency check that is pinning a lot of memtables, but it is hard to confirm that unless we can get a good repro here. @dt are you planning on running a similar test again?
