### ISSUE TITLE
Request for roachprod/roachtest flag to skip spot vms

### ISSUE THREAD

**Issue by tusharCRL** [cockroachdb/cockroach#120331]
**Is your feature request related to a problem? Please describe.**
Spot VMs are used now for 50% of benchmark tests chosen randomly. While manually running large(81) node size tpcc benchmark, few nodes died in middle of very long test. It turned out that automation picked spot VMs for this test.

**Describe the solution you'd like**
Availability of an optional flag like `spotVM=false` would really help where spotVMs are not desired.

Jira issue: CRDB-36637

**Comment by srosenberg** [comment]
Fixed by https://github.com/cockroachdb/cockroach/pull/124258
