### ISSUE TITLE
sql: rewrite body of UDFs for function calls

### ISSUE THREAD

**Issue by fqazi** [cockroachdb/cockroach#120351]
Presently when functions are invoked inside UDF bodies the references are all by name, we need to introduce a transformation to convert function invocations into the same special syntax we support for functions referenced by ID. This will allow UDF invocations from breaking if the referenced UDF gets renamed.

i.e:
```
CREATE PROCEDURE p_rewrite() AS $$
  SELECT nested_func();
  SELECT * FROM nested_func();
$$ LANGUAGE SQL

-- This will break today
ALTER FUNCTION nested_func rename nested_func_diff

```

Jira issue: CRDB-36644

Epic CRDB-19398

**Comment by fqazi** [comment]
After talking with @mgartner  we are going to do a short term solution of just blocking renames in this scenario. Longer term we need to rewrite the body, removing the GA tag and splitting this off

**Comment by mgartner** [comment]
Is this a duplicate of #83233?

**Comment by fqazi** [comment]
Yeah, let's close this one out. I'll add that we need to include UDF references now in that one
