### ISSUE TITLE
`latest` Docker tag wasn't updated

### ISSUE THREAD

**Issue by tyranron** [cockroachdb/cockroach#120358]
**Describe the problem**

After 23.2.2 CockroachDB release, the `cockroachdb/cockroach:latest` Docker image has not been updated and still points to the `cockroachdb/cockroach:v23.2.1` image, instead of `cockroachdb/cockroach:v23.2.2`.

`cockroachdb/cockroach:latest-v23.2`, at the same time, correctly points to the `cockroachdb/cockroach:v23.2.2` image.

**Expected behavior**

 `cockroachdb/cockroach:latest`  should point to the latest stable release `cockroachdb/cockroach:v23.2.2`.

**Additional data / screenshots**

<img width="521" alt="Screenshot 2024-03-12 at 19 54 10" src="https://github.com/cockroachdb/cockroach/assets/7114909/e96d1535-5b9b-4efe-8099-b5c0a98fbc7e">
<img width="521" alt="Screenshot 2024-03-12 at 19 53 53" src="https://github.com/cockroachdb/cockroach/assets/7114909/29f2b024-db9b-4e90-b53b-abb1b5cc2405">
<img width="521" alt="Screenshot 2024-03-12 at 19 53 24" src="https://github.com/cockroachdb/cockroach/assets/7114909/49094fb5-dda0-4506-892c-617c5160e683">
<img width="521" alt="Screenshot 2024-03-12 at 19 52 35" src="https://github.com/cockroachdb/cockroach/assets/7114909/26c3664e-5685-4cd9-94c3-ab01e8bb4561">

Jira issue: CRDB-36647

**Comment by rail** [comment]
Looks like a missing flag in the release process.

**Comment by rail** [comment]
We have another release in 5 days, so I'd prefer to avoid fixing the tags semi-manually. I'm going to address the root cause in a separate issue/PR.
