### ISSUE TITLE
sql: enable joins in bigtest

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#12035]
In light of #12033, it seems that we have gaps in our logic testing of joins.

We should enable joins in the bigtest: https://github.com/cockroachdb/cockroach/blob/74032f174ee4bb1f85c7eed099a7274b639db3f1/pkg/sql/logic_test.go#L1076

**Comment by knz** [comment]
We tried that before - See  #7733 and #7734.
We cannot reuse the existing test suite but we could extract salient pieces out of it.

**Comment by knz** [comment]
Suggested by @petermattis: go through the bigtest joins and collect those that work, and otherwise update the TODO in TestLogic.

**Comment by dianasaur323** [comment]
@asubiotto In your team notes re enabling bigtest with distsql, did we address this issue? If so, we can close. Otherwise, no action needed! Thanks.

**Comment by RaduBerinde** [comment]
No, this is about enabling more stuff inside bigtest (for both regular and distsql).

**Comment by jordanlewis** [comment]
I recently investigated adding some more of these, and we're pretty close. The main incompatibility seems to be our lack of support for integer division via `INT / INT` - for some reason this kind of expression shows up in nearly all of the un-enabled tests.

**Comment by dianasaur323** [comment]
Thanks both of you! In that case, I'm going to assign to you for now, @jordanlewis.

**Comment by jordanlewis** [comment]
There's too many in-the-weeds issues blocking this task to leave it a 1.0 priority. I'm still working on it but I don't want it to block other stuff before the release.

**Comment by jordanlewis** [comment]
These tests only test `CROSS JOIN` it turns out, and we can't run them because of random annoying incompatibilities like lack of unary + on strings. I think we should just close this.

**Comment by knz** [comment]
all right, but please then first update the TODO(s) to inform the reader of your conclusions.

**Comment by jordanlewis** [comment]
I've already updated the TODOs after my latest PR.
