### ISSUE TITLE
SSO support IdP providers and client secrets on a per database level

### ISSUE THREAD

**Issue by steven-hubbard** [cockroachdb/cockroach#120380]
Would like to be able to provide multiple sets of IdP information where any comma separated list could work for the entire cluster or that we could tie each one to a specific database within the cluster.

Jira issue: CRDB-36656

gz#20644

**Comment by pritesh-lahoti** [comment]
@steven-hubbard We are currently working on LDAP-based authentication (https://github.com/cockroachdb/cockroach/issues/125076), wherein the authentication method could be configured at a cluster/database/user level within the HBA conf.
We believe that should solve for this use-case. Let us know your thoughts.
cc - @kannanlakshmi @dikshant @BabuSrithar
