### ISSUE TITLE
acceptance: investigate using raw docker http API

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#12043]
a large number of our transitive deps, and many unwanted dep version preferences, come into our dev env via our use of docker/docker/... (e.g. client) for communicating to docker to orchestrate acceptance tests. additionally, many of our annoying dep breakages have come from them renaming a symbol without warning, deleting an entire package (again, without a deprecation cycle) or making other breaking api changes (including vendoring symbols used in their public client API).

using the REST api directly would certainly insulate us from their dependency management choices, and would hopefully also insulate us against at least some of the breaking refactoring changes they've made (e.g. those that didn't break HTTP compat).

This would mean duplicating _some_ client code, but dodging their deps and their churn might be worth it.

**Comment by tamird** [comment]
I don't think this is worth doing. The structured API has benefits beyond just making requests - it documents the available parameters to the various docker engine commands.

The motivation here - bad behaviour in our dependencies management tools (glide) - is the tail wagging the dog. I'm going to close this, but I'm open to further discussion.
