### ISSUE TITLE
workload: initialize bank workload failed with syntax error

### ISSUE THREAD

**Issue by lyang24** [cockroachdb/cockroach#120680]
**Describe the problem**
```
I240318 23:01:38.484242 1 ccl/workloadccl/fixture.go:342  [-] 1  starting import of 1 tables
Error: importing fixture: importing table bank: pq: at or near "(": syntax error
```

**To Reproduce**
ran 
`cockroach workload init bank --rows 1000000000 --ranges 350000 --payload-bytes 10000 --data-loader IMPORT {URL}`
against release v23.2.2 or 23.1.16 on linux environment

**Expected behavior**
seem like this argument is the key to reproduce the issue `--data-loader IMPORT` I think the error could come from here 
https://github.com/cockroachdb/cockroach/blob/1c258e755d2ed83241438ac3bb142625b3da80f5/pkg/ccl/workloadccl/fixture.go#L463

**Environment:**
 - CockroachDB version 23.2.2
 - Server OS: Linux
 - Client app cockroach sql

**Additional context**
What was the impact?

Jira issue: CRDB-36819

**Comment by mgartner** [comment]
@lyang24 Can you share an import file that reproduces this?

**Comment by lyang24** [comment]
> @lyang24 Can you share an import file that reproduces this?

Hey, I am trying initialize the bank work load with import jobs I don't think there are files involved. I took another look at this problem, although the prod code has version v23.2,  I am running an ancient cockroach sql cli version. I tested after upgrade the cli to v23.2 and the problem did not resurface. I am going to close this issue.
```
(base) eyang@HQ-C02FC4D6MD6T scripts % cockroach version
Build Tag:        v21.1.7
Build Time:       2021/08/09 17:58:36
Distribution:     CCL
Platform:         darwin amd64 (x86_64-apple-darwin19)
Go Version:       go1.15.14
C Compiler:       Clang 10.0.0 
Build Commit ID:  1fac61a6cd5bc3385e9378963622559e65667085
Build Type:       release
```
