### ISSUE TITLE
changefeedccl: collated string collation key present in output value

### ISSUE THREAD

**Issue by jayshrivastava** [cockroachdb/cockroach#120696]
When running a changefeed with CSV and collated string (unsure if this is a problem with other encoders), the collation is present in the output string.

```
demo@127.0.0.1:26257/movr> create table foo (id STRING(512) COLLATE en_US_u_ks_level2);                                                                   
CREATE TABLE

Time: 10ms total (execution 9ms / network 1ms)

demo@127.0.0.1:26257/movr> insert into foo values ('id1');                                                                                                
INSERT 0 1

Time: 12ms total (execution 12ms / network 0ms)

demo@127.0.0.1:26257/movr> insert into foo values ('id2');                                                                                                
INSERT 0 1

Time: 2ms total (execution 2ms / network 0ms)

demo@127.0.0.1:26257/movr> CREATE CHANGEFEED FOR TABLE foo WITH full_table_name, format=csv, initial_scan = 'only';                                       
{"key":"","table":"movr.public.foo","value":"'id1' COLLATE en_US_u_ks_level2,952846408169488385"}
{"key":"","table":"movr.public.foo","value":"'id2' COLLATE en_US_u_ks_level2,952846414359166977"}

Time: 20ms total (execution 20ms / network 0ms)

demo@127.0.0.1:26257/movr> select * from foo;                                                                                                             
  id
-------
  id1
  id2
(2 rows)

Time: 3ms total (execution 2ms / network 1ms)

```

There is a workaround for now, at the risk of worse performance (see https://github.com/cockroachdb/cockroach/issues/120369)

```
demo@127.0.0.1:26257/movr> CREATE CHANGEFEED WITH full_table_name, format=csv, initial_scan = 'only' as select id::STRING from foo;                       
{"key":"","table":"movr.public.foo","value":"id1"}
{"key":"","table":"movr.public.foo","value":"id2"}
```

Jira issue: CRDB-36828

**Comment by daniel-yliu** [comment]
Hi I got the issue from the work around, we are at version 23.1.11

invalid syntax: statement ignored: at or near "as": syntax error
SQLSTATE: 42601
DETAIL: source SQL:
`CREATE CHANGEFEED FOR TABLE "Roblox-main-yliu-sandbox"."Roblox.Entities.Cdcstream.LatestTableStatus" INTO 's3://dw-creator-analytics/eaas/production/Roblox-main-yliu-sandbox/Roblox.Entities.Cdcstream.LatestTableStatus/?AWS_ACCESS_KEY_ID=xxx&AWS_SECRET_ACCESS_KEY=yyy&S3_STORAGE_CLASS=INTELLIGENT_TIERING' WITH full_table_name, format=csv, initial_scan='only' as select "id"::STRING from "Roblox-main-yliu-sandbox"."Roblox.Entities.Cdcstream.LatestTableStatus"`

**Comment by jayshrivastava** [comment]
@daniel-yliu You need to leave out the "FOR TABLE ....` part. 

CREATE CHANGEFEED INTO 's3://....' WITH full_table_name, format=csv, initial_scan='only' as select "id"::STRING from "xxxxx"."xxxxx" should work.
