### ISSUE TITLE
colexec: v23.1.9: incorrect interface conversion in SelectIn operator

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#120648]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5079915655/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5079915655/?referrer=webhooks_plugin)

Panic Message:

```
error.go:89: unexpected error from the vectorized engine: interface conversion: tree.Datum is *tree.DTimestamp, not *tree.DTimestampTZ
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:89
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | runtime.panicdottypeE
  | 	GOROOT/src/runtime/iface.go:262
  | runtime.panicdottypeI
  | 	GOROOT/src/runtime/iface.go:272
  | github.com/cockroachdb/cockroach/pkg/sql/colconv.GetDatumToPhysicalFn.func12
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/colconv/datum_to_vec.eg.go:139
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.fillDatumRowTimestamp
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/colexec/select_in.eg.go:2031
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.GetInOperator
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/colexec/select_in.eg.go:315
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colbuilder.planSelectionOperators
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colbuilder/execplan.go:2122
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colbuilder.planSelectionOperators
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colbuilder/execplan.go:2080
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colbuilder.opResult.planFilterExpr
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colbuilder/execplan.go:2038
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colbuilder.opResult.planAndMaybeWrapFilter
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colbuilder/execplan.go:1814
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colbuilder.NewColOperator
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colbuilder/execplan.go:953
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlowCreator).setupFlow.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:1232
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlowCreator).setupFlow
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:1167
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Setup
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:268
  | github.com/cockroachdb/cockroach/pkg/sql/distsql.(*ServerImpl).setupFlow
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql/server.go:429
  | github.com/cockroachdb/cockroach/pkg/sql/distsql.(*ServerImpl).SetupLocalSyncFlow
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql/server.go:597
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).setupFlows
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:459
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:859
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1913
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll.func3
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1645
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1648
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2155
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1709
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1036
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:142
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:3086
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:141
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execPortal
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:247
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2287
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2289
Wraps: (3) unexpected error from the vectorized engine
Wraps: (4) interface conversion: tree.Datum is *tree.DTimestamp, not *tree.DTimestampTZ
  | -- cause hidden behind barrier
  | interface conversion: tree.Datum is *tree.DTimestamp, not *tree.DTimestampTZ
  | (1) interface conversion: tree.Datum is *tree.DTimestamp, not *tree.DTimestampTZ
  | Error types: (1) *runtime.TypeAssertionError
Error types: (1) *assert.withAssertionFailure (2) *withstack.withStack (3) *errutil.withPrefix (4) *barriers.barrierErr
-- report composition:
*barriers.barrierErr: masked error: interface conversion: tree.Datum is *tree.DTimestamp, not *tree.DTimestampTZ
*errutil.withPrefix: unexpected error from the vectorized engine
error.go:89: *withstack.withStack (top exception)
*assert.withAssertionFailure
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/conn_executor.go#L2288-L2290](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/conn_executor.go#L2288-L2290)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/conn_executor.go#L2286-L2288](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/conn_executor.go#L2286-L2288)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/conn_executor_exec.go#L246-L248](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/conn_executor_exec.go#L246-L248)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/conn_executor_exec.go#L140-L142](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/conn_executor_exec.go#L140-L142)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/conn_executor_exec.go#L3085-L3087](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/conn_executor_exec.go#L3085-L3087)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/conn_executor_exec.go#L141-L143](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/conn_executor_exec.go#L141-L143)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/conn_executor_exec.go#L1035-L1037](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/conn_executor_exec.go#L1035-L1037)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/conn_executor_exec.go#L1708-L1710](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/conn_executor_exec.go#L1708-L1710)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/conn_executor_exec.go#L2154-L2156](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/conn_executor_exec.go#L2154-L2156)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/distsql_running.go#L1647-L1649](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/distsql_running.go#L1647-L1649)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/distsql_running.go#L1644-L1646](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/distsql_running.go#L1644-L1646)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/distsql_running.go#L1912-L1914](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/distsql_running.go#L1912-L1914)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/distsql_running.go#L858-L860](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/distsql_running.go#L858-L860)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/distsql_running.go#L458-L460](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/distsql_running.go#L458-L460)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/distsql/server.go#L596-L598](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/distsql/server.go#L596-L598)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/distsql/server.go#L428-L430](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/distsql/server.go#L428-L430)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/colflow/vectorized_flow.go#L267-L269](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/colflow/vectorized_flow.go#L267-L269)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/colflow/vectorized_flow.go#L1166-L1168](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/colflow/vectorized_flow.go#L1166-L1168)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/colflow/vectorized_flow.go#L1231-L1233](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/colflow/vectorized_flow.go#L1231-L1233)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/colexec/colbuilder/execplan.go#L952-L954](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/colexec/colbuilder/execplan.go#L952-L954)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/colexec/colbuilder/execplan.go#L1813-L1815](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/colexec/colbuilder/execplan.go#L1813-L1815)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/colexec/colbuilder/execplan.go#L2037-L2039](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/colexec/colbuilder/execplan.go#L2037-L2039)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/colexec/colbuilder/execplan.go#L2079-L2081](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/colexec/colbuilder/execplan.go#L2079-L2081)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/colexec/colbuilder/execplan.go#L2121-L2123](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/colexec/colbuilder/execplan.go#L2121-L2123)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/bazel-out/k8-opt/bin/pkg/sql/colexec/select_in.eg.go#L314-L316](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/bazel-out/k8-opt/bin/pkg/sql/colexec/select_in.eg.go#L314-L316)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/bazel-out/k8-opt/bin/pkg/sql/colexec/select_in.eg.go#L2030-L2032](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/bazel-out/k8-opt/bin/pkg/sql/colexec/select_in.eg.go#L2030-L2032)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/bazel-out/k8-opt/bin/pkg/sql/colconv/datum_to_vec.eg.go#L138-L140](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/bazel-out/k8-opt/bin/pkg/sql/colconv/datum_to_vec.eg.go#L138-L140)
[GOROOT/src/runtime/iface.go#L271-L273](GOROOT/src/runtime/iface.go#L271-L273)
[GOROOT/src/runtime/iface.go#L261-L263](GOROOT/src/runtime/iface.go#L261-L263)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
[https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/colexecerror/error.go#L88-L90](https://github.com/cockroachdb/cockroach/blob/28b2e767986169df857f5f2cd1790d71ac633395/pkg/sql/colexecerror/error.go#L88-L90)
</details>

```
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 2289
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd.func2 at line 2287
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execPortal at line 247
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 141
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithProfiling at line 3086
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt.func1 at line 142
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 1036
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchToExecutionEngine at line 1709
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithDistSQLEngine at line 2155
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRunAll at line 1648
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRunAll.func3 at line 1645
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRun at line 1913
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).Run at line 859
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).setupFlows at line 459
pkg/sql/distsql/server.go in pkg/sql/distsql.(*ServerImpl).SetupLocalSyncFlow at line 597
pkg/sql/distsql/server.go in pkg/sql/distsql.(*ServerImpl).setupFlow at line 429
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlow).Setup at line 268
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlowCreator).setupFlow at line 1167
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlowCreator).setupFlow.func1 at line 1232
pkg/sql/colexec/colbuilder/execplan.go in pkg/sql/colexec/colbuilder.NewColOperator at line 953
pkg/sql/colexec/colbuilder/execplan.go in pkg/sql/colexec/colbuilder.opResult.planAndMaybeWrapFilter at line 1814
pkg/sql/colexec/colbuilder/execplan.go in pkg/sql/colexec/colbuilder.opResult.planFilterExpr at line 2038
pkg/sql/colexec/colbuilder/execplan.go in pkg/sql/colexec/colbuilder.planSelectionOperators at line 2080
pkg/sql/colexec/colbuilder/execplan.go in pkg/sql/colexec/colbuilder.planSelectionOperators at line 2122
bazel-out/k8-opt/bin/pkg/sql/colexec/select_in.eg.go in pkg/sql/colexec.GetInOperator at line 315
bazel-out/k8-opt/bin/pkg/sql/colexec/select_in.eg.go in pkg/sql/colexec.fillDatumRowTimestamp at line 2031
bazel-out/k8-opt/bin/pkg/sql/colconv/datum_to_vec.eg.go in pkg/sql/colconv.GetDatumToPhysicalFn.func12 at line 139
GOROOT/src/runtime/iface.go in runtime.panicdottypeI at line 272
GOROOT/src/runtime/iface.go in runtime.panicdottypeE at line 262
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1 at line 89
```

### Tags

| Tag | Value |
| --- | --- |
| Command | start-single-node |
| Environment | v23.1.9 |
| Go Version | go1.19.10 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.9 |
| Cockroach SHA | 28b2e767986169df857f5f2cd1790d71ac633395 |
| # of CPUs | 20 |
| # of Goroutines | 507 |

Jira issue: CRDB-36804

**Comment by DrewKimball** [comment]
The logic in `GetDatumToPhysicalFn` doesn't attempt to cast the input datum when the family is `TimestampFamily` or `TimeFamily`, and instead coerces directly to the canonical-typed datum (`DTimestamp` and `DTime`).
https://github.com/cockroachdb/cockroach/blob/d45a65e08d45383aade2bcffdcdbe72a0cc279b1/pkg/sql/colconv/datum_to_vec.eg.go#L93-L101

**Comment by yuzefovich** [comment]
We've seen this only once previously in #87970. In both cases we're in the PREPARE code path.

What this failure tells us is that we have `col IN (tuple)` expression where `col`'s type is TIMESTAMPTZ, but we have at least one element inside of the `tuple` that is TIMESTAMP. I tried reproducing this as a pgtest that uses the extended protocol in which I provided the hint for TIMESTAMP type and comparing against TIMESTAMPTZ column but it passes:
```
send
Query {"String": "CREATE TABLE t (id INT PRIMARY KEY, tz TIMESTAMPTZ);"}
Query {"String": "INSERT INTO t VALUES (1, '2001-01-01 12:00:00.123456'), (2, '2001-01-01 12:00:00.12345'), (3, '2001-01-01 12:00:00.1234');"}
----

until
ReadyForQuery
ReadyForQuery
----
{"Type":"CommandComplete","CommandTag":"CREATE TABLE"}
{"Type":"ReadyForQuery","TxStatus":"I"}
{"Type":"CommandComplete","CommandTag":"INSERT 0 3"}
{"Type":"ReadyForQuery","TxStatus":"I"}

# 1114 is the OIDs for TIMESTAMP.
send
Parse {"Query": "SELECT 1, 2, 3, 4, 5, 6, id FROM t WHERE tz IN ($1, $2)", "ParameterOIDs": [1114,1114]}
Describe {"ObjectType": "S"}
Bind {"Parameters": [{"text":"2001-01-01 12:00:00.1"},{"text":"2001-01-01 12:00:00.1234"}}]}
Execute
Sync
----

until ignore=RowDescription
ReadyForQuery
----
{"Type":"ParseComplete"}
{"Type":"ParameterDescription","ParameterOIDs":[1114,1114]}
{"Type":"RowDescription","Fields":[{"Name":"id","TableOID":104,"TableAttributeNumber":1,"DataTypeOID":20,"DataTypeSize":8,"TypeModifier":-1,"Format":0}]}
{"Type":"BindComplete"}
{"Type":"DataRow","Values":[{"text":"3"}]}
{"Type":"CommandComplete","CommandTag":"SELECT 1"}
{"Type":"ReadyForQuery","TxStatus":"I"}
```

> The logic in GetDatumToPhysicalFn doesn't attempt to cast the input datum when the family is TimestampFamily or TimeFamily, and instead coerces directly to the canonical-typed datum (DTimestamp and DTime).

That's not quite right. We currently don't support TIME and TIMETZ types, while TIMESTAMP and TIMESTAMPTZ types are represented via the same canonical type family. Still, in `GetDatumToPhysicalFn` we pass the actual type of `col` in my example, so we should get the correct conversion. It's either that we have mixed-type elements within the same tuple, or that we're somehow missing the correct cast / type annotation for evaluating that tuple.

Closing as unactionable.
