### ISSUE TITLE
non-nullable column with no value in crl-prod-7tc

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#120660]
**Describe the problem**

This [search](https://cockroachlabsgcp.splunkcloud.com/en-US/app/search/search?earliest=-7d%40h&latest=now&q=search%20index%3Dcc-app-crdb*%20friendly_id%3Dcrl-prod-7tc%20tenant_id%3D193%20%22AUTO%20CREATE%20STATS%22%20severity%3DERROR&display.page.search.mode=verbose&dispatch.sample_ratio=1&display.general.type=events&display.page.search.tab=events&workload_pool=standard_perf&sid=1710783464.90460) shows that there is a serverless cluster that has a non-nullable column with no value.

The problem happened during the AUTO CREATE STATS job. To investigate

- Check if we can access the unredacted logs.
- Check if there were recent schema changes on that table.
- Involve the Queries team for help when needed.

Jira issue: CRDB-36810

**Comment by rimadeodhar** [comment]
Investigation tracked here https://github.com/cockroachlabs/support/issues/2874.
