### ISSUE TITLE
roachprod: account for cost of boot partition

### ISSUE THREAD

**Issue by ajstorm** [cockroachdb/cockroach#120728]
When creating GCE clusters on roachprod, we're not properly accounting for the cost of the root partition.  This can be easily reproed by comparing these two cluster creations:

```
./bin/roachprod create ajstorm-test --clouds gce --nodes 1 --gce-machine-type n2-standard-16 --os-volume-size 10000 --local-ssd=true --gce-zones us-east1-b,us-east1-c,us-east1-d --username ajstorm --lifetime 1h
```

which shows this cost:

```
> roachprod list --pattern ajstorm                                                                                                                                                                             Cluster                     Clouds  Size              VM       Arch  $/hour  $ Spent  Uptime     TTL  $/TTL
                                                                                                       
  ajstorm-test  [gce:cockroach-ephemeral]     1  n2-standard-16   ice lake   $0.86    $0.04    3m0s  57m43s  $0.83
```

and this:

```
./bin/roachprod create ajstorm-test --clouds gce --nodes 1 --gce-machine-type n2-standard-16 --os-volume-size 100 --local-ssd=true --gce-zones us-east1-b,us-east1-c,us-east1-d --username ajstorm --lifetime 1h
```

which shows the same cost:

```
> roachprod list --pattern ajstorm                                                                                                                                                                 
            Cluster                     Clouds  Size              VM       Arch  $/hour  $ Spent  Uptime       TTL  $/TTL
                                                                                                         
  ajstorm-test  [gce:cockroach-ephemeral]     1  n2-standard-16   ice lake   $0.86    $0.01    1m0s  1h54m20s  $1.64
```

Kudos to @herkolategan for catching this problem before it cost us a significant amount of money.

Jira issue: CRDB-36842

**Comment by srosenberg** [comment]
Note, I've relabeled this as `C-enhancement`, as it's technically _not_ a bug. The first iteration of the cost estimation was never meant to be complete as the following comment indicates [1],

```
// populateCostPerHour adds an approximate cost per hour to each VM in the list,
// using a basic estimation method.
//  1. Compute and attached disks are estimated at the list prices, ignoring
//     all discounts, but including any automatically applied credits.
//  2. Boot disk costs are completely ignored.
//  3. Network egress costs are completely ignored.
//  4. Blob storage costs are completely ignored.
```

[1] https://github.com/cockroachdb/cockroach/pull/98955/commits/3a508a1fb6ad88a1487ed1b4bf90628acc8a9c4b#diff-8c23c429158bfbabe87bbb56878a7a26807e4a9bc2dd319d34bb856e7b1e2df5R1162-R1166

**Comment by vidit-bhat** [comment]
Is there any gotcha as to why `bootDisk` is deliberately excluded at [1]? Would removing the if check (and appropriately renaming the field `NonBootAttachedVolumes`) solve the problem?

[1] https://github.com/cockroachdb/cockroach/blob/master/pkg/roachprod/vm/gce/gcloud.go#L217

**Comment by DarrylWong** [comment]
To clarify, I think we still want to keep the concept of `NonBootAttachedVolumes`, since we still need it for `createAttachMountVolumes` which we don't want to call on the boot disk.

I think your initial approach of storing the boot disk separately was correct. When I said that you might be able to combine the two, I specifically meant in the `populateCostPerHour` logic. 

So instead of looping over `for _, v := range vm.NonBootAttachedVolumes {`, you might be able to loop over the union of `NonBootAttachedVolumes` and `BootDiskVolume` since I'm not sure if there's any difference  in costs for boot vs non boot disks.

Alternatively, you could get away with just one field and enforce that index 0 is always the boot disk? I don't think that's a cleaner solution though.

Let me know if that makes sense.

**Comment by vidit-bhat** [comment]
Yeah this makes sense. I too feel the initial approach is better. Will update the draft PR.
