### ISSUE TITLE
admission: control snapshot ingest disk write bandwidth

### ISSUE THREAD

**Issue by sumeerbhola** [cockroachdb/cockroach#120708]
see thread starting at https://github.com/cockroachdb/cockroach/issues/80607#issuecomment-1971592313 for context.

@aadityasondhi @andrewbaptist 

Jira issue: CRDB-36837

Epic CRDB-37479

**Comment by aadityasondhi** [comment]
pre-requisite: https://github.com/cockroachdb/cockroach/issues/86857

**Comment by sumeerbhola** [comment]
Snapshot ingestion can also consume significant CPU, as seen in the attached screenshot
![large-15](https://github.com/user-attachments/assets/ef8fa5d2-a71e-47d4-b791-560235b51113)

So we should also shape the write rate of the incoming bytes based on the CPU resource.

See details in https://cockroachlabs.slack.com/archives/C01SRKWGHG8/p1721291600405649
