### ISSUE TITLE
Sentry: temp_engine.go:40: log.Fatal: read-only file system
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/storage.(*pebbleTempEngine).Close
  | 	github.com/cockro...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#120867]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5090846743/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5090846743/?referrer=webhooks_plugin)

Panic Message:

```
temp_engine.go:40: log.Fatal: read-only file system
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/storage.(*pebbleTempEngine).Close
  | 	github.com/cockroachdb/cockroach/pkg/storage/temp_engine.go:40
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Stop
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:532
  | github.com/cockroachdb/cockroach/pkg/cli.startShutdownAsync.func1
  | 	github.com/cockroachdb/cockroach/pkg/cli/start.go:1138
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (2) secondary error attachment
  | read-only file system
  | (1) read-only file system
  | Error types: (1) syscall.Errno
Wraps: (3) log.Fatal: read-only file system
Error types: (1) *withstack.withStack (2) *secondary.withSecondaryError (3) *errutil.leafError
-- report composition:
*errutil.leafError: log.Fatal: read-only file system
*secondary.withSecondaryError
temp_engine.go:40: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/cli/start.go#L1137-L1139](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/cli/start.go#L1137-L1139)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/util/stop/stopper.go#L531-L533](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/util/stop/stopper.go#L531-L533)
[https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/storage/temp_engine.go#L39-L41](https://github.com/cockroachdb/cockroach/blob/2c1d4afd2c2de091a00a4dba4392ceeaf8504a95/pkg/storage/temp_engine.go#L39-L41)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/cli/start.go in pkg/cli.startShutdownAsync.func1 at line 1138
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).Stop at line 532
pkg/storage/temp_engine.go in pkg/storage.(*pebbleTempEngine).Close at line 40
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v23.1.8 |
| Go Version | go1.19.10 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.8 |
| Cockroach SHA | 2c1d4afd2c2de091a00a4dba4392ceeaf8504a95 |
| # of CPUs | 14 |
| # of Goroutines | 26 |

Jira issue: CRDB-36909

**Comment by yuzefovich** [comment]
dup of #86703
