### ISSUE TITLE
teamcity: automate jepsen testing

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#12098]
So we need to get two things rolling:

- automate the deployment of the jepsen test driver on a TC VM
- automate the execution of tests using a pool of VMs created on demand every day/week to run the tests.

(requested by @tamird / @cuongdo )

**Comment by jordanlewis** [comment]
How long do the tests take? Do they require multiple actual hosts, or do they work with docker on a single host?

**Comment by knz** [comment]
There are several tests (at least 5 we're interested in). Each test runs for a minimum of 5 minutes, although Aphyr recommends we run them for 45 minutes. These are cluster tests which need to change the network configuration of the cluster while each test is running, so they require multiple dedicated VMs/hosts.

The way it's commonly used is 1 "master" host then 3-5 VMs to run the tests on.

**Comment by jordanlewis** [comment]
It will be much easier to automate this using something like Terraform than trying to coordinate multiple TeamCity agents. I do not recommend trying the latter approach!

Can we try to write a Terraform configuration for this setup, similar to how most of the Nightly tests work? That way, TeamCity will simply trigger the Terraform configuration and watch the tests run remotely.

**Comment by cuongdo** [comment]
Yes, a Terraform config seems best given the need for multiple hosts. Let me know if you need help. The Terraform configs we use for the nightly allocator & load tests are in `pkg/acceptance/terraform`.

**Comment by jordanlewis** [comment]
Update:
- [x] Prepare a Terraform configuration #12328
- [ ] Create a script that does the following:
  - [ ] Package the latest Cockroach binary into an archive suitable for Jepsen and upload it to S3.
  - [ ] Run the tests sequentially.
    - [ ] Decide which combinations of tests and nemeses to run. @knz @spencerkimball 
  - [ ] As each test completes, output TeamCity-readable results based on the output from Jepsen.
  - [ ] Download the `store` directory from the Jepsen controller and archive the artifacts

**Comment by jordanlewis** [comment]
As a reminder to the script author:
- Start the `ssh-agent` and run `ssh-add` before starting the Jepsen tests to prevent `Auth Fail`.
- Set `--os ubuntu`, `--username ubuntu` in the `lein run` configuration.
