### ISSUE TITLE
util/span: btree based Frontier can drop `Forward` calls

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#120987]
PCR has been observed to get stuck in some cases, as described in #120231. While some performance-related issues were identified in that ticket, another issue was identified where the frontier would often become incorrect, according to the updates that were written to it.

One clue however was that this behavior was only observed when using the btree-based frontier; the LLBR frontier would reliably stay synchronized with its rangefeed. Playing back a recording of the rangefeed events in a unit test to an LLBR and BTree frontier side-by-side showed the same behavior, with the btree frontier becoming de-synchronized with the LLBR frontier after between 2k-80k updates.

Jira issue: CRDB-36990

**Comment by msbutler** [comment]
new btree was disabled, no longer blocks release

**Comment by dt** [comment]
we just disabled the library, but we didn't fix the bug in it yet, so this should remain open.
