### ISSUE TITLE
Support adding an AUTHORIZATION using an ALTER statement

### ISSUE THREAD

**Issue by dikshant** [cockroachdb/cockroach#121040]
The following is currently supported:
```
demo@127.0.0.1:26257/movr> CREATE SCHEMA tdbo AUTHORIZATION max1;
CREATE SCHEMA

Time: 40ms total (execution 40ms / network 0ms)
```

But not
```
demo@127.0.0.1:26257/movr> ALTER SCHEMA tdbo AUTHORIZATION max2;
invalid syntax: statement ignored: at or near "authorization": syntax error
SQLSTATE: 42601
DETAIL: source SQL:
ALTER SCHEMA tdbo AUTHORIZATION max2
^
HINT: try \h ALTER SCHEMA
```

We should support the ALTER. Additionally we should support to remove any authorizations:
```
demo@127.0.0.1:26257/movr> ALTER SCHEMA tdbo AUTHORIZATION NONE;
```

Jira issue: CRDB-37043

**Comment by rafiss** [comment]
this is supported with a different syntax: `ALTER SCHEMA schema_name OWNER TO user_name`. This matches Postgres: https://www.postgresql.org/docs/current/sql-alterschema.html

**Comment by dikshant** [comment]
Owner To would change the ownership of that object. The ask here is to not allow for that to happen but merely authorize another user. Postgres doesn't support this as far as I know but this request is still valid. So I am reopening it.

**Comment by rafiss** [comment]
> Owner To would change the ownership of that object.


In Postgres, `CREATE SCHEMA schema_name AUTHORIZATION user_name` makes `user_name` the owner. See the Postgres docs: ​https://www.postgresql.org/docs/current/sql-createschema.html

Similarly, in Postgres, `ALTER SCHEMA schema_name OWNER TO user_name`, will change the ownership of the schema so `user_name` owns it. CockroachDB matches both of those behaviors.

> The ask here is to not allow for that to happen but merely authorize another user. Postgres doesn't support this as far as I know but this request is still valid. So I am reopening it.

yes, that is what the CREATE and USAGE privileges are for:

```
GRANT CREATE ON SCHEMA schema_name TO user_name;
GRANT USAGE ON SCHEMA schema_name TO user_name;
```

After running the above commands, `user_name` will be able to create objects inside of that schema.
