### ISSUE TITLE
rangefeed: scheduler-based rangefeed processor does not signal catchup scan completion

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#121053]
The legacy rangefeed processor would publish a 0-valued checkpoint to signal completion of a catchup scan. The scheduler-based processor doesn't do this. It probably should.

https://github.com/cockroachdb/cockroach/blob/52a15f24866b2f1027455bcb05c22b277045620c/pkg/kv/kvserver/rangefeed/processor.go#L442-L447

Jira issue: CRDB-37049

Epic CRDB-39959

**Comment by wenyihu6** [comment]
I think scheduler-based processor also publishes a 0-valued checkpoint to signal completion of a catchup scan
https://github.com/cockroachdb/cockroach/blob/c83c57d354741ac36740894f7387c014eb6c09fe/pkg/kv/kvserver/rangefeed/scheduled_processor.go#L344.
