### ISSUE TITLE
kvcoord: `LeaseInfo` requests should be ignored by follower routing/proxying

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#121037]
DistSender circuit breakers use `LeaseInfo` requests as a makeshift health check. These probably shouldn't be subject to follower routing/proxying, since we're specifically asking about this replica's health, not the leaseholder's health or reachability. However, that doesn't mean that all `LeaseInfo` requests should be ignored -- if some other client sends one for non-health-check purposes, we probably do want to proxy it, like any other read request.

Proposal: add a boolean `NoProxy` field either to `LeaseInfoRequest` or `RequestHeader`, and set it in `DistSenderCircuitBreakers.sendProbe()`.

Jira issue: CRDB-37040

Epic CRDB-25200

**Comment by erikgrinaker** [comment]
@andrewbaptist Opinions on this? A `RequestHeader` field seems like it would be more generally useful.

**Comment by andrewbaptist** [comment]
I don't know if it is necessary here. We create a transport with only 1 replica in it. That type of request can never be proxied since there is no follower. 

I agree this might be needed in general, but I think it is better to hold off until there is a specific case where this is necessary.

**Comment by erikgrinaker** [comment]
What do you mean? It will be proxied like any other read request.

**Comment by erikgrinaker** [comment]
Specifically, if the replica is healthy but proxying fails, this will trip the circuit breaker even though the replica is healthy. This will commonly happen when a leaseholder crashes.

**Comment by erikgrinaker** [comment]
Oh wait, I get what you're saying. We're using a transport directly in sendProbe, bypassing the DistSender entirely.

**Comment by andrewbaptist** [comment]
Right - The transport doesn't proxy, only the DistSender does., although I did get confused on this.  

I had originally thought that a `sendToReplicas` with only one follower replica transport would never be proxied, but I may be wrong. If we know the leaseholder and the routing policy is `LEASEHOLDER` we can still create a proxy request. 

I don't know if this is a feature or a bug... (as I can't think of why we would hit that combination)
