### ISSUE TITLE
rangefeed: revert removal of non-mux/scheduler rangefeeds

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#121054]
We recently removed the legacy rangefeed protocol and scheduler, to simplify implementation of #110432. However, #110432 slipped to 24.2, so this removal is no longer strictly necessary. We should revert their removal, but keep them enabled by default, such that it's possible to change back to the legacy implementations via cluster setting in case of problems.

* https://github.com/cockroachdb/cockroach/pull/114408
* https://github.com/cockroachdb/cockroach/pull/114410

This also requires updated release notes and docs changes.

Jira issue: CRDB-37050

**Comment by erikgrinaker** [comment]
We're reverting the legacy processor removal in #121164, but keeping the scheduler enabled by default.

I won't have time to revert the unconditional mux rangefeed (#114408), but we may not want/have to either. This has been in use at several large customers for years, so we have fairly high confidence in it. If we keep it unconditionally enabled in 24.1, then we can remove the legacy protocol and code in 24.2 (i.e. after today's branch cut), which may be worthwhile.

I'll leave this determination to @rharding6373 and @nvanbenschoten.

**Comment by nvanbenschoten** [comment]
@rharding6373 given what Erik said above about our high confidence in mux rangefeed, it sounds reasonable to me to keep the non-mux rangefeed unconditionally enabled in 24.1. If you agree, I'll go ahead and close this issue.

**Comment by rharding6373** [comment]
Sounds good to me.
