### ISSUE TITLE
storage: virtual sstable bugs

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/cockroach#121166]
Companion issue for virtual sstable related bugs being surfaced by the Pebble metamorphic tests:

- [x] cockroachdb/pebble#3447
- [x] cockroachdb/pebble#3448
- [x] cockroachdb/pebble#3455
- [x] cockroachdb/pebble#3456
- [x] cockroachdb/pebble#3450
- [x] cockroachdb/pebble#3459
- [x] cockroachdb/pebble#3470
- [x] cockroachdb/cockroach#121263
- [x] cockroachdb/pebble#3485

Jira issue: CRDB-37103

**Comment by jbowens** [comment]
I'm downgrading this to a GA-blocker because the remaining item cockroachdb/pebble#3470 only affects online restore.

**Comment by itsbilal** [comment]
All known subissues are fixed at this time. We can probably close this, and reopen it if something else pops up?
