### ISSUE TITLE
`SHOW DEFAULT SESSION VARIABLES FOR ROLE` does not appear in CLI output for `\h SHOW`

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/cockroach#121139]
Running `cockroach demo` with a v24.1 alpha on macOS

```
$ uname -a
Darwin crlMBP-C02F51KPML7JMTI2.local 23.4.0 Darwin Kernel Version 23.4.0: Wed Feb 21 21:44:31 PST 2024; root:xnu-10063.101.15~2/RELEASE_X86_64 x86_64
```

```
select version();                          
                                                       version
---------------------------------------------------------------------------------------------------------------------
  CockroachDB CCL v24.1.0-alpha.4 (x86_64-apple-darwin19, built 2024/03/20 14:34:54, go1.22.1 X:nocoverageredesign)
(1 row)
```

The new statement `SHOW DEFAULT SESSION VARIABLES FOR USER {foo}` added in https://github.com/cockroachdb/cockroach/pull/117875 does not appear in the CLI help output for `SHOW`

```
\h SHOW                                    
Command:     SHOW
Syntax:
SHOW BACKUP, SHOW CLUSTER SETTING, SHOW COLUMNS, SHOW CONSTRAINTS,
SHOW CREATE, SHOW CREATE SCHEDULES, SHOW DATABASES, SHOW ENUMS, ...
```

Since the statements appear to be in alphabetical order, I'd expect it to appear between `SHOW DATABASES` and `SHOW ENUMS`

Found while working on https://github.com/cockroachdb/docs/pull/18422 

Jira issue: CRDB-37097

Epic CRDB-26921

**Comment by rafiss** [comment]
i believe the fix here is to add that statement to the list here: https://github.com/cockroachdb/cockroach/blob/54c06fcd610dea27de429bf2527c4e9dc2a381de/pkg/sql/parser/sql.y#L7425-L7434
