### ISSUE TITLE
sql: support INTERVAL x HOUR TO MINUTE syntax

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#12110]
Sequelize tries to run the following query when it starts up:

`SET TIME ZONE INTERVAL '+00:00' HOUR TO MINUTE;`

We currently don't support this syntax and return an error immediately.

**Comment by jordanlewis** [comment]
The official documentation for this format is here: https://www.postgresql.org/docs/9.6/static/datatype-datetime.html

And here is an enlightening mailing list thread about it: https://www.postgresql.org/message-id/20110510040219.GD5617%40tornado.gateway.2wire.net

The main takeaway is that the intervals suffixed with `X TO Y` behave identically to the same intervals suffixed with `Y`, and intervals suffixed with `Y` truncate extra precision past that of `Y`, as well as using `Y` as the base interval unit if the interval string contains nothing but a numeric value.

**Comment by a6802739** [comment]
@jordanlewis, could I have a try for this?

**Comment by jordanlewis** [comment]
I've already almost completed a patch for this, but thanks anyway!

**Comment by arjunravinarayan** [comment]
Thank you @jordanlewis, do loop me in when you submit your patch!
