### ISSUE TITLE
sql: support read-only SERVER_VERSION variable

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#12112]
Sequelize tries to read the value of `SHOW SERVER_VERSION`, which we currently don't support. Internally, it will parse the value of `SERVER_VERSION` as a `semver` and compare it against various known postgres versions to check for feature compatibility.

If we want to support Sequelize without patching it, we'll need to return a value for `SERVER_VERSION` that reflects the latest version of Postgres that we claim to mimic.

**Comment by tamird** [comment]
Note that we already have `server_version` in the `sql/pgwire.statusReportParams` map.
