### ISSUE TITLE
storage: investigate drop in SQL queries during online manual compaction

### ISSUE THREAD

**Issue by itsbilal** [cockroachdb/cockroach#121214]
On the `drt-ua1` test cluster, running an online manual compaction  `select crdb_internal.compact_engine_span(crdb_internal.node_id(), crdb_internal.node_id(), crdb_internal.tenant_span(2)[1], crdb_internal.tenant_span(2)[2]);` resulted in a near-total drop in SQL queries as SQL query latency went through the roof (p99 was at 10000ms).

Investigate what went wrong and if there's something that can be done in AC or in pkg/storage to minimize this extreme consequence of an online manual compaction.

![Screenshot 2024-03-26 at 1 47 53 PM](https://github.com/cockroachdb/cockroach/assets/345332/f43773e8-7c7b-4f70-a7ea-5b8ecb4fd179)

![Screenshot 2024-03-26 at 2 10 49 PM](https://github.com/cockroachdb/cockroach/assets/345332/d5c1fefc-fcdf-4099-9f68-d54f23897768)

Jira issue: CRDB-37141

**Comment by jbowens** [comment]
is this cluster on centmon or some other grafna so that we can peek at the metrics at the time?
