### ISSUE TITLE
sql: TestMultiRegionDataDriven/regional_by_table flaked [expected node 6 to have replica type voter but was leaseholder]

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#121239]
See flake in [unrelated pr](https://teamcity.cockroachdb.com/viewLog.html?buildId=14589567&buildTypeId=Cockroach_BazelEssentialCi)

Jira issue: CRDB-37151

**Comment by rafiss** [comment]
error is 
```
    datadriven.go:144: 
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/4515/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/ccl/multiregionccl/multiregionccl_test_/multiregionccl_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/multiregionccl/testdata/regional_by_table:200:
         
        expected:
        
        found:
        expected node %!s(int=6) to have replica type voter but was leaseholder
```

Checking if KV/Replication can investigate.

**Comment by arulajmani** [comment]
I can't see the artifacts anymore, but looks like this flaked because of a lease transfer. Seems benign, and a testing issue, so I'll add labels to reflect that.

**Comment by arulajmani** [comment]
Looking at this again, I was mislead by the error. I think we're missing an early return in cases where the replica is already a leaseholder. So, around here:
https://github.com/cockroachdb/cockroach/blob/b9ad8248f67df516eb1628093d2fb9756eac20b2/pkg/ccl/multiregionccl/datadriven_test.go#L387

I'll send out a patch.
