### ISSUE TITLE
restore: online restore produces a "bad split"

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#121252]
Currently export request can stop due to pagination (size, cpu, etc) at a key which is one of n column families of a row. Backup can flush this to its SST, which, if it hits its size limit at that point, can close and product a file span entry in the manifest that ends at that mid-row key. The following file span would then start at the same mid-row key.

These mid-row keys are _not_ valid split points, however restore span generation uses file start keys as its split points. Accordingly -- at least as of the creation of the 24.1 branch and in online restore, though potentially in classic restore and other versions subject to more investigation -- RESTORE can split at one of these mid-row keys, producing a "bad split" that, while perfectly valid in the KV layer and to backup/restore, is invalid to SQL readers who expect a read to a single range to read all of, or none of, a row that was broken up into some number of separate -- and to the kv layer and backup restore layers independent -- keys.

This error was observed on a cluster some number of days after an online restore:
```
root@localhost:26257/main/defaultdb> select count(distinct t_s_symb) from tpce.trade where t_id > 200000683218000 and t_id < 200000683228180;
ERROR: internal error: unexpected error from the vectorized engine: null_value_error: non-nullable column "trade:t_s_symb" with no value! Index scanned was "trade_pkey" with the index key columns (t_id) and the values (200000683218180)
```
Looking at the ranges it appears to have a bad split:
```
root@localhost:26257/main/defaultdb> select start_key, end_key from [show ranges from table tpce.trade] where start_key like '%200000683218%' or end_key LIKE '%200000683218%';
              start_key             |              end_key
------------------------------------+------------------------------------
  …/Table/139/1/200000682474907     | …/Table/139/1/200000683218180/2/1
  …/Table/139/1/200000683218180/2/1 | …/Table/139/1/200000685406968
(2 rows)

Time: 3.820s total (execution 3.820s / network 0.000s)
```

The restore was performed as:
```
RESTORE VIRTUAL CLUSTER 2
 FROM 'gs://cockroach-fixtures-us-east1/backups/tpc-e/v24.1/tenant/customers=2000000?AUTH=implicit' WITH OPTIONS (experimental deferred copy)
```

Inspection of the backup shows that the split key came from the file in the backup: 
```
demo@127.0.0.1:26257/movr> select * from [show backup files 'gs://cockroach-fixtures-us-east1/backups/tpc-e/v24.1/tenant/customers=2000000?AUTH=implicit'] where end_pretty like '%200000683218180%' or start_pretty like '%200000683218180%' limit 20;
             path             | backup_type |               start_pretty                |                end_pretty                 |           start_key            |            end_key             | size_bytes | rows | locality | file_bytes
------------------------------+-------------+-------------------------------------------+-------------------------------------------+--------------------------------+--------------------------------+------------+------+----------+-------------
  data/954492389506744321.sst | full        | /Tenant/2/Table/139/1/200000682474907     | /Tenant/2/Table/139/1/200000683218180/2/1 | \xfe8af68b89fbb5e649a23d9b     | \xfe8af68b89fbb5e649ad95048a89 |  103783459 |    0 | NULL     |         -1
  data/954492438748266497.sst | full        | /Tenant/2/Table/139/1/200000683218180/2/1 | /Tenant/2/Table/139/1/200000684856072/1/1 | \xfe8af68b89fbb5e649ad95048a89 | \xfe8af68b89fbb5e649c693088989 |  228708165 |    0 | NULL     |         -1
```

Jira issue: CRDB-37155

**Comment by dt** [comment]
Non-online restore is fine:
https://github.com/cockrachdb/cockroach/blob/master/pkg/ccl/backupccl/generative_split_and_scatter_processor.go#L148

**Comment by msbutler** [comment]
we can close this out, as the backport has landed https://github.com/cockroachdb/cockroach/pull/122311
