### ISSUE TITLE
sql: sequelize support is blocked on stored procedures

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#12120]
Sequelize's `postgres` dialect currently uses stored procedures for all database updates: see [`upsertQuery`](https://github.com/sequelize/sequelize/blob/70e053cbb8e66ef6c21091cc1b3d8ab46ae1325e/lib/dialects/postgres/query-generator.js#L282).

This is a pretty serious blocker to supporting Sequelize out of the box. As an alternative, we could consider creating a simple custom Sequelize dialect that simply overrides `upsertQuery` from the `postgres` dialect to do something without stored procedures.

**Comment by cuongdo** [comment]
Because Sequelize ships with few dialects *and* it's going to take us a while to support stored procedures, the custom dialect seems like the fastest path to supporting Sequelize. Is it possible to create a minimally hacky solution for patching the `postgres` dialect at runtime, which can be delivered to developers in a reasonable manner?

**Comment by cuongdo** [comment]
FYI `upsertQuery` creates `sequelize_upsert`, which executes an upsert with the same return values that MySQL has  for `INSERT .. ON DUPLICATE KEY UPDATE`. Relevant MySQL reference:

http://dev.mysql.com/doc/refman/5.7/en/insert-on-duplicate.html

Relevant quote:

With `ON DUPLICATE KEY UPDATE`, the affected-rows value per row is 1 if the row is inserted as a new row, 2 if an existing row is updated, and 0 if an existing row is set to its current values.

**Comment by bdarnell** [comment]
Another option would be to submit a PR upstream to sequelize that would make the postgres dialect use `ON CONFLICT DO UPDATE` instead of the stored procedure when the server version >= 9.5.0.
