### ISSUE TITLE
sql: Hibernate expects pg_attribute.attname to be lowercased

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#12122]
As you can see from the bottom of [this query](https://gist.github.com/jordanlewis/9d6a5a56b6776d0b16ffc883f14dce59), Hibernate expects that values in `pg_attribute.attname` (in this case, `'id'`) are lowercase. Our example ORM app explicitly sets an uppercase column name (`'ID'`) here.

So, it seems that we upcase these values somewhere, causing this query to fail. This may be related to #8862.

**Comment by nvanbenschoten** [comment]
We uppercase these attribute names ourselves. Have you tried lowercasing lines like https://github.com/cockroachdb/examples-orms/blob/nvanbenschoten/hibernate/java/hibernate/src/main/java/com/cockroachlabs/model/Customer.java#L11? I think this will fix the immediate issue, although #8862 is still an issue in general.

**Comment by nvanbenschoten** [comment]
After making [the change](https://github.com/cockroachdb/examples-orms/commit/ba23ba4b01d171240c6dfdaf6edb16c05c3a4d18) I discussed above and running on #12102, the next error I get is `compound types not supported yet: "con.confkey[pos.n]"`, which should be addressed by #12111. I'm investigating what will still be missing once @knz's PR gets merged.

**Comment by jordanlewis** [comment]
This seems like a duplicate of #8862. Closing.
