### ISSUE TITLE
sql: panic in CAST

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#12125]
```
create database ident;
create table ident.ident (ident int);
SELECT CAST ( - ROW ( ) AS REGPROC ) FROM ident.ident;
```

Found with RSG.

@knz you may have touched this most recently.

**Comment by jordanlewis** [comment]
@mjibson sent a PR. The new behavior of that query is:

```
root@:26257> SELECT CAST ( - ROW ( ) AS REGPROC ) FROM ident.ident;
pq: unsupported unary operator: - <tuple{}>
```

Does that sound correct to you?

**Comment by knz** [comment]
Yes
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
