### ISSUE TITLE
jobs: change 24.1 drop upgrade to rename+hide

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#121365]
The drop migration will rewrite the table which is unnecessarily expensive; all we need is to ensure they are not being accessed (by renaming it then hiding it)

NB: this blocks minting the cluster version.

Jira issue: CRDB-37215

**Comment by dt** [comment]
This needs to be a release-blocker rather than GA blocker since it will break compatibility with a prior beta (only in a strict sense, if we care about all clusters having the same system tables regardless of bootstrap version).

**Comment by msbutler** [comment]
keeping this open until 24.1 backport lands

**Comment by msbutler** [comment]
https://github.com/cockroachdb/cockroach/pull/121747
