### ISSUE TITLE
sql: support SEARCH_PATH variable

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#12137]
ActiveRecord tries to set `SEARCH_PATH` to `public` when it starts up. We need to support this.

See https://www.postgresql.org/docs/9.1/static/runtime-config-client.html

**Comment by asubiotto** [comment]
Reopening this for tracking because `lib/pq` also uses this for tests.

**Comment by jordanlewis** [comment]
This is actually fixed now.

**Comment by jordanlewis** [comment]
```root@127.0.0.1:62369/defaultdb> set search_path=public;
SET

Time: 259µs

root@127.0.0.1:62369/defaultdb> set search_path=public,pg_catalog;
SET

Time: 272µs```
