### ISSUE TITLE
apt and/or dnf/yum repo

### ISSUE THREAD

**Issue by idc77** [cockroachdb/cockroach#121304]
**Is your feature request related to a problem? Please describe.**
I use Archlinux, which has a good AUR script for cockroachdb.

Now I'm experimenting and my 3rd machine runs Ubuntu 22.04.
The instructions for docker are only for local trying it out thingy.
There is no apt repo, or if I used centos rocky whatever rhel clone, there is no yum repo either.
So the only way to way to be up to date would be docker with --net=host.
Who knows what unforseen issue there might be with this.

TLDR there are no apt or yum repos available

Bonus: Asking you a simple questiong is so hard, you have to either create a slack account (who likes slack, I don't), or a discourse account, which then sends you weekly digests, I don't want that. Why not just use github discussions?
You're not on the Fediverse, you're no on IRC, there are no simple means to ask a simple question, "does crdb have apt or yum repos?"
Since I can't find any, I'm guessing no, and now I have to write this feature request, which will probably be closed anyway.

**Describe the solution you'd like**
Provide apt or yum repos with the latest binary and systemd script.
Orient yourself at [the archlinux AUR script](https://aur.archlinux.org/packages/cockroachdb-bin) maybe.

**Describe alternatives you've considered**
There is no alternative. The alternative is to not use crdb. 
I know you want to sell your cloud offer, so you're trying to make it harder for people to self-host.
I already lost the motivation to finish my experiment, because I have to jump through hoops regarding everything.

**Additional context**

Jira issue: CRDB-37178

**Comment by rickystewart** [comment]
There are no plans to host an `apt` or `yum` repo, however you do not have to use Docker if you wish. Instead you can simply follow [these instructions](https://www.cockroachlabs.com/docs/v23.2/install-cockroachdb-linux) to extract the tarball containing the binary onto your system.

**Comment by rickystewart** [comment]
Closing this as there is a workaround and we will not be implementing the originally requested feature.
