### ISSUE TITLE
kv: Get rid of NoopRequests

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#12142]
Opening a separate issue to avoid losing track of @petermattis's comment on https://github.com/cockroachdb/cockroach/issues/11195#issuecomment-264659110, suggesting that we may want to get rid of NoopRequests as a performance optimization.

**Comment by petermattis** [comment]
In light of #16632, should this be moved to 1.1?

Cc @bdarnell, @tschottdorf

**Comment by bdarnell** [comment]
It's definitely worth considering for 1.1. I also think there are things we can do to make NoopRequests cheaper (replacing `Re{quest,sponse}Union` with something custom, for example).

**Comment by tschottdorf** [comment]
Yeah, I think we should look into never sending `NoopRequests`. Should be doable if we're willing to do a little bit more bookkeeping in `DistSender`. Basically, batch truncation now doesn't introduce `NoopRequests` but instead produces a batch fully relevant to the destination range, and returns enough information to associate the responses to that batch to the original batch (I think we only need a mapping `index_in_response -> index_in_original_batch`.

Maybe I'm missing something, but that really doesn't sound so hard.

**Comment by petermattis** [comment]
@tschottdorf That sounds right to me. Agreed that this doesn't sound too hard. And there are no migrations issues. Nothing but win here.
