### ISSUE TITLE
How can I get a table size using query?

### ISSUE THREAD

**Issue by TWpower** [cockroachdb/cockroach#121449]
**Is your feature request related to a problem? Please describe.**
- I cannot get the size of table in cockroachdb

**Describe the solution you'd like**
- Is there any function like pg_total_relation_size() in postgresql?
- I need information of each table size like using pg_total_relation_size()

**Describe alternatives you've considered**
- I could not find andy alternatives...

Jira issue: CRDB-37268

**Comment by rafiss** [comment]
https://github.com/cockroachdb/cockroach/issues/86017 is an existing tracking issue for `pg_relation_size`, so i'll close this one as a duplicate.

until that is implemented, you can see this information by using `SHOW RANGES FROM TABLE table_name WITH DETAILS`, which will show the size of each range in the table in the `range_size_mb` column. You can add them all up using: `SELECT sum(range_size_mb) FROM [SHOW RANGES FROM TABLE table_name WITH DETAILS]`

**Comment by TWpower** [comment]
@rafiss Thank you very much for it!
