### ISSUE TITLE
sql: current_schema{,s}() builtins should return public, not database name

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#12148]
In postgres, running `current_schema()` or `current_schemas(false)` will return `public` when the current database is a user-created database with default settings. We currently return the database name.

This is breaking ActiveRecord, which expects `current_schemas(false)` to contain a match for the namespace name of a table's `pg_class.relnamespace` column (which we always set to `public` for user-created tables) for the following query:

```
SELECT * FROM pg_class AS c
LEFT JOIN pg_namespace AS n
ON n.oid = c.relnamespace
WHERE ((c.relkind IN ('r', 'v', 'm'))AND (c.relname = 'schema_migrations'))
AND (n.nspname = ANY (current_schemas(false)));
```

**Comment by cuongdo** [comment]
What should it return when the current database is `system`?

**Comment by jordanlewis** [comment]
`system`. I think we can reuse a function for this that's defined in`pg_catalog.go`: `pgNamespaceForDb`.
