### ISSUE TITLE
Support jsonb_path_query()

### ISSUE THREAD

**Issue by DingDLu** [cockroachdb/cockroach#121512]
Customer needs to construct complex JSONB Queries to search into arbitrarily nested JSON through their application code and SQL Alchemy.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Jira issue: CRDB-37295

**Comment by rytaft** [comment]
Is this the same as #22513?

**Comment by dikshant** [comment]
Yep definitely the same.

**Comment by mgartner** [comment]
Closing as a duplicate of #22513.
