### ISSUE TITLE
backupccl: TestBackupSharedProcessTenantNodeDown flaked on 24.1

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#121567]
See flake [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=14669273&buildTypeId=Cockroach_BazelEssentialCi)

Jira issue: CRDB-37342

**Comment by stevendanna** [comment]
I'm downgrading this to P-2 to better reflect reality.

**Comment by stevendanna** [comment]
I stressed this for an hour or so and haven't reproduced this locally and the logs above are gone. Closing for now. Re-open if it flakes again.
