### ISSUE TITLE
Sentry: mutation_builder.go:1434: no value for check input column (tabOrd=75)
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/opt/o...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#121596]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5135252647/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5135252647/?referrer=webhooks_plugin)

Panic Message:

```
mutation_builder.go:1434: no value for check input column (tabOrd=75)
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*mutationBuilder).buildCheckInputScan
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/mutation_builder.go:1434
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*fkCheckHelper).buildInsertionCheck
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/mutation_builder_fk.go:637
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*mutationBuilder).buildFKChecksForInsert
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/mutation_builder_fk.go:77
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*mutationBuilder).buildInsert
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/insert.go:685
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildInsert
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/insert.go:293
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmt.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:344
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).processWiths
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/with.go:116
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:343
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmtAtRoot
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:272
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).Build
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:246
  | github.com/cockroachdb/cockroach/pkg/sql.(*optPlanningCtx).buildExecMemo
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:576
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).makeOptimizerPlan
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:240
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).makeExecPlan
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1978
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1484
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:964
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:142
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2986
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:141
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2181
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2186
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2103
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:900
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:310
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (3) no value for check input column (tabOrd=75)
Error types: (1) *assert.withAssertionFailure (2) *withstack.withStack (3) *errutil.leafError
-- report composition:
*errutil.leafError: no value for check input column (tabOrd=75)
mutation_builder.go:1434: *withstack.withStack (top exception)
*assert.withAssertionFailure
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/pgwire/conn.go#L309-L311](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/pgwire/conn.go#L309-L311)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/conn_executor.go#L899-L901](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/conn_executor.go#L899-L901)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/conn_executor.go#L2102-L2104](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/conn_executor.go#L2102-L2104)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/conn_executor.go#L2185-L2187](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/conn_executor.go#L2185-L2187)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/conn_executor.go#L2180-L2182](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/conn_executor.go#L2180-L2182)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/conn_executor_exec.go#L140-L142](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/conn_executor_exec.go#L140-L142)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/conn_executor_exec.go#L2985-L2987](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/conn_executor_exec.go#L2985-L2987)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/conn_executor_exec.go#L141-L143](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/conn_executor_exec.go#L141-L143)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/conn_executor_exec.go#L963-L965](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/conn_executor_exec.go#L963-L965)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/conn_executor_exec.go#L1483-L1485](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/conn_executor_exec.go#L1483-L1485)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/conn_executor_exec.go#L1977-L1979](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/conn_executor_exec.go#L1977-L1979)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/plan_opt.go#L239-L241](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/plan_opt.go#L239-L241)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/plan_opt.go#L575-L577](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/plan_opt.go#L575-L577)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt/optbuilder/builder.go#L245-L247](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt/optbuilder/builder.go#L245-L247)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt/optbuilder/builder.go#L271-L273](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt/optbuilder/builder.go#L271-L273)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt/optbuilder/builder.go#L342-L344](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt/optbuilder/builder.go#L342-L344)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt/optbuilder/with.go#L115-L117](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt/optbuilder/with.go#L115-L117)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt/optbuilder/builder.go#L343-L345](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt/optbuilder/builder.go#L343-L345)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt/optbuilder/insert.go#L292-L294](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt/optbuilder/insert.go#L292-L294)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt/optbuilder/insert.go#L684-L686](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt/optbuilder/insert.go#L684-L686)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt/optbuilder/mutation_builder_fk.go#L76-L78](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt/optbuilder/mutation_builder_fk.go#L76-L78)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt/optbuilder/mutation_builder_fk.go#L636-L638](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt/optbuilder/mutation_builder_fk.go#L636-L638)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt/optbuilder/mutation_builder.go#L1433-L1435](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt/optbuilder/mutation_builder.go#L1433-L1435)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommandsAsync.func1 at line 310
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 900
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 2103
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 2186
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd.func1 at line 2181
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 141
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithProfiling at line 2986
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt.func1 at line 142
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 964
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchToExecutionEngine at line 1484
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).makeExecPlan at line 1978
pkg/sql/plan_opt.go in pkg/sql.(*planner).makeOptimizerPlan at line 240
pkg/sql/plan_opt.go in pkg/sql.(*optPlanningCtx).buildExecMemo at line 576
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).Build at line 246
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).buildStmtAtRoot at line 272
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).buildStmt at line 343
pkg/sql/opt/optbuilder/with.go in pkg/sql/opt/optbuilder.(*Builder).processWiths at line 116
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).buildStmt.func2 at line 344
pkg/sql/opt/optbuilder/insert.go in pkg/sql/opt/optbuilder.(*Builder).buildInsert at line 293
pkg/sql/opt/optbuilder/insert.go in pkg/sql/opt/optbuilder.(*mutationBuilder).buildInsert at line 685
pkg/sql/opt/optbuilder/mutation_builder_fk.go in pkg/sql/opt/optbuilder.(*mutationBuilder).buildFKChecksForInsert at line 77
pkg/sql/opt/optbuilder/mutation_builder_fk.go in pkg/sql/opt/optbuilder.(*fkCheckHelper).buildInsertionCheck at line 637
pkg/sql/opt/optbuilder/mutation_builder.go in pkg/sql/opt/optbuilder.(*mutationBuilder).buildCheckInputScan at line 1434
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v23.1.5 |
| Go Version | go1.19.10 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.5 |
| Cockroach SHA | 72556c6b5dc0d4ed1a0202bc4176586956d54739 |
| # of CPUs | 64 |
| # of Goroutines | 1084 |

Jira issue: CRDB-37361

**Comment by yuzefovich** [comment]
unactionable
