### ISSUE TITLE
beta-20161208

### ISSUE THREAD

**Issue by asubiotto** [cockroachdb/cockroach#12159]
The candidate SHA is a855534af60f59539cae2df3ee57c3f54f1fd5b3.

Release notes are under review in https://github.com/cockroachdb/docs/pull/911.

The build is running on gamma, delta, and rho.

[Release process checklist](https://github.com/cockroachdb/cockroach/wiki/Release-Process)
- [x] Check and verify cluster status
- [x] Tag release and push tag
- [x] [Trigger release build](https://teamcity.cockroachdb.com/viewType.html?buildTypeId=Cockroach_MergeToMaster)
- [x] Check and verify binaries
- [x] Announce version to the registration cluster - see internal production instructions
- [x] Update homebrew
- [x] Update docs
- [ ] External communications for release

**Comment by petermattis** [comment]
Let's bump the beta SHA to a855534af60f59539cae2df3ee57c3f54f1fd5b3 to capture @knz's fix.

**Comment by mberhault** [comment]
master build failed on acceptance test TestSingleKey (`single_key_test.go:111: storage/store.go:2354: rejecting command with timestamp in the future: 1481204668291242297 (712.186276ms ahead)`). kicking a new one

**Comment by jseldess** [comment]
@asubiotto, please give the release notes one final review, and then I'll publish: https://github.com/cockroachdb/docs/pull/914

**Comment by jseldess** [comment]
Release notes are live: https://www.cockroachlabs.com/docs/beta-20161208.html. @asubiotto, you can update homebrew, and @jess-edwards, we can send out announcements.

**Comment by jess-edwards** [comment]
Sent! Closing.
