### ISSUE TITLE
admission: roachtest for disk bandwidth limiter 

### ISSUE THREAD

**Issue by aadityasondhi** [cockroachdb/cockroach#121576]
We want a roachtest that does something similar to https://github.com/cockroachdb/cockroach/pull/82813#issuecomment-1183477491.

Jira issue: CRDB-37350

Epic CRDB-37479

**Comment by irfansharif** [comment]
An old attempt, partly salvageable: https://github.com/cockroachdb/cockroach/pull/109945.
