### ISSUE TITLE
Curious about a statement on ePaxos

### ISSUE THREAD

**Issue by danielmenzen** [cockroachdb/cockroach#12160]
Hi,

I'm a researcher/student testing consensus algorithms for a project.

I saw this statement on your [docs](https://github.com/cockroachdb/cockroach/blob/master/docs/design.md):

> ePaxos has promising performance characteristics for WAN-distributed replicas, but it does not guarantee a consistent ordering between replicas.

Can you please share more information about it?

Also, what do you exactly mean by 'consistent ordering'? I ask this because from what I understand the protocol should be consistent and the 'state' on all replicas should be the same at the "end".

I appreciate any information you can share.

Thank you very much!

**Comment by bdarnell** [comment]
In raft (as well as most paxos-derived algorithms), all commands are assigned a position in a single global ordering. This is why raft has a single leader (per term), which is responsible for assigning a log index to each proposed command. In ePaxos, on the other hand, any node can propose a command and a definite order is only assigned for commands that interfere with each other.

For example, given two transactions performing `INSERT INTO tbl VALUES ($1)` with different values of `$1`, two different replicas could see those transactions occur in different orders. But a query like `SELECT * FROM tbl` would be recognized as depending on the `INSERT` statements so it would force them to resolve to either before or after the `SELECT` statement. This dependency analysis is why ePaxos is much more complex to implement than other consensus algorithms (and has tricky interactions with things like read leases).
