### ISSUE TITLE
roachtest: retry `cockroach` download

### ISSUE THREAD

**Issue by rickystewart** [cockroachdb/cockroach#121738]
For example, [this](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_Tests_LocalRoachtest/14686696?buildTab=log&focusLine=2031&logView=flowAware&linesState=196.226.4464.4465) build failed due to a `cockroach` download failure:

```
tmpdir="$(mktemp -d /tmp/cockroach-release.XXX)" && \
dir=v23.2.3 && \
curl -f -s -S -o- https://storage.googleapis.com/cockroach-release-artifacts-prod/cockroach-v23.2.3.linux-amd64.tgz | tar xfz - -C "${tmpdir}" --strip-components 1 && \
mv ${tmpdir}/cockroach ${dir}/cockroach && \
mkdir -p ${dir}/lib && \
if [ -d ${tmpdir}/lib ]; then mv ${tmpdir}/lib/* ${dir}/lib; fi && \
chmod 755 ${dir}/cockroach

stdout: <empty>
stderr:curl: (56) OpenSSL SSL_read: Connection reset by peer, errno 104

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```

Jira issue: CRDB-37486

**Comment by srosenberg** [comment]
Thanks @rickystewart. This is going to be addressed soon as part of [1]. I am going to close this one out since it's a dupe.

[1] https://github.com/cockroachdb/cockroach/issues/88044

**Comment by renatolabs** [comment]
While we do pass those default retry options, the default `shouldRetryFn` only retries on SSH errors, which is not the case in these GCS errors:

https://github.com/cockroachdb/cockroach/blob/04e1faeb6b674729e989e001d37429786b584c6e/pkg/roachprod/install/cluster_synced.go#L115

So in the end staging is not retried. I agree that I don't think retrying will necessarily help much for the reason you mentioned (blips lasting longer than our typical retries).

That said, we _can_ retry staging on these as a best effort approach. Skipping the test could also be an option, but I'm slightly concerned about bugs in `stage` leading to tests being constantly skipped without us realizing.

**Comment by renatolabs** [comment]
I'll reopen it to add the retrying as a best-effort approach; I have a commit that will make that change, so I'll have that commit close this issue.

**Comment by rickystewart** [comment]
Indeed, simply marking the test would be acceptable. As long as it doesn't block CI, we're good.
