### ISSUE TITLE
ui: database details page fails to load for databases with many tables

### ISSUE THREAD

**Issue by xinhaoz** [cockroachdb/cockroach#121791]
The database details page fetches all table names for the given database. We currently don't use any pagination for the query fetching table names causing the page to fail to load if the db has many tables ([see slack thread](https://cockroachlabs.slack.com/archives/C069N0PH2PR/p1712176437890879?thread_ts=1712067692.179199&cid=C069N0PH2PR)).

**Potential Solution(s)**
Currenlty we are issuing the [query directly via sql over http](https://github.com/cockroachdb/cockroach/blob/2ff48a08a10a2715cde969e67c5ecf2b28debfe2/pkg/ui/workspaces/cluster-ui/src/api/databaseDetailsApi.ts#L172), however the [admin server's getTables](https://github.com/cockroachdb/cockroach/blob/a16fcaf21e40cb3bd61b09c010b4cf75e7c2ab0f/pkg/server/admin.go#L492) api seems to support pagination already. 

Jira issue: CRDB-37545

Epic CRDB-37558

**Comment by annrpom** [comment]
Seen https://github.com/cockroachlabs/support/issues/2870
