### ISSUE TITLE
After node decommission problem ranges report continue showing probles

### ISSUE THREAD

**Issue by sergeyshaykhullin** [cockroachdb/cockroach#121924]
**Describe the problem**

Alter node decommission some ranges from completely deleted(Drop + GC) table are reported as underreplicated + problem ranges report showing decommissioned node as live with error

**To Reproduce**

cockroach node decommission 70 --insecure

If possible, provide steps to reproduce the behavior:

I don't know completely why this happen, it is not reproducible

1. Create table
2. Populate data
3. Drop table
4. Wait for GC (Cluster has 10mins retention, node decommission happened after a week from table deletion)
5. Decommission node

**Expected behavior**

Node completely decommissioned with no stale ranges from deleted tables

**Additional data / screenshots**

![image](https://github.com/cockroachdb/cockroach/assets/46970457/05a49019-e9c5-483b-824b-c69df64c07c0)
![image](https://github.com/cockroachdb/cockroach/assets/46970457/f6ab566a-0bc7-48ce-84c5-7a42b737f702)
![image](https://github.com/cockroachdb/cockroach/assets/46970457/e782d08d-af4f-4446-8bd6-e7b740ba39e6)
Home page shows 23.2.3, but if i open table from db with deleted table with stale ranges crdb shows mixed versions
![image](https://github.com/cockroachdb/cockroach/assets/46970457/2d3238ab-068d-4902-bcec-c2d20cb5e06c)
![image](https://github.com/cockroachdb/cockroach/assets/46970457/a78ed32f-0403-4c25-a07c-7cf906bc901d)

**Environment:**
 - CockroachDB version v23.2.3
 - Server OS: [e.g. Linux/Distrib] Debian
 - Client app No matter

**Additional context**

Also full backups are stuck for db containing this table

Maybe i can manually enqueue this ranges for deletion or for replication?
![image](https://github.com/cockroachdb/cockroach/assets/46970457/f38545d5-daef-40ad-b440-b977ad9913e2)

Jira issue: CRDB-37624

**Comment by sergeyshaykhullin** [comment]
Also we have found running job with no progress for two months

![image](https://github.com/cockroachdb/cockroach/assets/46970457/7f9fed3d-384d-43b7-b73a-103e0896b213)

Empty traces
[trace.20240409_202056.10.zip](https://github.com/cockroachdb/cockroach/files/14923723/trace.20240409_202056.10.zip)

And empty stacks for goroutines

**Comment by fqazi** [comment]
This seems more KV related, so I'm going to let the comment on this. If help is needed from foundations let us know.

**Comment by sergeyshaykhullin** [comment]
https://github.com/cockroachdb/cockroach/issues/127988
