### ISSUE TITLE
backup: TestBackupAndRestoreJobDescription failed on CI

### ISSUE THREAD

**Issue by ajstorm** [cockroachdb/cockroach#121927]
When running CI for a backport I'm seeing TestBackupAndRestoreJobDescription fail on the 24.1 release branch.  More info [here](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelExtendedCi/14716244?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildProblemsSection=true&expandBuildTestsSection=true).

Jira issue: CRDB-37626

**Comment by msbutler** [comment]
skip on 24.1 landed. closing
