### ISSUE TITLE
sql: strange failure in TestIndexDoesNotStorePrimaryKeyColumnMixedVersion

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#121939]
I saw this failure on PR #121775:

https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelExtendedCi/14738344?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildProblemsSection=true&expandBuildTestsSection=true

```
	tdb.Exec(t, "INSERT INTO t VALUES (1,2,3);")
	require.Equal(t, [][]string{{"1", "2", "3"}}, tdb.QueryStr(t, "SELECT * FROM t;"))
```

This is very strange - we successfully insert into the table but then the data isn't there.

I could not repro locally under stress.

Jira issue: CRDB-37631

**Comment by fqazi** [comment]
We should try to repro this again and if we don't have any luck then this can be closed.

**Comment by fqazi** [comment]
This wasn't reproducible. Based on what this scenario is testing the corruption only impacts the secondary index, so its unusual the primary index was impacted. Lets see if this shows up again

**Comment by michae2** [comment]
Saw this again here: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelExtendedCi/14957664?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildProblemsSection=true&expandBuildChangesSection=true&expandBuildTestsSection=true
