### ISSUE TITLE
sql: Consider supporting a version of rename table that lets you replace a different table

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#12195]
The idea is that syntax along the lines of `ALTER TABLE foo REPLACE WITH bar` would allow you to atomically drop `foo` and rename `bar` to `foo`. This came up in discussion on #12158 ([direct comment link](https://reviewable.io/reviews/cockroachdb/cockroach/12158#-KYSwldAP3lqW53WVgl6:-KYV8M3Y7xrpvRRsuMnu:bpi94sp)), in which we want to replace `system.eventlog` with a table that only differs in one of the primary key columns.

Alternatively, fixing #12123 such that a user could DROP a table and RENAME over it within a transaction would basically make this pointless.

I don't think we should do this unless other situations come up in which the same idea arises, but I want to make sure we at least track such situations so we can notice the pattern if it arises.

**Comment by lucy-zhang** [comment]
Closing in favor of #54562, which we intend to fix for 21.1.
