### ISSUE TITLE
o11y: unavailable ranges in console is coloured green

### ISSUE THREAD

**Issue by ajstorm** [cockroachdb/cockroach#122014]
On the `drt-large` cluster we're in the process of recovering from a cluster outage.  As a result, there are some unavailable ranges.  In the summary on the metric page we see this:

<img width="390" alt="image" src="https://github.com/cockroachdb/cockroach/assets/18447034/6f4cf0b2-e538-44da-9c63-7d27069b2d5d">

What's odd about this is that there are 3K unavailable ranges, and yet the font is green.  I'd think that for any number of unavailable ranges, this should be coloured red.

Jira issue: CRDB-37664

**Comment by krishnakeshan** [comment]
@ajstorm @nkodali if nobody is working on this can I pick it up?

**Comment by theloneexplorerquest** [comment]
Hi @ajstorm , I would like to work on this issue. Is it still available? 😊

**Comment by theloneexplorerquest** [comment]
I think I have found where the issue is:
https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/db-console/src/views/shared/components/summaryBar/summarybar.styl#L101
Looks like this number is always good no matter what input number is. I will raise a PR soon.
