### ISSUE TITLE
streamproducer: infinite retry on unrecoverable error

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#122002]
We don't call `WithRetry` (nobody does) so we don't limit the number of retries, so we'll just retry forever on an unrecoverable error.

We should be careful when changing this as currently scanner.go, if it breaks from its retry loop for any reason (success or max attempts) will be treated as success.

Jira issue: CRDB-37658

**Comment by stevendanna** [comment]
@dt assigned to you as I believe I just reviewed a PR where you fixed this.
