### ISSUE TITLE
Inconsistent results by the hint LOOKUP

### ISSUE THREAD

**Issue by sayJason** [cockroachdb/cockroach#122092]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**
Run the following statements.
```sql
CREATE TABLE t1 (c1 INTERVAL DAY TO SECOND NULL PRIMARY KEY);
CREATE TABLE t2 (c1 INTERVAL MONTH);
INSERT INTO t2 (c1) VALUES ((INTERVAL '58017 year 4 months 7 days 8 hours 42 minutes 16 seconds'));
SELECT t1.c1 FROM t2 LEFT OUTER HASH JOIN t1 USING (c1); -- {null}
SELECT t1.c1 FROM t2 LEFT OUTER LOOKUP JOIN t1 USING (c1); -- ERROR: overflow during Encode
```

**Expected behavior**
I expect that the second query should also return {null}.

**Environment:**
Server version: CockroachDB CCL v23.2.2 (x86_64-pc-linux-gnu, built 2024/02/26 21:06:09, go1.21.5 X:nocoverageredesign) (same version as client)

Jira issue: CRDB-37696

**Comment by yuzefovich** [comment]
Thanks for filing this issue! I think it's a dup of #45993.
