### ISSUE TITLE
sql: regression in TPCH Q2

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#122070]
I noticed that we had a big regression on TPCH Q2 between 22.2 and 24.1. In `tpchvec/perf` roachtest it used to take about 0.22s, and now it takes about 2.01s - 8x regression.

There was only a single change to the plan in #92378 which is likely the root cause.

Jira issue: CRDB-37685

**Comment by DrewKimball** [comment]
Relevant comment from #92378: https://github.com/cockroachdb/cockroach/pull/92378#issuecomment-1332742252

**Comment by yuzefovich** [comment]
Oh, ok, thanks, let's close this as expected regression then.
