### ISSUE TITLE
restore database failed

### ISSUE THREAD

**Issue by wuwo1952368901** [cockroachdb/cockroach#122170]
CockroachDB version 23.2.2 

Restoring database error with REVERTING prompt. Restore failed. Database cannot be deleted or accessed, error message:

ERROR: internal error while retreving user account memberships: internal error while retrieving user account: get default settings error: database "xxxxxxxxx" is offline: restoring
ERROR: node is running secure mode, SSL connection required

Jira issue: CRDB-37738

**Comment by yuzefovich** [comment]
dup of #122168
