### ISSUE TITLE
storage: fix and re-enable multi-level compactions

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/cockroach#122138]
Multi-level compactions were disabled due to excessively large compactions which could starve out compactions. We will fix the heuristics to avoid excessively large compactions and re-enable multi-level compactions.

We’ll want to:

fix the heuristic bug that allows excessively large compactions

perform some compaction benchmarking to validate that there still exists some write-amp benefit to the current multi-level heuristics

Iterating on the multi-level heuristics to further reduce write amp is out of scope.

See cockroachdb/pebble#3120.

Jira issue: CRDB-37723

Epic CRDB-37583

**Comment by itsbilal** [comment]
This was fixed in #131378.
