### ISSUE TITLE
sql: Conduct upgrade testing session based leasing

### ISSUE THREAD

**Issue by rimadeodhar** [cockroachdb/cockroach#122253]
To ensure our transition from expiry based leases to session based leasing using sqlliveness, we should test the upgrade path which performs the system table migration (locally or through DRT). Additionally, we should continuously monitor the new lease health metrics that we added both on DRT and on our SLI dashboards.
This testing should cover:
- A full upgrade.
- Intentionally, put the cluster in a bad state and leverage the killswitch to fallback to the old expiry based behavior. The steps taken here to pull the cluster out of the bad state should also be updated in our runbooks.

Jira issue: CRDB-37775

Epic CRDB-37769

**Comment by fqazi** [comment]
Worked with @itsbilal to validate this. The session based leasing migration and safety switch were both validated.
