### ISSUE TITLE
sql: Test schema changes on DRT

### ISSUE THREAD

**Issue by rimadeodhar** [cockroachdb/cockroach#122251]
We should manually test the new schema change statements we added to the declarative schema changer on DRT. We can leverage the operations framework for this.

New schema statements added to the DSC:
- CREATE SCHEMA
- CREATE SEQUENCE
- CREATE DATABASE
- ALTER TABLE x ALTER COLUMN y DROP DEFAULT
- ALTER COLUMN SET DEFAULT
- Add virtual column with a not null constraint.

Jira issue: CRDB-37773

Epic CRDB-37769

**Comment by rafiss** [comment]
I've done manual testing for the CREATE statements. And I added more coverage to the ALTER operation in https://github.com/cockroachdb/cockroach/pull/123424.
