### ISSUE TITLE
sql: workload testing on serverless

### ISSUE THREAD

**Issue by rimadeodhar** [cockroachdb/cockroach#122248]
This is an exploratory action item to run a one-off sql schema workload on serverless to test the following features:

- Timeouts for region liveness
- Confirm backups and restores work as expected for system tables marked as `exclude_data_from_backup` on serverless.

Jira issue: CRDB-37770

Epic CRDB-37769

**Comment by fqazi** [comment]
Had a live session with Jeff where we confirmed that this works on a serverless cluster. We did find one issue with region_liveness, so going to open a new issue for it: https://github.com/cockroachdb/cockroach/issues/122927
