### ISSUE TITLE
plpgsql: concerning behavior with `pg_sleep` in the loop

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#122318]
Consider this reproduction:
```sql
DROP PROCEDURE IF EXISTS p;
CREATE PROCEDURE p() LANGUAGE PLpgSQL AS $$
<<outer>>
DECLARE
   x INT = 0;
BEGIN
   LOOP
       x = x + 1;
       <<inner>>
       DECLARE
           y INT = x + 1;
           t TIMESTAMP := now();
           b TEXT;
       BEGIN
           RAISE NOTICE '%: x=% y=%', t, x, y;
           SELECT pg_sleep(0.5) INTO b;
       END inner;
       EXIT WHEN x > 3;
   END LOOP;
END outer;
$$;
CALL p();
```
It returns effectively immediately on CRDB but takes honest 2s on PG.

Relatedly, this reproduction:
```sql
DROP PROCEDURE IF EXISTS p;
CREATE PROCEDURE p() LANGUAGE PLpgSQL AS $$
DECLARE
   x INT = 0;
   b TEXT;
BEGIN
   LOOP
       x = x + 1;
       RAISE NOTICE '%: x=%', now(), x;
       SELECT pg_sleep(0.5) INTO b;
       EXIT WHEN x > 3;
   END LOOP;
END;
$$;
CALL p();
```
takes only 1.5s on CRDB (it should take 2s).

My guess is that whenever `pg_sleep` is in tail call position, it is optimized away. I wonder whether we're incorrectly propagating some function properties in such scenario.

Jira issue: CRDB-37799

**Comment by DrewKimball** [comment]
This is happening because of column-pruning rules. We need to place a barrier after projecting a variable if its expression is volatile.
