### ISSUE TITLE
roachtest: cdc/kafka-oauth failed

### ISSUE THREAD

**Issue by renatolabs** [cockroachdb/cockroach#122456]
I'm creating this issue manually because `hydra` fails with status 255, which is the same exit code we use to identify SSH flakes. In this case, however, the failure is not an SSH flake, but a legitimate test failure (thankfully, it seems like this is just a test bug).

For artifacts, see https://github.com/cockroachdb/cockroach/issues/90695#issuecomment-2051503141 and subsequent failures in the following runs.

The error happens when the following command is executed:

```
run_111029.305694316_n4_homeubuntuhydra-crea: 11:10:29 cluster.go:2432: > /home/ubuntu/hydra create oauth2-client -e http://localhost:4445 --grant-type client_credentials --token-endpoint-auth-method client_secret_basic --name "Test Client"
teamcity-14856548-1713246668-46-n4cpu4:[4]: /home/ubuntu/hydra create o...
Error: Post "http://localhost:4445/admin/clients": dial tcp 127.0.0.1:4445: connect: connection refused
Usage:
  hydra create oauth2-client [flags]
```

It seems that we should wait for the admin interface to be up before attempting to call this command.

Jira issue: CRDB-37895

**Comment by renatolabs** [comment]
Added GA-blocker label as we likely want this test passing before GA to avoid any blind spots in this area.

**Comment by rharding6373** [comment]
I have a fix for this in review, and have verified that the test now passes. It's a test only change to put this command in a retry loop. I don't think this should hold up a branch cut, so I'm going to remove the GA blocker label now.
