### ISSUE TITLE
sql: special case USING with non-outer joins to reduce data traffic

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#12250]
Suggested by @RaduBerinde in https://github.com/cockroachdb/cockroach/pull/12240#issuecomment-266176256,  regarding the handling of `SELECT x FROM a JOIN b USING(x)`.

Currently the code defines 3 data source columns, one for `a.x`, one for `b.x` and *also* one for the join column in the USING clause. This is necessary for outer joins, because in outer join the value of the join column may become different from that of the join operands, and the SELECT must be able to render either.

However, in the case of inner joins this can be optimized further, by not defining the join column and instead defining an additional table-less alias for the relevant source operands. So the data source would only present `a.x` and `b.x` but the table-less name `x` can resolve to `a.x`.

**Comment by knz** [comment]
@RaduBerinde I think we've achieved this already right?

**Comment by RaduBerinde** [comment]
Yeah, a while ago.
