### ISSUE TITLE
prod: gossip node configuration and create admin RPC to retrieve it

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#12252]
Suggested in  #12157: it would be useful if a user could capture in one action the configuration of all nodes, including the command-line parameters used to start them and the environment variables that influence node execution.

To achieve this, a query on any one node must be able to gather data about all other nodes in addition to itself; that means the configuration should be gossiped.

The once the information is gossiped, it should be exposed via a (new) admin RPC.

**Comment by a6802739** [comment]
@knz, I want to have a see on it.

**Comment by petermattis** [comment]
Another implementation option: we have several admin endpoints that fan out queries to all nodes. For example, `Admin.TableStats`.

**Comment by knz** [comment]
`cockroach zip` does this now
