### ISSUE TITLE
ui: change the newsletter subscription help text

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#12256]
Currently under the check box "Send me product and feature updates" there is a message "You will not be able to deselect this option from the Admin UI."

This is rather unhelpful and could freak privacy-conscious users out.

A better text: "Once you have selected this option, please contact us directly if you wish to unsubscribe."

**Comment by dianasaur323** [comment]
I think this actually gets unsubscribed in Hubspot. @jess-edwards can comment if that's incorrect. So the text could be - "Once you have selected this option, you can only unsubscribe directly in product and feature update emails." Or something along those lines. This UI is getting reworked as it becomes more of a "support" page. Adding @kuanluo so she can incorporate this feedback in her work.

**Comment by kuanluo** [comment]
Yup, this page is going to be more like "support" hub onward, so the text won't be there. :) Closing the issue. :)
