### ISSUE TITLE
Set ttl_delete_rate_limit to 100 instead of current 0 (unlimited)

### ISSUE THREAD

**Issue by dikshant** [cockroachdb/cockroach#122698]
Currently the delete rate limit is set to 0. This can cause adverse impact to foreground latency. A quick survey of our customer indicates most have a value of around 100. In any case a bounded value would be better than the current unlimited.

We should set this for only newly TTL enabled tables. Existing tables that have ttl should have their defaults be at 0 to prevent confusions around "why is my TTL job slow after upgrade?"

Jira issue: CRDB-38030

Epic CRDB-18322

**Comment by rafiss** [comment]
There are plans to integrate TTL with disk I/O limiting: https://github.com/cockroachdb/cockroach/issues/121782

Maybe we can just change the default on older branches, and leave master at `0` for right now. That way, it will be easier to see if disk AC is having the desired effects on master. We can decide when 24.2 is being cut if we want it to also have a limit of 100.
