### ISSUE TITLE
server: bad certificate error spams the logs

### ISSUE THREAD

**Issue by ajstorm** [cockroachdb/cockroach#122622]
We recently recreated the drt-large cluster but accidentally forgot to stop the workload cluster which was feeding it.  As a result, the workload cluster contained mismatched certificates which wouldn't allow a SQL connection.  This is all fine. 

What's bad is that when running the old workload setup against the new cluster, the logs get spammed with this message:

```
E240418 12:56:19.337038 118941573 1@server/server_sql.go:1872 ⋮ [T1,Vsystem,n19,client=‹34.95.61.134:40008›] 41238547  serving SQL client conn: remote error: ‹tls: bad certificate›
```

The log message gets written to the logs more than 500 times per second, and as a result, fills up a 10MB log file twice per minute (thus wrapping the logs _very_ quickly).  It would be better if we only printed this log message periodically as we're receiving these connection requests.

Jira issue: CRDB-38004

**Comment by vishgupt** [comment]
Hi @ajstorm, I want to work on this as my first issue. Can you provide more details about the expected behavior for this log message?

**Comment by ajstorm** [comment]
Hi @vishgupt.  Thanks for reaching out.

I believe we'll want to wrap this log message in a `log.Every`, as is done in [this](https://github.com/cockroachdb/cockroach/pull/117977/files) PR.

**Comment by AidanXu** [comment]
Hey, @ajstorm, could I work on this as my first issue?

**Comment by amitrahman1026** [comment]
Hey, @ajstorm, apologies for the multiple mentions. Saw this was getting a little stale because it seemed like @AidanXu missed out on linting, so I went ahead and did that
