### ISSUE TITLE
sql: slow query log does not report cancellation error code

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#122722]
**Describe the problem**

The slow query log includes error codes for slow queries. The error code is incorrect for queries that timed out due to `statement_timeout` or that were canceled explicitly.

**To Reproduce**

```
root@localhost:26257/defaultdb> SET CLUSTER SETTING sql.log.slow_query.latency_threshold = '500ms';
SET CLUSTER SETTING

root@localhost:26257/defaultdb> select pg_sleep(1);
  pg_sleep
------------
     t
(1 row)

root@localhost:26257/defaultdb> select pg_sleep(10);
^C  # this is me pressing Ctrl-C to cancel the query

attempting to cancel query...
ERROR: query execution canceled
SQLSTATE: 57014

root@localhost:26257/defaultdb> set statement_timeout = '2s';
SET

root@localhost:26257/defaultdb> select pg_sleep(10);
ERROR: query execution canceled due to statement timeout
SQLSTATE: 57014
```

Now open `cockroach-sql-slow.log`. It contains:
```
I240419 21:52:58.263697 707131 10@util/log/event_log.go:32 ⋮ [T1,Vsystem,n1,client=127.0.0.1:58837,hostnossl,user=root] 1 ={"Timestamp":1713563577261449000,"EventType":"slow_query","Statement":"SELECT pg_sleep(‹1.0›)","Tag":"SELECT","User":"root","ApplicationName":"$ cockroach sql","ExecMode":"exec","NumRows":1,"Age":1001.2132,"TxnCounter":8,"StmtPosInTxn":1}
I240419 21:53:30.362793 707131 10@util/log/event_log.go:32 ⋮ [T1,Vsystem,n1,client=127.0.0.1:58837,hostnossl,user=root] 2 ={"Timestamp":1713563607446246000,"EventType":"slow_query","Statement":"SELECT pg_sleep(‹10.0›)","Tag":"SELECT","User":"root","ApplicationName":"$ cockroach sql","ExecMode":"exec","SQLSTATE":"XXUUU","ErrorText":"pg_sleep(): context canceled","Age":2916.5344,"TxnCounter":10,"StmtPosInTxn":1}
I240419 21:54:45.471589 707131 10@util/log/event_log.go:32 ⋮ [T1,Vsystem,n1,client=127.0.0.1:58837,hostnossl,user=root] 3 ={"Timestamp":1713563683468890000,"EventType":"slow_query","Statement":"SELECT ‹pg_sleep›(‹10›)","Tag":"SELECT","User":"root","ApplicationName":"$ cockroach sql","ExecMode":"exec","SQLSTATE":"XXUUU","ErrorText":"pg_sleep(): context canceled","Age":2002.7068,"TxnCounter":14,"StmtPosInTxn":1}
```

**Expected behavior**

The first line in those logs is correct. But the latter 2 should have an error code of `57014` (instead of `XXUUU`).

**Environment:**
Tested this on v23.2.1, but all versions are affected.

**Additional context**
The issue is that the error code is added here https://github.com/cockroachdb/cockroach/blob/e9d1b467fbe5a2e6751f4eaf39d95c43f7c89068/pkg/sql/conn_executor_exec.go#L479-L484

and here https://github.com/cockroachdb/cockroach/blob/e9d1b467fbe5a2e6751f4eaf39d95c43f7c89068/pkg/sql/conn_executor_exec.go#L522-L529

That error rewriting logic is in `execStmtInOpenState`. The slow query log is written in `dispatchToExecutionEngine`. Since `execStmtInOpenState` is a caller of `dispatchToExecutionEngine`, that means the error code is only added after the log is written.

see https://cockroachlabs.slack.com/archives/C06PEGL22UX/p1713373695222239?thread_ts=1713193977.393989&cid=C06PEGL22UX

Jira issue: CRDB-38034

Epic CRDB-38033

**Comment by rimadeodhar** [comment]
Moving to the observability team as discussed with @nkodali

**Comment by xinhaoz** [comment]
I tested this out today and it looks like we can move the logging into `execOpenState` fine. There's some nuances with pausible portals and preserving the order of cleanup operations. Overall should be doable, hoping to get a PR out this week.
