### ISSUE TITLE
Sentry: error.go:89: unexpected error from the vectorized engine: runtime error: slice bounds out of range [:325] with capacity 168
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack tra...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#122797]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5237653189/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5237653189/?referrer=webhooks_plugin)

Panic Message:

```
error.go:89: unexpected error from the vectorized engine: runtime error: slice bounds out of range [:325] with capacity 168
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:89
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.InternalError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:195
  | github.com/cockroachdb/cockroach/pkg/sql/colflow/colrpc.(*Inbox).Next.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/colrpc/inbox.go:329
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | runtime.goPanicSliceAcap
  | 	GOROOT/src/runtime/panic.go:139
  | github.com/apache/arrow/go/arrow/array.(*Int64).setData
  | 	github.com/apache/arrow/go/arrow/array/external/com_github_apache_arrow_go_arrow/array/numeric.gen.go:79
  | github.com/apache/arrow/go/arrow/array.NewInt64Data
  | 	github.com/apache/arrow/go/arrow/array/external/com_github_apache_arrow_go_arrow/array/numeric.gen.go:38
  | github.com/cockroachdb/cockroach/pkg/col/colserde.(*ArrowBatchConverter).ArrowToBatch
  | 	github.com/cockroachdb/cockroach/pkg/col/colserde/arrowbatchconverter.go:521
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils.(*Deserializer).Deserialize.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils/deserializer.go:74
  | github.com/cockroachdb/cockroach/pkg/sql/colmem.(*Allocator).PerformOperation
  | 	github.com/cockroachdb/cockroach/pkg/sql/colmem/allocator.go:460
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils.(*Deserializer).Deserialize
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils/deserializer.go:73
  | github.com/cockroachdb/cockroach/pkg/sql/colflow/colrpc.(*Inbox).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/colrpc/inbox.go:409
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:118
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:126
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*OrderedSynchronizer).Next
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/colexec/ordered_synchronizer.eg.go:119
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:118
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:126
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*UnorderedDistinct).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/unordered_distinct.go:98
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk.(*diskSpillerBase).Next.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk/disk_spiller.go:202
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk.(*diskSpillerBase).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk/disk_spiller.go:200
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*limitOp).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/limit.go:47
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:118
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:126
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Materializer).next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:247
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Materializer).nextAdapter
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:272
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Materializer).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:278
Wraps: (3) unexpected error from the vectorized engine
Wraps: (4) runtime error: slice bounds out of range [:325] with capacity 168
  | -- cause hidden behind barrier
  | runtime error: slice bounds out of range [:325] with capacity 168
  | (1) attached stack trace
  |   -- stack trace:
  |   | github.com/cockroachdb/cockroach/pkg/sql/colflow/colrpc.(*Inbox).Next.func1
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/colrpc/inbox.go:324
  |   | runtime.gopanic
  |   | 	GOROOT/src/runtime/panic.go:884
  |   | runtime.goPanicSliceAcap
  |   | 	GOROOT/src/runtime/panic.go:139
  |   | github.com/apache/arrow/go/arrow/array.(*Int64).setData
  |   | 	github.com/apache/arrow/go/arrow/array/external/com_github_apache_arrow_go_arrow/array/numeric.gen.go:79
  |   | github.com/apache/arrow/go/arrow/array.NewInt64Data
  |   | 	github.com/apache/arrow/go/arrow/array/external/com_github_apache_arrow_go_arrow/array/numeric.gen.go:38
  |   | github.com/cockroachdb/cockroach/pkg/col/colserde.(*ArrowBatchConverter).ArrowToBatch
  |   | 	github.com/cockroachdb/cockroach/pkg/col/colserde/arrowbatchconverter.go:521
  |   | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils.(*Deserializer).Deserialize.func1
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils/deserializer.go:74
  |   | github.com/cockroachdb/cockroach/pkg/sql/colmem.(*Allocator).PerformOperation
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colmem/allocator.go:460
  |   | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils.(*Deserializer).Deserialize
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils/deserializer.go:73
  |   | github.com/cockroachdb/cockroach/pkg/sql/colflow/colrpc.(*Inbox).Next
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/colrpc/inbox.go:409
  |   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).next
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:118
  |   | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  |   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).Next
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:126
  |   | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*OrderedSynchronizer).Next
  |   | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/colexec/ordered_synchronizer.eg.go:119
  |   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).next
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:118
  |   | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  |   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).Next
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:126
  |   | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*UnorderedDistinct).Next
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/unordered_distinct.go:98
  |   | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk.(*diskSpillerBase).Next.f...
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colexec/materializer.go#L277-L279](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colexec/materializer.go#L277-L279)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colexec/materializer.go#L271-L273](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colexec/materializer.go#L271-L273)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colexec/materializer.go#L246-L248](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colexec/materializer.go#L246-L248)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colflow/stats.go#L125-L127](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colflow/stats.go#L125-L127)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colflow/stats.go#L117-L119](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colflow/stats.go#L117-L119)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colexec/limit.go#L46-L48](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colexec/limit.go#L46-L48)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colexec/colexecdisk/disk_spiller.go#L199-L201](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colexec/colexecdisk/disk_spiller.go#L199-L201)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colexec/colexecdisk/disk_spiller.go#L201-L203](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colexec/colexecdisk/disk_spiller.go#L201-L203)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colexec/unordered_distinct.go#L97-L99](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colexec/unordered_distinct.go#L97-L99)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colflow/stats.go#L125-L127](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colflow/stats.go#L125-L127)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colflow/stats.go#L117-L119](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colflow/stats.go#L117-L119)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/bazel-out/k8-opt/bin/pkg/sql/colexec/ordered_synchronizer.eg.go#L118-L120](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/bazel-out/k8-opt/bin/pkg/sql/colexec/ordered_synchronizer.eg.go#L118-L120)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colflow/stats.go#L125-L127](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colflow/stats.go#L125-L127)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colflow/stats.go#L117-L119](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colflow/stats.go#L117-L119)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colflow/colrpc/inbox.go#L408-L410](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colflow/colrpc/inbox.go#L408-L410)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colexec/colexecutils/deserializer.go#L72-L74](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colexec/colexecutils/deserializer.go#L72-L74)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colmem/allocator.go#L459-L461](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colmem/allocator.go#L459-L461)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colexec/colexecutils/deserializer.go#L73-L75](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colexec/colexecutils/deserializer.go#L73-L75)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/col/colserde/arrowbatchconverter.go#L520-L522](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/col/colserde/arrowbatchconverter.go#L520-L522)
[github.com/apache/arrow/go/arrow/array/external/com_github_apache_arrow_go_arrow/array/numeric.gen.go#L37-L39](github.com/apache/arrow/go/arrow/array/external/com_github_apache_arrow_go_arrow/array/numeric.gen.go#L37-L39)
[github.com/apache/arrow/go/arrow/array/external/com_github_apache_arrow_go_arrow/array/numeric.gen.go#L78-L80](github.com/apache/arrow/go/arrow/array/external/com_github_apache_arrow_go_arrow/array/numeric.gen.go#L78-L80)
[GOROOT/src/runtime/panic.go#L138-L140](GOROOT/src/runtime/panic.go#L138-L140)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colflow/colrpc/inbox.go#L328-L330](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colflow/colrpc/inbox.go#L328-L330)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colexecerror/error.go#L194-L196](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colexecerror/error.go#L194-L196)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colexecerror/error.go#L88-L90](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colexecerror/error.go#L88-L90)
</details>

```
pkg/sql/colexec/materializer.go in pkg/sql/colexec.(*Materializer).Next at line 278
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colexec/materializer.go in pkg/sql/colexec.(*Materializer).nextAdapter at line 272
pkg/sql/colexec/materializer.go in pkg/sql/colexec.(*Materializer).next at line 247
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).Next at line 126
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).next at line 118
pkg/sql/colexec/limit.go in pkg/sql/colexec.(*limitOp).Next at line 47
pkg/sql/colexec/colexecdisk/disk_spiller.go in pkg/sql/colexec/colexecdisk.(*diskSpillerBase).Next at line 200
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colexec/colexecdisk/disk_spiller.go in pkg/sql/colexec/colexecdisk.(*diskSpillerBase).Next.func1 at line 202
pkg/sql/colexec/unordered_distinct.go in pkg/sql/colexec.(*UnorderedDistinct).Next at line 98
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).Next at line 126
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).next at line 118
bazel-out/k8-opt/bin/pkg/sql/colexec/ordered_synchronizer.eg.go in pkg/sql/colexec.(*OrderedSynchronizer).Next at line 119
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).Next at line 126
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).next at line 118
pkg/sql/colflow/colrpc/inbox.go in pkg/sql/colflow/colrpc.(*Inbox).Next at line 409
pkg/sql/colexec/colexecutils/deserializer.go in pkg/sql/colexec/colexecutils.(*Deserializer).Deserialize at line 73
pkg/sql/colmem/allocator.go in pkg/sql/colmem.(*Allocator).PerformOperation at line 460
pkg/sql/colexec/colexecutils/deserializer.go in pkg/sql/colexec/colexecutils.(*Deserializer).Deserialize.func1 at line 74
pkg/col/colserde/arrowbatchconverter.go in pkg/col/colserde.(*ArrowBatchConverter).ArrowToBatch at line 521
github.com/apache/arrow/go/arrow/array/external/com_github_apache_arrow_go_arrow/array/numeric.gen.go in github.com/apache/arrow/go/arrow/array.NewInt64Data at line 38
github.com/apache/arrow/go/arrow/array/external/com_github_apache_arrow_go_arrow/array/numeric.gen.go in github.com/apache/arrow/go/arrow/array.(*Int64).setData at line 79
GOROOT/src/runtime/panic.go in runtime.goPanicSliceAcap at line 139
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
pkg/sql/colflow/colrpc/inbox.go in pkg/sql/colflow/colrpc.(*Inbox).Next.func1 at line 329
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.InternalError at line 195
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1 at line 89
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v23.1.19 |
| Go Version | go1.19.13 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.19 |
| Cockroach SHA | 1bca2adcbc1deb23067e28369f8b24c99194f2bb |
| # of CPUs | 36 |
| # of Goroutines | 830 |

Jira issue: CRDB-38075

**Comment by yuzefovich** [comment]
unactionable - dup of #70615
