### ISSUE TITLE
ui: update graphs on Admin UI to mirror Grafana

### ISSUE THREAD

**Issue by kuanluo** [cockroachdb/cockroach#12279]
@mrtracy and I met with @petermattis to discuss what graphs/sections are important to bring over to our Admin UI, and here are the action items:

#### Phase 1: all graphs from the following Grafana dashboards
- [x] Runtime 
- [x] SQL
- [x] Slow request
- [x] Storage
- [x] Replicas
- [x] Queues 

#### Phase 2: 
- [ ] Raft 
- [ ] Gossip
- [ ] Mutex

cc @dianasaur323

**Comment by mrtracy** [comment]
I'm going to close this, we have already made the switch and I don't think the "phase 2" portion of this is an actual requirement. Any additional graphs can be transferred on an individual basis.
