### ISSUE TITLE
sql: v23.1.19: zero transaction timestamp in EvalContext

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#122888]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5242691186/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5242691186/?referrer=webhooks_plugin)

Panic Message:

```
context.go:631: zero transaction timestamp in EvalContext
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/sem/eval.(*Context).GetTxnTimestamp
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/eval/context.go:631
  | github.com/cockroachdb/cockroach/pkg/sql/sem/builtins.glob..func174
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/builtins/builtins.go:3328
  | github.com/cockroachdb/cockroach/pkg/sql/sem/builtins.stringOverload1.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/builtins/builtins.go:9214
  | github.com/cockroachdb/cockroach/pkg/sql/sem/eval.(*evaluator).EvalFuncExpr
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/eval/expr.go:483
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FuncExpr).Eval
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/sem/tree/eval_expr_generated.go:276
  | github.com/cockroachdb/cockroach/pkg/sql/sem/eval.(*evaluator).EvalComparisonExpr
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/eval/expr.go:253
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*ComparisonExpr).Eval
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/sem/tree/eval_expr_generated.go:121
  | github.com/cockroachdb/cockroach/pkg/sql/sem/eval.(*evaluator).EvalOrExpr
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/eval/expr.go:562
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*OrExpr).Eval
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/sem/tree/eval_expr_generated.go:326
  | github.com/cockroachdb/cockroach/pkg/sql/sem/eval.Expr
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/eval/expr.go:26
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/schemaexpr.deserializeExprForFormatting
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/schemaexpr/expr.go:356
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/schemaexpr.formatExprForDisplayImpl
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/schemaexpr/expr.go:294
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/schemaexpr.FormatExprForDisplay
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/schemaexpr/expr.go:251
  | github.com/cockroachdb/cockroach/pkg/sql.populateTableConstraints
  | 	github.com/cockroachdb/cockroach/pkg/sql/pg_catalog.go:1077
  | github.com/cockroachdb/cockroach/pkg/sql.makeAllRelationsVirtualTableWithDescriptorIDIndex.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/pg_catalog.go:1248
  | github.com/cockroachdb/cockroach/pkg/sql.(*virtualDefEntry).makeConstrainedRowsGenerator.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/virtual_schema.go:827
  | github.com/cockroachdb/cockroach/pkg/sql.(*vTableLookupJoinNode).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/virtual_table.go:317
  | github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:220
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*FlowCoordinator).next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:128
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*FlowCoordinator).nextAdapter
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:145
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*FlowCoordinator).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:150
  | github.com/cockroachdb/cockroach/pkg/sql/execinfra.Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/execinfra/base.go:193
  | github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBaseNoHelper).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:726
  | github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:580
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:313
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:902
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1895
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll.func3
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1627
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1630
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2210
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1764
Wraps: (3) zero transaction timestamp in EvalContext
Error types: (1) *assert.withAssertionFailure (2) *withstack.withStack (3) *errutil.leafError
-- report composition:
*errutil.leafError: zero transaction timestamp in EvalContext
context.go:631: *withstack.withStack (top exception)
*assert.withAssertionFailure
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/conn_executor_exec.go#L1763-L1765](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/conn_executor_exec.go#L1763-L1765)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/conn_executor_exec.go#L2209-L2211](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/conn_executor_exec.go#L2209-L2211)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/distsql_running.go#L1629-L1631](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/distsql_running.go#L1629-L1631)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/distsql_running.go#L1626-L1628](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/distsql_running.go#L1626-L1628)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/distsql_running.go#L1894-L1896](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/distsql_running.go#L1894-L1896)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/distsql_running.go#L901-L903](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/distsql_running.go#L901-L903)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colflow/vectorized_flow.go#L312-L314](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colflow/vectorized_flow.go#L312-L314)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/flowinfra/flow.go#L579-L581](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/flowinfra/flow.go#L579-L581)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/execinfra/processorsbase.go#L725-L727](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/execinfra/processorsbase.go#L725-L727)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/execinfra/base.go#L192-L194](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/execinfra/base.go#L192-L194)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colflow/flow_coordinator.go#L149-L151](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colflow/flow_coordinator.go#L149-L151)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colflow/flow_coordinator.go#L144-L146](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colflow/flow_coordinator.go#L144-L146)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colflow/flow_coordinator.go#L127-L129](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colflow/flow_coordinator.go#L127-L129)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/plan_node_to_row_source.go#L219-L221](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/plan_node_to_row_source.go#L219-L221)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/virtual_table.go#L316-L318](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/virtual_table.go#L316-L318)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/virtual_schema.go#L826-L828](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/virtual_schema.go#L826-L828)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/pg_catalog.go#L1247-L1249](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/pg_catalog.go#L1247-L1249)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/pg_catalog.go#L1076-L1078](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/pg_catalog.go#L1076-L1078)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/catalog/schemaexpr/expr.go#L250-L252](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/catalog/schemaexpr/expr.go#L250-L252)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/catalog/schemaexpr/expr.go#L293-L295](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/catalog/schemaexpr/expr.go#L293-L295)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/catalog/schemaexpr/expr.go#L355-L357](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/catalog/schemaexpr/expr.go#L355-L357)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/sem/eval/expr.go#L25-L27](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/sem/eval/expr.go#L25-L27)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/bazel-out/k8-opt/bin/pkg/sql/sem/tree/eval_expr_generated.go#L325-L327](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/bazel-out/k8-opt/bin/pkg/sql/sem/tree/eval_expr_generated.go#L325-L327)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/sem/eval/expr.go#L561-L563](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/sem/eval/expr.go#L561-L563)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/bazel-out/k8-opt/bin/pkg/sql/sem/tree/eval_expr_generated.go#L120-L122](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/bazel-out/k8-opt/bin/pkg/sql/sem/tree/eval_expr_generated.go#L120-L122)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/sem/eval/expr.go#L252-L254](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/sem/eval/expr.go#L252-L254)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/bazel-out/k8-opt/bin/pkg/sql/sem/tree/eval_expr_generated.go#L275-L277](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/bazel-out/k8-opt/bin/pkg/sql/sem/tree/eval_expr_generated.go#L275-L277)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/sem/eval/expr.go#L482-L484](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/sem/eval/expr.go#L482-L484)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/sem/builtins/builtins.go#L9213-L9215](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/sem/builtins/builtins.go#L9213-L9215)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/sem/builtins/builtins.go#L3327-L3329](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/sem/builtins/builtins.go#L3327-L3329)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/sem/eval/context.go#L630-L632](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/sem/eval/context.go#L630-L632)
</details>

```
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchToExecutionEngine at line 1764
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithDistSQLEngine at line 2210
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRunAll at line 1630
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRunAll.func3 at line 1627
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRun at line 1895
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).Run at line 902
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlow).Run at line 313
pkg/sql/flowinfra/flow.go in pkg/sql/flowinfra.(*FlowBase).Run at line 580
pkg/sql/execinfra/processorsbase.go in pkg/sql/execinfra.(*ProcessorBaseNoHelper).Run at line 726
pkg/sql/execinfra/base.go in pkg/sql/execinfra.Run at line 193
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*FlowCoordinator).Next at line 150
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*FlowCoordinator).nextAdapter at line 145
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*FlowCoordinator).next at line 128
pkg/sql/plan_node_to_row_source.go in pkg/sql.(*planNodeToRowSource).Next at line 220
pkg/sql/virtual_table.go in pkg/sql.(*vTableLookupJoinNode).Next at line 317
pkg/sql/virtual_schema.go in pkg/sql.(*virtualDefEntry).makeConstrainedRowsGenerator.func1 at line 827
pkg/sql/pg_catalog.go in pkg/sql.makeAllRelationsVirtualTableWithDescriptorIDIndex.func2 at line 1248
pkg/sql/pg_catalog.go in pkg/sql.populateTableConstraints at line 1077
pkg/sql/catalog/schemaexpr/expr.go in pkg/sql/catalog/schemaexpr.FormatExprForDisplay at line 251
pkg/sql/catalog/schemaexpr/expr.go in pkg/sql/catalog/schemaexpr.formatExprForDisplayImpl at line 294
pkg/sql/catalog/schemaexpr/expr.go in pkg/sql/catalog/schemaexpr.deserializeExprForFormatting at line 356
pkg/sql/sem/eval/expr.go in pkg/sql/sem/eval.Expr at line 26
bazel-out/k8-opt/bin/pkg/sql/sem/tree/eval_expr_generated.go in pkg/sql/sem/tree.(*OrExpr).Eval at line 326
pkg/sql/sem/eval/expr.go in pkg/sql/sem/eval.(*evaluator).EvalOrExpr at line 562
bazel-out/k8-opt/bin/pkg/sql/sem/tree/eval_expr_generated.go in pkg/sql/sem/tree.(*ComparisonExpr).Eval at line 121
pkg/sql/sem/eval/expr.go in pkg/sql/sem/eval.(*evaluator).EvalComparisonExpr at line 253
bazel-out/k8-opt/bin/pkg/sql/sem/tree/eval_expr_generated.go in pkg/sql/sem/tree.(*FuncExpr).Eval at line 276
pkg/sql/sem/eval/expr.go in pkg/sql/sem/eval.(*evaluator).EvalFuncExpr at line 483
pkg/sql/sem/builtins/builtins.go in pkg/sql/sem/builtins.stringOverload1.func1 at line 9214
pkg/sql/sem/builtins/builtins.go in pkg/sql/sem/builtins.glob..func174 at line 3328
pkg/sql/sem/eval/context.go in pkg/sql/sem/eval.(*Context).GetTxnTimestamp at line 631
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v23.1.19 |
| Go Version | go1.19.13 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.19 |
| Cockroach SHA | 1bca2adcbc1deb23067e28369f8b24c99194f2bb |
| # of CPUs | 36 |
| # of Goroutines | 667 |

Jira issue: CRDB-38108

**Comment by yuzefovich** [comment]
This is a dup of #97643, only using `parse_date` builtin instead of `parse_time`.
