### ISSUE TITLE
Sentry: context.go:631: zero transaction timestamp in EvalContext
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/sem/eval.(*Contex...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#122896]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5243000849/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5243000849/?referrer=webhooks_plugin)

Panic Message:

```
context.go:631: zero transaction timestamp in EvalContext
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/sem/eval.(*Context).GetTxnTimestamp
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/eval/context.go:631
  | github.com/cockroachdb/cockroach/pkg/sql/sem/builtins.glob..func174
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/builtins/builtins.go:3328
  | github.com/cockroachdb/cockroach/pkg/sql/sem/builtins.stringOverload1.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/builtins/builtins.go:9214
  | github.com/cockroachdb/cockroach/pkg/sql/sem/eval.(*evaluator).EvalFuncExpr
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/eval/expr.go:483
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FuncExpr).Eval
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/sem/tree/eval_expr_generated.go:276
  | github.com/cockroachdb/cockroach/pkg/sql/sem/eval.(*evaluator).EvalComparisonExpr
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/eval/expr.go:253
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*ComparisonExpr).Eval
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/sem/tree/eval_expr_generated.go:121
  | github.com/cockroachdb/cockroach/pkg/sql/sem/eval.(*evaluator).EvalOrExpr
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/eval/expr.go:562
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*OrExpr).Eval
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/sem/tree/eval_expr_generated.go:326
  | github.com/cockroachdb/cockroach/pkg/sql/sem/eval.Expr
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/eval/expr.go:26
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/schemaexpr.deserializeExprForFormatting
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/schemaexpr/expr.go:356
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/schemaexpr.formatExprForDisplayImpl
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/schemaexpr/expr.go:294
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/schemaexpr.FormatExprForDisplay
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/schemaexpr/expr.go:251
  | github.com/cockroachdb/cockroach/pkg/sql.populateTableConstraints
  | 	github.com/cockroachdb/cockroach/pkg/sql/pg_catalog.go:1077
  | github.com/cockroachdb/cockroach/pkg/sql.makeAllRelationsVirtualTableWithDescriptorIDIndex.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/pg_catalog.go:1248
  | github.com/cockroachdb/cockroach/pkg/sql.(*virtualDefEntry).makeConstrainedRowsGenerator.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/virtual_schema.go:827
  | github.com/cockroachdb/cockroach/pkg/sql.(*vTableLookupJoinNode).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/virtual_table.go:317
  | github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:220
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Columnarizer).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/columnarizer.go:239
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:118
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:126
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).nextAdapter
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:250
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:254
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:286
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:328
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:902
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1895
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll.func3
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1627
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1630
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2210
Wraps: (3) zero transaction timestamp in EvalContext
Error types: (1) *assert.withAssertionFailure (2) *withstack.withStack (3) *errutil.leafError
-- report composition:
*errutil.leafError: zero transaction timestamp in EvalContext
context.go:631: *withstack.withStack (top exception)
*assert.withAssertionFailure
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/conn_executor_exec.go#L2209-L2211](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/conn_executor_exec.go#L2209-L2211)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/distsql_running.go#L1629-L1631](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/distsql_running.go#L1629-L1631)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/distsql_running.go#L1626-L1628](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/distsql_running.go#L1626-L1628)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/distsql_running.go#L1894-L1896](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/distsql_running.go#L1894-L1896)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/distsql_running.go#L901-L903](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/distsql_running.go#L901-L903)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colflow/vectorized_flow.go#L327-L329](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colflow/vectorized_flow.go#L327-L329)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colflow/flow_coordinator.go#L285-L287](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colflow/flow_coordinator.go#L285-L287)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colflow/flow_coordinator.go#L253-L255](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colflow/flow_coordinator.go#L253-L255)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colflow/flow_coordinator.go#L249-L251](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colflow/flow_coordinator.go#L249-L251)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colflow/stats.go#L125-L127](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colflow/stats.go#L125-L127)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colflow/stats.go#L117-L119](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colflow/stats.go#L117-L119)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colexec/columnarizer.go#L238-L240](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/colexec/columnarizer.go#L238-L240)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/plan_node_to_row_source.go#L219-L221](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/plan_node_to_row_source.go#L219-L221)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/virtual_table.go#L316-L318](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/virtual_table.go#L316-L318)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/virtual_schema.go#L826-L828](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/virtual_schema.go#L826-L828)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/pg_catalog.go#L1247-L1249](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/pg_catalog.go#L1247-L1249)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/pg_catalog.go#L1076-L1078](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/pg_catalog.go#L1076-L1078)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/catalog/schemaexpr/expr.go#L250-L252](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/catalog/schemaexpr/expr.go#L250-L252)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/catalog/schemaexpr/expr.go#L293-L295](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/catalog/schemaexpr/expr.go#L293-L295)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/catalog/schemaexpr/expr.go#L355-L357](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/catalog/schemaexpr/expr.go#L355-L357)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/sem/eval/expr.go#L25-L27](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/sem/eval/expr.go#L25-L27)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/bazel-out/k8-opt/bin/pkg/sql/sem/tree/eval_expr_generated.go#L325-L327](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/bazel-out/k8-opt/bin/pkg/sql/sem/tree/eval_expr_generated.go#L325-L327)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/sem/eval/expr.go#L561-L563](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/sem/eval/expr.go#L561-L563)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/bazel-out/k8-opt/bin/pkg/sql/sem/tree/eval_expr_generated.go#L120-L122](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/bazel-out/k8-opt/bin/pkg/sql/sem/tree/eval_expr_generated.go#L120-L122)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/sem/eval/expr.go#L252-L254](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/sem/eval/expr.go#L252-L254)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/bazel-out/k8-opt/bin/pkg/sql/sem/tree/eval_expr_generated.go#L275-L277](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/bazel-out/k8-opt/bin/pkg/sql/sem/tree/eval_expr_generated.go#L275-L277)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/sem/eval/expr.go#L482-L484](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/sem/eval/expr.go#L482-L484)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/sem/builtins/builtins.go#L9213-L9215](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/sem/builtins/builtins.go#L9213-L9215)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/sem/builtins/builtins.go#L3327-L3329](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/sem/builtins/builtins.go#L3327-L3329)
[https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/sem/eval/context.go#L630-L632](https://github.com/cockroachdb/cockroach/blob/1bca2adcbc1deb23067e28369f8b24c99194f2bb/pkg/sql/sem/eval/context.go#L630-L632)
</details>

```
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithDistSQLEngine at line 2210
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRunAll at line 1630
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRunAll.func3 at line 1627
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRun at line 1895
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).Run at line 902
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlow).Run at line 328
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).Run at line 286
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).next at line 254
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).nextAdapter at line 250
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).Next at line 126
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).next at line 118
pkg/sql/colexec/columnarizer.go in pkg/sql/colexec.(*Columnarizer).Next at line 239
pkg/sql/plan_node_to_row_source.go in pkg/sql.(*planNodeToRowSource).Next at line 220
pkg/sql/virtual_table.go in pkg/sql.(*vTableLookupJoinNode).Next at line 317
pkg/sql/virtual_schema.go in pkg/sql.(*virtualDefEntry).makeConstrainedRowsGenerator.func1 at line 827
pkg/sql/pg_catalog.go in pkg/sql.makeAllRelationsVirtualTableWithDescriptorIDIndex.func2 at line 1248
pkg/sql/pg_catalog.go in pkg/sql.populateTableConstraints at line 1077
pkg/sql/catalog/schemaexpr/expr.go in pkg/sql/catalog/schemaexpr.FormatExprForDisplay at line 251
pkg/sql/catalog/schemaexpr/expr.go in pkg/sql/catalog/schemaexpr.formatExprForDisplayImpl at line 294
pkg/sql/catalog/schemaexpr/expr.go in pkg/sql/catalog/schemaexpr.deserializeExprForFormatting at line 356
pkg/sql/sem/eval/expr.go in pkg/sql/sem/eval.Expr at line 26
bazel-out/k8-opt/bin/pkg/sql/sem/tree/eval_expr_generated.go in pkg/sql/sem/tree.(*OrExpr).Eval at line 326
pkg/sql/sem/eval/expr.go in pkg/sql/sem/eval.(*evaluator).EvalOrExpr at line 562
bazel-out/k8-opt/bin/pkg/sql/sem/tree/eval_expr_generated.go in pkg/sql/sem/tree.(*ComparisonExpr).Eval at line 121
pkg/sql/sem/eval/expr.go in pkg/sql/sem/eval.(*evaluator).EvalComparisonExpr at line 253
bazel-out/k8-opt/bin/pkg/sql/sem/tree/eval_expr_generated.go in pkg/sql/sem/tree.(*FuncExpr).Eval at line 276
pkg/sql/sem/eval/expr.go in pkg/sql/sem/eval.(*evaluator).EvalFuncExpr at line 483
pkg/sql/sem/builtins/builtins.go in pkg/sql/sem/builtins.stringOverload1.func1 at line 9214
pkg/sql/sem/builtins/builtins.go in pkg/sql/sem/builtins.glob..func174 at line 3328
pkg/sql/sem/eval/context.go in pkg/sql/sem/eval.(*Context).GetTxnTimestamp at line 631
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v23.1.19 |
| Go Version | go1.19.13 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.19 |
| Cockroach SHA | 1bca2adcbc1deb23067e28369f8b24c99194f2bb |
| # of CPUs | 36 |
| # of Goroutines | 674 |

Jira issue: CRDB-38116

**Comment by yuzefovich** [comment]
dup of #122888
