### ISSUE TITLE
storage: potential migrations

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#12289]
This issue tracks potential migrations that we haven't written code for yet.

- [ ] Recompute system key MVCC stats #12278 
- [ ] Migrate RaftTombstoneKey to the unreplicated key space #12154

**Comment by a6802739** [comment]
@petermattis, Could I have see on #12154?

**Comment by petermattis** [comment]
@a6802739 Thanks for the offer. There is a prerequisite on #12290 which needs a bit more thought on the design.

**Comment by a6802739** [comment]
@petermattis, So I should have a see on #12290 first?

**Comment by petermattis** [comment]
@a6802739 Yes. And we need to flesh out the design in that issue before starting implementation.

**Comment by a6802739** [comment]
@petermattis, okay, got it. Thanks a lot.

**Comment by tschottdorf** [comment]
Both of the aforementioned issues have been resolved, so closing this.
