### ISSUE TITLE
storage: write a test for lease clobbering

### ISSUE THREAD

**Issue by spencerkimball** [cockroachdb/cockroach#12285]
PR #12209 needs a unittest to verify that we now protect against leases being incorrectly overwritten on lease requests or lease transfers.

**Comment by spencerkimball** [comment]
from @andreimatei:

 A prop-eval-kv-only test demonstrating that a command evaluated under one lease and applied under another is rejected at apply time? If so, I guess you could add a testing hook in replica.propose(), similar to TestingCommandFilter, and block a lease transfer just before raftGroup.Propose(). Then perform another transfer and let it complete, unblock the original and check that it doesn't do anything?

**Comment by petermattis** [comment]
@cuongdo for re-assignment.

**Comment by tschottdorf** [comment]
Closing. It's been two years. These tests tend to either get written when the PR is open or not at all.
