### ISSUE TITLE
schemachanger: invalid usage of non-indexable column in ALTER PRIMARY KEY

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#122871]
Found via #122864:
```sql
CREATE TABLE tab_1 (
  col0_4         TSVECTOR NOT NULL,
  col0_6         OID,
  col0_18        REGTYPE,
  PRIMARY KEY (col0_18 DESC)
);

ALTER TABLE tab_1 ALTER PRIMARY KEY USING COLUMNS (col0_4);

INSERT INTO tab_1 (col0_4, col0_6, col0_18)
  WITH cte(col) AS (VALUES (0:::OID))
  SELECT '''qiOcIzk''', cte.col, cte.col FROM cte;
```
results in
```
unable to encode table key: *tree.DTSVector
```
which is an internal error in test builds. Interestingly, removing the PK change removes the error.

Jira issue: CRDB-38094

**Comment by yuzefovich** [comment]
This is a bug in the declarative schema changer where we forgot to check that all columns for the new PK are indexable.

**Comment by rafiss** [comment]
I used a git bisect with that repro example, and 7a8844145efd224895a873dc752553da1ffd65dc is the first bad commit. I don't see what the bug is yet.

**Comment by yuzefovich** [comment]
Isn't the problem that `checkForEarlyExit` doesn't verify that each column to be used in the new PK is indexable (i.e. similar to what we do at the end of `processColNodeType`)?

**Comment by rafiss** [comment]
Yeah, that sounds right, but I don't see why 7a88441 revealed that bug. I guess it just makes ALTER PRIMARY KEY use the new schema changer when it wasn't before.
