### ISSUE TITLE
Sentry: optimizer.go:279: top-level relational expression cannot have outer columns: (758-764,766-780,783-795,797-803)
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | githu...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#122962]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5247996144/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5247996144/?referrer=webhooks_plugin)

Panic Message:

```
optimizer.go:279: top-level relational expression cannot have outer columns: (758-764,766-780,783-795,797-803)
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).Optimize
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:279
  | github.com/cockroachdb/cockroach/pkg/sql.(*optPlanningCtx).reuseMemo
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:515
  | github.com/cockroachdb/cockroach/pkg/sql.(*optPlanningCtx).buildExecMemo
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:545
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).makeOptimizerPlan
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:245
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).makeExecPlan
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2081
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1588
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1058
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:142
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:3142
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:141
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execPortal
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:247
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2299
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2301
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2116
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:911
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:310
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (3) top-level relational expression cannot have outer columns: (758-764,766-780,783-795,797-803)
Error types: (1) *assert.withAssertionFailure (2) *withstack.withStack (3) *errutil.leafError
-- report composition:
*errutil.leafError: top-level relational expression cannot have outer columns: (758-764,766-780,783-795,797-803)
optimizer.go:279: *withstack.withStack (top exception)
*assert.withAssertionFailure
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/pgwire/conn.go#L309-L311](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/pgwire/conn.go#L309-L311)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/conn_executor.go#L910-L912](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/conn_executor.go#L910-L912)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/conn_executor.go#L2115-L2117](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/conn_executor.go#L2115-L2117)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/conn_executor.go#L2300-L2302](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/conn_executor.go#L2300-L2302)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/conn_executor.go#L2298-L2300](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/conn_executor.go#L2298-L2300)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/conn_executor_exec.go#L246-L248](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/conn_executor_exec.go#L246-L248)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/conn_executor_exec.go#L140-L142](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/conn_executor_exec.go#L140-L142)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/conn_executor_exec.go#L3141-L3143](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/conn_executor_exec.go#L3141-L3143)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/conn_executor_exec.go#L141-L143](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/conn_executor_exec.go#L141-L143)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/conn_executor_exec.go#L1057-L1059](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/conn_executor_exec.go#L1057-L1059)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/conn_executor_exec.go#L1587-L1589](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/conn_executor_exec.go#L1587-L1589)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/conn_executor_exec.go#L2080-L2082](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/conn_executor_exec.go#L2080-L2082)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/plan_opt.go#L244-L246](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/plan_opt.go#L244-L246)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/plan_opt.go#L544-L546](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/plan_opt.go#L544-L546)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/plan_opt.go#L514-L516](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/plan_opt.go#L514-L516)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/opt/xform/optimizer.go#L278-L280](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/opt/xform/optimizer.go#L278-L280)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommandsAsync.func1 at line 310
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 911
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 2116
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 2301
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd.func2 at line 2299
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execPortal at line 247
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 141
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithProfiling at line 3142
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt.func1 at line 142
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 1058
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchToExecutionEngine at line 1588
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).makeExecPlan at line 2081
pkg/sql/plan_opt.go in pkg/sql.(*planner).makeOptimizerPlan at line 245
pkg/sql/plan_opt.go in pkg/sql.(*optPlanningCtx).buildExecMemo at line 545
pkg/sql/plan_opt.go in pkg/sql.(*optPlanningCtx).reuseMemo at line 515
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).Optimize at line 279
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v23.1.17 |
| Go Version | go1.19.13 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.17 |
| Cockroach SHA | d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346 |
| # of CPUs | 16 |
| # of Goroutines | 5919 |

Jira issue: CRDB-38142

**Comment by yuzefovich** [comment]
unactionable
