### ISSUE TITLE
sql: IN is broken for computed tuples

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#12295]
What did I do:
```
root@:26257> select 'foo' in (x, null) from (select 'foo' as x);
+--------------------+
| 'foo' IN (x, NULL) |
+--------------------+
| false              |
+--------------------+
```

This fails because of the smartness introduced in aa5dd437a8f3643bf5764f3b5a026bdd504c10f5: this "in comparison" implementation with tuples on the right assumes the tuples are sorted; however tuple sorting only occurs during expression normalization, assuming that all the tuple elements are known already. If there is a column reference in there, the sort doesn't do what it should, and the `sort.Search` doesn't find what it should either.

(Compare with `SELECT 'foo' IN (NULL, x)` which does work)

**Comment by knz** [comment]
@nvanbenschoten it's fine if you let this sit until you have time. Or feel free to reassign.

**Comment by nvanbenschoten** [comment]
It looks like we'll either have to remove the sorting optimization, which wasn't very critical considering how few elements are in even the largest IN expressions, or we'll have to check whether or not the expression was normalized. I think this can be accomplished by simply checking [during evalutation](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/parser/eval.go#L2092), whether `expr.Right` is a `*DTuple` or a `*Tuple`, which is exactly what we do [during normalization](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/parser/normalize.go#L404). Do you have a preference @knz?

This also reminds me that we could probably perform a similar optimization for array ANY/SOME.

**Comment by petermattis** [comment]
The optimization is definitely worthwhile when the IN expression is constant across rows such as in a WHERE clause. But it doesn't make sense when the tuple changes on every row as in a render expression.

**Comment by knz** [comment]
+1 on peter's opinion. I think if we can switch on the type that'd be an OK solution, although in the long term what we really need is a boolean on the tuple to indicate whether it's sorted (a side benefit could be that that boolean could be set appropriately if the tuple was created by a subquery with an appropriate sort clause).

**Comment by nvanbenschoten** [comment]
I'm actually leaning towards a sorted flag on tuples immediately after giving this more thought. That approach would be less fragile, would avoid some awkward handling during evaluation, and would open up opportunities for other optimizations like knz mentioned.
