### ISSUE TITLE
sql: log session variable settings that are set in the connection string

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#122934]
**Is your feature request related to a problem? Please describe.**
When a new SQL connection is established, it would be helpful to see the session variables that were set in the connection string.

**Describe the solution you'd like**
Add logging to `parseClientProvidedSessionParameters` that will go to the SESSIONS log channel. https://github.com/cockroachdb/cockroach/blob/8a122522cac708e29271139fda695ae0027658d4/pkg/sql/pgwire/pre_serve_options.go#L45

**Additional context**
These session settings can still be changed with SET commands during the session. Also, even if a setting is not in the connection string, it still could have a custom default configured using the `ALTER ROLE ... SET ...` syntax.

Jira issue: CRDB-38129

Epic CRDB-38033

**Comment by lyang24** [comment]
This sounds relevant to one of our investigations. May i work on this issue?

**Comment by rafiss** [comment]
You are welcome to send a PR, thank you!
