### ISSUE TITLE
storage: enhance store-level migration infrastructure

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#12290]
The infrastructure for store-level migrations is currently very primitive: a single `Store.migrate` method exists which is called for every range descriptor every time the store starts. This is both overly expensive and insufficiently flexible. 

Two recent candidates for store-level migrations are recomputing system key stats to fix an inconsistency caused by a bug in handling of Raft tombstone keys and migrating the Raft tombstone key to the unreplicated key space. Recomputing the system key stats for every replica is a reasonably expensive operation which we wouldn't want to perform on every replica every time the store starts. Migrating the Raft tombstone keys is interesting because those keys are intended to exist only when a range descriptor for the range does not exist. 

I think the existing migration mechanism should be replaced with something similar to the [cluster upgrade tool](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/cluster_upgrade_tool.md). Each migration would have an associated name and the store will keep a `/Local/Store/Migration/<migration>` key that is only present after the migration has been run. Migrations would be run early in the lifetime of a store before the replicas have been loaded. 

See #12289

**Comment by petermattis** [comment]
Cc @a-robinson

**Comment by a-robinson** [comment]
Ack, I had missed this until #12289 got pinged this morning. I'll think about this soon.

**Comment by tschottdorf** [comment]
I doubt we're going to do anything here until we need it, so closing this. Feel free to reopen if you disagree.
