### ISSUE TITLE
backupccl: online restore does not restore correct backup data

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#123061]
To reproduce, run the `backup-restore/online-restore` roachtest, currently in [a pr](https://github.com/cockroachdb/cockroach/pull/122714), on a cockroach binary that contains the patch [here](https://github.com/cockroachdb/cockroach/pull/122918), which prevents OR from linking virtual ssts that point to empty key space.

Some next steps:
- this roachtest logs where the relevant backup lives. To even more easily reproduce, spin up a roachprod cluster, and take a regular restore and an online restore and manually run the sql level fingerprint. When i investigated this briefly, i could not repro the mismatch manually, which is very interesting. Double check this. Some questions here: does the roachtest run the foreground workload while it takes a fingerprint? Is there anything else different with how the roachtest runs the sql fingerprint, like an AOST query?
- Check if this is a bad split bug: to do so, modify the roachtest driver to take export request level fingerprints instead of the current sql level fingerprints. If the test passes with export request fingerprints, we have a smoking gun. The `fingerprintutils` package provides some nice APIs for cleaning this up. Make sure you run a stripped fingerprint.

Jira issue: CRDB-38185

**Comment by msbutler** [comment]
@itsbilal I stumbled upon some clues for this investigation. I think this fingerprint violation is a recent regression.

I originally discovered this corruption issue because the tpce workload we run in our OR perf tests was silently failing (patch to fix the silent fail [here](https://github.com/cockroachdb/cockroach/pull/122643)). This manifested in 0 actual queries running during the download phase.

BUT, while running the 8tb OR test (`restore/online/workload=true/tpce/8TB/aws/inc-count=1/nodes=10/cpus=8`)  or the 400 GB test `restore/online/workload=true/tpce/400GB/aws/inc-count=1/nodes=4/cpus=8` with a cockroach binary built on the sha `1c258e755d2ed83241438ac3bb142625b3da80f5` (landing around march 18th) , the tpce workload runs fine! this suggests that a restore running on that sha and the backup fixtures at that time (created around march 10th) don't contain the og regression. (note i did not stress these roachtests)

However, if I run this new backup-restore/online-restore roachtest on the above sha, I immediately get a fingerprint violation. One story that could explain this is that we merged something to _backup_ between when those fixtures were created and the sha above.

One next step is running the backup-restore roundtrip test on a sha around march 1st, to see if the or was corruption free.

**Comment by msbutler** [comment]
@itsbilal i may have bungled my commands. 

> However, if I run this new backup-restore/online-restore roachtest on the above sha, I immediately get a fingerprint violation.
I need to double check this.

**Comment by stevendanna** [comment]
@msbutler Perhaps we should try this with ImportEpoch's turned off?

**Comment by msbutler** [comment]
why would the importEpoch affect sql level fingerprinting?

**Comment by msbutler** [comment]
I was able to reproduce the corruption bug immediately using the `backup-restore/online-restore` roachtest with export request level fingerprints using this [patch](https://github.com/cockroachdb/cockroach/pull/123553). This suggests we're not dealing with a bad split bug. I can also reproduce on the latest sha on master and the first [sha ](https://github.com/cockroachdb/cockroach/pull/119847) that contains prefix synthesis.

**Comment by msbutler** [comment]
Using the fingerprint[s patch ](https://github.com/cockroachdb/cockroach/pull/123553), i observed the fingerprint mismatch before the download job begins and after it completes. Next, i'll try manually running the fingerprint tooling from the backup created by the test.

**Comment by msbutler** [comment]
ah, this roachtest consistently fails because of a test bug. fixed here. https://github.com/cockroachdb/cockroach/pull/123590

**Comment by msbutler** [comment]
tpce corruption blocked by https://github.com/cockroachdb/cockroach/pull/123426. closing.
