### ISSUE TITLE
sql: IN does not return NULL in situations where PG would

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#12302]
From https://www.postgresql.org/docs/9.0/static/functions-subquery.html#AEN16806
> Note that if the left-hand expression yields null, or if there are no equal right-hand values and at least one right-hand row yields null, the result of the IN construct will be null, not false. This is in accordance with SQL's normal rules for Boolean combinations of null values.

In Cockroach:
```
root@:26257> SELECT 1 IN (2, NULL);
+----------------+
| 1 IN (2, NULL) |
+----------------+
| false          |
+----------------+
```

In PG:
```
nathan=# SELECT 1 IN (2, NULL);
 ?column?
----------

```

This rule is identical to logic added in #12102, so I'll fix it once that change goes through.

**Comment by knz** [comment]
I guess this is related to  #12295 right?

**Comment by nvanbenschoten** [comment]
Unrelated actually, I just noticed it because of that issue.

**Comment by knz** [comment]
ok thanks carry on :shamrock:
