### ISSUE TITLE
storage: configure allocator size class hints

### ISSUE THREAD

**Issue by CheranMahalingam** [cockroachdb/cockroach#123090]
https://github.com/cockroachdb/pebble/pull/3508 added support for a new set of sstable flushing heuristics that can help reduce block cache internal fragmentation and the overall CockroachDB memory footprint. To reap the benefits we need to configure the default Pebble options at the Cockroach layer to specify the size classes supported by jemalloc once the Pebble version has been bumped (https://jemalloc.net/jemalloc.3.html#size_classes). This could look like,
```
opts.AllocatorSizeClasses = []int{
    16384,
    20480, 24576, 28672, 32768,
    40960, 49152, 57344, 65536,
    81920, 98304, 114688, 131072,
}
```
There are many more size classes that could be included, however, sstable blocks have a target block size of 32KiB, a minimum size threshold of ~19.6KiB and are unlikely to exceed 128KiB.

Jira issue: CRDB-38198

**Comment by aadityasondhi** [comment]
We need to verify the CPU implications of this change through profiles. We could run kv0 with small (1B) block bytes and view CPU profiles.

**Comment by sumeerbhola** [comment]
https://github.com/cockroachlabs/support/issues/2908#issuecomment-2136029530 may be helped by this change (9.36GiB allocated instead of 8GiB).
