### ISSUE TITLE
sql: v23.1.4: nil pointer with pausable portals

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#123042]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5253914031/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5253914031/?referrer=webhooks_plugin)

Panic Message:

```
conn_executor.go:891: runtime error: invalid memory address or nil pointer dereference
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:891
  | [...repeated from below...]
Wraps: (2) while executing: SELECT _._ AS _, avg(_._) AS _, avg(_._) AS _ FROM (SELECT _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _ FROM _ AS _ LEFT JOIN (SELECT _, min(_) AS _, max(_) AS _, max(_) AS _, extract('_', (max(_) - min(_)))::DECIMAL / ((_ * _) * _) AS _, extract('_', (max(_) - min(_)))::DECIMAL / ((_ * _) * _) AS _ FROM _ GROUP BY _) AS _ ON _._ = _._ LEFT JOIN _ AS _ ON _._ = _._ WHERE _._ = '_') AS _ GROUP BY _._ ORDER BY _._ ASC
Wraps: (3) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:891
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | runtime.panicmem
  | 	GOROOT/src/runtime/panic.go:260
  | runtime.sigpanic
  | 	GOROOT/src/runtime/signal_unix.go:835
  | github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).GetFlowCtx
  | 	github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:365
  | github.com/cockroachdb/cockroach/pkg/sql.getFinishedSetupFn.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1589
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).resumeFlowForPausablePortal
  | 	github.com/cockroachdb/cockroach/pkg/sql/planner.go:294
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2066
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1656
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:964
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:142
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2986
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:141
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execPortal
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:247
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2280
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2282
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2097
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:893
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:778
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (4) runtime error: invalid memory address or nil pointer dereference
Error types: (1) *withstack.withStack (2) *safedetails.withSafeDetails (3) *withstack.withStack (4) runtime.errorString
-- report composition:
runtime.errorString
conn_executor.go:891: *withstack.withStack (top exception)
*safedetails.withSafeDetails: while executing: SELECT _._ AS _, avg(_._) AS _, avg(_._) AS _ FROM (SELECT _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _ FROM _ AS _ LEFT JOIN (SELECT _, min(_) AS _, max(_) AS _, max(_) AS _, extract('_', (max(_) - min(_)))::DECIMAL / ((_ * _) * _) AS _, extract('_', (max(_) - min(_)))::DECIMAL / ((_ * _) * _) AS _ FROM _ GROUP BY _) AS _ ON _._ = _._ LEFT JOIN _ AS _ ON _._ = _._ WHERE _._ = '_') AS _ GROUP BY _._ ORDER BY _._ ASC
conn_executor.go:891: *withstack.withStack (1)
(check the extra data payloads)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/pgwire/conn.go#L777-L779](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/pgwire/conn.go#L777-L779)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/conn_executor.go#L892-L894](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/conn_executor.go#L892-L894)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/conn_executor.go#L2096-L2098](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/conn_executor.go#L2096-L2098)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/conn_executor.go#L2281-L2283](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/conn_executor.go#L2281-L2283)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/conn_executor.go#L2279-L2281](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/conn_executor.go#L2279-L2281)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/conn_executor_exec.go#L246-L248](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/conn_executor_exec.go#L246-L248)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/conn_executor_exec.go#L140-L142](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/conn_executor_exec.go#L140-L142)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/conn_executor_exec.go#L2985-L2987](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/conn_executor_exec.go#L2985-L2987)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/conn_executor_exec.go#L141-L143](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/conn_executor_exec.go#L141-L143)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/conn_executor_exec.go#L963-L965](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/conn_executor_exec.go#L963-L965)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/conn_executor_exec.go#L1655-L1657](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/conn_executor_exec.go#L1655-L1657)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/conn_executor_exec.go#L2065-L2067](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/conn_executor_exec.go#L2065-L2067)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/planner.go#L293-L295](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/planner.go#L293-L295)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/distsql_running.go#L1588-L1590](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/distsql_running.go#L1588-L1590)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/flowinfra/flow.go#L364-L366](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/flowinfra/flow.go#L364-L366)
[GOROOT/src/runtime/signal_unix.go#L834-L836](GOROOT/src/runtime/signal_unix.go#L834-L836)
[GOROOT/src/runtime/panic.go#L259-L261](GOROOT/src/runtime/panic.go#L259-L261)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
[https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/conn_executor.go#L890-L892](https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/conn_executor.go#L890-L892)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommandsAsync.func1 at line 778
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 893
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 2097
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 2282
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd.func2 at line 2280
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execPortal at line 247
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 141
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithProfiling at line 2986
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt.func1 at line 142
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 964
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchToExecutionEngine at line 1656
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithDistSQLEngine at line 2066
pkg/sql/planner.go in pkg/sql.(*planner).resumeFlowForPausablePortal at line 294
pkg/sql/distsql_running.go in pkg/sql.getFinishedSetupFn.func1 at line 1589
pkg/sql/flowinfra/flow.go in pkg/sql/flowinfra.(*FlowBase).GetFlowCtx at line 365
GOROOT/src/runtime/signal_unix.go in runtime.sigpanic at line 835
GOROOT/src/runtime/panic.go in runtime.panicmem at line 260
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn.func1 at line 891
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v23.1.4 |
| Go Version | go1.19.4 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.4 |
| Cockroach SHA | cf85e8ad48bb7a8afd821863d4f345baafa4a1b6 |
| # of CPUs | 12 |
| # of Goroutines | 1087 |

Jira issue: CRDB-38176

**Comment by yuzefovich** [comment]
I don't understand how this nil pointer is possible. We must have a `nil` `flow` object here:https://github.com/cockroachdb/cockroach/blob/cf85e8ad48bb7a8afd821863d4f345baafa4a1b6/pkg/sql/planner.go#L294
but just a few lines above we checked that we have non-nil one. Closing as unactionable.
