### ISSUE TITLE
Sentry: builder.go:446: unexpected statement: *tree.SetTracing
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Bui...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#123213]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5277759862/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5277759862/?referrer=webhooks_plugin)

Panic Message:

```
builder.go:446: unexpected statement: *tree.SetTracing
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:446
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmtAtRoot
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:272
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).Build
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:246
  | github.com/cockroachdb/cockroach/pkg/sql.(*optPlanningCtx).buildExecMemo
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:576
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).makeOptimizerPlan
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:240
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).makeExecPlan
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2030
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1539
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1036
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:142
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:3086
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:141
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2182
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2187
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2104
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:901
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:310
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (3) unexpected statement: *tree.SetTracing
Error types: (1) *assert.withAssertionFailure (2) *withstack.withStack (3) *errutil.leafError
-- report composition:
*errutil.leafError: unexpected statement: *tree.SetTracing
builder.go:446: *withstack.withStack (top exception)
*assert.withAssertionFailure
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/pgwire/conn.go#L309-L311](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/pgwire/conn.go#L309-L311)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/conn_executor.go#L900-L902](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/conn_executor.go#L900-L902)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/conn_executor.go#L2103-L2105](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/conn_executor.go#L2103-L2105)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/conn_executor.go#L2186-L2188](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/conn_executor.go#L2186-L2188)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/conn_executor.go#L2181-L2183](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/conn_executor.go#L2181-L2183)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/conn_executor_exec.go#L140-L142](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/conn_executor_exec.go#L140-L142)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/conn_executor_exec.go#L3085-L3087](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/conn_executor_exec.go#L3085-L3087)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/conn_executor_exec.go#L141-L143](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/conn_executor_exec.go#L141-L143)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/conn_executor_exec.go#L1035-L1037](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/conn_executor_exec.go#L1035-L1037)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/conn_executor_exec.go#L1538-L1540](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/conn_executor_exec.go#L1538-L1540)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/conn_executor_exec.go#L2029-L2031](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/conn_executor_exec.go#L2029-L2031)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/plan_opt.go#L239-L241](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/plan_opt.go#L239-L241)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/plan_opt.go#L575-L577](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/plan_opt.go#L575-L577)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/opt/optbuilder/builder.go#L245-L247](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/opt/optbuilder/builder.go#L245-L247)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/opt/optbuilder/builder.go#L271-L273](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/opt/optbuilder/builder.go#L271-L273)
[https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/opt/optbuilder/builder.go#L445-L447](https://github.com/cockroachdb/cockroach/blob/6bd6e0c65a2eba531e7a8412d63988abb5b50120/pkg/sql/opt/optbuilder/builder.go#L445-L447)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommandsAsync.func1 at line 310
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 901
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 2104
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 2187
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd.func1 at line 2182
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 141
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithProfiling at line 3086
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt.func1 at line 142
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 1036
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchToExecutionEngine at line 1539
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).makeExecPlan at line 2030
pkg/sql/plan_opt.go in pkg/sql.(*planner).makeOptimizerPlan at line 240
pkg/sql/plan_opt.go in pkg/sql.(*optPlanningCtx).buildExecMemo at line 576
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).Build at line 246
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).buildStmtAtRoot at line 272
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).buildStmt at line 446
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v23.1.10 |
| Go Version | go1.19.10 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.10 |
| Cockroach SHA | 6bd6e0c65a2eba531e7a8412d63988abb5b50120 |
| # of CPUs | 8 |
| # of Goroutines | 487 |

Jira issue: CRDB-38248

**Comment by yuzefovich** [comment]
dup of #95872
