### ISSUE TITLE
storage: 3-node cluster not balancing leases

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#12322]
Starting from scratch, a 3-node cluster does not appear to be balancing leases properly. When a 4th node is added the leases suddenly come into balance. There is probably some sort of off-by-one error. The graph below shows a 3-node cluster with ~1000 ranges. The imbalance resolves when a 4th node is added.

<img width="933" alt="screen shot 2016-12-13 at 12 50 03 pm" src="https://cloud.githubusercontent.com/assets/6201335/21152084/ea4aa9cc-c132-11e6-8474-8ff7e9b0db20.png">

**Comment by petermattis** [comment]
FYI, the replicas were created via:

`crl-ssh delta 0 ./block_writer -splits 1000 -max-blocks 1 -concurrency 1 'postgres://root@localhost:26257/?sslmode=verify-ca&sslrootcert=certs/ca.crt&sslcert=certs/root.client.crt&sslkey=certs/root.client.key'"`

This was done before starting additional `block_writer` load.

**Comment by petermattis** [comment]
Reproduced this problem this morning fairly quickly with `--vmodule=replicate_queue=2`. I'm seeing the following pattern:

```
I161221 15:36:24.002521 190 storage/replicate_queue.go:175  [n1,replicate,s1,r835/1:/Table/51/1/68{43487…-92031…},@c4242a3680] lease transfer needed, enqueuing
I161221 15:36:24.003307 185 storage/replicate_queue.go:267  [n1,replicate,s1,r835/1:/Table/51/1/68{43487…-92031…},@c4242a3680] processing: noop
I161221 15:36:24.004577 185 storage/replicate_queue.go:377  [n1,replicate,s1,r835/1:/Table/51/1/68{43487…-92031…},@c4242a3680] no suitable rebalance target
```

After running for a few minutes, I've counted 640 `lease transfer needed` messages but only 48 `transferring lease` messages. Looking into why replicate queue isn't able to find a lease transfer target.

**Comment by petermattis** [comment]
The selection of a lease transfer target is using the average number of ranges per store across all stores in the cluster. But only half the stores are being used because we have a 3-node cluster with 2 stores per node and we don't allow rebalancing between stores on the same node. 

```
I161221 16:13:52.340266 57 storage/allocator.go:464  lease transfer candidates: []
  candidate: avg-ranges=503.5 avg-leases=168
  5: ranges=3 leases=1 fraction-used=0.05
  3: ranges=1004 leases=169 fraction-used=0.05
  6: ranges=1004 leases=169 fraction-used=0.05
  4: ranges=3 leases=0 fraction-used=0.05
  2: ranges=0 leases=0 fraction-used=0.05
  1: ranges=1007 leases=669 fraction-used=0.05
```

**Comment by petermattis** [comment]
This problem goes away with a 4-node cluster because then we have an extra node we can rebalance to and thus start rebalancing to all of the stores within the cluster. We should probably improve the allocator heuristics to allow moving a replica from one store to another on the same node.

**Comment by vivekmenezes** [comment]
Why can't we transfer the leases and not move any data around?

**Comment by petermattis** [comment]
The lease can only be held by a store that contains one of the replicas for the range. If you look at the debug output above, 3 of the stores have 3 or fewer ranges so they can't hold the leases for the vast majority of ranges in the system.

We could possibly have a better heuristic here that balances the leases amongst the stores which have the ranges. Or, we could allow movement of replicas between stores on the same node.

**Comment by vivekmenezes** [comment]
what I am suggesting is better balancing between stores 3, 6 and 1 above. There is value to getting the leases balanced out between the nodes.

**Comment by petermattis** [comment]
Ok. That's what I meant by my comment:

> We could possibly have a better heuristic here that balances the leases amongst the stores which have the ranges.

This wouldn't be necessary if we properly balanced replicas among the stores in a 3-node cluster. But now that I think about it, we should probably restrict the candidates list for transfer lease targets to not contain stores that are on the same node as existing replicas. I think that would be a straightforward change and would alleviate this problem.
