### ISSUE TITLE
cdc: potentially dropping events during initial scan 

### ISSUE THREAD

**Issue by wenyihu6** [cockroachdb/cockroach#123371]
Initially, all span initial resolved timestamps are kept as zero upon resuming a
job since initial resolved timestamps are set as initial high water which
remains zero until initial scan is completed. However, since
https://github.com/cockroachdb/cockroach/commit/afb95b17f30e3099ad182c56ab5376ed3c3d878f,
we began reloading checkpoint timestamps instead of setting them all to zero at
the start. In PR #102717, we introduced a mechanism to reduce message duplicates
by re-loading job progress upon resuming which largely increased the likelihood
of this bug. This could result in dropping events since we now sometimes make a 
new frontier with all spans forwarded to initialResolved https://github.com/cockroachdb/cockroach/blob/df196391c576f3a26e57ad6d694ee7e793c1af81/pkg/ccl/changefeedccl/changefeed_processors.go#L528-L535. These errors could lead to incorrect frontier and missing events
during initial scans. 

Jira issue: CRDB-38432

**Comment by wenyihu6** [comment]
I agree that this could be another possible fix as far as I can tell (probably better since my current fix is a bit hacky and introduces more complication in the initial scan path). But I still want to read the code more to see how it plays along with other changefeeds and backfill since this is legacy code from https://github.com/cockroachdb/cockroach/blob/0eda54018b9676f855efcd90bfdd0c486c97bfdd/pkg/ccl/changefeedccl/changefeed_processors.go#L418-L422.

**Comment by rharding6373** [comment]
Reopening since we've found that although disabling shutdown checkpointing / drain watcher reduces the likelihood of hitting this issue, this issue pre-exists that feature.
