### ISSUE TITLE
cmd: sync cockroach-sql format flag with `cockroach sql`

### ISSUE THREAD

**Issue by annrpom** [cockroachdb/cockroach#123382]
**Is your feature request related to a problem? Please describe.**
Our [docs](https://www.cockroachlabs.com/docs/stable/cockroach-sql-binary) state the following: 

> the `cockroach-sql` command is a client for executing SQL statements from an interactive shell or directly from the command line. cockroach-sql is functionally equivalent to the [cockroach sql command](https://www.cockroachlabs.com/docs/v23.2/cockroach-sql).

However, there are many flags that `cockroach sql` supports that `cockroach-sql` does not. For instance, the `--format` flag works as expected with `cockroach sql`:
```
anniepompa in ~/go/src/github.com/cockroachdb/cockroach on fp-debug-doctor-jobs ● ● λ cockroach sql --format=csv -e="select 1" --insecure
?column?
1

Time: 0ms
```

But with `cockroach-sql`:
```
anniepompa in ~/go/src/github.com/cockroachdb/cockroach on fp-debug-doctor-jobs ● ● λ ./cockroach-sql --format=csv -e="select 1" --insecure
ERROR: unknown flag: --format
```

This has been the case since `cockroach-sql` was been introduced (v22.1).

**Describe the solution you'd like**
We should sync the flags

**Describe alternatives you've considered**
`cockroach sql` could be a workaround, but for customers with systems that do not meet the requirements of the cockroach binary (notably Alpine distros with images that use a different version of the C library -- musl libc), the sql shell binary (`cockroach-sql`) is what such customers turn to.

Jira issue: CRDB-38336

**Comment by annrpom** [comment]
We saw this occur: https://github.com/cockroachlabs/support/issues/2928

**Comment by MattSilvaa** [comment]
Hello @annrpom! Could I pick this up?

**Comment by rafiss** [comment]
@MattSilvaa sure, feel free to submit a PR, thanks!

**Comment by MattSilvaa** [comment]
PR is up...handling just `format` for now if that's ok.

**Comment by annrpom** [comment]
actually -- closing this out again. the support issue was just about the format flag. i'll open another issue out for syncing the rest of the flags up since that idea doesn't require an O-support label
