### ISSUE TITLE
storage: disk slowness during up-replication leads to liveness problems

### ISSUE THREAD

**Issue by ajstorm** [cockroachdb/cockroach#123392]
We have some vague disk slowness symptoms on `drt-large` after a preemption (and during a period of significant up-replication) which looks concerning.  Here is the sequence of events:

* Roachprod node 14 (which corresponds to n32) gets preempted at 17:50:06
* This prompts a significant amount of snapshot data to be sent to n24 (roachprod node 15)

<img width="630" alt="image" src="https://github.com/cockroachdb/cockroach/assets/18447034/4742a37f-ca76-4c40-9551-72fe84d1dcba">

* At `18:09:52`, n24 starts complaining about slow snapshots:

```
W240430 18:09:52.478498 769 kv/kvserver/liveness/liveness.go:752 ⋮ [T1,Vsystem,n24,liveness-hb] 1957797  slow heartbeat took 3.006430446s; err=disk write failed while updating node liveness: interrupted during singleflight ‹engine sync:7›: context deadline exceeded
```

* Over the next few seconds, the heartbeats get slower and slower:

```
W240430 18:09:55.300471 6899601491 kv/kvserver/liveness/liveness.go:752 ⋮ [T1,Vsystem,n24,s382,r73219/10:‹/Table/134/1/"`"/7{43/…-52/…}›] 1958044  slow heartbeat took 2.628505916s; err=heartbeat failed on epoch increment
```

```
W240430 18:09:57.295178 6899602176 kv/kvserver/liveness/liveness.go:752 ⋮ [T1,Vsystem,n24,s372,r74556/6:‹/Table/129/1/"`"/59{759…-804…}›] 1958245  slow heartbeat took 4.210669182s; err=heartbeat failed on epoch increment
```

```
W240430 18:10:04.212408 6899612663 kv/kvserver/liveness/liveness.go:752 ⋮ [T1,Vsystem,n24,s370,r73595/18:‹/Table/135/1/"`"/1214/{1…-5…}›] 1958946  slow heartbeat took 7.217240446s; err=heartbeat failed on epoch increment
```

```
W240430 18:10:25.686806 6899672507 kv/kvserver/liveness/liveness.go:752 ⋮ [T1,Vsystem,n24,s380,r36398/16:‹/Table/134/1/"`"/994{01…-16…}›] 1961030  slow heartbeat took 9.05261419s; err=heartbeat failed on epoch increment
```

* Tail latency gets worse in other areas, but nothing that would indicate that we should expect to see 9s+ heartbeats:

<img width="638" alt="image" src="https://github.com/cockroachdb/cockroach/assets/18447034/1a488ac5-b68c-47d4-bb68-23c1216379c4">

Eventually, we hit https://github.com/cockroachdb/cockroach/issues/122016, which brings down the node.  While we're investigating https://github.com/cockroachdb/cockroach/issues/122016 separately, the fact that we're having liveness issues due to up-replication seems like something that may be worth investigating. 

Jira issue: CRDB-38342

**Comment by ajstorm** [comment]
Note that while this may end up being an admission control or replication issue, it was initially routed to the Storage team based on [this](https://cockroachlabs.slack.com/archives/C0KB9Q03D/p1714575559391769?thread_ts=1714565272.478869&cid=C0KB9Q03D) comment.

**Comment by jbowens** [comment]
My two cents is there's nothing to investigate from a disk slowness perspective.
