### ISSUE TITLE
beta-20161215

### ISSUE THREAD

**Issue by paperstreet** [cockroachdb/cockroach#12348]
The candidate SHA is 5596982f21d1665e3872d2f0e4823e6f9168c1b8.

Release notes are under review in https://github.com/cockroachdb/docs/pull/923.

[Release process checklist](https://github.com/cockroachdb/cockroach/wiki/Release-Process)
- [x] The build is running on delta and rho.
- [x] Check and verify cluster status
- [x] Tag release and push tag
- [x] [Trigger release build](https://teamcity.cockroachdb.com/viewType.html?buildTypeId=Cockroach_MergeToMaster)
- [x] Check and verify binaries
- [x] Announce version to the registration cluster - see internal production instructions
- [x] Update homebrew
- [x] Update docs
- [x] External communications for release

**Comment by mberhault** [comment]
I think @bram is still poking at gamma. Let's do delta and rho only.

**Comment by knz** [comment]
Just for clarity my changes from df70a9d30149c8c00ce98c913ed1d2111d7986e2 have introduced a regression which causes outer joins using an ON clause to not work properly. I mentioned this in the doc issue already. Issue is reported as #12311.

**Comment by jseldess** [comment]
@paperstreet, updated release notes are ready to be published. Let me know when to go ahead.

**Comment by jseldess** [comment]
@jess-edwards, release notes are live: https://www.cockroachlabs.com/docs/beta-20161215.html. You can post to the forum and to our email list whenever you're ready.

**Comment by paperstreet** [comment]
All done
