### ISSUE TITLE
distsql: remove stored contexts

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#12346]
We have a bunch of stored contexts in places like `FlowCtx`, `tableReader`, `joinReader`. We should pass contexts instead of storing them.

CC @tamird

**Comment by a6802739** [comment]
@RaduBerinde , could I have a try for this?

**Comment by RaduBerinde** [comment]
Sure!

**Comment by arjunravinarayan** [comment]
Hi @a6802739, what's your status on this?

**Comment by asubiotto** [comment]
I'm interested in taking this on. @a6802739, I'll start working on this and in case you have made progress, let me know.
