### ISSUE TITLE
changefeedccl:  Error message with docs link resolves to "Page Not Found"

### ISSUE THREAD

**Issue by nollenr** [cockroachdb/cockroach#123483]
**Describe the problem**

I attempted to create a changefeed without enabling rangefeeds and received the following message:

ERROR: rangefeeds require the kv.rangefeed.enabled setting. See https://www.cockroachlabs.com/docs/v24.1/change-data-capture.html#enable-rangefeeds-to-reduce-latency

The following link appears to be broken (cloud be due to beta)
https://www.cockroachlabs.com/docs/v24.1/change-data-capture.html#enable-rangefeeds-to-reduce-latency

**To Reproduce**

What did you do? Describe in your own words.

Attempted to create a changefeed before enabling rangefeeds:

`CREATE CHANGEFEED FOR TABLE transactions
  INTO 'kafka://wenyitest.servicebus.windows.net:9093?tls_enabled=true&sasl_enabled=true&sasl_user=$ConnectionString&sasl_password=Endpoint%3Dsb%3A%2F%2Fwenyitest.servicebus.windows.net%2F%3BSharedAccessKeyName%3DRootManageSharedAccessKey%3BSharedAccessKey%3DM3wnjbdJ%2B6111A%2BnI8qpnkvpE0QMo2BF6%2BAEhJlcVPs%3D&sasl_mechanism=PLAIN'
  WITH updated, resolved;`

If possible, provide steps to reproduce the behavior:

1. Set up CockroachDB cluster ...
`ron@192.168.3.101:26257/bank> select version();
                                                        version
------------------------------------------------------------------------------------------------------------------------
  CockroachDB CCL v24.1.0-beta.3 (aarch64-unknown-linux-gnu, built 2024/04/26 16:27:07, go1.22.2 X:nocoverageredesign)
(1 row)

`
2. Send SQL ... / CLI command ...
`CREATE CHANGEFEED FOR TABLE transactions
  INTO 'kafka://wenyitest.servicebus.windows.net:9093?tls_enabled=true&sasl_enabled=true&sasl_user=$ConnectionString&sasl_password=Endpoint%3Dsb%3A%2F%2Fwenyitest.servicebus.windows.net%2F%3BSharedAccessKeyName%3DRootManageSharedAccessKey%3BSharedAccessKey%3DM3wnjbdJ%2B6111A%2BnI8qpnkvpE0QMo2BF6%2BAEhJlcVPs%3D&sasl_mechanism=PLAIN'
  WITH updated, resolved;`
3. Look at UI / log file / client app ...
N/A
`ERROR: rangefeeds require the kv.rangefeed.enabled setting. See https://www.cockroachlabs.com/docs/v24.1/change-data-capture.html#enable-rangefeeds-to-reduce-latency
`
**Expected behavior**
Enable range feed documentation link

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version [e.g. 2.0.x]
 - Server OS: [e.g. Linux/Distrib]
 - Client app [e.g. `cockroach sql`, JDBC, ...]

**Additional context**
What was the impact?

Jira issue: CRDB-38371

**Comment by kathancox** [comment]
This is the correct docs link to be added: https://www.cockroachlabs.com/docs/stable/create-and-configure-changefeeds#enable-rangefeeds
