### ISSUE TITLE
roadmap: distributed file system

### ISSUE THREAD

**Issue by jojo05** [cockroachdb/cockroach#12344]
Have you considered supporting or providing a distributed file system ?
(like Spanner or BigTable-like systems e.g. https://github.com/baidu/tera)

It would be useful also to explain this decision (pros/cons) for users of cockroach

Jira issue: CRDB-6129

**Comment by spencerkimball** [comment]
We have thought about it. It would be fairly straightforward to add this capability to CockroachDB than building it from scratch, although it's still a non-trivial amount of work. There's a really old issue discussing this: https://github.com/cockroachdb/cockroach/issues/243. Also, some preliminary work on an RFC: https://github.com/cockroachdb/cockroach/blob/spencerkimball/egg-store/docs/RFCS/egg_store.md

**Comment by jianjin** [comment]
spencerkimball@, the link you posted is 404. Is it moved to another place? if so, can you update using the new link?

For  "add this capability to CockraochDB",  Does what you mean the filesystem is on top of CockroachDB?

**Comment by Bessonov** [comment]
Interesting idea.

**Comment by Bessonov** [comment]
a comment will keep it active
