### ISSUE TITLE
sql: excessive event/request logging

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#12355]
`sql.Executor` now logs the executed sql statement 4 times:
* To the session event log in `sql.Executor.Prepare`.
* To the session event log in `sql.Executor.execRequest`.
* To the transaction request log in `sql.Executor.execStmtsInCurrentTxn`.
* To the session event log in `sql.Executor.execStmtInOpenTxn`.

This is a bit excessive and was noticeable on profiles. In particular, local `block_writer` tests see a 6% improvement if I disable the session event log. That's a hefty hammer so I'm not going to wield it myself.

The `sql.Executor` tracing code originally used a single `trace.Trace` for the session which allowed the use of `Trace.Lazy{Printf,Log}`. I realize that didn't play nicely with lightstep traces, but it  mirrored the use of a `trace.Trace` per connection in gRPC.

**Comment by RaduBerinde** [comment]
In addition to removing the duplicate logging, we could add a lazy interface to the `net/trace` event log.

**Comment by RaduBerinde** [comment]
Filed https://github.com/golang/go/issues/18320

**Comment by bdarnell** [comment]
Logging of SQL statements is also a security concern - deployments need to be able to disable all logging of full statements and/or limit such logging to destinations that can be properly secured. I'd argue that eventually, logging of sql statements should be opt-in, although while we're in beta we should definitely err on the side of logging too much.

**Comment by dianasaur323** [comment]
Also related to https://github.com/cockroachdb/cockroach/issues/14589 I believe.

**Comment by RaduBerinde** [comment]
The session event log was disabled in #13366. I think things are ok for 1.0. Moving to 1.1 to look into improving the performance and logic of logging statements.

**Comment by andreimatei** [comment]
The logging has changed. Closing this.
