### ISSUE TITLE
sql: hash joins don't use equality columns

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#12358]
While investigating #12311, I noticed that joins do not properly mark equality columns. This causes all right-hand columns to hash to the same value, the degenerate case for hash joins.

The problem may stem from `join_predicate.optimizeOnPredicate`, which seems to currently fail to correctly determine the set of equality indices.

**Comment by irfansharif** [comment]
cc @knz.

**Comment by jordanlewis** [comment]
Update: This occurs only in `FULL OUTER JOIN`, and there's nothing wrong with `optimizeOnPredicate`. The problem is that we keep track of which *buckets* we've seen for resolving the full outer join, but not which *rows*. This causes missing rows in the output when there is more than one row in each bucket.

Fix is forthcoming.

**Comment by jordanlewis** [comment]
Closing this in favor of #12311 as the bug is explained by that issue.
