### ISSUE TITLE
file write stall detected: disk slowness detected: write on file 24856607.sst (4096 bytes) has been ongoing for 83.5s

### ISSUE THREAD

**Issue by mzimmerman** [cockroachdb/cockroach#123552]
**Describe the problem**

4 node cluster under heavy write load, approximately 1 million records per minute

**To Reproduce**

Insert lots of records as fast as we can.

If possible, provide steps to reproduce the behavior:

This is a complex custom application working on sensitive data, so not easy to reproduce outside of the environment/data.

**Expected behavior**
Not to crash.

**Additional data / screenshots**
`F240502 23:55:46.268103 338424495 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 549369  file write stall detected: disk slowness detected: write on file 24856607.sst (4096 bytes) has been ongoing for 83.5s
F240502 23:55:46.268103 338424495 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 549369 !goroutine 338424495 [running]:
F240502 23:55:46.268103 338424495 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 549369 !runtime/debug.Stack()
F240502 23:55:46.268103 338424495 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 549369 !      GOROOT/src/runtime/debug/stack.go:24 +0x5e
F240502 23:55:46.268103 338424495 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 549369 !github.com/cockroachdb/cockroach/pkg/util/log.(*loggerT).outputLogEntry(_, {{{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}}, ...})
F240502 23:55:46.268103 338424495 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 549369 !      github.com/cockroachdb/cockroach/pkg/util/log/clog.go:280 +0xe7
F240502 23:55:46.268103 338424495 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 549369 !github.com/cockroachdb/cockroach/pkg/util/log.logfDepthInternal({0x77b14f8, 0xc001a9a480}, 0x2, 0x4, 0x0, 0x0?, {0x61681ed, 0x1d}, {0xc954cc1df0, 0x1, ...})
F240502 23:55:46.268103 338424495 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 549369 !      github.com/cockroachdb/cockroach/pkg/util/log/channels.go:109 +0x585
F240502 23:55:46.268103 338424495 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 549369 !github.com/cockroachdb/cockroach/pkg/util/log.logfDepth(...)
F240502 23:55:46.268103 338424495 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 549369 !      github.com/cockroachdb/cockroach/pkg/util/log/channels.go:39
F240502 23:55:46.268103 338424495 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 549369 !github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(...)
F240502 23:55:46.268103 338424495 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 549369 !      github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/util/log/log_channels_generated.go:848
F240502 23:55:46.268103 338424495 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 549369 !github.com/cockroachdb/cockroach/pkg/storage.(*Pebble).makeMetricEtcEventListener.func4({{0xccd6642500, 0x19}, 0x1, 0x1000, 0x13702d9494})
F240502 23:55:46.268103 338424495 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 549369 !      github.com/cockroachdb/cockroach/pkg/storage/pebble.go:1525 +0x1cd
F240502 23:55:46.268103 338424495 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 549369 !github.com/cockroachdb/pebble.TeeEventListener.func4({{0xccd6642500, 0x19}, 0x1, 0x1000, 0x13702d9494})
F240502 23:55:46.268103 338424495 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 549369 !      github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/event.go:706 +0x4a
F240502 23:55:46.268103 338424495 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 549369 !github.com/cockroachdb/cockroach/pkg/storage.wrapFilesystemMiddleware.func1({{0xccd6642500, 0x19}, 0x1, 0x1000, 0x13702d9494})
F240502 23:55:46.268103 338424495 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 549369 !      github.com/cockroachdb/cockroach/pkg/storage/pebble.go:790 +0x91
F240502 23:55:46.268103 338424495 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 549369 !github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFS).Create.func2(0x54?, 0x22a9236d96ef?, 0xbf5d8a0?)
F240502 23:55:46.268103 338424495 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 549369 !      github.com/cockroachdb/pebble/vfs/external/com_github_cockroachdb_pebble/vfs/disk_health.go:646 +0x65
F240502 23:55:46.268103 338424495 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 549369 !github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker.func1()
F240502 23:55:46.268103 338424495 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 549369 !      github.com/cockroachdb/pebble/vfs/external/com_github_cockroachdb_pebble/vfs/disk_health.go:186 +0x1c4
F240502 23:55:46.268103 338424495 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 549369 !created by github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker in goroutine 338416765
F240502 23:55:46.268103 338424495 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 549369 !      github.com/cockroachdb/pebble/vfs/external/com_github_cockroachdb_pebble/vfs/disk_health.go:166 +0x58`

Looking at the metrics for that node prior to the crash, this is the only thing I see out of the ordinary on the "overload" page.
![image](https://github.com/cockroachdb/cockroach/assets/2413139/c6f7808a-4d1b-4f54-b65f-19f2f243e906)

The IO on that node (yellow) was actually less than others that didn't crash:
![image](https://github.com/cockroachdb/cockroach/assets/2413139/196fa6ad-153d-4efd-9814-6d9c06b82c6a)
**Environment:**
cockroach version
```
Build Tag:        v23.2.4
Build Time:       2024/04/08 21:52:09
Distribution:     CCL
Platform:         linux amd64 (x86_64-pc-linux-gnu)
Go Version:       go1.21.8 X:nocoverageredesign
C Compiler:       gcc 6.5.0
Build Commit ID:  e3276dc8c5e041aabc787bba43193e638103f31f
Build Type:       release
Enabled Assertions: false
```
 - Server OS:
```
uname -a
Linux m1 5.15.0-101-generic #111-Ubuntu SMP Tue Mar 5 20:16:58 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```
 - Client app
```
github.com/jackc/pgx/v5 v5.5.1
```

**Additional context**
Restarting the service takes just ~20 seconds for it to be back up.

These are NVMe disks in a hardware Raid0 configuration -- I don't think it's possible for them to block on this operation for this long at a hardware level

Jira issue: CRDB-38395

**Comment by mzimmerman** [comment]
[cockroach-pebble.log](https://github.com/cockroachdb/cockroach/files/15200544/cockroach-pebble.log)

**Comment by jbowens** [comment]
There's not much we can say other than the a `write` syscall did not complete within 83.5s. This can be because of an operating system bug, a disk controller bug, disk overload, etc. This is _not_ in a public cloud environment, correct?

**Comment by mzimmerman** [comment]
Correct, this is on-premise hardware -- the server is doing other things, but not heavily loaded at all at the moment.
```
sudo cat /proc/meminfo  | head
MemTotal:       1056239628 kB
sudo cat /proc/cpuinfo | grep -i processor | wc -l
192
sudo cat /proc/cpuinfo | grep  -i "model name" | head -n 1
model name      : Intel(R) Xeon(R) Platinum 8160 CPU @ 2.10GHz
sudo mdadm -D /dev/md127
/dev/md127:
           Version : 1.2
     Creation Time : Mon Feb 26 18:37:26 2024
        Raid Level : raid0
        Array Size : 10938764288 (10.19 TiB 11.20 TB)
      Raid Devices : 7
sudo hdparm -t -T /dev/md127

/dev/md127:
 Timing cached reads:   15746 MB in  1.98 seconds = 7937.34 MB/sec
 Timing buffered disk reads: 4692 MB in  3.00 seconds = 1562.67 MB/sec
```
If it helps, we were getting very similar panic's on version v23.2.0 with less time (28.9s, saw some others too but didn't capture them)
