### ISSUE TITLE
oidcccl: HTTP client should respect timeouts

### ISSUE THREAD

**Issue by dhartunian** [cockroachdb/cockroach#123605]
**Describe the problem**

Currently, the HTTP client used by the code in the OIDC feature does not respect any timeouts we might have set on our default http client.

Internal client timeout:
https://github.com/cockroachdb/cockroach/blob/a892ee8fb3a9daaefea00afe064cb7d975075b8e/pkg/util/httputil/client.go#L26

OIDC Provider:
https://github.com/cockroachdb/cockroach/blob/44d7da514c7c0d21411fa31caaa59457b413540a/pkg/ccl/oidcccl/authentication_oidc.go#L259

Requests made here:
https://github.com/cockroachdb/cockroach/blob/44d7da514c7c0d21411fa31caaa59457b413540a/pkg/ccl/oidcccl/authentication_oidc.go#L226-L230

We should consider adding the timeout to the HTTP context, or overriding the client used in the OIDC library if possible.

Jira issue: CRDB-38416

**Comment by pritesh-lahoti** [comment]
Fixed as part of https://github.com/cockroachdb/cockroach/pull/125767
