### ISSUE TITLE
cdc: wrong behaviour upon resuming for initial scan

### ISSUE THREAD

**Issue by wenyihu6** [cockroachdb/cockroach#123623]
**Describe the problem**

In #102717, we introduced a mechanism to reduce message duplicates by re-loading job progress upon resuming. However, this pr forgot to account initial scans. During initial scans, we rely on an important prerequisite (resolved timestamps of all spans are required to be empty by keeping initial highwater as zero). This pr forwarded spans with resolved timestamps to its most up to date status in `reconcileJobStateWithLocalState`. This resulted in dropping events since we now sometimes make a new frontier with all spans forwarded to initialResolved https://github.com/cockroachdb/cockroach/blob/df196391c576f3a26e57ad6d694ee7e793c1af81/pkg/ccl/changefeedccl/changefeed_processors.go#L535. We should add more test coverage and re-think through the logic here though. 

We later found out that https://github.com/cockroachdb/cockroach/commit/afb95b17f30e3099ad182c56ab5376ed3c3d878f also did a similar thing where they [forward](https://github.com/cockroachdb/cockroach/blob/51ff3a711974c0a25210bccc988b64a0412869ed/pkg/ccl/changefeedccl/changefeed_dist.go#L410) job progress using checkpoint spans which could result in non-empty resolved timestamps in watches and dropping events during initial scans as well. 

Jira issue: CRDB-38432

**Comment by rharding6373** [comment]
Let's close this in favor of https://github.com/cockroachdb/cockroach/issues/123371.
