### ISSUE TITLE
The dead node holds a lease and has a blocking effect on the alter statement

### ISSUE THREAD

**Issue by liwei330249526** [cockroachdb/cockroach#123743]
**Describe the problem**

The dead node holds a lease and has a blocking effect on the alter statement

**To Reproduce**

1.  Start a three node cluster
2. create table t1(a int);
3. on node1,  select * from t1;
4. on node2,  select * from t1;
5. pkill -9  node2
6. on node1, alter table t1 add column a;   It will block for 5 minutes。

**Expected behavior**
 Expect to ignore the impact of dead nodes on alter statements

Jira issue: CRDB-38521

**Comment by fqazi** [comment]
@liwei330249526 Can you confirm which version of CRDB this scenario was run on? Also were any cluster settings customized?

**Comment by rafiss** [comment]
Thanks for the report @liwei330249526. Also, do you know how soon after the cluster startup did you perform the test? (It's possible not all data was replicated yet.)

**Comment by fqazi** [comment]
@liwei330249526 Trying this on master with roachprod local, I wasn't able to reproduce this either. We recover once the liveness expires for the killed node and the schema change continues.

**Comment by liwei330249526** [comment]
> @liwei330249526 Trying this on master with roachprod local, I wasn't able to reproduce this either. We recover once the liveness expires for the killed node and the schema change continues.

**Comment by liwei330249526** [comment]
> @liwei330249526 Trying this on master with roachprod local, I wasn't able to reproduce this either. We recover once the liveness expires for the killed node and the schema change continues.

**Comment by liwei330249526** [comment]
> Thanks for the report @liwei330249526. Also, do you know how soon after the cluster startup did you perform the test? (It's possible not all data was replicated yet.) Also, could you share which CRDB version you tested with?

cockroach-v23.1.12.linux-amd64

**Comment by liwei330249526** [comment]
@fqazi  @rafiss 

cockroach-v23.1.12.linux-amd64， I reproduced it on this version, but not tested in the master branch due to local compilation environment.

**Comment by fqazi** [comment]
@liwei330249526 Let me try reproducing on that branch

**Comment by fqazi** [comment]
@liwei330249526 I had no luck reproducing on the same version, on default settings the ALTER blocks for less than 5 minutes. Can you reproduce this and provide a debug.zip from your cluster? Not sure if you have sensitive data, if you do the you can directly submit to me at:  https://upload.cockroachlabs.com/u/faizan

**Comment by liwei330249526** [comment]
@fqazi  yes, ALTER blocks  block for 5 minutes;   Wrote incorrectly at first

**Comment by fqazi** [comment]
Ah, thats working as designed and the behaviour of the leasing subsystem: https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20151009_table_descriptor_lease.md. 

Before 24.1 CRDB uses a expiry leasing mechanism for table descriptors (i.e. table metadata), when a table is accessed a lease is acquired with an expiration (based on the lease duration, which defaults to 5 minutes). This mechanism is cooperative, so once a new version is written, if the old descriptor version can be released if no transactions on a node are using it. When doing a schema change we wait for all old versions of a descriptor to be no longer in use, so either the cooperative mechanism needs to take effect or the lease has to expire (i.e. up to 5 minutes later if a node crashes).

**Comment by liwei330249526** [comment]
So, did crdb redesign the lease mechanism after 24.1?   no need to wait for 5 minutes if  a node crashes?

**Comment by fqazi** [comment]
@liwei330249526 Yes in 24.1 we moved a session based SQL leasing, so now the expiry is tied to the system.sqlliveness table.  The recovery time for this scenario should be at most 45 seconds because of that change, the other benefit is that SQL leases have less background resource usage now (since there is no heartbeating).
