### ISSUE TITLE
Sentry: logstore.go:496: there is a gap at index 7957689452319564909
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | [...repeated from below...]...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#123880]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5325804118/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5325804118/?referrer=webhooks_plugin)

Panic Message:

```
logstore.go:496: there is a gap at index 7957689452319564909
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | [...repeated from below...]
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/logstore.LoadTerm
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/logstore/logstore.go:496
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*replicaRaftStorage).Term
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raftstorage.go:113
  | go.etcd.io/raft/v3.(*raftLog).term
  | 	go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/log.go:399
  | go.etcd.io/raft/v3.(*raftLog).lastTerm
  | 	go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/log.go:374
  | go.etcd.io/raft/v3.newRaft
  | 	go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/raft.go:478
  | go.etcd.io/raft/v3.NewRawNode
  | 	go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/rawnode.go:52
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).withRaftGroupLocked
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:1989
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).maybeInitializeRaftGroup
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_init.go:317
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).SendWithWriteBytes
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go:145
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).Send
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go:117
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*pendingLeaseRequest).requestLease
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_range_lease.go:549
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*pendingLeaseRequest).requestLeaseAsync.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_range_lease.go:397
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470
  | runtime.goexit
  | 	src/runtime/asm_arm64.s:1172
Wraps: (3) there is a gap at index 7957689452319564909
Error types: (1) *withstack.withStack (2) *withstack.withStack (3) *errutil.leafError
-- report composition:
*errutil.leafError: there is a gap at index 7957689452319564909
logstore.go:496: *withstack.withStack (top exception)
panic.go:884: *withstack.withStack (1)
(check the extra data payloads)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_arm64.s#L1171-L1173](src/runtime/asm_arm64.s#L1171-L1173)
[https://github.com/cockroachdb/cockroach/blob/93a67980ee45391b8ef02d40a6d50ddb0245817b/pkg/util/stop/stopper.go#L469-L471](https://github.com/cockroachdb/cockroach/blob/93a67980ee45391b8ef02d40a6d50ddb0245817b/pkg/util/stop/stopper.go#L469-L471)
[https://github.com/cockroachdb/cockroach/blob/93a67980ee45391b8ef02d40a6d50ddb0245817b/pkg/kv/kvserver/pkg/kv/kvserver/replica_range_lease.go#L396-L398](https://github.com/cockroachdb/cockroach/blob/93a67980ee45391b8ef02d40a6d50ddb0245817b/pkg/kv/kvserver/pkg/kv/kvserver/replica_range_lease.go#L396-L398)
[https://github.com/cockroachdb/cockroach/blob/93a67980ee45391b8ef02d40a6d50ddb0245817b/pkg/kv/kvserver/pkg/kv/kvserver/replica_range_lease.go#L548-L550](https://github.com/cockroachdb/cockroach/blob/93a67980ee45391b8ef02d40a6d50ddb0245817b/pkg/kv/kvserver/pkg/kv/kvserver/replica_range_lease.go#L548-L550)
[https://github.com/cockroachdb/cockroach/blob/93a67980ee45391b8ef02d40a6d50ddb0245817b/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go#L116-L118](https://github.com/cockroachdb/cockroach/blob/93a67980ee45391b8ef02d40a6d50ddb0245817b/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go#L116-L118)
[https://github.com/cockroachdb/cockroach/blob/93a67980ee45391b8ef02d40a6d50ddb0245817b/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go#L144-L146](https://github.com/cockroachdb/cockroach/blob/93a67980ee45391b8ef02d40a6d50ddb0245817b/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go#L144-L146)
[https://github.com/cockroachdb/cockroach/blob/93a67980ee45391b8ef02d40a6d50ddb0245817b/pkg/kv/kvserver/pkg/kv/kvserver/replica_init.go#L316-L318](https://github.com/cockroachdb/cockroach/blob/93a67980ee45391b8ef02d40a6d50ddb0245817b/pkg/kv/kvserver/pkg/kv/kvserver/replica_init.go#L316-L318)
[https://github.com/cockroachdb/cockroach/blob/93a67980ee45391b8ef02d40a6d50ddb0245817b/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L1988-L1990](https://github.com/cockroachdb/cockroach/blob/93a67980ee45391b8ef02d40a6d50ddb0245817b/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L1988-L1990)
[go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/rawnode.go#L51-L53](go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/rawnode.go#L51-L53)
[go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/raft.go#L477-L479](go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/raft.go#L477-L479)
[go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/log.go#L373-L375](go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/log.go#L373-L375)
[go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/log.go#L405-L407](go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/log.go#L405-L407)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
[src/runtime/asm_arm64.s#L1171-L1173](src/runtime/asm_arm64.s#L1171-L1173)
[https://github.com/cockroachdb/cockroach/blob/93a67980ee45391b8ef02d40a6d50ddb0245817b/pkg/util/stop/stopper.go#L469-L471](https://github.com/cockroachdb/cockroach/blob/93a67980ee45391b8ef02d40a6d50ddb0245817b/pkg/util/stop/stopper.go#L469-L471)
[https://github.com/cockroachdb/cockroach/blob/93a67980ee45391b8ef02d40a6d50ddb0245817b/pkg/kv/kvserver/pkg/kv/kvserver/replica_range_lease.go#L396-L398](https://github.com/cockroachdb/cockroach/blob/93a67980ee45391b8ef02d40a6d50ddb0245817b/pkg/kv/kvserver/pkg/kv/kvserver/replica_range_lease.go#L396-L398)
[https://github.com/cockroachdb/cockroach/blob/93a67980ee45391b8ef02d40a6d50ddb0245817b/pkg/kv/kvserver/pkg/kv/kvserver/replica_range_lease.go#L548-L550](https://github.com/cockroachdb/cockroach/blob/93a67980ee45391b8ef02d40a6d50ddb0245817b/pkg/kv/kvserver/pkg/kv/kvserver/replica_range_lease.go#L548-L550)
[https://github.com/cockroachdb/cockroach/blob/93a67980ee45391b8ef02d40a6d50ddb0245817b/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go#L116-L118](https://github.com/cockroachdb/cockroach/blob/93a67980ee45391b8ef02d40a6d50ddb0245817b/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go#L116-L118)
[https://github.com/cockroachdb/cockroach/blob/93a67980ee45391b8ef02d40a6d50ddb0245817b/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go#L144-L146](https://github.com/cockroachdb/cockroach/blob/93a67980ee45391b8ef02d40a6d50ddb0245817b/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go#L144-L146)
[https://github.com/cockroachdb/cockroach/blob/93a67980ee45391b8ef02d40a6d50ddb0245817b/pkg/kv/kvserver/pkg/kv/kvserver/replica_init.go#L316-L318](https://github.com/cockroachdb/cockroach/blob/93a67980ee45391b8ef02d40a6d50ddb0245817b/pkg/kv/kvserver/pkg/kv/kvserver/replica_init.go#L316-L318)
[https://github.com/cockroachdb/cockroach/blob/93a67980ee45391b8ef02d40a6d50ddb0245817b/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L1988-L1990](https://github.com/cockroachdb/cockroach/blob/93a67980ee45391b8ef02d40a6d50ddb0245817b/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L1988-L1990)
[go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/rawnode.go#L51-L53](go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/rawnode.go#L51-L53)
[go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/raft.go#L477-L479](go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/raft.go#L477-L479)
[go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/log.go#L373-L375](go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/log.go#L373-L375)
[go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/log.go#L398-L400](go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/log.go#L398-L400)
[https://github.com/cockroachdb/cockroach/blob/93a67980ee45391b8ef02d40a6d50ddb0245817b/pkg/kv/kvserver/pkg/kv/kvserver/replica_raftstorage.go#L112-L114](https://github.com/cockroachdb/cockroach/blob/93a67980ee45391b8ef02d40a6d50ddb0245817b/pkg/kv/kvserver/pkg/kv/kvserver/replica_raftstorage.go#L112-L114)
[https://github.com/cockroachdb/cockroach/blob/93a67980ee45391b8ef02d40a6d50ddb0245817b/pkg/kv/kvserver/logstore/logstore.go#L495-L497](https://github.com/cockroachdb/cockroach/blob/93a67980ee45391b8ef02d40a6d50ddb0245817b/pkg/kv/kvserver/logstore/logstore.go#L495-L497)
</details>

```
src/runtime/asm_arm64.s in runtime.goexit at line 1172
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 470
pkg/kv/kvserver/pkg/kv/kvserver/replica_range_lease.go in pkg/kv/kvserver.(*pendingLeaseRequest).requestLeaseAsync.func1 at line 397
pkg/kv/kvserver/pkg/kv/kvserver/replica_range_lease.go in pkg/kv/kvserver.(*pendingLeaseRequest).requestLease at line 549
pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go in pkg/kv/kvserver.(*Replica).Send at line 117
pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go in pkg/kv/kvserver.(*Replica).SendWithWriteBytes at line 145
pkg/kv/kvserver/pkg/kv/kvserver/replica_init.go in pkg/kv/kvserver.(*Replica).maybeInitializeRaftGroup at line 317
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).withRaftGroupLocked at line 1989
go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/rawnode.go in go.etcd.io/raft/v3.NewRawNode at line 52
go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/raft.go in go.etcd.io/raft/v3.newRaft at line 478
go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/log.go in go.etcd.io/raft/v3.(*raftLog).lastTerm at line 374
go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/log.go in go.etcd.io/raft/v3.(*raftLog).term at line 406
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
src/runtime/asm_arm64.s in runtime.goexit at line 1172
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 470
pkg/kv/kvserver/pkg/kv/kvserver/replica_range_lease.go in pkg/kv/kvserver.(*pendingLeaseRequest).requestLeaseAsync.func1 at line 397
pkg/kv/kvserver/pkg/kv/kvserver/replica_range_lease.go in pkg/kv/kvserver.(*pendingLeaseRequest).requestLease at line 549
pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go in pkg/kv/kvserver.(*Replica).Send at line 117
pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go in pkg/kv/kvserver.(*Replica).SendWithWriteBytes at line 145
pkg/kv/kvserver/pkg/kv/kvserver/replica_init.go in pkg/kv/kvserver.(*Replica).maybeInitializeRaftGroup at line 317
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).withRaftGroupLocked at line 1989
go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/rawnode.go in go.etcd.io/raft/v3.NewRawNode at line 52
go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/raft.go in go.etcd.io/raft/v3.newRaft at line 478
go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/log.go in go.etcd.io/raft/v3.(*raftLog).lastTerm at line 374
go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/log.go in go.etcd.io/raft/v3.(*raftLog).term at line 399
pkg/kv/kvserver/pkg/kv/kvserver/replica_raftstorage.go in pkg/kv/kvserver.(*replicaRaftStorage).Term at line 113
pkg/kv/kvserver/logstore/logstore.go in pkg/kv/kvserver/logstore.LoadTerm at line 496
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v23.1.20 |
| Go Version | go1.19.13 |
| Platform | linux arm64 |
| Distribution | CCL |
| Cockroach Release | v23.1.20 |
| Cockroach SHA | 93a67980ee45391b8ef02d40a6d50ddb0245817b |
| # of CPUs | 10 |
| # of Goroutines | 269 |

Jira issue: CRDB-38587

**Comment by yuzefovich** [comment]
unactionable
