### ISSUE TITLE
kv: implement leader leases

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#123847]
We want the properties of expiration-based leases, but without the cost of a replicated write per range every 3 seconds, and without the cost of ticking/heartbeating Raft ranges. In particular, we want to ensure the lease is functional (can process reads and replicated writes) and that it eagerly acquires leases.

From the [current working design doc](https://docs.google.com/document/d/1KwuDVaRvLEYb77QLb_3eqjOj-RRGHwRtY2I1e5iMMiM/edit?usp=sharing):
> Our goal is per-range raft leadership and range leasing with quorum availability and without the cost of per-range heartbeating. Connectivity to the other voting replica stores for a range is needed to retain leadership and, by extension, leaseholdership.

See the design doc for details on how this will be accomplished, the resulting scaling behavior, and the architectural simplifications that fall out.

Subtasks:
- [x] fix Leader lease interactions in proposal buffer
- [x] make sure quiescence works with leader leases

Jira issue: CRDB-38570

Epic CRDB-37522

**Comment by mohanr-rubrik** [comment]
@nvanbenschoten Can the design doc be made public if the design is finalized? Just curious to see the proposed protocol

**Comment by nvanbenschoten** [comment]
Now that leader leases are implemented, I'll close this issue and shift the remaining work over to https://github.com/cockroachdb/cockroach/issues/132762.
