### ISSUE TITLE
sql: dynamically determine histogram sample size

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#123972]
To collect histograms in table statistics, we currently sample 10k rows. 

The number of rows sampled when building histograms for table statistics is 10k, and it can be configured with [`sql.stats.histogram_samples.count`](https://www.cockroachlabs.com/docs/stable/cluster-settings#setting-sql-stats-histogram-samples-count). 

For very large table, this is too few rows. We should find a way to dynamically adjust the sample size based on the size of the table.

See this discussion for more context: https://cockroachlabs.slack.com/archives/C01RX2G8LT1/p1701834921110179?thread_ts=1701825005.623189&cid=C01RX2G8LT1

Jira issue: CRDB-38633

**Comment by nitesh-dubey** [comment]
Hi, @mgartner @michae2 Is this an internal issue, or is it available for contributors to pick up ?
The JIRA and slack link mentioned, which might contain more context are internal.

**Comment by michae2** [comment]
Hi @nitesh-dubey, thanks for your interest! We are planning to assign this to someone internal soon, so it would be better to pick up another issue if you don't mind. Maybe one tagged with ["good first issue" or E-starter or E-quick-win](https://github.com/cockroachdb/cockroach/issues?q=is%3Aopen+label%3A%22good+first+issue%22%2CE-starter%2CE-quick-win) would be good.

**Comment by nitesh-dubey** [comment]
I see...thanks @michae2 !
I'll go ahead and look at the issues with tags you suggested.
