### ISSUE TITLE
schema: Improve visibility into long running schema changes

### ISSUE THREAD

**Issue by rimadeodhar** [cockroachdb/cockroach#124075]
We lack visibility into long running schema changes. Investigating why a schema change is slow often involves sifting through logs to piece together the clues. To address this, we propose developing new debug tools similar to statement bundles to gather additional details on schema jobs. Leveraging existing job bundle tooling, we can extend its capabilities to output more information specifically for schema jobs, enhancing observability into schema changes.

There is some ambiguity here in terms of what observability will help here. As a starting point, we should look at what information is collected through job bundles and determine how to hook into that to add schema specific information.

Jira issue: CRDB-38686

Epic CRDB-38033

**Comment by spilchen** [comment]
To improve the visibility of long-running schema changes, I propose the following:

1. **Retain Trace Events**: Keep trace events and persist them after the schema change. This includes lower-level stats collected in the KV layer, which will help us understand where time is being spent.
   
2. **Collect Timing Stats**: Gather statistics on the time spent in `WaitForOneVersion` and `WaitForNoVersion`, and include these stats in the retained trace events for review after the schema change.

3. **Pretty Print Current Plan**: Provide a formatted output of the current running phase plan, similar to `EXPLAIN (DDL) ...`. This will be available on request through the job profiler in the DBConsole (under 'Jobs -> Advanced Debugging -> Request Execution Details'). This will clarify the status field (e.g., PostCommitPhase stage 2 of 7 with 1 BackfillType op pending) by showing the stages within the phase.

**Comment by spilchen** [comment]
For 2, one comment was to store aggregated stats. But to store aggregated stats, we need a way to anchor them for later retrieval. The `TracingAggregator` struct seems suitable for this purpose, but I'm unsure how to access it from within `WaitForOneAction`/`WaitForNoAction`. These functions are fairly generic and are used outside of schema changes as well. 

I don't think it's worth the effort to aggregate these stats inside the trace. If there are many instances, we would likely be most concerned with the latest active one when debugging something currently running. For debugging a finished instance, we can manually sum up the stats as needed.
