### ISSUE TITLE
geo: higher precision for DefaultGeoJSONDecimalDigits 

### ISSUE THREAD

**Issue by wenyihu6** [cockroachdb/cockroach#124175]
**Is your feature request related to a problem? Please describe.**

Currently, the number of decimal digits coordinates in GeoJSON is hardcoded at 9
via the [DefaultGeoJSONDecimalDigits](https://github.com/cockroachdb/cockroach/blob/4d52f96d8ed97a4068f426c1b63c8a69d55fd356/pkg/geo/encode.go#L36) constant. A customer wants a higher precision 
in this escalation https://github.com/cockroachlabs/support/issues/2946. Is it possible to increase the 
default decimal digits or make this number configurable?

If this is not something we want to support, are there any workarounds for this?
I recommended adding a new column using the built in function `ST_AsText()`, but I
was wondering if there are better options here.

Jira issue: CRDB-38745

**Comment by wenyihu6** [comment]
I heard SQL queries is owning the geo package now. Feel free to re-direct if not.

**Comment by rharding6373** [comment]
I tested that `const DefaultGeoJSONDecimalDigits = -1` allows arbitrary precision. I guessed this by reading the library source code. It's not documented anyway AFAICT.
