### ISSUE TITLE
UI: misc node fixes

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#12421]
Misc fixes for the nodes overview page:

- Started should be changed to something that show how long it's been alive for, and for dead store, the last time it was seen alive (or some combo)
- Total CPU Usage... is not useful.  Is this stat useful at all?
- Some load statistics would be nice.

**Comment by mrtracy** [comment]
The first two suggestions have been dealt with (except for dead nodes, but that is being tracked in a few other issues).

We previously had active connections on this table, but we don't currently; that's more of a suggestion than a fix though, but we're going to need broader research to nail down the most valuable columns.
