### ISSUE TITLE
ui: dead stores contribute to the totals

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#12422]
For example, total replica count should be 
534 ranges * 3 = 1602
And if you add up the replicas with the dead nodes you get 1931
And without the dead nodes 1602 

I'm assuming this is true for all other aggregates as well.

Note: screenshot not taken at same time as my back of the envelope calcs.
![screen shot 2016-12-15 at 14 00 11](https://cloud.githubusercontent.com/assets/1614265/21237903/dce0d480-c2ce-11e6-98b6-b80139353456.png)

**Comment by arjunravinarayan** [comment]
This seems like the way things should be - a node/store that can't be reached should still count (particularly for the BYTES column), until that range is upreplicated elsewhere and downreplicated from that dead store (i.e. the cluster has "given up" on that replica). Is your point that even after that latter event its still counted? We shouldn't reduce the replica count or the total data size as soon as a store goes down - it could just be a temporary network partition, and the data is still durable and safe.

**Comment by BramGruneir** [comment]
I'm talking about dead stores and nodes here.  Nodes that have been down for more than 5min, or much longer.  Here's an updated screenshot, most of these have been down for more than 6 hours.
<img width="1311" alt="screen shot 2016-12-15 at 21 46 39" src="https://cloud.githubusercontent.com/assets/1614265/21250025/0c97b644-c310-11e6-9aa5-03244850295c.png">

**Comment by BramGruneir** [comment]
To add to this, the total nodes and space used on the main page is also still counting long dead nodes.

**Comment by mrtracy** [comment]
This has been made obsolete by the removal of totals from this page.

**Comment by mrtracy** [comment]
Ehh, scratch that, there are still a few summary stats that are affected by this.

**Comment by mrtracy** [comment]
Excluding dead nodes is straightforward, but here's a more nuanced question: what about nodes that are in the stale "yellow" state?  I think that we should still include those in the totals, but I'm open to arguments otherwise.

**Comment by BramGruneir** [comment]
Yes, I agree, yellow state should be included in the stats.
