### ISSUE TITLE
workload: tpcc workload fails after after period with decimal errors

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#124259]
After running TPCC for a week, the workload starts to fail with error of the form ` workload/cli/run.go:569  [-] 1622  error in payment: update warehouse failed: ERROR: type DECIMAL(12,2): value with precision 12, scale 2 must round to an absolute value less than 10^10 (SQLSTATE 22003)`.

It appears that the accumulated balance for the warehouse grows indefinitely and eventually exceeds the decimal's bounds.

We should add an option for longer / continuous runs that avoids this, e.g. by resetting or periodically reducing this, or altering the schema, etc.

Jira issue: CRDB-38796

**Comment by nameisbhaskar** [comment]
adding warehouse table schema for reference:
`CREATE TABLE warehouse
(
    w_id        integer   not null primary key,
    w_name      varchar(10),
    w_street_1  varchar(20),
    w_street_2  varchar(20),
    w_city      varchar(20),
    w_state     char(2),
    w_zip       char(9),
    w_tax       decimal(4,4),
    w_ytd       decimal(12,2)
)
`
