### ISSUE TITLE
sql: get wrong timestamptz value using pooled connection

### ISSUE THREAD

**Issue by masayoshi-louis** [cockroachdb/cockroach#12432]
1. Please supply the header (i.e. the first few lines) of your most recent
   log file **for each node in your cluster**. On most unix-based systems
   running with defaults, this boils down to the output of

> I161216 09:34:06.077484 1 util/log/clog.go:1003  [config] file created at: 2016/12/16 09:34:06
> I161216 09:34:06.077484 1 util/log/clog.go:1003  [config] running on machine: db1
> I161216 09:34:06.077484 1 util/log/clog.go:1003  [config] binary: CockroachDB beta-20161215 (linux amd64, built 2016/12/15 15:10:48, go1.7.3)
> I161216 09:34:06.077484 1 util/log/clog.go:1003  [config] arguments: [cockroach start --host=db1 --attrs=bj1 --http-port=28080 --ca-cert=/var/lib/cockroach/ca.cert --cert=/var/lib/cockroach/node-cert/bj1.nodes.cert --key=/var/lib/cockroach/node-cert/bj1.nodes.key --store=/var/lib/cockroach/data,attrs=ssd --cache=4GB]

The config of the other two nodes are the same (except the host name).

2. Please describe the issue you observed:

- What did you do?

Connect to the server using c3p0 (and also hikariCP) + pg jdbc driver. The max pool size is set to 1.
Repeat a simple query "SELECT * FROM MyTable WHERE id = 'some string id'".

- What did you expect to see?
Correct values of TIMESTAMPTZ columns as they are stored in the db, like "2016-12-15T11:48:14.876Z".

- What did you see instead?
All TIMESTAMPTZ values become "2000-01-01T00:00:00Z" after the 5 queries (The first 5 queries return the correct values).

This issue only happen with pooled connections.

**Comment by masayoshi-louis** [comment]
My test program: [https://github.com/masayoshi-louis/cockroachdb-12432](https://github.com/masayoshi-louis/cockroachdb-12432)

**Comment by knz** [comment]
@masayoshi-louis please make a test program against your database that uses the jdbc interface directly, and check whether you can reproduce the behavior this way. This is to exclude Hikari from a possible cause of the problem. Thank you

**Comment by masayoshi-louis** [comment]
@knz Added: [Main2](https://github.com/masayoshi-louis/cockroachdb-12432/blob/master/src/main/java/Main2.java)

**Comment by knz** [comment]
Ok thanks.
Another question, how did you generate the data in the database?

**Comment by masayoshi-louis** [comment]
The SQL script:

create database test12432;
set database = 'test12432';
create table test1 (pk string primary key, value timestamptz);
insert into test1 values ('mykey', TIMESTAMPTZ '2016-03-26 10:10:10-05:00');

**Comment by dt** [comment]
Interestingly, `2000-01-01 00:00` is pewire's zero time.

**Comment by arjunravinarayan** [comment]
I have succeeded in replicating the issue. Thank you @masayoshi-louis for the well packaged example. I will investigate now.

**Comment by arjunravinarayan** [comment]
This happens even with just `TIMESTAMP`s, not just `TIMESTAMPTZ`s. It, however, does not happen with `DATE`s. It also does not require pooled connections, it happens even with a single JDBC connection of the form `"jdbc:postgresql://localhost:26257/test12432?user=user&password="`.

**Comment by christian-lefty** [comment]
Hi, I have been able to reproduce the same issue using JDBC:

    StringBuilder url = new StringBuilder()
        .append("jdbc:postgresql://")
        .append("HOST")
        .append(':')
        .append(26257)
        .append('/')
        .append("lefty_dev")
        .append("?user=")
        .append("root")
        .append("&sslcert=")
        .append("CERT"))
        .append("&sslkey=")
        .append("KEY"))
        .append("&sslmode=require&ssl=true");

    try (Connection conn = DriverManager.getConnection(url.toString())) {
      for (int i = 0; i < 50; ++i) {
        try (PreparedStatement stmt = conn.prepareStatement("select * from timestamps_test")) {
          try (ResultSet rs = stmt.executeQuery()) {
            Assert.assertTrue(rs.next());
            Assert.assertNotEquals("broke at index: " + i, 946681200000L, rs.getTimestamp(2).getTime());
          }
        }
      }
    }

This is assuming that timestamps_test is a table with (ID STRING, CREATED TIMESTAMP)

**Comment by christian-lefty** [comment]
It breaks at index 5

**Comment by arjunravinarayan** [comment]
Examining the packets in wireshark, using 
`tshark -i lo -f "tcp port 26257" -d tcp.port==26257,pgsql -O pgsql -Y pgsql` 
reveals that after the 5th instance, the JDBC client requests the result in a binary encoded format. Our binary encoded timestamps, introduced in #8590, are likely the culprit. Tracking that now.

**Comment by christian-lefty** [comment]
Hi arjun, would you know of any workaround that could be used in the meantime?

I tried adding "&binaryTransfer=false" as well as "binaryTransferDisable=TIMESTAMP" to the connection url but neither seems to do anything.

**Comment by arjunravinarayan** [comment]
The OID code for Timestamps is 1114, and `binaryTransferDisable=1114` makes things work for me. Can you try that? If you need to disable it for `TIMESTAMP_TZ` as well, you could use 1184 as well. I believe a comma separated list of numbers works if you need both of them.

We should be fixing this shortly, and this issue will track progress there. Let us know if this fix doesn't work for you in the interim.

**Comment by arjunravinarayan** [comment]
For reference, https://github.com/lib/pq/blob/master/oid/types.go#L87 is the mapping of types to OID codes, https://jdbc.postgresql.org/documentation/94/connect.html is the list of JDBC connection parameters where it says that you can specify OID codes or names.

Here is an example connection string that works
```
        String url = new StringBuilder()
            .append("jdbc:postgresql://")
            .append("HOST")
            .append(':')
            .append(PORT)
            .append('/')
            .append("db1")
            .append("?user=USER")
            .append("&sslmode=disable")
            .append("&ssl=false")
            .append("&binaryTransferDisable=1114")
            .Tostring();
```

**Comment by christian-lefty** [comment]
Great this works thanks a lot.
