### ISSUE TITLE
Dropped roles not removed from `crdb_internal_region` object

### ISSUE THREAD

**Issue by osmes** [cockroachdb/cockroach#124441]
**Describe the problem**

Dropped roles are not removed from `crdb_internal_region` object. This can have an effect of producing an error during `SHOW GRANTS;` execution like:
```
defaultdb> SHOW GRANTS;
ERROR: role/user "nobody" does not exist
SQLSTATE: 42704
```

**To Reproduce**

What did you do? Describe in your own words.

1. Created a 3 node cluster, with localities set to `region=west`, `region=central` and `region=east`.

2. Ran below SQL:
```
CREATE DATABASE db PRIMARY REGION "central";
ALTER DATABASE db ADD REGION "west";
ALTER DATABASE db ADD REGION "east";

USE db;

CREATE USER nobody;
GRANT ALL ON TYPE crdb_internal_region TO nobody;
DROP USER nobody;
```

3. Verify grant still exists inside `crdb_internal_region` enum object

4. Upgrade to 23.2 to observer `SHOW GRANTS;` erroring with `ERROR: role/user "nobody" does not exist`

**Expected behavior**
Grant should be dropped from `crdb_internal_region` enum when user is dropped. `SHOW GRANTS;` should not error.

**Additional data / screenshots**
Reproducing in 23.1.12, `SHOW GRANTS;` does not error after dropping the role. However, after upgrading to 23.2 or 24.1 the command starts to error.

**Environment:**
 - CockroachDB version 
23.1.12

Jira issue: CRDB-38898

Epic CRDB-37763

**Comment by rafiss** [comment]
@fqazi this looks related to https://github.com/cockroachdb/cockroach/pull/122557, but maybe something special with the region enum.

**Comment by fqazi** [comment]
Also reproduces easily on master, I think its being skipped in drop role, let me dig a bit

**Comment by fqazi** [comment]
Oh its generally broken for types, we don't seem to iterate over the users inside the privilege object 😬
