### ISSUE TITLE
storage: replica {3 3 3} not lease holder; current lease is repl={3 3 3}

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#12446]
The above error was seen while debugging flakiness in `TestRefreshPendingCommands`:

```
~ make stress PKG=./storage TESTS=TestRefreshPendingCommands STRESSFLAGS="-maxfails 1 -stderr -p 100" TESTTIMEOUT=1m TESTFLAGS='--vmodule=replica=4'
...
    --- FAIL: TestRefreshPendingCommands/#00 (1.56s)
    	client_raft_test.go:1001: range 1: replica {3 3 3} not lease holder; current lease is repl={3 3 3} start=0.900000123,17 exp=4.500000127,29 pro=3.600000127,30
FAIL


ERROR: exit status 1

841 runs completed, 1 failures, over 11s
FAIL
```

The logs show:

`I161216 15:27:02.500412 433 storage/replica.go:3305  [s1,r1/1:/M{in-ax},@c42038a480] command RequestLease [/Min,/Min) proposed from replica {NodeID:3 StoreID:3 ReplicaID:3}: leases repl={1 1 1} start=0.000000000,0 exp=4.500000127,29 and repl={3 3 3} start=0.900000123,17 exp=4.500000127,29 are not equivalent`

I'm not terribly familiar with this lease invariant code but something funky seems to be going on. Here is the [full output](https://github.com/cockroachdb/cockroach/files/657589/out.txt) from the test.

**Comment by petermattis** [comment]
The test is using expiration-based leases. For `RequestLease` operations we're supposed to skip the lease check, but we don't seem to be doing so correctly. In particular, this code looks suspicious:

```
	verifyLease := func() error {
		// Freeze commands do not verify lease.
		if raftCmd.BatchRequest.IsFreeze() {
			return nil
		}
		// Handle the case of pre-epoch-based-leases command.
		if raftCmd.OriginLease == nil {
			// Skip verification for lease commands for legacy case.
			if raftCmd.BatchRequest.IsSingleSkipLeaseCheckRequest() {
				return nil
			}
			l, origin := r.mu.state.Lease, raftCmd.OriginReplica
			if l.OwnedBy(origin.StoreID) && ts.Less(l.DeprecatedStartStasis) {
				return nil
			}
			return errors.Errorf("lease %s not held", l)
		}
		return raftCmd.OriginLease.Equivalent(*r.mu.state.Lease)
	}
```

`raftCmd.OriginLease` is not `nil`, but this is an expiration based lease and the old lease was held by a different node.

**Comment by petermattis** [comment]
Ok, here is the full scenario of what has happened:

* Node 3 is taken down
* The Raft log on nodes 1 and 2 are truncated ensuring that node 3 will be brought up to date via a snapshot
* Node 3 is restarted and a command is sent to it locally which generates a `RequestLease` request
* The `RequestLease` request is sent to the leader. Note that node 3 is still behind at this point.
* The leader (either node 1 or 2) and the follower (either node 1 or 2) commit and apply the `RequestLease` command.
* Node 3 receives a MsgApp for the `RequestLease` command, but rejects it because it isn't at the correct index. This triggers bringing node 3 up to date via a snapshot.
* Node 3 receives a snapshot that includes the `RequestLease` command it proposed.
* Node 3 re-proposes the `RequestLease` command because the snapshot triggered refreshing pending commands. Note that this `RequestLease` command has already been executed. 
* The second execution of the `RequestLease` command fails the `verifyLease` check because the lease that was present at the time the command was generated has changed.

Is there someway to make the `RequestLease` command idempotent by looking at the `roachpb.Lease`?

**Comment by tamird** [comment]
> Node 3 re-proposes the RequestLease command because the snapshot triggered refreshing pending commands. Note that this RequestLease command has already been executed.

Can you remind me why snapshots do this? I would expect that any pending commands covered by incoming snapshots would, upon application, be removed from the pending commands map.

**Comment by tamird** [comment]
OK, I think I see what's going on here - our handling of `MaxLeaseIndex` is incoherent. In one case (`(*Replica).processRaftCommand`) we ignore the `MaxLeaseIndex` if the command is a lease request (https://github.com/cockroachdb/cockroach/blob/8d9859c/pkg/storage/replica.go#L3306-L3311):
```
		// Lease commands are ignored by the counter (and their MaxLeaseIndex
		// is ignored). This makes sense since lease commands are proposed by
		// anyone, so we can't expect a coherent MaxLeaseIndex. Also, lease
		// proposals are often replayed, so not making them update the counter
		// makes sense from a testing perspective.
```
However, we *are* re-proposing these after a snapshot because of the expectation that any commands proposed before the snapshot are likely to have failed because of their `MaxLeaseIndex` being too low.

**Comment by tamird** [comment]
Hm, perhaps not. The reason for re-proposing after a snapshot is ostensibly missed leadership changes. However it still seems dubious that the application of the snapshot containing the pre-snapshot lease request doesn't result in the client learning of this success.

**Comment by andreimatei** [comment]
FWIW, here's some explanation about why the test is flaky and not consistently fail/success:
the test restarts a node, and then send an `increment` request through that node. Before the `increment` is sent, there’s another transaction started in the background - a `CPut` on the liveness record. In the vast majority of cases, that transaction causes an attempt at lease acquisition. The `RequestLease` command succeeds, and then is reproposed (as Pete's saying). The second attempt fails because of lack of idempotence, which also causes the `CPut` to fail. But nobody cares.
Then the `increment` is sent, the lease is already in place, everybody’s happy.
Now, every now and then, for reasons not entirely clear, the `LeaseRequest` triggered by the `CPut`  is not settled by the time `increment` is sent, and so the `increment` gets infected by the lease error.

I'm working on a fix for making `LeaseRequest` idempotent - or, rather, for having the sender be able to deal with this reproposal problem, but it's still work in progress.

**Comment by bdarnell** [comment]
> The second execution of the RequestLease command fails the verifyLease check because the lease that was present at the time the command was generated has changed.
Is there someway to make the RequestLease command idempotent by looking at the roachpb.Lease?

Yeah, I think we could return nil here if the proposed lease matches the current lease (in the `Lease.Equivalent` sense)

We might also want to just get rid of reproposals for lease commands - their relevance is time-limited and they're not protected by MaxLeaseIndex so reproposing them makes less sense than other commands. We could just cancel pending leases and let the normal lease request machinery generate new ones when required.

**Comment by bdarnell** [comment]
> Yeah, I think we could return nil here if the proposed lease matches the current lease (in the Lease.Equivalent sense)

I just read @andreimatei's comment in #12448 (https://github.com/cockroachdb/cockroach/pull/12448#discussion_r92868592) and agree that it's probably better to return LeaseRejectedError instead of NotLeaseHolderError and let the calling code decide whether it's an error or not.

**Comment by bdarnell** [comment]
> Can you remind me why snapshots do this? I would expect that any pending commands covered by incoming snapshots would, upon application, be removed from the pending commands map.

Because this possibility was never really considered. We can't propose any normal commands while being so far behind that we'd need a snapshot. Lease requests are the only scenario where this realistically arises.
