### ISSUE TITLE
opt: v23.1.16: index out of bounds in SHOW RANGES

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#124506]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5386176012/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5386176012/?referrer=webhooks_plugin)

Panic Message:

```
catch.go:29: runtime error: index out of range [4] with length 4
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/util/errorutil.ShouldCatch
  | 	github.com/cockroachdb/cockroach/pkg/util/errorutil/catch.go:29
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).Build.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:217
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | runtime.goPanicIndex
  | 	GOROOT/src/runtime/panic.go:113
  | github.com/cockroachdb/cockroach/pkg/sql.(*optTable).Index
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt_catalog.go:1221
  | github.com/cockroachdb/cockroach/pkg/sql.(*optCatalog).ResolveIndex
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt_catalog.go:318
  | github.com/cockroachdb/cockroach/pkg/sql/opt/cat.ResolveTableIndex
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/cat/utils.go:55
  | github.com/cockroachdb/cockroach/pkg/sql/delegate.(*delegator).delegateShowRanges
  | 	github.com/cockroachdb/cockroach/pkg/sql/delegate/show_ranges.go:95
  | github.com/cockroachdb/cockroach/pkg/sql/delegate.TryDelegate
  | 	github.com/cockroachdb/cockroach/pkg/sql/delegate/delegate.go:114
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:426
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmtAtRoot
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:277
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).Build
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:251
  | github.com/cockroachdb/cockroach/pkg/sql.(*optPlanningCtx).buildExecMemo
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:584
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).makeOptimizerPlan
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:245
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).makeExecPlan
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2060
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1567
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1037
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:142
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:3119
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:141
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2181
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2186
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2103
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:902
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:310
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (3) runtime error: index out of range [4] with length 4
  | -- cause hidden behind barrier
  | runtime error: index out of range [4] with length 4
  | (1) runtime error: index out of range [4] with length 4
  | Error types: (1) runtime.boundsError
Error types: (1) *assert.withAssertionFailure (2) *withstack.withStack (3) *barriers.barrierErr
-- report composition:
*barriers.barrierErr: masked error: runtime error: index out of range [4] with length 4
catch.go:29: *withstack.withStack (top exception)
*assert.withAssertionFailure
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/37f75744ac468fe5a97b343a188ea248bce8fb4a/pkg/sql/pgwire/conn.go#L309-L311](https://github.com/cockroachdb/cockroach/blob/37f75744ac468fe5a97b343a188ea248bce8fb4a/pkg/sql/pgwire/conn.go#L309-L311)
[https://github.com/cockroachdb/cockroach/blob/37f75744ac468fe5a97b343a188ea248bce8fb4a/pkg/sql/conn_executor.go#L901-L903](https://github.com/cockroachdb/cockroach/blob/37f75744ac468fe5a97b343a188ea248bce8fb4a/pkg/sql/conn_executor.go#L901-L903)
[https://github.com/cockroachdb/cockroach/blob/37f75744ac468fe5a97b343a188ea248bce8fb4a/pkg/sql/conn_executor.go#L2102-L2104](https://github.com/cockroachdb/cockroach/blob/37f75744ac468fe5a97b343a188ea248bce8fb4a/pkg/sql/conn_executor.go#L2102-L2104)
[https://github.com/cockroachdb/cockroach/blob/37f75744ac468fe5a97b343a188ea248bce8fb4a/pkg/sql/conn_executor.go#L2185-L2187](https://github.com/cockroachdb/cockroach/blob/37f75744ac468fe5a97b343a188ea248bce8fb4a/pkg/sql/conn_executor.go#L2185-L2187)
[https://github.com/cockroachdb/cockroach/blob/37f75744ac468fe5a97b343a188ea248bce8fb4a/pkg/sql/conn_executor.go#L2180-L2182](https://github.com/cockroachdb/cockroach/blob/37f75744ac468fe5a97b343a188ea248bce8fb4a/pkg/sql/conn_executor.go#L2180-L2182)
[https://github.com/cockroachdb/cockroach/blob/37f75744ac468fe5a97b343a188ea248bce8fb4a/pkg/sql/conn_executor_exec.go#L140-L142](https://github.com/cockroachdb/cockroach/blob/37f75744ac468fe5a97b343a188ea248bce8fb4a/pkg/sql/conn_executor_exec.go#L140-L142)
[https://github.com/cockroachdb/cockroach/blob/37f75744ac468fe5a97b343a188ea248bce8fb4a/pkg/sql/conn_executor_exec.go#L3118-L3120](https://github.com/cockroachdb/cockroach/blob/37f75744ac468fe5a97b343a188ea248bce8fb4a/pkg/sql/conn_executor_exec.go#L3118-L3120)
[https://github.com/cockroachdb/cockroach/blob/37f75744ac468fe5a97b343a188ea248bce8fb4a/pkg/sql/conn_executor_exec.go#L141-L143](https://github.com/cockroachdb/cockroach/blob/37f75744ac468fe5a97b343a188ea248bce8fb4a/pkg/sql/conn_executor_exec.go#L141-L143)
[https://github.com/cockroachdb/cockroach/blob/37f75744ac468fe5a97b343a188ea248bce8fb4a/pkg/sql/conn_executor_exec.go#L1036-L1038](https://github.com/cockroachdb/cockroach/blob/37f75744ac468fe5a97b343a188ea248bce8fb4a/pkg/sql/conn_executor_exec.go#L1036-L1038)
[https://github.com/cockroachdb/cockroach/blob/37f75744ac468fe5a97b343a188ea248bce8fb4a/pkg/sql/conn_executor_exec.go#L1566-L1568](https://github.com/cockroachdb/cockroach/blob/37f75744ac468fe5a97b343a188ea248bce8fb4a/pkg/sql/conn_executor_exec.go#L1566-L1568)
[https://github.com/cockroachdb/cockroach/blob/37f75744ac468fe5a97b343a188ea248bce8fb4a/pkg/sql/conn_executor_exec.go#L2059-L2061](https://github.com/cockroachdb/cockroach/blob/37f75744ac468fe5a97b343a188ea248bce8fb4a/pkg/sql/conn_executor_exec.go#L2059-L2061)
[https://github.com/cockroachdb/cockroach/blob/37f75744ac468fe5a97b343a188ea248bce8fb4a/pkg/sql/plan_opt.go#L244-L246](https://github.com/cockroachdb/cockroach/blob/37f75744ac468fe5a97b343a188ea248bce8fb4a/pkg/sql/plan_opt.go#L244-L246)
[https://github.com/cockroachdb/cockroach/blob/37f75744ac468fe5a97b343a188ea248bce8fb4a/pkg/sql/plan_opt.go#L583-L585](https://github.com/cockroachdb/cockroach/blob/37f75744ac468fe5a97b343a188ea248bce8fb4a/pkg/sql/plan_opt.go#L583-L585)
[https://github.com/cockroachdb/cockroach/blob/37f75744ac468fe5a97b343a188ea248bce8fb4a/pkg/sql/opt/optbuilder/builder.go#L250-L252](https://github.com/cockroachdb/cockroach/blob/37f75744ac468fe5a97b343a188ea248bce8fb4a/pkg/sql/opt/optbuilder/builder.go#L250-L252)
[https://github.com/cockroachdb/cockroach/blob/37f75744ac468fe5a97b343a188ea248bce8fb4a/pkg/sql/opt/optbuilder/builder.go#L276-L278](https://github.com/cockroachdb/cockroach/blob/37f75744ac468fe5a97b343a188ea248bce8fb4a/pkg/sql/opt/optbuilder/builder.go#L276-L278)
[https://github.com/cockroachdb/cockroach/blob/37f75744ac468fe5a97b343a188ea248bce8fb4a/pkg/sql/opt/optbuilder/builder.go#L425-L427](https://github.com/cockroachdb/cockroach/blob/37f75744ac468fe5a97b343a188ea248bce8fb4a/pkg/sql/opt/optbuilder/builder.go#L425-L427)
[https://github.com/cockroachdb/cockroach/blob/37f75744ac468fe5a97b343a188ea248bce8fb4a/pkg/sql/delegate/delegate.go#L113-L115](https://github.com/cockroachdb/cockroach/blob/37f75744ac468fe5a97b343a188ea248bce8fb4a/pkg/sql/delegate/delegate.go#L113-L115)
[https://github.com/cockroachdb/cockroach/blob/37f75744ac468fe5a97b343a188ea248bce8fb4a/pkg/sql/delegate/show_ranges.go#L94-L96](https://github.com/cockroachdb/cockroach/blob/37f75744ac468fe5a97b343a188ea248bce8fb4a/pkg/sql/delegate/show_ranges.go#L94-L96)
[https://github.com/cockroachdb/cockroach/blob/37f75744ac468fe5a97b343a188ea248bce8fb4a/pkg/sql/opt/cat/utils.go#L54-L56](https://github.com/cockroachdb/cockroach/blob/37f75744ac468fe5a97b343a188ea248bce8fb4a/pkg/sql/opt/cat/utils.go#L54-L56)
[https://github.com/cockroachdb/cockroach/blob/37f75744ac468fe5a97b343a188ea248bce8fb4a/pkg/sql/opt_catalog.go#L317-L319](https://github.com/cockroachdb/cockroach/blob/37f75744ac468fe5a97b343a188ea248bce8fb4a/pkg/sql/opt_catalog.go#L317-L319)
[https://github.com/cockroachdb/cockroach/blob/37f75744ac468fe5a97b343a188ea248bce8fb4a/pkg/sql/opt_catalog.go#L1220-L1222](https://github.com/cockroachdb/cockroach/blob/37f75744ac468fe5a97b343a188ea248bce8fb4a/pkg/sql/opt_catalog.go#L1220-L1222)
[GOROOT/src/runtime/panic.go#L112-L114](GOROOT/src/runtime/panic.go#L112-L114)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
[https://github.com/cockroachdb/cockroach/blob/37f75744ac468fe5a97b343a188ea248bce8fb4a/pkg/sql/opt/optbuilder/builder.go#L216-L218](https://github.com/cockroachdb/cockroach/blob/37f75744ac468fe5a97b343a188ea248bce8fb4a/pkg/sql/opt/optbuilder/builder.go#L216-L218)
[https://github.com/cockroachdb/cockroach/blob/37f75744ac468fe5a97b343a188ea248bce8fb4a/pkg/util/errorutil/catch.go#L28-L30](https://github.com/cockroachdb/cockroach/blob/37f75744ac468fe5a97b343a188ea248bce8fb4a/pkg/util/errorutil/catch.go#L28-L30)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommandsAsync.func1 at line 310
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 902
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 2103
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 2186
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd.func1 at line 2181
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 141
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithProfiling at line 3119
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt.func1 at line 142
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 1037
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchToExecutionEngine at line 1567
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).makeExecPlan at line 2060
pkg/sql/plan_opt.go in pkg/sql.(*planner).makeOptimizerPlan at line 245
pkg/sql/plan_opt.go in pkg/sql.(*optPlanningCtx).buildExecMemo at line 584
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).Build at line 251
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).buildStmtAtRoot at line 277
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).buildStmt at line 426
pkg/sql/delegate/delegate.go in pkg/sql/delegate.TryDelegate at line 114
pkg/sql/delegate/show_ranges.go in pkg/sql/delegate.(*delegator).delegateShowRanges at line 95
pkg/sql/opt/cat/utils.go in pkg/sql/opt/cat.ResolveTableIndex at line 55
pkg/sql/opt_catalog.go in pkg/sql.(*optCatalog).ResolveIndex at line 318
pkg/sql/opt_catalog.go in pkg/sql.(*optTable).Index at line 1221
GOROOT/src/runtime/panic.go in runtime.goPanicIndex at line 113
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).Build.func1 at line 217
pkg/util/errorutil/catch.go in pkg/util/errorutil.ShouldCatch at line 29
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v23.1.16 |
| Go Version | go1.19.13 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.16 |
| Cockroach SHA | 37f75744ac468fe5a97b343a188ea248bce8fb4a |
| # of CPUs | 64 |
| # of Goroutines | 6050 |

Jira issue: CRDB-38933

**Comment by yuzefovich** [comment]
Hm, I tried a few things but couldn't reproduce this (like indexes on virtual columns and indexes being backfilled while SHOW RANGES is executed). My guess is that the problem is very rare and is due to a mismatch between `optTable.indexes` and `tabledesc.ordinal`, perhaps with a concurrent schema change involved.
