### ISSUE TITLE
PCR: stream from non virtual cluster to virtual cluster 

### ISSUE THREAD

**Issue by alicia-l2** [cockroachdb/cockroach#124764]
Physical Cluster Replication is built on top of the cluster virtualization based architecture. This means most of our current customers cannot take advantage of PCR without an onerous migration process onto a new cluster. 

This work will expand PCR support so that we can stream from a single tenant to a multi tenant cluster. This will allow current customers to take advantage of PCR without needing to migrate to a new cluster. 

Jira issue: CRDB-39066

**Comment by dt** [comment]
Implemented in https://github.com/cockroachdb/cockroach/pull/122001 and backported to 24.1 in https://github.com/cockroachdb/cockroach/pull/122295
