### ISSUE TITLE
Cluster of 3 nodes crushes

### ISSUE THREAD

**Issue by byteg** [cockroachdb/cockroach#124731]
**Describe the problem**

Cluster periodically(1-2 times a day) crushes.

**To Reproduce**

1. Set up CockroachDB cluster of 3 nodes
2. Wait
3. All nodes crush

**Expected behavior**
No nodes crush.

**Additional data / screenshots**

> ling: dial tcp 78.24.221.250:26257: connect: connection refused"› [code 2/Unknown]
> I240526 19:54:57.876638 393548 1@storage/pebble.go:1525 ⋮ [n2,s2,pebble] 884  the server is terminating due to a fatal error (see the DEV channel for details)
> F240526 19:54:57.876735 393548 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 885  file write stall detected: disk slowness detected: syncdata on file 029902.log has been ongoing for 21.4s
> F240526 19:54:57.876735 393548 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 885 !goroutine 393548 [running]:
> F240526 19:54:57.876735 393548 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 885 !runtime/debug.Stack()
> F240526 19:54:57.876735 393548 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 885 !    GOROOT/src/runtime/debug/stack.go:24 +0x5e
> F240526 19:54:57.876735 393548 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 885 !github.com/cockroachdb/cockroach/pkg/util/log.(*loggerT).outputLogEntry(_, {{{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}}, ...})
> F240526 19:54:57.876735 393548 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 885 !    github.com/cockroachdb/cockroach/pkg/util/log/clog.go:280 +0xe7
> F240526 19:54:57.876735 393548 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 885 !github.com/cockroachdb/cockroach/pkg/util/log.logfDepthInternal({0x77b14f8, 0xc001644fc0}, 0x2, 0x4, 0x0, 0x0?, {0x61681ed, 0x1d}, {0xc001fe5df0, 0x1, ...})
> F240526 19:54:57.876735 393548 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 885 !    github.com/cockroachdb/cockroach/pkg/util/log/channels.go:109 +0x585
> F240526 19:54:57.876735 393548 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 885 !github.com/cockroachdb/cockroach/pkg/util/log.logfDepth(...)
> F240526 19:54:57.876735 393548 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 885 !    github.com/cockroachdb/cockroach/pkg/util/log/channels.go:39
> F240526 19:54:57.876735 393548 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 885 !github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(...)
> F240526 19:54:57.876735 393548 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 885 !    github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/util/log/log_channels_generated.go:848
> F240526 19:54:57.876735 393548 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 885 !github.com/cockroachdb/cockroach/pkg/storage.(*Pebble).makeMetricEtcEventListener.func4({{0xc00c152a60, 0x1f}, 0x3, 0x0, 0x4fb8d561e})
> F240526 19:54:57.876735 393548 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 885 !    github.com/cockroachdb/cockroach/pkg/storage/pebble.go:1525 +0x1cd
> F240526 19:54:57.876735 393548 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 885 !github.com/cockroachdb/pebble.TeeEventListener.func4({{0xc00c152a60, 0x1f}, 0x3, 0x0, 0x4fb8d561e})
> F240526 19:54:57.876735 393548 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 885 !    github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/event.go:706 +0x4a
> F240526 19:54:57.876735 393548 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 885 !github.com/cockroachdb/cockroach/pkg/storage.wrapFilesystemMiddleware.func1({{0xc00c152a60, 0x1f}, 0x3, 0x0, 0x4fb8d561e})
> F240526 19:54:57.876735 393548 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 885 !    github.com/cockroachdb/cockroach/pkg/storage/pebble.go:790 +0x91
> F240526 19:54:57.876735 393548 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 885 !github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFS).ReuseForWrite.func2(0x9d?, 0xbc4408c3c67?, 0xbf5d8a0?)
> F240526 19:54:57.876735 393548 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 885 !    github.com/cockroachdb/pebble/vfs/external/com_github_cockroachdb_pebble/vfs/disk_health.go:772 +0x65
> F240526 19:54:57.876735 393548 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 885 !github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker.func1()
> F240526 19:54:57.876735 393548 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 885 !    github.com/cockroachdb/pebble/vfs/external/com_github_cockroachdb_pebble/vfs/disk_health.go:186 +0x1c4
> F240526 19:54:57.876735 393548 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 885 !created by github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker in goroutine 244
> F240526 19:54:57.876735 393548 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 885 !    github.com/cockroachdb/pebble/vfs/external/com_github_cockroachdb_pebble/vfs/disk_health.go:166 +0x58
> F240526 19:54:57.876735 393548 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 885 !
> F240526 19:54:57.876735 393548 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 885 !For more context, check log files in: /root/cockroach-data/logs
> F240526 19:54:57.876735 393548 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 885 !
> F240526 19:54:57.876735 393548 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 885 !
> F240526 19:54:57.876735 393548 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 885 !****************************************************************************
> F240526 19:54:57.876735 393548 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 885 !
> F240526 19:54:57.876735 393548 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 885 !This node experienced a fatal error (printed above), and as a result the
> F240526 19:54:57.876735 393548 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 885 !process is terminating.
> F240526 19:54:57.876735 393548 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 885 !
> F240526 19:54:57.876735 393548 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 885 !Fatal errors can occur due to faulty hardware (disks, memory, clocks) or a
> F240526 19:54:57.876735 393548 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 885 !problem in CockroachDB. With your help, the support team at Cockroach Labs
> F240526 19:54:57.876735 393548 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 885 !will try to determine the root cause, recommend next steps, and we can
> F240526 19:54:57.876735 393548 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 885 !improve CockroachDB based on your report.
> F240526 19:54:57.876735 393548 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 885 !
> F240526 19:54:57.876735 393548 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 885 !Please submit a crash report by following the instructions here:
> F240526 19:54:57.876735 393548 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 885 !
> F240526 19:54:57.876735 393548 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 885 !    https://github.com/cockroachdb/cockroach/issues/new/choose
> F240526 19:54:57.876735 393548 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 885 !
> F240526 19:54:57.876735 393548 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 885 !If you would rather not post publicly, please contact us directly at:
> F240526 19:54:57.876735 393548 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 885 !
> F240526 19:54:57.876735 393548 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 885 !    support@cockroachlabs.com
> F240526 19:54:57.876735 393548 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 885 !
> F240526 19:54:57.876735 393548 storage/pebble.go:1525 ⋮ [n2,s2,pebble] 885 !The Cockroach Labs team appreciates your feedback.
> 

**Environment:**
 - CockroachDB version 23.2.4
 - Server OS: Ubuntu

Jira issue: CRDB-39044

**Comment by RaduBerinde** [comment]
Hi,

The message says it all: "disk slowness detected: syncdata on file 029902.log has been ongoing for 21.4s". The disk is very slow or not able to keep up with the workload. We tried to write to the write-ahead-log and it took over 20 seconds. Our system is designed to crash on purpose in this case because it can't be expected to function reasonably.

To further debug this, we'd need more details on the hardware and the workload that is running on Cockroach (and if there is anything else running on the machines).

**Comment by byteg** [comment]
Hi!
Thanks for fast reply. I'm running the cluster on VDS-KVM-NVMe, so in theory the disk should be quite fast.
The cluster is not loaded at all, it is not handling any requests currently.

**Comment by RaduBerinde** [comment]
Can you post screenshots of the metrics in the Storage dashboard (form the web UI)?

**Comment by byteg** [comment]
![screencapture-78-24-222-34-8080-2024-05-28-19_35_03](https://github.com/cockroachdb/cockroach/assets/2619643/073e015e-8a2b-43a0-aa34-6f572acbd6f7)

**Comment by RaduBerinde** [comment]
Thanks. Looks like very little activity, as expected. I would reach out to whoever hosts the machines to investigate why some IOs take 20+ seconds.

**Comment by RaduBerinde** [comment]
Closing as this is an infrastructure issue and not something that CRDB is doing wrong.
