### ISSUE TITLE
delta: zero QPS, non-zero exec latencies

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#12473]
We've been seeing zero QPS on delta for yet-unknown reasons. However, the exec latencies during this period are surprisingly non-zero.

https://monitoring.gce.cockroachdb.com/dashboard/db/cockroach-sql?from=1482155714898&to=1482159874626&var-cluster=delta&var-node=All&var-rate_interval=1m

![](https://www.evernote.com/shard/s86/sh/5e6f1934-6c72-4e52-aee0-503164ce778b/20430e377db14ad8/res/712f30ff-0601-48fe-9fd9-ee394ea71d0a/skitch.png)

**Comment by mberhault** [comment]
yeah, the prometheus-computed latencies have a few issues. I'm still digging through them.

**Comment by mberhault** [comment]
I don't think we've seen this since switching to the proper metrics (we were showing node.exec instead of sql.exec)
