### ISSUE TITLE
changefeedccl: setting `execution_locality` to a secondary region could create unbalanced plans

### ISSUE THREAD

**Issue by andyyang890** [cockroachdb/cockroach#124822]
**Edit (on Jul 29, 2024): Since this issue was filed, we've backported the bulk oracle to 23.1 in https://github.com/cockroachdb/cockroach/pull/124930 and 23.2 in https://github.com/cockroachdb/cockroach/pull/124925 so there is a mitigation available (off by default) in v23.1.23+ and v23.2.7+.**

---

Changefeeds on v23.1 that have `execution_locality` set to a watched table's secondary region (a region with lower priority in a zone config's `lease_preferences`) could make plans that assign the majority of the watched ranges to a change aggregator on the coordinator node.

This is because of https://github.com/cockroachdb/cockroach/issues/114079, which causes reassignment of ranges that don't match the locality of a replica returned by the DistSQL oracle to be reassigned to the gateway node (coordinator node), and https://github.com/cockroachdb/cockroach/issues/114528, which prevented the follower-reads oracle from being used for changefeeds.

In a nutshell, the issue is that the bin-packing oracle used by changefeeds will always pick the leaseholder if it's known and if not, it will pick the local node (coordinator node) if that's available before considering other replicas. However, since the leaseholder is most likely to be from the primary region, it won't match the execution_locality and so the DistSQL instance resolver will end up assigning those spans to the gateway node (coordinator node) too:
https://github.com/cockroachdb/cockroach/blob/1f6100098bb3f165cc291a421b387d02daaa34eb/pkg/sql/distsql_physical_planner.go#L1622-L1631

The end result is that the coordinator node ends up running a change aggregator watching a disproportionate portion (potentially even all) of the ranges.

This issue is partially mitigated on 23.2 by https://github.com/cockroachdb/cockroach/commit/5d7714a03a891c9fd5746fb876c39dced4f47205 and fully mitigated on 24.1 by https://github.com/cockroachdb/cockroach/commit/84e0e51d25afaa303ed8b977e38e13ab68271c80.

Jira issue: CRDB-39086

**Comment by rharding6373** [comment]
Closing since this is mitigated by the bulk oracle.
