### ISSUE TITLE
stability: leases don't finish rebalancing after 5 new nodes are added at once

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#12489]
This seems to happen with both the original allocator and the updated rule solver based one but it seems to be exacerbated by the new one.  Something seems to be stuck in the replicate queue, but I'm not sure what that is yet.  I'm investigating more.

If the cluster is perturbed by removing a node, after the cluster recovers, the leases rebalance correctly.  In the case of the example below the lease rebalancing seems to have spontaneously recovered.  All other metrics seem to be completely normal.

I've tried to repeat this with allocsim, and while I can see a slight stall it recovers quickly.

Since it takes a long time to repeat, I've only observed this three times, each time I've run this scenario.  Two times with the rule solver enabled, and once without.

<img width="935" alt="screen shot 2016-12-19 at 23 03 03" src="https://cloud.githubusercontent.com/assets/1614265/21337908/7a79e9fc-c63f-11e6-8a3e-90435d62ab66.png">
<img width="943" alt="screen shot 2016-12-19 at 23 21 52" src="https://cloud.githubusercontent.com/assets/1614265/21338203/0515eadc-c642-11e6-93e7-95fe01b381c5.png">
There charts were generated on gamma using the following

```
from=1482167996926&to=1482198746051&var-cluster=gamma&var-node=All&var-rate_interval=1m
```

Clearly, some function is being attempted multiple time in the queue and not proceeding, but going through the logs, I was unable to determine what that was.  I'm restarting the scenario again with more verbose logging to see if I can determine the root cause.

Steps to repeat:
1) Start up a cluster of 5 nodes, each with the block writer and with `COCKROACH_ENABLE_RULE_SOLVER=true`.  
2) Wait until there are around 500 ranges. This will take a long time.
3) Start up 5 new nodes, also with block writers.
4) After the replicas are rebalanced, lease rebalancing seems to get stuck.

This reproduced on two different shas
956e61fab45ee1bbfa266a63cc4f42891abac4ef 
6e5065e92500bf58753290cf143aebb91615c754

**Comment by a-robinson** [comment]
Likely has the same root cause as #12322. I believe @petermattis was pre-splitting the ranges when he ran into that, which would remove the waiting involved in your step 2 if you want to try reproducing this faster.

**Comment by BramGruneir** [comment]
Interesting.  I'll give that a try tomorrow locally.

**Comment by bdarnell** [comment]
The "pending" graph on the queues page was messed up (it was trying to compute the rate of a gauge). The number of pending replicas is flat during this time. (I also added a graph for purgatory, which is always zero unless I messed up the graph)

![image](https://cloud.githubusercontent.com/assets/160562/21342219/cd5ca5b0-c6cb-11e6-9553-661a57034f45.png)

The pending replicas are concentrated on two nodes, which *are* able to process other replicas.

![image](https://cloud.githubusercontent.com/assets/160562/21342251/fcb02382-c6cb-11e6-9f7c-911e2e220b3d.png)

Something must be getting requeued over and over and starving out the remaining lease rebalancing work. Lease rebalances always happen at priority zero and so anything with a non-zero priority could push them off indefinitely (but whatever's happening is getting recorded as a "success")

**Comment by BramGruneir** [comment]
Backup of a 5 node cluster with 500 ranges is now available here `gs://cockroach-backup/gamma.12489`

**Comment by BramGruneir** [comment]
So I've finally been able to reproduce the issue easily and inspect the logs.  Looks like there's a node-liveliness issue.

I see a ton of these:
```
I161221 04:50:44.766425 118 storage/replicate_queue.go:162  [n2,replicate,s2,r290/2:/Table/51/1/{191511…-209737…},@c420ad1200] [n2,s2,r290/2:/Table/51/1/{191511…-209737…}] repair needed (remove dead), enqueuing
I161221 04:50:44.967035 118 storage/replicate_queue.go:162  [n2,replicate,s2,r233/3:/Table/51/1/70{28899…-46725…},@c420c5e900] [n2,s2,r233/3:/Table/51/1/70{28899…-46725…}] repair needed (remove dead), enqueuing
I161221 04:50:45.167824 118 storage/replicate_queue.go:162  [n2,replicate,s2,r284/3:/Table/51/1/37{14956…-33281…},@c420d07b00] [n2,s2,r284/3:/Table/51/1/37{14956…-33281…}] repair needed (remove dead), enqueuing
I161221 04:50:45.368639 118 storage/replicate_queue.go:162  [n2,replicate,s2,r289/2:/Table/51/1/2{279538…-461590…},@c420a9e480] [n2,s2,r289/2:/Table/51/1/2{279538…-461590…}] repair needed (remove dead), enqueuing
```

But I don't see any actual removals. And many of these messages are repeated multiple times for a single replica.

**Comment by petermattis** [comment]
Can you output `StorePool.String()` in these messages? That would show what stores the `StorePool` thinks are dead.

**Comment by BramGruneir** [comment]
I've tried to re-create this a good number times over the holiday break and in the last week with newer builds and I can't reproduce the problem anymore.  
Here's an example from my latest run from the last few hours:
![screen shot 2017-01-09 at 13 34 17](https://cloud.githubusercontent.com/assets/1614265/21778187/644c8d60-d670-11e6-8562-e989ddea509d.png)
![screen shot 2017-01-09 at 13 36 27](https://cloud.githubusercontent.com/assets/1614265/21778246/a6f7c6b6-d670-11e6-90b1-daf77b84ab27.png)

I'm going to close this unless there are any objections.
