### ISSUE TITLE
*: switch from golang.org/x/net/context to stdlib

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#12498]
We currently use the `context` package from `golang.org/x/net/context`, instead of the version added to the standard library in Go 1.7. The two are equivalent (the `x/net` version is just a wrapper around the standard library version when built with Go 1.7), so now that we require Go 1.7 it should be simple to change all imports to the package's new home (unless I'm missing some compatibility issue). 

One concrete benefit of making this change is that it works better with `goimports`. The `.goimportsignore` file can be used to ignore certain packages (and this is useful to avoid other `log` packages that may be on the `GOPATH`), but packages from the standard library are hard-coded and cannot be ignored with this mechanism. If we switched from `x/net` to the standard library, then we could blacklist the `x/net` version in `.goimportsignore`.

**Comment by a-robinson** [comment]
I looked into this a couple weeks ago because it was bothering me too, but the two aren't usable at the same time, so we can't easily change until grpc does (https://github.com/grpc/grpc-go/issues/711). They won't be changing for a while in order to stay compatible with users of earlier go versions.

**Comment by bdarnell** [comment]
Thanks, I figured there was some reason to stick with the external package I wasn't seeing.

**Comment by dianasaur323** [comment]
@bdarnell @a-robinson haven't we moved beyond Go 1.7 at this point? I'm going to close out, but feel free to re-open if you disagree.

**Comment by a-robinson** [comment]
This is something that we still haven't done and can't do until https://github.com/grpc/grpc-go/issues/711 is resolved. I think leaving the issue open under the later milestone is appropriate.

**Comment by andreimatei** [comment]
go 1.9 is supposed to have a new type alias feature that will make this
kind of type move between packages work

**Comment by dt** [comment]
well 1.8 was supposed to have aliases too until it didn't, so a grain of salt and all about betting on something that hasn't shipped yet.
