### ISSUE TITLE
sql: interval input format differs from Postgres

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#12503]
We currently expect intervals in the SQL standard input format to be of the form `Y-M-D HH:MM:SS` when parsing them. There seems to be some disagreement about what the SQL standard says about this - Postgres doesn't parse intervals of this form, instead expecting `Y-M D HH:MM:SS` - note the missing dash between the `M` and the `D`.

The documentation here http://www.ibm.com/support/knowledgecenter/SSGU8G_12.1.0/com.ibm.esqlc.doc/ids_esqlc_0190.htm is also kind of confusing - both syntaxes are listed.  You can see why Postgres would expect no dash, because there are almost two separate input formats - `Y-M` and `D HH:MM:SS`.

I think we should accept both formats at minimum since we're aiming for Postgres compatibility. I would also be ok with not allowing `Y-M-D` format since Postgres doesn't.

**Comment by hainesc** [comment]
Sorry for misunderstanding the [documentation](https://www.postgresql.org/docs/current/static/datatype-datetime.html#DATATYPE-INTERVAL-INPUT-EXAMPLES) and this bug, I will try to fix it.

**Comment by jordanlewis** [comment]
@hainesc it's not at a problem - as I mention, it's very unclear to me even what the correct behavior is! Thanks for taking a look.

**Comment by hainesc** [comment]
I will try my best for postgres compatibility.

**Comment by hainesc** [comment]
I think we should have a discussion whether we should keep 100% compatible with postgres in interval parsing when there are floats. See https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/parser/datum.go#L1236-L1245

In postgres we have
```sql
> select '1:1.2'::interval;
  interval  
------------
 00:01:01.2
(1 row)
```
While in cockroach we have
```sql
> select '1:1.2'::interval;
INTERVAL '1h1m12s'
```

**Comment by hainesc** [comment]
Also, it is weird that in postgres
```sql
> select ':2:1'::interval;
 interval 
----------
 02:01:00
```

I am not sure whether it is a bug or intends to do so.
