### ISSUE TITLE
ldap: metrics for measuring LDAP connection latency

### ISSUE THREAD

**Issue by dikshant** [cockroachdb/cockroach#125097]
We need at least two metrics to distinguish LDAP/AD authentication time which includes the total time and the RTT (round trip time) latency to the LDAP/AD server. 

Jira issue: CRDB-39233

Epic CRDB-33829

**Comment by sanchit-CRL** [comment]
@dikshant regarding the visibility of the metric, is this a customer facing metric or internal ?
Also do you have any example of a similar metric that currently exists ?
