### ISSUE TITLE
ldap: telemetry to measure LDAP usage

### ISSUE THREAD

**Issue by dikshant** [cockroachdb/cockroach#125098]
We need telemetry via feature counters to measure which clusters are using LDAP for authentication/authorization

Jira issue: CRDB-39234

Epic CRDB-33829

**Comment by souravcrl** [comment]
I have verified diagnostics metrics for ldap authN locally
```
  "featureUsage": {
    "auth.ldap.begin_auth": 2,
    "auth.ldap.login_success": 1,
    "errorcodes.28000": 1,
```
https://localhost:8080/_status/diagnostics/local

authZ feature usage metrics are in progress https://github.com/cockroachdb/cockroach/pull/128498

**Comment by souravcrl** [comment]
verified for both authN and authZ on local for PR https://github.com/cockroachdb/cockroach/pull/129845

<img width="773" alt="Screenshot 2024-08-30 at 1 21 10 PM" src="https://github.com/user-attachments/assets/36da7085-ca97-46c2-a2d3-c471acd1e3b6">
