### ISSUE TITLE
build cockroach from source failed

### ISSUE THREAD

**Issue by ysbarney** [cockroachdb/cockroach#125171]
Starting local Bazel server and connecting to it...
WARNING: --enable_bzlmod is set, but no MODULE.bazel file was found at the workspace root. Bazel will create an empty MODULE.bazel file. Please consider migrating your external dependencies from WORKSPACE to MODULE.bazel. For more details, please refer to https://github.com/bazelbuild/bazel/issues/18958.
INFO: Analyzed target //pkg/cmd/dev:dev (123 packages loaded, 12238 targets configured).
INFO: Found 1 target...
Target //pkg/cmd/dev:dev up-to-date:
  _bazel/bin/pkg/cmd/dev/dev_/dev
INFO: Elapsed time: 188.787s, Critical Path: 87.01s
INFO: 22 processes: 6 internal, 16 processwrapper-sandbox.
INFO: Build completed successfully, 22 total actions
which: no md5 in (/home/kunlun/.cargo/bin:/opt/rh/devtoolset-10/root/usr/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/kunlun/.local/bin:/home/kunlun/bin:/home/kunlun/Downloads/bin)
=============================
=== RUNNING DOCTOR CHECKS ===
=============================
DOCTOR >> I can configure your .bazelrc.user to build either in the `dev` configuration or the `crosslinux` configuration.
DOCTOR >> The former uses your host toolchain, while the latter downloads and uses our production cross-toolchains.  
DOCTOR >> Which config you want to use (dev,crosslinux)? [dev] > crosslinux
WARNING: Build options --//build/toolchains:cross_flag, --//build/toolchains:nogo_disable_flag, --platforms, and 1 more have changed, discarding analysis cache (this can be expensive, see https://bazel.build/advanced/performance/iteration-speed).
ERROR: /home/test/Downloads/cockroach/build/bazelutil/BUILD.bazel:6:14: configurable attribute "targets" in //build/bazelutil:test_nogo_configured doesn't match this configuration: must use exactly one of `--config lintonbuild` or `--config nolintonbuild` explicitly

This instance of //build/bazelutil:test_nogo_configured has configuration identifier 13782d8. To inspect its configuration, run: bazel config 13782d8.

For more help, see https://bazel.build/docs/configurable-attributes#faq-select-choose-condition.

ERROR: Analysis of target '//build/bazelutil:test_nogo_configured' failed; build aborted
INFO: Elapsed time: 2.062s, Critical Path: 0.33s
INFO: 1 process: 1 internal.                                                                                         
ERROR: Build did NOT complete successfully

how to fix this error??

Jira issue: CRDB-39285

**Comment by ysbarney** [comment]
use master branch

**Comment by yuzefovich** [comment]
It sounds like you have both `--config lintonbuild` and `--config nolintonbuild` in `.bazelrc.user` file - you should remove one of them. Perhaps just remove that file altogether and run `./dev doctor` again.
