### ISSUE TITLE
sql: rework the pre and post renderings for groupNode, remove identAggregator

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#12525]
```sql
CREATE DATABASE t;
CREATE TABLE t.t(x INT);
INSERT INTO t.t(x) VALUES (42);
SELECT 1 + count(*) FROM t.t; -- this works
TRUNCATE t.t;
SELECT 1 + count(*) FROM t.t; -- this panics!
```

```
panic: interface conversion: parser.Datum is nil, not *parser.DInt [recovered]
        panic: SELECT 1 + count(*) FROM t.t;: interface conversion: parser.Datum is nil, not *parser.DInt [recovered]
        panic: SELECT 1 + count(*) FROM t.t;: interface conversion: parser.Datum is nil, not *parser.DInt

goroutine 297 [running]:
panic(0x17da0a0, 0xc4203f5090)
        /mnt/kena/go1.7.3/src/runtime/panic.go:500 +0x1a1
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc420499dd0)
        /mnt/kena/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:185 +0x6e
panic(0x17da0a0, 0xc4203f5090)
        /mnt/kena/go1.7.3/src/runtime/panic.go:458 +0x243
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements.func1(0xc420942000, 0x1d)
        /mnt/kena/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:455 +0x149
panic(0x180a580, 0xc420cadac0)
        /mnt/kena/go1.7.3/src/runtime/panic.go:458 +0x243
github.com/cockroachdb/cockroach/pkg/sql/parser.glob..func133(0xc420aee1a8, 0x0, 0x0, 0x255ca20, 0xc4203f5068, 0x0, 0xc420211ec0, 0xc421620ea0, 0x2526cf0)
        /mnt/kena/go/src/github.com/cockroachdb/cockroach/pkg/sql/parser/eval.go:249 +0xdc
github.com/cockroachdb/cockroach/pkg/sql/parser.(*BinaryExpr).Eval(0xc42090fc80, 0xc420aee1a8, 0xc42169bc30, 0xc4203f5040, 0x1, 0x1)
        /mnt/kena/go/src/github.com/cockroachdb/cockroach/pkg/sql/parser/eval.go:1858 +0x1a8
github.com/cockroachdb/cockroach/pkg/sql.(*groupNode).computeAggregates(0xc420a86c60, 0xc42090fc00, 0x0)
        /mnt/kena/go/src/github.com/cockroachdb/cockroach/pkg/sql/group.go:403 +0x287
```

**Comment by knz** [comment]
The proximate cause of the issue is `identAggregate.Result()` returning `nil` when there was no row. I tried to "fix" the issue by having it return NULL in that case, but then the result is incorrect (`1 + COUNT(*)` should be 1, not NULL, when there are no rows). It seems that the use of `identAggregate` in this case is incorrect.

**Comment by knz** [comment]
cc @dt (you've looked at this some time in the past) and @RaduBerinde (perhaps you have an idea)

**Comment by RaduBerinde** [comment]
Where is `identAggregate` used?

**Comment by RaduBerinde** [comment]
Ah, the result of `COUNT(*)` is passed through an `identAggregate`? I wonder if this is a regression from the recent restructuring.

**Comment by RaduBerinde** [comment]
So it looks like we are setting things up so that the select node renders `1, 0` for each node, then we aggregate using `IDENT, COUNT`, and then we render the sum (`@1+@2`). I don't understand why the `1` gets pushed into the pre-render and gets an aggregation function when we should just render `1 + @1` at the end.

**Comment by tamird** [comment]
Per #12706, this affects many (all?) aggregations, not just COUNT.

**Comment by knz** [comment]
Yes, correct

**Comment by RaduBerinde** [comment]
Probably related: `SELECT SUM(1)` returns NULL (it returns `1` in postgres). Similar thing for other functions.

**Comment by nvanbenschoten** [comment]
@RaduBerinde Just to clarify, `SELECT SUM(1)` returns `1` is classic CockroachDB SQL as well. That was the inconsistency I was trying to bring up.

**Comment by RaduBerinde** [comment]
Ah. We got confused. `SELECT SUM(1)` works correctly (in regular sql, and it's not supported at all in distsql right now). The discussion in #14637 was about a testcase in `aggregate` which runs in both regular and distsql, and it is `SELECT SUM(1) FROM kv` where `kv` is empty; in this case the correct result is indeed NULL. https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/testdata/logic_test/aggregate#L13

**Comment by RaduBerinde** [comment]
I am making this issue more broad; we need to fix the way we compute pre- and post-renderings, and we should get rid of the identAggregator (instead, the groupNode can expose all group-by columns by default).

**Comment by knz** [comment]
Moving to 1.1 since this is not causing a panic any more.

**Comment by RaduBerinde** [comment]
Yes, I looked into doing this but it's not an easy task, definitely not something we want to do for 1.0.

**Comment by RaduBerinde** [comment]
In #15686 we are seeing a problem with distql caused by IDENT "aggregation" of constants.

FWIW I believe these issues were introduced by https://github.com/cockroachdb/cockroach/commit/b4edfaeaf484c8824668e40ce7311af85e30c73a

**Comment by RaduBerinde** [comment]
#15688 fixed the incorrect uses of identAggregate.

This issue now tracks getting rid of identAggregate altogether. There is work that's needed on the distsql side too so I'm putting this on my pile.
