### ISSUE TITLE
sql: pg_type only reports basic types

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#12523]
Found in #5582:

```sql
SELECT oid, typname, typsend, typreceive, typoutput, typinput,
       typelem, coalesce(r.rngsubtype, 0), arr
FROM (SELECT t.oid, t.typname, t.typsend, t.typreceive, t.typoutput, t.typinput,
          t.typelem, ARRAY_AGG (a.atttypid) AS arr
      FROM (SELECT oid, typname, typsend, typreceive, typoutput, typinput, typelem, typrelid FROM pg_type) AS t
      JOIN (SELECT atttypid, attrelid FROM pg_attribute WHERE attnum > 0 AND NOT attisdropped ORDER BY attnum) AS a ON a.attrelid = t.typrelid
      GROUP BY t.oid, t.typname, t.typsend, t.typreceive, t.typoutput, t.typinput,  t.typelem) AS t
LEFT JOIN pg_range AS r ON r.rngtypid = t.oid;
```

returns no rows, because the join on `a.attrelid = t.typrelid` fails to find any match.

**Comment by knz** [comment]
After checking it appears that his works as intended (for now) because all our types in pg_types are basic types.

That said, I see that pg also reports tables (pg_databases, etc) in pg_types and reports they have composite types (typtyp = 'c') with the appropriate `typrelid`. Is that something we want to support? 

cc @nvanbenschoten

**Comment by nvanbenschoten** [comment]
I have yet to see any client rely on that behavior, and I don't even know how it would be used. As with a lot of the strange corners in Postgres, I'd err on the side of waiting until compatibility needs arise before putting effort into matching their behavior exactly.

**Comment by jordanlewis** [comment]
I'm going to close this - at this point we're pretty familiar with `pg_type` and how clients use it, and nobody seems to use the fact that tables live in `pg_type` in the wild. We can make a new issue if an actual compatibility issue comes out of this.
