### ISSUE TITLE
tsdump: add flag that lets you specify additional resolutions

### ISSUE THREAD

**Issue by andyyang890** [cockroachdb/cockroach#125256]
See this comment:
https://github.com/cockroachdb/cockroach/blob/3b0392d7888b73f61c65c56917eca00a9db71434/pkg/cli/tsdump.go#L66-L69

The default for `timeseries.storage.resolution_10s.ttl` is only 10 days and sometimes we may want to get tsdump's from further back in the past, which should be possible given the default for `timeseries.storage.resolution_30m.ttl` is 90 days.

Jira issue: CRDB-39348

**Comment by abarganier** [comment]
One thing to keep in mind for this issue is that today, even when `tsdump` is only return 10s resolution data, the size of a tsdump bundle can easily reach the 100s of gigabytes for larger clusters. Including the 30m resolution data should come with limitations, e.g. the presence of a filter, to ensure the output size doesn't get even more out of hand.

**Comment by daniel-crlabs** [comment]
This limitation hinders our ability to troubleshoot issues that are older than 10 days and require this data. This adds complexity to troubleshooting issues that occur in the past as (based on this feature) the only way to obtain this data is to live debug a past problem with the customer via the DBConsole.

The size of the tsdump should not be a concern, as trying to solve a problem should take precedence. In addition, if size was a concern, there are the flags `--from` and `--to` which can be used to limit the scope. If  we were investigating a problem that occurred 20 days in the past and we were only concerned about a 2 day time frame, the size of the tsdump would not be as large. 

I agree the tsdump default settings should be for a short time frame, however, someone should be able to specify for example, something like this:

`--from 2024-01-01` `--to 2024-01-02` and be able to obtain that data. This example is only 1 day worth and I'm very sure it would not be in the 100's of GBs as mentioned.

Please fix this as we always have tickets to investigate issues that occurred in the past (10 + days) and we are unable to obtain the data we need.

**Comment by daniel-crlabs** [comment]
@andyyang890 and @abarganier Are you sure about this? The code you quoted is for the default, which is known and expected. Where is the code that says even if you specify the `--from` and `--to` flags they will be ignored and only data 10 days older is collected? If this is the case this is a bug.

**Comment by andyyang890** [comment]
Alex can correct me if I'm wrong, but from reading the code it seems like we don't set any resolutions on the `tspb.DumpRequest` here:
https://github.com/cockroachdb/cockroach/blob/3b0392d7888b73f61c65c56917eca00a9db71434/pkg/cli/tsdump.go#L155-L159
which means we will only collect metrics with a resolution of 10:
https://github.com/cockroachdb/cockroach/blob/c73d42a4662391b172c6c042de813ba8a1750685/pkg/ts/server.go#L405-L408
which as mentioned above is controlled by `timeseries.storage.resolution_10s.ttl` (default 10 days).

**Comment by daniel-crlabs** [comment]
Resolution is not the time frame, `StartNanos` and `EndNanos` are (these get populated from the `--from` and `--to` arguments).

**Comment by andyyang890** [comment]
It's my understanding that any metrics data with 10s resolution from before `timeseries.storage.resolution_10s.ttl` will no longer exist so there'll be nothing to fetch even if you specify the `StartNanos` (set from the `--from` flag) to a timestamp before then.

**Comment by daniel-crlabs** [comment]
I believe a better alternative here instead of a new flag would be for tsdump to change the resolution for data collected that's older than 10 days to be that of 30s or whatever is available, instead of us having to specify such parameter.

**Comment by arjunmahishi** [comment]
> change the resolution for data collected that's older than 10 days to be that of 30s or whatever is available

This makes sense to me. I've raised a PR that makes this changes.
