### ISSUE TITLE
Makefile:242: .bootstrap: No such file or directory when building from source on OS X

### ISSUE THREAD

**Issue by tlvenn** [cockroachdb/cockroach#12521]
Something I meant to report for sometimes...
When I follow the direction posted on the website to build from source here:
> https://www.cockroachlabs.com/docs/install-cockroachdb.html

Once I issue the `make install` command, the first ouput I got is:
```
> make install
Makefile:242: .bootstrap: No such file or directory
installing githooks/post-checkout
installing githooks/post-merge
installing githooks/post-rewrite
git submodule update --init
```

The error does not halt the build and it seems to work fine but I don't think this is expected and I remember a short conversion with @bdarnell over a build issue I had when he said it was weird because the bootstrap script was supposed to take care of that.

Am i somehow missing something ?

**Comment by bdarnell** [comment]
It's normal and harmless for `Makefile:242: .bootstrap: No such file or directory` to be printed the first time you run `make`. This is because we use `include .bootstrap` in the makefile as a hack to make `.bootstrap` effectively a dependency of every target.

**Comment by tlvenn** [comment]
Hi @bdarnell, thanks for the explanation. What is the proper way to update the code and compile it again.

Would that be enough ?

```
go get -u github.com/cockroachdb/cockroach
cd GOPATH/src/github.com/cockroachdb/cockroach
make install
```

**Comment by bdarnell** [comment]
Yes, that should work. You could also `cd` to the cockroach directory and use `git pull` instead of `go get -u`. Or even better, `git fetch && git checkout beta-20161215` so you can get a version that's had a little more scrutiny than the current `master`.

**Comment by tlvenn** [comment]
Git pull is enough now that you are vendoring the deps correct ?

**Comment by bdarnell** [comment]
It was always enough because `make .bootstrap` would run `glock` and sync your copies of all the other packages we use to the right version. Vendoring just makes sure that we mess with our own private copies of the packages instead of ones that you may have been using for something else.

**Comment by tlvenn** [comment]
ha ok good to know, thanks again for the explanation Ben.

**Comment by tlvenn** [comment]
Closing the issue.
