### ISSUE TITLE
insights: limit usages of cluster-wide requests to ListExecutionInsights due to memory consumption

### ISSUE THREAD

**Issue by xinhaoz** [cockroachdb/cockroach#125340]
This call does not scale well with more nodes in the cluster.
In the short term we should swap to read local node insights where possible instead of cluster-wide insights to avoid causing memory issues.

Currently all cluster-wide requests come from constructing crdb_internal.cluster_execution_insights, which is used in the following places:
- DB Console UI Insights page: we can swap to use `crdb_internal.node_execution_insights`
- debug zip: remove the cluster wide table and include per-node insights via the node table above

Jira issue: CRDB-39396

**Comment by dhartunian** [comment]
From discussion on Sep 19:

Prefer aggregating a topK insights when fanout happens and prefer to hold "most recent unique" insights. Goal is to reduce memory usage during fanout while retaining useful information to surface about the most recent insights.
