### ISSUE TITLE
latency issues for an unknown reason on drt-chaos

### ISSUE THREAD

**Issue by ajstorm** [cockroachdb/cockroach#125305]
On the `drt-chaos` cluster (which is currently running `v24.2.0-alpha.00000000-dev-d0582983521533ffc15a8b8525a188d80da2a0b7`) , we're seeing some latency issues as we're finishing up a schema change.  Here's the log from the operations framework that was running the schema change operation (NOTE: log times are in EST, while the plot is in UTC) :

```
Running operation (add-.*|network-partition|node-kill).* on drt-chaos.

02:43:22 run.go:552: more than one operation found for filter (add-.*|network-partition|node-kill).*, randomly selected add-column to run
02:43:22 main.go:197: operation status: checking if operation add-column dependencies are met
02:43:22 main.go:197: operation status: running operation add-column with run id 112507285975938990
02:43:22 run.go:587: operation status: adding column add_column_op_862707690 to table cct_tpcc.history
03:37:05 run.go:587: operation status: column add_column_op_862707690 created
03:37:05 main.go:197: operation status: operation ran successfully; waiting 5m0s before cleanup
03:42:05 main.go:197: operation status: running cleanup
03:42:05 run.go:613: operation status: dropping column add_column_op_862707690
```

We seem to be finishing a ~45m add column operation when the latency increases dramatically.  Then, it seems to increase again as we perform the drop.

<img width="637" alt="image" src="https://github.com/cockroachdb/cockroach/assets/18447034/a026fb8d-3d15-405d-b42c-f5dfcfb62df0">

Jira issue: CRDB-39376

**Comment by rafiss** [comment]
@ajstorm where can i see these logs? are you sure they are in EST? I am interested in seeing when the DROP operation completed.
```
Running operation (add-.*|network-partition|node-kill).* on drt-chaos.

02:43:22 run.go:552: more than one operation found for filter (add-.*|network-partition|node-kill).*, randomly selected add-column to run
02:43:22 main.go:197: operation status: checking if operation add-column dependencies are met
02:43:22 main.go:197: operation status: running operation add-column with run id 112507285975938990
02:43:22 run.go:587: operation status: adding column add_column_op_862707690 to table cct_tpcc.history
03:37:05 run.go:587: operation status: column add_column_op_862707690 created
03:37:05 main.go:197: operation status: operation ran successfully; waiting 5m0s before cleanup
03:42:05 main.go:197: operation status: running cleanup
03:42:05 run.go:613: operation status: dropping column add_column_op_862707690
```

According to the DB Console Jobs page the `DROP COLUMN` operation started at 3:42 UTC and ended at 4:51 UTC. That 3:42 start time, matches with the log you shared, so that's why I wonder if those logs are also in UTC.

<img width="1549" alt="image" src="https://github.com/cockroachdb/cockroach/assets/1320573/6a62b9f7-e323-49ef-acab-b1f4149e3350">

**Comment by rafiss** [comment]
I have confirmed that the schema change jobs did in fact run at 2:43 UTC and 3:42 UTC, and were not running at 7:30 UTC, which is when these latency issues were observed.

There was a different DROP COLUMN that completed at 7:14 UTC. 
<img width="1497" alt="image" src="https://github.com/cockroachdb/cockroach/assets/1320573/fdc9f21a-f3be-421c-85f1-0307c8f0e194">

However, the latency issues did not start until 7:24 UTC.
<img width="888" alt="image" src="https://github.com/cockroachdb/cockroach/assets/1320573/17eb3048-babd-4930-b90c-353791d48930">


@ajstorm I will unassign my team from this for now. But let me know if I can help track down any other leads.

**Comment by ajstorm** [comment]
Thanks @rafiss, TIL that the operations log is in UTC.  We'll circle back and try to figure out what was running on the cluster at that time.  Sorry for the noise.

**Comment by ajstorm** [comment]
The first blip is due to a node kill, so it somewhat expected:

```
07:29:17 run.go:552: more than one operation found for filter (add-.*|network-partition|node-kill).*, randomly selected node-kill/sigkill/drain=false to run
07:29:17 main.go:197: operation status: checking if operation node-kill/sigkill/drain=false dependencies are met
07:29:17 main.go:197: operation status: running operation node-kill/sigkill/drain=false with run id 17292715695202699537
07:29:17 node_kill.go:51: operation status: killing node 6  with signal 9
07:29:17 cluster.go:2371: running cmd `pkill -9 -f cockroach\ start` on nodes [:6]; details in run_072917.882738275_n6_pkill-9-f-cockroach-.log
run_072917.882738275_n6_pkill-9-f-cockroach-: 07:29:17 cluster.go:2372: > pkill -9 -f cockroach\ start
run_072917.882738275_n6_pkill-9-f-cockroach-: 07:29:18 cluster.go:2390: > result: <ok>
07:29:18 node_kill.go:51: operation status: sent signal 9 to node 6 , waiting for process to exit
07:29:18 cluster.go:2371: running cmd `pgrep -f cockroach\ start` on nodes [:6]; details in run_072918.153694963_n6_pgrep-f-cockroach-st.log
run_072918.153694963_n6_pgrep-f-cockroach-st: 07:29:18 cluster.go:2372: > pgrep -f cockroach\ start
run_072918.153694963_n6_pgrep-f-cockroach-st: 07:29:18 cluster.go:2382: > result: COMMAND_PROBLEM: exit status 1
07:29:18 node_kill.go:51: operation status: killed node 6  with signal 9
07:29:18 main.go:197: operation status: operation ran successfully; waiting 5m0s before cleanup
07:34:18 main.go:197: operation status: running cleanup
07:34:18 cluster.go:2371: running cmd `./cockroach.sh` on nodes [:6]; details in run_073418.497745474_n6_cockroachsh.log
run_073418.497745474_n6_cockroachsh: 07:34:18 cluster.go:2372: > ./cockroach.sh
run_073418.497745474_n6_cockroachsh: 07:34:21 cluster.go:2390: > result: <ok>
07:34:21 run.go:613: operation status: restarted node with error %!s(<nil>)
```

The second one is also a node kill of node 6:

```
07:51:26 run.go:552: more than one operation found for filter (add-.*|network-partition|node-kill).*, randomly selected node-kill/sigkill/drain=false to run
07:51:26 main.go:197: operation status: checking if operation node-kill/sigkill/drain=false dependencies are met
07:51:26 main.go:197: operation status: running operation node-kill/sigkill/drain=false with run id 16709407679889458061
07:51:26 node_kill.go:51: operation status: killing node 6  with signal 9
07:51:26 cluster.go:2371: running cmd `pkill -9 -f cockroach\ start` on nodes [:6]; details in run_075126.570046306_n6_pkill-9-f-cockroach-.log
run_075126.570046306_n6_pkill-9-f-cockroach-: 07:51:26 cluster.go:2372: > pkill -9 -f cockroach\ start
run_075126.570046306_n6_pkill-9-f-cockroach-: 07:51:26 cluster.go:2390: > result: <ok>
07:51:26 node_kill.go:51: operation status: sent signal 9 to node 6 , waiting for process to exit
07:51:26 cluster.go:2371: running cmd `pgrep -f cockroach\ start` on nodes [:6]; details in run_075126.862644642_n6_pgrep-f-cockroach-st.log
run_075126.862644642_n6_pgrep-f-cockroach-st: 07:51:26 cluster.go:2372: > pgrep -f cockroach\ start
run_075126.862644642_n6_pgrep-f-cockroach-st: 07:51:27 cluster.go:2382: > result: COMMAND_PROBLEM: exit status 1
07:51:27 node_kill.go:51: operation status: killed node 6  with signal 9
07:51:27 main.go:197: operation status: operation ran successfully; waiting 5m0s before cleanup
07:56:27 main.go:197: operation status: running cleanup
07:56:27 cluster.go:2371: running cmd `./cockroach.sh` on nodes [:6]; details in run_075627.156800118_n6_cockroachsh.log
run_075627.156800118_n6_cockroachsh: 07:56:27 cluster.go:2372: > ./cockroach.sh
run_075627.156800118_n6_cockroachsh: 07:56:30 cluster.go:2390: > result: <ok>
07:56:30 run.go:613: operation status: restarted node with error %!s(<nil>)
```

There was also _a lot_ of chaos on the cluster at that time, something we probably need to address in the framework.  Closing this issue for now.

**Comment by ajstorm** [comment]
Reopening this one as I _think_ we may be seeing something similar again.  We have the `drt-chaos` logs showing this:

```
2024/06/13 09:57:33 run.go:552: more than one operation found for filter .*, randomly selected add-column to run
2024/06/13 09:57:33 main.go:200: operation status: checking if operation add-column dependencies are met
2024/06/13 09:57:33 main.go:200: operation status: running operation add-column with run id 14837096706164562750
2024/06/13 09:57:33 run.go:587: operation status: adding column add_column_op_3783570505 to table cct_tpcc.order_line
2024/06/13 18:06:53 run.go:587: operation status: column add_column_op_3783570505 created
2024/06/13 18:06:53 main.go:200: operation status: operation ran successfully; waiting 5m0s before cleanup
2024/06/13 18:11:53 main.go:200: operation status: running cleanup
2024/06/13 18:11:53 run.go:613: operation status: dropping column add_column_op_3783570505
```

The console also shows that the drop column was running at that time:

<img width="1451" alt="image" src="https://github.com/cockroachdb/cockroach/assets/18447034/695f9188-d9c0-4661-b899-64175003063f">

During that period of time, the Console also shows us this:

<img width="434" alt="image" src="https://github.com/cockroachdb/cockroach/assets/18447034/3ed9c646-61f9-4626-9c63-cf594fef9f61">

The blip around 0:30 is fairly short, but then there's a ~2 hour impact period where I can't trace it to anything else running on the cluster aside from this schema change (the other workloads are not changing during this time period).

@rafiss, are you able to have another look?

**Comment by rafiss** [comment]
I do see that n1 was running with more CPU usage than the others during this time. Unfortunately most of the logs have already rotated away. The earliest one I could save is from 2024-06-14 at 03:29:27. 

Based on the CPU usage pattern. I wonder if we're still missing a case for scattering ranges when doing an index backfill. It seems like the ADD COLUMN case was fine, but maybe it's not happening for DROP COLUMN.

I'll look into it more next week. I've saved the logs I could here (only from n1): 
[drt-logs_2024-06-14.tgz](https://github.com/user-attachments/files/15844324/drt-logs_2024-06-14.tgz)

**Comment by rafiss** [comment]
Collecting some findings:

Another thing that changed in the cluster during this time interval is that the live node count dropped.
<img width="899" alt="image" src="https://github.com/cockroachdb/cockroach/assets/1320573/dda6f092-3574-4c1c-a6b1-93aaa956f984">

Around this time, we can see the count of under-replicated ranges spike way up.
<img width="888" alt="image" src="https://github.com/cockroachdb/cockroach/assets/1320573/84c7a54f-2a15-41d8-a066-9750df6c02d0">

And it seems like for some reason, n1 picked up most of the new replicas shortly thereafter.
<img width="895" alt="image" src="https://github.com/cockroachdb/cockroach/assets/1320573/3d868fa7-372e-44df-a1c5-f1406d172415">


During the period of the latency impact, n1 is filled with many logs that show it might be overloaded.

```
raft ready handling: 0.65s [append=0.00s, apply=0.00s, , other=0.65s], wrote []; node might be overloaded

slow replica RPC: have been waiting 19.56s (0 attempts) for RPC GC [/Table/107/78/‹1546›/‹8›/‹0›,/Table/107/78/‹1546›/‹8›/‹0›/‹NULL›), GC [/Table/107/78/‹1692›/‹6›/‹0›,/Table/107/78/‹1692›/‹6›/‹0›/‹NULL›), GC [/Table/107/78/‹1609›/‹6›/‹0›,/Table/107/78/‹1609›/‹6›/‹0›/‹NULL›), GC [/Table/107/78/‹1558›/‹10›/‹0›,/Table/107/78/‹1558›/‹10›/‹0›/‹NULL›), GC [/Table/107/78/‹1563›/‹8›/‹0›,/Table/107/78/‹1563›/‹8›/‹0›/‹NULL›), GC [/Table/107/78/‹1566›/‹1›/‹0›,/Table/107/78/‹1566›/‹1›/‹0›/‹NULL›), GC [/Table/107/78/‹1643›/‹5›/‹0›,/Table/107/78/‹1643›/‹5›/‹0›/‹NULL›), GC [/Table/107/78/‹1597›/‹8›/‹0›,/Table/107/78/‹1597›/‹8›/‹0›/‹NULL›), GC [/Table/107/78/‹1639›/‹9›/‹0›,/Table/107/78/‹1639›/‹9›/‹0›/‹NULL›), GC [/Table/107/78/‹1586›/‹3›/‹0›,/Table/107/78/‹1586›/‹3›/‹0›/‹NULL›), GC [/Table/107/78/‹1538›/‹3›/‹0›,/Table/107/78/‹1538›/‹3›/‹0›/‹NULL›), GC [/Table/107/78/‹1640›/‹5›/‹0›,/Table/107/78/‹1640›/‹5›/‹0›/‹NULL›), GC [/Table/107/78/‹1657›/‹9›/‹0›,/Table/107/78/‹1657›/‹9›/‹0›/‹NULL›), GC [/Table/107/78/‹1550›/‹4›/‹0›,/Table/107/78/‹1550›/‹4›/‹0›/‹NULL›), GC [/Table/107/78/‹1640›/‹10›/‹0›,/Table/107/78/‹1640›/‹10›/‹0›/‹NULL›), GC [/Table/107/78/‹1596›/‹9›/‹0›,/Table/107/78/‹1596›/‹9›/‹0›/‹NULL›), GC [/Table/107/78/‹1608›/‹9›/‹0›,/Table/107/78/‹1608›/‹9›/‹0›/‹NULL›), GC [/Table/107/78/‹1687›/‹8›/‹0›,/Table/107/78/‹1687›/‹8›/‹0›/‹NULL›), GC [/Table/107/78/‹1691›/‹8›/‹0›,/Table/107/78/‹1691›/‹8›/‹0›/‹NULL›), GC [/Table/107/78/‹1586›/‹10›/‹0›,/Table/107/78/‹1586›/‹10›/‹0›/‹NULL›), GC [/Table/107/78/‹1645›/‹4›/‹0›,/Table/107/78/‹1645›/‹4›/‹0›/‹NULL›) to replica (n1,s2):19; resp: ‹(err: context deadline exceeded)›

‹queue.consistencyChecker: processing replica [outer]›: skipping 5 since replica can't be processed needs lease, not adding: repl=(n9,s32):1 seq=2456 start=1718336435.662286267,1 exp=1718343495.576181127,0 pro=1718343489.576181127,0
```

Finally, just noting that one other thing running on the cluster during this time was the GC job for the `ALTER TABLE ... ADD COLUMN` operation.

<img width="1498" alt="image" src="https://github.com/cockroachdb/cockroach/assets/1320573/764bb45d-e0f0-4b32-a365-04b4091661af">

**Comment by rafiss** [comment]
It looks the latency returned to normal right after the lease transfers finished up. During the incident period, the rate of range remove operations was also higher than normal. Both lease transfers and removes spiked up dramatically at 1:44, right before the incident started at 1:45.
<img width="891" alt="image" src="https://github.com/cockroachdb/cockroach/assets/1320573/b996f47f-f7ca-4a28-9498-f8b1ee3b6585">

I feel like this incident is more likely related to the loss of the node and ensuing lease transfers, as opposed to being caused by the schema change. WDYT @ajstorm?

**Comment by ajstorm** [comment]
Thanks for having another look.  I agree that this appears to be another red herring.  I didn't catch the node failure at first glance because it was unexpected (the node died due to out-of-disk, and wasn't killed by the operations framework), but seeing that does explain the latency behaviour.  

Closing again, hopefully for good.

**Comment by rafiss** [comment]
Sounds good! If there is something to investigate here, I think it would be: "why did n1 seem to pick up more of the replicas from the downed node as compared to all the other nodes in the cluster?" This could be a thread that KV might want to pull on, but I'm not sure.

**Comment by ajstorm** [comment]
I wonder if that's because n1 and n2 are in the same zone and the allocator is trying to rebalance the replicas across the three zones?
