### ISSUE TITLE
Cannot restore backup unknown type kind COMPOSITE

### ISSUE THREAD

**Issue by furstenheim-goodnotes** [cockroachdb/cockroach#125550]
**Describe the problem**

* Backup our prod db.
* Create a new cockroachdb instance with the same version `CockroachDB CCL v23.2.4`.
* Try to restore backup: `RESTORE DATABASE my_db from 'nodelocal://self/my_db';`

This fails:

```
ERROR: internal error: unknown type kind COMPOSITE
SQLSTATE: XX000
DETAIL: stack trace:
github.com/cockroachdb/cockroach/pkg/sql/catalog/rewrite/rewrite.go:670: TypeDescs()
github.com/cockroachdb/cockroach/pkg/ccl/backupccl/restore_planning.go:2177: doRestorePlan()
github.com/cockroachdb/cockroach/pkg/ccl/backupccl/restore_planning.go:1449: func3()
github.com/cockroachdb/cockroach/pkg/sql/planhook.go:206: func1()
src/runtime/asm_amd64.s:1650: goexit()

HINT: You have encountered an unexpected error.

Please check the public issue tracker to check whether this problem is
already tracked. If you cannot find it there, please report the error
with details by creating a new issue.

If you would rather not post publicly, please contact us directly
using the support form.


```

**Additional data / screenshots**

**Environment:**
 - CockroachDB version CockroachDB CCL v23.2.4
 - Server OS: Linux
 - Client app cockroach sql

Jira issue: CRDB-39507

**Comment by furstenheim-goodnotes** [comment]
My guess is this code, but I have no way of knowing:

```
CREATE TYPE IF NOT EXISTS some_type AS (
    a UUID,
    b UUID
)
```

They were only supported in one of the latest versions of crdb. A different db doesn't have these and the restore is working

**Comment by furstenheim-goodnotes** [comment]
https://github.com/cockroachdb/cockroach/blob/d102f9db95fb91646a980334207894831c079a79/pkg/sql/catalog/rewrite/rewrite.go#L670

There are enums, aliases, but no composites

**Comment by michae2** [comment]
Thanks for the bug report, @furstenheim-goodnotes. I can reproduce it on a demo cluster with the following:

```sql
CREATE TYPE IF NOT EXISTS some_type AS (a UUID, b UUID, c INT);
BACKUP DATABASE defaultdb INTO 'nodelocal://1/backup';
RESTORE DATABASE defaultdb FROM LATEST IN 'nodelocal://1/backup' WITH new_db_name = 'db';
```

Gives this error message:
```
ERROR: internal error: type descriptor rewrite failed: unknown type kind COMPOSITE
SQLSTATE: XX000
DETAIL: stack trace:
github.com/cockroachdb/cockroach/pkg/sql/catalog/rewrite/rewrite.go:670: TypeDescs()
github.com/cockroachdb/cockroach/pkg/ccl/backupccl/restore_planning.go:2103: doRestorePlan()
github.com/cockroachdb/cockroach/pkg/ccl/backupccl/restore_planning.go:1428: func3()
github.com/cockroachdb/cockroach/pkg/sql/planhook.go:201: func1()
src/runtime/asm_arm64.s:1222: goexit()
```

**Comment by michae2** [comment]
I think this actually might fall within @cockroachdb/sql-foundations purview.

**Comment by furstenheim-goodnotes** [comment]
Hi @michae2, could you please assist? I have some lost data that I need to recover from that backup :worried: . The types are not used in any table (just for queries), so it should be possible to strip them from the backup. That, or a patch of crdb that I could use. Thanks

**Comment by msbutler** [comment]
@furstenheim-goodnotes if the types are not used in any table, could you try restoring every table in your database individually?

**Comment by msbutler** [comment]
To conduct a "dry run" before running the real deal restore commands, try restoring the tables with the `schema_only` option. If all the dry run commands succeed, then i recommend running the commands without the schema_only option.

**Comment by furstenheim-goodnotes** [comment]
> @furstenheim-goodnotes if the types are not used in any table, could you try restoring every table in your database individually?

Ok, I think that will be enough in this case. Thanks

**Comment by rafiss** [comment]
To fix this, we need to add a case for composite types here: https://github.com/cockroachdb/cockroach/blob/3ee65b4394fa5859af0091887d4419a01e1ff1c2/pkg/sql/catalog/rewrite/rewrite.go#L659-L671
(and let's make sure we get test coverage of this too when we fix it)
