### ISSUE TITLE
schema: pause schema change job when running out of disk space

### ISSUE THREAD

**Issue by rimadeodhar** [cockroachdb/cockroach#125513]
Currently, we pause a schema change job when its running out of disk space during an operation involving an [index backfill](https://github.com/cockroachdb/cockroach/blob/d7f4220dcb9e1b4d3f730cea42e7946f22acb609/pkg/sql/backfill.go#L2265). 

Ask: Can we expand this functionality to [column backfill](https://github.com/cockroachdb/cockroach/blob/d7f4220dcb9e1b4d3f730cea42e7946f22acb609/pkg/sql/backfill.go#L2395) as well? 

This will help prevent a schema change from consuming all disk space and causing a cluster outage particularly on underprovisioned systems. See this [support ticket](https://github.com/cockroachlabs/support/issues/2987) for an example of such a case.

Jira issue: CRDB-39494

**Comment by rimadeodhar** [comment]
@fqazi - what do you think of the above approach? We should be able to expand this for other schema changes involving backfill as well right?

**Comment by fqazi** [comment]
I think its a reasonable approach, and I think was probably not there because it seems far less likely. We probably didn't expect the column backfill to balloon the size too much with an in place backfill.

**Comment by rimadeodhar** [comment]
I think there is a very real possibility of column backfill leading to this scenario. In the legacy case, we will rewrite all the rows containing the new column which easily 2x the table size until GC runs. With the declarative schema changer, we simply recreate the index so once again the space usage is high. I think this is worth prioritizing as it will at least prevent cluster outages due to the disk filling up.

**Comment by rafiss** [comment]
Let's add this check for the column backfiller here:
https://github.com/cockroachdb/cockroach/blob/d7f4220dcb9e1b4d3f730cea42e7946f22acb609/pkg/sql/backfill.go#L2393-L2397

And also in the declarative schema changer here: https://github.com/cockroachdb/cockroach/blob/379a702779ebcc4ff567a2feda7b27642509895a/pkg/sql/schemachanger/scexec/exec_backfill.go#L47
