### ISSUE TITLE
Sentry: error.go:89: unexpected error from the vectorized engine: runtime error: slice bounds out of range [18:9]
(1)
Wraps: (2) assertion failure
Wraps: (3) attached stack trace
  -- stack trace:
  |...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#125851]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5503698503/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5503698503/?referrer=webhooks_plugin)

Panic Message:

```
error.go:89: unexpected error from the vectorized engine: runtime error: slice bounds out of range [18:9]
(1)
Wraps: (2) assertion failure
Wraps: (3) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:89
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | runtime.goPanicSliceB
  | 	GOROOT/src/runtime/panic.go:153
  | github.com/cockroachdb/cockroach/pkg/sql/colfetcher.(*cFetcher).processValueBytes
  | 	github.com/cockroachdb/cockroach/pkg/sql/colfetcher/cfetcher.go:1246
  | github.com/cockroachdb/cockroach/pkg/sql/colfetcher.(*cFetcher).processValue
  | 	github.com/cockroachdb/cockroach/pkg/sql/colfetcher/cfetcher.go:1058
  | github.com/cockroachdb/cockroach/pkg/sql/colfetcher.(*cFetcher).NextBatch
  | 	github.com/cockroachdb/cockroach/pkg/sql/colfetcher/cfetcher.go:822
  | github.com/cockroachdb/cockroach/pkg/sql/colfetcher.(*ColIndexJoin).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colfetcher/index_join.go:230
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils.(*CancelChecker).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils/cancel_checker.go:59
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:118
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:126
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Materializer).next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:247
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Materializer).nextAdapter
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:272
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Materializer).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:278
  | github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*inputStatCollector).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowexec/stats.go:69
  | github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*joinReader).readInput
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowexec/joinreader.go:908
  | github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*joinReader).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowexec/joinreader.go:774
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Columnarizer).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/columnarizer.go:239
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:118
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:126
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).nextAdapter
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:250
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:254
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:286
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:328
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:902
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1895
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll.func3
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1627
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1630
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2206
Wraps: (4) unexpected error from the vectorized engine
Wraps: (5) runtime error: slice bounds out of range [18:9]
  | -- cause hidden behind barrier
  | runtime error: slice bounds out of range [18:9]
  | (1) runtime error: slice bounds out of range [18:9]
  | Error types: (1) runtime.boundsError
Error types: (1) *colexecerror.notInternalError (2) *assert.withAssertionFailure (3) *withstack.withStack (4) *errutil.withPrefix (5) *barriers.barrierErr
-- report composition:
*barriers.barrierErr: masked error: runtime error: slice bounds out of range [18:9]
*errutil.withPrefix: unexpected error from the vectorized engine
error.go:89: *withstack.withStack (top exception)
*assert.withAssertionFailure
*colexecerror.notInternalError
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/conn_executor_exec.go#L2205-L2207](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/conn_executor_exec.go#L2205-L2207)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/distsql_running.go#L1629-L1631](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/distsql_running.go#L1629-L1631)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/distsql_running.go#L1626-L1628](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/distsql_running.go#L1626-L1628)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/distsql_running.go#L1894-L1896](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/distsql_running.go#L1894-L1896)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/distsql_running.go#L901-L903](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/distsql_running.go#L901-L903)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colflow/vectorized_flow.go#L327-L329](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colflow/vectorized_flow.go#L327-L329)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colflow/flow_coordinator.go#L285-L287](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colflow/flow_coordinator.go#L285-L287)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colflow/flow_coordinator.go#L253-L255](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colflow/flow_coordinator.go#L253-L255)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colflow/flow_coordinator.go#L249-L251](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colflow/flow_coordinator.go#L249-L251)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colflow/stats.go#L125-L127](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colflow/stats.go#L125-L127)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colflow/stats.go#L117-L119](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colflow/stats.go#L117-L119)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colexec/columnarizer.go#L238-L240](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colexec/columnarizer.go#L238-L240)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/rowexec/joinreader.go#L773-L775](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/rowexec/joinreader.go#L773-L775)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/rowexec/joinreader.go#L907-L909](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/rowexec/joinreader.go#L907-L909)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/rowexec/stats.go#L68-L70](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/rowexec/stats.go#L68-L70)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colexec/materializer.go#L277-L279](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colexec/materializer.go#L277-L279)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colexec/materializer.go#L271-L273](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colexec/materializer.go#L271-L273)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colexec/materializer.go#L246-L248](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colexec/materializer.go#L246-L248)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colflow/stats.go#L125-L127](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colflow/stats.go#L125-L127)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colflow/stats.go#L117-L119](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colflow/stats.go#L117-L119)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colexec/colexecutils/cancel_checker.go#L58-L60](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colexec/colexecutils/cancel_checker.go#L58-L60)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colfetcher/index_join.go#L229-L231](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colfetcher/index_join.go#L229-L231)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colfetcher/cfetcher.go#L821-L823](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colfetcher/cfetcher.go#L821-L823)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colfetcher/cfetcher.go#L1057-L1059](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colfetcher/cfetcher.go#L1057-L1059)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colfetcher/cfetcher.go#L1245-L1247](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colfetcher/cfetcher.go#L1245-L1247)
[GOROOT/src/runtime/panic.go#L152-L154](GOROOT/src/runtime/panic.go#L152-L154)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colexecerror/error.go#L88-L90](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colexecerror/error.go#L88-L90)
</details>

```
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithDistSQLEngine at line 2206
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRunAll at line 1630
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRunAll.func3 at line 1627
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRun at line 1895
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).Run at line 902
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlow).Run at line 328
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).Run at line 286
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).next at line 254
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).nextAdapter at line 250
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).Next at line 126
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).next at line 118
pkg/sql/colexec/columnarizer.go in pkg/sql/colexec.(*Columnarizer).Next at line 239
pkg/sql/rowexec/joinreader.go in pkg/sql/rowexec.(*joinReader).Next at line 774
pkg/sql/rowexec/joinreader.go in pkg/sql/rowexec.(*joinReader).readInput at line 908
pkg/sql/rowexec/stats.go in pkg/sql/rowexec.(*inputStatCollector).Next at line 69
pkg/sql/colexec/materializer.go in pkg/sql/colexec.(*Materializer).Next at line 278
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colexec/materializer.go in pkg/sql/colexec.(*Materializer).nextAdapter at line 272
pkg/sql/colexec/materializer.go in pkg/sql/colexec.(*Materializer).next at line 247
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).Next at line 126
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).next at line 118
pkg/sql/colexec/colexecutils/cancel_checker.go in pkg/sql/colexec/colexecutils.(*CancelChecker).Next at line 59
pkg/sql/colfetcher/index_join.go in pkg/sql/colfetcher.(*ColIndexJoin).Next at line 230
pkg/sql/colfetcher/cfetcher.go in pkg/sql/colfetcher.(*cFetcher).NextBatch at line 822
pkg/sql/colfetcher/cfetcher.go in pkg/sql/colfetcher.(*cFetcher).processValue at line 1058
pkg/sql/colfetcher/cfetcher.go in pkg/sql/colfetcher.(*cFetcher).processValueBytes at line 1246
GOROOT/src/runtime/panic.go in runtime.goPanicSliceB at line 153
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1 at line 89
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v23.1.17 |
| Go Version | go1.19.13 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.17 |
| Cockroach SHA | d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346 |
| # of CPUs | 8 |
| # of Goroutines | 1038 |

Jira issue: CRDB-39637

**Comment by yuzefovich** [comment]
dup of #125849
