### ISSUE TITLE
sql: ALTER COLUMN TYPE on virtual column fails

### ISSUE THREAD

**Issue by spilchen** [cockroachdb/cockroach#125840]
**Describe the problem**

Any attempt to alter the column type of a computed virtual column will result in an error.

**To Reproduce**

What did you do?

```
demo@127.0.0.1:26257/demoapp/movr> SET enable_experimental_alter_column_type_general = true;
SET

Time: 1ms total (execution 1ms / network 0ms)

demo@127.0.0.1:26257/demoapp/movr> create table t1 (real1 int, comp1 int as (real1 * 2) virtual);
CREATE TABLE

Time: 7ms total (execution 7ms / network 0ms)

demo@127.0.0.1:26257/demoapp/movr> alter table t1 alter column comp1 type float;
ERROR: no column family found for column id 2
```

**Expected behavior**
Postgres does not support virtual columns yet, but it does support stored computed columns. It also allows altering the type of these stored computed columns. So, the expected behaviour here is to allow it as well.

Epic CRDB-25314

Jira issue: CRDB-39631

**Comment by rafiss** [comment]
Nice find! Do you know what the expected behavior is if the new type is not compatible with the original computed column expression?

**Comment by spilchen** [comment]
Good suggestion. Yeah, it works if going from int->bigint.
```
demo@127.0.0.1:26257/demoapp/movr> alter table t1 alter column comp1 type bigint;
ALTER TABLE
```
