### ISSUE TITLE
Sentry: error.go:89: unexpected error from the vectorized engine: runtime error: slice bounds out of range [2689:15]
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github....

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#125849]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5503692017/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5503692017/?referrer=webhooks_plugin)

Panic Message:

```
error.go:89: unexpected error from the vectorized engine: runtime error: slice bounds out of range [2689:15]
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:89
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | runtime.goPanicSliceB
  | 	GOROOT/src/runtime/panic.go:153
  | github.com/cockroachdb/cockroach/pkg/util/encoding.DecodeUntaggedBytesValue
  | 	github.com/cockroachdb/cockroach/pkg/util/encoding/encoding.go:2808
  | github.com/cockroachdb/cockroach/pkg/sql/colencoding.DecodeTableValueToCol
  | 	github.com/cockroachdb/cockroach/pkg/sql/colencoding/value_encoding.go:65
  | github.com/cockroachdb/cockroach/pkg/sql/colfetcher.(*cFetcher).processValueBytes
  | 	github.com/cockroachdb/cockroach/pkg/sql/colfetcher/cfetcher.go:1257
  | github.com/cockroachdb/cockroach/pkg/sql/colfetcher.(*cFetcher).processValue
  | 	github.com/cockroachdb/cockroach/pkg/sql/colfetcher/cfetcher.go:1058
  | github.com/cockroachdb/cockroach/pkg/sql/colfetcher.(*cFetcher).NextBatch
  | 	github.com/cockroachdb/cockroach/pkg/sql/colfetcher/cfetcher.go:822
  | github.com/cockroachdb/cockroach/pkg/sql/colfetcher.(*ColBatchScan).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colfetcher/colbatch_scan.go:258
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils.(*CancelChecker).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils/cancel_checker.go:59
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecsel.(*selLTInt64Int64ConstOp).Next
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/colexec/colexecsel/selection_ops.eg.go:24779
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecbase.(*simpleProjectOp).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecbase/simple_project.go:124
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Materializer).next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:247
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Materializer).nextAdapter
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:272
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Materializer).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:278
  | github.com/cockroachdb/cockroach/pkg/sql.(*rowSourceToPlanNode).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/row_source_to_plan_node.go:79
  | github.com/cockroachdb/cockroach/pkg/sql.(*bufferNode).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/buffer.go:48
  | github.com/cockroachdb/cockroach/pkg/sql.(*deleteNode).BatchedNext
  | 	github.com/cockroachdb/cockroach/pkg/sql/delete.go:110
  | github.com/cockroachdb/cockroach/pkg/sql.(*rowCountNode).startExec
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_batch.go:173
  | github.com/cockroachdb/cockroach/pkg/sql.startExec.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan.go:519
  | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:112
  | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:299
  | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:79
  | github.com/cockroachdb/cockroach/pkg/sql.walkPlan
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:43
  | github.com/cockroachdb/cockroach/pkg/sql.startExec
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan.go:522
  | github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Start
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:175
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*FlowCoordinator).Start.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:120
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*FlowCoordinator).Start
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:119
  | github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBaseNoHelper).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:725
  | github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:580
Wraps: (3) unexpected error from the vectorized engine
Wraps: (4) runtime error: slice bounds out of range [2689:15]
  | -- cause hidden behind barrier
  | runtime error: slice bounds out of range [2689:15]
  | (1) runtime error: slice bounds out of range [2689:15]
  | Error types: (1) runtime.boundsError
Error types: (1) *assert.withAssertionFailure (2) *withstack.withStack (3) *errutil.withPrefix (4) *barriers.barrierErr
-- report composition:
*barriers.barrierErr: masked error: runtime error: slice bounds out of range [2689:15]
*errutil.withPrefix: unexpected error from the vectorized engine
error.go:89: *withstack.withStack (top exception)
*assert.withAssertionFailure
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/flowinfra/flow.go#L579-L581](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/flowinfra/flow.go#L579-L581)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/execinfra/processorsbase.go#L724-L726](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/execinfra/processorsbase.go#L724-L726)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colflow/flow_coordinator.go#L118-L120](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colflow/flow_coordinator.go#L118-L120)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colflow/flow_coordinator.go#L119-L121](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colflow/flow_coordinator.go#L119-L121)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/plan_node_to_row_source.go#L174-L176](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/plan_node_to_row_source.go#L174-L176)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/plan.go#L521-L523](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/plan.go#L521-L523)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/walk.go#L42-L44](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/walk.go#L42-L44)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/walk.go#L78-L80](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/walk.go#L78-L80)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/walk.go#L298-L300](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/walk.go#L298-L300)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/walk.go#L111-L113](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/walk.go#L111-L113)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/plan.go#L518-L520](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/plan.go#L518-L520)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/plan_batch.go#L172-L174](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/plan_batch.go#L172-L174)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/delete.go#L109-L111](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/delete.go#L109-L111)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/buffer.go#L47-L49](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/buffer.go#L47-L49)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/row_source_to_plan_node.go#L78-L80](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/row_source_to_plan_node.go#L78-L80)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colexec/materializer.go#L277-L279](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colexec/materializer.go#L277-L279)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colexec/materializer.go#L271-L273](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colexec/materializer.go#L271-L273)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colexec/materializer.go#L246-L248](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colexec/materializer.go#L246-L248)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colexec/colexecbase/simple_project.go#L123-L125](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colexec/colexecbase/simple_project.go#L123-L125)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/bazel-out/k8-opt/bin/pkg/sql/colexec/colexecsel/selection_ops.eg.go#L24778-L24780](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/bazel-out/k8-opt/bin/pkg/sql/colexec/colexecsel/selection_ops.eg.go#L24778-L24780)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colexec/colexecutils/cancel_checker.go#L58-L60](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colexec/colexecutils/cancel_checker.go#L58-L60)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colfetcher/colbatch_scan.go#L257-L259](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colfetcher/colbatch_scan.go#L257-L259)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colfetcher/cfetcher.go#L821-L823](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colfetcher/cfetcher.go#L821-L823)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colfetcher/cfetcher.go#L1057-L1059](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colfetcher/cfetcher.go#L1057-L1059)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colfetcher/cfetcher.go#L1256-L1258](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colfetcher/cfetcher.go#L1256-L1258)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colencoding/value_encoding.go#L64-L66](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colencoding/value_encoding.go#L64-L66)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/util/encoding/encoding.go#L2807-L2809](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/util/encoding/encoding.go#L2807-L2809)
[GOROOT/src/runtime/panic.go#L152-L154](GOROOT/src/runtime/panic.go#L152-L154)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colexecerror/error.go#L88-L90](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colexecerror/error.go#L88-L90)
</details>

```
pkg/sql/flowinfra/flow.go in pkg/sql/flowinfra.(*FlowBase).Run at line 580
pkg/sql/execinfra/processorsbase.go in pkg/sql/execinfra.(*ProcessorBaseNoHelper).Run at line 725
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*FlowCoordinator).Start at line 119
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*FlowCoordinator).Start.func1 at line 120
pkg/sql/plan_node_to_row_source.go in pkg/sql.(*planNodeToRowSource).Start at line 175
pkg/sql/plan.go in pkg/sql.startExec at line 522
pkg/sql/walk.go in pkg/sql.walkPlan at line 43
pkg/sql/walk.go in pkg/sql.(*planVisitor).visit at line 79
pkg/sql/walk.go in pkg/sql.(*planVisitor).visitInternal at line 299
pkg/sql/walk.go in pkg/sql.(*planVisitor).visitInternal.func1 at line 112
pkg/sql/plan.go in pkg/sql.startExec.func2 at line 519
pkg/sql/plan_batch.go in pkg/sql.(*rowCountNode).startExec at line 173
pkg/sql/delete.go in pkg/sql.(*deleteNode).BatchedNext at line 110
pkg/sql/buffer.go in pkg/sql.(*bufferNode).Next at line 48
pkg/sql/row_source_to_plan_node.go in pkg/sql.(*rowSourceToPlanNode).Next at line 79
pkg/sql/colexec/materializer.go in pkg/sql/colexec.(*Materializer).Next at line 278
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colexec/materializer.go in pkg/sql/colexec.(*Materializer).nextAdapter at line 272
pkg/sql/colexec/materializer.go in pkg/sql/colexec.(*Materializer).next at line 247
pkg/sql/colexec/colexecbase/simple_project.go in pkg/sql/colexec/colexecbase.(*simpleProjectOp).Next at line 124
bazel-out/k8-opt/bin/pkg/sql/colexec/colexecsel/selection_ops.eg.go in pkg/sql/colexec/colexecsel.(*selLTInt64Int64ConstOp).Next at line 24779
pkg/sql/colexec/colexecutils/cancel_checker.go in pkg/sql/colexec/colexecutils.(*CancelChecker).Next at line 59
pkg/sql/colfetcher/colbatch_scan.go in pkg/sql/colfetcher.(*ColBatchScan).Next at line 258
pkg/sql/colfetcher/cfetcher.go in pkg/sql/colfetcher.(*cFetcher).NextBatch at line 822
pkg/sql/colfetcher/cfetcher.go in pkg/sql/colfetcher.(*cFetcher).processValue at line 1058
pkg/sql/colfetcher/cfetcher.go in pkg/sql/colfetcher.(*cFetcher).processValueBytes at line 1257
pkg/sql/colencoding/value_encoding.go in pkg/sql/colencoding.DecodeTableValueToCol at line 65
pkg/util/encoding/encoding.go in pkg/util/encoding.DecodeUntaggedBytesValue at line 2808
GOROOT/src/runtime/panic.go in runtime.goPanicSliceB at line 153
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1 at line 89
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v23.1.17 |
| Go Version | go1.19.13 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.17 |
| Cockroach SHA | d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346 |
| # of CPUs | 8 |
| # of Goroutines | 1024 |

Jira issue: CRDB-39635

**Comment by yuzefovich** [comment]
unactionable
