### ISSUE TITLE
Sentry: error.go:89: unexpected error from the vectorized engine: runtime error: slice bounds out of range [18:9]
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#125850]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5503698123/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5503698123/?referrer=webhooks_plugin)

Panic Message:

```
error.go:89: unexpected error from the vectorized engine: runtime error: slice bounds out of range [18:9]
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:89
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | runtime.goPanicSliceB
  | 	GOROOT/src/runtime/panic.go:153
  | github.com/cockroachdb/cockroach/pkg/sql/colfetcher.(*cFetcher).processValueBytes
  | 	github.com/cockroachdb/cockroach/pkg/sql/colfetcher/cfetcher.go:1246
  | github.com/cockroachdb/cockroach/pkg/sql/colfetcher.(*cFetcher).processValue
  | 	github.com/cockroachdb/cockroach/pkg/sql/colfetcher/cfetcher.go:1058
  | github.com/cockroachdb/cockroach/pkg/sql/colfetcher.(*cFetcher).NextBatch
  | 	github.com/cockroachdb/cockroach/pkg/sql/colfetcher/cfetcher.go:822
  | github.com/cockroachdb/cockroach/pkg/sql/colfetcher.(*ColIndexJoin).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colfetcher/index_join.go:230
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils.(*CancelChecker).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils/cancel_checker.go:59
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Materializer).next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:247
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Materializer).nextAdapter
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:272
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Materializer).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:278
  | github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*joinReader).readInput
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowexec/joinreader.go:908
  | github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*joinReader).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowexec/joinreader.go:774
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*FlowCoordinator).next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:128
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*FlowCoordinator).nextAdapter
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:145
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*FlowCoordinator).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:150
  | github.com/cockroachdb/cockroach/pkg/sql/execinfra.Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/execinfra/base.go:193
  | github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBaseNoHelper).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:726
  | github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:580
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:313
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:902
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1895
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll.func3
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1627
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1630
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2206
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1760
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1058
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:142
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:3142
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:141
Wraps: (3) unexpected error from the vectorized engine
Wraps: (4) runtime error: slice bounds out of range [18:9]
  | -- cause hidden behind barrier
  | runtime error: slice bounds out of range [18:9]
  | (1) runtime error: slice bounds out of range [18:9]
  | Error types: (1) runtime.boundsError
Error types: (1) *assert.withAssertionFailure (2) *withstack.withStack (3) *errutil.withPrefix (4) *barriers.barrierErr
-- report composition:
*barriers.barrierErr: masked error: runtime error: slice bounds out of range [18:9]
*errutil.withPrefix: unexpected error from the vectorized engine
error.go:89: *withstack.withStack (top exception)
*assert.withAssertionFailure
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/conn_executor_exec.go#L140-L142](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/conn_executor_exec.go#L140-L142)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/conn_executor_exec.go#L3141-L3143](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/conn_executor_exec.go#L3141-L3143)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/conn_executor_exec.go#L141-L143](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/conn_executor_exec.go#L141-L143)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/conn_executor_exec.go#L1057-L1059](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/conn_executor_exec.go#L1057-L1059)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/conn_executor_exec.go#L1759-L1761](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/conn_executor_exec.go#L1759-L1761)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/conn_executor_exec.go#L2205-L2207](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/conn_executor_exec.go#L2205-L2207)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/distsql_running.go#L1629-L1631](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/distsql_running.go#L1629-L1631)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/distsql_running.go#L1626-L1628](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/distsql_running.go#L1626-L1628)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/distsql_running.go#L1894-L1896](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/distsql_running.go#L1894-L1896)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/distsql_running.go#L901-L903](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/distsql_running.go#L901-L903)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colflow/vectorized_flow.go#L312-L314](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colflow/vectorized_flow.go#L312-L314)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/flowinfra/flow.go#L579-L581](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/flowinfra/flow.go#L579-L581)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/execinfra/processorsbase.go#L725-L727](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/execinfra/processorsbase.go#L725-L727)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/execinfra/base.go#L192-L194](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/execinfra/base.go#L192-L194)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colflow/flow_coordinator.go#L149-L151](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colflow/flow_coordinator.go#L149-L151)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colflow/flow_coordinator.go#L144-L146](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colflow/flow_coordinator.go#L144-L146)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colflow/flow_coordinator.go#L127-L129](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colflow/flow_coordinator.go#L127-L129)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/rowexec/joinreader.go#L773-L775](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/rowexec/joinreader.go#L773-L775)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/rowexec/joinreader.go#L907-L909](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/rowexec/joinreader.go#L907-L909)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colexec/materializer.go#L277-L279](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colexec/materializer.go#L277-L279)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colexec/materializer.go#L271-L273](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colexec/materializer.go#L271-L273)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colexec/materializer.go#L246-L248](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colexec/materializer.go#L246-L248)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colexec/colexecutils/cancel_checker.go#L58-L60](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colexec/colexecutils/cancel_checker.go#L58-L60)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colfetcher/index_join.go#L229-L231](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colfetcher/index_join.go#L229-L231)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colfetcher/cfetcher.go#L821-L823](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colfetcher/cfetcher.go#L821-L823)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colfetcher/cfetcher.go#L1057-L1059](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colfetcher/cfetcher.go#L1057-L1059)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colfetcher/cfetcher.go#L1245-L1247](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colfetcher/cfetcher.go#L1245-L1247)
[GOROOT/src/runtime/panic.go#L152-L154](GOROOT/src/runtime/panic.go#L152-L154)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
[https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colexecerror/error.go#L88-L90](https://github.com/cockroachdb/cockroach/blob/d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346/pkg/sql/colexecerror/error.go#L88-L90)
</details>

```
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 141
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithProfiling at line 3142
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt.func1 at line 142
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 1058
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchToExecutionEngine at line 1760
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithDistSQLEngine at line 2206
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRunAll at line 1630
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRunAll.func3 at line 1627
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRun at line 1895
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).Run at line 902
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlow).Run at line 313
pkg/sql/flowinfra/flow.go in pkg/sql/flowinfra.(*FlowBase).Run at line 580
pkg/sql/execinfra/processorsbase.go in pkg/sql/execinfra.(*ProcessorBaseNoHelper).Run at line 726
pkg/sql/execinfra/base.go in pkg/sql/execinfra.Run at line 193
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*FlowCoordinator).Next at line 150
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*FlowCoordinator).nextAdapter at line 145
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*FlowCoordinator).next at line 128
pkg/sql/rowexec/joinreader.go in pkg/sql/rowexec.(*joinReader).Next at line 774
pkg/sql/rowexec/joinreader.go in pkg/sql/rowexec.(*joinReader).readInput at line 908
pkg/sql/colexec/materializer.go in pkg/sql/colexec.(*Materializer).Next at line 278
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colexec/materializer.go in pkg/sql/colexec.(*Materializer).nextAdapter at line 272
pkg/sql/colexec/materializer.go in pkg/sql/colexec.(*Materializer).next at line 247
pkg/sql/colexec/colexecutils/cancel_checker.go in pkg/sql/colexec/colexecutils.(*CancelChecker).Next at line 59
pkg/sql/colfetcher/index_join.go in pkg/sql/colfetcher.(*ColIndexJoin).Next at line 230
pkg/sql/colfetcher/cfetcher.go in pkg/sql/colfetcher.(*cFetcher).NextBatch at line 822
pkg/sql/colfetcher/cfetcher.go in pkg/sql/colfetcher.(*cFetcher).processValue at line 1058
pkg/sql/colfetcher/cfetcher.go in pkg/sql/colfetcher.(*cFetcher).processValueBytes at line 1246
GOROOT/src/runtime/panic.go in runtime.goPanicSliceB at line 153
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1 at line 89
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v23.1.17 |
| Go Version | go1.19.13 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.17 |
| Cockroach SHA | d50ccb5a52cdf5a1f41cbb2fa61ef971c65e1346 |
| # of CPUs | 8 |
| # of Goroutines | 1073 |

Jira issue: CRDB-39636

**Comment by yuzefovich** [comment]
dup of #125849
