### ISSUE TITLE
sqlbase: clarify the semantics of the IndexDescriptor protobuf

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#12594]
Reported/requested by @RaduBerinde in #12583:

https://github.com/cockroachdb/cockroach/pull/12583#issuecomment-269426725

> Does index.ColumnIDs include the "stored columns"? Not obvious from the comments in structured.proto, IndexDescriptor comments need improving (maybe with a couple of examples).

https://github.com/cockroachdb/cockroach/pull/12583#issuecomment-269517841

> Not to me.. Implicit columns are the PK columns that are not part of the index (so they are always a subset of the PK columns). Stored columns can be any columns, and it's not clear from anywhere if column_ids includes those or not. In fact the comment suggest that it does not (column_ids "parallels the column_names list"), unless those columns show up in both column_names and store_column_names (which seems odd).

> So take an example: PK columns are k1, k2 and we have some columns v1, v2. We have an index on (v1,k1) which also stores v3. Implicit columns would be k2. It's unclear to me if column_names includes v3, and if column_ids includes its id. If yes, then is the only way to distinguish between a column that is part of the index or one that is merely stored cross-referencing column_names with stored_column_names?

> In fact I'm looking at EncodeSecondaryIndex and can't really find any code that deals with STORING columns. It may be the case that we treat (v1,k1) storing v3 as just (v1,k1,v3) but that seems incorrect for unique indexes.

https://github.com/cockroachdb/cockroach/pull/12583#issuecomment-269520311

> Or are the stored columns part of the implicit columns? In that case the explanation for implicit columns is incorrect ("The extra column IDs is computed as PrimaryIndex.column_ids - column_ids")..

**Comment by RaduBerinde** [comment]
I had some time to kill on a flight and worked on this, I will send out a PR when I get a chance.
