### ISSUE TITLE
ui: [suggestion] "opt-in" header minor styling tweaks

### ISSUE THREAD

**Issue by cppforlife** [cockroachdb/cockroach#12590]
imho it would be better:

- to insert opt-in header above all other elements instead of overlaying it
  - would not hide any content -- currently hides cluster button
- only show header once appropriate info is loaded (to avoid flashing on page refresh)
  - sometimes page load is slow so there is time between header being visible and then suddenly disappearing

**Comment by a-robinson** [comment]
Thanks for the feedback, @cppforlife 

@kuanluo

**Comment by kuanluo** [comment]
Thanks for the feedback, @cppforlife! 

#1 would be fixed in an upcoming ui update.
We will look into #2 to make sure it's also fixed in the update. cc @maxlang
