### ISSUE TITLE
storage: span and descriptor do not overlap

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#12603]
sha: 789f7499a1e02b11240e58bd5d1232c7827c2943

I'm playing with scalability, this time running photos against a pre-split tables, then running photos on each node locally (using https://github.com/cockroachdb/examples-go/pull/90)
I'm getting the following error:
```
I161229 23:11:40.269828 9 user.go:158  failed to run create photo op for 2598: pq: span and descriptor's range do not overlap: {/Table/52/2/2598/2016-12-29T23:11:40.046354Z/0 /Table/52/1/"Xc]ﻕ\xd4ḤKW\u007f\xc9\xe62|"} vs range_id:1918 start_key:"\274\211\022\377\371\324\242\006yJF\260\267\336-\210s\226;\000\001" end_key:"\275" replicas:<node_id:4 store_id:4 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > replicas:<node_id:3 store_id:3 replica_id:3 > next_replica_id:4
```

eg, from `cockroach-sky-0001.eastus2.cloudapp.azure.com`'s `logs/photos.stderr`, but other nodes show this as well.

@nvanbenschoten, I see a todo with your name in `data.go`.
```
// Intersect returns the intersection of the current span and the
// descriptor's range. Returns an error if the span and the
// descriptor's range do not overlap.
// TODO(nvanbenschoten) Investigate why this returns an endKey when
// rs.EndKey is nil. This gives the method unexpected behavior.
func (rs RSpan) Intersect(desc *RangeDescriptor) (RSpan, error) {
  if !rs.Key.Less(desc.EndKey) || !desc.StartKey.Less(rs.EndKey) {
    return rs, errors.Errorf("span and descriptor's range do not overlap: %s vs %s", rs, desc)
  }
```

**Comment by petermattis** [comment]
@mberhault Is this reproducible?

**Comment by mberhault** [comment]
I'll try again.

**Comment by nvanbenschoten** [comment]
The TODO here almost certainly has nothing to do with this error because the error message shows the `rs.EndKey` does not equal `nil`.

The question I brought up was about the condition `|| endKey == nil {`. An EndKey of nil for a span implies a single-key span, so the TODO is questioning why we extend the intersection in this case. Looking into it further now, I don't believe it is even valid for an RSpan to ever be missing it's `EndKey`. I removed the TODO and the condition in #12646.

**Comment by bdarnell** [comment]
This is still happening as of beta-20170323:

`span and descriptor's range do not overlap: {/Table/51/4/"5140712707"/NULL/"4091112119474418"/0 /Table/51/1/"4091221963483159"} vs range_id:194 start_key:"\273\214\0225098657573\000\001\024\204\247\"\311\037\207\377\0224090989369197332\000\001" end_key:"\273\214\0225594216204\000\001\024\204\247\"\334\305\207\377\0224090990325292389\000\001" replicas:<node_id:3 store_id:3 replica_id:1 > replicas:<node_id:4 store_id:4 replica_id:2 > replicas:<node_id:2 store_id:2 replica_id:3 > next_replica_id:4`

**Comment by petermattis** [comment]
`RSpan.Intersect` is only called outside of tests by `DistSender.sendPartialBatch`. I suspect we have an off-by-one error in the batch splitting logic.

**Comment by nvanbenschoten** [comment]
It looks like in both cases the span's `EndKey` is less than its `StartKey`. I haven't looked at this code in a while, but I don't think that even with a `Descending` scan this is supposed to happen.
