### ISSUE TITLE
Failed to construct index entries during backfill: overflow during Encode

### ISSUE THREAD

**Issue by chenglinLiang** [cockroachdb/cockroach#126103]
**Describe the problem**

An unexpected error occurred while creating an index for INTERVAL.

**To Reproduce**
``` sql
CREATE TABLE t1 (c0 INTERVAL);
INSERT INTO t1 (c0) VALUES ('1518320791 year');
CREATE INDEX ON t1(c0, rowid); 
```
**Expected behavior**
No error.

**Additional data / screenshots**
```
ERROR: failed to construct index entries during backfill: overflow during Encode
SQLSTATE: 22015
```

**Environment:**
 - CockroachDB version [v24.1.0-alpha.5([40cc14f](https://github.com/cockroachdb/cockroach/commit/40cc14f35ef73ab5aed081329e2592301bc2254c))
 - Server OS: [Ubuntu 20.04.6]
 - Client app [`cockroach sql`]

**Additional context**
It might be related to #84078, but the error still occurs in this version. I reproduced it in PostgreSQL, and the `interval out of range` error happens during the INSERT.

Jira issue: CRDB-39777

**Comment by yuzefovich** [comment]
Thanks for the report! Indeed, you ran into a known bug #84078 that we haven't yet fixed - please follow that issue for progress.
