### ISSUE TITLE
schemachanger: make merge phase more contention-aware

### ISSUE THREAD

**Issue by annrpom** [cockroachdb/cockroach#126197]
Now that we have `kv.transaction.internal.max_auto_retries` of 100, schema changes that are in the [MERGE](https://github.com/cockroachdb/cockroach/blob/1ab823efe62e2c4b8be7d9845cd9abf7683088b4/pkg/sql/schemachanger/testdata/end_to_end/add_column/add_column.explain#L128-L132) phase of a backfill could fail with `WriteTooOldError`s due to contention on the rows we are trying to merge (since we might be retrying constantly until num_retries is > 100).

To alleviate this, we should either:
1. Adjust merge chunks dynamically when running into contention (i.e. try full chunk -> retry -> try 1/2 -> retry -> ...). We also will want to bump the txn priority eventually, if there is excessive contention.
2. Treat the max_auto_retries failure as a retry

Jira issue: CRDB-39800

Epic CRDB-40419

**Comment by annrpom** [comment]
@fqazi discovered this here: https://cockroachlabs.slack.com/archives/C0168LW5THS/p1719293407747839

**Comment by rafiss** [comment]
Let's add some logic in the merge planner here: https://github.com/cockroachdb/cockroach/blob/563369567e594c4bd545ca23e0f2f9c2505fc6a0/pkg/sql/mvcc_backfiller.go#L109-L121

If we hit the `max_auto_retries` failure, then we can lower the chunk size and try again.
