### ISSUE TITLE
sql: remove StarDatumInstance

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#12615]
In the following output, `render 1` is a star, which seems wrong. Not sure if this means we're actually rendering all the columns, but at the very least it's confusing output for the EXPLAIN command.

Originated from this conversation: https://reviewable.io/reviews/cockroachdb/cockroach/10146#-K_Bcg0mPxSRQgi1xXRB

```
root@:26257> EXPLAIN (exprs) SELECT 1+COUNT(*) FILTER (WHERE k > 5), MAX(k>5) FILTER (WHERE k > 5) FROM filter_test GROUP BY v;
+-------+---------------+-------------+-----------------------------------------------------------+
| Level |     Type      |    Field    |                        Description                        |
+-------+---------------+-------------+-----------------------------------------------------------+
|     0 | group         |             |                                                           |
|     0 |               | aggregate 0 |                                                         1 |
|     0 |               | aggregate 1 | count(*) FILTER (WHERE k > 5)                             |
|     0 |               | aggregate 2 | max(k > 5) FILTER (WHERE k > 5)                           |
|     0 |               | render 0    | [agg arg "1"] + [agg arg "count(*) FILTER (WHERE k > 5)"] |
|     0 |               | render 1    | [agg arg "max(k > 5) FILTER (WHERE k > 5)"]               |
|     1 | render/filter |             |                                                           |
|     1 |               | render 0    |                                                         1 |
|     1 |               | render 1    | *                                                         |
|     1 |               | render 2    | k > 5                                                     |
|     1 |               | render 3    | v                                                         |
|     2 | scan          |             |                                                           |
|     2 |               | table       | filter_test@primary                                       |
+-------+---------------+-------------+-----------------------------------------------------------
```

**Comment by RaduBerinde** [comment]
I believe that we are indeed rendering a `starDatumInstance` which is a special `VariableExpr` that evaluates to a `DInt(0)` for any source row to facilitate `COUNT(*)`. IMO this is expected. Granted, not the best way to show it in `EXPLAIN` but I can't think of a better concise way to show this either.

**Comment by knz** [comment]
The better way is to not render the stardatuminstance at all :)

**Comment by RaduBerinde** [comment]
The root cause of this is trying to use the same underlying function for both `COUNT(x)` and `COUNT(*)`, even though they really mean different things. One idea to clean this up nicely is to add a parser rule to parse `COUNT(*)` differently as a `count_rows()` function (and we can format `count_rows()` as `count(*)` so wouldn't be externally visible).

**Comment by knz** [comment]
Recent refactorings by Radu have made this code much simpler, while retaining a (good) use for StarDatumInstance. This issue needs not exist any more.

**Comment by RaduBerinde** [comment]
It may still make sense to just remove it and send empty rows instead. Not a big deal though.

**Comment by RaduBerinde** [comment]
I've been working on a change to clean this up.
