### ISSUE TITLE
sql: implement DISTINCT ON (distinct on partial columns)

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#12633]
(Requested on Gitter)

According to the pg docs and clients, `select distinct on(a,b,c), d, e, f from ...` will report the first row worth of `d`, `e`,`f` values for every unique `(a,b,c)` tuple.

I've suggested the semantically equivalent `select name, col1, col2 from (select name, col1, col2, row_number() over (partition by name) as n from names) as s where s.n = 1`

but our implementation of window functions would make this approach horrendously expensive (i.e. it loads all rows into memory!) compared to a naive native implementation.

**Comment by jseldess** [comment]
@knz, we have a simple [`DISTINCT`](https://www.cockroachlabs.com/docs/select.html#select-distinct-rows) example in our `SELECT` docs. Should we add this more complex example as well, in the absence of a native implementation?

**Comment by knz** [comment]
I think it might be too early for that. I am not yet confident my suggestion is valid.

**Comment by jseldess** [comment]
K, thanks, @knz.

**Comment by petermattis** [comment]
Implementing `DISTINCT ON` seems to be a small matter of bookkeeping.

**Comment by dianasaur323** [comment]
Another customer recently asked for this. Perhaps something @awoods187 can triage.

**Comment by posener** [comment]
Tried to run Openstack Keystone on cockroachdb, it works fine, this missing feature fails a domain update command (a pretty common command I would say).
I think this implementation is necessary to make porting of existing applications to cockroachdb.

**Comment by petermattis** [comment]
@RaduBerinde, @knz `DISTINCT` on all columns is a equivalent to `GROUP BY` on those columns. Is `DISTINCT ON(columns)` equivalent to `GROUP BY` on the specified columns?  If yes, this seems even easier than I was imagining.

**Comment by RaduBerinde** [comment]
The semantics are a little strange. What exactly is "the first row"? A query has no ordering except what the order by indicates (which logically applies to the result of DISTINCT).

It could be a GROUP BY if we had a special aggregation function for the other columns:
`SELECT DISTINCT ON (a,b,c) a, b, c, FIRST_ROW(d), FIRST_ROW(e), FIRST_ROW(f) GROUP BY a,b,c`

**Comment by knz** [comment]
sorry "first row" doesn't presuppose an ordering. I think a more correct description is "any row".
The pg doc is pretty specific:

> Note that the “first row” of each set is unpredictable unless ORDER BY is used to ensure that the desired row appears first.

(https://www.postgresql.org/docs/10/static/sql-select.html)

**Comment by knz** [comment]
:+1: on the idea of a separate first_row aggregate. It'd be useful in testing too.

**Comment by RaduBerinde** [comment]
> Note that the “first row” of each set is unpredictable unless ORDER BY is used to ensure that the desired row appears first.


Ah, interesting. Our GROUP BY + ORDER BY doesn't work like that currently - we would need the ordering requirement to go through the groupNode. It would be the first instance of an aggregation function that is dependent on the ordering of the input rows.

**Comment by vivekmenezes** [comment]
assigning to richard if he can get to it before the end of his internship.

**Comment by posener** [comment]
Hi, is there any idea when is it going to be implemented?
Maybe I can provide some help in any way?
Cheers!

**Comment by richardwu** [comment]
Hey posener, 

I was planning to take a look at this sometime this week or next week, I'll try to provide an update as soon as I scope out the implementation.

**Comment by posener** [comment]
Thanks you so much!

**Comment by richardwu** [comment]
So I dug around the sorting code + aggregating and this doesn't seem too tricky to implement.

I plan on implementing this for the local execution engine first then get local-final aggregation working in the distributed execution engine (distsql).

Here's a very brief outline of what needs to be implemented for the final `DISTINCT ON` clause:
1. A `FirstRowAggregate` that implements `tree.AggregateFunc` in `aggregate_builtins` that bookkeeps the desired `sqlbase.ColumnOrdering` (from `ORDER BY` passed at the planning phase). If not specified, it would simply just bookkeep the first `tree.Datum` received. If ordering is specified, it would keep track of the most recent `Datum` that produces `< 0` when invoked with `sqlbase.CompareDatum` (initialized with the first `Datum`). Add this to the `Aggregates` map in `builtins/aggregate_builtins.go`.
2. Group by should work out of the box with `first_row` now. To make it more efficient if we have the desired ordering from an index we can update `groupNode.desiredAggregateOrdering` in `sql/group.go` with the addition of `FirstRowAggregate`.
3. Add the `DISTINCT ON` syntax to `sql.y` and `distinct_on_clause` as a third pattern under `simple_select_clause` (following the syntax of the other 2). This will produce a `tree.SelectClause` with a `GroupBy` on the columns inside the clause.
4. Add local-final distsql aggregation. Local and final aggregate functions are the same `FirstRowAggregate`.

I don't think this requires an RFC and seems pretty straightforward. Thoughts? @knz @RaduBerinde

**Comment by RaduBerinde** [comment]
This sounds good to me. Yeah, we don't need an RFC.

**Comment by knz** [comment]
Sounds good to me too.

**Comment by posener** [comment]
WOW, thank you so much!
