### ISSUE TITLE
kvserver: log iterator stats for lock table scan

### ISSUE THREAD

**Issue by arulajmani** [cockroachdb/cockroach#126309]
**Describe the problem**

Certain read-only requests scan split their evaluation into two parts -- scanning the lock table followed by scanning the MVCC keyspace. We log iterator stats for the latter, but not for the former; we should, in the [iterator](https://github.com/cockroachdb/cockroach/blob/7b9002e646f6e06aa597ec03d6aa4ba48a74a82c/pkg/storage/engine.go#L2080) created in `ScanConflictingIntentsForDroppingLatchesEarly`.

cc @nicktrav 

Jira issue: CRDB-39843

**Comment by lyang24** [comment]
Hi, by logging are you referring to this [recording function](https://github.com/lyang24/cockroach/blob/b8d259d04cc5e7fee7742be0d853befdb8327400/pkg/storage/mvcc.go#L1562-L1566)? or do we want to log the iter stats in a channel with high verbose level

**Comment by arulajmani** [comment]
> do we want to log the lock table iter stats in a channel with high verbose level

This was what I had in mind, so that it would show up in traces. @nicktrav already has a version of this locally though, so he beat you to it @lyang24!

**Comment by arulajmani** [comment]
I'll close this out as a duplicate of https://github.com/cockroachdb/cockroach/issues/126582.
