### ISSUE TITLE
 examples-orms: TestGORM/password flaked

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#126493]
See failure log here https://github.com/cockroachdb/cockroach/actions/runs/9742879278/job/26885099799

Jira issue: CRDB-39946

**Comment by rafiss** [comment]
It looks like we don't have artifacts from this test failure. I think we used to have this when this ran in TeamCity, but we may need something else for Github Actions runs of examples-orms. Let's make sure we capture artifacts, so we can investigate next time this happens.
