### ISSUE TITLE
storage: categorized write metrics are inflated

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/cockroach#126431]
In a multi-store configuration, the categorized write metrics can report inflated numbers.

For example, the following was pulled from a single node that has four stores:

<img width="791" alt="Screenshot 2024-06-28 at 2 13 09 PM" src="https://github.com/cockroachdb/cockroach/assets/804457/adda535e-ac62-4101-abce-35afaa395872">

Note also that the metrics per store are ~identical, which is sus.

Digging into the code, we have a single `DiskWriteStatsCollector` for all engines, and the collector doesn't internally separate based on store.

[More context (internal)](https://cockroachlabs.slack.com/archives/CAC6K3SLU/p1719609559087359).

Jira issue: CRDB-39906

**Comment by aadityasondhi** [comment]
Relevant [internal conversation](https://cockroachlabs.slack.com/archives/CAC6K3SLU/p1719609559087359)

**Comment by aadityasondhi** [comment]
The commit that introduced this bug is not present in v24.1, but is in v24.2.

Commit: 91f53eae420edbb40cddfd2559bcb4406f7a4c93

```
> git tag --contains 91f53eae420edbb40cddfd2559bcb4406f7a4c93 | grep v24.1
custombuild-v24.1.0-alpha.5-1783-g6cde73f5565

> git tag --contains 91f53eae420edbb40cddfd2559bcb4406f7a4c93 | grep v24.2
v24.2.0-alpha.1
v24.2.0-alpha.2
```
