### ISSUE TITLE
parsing base64 encoded Google Cloud credentials containing + error

### ISSUE THREAD

**Issue by zhangyangyu** [cockroachdb/cockroach#126552]
**Describe the problem**

If the base64 encoded Google credentials containing `+`, specifying it in URI will lead to error.

**To Reproduce**

```
nn=> backup database nn into 'gs://sdf/sddfd?AUTH=specified&CREDENTIALS=c2Zzamp3ZS48fHNoZnU+c2RqaHMK';
ERROR:  error getting credentials from CREDENTIALS: illegal base64 data at input byte 19
```

**Reason**

Seems cockroach use base64 standard encoding and get the encoded string from `url.Query()`. It unescapes the query string and make `+` becomes ` `.

Jira issue: CRDB-39975

**Comment by alicia-l2** [comment]
Thanks for filing this -- we'll look into it.

**Comment by alicia-l2** [comment]
Hey @zhangyangyu, unfortunately this is part of the expected behavior with getting the encoded string and unencoding. I'm going to close this issue out -- please open a new issue if you have any other problems!

**Comment by benbardin** [comment]
Hi Zhang! This is expected behavior. You'll want to URL-encode the parameters before passing them in.

**Comment by zhangyangyu** [comment]
@benbardin I know and I agree. The problem is the sample you give on doc site https://www.cockroachlabs.com/docs/v24.1/cloud-storage-authentication?filters=gcs#google-cloud-storage-specified The command `base64` never does URL-encode.
