### ISSUE TITLE
acceptance: TestNodeRestart causes test logs to become polluted by RPC errors

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#12671]
Most acceptance test logs drown under a flurry of the following:
```
vendor/google.golang.org/grpc/clientconn.go:698  grpc: addrConn.resetTransport failed to create client transport: 
connection error: desc = "transport: dial tcp 127.0.0.1:33033: getsockopt: connection refused"; 
Reconnecting to {127.0.0.1:33033 <nil>}
```

Usually (but not always) the tests can succeed despite this.

It's fairly easy to reproduce locally. Preliminary investigation suggests this is the docker client library getting confused when a test cluster ran inside docker is killed by a test. I may be wrong.

**Comment by knz** [comment]
Note: The flurry of error messages only starts after one of the tests has run -- if I run only a single acceptance test the error would never happen. I haven't been able to determine exactly at which test it starts.

**Comment by knz** [comment]
Note: the offending test is TestNodeRestart.
I've moved it to the end of the acceptance run ( 2d49cf68a6ee92807b9f85f500fcaa9e92c175a2 ) to avoid polluting the other tests. To investigate this issue, rename `zchaos_test.go` to `chaos_test.go`.

**Comment by knz** [comment]
cc @vivekmenezes

**Comment by bdarnell** [comment]
Closing since it's clear no one cares enough to look into this.
