### ISSUE TITLE
multitenant: shared-process tenant auto upgrades even if `preserve_downgrade_option` was set prior to restart

### ISSUE THREAD

**Issue by renatolabs** [cockroachdb/cockroach#126754]
Starting from 24.1+, shared-process tenants will auto-upgrade even if the operator set the `cluster.preserve_downgrade_option` prior to restarting the nodes.

### Reproduction

```console
$ roachprod create local -n1
$ roachprod stage local release v23.2.6 # bootstrap on 23.2
$ roachprod start local
$ roachprod start-sql main --storage-cluster local # create shared-process tenant
$ roachprod sql local:1 --cluster main -- -e "SET CLUSTER SETTING cluster.preserve_downgrade_option = '23.2';"
$ roachprod sql local:1 --cluster main -- -e "SHOW CLUSTER SETTING cluster.preserve_downgrade_option;"
  cluster.preserve_downgrade_option
-------------------------------------
  23.2
(1 row)

$ roachprod deploy local release v24.1.1 # rolling restart to 24.1
$ sleep 30 # wait for a while
$ roachprod sql local:1 --cluster main -- -e "SHOW CLUSTER SETTING version;"
  version
-----------
  24.1
(1 row)

$ roachprod sql local:1 --cluster main -- -e "SHOW CLUSTER SETTING cluster.preserve_downgrade_option;"
  cluster.preserve_downgrade_option
-------------------------------------

(1 row)
```

As we can see, the tenant correctly knew that the `cluster.preserve_downgrade_option` setting was set to `23.2` before the restart. Shortly after the restart, however, we see that the tenant's cluster version is already `24.1` and the `cluster.preserve_downgrade_option` is gone.

This issue **only happens for shared-process tenants**; separate-process deployments work as expected.

### Investigation

As for the cause of this issue, the problem is that the tenant learns about the `cluster.preserve_downgrade_option` _before_ it learns about the cluster version. The tenant's cluster version is initialized at `23.1` (according to `24.1`'s `MinSupported` constant), and therefore, the `preserve_downgrade_option` setting is refused:

> ```W240704 18:03:31.242481 1501 server/settingswatcher/settings_watcher.go:485 ⋮ [T2,Vmain,n1,rangefeed=‹settings-watcher›] 173  failed to set setting cluster.preserve_downgrade_option to ‹23.2›: cannot set cluster.preserve_downgrade_option to ‹23.2› (cluster version is 23.1)```

Shortly after, the tenant gets an accurate view of the cluster version:

> ```I240704 18:03:31.242505 1501 server/settingswatcher/settings_watcher.go:473 ⋮ [T2,Vmain,n1,rangefeed=‹settings-watcher›] 175  set cluster version from 23.1 to: 23.2```

#### Aside

This issue does not happen for separate process deployments because, in #121952, we introduced a `makeClusterSettings` function that sets `MinSupported` to the immediate predecessor (23.2 in this case) unless an internal environment variable is set. This function is used by both the system tenant and separate process tenants, but shared-process tenants use a different code path to create initial cluster settings.

### Resolution

We can (and should) update shared-process initialization to reuse (or otherwise replicate) the logic in the `makeClusterSettings` function referenced above and that would fix this issue for now.

However, we will face this problem again when `MinSupported != PreviousRelease` (i.e., when we officially support version-skip upgrades). The `version` setting will be initialized to `MinSupported` and could cause the `preserve_downgrade_option` to be refused again. This would impact both shared and external process tenants.

Jira issue: CRDB-40107

**Comment by renatolabs** [comment]
As usual for multitenant issues, pinging some folks directly: @stevendanna, @dt, @RaduBerinde.

> we will face this problem again when MinSupported != PreviousRelease

Let me know what your thoughts are specifically around avoiding this issue.

A naive approach after my first reading of the relevant code: we could keep a buffer of settings we get from the rangefeed until the initial scan is done. When that happens, we apply the `version` setting update, if any, before the others. Not the most elegant solution, so open to different approaches.

**Comment by dt** [comment]
I thought we deprecated the `preserve_downgrade_option` version number in favor of a simpler binary enabled/disabled option, that can be set to disabled regardless of the current version and which can be left disabled during manually initiated upgrades?

if so, maybe we just reject setting the deprecated one in tenants?

**Comment by stevendanna** [comment]
@renatolabs I might not be following but I wonder if we can remove this code completely:

https://github.com/cockroachdb/cockroach/blob/master/pkg/server/server_controller_new_server.go#L192-L204

and then rely on this code:

https://github.com/cockroachdb/cockroach/blob/master/pkg/server/server_sql.go#L1469-L1485

to initialise the cluster version from storage for us.  I had intended to remove the first bit of code in this release anyway but then I held off because it produces a non-trivial section of code where we don't yet have access to an initialised version.  But...it kinda seems better than having the version initialised to a bogus version.

**Comment by renatolabs** [comment]
> because it produces a non-trivial section of code where we don't yet have access to an initialised version

What is the non-trivial section of code?

Seems like we had this exact same conversation (but for separate process MT) back in #100684 and then the same logic was subsequently deleted in #104859.

As as experiment, I tried just deleting the clusterversion initialization on the shared-process path, and ran the script in the _Reproduction_ session of this issue; the issue no longer happens and the tenant starts fine.

Is there something that's silently broken if we just remove that code?

**Comment by stevendanna** [comment]
> Is there something that's silently broken if we just remove that code?

Not that I know of. When I wrote that comment I was worried about anyone adding code before sqlServer.preStart that relies on the version.  I suppose, however, that such code would be broken right now anyway since right now it is using the _wrong_ version. At least with an uninitialised version it would explode loudly.

**Comment by RaduBerinde** [comment]
We should perform validation of the setting only when we do `SET CLUSTER SETTING`. We shouldn't do any checking when we update the local in-memory copy. I think that would address the issue no?
