### ISSUE TITLE
core: debug page to highlight current issues

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#12679]
We should try to detect/display potential issues with individual nodes in a single place. This would be a simple crappy-html debug page for now but may be ported to the admin UI proper if useful and cleaned up.

* report simple (already known) issues. eg:
  * very long-running RPCs (eg: longest-running per rpc family if > X seconds), link to rpcz
  * problematic ranges (unavailable, range-leader-not-leaseholder), with link to debug pages (see #10736)
* basic stats that may indicate problems (some are currently prometheus alerts, but deserve to be surfaced to the admin UI):
  * basic problematic metrics (store almost full, zero qps)
* active tests (on demand-only?)
  * able to reach other nodes

**Comment by dianasaur323** [comment]
Does this still belong in 1.0? I think we can move it out, but feel free to move back in if you disagree.

**Comment by mberhault** [comment]
This can probably be closed in favor of @BramGruneir's work on debug pages.

**Comment by BramGruneir** [comment]
I'm going to work on an on demand active networking test in 1.2.
We already have a problem ranges page.
But we don't have any insight into long running RPCs yet. 

That being said, I think this can safely be closed.
