### ISSUE TITLE
ERROR: verify-idx-count: incompatible value type: cannot determine type of empty array

### ISSUE THREAD

**Issue by chenglinLiang** [cockroachdb/cockroach#126738]
**Describe the problem**

I encountered an error when creating an index on a table. However, when I used an equivalent SQL to create the table and the index, there was no error.

**To Reproduce**
**Error**
``` sql
CREATE TABLE t0 (
    c0 TIME CHECK (
        (
            ARRAY[B'1']
        ) NOT BETWEEN SYMMETRIC (
            CASE  
                WHEN false THEN ARRAY[] 
                ELSE ARRAY[] 
            END
        ) AND (
            ARRAY[B'1']
        )
    )
);
CREATE INDEX ON t0(c0);
```
```
ERROR: verify-idx-count: incompatible value type: cannot determine type of empty array. Consider casting to the desired type, for example ARRAY[]::int[]
SQLSTATE: 42P18
```
**Correct**
``` sql
CREATE TABLE t0 (
    c0 TIME CHECK (
        (
            ARRAY[B'1']
        ) NOT BETWEEN SYMMETRIC (
            ARRAY[] 
        ) AND (
            ARRAY[B'1']
        )
    )
);
CREATE INDEX ON t0(c0);
```

**Expected behavior**
No error.

**Environment:**
 - CockroachDB version [v24.1.0-alpha.5([40cc14f](https://github.com/cockroachdb/cockroach/commit/40cc14f35ef73ab5aed081329e2592301bc2254c))]
 - Server OS: [Ubuntu 20.04.6]
 - Client app [`cockroach sql`]

Jira issue: CRDB-40095

**Comment by yuzefovich** [comment]
Thanks for the report! I think this is a dup of #114316 and should be fixed on latest versions.
