### ISSUE TITLE
Cockroachdb Suddenly broken

### ISSUE THREAD

**Issue by cody151** [cockroachdb/cockroach#126804]
Hi There,

I created a 6 node cluster with a master node and then 5 worker nodes, the issue is that suddenly cockroachdb has sopped working all of a sudden, I restarted the VM and tried disabling the firewall yet despite starting the cockroach instance on the master with 

```
cockroach start --background --certs-dir=certs --advertise-host=172.16.11.11 --join=172.16.11.12,172.16.11.13,172.16.11.14,172.16.11.15,172.16.11.16 --background
```

it for some reason continues to error out when I try to join it

```
root@zen-db-master:~# cockroach sql --certs-dir=/root/certs --host=172.16.11.11 --database=defaultdb
#
# Welcome to the CockroachDB SQL shell.
# All statements must be terminated by a semicolon.
# To exit, type: \q.
#
ERROR: cannot dial server.
Is the server running?
If the server is running, check --host client-side and --advertise server-side.

failed to connect to `host=172.16.11.11 user=root database=movie_db`: tls error (read tcp 172.16.11.11:51298->172.16.11.11:26257: i/o timeout)
Failed running "sql"
```

Note that it has been working fine for the past few days as I have successfully visited the web page to view overview and inserted data into my database, this was fine even after restarting no problem but all of a sudden it refuses to connect with an "i/o timeout" error, but this does not really make sense since no updates were even run on the system to even cause ti to break?

Jira issue: CRDB-40141

**Comment by yuzefovich** [comment]
@cody151 are you still affected by this?

**Comment by yuzefovich** [comment]
I'm assuming the problem has been resolved.
