### ISSUE TITLE
feature request: better way of escalating unexpected situations in test environments

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#12680]
Sometimes there are situations in the system that we are capable of recovering from (and would like to in real user clusters) but that we don't ever expect to happen, and thus would like to be made aware of them when they do happen (especially in our test clusters). Plain old log messages often aren't noticed because they're only read when something has stopped working, so we need something more visible.

Debug-only assertions that are enabled by an environment variable, like e.g. `log.DFatal` could serve this purpose for test clusters, but wouldn't help surface such conditions in production environments. Also possible is a metric for such unexpected situations that can have an alert set up on it if its value is ever non-zero.

See this discussion on #12598 for additional context: https://reviewable.io/reviews/cockroachdb/cockroach/12598#-K_BztukC4vg1Palloht:-K_f-m_AJIeRF2xkQDki:b-gzgd51

**Comment by petermattis** [comment]
@dt Does Sentry support something like this?

**Comment by dt** [comment]
Yeah, we can send arbitrary messages to sentry (they even have an API for collecting user submitted feedback forms), though wrapping them as errors is always nice to get stack traces (which is how sentry prefers to group things).

Maybe we want a`log.Reportf(msg, args ...interface{})` ?

**Comment by dt** [comment]
@solongordon added a helper like this that is a failure in testing but only sentry event in production builds
