### ISSUE TITLE
build: Better support for RHEL/CentOS

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#12694]
RHEL and CentOS are slow-moving distributions which are popular in enterprise use (and they're used by conservative organizations that are often several major versions behind the current release). It's currently difficult to get CockroachDB running there. Our binaries don't work there because they're built for a newer glibc version, building from source requires a lot of yak shaving to update compilers, and docker is not available out of the box (in addition to the other complexities that docker introduces).

We should provide a better experience for RHEL users. I think the most practical way to do so is to make our binaries work on older versions of glibc (these binaries will work fine with newer versions of glibc). We could either install an older glibc into our builder image and link against it (I'm not sure how exactly to do that) or base our builder image on an older CentOS image (this would require us to do the work to get an updated compiler onto CentOS, but that's better than handing that work to all of our potential RHEL/CentOS users). FWIW, the python community takes the latter approach, and publishes docker images (called [`manylinux`](https://github.com/pypa/manylinux)) with a CentOS 5-based development environment which produces binaries that run on a wide variety of linux distributions. 

Or we could revive the fully-static MUSL-based builds, which would also work on Alpine and other non-glibc distributions. I don't know how likely it is that RHEL/CentOS users are relying on glibc-specific name resolution features.

**Comment by petermattis** [comment]
Building binaries for older versions of glibc seems like a perfect use for docker. 

Were there other downsides to the MUSL builds other than the name resolution differences?

Cc @tamird

**Comment by tamird** [comment]
docker+old glibc seems like the safer option to me.

I don't recall other issues with musl.

I'll take a stab at basing our builder image on centos 5, and separately at resurrecting the musl build. Seems like a good idea to have musl binaries ready for when we decide to test them again (or our users do).

**Comment by bdarnell** [comment]
MUSL publishes a list of differences with glibc: http://wiki.musl-libc.org/wiki/Functional_differences_from_glibc

The name resolution issue is the only thing that is clearly relevant to us. Compatibility in this area was improved in musl 1.1.13. I think this might have fixed the issue we were seeing before with the musl builds, although I don't know if there are any remaining issues.

**Comment by bdarnell** [comment]
Another data point: Rust has recently [revamped their build images](https://github.com/rust-lang/rust/pull/39198/files) to start with centos 5 and build compilers and other dependencies from source.

I also looked briefly at what it would take to build an older version of glibc on a newer system (we couldn't install that build into `/lib`, but I think we could get around that with compiler flags, or in the worst case a chroot). This turns out to be much tricker than it looks because glibc's configure script specifies both a minimum and a maximum version of compilers and other tools. So to build an old version of glibc, you'd also need to build an old version of gcc and even `make` (or bypass those checks in `./configure`). Whether you start with a new base and work your way back to an old libc or start with an old base and work your way forward to new compilers, you have to build a bunch of stuff by hand.

And the glibc bug I mention in https://github.com/cockroachdb/cockroach/issues/13005#issuecomment-275011287 has made me wonder whether supporting old glibc versions is even the right approach. [That bug](https://sourceware.org/bugzilla/show_bug.cgi?id=15946) (which was escalated from golang/go#6336) means that go programs cannot run reliably on glibc versions prior to 2.20. Since this is a security-relevant bug all major distros have patched the fix into their glibc package even if they still have a lower version number, but anyone using an unpatched version of a 2014-vintage distro will experience obscure failures (possibly including corruption similar to #13005). And there might be other bugs that didn't reach the severity threshold to get patched into LTS distros but are still problematic for us. Shipping musl binaries instead of glibc would insulate us from users' potentially-ancient glibc versions (On the other hand, it would put us on the hook for shipping new binaries whenever musl has a critical security issue. But we already have that obligation for every library we use *except* libc)

**Comment by tamird** [comment]
Woops, this should have been closed by #13102.
