### ISSUE TITLE
Do we need a separate Contains operation?

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#1269]
`client.DB` does not utilize the `Contains` op. Should it? You can mostly use `Get` as a substitute, but its less efficient due to retrieving the value. Perhaps this will become moot once tabular support comes along and you can specify which columns to retrieve. In the meantime, should we dump `Contains`?

**Comment by bdarnell** [comment]
I would just get rid of Contains(). If we find that the optimization would be significant I'd add an option to GetRequest instead. (we may expose this to clients as DB.Contains, but there's no reason to make a distinct rpc entry point for it)

**Comment by spencerkimball** [comment]
Makes sense.

**Comment by petermattis** [comment]
I'll whip up a PR to remove `Contains`.
