### ISSUE TITLE
server: --join with insecure node may lead to undiscoverable failure

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#12707]
So I think this is the scenario that brought up a question by @amosbird on Gitter today:

1. user starts insecure node on machine A with `cockroach start --insecure`
2. user starts insecure node on machine B with `cockroach start --join=A`

Now because `--insecure` is not specified on B, the process will not start listening on its public IP address. So it may be able to establish an outgoing connection to A, but if A tries to connect back to B, that will fail.

Is it possible that this would explain why the server deadlocks on startup?

**Comment by knz** [comment]
@tamird do you know how the TCP session handshake works with grpc? (Who connects to whom?)

**Comment by tamird** [comment]
Not sure what you mean. grpc is essentially http/2, so...machine B will first connect to machine A, but it is likely that connections in both directions will eventually exist due to raft traffic.

**Comment by knz** [comment]
ah so the scenario above could indeed lead to an issue where B can connect to A but the rest of the cluster can't connect back to B.

**Comment by a-robinson** [comment]
Yeah, this is some bad UX. Other nodes won't be able to initialize connections to B because it'll be advertising its localhost address. This is made even worse by the fact that SIGTERM currently gets ignored during node startup (#10138).

**Comment by knz** [comment]
The solution, it seems to me, is to default to listening on all interfaces if `--join` is specified to a non-localhost address. (ideally we'd listen only on the interface sufficient to join, but let's assume the user knows what they are doing if they pass `--join` explicitly).

**Comment by bdarnell** [comment]
Instead of defaulting to "all interfaces, insecurely" when `--join` is present, it might be better to make it an error to specify a non-localhost `--join` argument without either `--insecure` or certs and keys.

**Comment by dianasaur323** [comment]
assigning @tamird. Feel free to re-assign as appropriate. It seems to me that this is a relatively quick fix that can fit into our 1.0, but if not, let's move it out into a quarterly milestone (perhaps Q2 or Q3).

**Comment by mberhault** [comment]
as of #14703, `--host` defaults to all interfaces and is not influenced by `--insecure`.
This means that to accomplish the same problem as listed above, one would have to specify `--host=localhost`. Is this sufficient to consider this solved?

**Comment by bdarnell** [comment]
Yes, I think this is solved now.
