### ISSUE TITLE
roachtest: add tpc-e to roachperf

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#127035]
We run [TPC-E](https://github.com/cockroachlabs/tpc-e) nightly, but don't currently track its performance in roachperf. We should so that we can track performance over time and catch performance regressions.

Jira issue: CRDB-40248

**Comment by DarrylWong** [comment]
What metrics do we care about here?

For reference, this is what the tests currently spit out for performance:

<img width="1132" alt="image" src="https://github.com/user-attachments/assets/693a2d37-017f-445f-85a5-fed1cb6e884a">

Maybe just txn/s? But even then that seems like it would be way too much info for roachperf unless we want to aggregate it.

**Comment by srosenberg** [comment]
Let's go with throughput and latency of `TradeResult` [1],

> 6.6.8.4 The Measured Throughput is computed as the total number of Valid Trade-Result Transactions
within the Measurement Interval divided by the duration of the Measurement Interval in seconds.

[1] https://www.tpc.org/tpc_documents_current_versions/pdf/tpc-e_v1.14.0.pdf

**Comment by nvanbenschoten** [comment]
TPC-E is an open-loop workload with a fixed rate of transactions, so throughput should be stable unless (average) latency tanks. Maybe we plot different percentiles of `TradeResult` latency?
