### ISSUE TITLE
sql: postgres supports aggregate expressions in a subquery referring to the outer query

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#12703]
from section 4.2.8 of https://www.postgresql.org/docs/9.4/static/sql-expressions.html:
"""
When an aggregate expression appears in a subquery (see Section 4.2.11 and Section 9.22), the aggregate is normally evaluated over the rows of the subquery. But an exception occurs if the aggregate's arguments (and filter_clause if any) contain only outer-level variables: the aggregate then belongs to the nearest such outer level, and is evaluated over the rows of that query. The aggregate expression as a whole is then an outer reference for the subquery it appears in, and acts as a constant over any one evaluation of that subquery. The restriction about appearing only in the result list or HAVING clause applies with respect to the query level that the aggregate belongs to.
"""

Haven't thought too much about what this means, but we don't support it.

cc @knz

**Comment by knz** [comment]
Oh that's interesting! 
If/when we support correlated subqueries, if we do it in the way I have in mind, we can support this too without "too much" hassle I believe. Thanks for noticing.

**Comment by andy-kimball** [comment]
Rebecca, I believe this is the issue you're working on. Can you set your PR to close this down once it merges?

**Comment by rytaft** [comment]
Yep! This is exactly the issue I'm fixing.
