### ISSUE TITLE
sql: investigate moving sum_int to pg_catalog and overloading sum to return int

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#12701]
From the discussion on
https://github.com/cockroachdb/docs/pull/958#discussion_r94760530
https://github.com/cockroachdb/docs/pull/958#discussion_r94778573

Issue suggested by @nvanbenschoten:

> To be concrete, the idea @knz is proposing here is to add another sum overload with the signature sum(int)->int (in addition to sum(int)->decimal) that aggregates in an int64. While overloads with the same argument types but different return types does not make sense in typical languages where overloads are uniquely determined from their arguments, our use of demand-driven overload resolution means that this new overload could be useful in cases where an int return type is desired (ie. `sum():::int`). To avoid ambiguity in the non-demanded case, we would use our "preferred overload" mechanism to prefer the standard sum(int)->decimal implementation.

> While this approach would work in practice, it would be a deviation from our previous convention of uniquely identifying overloads by their argument types. As such, it deserves discussion. @knz do you mind opening an issue to discuss the idea? We might also want to hold off on the inclusion of this new function in the release notes until this question is resolved.

Also even if we keep offering `sum_int` for compatibility with pg we could put it in namespace `pg_catalog` since we now support that.

**Comment by nvanbenschoten** [comment]
`sum_int` is a custom CockroachDB aggregate introduced in #12512. It was not included for compatibility purposes, and Postgres does not have a builtin function with that name. This means that if we determine that this new overload fully supersedes `sum_int`, we could consider removing it.
