### ISSUE TITLE
ui: when you scroll right the dropdowns overlap the left nav

### ISSUE THREAD

**Issue by maxlang** [cockroachdb/cockroach#12717]
When the page is smaller than 1300px you can scroll to the right and then the z-indexes of the top bar, sidebar and dropdown selector conflict.

<img width="357" alt="screen shot 2017-01-05 at 3 24 31 pm" src="https://cloud.githubusercontent.com/assets/3691886/21696271/3fae9f74-d35b-11e6-803e-98fa98650374.png">

cc @kuanluo

**Comment by dianasaur323** [comment]
Looks like this is still an issue. 
![image](https://cloud.githubusercontent.com/assets/5768024/24875610/a95ad8ee-1df6-11e7-8426-b729210e66cc.png)

@kuanluo who is implementing these UI changes at this point?

**Comment by kuanluo** [comment]
@mrtracy is your man.
