### ISSUE TITLE
sql: UNION/EXCEPT/INTERCEPT should propagate demanded types from left to right 

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#12716]
```sql
CREATE TABLE IF NOT EXISTS user_edge (
    PRIMARY KEY (source_id, state, position),
    source_id      BYTES    NOT NULL,
    position       BIGINT   NOT NULL, -- Used for sort order on rows
    updated_at     INT      CHECK (updated_at > 0) NOT NULL,
    destination_id BYTES    NOT NULL,
    state          SMALLINT NOT NULL, -- Active(0), Deleted(1), Archived(2)

    UNIQUE INDEX source_id_destination_id_idx (source_id, destination_id)
);
```

```sql
SELECT * FROM(
	SELECT id
	FROM users
	EXCEPT SELECT $1
	EXCEPT SELECT destination_id FROM user_edge WHERE source_id = $1
) t ORDER BY RANDOM() LIMIT 1
```

expected result: success, actual result: `pq: could not determine data type of placeholder $1`

`s/$1/$1:::BYTES/` is a usable workaround.

**Comment by tamird** [comment]
Hm, maybe this isn't a bug - reversing the order of the two EXCEPT clauses fixes the problem as well.

**Comment by tamird** [comment]
Postgres correctly infers this type.

**Comment by knz** [comment]
Yes we can/should do this (propagate the column types of the left operand as demanded types on the right) but it's not yet currently easy since this is type checking for statements not expressions and we don't yet have infrastructure for that. One more item on the IR benefits.

**Comment by knz** [comment]
Note: this issue is not forgotten but should be more readily addressable once we have a unified IR and type checker for expressions and statements.

**Comment by knz** [comment]
Note: when testing this also take the examples from  #21869.

**Comment by jordanlewis** [comment]
This is fixed.
