### ISSUE TITLE
Not gossiping system tables at startup

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#12721]
The setup:
Take a long running cluster of 5 nodes.
Shut down the whole cluster, only bring up 4 of the nodes.

The cluster will not be able to recover as any leases held by the missing node will not be able to expire their leases.  Every attempt to get the lease for any range who's lease was held by that node will return a ErrNoLivenessRecord.

This is due to the fact that there is no liveliness record for that node, so all leases are left in an errored limbo state, presumably waiting for a slow gossip update. 

This seems to be caused by the system tables never getting gossiped, as their leases can't be acquired.
`W170105 17:56:37.058363 116 storage/store.go:1307  [n1,s1] error gossiping system config: range 1: replica {1 1 1} not lease holder; lease holder unknown`

Since the system tables are never gossiped, the node liveliness table never receives info about this failed node, which causes a cascade of issues.

I'm digging further into this and will update this issue accordingly.

**Comment by BramGruneir** [comment]
So I've dug deeper into this.

I'm quite certain that the lack of gossiping is due to the ip address of the test cluster being changed when I moved it from GCE to Az.  So the system configs cannot be gossiped, which in turn means that the node liveliness table is not being updated correctly.  All the working nodes appear in the table, but the missing node never shows up.  While the data on this missing node are stored in the cluster, they never make it to any of the nodes.

So there are three things that need to happen to fix this issue.

1) When the node liveliness table has no info about a node, it should treat this as a cache miss and read from the cluster directly.

2) Spend more time and add tests to ensure that a cluster that is stop and restarted with new ip addresses or different ports works correctly.  Maybe consider leaving out a node as well.

3) When there are problems gossiping during startup, specifically when the system tables cant be gossiped for 5 mins, bubble up the issue to the user, perhaps in the UI, or outright panic.

**Comment by petermattis** [comment]
> I'm quite certain that the lack of gossiping is due to the ip address of the test cluster being changed when I moved it from GCE to Az. So the system configs cannot be gossiped

How does the IP address of the test cluster changing prevent the system config from being gossiped?

**Comment by BramGruneir** [comment]
I keep getting the following errors:
```E170107 22:07:01.293555 13551 server/admin.go:765  failed to send RPC: sending to all 2 replicas failed; last error: [NotLeaseHolderError] range 5: replica {2 2 2} not lease holder; lease holder unknown```

For all the system ranges and a bunch of other ranges as well.

**Comment by petermattis** [comment]
Right, but how did changing IP addresses cause that?

**Comment by BramGruneir** [comment]
I think there's a problem in updateNodeAddress.  But I haven't debugged that far yet.

**Comment by BramGruneir** [comment]
And I think the lack of starting up one of the nodes is making the problem worse.

**Comment by petermattis** [comment]
> I think there's a problem in updateNodeAddress. But I haven't debugged that far yet.

Ok. Let's get to the bottom of this. I was getting mildly anxious about the proposed fixes without understanding what the underlying problem is.

**Comment by BramGruneir** [comment]
Of course.  But I think adding the cache miss lookup to the liveness table is a good idea regardless.  It removes any ambiguity during startup where there might be a delay.

**Comment by tamird** [comment]
Should this have been closed by #12721?

**Comment by a-robinson** [comment]
Yeah. There's still the potential todos that @BramGruneir mentioned above (particularly "When the node liveliness table has no info about a node, it should treat this as a cache miss and read from the cluster directly."), but #12798 fixed this.

**Comment by BramGruneir** [comment]
I'm not sure if that's needed.  @spencerkimball, what do you think?

**Comment by spencerkimball** [comment]
I don't believe we should start reading directly from the node liveness table. If gossip isn't working, the system isn't working for other reasons. Let's not pile on by having all nodes directly reading node liveness.
