### ISSUE TITLE
feature request: backup all state with Chandy-Lamport snapshot

### ISSUE THREAD

**Issue by glycerine** [cockroachdb/cockroach#12732]
For production use, one typically wants a backup that is a consistent snapshot of all tables/all data at a noted point in time.

The current docs indicate that there is only facility to backup one table at a time, and no facility for getting a consistent backup of all tables/the entire database.

Please consider implementing Chandy-Lamport snapshots for complete and consistent cockroachdb backups.

**Comment by dt** [comment]
For SQL dumps, dumping multiple tables at the same logical time is tracked in https://github.com/cockroachdb/cockroach/issues/8881

In addition to that, we're working on a more optimized, cockroach-specific backup/restore format and functionality which also backs up multiple tables / dbs as of a given time (as well as incrementally, etc) though that stuff isn't quite ready yet.

**Comment by dianasaur323** [comment]
Closing - we support this now.
