### ISSUE TITLE
Update the `changefeed.sink_io_workers` cluster setting description for sinks

### ISSUE THREAD

**Issue by katmayb** [cockroachdb/cockroach#127362]
Currently, the `changefeed.sink_io_workers` description on [cluster settings page](https://www.cockroachlabs.com/docs/dev/cluster-settings#setting-changefeed-sink-io-workers) mentions this setting only affects webhook sinks:

> the number of workers used by changefeeds when sending requests to the sink (currently webhook only): <0 disables, 0 assigns a reasonable default, >0 assigns the setting value

This description pulls from the eng/`cockroach` repo. We should update to add Pub/Sub and (possibly) v2 Kafka.

@asg0451 pointed out this discrepancy while [reviewing PR for a docs update](https://github.com/cockroachdb/docs/pull/18733/files) that included this cluster setting.

Jira issue: CRDB-40414

Epic CRDB-41784

**Comment by rharding6373** [comment]
Also need to apply this to kafka v2 sink
