### ISSUE TITLE
slinstance: make sql session initialization immune to AmbiguousResult errors

### ISSUE THREAD

**Issue by rimadeodhar** [cockroachdb/cockroach#127301]
**Describe the problem**
[
SQL Session initialization](https://github.com/cockroachdb/cockroach/blob/7bf9cccc270f97138e10bb31af1cd91c3febefa5/pkg/sql/sqlliveness/slinstance/slinstance.go#L217) uses conditional puts (CPut) to record a SQL session within the `sqlliveness` table during session initialization. However, if the CPut fails with an `AmbiguousResult` error (error indicating that the KV layer is unsure whether the txn committed successfully or not), subsequent retries continue to fail as the timestamp value is refreshed during each retry. So if the first insert had indeed succeeded, later calls to CPut fail as we are now attempting to insert a new value (updated timestamp) with the same key (session ID) into the `sqlliveness` table. The change to refresh the session expiry value during retries was done here https://github.com/cockroachdb/cockroach/pull/122202. I think the original motivation behind this PR still stands and so we should try to figure out how we can make sql session initialization immune to `AmbiguousResult` errors.

Outlining a couple of options:
1. We can use unconditional put for session initialization. However, we are not sure how safe this operation would be.
2. We can avoid refreshing the timestamp during retry and have a separate check to ensure we don't inject expired sessions into the table. We should make sure we don't regress on the work in https://github.com/cockroachdb/cockroach/pull/120006.
3. Perhaps, we could check if the value already exists before attempting a retry in case of an `AmbiguousResult` error from the KV layer.

See https://github.com/cockroachlabs/support/issues/3017 for more details.

Jira issue: CRDB-40364

Epic CRDB-40419

**Comment by VishalJaishankar** [comment]
Hi! SRE saw the same issue today. Related ticket https://cockroachlabs.atlassian.net/browse/CLOUDOPS-10373 and the error message https://cockroachlabs.atlassian.net/browse/CLOUDOPS-10373?focusedCommentId=239180

**Comment by sudomateo** [comment]
@rimadeodhar will this fix be included in some v23.X version?
