### ISSUE TITLE
stability: performance problems when adding a lot of nodes at once

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#12741]
When running @mberhault's scalability test that doubles the size of the cluster every half hour while running a block writer on each member node, it becomes clear that adding a lot of nodes to the cluster at once can cause some problems (particularly the jump from 32 to 64 nodes). This isn't urgently critical, since adding 32 nodes to an existing 32 node cluster within a matter of seconds isn't a top use case right now, but it is a little concerning.

A bunch of node liveness epochs got incremented, indicating that nodes weren't able to properly heartbeat their liveness entries (which can lead to other problems):

<img width="1357" alt="screen shot 2017-01-06 at 12 15 59 pm" src="https://cloud.githubusercontent.com/assets/7085343/21726271/138988e6-d40a-11e6-9bdb-2e68cf2093e2.png">

Mutex critical sections slow down:

<img width="901" alt="screen shot 2017-01-06 at 12 16 33 pm" src="https://cloud.githubusercontent.com/assets/7085343/21726277/1663f1d2-d40a-11e6-81bf-b97026cb56e5.png">

<img width="907" alt="screen shot 2017-01-06 at 12 16 44 pm" src="https://cloud.githubusercontent.com/assets/7085343/21726283/1a23b03c-d40a-11e6-98ed-0ddfa12a50cb.png">

Queue failures jump up:

<img width="941" alt="screen shot 2017-01-06 at 12 18 03 pm" src="https://cloud.githubusercontent.com/assets/7085343/21726307/3576c234-d40a-11e6-9bb4-b363b55bb258.png">

Raft performance gets worse before it gets better:

<img width="904" alt="screen shot 2017-01-06 at 12 18 59 pm" src="https://cloud.githubusercontent.com/assets/7085343/21726340/609ad7ca-d40a-11e6-886c-5d30da0c4a93.png">

<img width="904" alt="screen shot 2017-01-06 at 12 19 14 pm" src="https://cloud.githubusercontent.com/assets/7085343/21726342/6449d894-d40a-11e6-9130-3214db45dfb6.png">

Along with user-visible performance and aborted transactions:

<img width="902" alt="screen shot 2017-01-06 at 12 20 36 pm" src="https://cloud.githubusercontent.com/assets/7085343/21726420/a13e43de-d40a-11e6-9ce3-ab85a684d11b.png">

<img width="905" alt="screen shot 2017-01-06 at 12 20 49 pm" src="https://cloud.githubusercontent.com/assets/7085343/21726424/a622ab38-d40a-11e6-8b57-33ca575696f9.png">

Most concerningly, a bunch of lease/distsender requests apparently got stuck (and seemingly never unstuck) when the number of nodes jumped up:

<img width="967" alt="screen shot 2017-01-06 at 12 20 02 pm" src="https://cloud.githubusercontent.com/assets/7085343/21726481/d90faf00-d40a-11e6-934a-b761d89e356e.png">

<img width="903" alt="screen shot 2017-01-06 at 12 20 21 pm" src="https://cloud.githubusercontent.com/assets/7085343/21726486/dd00dfa8-d40a-11e6-9c12-268663efe08a.png">

Metrics at https://monitoring.gce.cockroachdb.com/dashboard/db/cockroach-sql?from=1483630200000&to=1483641000000&var-cluster=sky&var-node=All&var-rate_interval=1m

I can upload the logs somewhere as well if anyone would like them.

**Comment by petermattis** [comment]
I've noticed in recent experiments that performance suffers when significant rebalance is taking place. For example, in a 10 node cluster if you take 1 node down for longer than 5m performance takes a hit when rebalancing away from the down node kicks in. There might be something similar going on in this case. If you add a single node to a cluster only 1 rebalance operation can take place at a time which is a fairly small drain on background resources. If you add 32 nodes then 32 concurrent rebalance operations can occur.

**Comment by dianasaur323** [comment]
assigning to @petermattis. it seems like the performance hit we take when 1 node goes down merits some exploration for 1.0, and that that fix might help with adding nodes too quickly?

**Comment by petermattis** [comment]
The performance hit is likely attenuated by #14718. Would be interesting to re-run the experiment above when that changes lands.

**Comment by a-robinson** [comment]
Alright, lots of pretty graphs to share. The tl;dr is that things worked well except when moving from 8 to 16 nodes, where performance was terrible for about 5 minutes (starting just before 18:20 in the graphs). It's not obvious from the graphs why that transition was worse than any of the others. It doesn't look particularly different from the others in terms of what background work was being done at the time.

The other two concerning things:
* Gossip thrashing in large clusters appears to have returned, and I'm not sure what gossip changes since we fixed it could have caused it to come back.
* Performance didn't really improve much as nodes were added, and actually got worse when we moved from 32 to 64 nodes. This might just be due to the workload, though -- the only load being generated is from a single photos instance on each node with `--users=10`.

I'm going to shut down the nodes in 30 minutes or so unless anyone needs them for anything. I'll save the logs beforehand.

<img width="1380" alt="screen shot 2017-04-24 at 4 16 56 pm" src="https://cloud.githubusercontent.com/assets/7085343/25357099/9951ce52-290a-11e7-9f9b-c1f0a949556b.png">
<img width="921" alt="screen shot 2017-04-24 at 4 14 39 pm" src="https://cloud.githubusercontent.com/assets/7085343/25357074/860abf48-290a-11e7-8d90-b6da678ed88f.png">
<img width="915" alt="screen shot 2017-04-24 at 4 15 18 pm" src="https://cloud.githubusercontent.com/assets/7085343/25357082/8cb240b4-290a-11e7-8de3-b4e3e40ebfc4.png">
<img width="922" alt="screen shot 2017-04-24 at 4 17 59 pm" src="https://cloud.githubusercontent.com/assets/7085343/25357105/9c5312dc-290a-11e7-82d6-f1b96a01926e.png">
<img width="917" alt="screen shot 2017-04-24 at 4 18 23 pm" src="https://cloud.githubusercontent.com/assets/7085343/25357107/9e560418-290a-11e7-9b27-7ca30ccfdc53.png">
<img width="917" alt="screen shot 2017-04-24 at 4 19 44 pm" src="https://cloud.githubusercontent.com/assets/7085343/25357112/a03f785e-290a-11e7-9c6f-3e320ee17ec1.png">
<img width="919" alt="screen shot 2017-04-24 at 4 19 48 pm" src="https://cloud.githubusercontent.com/assets/7085343/25357113/a2cd76ac-290a-11e7-8c4c-154c6b88a674.png">
<img width="923" alt="screen shot 2017-04-24 at 4 20 28 pm" src="https://cloud.githubusercontent.com/assets/7085343/25357116/a466a3d0-290a-11e7-91f3-93d159940501.png">
<img width="919" alt="screen shot 2017-04-24 at 4 16 00 pm" src="https://cloud.githubusercontent.com/assets/7085343/25357086/8f3df5d0-290a-11e7-8ada-5005655633af.png">
<img width="920" alt="screen shot 2017-04-24 at 4 16 10 pm" src="https://cloud.githubusercontent.com/assets/7085343/25357095/945a8f06-290a-11e7-8cbd-b94a1fdfc0da.png">
<img width="923" alt="screen shot 2017-04-24 at 4 16 23 pm" src="https://cloud.githubusercontent.com/assets/7085343/25357096/972f1d14-290a-11e7-97cd-26ed86c45eca.png">

**Comment by a-robinson** [comment]
I'm gonna wipe and try again with only block writer running, but I just noticed that the performance has jumped quite noticeably since the original screenshots:

<img width="920" alt="screen shot 2017-04-24 at 4 45 21 pm" src="https://cloud.githubusercontent.com/assets/7085343/25357929/b302a0d0-290d-11e7-9e56-63e28681ae04.png">

The most correlated event appears to be two node liveness epochs being incremented, which could have led to a better distribution of leases across the nodes. The leases were perfectly well balanced before the epoch increments, but perhaps all the hot ranges had their lease on just one or two nodes.

**Comment by a-robinson** [comment]
Things were less rocky when running with block writer while ramping up load. The worst thing that happened was a 25% dip in QPS when moving from 8 to 16 nodes, which is a bit worse than what we were seeing when the original issue was filed. That's obviously not great, but is significantly better than what happened for photos.

What is a bit more concerning is that the cluster was seemingly falling behind while running in its steady state at 64 nodes. Note the number of under-replicated ranges and replicas behind on their raft log. The cluster was still functioning, but not totally catching up.

<img width="1379" alt="screen shot 2017-04-24 at 8 05 06 pm" src="https://cloud.githubusercontent.com/assets/7085343/25364070/9bab9e26-292d-11e7-82bb-1807269da805.png">
<img width="1378" alt="screen shot 2017-04-24 at 8 04 17 pm" src="https://cloud.githubusercontent.com/assets/7085343/25364069/982d8070-292d-11e7-81be-1c0d72d65442.png">
<img width="918" alt="screen shot 2017-04-24 at 8 05 57 pm" src="https://cloud.githubusercontent.com/assets/7085343/25364075/9f624204-292d-11e7-9551-0b6c92d09a1b.png">
<img width="1377" alt="screen shot 2017-04-24 at 8 05 25 pm" src="https://cloud.githubusercontent.com/assets/7085343/25364072/9d921512-292d-11e7-91a2-404904103082.png">
<img width="919" alt="screen shot 2017-04-24 at 8 06 42 pm" src="https://cloud.githubusercontent.com/assets/7085343/25364078/a1d77d9c-292d-11e7-98b7-e1352d847968.png">
<img width="920" alt="screen shot 2017-04-24 at 8 07 05 pm" src="https://cloud.githubusercontent.com/assets/7085343/25364081/a49700c0-292d-11e7-9d22-d19f45ceb0da.png">
<img width="926" alt="screen shot 2017-04-24 at 8 07 17 pm" src="https://cloud.githubusercontent.com/assets/7085343/25364083/a69d07c0-292d-11e7-8634-eb5cee0b619c.png">
<img width="925" alt="screen shot 2017-04-24 at 8 07 48 pm" src="https://cloud.githubusercontent.com/assets/7085343/25364085/a85f95fa-292d-11e7-90aa-1c75854ae84d.png">
<img width="925" alt="screen shot 2017-04-24 at 8 08 00 pm" src="https://cloud.githubusercontent.com/assets/7085343/25364087/aa22b96c-292d-11e7-8273-1d817b9fd81f.png">

**Comment by a-robinson** [comment]
I don't think there's anything actionable here for 1.0. The short 25% dip when going from 8 to 16 nodes isn't ideal, but certainly isn't a release blocker and will fall under our ruggedization goals for 1.1. I've also reopened our old gossip thrashing issue (#9819) to track the reappearance of that problem.
