### ISSUE TITLE
build: glide is misbehaving

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#12757]
Running as per the docs `build/glide.sh get -s ...`

Result:
```
[WARN]  The --strip-vcs flag is deprecated. This now works by default.
[INFO]  Preparing to install 1 package.
[INFO]  Attempting to get package github.com/spf13/cobra
[INFO]  --> Gathering release information for github.com/spf13/cobra
[INFO]  --> Adding github.com/spf13/cobra to your configuration
[INFO]  Downloading dependencies. Please wait...
[INFO]  --> Fetching github.com/cockroachdb/c-jemalloc.
[INFO]  --> Fetching github.com/docker/docker.
[INFO]  --> Fetching github.com/coreos/etcd.
[INFO]  --> Fetching golang.org/x/net.
[INFO]  --> Fetching github.com/spf13/cobra.
[INFO]  --> Fetching google.golang.org/api.
[INFO]  --> Fetching cloud.google.com/go.
[INFO]  Resolving imports
[ERROR] Failed to build an initial list of packages to scan: lstat go/src/github.com/cockroachdb/cockroach: no such file or directory
[ERROR] Failed to resolve local packages: lstat go/src/github.com/cockroachdb/cockroach: no such file or directory
```

**Comment by knz** [comment]
What is this non-relative use of `go/src`? Why no use of `$GOPATH`?

**Comment by tamird** [comment]
Version of glide?

**Comment by knz** [comment]
glide version 0.13.0-dev

(fresh from `go get`)

**Comment by dt** [comment]
hm, unrelated, we should potentially discourage `glide get`, it will erase all of @tamird's hand-written comments from `glide.yaml` (due to not being parsed when the pre-get conf is read).

That said, unfortunately, this Works On My Machine™ so I can't do much digging. I'm pretty sure it _does_ use GOPATH. What is your `GOPATH`? are there symlinks in the ancestry of your cockroach checkout? anything else interesting?

**Comment by knz** [comment]
What's interesting:

- my PWD is `/user/kena/cockroach`
- `~/cockroach` is actually a symlink to `go/src/github.com/cockroachdb/cockroach`, and
- ~/go` is a symlink to `/mnt/kena/go`
- GOPATH is set to `/mnt/kena/go`.

**Comment by cuongdo** [comment]
is this still an open issue?

**Comment by dt** [comment]
if it is it should be be filed as a minimal repro upstream rather than here (probably something to do with symlinks?)

**Comment by dt** [comment]
my guess is that PWD outside GOAPTH is a no-no, but that's just a guess. not a cockroach bug though.
