### ISSUE TITLE
restore: replan restore after trailing meta sent from restore proc

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#127676]
After a bad distsql plan for a restore, a node(s) may finish its work well before other nodes do. To prevent one or 2 nodes left with a ton of work while the rest sit idle, restore ought to automatically replan 10 minutes after a node has finished its work. This will lead restore to replan at most every 10 minutes. 

To implement, we ought to add a bit to the trailing meta when will be sent when the restore processor shuts down. When the coordinator receives it, it should set a 10 minute timer and replan the distsql job.

Jira issue: CRDB-40544

**Comment by azhu-crl** [comment]
Issue addressed by https://github.com/cockroachdb/cockroach/pull/128356
