### ISSUE TITLE
restore: distribute restore with verify_with_table_data

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#127677]
Currently, restore with the verify_with_table_data option uses the noop split and scatter processor (ssp) which automatically assigns a span to the current node running the ssp, which is only running on a single node. That means that all restore spans will get assigned to run on one node for reading. Instead, the noop ssp should randomly assign spans to nodes. To do this, a node fetcher needs to be added to the flowCtx accessable to the restore data processor. 

Jira issue: CRDB-40545

**Comment by azhu-crl** [comment]
Issue fixed with #127925 and backported to 23.1, 23.2, 24.1, 24.2
