### ISSUE TITLE
Unable to lower or switch off replica count

### ISSUE THREAD

**Issue by cody151** [cockroachdb/cockroach#127660]
For some reason I cannot lower the replica count below 3, I do not need replica count above 2 as I am running cockroachdb VMs on CEPH which has its own replication. Furthermore I probably do not even need replicas in cockroachdb at all I only need the distribution that is offered by cockroachdb rather than replication (since it is wasting space).

Jira issue: CRDB-40540

**Comment by yuzefovich** [comment]
unactionable
