### ISSUE TITLE
ui: some metrics are incorrectly using store ids as the source instead of node ids

### ISSUE THREAD

**Issue by xinhaoz** [cockroachdb/cockroach#127698]
In some metrics dashboards we provide the store id when we should be providing the node id, e.g.: https://github.com/cockroachdb/cockroach/blob/c7050a8fa2d6b64dd265767734d7ba792e1c6772/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/networking.tsx#L34.

This leads to incorrect and missing series on affected graphs.

Jira issue: CRDB-40556

**Comment by daniel-crlabs** [comment]
I see this issue has been marked as closed and it has 3 tags: 23.2, 24.1 and 24.2. What specific minor versions will have these fixes and when will it be available for customers to download? One of our customers has this issue currently and we need to let them know what version they should upgrade to.
