### ISSUE TITLE
SQL Client fails after setting sql.defaults.serial_normalization=5

### ISSUE THREAD

**Issue by rohitsudhakar-crl** [cockroachdb/cockroach#127667]
**Describe the problem**

Cockroach SQL Client fails to connect after setting the following Cluster Settings
set cluster setting sql.defaults.serial_normalization = 5;

set serial_normalization = 'sql_sequence_cached_node';

**To Reproduce**
Start a 3 node Cluster with v24.1.2
Connect to Cockroach SQL
Run the following

set cluster setting sql.defaults.serial_normalization = 5;

Disconnect the session and connect again. The following error appears

```
cockroach sql
#
# Welcome to the CockroachDB SQL shell.
# All statements must be terminated by a semicolon.
# To exit, type: \q.
#
ERROR: invalid value for parameter "serial_normalization": "invalid (5)"
SQLSTATE: 22023
HINT: Available values: rowid,virtual_sequence,sql_sequence,sql_sequence_cached,sql_sequence_cached_node
Failed running "sql"

```

**Expected behavior**
Cockroach SQL should connect fine without any issues.

**Environment:**
 - CockroachDB version v24.1.2

Jira issue: CRDB-40542

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[22686](https://cockroachdb.zendesk.com/agent/tickets/22686) has been linked to this issue.
