### ISSUE TITLE
sentry: github issue filing seems broken on 23.2+

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#127704]
I don't think we've had any github issues opened due to a sentry report on 23.2+ version (only 23.1 and prior) - we should look into that. It seems that either we're no longer able to create / consume the reports properly (IIRC we upgraded the errors library in 23.2 timeframe) or the sentry integration is broken. Perhaps the first step should be finding an internal error on one of the CC clusters and checking whether it resulted in a sentry event.

Jira issue: CRDB-40560

**Comment by rail** [comment]
Looks like downgrading sentry-go from v0.27.0 to v0.18.0 made it work on master :/
I'm going to see what changed in the sdk.

**Comment by rail** [comment]
This should be fixed now
