### ISSUE TITLE
opt: extra projection after GeneratePartialIndexScans

### ISSUE THREAD

**Issue by michae2** [cockroachdb/cockroach#127771]
After applying exploration rule `GeneratePartialIndexScans`, plans can end up with extra nested projections. It seems like `MergeProjects` isn't applying? Here's an opttest that demonstrates the issue on v24.2:

```
exec-ddl
CREATE TABLE xyz (x INT PRIMARY KEY, y INT, z INT, INDEX (z) WHERE y IS NULL)
----

opt expect=MergeProjects
SELECT x FROM xyz WHERE y IS NULL
----
project
 ├── columns: x:1!null
 ├── key: (1)
 └── project
      ├── columns: y:2 x:1!null
      ├── key: (1)
      ├── fd: ()-->(2)
      ├── scan xyz@xyz_z_idx,partial
      │    ├── columns: x:1!null
      │    └── key: (1)
      └── projections
           └── CAST(NULL AS INT8) [as=y:2]
```

Jira issue: CRDB-40588

**Comment by DrewKimball** [comment]
[triage] If the group being explored is under a project and creates a new project, normalization rules don't apply. However, we might merge the renders during exec-building. This is related to unnecessary index joins.
