### ISSUE TITLE
sql: validation of FK relationships in fixed space

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#12780]
Currently we only validate the FK relationships potentially violated by `UPDATE`/`DELETE`/`INSERT` operations using individual point-lookups for each row, meaning a N-row operation will need to do N round-trips to the other table.

The most extreme case of a multi-row FK operation might be running `VALIDATE` on an unvalidated FK, as this needs to check every row in the referencing table. The initial implementation of `VALIDATE` proposed in #12682 attempts to avoid doing O(N) lookups on the referenced table by instead using a JOIN, but unoptimized, that will read the whole result set before applying its WHERE filter valid rows.

We should figure out how to optimize this join such that it uses O(1) space i.e. filter earlier. This would likely be much easier if we could assume both the left and right sides were in the same order.

FK relationships are between indexes, but we do not currently force the indexes to have the same ordering. This allows more flexibility in using existing indexes to support FK constraints (since we *require* they be on indexes), but implies that any batched validation of N rows may be forced to do N, unordered lookups in one of the indexes.

We should consider if we want to require indexes used for FKs match in ordering -- or at least make it default to requiring it and then allow forcing the use of mis-matched ones with an option when the operator is fine with being forced into point-lookup based validation.

cc @knz

**Comment by jordanlewis** [comment]
cc @RaduBerinde probably closable with new fks stuff.
