### ISSUE TITLE
sql: stub out CREATE EXTENSION for plpgsql

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#12786]
Perform the following steps:

1. `rails new myapp --database=postgresql`
2.  Create the model:
```
cd myapp
echo << EOF > app/models/customer.rb
class Customer < ApplicationRecord
    has_many :orders
end
EOF
```
3. `rails db:setup`
4. `rails db:migrate`

This creates a file named `db/schema.rb`with the following:

```
enable_extension "plpgsql"
```

which issues this statement:

```
CREATE EXTENSION IF NOT EXISTS "plpgsql"
```

It doesn't appear that stored procedures are actually needed for anything other than some partitioned tables, so hopefully, this statement can just be stubbed out.

**Comment by dianasaur323** [comment]
@cuongdo is this still an issue for ActiveRecord?

**Comment by cuongdo** [comment]
I'm not sure. @jordanlewis?

**Comment by jordanlewis** [comment]
No, this no longer causes a problem. We still don't support `CREATE EXTENSION`, stubbed or not, but the adapter no longer tries to enable any extensions by default.
