### ISSUE TITLE
Sentry: log.go:322: log.Fatal: tocommit(4023204) is out of range [lastIndex(4023095)]. Was the raft log corrupted, truncated, or lost? (1) attached stack trace   -- stack trace:   | go.etcd.io/raft/v3...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#127904]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5658351426/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5658351426/?referrer=webhooks_plugin)

Panic Message:

```
log.go:322: log.Fatal: tocommit(4023204) is out of range [lastIndex(4023095)]. Was the raft log corrupted, truncated, or lost?
(1) attached stack trace
  -- stack trace:
  | go.etcd.io/raft/v3.(*raftLog).commitTo
  | 	go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/log.go:322
  | go.etcd.io/raft/v3.(*raft).handleHeartbeat
  | 	go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/raft.go:1774
  | go.etcd.io/raft/v3.stepCandidate
  | 	go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/raft.go:1644
  | go.etcd.io/raft/v3.(*raft).Step
  | 	go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/raft.go:1215
  | go.etcd.io/raft/v3.(*RawNode).Step
  | 	go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/rawnode.go:126
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processRaftRequestWithReplica.(*Replica).stepRaftGroup.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:625
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).withRaftGroupLocked
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:2022
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).withRaftGroup
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:2059
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).stepRaftGroup
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:576
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processRaftRequestWithReplica
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:414
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processRequestQueue.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:634
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).withReplicaForRequest
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:369
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processRequestQueue
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:632
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftSchedulerShard).worker
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:399
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).Start.func2
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:321
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:484
  | runtime.goexit
  | 	src/runtime/asm_amd64.s:1650
Wraps: (2) log.Fatal: tocommit(4023204) is out of range [lastIndex(4023095)]. Was the raft log corrupted, truncated, or lost?
Error types: (1) *withstack.withStack (2) *errutil.leafError
-- report composition:
*errutil.leafError: log.Fatal: tocommit(4023204) is out of range [lastIndex(4023095)]. Was the raft log corrupted, truncated, or lost?
log.go:322: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_amd64.s#L1649-L1651](src/runtime/asm_amd64.s#L1649-L1651)
[https://github.com/cockroachdb/cockroach/blob/4634a65a4891dcca4fc56916481d56721954d813/pkg/util/stop/stopper.go#L483-L485](https://github.com/cockroachdb/cockroach/blob/4634a65a4891dcca4fc56916481d56721954d813/pkg/util/stop/stopper.go#L483-L485)
[https://github.com/cockroachdb/cockroach/blob/4634a65a4891dcca4fc56916481d56721954d813/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L320-L322](https://github.com/cockroachdb/cockroach/blob/4634a65a4891dcca4fc56916481d56721954d813/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L320-L322)
[https://github.com/cockroachdb/cockroach/blob/4634a65a4891dcca4fc56916481d56721954d813/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L398-L400](https://github.com/cockroachdb/cockroach/blob/4634a65a4891dcca4fc56916481d56721954d813/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L398-L400)
[https://github.com/cockroachdb/cockroach/blob/4634a65a4891dcca4fc56916481d56721954d813/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L631-L633](https://github.com/cockroachdb/cockroach/blob/4634a65a4891dcca4fc56916481d56721954d813/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L631-L633)
[https://github.com/cockroachdb/cockroach/blob/4634a65a4891dcca4fc56916481d56721954d813/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L368-L370](https://github.com/cockroachdb/cockroach/blob/4634a65a4891dcca4fc56916481d56721954d813/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L368-L370)
[https://github.com/cockroachdb/cockroach/blob/4634a65a4891dcca4fc56916481d56721954d813/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L633-L635](https://github.com/cockroachdb/cockroach/blob/4634a65a4891dcca4fc56916481d56721954d813/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L633-L635)
[https://github.com/cockroachdb/cockroach/blob/4634a65a4891dcca4fc56916481d56721954d813/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L413-L415](https://github.com/cockroachdb/cockroach/blob/4634a65a4891dcca4fc56916481d56721954d813/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L413-L415)
[https://github.com/cockroachdb/cockroach/blob/4634a65a4891dcca4fc56916481d56721954d813/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L575-L577](https://github.com/cockroachdb/cockroach/blob/4634a65a4891dcca4fc56916481d56721954d813/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L575-L577)
[https://github.com/cockroachdb/cockroach/blob/4634a65a4891dcca4fc56916481d56721954d813/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L2058-L2060](https://github.com/cockroachdb/cockroach/blob/4634a65a4891dcca4fc56916481d56721954d813/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L2058-L2060)
[https://github.com/cockroachdb/cockroach/blob/4634a65a4891dcca4fc56916481d56721954d813/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L2021-L2023](https://github.com/cockroachdb/cockroach/blob/4634a65a4891dcca4fc56916481d56721954d813/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L2021-L2023)
[https://github.com/cockroachdb/cockroach/blob/4634a65a4891dcca4fc56916481d56721954d813/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L624-L626](https://github.com/cockroachdb/cockroach/blob/4634a65a4891dcca4fc56916481d56721954d813/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L624-L626)
[go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/rawnode.go#L125-L127](go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/rawnode.go#L125-L127)
[go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/raft.go#L1214-L1216](go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/raft.go#L1214-L1216)
[go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/raft.go#L1643-L1645](go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/raft.go#L1643-L1645)
[go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/raft.go#L1773-L1775](go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/raft.go#L1773-L1775)
[go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/log.go#L321-L323](go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/log.go#L321-L323)
</details>

```
src/runtime/asm_amd64.s in runtime.goexit at line 1650
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 484
pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go in pkg/kv/kvserver.(*raftScheduler).Start.func2 at line 321
pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go in pkg/kv/kvserver.(*raftSchedulerShard).worker at line 399
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).processRequestQueue at line 632
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).withReplicaForRequest at line 369
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).processRequestQueue.func1 at line 634
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).processRaftRequestWithReplica at line 414
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).stepRaftGroup at line 576
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).withRaftGroup at line 2059
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).withRaftGroupLocked at line 2022
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Store).processRaftRequestWithReplica.(*Replica).stepRaftGroup.func1 at line 625
go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/rawnode.go in go.etcd.io/raft/v3.(*RawNode).Step at line 126
go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/raft.go in go.etcd.io/raft/v3.(*raft).Step at line 1215
go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/raft.go in go.etcd.io/raft/v3.stepCandidate at line 1644
go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/raft.go in go.etcd.io/raft/v3.(*raft).handleHeartbeat at line 1774
go.etcd.io/raft/v3/external/io_etcd_go_raft_v3/log.go in go.etcd.io/raft/v3.(*raftLog).commitTo at line 322
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v23.2.2 |
| Go Version | go1.21.5 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.2.2 |
| Cockroach SHA | 4634a65a4891dcca4fc56916481d56721954d813 |
| # of CPUs | 64 |
| # of Goroutines | 393 |

Jira issue: CRDB-40661

**Comment by yuzefovich** [comment]
unactionable
