### ISSUE TITLE
Sentry: db.go:857: log.Fatal: pebble: fatal commit error: no such device
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/pebble.(*DB).applyInternal
  | 	github.com/cockroachdb/pe...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#127923]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5658673418/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5658673418/?referrer=webhooks_plugin)

Panic Message:

```
db.go:857: log.Fatal: pebble: fatal commit error: no such device
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/pebble.(*DB).applyInternal
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go:857
  | github.com/cockroachdb/pebble.(*DB).Apply
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go:780
  | github.com/cockroachdb/pebble.(*Batch).Commit
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/batch.go:1329
  | github.com/cockroachdb/cockroach/pkg/storage.(*pebbleBatch).Commit
  | 	github.com/cockroachdb/cockroach/pkg/storage/pebble_batch.go:617
  | github.com/cockroachdb/cockroach/pkg/storage.WriteSyncNoop
  | 	github.com/cockroachdb/cockroach/pkg/storage/engine.go:1537
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/liveness.(*NodeLiveness).verifyDiskHealth.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/liveness/liveness.go:1155
  | github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight.(*Group).doCall.func1
  | 	github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight/singleflight.go:389
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTask
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:319
  | github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight.(*Group).doCall
  | 	github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight/singleflight.go:388
  | runtime.goexit
  | 	src/runtime/asm_amd64.s:1650
Wraps: (2) secondary error attachment
  | no such device
  | (1) no such device
  | Error types: (1) syscall.Errno
Wraps: (3) log.Fatal: pebble: fatal commit error: no such device
Error types: (1) *withstack.withStack (2) *secondary.withSecondaryError (3) *errutil.leafError
-- report composition:
*errutil.leafError: log.Fatal: pebble: fatal commit error: no such device
*secondary.withSecondaryError
db.go:857: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_amd64.s#L1649-L1651](src/runtime/asm_amd64.s#L1649-L1651)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/util/syncutil/singleflight/singleflight.go#L387-L389](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/util/syncutil/singleflight/singleflight.go#L387-L389)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/util/stop/stopper.go#L318-L320](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/util/stop/stopper.go#L318-L320)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/util/syncutil/singleflight/singleflight.go#L388-L390](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/util/syncutil/singleflight/singleflight.go#L388-L390)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/kv/kvserver/liveness/liveness.go#L1154-L1156](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/kv/kvserver/liveness/liveness.go#L1154-L1156)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/storage/engine.go#L1536-L1538](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/storage/engine.go#L1536-L1538)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/storage/pebble_batch.go#L616-L618](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/storage/pebble_batch.go#L616-L618)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/batch.go#L1328-L1330](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/batch.go#L1328-L1330)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L779-L781](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L779-L781)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L856-L858](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L856-L858)
</details>

```
src/runtime/asm_amd64.s in runtime.goexit at line 1650
pkg/util/syncutil/singleflight/singleflight.go in pkg/util/syncutil/singleflight.(*Group).doCall at line 388
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunTask at line 319
pkg/util/syncutil/singleflight/singleflight.go in pkg/util/syncutil/singleflight.(*Group).doCall.func1 at line 389
pkg/kv/kvserver/liveness/liveness.go in pkg/kv/kvserver/liveness.(*NodeLiveness).verifyDiskHealth.func1 at line 1155
pkg/storage/engine.go in pkg/storage.WriteSyncNoop at line 1537
pkg/storage/pebble_batch.go in pkg/storage.(*pebbleBatch).Commit at line 617
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/batch.go in github.com/cockroachdb/pebble.(*Batch).Commit at line 1329
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go in github.com/cockroachdb/pebble.(*DB).Apply at line 780
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go in github.com/cockroachdb/pebble.(*DB).applyInternal at line 857
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v23.2.3 |
| Go Version | go1.21.5 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.2.3 |
| Cockroach SHA | 03498e5964c0eaa45bb5435b4c600de38d542910 |
| # of CPUs | 20 |
| # of Goroutines | 529 |

Jira issue: CRDB-40673

**Comment by yuzefovich** [comment]
unactionable
