### ISSUE TITLE
Sentry: panic.go:914: no data available
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:914
  | github.com/cockroachdb/cockroach/pkg/storage.(*pebbleBat...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#127907]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5658384101/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5658384101/?referrer=webhooks_plugin)

Panic Message:

```
panic.go:914: no data available
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:914
  | github.com/cockroachdb/cockroach/pkg/storage.(*pebbleBatch).SyncWait
  | 	github.com/cockroachdb/cockroach/pkg/storage/pebble_batch.go:666
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/logstore.(*SyncWaiterLoop).waitLoop
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/logstore/sync_waiter.go:95
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/logstore.(*SyncWaiterLoop).Start.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/logstore/sync_waiter.go:84
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:484
  | runtime.goexit
  | 	src/runtime/asm_amd64.s:1650
Wraps: (2) no data available
Error types: (1) *withstack.withStack (2) syscall.Errno
-- report composition:
syscall.Errno
panic.go:914: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_amd64.s#L1649-L1651](src/runtime/asm_amd64.s#L1649-L1651)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/util/stop/stopper.go#L483-L485](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/util/stop/stopper.go#L483-L485)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/kv/kvserver/logstore/sync_waiter.go#L83-L85](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/kv/kvserver/logstore/sync_waiter.go#L83-L85)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/kv/kvserver/logstore/sync_waiter.go#L94-L96](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/kv/kvserver/logstore/sync_waiter.go#L94-L96)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/storage/pebble_batch.go#L665-L667](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/storage/pebble_batch.go#L665-L667)
[GOROOT/src/runtime/panic.go#L913-L915](GOROOT/src/runtime/panic.go#L913-L915)
</details>

```
src/runtime/asm_amd64.s in runtime.goexit at line 1650
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 484
pkg/kv/kvserver/logstore/sync_waiter.go in pkg/kv/kvserver/logstore.(*SyncWaiterLoop).Start.func1 at line 84
pkg/kv/kvserver/logstore/sync_waiter.go in pkg/kv/kvserver/logstore.(*SyncWaiterLoop).waitLoop at line 95
pkg/storage/pebble_batch.go in pkg/storage.(*pebbleBatch).SyncWait at line 666
GOROOT/src/runtime/panic.go in runtime.gopanic at line 914
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v23.2.3 |
| Go Version | go1.21.5 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.2.3 |
| Cockroach SHA | 03498e5964c0eaa45bb5435b4c600de38d542910 |
| # of CPUs | 4 |
| # of Goroutines | 514 |

Jira issue: CRDB-40664

**Comment by yuzefovich** [comment]
unactionable
