### ISSUE TITLE
Sentry: rewrite.go:670: type descriptor rewrite failed: unknown type kind ×
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/ccl/backupccl.doRestorePlan
  | 	github...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#127976]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5661447488/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5661447488/?referrer=webhooks_plugin)

Panic Message:

```
rewrite.go:670: type descriptor rewrite failed: unknown type kind ×
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/ccl/backupccl.doRestorePlan
  | 	github.com/cockroachdb/cockroach/pkg/ccl/backupccl/restore_planning.go:2129
  | [...repeated from below...]
Wraps: (2) type descriptor rewrite failed
Wraps: (3) assertion failure
Wraps: (4) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/rewrite.TypeDescs
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/rewrite/rewrite.go:670
  | github.com/cockroachdb/cockroach/pkg/ccl/backupccl.doRestorePlan
  | 	github.com/cockroachdb/cockroach/pkg/ccl/backupccl/restore_planning.go:2128
  | github.com/cockroachdb/cockroach/pkg/ccl/backupccl.restorePlanHook.func3
  | 	github.com/cockroachdb/cockroach/pkg/ccl/backupccl/restore_planning.go:1440
  | github.com/cockroachdb/cockroach/pkg/sql.(*hookFnNode).startExec.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/planhook.go:206
  | runtime.goexit
  | 	src/runtime/asm_amd64.s:1695
Wraps: (5) unknown type kind ×
Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *assert.withAssertionFailure (4) *withstack.withStack (5) *errutil.leafError
-- report composition:
*errutil.leafError: unknown type kind ×
rewrite.go:670: *withstack.withStack (top exception)
*assert.withAssertionFailure
*errutil.withPrefix: type descriptor rewrite failed
restore_planning.go:2129: *withstack.withStack (1)
(check the extra data payloads)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_amd64.s#L1694-L1696](src/runtime/asm_amd64.s#L1694-L1696)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/sql/planhook.go#L205-L207](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/sql/planhook.go#L205-L207)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/ccl/backupccl/restore_planning.go#L1439-L1441](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/ccl/backupccl/restore_planning.go#L1439-L1441)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/ccl/backupccl/restore_planning.go#L2128-L2130](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/ccl/backupccl/restore_planning.go#L2128-L2130)
[src/runtime/asm_amd64.s#L1694-L1696](src/runtime/asm_amd64.s#L1694-L1696)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/sql/planhook.go#L205-L207](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/sql/planhook.go#L205-L207)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/ccl/backupccl/restore_planning.go#L1439-L1441](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/ccl/backupccl/restore_planning.go#L1439-L1441)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/ccl/backupccl/restore_planning.go#L2127-L2129](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/ccl/backupccl/restore_planning.go#L2127-L2129)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/sql/catalog/rewrite/rewrite.go#L669-L671](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/sql/catalog/rewrite/rewrite.go#L669-L671)
</details>

```
src/runtime/asm_amd64.s in runtime.goexit at line 1695
pkg/sql/planhook.go in pkg/sql.(*hookFnNode).startExec.func1 at line 206
pkg/ccl/backupccl/restore_planning.go in pkg/ccl/backupccl.restorePlanHook.func3 at line 1440
pkg/ccl/backupccl/restore_planning.go in pkg/ccl/backupccl.doRestorePlan at line 2129
src/runtime/asm_amd64.s in runtime.goexit at line 1695
pkg/sql/planhook.go in pkg/sql.(*hookFnNode).startExec.func1 at line 206
pkg/ccl/backupccl/restore_planning.go in pkg/ccl/backupccl.restorePlanHook.func3 at line 1440
pkg/ccl/backupccl/restore_planning.go in pkg/ccl/backupccl.doRestorePlan at line 2128
pkg/sql/catalog/rewrite/rewrite.go in pkg/sql/catalog/rewrite.TypeDescs at line 670
```

### Tags

| Tag | Value |
| --- | --- |
| Command | start-single-node |
| Environment | v24.1.2 |
| Go Version | go1.22.3 X:nocoverageredesign |
| Platform | darwin amd64 |
| Distribution | CCL |
| Cockroach Release | v24.1.2 |
| Cockroach SHA | 7e81be6de75205c3d08b0d8dcc6ca188306abc27 |
| # of CPUs | 16 |
| # of Goroutines | 570 |

Jira issue: CRDB-40715

**Comment by yuzefovich** [comment]
dup of #125550
