### ISSUE TITLE
Sentry: panic.go:770: read-only file system
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:770
  | github.com/cockroachdb/cockroach/pkg/storage.(*write...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#128052]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5663229780/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5663229780/?referrer=webhooks_plugin)

Panic Message:

```
panic.go:770: read-only file system
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:770
  | github.com/cockroachdb/cockroach/pkg/storage.(*writeBatch).SyncWait
  | 	github.com/cockroachdb/cockroach/pkg/storage/pebble_batch.go:384
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/logstore.(*SyncWaiterLoop).waitLoop
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/logstore/sync_waiter.go:95
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/logstore.(*SyncWaiterLoop).Start.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/logstore/sync_waiter.go:84
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:485
  | runtime.goexit
  | 	src/runtime/asm_amd64.s:1695
Wraps: (2) read-only file system
Error types: (1) *withstack.withStack (2) syscall.Errno
-- report composition:
syscall.Errno
panic.go:770: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_amd64.s#L1694-L1696](src/runtime/asm_amd64.s#L1694-L1696)
[https://github.com/cockroachdb/cockroach/blob/484f8e2f4d3cb23582416944d79eab72ff42a6a1/pkg/util/stop/stopper.go#L484-L486](https://github.com/cockroachdb/cockroach/blob/484f8e2f4d3cb23582416944d79eab72ff42a6a1/pkg/util/stop/stopper.go#L484-L486)
[https://github.com/cockroachdb/cockroach/blob/484f8e2f4d3cb23582416944d79eab72ff42a6a1/pkg/kv/kvserver/logstore/sync_waiter.go#L83-L85](https://github.com/cockroachdb/cockroach/blob/484f8e2f4d3cb23582416944d79eab72ff42a6a1/pkg/kv/kvserver/logstore/sync_waiter.go#L83-L85)
[https://github.com/cockroachdb/cockroach/blob/484f8e2f4d3cb23582416944d79eab72ff42a6a1/pkg/kv/kvserver/logstore/sync_waiter.go#L94-L96](https://github.com/cockroachdb/cockroach/blob/484f8e2f4d3cb23582416944d79eab72ff42a6a1/pkg/kv/kvserver/logstore/sync_waiter.go#L94-L96)
[https://github.com/cockroachdb/cockroach/blob/484f8e2f4d3cb23582416944d79eab72ff42a6a1/pkg/storage/pebble_batch.go#L383-L385](https://github.com/cockroachdb/cockroach/blob/484f8e2f4d3cb23582416944d79eab72ff42a6a1/pkg/storage/pebble_batch.go#L383-L385)
[GOROOT/src/runtime/panic.go#L769-L771](GOROOT/src/runtime/panic.go#L769-L771)
</details>

```
src/runtime/asm_amd64.s in runtime.goexit at line 1695
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 485
pkg/kv/kvserver/logstore/sync_waiter.go in pkg/kv/kvserver/logstore.(*SyncWaiterLoop).Start.func1 at line 84
pkg/kv/kvserver/logstore/sync_waiter.go in pkg/kv/kvserver/logstore.(*SyncWaiterLoop).waitLoop at line 95
pkg/storage/pebble_batch.go in pkg/storage.(*writeBatch).SyncWait at line 384
GOROOT/src/runtime/panic.go in runtime.gopanic at line 770
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v24.1.1 |
| Go Version | go1.22.3 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v24.1.1 |
| Cockroach SHA | 484f8e2f4d3cb23582416944d79eab72ff42a6a1 |
| # of CPUs | 8 |
| # of Goroutines | 270 |

Jira issue: CRDB-40771

**Comment by yuzefovich** [comment]
unactionable
