### ISSUE TITLE
Show combined read & write BW and combined read & write iops in in the DB console

### ISSUE THREAD

**Issue by joshimhoff** [cockroachdb/cockroach#128099]
**Is your feature request related to a problem? Please describe.**
Today, the DB console hardware page shows read & write BW and read & write iops in four separate graphs. When checking if a workload has saturated disk, one may need to add together read & write usage, since some cloud providers have combined iops limits. This is error-prone.

**Describe the solution you'd like**
The DB console hardware page should show combined read & write BW in one graph and combined read & write iops in another graph.

**Describe alternatives you've considered**
In CC Datadog, we will also include BW & iops limits, since the CC control plane knows them.

**Additional context**
This came up in the context of a recent CC incident.

Jira issue: CRDB-40801

**Comment by nicktrav** [comment]
After some internal discussion ([link](https://cockroachlabs.slack.com/archives/C07FGSTRENB/p1723141013522599)), we're going to close this one out.
