### ISSUE TITLE
Scanner run incurs high CPU at 4mb data

### ISSUE THREAD

**Issue by YugeshN** [cockroachdb/cockroach#1280]
I am running a single instance of cockroach and am noticing that the DB seems to be running the CPU at around 40-50% constantly, even though there are no clients connected and it's not (supposed to be) doing anything. 

The console is showing the following:

I0605 20:32:03.599615   14763 node.go:565] runtime stats: 36 goroutines, 1.21MB active, 673493.03cgo/sec, 0.74/0.01 %(u/s)time, 0.03 %gc (704x)
I0605 20:32:03.601440   14763 range.go:934] gossiping cluster id 39a3d847-a5f1-4483-8f0b-d7963055f647 from store 1, range 1
I0605 20:32:03.601470   14763 range.go:942] gossiping sentinel from store 1, range 1
I0605 20:32:03.601487   14763 range.go:946] gossiping first range from store 1, range 1
E0605 20:32:10.947279   14763 queue.go:262] failure processing range range=1 ["" - "\xff\xff") from replicate queue: allocator.go:207: unable to allocate a target store for {[] }
I0605 20:32:18.599368   14763 node.go:565] runtime stats: 34 goroutines, 0.71MB active, 449544.57cgo/sec, 0.89/0.01 %(u/s)time, 0.02 %gc (510x)
E0605 20:32:20.949825   14763 queue.go:262] failure processing range range=1 ["" - "\xff\xff") from replicate queue: allocator.go:207: unable to allocate a target store for {[] }
E0605 20:32:30.953240   14763 queue.go:262] failure processing range range=1 ["" - "\xff\xff") from replicate queue: allocator.go:207: unable to allocate a target store for {[] }
I0605 20:32:33.605321   14763 node.go:565] runtime stats: 36 goroutines, 1.21MB active, 675120.44cgo/sec, 0.75/0.01 %(u/s)time, 0.03 %gc (711x)

Any ideas as to what might be causing the CPU issues?

FYI, I have cockroach running in a VM with 2 CPUs assigned to it (from a 6 core machine). The VM CPU is pegged at 40-50%, whilst the overall machine is around 15%.

Thanks.

**Comment by tschottdorf** [comment]
hey @YugeshN, your node is probably doing *something*. Compare the runtime stats with my idle 3x cluster:

> I0605 17:02:26.528065   29599 node.go:567] runtime stats: 0 tasks, 46 goroutines, 0.95MB active, 1067.36cgo/sec, 0.02/0.01 %(u/s)time, 0.00 %gc (5x)

You shouldn't be seeing too many cgo calls unless RocksDB is being accessed, and you have a lot of GC going on as well. Maybe something is running wild; pprof can tell you:

```
go tool pprof http://localhost:8080/debug/pprof/profile
$ top
```

Mine shows:
```
370ms of 580ms total (63.79%)
Showing top 10 nodes out of 144 (cum >= 10ms)
      flat  flat%   sum%        cum   cum%
     110ms 18.97% 18.97%      120ms 20.69%  runtime.cgocall_errno
     100ms 17.24% 36.21%      100ms 17.24%  runtime.futex
      50ms  8.62% 44.83%       60ms 10.34%  syscall.Syscall
      30ms  5.17% 50.00%       30ms  5.17%  runtime.mallocgc
      20ms  3.45% 53.45%       20ms  3.45%  runtime.epollwait
      20ms  3.45% 56.90%       20ms  3.45%  runtime.usleep
      10ms  1.72% 58.62%       10ms  1.72%  github.com/cockroachdb/cockroach/proto.(*RequestHeader).Unmarshal
      10ms  1.72% 60.34%       10ms  1.72%  github.com/cockroachdb/cockroach/rpc/codec.protoUnmarshal
      10ms  1.72% 62.07%       30ms  5.17%  github.com/coreos/etcd/raft.(*raft).Step
      10ms  1.72% 63.79%       10ms  1.72%  handoffp
```

**Comment by YugeshN** [comment]
Tobias,

I took a couple snapshots of pprof and this is what I got... note, there is nothing connected to my server:

3780ms of 7630ms total (49.54%)
Dropped 63 nodes (cum <= 38.15ms)
Showing top 10 nodes out of 79 (cum >= 700ms)
      flat  flat%   sum%        cum   cum%
     770ms 10.09% 10.09%      770ms 10.09%  scanblock
     760ms  9.96% 20.05%     3040ms 39.84%  runtime.cgocall_errno
     400ms  5.24% 25.29%      490ms  6.42%  runtime.mallocgc
     340ms  4.46% 29.75%      340ms  4.46%  runtime.MSpan_Sweep
     330ms  4.33% 34.08%      330ms  4.33%  runtime.cas
     280ms  3.67% 37.75%      280ms  3.67%  runtime.newdefer
     240ms  3.15% 40.89%      740ms  9.70%  runtime.deferreturn
     230ms  3.01% 43.91%      230ms  3.01%  runtime.writebarrierptr
     220ms  2.88% 46.79%      220ms  2.88%  runtime.releasem
     210ms  2.75% 49.54%      700ms  9.17%  github.com/cockroachdb/cockroach/util/encoding.decodeBytes





3820ms of 7600ms total (50.26%)
Dropped 63 nodes (cum <= 38ms)
Showing top 10 nodes out of 80 (cum >= 800ms)
      flat  flat%   sum%        cum   cum%
     840ms 11.05% 11.05%     3010ms 39.61%  runtime.cgocall_errno
     780ms 10.26% 21.32%      780ms 10.26%  scanblock
     390ms  5.13% 26.45%      570ms  7.50%  runtime.mallocgc
     310ms  4.08% 30.53%      310ms  4.08%  runtime.cas
     280ms  3.68% 34.21%      700ms  9.21%  runtime.makeslice
     270ms  3.55% 37.76%      270ms  3.55%  runtime.MSpan_Sweep
     250ms  3.29% 41.05%      780ms 10.26%  runtime.deferreturn
     250ms  3.29% 44.34%      250ms  3.29%  runtime.newdefer
     240ms  3.16% 47.50%      240ms  3.16%  runtime.writebarrierptr
     210ms  2.76% 50.26%      800ms 10.53%  github.com/cockroachdb/cockroach/util/encoding.decodeBytes

**Comment by tschottdorf** [comment]
Thanks. Not as helpful as I had hoped. If you're getting this on every run, try restarting with `--verbosity=1` and see what the log gives you.
Also, could you post the arguments you're supplying to the binary?

**Comment by YugeshN** [comment]
I am using the following command line to start the server:

./cockroach start --stores=ssd=/root/db --gossip=self= --verbosity=1 --insecure=true

I normally use SSL, I only disabled it in order to get the profiling info.

I enabled verbosity and am getting the following:

I0605 22:26:11.380734   22766 queue.go:246] processing range range=1 ["" - "\xff\xff") from gc queue...
I0605 22:26:11.381307   22766 replicate_queue.go:85] range=1 ["" - "\xff\xff") needs 3 nodes; has 1
E0605 22:26:11.381377   22766 queue.go:262] failure processing range range=1 ["" - "\xff\xff") from replicate queue: allocator.go:207: unable to allocate a target store for {[] }
I0605 22:26:11.381400   22766 queue.go:265] processed range range=1 ["" - "\xff\xff") from replicate queue in 795.041µs
I0605 22:26:11.383073   22766 queue.go:265] processed range range=1 ["" - "\xff\xff") from rangeGC queue in 2.456116ms
I0605 22:26:13.790623   22766 queue.go:265] processed range range=1 ["" - "\xff\xff") from gc queue in 2.40987163s
I0605 22:26:15.862907   22766 clock_offset.go:224] finding offset interval for monitorInterval: 30s, numOffsets 2
I0605 22:26:15.863001   22766 clock_offset.go:180] healthy cluster offset: {-250.028413ms, 250.028413ms}
I0605 22:26:16.036201   22766 node.go:565] runtime stats: 34 goroutines, 0.57MB active, 477832.71cgo/sec, 0.36/0.01 %(u/s)time, 0.03 %gc (843x)
I0605 22:26:16.037360   22766 range.go:934] gossiping cluster id 39a3d847-a5f1-4483-8f0b-d7963055f647 from store 1, range 1
I0605 22:26:16.037388   22766 range.go:942] gossiping sentinel from store 1, range 1
I0605 22:26:16.037403   22766 range.go:946] gossiping first range from store 1, range 1


The spikes in CPU seem to correspond to the following log lines (I could be wrong though):

I0605 22:28:41.403913   22766 queue.go:265] processed range range=1 ["" - "\xff\xff") from rangeGC queue in 419.067µs
I0605 22:28:41.403945   22766 replicate_queue.go:85] range=1 ["" - "\xff\xff") needs 3 nodes; has 1
E0605 22:28:41.404019   22766 queue.go:262] failure processing range range=1 ["" - "\xff\xff") from replicate queue: allocator.go:207: unable to allocate a target store for {[] }
I0605 22:28:41.404039   22766 queue.go:265] processed range range=1 ["" - "\xff\xff") from replicate queue in 657.672µs

**Comment by YugeshN** [comment]
it seems the "failure procesing range..." lines always seems to preceed (from a log perspective) the sudden spike in CPU to around 55%.

**Comment by tschottdorf** [comment]
I can't reproduce it here unfortunately.

- does it happen when you run from an empty db (freshly init'ed) or just on your current one?
- can you update to latest master? it'll improve some log output.
- let's go back to pprof: the top10 are occupied by the garbage collector, so there might still be interesting things running which weren't listed. Try "filter=cockroach" followed by "top", or top999, or take a look at the output of "web" to look at everything graphically (make sure you do "filter=" to undo the filtering when you don't want it any more). If something interesting comes up, please share.

**Comment by tschottdorf** [comment]
sorry, the command is `focus`, not `filter`. I get it wrong every time.

**Comment by YugeshN** [comment]
I just updated to the latest master and initialized the db. the problem does not seem to occur on a fresh / empty db. So it seems the problem is somehow related to the data that I am inserting.

Will dig more into it to see what I can find.

**Comment by tschottdorf** [comment]
It's quite possibly the case that some parts of the system get slower dramatically at this point as most of our testing has been for short-lived instance. Give it a few days, we should be able to reproduce and look into this next week. We definitely appreciate your reports.

**Comment by YugeshN** [comment]
No problem... glad to help dig out some of the issues. FYI, I haven't run into the problem yet after inserting some new data. It could be that the problem was fixed with some recent change (since I update to master today). I will keep adding new data and see if I start running into the problem again. The additional logging looks useful, so if I run into it again, I should hopefully have more info for you.

**Comment by YugeshN** [comment]
I am still seeing spikes in CPU up to 50% (and slightly higher). The difference now is, it doesn't seem to be constant. It spikes up fairly regularly though. There are no clients connected to it.

The console isn't showing anything more than what I previously pasted. It does seem like the spikes are related to the lines I posted previously.

Any other suggestions on how I could dig into what might be causing it?

Thanks.

**Comment by tschottdorf** [comment]
Hey @YugeshN, can you try running with `--scan-interval=10m`? There's a chance the scanner is keeping you busy; we run it very often by default since that's convenient for development.

**Comment by YugeshN** [comment]
Tobias,

I tried running the server with the scan-interval set to 10 minutes, but that had no effect. I am still seeing a CPU spike every 7-10 seconds. What do these lines mean? They seem to be constantly dumped to the console and somehow seem related to the spike:

E0609 22:21:19.120560   11839 queue.go:262] failure processing range range=1 ["" - "\xff\xff") from replicate queue: allocator.go:207: unable to allocate a target store for {[] }
I0609 22:21:19.120585   11839 queue.go:265] processed range range=1 ["" - "\xff\xff") from replicate queue in 1.121102ms
I0609 22:23:12.071512   11839 queue.go:265] processed range range=1 ["" - "\xff\xff") from gc queue in 1.189702289s

**Comment by tschottdorf** [comment]
sorry @YugeshN, I gave you the wrong param. You're going to want to increase `--scan-max-idle-time` to something like `10m`. From your accounts it looks like the scanner is incurring a large overhead, and that should limit those runs. If that confirms our suspicion, the next step is figuring out what exactly takes so long. How much data do you have in that cluster?

**Comment by YugeshN** [comment]
Hi Tobias,

That new flag seems to help... I am not seeing the constant spike every 7-10 seconds now. I currently have a small amount of data. In fact, I expect the amount of data that I would have in a production system to be *significantly* higher than what I have right now... probably around 1000-2000x more and growing at an extremely fast rate (obviously in a cluster and not just one server).

How can I get an accurate measure of the amount of data I have thus far?

**Comment by tschottdorf** [comment]
See what the UI gives you (i.e. point your browser at the address the node runs on). Whatever operation the scanner does keeps it that busy, it's nothing that will remain that way.

**Comment by YugeshN** [comment]
I get this from the "stats" page:

 "stats": {
        "live_bytes": 4365134,
        "key_bytes": 14942,
        "val_bytes": 4512091,
        "intent_bytes": 0,
        "live_count": 26,
        "key_count": 31,
        "val_count": 1124,
        "intent_count": 0,
        "intent_age": 0,
        "gc_bytes_age": 9966821172,
        "sys_bytes": 2987,
        "sys_count": 15,
        "last_update_nanos": 1433976036717577266
      },

**Comment by Downchuck** [comment]
@YugeshN Is this on a single-node installation?

**Comment by YugeshN** [comment]
Yes it is.
On Jun 24, 2015 6:37 PM, Charles Pritchard <notifications@github.com> wrote:@YugeshN Is this on a single-node installation?

**Comment by petermattis** [comment]
Likely the same as #3524.
