### ISSUE TITLE
Why does DROP DATABASE takes so long?

### ISSUE THREAD

**Issue by lindenb1** [cockroachdb/cockroach#128072]
Just q very quick general question, why does DROP DATABASE take so long?
Even if my Database is just 500KB in size, it takes like forever to delete it again, why that?
Running on v24.1.2, I have 3x3 nodes in 3 regions all with locality enabled, but dropping a Database takes like forever.

Kindly asking for some help, I'm new to cockroachDB.

The only thing I see at the Dashboard at the Jobs tab is 

[GC for DROP DATABASE app]

Jira issue: CRDB-40784

**Comment by fqazi** [comment]
@lindenb1 Did the DROP DATABASE statement return in a reasonable amount of time? The garbage collection job is linked to the GC TTL interval and will clean up data once that time has gone by. See: https://www.cockroachlabs.com/docs/stable/architecture/storage-layer#garbage-collection. If the operation did take a long time can you share timings and maybe your schema?

**Comment by lindenb1** [comment]
No, sadly not, waited like 8 hrs. Then crushed my test cluster.
Lucky, this is just evaluation for me. But I also noticed the gc ttl, since my redeployment, I set this to 600 sec. But didn't retry yet as I have to rebuild my whole DB
