### ISSUE TITLE
Sentry: panic.go:884: panic: × (1) attached stack trace   -- stack trace:   | runtime.gopanic   | 	GOROOT/src/runtime/panic.go:884   | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*rangeIDQueue)...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#128136]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5667293123/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5667293123/?referrer=webhooks_plugin)

Panic Message:

```
panic.go:884: panic: ×
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*rangeIDQueue).SetPriorityID
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:127
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).SetPriorityID
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:321
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).setDescLockedRaftMuLocked
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_init.go:403
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).initRaftMuLockedReplicaMuLocked
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_init.go:213
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.prepareRightReplicaForSplit
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_split.go:257
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.splitPostApply
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_split.go:181
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleSplitResult
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_application_result.go:313
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*replicaStateMachine).handleNonTrivialReplicatedEvalResult
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_application_state_machine.go:333
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*replicaStateMachine).ApplySideEffects
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_application_state_machine.go:187
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply.mapCheckedCmdIter
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply/cmd.go:210
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply.(*Task).applyOneBatch
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply/task.go:295
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply.(*Task).ApplyCommittedEntries
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply/task.go:251
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:1021
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReady
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:732
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processReady
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:646
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftSchedulerShard).worker
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:395
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).Start.func2
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:302
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (2) panic: ×
  |
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
  | ×
Error types: (1) *withstack.withStack (2) *errutil.leafError
-- report composition:
*errutil.leafError: panic: ×
panic.go:884: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/util/stop/stopper.go#L469-L471](https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/util/stop/stopper.go#L469-L471)
[https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L301-L303](https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L301-L303)
[https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L394-L396](https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L394-L396)
[https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L645-L647](https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L645-L647)
[https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L731-L733](https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L731-L733)
[https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L1020-L1022](https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L1020-L1022)
[https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/kv/kvserver/apply/task.go#L250-L252](https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/kv/kvserver/apply/task.go#L250-L252)
[https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/kv/kvserver/apply/task.go#L294-L296](https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/kv/kvserver/apply/task.go#L294-L296)
[https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/kv/kvserver/apply/cmd.go#L209-L211](https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/kv/kvserver/apply/cmd.go#L209-L211)
[https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/kv/kvserver/pkg/kv/kvserver/replica_application_state_machine.go#L186-L188](https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/kv/kvserver/pkg/kv/kvserver/replica_application_state_machine.go#L186-L188)
[https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/kv/kvserver/pkg/kv/kvserver/replica_application_state_machine.go#L332-L334](https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/kv/kvserver/pkg/kv/kvserver/replica_application_state_machine.go#L332-L334)
[https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/kv/kvserver/pkg/kv/kvserver/replica_application_result.go#L312-L314](https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/kv/kvserver/pkg/kv/kvserver/replica_application_result.go#L312-L314)
[https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/kv/kvserver/pkg/kv/kvserver/store_split.go#L180-L182](https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/kv/kvserver/pkg/kv/kvserver/store_split.go#L180-L182)
[https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/kv/kvserver/pkg/kv/kvserver/store_split.go#L256-L258](https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/kv/kvserver/pkg/kv/kvserver/store_split.go#L256-L258)
[https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/kv/kvserver/pkg/kv/kvserver/replica_init.go#L212-L214](https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/kv/kvserver/pkg/kv/kvserver/replica_init.go#L212-L214)
[https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/kv/kvserver/pkg/kv/kvserver/replica_init.go#L402-L404](https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/kv/kvserver/pkg/kv/kvserver/replica_init.go#L402-L404)
[https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L320-L322](https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L320-L322)
[https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L126-L128](https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L126-L128)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 470
pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go in pkg/kv/kvserver.(*raftScheduler).Start.func2 at line 302
pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go in pkg/kv/kvserver.(*raftSchedulerShard).worker at line 395
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).processReady at line 646
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).handleRaftReady at line 732
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked at line 1021
pkg/kv/kvserver/apply/task.go in pkg/kv/kvserver/apply.(*Task).ApplyCommittedEntries at line 251
pkg/kv/kvserver/apply/task.go in pkg/kv/kvserver/apply.(*Task).applyOneBatch at line 295
pkg/kv/kvserver/apply/cmd.go in pkg/kv/kvserver/apply.mapCheckedCmdIter at line 210
pkg/kv/kvserver/pkg/kv/kvserver/replica_application_state_machine.go in pkg/kv/kvserver.(*replicaStateMachine).ApplySideEffects at line 187
pkg/kv/kvserver/pkg/kv/kvserver/replica_application_state_machine.go in pkg/kv/kvserver.(*replicaStateMachine).handleNonTrivialReplicatedEvalResult at line 333
pkg/kv/kvserver/pkg/kv/kvserver/replica_application_result.go in pkg/kv/kvserver.(*Replica).handleSplitResult at line 313
pkg/kv/kvserver/pkg/kv/kvserver/store_split.go in pkg/kv/kvserver.splitPostApply at line 181
pkg/kv/kvserver/pkg/kv/kvserver/store_split.go in pkg/kv/kvserver.prepareRightReplicaForSplit at line 257
pkg/kv/kvserver/pkg/kv/kvserver/replica_init.go in pkg/kv/kvserver.(*Replica).initRaftMuLockedReplicaMuLocked at line 213
pkg/kv/kvserver/pkg/kv/kvserver/replica_init.go in pkg/kv/kvserver.(*Replica).setDescLockedRaftMuLocked at line 403
pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go in pkg/kv/kvserver.(*raftScheduler).SetPriorityID at line 321
pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go in pkg/kv/kvserver.(*rangeIDQueue).SetPriorityID at line 127
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
```

### Tags

| Tag | Value |
| --- | --- |
| Command | start-single-node |
| Environment | v23.1.23 |
| Go Version | go1.19.13 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.23 |
| Cockroach SHA | 8705c1e39813e08ab5d582b19f401e1ad5dab4c5 |
| # of CPUs | 32 |
| # of Goroutines | 547 |

Jira issue: CRDB-40810

**Comment by yuzefovich** [comment]
unactionable
