### ISSUE TITLE
sql: failure to roundtrip interval -> string -> interval casts

### ISSUE THREAD

**Issue by eisenstatdavid** [cockroachdb/cockroach#12818]
```
root@:26257> SELECT '40 days'::INTERVAL;
+---------------------+
| '40 days'::INTERVAL |
+---------------------+
| 0m40d0ns            |
+---------------------+
(1 row)
root@:26257> SELECT '40 days'::INTERVAL::STRING::INTERVAL;
pq: could not parse '0m40d0ns' as type interval: time: unknown unit d in duration 0m40d0ns
```

**Comment by alecharmon** [comment]
@eisenstatdavid 👋 I'll take a crack at it

**Comment by alecharmon** [comment]
just to be clear, when casting a string to an interval it works but when casting it to an interval to a string and then back to an interval there are parsing issues?

**Comment by eisenstatdavid** [comment]
I'm not sure whether the string->interval or the interval->string code is at fault. What does Postgres do?

**Comment by alecharmon** [comment]
My understanding is that you need to use `TO_CHAR(timestamp, text_format)` in pg in order to cast to a string, and you need to supply a pattern in order to do so.

**Comment by eisenstatdavid** [comment]
We don't:

```
Davids-MBP:~ eisen$ psql
psql (9.6.1)
Type "help" for help.

eisen=# SELECT '40 days' :: INTERVAL :: VARCHAR :: INTERVAL;
 interval
----------
 40 days
(1 row)
```

**Comment by alecharmon** [comment]
Ahh ok I think i was trying to cast to STRING rather than VARCHAR

**Comment by hainesc** [comment]
Please refer to the link below to see the valid forms of interval.
https://www.postgresql.org/docs/current/static/datatype-datetime.html#DATATYPE-INTERVAL-INPUT-EXAMPLES

```sql
root@:26257> select 'P1Y9DT8H'::interval;
+----------------------+
| 'P1Y9DT8H'::INTERVAL |
+----------------------+
| 12m9d8h0m0s          |
+----------------------+
(1 row)
root@:26257> select '-1-2 2 3:2'::interval;
+------------------------+
| '-1-2 2 3:2'::INTERVAL |
+------------------------+
| -14m2d3h2m0s           |
+------------------------+
(1 row)
```

As you see, the output of interval in cockroach is invalid.

But, in postgres, the output of interval is OK.
```sql
postgres=# select 'P1Y9DT8H'::interval;
        interval        
------------------------
 1 year 9 days 08:00:00
(1 row)

postgres=# select '-1-2 2 3:2'::interval;
             interval              
-----------------------------------
 -1 years -2 mons +2 days 03:02:00
(1 row)
```

May be we should refactor the output form of interval in cockroach.
I can have a try if it is worth.
ping @knz

**Comment by knz** [comment]
We already know how to parse the postgres "long form" (mostly) properly, that is `'1 year 9 days'::interval` works.

I would like to suggest the following changes:

1. complete our postgres long form parser `postgresToDuration` (pkg/sql/parser/interval.go):
    - make it recognize negative values (extend `consumeInt` int the same file)
    - make it recognize the HH:MM:SS sub-format
2. replace our use of Go's standard `time.ParseDuration` in `parseDInterval` (datum.go):
    - fork and extend `ParseDuration` to also recognize years and months and produce our Interval type instead of Go's duration
    - use this replacement in `parseDInterval`
3. document all the things
4. optionally, change the default interval->string conversion to use the long postgres format, if more out-of-the-box pg compat is desired.

Note that even if you could solve the problem at hand using steps 1, 3 and 4 only, we internally would really like to be able to continue to use the short Go syntax for pretty-printing values inside our product (e.g. to format KV keys in the underlying data store), hence my proposal to address both 1 and 2.

**Comment by knz** [comment]
PS: whatever you do don't forget that we support more syntax than pg in some cases (e.g. nanoseconds) so don't drop that in the update!

**Comment by knz** [comment]
@alecharmon do you plan to work further on this?

**Comment by knz** [comment]
I fixed that.
