### ISSUE TITLE
rpc: performance about go rpc

### ISSUE THREAD

**Issue by thundercw** [cockroachdb/cockroach#1283]
Why only use one go rpc client instance between two cockroach nodes? We have tested that it will be the bottleneck  when the concurence is very high. is there any problems if use the clients pool?

Test environment : three nodes cluster in a lan(Gigabit switch), every cockroach node serves at least 60 clients,and  70% requests need cross node   .

 Look forward to your feedback.

**Comment by petermattis** [comment]
Does using multiple go rpc client instances improve performance in your test setup? There is no strong reason for using only one client other than not having any data indicating that using multiple clients would be better.

**Comment by bdarnell** [comment]
I think you may be seeing higher-level issues here: Go's RPC subsystem can multiplex multiple requests on the same connection, but because of locking and queuing at higher levels we cannot take full advantage of this easily. I think we need to look at what's going on in the Range and raft levels to make sure we're able to use the network efficiently.

**Comment by thundercw** [comment]
@petermattis Yes, I have used multiple rpc clients ,and the the performance was improved. However there is still anthor problem that the delay time in go rpc would be getting longer(some requests 10ms+) as the number of requests increased

**Comment by petermattis** [comment]
@tamird Similar to #1521, will this be obsoleted by the move to gRPC?

**Comment by tamird** [comment]
Yes, this one will, sort of. It probably should be absorbed into #1521
since it's really a question of "how many connections should we use between
hosts" and how to structure the abstraction that manages those connections.
