### ISSUE TITLE
sql: support SHOW CREATE TRIGGER

### ISSUE THREAD

**Issue by DrewKimball** [cockroachdb/cockroach#128368]
This is a tracking issue for `SHOW CREATE TRIGGER`, which should show a formatted version of the SQL used to define a trigger. We should also consider showing trigger definitions with `SHOW CREATE TABLE`.

Jira issue: CRDB-40970

**Comment by michae2** [comment]
It would be nice to also have `SHOW CREATE ALL TRIGGERS` as well.
