### ISSUE TITLE
Sentry: external_storage_builder.go:90: failed to run backup: running distributed backup to export 52 ranges: cannot create external storage before init
(1)
Wraps: (2) attached stack trace
  -- stack ...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#128314]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5680150218/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5680150218/?referrer=webhooks_plugin)

Panic Message:

```
external_storage_builder.go:90: failed to run backup: running distributed backup to export 52 ranges: cannot create external storage before init
(1)
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/ccl/backupccl.(*backupResumer).Resume
  | 	github.com/cockroachdb/cockroach/pkg/ccl/backupccl/backup_job.go:871
  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine.func2
  | 	github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1598
  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine
  | 	github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1599
  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).runJob
  | 	github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:456
  | github.com/cockroachdb/cockroach/pkg/jobs.(*StartableJob).Start.func2
  | 	github.com/cockroachdb/cockroach/pkg/jobs/jobs.go:831
  | [...repeated from below...]
Wraps: (3) failed to run backup
Wraps: (4) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/ccl/backupccl.backup.func5
  | 	github.com/cockroachdb/cockroach/pkg/ccl/backupccl/backup_job.go:389
  | github.com/cockroachdb/cockroach/pkg/util/ctxgroup.GoAndWait.Group.GoCtx.func1
  | 	github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:168
  | golang.org/x/sync/errgroup.(*Group).Go.func1
  | 	golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:78
  | runtime.goexit
  | 	src/runtime/asm_arm64.s:1222
Wraps: (5) running distributed backup to export 52 ranges
Wraps: (6) tags: [n1,received-error]
Wraps: (7) tags: [n×,f×,job=×,distsql.gateway=×,distsql.appname=×,sent-error=]
Wraps: (8) assertion failure
Wraps: (9)
  | (opaque error wrapper)
  | type name: github.com/cockroachdb/errors/withstack/*withstack.withStack
  | reportable 0:
  |
  | github.com/cockroachdb/cockroach/pkg/server.(*externalStorageBuilder).makeExternalStorage
  | 	github.com/cockroachdb/cockroach/pkg/server/external_storage_builder.go:90
  | github.com/cockroachdb/cockroach/pkg/ccl/backupccl.runBackupProcessor
  | 	github.com/cockroachdb/cockroach/pkg/ccl/backupccl/backup_processor.go:424
  | github.com/cockroachdb/cockroach/pkg/ccl/backupccl.(*backupDataProcessor).Start.func2
  | 	github.com/cockroachdb/cockroach/pkg/ccl/backupccl/backup_processor.go:234
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:485
  | runtime.goexit
  | 	src/runtime/asm_arm64.s:1222
Wraps: (10) cannot create external storage before init
Error types: (1) *colexecerror.notInternalError (2) *withstack.withStack (3) *errutil.withPrefix (4) *withstack.withStack (5) *errutil.withPrefix (6) *contexttags.withContext (7) *contexttags.withContext (8) *assert.withAssertionFailure (9) *errbase.opaqueWrapper (10) *errutil.leafError
-- report composition:
*errutil.leafError: cannot create external storage before init
external_storage_builder.go:90: *withstack.withStack (top exception)
*assert.withAssertionFailure
*contexttags.withContext: n2
*contexttags.withContext: n1
*errutil.withPrefix: running distributed backup to export 52 ranges
backup_job.go:389: *withstack.withStack (1)
*errutil.withPrefix: failed to run backup
backup_job.go:871: *withstack.withStack (2)
*colexecerror.notInternalError
(check the extra data payloads)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_arm64.s#L1221-L1223](src/runtime/asm_arm64.s#L1221-L1223)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/util/stop/stopper.go#L484-L486](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/util/stop/stopper.go#L484-L486)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/jobs/jobs.go#L830-L832](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/jobs/jobs.go#L830-L832)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/jobs/adopt.go#L455-L457](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/jobs/adopt.go#L455-L457)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/jobs/registry.go#L1598-L1600](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/jobs/registry.go#L1598-L1600)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/jobs/registry.go#L1597-L1599](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/jobs/registry.go#L1597-L1599)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/ccl/backupccl/backup_job.go#L870-L872](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/ccl/backupccl/backup_job.go#L870-L872)
[src/runtime/asm_arm64.s#L1221-L1223](src/runtime/asm_arm64.s#L1221-L1223)
[golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go#L77-L79](golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go#L77-L79)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/util/ctxgroup/ctxgroup.go#L167-L169](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/util/ctxgroup/ctxgroup.go#L167-L169)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/ccl/backupccl/backup_job.go#L388-L390](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/ccl/backupccl/backup_job.go#L388-L390)
[src/runtime/asm_arm64.s#L1221-L1223](src/runtime/asm_arm64.s#L1221-L1223)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/util/stop/stopper.go#L484-L486](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/util/stop/stopper.go#L484-L486)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/ccl/backupccl/backup_processor.go#L233-L235](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/ccl/backupccl/backup_processor.go#L233-L235)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/ccl/backupccl/backup_processor.go#L423-L425](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/ccl/backupccl/backup_processor.go#L423-L425)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/server/external_storage_builder.go#L89-L91](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/server/external_storage_builder.go#L89-L91)
</details>

```
src/runtime/asm_arm64.s in runtime.goexit at line 1222
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 485
pkg/jobs/jobs.go in pkg/jobs.(*StartableJob).Start.func2 at line 831
pkg/jobs/adopt.go in pkg/jobs.(*Registry).runJob at line 456
pkg/jobs/registry.go in pkg/jobs.(*Registry).stepThroughStateMachine at line 1599
pkg/jobs/registry.go in pkg/jobs.(*Registry).stepThroughStateMachine.func2 at line 1598
pkg/ccl/backupccl/backup_job.go in pkg/ccl/backupccl.(*backupResumer).Resume at line 871
src/runtime/asm_arm64.s in runtime.goexit at line 1222
golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go in golang.org/x/sync/errgroup.(*Group).Go.func1 at line 78
pkg/util/ctxgroup/ctxgroup.go in pkg/util/ctxgroup.GoAndWait.Group.GoCtx.func1 at line 168
pkg/ccl/backupccl/backup_job.go in pkg/ccl/backupccl.backup.func5 at line 389
src/runtime/asm_arm64.s in runtime.goexit at line 1222
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 485
pkg/ccl/backupccl/backup_processor.go in pkg/ccl/backupccl.(*backupDataProcessor).Start.func2 at line 234
pkg/ccl/backupccl/backup_processor.go in pkg/ccl/backupccl.runBackupProcessor at line 424
pkg/server/external_storage_builder.go in pkg/server.(*externalStorageBuilder).makeExternalStorage at line 90
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v24.1.2 |
| Go Version | go1.22.3 X:nocoverageredesign |
| Platform | linux arm64 |
| Distribution | CCL |
| Cockroach Release | v24.1.2 |
| Cockroach SHA | 7e81be6de75205c3d08b0d8dcc6ca188306abc27 |
| # of CPUs | 12 |
| # of Goroutines | 561 |

Jira issue: CRDB-40944

**Comment by yuzefovich** [comment]
dup of #120022
