### ISSUE TITLE
Sentry: db.go:857: log.Fatal: pebble: fatal commit error: write ×: read-only file system
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/pebble.(*DB).applyInternal
  | 	github.c...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#128330]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5680455686/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5680455686/?referrer=webhooks_plugin)

Panic Message:

```
db.go:857: log.Fatal: pebble: fatal commit error: write ×: read-only file system
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/pebble.(*DB).applyInternal
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go:857
  | github.com/cockroachdb/pebble.(*DB).Apply
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go:780
  | github.com/cockroachdb/pebble.(*DB).Set
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go:609
  | github.com/cockroachdb/cockroach/pkg/storage.(*Pebble).put
  | 	github.com/cockroachdb/cockroach/pkg/storage/pebble.go:1890
  | github.com/cockroachdb/cockroach/pkg/storage.(*Pebble).PutUnversioned
  | 	github.com/cockroachdb/cockroach/pkg/storage/pebble.go:1875
  | github.com/cockroachdb/cockroach/pkg/storage.(*putBuffer).putInlineMeta
  | 	github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:1747
  | github.com/cockroachdb/cockroach/pkg/storage.mvccPutInternal
  | 	github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:2288
  | github.com/cockroachdb/cockroach/pkg/storage.mvccPutUsingIter
  | 	github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:1973
  | github.com/cockroachdb/cockroach/pkg/storage.MVCCPut
  | 	github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:1883
  | github.com/cockroachdb/cockroach/pkg/storage.MVCCPutProto
  | 	github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:1123
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).WriteLastUpTimestamp
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store.go:2613
  | github.com/cockroachdb/cockroach/pkg/server.NewServer.func4.1
  | 	github.com/cockroachdb/cockroach/pkg/server/server.go:533
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Stores).VisitStores.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/stores.go:149
  | github.com/cockroachdb/cockroach/pkg/util/syncutil.(*IntMap).Range
  | 	github.com/cockroachdb/cockroach/pkg/util/syncutil/int_map.go:358
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Stores).VisitStores
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/stores.go:148
  | github.com/cockroachdb/cockroach/pkg/server.NewServer.func4
  | 	github.com/cockroachdb/cockroach/pkg/server/server.go:532
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/liveness.(*NodeLiveness).Start.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/liveness/liveness.go:678
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:484
  | runtime.goexit
  | 	src/runtime/asm_amd64.s:1650
Wraps: (2) secondary error attachment
  | write ×: read-only file system
  | (1) attached stack trace
  |   -- stack trace:
  |   | github.com/cockroachdb/pebble/vfs.(*syncingFile).Write
  |   | 	github.com/cockroachdb/pebble/vfs/external/com_github_cockroachdb_pebble/vfs/syncing_file.go:65
  |   | github.com/cockroachdb/pebble/record.(*LogWriter).flushPending
  |   | 	github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go:533
  |   | github.com/cockroachdb/pebble/record.(*LogWriter).flushLoop
  |   | 	github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go:473
  |   | runtime/pprof.Do
  |   | 	GOROOT/src/runtime/pprof/runtime.go:51
  |   | github.com/cockroachdb/pebble/record.NewLogWriter.func2
  |   | 	github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go:355
  |   | runtime.goexit
  |   | 	src/runtime/asm_amd64.s:1650
  | Wraps: (2) write ×
  | Wraps: (3) read-only file system
  | Error types: (1) *withstack.withStack (2) *fs.PathError (3) syscall.Errno
Wraps: (3) log.Fatal: pebble: fatal commit error: write ×: read-only file system
Error types: (1) *withstack.withStack (2) *secondary.withSecondaryError (3) *errutil.leafError
-- report composition:
*errutil.leafError: log.Fatal: pebble: fatal commit error: write ×: read-only file system
*secondary.withSecondaryError: details for github.com/cockroachdb/errors/withstack/*withstack.withStack:::
db.go:857: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_amd64.s#L1649-L1651](src/runtime/asm_amd64.s#L1649-L1651)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/util/stop/stopper.go#L483-L485](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/util/stop/stopper.go#L483-L485)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/kv/kvserver/liveness/liveness.go#L677-L679](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/kv/kvserver/liveness/liveness.go#L677-L679)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/server/server.go#L531-L533](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/server/server.go#L531-L533)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/kv/kvserver/pkg/kv/kvserver/stores.go#L147-L149](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/kv/kvserver/pkg/kv/kvserver/stores.go#L147-L149)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/util/syncutil/int_map.go#L357-L359](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/util/syncutil/int_map.go#L357-L359)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/kv/kvserver/pkg/kv/kvserver/stores.go#L148-L150](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/kv/kvserver/pkg/kv/kvserver/stores.go#L148-L150)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/server/server.go#L532-L534](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/server/server.go#L532-L534)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/kv/kvserver/pkg/kv/kvserver/store.go#L2612-L2614](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/kv/kvserver/pkg/kv/kvserver/store.go#L2612-L2614)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/storage/mvcc.go#L1122-L1124](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/storage/mvcc.go#L1122-L1124)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/storage/mvcc.go#L1882-L1884](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/storage/mvcc.go#L1882-L1884)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/storage/mvcc.go#L1972-L1974](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/storage/mvcc.go#L1972-L1974)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/storage/mvcc.go#L2287-L2289](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/storage/mvcc.go#L2287-L2289)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/storage/mvcc.go#L1746-L1748](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/storage/mvcc.go#L1746-L1748)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/storage/pebble.go#L1874-L1876](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/storage/pebble.go#L1874-L1876)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/storage/pebble.go#L1889-L1891](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/storage/pebble.go#L1889-L1891)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L608-L610](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L608-L610)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L779-L781](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L779-L781)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L856-L858](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L856-L858)
</details>

```
src/runtime/asm_amd64.s in runtime.goexit at line 1650
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 484
pkg/kv/kvserver/liveness/liveness.go in pkg/kv/kvserver/liveness.(*NodeLiveness).Start.func1 at line 678
pkg/server/server.go in pkg/server.NewServer.func4 at line 532
pkg/kv/kvserver/pkg/kv/kvserver/stores.go in pkg/kv/kvserver.(*Stores).VisitStores at line 148
pkg/util/syncutil/int_map.go in pkg/util/syncutil.(*IntMap).Range at line 358
pkg/kv/kvserver/pkg/kv/kvserver/stores.go in pkg/kv/kvserver.(*Stores).VisitStores.func1 at line 149
pkg/server/server.go in pkg/server.NewServer.func4.1 at line 533
pkg/kv/kvserver/pkg/kv/kvserver/store.go in pkg/kv/kvserver.(*Store).WriteLastUpTimestamp at line 2613
pkg/storage/mvcc.go in pkg/storage.MVCCPutProto at line 1123
pkg/storage/mvcc.go in pkg/storage.MVCCPut at line 1883
pkg/storage/mvcc.go in pkg/storage.mvccPutUsingIter at line 1973
pkg/storage/mvcc.go in pkg/storage.mvccPutInternal at line 2288
pkg/storage/mvcc.go in pkg/storage.(*putBuffer).putInlineMeta at line 1747
pkg/storage/pebble.go in pkg/storage.(*Pebble).PutUnversioned at line 1875
pkg/storage/pebble.go in pkg/storage.(*Pebble).put at line 1890
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go in github.com/cockroachdb/pebble.(*DB).Set at line 609
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go in github.com/cockroachdb/pebble.(*DB).Apply at line 780
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go in github.com/cockroachdb/pebble.(*DB).applyInternal at line 857
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v23.2.3 |
| Go Version | go1.21.5 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.2.3 |
| Cockroach SHA | 03498e5964c0eaa45bb5435b4c600de38d542910 |
| # of CPUs | 20 |
| # of Goroutines | 179 |

Jira issue: CRDB-40945

**Comment by yuzefovich** [comment]
unactionable
