### ISSUE TITLE
Sentry: replica_proposal.go:352: log.Fatal: sequence identical for different leases, prevLease=repl=(n5,s5):2 seq=12774 start=1722886583.033361114,0 epo=14514 pro=1722886583.033361114,0, newLease=repl...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#128395]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5683512461/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5683512461/?referrer=webhooks_plugin)

Panic Message:

```
replica_proposal.go:352: log.Fatal: sequence identical for different leases, prevLease=repl=(n5,s5):2 seq=12774 start=1722886583.033361114,0 epo=14514 pro=1722886583.033361114,0, newLease=repl=(n4,s4):5 seq=12774 start=1722960880.101350118,0 epo=15065 pro=1722960884.601696051,0
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).leasePostApplyLocked
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go:352
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).applySnapshot
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raftstorage.go:784
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:946
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processRaftSnapshotRequest.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:492
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).withReplicaForRequest
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:369
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processRaftSnapshotRequest
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:433
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).receiveSnapshot
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_snapshot.go:1428
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).HandleSnapshot.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:216
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:336
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).HandleSnapshot
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:213
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*RaftTransport).RaftSnapshot
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/raft_transport.go:615
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver._MultiRaft_RaftSnapshot_Handler
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/bazel-out/k8-opt/bin/pkg/kv/kvserver/kvserver_go_proto_/github.com/cockroachdb/cockroach/pkg/kv/kvserver/storage_services.pb.go:267
  | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.StreamServerInterceptor.func13
  | 	github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go:165
  | google.golang.org/grpc.getChainStreamHandler.func1
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1478
  | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func4
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:178
  | google.golang.org/grpc.getChainStreamHandler.func1
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1478
  | github.com/cockroachdb/cockroach/pkg/rpc.kvAuth.streamInterceptor
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/auth.go:167
  | google.golang.org/grpc.getChainStreamHandler.func1
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1478
  | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func2.1
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:145
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:336
  | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:144
  | google.golang.org/grpc.NewServer.chainStreamServerInterceptors.chainStreamInterceptors.func2
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1469
  | google.golang.org/grpc.(*Server).processStreamingRPC
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1627
  | google.golang.org/grpc.(*Server).handleStream
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1708
  | google.golang.org/grpc.(*Server).serveStreams.func1.2
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:965
  | runtime.goexit
  | 	src/runtime/asm_amd64.s:1650
Wraps: (2) log.Fatal: sequence identical for different leases, prevLease=repl=(n5,s5):2 seq=12774 start=1722886583.033361114,0 epo=14514 pro=1722886583.033361114,0, newLease=repl=(n4,s4):5 seq=12774 start=1722960880.101350118,0 epo=15065 pro=1722960884.601696051,0
Error types: (1) *withstack.withStack (2) *errutil.leafError
-- report composition:
*errutil.leafError: log.Fatal: sequence identical for different leases, prevLease=repl=(n5,s5):2 seq=12774 start=1722886583.033361114,0 epo=14514 pro=1722886583.033361114,0, newLease=repl=(n4,s4):5 seq=12774 start=1722960880.101350118,0 epo=15065 pro=1722960884.601696051,0
replica_proposal.go:352: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_amd64.s#L1649-L1651](src/runtime/asm_amd64.s#L1649-L1651)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L964-L966](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L964-L966)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1707-L1709](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1707-L1709)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1626-L1628](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1626-L1628)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1468-L1470](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1468-L1470)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/rpc/pkg/rpc/context.go#L143-L145](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/rpc/pkg/rpc/context.go#L143-L145)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/util/stop/stopper.go#L335-L337](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/util/stop/stopper.go#L335-L337)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/rpc/pkg/rpc/context.go#L144-L146](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/rpc/pkg/rpc/context.go#L144-L146)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1477-L1479](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1477-L1479)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/rpc/pkg/rpc/auth.go#L166-L168](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/rpc/pkg/rpc/auth.go#L166-L168)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1477-L1479](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1477-L1479)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/rpc/pkg/rpc/context.go#L177-L179](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/rpc/pkg/rpc/context.go#L177-L179)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1477-L1479](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1477-L1479)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go#L164-L166](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go#L164-L166)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/kv/kvserver/bazel-out/k8-opt/bin/pkg/kv/kvserver/kvserver_go_proto_/github.com/cockroachdb/cockroach/pkg/kv/kvserver/storage_services.pb.go#L266-L268](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/kv/kvserver/bazel-out/k8-opt/bin/pkg/kv/kvserver/kvserver_go_proto_/github.com/cockroachdb/cockroach/pkg/kv/kvserver/storage_services.pb.go#L266-L268)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/kv/kvserver/pkg/kv/kvserver/raft_transport.go#L614-L616](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/kv/kvserver/pkg/kv/kvserver/raft_transport.go#L614-L616)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L212-L214](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L212-L214)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/util/stop/stopper.go#L335-L337](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/util/stop/stopper.go#L335-L337)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L215-L217](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L215-L217)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/kv/kvserver/pkg/kv/kvserver/store_snapshot.go#L1427-L1429](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/kv/kvserver/pkg/kv/kvserver/store_snapshot.go#L1427-L1429)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L432-L434](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L432-L434)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L368-L370](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L368-L370)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L491-L493](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L491-L493)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L945-L947](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L945-L947)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/kv/kvserver/pkg/kv/kvserver/replica_raftstorage.go#L783-L785](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/kv/kvserver/pkg/kv/kvserver/replica_raftstorage.go#L783-L785)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go#L351-L353](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go#L351-L353)
</details>

```
src/runtime/asm_amd64.s in runtime.goexit at line 1650
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.(*Server).serveStreams.func1.2 at line 965
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.(*Server).handleStream at line 1708
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.(*Server).processStreamingRPC at line 1627
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.NewServer.chainStreamServerInterceptors.chainStreamInterceptors.func2 at line 1469
pkg/rpc/pkg/rpc/context.go in pkg/rpc.NewServerEx.func2 at line 144
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunTaskWithErr at line 336
pkg/rpc/pkg/rpc/context.go in pkg/rpc.NewServerEx.func2.1 at line 145
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.getChainStreamHandler.func1 at line 1478
pkg/rpc/pkg/rpc/auth.go in pkg/rpc.kvAuth.streamInterceptor at line 167
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.getChainStreamHandler.func1 at line 1478
pkg/rpc/pkg/rpc/context.go in pkg/rpc.NewServerEx.func4 at line 178
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.getChainStreamHandler.func1 at line 1478
pkg/util/tracing/grpcinterceptor/grpc_interceptor.go in pkg/rpc.NewServerEx.StreamServerInterceptor.func13 at line 165
pkg/kv/kvserver/bazel-out/k8-opt/bin/pkg/kv/kvserver/kvserver_go_proto_/github.com/cockroachdb/cockroach/pkg/kv/kvserver/storage_services.pb.go in pkg/kv/kvserver._MultiRaft_RaftSnapshot_Handler at line 267
pkg/kv/kvserver/pkg/kv/kvserver/raft_transport.go in pkg/kv/kvserver.(*RaftTransport).RaftSnapshot at line 615
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).HandleSnapshot at line 213
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunTaskWithErr at line 336
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).HandleSnapshot.func1 at line 216
pkg/kv/kvserver/pkg/kv/kvserver/store_snapshot.go in pkg/kv/kvserver.(*Store).receiveSnapshot at line 1428
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).processRaftSnapshotRequest at line 433
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).withReplicaForRequest at line 369
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).processRaftSnapshotRequest.func1 at line 492
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked at line 946
pkg/kv/kvserver/pkg/kv/kvserver/replica_raftstorage.go in pkg/kv/kvserver.(*Replica).applySnapshot at line 784
pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go in pkg/kv/kvserver.(*Replica).leasePostApplyLocked at line 352
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v23.2.3 |
| Go Version | go1.21.5 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.2.3 |
| Cockroach SHA | 03498e5964c0eaa45bb5435b4c600de38d542910 |
| # of CPUs | 20 |
| # of Goroutines | 488 |

Jira issue: CRDB-40991

**Comment by yuzefovich** [comment]
unactionable
