### ISSUE TITLE
ui: allow typing in custom time ranges

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#12833]
While the time selector for graphs is nice, it would be great if we could specify custom durations.
One possibility to do this would be to use the short suffix for intervals and allow modifications.

eg: instead of "Last 6 Hours", just put "6h". A user can just edit that to "3h" to have an arbitrary amount of time.
Simple expressions would be sufficient for now, we can worry about composite expressions later, if at all.

**Comment by mberhault** [comment]
@mrtracy: you mentioned a specific tag to use for UI stuff? I don't see one.

**Comment by dianasaur323** [comment]
I think we can move this out of 1.0 for now.

**Comment by dianasaur323** [comment]
Will be addressed by https://github.com/cockroachdb/cockroach/issues/13752

**Comment by couchand** [comment]
Oh my this would be a useful thing to have.  While on support duty I got sent a link to a cluster that had an event happen that needed investigation.  I didn't get in until four hours later, so now I'm trying to interpret five pixel widths on the 6 hour graph corresponding to when that happened.

**Comment by vilterp** [comment]
Related to time selection: #7778

cc @celiala; this was the pair of issues I mentioned as another project for you.
