### ISSUE TITLE
Sentry: errors.go:91: ×: referenced descriptor ID 191: looking up ID 191: descriptor not found
(1)
Wraps: (2) candidate pg code: XX000
Wraps: (3) attached stack trace
  -- stack trace:
  | github.com...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#128485]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5687957345/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5687957345/?referrer=webhooks_plugin)

Panic Message:

```
errors.go:91: ×: referenced descriptor ID 191: looking up ID 191: descriptor not found
(1)
Wraps: (2) candidate pg code: XX000
Wraps: (3) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.glob..func41.1
  | 	github.com/cockroachdb/cockroach/pkg/sql/crdb_internal.go:1469
  | github.com/cockroachdb/cockroach/pkg/sql.glob..func41
  | 	github.com/cockroachdb/cockroach/pkg/sql/crdb_internal.go:1587
  | github.com/cockroachdb/cockroach/pkg/sql.(*virtualDefEntry).getPlanInfo.func1.1
  | 	github.com/cockroachdb/cockroach/pkg/sql/virtual_schema.go:682
  | github.com/cockroachdb/cockroach/pkg/sql.setupGenerator.func3
  | 	github.com/cockroachdb/cockroach/pkg/sql/virtual_table.go:127
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:484
Wraps: (4) ×
Wraps: (5) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.wrapError
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_query.go:173
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.catalogQuery.processDescriptorResultRow
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_query.go:116
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.catalogQuery.query
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_query.go:75
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.catalogReader.GetByIDs
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_reader.go:285
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.(*cachedCatalogReader).GetByIDs
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_reader_cached.go:352
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.getDescriptorsByID
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:207
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.ByIDGetter.Descs
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/getters.go:39
  | github.com/cockroachdb/cockroach/pkg/sql.glob..func41
  | 	github.com/cockroachdb/cockroach/pkg/sql/crdb_internal.go:1585
  | github.com/cockroachdb/cockroach/pkg/sql.(*virtualDefEntry).getPlanInfo.func1.1
  | 	github.com/cockroachdb/cockroach/pkg/sql/virtual_schema.go:682
  | github.com/cockroachdb/cockroach/pkg/sql.setupGenerator.func3
  | 	github.com/cockroachdb/cockroach/pkg/sql/virtual_table.go:127
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:484
Wraps: (6) referenced descriptor ID 191
Wraps: (7) secondary error attachment
  | failed to find descriptor [191]
  | (1) attached stack trace
  |   -- stack trace:
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.requiredError
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_query.go:215
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.build
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_query.go:187
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.catalogQuery.processDescriptorResultRow
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_query.go:114
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.catalogQuery.query
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_query.go:75
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.catalogReader.GetByIDs
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_reader.go:285
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.(*cachedCatalogReader).GetByIDs
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_reader_cached.go:352
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.getDescriptorsByID
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:207
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.ByIDGetter.Descs
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/getters.go:39
  |   | github.com/cockroachdb/cockroach/pkg/sql.glob..func41
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/crdb_internal.go:1585
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*virtualDefEntry).getPlanInfo.func1.1
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/virtual_schema.go:682
  |   | github.com/cockroachdb/cockroach/pkg/sql.setupGenerator.func3
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/virtual_table.go:127
  |   | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  |   | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:484
  |   | runtime.goexit
  |   | 	src/runtime/asm_arm64.s:1197
  | Wraps: (2) failed to find descriptor [191]
  | Error types: (1) *withstack.withStack (2) *errutil.leafError
Wraps: (8) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/catalog.NewDescriptorNotFoundError
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/errors.go:94
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.requiredError
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_query.go:217
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.build
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_query.go:187
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.catalogQuery.processDescriptorResultRow
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_query.go:114
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.catalogQuery.query
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_query.go:75
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.catalogReader.GetByIDs
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_reader.go:285
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.(*cachedCatalogReader).GetByIDs
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_reader_cached.go:352
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.getDescriptorsByID
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:207
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.ByIDGetter.Descs
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/getters.go:39
  | github.com/cockroachdb/cockroach/pkg/sql.glob..func41
  | 	github.com/cockroachdb/cockroach/pkg/sql/crdb_internal.go:1585
  | github.com/cockroachdb/cockroach/pkg/sql.(*virtualDefEntry).getPlanInfo.func1.1
  | 	github.com/cockroachdb/cockroach/pkg/sql/virtual_schema.go:682
  | github.com/cockroachdb/cockroach/pkg/sql.setupGenerator.func3
  | 	github.com/cockroachdb/cockroach/pkg/sql/virtual_table.go:127
  | [...repeated from below...]
Wraps: (9) looking up ID 191
Wraps: (10) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/catalog.init
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/errors.go:91
  | runtime.doInit1
  | 	GOROOT/src/runtime/proc.go:6752
  | runtime.doInit
  | 	GOROOT/src/runtime/proc.go:6719
  | runtime.main
  | 	GOROOT/src/runtime/proc.go:249
  | runtime.goexit
  | 	src/runtime/asm_arm64.s:1197
Wraps: (11) descriptor not found
Error types: (1) *colexecerror.notInternalError (2) *pgerror.withCandidateCode (3) *withstack.withStack (4) *errutil.withPrefix (5) *withstack.withStack (6) *errutil.withPrefix (7) *secondary.withSecondaryError (8) *withstack.withStack (9) *errutil.withPrefix (10) *withstack.withStack (11) *errutil.leafError
-- report composition:
*errutil.leafError: descriptor not found
errors.go:91: *withstack.withStack (top exception)
*errutil.withPrefix: looking up ID 191
errors.go:94: *withstack.withStack (1)
*secondary.withSecondaryError: details for github.com/cockroachdb/errors/withstack/*...
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_arm64.s#L1196-L1198](src/runtime/asm_arm64.s#L1196-L1198)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/util/stop/stopper.go#L483-L485](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/util/stop/stopper.go#L483-L485)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/virtual_table.go#L126-L128](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/virtual_table.go#L126-L128)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/virtual_schema.go#L681-L683](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/virtual_schema.go#L681-L683)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/crdb_internal.go#L1586-L1588](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/crdb_internal.go#L1586-L1588)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/crdb_internal.go#L1468-L1470](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/crdb_internal.go#L1468-L1470)
[src/runtime/asm_arm64.s#L1196-L1198](src/runtime/asm_arm64.s#L1196-L1198)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/util/stop/stopper.go#L483-L485](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/util/stop/stopper.go#L483-L485)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/virtual_table.go#L126-L128](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/virtual_table.go#L126-L128)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/virtual_schema.go#L681-L683](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/virtual_schema.go#L681-L683)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/crdb_internal.go#L1584-L1586](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/crdb_internal.go#L1584-L1586)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/catalog/descs/getters.go#L38-L40](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/catalog/descs/getters.go#L38-L40)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/catalog/descs/descriptor.go#L206-L208](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/catalog/descs/descriptor.go#L206-L208)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/catalog/internal/catkv/catalog_reader_cached.go#L351-L353](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/catalog/internal/catkv/catalog_reader_cached.go#L351-L353)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/catalog/internal/catkv/catalog_reader.go#L284-L286](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/catalog/internal/catkv/catalog_reader.go#L284-L286)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/catalog/internal/catkv/catalog_query.go#L74-L76](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/catalog/internal/catkv/catalog_query.go#L74-L76)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/catalog/internal/catkv/catalog_query.go#L115-L117](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/catalog/internal/catkv/catalog_query.go#L115-L117)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/catalog/internal/catkv/catalog_query.go#L172-L174](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/catalog/internal/catkv/catalog_query.go#L172-L174)
[src/runtime/asm_arm64.s#L1196-L1198](src/runtime/asm_arm64.s#L1196-L1198)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/util/stop/stopper.go#L483-L485](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/util/stop/stopper.go#L483-L485)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/virtual_table.go#L126-L128](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/virtual_table.go#L126-L128)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/virtual_schema.go#L681-L683](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/virtual_schema.go#L681-L683)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/crdb_internal.go#L1584-L1586](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/crdb_internal.go#L1584-L1586)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/catalog/descs/getters.go#L38-L40](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/catalog/descs/getters.go#L38-L40)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/catalog/descs/descriptor.go#L206-L208](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/catalog/descs/descriptor.go#L206-L208)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/catalog/internal/catkv/catalog_reader_cached.go#L351-L353](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/catalog/internal/catkv/catalog_reader_cached.go#L351-L353)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/catalog/internal/catkv/catalog_reader.go#L284-L286](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/catalog/internal/catkv/catalog_reader.go#L284-L286)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/catalog/internal/catkv/catalog_query.go#L74-L76](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/catalog/internal/catkv/catalog_query.go#L74-L76)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/catalog/internal/catkv/catalog_query.go#L113-L115](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/catalog/internal/catkv/catalog_query.go#L113-L115)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/catalog/internal/catkv/catalog_query.go#L186-L188](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/catalog/internal/catkv/catalog_query.go#L186-L188)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/catalog/internal/catkv/catalog_query.go#L216-L218](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/catalog/internal/catkv/catalog_query.go#L216-L218)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/catalog/errors.go#L93-L95](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/catalog/errors.go#L93-L95)
[src/runtime/asm_arm64.s#L1196-L1198](src/runtime/asm_arm64.s#L1196-L1198)
[GOROOT/src/runtime/proc.go#L248-L250](GOROOT/src/runtime/proc.go#L248-L250)
[GOROOT/src/runtime/proc.go#L6718-L6720](GOROOT/src/runtime/proc.go#L6718-L6720)
[GOROOT/src/runtime/proc.go#L6751-L6753](GOROOT/src/runtime/proc.go#L6751-L6753)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/catalog/errors.go#L90-L92](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/catalog/errors.go#L90-L92)
</details>

```
src/runtime/asm_arm64.s in runtime.goexit at line 1197
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 484
pkg/sql/virtual_table.go in pkg/sql.setupGenerator.func3 at line 127
pkg/sql/virtual_schema.go in pkg/sql.(*virtualDefEntry).getPlanInfo.func1.1 at line 682
pkg/sql/crdb_internal.go in pkg/sql.glob..func41 at line 1587
pkg/sql/crdb_internal.go in pkg/sql.glob..func41.1 at line 1469
src/runtime/asm_arm64.s in runtime.goexit at line 1197
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 484
pkg/sql/virtual_table.go in pkg/sql.setupGenerator.func3 at line 127
pkg/sql/virtual_schema.go in pkg/sql.(*virtualDefEntry).getPlanInfo.func1.1 at line 682
pkg/sql/crdb_internal.go in pkg/sql.glob..func41 at line 1585
pkg/sql/catalog/descs/getters.go in pkg/sql/catalog/descs.ByIDGetter.Descs at line 39
pkg/sql/catalog/descs/descriptor.go in pkg/sql/catalog/descs.getDescriptorsByID at line 207
pkg/sql/catalog/internal/catkv/catalog_reader_cached.go in pkg/sql/catalog/internal/catkv.(*cachedCatalogReader).GetByIDs at line 352
pkg/sql/catalog/internal/catkv/catalog_reader.go in pkg/sql/catalog/internal/catkv.catalogReader.GetByIDs at line 285
pkg/sql/catalog/internal/catkv/catalog_query.go in pkg/sql/catalog/internal/catkv.catalogQuery.query at line 75
pkg/sql/catalog/internal/catkv/catalog_query.go in pkg/sql/catalog/internal/catkv.catalogQuery.processDescriptorResultRow at line 116
pkg/sql/catalog/internal/catkv/catalog_query.go in pkg/sql/catalog/internal/catkv.wrapError at line 173
src/runtime/asm_arm64.s in runtime.goexit at line 1197
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 484
pkg/sql/virtual_table.go in pkg/sql.setupGenerator.func3 at line 127
pkg/sql/virtual_schema.go in pkg/sql.(*virtualDefEntry).getPlanInfo.func1.1 at line 682
pkg/sql/crdb_internal.go in pkg/sql.glob..func41 at line 1585
pkg/sql/catalog/descs/getters.go in pkg/sql/catalog/descs.ByIDGetter.Descs at line 39
pkg/sql/catalog/descs/descriptor.go in pkg/sql/catalog/descs.getDescriptorsByID at line 207
pkg/sql/catalog/internal/catkv/catalog_reader_cached.go in pkg/sql/catalog/internal/catkv.(*cachedCatalogReader).GetByIDs at line 352
pkg/sql/catalog/internal/catkv/catalog_reader.go in pkg/sql/catalog/internal/catkv.catalogReader.GetByIDs at line 285
pkg/sql/catalog/internal/catkv/catalog_query.go in pkg/sql/catalog/internal/catkv.catalogQuery.query at line 75
pkg/sql/catalog/internal/catkv/catalog_query.go in pkg/sql/catalog/internal/catkv.catalogQuery.processDescriptorResultRow at line 114
pkg/sql/catalog/internal/catkv/catalog_query.go in pkg/sql/catalog/internal/catkv.build at line 187
pkg/sql/catalog/internal/catkv/catalog_query.go in pkg/sql/catalog/internal/catkv.requiredError at line 217
pkg/sql/catalog/errors.go in pkg/sql/catalog.NewDescriptorNotFoundError at line 94
src/runtime/asm_arm64.s in runtime.goexit at line 1197
GOROOT/src/runtime/proc.go in runtime.main at line 249
GOROOT/src/runtime/proc.go in runtime.doInit at line 6719
GOROOT/src/runtime/proc.go in runtime.doInit1 at line 6752
pkg/sql/catalog/errors.go in pkg/sql/catalog.init at line 91
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v23.2.8 |
| Go Version | go1.21.10 X:nocoverageredesign |
| Platform | linux arm64 |
| Distribution | CCL |
| Cockroach Release | v23.2.8 |
| Cockroach SHA | e003de1d4ce4f9817d62e53b5af9961bdd4f2571 |
| # of CPUs | 32 |
| # of Goroutines | 56059 |

Jira issue: CRDB-41033

**Comment by yuzefovich** [comment]
dup of #105257
