### ISSUE TITLE
catalog: v24.1.2: referenced table × is dropped

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#128443]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5686052363/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5686052363/?referrer=webhooks_plugin)

Panic Message:

```
validate.go:548: relation × (174): referenced table × (173) is dropped
(1) keys: [sql.schema.validation_errors.write.forward_references.relation]
Wraps: (2) keys: [sql.schema.validation_errors.write.forward_references.relation]
Wraps: (3) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate.(*validationErrorAccumulator).decorate
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate/validate.go:247
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate.(*validationErrorAccumulator).Report
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate/validate.go:182
  | [...repeated from below...]
Wraps: (4) relation × (174)
Wraps: (5) assertion failure
Wraps: (6) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/tabledesc.(*wrapper).validateOutboundFK
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/tabledesc/validate.go:548
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/tabledesc.(*wrapper).ValidateForwardReferences
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/tabledesc/validate.go:204
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate.Validate.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate/validate.go:99
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate.(*validationErrorAccumulator).validateDescriptorsAtLevel
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate/validate.go:198
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate.Validate
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate/validate.go:94
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).Validate
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/validate.go:40
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).ValidateUncommittedDescriptors
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/validate.go:74
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).commitSQLTransactionInternal
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1569
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).commitSQLTransaction
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1461
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:877
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:145
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:3457
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:144
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2292
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2297
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2214
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:965
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommands
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:253
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).serveImpl.func3
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:997
  | runtime.goexit
  | 	src/runtime/asm_amd64.s:1695
Wraps: (7) referenced table × (173) is dropped
Error types: (1) *telemetrykeys.withTelemetry (2) *telemetrykeys.withTelemetry (3) *withstack.withStack (4) *errutil.withPrefix (5) *assert.withAssertionFailure (6) *withstack.withStack (7) *errutil.leafError
-- report composition:
*errutil.leafError: referenced table × (173) is dropped
validate.go:548: *withstack.withStack (top exception)
*assert.withAssertionFailure
*errutil.withPrefix: relation × (174)
validate.go:247: *withstack.withStack (1)
*telemetrykeys.withTelemetry: sql.schema.validation_errors.write.forward_references.relation
*telemetrykeys.withTelemetry: sql.schema.validation_errors.write.forward_references.relation
(check the extra data payloads)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_amd64.s#L1694-L1696](src/runtime/asm_amd64.s#L1694-L1696)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/pgwire/server.go#L996-L998](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/pgwire/server.go#L996-L998)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/pgwire/conn.go#L252-L254](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/pgwire/conn.go#L252-L254)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor.go#L964-L966](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor.go#L964-L966)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor.go#L2213-L2215](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor.go#L2213-L2215)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor.go#L2296-L2298](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor.go#L2296-L2298)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor.go#L2291-L2293](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor.go#L2291-L2293)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor_exec.go#L143-L145](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor_exec.go#L143-L145)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor_exec.go#L3456-L3458](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor_exec.go#L3456-L3458)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor_exec.go#L144-L146](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor_exec.go#L144-L146)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor_exec.go#L876-L878](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor_exec.go#L876-L878)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor_exec.go#L1460-L1462](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor_exec.go#L1460-L1462)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor_exec.go#L1568-L1570](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor_exec.go#L1568-L1570)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/catalog/descs/validate.go#L73-L75](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/catalog/descs/validate.go#L73-L75)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/catalog/descs/validate.go#L39-L41](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/catalog/descs/validate.go#L39-L41)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/catalog/internal/validate/validate.go#L93-L95](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/catalog/internal/validate/validate.go#L93-L95)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/catalog/internal/validate/validate.go#L197-L199](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/catalog/internal/validate/validate.go#L197-L199)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/catalog/internal/validate/validate.go#L98-L100](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/catalog/internal/validate/validate.go#L98-L100)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/catalog/tabledesc/validate.go#L203-L205](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/catalog/tabledesc/validate.go#L203-L205)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/catalog/internal/validate/validate.go#L181-L183](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/catalog/internal/validate/validate.go#L181-L183)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/catalog/internal/validate/validate.go#L246-L248](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/catalog/internal/validate/validate.go#L246-L248)
[src/runtime/asm_amd64.s#L1694-L1696](src/runtime/asm_amd64.s#L1694-L1696)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/pgwire/server.go#L996-L998](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/pgwire/server.go#L996-L998)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/pgwire/conn.go#L252-L254](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/pgwire/conn.go#L252-L254)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor.go#L964-L966](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor.go#L964-L966)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor.go#L2213-L2215](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor.go#L2213-L2215)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor.go#L2296-L2298](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor.go#L2296-L2298)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor.go#L2291-L2293](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor.go#L2291-L2293)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor_exec.go#L143-L145](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor_exec.go#L143-L145)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor_exec.go#L3456-L3458](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor_exec.go#L3456-L3458)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor_exec.go#L144-L146](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor_exec.go#L144-L146)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor_exec.go#L876-L878](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor_exec.go#L876-L878)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor_exec.go#L1460-L1462](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor_exec.go#L1460-L1462)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor_exec.go#L1568-L1570](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor_exec.go#L1568-L1570)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/catalog/descs/validate.go#L73-L75](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/catalog/descs/validate.go#L73-L75)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/catalog/descs/validate.go#L39-L41](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/catalog/descs/validate.go#L39-L41)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/catalog/internal/validate/validate.go#L93-L95](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/catalog/internal/validate/validate.go#L93-L95)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/catalog/internal/validate/validate.go#L197-L199](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/catalog/internal/validate/validate.go#L197-L199)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/catalog/internal/validate/validate.go#L98-L100](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/catalog/internal/validate/validate.go#L98-L100)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/catalog/tabledesc/validate.go#L203-L205](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/catalog/tabledesc/validate.go#L203-L205)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/catalog/tabledesc/validate.go#L547-L549](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/catalog/tabledesc/validate.go#L547-L549)
</details>

```
src/runtime/asm_amd64.s in runtime.goexit at line 1695
pkg/sql/pgwire/server.go in pkg/sql/pgwire.(*Server).serveImpl.func3 at line 997
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommands at line 253
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 965
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 2214
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 2297
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd.func1 at line 2292
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 144
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithProfiling at line 3457
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt.func1 at line 145
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 877
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).commitSQLTransaction at line 1461
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).commitSQLTransactionInternal at line 1569
pkg/sql/catalog/descs/validate.go in pkg/sql/catalog/descs.(*Collection).ValidateUncommittedDescriptors at line 74
pkg/sql/catalog/descs/validate.go in pkg/sql/catalog/descs.(*Collection).Validate at line 40
pkg/sql/catalog/internal/validate/validate.go in pkg/sql/catalog/internal/validate.Validate at line 94
pkg/sql/catalog/internal/validate/validate.go in pkg/sql/catalog/internal/validate.(*validationErrorAccumulator).validateDescriptorsAtLevel at line 198
pkg/sql/catalog/internal/validate/validate.go in pkg/sql/catalog/internal/validate.Validate.func2 at line 99
pkg/sql/catalog/tabledesc/validate.go in pkg/sql/catalog/tabledesc.(*wrapper).ValidateForwardReferences at line 204
pkg/sql/catalog/internal/validate/validate.go in pkg/sql/catalog/internal/validate.(*validationErrorAccumulator).Report at line 182
pkg/sql/catalog/internal/validate/validate.go in pkg/sql/catalog/internal/validate.(*validationErrorAccumulator).decorate at line 247
src/runtime/asm_amd64.s in runtime.goexit at line 1695
pkg/sql/pgwire/server.go in pkg/sql/pgwire.(*Server).serveImpl.func3 at line 997
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommands at line 253
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 965
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 2214
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 2297
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd.func1 at line 2292
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 144
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithProfiling at line 3457
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt.func1 at line 145
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 877
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).commitSQLTransaction at line 1461
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).commitSQLTransactionInternal at line 1569
pkg/sql/catalog/descs/validate.go in pkg/sql/catalog/descs.(*Collection).ValidateUncommittedDescriptors at line 74
pkg/sql/catalog/descs/validate.go in pkg/sql/catalog/descs.(*Collection).Validate at line 40
pkg/sql/catalog/internal/validate/validate.go in pkg/sql/catalog/internal/validate.Validate at line 94
pkg/sql/catalog/internal/validate/validate.go in pkg/sql/catalog/internal/validate.(*validationErrorAccumulator).validateDescriptorsAtLevel at line 198
pkg/sql/catalog/internal/validate/validate.go in pkg/sql/catalog/internal/validate.Validate.func2 at line 99
pkg/sql/catalog/tabledesc/validate.go in pkg/sql/catalog/tabledesc.(*wrapper).ValidateForwardReferences at line 204
pkg/sql/catalog/tabledesc/validate.go in pkg/sql/catalog/tabledesc.(*wrapper).validateOutboundFK at line 548
```

### Tags

| Tag | Value |
| --- | --- |
| Command | mt start-sql |
| Environment | v24.1.2 |
| Go Version | go1.22.3 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v24.1.2-2-g5a68aaa15d7 |
| Cockroach SHA | 5a68aaa15d7044e394b93b7ca78c8ddb7fcee150 |
| # of CPUs | 32 |
| # of Goroutines | 312 |

Jira issue: CRDB-41017

**Comment by fqazi** [comment]
Not enough information to reproduce this closing this for now
