### ISSUE TITLE
testing: daily benchmark results are nearly unusable

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#12845]
Two problems:

1. the benchmark tests have been failing for multiple weeks now but the benchmark build log does not clearly indicate why.

2. the TC output embeds the raw HTML of the benchmark results, making the numeric output exceedingly hard to understand by the human. 

Example here:
![schermafdruk_2017-01-11_10-08-47](https://cloud.githubusercontent.com/assets/642886/21842362/b942aef4-d7e6-11e6-891b-a586e8c2147e.png)

**Comment by jordanlewis** [comment]
Opened #12850 to track the reason for the failing tests.

Our intern Will wrote a visualization for the benchmarks, but it hasn't been getting updated. It's available here: http://benchmark-stats.s3-website-us-west-2.amazonaws.com/

**Comment by cuongdo** [comment]
@jordanlewis are you planning to work on this for 1.1?

**Comment by tschottdorf** [comment]
Isn't @tamird working on (something related to) this?

**Comment by tamird** [comment]
This is stale; we no longer upload any of that stuff, the benchmarks run on a single TC machine.
