### ISSUE TITLE
beta-20170112

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#12849]
The candidate SHA is 5651988b49083f42182eaffd4d41328827aba1f6.
Deployment status is: pushed to `delta`, `gamma`, `indigo`, and `rho`

[Release process checklist](https://github.com/cockroachdb/cockroach/wiki/Release-Process)
- [x] Check and verify cluster status
- [x] Tag release and push tag
- [x] [Trigger release build](https://teamcity.cockroachdb.com/viewType.html?buildTypeId=Cockroach_MergeToMaster)
- [x] Check and verify binaries
- [x] Announce version to the registration cluster - see internal production instructions
- [x] Update homebrew
- [x] Update docs
- [ ] External communications for release

**Comment by jseldess** [comment]
Everything's done but external communication, @swatikumar16 and @jess-edwards. 

Release notes are here: https://www.cockroachlabs.com/docs/beta-20170112.html

**Comment by jseldess** [comment]
@swatikumar16, I saw the release note email go out. If you've posted to the forum, too, you can close this.

**Comment by bdarnell** [comment]
https://forum.cockroachlabs.com/t/release-notes-for-beta-20170112/410
