### ISSUE TITLE
acceptance: TestDockerCLI failures

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#12853]
Some rearranging of the code in cli/start.go as part of https://github.com/cockroachdb/cockroach/pull/12743 exposed some failures in TestDockerCLI, which runs all the interactive CLI tests against a server in a docker container.

With the changes in the PR, `TestDockerCLI/test_missing_log_output.tcl` fails with propEvalKV turned off due to the server's queues starting up and beginning to log before the "CockroachDB node starting" message gets printed. However, this seems like an ordering that's totally valid before my change as well. It seems as though we need to set the minimum log level to FATAL (or NONE) to avoid the potential ordering issue (which I've done in #12743).

With propEvalKV turned on, the test fails 100% of the time when run against master, due to the "running with experimental support for proposer-evaluated KV, see #10431" message that gets logged from some `storage` package-level code. I'd assume that for this we should avoid doing any logging from package init code (before the logger can be properly set up).

Additionally, the fact that this fails consistently locally also makes me suspect that failures in the underlying tests aren't being properly handled, since if they were then everything would be failing in teamcity.

@knz

**Comment by knz** [comment]
Can we spend a little time today to look at the error case? Also I'd need to understand whether you want to fix this before you can merge #12743.
