### ISSUE TITLE
Debug zip redaction is broken in 24.1

### ISSUE THREAD

**Issue by smcvey** [cockroachdb/cockroach#128591]
**Describe the problem**

Attempting to take a debug zip with any 24.1 binary fails, leading to an incomplete debug.zip that captures no logs from any of the nodes.  Instead, an error message is produced and the debug capture fails when it tries to capture the `system.lease` table:

**To Reproduce**

Standard 24.1 cluster, run:

```
cockroach debug zip debug.zip --redact
```

The debug will begin but fails here:

```
[cluster] retrieving SQL data for system.job_info: done
[cluster] retrieving SQL data for system.jobs...
[cluster] retrieving SQL data for system.jobs: writing output: debug/system.jobs.txt...
[cluster] retrieving SQL data for system.jobs: done
ERROR: requested redacted query for table system.lease, but no non-sensitive columns defined
Failed running "debug zip"
```

**Expected behavior**

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version: 24.1.[0-3]

**Additional context**
Customers who wish to send redacted debug zips to support when on 24.1 are not able to.

Jira issue: CRDB-41093

Epic CRDB-32134

**Comment by dhartunian** [comment]
will be resolved via: https://github.com/cockroachdb/cockroach/pull/122906

**Comment by dhartunian** [comment]
fixed via https://github.com/cockroachdb/cockroach/pull/122906
