### ISSUE TITLE
Sentry: error.go:61: unexpected error from the vectorized engine: bad message
(1)
Wraps: (2)
Wraps: (3) assertion failure
Wraps: (4)
  | (opaque error wrapper)
  | type name: github.com/cockroachdb/er...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#128685]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5695170256/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5695170256/?referrer=webhooks_plugin)

Panic Message:

```
error.go:61: unexpected error from the vectorized engine: bad message
(1)
Wraps: (2)
Wraps: (3) assertion failure
Wraps: (4)
  | (opaque error wrapper)
  | type name: github.com/cockroachdb/errors/withstack/*withstack.withStack
  | reportable 0:
  |
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:61
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:770
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.InternalError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:267
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils.HandleErrorFromDiskQueue
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils/utils.go:289
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk.(*hashBasedPartitioner).partitionBatch
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk/hash_based_partitioner.go:398
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk.(*hashBasedPartitioner).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk/hash_based_partitioner.go:463
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk.(*diskSpillerBase).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk/disk_spiller.go:223
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecbase.(*simpleProjectOp).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecbase/simple_project.go:124
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*UnorderedDistinct).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/unordered_distinct.go:100
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk.(*diskSpillerBase).Next.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk/disk_spiller.go:202
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:135
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk.(*diskSpillerBase).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk/disk_spiller.go:200
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*HashRouter).processNextBatch
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/routers.go:667
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*HashRouter).Run.func1.1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/routers.go:591
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:135
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*HashRouter).Run.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/routers.go:629
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:135
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*HashRouter).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/routers.go:586
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlowCreator).setupRouter.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:831
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlowCreator).setupRouter.(*vectorizedFlowCreator).accumulateAsyncComponent.func2.1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:734
  | runtime.goexit
  | 	src/runtime/asm_amd64.s:1695
Wraps: (5) unexpected error from the vectorized engine
Wraps: (6) bad message
  | -- cause hidden behind barrier
  | bad message
  | (1)
  |   | (opaque error wrapper)
  |   | type name: github.com/cockroachdb/errors/withstack/*withstack.withStack
  |   | reportable 0:
  |   |
  |   | github.com/cockroachdb/pebble/vfs.(*syncingFile).maybeSync
  |   | 	github.com/cockroachdb/pebble/vfs/external/com_github_cockroachdb_pebble/vfs/syncing_file.go:150
  |   | github.com/cockroachdb/pebble/vfs.(*syncingFile).Write
  |   | 	github.com/cockroachdb/pebble/vfs/external/com_github_cockroachdb_pebble/vfs/syncing_file.go:70
  |   | github.com/cockroachdb/cockroach/pkg/sql/colcontainer.(*diskQueueWriter).compressAndFlush
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colcontainer/diskqueue.go:124
  |   | github.com/cockroachdb/cockroach/pkg/sql/colcontainer.(*diskQueue).writeFooterAndFlush
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colcontainer/diskqueue.go:565
  |   | github.com/cockroachdb/cockroach/pkg/sql/colcontainer.(*diskQueue).Enqueue
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colcontainer/diskqueue.go:649
  |   | github.com/cockroachdb/cockroach/pkg/sql/colcontainer.(*PartitionedDiskQueue).Enqueue
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colcontainer/partitionedqueue.go:268
  |   | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk.(*hashBasedPartitioner).partitionBatch
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk/hash_based_partitioner.go:397
  |   | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk.(*hashBasedPartitioner).Next
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk/hash_based_partitioner.go:463
  |   | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk.(*diskSpillerBase).Next
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk/disk_spiller.go:223
  |   | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecbase.(*simpleProjectOp).Next
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecbase/simple_project.go:124
  |   | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*UnorderedDistinct).Next
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/unordered_distinct.go:100
  |   | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk.(*diskSpillerBase).Next.func1
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk/disk_spiller.go:202
  |   | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:135
  |   | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk.(*diskSpillerBase).Next
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk/disk_spiller.go:200
  |   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*HashRouter).processNextBatch
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/routers.go:667
  |   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*HashRouter).Run.func1.1
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/routers.go:591
  |   | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:135
  |   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*HashRouter).Run.func1
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/routers.go:629
  |   | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:135
  |   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*HashRouter).Run
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/routers.go:586
  |   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlowCreator).setupRouter.func1
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:831
  |   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlowCreator).setupRouter.(*vectorizedFlowCreator).accumulateAsyncComponent.func2.1
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:734
  |   | runtime.goexit
  |   | 	src/runtime/asm_amd64.s:1695
  | Wraps: (2) bad message
  | Error types: (1) *errbase.opaqueWrapper (2) syscall.Errno
Error types: (1) *colexecerror.notInternalError (2) *colexecerror.notInternalError (3) *assert.withAssertionFailure (4) *errbase.opaqueWrapper (5) *errutil.withPrefix (6) *barriers.barrierErr
-- report composition:
*barriers.barrierErr: details for github.com/cockroachdb/errors/withstack/*withstack.withStack:::
*errutil.withPrefix: unexpected error from the vectorized engine
error.go:61: *withstack.withStack (top exception)
*assert.withAssertionFailure
*colexecerror.notInternalError
*colexecerror.notInternalError
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_amd64.s#L1694-L1696](src/runtime/asm_amd64.s#L1694-L1696)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/sql/colflow/vectorized_flow.go#L733-L735](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/sql/colflow/vectorized_flow.go#L733-L735)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/sql/colflow/vectorized_flow.go#L830-L832](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/sql/colflow/vectorized_flow.go#L830-L832)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/sql/colflow/routers.go#L585-L587](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/sql/colflow/routers.go#L585-L587)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/sql/colexecerror/error.go#L134-L136](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/sql/colexecerror/error.go#L134-L136)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/sql/colflow/routers.go#L628-L630](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/sql/colflow/routers.go#L628-L630)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/sql/colexecerror/error.go#L134-L136](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/sql/colexecerror/error.go#L134-L136)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/sql/colflow/routers.go#L590-L592](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/sql/colflow/routers.go#L590-L592)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/sql/colflow/routers.go#L666-L668](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/sql/colflow/routers.go#L666-L668)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/sql/colexec/colexecdisk/disk_spiller.go#L199-L201](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/sql/colexec/colexecdisk/disk_spiller.go#L199-L201)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/sql/colexecerror/error.go#L134-L136](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/sql/colexecerror/error.go#L134-L136)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/sql/colexec/colexecdisk/disk_spiller.go#L201-L203](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/sql/colexec/colexecdisk/disk_spiller.go#L201-L203)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/sql/colexec/unordered_distinct.go#L99-L101](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/sql/colexec/unordered_distinct.go#L99-L101)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/sql/colexec/colexecbase/simple_project.go#L123-L125](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/sql/colexec/colexecbase/simple_project.go#L123-L125)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/sql/colexec/colexecdisk/disk_spiller.go#L222-L224](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/sql/colexec/colexecdisk/disk_spiller.go#L222-L224)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/sql/colexec/colexecdisk/hash_based_partitioner.go#L462-L464](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/sql/colexec/colexecdisk/hash_based_partitioner.go#L462-L464)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/sql/colexec/colexecdisk/hash_based_partitioner.go#L397-L399](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/sql/colexec/colexecdisk/hash_based_partitioner.go#L397-L399)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/sql/colexec/colexecutils/utils.go#L288-L290](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/sql/colexec/colexecutils/utils.go#L288-L290)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/sql/colexecerror/error.go#L266-L268](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/sql/colexecerror/error.go#L266-L268)
[GOROOT/src/runtime/panic.go#L769-L771](GOROOT/src/runtime/panic.go#L769-L771)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/sql/colexecerror/error.go#L60-L62](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/sql/colexecerror/error.go#L60-L62)
</details>

```
src/runtime/asm_amd64.s in runtime.goexit at line 1695
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlowCreator).setupRouter.(*vectorizedFlowCreator).accumulateAsyncComponent.func2.1 at line 734
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlowCreator).setupRouter.func1 at line 831
pkg/sql/colflow/routers.go in pkg/sql/colflow.(*HashRouter).Run at line 586
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 135
pkg/sql/colflow/routers.go in pkg/sql/colflow.(*HashRouter).Run.func1 at line 629
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 135
pkg/sql/colflow/routers.go in pkg/sql/colflow.(*HashRouter).Run.func1.1 at line 591
pkg/sql/colflow/routers.go in pkg/sql/colflow.(*HashRouter).processNextBatch at line 667
pkg/sql/colexec/colexecdisk/disk_spiller.go in pkg/sql/colexec/colexecdisk.(*diskSpillerBase).Next at line 200
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 135
pkg/sql/colexec/colexecdisk/disk_spiller.go in pkg/sql/colexec/colexecdisk.(*diskSpillerBase).Next.func1 at line 202
pkg/sql/colexec/unordered_distinct.go in pkg/sql/colexec.(*UnorderedDistinct).Next at line 100
pkg/sql/colexec/colexecbase/simple_project.go in pkg/sql/colexec/colexecbase.(*simpleProjectOp).Next at line 124
pkg/sql/colexec/colexecdisk/disk_spiller.go in pkg/sql/colexec/colexecdisk.(*diskSpillerBase).Next at line 223
pkg/sql/colexec/colexecdisk/hash_based_partitioner.go in pkg/sql/colexec/colexecdisk.(*hashBasedPartitioner).Next at line 463
pkg/sql/colexec/colexecdisk/hash_based_partitioner.go in pkg/sql/colexec/colexecdisk.(*hashBasedPartitioner).partitionBatch at line 398
pkg/sql/colexec/colexecutils/utils.go in pkg/sql/colexec/colexecutils.HandleErrorFromDiskQueue at line 289
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.InternalError at line 267
GOROOT/src/runtime/panic.go in runtime.gopanic at line 770
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1 at line 61
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v24.1.2 |
| Go Version | go1.22.3 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v24.1.2 |
| Cockroach SHA | 7e81be6de75205c3d08b0d8dcc6ca188306abc27 |
| # of CPUs | 8 |
| # of Goroutines | 637 |

Jira issue: CRDB-41148

**Comment by yuzefovich** [comment]
unactionable
