### ISSUE TITLE
Restore error message points to obsolete document and version is wrong

### ISSUE THREAD

**Issue by benbardin** [cockroachdb/cockroach#128611]
When a customer attempts to restore a backup and encounters an error, the error message references a document for the wrong version, in addition to showing the wrong version.

Customer attempts to restore a backup taken from 23.1 and attempts to restore into 24.2, which according to our docs is not supported ([Restoring Backups Across Versions](https://www.cockroachlabs.com/docs/v24.1/restoring-backups-across-versions) ).

The error however, shows an obscure minimum restorable version (see below) and it references documentation for a version the user does not have and is not using (22.2)

```
ERROR: backup from version 23.1 is older than the minimum restorable version 1000024.1
HINT: refer to our documentation about restoring across versions:
https://www.cockroachlabs.com/docs/v22.2/restoring-backups-across-versions.html 
The ask is to fix the above so the correct minimum restorable version is shown (instead of 1000024.1 ) and provide the link specific to the version the customer is using and not an old version (22.2).
```

See also https://cockroachlabs.atlassian.net/browse/CRDB-40559

Jira issue: CRDB-41104

**Comment by benbardin** [comment]
We likely can't do anything about the old link, but I do wonder about minimum restorable version.

**Comment by msbutler** [comment]
someone was running master. not an issue.

**Comment by dt** [comment]
Looks like we want to replace "v22.2" with "stable" in these two places:

* restore_planning.go:1658
* restore_planning.go:1662
