### ISSUE TITLE
Sentry: error.go:30: pebble/table: invalid table 016239 (checksum mismatch at 0/17365)
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:770
  | github.co...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#128869]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5707545378/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5707545378/?referrer=webhooks_plugin)

Panic Message:

```
error.go:30: pebble/table: invalid table 016239 (checksum mismatch at 0/17365)
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:770
  | github.com/cockroachdb/cockroach/pkg/storage.(*pebbleIterator).destroy
  | 	github.com/cockroachdb/cockroach/pkg/storage/pebble_iterator.go:1040
  | github.com/cockroachdb/cockroach/pkg/storage.(*pebbleIterator).Close
  | 	github.com/cockroachdb/cockroach/pkg/storage/pebble_iterator.go:362
  | [...repeated from below...]
Wraps: (2) forced error mark
  | ×
  | github.com/cockroachdb/errors/withstack/*withstack.withStack::
Wraps: (3) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/pebble/internal/base.CorruptionErrorf
  | 	github.com/cockroachdb/pebble/internal/base/external/com_github_cockroachdb_pebble/internal/base/error.go:30
  | github.com/cockroachdb/pebble/sstable.checkChecksum
  | 	github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader.go:556
  | github.com/cockroachdb/pebble/sstable.(*Reader).readBlock
  | 	github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader.go:675
  | github.com/cockroachdb/pebble/sstable.(*singleLevelIterator).loadBlock
  | 	github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader_iter_single_lvl.go:462
  | github.com/cockroachdb/pebble/sstable.(*singleLevelIterator).seekGEHelper
  | 	github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader_iter_single_lvl.go:755
  | github.com/cockroachdb/pebble/sstable.(*singleLevelIterator).SeekGE
  | 	github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader_iter_single_lvl.go:665
  | github.com/cockroachdb/pebble.(*levelIter).SeekGE
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/level_iter.go:708
  | github.com/cockroachdb/pebble.(*mergingIter).seekGE
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go:1045
  | github.com/cockroachdb/pebble.(*mergingIter).SeekGE
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go:1093
  | github.com/cockroachdb/pebble.(*Iterator).SeekGEWithLimit
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/iterator.go:1347
  | github.com/cockroachdb/pebble.(*Iterator).SeekGE
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/iterator.go:1251
  | github.com/cockroachdb/cockroach/pkg/storage.(*pebbleIterator).SeekEngineKeyGE
  | 	github.com/cockroachdb/cockroach/pkg/storage/pebble_iterator.go:386
  | github.com/cockroachdb/cockroach/pkg/storage.ClearRangeWithHeuristic.func1
  | 	github.com/cockroachdb/cockroach/pkg/storage/engine.go:1624
  | github.com/cockroachdb/cockroach/pkg/storage.ClearRangeWithHeuristic
  | 	github.com/cockroachdb/cockroach/pkg/storage/engine.go:1703
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/kvstorage.ClearRangeData
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/kvstorage/destroy.go:92
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/kvstorage.DestroyReplica
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/kvstorage/destroy.go:124
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).destroyRaftMuLocked
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_destroy.go:134
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).removeInitializedReplicaRaftMuLocked
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_remove_replica.go:186
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).removeReplicaRaftMuLocked
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_remove_replica.go:65
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).HandleRaftResponse.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:578
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:337
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).HandleRaftResponse
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:531
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*RaftTransport).processQueue.func1.1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/raft_transport.go:674
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*RaftTransport).processQueue.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/raft_transport.go:678
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:485
  | runtime.goexit
  | 	src/runtime/asm_amd64.s:1695
Wraps: (4) pebble/table: invalid table 016239 (checksum mismatch at 0/17365)
Error types: (1) *withstack.withStack (2) *markers.withMark (3) *withstack.withStack (4) *errutil.leafError
-- report composition:
*errutil.leafError: pebble/table: invalid table 016239 (checksum mismatch at 0/17365)
error.go:30: *withstack.withStack (top exception)
*markers.withMark
panic.go:770: *withstack.withStack (1)
(check the extra data payloads)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_amd64.s#L1694-L1696](src/runtime/asm_amd64.s#L1694-L1696)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/util/stop/stopper.go#L484-L486](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/util/stop/stopper.go#L484-L486)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/kv/kvserver/pkg/kv/kvserver/raft_transport.go#L677-L679](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/kv/kvserver/pkg/kv/kvserver/raft_transport.go#L677-L679)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/kv/kvserver/pkg/kv/kvserver/raft_transport.go#L673-L675](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/kv/kvserver/pkg/kv/kvserver/raft_transport.go#L673-L675)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L530-L532](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L530-L532)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/util/stop/stopper.go#L336-L338](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/util/stop/stopper.go#L336-L338)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L577-L579](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L577-L579)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/kv/kvserver/pkg/kv/kvserver/store_remove_replica.go#L64-L66](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/kv/kvserver/pkg/kv/kvserver/store_remove_replica.go#L64-L66)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/kv/kvserver/pkg/kv/kvserver/store_remove_replica.go#L185-L187](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/kv/kvserver/pkg/kv/kvserver/store_remove_replica.go#L185-L187)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/kv/kvserver/pkg/kv/kvserver/replica_destroy.go#L133-L135](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/kv/kvserver/pkg/kv/kvserver/replica_destroy.go#L133-L135)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/kv/kvserver/kvstorage/destroy.go#L123-L125](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/kv/kvserver/kvstorage/destroy.go#L123-L125)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/kv/kvserver/kvstorage/destroy.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/kv/kvserver/kvstorage/destroy.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/storage/engine.go#L1702-L1704](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/storage/engine.go#L1702-L1704)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/storage/engine.go#L1637-L1639](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/storage/engine.go#L1637-L1639)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/storage/pebble_iterator.go#L361-L363](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/storage/pebble_iterator.go#L361-L363)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/storage/pebble_iterator.go#L1039-L1041](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/storage/pebble_iterator.go#L1039-L1041)
[GOROOT/src/runtime/panic.go#L769-L771](GOROOT/src/runtime/panic.go#L769-L771)
[src/runtime/asm_amd64.s#L1694-L1696](src/runtime/asm_amd64.s#L1694-L1696)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/util/stop/stopper.go#L484-L486](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/util/stop/stopper.go#L484-L486)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/kv/kvserver/pkg/kv/kvserver/raft_transport.go#L677-L679](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/kv/kvserver/pkg/kv/kvserver/raft_transport.go#L677-L679)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/kv/kvserver/pkg/kv/kvserver/raft_transport.go#L673-L675](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/kv/kvserver/pkg/kv/kvserver/raft_transport.go#L673-L675)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L530-L532](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L530-L532)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/util/stop/stopper.go#L336-L338](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/util/stop/stopper.go#L336-L338)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L577-L579](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L577-L579)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/kv/kvserver/pkg/kv/kvserver/store_remove_replica.go#L64-L66](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/kv/kvserver/pkg/kv/kvserver/store_remove_replica.go#L64-L66)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/kv/kvserver/pkg/kv/kvserver/store_remove_replica.go#L185-L187](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/kv/kvserver/pkg/kv/kvserver/store_remove_replica.go#L185-L187)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/kv/kvserver/pkg/kv/kvserver/replica_destroy.go#L133-L135](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/kv/kvserver/pkg/kv/kvserver/replica_destroy.go#L133-L135)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/kv/kvserver/kvstorage/destroy.go#L123-L125](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/kv/kvserver/kvstorage/destroy.go#L123-L125)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/kv/kvserver/kvstorage/destroy.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/kv/kvserver/kvstorage/destroy.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/storage/engine.go#L1702-L1704](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/storage/engine.go#L1702-L1704)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/storage/engine.go#L1623-L1625](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/storage/engine.go#L1623-L1625)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/storage/pebble_iterator.go#L385-L387](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/storage/pebble_iterator.go#L385-L387)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/iterator.go#L1250-L1252](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/iterator.go#L1250-L1252)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/iterator.go#L1346-L1348](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/iterator.go#L1346-L1348)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go#L1092-L1094](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go#L1092-L1094)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go#L1044-L1046](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go#L1044-L1046)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/level_iter.go#L707-L709](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/level_iter.go#L707-L709)
[github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader_iter_single_lvl.go#L664-L666](github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader_iter_single_lvl.go#L664-L666)
[github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader_iter_single_lvl.go#L754-L756](github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader_iter_single_lvl.go#L754-L756)
[github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader_iter_single_lvl.go#L461-L463](github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader_iter_single_lvl.go#L461-L463)
[github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader.go#L674-L676](github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader.go#L674-L676)
[github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader.go#L555-L557](github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader.go#L555-L557)
[github.com/cockroachdb/pebble/internal/base/external/com_github_cockroachdb_pebble/internal/base/error.go#L29-L31](github.com/cockroachdb/pebble/internal/base/external/com_github_cockroachdb_pebble/internal/base/error.go#L29-L31)
</details>

```
src/runtime/asm_amd64.s in runtime.goexit at line 1695
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 485
pkg/kv/kvserver/pkg/kv/kvserver/raft_transport.go in pkg/kv/kvserver.(*RaftTransport).processQueue.func1 at line 678
pkg/kv/kvserver/pkg/kv/kvserver/raft_transport.go in pkg/kv/kvserver.(*RaftTransport).processQueue.func1.1 at line 674
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).HandleRaftResponse at line 531
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunTaskWithErr at line 337
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).HandleRaftResponse.func1 at line 578
pkg/kv/kvserver/pkg/kv/kvserver/store_remove_replica.go in pkg/kv/kvserver.(*Store).removeReplicaRaftMuLocked at line 65
pkg/kv/kvserver/pkg/kv/kvserver/store_remove_replica.go in pkg/kv/kvserver.(*Store).removeInitializedReplicaRaftMuLocked at line 186
pkg/kv/kvserver/pkg/kv/kvserver/replica_destroy.go in pkg/kv/kvserver.(*Replica).destroyRaftMuLocked at line 134
pkg/kv/kvserver/kvstorage/destroy.go in pkg/kv/kvserver/kvstorage.DestroyReplica at line 124
pkg/kv/kvserver/kvstorage/destroy.go in pkg/kv/kvserver/kvstorage.ClearRangeData at line 92
pkg/storage/engine.go in pkg/storage.ClearRangeWithHeuristic at line 1703
pkg/storage/engine.go in pkg/storage.ClearRangeWithHeuristic.func1 at line 1638
pkg/storage/pebble_iterator.go in pkg/storage.(*pebbleIterator).Close at line 362
pkg/storage/pebble_iterator.go in pkg/storage.(*pebbleIterator).destroy at line 1040
GOROOT/src/runtime/panic.go in runtime.gopanic at line 770
src/runtime/asm_amd64.s in runtime.goexit at line 1695
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 485
pkg/kv/kvserver/pkg/kv/kvserver/raft_transport.go in pkg/kv/kvserver.(*RaftTransport).processQueue.func1 at line 678
pkg/kv/kvserver/pkg/kv/kvserver/raft_transport.go in pkg/kv/kvserver.(*RaftTransport).processQueue.func1.1 at line 674
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).HandleRaftResponse at line 531
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunTaskWithErr at line 337
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).HandleRaftResponse.func1 at line 578
pkg/kv/kvserver/pkg/kv/kvserver/store_remove_replica.go in pkg/kv/kvserver.(*Store).removeReplicaRaftMuLocked at line 65
pkg/kv/kvserver/pkg/kv/kvserver/store_remove_replica.go in pkg/kv/kvserver.(*Store).removeInitializedReplicaRaftMuLocked at line 186
pkg/kv/kvserver/pkg/kv/kvserver/replica_destroy.go in pkg/kv/kvserver.(*Replica).destroyRaftMuLocked at line 134
pkg/kv/kvserver/kvstorage/destroy.go in pkg/kv/kvserver/kvstorage.DestroyReplica at line 124
pkg/kv/kvserver/kvstorage/destroy.go in pkg/kv/kvserver/kvstorage.ClearRangeData at line 92
pkg/storage/engine.go in pkg/storage.ClearRangeWithHeuristic at line 1703
pkg/storage/engine.go in pkg/storage.ClearRangeWithHeuristic.func1 at line 1624
pkg/storage/pebble_iterator.go in pkg/storage.(*pebbleIterator).SeekEngineKeyGE at line 386
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/iterator.go in github.com/cockroachdb/pebble.(*Iterator).SeekGE at line 1251
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/iterator.go in github.com/cockroachdb/pebble.(*Iterator).SeekGEWithLimit at line 1347
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go in github.com/cockroachdb/pebble.(*mergingIter).SeekGE at line 1093
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go in github.com/cockroachdb/pebble.(*mergingIter).seekGE at line 1045
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/level_iter.go in github.com/cockroachdb/pebble.(*levelIter).SeekGE at line 708
github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader_iter_single_lvl.go in github.com/cockroachdb/pebble/sstable.(*singleLevelIterator).SeekGE at line 665
github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader_iter_single_lvl.go in github.com/cockroachdb/pebble/sstable.(*singleLevelIterator).seekGEHelper at line 755
github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader_iter_single_lvl.go in github.com/cockroachdb/pebble/sstable.(*singleLevelIterator).loadBlock at line 462
github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader.go in github.com/cockroachdb/pebble/sstable.(*Reader).readBlock at line 675
github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader.go in github.com/cockroachdb/pebble/sstable.checkChecksum at line 556
github.com/cockroachdb/pebble/internal/base/external/com_github_cockroachdb_pebble/internal/base/error.go in github.com/cockroachdb/pebble/internal/base.CorruptionErrorf at line 30
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v24.1.3 |
| Go Version | go1.22.5 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v24.1.3 |
| Cockroach SHA | 9e10212477fde97f55ea4fff01797288c836575c |
| # of CPUs | 4 |
| # of Goroutines | 232 |

Jira issue: CRDB-41242

**Comment by yuzefovich** [comment]
unactionable
