### ISSUE TITLE
Add a unit test for LDR cross-cluster writes

### ISSUE THREAD

**Issue by navsetlur** [cockroachdb/cockroach#128814]
While we're confident it works, having a correctness test for LWW semantics would help when we start adding some KV code for conflicts. 

Jira issue: CRDB-41219

**Comment by stevendanna** [comment]
My idea for this was to start with something rather explicit. Namely, we insert rows via an `querier` interface that has an `InsertRow` and `DeleteRow` method.

At the time we call these functions, there are a few LWW relevant facts:

-  Row from the rangefeed event's mvcc_timestamp (MVCC Timestamp of the committe row)
- Whether PrevRow from the rangefeed event is nil or not
- Current row in the db's mvcc_timestamp
- Current row in the db's crdb_replication_origin_timestamp (mvcc_timestamp _of the original rangefeed event_)

Thus, it would be nice to have a test that produced all of the relevant combinations of these facts, ran `InsertRow` or `DeleteRow` and then asserted which row won at the end of the day.

The main cases are (crossed with the state of the previous row):
- remote row older than local crdb_replication_origin_timestamp
- remote row newer than local crdb_replication_origin_timestamp
- remote row older than local mvcc_timetamp (when crdb_replication_origin_timestamp is null)
- remote row newer than local mvcc_timstamp (when crdb_replication_origin_timestamp is null)

There are also the "equal to" cases, which are not handled particularly well at the moment but might be worth including.

Note that all of the interesting facts are easily controllable by us in the test when we construct the state except for the local mvcc_timetamp.  There are two routes we could use here: (1) we mostly just care about whether we are greater than or less than the local mvcc_timetamp, so we could write some rows and then read back the timestamp via SQL (at least if we ignore the delete cases for now. To get the mvcc timestamp of a delete we will need to query KV directly) or (2) we could directly write  at known timestamps using AddSSTable.
