### ISSUE TITLE
stats: v24.1.1: index out of range when decoding histogram tuple value with UUID element

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#128876]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5707953216/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5707953216/?referrer=webhooks_plugin)

Panic Message:

```
panic.go:770: runtime error: slice bounds out of range [:16] with capacity 5
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:770
  | runtime.goPanicSliceAcap
  | 	GOROOT/src/runtime/panic.go:140
  | github.com/cockroachdb/cockroach/pkg/util/encoding.DecodeUntaggedUUIDValue
  | 	github.com/cockroachdb/cockroach/pkg/util/encoding/encoding.go:3135
  | github.com/cockroachdb/cockroach/pkg/sql/rowenc/valueside.DecodeUntaggedDatum
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowenc/valueside/decode.go:186
  | github.com/cockroachdb/cockroach/pkg/sql/rowenc/valueside.Decode
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowenc/valueside/decode.go:45
  | github.com/cockroachdb/cockroach/pkg/sql/rowenc/valueside.decodeTuple
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowenc/valueside/tuple.go:53
  | github.com/cockroachdb/cockroach/pkg/sql/rowenc/valueside.DecodeUntaggedDatum
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowenc/valueside/decode.go:242
  | github.com/cockroachdb/cockroach/pkg/sql/rowenc/valueside.Decode
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowenc/valueside/decode.go:45
  | github.com/cockroachdb/cockroach/pkg/sql/stats.DecodeUpperBound
  | 	github.com/cockroachdb/cockroach/pkg/sql/stats/pkg/sql/stats/histogram.go:117
  | github.com/cockroachdb/cockroach/pkg/sql/stats.DecodeHistogramBuckets
  | 	github.com/cockroachdb/cockroach/pkg/sql/stats/pkg/sql/stats/stats_cache.go:711
  | github.com/cockroachdb/cockroach/pkg/sql/stats.(*TableStatisticsCache).parseStats
  | 	github.com/cockroachdb/cockroach/pkg/sql/stats/pkg/sql/stats/stats_cache.go:675
  | github.com/cockroachdb/cockroach/pkg/sql/stats.(*TableStatisticsCache).getTableStatsFromDB
  | 	github.com/cockroachdb/cockroach/pkg/sql/stats/pkg/sql/stats/stats_cache.go:822
  | github.com/cockroachdb/cockroach/pkg/sql/stats.(*TableStatisticsCache).addCacheEntryLocked.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/stats/pkg/sql/stats/stats_cache.go:432
  | github.com/cockroachdb/cockroach/pkg/sql/stats.(*TableStatisticsCache).addCacheEntryLocked
  | 	github.com/cockroachdb/cockroach/pkg/sql/stats/pkg/sql/stats/stats_cache.go:434
  | github.com/cockroachdb/cockroach/pkg/sql/stats.(*TableStatisticsCache).getTableStatsFromCache
  | 	github.com/cockroachdb/cockroach/pkg/sql/stats/pkg/sql/stats/stats_cache.go:339
  | github.com/cockroachdb/cockroach/pkg/sql/stats.(*Refresher).maybeRefreshStats
  | 	github.com/cockroachdb/cockroach/pkg/sql/stats/pkg/sql/stats/automatic_stats.go:811
  | github.com/cockroachdb/cockroach/pkg/sql/stats.(*Refresher).Start.func1.1
  | 	github.com/cockroachdb/cockroach/pkg/sql/stats/pkg/sql/stats/automatic_stats.go:536
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:485
  | runtime.goexit
  | 	src/runtime/asm_amd64.s:1695
Wraps: (2) runtime error: slice bounds out of range [:16] with capacity 5
Error types: (1) *withstack.withStack (2) runtime.boundsError
-- report composition:
runtime.boundsError
panic.go:770: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_amd64.s#L1694-L1696](src/runtime/asm_amd64.s#L1694-L1696)
[https://github.com/cockroachdb/cockroach/blob/484f8e2f4d3cb23582416944d79eab72ff42a6a1/pkg/util/stop/stopper.go#L484-L486](https://github.com/cockroachdb/cockroach/blob/484f8e2f4d3cb23582416944d79eab72ff42a6a1/pkg/util/stop/stopper.go#L484-L486)
[https://github.com/cockroachdb/cockroach/blob/484f8e2f4d3cb23582416944d79eab72ff42a6a1/pkg/sql/stats/pkg/sql/stats/automatic_stats.go#L535-L537](https://github.com/cockroachdb/cockroach/blob/484f8e2f4d3cb23582416944d79eab72ff42a6a1/pkg/sql/stats/pkg/sql/stats/automatic_stats.go#L535-L537)
[https://github.com/cockroachdb/cockroach/blob/484f8e2f4d3cb23582416944d79eab72ff42a6a1/pkg/sql/stats/pkg/sql/stats/automatic_stats.go#L810-L812](https://github.com/cockroachdb/cockroach/blob/484f8e2f4d3cb23582416944d79eab72ff42a6a1/pkg/sql/stats/pkg/sql/stats/automatic_stats.go#L810-L812)
[https://github.com/cockroachdb/cockroach/blob/484f8e2f4d3cb23582416944d79eab72ff42a6a1/pkg/sql/stats/pkg/sql/stats/stats_cache.go#L338-L340](https://github.com/cockroachdb/cockroach/blob/484f8e2f4d3cb23582416944d79eab72ff42a6a1/pkg/sql/stats/pkg/sql/stats/stats_cache.go#L338-L340)
[https://github.com/cockroachdb/cockroach/blob/484f8e2f4d3cb23582416944d79eab72ff42a6a1/pkg/sql/stats/pkg/sql/stats/stats_cache.go#L433-L435](https://github.com/cockroachdb/cockroach/blob/484f8e2f4d3cb23582416944d79eab72ff42a6a1/pkg/sql/stats/pkg/sql/stats/stats_cache.go#L433-L435)
[https://github.com/cockroachdb/cockroach/blob/484f8e2f4d3cb23582416944d79eab72ff42a6a1/pkg/sql/stats/pkg/sql/stats/stats_cache.go#L431-L433](https://github.com/cockroachdb/cockroach/blob/484f8e2f4d3cb23582416944d79eab72ff42a6a1/pkg/sql/stats/pkg/sql/stats/stats_cache.go#L431-L433)
[https://github.com/cockroachdb/cockroach/blob/484f8e2f4d3cb23582416944d79eab72ff42a6a1/pkg/sql/stats/pkg/sql/stats/stats_cache.go#L821-L823](https://github.com/cockroachdb/cockroach/blob/484f8e2f4d3cb23582416944d79eab72ff42a6a1/pkg/sql/stats/pkg/sql/stats/stats_cache.go#L821-L823)
[https://github.com/cockroachdb/cockroach/blob/484f8e2f4d3cb23582416944d79eab72ff42a6a1/pkg/sql/stats/pkg/sql/stats/stats_cache.go#L674-L676](https://github.com/cockroachdb/cockroach/blob/484f8e2f4d3cb23582416944d79eab72ff42a6a1/pkg/sql/stats/pkg/sql/stats/stats_cache.go#L674-L676)
[https://github.com/cockroachdb/cockroach/blob/484f8e2f4d3cb23582416944d79eab72ff42a6a1/pkg/sql/stats/pkg/sql/stats/stats_cache.go#L710-L712](https://github.com/cockroachdb/cockroach/blob/484f8e2f4d3cb23582416944d79eab72ff42a6a1/pkg/sql/stats/pkg/sql/stats/stats_cache.go#L710-L712)
[https://github.com/cockroachdb/cockroach/blob/484f8e2f4d3cb23582416944d79eab72ff42a6a1/pkg/sql/stats/pkg/sql/stats/histogram.go#L116-L118](https://github.com/cockroachdb/cockroach/blob/484f8e2f4d3cb23582416944d79eab72ff42a6a1/pkg/sql/stats/pkg/sql/stats/histogram.go#L116-L118)
[https://github.com/cockroachdb/cockroach/blob/484f8e2f4d3cb23582416944d79eab72ff42a6a1/pkg/sql/rowenc/valueside/decode.go#L44-L46](https://github.com/cockroachdb/cockroach/blob/484f8e2f4d3cb23582416944d79eab72ff42a6a1/pkg/sql/rowenc/valueside/decode.go#L44-L46)
[https://github.com/cockroachdb/cockroach/blob/484f8e2f4d3cb23582416944d79eab72ff42a6a1/pkg/sql/rowenc/valueside/decode.go#L241-L243](https://github.com/cockroachdb/cockroach/blob/484f8e2f4d3cb23582416944d79eab72ff42a6a1/pkg/sql/rowenc/valueside/decode.go#L241-L243)
[https://github.com/cockroachdb/cockroach/blob/484f8e2f4d3cb23582416944d79eab72ff42a6a1/pkg/sql/rowenc/valueside/tuple.go#L52-L54](https://github.com/cockroachdb/cockroach/blob/484f8e2f4d3cb23582416944d79eab72ff42a6a1/pkg/sql/rowenc/valueside/tuple.go#L52-L54)
[https://github.com/cockroachdb/cockroach/blob/484f8e2f4d3cb23582416944d79eab72ff42a6a1/pkg/sql/rowenc/valueside/decode.go#L44-L46](https://github.com/cockroachdb/cockroach/blob/484f8e2f4d3cb23582416944d79eab72ff42a6a1/pkg/sql/rowenc/valueside/decode.go#L44-L46)
[https://github.com/cockroachdb/cockroach/blob/484f8e2f4d3cb23582416944d79eab72ff42a6a1/pkg/sql/rowenc/valueside/decode.go#L185-L187](https://github.com/cockroachdb/cockroach/blob/484f8e2f4d3cb23582416944d79eab72ff42a6a1/pkg/sql/rowenc/valueside/decode.go#L185-L187)
[https://github.com/cockroachdb/cockroach/blob/484f8e2f4d3cb23582416944d79eab72ff42a6a1/pkg/util/encoding/encoding.go#L3134-L3136](https://github.com/cockroachdb/cockroach/blob/484f8e2f4d3cb23582416944d79eab72ff42a6a1/pkg/util/encoding/encoding.go#L3134-L3136)
[GOROOT/src/runtime/panic.go#L139-L141](GOROOT/src/runtime/panic.go#L139-L141)
[GOROOT/src/runtime/panic.go#L769-L771](GOROOT/src/runtime/panic.go#L769-L771)
</details>

```
src/runtime/asm_amd64.s in runtime.goexit at line 1695
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 485
pkg/sql/stats/pkg/sql/stats/automatic_stats.go in pkg/sql/stats.(*Refresher).Start.func1.1 at line 536
pkg/sql/stats/pkg/sql/stats/automatic_stats.go in pkg/sql/stats.(*Refresher).maybeRefreshStats at line 811
pkg/sql/stats/pkg/sql/stats/stats_cache.go in pkg/sql/stats.(*TableStatisticsCache).getTableStatsFromCache at line 339
pkg/sql/stats/pkg/sql/stats/stats_cache.go in pkg/sql/stats.(*TableStatisticsCache).addCacheEntryLocked at line 434
pkg/sql/stats/pkg/sql/stats/stats_cache.go in pkg/sql/stats.(*TableStatisticsCache).addCacheEntryLocked.func1 at line 432
pkg/sql/stats/pkg/sql/stats/stats_cache.go in pkg/sql/stats.(*TableStatisticsCache).getTableStatsFromDB at line 822
pkg/sql/stats/pkg/sql/stats/stats_cache.go in pkg/sql/stats.(*TableStatisticsCache).parseStats at line 675
pkg/sql/stats/pkg/sql/stats/stats_cache.go in pkg/sql/stats.DecodeHistogramBuckets at line 711
pkg/sql/stats/pkg/sql/stats/histogram.go in pkg/sql/stats.DecodeUpperBound at line 117
pkg/sql/rowenc/valueside/decode.go in pkg/sql/rowenc/valueside.Decode at line 45
pkg/sql/rowenc/valueside/decode.go in pkg/sql/rowenc/valueside.DecodeUntaggedDatum at line 242
pkg/sql/rowenc/valueside/tuple.go in pkg/sql/rowenc/valueside.decodeTuple at line 53
pkg/sql/rowenc/valueside/decode.go in pkg/sql/rowenc/valueside.Decode at line 45
pkg/sql/rowenc/valueside/decode.go in pkg/sql/rowenc/valueside.DecodeUntaggedDatum at line 186
pkg/util/encoding/encoding.go in pkg/util/encoding.DecodeUntaggedUUIDValue at line 3135
GOROOT/src/runtime/panic.go in runtime.goPanicSliceAcap at line 140
GOROOT/src/runtime/panic.go in runtime.gopanic at line 770
```

### Tags

| Tag | Value |
| --- | --- |
| Command | start-single-node |
| Environment | v24.1.1 |
| Go Version | go1.22.3 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v24.1.1 |
| Cockroach SHA | 484f8e2f4d3cb23582416944d79eab72ff42a6a1 |
| # of CPUs | 2 |
| # of Goroutines | 358 |

Jira issue: CRDB-41247

**Comment by yuzefovich** [comment]
dup of #137106
