### ISSUE TITLE
testing: goroutine leak in TestCopyTransaction

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#12884]
Found in https://teamcity.cockroachdb.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=116224#_focus=8824

8 leaked goroutines.

cc @mjibson

**Comment by knz** [comment]
(failing with prop-eval kv enabled)

**Comment by mjibson** [comment]
Note: this may get fixed by https://github.com/cockroachdb/cockroach/pull/12723 because it improves the COPY protocol to send a command complete message.

**Comment by tamird** [comment]
How come goroutines are leaking, even in the failure case?

**Comment by tamird** [comment]
Welp, I couldn't reproduce this, so closing.
