### ISSUE TITLE
aws terraform failures due to lack of VPC

### ISSUE THREAD

**Issue by scode** [cockroachdb/cockroach#12896]
I've attempted to use the supplied terraform files with AWS in a couple of envs. In both cases, they failed due to VPC related issues.

I'm not entirely sure if this is because it only works for classic EC2 and not VPC-only, or if there is something unusual about my setup. However, in order to make cluster creation work I had to apply this patch:

https://gist.github.com/scode/e939eca78113ff377df1a835a10a4e26

I'm not entirely sure how generally applicable this is, so I'm not submitting a PR with that change (at least not in its current state).

I may return to this after more testing/validation, but for the moment wanted to file it for searchability. Possible error seen by a user in this situation when attempting `terraform apply`:

```
* aws_security_group.default: Error creating Security Group: VPCIdNotSpecified: No default VPC for this user
	status code: 400, request id: REDACTED
```

In another environment, I got a different error pertaining to firewall rules:

```
* aws_security_group.default: Error authorizing security group egress rules: InvalidParameterValue: Only Amazon VPC security groups may be used with this operation.
	status code: 400, request id: REDACTED
```

The need for `associate_public_ip_address` may be environmental (not sure). The change to specifying security group by ID instead of name is inherent with AWS (with VPCs apparently you need to use ids). The rest is hopefully obvious.

Note that the patch probably breaks things for users for which the current .tf files work, and the changes are meant to assume you want to drop your cluster into a pre-existing VPC. It may be more appropriate for demonstration purposes to set up the VPC as a managed resource, which *should* then allow it to be used by anyone as long as their account allows creation of VPCs (which I *think* is all accounts).

**Comment by mberhault** [comment]
I haven't touched this in a little while, but I seem to recall that a default VPC existed when you were using 'VPC only' mode. we made use of that rather than having to create an extra one.

However, it would make sense to create a custom VPC, especially in an environment with many things other than cockroach running. @cuongdo: you're probably the latest to poke at this. Does this seem reasonable?

**Comment by dianasaur323** [comment]
@cuongdo I'm going to move this out into the 1.1 milestone. It seems like something we should at least try for usability reasons, but not a 1.0 priority given how close we are to release.

**Comment by mytototo** [comment]
Any news regarding a Terraform module to provision a secure CockroachDB cluster with multiple nodes on AWS?

**Comment by bdarnell** [comment]
Closing since we no longer provide terraform configs. We have a new [cloudformation template](https://github.com/cockroachdb/cockroachdb-cloudformation) which works with VPC but not (yet) multiple regions.
