### ISSUE TITLE
raft: leaders stepping down when switching joint configurations need to de-fortify

### ISSUE THREAD

**Issue by arulajmani** [cockroachdb/cockroach#129098]
**Describe the problem**

A leader steps down because it's either demoted or being removed from a raft group:

https://github.com/cockroachdb/cockroach/blob/ec66ae778100724b11f1b8978c915be1bcea390c/pkg/raft/raft.go#L2099-L2112

Assuming the leader was fortified and its store continues to maintain healthy `StoreLiveness` support from all other nodes in the cluster (i.e. the happy case), none of the other peers in the raft group will call an election. One of them needs to.

cc @nvanbenschoten 

Jira issue: CRDB-41372

Epic CRDB-37522

**Comment by arulajmani** [comment]
@nvanbenschoten, @miraradeva, @iskettaneh spent a fair few hours over the last couple of days talking about this issue. We decided that adding a new, explicit, `MsgDefortifyLeader`. Then, when a leader steps down, it can track track some state to remember its stint as a fortified leader in a prior term and send out a periodic `MsgDefortifyLeader` to all followers that were providing it fortification support. 

When a leader sends out a `MsgDefortifyLeader` it should de-fortify followers at all terms <= the term specified in the message. We should do so periodically (we discussed doing this in the `tickElection` method) until the leader knows it's safe to stop (discussed later). 

We'll also need to change the vote rejection condition a little bit. Say a follower is supporting a fortified leader at `T_fortified`. Currently, it will reject a Msg{Pre,}VoteRequest`. However, we'll need to modify this condition to also take into consideration the term of the log entry with which the candidate is campaigning with (call this `T_log_entry`) -- in particular,  if `T_log_entry > T_fortified`, then we know that a leader was elected at `T_log_entry`. This must mean that `T_fortified` has ended. Followers can use this information to conceptually de-fortify and grant their votes to other candidates.

Lastly, there's the question, when can the outgoing leader stop sending out `MsgDefortifyLeader` request? The condition is:

1. The leader sees a new log entry has been committed by a leader at a higher term. As the entry has been committed, we know it won't be rolled back by a future leader, which means future candidates will be able to conceptually de-fortify any followers that still support the outgoing leader in store liveness, if needed.
2. Optionally, followers can send back a `MsgDefortifyLeaderResp` indicating they've de-fortified successfully. Once all followers have de-fortified successfully, the outgoing leader can stop attempting to send out the `MsgDefortifyLeader`.

**Comment by nvanbenschoten** [comment]
> to all followers that were providing it fortification support.

A leader doesn't actually know which followers were providing it fortification support, as some may have provided it support without the leader having received the `MsgFortifyLeaderResp` message. So I think it just needs to send this to all followers, unconditionally.

> which means future candidates will be able to conceptually de-fortify any followers that still support the outgoing leader in store liveness

Specifically, any future candidate that is able to win the election will be guaranteed to have a LogTerm that is capable of defortifying any followers that still support the outgoing leader.
