### ISSUE TITLE
Seg fault while bench marking for optimum concurrency level

### ISSUE THREAD

**Issue by ravikumarsureshbabu** [cockroachdb/cockroach#12918]
Hello @andreimatei ,

I am raising the bug as you suggested in the chat box.

My Experiemnt
I am trying to benchmark cockroach DB to check optimum concurrency level at which it can give maximum transactions per second with less aborts or retries. 

Procedure

I have a Bank application that creates given number of accounts in database and runs given amount of transfers with given concurrency level.
This application is triggered by another program sequencially for different concurrency levels. 

Problem

While Bank application is triggered for different concurrency levels, cockroach DB non deterministically fails with the same error as

panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x110 pc=0xbcc796]

goroutine 50589 [running]:
panic(0x16042e0, 0xc4200100b0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc420420360)
	/home/ravi/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:180 +0x6e
panic(0x16042e0, 0xc4200100b0)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).Rollback(0x0, 0x15cf3e0, 0xc420e80ee0)
	/home/ravi/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:395 +0x26
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).CleanupOnError(0x0, 0x21cdf00, 0xc420e80f20)
	/home/ravi/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:325 +0x40
github.com/cockroachdb/cockroach/pkg/sql.(*txnState).updateStateAndCleanupOnErr(0xc4205bc048, 0x21cdf00, 0xc420e80f20, 0xc4203daa00)
	/home/ravi/go/src/github.com/cockroachdb/cockroach/pkg/sql/session.go:400 +0xc1
github.com/cockroachdb/cockroach/pkg/sql.(*Session).Finish(0xc4205bc000)
	/home/ravi/go/src/github.com/cockroachdb/cockroach/pkg/sql/session.go:188 +0x12f
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).finish(0xc4204f2180)
	/home/ravi/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:152 +0x7f
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn(0xc4201a3400, 0x21e5f20, 0xc421fa4000, 0x21ce800, 0xc4216042d0)
	/home/ravi/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:242 +0x652
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func8.1(0x21e5f20, 0xc421fa4000)
	/home/ravi/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:471 +0x5b
github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1(0xc420420360, 0xc420134290, 0x21e5f20, 0xc421fa4000, 0xc42021f820)
	/home/ravi/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:136 +0x95
created by github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith
	/home/ravi/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:138 +0x277

**My Code** 
[benchmark.zip](https://github.com/cockroachdb/cockroach/files/705280/benchmark.zip)

**Bank application : benchmark/main. go** 
**To run for multiple concurrences : benchmark/dynamicConcurrencyServer/server.go**

**To run the experiment**
 1) Go to benchmark/dynamicConcurrencyServer/
2) go build
3) command to run : ./dynamicConcurrencyServer -start=< start concurrency level > -max=< end concurrency level > -step=< concurrency steps >

Please let me know if you need more information. Thanks for the help. I appreciate it.

**Comment by ravikumarsureshbabu** [comment]
Sorry for the inconvenience. I had changed /cockroachdb/cockroach-go/crdb/tx.go I forgot to give it to you. Please find the attachment. 
[tx.go.zip](https://github.com/cockroachdb/cockroach/files/705590/tx.go.zip)

**Comment by andreimatei** [comment]
After some intense work with Ravi, this proved to be #9879, fixed in October. Ravi's checkout was old.
