### ISSUE TITLE
storage: per-category metrics not displaying in the db console

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/cockroach#129159]
In 24.2, we have per-category disk write metrics.

However, on `master`, these metrics no longer display.

24.2 (from a production cluster running `v24.2.0-beta.1`):

<img width="980" alt="Screenshot 2024-08-16 at 3 18 55 PM" src="https://github.com/user-attachments/assets/54317b0a-03e8-4940-800b-a08b945f9666">

From a DRT cluster, running 2f0b0399a5c9656bdf8a417d0ab57e4eb1ae0f64, we don't see any metrics:

<img width="980" alt="Screenshot 2024-08-16 at 3 33 52 PM" src="https://github.com/user-attachments/assets/38f98885-5658-4050-a837-1c70329baeb6">

On `master` (446bc365f4c24230ed36c3e3202d47e5adbd6f69), only the log file writes seem to display:

<img width="980" alt="Screenshot 2024-08-16 at 3 32 50 PM" src="https://github.com/user-attachments/assets/5ba32daf-90ae-41c7-ac23-d79a1eb5faea">

Jira issue: CRDB-41404

**Comment by nicktrav** [comment]
I noticed we landed #127266 recently, and it looks like this might have done it.

Before:

<img width="980" alt="Screenshot 2024-08-16 at 3 56 52 PM" src="https://github.com/user-attachments/assets/e5b1a994-446c-4e13-b1df-0e29dad765c0">

After that change:

<img width="980" alt="Screenshot 2024-08-16 at 3 58 55 PM" src="https://github.com/user-attachments/assets/33a08a14-bb3d-446f-bb18-f27568a379ff">

cc: @aadityasondhi - mind taking a look at this?

**Comment by aadityasondhi** [comment]
That's odd, we might be lacking some testing here, I'll take a look.

FWIW, it was working well at some point in that PR. https://github.com/cockroachdb/cockroach/pull/127266#issuecomment-2236855567
