### ISSUE TITLE
sql: Can't drop table with self-referential foreign key

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#12916]
When a table has a foreign key pointing to itself, we disallow dropping that table (without `CASCADE`). We should see that the FK points to the table being dropped and allow the drop. (this occurs in the sqlalchemy test suite)

```
root@:26257> create table test.a (user_id int primary key, parent_id int, constraint fk foreign key (parent_id) references test.a (user_id));
CREATE TABLE
root@:26257> drop table test.a;
pq: "a" is referenced by foreign key from table "a"
```

**Comment by dt** [comment]
Huh, we're supposed to build the set of tables being dropped first and then check fks only to those not in the set to avoid this (and the general case of multi-table cycles too), so something has regressed. I'll take a look today.
