### ISSUE TITLE
Sentry: replica_closedts.go:263: log.Fatal: side-transport update saw closed timestamp regression on r21: (lai=1873, ts=1723964613.016349632,0) -> (lai=656, ts=1723964627.058274929,0) (1) attached sta...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#129188]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5726275679/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5726275679/?referrer=webhooks_plugin)

Panic Message:

```
replica_closedts.go:263: log.Fatal: side-transport update saw closed timestamp regression on r21: (lai=1873, ts=1723964613.016349632,0) -> (lai=656, ts=1723964627.058274929,0)
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*sidetransportAccess).assertNoRegression
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_closedts.go:263
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*sidetransportAccess).forward
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_closedts.go:237
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*sidetransportAccess).get
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_closedts.go:334
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).getCurrentClosedTimestampLocked
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_follower_read.go:144
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).GetCurrentClosedTimestamp
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_follower_read.go:157
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).updateReplicationGauges.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store.go:3147
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*storeReplicaVisitor).Visit
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store.go:527
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).updateReplicationGauges
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store.go:3071
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).computeMetrics
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store.go:3309
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).ComputeMetricsPeriodically
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store.go:3341
  | github.com/cockroachdb/cockroach/pkg/server.(*Node).startComputePeriodicMetrics.func1.(*Node).computeMetricsPeriodically.func1
  | 	github.com/cockroachdb/cockroach/pkg/server/node.go:972
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Stores).VisitStores.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/stores.go:149
  | github.com/cockroachdb/cockroach/pkg/util/syncutil.(*IntMap).Range
  | 	github.com/cockroachdb/cockroach/pkg/util/syncutil/int_map.go:358
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Stores).VisitStores
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/stores.go:148
  | github.com/cockroachdb/cockroach/pkg/server.(*Node).computeMetricsPeriodically
  | 	github.com/cockroachdb/cockroach/pkg/server/node.go:971
  | github.com/cockroachdb/cockroach/pkg/server.(*Node).startComputePeriodicMetrics.func1
  | 	github.com/cockroachdb/cockroach/pkg/server/node.go:956
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:484
  | runtime.goexit
  | 	src/runtime/asm_amd64.s:1650
Wraps: (2) log.Fatal: side-transport update saw closed timestamp regression on r21: (lai=1873, ts=1723964613.016349632,0) -> (lai=656, ts=1723964627.058274929,0)
Error types: (1) *withstack.withStack (2) *errutil.leafError
-- report composition:
*errutil.leafError: log.Fatal: side-transport update saw closed timestamp regression on r21: (lai=1873, ts=1723964613.016349632,0) -> (lai=656, ts=1723964627.058274929,0)
replica_closedts.go:263: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_amd64.s#L1649-L1651](src/runtime/asm_amd64.s#L1649-L1651)
[https://github.com/cockroachdb/cockroach/blob/e3276dc8c5e041aabc787bba43193e638103f31f/pkg/util/stop/stopper.go#L483-L485](https://github.com/cockroachdb/cockroach/blob/e3276dc8c5e041aabc787bba43193e638103f31f/pkg/util/stop/stopper.go#L483-L485)
[https://github.com/cockroachdb/cockroach/blob/e3276dc8c5e041aabc787bba43193e638103f31f/pkg/server/node.go#L955-L957](https://github.com/cockroachdb/cockroach/blob/e3276dc8c5e041aabc787bba43193e638103f31f/pkg/server/node.go#L955-L957)
[https://github.com/cockroachdb/cockroach/blob/e3276dc8c5e041aabc787bba43193e638103f31f/pkg/server/node.go#L970-L972](https://github.com/cockroachdb/cockroach/blob/e3276dc8c5e041aabc787bba43193e638103f31f/pkg/server/node.go#L970-L972)
[https://github.com/cockroachdb/cockroach/blob/e3276dc8c5e041aabc787bba43193e638103f31f/pkg/kv/kvserver/pkg/kv/kvserver/stores.go#L147-L149](https://github.com/cockroachdb/cockroach/blob/e3276dc8c5e041aabc787bba43193e638103f31f/pkg/kv/kvserver/pkg/kv/kvserver/stores.go#L147-L149)
[https://github.com/cockroachdb/cockroach/blob/e3276dc8c5e041aabc787bba43193e638103f31f/pkg/util/syncutil/int_map.go#L357-L359](https://github.com/cockroachdb/cockroach/blob/e3276dc8c5e041aabc787bba43193e638103f31f/pkg/util/syncutil/int_map.go#L357-L359)
[https://github.com/cockroachdb/cockroach/blob/e3276dc8c5e041aabc787bba43193e638103f31f/pkg/kv/kvserver/pkg/kv/kvserver/stores.go#L148-L150](https://github.com/cockroachdb/cockroach/blob/e3276dc8c5e041aabc787bba43193e638103f31f/pkg/kv/kvserver/pkg/kv/kvserver/stores.go#L148-L150)
[https://github.com/cockroachdb/cockroach/blob/e3276dc8c5e041aabc787bba43193e638103f31f/pkg/server/node.go#L971-L973](https://github.com/cockroachdb/cockroach/blob/e3276dc8c5e041aabc787bba43193e638103f31f/pkg/server/node.go#L971-L973)
[https://github.com/cockroachdb/cockroach/blob/e3276dc8c5e041aabc787bba43193e638103f31f/pkg/kv/kvserver/pkg/kv/kvserver/store.go#L3340-L3342](https://github.com/cockroachdb/cockroach/blob/e3276dc8c5e041aabc787bba43193e638103f31f/pkg/kv/kvserver/pkg/kv/kvserver/store.go#L3340-L3342)
[https://github.com/cockroachdb/cockroach/blob/e3276dc8c5e041aabc787bba43193e638103f31f/pkg/kv/kvserver/pkg/kv/kvserver/store.go#L3308-L3310](https://github.com/cockroachdb/cockroach/blob/e3276dc8c5e041aabc787bba43193e638103f31f/pkg/kv/kvserver/pkg/kv/kvserver/store.go#L3308-L3310)
[https://github.com/cockroachdb/cockroach/blob/e3276dc8c5e041aabc787bba43193e638103f31f/pkg/kv/kvserver/pkg/kv/kvserver/store.go#L3070-L3072](https://github.com/cockroachdb/cockroach/blob/e3276dc8c5e041aabc787bba43193e638103f31f/pkg/kv/kvserver/pkg/kv/kvserver/store.go#L3070-L3072)
[https://github.com/cockroachdb/cockroach/blob/e3276dc8c5e041aabc787bba43193e638103f31f/pkg/kv/kvserver/pkg/kv/kvserver/store.go#L526-L528](https://github.com/cockroachdb/cockroach/blob/e3276dc8c5e041aabc787bba43193e638103f31f/pkg/kv/kvserver/pkg/kv/kvserver/store.go#L526-L528)
[https://github.com/cockroachdb/cockroach/blob/e3276dc8c5e041aabc787bba43193e638103f31f/pkg/kv/kvserver/pkg/kv/kvserver/store.go#L3146-L3148](https://github.com/cockroachdb/cockroach/blob/e3276dc8c5e041aabc787bba43193e638103f31f/pkg/kv/kvserver/pkg/kv/kvserver/store.go#L3146-L3148)
[https://github.com/cockroachdb/cockroach/blob/e3276dc8c5e041aabc787bba43193e638103f31f/pkg/kv/kvserver/pkg/kv/kvserver/replica_follower_read.go#L156-L158](https://github.com/cockroachdb/cockroach/blob/e3276dc8c5e041aabc787bba43193e638103f31f/pkg/kv/kvserver/pkg/kv/kvserver/replica_follower_read.go#L156-L158)
[https://github.com/cockroachdb/cockroach/blob/e3276dc8c5e041aabc787bba43193e638103f31f/pkg/kv/kvserver/pkg/kv/kvserver/replica_follower_read.go#L143-L145](https://github.com/cockroachdb/cockroach/blob/e3276dc8c5e041aabc787bba43193e638103f31f/pkg/kv/kvserver/pkg/kv/kvserver/replica_follower_read.go#L143-L145)
[https://github.com/cockroachdb/cockroach/blob/e3276dc8c5e041aabc787bba43193e638103f31f/pkg/kv/kvserver/pkg/kv/kvserver/replica_closedts.go#L333-L335](https://github.com/cockroachdb/cockroach/blob/e3276dc8c5e041aabc787bba43193e638103f31f/pkg/kv/kvserver/pkg/kv/kvserver/replica_closedts.go#L333-L335)
[https://github.com/cockroachdb/cockroach/blob/e3276dc8c5e041aabc787bba43193e638103f31f/pkg/kv/kvserver/pkg/kv/kvserver/replica_closedts.go#L236-L238](https://github.com/cockroachdb/cockroach/blob/e3276dc8c5e041aabc787bba43193e638103f31f/pkg/kv/kvserver/pkg/kv/kvserver/replica_closedts.go#L236-L238)
[https://github.com/cockroachdb/cockroach/blob/e3276dc8c5e041aabc787bba43193e638103f31f/pkg/kv/kvserver/pkg/kv/kvserver/replica_closedts.go#L262-L264](https://github.com/cockroachdb/cockroach/blob/e3276dc8c5e041aabc787bba43193e638103f31f/pkg/kv/kvserver/pkg/kv/kvserver/replica_closedts.go#L262-L264)
</details>

```
src/runtime/asm_amd64.s in runtime.goexit at line 1650
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 484
pkg/server/node.go in pkg/server.(*Node).startComputePeriodicMetrics.func1 at line 956
pkg/server/node.go in pkg/server.(*Node).computeMetricsPeriodically at line 971
pkg/kv/kvserver/pkg/kv/kvserver/stores.go in pkg/kv/kvserver.(*Stores).VisitStores at line 148
pkg/util/syncutil/int_map.go in pkg/util/syncutil.(*IntMap).Range at line 358
pkg/kv/kvserver/pkg/kv/kvserver/stores.go in pkg/kv/kvserver.(*Stores).VisitStores.func1 at line 149
pkg/server/node.go in pkg/server.(*Node).startComputePeriodicMetrics.func1.(*Node).computeMetricsPeriodically.func1 at line 972
pkg/kv/kvserver/pkg/kv/kvserver/store.go in pkg/kv/kvserver.(*Store).ComputeMetricsPeriodically at line 3341
pkg/kv/kvserver/pkg/kv/kvserver/store.go in pkg/kv/kvserver.(*Store).computeMetrics at line 3309
pkg/kv/kvserver/pkg/kv/kvserver/store.go in pkg/kv/kvserver.(*Store).updateReplicationGauges at line 3071
pkg/kv/kvserver/pkg/kv/kvserver/store.go in pkg/kv/kvserver.(*storeReplicaVisitor).Visit at line 527
pkg/kv/kvserver/pkg/kv/kvserver/store.go in pkg/kv/kvserver.(*Store).updateReplicationGauges.func1 at line 3147
pkg/kv/kvserver/pkg/kv/kvserver/replica_follower_read.go in pkg/kv/kvserver.(*Replica).GetCurrentClosedTimestamp at line 157
pkg/kv/kvserver/pkg/kv/kvserver/replica_follower_read.go in pkg/kv/kvserver.(*Replica).getCurrentClosedTimestampLocked at line 144
pkg/kv/kvserver/pkg/kv/kvserver/replica_closedts.go in pkg/kv/kvserver.(*sidetransportAccess).get at line 334
pkg/kv/kvserver/pkg/kv/kvserver/replica_closedts.go in pkg/kv/kvserver.(*sidetransportAccess).forward at line 237
pkg/kv/kvserver/pkg/kv/kvserver/replica_closedts.go in pkg/kv/kvserver.(*sidetransportAccess).assertNoRegression at line 263
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v23.2.4 |
| Go Version | go1.21.8 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.2.4 |
| Cockroach SHA | e3276dc8c5e041aabc787bba43193e638103f31f |
| # of CPUs | 2 |
| # of Goroutines | 389 |

Jira issue: CRDB-41427

**Comment by yuzefovich** [comment]
unactionable
