### ISSUE TITLE
CockroachDB may experience sudden high latency across the entire cluster during write operations.

### ISSUE THREAD

**Issue by wuhuua** [cockroachdb/cockroach#129210]
**Describe the problem**
I deployed a cluster using self-compiled CockroachDB v24.2.0-dev which has 50 nodes. When trying to start a write batch to the cluster, I found that CockroachDB may experience sudden high latency across the entire cluster during write operations.
<img width="1084" alt="企业微信截图_61ff9d75-b93b-4e40-8d23-20efae39de88" src="https://github.com/user-attachments/assets/dbc7bfa6-0192-4351-92a8-c1aadc2fa277">

**There's no network problem during my writing process, so I wonder why these sudden high latency occurs.**

My steps to run the cluster and write process:

1. Set up CockroachDB cluster
`/symmetricdbserver start --certs-dir=/local/certs --store=/symmetricdb/symmetricdb-data --listen-addr {{env "attr.unique.network.ip-address"}}:26259 --http-addr 0.0.0.0:8081 --join 0.symmetricdb-cluster-secure.service.consul:26259`
2. Send SQL ... / CLI command ...
Write batch SQL is executing in a transaction as follows: 
```sql
# In a transaction
INSERT INTO common_controls(created_at, updated_at, deleted_at, uin, bind_new_card_errcode, final_support_bank_list,
bank_limit_priority, id)
   VALUES (_, __more__) RETURNING id, id
INSERT INTO pay_methods(created_at, updated_at, deleted_at, uin, pay_method_type, account_type, bind_serial,
bank_type, pay_method_name, logo_url, default_card_setting_state, default_favor_compose_id, account_id,
is_default_pay_method, pay_method_color_type, id)
   VALUES (_, __more__) RETURNING id, id
```

**Environment:**
 - CockroachDB version 24.2.0-dev
 - Server OS: Linux/Centos
 - Client app: Gorm

Jira issue: CRDB-41447

**Comment by DrewKimball** [comment]
Hi @wuhuua, thanks for the report. To help me investigate, it would be helpful if you could gather some information for me:
* A tsdump for the period of the workload run. You can follow the instructions [here](https://www.cockroachlabs.com/docs/v24.1/cockroach-debug-tsdump.html#generate-a-tsdump-gob-file) to collect one.
* A statement bundle for a high-latency query, which you can collect by following the instructions [here](https://www.cockroachlabs.com/docs/stable/ui-statements-page#diagnostics) and setting a latency threshold.

You can send the results to me privately via [this link](https://upload.cockroachlabs.com/u/drewk).

**Comment by wuhuua** [comment]
tsdump sent, with a detailed description

**Comment by DrewKimball** [comment]
It looks like CPU is intermittently reaching ~100% on individual nodes. KV requests to a high-utilization node are delayed, and since we're bulk-inserting, a given SQL statement is pretty likely to hit the slow node.

<img width="875" alt="Screenshot 2024-08-29 at 12 09 59 PM" src="https://github.com/user-attachments/assets/2f34db8c-6ad3-4248-ae16-79306f65fb4a">
<img width="873" alt="Screenshot 2024-08-29 at 12 10 16 PM" src="https://github.com/user-attachments/assets/30326f61-1f7a-4e74-b8eb-def001c02a12">
<img width="869" alt="Screenshot 2024-08-29 at 12 10 31 PM" src="https://github.com/user-attachments/assets/d6382af1-6c88-40db-99dc-0a3311143a80">
<img width="864" alt="Screenshot 2024-08-29 at 12 10 47 PM" src="https://github.com/user-attachments/assets/034e4f7d-87dd-46fe-a809-f9beeecf695e">

**Comment by DrewKimball** [comment]
A good next step would be to try and figure out why CPU utilization is so high on certain nodes. We should be collecting CPU profiles [automatically](https://www.cockroachlabs.com/docs/stable/automatic-cpu-profiler), which you can access via the logging directory `cockroach-data/logs/pprof_dump`. Let's grab the profiles for several different nodes to make sure we capture an interesting period.

I also have a few questions about your hardware/workload:
* Is there a single CRDB node per instance?
* How many vCPUs are there per instance?
* How many rows are inserted per statement/transaction? Does this number vary?

**Comment by mgartner** [comment]
@wuhuua I'm going to close this issue for now. Please feel free to open a new issue (or reply to this issue) if you have further questions.
