### ISSUE TITLE
kvserver: replication AC v2 integration testing

### ISSUE THREAD

**Issue by sumeerbhola** [cockroachdb/cockroach#129276]
- [x] #130186
- [x] #130187
- [x] #130431

Epic [CRDB-37515](https://cockroachlabs.atlassian.net/browse/CRDB-37515)

Jira issue: CRDB-41474

Epic CRDB-37515

**Comment by kvoli** [comment]
Filed sub-issues for the listed test suites. Also replaced this issue in the (internal) tracking sheet with the sub-issues enumerated instead.
