### ISSUE TITLE
Sentry: default_exprs.go:92: ×: process default and computed columns: failed to type check the cast of × to ×: ×(): cannot determine type of empty array. Consider casting to the desired type, for ...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#129242]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5730863262/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5730863262/?referrer=webhooks_plugin)

Panic Message:

```
default_exprs.go:92: ×: process default and computed columns: failed to type check the cast of × to ×: ×(): cannot determine type of empty array. Consider casting to the desired type, for example ARRAY[]::int[]
(1)
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/importer.readInputFiles.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/importer/read_import_base.go:304
  | github.com/cockroachdb/cockroach/pkg/sql/importer.readInputFiles
  | 	github.com/cockroachdb/cockroach/pkg/sql/importer/read_import_base.go:308
  | github.com/cockroachdb/cockroach/pkg/sql/importer.(*csvInputReader).readFiles
  | 	github.com/cockroachdb/cockroach/pkg/sql/importer/read_import_csv.go:86
  | github.com/cockroachdb/cockroach/pkg/sql/importer.runImport.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/importer/read_import_base.go:106
  | github.com/cockroachdb/cockroach/pkg/sql/importer.runImport.Group.GoCtx.func4
  | 	github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:168
  | golang.org/x/sync/errgroup.(*Group).Go.func1
  | 	golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:75
Wraps: (3) ×
Wraps: (4) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/row.NewDatumRowConverter
  | 	github.com/cockroachdb/cockroach/pkg/sql/row/row_converter.go:360
  | [...repeated from below...]
Wraps: (5) process default and computed columns
Wraps: (6) assertion failure
Wraps: (7) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/schemaexpr.MakeDefaultExprs
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/schemaexpr/default_exprs.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/row.NewDatumRowConverter
  | 	github.com/cockroachdb/cockroach/pkg/sql/row/row_converter.go:358
  | github.com/cockroachdb/cockroach/pkg/sql/importer.makeDatumConverter
  | 	github.com/cockroachdb/cockroach/pkg/sql/importer/read_import_base.go:494
  | github.com/cockroachdb/cockroach/pkg/sql/importer.(*parallelImporter).importWorker
  | 	github.com/cockroachdb/cockroach/pkg/sql/importer/read_import_base.go:702
  | github.com/cockroachdb/cockroach/pkg/sql/importer.runParallelImport.func1.1
  | 	github.com/cockroachdb/cockroach/pkg/sql/importer/read_import_base.go:599
  | github.com/cockroachdb/cockroach/pkg/util/ctxgroup.GroupWorkers.func1
  | 	github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:177
  | github.com/cockroachdb/cockroach/pkg/util/ctxgroup.GroupWorkers.Group.GoCtx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:168
  | golang.org/x/sync/errgroup.(*Group).Go.func1
  | 	golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:75
  | runtime.goexit
  | 	src/runtime/asm_amd64.s:1650
Wraps: (8) failed to type check the cast of × to ×
Wraps: (9) ×(): cannot determine type of empty array. Consider casting to the desired type, for example ARRAY[]::int[]
  | -- cause hidden behind barrier
  | ×(): cannot determine type of empty array. Consider casting to the desired type, for example ARRAY[]::int[]
  | (1) candidate pg code: 22023
  | Wraps: (2) attached stack trace
  |   -- stack trace:
  |   | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FuncExpr).TypeCheck.func1
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/type_check.go:1191
  |   | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FuncExpr).TypeCheck
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/type_check.go:1194
  |   | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.TypeCheck
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/type_check.go:339
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/schemaexpr.MakeDefaultExprs
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/schemaexpr/default_exprs.go:82
  |   | github.com/cockroachdb/cockroach/pkg/sql/row.NewDatumRowConverter
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/row/row_converter.go:358
  |   | github.com/cockroachdb/cockroach/pkg/sql/importer.makeDatumConverter
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/importer/read_import_base.go:494
  |   | github.com/cockroachdb/cockroach/pkg/sql/importer.(*parallelImporter).importWorker
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/importer/read_import_base.go:702
  |   | github.com/cockroachdb/cockroach/pkg/sql/importer.runParallelImport.func1.1
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/importer/read_import_base.go:599
  |   | github.com/cockroachdb/cockroach/pkg/util/ctxgroup.GroupWorkers.func1
  |   | 	github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:177
  |   | github.com/cockroachdb/cockroach/pkg/util/ctxgroup.GroupWorkers.Group.GoCtx.func2
  |   | 	github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:168
  |   | [...repeated from below...]
  | Wraps: (3) ×()
  | Wraps: (4) candidate pg code: 42P18
  | Wraps: (5) attached stack trace
  |   -- stack trace:
  |   | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.init
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/type_check.go:1820
  |   | runtime.doInit1
  |   | 	GOROOT/src/runtime/proc.go:6757
  |   | runtime.doInit
  |   | 	GOROOT/src/runtime/proc.go:6724
  |   | runtime.main
  |   | 	GOROOT/src/runtime/proc.go:249
  |   | runtime.goexit
  |   | 	src/runtime/asm_amd64.s:1650
  | Wraps: (6) cannot determine type of empty array. Consider casting to the desired type, for example ARRAY[]::int[]
  | Error types: (1) *pgerror.withCandidateCode (2) *withstack.withStack (3) *errutil.withPrefix (4) *pgerror.withCandidateCode (5) *withstack.withStack (6) *errutil.leafError
Error types: (1) *colexecerror.notInternalError (2) *withstack.withStack (3) *errutil.withPrefix (4) *withstack.withStack (5) *errutil.withPrefix (6) *assert.withAssertionFailure (7) *withstack.withStack (8) *errutil.withPrefix (9) *barriers.barrierErr
-- report composition:
*barriers.barrierErr: details for github.com/cockroachdb/cockroach/pkg/sql/pgwire/pgerror/*pgerror.withCandidateCode:::
*errutil.withPrefix: failed to type check the cast of × to ×
default_exprs.go:92: *withstack.withStack (top exception)
*assert.withAssertionFailure
*errutil.withPrefix: process default and computed columns
row_converter.go:360: *withstack.withStack (1)
*errutil.withPrefix: ×
read_import_base.go:304: *withstack.withStack (2)
*colexecerror.notInternalError
(check the extra data payloads)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_amd64.s#L1649-L1651](src/runtime/asm_amd64.s#L1649-L1651)
[golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go#L74-L76](golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go#L74-L76)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/util/ctxgroup/ctxgroup.go#L167-L169](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/util/ctxgroup/ctxgroup.go#L167-L169)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/importer/read_import_base.go#L105-L107](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/importer/read_import_base.go#L105-L107)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/importer/read_import_csv.go#L85-L87](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/importer/read_import_csv.go#L85-L87)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/importer/read_import_base.go#L307-L309](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/importer/read_import_base.go#L307-L309)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/importer/read_import_base.go#L303-L305](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/importer/read_import_base.go#L303-L305)
[src/runtime/asm_amd64.s#L1649-L1651](src/runtime/asm_amd64.s#L1649-L1651)
[golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go#L74-L76](golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go#L74-L76)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/util/ctxgroup/ctxgroup.go#L167-L169](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/util/ctxgroup/ctxgroup.go#L167-L169)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/util/ctxgroup/ctxgroup.go#L176-L178](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/util/ctxgroup/ctxgroup.go#L176-L178)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/importer/read_import_base.go#L598-L600](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/importer/read_import_base.go#L598-L600)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/importer/read_import_base.go#L701-L703](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/importer/read_import_base.go#L701-L703)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/importer/read_import_base.go#L493-L495](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/importer/read_import_base.go#L493-L495)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/row/row_converter.go#L359-L361](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/row/row_converter.go#L359-L361)
[src/runtime/asm_amd64.s#L1649-L1651](src/runtime/asm_amd64.s#L1649-L1651)
[golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go#L74-L76](golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go#L74-L76)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/util/ctxgroup/ctxgroup.go#L167-L169](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/util/ctxgroup/ctxgroup.go#L167-L169)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/util/ctxgroup/ctxgroup.go#L176-L178](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/util/ctxgroup/ctxgroup.go#L176-L178)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/importer/read_import_base.go#L598-L600](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/importer/read_import_base.go#L598-L600)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/importer/read_import_base.go#L701-L703](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/importer/read_import_base.go#L701-L703)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/importer/read_import_base.go#L493-L495](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/importer/read_import_base.go#L493-L495)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/row/row_converter.go#L357-L359](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/row/row_converter.go#L357-L359)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/catalog/schemaexpr/default_exprs.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/catalog/schemaexpr/default_exprs.go#L91-L93)
</details>

```
src/runtime/asm_amd64.s in runtime.goexit at line 1650
golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go in golang.org/x/sync/errgroup.(*Group).Go.func1 at line 75
pkg/util/ctxgroup/ctxgroup.go in pkg/sql/importer.runImport.Group.GoCtx.func4 at line 168
pkg/sql/importer/read_import_base.go in pkg/sql/importer.runImport.func1 at line 106
pkg/sql/importer/read_import_csv.go in pkg/sql/importer.(*csvInputReader).readFiles at line 86
pkg/sql/importer/read_import_base.go in pkg/sql/importer.readInputFiles at line 308
pkg/sql/importer/read_import_base.go in pkg/sql/importer.readInputFiles.func2 at line 304
src/runtime/asm_amd64.s in runtime.goexit at line 1650
golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go in golang.org/x/sync/errgroup.(*Group).Go.func1 at line 75
pkg/util/ctxgroup/ctxgroup.go in pkg/util/ctxgroup.GroupWorkers.Group.GoCtx.func2 at line 168
pkg/util/ctxgroup/ctxgroup.go in pkg/util/ctxgroup.GroupWorkers.func1 at line 177
pkg/sql/importer/read_import_base.go in pkg/sql/importer.runParallelImport.func1.1 at line 599
pkg/sql/importer/read_import_base.go in pkg/sql/importer.(*parallelImporter).importWorker at line 702
pkg/sql/importer/read_import_base.go in pkg/sql/importer.makeDatumConverter at line 494
pkg/sql/row/row_converter.go in pkg/sql/row.NewDatumRowConverter at line 360
src/runtime/asm_amd64.s in runtime.goexit at line 1650
golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go in golang.org/x/sync/errgroup.(*Group).Go.func1 at line 75
pkg/util/ctxgroup/ctxgroup.go in pkg/util/ctxgroup.GroupWorkers.Group.GoCtx.func2 at line 168
pkg/util/ctxgroup/ctxgroup.go in pkg/util/ctxgroup.GroupWorkers.func1 at line 177
pkg/sql/importer/read_import_base.go in pkg/sql/importer.runParallelImport.func1.1 at line 599
pkg/sql/importer/read_import_base.go in pkg/sql/importer.(*parallelImporter).importWorker at line 702
pkg/sql/importer/read_import_base.go in pkg/sql/importer.makeDatumConverter at line 494
pkg/sql/row/row_converter.go in pkg/sql/row.NewDatumRowConverter at line 358
pkg/sql/catalog/schemaexpr/default_exprs.go in pkg/sql/catalog/schemaexpr.MakeDefaultExprs at line 92
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v23.2.3 |
| Go Version | go1.21.5 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.2.3 |
| Cockroach SHA | 03498e5964c0eaa45bb5435b4c600de38d542910 |
| # of CPUs | 8 |
| # of Goroutines | 1236 |

Jira issue: CRDB-41464

**Comment by yuzefovich** [comment]
should be fixed by #125284
