### ISSUE TITLE
Sentry: logical_props_builder.go:1743: no volatility for cast ×::×
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.Build...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#129258]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5731151546/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5731151546/?referrer=webhooks_plugin)

Panic Message:

```
logical_props_builder.go:1743: no volatility for cast ×::×
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.BuildSharedProps
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/memo/logical_props_builder.go:1743
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*plpgsqlBuilder).addBarrierIfVolatile
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/plpgsql.go:1856
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*plpgsqlBuilder).addPLpgSQLAssign
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/plpgsql.go:1117
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*plpgsqlBuilder).buildPLpgSQLStatements
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/plpgsql.go:478
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*plpgsqlBuilder).buildPLpgSQLStatements
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/plpgsql.go:510
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*plpgsqlBuilder).appendPlpgSQLStmts
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/plpgsql.go:1762
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*plpgsqlBuilder).buildPLpgSQLStatements
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/plpgsql.go:572
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*plpgsqlBuilder).buildPLpgSQLStatements
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/plpgsql.go:601
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*plpgsqlBuilder).buildBlock
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/plpgsql.go:409
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*plpgsqlBuilder).buildRootBlock
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/plpgsql.go:305
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildCreateFunction.func7
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/create_function.go:400
  | github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*FoldingControl).TemporarilyDisallowStableFolds
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/norm/fold_constants_funcs.go:113
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildCreateFunction
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/create_function.go:395
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:387
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmtAtRootWithScope
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:299
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmtAtRoot
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:280
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).Build
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:259
  | github.com/cockroachdb/cockroach/pkg/sql.(*optPlanningCtx).buildReusableMemo
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:450
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).prepareUsingOptimizer
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:170
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).populatePrepared
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:344
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).prepare.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:284
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).prepare
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:289
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).addPreparedStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:122
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execPrepare
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:83
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2423
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2214
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:965
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommands
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:253
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).serveImpl.func3
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:997
  | runtime.goexit
  | 	src/runtime/asm_amd64.s:1695
Wraps: (3) no volatility for cast ×::×
Error types: (1) *assert.withAssertionFailure (2) *withstack.withStack (3) *errutil.leafError
-- report composition:
*errutil.leafError: no volatility for cast ×::×
logical_props_builder.go:1743: *withstack.withStack (top exception)
*assert.withAssertionFailure
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_amd64.s#L1694-L1696](src/runtime/asm_amd64.s#L1694-L1696)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/pgwire/server.go#L996-L998](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/pgwire/server.go#L996-L998)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/pgwire/conn.go#L252-L254](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/pgwire/conn.go#L252-L254)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor.go#L964-L966](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor.go#L964-L966)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor.go#L2213-L2215](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor.go#L2213-L2215)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor.go#L2422-L2424](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor.go#L2422-L2424)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor_prepare.go#L82-L84](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor_prepare.go#L82-L84)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor_prepare.go#L121-L123](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor_prepare.go#L121-L123)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor_prepare.go#L288-L290](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor_prepare.go#L288-L290)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor_prepare.go#L283-L285](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor_prepare.go#L283-L285)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor_prepare.go#L343-L345](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/conn_executor_prepare.go#L343-L345)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/plan_opt.go#L169-L171](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/plan_opt.go#L169-L171)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/plan_opt.go#L449-L451](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/plan_opt.go#L449-L451)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/opt/optbuilder/builder.go#L258-L260](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/opt/optbuilder/builder.go#L258-L260)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/opt/optbuilder/builder.go#L279-L281](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/opt/optbuilder/builder.go#L279-L281)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/opt/optbuilder/builder.go#L298-L300](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/opt/optbuilder/builder.go#L298-L300)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/opt/optbuilder/builder.go#L386-L388](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/opt/optbuilder/builder.go#L386-L388)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/opt/optbuilder/create_function.go#L394-L396](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/opt/optbuilder/create_function.go#L394-L396)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/opt/norm/fold_constants_funcs.go#L112-L114](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/opt/norm/fold_constants_funcs.go#L112-L114)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/opt/optbuilder/create_function.go#L399-L401](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/opt/optbuilder/create_function.go#L399-L401)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/opt/optbuilder/plpgsql.go#L304-L306](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/opt/optbuilder/plpgsql.go#L304-L306)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/opt/optbuilder/plpgsql.go#L408-L410](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/opt/optbuilder/plpgsql.go#L408-L410)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/opt/optbuilder/plpgsql.go#L600-L602](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/opt/optbuilder/plpgsql.go#L600-L602)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/opt/optbuilder/plpgsql.go#L571-L573](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/opt/optbuilder/plpgsql.go#L571-L573)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/opt/optbuilder/plpgsql.go#L1761-L1763](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/opt/optbuilder/plpgsql.go#L1761-L1763)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/opt/optbuilder/plpgsql.go#L509-L511](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/opt/optbuilder/plpgsql.go#L509-L511)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/opt/optbuilder/plpgsql.go#L477-L479](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/opt/optbuilder/plpgsql.go#L477-L479)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/opt/optbuilder/plpgsql.go#L1116-L1118](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/opt/optbuilder/plpgsql.go#L1116-L1118)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/opt/optbuilder/plpgsql.go#L1855-L1857](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/opt/optbuilder/plpgsql.go#L1855-L1857)
[https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/opt/memo/logical_props_builder.go#L1742-L1744](https://github.com/cockroachdb/cockroach/blob/5a68aaa15d7044e394b93b7ca78c8ddb7fcee150/pkg/sql/opt/memo/logical_props_builder.go#L1742-L1744)
</details>

```
src/runtime/asm_amd64.s in runtime.goexit at line 1695
pkg/sql/pgwire/server.go in pkg/sql/pgwire.(*Server).serveImpl.func3 at line 997
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommands at line 253
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 965
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 2214
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 2423
pkg/sql/conn_executor_prepare.go in pkg/sql.(*connExecutor).execPrepare at line 83
pkg/sql/conn_executor_prepare.go in pkg/sql.(*connExecutor).addPreparedStmt at line 122
pkg/sql/conn_executor_prepare.go in pkg/sql.(*connExecutor).prepare at line 289
pkg/sql/conn_executor_prepare.go in pkg/sql.(*connExecutor).prepare.func2 at line 284
pkg/sql/conn_executor_prepare.go in pkg/sql.(*connExecutor).populatePrepared at line 344
pkg/sql/plan_opt.go in pkg/sql.(*planner).prepareUsingOptimizer at line 170
pkg/sql/plan_opt.go in pkg/sql.(*optPlanningCtx).buildReusableMemo at line 450
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).Build at line 259
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).buildStmtAtRoot at line 280
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).buildStmtAtRootWithScope at line 299
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).buildStmt at line 387
pkg/sql/opt/optbuilder/create_function.go in pkg/sql/opt/optbuilder.(*Builder).buildCreateFunction at line 395
pkg/sql/opt/norm/fold_constants_funcs.go in pkg/sql/opt/norm.(*FoldingControl).TemporarilyDisallowStableFolds at line 113
pkg/sql/opt/optbuilder/create_function.go in pkg/sql/opt/optbuilder.(*Builder).buildCreateFunction.func7 at line 400
pkg/sql/opt/optbuilder/plpgsql.go in pkg/sql/opt/optbuilder.(*plpgsqlBuilder).buildRootBlock at line 305
pkg/sql/opt/optbuilder/plpgsql.go in pkg/sql/opt/optbuilder.(*plpgsqlBuilder).buildBlock at line 409
pkg/sql/opt/optbuilder/plpgsql.go in pkg/sql/opt/optbuilder.(*plpgsqlBuilder).buildPLpgSQLStatements at line 601
pkg/sql/opt/optbuilder/plpgsql.go in pkg/sql/opt/optbuilder.(*plpgsqlBuilder).buildPLpgSQLStatements at line 572
pkg/sql/opt/optbuilder/plpgsql.go in pkg/sql/opt/optbuilder.(*plpgsqlBuilder).appendPlpgSQLStmts at line 1762
pkg/sql/opt/optbuilder/plpgsql.go in pkg/sql/opt/optbuilder.(*plpgsqlBuilder).buildPLpgSQLStatements at line 510
pkg/sql/opt/optbuilder/plpgsql.go in pkg/sql/opt/optbuilder.(*plpgsqlBuilder).buildPLpgSQLStatements at line 478
pkg/sql/opt/optbuilder/plpgsql.go in pkg/sql/opt/optbuilder.(*plpgsqlBuilder).addPLpgSQLAssign at line 1117
pkg/sql/opt/optbuilder/plpgsql.go in pkg/sql/opt/optbuilder.(*plpgsqlBuilder).addBarrierIfVolatile at line 1856
pkg/sql/opt/memo/logical_props_builder.go in pkg/sql/opt/memo.BuildSharedProps at line 1743
```

### Tags

| Tag | Value |
| --- | --- |
| Command | mt start-sql |
| Environment | v24.1.2 |
| Go Version | go1.22.3 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v24.1.2-2-g5a68aaa15d7 |
| Cockroach SHA | 5a68aaa15d7044e394b93b7ca78c8ddb7fcee150 |
| # of CPUs | 16 |
| # of Goroutines | 322 |

Jira issue: CRDB-41468

**Comment by yuzefovich** [comment]
dup of #129256
