### ISSUE TITLE
spanconfig: add metrics for issues with the span config reconciliation job

### ISSUE THREAD

**Issue by arulajmani** [cockroachdb/cockroach#129339]
**Describe the problem**

Currently, whenever the `SpanConfig` job fails or retries, we simply log and try again (either on the same node or let the job bounce to a different node). See:

https://github.com/cockroachdb/cockroach/blob/e9a6d3d7c935dd347a4254729edf2db8c764dcbf/pkg/spanconfig/spanconfigjob/job.go#L211-L217

These are hard to spot; we should add metrics (counters) for both these cases. Would've been useful for [this internal escalation](https://github.com/cockroachlabs/support/issues/3061). 

Jira issue: CRDB-41502

**Comment by rafiss** [comment]
We already have these metrics, since they are created automatically by the jobs framework for each job type. See here for the metric names: https://github.com/cockroachdb/cockroach/blob/936383afc36bbf4ed341bd43ddc767326a5f9134/pkg/roachprod/opentelemetry/cockroachdb_metrics.go#L649-L660
