### ISSUE TITLE
Sentry: panic.go:770: runtime error: index out of range [825045937120] with length 2803 (1) attached stack trace   -- stack trace:   | runtime.gopanic   | 	GOROOT/src/runtime/panic.go:770   | github.c...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#129476]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5743328361/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5743328361/?referrer=webhooks_plugin)

Panic Message:

```
panic.go:770: runtime error: index out of range [825045937120] with length 2803
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:770
  | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).divideAndSendBatchToRanges.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:1798
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:770
  | runtime.goPanicIndex
  | 	GOROOT/src/runtime/panic.go:114
  | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*orderRestorationHelper).restoreOrder
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/batch.go:1047
  | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*BatchTruncationHelper).Truncate
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/batch.go:363
  | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).divideAndSendBatchToRanges
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:1900
  | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).Send
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:1238
  | github.com/cockroachdb/cockroach/pkg/kv.(*CrossRangeTxnWrapperSender).Send
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:229
  | github.com/cockroachdb/cockroach/pkg/kv.(*DB).sendUsingSender
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:1138
  | github.com/cockroachdb/cockroach/pkg/kv.(*DB).send
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:1121
  | github.com/cockroachdb/cockroach/pkg/kv.sendAndFill
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:970
  | github.com/cockroachdb/cockroach/pkg/kv.(*DB).Run
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:993
  | github.com/cockroachdb/cockroach/pkg/ts.(*DB).storeKvs
  | 	github.com/cockroachdb/cockroach/pkg/ts/db.go:311
  | github.com/cockroachdb/cockroach/pkg/ts.(*DB).tryStoreData
  | 	github.com/cockroachdb/cockroach/pkg/ts/db.go:249
  | github.com/cockroachdb/cockroach/pkg/ts.(*DB).StoreData
  | 	github.com/cockroachdb/cockroach/pkg/ts/db.go:214
  | github.com/cockroachdb/cockroach/pkg/ts.(*poller).poll.func1.1
  | 	github.com/cockroachdb/cockroach/pkg/ts/db.go:195
  | github.com/cockroachdb/cockroach/pkg/util/timeutil.RunWithTimeout
  | 	github.com/cockroachdb/cockroach/pkg/util/timeutil/timeout.go:29
  | github.com/cockroachdb/cockroach/pkg/ts.(*poller).poll.func1
  | 	github.com/cockroachdb/cockroach/pkg/ts/db.go:193
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTask
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:320
  | github.com/cockroachdb/cockroach/pkg/ts.(*poller).poll
  | 	github.com/cockroachdb/cockroach/pkg/ts/db.go:184
  | github.com/cockroachdb/cockroach/pkg/ts.(*poller).start.func1
  | 	github.com/cockroachdb/cockroach/pkg/ts/db.go:162
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:485
  | runtime.goexit
  | 	src/runtime/asm_amd64.s:1695
Wraps: (2) runtime error: index out of range [825045937120] with length 2803
Error types: (1) *withstack.withStack (2) runtime.boundsError
-- report composition:
runtime.boundsError
panic.go:770: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_amd64.s#L1694-L1696](src/runtime/asm_amd64.s#L1694-L1696)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/util/stop/stopper.go#L484-L486](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/util/stop/stopper.go#L484-L486)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/ts/db.go#L161-L163](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/ts/db.go#L161-L163)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/ts/db.go#L183-L185](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/ts/db.go#L183-L185)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/util/stop/stopper.go#L319-L321](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/util/stop/stopper.go#L319-L321)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/ts/db.go#L192-L194](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/ts/db.go#L192-L194)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/util/timeutil/timeout.go#L28-L30](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/util/timeutil/timeout.go#L28-L30)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/ts/db.go#L194-L196](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/ts/db.go#L194-L196)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/ts/db.go#L213-L215](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/ts/db.go#L213-L215)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/ts/db.go#L248-L250](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/ts/db.go#L248-L250)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/ts/db.go#L310-L312](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/ts/db.go#L310-L312)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/kv/db.go#L992-L994](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/kv/db.go#L992-L994)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/kv/db.go#L969-L971](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/kv/db.go#L969-L971)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/kv/db.go#L1120-L1122](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/kv/db.go#L1120-L1122)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/kv/db.go#L1137-L1139](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/kv/db.go#L1137-L1139)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/kv/db.go#L228-L230](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/kv/db.go#L228-L230)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/kv/kvclient/kvcoord/dist_sender.go#L1237-L1239](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/kv/kvclient/kvcoord/dist_sender.go#L1237-L1239)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/kv/kvclient/kvcoord/dist_sender.go#L1899-L1901](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/kv/kvclient/kvcoord/dist_sender.go#L1899-L1901)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/kv/kvclient/kvcoord/batch.go#L362-L364](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/kv/kvclient/kvcoord/batch.go#L362-L364)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/kv/kvclient/kvcoord/batch.go#L1046-L1048](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/kv/kvclient/kvcoord/batch.go#L1046-L1048)
[GOROOT/src/runtime/panic.go#L113-L115](GOROOT/src/runtime/panic.go#L113-L115)
[GOROOT/src/runtime/panic.go#L769-L771](GOROOT/src/runtime/panic.go#L769-L771)
[https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/kv/kvclient/kvcoord/dist_sender.go#L1797-L1799](https://github.com/cockroachdb/cockroach/blob/7e81be6de75205c3d08b0d8dcc6ca188306abc27/pkg/kv/kvclient/kvcoord/dist_sender.go#L1797-L1799)
[GOROOT/src/runtime/panic.go#L769-L771](GOROOT/src/runtime/panic.go#L769-L771)
</details>

```
src/runtime/asm_amd64.s in runtime.goexit at line 1695
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 485
pkg/ts/db.go in pkg/ts.(*poller).start.func1 at line 162
pkg/ts/db.go in pkg/ts.(*poller).poll at line 184
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunTask at line 320
pkg/ts/db.go in pkg/ts.(*poller).poll.func1 at line 193
pkg/util/timeutil/timeout.go in pkg/util/timeutil.RunWithTimeout at line 29
pkg/ts/db.go in pkg/ts.(*poller).poll.func1.1 at line 195
pkg/ts/db.go in pkg/ts.(*DB).StoreData at line 214
pkg/ts/db.go in pkg/ts.(*DB).tryStoreData at line 249
pkg/ts/db.go in pkg/ts.(*DB).storeKvs at line 311
pkg/kv/db.go in pkg/kv.(*DB).Run at line 993
pkg/kv/db.go in pkg/kv.sendAndFill at line 970
pkg/kv/db.go in pkg/kv.(*DB).send at line 1121
pkg/kv/db.go in pkg/kv.(*DB).sendUsingSender at line 1138
pkg/kv/db.go in pkg/kv.(*CrossRangeTxnWrapperSender).Send at line 229
pkg/kv/kvclient/kvcoord/dist_sender.go in pkg/kv/kvclient/kvcoord.(*DistSender).Send at line 1238
pkg/kv/kvclient/kvcoord/dist_sender.go in pkg/kv/kvclient/kvcoord.(*DistSender).divideAndSendBatchToRanges at line 1900
pkg/kv/kvclient/kvcoord/batch.go in pkg/kv/kvclient/kvcoord.(*BatchTruncationHelper).Truncate at line 363
pkg/kv/kvclient/kvcoord/batch.go in pkg/kv/kvclient/kvcoord.(*orderRestorationHelper).restoreOrder at line 1047
GOROOT/src/runtime/panic.go in runtime.goPanicIndex at line 114
GOROOT/src/runtime/panic.go in runtime.gopanic at line 770
pkg/kv/kvclient/kvcoord/dist_sender.go in pkg/kv/kvclient/kvcoord.(*DistSender).divideAndSendBatchToRanges.func1 at line 1798
GOROOT/src/runtime/panic.go in runtime.gopanic at line 770
```

### Tags

| Tag | Value |
| --- | --- |
| Command | start-single-node |
| Environment | v24.1.2 |
| Go Version | go1.22.3 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v24.1.2 |
| Cockroach SHA | 7e81be6de75205c3d08b0d8dcc6ca188306abc27 |
| # of CPUs | 4 |
| # of Goroutines | 384 |

Jira issue: CRDB-41562

**Comment by yuzefovich** [comment]
unactionable
