### ISSUE TITLE
Is it possible to alter a normal index to storing column index?

### ISSUE THREAD

**Issue by lalalalatt** [cockroachdb/cockroach#129528]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Jira issue: CRDB-41574

**Comment by DarrylWong** [comment]
Hi @lalalalatt!

Could you ask your question over on the [community slack channel](https://go.crdb.dev/p/slack) or the [forums](https://forum.cockroachlabs.com/)? Those would be more appropriate channels to ask questions like this.
