### ISSUE TITLE
rac2: admitted vector handling

### ISSUE THREAD

**Issue by sumeerbhola** [cockroachdb/cockroach#129508]
This needs to be done outside Raft, since it (a) allows for more efficient attachment of the admitted vector when sending a MsgAppResp, (b) probably more maintainable, since it will sit inside the RACv2 code, etc.

Prototype is in https://github.com/cockroachdb/cockroach/pull/129447

---

Key changes:
- #129751
- #130074
- #130171
- #130427
- #130444

(see full history of changes below)

---

Jira issue: CRDB-41569
Epic: CRDB-37515

**Comment by kvoli** [comment]
@pav-kv is all that is left https://github.com/cockroachdb/cockroach/issues/129508 to complete this issue?

**Comment by pav-kv** [comment]
Only need to merge #130444 after some fixups. Will do today/tomorrow.
