### ISSUE TITLE
Sentry: panic.go:884: panic: × (1) attached stack trace   -- stack trace:   | runtime.gopanic   | 	GOROOT/src/runtime/panic.go:884   | github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*reg...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#129594]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5749108777/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5749108777/?referrer=webhooks_plugin)

Panic Message:

```
panic.go:884: panic: ×
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*registration).validateEvent
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed/registry.go:186
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*registration).publish
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed/registry.go:157
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*registry).PublishToOverlapping.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed/registry.go:477
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*registry).forOverlappingRegs.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed/registry.go:524
  | github.com/cockroachdb/cockroach/pkg/util/interval.(*llrbNode).doMatch
  | 	github.com/cockroachdb/cockroach/pkg/util/interval/llrb_based_interval.go:598
  | github.com/cockroachdb/cockroach/pkg/util/interval.(*llrbTree).DoMatching
  | 	github.com/cockroachdb/cockroach/pkg/util/interval/llrb_based_interval.go:585
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*registry).forOverlappingRegs
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed/registry.go:534
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*registry).PublishToOverlapping
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed/registry.go:473
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*Processor).publishValue
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed/processor.go:845
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*Processor).consumeLogicalOps
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed/processor.go:765
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*Processor).consumeEvent
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed/processor.go:734
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*Processor).run
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed/processor.go:385
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*Processor).Start.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed/processor.go:270
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (2) panic: ×
Error types: (1) *withstack.withStack (2) *errutil.leafError
-- report composition:
*errutil.leafError: panic: ×
panic.go:884: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/6ed4ef16634f683adfb7d77b4ebf414e0c1e42a7/pkg/util/stop/stopper.go#L469-L471](https://github.com/cockroachdb/cockroach/blob/6ed4ef16634f683adfb7d77b4ebf414e0c1e42a7/pkg/util/stop/stopper.go#L469-L471)
[https://github.com/cockroachdb/cockroach/blob/6ed4ef16634f683adfb7d77b4ebf414e0c1e42a7/pkg/kv/kvserver/rangefeed/processor.go#L269-L271](https://github.com/cockroachdb/cockroach/blob/6ed4ef16634f683adfb7d77b4ebf414e0c1e42a7/pkg/kv/kvserver/rangefeed/processor.go#L269-L271)
[https://github.com/cockroachdb/cockroach/blob/6ed4ef16634f683adfb7d77b4ebf414e0c1e42a7/pkg/kv/kvserver/rangefeed/processor.go#L384-L386](https://github.com/cockroachdb/cockroach/blob/6ed4ef16634f683adfb7d77b4ebf414e0c1e42a7/pkg/kv/kvserver/rangefeed/processor.go#L384-L386)
[https://github.com/cockroachdb/cockroach/blob/6ed4ef16634f683adfb7d77b4ebf414e0c1e42a7/pkg/kv/kvserver/rangefeed/processor.go#L733-L735](https://github.com/cockroachdb/cockroach/blob/6ed4ef16634f683adfb7d77b4ebf414e0c1e42a7/pkg/kv/kvserver/rangefeed/processor.go#L733-L735)
[https://github.com/cockroachdb/cockroach/blob/6ed4ef16634f683adfb7d77b4ebf414e0c1e42a7/pkg/kv/kvserver/rangefeed/processor.go#L764-L766](https://github.com/cockroachdb/cockroach/blob/6ed4ef16634f683adfb7d77b4ebf414e0c1e42a7/pkg/kv/kvserver/rangefeed/processor.go#L764-L766)
[https://github.com/cockroachdb/cockroach/blob/6ed4ef16634f683adfb7d77b4ebf414e0c1e42a7/pkg/kv/kvserver/rangefeed/processor.go#L844-L846](https://github.com/cockroachdb/cockroach/blob/6ed4ef16634f683adfb7d77b4ebf414e0c1e42a7/pkg/kv/kvserver/rangefeed/processor.go#L844-L846)
[https://github.com/cockroachdb/cockroach/blob/6ed4ef16634f683adfb7d77b4ebf414e0c1e42a7/pkg/kv/kvserver/rangefeed/registry.go#L472-L474](https://github.com/cockroachdb/cockroach/blob/6ed4ef16634f683adfb7d77b4ebf414e0c1e42a7/pkg/kv/kvserver/rangefeed/registry.go#L472-L474)
[https://github.com/cockroachdb/cockroach/blob/6ed4ef16634f683adfb7d77b4ebf414e0c1e42a7/pkg/kv/kvserver/rangefeed/registry.go#L533-L535](https://github.com/cockroachdb/cockroach/blob/6ed4ef16634f683adfb7d77b4ebf414e0c1e42a7/pkg/kv/kvserver/rangefeed/registry.go#L533-L535)
[https://github.com/cockroachdb/cockroach/blob/6ed4ef16634f683adfb7d77b4ebf414e0c1e42a7/pkg/util/interval/llrb_based_interval.go#L584-L586](https://github.com/cockroachdb/cockroach/blob/6ed4ef16634f683adfb7d77b4ebf414e0c1e42a7/pkg/util/interval/llrb_based_interval.go#L584-L586)
[https://github.com/cockroachdb/cockroach/blob/6ed4ef16634f683adfb7d77b4ebf414e0c1e42a7/pkg/util/interval/llrb_based_interval.go#L597-L599](https://github.com/cockroachdb/cockroach/blob/6ed4ef16634f683adfb7d77b4ebf414e0c1e42a7/pkg/util/interval/llrb_based_interval.go#L597-L599)
[https://github.com/cockroachdb/cockroach/blob/6ed4ef16634f683adfb7d77b4ebf414e0c1e42a7/pkg/kv/kvserver/rangefeed/registry.go#L523-L525](https://github.com/cockroachdb/cockroach/blob/6ed4ef16634f683adfb7d77b4ebf414e0c1e42a7/pkg/kv/kvserver/rangefeed/registry.go#L523-L525)
[https://github.com/cockroachdb/cockroach/blob/6ed4ef16634f683adfb7d77b4ebf414e0c1e42a7/pkg/kv/kvserver/rangefeed/registry.go#L476-L478](https://github.com/cockroachdb/cockroach/blob/6ed4ef16634f683adfb7d77b4ebf414e0c1e42a7/pkg/kv/kvserver/rangefeed/registry.go#L476-L478)
[https://github.com/cockroachdb/cockroach/blob/6ed4ef16634f683adfb7d77b4ebf414e0c1e42a7/pkg/kv/kvserver/rangefeed/registry.go#L156-L158](https://github.com/cockroachdb/cockroach/blob/6ed4ef16634f683adfb7d77b4ebf414e0c1e42a7/pkg/kv/kvserver/rangefeed/registry.go#L156-L158)
[https://github.com/cockroachdb/cockroach/blob/6ed4ef16634f683adfb7d77b4ebf414e0c1e42a7/pkg/kv/kvserver/rangefeed/registry.go#L185-L187](https://github.com/cockroachdb/cockroach/blob/6ed4ef16634f683adfb7d77b4ebf414e0c1e42a7/pkg/kv/kvserver/rangefeed/registry.go#L185-L187)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 470
pkg/kv/kvserver/rangefeed/processor.go in pkg/kv/kvserver/rangefeed.(*Processor).Start.func1 at line 270
pkg/kv/kvserver/rangefeed/processor.go in pkg/kv/kvserver/rangefeed.(*Processor).run at line 385
pkg/kv/kvserver/rangefeed/processor.go in pkg/kv/kvserver/rangefeed.(*Processor).consumeEvent at line 734
pkg/kv/kvserver/rangefeed/processor.go in pkg/kv/kvserver/rangefeed.(*Processor).consumeLogicalOps at line 765
pkg/kv/kvserver/rangefeed/processor.go in pkg/kv/kvserver/rangefeed.(*Processor).publishValue at line 845
pkg/kv/kvserver/rangefeed/registry.go in pkg/kv/kvserver/rangefeed.(*registry).PublishToOverlapping at line 473
pkg/kv/kvserver/rangefeed/registry.go in pkg/kv/kvserver/rangefeed.(*registry).forOverlappingRegs at line 534
pkg/util/interval/llrb_based_interval.go in pkg/util/interval.(*llrbTree).DoMatching at line 585
pkg/util/interval/llrb_based_interval.go in pkg/util/interval.(*llrbNode).doMatch at line 598
pkg/kv/kvserver/rangefeed/registry.go in pkg/kv/kvserver/rangefeed.(*registry).forOverlappingRegs.func1 at line 524
pkg/kv/kvserver/rangefeed/registry.go in pkg/kv/kvserver/rangefeed.(*registry).PublishToOverlapping.func1 at line 477
pkg/kv/kvserver/rangefeed/registry.go in pkg/kv/kvserver/rangefeed.(*registration).publish at line 157
pkg/kv/kvserver/rangefeed/registry.go in pkg/kv/kvserver/rangefeed.(*registration).validateEvent at line 186
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v23.1.22 |
| Go Version | go1.19.13 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.22 |
| Cockroach SHA | 6ed4ef16634f683adfb7d77b4ebf414e0c1e42a7 |
| # of CPUs | 128 |
| # of Goroutines | 10444 |

Jira issue: CRDB-41607

**Comment by yuzefovich** [comment]
unactionable
