### ISSUE TITLE
sql: nullable arguments in builtin functions are unsupported

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#12968]
It is currently impossible to define a builtin function that accepts an optionally-null argument because of the way the overload resolver deals with `NULL`.

There's at least one builtin function that requires a nullable argument: see the discussion of `format_type()` in #12967.

This issue tracks the work necessary to enhance the overload resolver to deal with nullable arguments.

**Comment by jordanlewis** [comment]
This isn't actually required for ActiveRecord, just for a correct implementation of `format_type()`. I'm untagging this issue.

**Comment by cuongdo** [comment]
Is fixed fixed by #13031?

**Comment by eisenstatdavid** [comment]
Changing this to 1.0 because the ABS(NULL) issue was 1.0.
