### ISSUE TITLE
ldap: allow users to authenticate via LDAP to DB Console

### ISSUE THREAD

**Issue by dikshant** [cockroachdb/cockroach#129666]
We should extend ldap authentication to work with DB Console

Jira issue: CRDB-41654

Epic CRDB-33829

**Comment by dhartunian** [comment]
@souravcrl From a quick look at the commit message in https://github.com/cockroachdb/cockroach/pull/126227, it looks like if LDAP is configured, the user can provide a username and omit the password.

In the simplest possible implementation (with admittedly confusing UX) you could simply change nothing in the DB Console, and authenticate via LDAP if the configuration is present and ignore the password field. That handler is here: https://github.com/cockroachdb/cockroach/blob/cc4b8b1e386901644b0526fac5023f12e6dbc79d/pkg/server/authserver/authentication.go#L127-L172

For something a bit nicer, we could pass a flag to the UI telling it whether LDAP is configured and add a button to "Login with LDAP" for instance.
