### ISSUE TITLE
Sentry: crash_reporting.go:415: sampler-mem: no bytes in account to release, current 21756492, free 23841982
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/util/lo...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#129762]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5764794127/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5764794127/?referrer=webhooks_plugin)

Panic Message:

```
crash_reporting.go:415: sampler-mem: no bytes in account to release, current 21756492, free 23841982
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/util/log/logcrash.ReportOrPanic
  | 	github.com/cockroachdb/cockroach/pkg/util/log/logcrash/crash_reporting.go:415
  | github.com/cockroachdb/cockroach/pkg/util/mon.(*BoundAccount).Shrink
  | 	github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:991
  | github.com/cockroachdb/cockroach/pkg/sql/stats.(*SampleReservoir).MaybeResize
  | 	github.com/cockroachdb/cockroach/pkg/sql/stats/pkg/sql/stats/row_sampling.go:139
  | github.com/cockroachdb/cockroach/pkg/sql/stats.(*SampleReservoir).retryMaybeResize
  | 	github.com/cockroachdb/cockroach/pkg/sql/stats/pkg/sql/stats/row_sampling.go:159
  | github.com/cockroachdb/cockroach/pkg/sql/stats.(*SampleReservoir).SampleRow
  | 	github.com/cockroachdb/cockroach/pkg/sql/stats/pkg/sql/stats/row_sampling.go:171
  | github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*samplerProcessor).sampleRow
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowexec/sampler.go:464
  | github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*samplerProcessor).mainLoop
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowexec/sampler.go:332
  | github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*samplerProcessor).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowexec/sampler.go:235
  | github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).StartInternal.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:513
  | runtime.goexit
  | 	src/runtime/asm_amd64.s:1650
Wraps: (2) sampler-mem: no bytes in account to release, current 21756492, free 23841982
Error types: (1) *withstack.withStack (2) *errutil.leafError
-- report composition:
*errutil.leafError: sampler-mem: no bytes in account to release, current 21756492, free 23841982
crash_reporting.go:415: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_amd64.s#L1649-L1651](src/runtime/asm_amd64.s#L1649-L1651)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/flowinfra/flow.go#L512-L514](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/flowinfra/flow.go#L512-L514)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/rowexec/sampler.go#L234-L236](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/rowexec/sampler.go#L234-L236)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/rowexec/sampler.go#L331-L333](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/rowexec/sampler.go#L331-L333)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/rowexec/sampler.go#L463-L465](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/rowexec/sampler.go#L463-L465)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/stats/pkg/sql/stats/row_sampling.go#L170-L172](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/stats/pkg/sql/stats/row_sampling.go#L170-L172)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/stats/pkg/sql/stats/row_sampling.go#L158-L160](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/stats/pkg/sql/stats/row_sampling.go#L158-L160)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/stats/pkg/sql/stats/row_sampling.go#L138-L140](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/stats/pkg/sql/stats/row_sampling.go#L138-L140)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/util/mon/bytes_usage.go#L990-L992](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/util/mon/bytes_usage.go#L990-L992)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/util/log/logcrash/crash_reporting.go#L414-L416](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/util/log/logcrash/crash_reporting.go#L414-L416)
</details>

```
src/runtime/asm_amd64.s in runtime.goexit at line 1650
pkg/sql/flowinfra/flow.go in pkg/sql/flowinfra.(*FlowBase).StartInternal.func1 at line 513
pkg/sql/rowexec/sampler.go in pkg/sql/rowexec.(*samplerProcessor).Run at line 235
pkg/sql/rowexec/sampler.go in pkg/sql/rowexec.(*samplerProcessor).mainLoop at line 332
pkg/sql/rowexec/sampler.go in pkg/sql/rowexec.(*samplerProcessor).sampleRow at line 464
pkg/sql/stats/pkg/sql/stats/row_sampling.go in pkg/sql/stats.(*SampleReservoir).SampleRow at line 171
pkg/sql/stats/pkg/sql/stats/row_sampling.go in pkg/sql/stats.(*SampleReservoir).retryMaybeResize at line 159
pkg/sql/stats/pkg/sql/stats/row_sampling.go in pkg/sql/stats.(*SampleReservoir).MaybeResize at line 139
pkg/util/mon/bytes_usage.go in pkg/util/mon.(*BoundAccount).Shrink at line 991
pkg/util/log/logcrash/crash_reporting.go in pkg/util/log/logcrash.ReportOrPanic at line 415
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v23.2.9 |
| Go Version | go1.21.12 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.2.9 |
| Cockroach SHA | 579c0a000fb80ef7184e46ea038937c135ee2f0c |
| # of CPUs | 16 |
| # of Goroutines | 14660 |

Jira issue: CRDB-41698

**Comment by yuzefovich** [comment]
dup of #128241
