### ISSUE TITLE
Sentry: raft.go:1736: log.Fatal: match(6849) is out of range [lastIndex(6845)]. Was the raft log corrupted, truncated, or lost? (1) attached stack trace   -- stack trace:   | github.com/cockroachdb/co...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#129822]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5767945691/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5767945691/?referrer=webhooks_plugin)

Panic Message:

```
raft.go:1736: log.Fatal: match(6849) is out of range [lastIndex(6845)]. Was the raft log corrupted, truncated, or lost?
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/raft.(*raft).checkMatch
  | 	github.com/cockroachdb/cockroach/pkg/raft/raft.go:1736
  | github.com/cockroachdb/cockroach/pkg/raft.(*raft).handleAppendEntries
  | 	github.com/cockroachdb/cockroach/pkg/raft/raft.go:1669
  | github.com/cockroachdb/cockroach/pkg/raft.stepFollower
  | 	github.com/cockroachdb/cockroach/pkg/raft/raft.go:1627
  | github.com/cockroachdb/cockroach/pkg/raft.(*raft).Step
  | 	github.com/cockroachdb/cockroach/pkg/raft/raft.go:1205
  | github.com/cockroachdb/cockroach/pkg/raft.(*RawNode).Step
  | 	github.com/cockroachdb/cockroach/pkg/raft/rawnode.go:115
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processRaftRequestWithReplica.(*Replica).stepRaftGroup.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:633
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).withRaftGroupLocked
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:2057
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).withRaftGroup
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:2094
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).stepRaftGroup
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:584
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processRaftRequestWithReplica
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:411
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processRequestQueue.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:631
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).withReplicaForRequest
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:366
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processRequestQueue
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:629
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftSchedulerShard).worker
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:394
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).Start.func2
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:316
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:485
  | runtime.goexit
  | 	src/runtime/asm_arm64.s:1222
Wraps: (2) log.Fatal: match(6849) is out of range [lastIndex(6845)]. Was the raft log corrupted, truncated, or lost?
Error types: (1) *withstack.withStack (2) *errutil.leafError
-- report composition:
*errutil.leafError: log.Fatal: match(6849) is out of range [lastIndex(6845)]. Was the raft log corrupted, truncated, or lost?
raft.go:1736: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_arm64.s#L1221-L1223](src/runtime/asm_arm64.s#L1221-L1223)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/util/stop/stopper.go#L484-L486](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/util/stop/stopper.go#L484-L486)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L315-L317](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L315-L317)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L393-L395](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L393-L395)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L628-L630](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L628-L630)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L365-L367](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L365-L367)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L630-L632](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L630-L632)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L410-L412](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L410-L412)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L583-L585](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L583-L585)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L2093-L2095](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L2093-L2095)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L2056-L2058](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L2056-L2058)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L632-L634](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L632-L634)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/raft/rawnode.go#L114-L116](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/raft/rawnode.go#L114-L116)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/raft/raft.go#L1204-L1206](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/raft/raft.go#L1204-L1206)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/raft/raft.go#L1626-L1628](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/raft/raft.go#L1626-L1628)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/raft/raft.go#L1668-L1670](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/raft/raft.go#L1668-L1670)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/raft/raft.go#L1735-L1737](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/raft/raft.go#L1735-L1737)
</details>

```
src/runtime/asm_arm64.s in runtime.goexit at line 1222
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 485
pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go in pkg/kv/kvserver.(*raftScheduler).Start.func2 at line 316
pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go in pkg/kv/kvserver.(*raftSchedulerShard).worker at line 394
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).processRequestQueue at line 629
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).withReplicaForRequest at line 366
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).processRequestQueue.func1 at line 631
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).processRaftRequestWithReplica at line 411
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).stepRaftGroup at line 584
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).withRaftGroup at line 2094
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).withRaftGroupLocked at line 2057
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Store).processRaftRequestWithReplica.(*Replica).stepRaftGroup.func1 at line 633
pkg/raft/rawnode.go in pkg/raft.(*RawNode).Step at line 115
pkg/raft/raft.go in pkg/raft.(*raft).Step at line 1205
pkg/raft/raft.go in pkg/raft.stepFollower at line 1627
pkg/raft/raft.go in pkg/raft.(*raft).handleAppendEntries at line 1669
pkg/raft/raft.go in pkg/raft.(*raft).checkMatch at line 1736
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v24.2.0 |
| Go Version | go1.22.5 X:nocoverageredesign |
| Platform | linux arm64 |
| Distribution | CCL |
| Cockroach Release | v24.2.0 |
| Cockroach SHA | 953d09cce5a01cc0053e138516d80a27454f027c |
| # of CPUs | 16 |
| # of Goroutines | 590 |

Jira issue: CRDB-41727

**Comment by yuzefovich** [comment]
unactionable
