### ISSUE TITLE
ui: add support page

### ISSUE THREAD

**Issue by kuanluo** [cockroachdb/cockroach#12982]
We're going to shift the purpose of the Support panel in the admin ui slightly to make it a support hub for users. 

Form being filled below:
![help-rev-b](https://cloud.githubusercontent.com/assets/1486483/22083001/07e73500-dd98-11e6-896b-2227296716cf.jpg)

When all the fields are filled:
![d-filled](https://cloud.githubusercontent.com/assets/1486483/22083190/f966d1ec-dd98-11e6-87d8-f039f7446136.jpg)

After users hit submit:
![d-submitted](https://cloud.githubusercontent.com/assets/1486483/22083201/00b720dc-dd99-11e6-9785-b080c0086510.jpg)

Here is [the link](https://drive.google.com/drive/folders/0BzCbOEMl6iidMDFGVGhKSHFmSzQ?usp=sharing) to the mocks on Google Drive, and the Sketch file is updated with the latest designs.

 @jess-edwards Can you point to where in the Hubspot do we collect this info? @dianasaur323 Can you verify where else does this information go?

**Comment by dianasaur323** [comment]
LGTM.

**Comment by jess-edwards** [comment]
@kuanluo Let's move conversation RE: registration / hubspot to this issue [#29](https://github.com/cockroachlabs/registration/issues/29)

**Comment by dianasaur323** [comment]
@kuanluo moving milestone to 1.1

**Comment by kuanluo** [comment]
@dianasaur323 @jess-edwards Works for me. Thanks!

**Comment by mrtracy** [comment]
@dianasaur323 are we planning on putting this page, or a similar page, back into the product? It was removed before the 1.0 release.

I'm assuming that this should either be closed or moved to a later milestone.

**Comment by kuanluo** [comment]
@mrtracy @dianasaur323 

Ideally, it should be up as soon as possible to gather customer feedback as well as information.

**Comment by dianasaur323** [comment]
@mrtracy @kuanluo yes, it would be great to have this. Although, let's definitely get Segment set  up first - I need adequate time to make sure we can get the data we need from it, so we have to at least get the backend hooked in a month ahead of release.

**Comment by dianasaur323** [comment]
Although we wanted to squeeze this into 1.1, I'm not convinced we have any remaining time for this, especially if we want to set up the email stuff correctly. Let's revisit in 1.2.
