### ISSUE TITLE
dump only one table once a time 

### ISSUE THREAD

**Issue by EamonZhang** [cockroachdb/cockroach#12987]
**BUG REPORT**

https://www.cockroachlabs.com/docs/back-up-and-restore-data.html#synopsis

it can only dump one table once a time , other case failed! 

$cockroach --help 
`cockroach dump [options] <database> <table> [flags]`

only this case is can use .

$cockroach version
```
Build Tag:   beta-20170112
Build Time:  2017/01/12 18:27:36
Platform:    linux amd64
Go Version:  go1.7.3
C Compiler:  gcc 4.9.2
```

**Comment by dt** [comment]
hi @EamonZhang 

Sorry, it looks like the multi table dump support (#12759) was merged *just after* that beta version was tagged.

The the documentation you found on that page was updated when the new feature was merged, so unfortunately right now it is describing how it *will* work, once we release the next beta --alternatively, if you want to try it right away, you could also use a binary built from HEAD which would include that multi-table dump.

**Comment by dianasaur323** [comment]
@EamonZhang Our multi-table dump is supported now, so I will be closing this issue.
