### ISSUE TITLE
cli: feature request: provide a way to make wide tables more readable on narrow terminals

### ISSUE THREAD

**Issue by EamonZhang** [cockroachdb/cockroach#12985]
**ADVISE**

1. commands 'cockroach node status' shows the result too long preline. it cause line feed and seem confused.
  
![image](https://cloud.githubusercontent.com/assets/8612228/22092442/8c040322-de38-11e6-9237-6d936f479c34.png)

2.this problem is also exist in sql command, 
   to solve this ， postgres use  \x , mysql use \G.
  Does cockroach  support?

**Comment by knz** [comment]
Hi @EamonZhang! Thanks for filing this issue. I acknowledge this is currently a limitation.

As a workaround you can add the flag `--pretty=false`, redirect the output to a `.tsv` file, and open it using a spreadsheet program.

However your suggestion to add a flag comparable to pg's `\x` is interesting and we'll look into it.
