### ISSUE TITLE
schemachanger: v23.2.9: CREATE INDEX: expected value to be present in temp index

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#129862]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5770993925/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5770993925/?referrer=webhooks_plugin)

Panic Message:

```
mvcc_index_merger.go:428: executing declarative schema change PostCommitPhase stage 5 of 7 with 1 BackfillType op (rollback=false) for CREATE INDEX: expected value to be present in temp index for key=/Table/132/141/×/×/×/×/×/×/×/×
(1)
  | (opaque error wrapper)
  | type name: github.com/cockroachdb/errors/withstack/*withstack.withStack
  | reportable 0:
  |
  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scerrors.EventLogger.HandlePanicAndLogError
  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scerrors/errors.go:81
  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scrun.executeStage
  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scrun/scrun.go:205
  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scrun.RunSchemaChangesInJob.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scrun/scrun.go:139
  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scdeps.(*jobExecutionDeps).WithTxnInJob.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scdeps/run_deps.go:144
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).DescsTxn.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1772
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).txn.func4
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1861
  | github.com/cockroachdb/cockroach/pkg/kv.(*Txn).exec
  | 	github.com/cockroachdb/cockroach/pkg/kv/txn.go:1032
  | github.com/cockroachdb/cockroach/pkg/kv.runTxn
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:1079
  | github.com/cockroachdb/cockroach/pkg/kv.(*DB).TxnWithAdmissionControl
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:1042
  | github.com/cockroachdb/cockroach/pkg/kv.(*DB).Txn
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:1017
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).txn
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1848
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).DescsTxn
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1770
  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scdeps.(*jobExecutionDeps).WithTxnInJob
  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scdeps/run_deps.go:109
  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scrun.RunSchemaChangesInJob
  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scrun/scrun.go:135
  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scjob.(*newSchemaChangeResumer).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scjob/job.go:118
  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scjob.(*newSchemaChangeResumer).Resume
  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scjob/job.go:45
  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine.func2
  | 	github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1722
  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine
  | 	github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1723
  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).runJob
  | 	github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:477
  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).resumeJob.func2
  | 	github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:389
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:484
  | runtime.goexit
  | 	src/runtime/asm_amd64.s:1650
Wraps: (2) executing declarative schema change PostCommitPhase stage 5 of 7 with 1 BackfillType op (rollback=false) for CREATE INDEX
Wraps: (3) tags: [n×,received-error=]
Wraps: (4) tags: [n×,f×,job=×,distsql.gateway=×,distsql.appname=×,sent-error=]
Wraps: (5) assertion failure
Wraps: (6)
  | (opaque error wrapper)
  | type name: github.com/cockroachdb/errors/withstack/*withstack.withStack
  | reportable 0:
  |
  | github.com/cockroachdb/cockroach/pkg/sql/backfill.(*IndexBackfillMerger).constructMergeBatch
  | 	github.com/cockroachdb/cockroach/pkg/sql/backfill/mvcc_index_merger.go:428
  | github.com/cockroachdb/cockroach/pkg/sql/backfill.(*IndexBackfillMerger).merge.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/backfill/mvcc_index_merger.go:376
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).Txn.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1782
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).txn.func4
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1861
  | github.com/cockroachdb/cockroach/pkg/kv.(*Txn).exec
  | 	github.com/cockroachdb/cockroach/pkg/kv/txn.go:1032
  | github.com/cockroachdb/cockroach/pkg/kv.runTxn
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:1079
  | github.com/cockroachdb/cockroach/pkg/kv.(*DB).TxnWithAdmissionControl
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:1042
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).txn.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1834
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).txn
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1848
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).Txn
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1783
  | github.com/cockroachdb/cockroach/pkg/sql/backfill.(*IndexBackfillMerger).merge
  | 	github.com/cockroachdb/cockroach/pkg/sql/backfill/mvcc_index_merger.go:359
  | github.com/cockroachdb/cockroach/pkg/sql/backfill.(*IndexBackfillMerger).Run.func5
  | 	github.com/cockroachdb/cockroach/pkg/sql/backfill/mvcc_index_merger.go:175
  | github.com/cockroachdb/cockroach/pkg/sql/backfill.(*IndexBackfillMerger).Run.Group.GoCtx.func8
  | 	github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:168
  | golang.org/x/sync/errgroup.(*Group).Go.func1
  | 	golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:78
  | runtime.goexit
  | 	src/runtime/asm_amd64.s:1650
Wraps: (7) expected value to be present in temp index for key=/Table/132/141/×/×/×/×/×/×/×/×
Error types: (1) *errbase.opaqueWrapper (2) *errutil.withPrefix (3) *contexttags.withContext (4) *contexttags.withContext (5) *assert.withAssertionFailure (6) *errbase.opaqueWrapper (7) *errutil.leafError
-- report composition:
*errutil.leafError: expected value to be present in temp index for key=/Table/132/141/×/×/×/×/×/×/×/×
mvcc_index_merger.go:428: *withstack.withStack (top exception)
*assert.withAssertionFailure
*contexttags.withContext: n71
*contexttags.withContext: n22
*errutil.withPrefix: executing declarative schema change PostCommitPhase stage 5 of 7 with 1 BackfillType op (rollback=false) for CREATE INDEX
errors.go:81: *withstack.withStack (1)
(check the extra data payloads)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_amd64.s#L1649-L1651](src/runtime/asm_amd64.s#L1649-L1651)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/util/stop/stopper.go#L483-L485](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/util/stop/stopper.go#L483-L485)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/jobs/adopt.go#L388-L390](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/jobs/adopt.go#L388-L390)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/jobs/adopt.go#L476-L478](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/jobs/adopt.go#L476-L478)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/jobs/registry.go#L1722-L1724](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/jobs/registry.go#L1722-L1724)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/jobs/registry.go#L1721-L1723](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/jobs/registry.go#L1721-L1723)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/schemachanger/scjob/job.go#L44-L46](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/schemachanger/scjob/job.go#L44-L46)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/schemachanger/scjob/job.go#L117-L119](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/schemachanger/scjob/job.go#L117-L119)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/schemachanger/scrun/scrun.go#L134-L136](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/schemachanger/scrun/scrun.go#L134-L136)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/schemachanger/scdeps/run_deps.go#L108-L110](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/schemachanger/scdeps/run_deps.go#L108-L110)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/internal.go#L1769-L1771](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/internal.go#L1769-L1771)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/internal.go#L1847-L1849](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/internal.go#L1847-L1849)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/kv/db.go#L1016-L1018](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/kv/db.go#L1016-L1018)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/kv/db.go#L1041-L1043](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/kv/db.go#L1041-L1043)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/kv/db.go#L1078-L1080](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/kv/db.go#L1078-L1080)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/kv/txn.go#L1031-L1033](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/kv/txn.go#L1031-L1033)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/internal.go#L1860-L1862](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/internal.go#L1860-L1862)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/internal.go#L1771-L1773](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/internal.go#L1771-L1773)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/schemachanger/scdeps/run_deps.go#L143-L145](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/schemachanger/scdeps/run_deps.go#L143-L145)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/schemachanger/scrun/scrun.go#L138-L140](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/schemachanger/scrun/scrun.go#L138-L140)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/schemachanger/scrun/scrun.go#L204-L206](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/schemachanger/scrun/scrun.go#L204-L206)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/schemachanger/scerrors/errors.go#L80-L82](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/schemachanger/scerrors/errors.go#L80-L82)
[src/runtime/asm_amd64.s#L1649-L1651](src/runtime/asm_amd64.s#L1649-L1651)
[golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go#L77-L79](golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go#L77-L79)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/util/ctxgroup/ctxgroup.go#L167-L169](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/util/ctxgroup/ctxgroup.go#L167-L169)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/backfill/mvcc_index_merger.go#L174-L176](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/backfill/mvcc_index_merger.go#L174-L176)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/backfill/mvcc_index_merger.go#L358-L360](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/backfill/mvcc_index_merger.go#L358-L360)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/internal.go#L1782-L1784](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/internal.go#L1782-L1784)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/internal.go#L1847-L1849](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/internal.go#L1847-L1849)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/internal.go#L1833-L1835](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/internal.go#L1833-L1835)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/kv/db.go#L1041-L1043](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/kv/db.go#L1041-L1043)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/kv/db.go#L1078-L1080](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/kv/db.go#L1078-L1080)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/kv/txn.go#L1031-L1033](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/kv/txn.go#L1031-L1033)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/internal.go#L1860-L1862](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/internal.go#L1860-L1862)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/internal.go#L1781-L1783](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/internal.go#L1781-L1783)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/backfill/mvcc_index_merger.go#L375-L377](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/backfill/mvcc_index_merger.go#L375-L377)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/backfill/mvcc_index_merger.go#L427-L429](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/backfill/mvcc_index_merger.go#L427-L429)
</details>

```
src/runtime/asm_amd64.s in runtime.goexit at line 1650
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 484
pkg/jobs/adopt.go in pkg/jobs.(*Registry).resumeJob.func2 at line 389
pkg/jobs/adopt.go in pkg/jobs.(*Registry).runJob at line 477
pkg/jobs/registry.go in pkg/jobs.(*Registry).stepThroughStateMachine at line 1723
pkg/jobs/registry.go in pkg/jobs.(*Registry).stepThroughStateMachine.func2 at line 1722
pkg/sql/schemachanger/scjob/job.go in pkg/sql/schemachanger/scjob.(*newSchemaChangeResumer).Resume at line 45
pkg/sql/schemachanger/scjob/job.go in pkg/sql/schemachanger/scjob.(*newSchemaChangeResumer).run at line 118
pkg/sql/schemachanger/scrun/scrun.go in pkg/sql/schemachanger/scrun.RunSchemaChangesInJob at line 135
pkg/sql/schemachanger/scdeps/run_deps.go in pkg/sql/schemachanger/scdeps.(*jobExecutionDeps).WithTxnInJob at line 109
pkg/sql/internal.go in pkg/sql.(*InternalDB).DescsTxn at line 1770
pkg/sql/internal.go in pkg/sql.(*InternalDB).txn at line 1848
pkg/kv/db.go in pkg/kv.(*DB).Txn at line 1017
pkg/kv/db.go in pkg/kv.(*DB).TxnWithAdmissionControl at line 1042
pkg/kv/db.go in pkg/kv.runTxn at line 1079
pkg/kv/txn.go in pkg/kv.(*Txn).exec at line 1032
pkg/sql/internal.go in pkg/sql.(*InternalDB).txn.func4 at line 1861
pkg/sql/internal.go in pkg/sql.(*InternalDB).DescsTxn.func1 at line 1772
pkg/sql/schemachanger/scdeps/run_deps.go in pkg/sql/schemachanger/scdeps.(*jobExecutionDeps).WithTxnInJob.func1 at line 144
pkg/sql/schemachanger/scrun/scrun.go in pkg/sql/schemachanger/scrun.RunSchemaChangesInJob.func1 at line 139
pkg/sql/schemachanger/scrun/scrun.go in pkg/sql/schemachanger/scrun.executeStage at line 205
pkg/sql/schemachanger/scerrors/errors.go in pkg/sql/schemachanger/scerrors.EventLogger.HandlePanicAndLogError at line 81
src/runtime/asm_amd64.s in runtime.goexit at line 1650
golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go in golang.org/x/sync/errgroup.(*Group).Go.func1 at line 78
pkg/util/ctxgroup/ctxgroup.go in pkg/sql/backfill.(*IndexBackfillMerger).Run.Group.GoCtx.func8 at line 168
pkg/sql/backfill/mvcc_index_merger.go in pkg/sql/backfill.(*IndexBackfillMerger).Run.func5 at line 175
pkg/sql/backfill/mvcc_index_merger.go in pkg/sql/backfill.(*IndexBackfillMerger).merge at line 359
pkg/sql/internal.go in pkg/sql.(*InternalDB).Txn at line 1783
pkg/sql/internal.go in pkg/sql.(*InternalDB).txn at line 1848
pkg/sql/internal.go in pkg/sql.(*InternalDB).txn.func2 at line 1834
pkg/kv/db.go in pkg/kv.(*DB).TxnWithAdmissionControl at line 1042
pkg/kv/db.go in pkg/kv.runTxn at line 1079
pkg/kv/txn.go in pkg/kv.(*Txn).exec at line 1032
pkg/sql/internal.go in pkg/sql.(*InternalDB).txn.func4 at line 1861
pkg/sql/internal.go in pkg/sql.(*InternalDB).Txn.func1 at line 1782
pkg/sql/backfill/mvcc_index_merger.go in pkg/sql/backfill.(*IndexBackfillMerger).merge.func1 at line 376
pkg/sql/backfill/mvcc_index_merger.go in pkg/sql/backfill.(*IndexBackfillMerger).constructMergeBatch at line 428
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v23.2.9 |
| Go Version | go1.21.12 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.2.9 |
| Cockroach SHA | 579c0a000fb80ef7184e46ea038937c135ee2f0c |
| # of CPUs | 16 |
| # of Goroutines | 3379 |

Jira issue: CRDB-41744

**Comment by fqazi** [comment]
This hasn't reappeared in a while and insufficient information to root cause this at the moment.
