### ISSUE TITLE
upgrade: first upgrade to repair descriptor corruption can get stuck on txn retries

### ISSUE THREAD

**Issue by fqazi** [cockroachdb/cockroach#129949]
Currently the logic for repairing descriptors with corruption for upgrades work at a 1000 descriptors at a time, which can be problematic if a cluster has a large number of descriptors with corruption that are heavily contended. This can lead to this upgrade step hitting transaction retries forever, which can be observed with cluster queries like:
```
SELECT count(*) FROM (SELECT crdb_internal.repair_catalog_corruption(id, corruption) AS was_repaired FROM "".crdb_internal.kv_repairable_catalog_corruptions LIMIT 1000) WHERE was_repaired ```
```
We should automatically adjust this batch size, so that a reasonable number of descriptors is exercised when a txn retry is hit. This can be done at https://github.com/cockroachdb/cockroach/blob/cf787f691f3d757409f10bb2bb8cb1bec2b20562/pkg/upgrade/upgrades/first_upgrade.go#L168

Jira issue: CRDB-41792

gz#23238

Epic CRDB-40419

**Comment by rimadeodhar** [comment]
Additionally, we should also consider reducing the limit from 1000 to a more reasonable number - like 100 even for the default case. Thanks @spilchen for the suggestion!

**Comment by fqazi** [comment]
Lets also add a test case with the full batch size here to confirm its sane in normal circumstances without contention too.
