### ISSUE TITLE
storage: spread hot ranges across the cluster

### ISSUE THREAD

**Issue by arjunravinarayan** [cockroachdb/cockroach#12996]
A new cockroach cluster starts out a new table on a single range, and until that range grows to ~64mb, it doesn't get split. As a result, firing up and running some example benchmark is limited by the query throughput of our single-range performance, regardless of the size of the initial cluster. Essentially, flooring a load generator on a 6 or 10 node cluster gives you as much power off the starting grid as a 3-node cluster.

Right now at our current performance levels, that is limited to a few thousand QPS. If the individual queries grow the table slowly, it takes an inordinately long period of time before QPS grows. `block_writer` grows tables fairly quickly, so we notice performance steps in tens of minutes. For other, less write intensive workloads, this doesn't improve. And if access patterns are skewed, as with photos or read-intensive YCSB as a load generator, a hot range with little to no size growth remains hot forever, gating performance.

The primary solution is to split ranges based on access patterns, and spreading hot ranges and leader replicas across the available cluster. It's unclear to me if there are better/easier solutions in the meantime before such a feature is implemented.

cc @petermattis

**Comment by petermattis** [comment]
The short term solution is to manually split the table using `ALTER TABLE SPLIT AT`. Alternately, you can configure a small range size using. For example, the following will set the range size to 2MB:

`echo "range_max_bytes: $[2 * 1024 * 1024]" | ./cockroach zone set .default --file=-`.
