### ISSUE TITLE
ui: unknown event type: alter_table

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#12999]
![screen shot 2017-01-19 at 11 35 40 am](https://cloud.githubusercontent.com/assets/6201335/22115562/7b489838-de3b-11e6-9f37-c8dd909cc816.png)

We have so few event types, how is `alter_table` unknown?

**Comment by leomkkwan** [comment]
![cockroach](https://cloud.githubusercontent.com/assets/18466032/22158694/64ec2a2a-df0b-11e6-8ed4-e710386a4860.PNG)

FYI, there is more events that are unknown.
