### ISSUE TITLE
When Timestamptz is enterted  format  2017-01-19 16:35:03.564000 +01:00:00 it throws exception

### ISSUE THREAD

**Issue by Velicko91** [cockroachdb/cockroach#12995]
Hello,
I tried to use Spring-jdbc template, and for timestamptz its throwing exception because you are not supporting this time format  2017-01-19 16:35:03.564000 +01:00:00. when i removed  through a debugger space infront + and last 3 chars (:00), insert was successful. But database saved this  
2017-01-19 16:35:03.56 +0000 +0000 .

**Comment by dt** [comment]
Fixed #14712
