### ISSUE TITLE
server: `start-single-node --background` is not always immediately reachable after returning

### ISSUE THREAD

**Issue by def-** [cockroachdb/cockroach#130011]
**Describe the problem**

Sometimes in our Materialize CI we notice that Cockroach is not immediately reachable after starting it with `cockroach start-single-node --insecure`, for example in https://buildkite.com/materialize/test/builds/89635#0191b6d7-9684-4202-87b2-f88668b59fce
```
ERROR: cannot dial server.
Is the server running?
If the server is running, check --host client-side and --advertise server-side.

timeout: context deadline exceeded
Failed running "sql"
```
There was a similar issue reported here previously: https://github.com/cockroachdb/cockroach/issues/83700, so it seems Cockroach itself had similar errors in CI.

**To Reproduce**

In our Materialize CI we run a local cockroach instance like this:

https://github.com/MaterializeInc/materialize/blob/5cf69faa22f9547effbe8dde6228f848388a2394/misc/images/materialized/entrypoint.sh#L43-L50
```bash
  COCKROACH_SKIP_ENABLING_DIAGNOSTIC_REPORTING=true cockroach start-single-node \
      --insecure \
      --background \
      --store=/mzdata/cockroach

  # See: https://github.com/cockroachdb/cockroach/issues/93892
  # See: https://github.com/MaterializeInc/materialize/issues/16726
  cockroach sql --insecure -e "SET CLUSTER SETTING sql.stats.forecasts.enabled = false"
```

**Expected behavior**
The documentation in https://www.cockroachlabs.com/docs/stable/cockroach-start-single-node states:

> `--background`: Runs the node in the background. Control is returned to the shell only once the node is ready to accept requests, so this is recommended over appending & to the command. 

Which is exactly what I'd expect. So a `cockroach sql` should not fail after starting up with `--background`.

**Environment:**
 - CockroachDB version v23.1.11
 - Server OS: Ubuntu Jammy
 - Client app `cockroach sql`

**Additional context**
Flake in CI, we'll have to think about a workaround

Jira issue: CRDB-41840

**Comment by ZhouXing19** [comment]
Hello @def- , thanks for reporting this issue. I would like to get more information. Is the server started via `cockroach start-single-node --insecure` never became available via `cockroach sql`, or it is accessible later on, but just immediately? Just trying to narrow down the case here so that we can better debug it. Thanks!

**Comment by def-** [comment]
I don't have definitive data on that since we stop the execution immediately after the first call to `cockroach sql` failed. But after adding the workaround of retrying the `cockroach sql` call I haven't seen failures like this reoccurring in Materialize's CI, so my best guess is that it becomes accessible after a moment.

**Comment by cthumuluru-crdb** [comment]
In case of https://github.com/cockroachdb/cockroach/issues/83700, it looks like Cockroach process was still alive and using the UDS socket that the new process is trying to bind to. It might be unrelated?

**Comment by cthumuluru-crdb** [comment]
@def- can you please share Cockroach logs for this run?

**Comment by def-** [comment]
```
*
* WARNING: ALL SECURITY CONTROLS HAVE BEEN DISABLED!
* 
* This mode is intended for non-production testing only.
* 
* In this mode:
* - Your cluster is open to any client that can access any of your IP addresses.
* - Intruders with access to your machine or network can observe client-server traffic.
* - Intruders can log in without password and read or write any data in the cluster.
* - Intruders can consume all your server's resources and cause unavailability.
*
*
* INFO: To start a secure server without mandating TLS for clients,
* consider --accept-sql-without-tls instead. For other options, see:
* 
* - https://go.crdb.dev/issue-v/53404/v23.1
* - https://www.cockroachlabs.com/docs/v23.1/secure-a-cluster.html
*
*
* WARNING: Running a server without --sql-addr, with a combined RPC/SQL listener, is deprecated.
* This feature will be removed in a later version of CockroachDB.
*
*
* WARNING: neither --listen-addr nor --advertise-addr was specified.
* The server will advertise "materialized" to other nodes, is this routable?
* 
* Consider using:
* - for local-only servers:  --listen-addr=localhost:36257 --sql-addr=localhost:26257
* - for multi-node clusters: --listen-addr=:36257 --sql-addr=:26257 --advertise-addr=<host/IP addr>
* 
*
ERROR: cannot dial server.
Is the server running?
If the server is running, check --host client-side and --advertise server-side.

timeout: context deadline exceeded
Failed running "sql"
```

**Comment by cthumuluru-crdb** [comment]
The issue seems to be related to the delay from the time we open  SQL listener and the time when the server is ready to process incoming connections. Default `cockroach sql` connection timeout is set to 15s. You can increase that using `connect_timeout` connection parameter.

**Comment by cthumuluru-crdb** [comment]
@def- to debug this issue further, I need Cockroach database logs from the logs folder. If the logs contain any sensitive information, please reach out to our support team to share them securely.

**Comment by def-** [comment]
How about just making `starg-single-node --background` wait until the server is actually ready to process incoming connections? I don't have logs unfortunately and can't reproduce the issue.

**Comment by cthumuluru-crdb** [comment]
I'll check and get back to you on that. In the meantime, please increase the timeout using `connect_timeout` connection url parameter to mitigate the test failures.

**Comment by cthumuluru-crdb** [comment]
The control is returned back once the node is ready to bootstrap and that was a deliberate choice. The bootstrap process took more than 15s in this particular case which is not normal. Without Cockroach server logs its hard to track down the real issue. Next time this happens, can you please share the server logs too?

**Comment by cthumuluru-crdb** [comment]
Closing this ticket for now. If you see this issue again, reopen it and share the server logs.
