### ISSUE TITLE
distribution: <hidden> vectorized: <hidden>

### ISSUE THREAD

**Issue by leolong0325** [cockroachdb/cockroach#130007]
When I was writing some regression tests using crdb I found that some fields were hidden:

```sql
query T
EXPLAIN ANALYZE CREATE TABLE t2 AS SELECT * FROM t1;
----
planning time: 10µs
execution time: 100µs
distribution: <hidden>
vectorized: <hidden>
maximum memory usage: <hidden>
network usage: <hidden>
regions: <hidden>
·
• create table as
│ nodes: <hidden>
│ regions: <hidden>
│ actual row count: 0
│
└── • render
    │ nodes: <hidden>
    │ regions: <hidden>
    │ actual row count: 0
    │ KV time: 0µs
    │ KV contention time: 0µs
    │ KV rows read: 0
    │ KV bytes read: 0 B
    │
    └── • scan
          nodes: <hidden>
          regions: <hidden>
          actual row count: 0
          KV time: 0µs
          KV contention time: 0µs
          KV rows read: 0
          KV bytes read: 0 B
          missing stats
          table: t1@primary
          spans: FULL SCAN
```
But I am interested in the value of the distribution field. How can I make it not hidden?

Looking forward to your reply. 

Best wishes!

Jira issue: CRDB-41837

**Comment by DrewKimball** [comment]
Hi @leolong0325, thanks for posting! We replace some fields with `<hidden>`, and others with default values, because showing the actual values would cause the test to flake whenever they happened to differ. Distribution, for example, can vary because leaseholder placement happens to change from test to test, or between different test configurations. Can you explain more about what you're trying to test, so I can point you in the right direction?

**Comment by leolong0325** [comment]
Thank you for your response and attention.

I have developed a feature similar to Oracle's hint functionality based on CockroachDB. This feature allows the value of distsql to be specified at the statement level, enabling the distributed query to execute as expected. I wrote test cases to verify whether the feature functions correctly. For example, the following case is what I expect to see：
```sql
qbadmin@localhost:20158/qianbase> PREPARE d AS SELECT /*+ set(distsql,'off') */ * FROM t1;
PREPARE


Time: 0ms total (execution 0ms / network 0ms)

qbadmin@localhost:20158/qianbase> EXPLAIN ANALYZE (plan) EXECUTE d;
                                   info
---------------------------------------------------------------------------
  planning time: 150µs
  execution time: 616µs
  distribution: local
  vectorized: true
  cumulative time spent in KV: 342µs
  maximum memory usage: 20 KiB
  network usage: 0 B (0 messages)

  • scan
    nodes: n1
    actual row count: 0
    KV time: 342µs
    KV contention time: 0µs
    KV rows read: 0
    KV bytes read: 0 B
    estimated row count: 1 (100% of the table; stats collected 1 day ago)
    table: t1@primary
    spans: FULL SCAN
(18 rows)


Time: 1ms total (execution 1ms / network 0ms)
```

But when I was writing the test case, the field distribution was hidden:
```sql
statement ok
PREPARE d AS SELECT /*+ set(distsql,'on') */ * FROM t1;

query T
EXPLAIN ANALYZE EXECUTE d;
----
planning time: 10µs
execution time: 100µs
distribution: <hidden>
vectorized: <hidden>
maximum memory usage: <hidden>
network usage: <hidden>
regions: <hidden>
·
• scan
  nodes: <hidden>
  regions: <hidden>
  actual row count: 0
  KV time: 0µs
  KV contention time: 0µs
  KV rows read: 0
  KV bytes read: 0 B
  missing stats
  table: t1@primary
  spans: FULL SCAN
```
So, I would like to know if it is possible to temporarily disable the "hidden" feature for testing purposes.

Looking forward to your reply again.

Best regards！

**Comment by DrewKimball** [comment]
I think your best option then will be to use an `EXPLAIN (DISTSQL)` or just plain `EXPLAIN`, rather than `EXPLAIN ANALYZE`. In addition, the test should probably go in [this file](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/opt/exec/execbuilder/testdata/distsql_misc), which simulates a 5-node cluster and already contains setup logic to make sure the data in table `xyz` is distributed across the nodes.

**Comment by leolong0325** [comment]
Since I am executing a PREPARE statement, I can only view the execution plan through EXPLAIN ANALYZE during the EXECUTE phase, and the EXPLAIN EXECUTE syntax is not supported. Additionally, the distribution field in the result of EXPLAIN (DISTSQL) will also be hidden.

**Comment by DrewKimball** [comment]
Hi @leolong0325, sorry for the delay. There's not currently a way to disable this redaction for our logic tests (although you're welcome to add one). It's not perfect, but you could use `EXPLAIN ANALYZE (DISTSQL)` - the `distribution` field will still be hidden, but the URL will still show how the physical plan is distributed across nodes. You could also check use tracing to view the distribution choice when the query is executed like in this snippet:
```
diff --git a/pkg/sql/opt/exec/execbuilder/testdata/distsql_misc b/pkg/sql/opt/exec/execbuilder/testdata/distsql_misc
index 085d15c7ff0..902e852f2c1 100644
--- a/pkg/sql/opt/exec/execbuilder/testdata/distsql_misc
+++ b/pkg/sql/opt/exec/execbuilder/testdata/distsql_misc
@@ -132,6 +132,24 @@ vectorized: true
 ·
 Diagram: https://cockroachdb.github.io/distsqlplan/decode.html#eJyklEFvmz4UwO__T2G903-TERjIDpw2NZmElKZZ4LBpiioXv6aogJlt1FUR330ydGtBSYWID5bs5_zeLw8_H0H_KiCC1fft-ku8If8v4yRNvq0pSX9sV8kHkqzWq6uUfCRfdzfXRHDDgUIlBW54iRqin8CAgg8UAqAQAoUF7CnUSmaotVT2yLH7QSx-Q-RRyKu6MXZ7TyGTCiE6gslNgRBByu8K3CEXqFwPKAg0PC-6NDb1Zzvd1o_4DBSuZNGUlY4Ip-SOkowSARSSmts9x2WEV4IwIs0DKti3FGRjXjNrww8IEXujGi8h8lp6xvZVsqmkEqhQDAXzygB9me8LyU0XzvKSF7BvT_zZjXRk7S4GlHOe_shzMfBk06vKLqmqyxzXn1VXNvD1p_v6F_n6jhvM8vUHvsF03-Ai38Bxw1m-wcA3nO4bXuQbOu5ilm94ts9O-O5Q17LSOKlTvFEmh9neQ3HAvou1bFSGWyWz7my_vOlA3YZAbfoo6xdx1YWYzaCQl_-eibck9i7p04DkvUvy5zqxMSmYS_LHpHAuKRiTFnNJof2K94V8us0FROC9DOfE9Hd07zA_aHuVkgf51GHT59peBKMapHDNH3GJBlWZV7k2edYH2va_PwEAAP__DBRFDg==

+statement ok
+PREPARE foo AS SELECT * FROM data;
+
+statement ok
+SET TRACING = "on", cluster;
+
+statement ok
+EXECUTE foo;
+
+statement ok
+SET TRACING = "off";
+
+# The first execution should miss the query cache.
+query T
+SELECT message FROM [SHOW TRACE FOR SESSION] WHERE message LIKE 'will distribute plan%';
+----
+will distribute plan: true
+
```

**Comment by leolong0325** [comment]
Thanks for your reply. I tried SET TRACING = "on"; and it can display the value of the distribution field normally, which also meets my expectations.

Thanks again for your answer.
Best regards！
