### ISSUE TITLE
metric: changefeed metrics broken down by CIDR

### ISSUE THREAD

**Issue by andrewbaptist** [cockroachdb/cockroach#130097]
We need to add the metrics changefeed.network.write_bytes and changefeed.network.read_bytes to track all network bytes sent and received by the changefeed sinks. These metrics will allow accurate network billing. 

This is the remaining work from #128674.

Jira issue: CRDB-41873

**Comment by rohan-joshi** [comment]
**Objective:** Calculate, report on, and bill on the network bytes sent and received by changefeed sinks. These will be used as part of network billing.

**Requirements:**
* Metrics: 
** `changefeed.network.write_bytes` should capture the number of bytes written to the target sink
**  `changefeed.network.read_bytes` in theory, this should be the number of bytes read by the sink consuming whatever messages are sent back from the target sink
* Sinks, in priority order:
** Kafka 
** Cloud Storage ({{s3://}}, {{azure://}}, {{gs://}}) 
** Webhook: {{webhook-https://}} 
** google cloud pub/sub: {{gcpubsub}} 
** External connections: {{external://}} 

This is the remaining work from #128674.

**Comment by asg0451** [comment]
next todos based on the above prioritization:
- [ ] validate that cloudstorage sinks work 
- [ ] kafka 2 - (@andrewbaptist)
- [ ] kafka 1 - @asg0451 
- [ ] webhooks 1 - @andyyang890 
- [ ] webhooks 2 - me or andy, whoever's available first
