### ISSUE TITLE
ui: fake hover line doesn't reach top of graph

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#13001]
![screen shot 2017-01-19 at 11 54 09 am](https://cloud.githubusercontent.com/assets/6201335/22116298/0f71dc20-de3e-11e6-9aca-5800d966b5d8.png)

When hovering over one graph, the indicator lines on the other graph do not reach the top of the graph.

**Comment by vivekmenezes** [comment]
Another problem is that the hover lines across many graphs stacked vertically do not properly align.
