### ISSUE TITLE
include --cache value in the error: WARNING: recommended default value of --max-go-memory (129Gib) was truncated to 88GiB, consider reducing --max-sql-memory and/or --cache

### ISSUE THREAD

**Issue by Lukens4242** [cockroachdb/cockroach#130195]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

IHAC that has a cluster with 230gb of ram per node, 45% for max-sql-memory and 25% for cache.  When they do this they get a warning in the logs
`WARNING: recommended default value of --max-go-memory (129Gib) was truncated to 88GiB, consider reducing --max-sql-memory and/or --cache`

**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

Start a cluster where nodes have 230gb of memory and --max-go-memory is set to 45% and --cache is set to 25%

**Expected behavior**
We don't understand why the max-go-memory was truncated to 88GiB

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version 23.1.19
 - Server OS: k8s

**Additional context**
What was the impact?

Customer has upgraded a cluster from 22.2 to 23.1.  Since then they started getting a message in their logs about the value of max-go-memory being truncated.  WARNING: recommended default value of --max-go-memory (129Gib) was truncated to 88GiB, consider reducing --max-sql-memory and/or --cache  There are no performance issues at this time and recently a review of the cluster was done and found it to be healthy.  These nodes have 230gb of ram.  They are wondering why this message began to pop up post 23.1 and what (if anything) should be done about it.

Jira issue: CRDB-41918

**Comment by RaduBerinde** [comment]
Thanks for filing @Lukens4242 

The go memory limit was added in 23.1, which is why this message didn't show up before.
The maximum go memory limit of 88GiB is calculated as `90% * (system RAM) - 115% * (cache size)`.  If `--cache` is `25%`, the equation becomes `61.25%*(system RAM)`. This suggests that the cockroach process thinks the total system memory is around 140GB. This is possible if the k8s container or `cgroups` was configured with a memory limit.
