### ISSUE TITLE
crosscluster/logical: ldr tables failing SQL statements after upgrade.

### ISSUE THREAD

**Issue by shailendra-patel** [cockroachdb/cockroach#130137]
After upgrading `drt-ldr` clusters from version 24.2 → 24.3, cluster started seeing significant SQL Statement errors. 

Bidirectional LDR stream is configured on `ycsb.public.usertable`, after upgrade `SELECT` statements started failing with below error:

```shell
roachprod@localhost:26257/ycsb> select * from usertable;                                                                                                                                                 
ERROR: internal error: unexpected error from the vectorized engine: null_value_error: non-nullable column "usertable:field0" with no value! Index scanned was "usertable_pkey" with the index key columns (ycsb_key) and the values ('user11501846402603769733')
```

The schema of this table is:

```
CREATE TABLE public.usertable (
  ycsb_key VARCHAR(255) NOT NULL,
  field0 STRING NOT NULL,
  field1 STRING NOT NULL,
  field2 STRING NOT NULL,
  field3 STRING NOT NULL,
  field4 STRING NOT NULL,
  field5 STRING NOT NULL,
  field6 STRING NOT NULL,
  field7 STRING NOT NULL,
  field8 STRING NOT NULL,
  field9 STRING NOT NULL,
  expired_at TIMESTAMPTZ NOT NULL DEFAULT now():::TIMESTAMPTZ + '00:30:00':::INTERVAL,
  crdb_replication_origin_timestamp DECIMAL NOT VISIBLE NULL ON UPDATE NULL,
  CONSTRAINT usertable_pkey PRIMARY KEY (ycsb_key ASC)
) WITH (ttl = 'on', ttl_expiration_expression = 'expired_at', ttl_job_cron = '0 */3 * * *')
```

Inspection of this particular row shows what appears to be a key where we've only written the `expired_at` and `crdb_replication_origin_timestamp` column:

```
          crdb_internal.pretty_key          |             crdb_internal.pretty_value
--------------------------------------------+------------------------------------------------------
  /Table/111/2/"user11501846402603769733"/0 | /TUPLE/13:13:Decimal/1725426751445858935.0000000000
(1 row)
```

### Empty previous value on deletion event

The KV write path code currently assumes any event without a previous value is an insert:

https://github.com/cockroachdb/cockroach/blob/b6862f42d3a229cad814b61d5a77a420afb540b5/pkg/ccl/crosscluster/logical/lww_kv_processor.go#L197-L219

This assumption seems like it _could_ be incorrect for rangefeeds in general since the previous value before a deletion tombstone could have been GC'd.  Treating this deletion event as an insertion event could likely produce a row like that observed above since the two values we did write are the only two values we are able to write without any data in the event (the `expired_at` field is populated via the default expression and the `crdb_replication_origin_timestamp` field is populated via the MVCC timestamp of the event.)

**Questions with this theory**

- How did the previous value get garbage collected? As far as we understand, in the absence of range keys, a value will only be garbage collected if the value _shadowing_ that value has passed the gc threshold.  In this case, the value shadowing it is the delete, which should have still be protected by a protected timestamp.
- Are we sure there were no rangekeys in play? We checked for rangekeys and found none, but those rangekeys may also have been GC'd by the time we observed the table.
- Are we sure there isn't a PTS-management bug?

More details in thread https://cockroachlabs.slack.com/archives/C05FHJJ0MD0/p1725428949619129

Jira issue: CRDB-41886

**Comment by msbutler** [comment]
@stevendanna during tech pod today, i think you came up with an example where the lost delete bug could cause this delete with no prev value bug. After thinking through it again,  I'm having trouble constructing the story. Here's my understanding of the lost delete bug:
t1.  UPDATE key=1 on Server A
t2.  DELETE key=1 on Server B
t3.  Server B receives the update from t1 and applies it at t3. Meaning that its local MVCC timestamp is t3 and OriginTS is t1. Given this update is older than the delete, according to the OriginTS, this update should not get written. However, currently it does.

I don't see how this could lead to a replicated delete without a prev value?

**Comment by stevendanna** [comment]
I am 90% sure I understand what happened here.

1. The KV processor has a bug in which a delete with no previous value is mishandled.
2. The ycsb workload was configure to issue DELETES at a 10% rate.  My understanding of the custom ycsb workload is that this may often be issuing deletes on keys that don't exists.
3. A delete on a key that doesn't exist will create a rangefeed event with no previous value.

I also looked at the mvcc_timestamp and origin_timestamp of two broken rows and found that they were very close together:

```
Key 1:
1725436779103012639  -> Wed Sep 04 2024 07:59:39 GMT+0000
1725436788332727277  -> Wed Sep 04 2024 07:59:48 GMT+0000

Key 2:
1725465074690228737 -> Wed Sep 04 2024 15:51:14 GMT+0000
1725465088722411549 -> Wed Sep 04 2024 15:51:28 GMT+0000
```

This makes it rather unlikely that this is GC related.
