### ISSUE TITLE
gossip: I wish it were easier to view the deserialized gossip values a node has

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#13023]
On multiple occasions now, I've wished that I could see some particular info from the `/_status/gossip/local` page while looking into an issue. However, the actual gossip values are all serialized/encoded and thus not easy to use. It'd be nice if the real values were easier to get at.

While reworking the `serverpb/status.proto` protos to let us be smarter about printing meaningful values would be nice, realistically this likely just means some instructions and perhaps a small tool for taking a "rawValue" from the gossip debug page and printing out something more meaningful.

Also, for what it's worth, on all occasions that I've wanted to read gossip values, I was primarily interested in node liveness entries, so perhaps an easier alternative would just be to have a node liveness debug page.

**Comment by dianasaur323** [comment]
@a-robinson I'm moving optimizations to the debug page over to Q3 2017, but please revise if you disagree
