### ISSUE TITLE
sql: handle type specifiers in CastExpr evaluation for all types

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#13024]
At the moment, we ignore column type specifiers when evaluating type casts for all types other than `STRING`. This means that we do not respect type limits like precision and scale when casting. We should respect these type constraints, and try to merge the handling of them with their respective handling in table insertion code. Example:

Postgres:
```
postgres=# SELECT 123.456::NUMERIC(3);
 numeric
---------
     123
```

Cockroach:
```
root@:26257> SELECT 123.456::NUMERIC(3);
+---------------------+
| 123.456::NUMERIC(3) |
+---------------------+
|             123.456 |
+---------------------+
```

**Comment by MohamedElqdusy** [comment]
Hi @nvanbenschoten, I think It's working with NUMERIC now.
root@:26257/> SELECT 123.456::NUMERIC(3);
+---------------------+
| 123.456::NUMERIC(3) |
+---------------------+
|                     123|
+---------------------+

**Comment by jordanlewis** [comment]
This is indeed solved.
