### ISSUE TITLE
c-deps: upgrade krb5

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/cockroach#130266]
We currently run version [1.17](https://github.com/cockroachdb/krb5/tree/a1b8c3b2a397cd8132328e95613319d490684969). There is a [1.21.3 available upstream](https://github.com/krb5/krb5/tags) (at the time of writing). We're at least six years behind in updates.

Upgrade to the latest and greatest.

Jira issue: CRDB-41962

Epic CRDB-37617

**Comment by RaduBerinde** [comment]
We should probably also upgrade older CRDB versions to at least 1.17.2 which has some bug fixes on top of 1.17.
