### ISSUE TITLE
gossip: Restarting a cluster with new hostnames/IPs doesn't work in many cases

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#13027]
This was found while testing out the restore functionality from a 10-node cluster backup onto a new set of 10 nodes. When starting up the cluster with three different configurations of `--join` parameters on the 10 nodes, something different happened each time:

1. With `--join=<node-1>` for nodes 2-10 and `--join=""` for node 1: none of the nodes initialized properly. They all got stuck waiting to be connected to the cluster via gossip.
1. With `--join=<node-(i-1)>` for nodes i=2 to i=10, and `--join=""` for node 1: nodes 4-10 initialized properly. Nodes 1-3 got stuck waiting to be connected to the cluster via gossip.
1. With `--join=<comma-separated-list-of-all-nodes>` for all the nodes in the cluster, including node 1: the cluster started up properly.

Because all of the nodes were new, it's worth noting that none of the addresses saved from the gossip network before the backup were usable on the new nodes. Thus, while all the nodes had a store full of data, they didn't know where the other nodes were other than what they got in the `--join` parameter.

While the details vary a little (see below), the core issue in both of the first two cases is that nodes don't serving incoming connections until they have initialized themselves, where "initialized themselves" effectively means that the node is connected enough to know the cluster ID. This means that only nodes with a copy of the first range can properly bootstrap themselves if they're unable to connect to another node, because they're the only ones that will add the cluster ID to their local gossip infostore.

In the first case above, because node 1 didn't have a copy of range 1, it is unable to initialize itself. Because it doesn't get initialized, it doesn't start accepting incoming connections, and thus it doesn't get the cluster ID even though it has incoming connections from 3 nodes that do have the cluster ID (the 3 that have a copy of range 1). Thus the cluster never gets going -- 3 nodes are up and running in some sense, but don't know about each other so they can't do anything.

In the second case above, nodes 4-10 work because node 4 is the lowest node ID that had a copy of range 1. Thus, it initializes itself and accepts the incoming connection from node 5, which allowed node 5 to initialize, which allowed node 6 to initialize, etc. Nodes 1-3 are stuck forever because they have no outgoing gossip connection to any of nodes 4-10.

In the third case above, all nodes work because they all attempt to connect to at least one node that has a copy of range 1.

-------------

It would be conceivable to say that the current state of things is ok, and that you should specify all the nodes in all the join flags (or at the very least ensure that it's a fully-connected directed graph). That seems a bit prescriptive and error-prone, though. If a node was able to learn from incoming gossip connections during startup, pretty much any configuration of `--join` flags would work.

@mjibson @spencerkimball

**Comment by a-robinson** [comment]
@mjibson this isn't anything blocking the restore effort for now, right? At some point before release it'd be worth thinking about how this issue might affect users at their most frantic moments (i.e. when their database is down and they're trying to restore it for the first time) and what we should do to help them, whether it's documentation and help messages about how to set join flags or making gossip more resilient to different configurations.

**Comment by a-robinson** [comment]
cc @jseldess

**Comment by bdarnell** [comment]
This is another argument in favor of revamping the "empty join" method of initialization. Unless you go back and add the `--join` flag to the first node after initialization, your cluster is left in a more fragile state. 

But requiring the `--join` flags to be a fully-connected directed graph is also setting the bar too high. We should fix this so that nodes without range 1 can accept connections from those that have it so we can get the gossip network connected.

**Comment by mjibson** [comment]
At least one bug was fixed that allowed our backup work to proceed, and we successfully restored a 2TB cluster to operation without changing the data to get around this issue. So no need to keep this open for my benefit.

**Comment by jseldess** [comment]
@bdarnell, @a-robinson, in terms of doc updates for v1, should we update relevant docs to recommend starting nodes 2 and beyond with all known node IPs/hostnames in the `--join` flag, and recommend stopping and restarting node 1 with all known node IPs/hostnames in the `--join` flag?

Anything else?

**Comment by spencerkimball** [comment]
@jseldess I think we should recommend that all nodes join the same node on startup.

For initialization of a cluster node 1 has empty `-join` flag, and node 2 -  node N have `-join=node1`.

When restarting an existing cluster with completely new addresses, We should just recommend that all nodes specify `-join=node1`, **including** node1.

**Comment by jseldess** [comment]
Limitation documented with https://github.com/cockroachdb/docs/pull/1381
