### ISSUE TITLE
crosscluster/logical: provide initial and catchup scan observability 

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#130367]
Suppose we spun up a goroutine in event_stream.go which computes the number of ranges conducting a catchup scan or initial scan (i.e. num ranges with a frontier over 5 mins behind). Then, using the checkpoint events, we could send info over to the consumer about lagging spans, which they could use to provide job progress obs on the percent of spans caught up. 

Jira issue: CRDB-42017

Epic CRDB-40869

**Comment by msbutler** [comment]
this still needs to be done.

**Comment by jeffswenson** [comment]
There's a limitation in job progress which is we can only export a watermark or a fraction completed. So the initial cut of this feature will only show progress for the initial scan.

**Comment by msbutler** [comment]
completed
