### ISSUE TITLE
sql: syntax X'...' should be byte array not string

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#13049]
CockroachDB supports the non-standard extension syntax `x'.....'` to enter a literal string using hexadecimal codes only.

This is all fine and dandy but it's not so clear to me that we have a use case for it.

Meanwhile, we do have a use case for *entering raw bytes containing possibly invalid UTF-8 sequences (a byte array) in hexadecimal*, for example a uuid value or a SHA hash, but CockroachDB does not provide a compact syntax to do so yet -- the best we have so far is `b'\xAA\xAA\xAA\xAA...` which is 50% less efficient to type.

It seems to me we should simply repurpose the syntax `x'....'` to become a byte array literal (BCONST) instead of a string array literal (SCONST). 

@jordanlewis what do you think? (You added this support initially)

cc @nvanbenschoten

**Comment by jordanlewis** [comment]
I like that idea. I agree that the raw bytes use case is more interesting and useful than the hex string literal one.

I'm hesitant for 2 reasons. First, we've already added `x'...'` and announced its meaning, so this change would be breaking for any users (perhaps none?) that might have incorporated that syntax into their programs already. Second, repurposing the syntax would move us farther away from Postgres compatibility.

I think I'd prefer to implement the escape string `\x` that Postgres provides to solve this problem. It's detailed [here](https://www.postgresql.org/docs/9.1/static/datatype-binary.html). It allows entering byte array literals in hexadecimal with the syntax `e'\\xDEADBEEF'`.

**Comment by knz** [comment]
1. my guess is that nobody is using it, for the simple reason that we're not well documenting it yet.

2. we're still in beta so we can change that.

3. I don't care about pg compatibility in this regard. It just so is that pg supports *zero* way to enter byte array via hex codes in a convenient way.

4. The "escape string `\x` feature for bytea" you refer to is insane. It's been grown organically over time, adding patches over patches of wonky specifications. This is simply garbage. If we are to "build this product right" we must absolutely avoid this until a customer pays us big $$$$ to do this sh*t.

**Comment by knz** [comment]
That is to say, if you're worried about a possible contradictory overlap of syntax, we can also opt for a different prefix than "`x'`".

**Comment by bdarnell** [comment]
This feature came from [mysql](https://dev.mysql.com/doc/refman/5.7/en/hexadecimal-literals.html) where it produces a binary string, so I'd support making this change.

**Comment by knz** [comment]
@bdarnell which feature? The one we implement now or the ugly/wonky thing that pg advertises?

**Comment by jordanlewis** [comment]
I forgot that we got this syntax from mysql. I retract my objection to redefining it to produce byte arrays.

**Comment by bdarnell** [comment]
@knz The one we implement now. We implemented it before/instead of the postgres version because it makes so much more sense.
