### ISSUE TITLE
sql: factor the handling of data types that differ only in their name

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#13045]
Stimulated by the discussion on  #12641:

- Myself:

  > Given the amount of redundancy caused by STRING and NAME existing side by side, or INT and OID, I would suggest investigating if we could have one field in the column type with its "behavior type" (the code that runs) and another one with its "advertised type". Have the latter nullable so that if it doesn't exist yet it defaults to the behavior type, for backward compatibility.

- @nvanbenschoten:

  > That's actually exactly how I initially implemented this, but it quickly became apparent that the approach caused more issues than it solved. To demonstrate why this is, take a look at all references to ColumnType_OID. Out of the 7 places that the value is used, 5 of them would need special handling for DOids (either calling parser.NewDOid or returning parser.TypeOid). Adding a new "advertised type" field would mean that we would need to break these "flat" enumeration switch statements into nested switches, which makes the code less readable and less pleasant to work with.

To which I counter-argue that if either approach results in too much redundancy and neither is better than the other, that means we still have a DRY problem to solve.

**Comment by knz** [comment]
This is especially worrying in the light of #12526 #12530.

**Comment by cuongdo** [comment]
Is there more work to be done here?

**Comment by knz** [comment]
No, this was actually solved by #12641. Well spotted.
