### ISSUE TITLE
crosscluster/logical: update LDR job status after resume

### ISSUE THREAD

**Issue by shailendra-patel** [cockroachdb/cockroach#130565]
LDR job status is not updated correctly after resume.

If LDR job is paused because of an error and then resumed the job status is not updated correctly.
<img width="1514" alt="Screenshot 2024-09-12 at 8 13 10 PM" src="https://github.com/user-attachments/assets/d017d3e5-a4aa-4ae4-935f-2483a5e97f13">

Jira issue: CRDB-42125

Epic CRDB-41465

**Comment by msbutler** [comment]
fixed inadvertently
