### ISSUE TITLE
sql: panic in FLOAT -> DECIMAL conversion

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#13051]
```sql
SELECT 'NaN'::FLOAT::DECIMAL
```

-> server panic

It's actually written black on white in the comment for `decimal.SetFromFloat`:
```
// The function will panic if the float is NaN or ±Inf.
```

cc @mjibson -- is this something we want to fix or are we just merging your new decimal code soon?

**Comment by mjibson** [comment]
I think we can just ignore it for now. In my apd branch this same query results in:

```
> SELECT 'NaN'::FLOAT::DECIMAL;
pq: parse mantissa: NaN
```

So it'll get fixed then, and once I add NaN support it'll work for realsies.

**Comment by knz** [comment]
Then you can just close this one when you merge apd support.
Thanks!
