### ISSUE TITLE
Backup creation failing on tpcc table in drt-large

### ISSUE THREAD

**Issue by csgourav** [cockroachdb/cockroach#130858]
We are seeing backup creation failure issue on drt-large 
`
exhausted retries: running distributed backup to export 14 ranges: exporting /Table/109/1/"\x{80"/1017/10-a0"}: replica unavailable: (n10,s76):4 unable to serve request to r54502:/Table/108/1/"\x{80"/1104-a0"} [(n5,s37):10, (n36,s285):2, (n37,s293):9, (n10,s76):4, (n4,s31):6, (n21,s164):431LEARNER, next=432, gen=1203, sticky=1725538848.013655569,0]: closed timestamp: 1725592937.647900868,0 (2024-09-06 03:22:17); raft status: {"id":"4","term":171,"vote":"2","commit":5764068,"lead":"2","raftState":"StateFollower","applied":5764068,"progress":{},"leadtransferee":"0"}: encountered poisoned latch /Local/RangeID/54502/r/AbortSpan/"aa29381d-fd46-43ab-ac60-b5c7f7ba1430"@0,0`

Seems related to `kv layer` based on the `encountered poisoned latch` message.

We also saw one under-replicated range for a long time.

More details in this thread [[link](https://cockroachlabs.slack.com/archives/C0KB9Q03D/p1725970819027759)]

Jira issue: CRDB-42269

**Comment by tbg** [comment]
@csgourav as far as I can tell, the issue resolved on September 14. The affected range, r54502, no longer exists in the system. No replicas are currently unavailable, as far as I can see. Could you check whether backups are really failing, and if still the case, whether the symptoms have changed? Thank you.

**Comment by csgourav** [comment]
@tbg We recreated the whole cluster, moved to on-demand nodes. Likely that the issue might not exist, will update. Created this to track the old issue, if that can be debugged from logs to help root cause the issue. The logs are there on [datadog](https://us5.datadoghq.com/dashboard/pbe-ic2-3qt/drt?fromUser=true&refresh_mode=sliding&tpl_var_cluster%5B0%5D=drt-large&tpl_var_workload_cluster%5B0%5D=workload-large&from_ts=1726569857819&to_ts=1726573457819&live=true)

**Comment by tbg** [comment]
Okay- thank you. Please state these circumstances next time, it is difficult to engage in their absence. I will see what can be gleaned from the historical logs.

**Comment by tbg** [comment]
The range was definitely messed up, it was unable to get a snapshot through that it needed, and there was also a large uncommitted raft log. It's difficult to see through the noise though.
I have a DD notebook [here](https://us5.datadoghq.com/notebook/129043/2024-09-18-investigating-unavailable-replica-on-drt-large?range=574440000&start=1726092000000&live=false) but basically don't think there's much more we can learn from this other than the above.

Thanks for putting this on my radar anyway, it was nice to interact with the DRT clusters a bit.
