### ISSUE TITLE
sql: implement generate_subscripts builtin

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#13098]
The [`generate_subscripts(array anyarray, dim int)`](https://www.postgresql.org/docs/9.1/static/functions-srf.html) builtin returns the set of valid subscripts for the given array along the given dimension.

pgcli uses this function. Implementing this requires fleshing out support for set-returning functions, which will probably get done as a part of #12785.

**Comment by jordanlewis** [comment]
More specifically, this is blocked by #11215.

**Comment by jordanlewis** [comment]
This is now required by Rails 5.1.0 - our adapter works around it, but it'd be great to support this so we can remove the workaround from the adapter.

**Comment by george-oakling** [comment]
+1 autoupdate of models by strongloop/loopback is also using the function.

**Comment by jordanlewis** [comment]
@BramGruneir you could probably tackle this quickly at this point, right?

**Comment by BramGruneir** [comment]
Yep, looks pretty straight forward.  

@knz for triage, this should be an easy win.
