### ISSUE TITLE
rocksdb: Use `warn_unused_result` where appropriate

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#13101]
If we added the `warn_unused_result` attribute to functions in `storage/engine/rocksdb/db.cc` whose return values indicate success or failure, we could avoid oversights like #13099.

**Comment by bdarnell** [comment]
See #14416 for another issue that would have been prevented by this.

**Comment by petermattis** [comment]
For #14416, how would we add the `warn_unused_result` attribute to `WriteBatch::Iterate`?

**Comment by tamird** [comment]
Speaking of which: https://github.com/cockroachdb/cockroach/blob/95deaf6/pkg/ccl/storageccl/engineccl/db.cc#L36

**Comment by dianasaur323** [comment]
@petermattis can I close this out given #14421 is merged?

**Comment by petermattis** [comment]
Yeah, this isn't fixed, but I'm not sure what else to do here. We can't add attributes to the RocksDB methods without modifying the RocksDB source itself. Moving to the Later milestone as there is nothing urgent to do here.
