### ISSUE TITLE
Sentry: panic.go:770: runtime error: index out of range [126] with length 33
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:770
  | runtime.goPanicInde...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#131096]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5879776309/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5879776309/?referrer=webhooks_plugin)

Panic Message:

```
panic.go:770: runtime error: index out of range [126] with length 33
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:770
  | runtime.goPanicIndex
  | 	GOROOT/src/runtime/panic.go:114
  | github.com/cockroachdb/cockroach/pkg/util/cidr.(*Lookup).setDestinations
  | 	github.com/cockroachdb/cockroach/pkg/util/cidr/cidr.go:283
  | github.com/cockroachdb/cockroach/pkg/util/cidr.(*Lookup).setURL
  | 	github.com/cockroachdb/cockroach/pkg/util/cidr/cidr.go:248
  | github.com/cockroachdb/cockroach/pkg/util/cidr.(*Lookup).refresh
  | 	github.com/cockroachdb/cockroach/pkg/util/cidr/cidr.go:149
  | github.com/cockroachdb/cockroach/pkg/util/cidr.(*Lookup).Start.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/cidr/cidr.go:121
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:484
  | runtime.goexit
  | 	src/runtime/asm_amd64.s:1695
Wraps: (2) runtime error: index out of range [126] with length 33
Error types: (1) *withstack.withStack (2) runtime.boundsError
-- report composition:
runtime.boundsError
panic.go:770: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_amd64.s#L1694-L1696](src/runtime/asm_amd64.s#L1694-L1696)
[https://github.com/cockroachdb/cockroach/blob/f90452c54e22059c5e1197f3bd62deee8aec33b2/pkg/util/stop/stopper.go#L483-L485](https://github.com/cockroachdb/cockroach/blob/f90452c54e22059c5e1197f3bd62deee8aec33b2/pkg/util/stop/stopper.go#L483-L485)
[https://github.com/cockroachdb/cockroach/blob/f90452c54e22059c5e1197f3bd62deee8aec33b2/pkg/util/cidr/cidr.go#L120-L122](https://github.com/cockroachdb/cockroach/blob/f90452c54e22059c5e1197f3bd62deee8aec33b2/pkg/util/cidr/cidr.go#L120-L122)
[https://github.com/cockroachdb/cockroach/blob/f90452c54e22059c5e1197f3bd62deee8aec33b2/pkg/util/cidr/cidr.go#L148-L150](https://github.com/cockroachdb/cockroach/blob/f90452c54e22059c5e1197f3bd62deee8aec33b2/pkg/util/cidr/cidr.go#L148-L150)
[https://github.com/cockroachdb/cockroach/blob/f90452c54e22059c5e1197f3bd62deee8aec33b2/pkg/util/cidr/cidr.go#L247-L249](https://github.com/cockroachdb/cockroach/blob/f90452c54e22059c5e1197f3bd62deee8aec33b2/pkg/util/cidr/cidr.go#L247-L249)
[https://github.com/cockroachdb/cockroach/blob/f90452c54e22059c5e1197f3bd62deee8aec33b2/pkg/util/cidr/cidr.go#L282-L284](https://github.com/cockroachdb/cockroach/blob/f90452c54e22059c5e1197f3bd62deee8aec33b2/pkg/util/cidr/cidr.go#L282-L284)
[GOROOT/src/runtime/panic.go#L113-L115](GOROOT/src/runtime/panic.go#L113-L115)
[GOROOT/src/runtime/panic.go#L769-L771](GOROOT/src/runtime/panic.go#L769-L771)
</details>

```
src/runtime/asm_amd64.s in runtime.goexit at line 1695
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 484
pkg/util/cidr/cidr.go in pkg/util/cidr.(*Lookup).Start.func2 at line 121
pkg/util/cidr/cidr.go in pkg/util/cidr.(*Lookup).refresh at line 149
pkg/util/cidr/cidr.go in pkg/util/cidr.(*Lookup).setURL at line 248
pkg/util/cidr/cidr.go in pkg/util/cidr.(*Lookup).setDestinations at line 283
GOROOT/src/runtime/panic.go in runtime.goPanicIndex at line 114
GOROOT/src/runtime/panic.go in runtime.gopanic at line 770
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v24.3.0-alpha.00000000 |
| Go Version | go1.22.5 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v24.2.0-alpha.2-1635-gf90452c54e2 |
| Cockroach SHA | f90452c54e22059c5e1197f3bd62deee8aec33b2 |
| # of CPUs | 4 |
| # of Goroutines | 890 |

Jira issue: CRDB-42371

**Comment by yuzefovich** [comment]
dup of #130814
