### ISSUE TITLE
Sentry: validate.go:409: relation × (5136322): depended-on-by relation × (5136326) is dropped
(1)
Wraps: (2) keys: [sql.schema.validation_errors.read.backward_references.relation sql.schema.validati...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#131088]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5879321916/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5879321916/?referrer=webhooks_plugin)

Panic Message:

```
validate.go:409: relation × (5136322): depended-on-by relation × (5136326) is dropped
(1)
Wraps: (2) keys: [sql.schema.validation_errors.read.backward_references.relation sql.schema.validation_errors.read.backward_references.relation sql.schema.validation_errors.read.backward_references.relation]
Wraps: (3) secondary error attachment
  | relation × (5138039): invalid depended-on-by relation back reference: referenced descriptor ID 5138043: referenced descriptor not found
  | (1) secondary error attachment
  |   | relation × (5146744): invalid depended-on-by relation back reference: referenced descriptor ID 5146748: referenced descriptor not found
  |   | (1) keys: [sql.schema.validation_errors.read.backward_references.relation]
  |   | Wraps: (2) attached stack trace
  |   |   -- stack trace:
  |   |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate.(*validationErrorAccumulator).decorate
  |   |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate/validate.go:247
  |   |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate.(*validationErrorAccumulator).Report
  |   |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate/validate.go:182
  |   |   | [...repeated from below...]
  |   | Wraps: (3) relation × (5146744)
  |   | Wraps: (4) assertion failure
  |   | Wraps: (5) attached stack trace
  |   |   -- stack trace:
  |   |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/tabledesc.(*wrapper).ValidateBackReferences
  |   |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/tabledesc/validate.go:292
  |   |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate.Validate.func3
  |   |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate/validate.go:110
  |   |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate.(*validationErrorAccumulator).validateDescriptorsAtLevel
  |   |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate/validate.go:198
  |   |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate.Validate
  |   |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate/validate.go:105
  |   |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).Validate
  |   |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/validate.go:40
  |   |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).finalizeDescriptors
  |   |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:666
  |   |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.getDescriptorsByID
  |   |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:220
  |   |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).aggregateAllLayers
  |   |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:1023
  |   |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).GetAllComments
  |   |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:741
  |   |   | github.com/cockroachdb/cockroach/pkg/sql.init.func28
  |   |   | 	github.com/cockroachdb/cockroach/pkg/sql/crdb_internal.go:5901
  |   |   | github.com/cockroachdb/cockroach/pkg/sql.(*virtualDefEntry).getPlanInfo.func1.1
  |   |   | 	github.com/cockroachdb/cockroach/pkg/sql/virtual_schema.go:661
  |   |   | github.com/cockroachdb/cockroach/pkg/sql.setupGenerator.func3
  |   |   | 	github.com/cockroachdb/cockroach/pkg/sql/virtual_table.go:127
  |   |   | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  |   |   | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:485
  |   |   | runtime.goexit
  |   |   | 	src/runtime/asm_amd64.s:1695
  |   | Wraps: (6) invalid depended-on-by relation back reference
  |   | Wraps: (7) referenced descriptor ID 5146748: referenced descriptor not found
  |   |   | -- cause hidden behind barrier
  |   |   | referenced descriptor ID 5146748: referenced descriptor not found
  |   |   | (1) attached stack trace
  |   |   |   -- stack trace:
  |   |   |   | github.com/cockroachdb/cockroach/pkg/sql/catalog.NewReferencedDescriptorNotFoundError
  |   |   |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/errors.go:102
  |   |   |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate.(*validationDescGetterImpl).GetDescriptor
  |   |   |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate/validate.go:297
  |   |   |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/tabledesc.(*wrapper).ValidateBackReferences
  |   |   |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/tabledesc/validate.go:290
  |   |   |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate.Validate.func3
  |   |   |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate/validate.go:110
  |   |   |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate.(*validationErrorAccumulator).validateDescriptorsAtLevel
  |   |   |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate/validate.go:198
  |   |   |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate.Validate
  |   |   |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate/validate.go:105
  |   |   |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).Validate
  |   |   |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/validate.go:40
  |   |   |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).finalizeDescriptors
  |   |   |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:666
  |   |   |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.getDescriptorsByID
  |   |   |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:220
  |   |   |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).aggregateAllLayers
  |   |   |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:1023
  |   |   |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).GetAllComments
  |   |   |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:741
  |   |   |   | github.com/cockroachdb/cockroach/pkg/sql.init.func28
  |   |   |   | 	github.com/cockroachdb/cockroach/pkg/sql/crdb_internal.go:5901
  |   |   |   | github.com/cockroachdb/cockroach/pkg/sql.(*virtualDefEntry).getPlanInfo.func1.1
  |   |   |   | 	github.com/cockroachdb/cockroach/pkg/sql/virtual_schema.go:661
  |   |   |   | github.com/cockroachdb/cockroach/pkg/sql.setupGenerator.func3
  |   |   |   | 	github.com/cockroachdb/cockroach/pkg/sql/virtual_table.go:127
  |   |   |   | [...repeated from below...]
  |   |   | Wraps: (2) referenced descriptor ID 5146748
  |   |   | Wraps: (3) attached stack trace
  |   |   |   -- stack trace:
  |   |   |   | github.com/cockroachdb/cockroach/pkg/sql/catalog.init
  |   |   |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/errors.go:99
  |   |   |   | runtime.doInit1
  |   |   |   | 	GOROOT/src/runtime/proc.go:7206
  |   |   |   | runtime.doInit
  |   |   |   | 	GOROOT/src/runtime/proc.go:7173
  |   |   |   | runtime.main
  |   |   |   | 	GOROOT/src/runtime/proc.go:253
  |   |   |   | runtime.goexit
  |   |   |   | 	src/runtime/asm_amd64.s:1695
  |   |   | Wraps: (4) referenced descriptor not found
  |   |   | Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.leafError
  |   | Error types: (1) *telemetrykeys.withTelemetry (2) *withstack.withStack (3) *errutil.withPrefix (4) *assert.withAssertionFailure (5) *withstack.withStack (6) *errutil.withPrefix (7) *barriers.barrierErr
  | Wraps: (2) keys: [sql.schema.validation_errors.read.backward_references.relation]
  | Wraps: (3) attached stack trace
  |   -- stack trace:
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate.(*validationErrorAccumulator).decorate
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate/validate.go:247
  |   | ...
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_amd64.s#L1694-L1696](src/runtime/asm_amd64.s#L1694-L1696)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/util/stop/stopper.go#L484-L486](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/util/stop/stopper.go#L484-L486)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/virtual_table.go#L126-L128](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/virtual_table.go#L126-L128)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/virtual_schema.go#L660-L662](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/virtual_schema.go#L660-L662)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/crdb_internal.go#L5900-L5902](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/crdb_internal.go#L5900-L5902)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/catalog/descs/collection.go#L740-L742](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/catalog/descs/collection.go#L740-L742)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/catalog/descs/collection.go#L1022-L1024](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/catalog/descs/collection.go#L1022-L1024)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/catalog/descs/descriptor.go#L219-L221](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/catalog/descs/descriptor.go#L219-L221)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/catalog/descs/descriptor.go#L665-L667](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/catalog/descs/descriptor.go#L665-L667)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/catalog/descs/validate.go#L39-L41](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/catalog/descs/validate.go#L39-L41)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/catalog/internal/validate/validate.go#L104-L106](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/catalog/internal/validate/validate.go#L104-L106)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/catalog/internal/validate/validate.go#L197-L199](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/catalog/internal/validate/validate.go#L197-L199)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/catalog/internal/validate/validate.go#L109-L111](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/catalog/internal/validate/validate.go#L109-L111)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/catalog/tabledesc/validate.go#L298-L300](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/catalog/tabledesc/validate.go#L298-L300)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/catalog/internal/validate/validate.go#L181-L183](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/catalog/internal/validate/validate.go#L181-L183)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/catalog/internal/validate/validate.go#L246-L248](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/catalog/internal/validate/validate.go#L246-L248)
[src/runtime/asm_amd64.s#L1694-L1696](src/runtime/asm_amd64.s#L1694-L1696)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/util/stop/stopper.go#L484-L486](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/util/stop/stopper.go#L484-L486)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/virtual_table.go#L126-L128](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/virtual_table.go#L126-L128)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/virtual_schema.go#L660-L662](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/virtual_schema.go#L660-L662)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/crdb_internal.go#L5900-L5902](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/crdb_internal.go#L5900-L5902)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/catalog/descs/collection.go#L740-L742](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/catalog/descs/collection.go#L740-L742)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/catalog/descs/collection.go#L1022-L1024](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/catalog/descs/collection.go#L1022-L1024)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/catalog/descs/descriptor.go#L219-L221](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/catalog/descs/descriptor.go#L219-L221)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/catalog/descs/descriptor.go#L665-L667](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/catalog/descs/descriptor.go#L665-L667)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/catalog/descs/validate.go#L39-L41](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/catalog/descs/validate.go#L39-L41)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/catalog/internal/validate/validate.go#L104-L106](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/catalog/internal/validate/validate.go#L104-L106)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/catalog/internal/validate/validate.go#L197-L199](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/catalog/internal/validate/validate.go#L197-L199)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/catalog/internal/validate/validate.go#L109-L111](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/catalog/internal/validate/validate.go#L109-L111)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/catalog/tabledesc/validate.go#L298-L300](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/catalog/tabledesc/validate.go#L298-L300)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/catalog/tabledesc/validate.go#L408-L410](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/catalog/tabledesc/validate.go#L408-L410)
</details>

```
src/runtime/asm_amd64.s in runtime.goexit at line 1695
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 485
pkg/sql/virtual_table.go in pkg/sql.setupGenerator.func3 at line 127
pkg/sql/virtual_schema.go in pkg/sql.(*virtualDefEntry).getPlanInfo.func1.1 at line 661
pkg/sql/crdb_internal.go in pkg/sql.init.func28 at line 5901
pkg/sql/catalog/descs/collection.go in pkg/sql/catalog/descs.(*Collection).GetAllComments at line 741
pkg/sql/catalog/descs/collection.go in pkg/sql/catalog/descs.(*Collection).aggregateAllLayers at line 1023
pkg/sql/catalog/descs/descriptor.go in pkg/sql/catalog/descs.getDescriptorsByID at line 220
pkg/sql/catalog/descs/descriptor.go in pkg/sql/catalog/descs.(*Collection).finalizeDescriptors at line 666
pkg/sql/catalog/descs/validate.go in pkg/sql/catalog/descs.(*Collection).Validate at line 40
pkg/sql/catalog/internal/validate/validate.go in pkg/sql/catalog/internal/validate.Validate at line 105
pkg/sql/catalog/internal/validate/validate.go in pkg/sql/catalog/internal/validate.(*validationErrorAccumulator).validateDescriptorsAtLevel at line 198
pkg/sql/catalog/internal/validate/validate.go in pkg/sql/catalog/internal/validate.Validate.func3 at line 110
pkg/sql/catalog/tabledesc/validate.go in pkg/sql/catalog/tabledesc.(*wrapper).ValidateBackReferences at line 299
pkg/sql/catalog/internal/validate/validate.go in pkg/sql/catalog/internal/validate.(*validationErrorAccumulator).Report at line 182
pkg/sql/catalog/internal/validate/validate.go in pkg/sql/catalog/internal/validate.(*validationErrorAccumulator).decorate at line 247
src/runtime/asm_amd64.s in runtime.goexit at line 1695
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 485
pkg/sql/virtual_table.go in pkg/sql.setupGenerator.func3 at line 127
pkg/sql/virtual_schema.go in pkg/sql.(*virtualDefEntry).getPlanInfo.func1.1 at line 661
pkg/sql/crdb_internal.go in pkg/sql.init.func28 at line 5901
pkg/sql/catalog/descs/collection.go in pkg/sql/catalog/descs.(*Collection).GetAllComments at line 741
pkg/sql/catalog/descs/collection.go in pkg/sql/catalog/descs.(*Collection).aggregateAllLayers at line 1023
pkg/sql/catalog/descs/descriptor.go in pkg/sql/catalog/descs.getDescriptorsByID at line 220
pkg/sql/catalog/descs/descriptor.go in pkg/sql/catalog/descs.(*Collection).finalizeDescriptors at line 666
pkg/sql/catalog/descs/validate.go in pkg/sql/catalog/descs.(*Collection).Validate at line 40
pkg/sql/catalog/internal/validate/validate.go in pkg/sql/catalog/internal/validate.Validate at line 105
pkg/sql/catalog/internal/validate/validate.go in pkg/sql/catalog/internal/validate.(*validationErrorAccumulator).validateDescriptorsAtLevel at line 198
pkg/sql/catalog/internal/validate/validate.go in pkg/sql/catalog/internal/validate.Validate.func3 at line 110
pkg/sql/catalog/tabledesc/validate.go in pkg/sql/catalog/tabledesc.(*wrapper).ValidateBackReferences at line 299
pkg/sql/catalog/tabledesc/validate.go in pkg/sql/catalog/tabledesc.(*wrapper).validateInboundTableRef at line 409
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v24.1.4 |
| Go Version | go1.22.5 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v24.1.4 |
| Cockroach SHA | a1cbd782a33a51f7500444373ccdaa81eb2ed971 |
| # of CPUs | 32 |
| # of Goroutines | 10794 |

Jira issue: CRDB-42367

**Comment by yuzefovich** [comment]
unactionable
