### ISSUE TITLE
sql: v24.2.2: LeafTxn incompatible with locking request ×

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#131159]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5886181034/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5886181034/?referrer=webhooks_plugin)

Panic Message:

```
txn_coord_sender.go:695: LeafTxn "sql txn" meta={id=67f2c35f key=/Min iso=Serializable pri=0.00851811 epo=0 ts=1726959736.737407393,0 min=1726959736.737407393,0 seq=0} lock=false stat=PENDING rts=1726959736.737407393,0 wto=false gul=1726959736.987407393,0 incompatible with locking request ×
(1)
Wraps: (2)
Wraps: (3)
Wraps: (4) tags: [n×,peer=×,client=×,hostssl=,user=×]
Wraps: (5) assertion failure
Wraps: (6)
  | (opaque error wrapper)
  | type name: github.com/cockroachdb/errors/withstack/*withstack.withStack
  | reportable 0:
  |
  | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*TxnCoordSender).maybeRejectIncompatibleRequest
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_coord_sender.go:695
  | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*TxnCoordSender).Send
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_coord_sender.go:491
  | github.com/cockroachdb/cockroach/pkg/kv.(*DB).sendUsingSender
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:1138
  | github.com/cockroachdb/cockroach/pkg/kv.(*Txn).Send
  | 	github.com/cockroachdb/cockroach/pkg/kv/txn.go:1282
  | github.com/cockroachdb/cockroach/pkg/sql/row.newTxnKVFetcher.makeTxnKVFetcherDefaultSendFunc.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/row/kv_batch_fetcher.go:281
  | github.com/cockroachdb/cockroach/pkg/sql/row.(*txnKVFetcher).fetch
  | 	github.com/cockroachdb/cockroach/pkg/sql/row/kv_batch_fetcher.go:589
  | github.com/cockroachdb/cockroach/pkg/sql/row.(*txnKVFetcher).nextBatch
  | 	github.com/cockroachdb/cockroach/pkg/sql/row/kv_batch_fetcher.go:872
  | github.com/cockroachdb/cockroach/pkg/sql/row.(*kvBatchFetcherHelper).NextBatch
  | 	github.com/cockroachdb/cockroach/pkg/sql/row/kv_batch_fetcher.go:1021
  | github.com/cockroachdb/cockroach/pkg/sql/row.(*KVFetcher).nextKV
  | 	github.com/cockroachdb/cockroach/pkg/sql/row/kv_fetcher.go:286
  | github.com/cockroachdb/cockroach/pkg/sql/row.(*KVFetcher).NextKV
  | 	github.com/cockroachdb/cockroach/pkg/sql/row/kv_fetcher.go:307
  | github.com/cockroachdb/cockroach/pkg/sql/colfetcher.(*cFetcher).NextBatch
  | 	github.com/cockroachdb/cockroach/pkg/sql/colfetcher/cfetcher.go:693
  | github.com/cockroachdb/cockroach/pkg/sql/colfetcher.(*ColBatchScan).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colfetcher/colbatch_scan.go:243
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils.(*CancelChecker).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils/cancel_checker.go:59
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils.(*vectorTypeEnforcer).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils/operator.go:157
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecbase.constNullOp.Next
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/colexec/colexecbase/const.eg.go:611
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils.(*vectorTypeEnforcer).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils/operator.go:157
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecbase.(*castOpNullAny).Next
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/colexec/colexecbase/cast.eg.go:1199
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils.(*vectorTypeEnforcer).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils/operator.go:157
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecbase.constNullOp.Next
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/colexec/colexecbase/const.eg.go:611
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils.(*vectorTypeEnforcer).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils/operator.go:157
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecbase.(*castOpNullAny).Next
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/colexec/colexecbase/cast.eg.go:1199
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils.(*vectorTypeEnforcer).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils/operator.go:157
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecbase.constInt64Op.Next
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/colexec/colexecbase/const.eg.go:368
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecbase.(*simpleProjectOp).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecbase/simple_project.go:124
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Materializer).next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:251
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Materializer).nextAdapter
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:276
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:152
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Materializer).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:282
  | github.com/cockroachdb/cockroach/pkg/sql.(*rowSourceToPlanNode).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/row_source_to_plan_node.go:79
  | github.com/cockroachdb/cockroach/pkg/sql.(*bufferNode).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/buffer.go:48
  | github.com/cockroachdb/cockroach/pkg/sql.(*updateNode).BatchedNext
  | 	github.com/cockroachdb/cockroach/pkg/sql/update.go:168
  | github.com/cockroachdb/cockroach/pkg/sql.(*rowCountNode).startExec
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_batch.go:173
Wraps: (7) LeafTxn "sql txn" meta={id=67f2c35f key=/Min iso=Serializable pri=0.00851811 epo=0 ts=1726959736.737407393,0 min=1726959736.737407393,0 seq=0} lock=false stat=PENDING rts=1726959736.737407393,0 wto=false gul=1726959736.987407393,0 incompatible with locking request ×
Error types: (1) *colexecerror.notInternalError (2) *colexecerror.notInternalError (3) *colexecerror.StorageError (4) *contexttags.withContext (5) *assert.withAssertionFailure (6) *errbase.opaqueWrapper (7) *errutil.leafError
-- report composition:
*errutil.leafError: LeafTxn "sql txn" meta={id=67f2c35f key=/Min iso=Serializable pri=0.00851811 epo=0 ts=1726959736.737407393,0 min=1726959736.737407393,0 seq=0} lock=false stat=PENDING rts=1726959736.737407393,0 wto=false gul=1726959736.987407393,0 incompatible with locking request ×
txn_coord_sender.go:695: *withstack.withStack (top exception)
*assert.withAssertionFailure
*contexttags.withContext: nsql1
*colexecerror.StorageError
*colexecerror.notInternalError
*colexecerror.notInternalError
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/plan_batch.go#L172-L174](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/plan_batch.go#L172-L174)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/update.go#L167-L169](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/update.go#L167-L169)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/buffer.go#L47-L49](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/buffer.go#L47-L49)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/row_source_to_plan_node.go#L78-L80](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/row_source_to_plan_node.go#L78-L80)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colexec/materializer.go#L281-L283](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colexec/materializer.go#L281-L283)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colexecerror/error.go#L151-L153](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colexecerror/error.go#L151-L153)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colexec/materializer.go#L275-L277](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colexec/materializer.go#L275-L277)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colexec/materializer.go#L250-L252](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colexec/materializer.go#L250-L252)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colexec/colexecbase/simple_project.go#L123-L125](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colexec/colexecbase/simple_project.go#L123-L125)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/bazel-out/k8-opt/bin/pkg/sql/colexec/colexecbase/const.eg.go#L367-L369](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/bazel-out/k8-opt/bin/pkg/sql/colexec/colexecbase/const.eg.go#L367-L369)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colexec/colexecutils/operator.go#L156-L158](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colexec/colexecutils/operator.go#L156-L158)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/bazel-out/k8-opt/bin/pkg/sql/colexec/colexecbase/cast.eg.go#L1198-L1200](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/bazel-out/k8-opt/bin/pkg/sql/colexec/colexecbase/cast.eg.go#L1198-L1200)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colexec/colexecutils/operator.go#L156-L158](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colexec/colexecutils/operator.go#L156-L158)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/bazel-out/k8-opt/bin/pkg/sql/colexec/colexecbase/const.eg.go#L610-L612](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/bazel-out/k8-opt/bin/pkg/sql/colexec/colexecbase/const.eg.go#L610-L612)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colexec/colexecutils/operator.go#L156-L158](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colexec/colexecutils/operator.go#L156-L158)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/bazel-out/k8-opt/bin/pkg/sql/colexec/colexecbase/cast.eg.go#L1198-L1200](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/bazel-out/k8-opt/bin/pkg/sql/colexec/colexecbase/cast.eg.go#L1198-L1200)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colexec/colexecutils/operator.go#L156-L158](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colexec/colexecutils/operator.go#L156-L158)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/bazel-out/k8-opt/bin/pkg/sql/colexec/colexecbase/const.eg.go#L610-L612](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/bazel-out/k8-opt/bin/pkg/sql/colexec/colexecbase/const.eg.go#L610-L612)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colexec/colexecutils/operator.go#L156-L158](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colexec/colexecutils/operator.go#L156-L158)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colexec/colexecutils/cancel_checker.go#L58-L60](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colexec/colexecutils/cancel_checker.go#L58-L60)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colfetcher/colbatch_scan.go#L242-L244](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colfetcher/colbatch_scan.go#L242-L244)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colfetcher/cfetcher.go#L692-L694](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colfetcher/cfetcher.go#L692-L694)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/row/kv_fetcher.go#L306-L308](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/row/kv_fetcher.go#L306-L308)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/row/kv_fetcher.go#L285-L287](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/row/kv_fetcher.go#L285-L287)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/row/kv_batch_fetcher.go#L1020-L1022](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/row/kv_batch_fetcher.go#L1020-L1022)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/row/kv_batch_fetcher.go#L871-L873](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/row/kv_batch_fetcher.go#L871-L873)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/row/kv_batch_fetcher.go#L588-L590](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/row/kv_batch_fetcher.go#L588-L590)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/row/kv_batch_fetcher.go#L280-L282](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/row/kv_batch_fetcher.go#L280-L282)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/kv/txn.go#L1281-L1283](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/kv/txn.go#L1281-L1283)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/kv/db.go#L1137-L1139](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/kv/db.go#L1137-L1139)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L490-L492](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L490-L492)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L694-L696](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L694-L696)
</details>

```
pkg/sql/plan_batch.go in pkg/sql.(*rowCountNode).startExec at line 173
pkg/sql/update.go in pkg/sql.(*updateNode).BatchedNext at line 168
pkg/sql/buffer.go in pkg/sql.(*bufferNode).Next at line 48
pkg/sql/row_source_to_plan_node.go in pkg/sql.(*rowSourceToPlanNode).Next at line 79
pkg/sql/colexec/materializer.go in pkg/sql/colexec.(*Materializer).Next at line 282
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 152
pkg/sql/colexec/materializer.go in pkg/sql/colexec.(*Materializer).nextAdapter at line 276
pkg/sql/colexec/materializer.go in pkg/sql/colexec.(*Materializer).next at line 251
pkg/sql/colexec/colexecbase/simple_project.go in pkg/sql/colexec/colexecbase.(*simpleProjectOp).Next at line 124
bazel-out/k8-opt/bin/pkg/sql/colexec/colexecbase/const.eg.go in pkg/sql/colexec/colexecbase.constInt64Op.Next at line 368
pkg/sql/colexec/colexecutils/operator.go in pkg/sql/colexec/colexecutils.(*vectorTypeEnforcer).Next at line 157
bazel-out/k8-opt/bin/pkg/sql/colexec/colexecbase/cast.eg.go in pkg/sql/colexec/colexecbase.(*castOpNullAny).Next at line 1199
pkg/sql/colexec/colexecutils/operator.go in pkg/sql/colexec/colexecutils.(*vectorTypeEnforcer).Next at line 157
bazel-out/k8-opt/bin/pkg/sql/colexec/colexecbase/const.eg.go in pkg/sql/colexec/colexecbase.constNullOp.Next at line 611
pkg/sql/colexec/colexecutils/operator.go in pkg/sql/colexec/colexecutils.(*vectorTypeEnforcer).Next at line 157
bazel-out/k8-opt/bin/pkg/sql/colexec/colexecbase/cast.eg.go in pkg/sql/colexec/colexecbase.(*castOpNullAny).Next at line 1199
pkg/sql/colexec/colexecutils/operator.go in pkg/sql/colexec/colexecutils.(*vectorTypeEnforcer).Next at line 157
bazel-out/k8-opt/bin/pkg/sql/colexec/colexecbase/const.eg.go in pkg/sql/colexec/colexecbase.constNullOp.Next at line 611
pkg/sql/colexec/colexecutils/operator.go in pkg/sql/colexec/colexecutils.(*vectorTypeEnforcer).Next at line 157
pkg/sql/colexec/colexecutils/cancel_checker.go in pkg/sql/colexec/colexecutils.(*CancelChecker).Next at line 59
pkg/sql/colfetcher/colbatch_scan.go in pkg/sql/colfetcher.(*ColBatchScan).Next at line 243
pkg/sql/colfetcher/cfetcher.go in pkg/sql/colfetcher.(*cFetcher).NextBatch at line 693
pkg/sql/row/kv_fetcher.go in pkg/sql/row.(*KVFetcher).NextKV at line 307
pkg/sql/row/kv_fetcher.go in pkg/sql/row.(*KVFetcher).nextKV at line 286
pkg/sql/row/kv_batch_fetcher.go in pkg/sql/row.(*kvBatchFetcherHelper).NextBatch at line 1021
pkg/sql/row/kv_batch_fetcher.go in pkg/sql/row.(*txnKVFetcher).nextBatch at line 872
pkg/sql/row/kv_batch_fetcher.go in pkg/sql/row.(*txnKVFetcher).fetch at line 589
pkg/sql/row/kv_batch_fetcher.go in pkg/sql/row.newTxnKVFetcher.makeTxnKVFetcherDefaultSendFunc.func2 at line 281
pkg/kv/txn.go in pkg/kv.(*Txn).Send at line 1282
pkg/kv/db.go in pkg/kv.(*DB).sendUsingSender at line 1138
pkg/kv/kvclient/kvcoord/txn_coord_sender.go in pkg/kv/kvclient/kvcoord.(*TxnCoordSender).Send at line 491
pkg/kv/kvclient/kvcoord/txn_coord_sender.go in pkg/kv/kvclient/kvcoord.(*TxnCoordSender).maybeRejectIncompatibleRequest at line 695
```

### Tags

| Tag | Value |
| --- | --- |
| Command | mt start-sql |
| Environment | v24.2.2 |
| Go Version | go1.22.5 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v24.2.2 |
| Cockroach SHA | ebd5b645798d923e8e53c249d4850c9505546229 |
| # of CPUs | 32 |
| # of Goroutines | 489 |

Jira issue: CRDB-42415

**Comment by yuzefovich** [comment]
It's unclear why we decided to use the LeafTxn for a plan with mutation. I have thought about this for some time but couldn't come up with an explanation. Unactionable without a repro.
