### ISSUE TITLE
Sentry: catch.go:29: runtime error: invalid memory address or nil pointer dereference
(1) assertion failure
Wraps: (2)
  | (opaque error wrapper)
  | type name: github.com/cockroachdb/errors/withstack...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#131117]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5881038342/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5881038342/?referrer=webhooks_plugin)

Panic Message:

```
catch.go:29: runtime error: invalid memory address or nil pointer dereference
(1) assertion failure
Wraps: (2)
  | (opaque error wrapper)
  | type name: github.com/cockroachdb/errors/withstack/*withstack.withStack
  | reportable 0:
  |
  | github.com/cockroachdb/cockroach/pkg/util/errorutil.ShouldCatch
  | 	github.com/cockroachdb/cockroach/pkg/util/errorutil/catch.go:29
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).Build.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:225
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:770
  | runtime.panicmem
  | 	GOROOT/src/runtime/panic.go:261
  | runtime.sigpanic
  | 	GOROOT/src/runtime/signal_unix.go:881
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).SchemaChange
  | 	github.com/cockroachdb/cockroach/pkg/sql/schema_change_plan_node.go:59
  | github.com/cockroachdb/cockroach/pkg/sql.buildOpaque
  | 	github.com/cockroachdb/cockroach/pkg/sql/opaque.go:57
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).tryBuildOpaque
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/opaque.go:70
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:467
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmtAtRootWithScope
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:299
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmtAtRoot
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:280
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildExplain
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/explain.go:31
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:389
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildCTE
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/with.go:198
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildCTE
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/with.go:251
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildCTEs
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/with.go:143
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).processWiths
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/with.go:113
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildSelect
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:1127
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:356
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmtAtRootWithScope
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:299
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmtAtRoot
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:280
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).Build
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:259
  | github.com/cockroachdb/cockroach/pkg/sql.(*optPlanningCtx).buildExecMemo
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:862
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).makeOptimizerPlan
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:251
  | github.com/cockroachdb/cockroach/pkg/sql.(*SchemaChanger).backfillQueryIntoTable.func2.2
  | 	github.com/cockroachdb/cockroach/pkg/sql/schema_changer.go:381
  | github.com/cockroachdb/cockroach/pkg/sql.(*schemaResolver).runWithOptions
  | 	github.com/cockroachdb/cockroach/pkg/sql/schema_resolver.go:444
  | github.com/cockroachdb/cockroach/pkg/sql.(*SchemaChanger).backfillQueryIntoTable.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/schema_changer.go:380
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).Txn.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1940
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).txn.func4
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:2027
  | github.com/cockroachdb/cockroach/pkg/kv.(*Txn).exec
  | 	github.com/cockroachdb/cockroach/pkg/kv/txn.go:1049
  | github.com/cockroachdb/cockroach/pkg/kv.runTxn
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:1103
  | github.com/cockroachdb/cockroach/pkg/kv.(*DB).TxnWithAdmissionControl
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:1066
Wraps: (3) runtime error: invalid memory address or nil pointer dereference
  | -- cause hidden behind barrier
  | ×
  | (1) ×
  |   |
  |   | (opaque error leaf)
  |   | type name: runtime/runtime.errorString
  | Error types: (1) *errbase.opaqueLeaf
Error types: (1) *assert.withAssertionFailure (2) *errbase.opaqueWrapper (3) *barriers.barrierErr
-- report composition:
*barriers.barrierErr: masked error: ×
catch.go:29: *withstack.withStack (top exception)
*assert.withAssertionFailure
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/kv/db.go#L1065-L1067](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/kv/db.go#L1065-L1067)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/kv/db.go#L1102-L1104](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/kv/db.go#L1102-L1104)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/kv/txn.go#L1048-L1050](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/kv/txn.go#L1048-L1050)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/internal.go#L2026-L2028](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/internal.go#L2026-L2028)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/internal.go#L1939-L1941](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/internal.go#L1939-L1941)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/schema_changer.go#L379-L381](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/schema_changer.go#L379-L381)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/schema_resolver.go#L443-L445](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/schema_resolver.go#L443-L445)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/schema_changer.go#L380-L382](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/schema_changer.go#L380-L382)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/plan_opt.go#L250-L252](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/plan_opt.go#L250-L252)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/plan_opt.go#L861-L863](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/plan_opt.go#L861-L863)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/optbuilder/builder.go#L258-L260](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/optbuilder/builder.go#L258-L260)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/optbuilder/builder.go#L279-L281](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/optbuilder/builder.go#L279-L281)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/optbuilder/builder.go#L298-L300](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/optbuilder/builder.go#L298-L300)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/optbuilder/builder.go#L355-L357](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/optbuilder/builder.go#L355-L357)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/optbuilder/select.go#L1126-L1128](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/optbuilder/select.go#L1126-L1128)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/optbuilder/with.go#L112-L114](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/optbuilder/with.go#L112-L114)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/optbuilder/with.go#L142-L144](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/optbuilder/with.go#L142-L144)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/optbuilder/with.go#L250-L252](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/optbuilder/with.go#L250-L252)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/optbuilder/with.go#L197-L199](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/optbuilder/with.go#L197-L199)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/optbuilder/builder.go#L388-L390](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/optbuilder/builder.go#L388-L390)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/optbuilder/explain.go#L30-L32](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/optbuilder/explain.go#L30-L32)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/optbuilder/builder.go#L279-L281](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/optbuilder/builder.go#L279-L281)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/optbuilder/builder.go#L298-L300](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/optbuilder/builder.go#L298-L300)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/optbuilder/builder.go#L466-L468](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/optbuilder/builder.go#L466-L468)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/optbuilder/opaque.go#L69-L71](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/optbuilder/opaque.go#L69-L71)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opaque.go#L56-L58](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opaque.go#L56-L58)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/schema_change_plan_node.go#L58-L60](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/schema_change_plan_node.go#L58-L60)
[GOROOT/src/runtime/signal_unix.go#L880-L882](GOROOT/src/runtime/signal_unix.go#L880-L882)
[GOROOT/src/runtime/panic.go#L260-L262](GOROOT/src/runtime/panic.go#L260-L262)
[GOROOT/src/runtime/panic.go#L769-L771](GOROOT/src/runtime/panic.go#L769-L771)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/optbuilder/builder.go#L224-L226](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/optbuilder/builder.go#L224-L226)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/util/errorutil/catch.go#L28-L30](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/util/errorutil/catch.go#L28-L30)
</details>

```
pkg/kv/db.go in pkg/kv.(*DB).TxnWithAdmissionControl at line 1066
pkg/kv/db.go in pkg/kv.runTxn at line 1103
pkg/kv/txn.go in pkg/kv.(*Txn).exec at line 1049
pkg/sql/internal.go in pkg/sql.(*InternalDB).txn.func4 at line 2027
pkg/sql/internal.go in pkg/sql.(*InternalDB).Txn.func1 at line 1940
pkg/sql/schema_changer.go in pkg/sql.(*SchemaChanger).backfillQueryIntoTable.func2 at line 380
pkg/sql/schema_resolver.go in pkg/sql.(*schemaResolver).runWithOptions at line 444
pkg/sql/schema_changer.go in pkg/sql.(*SchemaChanger).backfillQueryIntoTable.func2.2 at line 381
pkg/sql/plan_opt.go in pkg/sql.(*planner).makeOptimizerPlan at line 251
pkg/sql/plan_opt.go in pkg/sql.(*optPlanningCtx).buildExecMemo at line 862
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).Build at line 259
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).buildStmtAtRoot at line 280
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).buildStmtAtRootWithScope at line 299
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).buildStmt at line 356
pkg/sql/opt/optbuilder/select.go in pkg/sql/opt/optbuilder.(*Builder).buildSelect at line 1127
pkg/sql/opt/optbuilder/with.go in pkg/sql/opt/optbuilder.(*Builder).processWiths at line 113
pkg/sql/opt/optbuilder/with.go in pkg/sql/opt/optbuilder.(*Builder).buildCTEs at line 143
pkg/sql/opt/optbuilder/with.go in pkg/sql/opt/optbuilder.(*Builder).buildCTE at line 251
pkg/sql/opt/optbuilder/with.go in pkg/sql/opt/optbuilder.(*Builder).buildCTE at line 198
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).buildStmt at line 389
pkg/sql/opt/optbuilder/explain.go in pkg/sql/opt/optbuilder.(*Builder).buildExplain at line 31
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).buildStmtAtRoot at line 280
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).buildStmtAtRootWithScope at line 299
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).buildStmt at line 467
pkg/sql/opt/optbuilder/opaque.go in pkg/sql/opt/optbuilder.(*Builder).tryBuildOpaque at line 70
pkg/sql/opaque.go in pkg/sql.buildOpaque at line 57
pkg/sql/schema_change_plan_node.go in pkg/sql.(*planner).SchemaChange at line 59
GOROOT/src/runtime/signal_unix.go in runtime.sigpanic at line 881
GOROOT/src/runtime/panic.go in runtime.panicmem at line 261
GOROOT/src/runtime/panic.go in runtime.gopanic at line 770
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).Build.func1 at line 225
pkg/util/errorutil/catch.go in pkg/util/errorutil.ShouldCatch at line 29
```

### Tags

| Tag | Value |
| --- | --- |
| Command | demo |
| Environment | v24.2.0 |
| Go Version | go1.22.5 X:nocoverageredesign |
| Platform | linux arm64 |
| Distribution | CCL |
| Cockroach Release | v24.2.0 |
| Cockroach SHA | 953d09cce5a01cc0053e138516d80a27454f027c |
| # of CPUs | 10 |
| # of Goroutines | 478 |

Jira issue: CRDB-42383

**Comment by yuzefovich** [comment]
dup of #131121
