### ISSUE TITLE
sql: v24.2.2: identity column × of relation × has 0 sequences instead of 1

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#131280]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5898561626/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5898561626/?referrer=webhooks_plugin)

Panic Message:

```
alter_table.go:1267: identity column × of relation × has 0 sequences instead of 1
(1)
Wraps: (2) assertion failure
Wraps: (3) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.applyColumnMutation
  | 	github.com/cockroachdb/cockroach/pkg/sql/alter_table.go:1267
  | github.com/cockroachdb/cockroach/pkg/sql.(*alterTableNode).startExec
  | 	github.com/cockroachdb/cockroach/pkg/sql/alter_table.go:646
  | github.com/cockroachdb/cockroach/pkg/sql.startExec.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan.go:524
  | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:112
  | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:299
  | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:79
  | github.com/cockroachdb/cockroach/pkg/sql.walkPlan
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:43
  | github.com/cockroachdb/cockroach/pkg/sql.startExec
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan.go:527
  | github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Start
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:171
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Columnarizer).Init
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/columnarizer.go:183
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).init
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:94
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:152
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).Init
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:103
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Materializer).Start.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:233
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:152
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Materializer).Start
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:232
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*FlowCoordinator).Start.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:116
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:152
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*FlowCoordinator).Start
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:115
  | github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBaseNoHelper).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:731
  | github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:579
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:305
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:932
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1994
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll.func3
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1708
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1711
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2420
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1967
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1174
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:146
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:3429
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:145
Wraps: (4) identity column × of relation × has 0 sequences instead of 1
Error types: (1) *colexecerror.notInternalError (2) *assert.withAssertionFailure (3) *withstack.withStack (4) *errutil.leafError
-- report composition:
*errutil.leafError: identity column × of relation × has 0 sequences instead of 1
alter_table.go:1267: *withstack.withStack (top exception)
*assert.withAssertionFailure
*colexecerror.notInternalError
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/conn_executor_exec.go#L144-L146](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/conn_executor_exec.go#L144-L146)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/conn_executor_exec.go#L3428-L3430](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/conn_executor_exec.go#L3428-L3430)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/conn_executor_exec.go#L145-L147](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/conn_executor_exec.go#L145-L147)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/conn_executor_exec.go#L1173-L1175](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/conn_executor_exec.go#L1173-L1175)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/conn_executor_exec.go#L1966-L1968](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/conn_executor_exec.go#L1966-L1968)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/conn_executor_exec.go#L2419-L2421](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/conn_executor_exec.go#L2419-L2421)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/distsql_running.go#L1710-L1712](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/distsql_running.go#L1710-L1712)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/distsql_running.go#L1707-L1709](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/distsql_running.go#L1707-L1709)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/distsql_running.go#L1993-L1995](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/distsql_running.go#L1993-L1995)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/distsql_running.go#L931-L933](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/distsql_running.go#L931-L933)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colflow/vectorized_flow.go#L304-L306](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colflow/vectorized_flow.go#L304-L306)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/flowinfra/flow.go#L578-L580](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/flowinfra/flow.go#L578-L580)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/execinfra/processorsbase.go#L730-L732](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/execinfra/processorsbase.go#L730-L732)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colflow/flow_coordinator.go#L114-L116](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colflow/flow_coordinator.go#L114-L116)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colexecerror/error.go#L151-L153](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colexecerror/error.go#L151-L153)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colflow/flow_coordinator.go#L115-L117](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colflow/flow_coordinator.go#L115-L117)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colexec/materializer.go#L231-L233](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colexec/materializer.go#L231-L233)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colexecerror/error.go#L151-L153](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colexecerror/error.go#L151-L153)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colexec/materializer.go#L232-L234](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colexec/materializer.go#L232-L234)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colflow/stats.go#L102-L104](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colflow/stats.go#L102-L104)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colexecerror/error.go#L151-L153](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colexecerror/error.go#L151-L153)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colflow/stats.go#L93-L95](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colflow/stats.go#L93-L95)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colexec/columnarizer.go#L182-L184](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colexec/columnarizer.go#L182-L184)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/plan_node_to_row_source.go#L170-L172](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/plan_node_to_row_source.go#L170-L172)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/plan.go#L526-L528](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/plan.go#L526-L528)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/walk.go#L42-L44](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/walk.go#L42-L44)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/walk.go#L78-L80](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/walk.go#L78-L80)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/walk.go#L298-L300](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/walk.go#L298-L300)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/walk.go#L111-L113](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/walk.go#L111-L113)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/plan.go#L523-L525](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/plan.go#L523-L525)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/alter_table.go#L645-L647](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/alter_table.go#L645-L647)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/alter_table.go#L1266-L1268](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/alter_table.go#L1266-L1268)
</details>

```
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 145
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithProfiling at line 3429
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt.func1 at line 146
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 1174
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchToExecutionEngine at line 1967
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithDistSQLEngine at line 2420
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRunAll at line 1711
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRunAll.func3 at line 1708
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRun at line 1994
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).Run at line 932
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlow).Run at line 305
pkg/sql/flowinfra/flow.go in pkg/sql/flowinfra.(*FlowBase).Run at line 579
pkg/sql/execinfra/processorsbase.go in pkg/sql/execinfra.(*ProcessorBaseNoHelper).Run at line 731
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*FlowCoordinator).Start at line 115
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 152
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*FlowCoordinator).Start.func1 at line 116
pkg/sql/colexec/materializer.go in pkg/sql/colexec.(*Materializer).Start at line 232
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 152
pkg/sql/colexec/materializer.go in pkg/sql/colexec.(*Materializer).Start.func1 at line 233
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).Init at line 103
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 152
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).init at line 94
pkg/sql/colexec/columnarizer.go in pkg/sql/colexec.(*Columnarizer).Init at line 183
pkg/sql/plan_node_to_row_source.go in pkg/sql.(*planNodeToRowSource).Start at line 171
pkg/sql/plan.go in pkg/sql.startExec at line 527
pkg/sql/walk.go in pkg/sql.walkPlan at line 43
pkg/sql/walk.go in pkg/sql.(*planVisitor).visit at line 79
pkg/sql/walk.go in pkg/sql.(*planVisitor).visitInternal at line 299
pkg/sql/walk.go in pkg/sql.(*planVisitor).visitInternal.func1 at line 112
pkg/sql/plan.go in pkg/sql.startExec.func2 at line 524
pkg/sql/alter_table.go in pkg/sql.(*alterTableNode).startExec at line 646
pkg/sql/alter_table.go in pkg/sql.applyColumnMutation at line 1267
```

### Tags

| Tag | Value |
| --- | --- |
| Command | mt start-sql |
| Environment | v24.2.2 |
| Go Version | go1.22.5 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v24.2.2 |
| Cockroach SHA | ebd5b645798d923e8e53c249d4850c9505546229 |
| # of CPUs | 16 |
| # of Goroutines | 420 |

Jira issue: CRDB-42471

**Comment by fqazi** [comment]
We can add validation to detect if invalid_objects with this condition exist, the original root cause of this issue is unknown at this point
