### ISSUE TITLE
Sentry: alter_table.go:1267: identity column × of relation × has 0 sequences instead of 1
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#131281]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5898563244/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5898563244/?referrer=webhooks_plugin)

Panic Message:

```
alter_table.go:1267: identity column × of relation × has 0 sequences instead of 1
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.applyColumnMutation
  | 	github.com/cockroachdb/cockroach/pkg/sql/alter_table.go:1267
  | github.com/cockroachdb/cockroach/pkg/sql.(*alterTableNode).startExec
  | 	github.com/cockroachdb/cockroach/pkg/sql/alter_table.go:646
  | github.com/cockroachdb/cockroach/pkg/sql.startExec.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan.go:524
  | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:112
  | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:299
  | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:79
  | github.com/cockroachdb/cockroach/pkg/sql.walkPlan
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:43
  | github.com/cockroachdb/cockroach/pkg/sql.startExec
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan.go:527
  | github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Start
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:171
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*FlowCoordinator).Start.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:116
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:152
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*FlowCoordinator).Start
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:115
  | github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBaseNoHelper).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:731
  | github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:579
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:305
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:932
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1994
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll.func3
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1708
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1711
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2420
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1967
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1174
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:146
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:3429
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:145
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execPortal
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:251
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2421
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2423
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2238
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:963
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommands
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:253
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).serveImpl.func4
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:1052
Wraps: (3) identity column × of relation × has 0 sequences instead of 1
Error types: (1) *assert.withAssertionFailure (2) *withstack.withStack (3) *errutil.leafError
-- report composition:
*errutil.leafError: identity column × of relation × has 0 sequences instead of 1
alter_table.go:1267: *withstack.withStack (top exception)
*assert.withAssertionFailure
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/pgwire/server.go#L1051-L1053](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/pgwire/server.go#L1051-L1053)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/pgwire/conn.go#L252-L254](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/pgwire/conn.go#L252-L254)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/conn_executor.go#L962-L964](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/conn_executor.go#L962-L964)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/conn_executor.go#L2237-L2239](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/conn_executor.go#L2237-L2239)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/conn_executor.go#L2422-L2424](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/conn_executor.go#L2422-L2424)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/conn_executor.go#L2420-L2422](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/conn_executor.go#L2420-L2422)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/conn_executor_exec.go#L250-L252](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/conn_executor_exec.go#L250-L252)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/conn_executor_exec.go#L144-L146](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/conn_executor_exec.go#L144-L146)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/conn_executor_exec.go#L3428-L3430](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/conn_executor_exec.go#L3428-L3430)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/conn_executor_exec.go#L145-L147](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/conn_executor_exec.go#L145-L147)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/conn_executor_exec.go#L1173-L1175](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/conn_executor_exec.go#L1173-L1175)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/conn_executor_exec.go#L1966-L1968](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/conn_executor_exec.go#L1966-L1968)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/conn_executor_exec.go#L2419-L2421](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/conn_executor_exec.go#L2419-L2421)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/distsql_running.go#L1710-L1712](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/distsql_running.go#L1710-L1712)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/distsql_running.go#L1707-L1709](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/distsql_running.go#L1707-L1709)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/distsql_running.go#L1993-L1995](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/distsql_running.go#L1993-L1995)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/distsql_running.go#L931-L933](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/distsql_running.go#L931-L933)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colflow/vectorized_flow.go#L304-L306](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colflow/vectorized_flow.go#L304-L306)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/flowinfra/flow.go#L578-L580](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/flowinfra/flow.go#L578-L580)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/execinfra/processorsbase.go#L730-L732](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/execinfra/processorsbase.go#L730-L732)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colflow/flow_coordinator.go#L114-L116](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colflow/flow_coordinator.go#L114-L116)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colexecerror/error.go#L151-L153](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colexecerror/error.go#L151-L153)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colflow/flow_coordinator.go#L115-L117](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/colflow/flow_coordinator.go#L115-L117)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/plan_node_to_row_source.go#L170-L172](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/plan_node_to_row_source.go#L170-L172)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/plan.go#L526-L528](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/plan.go#L526-L528)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/walk.go#L42-L44](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/walk.go#L42-L44)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/walk.go#L78-L80](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/walk.go#L78-L80)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/walk.go#L298-L300](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/walk.go#L298-L300)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/walk.go#L111-L113](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/walk.go#L111-L113)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/plan.go#L523-L525](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/plan.go#L523-L525)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/alter_table.go#L645-L647](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/alter_table.go#L645-L647)
[https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/alter_table.go#L1266-L1268](https://github.com/cockroachdb/cockroach/blob/ebd5b645798d923e8e53c249d4850c9505546229/pkg/sql/alter_table.go#L1266-L1268)
</details>

```
pkg/sql/pgwire/server.go in pkg/sql/pgwire.(*Server).serveImpl.func4 at line 1052
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommands at line 253
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 963
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 2238
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 2423
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd.func2 at line 2421
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execPortal at line 251
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 145
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithProfiling at line 3429
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt.func1 at line 146
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 1174
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchToExecutionEngine at line 1967
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithDistSQLEngine at line 2420
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRunAll at line 1711
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRunAll.func3 at line 1708
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRun at line 1994
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).Run at line 932
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlow).Run at line 305
pkg/sql/flowinfra/flow.go in pkg/sql/flowinfra.(*FlowBase).Run at line 579
pkg/sql/execinfra/processorsbase.go in pkg/sql/execinfra.(*ProcessorBaseNoHelper).Run at line 731
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*FlowCoordinator).Start at line 115
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 152
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*FlowCoordinator).Start.func1 at line 116
pkg/sql/plan_node_to_row_source.go in pkg/sql.(*planNodeToRowSource).Start at line 171
pkg/sql/plan.go in pkg/sql.startExec at line 527
pkg/sql/walk.go in pkg/sql.walkPlan at line 43
pkg/sql/walk.go in pkg/sql.(*planVisitor).visit at line 79
pkg/sql/walk.go in pkg/sql.(*planVisitor).visitInternal at line 299
pkg/sql/walk.go in pkg/sql.(*planVisitor).visitInternal.func1 at line 112
pkg/sql/plan.go in pkg/sql.startExec.func2 at line 524
pkg/sql/alter_table.go in pkg/sql.(*alterTableNode).startExec at line 646
pkg/sql/alter_table.go in pkg/sql.applyColumnMutation at line 1267
```

### Tags

| Tag | Value |
| --- | --- |
| Command | mt start-sql |
| Environment | v24.2.2 |
| Go Version | go1.22.5 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v24.2.2 |
| Cockroach SHA | ebd5b645798d923e8e53c249d4850c9505546229 |
| # of CPUs | 16 |
| # of Goroutines | 420 |

Jira issue: CRDB-42472

**Comment by yuzefovich** [comment]
dup of #131280
