### ISSUE TITLE
rowexec: v23.2.8: sample-aggregator-mem: no bytes in account to release

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#131273]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5897448697/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5897448697/?referrer=webhooks_plugin)

Panic Message:

```
crash_reporting.go:415: sample-aggregator-mem: no bytes in account to release, current 2119161, free 3170455
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/util/log/logcrash.ReportOrPanic
  | 	github.com/cockroachdb/cockroach/pkg/util/log/logcrash/crash_reporting.go:415
  | github.com/cockroachdb/cockroach/pkg/util/mon.(*BoundAccount).Shrink
  | 	github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:991
  | github.com/cockroachdb/cockroach/pkg/util/mon.(*BoundAccount).Resize
  | 	github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:951
  | github.com/cockroachdb/cockroach/pkg/sql/stats.(*SampleReservoir).copyRow
  | 	github.com/cockroachdb/cockroach/pkg/sql/stats/pkg/sql/stats/row_sampling.go:273
  | github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*sampleAggregator).sampleRow.(*SampleReservoir).SampleRow.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/stats/pkg/sql/stats/row_sampling.go:195
  | github.com/cockroachdb/cockroach/pkg/sql/stats.(*SampleReservoir).retryMaybeResize
  | 	github.com/cockroachdb/cockroach/pkg/sql/stats/pkg/sql/stats/row_sampling.go:154
  | github.com/cockroachdb/cockroach/pkg/sql/stats.(*SampleReservoir).SampleRow
  | 	github.com/cockroachdb/cockroach/pkg/sql/stats/pkg/sql/stats/row_sampling.go:171
  | github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*sampleAggregator).sampleRow
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowexec/sample_aggregator.go:416
  | github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*sampleAggregator).mainLoop
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowexec/sample_aggregator.go:330
  | github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*sampleAggregator).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowexec/sample_aggregator.go:205
  | github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:579
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:919
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).planAndRunCreateStats
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_plan_stats.go:665
  | github.com/cockroachdb/cockroach/pkg/sql.(*createStatsResumer).Resume.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/create_stats.go:704
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).Txn.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1782
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).txn.func4
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1861
  | github.com/cockroachdb/cockroach/pkg/kv.(*Txn).exec
  | 	github.com/cockroachdb/cockroach/pkg/kv/txn.go:1032
  | github.com/cockroachdb/cockroach/pkg/kv.runTxn
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:1079
  | github.com/cockroachdb/cockroach/pkg/kv.(*DB).TxnWithAdmissionControl
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:1042
  | github.com/cockroachdb/cockroach/pkg/kv.(*DB).Txn
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:1017
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).txn
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1848
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).Txn
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1783
  | github.com/cockroachdb/cockroach/pkg/sql.(*createStatsResumer).Resume
  | 	github.com/cockroachdb/cockroach/pkg/sql/create_stats.go:674
  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine.func2
  | 	github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1722
  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine
  | 	github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1723
  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).runJob
  | 	github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:477
  | github.com/cockroachdb/cockroach/pkg/jobs.(*StartableJob).Start.func2
  | 	github.com/cockroachdb/cockroach/pkg/jobs/jobs.go:971
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:484
  | runtime.goexit
  | 	src/runtime/asm_arm64.s:1197
Wraps: (2) sample-aggregator-mem: no bytes in account to release, current 2119161, free 3170455
Error types: (1) *withstack.withStack (2) *errutil.leafError
-- report composition:
*errutil.leafError: sample-aggregator-mem: no bytes in account to release, current 2119161, free 3170455
crash_reporting.go:415: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_arm64.s#L1196-L1198](src/runtime/asm_arm64.s#L1196-L1198)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/util/stop/stopper.go#L483-L485](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/util/stop/stopper.go#L483-L485)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/jobs/jobs.go#L970-L972](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/jobs/jobs.go#L970-L972)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/jobs/adopt.go#L476-L478](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/jobs/adopt.go#L476-L478)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/jobs/registry.go#L1722-L1724](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/jobs/registry.go#L1722-L1724)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/jobs/registry.go#L1721-L1723](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/jobs/registry.go#L1721-L1723)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/create_stats.go#L673-L675](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/create_stats.go#L673-L675)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/internal.go#L1782-L1784](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/internal.go#L1782-L1784)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/internal.go#L1847-L1849](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/internal.go#L1847-L1849)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/kv/db.go#L1016-L1018](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/kv/db.go#L1016-L1018)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/kv/db.go#L1041-L1043](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/kv/db.go#L1041-L1043)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/kv/db.go#L1078-L1080](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/kv/db.go#L1078-L1080)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/kv/txn.go#L1031-L1033](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/kv/txn.go#L1031-L1033)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/internal.go#L1860-L1862](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/internal.go#L1860-L1862)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/internal.go#L1781-L1783](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/internal.go#L1781-L1783)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/create_stats.go#L703-L705](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/create_stats.go#L703-L705)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/distsql_plan_stats.go#L664-L666](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/distsql_plan_stats.go#L664-L666)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/distsql_running.go#L918-L920](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/distsql_running.go#L918-L920)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/flowinfra/flow.go#L578-L580](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/flowinfra/flow.go#L578-L580)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/rowexec/sample_aggregator.go#L204-L206](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/rowexec/sample_aggregator.go#L204-L206)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/rowexec/sample_aggregator.go#L329-L331](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/rowexec/sample_aggregator.go#L329-L331)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/rowexec/sample_aggregator.go#L415-L417](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/rowexec/sample_aggregator.go#L415-L417)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/stats/pkg/sql/stats/row_sampling.go#L170-L172](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/stats/pkg/sql/stats/row_sampling.go#L170-L172)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/stats/pkg/sql/stats/row_sampling.go#L153-L155](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/stats/pkg/sql/stats/row_sampling.go#L153-L155)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/stats/pkg/sql/stats/row_sampling.go#L194-L196](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/stats/pkg/sql/stats/row_sampling.go#L194-L196)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/stats/pkg/sql/stats/row_sampling.go#L272-L274](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/sql/stats/pkg/sql/stats/row_sampling.go#L272-L274)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/util/mon/bytes_usage.go#L950-L952](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/util/mon/bytes_usage.go#L950-L952)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/util/mon/bytes_usage.go#L990-L992](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/util/mon/bytes_usage.go#L990-L992)
[https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/util/log/logcrash/crash_reporting.go#L414-L416](https://github.com/cockroachdb/cockroach/blob/e003de1d4ce4f9817d62e53b5af9961bdd4f2571/pkg/util/log/logcrash/crash_reporting.go#L414-L416)
</details>

```
src/runtime/asm_arm64.s in runtime.goexit at line 1197
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 484
pkg/jobs/jobs.go in pkg/jobs.(*StartableJob).Start.func2 at line 971
pkg/jobs/adopt.go in pkg/jobs.(*Registry).runJob at line 477
pkg/jobs/registry.go in pkg/jobs.(*Registry).stepThroughStateMachine at line 1723
pkg/jobs/registry.go in pkg/jobs.(*Registry).stepThroughStateMachine.func2 at line 1722
pkg/sql/create_stats.go in pkg/sql.(*createStatsResumer).Resume at line 674
pkg/sql/internal.go in pkg/sql.(*InternalDB).Txn at line 1783
pkg/sql/internal.go in pkg/sql.(*InternalDB).txn at line 1848
pkg/kv/db.go in pkg/kv.(*DB).Txn at line 1017
pkg/kv/db.go in pkg/kv.(*DB).TxnWithAdmissionControl at line 1042
pkg/kv/db.go in pkg/kv.runTxn at line 1079
pkg/kv/txn.go in pkg/kv.(*Txn).exec at line 1032
pkg/sql/internal.go in pkg/sql.(*InternalDB).txn.func4 at line 1861
pkg/sql/internal.go in pkg/sql.(*InternalDB).Txn.func1 at line 1782
pkg/sql/create_stats.go in pkg/sql.(*createStatsResumer).Resume.func1 at line 704
pkg/sql/distsql_plan_stats.go in pkg/sql.(*DistSQLPlanner).planAndRunCreateStats at line 665
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).Run at line 919
pkg/sql/flowinfra/flow.go in pkg/sql/flowinfra.(*FlowBase).Run at line 579
pkg/sql/rowexec/sample_aggregator.go in pkg/sql/rowexec.(*sampleAggregator).Run at line 205
pkg/sql/rowexec/sample_aggregator.go in pkg/sql/rowexec.(*sampleAggregator).mainLoop at line 330
pkg/sql/rowexec/sample_aggregator.go in pkg/sql/rowexec.(*sampleAggregator).sampleRow at line 416
pkg/sql/stats/pkg/sql/stats/row_sampling.go in pkg/sql/stats.(*SampleReservoir).SampleRow at line 171
pkg/sql/stats/pkg/sql/stats/row_sampling.go in pkg/sql/stats.(*SampleReservoir).retryMaybeResize at line 154
pkg/sql/stats/pkg/sql/stats/row_sampling.go in pkg/sql/rowexec.(*sampleAggregator).sampleRow.(*SampleReservoir).SampleRow.func1 at line 195
pkg/sql/stats/pkg/sql/stats/row_sampling.go in pkg/sql/stats.(*SampleReservoir).copyRow at line 273
pkg/util/mon/bytes_usage.go in pkg/util/mon.(*BoundAccount).Resize at line 951
pkg/util/mon/bytes_usage.go in pkg/util/mon.(*BoundAccount).Shrink at line 991
pkg/util/log/logcrash/crash_reporting.go in pkg/util/log/logcrash.ReportOrPanic at line 415
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v23.2.8 |
| Go Version | go1.21.10 X:nocoverageredesign |
| Platform | linux arm64 |
| Distribution | CCL |
| Cockroach Release | v23.2.8 |
| Cockroach SHA | e003de1d4ce4f9817d62e53b5af9961bdd4f2571 |
| # of CPUs | 32 |
| # of Goroutines | 10542 |

Jira issue: CRDB-42465

**Comment by yuzefovich** [comment]
dup of #128241
