### ISSUE TITLE
Incorrect json value string escaping in `cockroach sql --format sql`

### ISSUE THREAD

**Issue by marcrasi** [cockroachdb/cockroach#131257]
**Describe the problem**

Somewhere between v23.1.2 and v24.1.2, the string escaping from `cockroach sql --format sql` changed in such a way that JSON values are incorrectly escaped.

**To Reproduce**

On v24.1.2, I first set up an example table:
```
root@127.0.0.1:26257/alda> create table test_escaping (value json);
root@127.0.0.1:26257/alda> insert into test_escaping values ('"there are \"quotes\" in this json string"');
root@127.0.0.1:26257/alda> select * from test_escaping;
                    value
----------------------------------------------
  "there are \"quotes\" in this json string"
```

Next I select from the table in `--format=sql`:
```
cockroach-local sql -d alda -e 'select * from test_escaping;' --format=sql

CREATE TABLE results (
  value STRING
);
INSERT INTO results VALUES (e'"there are \"quotes\" in this json string"');
```

The string literal is not correct. There should be two backslashes in front of the quotes because the e-string unescapes once, and then the quotes in the json value still need to be escaped.

The problem means you can't run the INSERT statement back into the `test_escaping` table:
```
root@127.0.0.1:26257/alda> INSERT INTO test_escaping VALUES (e'"there are \"quotes\" in this json string"');
ERROR: could not parse JSON: unable to decode JSON: while decoding 40 bytes at offset 13:
...|"there are "quotes" in this j|...
...|.............^...............|...: trailing characters after JSON document
SQLSTATE: 22P02
```

**Expected behavior**

If I do the same thing on v23.1.2, I get a different output, with correct escaping:
```
cockroach-local sql -d alda -e 'select * from test_escaping;' --format=sql

CREATE TABLE results (
  value STRING
);
INSERT INTO results VALUES (e'"there are \\"quotes\\" in this json string"');
```

**Environment:**
 - CockroachDB version v24.1.2
 - Server: Single node server on my MacOS laptop.
 - Client app: `cockroach sql`.

Jira issue: CRDB-42461

Epic CRDB-40419

**Comment by wenyihu6** [comment]
I can't clearly tell if this is for queries or foundations. Given SQLSTATE: 22P02 from sql/pgwire, I’m routing this to the SQL Foundations team as well. But feel free to redirect if necessary or loop me back in for further investigation.

**Comment by rafiss** [comment]
I ran a git bisect and found that https://github.com/cockroachdb/cockroach/pull/114707 introduced this problem. That PR  was created to resolve another issue: https://github.com/cockroachdb/cockroach/issues/107518

cc @rharding6373 just a heads up since you filed that issue originally, I will be looking into whether we need to have different escaping behavior here.
