### ISSUE TITLE
cdc: improve schemafeed bottleneck when schema_locked=false

### ISSUE THREAD

**Issue by rharding6373** [cockroachdb/cockroach#131327]
We could make improvements to schemafeed's `pauseOrResumePolling` loop by avoiding the use of errors for checking.

Context: https://cockroachlabs.slack.com/archives/C065X5307U3/p1724335407360119?thread_ts=1724271598.403169&cid=C065X5307U3

Jira issue: CRDB-42497

Epic CRDB-41784

**Comment by wenyihu6** [comment]
Adding the relevant CPU profile in question for more context: 

<img width="1044" alt="Image" src="https://github.com/user-attachments/assets/f227b425-9bcf-45df-8e72-8caad779dd65" />

**Comment by wenyihu6** [comment]
Linking the relevant cpu profile for more context: 

<img width="1216" alt="Image" src="https://github.com/user-attachments/assets/5c5518da-103d-47ab-8bfa-03bf5df4c9ef" />
