### ISSUE TITLE
Sentry: datum.go:5346: comparison of two different versions of enum %!s(func() string=0x13d16d0) oid ×: versions 2 and 11
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | g...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#131322]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5901535887/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5901535887/?referrer=webhooks_plugin)

Panic Message:

```
datum.go:5346: comparison of two different versions of enum %!s(func() string=0x13d16d0) oid ×: versions 2 and 11
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*DEnum).Compare
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/datum.go:5346
  | github.com/cockroachdb/cockroach/pkg/sql/opt/constraint.(*KeyContext).Compare
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/constraint/key.go:325
  | github.com/cockroachdb/cockroach/pkg/sql/opt/constraint.Key.Compare
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/constraint/key.go:116
  | github.com/cockroachdb/cockroach/pkg/sql/opt/constraint.(*Span).StartsAfter
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/constraint/span.go:222
  | github.com/cockroachdb/cockroach/pkg/sql/opt/constraint.(*Constraint).IntersectWith
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/constraint/constraint.go:202
  | github.com/cockroachdb/cockroach/pkg/sql/opt/idxconstraint.(*indexConstraintCtx).makeSpansForAnd
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/idxconstraint/index_constraints.go:805
  | github.com/cockroachdb/cockroach/pkg/sql/opt/idxconstraint.(*indexConstraintCtx).makeSpansForExpr
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/idxconstraint/index_constraints.go:680
  | github.com/cockroachdb/cockroach/pkg/sql/opt/idxconstraint.(*Instance).Init
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/idxconstraint/index_constraints.go:1136
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*CustomFuncs).initIdxConstraintForIndex
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/general_funcs.go:202
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*CustomFuncs).tryConstrainIndex
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/select_funcs.go:1055
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*CustomFuncs).MakeCombinedFiltersConstraint
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/select_funcs.go:298
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*CustomFuncs).GenerateConstrainedScans.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/select_funcs.go:450
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*scanIndexIter).ForEachStartingAfter
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/scan_index_iter.go:304
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*scanIndexIter).ForEach
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/scan_index_iter.go:207
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*CustomFuncs).GenerateConstrainedScans
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/select_funcs.go:442
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*explorer).exploreSelect
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/xform/explorer.og.go:361
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*explorer).exploreGroupMember
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/xform/explorer.og.go:26
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*explorer).exploreGroup
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/explorer.go:185
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).optimizeGroup
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:537
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).optimizeExpr
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:300
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).optimizeGroupMember
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:579
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).optimizeGroup
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:524
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).Optimize
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:270
  | github.com/cockroachdb/cockroach/pkg/sql.(*optPlanningCtx).reuseMemo
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:557
  | github.com/cockroachdb/cockroach/pkg/sql.(*optPlanningCtx).fetchPreparedMemoLegacy
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:785
  | github.com/cockroachdb/cockroach/pkg/sql.(*optPlanningCtx).buildExecMemo
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:809
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).makeOptimizerPlan
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:251
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).makeExecPlan
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2291
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1841
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1174
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:146
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:3429
Wraps: (3) comparison of two different versions of enum %!s(func() string=0x13d16d0) oid ×: versions 2 and 11
Error types: (1) *assert.withAssertionFailure (2) *withstack.withStack (3) *errutil.leafError
-- report composition:
*errutil.leafError: comparison of two different versions of enum %!s(func() string=0x13d16d0) oid ×: versions 2 and 11
datum.go:5346: *withstack.withStack (top exception)
*assert.withAssertionFailure
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/conn_executor_exec.go#L3428-L3430](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/conn_executor_exec.go#L3428-L3430)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/conn_executor_exec.go#L145-L147](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/conn_executor_exec.go#L145-L147)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/conn_executor_exec.go#L1173-L1175](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/conn_executor_exec.go#L1173-L1175)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/conn_executor_exec.go#L1840-L1842](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/conn_executor_exec.go#L1840-L1842)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/conn_executor_exec.go#L2290-L2292](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/conn_executor_exec.go#L2290-L2292)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/plan_opt.go#L250-L252](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/plan_opt.go#L250-L252)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/plan_opt.go#L808-L810](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/plan_opt.go#L808-L810)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/plan_opt.go#L784-L786](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/plan_opt.go#L784-L786)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/plan_opt.go#L556-L558](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/plan_opt.go#L556-L558)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/xform/optimizer.go#L269-L271](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/xform/optimizer.go#L269-L271)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/xform/optimizer.go#L523-L525](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/xform/optimizer.go#L523-L525)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/xform/optimizer.go#L578-L580](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/xform/optimizer.go#L578-L580)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/xform/optimizer.go#L299-L301](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/xform/optimizer.go#L299-L301)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/xform/optimizer.go#L536-L538](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/xform/optimizer.go#L536-L538)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/xform/explorer.go#L184-L186](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/xform/explorer.go#L184-L186)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/bazel-out/k8-opt/bin/pkg/sql/opt/xform/explorer.og.go#L25-L27](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/bazel-out/k8-opt/bin/pkg/sql/opt/xform/explorer.og.go#L25-L27)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/bazel-out/k8-opt/bin/pkg/sql/opt/xform/explorer.og.go#L360-L362](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/bazel-out/k8-opt/bin/pkg/sql/opt/xform/explorer.og.go#L360-L362)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/xform/select_funcs.go#L441-L443](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/xform/select_funcs.go#L441-L443)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/xform/scan_index_iter.go#L206-L208](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/xform/scan_index_iter.go#L206-L208)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/xform/scan_index_iter.go#L303-L305](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/xform/scan_index_iter.go#L303-L305)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/xform/select_funcs.go#L449-L451](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/xform/select_funcs.go#L449-L451)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/xform/select_funcs.go#L297-L299](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/xform/select_funcs.go#L297-L299)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/xform/select_funcs.go#L1054-L1056](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/xform/select_funcs.go#L1054-L1056)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/xform/general_funcs.go#L201-L203](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/xform/general_funcs.go#L201-L203)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/idxconstraint/index_constraints.go#L1135-L1137](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/idxconstraint/index_constraints.go#L1135-L1137)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/idxconstraint/index_constraints.go#L679-L681](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/idxconstraint/index_constraints.go#L679-L681)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/idxconstraint/index_constraints.go#L804-L806](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/idxconstraint/index_constraints.go#L804-L806)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/constraint/constraint.go#L201-L203](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/constraint/constraint.go#L201-L203)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/constraint/span.go#L221-L223](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/constraint/span.go#L221-L223)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/constraint/key.go#L115-L117](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/constraint/key.go#L115-L117)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/constraint/key.go#L324-L326](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/constraint/key.go#L324-L326)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/sem/tree/datum.go#L5345-L5347](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/sem/tree/datum.go#L5345-L5347)
</details>

```
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithProfiling at line 3429
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt.func1 at line 146
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 1174
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchToExecutionEngine at line 1841
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).makeExecPlan at line 2291
pkg/sql/plan_opt.go in pkg/sql.(*planner).makeOptimizerPlan at line 251
pkg/sql/plan_opt.go in pkg/sql.(*optPlanningCtx).buildExecMemo at line 809
pkg/sql/plan_opt.go in pkg/sql.(*optPlanningCtx).fetchPreparedMemoLegacy at line 785
pkg/sql/plan_opt.go in pkg/sql.(*optPlanningCtx).reuseMemo at line 557
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).Optimize at line 270
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).optimizeGroup at line 524
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).optimizeGroupMember at line 579
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).optimizeExpr at line 300
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).optimizeGroup at line 537
pkg/sql/opt/xform/explorer.go in pkg/sql/opt/xform.(*explorer).exploreGroup at line 185
bazel-out/k8-opt/bin/pkg/sql/opt/xform/explorer.og.go in pkg/sql/opt/xform.(*explorer).exploreGroupMember at line 26
bazel-out/k8-opt/bin/pkg/sql/opt/xform/explorer.og.go in pkg/sql/opt/xform.(*explorer).exploreSelect at line 361
pkg/sql/opt/xform/select_funcs.go in pkg/sql/opt/xform.(*CustomFuncs).GenerateConstrainedScans at line 442
pkg/sql/opt/xform/scan_index_iter.go in pkg/sql/opt/xform.(*scanIndexIter).ForEach at line 207
pkg/sql/opt/xform/scan_index_iter.go in pkg/sql/opt/xform.(*scanIndexIter).ForEachStartingAfter at line 304
pkg/sql/opt/xform/select_funcs.go in pkg/sql/opt/xform.(*CustomFuncs).GenerateConstrainedScans.func1 at line 450
pkg/sql/opt/xform/select_funcs.go in pkg/sql/opt/xform.(*CustomFuncs).MakeCombinedFiltersConstraint at line 298
pkg/sql/opt/xform/select_funcs.go in pkg/sql/opt/xform.(*CustomFuncs).tryConstrainIndex at line 1055
pkg/sql/opt/xform/general_funcs.go in pkg/sql/opt/xform.(*CustomFuncs).initIdxConstraintForIndex at line 202
pkg/sql/opt/idxconstraint/index_constraints.go in pkg/sql/opt/idxconstraint.(*Instance).Init at line 1136
pkg/sql/opt/idxconstraint/index_constraints.go in pkg/sql/opt/idxconstraint.(*indexConstraintCtx).makeSpansForExpr at line 680
pkg/sql/opt/idxconstraint/index_constraints.go in pkg/sql/opt/idxconstraint.(*indexConstraintCtx).makeSpansForAnd at line 805
pkg/sql/opt/constraint/constraint.go in pkg/sql/opt/constraint.(*Constraint).IntersectWith at line 202
pkg/sql/opt/constraint/span.go in pkg/sql/opt/constraint.(*Span).StartsAfter at line 222
pkg/sql/opt/constraint/key.go in pkg/sql/opt/constraint.Key.Compare at line 116
pkg/sql/opt/constraint/key.go in pkg/sql/opt/constraint.(*KeyContext).Compare at line 325
pkg/sql/sem/tree/datum.go in pkg/sql/sem/tree.(*DEnum).Compare at line 5346
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v24.2.0 |
| Go Version | go1.22.5 X:nocoverageredesign |
| Platform | linux arm64 |
| Distribution | CCL |
| Cockroach Release | v24.2.0 |
| Cockroach SHA | 953d09cce5a01cc0053e138516d80a27454f027c |
| # of CPUs | 12 |
| # of Goroutines | 711 |

Jira issue: CRDB-42495

**Comment by yuzefovich** [comment]
dup of #129623
