### ISSUE TITLE
Behavior outside of SQL Standard when updating a single row many (millions of) times

### ISSUE THREAD

**Issue by lancel66** [cockroachdb/cockroach#131308]
**Describe the problem**

Most enterprise data stores support a updating a single row many (millions of) times without issue. (Postgres, Yugabyte, Oracle, SQL Server, DB2, DynamoDB, Redis, MongoDB).  Looking through the SQL Standard (https://en.wikipedia.org/wiki/SQL-92), there are no mentions of this operation not being allowed.  This requires application developers to implement workarounds in many cases, especially with migrations.

**To Reproduce**

Update a single row many (millions of) times

**Expected behavior**

CockroachDB should behave the same as other data stores

**Additional context**

Application developer time lost due to code rewrite for workaround. Tickets opened, more time lost.

Jira issue: CRDB-42493

**Comment by nicktrav** [comment]
@lancel66 - wdyt about merging this in with the one we have open already, which is more targeted at the issue at hand: https://github.com/cockroachdb/cockroach/issues/92705

**Comment by lancel66** [comment]
> @lancel66 - wdyt about merging this in with the one we have open already, which is more targeted at the issue at hand: #92705

Hi @nicktrav merging sounds good to me, just wanted to capture the "SQL Standard" viewpoint on this. Thanks!
