### ISSUE TITLE
sql: v24.2.3: nil local flow with pausable portals

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#131337]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5904382287/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5904382287/?referrer=webhooks_plugin)

Panic Message:

```
conn_executor.go:961: runtime error: invalid memory address or nil pointer dereference
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:961
  | [...repeated from below...]
Wraps: (2) while executing: SELECT CAST(_._._ AS DATE) AS _, _(DISTINCT _._._) AS _, _(_._._) AS _ FROM _ WHERE ((((((_._._ != _) OR (_._._ IS NULL)) AND ((_._._ != _) OR (_._._ IS NULL))) AND ((_._._ != _) OR (_._._ IS NULL))) AND (_._._ >= (CAST(_('_', CAST((CAST((CAST(_() AS TIMESTAMP) + ('_'::INTERVAL)) AS TIMESTAMP) + ('_'::INTERVAL)) AS TIMESTAMP)) AS TIMESTAMP) + ('_'::INTERVAL)))) AND (_._._ < (CAST(_('_', CAST((CAST((CAST(_() AS TIMESTAMP) + ('_'::INTERVAL)) AS TIMESTAMP) + ('_'::INTERVAL)) AS TIMESTAMP)) AS TIMESTAMP) + ('_'::INTERVAL)))) GROUP BY CAST(_._._ AS DATE) ORDER BY CAST(_._._ AS DATE) ASC
Wraps: (3) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:961
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:770
  | runtime.panicmem
  | 	GOROOT/src/runtime/panic.go:261
  | runtime.sigpanic
  | 	GOROOT/src/runtime/signal_unix.go:881
  | github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).GetFlowCtx
  | 	github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:368
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).resumeFlowForPausablePortal.getFinishedSetupFn.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1652
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).resumeFlowForPausablePortal
  | 	github.com/cockroachdb/cockroach/pkg/sql/planner.go:314
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2393
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1967
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchReadCommittedStmtToExecutionEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1715
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1169
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:146
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:3429
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:145
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execPortal
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:251
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2421
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2423
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2238
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:963
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommands
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:256
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).serveImpl.func4
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:1136
  | runtime.goexit
  | 	src/runtime/asm_amd64.s:1695
Wraps: (4) runtime error: invalid memory address or nil pointer dereference
Error types: (1) *withstack.withStack (2) *safedetails.withSafeDetails (3) *withstack.withStack (4) runtime.errorString
-- report composition:
runtime.errorString
conn_executor.go:961: *withstack.withStack (top exception)
*safedetails.withSafeDetails: while executing: SELECT CAST(_._._ AS DATE) AS _, _(DISTINCT _._._) AS _, _(_._._) AS _ FROM _ WHERE ((((((_._._ != _) OR (_._._ IS NULL)) AND ((_._._ != _) OR (_._._ IS NULL))) AND ((_._._ != _) OR (_._._ IS NULL))) AND (_._._ >= (CAST(_('_', CAST((CAST((CAST(_() AS TIMESTAMP) + ('_'::INTERVAL)) AS TIMESTAMP) + ('_'::INTERVAL)) AS TIMESTAMP)) AS TIMESTAMP) + ('_'::INTERVAL)))) AND (_._._ < (CAST(_('_', CAST((CAST((CAST(_() AS TIMESTAMP) + ('_'::INTERVAL)) AS TIMESTAMP) + ('_'::INTERVAL)) AS TIMESTAMP)) AS TIMESTAMP) + ('_'::INTERVAL)))) GROUP BY CAST(_._._ AS DATE) ORDER BY CAST(_._._ AS DATE) ASC
conn_executor.go:961: *withstack.withStack (1)
(check the extra data payloads)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_amd64.s#L1694-L1696](src/runtime/asm_amd64.s#L1694-L1696)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/pgwire/server.go#L1135-L1137](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/pgwire/server.go#L1135-L1137)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/pgwire/conn.go#L255-L257](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/pgwire/conn.go#L255-L257)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/conn_executor.go#L962-L964](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/conn_executor.go#L962-L964)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/conn_executor.go#L2237-L2239](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/conn_executor.go#L2237-L2239)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/conn_executor.go#L2422-L2424](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/conn_executor.go#L2422-L2424)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/conn_executor.go#L2420-L2422](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/conn_executor.go#L2420-L2422)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/conn_executor_exec.go#L250-L252](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/conn_executor_exec.go#L250-L252)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/conn_executor_exec.go#L144-L146](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/conn_executor_exec.go#L144-L146)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/conn_executor_exec.go#L3428-L3430](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/conn_executor_exec.go#L3428-L3430)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/conn_executor_exec.go#L145-L147](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/conn_executor_exec.go#L145-L147)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/conn_executor_exec.go#L1168-L1170](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/conn_executor_exec.go#L1168-L1170)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/conn_executor_exec.go#L1714-L1716](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/conn_executor_exec.go#L1714-L1716)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/conn_executor_exec.go#L1966-L1968](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/conn_executor_exec.go#L1966-L1968)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/conn_executor_exec.go#L2392-L2394](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/conn_executor_exec.go#L2392-L2394)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/planner.go#L313-L315](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/planner.go#L313-L315)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/distsql_running.go#L1651-L1653](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/distsql_running.go#L1651-L1653)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/flowinfra/flow.go#L367-L369](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/flowinfra/flow.go#L367-L369)
[GOROOT/src/runtime/signal_unix.go#L880-L882](GOROOT/src/runtime/signal_unix.go#L880-L882)
[GOROOT/src/runtime/panic.go#L260-L262](GOROOT/src/runtime/panic.go#L260-L262)
[GOROOT/src/runtime/panic.go#L769-L771](GOROOT/src/runtime/panic.go#L769-L771)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/conn_executor.go#L960-L962](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/conn_executor.go#L960-L962)
</details>

```
src/runtime/asm_amd64.s in runtime.goexit at line 1695
pkg/sql/pgwire/server.go in pkg/sql/pgwire.(*Server).serveImpl.func4 at line 1136
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommands at line 256
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 963
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 2238
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 2423
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd.func2 at line 2421
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execPortal at line 251
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 145
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithProfiling at line 3429
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt.func1 at line 146
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 1169
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchReadCommittedStmtToExecutionEngine at line 1715
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchToExecutionEngine at line 1967
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithDistSQLEngine at line 2393
pkg/sql/planner.go in pkg/sql.(*planner).resumeFlowForPausablePortal at line 314
pkg/sql/distsql_running.go in pkg/sql.(*planner).resumeFlowForPausablePortal.getFinishedSetupFn.func1 at line 1652
pkg/sql/flowinfra/flow.go in pkg/sql/flowinfra.(*FlowBase).GetFlowCtx at line 368
GOROOT/src/runtime/signal_unix.go in runtime.sigpanic at line 881
GOROOT/src/runtime/panic.go in runtime.panicmem at line 261
GOROOT/src/runtime/panic.go in runtime.gopanic at line 770
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn.func1 at line 961
```

### Tags

| Tag | Value |
| --- | --- |
| Command | mt start-sql |
| Environment | v24.2.3 |
| Go Version | go1.22.5 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v24.2.3 |
| Cockroach SHA | 217b43e69da61e9712d73e3e19fd5076fbdb26df |
| # of CPUs | 16 |
| # of Goroutines | 464 |

Jira issue: CRDB-42504

**Comment by fqazi** [comment]
Closing this in favour of: https://github.com/cockroachdb/cockroach/issues/128297, since its related
