### ISSUE TITLE
ui: Events should record the database name as well as the table name.

### ISSUE THREAD

**Issue by maxlang** [cockroachdb/cockroach#13143]
Currently events that target a table such as the `CREATE TABLE` event or `ALTER TABLE` event record the table name but not the database name. For example, here's the info field for an `ALTER TABLE` event:

```{ "TableName": "test", "IndexName": "\"\"", "Statement": "CREATE INDEX ON test.test (id)", "User": "root", "MutationID": 5 }```

It would be nice to record the database name as well so that we can more easily identify the exact table.

Note that this is a "want to have" not a blocker. We can currently use the target ID and a list of all tables to identify the exact table an event occurred on. The issue is that we need to pull down a list of all tables first, rather than just the tables for a specific database.

**Comment by dianasaur323** [comment]
If this is a "want to have" and not a blocker, let's move milestones.

**Comment by dianasaur323** [comment]
Doesn't seem like a huge deal. Moving to 1.2

**Comment by jordanlewis** [comment]
@dhartunian hey, is this relevant to you? Feel free to close, but pinging your way!

**Comment by dhartunian** [comment]
Closing this. The db/table tagging I was looking for was on the statement level, not event-level. If requirements come up that need this I'm fine with creating a new ticket.
