### ISSUE TITLE
Sentry: prepared_stmt.go:115: log.Fatal: corrupt PreparedStatement refcount
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*PreparedStatement).decRef
  | 	git...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#131598]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5930281822/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5930281822/?referrer=webhooks_plugin)

Panic Message:

```
prepared_stmt.go:115: log.Fatal: corrupt PreparedStatement refcount
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*PreparedStatement).decRef
  | 	github.com/cockroachdb/cockroach/pkg/sql/prepared_stmt.go:115
  | github.com/cockroachdb/cockroach/pkg/sql.(*PreparedPortal).close
  | 	github.com/cockroachdb/cockroach/pkg/sql/prepared_stmt.go:327
  | github.com/cockroachdb/cockroach/pkg/sql.(*prepStmtNamespace).closeAllPortals
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1946
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).close
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1255
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1231
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:961
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:770
  | runtime.panicmem
  | 	GOROOT/src/runtime/panic.go:261
  | runtime.sigpanic
  | 	GOROOT/src/runtime/signal_unix.go:881
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).getCommonSQLEventDetails
  | 	github.com/cockroachdb/cockroach/pkg/sql/event_log.go:200
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).logEventsWithOptions
  | 	github.com/cockroachdb/cockroach/pkg/sql/event_log.go:221
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).logOperationalEventsOnlyExternally
  | 	github.com/cockroachdb/cockroach/pkg/sql/exec_log.go:549
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).maybeLogStatementInternal
  | 	github.com/cockroachdb/cockroach/pkg/sql/exec_log.go:444
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).maybeLogStatement
  | 	github.com/cockroachdb/cockroach/pkg/sql/exec_log.go:149
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState.func15
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:781
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState.func3.1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:314
  | github.com/cockroachdb/cockroach/pkg/sql.(*cleanupFuncStack).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/prepared_stmt.go:356
  | github.com/cockroachdb/cockroach/pkg/sql.(*portalPauseInfo).cleanupAll
  | 	github.com/cockroachdb/cockroach/pkg/sql/prepared_stmt.go:480
  | github.com/cockroachdb/cockroach/pkg/sql.(*PreparedPortal).close
  | 	github.com/cockroachdb/cockroach/pkg/sql/prepared_stmt.go:329
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).deletePortal
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:609
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execBind
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:411
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2454
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2238
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:963
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommands
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:256
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).serveImpl.func4
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:1136
  | runtime.goexit
  | 	src/runtime/asm_amd64.s:1695
Wraps: (2) log.Fatal: corrupt PreparedStatement refcount
Error types: (1) *withstack.withStack (2) *errutil.leafError
-- report composition:
*errutil.leafError: log.Fatal: corrupt PreparedStatement refcount
prepared_stmt.go:115: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_amd64.s#L1694-L1696](src/runtime/asm_amd64.s#L1694-L1696)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/pgwire/server.go#L1135-L1137](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/pgwire/server.go#L1135-L1137)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/pgwire/conn.go#L255-L257](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/pgwire/conn.go#L255-L257)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/conn_executor.go#L962-L964](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/conn_executor.go#L962-L964)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/conn_executor.go#L2237-L2239](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/conn_executor.go#L2237-L2239)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/conn_executor.go#L2453-L2455](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/conn_executor.go#L2453-L2455)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/conn_executor_prepare.go#L410-L412](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/conn_executor_prepare.go#L410-L412)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/conn_executor_prepare.go#L608-L610](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/conn_executor_prepare.go#L608-L610)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/prepared_stmt.go#L328-L330](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/prepared_stmt.go#L328-L330)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/prepared_stmt.go#L479-L481](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/prepared_stmt.go#L479-L481)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/prepared_stmt.go#L355-L357](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/prepared_stmt.go#L355-L357)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/conn_executor_exec.go#L313-L315](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/conn_executor_exec.go#L313-L315)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/conn_executor_exec.go#L780-L782](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/conn_executor_exec.go#L780-L782)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/exec_log.go#L148-L150](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/exec_log.go#L148-L150)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/exec_log.go#L443-L445](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/exec_log.go#L443-L445)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/exec_log.go#L548-L550](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/exec_log.go#L548-L550)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/event_log.go#L220-L222](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/event_log.go#L220-L222)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/event_log.go#L199-L201](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/event_log.go#L199-L201)
[GOROOT/src/runtime/signal_unix.go#L880-L882](GOROOT/src/runtime/signal_unix.go#L880-L882)
[GOROOT/src/runtime/panic.go#L260-L262](GOROOT/src/runtime/panic.go#L260-L262)
[GOROOT/src/runtime/panic.go#L769-L771](GOROOT/src/runtime/panic.go#L769-L771)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/conn_executor.go#L960-L962](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/conn_executor.go#L960-L962)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/conn_executor.go#L1230-L1232](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/conn_executor.go#L1230-L1232)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/conn_executor.go#L1254-L1256](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/conn_executor.go#L1254-L1256)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/conn_executor.go#L1945-L1947](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/conn_executor.go#L1945-L1947)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/prepared_stmt.go#L326-L328](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/prepared_stmt.go#L326-L328)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/prepared_stmt.go#L114-L116](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/prepared_stmt.go#L114-L116)
</details>

```
src/runtime/asm_amd64.s in runtime.goexit at line 1695
pkg/sql/pgwire/server.go in pkg/sql/pgwire.(*Server).serveImpl.func4 at line 1136
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommands at line 256
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 963
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 2238
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 2454
pkg/sql/conn_executor_prepare.go in pkg/sql.(*connExecutor).execBind at line 411
pkg/sql/conn_executor_prepare.go in pkg/sql.(*connExecutor).deletePortal at line 609
pkg/sql/prepared_stmt.go in pkg/sql.(*PreparedPortal).close at line 329
pkg/sql/prepared_stmt.go in pkg/sql.(*portalPauseInfo).cleanupAll at line 480
pkg/sql/prepared_stmt.go in pkg/sql.(*cleanupFuncStack).run at line 356
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState.func3.1 at line 314
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState.func15 at line 781
pkg/sql/exec_log.go in pkg/sql.(*planner).maybeLogStatement at line 149
pkg/sql/exec_log.go in pkg/sql.(*planner).maybeLogStatementInternal at line 444
pkg/sql/exec_log.go in pkg/sql.(*planner).logOperationalEventsOnlyExternally at line 549
pkg/sql/event_log.go in pkg/sql.(*planner).logEventsWithOptions at line 221
pkg/sql/event_log.go in pkg/sql.(*planner).getCommonSQLEventDetails at line 200
GOROOT/src/runtime/signal_unix.go in runtime.sigpanic at line 881
GOROOT/src/runtime/panic.go in runtime.panicmem at line 261
GOROOT/src/runtime/panic.go in runtime.gopanic at line 770
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn.func1 at line 961
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).closeWrapper at line 1231
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).close at line 1255
pkg/sql/conn_executor.go in pkg/sql.(*prepStmtNamespace).closeAllPortals at line 1946
pkg/sql/prepared_stmt.go in pkg/sql.(*PreparedPortal).close at line 327
pkg/sql/prepared_stmt.go in pkg/sql.(*PreparedStatement).decRef at line 115
```

### Tags

| Tag | Value |
| --- | --- |
| Command | mt start-sql |
| Environment | v24.2.3 |
| Go Version | go1.22.5 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v24.2.3 |
| Cockroach SHA | 217b43e69da61e9712d73e3e19fd5076fbdb26df |
| # of CPUs | 32 |
| # of Goroutines | 798 |

Jira issue: CRDB-42626

**Comment by yuzefovich** [comment]
dup of #132103
