### ISSUE TITLE
ui: change graphs on main page

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#13163]
I think there is value to place up front on the cluster page graphs that 1. provide confidence that the system is functioning, 2. graphs that an average user will understand without understanding internal details.

This could mean introducing a ```Main``` category in the dashboard

- Main category graphs: SQL Queries, Transactions, Latency 99%, Latency 90%, Capacity, Replicas per node (?)

We could then consider folding the remaining of the SQL category into the runtime category

**Comment by kuanluo** [comment]
@vivekmenezes @maxlang 

Sounds like a good plan - We talked about highlighting some key information and this is the easiest way to get it done. So I'm onboard.

**Comment by vivekmenezes** [comment]
Hey can we make this a top priority. I'd like to have all Beta customers see the new main page

**Comment by vivekmenezes** [comment]
https://honeycomb.io/blog/2017/01/instrumentation-the-first-four-things-you-measure/

we need to ensure that we have these four things on the main page

**Comment by bdarnell** [comment]
We're currently only measuring requests at the end, not the start (which means that our current monitoring never reports on requests that hang without ever returning)
