### ISSUE TITLE
sql: invalid use of client.Txn.SetSystemConfigTrigger

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#13175]
#13167 verifies that `client.Txn.SetSystemConfigTrigger` is called before any transactional writes are executed. `SchemaChanger.{truncateAndBackfillColumnsChunk,truncateIndexes,backfillIndexesChunk}` violated this assertion by calling `SetSystemConfigTrigger` conditionally after a lot of other transactional work. A temporary workaround was added in #13167 which calls `SetSystemConfigTrigger` immediately after the transaction is created, but that is somewhat unsatisfactory as it anchors all of the schema change transactions on the system-config range. It isn't clear to me that `SetSystemConfigTrigger` is needed at all here, but someone with more knowledge of the schema change code will have to look at this closer. 

PS The system-config trigger, when set, causes the system-config span to be gossiped when a transaction commits. This is necessary to propagate changes to TableDescriptors, but I'm not clear on whether the type of TableDescriptor changes being performed by `SchemaChanger.maybeWriteResumeSpan` require the TableDescriptors to be gossiped.

**Comment by bdarnell** [comment]
Yeah, the schema change checkpoints don't need to be gossiped. I think it would be correct to just omit the SystemConfigTrigger on transactions that only update the checkpoint, although it doesn't feel great to allow divergence between the persisted and gossiped descriptors. In #6643 we discussed using a new non-gossiped system table for checkpoints (or conversely, trimming the gossiped table down to the `version` field and moving all the rest out to a non-gossipped table)

**Comment by vivekmenezes** [comment]
I can confirm that we do not need the checkpoints to be gossiped.

Going forward it's a good idea to ensure that only the table versions are gossiped. This can be achieved by:

1. Creating a new DescriptorVersion table with only the descriptor ids and their versions
2. Only gossip this new table and stop gossiping the old descriptor table.
3. Fix all the places incrementing the descriptor version to update the new descriptor version table.
4. Remove the need to SetSystemConfigTrigger() when updating a descriptor.
5. Change the gossip notifications to read the descriptors on a version change.
6. write a system upgrade function that reads all the descriptors and populates the new descriptor version table. This upgrade function should also re-gossip the new upgraded table.

**Comment by vivekmenezes** [comment]
this is likely fixed, @jordanlewis to review and close

**Comment by jordanlewis** [comment]
This is no longer relevant because we store schema change checkpoints in the jobs table now.
