### ISSUE TITLE
Sentry: conn_executor.go:909: interface conversion: tree.FnOverload is nil, not func(context.Context, *eval.Context, tree.Datums) (tree.Datum, error)
(1) attached stack trace
  -- stack trace:
  | git...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#131887]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5950045422/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5950045422/?referrer=webhooks_plugin)

Panic Message:

```
conn_executor.go:909: interface conversion: tree.FnOverload is nil, not func(context.Context, *eval.Context, tree.Datums) (tree.Datum, error)
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:909
  | [...repeated from below...]
Wraps: (2) while executing: SET LOCAL search_path = string_agg(_, _)
Wraps: (3) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:909
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:110
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:110
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | runtime.panicdottypeE
  | 	GOROOT/src/runtime/iface.go:262
  | github.com/cockroachdb/cockroach/pkg/sql/sem/eval.(*evaluator).EvalFuncExpr
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/eval/expr.go:483
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FuncExpr).Eval
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/sem/tree/eval_expr_generated.go:276
  | github.com/cockroachdb/cockroach/pkg/sql/sem/eval.Expr
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/eval/expr.go:26
  | github.com/cockroachdb/cockroach/pkg/sql.(*setVarNode).startExec
  | 	github.com/cockroachdb/cockroach/pkg/sql/set_var.go:134
  | github.com/cockroachdb/cockroach/pkg/sql.startExec.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan.go:519
  | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:112
  | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:299
  | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:79
  | github.com/cockroachdb/cockroach/pkg/sql.walkPlan
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:43
  | github.com/cockroachdb/cockroach/pkg/sql.startExec
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan.go:522
  | github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Start
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:175
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Columnarizer).Init
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/columnarizer.go:183
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).init
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:94
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:135
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).Init
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:103
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).init.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:245
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:135
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).init
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:244
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:278
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:328
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:916
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1910
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll.func3
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1641
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1644
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2214
Wraps: (4) interface conversion: tree.FnOverload is nil, not func(context.Context, *eval.Context, tree.Datums) (tree.Datum, error)
Error types: (1) *withstack.withStack (2) *safedetails.withSafeDetails (3) *withstack.withStack (4) *runtime.TypeAssertionError
-- report composition:
*runtime.TypeAssertionError
conn_executor.go:909: *withstack.withStack (top exception)
*safedetails.withSafeDetails: while executing: SET LOCAL search_path = string_agg(_, _)
conn_executor.go:909: *withstack.withStack (1)
(check the extra data payloads)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/conn_executor_exec.go#L2213-L2215](https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/conn_executor_exec.go#L2213-L2215)
[https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/distsql_running.go#L1643-L1645](https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/distsql_running.go#L1643-L1645)
[https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/distsql_running.go#L1640-L1642](https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/distsql_running.go#L1640-L1642)
[https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/distsql_running.go#L1909-L1911](https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/distsql_running.go#L1909-L1911)
[https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/distsql_running.go#L915-L917](https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/distsql_running.go#L915-L917)
[https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/colflow/vectorized_flow.go#L327-L329](https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/colflow/vectorized_flow.go#L327-L329)
[https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/colflow/flow_coordinator.go#L277-L279](https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/colflow/flow_coordinator.go#L277-L279)
[https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/colflow/flow_coordinator.go#L243-L245](https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/colflow/flow_coordinator.go#L243-L245)
[https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/colexecerror/error.go#L134-L136](https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/colexecerror/error.go#L134-L136)
[https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/colflow/flow_coordinator.go#L244-L246](https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/colflow/flow_coordinator.go#L244-L246)
[https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/colflow/stats.go#L102-L104](https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/colflow/stats.go#L102-L104)
[https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/colexecerror/error.go#L134-L136](https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/colexecerror/error.go#L134-L136)
[https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/colflow/stats.go#L93-L95](https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/colflow/stats.go#L93-L95)
[https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/colexec/columnarizer.go#L182-L184](https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/colexec/columnarizer.go#L182-L184)
[https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/plan_node_to_row_source.go#L174-L176](https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/plan_node_to_row_source.go#L174-L176)
[https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/plan.go#L521-L523](https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/plan.go#L521-L523)
[https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/walk.go#L42-L44](https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/walk.go#L42-L44)
[https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/walk.go#L78-L80](https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/walk.go#L78-L80)
[https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/walk.go#L298-L300](https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/walk.go#L298-L300)
[https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/walk.go#L111-L113](https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/walk.go#L111-L113)
[https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/plan.go#L518-L520](https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/plan.go#L518-L520)
[https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/set_var.go#L133-L135](https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/set_var.go#L133-L135)
[https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/sem/eval/expr.go#L25-L27](https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/sem/eval/expr.go#L25-L27)
[https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/bazel-out/k8-opt/bin/pkg/sql/sem/tree/eval_expr_generated.go#L275-L277](https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/bazel-out/k8-opt/bin/pkg/sql/sem/tree/eval_expr_generated.go#L275-L277)
[https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/sem/eval/expr.go#L482-L484](https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/sem/eval/expr.go#L482-L484)
[GOROOT/src/runtime/iface.go#L261-L263](GOROOT/src/runtime/iface.go#L261-L263)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
[https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/colexecerror/error.go#L109-L111](https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/colexecerror/error.go#L109-L111)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
[https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/colexecerror/error.go#L109-L111](https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/colexecerror/error.go#L109-L111)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
[https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/conn_executor.go#L908-L910](https://github.com/cockroachdb/cockroach/blob/8705c1e39813e08ab5d582b19f401e1ad5dab4c5/pkg/sql/conn_executor.go#L908-L910)
</details>

```
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithDistSQLEngine at line 2214
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRunAll at line 1644
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRunAll.func3 at line 1641
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRun at line 1910
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).Run at line 916
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlow).Run at line 328
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).Run at line 278
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).init at line 244
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 135
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).init.func1 at line 245
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).Init at line 103
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 135
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).init at line 94
pkg/sql/colexec/columnarizer.go in pkg/sql/colexec.(*Columnarizer).Init at line 183
pkg/sql/plan_node_to_row_source.go in pkg/sql.(*planNodeToRowSource).Start at line 175
pkg/sql/plan.go in pkg/sql.startExec at line 522
pkg/sql/walk.go in pkg/sql.walkPlan at line 43
pkg/sql/walk.go in pkg/sql.(*planVisitor).visit at line 79
pkg/sql/walk.go in pkg/sql.(*planVisitor).visitInternal at line 299
pkg/sql/walk.go in pkg/sql.(*planVisitor).visitInternal.func1 at line 112
pkg/sql/plan.go in pkg/sql.startExec.func2 at line 519
pkg/sql/set_var.go in pkg/sql.(*setVarNode).startExec at line 134
pkg/sql/sem/eval/expr.go in pkg/sql/sem/eval.Expr at line 26
bazel-out/k8-opt/bin/pkg/sql/sem/tree/eval_expr_generated.go in pkg/sql/sem/tree.(*FuncExpr).Eval at line 276
pkg/sql/sem/eval/expr.go in pkg/sql/sem/eval.(*evaluator).EvalFuncExpr at line 483
GOROOT/src/runtime/iface.go in runtime.panicdottypeE at line 262
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1 at line 110
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1 at line 110
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn.func1 at line 909
```

### Tags

| Tag | Value |
| --- | --- |
| Command | start-single-node |
| Environment | v23.1.23 |
| Go Version | go1.19.13 |
| Platform | darwin arm64 |
| Distribution | CCL |
| Cockroach Release | v23.1.23 |
| Cockroach SHA | 8705c1e39813e08ab5d582b19f401e1ad5dab4c5 |
| # of CPUs | 10 |
| # of Goroutines | 413 |

Jira issue: CRDB-42736

**Comment by rafiss** [comment]
https://github.com/cockroachdb/cockroach/pull/131891 fixes this
