### ISSUE TITLE
PCR: multiple replication stream ingestion jobs can be started when cutting back to primary cluster

### ISSUE THREAD

**Issue by davidwding** [cockroachdb/cockroach#131836]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

When using physical cluster replication, it is possible to perform fast cutback to efficiently cutback to the original primary cluster. This is done using a statement like so:

`ALTER VIRTUAL CLUSTER {original_primary_vc} START REPLICATION OF {promoted_standby_vc} ON {connection_string_standby};`

It is possible to run this statement multiple times, and then observe using `SHOW JOBS;` that there are multiple replication stream ingestion jobs running on the virtual cluster, which should not happen.

**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. Set up PCR between two clusters as documented [here](https://www.cockroachlabs.com/docs/v24.1/set-up-physical-cluster-replication).
2. Perform cutover from the primary to the standby as documented [here](https://www.cockroachlabs.com/docs/v24.1/cutover-replication#cut-back-to-the-primary-cluster).
3. Initiate the fast cutback process to the original primary cluster as documented [here](https://www.cockroachlabs.com/docs/v24.1/cutover-replication#cut-back-to-the-primary-cluster), running the specified statement.
4. Repeat step 3, running the statement multiple times. It succeeds every time.
5. Run `SHOW JOBS` and observe one `REPLICATION STREAM INGESTION` job for each time the statement in step 3 was run.

**Expected behavior**
Running the `ALTER VIRTUAL CLUSTER...` statement multiple times should not work. There should not be multiple `REPLICATION STREAM INGESTION` on one virtual cluster.

**Additional data / screenshots**
n/a

**Environment:**
 - CockroachDB version [e.g. 2.0.x]: v24.1.0
 - Server OS: [e.g. Linux/Distrib]: linux amd64 (x86_64-pc-linux-gnu)
 - Client app [e.g. `cockroach sql`, JDBC, ...]: `cockroach sql`

**Additional context**
n/a

Jira issue: CRDB-42720

**Comment by msbutler** [comment]
@davidwding looks like you were testing on 24.1.0. This bug was actually fixed in a subsequent version of 24.1 https://github.com/cockroachdb/cockroach/pull/123735

But was not on 24.1.0
```
~/go/src/github.com/cockroachdb/master #v24.1.0 *1 ?1
❯ git log --oneline | grep "prevent starting duplicate replication"
```
