### ISSUE TITLE
sql: unnecessary transactional ID allocation in GenerateUniqueDescID

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#13180]
`sql.GenerateUniqueDescID` performs a KV Increment operation on the `/system/desc-idgen` key. It currently does so within a transaction, but there is not much reason for doing this. If the transaction aborts we're fine with leaking a key. On the flip side, doing the increment transactionally means we'll have a conflict if 2 transactions concurrently try to create a table/index/view/etc.

I'm pretty sure the code originally allocated IDs non-transactionally. My git-fu isn't strong enough to discover when this changed. If this is intentional behavior, we should add a comment documenting it to `GenerateUniqueDescID` so that nobody accidentally "fixes" it.

Assigning to @vivekmenezes for triage.

**Comment by vivekmenezes** [comment]
We can change it to be non-transactional. The only problem is that whenever we hit errors, 1. some tests depending on specific tableids will become flaky, and 2. we could eventually run out of table ids. Not sure what's the benefit of not using a transaction; do we really care about contention here?

**Comment by dt** [comment]
In `create table` I think there are some error/bad input cases that checked after we bump it, where we're leaning on the txn to avoid wasting low table ids (which are somewhat at a premium since that var int goes at the front of *every* key) unless we're actually going to create a table.

**Comment by petermattis** [comment]
@vivekmenezes The only tests I'm aware of that are dependent on specific table IDs are the ones which list keys. I doubt there would be a problem with the table IDs being non-deterministic (though feel free to prove me wrong).

With a 64-bit ID, we're never going to run out of table IDs, so that shouldn't be a concern.
