### ISSUE TITLE
CockroachDB is producing duplicate metrics on same instance.

### ISSUE THREAD

**Issue by asiyani** [cockroachdb/cockroach#131926]
**Describe the problem**

CockroachDB is producing duplicate metrics on same instance.
 
We found following metrics with duplicate series 
* mem_sql_current
* mem_sql_max_bucket
* mem_sql_max_bucke
* mem_sql_max_count
* mem_sql_max_sum
* mem_sql_session_current
* mem_sql_session_max_bucket
* mem_sql_session_max_count
* mem_sql_session_max_sum
* mem_sql_txn_current
* mem_sql_txn_max_bucket
* mem_sql_txn_max_count
* mem_sql_txn_max_sum

eg
```
# HELP sql_mem_sql_current Current sql statement memory usage for sql
# TYPE sql_mem_sql_current gauge
sql_mem_sql_current 112640.0
sql_mem_sql_current 112640.0
# HELP sql_mem_sql_max Memory usage per sql statement for sql
# TYPE sql_mem_sql_max histogram
sql_mem_sql_max_bucket{le="4487.0"} 4.0
sql_mem_sql_max_bucket{le="5243.0"} 8.0
sql_mem_sql_max_bucket{le="6127.0"} 13.0
sql_mem_sql_max_bucket{le="+Inf"} 13.0
sql_mem_sql_max_sum 69555.0
sql_mem_sql_max_count 13.0
sql_mem_sql_max_bucket{le="4487.0"} 4.0
sql_mem_sql_max_bucket{le="5243.0"} 8.0
sql_mem_sql_max_bucket{le="6127.0"} 13.0
sql_mem_sql_max_bucket{le="+Inf"} 13.0
```

**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. Set up port forwarding `kubectl port-forward cockroach-0 8000:8000`
2. open `http://localhost:8000/_status/vars` and search for these metrics

**Expected behavior**
For given label metrics series should be unique.

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version v20.1.3

**Additional context**
What was the impact?
Prometheus generates warning logs every minute because of these duplicate metrics

```caller=scrape.go:1754 level=warn component="scrape manager" scrape_pool=kubernetes-service-endpoints target=http://10.2.30.46:8000/_status/vars msg="Error on ingesting samples with different value but same timestamp" num_dropped=22```

Jira issue: CRDB-42756

**Comment by alyshanjahani-crl** [comment]
Hey @asiyani i see this on a version of CRDB that is passed its end of support https://www.cockroachlabs.com/docs/releases/release-support-policy#end-of-life-eol-versions

On `v24.2.3` of CRDB for example i see `sql_mem_sql_current`  isn't duplicated.
```
# HELP sql_mem_sql_current Current sql statement memory usage for sql
# TYPE sql_mem_sql_current gauge
sql_mem_sql_current{node_id="41"} 0
```
 
In your example you list a histogram metric. Note that these are not duplicates since they have different labels (for each bucket in the histogram):
```
# HELP sql_mem_sql_max Memory usage per sql statement for sql
# TYPE sql_mem_sql_max histogram
sql_mem_sql_max_bucket{le="4487.0"} 4.0
sql_mem_sql_max_bucket{le="5243.0"} 8.0
sql_mem_sql_max_bucket{le="6127.0"} 13.0
sql_mem_sql_max_bucket{le="+Inf"} 13.0
sql_mem_sql_max_sum 69555.0
sql_mem_sql_max_count 13.0
sql_mem_sql_max_bucket{le="4487.0"} 4.0
sql_mem_sql_max_bucket{le="5243.0"} 8.0
sql_mem_sql_max_bucket{le="6127.0"} 13.0
sql_mem_sql_max_bucket{le="+Inf"} 13.0
```
