### ISSUE TITLE
storage: TestRefreshPendingCommands is flaky

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#13199]
See discussion and de-flake in #13158. `multiTestContext.restartNode()` sometimes blocks because a heartbeat `cput` never completes.

**Comment by petermattis** [comment]
From a [comment](https://github.com/cockroachdb/cockroach/pull/13158#issuecomment-275738847):

> Why do you think this has anything to do with leases? From what you wrote, sounds like the mystery is why a CPUT disappears into the void?

The first step in the CPut is to request the range lease and it never seems to make it past that step. At least, that was as far as I got in the debugging.

**Comment by andreimatei** [comment]
Still no idea what's going on here, but one observation is that, when the test succeeds, the `NodeLiveness.IncrementEpoch()` never seems to succeed for the restarted node; it returns a "context cancelled" error.
When the test fails, the epoch is incremented, but the increment that succeeds has a very low expiration (approx equal to a non-epoch lease duration). This means that the node is not live after that increment, since the clock has already been advanced ~ 2*lease duration (because the test drains some leases). 
And then the test sends another increment, and it's unclear what's going on with it; it doesn't seem to be applied.

**Comment by andreimatei** [comment]
Here's what's going on:

The test deadlocks when trying to restart store 3 on recursive heartbeating of the liveness record. While the store was stopped, Raft state has advanced.

- part of restarting the store, we start the heartbeating routine on store 3.
- the routine tries to increment the epoch on the first loop, so store 3 wants to increment itself to 2.  It sends a CPut.
- node 3 is not aware of the latest lease. Sends a `RequestLeaseRequest`.
- the lease acq request is sent under an ancient lease - starting at 0.0, not at 0.9, and owner by node 1, not 2 - not under the current lease. Thus, it is rejected with a `LeaseRejectedError`. The `replicaPendingLease` transforms the lease rejection into a `NotLeaseHolderError` and, because the current lease is also expired, returns a NLHE with an unknown leaseholder. 
- the `multiTestContext` transport sees the NLHE with unknown leaseholder. It thinks that it *might* be because the leaseholder was removed from the group (which is not the case), so it moves the clock to expire all leases and it increments all the epochs.
- incrementing the epoch also tries to do heartbeat, and this heartbeat blocks on the on the ongoing one (we don't allow more than one heartbeat at a time).

The solution seems to be to either:
1. stop incrementing the epochs in `multiTestContextKVTransport.expireLeases()`. Advancing the clock should be enough for "expiring leases". I talked to @spencerkimball and we're not quite sure why the code also increments all the epochs instead of relying on it being done the next time someone want to take a lease. But there was probably a subtle reason having to do with test fragility, so I'm expecting pain.
1. make that brutal `multiTestContextKVTransport.SendNext()` more discriminate about when it needs to call `expireLeases()`. In particular, it needs to call it when a leaseholder was removed from a group, but that's not the case here. We can find a way to tell it through the NLHE that that's not the case.

**Comment by tamird** [comment]
On Tue, Jan 31, 2017 at 7:56 PM, Andrei Matei <notifications@github.com>
wrote:

> - stop incrementing the epochs in multiTestContextKVTransport.
> expireLeases(). Advancing the clock should be enough for "expiring
> leases". I talked to @spencerkimball <https://github.com/spencerkimball>
> and we're not quite sure why the code also increments all the epochs
> instead of relying on it being done the next time someone want to take a
> lease. But there was probably a subtle reason having to do with test
> fragility, so I'm expecting pain.


If spencer doesn't know what the pain here was, there might not have been
any? That code was added in 4c2b798d4dbf3bc02d9b05ea769e29be6d2d9810, which
is the "initial commit" of epoch based leases, so spencer is the only
person who would have seen test fragility there, if it existed.

I'd try this before adding yet more stuff to NLHE.

**Comment by bdarnell** [comment]
Yeah, we may be able to just get rid of that and rename `expireLeases` to `advanceClock`. Most callers of this method don't actually need all leases to be revoked, they just want to wait until some other node *could* obtain the lease.
