### ISSUE TITLE
example_orms: TestActiveRecord/client-cert failed

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#132085]
I think the relevant message is:
```
server startup failed: cockroach server exited with error: consider changing the port via --listen-addr: listen tcp 127.0.0.1:41475: bind: address already in use
Failed running "mt start-sql"
    main_test.go:284: cockroach-go tenantserver WaitForInit failed: init did not finish for node 0
```
See test failure logs [here.](https://github.com/cockroachdb/cockroach/actions/runs/11214913848/job/31170986081) 

Jira issue: CRDB-42830

**Comment by rimadeodhar** [comment]
Closing as the logs seem to have rotated. We will take a look at this if we see this failure again.
