### ISSUE TITLE
sql: EXPLAIN(PLAN) SELECT 1 shows something weird

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#13203]
Hey Raphael, is this expected?

```
root@:26257 ?> EXPLAIN (PLAN) SELECT 1;
+-------+---------+-------+-------------+
| Level |  Type   | Field | Description |
+-------+---------+-------+-------------+
|     0 | nullrow |       |             |
+-------+---------+-------+-------------+
```

**Comment by knz** [comment]
Ha! Go figure, I was also thinking about this same thing yesterday just before you filed the issue.

The word "nullrow" is expected yes, basically the renderNode renders things "for every row in its input" so a simple `select 1` has a `nullrow` input to trigger its rendering.

What's missing is an EXPLAIN line for the renderNode itself. I'll file a PR shortly just for that.
