### ISSUE TITLE
sql: CockroachDB does not implement three-valued logic properly

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#13217]
Symptom:

```
SELECT 'ok' WHERE 1 NOT IN (SELECT CAST (NULL AS INTEGER))
```

return `ok`, whereas it should return nothing.

See https://en.wikipedia.org/wiki/Null_(SQL)#Comparisons_with_NULL_and_the_three-valued_logic_.283VL.29

In particular: https://en.wikipedia.org/wiki/Null_(SQL)#Law_of_the_excluded_fourth_.28in_WHERE_clauses.29

This impacts both specific cases like the above, and possibly predicate optimization for index selection, etc.

This issue is a generalization of #12302.

cc @nvanbenschoten

**Comment by nvanbenschoten** [comment]
```
root@:26257/test> SELECT 'ok' WHERE 1 NOT IN (SELECT CAST (NULL AS INTEGER));
+------+
| 'ok' |
+------+
+------+
(0 rows)
```

The example you gave was addressed by https://github.com/cockroachdb/cockroach/pull/13444/commits/747877af46dfa951a14423c4b6d564585fc5d5b4. Is there more we should test with this issue (predicate optimization for index selection?), or can it be closed?

**Comment by knz** [comment]
our predicate optimization is doing the right thing already I think. So let's close this.
Thanks for checking :)
