### ISSUE TITLE
sql: implement "searched CASE"

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#13218]
The SQL standard defines two CASE expressions:

- simple CASE expressions: `CASE i WHEN 1 THEN 'one' WHEN 2 THEN 'two' ELSE 'three' END` - this one we implement already
- "searched CASE": `CASE WHEN i = 1 THEN 'one' WHEN i = 2 THEN 'two' ELSE 'three' END` - this one we don't implement yet

Characteristics:
- The searched CASE expression does not have anything between the first two keywords (`CASE WHEN`). 
- It can be leveraged to check whether the condition is NULL (`WHEN i IS NULL`), whereas a simple CASE cannot do that.

**Comment by petermattis** [comment]
I'm pretty sure we already support "searched case". See [CaseExpr.Eval](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/parser/eval.go#L1888). Also:

```
root@:26257> select case when true then 'hello' else 'world' end;
+--------------------------------+
| CASE WHEN true THEN 'hello' ELSE 'world' END |
+--------------------------------+
| hello                          |
+--------------------------------+
(1 row)
```

**Comment by knz** [comment]
Duh. Somehow I completely missed that `else` part. Sorry for the noise.

**Comment by knz** [comment]
It was just missing in docs: https://github.com/cockroachdb/docs/pull/1036
