### ISSUE TITLE
Sentry: panic.go:770: panic: × (1) attached stack trace   -- stack trace:   | runtime.gopanic   | 	GOROOT/src/runtime/panic.go:770   | github.com/cockroachdb/cockroach/pkg/roachpb.Lease.Type   | 	git...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#132152]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5967608468/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5967608468/?referrer=webhooks_plugin)

Panic Message:

```
panic.go:770: panic: ×
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:770
  | github.com/cockroachdb/cockroach/pkg/roachpb.Lease.Type
  | 	github.com/cockroachdb/cockroach/pkg/roachpb/pkg/roachpb/data.go:1902
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/leases.Status
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/leases/status.go:116
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).leaseStatusForRequestRLocked
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_range_lease.go:701
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).leaseStatusAtRLocked
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_range_lease.go:681
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).tick
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:1305
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processTick
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:715
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftSchedulerShard).worker
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:407
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).Start.func2
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:316
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:485
  | runtime.goexit
  | 	src/runtime/asm_amd64.s:1695
Wraps: (2) panic: ×
Error types: (1) *withstack.withStack (2) *errutil.leafError
-- report composition:
*errutil.leafError: panic: ×
panic.go:770: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_amd64.s#L1694-L1696](src/runtime/asm_amd64.s#L1694-L1696)
[https://github.com/cockroachdb/cockroach/blob/8fb18e7ae08fdd481b959f74330e273a2500e1df/pkg/util/stop/stopper.go#L484-L486](https://github.com/cockroachdb/cockroach/blob/8fb18e7ae08fdd481b959f74330e273a2500e1df/pkg/util/stop/stopper.go#L484-L486)
[https://github.com/cockroachdb/cockroach/blob/8fb18e7ae08fdd481b959f74330e273a2500e1df/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L315-L317](https://github.com/cockroachdb/cockroach/blob/8fb18e7ae08fdd481b959f74330e273a2500e1df/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L315-L317)
[https://github.com/cockroachdb/cockroach/blob/8fb18e7ae08fdd481b959f74330e273a2500e1df/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L406-L408](https://github.com/cockroachdb/cockroach/blob/8fb18e7ae08fdd481b959f74330e273a2500e1df/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L406-L408)
[https://github.com/cockroachdb/cockroach/blob/8fb18e7ae08fdd481b959f74330e273a2500e1df/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L714-L716](https://github.com/cockroachdb/cockroach/blob/8fb18e7ae08fdd481b959f74330e273a2500e1df/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L714-L716)
[https://github.com/cockroachdb/cockroach/blob/8fb18e7ae08fdd481b959f74330e273a2500e1df/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L1304-L1306](https://github.com/cockroachdb/cockroach/blob/8fb18e7ae08fdd481b959f74330e273a2500e1df/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L1304-L1306)
[https://github.com/cockroachdb/cockroach/blob/8fb18e7ae08fdd481b959f74330e273a2500e1df/pkg/kv/kvserver/pkg/kv/kvserver/replica_range_lease.go#L680-L682](https://github.com/cockroachdb/cockroach/blob/8fb18e7ae08fdd481b959f74330e273a2500e1df/pkg/kv/kvserver/pkg/kv/kvserver/replica_range_lease.go#L680-L682)
[https://github.com/cockroachdb/cockroach/blob/8fb18e7ae08fdd481b959f74330e273a2500e1df/pkg/kv/kvserver/pkg/kv/kvserver/replica_range_lease.go#L700-L702](https://github.com/cockroachdb/cockroach/blob/8fb18e7ae08fdd481b959f74330e273a2500e1df/pkg/kv/kvserver/pkg/kv/kvserver/replica_range_lease.go#L700-L702)
[https://github.com/cockroachdb/cockroach/blob/8fb18e7ae08fdd481b959f74330e273a2500e1df/pkg/kv/kvserver/leases/status.go#L115-L117](https://github.com/cockroachdb/cockroach/blob/8fb18e7ae08fdd481b959f74330e273a2500e1df/pkg/kv/kvserver/leases/status.go#L115-L117)
[https://github.com/cockroachdb/cockroach/blob/8fb18e7ae08fdd481b959f74330e273a2500e1df/pkg/roachpb/pkg/roachpb/data.go#L1901-L1903](https://github.com/cockroachdb/cockroach/blob/8fb18e7ae08fdd481b959f74330e273a2500e1df/pkg/roachpb/pkg/roachpb/data.go#L1901-L1903)
[GOROOT/src/runtime/panic.go#L769-L771](GOROOT/src/runtime/panic.go#L769-L771)
</details>

```
src/runtime/asm_amd64.s in runtime.goexit at line 1695
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 485
pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go in pkg/kv/kvserver.(*raftScheduler).Start.func2 at line 316
pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go in pkg/kv/kvserver.(*raftSchedulerShard).worker at line 407
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).processTick at line 715
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).tick at line 1305
pkg/kv/kvserver/pkg/kv/kvserver/replica_range_lease.go in pkg/kv/kvserver.(*Replica).leaseStatusAtRLocked at line 681
pkg/kv/kvserver/pkg/kv/kvserver/replica_range_lease.go in pkg/kv/kvserver.(*Replica).leaseStatusForRequestRLocked at line 701
pkg/kv/kvserver/leases/status.go in pkg/kv/kvserver/leases.Status at line 116
pkg/roachpb/pkg/roachpb/data.go in pkg/roachpb.Lease.Type at line 1902
GOROOT/src/runtime/panic.go in runtime.gopanic at line 770
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v24.2.2 |
| Go Version | go1.22.5 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v24.2.2 |
| Cockroach SHA | 8fb18e7ae08fdd481b959f74330e273a2500e1df |
| # of CPUs | 6 |
| # of Goroutines | 479 |

Jira issue: CRDB-42849

**Comment by yuzefovich** [comment]
unactionable
