### ISSUE TITLE
Kafka v2 changefeed fails to shut down

### ISSUE THREAD

**Issue by asg0451** [cockroachdb/cockroach#132198]
The drt cluster observed changefeeds getting stuck on cancel. Investigation turned up a deadlock on shutdown in the library used by the kafka v2 sink. See conversation in [slack](https://cockroachlabs.slack.com/archives/C05FHJJ0MD0/p1728375970410019) and [the upstream issue](https://github.com/twmb/franz-go/issues/831)

The new sink is available in v23.2.10, v24.1.4, and v24.2.0. It is the default kafka sink in v24.2.0+.

Jira issue: CRDB-42871

**Comment by twmb** [comment]
franz-go v1.18 released
