### ISSUE TITLE
Sentry: replica_proposal.go:347: log.Fatal: lease sequence inversion, prevLease=repl=(n2,s2):2 seq=175 start=1728429875.639489916,0 exp=1728430435.368083987,0 pro=1728430429.368083987,0, newLease=repl...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#132208]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5971730748/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5971730748/?referrer=webhooks_plugin)

Panic Message:

```
replica_proposal.go:347: log.Fatal: lease sequence inversion, prevLease=repl=(n2,s2):2 seq=175 start=1728429875.639489916,0 exp=1728430435.368083987,0 pro=1728430429.368083987,0, newLease=repl=(n4,s4):4 seq=174 start=1728431390.050319558,0 exp=1728432408.729830527,0 pro=1728432402.729830527,0
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).leasePostApplyLocked
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go:347
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).applySnapshot
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raftstorage.go:821
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:986
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processRaftSnapshotRequest.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:489
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).withReplicaForRequest
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:366
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processRaftSnapshotRequest
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:430
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).receiveSnapshot
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_snapshot.go:1470
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).HandleSnapshot.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:213
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:337
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).HandleSnapshot
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:210
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*RaftTransport).RaftSnapshot
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/raft_transport.go:621
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver._MultiRaft_RaftSnapshot_Handler
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/bazel-out/k8-opt/bin/pkg/kv/kvserver/kvserver_go_proto_/github.com/cockroachdb/cockroach/pkg/kv/kvserver/storage_services.pb.go:267
  | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.StreamServerInterceptor.func13
  | 	github.com/cockroachdb/cockroach/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go:165
  | google.golang.org/grpc.getChainStreamHandler.func1
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1481
  | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func4
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:179
  | google.golang.org/grpc.getChainStreamHandler.func1
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1481
  | github.com/cockroachdb/cockroach/pkg/rpc.kvAuth.streamInterceptor
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/auth.go:157
  | google.golang.org/grpc.getChainStreamHandler.func1
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1481
  | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func2.1
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:146
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:337
  | github.com/cockroachdb/cockroach/pkg/rpc.NewServerEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:145
  | google.golang.org/grpc.NewServer.chainStreamServerInterceptors.chainStreamInterceptors.func2
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1472
  | google.golang.org/grpc.(*Server).processStreamingRPC
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1636
  | google.golang.org/grpc.(*Server).handleStream
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:1716
  | google.golang.org/grpc.(*Server).serveStreams.func1.1
  | 	google.golang.org/grpc/external/org_golang_google_grpc/server.go:947
  | runtime.goexit
  | 	src/runtime/asm_amd64.s:1695
Wraps: (2) log.Fatal: lease sequence inversion, prevLease=repl=(n2,s2):2 seq=175 start=1728429875.639489916,0 exp=1728430435.368083987,0 pro=1728430429.368083987,0, newLease=repl=(n4,s4):4 seq=174 start=1728431390.050319558,0 exp=1728432408.729830527,0 pro=1728432402.729830527,0
Error types: (1) *withstack.withStack (2) *errutil.leafError
-- report composition:
*errutil.leafError: log.Fatal: lease sequence inversion, prevLease=repl=(n2,s2):2 seq=175 start=1728429875.639489916,0 exp=1728430435.368083987,0 pro=1728430429.368083987,0, newLease=repl=(n4,s4):4 seq=174 start=1728431390.050319558,0 exp=1728432408.729830527,0 pro=1728432402.729830527,0
replica_proposal.go:347: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_amd64.s#L1694-L1696](src/runtime/asm_amd64.s#L1694-L1696)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L946-L948](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L946-L948)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1715-L1717](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1715-L1717)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1635-L1637](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1635-L1637)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1471-L1473](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1471-L1473)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/rpc/pkg/rpc/context.go#L144-L146](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/rpc/pkg/rpc/context.go#L144-L146)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/util/stop/stopper.go#L336-L338](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/util/stop/stopper.go#L336-L338)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/rpc/pkg/rpc/context.go#L145-L147](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/rpc/pkg/rpc/context.go#L145-L147)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1480-L1482](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1480-L1482)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/rpc/pkg/rpc/auth.go#L156-L158](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/rpc/pkg/rpc/auth.go#L156-L158)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1480-L1482](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1480-L1482)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/rpc/pkg/rpc/context.go#L178-L180](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/rpc/pkg/rpc/context.go#L178-L180)
[google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1480-L1482](google.golang.org/grpc/external/org_golang_google_grpc/server.go#L1480-L1482)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go#L164-L166](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/util/tracing/grpcinterceptor/grpc_interceptor.go#L164-L166)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/kv/kvserver/bazel-out/k8-opt/bin/pkg/kv/kvserver/kvserver_go_proto_/github.com/cockroachdb/cockroach/pkg/kv/kvserver/storage_services.pb.go#L266-L268](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/kv/kvserver/bazel-out/k8-opt/bin/pkg/kv/kvserver/kvserver_go_proto_/github.com/cockroachdb/cockroach/pkg/kv/kvserver/storage_services.pb.go#L266-L268)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/kv/kvserver/pkg/kv/kvserver/raft_transport.go#L620-L622](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/kv/kvserver/pkg/kv/kvserver/raft_transport.go#L620-L622)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L209-L211](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L209-L211)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/util/stop/stopper.go#L336-L338](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/util/stop/stopper.go#L336-L338)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L212-L214](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L212-L214)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/kv/kvserver/pkg/kv/kvserver/store_snapshot.go#L1469-L1471](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/kv/kvserver/pkg/kv/kvserver/store_snapshot.go#L1469-L1471)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L429-L431](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L429-L431)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L365-L367](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L365-L367)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L488-L490](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L488-L490)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L985-L987](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L985-L987)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/kv/kvserver/pkg/kv/kvserver/replica_raftstorage.go#L820-L822](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/kv/kvserver/pkg/kv/kvserver/replica_raftstorage.go#L820-L822)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go#L346-L348](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go#L346-L348)
</details>

```
src/runtime/asm_amd64.s in runtime.goexit at line 1695
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.(*Server).serveStreams.func1.1 at line 947
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.(*Server).handleStream at line 1716
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.(*Server).processStreamingRPC at line 1636
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.NewServer.chainStreamServerInterceptors.chainStreamInterceptors.func2 at line 1472
pkg/rpc/pkg/rpc/context.go in pkg/rpc.NewServerEx.func2 at line 145
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunTaskWithErr at line 337
pkg/rpc/pkg/rpc/context.go in pkg/rpc.NewServerEx.func2.1 at line 146
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.getChainStreamHandler.func1 at line 1481
pkg/rpc/pkg/rpc/auth.go in pkg/rpc.kvAuth.streamInterceptor at line 157
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.getChainStreamHandler.func1 at line 1481
pkg/rpc/pkg/rpc/context.go in pkg/rpc.NewServerEx.func4 at line 179
google.golang.org/grpc/external/org_golang_google_grpc/server.go in google.golang.org/grpc.getChainStreamHandler.func1 at line 1481
pkg/util/tracing/grpcinterceptor/grpc_interceptor.go in pkg/rpc.NewServerEx.StreamServerInterceptor.func13 at line 165
pkg/kv/kvserver/bazel-out/k8-opt/bin/pkg/kv/kvserver/kvserver_go_proto_/github.com/cockroachdb/cockroach/pkg/kv/kvserver/storage_services.pb.go in pkg/kv/kvserver._MultiRaft_RaftSnapshot_Handler at line 267
pkg/kv/kvserver/pkg/kv/kvserver/raft_transport.go in pkg/kv/kvserver.(*RaftTransport).RaftSnapshot at line 621
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).HandleSnapshot at line 210
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunTaskWithErr at line 337
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).HandleSnapshot.func1 at line 213
pkg/kv/kvserver/pkg/kv/kvserver/store_snapshot.go in pkg/kv/kvserver.(*Store).receiveSnapshot at line 1470
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).processRaftSnapshotRequest at line 430
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).withReplicaForRequest at line 366
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).processRaftSnapshotRequest.func1 at line 489
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked at line 986
pkg/kv/kvserver/pkg/kv/kvserver/replica_raftstorage.go in pkg/kv/kvserver.(*Replica).applySnapshot at line 821
pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal.go in pkg/kv/kvserver.(*Replica).leasePostApplyLocked at line 347
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v24.2.3 |
| Go Version | go1.22.5 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v24.2.3 |
| Cockroach SHA | 217b43e69da61e9712d73e3e19fd5076fbdb26df |
| # of CPUs | 4 |
| # of Goroutines | 327 |

Jira issue: CRDB-42877

**Comment by yuzefovich** [comment]
unactionable
