### ISSUE TITLE
sql/delegate refactor show * with comment code and remove potentially unsafe usage of system.comments

### ISSUE THREAD

**Issue by Dedej-Bergin** [cockroachdb/cockroach#132201]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

We originally thought this was a bug, but now we see it works fine and this item is still needed to track a refactoring/best practice improvement.

There is some duplicate code we can remove and also system.comments which is currently being used is a low level internal table so it's possible that we will change it in the future and that would give these show comments commands problems in the future.

Jira issue: CRDB-42872

**Comment by sambhav-jain-16** [comment]
@Dedej-Bergin 
So I checked for above.
for `show databases`, we might have to `crdb_internal.kv_catalog_comments` since the database comments are not present in `pg_description` table

```
demo@127.0.0.1:26257/demoapp/movr> create database sajain;                     
CREATE DATABASE

Time: 7ms total (execution 7ms / network 0ms)

demo@127.0.0.1:26257/demoapp/movr> comment on database sajain is 'hello';      
COMMENT ON DATABASE

Time: 7ms total (execution 7ms / network 1ms)

demo@127.0.0.1:26257/demoapp/movr> select * from pg_catalog.pg_description     
                                -> where description like 'hello';             
  objoid | classoid | objsubid | description
---------+----------+----------+--------------
(0 rows)

Time: 9ms total (execution 9ms / network 0ms)

demo@127.0.0.1:26257/demoapp/movr> select * from pg_catalog.pg_description     
                                -> where classoid = 4294967081;                
  objoid | classoid | objsubid | description
---------+----------+----------+--------------
(0 rows)

Time: 1ms total (execution 1ms / network 0ms)

demo@127.0.0.1:26257/demoapp/movr> select * from                               
                                -> crdb_internal.kv_catalog_comments where     
                                -> classoid = 4294967081;                      
   classoid  | objoid | objsubid | description
-------------+--------+----------+--------------
  4294967081 |    113 |        0 | hello
(1 row)

Time: 13ms total (execution 12ms / network 1ms)

```

I think it should be fine since we fetch the database name also from `crdb_internal.databases` https://github.com/cockroachdb/cockroach/blob/58c475d67e32b75284b4fe293bff82807c3d129d/pkg/sql/delegate/show_databases.go#L20-L30
Let me know if the above approach sounds good to you


for `show schemas` we can use `pg_description`

**Comment by Dedej-Bergin** [comment]
Thanks for picking this up @sambhav-jain-16 ! Yes the above approach sounds good.

**Comment by Dedej-Bergin** [comment]
This is the original description we used to have, after @sambhav-jain-16 looked into it we found that this is not currently a bug.

//Previous outdated description
Describe the problem

Please describe the issue you observed, and any steps we can take to reproduce it:

Show schemas with comment and show databases with comment rely on system.comments table. This table is only accessible with users that have specific permissions. We could fix both of these with some similar to what was done in show types with comment in this PR (https://github.com/cockroachdb/cockroach/pull/131183) where we used pg_catalog.pg_description instead of system.comments.

To Reproduce

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

// create a comment on schema or database with a command like this: comment on schema is 'test-comment';
// Create a user that is not admin and switch to that user
// Run the show schemas with comment or the show databases with comment to hit the permissions error produced by system.comments

Expected behavior
Comments should be displayed even if a user is not admin like in show types with comment.

Jira issue: [CRDB-42872](https://cockroachlabs.atlassian.net/browse/CRDB-42872)
