### ISSUE TITLE
Sentry: replica_closedts.go:263: log.Fatal: side-transport update saw closed timestamp regression on r21: (lai=662, ts=1728574572.439870677,0) -> (lai=2468, ts=1728574572.308396880,0) (1) attached sta...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#132322]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5979074847/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5979074847/?referrer=webhooks_plugin)

Panic Message:

```
replica_closedts.go:263: log.Fatal: side-transport update saw closed timestamp regression on r21: (lai=662, ts=1728574572.439870677,0) -> (lai=2468, ts=1728574572.308396880,0)
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*sidetransportAccess).assertNoRegression
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_closedts.go:263
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*sidetransportAccess).forward
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_closedts.go:237
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).ForwardSideTransportClosedTimestamp
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_closedts.go:138
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Stores).ForwardSideTransportClosedTimestampForRange.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/stores.go:132
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Stores).VisitStores.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/stores.go:149
  | github.com/cockroachdb/cockroach/pkg/util/syncutil.(*Map[...]).Range
  | 	github.com/cockroachdb/cockroach/pkg/util/syncutil/map.go:383
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Stores).VisitStores
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/stores.go:148
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Stores).ForwardSideTransportClosedTimestampForRange
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/stores.go:129
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/closedts/sidetransport.(*incomingStream).processUpdate
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/closedts/sidetransport/receiver.go:254
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/closedts/sidetransport.(*incomingStream).Run.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/closedts/sidetransport/receiver.go:332
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:485
  | runtime.goexit
  | 	src/runtime/asm_amd64.s:1695
Wraps: (2) log.Fatal: side-transport update saw closed timestamp regression on r21: (lai=662, ts=1728574572.439870677,0) -> (lai=2468, ts=1728574572.308396880,0)
Error types: (1) *withstack.withStack (2) *errutil.leafError
-- report composition:
*errutil.leafError: log.Fatal: side-transport update saw closed timestamp regression on r21: (lai=662, ts=1728574572.439870677,0) -> (lai=2468, ts=1728574572.308396880,0)
replica_closedts.go:263: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_amd64.s#L1694-L1696](src/runtime/asm_amd64.s#L1694-L1696)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/util/stop/stopper.go#L484-L486](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/util/stop/stopper.go#L484-L486)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/kv/kvserver/closedts/sidetransport/receiver.go#L331-L333](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/kv/kvserver/closedts/sidetransport/receiver.go#L331-L333)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/kv/kvserver/closedts/sidetransport/receiver.go#L253-L255](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/kv/kvserver/closedts/sidetransport/receiver.go#L253-L255)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/kv/kvserver/pkg/kv/kvserver/stores.go#L128-L130](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/kv/kvserver/pkg/kv/kvserver/stores.go#L128-L130)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/kv/kvserver/pkg/kv/kvserver/stores.go#L147-L149](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/kv/kvserver/pkg/kv/kvserver/stores.go#L147-L149)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/util/syncutil/map.go#L382-L384](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/util/syncutil/map.go#L382-L384)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/kv/kvserver/pkg/kv/kvserver/stores.go#L148-L150](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/kv/kvserver/pkg/kv/kvserver/stores.go#L148-L150)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/kv/kvserver/pkg/kv/kvserver/stores.go#L131-L133](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/kv/kvserver/pkg/kv/kvserver/stores.go#L131-L133)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/kv/kvserver/pkg/kv/kvserver/replica_closedts.go#L137-L139](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/kv/kvserver/pkg/kv/kvserver/replica_closedts.go#L137-L139)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/kv/kvserver/pkg/kv/kvserver/replica_closedts.go#L236-L238](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/kv/kvserver/pkg/kv/kvserver/replica_closedts.go#L236-L238)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/kv/kvserver/pkg/kv/kvserver/replica_closedts.go#L262-L264](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/kv/kvserver/pkg/kv/kvserver/replica_closedts.go#L262-L264)
</details>

```
src/runtime/asm_amd64.s in runtime.goexit at line 1695
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 485
pkg/kv/kvserver/closedts/sidetransport/receiver.go in pkg/kv/kvserver/closedts/sidetransport.(*incomingStream).Run.func1 at line 332
pkg/kv/kvserver/closedts/sidetransport/receiver.go in pkg/kv/kvserver/closedts/sidetransport.(*incomingStream).processUpdate at line 254
pkg/kv/kvserver/pkg/kv/kvserver/stores.go in pkg/kv/kvserver.(*Stores).ForwardSideTransportClosedTimestampForRange at line 129
pkg/kv/kvserver/pkg/kv/kvserver/stores.go in pkg/kv/kvserver.(*Stores).VisitStores at line 148
pkg/util/syncutil/map.go in pkg/util/syncutil.(*Map[...]).Range at line 383
pkg/kv/kvserver/pkg/kv/kvserver/stores.go in pkg/kv/kvserver.(*Stores).VisitStores.func1 at line 149
pkg/kv/kvserver/pkg/kv/kvserver/stores.go in pkg/kv/kvserver.(*Stores).ForwardSideTransportClosedTimestampForRange.func1 at line 132
pkg/kv/kvserver/pkg/kv/kvserver/replica_closedts.go in pkg/kv/kvserver.(*Replica).ForwardSideTransportClosedTimestamp at line 138
pkg/kv/kvserver/pkg/kv/kvserver/replica_closedts.go in pkg/kv/kvserver.(*sidetransportAccess).forward at line 237
pkg/kv/kvserver/pkg/kv/kvserver/replica_closedts.go in pkg/kv/kvserver.(*sidetransportAccess).assertNoRegression at line 263
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v24.2.0 |
| Go Version | go1.22.5 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v24.2.0 |
| Cockroach SHA | 953d09cce5a01cc0053e138516d80a27454f027c |
| # of CPUs | 2 |
| # of Goroutines | 398 |

Jira issue: CRDB-42974

**Comment by yuzefovich** [comment]
unactionable
