### ISSUE TITLE
ui: Complete single-node page

### ISSUE THREAD

**Issue by mrtracy** [cockroachdb/cockroach#13230]
The current Admin UI design includes a "single node" page which is accessible by clicking on a specific node from the nodes list page.  While the single node page already exists, it has not been updated to match the current design; both the content and the appearance need to be updated.

**Comment by dianasaur323** [comment]
I think perhaps not a 1.0 fix - there are a couple outstanding bugs that I think take precedence to this. Moving milestones.

**Comment by mrtracy** [comment]
If this is out of 1.0, do we want to remove the *link* to the incomplete page from the UI for 1.0?  It's current appearance is quite gnarly.

**Comment by a-robinson** [comment]
Yeah, removing it seems best to me.

**Comment by dianasaur323** [comment]
Based on our discussion yesterday, it seems like we'll keep the link and leave it gnarly, unless we have some free time to clean it up. Regardless, I think we don't have to focus on this for the 1.0.
