### ISSUE TITLE
backupccl/backup_processor.go redacted message 

### ISSUE THREAD

**Issue by massimocGH** [cockroachdb/cockroach#132448]
this redacted message is preventing our ability to investigate which are the backup localities that have no matching region:

I241008 03:03:10.878631 2262307021 ccl/backupccl/backup_processor.go:298 ⋮ [distsql.gateway=‹×›,f‹×›,job=1010191566538702872,n1] 12783181 backing up 2716 spans to default locality because backup localities [‹×› ‹×› ‹×›] have no match in node's localities [‹×› ‹×› ‹×› ‹×› ‹×›]

Jira issue: CRDB-43073

**Comment by benbardin** [comment]
This is unfortunately working as intended. Some customers consider the names of their regions to be protected information, so we are unable to share them in a redacted debug.zip.
