### ISSUE TITLE
rac2: add RangeController tests that exercise entries not subject to admission control

### ISSUE THREAD

**Issue by sumeerbhola** [cockroachdb/cockroach#132467]
https://github.com/cockroachdb/cockroach/blob/34316ac410931104b46f77e1c3f6e7decb17c2da/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller_test.go#L752

Epic [CRDB-37515](https://cockroachlabs.atlassian.net/browse/CRDB-37515)

Jira issue: CRDB-43076

Epic CRDB-37515

**Comment by kvoli** [comment]
Should this be a GA blocker @sumeerbhola -- I've moved it to P1-testing from P2-GA accordingly, but want to double check the blocker label was intentional.

**Comment by sumeerbhola** [comment]
This was fixed by https://github.com/cockroachdb/cockroach/pull/132838. Closing it.
