### ISSUE TITLE
Sentry: crash_reporting.go:390: index-join-1-unlimited-1: no bytes in account to release, current 1096, free 1125
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/ut...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#132422]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5983634534/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5983634534/?referrer=webhooks_plugin)

Panic Message:

```
crash_reporting.go:390: index-join-1-unlimited-1: no bytes in account to release, current 1096, free 1125
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/util/log/logcrash.ReportOrPanic
  | 	github.com/cockroachdb/cockroach/pkg/util/log/logcrash/crash_reporting.go:390
  | github.com/cockroachdb/cockroach/pkg/util/mon.(*BoundAccount).Shrink
  | 	github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:915
  | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvstreamer.(*budget).releaseLocked
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvstreamer/budget.go:119
  | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvstreamer.(*budget).release
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvstreamer/budget.go:112
  | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvstreamer.(*workerCoordinator).performRequestAsync.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvstreamer/streamer.go:1402
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (2) index-join-1-unlimited-1: no bytes in account to release, current 1096, free 1125
Error types: (1) *withstack.withStack (2) *errutil.leafError
-- report composition:
*errutil.leafError: index-join-1-unlimited-1: no bytes in account to release, current 1096, free 1125
crash_reporting.go:390: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/b95f2225b09cf25f9f2be31ef6a6f65c73a1b081/pkg/util/stop/stopper.go#L469-L471](https://github.com/cockroachdb/cockroach/blob/b95f2225b09cf25f9f2be31ef6a6f65c73a1b081/pkg/util/stop/stopper.go#L469-L471)
[https://github.com/cockroachdb/cockroach/blob/b95f2225b09cf25f9f2be31ef6a6f65c73a1b081/pkg/kv/kvclient/kvstreamer/streamer.go#L1401-L1403](https://github.com/cockroachdb/cockroach/blob/b95f2225b09cf25f9f2be31ef6a6f65c73a1b081/pkg/kv/kvclient/kvstreamer/streamer.go#L1401-L1403)
[https://github.com/cockroachdb/cockroach/blob/b95f2225b09cf25f9f2be31ef6a6f65c73a1b081/pkg/kv/kvclient/kvstreamer/budget.go#L111-L113](https://github.com/cockroachdb/cockroach/blob/b95f2225b09cf25f9f2be31ef6a6f65c73a1b081/pkg/kv/kvclient/kvstreamer/budget.go#L111-L113)
[https://github.com/cockroachdb/cockroach/blob/b95f2225b09cf25f9f2be31ef6a6f65c73a1b081/pkg/kv/kvclient/kvstreamer/budget.go#L118-L120](https://github.com/cockroachdb/cockroach/blob/b95f2225b09cf25f9f2be31ef6a6f65c73a1b081/pkg/kv/kvclient/kvstreamer/budget.go#L118-L120)
[https://github.com/cockroachdb/cockroach/blob/b95f2225b09cf25f9f2be31ef6a6f65c73a1b081/pkg/util/mon/bytes_usage.go#L914-L916](https://github.com/cockroachdb/cockroach/blob/b95f2225b09cf25f9f2be31ef6a6f65c73a1b081/pkg/util/mon/bytes_usage.go#L914-L916)
[https://github.com/cockroachdb/cockroach/blob/b95f2225b09cf25f9f2be31ef6a6f65c73a1b081/pkg/util/log/logcrash/crash_reporting.go#L389-L391](https://github.com/cockroachdb/cockroach/blob/b95f2225b09cf25f9f2be31ef6a6f65c73a1b081/pkg/util/log/logcrash/crash_reporting.go#L389-L391)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 470
pkg/kv/kvclient/kvstreamer/streamer.go in pkg/kv/kvclient/kvstreamer.(*workerCoordinator).performRequestAsync.func1 at line 1402
pkg/kv/kvclient/kvstreamer/budget.go in pkg/kv/kvclient/kvstreamer.(*budget).release at line 112
pkg/kv/kvclient/kvstreamer/budget.go in pkg/kv/kvclient/kvstreamer.(*budget).releaseLocked at line 119
pkg/util/mon/bytes_usage.go in pkg/util/mon.(*BoundAccount).Shrink at line 915
pkg/util/log/logcrash/crash_reporting.go in pkg/util/log/logcrash.ReportOrPanic at line 390
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v23.1.14 |
| Go Version | go1.19.13 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.14 |
| Cockroach SHA | b95f2225b09cf25f9f2be31ef6a6f65c73a1b081 |
| # of CPUs | 32 |
| # of Goroutines | 1530 |

Jira issue: CRDB-43052

**Comment by yuzefovich** [comment]
unactionable
