### ISSUE TITLE
what docs?

### ISSUE THREAD

**Issue by paigeadelethompson** [cockroachdb/cockroach#132529]
ERROR: connect to external storage: unsupported storage scheme: "" - refer to docs to find supported storage schemes

- storage schemes

Jira issue: CRDB-43118

**Comment by DarrylWong** [comment]
Hi! The following doc listing the supported cloud storages may be helpful: https://www.cockroachlabs.com/docs/stable/use-cloud-storage

Just fyi, questions like these are better suited for the community slack or forum, you will probably have faster responses there.

Sending to disaster recovery in case they find the following TODO is still relevant:  

https://github.com/cockroachdb/cockroach/blob/c68c559859be738efead9971f5e11f62a8c69d06/pkg/cloud/impl_registry.go#L197-L198

**Comment by alicia-l2** [comment]
Closing this issue, feel free to re-open/add further comments if you need any additional help.
