### ISSUE TITLE
*: crash under Linux/ARM64 related to timers: "too many concurrent timer firings"

### ISSUE THREAD

**Issue by rickystewart** [cockroachdb/cockroach#132596]
This seems to only ever occur on ARM. The timing of the new failures correlates with the recent Go 1.23 upgrade.

#132573
#132578
#132579

Jira issue: CRDB-43172

**Comment by dt** [comment]
I've bumped this to release-blocker since we've seen it outside unit tests and in roachtests as well now: #132525

**Comment by stevendanna** [comment]
Another possibility: https://github.com/golang/go/issues/69880
