### ISSUE TITLE
storage: excessive disk usage combined with inaccurate storage.capacity.used metric

### ISSUE THREAD

**Issue by sambhav-jain-16** [cockroachdb/cockroach#132668]
**Describe the problem**

`drt-chaos` cluster went down due to disk being full. Ideally the storage shouldn't be filled up since garbage collection was triggered. Also, `storage.capacity.used` value was not increasing however `storage.capacity.available` kept on decreasing as the workload progressed.
This also resulted in pebble not removing the SSTables which were marked to be deleted.

Screenshot from datadog
<img width="960" alt="Screenshot 2024-10-14 at 5 54 47 PM" src="https://github.com/user-attachments/assets/7ac5da98-1f3d-457f-86e9-bc267558bbec">

Screenshot from console
![Screenshot 2024-10-14 at 6 00 54 PM](https://github.com/user-attachments/assets/aa6b3372-3176-417f-8a79-6703835a7bee)

**Expected behavior**
`storage.capacity.used` should increase if `storage.capacity.available` is decreasing and storage layer should clear the extra SSTabled when marked to be deleted.

Jira issue: CRDB-43217

**Comment by itsbilal** [comment]
I'm looking into this and so far it seems like Pebble's tracking of total bytes in sstables is pretty far off from the actual bytes taken up by sstables on disk. I'm actually not 100% sure where the discrepancy is coming from, but something seems really off

**Comment by itsbilal** [comment]
Looks like there's one case of compaction cancellation where we don't delete compaction outputs:

https://github.com/cockroachdb/pebble/blob/248af3efa7271926fb7f7b048f4e14aef579f65a/compaction.go#L2206

**Comment by jbowens** [comment]
Were there very many cancelled compactions and do we understand why? I think if we don't already have a metric counting cancelled compactions and maybe bytes written by cancelled compactions, we should add them. Too many cancelled compactions increase w-amp.

**Comment by itsbilal** [comment]
@jbowens The cluster happened to have a lot of tombstone density compactions as well as lots of compactions in general (see #4052, still being investigated). That and it was seeing heavy inbound rebalances due to 2 dead nodes, and those ingests/excises were conflicting with those compactions, resulting in a decent amount of cancelled compaction outputs being generated over the course of a couple days.

We should add a metric for cancelled compactions though.

**Comment by itsbilal** [comment]
Also I'm not sure if this is a GA-blocker seeing as it would happen on past releases (23.2, 24.1, 24.2) too. However #4052 definitely seems like it's a new bug.

**Comment by jbowens** [comment]
I'm confident we should treat this as a GA blocker given the severe impact.

**Comment by itsbilal** [comment]
Interestingly enough, this bug is not present on 24.1 because `runCompaction` doesn't do any SSTable cleanup and we let `compact1` do it all. Which is to say this bug crept in with the compaction runner refactor in 24.2.
