### ISSUE TITLE
v24.3.0-alpha.2: `cockroach demo` output still mentions disabling telemetry

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/cockroach#132688]
In v24.3 one will no longer be able to disable telemetry.  However the "welcome screen" output of `cockroach demo` is still talking about `COCKROACH_SKIP_ENABLING_DIAGNOSTIC_REPORTING`, which is now (AIUI) incorrect.

```
$ cockroach version
Build Tag:        v24.3.0-alpha.2
Build Time:       2024/10/14 18:12:53
Distribution:     CCL
Platform:         darwin amd64 (x86_64-apple-darwin19)
Go Version:       go1.22.5 X:nocoverageredesign
C Compiler:       Clang 10.0.0 
Build Commit ID:  45b47f90445fdb0e0c8e07df863c3bbe17daa491
Build Type:       release
Enabled Assertions: false
$ cockroach demo --insecure 
#
# Welcome to the CockroachDB demo database!
#
# You are connected to a temporary, in-memory CockroachDB cluster of 1 node.
#
# You are connected to tenant "demoapp", but can connect to the system tenant with
# '\connect' and the SQL url printed via '\demo ls'.
#
# This demo session will send telemetry to Cockroach Labs in the background.
# To disable this behavior, set the environment variable
# COCKROACH_SKIP_ENABLING_DIAGNOSTIC_REPORTING=true.
```

**Expected behavior**

Expected behavior would probably be just the removal of these two lines:

```
# To disable this behavior, set the environment variable
# COCKROACH_SKIP_ENABLING_DIAGNOSTIC_REPORTING=true.
```

PS. I did [this search](https://github.com/cockroachdb/cockroach/issues?q=is%3Aissue+%22cockroach+demo%22+telemetry+is%3Aclosed+sort%3Aupdated-desc) and [this one](https://github.com/cockroachdb/cockroach/pulls?q=is%3Apr+COCKROACH_SKIP_ENABLING_DIAGNOSTIC_REPORTING+is%3Aclosed+sort%3Aupdated-desc) but didn't find any issues for this

Jira issue: CRDB-43226

**Comment by angles-n-daemons** [comment]
After exploring this internally, it seems as if we want to continue supporting the variable to allow clusters to disable telemetry if desired, but all copy referring to it will be removed.

If the user desires to disable telemetry, they will receive notification throttling in advance of being throttled via the db-console ui.
