### ISSUE TITLE
kv: test leader leases

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#132762]
Part of https://github.com/cockroachdb/cockroach/issues/123847.

Now that we support leader leases, we should throw the full test suite at them. Specifically, we should use leader leases in:
- [x] unit tests: https://github.com/cockroachdb/cockroach/pull/131623
- [x] `failover` tests: https://github.com/cockroachdb/cockroach/pull/131624
- [x] roachtests: https://github.com/cockroachdb/cockroach/pull/133217

Jira issue: CRDB-43269

Epic CRDB-37522

**Comment by arulajmani** [comment]
The unit tests were addressed as part of https://github.com/cockroachdb/cockroach/issues/133763. We now have them running metamorphically on master.
