### ISSUE TITLE
util/log: add and an extra argument to TestLogScope.Close() to capture panics

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#13285]
Right now TestLogScope.Close checks whether the current test is failing using testing.T's `Failed()` method, and (as per #13219) a separate call to `calledDuringPanic()`. 

Suggestion by @andreimatei on https://github.com/cockroachdb/cockroach/pull/13219#issuecomment-276143162:

>  can't we pipe calledDuringPanic as an argument to Close()? To get rid of magic.

(In other words: move the call to calledDuringPanic to each of the callers of TestLogScope.Close() )

**Comment by andreimatei** [comment]
talked to @knz offline. My suggestion was to use `recover` but that's too much burden on the callers of TestLogScope.
