### ISSUE TITLE
Program exits after transaction exception

### ISSUE THREAD

**Issue by DeleteLin** [cockroachdb/cockroach#132996]
SET CLUSTER SETTING sql.txn.read_committed_isolation.enabled = 'true';
SET default_transaction_isolation = 'read committed';
start transaction;
CREATE TABLE test (
	id int NOT NULL,
	PRIMARY KEY (id)
);
select * from test;

-- rollback   RROR: current transaction is aborted, commands ignored until end of transaction block

commit;
-- exit code 130

* ERROR: a SQL panic has occurred while executing the following statement:
* COMMIT TRANSACTION
*
*
* ERROR: a panic has occurred!
* runtime error: invalid memory address or nil pointer dereference
* (1) attached stack trace
*   -- stack trace:
*   | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
*   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:967
*   | [...repeated from below...]
* Wraps: (2) while executing: COMMIT TRANSACTION
* Wraps: (3) attached stack trace
*   -- stack trace:
*   | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
*   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:967
*   | runtime.gopanic
*   | 	GOROOT/src/runtime/panic.go:914
*   | runtime.panicmem
*   | 	GOROOT/src/runtime/panic.go:261
*   | runtime.sigpanic
*   | 	GOROOT/src/runtime/signal_unix.go:861
*   | github.com/cockroachdb/cockroach/pkg/util/tracing.SpanFromContext
*   | 	github.com/cockroachdb/cockroach/pkg/util/tracing/context.go:25
*   | github.com/cockroachdb/cockroach/pkg/util/log.getSpanOrEventLog
*   | 	github.com/cockroachdb/cockroach/pkg/util/log/trace.go:91
*   | github.com/cockroachdb/cockroach/pkg/util/log.vEventf
*   | 	github.com/cockroachdb/cockroach/pkg/util/log/trace.go:212
*   | github.com/cockroachdb/cockroach/pkg/util/log.VEventf
*   | 	github.com/cockroachdb/cockroach/pkg/util/log/trace.go:238
*   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*leasedDescriptors).releaseAll
*   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/leased_descriptors.go:257
*   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).ReleaseLeases
*   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:192
*   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).ReleaseAll
*   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:200
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).resetExtraTxnState
*   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2022
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).txnStateTransitionsApplyWrapper
*   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:3964
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
*   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2511
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
*   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2185
*   | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
*   | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:969
*   | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommands
*   | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:250
*   | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).serveImpl.func3
*   | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:1104
*   | runtime.goexit
*   | 	src/runtime/asm_amd64.s:1650
* Wraps: (4) runtime error: invalid memory address or nil pointer dereference
* Error types: (1) *withstack.withStack (2) *safedetails.withSafeDetails (3) *withstack.withStack (4) runtime.errorString
*
*
* ERROR: Queued as error f6385c242186457381b3050013399e9f
*
*
* ERROR: Timeout trying to submit crash report
*
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xc2f058]

goroutine 7305 [running]:
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc00440cc80, {0x7aa7868, 0xc0068dc150}, {0x59d5e20?, 0xb4bd3c0?})
	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1222 +0x19d
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1({0x7aa7868, 0xc0068dc150}, {0xcaac0fe4?})
	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:967 +0x45
panic({0x59d5e20?, 0xb4bd3c0?})
	GOROOT/src/runtime/panic.go:914 +0x21f
github.com/cockroachdb/cockroach/pkg/util/tracing.SpanFromContext({0x0?, 0x0?})
	github.com/cockroachdb/cockroach/pkg/util/tracing/context.go:25 +0x18
github.com/cockroachdb/cockroach/pkg/util/log.getSpanOrEventLog({0x0, 0x0})
	github.com/cockroachdb/cockroach/pkg/util/log/trace.go:91 +0x25
github.com/cockroachdb/cockroach/pkg/util/log.vEventf({0x0, 0x0}, 0x0, 0x1, 0x72cd26?, 0x0?, {0x6406a6d, 0x18}, {0xc005b18e50, 0x1, ...})
	github.com/cockroachdb/cockroach/pkg/util/log/trace.go:212 +0x107
github.com/cockroachdb/cockroach/pkg/util/log.VEventf(...)
	github.com/cockroachdb/cockroach/pkg/util/log/trace.go:238
github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*leasedDescriptors).releaseAll(0xc0045d1208, {0x0?, 0x0})
	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/leased_descriptors.go:257 +0xd6
github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).ReleaseLeases(...)
	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:192
github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).ReleaseAll(0xc0045d11e0, {0x0, 0x0})
	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:200 +0x30
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).resetExtraTxnState(0xc00440cc80, {0x0, 0x0}, {0x3, {0xbc, 0x1, 0x28, 0x2a, 0x42, 0x73, ...}, ...}, ...)
	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2022 +0x128
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).txnStateTransitionsApplyWrapper(0xc00440cc80, {0x7a5fba0?, 0xc007b78aa0?}, {0x5bc79c0, 0xc007b78ab0}, {0x7f29b5ff6860?, 0xc005883740}, 0xc1bd07c3ca08ea73?)
	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:3964 +0xa2b
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd(0xc00440cc80)
	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2511 +0x1778
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc00440cc80, {0x7aa7868, 0xc0068dc150}, 0xc009b1fcc0?, 0xe2bbf1?, 0xc007983df0?)
	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2185 +0x208
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc003bbe000?, {0x7aa7868?, 0xc0068dc150?}, {0xc0074b8009?}, 0x4?, 0xc0067c7f80?)
	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:969 +0xda
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommands(0xc005883000, {0x7aa7868?, 0xc0068dc150}, {0x0, 0x4, {0x1, {0x6384e47, 0x3}, {0xc0099158d0, 0xf}, ...}, ...}, ...)
	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:250 +0x3fb
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).serveImpl.func3()
	github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:1104 +0xec
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).serveImpl in goroutine 7314
	github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:1101 +0x572

Jira issue: CRDB-43394

**Comment by DeleteLin** [comment]
cockroach demo

select version();
CockroachDB CCL v23.2.12 (x86_64-pc-linux-gnu, built 2024/09/23 22:32:15, go1.21.12 X:nocoverageredesign)

uname -a
Linux xiaoxiao-KuangshiG16-Series-GM6PG0Q 6.8.0-47-generic #47-Ubuntu SMP PREEMPT_DYNAMIC Fri Sep 27 21:40:26 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by yuzefovich** [comment]
Thanks for the report! We've seen similar crashes in sentry, but unfortunately the provided reproduction doesn't trigger the problem for me locally, so I'll close this issue as unactionable. If you stumble onto another more reliable repro of the problem, please file a new issue and feel free to tag me directly, thanks!
