### ISSUE TITLE
log: fix documentation of buffered writes error

### ISSUE THREAD

**Issue by dhartunian** [cockroachdb/cockroach#133098]
**Describe the problem**

The error returned when `auditable: true` and `buffering:` is enabled in https://github.com/cockroachdb/cockroach/pull/132742 is incorrect. It references the `buffered-writes` option which is different from `buffering`.

https://github.com/cockroachdb/cockroach/blob/56c0f1e14d0720b93ff7cfc1f571799d298544c8/pkg/util/log/logconfig/validate.go#L370-L378

Expected: "File-based audit logging cannot coexist with buffering configuration. Disable either the buffering configuration ("buffering") or auditable log ("auditable") configuration."

Additionally, we should add a nil check for the `Auditable` pointer to match `fc.BufferedWrites` above.

Jira issue: CRDB-43462

**Comment by aa-joshi** [comment]
This is addressed as part of #132899. Changes are picked as part of 24.3 release. I am closing the issue as it is already fixed.
