### ISSUE TITLE
license: reduce overhead of `MaybeFailIfThrottled` (0.4% cpu)

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#133088]
In a recent CPU profile captured while running the sysbench oltp_read_write workload, `license.(*Enforcer).MaybeFailIfThrottled` accounted for 1.34% of CPU samples. 

<img width="925" alt="image" src="https://github.com/user-attachments/assets/59ccc322-9e0e-42d6-926c-16ff38d2928d">

There are two lines that stand out prominently in this profile:

### 1. A line calling `license.(*Enforcer).getMaxOpenTransactions`

<img width="937" alt="image" src="https://github.com/user-attachments/assets/b49fdd4b-c5c5-4eb0-85a8-7d33166a2990">

I have a few open questions that may lead to some improvements here:

1. Is the `COCKROACH_MAX_OPEN_TXNS_DURING_THROTTLE` env var necessary? Why would we allow the customer to configure the throttling limit?
2. The most expensive part of `getMaxOpenTransactions` is the eventual call to `envutil.getAndCacheEnv` which invokes the costly `runtime.Caller` function. The information returned from `runtime.Caller` is used to ensure that each env variable is only set in one file:
   - There is no need to pay the expensive price of `runtime.Caller` every time the env var is accessed for information that is static. `envutil` could provide an function that returns a file key and users of this API could generate a key once in `init` functions and pass them to other `envutil` functions, rather than having each `envutil` function call `runtime.Caller` themselves.
   - The file name returned by `runtime.Caller` is only used to panic if there is more than one file where an env var is used. This doesn't seem like desirable behavior in a production build. Should we only perform this check in test builds by using `buildutil.CrdbTestBuild`? If so, then we only need to call `runtime.Caller` in test builds.

### 2. A line creating a NOTICE

<img width="1443" alt="image" src="https://github.com/user-attachments/assets/dc894792-cae9-4350-8cef-d912ecfc9093">

I have a few open questions that may lead to some improvements here:

1. In what cases is this code path hit? We had a license installed, but we were still hitting the code path stating "No license is installed..." Is it possible that the internal executor, or some other internal process, is hitting this error, even with a license installed?
2. Is it necessary for NOTICEs to have stack traces? That's the most expensive part of building this error: collecting the stack trace. I'm also not sure why NOTICEs use errors, is there a good reason for that? If they must use errors, can they use a simpler form of error without a stack trace?
3. Redaction of the error message is also expensive. Does wrapping `gracePeriodEnd` in `redact.Safe(_)` make it cheaper?

## Priority

I'm assigning the P-2 label because I believe there's potential for a fairly significant improvement to be made here (~1%) without a huge effort. Note that there is some chance that the NOTICE (2) code path was being hit due to some misconfiguration of the license that is unlikely to happen in real-world workloads, which would reduce the potential gains here.

Jira issue: CRDB-43621

**Comment by tbg** [comment]
For another data point, with a valid license I'm still seeing 0.4% of cpu here on `tobias-sbrw`:

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/98f7a735-45ec-43a6-82fd-2c3b709cf208">
