### ISSUE TITLE
sql: wrong name resolution order

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#13313]
Currently if a database has a physical table named after one of pg_catalog's tables, say for example `create table pg_types (...)` and a query does `select * from pg_types`, we  (CockroachDB) look it up in `pg_catalog`  whereas pg would pick the physical table.

This is because we look through the search path before the "current database" (as set by `set database =`). 

This probably should be inverted at least, and perhaps `set database` could populate the search_path instead.

@nvanbenschoten thoughts?

**Comment by nvanbenschoten** [comment]
Interesting, I thought we made a specific effort to resolve unqualified names with the same precedence order as Postgres. Regardless, inverting the order that we look at the current database and search_path should fix this.

**Comment by knz** [comment]
Yes I wrote that code and chances are I just made a mistake there.
