### ISSUE TITLE
sql: hold for SQL queries GA blockers

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#133264]
SQL Queries has a number of PRs to merge and backport to 24.3. This issue serves as a GA-blocking issue for all that work. We'll close it once the backports are complete.

- [x] https://github.com/cockroachdb/cockroach/pull/133171
- [x] https://github.com/cockroachdb/cockroach/pull/133281
- [x] https://github.com/cockroachdb/cockroach/pull/133073
- [x] https://github.com/cockroachdb/cockroach/pull/134002
- [x] https://github.com/cockroachdb/cockroach/pull/133220 and its backport
- [x] https://github.com/cockroachdb/cockroach/pull/133320
- [x] https://github.com/cockroachdb/cockroach/pull/133512
- [x] https://github.com/cockroachdb/cockroach/pull/133328 and its backport
- [x] https://github.com/cockroachdb/cockroach/pull/134223
- [x] https://github.com/cockroachdb/cockroach/pull/134609

Jira issue: CRDB-43526

**Comment by DrewKimball** [comment]
All blockers are closed.
