### ISSUE TITLE
kv: `failover/liveness/pause` and `failover/liveness/blackhole` regression

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#133259]
We appear to have caused a regression between Aug 3rd and Aug 10th on some of the `failover/liveness` tests with epoch-based leases.

<img width="882" alt="Screenshot 2024-10-23 at 11 42 33 AM" src="https://github.com/user-attachments/assets/f6544fbd-e918-4549-8c7b-147112e2166f">
<img width="873" alt="Screenshot 2024-10-23 at 11 42 47 AM" src="https://github.com/user-attachments/assets/1925a0d6-c77a-4ad9-aec7-d82f8abc50d2">

We need to understand what caused the regression and what we can do about it. A bisect should make this straightforward.

Jira issue: CRDB-43523

**Comment by nvanbenschoten** [comment]
@arulajmani points out that we landed https://github.com/cockroachdb/cockroach/pull/128708 on Aug 9th, which lines up with the timeline here. That PR was a revert of a change from July which had caused a different regression on `failover/non-system/crash`, tracked in https://github.com/cockroachdb/cockroach/issues/128642.

**Comment by nvanbenschoten** [comment]
@arulajmani was correct that switching `kv.lease.reject_on_leader_unknown.enabled` back to `false` caused the regression. But what I don't understand is why things weren't worse before https://github.com/cockroachdb/cockroach/pull/127082 (July 13th). Switching `kv.lease.reject_on_leader_unknown.enabled` back to `false` was just reverting a change we had made a month earlier.

**Comment by arulajmani** [comment]
> But what I don't understand is why things weren't worse before https://github.com/cockroachdb/cockroach/pull/127082 (July 13th).

+1.

**Comment by nvanbenschoten** [comment]
I can confirm that we see better results on the `release-24.2` branch (b91529e7af96b4f894bb15c330d2f461dca41dd6):
```
./liveness/pause/run_1/run_174945.408091439_n5_cockroach-workload-r.log
6979.3
./liveness/pause/run_2/run_174952.689286562_n5_cockroach-workload-r.log
6442.5
./liveness/pause/run_3/run_174918.159363971_n5_cockroach-workload-r.log
6979.3
```

**Comment by nvanbenschoten** [comment]
Same good results on 46a5cb142d7f9c19c190d63dc7c8f91195e4ef3c, which I had previously measured as bad. Maybe something changed in roachtest itself.
```
./liveness/pause/read-only/read-write/run_1/run_185721.271468600_n5_cockroach-workload-r.log
6979.3
./liveness/pause/read-only/read-write/run_2/run_185809.527398625_n5_cockroach-workload-r.log
6979.3
./liveness/pause/read-only/read-write/run_3/run_185750.049269372_n5_cockroach-workload-r.log
6710.9
```

**Comment by nvanbenschoten** [comment]
I get good results on 6c784d4793c6e14e30b390b56df42c2afba9b163 even if I revert the change to the cluster setting.
```
./pause/read-only/read-write/run_1/run_160822.667412297_n5_cockroach-workload-r.log
6979.3
./pause/read-only/read-write/run_2/run_160849.247395907_n5_cockroach-workload-r.log
6710.9
./pause/read-only/read-write/run_3/run_160809.150606263_n5_cockroach-workload-r.log
7247.8
```

**Comment by nvanbenschoten** [comment]
I don't understand why, but I believe that I have bisected this to e60feee392a1fc0c3984d187f49572bc9d742d52.

**Comment by nvanbenschoten** [comment]
Yeah, that's the commit that caused this.

I wonder if it has something to do with https://github.com/cockroachdb/cockroach/commit/e60feee392a1fc0c3984d187f49572bc9d742d52#diff-f0fe76e6faafc85192307191624619840130300e3c957c4ee5a1f57e398af828R102. Were there cases where we used to return `s.RaftState == StateFollower && s.Lead == r.id` and we no longer do? Perhaps after a check quorum step down? That could explain why `kv.lease.reject_on_leader_unknown.enabled` suddenly started making more of a difference.
