### ISSUE TITLE
roachtest: enable leader leases on perturbation tests

### ISSUE THREAD

**Issue by arulajmani** [cockroachdb/cockroach#133205]
**Describe the problem**

We should run variants of the perturbation tests with leader leases. cc @andrewbaptist -- you might have thoughts on whether certain variants are better than others, or if we should indiscriminately add these to all tests. 

Jira issue: CRDB-43505

Epic CRDB-42947

**Comment by nvanbenschoten** [comment]
Closed by https://github.com/cockroachdb/cockroach/pull/134204.
