### ISSUE TITLE
cli: add --listening-url-file flag

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#13327]
There are many cases (like https://github.com/cockroachdb/cockroach-go/pull/24) where exposing Cockroach on a random, automatically assigned port is desired. For instance, it is useful to avoid `address already in use` errors when running multiple instances of Cockroach side-by-side. This can be accomplished using the `--port` flag when running `cockroach start`, and setting this value to `0`, which uses [`ListenTCP`](https://golang.org/pkg/net/#ListenTCP)'s automatic port selection functionality.

However, in cases where a port is automatically assigned, a user cannot know the address to communicate with Cockroach ahead of time. Instead, they must wait for Cockroach to tell them where to connect. Currently, the only way to find this address is to parse the startup logs and find the line that looks like `sql: postgresql://root@localhost:26257?sslmode=disable`. We should introduce a more structured method to retrieve this targetted feedback from new Cockroach servers.

The current idea here is to add a new `--listening-url-file` flag, which would specify a filename to which the url would be written once startup is complete. This is analogous to PID files, where the process id of a running process is stored in a file in a well-known location. Implementation of this will need to handle error cases and cleanup on server shutdown in a similar manner to PID files.

**Comment by clebs** [comment]
Hello,

I would like to give this a try! It is my first look at this project but it seems quite straightforward issue and the solution is quite clear.

**Comment by nvanbenschoten** [comment]
Great @clebs! I've gone ahead and assigned you to the issue. Please update accordingly and reach out if you have any questions.

**Comment by clebs** [comment]
Cool thanks! I will be studying the PID files you mentioned and follow them as guideline.

The only question I currently have is:
You mention "a well-known location" in the description, is this a particular folder by convention or should the user be able to define it himself?

**Comment by nvanbenschoten** [comment]
I'm not actually sure what we'd like the default/suggested location to be. @bdarnell?

**Comment by bdarnell** [comment]
There would be no default; this feature would only be used when the user opted in and provided their own filename (which they would coordinate with whatever client they're using). The traditional home for files like this would be `/var/run` if it's a production service, although since this feature is primarily intended for use in testing environments its more likely to be somewhere under `/tmp/`.
