### ISSUE TITLE
sql: EXPLAIN options regression: QUALIFY, METADATA, and SYMVARS

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/cockroach#13321]
## Version

~~~
Build Tag:    5856727
Build Time:   2017/01/26 21:21:03
Distribution: CCL
Platform:     darwin amd64
Go Version:   go1.7.1
C Compiler:   4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)
~~~

### Steps to Repro

Create a database:
~~~
> CREATE TABLE IF NOT EXISTS t (k INT, v INT);
~~~

Run any of the following commands:

~~~
> EXPLAIN (QUALIFY) SELECT k FROM t;

> EXPLAIN (PLAN, QUALIFY) SELECT k FROM t;

> EXPLAIN (METADATA) SELECT k FROM t;

> EXPLAIN (PLAN, METADATA) SELECT k FROM t;

> EXPLAIN (SYMVARS) SELECT k FROM t;

> EXPLAIN (PLAN, SYMVARS) SELECT k FROM t;
~~~

### Expected Result

The query plan using the specified `PLAN` option is returned.

### Actual Result

You receive an `pq: unsupported EXPLAIN option` error message.

### More info

@knz's original diagnosis was that I was running from an old build, but I'm running from a new pull off the CRDB source. Had @andreimatei look at this on Friday and he suggested filing a bug because of the regression in support.

**Comment by knz** [comment]
sean please let's have a hangouts session about this.

**Comment by sploiselle** [comment]
Was using a newer version of the client to connect to an older version of the server, which was causing the issue. Once both were running on the newer version, issues disappeared.
