### ISSUE TITLE
Sentry: replica_raft.go:1711: ×: ×: replica unavailable: (n1,s1):1 unable to serve request to r18:× [(n1,s1):1, (n3,s3):2, (n2,s2):3LEARNER, next=4, gen=3]: lost quorum (down: (n3,s3):2); closed ti...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#133283]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/6015055895/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/6015055895/?referrer=webhooks_plugin)

Panic Message:

```
replica_raft.go:1711: ×: ×: replica unavailable: (n1,s1):1 unable to serve request to r18:× [(n1,s1):1, (n3,s3):2, (n2,s2):3LEARNER, next=4, gen=3]: lost quorum (down: (n3,s3):2); closed timestamp: 1729709513.209878000,0 (2024-10-23 18:51:53); raft status: {"id":"1","term":6,"vote":"1","commit":264,"lead":"0","raftState":"StatePreCandidate","applied":264,"progress":{},"leadtransferee":"0"}: have been waiting 60.50s for slow proposal Put [/Table/15/1/×/×], Delete [/Table/15/2/×/×/×/×], ConditionalPut [/Table/15/2/×/×/×/×], ConditionalPut [/Table/15/3/×/×/×/×], Delete [/Table/15/4/×/×/×/×/×], Delete [/Table/15/4/×/×/×/×/×/×], [txn: 54b09f72]
(1)
Wraps: (2) candidate pg code: XX000
Wraps: (3) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.init.func19.1
  | 	github.com/cockroachdb/cockroach/pkg/sql/crdb_internal.go:1456
  | [...repeated from below...]
Wraps: (4) ×
Wraps: (5) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).execInternal.func1.1
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1226
  | github.com/cockroachdb/cockroach/pkg/sql.(*rowsIterator).Close
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:603
  | github.com/cockroachdb/cockroach/pkg/sql.(*rowsIterator).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:579
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).queryInternalBuffered
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:684
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).queryRowExWithCols
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:762
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).QueryRowExWithCols
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:749
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).QueryRowEx
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:722
  | github.com/cockroachdb/cockroach/pkg/jobs.Updater.load
  | 	github.com/cockroachdb/cockroach/pkg/jobs/jobs.go:714
  | github.com/cockroachdb/cockroach/pkg/jobs.Updater.load.func1
  | 	github.com/cockroachdb/cockroach/pkg/jobs/jobs.go:682
  | github.com/cockroachdb/cockroach/pkg/sql.(*internalDBWithOverrides).Txn.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:2080
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).Txn.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1920
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).txn.func4
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:2007
  | github.com/cockroachdb/cockroach/pkg/kv.(*Txn).exec
  | 	github.com/cockroachdb/cockroach/pkg/kv/txn.go:1052
  | github.com/cockroachdb/cockroach/pkg/kv.runTxn
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:1098
  | github.com/cockroachdb/cockroach/pkg/kv.(*DB).TxnWithAdmissionControl
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:1061
  | github.com/cockroachdb/cockroach/pkg/kv.(*DB).Txn
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:1036
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).txn
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1994
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).Txn
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1921
  | github.com/cockroachdb/cockroach/pkg/sql.(*internalDBWithOverrides).Txn
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:2076
  | github.com/cockroachdb/cockroach/pkg/jobs.Updater.load
  | 	github.com/cockroachdb/cockroach/pkg/jobs/jobs.go:678
  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).LoadJobWithTxn
  | 	github.com/cockroachdb/cockroach/pkg/jobs/registry.go:862
  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).LoadJob
  | 	github.com/cockroachdb/cockroach/pkg/jobs/registry.go:835
  | github.com/cockroachdb/cockroach/pkg/sql.decodeMetaFieldsForJobs
  | 	github.com/cockroachdb/cockroach/pkg/sql/crdb_internal.go:1701
  | github.com/cockroachdb/cockroach/pkg/sql.init.func19
  | 	github.com/cockroachdb/cockroach/pkg/sql/crdb_internal.go:1531
  | github.com/cockroachdb/cockroach/pkg/sql.(*virtualDefEntry).getPlanInfo.func1.1
  | 	github.com/cockroachdb/cockroach/pkg/sql/virtual_schema.go:656
  | github.com/cockroachdb/cockroach/pkg/sql.setupGenerator.func3
  | 	github.com/cockroachdb/cockroach/pkg/sql/virtual_table.go:122
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:498
  | runtime.goexit
  | 	src/runtime/asm_arm64.s:1222
Wraps: (6) ×
Wraps: (7)
Wraps: (8) forced error mark
  | ×
  | github.com/cockroachdb/cockroach/pkg/util/circuit/*circuit.breakerErrorMark::
Wraps: (9) forced error mark
  | ×
  | github.com/cockroachdb/errors/withstack/*withstack.withStack::
Wraps: (10) replica unavailable: (n1,s1):1 unable to serve request to r18:× [(n1,s1):1, (n3,s3):2, (n2,s2):3LEARNER, next=4, gen=3]: lost quorum (down: (n3,s3):2); closed timestamp: 1729709513.209878000,0 (2024-10-23 18:51:53); raft status: {"id":"1","term":6,"vote":"1","commit":264,"lead":"0","raftState":"StatePreCandidate","applied":264,"progress":{},"leadtransferee":"0"}: have been waiting 60.50s for slow proposal Put [/Table/15/1/×/×], Delete [/Table/15/2/×/×/×/×], ConditionalPut [/Table/15/2/×/×/×/×], ConditionalPut [/Table/15/3/×/×/×/×], Delete [/Table/15/4/×/×/×/×/×], Delete [/Table/15/4/×/×/×/×/×/×], [txn: 54b09f72]
Wraps: (11)
  | (opaque error wrapper)
  | type name: github.com/cockroachdb/errors/withstack/*withstack.withStack
  | reportable 0:
  |
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.replicaUnavailableError
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_circuit_breaker.go:268
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).replicaUnavailableError
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_circuit_breaker.go:277
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*replicaCircuitBreaker).tripSync
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_circuit_breaker.go:97
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*replicaCircuitBreaker).TripAsync.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_circuit_breaker.go:91
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:498
  | runtime.goexit
  | 	src/runtime/asm_arm64.s:1222
Wraps: (12) lost quorum (down: (n3,s3):2); closed timestamp: 1729709513.209878000,0 (2024-10-23 18:51:53); raft status: {"id":"1","term":6,"vote":"1","commit":264,"lead":"0","raftState":"StatePreCandidate","applied":264,"progress":{},"leadtransferee":"0"}
Wraps: (13)
  | (opaque error wrapper)
  | type name: github.com/cockroachdb/errors/withstack/*withstack.withStack
  | reportable 0:
  |
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).refreshProposalsLocked
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:1711
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).tick
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:1543
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processTick
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:711
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftSchedulerShard).worker
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:410
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).Start.func2
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:319
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:498
  | runtime.goexit
  | 	src/runtime/asm_arm64.s:1222
Wraps: (14) have been waiting 60.50s for slow proposal Put [/Table/15/1/×/×], Delete [/Table/15/2/×/×/×/×], ConditionalPut [/Table/15/2/×/×/×/×], ConditionalPut [/Table/15/3/×/×/×/×], Delete [/Table/15/4/×/×/×/×/...
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_arm64.s#L1221-L1223](src/runtime/asm_arm64.s#L1221-L1223)
[https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/util/stop/stopper.go#L497-L499](https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/util/stop/stopper.go#L497-L499)
[https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/sql/virtual_table.go#L121-L123](https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/sql/virtual_table.go#L121-L123)
[https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/sql/virtual_schema.go#L655-L657](https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/sql/virtual_schema.go#L655-L657)
[https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/sql/crdb_internal.go#L1533-L1535](https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/sql/crdb_internal.go#L1533-L1535)
[https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/sql/crdb_internal.go#L1455-L1457](https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/sql/crdb_internal.go#L1455-L1457)
[src/runtime/asm_arm64.s#L1221-L1223](src/runtime/asm_arm64.s#L1221-L1223)
[https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/util/stop/stopper.go#L497-L499](https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/util/stop/stopper.go#L497-L499)
[https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/sql/virtual_table.go#L121-L123](https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/sql/virtual_table.go#L121-L123)
[https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/sql/virtual_schema.go#L655-L657](https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/sql/virtual_schema.go#L655-L657)
[https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/sql/crdb_internal.go#L1530-L1532](https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/sql/crdb_internal.go#L1530-L1532)
[https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/sql/crdb_internal.go#L1700-L1702](https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/sql/crdb_internal.go#L1700-L1702)
[https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/jobs/registry.go#L834-L836](https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/jobs/registry.go#L834-L836)
[https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/jobs/registry.go#L861-L863](https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/jobs/registry.go#L861-L863)
[https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/jobs/jobs.go#L677-L679](https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/jobs/jobs.go#L677-L679)
[https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/sql/internal.go#L2075-L2077](https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/sql/internal.go#L2075-L2077)
[https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/sql/internal.go#L1920-L1922](https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/sql/internal.go#L1920-L1922)
[https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/sql/internal.go#L1993-L1995](https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/sql/internal.go#L1993-L1995)
[https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/kv/db.go#L1035-L1037](https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/kv/db.go#L1035-L1037)
[https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/kv/db.go#L1060-L1062](https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/kv/db.go#L1060-L1062)
[https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/kv/db.go#L1097-L1099](https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/kv/db.go#L1097-L1099)
[https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/kv/txn.go#L1051-L1053](https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/kv/txn.go#L1051-L1053)
[https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/sql/internal.go#L2006-L2008](https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/sql/internal.go#L2006-L2008)
[https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/sql/internal.go#L1919-L1921](https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/sql/internal.go#L1919-L1921)
[https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/sql/internal.go#L2079-L2081](https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/sql/internal.go#L2079-L2081)
[https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/jobs/jobs.go#L681-L683](https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/jobs/jobs.go#L681-L683)
[https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/jobs/jobs.go#L713-L715](https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/jobs/jobs.go#L713-L715)
[https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/sql/internal.go#L721-L723](https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/sql/internal.go#L721-L723)
[https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/sql/internal.go#L748-L750](https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/sql/internal.go#L748-L750)
[https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/sql/internal.go#L761-L763](https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/sql/internal.go#L761-L763)
[https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/sql/internal.go#L683-L685](https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/sql/internal.go#L683-L685)
[https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/sql/internal.go#L578-L580](https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/sql/internal.go#L578-L580)
[https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/sql/internal.go#L602-L604](https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/sql/internal.go#L602-L604)
[https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/sql/internal.go#L1225-L1227](https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/sql/internal.go#L1225-L1227)
[src/runtime/asm_arm64.s#L1221-L1223](src/runtime/asm_arm64.s#L1221-L1223)
[https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/util/stop/stopper.go#L497-L499](https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/util/stop/stopper.go#L497-L499)
[https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/kv/kvserver/pkg/kv/kvserver/replica_circuit_breaker.go#L90-L92](https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/kv/kvserver/pkg/kv/kvserver/replica_circuit_breaker.go#L90-L92)
[https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/kv/kvserver/pkg/kv/kvserver/replica_circuit_breaker.go#L96-L98](https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/kv/kvserver/pkg/kv/kvserver/replica_circuit_breaker.go#L96-L98)
[https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/kv/kvserver/pkg/kv/kvserver/replica_circuit_breaker.go#L276-L278](https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/kv/kvserver/pkg/kv/kvserver/replica_circuit_breaker.go#L276-L278)
[https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/kv/kvserver/pkg/kv/kvserver/replica_circuit_breaker.go#L267-L269](https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/kv/kvserver/pkg/kv/kvserver/replica_circuit_breaker.go#L267-L269)
[src/runtime/asm_arm64.s#L1221-L1223](src/runtime/asm_arm64.s#L1221-L1223)
[https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/util/stop/stopper.go#L497-L499](https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/util/stop/stopper.go#L497-L499)
[https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L318-L320](https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L318-L320)
[https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L409-L411](https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L409-L411)
[https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L710-L712](https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L710-L712)
[https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L1542-L1544](https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L1542-L1544)
[https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L1710-L1712](https://github.com/cockroachdb/cockroach/blob/1e5b3c212b45419c960038718c48a5dd75a111a0/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L1710-L1712)
</details>

```
src/runtime/asm_arm64.s in runtime.goexit at line 1222
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 498
pkg/sql/virtual_table.go in pkg/sql.setupGenerator.func3 at line 122
pkg/sql/virtual_schema.go in pkg/sql.(*virtualDefEntry).getPlanInfo.func1.1 at line 656
pkg/sql/crdb_internal.go in pkg/sql.init.func19 at line 1534
pkg/sql/crdb_internal.go in pkg/sql.init.func19.1 at line 1456
src/runtime/asm_arm64.s in runtime.goexit at line 1222
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 498
pkg/sql/virtual_table.go in pkg/sql.setupGenerator.func3 at line 122
pkg/sql/virtual_schema.go in pkg/sql.(*virtualDefEntry).getPlanInfo.func1.1 at line 656
pkg/sql/crdb_internal.go in pkg/sql.init.func19 at line 1531
pkg/sql/crdb_internal.go in pkg/sql.decodeMetaFieldsForJobs at line 1701
pkg/jobs/registry.go in pkg/jobs.(*Registry).LoadJob at line 835
pkg/jobs/registry.go in pkg/jobs.(*Registry).LoadJobWithTxn at line 862
pkg/jobs/jobs.go in pkg/jobs.Updater.load at line 678
pkg/sql/internal.go in pkg/sql.(*internalDBWithOverrides).Txn at line 2076
pkg/sql/internal.go in pkg/sql.(*InternalDB).Txn at line 1921
pkg/sql/internal.go in pkg/sql.(*InternalDB).txn at line 1994
pkg/kv/db.go in pkg/kv.(*DB).Txn at line 1036
pkg/kv/db.go in pkg/kv.(*DB).TxnWithAdmissionControl at line 1061
pkg/kv/db.go in pkg/kv.runTxn at line 1098
pkg/kv/txn.go in pkg/kv.(*Txn).exec at line 1052
pkg/sql/internal.go in pkg/sql.(*InternalDB).txn.func4 at line 2007
pkg/sql/internal.go in pkg/sql.(*InternalDB).Txn.func1 at line 1920
pkg/sql/internal.go in pkg/sql.(*internalDBWithOverrides).Txn.func1 at line 2080
pkg/jobs/jobs.go in pkg/jobs.Updater.load.func1 at line 682
pkg/jobs/jobs.go in pkg/jobs.Updater.load at line 714
pkg/sql/internal.go in pkg/sql.(*InternalExecutor).QueryRowEx at line 722
pkg/sql/internal.go in pkg/sql.(*InternalExecutor).QueryRowExWithCols at line 749
pkg/sql/internal.go in pkg/sql.(*InternalExecutor).queryRowExWithCols at line 762
pkg/sql/internal.go in pkg/sql.(*InternalExecutor).queryInternalBuffered at line 684
pkg/sql/internal.go in pkg/sql.(*rowsIterator).Next at line 579
pkg/sql/internal.go in pkg/sql.(*rowsIterator).Close at line 603
pkg/sql/internal.go in pkg/sql.(*InternalExecutor).execInternal.func1.1 at line 1226
src/runtime/asm_arm64.s in runtime.goexit at line 1222
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 498
pkg/kv/kvserver/pkg/kv/kvserver/replica_circuit_breaker.go in pkg/kv/kvserver.(*replicaCircuitBreaker).TripAsync.func1 at line 91
pkg/kv/kvserver/pkg/kv/kvserver/replica_circuit_breaker.go in pkg/kv/kvserver.(*replicaCircuitBreaker).tripSync at line 97
pkg/kv/kvserver/pkg/kv/kvserver/replica_circuit_breaker.go in pkg/kv/kvserver.(*Replica).replicaUnavailableError at line 277
pkg/kv/kvserver/pkg/kv/kvserver/replica_circuit_breaker.go in pkg/kv/kvserver.replicaUnavailableError at line 268
src/runtime/asm_arm64.s in runtime.goexit at line 1222
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 498
pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go in pkg/kv/kvserver.(*raftScheduler).Start.func2 at line 319
pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go in pkg/kv/kvserver.(*raftSchedulerShard).worker at line 410
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).processTick at line 711
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).tick at line 1543
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).refreshProposalsLocked at line 1711
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | development |
| Go Version | go1.22.5 X:nocoverageredesign |
| Platform | darwin arm64 |
| Distribution | CCL |
| Cockroach Release | v24.3.0-alpha.3-dev-1e5b3c212b45419c960038718c48a5dd75a111a0 |
| Cockroach SHA | 1e5b3c212b45419c960038718c48a5dd75a111a0 |
| # of CPUs | 10 |
| # of Goroutines | 599 |

Jira issue: CRDB-43534

**Comment by yuzefovich** [comment]
unactionable
