### ISSUE TITLE
ui: Expose information about rebalancing decisions

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#13339]
Cockroach makes a lot of automated decisions about where to place replicas and leases within a cluster. While we hope that these decisions improve performance and availability, it's possible that we could occasionally make bad decisions. Rebalancing decisions are currently only visible in the logs, so if a user is trying to figure out why performance in their cluster dipped they're not very likely to notice the rebalance that may have caused the dip. We may want to expose these events (or the underlying information used to make rebalancing decisions) somewhere.

Suggested by @RaduBerinde while reviewing #13233.

Jira issue: CRDB-6116

**Comment by dianasaur323** [comment]
@a-robinson Is this something you would want to see in events on graphs (basically a little marker would show up when rebalancing occurs)?

**Comment by a-robinson** [comment]
I think rebalancing happens a bit too often to be a good fit for overlaying on all graphs. It'd probably make more sense as a separate section with recent rebalancing events (and ideally the reasons why we made them).

**Comment by petermattis** [comment]
Agreed that we have too many rebalancing events to overlay on graphs. I feel like there is some cool visualization that could be done here, but I'm not sure what it is.

**Comment by a-robinson** [comment]
They aren't great for users of the system, but https://github.com/cockroachdb/cockroach/pull/17789 and https://github.com/cockroachdb/cockroach/pull/17756 fulfilled this need for developers (i.e. me).

**Comment by jordanlewis** [comment]
Hey @andreimatei, do we have more information about these kinds of decisions given the work with the allocator simulator and so on?
