### ISSUE TITLE
logictest: add a logic test to test for mixed version functionality for license enforcement

### ISSUE THREAD

**Issue by rimadeodhar** [cockroachdb/cockroach#133314]
This task tracks adding a logictest to increase mixed version test coverage for CockroachDB license enforcement code. We can also use our code coverage tool to validate current test coverage.

Jira issue: CRDB-43539

**Comment by spilchen** [comment]
It doesn't look like we have collected test coverage recently. The last successful builds were from last December: https://teamcity.cockroachdb.com/project/Cockroach_Coverage?mode=builds#all-projects. I tried to trigger the build myself, but it wasn't able to generate any coverage data.

**Comment by spilchen** [comment]
I don’t think logic test is a good fit for additional license enforcement tests. To do license enforcement you need to be running concurrent connections. logictest has limited support for that. You can do some concurrent test with the async keyword for both queries and statements. However, once you add the async behaviour, you are adding a lot of timing into the test and it’s a lot harder to get consistent results. This is as close as I could get for a reliable repro, but it depended on a sleep to wait for all background connections to have an open transaction.

```
# LogicTest: local local-mixed-24.1 local-mixed-24.2

subtest throttle

# Install an expired free license. This ensures that we are in the
# mode to throttle.
statement ok
SET CLUSTER SETTING enterprise.license = 'crl-0-EKjXh/ACGAM';

statement ok
CREATE TABLE ut_table (c1 int);

statement ok
INSERT INTO ut_table VALUES (0),(10);

statement ok
GRANT ALL ON ut_table TO testuser;

user testuser

statement ok
SET enable_shared_locking_for_serializable = true;

statement ok
BEGIN

query I rowsort
SELECT * FROM ut_table WHERE c1 IN (0,10) FOR SHARE
----
0
10

user root

# We can allow 4 more connections before throttling begins. We will
# run each of these async and have them block on the share lock that
# the foreground process has.

statement async bg1
UPDATE ut_table SET c1 = c1 + 1;

statement async bg2
UPDATE ut_table SET c1 = c1 + 1;

statement async bg3
UPDATE ut_table SET c1 = c1 + 1;

statement async bg4
UPDATE ut_table SET c1 = c1 + 1;

# Now run another test that should throttle as it's the 6th transaction in.
sleep 5s
query error pgcode XXC02 pq: License expired on 1994-06-17 .* The maximum number of concurrently open transactions has been reached.\nHINT: Obtain and install a new license to continue.
SELECT 1;

user testuser

statement ok
COMMIT;

user root

# With the foreground transaction done, and its lock given up, all of the
# background queries can proceed.
awaitstatement bg1
awaitstatement bg2
awaitstatement bg3
awaitstatement bg4

statement ok
SET CLUSTER SETTING enterprise.license = '';

subtest end
```

**Comment by spilchen** [comment]
I ended up just capturing test coverage manually via this:
```
❯ go test -coverprofile cov.prof ./pkg/server/license/...
ok      github.com/cockroachdb/cockroach/pkg/server/license     3.338s  coverage: 81.5% of statements
❯ go test -coverprofile cov.prof ./pkg/ccl/utilccl/...
        github.com/cockroachdb/cockroach/pkg/ccl/utilccl/licenseccl             coverage: 0.0% of statements
ok      github.com/cockroachdb/cockroach/pkg/ccl/utilccl        0.696s  coverage: 71.0% of statements
```

I think the coverage looks good overall. I did a visual inspection of the coverage profile and found that the only gap was some error-handling code. There’s a function in the pkg/server/license package that wasn’t directly tested, but it is covered by a function in the pkg/ccl/utilccl package. So, I believe we have sufficient test coverage here.

**Comment by spilchen** [comment]
Stan was able to rerun the unit test coverage test in TeamCity. Here's the link from his run:
https://storage.googleapis.com/cockroach-tmp/cockroach/2024-10-29%2014:47Z%20322a8d5b%20-%20unit_tests/index.html

The `pkg/server/license` package shows pretty good test coverage. It's higher than when I ran `go test` manually since it collects coverage across all tests.
![image](https://github.com/user-attachments/assets/b1334de7-217c-4101-abf6-75643b3e98a0)
