### ISSUE TITLE
Sentry: replica_init.go:380: log.Fatal: attempted to change replica's ID from 36 to 20 (1) attached stack trace   -- stack trace:   | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).setDes...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#133398]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/6017668368/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/6017668368/?referrer=webhooks_plugin)

Panic Message:

```
replica_init.go:380: log.Fatal: attempted to change replica's ID from 36 to 20
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).setDescLockedRaftMuLocked
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_init.go:380
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).setDescRaftMuLocked
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_init.go:348
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleDescResult
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_application_result.go:474
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*replicaStateMachine).handleNonTrivialReplicatedEvalResult
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_application_state_machine.go:354
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*replicaStateMachine).ApplySideEffects
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_application_state_machine.go:194
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply.mapCheckedCmdIter
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply/cmd.go:214
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply.(*Task).applyOneBatch
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply/task.go:295
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply.(*Task).ApplyCommittedEntries
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply/task.go:251
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:1099
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReady
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:758
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processReady
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:689
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftSchedulerShard).worker
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:417
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).Start.func2
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:320
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:485
  | runtime.goexit
  | 	src/runtime/asm_arm64.s:1222
Wraps: (2) log.Fatal: attempted to change replica's ID from 36 to 20
Error types: (1) *withstack.withStack (2) *errutil.leafError
-- report composition:
*errutil.leafError: log.Fatal: attempted to change replica's ID from 36 to 20
replica_init.go:380: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_arm64.s#L1221-L1223](src/runtime/asm_arm64.s#L1221-L1223)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/util/stop/stopper.go#L484-L486](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/util/stop/stopper.go#L484-L486)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L319-L321](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L319-L321)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L416-L418](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L416-L418)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L688-L690](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L688-L690)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L757-L759](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L757-L759)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L1098-L1100](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L1098-L1100)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/kv/kvserver/apply/task.go#L250-L252](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/kv/kvserver/apply/task.go#L250-L252)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/kv/kvserver/apply/task.go#L294-L296](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/kv/kvserver/apply/task.go#L294-L296)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/kv/kvserver/apply/cmd.go#L213-L215](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/kv/kvserver/apply/cmd.go#L213-L215)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/kv/kvserver/pkg/kv/kvserver/replica_application_state_machine.go#L193-L195](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/kv/kvserver/pkg/kv/kvserver/replica_application_state_machine.go#L193-L195)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/kv/kvserver/pkg/kv/kvserver/replica_application_state_machine.go#L353-L355](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/kv/kvserver/pkg/kv/kvserver/replica_application_state_machine.go#L353-L355)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/kv/kvserver/pkg/kv/kvserver/replica_application_result.go#L473-L475](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/kv/kvserver/pkg/kv/kvserver/replica_application_result.go#L473-L475)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/kv/kvserver/pkg/kv/kvserver/replica_init.go#L347-L349](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/kv/kvserver/pkg/kv/kvserver/replica_init.go#L347-L349)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/kv/kvserver/pkg/kv/kvserver/replica_init.go#L379-L381](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/kv/kvserver/pkg/kv/kvserver/replica_init.go#L379-L381)
</details>

```
src/runtime/asm_arm64.s in runtime.goexit at line 1222
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 485
pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go in pkg/kv/kvserver.(*raftScheduler).Start.func2 at line 320
pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go in pkg/kv/kvserver.(*raftSchedulerShard).worker at line 417
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).processReady at line 689
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).handleRaftReady at line 758
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked at line 1099
pkg/kv/kvserver/apply/task.go in pkg/kv/kvserver/apply.(*Task).ApplyCommittedEntries at line 251
pkg/kv/kvserver/apply/task.go in pkg/kv/kvserver/apply.(*Task).applyOneBatch at line 295
pkg/kv/kvserver/apply/cmd.go in pkg/kv/kvserver/apply.mapCheckedCmdIter at line 214
pkg/kv/kvserver/pkg/kv/kvserver/replica_application_state_machine.go in pkg/kv/kvserver.(*replicaStateMachine).ApplySideEffects at line 194
pkg/kv/kvserver/pkg/kv/kvserver/replica_application_state_machine.go in pkg/kv/kvserver.(*replicaStateMachine).handleNonTrivialReplicatedEvalResult at line 354
pkg/kv/kvserver/pkg/kv/kvserver/replica_application_result.go in pkg/kv/kvserver.(*Replica).handleDescResult at line 474
pkg/kv/kvserver/pkg/kv/kvserver/replica_init.go in pkg/kv/kvserver.(*Replica).setDescRaftMuLocked at line 348
pkg/kv/kvserver/pkg/kv/kvserver/replica_init.go in pkg/kv/kvserver.(*Replica).setDescLockedRaftMuLocked at line 380
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v24.1.4 |
| Go Version | go1.22.5 X:nocoverageredesign |
| Platform | linux arm64 |
| Distribution | CCL |
| Cockroach Release | v24.1.4 |
| Cockroach SHA | a1cbd782a33a51f7500444373ccdaa81eb2ed971 |
| # of CPUs | 8 |
| # of Goroutines | 892 |

Jira issue: CRDB-43583

**Comment by yuzefovich** [comment]
unactionable
