### ISSUE TITLE
Sentry: txn_lock_gatekeeper.go:70: ×: concurrent txn use detected. ba: Scan [/Table/52/2/×,/Table/52/2/×/×), [txn: 0cba37ed], [max_span_request_keys: 0], [target_bytes: 10485760] (1) secondary err...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#133325]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/6015902982/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/6015902982/?referrer=webhooks_plugin)

Panic Message:

```
txn_lock_gatekeeper.go:70: ×: concurrent txn use detected. ba: Scan [/Table/52/2/×,/Table/52/2/×/×), [txn: 0cba37ed], [max_span_request_keys: 0], [target_bytes: 10485760]
(1) secondary error attachment
  | ×: concurrent txn use detected. ba: Scan [/Table/52/2/×,/Table/52/2/×/×), [txn: 0cba37ed], [max_span_request_keys: 0], [target_bytes: 10485760]
  | (1) attached stack trace
  |   -- stack trace:
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).execInternal.func1.1
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1264
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*rowsIterator).Next.func1
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:559
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*rowsIterator).Next
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:618
  |   | github.com/cockroachdb/cockroach/pkg/sql/syntheticprivilegecache.(*Cache).readFromStorage
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/syntheticprivilegecache/cache.go:145
  |   | github.com/cockroachdb/cockroach/pkg/sql/syntheticprivilegecache.(*Cache).Get.func1
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/syntheticprivilegecache/cache.go:93
  |   | github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight.(*Group).doCall.func1
  |   | 	github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight/singleflight.go:389
  |   | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTask
  |   | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:320
  |   | github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight.(*Group).doCall
  |   | 	github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight/singleflight.go:388
  |   | runtime.goexit
  |   | 	src/runtime/asm_amd64.s:1695
  | Wraps: (2) ×
  | Wraps: (3)
  | Wraps: (4) assertion failure
  | Wraps: (5)
  |   | (opaque error wrapper)
  |   | type name: github.com/cockroachdb/errors/withstack/*withstack.withStack
  |   | reportable 0:
  |   |
  |   | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnLockGatekeeper).SendLocked
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_lock_gatekeeper.go:70
  |   | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnMetricRecorder).SendLocked
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_metric_recorder.go:46
  |   | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnSpanRefresher).sendLockedWithRefreshAttempts
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go:239
  |   | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnSpanRefresher).SendLocked
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go:167
  |   | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnCommitter).SendLocked
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_committer.go:149
  |   | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnPipeliner).SendLocked
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go:326
  |   | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnSeqNumAllocator).SendLocked
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_seq_num_allocator.go:117
  |   | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnHeartbeater).SendLocked
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater.go:270
  |   | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*TxnCoordSender).Send
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_coord_sender.go:539
  |   | github.com/cockroachdb/cockroach/pkg/kv.(*DB).sendUsingSender
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:1138
  |   | github.com/cockroachdb/cockroach/pkg/kv.(*Txn).Send
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/txn.go:1282
  |   | github.com/cockroachdb/cockroach/pkg/sql/row.newTxnKVFetcher.makeTxnKVFetcherDefaultSendFunc.func2
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/row/kv_batch_fetcher.go:281
  |   | github.com/cockroachdb/cockroach/pkg/sql/row.(*txnKVFetcher).fetch
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/row/kv_batch_fetcher.go:589
  |   | github.com/cockroachdb/cockroach/pkg/sql/row.(*txnKVFetcher).nextBatch
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/row/kv_batch_fetcher.go:872
  |   | github.com/cockroachdb/cockroach/pkg/sql/row.(*kvBatchFetcherHelper).NextBatch
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/row/kv_batch_fetcher.go:1021
  |   | github.com/cockroachdb/cockroach/pkg/sql/row.(*KVFetcher).nextKV
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/row/kv_fetcher.go:286
  |   | github.com/cockroachdb/cockroach/pkg/sql/row.(*KVFetcher).NextKV
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/row/kv_fetcher.go:307
  |   | github.com/cockroachdb/cockroach/pkg/sql/colfetcher.(*cFetcher).NextBatch
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colfetcher/cfetcher.go:693
  |   | github.com/cockroachdb/cockroach/pkg/sql/colfetcher.(*ColBatchScan).Next
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colfetcher/colbatch_scan.go:243
  |   | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils.(*CancelChecker).Next
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils/cancel_checker.go:59
  |   | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecbase.(*simpleProjectOp).Next
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecbase/simple_project.go:124
  |   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).next
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:118
  |   | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:152
  |   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).Next
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:126
  |   | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Materializer).next
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:251
  |   | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Materializer).nextAdapter
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:276
  |   | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:152
  |   | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Materializer).Next
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:282
  |   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*FlowCoordinator).next
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:124
  |   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*FlowCoordinator).nextAdapter
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:141
  |   | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:152
  |   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*FlowCoordinator).Next
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:146
  | Wraps: (6) concurrent txn use detected. ba: Scan [/Table/52/2/×,/Table/52/2/×/×), [txn: 0cba37ed], [max_span_request_keys: 0], [target_bytes: 10485760]
  | Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *colexecerror.StorageError (4) *assert.withAssertionFailure (5) *errbase.opaqueWrapper (6) *errutil.leafError
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).execInternal.func1.1
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1264
  | github.com/cockroachdb/cockroach/pkg/sql.(*rowsIterator).Next.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:559
  | github.com/cockroachdb/cockroach/pkg/sql.(*rowsIterator).Next
  | 	github.com/coc...
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_amd64.s#L1694-L1696](src/runtime/asm_amd64.s#L1694-L1696)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/util/syncutil/singleflight/singleflight.go#L387-L389](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/util/syncutil/singleflight/singleflight.go#L387-L389)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/util/stop/stopper.go#L319-L321](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/util/stop/stopper.go#L319-L321)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/util/syncutil/singleflight/singleflight.go#L388-L390](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/util/syncutil/singleflight/singleflight.go#L388-L390)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/syntheticprivilegecache/cache.go#L92-L94](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/syntheticprivilegecache/cache.go#L92-L94)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/syntheticprivilegecache/cache.go#L144-L146](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/syntheticprivilegecache/cache.go#L144-L146)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/internal.go#L617-L619](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/internal.go#L617-L619)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/internal.go#L558-L560](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/internal.go#L558-L560)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/internal.go#L1263-L1265](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/internal.go#L1263-L1265)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/colflow/flow_coordinator.go#L145-L147](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/colflow/flow_coordinator.go#L145-L147)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/colexecerror/error.go#L151-L153](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/colexecerror/error.go#L151-L153)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/colflow/flow_coordinator.go#L140-L142](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/colflow/flow_coordinator.go#L140-L142)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/colflow/flow_coordinator.go#L123-L125](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/colflow/flow_coordinator.go#L123-L125)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/colexec/materializer.go#L281-L283](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/colexec/materializer.go#L281-L283)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/colexecerror/error.go#L151-L153](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/colexecerror/error.go#L151-L153)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/colexec/materializer.go#L275-L277](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/colexec/materializer.go#L275-L277)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/colexec/materializer.go#L250-L252](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/colexec/materializer.go#L250-L252)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/colflow/stats.go#L125-L127](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/colflow/stats.go#L125-L127)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/colexecerror/error.go#L151-L153](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/colexecerror/error.go#L151-L153)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/colflow/stats.go#L117-L119](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/colflow/stats.go#L117-L119)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/colexec/colexecbase/simple_project.go#L123-L125](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/colexec/colexecbase/simple_project.go#L123-L125)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/colexec/colexecutils/cancel_checker.go#L58-L60](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/colexec/colexecutils/cancel_checker.go#L58-L60)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/colfetcher/colbatch_scan.go#L242-L244](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/colfetcher/colbatch_scan.go#L242-L244)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/colfetcher/cfetcher.go#L692-L694](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/colfetcher/cfetcher.go#L692-L694)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/row/kv_fetcher.go#L306-L308](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/row/kv_fetcher.go#L306-L308)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/row/kv_fetcher.go#L285-L287](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/row/kv_fetcher.go#L285-L287)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/row/kv_batch_fetcher.go#L1020-L1022](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/row/kv_batch_fetcher.go#L1020-L1022)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/row/kv_batch_fetcher.go#L871-L873](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/row/kv_batch_fetcher.go#L871-L873)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/row/kv_batch_fetcher.go#L588-L590](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/row/kv_batch_fetcher.go#L588-L590)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/row/kv_batch_fetcher.go#L280-L282](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/sql/row/kv_batch_fetcher.go#L280-L282)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/kv/txn.go#L1281-L1283](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/kv/txn.go#L1281-L1283)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/kv/db.go#L1137-L1139](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/kv/db.go#L1137-L1139)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L538-L540](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L538-L540)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater.go#L269-L271](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater.go#L269-L271)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/kv/kvclient/kvcoord/txn_interceptor_seq_num_allocator.go#L116-L118](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/kv/kvclient/kvcoord/txn_interceptor_seq_num_allocator.go#L116-L118)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go#L325-L327](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go#L325-L327)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/kv/kvclient/kvcoord/txn_interceptor_committer.go#L148-L150](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/kv/kvclient/kvcoord/txn_interceptor_committer.go#L148-L150)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go#L166-L168](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go#L166-L168)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go#L238-L240](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go#L238-L240)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/kv/kvclient/kvcoord/txn_interceptor_metric_recorder.go#L45-L47](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/kv/kvclient/kvcoord/txn_interceptor_metric_recorder.go#L45-L47)
[https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/kv/kvclient/kvcoord/txn_lock_gatekeeper.go#L69-L71](https://github.com/cockroachdb/cockroach/blob/217b43e69da61e9712d73e3e19fd5076fbdb26df/pkg/kv/kvclient/kvcoord/txn_lock_gatekeeper.go#L69-L71)
</details>

```
src/runtime/asm_amd64.s in runtime.goexit at line 1695
pkg/util/syncutil/singleflight/singleflight.go in pkg/util/syncutil/singleflight.(*Group).doCall at line 388
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunTask at line 320
pkg/util/syncutil/singleflight/singleflight.go in pkg/util/syncutil/singleflight.(*Group).doCall.func1 at line 389
pkg/sql/syntheticprivilegecache/cache.go in pkg/sql/syntheticprivilegecache.(*Cache).Get.func1 at line 93
pkg/sql/syntheticprivilegecache/cache.go in pkg/sql/syntheticprivilegecache.(*Cache).readFromStorage at line 145
pkg/sql/internal.go in pkg/sql.(*rowsIterator).Next at line 618
pkg/sql/internal.go in pkg/sql.(*rowsIterator).Next.func1 at line 559
pkg/sql/internal.go in pkg/sql.(*InternalExecutor).execInternal.func1.1 at line 1264
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*FlowCoordinator).Next at line 146
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 152
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*FlowCoordinator).nextAdapter at line 141
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*FlowCoordinator).next at line 124
pkg/sql/colexec/materializer.go in pkg/sql/colexec.(*Materializer).Next at line 282
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 152
pkg/sql/colexec/materializer.go in pkg/sql/colexec.(*Materializer).nextAdapter at line 276
pkg/sql/colexec/materializer.go in pkg/sql/colexec.(*Materializer).next at line 251
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).Next at line 126
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 152
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).next at line 118
pkg/sql/colexec/colexecbase/simple_project.go in pkg/sql/colexec/colexecbase.(*simpleProjectOp).Next at line 124
pkg/sql/colexec/colexecutils/cancel_checker.go in pkg/sql/colexec/colexecutils.(*CancelChecker).Next at line 59
pkg/sql/colfetcher/colbatch_scan.go in pkg/sql/colfetcher.(*ColBatchScan).Next at line 243
pkg/sql/colfetcher/cfetcher.go in pkg/sql/colfetcher.(*cFetcher).NextBatch at line 693
pkg/sql/row/kv_fetcher.go in pkg/sql/row.(*KVFetcher).NextKV at line 307
pkg/sql/row/kv_fetcher.go in pkg/sql/row.(*KVFetcher).nextKV at line 286
pkg/sql/row/kv_batch_fetcher.go in pkg/sql/row.(*kvBatchFetcherHelper).NextBatch at line 1021
pkg/sql/row/kv_batch_fetcher.go in pkg/sql/row.(*txnKVFetcher).nextBatch at line 872
pkg/sql/row/kv_batch_fetcher.go in pkg/sql/row.(*txnKVFetcher).fetch at line 589
pkg/sql/row/kv_batch_fetcher.go in pkg/sql/row.newTxnKVFetcher.makeTxnKVFetcherDefaultSendFunc.func2 at line 281
pkg/kv/txn.go in pkg/kv.(*Txn).Send at line 1282
pkg/kv/db.go in pkg/kv.(*DB).sendUsingSender at line 1138
pkg/kv/kvclient/kvcoord/txn_coord_sender.go in pkg/kv/kvclient/kvcoord.(*TxnCoordSender).Send at line 539
pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater.go in pkg/kv/kvclient/kvcoord.(*txnHeartbeater).SendLocked at line 270
pkg/kv/kvclient/kvcoord/txn_interceptor_seq_num_allocator.go in pkg/kv/kvclient/kvcoord.(*txnSeqNumAllocator).SendLocked at line 117
pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go in pkg/kv/kvclient/kvcoord.(*txnPipeliner).SendLocked at line 326
pkg/kv/kvclient/kvcoord/txn_interceptor_committer.go in pkg/kv/kvclient/kvcoord.(*txnCommitter).SendLocked at line 149
pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go in pkg/kv/kvclient/kvcoord.(*txnSpanRefresher).SendLocked at line 167
pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go in pkg/kv/kvclient/kvcoord.(*txnSpanRefresher).sendLockedWithRefreshAttempts at line 239
pkg/kv/kvclient/kvcoord/txn_interceptor_metric_recorder.go in pkg/kv/kvclient/kvcoord.(*txnMetricRecorder).SendLocked at line 46
pkg/kv/kvclient/kvcoord/txn_lock_gatekeeper.go in pkg/kv/kvclient/kvcoord.(*txnLockGatekeeper).SendLocked at line 70
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v24.2.3 |
| Go Version | go1.22.5 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v24.2.3 |
| Cockroach SHA | 217b43e69da61e9712d73e3e19fd5076fbdb26df |
| # of CPUs | 4 |
| # of Goroutines | 399 |

Jira issue: CRDB-43540

**Comment by yuzefovich** [comment]
dup of #132706
