### ISSUE TITLE
rpc,security: optimize kvAuth for performance (0.5% cpu)

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#133317]
on the sysbench oltp_read_write reference workload, authenticating incoming RPCs accounted for ~0.5% of sampled CPU time. This seems to be driven primarily by allocations such as these.

We should optimize this code.

As an aside: it's possible that some of the overhead of repeat authorization could be removed (within a tenant) by using long-lived streaming RPCs instead. IIRC Internally, unary RPCs are just special-cased streaming RPCs, anyway.

```
github.com/cockroachdb/cockroach/pkg/security.getCertificatePrincipals
pkg/security/auth.go

  Total:        20ms      320ms (flat, cum)  0.15%
    188            .          .           	} 
    189            .          .           	return mappedName 
    190            .          .           } 
    191            .          .            
    192            .          .           func getCertificatePrincipals(cert *x509.Certificate) []string { 
    193            .      210ms           	results := make([]string, 0, 1+len(cert.DNSNames)) 
    194         10ms       60ms           	results = append(results, transformPrincipal(cert.Subject.CommonName)) 
    195            .          .           	for _, name := range cert.DNSNames { 
    196         10ms       50ms           		results = append(results, transformPrincipal(name)) 
    197            .          .           	} 
    198            .          .           	return results 
    199            .          .           } 
    200            .          .            
    201            .          .           // GetCertificateUserScope extracts the certificate scopes from a client 
```

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/743a5015-9ec9-40a7-b074-ada0ca68d3e2">

Jira issue: CRDB-43616

**Comment by nvanbenschoten** [comment]
With the local RPC fast path disabled in the microbenchmark, I do see this code being hit, but it accounts for much less of the CPU profile. Only about .01%. Maybe it is using a cert with fewer principals.
