### ISSUE TITLE
roachtest: both branches of `if-else` are identical

### ISSUE THREAD

**Issue by chavacava** [cockroachdb/cockroach#133301]
Both branches of the following `if-else` are identical

https://github.com/cockroachdb/cockroach/blob/23adad662adb2529620bd73d20b421fe61dabb6d/pkg/cmd/roachtest/tests/connection_latency.go#L51-L57

Found with [revive](https://github.com/mgechev/revive/)

Jira issue: CRDB-43537

**Comment by yuzefovich** [comment]
This duplication started in fd6d12c728d9cfd54750383a74bb10680f8f4946. @DarrylWong can you please double-check that no "meaning" was lost in that change and remove the duplication if so?

**Comment by DarrylWong** [comment]
Totally missed this ping until now. Fortunately it looks like harmless duplication. The branch previously was setting up `testuser`/certs, but as of https://github.com/cockroachdb/cockroach/commit/fd6d12c728d9cfd54750383a74bb10680f8f4946 the test just uses the default user/certs created by the roachprod framework. I'll put out a quick fix.
