### ISSUE TITLE
stability: cockroach db leaks memory over long term (few days)

### ISSUE THREAD

**Issue by chandradeepak** [cockroachdb/cockroach#13333]
Is this a question, feature request, or bug report?
Bug report .

**QUESTION**

Have you checked our documentation at https://cockroachlabs.com/docs/? If you could not find an answer there, please consider asking your question in our community forum at https://forum.cockroachlabs.com/, as it would benefit other members of our community.

Prefer live chat? Message our engineers on our Gitter channel at https://gitter.im/cockroachdb/cockroach. 

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

3. Provide any additional detail on your proposed use case for this feature.

**BUG REPORT**

1. Please supply the header (i.e. the first few lines) of your most recent
   log file **for each node in your cluster**. On most unix-based systems
   running with defaults, this boils down to the output of

     grep -F '[config]' cockroach-data/logs/cockroach.INFO

   When log files are not available, supply the output of `cockroach version`
   and all flags/environment variables passed to `cockroach start` instead.

Attached are the logs of cockroach db.

I170131 22:38:29.630971 29 util/log/clog.go:899  [config] file created at: 2017/01/31 22:38:29
I170131 22:38:29.630971 29 util/log/clog.go:899  [config] running on machine: machine1
I170131 22:38:29.630971 29 util/log/clog.go:899  [config] binary: CockroachDB beta-20161201 (linux amd64, built 2016/12/01 18:32:34, go1.7.3)
I170131 22:38:29.630971 29 util/log/clog.go:899  [config] arguments: [/opt/appa/cockroach-beta-20161201.linux-amd64/cockroach start --host machine1 --store /var/lib/cockroach-data --http-host 127.0.0.1 --http-port 8181 --insecure --max-sql-memory 5GB --cache 5GB]

[logs.zip](https://github.com/cockroachdb/cockroach/files/743789/logs.zip)

2. Please describe the issue you observed:

- What did you do?
we are running cockroach db in 3 nodes.  Just started it and running for a few days . I have one table and we hardly do any queries on it.

- What did you expect to see?

I want the nodes to be stable not grow in memory .
- What did you see instead?

But they have high memory usage because of cockroach db running there. In all the 3 nodes.  This is making us restart nodes often which is limiting us severely.

This is a snapshot of the top command. 

 PID           USER      PR  NI    VIRT        RES         SHR     S      %CPU         %MEM      TIME+         COMMAND
104358 cockroa+  20   0    20.351g  0.013t    20256  S    71.1            44.0         7505:50     cockroach

**Comment by petermattis** [comment]
From the logs I see:

`I170201 02:59:45.509093 198 server/status/runtime.go:228  runtime stats: 13 GiB RSS, 112 goroutines, 100 MiB/117 MiB/280 MiB GO alloc/idle/total, 4.7 GiB/6.3 GiB CGO alloc/total, 3735.20cgo/sec, 0.23/0.02 %(u/s)time, 0.00 %gc (7x)`

This indicates that the Go portion of the process has 100MB of allocated memory while the C portion (i.e. RocksDB) has 4.7 GB. Both of these numbers match with expectations given your `--cache-size` setting of 5GB. Note that even when idle, Cockroach will tend to expand to consume idle memory for the cache. 

I don't have an explanation for the `0.013t` (13GB) RES number from top, but we can see it matches up with the `13 GiB RSS` in the log message. Looking through the provided logs, I see the RSS number slowly creeping up, but the value seems out of sync with the total memory in use by Go/C. We have long running test clusters which don't exhibit this growth, so I'm a bit perplexed as to what is going on. 

I'll spend a little more time spelunking your logs to see if I can find a culprit.

**Comment by chandradeepak** [comment]
thanks . But we have seen this growth happen all the time and got reproduced all the time.  Initially it is low but it slowly creeps up as you said typically over a week. only way we have to get rid of is to restart the cluster nodes. we have a 3 node cluster which exhibits this behavior. And in terms of operations we do on table is nothing.we haven't used it much lately. 

 Please let me know if you need any more logs which i can provide you with . 

Thanks for your support.

**Comment by chandradeepak** [comment]
Any update on this  ?

**Comment by petermattis** [comment]
I made one attempt to reproduce this last weekend and was unsuccessful. My RSS grew to slightly larger than the RocksDB cache size and then remained stable. Can you detail exactly what operations you performed since the cluster was created? Hard to see how that matters, but more info doesn't hurt.

Also, you're running on Linux while I did my test on Mac OS X. I'll try another attempt at reproduction on Linux.

**Comment by petermattis** [comment]
I ran a single-node cockroach cluster on a 8 cpu / 16 GB linux box. Over the course of 23 hours, the resident set size grew from 118 MiB to 317 MiB. But for me, this is entirely attributable to the growth in CGO memory usage (i.e. the RocksDB cache). Over that same time period, the RocksDB cache grew from 10 MiB to 206 MiB. This is despite the associated RocksDB sstable only being 7.4 MiB. I believe the cache growth is because RocksDB does not clear the cache of old sstables when they are merged.

The above doesn't explain what is going on for you, though. I'm going to continue poking at this.

**Comment by chandradeepak** [comment]
Hello petermattis, 
I guess this doesn't happen with a single node cluster and not definitely in one day . Our setup has a 3 node cluster and ran for one week before seeing the issue. But this is consistently reproduced in our clusters. Please let me know if you need any more logs from my side .

**Comment by petermattis** [comment]
I tested a 1 node cluster because it seems surprising that a 3 node cluster would be different. But since I can't reproduce the problem and clearly don't know what is going on, I'll try a 3 node cluster.

I'll also leave the cluster running for longer. I'll note that your logs show a steady growth in the delta between RSS and CGO total which I didn't see at all in my testing.

**Comment by petermattis** [comment]
@chandradeepak I've tried testing on a 3-node cluster and been unable to reproduce. Are you still seeing this problem? Much has changed in the system since you originally reported the issue and I'm wondering if you can reproduce on a recent beta.

**Comment by chandradeepak** [comment]
@petermattis Hi peter thanks for trying it again. we recently deployed a new 3 node cluster . we are using the latest version of cockroach there. so far we haven't seen growth like last time . But if it happens again i will report with logs.  But before closing the issue i am planning to wait couple of weeks to see the growth happens again since we have deployed it recently like 3 days before.

**Comment by petermattis** [comment]
@chandradeepak I've also been unable to reproduce.

Moving this issue to the 1.1 milestone. At some point we'll close it as unreproducible.

**Comment by chandradeepak** [comment]
Thanks @petermattis  for trying it out .  I guess with latest build i haven't seen any growth so far. I am closing the issue. will reopen it if i see any leak. 

Thanks for all your help on this .

**Comment by chandradeepak** [comment]
just an update i haven't seen the growth happening now after 20 days. i think it is safe to say there is no memory growth happening .  
Thanks for your help.

**Comment by petermattis** [comment]
Thanks for following up, @chandradeepak.
