### ISSUE TITLE
 cockroach: both branches of `if-else` are identical

### ISSUE THREAD

**Issue by chavacava** [cockroachdb/cockroach#133305]
Both branches of the following `if-else` are identical

https://github.com/cockroachdb/cockroach/blob/b7b76a1aed9fb67f3667f00c79355812525ae738/pkg/util/tracing/span_test.go#L938-L942

Found with [revive](https://github.com/mgechev/revive/)

Jira issue: CRDB-43538

**Comment by yuzefovich** [comment]
Thanks for the report! We'll fix it up shortly.
