### ISSUE TITLE
roachtest: disable perturbation metamorphic variant test assertions other than crash/runtime-invariant/tokens-returned

### ISSUE THREAD

**Issue by kvoli** [cockroachdb/cockroach#133450]
The `perturbation` tests perturb a cluster and then assert on the QoS during the perturbation and during the recovery.

For the metamorphic `perturbation` roachtest variations:

```
perturbation/metamorphic/addNode [kv]
perturbation/metamorphic/backfill [kv]
perturbation/metamorphic/decommission [kv]
perturbation/metamorphic/partition [kv]
perturbation/metamorphic/restart [kv]
perturbation/metamorphic/slowDisk [kv]
```

This proves problematic when certain spaces are reached for the metamorphic variable combinations, as no cluster could reasonably be expected to pass reliably, given our current (acknowledged) design.

https://github.com/cockroachdb/cockroach/blob/5e1ce54bba69fdf695c449920a86fbe6d3613440/pkg/cmd/roachtest/tests/admission_control_latency.go#L214-L216

This issue is to remove the metamorphic QoS assertions, or:
1. disable first and then
2. iron out the metamorphic assertions and state space constraints to the point where any KV team member could effectively triage the failure. And, agree that the test failing has high likelihood of: legitimate bug / edge case / unknown design issue / etc. which is currently not the case[^1]. i.e., make the investment vs payoff ratio more amenable.

xref:
- https://github.com/cockroachdb/cockroach/issues/133374
- https://github.com/cockroachdb/cockroach/issues/133001
- https://github.com/cockroachdb/cockroach/issues/133155
- https://github.com/cockroachdb/cockroach/issues/131822

[^1]: This is made slightly worse by virtue of timing w.r.t the 24.3 release, where failures must be inspected much more closely than otherwise.

Jira issue: CRDB-43627

**Comment by kvoli** [comment]
cc @andrewbaptist I think this is higher priority than any other related rac2 pod work you may be currently doing, could you have a read through the issue.

**Comment by andrewbaptist** [comment]
Done as part of #133667
