### ISSUE TITLE
distsql: support distributed aggregation by hash

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#13343]
We currently support aggregation (`GROUP BY`, or functions like `MAX`, `AVG`) with a distributed local stage and a non-distributed final stage:

![image](https://cloud.githubusercontent.com/assets/16544120/22517961/df942d1a-e878-11e6-9d23-cf13c705cce1.png)

In many cases, the final stage can be distributed by hash (we already do something very similar for joins).

**Comment by dianasaur323** [comment]
@RaduBerinde moving into 1.1 unless you disagree.

**Comment by RaduBerinde** [comment]
Fixed a while back in #15016 .
