### ISSUE TITLE
Sentry: mutation_builder.go:1365: should have found not null column in index
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/opt/op...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#133486]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/6020194536/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/6020194536/?referrer=webhooks_plugin)

Panic Message:

```
mutation_builder.go:1365: should have found not null column in index
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.findNotNullIndexCol
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/mutation_builder.go:1365
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*arbiterSet).ForEach.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/arbiter_set.go:126
  | github.com/cockroachdb/cockroach/pkg/util/intsets.Fast.ForEach
  | 	github.com/cockroachdb/cockroach/pkg/util/intsets/fast.go:154
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*arbiterSet).ForEach
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/arbiter_set.go:122
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*mutationBuilder).buildInputForUpsert
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/insert.go:778
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildInsert
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/insert.go:327
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmt.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:358
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).processWiths
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/with.go:116
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:357
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmtAtRootWithScope
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:290
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmtAtRoot
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:271
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).Build
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:250
  | github.com/cockroachdb/cockroach/pkg/sql.(*optPlanningCtx).buildReusableMemo
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:445
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).prepareUsingOptimizer
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:169
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).populatePrepared
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:339
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).prepare.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:277
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).prepare
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:282
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).addPreparedStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:116
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execPrepare
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:77
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2394
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2185
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:969
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommands
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:247
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).serveImpl.func3
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:1004
  | runtime.goexit
  | 	src/runtime/asm_arm64.s:1197
Wraps: (3) should have found not null column in index
Error types: (1) *assert.withAssertionFailure (2) *withstack.withStack (3) *errutil.leafError
-- report composition:
*errutil.leafError: should have found not null column in index
mutation_builder.go:1365: *withstack.withStack (top exception)
*assert.withAssertionFailure
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_arm64.s#L1196-L1198](src/runtime/asm_arm64.s#L1196-L1198)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/pgwire/server.go#L1003-L1005](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/pgwire/server.go#L1003-L1005)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/pgwire/conn.go#L246-L248](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/pgwire/conn.go#L246-L248)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/conn_executor.go#L968-L970](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/conn_executor.go#L968-L970)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/conn_executor.go#L2184-L2186](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/conn_executor.go#L2184-L2186)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/conn_executor.go#L2393-L2395](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/conn_executor.go#L2393-L2395)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/conn_executor_prepare.go#L76-L78](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/conn_executor_prepare.go#L76-L78)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/conn_executor_prepare.go#L115-L117](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/conn_executor_prepare.go#L115-L117)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/conn_executor_prepare.go#L281-L283](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/conn_executor_prepare.go#L281-L283)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/conn_executor_prepare.go#L276-L278](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/conn_executor_prepare.go#L276-L278)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/conn_executor_prepare.go#L338-L340](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/conn_executor_prepare.go#L338-L340)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/plan_opt.go#L168-L170](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/plan_opt.go#L168-L170)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/plan_opt.go#L444-L446](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/plan_opt.go#L444-L446)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/opt/optbuilder/builder.go#L249-L251](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/opt/optbuilder/builder.go#L249-L251)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/opt/optbuilder/builder.go#L270-L272](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/opt/optbuilder/builder.go#L270-L272)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/opt/optbuilder/builder.go#L289-L291](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/opt/optbuilder/builder.go#L289-L291)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/opt/optbuilder/builder.go#L356-L358](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/opt/optbuilder/builder.go#L356-L358)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/opt/optbuilder/with.go#L115-L117](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/opt/optbuilder/with.go#L115-L117)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/opt/optbuilder/builder.go#L357-L359](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/opt/optbuilder/builder.go#L357-L359)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/opt/optbuilder/insert.go#L326-L328](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/opt/optbuilder/insert.go#L326-L328)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/opt/optbuilder/insert.go#L777-L779](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/opt/optbuilder/insert.go#L777-L779)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/opt/optbuilder/arbiter_set.go#L121-L123](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/opt/optbuilder/arbiter_set.go#L121-L123)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/util/intsets/fast.go#L153-L155](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/util/intsets/fast.go#L153-L155)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/opt/optbuilder/arbiter_set.go#L125-L127](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/opt/optbuilder/arbiter_set.go#L125-L127)
[https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/opt/optbuilder/mutation_builder.go#L1364-L1366](https://github.com/cockroachdb/cockroach/blob/579c0a000fb80ef7184e46ea038937c135ee2f0c/pkg/sql/opt/optbuilder/mutation_builder.go#L1364-L1366)
</details>

```
src/runtime/asm_arm64.s in runtime.goexit at line 1197
pkg/sql/pgwire/server.go in pkg/sql/pgwire.(*Server).serveImpl.func3 at line 1004
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommands at line 247
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 969
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 2185
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 2394
pkg/sql/conn_executor_prepare.go in pkg/sql.(*connExecutor).execPrepare at line 77
pkg/sql/conn_executor_prepare.go in pkg/sql.(*connExecutor).addPreparedStmt at line 116
pkg/sql/conn_executor_prepare.go in pkg/sql.(*connExecutor).prepare at line 282
pkg/sql/conn_executor_prepare.go in pkg/sql.(*connExecutor).prepare.func2 at line 277
pkg/sql/conn_executor_prepare.go in pkg/sql.(*connExecutor).populatePrepared at line 339
pkg/sql/plan_opt.go in pkg/sql.(*planner).prepareUsingOptimizer at line 169
pkg/sql/plan_opt.go in pkg/sql.(*optPlanningCtx).buildReusableMemo at line 445
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).Build at line 250
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).buildStmtAtRoot at line 271
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).buildStmtAtRootWithScope at line 290
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).buildStmt at line 357
pkg/sql/opt/optbuilder/with.go in pkg/sql/opt/optbuilder.(*Builder).processWiths at line 116
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).buildStmt.func2 at line 358
pkg/sql/opt/optbuilder/insert.go in pkg/sql/opt/optbuilder.(*Builder).buildInsert at line 327
pkg/sql/opt/optbuilder/insert.go in pkg/sql/opt/optbuilder.(*mutationBuilder).buildInputForUpsert at line 778
pkg/sql/opt/optbuilder/arbiter_set.go in pkg/sql/opt/optbuilder.(*arbiterSet).ForEach at line 122
pkg/util/intsets/fast.go in pkg/util/intsets.Fast.ForEach at line 154
pkg/sql/opt/optbuilder/arbiter_set.go in pkg/sql/opt/optbuilder.(*arbiterSet).ForEach.func1 at line 126
pkg/sql/opt/optbuilder/mutation_builder.go in pkg/sql/opt/optbuilder.findNotNullIndexCol at line 1365
```

### Tags

| Tag | Value |
| --- | --- |
| Command | start-single-node |
| Environment | v23.2.9 |
| Go Version | go1.21.12 X:nocoverageredesign |
| Platform | linux arm64 |
| Distribution | CCL |
| Cockroach Release | v23.2.9 |
| Cockroach SHA | 579c0a000fb80ef7184e46ea038937c135ee2f0c |
| # of CPUs | 10 |
| # of Goroutines | 532 |

Jira issue: CRDB-43642

**Comment by yuzefovich** [comment]
unactionable
