### ISSUE TITLE
sql: RowFetcher batch limit calculation does not take into account column families

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#13346]
While investigating read performance on the `blocks` schema, I noticed that `ScanRequests` had an incorrectly set `MaxSpanRequestKeys` field. Given the table def:

```
	CREATE TABLE IF NOT EXISTS blocks (
	  block_id BIGINT NOT NULL,
	  writer_id STRING NOT NULL,
	  block_num BIGINT NOT NULL,
	  raw_bytes BYTES NOT NULL,
	  PRIMARY KEY (block_id, writer_id, block_num)
```

And the query:

```
SELECT writer_id, raw_bytes FROM blocks WHERE block_id >= $1 LIMIT 1
```

The `blocks` table has a single column family meaning there is a single key per row for the primary index. I would expect for this query that `MaxSpanRequestKeys` would be 1, but debug logs show it is set to 5. The code causing this is https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sqlbase/rowfetcher.go#L165-L178:

```
	firstBatchLimit := limitHint
	if firstBatchLimit != 0 {
		// For a secondary index, we have one key per row.
		if !rf.isSecondaryIndex {
			// We have a sentinel key per row plus at most one key per non-PK column. Of course, we
			// may have other keys due to a schema change, but this is only a hint.
			firstBatchLimit *= int64(1 + len(rf.cols) - len(rf.index.ColumnIDs))
		}
		// We need an extra key to make sure we form the last row.
		firstBatchLimit++
	}
```

For this query, `limitHint` is 2 (I'm not sure why it isn't one, but whatever). This is not a secondary index and there are 4 columns and 3 columns that are part of the index key. The math translates `(limitHint * (1 + 4 - 3)) + 1 == 5`. Seems like this math is not taking column families into account.

**Comment by petermattis** [comment]
@RaduBerinde You might be a better person to look at this than @danhhz. Seems like there is an easy fix here to make this code aware of column families. I'm curious what the `We need an extra key to make sure we form the last row` comment is about.

**Comment by RaduBerinde** [comment]
Ah, this is the code, it predates column families:
https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sqlbase/rowfetcher.go#L172

This row limit is another thing that would improve if we form rows inside KV (#13193).

**Comment by RaduBerinde** [comment]
>  I'm curious what the We need an extra key to make sure we form the last row comment is about.

The code that forms rows knows when a row is done when it hits a key that has another PK, eg:

```
/table/primary/1
/table/primary/1/col1
/table/primary/1/col2
/table/primary/2  // when processing this key, we form row 1
```

If we only need row 1 and we read exactly 3 keys, we won't form the row and that will result in asking for another batch.

The code could be improved to keep track of the columns received and complete the row as soon as all needed columns are seen.

**Comment by petermattis** [comment]
> If we only need row 1 and we read exactly 3 keys, we won't form the row and that will result in asking for another batch.
> 
> The code could be improved to keep track of the columns received and complete the row as soon as all needed columns are seen.

Ah, thanks for reminding me. I think I wrote that code. Yeah, deciding that the row is complete when we've received all of the needed columns seems like a straightforward change.

**Comment by danhhz** [comment]
Our columns (and column families) are sparse, so I'm not sure doing it based on seeing all the columns (or seeing all the families) works.

@petermattis Did you still intend that I pick this up? What's the priority? The fix seems pretty obvious, but I'd have to dig into how to add a test (since obviously nothing caught it when I missed this originally).

**Comment by petermattis** [comment]
> Did you still intend that I pick this up?

Yes. Or @RaduBerinde.

> What's the priority? 

Moderate. Doesn't seem too hard to fix so I don't want this to linger around.

> The fix seems pretty obvious, but I'd have to dig into how to add a test (since obviously nothing caught it when I missed this originally).

I'd restructure the code so there is a method on `TableDescriptor` that returns the number of keys to read for a row given an `IndexDescriptor`. That seems straightforward to unit test.
