### ISSUE TITLE
distsql: support outer joins

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#13342]
We support inner joins in distsql but not outer joins. We need to modify the HashJoiner and MergeJoiner to provide internal "merged" columns, similar to how `joinNode` does it. I can provide more context in-person if someone is interested in taking this on.

**Comment by rampage644** [comment]
I plan to implement those, if there is no objections.

**Comment by cuongdo** [comment]
cc @asubiotto

**Comment by asubiotto** [comment]
That would be great @rampage644, thank you!

**Comment by RaduBerinde** [comment]
One thing needs to be added to the joiners to implement this: the ability to output "merged" equality columns (see `numMergedEqualityColumns` in `joinPredicate`).
