### ISSUE TITLE
storage: remove unnecessary abort cache checks

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#13359]
We currently check the abort-cache to see if a transaction has been aborted on transactional reads and writes. This check involves a RocksDB read which is mildly expensive. For 1PC transactions this is unnecessary as there is no possibility of an abort-cache record. 

I'm not sure if there is a good signal whether a transactional read operation is the sole operation in a transaction. The existing `isOnePhaseCommit` method used on writes checks for a begin and end transaction request in the batch. But for a read-only transaction we never send a begin transaction. We might have to plumb down an additional signal in the `BatchRequest`, but that shouldn't be difficult.

Cc @bdarnell, @spencerkimball

**Comment by bdarnell** [comment]
Not just 1PC; abort-cache records are similarly impossible for multi-step read-only transactions. We don't need to start checking the abort cache until the transaction has attempted to perform a write; until then we're just performing reads at a given timestamp. (If a read/write transaction restarts, and the first thing it does on its second attempt is a read, does that read need to check the abort cache? I don't think so, but I'm not positive). 

I think we can limit the abort cache checks to A) write commands B) reads where the Transaction.Writing field is true C) BeginTransaction.

**Comment by petermattis** [comment]
> If a read/write transaction restarts, and the first thing it does on its second attempt is a read, does that read need to check the abort cache? I don't think so, but I'm not positive.

#2231 was the motivation for checking the abort cache on reads. It isn't strictly necessary, but we do so to avoid having an aborted transaction continue to successfully perform read operations. Seems safe to only do this check if `Transaction.Writing` is set. Am I missing anything here?

**Comment by spencerkimball** [comment]
Alternatively, there really will be only a handful of abort cache records at most. We could cache them in memory. This would save us on writes as well.

**Comment by bdarnell** [comment]
> Seems safe to only do this check if Transaction.Writing is set. Am I missing anything here?

Yeah, that's my thought as well.

> Alternatively, there really will be only a handful of abort cache records at most. 

[citation needed]

> We could cache them in memory. This would save us on writes as well.

The abort cache records on the range where the transaction record lives must be written to disk and persisted; this is necessary for correctness. We might be able to take a best-effort approach for other uses of the abort cache, but I think if we're going to allow this anomaly in some cases (whenever the in-memory record is lost), we might as well just skip the abort cache for reads entirely.

**Comment by petermattis** [comment]
> The abort cache records on the range where the transaction record lives must be written to disk and persisted; this is necessary for correctness. We might be able to take a best-effort approach for other uses of the abort cache, but I think if we're going to allow this anomaly in some cases (whenever the in-memory record is lost), we might as well just skip the abort cache for reads entirely.

I think @spencerkimball was suggesting that we both write the abort cache records to disk and cache them in memory. But I'm less certain that the number of abort cache records will be small in all workloads and that a non-RocksDB cache will be significantly faster than the existing checks.
