### ISSUE TITLE
sql: "soft" limit too pessimistic

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#13351]
`applyLimit` has the following code:

```
	case *scanNode:
		// Either a limitNode or EXPLAIN is pushing a limit down onto this
		// node. The special value math.MaxInt64 means "no limit".
		if !n.disableBatchLimits && numRows != math.MaxInt64 {
			n.limitHint = numRows
			// If we have a filter, some of the rows we retrieve may not pass the
			// filter so the limit becomes "soft".
			n.limitSoft = soft || !isFilterTrue(n.filter)
		}
```

Consider this query on the block_writer table:

```
SELECT * FROM datablocks.blocks WHERE block_id >= $1 LIMIT 1
```

When `id` is a prefix of the primary key, we know that exactly the keys we're scanning are the ones matching the filter. For some reason, we're computing `!isFilterTrue(n.filter)` as true which in turn is causing the limit to be marked as "soft". The soft limit causes the row fetching code to double the number of rows fetched initially.

@knz Please reassign if there is someone more appropriate to look at this.

**Comment by knz** [comment]
This (mis)feature was there forever. I'm trying to extend the index constraint propagation to make it go away. stay tuned
