### ISSUE TITLE
cli/sql: implement a mode where query results are streamed to the output

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#13362]
Currently the client *always* buffers the results in memory even when the output format does not strictly require it (i.e. anything else than `pretty`). 

It would be useful to redesign the process query-format-print to become a pipeline instead of a sequence.

**Comment by richardartoul** [comment]
Hey Knz,

Could I take a stab at this? I think I found the relevant code in the CLI and it seems like a good way to introduce myself to this codebase.

My guess is that I need to modify the sqlRowsToStrings and printQueryOutput functions in the CLI to stream rows to the formatters instead of passing them all at once. Sound about right?

**Comment by knz** [comment]
Yes, that's correct.

**Comment by knz** [comment]
Feel free to give this a shot!

**Comment by andreimatei** [comment]
Just a random question - we didn't do anything here to stop buffering _at the server_, did at? In case I missed something big.

**Comment by richardartoul** [comment]
@andreimatei I dont think so. I modified the functions that handle converting rows to strings, formatting them, and then printing them to instead accept an iterator, but this is all CLI code.

Thus if somewhere in the CLI code you have rows that are already buffered in memory, you can wrap them in an iterator and print them like normal. If they haven't been "consumed" from the server yet (by repeatedly calling Next()) then the formatter can handle calling that for you and print the results as they get back from the server.

Buffering at the server level should be unaffected.

**Comment by andreimatei** [comment]
Thanks Richard, that's what I thought. Thanks for your contribution!
We also buffer at the server; we need to do something about that. Unfortunately I'm not sure what the implications with the pgwire protocol are.

**Comment by petermattis** [comment]
> We also buffer at the server; we need to do something about that. Unfortunately I'm not sure what the implications with the pgwire protocol are.

I believe there are no implications, but the server-side changes to accomplish this are non-trivial.

**Comment by andreimatei** [comment]
@petermattis Can errors be passed inline with the results?

**Comment by petermattis** [comment]
@andreimatei Not "inline", but I believe you can return results and, when the first error is encountered, return that error.
