### ISSUE TITLE
kv: refresh tests for leader leases

### ISSUE THREAD

**Issue by arulajmani** [cockroachdb/cockroach#133763]
**Describe the problem**

Most of our tests don't care which leasing protocol they're run under. As such, using a metamorphic constant for `RaftLeaderFortificationFractionEnabled` should give us the coverage we need.

However, there are a bunch of tests that are closely coupled to the underlying leasing protocol, in most cases epoch based leases. For such tests, we should create a leader lease specific variant. https://github.com/cockroachdb/cockroach/pull/133509 is an example of one such effort. This issue captures (currently non-exhaustive) list of tests that need refreshing:

- [x] `TestRequestsOnLaggingReplica` @arulajmani 
- [x] `TestRaftCheckQuorum` @arulajmani 
- [x] `TestProcessSplitAfterRightHandSideHasBeenRemoved` @iskettaneh 
- [x] `TestLeaseExpirationBelowFutureTimeRequest` @miraradeva 
- [x] `TestSnapshotAfterTruncation` @miraradeva 
- [x] `TestRangefeedCheckpointsRecoverFromLeaseExpiration` @miraradeva 
- [x] `TestRaftUnquiesceLeaderNoProposal` @miraradeva 
- [x] `TestLeaseRenewer` @miraradeva 
- [x] `TestGetChecksumNotSuccessfulExitConditions` @arulajmani 
- [x] `TestLeaseQueueExpirationLeasesOnly` @arulajmani 
- [x] `TestLeaseQueueSwitchesLeaseType` @arulajmani 
- [x] `TestLeaseMetricsOnSplitAndTransfer` @arulajmani 
- [x] `TestSnapshotAfterTruncationWithUncommittedTail` @arulajmani 
- [x] `TestRaftPreVote` @arulajmani 
- [x] `TestReplicateRestartAfterTruncationWithRemoveAndReAdd` @arulajmani 
- [x] `TestReplicateRestartAfterTruncation` @arulajmani 
- [x] `TestQuotaPool` @arulajmani 
- [x] `TestStoreRangeLease` @arulajmani 
- [x] `TestFlowControlAdmissionPostSplitMergeV2` @arulajmani 
- [x] `TestFlowControlCrashedNodeV2` @arulajmani 
- [x]  `TestFlowControlCrashedNode` @arulajmani 
- [x]  `TestFlowControlRaftSnapshot` @arulajmani 
- [x] `TestFlowControlRaftSnapshotV2` @arulajmani 
- [x] `TestFlowControlRaftMembershipV2` @arulajmani 
- [x] `TestFlowControlUnquiescedRangeV2` @arulajmani 
- [x] `TestFlowControlUnquiescedRange` @arulajmani 
- [x] `TestFlowControlSendQueue` @arulajmani 
- [x] `TestFlowControlRepeatedlySwitchMode` @arulajmani 
- [x] `TestFlowControlRaftTransportBreak` @arulajmani 
- [x] `TestFlowControlAdmissionPostSplitMergeV2` @arulajmani 
- [x] `TestFlowControlV1ToV2Transition` @arulajmani 
- [x] `TestFlowControlQuiescedRange` @arulajmani 
- [x] `TestStoreLoadReplicaQuiescent` @arulajmani 
- [x] `TestReplicaCircuitBreaker_ExemptRequests` @iskettaneh 
- [x] `TestReplicaCircuitBreaker_Partial_Retry` @iskettaneh 
- [x] `TestLeaseTransfersUseExpirationLeasesAndBumpToEpochBasedOnes` @arulajmani 
- [x] `TestLeaseRequestBumpsEpoch` @arulajmani 
- [x] `TestLeaseRequestFromExpirationToEpochDoesNotRegressExpiration` @iskettaneh 
- [x] `TestTransferRaftLeadership` @iskettaneh 
- [x] `TestRangeQuiescence` @arulajmani 
- [x] `TestStoreRangeMergeTimestampCacheCausality` @arulajmani 
- [x] `TestUninitializedReplicaRemainsQuiesced` @arulajmani 
- [x] `TestRevertToEpochIfTooManyRanges` @arulajmani 
- [x] `TestReplicaLeaseCounters` @arulajmani 
- [x] `TestNodeLivenessInitialIncrement` @arulajmani 
- [x] `TestRaftLeaderRemovesItself` @arulajmani 
- [x] `TestRequestsOnFollowerWithNonLiveLeaseholder` @arulajmani 
- [x] `TestRaftPreVoteUnquiesceDeadLeader` @arulajmani 
- [x] `TestNodeLivenessRetryAmbiguousResultOnCreateError/result_is_ambiguous` @arulajmani 
- [x] `TestReplicaRefreshPendingCommandsTicks` @arulajmani 
- [x] `TestWedgedReplicaDetection` @arulajmani 
- [x] `TestLogGrowthWhenRefreshingPendingCommands` @arulajmani 
- [x] `TestReplicaTombstone` @iskettaneh 
- [x] `TestLeaderAfterSplit` @arulajmani 
- [x] `TestRaftLogQueue` @arulajmani 
- [x] `TestRaftTracing` @arulajmani 
- [x] `TestCrashWhileTruncatingSideloadedEntries` @arulajmani 
- [x] `TestNodeLivenessNoRetryOnAmbiguousResultCausedByCancellation` @arulajmani 
- [x] `TestFindUpdateRaft` @iskettaneh 
- [x] `TestFindUpdateDescriptor` @iskettaneh 
- [x] `TestLeaseholderRelocate` @iskettaneh 

Tests that are going to require a big push to change:
- [ ] `TestStoreRangeMergeAbandonedFollowersAutomaticallyGarbageCollected` @arulajmani 
- [ ]  `TestElectionAfterRestart` @arulajmani 
- [ ] `TestLossOfQuorumRecovery`  @iskettaneh 
- [ ]  `TestRetrieveApplyStatus` @iskettaneh
- [ ] `TestStoreRangeMergeTimestampCache`
- [ ] `TestTransactionUnexpectedlyCommitted`

Note that for some of these tests, we need https://github.com/cockroachdb/cockroach/pull/133353 to make sure the test is actually using leader leases and not fooling itself to reproduce. 

Jira issue: CRDB-43739

Epic CRDB-42947

**Comment by arulajmani** [comment]
`TestLeaseExpirationBelowFutureTimeRequest` seems to be setting up a scratch range with expiration based leases:

https://github.com/cockroachdb/cockroach/blob/c83c57d354741ac36740894f7387c014eb6c09fe/pkg/kv/kvserver/client_replica_test.go#L1470

It then makes use of this expiration to figure out what the timestamp of the future time request should be. I don't see much point in moving this to use leader leases; it was written using expiration based leases for a good reason.

**Comment by miraradeva** [comment]
`TestLeaseExpirationBelowFutureTimeRequest` is stressing well after the Raft commit from https://github.com/cockroachdb/cockroach/pull/135707. I'll mark it as done.

**Comment by arulajmani** [comment]
`TestGetChecksumNotSuccessfulExitConditions` seems like a false alarm. I'll check it off.

**Comment by arulajmani** [comment]
Shouldn't have been closed by whichever linked PR did this.

**Comment by arulajmani** [comment]
`TestReplicaLeaseCounters` seems to be a false alarm -- stressing fine, I'll check if off.

**Comment by arulajmani** [comment]
`TestNodeLivenessRetryAmbiguousResultOnCreateError` was also addressed by https://github.com/cockroachdb/cockroach/pull/136374 (confirmed it). I'll check it off.

**Comment by arulajmani** [comment]
`TestElectionAfterRestart` fails because an election is triggered after a timeout (which the test doesn't expect). This doesn't work well with leader leases, as we won't campaign unless we have StoreLiveness support. Request for StoreLiveness support is kicked off the very first time we call an election (which, as a result, is guaranteed to fail). I'm not sure what the best way to fix this test is.

**Comment by arulajmani** [comment]
All the tests that haven't been checked on this issue are covered by https://github.com/cockroachdb/cockroach/issues/136806. Thanks for the efforts on this on @iskettaneh and @miraradeva! 🚀
