### ISSUE TITLE
perf: investigate if our "key" overhead has a performance impact on writes

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#13392]
We have a 3 key overhead when applying a write operation. For any `BatchRequest` that contains a write operation we also write the keys:
* `/Local/RangeID/<id>/r/RaftAppliedIndex`
* `/Local/RangeID/<id>/r/LeaseAppliedIndex`
* `/Local/RangeID/<id>/r/RangeStats`

Since these keys are all written in the same batch using keys derived from the same range ID and they are all read at the same time, it is feasible to combine their state into a single key. An initial hacky experiment to see if this would provide any performance benefit failed (no noticeable benefit), but we should pay attention to the overhead here. The space consideration is minimal, but each key needs a separate entry in the RocksDB MemTable.

**Comment by petermattis** [comment]
Very strange. I did another experiment where I folded `{Raft,Lease}AppliedIndex` into `MVCCStats` (via 2 new fields) and performance got marginally worse. That doesn't make sense.

**Comment by petermattis** [comment]
A stray `log.Infof` in `applyRaftCommand` was the source of the slowdown. Fixing that and my experiment shows a 4% speedup from folding `{Raft,Lease}AppliedIndex` into `MVCCStats`. Doing this for real would require some sort of migration. I think I'll leave this on the back burner for now.

**Comment by petermattis** [comment]
Along with folding `{Raft,Lease}AppliedIndex` into `MVCCStats`, we should switch to using `MVCCRangeStats` which uses variable width encodings for most of the fields. See https://github.com/cockroachdb/cockroach/issues/18659#issuecomment-331316365:

> MVCCStats as stored under /Local/RangeID/X/r/RangeStats is a below-raft proto because we need to ensure that the value for that key is identical on all replicas for the consistency checker. This complicates changing MVCCStats but does not prohibit it. For example, we could rename the existing MVCCStats to MVCCLegacyStats and create a new MVCCStats proto with parallel fields, perhaps encoded differently, perhaps with additional fields. And then we'd have to enhance the consistency checker so that it translated from MVCCStats to MVCCLegacyStats before computing the checksum. This would require a small bit of special casing in Replica.sha512. For migration, it would probably also be necessary to translate the stats when sending a snapshot. The high-level idea is that the format as seen by the consistency checker and in snapshots is more or less frozen, but that still gives us a small bit of wiggle room

**Comment by nvanbenschoten** [comment]
I’m at a loss. Any idea what the new key here should be called? `AppliedIndicesAndStatsKey`? `AppliedMetaKey`? `AppliedStateKey`? Naming truly is the hardest part of computer science.

Also, I think you meant `MVCCNetworkStats`, not `MVCCRangeStats`. We could rename the proto since we're now going to be persisting it outside of Raft entries, but that's not a big deal.

**Comment by petermattis** [comment]
I think I wrote the above before `MVCCNetworkStats` existed. I don't know what to name this key either.

**Comment by nvanbenschoten** [comment]
I have https://github.com/cockroachdb/cockroach/pull/22317 working with the second option discussed [here](https://github.com/cockroachdb/cockroach/pull/22317#issuecomment-363594994), but this change is too large and too risky to cherry-pick in to 2.0. Moving to 2.1 where it can be introduced early in the engineering cycle.
