### ISSUE TITLE
Sentry: receiver.go:271: log.Fatal: expected closed timestamp side-transport message with sequence number 1590654, got 1590653 (1) attached stack trace   -- stack trace:   | github.com/cockroachdb/coc...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#133999]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/6034269021/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/6034269021/?referrer=webhooks_plugin)

Panic Message:

```
receiver.go:271: log.Fatal: expected closed timestamp side-transport message with sequence number 1590654, got 1590653
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/closedts/sidetransport.(*incomingStream).processUpdate
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/closedts/sidetransport/receiver.go:271
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/closedts/sidetransport.(*incomingStream).Run.func1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/closedts/sidetransport/receiver.go:332
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:485
  | runtime.goexit
  | 	src/runtime/asm_amd64.s:1695
Wraps: (2) log.Fatal: expected closed timestamp side-transport message with sequence number 1590654, got 1590653
Error types: (1) *withstack.withStack (2) *errutil.leafError
-- report composition:
*errutil.leafError: log.Fatal: expected closed timestamp side-transport message with sequence number 1590654, got 1590653
receiver.go:271: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_amd64.s#L1694-L1696](src/runtime/asm_amd64.s#L1694-L1696)
[https://github.com/cockroachdb/cockroach/blob/8fb18e7ae08fdd481b959f74330e273a2500e1df/pkg/util/stop/stopper.go#L484-L486](https://github.com/cockroachdb/cockroach/blob/8fb18e7ae08fdd481b959f74330e273a2500e1df/pkg/util/stop/stopper.go#L484-L486)
[https://github.com/cockroachdb/cockroach/blob/8fb18e7ae08fdd481b959f74330e273a2500e1df/pkg/kv/kvserver/closedts/sidetransport/receiver.go#L331-L333](https://github.com/cockroachdb/cockroach/blob/8fb18e7ae08fdd481b959f74330e273a2500e1df/pkg/kv/kvserver/closedts/sidetransport/receiver.go#L331-L333)
[https://github.com/cockroachdb/cockroach/blob/8fb18e7ae08fdd481b959f74330e273a2500e1df/pkg/kv/kvserver/closedts/sidetransport/receiver.go#L270-L272](https://github.com/cockroachdb/cockroach/blob/8fb18e7ae08fdd481b959f74330e273a2500e1df/pkg/kv/kvserver/closedts/sidetransport/receiver.go#L270-L272)
</details>

```
src/runtime/asm_amd64.s in runtime.goexit at line 1695
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 485
pkg/kv/kvserver/closedts/sidetransport/receiver.go in pkg/kv/kvserver/closedts/sidetransport.(*incomingStream).Run.func1 at line 332
pkg/kv/kvserver/closedts/sidetransport/receiver.go in pkg/kv/kvserver/closedts/sidetransport.(*incomingStream).processUpdate at line 271
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v24.2.2 |
| Go Version | go1.22.5 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v24.2.2 |
| Cockroach SHA | 8fb18e7ae08fdd481b959f74330e273a2500e1df |
| # of CPUs | 4 |
| # of Goroutines | 492 |

Jira issue: CRDB-43857

**Comment by yuzefovich** [comment]
unactionable
