### ISSUE TITLE
util/stop: remove calls to caller.Lookup

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#13415]
`Stopper.{RunTask,RunTaskWithErr,RunAsyncTask,RunLimitedAsyncTask` make a call to `caller.Lookup` in order to maintain a map of tasks started per callsite. The calls to `caller.Lookup` show up in profiles (via calls to `runtime.Caller`). There are currently 45 non-test uses of these methods.

Is there value in maintaining the tasks-by-callsite map? I rarely (never) use it. If there is value and we want to keep it, we could use an approach similar to `context.WithValue` where the caller passes in a unique key per callsite which we'd use to lookup cached information about the callsite file and line number.

**Comment by bdarnell** [comment]
This is mainly used to diagnose "which tasks are keeping the stopper from closing". I've only rarely found it useful, and then only in tests and not production. I'd support making this opt-in in some way.

**Comment by tschottdorf** [comment]
It does do this:

![image](https://cloud.githubusercontent.com/assets/5076964/26435025/44753e7c-40da-11e7-8713-11c662586917.png)

Probably not worth spending time on, though.

**Comment by petermattis** [comment]
Where is that screenshot from?

**Comment by tschottdorf** [comment]
That's lightstep. I think (?) we use the lookup there somewhere. Or it's just a coincidence. Either way, not terribly important.

**Comment by petermattis** [comment]
Ah, yes. We call `tracing.ForkCtxSpan` and pass in the `taskKey` in `Run{,Limited}AsyncTask`. Should probably pass in a string to those methods.
