### ISSUE TITLE
kvserver: trying to remove a replica that doesn't exist:

### ISSUE THREAD

**Issue by shailendra-patel** [cockroachdb/cockroach#134198]
On `drt-scale` 150 node cluster hit an unexpected error. The issue occurred during tpcc import of 420K warehouses.

```
trying to remove a replica that doesn't exist: {ChangeType:REMOVE_VOTER Target:n102,s407}
HINT: ‹You have encountered an unexpected error.›

‹Please check the public issue tracker to check whether this problem is›
‹already tracked. If you cannot find it there, please report the error›
‹with details by creating a new issue.›

‹If you would rather not post publicly, please contact us directly›
‹using the support form.›

‹We appreciate your feedback.›
```
[Datadog error link](https://us5.datadoghq.com/logs?query=status%3Aerror%20cluster%3Adrt-scale%20%22trying%20to%20remove%20a%20replica%20that%20doesn%27t%20exist%22&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=paused&storage=flex_tier&stream_sort=time%2Casc&viz=stream&from_ts=1730637691705&to_ts=1730706364215&live=false).

Jira issue: CRDB-43976

Epic CRDB-44205

**Comment by arulajmani** [comment]
There are known races which can lead to this, and this is benign. Instead of rehashing this, I'll link @kvoli's comment here instead and close this out.

https://github.com/cockroachdb/cockroach/issues/134795#issuecomment-2479344245

**Comment by andrewbaptist** [comment]
We may want to change the error message if they can sometimes occur. Currently it says "You have encountered an unexpected error" when in fact this is expected in overloaded situations.

**Comment by arulajmani** [comment]
Yeah, agreed. There's some talk about this on https://github.com/cockroachdb/cockroach/issues/134412 and I think this should be as simple as not marking these as `AssertionFailed` errors.
