### ISSUE TITLE
sql: speed up sorting when the input is partially sorted

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#13413]
Discussed on slack:

> @knz what we could do too is perhaps implement an extension to sorting to do "batch sorting" -- if sorting is requested on columns a,b,c and the source provides data in order a,b, collect the batches of rows for each value of (a,b) and sort on the remaining column c.
> @RaduBerinde yes, that would be a big improvement [...] The distsql sorter already does that though

The TODO was already in the code:

```
// TODO(andrei): If we're scanning an index with a prefix matching an
// ordering prefix, we should only accumulate values for equal fields
// in this prefix, then sort the accumulated chunk and output.
// TODO(irfansharif): matching column ordering speed-ups from distsql,
// when implemented, could be repurposed and used here.
```

**Comment by RaduBerinde** [comment]
A note that in this case, we should also propagate a soft limit through the sort node. We may need to re-propagate limits after index selection if we don't already

**Comment by jordanlewis** [comment]
I think this exists in DistSQL, so I'm going to close this issue. We're not going to backport optimizations into local SQL.
