### ISSUE TITLE
observability: dbconsole database page loading issue.

### ISSUE THREAD

**Issue by shailendra-patel** [cockroachdb/cockroach#134196]
When opening the [database page ](https://drt-scale-0015.drt.crdb.io:26258/#/databases?page=1&pageSize=10&sortField=name&sortOrder=asc)from the dbconsole on the `drt-scale `150-node cluster, the page initially appears zoomed out while the data is being loaded. Once the loading completes, the page resizes to fit the normal browser page size.

https://github.com/user-attachments/assets/f8e89c7d-c8df-475d-996c-6834dae59864

Jira issue: CRDB-43975

**Comment by xinhaoz** [comment]
This was closed by https://github.com/cockroachdb/cockroach/pull/133375/commits which was backported to 24.3. Closing.
