### ISSUE TITLE
kv: seeing "checksum computation failed: context canceled" error message in drt-scale cluster

### ISSUE THREAD

**Issue by nameisbhaskar** [cockroachdb/cockroach#134210]
We are seeing the following continuous error message in the `drt-scale` cluster:
```
checksum computation failed: context canceled
```
Datadog link - https://us5.datadoghq.com/logs?query=cluster%3Adrt-scale%20status%3Aerror%20%22checksum%20computation%20failed%3A%20context%20canceled%22&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&event=AgAAAZL3n9oao4xdjQAAAAAAAAAYAAAAAEFaTDNuOW9hQUFDVDZVRllPOWczdHdDMwAAACQAAAAAMDE5MmY3YTAtYWM5ZS00MmI5LTk1NjYtMDUyN2Q3OTc5OGI5&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=flex_tier&stream_sort=time%2Casc&viz=stream&from_ts=1730726863844&to_ts=1730727763844&live=true

Jira issue: CRDB-43978

Epic CRDB-44205

**Comment by arulajmani** [comment]
The datadog link isn't working for me (maybe we no longer have access to the logs). However, this is likely because of overload, especially given the fact that we know this cluster was incredibly overloaded around this time. I'll close it out.

**Comment by dshjoshi** [comment]
Adding this for artifact recording purpose (as the issue has been already closed). The screen capture of the DD log (when you follow the DD link provided  in the issue description.
<img width="822" alt="Screenshot 2024-12-02 at 11 08 55 AM" src="https://github.com/user-attachments/assets/85bcd748-1fe3-4a4b-b1fc-b461b161e3c9">
