### ISSUE TITLE
pkg/cli: tsdump command fails is the DD_SITE is set incorrectly

### ISSUE THREAD

**Issue by arjunmahishi** [cockroachdb/cockroach#134292]
**Describe the problem**

The `tsdump` command fails if the `DD_SITE` is set incorrectly. I think this change was made as a part of the efforts to upload the tsdump to datadog. Ideally, this check should only happen if the `--format` is `datadog`. 

The check is happening here: https://github.com/cockroachdb/cockroach/blob/6d792725ebcbb766255fc5561a465b997bfc390e/pkg/cli/tsdump.go#L81-L85

**To Reproduce**

Run the `tsdump` command without setting the `DD_SITE` env variable.

**Environment:**
 - CockroachDB version - `24.3`

**Additional context**

This was caught as a part of the 150 node cluster testing.

Jira issue: CRDB-44004

**Comment by vidit-bhat** [comment]
To add a bit more context I ran `./cockroach debug tsdump --format=raw --certs-dir ./certs --from="$(date +'%Y-%m-%d %H:%M:%S' -d 'yesterday')" --to="$(date +'%Y-%m-%d %H:%M:%S')" > ./tsdumps/$(date +%Y_%m_%d_%H_%M_%S).gob` and got

```
ERROR: unsupported datadog site 'us5.datadoghq.com'
Failed running "debug tsdump"
```

The environment variable `DD_SITE` was set
```
ubuntu@drt-scale-0001:~$ echo $DD_SITE 
us5.datadoghq.com
```
