### ISSUE TITLE
sql: unknown protocol version 0

### ISSUE THREAD

**Issue by vidit-bhat** [cockroachdb/cockroach#134293]
On `drt-scale` cluster we see quite a few error logs `serving SQL client conn: unknown protocol version 0`. The PG protocol version is at 3. 

[Datadog link](https://us5.datadoghq.com/logs?query=status%3Aerror%20cluster%3Adrt-scale%20%22serving%20SQL%20client%20conn%3A%20unknown%20protocol%20version%22&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=paused&storage=flex_tier&stream_sort=time%2Casc&viz=stream&from_ts=1730685981171&to_ts=1730806574000&live=false)

Related slack thread: https://cockroachlabs.slack.com/archives/C07HPMBLVJ7/p1730785914749999

Jira issue: CRDB-44005

**Comment by rafiss** [comment]
Unfortunately we didn't have time to investigate this earlier and the logs are gone now. As far as I know this can only happen if an invalid client connected to the cluster, or maybe if a normal client connected but then dropped the connection during the initial handshake.
