### ISSUE TITLE
ui: show graph of the number of outstanding requests on main cluster page

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#13435]
It will be nice to visualize SQL requests getting queued up because of a problem. A count of the number of outstanding requests is valuable.

**Comment by kuanluo** [comment]
@vivekmenezes Just to clarify - are you think about a current number in the summary bar, or a graph of the numbers documenting historical numbers?

**Comment by vivekmenezes** [comment]
I'm thinking of a current number in the summary bar, although seeing that historically is also useful to understand when a cluster was wedged. Its important enough to be reflected in the summary. I think having an average/median time since started is also useful to better understand how long the queries have been executing for.

**Comment by kuanluo** [comment]
Having both in the summary make sense to me. 

@mrtracy Curious if generating one (or separate) graph to show 1) numbers of requested getting queued up and 2) avg/median time queries have been executing for would be better/a lot more work.

**Comment by dianasaur323** [comment]
moving to 1.1 unless you disagree

**Comment by dianasaur323** [comment]
An interesting metric that we should consider including in the cluster viz. @josueeee. Moving to 1.2 so that it gets incorporated into that design project.

**Comment by jordanlewis** [comment]
We don't really have a well-defined concept of "outstanding SQL requests" besides just the graph of active queries, which we have separately. We also have graphs that show the count of distsql flows in the system which is a somewhat relevant quantity.

I'll close this for now, but if there's something specific we were looking for here that I am missing please feel free to reopen.
