### ISSUE TITLE
util/log: AmbientContext.AnnotateCtx is allocation heavy

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#13438]
In a simple write-only workload (`loadgen/kv`), `AmbientContext.AnnotateCtx` is responsible for ~6.5% of the total allocations. Unfortunately, this code is tuned and inspection doesn't reveal any easy fixes. The allocations all come out of `augmentTagChain`. We take the fast-path ~2/3 of the time which performs a single `context.WithValue`. And the other 1/3 of the time we take the slow-path which involves merging with the existing tag chain. The fast-path, despite being used 2/3 of the time, consumes 1/3 of the allocations. 

I'm not sure what can be done here with the constraints of `context.Context`. A radical thought is to provide our own `Context` struct that is passed by value and internally contains a `context.Context` and a tag chain.

**Comment by RaduBerinde** [comment]
Another possible optimization is if a good fraction of the cases we are annotating a background / TODO (we could cache a Context for that case and reuse it); I don't have an idea if that's the case.

**Comment by petermattis** [comment]
Let me check. I would guess a significant fraction are coming out of gRPC callbacks.

**Comment by petermattis** [comment]
`go tool pprof` to the rescue. This is from a heap profile, generated using `peek AmbientContext.*AnnotateCtx` with a small bit of hand formatting to fit your screen. I then manually checked what type of context was being annotated at each call site and starred the ones that are using `context.{TODO,Background}`. 

```
--------------+-------------
 calls calls% +   context
--------------+-------------
190798 22.64% |   storage.(*Replica).Send
117143 13.90% |   storage.(*Store).AnnotateCtx
 94991 11.27% | * storage.(*Replica).FirstIndex
 86669 10.28% | * storage.(*Replica).withRaftGroupLocked
 78120  9.27% |   kv.(*DistSender).Send
 75193  8.92% |   server.(*Node).AnnotateCtx
 37000  4.39% | * storage.defaultSubmitProposalLocked
 35448  4.21% | * storage.(*baseQueue).processReplica
 35407  4.20% | * sql.(*Executor).AnnotateCtx
 32172  3.82% | * storage.(*baseQueue).maybeAddToPurgatory.func2.1
 25974  3.08% | * storage.(*Replica).handleRaftReadyRaftMuLocked
 18942  2.25% | * storage.(*baseQueue).MaybeAdd
  5929   0.7% | * storage.(*Replica).maybeQuiesceLocked
  5845  0.69% | * storage.(*Replica).quiesceLocked
  3282  0.39% | * storage.(*baseQueue).processLoop.func1.2
845862  6.71% |   util/log.(*AmbientContext).AnnotateCtx
```

As you can see, there are a significant number: 45% of the total. The optimization to cache annotated `context.{TODO,Background}` contexts seems easy and impactful. I'm going to take a whack at it.

**Comment by RaduBerinde** [comment]
I remember starting out with something like that but it was getting too confusing (AmbientContext was supposed to replace stored Contexts but it was storing a Context). I think now that we're more comfortable with the semantics of AmbientContext it won't be a problem anymore, and it shouldn't be visible in the interface.

**Comment by petermattis** [comment]
Yes, the `AmbientContext` interface remains unchanged. I'll send out a PR shortly. Unfortunately this doesn't result in a 45% reduction in allocations because `baseQueue` has fun code like: 

```
	ctx := repl.AnnotateCtx(bq.AnnotateCtx(context.TODO()))
```

**Comment by knz** [comment]
cc @nvanbenschoten for prioritization

**Comment by nvanbenschoten** [comment]
Closing as this no longer shows up prominently on memory profiles.
