### ISSUE TITLE
kvserver: unavailable ranges on drt-scale.

### ISSUE THREAD

**Issue by shailendra-patel** [cockroachdb/cockroach#134394]
On `drt-scale` cluster the dbconsole shown unavailable and underreplicated ranges. All the problematic ranges are from the same node i.e. `node 43`

At `Nov 05, 2024 at 3:25:00 UTC` we started seeing this issue. See attachment[1]
At the same time we started seeing error in lease transfer queue. See attachment[2]

While looking at the one of the problem ranges from dbconsole it looked available but reported unavailable. See attachment[3]

At the time of this behaviour we are seeing following error logs: [Datadog dashboard link](https://us5.datadoghq.com/logs?query=cluster%3Adrt-scale%20host%3Adrt-scale-0043%20-%22background%20error%3A%20pebble%3A%20compaction%20cancelled%20by%20a%20concurrent%20operation%2C%20will%20retry%20compaction%22%20-status%3A%28info%20OR%20warn%29&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=paused&storage=flex_tier&stream_sort=time%2Casc&viz=stream&from_ts=1730777100000&to_ts=1730783220000&live=false).
```
[NotLeaseHolderError] ‹failed to manipulate liveness record: liveness record changed while incrementing epoch for liveness(nid:18 epo:1 exp:1730778011.520588940,0); actual is liveness(nid:18 epo:1 exp:1730778017.520550335,0); is the node still live?›; r564688: replica (n43,s172):6VOTER_INCOMING not lease holder; lease holder unknown
```

There could be two possibility:
1. Dbconsole reported wrong metric as unavailable ranges while the ranges are available.
2. This could be a similar issue of slow gossip callback processing as mentioned [on this page](https://cockroachlabs.atlassian.net/wiki/spaces/TS/pages/3667853374/2024-06-03+RCA+on+DoorDash+--+Ranges+unavailable+during+upgrade+21863).

**Restarting the node fixed the issue.** But we want to understand what happened here and is there a possibility of bug.

**Attachment 1**
<img width="1015" alt="Screenshot 2024-11-06 at 3 19 56 PM" src="https://github.com/user-attachments/assets/7a56507f-8c08-4f18-8db0-c482a168f43a">

**Attachment 2**
<img width="1037" alt="Screenshot 2024-11-06 at 3 22 36 PM" src="https://github.com/user-attachments/assets/c0cf50a3-61ef-49d0-86fb-1d84a181bffc">

**Attachment 3**
<img width="1579" alt="Screenshot 2024-11-05 at 10 07 43 AM" src="https://github.com/user-attachments/assets/088445ce-98f4-4b31-809c-49715088866f">

Jira issue: CRDB-44051

**Comment by shailendra-patel** [comment]
On `Nov 07, 2024 at 6:25:30 UTC`, we have again observed `unavailable` and `underreplicated` ranges on `drt-scale` cluster. The problematic ranges were coming from one specific node i.e `node 75`.

The timeline of events:

1. At `Nov 07, 2024 at 6:25:30 UTC` started seeing unavailable and underreplicated ranges on dbconsole.
2. At `Nov 07, 2024 at 6:28 UTC`  started `seeing disk slowness` detected event on all four stores of the node 75.
3. At `Nov 07, 2024 at 6:29 UTC` seen event `disk slowness cleared`.
4. **Restarted** node 75 at `Nov 07, 2024 at 7:26 UTC` and the `unavailable` and `underreplicated` ranges went away.

Questions:
1. What is causing this behaviour?
2. How does restarting the problematic node solves the issue.

<img width="1483" alt="Screenshot 2024-11-07 at 4 16 26 PM" src="https://github.com/user-attachments/assets/2c290439-d8b1-47b1-adc9-87002c563d76">
<img width="1021" alt="Screenshot 2024-11-07 at 4 19 30 PM" src="https://github.com/user-attachments/assets/d9ef6fb1-f886-46a0-9255-a0904ba3d279">

**Comment by arulajmani** [comment]
Closing this out because the cluster seems to be running extremely hot (multiple nodes >90%) when this issue was caused. See https://cockroachlabs.slack.com/archives/C07HPMBLVJ7/p1730977433795349 for more details. Another instance of the issue was when we saw high goroutine scheduling latencies which were workload induced. Detailed investigation is in the linked thread.

**Comment by dshjoshi** [comment]
While this has been closed, we will get back to it.
