### ISSUE TITLE
storage: over-aggressive replicateQueue purgatory checks

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#13433]
The `replicateQueue` is configured to re-check the replicas in purgatory every time node liveness changes or it receives an updated store descriptor via gossip. But due to reactive store descriptor gossiping, we can end up checking purgatory extremely frequently.

This isn't a huge problem and the performance impact is negligible in the workloads I've looked at, but it does show up in allocation profiles (i.e. it adds to GC pressure). With the addition of node liveness, I wonder if we need to check purgatory when store descriptors are gossiped.

Cc @spencerkimball

**Comment by dianasaur323** [comment]
@spencerkimball this doesn't sound like it needs to be done immediately - moving to 1.1 unless you want to finish by 1.0.
