### ISSUE TITLE
Uniqueness of Serial type

### ISSUE THREAD

**Issue by tlvenn** [cockroachdb/cockroach#13441]
Hi,

Usually, any flavour of snowflake has a sequence number part but the serial type that Cockroachdb currently use does not unless I am mistaken. How does Cockroachdb prevent collision when 2 serials are requested at the same time on a given node ?

Thanks in advance.

**Comment by petermattis** [comment]
@tlvenn `unique_rowid()` (which powers the SERIAL type) generates a value that is composed of a timestamp+nodeID. The nodeID is guaranteed unique across the cluster and the timestamp is guaranteed unique within a node by using a small wrapper around the clock which forces timestamps to be strictly increasing. 

The one small window of vulnerability we haven't closed here is that the wrapper around the clock does not handle cases where the clock jumps backward significantly while the node is down.

**Comment by tlvenn** [comment]
Thanks for the explanation @petermattis

**Comment by tlvenn** [comment]
Closed the issue but when you have the time I am curious on what approach you took for that wrapper to be lock free and not create contention at the same time.

**Comment by petermattis** [comment]
The wrapper around the local clock is not lock free, but the code inside the critical section is very tiny and isn't a bottleneck on insertion at this time.
