### ISSUE TITLE
kvserver: benign races during replication changes log rather alarmingly

### ISSUE THREAD

**Issue by shailendra-patel** [cockroachdb/cockroach#134412]
On `drt-scale` hitting the following error message quite a few times.
```
trying to add({ChangeType:ADD_VOTER Target:n124,s494}) to a store that already has a LEARNER
HINT: ‹You have encountered an unexpected error.›

‹Please check the public issue tracker to check whether this problem is›
‹already tracked. If you cannot find it there, please report the error›
‹with details by creating a new issue.›

‹If you would rather not post publicly, please contact us directly›
‹using the support form.›

‹We appreciate your feedback.›
```

[Datadog Link](https://us5.datadoghq.com/logs?query=status%3Aerror%20cluster%3Adrt-scale%20%22trying%20to%20add%22&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&event=AwAAAZL9PXFu00dLFQAAABhBWkw5UFhGdUFBQ3kzbk5mdEhVOUp3TDkAAAAkMDE5MmZkM2YtOWY2NS00YjliLTg5MDItMjQ4YjA2ZjY4NWFkAAS0kg&fromUser=true&messageDisplay=inline&refresh_mode=paused&storage=flex_tier&stream_sort=time%2Casc&viz=stream&from_ts=1730809685976&to_ts=1730905380000&live=false)

Jira issue: CRDB-44069

Epic CRDB-44205

**Comment by kvoli** [comment]
> Was the cluster overloaded? If nothing else, we can update the error message or add another check, but this is benign @shailendra-patel.
> > If the error message is benign, can we consider rephrasing the wording and adjusting the severity level accordingly?

Lets do that. I'm adjusting the severity accordingly.

**Comment by arulajmani** [comment]
I'm updating the issue title to capture what we're going to do here, given such errors are somewhat expected, especially when the cluster is overloaded.

**Comment by arulajmani** [comment]
Actually, seems like we already had https://github.com/cockroachdb/cockroach/issues/108588. I'm going to close that issue out and maybe re-assign you to it @kvoli.
