### ISSUE TITLE
kvserver: cannot merge because rhs is either in a joint state or has learner replicas

### ISSUE THREAD

**Issue by shailendra-patel** [cockroachdb/cockroach#134414]
On `drt-scale`, observing below error message quite few times

[Datadog link](https://us5.datadoghq.com/logs?query=status%3Aerror%20cluster%3Adrt-scale%20%22cannot%20merge%20because%20rhs%20is%20either%20in%20a%20joint%20state%20or%20has%20learner%22&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=paused&storage=flex_tier&stream_sort=time%2Casc&viz=stream&from_ts=1730858316764&to_ts=1730906508000&live=false)
```
cannot merge because rhs is either in a joint state or has learner replicas: [(n131,s523):8 (n129,s516):9 (n37,s148):7 (n89,s353):10LEARNER]
HINT: ‹You have encountered an unexpected error.›

‹Please check the public issue tracker to check whether this problem is›
‹already tracked. If you cannot find it there, please report the error›
‹with details by creating a new issue.›

‹If you would rather not post publicly, please contact us directly›
‹using the support form.›

‹We appreciate your feedback.›
```

Jira issue: CRDB-44071

Epic CRDB-44205

**Comment by arulajmani** [comment]
Another instance of https://github.com/cockroachdb/cockroach/issues/134412, but slightly different. Closing this out so we can coalesce on that issue.
