### ISSUE TITLE
testing: Use more permissive certs in tests that rely on IsolatedTestAddr

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#13449]
Currently, our unit tests that spin up multiple servers using `IsolatedTestAddr` have to also set `Insecure` to true to avoid cert validation failures. This is because `IsolatedTestAddr` assigns each server a random loopback address (not just `127.0.0.1`) but our test certs can only validate `127.0.0.1`.

As @tamird [brought up in a recent PR review](https://github.com/cockroachdb/cockroach/pull/13427#issuecomment-277738307), it may be better to make our certs more lenient than to make more tests run in insecure mode. This issue is to track that suggestion.

**Comment by bdarnell** [comment]
I'm not sure if this is possible. I don't think wildcards are allowed in IP addresses (i.e. you can't have a certificate for `127.*.*.*`), just in hostnames. We could list a bunch of IPs individually in the cert, but then we wouldn't get as much address space expansion. I'd rather leave these tests in insecure mode than worry about this.

**Comment by a-robinson** [comment]
Closing since it don't believe like we have any intention of doing this.
