### ISSUE TITLE
stability: system clock/ntp jumps (>1s)

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#13447]
This is a tracking issue, not much we can do about it right now.

GCE instance `cockroach-omega-0006` (`104.196.19.134`), 8vcpu, 16GiB RAM, in `us-east1-d` has been having clock issues.
Three times so far, the system clock has jumped backwards by anywhere from 1 to 6 seconds.
No mention of migrations in `gcloud compute operations list`

First two drifts occurred on 2017-02-01: all times UTC
- 1.75s around 01:42:30, resolved manually by stopping ntp and running `ntpdate`.
- 1s around 03:47:30, resolved itself around 04:16:20.
![omega_drift_2017-02-01](https://cloud.githubusercontent.com/assets/5901480/22693288/9c4d49dc-ed10-11e6-953d-35b739c99ba5.png)

Latest drift occurred on 2017-02-07: around 10:49:10, this time jumping backwards by 6 seconds. Fixed itself around 14:00. Only thing in the logs is: `Feb  7 13:59:52 cockroach-omega-0006 systemd[1]: Time has been changed`
![omega_drift_2017-02-07](https://cloud.githubusercontent.com/assets/5901480/22695020/451e9010-ed17-11e6-8113-9585df945076.png)

**Comment by mberhault** [comment]
@spencerkimball, @a-robinson: any idea who I can forward this to over at GCE?

**Comment by mberhault** [comment]
ah, it's `cockroach-omega-0003` this time:
jumped backwards by 3 seconds around 020917-16:41, and fixed itself around 020917-19:08:
<img width="1422" alt="screen shot 2017-02-09 at 3 01 01 pm" src="https://cloud.githubusercontent.com/assets/5901480/22800834/a1de64ca-eed8-11e6-9cb4-3a63d6d9d785.png">

**Comment by a-robinson** [comment]
Have we heard anything back about this yet?

**Comment by mberhault** [comment]
uh, no. I haven't filed a support ticket or anything. Just looking at it now, it turns out we don't have a support plan for GCE.

**Comment by a-robinson** [comment]
@spencerkimball had suggested going through our "GCP for Startups" contact.

**Comment by petermattis** [comment]
The `GCP for Startups` folks are still investigating the nature of `Local SSD` for me. I have another Google contact who promised to be able to investigate clock offset issues. Let me track him down and corner him.

**Comment by mberhault** [comment]
one more: omega-001 jumped back 600ms for ~50m.
started at 2017-02-13 10:51, ended by itself at 11:41.

<img width="1433" alt="screen shot 2017-02-13 at 7 05 52 am" src="https://cloud.githubusercontent.com/assets/5901480/22882821/ff50633a-f1ba-11e6-8ab7-13cdccf1a4d9.png">

**Comment by mberhault** [comment]
omega-0006 jumped back 6s for about 2.5 hours.
started at 2017-02-17 04:41:50, ended by itself at 07:15:20
<img width="1432" alt="screen shot 2017-02-17 at 8 54 13 am" src="https://cloud.githubusercontent.com/assets/5901480/23067830/fde35944-f4ee-11e6-8a71-521de81bacd7.png">

**Comment by mberhault** [comment]
Per discussion with Google folks, the OS image we were running had a problem, missing the clock sync process upon migrations. I've restart omega with a newer image and confirmed that the process is running.

I also tried without ntp, but even one hour showed that it's not reasonable:
<img width="1435" alt="screen shot 2017-02-20 at 10 32 52 am" src="https://cloud.githubusercontent.com/assets/5901480/23131485/2022a59e-f758-11e6-92b7-f7f1b2ee09fc.png">

within 1h, half the instances had drifted by about 7ms, the other half were still within 1ms of ntp time.
Turning on ntp brought all three instances back inline.

Will keep this open to see if we experience big jumps, those were rare enough that we may have to wait a bit.

**Comment by mberhault** [comment]
we haven't seen this in quite some time. we've done two different images on GCE so far, both have the google clock skew daemon running. Closing.
