### ISSUE TITLE
storage,kv: sudden leaseholder changes due to io overload shedding

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#134423]
On a test cluster I observed frequent sudden and drastic leaseholder movements, when a node would in the space of a couple seconds shed all of its leases due to its IO overload score touching the threshold at which it does so.

Further investigation suggests this may be to a number of concurrent larger multi-level compactions that were recently enabled briefly occupying all the compaction slots, causing L0 to briefly increase in its level count and hitting the threshold.

It seems like we should shed leases more gradually as overload signals rise rather than all at once, and that we should avoid using all of our compaction capacity on longer running multi-level compactions for periods so long that they starve out compactions required to keep L0 level counts healthy.

Jira issue: CRDB-44074

**Comment by itsbilal** [comment]
Pebble companion issue https://github.com/cockroachdb/pebble/issues/4139

**Comment by itsbilal** [comment]
I'll turn this issue into one about just disabling multilevel compactions in 24.3, while cockroachdb/pebble#4139 is about reenabling them with concurrency limits.

**Comment by dt** [comment]
Do we need a new separate issue for more gradual ramp up of lease shedding?
