### ISSUE TITLE
roachpb: reduce memory allocations for Transaction.ObservedTimestamps

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#13442]
`Transaction.ObservedTimestamps` is a map from node ID to the highest observed timestamp for that node and is used to avoid uncertainty related restarts. This map is copied whenever we clone a transaction, which is unfortunately several times during the lifetime of a request. And those copies involve 3 allocations for the map and the values (I'm not quite sure why the map internals result in 3 allocations, but the profiler doesn't lie). The allocations for the `Transaction.ObservedTimestamps` map account for 4% of the total allocations in Cockroach under a write-only workload I profiled.

It looks straightforward to transform the type from `map[NodeID]hlc.Timestamp` to `[]struct{NodeID,hlc.Timestamp}` and to keep the slice sorted for quick lookup. 

A more radical change would be to replace `ObservedTimestamp` with a 1 element entry which is the observed timestamp of the node we're sending the request to. `Transaction.GetObservedTimestamp` is only called from the store executing a request and from `TxnCoordSender`. The latter could maintain a full map of node to observed timestamp while the store only needs to know the observed timestamp for the node it is running on.

**Comment by bdarnell** [comment]
It looks to me like `ObservedTimestamp` could be moved out of the `Transaction` proto completely and moved to the batch headers (and the full map stored in TxnCoordSender's txnMetadata)
