### ISSUE TITLE
acceptance/terraform: add terraform tests that run YCSB

### ISSUE THREAD

**Issue by arjunravinarayan** [cockroachdb/cockroach#13459]
Once the [YCSB load generator](https://github.com/cockroachdb/loadgen/pull/14) is running stably on the production cluster, add a terraform test that runs the YCSB load generator nightly.

**Comment by arjunravinarayan** [comment]
Unassigning this as it has proven to be more work than we thought.

**Comment by jordanlewis** [comment]
Can we close this? Is there a similar need for roachtest?

**Comment by arjunravinarayan** [comment]
No, this has long been superseded by our nightly roachtest framework.
