### ISSUE TITLE
storage: node unable to restart after kill -9, "... may contain relevant WALs"

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#134519]
Commit: a60d739746648922134ec3c0a22bb069bf1d283c (master)

We ran some quorum replication flow control experiments that at times pushed writes on the cluster. We had wal failover set up.

<details><summary>Details</summary>
<p>

```
I241107 11:15:20.363500 114 util/log/file_sync_buffer.go:237 ⋮ [config]   arguments: [‹./cockroach› ‹start› ‹--certs-dir› ‹certs› ‹--log› ‹file-defaults: {dir: 'logs', exit-on-error: false}› ‹--listen-addr=:26257› ‹--http-addr=:26258› ‹--adve
rtise-addr=10.142.1.248:26257› ‹--join=34.148.60.236:26257› ‹--store› ‹path=/mnt/data1/cockroach,attrs=store1:node12:node
12store1› ‹--store› ‹path=/mnt/data2/cockroach,attrs=store2:node12:node12store2› ‹--wal-failover=among-stores› ‹--cache=25%› ‹--max-sql-memory=25%› ‹--locality=region=fake-2›]
```

</p>
</details> 

At some time, we `kill -9`'ed node 12. It won't start again:

> E241107 13:06:39.627173 1 1@cli/clierror/check.go:30 ⋮ [-] 13  ‹ERROR›: server startup failed: failed to start server: failed to create engines: ‹directory "/mnt/data2/cockroach/auxiliary/wals-among-stores" may contain relevant WALs›

In fact that directory contains some WALs:

```
$ ls /mnt/data2/cockroach/auxiliary/wals-among-stores/
037122.log       037326.log       037477.log       037873.log       038283.log       114926.log       failover_source
```

but as an operator I am left unable to restart this node.

Jira issue: CRDB-44122

**Comment by jbowens** [comment]
This was a mistake in manually restarting the node without the second store, and this is the expected resulting error message.

https://cockroachlabs.slack.com/archives/CAC6K3SLU/p1730988575232169
