### ISSUE TITLE
sql: table scans over interleaved tables return incorrect results

### ISSUE THREAD

**Issue by lymar** [cockroachdb/cockroach#13451]
Cockroach version: beta-20170126.

Copy-and-paste code from https://www.cockroachlabs.com/docs/interleave-in-parent.html into SQL console:
```
root@:26257> CREATE TABLE customers (
               id INT PRIMARY KEY,
               name STRING(50)
             );
CREATE TABLE

root@:26257> CREATE TABLE orders (
               customer INT, 
               id INT,
               total DECIMAL(20, 5), 
               PRIMARY KEY (customer, id), 
               CONSTRAINT fk_customer FOREIGN KEY (customer) REFERENCES customers
               ) INTERLEAVE IN PARENT customers (customer)
             ;
CREATE TABLE

root@:26257> INSERT INTO customers 
             (id, name) VALUES 
             (1, 'Ha-Yun'),
             (2, 'Emanuela');
INSERT 2

root@:26257> INSERT INTO orders 
             (customer, id, total) VALUES 
             (1, 1000, 100.00),
             (2, 1001, 90.00),
             (1, 1002, 80.00),
             (2, 1003, 70.00);
INSERT 4
```

Then try SELECT **(bug?!)**:

```
root@:26257> SELECT * FROM orders WHERE customer=1 AND id=1000;
+----------+----+-------+
| customer | id | total |
+----------+----+-------+
+----------+----+-------+
(0 rows)
```

But I expect:

```
root@:26257> SELECT * FROM orders WHERE customer=1 AND id=1000;
+----------+------+-------+
| customer |  id  | total |
+----------+------+-------+
|        1 | 1000 |   100 |
+----------+------+-------+
(1 row)
```

Why do I get an empty result?

**Comment by knz** [comment]
Confirmed in 6067175467360837c69b66fafae9910952cf6709.

**Comment by knz** [comment]
cc @danhhz

**Comment by danhhz** [comment]
woah. on it

**Comment by danhhz** [comment]
I was able to reproduce this and have narrowed the issue down to constructing various spans (at least `makeSpansForIndexConstraints` and maybe more) in a way that is incompatible with interleaved tables. (Specifically, code that assumes MakeIndexKeyPrefix followed by encoding primary key columns is not correct.)

I'm worried about how such an obvious bug was missed. I'm going to take a bit while working on the fix to consider how we could prevent future regressions.

**Comment by benesch** [comment]
[`InternalExecutor.GetTableSpan`](https://github.com/cockroachdb/cockroach/blob/0bc16eb28fecd76e9145cc39b864137187d80b01/pkg/sql/internal.go#L51-L70) is broken for similar reasons.

**Comment by eisenstatdavid** [comment]
This bug was present in beta-20161013, the first with interleaved tables. The problem seems to be that no one taught `index_selection.go:makeSpansForIndexConstraints` about interleaved tables. I'm working on a fix.
