### ISSUE TITLE
sql: SHOW SERVER_VERSION needs lowercase column name

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#13465]
Sequelize issues this query:

```
SHOW SERVER_VERSION
```

On CockroachDB, this results in:

```
root@:26257/> SHOW SERVER_VERSION;
+----------------+
| SERVER_VERSION |
+----------------+
| 9.5.0          |
+----------------+
```

PostgreSQL 9.6.1 gives this as its result:
```
postgres=# SHOW SERVER_VERSION;
 server_version
----------------
 9.6.1
(1 row)
```

Note the difference in capitalization. Sequelize requires that the column name for the result set be `server_version` (lowercase). If it isn't lowercase, version/feature detection breaks.

cc @nvanbenschoten

**Comment by tamird** [comment]
Is this something which applies to all such variables?

**Comment by nvanbenschoten** [comment]
Oh boy, do you mind linking to the code in Sequelize that makes this capitalization assumption?

**Comment by cuongdo** [comment]
I believe it's this line of code:

https://github.com/sequelize/sequelize/blob/v3/lib/dialects/postgres/query.js#L237

which relies on the query result provided by https://github.com/brianc/node-postgres, which seems to convert each field name to a field in the result object.

**Comment by cuongdo** [comment]
@tamird It does seem like PostgreSQL always lower cases the column name for `SHOW` results. Here's one notable exception (it's unclear if this affects the ORMs we care about):

```
postgres=# SHOW TIME ZONE;
  TimeZone
------------
 US/Eastern
(1 row)
```

(note the camel-cased `TimeZone`)

It might suffice to lower-case the column name in the result set.
