### ISSUE TITLE
storage,kv: undiagnosed replica inconsistency reported on f9918d8f8

### ISSUE THREAD

**Issue by stevendanna** [cockroachdb/cockroach#134640]
**Describe the problem**

This is a placeholder issue for a report of replica inconsistency in a running cluster.  We are still collecting information from the report and thus have very little additional information.

Jira issue: CRDB-44185

**Comment by benbardin** [comment]
We believe this issue arose from a hard shutdown on a node running ZFS with fsync disabled. We believe lease transfers were lost when the ZFS buffer did not flush.

To increase our confidence, we are adding observability and doing additional testing.
