### ISSUE TITLE
sql: all inspection queries hang during table dropping

### ISSUE THREAD

**Issue by arjunravinarayan** [cockroachdb/cockroach#13460]
I ran `loadgen/ycsb` workload B successfully for ~80 minutes, which ran at ~1800qps, and resulted in 514982 rows written (according to the load generator). For context, ycsb's schema looks like this:

`CREATE TABLE IF NOT EXISTS usertable(ycsb_key INT PRIMARY KEY NOT NULL, FIELD1 TEXT, FIELD2 TEXT, FIELD3 TEXT,FIELD4 TEXT, FIELD5 TEXT, FIELD6 TEXT, FIELD7 TEXT, FIELD8 TEXT, FIELD9 TEXT, FIELD10 TEXT)`

Dropping this table on a freshly restarted cluster is taking over 1.5 hours, with no way to see progress or status. While this is happening, all inspection queries fail, including `SHOW TABLES` or `SHOW CREATE...`. Of course, `CREATE TABLE usertable` also cannot complete until this finishes (#7348).

I believe this hanging occurs during all pending `ALTER TABLE` queries as well, but I have not reproduced a non-`DROP` version.

**Comment by arjunravinarayan** [comment]
@petermattis could you please route this for me?

**Comment by petermattis** [comment]
@vivekmenezes `DROP TABLE` is considered as schema change operation, correct?

**Comment by vivekmenezes** [comment]
Feel free to close this issue if you think  #7348 will resolve it. The solution there is to rename the table before dropping it.

**Comment by vivekmenezes** [comment]
#13908 resolves this.
