### ISSUE TITLE
ui: on 15" macbook, website overflows horizontally (hiding the summary)

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#13475]
This can be remedied by repeated CMD+-, but it seems awkward for the first view.
(edit: uploaded the correct picture)
![image](https://cloud.githubusercontent.com/assets/5076964/22721078/a5b2cdd2-ed7c-11e6-9e6c-34080954d9db.png)

**Comment by kuanluo** [comment]
@maxlang Curious how did this happen, and the solution might benefit standard, smaller desktop screens like 11" as well.

**Comment by dianasaur323** [comment]
@mrtracy honestly, I would put this lower on our priority list of bug fixes if your list is already pretty long.

**Comment by mrtracy** [comment]
I do not think this is still a bug; at 1366px widescreen resolution everything on the cluster page fits onto the page horizontally, 15" macbook pro should actually a bit wider than that.  We are not targeting anything slimmer; the current layout packs a lot of information horizontally and we will require design guidance to display any thinner.
