### ISSUE TITLE
ui: consider if log output should be anti-chronological

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#13474]
It's currently chronological, which means that old stuff is the first thing you see:

![image](https://cloud.githubusercontent.com/assets/5076964/22720919/d3077342-ed7b-11e6-8149-82cbae4e78c1.png)

Maybe anti-chronological is unintuitive, but the amount of scrolling required to get to the current output is pretty annoying.

**Comment by mrtracy** [comment]
Duplicate #8907
