### ISSUE TITLE
Sentry: error.go:78: unexpected error from the vectorized engine: runtime error: slice bounds out of range [:312] with capacity 169
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack tra...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#134797]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/6055457642/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/6055457642/?referrer=webhooks_plugin)

Panic Message:

```
error.go:78: unexpected error from the vectorized engine: runtime error: slice bounds out of range [:312] with capacity 169
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:78
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:770
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.InternalError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:291
  | github.com/cockroachdb/cockroach/pkg/sql/colflow/colrpc.(*Inbox).Next.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/colrpc/inbox.go:329
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:770
  | runtime.goPanicSliceAcap
  | 	GOROOT/src/runtime/panic.go:140
  | github.com/apache/arrow/go/arrow/array.(*Int64).setData
  | 	github.com/apache/arrow/go/arrow/array/external/com_github_apache_arrow_go_arrow/array/numeric.gen.go:79
  | github.com/apache/arrow/go/arrow/array.NewInt64Data
  | 	github.com/apache/arrow/go/arrow/array/external/com_github_apache_arrow_go_arrow/array/numeric.gen.go:38
  | github.com/cockroachdb/cockroach/pkg/col/colserde.(*ArrowBatchConverter).ArrowToBatch
  | 	github.com/cockroachdb/cockroach/pkg/col/colserde/arrowbatchconverter.go:532
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils.(*Deserializer).Deserialize.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils/deserializer.go:74
  | github.com/cockroachdb/cockroach/pkg/sql/colmem.(*Allocator).PerformOperation
  | 	github.com/cockroachdb/cockroach/pkg/sql/colmem/allocator.go:448
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils.(*Deserializer).Deserialize
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils/deserializer.go:73
  | github.com/cockroachdb/cockroach/pkg/sql/colflow/colrpc.(*Inbox).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/colrpc/inbox.go:409
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*OrderedSynchronizer).Next
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/colexec/ordered_synchronizer.eg.go:119
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*UnorderedDistinct).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/unordered_distinct.go:100
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk.(*diskSpillerBase).Next.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk/disk_spiller.go:202
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:152
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk.(*diskSpillerBase).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk/disk_spiller.go:200
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*limitOp).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/limit.go:47
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Materializer).next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:251
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Materializer).nextAdapter
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:276
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:152
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Materializer).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:282
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*FlowCoordinator).next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:124
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*FlowCoordinator).nextAdapter
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:141
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:152
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*FlowCoordinator).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:146
  | github.com/cockroachdb/cockroach/pkg/sql/execinfra.Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/execinfra/base.go:199
  | github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBaseNoHelper).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:732
  | github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:579
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:305
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:932
Wraps: (3) unexpected error from the vectorized engine
Wraps: (4) runtime error: slice bounds out of range [:312] with capacity 169
  | -- cause hidden behind barrier
  | runtime error: slice bounds out of range [:312] with capacity 169
  | (1) attached stack trace
  |   -- stack trace:
  |   | github.com/cockroachdb/cockroach/pkg/sql/colflow/colrpc.(*Inbox).Next.func1
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/colrpc/inbox.go:324
  |   | runtime.gopanic
  |   | 	GOROOT/src/runtime/panic.go:770
  |   | runtime.goPanicSliceAcap
  |   | 	GOROOT/src/runtime/panic.go:140
  |   | github.com/apache/arrow/go/arrow/array.(*Int64).setData
  |   | 	github.com/apache/arrow/go/arrow/array/external/com_github_apache_arrow_go_arrow/array/numeric.gen.go:79
  |   | github.com/apache/arrow/go/arrow/array.NewInt64Data
  |   | 	github.com/apache/arrow/go/arrow/array/external/com_github_apache_arrow_go_arrow/array/numeric.gen.go:38
  |   | github.com/cockroachdb/cockroach/pkg/col/colserde.(*ArrowBatchConverter).ArrowToBatch
  |   | 	github.com/cockroachdb/cockroach/pkg/col/colserde/arrowbatchconverter.go:532
  |   | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils.(*Deserializer).Deserialize.func1
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils/deserializer.go:74
  |   | github.com/cockroachdb/cockroach/pkg/sql/colmem.(*Allocator).PerformOperation
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colmem/allocator.go:448
  |   | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils.(*Deserializer).Deserialize
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils/deserializer.go:73
  |   | github.com/cockroachdb/cockroach/pkg/sql/colflow/colrpc.(*Inbox).Next
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/colrpc/inbox.go:409
  |   | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*OrderedSynchronizer).Next
  |   | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/colexec/ordered_synchronizer.eg.go:119
  |   | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*UnorderedDistinct).Next
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/unordered_distinct.go:100
  |   | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk.(*diskSpillerBase).Next.func1
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk/disk_spiller.go:202
  |   | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:152
  |   | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk.(*diskSpillerBase).Next
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecdisk/disk_spiller.go:200
  |   | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*limitOp).Next
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/limit.go:47
  |   | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Materializer).next
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:251
  |   | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Materializer).nextAdapter
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:276
  |   | github.com/cockroachdb/cockroach/pkg/sq...
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/distsql_running.go#L931-L933](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/distsql_running.go#L931-L933)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colflow/vectorized_flow.go#L304-L306](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colflow/vectorized_flow.go#L304-L306)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/flowinfra/flow.go#L578-L580](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/flowinfra/flow.go#L578-L580)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/execinfra/processorsbase.go#L731-L733](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/execinfra/processorsbase.go#L731-L733)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/execinfra/base.go#L198-L200](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/execinfra/base.go#L198-L200)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colflow/flow_coordinator.go#L145-L147](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colflow/flow_coordinator.go#L145-L147)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexecerror/error.go#L151-L153](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexecerror/error.go#L151-L153)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colflow/flow_coordinator.go#L140-L142](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colflow/flow_coordinator.go#L140-L142)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colflow/flow_coordinator.go#L123-L125](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colflow/flow_coordinator.go#L123-L125)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexec/materializer.go#L281-L283](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexec/materializer.go#L281-L283)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexecerror/error.go#L151-L153](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexecerror/error.go#L151-L153)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexec/materializer.go#L275-L277](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexec/materializer.go#L275-L277)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexec/materializer.go#L250-L252](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexec/materializer.go#L250-L252)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexec/limit.go#L46-L48](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexec/limit.go#L46-L48)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexec/colexecdisk/disk_spiller.go#L199-L201](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexec/colexecdisk/disk_spiller.go#L199-L201)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexecerror/error.go#L151-L153](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexecerror/error.go#L151-L153)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexec/colexecdisk/disk_spiller.go#L201-L203](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexec/colexecdisk/disk_spiller.go#L201-L203)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexec/unordered_distinct.go#L99-L101](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexec/unordered_distinct.go#L99-L101)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/bazel-out/k8-opt/bin/pkg/sql/colexec/ordered_synchronizer.eg.go#L118-L120](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/bazel-out/k8-opt/bin/pkg/sql/colexec/ordered_synchronizer.eg.go#L118-L120)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colflow/colrpc/inbox.go#L408-L410](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colflow/colrpc/inbox.go#L408-L410)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexec/colexecutils/deserializer.go#L72-L74](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexec/colexecutils/deserializer.go#L72-L74)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colmem/allocator.go#L447-L449](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colmem/allocator.go#L447-L449)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexec/colexecutils/deserializer.go#L73-L75](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexec/colexecutils/deserializer.go#L73-L75)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/col/colserde/arrowbatchconverter.go#L531-L533](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/col/colserde/arrowbatchconverter.go#L531-L533)
[github.com/apache/arrow/go/arrow/array/external/com_github_apache_arrow_go_arrow/array/numeric.gen.go#L37-L39](github.com/apache/arrow/go/arrow/array/external/com_github_apache_arrow_go_arrow/array/numeric.gen.go#L37-L39)
[github.com/apache/arrow/go/arrow/array/external/com_github_apache_arrow_go_arrow/array/numeric.gen.go#L78-L80](github.com/apache/arrow/go/arrow/array/external/com_github_apache_arrow_go_arrow/array/numeric.gen.go#L78-L80)
[GOROOT/src/runtime/panic.go#L139-L141](GOROOT/src/runtime/panic.go#L139-L141)
[GOROOT/src/runtime/panic.go#L769-L771](GOROOT/src/runtime/panic.go#L769-L771)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colflow/colrpc/inbox.go#L328-L330](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colflow/colrpc/inbox.go#L328-L330)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexecerror/error.go#L290-L292](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexecerror/error.go#L290-L292)
[GOROOT/src/runtime/panic.go#L769-L771](GOROOT/src/runtime/panic.go#L769-L771)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexecerror/error.go#L77-L79](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexecerror/error.go#L77-L79)
</details>

```
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).Run at line 932
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlow).Run at line 305
pkg/sql/flowinfra/flow.go in pkg/sql/flowinfra.(*FlowBase).Run at line 579
pkg/sql/execinfra/processorsbase.go in pkg/sql/execinfra.(*ProcessorBaseNoHelper).Run at line 732
pkg/sql/execinfra/base.go in pkg/sql/execinfra.Run at line 199
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*FlowCoordinator).Next at line 146
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 152
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*FlowCoordinator).nextAdapter at line 141
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*FlowCoordinator).next at line 124
pkg/sql/colexec/materializer.go in pkg/sql/colexec.(*Materializer).Next at line 282
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 152
pkg/sql/colexec/materializer.go in pkg/sql/colexec.(*Materializer).nextAdapter at line 276
pkg/sql/colexec/materializer.go in pkg/sql/colexec.(*Materializer).next at line 251
pkg/sql/colexec/limit.go in pkg/sql/colexec.(*limitOp).Next at line 47
pkg/sql/colexec/colexecdisk/disk_spiller.go in pkg/sql/colexec/colexecdisk.(*diskSpillerBase).Next at line 200
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 152
pkg/sql/colexec/colexecdisk/disk_spiller.go in pkg/sql/colexec/colexecdisk.(*diskSpillerBase).Next.func1 at line 202
pkg/sql/colexec/unordered_distinct.go in pkg/sql/colexec.(*UnorderedDistinct).Next at line 100
bazel-out/k8-opt/bin/pkg/sql/colexec/ordered_synchronizer.eg.go in pkg/sql/colexec.(*OrderedSynchronizer).Next at line 119
pkg/sql/colflow/colrpc/inbox.go in pkg/sql/colflow/colrpc.(*Inbox).Next at line 409
pkg/sql/colexec/colexecutils/deserializer.go in pkg/sql/colexec/colexecutils.(*Deserializer).Deserialize at line 73
pkg/sql/colmem/allocator.go in pkg/sql/colmem.(*Allocator).PerformOperation at line 448
pkg/sql/colexec/colexecutils/deserializer.go in pkg/sql/colexec/colexecutils.(*Deserializer).Deserialize.func1 at line 74
pkg/col/colserde/arrowbatchconverter.go in pkg/col/colserde.(*ArrowBatchConverter).ArrowToBatch at line 532
github.com/apache/arrow/go/arrow/array/external/com_github_apache_arrow_go_arrow/array/numeric.gen.go in github.com/apache/arrow/go/arrow/array.NewInt64Data at line 38
github.com/apache/arrow/go/arrow/array/external/com_github_apache_arrow_go_arrow/array/numeric.gen.go in github.com/apache/arrow/go/arrow/array.(*Int64).setData at line 79
GOROOT/src/runtime/panic.go in runtime.goPanicSliceAcap at line 140
GOROOT/src/runtime/panic.go in runtime.gopanic at line 770
pkg/sql/colflow/colrpc/inbox.go in pkg/sql/colflow/colrpc.(*Inbox).Next.func1 at line 329
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.InternalError at line 291
GOROOT/src/runtime/panic.go in runtime.gopanic at line 770
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1 at line 78
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v24.2.4 |
| Go Version | go1.22.5 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v24.2.4 |
| Cockroach SHA | 8140b8e294fb16a293d0aae662bcf5c1d488c852 |
| # of CPUs | 128 |
| # of Goroutines | 1337 |

Jira issue: CRDB-44250

**Comment by yuzefovich** [comment]
CC'ing via the CODEOWNERS-based sentry heuristic:
* @cockroachdb/sql-queries

<sub>:owl: Hoot! I am a [Blathers](https://github.com/apps/blathers-crl), a bot for [CockroachDB](https://github.com/cockroachdb). My owner is [dev-inf](https://github.com/orgs/cockroachdb/teams/dev-inf).</sub>

**Comment by yuzefovich** [comment]
CC'ing via the CODEOWNERS-based sentry heuristic:
* @cockroachdb/sql-queries

<sub>:owl: Hoot! I am a [Blathers](https://github.com/apps/blathers-crl), a bot for [CockroachDB](https://github.com/cockroachdb). My owner is [dev-inf](https://github.com/orgs/cockroachdb/teams/dev-inf).</sub>

**Comment by yuzefovich** [comment]
CC'ing via the CODEOWNERS-based sentry heuristic:
* @cockroachdb/sql-queries

<sub>:owl: Hoot! I am a [Blathers](https://github.com/apps/blathers-crl), a bot for [CockroachDB](https://github.com/cockroachdb). My owner is [dev-inf](https://github.com/orgs/cockroachdb/teams/dev-inf).</sub>

**Comment by yuzefovich** [comment]
CC'ing via the CODEOWNERS-based sentry heuristic:
* @cockroachdb/sql-queries

<sub>:owl: Hoot! I am a [Blathers](https://github.com/apps/blathers-crl), a bot for [CockroachDB](https://github.com/cockroachdb). My owner is [dev-inf](https://github.com/orgs/cockroachdb/teams/dev-inf).</sub>

**Comment by yuzefovich** [comment]
dup of #134798
