### ISSUE TITLE
kvclient: rangefeed failures causing spanconfigs not to update.

### ISSUE THREAD

**Issue by shailendra-patel** [cockroachdb/cockroach#134778]
The age of the oldest PTS record on the `drt-scale` cluster was increasing. Upon checking the `system.protected_ts_records`, it was found that no schedule or job was holding the PTS. 

The spanconfigs on node n43 were not updating to reflect the PTS records in the table, causing the oldest PTS record to appear older than it should be. The rangefeeds on node n43 were stuck in catchup and spinning due to connection errors, which led to the spanconfigs not updating.

<img width="1404" alt="Screenshot 2024-11-08 at 12 22 28 PM" src="https://github.com/user-attachments/assets/3df4af56-f95f-4094-b5e4-cc67a3a4c461">

Jira issue: CRDB-44233

**Comment by arulajmani** [comment]
@stevendanna I'm assigning this to you given you have a PR open for this already.
