### ISSUE TITLE
sql: move constant detection for ordering to renderNode

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#13476]
`planNode.Ordering()` gives us information about the columns in the plan that need to be sorted using selected indexes. However, there are many cases where optimizations are interested in the ordering properties of the data source, and aren't interested in which indexes were scanned or which fields were sorted to achieve this ordering. 

The distinction is subtle but important for cases like `SELECT 1 ORDER BY 1`. Here we know that the first column can be considered sorted in both an ascending and descending order. However, even with the `ORDER BY` clause, [sort.go](https://github.com/cockroachdb/cockroach/blob/81e8f13b70b7e95092b53f65dadda78cc847891c/pkg/sql/sort.go#L181) notices that no sorting is needed and elides the entry into its `plan.Ordering() orderingInfo `. Another example is `SELECT pk, secondary FROM t ORDER BY 1, 2`. Because we know the pk will be unique, we remove the second ordering from `plan.Ordering()`. It would be useful in a number of places to have something like `plan.OrderingProperties()`, targeted at consumers of the `planNode` to communicate which ordering conditions can be relied upon. Ideally, this would fit into our many uses of [`computeOrderingMatch`](https://github.com/cockroachdb/cockroach/blob/81e8f13b70b7e95092b53f65dadda78cc847891c/pkg/sql/ordering.go#L134) and improve a number of statement types at once.

This might also prompt the introduction of a third ordering direction: bidirectional. This would be useful for constants that can be considered ordered in both an ascending and descending direction.

**Comment by RaduBerinde** [comment]
Hi Nathan,

How would `OrderingProperties()` differ from `Ordering()` and `orderingInfo`? `orderingInfo` already has support for "exact match" columns, which I believe what we want for constants - it's not just that they can be considered both ascending and descending, but they can also be anywhere in a desired ordering.

`orderingInfo` also has support of expressing that rows are unique w.r.t the columns in the ordering: in `SELECT pk, secondary FROM t ORDER BY 1, 2.`, `orderingInfo{}` will say ordered by 1, with `unique=true`, which would make it automatically satisfy ("match") an ordering like 1,2.

Perhaps I don't quite understand the core issue - do you have an example that would help? One problem which I can recognize is that `sort.go` makes these determinations about constants and then when the `sortNode` is elided, that information goes away. I think we want to move the constant detection logic from `orderBy` in sort.go into the `renderNode`; this node should detect constants and populate its `Ordering()` accordingly. In the `SELECT 1` case, `renderNode.Ordering()` would present 1 as an exact match column, which would make the ordering satisfy both 1+ and 1-.

**Comment by RaduBerinde** [comment]
For reference, this is the plan and ordering info for the second example:
```sql
root@:26257/test> CREATE TABLE t (pk INT PRIMARY KEY, secondary INT);
CREATE TABLE
root@:26257/test> EXPLAIN (METADATA) SELECT pk, secondary FROM t ORDER BY 1, 2;
+-------+------+-------+-------------+-----------------+------------+
| Level | Type | Field | Description |     Columns     |  Ordering  |
+-------+------+-------+-------------+-----------------+------------+
|     0 | scan |       |             | (pk, secondary) | +pk,unique |
|     0 |      | table | t@primary   |                 |            |
|     0 |      | spans | ALL         |                 |            |
+-------+------+-------+-------------+-----------------+------------+
```

**Comment by nvanbenschoten** [comment]
Radu, thanks for the explanation. After reading more about `orderingInfo` and realizing that `computeOrderingMatch` is exactly what I had been trying to implement myself (and did end up using in #13444), I think `Ordering()` fits the use case perfectly. The main issue I'm running into with my example `SELECT 1 ORDER BY 1` is what you point out: `sort.go` doesn't consistently populate `orderingInfo` with all information it knows. For example, whether the node is elided or not, it won't populate a `exactMatchCols` map.

I think the following changes could be made to resolve this issue:
- fix `render.go` to compute and propagate `exactMatchCols` like you suggest, regardless of if `sort.go` ends up being elided
- move `computeOrderingMatch` to a method on `orderingInfo` and the obvious interface to use the type
- change the comment above `planNode.Ordering` to be more accurate. `orderingInfo` is about more than just "The indexes of the columns"

**Comment by RaduBerinde** [comment]
@knz I can take this on if there is no urgency.

**Comment by knz** [comment]
excellent. thanks
