### ISSUE TITLE
Backup uri with spaces 

### ISSUE THREAD

**Issue by alicia-l2** [cockroachdb/cockroach#134861]
See https://cockroachlabs.atlassian.net/wiki/spaces/BI/pages/4054843457/Backup+schedule+Bug+repro for repro

When running CREATE SCHEDULE on a backup endpoint with spaces in the URI, it works. But when we run ALTER SCHEDULE on that created backup job, or run ALTER SCHEDULE using that same backup endpoint with spaces, I get an error. 
When I run ALTER SCHEDULE on an encoded version of the URI it works. This feels like a bug. 

Jira issue: CRDB-44285

**Comment by msbutler** [comment]
solution: we ought to support uri's with spaces.
