### ISSUE TITLE
sqlccl: figure out import/export checksums (for backup/restore)

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#13482]
Backup (via export) creates a number of files containing data and saves the path of each file with its checksum in a BackupDescriptor. We need to decide how we plan to use these checksums during restore (via import) and also which checksum to use.

If we only care about the checksum as a basic verification that files referenced in the BackupDescriptor haven't been changed in the interim, we could piggyback on the one kept by the various cloud storages (md5 for s3/azure, crc32c for gcs) and avoid the need to compute it ourselves.

If we want to verify the actual bytes as received on the CockroachDB nodes, we're free to pick any checksum we like. This will definitely be necessary if we ever use AddFile (or something like it), but even if not, we may want to go this route to defend against corruptions when fetching the file.

@bdarnell has expressed a preference for sha256 over crc32c (https://reviewable.io/reviews/cockroachdb/cockroach/13417#-KcOVgrrYgcdoNoCn8kj) but it looks like the go stdlib implementation of it only operates on byte slices (https://golang.org/pkg/crypto/sha256/), which is a little unfortunate.

cc @dt @mjibson

**Comment by mjibson** [comment]
The helper function only works on byte slices, but you can also do sha256.New(), then call .Write on that, since it returns a hash.Hash. So we should be able to use that just as easily as crc.

**Comment by danhhz** [comment]
decided to keep the feature, checksum before & after network transfer, strengthen the checksum algo
