### ISSUE TITLE
ldapccl: handle non-standard sql group roles in ldap authZ

### ISSUE THREAD

**Issue by souravcrl** [cockroachdb/cockroach#134923]
Currently, sql syntax limits us to use the [convention](https://www.cockroachlabs.com/docs/v24.2/create-user#user-names) mentioned here for creating sql usernames. Thus during authZ where we process grant role for ldap groups with `.` or `-` in their `CN` fail as they need a quoted string to process the stmt.

```
root@localhost:26257/defaultdb> GRANT crl-example-com-domain-sync-users TO testuser;                                                                                                                   
ERROR: statement ignored: at or near "-": syntax error: not a valid privilege: "crl"
SQLSTATE: 42601
DETAIL: source SQL:
GRANT crl-example-com-domain-sync-users TO testuser
```

Proposal: handle non-standard group roles in grant stmt using quoted string.

Epic CRDB-33829

Jira issue: CRDB-44290

**Comment by souravcrl** [comment]
blathers backport 24.3.0-rc

**Comment by rafiss** [comment]
I'm reopening as the REVOKE code path still needs to be updated too. Doing that here: https://github.com/cockroachdb/cockroach/pull/135028

Also, is this a GA blocker?
