### ISSUE TITLE
sql: COPY from .sql file fails and causes cockroach to consume 100% of CPU

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/cockroach#13490]
### Version

~~~
cockroach version
Build Tag:    add11bf
Build Time:   2017/02/07 17:17:19
Distribution: CCL
Platform:     darwin amd64
Go Version:   go1.7.1
C Compiler:   4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)
Build SHA-1:  add11bf07ec75b4293979490b93c74224665dda2
Build Type:   development
~~~

## Steps to Repro

1. Create `import.sql` file with following contents:
   ~~~
   CREATE TABLE playground (
       equip_id integer NOT NULL,
       type character varying(50) NOT NULL,
       color character varying(25) NOT NULL,
       location character varying(25),
       install_date date
   );
   
   
   COPY playground (equip_id, type, color, location, install_date) FROM stdin;
   1	slide	blue	south	2014-04-28
   2	swing	yellow	northwest	2010-08-16
   \.
   ~~~

2. Start cockroach.

3. Run `pg_dump`-compatible import:
   `psql -p 26257 -h 127.0.0.1 -d pgdumptest -U root < import.sql`

## Expected result

Import completes, running `CREATE TABLE` and `COPY` statements successfully.

## Actual result

`CREATE TABLE` executes and then terminal hangs.

Running `top -s1` shows `cockroach` process consuming 100% of CPU.

**Comment by mjibson** [comment]
This works on my machine. Can you try rebuilding cockroach from master to see if you still have a problem?

**Comment by sploiselle** [comment]
Cause of issue identified in #13847; closing this issue
