### ISSUE TITLE
ui: Log events for all DDL statements

### ISSUE THREAD

**Issue by mrtracy** [cockroachdb/cockroach#13492]
Our event logs currently only record a subset of DDL statements (statements which alter the schema or other metadata).  Examples of DDL statements that are not currently logged:

- [ ] Database Rename
- [ ] Table Rename
- [ ] Index Alteration
- [ ] GRANT on any database object
- [ ] REVOKE on any database object
- [ ] User-related DDL statements

There may be other examples, but this is the list of unchecked items taken from #3725.

**Comment by jordanlewis** [comment]
Hey @solongordon I think some of these would be pretty to add - I checked a couple and they're still missing from the events page in the web ui.

**Comment by neeral** [comment]
@mrtracy are there any remaining items from the list in the initial [comment](https://github.com/cockroachdb/cockroach/issues/13492#issue-206310430) on this issue? If not, could this issue be closed?

**Comment by jordanlewis** [comment]
Hey @neeral, I think we can close this one thanks to your work!
