### ISSUE TITLE
perf: massive latency increase after upgrade

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#13507]
`cyan` was upgraded a few times overnight: all times UTC.
22h: ff184d2
23h: 5e945a2
03h: 04f2ead
08h: 298907e

At 23h, sql latency went through the roof, 99th from ~1s to ~17s, but for a single node only, and not the same node after another restart.
Prometheus and admin UI agree:
<img width="1277" alt="screen shot 2017-02-09 at 8 35 29 am" src="https://cloud.githubusercontent.com/assets/5901480/22785576/d41b5500-eea2-11e6-8269-2e2f0304fea6.png">

This matches a sizeable increase in leader-not-leaseholder ranges (constantly around 1.2K).
<img width="1428" alt="screen shot 2017-02-09 at 8 35 47 am" src="https://cloud.githubusercontent.com/assets/5901480/22785617/0d05e54c-eea3-11e6-9996-2186fcd71411.png">

The changes between 22h and 23h are:

petermattis/pmattis/sync-raft-log 5e945a2  
andreimatei/remove-lease-acquisition-o… 7b91fbc  
petermattis/pmattis/raft-entry-cache ddbcd15

While I was expecting some increase in latency and lower qps due to raft log syncing, this looks like something else.

**Comment by mberhault** [comment]
FYI: this is `cobalt` before/after upgrade to 04f2ead at 5h UTC:
<img width="921" alt="screen shot 2017-02-09 at 8 40 41 am" src="https://cloud.githubusercontent.com/assets/5901480/22785746/93f5a380-eea3-11e6-83de-df7ee7b62f36.png">

The "steps" in qps match range splits.

**Comment by petermattis** [comment]
Can we try setting `COCKROACH_SYNC_RAFT_LOG=false`?

**Comment by mberhault** [comment]
yup, that was my next step.

**Comment by petermattis** [comment]
We may want to flip the default for that setting until we have further testing on various cloud platforms?

**Comment by mberhault** [comment]
I think so, though we have a week before the next beta (that change didn't make it this week), and one of the things on my place today is running the loadgen with/without it. behavior with increasing cluster size (eg: cobalt) needs to be looked into as well

**Comment by mberhault** [comment]
continuous deployment on `cyan` paused, and binaries (still at 298907e) restarted with `COCKROACH_SYNC_RAFT_LOG="false"`

**Comment by mberhault** [comment]
2 minute run looks good so far:
<img width="1426" alt="screen shot 2017-02-09 at 9 12 28 am" src="https://cloud.githubusercontent.com/assets/5901480/22786783/ed752774-eea7-11e6-85b5-2a46618a0454.png">

I'll keep it running for a bit, then flip it back to `true` so we can take a look. I'm particularly surprised by the single-node 17s latency.

**Comment by petermattis** [comment]
Perhaps Azure SSD has some surprising performance.

**Comment by mberhault** [comment]
it's possible. We can flip it on `omega` (GCE local ssd) and see what happens

**Comment by mberhault** [comment]
Turned it back to true on `cyan`, experienced about 5 minutes of chaos, then back to the previously-seen single-node-with-very-high-latency:
<img width="950" alt="screen shot 2017-02-09 at 9 30 10 am" src="https://cloud.githubusercontent.com/assets/5901480/22787464/7b72b710-eeaa-11e6-8b1e-0ca05872535b.png">

This time, it's https://cockroach-cyan-0001.crdb.io:8080/ clocking in at 17s 99th percentile.

We also have a slowly-increasing leader-not-leaseholder count:
<img width="953" alt="screen shot 2017-02-09 at 9 34 56 am" src="https://cloud.githubusercontent.com/assets/5901480/22787689/232e5a4a-eeab-11e6-85ca-e702ec191235.png">

raft ops on cyan-0001 are increasingly `TimeoutNow`:
<img width="1095" alt="screen shot 2017-02-09 at 9 36 19 am" src="https://cloud.githubusercontent.com/assets/5901480/22787760/642ba4bc-eeab-11e6-8211-502cfd37eea9.png">

**Comment by mberhault** [comment]
syncing slows everything down. Not much more to debug here.
