### ISSUE TITLE
stability: insufficient metrics into Raft actions

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#13523]
#13506 was caused by Raft snapshots being silently ignored due to having an incorrect term in the `raftpb.Message` envelope. The dropped snapshots only became visible when we enabled `--vmodule=raft=2` which showed Raft "info"-level messages. It would be good to have greater visibility into Raft actions such as messages being dropped. Could the `raft.Storage` interface be extended to provide notification of these events? Or perhaps we could add an optional `raft.Events` interface?

Cc @bdarnell, @cockroachdb/stability

**Comment by bdarnell** [comment]
It would be straightforward to add a new interface for this (we already have `raft.Storage` and `raft.Logger`). It's just a matter of deciding what the interface should look like and what events should be tracked.

**Comment by petermattis** [comment]
#17741 seems to have been caused by Raft dropping proposals during leadership transfer combined with a bug where we were quiescing a replica when it wasn't the leaseholder. This would have been much easier to track down if we could see on the Range debug page that one of the replicas for the range was in the leadership transfer state and a count of the number of dropped proposals. We should enhance our visibility into Raft in 1.2.

**Comment by bdarnell** [comment]
The leadership transfer state is already exposed in the `raft.Status` struct, so we could add a metric for this easily. (Getting information about proposals that are dropped for this reason would require changes to raft upstream)

**Comment by petermattis** [comment]
Oh, we should probably use the presence of `raft.Status.LeadTransferee` to prevent quiescence. That would have also avoided #17741.

**Comment by petermattis** [comment]
@bdarnell Not sure if you have any bandwidth to do anything here for 2.0. If not, we should punt to 2.1.

**Comment by bdarnell** [comment]
Probably not happening for 2.0 (although there are changes afoot upstream that would expose this dropped proposal event to us, and we might pick those up in time to get this metric).

**Comment by tschottdorf** [comment]
We do have logspy, and there isn't any concrete proposal here, so I'm going to close. Feel free to reopen.
