### ISSUE TITLE
sql: add benchmarks for schema change backfill execution

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#13538]
We need to add benchmarks for all the schema change backfill operations so we can track performance as we make performance improvements, as well as ensure no decline in performance.

**Comment by vivekmenezes** [comment]
https://github.com/cockroachdb/cockroach/pull/16421 is a good example of how this could be done.

**Comment by vivekmenezes** [comment]
related to #12424

**Comment by jordanlewis** [comment]
Hey @dt, this one is pretty clearly in the Bulk IO side IMO but we've slung it back and forth several times. I would guess you can close it, but I'll leave it up to you, thanks!

**Comment by mwang1026** [comment]
Closing in favor of https://github.com/cockroachdb/cockroach/issues/54528
