### ISSUE TITLE
sql: TestLogicDistSQL doubles the time it takes to run tests

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#13549]
Running the sql tests take around 90 seconds on my machine. This time has essentially doubled from around 45 seconds with the introduction of TestLogicDistSQL . We need to speed up all the SQL tests. This can involve:

1. Running the test setup() only once for the entire set of tests thereby bring up a TestCluster once and running all the SQL statements from all the files on the same cluster. This will involve using different table names in all the tests, or adding a filename prefix for all the tablenames.
2. Once the tests use different table names, we can run each test file in a different thread.

**Comment by andreimatei** [comment]
note that there a `make testshort` target that avoids the logic tests with distsql

**Comment by a-robinson** [comment]
[@jordanlewis played around with the first idea previously and found that trying to drop tables between tests was actually slower than creating a new testserver for every subtest](https://github.com/cockroachdb/cockroach/pull/11719#issuecomment-265003891). You could modify the tests such that they can just be run in separate namespaces/databases, but would have to do something with all the tests that read the system tables.

**Comment by jordanlewis** [comment]
Modifying the tests to use different namespaces/databases would also lead you to encounter a whole new set of problems in the `information_schema` and `pg_catalog` tests, as all databases show up in those tables. You'd have to do a bit of work to have the test queries ignore the irrelevant databases.

**Comment by jordanlewis** [comment]
Closing, I don't think there's much to be done here. Re-open if you like.
