### ISSUE TITLE
sql: CREATE VIEW doesn't clear avoidCachedDescriptors

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#13547]
CreateView sets avoidCachedDescriptors on the planner (and thus on the session) but does not clear it. That means a later `AS OF SYSTEM TIME` in the same session but in an invalid place (like `CREATE TABLE t AS SELECT ... AS OF SYSTEM TIME`) will succeed.

@a-robinson

**Comment by a-robinson** [comment]
Oh wow, I didn't realize the same planner was reused for the entire session (as got brought up in gitter). Taking a look.
