### ISSUE TITLE
ui: Inconsistent calculation of "Used" space for nodes

### ISSUE THREAD

**Issue by mrtracy** [cockroachdb/cockroach#13548]
Our monitoring systems currently use a few different methods to display a node's "used space" in the UI, which is causing confusion. We should converge on a single calculation for this statistic.

#### Current State

+ The "Node List" table uses a set of combined values from the MVCC stats for the node's stores (liveBytes + intentBytes + sysBytes).
+ The "Capacity" value on the node overview summary uses the "capacity.available" and "capacity.total" stats to compute used and total size for the cluster.

However, the "capacity" stats are themselves different depending on if the user has specified a maximum size for a store.

+ If a maximum size is specified, "capacity.total" is that maximum size, while "capacity.available" is that maximum size minus the computed size of all files in the store's file directory.
+ If no maximum size is specified, "capacity.total" is the total size of the store's disk taken from `gosigar`, while "capacity.available" is the available byte count for the disk, also taken from `gosigar`.

#### What is correct

In my opinion, the "capacity" calculation on stores with a maximum size is the most correct of these three.  The "MVCC stats" method does not consider non-live bytes or any additional overhead in rocksdb; it also does not provide a "total" size of the disk.

In the case where no maximum size is specified for a store, I would suggest we use the following computations:

+ Used = (Total used by CockroachDB files)
+ Available = (Disk Available from Gosigar) - (Used by CockroachDB files)
+ Total = (Total from Gosigar)

The reason for keeping a separate for "Total" and "Available" is that this allows us to track the case where the disk is consumed by another application; currently, we have no notion of that.

The "MVCC Stats" method might still have merit for computing "valuable" used disk space, but it would primarily be useful to contrast with the total "used" taken from the file system; that would let us determine how much space is being taken up by dead data, log files, SSTables, etc.

**Comment by vivekmenezes** [comment]
The capacity used values are larger than the mvcc values pointing to the mvcc values possibly being more conservative.

**Comment by petermattis** [comment]
`storage/engine.RocksDB.Capacity()` computes the on-disk size of the RocksDB files. It then uses this to adjust the returned `Capacity.Available` value. Seems like we should directly return a `Capacity.Used` field.
