### ISSUE TITLE
ui: show 10 nodes graphically in the admin UI 

### ISSUE THREAD

**Issue by kuanluo** [cockroachdb/cockroach#13557]
Part of #13184 

## Objective: Accelerate new users’ understanding of CockroachDB by showcasing our value props visually.

**Stats to show (1-8 being the most important, 9-10 are stretch goals)**:

- [x] 1. Number of replicas -> replica count per node. See outliers in the cluster. This is showing replicas flowing to new node
- [x] 2. Leaseholders: you look for the count of leaseholders on a single node. You want the lease holders to be equally distributed across nodes.
- [x] 3. Capacity & usage. % used is very important. 
- [ ] 4. Inter/intra network traffic: Inter: round trip time / throughput both directions (bytes + requests per second) ~10ms range; Intra: round trip time / throughput both direction  <1ms range
- [ ] 5. Recovery metric: How much recovery there is left (we have raw count)? Time-based? Count-down? raw-count? 
- [ ] 6. Unavailability per node: how long it’s been last alive. Per node liveness information. Node is green, yellow -> red (counter, elapsed time “it’s been down for an hour”)
- [ ] 7. Throughput for client request / latency for client request on a per node basis 
- [x] 8. Grouping nodes by Localities [structural] 
- Restart a cluster and add SSD to it.
- Data centers: Configuration is very general. They can do whatever they want. UI can show two levels or three levels of configurations. If we have multi-center set up, you want to see what the setup in each setup 

- [ ] 9.*User create data on table. Can we show where my data is across data centers?  
- Some table database selectors or something sort of ui display 
- Highlight our value props 

- [ ] 10.*Snapshot per node / cluster 

**Considerations**:
1. Let design experiment to see how many information we can offer at once first, and consider alternative ways (eg: toggle) to display different information  
2.  Make sure the node graphics are reusable in the future
- Most important to get the single node inTake non-network related one and display these information per node -> atlas (many of them will feature nodes) 

cc @maxlang @mrtracy @vivekmenezes @petermattis @spencerkimball  @dianasaur323

**Comment by kuanluo** [comment]
@petermattis @mrtracy @maxlang Some questions:

> 5. Recovery metric: How much recovery there is left (we have raw count)? Time-based? Count-down? raw-count?
> 6. Unavailability per node: how long it’s been last alive. Per node liveness information. Node is green, yellow -> red (counter, elapsed time “it’s been down for an hour”)

For the above stats, should we surface only when a node is down? Otherwise, would the default value always be zero/NA?

> 7. Throughput for client request / latency for client request on a per node basis 

We currently have QPS and P50/99 latency in the Summary (screenshot from `blue`). Are those the right numbers for client request throughput and latency?
![image](https://cloud.githubusercontent.com/assets/1486483/23234688/dbd4bfc4-f920-11e6-9256-57042c800d8a.png)

**Comment by kuanluo** [comment]
Good inspiration on toggling between modes of visualization: http://www.nytimes.com/interactive/2012/02/13/us/politics/2013-budget-proposal-graphic.html?_r=0

**Comment by dianasaur323** [comment]
Moving to 1.2. cc @josueeee so he knows that these metrics should be incorporated into cluster viz

**Comment by couchand** [comment]
Closing this as there isn't anything actionable left.
