### ISSUE TITLE
cli: History should group statements entered on the same line

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#13562]
Sometimes while testing I will enter two semicolon-delimited SQL statements on the same line and would like to be able to repeat that pair of statements with `(up-arrow, enter)`. (Motivating example: `drop database foo; create database foo`). In most CLIs that works fine, but our "normalization" splits them up and treats them as separate history entries (turning this into `(up, up, enter, up, up, enter)`). I don't think we should split up commands that were entered on the same line like this (but I like that we join the separate lines of a single command entered on multiple lines).

**Comment by dianasaur323** [comment]
assigning to knz for reassignment
