### ISSUE TITLE
Sentry: error.go:78: unexpected error from the vectorized engine: node unavailable; try another peer
(1)
Wraps: (2)
Wraps: (3) assertion failure
Wraps: (4) attached stack trace
  -- stack trace:
  | g...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#135687]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/6075081381/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/6075081381/?referrer=webhooks_plugin)

Panic Message:

```
error.go:78: unexpected error from the vectorized engine: node unavailable; try another peer
(1)
Wraps: (2)
Wraps: (3) assertion failure
Wraps: (4) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:78
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:770
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.InternalError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:291
  | github.com/cockroachdb/cockroach/pkg/sql/colfetcher.(*ColIndexJoin).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colfetcher/index_join.go:226
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils.(*CancelChecker).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils/cancel_checker.go:59
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils.(*vectorTypeEnforcer).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils/operator.go:157
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*tupleProjOp).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/tuple_proj_op.go:59
  | github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecbase.(*simpleProjectOp).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecbase/simple_project.go:124
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Materializer).next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:251
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Materializer).nextAdapter
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:276
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:152
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Materializer).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:282
  | github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*windower).accumulateRows
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowexec/windower.go:265
  | github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*windower).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowexec/windower.go:217
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*FlowCoordinator).next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:124
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*FlowCoordinator).nextAdapter
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:141
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:152
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*FlowCoordinator).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:146
  | github.com/cockroachdb/cockroach/pkg/sql/execinfra.Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/execinfra/base.go:199
  | github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBaseNoHelper).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:732
  | github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:579
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:305
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:932
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1994
  | github.com/cockroachdb/cockroach/pkg/sql.runPlanInsidePlan.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/apply_join.go:362
  | github.com/cockroachdb/cockroach/pkg/sql.runPlanInsidePlan
  | 	github.com/cockroachdb/cockroach/pkg/sql/apply_join.go:365
  | github.com/cockroachdb/cockroach/pkg/sql.(*applyJoinNode).runNextRightSideIteration
  | 	github.com/cockroachdb/cockroach/pkg/sql/apply_join.go:257
  | github.com/cockroachdb/cockroach/pkg/sql.(*applyJoinNode).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/apply_join.go:222
  | github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:216
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Columnarizer).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/columnarizer.go:239
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.getNext_false
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/colexec/hash_aggregator.eg.go:540
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*hashAggregator).Next
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/colexec/hash_aggregator.eg.go:90
Wraps: (5) unexpected error from the vectorized engine
Wraps: (6) node unavailable; try another peer
  | -- cause hidden behind barrier
  | node unavailable; try another peer
  | (1) node unavailable; try another peer
  | Error types: (1) *kvpb.NodeUnavailableError
Error types: (1) *colexecerror.notInternalError (2) *colexecerror.notInternalError (3) *assert.withAssertionFailure (4) *withstack.withStack (5) *errutil.withPrefix (6) *barriers.barrierErr
-- report composition:
*barriers.barrierErr: masked error: node unavailable; try another peer
*errutil.withPrefix: unexpected error from the vectorized engine
error.go:78: *withstack.withStack (top exception)
*assert.withAssertionFailure
*colexecerror.notInternalError
*colexecerror.notInternalError
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/bazel-out/k8-opt/bin/pkg/sql/colexec/hash_aggregator.eg.go#L89-L91](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/bazel-out/k8-opt/bin/pkg/sql/colexec/hash_aggregator.eg.go#L89-L91)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/bazel-out/k8-opt/bin/pkg/sql/colexec/hash_aggregator.eg.go#L539-L541](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/bazel-out/k8-opt/bin/pkg/sql/colexec/hash_aggregator.eg.go#L539-L541)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexec/columnarizer.go#L238-L240](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexec/columnarizer.go#L238-L240)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/plan_node_to_row_source.go#L215-L217](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/plan_node_to_row_source.go#L215-L217)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/apply_join.go#L221-L223](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/apply_join.go#L221-L223)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/apply_join.go#L256-L258](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/apply_join.go#L256-L258)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/apply_join.go#L364-L366](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/apply_join.go#L364-L366)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/apply_join.go#L361-L363](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/apply_join.go#L361-L363)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/distsql_running.go#L1993-L1995](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/distsql_running.go#L1993-L1995)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/distsql_running.go#L931-L933](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/distsql_running.go#L931-L933)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colflow/vectorized_flow.go#L304-L306](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colflow/vectorized_flow.go#L304-L306)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/flowinfra/flow.go#L578-L580](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/flowinfra/flow.go#L578-L580)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/execinfra/processorsbase.go#L731-L733](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/execinfra/processorsbase.go#L731-L733)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/execinfra/base.go#L198-L200](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/execinfra/base.go#L198-L200)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colflow/flow_coordinator.go#L145-L147](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colflow/flow_coordinator.go#L145-L147)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexecerror/error.go#L151-L153](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexecerror/error.go#L151-L153)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colflow/flow_coordinator.go#L140-L142](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colflow/flow_coordinator.go#L140-L142)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colflow/flow_coordinator.go#L123-L125](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colflow/flow_coordinator.go#L123-L125)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/rowexec/windower.go#L216-L218](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/rowexec/windower.go#L216-L218)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/rowexec/windower.go#L264-L266](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/rowexec/windower.go#L264-L266)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexec/materializer.go#L281-L283](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexec/materializer.go#L281-L283)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexecerror/error.go#L151-L153](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexecerror/error.go#L151-L153)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexec/materializer.go#L275-L277](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexec/materializer.go#L275-L277)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexec/materializer.go#L250-L252](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexec/materializer.go#L250-L252)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexec/colexecbase/simple_project.go#L123-L125](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexec/colexecbase/simple_project.go#L123-L125)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexec/tuple_proj_op.go#L58-L60](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexec/tuple_proj_op.go#L58-L60)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexec/colexecutils/operator.go#L156-L158](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexec/colexecutils/operator.go#L156-L158)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexec/colexecutils/cancel_checker.go#L58-L60](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexec/colexecutils/cancel_checker.go#L58-L60)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colfetcher/index_join.go#L225-L227](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colfetcher/index_join.go#L225-L227)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexecerror/error.go#L290-L292](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexecerror/error.go#L290-L292)
[GOROOT/src/runtime/panic.go#L769-L771](GOROOT/src/runtime/panic.go#L769-L771)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexecerror/error.go#L77-L79](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/colexecerror/error.go#L77-L79)
</details>

```
bazel-out/k8-opt/bin/pkg/sql/colexec/hash_aggregator.eg.go in pkg/sql/colexec.(*hashAggregator).Next at line 90
bazel-out/k8-opt/bin/pkg/sql/colexec/hash_aggregator.eg.go in pkg/sql/colexec.getNext_false at line 540
pkg/sql/colexec/columnarizer.go in pkg/sql/colexec.(*Columnarizer).Next at line 239
pkg/sql/plan_node_to_row_source.go in pkg/sql.(*planNodeToRowSource).Next at line 216
pkg/sql/apply_join.go in pkg/sql.(*applyJoinNode).Next at line 222
pkg/sql/apply_join.go in pkg/sql.(*applyJoinNode).runNextRightSideIteration at line 257
pkg/sql/apply_join.go in pkg/sql.runPlanInsidePlan at line 365
pkg/sql/apply_join.go in pkg/sql.runPlanInsidePlan.func2 at line 362
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRun at line 1994
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).Run at line 932
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlow).Run at line 305
pkg/sql/flowinfra/flow.go in pkg/sql/flowinfra.(*FlowBase).Run at line 579
pkg/sql/execinfra/processorsbase.go in pkg/sql/execinfra.(*ProcessorBaseNoHelper).Run at line 732
pkg/sql/execinfra/base.go in pkg/sql/execinfra.Run at line 199
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*FlowCoordinator).Next at line 146
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 152
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*FlowCoordinator).nextAdapter at line 141
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*FlowCoordinator).next at line 124
pkg/sql/rowexec/windower.go in pkg/sql/rowexec.(*windower).Next at line 217
pkg/sql/rowexec/windower.go in pkg/sql/rowexec.(*windower).accumulateRows at line 265
pkg/sql/colexec/materializer.go in pkg/sql/colexec.(*Materializer).Next at line 282
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 152
pkg/sql/colexec/materializer.go in pkg/sql/colexec.(*Materializer).nextAdapter at line 276
pkg/sql/colexec/materializer.go in pkg/sql/colexec.(*Materializer).next at line 251
pkg/sql/colexec/colexecbase/simple_project.go in pkg/sql/colexec/colexecbase.(*simpleProjectOp).Next at line 124
pkg/sql/colexec/tuple_proj_op.go in pkg/sql/colexec.(*tupleProjOp).Next at line 59
pkg/sql/colexec/colexecutils/operator.go in pkg/sql/colexec/colexecutils.(*vectorTypeEnforcer).Next at line 157
pkg/sql/colexec/colexecutils/cancel_checker.go in pkg/sql/colexec/colexecutils.(*CancelChecker).Next at line 59
pkg/sql/colfetcher/index_join.go in pkg/sql/colfetcher.(*ColIndexJoin).Next at line 226
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.InternalError at line 291
GOROOT/src/runtime/panic.go in runtime.gopanic at line 770
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1 at line 78
```

### Tags

| Tag | Value |
| --- | --- |
| Command | mt start-sql |
| Environment | v24.2.4 |
| Go Version | go1.22.5 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v24.2.4 |
| Cockroach SHA | 8140b8e294fb16a293d0aae662bcf5c1d488c852 |
| # of CPUs | 32 |
| # of Goroutines | 218 |

Jira issue: CRDB-44678

**Comment by yuzefovich** [comment]
dup of #128649
