### ISSUE TITLE
storage: Remove or fix "initial metrics computation"

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#13560]
As soon as gossip is connected, we attempt to compute the store metrics: https://github.com/cockroachdb/cockroach/blob/6e9c78f05fdd06bec380ab701a7f422cd0564a10/pkg/storage/store.go#L1250-L1262

This (nearly) always fails because gossip becomes connected before the system config is available. It logs a INFO message and then we discard the error. (This line appears in the logs of nearly all our tests, and is the only message in the logs for many tests). 

We should either wait for the system config to be available before computing metrics or remove the call completely since it's consistently failing.

**Comment by dianasaur323** [comment]
@bdarnell - going to assign this to you for now, but perhaps we should reassign.

**Comment by bdarnell** [comment]
This is just a test cleanup issue, so moving post 1.0.

**Comment by bdarnell** [comment]
Bumping to "Later" and unassigning this test-cleanup issue.
