### ISSUE TITLE
Consider making `kv.dist_sender.concurrency_limit` cluster setting public in at least v24.3, possibly v24.1+ 

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/cockroach#135615]
We are working on adding it to docs as a performance recommendation in some scenarios (see PR https://github.com/cockroachdb/docs/pull/19096 for details)

via @sean- in discussion on the docs PR:

> we decided to not backport the change per discussion in: https://github.com/cockroachdb/cockroach/pull/131535#issuecomment-2380069779

however, perhaps we would be willing to flip the setting to public on v24.1 and v24.2 even if we don't want to change the default

Jira issue: CRDB-44656

Epic CRDB-43580

**Comment by arulajmani** [comment]
@rmloveland, it turns out that these two settings take their default value from `GOMAXPROCS`, which is dependent on the machine they run on. This makes making the setting public hard, as the generated docs expect a constant value for public cluster settings.
