### ISSUE TITLE
rac2: chronic send-queue in apply_to_all causes problems with splits, merges, and below-raft migrations

### ISSUE THREAD

**Issue by sumeerbhola** [cockroachdb/cockroach#135601]
See the reproduction in unit tests in https://github.com/cockroachdb/cockroach/pull/135339 and discussion in https://cockroachlabs.slack.com/archives/C06UFBJ743F/p1731949918262989 and https://cockroachlabs.slack.com/archives/C06UFBJ743F/p1731706469382499.

Since the `SplitTrigger` does not apply at the state machine on the replica with the send-queue, the timeout of 20s in `maybeDropMsgApp` where the store with the uninitialized RHS rejects MsgApps, eventually expires. The uninitialized replica returns a MsgAppResp, which triggers a snapshot to be sent to the replica. These snapshots cannot apply since they overlap with the unsplit range, and cause a `snapshot intersects existing range; initiated GC:` error. This is wasteful.

Both merge and below-raft migrations call `waitForApplication` which waits for all replicas to apply some command (`SubsumeRequest` and `MigrateRequest` respectively). These exceed the deadline when a replica has a chronic send-queue.

Some solutions involving force-flushing are discussed in https://cockroachlabs.slack.com/archives/C06UFBJ743F/p1731949918262989.

Note that force-flushing should be ok for splits and merges since only a tiny subset of ranges on an overloaded store should get force-flushed. For a below-raft migration, force-flushing will affect all ranges, so there is a much higher probability of extreme overload. However, AFAIK, we have had only 3 below-raft migrations in history: truncatedAndRangeAppliedStateMigration, migration for separated intents, addRaftAppliedIndexTermMigration. The last one was in Feb 2022. So these are very rare. The rarity of such migrations suggests that perhaps we can get away with providing some instruction to cluster operators to take a look at cluster health and ensure empty send-queues before starting an upgrade that involves such a migration.

Jira issue: CRDB-44654

Epic CRDB-42900

**Comment by pav-kv** [comment]
> For a below-raft migration, force-flushing will affect all ranges, so there is a much higher probability of extreme overload.

Maybe we could decouple sending the migration command to all ranges vs waiting for all replicas to apply this migration. The latter doesn't seem to be critical to complete timely. We only need this condition for phasing out the old code, which happens across releases.

Other improvement ideas here: #72931.

**Comment by sumeerbhola** [comment]
Not yet fixed for merge since SubsumeRequest is a read request and does not get replicated.
