### ISSUE TITLE
ua:  tsdump export is unsupported

### ISSUE THREAD

**Issue by kvoli** [cockroachdb/cockroach#135720]
TSE reported that they are unable to gather a TSDump from a unified architecture cluster in https://github.com/cockroachlabs/support/issues/3127.

TSDumps have become a vital part of debugging production issues that arise within the database. Without them, a large fraction of the observability which is added (with the presumption of its availability in nearly all cases) is lost.

```
$ debug tsdump --format=raw --host=crdb-tyes-pr-01 --certs-dir=... > tsdump.gob; gzip tsdump.gob
ERROR: unimplemented: operation is unsupported within a virtual cluster
SQLSTATE: 0A000
HINT: You have attempted to use a feature that is not yet implemented.
See: [go.crdb.dev/issue-v/54252/v23.2](https://go.crdb.dev/issue-v/54252/v23.2)
```

This was on v23.2.6 running PCR.

Jira issue: CRDB-44685

**Comment by smcvey** [comment]
The tsdump command attempts to connect to the 'default' virtual cluster, so if the cluster setting `server.controller.default_target_cluster` is set to anything other than `system`, then it fails with an error message.  However, it can be bypassed by explicitly specifying the `system` cluster in the URL, eg:

```
cockroach debug tsdump --format=raw --url "postgresql://<address>:<port>?options=-ccluster%3Dsystem" > tsdump.gob
```
