### ISSUE TITLE
Sentry: structured.go:2303: × uses external row data
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:770
  | [...repeated from below...]
Wraps: (2) ass...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#135754]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/6076217520/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/6076217520/?referrer=webhooks_plugin)

Panic Message:

```
structured.go:2303: × uses external row data
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:770
  | [...repeated from below...]
Wraps: (2) assertion failure
Wraps: (3) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/tabledesc.(*wrapper).TableSpan
  | 	pkg/sql/catalog/tabledesc/structured.go:2303
  | github.com/cockroachdb/cockroach/pkg/sql.populateClusterLocksWithFilter.genClusterLocksGenerator.func1
  | 	pkg/sql/crdb_internal.go:8023
  | github.com/cockroachdb/cockroach/pkg/sql.populateClusterLocksWithFilter
  | 	pkg/sql/crdb_internal.go:8233
  | github.com/cockroachdb/cockroach/pkg/sql.init.genPopulateClusterLocksWithIndex.func962
  | 	pkg/sql/crdb_internal.go:8220
  | github.com/cockroachdb/cockroach/pkg/sql.(*virtualDefEntry).getPlanInfo.func1.(*virtualDefEntry).makeConstrainedRowsGenerator.2
  | 	pkg/sql/virtual_schema.go:836
  | github.com/cockroachdb/cockroach/pkg/sql.setupGenerator.func3
  | 	pkg/sql/virtual_table.go:122
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	pkg/util/stop/stopper.go:498
  | runtime.goexit
  | 	src/runtime/asm_amd64.s:1695
Wraps: (4) × uses external row data
Error types: (1) *withstack.withStack (2) *assert.withAssertionFailure (3) *withstack.withStack (4) *errutil.leafError
-- report composition:
*errutil.leafError: × uses external row data
structured.go:2303: *withstack.withStack (top exception)
*assert.withAssertionFailure
panic.go:770: *withstack.withStack (1)
(check the extra data payloads)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_amd64.s#L1694-L1696](src/runtime/asm_amd64.s#L1694-L1696)
[pkg/util/stop/stopper.go#L497-L499](pkg/util/stop/stopper.go#L497-L499)
[pkg/sql/virtual_table.go#L121-L123](pkg/sql/virtual_table.go#L121-L123)
[pkg/sql/virtual_schema.go#L835-L837](pkg/sql/virtual_schema.go#L835-L837)
[pkg/sql/crdb_internal.go#L8219-L8221](pkg/sql/crdb_internal.go#L8219-L8221)
[pkg/sql/crdb_internal.go#L8232-L8234](pkg/sql/crdb_internal.go#L8232-L8234)
[pkg/sql/crdb_internal.go#L8022-L8024](pkg/sql/crdb_internal.go#L8022-L8024)
[pkg/sql/catalog/tabledesc/structured.go#L2302-L2304](pkg/sql/catalog/tabledesc/structured.go#L2302-L2304)
[GOROOT/src/runtime/panic.go#L769-L771](GOROOT/src/runtime/panic.go#L769-L771)
[src/runtime/asm_amd64.s#L1694-L1696](src/runtime/asm_amd64.s#L1694-L1696)
[pkg/util/stop/stopper.go#L497-L499](pkg/util/stop/stopper.go#L497-L499)
[pkg/sql/virtual_table.go#L121-L123](pkg/sql/virtual_table.go#L121-L123)
[pkg/sql/virtual_schema.go#L835-L837](pkg/sql/virtual_schema.go#L835-L837)
[pkg/sql/crdb_internal.go#L8219-L8221](pkg/sql/crdb_internal.go#L8219-L8221)
[pkg/sql/crdb_internal.go#L8232-L8234](pkg/sql/crdb_internal.go#L8232-L8234)
[pkg/sql/crdb_internal.go#L8022-L8024](pkg/sql/crdb_internal.go#L8022-L8024)
[pkg/sql/catalog/tabledesc/structured.go#L2302-L2304](pkg/sql/catalog/tabledesc/structured.go#L2302-L2304)
</details>

```
src/runtime/asm_amd64.s in runtime.goexit at line 1695
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 498
pkg/sql/virtual_table.go in pkg/sql.setupGenerator.func3 at line 122
pkg/sql/virtual_schema.go in pkg/sql.(*virtualDefEntry).getPlanInfo.func1.(*virtualDefEntry).makeConstrainedRowsGenerator.2 at line 836
pkg/sql/crdb_internal.go in pkg/sql.init.genPopulateClusterLocksWithIndex.func962 at line 8220
pkg/sql/crdb_internal.go in pkg/sql.populateClusterLocksWithFilter at line 8233
pkg/sql/crdb_internal.go in pkg/sql.populateClusterLocksWithFilter.genClusterLocksGenerator.func1 at line 8023
pkg/sql/catalog/tabledesc/structured.go in pkg/sql/catalog/tabledesc.(*wrapper).TableSpan at line 2303
GOROOT/src/runtime/panic.go in runtime.gopanic at line 770
src/runtime/asm_amd64.s in runtime.goexit at line 1695
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 498
pkg/sql/virtual_table.go in pkg/sql.setupGenerator.func3 at line 122
pkg/sql/virtual_schema.go in pkg/sql.(*virtualDefEntry).getPlanInfo.func1.(*virtualDefEntry).makeConstrainedRowsGenerator.2 at line 836
pkg/sql/crdb_internal.go in pkg/sql.init.genPopulateClusterLocksWithIndex.func962 at line 8220
pkg/sql/crdb_internal.go in pkg/sql.populateClusterLocksWithFilter at line 8233
pkg/sql/crdb_internal.go in pkg/sql.populateClusterLocksWithFilter.genClusterLocksGenerator.func1 at line 8023
pkg/sql/catalog/tabledesc/structured.go in pkg/sql/catalog/tabledesc.(*wrapper).TableSpan at line 2303
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | development |
| Go Version | go1.22.8 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v25.1.0-alpha.00000000-dev-0061bb12acbf3829ebc4869f170f32566387db1f |
| Cockroach SHA | 0061bb12acbf3829ebc4869f170f32566387db1f |
| # of CPUs | 8 |
| # of Goroutines | 786 |

Jira issue: CRDB-44698

**Comment by fqazi** [comment]
Same as: https://github.com/cockroachdb/cockroach/issues/135755
