### ISSUE TITLE
kvclient: introduce an independent knob to reject large write transactions

### ISSUE THREAD

**Issue by arulajmani** [cockroachdb/cockroach#135841]
**Describe the problem**

Currently, the only way to reject large write transactions is `kv.transaction.reject_over_max_intents_budget.enabled`, which rejects any transaction that goes over the `kv.transaction.max_intents_bytes` tracking limit. It's not great that these settings are always tied together [[1]](https://cockroachlabs.slack.com/archives/C081JBE946P/p1732127471595909?thread_ts=1732123002.069389&cid=C081JBE946P). 

We should introduce a new cluster setting to reject large writing transactions that isn't tied to the `kv.transaction.max_intents_bytes` cluster setting.

Jira issue: CRDB-44747

**Comment by andrewbaptist** [comment]
@arulajmani I'm adding a new setting that is completely independent of `kv.transaction.reject_over_max_intents_budget.enabled` and `kv.transaction.max_intents_bytes` for now. I'm going to update the node on `kv.transaction.reject_over_max_intents_budget.enabled` to recommend against using it.

**Comment by arulajmani** [comment]
Sounds good @andrewbaptist. I'll assign the issue to you in that case.
