### ISSUE TITLE
kv: perturbation test for intent resolution

### ISSUE THREAD

**Issue by andrewbaptist** [cockroachdb/cockroach#135937]
**Is your feature request related to a problem? Please describe.**
In a customer case, we saw almost 10 billion intents created over multiple ranges over a 5 hour window from a single INSERT INTO ... SELECT FROM statement that was ultimately aborted. We should create a perturbation test that simulates this behavior and validates that whether the intents are cleaned up by either a conflicting higher priority transaction or the mvcc gc queue. 

**Describe the solution you'd like**
We have seen large availability outages due to LSM inversion when the mvcc gc queue cleaned up these intents.  

**Describe alternatives you've considered**
There is an existing test `registerIntentResolutionOverload` which tests that the LSM does not get too overloaded. We can replace this test with a perturbation test.

Jira issue: CRDB-44796

**Comment by kvoli** [comment]
Removing the O-roachtest label otherwise this ends up in the roachtest triage queue [here](https://github.com/cockroachdb/cockroach/issues?q=is%3Aissue+label%3AO-roachtest+label%3AT-kv%2CT-kv-replication+-label%3AC-bug%2CX-infra-flake%2CX-duplicate%2CX-unactionable+created%3A%3E%3D2022-12-01+).
