### ISSUE TITLE
Alter statements are considered idle for the idle timeout setting

### ISSUE THREAD

**Issue by steven-hubbard** [cockroachdb/cockroach#135930]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

1. Set up CockroachDB cluster
2. SET CLUSTER SETTING sql.defaults.idle_in_session_timeout = '15m';
3. Issue a long running alter command
4. Connection is severed at 15m mark with below error:

```
ERROR: unexpected EOF
ERROR: connection lost.

unexpected EOF
Failed running "sql"

```

For testing we dropped the timeout to 10s and did confirm that this setting will respect a session setting for idle_in_session_timeout.

**Environment:**
 - CockroachDB version [23.2.11]
 - Server OS: Linux
 - Client app: ockroach sql

**Additional context**
What was the impact?

I can create a separate issue for this one, but it could potentially be related to server.web_session.timeout. In this case if I have the DBConsole up and am actively moving through pages or dashboards, I will be signed out regardless of how active I am once the value for web_session.timeout setting has passed. 

Jira issue: CRDB-44791

Epic CRDB-43310

**Comment by spilchen** [comment]
The idle timeout is here:
https://github.com/cockroachdb/cockroach/blob/1348f54828973836dfbcb828a4134cc88917a934/pkg/sql/conn_executor_exec.go#L159-L165

This is where we wait for the background job to finish:
https://github.com/cockroachdb/cockroach/blob/cdd3635167760f3297fe3025f136efbc98cb5563/pkg/sql/conn_executor.go#L4022-L4040

The fix should happen in one or both of these spots.
