### ISSUE TITLE
sql: revisit ordering code for ordinalityNode

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#13594]
During expand plan we have one-off logic for the ordering of ordinalityNode: https://github.com/cockroachdb/cockroach/blob/b02e43f9e6d497f162cdc2fc1d72b5c9364aa00c/pkg/sql/expand_plan.go#L124

This should be better encapsulated in the node itself. The logic also needs to be revisited. We try to pass through a desired ordering even if there is a desired ordering on the ordinality column (code below) but that will never end up being used - what is important is the way we update `n.ordering` afterward; we only use the ordinality ordering if there is no underlying ordering. We also aren't checking for the desired direction of the ordinality column in this code:

```go
// If there's a desired ordering on the ordinality column, drop it.
if len(params.desiredOrdering) > 0 {
	newDesired := make(sqlbase.ColumnOrdering, 0, len(params.desiredOrdering))
	for _, ordInfo := range params.desiredOrdering {
		if ordInfo.ColIdx == len(n.columns)-1 {
			break
		}
		newDesired = append(newDesired, ordInfo)
	}
	params.desiredOrdering = newDesired
}
```
CC @knz

**Comment by knz** [comment]
I do not agree that the desired ordering will not be used if it gets passed through. It's pretty clear it is -- if there's an ORDER BY clause "outside" of WITH ORD on a column of the source, this way we can use that desired ordering to present the rows in the "right order" without needing to sort.

I agree there's an error about the sort order otherwise, and that the code needs be better encapsulated. Will do.

**Comment by knz** [comment]
Huh also I don't think there's an issue with the direction either. Regardless of the direction, the ordering columns must be dropped from the ordering constraint. Then on the way back from the recursion, the sort node (if any was required) will observe that the ordering column is not sorted in the same order as requested and decide to remain.

**Comment by RaduBerinde** [comment]
> I do not agree that the desired ordering will not be used if it gets passed through. It's pretty clear it is -- if there's an ORDER BY clause "outside" of WITH ORD on a column of the source, this way we can use that desired ordering to present the rows in the "right order" without needing to sort.

Sure it needs to be passed in general, the key part was "even if there is a desired ordering on the ordinality column".

I think I confused myself a bit, but there is still a point here - when we have an ordering that contains both the ordinality column and something else, we will always sort because of how we calculate `n.ordering`. Say we have a desired ordering by `a, ordinality`; there isn't much point in selecting an index that gives us `a` because `ordinalityNode.Ordering()` will be `a` and we will sort anyway to get `a,ordinality` (even though we don't need to). Example:

```sql
CREATE TABLE t (k1 INT, k2 INT, v INT, PRIMARY KEY(k1,k2));
EXPLAIN (METADATA) SELECT * FROM t WITH ORDINALITY ORDER BY k1, ordinality;
+-------+------------+-------+-----------------+-------------------------+-----------------+
| Level |    Type    | Field |   Description   |         Columns         |    Ordering     |
+-------+------------+-------+-----------------+-------------------------+-----------------+
|     0 | sort       |       |                 | (k1, k2, v, ordinality) | +k1,+ordinality |
|     0 |            | order | +k1,+ordinality |                         |                 |
|     1 | ordinality |       |                 | (k1, k2, v, ordinality) | +k1,+k2,unique  |
|     2 | scan       |       |                 | (k1, k2, v)             | +k1,+k2,unique  |
|     2 |            | table | t@primary       |                         |                 |
|     2 |            | spans | ALL             |                         |                 |
+-------+------------+-------+-----------------+-------------------------+-----------------+
```
The direction not matching is the same kind of thing - we know we will sort.

Desiring a prefix would still be useful if the `sortNode` could make use of prefix orderings (which it should, and DistSQL already does). So maybe we should just add some comments explaining that in this case we know we won't satisfy the desiredOrdering but it may still be helpful to satisfy a prefix of it.

I guess what we can do to improve these cases is to always append the ordinality column to `n.source.Ordering()`  (unless the latter is `unique`).
