### ISSUE TITLE
sql: optimize `= ANY` like `IN`

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#13593]
Once arrays are supported we run into queries that select specific values with `WHERE s = ANY([a,b,c])` instead of `s IN (a,b,c)`.

We need to support them "just as well" i.e. generate the corresponding index constraints and ultimately KV lookup spans.

For reference, in pg all the `IN` expressions are converted to `= ANY()` internally, and only the latter refines index selection / point lookups.

Reported / detected in #13358.

**Comment by tlvenn** [comment]
Hi @cuongdo, I just wanted to emphasis that per the discussion in #13358, the usage of `ANY` is not as exotic as one may think and many ORMs will favour it over the more conventional `IN` syntax.

So this should impact the overall performance big picture on the read side of things.

**Comment by andy-kimball** [comment]
Like Postgres, the cost-based optimizer maps IN to ANY, so closing this as "Fixed".
