### ISSUE TITLE
descs: catalog cache lookups needlessly allocate (1.42% allocs in oltp_read_only)

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#135905]
`lookupStoreCacheID`[^1] in `oltp_read_only`:

[^1]: https://github.com/cockroachdb/cockroach/blob/6a7b1e20e70c0ba8e6bb7a42d52512d9437cd75b/pkg/sql/catalog/descs/descriptor.go#L555-L567

<img width="1124" alt="image" src="https://github.com/user-attachments/assets/19ea5913-31f1-4876-8dfd-5df2bd451e5f">

It looks like we're heap allocating purely because the `NameKey` for the cache is an interface:

https://github.com/cockroachdb/cockroach/blob/6a7b1e20e70c0ba8e6bb7a42d52512d9437cd75b/pkg/sql/catalog/descriptor.go#L153-L161

This seems unfortunate. We can make a deeper change there or at least pool this particular allocation.

Epic: CRDB-42584

Jira issue: CRDB-44785

**Comment by rafiss** [comment]
This looks like the same as https://github.com/cockroachdb/cockroach/issues/121300. Progress was made in [PR #134216](https://github.com/cockroachdb/cockroach/pull/134216), and there's a bit of discussion over in https://github.com/cockroachdb/cockroach/pull/134219#issuecomment-2455593603.
