### ISSUE TITLE
ui: display progress of backups/restores/schema changes

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#13604]
Tracking issue for displaying incremental progress of backup/restore/schema change jobs in the admin UI. See #12555 for overview.

RFC coming soon.

/cc @danhhz

**Comment by kuanluo** [comment]
Photo of notes from today's meeting: 
![backup-store](https://cloud.githubusercontent.com/assets/1486483/22989803/30795482-f385-11e6-8846-1d247b099929.JPG)

**Comment by vivekmenezes** [comment]
I think we should remove schema changes from this issue. Thoughts?

**Comment by kuanluo** [comment]
@vivekmenezes 

We included schema change as a reminder that it's part of the query type that we should keep in mind for the query progress UI indicators. Not sure if it's part of the engineering work.

**Comment by dianasaur323** [comment]
@jseldess Here is the GitHub issue for the jobs table in the admin UI

**Comment by dianasaur323** [comment]
![image](https://user-images.githubusercontent.com/5768024/27088300-4c1ab5e4-5025-11e7-83b1-466a9feded21.png)
@kuanluo Adding in your most recent mock here.

**Comment by jseldess** [comment]
Thanks, @dianasaur323!
