### ISSUE TITLE
Sentry: collection.go:258: adding uncommitted × × (151) version 1083: memory usage exceeds limit for uncommittedDescriptors: root: memory budget exceeded: 10240 bytes requested, 1610606678 currently...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#136073]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/6085258209/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/6085258209/?referrer=webhooks_plugin)

Panic Message:

```
collection.go:258: adding uncommitted × × (151) version 1083: memory usage exceeds limit for uncommittedDescriptors: root: memory budget exceeded: 10240 bytes requested, 1610606678 currently allocated, 1610612736 bytes in budget
(1)
Wraps: (2) assertion failure
Wraps: (3) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).AddUncommittedDescriptor.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:258
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).AddUncommittedDescriptor
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:273
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).WriteDescToBatch
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:304
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).writeTableDescToBatch
  | 	github.com/cockroachdb/cockroach/pkg/sql/table.go:340
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).writeSchemaChangeToBatch
  | 	github.com/cockroachdb/cockroach/pkg/sql/table.go:297
  | github.com/cockroachdb/cockroach/pkg/sql.(*changeDescriptorBackedPrivilegesNode).startExec
  | 	github.com/cockroachdb/cockroach/pkg/sql/grant_revoke.go:372
  | github.com/cockroachdb/cockroach/pkg/sql.startExec.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan.go:520
  | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:112
  | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:299
  | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:79
  | github.com/cockroachdb/cockroach/pkg/sql.walkPlan
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:43
  | github.com/cockroachdb/cockroach/pkg/sql.startExec
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan.go:523
  | github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Start
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:175
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Columnarizer).Init
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/columnarizer.go:183
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).init
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:94
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).Init
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:103
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).Run.(*BatchFlowCoordinator).init.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:245
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).init
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:244
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:278
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:320
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:905
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1945
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll.func3
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1660
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1663
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2401
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1940
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1125
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:145
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:3399
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:144
Wraps: (4) adding uncommitted × × (151) version 1083
Wraps: (5) memory usage exceeds limit for uncommittedDescriptors: root: memory budget exceeded: 10240 bytes requested, 1610606678 currently allocated, 1610612736 bytes in budget
  | -- cause hidden behind barrier
  | memory usage exceeds limit for uncommittedDescriptors: root: memory budget exceeded: 10240 bytes requested, 1610606678 currently allocated, 1610612736 bytes in budget
  | (1) attached stack trace
  |   -- stack trace:
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*uncommittedDescriptors).upsert
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/uncommitted_descriptors.go:200
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).AddUncommittedDescriptor
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:273
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).WriteDescToBatch
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:304
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*planner).writeTableDescToBatch
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/table.go:340
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*planner).writeSchemaChangeToBatch
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/table.go:297
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*changeDescriptorBackedPrivilegesNode).startExec
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/grant_revoke.go:372
  |   | github.com/cockroachdb/cockroach/pkg/sql.startExec.func2
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/plan.go:520
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal.func1
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:112
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:299
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:79
  |   | github.com/cockroachdb/cockroach/pkg/sql.walkPlan
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:43
  |   | github.com/cockroachdb/cockroach/pkg/sql.startExec
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/plan.go:523
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Start
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:175
  |   | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Columnarizer).Init
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/columnarizer.go:183
  |   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).init
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:94
  |   | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  |   | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).Init
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:103
  |   | github.com/cockroachdb/cockroach...
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/conn_executor_exec.go#L143-L145](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/conn_executor_exec.go#L143-L145)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/conn_executor_exec.go#L3398-L3400](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/conn_executor_exec.go#L3398-L3400)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/conn_executor_exec.go#L144-L146](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/conn_executor_exec.go#L144-L146)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/conn_executor_exec.go#L1124-L1126](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/conn_executor_exec.go#L1124-L1126)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/conn_executor_exec.go#L1939-L1941](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/conn_executor_exec.go#L1939-L1941)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/conn_executor_exec.go#L2400-L2402](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/conn_executor_exec.go#L2400-L2402)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/distsql_running.go#L1662-L1664](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/distsql_running.go#L1662-L1664)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/distsql_running.go#L1659-L1661](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/distsql_running.go#L1659-L1661)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/distsql_running.go#L1944-L1946](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/distsql_running.go#L1944-L1946)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/distsql_running.go#L904-L906](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/distsql_running.go#L904-L906)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/colflow/vectorized_flow.go#L319-L321](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/colflow/vectorized_flow.go#L319-L321)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/colflow/flow_coordinator.go#L277-L279](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/colflow/flow_coordinator.go#L277-L279)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/colflow/flow_coordinator.go#L243-L245](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/colflow/flow_coordinator.go#L243-L245)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/colflow/flow_coordinator.go#L244-L246](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/colflow/flow_coordinator.go#L244-L246)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/colflow/stats.go#L102-L104](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/colflow/stats.go#L102-L104)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/colflow/stats.go#L93-L95](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/colflow/stats.go#L93-L95)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/colexec/columnarizer.go#L182-L184](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/colexec/columnarizer.go#L182-L184)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/plan_node_to_row_source.go#L174-L176](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/plan_node_to_row_source.go#L174-L176)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/plan.go#L522-L524](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/plan.go#L522-L524)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/walk.go#L42-L44](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/walk.go#L42-L44)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/walk.go#L78-L80](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/walk.go#L78-L80)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/walk.go#L298-L300](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/walk.go#L298-L300)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/walk.go#L111-L113](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/walk.go#L111-L113)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/plan.go#L519-L521](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/plan.go#L519-L521)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/grant_revoke.go#L371-L373](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/grant_revoke.go#L371-L373)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/table.go#L296-L298](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/table.go#L296-L298)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/table.go#L339-L341](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/table.go#L339-L341)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/catalog/descs/collection.go#L303-L305](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/catalog/descs/collection.go#L303-L305)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/catalog/descs/collection.go#L272-L274](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/catalog/descs/collection.go#L272-L274)
[https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/catalog/descs/collection.go#L257-L259](https://github.com/cockroachdb/cockroach/blob/03498e5964c0eaa45bb5435b4c600de38d542910/pkg/sql/catalog/descs/collection.go#L257-L259)
</details>

```
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 144
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithProfiling at line 3399
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt.func1 at line 145
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 1125
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchToExecutionEngine at line 1940
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithDistSQLEngine at line 2401
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRunAll at line 1663
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRunAll.func3 at line 1660
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRun at line 1945
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).Run at line 905
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlow).Run at line 320
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).Run at line 278
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).init at line 244
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).Run.(*BatchFlowCoordinator).init.func2 at line 245
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).Init at line 103
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).init at line 94
pkg/sql/colexec/columnarizer.go in pkg/sql/colexec.(*Columnarizer).Init at line 183
pkg/sql/plan_node_to_row_source.go in pkg/sql.(*planNodeToRowSource).Start at line 175
pkg/sql/plan.go in pkg/sql.startExec at line 523
pkg/sql/walk.go in pkg/sql.walkPlan at line 43
pkg/sql/walk.go in pkg/sql.(*planVisitor).visit at line 79
pkg/sql/walk.go in pkg/sql.(*planVisitor).visitInternal at line 299
pkg/sql/walk.go in pkg/sql.(*planVisitor).visitInternal.func1 at line 112
pkg/sql/plan.go in pkg/sql.startExec.func2 at line 520
pkg/sql/grant_revoke.go in pkg/sql.(*changeDescriptorBackedPrivilegesNode).startExec at line 372
pkg/sql/table.go in pkg/sql.(*planner).writeSchemaChangeToBatch at line 297
pkg/sql/table.go in pkg/sql.(*planner).writeTableDescToBatch at line 340
pkg/sql/catalog/descs/collection.go in pkg/sql/catalog/descs.(*Collection).WriteDescToBatch at line 304
pkg/sql/catalog/descs/collection.go in pkg/sql/catalog/descs.(*Collection).AddUncommittedDescriptor at line 273
pkg/sql/catalog/descs/collection.go in pkg/sql/catalog/descs.(*Collection).AddUncommittedDescriptor.func1 at line 258
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v23.2.3 |
| Go Version | go1.21.5 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.2.3 |
| Cockroach SHA | 03498e5964c0eaa45bb5435b4c600de38d542910 |
| # of CPUs | 32 |
| # of Goroutines | 651 |

Jira issue: CRDB-44856

**Comment by spilchen** [comment]
We’re exceeding the memory budget allocated for tracking uncommitted descriptors during a schema change. This issue doesn’t appear to be actionable. The memory budget itself seems reasonable (1610606678 bytes), so it might simply result from a schema change involving a large number of descriptors.

**Comment by spilchen** [comment]
Lets use this issue to change the error handling for out of memory errors in this code path. The sentry report is being generated because we wrap an assertion error here:
https://github.com/cockroachdb/cockroach/blob/a609fd6aeb5f9dca8a0f12fcec841b68c158563d/pkg/sql/catalog/descs/collection.go#L263-L268

We should change this so that the assertion is only generated if the error we get doesn't have a SQL code attached with it (we can check if it has a pgcode).
