### ISSUE TITLE
cli: expose timeuntilstoredead

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#13602]
Currently, `timeuntilstoredead` is only an env variable. Based on a chat with @bdarnell, it'd be good to eventually expose this more, ideally as some sort of global configuration for the cluster instead of a flag that needs to be specified on each node. Ben suggested we could easily make it something settable with a new command similar to `cockroach zone set`.

**Comment by dianasaur323** [comment]
Will this fit into the systems table that @dt is working on? Assigning to @dt for now for his thoughts on if this can make it into 1.0. If not, please put into Q3 2017 milestone.

**Comment by dt** [comment]
I don't know what `timeuntilstoredead` is, but there's a description of the settings table and what it is intended for here: https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/settings_table.md

**Comment by dt** [comment]
but yes, generally env vars are candidates for switching to `system.settings`

**Comment by bdarnell** [comment]
It's [here](https://github.com/cockroachdb/cockroach/blob/c9493dd875631094aa3c80a2491eef3322780da4/pkg/server/config.go#L163) and would definitely be good to move to the settings table.

**Comment by BramGruneir** [comment]
I agree, I think it's a perfect candidate.
Also failedReservationsTimeout and declinedReservationsTimeout which are from the store pool.  Might be worth renaming them too.

**Comment by petermattis** [comment]
@BramGruneir It should be very easy to get settings added for these. Can you get this done today?

**Comment by BramGruneir** [comment]
Yep, already working on it.
