### ISSUE TITLE
sql: prepared statements should cache a parsed query

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#13618]
Prepared statements (i.e. `sql.PreparedStatement`) currently stores the raw query string. When the prepared statement is executed, we parse the query string, bind parameters and execute. The re-parsing on every execution is conceptually unnecessary, though required due to SQL execution potentially mutating the parsed query. Is this still true? There is a comment in the code that constant literals can change their representation during type checking (e.g. `1.0000` -> `1`). The ideal would be to reuse the same parsed query for every execution of a prepared statement.

If reusing the same parsed query is not feasible, another option is to perform a deep clone of the parsed query.

**Comment by knz** [comment]
To achieve this we need to change the handling of placeholders, to not fold their value as constants during the initial type checking phase. This is possible and probably desirable anyway.

**Comment by knz** [comment]
This may be another phrasing (dup?) of #6402.

**Comment by jordanlewis** [comment]
Closed by #15639.
