### ISSUE TITLE
ui: QPS in Admin UI sidebar disagrees with SQL dashboard QPS

### ISSUE THREAD

**Issue by arjunravinarayan** [cockroachdb/cockroach#13611]
The sidebar rotates between ~7k-8k QPS
<img width="347" alt="screenshot 2017-02-15 16 35 44" src="https://cloud.githubusercontent.com/assets/1565833/22996455/d7439126-f39c-11e6-9ea5-dd3af91d9638.png">
However, under the SQL dashboard, the "SQL Queries" shows
<img width="863" alt="screenshot 2017-02-15 16 36 19" src="https://cloud.githubusercontent.com/assets/1565833/22996480/eefea4f4-f39c-11e6-981e-53fea659fa78.png">
This is confirmed by the Grafana dashboard which shows
<img width="1235" alt="screenshot 2017-02-15 16 37 03" src="https://cloud.githubusercontent.com/assets/1565833/22996505/0034264a-f39d-11e6-8b5a-ac271eadc5fd.png">

This is on cluster Denim, which is the first cluster running a new load generator (YCSB). I'm wondering if the new load pattern is uncovering a bug that we haven't seen with block writer or photos. This is currently a live cluster if that would be useful for debugging, let me know if I should not take this cluster down and preserve it as a running artifact (I currently have no plans to, but it is running with degraded performance, which I am scheduled to investigate in the next couple days, which might involve restarting load).

@mrtracy, assigning to you, could you please route this to the right person?

**Comment by mrtracy** [comment]
I can't duplicate this, the numbers seem to match on the clusters I'm checking.  @arjunravinarayan can you let me know if this still reproduces?  Moving to 1.1.

**Comment by arjunravinarayan** [comment]
Closing as I can't reproduce this now either, will reopen and preserve the cluster artifact if this is seen again.
