### ISSUE TITLE
kvserver: mitigate chronic lagging rangefeeds due to rac2 send queues

### ISSUE THREAD

**Issue by kvoli** [cockroachdb/cockroach#136214]
Now that entries can be arbitrarily delayed by RACv2 pacing, it is also now more likely that a rangefeed planned on a chronically behind store may also have corresponding chronic rangefeed lag.

This issue is to mitigate chronic rangefeed lag that results from RACv2 pacing entries at a quorum speed.

Jira issue: CRDB-44928

**Comment by sumeerbhola** [comment]
related issue https://github.com/cockroachdb/cockroach/issues/119490
