### ISSUE TITLE
perf: explore use of direct IO for the RocksDB WAL

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#13620]
RocksDB 5.1.2 added support for using direct IO (`O_DIRECT`) for writes. This might be a faster option than using fsync/fdatasync after writing the WAL.

**Comment by tschottdorf** [comment]
cc @irfansharif - not sure, but maybe this option is something that would apply to the Raft log RocksDB instance?

**Comment by irfansharif** [comment]
it does, have this in my notes somewhere. on my radar for when tuning RocksDB for raft log workload.

**Comment by petermattis** [comment]
In more recent RocksDB releases, the option became `use_direct_io_for_flush_and_compaction` and only applies to reads and writes performed by background flushes and compactions. So direct IO could not be used as a replacement for syncing the WAL.

Enabling `use_direct_io_for_flush_and_compaction` on a write-only workload showed a 5-10% performance decrease. Disk utilization jump from ~50% to ~75% and disk read bandwidth jumped from 0 to 60-80 MB/sec. Avoiding the OS buffer cache doesn't seem to be a good idea at this time.

**Comment by leventov** [comment]
https://github.com/facebook/rocksdb/wiki/Direct-IO says:
> `use_direct_io_for_flush_and_compaction` and `use_direct_reads` will only be applied to SST file I/O but not **WAL I/O** or MANIFEST I/O because the I/O pattern of these files are not suitable for direct I/O

I wonder why WAL I/O pattern is considered not suitable for direct I/O?

**Comment by saolof** [comment]
> In more recent RocksDB releases, the option became `use_direct_io_for_flush_and_compaction` and only applies to reads and writes performed by background flushes and compactions. So direct IO could not be used as a replacement for syncing the WAL.
> 
> Enabling `use_direct_io_for_flush_and_compaction` on a write-only workload showed a 5-10% performance decrease. Disk utilization jump from ~50% to ~75% and disk read bandwidth jumped from 0 to 60-80 MB/sec. Avoiding the OS buffer cache doesn't seem to be a good idea at this time.

Note that direct io pays the cost of writes upfront without offloading work to kernel threads, so results may look different when said kernel threads see high load making buffered IO somewhat nontrivial to benchmark. But the discussion is quite different now from in 2017 since rocksdb is no longer the backend for crdb and io_uring exists.
