### ISSUE TITLE
sql: log completed (perhaps ongoing too ) schema updates in a table that can be queried by users

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#13628]
Users need to view and query a history of changes to tables. They also want to be able to garbage collect entries. This supports use cases where transactions fire off notifications that result in a change in another system. These notifications need to be consistent - as in, upon failure, users need to be able to check to change table to see if all changes have been captured. 

MySQL and PostgreSQL implement change tables, and the suggestion is to explore these two options with a preference for supporting the PostgreSQL standard. Another option to consider is the possibility to push reads and writes to Kafka in a built-in fashion. This would likely be another feature (Kafka integration). 

This is a separate issue from continuous transaction streaming, which would be a fit for a different set of use cases.

**Comment by tamird** [comment]
> These notifications need to be consistent - as in, upon failure, users need to be able to check to change table to see if all changes have been captured.

I think we need a bit more detail here. Whose failure, CRDB or the external system? What is the user checking, exactly? Why can't they use `AS OF SYSTEM TIME` queries to satisfy this use case?

> MySQL and PostgreSQL implement change tables

Can you link to these implementations? There are various things that sound roughly similar to what you're describing here, but no exact matches.

**Comment by dianasaur323** [comment]
Ok - I followed up on this. It looks like it's mainly PostgreSQL extensions that support this capability. 

Here's a link that goes into further detail: https://www.confluent.io/blog/bottled-water-real-time-integration-of-postgresql-and-kafka/

**Comment by ivan** [comment]
For PostgreSQL there is this extension https://github.com/arkhipov/temporal_tables and some usage information at http://clarkdave.net/2015/02/historical-records-with-postgresql-and-temporal-tables-and-sql-2011/

**Comment by dt** [comment]
we have CDC for data ranges and the event log for schema changes so I'm happy with closing this.
