### ISSUE TITLE
Change the name!

### ISSUE THREAD

**Issue by niyazpk** [cockroachdb/cockroach#13634]
CockroachDB is not a good name. You have a great product going on here. I think the name is going to be a big hindrance for adoption.

I cannot suggest my team to evaluate CockroachDB for our use-cases without people flinching their face hearing the name. I'd like people to evaluate the DB for its merits, but that becomes difficult if they associate the product with low-quality, even before the evaluation because of the name.

**Comment by UnnoTed** [comment]
There is a past of people complaining about the name...

**Comment by crudbug** [comment]
RoachDB  !

**Comment by wendigo** [comment]
CouchDB - you're lazy dev, MySQL - selfish, Oracle - too much Matrix... :trollface: 

I really like CocroachDB name. Sounds pretty badass 😎

**Comment by vivekmenezes** [comment]
yeah we know what happened to python the language too!

**Comment by impredicative** [comment]
@vivekmenezes Not an option? Is it prohibited by the laws of physics? I think not. I wait years to check this db given its questionable name.

**Comment by cup** [comment]
https://github.com/cockroachdb/cockroach/issues/13634
https://github.com/cockroachdb/cockroach/issues/2677
https://github.com/cockroachdb/cockroach/issues/3151
