### ISSUE TITLE
sql: float log and sqrt are inconsistent in their error handling

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#13642]
Currently the float `log` builtins report a NaN result for negative arguments, whereas `sqrt` causes an error.

Meanwhile the decimal builtins all report an error for invalid arugments.

Either errors or NaNs are probably fine, but probably the behavior should be the same for float and decimal by default. 

(perhaps the other functions have a similar problem as well)

The naive short-term solution is to generate errors in all cases.
We *could* do that and it would match pg's behavior, however suppose this was implemented:

- there would be two checks of the argument: one by our builtin code, and then one by the math library (there's already such a check to decide the NaN result)
- it would not be possible to compute a log()  column on a table unless there was some guarantee all the values in that column are valid already
- if all the values were not guaranteed to be valid already, the user would need to write `IF(x<0, "NaN"::float, log(x)`, which would cause **three** checks of the argument: one by `IF`, and then one again by our `log` builtin, and then one by the math library.

The proper solution is to:

1) as a short-term solution, provide two builtins side by side for the math functions; the "basic" one would  return NaN in case of invalid arguments, and the other one e.g. "log_checked" would do the extra check and return an error. 
2) part of the short-term solution, also provide `isnan` and `isinf` functions on float/decimal types, so the user can substitute a NULL for NaN in their computations (this makes it easier to do the right thing in e.g. joins)
3) the longer term solution is to have a session flag that switches between two sets of builtins, both with the same name, one that does error checking and the other that doesnt.

**Comment by knz** [comment]
`isinf` is not really necessary because one can actually compare with `'inf'::float`. 
Punting on this until apd supports NaN too.

**Comment by jordanlewis** [comment]
Fixed.

```
root@127.0.0.1:58219/defaultdb> select log(-1.0);
pq: log(): cannot take logarithm of a negative number
root@127.0.0.1:58219/defaultdb> select sqrt(-1.0);
pq: sqrt(): cannot take square root of a negative number
```
