### ISSUE TITLE
schemachanger: incorrect InvertedColumnKinds in the inverted index

### ISSUE THREAD

**Issue by smcvey** [cockroachdb/cockroach#136410]
**Describe the problem**

If you have a table with a composite index of a regular column and a trigram index, running `SHOW CREATE TABLE` somehow loses the gin_trgm_ops class so the output cannot be repeatedly entered back into CockroachDB.

**To Reproduce**

1. First create the table with the composite index:

```
CREATE TABLE t (id UUID PRIMARY KEY, x STRING, y STRING);
CREATE INDEX ON t USING GIN (x, y gin_trgm_ops);
```

2. Now show the output of `SHOW CREATE TABLE t;`, it looks similar to this:

```
CREATE TABLE public.t (
      id UUID NOT NULL,
      x STRING NULL,
      y STRING NULL,
      CONSTRAINT t_pkey PRIMARY KEY (id ASC),
      INVERTED INDEX t_x_y_idx (x ASC, y)
  );
```

If we drop the table and then paste the above back in to recreate it, this happens:

```
ERROR: data type text has no default operator class for access method "gin"
SQLSTATE: 42704
HINT: You must specify an operator class for the index (did you mean gin_trgm_ops?)
```

The `gin_trgm_ops` class is missing from the end of `y` in the index line.
Please describe the issue you observed, and any steps we can take to reproduce it:

**Expected behavior**
The output of `SHOW CREATE TABLE` should be re-enterable into Cockroach to produce exactly the same table topology as was there before.

**Environment:**
 - CockroachDB version: v24.2.5, v24.3.0

**Additional context**
The output of `SHOW CREATE TABLE` cannot be repeatedly used.

Jira issue: CRDB-45025

**Comment by rytaft** [comment]
Hi @smcvey -- I assume you didn't mean to write "CockroachDB version: v2.4.5" -- what's the actual version you were running this on?

**Comment by smcvey** [comment]
It was meant to be v24.2.5, which I've now corrected.  Also, v24.3.0 just came out, it affects that as well.

(It's basically broken in all versions).

**Comment by michae2** [comment]
(I can reproduce it on tip of master as well.)

**Comment by yuzefovich** [comment]
I looked into this, and I think it's a bug in the declarative schema changer. In particular, I think this diff is needed:
```
--- a/pkg/sql/schemachanger/scexec/scmutationexec/index.go
+++ b/pkg/sql/schemachanger/scexec/scmutationexec/index.go
@@ -11,6 +11,7 @@ import (
 
        "github.com/cockroachdb/cockroach/pkg/sql/catalog"
        "github.com/cockroachdb/cockroach/pkg/sql/catalog/catenumpb"
+       "github.com/cockroachdb/cockroach/pkg/sql/catalog/catpb"
        "github.com/cockroachdb/cockroach/pkg/sql/catalog/colinfo"
        "github.com/cockroachdb/cockroach/pkg/sql/catalog/descpb"
        "github.com/cockroachdb/cockroach/pkg/sql/catalog/tabledesc"
@@ -408,7 +409,7 @@ func (i *immediateVisitor) AddColumnToIndex(ctx context.Context, op scop.AddColu
        }
        // If this is an inverted column, note that.
        if indexDesc.Type == descpb.IndexDescriptor_INVERTED && op.ColumnID == indexDesc.InvertedColumnID() {
-               indexDesc.InvertedColumnKinds = append(indexDesc.InvertedColumnKinds, op.InvertedKind)
+               indexDesc.InvertedColumnKinds = []catpb.InvertedIndexColumnKind{op.InvertedKind}
        }
        return nil
 }
```
I added some print statements to show the contents of `InvertedColumnKinds` after the append and got:
```
[DEFAULT]
[DEFAULT TRIGRAM]
[DEFAULT]
[DEFAULT TRIGRAM]
[DEFAULT]
[DEFAULT TRIGRAM]
[DEFAULT]
[DEFAULT TRIGRAM]
```
To me this suggests that when using `CREATE INDEX ON t USING GIN (x, y gin_trgm_ops);` form we first run some kind of "vanilla" CREATE INDEX element that sets the DEFAULT kind, and then we update the index descriptor to append the proper TRIGRAM kind. When using `CREATE INVERTED INDEX ON t (s gin_trgm_ops);` (from #109201) we apparently go straight to creating inverted index. (This is my speculation.)

Interestingly, I couldn't reproduce this problem via the logic test but could easily hit it via `demo`.

I'll route this to Foundations for the fix and proper testing. I also would like to learn why the logic test doesn't reproduce this and why we execute the schema change element 4 (or 8?) times for a single CREATE INDEX stmt.

**Comment by rafiss** [comment]
> I also would like to learn why the logic test doesn't reproduce this

@yuzefovich did your logic test look like this:
```
statement ok
CREATE TABLE roaches (id UUID PRIMARY KEY, x STRING, y STRING, FAMILY f1 (id, x, y));
CREATE INDEX ON roaches USING GIN (x, y gin_trgm_ops);
```

If so, that sends the two statements in one batch, which means they run in a multi-statement explicit transaction. The declarative schema changer does not yet support multiple statements in a transaction, so this would cause the statements to fallback to the legacy schema changer.

The test would need to look like this:
```
statement ok
CREATE TABLE roaches (id UUID PRIMARY KEY, x STRING, y STRING, FAMILY f1 (id, x, y));

statement ok
CREATE INDEX ON roaches USING GIN (x, y gin_trgm_ops);
```

**Comment by yuzefovich** [comment]
Yeah, it's likely I used a single `statement ok` directive. Makes sense, thanks!
