### ISSUE TITLE
sql,distsql: alter_table logic test failure with fake span resolver

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#13646]
I am trying to make logic tests to run with DistSQL + fake span resolver in a 3 node testcluster.

I am seeing a failure for https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/testdata/alter_table#L477

```sql
# Adding a unique column to an existing table with data with a default value
# is illegal
statement error duplicate key value .* violates unique constraint \"add_default_f_key\"
ALTER TABLE add_default ADD f TIMESTAMP UNIQUE DEFAULT current_timestamp()
```

The statement doesn't hit the expected error:
```
$ make test PKG=./pkg/sql TESTS=LogicDistSQL//alter_table TESTFLAGS='--max-errors 10'
go test -v  -tags '' -i ./pkg/sql
go test  -tags '' -run "LogicDistSQL//alter_table" -timeout 2m ./pkg/sql --max-errors 10
I170217 10:12:34.204108 1 rand.go:76  Random seed: -7174852851567646062
E170217 10:12:40.569642 8779 sql/distsqlrun/server.go:202  [n1] duplicate key value (f)=('2017-02-17 15:12:40.549548+00:00') violates unique constraint "add_default_f_key"
E170217 10:12:40.650652 8785 sql/distsqlrun/server.go:202  [n1] duplicate key value (f)=('2017-02-17 15:12:40.638531+00:00') violates unique constraint "add_default_f_key"
E170217 10:12:40.805665 8931 sql/distsqlrun/server.go:202  [n1] duplicate key value (f)=('2017-02-17 15:12:40.786231+00:00') violates unique constraint "add_default_f_key"
test log files left over in: /tmp/TestLogic386323654
--- FAIL: TestLogicDistSQL (6.92s)
    --- FAIL: TestLogicDistSQL/testdata/alter_table (6.91s)
    	logic_test.go:1485: 
    		testdata/alter_table:479: expected "duplicate key value .* violates unique constraint \\\"add_default_f_key\\\"", but found <nil>
    	logic_test.go:1300: 
    		testdata/alter_table:479: error in statement, skipping to next file
FAIL
FAIL	github.com/cockroachdb/cockroach/pkg/sql	6.947s
Makefile:136: recipe for target 'test' failed
```

I am guessing it is the new backfiller. I have pushed a temporary branch to the repo https://github.com/cockroachdb/cockroach/tree/radu-logic-test-cluster-for-vivek that can be used to repro.

**Comment by vivekmenezes** [comment]
I'm gonna be out on vacation starting today so I might not be able to get to it.

**Comment by RaduBerinde** [comment]
No problem, we can take a look. From the logs it looks like the nodes are hitting the error so maybe it's just a matter of plumbing the error. A general question though - is an `ALTER TABLE` statement that adds a column supposed to wait until the backfill is complete?

**Comment by vivekmenezes** [comment]
Yes the ALTER TABLE statement will wait until the backfill is complete. I'd
change the name of the column in the test so you can at least see if its
hitting the error

**Comment by RaduBerinde** [comment]
This code is very hard to debug. It could also use more comments - for example, it took me a while to understand the non-trivial logic behind the way we update the resume span here (and I'm still not quite sure I understand correctly): https://github.com/cockroachdb/cockroach/blob/4945ed5155693dbc8a9006c0cc9e7f07cbd12543/pkg/sql/backfill.go#L247

Anyway, the statement is this:
`ALTER TABLE add_default ADD f TIMESTAMP UNIQUE DEFAULT current_timestamp();`

As far as I can tell, what is happening is that we are retrying the schema change operation, and every time we do, we don't reset the `ResumeSpan`. Every time we rewrite all the values with the current timestamp, but the index backfill is happening on fewer and fewer rows. Also note that we are using the fake span resolver so we may be breaking the span apart differently each time.

These are the `InitPut`s that happen (some succeed, some do not):
```
10:I170219 18:04:23.789132 8915 sql/distsqlrun/indexbackfiller.go:189  [n3,f364df213,IndexBackfiller=57] InitPut /Table/57/2/2017-02-19T23:04:23.779242Z/0 -> {[0 0 0 0 3 138] 0.000000000,0}
11:I170219 18:04:23.789267 8915 sql/distsqlrun/indexbackfiller.go:189  [n3,f364df213,IndexBackfiller=57] InitPut /Table/57/2/2017-02-19T23:04:23.779242Z/0 -> {[0 0 0 0 3 139] 0.000000000,0}
12:I170219 18:04:23.789325 8915 sql/distsqlrun/indexbackfiller.go:189  [n3,f364df213,IndexBackfiller=57] InitPut /Table/57/2/2017-02-19T23:04:23.779242Z/0 -> {[0 0 0 0 3 141] 0.000000000,0}

<retry>

23:I170219 18:04:23.891246 8972 sql/distsqlrun/indexbackfiller.go:189  [n2,fab50ff33,IndexBackfiller=57] InitPut /Table/57/2/2017-02-19T23:04:23.881007Z/0 -> {[0 0 0 0 3 139] 0.000000000,0}
24:I170219 18:04:23.891904 8979 sql/distsqlrun/indexbackfiller.go:189  [n3,fab50ff33,IndexBackfiller=57] InitPut /Table/57/2/2017-02-19T23:04:23.881007Z/0 -> {[0 0 0 0 3 141] 0.000000000,0}
25:I170219 18:04:23.892550 8827 sql/distsqlrun/indexbackfiller.go:189  [n1,fab50ff33,IndexBackfiller=57] InitPut /Table/57/2/2017-02-19T23:04:23.881007Z/0 -> {[0 0 0 0 3 138] 0.000000000,0}

<retry>

42:I170219 18:04:24.049558 9060 sql/distsqlrun/indexbackfiller.go:189  [n3,f68bcaeff,IndexBackfiller=57] InitPut /Table/57/2/2017-02-19T23:04:24.040879Z/0 -> {[0 0 0 0 3 138] 0.000000000,0}
51:I170219 18:04:24.070919 9106 sql/distsqlrun/indexbackfiller.go:189  [n2,f639fcbe2,IndexBackfiller=57] InitPut /Table/57/2/2017-02-19T23:04:24.040879Z/0 -> {[0 0 0 0 3 141] 0.000000000,0}

<retry>

62:I170219 18:04:24.295101 9173 sql/distsqlrun/indexbackfiller.go:189  [n2,fef6ebbc1,IndexBackfiller=57] InitPut /Table/57/2/2017-02-19T23:04:24.28651Z/0 -> {[0 0 0 0 3 141] 0.000000000,0}
```

Note how one by one we get one row in each time.

I don't know if not resetting `ResumeSpan` is a bug or a feature - is the intention to try to resume from the last checkpoint? If yes, it's not right in this case, where the values are context dependent. It's also not working quite as intended because we rewrite all the values (if we wanted to resume, we should resume the index backfill step, not do the other steps from scratch).

I might comment out the test for the time being since I'm not very comfortable messing with this code.

**Comment by vivekmenezes** [comment]
What's happening here I believe is that the column backfill is succeeding but the index backfill is failing. Now when the column backfill succeeds it leaves no marker that it has succeeded (it depends on the schema change being upgraded, but that is hinged on the index backfill succeeding). Without the marker, it restarts the column backfill from scratch. The index backfill on the other hand has partially succeeded and restarts from the checkpoint.

**Comment by RaduBerinde** [comment]
That sounds right - the final values in the table are all from the last retry.

**Comment by vivekmenezes** [comment]
I haven't looked at the code, but it's most likely the case that a conflicting index key is being hit on a remote node, which is returning an error to the gateway node, but the gateway node is unable to interpret the conflicting index key error as a constraint violation, and treats it as a retry error. This retry error cannot be resolved and it just keeps retrying until the test times out. The solution is to send the error back as a special error message and interpret that correctly on the gateway.

**Comment by RaduBerinde** [comment]
PR #13706 temporarily comments out this test (it should be re-enabled when the issue is fixed).
