### ISSUE TITLE
Sentry: log_writer.go:743: × (1) attached stack trace   -- stack trace:   | runtime.gopanic   | 	GOROOT/src/runtime/panic.go:770   | github.com/cockroachdb/pebble.(*DB).commitWrite   | 	github.com/co...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#136469]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/6105335700/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/6105335700/?referrer=webhooks_plugin)

Panic Message:

```
log_writer.go:743: ×
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:770
  | github.com/cockroachdb/pebble.(*DB).commitWrite
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go:978
  | github.com/cockroachdb/pebble.(*commitPipeline).prepare
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/commit.go:468
  | github.com/cockroachdb/pebble.(*commitPipeline).Commit
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/commit.go:317
  | github.com/cockroachdb/pebble.(*DB).applyInternal
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go:863
  | github.com/cockroachdb/pebble.(*DB).ApplyNoSyncWait
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go:811
  | github.com/cockroachdb/cockroach/pkg/storage.(*writeBatch).CommitNoSyncWait
  | 	github.com/cockroachdb/cockroach/pkg/storage/pebble_batch.go:358
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/logstore.(*LogStore).storeEntriesAndCommitBatch
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/logstore/logstore.go:261
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/logstore.(*LogStore).StoreEntries
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/logstore/logstore.go:152
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:1066
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReady
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:758
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processReady
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:686
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftSchedulerShard).worker
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:413
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).Start.func2
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:316
  | [...repeated from below...]
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/pebble/record.(*LogWriter).flushPending.func1
  | 	github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go:743
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:770
  | sync.(*WaitGroup).Add
  | 	GOROOT/src/sync/waitgroup.go:62
  | sync.(*WaitGroup).Done
  | 	GOROOT/src/sync/waitgroup.go:87
  | github.com/cockroachdb/pebble/wal.(*recordQueue).pop
  | 	github.com/cockroachdb/pebble/wal/external/com_github_cockroachdb_pebble/wal/failover_writer.go:279
  | github.com/cockroachdb/pebble/wal.(*failoverWriter).doneSyncCallback
  | 	github.com/cockroachdb/pebble/wal/external/com_github_cockroachdb_pebble/wal/failover_writer.go:712
  | github.com/cockroachdb/pebble/record.(*pendingSyncsWithHighestSyncIndex).pop
  | 	github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go:313
  | github.com/cockroachdb/pebble/record.(*LogWriter).flushPending
  | 	github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go:766
  | github.com/cockroachdb/pebble/record.(*LogWriter).flushLoop
  | 	github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go:695
  | runtime/pprof.Do
  | 	GOROOT/src/runtime/pprof/runtime.go:51
  | github.com/cockroachdb/pebble/record.NewLogWriter.func2
  | 	github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go:562
  | runtime.goexit
  | 	src/runtime/asm_amd64.s:1695
Wraps: (3) ×
Error types: (1) *withstack.withStack (2) *withstack.withStack (3) *errutil.leafError
-- report composition:
*errutil.leafError: ×
log_writer.go:743: *withstack.withStack (top exception)
panic.go:770: *withstack.withStack (1)
(check the extra data payloads)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_amd64.s#L1694-L1696](src/runtime/asm_amd64.s#L1694-L1696)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/util/stop/stopper.go#L484-L486](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/util/stop/stopper.go#L484-L486)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L315-L317](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L315-L317)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L412-L414](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L412-L414)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L685-L687](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L685-L687)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L757-L759](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L757-L759)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L1065-L1067](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L1065-L1067)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/kv/kvserver/logstore/logstore.go#L151-L153](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/kv/kvserver/logstore/logstore.go#L151-L153)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/kv/kvserver/logstore/logstore.go#L260-L262](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/kv/kvserver/logstore/logstore.go#L260-L262)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/storage/pebble_batch.go#L357-L359](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/storage/pebble_batch.go#L357-L359)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L810-L812](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L810-L812)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L862-L864](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L862-L864)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/commit.go#L316-L318](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/commit.go#L316-L318)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/commit.go#L467-L469](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/commit.go#L467-L469)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L977-L979](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L977-L979)
[GOROOT/src/runtime/panic.go#L769-L771](GOROOT/src/runtime/panic.go#L769-L771)
[src/runtime/asm_amd64.s#L1694-L1696](src/runtime/asm_amd64.s#L1694-L1696)
[github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go#L561-L563](github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go#L561-L563)
[GOROOT/src/runtime/pprof/runtime.go#L50-L52](GOROOT/src/runtime/pprof/runtime.go#L50-L52)
[github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go#L694-L696](github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go#L694-L696)
[github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go#L765-L767](github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go#L765-L767)
[github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go#L312-L314](github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go#L312-L314)
[github.com/cockroachdb/pebble/wal/external/com_github_cockroachdb_pebble/wal/failover_writer.go#L711-L713](github.com/cockroachdb/pebble/wal/external/com_github_cockroachdb_pebble/wal/failover_writer.go#L711-L713)
[github.com/cockroachdb/pebble/wal/external/com_github_cockroachdb_pebble/wal/failover_writer.go#L278-L280](github.com/cockroachdb/pebble/wal/external/com_github_cockroachdb_pebble/wal/failover_writer.go#L278-L280)
[GOROOT/src/sync/waitgroup.go#L86-L88](GOROOT/src/sync/waitgroup.go#L86-L88)
[GOROOT/src/sync/waitgroup.go#L61-L63](GOROOT/src/sync/waitgroup.go#L61-L63)
[GOROOT/src/runtime/panic.go#L769-L771](GOROOT/src/runtime/panic.go#L769-L771)
[github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go#L742-L744](github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go#L742-L744)
</details>

```
src/runtime/asm_amd64.s in runtime.goexit at line 1695
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 485
pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go in pkg/kv/kvserver.(*raftScheduler).Start.func2 at line 316
pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go in pkg/kv/kvserver.(*raftSchedulerShard).worker at line 413
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).processReady at line 686
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).handleRaftReady at line 758
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked at line 1066
pkg/kv/kvserver/logstore/logstore.go in pkg/kv/kvserver/logstore.(*LogStore).StoreEntries at line 152
pkg/kv/kvserver/logstore/logstore.go in pkg/kv/kvserver/logstore.(*LogStore).storeEntriesAndCommitBatch at line 261
pkg/storage/pebble_batch.go in pkg/storage.(*writeBatch).CommitNoSyncWait at line 358
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go in github.com/cockroachdb/pebble.(*DB).ApplyNoSyncWait at line 811
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go in github.com/cockroachdb/pebble.(*DB).applyInternal at line 863
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/commit.go in github.com/cockroachdb/pebble.(*commitPipeline).Commit at line 317
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/commit.go in github.com/cockroachdb/pebble.(*commitPipeline).prepare at line 468
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go in github.com/cockroachdb/pebble.(*DB).commitWrite at line 978
GOROOT/src/runtime/panic.go in runtime.gopanic at line 770
src/runtime/asm_amd64.s in runtime.goexit at line 1695
github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go in github.com/cockroachdb/pebble/record.NewLogWriter.func2 at line 562
GOROOT/src/runtime/pprof/runtime.go in runtime/pprof.Do at line 51
github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go in github.com/cockroachdb/pebble/record.(*LogWriter).flushLoop at line 695
github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go in github.com/cockroachdb/pebble/record.(*LogWriter).flushPending at line 766
github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go in github.com/cockroachdb/pebble/record.(*pendingSyncsWithHighestSyncIndex).pop at line 313
github.com/cockroachdb/pebble/wal/external/com_github_cockroachdb_pebble/wal/failover_writer.go in github.com/cockroachdb/pebble/wal.(*failoverWriter).doneSyncCallback at line 712
github.com/cockroachdb/pebble/wal/external/com_github_cockroachdb_pebble/wal/failover_writer.go in github.com/cockroachdb/pebble/wal.(*recordQueue).pop at line 279
GOROOT/src/sync/waitgroup.go in sync.(*WaitGroup).Done at line 87
GOROOT/src/sync/waitgroup.go in sync.(*WaitGroup).Add at line 62
GOROOT/src/runtime/panic.go in runtime.gopanic at line 770
github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go in github.com/cockroachdb/pebble/record.(*LogWriter).flushPending.func1 at line 743
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v24.2.4 |
| Go Version | go1.22.5 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v24.2.4 |
| Cockroach SHA | 8140b8e294fb16a293d0aae662bcf5c1d488c852 |
| # of CPUs | 8 |
| # of Goroutines | 1406 |

**Comment by itsbilal** [comment]
All useful info got redacted here. It could just be a disk / infra issue on the cluster where this was being run; the method where the panic happens writes to the WAL.
