### ISSUE TITLE
sql/parser: some fields of sqlSymType are unused

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#13643]
I was investigating the output provided by go-yacc and I found that the fields `id`, `pos` and `empty`, defined in `sql.y`'s `%union` clause, are unused. This also means the corresponding code in `scan.go` can be modified to use a local variable instead.

cc @nvanbenschoten

**Comment by nvanbenschoten** [comment]
The only field that I'm seeing that's unused is `empty`, which is an empty struct that takes up no space. You can check this by modifying the generated `sql.go` and seeing if it compiles. Do you mind expanding on how you "found that the fields `id` and `pos` are unused".

**Comment by knz** [comment]
So these fields `id` and `pos` are only used by the scanner itself -- it could be passed as a function argument locally instead of stored in the union.
