### ISSUE TITLE
sql: arrays can't be cast to their own type

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#13651]
```
root@:26257/> SELECT ARRAY[1, 2]::int[];
pq: invalid cast: int[] -> INT[]
```

**Comment by knz** [comment]
Note for implementer: there's a commented test for this already in `pgwire_test.go`.

**Comment by justinj** [comment]
Can this be closed now @jordanlewis ? Also note [this comment](https://github.com/justinj/cockroach/blob/ed2720d4e7b3613819fba550e1e60cd0bc3cae55/pkg/sql/pgwire/pgwire_test.go#L910-L913)

**Comment by jordanlewis** [comment]
Will send a PR for that comment.
