### ISSUE TITLE
sql: v24.1.4: batchFlowCoordinator should be nil for vectorizedFlow when using pausable portals

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#136516]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/6105957429/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/6105957429/?referrer=webhooks_plugin)

Panic Message:

```
vectorized_flow.go:291: batchFlowCoordinator should be nil for vectorizedFlow
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Resume
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:291
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).resumeFlowForPausablePortal
  | 	github.com/cockroachdb/cockroach/pkg/sql/planner.go:315
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2427
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2004
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchReadCommittedStmtToExecutionEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1691
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1145
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:145
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:3457
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:144
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execPortal
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:250
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2397
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2399
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2214
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:965
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommands
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:253
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).serveImpl.func3
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:995
  | runtime.goexit
  | 	src/runtime/asm_amd64.s:1695
Wraps: (3) batchFlowCoordinator should be nil for vectorizedFlow
Error types: (1) *assert.withAssertionFailure (2) *withstack.withStack (3) *errutil.leafError
-- report composition:
*errutil.leafError: batchFlowCoordinator should be nil for vectorizedFlow
vectorized_flow.go:291: *withstack.withStack (top exception)
*assert.withAssertionFailure
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_amd64.s#L1694-L1696](src/runtime/asm_amd64.s#L1694-L1696)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/pgwire/server.go#L994-L996](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/pgwire/server.go#L994-L996)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/pgwire/conn.go#L252-L254](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/pgwire/conn.go#L252-L254)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/conn_executor.go#L964-L966](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/conn_executor.go#L964-L966)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/conn_executor.go#L2213-L2215](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/conn_executor.go#L2213-L2215)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/conn_executor.go#L2398-L2400](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/conn_executor.go#L2398-L2400)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/conn_executor.go#L2396-L2398](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/conn_executor.go#L2396-L2398)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/conn_executor_exec.go#L249-L251](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/conn_executor_exec.go#L249-L251)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/conn_executor_exec.go#L143-L145](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/conn_executor_exec.go#L143-L145)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/conn_executor_exec.go#L3456-L3458](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/conn_executor_exec.go#L3456-L3458)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/conn_executor_exec.go#L144-L146](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/conn_executor_exec.go#L144-L146)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/conn_executor_exec.go#L1144-L1146](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/conn_executor_exec.go#L1144-L1146)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/conn_executor_exec.go#L1690-L1692](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/conn_executor_exec.go#L1690-L1692)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/conn_executor_exec.go#L2003-L2005](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/conn_executor_exec.go#L2003-L2005)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/conn_executor_exec.go#L2426-L2428](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/conn_executor_exec.go#L2426-L2428)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/planner.go#L314-L316](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/planner.go#L314-L316)
[https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/colflow/vectorized_flow.go#L290-L292](https://github.com/cockroachdb/cockroach/blob/a1cbd782a33a51f7500444373ccdaa81eb2ed971/pkg/sql/colflow/vectorized_flow.go#L290-L292)
</details>

```
src/runtime/asm_amd64.s in runtime.goexit at line 1695
pkg/sql/pgwire/server.go in pkg/sql/pgwire.(*Server).serveImpl.func3 at line 995
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommands at line 253
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 965
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 2214
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 2399
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd.func2 at line 2397
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execPortal at line 250
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 144
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithProfiling at line 3457
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt.func1 at line 145
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 1145
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchReadCommittedStmtToExecutionEngine at line 1691
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchToExecutionEngine at line 2004
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithDistSQLEngine at line 2427
pkg/sql/planner.go in pkg/sql.(*planner).resumeFlowForPausablePortal at line 315
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlow).Resume at line 291
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v24.1.4 |
| Go Version | go1.22.5 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v24.1.4 |
| Cockroach SHA | a1cbd782a33a51f7500444373ccdaa81eb2ed971 |
| # of CPUs | 4 |
| # of Goroutines | 862 |

Jira issue: CRDB-45098

**Comment by yuzefovich** [comment]
Not sure how this is possible. We assume that the result writer that we use for the query is `limitedCommandResult` which doesn't implement `BatchReceiver` interface, so we should have `batchFlowCoordinator` unset. I did find an edge case which results in an internal error, will send a patch.
