### ISSUE TITLE
Sentry: syncing_file.go:65: write ×: disk quota exceeded (1) attached stack trace   -- stack trace:   | runtime.gopanic   | 	GOROOT/src/runtime/panic.go:770   | github.com/cockroachdb/pebble.(*DB).co...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#136567]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/6107395817/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/6107395817/?referrer=webhooks_plugin)

Panic Message:

```
syncing_file.go:65: write ×: disk quota exceeded
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:770
  | github.com/cockroachdb/pebble.(*DB).commitWrite
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go:956
  | github.com/cockroachdb/pebble.(*commitPipeline).prepare
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/commit.go:467
  | github.com/cockroachdb/pebble.(*commitPipeline).Commit
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/commit.go:316
  | github.com/cockroachdb/pebble.(*DB).applyInternal
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go:845
  | github.com/cockroachdb/pebble.(*DB).ApplyNoSyncWait
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go:793
  | github.com/cockroachdb/cockroach/pkg/storage.(*writeBatch).CommitNoSyncWait
  | 	github.com/cockroachdb/cockroach/pkg/storage/pebble_batch.go:356
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/logstore.(*LogStore).storeEntriesAndCommitBatch
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/logstore/logstore.go:260
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/logstore.(*LogStore).StoreEntries
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/logstore/logstore.go:151
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:1066
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReady
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:758
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processReady
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:689
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftSchedulerShard).worker
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:417
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).Start.func2
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:320
  | [...repeated from below...]
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/pebble/vfs.(*syncingFile).Write
  | 	github.com/cockroachdb/pebble/vfs/external/com_github_cockroachdb_pebble/vfs/syncing_file.go:65
  | github.com/cockroachdb/pebble/record.(*LogWriter).flushBlock
  | 	github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go:782
  | github.com/cockroachdb/pebble/record.(*LogWriter).flushPending
  | 	github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go:749
  | github.com/cockroachdb/pebble/record.(*LogWriter).flushLoop
  | 	github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go:695
  | runtime/pprof.Do
  | 	GOROOT/src/runtime/pprof/runtime.go:51
  | github.com/cockroachdb/pebble/record.NewLogWriter.func2
  | 	github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go:562
  | runtime.goexit
  | 	src/runtime/asm_amd64.s:1695
Wraps: (3) write ×
Wraps: (4) disk quota exceeded
Error types: (1) *withstack.withStack (2) *withstack.withStack (3) *fs.PathError (4) syscall.Errno
-- report composition:
syscall.Errno
*fs.PathError
syncing_file.go:65: *withstack.withStack (top exception)
panic.go:770: *withstack.withStack (1)
(check the extra data payloads)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_amd64.s#L1694-L1696](src/runtime/asm_amd64.s#L1694-L1696)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/util/stop/stopper.go#L484-L486](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/util/stop/stopper.go#L484-L486)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L319-L321](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L319-L321)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L416-L418](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L416-L418)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L688-L690](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L688-L690)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L757-L759](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L757-L759)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L1065-L1067](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L1065-L1067)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/kv/kvserver/logstore/logstore.go#L150-L152](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/kv/kvserver/logstore/logstore.go#L150-L152)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/kv/kvserver/logstore/logstore.go#L259-L261](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/kv/kvserver/logstore/logstore.go#L259-L261)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/storage/pebble_batch.go#L355-L357](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/storage/pebble_batch.go#L355-L357)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L792-L794](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L792-L794)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L844-L846](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L844-L846)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/commit.go#L315-L317](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/commit.go#L315-L317)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/commit.go#L466-L468](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/commit.go#L466-L468)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L955-L957](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L955-L957)
[GOROOT/src/runtime/panic.go#L769-L771](GOROOT/src/runtime/panic.go#L769-L771)
[src/runtime/asm_amd64.s#L1694-L1696](src/runtime/asm_amd64.s#L1694-L1696)
[github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go#L561-L563](github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go#L561-L563)
[GOROOT/src/runtime/pprof/runtime.go#L50-L52](GOROOT/src/runtime/pprof/runtime.go#L50-L52)
[github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go#L694-L696](github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go#L694-L696)
[github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go#L748-L750](github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go#L748-L750)
[github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go#L781-L783](github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go#L781-L783)
[github.com/cockroachdb/pebble/vfs/external/com_github_cockroachdb_pebble/vfs/syncing_file.go#L64-L66](github.com/cockroachdb/pebble/vfs/external/com_github_cockroachdb_pebble/vfs/syncing_file.go#L64-L66)
</details>

```
src/runtime/asm_amd64.s in runtime.goexit at line 1695
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 485
pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go in pkg/kv/kvserver.(*raftScheduler).Start.func2 at line 320
pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go in pkg/kv/kvserver.(*raftSchedulerShard).worker at line 417
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).processReady at line 689
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).handleRaftReady at line 758
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked at line 1066
pkg/kv/kvserver/logstore/logstore.go in pkg/kv/kvserver/logstore.(*LogStore).StoreEntries at line 151
pkg/kv/kvserver/logstore/logstore.go in pkg/kv/kvserver/logstore.(*LogStore).storeEntriesAndCommitBatch at line 260
pkg/storage/pebble_batch.go in pkg/storage.(*writeBatch).CommitNoSyncWait at line 356
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go in github.com/cockroachdb/pebble.(*DB).ApplyNoSyncWait at line 793
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go in github.com/cockroachdb/pebble.(*DB).applyInternal at line 845
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/commit.go in github.com/cockroachdb/pebble.(*commitPipeline).Commit at line 316
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/commit.go in github.com/cockroachdb/pebble.(*commitPipeline).prepare at line 467
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go in github.com/cockroachdb/pebble.(*DB).commitWrite at line 956
GOROOT/src/runtime/panic.go in runtime.gopanic at line 770
src/runtime/asm_amd64.s in runtime.goexit at line 1695
github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go in github.com/cockroachdb/pebble/record.NewLogWriter.func2 at line 562
GOROOT/src/runtime/pprof/runtime.go in runtime/pprof.Do at line 51
github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go in github.com/cockroachdb/pebble/record.(*LogWriter).flushLoop at line 695
github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go in github.com/cockroachdb/pebble/record.(*LogWriter).flushPending at line 749
github.com/cockroachdb/pebble/record/external/com_github_cockroachdb_pebble/record/log_writer.go in github.com/cockroachdb/pebble/record.(*LogWriter).flushBlock at line 782
github.com/cockroachdb/pebble/vfs/external/com_github_cockroachdb_pebble/vfs/syncing_file.go in github.com/cockroachdb/pebble/vfs.(*syncingFile).Write at line 65
```

### Tags

| Tag | Value |
| --- | --- |
| Command | start-single-node |
| Environment | v24.1.3 |
| Go Version | go1.22.5 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v24.1.3 |
| Cockroach SHA | 9e10212477fde97f55ea4fff01797288c836575c |
| # of CPUs | 16 |
| # of Goroutines | 621 |

Jira issue: CRDB-45134

**Comment by itsbilal** [comment]
The error message `disk quota exceeded` is not from CRL or Pebble, but rather from the OS or an underlying block device / service. This is also a short-lived `start-single-node` cluster so this is likely not indicative of a pebble bug. Closing.
