### ISSUE TITLE
--insecure flag description is confusing

### ISSUE THREAD

**Issue by gpaul** [cockroachdb/cockroach#13659]
From the CLI help output it seems `--insecure` defaults to `true`, which contradicts its own description.

```
     --insecure                      
        Run over non-encrypted (non-TLS) connections. This is strongly
        discouraged for production usage and this flag must be explicitly
        specified in order for the server to listen on an external address in
        insecure mode.
        Environment variable: COCKROACH_INSECURE
        (default true)
```
Note the last line.

**Comment by tamird** [comment]
Everything there is accurate, but it is slightly confusing. The flag controls the server's acceptance of non-TLS connections, and defaults to true.

However, if you want the server to listen for non-TLS connections on an external address (i.e. not localhost), you must explicitly specify the flag.

**Comment by gpaul** [comment]
Thanks for the clarification. Is specifying the COCKROACH_INSECURE=true environment variable sufficient or does it specifically require the command line flag?

**Comment by jseldess** [comment]
@gpaul, we recently made changes that I believe should resolve this issue. The cli help for `cockroach start` now simply states:

```
      --insecure
        Start an insecure node, using unencrypted (non-TLS) connections. This
        is strongly discouraged for production usage.
```

Whereas previously a cluster was `--insecure` by default, you now must explicitly pass `--insecure` on startup if you do not want TLS. If you don't pass the flag,  and you don't have certs in the default location (the new `--certs-dir` flag), you get an error suggesting you need certs or the `--insecure` flag. 

These and related changes are detailed in the [forum](https://forum.cockroachlabs.com/t/psa-insecure-is-now-false-by-default-certs-dir-replaces-old-certificate-flags/568) as well as in the [beta-20170420]( https://www.cockroachlabs.com/docs/beta-20170420.html) release notes. The [`cockroach start`](https://www.cockroachlabs.com/docs/start-a-node.html) docs and all [deployment guides](https://www.cockroachlabs.com/docs/manual-deployment.html) have also been updated.

Let me know if it's ok to close this issue, or if you still have questions.

**Comment by gpaul** [comment]
Perfect, this is great
