### ISSUE TITLE
distsql: testing infrastructure

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#13665]
This issue tracks adding better testing infrastructure for DistSQL.  In a gist, we want to be able to easily set up tests like those in [TestDistSQLPlanner](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/distsql_physical_planner_test.go#L75) from logic test files.
Once available, we should switch over these tests to the new infrastructure.

The two major things we want:
 - a way to split and distribute tables the way we want; can augment `SPLIT AT` with replica information for the new split and/or use a special column in tables to determine split points. Also switch `SPLIT AT` to a function so that we can feed it from a subquery.
 - a way to generate table data procedurally; we may be able to use subqueries with generators (`GENERATE_SERIES`) but we at least need to develop some sample patterns.

CC @andreimatei

**Comment by RaduBerinde** [comment]
I can work on this in the following days.

**Comment by RaduBerinde** [comment]
Checklist for implementing the RFC in #14146:
- [x] implementing the new SPLIT AT syntax
- [ ] implementing the new TESTING_RELOCATE statement
- [ ] implementing the new SCATTER statement

**Comment by RaduBerinde** [comment]
Quoting an important [suggestion](https://github.com/cockroachdb/cockroach/pull/14146#issuecomment-287197905) by @petermattis:

> To implement scatter, we could add a new admin endpoint that returned the candidate stores given a table or zone config. This would also be useful for upcoming work in the UI to show the effect of a zone config. Cc @bramgruneir, @mrtracy.

**Comment by RaduBerinde** [comment]
`SHOW TESTING_RANGES` and `TESTING_RELOCATE` are in, these were the requirements for distsql tests. I am closing this. I don't think anything is tracking the implementation of `SCATTER`, @danhhz feel free to create an issue to track that.

**Comment by RaduBerinde** [comment]
Actually, reopening to track implementation of SCATTER.

@petermattis: regarding your suggestion above: is the idea that we add this to the `serverpb` admin API and have the sql layer get the info via a loopback HTTP get? One problem is that `serverpb` depends on `storage` and I don't know if we want `sql` to depend on `storage` (even indirectly).

**Comment by petermattis** [comment]
> @petermattis: regarding your suggestion above: is the idea that we add this to the serverpb admin API and have the sql layer get the info via a loopback HTTP get? One problem is that serverpb depends on storage and I don't know if we want sql to depend on storage (even indirectly).

My idea was only half-baked. Yes, I was suggesting an admin API endpoint. But perhaps `sql` should have some internal call it can make, passed in via `sql.ExecutorConfig`.

**Comment by RaduBerinde** [comment]
Got it. Yeah, I think that even if we have an admin endpoint for other reasons, it's probably easier if we provide an internal interface for `sql` to call into that implementation directly.
