### ISSUE TITLE
Sentry: catch.go:29: runtime error: slice bounds out of range [:16] with capacity 5
(1)
Wraps: (2) assertion failure
Wraps: (3) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockro...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#136779]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/6111845638/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/6111845638/?referrer=webhooks_plugin)

Panic Message:

```
catch.go:29: runtime error: slice bounds out of range [:16] with capacity 5
(1)
Wraps: (2) assertion failure
Wraps: (3) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/util/errorutil.ShouldCatch
  | 	github.com/cockroachdb/cockroach/pkg/util/errorutil/catch.go:29
  | github.com/cockroachdb/cockroach/pkg/sql/stats.(*TableStatisticsCache).GetTableStats.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/stats/pkg/sql/stats/stats_cache.go:230
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:770
  | runtime.goPanicSliceAcap
  | 	GOROOT/src/runtime/panic.go:140
  | github.com/cockroachdb/cockroach/pkg/util/encoding.DecodeUntaggedUUIDValue
  | 	github.com/cockroachdb/cockroach/pkg/util/encoding/encoding.go:3160
  | github.com/cockroachdb/cockroach/pkg/sql/rowenc/valueside.DecodeUntaggedDatum
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowenc/valueside/decode.go:187
  | github.com/cockroachdb/cockroach/pkg/sql/rowenc/valueside.Decode
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowenc/valueside/decode.go:46
  | github.com/cockroachdb/cockroach/pkg/sql/rowenc/valueside.decodeTuple
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowenc/valueside/tuple.go:53
  | github.com/cockroachdb/cockroach/pkg/sql/rowenc/valueside.DecodeUntaggedDatum
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowenc/valueside/decode.go:253
  | github.com/cockroachdb/cockroach/pkg/sql/rowenc/valueside.Decode
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowenc/valueside/decode.go:46
  | github.com/cockroachdb/cockroach/pkg/sql/stats.DecodeUpperBound
  | 	github.com/cockroachdb/cockroach/pkg/sql/stats/pkg/sql/stats/histogram.go:118
  | github.com/cockroachdb/cockroach/pkg/sql/stats.DecodeHistogramBuckets
  | 	github.com/cockroachdb/cockroach/pkg/sql/stats/pkg/sql/stats/stats_cache.go:712
  | github.com/cockroachdb/cockroach/pkg/sql/stats.(*TableStatisticsCache).parseStats
  | 	github.com/cockroachdb/cockroach/pkg/sql/stats/pkg/sql/stats/stats_cache.go:676
  | github.com/cockroachdb/cockroach/pkg/sql/stats.(*TableStatisticsCache).getTableStatsFromDB
  | 	github.com/cockroachdb/cockroach/pkg/sql/stats/pkg/sql/stats/stats_cache.go:823
  | github.com/cockroachdb/cockroach/pkg/sql/stats.(*TableStatisticsCache).addCacheEntryLocked.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/stats/pkg/sql/stats/stats_cache.go:434
  | github.com/cockroachdb/cockroach/pkg/sql/stats.(*TableStatisticsCache).addCacheEntryLocked
  | 	github.com/cockroachdb/cockroach/pkg/sql/stats/pkg/sql/stats/stats_cache.go:436
  | github.com/cockroachdb/cockroach/pkg/sql/stats.(*TableStatisticsCache).getTableStatsFromCache
  | 	github.com/cockroachdb/cockroach/pkg/sql/stats/pkg/sql/stats/stats_cache.go:341
  | github.com/cockroachdb/cockroach/pkg/sql/stats.(*TableStatisticsCache).GetTableStats
  | 	github.com/cockroachdb/cockroach/pkg/sql/stats/pkg/sql/stats/stats_cache.go:240
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createStatsPlan
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_plan_stats.go:670
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPlanForCreateStats
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_plan_stats.go:723
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).planAndRunCreateStats
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_plan_stats.go:738
  | github.com/cockroachdb/cockroach/pkg/sql.(*createStatsResumer).Resume.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/create_stats.go:697
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).Txn.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1941
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).txn.func4
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:2028
  | github.com/cockroachdb/cockroach/pkg/kv.(*Txn).exec
  | 	github.com/cockroachdb/cockroach/pkg/kv/txn.go:1057
  | github.com/cockroachdb/cockroach/pkg/kv.runTxn
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:1103
  | github.com/cockroachdb/cockroach/pkg/kv.(*DB).TxnWithAdmissionControl
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:1066
  | github.com/cockroachdb/cockroach/pkg/kv.(*DB).Txn
  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:1041
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).txn
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:2015
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalDB).Txn
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1942
  | github.com/cockroachdb/cockroach/pkg/sql.(*createStatsResumer).Resume
  | 	github.com/cockroachdb/cockroach/pkg/sql/create_stats.go:668
  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine.func2
  | 	github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1632
Wraps: (4) runtime error: slice bounds out of range [:16] with capacity 5
  | -- cause hidden behind barrier
  | runtime error: slice bounds out of range [:16] with capacity 5
  | (1) runtime error: slice bounds out of range [:16] with capacity 5
  | Error types: (1) runtime.boundsError
Error types: (1) *colexecerror.notInternalError (2) *assert.withAssertionFailure (3) *withstack.withStack (4) *barriers.barrierErr
-- report composition:
*barriers.barrierErr: masked error: runtime error: slice bounds out of range [:16] with capacity 5
catch.go:29: *withstack.withStack (top exception)
*assert.withAssertionFailure
*colexecerror.notInternalError
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/jobs/registry.go#L1631-L1633](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/jobs/registry.go#L1631-L1633)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/create_stats.go#L667-L669](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/create_stats.go#L667-L669)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/internal.go#L1941-L1943](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/internal.go#L1941-L1943)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/internal.go#L2014-L2016](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/internal.go#L2014-L2016)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/kv/db.go#L1040-L1042](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/kv/db.go#L1040-L1042)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/kv/db.go#L1065-L1067](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/kv/db.go#L1065-L1067)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/kv/db.go#L1102-L1104](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/kv/db.go#L1102-L1104)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/kv/txn.go#L1056-L1058](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/kv/txn.go#L1056-L1058)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/internal.go#L2027-L2029](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/internal.go#L2027-L2029)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/internal.go#L1940-L1942](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/internal.go#L1940-L1942)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/create_stats.go#L696-L698](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/create_stats.go#L696-L698)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/distsql_plan_stats.go#L737-L739](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/distsql_plan_stats.go#L737-L739)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/distsql_plan_stats.go#L722-L724](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/distsql_plan_stats.go#L722-L724)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/distsql_plan_stats.go#L669-L671](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/distsql_plan_stats.go#L669-L671)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/stats/pkg/sql/stats/stats_cache.go#L239-L241](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/stats/pkg/sql/stats/stats_cache.go#L239-L241)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/stats/pkg/sql/stats/stats_cache.go#L340-L342](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/stats/pkg/sql/stats/stats_cache.go#L340-L342)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/stats/pkg/sql/stats/stats_cache.go#L435-L437](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/stats/pkg/sql/stats/stats_cache.go#L435-L437)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/stats/pkg/sql/stats/stats_cache.go#L433-L435](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/stats/pkg/sql/stats/stats_cache.go#L433-L435)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/stats/pkg/sql/stats/stats_cache.go#L822-L824](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/stats/pkg/sql/stats/stats_cache.go#L822-L824)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/stats/pkg/sql/stats/stats_cache.go#L675-L677](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/stats/pkg/sql/stats/stats_cache.go#L675-L677)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/stats/pkg/sql/stats/stats_cache.go#L711-L713](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/stats/pkg/sql/stats/stats_cache.go#L711-L713)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/stats/pkg/sql/stats/histogram.go#L117-L119](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/stats/pkg/sql/stats/histogram.go#L117-L119)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/rowenc/valueside/decode.go#L45-L47](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/rowenc/valueside/decode.go#L45-L47)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/rowenc/valueside/decode.go#L252-L254](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/rowenc/valueside/decode.go#L252-L254)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/rowenc/valueside/tuple.go#L52-L54](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/rowenc/valueside/tuple.go#L52-L54)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/rowenc/valueside/decode.go#L45-L47](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/rowenc/valueside/decode.go#L45-L47)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/rowenc/valueside/decode.go#L186-L188](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/rowenc/valueside/decode.go#L186-L188)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/util/encoding/encoding.go#L3159-L3161](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/util/encoding/encoding.go#L3159-L3161)
[GOROOT/src/runtime/panic.go#L139-L141](GOROOT/src/runtime/panic.go#L139-L141)
[GOROOT/src/runtime/panic.go#L769-L771](GOROOT/src/runtime/panic.go#L769-L771)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/stats/pkg/sql/stats/stats_cache.go#L229-L231](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/sql/stats/pkg/sql/stats/stats_cache.go#L229-L231)
[https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/util/errorutil/catch.go#L28-L30](https://github.com/cockroachdb/cockroach/blob/8140b8e294fb16a293d0aae662bcf5c1d488c852/pkg/util/errorutil/catch.go#L28-L30)
</details>

```
pkg/jobs/registry.go in pkg/jobs.(*Registry).stepThroughStateMachine.func2 at line 1632
pkg/sql/create_stats.go in pkg/sql.(*createStatsResumer).Resume at line 668
pkg/sql/internal.go in pkg/sql.(*InternalDB).Txn at line 1942
pkg/sql/internal.go in pkg/sql.(*InternalDB).txn at line 2015
pkg/kv/db.go in pkg/kv.(*DB).Txn at line 1041
pkg/kv/db.go in pkg/kv.(*DB).TxnWithAdmissionControl at line 1066
pkg/kv/db.go in pkg/kv.runTxn at line 1103
pkg/kv/txn.go in pkg/kv.(*Txn).exec at line 1057
pkg/sql/internal.go in pkg/sql.(*InternalDB).txn.func4 at line 2028
pkg/sql/internal.go in pkg/sql.(*InternalDB).Txn.func1 at line 1941
pkg/sql/create_stats.go in pkg/sql.(*createStatsResumer).Resume.func1 at line 697
pkg/sql/distsql_plan_stats.go in pkg/sql.(*DistSQLPlanner).planAndRunCreateStats at line 738
pkg/sql/distsql_plan_stats.go in pkg/sql.(*DistSQLPlanner).createPlanForCreateStats at line 723
pkg/sql/distsql_plan_stats.go in pkg/sql.(*DistSQLPlanner).createStatsPlan at line 670
pkg/sql/stats/pkg/sql/stats/stats_cache.go in pkg/sql/stats.(*TableStatisticsCache).GetTableStats at line 240
pkg/sql/stats/pkg/sql/stats/stats_cache.go in pkg/sql/stats.(*TableStatisticsCache).getTableStatsFromCache at line 341
pkg/sql/stats/pkg/sql/stats/stats_cache.go in pkg/sql/stats.(*TableStatisticsCache).addCacheEntryLocked at line 436
pkg/sql/stats/pkg/sql/stats/stats_cache.go in pkg/sql/stats.(*TableStatisticsCache).addCacheEntryLocked.func1 at line 434
pkg/sql/stats/pkg/sql/stats/stats_cache.go in pkg/sql/stats.(*TableStatisticsCache).getTableStatsFromDB at line 823
pkg/sql/stats/pkg/sql/stats/stats_cache.go in pkg/sql/stats.(*TableStatisticsCache).parseStats at line 676
pkg/sql/stats/pkg/sql/stats/stats_cache.go in pkg/sql/stats.DecodeHistogramBuckets at line 712
pkg/sql/stats/pkg/sql/stats/histogram.go in pkg/sql/stats.DecodeUpperBound at line 118
pkg/sql/rowenc/valueside/decode.go in pkg/sql/rowenc/valueside.Decode at line 46
pkg/sql/rowenc/valueside/decode.go in pkg/sql/rowenc/valueside.DecodeUntaggedDatum at line 253
pkg/sql/rowenc/valueside/tuple.go in pkg/sql/rowenc/valueside.decodeTuple at line 53
pkg/sql/rowenc/valueside/decode.go in pkg/sql/rowenc/valueside.Decode at line 46
pkg/sql/rowenc/valueside/decode.go in pkg/sql/rowenc/valueside.DecodeUntaggedDatum at line 187
pkg/util/encoding/encoding.go in pkg/util/encoding.DecodeUntaggedUUIDValue at line 3160
GOROOT/src/runtime/panic.go in runtime.goPanicSliceAcap at line 140
GOROOT/src/runtime/panic.go in runtime.gopanic at line 770
pkg/sql/stats/pkg/sql/stats/stats_cache.go in pkg/sql/stats.(*TableStatisticsCache).GetTableStats.func1 at line 230
pkg/util/errorutil/catch.go in pkg/util/errorutil.ShouldCatch at line 29
```

### Tags

| Tag | Value |
| --- | --- |
| Command | mt start-sql |
| Environment | v24.2.4 |
| Go Version | go1.22.5 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v24.2.4 |
| Cockroach SHA | 8140b8e294fb16a293d0aae662bcf5c1d488c852 |
| # of CPUs | 32 |
| # of Goroutines | 435 |

Jira issue: CRDB-45244

**Comment by yuzefovich** [comment]
dup of #128876
