### ISSUE TITLE
client: support concurrent Batch execution on client.Txn objects

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#13684]
One of the larger tasks needed for #13160 is to support running concurrent `client.Batch`
objects on a single `client.Txn` from different goroutines. Initial attempts at supporting this
have consisted of mechanical changes to synchronize access to transaction state, because the underlying transaction model was designed to support a concurrent execution model for most operations. This extends from the design that transaction ratcheting effects are all commutative and that most state transitions that transactions undergo are idempotent.

The only place that I have found where this assumption breaks down is during transaction creation. Our `client.Txn` implementation includes a `roachpb.BeginTransactionRequest` before the first transactional write that it sees after examining all requests in each `BatchRequest` that it sends. It then does not update its `Writing` flag until that `BeginTransactionRequest` returns successfully. This is problematic for concurrent batches because, without any special handling, it will result in multiple `BeginTransactionRequest`s being sent. Currently, we [throw an error](https://github.com/cockroachdb/cockroach/blob/9d0e8b7ffeabfbb38b1ef3bf5287efeebd43a01d/pkg/storage/replica_command.go#L443) on duplicate `BeginTransaction` requests, because we deem that a client error has occurred.

The two possible solutions I see to this are:
- When the first `roachpb.BeginTransactionRequest` is sent, we block all other requests from executing at the client until the result of that request is known. This would prevent multiple `BeginTransactionRequest`s from ever being sent for the same transaction. It would also prevent other transaction initialization state from racing between client threads, such as transaction `Id` and anchor `Key`.
- We make `roachpb.BeginTransactionRequest` idempotent for a given transaction with the same key and ID. This would allow the current approach to work with minimal changes. The only complication to this is that we'll need to synchronize at the client for transaction initialization. This would probably mean pulling the logic in [maybeBeginTxn](https://github.com/cockroachdb/cockroach/blob/3c8cf113611a3d1f0dc519c428569d543ba0cec9/pkg/kv/txn_coord_sender.go#L510) into the `client` package, which has already been suggested by Andrei [here](https://github.com/cockroachdb/cockroach/blob/4c174761c24a1af6d864a30bed4d35159032db14/pkg/internal/client/txn.go#L557). This change would certainly have a larger impact on our transaction semantics, and I'm not sure I fully understand all of its ramifications.

@andreimatei and @bdarnell, do either of you have any insight into this?

**Comment by andreimatei** [comment]
The disadvantage of option a) is that all requests within on txn would need to wait for the first write batch to complete, right?

I've got a probably stupid question - with option b), why exactly do we need to send a `BeginTransactionRequest` multiple times (with multiple batches)? Can't the client just remember the fact that it has already sent one request with a `BeginTxnReq` and, even if that request is still in flight and doesn't have a result yet, allow other write batches to be sent (after having the header  initialized with the pending txn id which, as you say, should be initialized by the client)? I'm not sure how we'd handle the failure of the `BeginTxnReq` - not sure what would happen if we don't do any cleanup for the other writes? To do cleanup more properly we probably need the `TxnCoordSender`/`client.Txn` merger that's frequently referenced - #10511.

**Comment by nvanbenschoten** [comment]
Right, the main downside is that we would need to limit concurrency for transactions before the `BeginTransactionRequest` has been sent and acknowledged. This requires some generally ugly handling of batches that may overlap, and it would be nice to avoid by improving the underlying model instead.

There were two reasons why I didn't think what you proposed was possible. First, I didn't realize the kv/storage layer supported operations on transactions that have not yet created a transaction record. This would be necessary because there are no guarantees against the inflight `BeginTxnReq` getting reordered with a concurrent batch that does not contain a `BeginTxnReq`. I also was not sure how we would handle a `BeginTxnReq` failure. Would this cause us to leak requests that would never be cleaned up? What happens if the client goes down during this period? If both of those concerns turn out to be unfounded, then making sure to only send one `BeginTxnReq` at the client would be an easy way to fix this.

With regard to #10511, I'm currently putting that on hold, as the refactoring required a huge amount of code movement and changes to tests, without any direct benefit to this issue. I'd rather not try to make a stability-related change on top of a large refactoring. That said if the client/kv interface gets any more complex because of this change (extra cleanup logic, for instance), I may reconsider that decision.

**Comment by bdarnell** [comment]
The storage layer does (mostly) support transactional writes that occur before BeginTransaction has finished. These writes can occur naturally with the way that DistSender splits up batches (BeginTransaction is not guaranteed to be in the first batch). However, when this happens the transaction is vulnerable to being aborted since it automatically loses any pushes that occur before its transaction record has been written (see #9287), so we should try to ensure that BeginTransaction is at least concurrent with the first write (as long as it's been proposed to raft before any subsequent writes complete, we know it will be safe from pushes that could be a consequence of those writes)

I don't think repeating the BeginTransaction as in option B helps much; I think the best approach is to just send it on the first write and not wait for it to complete.
