### ISSUE TITLE
sql: `create table x; begin; drop table x; create table x`: relation `x` already exists

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#13686]
I believe this was discussed somewhere already, but wasn't able to find it. It's perhaps similar in spirit to #13505.

The problem is (presumably) that the table is really only dropped when the transaction commits, but the recreation in the same txn explicitly requires it to be (assumed) gone before commit.

Found while trying to use `diesel-rs`, which reliably triggers this with when following http://diesel.rs/guides/getting-started/ at `diesel migration run; diesel migration redo`.

**Comment by nvanbenschoten** [comment]
IIRC, @andreimatei is intimately familiar with this issue.

**Comment by a-robinson** [comment]
Yeah, we already have some discussion about this on #12123.
