### ISSUE TITLE
sql: "interval `1` year" is interpeted as an interval of 1 second

### ISSUE THREAD

**Issue by arjunravinarayan** [cockroachdb/cockroach#13693]
```
root@:26257/foo> SELECT INTERVAL '1 year';
+-------------------+
| INTERVAL '1 year' |
+-------------------+
| 12m0d0ns          |
+-------------------+
(1 row)
root@:26257/foo> SELECT INTERVAL '1' year;
+--------------+
| INTERVAL '1' |
+--------------+
| 1s           |
+--------------+
(1 row)
```

This seems wrong, because at least one line of SQL in the wild uses the latter format: https://github.com/oltpbenchmark/oltpbench/blob/master/src/com/oltpbenchmark/benchmarks/tpch/queries/query5.sql#L20

cc @cuongdo as this might fall under ORM support? Perhaps we should have "syntax support group" as a superset of the ORM team since this has nothing to do with any specific ORM.

**Comment by jordanlewis** [comment]
The trouble here is that the new parser introduced for the special `SET TIMEZONE <interval>` syntax is not being properly used for `INTERVAL` in other normal contexts.
