### ISSUE TITLE
Sentry: txn_lock_gatekeeper.go:65: ×: concurrent txn use detected. ba: Get [/Tenant/2038/NamespaceTable/30/1/163/167/"privileges"/4/1], [txn: ec10bea2] (1) secondary error attachment   | ×: concurre...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#136976]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/6118623859/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/6118623859/?referrer=webhooks_plugin)

Panic Message:

```
txn_lock_gatekeeper.go:65: ×: concurrent txn use detected. ba: Get [/Tenant/2038/NamespaceTable/30/1/163/167/"privileges"/4/1], [txn: ec10bea2]
(1) secondary error attachment
  | ×: concurrent txn use detected. ba: Get [/Tenant/2038/NamespaceTable/30/1/163/167/"privileges"/4/1], [txn: ec10bea2]
  | (1) attached stack trace
  |   -- stack trace:
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).execInternal.func1.1
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1259
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*rowsIterator).Next.func1
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:554
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*rowsIterator).Next
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:613
  |   | github.com/cockroachdb/cockroach/pkg/sql/syntheticprivilegecache.(*Cache).readFromStorage
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/syntheticprivilegecache/cache.go:140
  |   | github.com/cockroachdb/cockroach/pkg/sql/syntheticprivilegecache.(*Cache).Get.func1
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/syntheticprivilegecache/cache.go:88
  |   | github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight.(*Group).doCall.func1
  |   | 	github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight/singleflight.go:384
  |   | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTask
  |   | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:315
  |   | github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight.(*Group).doCall
  |   | 	github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight/singleflight.go:383
  |   | runtime.goexit
  |   | 	src/runtime/asm_amd64.s:1695
  | Wraps: (2) ×
  | Wraps: (3) assertion failure
  | Wraps: (4)
  |   | (opaque error wrapper)
  |   | type name: github.com/cockroachdb/errors/withstack/*withstack.withStack
  |   | reportable 0:
  |   |
  |   | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnLockGatekeeper).SendLocked
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_lock_gatekeeper.go:65
  |   | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnMetricRecorder).SendLocked
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_metric_recorder.go:41
  |   | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnSpanRefresher).sendLockedWithRefreshAttempts
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go:234
  |   | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnSpanRefresher).SendLocked
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go:162
  |   | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnCommitter).SendLocked
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_committer.go:144
  |   | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnPipeliner).SendLocked
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go:321
  |   | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnSeqNumAllocator).SendLocked
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_seq_num_allocator.go:112
  |   | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnHeartbeater).SendLocked
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater.go:265
  |   | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*TxnCoordSender).Send
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_coord_sender.go:534
  |   | github.com/cockroachdb/cockroach/pkg/kv.(*DB).sendUsingSender
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:1133
  |   | github.com/cockroachdb/cockroach/pkg/kv.(*Txn).Send
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/txn.go:1286
  |   | github.com/cockroachdb/cockroach/pkg/kv.sendAndFill
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:965
  |   | github.com/cockroachdb/cockroach/pkg/kv.(*Txn).Run
  |   | 	github.com/cockroachdb/cockroach/pkg/kv/txn.go:803
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.catalogQuery.query
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_query.go:54
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.catalogReader.GetByNames
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_reader.go:328
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.(*cachedCatalogReader).GetByNames
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_reader_cached.go:393
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).getNonVirtualDescriptorID.func7
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:594
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).getNonVirtualDescriptorID
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:615
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.getDescriptorByName
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:393
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.ByNameGetter.Table
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/getters.go:296
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.PrefixAndTable
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/helpers.go:133
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*schemaResolver).LookupObject
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/schema_resolver.go:168
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/resolver.ResolveExisting
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/resolver/resolver.go:340
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/resolver.ResolveExistingObject
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/resolver/resolver.go:179
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/resolver.ResolveExistingTableObject
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/resolver/resolver.go:103
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*optCatalog).ResolveDataSource
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/opt_catalog.go:255
  |   | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).resolveDataSource
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/util.go:665
  |   | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildDataSource
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:134
  |   | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildDataSource
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:89
  |   | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildFromTablesRightDeep
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:1409
  |   | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildFromTables
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:1386
  |   | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildFrom
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:1316
  | Wraps: (5) concurrent txn use detected. ba: Get [/Tenant/2038/NamespaceTable/30/1/163/167/"privileges"/4/1], [txn: ec10bea2]
  | Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *assert.withAssertionFailure (4) *errbase.opaqueWrapper (5) *errutil.leafError
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).execInternal.func1.1
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:1259
  | github.com/cockroachdb/cockroach/pkg/sql.(*rowsIterator).Next.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/internal.go:554
  | github.com/cockroachdb/cockroach/pkg/sql.(*rowsIterator).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/...
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_amd64.s#L1694-L1696](src/runtime/asm_amd64.s#L1694-L1696)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/util/syncutil/singleflight/singleflight.go#L382-L384](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/util/syncutil/singleflight/singleflight.go#L382-L384)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/util/stop/stopper.go#L314-L316](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/util/stop/stopper.go#L314-L316)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/util/syncutil/singleflight/singleflight.go#L383-L385](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/util/syncutil/singleflight/singleflight.go#L383-L385)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/syntheticprivilegecache/cache.go#L87-L89](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/syntheticprivilegecache/cache.go#L87-L89)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/syntheticprivilegecache/cache.go#L139-L141](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/syntheticprivilegecache/cache.go#L139-L141)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/internal.go#L612-L614](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/internal.go#L612-L614)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/internal.go#L553-L555](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/internal.go#L553-L555)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/internal.go#L1258-L1260](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/internal.go#L1258-L1260)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/opt/optbuilder/select.go#L1315-L1317](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/opt/optbuilder/select.go#L1315-L1317)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/opt/optbuilder/select.go#L1385-L1387](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/opt/optbuilder/select.go#L1385-L1387)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/opt/optbuilder/select.go#L1408-L1410](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/opt/optbuilder/select.go#L1408-L1410)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/opt/optbuilder/select.go#L88-L90](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/opt/optbuilder/select.go#L88-L90)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/opt/optbuilder/select.go#L133-L135](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/opt/optbuilder/select.go#L133-L135)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/opt/optbuilder/util.go#L664-L666](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/opt/optbuilder/util.go#L664-L666)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/opt_catalog.go#L254-L256](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/opt_catalog.go#L254-L256)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/catalog/resolver/resolver.go#L102-L104](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/catalog/resolver/resolver.go#L102-L104)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/catalog/resolver/resolver.go#L178-L180](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/catalog/resolver/resolver.go#L178-L180)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/catalog/resolver/resolver.go#L339-L341](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/catalog/resolver/resolver.go#L339-L341)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/schema_resolver.go#L167-L169](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/schema_resolver.go#L167-L169)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/catalog/descs/helpers.go#L132-L134](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/catalog/descs/helpers.go#L132-L134)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/catalog/descs/getters.go#L295-L297](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/catalog/descs/getters.go#L295-L297)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/catalog/descs/descriptor.go#L392-L394](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/catalog/descs/descriptor.go#L392-L394)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/catalog/descs/descriptor.go#L614-L616](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/catalog/descs/descriptor.go#L614-L616)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/catalog/descs/descriptor.go#L593-L595](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/catalog/descs/descriptor.go#L593-L595)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/catalog/internal/catkv/catalog_reader_cached.go#L392-L394](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/catalog/internal/catkv/catalog_reader_cached.go#L392-L394)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/catalog/internal/catkv/catalog_reader.go#L327-L329](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/catalog/internal/catkv/catalog_reader.go#L327-L329)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/catalog/internal/catkv/catalog_query.go#L53-L55](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/catalog/internal/catkv/catalog_query.go#L53-L55)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/kv/txn.go#L802-L804](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/kv/txn.go#L802-L804)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/kv/db.go#L964-L966](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/kv/db.go#L964-L966)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/kv/txn.go#L1285-L1287](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/kv/txn.go#L1285-L1287)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/kv/db.go#L1132-L1134](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/kv/db.go#L1132-L1134)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L533-L535](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L533-L535)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater.go#L264-L266](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater.go#L264-L266)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/kv/kvclient/kvcoord/txn_interceptor_seq_num_allocator.go#L111-L113](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/kv/kvclient/kvcoord/txn_interceptor_seq_num_allocator.go#L111-L113)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go#L320-L322](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go#L320-L322)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/kv/kvclient/kvcoord/txn_interceptor_committer.go#L143-L145](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/kv/kvclient/kvcoord/txn_interceptor_committer.go#L143-L145)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go#L161-L163](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go#L161-L163)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go#L233-L235](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go#L233-L235)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/kv/kvclient/kvcoord/txn_interceptor_metric_recorder.go#L40-L42](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/kv/kvclient/kvcoord/txn_interceptor_metric_recorder.go#L40-L42)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/kv/kvclient/kvcoord/txn_lock_gatekeeper.go#L64-L66](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/kv/kvclient/kvcoord/txn_lock_gatekeeper.go#L64-L66)
</details>

```
src/runtime/asm_amd64.s in runtime.goexit at line 1695
pkg/util/syncutil/singleflight/singleflight.go in pkg/util/syncutil/singleflight.(*Group).doCall at line 383
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunTask at line 315
pkg/util/syncutil/singleflight/singleflight.go in pkg/util/syncutil/singleflight.(*Group).doCall.func1 at line 384
pkg/sql/syntheticprivilegecache/cache.go in pkg/sql/syntheticprivilegecache.(*Cache).Get.func1 at line 88
pkg/sql/syntheticprivilegecache/cache.go in pkg/sql/syntheticprivilegecache.(*Cache).readFromStorage at line 140
pkg/sql/internal.go in pkg/sql.(*rowsIterator).Next at line 613
pkg/sql/internal.go in pkg/sql.(*rowsIterator).Next.func1 at line 554
pkg/sql/internal.go in pkg/sql.(*InternalExecutor).execInternal.func1.1 at line 1259
pkg/sql/opt/optbuilder/select.go in pkg/sql/opt/optbuilder.(*Builder).buildFrom at line 1316
pkg/sql/opt/optbuilder/select.go in pkg/sql/opt/optbuilder.(*Builder).buildFromTables at line 1386
pkg/sql/opt/optbuilder/select.go in pkg/sql/opt/optbuilder.(*Builder).buildFromTablesRightDeep at line 1409
pkg/sql/opt/optbuilder/select.go in pkg/sql/opt/optbuilder.(*Builder).buildDataSource at line 89
pkg/sql/opt/optbuilder/select.go in pkg/sql/opt/optbuilder.(*Builder).buildDataSource at line 134
pkg/sql/opt/optbuilder/util.go in pkg/sql/opt/optbuilder.(*Builder).resolveDataSource at line 665
pkg/sql/opt_catalog.go in pkg/sql.(*optCatalog).ResolveDataSource at line 255
pkg/sql/catalog/resolver/resolver.go in pkg/sql/catalog/resolver.ResolveExistingTableObject at line 103
pkg/sql/catalog/resolver/resolver.go in pkg/sql/catalog/resolver.ResolveExistingObject at line 179
pkg/sql/catalog/resolver/resolver.go in pkg/sql/catalog/resolver.ResolveExisting at line 340
pkg/sql/schema_resolver.go in pkg/sql.(*schemaResolver).LookupObject at line 168
pkg/sql/catalog/descs/helpers.go in pkg/sql/catalog/descs.PrefixAndTable at line 133
pkg/sql/catalog/descs/getters.go in pkg/sql/catalog/descs.ByNameGetter.Table at line 296
pkg/sql/catalog/descs/descriptor.go in pkg/sql/catalog/descs.getDescriptorByName at line 393
pkg/sql/catalog/descs/descriptor.go in pkg/sql/catalog/descs.(*Collection).getNonVirtualDescriptorID at line 615
pkg/sql/catalog/descs/descriptor.go in pkg/sql/catalog/descs.(*Collection).getNonVirtualDescriptorID.func7 at line 594
pkg/sql/catalog/internal/catkv/catalog_reader_cached.go in pkg/sql/catalog/internal/catkv.(*cachedCatalogReader).GetByNames at line 393
pkg/sql/catalog/internal/catkv/catalog_reader.go in pkg/sql/catalog/internal/catkv.catalogReader.GetByNames at line 328
pkg/sql/catalog/internal/catkv/catalog_query.go in pkg/sql/catalog/internal/catkv.catalogQuery.query at line 54
pkg/kv/txn.go in pkg/kv.(*Txn).Run at line 803
pkg/kv/db.go in pkg/kv.sendAndFill at line 965
pkg/kv/txn.go in pkg/kv.(*Txn).Send at line 1286
pkg/kv/db.go in pkg/kv.(*DB).sendUsingSender at line 1133
pkg/kv/kvclient/kvcoord/txn_coord_sender.go in pkg/kv/kvclient/kvcoord.(*TxnCoordSender).Send at line 534
pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater.go in pkg/kv/kvclient/kvcoord.(*txnHeartbeater).SendLocked at line 265
pkg/kv/kvclient/kvcoord/txn_interceptor_seq_num_allocator.go in pkg/kv/kvclient/kvcoord.(*txnSeqNumAllocator).SendLocked at line 112
pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go in pkg/kv/kvclient/kvcoord.(*txnPipeliner).SendLocked at line 321
pkg/kv/kvclient/kvcoord/txn_interceptor_committer.go in pkg/kv/kvclient/kvcoord.(*txnCommitter).SendLocked at line 144
pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go in pkg/kv/kvclient/kvcoord.(*txnSpanRefresher).SendLocked at line 162
pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go in pkg/kv/kvclient/kvcoord.(*txnSpanRefresher).sendLockedWithRefreshAttempts at line 234
pkg/kv/kvclient/kvcoord/txn_interceptor_metric_recorder.go in pkg/kv/kvclient/kvcoord.(*txnMetricRecorder).SendLocked at line 41
pkg/kv/kvclient/kvcoord/txn_lock_gatekeeper.go in pkg/kv/kvclient/kvcoord.(*txnLockGatekeeper).SendLocked at line 65
```

### Tags

| Tag | Value |
| --- | --- |
| Command | mt start-sql |
| Environment | v24.2.5 |
| Go Version | go1.22.5 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v24.2.5 |
| Cockroach SHA | beddec16a5a438d66bd3f5f4202085cf21c0973c |
| # of CPUs | 32 |
| # of Goroutines | 380 |

Jira issue: CRDB-45331

**Comment by yuzefovich** [comment]
dup of #132706
