### ISSUE TITLE
sql: REGCLASS casts don't behave properly when the user is root

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#13695]
When the current user is root, virtual tables that expose information about database tables (including `pg_class`) have no restrictions on what tables they show. The query used to look up information in `pg_class` by table name does not qualify the table by the current database, so in the case that two databases have an identically named table, the query will fail due to returning too many results.

**Comment by cuongdo** [comment]
what is the effect of this? does this need to be fixed by 1.0?

**Comment by jordanlewis** [comment]
This will cause ORM-style metadata queries to sometimes fail when run as `root`. It also precludes our ActiveRecord example from working. This is trivial to fix - I was planning to get to it today or tomorrow.
