### ISSUE TITLE
storage: filesystem reporting seems buggy

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#137021]
We use `filepath.Rel` to associate a mountpoint to a filesystem: https://github.com/cockroachdb/cockroach/blob/c68c559859be738efead9971f5e11f62a8c69d06/pkg/storage/store_properties.go#L80

I think this is buggy because `Rel` can add `..` as seen here: https://cs.opensource.google/go/go/+/refs/tags/go1.23.4:src/path/filepath/path.go;l=234

In #136932 we see it reporting a `tmpfs` mount at `/run/user/1001` for the store at ` /cockroach/cockroach-data`. 

Jira issue: CRDB-45360

**Comment by cdprete** [comment]
Hi @RaduBerinde.
Just to have the full picture, that's the output of the `df -h` command from my side:
![image](https://github.com/user-attachments/assets/36571262-784c-45fb-9bef-a78986d0fb8a)
