### ISSUE TITLE
sql: reconcile "desired" and "actual" orderings

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#13709]
Found / reported / discussed in https://github.com/cockroachdb/cockroach/pull/13703#discussion_r102361781

> A more general fix would be to also pass the desired/useful ordering to computeOrdering so that when it has a choice, it chooses something that matches the given ordering more. In that case, we would want to do it this way, as trim() wouldn't have that capability.

**Comment by dianasaur323** [comment]
@knz moving to 1.1 unless you disagree

**Comment by andy-kimball** [comment]
Closing as "obsolete", as the cost-based optimizer works differently.
