### ISSUE TITLE
Sentry: information_schema.go:810: error resolving table 170 referenced in foreign key × in table ×: relation × does not exist
(1)
Wraps: (2)
Wraps: (3)
Wraps: (4) assertion failure
Wraps: (5) atta...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#137074]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/6125051743/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/6125051743/?referrer=webhooks_plugin)

Panic Message:

```
information_schema.go:810: error resolving table 170 referenced in foreign key × in table ×: relation × does not exist
(1)
Wraps: (2)
Wraps: (3)
Wraps: (4) assertion failure
Wraps: (5) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.init.func748.1
  | 	github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:810
  | github.com/cockroachdb/cockroach/pkg/sql.forEachTableDescWithTableLookupInternalFromDescriptors
  | 	github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:2857
  | github.com/cockroachdb/cockroach/pkg/sql.forEachTableDescWithTableLookupInternal
  | 	github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:2730
  | github.com/cockroachdb/cockroach/pkg/sql.forEachTableDescWithTableLookup
  | 	github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:2701
  | github.com/cockroachdb/cockroach/pkg/sql.init.func748
  | 	github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:790
  | github.com/cockroachdb/cockroach/pkg/sql.(*virtualDefEntry).getPlanInfo.func1.1
  | 	github.com/cockroachdb/cockroach/pkg/sql/virtual_schema.go:656
  | github.com/cockroachdb/cockroach/pkg/sql.setupGenerator.func3
  | 	github.com/cockroachdb/cockroach/pkg/sql/virtual_table.go:122
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:480
  | runtime.goexit
  | 	src/runtime/asm_amd64.s:1695
Wraps: (6) error resolving table 170 referenced in foreign key × in table ×
Wraps: (7) relation × does not exist
  | -- cause hidden behind barrier
  | relation × does not exist
  | (1) candidate pg code: 42P01
  | Wraps: (2) attached stack trace
  |   -- stack trace:
  |   | github.com/cockroachdb/cockroach/pkg/sql/sqlerrors.NewUndefinedRelationError
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/sqlerrors/errors.go:171
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*internalLookupCtx).getTableByID
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/resolver.go:953
  |   | github.com/cockroachdb/cockroach/pkg/sql.init.func748.1
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:808
  |   | github.com/cockroachdb/cockroach/pkg/sql.forEachTableDescWithTableLookupInternalFromDescriptors
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:2857
  |   | github.com/cockroachdb/cockroach/pkg/sql.forEachTableDescWithTableLookupInternal
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:2730
  |   | github.com/cockroachdb/cockroach/pkg/sql.forEachTableDescWithTableLookup
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:2701
  |   | github.com/cockroachdb/cockroach/pkg/sql.init.func748
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:790
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*virtualDefEntry).getPlanInfo.func1.1
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/virtual_schema.go:656
  |   | github.com/cockroachdb/cockroach/pkg/sql.setupGenerator.func3
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/virtual_table.go:122
  |   | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  |   | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:480
  |   | runtime.goexit
  |   | 	src/runtime/asm_amd64.s:1695
  | Wraps: (3) relation × does not exist
  | Error types: (1) *pgerror.withCandidateCode (2) *withstack.withStack (3) *errutil.leafError
Error types: (1) *colexecerror.notInternalError (2) *colexecerror.notInternalError (3) *colexecerror.notInternalError (4) *assert.withAssertionFailure (5) *withstack.withStack (6) *errutil.withPrefix (7) *barriers.barrierErr
-- report composition:
*barriers.barrierErr: details for github.com/cockroachdb/cockroach/pkg/sql/pgwire/pgerror/*pgerror.withCandidateCode:::
*errutil.withPrefix: error resolving table 170 referenced in foreign key × in table ×
information_schema.go:810: *withstack.withStack (top exception)
*assert.withAssertionFailure
*colexecerror.notInternalError
*colexecerror.notInternalError
*colexecerror.notInternalError
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_amd64.s#L1694-L1696](src/runtime/asm_amd64.s#L1694-L1696)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/util/stop/stopper.go#L479-L481](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/util/stop/stopper.go#L479-L481)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/virtual_table.go#L121-L123](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/virtual_table.go#L121-L123)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/virtual_schema.go#L655-L657](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/virtual_schema.go#L655-L657)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/information_schema.go#L789-L791](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/information_schema.go#L789-L791)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/information_schema.go#L2700-L2702](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/information_schema.go#L2700-L2702)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/information_schema.go#L2729-L2731](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/information_schema.go#L2729-L2731)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/information_schema.go#L2856-L2858](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/information_schema.go#L2856-L2858)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/information_schema.go#L809-L811](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/information_schema.go#L809-L811)
</details>

```
src/runtime/asm_amd64.s in runtime.goexit at line 1695
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 480
pkg/sql/virtual_table.go in pkg/sql.setupGenerator.func3 at line 122
pkg/sql/virtual_schema.go in pkg/sql.(*virtualDefEntry).getPlanInfo.func1.1 at line 656
pkg/sql/information_schema.go in pkg/sql.init.func748 at line 790
pkg/sql/information_schema.go in pkg/sql.forEachTableDescWithTableLookup at line 2701
pkg/sql/information_schema.go in pkg/sql.forEachTableDescWithTableLookupInternal at line 2730
pkg/sql/information_schema.go in pkg/sql.forEachTableDescWithTableLookupInternalFromDescriptors at line 2857
pkg/sql/information_schema.go in pkg/sql.init.func748.1 at line 810
```

### Tags

| Tag | Value |
| --- | --- |
| Command | mt start-sql |
| Environment | v24.2.5 |
| Go Version | go1.22.5 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v24.2.5 |
| Cockroach SHA | beddec16a5a438d66bd3f5f4202085cf21c0973c |
| # of CPUs | 32 |
| # of Goroutines | 374 |

Jira issue: CRDB-45373

**Comment by Dedej-Bergin** [comment]
Not enough information, closing this issue.
