### ISSUE TITLE
docs: document that result ordering can vary arbitrarily without `ORDER BY`

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#13710]
Suggested in https://github.com/cockroachdb/cockroach/pull/13706#issuecomment-281730585

We should make it extra clear in the docs that any `SELECT` statement with no `ORDER BY` makes no guarantee about the ordering of the result, and moreover the result ordering can vary when the same query is repeated.

Even in a query like `SELECT * FROM (SELECT .. FROM .. ORDER BY ..)`, the "inner" `ORDER BY` does not guarantee anything; the outer query must have an `ORDER BY` if a certain order is required. This is consistent with the SQL standard.

In the non-distsql implementation, there are some extra ordering guarantees based on which existing users may have made some assumptions. With distsql there are no guarantees other than what the `ORDER BY` clause imposes.

Note though that for things like `GROUP BY` even the non-distsql implementation outputs results in arbitrary, varying order.

**Comment by knz** [comment]
(nit: usually we create doc issues in the docs repo :)

**Comment by RaduBerinde** [comment]
Ah oops, filed https://github.com/cockroachdb/docs/issues/1110 and closing this.
