### ISSUE TITLE
rpc: 99th percentile round-trip latency numbers seem too high

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#13722]
We recently added a metric tracking the round-trip latency of the heartbeat pings we send on all our inter-node connections (#13533). While the 50th percentile measurements look reasonable (a few milliseconds), the 99th percentile readings on all of our prod clusters are pretty concerning.

Our clusters on Azure have a 99th percentile of around 50-100ms:

<img width="932" alt="screen shot 2017-02-22 at 4 23 36 pm" src="https://cloud.githubusercontent.com/assets/7085343/23233477/f6864698-f91c-11e6-9dfd-21f8726ddf08.png">

And our cluster on GCE has a 99th percentile around 20-40ms:

<img width="930" alt="screen shot 2017-02-22 at 4 29 23 pm" src="https://cloud.githubusercontent.com/assets/7085343/23233509/0cc5d982-f91d-11e6-9179-e51bd55ab4fb.png">

We should figure out what the cause of this is, since those are very bad numbers for requests that don't require doing any work or traversing any datacenter boundaries.

**Comment by a-robinson** [comment]
It's not likely to be a virtualization/environmental issue - I just ran 700 iterations of ping and never saw any latency higher than 5.3ms.

**Comment by tamird** [comment]
Just to play devil's advocate real quick - we are not measuring these using a monotonic clock, are we?

**Comment by a-robinson** [comment]
Indeed we're not, just a standard clock. It's a good point that we should switch, although I can't imagine that would account for such a consistently high measurement. I'd think that would only cause spikes.

**Comment by bdarnell** [comment]
GRPC heartbeats are more than a simple network round trip. Everything is multiplexed onto a single HTTP/2 connection, so there's locking and queuing at that layer. If a snapshot is being sent the heartbeat may have to wait for that data to be written (looks like grpc writes in 16KiB frames), and for flow control at both the TCP and HTTP/2 levels.

**Comment by a-robinson** [comment]
Thanks for the insight, @bdarnell. Do you think it's worth investigating further? I was going to add a bit of tracing to the heartbeat code so we could get more detail than a single span for the entire heartbeat in lightstep, but that won't give us much more detail other than a very vague idea of where the request is getting delayed.

**Comment by petermattis** [comment]
Good point about everything being multiplexed on a single HTTP/2 connection, though I doubt we're sending so many snapshots on all these clusters.

Probably should kill the load on one of the clusters and check to see if the latencies drop to more reasonable values.

Also, 5ms ping times seem high for within a datacenter.

**Comment by a-robinson** [comment]
The average was in the 1.5-2ms range, with just a couple outliers. I think that's about all you can expect when running on cloud VMs - you're going to have worse tail performance.

**Comment by a-robinson** [comment]
Things certainly get better with traffic disabled, although still a little on the high end:

<img width="931" alt="screen shot 2017-02-22 at 6 07 07 pm" src="https://cloud.githubusercontent.com/assets/7085343/23237078/d07c967a-f929-11e6-99ed-dd9b9c1577de.png">

In case it's a little tough to tell, they've dropped down to about 15-30ms at p99. Absolutely all variability left the p50 measurement once the load generators were disabled, settling down to right around what my pings were showing (~1.8ms):

<img width="927" alt="screen shot 2017-02-22 at 6 09 28 pm" src="https://cloud.githubusercontent.com/assets/7085343/23237160/229d3b62-f92a-11e6-9088-c3d411aa1e55.png">

**Comment by a-robinson** [comment]
And since @mberhault kindly pointed out that I hadn't removed all the work, the 99th percentile latency has indeed dropped all the way down to the 3-6ms range that I was seeing in ping:

<img width="921" alt="screen shot 2017-02-22 at 6 24 29 pm" src="https://cloud.githubusercontent.com/assets/7085343/23237618/2ef07198-f92c-11e6-976b-dcbf70a552df.png">

Thus, it is indeed the connection getting legitimately clogged up. This may be something that needs fixing, but it is a factor of the load on the system.

**Comment by petermattis** [comment]
Those latencies still see high to me. Checking on `cobalt` just now, I'm seeing avg ping times of ~600us when using the internal IP addresses and 1.8ms when using the DNS names. Omega (GCE) is showing avg ping times of ~300us. Those numbers are more in line with my expectations.

**Comment by a-robinson** [comment]
Ah, brilliant, Azure's external IP routing is super slow. I'm seeing the same numbers. We may want to modify our supervisor configs to bind to / advertise external IPs rather than hostnames since that's a pretty major difference.

I'm also a bit surprised just how costly GCE's external IP virtualization is -- I see around 280us for external vs 140us for internal. I thought it was better than that.

**Comment by petermattis** [comment]
> We may want to modify our supervisor configs to bind to / advertise external IPs rather than hostnames since that's a pretty major difference.

Bind to internal IPs, right? 

Cc @mberhault

**Comment by mberhault** [comment]
DNS names don't matter, it's the IP addresses they map to. We recently moved a few supervisor configs to use the external DNS names. We should stop doing that. The internal dns names (eg: `cockroach-violet-0001`) will be just fine. `indigo` is the only exception since the nodes are not in the same virtual private network.

There seems to be a massive discrepancy between cluster (different zones, slightly different machine type):
violet: centralus, D3v2: 350us internal / 590us external
```
cockroach@cockroach-violet-0001:~$ ping -i 0.2 -q -c 50 cockroach-violet-0002
PING cockroach-violet-0002.trlnlrou2h1etawy34fljx303d.gx.internal.cloudapp.net (192.168.1.5) 56(84) bytes of data.
50 packets transmitted, 50 received, 0% packet loss, time 9809ms
rtt min/avg/max/mdev = 0.206/0.353/0.872/0.119 ms

cockroach@cockroach-violet-0001:~$ ping -i 0.2 -q -c 50 cockroach-violet-0002.crdb.io
PING cockroach-violet-0002.crdb.io (40.69.150.212) 56(84) bytes of data.
50 packets transmitted, 50 received, 0% packet loss, time 9804ms
rtt min/avg/max/mdev = 0.387/0.589/1.986/0.219 ms
```

cobalt: eastus, D3: 700us internal / 1400us external
```
cockroach@cockroach-cobalt-01:~$ ping -i 0.2 -q -c 50 cockroach-cobalt-02
PING cockroach-cobalt-02.hpuurpc1pare3bbkgbzmmhanoe.bx.internal.cloudapp.net (192.168.1.5) 56(84) bytes of data.
50 packets transmitted, 50 received, 0% packet loss, time 9810ms
rtt min/avg/max/mdev = 0.405/0.702/2.431/0.345 ms

cockroach@cockroach-cobalt-01:~$ ping -i 0.2 -q -c 50 cockroach-cobalt-0002.crdb.io
PING cockroach-cobalt-0002.crdb.io (40.117.102.161) 56(84) bytes of data.
50 packets transmitted, 50 received, 0% packet loss, time 9833ms
rtt min/avg/max/mdev = 1.154/1.410/3.498/0.326 ms
```

omega: 190us internal / 420us external
```
cockroach@cockroach-omega-0001:~$ ping -i 0.2 -q -c 50 cockroach-omega-0002
PING cockroach-omega-0002.c.cockroach-shared.internal (10.142.0.4) 56(84) bytes of data.
ics ---
50 packets transmitted, 50 received, 0% packet loss, time 9805ms
rtt min/avg/max/mdev = 0.116/0.192/0.840/0.153 ms

cockroach@cockroach-omega-0001:~$ ping -i 0.2 -q -c 50 cockroach-omega-0002.crdb.io
PING cockroach-omega-0002.crdb.io (104.196.180.58) 56(84) bytes of data.
50 packets transmitted, 50 received, 0% packet loss, time 9804ms
rtt min/avg/max/mdev = 0.227/0.417/2.835/0.397 ms
```

The difference between `omega` and `violet` could be explained by the fact that the host OS on Azure is still Windows, and it's historically had a crappy networking stack. No idea what could cause the cobalt numbers though, I'll run basic pings on everything I can find, then try to dig further.

**Comment by mberhault** [comment]
Except ultimately, the `--join` flag doesn't matter, it's the `--advertize-host` that does, and the only place we're specifying it is `indigo`. All others just end up using their local hostname, which resolves to the internal IP for nodes on the same network.

So the only cluster using external IPs for internal communication is `indigo`, and I don't think there's much we can do about that, unless we introduce a mechanism allowing a different advertize-host for nodes in the same network vs those outside it.

**Comment by a-robinson** [comment]
Yeah, sorry, I can't type. I meant that we should use "internal rather than external", not "external rather than hostname".

Although I was also not paying close enough attention and thought that cobalt advertising itself as `cockroach-cobalt-01` was bad, even though that's just the internally-scoped hostname, not the external hostname, so it is fine.

That means the 1.8ms 50th percentile and 3-6ms 99th percentile for the heartbeat RPCs are still pretty bad.

**Comment by petermattis** [comment]
Seems like there is still something funky here. Hard to believe that gRPC round-trip time on an idle cluster is 150% slower than ping time. And given the timings, I'm suspicious that somehow we're using the external IPs even though it appears we aren't.

**Comment by petermattis** [comment]
I wrote a simple gRPC service which shows 1-1.5ms RTTs on cobalt, while ping is showing 600ms RTTs. Next step would be to try something even simpler that just uses sockets.

**Comment by a-robinson** [comment]
This is still pretty abysmal, even after a build including #14939 was pushed. Our end user tail latency is bound to be terrible if our heartbeat tail latency is terrible. Picking this back up again.

**Comment by a-robinson** [comment]
After some investigation today, I think we might have to table this until after 1.0.

I first tried putting the heartbeat pings onto their own connections, separated from all our other grpc traffic, but that had a negligible effect on latency at the 50th, 95th, and 99th percentiles.

With the heartbeats still on their own connections, I then added basic tracing so that we could tell how much of the request time gets spent getting the request from the client to the server and how much gets spent getting it from the server back to the client. There was no consistent pattern, meaning that there probably isn't a single bottleneck delaying the requests.

It also doesn't look like grpc is blocking on sends, judging by some simple timing logic added into the client path. It looked like data was flushed out to the `net.Conn` synchronously within the sending logic I instrumented, but it's possible I made a mistake when spelunking the code.

For the sake of reproduction and making sure I'm not doing things totally wrong, I was running on cobalt with the cockroachdb diff in https://github.com/a-robinson/cockroach/commit/0b14f7cb2c1b65a012a9772a4691cee7a567be3a and the grpc logging diff in https://gist.github.com/a-robinson/0673ed8f7cf5c5e4feea69ceb195c41c, and some example lightstep traces from the instrumented heartbeat pings are below. `servePing` is when the request reached our server code for the `Ping` rpc method.

<img width="1162" alt="screen shot 2017-04-18 at 4 51 34 pm" src="https://cloud.githubusercontent.com/assets/7085343/25153112/630da416-2459-11e7-94c3-3fc962ae4d5b.png">
<img width="1149" alt="screen shot 2017-04-18 at 4 51 38 pm" src="https://cloud.githubusercontent.com/assets/7085343/25153115/630ed200-2459-11e7-8258-6ffcc03dd7f9.png">
<img width="1150" alt="screen shot 2017-04-18 at 4 51 44 pm" src="https://cloud.githubusercontent.com/assets/7085343/25153111/630b132c-2459-11e7-8ac3-44aabb838503.png">
<img width="1162" alt="screen shot 2017-04-18 at 4 51 49 pm" src="https://cloud.githubusercontent.com/assets/7085343/25153113/630de232-2459-11e7-9eae-f1a9db648387.png">
<img width="1158" alt="screen shot 2017-04-18 at 4 51 53 pm" src="https://cloud.githubusercontent.com/assets/7085343/25153114/630e5f6e-2459-11e7-875b-7e83de143aa7.png">

**Comment by a-robinson** [comment]
So I'm going to move this out of 1.0 since I think too much time and too big of a change may be needed to improve things, but I'll take another look at it if we magically finish up all our other 1.0 work early.

**Comment by a-robinson** [comment]
It's also worth noting that it doesn't appear to just be one or two nodes dragging things down. These are the exponentially-weighted moving average latencies between nodes on cobalt:

```
cockroach-cobalt-01:
I170418 21:35:58.982212 191 rpc/clock_offset.go:165  [n1] Latency[cockroach-cobalt-01:26257]=11.984895ms
I170418 21:35:59.882250 426 rpc/clock_offset.go:165  [n1] Latency[cockroach-cobalt-05:26257]=8.325804ms
I170418 21:35:59.901422 62 rpc/clock_offset.go:165  [n1] Latency[cockroach-cobalt-06:26257]=9.499359ms
I170418 21:36:00.188822 886 rpc/clock_offset.go:165  [n1] Latency[cockroach-cobalt-04:26257]=9.720632ms
I170418 21:36:00.199401 387 rpc/clock_offset.go:165  [n1] Latency[cockroach-cobalt-02:26257]=14.02666ms
I170418 21:36:00.512876 583 rpc/clock_offset.go:165  [n1] Latency[cockroach-cobalt-03:26257]=14.454181ms

cockroach-cobalt-02:
I170418 21:35:58.859672 953 rpc/clock_offset.go:165  [n2] Latency[cockroach-cobalt-06:26257]=8.457781ms
I170418 21:35:59.883196 45 rpc/clock_offset.go:165  [n2] Latency[192.168.1.4:26257]=15.216819ms
I170418 21:35:59.886607 89 rpc/clock_offset.go:165  [n2] Latency[cockroach-cobalt-02:26257]=9.728978ms
I170418 21:36:00.576489 209 rpc/clock_offset.go:165  [n2] Latency[cockroach-cobalt-01:26257]=13.264136ms
I170418 21:36:00.794901 204 rpc/clock_offset.go:165  [n2] Latency[cockroach-cobalt-05:26257]=9.133166ms
I170418 21:36:01.282501 778 rpc/clock_offset.go:165  [n2] Latency[cockroach-cobalt-03:26257]=9.440866ms

cockroach-cobalt-03:
I170418 21:35:59.777241 43 rpc/clock_offset.go:165  [n3] Latency[192.168.1.4:26257]=13.976382ms
I170418 21:35:59.832419 293 rpc/clock_offset.go:165  [n3] Latency[cockroach-cobalt-01:26257]=6.652615ms
I170418 21:35:59.879014 121 rpc/clock_offset.go:165  [n3] Latency[cockroach-cobalt-02:26257]=19.836078ms
I170418 21:36:00.336743 240 rpc/clock_offset.go:165  [n3] Latency[cockroach-cobalt-05:26257]=8.718053ms
I170418 21:36:01.044516 158 rpc/clock_offset.go:165  [n3] Latency[cockroach-cobalt-06:26257]=8.611629ms
I170418 21:36:01.193219 736 rpc/clock_offset.go:165  [n3] Latency[cockroach-cobalt-04:26257]=17.462531ms

cockroach-cobalt-04:
I170418 21:35:59.398161 362 rpc/clock_offset.go:165  [n4] Latency[cockroach-cobalt-01:26257]=7.518732ms
I170418 21:36:00.257268 530 rpc/clock_offset.go:165  [n4] Latency[cockroach-cobalt-06:26257]=11.394542ms
I170418 21:36:00.282059 367 rpc/clock_offset.go:165  [n4] Latency[cockroach-cobalt-05:26257]=10.859868ms
I170418 21:36:01.474698 74 rpc/clock_offset.go:165  [n4] Latency[cockroach-cobalt-02:26257]=9.669181ms
I170418 21:36:02.026248 57 rpc/clock_offset.go:165  [n4] Latency[192.168.1.4:26257]=18.65271ms
I170418 21:36:02.028063 270 rpc/clock_offset.go:165  [n4] Latency[cockroach-cobalt-04:26257]=6.795953ms

cockroach-cobalt-05:
I170418 21:36:00.220024 124 rpc/clock_offset.go:165  [n5] Latency[cockroach-cobalt-04:26257]=20.155424ms
I170418 21:36:00.255837 291 rpc/clock_offset.go:165  [n5] Latency[cockroach-cobalt-01:26257]=10.3495ms
I170418 21:36:00.335461 1031 rpc/clock_offset.go:165  [n5] Latency[cockroach-cobalt-03:26257]=12.955542ms
I170418 21:36:02.451674 44 rpc/clock_offset.go:165  [n5] Latency[192.168.1.4:26257]=8.171377ms
I170418 21:36:02.485470 233 rpc/clock_offset.go:165  [n5] Latency[cockroach-cobalt-05:26257]=9.455923ms
I170418 21:36:02.524240 57 rpc/clock_offset.go:165  [n5] Latency[cockroach-cobalt-02:26257]=12.246806ms

cockroach-cobalt-06:
I170418 21:36:01.035860 817 rpc/clock_offset.go:165  [n6] Latency[cockroach-cobalt-03:26257]=15.388843ms
I170418 21:36:02.217820 125 rpc/clock_offset.go:165  [n6] Latency[cockroach-cobalt-02:26257]=13.106981ms
I170418 21:36:02.438960 350 rpc/clock_offset.go:165  [n6] Latency[cockroach-cobalt-06:26257]=9.834029ms
I170418 21:36:02.484349 58 rpc/clock_offset.go:165  [n6] Latency[192.168.1.4:26257]=10.025955ms
I170418 21:36:02.719054 200 rpc/clock_offset.go:165  [n6] Latency[cockroach-cobalt-04:26257]=12.380071ms
I170418 21:36:03.118946 354 rpc/clock_offset.go:165  [n6] Latency[cockroach-cobalt-05:26257]=11.457138ms
```

**Comment by petermattis** [comment]
One point I'll add to this: at some point I wrote a simple "ping" test program that used gRPC. Running that program alongside `cockroach` on one of our test clusters with high latencies showed very reasonable latencies. My takeaway was that the there is something going on inside our process.

**Comment by bdarnell** [comment]
In the meeting this morning I suggested that setting `TCP_NODELAY` could perhaps be a quick fix, but Go's `net` package turns on `TCP_NODELAY` by default. I'm still suspicious of TCP-level oddities because of the way that we send our raft messages as one-way streams on two separate TCP connections, but I don't have any more concrete ideas at the moment so investigating more post-1.0 sounds like a good idea.

**Comment by bdarnell** [comment]
This could just be the GC assist issue (#17243)

**Comment by tschottdorf** [comment]
Going to unassign for now. Probably worth taking a look @petermattis evaluates cRPC/gRPC.

**Comment by bdarnell** [comment]
For the record, it's not GC assist as I suggested in my previous comment. 

GRPC 1.8 (we're on 1.7 now; 1.9 was just released a few days ago) includes grpc/grpc-go#1636, which might help. On the `pinger` benchmark it showed a major improvement in median latency, but no change in p95 or p99. Upgrading grpc to 1.8 or 1.9 is probably the only change we can make here for 2.0.

**Comment by petermattis** [comment]
Let's do the grpc bump soon to work out any issues that arise from it. @bdarnell Are you going to do that?

**Comment by bdarnell** [comment]
Yeah, I can do a grpc bump tomorrow. I'll try the latest 1.9.1 release; if we have trouble we have the option of falling back to 1.8.5.

**Comment by bdarnell** [comment]
When GRPC 1.9.1 was deployed to cyan, it made no discernible difference to any of the metrics. Bumping this to 2.1 and unassigning myself since I don't think there's going to be anything else we can do here before 2.0.

**Comment by petermattis** [comment]
gRPC has made various improvements. We should re-evaluate this issue early in the 2.2 cycle.

**Comment by lunevalex** [comment]
CRDB is now on grpc 1.29, closing this for lack of relevance.
