### ISSUE TITLE
sql: selecting from an zero-column table is broken

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#13725]
I'm not sure there's a valid use case for this, but attempting to select from a zero-column table in the SQL CLI fails in a strange way:

```sql
> CREATE TABLE t ();
CREATE TABLE

> SELECT * FROM d.t10;
pq: unknown response for simple query: 'n'
```

Meanwhile in Postgres:

```sql
> CREATE TABLE t ();
CREATE TABLE

> SELECT * FROM t;
--
(0 rows)

> INSERT INTO t DEFAULT VALUES;
INSERT 0 1

> SELECT * FROM t;
--
(1 row)
```

**Comment by jordanlewis** [comment]
Nice catch - seems like a bug in our pgwire implementation: https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/pgwire/v3.go#L1005

Seems like this special case is incorrect, and really we're not supposed to send "no data" if our result has no columns.

**Comment by jordanlewis** [comment]
Hmm looks like @knz added this behavior recently, maybe he can clarify why it was added.

**Comment by knz** [comment]
This was #4548, so not exactly "Recently".

The original problem (#4538) is that JDBC was confused by a response of `RowDescription` as a result of a DDL statement (CREATE etc.). I thought in #4548 that the way to detect non-query statements was to test the number of columns, because *back then* we couldn't yet create a table with zero columns. Obviously that condition was wrong.

**Comment by jordanlewis** [comment]
The problem is actually not the resultant `RowDescription` from a DDL - it's the resultant `RowDescription` response from a client `describe` message on a prepared statement that happens to be a DDL.

I'm preparing a fix.

**Comment by mjibson** [comment]
After in person discussion with Jordan, I'm not convinced this was the correct fix. I think The NoData message is referring to INSERT and other queries that don't ever return rows. We are going to add C and Java tests, and I'm going to investigate with a postgres server to figure out when they use that message. Reopening until this is resolved.
