### ISSUE TITLE
sql: Transaction metrics go up when external traffic stops

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#13728]
I turned off all `block_writer` load to cobalt to see how it would affect #13722, and noticed this weird quirk in the SQL metrics.

As load on the system dropped to be negligible, with the only writes being to system tables:

<img width="923" alt="screen shot 2017-02-22 at 6 03 13 pm" src="https://cloud.githubusercontent.com/assets/7085343/23236973/5e1a3efc-f929-11e6-8fc2-75a28e93d9af.png">

The "Transactions" metrics (`sql_txn_begin_count`, `sql_txn_commit_count`, and `sql_txn_rollback_count`) actually went way up:

<img width="924" alt="screen shot 2017-02-22 at 6 03 23 pm" src="https://cloud.githubusercontent.com/assets/7085343/23237000/72eba7f8-f929-11e6-8be0-c9f6e9e528a3.png">

This doesn't seem expected, but maybe I just don't understand them? @arjunravinarayan @mberhault

**Comment by mberhault** [comment]
`cobalt` has `photos` running against it.
As the write load from `block_writer` goes down, I would expect more resources available for `photos` ops.

**Comment by a-robinson** [comment]
<insert shame cube here>

You're right, thanks.
