### ISSUE TITLE
sql: Latency metric not populated

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#13720]
Sorry if this is a known issue, but I was looking through our various latency metrics and noticed that the `sql.latency` metric never actually gets populated anywhere. Is that intentional, @mrtracy, or just an oversight?

**Comment by a-robinson** [comment]
https://sourcegraph.com/github.com/cockroachdb/cockroach@73136b975416d3609a41985adc66aa9db190d6e6/-/blob/pkg/sql/executor.go#L214:2-214:9

**Comment by mrtracy** [comment]
Certainly an oversight, it should be removed. @arjunravinarayan, can you confirm that the information in this metric was divided between "DistSQLExecLatency" and "SQLExecLatency"?

**Comment by arjunravinarayan** [comment]
That sounds right to me. Note there's also `server/node.go:nodeMetrics.Latency` as well, which measures end-to-end latency (as opposed to execution latency)
