### ISSUE TITLE
tracing: FormatRawSpans should reset `last`

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#13732]
`tracing.FormatRawSpans` prints two nearly identical columns of times. It looks like the second column is meant to be the delta from the previous row, but because `last` is set once before the first iteration and never reset, it's just showing the time since the first event. It looks like `last` is meant to be updated every time through the loop.

**Comment by dianasaur323** [comment]
assigning to @petermattis for reassignment.
