### ISSUE TITLE
pebble: v24.3.0: nil pointer in singleLevelIterator

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#137473]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/6140129460/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/6140129460/?referrer=webhooks_plugin)

Panic Message:

```
conn_executor.go:961: runtime error: invalid memory address or nil pointer dereference
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
  | 	pkg/sql/conn_executor.go:961
  | [...repeated from below...]
Wraps: (2) while executing: UPDATE _ AS _ SET _ = _._, _ = _._, _ = _._ FROM (VALUES ('_', '_', __more1_10__), (__more10_100__)) AS _ (_, _, _, _) WHERE _._ = _._
Wraps: (3) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
  | 	pkg/sql/conn_executor.go:961
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:770
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
  | 	pkg/sql/colexecerror/error.go:122
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:770
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
  | 	pkg/sql/colexecerror/error.go:122
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:770
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
  | 	pkg/sql/colexecerror/error.go:122
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:770
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1
  | 	pkg/sql/colexecerror/error.go:122
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:770
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).recover
  | 	pkg/util/stop/stopper.go:226
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:770
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).SendWithWriteBytes.func1
  | 	pkg/kv/kvserver/store_send.go:104
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:770
  | runtime.panicmem
  | 	GOROOT/src/runtime/panic.go:261
  | runtime.sigpanic
  | 	GOROOT/src/runtime/signal_windows.go:401
  | github.com/cockroachdb/pebble/sstable.(*singleLevelIterator[...]).closeInternal
  | 	external/com_github_cockroachdb_pebble/sstable/reader_iter_single_lvl.go:1592
  | github.com/cockroachdb/pebble/sstable.(*singleLevelIterator[...]).Close
  | 	external/com_github_cockroachdb_pebble/sstable/reader_iter_single_lvl.go:1571
  | github.com/cockroachdb/pebble.(*levelIter).Close
  | 	external/com_github_cockroachdb_pebble/level_iter.go:917
  | github.com/cockroachdb/pebble.(*mergingIter).Close
  | 	external/com_github_cockroachdb_pebble/merging_iter.go:1307
  | github.com/cockroachdb/pebble.(*lazyCombinedIter).Close
  | 	external/com_github_cockroachdb_pebble/range_keys.go:703
  | github.com/cockroachdb/pebble.(*Iterator).Close
  | 	external/com_github_cockroachdb_pebble/iterator.go:2345
  | github.com/cockroachdb/cockroach/pkg/storage.(*pebbleIterator).destroy
  | 	pkg/storage/pebble_iterator.go:1014
  | github.com/cockroachdb/cockroach/pkg/storage.(*pebbleReadOnly).Close
  | 	pkg/storage/pebble.go:2819
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:770
  | runtime.panicmem
  | 	GOROOT/src/runtime/panic.go:261
  | runtime.sigpanic
  | 	GOROOT/src/runtime/signal_windows.go:401
  | github.com/cockroachdb/pebble/sstable.(*singleLevelIterator[...]).closeInternal
  | 	external/com_github_cockroachdb_pebble/sstable/reader_iter_single_lvl.go:1592
  | github.com/cockroachdb/pebble/sstable.(*singleLevelIterator[...]).Close
  | 	external/com_github_cockroachdb_pebble/sstable/reader_iter_single_lvl.go:1571
  | github.com/cockroachdb/pebble.(*levelIter).Close
  | 	external/com_github_cockroachdb_pebble/level_iter.go:917
  | github.com/cockroachdb/pebble.(*levelIter).loadFile
  | 	external/com_github_cockroachdb_pebble/level_iter.go:522
  | github.com/cockroachdb/pebble.(*levelIter).skipEmptyFileForward
  | 	external/com_github_cockroachdb_pebble/level_iter.go:862
Wraps: (4) runtime error: invalid memory address or nil pointer dereference
Error types: (1) *withstack.withStack (2) *safedetails.withSafeDetails (3) *withstack.withStack (4) runtime.errorString
-- report composition:
runtime.errorString
conn_executor.go:961: *withstack.withStack (top exception)
*safedetails.withSafeDetails: while executing: UPDATE _ AS _ SET _ = _._, _ = _._, _ = _._ FROM (VALUES ('_', '_', __more1_10__), (__more10_100__)) AS _ (_, _, _, _) WHERE _._ = _._
conn_executor.go:961: *withstack.withStack (1)
(check the extra data payloads)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[external/com_github_cockroachdb_pebble/level_iter.go#L861-L863](external/com_github_cockroachdb_pebble/level_iter.go#L861-L863)
[external/com_github_cockroachdb_pebble/level_iter.go#L521-L523](external/com_github_cockroachdb_pebble/level_iter.go#L521-L523)
[external/com_github_cockroachdb_pebble/level_iter.go#L916-L918](external/com_github_cockroachdb_pebble/level_iter.go#L916-L918)
[external/com_github_cockroachdb_pebble/sstable/reader_iter_single_lvl.go#L1570-L1572](external/com_github_cockroachdb_pebble/sstable/reader_iter_single_lvl.go#L1570-L1572)
[external/com_github_cockroachdb_pebble/sstable/reader_iter_single_lvl.go#L1591-L1593](external/com_github_cockroachdb_pebble/sstable/reader_iter_single_lvl.go#L1591-L1593)
[GOROOT/src/runtime/signal_windows.go#L400-L402](GOROOT/src/runtime/signal_windows.go#L400-L402)
[GOROOT/src/runtime/panic.go#L260-L262](GOROOT/src/runtime/panic.go#L260-L262)
[GOROOT/src/runtime/panic.go#L769-L771](GOROOT/src/runtime/panic.go#L769-L771)
[pkg/storage/pebble.go#L2818-L2820](pkg/storage/pebble.go#L2818-L2820)
[pkg/storage/pebble_iterator.go#L1013-L1015](pkg/storage/pebble_iterator.go#L1013-L1015)
[external/com_github_cockroachdb_pebble/iterator.go#L2344-L2346](external/com_github_cockroachdb_pebble/iterator.go#L2344-L2346)
[external/com_github_cockroachdb_pebble/range_keys.go#L702-L704](external/com_github_cockroachdb_pebble/range_keys.go#L702-L704)
[external/com_github_cockroachdb_pebble/merging_iter.go#L1306-L1308](external/com_github_cockroachdb_pebble/merging_iter.go#L1306-L1308)
[external/com_github_cockroachdb_pebble/level_iter.go#L916-L918](external/com_github_cockroachdb_pebble/level_iter.go#L916-L918)
[external/com_github_cockroachdb_pebble/sstable/reader_iter_single_lvl.go#L1570-L1572](external/com_github_cockroachdb_pebble/sstable/reader_iter_single_lvl.go#L1570-L1572)
[external/com_github_cockroachdb_pebble/sstable/reader_iter_single_lvl.go#L1591-L1593](external/com_github_cockroachdb_pebble/sstable/reader_iter_single_lvl.go#L1591-L1593)
[GOROOT/src/runtime/signal_windows.go#L400-L402](GOROOT/src/runtime/signal_windows.go#L400-L402)
[GOROOT/src/runtime/panic.go#L260-L262](GOROOT/src/runtime/panic.go#L260-L262)
[GOROOT/src/runtime/panic.go#L769-L771](GOROOT/src/runtime/panic.go#L769-L771)
[pkg/kv/kvserver/store_send.go#L103-L105](pkg/kv/kvserver/store_send.go#L103-L105)
[GOROOT/src/runtime/panic.go#L769-L771](GOROOT/src/runtime/panic.go#L769-L771)
[pkg/util/stop/stopper.go#L225-L227](pkg/util/stop/stopper.go#L225-L227)
[GOROOT/src/runtime/panic.go#L769-L771](GOROOT/src/runtime/panic.go#L769-L771)
[pkg/sql/colexecerror/error.go#L121-L123](pkg/sql/colexecerror/error.go#L121-L123)
[GOROOT/src/runtime/panic.go#L769-L771](GOROOT/src/runtime/panic.go#L769-L771)
[pkg/sql/colexecerror/error.go#L121-L123](pkg/sql/colexecerror/error.go#L121-L123)
[GOROOT/src/runtime/panic.go#L769-L771](GOROOT/src/runtime/panic.go#L769-L771)
[pkg/sql/colexecerror/error.go#L121-L123](pkg/sql/colexecerror/error.go#L121-L123)
[GOROOT/src/runtime/panic.go#L769-L771](GOROOT/src/runtime/panic.go#L769-L771)
[pkg/sql/colexecerror/error.go#L121-L123](pkg/sql/colexecerror/error.go#L121-L123)
[GOROOT/src/runtime/panic.go#L769-L771](GOROOT/src/runtime/panic.go#L769-L771)
[pkg/sql/conn_executor.go#L960-L962](pkg/sql/conn_executor.go#L960-L962)
</details>

```
external/com_github_cockroachdb_pebble/level_iter.go in github.com/cockroachdb/pebble.(*levelIter).skipEmptyFileForward at line 862
external/com_github_cockroachdb_pebble/level_iter.go in github.com/cockroachdb/pebble.(*levelIter).loadFile at line 522
external/com_github_cockroachdb_pebble/level_iter.go in github.com/cockroachdb/pebble.(*levelIter).Close at line 917
external/com_github_cockroachdb_pebble/sstable/reader_iter_single_lvl.go in github.com/cockroachdb/pebble/sstable.(*singleLevelIterator[...]).Close at line 1571
external/com_github_cockroachdb_pebble/sstable/reader_iter_single_lvl.go in github.com/cockroachdb/pebble/sstable.(*singleLevelIterator[...]).closeInternal at line 1592
GOROOT/src/runtime/signal_windows.go in runtime.sigpanic at line 401
GOROOT/src/runtime/panic.go in runtime.panicmem at line 261
GOROOT/src/runtime/panic.go in runtime.gopanic at line 770
pkg/storage/pebble.go in pkg/storage.(*pebbleReadOnly).Close at line 2819
pkg/storage/pebble_iterator.go in pkg/storage.(*pebbleIterator).destroy at line 1014
external/com_github_cockroachdb_pebble/iterator.go in github.com/cockroachdb/pebble.(*Iterator).Close at line 2345
external/com_github_cockroachdb_pebble/range_keys.go in github.com/cockroachdb/pebble.(*lazyCombinedIter).Close at line 703
external/com_github_cockroachdb_pebble/merging_iter.go in github.com/cockroachdb/pebble.(*mergingIter).Close at line 1307
external/com_github_cockroachdb_pebble/level_iter.go in github.com/cockroachdb/pebble.(*levelIter).Close at line 917
external/com_github_cockroachdb_pebble/sstable/reader_iter_single_lvl.go in github.com/cockroachdb/pebble/sstable.(*singleLevelIterator[...]).Close at line 1571
external/com_github_cockroachdb_pebble/sstable/reader_iter_single_lvl.go in github.com/cockroachdb/pebble/sstable.(*singleLevelIterator[...]).closeInternal at line 1592
GOROOT/src/runtime/signal_windows.go in runtime.sigpanic at line 401
GOROOT/src/runtime/panic.go in runtime.panicmem at line 261
GOROOT/src/runtime/panic.go in runtime.gopanic at line 770
pkg/kv/kvserver/store_send.go in pkg/kv/kvserver.(*Store).SendWithWriteBytes.func1 at line 104
GOROOT/src/runtime/panic.go in runtime.gopanic at line 770
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).recover at line 226
GOROOT/src/runtime/panic.go in runtime.gopanic at line 770
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1 at line 122
GOROOT/src/runtime/panic.go in runtime.gopanic at line 770
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1 at line 122
GOROOT/src/runtime/panic.go in runtime.gopanic at line 770
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1 at line 122
GOROOT/src/runtime/panic.go in runtime.gopanic at line 770
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError.func1 at line 122
GOROOT/src/runtime/panic.go in runtime.gopanic at line 770
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn.func1 at line 961
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v24.3.0 |
| Go Version | go1.22.8 X:nocoverageredesign |
| Platform | windows amd64 |
| Distribution | CCL |
| Cockroach Release | v24.3.0 |
| Cockroach SHA | ef2ebe96f3a26fd6d6716e2ec4a0c8c6fe0fb567 |
| # of CPUs | 32 |
| # of Goroutines | 813 |

Jira issue: CRDB-45592

**Comment by yuzefovich** [comment]
Hm, same cluster as #137470. Maybe storage folks will see a problem simply based on the stack trace.

**Comment by yuzefovich** [comment]
I'll close this as a dup of #137474
