### ISSUE TITLE
Create peer nodeID, storeID & raftID for context

### ISSUE THREAD

**Issue by spencerkimball** [cockroachdb/cockroach#1374]
These will need to be part of the incoming proto.RequestHeader and get set in the context.Context when a request is received. I think they'll make debugging via log files a lot simpler

**Comment by petermattis** [comment]
@bdarnell I'm guessing this issue is long out of date.

**Comment by bdarnell** [comment]
Yeah, I'm pretty sure all of this is in our structured logs.
