### ISSUE TITLE
sql: benchmarks failed with ambiguous result errors

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#13746]
https://teamcity.cockroachdb.com/viewLog.html?buildId=158952&tab=buildResultsDiv&buildTypeId=Cockroach_BenchmarkTests

```
--- FAIL: BenchmarkSort100000Limit10Multinode_Cockroach
	bench_test.go:1014: pq: result is ambiguous (error=key range /Table/51/1/0/0-/Table/51/1/99999/0/NULL outside of bounds of range /Table/50-/Table/51, pending RPCs=1)
--- FAIL: BenchmarkSort100000Limit10DistinctMultinode_Cockroach
	bench_test.go:1014: pq: result is ambiguous (error=key range /Table/51/1/0/0-/Table/51/1/99999/0/NULL outside of bounds of range /Table/50-/Table/51, pending RPCs=1)
```

I'm confused. Why is a "range out of bounds" turning into an ambiguous result?

**Comment by bdarnell** [comment]
`AmbiguousResultError` always implies at least two attempts, but it only returns the error from the last attempt. The first attempt must have returned some ambiguous error like an RPC timeout. But we probably should be retrying on "addressing" errors like RangeKeyMismatchError even if there is a prior ambiguous failure.

**Comment by jordanlewis** [comment]
Also discussed in #13220.

**Comment by spencerkimball** [comment]
I'll take a look at this. Some possible remedies come to mind for this and #13220. Does anyone have a solid means of repro'ing these failures?

**Comment by tamird** [comment]
I'd try `make bench ... TESTFLAGS='-count 300'`
