### ISSUE TITLE
Cluster setting sql.defaults.disallow_full_table_scans.enabled prevents index creation

### ISSUE THREAD

**Issue by smcvey** [cockroachdb/cockroach#137404]
**Describe the problem**

If full table scans are disabled, it prevents the creation of new indexes on tables.

**To Reproduce**

```
SET CLUSTER SETTING sql.defaults.disallow_full_table_scans.enabled = true;
CREATE TABLE t (id UUID PRIMARY KEY);
CREATE INDEX ON t (id);
```

This produces the error message:

```
ERROR: verify-idx-count: index "t_id_idx" cannot be used for this query
SQLSTATE: 42809
HINT: try overriding the `disallow_full_table_scans` or increasing the `large_full_scan_rows` cluster/session settings
```

Despite the hint, overriding either of these variables in the session has no effect.  The cluster setting needs overridden, which can't be done by an ordinary user.

**Expected behavior**
The setting is intended to prevent users/applications from accidentally running expensive full table scans. However, it should not prevent the creation of an index which requires, by definition, a full table scan.

**Environment:**
 - CockroachDB version: master

Jira issue: CRDB-45564

https://cockroachdb.zendesk.com/agent/tickets/24794

**Comment by rafiss** [comment]
Let's add an exception for `disallow_full_table_scans` similar to how we did for `statement_timeout` in 8f01b6389db17962c21a01d386b79715505ad64f. It's also a good time to check for any other timeouts or blocks that should not apply to background internal executor jobs.
