### ISSUE TITLE
server: debug range page needs to look better

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#13749]
<img width="955" alt="screen shot 2017-02-23 at 02 05 54" src="https://cloud.githubusercontent.com/assets/1614265/23267301/4d0ef4f6-f9b8-11e6-9e63-09644f6bdc44.png">

At least picking some nicer colours, but I'm sure much more can be done.

**Comment by kuanluo** [comment]
Based on the short conversation we had at your desk, I have two low-hanging fruit type of ideas:
1. Use time format (eg: 12:34:34PM) for Lease Start/Expiration would shrink the column width of each replica, and thus make the entire page more compact and readable.
2. Only highlight the mismatch of data. 

Here's what it could look like:
![image](https://cloud.githubusercontent.com/assets/1486483/23370955/6668639a-fce4-11e6-809a-273615ecb8bc.png)

@BramGruneir, I'd love your thoughts on implementing those and see what's next steps to work on.

**Comment by BramGruneir** [comment]
So we don't always know is what the correct value is.  2 might be correct and one incorrect, or vice versa, so I can bold the value that's different, but it's not always the one that's wrong.

The times are a problem, but I think we need the full value for them.  If you hover over any value with an ellipsis, it has the full text in the tooltips.

**Comment by kuanluo** [comment]
>  I can bold the value that's different, but it's not always the one that's wrong.

That sounds good for an immediate improvement. The yellow is just to call out the difference.

>The times are a problem, but I think we need the full value for them. If you hover over any value with an ellipsis, it has the full text in the tooltips.

Sounds good. However you think might help you debug. There's a lot of room for improvement on this, but we can start small and go from there. :)

**Comment by bdarnell** [comment]
In most cases treating the leader with the highest term as "correct" is a reasonable assumption.

When the times are different, they often differ by fractions of seconds so it wouldn't work to truncate them. But they're rarely different, so maybe we abbreviate them by default (and even when they are different, I've rarely found the timestamp to be useful information). 

A similar argument could be made for the key range - it rarely differs, but when it does you need to be able to see the whole thing.

**Comment by kuanluo** [comment]
A few additional notes on the mock:
1. I right-aligned the labels, so they're quicker for the eyes to scan.
2. The labels have a light background to differentiate from the rest. If we fancy, we can make the label column sticky. :) 
3. I took out the alternate white and gray background for each replica - they seem more distracting than helpful when the default value is 3.

**Comment by dianasaur323** [comment]
Since we are actually exposing some of the /debug pages when we discuss troubleshooting with users, I think we can slate some clean up to occur in the 1.1 timeframe. Moving.

**Comment by arjunravinarayan** [comment]
@BramGruneir can I close this issue, or change the milestone to Later? It seems most of the low hanging fruit has been picked here, and in any case, nothing further is being done in the 2.0 timeframe.

**Comment by arjunravinarayan** [comment]
Apologies for the autocmpleted mistag, I meant @kuanluo.

**Comment by kuanluo** [comment]
Yes @arjunravinarayan !
