### ISSUE TITLE
distsql: remove the hardcoded reference to raduberinde.github.io

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#13758]
The code in `sql/distsqlrun/flow_diagram.go` generates links hard coded to `raduberinde.github.io`. That's rather poor UX especially should that site become unavailable / repurposed.

**Comment by knz** [comment]
This is preliminary but linked to  #12651.

**Comment by RaduBerinde** [comment]
Yes, this is temporary - we want the URL to point to the cockroach server itself (though unfortunately that will make it less usable on GCE and similar).

**Comment by RaduBerinde** [comment]
We need to embed the files in https://github.com/RaduBerinde/raduberinde.github.io into the server and expose them. Ideally this would be integrated with some of our existing UI stuff (where I think we already have `d3` as a dependency), though for a first pass it's acceptable to just embed them as they are.

**Comment by cuongdo** [comment]
Fixed by #15162 and cockroachdb/cockroachdb.github.io#1
