### ISSUE TITLE
catalog: v23.1.12: building declarative schema change targets for EXPERIMENTAL CHANGEFEED: incorrect interface conversion

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#137516]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/6145566934/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/6145566934/?referrer=webhooks_plugin)

Panic Message:

```
catch.go:29: building declarative schema change targets for EXPERIMENTAL CHANGEFEED: interface conversion: btree.Item is *nstree.byIDItem, not *nstree.byNameItem
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/util/errorutil.ShouldCatch
  | 	github.com/cockroachdb/cockroach/pkg/util/errorutil/catch.go:29
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).Build.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:212
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).tryBuildOpaque
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/opaque.go:72
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:440
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmtAtRoot
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:272
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).Build
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:246
  | github.com/cockroachdb/cockroach/pkg/sql.(*optPlanningCtx).buildExecMemo
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:576
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).makeOptimizerPlan
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:240
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).makeExecPlan
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2028
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1537
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1036
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:142
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:3083
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:141
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2183
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2188
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2105
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:902
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:310
  | runtime.goexit
  | 	src/runtime/asm_arm64.s:1172
Wraps: (3) building declarative schema change targets for EXPERIMENTAL CHANGEFEED: interface conversion: btree.Item is *nstree.byIDItem, not *nstree.byNameItem
  | -- cause hidden behind barrier
  | building declarative schema change targets for EXPERIMENTAL CHANGEFEED: interface conversion: btree.Item is *nstree.byIDItem, not *nstree.byNameItem
  | (1) attached stack trace
  |   -- stack trace:
  |   | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scerrors.EventLogger.HandlePanicAndLogError
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scerrors/errors.go:81
  |   | runtime.gopanic
  |   | 	GOROOT/src/runtime/panic.go:884
  |   | runtime.panicdottypeE
  |   | 	GOROOT/src/runtime/iface.go:262
  |   | runtime.panicdottypeI
  |   | 	GOROOT/src/runtime/iface.go:272
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/nstree.(*byNameItem).Less
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/nstree/by_name.go:39
  |   | github.com/google/btree.items.find.func1
  |   | 	github.com/google/btree/external/com_github_google_btree/btree.go:189
  |   | sort.Search
  |   | 	GOROOT/src/sort/search.go:65
  |   | github.com/google/btree.items.find
  |   | 	github.com/google/btree/external/com_github_google_btree/btree.go:188
  |   | github.com/google/btree.(*node).insert
  |   | 	github.com/google/btree/external/com_github_google_btree/btree.go:309
  |   | github.com/google/btree.(*BTree).ReplaceOrInsert
  |   | 	github.com/google/btree/external/com_github_google_btree/btree.go:702
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/nstree.upsert
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/nstree/tree.go:38
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/nstree.byNameMap.upsert
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/nstree/by_name_map.go:24
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/nstree.(*NameMap).Upsert
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/nstree/name_map.go:39
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*leasedDescriptors).getResult
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/leased_descriptors.go:168
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*leasedDescriptors).getByName
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/leased_descriptors.go:104
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).getNonVirtualDescriptorID.func6
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:574
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).getNonVirtualDescriptorID
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:614
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.getDescriptorByName
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:398
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.ByNameGetter.Database
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/getters.go:243
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.getObjectPrefix
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/helpers.go:97
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.PrefixAndTable
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/helpers.go:134
  |   | github.com/cockroachdb/cockroach/pkg/sql.MemberOfWithAdminOption
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/authorization.go:518
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*planner).MemberOfWithAdminOption
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/authorization.go:496
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*planner).UserHasAdminRole
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/authorization.go:472
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*planner).HasAdminRole
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/authorization.go:488
  |   | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scbuild.newBuilderState
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scbuild/build.go:256
  |   | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scbuild.Build
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scbuild/build.go:69
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*planner).SchemaChange
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/schema_change_plan_node.go:71
  |   | github.com/cockroachdb/cockroach/pkg/sql.buildOpaque
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/opaque.go:56
  |   | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).tryBuildOpaque
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/opaque.go:70
  |   | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmt
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:440
  |   | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmtAtRoot
  |   | 	github.com/cockr...
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_arm64.s#L1171-L1173](src/runtime/asm_arm64.s#L1171-L1173)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/pgwire/conn.go#L309-L311](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/pgwire/conn.go#L309-L311)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/conn_executor.go#L901-L903](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/conn_executor.go#L901-L903)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/conn_executor.go#L2104-L2106](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/conn_executor.go#L2104-L2106)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/conn_executor.go#L2187-L2189](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/conn_executor.go#L2187-L2189)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/conn_executor.go#L2182-L2184](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/conn_executor.go#L2182-L2184)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/conn_executor_exec.go#L140-L142](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/conn_executor_exec.go#L140-L142)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/conn_executor_exec.go#L3082-L3084](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/conn_executor_exec.go#L3082-L3084)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/conn_executor_exec.go#L141-L143](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/conn_executor_exec.go#L141-L143)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/conn_executor_exec.go#L1035-L1037](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/conn_executor_exec.go#L1035-L1037)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/conn_executor_exec.go#L1536-L1538](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/conn_executor_exec.go#L1536-L1538)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/conn_executor_exec.go#L2027-L2029](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/conn_executor_exec.go#L2027-L2029)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/plan_opt.go#L239-L241](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/plan_opt.go#L239-L241)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/plan_opt.go#L575-L577](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/plan_opt.go#L575-L577)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/opt/optbuilder/builder.go#L245-L247](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/opt/optbuilder/builder.go#L245-L247)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/opt/optbuilder/builder.go#L271-L273](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/opt/optbuilder/builder.go#L271-L273)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/opt/optbuilder/builder.go#L439-L441](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/opt/optbuilder/builder.go#L439-L441)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/opt/optbuilder/opaque.go#L71-L73](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/opt/optbuilder/opaque.go#L71-L73)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/opt/optbuilder/builder.go#L211-L213](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/sql/opt/optbuilder/builder.go#L211-L213)
[https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/util/errorutil/catch.go#L28-L30](https://github.com/cockroachdb/cockroach/blob/d7e9824b4cd6ebf7a8548156f2a772ae6648257d/pkg/util/errorutil/catch.go#L28-L30)
</details>

```
src/runtime/asm_arm64.s in runtime.goexit at line 1172
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommandsAsync.func1 at line 310
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 902
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 2105
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 2188
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd.func1 at line 2183
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 141
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithProfiling at line 3083
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt.func1 at line 142
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 1036
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchToExecutionEngine at line 1537
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).makeExecPlan at line 2028
pkg/sql/plan_opt.go in pkg/sql.(*planner).makeOptimizerPlan at line 240
pkg/sql/plan_opt.go in pkg/sql.(*optPlanningCtx).buildExecMemo at line 576
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).Build at line 246
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).buildStmtAtRoot at line 272
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).buildStmt at line 440
pkg/sql/opt/optbuilder/opaque.go in pkg/sql/opt/optbuilder.(*Builder).tryBuildOpaque at line 72
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).Build.func1 at line 212
pkg/util/errorutil/catch.go in pkg/util/errorutil.ShouldCatch at line 29
```

### Tags

| Tag | Value |
| --- | --- |
| Command | start-single-node |
| Environment | v23.1.12 |
| Go Version | go1.19.13 |
| Platform | linux arm64 |
| Distribution | CCL |
| Cockroach Release | v23.1.12 |
| Cockroach SHA | d7e9824b4cd6ebf7a8548156f2a772ae6648257d |
| # of CPUs | 10 |
| # of Goroutines | 538 |

Jira issue: CRDB-45633

**Comment by spilchen** [comment]
Experimental changefeeds (created via EXPERIMENTAL CHANGEFEED FOR ...) aren’t supported by the DSC. At this point, we’re simply going through the motions to check if it’s being handled. So far, the code path is fairly generic—we’re looking up a descriptor by name, but the map is set up by ID. This is still generic logic, and it’s likely that another goroutine corrupted the map somehow.

Without a reliable reproduction, this issue will be challenging to debug. We haven’t encountered this type of error before. For now, I’m going to close this as non-actionable. If it starts happening more frequently, we can revisit and investigate further.
