### ISSUE TITLE
hlc: document that NewClock's maxOffset should never be zero

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#13768]
Consider making it panic. From https://reviewable.io/reviews/cockroachdb/cockroach/13726#-KdeyNnDyHpdrSLtu-Vc:-KdgR7YF9JLQvGlJ9GXE:b-brk0y8

**Comment by tamird** [comment]
It's not true that it should _never_ be zero, but it should never be zero in tests.

**Comment by danhhz** [comment]
```
$ git grep -F "hlc.NewClock(hlc.UnixNano, 0)" | grep _test.go | wc -l
      23
```

This issue has rotted, closing
