### ISSUE TITLE
Cannot close a cursor in a read-only transaction

### ISSUE THREAD

**Issue by PetrSilar** [cockroachdb/cockroach#137606]
**Describe the problem**

It's not possible to close a cursor in a read-only transaction. Attempting so ends with `ERROR: cannot execute CLOSE in a read-only transaction` and the transaction is aborted.
The behavior seems illogical to me and it's also different from the Postgre's behavior (obviously).
I didn't find any mention about this behavior as e.g. Cockroach's limitation.

**To Reproduce**

Follow e.g. the example in chapter _Cursors_ of the documentation ([https://www.cockroachlabs.com/docs/v24.3/cursors.html](https://www.cockroachlabs.com/docs/v24.3/cursors.html)). Just replace `BEGIN;` with `BEGIN READ ONLY;`:
```
BEGIN READ ONLY;
DECLARE rides_cursor CURSOR FOR SELECT * FROM movr.rides;
FETCH FORWARD 5 FROM rides_cursor;
CLOSE rides_cursor;
COMMIT;
```

**Expected behavior**

`CLOSE rides_cursor;` works. I.e. the command is accepted and transaction can continue.

**Additional data / screenshots**
N/A

**Environment:**
 - CockroachDB 24.3.1 (the issue is definitely not new in this release)
 - official docker image

**Additional context**
What was the impact?

I use third party library [libpqxx](https://github.com/jtv/libpqxx) to access Cockroach's data. The library obviously calls `CLOSE` in cursor's class destructor. To workaround the issue I have to patch the library's sources (to comment out the call) which is pretty uncomfortable. The resources of the cursors within Cockroach will remind allocated to the transaction's end.

Jira issue: CRDB-45669

**Comment by PetrSilar** [comment]
> Hi @PetrSilar, please add branch-* labels to identify which branch(es) this C-bug affects.
> 
> 🦉 Hoot! I am a [Blathers](https://github.com/apps/blathers-crl), a bot for [CockroachDB](https://github.com/cockroachdb). My owner is [dev-inf](https://github.com/orgs/cockroachdb/teams/dev-inf).

It seems I don't have enough rights to do that (the _Labels_ on the right side are not clickable for me).

**Comment by jeffswenson** [comment]
Thanks for reporting this!

I added 23.1 as the first impacted release, because I had that version on hand to test with. I suspect this behavior is as old as read only transactions and cursors.

**Comment by PetrSilar** [comment]
Thank you for the very fast fix!

**Comment by yuzefovich** [comment]
Thank you for the report!
