### ISSUE TITLE
ui: Tooltips for graphs

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/cockroach#13766]
Each graph in the Admin UI should have a tooltip with greater detail about what it represents.

**Comment by mrtracy** [comment]
We previously had tooltips for all graphs, and in fact most graphs still have tooltip text specified in our React elements; however, we have not yet turned these tooltips back on after our recent redesign.

The central issue is where that tooltip should be positioned: in our previous iteration, the tooltip would display when you hovered over a small icon on the top-right corner of the graph. Because the hover target was small, we could display the tooltip at a constant position relative to this icon and it would be reasonably close to the current mouse position.

However, in our current graph design the tooltip target is supposed to be the graph title; this is a much larger target, and thus we may need to position the tooltip relative to the current mouse position directly, which is quite a bit trickier (although far from intractable).

**Comment by mrtracy** [comment]
Kuan, i'm going to assign this to you for some design input (just an answer to where this tooltip should be positioned, and if there are any changes to the tooltip appearance since the previous design). Just assign it back to me after that.

**Comment by kuanluo** [comment]
Yes, I will take a look first and @sploiselle can chime in with final copy.

**Comment by kuanluo** [comment]
@mrtracy @sploiselle 

Having no icon and relying on the hover of the titles might be too subtle. After trying a few options, I settled on having the icon to the right corner of the graph box:
![image](https://cloud.githubusercontent.com/assets/1486483/23808921/a343f2a8-0599-11e7-8d50-1ce87a4ad5e7.png)

The icon is `12px` circle with a ! in the middle, that's from Lato Black `10px` font. The normal state color is `#b8bbbc` the same as the small text under Capacity used in the Summary box.
It would be great if we can allow a larger-than-size-of-icon area for hover: 

![image](https://cloud.githubusercontent.com/assets/1486483/23809379/73fbbc90-059b-11e7-88a1-77686e08c7f8.png)

The hover state color is the same as the title of the graph, and the tooltip box uses the same style as the ones for the graph. The styles are also updated on Page: UI Polish on Sketch.

**Comment by mrtracy** [comment]
@sploiselle Tooltips have now been enabled for all graphs that have them, but not every graph has a tooltip yet, and I still believe you were looking to refresh the tooltips for the 1.0 milestone.

**Comment by petermattis** [comment]
Ping. We have ~24 hours if we want to do anything here for 1.0. @sploiselle I believe you were working on new tooltip text.

**Comment by petermattis** [comment]
@sploiselle Is there anything left to do here? Can we close this issue?

**Comment by sploiselle** [comment]
@petermattis We still need tooltips for the other graphs but the work related to the 1.0 release is finished. If it's preferable, can close this ticket and create a new one that's related to the follow-on tasks.

**Comment by petermattis** [comment]
SGTM. Or change the milestone on this issue to 1.1.

**Comment by dianasaur323** [comment]
@mrtracy don't worry about doing this issue for 1.1.

**Comment by Amruta-Ranade** [comment]
@mrtracy @kuanluo @dianasaur323 In addition to new tooltips, some existing tooltips are incorrect or need improvement. Do we have all the tooltips listed in one place that I can edit? Or should I copy-paste them individually and edit them?

**Comment by dianasaur323** [comment]
@Amruta-Ranade If you tell me what you'd like for all the tooltips, it's relatively easy for me to put them in. I can also show you how to do it if you'd like.

**Comment by dianasaur323** [comment]
e

**Comment by Amruta-Ranade** [comment]
@dianasaur323 I would love to learn to do it myself - whenever you have the time, let me know :)

**Comment by dianasaur323** [comment]
@Amruta-Ranade do you mind grabbing something on my calendar next week? Otherwise I'll never get to it. Thanks!

**Comment by couchand** [comment]
It doesn't seem like there's anything specific left on this, so I'm closing it.

@Amruta-Ranade if you want to open an issue for the ones that are wrong, go ahead (if that's even still the case).
