### ISSUE TITLE
cli: results with no columns are rendered incorrectly

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#13769]
Our CLI renders results of a select with no columns by just printing `OK`, which doesn't make too much sense.

Us:
```
root@:26257/jordan> SELECT * FROM empty;
OK
```
psql:
```
$ psql -p 26257 -h localhost
psql (9.6.2, server 9.5.0)
Type "help" for help.

jordan=> select * from empty;
--
(0 rows)
```

Found after fixing #13725.

**Comment by knz** [comment]
The error is server side.

Using `psql` using both a pg server and a cockroach server:

- with a pg server, the example returns 3 rows (with no columns)
- with a cockroach server, the example returns 0 rows (with no columns)

The problem is with the server/pgwire, not the client.
