### ISSUE TITLE
storage: TestPut consistency check sometimes never returns

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#13777]
Depends on #13776. After that change goes in, if we re-enable the `CheckConsistency` call in the test we sometimes see a failure where the consistency check never returns:

`W170223 17:23:58.708510 2724 kv/dist_sender.go:1173  [n1] have been waiting 1m0s sending RPC for batch: 1 ChkConsistency`

**Comment by petermattis** [comment]
When the hang occurs, I see that the compute checksum request is not processed on one of the nodes. Without the compute checksum being processed, a subsequent collect checksum request to that node hangs indefinitely.

**Comment by petermattis** [comment]
Oh, fun. We might not process a `ComputeChecksumRequest` on one of the replicas because the replica was too far behind (or just being added) and it was caught up using a Raft snapshot. Because the `ComputeChecksumRequest` wasn't processed, the subsequent `CollectionChecksum` request waits forever (or until it times out).

Not sure what we can/should do here. We can't rely no a request sent through Raft to be executed on every replica. So creating side-effects from the execution of the command that are then required for another operation is a no-no.

Cc @bdarnell

**Comment by bdarnell** [comment]
Looks like we need to cancel all pending `Replica.getChecksum` calls when applying a snapshot (probably in `refreshPendingCommands` with an appropriate `reason` code. (and we should have a timeout too)

**Comment by petermattis** [comment]
I went the route of ensuring that we specify a timeout for `CollectionChecksum` requests.
