### ISSUE TITLE
Sentry: flow.go:536: length of both the processor and the output must be 1
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/flowinfr...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#137886]
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/6167012007/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/6167012007/?referrer=webhooks_plugin)

Panic Message:

```
flow.go:536: length of both the processor and the output must be 1
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Resume
  | 	github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:536
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Resume
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:292
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).resumeFlowForPausablePortal
  | 	github.com/cockroachdb/cockroach/pkg/sql/planner.go:311
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2399
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1973
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchReadCommittedStmtToExecutionEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1721
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1175
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:141
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:3435
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:140
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execPortal
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:246
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2416
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2418
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2233
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:958
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommands
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:251
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).serveImpl.func4
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:1131
  | runtime.goexit
  | 	src/runtime/asm_amd64.s:1695
Wraps: (3) length of both the processor and the output must be 1
Error types: (1) *assert.withAssertionFailure (2) *withstack.withStack (3) *errutil.leafError
-- report composition:
*errutil.leafError: length of both the processor and the output must be 1
flow.go:536: *withstack.withStack (top exception)
*assert.withAssertionFailure
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_amd64.s#L1694-L1696](src/runtime/asm_amd64.s#L1694-L1696)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/pgwire/server.go#L1130-L1132](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/pgwire/server.go#L1130-L1132)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/pgwire/conn.go#L250-L252](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/pgwire/conn.go#L250-L252)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/conn_executor.go#L957-L959](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/conn_executor.go#L957-L959)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/conn_executor.go#L2232-L2234](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/conn_executor.go#L2232-L2234)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/conn_executor.go#L2417-L2419](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/conn_executor.go#L2417-L2419)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/conn_executor.go#L2415-L2417](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/conn_executor.go#L2415-L2417)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/conn_executor_exec.go#L245-L247](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/conn_executor_exec.go#L245-L247)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/conn_executor_exec.go#L139-L141](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/conn_executor_exec.go#L139-L141)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/conn_executor_exec.go#L3434-L3436](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/conn_executor_exec.go#L3434-L3436)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/conn_executor_exec.go#L140-L142](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/conn_executor_exec.go#L140-L142)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/conn_executor_exec.go#L1174-L1176](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/conn_executor_exec.go#L1174-L1176)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/conn_executor_exec.go#L1720-L1722](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/conn_executor_exec.go#L1720-L1722)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/conn_executor_exec.go#L1972-L1974](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/conn_executor_exec.go#L1972-L1974)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/conn_executor_exec.go#L2398-L2400](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/conn_executor_exec.go#L2398-L2400)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/planner.go#L310-L312](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/planner.go#L310-L312)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/colflow/vectorized_flow.go#L291-L293](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/colflow/vectorized_flow.go#L291-L293)
[https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/flowinfra/flow.go#L535-L537](https://github.com/cockroachdb/cockroach/blob/beddec16a5a438d66bd3f5f4202085cf21c0973c/pkg/sql/flowinfra/flow.go#L535-L537)
</details>

```
src/runtime/asm_amd64.s in runtime.goexit at line 1695
pkg/sql/pgwire/server.go in pkg/sql/pgwire.(*Server).serveImpl.func4 at line 1131
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommands at line 251
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 958
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 2233
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 2418
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd.func2 at line 2416
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execPortal at line 246
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 140
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithProfiling at line 3435
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt.func1 at line 141
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 1175
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchReadCommittedStmtToExecutionEngine at line 1721
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchToExecutionEngine at line 1973
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithDistSQLEngine at line 2399
pkg/sql/planner.go in pkg/sql.(*planner).resumeFlowForPausablePortal at line 311
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlow).Resume at line 292
pkg/sql/flowinfra/flow.go in pkg/sql/flowinfra.(*FlowBase).Resume at line 536
```

### Tags

| Tag | Value |
| --- | --- |
| Command | mt start-sql |
| Environment | v24.2.5 |
| Go Version | go1.22.5 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v24.2.5 |
| Cockroach SHA | beddec16a5a438d66bd3f5f4202085cf21c0973c |
| # of CPUs | 32 |
| # of Goroutines | 526 |

Jira issue: CRDB-45790

**Comment by yuzefovich** [comment]
unactionable
