### ISSUE TITLE
distsql: typing information for data traveling over the wire on DistSQL streams should be statically configured

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#13798]
At the moment, the typing information is fed to a `StreamDecoder` when the first row is passed to the corresponding `StreamEncoder`. This leads to an awkward communication protocol where the sender/receiver need to keep track of whether they've sent/received this information.
I think it'd be a lot nicer if the typing was inferred and configured as part of the `StreamEndpointSpec` when the plan is created.

Jira issue: CRDB-6110

**Comment by RaduBerinde** [comment]
A note on how to add this to the planner: the schema is always available in the corresponding input sync spec; so this could easily be added in `PopulateEndoints`.

**Comment by dianasaur323** [comment]
moving to later to match the referenced issue #8792
