### ISSUE TITLE
distsql: versioning story

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#13801]
We need to have  a versioning mechanism in place for distsql.

### SQL expressions ###

The big issue is around serialized SQL expressions - these are bound to change in an incompatible way sooner or later, especially as we fill in the gaps of what distsql supports (e.g. collated strings, functions that depend on evalcontexts).

One idea that can provide a lot of flexibility is as follows. We have a distsql expression version that is embedded in every server. A server emits expressions "signed" with a "minimum" version; this is not the server's version, but it is the minimum server version that can handle that expression. A server fails a request that contains an expression with a version higher than its own. It is up to the "emitter" (planner) to keep track of what features are handled by which versions. This way, when changes are made, we can decide at that time how far back we can guarantee compatibility. 

This allows a smooth transition through consecutive versions while gracefully failing queries in mixed-version clusters that span versions that are too far apart. Once we add a new feature, we first release a version `X` that is able to handle that new feature, but that *does not use it* during planning. A subsequent version `Y` can use it during planning as well, setting the version field to `X` so that only version `X` and above servers can run it. The user would need to upgrade through both versions if they want to avoid stopping everything.

Servers can also have a "minimum acceptable version" and disallow requests with versions smaller than that - this allows retiring deprecated features.

### Flow specs and components ###

Similar problems need to be addressed for flow specs - we need to be able to add new processors and new capabilities to existing processors. However, this can be handled without including specific versions, by always adding new protobuf fields/types and continuing to handle the deprecated ones as necessary.

Perhaps this proposal should be made into an RFC.

CC @cuongdo @andreimatei @knz

**Comment by knz** [comment]
I would like to suggest that at least in the coming months we consider restricting distribution of queries to nodes that run exactly the same version of the code. 

The structure of SQL expressions is not the only issue at stake -- the entire flow management code needs to match or bad things will happen. We need to see this code running for a while in prod to get a feeling of what could go wrong upon version mismatches.

**Comment by RaduBerinde** [comment]
I think that would be a good approach to start with.
