### ISSUE TITLE
storage: Cancel pending getChecksums when applying snapshots

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#13810]
From #13777 : When a raft snapshot is applied, consistency check operations may be left hanging until they eventually time out. It would be better to cancel these `getChecksum` operations, probably when calling `refreshPendingCommandsLocked` with an appropriate `reason` code.

**Comment by dianasaur323** [comment]
@bdarnell is this still an issue, and if so, should we move it into the 1.0 milestone?

**Comment by bdarnell** [comment]
Still an issue as far as I know. It's not critical for 1.0, though, so I'll put it in 1.1.

**Comment by tschottdorf** [comment]
Haven't seen this be an issue.
