### ISSUE TITLE
distsql: expressions requiring the `EvalCtx` can't be evaluated

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#13821]
We don't serialize the `EvalCtx` when setting up flows (and we don't initialize it on the remote side). This means we can't evaluate expressions that need any of the arguments in that context. We currently prevent queries with such expressions from being distributed by using a `FuncExpr.IsContextDependent()` check.

Notably, the `EvalCtx` contains a session's time zone which is used for parsing dates. With this occasion, we should investigate if the accessor for that time zone, which currently returns `UTC` is nothing is set, is safe as it is or whether it should error if it hasn't been initialized.

**Comment by dianasaur323** [comment]
@andreimatei I also need your thoughts on timing for this issue. I'm trying to close out old issues that were marked with a Q1 2017 milestone in case some should be done by 1.0.

**Comment by RaduBerinde** [comment]
We are trying to get this done opportunistically for 1.0, in part because explaining this limitation to our users is complicated.

**Comment by dianasaur323** [comment]
Gotcha, thanks Radu!

**Comment by cuongdo** [comment]
If this isn't fixed for 1.0, please ensure that this is documented as a known limitation.

**Comment by arjunravinarayan** [comment]
The thinking is to serialize just the timestamps for 1.0, as that solves the biggest known limitation from a user's perspective with relatively little code, but only try and solve this completely in 1.1. cc @andreimatei.

**Comment by RaduBerinde** [comment]
The important one is to serialize whatever is needed to support `DATE` and `TIMESTAMPTZ` types (I think `EvalContext.Location`).

**Comment by arjunravinarayan** [comment]
Closed by #15628.
