### ISSUE TITLE
ui: graph overlay does not show all lines

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#13824]
build sha: 4c8949513d287b92be1c167615398a2a53fe39da (beta-20170223)

The graph overlay seems to be having issues displaying data for all the lines displayed on the graph.
The pattern *seems* to be that data series that are new in the graph (as in start somewhere in the middle) get shown as zero. I have not tried this enough time to be sure though.
![broken_graph_overlay](https://cloud.githubusercontent.com/assets/5901480/23378156/6835eb90-fd00-11e6-9fbe-5429e70db6b5.png)

In the above screenshot, the blue line for `cockroach-node-4` starts about 3/4 through the graph, but there's not a single point that shows an overlay with a non-zero value.

**Comment by dianasaur323** [comment]
@josueeee let's reconsider how monitoring can look better for this use case. Moving to 1.2

**Comment by couchand** [comment]
This seems to be a duplicate of #12856
