### ISSUE TITLE
sql: option for logging queries

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#13851]
Although we don't want to document current debug logging flags (see https://github.com/cockroachdb/docs/issues/1066), it'd be nice to add a new, more intuitive option for logging queries that could be documented. 

@bdarnell suggests maybe a setting in some system configuration table instead of something to be set on each node at startup, in which case we might want to track it in #9304.

**Comment by dianasaur323** [comment]
adding in @knz who I believe is working on SQL logging. Please remove from 1.0 if it's not going to be ready then.

**Comment by knz** [comment]
@dt I will want to work together with you on this at the same time as we polish #13968.
