### ISSUE TITLE
storage: pushTxnQueue doesn't support batched pushTxn ops

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#13876]
`intentResolver` sends multiple `PushTxn` operations in a single batch, but the retry loop in `Store.Send` only uses the `pushTxnQueue` for single pushes. We must either split up these batches and send pushes individually, or support batches containing multiple pushes in `Store.Send`.

See #13875, which introduces exponential backoff for these batches so we're at least not retrying them in a tight loop.

**Comment by spencerkimball** [comment]
Note that `PushTxn` requests never come batched (`roachpb/api.go` defines the `isAlone` flag for `PushTxnRequest`), so `pushTxnQueue` doesn't need to support batched ops.

**Comment by bdarnell** [comment]
Yeah, this issue was mistaken. (the isAlone flag was introduced at the same time as the queue; prior to that pushes could be batched)
