### ISSUE TITLE
sql: can define improperly typed column default

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#13873]
During table creation and alter table (see https://github.com/cockroachdb/cockroach/issues/13872), you can define an invalid default expression for a column. This then prevents inserts.
 
```
~/src/github.com/cockroachdb/cockroach$ cockroach sql
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.

root@:26257/> create database test;
CREATE DATABASE

root@:26257/> create table test.t1 (a decimal default (decimal '1-3'));
CREATE TABLE

root@:26257/> show columns from test.t1;
+-------+---------+------+---------------------------+---------+
| Field |  Type   | Null |          Default          | Indices |
+-------+---------+------+---------------------------+---------+
| a     | DECIMAL | true | ('1-3':::STRING::DECIMAL) | {}      |
+-------+---------+------+---------------------------+---------+
(1 row)

root@:26257/> insert into test.t1 values (default);
pq: could not parse '1-3' as type decimal
```

@dt, @vivekmenezes

**Comment by eisenstatdavid** [comment]
This is a tricky issue to address because `"could not parse"` is actually a runtime error arising from the cast from `string` to `decimal`, which evades the existing type checking. Due to the flexibility of the `DEFAULT` constraint, we could also have an "time bomb" like this:

```
root@:26257/> create database d;
CREATE DATABASE
root@:26257/> create table d.t (c decimal default if(now() < '2017-04-18 18:00:00', 2, '3-1'::decimal));
CREATE TABLE
root@:26257/> insert into d.t values (default);
INSERT 1

<wait a little bit>

root@:26257/> insert into d.t values (default);
pq: could not parse '3-1' as type decimal
```

As such, I don't think that it's feasible to detect all runtime errors ahead of time, though post-1.0 we could consider improving the compile-time evaluation of constant expressions to detect constructs that inevitably explode.

Note that insertion isn't blocked if one overrides the default value:

```
root@:26257/> create database d;
CREATE DATABASE
root@:26257/> create table d.t (c decimal default '3-1'::decimal);
CREATE TABLE
root@:26257/> insert into d.t values (2);
INSERT 1
root@:26257/> select * from d.t;
+---+
| c |
+---+
| 2 |
+---+
(1 row)
```

**Comment by jordanlewis** [comment]
We should definitely enhance constant folding to evaluate constant casts and function applications. I think this could probably get done pre-1.0.

**Comment by eisenstatdavid** [comment]
Closing because #15055 is the extent of what we can do here.

**Comment by justinj** [comment]
Copied from comments on #15055:

> After some more investigating it seems like what Postgres might be doing is just checking if literals can be coerced their expected types (but just literals, not constant expressions in general). For example, these are accepted:
> ```
> CREATE TABLE t (a INT DEFAULT CONCAT('f', 'oo')::INT);
> CREATE TABLE t (a INT DEFAULT ('f' || 'oo')::INT);
> ```
> but this isn't:
> ```
> CREATE TABLE t (a INT DEFAULT 'foo'::INT);
> ```
> and this also isn't, so it's not just an explicit coercion thing:
> ```
> CREATE TABLE t (a INT DEFAULT (case when 1 = 1 then 1 else 'foo' end));
> ```
> We could possibly do a similar check.
