### ISSUE TITLE
sql: non-recoverable errors during schema changes do not cause schema change to abort

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#13872]
```
~/src/github.com/cockroachdb/cockroach$ grep -F '[config]' schema-change/logs/cockroach.INFO
I170301 11:22:30.874796 1 util/log/clog.go:999  [config] file created at: 2017/03/01 11:22:30
I170301 11:22:30.874796 1 util/log/clog.go:999  [config] running on machine: JESSEs-MacBook-Pro
I170301 11:22:30.874796 1 util/log/clog.go:999  [config] binary: CockroachDB CCL 4ac3ba3 (darwin amd64, built 2017/02/28 04:25:18, go1.7.1)
I170301 11:22:30.874796 1 util/log/clog.go:999  [config] arguments: [cockroach start --store=schema-change]
```

Currently, you're able to define an invalid column default (reported in separate issue: https://github.com/cockroachdb/cockroach/issues/13873). Doing so during `alter table` causes the schema change to continue indefinitely. There may be other ways to provoke this behavior, but in  any case, we need to ensure schema changes either make forward progress or fail, e.g., by distinguishing between fatal and retryable errors.

Steps to reproduce: 

1. Add a new column to a table with an invalid default value:

   ```
   root@:26257/> ALTER TABLE test.sc ADD COLUMN e DECIMAL NOT NULL DEFAULT (DECIMAL '1-3');
   ```

   This results in the SQL shell hanging indefinitely. And this error getting logged over and over: 
   
   ```
   W170301 11:24:00.461757 240 sql/session.go:491  [n1] Error executing schema change: could not parse '1-3' as type decimal
   ```

2. Force quit the sql client.

3. Restarted the sql client and try to insert a new row:

    ```
    root@:26257/> insert into test.sc values (1, 3.3);
    ```

   This results in an error:

   ```
   pq: could not parse '1-3' as type decimal
   ```

**Comment by dt** [comment]
Seems like we have two separate issues here: one is validating DEFAULT exprs to prevent getting into this state, the other is what to do when we do get into it anyway -- we need to ensure schema changes either make forward progress or fail, e.g. by distinguishing between fatal and retryable errors.

**Comment by jseldess** [comment]
Good point, @dt. I'll create a separate issue for the default bug and rephrase this one.
