### ISSUE TITLE
ui: table inspector reports incorrect number of indices

### ISSUE THREAD

**Issue by mattlord** [cockroachdb/cockroach#13888]
```
root@:26257/test> show create table t2;
+-------+---------------------------------------------+
| Table |                 CreateTable                 |
+-------+---------------------------------------------+
| t2    | CREATE TABLE t2 (␤                          |
|       |     id INT NOT NULL,␤                       |
|       |     name STRING(100) NULL,␤                 |
|       |     CONSTRAINT "primary" PRIMARY KEY (id),␤ |
|       |     INDEX idx_name (name),␤                 |
|       |     FAMILY "primary" (id, name)␤            |
|       | )                                           |
+-------+---------------------------------------------+
(1 row)
root@:26257/test> show indexes from t2;
+-------+----------+--------+-----+--------+-----------+---------+----------+
| Table |   Name   | Unique | Seq | Column | Direction | Storing | Implicit |
+-------+----------+--------+-----+--------+-----------+---------+----------+
| t2    | primary  | true   |   1 | id     | ASC       | false   | false    |
| t2    | idx_name | false  |   1 | name   | ASC       | false   | false    |
| t2    | idx_name | false  |   2 | id     | ASC       | false   | true     |
+-------+----------+--------+-----+--------+-----------+---------+----------+
(3 rows)
```

As you can see the test.t2 table has 2 indexes: primary and idx_name.

However the Console lists a value of 3 for the "# OF INDICES" column:
<img width="1434" alt="cockroach-console-bug" src="https://cloud.githubusercontent.com/assets/1043484/23561794/bd1f235a-000d-11e7-8381-9e82585ae4b2.png">

I've tested this with various tables and the count shown in the Console seems to be the number of index parts rather than a count of the unique indexes--so not taking into account multi-column indexes (and all secondary indexes seem to be multi-column indexes, including a copy of the PK). 

I'm not sure if you want to change this in TableDescriptor, IndexDescriptor, or just in the Console... but it's at least confusing for the end user in the Console.

**Comment by knz** [comment]
Thanks @mattlord !

**Comment by dianasaur323** [comment]
I'm seeing the same problem in the PM cluster where show columns from customer shows this:
![image](https://user-images.githubusercontent.com/5768024/30604631-902a21d2-9d39-11e7-9afe-113bbc368a70.png)

While the table shows this:
![image](https://user-images.githubusercontent.com/5768024/30604641-9ac9dc2c-9d39-11e7-89e2-cff74c2b0b8f.png)

**Comment by knz** [comment]
@dianasaur323 what is the output of `show indexes from customer` on that db?

**Comment by dianasaur323** [comment]
![image](https://user-images.githubusercontent.com/5768024/30606769-cd5fd414-9d40-11e7-9413-4a4ebe3c3a57.png)

**Comment by knz** [comment]
All right now I understand what the bug is. Will make a fix.

**Comment by knz** [comment]
@mrtracy `admin.go` the TableDetailsResponse doesn't deduplicate the index names. Looking into it.
