### ISSUE TITLE
sql: aggregation (possibly table scan) returns incorrect results

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#13892]
Scenario:

- user is running insert benchmark in one client, says that insert benchmark  populates monotonically increasing PK values
- concurrently using the CLI shell the user runs single-statement `select` queries to inspect the MAX of the primary key

Observation: in the CLI query results the MAX is observed to go down sometimes.

Other observation: the query plan is a simple revscan on the PK with limit 1 (i.e. no aggregation, or technically speaking an "aggregation" over a single row already containing the desired value)

Theories:
1. the benchmark is not inserting monotonically increasing PK values
2. the table scan is incorrect
3. the single row "aggregation" is incorrect

**Comment by petermattis** [comment]
> the benchmark is not inserting monotonically increasing PK values

Why would this matter? Even if the PK values are being inserted out of order, we would expect MAX to be monotonically increasing.

**Comment by bdarnell** [comment]
The table definition:

```
testdb=> SHOW CREATE TABLE test_table;
   Table    |                   CreateTable
------------+-------------------------------------------------
 test_table | CREATE TABLE test_table (                      +
            |         id_ INT NOT NULL,                      +
            |         name_ STRING NULL,                     +
            |         CONSTRAINT "primary" PRIMARY KEY (id_),+
            |         FAMILY "primary" (id_, name_)          +
            | )
(1 row)
```

The query, with explanation:

```
explain(verbose) select max(id_) from test_table;
 Level |  Type   |    Field    |        Description         |        Columns        |  Ordering
-------+---------+-------------+----------------------------+-----------------------+-------------
     0 | group   |             |                            | ("max(id_)")          |
     0 |         | aggregate 0 | max(testdb.test_table.id_) |                       |
     0 |         | render 0    | max(testdb.test_table.id_) |                       |
     1 | render  |             |                            | (id_)                 | -id_,unique
     1 |         | render 0    | testdb.test_table.id_      |                       |
     2 | revscan |             |                            | (id_, name_[omitted]) | -id_,unique
     2 |         | table       | test_table@primary         |                       |
     2 |         | spans       | ALL                        |                       |
     2 |         | limit       | 1                          |                       |
(9 rows)
```

**Comment by RaduBerinde** [comment]
Everything looks good from the SQL side. The revscan is returning the wrong result. I would check very carefully that there isn't something funky going on with the system clock..

**Comment by RaduBerinde** [comment]
I can try to set up a paralleltest to reproduce.
@knz do you remember if this was a multi-node cluster, and if yes were the two clients (the INSERTer and the SELECTer) connecting to different nodes?

**Comment by knz** [comment]
I can't remember the number of nodes.

**Comment by RaduBerinde** [comment]
I have been trying to repro this but never saw the issue. We would need more specific information about the cluster setup, incorrect values observed, what the benchmark is inserting, etc.. There is not much to go on here so I'm closing.
