### ISSUE TITLE
ui: Admin UI appears odd on very wide screens

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#13903]
Our ui only takes up limited amount of the screen.  It should scale for larger screens.

<img width="1281" alt="screen shot 2017-03-06 at 11 34 08" src="https://cloud.githubusercontent.com/assets/1614265/23619723/8eb4c09a-0262-11e7-9ceb-a8489c432a5b.png">

**Comment by mrtracy** [comment]
Restated as a problem rather than a solution
