### ISSUE TITLE
storage: "unable to add replica ... which is already present" message shouldn't be logged at error severity

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#13916]
Shortly after starting up a 3 node cluster on AWS, a user saw a lot of these error messages in the logs for a handful of different ranges. They don't indicate a true error, and shouldn't be logged at such high severity.

**Comment by dianasaur323** [comment]
Seems like a quick fix? Assigning to @a-robinson. Feel free to reassign if necessary.

**Comment by a-robinson** [comment]
#14863
