### ISSUE TITLE
perf: latency discrepancy

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#13929]
99th and 95th %tile latencies reported by Grafana do not match the 99th and 95th %tile latencies reported by `kv`. Yes, these latencies are measured at different places, but the discrepancy is large enough to warrant investigation.

<img width="929" alt="screen shot 2017-03-06 at 9 28 38 pm" src="https://cloud.githubusercontent.com/assets/6201335/23639174/1d582a66-02b4-11e7-95c2-133231bc8c2f.png">

<img width="928" alt="screen shot 2017-03-06 at 9 28 46 pm" src="https://cloud.githubusercontent.com/assets/6201335/23639179/1f9f52b8-02b4-11e7-8e9d-0137cad40ba0.png">

```
_elapsed___errors__ops/sec(inst)___ops/sec(cum)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)
  1h6m1s      144        34711.4        36595.0      7.9     48.2     71.3    176.2
  1h6m2s      144        36445.7        36595.0      8.1     44.0     67.1    159.4
  1h6m3s      144        36669.3        36595.0      7.9     48.2     71.3    142.6
  1h6m4s      144        35767.3        36594.8      8.1     48.2     71.3    159.4
  1h6m5s      144        35480.7        36594.5      8.4     48.2     71.3    151.0
  1h6m6s      144        38995.4        36595.1      7.1     46.1     65.0    251.7
  1h6m7s      144        38231.9        36595.5      7.3     44.0     62.9    121.6
  1h6m8s      144        36039.5        36595.4      7.9     46.1     67.1    142.6
  1h6m9s      144        36896.3        36595.4      8.1     48.2     71.3    176.2
 1h6m10s      144        37703.5        36595.7      7.6     46.1     67.1    218.1
```

Notice that the 95th %tile latencies in the graphs are ~5-10ms while `kv` is reporting ~45-50ms. Is this another instance of our latency metrics being faulty?

**Comment by petermattis** [comment]
@mberhault Not sure if I'm reading this right, but the Grafana data seems to be showing the `exec.latency` metric which is measured for `Node.Batch` calls. But I think we should be using the `sql.exec.latency` metric.

**Comment by mberhault** [comment]
Uh. oops. I'll fix that.

**Comment by petermattis** [comment]
@mrtracy What metric is being used on the Admin UI `Exec Latency` graphs.

**Comment by mberhault** [comment]
Added aggregation rule and modified grafana.

**Comment by petermattis** [comment]
@mrtracy Ping. What metric is the admin UI using for the latency graphs?

**Comment by mberhault** [comment]
The "backend statement execution latency" graphs on the sql tab use `cr.node.sql.exec.latency-p*`, so they're doing the right thing, only prometheus/grafana was erroneous.
