### ISSUE TITLE
sql: support FlywayDB schema migration and management tool

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#13949]
This issue tracks individual bugs or missing features for supporting [FlywayDB](https://flywaydb.org). It will be updated to add new issues over time as they're discovered.

FlywayDB is a popular schema management and migration tool similar to Liquibase. It has support for a wide variety of databases including PostgreSQL. Such a popular tool should be usable with CockroachDB, whether that's through the existing PostgreSQL adapter or, if necessary, a custom CockroachDB adapter.

- [x] #13948 - RESET keyword

**Comment by cuongdo** [comment]
To update this issue, support for CockroachDB has been [merged into Flyway](https://github.com/flyway/flyway/commit/4cab619a2445bbaef19a47d0810710fe55a4d7c2). This is pending some acceptance testing by @jordanlewis.

**Comment by tlvenn** [comment]
Support for `SELECT ... FOR UPDATE` statement will be needed as well as discussed in #18656

**Comment by cuongdo** [comment]
@jordanlewis do you have any updates on the Flyway support? has it been integration tested yet?

**Comment by jordanlewis** [comment]
It's been tested. It's missing CI still, though.

**Comment by tlvenn** [comment]
On a side note, in relation to #19145 , Flyway CDB adaptor have to be patched so that the drop database statement is explicitly using `CASCADE` for now.

> https://github.com/flyway/flyway/blob/4cab619a2445bbaef19a47d0810710fe55a4d7c2/flyway-core/src/main/java/org/flywaydb/core/internal/dbsupport/cockroachdb/CockroachDBSchema.java#L61
