### ISSUE TITLE
sql: SET var TO/= DEFAULT is unsupported 

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#13952]
We support [the syntax](https://github.com/cockroachdb/cockroach/blob/7eaf354baeebd0285db8247f16fa2b9f186f1956/pkg/sql/parser/sql.y#L1428) in our parser, but there's no support in `sql/set.go` where there would need to be a map of defaults for each supported var.

This is related to (and needed for) #13948.

**Comment by knz** [comment]
What would be the consequence of accepting the syntax but ignoring it entirely?

**Comment by jordanlewis** [comment]
Presumably, applications that expected stuff like `SET DATABASE TO DEFAULT` might fail or encounter unexpected results.

**Comment by boxofrad** [comment]
Hi! 👋 

I'd like to start contributing to CockroachDB, would this be a good first ticket?

My initial thoughts were to add a `defaults` member to the `sql.Session` struct, fill it in [`sql.NewSession()`](https://github.com/cockroachdb/cockroach/blob/3674a3a52e10ba5de2bb5442872b28c22da31021/pkg/sql/session.go#L124), and restore those values in [`planner.Set()`](https://github.com/cockroachdb/cockroach/blob/3674a3a52e10ba5de2bb5442872b28c22da31021/pkg/sql/set.go#L35).

The PostgreSQL behaviour is [slightly different](https://www.postgresql.org/docs/9.6/static/sql-reset.html):

> This is subtly different from defining it as "the value that the parameter had at session start", because if the value came from the configuration file, it will be reset to whatever is specified by the configuration file now.

Would we need to consider this?

**Comment by jordanlewis** [comment]
Hi @boxofrad,

Yes, I think this could be a good first ticket for sure, and we'd appreciate your contribution.

Luckily, we don't need to consider the more complex Postgres behavior that you cite, because we don't have any session variables that tie into configuration parameters.

Your initial thoughts are pretty good, but I think we can do a little bit better if you're willing to perform a small refactoring as well. If you have a look at [sql/show.go#varGen](https://github.com/cockroachdb/cockroach/blob/3674a3a5/pkg/sql/show.go#L36), you'll see that we've made a map from variable name to getter function. I think it would be nice to unify `show` and `set` by changing that map to have a value type of something like:

```
type Var struct {
  Set func(p *planner, []parser.TypedExpr) error
  Get func(p *planner) string
  Reset func(p *planner) error
}
```

This has a few benefits. It unifies the implementations of `set` and `show`, which I'm noticing have already drifted a bit, with some variables settable but not showable; it prevents the spreading of similar logic across the two files; and for the purposes of adding defaults, it prevents us from having to add another similar bit of logic to the session struct.

What do you think? It's a little bit more work, but it would provide a lot of cleanup value as well as adding the new feature. If you decide to take this on, I suggest doing the refactor in one commit and adding the reset/default implementation in another.

**Comment by boxofrad** [comment]
Thanks for the tip @jordanlewis! 🙇 
I went ahead with the refactoring as suggested - see #14105.

**Comment by jordanlewis** [comment]
Thanks for the great contribution @boxofrad! Closing this now.
