### ISSUE TITLE
ui: Versions error in admin UI

### ISSUE THREAD

**Issue by spencerkimball** [cockroachdb/cockroach#13959]
Getting this error loading the admin UI - Node versions are mismatched. undefined versions. Versions across all 3 are exact.  The IP’s were removed from below commands.
 
cockroach version
Build Tag: beta-20170223
Build Time: 2017/02/23 16:30:53
Distribution: CCL
Platform: linux amd64
Go Version: go1.7.5
C Compiler: gcc 4.9.3
Build SHA-1: 4c8949513d287b92be1c167615398a2a53fe39da
Build Type: release
 
Started 3 node cluster on ubuntu 16.04.
cockroach start --insecure --background --advertise-host=
cockroach start --insecure --background --advertise-host= --join= :26257
cockroach start --insecure --background --advertise-host= --join=:26257
 
new tables and database get created across all 3 nodes fine.
 
8080 should be opened
AWS EC2 sercurity group rule
Type= All Traffic, Protocol=All, Port-Range=All

**Comment by markhubb33** [comment]
Hi Guys

It was something on our end.  I don't know what was changed to fix this at this point but will find out.  this can be closed out.

Thanks
Mark

**Comment by dianasaur323** [comment]
@markhubb33 Great to hear. Let us know if you have any other issues. Closing out!

**Comment by maxlang** [comment]
Looks like we occasionally get a bad response from the backend. Re-opening.

**Comment by spencerkimball** [comment]
Let's not wait to fix the possibility of a bad response. A simpler fix, and one that should be implemented in this case, is to ignore bad responses for the purpose of issuing this warning. It's otherwise just confusing.

**Comment by dianasaur323** [comment]
assigning to @mrtracy

**Comment by couchand** [comment]
Given that we don't have any more information about this, I'm closing it out for now.  Feel free to file a new issue if there's an issue here.
