### ISSUE TITLE
ui: support operating behind reverse proxy

### ISSUE THREAD

**Issue by gpaul** [cockroachdb/cockroach#13981]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.

I would like to run CockroachDB's Admin UI behind a reverse proxy at a base URI of `/cockroach`. In a perfect world I would like to have all paths in the response be relative. In the spirit of pragmatism I'd gladly settle for some way to configure a global `/cockroach` prefix.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

Blocker. No workaround.

3. Provide any additional detail on your proposed use case for this feature.

According to https://tools.ietf.org/html/rfc7320#section-2.3

> For example, an application ought not specify a fixed URI path "/myapp", since this usurps the host's control of that space.

**Comment by mrtracy** [comment]
This is not familiar territory for me personally, thanks for bringing this up.  

I can't commit to a time frame, but I think we should look into the usage of relative paths; the Admin UI is a single page app and we use hash navigation to individual pages (we don't any sort of pushState), so if i'm understanding this correctly using relative urls for our JSON requests and assets might actually be more straightforward than attempting to configure a baseUri.  Does that seem correct to you?

**Comment by gpaul** [comment]
Something like https://github.com/cockroachdb/cockroach/pull/14017 seems to do the trick.
