### ISSUE TITLE
sql: Foreign key validation on existing table is too slow

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#13986]
I don't have a lot of details to explain the exact scenario, but a user reported that when they ran the `ALTER TABLE VALIDATE CONSTRAINT` command on a table which had an unvalidated foreign constraint and only about 1000 rows, it took multiple minutes to complete. This seems far too long for such a small table.

Is that level of slowness expected, @dt?

**Comment by dt** [comment]
99% sure that's just the `JOIN`, so over to @knz for more insight.

**Comment by dt** [comment]
Ideally we should make a representative pair of tables and wrap it in a benchmark so we can quantify that JOIN performance.

**Comment by knz** [comment]
Yeah sorry but there is nothing for me to work with here.
I know the query (we generate it) but I don't have the db schema, so I have no idea which plan was generated.

Please provide schema and/or debug output with `--vmodule=executor=3`

**Comment by jordanlewis** [comment]
cc @BramGruneir  - is this something you / @emsal1863 are looking at or have looked at?

**Comment by BramGruneir** [comment]
@jordanlewis No we haven't. As @dt mentioned earlier, the best way to start this investigation is to create a benchmark and go from there.

**Comment by jordanlewis** [comment]
Stale.
