### ISSUE TITLE
beta-20170309

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#13988]
The candidate SHA is dd3a574da6734faebf523d7cc2df244ab662527d.
Deployment status is on adriatic, indigo, and omega.

[Release process checklist](https://github.com/cockroachdb/cockroach/wiki/Release-Process)
- [x] Check and verify cluster status
- [x] Tag release and push tag
- [x] [Trigger release build](https://teamcity.cockroachdb.com/viewType.html?buildTypeId=Cockroach_MergeToMaster)
- [x] Check and verify binaries
- [x] Announce version to the registration cluster - see internal production instructions
- [x] Update homebrew
- [x] Update docs
- [x] External communications for release

**Comment by benesch** [comment]
Clusters look healthy. No known issues. Proceeding with release!

**Comment by benesch** [comment]
@jseldess is adding a few additional changes to the release notes. Otherwise, the binaries and an initial version of the release notes are deployed.

**Comment by jseldess** [comment]
Docs updated and published. 

@jess-edwards, @swatikumar16, you're up.

**Comment by benesch** [comment]
External communications deployed. Cheers, everyone!
