### ISSUE TITLE
server: add /debug/network page

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#13984]
Network misconfiguration is a very common problem. The admin UI should highlight when there are networking problems. As an interim solution, we should add a /debug/network page that fills a matrix showing RPC latencies from every machine to every other machine (in both directions). 

@a-robinson, @BramGruneir not sure which of you have more time to work on this. Assigning Alex because this ties in with the network latency measurements added to RPC heartbeats and Bram because this is similar to the /debug/range work.

**Comment by a-robinson** [comment]
Fixed by @BramGruneir in #16174
