### ISSUE TITLE
Support for oid() function

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#13998]
This is the first (of potentially many) blockers to using the IntelliJ database tool with CockroachDB. The `oid()` function may just be a shortcut for casting an integer to an OID, although I can't find any documentation about it.

**Comment by jordanlewis** [comment]
https://doxygen.postgresql.org/int8_8c.html#a08ff5000a961812c9c3ffefe05e5c85f is the source in Postgres. You can usually figure out where to find the source code for a builtin by checking `pg_proc` in a Postgres instance - `SELECT prosrc FROM pg_proc WHERE proname='oid'` led me to `i8tooid`.

**Comment by jordanlewis** [comment]
I happen to use the JetBrains Gogland for go development, so I went ahead and gave the DB tool a try. It seemed to work for selects, but I also didn't see a call to `oid()` in the query log, so I'm guessing whatever tool was tried is different from the one that I tried.

Additionally, inserts with auto-commit mode off tried to execute `SAVEPOINT JDBC_SAVEPOINT_0`, which we don't support.

**Comment by jordanlewis** [comment]
Actually, I see a (pretty hilarious) query that uses `oid()`, which I suppose will work after the patch:

```
 select max(last_tx) as state_number
from (
  select max(xmin::varchar::bigint) as last_tx
    from pg_catalog.pg_type
    where typnamespace = oid($1)
  union all
  select max(xmin::varchar::bigint) as last_tx
    from pg_catalog.pg_class
    where relnamespace = oid($2)
  union all
  select max(xmin::varchar::bigint) as last_tx
    from pg_catalog.pg_proc
    where pronamespace = oid($3)
  union all
  select max(xmin::varchar::bigint) as last_tx
    from pg_catalog.pg_operator
    where oprnamespace = oid($4)
  union all
  select max(A.xmin::varchar::bigint) as last_tx
    from pg_catalog.pg_attribute A join pg_catalog.pg_class K on K.oid = A.attrelid
    where K.relnamespace = oid($5)
  union all
  select max(xmin::varchar::bigint) as last_tx
    from pg_catalog.pg_constraint
    where connamespace = oid($6)
  union all
  select max(IX.xmin::varchar::bigint) as last_tx
    from pg_catalog.pg_index IX,
         pg_catalog.pg_class IC
    where IC.oid = IX.indrelid
      and IC.relnamespace = oid($7)
  union all
  select max(RU.xmin::varchar::bigint) as last_tx
    from pg_catalog.pg_rewrite RU,
         pg_catalog.pg_class RC
    where RC.oid = RU.ev_class
      and RC.relnamespace = oid($8)
  union all
  select max(TG.xmin::varchar::bigint) as last_tx
    from pg_catalog.pg_trigger TG,
         pg_catalog.pg_class TC
    where TC.oid = TG.tgrelid
      and TC.relnamespace = oid($9)
  union all
  select max(DE.xmin::varchar::bigint) as last_tx
    from pg_catalog.pg_description DE,
         pg_catalog.pg_class DC
    where DC.oid = DE.objoid
      and DC.relnamespace = oid($10)
      and DC.relkind in ('r', 'm', 'v')
) X
```

**Comment by a-robinson** [comment]
@kain1e, which tool were you showing me?

**Comment by jordanlewis** [comment]
No, nevermind, this won't work yet. We don't support `pg_operator`, `pg_trigger`, or `pg_rewrite`.

**Comment by jordanlewis** [comment]
... nor do we support the `xmin` column, which is an implicit column defined by Postgres as "The identity (transaction ID) of the inserting transaction for this row version. (A row version is an individual state of a row; each update of a row creates a new row version for the same logical row.)"

See https://www.postgresql.org/docs/9.6/static/ddl-system-columns.html for more details on `xmin`.

It seems quite unlikely to me that we will add support for `xmin`.

**Comment by a-robinson** [comment]
Wow, that's one heck of a feature.

**Comment by kain1e** [comment]
The tool I showed you was IntelliJ:s db tool window that needs catalog metadata:   https://www.jetbrains.com/help/idea/2016.3/database-tool-window.html. Its mainly used for visually browsing schemas. It now stops with the message  'ERROR: unknown function: oid(). (1s)'
IntelliJs SQL console window seems to work just fine.
