### ISSUE TITLE
why does teamcity need write permission to my personal data?

### ISSUE THREAD

**Issue by gpaul** [cockroachdb/cockroach#14018]
When I want to log into teamcity it wants *write* access to

> Personal user data:
  Full access
  This application will be able to read and write all user data. This includes the following:
  Private email addresses
  Private profile information
  Followers

Why?

**Comment by mberhault** [comment]
Not sure. https://github.com/pwielgolaski/teamcity-oauth says to use that for github. I only glanced at the plugin source, so I'm not sure what information it needs.
However, it seems that github only has the following user scopes:
```
user          Grants read/write access to profile info only. Note that this scope includes user:email and user:follow.
user:email    Grants read access to a user's email addresses.
user:follow   Grants access to follow or unfollow other users.
```

Maybe `user:email` doesn't have all the information needed? Not sure, someone should poke further, but at that point, teamcity/oauth-plugin authors would probably be more useful.

**Comment by gpaul** [comment]
Thanks @mberhault I've opened an issue upstream, let's see what happens. Until this is addressed I cannot debug #14017 even though I would love to.

**Comment by jordanlewis** [comment]
Hi @gpaul, in the meantime you can append `&guest=1` to force a guest login to TeamCity.

**Comment by gpaul** [comment]
@jordanlewis excellent! Thanks

**Comment by benesch** [comment]
@jordanlewis a quick source drive through the teamcity-oauth plugin suggests it doesn't need any scopes at all. It only [needs to extract the `login` key from the api.github.com/user endpoint](https://github.com/pwielgolaski/teamcity-oauth/blob/753a13f318003e9e143efa9b4d99012fe9228389/src/main/java/jetbrains/buildServer/auth/oauth/OAuthAuthenticationScheme.java#L99-L109) and AFAICT [doesn't hit any other endpoints](https://github.com/pwielgolaski/teamcity-oauth/blob/98bdcdb81e42661fa1b9cc767b6bcf697e1fdaa8/src/main/java/jetbrains/buildServer/auth/oauth/ConfigPresets.java). Might be worth reconfiguring the plugin to not request any scopes and see if it continues to work? I'll bet it does.

**Comment by pwielgolaski** [comment]
Use latest version (>= 1.0.4) and don't specify scope, it should solve the issue.

**Comment by benesch** [comment]
Thanks for the quick turnaround, @pwielgolaski!

**Comment by dt** [comment]
Upgraded plugin, removed scope and restarted TC last night. Confirmed this morning that I can re-auth with GitHub providing `Public data only`.

Thanks for pointing this out @gpaul and thanks again @pwielgolaski for the super-quick update!

**Comment by gpaul** [comment]
This is great news, thanks all.
