### ISSUE TITLE
sql: MemoryMonitor messages completely spam traces for large queries

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#14020]
When running a pretty sizable join, the number of messages about "requesting 10240 bytes from the pool" completely overwhelm everything else about the query's trace. In the first such query I looked at on `/debug/requests`, the trace was at 1000 lines (plus a message indicating that 16265 events discarded had been discarded from the trace), 895 of which were either `txn: requesting N bytes from the pool` or `root: requesting N bytes from the pool` (where N is usually 10240, but occasionally a little larger). It seems safe to assume that most of the discarded events were the same.

I have a couple questions about this:

1. Is it expected for queries to do so many small allocations?
1. Should the allocation algorithm request larger chunks if it finds that it's having to request more so frequently?
1. If this is expected behavior, should we really be attaching it to the trace? I imagine it's causing a ton of allocations.

I've attached a file with some example traces from `/debug/requests`, which includes the queries that were run.

[bigtrace.txt](https://github.com/cockroachdb/cockroach/files/831519/bigtrace.txt)

@knz

**Comment by knz** [comment]
1. yes
2. it doesn't really matter, the overhead here is rather negligible. FWIW that size is configurable.
3. no, we should not be attaching this to the trace. I am surprised, these messages should only appear at logging level 2 or above. Why is the trace capturing them in the first place?

**Comment by knz** [comment]
Basically anything that prevents the log messages from being output anywhere unless `--vmodule=mem_usage=...` is specified would be good by me. I thought that filtering on the log level was enough, but apparently it is not.

**Comment by a-robinson** [comment]
Ok, thanks for clarifying! I'll send a PR to keep them out of the trace. The issue here is a misunderstanding of VEventf, which always writes to the trace but does the verbosity check before deciding whether to write to the log. The comment on it could probably stand be improved.

**Comment by andreimatei** [comment]
Well, I don't think we want to keep these messages out of the trace
completely. Rafa, could we only log progressively, when an account doubles
since the last time it logged?

Also, FWIW, I see there's a `COCKROACH_NOTEWORTHY_SESSION_MEMORY_USAGE` env
var controlling what increments we print.

**Comment by knz** [comment]
Ok let's be specific then:

- the message `%s: memory usage increases to %s (+%d)` should always go to the trace, but you may want to increase `COCKROACH_NOTEWORTHY_SESSION_MEMORY_USAGE` like andrei suggested if it's too verbose as-is.
- we probably want to have `%s, memory usage max %s` in the trace too (from `Stop()`)
- the following messages should never go to the trace:
  - `%s: now at %d bytes (+%d) - %s`
  - `%s: now at %d bytes (-%d) - %s`
  - `%s: requesting %d bytes from the pool`
  - `%s: releasing %d bytes to the pool`
  - everything logged by `MakeUnlimitedMonitor()` and `(*MemoryMonitor).Start()`
- perhaps the error `%s: memory budget exceeded: %d bytes requested, %d bytes in budget` should *also* be logged to the trace.
