### ISSUE TITLE
server: Include info about request counts to each range on debug page(s)

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#14038]
We now have info in the `replicaStats` member of each Replica about how many requests the replica has processed (and from which localities). This info would be useful to put in the new range debug page, if not elsewhere as well.

It would have helped debug the load generation problem in #13627, as one example.

@BramGruneir @a-robinson

**Comment by BramGruneir** [comment]
@a-robinson Is this covered by #17124, or is there more you were thinking of?

**Comment by a-robinson** [comment]
Yup, this was it.
