### ISSUE TITLE
restore: TableDescriptors: unexpected value

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#14045]
When running a restore from a time travel backup, got this error:

```
pq: restoring 1 TableDescriptors: unexpected value: raw_bytes:"j\303\033\004\001h" timestamp:<wall_time:1489009352501625105 logical:0 >
```

But the table existed and had 16M rows in it, so it's not immediately clear what or when the failure was. It's pretty odd that a failure still resulted in a table being present.

**Comment by dt** [comment]
was this an empty cluster you were restoring into?

**Comment by mjibson** [comment]
It was an empty database.

**Comment by mjibson** [comment]
I think this has been fixed by our various work because we haven't seen it again. Closing.

**Comment by dt** [comment]
it _shouldn't_ have been, but i'm fine closing until we see a repro with the refactored, wrapf'ed code.
