### ISSUE TITLE
stability: consistency checksum mismatch on gamma

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#14053]
I tried to revive gamma with commit 9ad551b to reproduce #12875 and I got what appears to be a different issue. Range 294 has been causing nodes to die due to checksum mismatches reported by the consistency checker. 

The inconsistency affects the RangeStats key and a large number of regular data keys. Here's a snippet:

```
E170307 00:27:12.791627 132745897 storage/replica_command.go:1914  [n10,s10,r294/5:/Table/51/1/9{095509…-113820…},@c427205880] replica {1 1 4} is inconsistent: expected checksum de49f7e83b6189b5fd80cfeca1aa6935936e8be0b4723591c9c3cbe993bbe33c5c2bfff55f8b877062c73968b8937e9bf9fc1c560d95afe9c1c06c784918e416, got 78e5c81c4eab4c6c5eec924e44fb22702291ef07002b90e15a34bd0636b1b92e4835a51b9fa06055c63c3f703788dbd5d5363643d3712fedbe2e60fc89758e7a
--- leaseholder
+++ follower
-0.000000000,0 /Local/RangeID/294/r/RangeStats
-  ts:<zero>
-  value:^R^D^H^@^P^@^X^@ ^@(^@2|<C0><8B><8A>3^C        ҍl<85><EF>q<A9>^T^Q<B9><9C>^]^@^@^@^@^@^Y^@^@^@^@^@^@^@^@!W<9A>6^C^@^@^@^@)<B2><C8>^E^@^@^@^@^@1<AA>^G<88>^A^@^@^@
^@9<B2><C8>^E^@^@^@^@^@A<AD><92><AE>^A^@^@^@^@I<B2><C8>^E^@^@^@^@^@Q<8A>2^@^@^@^@^@^@Y<9A>^@^@^@^@^@^@^@a{<B2>^_^@^@^@^@^@i^W
^@^@^@^@^@^@p^@
-  raw_key:/Local/RangeID/294/r/RangeStats raw_value:120408001000180020002800327cc08b8a330309d28d6c85ef71a91411b99c1d000000000019000000000000000021579a36030000000029b2c805000000000031aa0788010000000039b2c805000000000041ad92ae010000000049b2c8050000000000518a32000000000000599a00000000000000617bb21f000000000069170a0000000000007000
+0.000000000,0 /Local/RangeID/294/r/RangeStats
+  ts:<zero>
+  value:^R^D^H^@^P^@^X^@ ^@(^@2|<F2><9F><C2>>^C        ҍl<85><EF>q<A9>^T^Q<B9><9C>^]^@^@^@^@^@^Y^@^@^@^@^@^@^@^@!̙6^C^@^@^@^@)<B1><C8>^E^@^@^@^@^@1f^G<88>^A^@^@^@^@9<B1>
<C8>^E^@^@^@^@^@Af<92><AE>^A^@^@^@^@I<B1><C8>^E^@^@^@^@^@Q<8A>2^@^@^@^@^@^@Y<9A>^@^@^@^@^@^@^@a{<B2>^_^@^@^@^@^@i^W
^@^@^@^@^@^@p^@
+  raw_key:/Local/RangeID/294/r/RangeStats raw_value:120408001000180020002800327cf29fc23e0309d28d6c85ef71a91411b99c1d000000000019000000000000000021cc9936030000000029b1c805000000000031660788010000000039b1c8050000000000416692ae010000000049b1c8050000000000518a32000000000000599a00000000000000617bb21f000000000069170a0000000000007000
-1488775541.796898839,0 /Table/51/1/9107503532074261439/"f6faf94f-0aa6-485a-aae4-09c8a25bd0f5"/16350/0
-  ts:2017-03-06 04:45:41.796898839 +0000 UTC
-  value:<B2><D3>^R\
FvL^A<89>3'<FF>ڀ<F3><EA>N>^R<E5>p<EE>'^X-^R^Z<EA><E4>^LX<84><F0>Q<E5>^_6<8D><FE><A0>^\[<EC><8F><F7><E0><89><C0>^GeRt<C6><E9>Ω<96><FF>^Z<9A><B6><F4><D5>«DLB<B4><FF>Y<E3>aPG<9D>g<D3>o\<CF>3}<BC>^D
<9B><F8><B4><D8><E0>^A*<A5><86><9B><B4><ED><DC>3"K^X<B1><9E><A8><AB><DB><CC>ߝ@ESC^Q<9A>n<FA>u<F3>^]<94>~<E5>n
-  raw_key:/Table/51/1/9107503532074261439/"f6faf94f-0aa6-485a-aae4-09c8a25bd0f5"/16350/0 raw_value:b2d3125c0a46764c01893327ffda80f3ea4e3e12e570ee27182d121aeae40c5884f051e51f368dfea01c5bec8ff7e089c007655274c6e9cea996ff1a9ab6f4d5c2ab444c42b4ff59e36150479d67d36f5ccf337dbc040a9bf8b4d8e0012aa5869bb4eddc33224b18b19ea8abdbccdf9d401b119a6efa75f31d947ee56e
-1488840091.491830809,0 /Table/51/1/9107503606271963575/"12dfd933-1ba3-454a-9ee3-25184c3231e7"/290236/0
-  ts:2017-03-06 22:41:31.491830809 +0000 UTC
-  value:
q/ESC
FN<8A><8F>W<F2>7^W^H<92>b<C3>^\<A1><A5>~!^Q^K`<F1><C0><B0>^BP <AB>1^L<AA><CC><D3><F9>G<AA>E$<DA>^Cɠ?5Q<D2>a^C<B2><9E>D`<9D>a<AC>i$<95>E/<B1><8E><E8>^W5<DD>M<D3>S<A2>\P^Me<A9>ρM
-  raw_key:/Table/51/1/9107503606271963575/"12dfd933-1ba3-454a-9ee3-25184c3231e7"/290236/0 raw_value:0a712f1b0a464e8a8f57f23717089262c31ca1a57e21110b60f1c0b0025020ab310caaccd3f947ef99a5aa4524da03c9a03f3551d26103b29e44609d61ac692495452fb18ee81735dd4dd353a25c500d65a9cf814d
-1488795049.606641211,2 /Table/51/1/9107503674429126669/"3ec160da-e242-4b35-82cb-c4a92b3823c2"/137232/0
-  ts:2017-03-06 10:10:49.606641211 +0000 UTC
-  value:<81>%<8E>?
F*^D<DE><EF>^V<E7><E6>V<B1>A<91><EE><89> <E5>l<B1><C5><82><B4>^A<D9><F3><AE>l<BF><84><86>N<95>5[#v<BE>o^_^S<A7>g<ED>
-  raw_key:/Table/51/1/9107503674429126669/"3ec160da-e242-4b35-82cb-c4a92b3823c2"/137232/0 raw_value:81258e3f0a462a04deef16e7e656b14191ee8920e56cb1c54d0882b401d9f3ae6cbf84864e95355b2376be6f1f13a767ed
```

Given the number of (apparently-consecutive) keys that are affected, I suspect that this is split-related. I haven't dug any deeper yet, though.

**Comment by bdarnell** [comment]
The logs aren't terribly helpful. `r294` was created when `r63` split, about 11 hours before the inconsistency was discovered. Since the consistency checker is running on a 24h cycle, it is entirely possible that the inconsistency was present when r294 was first created. 

    I170306 12:45:28.319334 318 storage/replica_command.go:2456  [split,n2,s2,r63/2:/Table/51/1/9{077259…-113820…},@c426ddea80] initiating a split of this range at key /Table/51/1/9095509723689444127/"07075438-e259-4259-8f89-595ea77b1654"/57844 [r294]

    E170306 23:14:34.078779 145023223 storage/replica_command.go:1914  [replica consistency checker,n6,s6,r294/1:/Table/51/1/9{095509…-113820…},@c42c53a000] replica {1 1 4} is inconsistent: expected checksum 56f9c1c54e48a3785911c41ec4a97e5ffd06edf199ab2418060b1c811a6b78185e5c964a52d0aedb2d3efbe60ef98b0b71a1e67022582d5eb2445dac493ddbc8, got c379

In between, there are a lot of "context deadline exceeded" errors, but nothing that looks suspicious. In particular, there is no split of r294 in the logs. The logs of r63 are similar. There are several splits (creating ranges 111, 202, and 294), and there appears to be more rebalancing activity in the logs for r63, but nothing that looks wrong. There is a rebalance of r63 about 45 seconds after the split that creates 294; r294 is never rebalanced in its life (if my logs are complete. Some nodes survived long enough after the inconsistency was detected to have their logs GC'd, although I think all the nodes that were directly involved died and preserved their logs).

**Comment by bdarnell** [comment]
Let's decode those RangeStats values:

```
package main

import (
	"encoding/hex"
	"fmt"

	"github.com/cockroachdb/cockroach/pkg/roachpb"
	"github.com/cockroachdb/cockroach/pkg/storage/engine/enginepb"
	"github.com/kr/pretty"
)

func decodeRangeStats(s string) enginepb.MVCCStats {
	decoded := make([]byte, hex.DecodedLen(len(s)))
	if _, err := hex.Decode(decoded, []byte(s)); err != nil {
		panic(err)
	}
	var meta enginepb.MVCCMetadata
	if err := meta.Unmarshal(decoded); err != nil {
		panic(err)
	}
	value := roachpb.Value{RawBytes: meta.RawBytes}
	var stats enginepb.MVCCStats
	if err := value.GetProto(&stats); err != nil {
		panic(err)
	}
	return stats
}

func main() {
	s1 := decodeRangeStats(`120408001000180020002800327cc08b8a330309d28d6c85ef71a91411b99c1d000000000019000000000000000021579a36030000000029b2c805000000000031aa0788010000000039b2c805000000000041ad92ae010000000049b2c8050000000000518a32000000000000599a00000000000000617bb21f000000000069170a0000000000007000`)
	s2 := decodeRangeStats(`120408001000180020002800327cf29fc23e0309d28d6c85ef71a91411b99c1d000000000019000000000000000021cc9936030000000029b1c805000000000031660788010000000039b1c8050000000000416692ae010000000049b1c8050000000000518a32000000000000599a00000000000000617bb21f000000000069170a0000000000007000`)

	fmt.Println(&s1)
	fmt.Println(&s2)
	fmt.Println(pretty.Diff(&s1, &s2))
}
```

```
[bdarnell@rowlf cockroach]$ go run decoder.go
contains_estimates:false last_update_nanos:1488846425372265938 intent_age:1940665 gc_bytes_age:0 live_bytes:53910103 live_count:379058 key_bytes:25692074 key_count:379058 val_bytes:28218029 val_count:379058 intent_bytes:12938 intent_count:154 sys_bytes:2077307 sys_count:2583 
contains_estimates:false last_update_nanos:1488846425372265938 intent_age:1940665 gc_bytes_age:0 live_bytes:53909964 live_count:379057 key_bytes:25692006 key_count:379057 val_bytes:28217958 val_count:379057 intent_bytes:12938 intent_count:154 sys_bytes:2077307 sys_count:2583 
[LiveBytes: 53910103 != 53909964 LiveCount: 379058 != 379057 KeyBytes: 25692074 != 25692006 KeyCount: 379058 != 379057 ValBytes: 28218029 != 28217958 ValCount: 379058 != 379057]
```

These aren't that far off; they differ by a single key/value pair (68 bytes of key and 71 bytes of value), and they have the same last-update timestamp. So in addition to being inconsistent with each other, at least one of them is inconsistent with the real data (since the full diff shows that there are a large number of entries that are present in one but not the other, and these differences are always in the same direction).

**Comment by spencerkimball** [comment]
Any chance we could start a data printing facility that works in tandem with our current `keys/printer` that would opportunistically decode data values when it can?

**Comment by bdarnell** [comment]
> Any chance we could start a data printing facility that works in tandem with our current keys/printer that would opportunistically decode data values when it can?

We have a lot of the necessary code in `cli/debug.go` (e.g. `tryRangeIDKey`).

**Comment by bdarnell** [comment]
I think the fact that the stats are off by one entry is because [this line](https://github.com/cockroachdb/cockroach/blob/e95d1dfe2527d66331f80abdde2019e2c7627b24/pkg/storage/replica_proposal.go#L569) uses `store.Engine()` directly instead of writing to the same batch as everything else. That's enough to cause replica divergence if there's an ill-timed restart, but it doesn't explain the other missing keys.

**Comment by petermattis** [comment]
I'm not following why `ContainsEstimates` can't be cleared using the normal MVCCStats machinery. Also, that field is only true for ranges containing "merge" operations (i.e. time series ranges). At the very least we could narrow that hack so it only applied if `ContainsEstimates` is true.

**Comment by bdarnell** [comment]
The normal machinery just applies a delta, so adding anything to an estimate yields a new estimate. We need some "abnormal" machinery to handle this case by doing a full scan and recomputing the stats; this is it, although it's clearly the wrong place for it. It belongs earlier in the pipeline when we're doing the on-disk changes; `replica_proposal.go` is for doing things in-memory.

**Comment by petermattis** [comment]
The "abnormal" machinery for recomputing the stats from scratch already exists in `splitTrigger`. The problem seems to be the inability to clear the `ContainsEstimates` field using the normal machinery. Seems like what we need is a new `MVCCStatus.ClearContainsEstimates` field that is set in `splitTrigger` and a small update to `MVCCStats.Add` to process that field. Need to be a bit careful here as we rely on commutativity of `MVCCStats.Add`.

**Comment by a-robinson** [comment]
All traces of gamma got wiped a couple weeks ago, so there's not much we can do here at this point. We're going to make another run through any split tests that are currently skipped or have flaked, but otherwise closing this.
