### ISSUE TITLE
sql: `UPSERT` improperly producing error "cannot affect row a second time"

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/cockroach#14052]
### Steps to Repro

Create schema:
```
CREATE TABLE foo (id INT PRIMARY KEY);

CREATE TABLE bar (
	foo_id INT, 
	id INT, 
	name CHAR, 
	truthiness BOOL,
	PRIMARY KEY (foo_id, id)
);

CREATE TABLE foo_and_bar (
	foo_id INT PRIMARY KEY, 
	bar_char_a CHAR, 
	bar_bool_a BOOL, 
	bar_char_b CHAR, 
	bar_bool_b BOOL
);
```

Enter data:
```
INSERT INTO foo VALUES (1), (2), (3), (4);

INSERT INTO bar VALUES 
(1, 1, 'A', TRUE), 
(1, 2, 'B', FALSE), 
(2, 3, 'A', TRUE), 
(2, 4, 'B', FALSE), 
(3, 5, 'A', TRUE), 
(3, 6, 'B', FALSE);

INSERT INTO foo_and_bar(foo_id, bar_char_a, bar_bool_a) 
SELECT foo_id, name, truthiness  
FROM bar 
WHERE name = 'A';
```

Now, try to use `UPSERT`/`INSERT...ON CONFLICT` to fill in blank columns of `foo_and_bar`:
```
UPSERT INTO foo_and_bar
	(foo_id, bar_char_b, bar_bool_b) 
SELECT bar.foo_id, bar.name, bar.truthiness 
FROM bar 
JOIN foo_and_bar 
ON foo_and_bar.foo_id = bar.foo_id 
WHERE bar.name = 'B';
```

### Expected Result

The 3 rows in `foo_and_bar` have their  `bar_char_b` and `bar_bool_b` values updated.

### Actual Result

```
pq: UPSERT/ON CONFLICT DO UPDATE command cannot affect row a second time
```

## More Info

- Here's the equivalent `INSERT...ON CONFLICT` statement, which produces the same error in Cockroach:
  ```
  INSERT INTO foo_and_bar(foo_id, bar_char_b, bar_bool_b) 
  SELECT bar.foo_id, bar.name, bar.truthiness
  FROM bar 
  JOIN foo_and_bar ON foo_and_bar.foo_id = bar.foo_id 
  WHERE bar.name = 'B'
      ON CONFLICT (foo_id) 
      DO UPDATE SET bar_char_b = excluded.bar_char_b, bar_bool_b = excluded.bar_bool_b;
  ```

- I'm able to get this to work in Postgres (using the `INSERT...ON CONFLICT` statement instead of `UPSERT`).
  ```
   foo_id | bar_char_a | bar_bool_a | bar_char_b | bar_bool_b
  --------+------------+------------+------------+------------
        1 | A          | t          | B          | f
        2 | A          | t          | B          | f
        3 | A          | t          | B          | f
  ```

**Comment by danhhz** [comment]
Traced this to https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/tablewriter.go#L298, where we're batching insert rows. The row we're passed is sometimes reused, so changing that line to copy it fixes this issue: `tu.insertRows = append(tu.insertRows, append([]parser.Datum(nil), row...))`

I don't know offhand if that's the right level for the fix or if it should be somewhere else in the stack. I'll investigate and get a fix out
