### ISSUE TITLE
intermittent random crashing in  cockroach-beta-20170309

### ISSUE THREAD

**Issue by andymans** [cockroachdb/cockroach#14068]
Is this a question, feature request, or bug report?

type - bug report: 
cockroach version - cockroach-beta-20170309.darwin-10.9-amd64

After some random period after startup (usually > 30 mins)  I issue a query from my app server and receive an Error: connect ECONNREFUSED 127.0.0.1:26257

To check this, I switch to my other terminal session where I have a cockroach sql client running. there, I receive the following:

driver: bad connection
connection lost; opening new connection and resetting session parameters...

I've been using the version that shipped on 23 feb until today, and this has not happened before. I suspect it's a new bug.

**Comment by tamird** [comment]
Could you include the server logs?

**Comment by andymans** [comment]
Unfortunately I tailed the logs for the 10th, but:

E170310 11:44:07.066066 26 util/log/clog.go:1017  [config] file created at: 2017/03/10 11:44:07
E170310 11:44:07.066066 26 util/log/clog.go:1017  [config] running on machine: Andys-MacBook-Pro
E170310 11:44:07.066066 26 util/log/clog.go:1017  [config] binary: CockroachDB CCL beta-20170309 (darwin amd64, built 2017/03/09 16:34:35, go1.8)
E170310 11:44:07.066066 26 util/log/clog.go:1017  [config] arguments: [./cockroach start]
E170310 11:44:07.066066 26 util/log/clog.go:1017  line format: [IWEF]yymmdd hh:mm:ss.uuuuuu goid file:line msg utf8=✓
E170310 11:44:07.066065 26 storage/queue.go:628  [replicate,n1,s1,r1/1:/{Min-Table/0},@c4203f1180] range requires a replication change, but lacks a quorum of live replicas (0/1)
E170310 11:44:17.039045 99 server/status/runtime.go:187  unable to get file descriptor usage (will not try again): not implemented on darwin
E170310 11:54:07.074621 161 storage/queue.go:708  [n1,replicate] 6 replicas failing with "0 of 0 stores with all attributes matching []; likely not enough nodes in cluster"
E170310 12:04:07.076740 161 storage/queue.go:708  [n1,replicate] 6 replicas failing with "0 of 0 stores with all attributes matching []; likely not enough nodes in cluster"

NB this error seems only to occur when running in 'single-node'. In fact it has not occurred again for the last 2 days...I'll keep an eye on it; but feel free to close...

**Comment by dianasaur323** [comment]
@andymans I'm going to close this issue out now, but let us know if you encounter any other issues.
