### ISSUE TITLE
sql: sql.request.latency metric?

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#14095]
We have a `sql.exec.latency` metric which measures the time it takes to plan and execute a parsed SQL statement, but we don't have a metric which captures the parsing and output of the result.

**Comment by knz** [comment]
Note: the new data collected by #14080 will enable this.

**Comment by justinj** [comment]
Should this/all new metrics always be added to the dashboards? Or is there some discretion exercised? Off the top of my head it seems like this might not be that useful on a day-to-day basis because it's likely to be so similar to `sql.exec.latency`?

**Comment by knz** [comment]
We don't yet have enough experience to know when to add or not add metrics to a dashboard.
So for now it's a bit of a personal decision that's subjective and arbitrary.
What is important is to ensure it is exported so we can look at it from the debug endpoints when needed.
