### ISSUE TITLE
ui: long log doesn't wrap up in the admin ui

### ISSUE THREAD

**Issue by kuanluo** [cockroachdb/cockroach#14112]
On the Logs page in the admin UI, long logs don't wrap causing the entire page have crazy horizontal scroll.
![image](https://cloud.githubusercontent.com/assets/1486483/23870516/087a4a68-07fd-11e7-9720-a6aac4d63397.png)

See video: https://drive.google.com/open?id=0BzCbOEMl6iidZlU5bDBJUHc1YVE

**Comment by mrtracy** [comment]
This is no longer an issue, should have been closed by #13182
