### ISSUE TITLE
backup: specifying bogus descriptors to BACKUP doesn't fail

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#14118]
This query claims to succeed

```
BACKUP garbage_a, garbage_b TO 'foo';
```

even though `garbage_a` and `garbage_b` don't name valid objects. The fix for this should properly abort with partially-valid specifiers too, like `foo.bar, baz.*` where `baz.*` is valid but `foo.bar` is not.

**Comment by danhhz** [comment]
my description from the dup #14149:

backup is given a list of database or table targets, potentially with wildcards. it should error if any one of them is TABLE foo.bar or TABLE baz and that doesn't match anything. TABLE foo.* not matching is probably fine unless foo is not a database, similarly DATABASE foo. it should also error if all targets specified result in 0 tables

same goes for restore
