### ISSUE TITLE
sqlccl: strategy for disasters that have happened since the last backup

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#14120]
We've had a request for the ability to restore a table that has been dropped since the last backup. (Similarly for data changed due to user error.) If the last backup was 10 hours ago and the event happened 1 hour ago, the 9 hours of data since the backup should be recovered, if possible.

 Perhaps this is as simple as using DistSQL to SELECT AS OF SYSTEM TIME and INSERT.

**Comment by vivekmenezes** [comment]
is this the same as #16161

**Comment by danhhz** [comment]
Looks like #16161 go retitled to make this more or less a dup. Closing
