### ISSUE TITLE
ui: show failed query count somewhere in admin ui

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#14148]
I just debugged why one of the production clusters wasn't getting any queries. It turns out it got wiped without restarting block_writer, which only creates the necessary databases and tables at startup, so it was continuously failing (with `pq: database "datablocks" does not exist` in the logs).  As far as I could see on the admin ui, nothing strange was happening to the cluster. Could be useful for these sorts of situations to have the count of failed SQL queries in one of the graphs.

**Comment by kuanluo** [comment]
That's a good idea! It could even be a number count in the summary box. 

Looping @mrtracy here to investigate.

**Comment by dianasaur323** [comment]
cc @josueeee

**Comment by danhhz** [comment]
fwiw, I still run into this issue probably once every two weeks or so

**Comment by dianasaur323** [comment]
Thanks Dan, point taken. We can get to this in 1.2.

**Comment by piyush-singh** [comment]
@danhhz FYI, you can now see this metric on a custom time series chart ([example](https://cyan.crdb.io:8080/#/debug/chart?metrics=%5B%7B%22downsampler%22%3A1%2C%22aggregator%22%3A1%2C%22derivative%22%3A0%2C%22perNode%22%3Atrue%2C%22source%22%3A%22%22%2C%22metric%22%3A%22cr.node.sql.failure.count%22%7D%5D)). We'll be working on adding this to the new queries page to expose it more visibly, but that will be later in the 2.1 cycle.
