### ISSUE TITLE
backup: more validation on backup/restore target selection

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#14149]
backup is given a list of database or table targets, potentially with wildcards. it should error if any one of them is `TABLE foo.bar` or `TABLE baz` and that doesn't match anything. `TABLE foo.*` not matching is probably fine unless `foo` is not a database, similarly `DATABASE foo`. it should also error if all targets specified result in 0 tables

same goes for restore

**Comment by benesch** [comment]
heh; I filed this as #14118 yesterday.

**Comment by danhhz** [comment]
welp, we don't need 2
