### ISSUE TITLE
distsql: support DISTINCT in planning

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#14141]
We have a "distinct" processor but we don't yet use it in planning.

**Comment by arjunravinarayan** [comment]
I'd be happy to take this on shortly.

**Comment by RaduBerinde** [comment]
Note that this issue entails both implementing the DISTINCT select clause, as well as the DISTINCT clause in aggregations (`SELECT SUM(DISTINCT v) ..`).

**Comment by arjunravinarayan** [comment]
Ah, I didn't catch that from the issue description, will work on adding that as well. Thank you.

**Comment by RaduBerinde** [comment]
Yeah I probably didn't think of it when I filed. We can also make it a separate issue, but we should track it.

**Comment by arjunravinarayan** [comment]
There's no need to make this a separate issue, I'm working on it in the same PR branch. Thanks.

**Comment by arjunravinarayan** [comment]
I think this is complicated enough that it needs its own issue. I will make one now.
