### ISSUE TITLE
sql: disassociate the entire schema change backfill from a single transaction

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#14156]
We associate the backfill with a single transaction because the distsql API call
distSQLPlanner.Run() needs a transaction. For schema changes this txn is ignored 
during the execution of the schema change. The index backfiller processor when called 
remotely creates its own transactions and runs backfills.

Jira issue: CRDB-6105

**Comment by andreimatei** [comment]
from dupe #15181

I think this code should make it clear what the outer txn is used for and limit its scope accordingly. It's used for getting a lease and for planning (for the rangeIterator) - I think it should stop there and we should configure the flows without a txn.

**Comment by jordanlewis** [comment]
This is out of date, backfills work differently now.

**Comment by andreimatei** [comment]
Do they? I think the confusing code in question is still there:
https://github.com/cockroachdb/cockroach/blob/63549e51eb0cedce71019e0ff15201b4d176df3a/pkg/sql/backfill.go#L788

**Comment by jordanlewis** [comment]
cc @dt @lucy-zhang - I don't understand how this stuff works, but I thought we did backfills without these transaction objects these days.

**Comment by dt** [comment]
That is not a single txn -- that is one per batch of spans that the backfiller processor does I think?

**Comment by ajwerner** [comment]
We use transactions in the column backfill. That's very important for correctness. Generally it should hit the 1PC. It's not a single transaction. It's a transaction per batch.

**Comment by andreimatei** [comment]
This issue, as I understand it, is complaining that [the dummy transaction](https://github.com/cockroachdb/cockroach/blob/63549e51eb0cedce71019e0ff15201b4d176df3a/pkg/sql/backfill.go#L788) that appears to span the whole backfill DistSQL execution is confusing.

**Comment by dt** [comment]
but the "whole distsql execution" is only one batch -- when we hit `duration` the whole flow gets torn down, we write the progress to the job and we start over at the for loop above it, right?
