### ISSUE TITLE
ui: Events section of front page doesn't auto-update even though everything else does

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#14164]
It appears as though all elements of the landing page for the admin UI auto-update over time to reflect the current state of the cluster except for the "Events" box. This confused me, because it made me think that a bunch of schema changes had happened just a couple minutes ago, when in reality I had just had the page open for a half hour and they hadn't updated (not even their times, which continued reading "3 mins ago").

Not updating them would be fine if the rest of the page didn't auto-update, but it seems confusing for parts of the page to be up-to-date as of now and others to be arbitrarily stale based on when I opened the page.

@kuanluo

**Comment by kuanluo** [comment]
You're totally right. It should auto-update, @a-robinson. I am assuming this is either a bug or an oversight in implementation.
