### ISSUE TITLE
beta-20170316

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#14167]
The candidate SHA is 10c2544061021c976d5c1585067d4a7ee78c1d69.
Deployment status is: deployed to cerulean, adriatic, blue, and indigo. Pending pekv deploy to omega courtesy of @arjunravinarayan.

[Release process checklist](https://github.com/cockroachdb/cockroach/wiki/Release-Process)
- [ ] Check and verify cluster status
- [ ] Tag release and push tag
- [ ] [Trigger release build](https://teamcity.cockroachdb.com/viewType.html?buildTypeId=Cockroach_MergeToMaster)
- [ ] Check and verify binaries
- [ ] Announce version to the registration cluster - see internal production instructions
- [ ] Update the [Homebrew tap](/cockroachdb/homebrew-cockroach)
- [ ] Update docs
- [ ] External communications for release

**Comment by mberhault** [comment]
all cluster but `omega` look good. pekv was never deployed to omega.
I supposed we need to figure out if this is a blocker or not.

**Comment by benesch** [comment]
Who makes the call?

**Comment by mberhault** [comment]
It depends on the type of problem. It could be an old one that surfaces rarely (or started resurfacing recently) in which case it's not a blocker. @a-robinson, any updates?

**Comment by a-robinson** [comment]
It does seem to be an old race condition, not something newly added, but my current thinking is that there's a decent chance that #13973 may have made it more likely to trigger. I haven't fully fleshed out the scenario that caused it yet, though. Mind holding off for another 45 minutes and checking in again then?

**Comment by benesch** [comment]
Works for me.

**Comment by a-robinson** [comment]
@benesch - just in case you're not watching #14193, we shouldn't release the current binary. We either need to wait until next week or revert #13973 from what we've been testing the last two days and release that.

**Comment by benesch** [comment]
Thanks for the heads up, @a-robinson!

**Comment by benesch** [comment]
Due to #14193, this week's release is canceled to give us time to prepare a proper fix.

/cc @jess-edwards @swa
