### ISSUE TITLE
storage: better testing of Store.SplitRange

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#1417]
#1407 fixed a bug that only showed up occasionally in our current tests. We should add something to test this more deterministically. I think the best way to test it is to add sanity checks in Store.SplitRange to read the current descriptor from the database and make sure it matches the one we're adding to the in-memory maps. However, this breaks all the tests that use `splitTestRange()` because it only executes part of the splitting process. We need to replace all uses of `splitTestRange()` with a more complete test that executes the full `AdminSplitTransaction`, then we can add these invariant checks to `SplitRange`.

**Comment by petermattis** [comment]
@bdarnell This is a very old issue. Is there any work remaining to be done here?

**Comment by bdarnell** [comment]
Yes, it would still be nice to remove `splitTestRange` and add more assertions in `SplitRange`.

**Comment by spencerkimball** [comment]
@bdarnell this issue is very old and seems unlikely to represent worthwhile work, so I'm closing it. Please re-open and update if you disagree.
