### ISSUE TITLE
storage: add a metric for unsatisfiable allocation request

### ISSUE THREAD

**Issue by spencerkimball** [cockroachdb/cockroach#14174]
Adding this metric would help diagnose under-replicated ranges in the event that we can't allocate a replica on a node / store with the required zone config constraints.

**Comment by dianasaur323** [comment]
@BramGruneir not sure if this is included in the work you are doing around fixing debug pages. If not, let's move out into 1.1.

**Comment by BramGruneir** [comment]
Moving this to 1.1

**Comment by cuongdo** [comment]
This is a code change, and it's past the 1.1 freeze. @BramGruneir is this going into 1.1 soon?

**Comment by BramGruneir** [comment]
I'd like to try to get it in.  The prerequisite before starting this was getting #17433 in first.

We already have the ability to detect under-replicated ranges in the problem-ranges report.  So this would just be a nice signal on the range page directly.

**Comment by BramGruneir** [comment]
We can close this once #17789 lands.

**Comment by a-robinson** [comment]
Although honestly I think the problem ranges page was the real fix here. It makes it clear which ranges we're failing to allocate for.

**Comment by BramGruneir** [comment]
I also just merged another 2 fixes for the raft debug page #18069, which was reporting every range as a false positive.  So it too can be useful on smallish clusters.  For larger clusters, it's going to get too big too fast.  We might want to move the pagination on that up to onto the server at some point.  (or remove/replace that page)
