### ISSUE TITLE
docs: create a run book for deploying and monitoring CockroachDB

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#14185]
This is an issue to jumpstart a wider discussion on offering a public run book that documents best practices on running, benchmarking, and monitoring CockroachDB from an operational point of view. Given our ongoing experience running POCs, we should start documenting the overall process. As a first step, we can put this documentation in our public wiki. 

Some initial feedback from external users was to outline what metrics matter when monitoring CockroachDB clusters - we offered up clock skew as one metric, but there are many others. Please offer up your thoughts!

**Comment by jseldess** [comment]
@dianasaur323, this is very much what we need in the docs as well. Why wouldn't we just put it there instead of on our wiki?

**Comment by dianasaur323** [comment]
@jseldess Totally agree that this needs to be in the docs as well. However, since it will likely be a work in progress, and we want others to contribute as well, we figured we could start in the wiki and eventually move it over to the docs.

Also added @mberhault since I know he has plenty of thoughts here.

**Comment by jseldess** [comment]
Makes sense, @dianasaur323. Thanks. Looking forward to this resource.

**Comment by cuongdo** [comment]
@petermattis @bdarnell @mberhault do any of you have time to take this on for 1.1?

**Comment by mberhault** [comment]
I can start with a skeleton version. This should probably move to the docs repo though, no coding involved here.

**Comment by jseldess** [comment]
Will be grateful for whatever you come up with. We can both integrate into our docs and use for our upcoming trainings.

**Comment by cuongdo** [comment]
@mberhault how is this going?

**Comment by mberhault** [comment]
I'm just starting on this. This would be good to have by 1.1, but it'll depend on how much polish it needs docs side.

**Comment by jseldess** [comment]
I have this as a definite focus for 1.2 docs, but @mberhault, if you can get something drafted, I can try to do minimal editing for 1.1 publication. I won't have bandwidth beyond that, though.

**Comment by mberhault** [comment]
That's fine. I think we can start with a playbook that's separate from the docs (useful at first to iterate) and make it available alongside the monitoring/alert configs. We can worry about styling, wording, and integration into the docs at a later date.

**Comment by mberhault** [comment]
@jseldess: is this still planned? Either way, it probably belongs in docs rather than here.

**Comment by jseldess** [comment]
We've done a lot of work here already, building out our [production checklist](https://www.cockroachlabs.com/docs/stable/recommended-production-settings.html) and adding more guidance around [monitoring and alerting](https://www.cockroachlabs.com/docs/stable/monitoring-and-alerting.html). So I think we can close this.
