### ISSUE TITLE
restore: update foreign keys to point to existing tables?

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#14216]
Currently restoring a table will fail if it has a foreign key that references a table not in restore, or optionally will succeed and remove the foreign key with the skip_missing option.

In some cases an operator might want to restore tables one at a time (e.g. get an important `customers` table back first, then move on to restore a larger `orders` or `reviews` table), so the either-in-same-restore-or-nothing approach might be inconvenient -- they'd have to manually re-add each FK with ALTER TABLE, assuming we even gave them a way to recover the FKs to add. It'd be nice if there were a way for the restoring table to update it's FK to point to the existing table.

**Comment by dt** [comment]
documenting this here as a TODO since it isn't currently slated on a quarterly roadmap /cc @danhhz

**Comment by dianasaur323** [comment]
Hmm.. this seems like some cleanup work that should be done by 1.1

**Comment by danhhz** [comment]
i don't think we need to do this until someone needs it
