### ISSUE TITLE
backup/restore: ability to inspect a backup

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#14219]
given the path to a backup, it would be nice to be able to inspect it, to list the tables it contains and their schemas, time bounds, etc.

**Comment by dt** [comment]
cc @danhhz

**Comment by danhhz** [comment]
Agreed. I imagine this in SQL and would it would tie in with whatever we do scheduling/listing all the backups that have been made. No reason we couldn't do this first though

**Comment by dt** [comment]
Yeah, I think this has immediate bang-for-buck and doesn't need to be tied to longer-term, larger-scope backup mgmt tooling, though it certainly would be expanded when we get their.

Short-term, something simple, just listing tables, time, size, etc could be really valuable -- for example our validation errors on referenced tables in RESTORE would be easily to resolve if you could list tables (and if we included their names, but that's a separate issue).

**Comment by a6802739** [comment]
@dt  any suggestions for inspecting the back info given the specified backup path?

**Comment by dt** [comment]
At the moment, don't have anything implemented -- hopefully will add something in the next week or two though.

If you need to inspect a given backup right now though, you could use `protoc`'s `--decode` mode on the `BACKUP` file since it is a protocol buffer.

**Comment by dt** [comment]
@danhhz any thoughts on grammar here? `SHOW BACKUP 'path/to/some/backup' ` ?

**Comment by danhhz** [comment]
the first sgtm. not really into complicating the actual BACKUP and RESTORE nodes with this, so i'm inclined against the second

**Comment by a6802739** [comment]
@dt, could I have a try for this?

**Comment by dt** [comment]
@a6802739 feel free! I think we'll want to
a) extend the grammar with `SHOW BACKUP path/to/backup`
b) add a planHook like the Backup and Restore hooks
c) use `loadBackupDescs` in `ccl/sqlccl` to load up the backup info proto and read fields from it to make some rows

What exactly goes in those rows i'm not exactly sure... maybe we start with `table`, `time`, `incremental` with `tableName`,  `endTime` and `startTime` (or NULL) ?

**Comment by a6802739** [comment]
@dt , got it. I will have a try then.
