### ISSUE TITLE
sql: take into account that fwd scans are faster

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#14228]
Apparently, reverse scans are roughly 2x slower than forward scans (due to RocksDB not being as efficient when scanning backwards).

The index selection code should take this into account so if there are two indexes that are similar but result in opposite scan directions, the fwd one should be chosen.

We should also have some documentation explaining this so that users are aware when they design their indexes.

CC @knz, @dt

**Comment by a-robinson** [comment]
You might want to do a more direct test to check whether it's really a 2x difference and on which types of reads before making big changes. For example, there seems to be a large overhead for single-key reads, but if you're scanning entire blocks then the difference might be much smaller.

**Comment by petermattis** [comment]
```
name                                        old time/op    new time/op     delta
MVCCScan_RocksDB/1Versions10Rows8Bytes-8      35.6µs ± 1%     14.0µs ± 2%   -60.63%  (p=0.000 n=10+10)
MVCCScan_RocksDB/1Versions100Rows8Bytes-8      265µs ± 1%       77µs ± 4%   -70.93%   (p=0.000 n=9+10)
MVCCScan_RocksDB/1Versions1000Rows8Bytes-8    2.56ms ± 1%     0.69ms ± 6%   -73.06%  (p=0.000 n=10+10)
```

Old is `MVCCReverseScan`. New is `MVCCScan`. I'm surprised the difference is that large. Might be some low-hanging fruit to pluck here.

**Comment by knz** [comment]
I don't know how to act on this issue at this time. It seems to me our performance targets are too fuzzy and we lack profiling data to suggest this particular issue will deliver significant improvements. De-assigning.

**Comment by knz** [comment]
I did add the item to  #12418 though.

**Comment by a-robinson** [comment]
One example of this having a major performance effect is #18159, where each revscan batch in an `ORDER BY <primary key> DESC` table scan over `system.rangelog` takes about 5-6x longer than the same scans with `ORDER BY <primary key> ASC`.

Also, as an external data point about how important scan ordering can be in RocksDB, the difference between forward and reverse scans is apparently important enough for MyRocks to include a warning about it not just on their [Limitations page](https://github.com/facebook/mysql-5.6/wiki/MyRocks-limitations), but even in their pretty short [Getting Started guide](http://myrocks.io/docs/getting-started/#create-a-rocksdb-table).

**Comment by petermattis** [comment]
I bet the lack of [column families](https://github.com/cockroachdb/cockroach/issues/17901) for `system.rangelog` is exacerbating the performance problem with reverse scans.

**Comment by petermattis** [comment]
The speed of forward vs reverse scans should be factored into the cost model. Cc @rytaft

**Comment by andy-kimball** [comment]
The cost-based optimizer factors in forward vs. reverse scans. Closing as "Fixed".
