### ISSUE TITLE
Unhelpful error when starting node on already used port

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#14223]
I started a node, forgot about it, and then later tried to start a node again on the same port and got this error:

```
$ ./cockroach start --logtostderr
I170316 22:06:12.710307 1 cli/start.go:325  CockroachDB CCL 08155fe (darwin amd64, built 2017/03/17 01:54:20, go1.8)
I170316 22:06:12.815944 21 cli/start.go:360  starting cockroach node
W170316 22:06:12.818234 21 server/server.go:158  [n?] running in insecure mode, this is strongly discouraged. See --insecure.
Error: unable to connect or connection lost.

Please check the address and credentials such as certificates (if attempting to
communicate with a secure cluster).

cockroach server exited with error: listen tcp 127.0.0.1:26257: bind: address already in use
Failed running "start"
```

@bdarnell told me that I have a node running on the default port already. In such a case, we should return a more helpful error.

**Comment by bdarnell** [comment]
The bigger problem is that without `--logtostderr`, the only message printed to the terminal is `Failed running "start"`. Even when we're not doing full logging to stderr, we should try to print *something* to the terminal in this case, or at least tell people to look in the logs.

**Comment by tamird** [comment]
Looks like 32616a9c44a1690c0b60f071da6284f8ec492506
added MaybeDecorateGRPCError to the error returned from start, which
doesn't seem appropriate.

**Comment by jseldess** [comment]
Yes, I should've included the output without `--logtostderr`:

```
~/src/github.com/cockroachdb/cockroach$ cockroach start
Failed running "start"
```

**Comment by bdarnell** [comment]
And while we're on the subject, if you use `--background`, the `Failed running "start"` message is printed twice:

```
$ ./cockroach start --background
Failed running "start"
Error: exit status 1
Failed running "start"
```

**Comment by benesch** [comment]
Additional data point: I'm sitting in a user research interview now where a "are you already running a Cockroach node on this port?" hint would have been hugely helpful.

**Comment by a-robinson** [comment]
I think we may want to generalize this issue a little more to all the situations where a node crashes without `--logtostderr` specified, because it's an issue for more than just reused ports. Ideally we could duplicate the `log.Fatal` or `panic` message to stdout, but we should at least print something about the existence/location of log files that will contain the failure information.

**Comment by knz** [comment]
This issue has been addressed. Now trying to start another node on the same port results in the following output:

```
*
* ERROR: cockroach server exited with error: consider changing the port via --port: listen tcp 127.0.0.1:26257: bind: address already in use
*
Failed running "start"
```
