### ISSUE TITLE
sql: DROP hangs after server restart

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#14246]
(I think this is a repeat of an earlier issue I have filed last year, but I can't seem to find the earlier issue)

Scenario:
1. start 1-node cluster
2. start client
3. issue CREATE TABLE then SELECT on the table
4. shut down node with ctrl+c (once = graceful shutdown)
5. restart the node
6. issue DROP TABLE on the client

-> the DROP hangs, and the server logs get filled with

```
I170317 22:42:38.420390 316 sql/lease.go:301  publish (count leases): descID=110 name=blah version=1 count=1
I170317 22:42:38.596254 316 sql/lease.go:301  publish (count leases): descID=110 name=blah version=1 count=1
I170317 22:42:38.817968 316 sql/lease.go:301  publish (count leases): descID=110 name=blah version=1 count=1
I170317 22:42:39.050036 316 sql/lease.go:301  publish (count leases): descID=110 name=blah version=1 count=1
I170317 22:42:39.230746 316 sql/lease.go:301  publish (count leases): descID=110 name=blah version=1 count=1
I170317 22:42:39.407383 316 sql/lease.go:301  publish (count leases): descID=110 name=blah version=1 count=1
I170317 22:42:39.628070 316 sql/lease.go:301  publish (count leases): descID=110 name=blah version=1 count=1
```

cc @vivekmenezes

**Comment by vivekmenezes** [comment]
confirmed that this issue is reproducible

**Comment by vivekmenezes** [comment]
Assigning to alfonso to check if the node is draining properly and the lease on the table is being released. This doesn't seem to be the case. When the node comes back up it has no knowledge of the lease and can therefore not release the lease

**Comment by asubiotto** [comment]
The node attempts to delete the lease but fails to send the RPC with
```
sql/lease.go:262  error releasing lease "51(\"t\") ver=1:1490214459728910000": failed to send RPC: sending to all 1 replicas failed; last error: node unavailable; try another peer
```
Will investigate further.

**Comment by vivekmenezes** [comment]
This is a single node issue. I'm sure you won't see it on a three node
cluster. We seem to have a situation where a node wants to drain and
therefore doesn't serve requests and yet it needs to serve requests in
order to drain. Perhaps when a nodes comes back up it also deletes old
leases
