### ISSUE TITLE
sql: constant placeholders do not get type-resolved properly

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#14245]
The following scenario does not work the way I would expect. Prepare a query via pgwire:

```
SELECT * FROM pg_catalog.pg_class
WHERE relnamespace=$1
```

Then, execute it with any integer as the parameter.

This fails with the message:
```
unsupported comparison operator: <oid> = <int>
```

However, running this query without a prepare/execute works just fine.

It seems that `Placeholder` values do not go through the same typechecking process that constant literals do - in the case of constant literals, the type checker attempts to resolve the constant into the desired type of its position in the expression tree by calling `constant.go#ResolveAsType`. Is this desired?

Assigning to @nvanbenschoten for insight into whether this behavior is expected or not.

I found this while playing with DBeaver, which executes the following prepared query:

```
SELECT c.oid,c.*,d.description FROM pg_catalog.pg_class c
LEFT OUTER JOIN pg_catalog.pg_description d ON d.objoid=c.oid AND d.objsubid=0
WHERE c.relnamespace=$1 AND c.relkind not in ('i','c')
```

**Comment by knz** [comment]
I think the issue is in pgwire: the type of the column computed for the placeholder is not propagated from prepare to execute properly. I haven't fully understood that code path yet though.

**Comment by jordanlewis** [comment]
There are two separate issues here, one of which is corrected by #14255:

1. The OID type was marked as ambiguous, which prevented the prepared query `SELECT * FROM pg_class WHERE oid=$1` from working. This is fixed by #14255.
2. A second problem, resulting in the `unsupported comparison operator: <oid> = <int>` error message that I originally included in this issue, that manifests during the prepare stage of the query

While investigating this bug, after correcting the `IsAmbiguous` implementation in the way #14255 does, the DBeaver query mentioned in the original post is successful via `TestPGPreparedQuery`. However, it still fails with that same error when it gets issued by DBeaver. I obtained a stack trace at the site where the error is created and pasted it below.

I have an unproven hunch that the underlying cause is the pgwire type hint that DBeaver sends along with the prepared query. I think what's going on is that the program is sending an `int` type hint for the placeholder parameter, which confuses the type checker because we really want to let that placeholder parameter get coerced into an `oid` the way it does in a normal, non-prepared query. I think this explanation also covers why testing this query via `TestPGPreparedQuery` doesn't detect any issues, because it doesn't look like that test sends any type hints via pgwire.

```
runtime/debug.PrintStack()
        /usr/local/Cellar/go/1.8/libexec/src/runtime/debug/stack.go:16 +0x22
github.com/cockroachdb/cockroach/pkg/sql/parser.typeCheckComparisonOp(0xc4208861b0, 0x0, 0x5fc09e0, 0xc42088c930, 0x5fc0d60, 0xc42091dfe0, 0xc4203db3c0, 0x0, 0xc4209a6648, 0x4723646, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/parser/type_check.go:991 +0x497
github.com/cockroachdb/cockroach/pkg/sql/parser.(*ComparisonExpr).TypeCheck(0xc420274300, 0xc4208861b0, 0x5fc72e0, 0x64fbf80, 0xc420274380, 0x558f240, 0xc420274380, 0x16)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/parser/type_check.go:336 +0x3e5
github.com/cockroachdb/cockroach/pkg/sql/parser.typeCheckAndRequire(0xc4208861b0, 0x5fc03a0, 0xc420274300, 0x5fc72e0, 0x64fbf80, 0x56219ee, 0xc, 0xc4202777d0, 0xc4209a67d0, 0x47d0350, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/parser/type_check.go:807 +0x70
github.com/cockroachdb/cockroach/pkg/sql/parser.typeCheckAndRequireBoolean(0xc4208861b0, 0x5fc03a0, 0xc420274300, 0x56219ee, 0xc, 0xc4202777d0, 0x5fc0060, 0xc4202777d0, 0xc4209a6818)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/parser/type_check.go:803 +0x75
github.com/cockroachdb/cockroach/pkg/sql/parser.(*AndExpr).TypeCheck(0xc4202777d0, 0xc4208861b0, 0x5fc72e0, 0x64fbf80, 0x0, 0x0, 0x5fc0060, 0xc4202777d0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/parser/type_check.go:97 +0x6e
github.com/cockroachdb/cockroach/pkg/sql/parser.TypeCheck(0x5fc0060, 0xc4202777d0, 0xc4208861b0, 0x5fc72e0, 0x64fbf80, 0xc420887900, 0x0, 0x0, 0xc4202841e8)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/parser/parse.go:95 +0xbd
github.com/cockroachdb/cockroach/pkg/sql/parser.TypeCheckAndRequire(0x5fc0060, 0xc4202777d0, 0xc4208861b0, 0x5fc72e0, 0x64fbf80, 0x56185ae, 0x5, 0x1e, 0x1e, 0x5fba360, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/parser/parse.go:103 +0x74
github.com/cockroachdb/cockroach/pkg/sql.(*planner).analyzeExpr(0xc4208861a0, 0xa653028, 0xc4201e7d80, 0x5fc0060, 0xc420277050, 0xc4202841e8, 0x1, 0x1, 0xc42088c900, 0x1e, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/analyze.go:1659 +0x110
github.com/cockroachdb/cockroach/pkg/sql.(*renderNode).initWhere(0xc4204257a0, 0xa653028, 0xc4201e7d80, 0xc4208aa160, 0x0, 0x0, 0x0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/render.go:416 +0x315
github.com/cockroachdb/cockroach/pkg/sql.(*planner).SelectClause(0xc4208861a0, 0xa653028, 0xc4201e7d80, 0xc4209e5b80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/render.go:249 +0xf4
github.com/cockroachdb/cockroach/pkg/sql.(*planner).Select(0xc4208861a0, 0xa653028, 0xc4201e7d80, 0xc4202770b0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1c, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/render.go:189 +0x51e
github.com/cockroachdb/cockroach/pkg/sql.(*planner).prepare(0xc4208861a0, 0xa653028, 0xc4201e7d80, 0x5fc0de0, 0xc4202770b0, 0xe9, 0x0, 0x0, 0x0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:387 +0xf99
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).Prepare(0xc4200016c0, 0xc4208c00ae, 0xbf, 0xc420886000, 0xc420276f60, 0x0, 0x0, 0x0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:465 +0x739
github.com/cockroachdb/cockroach/pkg/sql.PreparedStatements.New(0xc420886000, 0xc420217680, 0xc4200016c0, 0xc4208c00ad, 0x0, 0xc4208c00ae, 0xbf, 0xc420276f60, 0x0, 0x0, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/prepare.go:76 +0x63
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).handleParse(0xc420a1a800, 0xc420a1a828, 0xc42012fb00, 0x50)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:550 +0x518
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve(0xc420a1a800, 0xa6254c0, 0xc420217620, 0xc420472150, 0x5400, 0xc42025a310, 0x0, 0x0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:437 +0x8f0
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn(0xc42025a1c0, 0xa653028, 0xc4201e7d00, 0x5fc98c0, 0xc42044f720, 0x0, 0x0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:415 +0x927
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func9.1(0x5fc98c0, 0xc42044f720)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:587 +0x153
github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1(0xc4201e00a0, 0xc420134010, 0x5fc98c0, 0xc42044f720, 0xc4204ac990)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:136 +0x95
created by github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:138 +0x239
error: unsupported comparison operator: <oid> = <int>
```

**Comment by nvanbenschoten** [comment]
Huh, that's very strange. If your hunch proves correct, which shouldn't be too hard to check, then I think we'll have a few options we can consider:
- [DBeaver](https://github.com/serge-rider/dbeaver) is open-source, so we can look into fixing this upstream. If we were to do this, I'd first want to confirm that this is an isolated occurrence and that other clients properly send the oid type hint when using placeholders for oid values
- We could add a mix-type comparison operation between OID and INT. I'd really hate to do this, but it might be necessary
- We could reconsider how we handle type hints. While this could help, I can't think of any realistic ways that this could be improved

**Comment by jordanlewis** [comment]
I confirmed my hunch - this problem is indeed caused by the client setting the type hint for the `oid` placeholder to an `int` type. [Here's the offending query](https://github.com/serge-rider/dbeaver/blob/devel/plugins/org.jkiss.dbeaver.ext.postgresql/src/org/jkiss/dbeaver/ext/postgresql/model/PostgreSchema.java#L406) in DBeaver. As you can see, the placeholder is set via `PreparedStatement.setLong()` to the result of `getObjectId()`, which also returns a `long`. The actual prepare pgwire command is only sent once `executeQuery` is run, but at that point, the type hint has already been provided to the driver.

- I think an upstream fix might not be the wisest choice. Sending an incorrect type hint for OID parameters seems to be [somewhat](https://github.com/sjatgutzmann/pgstudio/blob/5216e4b49dc0040f5721b25837223be252f964e5/src/com/openscg/pgstudio/server/models/Database.java#L234) [popular](https://github.com/john-kolpakov-x/libase-left/blob/4fbac0c2adfe3d2b8e6a1a5b2d7565009cde384c/greetgo.libase/src/main/java/kz/greetgo/libase/strureader/RowReaderPostgres.java#L284) based on a few GitHub code searches, and it seems like it could be a losing battle to try to squash all of the instances. Additionally, from a client perspective, it's a bit unintuitive that this query's placeholders would have to be set to a special OID type since the query works just fine from the SQL shell with an integer constant, so I imagine this could be a pretty common pitfall.
- I'd also like to avoid adding oid-int comparison operators if possible.
- With respect to reconsidering type hint handling, I thought that we might be able to resolve this issue by playing a similar trick to the one that `CastExpr` does during type checking. That is, we check to see whether the placeholder's type can become the type expected by its context via the `Constant.AvailableTypes()` mechanism. However, I'm not sure if this approach will work, as I'm not sure whether we're able to infer what type the placeholder is expected to be by its context. In the case of the offending query, for instance, I think the expected type of `oid` is only inferrable by noticing the lack of cross-type equality operator for `int` and `oid`, right? So this idea may not work out in practice.

**Comment by jordanlewis** [comment]
It's also not obvious how to set a placeholder of a `PreparedStatement` to an OID-typed value using pgjdbc. I'm not sure if it's possible, as there doesn't seem to be an class representing OIDs implemented in pgjdbc at all.

The Java type of the result of the query `SELECT oid FROM pg_class` is also `Long`, which makes me think that this use case isn't really supported.

**Comment by jordanlewis** [comment]
This is a duplicate of #14311
