### ISSUE TITLE
docs: place the explanation about contexts in tech-notes

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#14267]
The document at https://paper.dropbox.com/doc/context.Context-and-how-it-relates-to-logging-and-tracing-in-CockroachDB-bFMpKpbR1vqnn6qmIBKTC?t=876778573480393#:t=876778573480393

should be uploaded to the `docs/tech-notes` directory.

**Comment by knz** [comment]
(alongside #14266 and #14262)

**Comment by knz** [comment]
Note that should do this even if you haven't addressed all outstanding comments. Just copy the comments with a "FIXME" in the doc.

**Comment by knz** [comment]
(Let's continue the discussion, if any, as comments on the PR.)

**Comment by andreimatei** [comment]
I was going to put this doc on the wiki. I think it's more discoverable and
easier to edit. Don't you?

**Comment by tamird** [comment]
I don't expect that many edits, so I'm +1 on the docs.

**Comment by knz** [comment]
Also I'm rather keen on versioning these docs with the source code they're describing. So later we can peek safely at "how things were" with consistent docs.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by arjunravinarayan** [comment]
I strongly support checking it into the main repository, as opposed to keeping it in the wiki.

**Comment by andreimatei** [comment]
this has been done
