### ISSUE TITLE
cleanup: Make all our panic and fatal log messages more verbose

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#14269]
Is there any reason that we don't as a rule include a lot of information in our panic and fatal log messages? In such cases, we don't need to worry about spamming the logs, and every extra bit of information can really help when trying to debug a failure that's difficult to reproduce.

As an example, the failure hit in #14193 [doesn't print out any information about the replica being garbage collected](https://github.com/cockroachdb/cockroach/blob/a0edcd258e1734fcca300905f74b783100029ab3/pkg/storage/store.go#L2224), which would have accelerated debugging of the problem as we would have quickly seen that it was only partially initialized. A quick scan through the rest of the file shows a handful of other `log.Fatal` calls that would benefit from more info, and I assume the same issue abounds in the rest of our code too.

Is anyone opposed to getting super verbose in our fatal log messages to aid debugging in the cases where they're actually hit? It shouldn't take too much effort to improve them, and I assume our future selves will thank us.

**Comment by tamird** [comment]
I've been fighting this fight one code review at a time for a while now, so
you have my vote.

**Comment by 450606975** [comment]
Do you mean you hope  more information can be found in the panic and fatal log , for explame the source file and code where the error occur  ?    I  find there are 2049  points need to be changed about  fatal log . it really looks like a large job.  Has  this problem  been solved ?

**Comment by a-robinson** [comment]
The source file and line number are already included in all of our log statements. This is more referring to peripheral information about the cause of the failure, as in the example in my initial comment. In that case, we were only logging the placeholder that didn't match our expectations, when we would have benefited greatly from also logging the object that we expected to see.

The motivation is that panics/fatals can be tough to reproduce, so every bit of information that we can print in them is worth printing. Not all of our panics/fatals need to be improved, but many of them could.
