### ISSUE TITLE
Build error: proto.Skip undefined.

### ISSUE THREAD

**Issue by hangyuancn** [cockroachdb/cockroach#1427]
if seems that the github.com/gogo/protobuf/proto has been updated ? I can't build successfully now:

rpc/codec/wire/wire.pb.go:299: undefined: proto.Skip
rpc/codec/wire/wire.pb.go:432: undefined: proto.Skip

github.com/cockroachdb/cockroach/proto

proto/api.pb.go:934: undefined: proto.Skip
proto/api.pb.go:1189: undefined: proto.Skip
proto/api.pb.go:1310: undefined: proto.Skip
proto/api.pb.go:1377: undefined: proto.Skip
proto/api.pb.go:1471: undefined: proto.Skip
proto/api.pb.go:1562: undefined: proto.Skip
proto/api.pb.go:1629: undefined: proto.Skip
proto/api.pb.go:1747: undefined: proto.Skip
proto/api.pb.go:1814: undefined: proto.Skip
proto/api.pb.go:1896: undefined: proto.Skip
proto/api.pb.go:1896: too many errors

**Comment by tschottdorf** [comment]
Maybe your dependencies are not as prescribed by our `GLOCKFILE`? Try running the following in the `cockroach` repository root:

`glock sync -n < GLOCKFILE`.

**Comment by hangyuancn** [comment]
I really appreciate for your help. Now I can build successfully.

By the way, can you help me get some material which can explain the glock and the GLOCKFILE format.

**Comment by tschottdorf** [comment]
We try to have an up-to-date onboarding guide here:
https://github.com/cockroachdb/cockroach/blob/master/CONTRIBUTING.md

If you find issues with it, we'd appreciate a PR. The Glock stuff should happen automagically if you use `make`.

To read up on Glock, [check out their docs](https://github.com/robfig/glock).

Best,
Tobias

**Comment by hangyuancn** [comment]
Thanks for your feedback.
You know I am from china, behind the Great Wall.
Actually, I manually downloaded some package and comment some lines in the GLOCKFILE before running the glock cmd and buiding. That's why the make didn't take effect.
