### ISSUE TITLE
storage: Reduce log spam from printing of command queue dependencies

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#14274]
When a command has been waiting in the command queue for a minute or more, we [print out a log message with some information that's meant to help us debug what's going on](https://github.com/cockroachdb/cockroach/blob/43f24c9042657448a0ad635b95099b75e478de41/pkg/storage/replica.go#L1736). Unfortunately, I think it prints a little too much.

On cobalt (#14250), there's a very large backlog (>60k) of commands blocked on a single key. This makes for quadratic growth of log lines, since each blocked command prints a line for each blocked command in front of it. This means that our configured 20 rotated 5MB files only covers about 3.5 hours worth of time, not nearly enough to go back to when the actual problem started.

We should somehow limit these log messages to a smaller size. For example, it looks like we print a separate line for each command blocked on the same key, when really just printing the number of commands blocked on that key would be nearly as useful with just a tiny fraction of the spam.

**Comment by a-robinson** [comment]
This came up again on another cluster and all I can say is that it's insanely annoying, as it rotates away all other (useful) logs. If someone has a quick fix, that'd be great, otherwise I'll take the time to learn a bit more about the command queue implementation and fix this sometime over the next few days.

**Comment by bdarnell** [comment]
A quick fix would be to change the `%s` in the printf string to `%.200s` to limit its length. You'd still have some quadratic behavior as a large string gets generated and discarded but it would quiet the logs.
