### ISSUE TITLE
storage: Transactions deadlock when reads follow writes

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#14276]
The test in https://forum.cockroachlabs.com/t/transactional-test-threads-stuck-on-selects/512/3 shows that when we have multiple transactions, each of which writes to a unique key, then scans the entire table, they deadlock. I theorized that the problem was that [this code](https://github.com/cockroachdb/cockroach/blob/43f24c9042657448a0ad635b95099b75e478de41/pkg/storage/store.go#L2630-L2634) was not setting the right push type for this case (a read within a transaction that has already written), but that didn't appear to fix the problem so either there is something else going on or my test was at fault. Here's my attempt at translating the test above to a KV-level test (to be run in the `storage_test` package):

```
func TestReadAfterWriteDeadlock(t *testing.T) {
	defer leaktest.AfterTest(t)()

	s, _, db := serverutils.StartServer(t, base.TestServerArgs{})
	defer s.Stopper().Stop()

	txns := []struct {
		attempts int
		key      roachpb.Key
	}{
		{key: roachpb.Key("a")},
		{key: roachpb.Key("b")},
	}
	endKey := roachpb.Key("z")
	var writeWG, readWG sync.WaitGroup
	writeWG.Add(len(txns))
	readWG.Add(len(txns))
	errCh := make(chan error, len(txns))

	for i := range txns {
		go func(i int) {
			errCh <- db.Txn(context.Background(),
				func(ctx context.Context, txn *client.Txn) error {
					txns[i].attempts++
					if err := txn.Put(ctx, txns[i].key, []byte("value")); err != nil {
						return err
					}
					if txns[i].attempts == 1 {
						writeWG.Done()
						writeWG.Wait()
					}
					_, err := txn.Scan(ctx, txns[0].key, endKey, 0)
					if txns[i].attempts == 1 {
						readWG.Done()
						readWG.Wait()
					}
					if err != nil {
						return err
					}
					return nil
				})
		}(i)
	}

	deadline := time.After(5 * time.Second)
	for _ = range txns {
		select {
		case err := <-errCh:
			if err != nil {
				t.Errorf("txn failed: %s", err)
			}
		case <-deadline:
			t.Fatalf("timed out")
		}
	}

	var totalAttempts int
	for _, txn := range txns {
		totalAttempts += txn.attempts
	}
	if totalAttempts <= len(txns) {
		t.Errorf("expected some txns to have multiple attempts, got %+v", txns)
	}
}
```

**Comment by spencerkimball** [comment]
This particular snippet of test code has problems only because of the read wait group, which prevents the first transaction to finish from continuing and ending the transaction, so everyone else is stuck in the push txn queue behind it.

The original problem posted to the forum was a result of the OP not using cursors correctly from the Python SQL client.
