### ISSUE TITLE
security: Support letsencrypt.org for certs on UI port

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#14272]
As long as we're going to be serving our web UI on a separate port from everything else, we might as well take advantage of this fact and use a different, more web-friendly certificate for this port. I haven't looked into what exactly this would involve, but if the node has an externally-visible hostname (and with some sort of opt-in) we should be able to get a letsencrypt.org certificate for the node to eliminate browser security warnings.

**Comment by mberhault** [comment]
That would be very convenient.

I think we have two major issues to address:
- generate and renew letsencrypt certificates. These are short lived (~90d) so frequent renewal is a fact
- pickup new certificates and use the right one based on external name used

If we implement a cert rotation mechanism (along the lines of #14254), we should be able to de-couple getting/renewing certificates from actually using them.
That would allow us to use existing letsencrypt utilities (and the many tools/plugins people are writing for it) and only worry about picking up and using new certificates. Integrating certificate request/renewal inside cockroach might be doable as well, but none of the authentication methods are great right now, requiring either privileged ports (`:80` or `:443`) or DNS changes.

**Comment by mberhault** [comment]
Quick update: using a separate cert/key pair for the UI will be easy to do with the new certificate manager:
* ui cert/key pair located at: `COCKROACH_CERTS_DIR/ui.{crt,key}`
* these can be symlinks to the letsencrypt chain and key
* fallback to `node.{crt,key}` if UI-specific pair is not found
* the system CA pool needs to be loaded in addition to our self-signed cert
* creation/renewal still needs to be done by letsencrypt, probably on a single node, then propagated to others

This may see some tweaks, but that's the general idea. I propose to keep this with a milestone of "later" and circle back after 1.0 when the certificate manager is fully fleshed out.

**Comment by petermattis** [comment]
This is a feature and we should do it, but not for 2.0.

**Comment by mberhault** [comment]
Duplicate of #26630

**Comment by telderfts** [comment]
If Cockroach is installed in Kubernetes then Certmanager can automatically rotate the cert using a custom cluster issuer.
