### ISSUE TITLE
build: teamcity releases are sometimes built with `-dirty` in the tag

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#14284]
The TeamCity release builds have a `-dirty` build tag injected, but TeamCity work trees should not be dirty. This seems to be a heisenbug: attempts to print out `git status` in the TC build configuration make the problem go away. I landed #14259 to sneak a `git status` into `scripts/teamcity-release-upload.sh`, but the problem has again disappeared.

Filing this issue to remind myself to reinvestigate.

/cc @mberhault

**Comment by bdarnell** [comment]
It happened for the 1.0-rc.1 mac builds.

```
Build Tag:    v1.0-rc.1-dirty
Build Time:   2017/05/01 18:31:33
Distribution: CCL
Platform:     darwin amd64
Go Version:   go1.8.1
C Compiler:   4.2.1 Compatible Clang 3.8.0 (tags/RELEASE_380/final)
Build SHA-1:  2d4d1ab5c42efb5accf73c9876e6ffd934fdc9e6
Build Type:   release
```

**Comment by tamird** [comment]
Are we still seeing this heisenbug?

**Comment by mberhault** [comment]
rc.2 doesn't have it. rc.1 did though.

**Comment by tamird** [comment]
Yeah, I think it was "fixed" by https://github.com/cockroachdb/cockroach/pull/15562.

**Comment by benesch** [comment]
Yup, not exactly a satisfying "solution." Figured I'd assign you to this as well, @tamird, just to keep it on your radar when it inevitably crops up in like v1.7 or whatever.

**Comment by tamird** [comment]
Closing as heisenbug.

**Comment by benesch** [comment]
Not convinced we've seen the last of it, but I guess it's been a while since we have.

**Comment by benesch** [comment]
This reoccured in v1.1-alpha.20170622.

**Comment by benesch** [comment]
https://teamcity.cockroachdb.com/viewLog.html?buildId=282702&buildTypeId=Cockroach_ReleaseBuild&tab=buildLog&_focus=123#_state=123
