### ISSUE TITLE
sql: retry errors report the wrong key if the table was created in the same txn

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#14282]
Found while investigating #14264
The txn there does `begin; create database; create table; insert; commit` and fails with:

```
pq: restart transaction: retry txn "sql txn" id=67fdee7f key=/Table/0/0 ...
```

(note the bogus `/Table/0/0` key in the msg)

Whereas if the `create database; create table;` are performed before `begin` (prior to the start of the txn) the same retry error is reported as:

```
pq: restart transaction: retry txn "sql txn" id=0181dd9a key=/Table/51/1/229294915573186561/0 ...
```

(i.e. with a valid key)

The question is 1) where is the bogus key name coming from 2) is that a problem?

cc @vivekmenezes @dt @danhhz

**Comment by dianasaur323** [comment]
@knz, assigning to you now for reassignment. We should figure out if this will be a problem, and if not, punt the investigation for 1.1. Currently setting as 1.0 for now though so that it doesn't fall through the cracks.

**Comment by knz** [comment]
@andreimatei do you know who is best placed to look at this?

**Comment by andreimatei** [comment]
I think any of us are as good as any other... I've removed the milestone; it doesn't worry me too much :).

**Comment by vivekmenezes** [comment]
assigning to myself because I'm making major changes in this area.

**Comment by bdarnell** [comment]
> 1) where is the bogus key name coming from

[Here](https://github.com/cockroachdb/cockroach/blob/72cb609b636ae4aa35d80f5a08d02c1d16aa2553/pkg/internal/client/txn.go#L267), which is called from various points in the sql layer related to schema changes. Since #16701, this key is printed as `/Table/SystemConfigSpan/Start` instead of `/Table/0/0`. 

> 2) is that a problem?

I don't think so. @andreimatei and @vivekmenezes is there anything you want to do here or can we close this issue?

**Comment by andreimatei** [comment]
Yeah, txns that perform schema changes are anchored in the "system config span" so that they trigger gossip.
No problems here AFAICS.
