### ISSUE TITLE
sql: column type "TIMESTAMP NULL DEFAULT NULL" not supported

### ISSUE THREAD

**Issue by arjunravinarayan** [cockroachdb/cockroach#14308]
The following DDL query, from the [OLTPBench TPC-C specification](https://github.com/oltpbenchmark/oltpbench/blob/master/src/com/oltpbenchmark/benchmarks/tpcc/ddls/tpcc-postgres-ddl.sql), runs in postgres:

```
CREATE TABLE order_line (
  ol_w_id int NOT NULL,
  ol_d_id int NOT NULL,
  ol_o_id int NOT NULL,
  ol_number int NOT NULL,
  ol_i_id int NOT NULL,
  ol_delivery_d timestamp NULL DEFAULT NULL,
  ol_amount decimal(6,2) NOT NULL,
  ol_supply_w_id int NOT NULL,
  ol_quantity decimal(2,0) NOT NULL,
  ol_dist_info char(24) NOT NULL,
  PRIMARY KEY (ol_w_id,ol_d_id,ol_o_id,ol_number)
)
```

but fails in cockroach with the following error:
`pq: incompatible type for DEFAULT expression: timestamp vs NULL`

@jordanlewis, can you please triage this to the relevant person? Thank you!

**Comment by arjunravinarayan** [comment]
I think all `DEFAULT NULL`s are unsupported, not just `TIMESTAMP`s. I'm getting this error when creating a table with a column with `INT DEFAULT NULL` as well (table `oorder` in the OLTPBench TPC-C DDL spec).

**Comment by jordanlewis** [comment]
We should just ignore `DEFAULT NULL` as I believe that's equivalent to having no `DEFAULT` statement at all.
