### ISSUE TITLE
ui: wrong format for the SQL Deletes metric

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#14316]
Noticed this on a cerulean node. Check out the `m` in the Deletes number, and notice how the line is plotted at 0 even though the value is not 0.

![screenshot 2017-03-22 14 08 48](https://cloud.githubusercontent.com/assets/377201/24214249/506db746-0f0b-11e7-8606-c7ce28a7c074.png)

**Comment by mrtracy** [comment]
Duplicate #12856

**Comment by bdarnell** [comment]
I think this is different from #12856. 

The `m` suffix means this is 33 milli-deletes per second, so the line is correct. It's a little silly to be using the `m` format in this context, though.

**Comment by mrtracy** [comment]
Ben is correct, this is a bug with metrix suffixes.
