### ISSUE TITLE
sql: don't fully double-encode decimals in indexes

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#14314]
Instead of fully encoding decimals twice in indexes, attempt to do something smarter like only encoding the number of truncated zeros in the composite index, and appending those to the indexed key.

See: https://github.com/cockroachdb/cockroach/pull/14208#issuecomment-288222839

**Comment by andreimatei** [comment]
@mjibson how come you closed this?

**Comment by mjibson** [comment]
It was a duplicate of #14575.
