### ISSUE TITLE
cli: show node that sql client is connected to

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#14310]
**Feature request**

 When you start the built-in sql shell, you get a welcome message with some simple tips:

```
root@load-balance-test-ubuntu-2gb-nyc3-02:~# cockroach sql --host=138.197.78.223 --port=26257 --insecure
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.
```

It'd be nice to add details about the node connected to. This would be especially useful when you are using a load balancer and want to validate that the connections are getting proxied to different nodes.

@arjunravinarayan

**Comment by jseldess** [comment]
Another approach would be to have some kind of session variable that you could query, like MySQL's [`wsrep_node_address`](http://galeracluster.com/documentation-webpages/mysqlwsrepoptions.html). Found reference to this [here](https://www.digitalocean.com/community/tutorials/how-to-balance-tcp-traffic-with-digitalocean-load-balancers#connecting-the-galera-cluster-through-the-load-balancer).

**Comment by arjunravinarayan** [comment]
I think the session variable is a superior system. Looking closely at how the welcome message is generated, it is generated locally (by the CLI tool) and is not sent across the network. It might be easiest to have a nodeID be generated only in response to a specific session variable being queried.

**Comment by jseldess** [comment]
@arjunravinarayan, updated the issue to be less prescriptive.

**Comment by knz** [comment]
You can query the virtual table `crdb_internal.node_build_info`. The first column gives you the node ID you're connected to.

**Comment by arjunravinarayan** [comment]
I do not see a `crdb_internal_node_build_info` table. 

```
root@:26257/crdb_internal> SET database = 'crdb_internal';
SET
root@:26257/crdb_internal> show tables;
+----------------+
|     Table      |
+----------------+
| app_stats      |
| build_info     |
| leases         |
| schema_changes |
| tables         |
+----------------+
(5 rows)
root@:26257/crdb_internal> SELECT * FROM node_build_info;
pq: table "node_build_info" does not exist
```

**Comment by knz** [comment]
The table is called `build_info` in your version. The name was changed two days ago, you'll pick the new name when you upgrade.

**Comment by arjunravinarayan** [comment]
Thank you! Just rebased, and it's there. 

`SELECT node_id FROM node_build_info` almost gets us there, it has far too many redundant columns. Is it safe to just do `SELECT node_id FROM node_build_info LIMIT 1`? Are we guaranteed that we're not going to have conflicting node IDs in this virtual table?

**Comment by knz** [comment]
`limit 1` is fine indeed. It's a `node_` table so guaranteed to be local with just one node ID. However I'd suggest keeping the issue open; I think providing an(other) interface to get to the node id is a good idea.

**Comment by arjunravinarayan** [comment]
do you suggest a built-in function?

**Comment by knz** [comment]
No, I suggest a session pseudo-variable which you can SHOW.

**Comment by jseldess** [comment]
In the meantime, I've used `SELECT node_id FROM crdb_internal.node_build_info LIMIT 1;` to see which node a load balancer redirects you to in our deployment docs: https://www.cockroachlabs.com/docs/manual-deployment.html#step-6-test-load-balancing. Thanks, @knz and @arjunravinarayan.

**Comment by knz** [comment]
`SHOW node_id` will now do the same.
