### ISSUE TITLE
cli: Improve UX around adding users related to certs

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/cockroach#14322]
At nwHacks, participants were confused about the relationship between users and certificate authentication.

I think we could improve the experience slightly with some guidance on the return if `cockroach user set` on secure clusters; something like "This user must authenticate with a certificate or password."

**Comment by mberhault** [comment]
We could add a message after setting user details, but I'm not sure this will be sufficient to explain the user of client certificates for authentication.
Rather, we still need users to read something like https://www.cockroachlabs.com/docs/stable/create-and-manage-users.html#user-authentication

**Comment by cuongdo** [comment]
Would it then be sufficient to add that link to the error message as well?

**Comment by mberhault** [comment]
I think this is more about general understanding of authentication rather than specific error messages.
We can tweak error messages to make it clear when things are secure vs insecure (eg: #17831), but at some point they need to read the docs.

**Comment by dianasaur323** [comment]
hmm... would you agree that perhaps this is a general question that we could expect people to have background knowledge on?

**Comment by mberhault** [comment]
@sploiselle: can you see if there's anything left to do here. I think it's more about making sure users read the docs, but I'm happy to tweak error messages.

**Comment by sploiselle** [comment]
I totally agree that at some point, people need to either read the docs or understand how authentication works. That being said, scaffolding user's understanding only helps with adoption.

My concrete recommendation here is this:

- If the user is added to a secure cluster with a password, we surface the following message:
    
    ~~~
    $(username) must authenticate access to the cluster with their client certificate or password.
    ~~~
- If the user is added to a secure cluster without a password, we surface the following message:
    
    ~~~
    $(username) must authenticate access to the cluster with their client certificate.
    ~~~

**Comment by sploiselle** [comment]
Following up on this @mberhault:

If you recommend users read the docs to ensure they use the feature correctly, I suggest linking to the docs page. Realized that we have included links to the docs site in numerous places already, so we've taken on the technical debt of maintaining the links. To somewhat alleviate your concerns about link rot, @knz has built tests to ensure we maintain link health.

**Comment by mberhault** [comment]
Ok, I'll tweak the messaging after `cockroach user` commands. Bumping to 1.2 though, this isn't critical enough for a cherrypick into 1.1.

**Comment by benesch** [comment]
Can we bump this to 2.1? Looks like it's too late for 2.0.

**Comment by knz** [comment]
Closing in favor of #33594.
