### ISSUE TITLE
ui: Capacity Used is shown as 100% when data can't be loaded from server

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#14326]
On a malfunctioning server where the admin UI is unable to get the data that it needs to populate the cluster overview page, it displays the store as 100% full. It'd probably be slightly better to leave the field blank in such a situation.

<img width="345" alt="screen shot 2017-03-22 at 5 04 13 pm" src="https://cloud.githubusercontent.com/assets/7085343/24220721/cc07e9e2-0f21-11e7-9809-89bb0d33e558.png">

**Comment by a-robinson** [comment]
@kuanluo

**Comment by kuanluo** [comment]
Interesting. Thanks for pointing this out, and agree with the suggestion. We can use "-" in this case. cc @mrtracy
