### ISSUE TITLE
cli: Improve UX for errors on `cockroach start`

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/cockroach#14323]
Right now the error message you receive for `cockroach start` is typically either:

```
Failed running "start"
```
or
```
Failed running "start"
Error: exit status 1
Failed running "start"
```

### Suggestion

We can easily improve the user experience by changing the error message to suggest adding the `--logtostderr` flag when it's not included and the node fails to start.

**Comment by bdarnell** [comment]
Related: #14318 and #14223

**Comment by knz** [comment]
Both #14318 and #14223 - in general the fatal messages and the errors are now properly reported, even when `--logtostderr` is not reported. Nothing to do here any more.
