### ISSUE TITLE
sql: the database name is still in use for a short time after DROP DATABASE

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#14332]
We allow caching of the database descriptors to allow us to locally map a database name to a database id. If it so happens that the database gets dropped, the system can very well be using an invalid cached entry and a user can use an incorrect database id to eventually reference a table. Even though the table is marked to be dropped, the local cached map entry might not get cleared in time before a new database/table with the same name is created. New rows inserted can use the old database/table descriptor and when the old table eventually gets dropped, these new rows will be dropped.

This same issue doesn't happen with DROP TABLE, because the table name can only be used once the name has been cleared from all caches. This problem can be solved by introducing leases on databases.

**Comment by jordanlewis** [comment]
@ajwerner @lucy-zhang this seems like something that would be fixed by database leasing, no? Feel free to close this if it's already represented by an other issue, or repurpose this issue as the database lease issue.
