### ISSUE TITLE
storage: Consider not allowing a replica's ID to change

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#14349]
For historical reasons, we allow a replica's ID change without it being GC'ed. If a request is received at a store for a range with a higher replica ID than the existing replica's ID, it discards its old raft RawNode and creates a new one with the new ID. This has tickled some bugs/races (#14193, #14231) and is fairly confusing.

We could instead reject messages to a replica that are for a higher ID, guaranteeing the ID will never change once it has been set. This would make the code simpler, but could lead to delays in up-replication if the GC queue is slow to remove the old replica ID for whatever reason.

Inspired by discussion in #14231 and #14348.

@tamird @bdarnell

**Comment by irfansharif** [comment]
> If a request is received at a store for a range with a higher replica ID than the existing replica's ID

When/how does this happen? i.e. if we have a store `s2` with a single range `r1` & replica ID `2`, when/how is a request generated addressing `s2,r1` with a `ToReplica` replica ID higher that `2`?

**Comment by tschottdorf** [comment]
If the cluster removes and then re-adds the replica on s2 before s2 replica-gcs it, that would happen.

**Comment by tbg** [comment]
Related: https://github.com/cockroachdb/cockroach/pull/35787 (introducing learners and removing preemptive snaps) and https://github.com/cockroachdb/cockroach/pull/34061 (better defined replica lifecycle).

**Comment by ajwerner** [comment]
Closed by #40892. :tada:
