### ISSUE TITLE
TestRangeIdempotence fails with multiple CPUs

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#1434]
repro:
```
for i in {0..10}; do go test -run TestRangeIdempotence -cpu 1,2 ./storage -timeout 15s; done
```

Subtask of #1406.

**Comment by bdarnell** [comment]
Instead of patching your local workspace, you can simply add `CPUS=1,2` to the end of your `make` invocation: `make PKG=./storage TESTS=TestRangeIdempotence CPUS=1,2`
