### ISSUE TITLE
distsql: support local aggregation in STDDEV, VARIANCE

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#14351]
Most aggregation functions support a local stage that performs an initial aggregation for the values on each node. For example, for SUM we can take the sum of all values on each node and sum those to get the final result:
![image](https://cloud.githubusercontent.com/assets/16544120/22517961/df942d1a-e878-11e6-9d23-cf13c705cce1.png)

For AVG, STDDEV, VARIANCE we don't do this; we need to extend the infrastructure to allow more than one intermediary value per function, with a final rendering expression. For AVG, we would have two values (sum and count), and after the final aggregation we would divide them to get the average. Similar solutions exist for STDDEV and VARIANCE.

This would be a great started project for someone because it touches a relatively small surface of distsql.

Update: we now support AVG and there is infrastructure for multiple intermediary values per function.

**Comment by RaduBerinde** [comment]
I'm going to implement this for `AVG` as it's fairly common.

**Comment by RaduBerinde** [comment]
AVG was implemented a while back, updating title.

**Comment by cuongdo** [comment]
is this making it into 1.1?

**Comment by RaduBerinde** [comment]
I don't think STDDEV and VARIANCE are priorities, bumping to 1.2.
