### ISSUE TITLE
sql: adding a column with a non-pure default doesn't work correctly

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#14352]
Adding a column to a table with a default expression that isn't a pure function works incorrectly: the expression seems to be evaluated once, and the resultant value inserted into every existing row. Observe the following interaction:

```
root@:26257/test> create table test (a int);
CREATE TABLE
root@:26257/test> insert into test values (1);
INSERT 1
root@:26257/test> insert into test values (2);
INSERT 1
root@:26257/test> alter table test add column b int not null default unique_rowid();
ALTER TABLE
root@:26257/test> select * from test;
+---+--------------------+
| a |         b          |
+---+--------------------+
| 1 | 230152696272355328 |
| 2 | 230152696272355328 |
+---+--------------------+
(2 rows)
```

The column backfiller should detect whether a default expression is pure or not. If it isn't pure, it needs to evaluate the expression once per row, not once total.

**Comment by dianasaur323** [comment]
@vivekmenezes perhaps a 1.0 issue that might leak over?
