### ISSUE TITLE
sql: Support Go ORM: go-pg

### ISSUE THREAD

**Issue by UnnoTed** [cockroachdb/cockroach#14379]
**FEATURE REQUEST**

Support for https://github.com/go-pg/pg
it is a ORM with focus on PostgreSQL's features and performance

GORM looks nice, but things are done better when they're focused in one⁽ᵒʳ ᵗʷᵒ⁾ thingˢ.
https://github.com/go-pg/pg/wiki/FAQ#why-go-pg

**Comment by jordanlewis** [comment]
Hi @UnnoTed, thanks for the suggestion! Have you gotten a chance to try `go-pg` against CockroachDB for yourself? It's possible that we already support a good deal of the required functionality.

**Comment by AdamJacobMuller** [comment]
I tested this slightly, connections seem to work but go-pg does not support certificate-based authentication so it only works with password based auth.

Schema creation appears to be the big thing. `go-pg` creates schema's assuming full (?) support for postgresql column types. I think the big one that was missing was jsonb support.

**Comment by yashsriv** [comment]
I'd like to add the fact that it mostly works perfectly for me now except for array types as go-pg sends array in the postgresql string syntax:

```
INSERT INTO a (arr) VALUES ('{"foo", "bar"}')
```

**Comment by jordanlewis** [comment]
Hey @yashsriv, we've lifted that limitation for the 19.2 release - please ping on this thread if you have other trouble.

**Comment by awoods187** [comment]
We believe Go ORM should work well with CockroachDB--let us know if you run into any issues.
