### ISSUE TITLE
util/log: syscall.Dup2 and syscall.Stderr are not windows compatible

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#14385]
In clog.go:926 both syscall.Dup2 and syscall.Stderr are both used and they are both not compatible with windows.  
Please find alternatives as this is preventing a clean windows build.

**Comment by vielmetti** [comment]
As noted in https://github.com/cockroachdb/cockroach/issues/14405 the lack of syscall.Dup2 is also an issue on linux-aarch64.

**Comment by knz** [comment]
Care to suggest alternatives?
We really want a means to redirect Go's low level error messages to the log file.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by petermattis** [comment]
Apparently `syscall.Dup3` exists: https://github.com/golang/go/issues/11981. Should be possible to use `Dup3` on ARM and `Dup2` otherwise.

**Comment by BramGruneir** [comment]
Or something windows specific:  https://stackoverflow.com/questions/34772012/capturing-panic-in-golang/34772516

**Comment by tamird** [comment]
Also note that Dup3 is Linux-only, while Dup2 is supported in BSD. So I think we can use Dup3 on Linux (not just ARM), whatever crazy windows stuff is required on windows, and Dup2 everywhere else.

**Comment by knz** [comment]
Dup2 is POSIX AFAIK.

I'd really like to know how Linux aarch64 manages to miss it. Unless it's not really Linux?

Windows 10 has a POSIX layer. Would be curious to know if we could just use that for windows support.

Nevertheless thanks for the windows hint I'll try to work something out based on that. 
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bdarnell** [comment]
Posix requires a C function `dup2`, but it's not specific about system calls. On linux aarch64, `dup2` is implemented in userspace (libc) in terms of the `dup3` system call. On architectures older than aarch64, a `dup2` system call is also provided for backwards compatibility. Go's `syscall` package only exposes real system calls, but it doesn't have any of the userspace/libc wrappers. 

https://groups.google.com/forum/#!topic/golang-dev/zpeFtN2z5Fc

**Comment by knz** [comment]
Oh excellent, so we can use build tags and cgo to pick what we need. Thanks for all the hints.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
