### ISSUE TITLE
security: syscall.Stdin is not compatible with Windows

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#14382]
In password.go lines 51 and 59, syscall.Stdin is used and this prevents cockroach from being compiled in windows.  Please find an alternative.

**Comment by petermattis** [comment]
@BramGruneir In the short term, I think you should work around these problems by creating stubs for the bits that don't work under Windows. For example, move `PromptForPassword` from `security/password.go` to `security/password_unix.go` and protect with an appropriate Go build tag and create a `security/password_windows.go` with a non-functional `PromptForPassword` that always panics.
