### ISSUE TITLE
util/timeutil: C.strptime is not compatible with windows

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#14383]
In conv.go, line 50, the C.strptime is used and this function is not compatible with windows, and is therefore preventing a clean windows build.  

Based on the comment on line 41, it looks like there was already some consideration of finding an alternative.  Please replace this function with something that is windows compatible.

**Comment by knz** [comment]
Got some hints from here: http://stackoverflow.com/questions/321849/strptime-equivalent-on-windows#3137634

```
#include <time.h>
#include <iomanip>
#include <sstream>

extern "C" char* strptime(const char* s,
                          const char* f,
                          struct tm* tm) {
  // Isn't the C++ standard lib nice? std::get_time is defined such that its
  // format parameters are the exact same as strptime. Of course, we have to
  // create a string stream first, and imbue it with the current C locale, and
  // we also have to make sure we return the right things if it fails, or
  // if it succeeds, but this is still far simpler an implementation than any
  // of the versions in any of the C standard libraries.
  std::istringstream input(s);
  input.imbue(std::locale(setlocale(LC_ALL, nullptr)));
  input >> std::get_time(tm, f);
  if (input.fail()) {
    return nullptr;
  }
  return (char*)(s + input.tellg());
}
```

**Comment by knz** [comment]
Wow so C++11 actually standardized get_time in the stdlib... :smile: 
http://www.cplusplus.com/reference/iomanip/get_time/
http://www.cplusplus.com/reference/locale/time_get/get/

**Comment by tamird** [comment]
Whoa, that's awesome.
