### ISSUE TITLE
sql: Better caching of database names

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#14386]
This trace of a slow query shows two lookups for the name `system`, to look up the `system.descriptor` and `system.lease` tables. We should be caching these lookups so we don't have to resolve the same database name twice in one query. 
![pasted image at 2017_03_22 02_03 pm](https://cloud.githubusercontent.com/assets/160562/24367798/f73707e2-12eb-11e7-9c76-4979def707e5.png)

**Comment by dianasaur323** [comment]
@cuongdo not sure who to assign this to. Seems like it might be low hanging fruit, but if not, let's move to 1.1.

**Comment by vivekmenezes** [comment]
assigning to myself because I'm making major changes in this area

**Comment by jordanlewis** [comment]
This doesn't seem like it's going to make it into 2.0, right @vivekmenezes?

**Comment by vivekmenezes** [comment]
fixed by #35555 

Thanks @knz !
