### ISSUE TITLE
all: windows build progress

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#14406]
I'm adding this issue to keep track of our progress in getting a functional windows build.

**Comment by BramGruneir** [comment]
cc: @petermattis @spencerkimball 
I'll keep this updated with our progress.

**Comment by spencerkimball** [comment]
Sounds like good progress! What happens when you run it? Can we run
unittests?

**Comment by tamird** [comment]
Running tests is tricky (because CCL doesn't build on Windows, due to the way it depends on `storage/engine`'s cgo symbols.

Looks like my logging patch is borked, so we're gonna need to fix https://github.com/cockroachdb/cockroach/issues/14385 before we can run tests.

**Comment by petermattis** [comment]
Why do we need CCL to run tests? Clearly we won't be able to run CCL tests, but others should work, right?

**Comment by tamird** [comment]
Yes, you just can't run `make test`, is all.

**Comment by dt** [comment]
could tag the ccl tree `!windows` as a stopgap -- by design, the rest of the tree doesn't import it.

**Comment by tamird** [comment]
Indeed, yet that's a lot of files to tag. It'd be lovely if there was a
better solution (perhaps even just extracting some common code and
`#include`ing it from both `db.cc`s).

**Comment by tamird** [comment]
We have our first test failures!
```
--- FAIL: TestReplicaStats (0.00s)
	replica_stats_test.go:161: 0: expected non-zero measurement duration, got: 0s
	replica_stats_test.go:161: 1: expected non-zero measurement duration, got: 0s
	replica_stats_test.go:161: 2: expected non-zero measurement duration, got: 0s
	replica_stats_test.go:161: 3: expected non-zero measurement duration, got: 0s
	replica_stats_test.go:161: 4: expected non-zero measurement duration, got: 0s
	replica_stats_test.go:161: 5: expected non-zero measurement duration, got: 0s
	replica_stats_test.go:161: 6: expected non-zero measurement duration, got: 0s
	replica_stats_test.go:161: 7: expected non-zero measurement duration, got: 0s
	replica_stats_test.go:161: 8: expected non-zero measurement duration, got: 0s
	replica_stats_test.go:161: 9: expected non-zero measurement duration, got: 0s
	replica_stats_test.go:161: 10: expected non-zero measurement duration, got: 0s
	replica_stats_test.go:161: 11: expected non-zero measurement duration, got: 0s
	replica_stats_test.go:161: 12: expected non-zero measurement duration, got: 0s
```

**Comment by BramGruneir** [comment]
Just a quick note, you can't run the cockroach exectable in dos until you tell dos that it is an executable, so  as a final step, 
In dos: `C:\Users\cockroach\go\src\github.com\corkroachdb\cockroach>rename cockroach corkroach.exe`

**Comment by BramGruneir** [comment]
Cockroach is running on Windows!
![image](https://cloud.githubusercontent.com/assets/1614265/24531715/dad9399a-1588-11e7-8810-b3638265f384.png)

Of course, not everything is working properly and it seems to be quite slow.  I've started filing issues against it with the tag Windows.  
https://github.com/cockroachdb/cockroach/labels/windows

**Comment by petermattis** [comment]
Woohoo!

**Comment by tamird** [comment]
Getting close. Almost all tests are passing. Current list:
```
--- FAIL: TestDumpRow (0.15s)
--- FAIL: TestDumpRandom (0.17s)
--- FAIL: TestDumpAsOf (0.14s)
FAIL
FAIL	github.com/cockroachdb/cockroach/pkg/cli	12.093s
--- FAIL: TestServerStartClock (0.08s)
--- FAIL: TestStatusLocalLogs (0.67s)
FAIL
FAIL	github.com/cockroachdb/cockroach/pkg/server	8.035s
--- FAIL: TestJobLogger (0.20s)
    --- FAIL: TestJobLogger/valid_job_lifecycles_succeed (0.02s)
    --- FAIL: TestJobLogger/succeeded_forces_fraction_completed_to_1.0 (0.02s)
FAIL
FAIL	github.com/cockroachdb/cockroach/pkg/sql	128.123s
--- FAIL: TestEval (0.04s)
FAIL
FAIL	github.com/cockroachdb/cockroach/pkg/sql/parser	0.856s
--- FAIL: TestReplicaStats (0.00s)
FAIL
FAIL	github.com/cockroachdb/cockroach/pkg/storage	46.603s
--- FAIL: TestConcurrentBatch (17.22s)
FAIL
FAIL	github.com/cockroachdb/cockroach/pkg/storage/engine	20.733s
--- FAIL: TestGetLogReader (0.02s)
    --- FAIL: TestGetLogReader/logtestexe.log (0.00s)
        --- FAIL: TestGetLogReader/logtestexe.log/restricted=true (0.00s)
        --- FAIL: TestGetLogReader/logtestexe.log/restricted=false (0.00s)
    --- FAIL: TestGetLogReader/cockroach.roach0.root.2015-09-25T19_24_19Z.00000.log (0.00s)
        --- FAIL: TestGetLogReader/cockroach.roach0.root.2015-09-25T19_24_19Z.00000.log/restricted=true (0.00s)
--- FAIL: TestGC (0.10s)
FAIL
FAIL	github.com/cockroachdb/cockroach/pkg/util/log	0.458s
--- FAIL: TestTimeConversion (0.00s)
FAIL
FAIL	github.com/cockroachdb/cockroach/pkg/util/timeutil	0.403s
```

`TestDump*`, `TestServerStartClock`, `TestJobLogger`, `TestReplicaStats` all have something to do with the system clock (@bdarnell suggested that its resolution may be too low).

`TestStatusLocalLogs`, `TestGetLogReader`, `TestGC` are likely all https://github.com/cockroachdb/cockroach/issues/14546.

`TestEval`, `TestTimeConversion` have to do with my shitty workaround for https://github.com/cockroachdb/cockroach/issues/14383.

`TestConcurrentBatch` is #14486, which is still present after I've built rocksdb with hardware crc32c and snappy.

**Comment by tamird** [comment]
Measuring clock resolution empirically on Windows and macOS:
```go
package main

import (
	"fmt"
	"time"
)

func main() {
	for i := 0; i < 10; i++ {
		now := time.Now()
		time.Sleep(time.Nanosecond)
		fmt.Printf("slept for %s\n", time.Since(now))
	}
}

```
On macOS:
```
slept for 7.22µs
slept for 2.515µs
slept for 1.969µs
slept for 573ns
slept for 1.801µs
slept for 1.428µs
slept for 1.897µs
slept for 1.477µs
slept for 624ns
slept for 650ns
```
on Windows:
```
go run foo/main.go
slept for 1.0005ms
slept for 2.0009ms
slept for 1.9993ms
slept for 1.0003ms
slept for 1.9992ms
slept for 1.0006ms
slept for 2ms
slept for 1.9999ms
slept for 2.0001ms
slept for 2.0002ms
```
I'm not yet sure why Windows' resolution is so bad, but it seems a fact that it is bad.

**Comment by petermattis** [comment]
Your code in https://github.com/cockroachdb/cockroach/issues/14406#issuecomment-291315535 isn't measuring clock resolution, but measuring the resolution of `time.Sleep`. I recall a time in the distant past when Linux was unable to accurately sleep for a duration less than 20ms. Perhaps Windows has something similar going on. Or perhaps the implementation of `time.Sleep` on Windows is using a mechanism with poor resolution.

**Comment by tamird** [comment]
Good point.

Another go:
```go
package main

import (
	"fmt"
	"time"
)

func main() {
	start := time.Now()
	for {
		if elapsed := time.Since(start); elapsed > 0 {
			fmt.Printf("resolution: %s\n", elapsed)
			break
		}
	}
}
```
Windows:
```
resolution: 1.0009ms
```
macOS:
```
resolution: 1.466µs
```

**Comment by bdarnell** [comment]
Windows has a few different timers: a [low-resolution one that returns wall time](https://www.python.org/dev/peps/pep-0418/#windows-timegettime) and two [high-resolution timers](https://www.python.org/dev/peps/pep-0418/#windows-queryperformancecounter) which are monotonic and relative to an unspecified base. I think go currently always uses the low-resolution wall-time clock, including for things like `time.Sleep`. I don't know if the monotonic clock work that is planned for go 1.9 will make this better.

The windows system clock resolution is adjustable, and [Go programs set it to 1ms](https://github.com/golang/go/issues/8687), which appears to be consistent with this result.

**Comment by tamird** [comment]
Yeah, so in Go 1.9 the monotonic part is populated by the interrupt timer. Go reads values straight out of memory: https://github.com/golang/go/blob/go1.8/src/runtime/os_windows.go#L581:L624

Looks like [more precise time-retrieval functions](https://msdn.microsoft.com/en-us/library/windows/desktop/dn553408(v=vs.85).aspx) were added in Windows 8:

> Windows 8, Windows 8.1, Windows Server 2012, and Windows Server 2012 R2 use TSCs as the basis for the performance counter. The TSC synchronization algorithm was significantly improved to better accommodate large systems with many processors. In addition, support for the new precise time-of-day API was added, which enables acquiring precise wall clock time stamps from the operating system. For more info, see GetSystemTimePreciseAsFileTime.

> When you need UTC-synchronized time stamps with a resolution of 1 microsecond or better, choose [`GetSystemTimePreciseAsFile`](https://msdn.microsoft.com/en-us/library/windows/desktop/hh706895(v=vs.85).aspx) Time or [`KeQuerySystemTimePrecise`](https://msdn.microsoft.com/en-us/library/windows/desktop/hh698269(v=vs.85).aspx).

But Go uses neither of these.

**Comment by tamird** [comment]
Incorporating some windows-specific code:
```go
package main

import (
	"fmt"
	"syscall"
	"time"
	"unsafe"
)

var (
	kernel32                           = syscall.MustLoadDLL("kernel32.dll")
	procGetSystemTimePreciseAsFileTime = kernel32.MustFindProc("GetSystemTimePreciseAsFileTime")
)

func GetSystemTimePreciseAsFileTime(time *syscall.Filetime) {
	syscall.Syscall(procGetSystemTimePreciseAsFileTime.Addr(), 1, uintptr(unsafe.Pointer(time)), 0, 0)
	return
}

func Now() time.Time {
	var ft syscall.Filetime
	GetSystemTimePreciseAsFileTime(&ft)
	return time.Unix(0, ft.Nanoseconds())
}

func main() {
	start := Now()
	for i := 0; i < 10; {
		now := Now()
		if elapsed := now.Sub(start); elapsed > 0 {
			start = now
			fmt.Printf("resolution: %s\n", elapsed)
			i++
		}
	}
}
```
We get a nicer result:
```
resolution: 500ns
resolution: 73.9µs
resolution: 9µs
resolution: 6.6µs
resolution: 6.7µs
resolution: 6.9µs
resolution: 7.2µs
resolution: 6.7µs
resolution: 7µs
resolution: 6.6µs
```
So...we may have to build with a custom Go runtime for Windows?

**Comment by bdarnell** [comment]
> So...we may have to build with a custom Go runtime for Windows?

Do we care about sub-millisecond timer resolution outside of a few tests?

**Comment by tamird** [comment]
Successfully built cockroach for windows on my gce worker:
```
C:\Users\tamird\Desktop>cockroach.exe version
Build Tag:    89cb2e2-dirty
Build Time:   2017/04/07 01:17:46
Distribution: OSS
Platform:     windows amd64
Go Version:   go1.8
C Compiler:   gcc 6.3.0
Build SHA-1:  89cb2e227744f21da9ff6de9b9c088395638ea0b
Build Type:   development
```
