### ISSUE TITLE
sql/parser: split EXPLAIN syntax nodes to permit finer-grained annotations

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#14415]
See https://github.com/cockroachdb/cockroach/pull/14188#issuecomment-289227895.

> EXPLAIN(DEBUG/TRACE) are unsafe, but the most common EXPLAIN(PLAN) isn't. Can I suggest that you file a follow-up issue to separate these into distinct syntax nodes, that can be marked separately for the purpose of your condition

We often find ourselves wanting to look at a syntax node to get a quick idea of what evaluating the syntax would entail. We also have a [pattern](https://github.com/cockroachdb/cockroach/blob/12e8530df71a1cb2762357590355b6e5bb2779e7/pkg/sql/parser/stmt.go#L77) of marking syntax nodes with different "annotation interfaces" for a similar purpose. Because the different EXPLAIN nodes have such different evaluation semantics, it would be very nice if they were split into different syntax nodes so that we could perform this syntax inspection at a finer granularity.

**Comment by knz** [comment]
Both EXPLAIN(TRACE) and EXPLAIN(DEBUG) are disappearing as per  #15948. No need to work on this.
