### ISSUE TITLE
sql: support distSQL with RETURNING NOTHING syntax

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#14412]
In the initial introduction of `RETURNING NOTHING` in #14188, we did not add support for DistSQL. This was mainly because `RETURNING NOTHING` only works with INSERT/UPDATE/and DELETE statements, none of which are supported by DistSQL at the moment. There were also a few races caught by the race detector when we attempted to interact with the shared `distSQLPlanner` concurrently. Still, we should keep interactions between the `Executor` and the classic and distributed planners symmetric.

**Comment by jordanlewis** [comment]
This was closed by #28590.
