### ISSUE TITLE
ui: "New Version Available" alert should not appear on builds without a proper build tag

### ISSUE THREAD

**Issue by mrtracy** [cockroachdb/cockroach#14427]
This is the same underlying issue as #13473, but this is specifically focused on the Admin UI alert resulting from a version mismatch.

Essentially, if the user is running a self-built binary without a proper build tag, they will constantly get the "New Version Available" alert. The system that determines if this alert should be displayed should *not* display the alert when running on a self-built binary.

**Comment by mrtracy** [comment]
This can be fixed after 1.0 because it should only affect dev builds, not official builds.

**Comment by mrtracy** [comment]
@benesch When I logged this issue, I wasn't aware that there was a registration server making this determination. Do you think this is still an issue?  Basically, if a cluster reports in with a self-built tag, does the version server return something?

**Comment by benesch** [comment]
It shouldn't, but let me verify!

**Comment by benesch** [comment]
Reg server is properly returning `[]` (no new versions) for dev builds. Closing!
