### ISSUE TITLE
build: reconsider use of -s and -w

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#14436]
See:

https://twitter.com/rakyll/status/846860908353634308
https://twitter.com/davecheney/status/846844080227213312
https://github.com/golang/go/issues/19753

**Comment by bdarnell** [comment]
Note that while we've only recently started using `-s` and `-w`, we had been using `strip` in our beta release binaries for a long time before that (see #14224), with no known issues. In the absence of more specific concerns with stripped binaries, I'm fine with continuing to do so.

**Comment by tamird** [comment]
That twitter conversation is a marvel of FUD.

**Comment by bdarnell** [comment]
It turns out that `-ldflags -s` is also a workaround for https://github.com/golang/go/issues/19741

**Comment by mjibson** [comment]
While it may be FUD, those are 2 pretty reliable sources. Dave's argument is that since it isn't tested it's not guaranteed to work. JBD doesn't have an argument, but is on the Go team, so worth considering. I don't think we need to change anything since we've been doing this (-s/-w or strip) for a while now without any visible problems, but we should keep track of that Go issue to see where it goes.

**Comment by bdarnell** [comment]
As a counterpoint, there's [this message from Russ Cox](https://groups.google.com/d/msg/golang-dev/ABppMOjYP6w/Sv-9SpUUAwAJ):

> To answer the original question, I don't think we have to do anything to "support" this, any more than we "support" readelf or objdump or anything else. We don't intentionally do anything that would make stripping a binary not OK, and strip has worked for the past five years or so. What didn't work was using -s with the linker (that is very different from invoking strip), and even that has worked for the past five years or so.
>
> I don't believe a test in all.bash is needed.

**Comment by tamird** [comment]
https://github.com/golang/go/commit/94c95d3e52ed55ef57e60ace559b684e4d5ebcbf
