### ISSUE TITLE
stability: leader-not-leaseholder alerts after liveness issues.

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#14444]
Seen on `catrina`, running `beta-20170323`.
This is running 3 nodes with very little load (sql queries from the url-shortener example).

Nodes 1 (`192.168.0.4`) and 2 (`192.168.0.5`) ran into trouble:

node 1:
```
I170329 09:44:17.534718 1997 vendor/google.golang.org/grpc/transport/http2_server.go:323  transport: http2Server.HandleStreams failed to read frame: read tcp 192.168.1.4:26257->192.168.1.5:50290: read: connection reset by peer
```

node 2:
```
E170329 09:44:17.513342 192 rpc/context.go:265  [n2] removing connection to cockroach-catrina-0001:26257 due to error: rpc error: code = DeadlineExceeded desc = context deadline exceeded
W170329 09:44:17.515152 215 storage/raft_transport.go:442  [n2] raft transport stream to node 1 failed: rpc error: code = Internal desc = transport is closing
W170329 09:44:17.516241 79 storage/node_liveness.go:293  [n2,hb] slow heartbeat took 9.0s
W170329 09:44:17.516409 79 storage/node_liveness.go:256  [n2,hb] failed node liveness heartbeat: result is ambiguous (sending to all 3 replicas failed; last error: rpc error: code = Internal desc = transport is closing, but RPC failure may have masked txn commit)
```

After this, node 2 went into a `E170329 09:44:55.386572 22080840 storage/replica_range_lease.go:194  [n2,s2,r160/2:/System/tsd/cr.node.sql.mon.…,@c4209a6700] heartbeat failed on epoch increment` loop, but then recovered.

At this point, the liveness counts are back to normal. 
However, node 3 is showing 4 leader-not-leaseholder ranges. I'm still trying to find which ones, there's so little traffic, nothing is stuck on them.

Logs for all three nodes from 9:40 until about 14:30:
[node1.txt](https://github.com/cockroachdb/cockroach/files/879497/node1.txt)
[node2.txt](https://github.com/cockroachdb/cockroach/files/879498/node2.txt)
[node3.txt](https://github.com/cockroachdb/cockroach/files/879499/node3.txt)

Be aware that catrina is firewalled. You can forward your local port 8080 to a specific node by doing:
```
crl-ssh catrina 1 -N -L 8080:localhost:8080
```

**Comment by spencerkimball** [comment]
We attempt to transfer the leadership if applicable when we quiesce. This may or may not succeed, but the range is quiesced regardless. Therefore we would expect those ranges to begin making contributions to the leader-not-leaseholder stats until they're unquiesced due to activity.

It's not an error to have leader-not-leaseholder count above 1. I think this alert should be removed, or else given some sort of threshold value. Make it a percentage of total range count if possible. Otherwise, just choose a reasonable constant, like 100.
