### ISSUE TITLE
sql: do not run an unnecessary column backfill for a non-nullable column without a default

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#14455]
The column backfill runs even when a column is configured without a default value. This is done to check if a non-nullable column is being added without a default to a non-empty table.

Instead of going via the distributed backfill to run this check it will be better to promote the column as a publicly visible column only if the said table is empty. This can be done while promoting the table to be publicly visible at the very end of the schema change process after the backfill phase.

An example of this is:

CREATE TABLE a ( a int PRIMARY KEY )
ALTER TABLE a ADD COLUMN b int NOT NULL

-- Will succeed since there's no data in the table

INSERT INTO a VALUES (1, 2)
ALTER TABLE a ADD COLUMN c int NOT NULL
-- Will fail since there *is* data in the table

We want the latter to fail without going through distributed backfill.

**Comment by cuongdo** [comment]
@jordanlewis @vivekmenezes how's this looking for 1.1?
