### ISSUE TITLE
build: checkdeps.sh allows unvendored packages when build fails

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#14451]
#14239 somehow got a green CI without including snappy in `vendor`.

One issue seems to be `|| true` in checkdeps.sh, introduced in 5b55a08be2fe58752dfc7fe88baf81bf0b6cdfdc, that let the script continue even though `go list` crashed on the bad import (https://teamcity.cockroachdb.com/viewLog.html?buildId=198562&buildTypeId=Cockroach_UnitTests_Depcheck&tab=buildLog#_state=116):
```
[12:32:52][Step 2/3] '
[12:32:53][Step 2/3] can't load package: pkg/rpc/snappy.go:21:2: cannot find package "github.com/golang/snappy" in any of:
[12:32:53][Step 2/3] 	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/golang/snappy (vendor tree)
[12:32:53][Step 2/3] 	/usr/local/go/src/github.com/golang/snappy (from $GOROOT)
[12:32:53][Step 2/3] 	/go/src/github.com/golang/snappy (from $GOPATH)
[12:32:53][Step 2/3] can't load package: pkg/rpc/snappy.go:21:2: cannot find package "github.com/golang/snappy" in any of:
[12:32:53][Step 2/3] 	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/golang/snappy (vendor tree)
[12:32:53][Step 2/3] 	/usr/local/go/src/github.com/golang/snappy (from $GOROOT)
[12:32:53][Step 2/3] 	/go/src/github.com/golang/snappy (from $GOPATH)
[12:32:53][Step 2/3] ++ true
[12:32:53][Step 2/3] + missing=
[12:32:53][Step 2/3] + '[' -n '' ']'
[12:32:53][Step 2/3] + echo 'all 3rd-party dependencies appear to be properly vendored.'
```

Interestingly, apparently the actual test runs though didn't fail to build ... somehow they got a copy of snappy in GOPATH?

**Comment by tamird** [comment]
Ah, of course the `|| true` ignores everything's exit code, not just `grep`'s.

Time to rewrite this one in Go as well?

**Comment by dt** [comment]
yeah, seems likely -- bash is the worst. I just wanted to record my initial digging here, since I'm not going to be working on it for next couple days.

**Comment by dt** [comment]
maybe a `2>&1` bandaid -- so the grep sees the crash output?

that said, I'd have expected the `test` build to fail to compile unless we `go get` somewhere -- I thought we didn't?

**Comment by tamird** [comment]
Isolation in our TC builds is non-existent - `go-test-teamcity`, for instance, is not subject to the normal vendoring rules, and neither is anything else that builds on those machines, like https://github.com/cockroachdb/loadgen. If any of those depend on golang/snappy, well, you get the point.

**Comment by tamird** [comment]
Perhaps @justinj is interested in learning about `go/build` this Friday?

**Comment by justinj** [comment]
👍 Very interested in learning about disparate parts of Cockroach, and I didn't have any plans for Friday, so that sounds good to me. @tamird can we talk on Friday (or earlier) so I can get an idea of what's going on/what's required?

**Comment by jordanlewis** [comment]
We expect that `vendor` contains everything we need to compile and test, right? If that's the case, I suggest modifying the builder image to stop mounting anything besides the `src/github.com/cockroachdb` and `pkg/github.com/cockroachdb` components of the GOPATH.

It's true that our TeamCity agents do not have good isolation, but that is exactly the reason why we have the builder image in the first place. The reason this is a problem is that we are allowing too much state to creep into the builder image's mount point from the host. If we were to remove that state, we would no longer have a problem here at all.

**Comment by tamird** [comment]
I like this idea, but it has the unfortunate side effect of preventing local experimentation with out-of-vendor packages.

For example, suppose I want to modify c-rocksdb and test it locally before going through all the trouble of updating the vendored copy - I may just `rm -rf vendor/github.com/cockroachdb/c-rocksdb` while I'm experimenting.

I still think this is a good idea, just pointing out this downside.

**Comment by jordanlewis** [comment]
Let's add a flag to `build/builder.sh` for your use case, then. Correct me if I'm wrong, but I don't think that this is a particularly common workflow that we need to protect from change.

I'll send a PR.

**Comment by petermattis** [comment]
Or add a `build/builder.sh` flag that only maps `github.com/cockroachdb/cockroach` for use by TeamCity. I frequently use `build/builder.sh` to be stuff outside of `github.com/cockroachdb/cockroach` (e.g. `build/builder.sh go build -o kv github.com/cockroachdb/loadgen/kv`).

**Comment by tamird** [comment]
I'd prefer the positive flag - meaning you have to explicitly opt in to get
the entire GOPATH mounted. I would wager that this will save some bug
reports.

Perhaps an environment variable rather than a flag, for those of us with
advanced use cases.

**Comment by petermattis** [comment]
> I'd prefer the positive flag - meaning you have to explicitly opt in to get the entire GOPATH mounted.

And I'd prefer the opposite. Don't move my cheese unless it is absolutely necessary and it doesn't seem necessary in this case.

>  I would wager that this will save some bug reports.

Bug reports from who?

**Comment by tamird** [comment]
Heh, it's my cheese too. Doesn't seem like a terrible inconvenience to me, and I was hoping to save @jordanlewis the trouble of changing TC scripts.

Either way is fine by me.

**Comment by petermattis** [comment]
Or we could make this automatic. Untested, so it probably doesn't work:

```diff
diff --git a/build/builder.sh b/build/builder.sh
index a41626d..51b710c 100755
--- a/build/builder.sh
+++ b/build/builder.sh
@@ -110,7 +110,13 @@ mkdir -p "${host_home}"/.yarn-cache
 vols=""
 vols="${vols} --volume=${passwd_file}:/etc/passwd"
 vols="${vols} --volume=${host_home}:${container_home}"
-vols="${vols} --volume=${gopath0}/src:/go/src"
+if [ "$1" = "make" ]; then
+  # If we're building cockroach then limit the source we map in to the
+  # builder.
+  vols="${vols} --volume=${gopath0}/src/github.com/cockroachdb/cockroach:/go/src/github.com/cockroachdb/cockroach"
+else
+  vols="${vols} --volume=${gopath0}/src:/go/src"
+fi
 vols="${vols} --volume=${gocache}/pkg/docker_amd64:/go/pkg/linux_amd64"
 vols="${vols} --volume=${gocache}/pkg/docker_amd64_msan:/go/pkg/linux_amd64_msan"
 vols="${vols} --volume=${gocache}/pkg/docker_amd64_musl:/go/pkg/linux_amd64_musl"
```

**Comment by dt** [comment]
after #14454, we can just delete everything after the `glide i && git diff` part of checkdeps.sh 🎉

**Comment by dt** [comment]
#14454
