### ISSUE TITLE
backup/restore: local filesystem backup/restore target potentially confusing ux

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#14453]
BACKUP and RESTORE generally assume nodes are interchangeable, so using their local disks doesn't  make much sense (on BACKUP, the backup would end up fragmented across nodes, and restore can't assume a particular node restores particular range so they all need the whole thing at their disposal).

Additionally, there's some risk of confusion around the fact that it references the node's file system, not the client's.

Supporting local paths could be useful when they're backed by NFS or something similar, or in single-node testing, but maybe we should try to make it less easy to use them incorrectly.

**Comment by dt** [comment]
+cc @arjunravinarayan @sploiselle @danhhz

**Comment by dt** [comment]
one easy option might be just to change the scheme for local file to `nodelocal://` or something?

**Comment by arjunravinarayan** [comment]
Would it be possible to indicate _which_ node the data is on? If I can say "node1://mnt/data1/bkp_foo" then I'd be happy. The usual way that I can imagine people using node local file system backups are to dump and copy them off of a single machine, so if we could just indicate that that would be good enough for me.

**Comment by dt** [comment]
AFAIK, we're not implementing an inter-node filesystem any time soon -- fire up an a little HTTP server on `node1` and use `http://node1/...` if you want that behavior.

**Comment by arjunravinarayan** [comment]
That's actually a great suggestion, and one we should document somewhere.

**Comment by danhhz** [comment]
I agree with all of this. 1) this should be harder to mess up 2) we shouldn't be shuttling files around between nodes 3) let's document patterns we expect to be useful (including nfs and this http trick)

**Comment by dt** [comment]
I think my vote for 1) -- make it harder to mess up -- would be to use a uri scheme that makes it clearer what it is. yes, being something other than "file://" or the lack of an explicit scheme means it is less discoverable and you'd need to consult the docs to find it, but that might actually be a good thing: that gives us the chance to point out that it _probably_ isn't what you want.

**Comment by danhhz** [comment]
`nodelocal://` sounds fine to me. it's better to be strict now and soften later if users find it too limiting
