### ISSUE TITLE
beta-20170330

### ISSUE THREAD

**Issue by eisenstatdavid** [cockroachdb/cockroach#14450]
The candidate SHA is f0f5783cc67f9cda16cedf1b88ca0691b0b65884.
Deployed to `adriatic`, `blue`, `cerulean` (race build), and `omega`.

[Release process checklist](https://github.com/cockroachdb/cockroach/wiki/Release-Process)
- [x] Check and verify cluster status
- [x] Tag release and push tag
- [x] [Trigger release build](https://teamcity.cockroachdb.com/viewType.html?buildTypeId=Cockroach_MergeToMaster)
- [x] Check and verify binaries
- [x] Announce version to the registration cluster - see internal production instructions
- [x] Update the [Homebrew tap](/cockroachdb/homebrew-cockroach)
- [x] Update docs
- [ ] External communications for release

**Comment by dianasaur323** [comment]
I'm going to close this out now!
