### ISSUE TITLE
storage: Writes in command queue for `[/Meta1/"",Max)`

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#14460]
A test cluster with a large number of ranges is experiencing a large backlog in the command queue. In the logs we see a lot of operations in the command queue for range 1, including both read *and write* operations for the range `[/Meta1/"",/Max)`. The reads on this key span are expected (they're issued by the DistSender to look up range metadata), but I can't think of any reason for there to be writes with this span. There are a lot more writes than reads, and they appear to be standing in the way of necessary metadata lookups. 

```
W170328 18:20:31.325888 522366 storage/replica.go:1781  [n1,s1,r1/14:/M{in-eta2/Table/…},@c4203f8e00] have been waiting 1m0s for dependencies: cmds:
[{global:<nil> local:<nil>} {global:0xc5ded26000 local:0xc428aaeb80}]
global:
  65965 readonly [/Meta1/"",/Max)
  65974 readonly [/Meta1/"",/Max)
  65983 readonly [/Meta1/"",/Max)
  65986 readonly [/Meta1/"",/Max)
  65989 readonly [/Meta1/"",/Max)
  65998 readonly [/Meta1/"",/Max)
  65988 readonly [/Meta2/Table/99/1/-8671299324475040254)
  65997 readonly [/Meta2/Table/99/1/-7699206137365604611)
  65964 readonly [/Meta2/Table/99/1/-553994299767263530)
  65973 readonly [/Meta2/Table/99/1/-333243783118308863)
  65982 readonly [/Meta2/Table/99/1/151033392650629945)
  65985 readonly [/Meta2/Table/99/1/3656861351929005903)
  65959 [/Meta1/"",/Max)
  65962 [/Meta1/"",/Max)
  65968 [/Meta1/"",/Max)
  65971 [/Meta1/"",/Max)
  65977 [/Meta1/"",/Max)
  65980 [/Meta1/"",/Max)
  65992 [/Meta1/"",/Max)
  65995 [/Meta1/"",/Max)
  66001 [/Meta1/"",/Max)
  66004 [/Meta1/"",/Max)
  66007 [/Meta1/"",/Max)
  66010 [/Meta1/"",/Max)
…
```

**Comment by petermattis** [comment]
What write operation hits the span `[/Meta1/"",/Max]` on a range that has the span `[/Min,/Meta2/Table/...]`? That seems odd. Or is something wrong with our debug output where those are actually point operations?

**Comment by petermattis** [comment]
Point operations don't specify the end key. We can see this in the above output: `65985 readonly [/Meta2/Table/99/1/3656861351929005903)`. So what operation is adding write spans for `[/Meta1/"",/Max]`?

**Comment by petermattis** [comment]
Cc @spencerkimball

**Comment by spencerkimball** [comment]
@bdarnell the range descriptor does `RangeLookup` requests with `ReadConsistency = INCONSISTENT`, which means it bypasses the command queue entirely, so I don't believe any of these spans implicates the range descriptor cache. @petermattis just suggested that perhaps the user experiencing this problem has prop eval kv enabled, which could be inserting that kind of a span for both reads and writes.

**Comment by bdarnell** [comment]
Ah, yeah, it could be propEvalKV because `LocalMax` and `Meta1Prefix` are the same.

**Comment by a-robinson** [comment]
Is there anything to be done here? It seems as though it was just due to propEvalKV.

**Comment by bdarnell** [comment]
Yeah, the writes in the command queue are probably just propEvalKV. We may need to do other investigations into what exactly happens with very large numbers of ranges (and splits in the meta2 span), but I guess that's a separate issue and we need to verify whether there's a problem at all without propEvalKV.
