### ISSUE TITLE
ui,distsql: backend statement execution latency graphs don't match tpch stats

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#14478]
Build: e193b7c

I'm running four instances of this in a loop against a 6-node cluster:

`./tpch -queries=1`

`tpch` is reporting that each query takes ~150s. This is vastly different from what the admin UI is reporting when viewing any node:

<img width="1210" alt="screenshot 2017-03-30 13 43 43" src="https://cloud.githubusercontent.com/assets/1564582/24518275/5df5f6ae-154f-11e7-990a-e0b41c5ce6b9.png">

It's unclear where this 10.2 second figure is coming from. TPC-H query 1 is the only SQL query that's running right now (except for maybe admin UI stuff, but that shouldn't take anywhere near 10s).

**Comment by bdarnell** [comment]
"Backend statement execution" is measured at KV/RPC level, not SQL (we should probably change that caption).

**Comment by cuongdo** [comment]
What is a better label for this? "KV/RPC Execution Latency"?

On the other hand, it may not make sense to have a different KV/RPC latency graph for just DistSQL.

**Comment by mrtracy** [comment]
Assigning to @cuongdo, this doesn't appear to be a bug in the UI code itself, rather a mislabeled metric and a possible blind spot.

**Comment by cuongdo** [comment]
reassigning to @couchand since you're already looking at DistSQL metrics

**Comment by couchand** [comment]
It doesn't look like this chart exists anymore, or else the label's already been updated.  We can open a new issue if specific concerns with the latency measurements are uncovered.
