### ISSUE TITLE
storage/engine: TestConcurrentBatch takes a long time to complete on windows

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#14486]
When running In Windows, TestConcurrentBath takes upwards of 16s to complete. A special case has been added to deal allow more time in the test, but the root cause should be investigated.

**Comment by tamird** [comment]
How long does it take on not-Windows?

**Comment by BramGruneir** [comment]
--- PASS: TestConcurrentBatch (1.64s)

**Comment by tamird** [comment]
Well, that seems bad enough on windows that we might want to investigate before merging #14488.

**Comment by petermattis** [comment]
I told @BramGruneir the temporary workaround was fine. Let's find the next problem and then circle back to this when the tests are all passing.

**Comment by tamird** [comment]
Fixed by #14840.
