### ISSUE TITLE
distsql: fill in some distsqlrun.Error fields for better debugging

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#14503]
#14025 add a distsqlrun.Error type to distsql protobufs. There are two fields ```NodeID``` and ```authoritative``` that are not filled in. It will also be nice to add in new fields ```ProcessorID``` and perhaps ```StreamID``` .

**Comment by dianasaur323** [comment]
assigning to @arjunravinarayan for now, but feel free to re-assign. I think we can probably wait to do this in our 1.1, but move if you disagree.

**Comment by arjunravinarayan** [comment]
This isn't going to make it into 1.1. It's not completely clear to me what the motivation is as I haven't seen the need for this while debugging various DistSQL problems over this past release cycle, so we should scope this out precisely and address it early in the next release cycle, under the bucket of addressing technical debt.

@asubiotto you previously thumbs-uped this. Just wanted to ping you if you had anything to add to the description to help me triage here. Feel free to ignore this if you don't have anything in particular.

**Comment by jordanlewis** [comment]
This has probably lost its relevance.
