### ISSUE TITLE
perf: RocksDB block cache grows over time

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#14512]
The RocksDB block cache will eventually grow over time to reach its configured limit, even in an idle cluster. This is a combination of our time-series data storage and the fact that RocksDB does not purge old data from the cache until it reaches its memory limit, so the cache can use more memory than the on-disk storage (because it holds data for sstables that have been compacted away). This is surprising and results in a lot of user reactions like "CockroachDB is leaking memory! I started a node, forgot about it for a week, and now it's using 6GB of RAM".

I'm filing this issue in part to give us a canonical thread to point to for this issue, and also to discuss things that we might do to make it better. Possible mitigations include
- Document this issue more prominently and encourage running with a reduced `--cache-size` flag and/or in a memory-limited cgroup (the latter would also reduce the sql memory budget and give us more flexibility to tweak memory allocation between different pools in the future, but it appears to be more complicated)
- Change the default cache size. The current default of 25% of physical memory (or the cgroup limit) was chosen on the assumption that cockroach would have the machine to itself. Maybe it's more important to avoid excessive memory consumption when there's other stuff on the machine than to maximize the cache size on dedicated machines. This shifts the burden so that deployments on dedicated machines would need to set `--cache-size` for best performance. (we should probably also benchmark different cache sizes to see how much it matters)
- Change RocksDB to purge compacted sstables from the block cache. This would still allow the cache to grow over time to its full limit, but it would slow the growth and limit the size of the cache to the size of data on disk.
- Change RocksDB to preallocate the entire block cache at startup. This will make the issue of cache size more visible and make it clear that it's a fixed-size cache instead of a leak.

**Comment by petermattis** [comment]
> Change RocksDB to purge compacted sstables from the block cache. This would still allow the cache to grow over time to its full limit, but it would slow the growth and limit the size of the cache to the size of data on disk.

I did some investigation into this a few weeks ago. We can hook in and receive notification when an sstable is deleted, but there is no easy means of then telling the cache to delete all the blocks from that sstable. I think doing this would require changes to RocksDB.

> Change RocksDB to preallocate the entire block cache at startup. This will make the issue of cache size more visible and make it clear that it's a fixed-size cache instead of a leak.

I think this might be doable by wrapping RocksDB `LRUCache` and `LRUCacheShard`. I didn't explore in depth, though. There might need to be changes to RocksDB to accomplish this as well.

> Change the default cache size. 

This would be my preference for the short term.

**Comment by petermattis** [comment]
> Change the default cache size.

Also note that the default of 25% of physical memory might be low for a dedicated machine.

**Comment by bdarnell** [comment]
> Also note that the default of 25% of physical memory might be low for a dedicated machine.

Yeah. We set this value before a lot of work was done on controlling the memory usage for SQL and raft snapshots, so we needed to allow a lot of room for bursts in other memory usage. Now it's feasible to raise the limit. 

Instead of encouraging use of the `--cache-size` flag we may want to introduce a new `--memory-limit` flag (that would override the use of physical/cgroup memory) so we can continue to tweak the percentage allocations of different consumers of memory without needing users to change their configurations as much.

**Comment by petermattis** [comment]
The RocksDB cache size is dynamically adjustable. I wonder if we can have a heuristic that shrinks the cache size when there is little or no traffic and raises it when there is.

**Comment by petermattis** [comment]
The RocksDB folks are unlikely to fix this upstream any time soon (https://github.com/facebook/rocksdb/issues/2391). Either we try to fix it ourself in RocksDB, or we add some idle cluster/node heuristic which temporarily sets the cache size to 0, thus purging it of any unused block.

**Comment by petermattis** [comment]
@bdarnell Do you have any new thoughts on changing the default `--cache-size` to be a fixed value? I think that is the only mitigation we can do in the 1.1 time frame.

**Comment by bdarnell** [comment]
To what fixed value? Setting it higher than 512MB would probably cause problems on machines with our minimum hardware requirements of 2GB ram, and that seems way too low for a production service. Is the intention that any serious production user would need to start setting the cache size explicitly?

**Comment by petermattis** [comment]
I was thinking `256MiB`. Yes, the intention would be that any serious production user would need to start setting the cache size explicitly. We might want to warn about this in the UI which suggests we should hold off on doing anything for 1.1.

**Comment by bdarnell** [comment]
Have we done any benchmarking to show the impact of the smaller cache size? I think I'd rather go ahead and make the change now than do it in 1.2, even if that would allow us to make some UI updates to go along with it (it's only going to get harder to change as we have more production users).

Instead of defaulting `--cache` to 256MiB, I think I'd prefer to introduce a flag like `--total-memory` defaulting to 1GiB. That way we can adjust the recommended memory proportions in the future without asking people to update a bunch of flags every time (we currently keep a lot of memory unassigned to allow for various kinds of spikes; as we bring these spikes under control we'll probably want to allow more memory to go to cache).

**Comment by petermattis** [comment]
No, I haven't done any benchmark on the effect of the cache size. 

A `--total-memory` flag sounds nice. We could carve off the range descriptor cache, leaseholder cache, timestamp cache and raft entry cache. The downside is that it wouldn't be a strict limit. Also, getting tight to get this right for 1.1.

**Comment by petermattis** [comment]
> Have we done any benchmarking to show the impact of the smaller cache size? 

I just ran an accidental experiment where the cache size was 0 (see #17975). The performance impact was in the 5-10% range for `kv --read-percent 95`. That's quite a bit smaller than I expected. I'm going to run some additional tests to validate this, but if that number holds up it argues strongly for a smaller default `--cache-size` setting.

**Comment by petermattis** [comment]
Actually, #17975 resulted in the default block cache size which is 8MB, not 0.

**Comment by petermattis** [comment]
Another option: we could place the timeseries data in a separate column family. Each column family can have a separate cache and we would configure a much smaller cache for the timeseries column family. Somewhat onerous to do a migration, but feasible for a newly created store. Also seems like quite a bit of work to avoid this memory growth, but tossing it out there is a possibility.

**Comment by bdarnell** [comment]
Given that accidental experiment, setting a small fixed default for 1.1 makes sense to me (I'd go with 128MiB). We can postpone refactoring to something like `--total-memory` instead f `--cache` until later.

**Comment by petermattis** [comment]
Ok. I need to re-run that experiment in a non-accidental setting. I'll try with the default `--cache-size` vs `--cache-size=128MiB`.

**Comment by petermattis** [comment]
Running `kv --read-percent=0 --splits=1000 --concurrency=384` on a 6-node cluster:

```
_____N__ops/sec(1)__ops/sec(2)_____delta
   384     16398.5     17508.9     6.77%
```

The `ops/sec(1)` run corresponds to `--cache-size=128MiB` while the `ops/sec(2)` run corresponds to the default cache size which on the machines tested is `6.9GiB`. 

Graphs from the `--cache-size=128MiB` run:

<img width="922" alt="screen shot 2017-08-29 at 3 57 47 pm" src="https://user-images.githubusercontent.com/6201335/29845742-03c94f2c-8ce2-11e7-9669-ec4abfbfcf32.png">
<img width="923" alt="screen shot 2017-08-29 at 3 57 58 pm" src="https://user-images.githubusercontent.com/6201335/29845743-03e79ee6-8ce2-11e7-9328-4db4802ed6d9.png">

And the `--cache-size=6.9GiB` run:

<img width="922" alt="screen shot 2017-08-29 at 4 58 55 pm" src="https://user-images.githubusercontent.com/6201335/29845758-12786ba2-8ce2-11e7-9881-f1c35f83aebc.png">
<img width="920" alt="screen shot 2017-08-29 at 4 58 46 pm" src="https://user-images.githubusercontent.com/6201335/29845761-15d66fb0-8ce2-11e7-9a73-0c877769d1c2.png">

Note that a write-only workload does reads on every write in order to maintain the range-level MVCC stats, but those are most likely hitting the filter blocks (which are pinned in the cache) since we're not overwriting keys. Also, with the `--cache-size=128MiB` setting, we're not actually reading from disk, but from the OS buffer cache. I'll try another test with a workload involving reads.

**Comment by petermattis** [comment]
A read-heavy workload (`kv --read-percent 95 --concurrency 384`) on the same 6-node cluster as above and pre-populated with the same data (~6.25GiB) shows a much bigger effect from a smaller cache size. 

```
_____N__ops/sec(1)__ops/sec(2)_____delta
   384     34330.9     48105.0     40.1%
```

The first 5 mins in the graphs below are with a `--cache=128MiB`. The second 5 mins are with `--cache=6.9GiB`.

<img width="934" alt="screen shot 2017-08-29 at 9 11 38 pm" src="https://user-images.githubusercontent.com/6201335/29850877-ae1e786e-8cfe-11e7-811d-cdf89228f09e.png">
<img width="933" alt="screen shot 2017-08-29 at 9 11 28 pm" src="https://user-images.githubusercontent.com/6201335/29850876-ae1dbdca-8cfe-11e7-8beb-b3025ff255f3.png">

**Comment by petermattis** [comment]
@bdarnell Thoughts? There is a big performance win from a large cache size for reads, though I'd point out that Postgres defaults to 128MB.

**Comment by bdarnell** [comment]
Why such a big change from https://github.com/cockroachdb/cockroach/issues/14512#issuecomment-325475752 where you saw 5-10% slowdown in the 95%-read case? Was that test actually write-only?

With that much of a performance difference, it looks like we're not going to be able to set a default that always works and some class of users will be more or less required to set `--cache` to get reasonable behavior. We can either default to a small cache and production users will need to increase it to get good performance, or default to a large cache and development users will need to decrease it to avoid eating up all their memory. I think I'd lean towards the smaller default because the consequences of a too-small cache are less sever than a too-large one, although it bothers me that once we start recommending that all production users set `--cache`, we're probably going to have to recommend changes to it in future releases.

**Comment by petermattis** [comment]
> Why such a big change from #14512 (comment) where you saw 5-10% slowdown in the 95%-read case? Was that test actually write-only?

The test run in #14512 were short enough that the data still mostly fit in cache even at the reduced size.

@mrtracy How difficult is it to add a warning banner to the UI when a node's configured cache size is the default?

**Comment by mrtracy** [comment]
Adding a banner isn't too difficult; the possibly difficult part is fetching the data needed to determine if the warning should display or not.  If you're just looking at a cluster setting and comparing it to a constant, that's very easy, we just need an API for the UI to load that setting and inspect it.

**Comment by petermattis** [comment]
@mrtracy Would adding a new endpoint make sense? Since `--cache` is a per-node setting, I was thinking of adding a field to `NodeStatus`.

**Comment by mrtracy** [comment]
That works as well, it does seem aligned with the other information on NodeStatus.
