### ISSUE TITLE
storage: revisit TimestampCache eviction policy

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#14518]
Internally, the `TimestampCache` has 3 caches: a read interval cache, a write interval cache and a request cache. The combined size of the caches is limited to `TimestampCache.maxBytes`, but the eviction from the caches is funky: we only evict from one of the sub-caches when inserting into it. For example, `TimestampCache.AddRequest` is the only place we evict from the request cache.

I'm not certain that this behavior is problematic, though it seems odd that inserting into the read interval cache might push `TimestampCache.bytes` over the `maxBytes` threshold, but not result in anything being evicted because all of the memory is consumed in the write interval cache.

**Comment by petermattis** [comment]
We could change `TimestampCache.{r,w}cache` into interval trees and perform the cache maintenance and eviction in `TimestampCache`. Might be doable cleanly via some reorganization of `cache.baseCache`, though I haven't thought about it too much. This doesn't seem particularly urgent, though.

**Comment by nvanbenschoten** [comment]
Closed by #20232.
