### ISSUE TITLE
clean up error handling / nil receivers

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#1454]
all methods defined on receivers which implement `error` (and some others, within reason, but let's start with errors) need to handle `nil` receivers well.

see the discussion in #1445.

**Comment by bdarnell** [comment]
I don't think they should handle nil receivers; in general we probably should panic if we call these methods on a nil receiver. My point from the other thread is that *if* we ever deliberately returned nil pointers wrapped in a non-nil error interface value *then* we'd need to handle nil receivers instead of expecting callers to do a second nil check.

**Comment by spencerkimball** [comment]
My vote is not to go overboard here. These kinds of patterns can become heavier than just the normal nil pointer exceptions they're trying to obviate.

**Comment by tschottdorf** [comment]
I don't want to add assertions everywhere, but I want to put the assumption on solid footing that any non-nil error is an error and behaves like an error (and the same for some of the interfaces we've glued around error handling), regardless of whether that can happen in practice. The way we currently do it is based on the implicit rule that we don't return nil pointers as interfaces, which can't be looked up. Once the implementations handle nil correctly (and that can be stated in the interface's comment so a lookup at the site of the type assertion easily finds it) that problem is gone, and we don't need to check the result of those assertions against `nil`. Only a small number of local changes are required, so where's the problem?

Returning those nil interface pointers can actually happen in practice (I remember suggesting an edit to @spencerkimball once which would've introduced one erroneously), but it should be exceedingly rare and an obvious problem in practice if it did (as far as I can tell the only way to get there is defining an interface nil pointer value for an error which is filled when an actual error occurs).

**Comment by spencerkimball** [comment]
This is a subtle problem and the solution is going to be somewhat arbitrary in the sense that people will forever be wondering why we have a hard and fast rule that error implementations must handle nil receivers.

My feeling is a rule of thumb should be applied here: if the problem isn't actually a problem in practice, don't introduce new process and tools to fix it.

Is this a problem in practice?

**Comment by tschottdorf** [comment]
I don't think this is a priority any time soon (and may never be).
