### ISSUE TITLE
engineccl: make MultiIterator match the new engine.Iterator interface

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#14558]
It changed in https://github.com/cockroachdb/cockroach/pull/14549

Also, this is apparently more brittle than I guessed. Consider doing the SimpleIterator TODO

**Comment by danhhz** [comment]
same goes for MVCCIncrementalIterator

**Comment by tschottdorf** [comment]
@danhhz this is done now, right? Or at least something related to this was done. Can you comment?

**Comment by danhhz** [comment]
Yup. Done in https://github.com/cockroachdb/cockroach/pull/16614
