### ISSUE TITLE
debug: "grpc: the client connection is closing" error on raft debug page

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#14559]
I was trying to check out which system range had bit the dust on indigo by going to the `/_status/raft` debug page when I hit the above error. I get the same error every time I retry as well, so apparently the client connection isn't closing very quickly.

Looks like a misuse of a dial timeout judging by https://github.com/grpc/grpc-go/issues/133, but do you know anything about this @tamird?

**Comment by tamird** [comment]
I don't know anything about this off the top of my head. Visiting https://indigo.crdb.io:8080/_status/raft produces output for me, albeit slowly. What's the task here, exactly?

**Comment by a-robinson** [comment]
There isn't much actionable now that the cluster is healthy again. The unexpected behavior was that the page was consistently returning the "grpc: the client connection is closing" error every time for a number of minutes (if not longer, I don't recall how long I was trying for), which would seem to indicate that we weren't properly closing the connection.

Feel free to close.

**Comment by tamird** [comment]
> which would seem to indicate that we weren't properly closing the connection.

Or that we were immediately reopening and re-closing it repeatedly.
