### ISSUE TITLE
stability: goroutine spike on indigo

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#14561]
At ~07:48:22 this morning, `indigo 9` experienced a spike in goroutines. The following shows 2 log entries containing goroutine counts:

```
I170403 07:48:22.009449 145 server/status/runtime.go:227  [n9] runtime stats: 5.9 GiB RSS, 649 goroutines, 313 MiB/248 MiB/843 MiB GO alloc/idle/total, 3.9 GiB/5.1 GiB CGO alloc/total, 7273.12cgo/sec, 0.75/0.08 %(u/s)time, 0.00 %gc (5x)
I170403 07:48:32.021121 145 server/status/runtime.go:227  [n9] runtime stats: 6.6 GiB RSS, 44575 goroutines, 801 MiB/664 KiB/1.6 GiB GO alloc/idle/total, 3.9 GiB/5.1 GiB CGO alloc/total, 5188.67cgo/sec, 1.21/0.19 %(u/s)time, 0.00 %gc (3x)
```

Over the course of 10 seconds, the node went from using 649 gorutines to 44575 goroutines. The periodic goroutine dump taken at 07:48:56 shows 8904 goroutines, with 7935 stuck in:

```
7935: select [Created by stop.(*Stopper).RunAsyncTask @ stopper.go:284]
    kv                  dist_sender.go:1161         (*DistSender).sendToReplicas(#1400, #245526, *, #405, 0, #1401, 0x2, *, 0x3, 0x3, ...)
    kv                  dist_sender.go:406          (*DistSender).sendRPC(#1400, #245526, *, 0x2, *, 0x3, 0x3, 0, 0, 0, ...)
    kv                  dist_sender.go:475          (*DistSender).sendSingleRange(#1400, #245527, *, 0, 0, 0, 0, 0, 0, *, ...)
    kv                  dist_sender.go:932          (*DistSender).sendPartialBatch(#1400, #245527, *, 0, 0, 0, 0, 0, 0, *, ...)
    kv                  dist_sender.go:811          (*DistSender).divideAndSendBatchToRanges(#1400, #245527, *, 0, 0, 0, 0, 0, 0, *, ...)
    kv                  dist_sender.go:626          (*DistSender).Send(#1400, #245527, *, 0, 0, 0, 0, 0, 0, *, ...)
    kv                  txn_coord_sender.go:426     (*TxnCoordSender).Send(#1349, #245527, *, 0, 0, 0, 0, 0, 0, *, ...)
    client              db.go:528                   (*DB).send(*, #245526, *, 0, 0, 0, 0, 0, 0, *, ...)
    client              txn.go:783                  (*Txn).send(*, #245526, *, 0, 0, 0, 0, 0, 0, 0, ...)
    client              txn.go:392                  send)-fm(#245526, *, 0, 0, 0, 0, 0, 0, 0, 0, ...)
    client              db.go:436                   sendAndFill(#245526, *, *, *, *, *)
    client              txn.go:392                  (*Txn).Run(*, #245526, *, *, 0, 0)
    client              txn.go:245                  (*Txn).Get(*, #245526, *, #247, *, *, *, *, *, *, ...)
    sql                 descriptor.go:186           getDescriptor(#245526, *, *, #312, *, #337, *, 0, 0, 0)
    sql                 database.go:143             getDatabaseDesc(#245526, *, *, #309, *, #278, 0x6, 0, 0, 0)
    sql                 database.go:162             MustGetDatabaseDesc(#245526, *, *, #309, *, #278, 0x6, *, *, *)
    sql                 table.go:152                getTableOrViewDesc(#245526, *, *, #309, *, *, *, *, *)
    sql                 table.go:178                getTableDesc(#245526, *, *, #309, *, *, *, *, *)
    sql                 table.go:229                mustGetTableDesc(#245526, *, *, #309, *, *, *, 0x1, *)
    sql                 table.go:223                (*planner).mustGetTableDesc(*, #245526, *, *, #344, *, *)
    sql                 table.go:293                (*planner).getTableLease(*, #245526, *, *, *, 0, 0)
    sql                 update.go:46                (*planner).makeEditNode(*, #245526, *, *, #623, 0, *, *, *, *, ...)
    sql                 delete.go:56                (*planner).Delete(*, #245526, *, *, 0, 0, 0, 0, 0, 0xde477d, ...)
    sql                 plan.go:292                 (*planner).newPlan(*, #245526, *, #323, *, 0, 0, 0, 0, *, ...)
    sql                 plan.go:203                 (*planner).makePlan(*, #245526, *, #323, *, 0, *, *, *, *)
    sql                 planner.go:316              (*planner).query(*, #245526, *, #277, 0x57, *, 0x4, 0x4, *, *, ...)
    sql                 planner.go:383              (*planner).exec(*, #245526, *, #277, 0x57, *, 0x4, 0x4, 0, 0, ...)
    sql                 lease.go:245                LeaseStore.Release.func1(#245526, *, *, 0, 0)
    client              db.go:490                   (*DB).Txn.func1(#245526, *, *, *, *, *)
    client              txn.go:591                  (*Txn).Exec(*, #245526, *, *, *, *, *)
    client              db.go:491                   (*DB).Txn(*, #245526, *, *, 0, 0)
    sql                 lease.go:255                LeaseStore.Release(#300, #1349, #1436, #249141, #1436, #4, 0, 0, 0, #788, ...)
    sql                 lease.go:789                (*tableState).removeLease.func1(#245525, #678)
    stop                stopper.go:283              (*Stopper).RunAsyncTask.func1(#936, #268, 0x3, 0x1, 0, 0, *, #245525, #678)
```

I'm still investigating why the RPCs aren't finishing, but that stack trace is curious in the SQL land. Why do we have 7935 goroutines trying to delete a lease concurrently?

Cc @cockroachdb/sql, @cockroachdb/core

**Comment by a-robinson** [comment]
And why has the cluster not recovered since the subsequent node crash?

**Comment by petermattis** [comment]
Prior to the goroutine spike, the log is filled with the following as well as a number of other node liveness messages:

```
E170403 07:45:49.705398 642421113 storage/replica_range_lease.go:199  [n9,s9,r6287/3:/Table/51/1/170{66310…-77593…},@c4235ed180] mismatch incrementing epoch for node_id:2 epoch:3 expiration:<wall_time:1491205549265021084 logical:0 > ; actual is {NodeID:2 Epoch:3 Expiration:1491205555.987204220,0 Draining:false}
```

**Comment by petermattis** [comment]
<img width="932" alt="screen shot 2017-04-03 at 12 01 52 pm" src="https://cloud.githubusercontent.com/assets/6201335/24618575/7b1a8510-1865-11e7-96a2-38feefca1166.png">

Network latencies on `indigo 9` spiked right before the crash. 

<img width="932" alt="screen shot 2017-04-03 at 12 02 07 pm" src="https://cloud.githubusercontent.com/assets/6201335/24618587/87fec7c8-1865-11e7-867c-d44316b6a153.png">

Latencies also went crazy on other nodes as well. I'm guessing the high latencies will be causing troubles for Raft. Yep:

<img width="931" alt="screen shot 2017-04-03 at 12 03 48 pm" src="https://cloud.githubusercontent.com/assets/6201335/24618614/a60fbb14-1865-11e7-97e0-66ef4f37912c.png">

**Comment by petermattis** [comment]
Note that the above latency graphs use a measurement from our "heartbeat" RPC. Actual latencies between nodes in indigo (using `ping`) appear reasonable right now.

**Comment by tamird** [comment]
As we've discovered, it turns out that our heartbeat RPCs can suffer from
contention on the grpc stream, especially in the presence of
https://github.com/petermattis/grpc-go/commit/d3f1ab4a4dca70781cf6dc850a79ed38632660a6

**Comment by andreimatei** [comment]
Can't imagine why we'd have many goroutines trying to release table leases at the same time... I'm looking at the code, and we're not supposed to be attempting to release the same lease multiple times. Anything in the logs about leases? Unfortunately I think we'd need to enable vmodule on sql/lease.go and sql/table.go.

**Comment by petermattis** [comment]
Here is what network traffic looked like on `indigo 9` around the time period it died. What is with the weird spikes of loopback traffic:

<img width="1408" alt="screen shot 2017-04-03 at 12 26 59 pm" src="https://cloud.githubusercontent.com/assets/6201335/24619727/f51020c0-1868-11e7-8558-4fd8e273ab0c.png">

**Comment by petermattis** [comment]
> As we've discovered, it turns out that our heartbeat RPCs can suffer from contention on the grpc stream, especially in the presence of petermattis/grpc-go@d3f1ab4

It's possible the network latency jump is an artifact of `indigo 9` crashing. When the crash occurs, we'll start performing more snapshots and perhaps those snapshots are starving the heartbeat RPCs.

**Comment by petermattis** [comment]
I don't think there is anything actionable here in the 1.0 time frame, but it seems likely there is something that still needs investigation in the table lease code.

**Comment by vivekmenezes** [comment]
I wonder if there is anything actionable here? Can I close this issue?

**Comment by petermattis** [comment]
@vivekmenezes I realize the code in this area has changed, but do you have any explanation for the large number of goroutines with that stack trace? Specifically, this question:

> Why do we have 7935 goroutines trying to delete a lease concurrently?

Perhaps I'm misunderstanding the stack trace.

**Comment by vivekmenezes** [comment]
I don't see how that can happen in the old as well as the new code.

**Comment by petermattis** [comment]
At the time of this failure, the code in `tableState.removeLease` looked like:

```
func (t *tableState) removeLease(lease *LeaseState, m *LeaseManager) {
	t.active.remove(lease)
	t.tableNameCache.remove(lease)

	ctx := context.TODO()
	if m.isDraining() {
		// Release synchronously to guarantee release before exiting.
		m.LeaseStore.Release(ctx, t.stopper, lease)
		return
	}

	// Release to the store asynchronously, without the tableState lock.
	if err := t.stopper.RunAsyncTask(ctx, func(ctx context.Context) {
		m.LeaseStore.Release(ctx, t.stopper, lease)
	}); err != nil {
		log.Warningf(ctx, "error: %s, not releasing lease: %q", err, lease)
	}
}
```

The call to `m.LeaseStore.Release` is the root of the stack trace listed in the original message. There is nothing throttling the the creation of the async tasks here and if `LeaseStore.Release` blocks for some reason (e.g. due to other badness in the system), we can generate goroutines without end. 

Looking at master, there is similar code in `tableState.releaseLease`. I haven't understood the purpose of the async task here other than the comment about not holding the tableState lock. Perhaps there is a lock order issue going on here.

**Comment by petermattis** [comment]
It isn't clear to me why we would have so many calls to `tableState.removeLease`.

**Comment by vivekmenezes** [comment]
I can see how this could build up over time as we renew and release leases on a table, but you note that this happened over a 10 second window. Perhaps we can add more stats for the entire table lease code so that we have a way to see some numbers that we can trust. I'll do that.

**Comment by petermattis** [comment]
Since this hasn't reoccurred, adding stats might not be particularly useful. Perhaps you can try to create a synthetic scenario where calls to `LeaseStore.Release` block and verify that behavior of the system when that happens.

**Comment by vivekmenezes** [comment]
The old code could keep old leases on the same version of a table descriptor if a SQL statement referencing the table descriptor was stuck for a long time (many minutes/hours). Not sure why all the SQL statements would get released at the same time releasing all the old leases on the descriptor. What I'm saying is what was seen here is pretty far fetched!

In the current code there can be only one outstanding lease on a particular version of the table descriptor. Whenever a new lease is created it takes on the reference count on the prior lease  at the same table version and any prior lease doesn't need to wait on any SQL statement (because of the transfer of reference count) and gets released immediately. This is tested by TestLeaseManagerReacquire

I'm closing this issue because I'm confident we're not going to see it.
