### ISSUE TITLE
rpc: log spam about unable to connect to down node

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#14564]
Not sure what can be done here, but when a node in a cluster is down, all of the other nodes log a message once per second about being unable to create a client transport:

```
I170403 16:28:47.254064 647313714 vendor/google.golang.org/grpc/clientconn.go:806  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 13.64.250.160:26257: getsockopt: connection refused"; Reconnecting to {cockroach-indigo-0009.crdb.io:26257 <nil>}
I170403 16:28:48.141162 647313714 vendor/google.golang.org/grpc/clientconn.go:806  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 13.64.250.160:26257: getsockopt: connection refused"; Reconnecting to {cockroach-indigo-0009.crdb.io:26257 <nil>}
I170403 16:28:52.003562 647313714 vendor/google.golang.org/grpc/clientconn.go:806  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 13.64.250.160:26257: getsockopt: connection refused"; Reconnecting to {cockroach-indigo-0009.crdb.io:26257 <nil>}
```

**Comment by tamird** [comment]
This is also https://github.com/grpc/grpc-go/issues/1044.

**Comment by tamird** [comment]
Indeed, not sure what can be done here. We could do something horrible in our logger (https://github.com/cockroachdb/cockroach/blob/88d4bae/pkg/util/grpcutil/log.go) to intercept these calls and suppress them.

Does that sound like something you might be interested in? Otherwise we should remove 1.0.

**Comment by petermattis** [comment]
> Does that sound like something you might be interested in?

Is there any other option? I've heard murmurings about other requests to silence the gRPC logs, but I'm not sure what the time frame is on that. Filtering certain gRPC log messages based on strings seems reasonable.
