### ISSUE TITLE
Test panics with no output

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#14576]
There have been two test failures lately with no output at all other than the random seed (#14423, #14417). Are there any known remaining issues with log output in tests, @knz @jordanlewis?

**Comment by jordanlewis** [comment]
Not that I'm aware of. For what it's worth, the round numbers of seconds in their runtimes all seem to indicate timeouts:

```
=== RUN   TestUpsertFastPath
FAIL	github.com/cockroachdb/cockroach/pkg/sql	600.172s
```
```
=== RUN   TestRetryableErrorForWrongTxn
FAIL	github.com/cockroachdb/cockroach/pkg/sql	180.066s
```

**Comment by a-robinson** [comment]
Yeah, so I wonder what's preventing the usual stack traces from getting printed?

**Comment by jordanlewis** [comment]
Oh, those two are from 6 days ago. I think 6 days ago we didn't have Raphael's fix for the suppressed stack traces. #14364

**Comment by a-robinson** [comment]
Ah, thanks. That makes sense. We have a recent outburst of test timeouts then, taking #14562 and #14452 into account. I'll close this though, as at least the lack of output is understood.
