### ISSUE TITLE
ui/support: Investigate the export of monitoring data from a remote cluster

### ISSUE THREAD

**Issue by mrtracy** [cockroachdb/cockroach#14584]
As the number of running clusters continues to increase, CockroachDB requires better tools to help diagnose customer issues that will inevitably crop up. 

One possible solution is the ability for customers to export monitoring data from their cluster and send it to a remote location (i.e. Cockroach Labs) as part of the support process; at the remote location, the exported data can be imported to allow a support person to inspect the static state of the customer's cluster at export time using the same Admin UI tools used to inspect a running cluster.

This issue is intended as a high-level investigation of such an import/export system.

##### Export
The export process is more straightforward than the import process - a command line option will be added to CockroachDB to connect to a cluster and extract monitoring data (logs, time series, node status), storing it in some archive.

This export step likely has some value by itself (without an "import" step), even if the output of the archive is difficult to inspect.

##### Import
The "import" step would mean being able to use our Admin UI tools to inspect the data in the archive, as if it were a running cluster.

This is considerably more difficult than data export.  Our UI has been built to query a running cluster using the Admin and Time-series interfaces. Thus, we would either have to implement the server-side API over a static archive, or we would need to find a way to import this data into a local cluster and place it in some sort of "inspection mode" so that the data remains static..

**Comment by bdarnell** [comment]
We could have the server persist the contents of the prometheus endpoint periodically (we might not be able to collect high-resolution data this way, but that might be enough). And we might be able to use prometheus/grafana as the inspection interface for this data.
