### ISSUE TITLE
sql: add prepared query/statement capability to logic test framework

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#14581]
Prepared queries are a weak spot in our sql semantics testing story. Currently, we exercise them in `pgwire_test.go`, which is getting rather unwieldy due to the complexity of trying to fully exercise all of the prepared statement and query code paths.

It would be really great if the tests in that file could be written in the logic test framework instead.

I can think of a few approaches:

- Teach the framework to run files in a prepare/execute mode when instructed. This mode would replace constants in valid positions with placeholders, and prepare/execute the statements or queries.
- Add a new `prepare` option to the `query` and `statement` directives, with an optional argument that contains a type hint for each placeholder in the input, that instructs the framework to prepare the query or statement before executing it.

**Comment by bdarnell** [comment]
It wouldn't give us as much control over type hints but we could also do this with the textual PREPARE and EXECUTE commands as seen in other databases (#7568).

**Comment by petermattis** [comment]
@jordanlewis Didn't you already add `PREPARE` and `EXECUTE` support? Is there anything else to do here?

**Comment by jordanlewis** [comment]
Yep, this is done. I do have another wishlist item related to this - an option in the sql shell or sql logic test framework that treats `PREPARE` and `EXECUTE` statements as pgwire commands and not SQL commands - but it's not a pressing need.
