### ISSUE TITLE
Support UUID natively

### ISSUE THREAD

**Issue by 0xbaadf00d** [cockroachdb/cockroach#14595]
Actually, in our company, we are using PostgreSQL, but the "replication / clustering" part of PostgreSQL is verry hard to maintain and configure. Cockroach seems a really good alternative but UUID type is missing and we are massively using UUID for public URL and in the API.

As you are compatible with PostgreSQL driver, it could be nice to support natively all types that PostgreSQL support, including UUID or Enum. For a scalable DB like Cockroach, I think UUID type must be a core feature. 

String conversion (#8719) is a workaround, but not a valid and reliable solution... Searching UUID (native) is faster that search for a String during a _SELECT x FROM x WHERE_ x query. Nowaday, lot of applications use UUID rather than simple auto-increment ID.

Sincerely

**Comment by bdarnell** [comment]
Why is this a separate issue from #8719? It looks like you're asking for exactly the same thing. 

> Searching UUID (native) is faster that search for a String

There are two ways you could store a UUID: either as 16-byte array or a 36-character hex string. The hex string is indeed a bit slower, but the 16-byte array in a `BYTES` column will perform just as well as a native UUID type would.

**Comment by 0xbaadf00d** [comment]
By using JDBC PostgreSQL (Java 8), I have to pass an UUID or a byte[] where I build my query with an ORM (eg : Ebean ORM) ?

**Comment by bdarnell** [comment]
Passing a `byte[]` would be the best for performance, but you could also pass it as a string and use the `to_uuid()` function in your query.

**Comment by knz** [comment]
@0xbaadf00d: to clarify what ben says, you'd use a column of type "BYTES" to store the UUID in a table (and index it), then to get/set the value you would do `SELECT from_uuid(uuid_col), ...` or `INSERT INTO ...(uuid_col, ...) VALUES (to_uuid(...), ...)`

This requires you can set in the ORM custom accessor functions for your column.  If that is not the case, you can work with the string type directly instead. 
Does this clarify?

Ben: FWIW the fact that ORMs typically do not allow custom conversion functions is a motivating factor to justify supporting the type natively server-side.

**Comment by jseldess** [comment]
@knz, @bdarnell, what additional details would you like me to add to https://www.cockroachlabs.com/docs/sql-faqs.html#does-cockroachdb-support-a-uuid-type? Should we add an example?

**Comment by knz** [comment]
Yes probably examples would be good, or perhaps links to the two builtins from_uuid/to_uuid.

**Comment by bdarnell** [comment]
Yeah, I think what we need are examples, and a sample table definition and to/from queries would be a good start, but I think what's tripping people up is not the SQL syntax but how to use this end-to-end with the UUID type in whatever programming language they're using. 

Also, we only need one issue tracking UUID support, so I'm going to close this one and ask that all followup discussion go to #8719.
