### ISSUE TITLE
ui: total client connections with breakdown per node

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#14598]
**Feature request:**

Currently, it's possible to see:
- Client connections across all nodes using **Graph: Cluster > Dashboard: SQL > SQL Connections** 
   ![screen shot 2017-04-04 at 9 38 46 am](https://cloud.githubusercontent.com/assets/15893490/24659435/a7bd6f50-191a-11e7-9d07-03377ed1fc81.png)
- Client connections per node using **Graph: node address > Dashboard: SQL > SQL Connections**
   ![screen shot 2017-04-04 at 9 42 42 am](https://cloud.githubusercontent.com/assets/15893490/24659581/13f3430c-191b-11e7-8d29-4e0e12fab93a.png)

But it would be nice to see the total client connections with a per node breakdown in one place (we used to list "Connections" on the nodes list page). This would be especially useful for quickly validating load balancing.

**Comment by jseldess** [comment]
@kuanluo, mentioned this to you in passing a few weeks back. Finally opening the issue.

**Comment by kuanluo** [comment]
Got it. Thanks, @jseldess! We can simply add the breakdown to the tooltip of the cluster level SQL connection, as shown in the first graph. 

cc @mrtracy Probably not a top priority, but we can do a UX improvement pass on this when you are through the bugs.

**Comment by dianasaur323** [comment]
adding to 1.0 milestone with the possibility that we will move this out if we can't get to it.
