### ISSUE TITLE
stability: revisit periodic goroutine dumps

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#14602]
The `/debug/pprof/goroutine?debug=2` endpoint stops all goroutines while generating the stack traces. When there are thousands or 10s of thousands of goroutines, this can be a significant pause. On test clusters, we generate a goroutine dump every 30s. Below shows the CPU usage on a node with O(15K) goroutines:

<img width="1406" alt="screen shot 2017-04-04 at 12 32 26 pm" src="https://cloud.githubusercontent.com/assets/6201335/24668294/5ab9e1b0-1934-11e7-92b6-54c814107e85.png">

At 16:28 I disabled the periodic goroutine dumps and the spiky CPU usage disappeared.

**Comment by petermattis** [comment]
On a node with 14,820 goroutines, it takes 9.5s to `curl -k -o goroutine.tmp 'https://localhost:8080/debug/pprof/goroutine?debug=2'`. The bulk of that time is spent generating the goroutine dump with all goroutines stopped. Ouch.

**Comment by mberhault** [comment]
ok, that's rather bad. I don't think we've been using those too much recently anyway. I'll start turning some of those off.

**Comment by bdarnell** [comment]
The `runtime.Stack()` API lets you pass in a limited-size buffer. The [pprof goroutine dumper](https://github.com/golang/go/blob/9b15c13dc567d92c6ac628c762d42b4ae2c9469f/src/runtime/pprof/pprof.go#L599-L618) will use up to 64MB for this. Maybe we should implement our own goroutine dumper that has a smaller limit so we can put a smaller bound on how much overhead this will have. (I'd also be OK with disabling them; I haven't used them in a while)

**Comment by petermattis** [comment]
Remember that `get_profile.sh` also deletes old profiles. So disabling this should leave the deletion of place, but not gather new goroutine dumps.

**Comment by petermattis** [comment]
@mberhault Is there anything left to do here?

**Comment by mberhault** [comment]
some tweaks to get_profile and stopping goroutine dumps in more clusters, but nothing on this issue. Closing.
