### ISSUE TITLE
sql: aggregate function alongside window clause not recognized by GROUP BY semantic check

### ISSUE THREAD

**Issue by r7ar7a** [cockroachdb/cockroach#14606]
**BUG REPORT**

Please supply the header (i.e. the first few lines) of your most recent
```
root@480e29851960:/cockroach# grep -F '[config]' cockroach-data/logs/cockroach.log
I170404 17:37:56.092352 1 util/log/clog.go:991  [config] file created at: 2017/04/04 17:37:56
I170404 17:37:56.092352 1 util/log/clog.go:991  [config] running on machine: 480e29851960
I170404 17:37:56.092352 1 util/log/clog.go:991  [config] binary: CockroachDB CCL 274f7e5 (linux amd64, built 2017/04/04 04:12:13, go1.8)
I170404 17:37:56.092352 1 util/log/clog.go:991  [config] arguments: [/cockroach/cockroach start --insecure --http-port 9999]
```

Please describe the issue you observed:

- What did you do?
```
rara@Andrass-MacBook-Pro:~$ docker run -d --name=cockroach -p 26257:26257 -p 9999:9999 cockroachdb/cockroach:latest  start --insecure --http-port 9999
480e2985196042056a175397d516df4d0beb03dd4a1afa36500a73f6fb129760
rara@Andrass-MacBook-Pro:~$ docker exec -it cockroach bash
root@480e29851960:/cockroach# ./cockroach.sh sql -e 'SELECT 2 * (ROW_NUMBER() OVER (ORDER BY MAX(i))) FROM (SELECT 1 AS i, 2 AS j) GROUP BY j;'
+--------------------------------+
| 2 * (ROW_NUMBER() OVER (ORDER BY MAX(i))) |
+--------------------------------+
|                              2 |
+--------------------------------+
(1 row)
root@480e29851960:/cockroach# ./cockroach.sh sql -e 'SELECT MAX(i) * (ROW_NUMBER() OVER (ORDER BY MAX(i))) FROM (SELECT 1 AS i, 2 AS j) GROUP BY j;'
Error: pq: column "i" must appear in the GROUP BY clause or be used in an aggregate function
Failed running "sql"
```
the only difference is:
./cockroach.sh sql -e 'SELECT &nbsp;&nbsp;&nbsp;&nbsp; **2** &nbsp;&nbsp;&nbsp; * (ROW_NUMBER() OVER (ORDER BY MAX(i))) FROM ...'
./cockroach.sh sql -e 'SELECT **MAX(i)** * (ROW_NUMBER() OVER (ORDER BY MAX(i))) FROM ...'

- What did you expect to see?
one single value (1)
- What did you see instead?
parsing error
`Error: pq: column "i" must appear in the GROUP BY clause or be used in an aggregate function
Failed running "sql"`

... I also tested this query with postgresql, and it have worked.

**Comment by knz** [comment]
@nvanbenschoten can you remind me/us which code is responsible for this check and why this fails; if that's not up your alley feel free to reassign.

**Comment by nvanbenschoten** [comment]
Hi Andras, thanks for the bug report! The issue here is similar to what prompted https://github.com/cockroachdb/cockroach/commit/5d26b09dc2949d8f59a19935dbc97e4a56495abb. In that case, index variables (column references) above the "windowing level" in the expression tree needed to be pushed below so that they were evaluated correctly. Similarly, here aggregate functions above the "windowing level" need to be pushed below and added to `groupNode`'s renders so that they are properly handled there. I have a working fix, but want to verify that I'm not abusing the `IndexedVar` infrastructure before pushing it.
