### ISSUE TITLE
sql: failure to delete from index with storing clause

### ISSUE THREAD

**Issue by eisenstatdavid** [cockroachdb/cockroach#14601]
The bug described in #14533 has wider scope than just collated strings, so I'm making a new bug with a reduced test case. Run

```
DROP DATABASE IF EXISTS d;
CREATE DATABASE d;
SET DATABASE = d;
CREATE TABLE t (a STRING, b BOOL);
CREATE INDEX i ON t (a) STORING (b);
INSERT INTO t VALUES
  ('a', FALSE),
  ('b', FALSE),
  ('c', FALSE);
EXPLAIN DELETE FROM t WHERE a > 'a' AND a < 'c';
DELETE FROM t WHERE a > 'a' AND a < 'c';
EXPLAIN SELECT a FROM t ORDER BY a;
SELECT a FROM t ORDER BY a;
DROP INDEX i;
EXPLAIN SELECT a FROM t ORDER BY a;
SELECT a FROM t ORDER BY a;
```

and observe that the `SELECT` statements give different results despite the fact that the only intervening mutation is dropping the index.

```
DROP DATABASE
CREATE DATABASE
SET
CREATE TABLE
CREATE INDEX
INSERT 3
6 rows
Level	Type	Field	Description
0	delete
0		from	t
1	render
2	scan
2		table	t@i
2		spans	"/""a\x00""-/""c"""
DELETE 1
4 rows
Level	Type	Field	Description
0	render
1	scan
1		table	t@i
1		spans	ALL
3 rows
a
a
b
c
DROP INDEX
6 rows
Level	Type	Field	Description
0	sort
0		order	+a
1	render
2	scan
2		table	t@primary
2		spans	ALL
2 rows
a
a
c
```

**Comment by eisenstatdavid** [comment]
The impact of this bug is that deleting from a table that has an index with a `STORING` clause can break the fundamental relationship of index to table. Non-unique indexes are always affected; unique indexes are affected only if the indexed columns contain `NULL`.

The root cause is that the planner doesn't mark the `STORING` columns as necessary for the deletion, hence they encode incorrectly as `NULL` for the point deletion at the KV layer. This is likely an issue for updates as well. I see three alternatives for how we proceed.

1. When scanning for rows to delete, mark the `STORING` columns as needed so that index keys can be properly constructed. The downside is that the planner may not be able to use an index.

2. Issue range deletions for indexes with `STORING` columns. The downside is that range deletions are probably slower than point deletions. I don't know how much slower.

3. Make a backward-incompatible change to the encoding for indexes with a `STORING` clause.

The format for non-unique indexes would be
```
[indexed columns][non-indexed primary key columns]: [STORING columns].
```
The formats for unique indexes would be
```
[indexed columns, zero NULLs]: [STORING columns][non-indexed primary key columns]
[indexed columns, one or more NULLs][non-indexed primary key columns]: [STORING columns]
```
The downsides are that this is a BACKWARD INCOMPATIBLE CHANGE and that index key construction becomes more involved. The upsides are that

1. this is a pretty good time to make such a change, given that we're pre-1.0 and many if not all secondary indexes with `STORING` clauses will need to be rebuilt anyway,
2. we avoid the performance downsides arising from the other two alternatives, and
3. this alternative eliminates the wart with performance implications where unique indexes with indexed `NULL`s store the extra fields twice.

**Comment by eisenstatdavid** [comment]
The formats for unique indexes actually have to be
```
[indexed columns, zero NULLs]: [STORING columns and primary key columns]
[indexed columns, one or more NULLs][non-indexed primary key columns]: [STORING columns and primary key columns]
```
We only lose the double encoding for stored columns (unless we go whole hog and break backward compatibility for non-storing, unique secondary indexes too).

**Comment by eisenstatdavid** [comment]
cc @RaduBerinde @bdarnell

**Comment by petermattis** [comment]
Seems like the current code is just broken with respect to `STORING`. So I'm fine with a backwards incompatible change.

Related, in discussion today the idea of a SQL fsck tool came up again.

**Comment by bdarnell** [comment]
> this is a pretty good time to make such a change, given that we're pre-1.0

We've promised backwards-compatibility at the level of the on-disk format ever since we went into beta. We've had some small violations of that (e.g. for collated indexes, but that feature was only a week old), but we're well past the time when we can freely make breaking changes. Maybe this is still OK (STORING is a relatively rarely-used feature), but we should be careful about it and make sure the transition is as graceful as possible (for example, it would be best if the query planner could identify indexes in the old format and avoid using them).

**Comment by RaduBerinde** [comment]
The right thing to do in principle is indeed to always put the STORING columns in the value. The way things are right now, I don't see a reason to use STORING at all (vs. putting all the columns in the index).

**Comment by petermattis** [comment]
> We've promised backwards-compatibility at the level of the on-disk format ever since we went into beta.

Unless I'm reading @eisenstatdavid's message wrong, if you're using `STORING` right now you're probably encountering badness if you've deleted from the associated index. I agree about needing to be careful here.

> Issue range deletions for indexes with STORING columns. The downside is that range deletions are probably slower than point deletions. I don't know how much slower.

Range deletions are not much slower than point deletions. This may be fine. 

@eisenstatdavid I just re-read your message and I'm mildly confused about what the current behavior is with respect to `STORING` columns. I thought they were always stored in the value unless the column was also part of the index key.

**Comment by eisenstatdavid** [comment]
> I just re-read your message and I'm mildly confused about what the current behavior is with respect to STORING columns. I thought they were always stored in the value unless the column was also part of the index key.

The current behavior is that stored columns, and primary key columns not in the secondary key ("extra columns") are encoded together. For non-unique indexes, this means the KV key. For unique indexes, this means the KV value except when the secondary key has a NULL column, in which case the extra columns appear in the key too for uniqueness.

**Comment by eisenstatdavid** [comment]
Secondary indexes with STORING whose tables have been updated/deleted from should be presumed garbage (depending on the details of the planner, I guess), but insert-only tables are fine.

**Comment by petermattis** [comment]
Hmm, I'm probably missing something, but why can't the planner construct the write index keys for the deletion. In the example you gave, scanning `t@i` will provide both `a` and `b`. I'm sure there are more complex examples where an index-join would be necessary to get the columns for a row, but those examples can be constructed without `STORING` too.

**Comment by eisenstatdavid** [comment]
@petermattis I wrote that example before I understood the problem completely. Consider the case of a table with columns w, x, y, z and primary key w; index on x, y (storing w because it's the primary primary key); and index on y storing z (and w because it's the primary primary key). If we want to delete from the table with a where clause that specifies a range for x, then we would like to use the index on x, y but we can't if we need z to delete from the other index.

**Comment by eisenstatdavid** [comment]
(to be explicit, we wouldn't need z if `STORING` stored columns in the KV value)

**Comment by petermattis** [comment]
> Consider the case of a table with columns w, x, y, z and primary key w; index on x, y (storing w because it's the primary primary key); and index on y storing z (and w because it's the primary primary key). If we want to delete from the table with a where clause that specifies a range for x, then we would like to use the index on x, y but we can't if we need z to delete from the other index.

Right. We'd need to do an index-join to lookup all of the columns in the row. I think there is a short term issue to fix here which is the incorrect construction of the keys when `STORING` columns are present for non-unique indexes (or unique indexes with a `NULL`). And there is a longer term fix to see if we can adjust the index key construction for indexes containing a `STORING` clause so that `STORING` columns are always stored in the value.

**Comment by eisenstatdavid** [comment]
I have a fourth idea. `IndexDescriptor` has a repeated field called `extra_column_ids` that is currently the union of the non-indexed primary key columns and the stored columns. Let's introduce another repeated field, `store_column_ids`. For old tables, `extra_column_ids` has its old meaning, and `store_column_ids` is empty. For new tables, `extra_column_ids` doesn't contain the stored columns; those go in `store_column_ids`.

The format for non-unique indexes would be
```
[indexed columns][extra columns as specified `extra_column_ids`]: [store columns as specified by `store_column_ids`].
```
This format simplifies to the current format when `store_column_ids` is empty. The formats for unique indexes would be
```
[indexed columns, zero NULLs]: [extra columns as specified by `extra_column_ids`][stored columns as specified by `stored_column_ids`]
[indexed columns, one or more NULLs][extra columns as specified by `extra_column_ids`]: [extra columns as specified by `extra_column_ids`][stored columns as specified by `stored_column_ids`].
```
These formats too simplify to the current formats when `store_column_ids` is empty. The only remaining wart is that the extra columns (non-indexed primary key columns) still appear twice when an indexed column is null. Oh well.

(While we're at it, let's improve the storage of composite columns by suppressing the redundant key encoding for stored composite columns in secondary indexes.)

We get backward compatibility almost for free. The almost is because of testing, but it should suffice to make the table construction logic flag controlled and run the SQL tests both ways.

**Comment by petermattis** [comment]
Sounds reasonable to me, though you'll still have to fix up the index key creation for old tables where the store columns are present in `extra_column_ids`. That might negate some of the ease of doing this. 

> The only remaining wart is that the extra columns (non-indexed primary key columns) still appear twice when an indexed column is null. Oh well.

That seems minor.

**Comment by eisenstatdavid** [comment]
> you'll still have to fix up the index key creation for old tables where the store columns are present in extra_column_ids
I don't understand your logic here -- a fix would be relevant only for indexes affected by this bug, and those indexes can't be trusted anyway. New indexes on old tables would have the store columns separate from the extra columns, so the only caveat would be not to create any indexes during the cluster upgrade.

**Comment by eisenstatdavid** [comment]
Regardless, the fix is making the planner aware that it needs all of the extra columns of the various indexes to delete, which seems as though it shouldn't be too bad.

**Comment by petermattis** [comment]
> I don't understand your logic here -- a fix would be relevant only for indexes affected by this bug, and those indexes can't be trusted anyway.

Yes, those indexes can't be trusted, but I think we should fix the logic regardless. As you say later, it shouldn't be too bad to do so.

**Comment by eisenstatdavid** [comment]
#14643 implemented approach 1 because it doesn't interfere with a later change introducing `store_column_ids` (i.e., the aforementioned fourth idea, which I will start implementing tomorrow).
