### ISSUE TITLE
The NODES link in the console does not work

### ISSUE THREAD

**Issue by huachaohuang** [cockroachdb/cockroach#14625]
**BUG REPORT**

1. Please supply the header (i.e. the first few lines) of your most recent
  Seems not necessary.

2. Please describe the issue you observed:

- What did you do?
  1. Start a node `node-1` with nodeID 1
  2. Access the console in http://localhost:8080/#/nodes/1
  3. Click the **NODES** link at the top, which jumps to http://localhost:8080/#/nodes

- What did you expect to see?
  See all nodes information like http://localhost:8080/#/cluster/nodes.

- What did you see instead?
  See nothing.

**Comment by mrtracy** [comment]
Related to #13230
