### ISSUE TITLE
ui: missing data in graph hover for some nodes

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#14636]
I lost a node for a while but its data is missing from the graph hover for all times after it died (even once it had come back). If that doesn't make sense, look at the two screen shots

Node 3 before it died: https://www.dropbox.com/s/i1lderxfnvln9ca/Screenshot%202017-04-05%2012.50.30.png?dl=0
Node 3 after it had come back (note the 0.000): https://www.dropbox.com/s/zqx8sa7k86utnrl/Screenshot%202017-04-05%2012.50.55.png?dl=0

**Comment by mrtracy** [comment]
@danhhz The line itself for node 3 is visible, so might I ask: was the tooltip zero at *every* point, or just certain points?

If it was only zero at certain points, this is a duplicate of #12856

**Comment by danhhz** [comment]
The tooltip was zero for every point after the node went down. This included points from after it came back up that were clearly not 0 on the graph.

Maybe it was just interpolating and I didn't go left and right far enough to find the endpoints of the interpolation. I'm happy closing this as a dup #12856
