### ISSUE TITLE
beta-20170406

### ISSUE THREAD

**Issue by asubiotto** [cockroachdb/cockroach#14631]
The candidate SHA is 7e593b16a9bf3a938adb33e54b32bac330d650cc.
Deployed to `omega` and `adriatic` as well as a race-enabled build to `cerulean`.

[Release process checklist](https://github.com/cockroachdb/cockroach/wiki/Release-Process)
- [x] Check and verify cluster status
- [x] Tag release and push tag
- [x] [Trigger release build](https://teamcity.cockroachdb.com/viewType.html?buildTypeId=Cockroach_MergeToMaster)
- [x] Check and verify binaries
- [x] Announce version to the registration cluster - see internal production instructions
- [x] Update the [Homebrew tap](/cockroachdb/homebrew-cockroach)
- [x] Update docs
- [x] External communications for release

**Comment by mberhault** [comment]
I changed the title, we use the actual release data at the beta tag.
