### ISSUE TITLE
cli: refactor flag handling

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#14662]
Our flags are a bit of a mess, specifically:
* similarly-named flags are used in both client and server contexts
* environment variables are sometimes used, sometimes not
* all flags are initialized, and loaded, regardless of the command run

This is making some details tricky (eg: #9189).
We should look into a better way of rearranging our flags. Some options include:
* using higher-level env utilities (eg: [spf13/viper](https://github.com/spf13/viper))
* re-organizing the cli commands (better file names, flags specified in the command itself, etc..)

No milestone yet. Might be useful for 1.0, but this should not break existing behavior, so post-1.0 should fine as well.

**Comment by mberhault** [comment]
Unassigning. There hasn't been much demand for this.

**Comment by knz** [comment]
Regarding the initial issue

>    similarly-named flags are used in both client and server contexts

This has been addressed. For example we now use `--listen-addr` for the server and `--url` for clients.

>    environment variables are sometimes used, sometimes not

The set of env vars is now centralized and the specific values used are reported in the log file. We also have streamlined the cases where an env var is used as default when a flag is not provided.

>    all flags are initialized, and loaded, regardless of the command run

I don't think there is a clear benefit in changing this: the initialization is currently super-fast, doesn't cost much memory, and the code is overall readable.

**Comment by knz** [comment]
since it's not clear from the issue description what we can improve further, i'll close this. feel free to file issues with more specific requests.
