### ISSUE TITLE
engineccl: make it build on windows

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#14673]
`ccl/storageccl/engineccl` currently depends on C++ symbols exported from `storage/engine`. Due to https://github.com/golang/go/issues/14985, it is not possible to share non-Go symbols across Go package boundaries.

It's also not kosher to duplicate the relevant files in the two packages, because that will result in duplicate symbols during final linking.

I think the only way to accomplish this today (without building a standalone C++ library) is to extract the common code and use preprocessor magic to prefix the symbol names with "ccl" when included in the ccl tree - that way we can have all the necessary code in both packages without suffering symbol name collisions.

Low priority, but wanted to document my thoughts. cc @danhhz @bdarnell @petermattis

**Comment by tamird** [comment]
Another idea is to use inline functions, and put all the implementations in the header. Suggested by @petermattis at lunch.

I just tried this, and it's hairier than I thought; the constraint that headers included from Go must be guarded with `#ifdef __cplusplus` + `extern "C"` dances makes me think this should be tackled by someone more experienced with C++ than I, not least because my attempt is likely to produce the wrong color bike shed.

I'm going to assign @petermattis for now, but feel free to reassign.

**Comment by petermattis** [comment]
Can't we just move `DBBatchReprVerify` into `storage/engine`?

**Comment by danhhz** [comment]
I think we wanted to leave ccl licensed code in the ccl tree if we can. We could un-ccl this, but we'll probably have more interesting c++ code in the future, so if there's a real fix for this, we should probably do it.

I'm also okay not supporting enterprise features on windows builds until we start testing them and make them first class (if we ever do that)

**Comment by petermattis** [comment]
`DBBatchReprVerify` doesn't seem particularly ccl-ish, but I suppose using it as a forcing function is ok. Another option is to move portions of the C++ in `storage/engine` into a `.a` compiled by a Makefile. @tamird I'm not completely familiar with all of the linker intricacies. Would that work?

**Comment by tamird** [comment]
Yes, that would work.

**Comment by petermattis** [comment]
Great. Back in your court.

**Comment by tamird** [comment]
@petermattis that's essentially the same as putting portions of the C++ in `storage/engine` into a shared header with a bunch of `inline` or `static` functions, from a "I don't know the subtleties of C++" perspective. Reconsider?

**Comment by petermattis** [comment]
Hmm, I don't know if it is the same, but this isn't urgent to think about for the next few weeks. Let's revisit when 1.0 is out the door.
