### ISSUE TITLE
JDBC PreparedStatement#setTimestamp always throws could not parse string as timestamp

### ISSUE THREAD

**Issue by vladmihalcea** [cockroachdb/cockroach#14699]
Assuming we have the following database table:

    create table post (
        id  bigserial not null, 
        createdOn timestamp,
        title varchar(255), 
        primary key (id)
    )

When executing the following INSERT statement:

```
try(PreparedStatement preparedStatement = connection.prepareStatement(
	"INSERT INTO post (title, createdOn) " +
	"VALUES (?, ?)")
) {
	int index = 0;
	preparedStatement.setString(
		++index,
		"High-Performance Java Persistence"
	);
	preparedStatement.setTimestamp(
		++index,
		new Timestamp( System.currentTimeMillis() )
	);
	int updateCount = preparedStatement.executeUpdate();

	assertEquals( 1, updateCount );
}
```

We get the following exception:
```

Caused by: org.postgresql.util.PSQLException: ERROR: error in argument for $2: could not parse string "2017-04-07 14:53:44.524000 +03:00:00" as timestamp
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2182)
```
Changing the `createdOn` column to `timestamptz` yields the same result.

**Comment by dt** [comment]
@vladmihalcea Thanks for the report! I just merged a fix and a test case in #14712. Please give the next beta release a try (or build from master if you want to try before then) and let me know if you still see any issues!

**Comment by vladmihalcea** [comment]
Thanks. I'll give it a try once you upload a newer version on Docker Hub.

**Comment by dt** [comment]
@vladmihalcea Great, thanks! I believe it should be in the latest builds on docker hub.

**Comment by bobbymicroby** [comment]
Hi guys, we have exactly the same table setup/ jdbc code and we received the same error. We have just build cockroach from master and we got :

```could not parse string "2017-6-1 16:19:7.904000 +3:0:0" as timestamp```

**Comment by jordanlewis** [comment]
Hi @bobbymicroby, I have an open PR to address this - it should be included in an upcoming point release. JDBC generates timestamps in a funny way that we didn't expect, such as `0:1:7` - that's supposed to be expanded to `00:01:17`.

**Comment by bobbymicroby** [comment]
Hi @jordanlewis. Can you point to the branch of the PR so I can build it and try it locally ?

**Comment by bobbymicroby** [comment]
I guess this is it : 

https://github.com/cockroachdb/cockroach/compare/master...jordanlewis:timestamp-parse-issues

**Comment by jordanlewis** [comment]
Yeah, but it's not complete. I was trying to finish it up this morning!

**Comment by bobbymicroby** [comment]
Okay, i will watch it and try it when it is ready. Tnx a lot !
