### ISSUE TITLE
sql: Allow SHOW TRANSACTION ISOLATION/PRIORITY outside of transactions

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#14700]
PostgreSQL allows these statements at any point, and the java connection pool library `c3p0` appears to issue one or both of them as soon as it opens a connection, so we need to allow them and return the default values. This probably just means reverting #14491, unless we want to preserve some of the refactoring that was done there.

From [this forum post](https://forum.cockroachlabs.com/t/can-not-connect-to-the-server-after-upgrading-to-beta-20170406/547).

**Comment by dt** [comment]
Much of the refactoring in #14491 overlapped with #14105 (so it won't `git revert` cleanly).
