### ISSUE TITLE
int treated as string in node js using pg client

### ISSUE THREAD

**Issue by aunz** [cockroachdb/cockroach#14701]
Hello, not sure I should post here or the [node-postgres](https://github.com/brianc/node-postgres) client for node js.

I am running docker in windows 10
`docker run --rm -d -p 26257:26257 -p 8080:8080 cockroachdb/cockroach:latest start --insecure`

and connect to it with
```js
const pg = require('pg')

const pool = new pg.Pool({
  user: 'root',
  port: 26257
})

pool.query('select 123 as num;')
  .then(r => console.log(typeof r.rows[0].num, r.rows[0].num)) // => string 123
  .catch(console.log)
```

123 is expected to be `number`, but it's `string`

I have tried `'select 123::int as num'` and still got typeof `string`

But, if I did `'select 123::float as num'`, I got typeof `number` as expected.

Another one, `'select 1/0::float as num'` produced typeof `number`, but the value was `NaN`, instead of `Infinity`

My apology if I should be posting at node-postgres

**Comment by aunz** [comment]
With the [help](brianc/node-postgres#1260) from the node-postgres team, I found the solution.

As cockroachdb treats all int as 64-bit but JavaScript only supports 53-bit int so pg driver by [default](https://github.com/brianc/node-pg-types/blob/master/lib/textParsers.js) treat bigInt as string. To circumvent this, I add the following lines

```js
import pg from 'pg'
pg.types.setTypeParser(20, parseInt) // <- add this line
```
The caveat is that int larger than `9007199254740991 (Number.MAX_SAFE_INTEGER)` or smaller than `-9007199254740991 Number.MIN_SAFE_INTEGER` may result in data loss

**Comment by miracle2k** [comment]
The problem with this, it seems, is that SERIAL fields usually/frequently/always seem to have ids that are larger than that. One such id given to be by Cockroach:

```
> parseInt('256409871051915265')
256409871051915260
```

**Comment by miracle2k** [comment]
I am now using this approach *thumbs crossed*:

```
// https://github.com/cockroachdb/cockroach/issues/14701
pg.types.setTypeParser(20, (value: string) => {
  const parsed = parseInt(value);

  // Is this number safe to convert?
  if (parsed.toString() !== value) {
    return value;
  };

  // Even if it was parsed correctly, don't trust it if
  // it's outside the bounds.
  if (parsed > Number.MAX_SAFE_INTEGER || parsed < Number.MIN_SAFE_INTEGER) {
    return value;
  }

  return parsed;
});
```
