### ISSUE TITLE
distsql: TestRebalance_3To5Small_WithSchemaChanges fails with distsql turned on

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#14727]
This test is failing with #14668 

https://teamcity.cockroachdb.com/viewLog.html?buildId=212139&tab=buildResultsDiv&buildTypeId=Cockroach_Nightlies_SchemaChangeTest3to510g

The test essentially hangs in the validation phase that uses distsql. I'm going to disable it for now.

**Comment by dianasaur323** [comment]
@vivekmenezes not sure what you were referring to here in this issue, but I marked as 1.0 for now. Feel free to move as necessary.

**Comment by tamird** [comment]
Looks like this test is still failing, not sure if with DistSQL or not, with the error:
```
[TestRebalance_3To5Small_WithSchemaChanges] allocator_test.go:255: pq: index "foo" not found
```

https://teamcity.cockroachdb.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=230387#_focus=3156

**Comment by vivekmenezes** [comment]
the failure seen is #15038

**Comment by vivekmenezes** [comment]
Closing issue since distsql is now enabled in auto mode and the SQL in the test run for verifying the correctness of a schema change is working with distsql on.
