### ISSUE TITLE
storage: replace storage.TestStoreContext (and similar) with functions

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#1472]
Mutable global contexts like storage.TestStoreContext can be accidentally mutated, as in #1471. It would be better to make these factory functions returning new unshared objects to avoid state accidentally leaking between tests.

**Comment by tamird** [comment]
Would constants work?

**Comment by bdarnell** [comment]
No; composite types including structs cannot be `const` in go. golang/go#359

**Comment by petermattis** [comment]
@bdarnell Do you still plan on doing this cleanup?

**Comment by bdarnell** [comment]
I'd still like for it to be done, but not enough to do it myself :)  This would be a good task for a first-time contributor.

**Comment by tschottdorf** [comment]
I also think this remains useful.
