### ISSUE TITLE
build: Better `latest` tarballs

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#14731]
Our current `latest` release tarballs are different from our dated tarballs (they expand into a directory named `cockroach-latest` instead of `cockroach-beta-###`). This has some unfortunate consequences: the `latest` tarballs are overwritten with every release, so if we need to withdraw a release we have to do a new build instead of just changing a pointer. This takes time, and (currently) overwrites the dated tarballs too (see cockroachdb/homebrew-cockroach#11), which is not great - those should be write-once/immutable. 

My preference would be to make the `latest` tarballs an HTTP redirect to the dated tarballs. This has some impact on docs (we can't just say `cd cockroach-latest`; it needs to include the date of the release), but it simplifies everything else. Or if we want to keep the constant directory name, we should store historical versions of the `latest` tarballs instead of just overwriting them.

**Comment by benesch** [comment]
Agreed, an HTTP redirect seems like the right approach. I'm also in favor of ditching `cockroach-latest`, since that becomes incorrect once the next release comes out.

I initially figured this wasn't possible with S3, but it looks like S3  [has supported 301 redirects](https://aws.amazon.com/blogs/aws/amazon-s3-support-for-website-redirects/) for many, many years.

**Comment by mberhault** [comment]
We're using a separate tarball partially to make the docs easier. We
include steps to extract the tarball and cd into the directory so a fixed
name is easier.
That said, it's easy enough to change and still keep the docs clear.

The bigger issue may be cloudfront-from-S3. I seem to recall something bad
about redirects in that case, but I'm not certain.

**Comment by benesch** [comment]
Just floating a thought: what if we ditched the latest tarballs entirely? Tossing a `latest_release` variable in the docs Jekyll config and deriving the tarball download URL and installation instructions from that variable wouldn't be much fuss at all, especially considering that we deploy release notes weekly. Makes withdrawing a release as easy as updating the docs pointer, too.

I guess I'm asking if there's a reason we have the latest aliases besides the docs? I thought this pattern was convention, but the few other pieces of software I just checked out (MySQL, Postgres, Bintray) don't seem to have a latest alias—at least not an easily-discoverable one.

**Comment by mberhault** [comment]
I have no strong objections, especially not to making it a redirect instead of separate tarballs.
Even a redirect is not necessarily standard practice but it's useful for the frequent releases like our betas. This will definitely not be the case with actual releases.

**Comment by bdarnell** [comment]
For historical reference: cockroachdb/docs#209 was the impetus for publishing `latest` tarballs. I'd be OK with getting rid of them with the move to 1.0 since we would then expect people to stick to one version instead of tracking the latest betas as they are released every ~week.

**Comment by tamird** [comment]
Another idea: make `latest` an HTTP redirect but move the `latest` s3 Put to the docs repo's deployment script. The docs would use dated URLs so that they are stable, but we would keep `latest` for certain conveniences such as deployment scripts and (maybe) https://github.com/cockroachdb/cockroach-go/issues/19.

**Comment by benesch** [comment]
That's my ideal too.

**Comment by petermattis** [comment]
Where did we land on this?

**Comment by benesch** [comment]
Could anyone with thoughts on this issue chime in on cockroachdb/docs#1375? I want to get this resolved first thing next week.

**Comment by benesch** [comment]
We no longer link to the latest tarballs from our docs, so going to consider this done.
