### ISSUE TITLE
brew upgrade does not appear to be working

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#14750]
I installed CockroachDB 20170309 a while ago using brew install. I wanted to upgrade to the newest version of CockroachDB. I tried brew update, then brew upgrade cockroach, and received this:

```brew upgrade cockroach
Error: cockroachdb/cockroach/cockroach 20170309 already installed

I would have expected it to upgrade to 20170330

**Comment by benesch** [comment]
Working theory: this is a Homebrew bug (or subtle `brew update` breakage) that's out of our control. @dianasaur323's going to try upgrading to this week's beta and consider this resolved if it works.

**Comment by dianasaur323** [comment]
@benesch working! Excellent - closing out.
