### ISSUE TITLE
storage: OOM on `navy` seems to be caused by `timestampCache`

### ISSUE THREAD

**Issue by asubiotto** [cockroachdb/cockroach#14765]
2 nodes of the 6 on `navy` OOMed. Looking at the memory profile (space in use at sample time) I found that the space in use by the timestampCache is pretty high (if I'm reading the web output correctly around 2.5GiB):
![image](https://cloud.githubusercontent.com/assets/10560359/24877787/9491638a-1dfe-11e7-8cac-b9ba2199e272.png)

This might be because of some mistakes in keeping track of the `timestampCache.bytes` which was fixed in #14760. Keeping this issue open to document this failure and will close if we don't see it for a while.

**Comment by dianasaur323** [comment]
@asubiotto assigning you so that you can close out when appropriate

**Comment by petermattis** [comment]
@asubiotto Is it time to close this out?

**Comment by asubiotto** [comment]
Haven't seen this happen again.
