### ISSUE TITLE
UI: Widget displays above table.

### ISSUE THREAD

**Issue by manuelmenzella** [cockroachdb/cockroach#14772]
In the "Live Nodes" page, the summary widget blocks the information table.

http://localhost:8080/#/cluster/nodes

http://imgur.com/a/v6iFH

**Comment by vivekmenezes** [comment]
@manuelmenzella thanks for reporting this problem

**Comment by dianasaur323** [comment]
Should be fixed with https://github.com/cockroachdb/cockroach/issues/13945
