### ISSUE TITLE
restore: NotLeaseHolderError when restoring TPC-H scale factor 10 data

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#14784]
Build: 725ea82
Config: 6-node Azure cluster (Standard_D3)

While trying to RESTORE a backup of data for TPC-H scale factor 10 (~23 GB), I've run this issue:

>root@:26257/> RESTORE tpch.* FROM 'azure://...../scalefactor-10';
>pq: importing 813 ranges: writebatch [/Table/58/9/54613/79612/233862530031812609/0,/Table/58/9/54658/604645/233862242939731969/0/NULL): result is ambiguous (Raft re-proposal failed: [NotLeaseHolderError] range 52: replica {2 2 2} not lease holder; current lease is repl={4 4 4} start=1491875884.347312985,0 epo=2 pro=1491875884.347317085,0)

In the node 2 logs, I see the only messages that pertain to this key range:

>W170411 01:54:18.978691 63316 kv/dist_sender.go:1174  [s2,r52/2:/Table/58/9/5{2987/1…-4905/1…},@c421aaa000,n2] have been waiting 1m0s sending RPC to r52 for batch: WriteBatch [/Table/58/9/54567/529561/233878886285279233/0,/Table/58/9/54613/79612/233859312527245313/0/NULL)

> W170411 01:55:33.184925 64033 storage/replica.go:2292  [n2,s2,r52/2:/Table/58/9/5{2987/1…-4905/1…},@c421aaa000] have been waiting 1m0s for proposing command WriteBatch [/Table/58/9/54567/529561/233878886285279233/0,/Table/58/9/54613/79612/233859312527245313/0/NULL)

>W170411 01:59:29.528451 64033 storage/replica.go:1709  [n2,s2,r52/2:/Table/58/9/5{2987/1…-4905/1…},@c421aaa000] context canceled before command queue: WriteBatch [/Table/58/9/54567/529561/233878886285279233/0,/Table/58/9/54613/79612/233859312527245313/0/NULL)

This has happened twice so far (out of 3 attempted RESTOREs).

Logs from all nodes:
[logs.zip](https://github.com/cockroachdb/cockroach/files/913279/logs.zip)

**Comment by cuongdo** [comment]
I'm not sure who to assign this to, so please reassign if needed @bdarnell & @danhhz.

**Comment by cuongdo** [comment]
Actually, this may be a more inclusive set of relevant logs:

> W170411 01:54:18.978691 63316 kv/dist_sender.go:1174  [s2,r52/2:/Table/58/9/5{2987/1…-4905/1…},@c421aaa000,n2] have been waiting 1m0s sending RPC to r52 for batch: WriteBatch [/Table/58/9/54567/529561/233878886285279233/0,/Table/58/9/54613/79612/233859312527245313/0/NULL)

> W170411 01:54:19.056707 63317 kv/dist_sender.go:1174  [s2,r52/2:/Table/58/9/5{2987/1…-4905/1…},@c421aaa000,n2] have been waiting 1m0s sending RPC to r52 for batch: WriteBatch [/Table/58/9/54613/79612/233862530031812609/0,/Table/58/9/54658/604645/233862242939731969/0/NULL)

> W170411 01:55:32.560146 64029 storage/replica.go:2292  [n2,s2,r52/2:/Table/58/9/5{2987/1…-4905/1…},@c421aaa000] have been waiting 1m0s for proposing command WriteBatch [/Table/58/9/54613/79612/233862530031812609/0,/Table/58/9/54658/604645/233862242939731969/0/NULL)

> W170411 01:55:33.184925 64033 storage/replica.go:2292  [n2,s2,r52/2:/Table/58/9/5{2987/1…-4905/1…},@c421aaa000] have been waiting 1m0s for proposing command WriteBatch [/Table/58/9/54567/529561/233878886285279233/0,/Table/58/9/54613/79612/233859312527245313/0/NULL)

> W170411 01:59:29.528451 64033 storage/replica.go:1709  [n2,s2,r52/2:/Table/58/9/5{2987/1…-4905/1…},@c421aaa000] context canceled before command queue: WriteBatch [/Table/58/9/54567/529561/233878886285279233/0,/Table/58/9/54613/79612/233859312527245313/0/NULL)

**Comment by danhhz** [comment]
The `have been waiting 1m0s for proposing command WriteBatch` messages are not surprising right now, given that we don't rate limit sending them out.

I don't quite know what to make of this error yet. The way restore works is that it runs "Import" to download the files and send out "WriteBatch" requests. Import tries to run on leaseholders to save a network hop, but it uses the normal client.DB and doesn't need to be on the leaseholder for correctness. The WriteBatch commands it sends out go through the normal mechanism.

Which all means that AFAICT there shouldn't be any RESTORE specific leaseholder wonkyness here. We do however probably need to rate limit some of this stuff more, since there's a number of things we're stressing more than the usual sql codepaths do. I'm uncomfortable with not understanding the underlying behavior here, but it's entirely possible that the ratelimiting will help with this

**Comment by bdarnell** [comment]
> The have been waiting 1m0s for proposing command WriteBatch messages are not surprising right now, given that we don't rate limit sending them out.

Then I think you need to rate-limit them. NotLeaseHolderError is not a problem on its own, but it becomes ambiguous when it is combined with a proposal timeout like this. In general, ambiguous results are possible and we may need to think about how to idempotently retry the parts of a restore when they happen. 

#12490 might help with this too, but that was just bumped from the 1.0 milestone.

**Comment by danhhz** [comment]
This happened again on the 2tb restore
```
importing 16384 ranges: writebatch [/Table/51/1/1996216615416052848/"bb3b72d2-ed93-43af-a6c8-2a35a1f733a1"/12285928/0,/Table/51/1/1996230109315663822/"a161e34a-841f-43e8-adfa-d186b185df22"/11256446/0/NULL): result is ambiguous (Raft re-proposal failed: [NotLeaseHolderError] range 8396: replica {10 10 2} not lease holder; current lease is repl={7 7 4} start=1492555807.399457288,0 epo=4 pro=1492555807.399461528,0)
```
I'll take a look at this tomorrow.
