### ISSUE TITLE
storage: timestamp cache panic: bad reqSize: 72 < 160

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#14793]
ERROR: a panic has occurred!
If no details are printed below, check the log file for details.
panic: bad reqSize: 72 < 160 [recovered]
	panic: bad reqSize: 72 < 160 [recovered]
	panic: bad reqSize: 72 < 160

goroutine 4079 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc420c46640)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:199 +0x94
panic(0x199eac0, 0xc422978b90)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/storage.(*Store).Send.func1(0xc423c71538, 0xc423c715b0, 0x14b461439c65760a, 0x0, 0xc423c715a8, 0xc42072ac00)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2498 +0x224
panic(0x199eac0, 0xc422978b90)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/storage.(*timestampCache).ExpandRequests(0xc420581b20, 0x14b461439c5bb6ae, 0xc400000000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/timestamp_cache.go:632 +0x612
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).applyTimestampCache(0xc42370e900, 0xc4229dfea0, 0xc422ed0000, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1870 +0xeb
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).tryExecuteWriteBatch(0xc42370e900, 0x7f81206423c0, 0xc422ed00c0, 0x14b461439c5bb6ae, 0x0, 0x500000005, 0x3, 0x2c, 0x0, 0xc422a64680, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2239 +0xd4f
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).executeWriteBatch(0xc42370e900, 0x7f81206423c0, 0xc422ed00c0, 0x14b461439c5bb6ae, 0x0, 0x500000005, 0x3, 0x2c, 0x0, 0xc422a64680, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2104 +0x98
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).Send(0xc42370e900, 0x7f81206423c0, 0xc422ed00c0, 0x14b461439c5bb6ae, 0x0, 0x500000005, 0x3, 0x2c, 0x0, 0xc422a64680, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1455 +0x229
github.com/cockroachdb/cockroach/pkg/storage.(*Store).Send(0xc42072ac00, 0x7f81206423c0, 0xc422ed0030, 0x14b461439c5bb6ae, 0x0, 0x500000005, 0x3, 0x2c, 0x0, 0xc422a64680, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2614 +0x645
github.com/cockroachdb/cockroach/pkg/storage.(*Stores).Send(0xc420c82100, 0x7f81206423c0, 0xc422e2bec0, 0x0, 0x0, 0x500000005, 0x3, 0x2c, 0x0, 0xc422a64680, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/stores.go:187 +0x1cf
github.com/cockroachdb/cockroach/pkg/server.(*Node).batchInternal.func1(0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:834 +0x18c
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr(0xc420c46640, 0xc423c71840, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:263 +0x105
github.com/cockroachdb/cockroach/pkg/server.(*Node).batchInternal(0xc421b13b80, 0x7f81206423c0, 0xc422e2be90, 0xc422c7d1a8, 0xc422e2be90, 0x1f, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:845 +0x20a
github.com/cockroachdb/cockroach/pkg/server.(*Node).Batch(0xc421b13b80, 0x7f81206423c0, 0xc422e2be90, 0xc422c7d1a8, 0x1f, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:862 +0x99
github.com/cockroachdb/cockroach/pkg/kv.(*grpcTransport).SendNext.func1.1(0xc4210e2410, 0xc422c7d180, 0x7f81206423c0, 0xc422e2be00, 0x0, 0x0, 0xc421ce2f80)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/transport.go:192 +0x46e
github.com/cockroachdb/cockroach/pkg/kv.(*grpcTransport).SendNext.func1(0xc4210e2410, 0xc422c7d180, 0x7f81206423c0, 0xc422e2be00, 0x2807340, 0xc422c7d220, 0xc422444a20)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/transport.go:206 +0x7e
created by github.com/cockroachdb/cockroach/pkg/kv.(*grpcTransport).SendNext
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/transport.go:210 +0x140

ERROR: exit status 2

**Comment by tamird** [comment]
Didn't @petermattis fix this yesterday?

**Comment by RaduBerinde** [comment]
Ah, you're right. Will resync and try again.
