### ISSUE TITLE
restore: 2tb dataset doesn't finish

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#14792]
Running `RESTORE datablocks.* FROM 'redacted-2tb-backup'` gets stuck and never finishes.

**Comment by danhhz** [comment]
The first thing that happens is splits. The ~16k splits work fine on a 1 node cluster, but seem to lock up on a 3 node cluster. Rate limiting them to 100/second seems to work locally with a 3 node roachdemo cluster.

I'd like to know why dumping them all at once doesn't work, but I've seen similar badness from dumping all the Export commands in backup and am thinking about rate limiting that, too. In the interest of making progress, I'm going to merge the various rate limitings and file issues to look into what is breaking.

**Comment by danhhz** [comment]
cc @mjibson

**Comment by andreimatei** [comment]
@cuongdo has seen similar badness with large numbers of splits; where's that issue? I don't seem to find it now.

**Comment by danhhz** [comment]
when testing with rate limiting, it seems we then run into https://github.com/cockroachdb/cockroach/issues/14776 and nodes start crashing

**Comment by danhhz** [comment]
#15415 seems to have addressed this. There's still some room to move in not affecting liveness, but I'll leave that to be tracked in #15341
