### ISSUE TITLE
backup/restore: azure doesn't work if there's a `+` in the key

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#14804]
It fails with a complaint about base64 encoding. We can currently get around this by regenerating keys in the azure portal until we get one without a `+`, but this is bad to tell users. It's possible the azure package has been updated and we need to get a newer version.

**Comment by bdarnell** [comment]
There is a url-safe variant of base64 (replacing `+` and `/` with `-` and `_`). Can we make it use that instead, or is this all under azure's control and not something we can control?

**Comment by mjibson** [comment]
We haven't done any investigation yet, but I think it's not something we control since we aren't doing any base64 encoding ourselves.

**Comment by mjibson** [comment]
This is happening because we weren't correctly escaping the password parameter using url.Values.Encode. All it means is you can't copy and paste the password directly into the URL, but have to use your language's URL-generation library to do things correctly. I do not think it makes sense for us to add smarts around this to try to detect it. I think we should close this issue as not a bug. @danhhz agree?

**Comment by danhhz** [comment]
Agree.

@bdarnell we get these from the azure portal, so I don't think it's something we can control
