### ISSUE TITLE
security: allow root user to access status/admin endpoints

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#14839]
Some of the CLI commands need node user authentication to function properly.

Specifically, anything using the status client: `nodes ls`, `gen haproxy`, `debug zip` or some of the admin endpoints (`debug zip`).

The issue on the admin endpoints seem to be the ones that turn into sql queries.
eg:
```
func (s *adminServer) Databases(
  ctx context.Context, req *serverpb.DatabasesRequest,
) (*serverpb.DatabasesResponse, error) {
  args := sql.SessionArgs{User: s.getUser(req)}
  ctx, session := s.NewContextAndSessionForRPC(ctx, args)
  defer session.Finish(s.server.sqlExecutor)
  r := s.server.sqlExecutor.ExecuteStatements(session, "SHOW DATABASES;", nil)
  defer r.Close(ctx)
  if err := s.checkQueryResults(r.ResultList, 1); err != nil {
    return nil, s.serverError(err)
  }
```

@knz:
Does `sqlExecutor.ExecuteStatements` perform the KV operations itself with the specified user? If so, that's definitely a no-no, only the Node user is allowed to do that.

The status endpoint fails on the node list:
```
// Nodes returns all node statuses.
func (s *statusServer) Nodes(
  ctx context.Context, req *serverpb.NodesRequest,
) (*serverpb.NodesResponse, error) {
  ctx = s.AnnotateCtx(ctx)
  startKey := keys.StatusNodePrefix
  endKey := startKey.PrefixEnd()

  b := &client.Batch{}
  b.Scan(startKey, endKey)
  if err := s.db.Run(ctx, b); err != nil {
    log.Error(ctx, err)
    return nil, grpc.Errorf(codes.Internal, err.Error())
  }
```

Not sure why that's propagating the user from the client request though.

**Comment by knz** [comment]
To your specific question "Does `ExecuteStatements` perform the KV operations itself with the specified user?" the answer is yes.

**Comment by knz** [comment]
(I do not know anything yet about the admin RPC code, so I can't be of any immediate help further)

**Comment by mberhault** [comment]
It seems the problem with the `status.Nodes` call is that the received context which contains certs is re-used for further communication. That eventually turns into a kv batch call which fails on non-root users.

Using a new context works fine:
```
// Nodes returns all node statuses.
func (s *statusServer) Nodes(
  ctx context.Context, req *serverpb.NodesRequest,
) (*serverpb.NodesResponse, error) {
  log.Infof(ctx, "Context: %+v", ctx)
  ctx = context.Background() // <<<----- this bit here.
  ctx = s.AnnotateCtx(ctx)
  startKey := keys.StatusNodePrefix
  endKey := startKey.PrefixEnd()

  b := &client.Batch{}
  b.Scan(startKey, endKey)
  if err := s.db.Run(ctx, b); err != nil {
    log.Error(ctx, err)
    return nil, grpc.Errorf(codes.Internal, err.Error())
  }
```

So it looks like we're using way too much information from the context when issuing another request.
Who's our context expert@ @andreimatei?

**Comment by tamird** [comment]
Indeed, see https://github.com/cockroachdb/cockroach/blob/673c2c9a546657123eaeb42f35cbdac0d85b5d61/pkg/kv/db.go#L93 where we pull the information from the context.

An alternative to replacing the context completely is https://godoc.org/google.golang.org/grpc/peer#NewContext.

**Comment by mberhault** [comment]
ah. damn. If the right thing to clear just the credentials? or the entire context?
If the latter, we lose some tracing information.

**Comment by tamird** [comment]
I think just the credentials; doesn't `peer.NewContext` do the right thing?

**Comment by mberhault** [comment]
`peer.NewContext` creates a new context for the given peer, but we don't quite know what that is at this time.
Instead, we want to make sure all requests issued by the node are setup with the client settings determined at initialization time and not the incoming connection's context.

**Comment by tamird** [comment]
So why not create a Peer at initialization time and pass that to peer.NewContext?

**Comment by mberhault** [comment]
Because we shouldn't have to, those are filled in by the server on receipt. We already allow unset peers in `batchInternal` so local shortcuts can clear the context.
I think dropping the peer from the context is the right way to go or rather creating a new context without the peer (since you can't drop values from a context. grr)

**Comment by tamird** [comment]
How are you going to drop the peer from the context

**Comment by mberhault** [comment]
I think we can just create a new one. If there are any tracing fields we care about, we can set those.

**Comment by tamird** [comment]
It's not just tracing; these contexts also propagate cancellation.

**Comment by mberhault** [comment]
ok, so we can pick specific values to propagate, but that's at risk of missing some.
I'll see if we can do something that will make the grpc client ignore the peer, or if we can fill it in with a proper one. Either way, it's a pain.
