### ISSUE TITLE
What does it mean by start key must be greater than LocalMax?

### ISSUE THREAD

**Issue by ggaaooppeenngg** [cockroachdb/cockroach#14842]
**QUESTION**

I got this error below, when I runs internal client command `cockroach kv scan "" "2"`.
"Error: start key in [/Min,/System/tsd/cr.store.replicas.commandqueue.combinedqueuesize/1/10s/2017-04-10T08:00:00Z) must be greater than LocalMax"

It seems empty start key is not allowed, what's LocalMax?

**Comment by petermattis** [comment]
The `cockroach debug kv scan` command is very low-level and allowed you to generate a `ScanRequest` with an invalid start key (`/Min`). Have you seen this error outside of using the `debug kv scan` command?

We might want to get rid of the `debug kv` commands. They were useful early in the life of cockroach, but I think they have outlived their purpose. The mutating commands (`{put,cput,inc,del,delrange}`) are particularly dangerous. I'm having trouble imagining a scenario where using these commands would be appropriate.

Cc @cockroachdb/core

**Comment by bdarnell** [comment]
+1 to getting rid of `cockroach debug kv`. I haven't used any of these commands since the introduction of SQL.

I would also move `cockroach range split` under `debug`. I don't want to get rid of it because I have plans to use it for testing splits in the meta2 range, but regular users should be using the SQL `SPLIT` command instead.

**Comment by a-robinson** [comment]
SGTM

**Comment by ggaaooppeenngg** [comment]
I like the design of cockroach, the underlying sorted key value map, and currently find no alternative.

So I moved internal/client out, in order to use cockroach as key value database avoiding SQL layer. I am also considering it dangerous to do it in fact, but have not came across problems in my demo development, maybe if I keep doing this, I will.

I want a global replicated key value database with transaction, and if there is a pure raw API to do get and put, I think it will be better to handle and manage the data, I read your post about mapping SQL to key and value, but my model is very simple, SQL makes my feel a little overhead.

Since it will be deprecated and not in plan, maybe I should use simple primary key and values as SQL model.

**Comment by petermattis** [comment]
> Since it will be deprecated and not in plan, maybe I should use simple primary key and values as SQL model.

This is what we currently recommend. See https://www.cockroachlabs.com/docs/frequently-asked-questions.html#can-i-use-cockroachdb-as-a-key-value-store.

**Comment by petermattis** [comment]
I'll take care of removing the `debug kv` commands and moving `range` to `debug range`.

**Comment by petermattis** [comment]
> I would also move cockroach range split under debug. I don't want to get rid of it because I have plans to use it for testing splits in the meta2 range, but regular users should be using the SQL SPLIT command instead.

FYI, `range {ls,split}` already live under `debug range {ls,split}`.
