### ISSUE TITLE
storage: upreplicate test (1->3, 10GB) timing out

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#14852]
Failures:
https://teamcity.cockroachdb.com/viewLog.html?buildId=215349&tab=buildResultsDiv&buildTypeId=Cockroach_AllocatorTest1to310g
https://teamcity.cockroachdb.com/viewLog.html?buildId=217520&buildTypeId=Cockroach_AllocatorTest1to310g&tab=buildLog

As background, this test starts with 1 node w/ 10 GB of data. Then, it adds 2 nodes and waits for the cluster to up-replicate (it measures stddev of range count). During this time, `block_writer` and `photos` are running.

While running the test manually and monitoring admin UI, it looks like it takes several seconds for a single range to be replicated, which is much slower than I expect.

So, the test is timing out after 2 hours. Previously, it would comfortably finish in 40-50 minutes.

Setting `COCKROACH_PREEMPTIVE_SNAPSHOT_RATE=64000000` in the environment restores the previous performance of the test.

I'm not sure what the right course of action here is.

**Comment by petermattis** [comment]
Up-replicating 10 GB of data to 2 additional nodes involves transferring 20 GB of data. Doing that in 50 min implies a rate of ~7 MB/sec. The default value for `COCKROACH_PREEMPTIVE_SNAPSHOT_RATE` limits preemptive snapshots to 2 MB/sec, so I would expect the up-replication to take almost 3 hours. 

Perhaps we need to distinguish between snapshots used for up-replication and those used for rebalancing.

In the short term, can we bump the value of `COCKROACH_PREEMPTIVE_SNAPSHOT_RATE` for this test to 8 MB?

**Comment by cuongdo** [comment]
I'll try bumping the snapshot bandwidth. As a reference point, this was our performance prior to the bandwidth limiting of preemptive snapshots:

`photos`: 10-40 qps (there's no long-term average)
`block_writer`: 99 qps

After:

`photos`: 40-80 qps
`block_writer`: 686 qps

So, the change is definitely benefitting `photos` and `block_writer` performance (at the expense of up-replication).

**Comment by cuongdo** [comment]
Bumping `COCKROACH_PREEMPTIVE_SNAPSHOT_RATE` to 8 MB/s worked. In real use, I wonder what the right strategy is. Possibly something like `min(guaranteed_minimum, observed_bandwidth * % of bandwidth reserved for snapshots)` in the longer-term and some higher rate for up-replication in the short-term.

**Comment by bdarnell** [comment]
Is upreplicating from a single node with data a use case we really care about? It seems far more common to create a 3+ node cluster while empty and then insert the data. I don't think it's going to be worthwhile to create a special case that would apply here but not to other uses of snapshots.

**Comment by cuongdo** [comment]
It's probably not important to adjust bandwidth throttling just for this test/scenario. However, I wonder about other cases that trigger a lot of up-replication, such as bulk ingestion of data, which causes lots of splits.

**Comment by bdarnell** [comment]
Ingesting data into an existing multi-node cluster causes splits which lead to *rebalances*, not up-replication. The ranges are fully replicated from the beginning, so this looks like the lowest priority of snapshot (as opposed to repairs performed due to a node death, which sounds like it should be high priority and yet it was the reason we instituted the bandwidth limits in the first place).

The best way to handle bulk ingestion is to pre-split and scatter the ranges while they're still empty; then you only have to worry about the bandwidth from the ingestion itself.

**Comment by dianasaur323** [comment]
Is there an action item here / what milestone should we place it in?

**Comment by cuongdo** [comment]
I saw that this had a dramatic effect on run times for our nightly allocator tests, which test both up-replication and rebalancing, under `photos` and `block_writer` load.

However, until we have more data to prove that there is a general problem, we should probably take no action for now. It's simple to bump the default for `COCKROACH_PREEMPTIVE_SNAPSHOT_RATE` anyway.

**Comment by tamird** [comment]
I'm not sure it's related, but the 1->6 test (https://teamcity.cockroachdb.com/viewType.html?buildTypeId=Cockroach_Nightlies_AllocatorTest1to6_108g) hasn't run since December - someone paused the triggers on it.

Does anyone know why it was disabled? Should we reenable it?

**Comment by petermattis** [comment]
@cuongdo I believe the actionable work here is captured in #14768. Is there anything else to do?

**Comment by cuongdo** [comment]
#14768 seems to cover this, and the 1->3 allocator nightly test would make a good test for that, since it combines `photos`, `block_writer`, and up-replication.

**Comment by a-robinson** [comment]
Closing this since it doesn't look like there's anything actionable.
