### ISSUE TITLE
sql: shift operator for ints needs a modulo

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#14874]
postgres:

```
postgres=# select 1::int << 64;
 ?column? 
----------
        1
(1 row)
```

cockroach:
```
root@:26257/> SELECT 1::int << 64;
+--------------+
| 1::INT << 64 |
+--------------+
|            0 |
+--------------+
(1 row)
```

It appears that, for integers, Postgres takes the modulo of the second operand in shift operations. (It doesn't retain this behavior when working on bytes.) It is unclear if we want to copy it. I'm inclined to leave this as is, since the Postgres behavior is surprising and inconsistent.

@jordanlewis thoughts?

**Comment by bdarnell** [comment]
Tangentially related: In #12481 we're debating whether it's ok to support the `int4` name as an alias for our 64-bit integer type (and either ignoring the "4" or using a CHECK constraint to limit the range of the value). If we decide to follow postgres here, that would argue that we shouldn't support an `int4` that still acts like an `int8` for certain operations.

**Comment by jordanlewis** [comment]
I'm happy to not support this surprising (and unhelpful?) behavior.
