### ISSUE TITLE
build: document the tool dependencies

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#14889]
I have a regular Ubuntu deployment here and I cannot run `make protobuf` nor `go generate` any more on my CockroachDB source tree. Same applies on the latest port tree on a latest FreeBSD upgrade.

All my tool dependencies are up-to-date using standard distribution packages and yet they are considered "too old" by the build system.

The dependency on Go 1.8 is well-documented but none of the other tool version requirements are to be found in `CONTRIBUTING.md` nor `build/README.md`.

The particularly unpleasant situation is that any non-UI-related stuff now requires node and yarn versions which are nowhere to be found in standard distributions. I am not too fond of having to manage custom installs of all tools myself.

Therefore here are some suggestions in increasing amount of usefulness:

1. document the list of tool dependencies and versions in CONTRIBUTING.md with the links to the source packages necessary to upgrade to that version;
2. document the steps required on off-the-shelf distro releases (at least Ubuntu/Debian, I could probably fork that to FreeBSD after a first version is written) to obtain all the non-standard tools;
3. provide and maintain a standard VM image with all the tools necessary and sufficient to develop CockroachDB.

**Comment by knz** [comment]
Note that this situation is recent; just last month about the same date in March this wasn't an issue.

**Comment by knz** [comment]
Another suggestion:

4. provide an acceptance test which runs a script that installs all deps and then runs a full build of cockroachdb on top of a blank standard linux install.

**Comment by knz** [comment]
Note that this issue is somewhat more serious than it seems: **if we are to seek help from external contributors, we should ensure that the onramp to getting their help is as smooth as possible. This issue highlights that we may be blocking external contributions without realizing it.**

**Comment by tamird** [comment]
We already document that the builder image is to be used to generate UI
code, for exactly this reason. I'll take another pass to make sure we
advise to do the same for protocol buffers, but I am staunchly against
supporting standard distributions for these tasks; this is just not
tractable in JS-land.

**Comment by bdarnell** [comment]
+1 to documenting what we require outside the builder image (just like we document the C++ compiler requirements in CONTRIBUTING.md). It doesn't have to be robustly tested but we should make a best effort to document things like which version of node.js we require and the fact that we need yarn.

**Comment by RaduBerinde** [comment]
The lack of documentation for this has been a problem for me too. I have never used these tools and by the time I have to upgrade one I forget how I installed it last time. A list of tools and required versions would definitely help.

For the record, these two are definitely needed (commands for Ubuntu pasted):
 - node: https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions 
```
curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
sudo apt-get install -y nodejs
```

 - yarn: https://yarnpkg.com/lang/en/docs/install/#linux-tab
```
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt-get update && sudo apt-get install yarn
```

**Comment by dianasaur323** [comment]
@knz is this an issue that effects anyone installing on Ubuntu? or is this developer specific?

**Comment by tamird** [comment]
This is a developer-facing issue only.

**Comment by dianasaur323** [comment]
Well, we kind of say that we are a "single binary with no dependencies," so I think we should address this.... Perhaps @jseldess  can take a look to see if we can tackle this as a known limitation.

**Comment by tamird** [comment]
No, this has absolutely nothing to do with end users.

**Comment by dianasaur323** [comment]
Oh god, I'm sorry. I completely misread that. Struggles.... let's worry about this post 1.0. Doing Q3 2017 milestone.

**Comment by petermattis** [comment]
To be clear, the developers in question are CockroachDB developers, not developers using CockroachDB.
