### ISSUE TITLE
sql: ambiguous error during benchmark

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#14896]
running `make bench PKG=./pkg/sql`:

```
BenchmarkSQL/InsertDistinct100/MultinodeCockroach-4             --- FAIL: BenchmarkSQL/InsertDistinct100/MultinodeCockroach-4        bench_test.go:829: pq: result is ambiguous (Raft re-proposal failed: unexpected value: raw_bytes:"7\210\332\010\n" timestamp:<wall_time:1492091315841929799 logical:0 > )
```

Andrei says:

> it’s prolly worth filing a bug for that ambiguous result error and try Spencer as an assignee. Although ambiguous results are sometimes a fact of life, they probably shouldn’t happen in that benchmark where nodes aren’t crashing. In the past we’ve improved things as a result of looking into them.

**Comment by spencerkimball** [comment]
This might be ameliorated, if not fixed by #15605.

**Comment by petermattis** [comment]
@tamird Didn't you fix the ambiguous errors that were occurring during benchmarks?

**Comment by tamird** [comment]
Yep!
