### ISSUE TITLE
sql: regression in binary evaluation of subqueries

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#14895]
`TestRebalance_3To5Small_WithSchemaChanges` failed last night with the error `allocator_test.go:200: time: unknown unit ms- in duration -124ms-813��s`. The string `-124ms-813��s` is the result of the query `SELECT (SELECT MAX(timestamp) FROM rangelog) - (SELECT MAX(timestamp) FROM eventlog WHERE eventType=$1)`, which appears not to have been fully evaluated.

https://teamcity.cockroachdb.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=219625#_focus=2351

**Comment by cuongdo** [comment]
I'm already looking at this. I don't think this is a subquery issue. I think it's caused by trying to parse a `duration.Duration` using `time.ParseDuration`

**Comment by tamird** [comment]
What do you mean? The result of the query above seems to be the literal string `"-124ms-813��s"`.

**Comment by cuongdo** [comment]
The timestamps are full timestamps. They'd be significantly larger than 124 ms.

**Comment by cuongdo** [comment]
I think that the clock is jumping backward (Azure hypervisor weirdness), and the way we print `Duration`s out is by concatenating  (milliseconds)ms and (microseconds)us. The problem is that both of these are negative, which is producing this strange output.
