### ISSUE TITLE
sql: unexpected formatting for negative INTERVALs

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#14906]
What happens:

```
root@:26257/> SELECT now() - (now() + '5s2ms':::INTERVAL);
+--------------------------------+
| now() - (now() + '5s2ms':::INTERVAL) |
+--------------------------------+
| -5s-2ms                        |
+--------------------------------+
(1 row)
```

I'd expect the result to be `-5s2ms`. 

For reference, this is what PG reports:

```
postgres=#  SELECT now() - (now() + '5s2ms'::INTERVAL);
   ?column?
---------------
 -00:00:05.002
(1 row)
```

**Comment by knz** [comment]
This is expected behavior... What's wrong exactly?

**Comment by knz** [comment]
We need negative signs on the individual parts, in particular because our `Duration` struct has 3 fields and each can have a sign different from the others.

**Comment by jordanlewis** [comment]
I agree that the output is a bit unintuitive, though. Humans tend not to write or read intervals with more than one negative sign inside :)

**Comment by knz** [comment]
What's the alternative then?

**Comment by knz** [comment]
Note that pg supports `-3 day 4 min -10 second` which is ... the same

**Comment by knz** [comment]
(i.e. `-3 day 4 min` is not the same as `-(3 day 4 min)` )

**Comment by cuongdo** [comment]
It's not a huge deal; it's just somewhat surprising. Is there documentation on the output format? Alternatively, does it follow a SQL or other standard?

**Comment by knz** [comment]
This is a pg extension.
