### ISSUE TITLE
build: Release builds tagged as `beta-20170413-dirty`

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#14916]
The new beta binaries at https://binaries.cockroachdb.com/cockroach-beta-20170413.linux-amd64.tgz are tagged as `beta-20170413-dirty`. It looks like some build product is not being `.gitignored` as it should be.

[Build log](https://teamcity.cockroachdb.com/viewLog.html?buildId=221497&buildTypeId=Cockroach_MergeToMaster&tab=buildLog#_focus=115&state=115)

**Comment by benesch** [comment]
Ugh, sorry. See also #14284.
