### ISSUE TITLE
perf: improve simple read-only query latency

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#14927]
The `kv` tool uses the schema:

```
CREATE TABLE IF NOT EXISTS test.kv (
  k BIGINT NOT NULL PRIMARY KEY,
  v BYTES NOT NULL
)
```

When run with `kv --read-percent 100 --concurrency 1` it will perform simple read-only queries to non-existent keys. This highlights the overhead involved in execution. The following trace was gathered using `COCKROACH_TRACE_SQL=1us` (with a few additional `log.Event` calls scattered in the code):

```
I170414 10:31:00.506894 544 sql/session.go:644  [client=[::1]:59717,user=root,n1] SQL trace:
     0.005ms      0.005ms    [client=[::1]:59717,user=root,n1] start
     0.013ms      0.008ms    [client=[::1]:59717,user=root,n1] SELECT k, v FROM test.kv WHERE k = $1
     0.020ms      0.007ms    [client=[::1]:59717,user=root,n1] plan start
     0.058ms      0.037ms    [client=[::1]:59717,user=root,n1] plan done
     0.060ms      0.002ms    [client=[::1]:59717,user=root,n1] exec start
     0.068ms      0.008ms    [client=[::1]:59717,user=root,n1] txn send
     0.075ms      0.007ms    [client=[::1]:59717,user=root,n1] dist send
     0.082ms      0.007ms    [client=[::1]:59717,user=root,n1] querying next range at /Table/51/1/0
     0.094ms      0.012ms    [client=[::1]:59717,user=root,n1] sending batch 1 Scan to r12
     0.107ms      0.013ms        [client=[::1]:59717,user=root,n1] sending request to local server
     0.121ms      0.014ms            [n1] 1 Scan
     0.126ms      0.005ms            [n1,s1,r12/1:/{Table/51-Max}] read-only path
     0.130ms      0.004ms            [n1,s1,r12/1:/{Table/51-Max}] command queue
     0.133ms      0.003ms            [n1,s1,r12/1:/{Table/51-Max}] waiting for read lock
     0.137ms      0.004ms            [n1,s1,r12/1:/{Table/51-Max}] Scan
     0.154ms      0.017ms            [n1,s1,r12/1:/{Table/51-Max}] read completed
     0.175ms      0.021ms    [client=[::1]:59717,user=root,n1] exec done
     0.178ms      0.004ms    [client=[::1]:59717,user=root,n1] SELECT 0 done
     0.182ms      0.004ms    [client=[::1]:59717,user=root,n1] done
```

The second column ("relative time") shows when an event was recorded in relation to the previous event. Note that the `[n1,s1,r12/1:/{Table/51-Max}] Scan` event took `0.017ms`. This is where the RocksDB work is actually performed. Planning took `0.037ms`. Not shown above is that parsing took `0.015ms` (this isn't captured on the trace due to when parsing occurs). Given that this is a prepared statement, the parsing could be eliminated. Similarly for planning.

The `txn send` event is recorded at the start of `TxnCoordSender.Send`. Note that the query took `0.052ms` between the call to `TxnCoordSender.Send` and arriving at `Node.Batch`.

The trace above doesn't capture the full duration of executing a pgwire command. Other logging shows that `sql/pgwire.v3conn.handleExecute` took `0.250ms` for the above query indicating that there are `0.068ms` unaccounted for, presumably somewhere in `sql/pgwire`.

Cc @cockroachdb/core, @cockroachdb/sql

**Comment by RaduBerinde** [comment]
I think one of the first steps would be to write some benchmarks for parsing and for planning (we have a single very basic benchmark for parsing, nothing for planning). There must be some low-hanging fruit there in terms of improvements, and it would be good to have something to catch regressions when major changes are made.

What are the queries like? Simple `SELECT k,v WHERE k = <something>`? (a link to the tool would work too)

**Comment by petermattis** [comment]
I've also used `go tool trace` and @knz's `COCKROACH_SQL_STMT_STATS_ENABLE`. After running `kv --read-percent 100 --concurrency 1` for ~30s, the latter showed:

```
~ ./cockroach sql
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.
root@:26257/> SELECT parse_lat_avg * 1000, plan_lat_avg * 1000, run_lat_avg * 1000, service_lat_avg * 1000, overhead_lat_avg * 1000 FROM crdb_internal.node_statement_statistics WHERE key LIKE 'SELECT k, v%';
+----------------------+---------------------+--------------------+------------------------+-------------------------+
| parse_lat_avg * 1000 | plan_lat_avg * 1000 | run_lat_avg * 1000 | service_lat_avg * 1000 | overhead_lat_avg * 1000 |
+----------------------+---------------------+--------------------+------------------------+-------------------------+
|  0.01312008862778006 | 0.03419303373898451 |  0.078959702681026 |    0.13343260351564304 |    0.007159778467851033 |
+----------------------+---------------------+--------------------+------------------------+-------------------------+
(1 row)
```

These numbers match up with the numbers in the trace. I'm guessing the slightly lower values reflect that I didn't have `COCKROACH_TRACE_SQL` enabled (which is moderately expensive).

Parsing takes ~10% of service time, planning takes ~25% and running the plan takes ~60%.

**Comment by petermattis** [comment]
Punting to 1.1 as investigation did not reveal any low-hanging fruit here.

**Comment by petermattis** [comment]
After #15639, the phase latencies for the `kv --read-percent 100 --concurrency 1` workload look like:

```
+----------------------+----------------------+--------------------+------------------------+-------------------------+
| parse_lat_avg * 1000 | plan_lat_avg * 1000  | run_lat_avg * 1000 | service_lat_avg * 1000 | overhead_lat_avg * 1000 |
+----------------------+----------------------+--------------------+------------------------+-------------------------+
|                    0 | 0.036195270259024144 | 0.0774928296612224 |    0.12238306385103326 |    0.008694963930788346 |
+----------------------+----------------------+--------------------+------------------------+-------------------------+
```

As expected, parsing consumes no time (yay!), but planning now consumes 30% of the service latency time. Note that overhead is essentially 0% for with `--concurrency=1`. Here is `--concurrency=16`:

```
+----------------------+---------------------+--------------------+------------------------+-------------------------+
| parse_lat_avg * 1000 | plan_lat_avg * 1000 | run_lat_avg * 1000 | service_lat_avg * 1000 | overhead_lat_avg * 1000 |
+----------------------+---------------------+--------------------+------------------------+-------------------------+
|                    0 |   0.099991640010743 | 0.3143297722827861 |    0.45040629088537154 |      0.0360848785918311 |
+----------------------+---------------------+--------------------+------------------------+-------------------------+
```

Surprisingly, planning has dropped to 22% and overhead has risen to 8% of service latency. I'm not sure what that is about. The overall latencies have risen, presumably because of goroutine context switching during processing of a query.

**Comment by jordanlewis** [comment]
I did a bunch of analysis on this today. I think there's plenty more low-hanging fruit to be plucked here without having to figure out how to cache a plan.

- Type checking takes 22% of the planning time. Almost half of this is spent copying `CmpOp` structs around.
- Allocating planners takes a long time too, about 15% of the planning time. This is easy to alleviate as well - since we know that a session will only use one concurrent planner when there are no parallel statements in flight, we can save a planner in the session and clear it before use every time.
- `getPlanForDesc` takes about 30% of the planning time, because allocating a `scanNode` is extremely expensive. `scanNodes` must live in the heap, but they're `7520` bytes each, without following pointers. At one `scanNode` allocation per plan, at the ~14,000 reads per second my laptop pushes, that's 100 MB/s of GC pressure for `scanNode` allocation alone. I'm not too experienced with the Go garbage collector, so I don't know how expensive that is in the scheme of things, but it doesn't seem great.

I have some in-progress patches to solve the first two issues. I don't know how to solve the last issue.

**Comment by petermattis** [comment]
Very nice that you looked into this!

I thought the session had a cached planner. I'm pretty sure it did at one time.

We could allocate the `scanNode` using a `sync.Pool`. This would reduce the GC pressure significantly. Is there an obvious place where the `scanNode` is no longer being used? I suppose you could write a `planVisitor` that walked over the plan after the query was executed and recently any `sync.Pool` allocated nodes back to their pools.

**Comment by RaduBerinde** [comment]
We should also look at making the scanNode smaller. 7k is huge, I'm sure there's some stuff to clean up in there.

**Comment by petermattis** [comment]
> We should also look at making the scanNode smaller. 7k is huge, I'm sure there's some stuff to clean up in there.

https://github.com/rsc/sizeof

```
~/Development/go/src/github.com/cockroachdb/cockroach/pkg/sql master sizeof -f scanNode
scanNode 7520
scanNode.p 0
scanNode.desc 8
scanNode.index 616
scanNode.specifiedIndex 624
scanNode.noIndexJoin 632
scanNode.cols 640
scanNode.resultColumns 664
scanNode.row 688
scanNode.valNeededForCol 712
scanNode.colIdxMap 736
scanNode.spans 744
scanNode.isSecondaryIndex 768
scanNode.reverse 769
scanNode.ordering 776
scanNode.explain 816
scanNode.rowIndex 824
scanNode.debugVals 832
scanNode.filter 880
scanNode.filterVars 896
scanNode.scanInitialized 936
scanNode.fetcher 944
scanNode.hardLimit 7480
scanNode.softLimit 7488
scanNode.disableBatchLimits 7496
scanNode.scanVisibility 7504
scanNode.noCopy 7512
```

```
~/Development/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase master sizeof RowFetcher
RowFetcher 6536
```

**Comment by RaduBerinde** [comment]
A big part of the fetcher is DatumAlloc, which includes a CollationEnvironment which has a 4k buffer. Ideally we would only allocate that if needed (and 4k seems excessive, though I'm not sure exactly what it's for). @eisenstatdavid

**Comment by knz** [comment]
Both the CollationEnvironment and scanNode can be allocated using a pool allocator. We could even avoid a common sync.Pool and its mutex overhead by having an allocation slice per session (like we do for datum arrays already). This is actionable because logical plans already have an explicit "destructor" via their `Close()` recursion.

**Comment by eisenstatdavid** [comment]
`CollationEnvironment` consists of a small map and a `collate.Buffer` that holds collation keys as they are constructed. If we forked the collation library, we could lower that 4k -- I don't think that the library authors particularly anticipated our use case.

**Comment by petermattis** [comment]
We could lazily allocate `CollationEnvironment` within `DatumAlloc`. I assume it is only used when there are collated strings.

**Comment by tamird** [comment]
Do we need to fork? Upstream may be open to changing this. I did some
archaeology; this value of 4kb has been there since "initial commit":
https://github.com/golang/exp/commit/b8afd77408752bf7128cdb1c02985fff9c8dff26#diff-4cda0ef929b958592273fcc75cde259dR147
(wait for it, this takes a while to load the highlighted line).

**Comment by petermattis** [comment]
The low-hanging and not-so-low hanging fruit has been plucked here. Filed #17158 to capture the desire to cache query plans.
