### ISSUE TITLE
cli stores all the duplicate commands

### ISSUE THREAD

**Issue by edwardsmarkf** [cockroachdb/cockroach#14938]
feature request: [referenced here](https://forum.cockroachlabs.com/t/cli-identical-command-question/560)

when using the CLI, i noticed that if i keep doing the same command (via up arrow) over and over again such as:
SELECT * FROM cockroachIsTotallyAsesome WHERE TRUE; that command seems to be saved in the command-line-recall buffer over and over again, even though each one is identical.

linux and mariadb don't remember all the duplicate commands.

the problem of course is that there are important commands such as a CREATE TABLE that get pushed pretty far down the stack.

in other words, if i do the following:

```
CREATE TABLE cockroachIsTotallyAsesome ( field1 blah blah blah);
INSERT INTO cockroachIsTotallyAsesome VALUES (blah blah blah);
SELECT * FROM cockroachIsTotallyAsesome WHERE TRUE;
SELECT * FROM cockroachIsTotallyAsesome WHERE TRUE;
-- repeated 20 times using up-arrow --
SELECT * FROM cockroachIsTotallyAsesome WHERE TRUE;
SELECT * FROM cockroachIsTotallyAsesome WHERE TRUE;
```

i should think my command-line-recall buffer would only contain:

```
SELECT * FROM cockroachIsTotallyAsesome WHERE TRUE;
INSERT INTO cockroachIsTotallyAsesome VALUES (blah blah blah);
CREATE TABLE cockroachIsTotallyAsesome ( field1 blah blah blah);
```

**Comment by knz** [comment]
Hi Edward!
Thank you for your suggestion, it does seem interesting indeed.
For now CockroachDB delegates history handling **entirely** (including the in-memory history buffer) to our dependency package readline from here: https://github.com/chzyer/readline

I have filed an issue on your behalf here: https://github.com/chzyer/readline/issues/1132
Feel free to follow-up as comments on that issue or subscribe to it to track progress.

I plan to integrate the changes from the upstream package as soon as this feature is implemented.

Thank you again

**Comment by jseldess** [comment]
Limitation documented in https://github.com/cockroachdb/docs/pull/1381.

**Comment by jseldess** [comment]
@knz, will this be cherrypicked into 1.1? If so, I'll remove the known limitation.
