### ISSUE TITLE
Better handling of "allocation failure" when running < 3 nodes

### ISSUE THREAD

**Issue by Downchuck** [cockroachdb/cockroach#1494]
Currently when executing on a single node there will be log spew:

```
root@...:/cockroach# I0625 01:16:41.552830      36 range.go:977] gossiping cluster id ... from store 1, range 1
I0625 01:16:41.553549      36 range.go:985] gossiping sentinel from store 1, range 1
I0625 01:16:41.553707      36 range.go:989] gossiping first range from store 1, range 1
E0625 01:16:41.576486      36 queue.go:266] failure processing range range=1 ["" - "\xff\xff") from replicate queue: allocator.go:204: unable to allocate a target store; no candidates available
```

That all makes sense, but for explicitly single-node installations, it is noise.

**Comment by tschottdorf** [comment]
an "explicitly single-node" installation should update their configuration so that the default zone doesn't ask ranges to have three replicas, see `./cockroach help zone`. The setup will get more polish as production moves closer.

**Comment by Downchuck** [comment]
What should the configuration be updated with ?

**Comment by bdarnell** [comment]
Currently, you'll need to create a file (e.g. `zone.cfg`) with the contents

    replicas:
    - attrs: []
    range_min_bytes: 1048576
    range_max_bytes: 67108864
    gc:
      ttlseconds: 86400

and run `cockroach zone set "" zone.cfg`. (the contents above were derived from `cockroach zone get ""` with two of the three `attrs` lines removed). All of this is likely to change in the future.

**Comment by tamird** [comment]
From #1565:
> I'm talking about returning an error from replicateQueue.process, not allocator.AllocateTarget. When AllocateTarget cannot find a target, process should not return an error.

> Even if replicateQueue doesn't do anything useful with error messages returned by AllocateTarget, they can still be useful: we will have some diagnostic UI where an admin can inspect an underreplicated range and we want to be able to report more details like "there are not enough nodes" or "nodes exist but none match requested constraints". It might make sense to separate that into a separate UI-only method, though, instead of constructing a message just to throw it away.
