### ISSUE TITLE
function in unique index [feature request]

### ISSUE THREAD

**Issue by aunz** [cockroachdb/cockroach#14965]
```sql
create table users (
  id int primary key,
  name string,
  email string,
  unique (lower(email)) -- this throws an error
);
create unique index on users (lower(email));  -- this also throws an error
```
Would be nice to have, as postgreSQL [supports](https://www.postgresql.org/docs/9.6/static/sql-createindex.html) this

**Comment by jordanlewis** [comment]
Thanks for the suggestion! This feature is known as computed indexes, which we're tracking in issue #9682 already. I'm closing this as a duplicate.
