### ISSUE TITLE
testing: add Index to `test.kv` table in prod cluster

### ISSUE THREAD

**Issue by spencerkimball** [cockroachdb/cockroach#14983]
To test online schema change, we should verify we can add an index to the value column in the `test.kv` schema, which is running across most of the prod clusters. Just choose one without chaos and verify you can add this index and drop it after it's been added.

Then we should probably do the same thing on the blue cluster, which has chaos running.

**Comment by petermattis** [comment]
Does this issue belong in the 1.0 milestone? We almost certainly need more testing of schema changes under load, but is there bandwidth to do so for the 1.0 cycle?

**Comment by jordanlewis** [comment]
We have testing in the nightlies already for this don't we?

**Comment by vivekmenezes** [comment]
it runs on nightlies but the plan here is to run it on a prod cluster. I'm not going to get to this by 2.0 so moving to 2.1. It will also be faster by then.

**Comment by nvanbenschoten** [comment]
The `schemachange` roachtests do this every night at a relatively large scale. We're moving away from prod clusters, so there's nothing more to do here.
