### ISSUE TITLE
sql: support quote_ident builtin

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#15006]
Add support for the [`quote_ident`](https://www.postgresql.org/docs/9.6/static/functions-string.html) builtin, which

> Return the given string suitably quoted to be used as an identifier in an SQL statement string. Quotes are added only if necessary (i.e., if the string contains non-identifier characters or would be case-folded). Embedded quotes are properly doubled.

This should be fairly straightforward, as we already have internal formatters that do this same work properly in `parser/format.go`.

This is used by at least one ORM-like tool, FlywayDB.

**Comment by cuongdo** [comment]
@jordanlewis please move this to 1.2 or Later, based on your evaluation of this

**Comment by flemzord** [comment]
You may have vision on the availability of this feature? Because it is important not to use ORM as Doctrine in PHP.

**Comment by knz** [comment]
@flemzord see  #19337
