### ISSUE TITLE
sql: event log is broken

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#15007]
Run cockroach with tracing and the event log enabled:

```
~ COCKROACH_ENABLE_TRACING=true COCKROACH_ENABLE_SQL_EVENT_LOG=true ./cockroach start --insecure
```

Add some load:

```
~ kv --read-percent 0 --concurrency 1
```

I would expect to see the SQL statements being added to the SQL event log at `/debug/events`. Instead, I only see a handful of entries:

```
2017/04/17 15:04:55.796678	9.623467	[::1]:58592
#   github.com/cockroachdb/cockroach/pkg/util/log.WithEventLog			/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/util/log/trace.go:66
#   github.com/cockroachdb/cockroach/pkg/sql.NewSession				/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/sql/session.go:287
#   github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).setupSession	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:314
#   github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve		/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:338
#   github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn		/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:421
#   github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func9.1		/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:593
#   github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1	/Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:137
15:04:55.802664	 .  5986	... [client=[::1]:58592,user=root,n1] preparing: SELECT k, v FROM test.kv WHERE k = $1
15:04:55.804897	 .  2232	... [client=[::1]:58592,user=root,n1] client.Txn did AutoCommit. err: <nil> txn: "unnamed" id=eed623cf key=/Table/11/1/51/1/2017-04-17T22:10:36.169126Z/1/0 rw=true pri=0.01192638 iso=SERIALIZABLE stat=COMMITTED epo=0 ts=1492466695.803758002,0 orig=1492466695.803758002,0 max=1492466696.303758002,0 wto=false rop=false
15:04:55.805076	 .   179	... [client=[::1]:58592,user=root,n1] preparing: UPSERT INTO test.kv (k, v) VALUES ($1, $2)
```

Despite the continuing load, the above is all that is ever added to the event log. If I log directly to `Session.context` everything is ok. But logging to `Session.Ctx()` disappears.

**Comment by petermattis** [comment]
Low priority, except I was going to try to demonstrate this to a user tomorrow.

**Comment by RaduBerinde** [comment]
Things go to an embedded event log only if there is no span in the context. What may have changed is that in sql we were probably not opening a span and now we do.

It's easy to change things so that everything goes both to the span and the event log, but that is not desirable for the queue event logs. We probably want a `mode` which we can store in `ctxEventLog`.

**Comment by petermattis** [comment]
> Things go to an embedded event log only if there is no span in the context. What may have changed is that in sql we were probably not opening a span and now we do.

Yeah, I saw that as I was filing the bug. But strange that a few statements go to the event log and then nothing. 

> It's easy to change things so that everything goes both to the span and the event log, but that is not desirable for the queue event logs. 

The queues do not have event logs anymore.

**Comment by RaduBerinde** [comment]
Ah, good to know. There is still the gossip event log, not sure if changing that to log everything is ok?

**Comment by petermattis** [comment]
I doubt anyone uses the gossip event log.

Do you mind sending the diff to enable output to both spans and the event
log? I can patch it in locally for demo purposes.

**Comment by RaduBerinde** [comment]
I was working on a change that adds an inclusive/exclusive flag. But I'm having second thoughts.. This would mean that ALL events (everything that we see in lightstep) would make it to the event log.

**Comment by petermattis** [comment]
> This would mean that ALL events (everything that we see in lightstep) would make it to the event log.

They'd make it to the event log if they are output on the SQL session context. That doesn't seem bad, but I may change my mind when I see the actual result.

**Comment by petermattis** [comment]
Perhaps we should be manually deciding what goes to the event log. I'm primarily interesting in seeing the queries that are executed on a session and their results.

**Comment by RaduBerinde** [comment]
> They'd make it to the event log if they are output on the SQL session context. That doesn't seem bad, but I may change my mind when I see the actual result.

The transaction's context is derived from the session context, so all contexts below would all have the event log.

**Comment by petermattis** [comment]
> The transaction's context is derived from the session context, so all contexts below would have the event log.

Hmm, ok. I guess my point still stands that I'm primarily interested in seeing the queries that are executed on a session (and their results) in the event log. Perhaps we shouldn't be trying to unify them with tracing. Or perhaps we give up on /debug/events entirely and try to add a dedicated log for SQL statements.

**Comment by RaduBerinde** [comment]
This is the change I was working on, I am hitting an issue connecting to the debug endpoint so I can't test it right now: https://github.com/RaduBerinde/cockroach/commit/14f7943287e443aef61d314ec9ad9bc402cd386d

But yeah I think probably doing something different for that special case would make more sense - perhaps log to both `session.Ctx()` and `session.context` if they are different.
