### ISSUE TITLE
distsql: ObservedTimestamps are not marshalled back to the gateway

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#15013]
The timestamps observed by `TableReaders` and such on remote nodes are not marshalled backed to the gateway. In the non-distsql world, this happens through `Transaction.Update`, which uses updated protos from all the `BatchResponse`s.

The consequence is that a transaction can be starved by continuous writers because there's no longer a bound on its uncertainty interval.

**Comment by spencerkimball** [comment]
Fixed in #21447; the sender's `AugmentTxnMeta` call used by the distSQL receiver on the `TxnCoordMeta` propagated from distSQL processors properly builds up the set of all observed timestamps.
