### ISSUE TITLE
sql: `SAVEPOINT cockroach_restart` can be erroneously called after having run other SQL statements when using DistSQL

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#15012]
We enforce that SAVEPOINT is the first statement in a txn (or in a retry of a txn) by looking at `client.Txn.CommandCount()`. If the previous statements used `DistSQL`, that `CommandCount` is not necessarily updated.
We should get rid of `CommandCount` and track the status of the txn exclusively at the sql level.

**Comment by knz** [comment]
@andreimatei I think this has been fixed, correct?

**Comment by bobvawter** [comment]
Please note that some users currently require being able to make metadata requests against virtual tables before issuing the savepoint.  Any solution to this should preserve this behavior.

**Comment by knz** [comment]
> Please note that some users currently require being able to make metadata requests against virtual tables before issuing the savepoint. Any solution to this should preserve this behavior.

I don't think this is currently supported though. "Make metadata requests" requires KV operations, which in turn engages the retry logic.

**Comment by asubiotto** [comment]
@knz has this been fixed?

**Comment by knz** [comment]
yes correct I fixed that. thanks for noticing
