### ISSUE TITLE
TestStoreRangeManySplits failed in CI with `-cpu 2`

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#1501]
Report is here https://circleci.com/gh/cockroachdb/cockroach/4060.

Hard to repro locally afaik.

**Comment by tschottdorf** [comment]
and this isn't just a slow machine? `1s` is known to time out in race mode.

**Comment by tamird** [comment]
Oh, so we should just increase it?

**Comment by tschottdorf** [comment]
I think so, up it to `5s` (our standard retry logic does doubling anyways, so that doesn't cost us on faster machines). If it comes back then, it's likely a deadlock.

**Comment by kkaneda** [comment]
Sure, sent https://github.com/cockroachdb/cockroach/pull/1516 to increase the timeout..
