### ISSUE TITLE
security: certificate details and monitoring

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#15027]
As a follow up to #1674, and part of https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/certificate_rotation.md, we need the following;
* debug page showing certificate details (filenames, expiration date, etc..)
* extract and monitor expiration dates for CA and node certificates.

**Comment by a-robinson** [comment]
We probably actually want this info in the admin UI, not just a debug page.
