### ISSUE TITLE
teamcity: Post failures as comments on existing issues when possible for master builds

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#15034]
Currently, teamcity posts repeated failures of the same test under stress to the same issue as comments rather than opening a new issue (thanks to https://github.com/cockroachdb/cockroach/pull/13329). However, it does not do this for failures of normal master builds (as discussed in https://github.com/cockroachdb/cockroach/issues/14184#issuecomment-291240684), so we still sometimes have to manually de-dupe issues. It'd be great if we also got the commenting behavior for our non-stress builds.

@justinj

**Comment by petermattis** [comment]
@a-robinson The `github-post` tool now posts comments to existing issues when possible. Do you have a recent example of where we're creating new issues rather than posting a comment to an existing issue? Please reopen if you do.

**Comment by benesch** [comment]
Sure: https://github.com/cockroachdb/cockroach/issues/26895 and https://github.com/cockroachdb/cockroach/issues/26833. Test failures on master don't use github-post. They use teamcity-post-failures.py instead.

**Comment by tschottdorf** [comment]
That has bothered me in the past too. They can just use github-post, right?

**Comment by tschottdorf** [comment]
Would it be acceptable to strip out the Rube Goldberg machine and just accept that the issue text will be a little less helpful for `master` sourced issues? We'll just pretend the test output is the test "This test failed, please click the link".

**Comment by benesch** [comment]
You need the machinery to even get the name of the test that failed, unfortunately.
