### ISSUE TITLE
UI should be reload-safe

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#1503]
Currently some stateful UI elements like log severity filtering hold all their state in the DOM; we should store this state in query parameters so that pages can be safely reloaded.

Low priority.

**Comment by tschottdorf** [comment]
it's not unlikely that we're exceeding what query parameters can do and that we should consider local storage.

**Comment by BramGruneir** [comment]
I disagree.  If we can't fit what we need in the query parameters, we've moved too far from a basic site.  Not only do should the site to be reload safe, but I want someone to be able to send the url to someone else and see the same page (regardless of which node they connect to).

If we want to store settings for certain users (i.e. default pages, languages, etc.), we can do so in the DB.

**Comment by spencerkimball** [comment]
I agree; I've yet to see local storage work well for a web application and
would like to avoid it. The amount of state we've been discussing storing
in URL parameters is still quite trivial.

**Comment by tamird** [comment]
@BramGruneir is this complete?

**Comment by BramGruneir** [comment]
It is for now, we just to ensure that any new pages that have user selectable options get the same treatment.
