### ISSUE TITLE
distsql: TPC-H query 15 can't be run with distsql because `CREATE VIEW` is unsupported

### ISSUE THREAD

**Issue by asubiotto** [cockroachdb/cockroach#15037]
This was run with `DISTSQL='always'`. I believe this should run through single-node SQL even in the 'always' mode.

**Comment by RaduBerinde** [comment]
`always` is meant as a debugging mode where you want to make sure every query is supported and run through DistSQL. It will fail any unsupported queries.

We should be using `on`, where all supported queries are run with DistSQL, and unsupported queries are run with single-node SQL..
