### ISSUE TITLE
sql: new system setting for default distSQL behavior

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#15045]
A new system setting should be introduced to define whether distsql is enabled or not in newly created client sessions.

Action items:

- [ ] create a system setting
- [ ] use it in session initialization (for sessions created via pgwire)
- [ ] ~~provide a UI for the user to change the setting (either CLI and/or UI)~~ document (in docs repo) that the user can change this via `SET CLUSTER SETTING ... = ...`

**Comment by knz** [comment]
As discussed during team meeting today. cc @cuongdo @andreimatei @RaduBerinde @asubiotto

**Comment by dt** [comment]
fwiw: cli ui for settings is `SET CLUSTER SETTING foo = bar`

**Comment by asubiotto** [comment]
How does this interact with what we already have? That is, a flag for server default and session variable for session preference.

**Comment by knz** [comment]
1) The setting must be overridable per-session anyway. So wherever the default is coming from, it needs to be copied to each new session's `DistSQLMode` when the session is created, and query execution should only look at `DistSQLMode` throughout.

2) the question is then what is the default value for `DistSQLMode` for newly created sessions. Right now the field is initialized from `defaultDistSQLMode`, which is currently set from an env var. This issue is proposing to replace the env var by a system setting, like we are doing already for other settings.

**Comment by knz** [comment]
see https://github.com/cockroachdb/cockroach/issues/15242
