### ISSUE TITLE
*: capture and report errors to some form of error tracking

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#15052]
We'll want to know if clusters are crashing / if we ship a bug /etc.

**Comment by dt** [comment]
A couple options @knz and I discussed: 
a) Using an off-the-shelf service and their client library to capture and report.
b) Using our own capture-and-report code to hit an endpoint we own which then proxies some off-the-shelf service.
c) Using our own capture-and-report code and our own recoding and tracking service.

We clearly do not have the resources for c) at the moment. a) seems iffy -- we'd be betting on a single service, and how to handle API keys is unclear.
b) seems like it has more flexibility, compared to shipping a given off the shelf solution. Probably just comes down to how much functionality is in these client libs in terms of collecting useful info.

**Comment by knz** [comment]
This is not going to fit 1.0 I fear.
Rescheduling for 1.1 instead.

**Comment by dt** [comment]
This is mostly "done" for now, as of #15393 (plus some followups). We'll file individual, more targeted issues for any individual improvements to it going forward.
