### ISSUE TITLE
sql: optimize ordering on tuple columns, distribute queries with tuple columns

### ISSUE THREAD

**Issue by eisenstatdavid** [cockroachdb/cockroach#15057]
`SELECT v FROM (SELECT (k, v), k, v  FROM kv ORDER BY k, v) ORDER BY 1` creates a tuple to use as a sort key. `ORDER BY k, v` sorts by the named columns directly. We should make the former behave like the latter to aid index selection.

Also, any intermediate render using a tuple causes distribution to be disabled.

**Comment by andreimatei** [comment]
Added a 1.1 milestone to keep track of it. Seems pretty important to me; I suspect a lot of people would type the queries with the spurious parens.

**Comment by RaduBerinde** [comment]
As an additional data point, distsql doesn't currently support moving tuples in streams, so the tuple would force the query to run non-distributed.

**Comment by eisenstatdavid** [comment]
I think this would make a decent starter project, actually. Assigning to @vivekmenezes to be reassigned.

**Comment by RaduBerinde** [comment]
This is no longer an issue with the optimizer. Note that the example here is broken, `ORDER BY 1` simply means `ORDER BY v`. I tried `ORDER BY (k, v)` and it doesn't render the tuple.
```
root@127.246.171.24:26257/defaultdb> EXPLAIN (OPT, VERBOSE) SELECT a FROM ab ORDER BY (a,b);
                info
------------------------------------
  sort
   ├── columns: a:1  [hidden: b:2]
   ├── stats: [rows=1000]
   ├── cost: 1365.30147
   ├── ordering: +1,+2
   ├── prune: (1,2)
   └── scan ab
        ├── columns: a:1 b:2
        ├── stats: [rows=1000]
        ├── cost: 1115.01
        └── prune: (1,2)
(11 rows)
```
