### ISSUE TITLE
backup/restore: do we want event log entries for BACKUP & RESTORE?

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#15161]

**Comment by dianasaur323** [comment]
ha! it's funny that there is an issue out for this - yes we do, although we are revamping how events show up in the admin UI, so there might not be any work for the bulk io team.

**Comment by dianasaur323** [comment]
Hmm... this one is already encapsulated in our work for events on graphs, so I think we can safely close this out. Reopen if you disagree!
