### ISSUE TITLE
beta-20170420

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#15174]
The candidate SHA is 9f61dd3e24edd170868a122d4220627230a75178.
Deployment status is omega, adriatic, cerulean.

[Release process checklist](https://github.com/cockroachdb/cockroach/wiki/Release-Process)
- [x] Check and verify cluster status
- [x] Tag release and push tag
- [x] [Trigger release build](https://teamcity.cockroachdb.com/viewType.html?buildTypeId=Cockroach_MergeToMaster)
- [x] Check and verify binaries
- [x] Update the [Homebrew tap](/cockroachdb/homebrew-cockroach)
- [ ] Update docs
- [x] Announce version to the registration cluster (see internal production instructions)
- [ ] Deploy the beta to the registration cluster (see internal production instructions)
- [ ] External communications for release

**Comment by bdarnell** [comment]
@mjibson would like to get #15166 included in the beta. I'd be OK with just using 9f61dd3e24edd170868a122d4220627230a75178 instead of cherry-picking it; that includes 5 other PRs

**Comment by danhhz** [comment]
Okay. I'll redeploy

**Comment by danhhz** [comment]
Done. New candidate is 9f61dd3e24edd170868a122d4220627230a75178

**Comment by danhhz** [comment]
cc @mjibson

**Comment by mjibson** [comment]
Great. Thanks. Mostly this means one less thing to put in the release notes.
