### ISSUE TITLE
sql: schema change in transactions code is confusing

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#15181]
Hey Vivek, this code looks funky to me:
https://github.com/cockroachdb/cockroach/blob/28fda73/pkg/sql/backfill.go#L394-L427

The backfill code starts a transaction and, inside it, it plans and runs a distributed backfill using DistSQL. The code really makes it look like the transaction is used to actually perform the backfill writes, but, of course, that can't be - there'd be many things wrong with trying to locally commit a transaction that had performed distributed writes.
Instead, the backfill processor ignores the transaction that was configured on the flow and performs its own transactions:
https://github.com/cockroachdb/cockroach/blob/28fda73/pkg/sql/distsqlrun/indexbackfiller.go#L116

Beyond being confusing, I think this code is pretty error-prone: the closure in backfill.go can run any number of times in case of retryable errors for _that_ transaction, but the way the code is written, we pass errors from the distributed query to this outer call to `db.Txn()`, and so internal retryable errors could cause a retry of this outer txn. We have some protection against wrong retries like this, but still.
This came up because I'm adding proper handling of retryable errors when the flow through DistSQL and I have to touch all the `distSQLReceiver`s and have them configured with a transaction, and it gave me great pause when thinking what txn do I want for the receiver in backfill.

I think this code should make it clear what the outer txn is used for and limit its scope accordingly. It's used for getting a lease and for planning (for the `rangeIterator`) - I think it should stop there and we should configure the flows without a txn.

A related thing which we discussed before was also configuring the backfillers with a maximum commit time take from the table lease.

What do you think?

cc @RaduBerinde

**Comment by vivekmenezes** [comment]
is this the same issue as https://github.com/cockroachdb/cockroach/issues/14156

It's a relative low priority for me.

The maximum commit time is issue

https://github.com/cockroachdb/cockroach/issues/14198

both these are not 1.0 issues at the moment

**Comment by andreimatei** [comment]
dupe of #14156
