### ISSUE TITLE
sql/distsql: use external storage for larger queries

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#15206]
Investigating #15194 (OOM while executing TPC-H query 3 load) was a reminder that we need to determine how to constrain the memory used by running queries while still allowing them to execute. Short-term steps might include switching to more efficient in-memory encodings, but that will be an incremental improvement.

Possible longer-term approaches include disk-based sorting and aggregation, as well as disk-based temporary tables.

cc @cockroachdb/distsql

**Comment by cuongdo** [comment]
I think we should take steps to address this in 1.1, so I've assigned myself temporarily.

**Comment by jseldess** [comment]
Documented with https://github.com/cockroachdb/docs/pull/1381

**Comment by asubiotto** [comment]
Closing in favor of a more detailed tracking issue: #16718
