### ISSUE TITLE
restore: slows down over time

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#15205]
This 2tb restore finished the first 1tb at more or less a consistent pace, but obviously slows down over time. Unclear if there's anything to do here, but opening this for discussion

This was a restore on a 10 node cluster with no other traffic. Ignore everything after the drop, one of the nodes ran out of disk

![image](https://cloud.githubusercontent.com/assets/52528/25238285/ffc3d412-25ba-11e7-8515-333a64777ff9.png)

**Comment by danhhz** [comment]
My current theory is that the naive rate limiting is at fault here. We allow num_nodes outstanding Import requests at any given time, so it's possible that some nodes weren't doing any work. Dunno why this would be more likely over time. We do start the restore by scattering leaseholders, but it's hard to see if this becomes less balanced over time because of quiescence.

Alternatively, rocksdb compactions are more expensive as we get more data. Maybe this has something to do with it.

**Comment by petermattis** [comment]
This could be related to https://github.com/cockroachdb/cockroach/issues/14108. We could take a look at the node statistics page to see if anything is increasing appreciably over time (e.g. disk I/O).

**Comment by danhhz** [comment]
It's a terraform cluster, so unfortunately I don't have grafana

**Comment by danhhz** [comment]
This seems to have been fixed sometime in the last few months

![image](https://user-images.githubusercontent.com/52528/28375723-388ee230-6c76-11e7-8b8c-5de970d2e773.png)
