### ISSUE TITLE
storage: size based raft log truncation

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#15210]
We currently truncate the raft log at 100 entries. Restores work via ~1MB WriteBatch requests, so this means the raft log can be very large without being truncated. (Anecdotally, we've seen this in testing RESTORE where the size of sstables on disk end up 2x the "Live Bytes" metric.) We should add a size component to the truncation threshold.

(someone please correct me if any of the core details are wrong here)

**Comment by petermattis** [comment]
We do size-based truncation, but the heuristics refuse to perform a truncation if the number of stale entries is less than 100. I believe that is purely historical. I think we could change the heuristics fairly easily. We'd need to adjust the heuristics in both `raftLogQueue.{shouldQueue,process}` as well as the heuristic in `Replica.handleReplicatedEvalResult` which only adds to the Raft log queue periodically. See `Replica.mu.raftLogSize`.
