### ISSUE TITLE
build: windows binaries don't have the extension .exe

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#15221]
After extracting the binary, it needs to be renamed from `cockroach` to `cockroach.exe`.

The directory looks good
`c:\binary\cockroach-latest.windows-6.2-amd64.exe\cockroach` but the file itself has the wrong extension.

**Comment by danhhz** [comment]
Ha. Yup. I also discovered this when cutting the beta

**Comment by BramGruneir** [comment]
cc: @jseldess
