### ISSUE TITLE
settings: standardize the interaction between env vars and settings

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#15242]
Right now we have a bit of a floating uncertainty about configuration:

1. when should a configuration knob have an env var or a cluster setting?
2. if both, in which order do we prioritize? e.g. should the env var be the default for the setting? Or override?
3. what about cmdline flags and session vars?

We need to clarify this in our docs, in our mind and throughout the code.

**We must ensure that users have a consistent experience of configuration, and not make different mechanisms for different configuration options, which would cause endless confusion and complexity in docs.** (let's - still - make data easy)

Proposal:

## A. env vars or setting?
    
Keep in mind:
- settings are cluster-wide, used for all nodes and all sessions.
- settings may not see their configured value appear until some non-deterministic delay after node startup.
- settings can change over time while a node is running, even in the middle of a session.
- settings are visible to users remotely (e.g. `show all cluster settings`), and configurable remotely by admins, whereas flags and env vars cannot.

General principles:

- env vars (or flags) for things that impact start-up (e.g. certs, `--join`)
- env vars (or flags) for things that must not (or cannot) change throughout node execution (e.g. `--port`, `--cache-size`)
- settings for thing that can be really convenient to change over time e.g. opt-out online registration
  - however (from Ben) "we only want to make settings that we reasonably expect *users* to need to change, and not to expose every knob that could be turned"

## B. if both, how to prioritize?

Say we have both an env var and a setting, what's the interaction?

Two choices: 

- env var has priority (override over the setting): this can be useful to override the setting for a specific node. For example we could have some general behavior set via the setting, and the use env var to do some local testing using a custom value on one (or several nodes) without impacting the rest of the cluster.

- setting has priority (override over the env var): conceptually this is as if the env var was the "default value" for the setting until the setting is set. This has weird semantics if the env var doesn't have the same value on every node: until the setting is set, after which it will have the same value everywhere, the nodes can observe different things.

My advice is to go for the first choice: **env var has priority over setting**: check if env var is set, and only if not set use the setting. We'd need a new `EnvOrDefaultSetting` for that.

## C. what about cmdline flags and session vars?

(or config files, if/when that happens)

1. we're already aligned with most other open source software regarding the interaction between cmd flags and env vars: env var value is default value for cmdline flag (flag can override). If/when we have config files, the order will (likely) be **env var lowest, then config file, then cmdline flag** (as is customary).

2. session vars vs cluster settings. Usually this is not difficult to decide -- either something that needs to change per session (or per user) or something global for the cluster. But sometime the question arises, for example as of this writing what do we do with the "distsql" flag? (#15045)

   **Likely pattern: session var at highest priority (session var always decides), but upon creating a new session the session var is initialized from something else, presumably the cluster setting.**

3. session vars vs env vars (when no cluster setting): same as above, set the session var upon session init with the value from the env var

4. what if we need to disable a session var value or something for testing/debugging? How to prevent clients from customizing the session default? If that need arises, then the mechanism would be to add a gate flag on session init and `set session var` (not `set cluster setting`) to prevent said session var to be configured in a specific way if some condition is met, presumably some debug knob

## D. woops the text above is inconsistent it seems?

So if you paid attention you'll see above two contradictory points, or rather something that yields an absurd situation:

- settings vs env vars, I suggested env vars override settings
- env vars vs flags/config files, I suggested flags override env vars

This would mean that flags/config files override settings; this does not sound right -- or rather, it will sound right to 50% of users and 50% will hate it.

What makes? **Proposal: avoid this dilemma entirely by being disciplined on not offering a customizable setting for things that are also customizable via cmdline flags or config files**

So we'd really have two sorts of customization knobs:
- things that have an env var and a cmdline flag / config file entry
- things that have an env var and a cluster setting
- but we'd have nothing that has both a cluster setting and a cmdline flag / config file entry

## E. The missing liink in the story

**settings: we actually need per-node customizable settings #15243**

Once we have per-node customizable settings then we can remove any remaining env var that overlaps with a setting, keeping env vars only in combination with cmdline flags.

**Comment by knz** [comment]
cc @bdarnell @dt @arjunravinarayan

**Comment by arjunravinarayan** [comment]
I agree with all of this, although I can only speak for those ENV vars/settings that I am familiar with, so we do need a few more people to chime in. We should also be careful and eliminate as many ENV vars as possible. ENV vars are set per-node, and that's what's really causing all the problems here. Most things do not need that level of flexibility, so I think we should move things to cluster settings even if they are not necessarily tunable by users - I think that criterion is too strict.

**Comment by dt** [comment]
my main complaint with env vars having to set them on every node and then having to restart to change them -- if a behavior can be changed at runtime, it seems like it should probably *not* be controllable via an env var (which can't be).

**Comment by knz** [comment]
As I suggest above if some knob has both a setting and and env var, then the env var should only be used as an override for testing and probably would be used only rarely.

**Comment by dt** [comment]
I'm slightly -1 on an env overriding a cluster setting: when you change the setting, you might be surprised with nothing happens because of an env flag passed a long time ago, at server start.

As you say, I think the best behavior is just avoiding mixing them.

**Comment by arjunravinarayan** [comment]
If it overrides, there should at least be a sign somewhere that says OVERRIDDEN BY ENV VAR when you do a SHOW on that cluster setting.

**Comment by knz** [comment]
+1 on @arjunravinarayan's suggestion, that would alleviate david's concern

**Comment by dt** [comment]
somewhat, but only if you actually think go go `SHOW CLUSTER SETTINGS` on that node. still generally dislike mixing them, since you are forced to violate one of them and either way is going to confuse someone.

**Comment by bdarnell** [comment]
I don't think we should ever have an env var (or command-line flag) and a cluster setting for the same thing. We only ever used env vars for two hacky reasons: A) we didn't have cluster settings yet and B) the other alternative, command-line flags, would be more visible to users via `--help` (although at least now we have the ability to mark flags as "hidden").  (and C: client-side convenience, but we're talking about server-side stuff here). 

So my guidelines are:
- Anything that we want to document for users should be either a cluster setting or a command-line flag, with the former strongly preferred. Flags should be used only for things that need to vary per-node (like cache size) or are impractical to make a cluster setting (like max offset or `--join`).
- Environment variables are OK as a quick way to make something customizable for our own testing, but we should try to minimize this, and they should probably be temporary in most cases. (in the long term we may want to either introduce "hidden" cluster settings or just have an internal "here be dragons" namespace for these so we don't have to use env vars for them. But using cluster settings also implies that things may change at runtime, and that's not always easy to do)
- Sometimes it's appropriate for the same thing to be both a cluster setting and a session variable; in this case I think the session variable would always take precedence. I think this would be the only time we'd want to have the same variable set at two different levels.

**Comment by knz** [comment]
Ok I tend to agree, but that means we should avoid situations where there is an env var and a cluster setting for the same thing?

In which case we should really eliminate the pattern where the env var serves as a default for the setting, which I have seen appearing in the code this week!!!

**Comment by petermattis** [comment]
> In which case we should really eliminate the pattern where the env var serves as a default for the setting, which I have seen appearing in the code this week!!!

I agree, though I did this for the `kv.snapshot.{rebalance,recover}.rate`, but that's because a nightly test was using the env var which I didn't know how to change.

**Comment by knz** [comment]
@petermattis ok, and then your comment here strongly suggests we should provision a way to set up the cluster settings upfront for newly created clusters.

**Comment by dt** [comment]
right now that would be `cockroach start --background && cockroach sql -e "SET CLUSTER SETTING...` but maybe we want a way that start picks up initial settings?

**Comment by bdarnell** [comment]
Another thing for the explicit init command, perhaps.

**Comment by a-robinson** [comment]
Is there any sort of implied long-term support for options in the settings table? That'd be my main hesitation toward moving over a number of the existing environment variables. And if we're ok with exposing settings that we don't plan on supporting long-term, should the naming scheme be any different?

**Comment by knz** [comment]
@a-robinson we have not thought about settings enough to make an informed statements. My recommendation would be to highlight in the release notes that we do not guarantee backward-compatibility for the settings subsystem when it pertains to internal tuning knobs (as opposed to user-visible features like diagnostics reporting, which we can commit to keeping stable).

**Comment by jseldess** [comment]
We can make it clear which ones we're committed to keeping stable and which ones are subject to change in the user-facing docs as well, not just in the release notes.

**Comment by knz** [comment]
That would be ideal.

**Comment by knz** [comment]
I merged the discussion we had on this topic and the adopted parts of the proposal in a RFC in #15253. Please continue the discussion on that PR.
