### ISSUE TITLE
sql: verify float overflowing to Inf is desired

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#15255]
The [spanner docs](https://cloud.google.com/spanner/docs/functions-and-operators#operators) say:

> For all floating point operations, +/-inf and NaN may only be returned if one of the operands is +/-inf or NaN. In other cases, an error is returned

In cockroach:

```
root@:26257/> select 1e300::float * 1e10::float;
+----------------------------+
| 1e300::FLOAT * 1e10::FLOAT |
+----------------------------+
| +Inf                       |
+----------------------------+
root@:26257/> select pow(0::float, -1::float);
+---------------------------+
| pow(0::FLOAT, - 1::FLOAT) |
+---------------------------+
| +Inf                      |
+---------------------------+
```

In postgres:

```
postgres=# select 1e300::float * 1e10::float;
ERROR:  value out of range: overflow
postgres=#  select pow(0::float, -1::float);
ERROR:  zero raised to a negative power is undefined
```

Both postgres and spanner appear to refuse to ever produce `Inf` as a result unless an argument is already Inf. It is unclear if we should adopt this behavior or not.

**Comment by tamird** [comment]
Hm. What's the justification for our current behaviour? It doesn't seem
correct to me, intuitively.

**Comment by mjibson** [comment]
I don't believe there is one, it's the result of using Go's float64 everywhere and letting it dictate our behavior.

**Comment by knz** [comment]
IEEE734 says that there are multiple ways to handle FP overflows, and overflowing to infinity is one of the valid behaviors. Unfortunately Go, unlike C/C++, does not allow us to control the FP error handling, so unless we have a custom FP type (which would have horrible performance profile) I suggest to ignore this issue.

**Comment by mjibson** [comment]
That's fine with me. I agree that wrapping all float operations in a "did this overflow to infinity or NaN" check would be both slow and error prone as we could easily miss one, so it's probably safer to just leave it as is. Should add this to the "things we do different than postgres doc", which I'll do.
