### ISSUE TITLE
Single node bootstrap docs don't result in running instance

### ISSUE THREAD

**Issue by cleishm** [cockroachdb/cockroach#1525]
Following the single node bootstrap docs, https://github.com/cockroachdb/cockroach#bootstrap-and-talk-to-a-single-node, doesn't result in a running instance. Instead, the following error is continuously output:

```
E0627 12:50:27.352554      51 queue.go:266] failure processing range range=1 ["" - "\xff\xff") from replicate queue: allocator.go:204: unable to allocate a target store; no candidates available
```

Unfortunately it's not clear whether this is a software or user error, and I could use some advice to differentiate!

Thanks,
Chris

**Comment by tamird** [comment]
That's a harmless warning; the node is running.

**Comment by cleishm** [comment]
Ah hah! User misunderstanding then. Thanks!
