### ISSUE TITLE
Nakama server cannot apply migrations with beta-20170420

### ISSUE THREAD

**Issue by novabyte** [cockroachdb/cockroach#15269]
I cannot run a migration with Nakama which worked with beta-20170330.

The start of the log file for cockroachdb:

```
I170422 15:47:49.075609 1 util/log/clog.go:990  [config] file created at: 2017/04/22 15:47:49
I170422 15:47:49.075609 1 util/log/clog.go:990  [config] running on machine: localhost
I170422 15:47:49.075609 1 util/log/clog.go:990  [config] binary: CockroachDB CCL beta-20170420 (darwin amd64, built 2017/04/21 07:53:42, go1.8.1)
I170422 15:47:49.075609 1 util/log/clog.go:990  [config] arguments: [cockroach start --insecure --store=attrs=ssd,path=/tmp/cockroach]
```

The error output for Nakama server:

```
{"level":"info","ts":"2017-04-22T15:54:19.704+0100","msg":"Database connection","dsns":"root@localhost:26257"}
{"level":"info","ts":"2017-04-22T15:54:19.713+0100","msg":"Using existing database","name":"nakama"}
{"level":"fatal","ts":"2017-04-22T15:54:19.720+0100","msg":"Failed to apply migrations","count":0,"error":"pq: there is already a transaction in progress handling 20170115200001_initial_schema.sql","stacktrace":"nakama/vendor/go.uber.org/zap.Stack\n\tvendor/go.uber.org/zap/field.go:209\nnakama/vendor/go.uber.org/zap.(*Logger).check\n\tvendor/go.uber.org/zap/logger.go:273\nnakama/vendor/go.uber.org/zap.(*Logger).Fatal\n\tvendor/go.uber.org/zap/logger.go:208\nnakama/cmd.(*migrationService).up\n\tcmd/migrate.go:166\nnakama/cmd.(*migrationService).(nakama/cmd.up)-fm\n\tcmd/migrate.go:94\nnakama/cmd.MigrateParse\n\tcmd/migrate.go:155\nmain.main\n\tmain.go:65"}
```

The important error message is "pq: there is already a transaction in progress handling 20170115200001_initial_schema.sql". I'm not sure what we'd need to change to apply our schema migrations with the latest version of cockroachdb. The SQL migration we try to apply is here:

https://github.com/heroiclabs/nakama/blob/master/migrations/20170115200001_initial_schema.sql

Let me know what more information I can supply to help identify root cause and how best to resolve it.

**Comment by vivekmenezes** [comment]
It's hard for me to see what particular schema change in that file is failing within your golang code. I'd appreciate it if you can provide me with a pointer your golang code that is failing while applying the schema. This is the code that reads that schema file and calls into the sql driver. Thanks!

**Comment by petermattis** [comment]
Can you `cat schema.sql | ./cockroach sql`?

**Comment by vivekmenezes** [comment]
thanks @petermattis 

adding 

```
CREATE DATABASE nakama;

SET DATABASE=nakama;
```

to the initial_schema.sql file and running

```
$ cat nakama.sql | ./cockroach sql --insecure
CREATE DATABASE
SET
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE TABLE
CREATE INDEX
CREATE TABLE
CREATE INDEX
CREATE INDEX
CREATE TABLE
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
DROP TABLE
DROP TABLE
DROP TABLE
DROP TABLE
DROP TABLE
DROP TABLE
DROP TABLE
DROP TABLE
```

**Comment by novabyte** [comment]
@vivekmenezes We use this library to do migrations: https://github.com/rubenv/sql-migrate

It depends on [gorp](https://github.com/go-gorp/gorp) (unfortunately) right now. The code we use to drive the migrations is within one of our subcommands of the server:

https://github.com/heroiclabs/nakama/blob/master/cmd/migrate.go#L159

**Comment by vivekmenezes** [comment]
this issue is caused by the new code we put in to prevent statements from following a schema change in the same transaction when the schema change needs to be rolled out. I'm thinking about how we could fix this. One last minute option is to rollback https://github.com/cockroachdb/cockroach/pull/14368

**Comment by tamird** [comment]
@vivekmenezes it also seems that #14368 broke the examples-orms test suite: https://teamcity.cockroachdb.com/viewLog.html?tab=buildLog&buildTypeId=Cockroach_ExampleORMs&buildId=221487.

**Comment by vivekmenezes** [comment]
I'm going to rollback my original change and another change that was made
in the fallout. Coming sometime in today
