### ISSUE TITLE
Need to limit root privileges on some system tables

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#15265]
Noticed in the admin UI that the `root` user has full privileges on some `system` tables. Is this intentional? Seems risky. 

For example:

<img width="931" alt="screen shot 2017-04-22 at 2 11 12 am" src="https://cloud.githubusercontent.com/assets/15893490/25301967/ffb3802a-2700-11e7-9477-49578abae4df.png">

I'm able to insert into that table and do other things, which can't be what we want?

```
root@:26257/system> show columns from rangelog;
+--------------+-----------+-------+----------------+-----------+
|    Field     |   Type    | Null  |    Default     |  Indices  |
+--------------+-----------+-------+----------------+-----------+
| timestamp    | TIMESTAMP | false | NULL           | {primary} |
| rangeID      | INT       | false | NULL           | {}        |
| storeID      | INT       | false | NULL           | {}        |
| eventType    | STRING    | false | NULL           | {}        |
| otherRangeID | INT       | true  | NULL           | {}        |
| info         | STRING    | true  | NULL           | {}        |
| uniqueID     | INT       | false | unique_rowid() | {primary} |
+--------------+-----------+-------+----------------+-----------+
(7 rows)
root@:26257/system> insert into rangelog values (now(), 10, 10, 'test', 10, 'test');
INSERT 1
```

**Comment by dianasaur323** [comment]
assigning to @mberhault. Please re-assign if you aren't the right person. Let's take a look to see if we should fix this?

**Comment by mberhault** [comment]
it should be fine, the rangelog table for example can be messed with, it's not critical.
@asubiotto: I believe those were sorted out by you not too long ago.

**Comment by dianasaur323** [comment]
@asubiotto Thoughts on if we should close this out, or leave for 1.1?

**Comment by asubiotto** [comment]
I think this is fine;  the root user is a superuser. Closing but feel free to re-open.

**Comment by jseldess** [comment]
Make sense to me as long as `root` user changes to these tables can't somehow mess up the cluster's operations, in which case I'd say we should just make them strictly read-only to anything but cockroachdb.

**Comment by asubiotto** [comment]
They can mess up cluster operations (e.g. delete all users) but I think that's part of being a superuser.

**Comment by jseldess** [comment]
True, but I guess I don't understand why we treat the `system` database differently than other built-in dbs. For example, there are no privileges on `crdb_internal` or `pg_catalog` tables...

```
root@:26257/system> show grants on crdb_internal.leases;
+-------+------+------------+
| Table | User | Privileges |
+-------+------+------------+
+-------+------+------------+
(0 rows)

root@:26257/system> show grants on pg_catalog.pg_am;
+-------+------+------------+
| Table | User | Privileges |
+-------+------+------------+
+-------+------+------------+
(0 rows)
```

**Comment by bdarnell** [comment]
The `crdb_internal` and `pg_catalog` tables are magic and read-only anyway. We restrict access to some system tables (like `namespace` and `descriptor`) because you can really mess up the cluster by touching those, but there's nothing you can really do with the `rangelog` table.

**Comment by jseldess** [comment]
Got it. Thanks.
