### ISSUE TITLE
docs: show examples of Cockroach with Longhorn

### ISSUE THREAD

**Issue by mytototo** [cockroachdb/cockroach#15267]
Hi there,

Is there any working example of a HA Cockroach with Longhorn?

Thanks.

**Comment by dianasaur323** [comment]
@mytototo not yet - we haven't started testing out integrations with any Rancher products. If you get the chance to test it out, do let us know! I'm marking this as a community request so that others can vote on it if they would like to see an example as well.

**Comment by knz** [comment]
cc @tim-o @jseldess for next actions
