### ISSUE TITLE
storage: txn sequence number assigned by DistSender is rolled back on error

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#15278]
Our `Transaction` protos have a [Sequence number](https://github.com/cockroachdb/cockroach/blob/master/pkg/storage/engine/enginepb/mvcc.proto#L56) used to protect against replays. This sequence number is [incremented](https://github.com/cockroachdb/cockroach/blob/master/pkg/kv/dist_sender.go#L742) by the DistSender upon sending every (sub)batch. The `DistSender` only does this incrementing on the `Transaction` proto that's embedded in a `Batch` being sent, and not in any more persistent in-memory copy of the `Transaction` (e.g. the copy in the `client.Txn`, used to initialize new Batches with)..

The sequence number is __not__ reset on transaction restarts.

Here's one thing that I see happening: when an error happens in the storage layer, the `roachpb.Error` that's returned to the client (and used by the client to restart the txn, in case of a retryable error) can drop this incremented Sequence number on the floor and return an old one. This happens because the following code uses the reply's txn to set the error's txn:
https://github.com/cockroachdb/cockroach/blob/master/pkg/storage/replica_command.go#L234

and the reply's txn is, at least sometimes, based on the copy of the `Transaction` proto from the DB: https://github.com/cockroachdb/cockroach/blob/master/pkg/storage/replica_command.go#L658
That copy can be, I think, arbitrarily stale.

I've noticed this because I'm mocking around with the code around how transaction protos are re-initialized on retries.

My questions are:

1) It is clearly a violation of the intent of that sequence number for it to be rolled back like that, right? I'm not sure of its consequences, given that I've only observed the issue on errors, where we retry the transaction with a higher epoch anyway. But I think that same overwriting happens also successful replies. Would it be wise to try to return a more updated tranction in replies?
2) Should retries start from sequence number 0? This would help me with some code I'm writing, I think, and also I'd find it less surprising. It would involve augmenting the checks for valid overwrites here: https://github.com/cockroachdb/cockroach/blob/master/pkg/storage/engine/mvcc.go#L1077
3) Btw, we still need sequence numbers, right? Just asking because the "sequence cache" that we once had has been transformed into some other beast. It seems to be that we still need them to prevent reorderings of writes from the same (retry of a) transaction. Unless the raft-level indexes protect against these?

cc @bdarnell @spencerkimball

**Comment by bdarnell** [comment]
We never compare sequence numbers from different epochs; restarting the sequence number at zero when the epoch increments makes sense to me (I thought it already did this). 

I think the only time we ever use the on-disk transaction is when we're restarting with a new epoch, so I don't think anything else needs to change. If we do use it sometimes when continuing with the same epoch, that's probably an error (although there is a guard in `Transaction.Update` to avoid moving the sequence number backwards).

**Comment by andreimatei** [comment]
> We never compare sequence numbers from different epochs; restarting the sequence number at zero when the epoch increments makes sense to me (I thought it already did this).

Sure we do. Look at my MVCC link; if the current epoch is greater than an intent's epoch, we compare the sequence numbers.
https://github.com/cockroachdb/cockroach/blob/master/pkg/storage/engine/mvcc.go#L1077

> I think the only time we ever use the on-disk transaction is when we're restarting with a new epoch, so I don't think anything else needs to change. If we do use it sometimes when continuing with the same epoch, that's probably an error (although there is a guard in Transaction.Update to avoid moving the sequence number backwards).

Why do you think we only use the on-dist txn when restarting? We seem to set the on-disk txn as `reply.Txn`. Indeed, on the client we always use `Update()`, for better or worse, which only moves the Sequence forward, but, as far as I can tell, the client never has the "most updated" proto - the one with the Sequence number allocated by the `DistSender`.

**Comment by andreimatei** [comment]
Ben pointed out that the on-disk Transaction record is only used in responses for `EndTransaction`, where it shouldn't matter much.
