### ISSUE TITLE
storage: Snapshots for under-replicated ranges should have higher bandwidth

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#15273]
We currently divide snapshots into two categories for bandwidth management - preemptive and raft-initiated. Raft-initiated snapshots are given more bandwidth because they indicate an existing follower that is falling behind (and therefore not contributing to the raft quorum). Preemptive snapshots are (often) rebalancing traffic that is low-priority, but when they're used to repair an under-replicated range they should be high priority.

Noticed in https://github.com/cockroachdb/cockroach/issues/15163#issuecomment-296387234

**Comment by petermattis** [comment]
Easy enough to do, but for my future self we can't just pass `snapTypeRaft` for these up-replication snapshots as `snapTypePreemptive` controls whether we call `Replica.setPendingSnapshotIndex`.
