### ISSUE TITLE
sql: compatibility with KnexJs query builder

### ISSUE THREAD

**Issue by ansarizafar** [cockroachdb/cockroach#15299]
Please provide support for [KnexJS](knexjs.org) query builder.

**Comment by tamird** [comment]
Hi @ansarizafar, thanks for the request. Have tried using CRDB with KnexJS? What problems did you run into?

**Comment by ansarizafar** [comment]
I had tried to use CRDB with KnexJs few weeks back without any luck. I was not able to connect.

**Comment by tamird** [comment]
Could you please post the full script you used, along with any errors you
encountered?

**Comment by ansarizafar** [comment]
I switched to Postgresql after an unsuccessful attempt. I had used the following code but don't exactly remember the error message.
```
var pg = require('knex')({
  client: 'pg',
  connection: process.env.PG_CONNECTION_STRING,
  searchPath: 'knex,public'
});
```

**Comment by tamird** [comment]
Perhaps you could try again with the current beta and let us know what you
get.

**Comment by ansarizafar** [comment]
I am using an old machine to play with beta software and current beta don't work on my test machine.

**Comment by tamird** [comment]
Ah, that's probably due to
https://github.com/cockroachdb/cockroach/commit/aa067e3fdafb8de94f5c64ec894997ed85855706
.

Could you try again after this week's beta? It should clear up this issue.

**Comment by ansarizafar** [comment]
Ok. In my opinion KenxJs is better than Sequelizejs and CRDB should support it.

**Comment by ansarizafar** [comment]
I tried to use CRDB with KenxJs . I am gettinf this error when trying to execute a query
```
{ Error: connect ECONNREFUSED 104.131.159.76:26257
9:00 PM
    at Object.exports._errnoException (util.js:1022:11)
9:00 PM
    at exports._exceptionWithHostPort (util.js:1045:20)
9:00 PM
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
9:00 PM
  code: 'ECONNREFUSED',
9:00 PM
  errno: 'ECONNREFUSED',
9:00 PM
  syscall: 'connect',
9:00 PM
  address: '104.131.159.76',
9:00 PM
  port: 26257 }
```
Connection string postgresql://root@host:26257/restock?sslmode=disable

**Comment by tamird** [comment]
Connection refused suggests that the server isn't listening on that host:port. Are you able to reach your CRDB server with `cockroach sql --url postgresql://root@host:26257/restock?sslmode=disable`?

**Comment by tamird** [comment]
Also, it would be helpful if you could share the complete knexjs code you're trying to run.

**Comment by ansarizafar** [comment]
Here is my Knexjs code
```
 var client = knex({
  client: 'pg',
  connection: 'postgresql://root@host:4000/restock?sslmode=disable',
  searchPath: 'knex,public'
});

user = await client.select().from('users');
              console.log(user);
              return user
```
I have fixed port issue now I am getting this error
```
Error: Connection terminated
11:11 PM
    at Connection.<anonymous> (/app/node_modules/pg/lib/client.js:193:17)
11:11 PM
    at Connection.g (events.js:291:16)
11:11 PM
    at emitNone (events.js:86:13)
11:11 PM
    at Connection.emit (events.js:185:7)
11:11 PM
    at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:141:10)
11:11 PM
    at emitNone (events.js:91:20)
11:11 PM
    at Socket.emit (events.js:185:7)
11:11 PM
    at endReadableNT (_stream_readable.js:974:12)
11:11 PM
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
11:11 PM
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by benesch** [comment]
A few thoughts. In the sample code you posted, you're attempting to connect to port 4000. Are you sure that's the port you started your Cockroach server on?

As @tamird suggested, please post the output of `cockroach sql --url postgresql://root@host:4000/restock?sslmode=disable`, assuming that 4000 is the right port.

**Comment by ansarizafar** [comment]
Here is the output
```
# Welcome to the cockroach SQL interface.                                                                 
# All statements must be terminated by a semicolon.                                                       
# To exit: CTRL + D.                                                                                      
root@0.0.0.0:4000/restock>   
```

**Comment by tamird** [comment]
I am unable to reproduce your error. Here's what I ran locally:
```javascript
#!/usr/bin/env node

var knex = require('./knex')

 var client = knex({
  client: 'pg',
  connection: 'postgresql://root@localhost:26257/knex_test?sslmode=disable',
  searchPath: 'knex,public'
});

client.select().from('users').then(function(user) {
	console.log(user);
});

```
and the result:
```
/Users/tamird/src/knex/lib/dialects/postgres/index.js:182
        resolver(/^PostgreSQL (.*?)( |$)/.exec(resp.rows[0].version)[1]);
                                                                    ^

TypeError: Cannot read property '1' of null
    at Query.<anonymous> (/Users/tamird/src/knex/lib/dialects/postgres/index.js:182:69)
    at Query.handleReadyForQuery (/Users/tamird/src/knex/node_modules/pg/lib/query.js:124:10)
    at Connection.<anonymous> (/Users/tamird/src/knex/node_modules/pg/lib/client.js:172:19)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/Users/tamird/src/knex/node_modules/pg/lib/connection.js:136:12)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:560:20)
```

This is because knex is overly aggressive in trying to parse the postgres server's version (for feature detection). It assumes that the return value of `select version()` begins with "PostgreSQL", which is not the case in CDB.

You might wish to file an issue in https://github.com/tgriesser/knex.

**Comment by ansarizafar** [comment]
Great news Knexjs has added support for CockroachDB on my request. CRDB support is coming in release knex 0.13

**Comment by tamird** [comment]
That is great news! Can you share where that was announced or implemented?
I was testing against knex's master branch when I saw the error above.

**Comment by ansarizafar** [comment]
Here is the link [https://github.com/tgriesser/knex/issues/2002](https://github.com/tgriesser/knex/issues/2002)

**Comment by tamird** [comment]
Ah, I see; you need to manually set the version. Great! Giving this a close for now but please let us know if you uncover more issues.

**Comment by nicck** [comment]
Unfortunately it is still not possible to use cockroachdb with knexjs. Issues I have found:

- `select * for update` is not supported by cockroach
- `column name "current_schema" not found` b/c current_schema is not enclosed in `'` `'`
- migrations lock does not work
- uuid and json types are not supported
- `.primary()` in migrations fails with something like "multiple primary keys not allowed";

As I can see cockroachdb is not drop-in replacement for postgresql.

**Comment by JorgeCeja** [comment]
Any updates? Thanks!

**Comment by josdotso** [comment]
@tamird Would you be willing to reopen this based on @nicck's comment?

**Comment by josdotso** [comment]
Thanks @tamird !

**Comment by petermattis** [comment]
@knz for triage.

**Comment by Bessonov** [comment]
SELECT FOR UPDATE placebo is a part of https://github.com/cockroachdb/cockroach/issues/6583. Some workaround are described in https://github.com/tgriesser/knex/issues/2002#issuecomment-383766677.

**Comment by awoods187** [comment]
@jordanlewis we should add this one to the list

**Comment by intech** [comment]
Up! https://github.com/knex/knex/issues/2002#issuecomment-719885770
