### ISSUE TITLE
sql: more fine-grained tracking of memory during expression evaluation

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#15295]
When evaluating an expression, we should keep fine-grained track of the memory allocated during each step of the evaluation. For example, when evaluating the expression

```sql
SELECT LENGTH(REPEAT('abc', 999999));
```

we should first track that `REPEAT` needs to allocate a large amount of memory, but then be aware that after computing `LENGTH` we no longer need that value around. As of this writing there is no memory tracking at all for expression evaluation (but there is a PR in the works for a limited version).

This is important when evaluating queries that look something like

```sql
SELECT LENGTH(REPEAT('abc', 999999)) + LENGTH(REPEAT('abc', 999999));
```

where each individual call to `REPEAT` is safe to allocate, but allocating them together will overflow the memory budget.

Also see [this comment/issue](https://github.com/cockroachdb/cockroach/issues/10545#issuecomment-296241884) for more context.

**Comment by jordanlewis** [comment]
We decided to change approaches on this, and to have a hard cap on how much memory expressions like this can produce.
