### ISSUE TITLE
cli/conn: sql URLs should behave a bit more like psql for secure clusters

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#15318]
When using secure mode, the `cockroach sql` command will look for client certificates in `--certs-dir` and use them. If they are not present, it will prompt for a password.

The automatic cert detection makes a few things impossible.
* cannot use password authentication if client certs are present
* cannot use `sslmode` of `allow`, `prefer`, or `require` which skip CA checks (if no certs are present at all, we assume insecure mode)

We should try to support other modes. While it's not recommended, we should allow clients talking to a secure cockroach cluster over SSL but without checking the CA cert.
We should also make sure the behavior when using flags vs pgurl is consistent.

See [this forum post](https://forum.cockroachlabs.com/t/psql-remote-connection-certificate-not-valid/584) for a discussion of some issues encountered.

**Comment by mberhault** [comment]
btw: doing this will expand the list of security modes we support a bit more, making it easier to handle clients.
Specifically, connections already work with SSL but no CA cert, they just can't be setup through the `cockroach sql` shell. This means that client can run over SSL and password authentication but don't need to have client or even CA certs distributed to them.

If this is small enough (it should be, and should only impact the CLI), it might be worth doing for 1.0.
@bdarnell: thoughts? we've talked quite a bit about our rather large gap between insecure and secure. Properly supporting SSL+password with no certs whatsoever on the client would provide a bit of middle ground.

**Comment by bdarnell** [comment]
As long as the user must explicitly opt in to TLS with no CA (which is MITM-able), I'm OK with it.

**Comment by mberhault** [comment]
It depends on the library. Apparently, `prefer` is the default, meaning we'll do SSL if the server supports it, but no CA.

The [postgres doc](https://www.postgresql.org/docs/9.1/static/libpq-ssl.html) actually has a nice table summarizing the dangers pretty well.

We can't do anything to control other clients, but we can have stricter defaults of `disable` in insecure mode, and `verify-full` for secure. `go/lib/pq` defaults to `require` which is too liberal.
We could make our sql shell 1) handle other modes, and 2) default to `verify-full`.

Currently, if the `--url` is specified, we pass it through as it, meaning I can foo the following:
```
$ ./cockroach sql --url='postgresql://foo@vintner:26257?sslmode=require&password=foo'
```

Which uses SSL but no CA certs. The password must also be passed in the URL, we won't prompt for it.
We can easily parse the URL, fill in defaults, prompt for the password if needed, and build it back up.

The addition of some logic (eg: don't fail on missing `ca.crt` in `require` mode) would bring the flag-based invocation up to par with the url-based one but allow reasonable defaults.

**Comment by mberhault** [comment]
Not a priority, punting to 1.2.

**Comment by arjunravinarayan** [comment]
Repunting to 2.1, since this is feature work that is not going to make it in the 2.0 timeframe.

**Comment by mberhault** [comment]
They always could when using `--url`, this issue is about allowing other modes (eg: SSL certs present, but use password anyway) through the regular flags.

**Comment by knz** [comment]
Oh I see. Thanks

**Comment by mberhault** [comment]
meh. There's been no request for this, punting until "later".

**Comment by knz** [comment]
I think bit by bit we are deprecating the discrete flags and `--url` is taking over. In any case:

1) now all commands accept `--url`, not just SQL-based commands
2) the use cases at the top of this issue are supported since  #23725

so I am going to close this issue. If we learn new things from user demand, we can re-open issue with a more specific dscription of the desired behavior.
