### ISSUE TITLE
build: handle 1.0 versions

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#15329]
The only versioning our build system understands is the `beta-*` tags.

We'll need to handle 1.0 (and further) versioning, including minor versions (eg: `1.0.1`) and release candidates (eg: `1.0-rc1`, `1.0.1-rc1`).

I can think of the following to update:
* teamcity build rules
* various scripts used by teamcity (eg: `build/teamcity-release-upload.sh`)
* registration server version comparison

Marking as 1.0 deadline (obviously). We can get away with calling some betas release candidates, but we'll really need proper versioning in the 1.0 binary.

**Comment by a-robinson** [comment]
Also the logic in `build/teamcity-release-upload.sh` for which releases are considered "stable", which affects which releases we push as latest to docker hub.

**Comment by a-robinson** [comment]
Whoops, you already included that script. Carry on :)

**Comment by benesch** [comment]
I just proposed the following change to the release cycle document.

> All versions post-1.0.0 should sort correctly with github.com/hashicorp/go-version and sort --version-sort. This ensures compatibility with downstream package managers’ version ordering. Importantly, alphabetic components (e.g. beta, rc) can only appear after a - character, and must be separated from any following numeric components by a . character to ensure that e.g. 1.1-rc.2 sorts before 1.1-rc.10. For example, the following tags sort in the listed order:
>
>  * 1.0 (final major release)
>  * 1.0.1 (final patch release)
>  * 1.1-beta.2017.09.12 (semimonthly unstable release)
>  * 1.1-rc.2 (early release candidate)
>  * 1.1-rc.10 (late release candidate)
>  * 1.1 (final minor release)
>
> Note that pre-1.0 beta releases were tagged beta-YYYYMMDD, which incorrectly compares as greater than 1.0.0, even with version-aware sort orders. Code that must handle old CockroachDB versions, like our registration cluster, must special-case versions that begin with beta-, but should not expect to special-case any future versions.

The big difference is e.g. `1.1-rc.2` instead of `1.1-rc2` to handle version sorts that aren't smart enough to split numeric and non-numeric components without an intervening `.`. 

FYI I'm working on fixing version handling in the reg cluster.

**Comment by benesch** [comment]
@tamird is your refactor going to make it into 1.0?

**Comment by tamird** [comment]
I sure hope so.

**Comment by benesch** [comment]
I've updated the relevant build triggers and VCS roots in TC to also consider `v*` as a release tag. #15389 applied the same change to the teamcity-release-upload.sh script. I've got an open PR for the reg server as well. So I think we're good to go! I'll leave this open for now, though.

attn @bdarnell: the tag must be named `v1.0-rc.1` or `v1.0.0-rc.1` and not `1.0-rc.1`.

**Comment by bdarnell** [comment]
We've successfully released `v1.0-rc.1`, so I think we've done everything that's necessary here.
