### ISSUE TITLE
storage: Leases follow-the-workload performs poorly if localities are under-specified in uneven latency deployments

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#15369]
I recently found in testing that using multiple levels of localities was very important to getting a stable, proper lease balance in configurations where two of your three datacenters are much closer to each other than to the third (such as in [our allocsim config that simulates two east coast US datacenters and one in Australia](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/allocsim/configs/node-per-locality-uneven-latency-imbalanced-load2.json)). As described in [my commit that added a second level of locality hierarchy to the config](https://github.com/cockroachdb/cockroach/pull/15321/commits/90b53cf2522784abdfa39f6974805d0812b29757):

```
This is needed to stop the thrashing when running on the uneven-latency
configs when running with imbalanced load, since otherwise the locality
that has all the load will freely transfer requests to its nearby
locality, which will eagerly transfer them to the distant locality,
which will eagerly transfer them back to the locality with all the load.
This behavior is essentially due to relying on the DiversityScore for
determining whether or not requests to the loaded locality should count
towards the other nearby locality's weight. We want them to, but without
having a multi-level locality they won't.

To help users that haven't set up their localities in such a way, we'd
have to start taking into account the latency to where the requests are,
which is tough to do for any node other than yourself. I suppose that
doing it for yourself would be better than nothing, but that may be too
big a change for 1.0.
```

For 1.0, we can try to educate users into specifying multiple levels of localities (or to disable load-based lease rebalancing) when they have very uneven latencies between their datacenters, but based on the feedback we get we may have to do something smarter than just using the locality-derived DiversityScore. I'll update the docs to make this clear for now, and I'll update the milestone as appropriate based on whether this bites users out in the wild.

**Comment by a-robinson** [comment]
Doc updates in #15379 and https://github.com/cockroachdb/docs/pull/1334

**Comment by petermattis** [comment]
@a-robinson Is your current work on load-based lease/replica rebalancing going to resolve this issue?

**Comment by a-robinson** [comment]
No, this is orthogonal. Fixing it will require more sophisticated attribution of load to localities that are near each other on the network both don't have any locality kv pairs in common.

**Comment by a-robinson** [comment]
edit: renamed issue to avoid confusion with the new load-based rebalancing functionality in 2.1

**Comment by sploiselle** [comment]
@a-robinson Can I get a quick blurb describing this known limitation w/r/t the impact to user experience? Ideally, we need it by Friday 10/26 for the 2.1 Known Limitations page. Posting it on this issue and/or pinging me would be great.

**Comment by a-robinson** [comment]
@sploiselle I'd say [this](https://www.cockroachlabs.com/docs/stable/known-limitations.html#load-based-lease-rebalancing-in-uneven-latency-deployments) is a pretty good explanation of it :)
