### ISSUE TITLE
sql: EvalContext is insufficiently initialized in most places where it is used

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#15363]
Encountered while working on  #15357: contrary to `SemaContext`, which has `MakeSemaContext` constructor, `EvalContext` does not have a constructor and it is used in many places using the default values and a quick-and-dirty, minimal "set the timestamps" initialization at the point of use.

Setting the timestamps is only part of the story however

1) this puts the onus on the point of use to do the correct initialization, and a quick scan through the code reveals this is not done properly in several places

2) the evalcontext may contain other fields that need to be initialized properly for built-ins to make sense. For example NodeID, used by `unique_rowid`: if the default of 0 is used on separate nodes, we risk generating twice the same "unique rowid". This is especially a problem since #15344 has been merged.

3) This hampers things like the work on #15357 for example which want to see useful information about the current session in EvalContext.

So the EvalContext should really have a constructor that populates it with useful values.

**Comment by knz** [comment]
cc @justinj not sure how this interacts with what you were doing.

**Comment by knz** [comment]
cc @RaduBerinde I would suggest until this issue is fixed that we think at least about initializing NodeID properly in the evalCtx of distsql flows. Where should I look at to do this reliably?

**Comment by justinj** [comment]
Agreed, I've run into this (having to deal with incomplete `EvalContext`s) in a bunch of places working on what I am now.

**Comment by RaduBerinde** [comment]
@knz we don't currently allow context-dependent functions in distsql (they run non-distributed).
That said, I think [this](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/distsqlrun/server.go#L164) is the appropriate place to set NodeID and probably a bunch of other stuff.

**Comment by arjunravinarayan** [comment]
@RaduBerinde but we plan to (see #13821, which is marked as 1.0)

**Comment by andreimatei** [comment]
This has gotten better with #15628, but a ctor would still be nice.

**Comment by arjunravinarayan** [comment]
@knz with #15628 in, I believe this milestone should be changed to 1.1 from 1.0 - is that correct?

**Comment by knz** [comment]
1.0.1 actually...

**Comment by petermattis** [comment]
Let's change the milestone to 1.1 and create a 1.0.1 label.

**Comment by jordanlewis** [comment]
@knz to close and re-open with a more targeted action.

**Comment by knz** [comment]
Subsumed by #15667.
