### ISSUE TITLE
stability: High p95 latency during/after rolling restart

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#15376]
I did a rolling restart to upgrade `omega` to commit 18aaa37d385494db30a0e975db6fb0fd48d7db58 (from a build about 2 days old). During the restart, throughput dropped, and p95 latency went up to 17 seconds on one node at a time, staying that high for several minutes before recovering. I don't think this is a new issue. 

![image](https://cloud.githubusercontent.com/assets/160562/25453495/28ae8648-2a97-11e7-8337-8eb840058896.png)

**Comment by petermattis** [comment]
Did this rolling restart perform node draining? Did the draining succeed in moving off all of the leases? Looking at the leaseholders per node graph, the fall-off seems too fast to have been done intentionally, but perhaps this is how fast we can drain:

<img width="934" alt="screen shot 2017-04-26 at 3 49 21 pm" src="https://cloud.githubusercontent.com/assets/6201335/25453708/06b4f2ec-2a98-11e7-9956-27628895777a.png">

**Comment by bdarnell** [comment]
I did `crl-interactive-restart` as documented in the production readme (which in turn does a supervisorctl stop and start). @mberhault @asubiotto, what is expected here?

**Comment by asubiotto** [comment]
If draining was performed correctly, I would not expect this to happen. I'm not sure how supervisorctl stops the process but if it is through a `SIGTERM` and the node doesn't manage to transfer away all its leases in under a minute, the node will proceed to perform a hard shutdown while still holding on to some leases. This could explain the latencies.

**Comment by bdarnell** [comment]
If I'm reading the supervisor config correctly, it sends a SIGTERM, waits up to 90 seconds, then does a SIGKILL. So it should have given it enough time to drain.

**Comment by asubiotto** [comment]
Right, but `cockroach` only [waits up to a minute](https://github.com/cockroachdb/cockroach/blob/master/pkg/cli/start.go#L484). The `quit` command was recently changed to reflect this as well. Maybe this should be changed.

**Comment by petermattis** [comment]
From `omega` 1:

```
I170426 19:27:30.059219 1 cli/start.go:432  received signal 'terminated'
E170426 19:28:30.103589 1 cli/error.go:68  time limit reached, initiating hard shutdown
```

I noticed that `omega` 1 didn't start transferring leases until `19:27:57`. But it then transferred 684 leases between `19:27:57` and `19:28:09`. Log messages a few minutes before this indicate that this was all of the leases on the node. So it seems that draining of the leases occurred very rapidly.

**Comment by bdarnell** [comment]
This appears to have been fixed by TickQuiesced (I've done experiments and I no longer see the symptoms described here unless I disable TickQuiesced)
