### ISSUE TITLE
build: Race build on merge to master broken

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#15378]
Merges to master are no longer building race binaries and pushing them to S3, so I am unable to deploy a new build to the race test cluster. Judging by the last successful race build in s3, it looks like it was broken by #15209.

**Comment by tamird** [comment]
Oh, this is broken because the race detector doesn't work on not-glibc https://github.com/golang/go/issues/14481.

We need to not try to build musl race builds.
