### ISSUE TITLE
Counters are displayed as Hex string when using cockroach client - is this expected behaviour?

### ISSUE THREAD

**Issue by bgurupra** [cockroachdb/cockroach#1539]
[ec2-user@ip-172-31-36-63 cockroach]$ ./cockroach kv inc mycnt 5
5

[ec2-user@ip-172-31-36-63 cockroach]$ ./cockroach kv get mycnt
"\x00\x00\x00\x00\x00\x00\x00\x05"

[ec2-user@ip-172-31-36-63 cockroach]$ ./cockroach kv put  a 25

[ec2-user@ip-172-31-36-63 cockroach]$ ./cockroach kv scan
"a"     "25"
"mycnt" "\x00\x00\x00\x00\x00\x00\x00\x05"

[ec2-user@ip-172-31-36-63 cockroach]$ uname -a
x86_64 x86_64 x86_64 GNU/Linux

**Comment by tschottdorf** [comment]
Hi @bgurupra, this is currently expected behaviour, see `ExampleBasic()` in `server/cli/cli_test.go`. If you want to read a counter value, run `kv inc mycnt 0`. The API is in motion though, so the behaviour may change.
