### ISSUE TITLE
distsql: backfill checkpoint txn thrashing

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#15422]
If you do `make test PKG=./pkg/sql TESTS=TestDistBackfill TESTFLAGS=-v` you see a ton of:

```
I170427 15:46:36.599179 3274 sql/distsqlrun/backfiller.go:169  [n4,IndexBackfiller=52] retrying adding checkpoint /Table/52/1/{7200/0-8000} to table NumToSt
```

Haven't checked the code, but I think this is because the txns doing checkpointing all conflict with one another. If this can be seen even on a small table like in this test, I think it might be a problem. And also might explain why this test, adding an index to 10.000 rows, takes ~2s.

I could be completely wrong and maybe there's nothing to see here other than log spam.

**Comment by vivekmenezes** [comment]
same as #13645
