### ISSUE TITLE
server: malformed problem ranges page

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#15440]
The screenshot was taken through an ssh tunnel so perhaps some bit of css wasn't loading:

<img width="1398" alt="screen shot 2017-04-27 at 9 27 45 pm" src="https://cloud.githubusercontent.com/assets/6201335/25510759/7eb750b6-2b90-11e7-8e15-0698a7187934.png">

Two problems:
* No spaces between the range IDs
* The range IDs do not wrap

**Comment by BramGruneir** [comment]
Weird.  There's supposed to be a nbsp between each item in the list.  Can
you get the page source?
