### ISSUE TITLE
Re-organize admin client

### ISSUE THREAD

**Issue by MBerhault** [cockroachdb/cockroach#1548]
It's very messy right now, only takes yaml, and is fairly convoluted.

**Comment by vivekmenezes** [comment]
Is there a problem with Yaml? Any thoughts on what you wanted to do?

**Comment by MBerhault** [comment]
The admin endpoints can already accept multiple encodings. For things like the UserConfig which do not take a config file, I'd rather build a proto and put that directly.
My thinking was to change the admin client to take an arbitrary encoding. It will still support yaml, and this will still be the file encoding expected for accounting/perm/zone.

**Comment by vivekmenezes** [comment]
Sounds good. Thanks for explaining.

**Comment by MBerhault** [comment]
This is mostly done. It would be nice to add proto at some point.

**Comment by MBerhault** [comment]
No longer needed, all configs are moving to structured layout with sql interface. #2090
