### ISSUE TITLE
docs: add KnexJs tutorial to Build an App with CockroachDB section in Documentation

### ISSUE THREAD

**Issue by ansarizafar** [cockroachdb/cockroach#15528]
Latest version of KnexJS query builder is compatible with CockroachDB. A KnexJS tutorial would be a great addition to documentation.

**Comment by tamird** [comment]
Thanks for the suggestion! FYI we also have a public [docs repo](https://github.com/cockroachdb/docs). cc @jseldess

**Comment by knz** [comment]
Dup https://github.com/cockroachdb/docs/issues/3137
