### ISSUE TITLE
gossip: Improve/replace hop-counting logic

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#15539]
Our current logic for counting the number of hops between nodes works poorly in the presence of node restarts. A node's count of hops for a given piece of gossip never lowers once the node has received it (due to high-watermark tracking), even if the node later connects directly to the node that produced the gossip. This lack of proper tracking can lead to a bunch of nodes thrashing their gossip connections, all trying to connect directly to some node whom they all perceive as being far away.

As discussed in #9819 and #15533, we should do some surgery on this logic to improve the behavior amidst node restarts and connection churning.

**Comment by tamird** [comment]
@spencerkimball who might have some fresh ideas in this area.

**Comment by tamird** [comment]
Heh, is this a dupe of #15538?

**Comment by a-robinson** [comment]
Yup, looks like he won the race.

**Comment by spencerkimball** [comment]
Oops, sorry about that Alex.
