### ISSUE TITLE
storage: command queue optimization

### ISSUE THREAD

**Issue by spencerkimball** [cockroachdb/cockroach#15544]
Because reads can proceed in parallel without mediation by the command queue, a reasonable optimization would be to completely defer command queue insertion until there are writes, at which point still-pending reads are expanded in the command queue.

**Comment by tschottdorf** [comment]
reminder to self: @andreimatei a while back floated the idea of letting reads populate the timestamp cache when they begin as opposed to when the end, which could allow them to not go into the command queue at all. I haven't tried to poke holes in this argument, but if it were sound and there were a way to skip populating the command queue completely for reads, that'd be even better.

https://forum.cockroachlabs.com/t/why-do-we-keep-read-commands-in-the-command-queue/360

**Comment by spencerkimball** [comment]
@andreimatei and @tschottdorf: doing this naively will cause infinite retries on some of the txn_correctness_test tests. This is because reads may encounter intents and as a result normally not update the read timestamp cache, and that property is important to preserve or else you can have transaction retry histories which never finish.

**Comment by petermattis** [comment]
The bits of code to look at here are `Replica.beginCmds` and `Replica.endCmds`. I suspect the easiest path forward is to completely encapsulate this optimization in the command queue code. Specifically, `CommandQueue.add` can bundle up its arguments when `readonly == true` and add to a new `CommandQueue.readCmds` slice. When a write command arrives, we expand the `readCmds` slice adding the commands to the `CommandQueue.reads` tree.

**Comment by petermattis** [comment]
Cc @garvitjuniwal

**Comment by tschottdorf** [comment]
Fixed in https://github.com/cockroachdb/cockroach/pull/16360.
