### ISSUE TITLE
ui: nodes identified by hostname in cluster overview dropdown

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#15541]
From https://github.com/cockroachdb/cockroach/issues/10365#issuecomment-298277836.

<img width="1105" alt="screen shot 2017-04-30 at 15 14 27" src="https://cloud.githubusercontent.com/assets/1535036/25567263/e9f0c9b0-2db7-11e7-875f-294e5bafd332.png">

The above is caused by the fact that nodes are identified in that list by their hostname, and node ID 7 was recreated as node ID 11 (still on the host blue 7). So perhaps we need to be careful about identifying nodes by their addresses.

**Comment by dianasaur323** [comment]
Perhaps we should append node id. @kuanluo

**Comment by mrtracy** [comment]
Update: This appears to cause problems with graphs as well. If the same node address appears for two different nodes in the same graph, one of the lines will not appear.
