### ISSUE TITLE
odd discrepancy in homebrew install message 

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#15579]
I get the following message when installing on Homebrew:

`==> make install
==> Caveats
CockroachDB is a distributed database intended for multi-server deployments.
For local development only, this formula ships a launchd configuration to
start a single-node cluster that stores its data under:
  /usr/local/var/cockroach/
Instead of the default port of 8080, the node serves its admin UI at:
  http://localhost:26256`

However, the node is serving the admin UI at localhost:8080. I'm confused by the disclaimer that the node serves its admin UI at localhost:26256.

**Comment by tamird** [comment]
I think the comment is correct. Note the mention of the "launchd configuration". My guess is that you're running the binary by hand (e.g. `cockroach start ...` in the terminal) rather than via launchctl.

I don't think there's anything to do here.

**Comment by tamird** [comment]
I believe you can start cockroach using the launchd configuration by running `brew services start cockroachdb`. Be sure to shut down the other node you have running first.

**Comment by dianasaur323** [comment]
ahhhhh that's a little confusing but I think accurate as you said. Closing out!
