### ISSUE TITLE
ui: opt-in banner showing up as an alert

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#15578]
We recently moved away from opt-in, but the banner is still showing up on the top right in rc.1.

![image](https://cloud.githubusercontent.com/assets/5768024/25601556/00ae9eb2-2ebb-11e7-8df4-b883c584e954.png)

Was this PR supposed to fix that? https://github.com/cockroachdb/cockroach/pull/15488

**Comment by tamird** [comment]
Yes, but rc1 doesn't include that change.

**Comment by dianasaur323** [comment]
Ah, ok - perfect. I wasn't sure if that merged change was in rc.1 yet or not. Let's close this out then.

**Comment by tamird** [comment]
By the way, here's a list of all the changes which are merged to master but not present on rc1: https://github.com/cockroachdb/cockroach/compare/v1.0-rc.1...master.
