### ISSUE TITLE
sql: add statement to cancel long running query

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#15593]
#7003 will provide the SQL to list all the long running queries in the system. Once that's done, we should add a statement that can cancel a query by query ID from the list.

**Comment by benesch** [comment]
@israelg99, you mentioned you were looking into query cancelation—wanted to put you in touch with @itsbilal ASAP, as he's been hard at work implementing that feature, as laid out in [his RFC](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/query_cancellation.md). Don't want the two of you to duplicate work!

**Comment by itsbilal** [comment]
This should be implemented in master now. Related PRs: https://github.com/cockroachdb/cockroach/pull/17003 https://github.com/cockroachdb/cockroach/pull/17527
