### ISSUE TITLE
gossip, server, ui: Node liveness records from dead nodes never time out

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#15609]
@tamird mentioned this recently but doesn't appear to have filed an issue for it. There's no reason for us to put such a long TTL on node liveness records and/or not remove them for dead nodes. Not removing it is causing node 7 to show up on blue's `debug/problemranges` page even though node 7 was removed from the cluster days ago:

<img width="1336" alt="screen shot 2017-05-02 at 2 50 00 pm" src="https://cloud.githubusercontent.com/assets/7085343/25633878/a493406a-2f46-11e7-8b2a-82efcaaeb12e.png">

**Comment by a-robinson** [comment]
I haven't confirmed, but this might also be aggravating #15342

**Comment by a-robinson** [comment]
@tamird I assume you aren't actually working on this? It's definitely annoying, but we'll probably have to push it to 1.2.

**Comment by tamird** [comment]
Correct.

**Comment by benesch** [comment]
This also impacts decommissioned nodes, which display in the admin UI permanently after decommission as of #17553:

![screenshot 2017-08-09 11 23 24](https://user-images.githubusercontent.com/882976/29200862-fd6f3444-7e26-11e7-96f2-64e0aad82e85.png)

**Comment by tschottdorf** [comment]
How do we feel about making it such that `dead && decommissioned` excludes the node in all listings?

If the node actually still exists, restarting it will make it non-dead, and then it can be recommissioned.

A node that just dies for a few days usually won't be decommissioned (unless the owner intents it to not come back, in which case we do actually want to hide it).

Am I missing caveats here?

**Comment by a-robinson** [comment]
That seems to be what most people want. The only caveat I'm aware of is that (like cockroaches) getting rid of them has proven to be hard -- they just keep reappearing after we think we've killed the last of them.

**Comment by dianasaur323** [comment]
@vivekmenezes could we assign someone to take on this decommissioning node issue? We won't have time to tackle it on the admin UI team.

**Comment by tschottdorf** [comment]
I think this is mostly done, @m-schneider to confirm and close.
