### ISSUE TITLE
security: investigate scrypt vs bcrypt for password storage

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#1560]

**Comment by mberhault** [comment]
I believe this is 1.0, along with all user-related stuff (web authentication, password-based pg authentication, etc...)

**Comment by mberhault** [comment]
I don't think there's much to do here. @asubiotto?

**Comment by asubiotto** [comment]
I don't think so either. I don't think it's a necessary enhancement at this stage.
