### ISSUE TITLE
storageccl: figure out what to do with TestImport

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#15611]
It's not clear if this is providing any value of the normal restore testing. It needed to be skipped so we could get another change in for rc2. Determine what we want to do.

**Comment by danhhz** [comment]
We should probably revisit this soon

**Comment by danhhz** [comment]
@mjibson do you remember what was broken? I just tried unskipping this and it passes

**Comment by mjibson** [comment]
Nope, not sure what was broken.

**Comment by danhhz** [comment]
Closed by https://github.com/cockroachdb/cockroach/pull/16469
