### ISSUE TITLE
distsql: improve memory accounting

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#15635]
Currently the memory accounting happens against a single monitor. We should count and perhaps limit per user session as well (we would have to plumb a session id through).

**Comment by arjunravinarayan** [comment]
Are we doing this in 1.1? I think this is going to get punted to 1.2

**Comment by RaduBerinde** [comment]
Indeed, moved to 1.2.

**Comment by a6802739** [comment]
@RaduBerinde, could I have a try for this?

**Comment by RaduBerinde** [comment]
@a6802739 sure.. You can make a proposal on what to do (either here in an RFC). I would first investigate how memory accounting works for non-distributed SQL.

**Comment by a6802739** [comment]
@RaduBerinde, sure. Thank you very much.

**Comment by jordanlewis** [comment]
@a6802739 are you still working on this?

**Comment by a6802739** [comment]
@jordanlewis , Sorry for late response.

Yes, I'm still working on this. I'll ask for some help If I met some problems.

Thank you very much.
