### ISSUE TITLE
sql, distsql: account for aggregate func memory usage

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#15634]
We don't account for the size of the AggregateFunc implementation itself, including the size of whatever Datum it's holding. We do the latter for things like concatenation array aggregation, but not for everything that can have arbitrary size (like decimal).

We must be careful to not simply just call `Grow()` every time the datum changes or that can easily become the bottleneck of an aggregation operation. We could have a pre-counted "grace" size of e.g. 16 bytes and only grow for things that are beyond that.

CC @justinj

**Comment by cuongdo** [comment]
@justinj can you take this on for 1.1? if not please move to 1.2

**Comment by jordanlewis** [comment]
We should get to this soon.

**Comment by solongordon** [comment]
Fixed by #28303.
