### ISSUE TITLE
distsql: flaky range relocation in test

### ISSUE THREAD

**Issue by eisenstatdavid** [cockroachdb/cockroach#15646]
From https://teamcity.cockroachdb.com/viewLog.html?buildId=240651&buildTypeId=Cockroach_UnitTests:

```
TestLogic/5node/distsql_agg 	
 	Already fixed in:	15612	#14725 	eisen (1) 	03 May 17 15:19
First failure:	15612	#14642 	eisen (1) 	02 May 17 19:32
 logic_test.go:1625: 
    testdata/logic_test/distsql_agg:353: expected success, but found
    pq: snapshot failed: (n1,s1):?: remote couldn't accept snapshot with error: [n1,s1],r21: cannot apply snapshot: snapshot intersects existing range [n1,s1,r10/1:/{Table/51/1/9-Max}]
logic_test.go:1635: 
    testdata/logic_test/distsql_agg:353: error in statement, skipping to next file
```

**Comment by m-schneider** [comment]
@a-robinson Do you happen to know anything about this, this just happened to me too.

**Comment by a-robinson** [comment]
I don't know about the "snapshot intersects existing range" error specifically. I believe @bdarnell is looking into #16251, which will likely involve fixing that error.

Rebalancing did get extra thrashy today, though, due to #16747 getting merged. #16772 should help with that.

**Comment by tschottdorf** [comment]
I think this is just the same bug as https://github.com/cockroachdb/cockroach/issues/16729. It's related to the testing infrastructure and not an actual bug. Of course we still need to fix it. Let me dig up that work in progress...
