### ISSUE TITLE
rsg: investigate why RSG took so long to find #15632

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#15650]
https://github.com/cockroachdb/cockroach/issues/15632 had been present for a long time, but RSG just found it. RSG probably needs a smarter way of generating whatever arguments it was, because there may be more bugs of the same kind lurking.

**Comment by mjibson** [comment]
This is slow because `a_expr` generation is not great, and IFNULL has two of them. `IF` pretty much never generated for a similar reason, which has 3 of them. Probably need to do some work to make a_expr (and friends) faster so we can get a better test coverage.

**Comment by petermattis** [comment]
@mjibson Is there work to be done here for 1.1, or should we burden our future selves?

**Comment by mjibson** [comment]
No need to be 1.1, but I still want to improve this.
