### ISSUE TITLE
cli: Ask password twice on secure cluster

### ISSUE THREAD

**Issue by leomkkwan** [cockroachdb/cockroach#15656]
When using password login to a secure cluster from cli, it will ask password twice. Test on version v1.0-rc.1.

> root@local:/home/leo/cockroach# ./cockroach sql --certs-dir=certs --user=leo
Enter password:
Confirm password:
 Welcome to the cockroach SQL interface.
 All statements must be terminated by a semicolon.
 To exit: CTRL + D.

I am not sure if that intend, but it is kind of weird to ask password twice in a login session.

**Comment by mberhault** [comment]
That's definitely not intended and just silly. I'll try to get this before 1.0.
