### ISSUE TITLE
Release: 1.0-rc.2

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#15660]
The candidate SHA is 32862bd08f4fdb202475eb6eccc30bff38598e11
Deployment status is: deployed to `adriatic`, `blue`, `cerulean`,  `denim`, `navy`, `omega`

[Release process checklist](https://github.com/cockroachdb/cockroach/wiki/Release-Process)
- [x] Check and verify cluster status
- [x] Tag release and push tag
- [x] [Trigger release build](https://teamcity.cockroachdb.com/viewType.html?buildTypeId=Cockroach_MergeToMaster)
- [x] Check and verify binaries
- [x] Update the [Homebrew tap](/cockroachdb/homebrew-cockroach)
- [x] Update docs
- [x] Announce version to the registration cluster (see internal production instructions)
- [x] External communications for release

**Comment by mberhault** [comment]
Release notes: https://github.com/cockroachdb/docs/pull/1357

**Comment by mberhault** [comment]
`blue` was wiped. all other clusters were upgraded with a rolling restart.

**Comment by mberhault** [comment]
Will need to pull in #15679 (commit 5fad52b9f54667ea243a02652d4885047056d885).

**Comment by mberhault** [comment]
We also need #15688 and an upcoming change by @knz.

**Comment by mberhault** [comment]
Adding a few changes to the build tools.

**Comment by mberhault** [comment]
@RaduBerinde: do you want a release notes entry for #15688?

**Comment by RaduBerinde** [comment]
Sure, "fixed instances of incorrect NULL results when using an aggregation with an empty table".

**Comment by mberhault** [comment]
New candidate sha is 1700211837c3e519bf093f8cda26fe2afb028ff3.
Binaries are built and being pushed to all candidate clusters listed in the commit message.

**Comment by mberhault** [comment]
`adriatic`, `blue`, `cerulean`, `navy`, `omega` upgraded to 1700211
