### ISSUE TITLE
distsql: the Context used for expression evaluation (EvalCtx.Ctx) is wrong

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#15670]
As indicated by the TODO here: https://github.com/cockroachdb/cockroach/blob/549631b/pkg/sql/distsqlrun/server.go#L180

Each processor that needs to evaluate expressions should initialize the `Ctx` inside the `EvalCtx`. This would probably be made easier by making the EvalCtx immutable and passing it by value more.

**Comment by cuongdo** [comment]
This still seems important and should be done earlier, to avoid another last-minute scramble. Is this doable for 1.1?

**Comment by andreimatei** [comment]
I don't know how much work it is to fix this, I have to look at the code. But I don't think it's a particularly big deal; I think this just affects the log messages from expression evaluation.

**Comment by RaduBerinde** [comment]
Ah, from the description it seemed that this is about an `EvalContext` being wrong, but it's about a `context.Context`, so it's not really that important. Moving to 1.2.

**Comment by andreimatei** [comment]
Why does it seem out of date or different? If you look for uses of `evalCtx.Ctx()` in distsql you find plenty - e.g. https://github.com/cockroachdb/cockroach/blob/b1d18df2ed1ff4a1f7e0d7825977dd549f9f752c/pkg/sql/distsqlrun/sorter.go#L225

Also all the expression evaluation done by DistSQL.

**Comment by andreimatei** [comment]
Looks like this was fixed for most processors at some point:
https://github.com/cockroachdb/cockroach/blob/e207532786239891f1581da559c8c401c6c6b408/pkg/sql/execinfra/processorsbase.go#L805
