### ISSUE TITLE
ui: enable some form of analytics

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#15674]
Embed Google Analytics or something similar in the Admin UI. Like any other application, we need insights into how the UI is being used.

Cc @kuanluo, @dianasaur323

**Comment by dianasaur323** [comment]
Further conversation here: https://github.com/cockroachlabs/registration/issues/60

**Comment by mrtracy** [comment]
The UI has been augmented with segment analytics, which are enabled if a cluster allows diagnostic information to be collected. Any further additions or changes to the analytics being logged should be tracked as a separate issue.
