### ISSUE TITLE
confusion about how to build cockroachdb from source

### ISSUE THREAD

**Issue by williamh** [cockroachdb/cockroach#15684]
Hello, this is a question about building from source.

I am a maintainer on Gentoo Linux, and I want to package cockroach-1.0-rc1, but your documentation refers to a source tarball which is just named cockroach-latest.src.tgz with no version number in the name. Is this 1.0-rc1, or is it some snapshot later than that?

I have spent most of the day trying to figure out how to check out your git repositories and build from there without the build checking out anything from git but haven't had any luck.

If the tarball referred to in your documentation is the source for 1.0-rc1 do you mind versioning your tarball names in the future? If not, is there a simple way to download the release from http://github.com/cockroachdb/cockroach/releases, put the vendored code in the vendor directory, then build everything without the build process trying to pull from git?

Thanks,

William

**Comment by mberhault** [comment]
moving this issue over to the docs repo: https://github.com/cockroachdb/docs/issues/1368
