### ISSUE TITLE
parser: `ColumnType` should support all types

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#15714]
The problem is mentioned in https://github.com/cockroachdb/cockroach/pull/15710#issuecomment-299458840

We use `DatumTypeToColumnType` to create casts when serializing expressions for distsql and for checking expressions for equivalence. The issue is that not all types are supported by this function (only the types that can be table columns).

Given that `ColumnType`s are what we put in casts and type annotations, it follows that we only support this subset of types in casts and type annotations (which is incomplete).

We should have these support all types (including for `DatumTypeToColumnType`) and divorce them from the concept of what we can store in table columns.

CC @knz @jordanlewis

**Comment by petermattis** [comment]
@arjunravinarayan for investigation or triage.

**Comment by RaduBerinde** [comment]
I think that currently this is only a problem for tuples, and that is tracked separately by #15938. Closing this one.
