### ISSUE TITLE
sql: unique_rowid() returns and javascript

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#15721]
`unique_rowid()` returns values that cannot be represented exactly by a number in Javascript. For example, `235191684988928001` is a recent value returned by `unique_rowid()` but in Javascript that is represented as `235191684988928000` (notice the last digit is different). The precision loss can then foul up Javascript application which temporarily stores the ID and then queries using it.

Reported by @mattiasmak. This is arguably a bug in the NodeJS driver.

**Comment by tamird** [comment]
Is there any sample code to go with this? Specifically, I'm curious about
how the return type gets reported to the Javascript application, and which
Node driver is being used.

**Comment by petermattis** [comment]
`node-pg` was mentioned. @mattiasmak do you have a snippet of code you can share with us demonstrating this problem?

**Comment by jseldess** [comment]
@petermattis, is there a workaround we should suggest here? Don't query based on a returned `unique_rowid()` value in a Javascript application?

**Comment by petermattis** [comment]
The workaround would be to cast the integer to a string when using a language that doesn't support 64-bit integer types. For example: `SELECT CAST(id AS string) FROM my_table`.

**Comment by benesch** [comment]
Since v3, which is ancient at this point, the node-postgres driver (the de facto standard driver for Node) will return bigints as strings unless you explicitly configure it otherwise ([source](https://github.com/brianc/node-postgres/blob/master/CHANGELOG.md#v300))

We should probably document this necessity. My guess is you've somehow changed this default, @mattiasmak?

**Comment by tamird** [comment]
Heh, v3 only changed the handling of arrays of bigints. Solitary bigints
were correctly handled since v2, released 2013-06-18 (see
https://github.com/brianc/node-postgres/pull/353).

**Comment by jseldess** [comment]
I don't understand the implications of the last two comments. Here's how I'm explaining the limitation currently. Is it still accurate? If not, how should I change it?

> The `unique_rowid()` [function](functions-and-operators.html) returns values that cannot be represented exactly by numbers in Javascript. For example, a `235191684988928001` value returned by `unique_rowid()` would get represented as `235191684988928000` in Javascript. Notice that the last digit is different. In such cases, if the Javascript application temporarily stores the value `235191684988928001` and queries using it, it won't match the value that actually got stored.

> As a workaround when using JavaScript or another language that doesn't support 64-bit integer types, cast the integer to a string server-side before inspecting or using it, for example:

> ~~~ sql
> SELECT CAST (id AS string) FROM my_table;
> ~~~

**Comment by tamird** [comment]
I believe we don't need to document any workarounds for this; this doesn't
appear to be a CockroachDB issue, and it doesn't even appear to be
a node-postgres issue.

We're still waiting for some code to reproduce this problem, so we can
decide if it's something we need to address.

**Comment by tamird** [comment]
Ah, I see we already have this on known-limitations. We should remove it. It's also the case that this kind of problem will affect *any* 64-bit integer returned from the database to a Javascript application (but again, only with prehistoric versions of node-pg or with exotic configurations of node-pg), so if we *do* decide to document this, we should not confine the note to `unique_rowid`.

**Comment by jseldess** [comment]
Thanks, @tamird. Asked @sploiselle to remove it as part of https://github.com/cockroachdb/docs/pull/1400.

**Comment by benesch** [comment]
Wait wait! I think this is worth documenting. I'll wager there are many node applications that choose to parse `int8`s as ints instead of strings. ([See here](https://github.com/sequelize/sequelize/issues/1774) for one such discussion.) 

I do think we should expand the documentation to include all 64-bit integers, but calling out `unique_rowid` explicitly isn't so crazy. Auto-incrementing primary keys are exactly where most users will run into this first, if they run into it, because parsing a Postgres auto-incrementing `int8` column as a number will work until you hit your 100-billionth insert or whatever, whereas it'll fall over basically immediately with Cockroach.

**Comment by jseldess** [comment]
Perhaps this just shouldn't be documented as a known limitation, which implies a limitation on the part of CockroachDB, but rather somewhere else, maybe in the SQL-specific FAQs section?

**Comment by benesch** [comment]
That's a good point! It's not a known limitation; it's a "gotcha" for folks who were already bending the rules.

**Comment by benesch** [comment]
It just occurred to me that our examples-orm repository literally gets this wrong at this very moment. https://reviewable.io/reviews/cockroachdb/examples-orms/20#-Kfiyp_3rHRaWNdsq433

We should document this more loudly, if anything.

**Comment by tamird** [comment]
Ouch.

**Comment by petermattis** [comment]
@jseldess Have we done anything towards documenting this?

**Comment by petermattis** [comment]
@jseldess Is this done?

@benesch Was `examples-orms` fixed?

**Comment by jseldess** [comment]
It looks like we [removed this from known limitations](https://github.com/cockroachdb/docs/pull/1400/files#diff-b959712af7fa5ed1c822d0310313666eL41), but we never put it back anywhere else. 

I've just opened this docs PR to add it back as a SQL FAQ: https://github.com/cockroachdb/docs/pull/1928.

**Comment by jseldess** [comment]
Docs PR merged: https://github.com/cockroachdb/docs/pull/1928

@petermattis, ok to close this?

**Comment by petermattis** [comment]
Looks great.
