### ISSUE TITLE
jepsen: the Register test is improperly configured

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#15734]
From https://teamcity.cockroachdb.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=243251#_focus=3362

(Detected using new scripts from #15717 )

```
ERROR [2017-05-06 01:46:36,330] main - jepsen.cli Oh jeez, I'm sorry, Jepsen broke. Here's why:
java.util.concurrent.ExecutionException: java.lang.AssertionError: Assert failed: This jepsen.independent/concurrent-generator has 5 threads to work with, but can only use 0 of those threads to run 0 concurrent keys with 10 threads apiece. Consider raising or lowering the test's :concurrency to a multiple of 10.
(= thread-count (* group-size group-count))
```

The error occurs for any combination of nemeses.

**Comment by aphyr** [comment]
Ah! Like the error message says, "Consider raising or lowering the test's :concurrency to a multiple of 10.". It's currently 5. All you have to do to fix that is pass --concurrency 10 (or 20, 100, etc).
