### ISSUE TITLE
sql: `information_schema.*.IS_GRANTABLE` has wrong type

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#15746]
Looks like every table that's been added to `information_schema` with an `IS_GRANTABLE` column has been created with the (perfectly sensible) `BOOL` type. This isn't quite right, though, since [`information_schema` predates `BOOL` being part of SQL](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/information_schema.go#L56-L58). 

For example, MySQL defines `information_schema.table_privileges` like so:

```sql
CREATE TEMPORARY TABLE `TABLE_PRIVILEGES` (
  `GRANTEE` varchar(81) NOT NULL DEFAULT '',
  `TABLE_CATALOG` varchar(512) NOT NULL DEFAULT '',
  `TABLE_SCHEMA` varchar(64) NOT NULL DEFAULT '',
  `TABLE_NAME` varchar(64) NOT NULL DEFAULT '',
  `PRIVILEGE_TYPE` varchar(64) NOT NULL DEFAULT '',
  `IS_GRANTABLE` varchar(3) NOT NULL DEFAULT ''
) ENGINE=MEMORY DEFAULT CHARSET=utf8 
```

But we define it like this:

```
CREATE TABLE information_schema.table_privileges (
	GRANTOR STRING NOT NULL DEFAULT '',
	GRANTEE STRING NOT NULL DEFAULT '',
	TABLE_CATALOG STRING NOT NULL DEFAULT '',
	TABLE_SCHEMA STRING NOT NULL DEFAULT '',
	TABLE_NAME STRING NOT NULL DEFAULT '',
	PRIVILEGE_TYPE STRING NOT NULL DEFAULT '',
	IS_GRANTABLE BOOL NOT NULL DEFAULT FALSE,
	WITH_HIERARCHY BOOL NOT NULL DEFAULT FALSE
);
```

I think `IS_GRANTABLE` should have type `STRING` and hold either `YES` or `NO`—or perhaps we make like PostgreSQL and define a `yes_or_no` type for use in the information schema.

We also declare `IS_GRANTABLE` as `NOT NULL`... then proceed to return nothing but `NULL`s.

I'm not aware of any applications actually encountering these bugs, just something I saw while reading through the code. Assigning to @jordanlewis and @nvanbenschoten to triage. Doesn't seem like the world's biggest deal.

**Comment by jordanlewis** [comment]
@nvanbenschoten did you just fix this?

**Comment by nvanbenschoten** [comment]
Yep! Didn't know about this issue though. Thanks for catching that.

Fixed in https://github.com/cockroachdb/cockroach/pull/21612.
