### ISSUE TITLE
security: TLS paths config is non-standard

### ISSUE THREAD

**Issue by gpaul** [cockroachdb/cockroach#15760]
**FEATURE REQUEST**

The recent changes to how TLS certificates and keys are configured is non-standard.

```
      --certs-dir string            
        The path to the directory containing SSL certificates and keys.

        Cockroach looks for certificates and keys inside the directory using the
        following naming scheme:

          - CA certificate and key: ca.crt, ca.key
          - Server certificate and key: node.crt, node.key
          - Client certificate and key: client.<user>.crt, client.<user>.key
``` 

Storing CA and end entity keys and certs in the same directory is not something I've heard of.

For example, on RHEL the default locations are
- `/etc/pki/CA/private/`: CA keys
- `/etc/pki/CA/certs/`: CA certificates
- `/etc/pki/tls/private/`: end entity keys
- `/etc/pki/tls/certs/`: end entity certificates

It would be good to have these configurable so I don't need to create `/etc/pki/cockroachdb/`, working outside the distribution defaults. 

I think this probably came about through your assuming that people use the cockroach cli to create certificates, but please note that in any deployment scenario where an enterprise user is serious about security they will likely have policies in place dictating how certificates are created and where they are stored.

Thanks for the good work, keep it up!

**Comment by gpaul** [comment]
That sounds like a good step forward to me if the CA cert path can be individually customized.

**Comment by gpaul** [comment]
To use TLS I need to specify (one or more) CA bundles, my private key, and it's accompanying certificate.

To enable PKI-based client authentication I need to specify (a directory full of) trusted peer certificates.

**Comment by jgehrcke** [comment]
Also, `ca.key` should *never* be passed to CockroachDB unless CockroachDB is intended to sign/issue certificates.

(The help text `- CA certificate and key: ca.crt, ca.key` should not encourage operators to actually place the private key corresponding to their signing CA certificate into said directory).

**Comment by riaan53** [comment]
Any update on this? 

Have a look at how https://github.com/nats-io/gnatsd handles this.

**Comment by jjzazuet** [comment]
Hi, I'm also interested in seeing if the way to deploy/maintain/rotate certificates has changed. Thanks!

**Comment by mberhault** [comment]
No changes to the way we handle certificate nomenclature. If anything we've added more certificates that can be located in the certs directory. eg: CA for client certificates, CA for admin UI, client-only certificate for the node (to talk to other nodes), UI server certificate.

We still feel this approach to be more convenient that individually specifying full paths to each certificate and key, especially given the fact that "standard" locations are anything but. Furthermore, symlinks can easily be used to work with certificate PKI infrastructure with incompatible locations.

A final note: client certificates do not need to live on the node, all certificate verification is done using the CA, not by comparing against self-signed certificates stored locally.
