### ISSUE TITLE
Interacting with CockroachDB from Go

### ISSUE THREAD

**Issue by ggitau** [cockroachdb/cockroach#1576]
Hi?
What options are available to interact with CockroachDB from go? The official go libraries might not be available at this point or are they?

**Comment by MBerhault** [comment]
Cockroach is written entirely in Go so all client libraries are first implemented in Go with other languages to follow as demand increases.

**Comment by bdarnell** [comment]
But note that "official" clients aren't yet available in any language: we're in the process of replacing our current key-value API with a SQL interface.

**Comment by vivekmenezes** [comment]
We are currently working on getting the go sql driver working with
cockroach; see: https://golang.org/pkg/database/sql/driver/. We should get
the basic functionality working by end July.

Vivek

**Comment by ggitau** [comment]
Looking forward to the sql driver. Heard about a HTTP API, is that available as a base for client implementations in other languages?

**Comment by vivekmenezes** [comment]
The HTTP SQL API is in sql/sqlwire/... But this is all in pre-alpha and
subject to a *lot* of change. What language were you planning to implement
for? Thanks

**Comment by ggitau** [comment]
Oh in that case i'll be patient and wait for the go sql driver....wanted to use the HTTP API directly in either go/java.

**Comment by vivekmenezes** [comment]
Hi,

We've made great progress on the SQL driver but it's still not ready for
alpha. I'll update you when you can start trying it out.

Thank you for your patience

Vivek

**Comment by ggitau** [comment]
Nice. Thanks for the update

**Comment by ggitau** [comment]
Hi,
What's the progress on the sql driver?Is it usable at this point?If so, is there a simple code example for this?

**Comment by vivekmenezes** [comment]
We've made significant progress on the SQL implementation and are getting
close to being Beta ready. We are for the most part feature complete for
Beta, and are going to be spending the next two months working on stability
and performance.

You're more than welcome to try out the alpha implementation at this stage.

Vivek

**Comment by tschottdorf** [comment]
There's some example code here:
https://github.com/cockroachdb/examples-go/blob/master/bank/sql_bank/main.go

**Comment by ggitau** [comment]
Thanks guys.I really appreciate this.
