### ISSUE TITLE
sql+storage: clarify/extend support for single rows larger than a range

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#15770]
(Issue created to mirror known limitations listed in https://github.com/cockroachdb/docs/pull/1381#issuecomment-299895895 )

Right now the combined size of all the values in a single column family has to fit within a range (because a single k/v pair must fit), however this is not documented and in particular it is unclear which tunables, if any, have an influence on this limitation.
The following questions need answer:

- what is the maximum size of all the values in a column family for a single row?
- is this maximum size configurable? how?
- is there any minimum value CockroachDB is able to guarantee for this maximum for the future (commitment to backward compatibility)?

A further item (perhaps not in scope for this issue) is to investigate whether it is possible to lift this requirement, by auto splitting large values over multiple k/v pairs.

**Comment by jseldess** [comment]
@knz or @danhhz, please check the language I added on this to the known limitations: https://github.com/cockroachdb/docs/pull/1381

**Comment by cuongdo** [comment]
looks like this is documented
