### ISSUE TITLE
sql: BACKUP/RESTORE can take placeholders in pgwire but not in SQL

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#15772]
Currently, the BACKUP and RESTORE parser statements can take either names or placeholders for their targets.

However, neither BACKUP nor RESTORE are part of the `preparable_stmt` rule in `sql.y`, which prevents them from being used with a `PREPARE` statement in SQL.

This can be fixed by adding `backup_stmt` to the `preparable_stmt` rule and adding tests.

**Comment by jordanlewis** [comment]
Alternatively, if it's not needed, we could remove the extra logic for dealing with placeholders from BACKUP and RESTORE entirely. Could @danhhz or @benesch weigh in here?

**Comment by benesch** [comment]
No, we definitely want placeholder support! If it's missing in `preparable_stmt`, that's surely an oversight.

**Comment by danhhz** [comment]
We definitely need the pgwire placeholder behavior. I don't care if they work with PREPARE

**Comment by benesch** [comment]
I'll draw up a PR. They should work with `PREPARE`.

**Comment by jordanlewis** [comment]
The main thing that's giving me pause here is that `preparable_stmt` currently only contains "the big 4": select, insert, update and delete. And that's the same in Postgres.

Perhaps we don't care to support `PREPARE` for anything but those, even though we might support pgwire placeholders in other statements?

**Comment by benesch** [comment]
What other queries do we support pgwire placeholders for? (And/or how I can I find out?)

**Comment by jordanlewis** [comment]
I don't know :( It might be everything, although that sounds wrong? I would love to find out the answer to this.

**Comment by danhhz** [comment]
@benesch I'd look for PLACEHOLDER in sql.y

**Comment by jordanlewis** [comment]
It looks like Postgres doesn't support placeholders for anything besides The Big 4 in pgwire or SQL. So to be consistent we should probably add these to `preparable_stmt`, but I don't really feel that strongly about it. I'm happy to see this be left for a rainy day.
