### ISSUE TITLE
sql: system.settings table should not be editable.

### ISSUE THREAD

**Issue by arjunravinarayan** [cockroachdb/cockroach#15773]
The `system.settings` table exposes information about cluster settings that were manually set:

```
root@:26257/> select * from system.settings;
+-------------------------------+-------+----------------------------------+-----------+
|             name              | value |           lastUpdated            | valueType |
+-------------------------------+-------+----------------------------------+-----------+
| diagnostics.reporting.enabled | false | 2017-05-08 17:11:04.742088+00:00 | b         |
| sql.defaults.distsql          |     1 | 2017-04-27 17:53:47.355744+00:00 | e         |
+-------------------------------+-------+----------------------------------+-----------+
```

The way to see all cluster settings is `SHOW ALL CLUSTER SETTINGS`. The way to change settings is also `SET CLUSTER SETTING foo = bar`, which also happens to update the `system.settings` table. However, this table is editable, which bypasses any guards in the `SET` code path. For instance:

```
root@:26257/> set cluster setting sql.defaults.distsql = 3;
pq: invalid integer value '3' for enum setting
```

This can be bypassed with:
```
root@:26257/> UPSERT INTO system.settings VALUES ('sql.defaults.distsql', '3', now(), 'e');
INSERT 1
```
which silently succeeds without updating the value. However if you do use a valid value, this does update the underlying value.

```
root@:26257/> UPSERT INTO system.settings VALUES ('sql.defaults.distsql', '0', now(), 'e');
INSERT 1
root@:26257/> show cluster setting sql.defaults.distsql;
+----------------------+
| sql.defaults.distsql |
+----------------------+
|                    0 |
+----------------------+
(1 row)
```

This should be fixed. I propose making `system.settings` non-updatable, so all updates have to go through the `SET` code path.

**Comment by dt** [comment]
dupe #15250 ?

**Comment by arjunravinarayan** [comment]
Yes. Thanks for the triage, and sorry for not catching that!
