### ISSUE TITLE
sql: DROP DATABASE is failing in surprising ways

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#15786]
problem reported by a user:

DROP DATABASE test;
pq: invalid foreign key: missing table=64 index=1: descriptor not found

I created multiple table on test start and removed them afterwards (Not removing the database). I did this multiple time to try out my schema. And after a while I can remove the database (one specific table). When i look in the UI and look at the table schema it's just empty. Like it was removed but not correctly.

when i try to remove the faulty table I also get:

DROP table issues;
pq: invalid foreign key: missing table=64 index=1: descriptor not found

So then I started to create a new database with tables at the beginning of the test and then remove the database.

This led to:

root@:26257/> set database=aam_test;
SET
root@:26257/aam_test> show tables;
pq: no database with ID 183 found
I use the same Database name when I create a new.

Everything worked in the beginning fine. But after a while it started to get wierd.

I use

Build Tag: v1.0-rc.2
Build Time: 2017/05/05 13:55:11
Distribution: CCL
Platform: linux amd64
Go Version: go1.8.1
C Compiler: gcc 6.3.0
Build SHA-1: 1700211837c3e519bf093f8cda26fe2afb028ff3
Build Type: release

**Comment by vivekmenezes** [comment]
This looks like a bug where a table gets dropped but a FK reference to it is not deleted.

**Comment by vivekmenezes** [comment]
@dt assigning to masha so she can take a look at this.

**Comment by m-schneider** [comment]
I took a look at this and couldn't reproduce. Has anyone been able to?

**Comment by justinj** [comment]
Conceivably related to #16316 maybe? (but :man_scientist: 🐶)

**Comment by vivekmenezes** [comment]
closing for now.
