### ISSUE TITLE
Installing cockroachdb with docker

### ISSUE THREAD

**Issue by ggitau** [cockroachdb/cockroach#1578]
I get the following error when I try install CockroachDB via docker. Any pointers as to what could be causing this?

docker run -t -i -p 8080:8080 cockroachdb/cockroach shell
/bin/bash: shell: No such file or directory

**Comment by tschottdorf** [comment]
it's because we broke something. I'll ping you when it's been fixed. Thanks for reporting!

**Comment by ggitau** [comment]
Thanks

**Comment by tschottdorf** [comment]
@ggitau you should be good to go now.

**Comment by ggitau** [comment]
It works. Thanks.
