### ISSUE TITLE
storage: result is ambiguous (error=r1513 was not found, pending RPCs=1)

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#15782]
`blue` is seeing frequent errors (see `logs/block_writer.stderr`) of the form in the title:

```
2017/05/08 19:25:35 pq: result is ambiguous (error=r2793 was not found, pending RPCs=1)
2017/05/08 19:25:36 pq: result is ambiguous (error=r2936 was not found, pending RPCs=1)
2017/05/08 19:25:37 pq: result is ambiguous (error=r371 was not found, pending RPCs=1)
2017/05/08 19:25:38 pq: result is ambiguous (error=r844 was not found, pending RPCs=1)
2017/05/08 19:25:38 pq: result is ambiguous (error=r1782 was not found, pending RPCs=1)
2017/05/08 19:25:38 pq: result is ambiguous (error=r3305 was not found, pending RPCs=1)
2017/05/08 19:25:38 pq: result is ambiguous (error=r710 was not found, pending RPCs=1)
```

The instances listed here seemed to coincide with replica rebalancing following a node outage. 

I'm not sure if there is anything to be done, though it is worth double-checking that we're not returning an ambiguous result error unnecessarily.

**Comment by bdarnell** [comment]
Might be caused by #15573.

**Comment by spencerkimball** [comment]
There's nothing I can think of to do here. It's waiting a whole second to receive word back from those pending RPCs (which may have succeeded), but for whatever reason (likely caused by the chaos underway), the extant pending RPC doesn't come back and we must return an ambiguous result.

**Comment by tamird** [comment]
It's worth mentioning that the timeout we use here is somewhat odd - we already enforce a 3-second "liveness" timeout on gRPC connections via grpc-level heartbeats which close the underlying transport if they time out. That would cause these pending RPCs to return an error.

I think we should consider removing (or greatly relaxing) the explicit timeout in the dist sender. If that means we need to shorten the timeout on the connection-level keepalives, I'd rather we did that than to have several competing "partition detection" timeouts in the system.

**Comment by bdarnell** [comment]
The DistSender timeout is not just to detect partitions. It's also intended to handle nodes that may be slow to respond for other reasons even while the network is healthy (some discussion of this idea [here](http://www.bailis.org/blog/doing-redundant-work-to-speed-up-distributed-queries/)). Maybe that doesn't make sense for us given our reliance on the single lease holder, but at least conceptually it's not redundant with network-level partition detection.
