### ISSUE TITLE
storage: send MsgApp traffic on a separate gRPC stream

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#15808]
Forked from [#15702](https://github.com/cockroachdb/cockroach/issues/15702#issuecomment-300189834):

> Also, pulling on the thread a little further, even if they are not reproposed, commands this large are sufficient to cause heartbeats to be delayed, perhaps to the point of causing elections. Maybe MsgApp messages should use separate GRPC streams (similar to the way that MsgSnap used to). This would need a lot of testing (we want to minimize the chance that MsgApps are reordered with respect to each other, but I think raft will tolerate reorderings of different message types reasonably well)

To be clear, `MsgSnap` still uses a different stream, but that is due to it using a different endpoint.

**Comment by cuongdo** [comment]
@petermattis changing this to 1.2, because it's late to be making this change

**Comment by tschottdorf** [comment]
@bdarnell please reopen if you think it's valuable to keep this open.
