### ISSUE TITLE
sql: write ARRAY encoding RFC

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#15818]
One of the first steps for adding full support for ARRAY columns (#2115) is the creation of an RFC for the KV encoding of ARRAYs. Possible considerations are:

1. Future-proofing. It'll be significant effort to change the encoding later
2. Efficient support for expected access patterns (see [this comment on 2115](https://github.com/cockroachdb/cockroach/issues/2115#issuecomment-265773792) for some ideas)
3. Multi-dimensional arrays

cc @jordanlewis @knz for other thoughts regarding what should go into the RFC

**Comment by knz** [comment]
Note that the kV indexing of arrays and that of array indexes are two fundamentally different problems and I suspect there will be not one but multiple index types for array columns depending on the queries that need to be satisfied.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by petermattis** [comment]
@knz I believe the focus of the RFC is encoding ARRAYS into values, not keys (which would be necessary to use an ARRAY column in an index).

A big question to answer is if an ARRAY is encoded into a single KV or if it can be split across multiple KVs. The former would place limits on the size of the ARRAY. The latter introduces complexity and questions about how we specify (or heuristically determine) where the breakpoints are performed.

**Comment by vivekmenezes** [comment]
This is done right?

**Comment by justinj** [comment]
Yes!
