### ISSUE TITLE
sql: use Hibernate's test suite

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#15821]
Currently, we have a [basic test](https://github.com/cockroachdb/examples-orms/tree/master/java/hibernate) for Hibernate compatibility. Because Hibernate is popular with our users, we should increase our Hibernate test coverage to more proactively discover issues and regressions. 

A relatively straightforward way to do that is to regularly run the subset of Hibernate test suite that is relevant to CockroachDB.

@jordanlewis would be a great person to consult with for this task

**Comment by cuongdo** [comment]
Where do this stand now?

**Comment by justinj** [comment]
I'm currently re-running the test suite since the recent alias additions should have improved our compatibility a decent amount. I'm going to try to bucket all the failures and see where we stand.

**Comment by vivekmenezes** [comment]
This is a fix going into our fork of the Hibernate repo. Taking it out of the 1.1 release.

**Comment by BramGruneir** [comment]
This is now completed. See #30565

**Comment by vivekmenezes** [comment]
hooray!
