### ISSUE TITLE
sql: get an unexpected CastTarget <nil> when creating a view

### ISSUE THREAD

**Issue by jrote1** [cockroachdb/cockroach#15827]
[debug.zip](https://github.com/cockroachdb/cockroach/files/988328/debug.zip)
When creating the following view I am getting a `CastTarget<nil>` exception, I have attached my debug logs.

```
create view "Products by Category" AS
SELECT "Categories"."CategoryName", "Products"."ProductName", "Products"."QuantityPerUnit", "Products"."UnitsInStock", "Products"."Discontinued"
FROM "Categories" INNER JOIN "Products" ON "Categories"."CategoryID" = "Products"."CategoryID"
WHERE "Products"."Discontinued" <> true
```

**Comment by jordanlewis** [comment]
Hi @jrote1,

Thanks for the report. We recently fixed a similar bug in #15798, but it doesn't look like that is the cause of your troubles here. I tried to reproduce the issue on a version without the fix, but didn't have any luck. I attached my session log - were there other steps you took to uncover this problem?

https://gist.github.com/jordanlewis/f5d8fb67603d661c8a2b914e2dfbc2eb

**Comment by jrote1** [comment]
I will be working on this at the weekend so i'll try and provide a more exact repo

**Comment by jrote1** [comment]
Running the following SQL on a database will replicate this issue
[CauseNodeToCrash.txt](https://github.com/cockroachdb/cockroach/files/1003903/CauseNodeToCrash.txt)

**Comment by jrote1** [comment]
This consistently replicates the problem for me on linux and windows

**Comment by jordanlewis** [comment]
Thanks for the detailed report. I'll look into this today.

**Comment by jordanlewis** [comment]
Sorry for the delay. I was able to reproduce the panic in our 1.0 version but not in our 1.0.2 version - and I confirmed that #15798 fixed the panic. In 1.0.2 however, there's a different problem:

```
root@:26257/foo> create table test (foo boolean);
CREATE TABLE
root@:26257/foo> CREATE TABLE test (foo BOOL);
CREATE TABLE
root@:26257/foo> CREATE VIEW v AS SELECT foo FROM test;
pq: value type bool cannot be used for table columns
```

This issue isn't present in `master` - so we fixed this bug but apparently didn't backport it to 1.0. @knz @eisenstatdavid do you have a recollection of why/when/how this was fixed?

**Comment by eisenstatdavid** [comment]
Nope :(

**Comment by jordanlewis** [comment]
This is fixed in the latest point release.
