### ISSUE TITLE
Cluster seems unstable

### ISSUE THREAD

**Issue by jrote1** [cockroachdb/cockroach#15838]
Fairly often 2 of my 3 nodes status changes to suspect and then eventually fixes itself. I have attached debug logs hopefully they shed some light. No sql scripts or anything are being run when this occurs
 just the overview page.
[debug.zip](https://github.com/cockroachdb/cockroach/files/989268/debug.zip)

**Comment by petermattis** [comment]
@jrote1 Thanks for the report. Can you expand on what you mean by "suspect"? I'll take a look at the debug logs, but it would be helpful to know what to be looking for or a time frame when you saw the badness.

**Comment by jrote1** [comment]
@petermattis  On the web dashboard you have active nodes on the right and when there is problems number of suspent/dead nodes appear. This is where the nodes appear as suspect and also on the nodes page. Just FYI these logs also have error for #15827

**Comment by petermattis** [comment]
Ah, got it.

There are an unusual number of `slow heartbeat` messages for Node Liveness. These could result in blips on the Node Count graph.

Do you mind sharing the Node Count graph (on the Runtime dashboard)? You'll have to adjust the time frame to 1 day (or maybe 1 week). This will give me a time frame for when these events occurred.

**Comment by petermattis** [comment]
Btw, apologies for not recognizing the "suspect" terminology. I didn't realize that had made it into the UI. In the backend we talk about node liveness.

**Comment by jrote1** [comment]
I have opened up the dashboard to all ips https://jakenetwork.org:8080 so you can get everything you need, let me know when your done and i'll close it thanks.
And is all good no worries

**Comment by jrote1** [comment]
One node actually died today had to restart it, even though it says it was running. Strange :/

**Comment by jrote1** [comment]
This is just a dev playground cluster so if you need access or anything let me know.

**Comment by petermattis** [comment]
Thanks, taking a look.

**Comment by jrote1** [comment]
Just background of environment if you need it, three vms on same hypervisor.  4 cores 2.4GHz, 2GB RAM, 20GB SSD

**Comment by petermattis** [comment]
I looked at the various blips on the Node Count graph and they all corresponded to servers restarting. I wonder if that graph is capturing all of the times the "suspect" node count is non zero. 

I'm done looking at the dashboard for now. Back to looking through the logs.

**Comment by jrote1** [comment]
I don't think the suspects are showing on that graph tbh

**Comment by jrote1** [comment]
![nodesout](https://cloud.githubusercontent.com/assets/4202486/25906281/15b92240-359c-11e7-985e-4ad42866c21c.png)
If you see this screenshot the peaks on the service latency normally happen when a node goes suspect from my observation. so it you remove the spikes that match node count the rest should be suspect ones

**Comment by petermattis** [comment]
I'm not seeing anything in the logs corresponding to the latency blips.

**Comment by jrote1** [comment]
I'll keep an eye on this and if happens again I'll try and provide more info

**Comment by cuongdo** [comment]
@jrote1 have you seen this issue again?

**Comment by cuongdo** [comment]
There have been a lot of fixes since this issue was filed. Please reopen if this reoccurs.
