### ISSUE TITLE
server/cli: ignore the "Available memory" hint from gosigar if it's zero

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#15839]
Found in #15836: on OpenBSD at least gosigar has an implementation from (*Mem).Get() that doesn't fail with an error, but reports 0 available bytes. The computation for CacheSize and SQLMaxMemory derives 0 for both settings as a result.

In general a value of 0 from gosigar should be considered suspicious/invalid and just ignored in favor of the defaults. (perhaps with a warning)

**Comment by tamird** [comment]
It's surprising that gosigar returns zero without an error; perhaps this is just a bug upstream?

**Comment by knz** [comment]
Perhaps -> for sure

**Comment by knz** [comment]
It might be though that the issue is something like OpenBSD denying the syscall silently for a non-privileged process, and the gosigar dev who made the openbsd port having just enough privileges. Or something changed in openbsd between the time that support was developed and now. I'm rather confident gosigar doesn't CI openbsd support.
