### ISSUE TITLE
storage: consistency checker queue buildup

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#15832]
on adriatic, which was freshly wiped and is running a cycle-len 10k kv loadgen:

![image](https://cloud.githubusercontent.com/assets/5076964/25880260/620b107e-3504-11e7-89f8-0ac024a0c8fb.png)

Maybe this is expected, but looks unintuitive to me that replicas would pile up like that.
The cluster looks healthy at first glance.

**Comment by petermattis** [comment]
I think we pace how fast we drain the consistency checker queue. That might be expected. I'm not sure.

**Comment by a-robinson** [comment]
It took a while before the queue started clearing, but it did clear:

<img width="919" alt="screen shot 2017-05-10 at 11 47 45 am" src="https://cloud.githubusercontent.com/assets/7085343/25907812/8275a424-3576-11e7-9621-073c4ce79692.png">

**Comment by tschottdorf** [comment]
Yeah, looks fine.
