### ISSUE TITLE
server: number of file descriptors not always detected on OpenBSD

### ISSUE THREAD

**Issue by mrijkeboer** [cockroachdb/cockroach#15840]
**BUG REPORT**

The number of file descriptors is not always detected on OpenBSD. Due to the fact that the default number of file descriptors on OpenBSD is too low, `cockroach` won't start and fails with the following error:

```
$ cockroach start --host=127.0.0.1 --insecure                                                     
*
* WARNING: running in insecure mode, this is strongly discouraged. See --insecure.
*
*
* ERROR: cockroach server exited with error: failed to create engines: hard open file descriptor limit of 1024 is under the minimum required 1956
* please see https://www.cockroachlabs.com/docs/recommended-production-settings.html for more details
*
Failed running "start"
```

To raise the global number of file descriptors to the recommended value, the `kern.maxfiles` sysctl has to be increased:

```
# echo "sysctl kern.maxfiles=15000" >> /etc/sysctl.conf
```

Besides the global limit, the per user limit must be raised by editing the login class for the user in `/etc/login.conf` and setting `openfiles` to 15000 i.e. `:openfiles=15000:\`.

After rebooting, `cockroach` can now be started with the following command:

```
$ cockroach start --insecure --host=127.0.0.1 --max-sql-memory=512MiB --cache=512MiB
```

This seems to indicate that the detection works, because `cockroach` starts. However, the following warning is still logged (indicating that it doesn't work):

```
W170510 13:21:41.016201 146 server/status/runtime.go:184  [n1] unable to get file descriptor usage (will not try again): not implemented on openbsd
```

Header of most recent log file:

```
$ grep -F '[config]' cockroach-data/logs/cockroach.log
I170510 13:21:30.826910 1 util/log/clog.go:1011  [config] file created at: 2017/05/10 13:21:30
I170510 13:21:30.826910 1 util/log/clog.go:1011  [config] running on machine: crush
I170510 13:21:30.826910 1 util/log/clog.go:1011  [config] binary: CockroachDB CCL 0f59bf400 (openbsd amd64, built 2017/05/06 17:13:15, go1.8.1)
I170510 13:21:30.826910 1 util/log/clog.go:1011  [config] arguments: [cockroach start --insecure --host=127.0.0.1 --logtostderr --max-sql-memory=512MiB --cache=512MiB]
```

Jira issue: CRDB-6364

**Comment by knz** [comment]
Thank you for your issue which is also incidentally a good workaround for OpenBSD users!
We'll have a look. In the meantime thank you for your patience and your help.

**Comment by roysG** [comment]
I can׳t run it on mac, version: macOS sierra

**Comment by tschottdorf** [comment]
@knz is there anything to do here? The two checks are different. At startup, we check the hard file descriptor limit (or rather, RocksDB does, I think).
While the server runs, we try to monitor the file descriptor usage (which is different from checking a limit) and apparently isn't implemented in gosigar.
