### ISSUE TITLE
Document cluster restart procedure

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/cockroach#15846]
https://www.cockroachlabs.com/docs/stop-a-node.html has a documentation on stopping a node at a time.  One can infer stopping each of the nodes individually will stop the cluster; however, there should be a documented way to stop and restart the whole cluster or a portion of the cluster.

**Comment by dianasaur323** [comment]
Adding @jseldess and assigning for 1.1. I think an issue might be out already in the docs repo - I seem to remember seeing something? Might be wrong though.

**Comment by jseldess** [comment]
Thanks, @robert-s-lee and @dianasaur323. There was no existing docs issue for this, so I've just created one: https://github.com/cockroachdb/docs/issues/1398. I think we can close this issue as a duplicate.
