### ISSUE TITLE
log+sql+reporting: enhance the auto reporting of issues

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#15854]
cc @dt 

Background: currently auto error reporting does not include error details, because these can contain strings, table/column names etc which would be a privacy violation.

- [x] gate all non-SQL errors on pgwire to transform them to "internal server error" so the user does not see something they don't understand and for which we can't easily explain in the SQL docs. This is essentially a dup of #5452
  - [x] update the existing code to use pgerrors for all SQL errors, and consider every remaining non-marked error as an internal error.
  - [x] ensure that the details (stack trace, and Cause chain for errors from the errors package) of the real error do get reported to us even if the user doesn't see them.
  - [x] make the "server internal error" message, the one that users see, include an "internal error message code", which would also be put in the log file alongside the details of the error, so that a DBA can troubleshoot an error reported by their users.
  - [x] to properly handle code paths where an error initially annotated with a PG error code is further Wrap()ped during the unwinding (@knz: I surmise there is currently no such code path, but we need to think about that for the future), we need to ensure that the pgwire interface unwraps the errors to fish the pg error code, before deciding whether the error is internal or not. (@dt: in the process of addressing this point, care should be taken to check whether the type system can be leveraged to support this better, AKA "pError version two")

- [x] make it so that panic reports tell us more. Possible strategies
  - [x] replace all uses of `panic(fmt.Sprintf(fmtstring, ...))` by `log.Panic(fmtstring, ...)` which creates an object which saves the format string, so that the format string itself (before we think further about its arguments) get reported. (For reference, the format string provided to `log.Fatal` is already reported, with the rationale that the format string never contains sensitive information.)
  - [x] propose a new interface `log.PanicWithSensitiveAnnotations(...)` and/or an extended version of `errors.Errorf` and `errors.Wrapf` which alongside the format string also gives the user the opportunity to annotate which of the remaining arguments are safe for reporting.  These things would create a struct containing the fully formatted error containing all the parts of the message (this fully formatted error would go to the error file/log), and a formatted error where all the sensitive arguments have been replaced by a default value of their type (or an "_")
  - [x] find/propose a mechanism that replaces/extends the errors package, in particular `errors.Wrap`, so that we can annotate what is sensitive and what isn't in the error details, and use these annotations in the reporting.
- [x] log unimplemented errors during SQL processing
  - [x] in particular those already marked "unimplemented" with a special error case in the grammar -- this needs a mechanism that is not yet implemented. Idea from @dt: no need to report the grammatical context, the line number in sql.y/sql.go is probably enough.
  - [x] extend the existing facility "unimplementedWithIssueError" to report (or possibly collect/aggregate with bucketing, like in the per-stmt stats) the error that's being constructed (there is no situation where this error constructor is called for something that ends up not being an error), then possibly use this facility in the parser (to avoid implementing a separate mechanism)
      - [x] but also those SQL features for which we have a TODO and/or an error message already in the code to inform the user they should not use this construct or suggest an alternative. (Note: chances are we are already getting those through the per-stmt stats reporting, which includes any error after parsing - to be checked)
  - [x] common to the two previous points, we really need a separate bucketing/counting system for errors, where the bucket keys are the error messages and not the queries. We want to know how often each error occurs.
  - [x] this separate bucketing should be used for any error during logical planning, not only unimplemented errors; this information will tell us whether we missed a feature or whether we didn't explain users properly how to use our stuff.

**Comment by dt** [comment]
@knz there's a lot here -- should we pull it into an RFC, or 3 mini-RFCs, to see if others have thoughts or contributions before we go start changing potentially hundreds of callsites?

**Comment by knz** [comment]
work for me

**Comment by jordanlewis** [comment]
@knz this feels basically finished, no?

**Comment by knz** [comment]
OH YEAH. Thank you.
