### ISSUE TITLE
backup: use merkle trees to allow verification of ranges

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#15850]
Current approaches to verifying data during restore involve checking hashes of sstables after fetching them from storage and then some sort of full-table fingerprint of the SQL-read data (e.g what would happen if you piped `select * from tbl` into some hash function).

Another approach might be to use a merkle tree over the hashes of the SQL rows:
The root has could serve much the same purpose as our table fingerprint, but we'd additionally be able to, after fetching a given SSTable and doing the the transformation work required for restore (remapping its keys to the restoring cluster), we could potentially fire up a sql RowReader on that range, compute its partial hash and then verify it belongs to the tree, before linking the prepared file into the rocksdb.

**Comment by a6802739** [comment]
@dt , could I have a try for this?

**Comment by dt** [comment]
@a6802739 We haven't yet figured out if this is something we *want* to do -- currently this issue is about investigating it and figuring out if it makes sense -- i.e. investigating what the benefits would be, sketching out a design, maybe writing some examples. If you're interested in doing that research, @danhhz might be able to point you towards what the interesting questions to answer are, but there isn't currently a well-defined feature to work on here.

**Comment by a6802739** [comment]
@dt, Thank you very much.If you could give me some reference, maybe I could make some investigate first. And I wonder If there is some feature left about `backup and restore`, and which is suitable for me to  start wit?

**Comment by dt** [comment]
@a6802739 For that I'll have to point you towards @danhhz, who is coordinating errors on backup & restore work right now.

**Comment by danhhz** [comment]
@a6802739 I took a look at our open BACKUP/RESTORE work and it looks like https://github.com/cockroachdb/cockroach/issues/14884 would be a good candidate. It also happens that you filed it : - )

**Comment by a6802739** [comment]
@danhhz, I will try to work on it.
