### ISSUE TITLE
How to get Key Prev for Reverse Scan

### ISSUE THREAD

**Issue by thundercw** [cockroachdb/cockroach#1585]
Now I am working on reverse scan.The semantic is similar to scan but with the `RequestHeader.EndKey` included and `RequestHeader.Key` excluded. And the search direction is from the endkey to key.

If the reverse scan is cross multi-ranges,the first range I can get by the `RequestHeader.EndKey`. The problem is that to get the next range need the first range.startkey.prev().prev().  So is there a method to calculate the key' prev?

Note: A second solution to get the next range is using the `RequestHeader.Key` ,but the performance will be poor if the scan cross many ranges.

**Comment by petermattis** [comment]
`Key.Prev()` used to exist but was removed because it wasn't being used. You could certainly revive it. See https://github.com/cockroachdb/cockroach/commit/5ebdffa5c69ec6ce9f7bc0233a6d2f9dcf3ed7fc.

**Comment by tschottdorf** [comment]
is `key.Prev()` really feasible? After all, `key.Next() just appends `\0`, so you can't have `key.Prev().Next()` equal `key` unless `key` happens to end with a null byte.

**Comment by petermattis** [comment]
The previous implementation of `key.Prev()` utilized the max key length:

```
// Returns the previous byte bounded by the max key length.		
// If the last byte is 0, then truncate it. Otherwise decrease the		
// last byte by one and add in "\xff"s for the rest of the key length.
// Examples:		
// 	 "" -> panic		
//   "\x00" -> ""		
//   "\xff00" -> "\xff"		
//   "\xff03" -> "\xff\x02\xff..."		
//   "\xff...\x01" -> "\xff...\x00"		
//   "\xff...\x00" -> "\xff..." (same except the \x00 is removed)		
//   "\xff..." -> "\xff...\xfe"
```

**Comment by tschottdorf** [comment]
oh, I see. Yuck.

**Comment by thundercw** [comment]
@petermattis ,thanks.  Do you still allow us to use `key.prev()` you have removed in the future ? 

After my second thought,to get the next range by first range's `key.prev()` is  not a good method,.Because the rangecache is filled by `scan` . If the ranges to be rev-scaned are not in the cache,  `InternalRangeLookup` will be called when a new range scan begins.

I have got another solution.If the request is rev-scan and the needed ranges are not in the cache will use `InternalRangeLookupRevese` to get .`InternalRangeLookupRevese`will be implimented follow the example of `InternalRangeLookup` but use  `Mvcc.ReverseScan`.

Do you have any better idea?  Look forward to your feedback.

**Comment by petermattis** [comment]
I'm fine with `key.Prev()` being resurrected.

You've got a good point about needing to scan backwards for ranges. Rather than adding a new `InternalRangeLookupReverse` RPC, I suggest you just add a `reverse` field to the existing `InternalRangeLookupRequest`.

This change is going to be somewhat involved. It would be good to break it up into pieces, starting with `MVCCReverseScan` in order to make sure there aren't any gotchas .

**Comment by tamird** [comment]
Discussion moved to #1686.
