### ISSUE TITLE
`make stress STRESSFLAGS="-maxfails 1` leaves stress.test processes around after failure

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#15855]
I've observed this on GCE with multiple types of failure of the test binary - race detected, OOM killer, etc:

``` 
make stressrace PKG=./pkg/sql TESTS=TestMonotonicInserts STRESSFLAGS="-p 16 -maxfails 1 -stderr"
...
--- FAIL: TestMonotonicInserts (26.98s)
    --- FAIL: TestMonotonicInserts/distsql=on (14.28s)
    	testing.go:610: race detected during execution of test
	testing.go:610: race detected during execution of test
FAIL
```

after the failure:
```
andrei@gceworker:~$ ps aux | grep stress
andrei   27596 83.6  3.0 1702308 999132 pts/0  Sl   19:21   2:27 ./stress.test -test.run TestMonotonicInserts -test.timeout 15m
andrei   27624 74.6  2.6 1649700 882820 pts/0  Sl   19:21   2:11 ./stress.test -test.run TestMonotonicInserts -test.timeout 15m
andrei   27676 80.6  2.8 1679652 939184 pts/0  Sl   19:21   2:21 ./stress.test -test.run TestMonotonicInserts -test.timeout 15m
...
```

@benesch I'm assigning to you since you've become my goto guru, but feel free to unassign if you don't think anything of it.

**Comment by vivekmenezes** [comment]
moving to later unless you think it's important fix sooner

**Comment by petermattis** [comment]
This is happening to me too. Would be nice to figure out what changed as I'm pretty sure it didn't use to do this. Likely it is something simple (or stupid).

**Comment by bdarnell** [comment]
Is this a recent change? It looks like `stress` has never made much of an effort to clean up after itself. Once it's reached its exit condition (`-maxfails`), it just exits without killing its child processes. If they hang, they won't exit until they reach their `-test.timeout`. There needs to be some sort of explicit cleanup step before `stress` exits (either a `WaitGroup` to let all pending processes finish, or a loop to kill them all).

**Comment by petermattis** [comment]
@bdarnell Not sure if this is due to a recent change, but I've only noticed the stray `stress.test` processes recently.

**Comment by benesch** [comment]
CC'ing @tamird just in case he has some insight.

**Comment by tamird** [comment]
https://go-review.googlesource.com/c/44790/

**Comment by benesch** [comment]
I wish all my requests for insight were rewarded with full patches. 🎉  Should we merge that into github.com/cockroachdb/stress in the meantime?

Also, at this point I figure I might as well assign this to you, @tamird.

**Comment by andreimatei** [comment]
Respect.

**Comment by tamird** [comment]
Makes sense, thanks!

Since upstream was moved to x/tools in the time since our fork was created,
I'm hopeful that upstream will accept that change (and the others from our
fork, that I'll submit subsequently). If that doesn't happen, I'll port my
patch to our fork. Let's hope they're responsive.
