### ISSUE TITLE
build:  "make check"  should run tests, not "make test"

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#15862]
That's something that has been bugging me ever since I started at CRL.
Every other OSS project under the sun uses "make" for "build the thing" and "make check" for "run the tests".

Except in CockroachDB it's "make test".

A user on Gitter today:
```
(20:04) < brianolson> build from source is failing in a test that expects to be in a git checkout, but is failing because it can't find a .git directory.
(20:04) < brianolson> `    Istyle_test.go:288: err=exit status 128, stderr=fatal: Not a git repository (or any of the parent directories): .git`
```

My answer:

>  CockroachDB's test suite is ran via "make test", not "make check". Sorry for the idiosyncracy.

My suggestion: **align our practices onto what the open source community expects; make users happy.**

- rename the "check" target to "lint" (or whatever)
- rename the "test" target to "check"

**Comment by dt** [comment]
while we're on unexpected `make` behaviors:
`make` = `make build`
`[sudo] make install` actually installs, e.g. to some user-independent, system-wide PATH like /usr/local/bin.

**Comment by knz** [comment]
cc @benesch

**Comment by benesch** [comment]
@dt I fixed that in our source tarballs :)

https://github.com/cockroachdb/homebrew-cockroach/blob/master/Formula/cockroach.rb#L14

**Comment by knz** [comment]
great but I won't mind making everything good in the main repo too.

**Comment by jordanlewis** [comment]
I disagree that `make test` is non-standard. Many projects use this, including Python and MySQL.

**Comment by benesch** [comment]
In that case, we could just rename `check` to `lint` to avoid confusing people.

**Comment by knz** [comment]
ok I could live with having "make check == make test".
I think it's important to *also* provide `make check` for compatibility.

**Comment by benesch** [comment]
@bdarnell @tamird you both have arguments for leaving the `make install` target as a simple wrapper for `go install`, right? I tried to drudge up the previous conversations I feel like we've had but couldn't find them.

**Comment by bdarnell** [comment]
I don't have a strong preference either way for what `make install` does, but I do use it in my current workflow so changing it would be mildly disruptive. I'm OK with changing it for consistency with the source tarball's makefile.
