### ISSUE TITLE
ui: Add option on logs page to return more logs

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#15875]
Our server endpoint that returns node logs exposes a parameter for how many log entries to return, but there appears to be no way to set that from the UI, making it tough to get anything other than each node's first 1000 entries via the UI. While enabling all the knobs from the UI would be nice, at least exposing the number of entries as an option would make it possible to get all the logs via the UI.

I was considering adding a debug page for viewing all the logs since the current experience isn't useful for debugging, but may try adding this option instead.

**Comment by dianasaur323** [comment]
@a-robinson is the logs page actually useful for this? I was looking at it, and it's not like you can grep or filter for anything. What would be your dream logs page?

**Comment by a-robinson** [comment]
I talked with @kuanluo about this last month, but I'm not sure our thoughts got written down anywhere. In short, the logs page is sometimes our only way of accessing logs if a user has just given us an SSH tunnel to their admin UI, so a bare minimum for it to be useful is for it to be capable of at exposing all of a node's logs. Other features on top of that are nice, but aren't necessary (and are probably much less important to our users than other things we could be doing instead).

**Comment by kuanluo** [comment]
To give you more context, @dianasaur323, @a-robinson and @mrtracy and I sat down to discuss the appearance of the logs page, and decided that they need to be more condensed to be useful. 

The issue/notes: https://github.com/cockroachdb/cockroach/issues/15874

This is a different issue, and will definitely be out of 1.1 scope for design/Matt.

**Comment by dianasaur323** [comment]
@a-robinson I think instead of showing all logs, it might be easier to allow easy export into a raw text file. I'm also in love with Heroku's log page:

![image](https://user-images.githubusercontent.com/5768024/27651092-1f57763c-5c05-11e7-8d01-3ac29ffec7e8.png)

**Comment by a-robinson** [comment]
@dianasaur323 Yeah that'd be a good solution. It's what I was otherwise going to do via a debug page, but building it in would be better.
