### ISSUE TITLE
ui: Densify the node logs page

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#15874]
There's a lot of whitespace on the logs page (`#/cluster/nodes/1/logs`) that makes the log-viewing experience less pleasant than it could be. People looking at logs in the UI are probably pretty accustomed to looking at raw text files, which have very little whitespace, so it shouldn't be too visually shocking to condense the page a bit.

For comparison, opening the raw log file in my browser shows more than 3x as many entries as our UI page. I wouldn't expect the UI to show quite as many, but that's a big difference:

<img width="1387" alt="screen shot 2017-05-11 at 12 29 41 pm" src="https://cloud.githubusercontent.com/assets/7085343/25960727/d5417906-3645-11e7-85f3-45507ea432ab.png">

<img width="1384" alt="screen shot 2017-05-11 at 12 30 36 pm" src="https://cloud.githubusercontent.com/assets/7085343/25960735/d97f8f8a-3645-11e7-9c21-11a5e4f1fb5d.png">

@kuanluo for thoughts

**Comment by kuanluo** [comment]
Thanks for pointing this out, @a-robinson. I didn't think deep at all on this page for 1.0 - we wanted a page that looks "nice" and adheres to the visual pattern for the admin ui, and @mrtracy built it very quickly. 

Now we have time to improve on this, and I have a lot of questions, such as:
- What do you look for when you're on this type of pages?
- How do you find what you're looking for? 
- What do you do before/after you come here? 
etc 

Would be great to chat about this, and see how we can optimize it. Can you take the lead and schedule something on our calendar? Some insights from actual users like you would be awesome .

**Comment by kuanluo** [comment]
@mrtracy @a-robinson 

Meeting notes:
- Not incredibly useful (doesn’t load the entire log)
- Would like more vertical spacing (see more at once) 
- Good things: Columns are easier to scan,  severity column first is useful. 
- Outcome: 
    - Keep message column wider by shrinking the file:name columns, so eyes go in the middle of the page 
    - Decrease font size as well as spacing between rows 

Let's try these immediate improvements, and see how it goes from there. Thanks both!

**Comment by dianasaur323** [comment]
I would actually argue for us not to worry about this in the 1.1. We'll probably change this in our 1.2, and @mrtracy has a bunch of other things to work on before 1.1 anyway. 

Instead, we should get on the same page in regards to what we actually want people to do with the logs page. My proposal is that we revisit the timing of this after we get on the same page in terms of user stories, and use that to guide a more meaningful improvement to this page.
