### ISSUE TITLE
Feature request: configure cluster name to be exposed in the Prometheus metrics (and possibly admin interface)

### ISSUE THREAD

**Issue by JorritSalverda** [cockroachdb/cockroach#15888]
**FEATURE REQUEST**

After setting up CockroachDB in Kubernetes with Prometheus and Grafana I realized that the _cluster label_ used by the dashboards is missing from your Prometheus metrics and actually added in your Prometheus config example. But I already have a more generic Prometheus config that doesn't add the cluster label.

It would be nice to set a **cluster name in CockroachDB** itself and expose it in the Prometheus metrics.

This will help when running multiple CockroachDB clusters in the same Kubernetes cluster without requiring specific Prometheus configuration for each. 

As a side benefit when the CockroachDB cluster itself has a name it can be shown in the admin interface to avoid confusion when dealing with multiple clusters.

**Comment by a-robinson** [comment]
Thanks for the request, @JorritSalverda. How would you envision such a cluster name being specified? Via a command line flag? A [cluster setting](https://www.cockroachlabs.com/docs/cluster-settings.html)?

**Comment by JorritSalverda** [comment]
As it's something I only want to set up once when creating a cluster a _SQL command_ to configure it would actually be quite cumbersome. With all the different tools I'm running in _Kubernetes_ I find configuring things through environment variables the easiest.

However preference would probably differ from person to person and depending on where you run it. An environment variable is fine for a _Kubernetes_ pod, but if you install it on a couple of vms shared with other software you might want to use a config file.

The most elegant en flexible way I've seen it done is how _Grafana_ deals with configuration, see http://docs.grafana.org/installation/configuration/. They use a configuration file, but you can override any item in there with an environment variable. This gives you the ease of starting out with environment variables, but when the number of configuration items continues to grow and grow you can switch to using the file instead. In Kubernetes you could use a _ConfigMap_ for that. Next to the file-based and envvar-based solution Grafana also allows you to use a command line flag. So everyone's happy :)

As for the _Prometheus_ metrics it would be ideal to add the value to all metrics using a label like `cockroachdb_cluster` to make it unique compared to other applications. Instead of depending on `job="cockroach"` in your aggregation rules, alerting rules and Grafana dashboards you could replace it with `cockroachdb_cluster!=""`. This makes it a much more scalable solution in Kubernetes clusters with many applications and perhaps more than one Cockroachdb cluster. It's also independent from how you collected the Prometheus metrics. I for one use something very close to the https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus-kubernetes.yml example for scraping all applications in my Kubernetes cluster, but have never used the job label in any of my queries.

I've also moved the scraping annotations at
https://github.com/cockroachdb/cockroach/blob/master/cloud/kubernetes/cockroachdb-statefulset.yaml#L41-L44 to the StatefulSet metadata at https://github.com/cockroachdb/cockroach/blob/master/cloud/kubernetes/cockroachdb-statefulset.yaml#L77 because it gives met the `kubernetes_pod_name` label which I use in your Grafana dashboards instead of `instance`. With nodes moving around and around the former is actually constant in a _StatefulSet_, whereas _instance_ isn't. Just to make my point that the way of collecting Prometheus metrics shouldn't be a factor in your aggregation and alerting rules, nor the Grafana dashboards.

I'm happy if you manage to implement this label in the Prometheus metrics to do a PR for the Prometheus aggregation and alerting rules and the Grafana dashboards to make it more in line with the above.

**Comment by a-robinson** [comment]
Thanks for the detail, @JorritSalverda. cc @mberhault for thoughts

**Comment by dt** [comment]
re: evn var vs config vs setting:
I assume you want all nodes in the cluster to be using the same value, while an env var or node-specific config file could potentially allow specifying different names on different nodes in the same cluster. Our gossip-shared cluster-wide settings were intended pretty much for exactly this type of use-case. w.r.t to needing to set them via SQL after the cluster is started, I think fixing #15301 when we have an `init` command might help.

**Comment by mberhault** [comment]
I think it's reasonable to have a cluster name in general. It should be set exactly once (like the cluster ID) and known by all.
Exporting it through prometheus is trivial, we already have support for labels attached to various sets of metrics (eg: the store ID). Adding a `cluster=<foo>` to all metrics is easy as well.

**Comment by JorritSalverda** [comment]
Yes, the value should be the same for all nodes in the cluster, so a SQL setting would be fine as long as it's easy to set from for example a Kubernetes manifest. https://github.com/cockroachdb/cockroach/issues/15301 seems to
