### ISSUE TITLE
Windows Build not starting

### ISSUE THREAD

**Issue by streppelchen** [cockroachdb/cockroach#15887]
I'm trying to run the windows build, but it immediately crashes with the error "procedure not found"
`PS E:\cockroachdb1-0-0\cockroach-v1.0-rc.2.windows-6.2-amd64> .\cockroach.exe start --insecure
*
* WARNING: running in insecure mode, this is strongly discouraged. See --insecure.
*
*
* ERROR: a panic has occurred!
*
Failed to find GetSystemTimePreciseAsFileTime procedure in kernel32.dll: Die angegebene Prozedur wurde nicht gefunden.

goroutine 51 [running]:
runtime/debug.Stack(0x5889438, 0xc0421d0600, 0x132c000)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x80
github.com/cockroachdb/cockroach/pkg/util/log.ReportPanic(0x5889438, 0xc0421d0600, 0x137fb80, 0xc0423de6c0, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:89 +0x2b6
github.com/cockroachdb/cockroach/pkg/util/log.RecoverAndReportPanic(0x5889438, 0xc0421d0600)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:57 +0x84
panic(0x137fb80, 0xc0423de6c0)
        /usr/local/go/src/runtime/panic.go:489 +0x2dd
github.com/cockroachdb/cockroach/vendor/golang.org/x/sys/windows.(*LazyProc).mustFind(0xc04237f530)
        /go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sys/windows/dll_windows.go:287 +0x5f
github.com/cockroachdb/cockroach/vendor/golang.org/x/sys/windows.(*LazyProc).Addr(0xc04237f530, 0x0)
        /go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sys/windows/dll_windows.go:294 +0x32
github.com/cockroachdb/cockroach/vendor/golang.org/x/sys/windows.GetSystemTimePreciseAsFileTime(0xc0427016b8)
        /go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sys/windows/zsyscall_windows.go:825 +0x34
github.com/cockroachdb/cockroach/pkg/util/timeutil.now(0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/timeutil/now_windows.go:33 +0x3f
github.com/cockroachdb/cockroach/pkg/util/timeutil.Now(0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/timeutil/time.go:43 +0x30
github.com/cockroachdb/cockroach/pkg/util/metric.newSlidingHistogram(0xdf8475800, 0x2540be400, 0x1, 0x50)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/metric/sliding_histogram.go:43 +0x42
github.com/cockroachdb/cockroach/pkg/util/metric.NewHistogram(0x154e5de, 0x12, 0x15893bd, 0x35, 0x0, 0x0, 0x0, 0xdf84758
00, 0x2540be400, 0x1, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/metric/metric.go:174 +0x53
github.com/cockroachdb/cockroach/pkg/util/metric.NewLatency(0x154e5de, 0x12, 0x15893bd, 0x35, 0x0, 0x0, 0x0, 0xdf8475800
, 0x1264f10)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/metric/metric.go:194 +0x74
github.com/cockroachdb/cockroach/pkg/rpc.newRemoteClockMonitor(0xc04200cb80, 0x6fc23ac00, 0xdf8475800, 0xc04200cbc0)
        /go/src/github.com/cockroachdb/cockroach/pkg/rpc/clock_offset.go:94 +0x3d4
github.com/cockroachdb/cockroach/pkg/rpc.NewContext(0x2220680, 0x27bd388, 0x0, 0xc042172370, 0x5889438, 0xc0423de5d0, 0x
c0420d02d0, 0xc04200cb80, 0xc0426d25a0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:170 +0x18f
github.com/cockroachdb/cockroach/pkg/server.NewServer(0xc0420d02d0, 0x0, 0x0, 0xc042224dc0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0
, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:165 +0x474
github.com/cockroachdb/cockroach/pkg/cli.runStart.func1.1(0x5889438, 0xc0421d0600, 0xc042004238, 0xc0426d25a0, 0xc042182
4c0, 0x125e9ab, 0xc042033fd0)
        /go/src/github.com/cockroachdb/cockroach/pkg/cli/start.go:344 +0x15e
github.com/cockroachdb/cockroach/pkg/cli.runStart.func1(0x5889438, 0xc0421d0600, 0x222c7a0, 0x27bd388, 0xc042004238, 0xc
0426d25a0, 0xc0421824c0, 0xc042684a80)
        /go/src/github.com/cockroachdb/cockroach/pkg/cli/start.go:414 +0xe6
created by github.com/cockroachdb/cockroach/pkg/cli.runStart
        /go/src/github.com/cockroachdb/cockroach/pkg/cli/start.go:417 +0x3a2

PS E:\cockroachdb1-0-0\cockroach-v1.0-rc.2.windows-6.2-amd64>
`

i'm running the powershell with admin privileges

**Comment by tamird** [comment]
Looks like you're running on a Windows version lower than 8. At this time,
native CockroachDB-on-Windows requires Windows 8 or higher.

Our docs already mention this, but we should improve the error messaging
when running on an unsupported Windows version.

**Comment by streppelchen** [comment]
You are right, that's the one thing I did not read.
Make the text box mentioning this red on the download page, maybe that will help.
Sorry!

**Comment by tamird** [comment]
cc @jseldess ^

**Comment by jseldess** [comment]
Just opened a PR to address this. Thanks for the suggestion, @streppelchen!

**Comment by tamird** [comment]
I'm also going to repurpose this issue to track adding a better error message.

**Comment by xenu256** [comment]
Same for Windows 8.1:

```text
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	cockroach.exe
  Application Version:	0.0.0.0
  Application Timestamp:	590c8560
  Fault Module Name:	cockroach.exe
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	590c8560
  Exception Code:	c000001d
  Exception Offset:	0000000001d15492
  OS Version:	6.3.9600.2.0.0.256.48
  Locale ID:	1033
  Additional Information 1:	2b90
  Additional Information 2:	2b907fb1c8317a69114a8f4081635399
  Additional Information 3:	97e8
  Additional Information 4:	97e8c0fce6acd672b59395d95cc4a831
```

**Comment by TomHunt3r** [comment]
is there a way run < Window 8 version

**Comment by tamird** [comment]
I don't believe so.

**Comment by turbo** [comment]
Is it only this single API call that's blocking <Windows 8 compatibility? If so, it might be a good idea to implement some kind of fallback, if something of equal precision could be accessed.

**Comment by tamird** [comment]
We're open to suggestions. Nothing of equal precision is known to us.
