### ISSUE TITLE
Unwanted folders in my $Home folder

### ISSUE THREAD

**Issue by atilkan** [cockroachdb/cockroach#15890]
This is a problem if every node comes to my home folder. This is dirty.
![screen shot 2017-05-12 at 14 57 44](https://cloud.githubusercontent.com/assets/1254613/25998304/0ac3ffde-3729-11e7-9152-2eda08e81369.png)

**Comment by mberhault** [comment]
`cockroach-data` is the default `--store` directory.
Did you start other cockroach nodes with `--store=node2` and `--store=node3`? Not sure about `p` and `w` though. Do the contents look like cockroach data/logs?

**Comment by atilkan** [comment]
@mberhault I started nodes like 
`cockroach start --insecure \
--store=node2 \
--host=localhost \
--port=26258 \
--http-port=8081 \
--join=localhost:26257 \
--background`

**p** and **w** paths are similar, logs of RockDB. I am playing with DBs but did not install RockDB. They appeared after cockroach experiments. 
![screen shot 2017-05-12 at 16 43 36](https://cloud.githubusercontent.com/assets/1254613/26000420/9117aa4c-3731-11e7-9e55-c4f76e01dda2.png)

**Comment by mberhault** [comment]
if at any point you specified `--store=p` and `--store=w`, then those would be created by cockroach. If not, there may be something else going on.

**Comment by atilkan** [comment]
It may be from dgraph or cayley. I guess they use it some part of their system. 
I have no idea about this.
But anyways, nodes on my home folder are disturbing me. Do you have documentation about it. So i can specify the location until you agree that is not the best place.

**Comment by mberhault** [comment]
The `--store` flag is a path, see https://www.cockroachlabs.com/docs/start-a-node.html#store

**Comment by bdarnell** [comment]
The directories created by cockroach will contain a file named `COCKROACH_VERSION`. If the `p` and `w` directories don't have them then they must have been created by something else.

`cockroach-data`, `node1`, and `node2` are the directories used by our [local cluster tutorial](https://www.cockroachlabs.com/docs/start-a-local-cluster.html). They're not always created in your home directory; they use your current directory when you run the commands.

**Comment by atilkan** [comment]
@bdarnell @mberhault Thanks. I just discovered the forum, i will ask there more.
