### ISSUE TITLE
sql: support an (empty) information_schema.sequences

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#15921]
For compatibility with clients that enquire that virtual table, e.g. here: https://github.com/radutopala/cockroach-app/issues/2

(The virtual table can stay empty as long as we don't support sequences)

This is separate/complementary to #5811.

**Comment by cuongdo** [comment]
@knz please triage

**Comment by knz** [comment]
keeping it, I have a pr open already :)
