### ISSUE TITLE
Crash after hard shutdown on OSX

### ISSUE THREAD

**Issue by awbacker** [cockroachdb/cockroach#15922]
I was running a 3 node cluster locally as per the "getting started" docs and my Macbook crashed.  After restart I am unable to bring up the master node (or any node) locally, and it just hangs after giving the warning about `--insecure` being used.

* No entries get added to the log file
* Only command run was `create database`
* I had a similar issue when using a single node, but didn't pay attention then.  deleted `cockroach-data` and it was ok.  In those cases I also had added no data or made any changes.

```
Build Tag:    v1.0
Build Time:   2017/05/10 13:17:56
Distribution: CCL
Platform:     darwin amd64
Go Version:   go1.8.1
C Compiler:   4.2.1 Compatible Clang 3.8.0 (tags/RELEASE_380/final)
Build SHA-1:  43aa1ed04cd817348921ac27e11e25725f634aa6
Build Type:   release
```

Logfiles files are all **identical** except for the start command
```
$ grep -F '[config]' [cockroach-data|node2|node2]/logs/cockroach.log
I170515 22:33:56.978031 1 util/log/clog.go:1011  [config] file created at: 2017/05/15 22:33:56
I170515 22:33:56.978031 1 util/log/clog.go:1011  [config] running on machine: throne
I170515 22:33:56.978031 1 util/log/clog.go:1011  [config] binary: CockroachDB CCL v1.0 (darwin amd64, built 2017/05/10 13:17:56, go1.8.1)
I170515 22:33:56.978031 1 util/log/clog.go:1011  [config] arguments: [./cockroach start --insecure --host=localhost]
```

**Comment by tamird** [comment]
Thanks for the report! Could you share some details with us:

- the precise commands you used to run each node
- some detail about your machine: OS version, hardware SKU (i.e. from the "about this mac" screen; mine reads `MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports)`, for instance).

Also, what was the "similar issue"? I guess your machine didn't crash. Did you observe a stall?

**Comment by a-robinson** [comment]
This looks like the same issue as #15889 -- namely that a single node can't be successfully brought up by itself it the cluster has previously been larger than one node, because that one node doesn't have a quorum by itself. Try starting another node at the same time in a second terminal and it should work.

We're tracking improvements to the documentation around this in https://github.com/cockroachdb/docs/issues/1403 and to the runtime experience in https://github.com/cockroachdb/cockroach/issues/15894. Let me know if trying to start two nodes at once doesn't fix things for you!

**Comment by awbacker** [comment]
@a-robinson Thanks, I will close this issue.  With 2 nodes it came up after a 10 second delay or so.  I find it odd that there is no logging when this is going on, to terminal or cockroach.log.  With something there I wouldn't have filed the issue at all.  I start all 3 from a shell script, so it would just hang on the first node and never BG itself and get to the other nodes.  Maybe a `--cluster` flag to signal intent to create one?

@tamird MacBook6,2 os-x 10.12.4.  
@tamird The "similar issue" was a hang during startup, same as here, in single node mode.  Maybe I hard-killed the proccess?  It was right at the beginning, so I'm not sure what I did and I immediately wiped the data dir and started again, sorry :(
