### ISSUE TITLE
Build fails from tarball

### ISSUE THREAD

**Issue by dotwaffle** [cockroachdb/cockroach#15923]
The website says building from source uses a tarball: https://binaries.cockroachdb.com/cockroach-latest.src.tgz

This was freshly downloaded as of 15:43 UTC on 2017-05-15.

As far as I can tell, the build actually succeeds, but the testing step fails because it's expecting git repositories as part of the TestStyle test-suite.
[log.txt](https://github.com/cockroachdb/cockroach/files/1001595/log.txt)

**Comment by tamird** [comment]
@dotwaffle looks like you ran `make all`, which includes the linter. Could you run a narrower target, like `make install`?

Also, do the docs mention `make all`? cc @benesch @jseldess

**Comment by benesch** [comment]
The docs mention a bare `make`, which implies `make all`. Womp womp. #15909 will fix this, but we could update the docs in the meantime.

**Comment by benesch** [comment]
And yup, @dotwaffle, `make build` and/or `make install` will skip running the broken linters. You might prefer `make build` since it won't require `sudo` if `/usr/local` is owned by root.

**Comment by dotwaffle** [comment]
Whoops! Sorry, muscle memory ;)

**Comment by benesch** [comment]
No problem! We're doing our best to bring our build system in line with your muscle memory. I've opened https://github.com/cockroachdb/docs/pull/1413 to fix the broken docs. V1.1 will eventually feature a `make` command that works like you expect.

**Comment by benesch** [comment]
This is fixed in two ways: in 1.1, `make` no longer implies `make build test lint`, and, in 1.0 and 1.1, docs suggest using `make build` instead of the bare `make`. Closing!
