### ISSUE TITLE
distsql: support tuples in streams

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#15938]
We currently don't support tuples in DistSQL streams. We don't have a `ColumnType_Kind` for it and no way to encode it over the wire. This makes certain queries non-distributed.

For example: `SELECT (k, v) FROM t`.

Another example is more subtle: `SELECT k, v FROM t ORDER BY (k, v)`. Here the extra parens cause a tuple to be created for each row and used as the sort key. So this query is not supported by DistSQL, as opposed to the equivalent `SELECT k, v FROM t ORDER BY k, v`. Granted, this case should be probably converted to latter version before distsql planning.

CC @asubiotto

**Comment by arjunravinarayan** [comment]
Supporting tuples in DistSQL requires two things:
1. propagating the appropriate type information via `ColumnType`. This was fairly straightforward.
2. encoding/decoding the tuple types over the wire. for now I'm working on adding only a value encoding, so it would not be order preserving. This is a little more work, but still seems straightforward.

The other part mentioned - converting tuplified queries into untuplified versions - are not strictly necessary for supporting tuples in distsql, so should probably be tracked by the optimizer team.

**Comment by RaduBerinde** [comment]
Great! A value encoding is functionally sufficient.

The other part wasn't meant to be a task for this issue, it was just an example where tuples can pop up unexpectedly. I am filing an issue for the optimizer.

**Comment by arjunravinarayan** [comment]
Glad to see you think a value encoding is sufficient. I was afraid there might be an edge case where it wouldn't suffice. I think optimization wise pushing tuple construction as far down towards the end of the query would probably be sufficient - the value encoding precludes execution optimizations that require orderings between values, but that's about it... Anything that requires a tuple can be accomplished by keeping multiple columns as far as I can see, and constructing the tuple at the very end.

**Comment by RaduBerinde** [comment]
> the value encoding precludes execution optimizations that require orderings between values, but that's about it

Exactly, if we need ordering, we will just decode and compare. Unclear how important this optimization is anyway.
