### ISSUE TITLE
ts: Make timeseries truncation threshold configurable

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#15931]
Our timeseries data can take up a considerable amount of space in its default configuration, which samples metrics every 10 seconds and stores them for 30 days. We let users configure the sampling interval, but not the storage duration. We may want to let them configure both, although doing so could have consequences for the admin UI, which currently assumes that metrics are valid for a month.

Asked about in https://forum.cockroachlabs.com/t/live-bytes-steadily-increasing/629/4

Also, @mrtracy, is there an issue tracking downsampling of old metrics [as proposed in the RFC](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/time_series_culling.md)? All I see is #5910 about truncating them, which has been fixed.

**Comment by dianasaur323** [comment]
This feature is also mentioned here: https://github.com/cockroachdb/cockroach/issues/16016

**Comment by dianasaur323** [comment]
**PM Acceptance Testing**
- [ ] Set time series setting to something crazy short to see what happens in the admin UI
