### ISSUE TITLE
sql: make scanNode use meaningful limit values

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#15947]
Currently the code uses the value 0 to mean "no limit".
As suggested in https://github.com/cockroachdb/cockroach/pull/15925#issuecomment-301548114 this could be altered to use MaxInt64 instead, but then the `limitHints()` method needs to be modified, and the rest of the code checked for uses of uninitialized scanNode instances.

**Comment by andreimatei** [comment]
Are you sure `MaxInt64` is better than 0? To me, 0 is a more natural sentinel. When I start seeing `MaxInt64` in plans and such, it looks like garbled text and I wonder where it came from. Using 0, you have to check for it everywhere, of course, but with `MaxInt64` you sometimes need to worry about overflow, and if you forget to do that, you can get in big but subtle trouble. And you also need to worry about initialization. DistSQL also uses 0 in its processors for `Limit` and `LimitHint`.

**Comment by knz** [comment]
@petermattis care to chime in and answer Andrei? You proposed this change in the first place.

@andreimatei it goes without saying that if we perform this change the distsql code needs to be updated as well.

**Comment by petermattis** [comment]
@andreimatei Yes, it is nice to have 0 mean something useful, but doing so can cause awkwardness in interpreting the limit. The purpose of this change was to transform:

```
	for n.hardLimit == 0 || n.rowIndex < n.hardLimit {
```

into:

```
	for n.rowIndex < n.hardLimit {
```

**Comment by andreimatei** [comment]
I saw that line of code that prompted this. I was saying that I don't think it's so bad :). If it's burdensome in the context of a particular function, perhaps we can turn the 0 to MaxInt64 just in the context of that particular function.

**Comment by cuongdo** [comment]
@knz please triage

**Comment by jordanlewis** [comment]
I'm going to close this as stale - it's just a refactoring project. I think the ship has sailed. Feel free to re-open if you care (and have a plan to deal with it).
