### ISSUE TITLE
sql: retire EXPLAIN(DEBUG), replace by tracing

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#15948]
- this would greatly reduce the complexity of the query execution code
- this would enable adding the missing test to #15925 
- would simplify the resolution of #9563

**Comment by RaduBerinde** [comment]
CC @andreimatei

This could be done by emitting the explainDebug information as special trace events, and run the same code for `DEBUG (TRACE)` but only show those events.

**Comment by andreimatei** [comment]
Or we could just forget about it and see if the current `EXPLAIN(TRACE)` is good enough
