### ISSUE TITLE
storage: Refactor raft.Storage methods

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#15957]
`storage.Replica` currently implements the `etcd/raft.Storage` interface directly, which exposes methods with externally-imposed names. Some of these methods require locks to be held (e.g. `FirstIndex`, but they cannot follow our usual convention of a `Locked` suffix (they also have some very generic-sounding names like `Entries`). We should define these methods on a new `replicaRaftStorage` type alias instead of `*Replica` itself so they are not used with misleading names elsewhere in the storage package. Any methods that need to be accessible within package `storage` can be defined on `*Replica` with a name like `raftFirstIndexLocked`. 

See https://github.com/cockroachdb/cockroach/pull/15935#issuecomment-301841676

**Comment by a6802739** [comment]
I could have a see on this part.

**Comment by bdarnell** [comment]
Go ahead @a6802739
