### ISSUE TITLE
sql: name resolution issues in views

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#15951]
There are some sneaky case normalization issues in views. I'm not exactly sure what the cause is, but observe the following set of interactions, all of which should work without error:

```
root@:26257/test> CREATE TABLE test (a int, b int);
CREATE TABLE
root@:26257/test> CREATE VIEW Caps AS SELECT a, b FROM test;
CREATE VIEW
root@:26257/test> SELECT sum(Caps.a) FROM Caps GROUP BY b;
pq: source name "caps" not found in FROM clause
root@:26257/test> SELECT sum("Caps".a) FROM "Caps" GROUP BY b;
pq: source name "caps" not found in FROM clause
root@:26257/test> CREATE VIEW "QuotedCaps" AS SELECT a, b FROM test;
CREATE VIEW
root@:26257/test> SELECT sum("QuotedCaps".a) FROM "QuotedCaps" GROUP BY b;
pq: source name "quotedcaps" not found in FROM clause
```

Found while investigating #15827.

Assigning to @eisenstatdavid for now since he recently worked on case folding.

**Comment by jordanlewis** [comment]
Note that this doesn't happen with tables:

```
root@:26257/test> CREATE TABLE "QuotedCapsTable" (a int, b int);
CREATE TABLE
root@:26257/test> SELECT sum("QuotedCapsTable".a) FROM "QuotedCapsTable" GROUP BY b;
+--------------------------+
| sum("QuotedCapsTable".a) |
+--------------------------+
+--------------------------+
(0 rows)
```

and that it doesn't happen if you don't specify the table name explicitly in the aggregate:

```
root@:26257/test> SELECT sum(a) FROM "QuotedCaps" GROUP BY b;
+--------+
| sum(a) |
+--------+
+--------+
(0 rows)
```

**Comment by jordanlewis** [comment]
It would be great to get a fix for this in quickly, as I think it prevents people from using the database if they have views with capital letters in their names. I haven't found a workaround.

**Comment by eisenstatdavid** [comment]
Still digging, but this isn't a case issue. Running
```
CREATE TABLE test (a int, b int);
CREATE VIEW caps AS SELECT a, b FROM test;
SELECT sum (caps. a) FROM caps GROUP BY b;
```
gives an error at b7423db2fd90d308b24017fb373d1274ec716393.

**Comment by jordanlewis** [comment]
You're right. I got badly confirmation biased. Feel free to reassign, and sorry to cast false blame on the case normalization!

**Comment by eisenstatdavid** [comment]
The problem seems to be that we replace the view by its subquery but never propagate the name of the view. I'm working on a fix.
