### ISSUE TITLE
tools: handle unstable releases

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#15977]
We'll start cutting weekly releases from `master` again soon, probably labelling those `1.1-alpha-<date>`.
We need to make sure this doesn't interfere with `1.0.x` point releases.

***updated***

We've decided to go with the following release types:
* `stable`: `X.Y.Z` releases
* `unstable`: everything else: `alpha`, `beta`, and `rc`

And the following impact on announcements/builds:
* tarballs: keep the `latest` tarballs for `stable`, but don't generate one for `unstable`
* new version notifications: already looks for `stable` versions (without a `-...`)
* docker images: don't push one for `unstable`
* homebrew: don't push one for `unstable`
* docs: default download page should be for stable. We'll need to split `unstable` release notes.

**Comment by mberhault** [comment]
deadline is "whenever we start cutting weekly unstable releases again", probably about two weeks.

**Comment by mberhault** [comment]
@benesch has been poking at tarballs.
@dt I believe is playing with the registration cluster
@bdarnell for input

**Comment by benesch** [comment]
Are `beta` and `rc` mutually exclusive? I figure we can call them alphas till Aug 1 (feature development), betas till Sep 1 (ruggedization and polish only), and RCs until the release on Oct 1 (basically no changes but tiny bugfixes).

**Comment by mberhault** [comment]
For the purposes of tracking, I think `unstable` and `stable` might be enough. If we want more granularity, `rc` can probably fall into `beta`. I mostly want to avoid people thinking (through naming or notification) that there's a new stable release when it's just a new unstable one.

**Comment by benesch** [comment]
Oh! I understand now. "Tracking" as in release channels. Yes, I agree: unstable and stable seem sufficient.

**Comment by petermattis** [comment]
`{alpha,beta,rc}` should all be `unstable`. `stable` should be reserved for the truly stable releases.

**Comment by mberhault** [comment]
Updated issue message with decisions.

**Comment by bdarnell** [comment]
I agree with the stable/unstable tracks, but we should remember that in the long run it will get a bit more complicated as we have releases that are "stable" but not "latest": we may release a bugfix 1.0.5 after 1.1 is already out. Latest should effectively mean "highest stable version number", not "most recently built".

**Comment by benesch** [comment]
Doing that right, I think, requires an S3 ListBucket request, followed by version parsing and sorting.

**Comment by mberhault** [comment]
Yeah, I think the `latest` pointer may be best managed elsewhere. Version name is not enough.
We could do it through TC builds, but having a `stable` and `latest stable` feels odd. This feels like a point where latest may best be triggered manually.

**Comment by benesch** [comment]
Floating an alternative proposal: we could do the redirect on the registration server. We already teach it about each version, and it already maintains a sorted list of all versions...

Downside, of course, is that the link breaks whenever the reg server crashes.

**Comment by mberhault** [comment]
Yeah, I'm hesitant to add anything in the path of serving the binaries.
I think a manual `tag-as-latest` which would just create the links would be ok. Not sure what would work for homebrew/docker though.

**Comment by bdarnell** [comment]
We've been making 1.1 alphas for a while now; anything left to do with this issue?

**Comment by mberhault** [comment]
nope, I think we're all set. Closing.
