### ISSUE TITLE
release: 1.0.1

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#15978]
The current SHA is 50fd18dcf8da75a0f4980344a885fe6105d0cf23
Deployment status:
* continuous deployment of all SHAs to `cobalt`.
* 50fd18dcf8da75a0f4980344a885fe6105d0cf23 deployed to `blue`, `cerulean`, `indigo`, `omega`

[Release process checklist](https://github.com/cockroachdb/cockroach/wiki/Release-Process)
- [x] Check and verify cluster status
- [x] Tag release and push tag
- [x] [Trigger release build](https://teamcity.cockroachdb.com/viewType.html?buildTypeId=Cockroach_MergeToMaster)
- [x] Check and verify binaries
- [x] Update the [Homebrew tap](/cockroachdb/homebrew-cockroach)
- [ ] Update the image tag in our Kubernetes configurations
- [x] Update docs
- [x] Announce version to the registration cluster (see internal production instructions)
- [x] External communications for release

**Comment by petermattis** [comment]
Need to cherry-pick https://github.com/cockroachdb/cockroach/pull/15968 as well.

**Comment by mberhault** [comment]
Yup. Any merged PRs with the `1.0.1` label will be cherry-picked.

**Comment by jseldess** [comment]
@mberhault, do we still need to handle homebrew and k8 configurations, or can we just check those boxes above?

**Comment by mberhault** [comment]
We're waiting for the homebrew change to be merged (we're in the code package now, so we need to wait for them to merge it). See: https://github.com/Homebrew/homebrew-core/pull/13932
Kubernetes is also partially external (https://github.com/kubernetes/kubernetes/)

**Comment by mberhault** [comment]
But we shouldn't wait on those, they should probably be at the end.

**Comment by a-robinson** [comment]
Yeah, there's no need to wait on them.

**Comment by jseldess** [comment]
Everything but homebrew and k8 are done now, @mberhault.
