### ISSUE TITLE
stability: Crashes due to "on-disk and in-memory state diverged"

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#15980]
We've seen a few of these pop up in sentry, and now have had a test fail due to it (#15975). It probably isn't a coincidence that the test that failed is one in which we stop and restart a node. Since we have a test that can apparently repro this, it should be much easier to get to the bottom of.

https://sentry.io/cockroach-labs/cockroachdb/issues/274926461/
https://sentry.io/cockroach-labs/cockroachdb/issues/269875826/
https://sentry.io/cockroach-labs/cockroachdb/issues/272304033/

**Comment by a-robinson** [comment]
Deduping with #15979

**Comment by tschottdorf** [comment]
Ah, nice that these pop up more frequently.
