### ISSUE TITLE
storage: Ensure clusters with a lot of empty ranges get reasonable balance of data across nodes

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#15988]
As [mentioned](https://reviewable.io/reviews/cockroachdb/cockroach/15946#-KkIINVYP_qTd3n3663o:-KkLOYcPyQoDH-0jkNmd:b-g8hfd) in the review of #15946, when tables are deleted they leave behind empty ranges, which we currently never merge or otherwise get rid of. Because we currently don't consider the amount of data in a range when making rebalancing decisions, it's conceivable that in pathological cases we could end up putting 10,000 64MB ranges on one node and 10,000 empty ranges on another, making for a terrible balance of disk usage and request load.

We should investigate how bad this gets in realistic scenarios to decide whether explicit logic around balancing bytes is needed soon.

**Comment by andreimatei** [comment]
Perhaps this is the impetuous we need to make merging actually work? :P
It's been a while since I asked around what the state of merging is. Is it never gonna happen? Perhaps merging of empty ranges (or one empty range with a non-empty one) are somehow easier than the general case?

**Comment by petermattis** [comment]
Merging is still hard (even for empty ranges) because in addition to all of the merge specific logic, we need to tell the rebalancer to co-locate the replicas of the ranges to merge. And I think we have to ensure the leader for the 2 ranges is on the same node. I haven't thought of an easy way to ensure that (yet).

**Comment by bdarnell** [comment]
I don't think we need to co-locate replicas and leadership to merge empty ranges - that's what makes merging empty ranges easier. We just need to freeze the empty RHS to ensure it stays empty, edit the metadata on the LHS to take over the larger key span, then lazily destroy the now-unreachable RHS replicas.
