### ISSUE TITLE
storage: test GC queue in presence of many intents

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#15997]
We have done little testing on this case.

**Comment by cuongdo** [comment]
@tschottdorf should this move to 1.2? or later?

**Comment by tschottdorf** [comment]
1.2 will do for now.

**Comment by tschottdorf** [comment]
I wrote a little tool that fires up a local single node and writes expired txn entries into its liveness range. I haven't tested how the GC queue reacts yet, but the `cockroach debug estimate-gc` output looks promising (this is after running for ~5s)

```
$ ./cockroach debug estimate-gc ./cockroach-data-gcpressurizer/1/ 3
RangeID: 3 [/System/NodeLiveness, /System/NodeLivenessMax):
storage.GCInfo{
    Now:                        hlc.Timestamp{WallTime:1505719085523655593, Logical:0},
    Policy:                     config.GCPolicy{TTLSeconds:86400},
    NumKeysAffected:            0,
    IntentsConsidered:          0,
    IntentTxns:                 0,
    TransactionSpanTotal:       13000,
    TransactionSpanGCAborted:   0,
    TransactionSpanGCCommitted: 0,
    TransactionSpanGCPending:   13000,
    TxnSpanGCThreshold:         hlc.Timestamp{WallTime:1505715485523655593, Logical:0},
    AbortSpanTotal:             1,
    AbortSpanConsidered:        0,
    AbortSpanGCNum:             1,
    PushTxn:                    13000,
    ResolveTotal:               0,
    ResolveSuccess:             0,
    Threshold:                  hlc.Timestamp{WallTime:1505632685523655593, Logical:0},
```

This means that the GC queue will try to push 13k transactions the next time it runs. Each of the transactions holds 100 intents, so after that it will try to resolve 13k*100 = 1.3 million intents.

If a cluster can remain available with this going on on its liveness range, I think we're fairly safe. I'm sure it won't fare too well when I test this tomorrow.

**Comment by tschottdorf** [comment]
cc @nvanbenschoten wrt #18199.

**Comment by tschottdorf** [comment]
Yep, as expected this is pretty effective at overwhelming the GC queue on different levels.

![image](https://user-images.githubusercontent.com/5076964/30549022-a405e502-9c61-11e7-9bd1-5a923b38af28.png)

**Comment by nvanbenschoten** [comment]
Awesome @tschottdorf! Being able to easily create this pathological condition in a cluster is a big first step towards addressing it. I'd be curious to hear your ideas towards improving our ability to perform large-scale garbage collection once we're in this state.

**Comment by tschottdorf** [comment]
@cuongdo I wanted to put this on your radar since it's repeatedly become a problem for users (https://github.com/cockroachdb/cockroach/issues/19216 being the latest two instances). We'll definitely want to make progress here soon.

**Comment by tschottdorf** [comment]
@danhhz you mentioned the other day that you were interested in getting "store directory fixtures" in addition to the backup-based fixtures. This would be a candidate for that. Is there an issue I should link here?

Moving to 2.1 since that's where it will realistically come together. For now, I'm reasonably sure that the badness I was able to create with the experiments above is no more.

**Comment by danhhz** [comment]
We're still figuring out what the tooling around that will look like but the 2tb backup test already uses them https://github.com/cockroachdb/cockroach/blob/6f1ba7656c00e0b8f1ddf1e95ffbfb5a390ca666/pkg/cmd/roachtest/backup.go#L32-L46

**Comment by tschottdorf** [comment]
Great! Optimistically moving this back to 2.0, then.
