### ISSUE TITLE
Feature request: sidecar container to provide tunnel towards cluster

### ISSUE THREAD

**Issue by JorritSalverda** [cockroachdb/cockroach#15994]
**FEATURE REQUEST**

When simplifying setting up security in one of the future releases it could be very useful to look at how Google allows you to securely connect to Cloud SQL via a sidecar container that provides a tunnel between a Kubernetes pod and a Cloud SQL instance. It makes the database available for the other containers in the pod to connect on localhost. The application than doesn't need to worry about encrypted connections towards the cluster, making life much easier.

A similar proxy container could expose a CockroachDB cluster to an application on localhost, whilst encrypting the communication over the network.

See https://cloud.google.com/sql/docs/mysql/connect-container-engine#6_update_your_pod_configuration_file for more detail on the Cloud SQL proxy.

**Comment by knz** [comment]
cc @a-robinson @bdarnell

**Comment by a-robinson** [comment]
Also @mberhault, since this would primarily be useful for secure deployments, and he's working on that in #16385.

I'd be interested to know if any other databases have adopted this model, though. Are there any examples other than hosted DBs like Cloud SQL?

**Comment by knz** [comment]
This is now possible via either the unix socket or TLS-less SQL listeners.
