### ISSUE TITLE
ui: Newlines within log entries don't get rendered on logs page

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#15990]
Easy to reproduce by running with a high verbosity (e.g. `--verbosity=5`) and opening up the logs page (`/#/cluster/nodes/1/logs`):

<img width="1285" alt="screen shot 2017-05-17 at 12 22 46 pm" src="https://cloud.githubusercontent.com/assets/7085343/26164805/d4b6cf1c-3afb-11e7-8294-5c19c66737d2.png">

As first mentioned in https://github.com/cockroachdb/cockroach/issues/15958#issuecomment-302144025

**Comment by dianasaur323** [comment]
I would love to improve the logs page, but unlikely to make it in 1.1
