### ISSUE TITLE
storage: *errors.errorString: replica.go:1351 on-disk and in-memory state diverged:

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#16004]
This happened on a 1.0 binary, so it's neither #15819 nor the more recently #15935.

https://sentry.io/cockroach-labs/cockroachdb/issues/269875826/

```
*errors.errorString: replica.go:1351 on-disk and in-memory state diverged:
%s
  File "github.com/cockroachdb/cockroach/pkg/storage/replica.go", line 1351, in assertStateRLocked
  File "github.com/cockroachdb/cockroach/pkg/storage/replica.go", line 1336, in assertState
  File "github.com/cockroachdb/cockroach/pkg/storage/replica_proposal.go", line 792, in handleEvalResult
  File "github.com/cockroachdb/cockroach/pkg/storage/replica.go", line 3755, in processRaftCommand
  File "github.com/cockroachdb/cockroach/pkg/storage/replica.go", line 2886, in handleRaftReadyRaftMuLocked
...
(5 additional frame(s) were not displayed)

replica.go:1351 on-disk and in-memory state diverged:
%s
```

**Comment by tamird** [comment]
This looks like a sentry misconfiguration. The actual SHA
is 0ba0af9ed345ecd645efb4743b8d3100a2a78955, which is #15819.

On Wed, May 17, 2017 at 4:06 PM, Tobias Schottdorf <notifications@github.com

**Comment by tschottdorf** [comment]
Ah, well spotted. Any idea what the misconfiguration is?

**Comment by petermattis** [comment]
@tamird Can you elaborate on why you think this is a sentry misconfiguration? I'm seeing the `rev` match the `v1.0` SHA. What are you looking at?

**Comment by a-robinson** [comment]
Where are you seeing that? I do see a couple occurrences at that commit, but also one at 43aa1ed04cd817348921ac27e11e25725f634aa6 with release=v1.0

**Comment by tschottdorf** [comment]
![image](https://cloud.githubusercontent.com/assets/5076964/26174229/ab3aa7c8-3b1c-11e7-9313-571191940ea5.png)

on the right hand side, around the middle.

**Comment by tamird** [comment]
@a-robinson but 43aa1ed is not the 1.0 SHA! It's on the release branch, but it's not actually 1.0.

That said, there are some events at the real 1.0 SHA: https://sentry.io/cockroach-labs/cockroachdb/issues/269875826/events/?query=rev%3A%2243aa1ed04cd817348921ac27e11e25725f634aa6%22

**Comment by tamird** [comment]
cc @dt because I don't understand where the release tag is coming from.

**Comment by tschottdorf** [comment]
@tamird I clicked around in your link but all the events that I opened up had the 0ba0af sha as well. Am I missing something?

**Comment by tamird** [comment]
@tschottdorf I think that bar is just showing you the rev with the highest number of occurrences; the actual event's rev is in the middle of the screen in the tags section.

**Comment by a-robinson** [comment]
@tamird if 43aa1ed04cd817348921ac27e11e25725f634aa6 isn't the `REV` value for the 1.0 release, then what is?

@tschottdorf that's funny, because all the ones I'm seeing at that link are at 43aa1ed04cd817348921ac27e11e25725f634aa6.
<img width="1304" alt="screen shot 2017-05-17 at 4 24 15 pm" src="https://cloud.githubusercontent.com/assets/7085343/26174412/4d0cad62-3b1d-11e7-81e2-c063de1f69da.png">

**Comment by petermattis** [comment]
Add for a given instance (i.e. https://sentry.io/cockroach-labs/cockroachdb/issues/269875826/), I think you want to look at the `rev` info in the `Tags` section. Certainly seems to be 43aa1ed04cd817348921ac27e11e25725f634aa6 to me.

**Comment by tamird** [comment]
@a-robinson eh, you're right - I was basing that on the GH UI which showed me the 1.0-release branch but not the tag, for some reason.

**Comment by dt** [comment]
release = buildInfo.Tag, which comes from
```
.buildinfo/tag: | .buildinfo
	@{ git describe --tags --exact-match 2> /dev/null || git rev-parse --short HEAD; } | tr -d \\n > $@
	@git diff-index --quiet HEAD || echo -dirty >> $@
```
 rev = buildInfo.Revision, or `git rev-parse HEAD`

**Comment by tamird** [comment]
Hm, yeah. Seems real.

**Comment by tschottdorf** [comment]
Ah, I looked at the distribution without realizing that's what it was. Ok, seems real.

**Comment by cuongdo** [comment]
removing milestone, as this doesn't seem actionable after chatting with @tschottdorf

**Comment by tschottdorf** [comment]
This is still happening on v1.0.6, with messages such as

```
on-disk and in-memory state diverged: [RaftAppliedIndex: 68 != 69 Lease.Expiration.WallTime: 1506597457245193300 != 1506597461745378100 Lease.DeprecatedStartStasis.WallTime: 1506597457245193300 != 1506597461745378100 Lease.ProposedTS.WallTime: 1506597448245204300 != 1506597452745386300] replica.go:1366

on-disk and in-memory state diverged: [RaftAppliedIndex: 234235 != 234236 LeaseAppliedIndex: 232956 != 232957 TruncatedState.Index: 229979 != 234234 TruncatedState.Term: 2643 != 4547] replica.go:1366


on-disk and in-memory state diverged: [RaftAppliedIndex: 0 != 168 LeaseAppliedIndex: 0 != 139 Lease.Start.WallTime: 0 != 1506432427777071984 Lease.Start.Logical: 0 != 1 Lease.Expiration.WallTime: 0 != 1506432530591537745 Lease.Replica.NodeID: 0 != 1 Lease.Replica.StoreID: 0 != 1 Lease.Replica.ReplicaID: 0 != 1 Lease.DeprecatedStartStasis.WallTime: 0 != 1506432530591537745 Lease.ProposedTS: nil != &hlc.Timestamp{WallTime:1506432521591542099, Logical:0} TruncatedState.Index: 0 != 116 TruncatedState.Term: 0 != 7 Stats.LastUpdateNanos: 0 != 1506432522484024584 Stats.GCBytesAge: 0 != 995935 Stats.LiveBytes: 0 != 901 Stats.LiveCount: 0 != 13 Stats.KeyBytes: 0 != 935 Stats.KeyCount: 0 != 13 Stats.ValBytes: 0 != 2785 Stats.ValCount: 0 != 74 Stats.IntentBytes: 0 != 110 Stats.IntentCount: 0 != 2 Stats.SysBytes: 0 != 1068 Stats.SysCount: 0 != 10] replica.go:1366

on-disk and in-memory state diverged: [RaftAppliedIndex: 0 != 183 LeaseAppliedIndex: 0 != 155 Lease.Start.WallTime: 0 != 1506418620962787293 Lease.Expiration.WallTime: 0 != 1506418629962787293 Lease.Replica.NodeID: 0 != 3 Lease.Replica.StoreID: 0 != 3 Lease.Replica.ReplicaID: 0 != 2 Lease.ProposedTS: nil != &hlc.Timestamp{WallTime:1506418620962790073, Logical:0} TruncatedState.Index: 0 != 115 TruncatedState.Term: 0 != 7 Stats.LastUpdateNanos: 0 != 1506418620436285731 Stats.GCBytesAge: 0 != 799523 Stats.LiveBytes: 0 != 839 Stats.LiveCount: 0 != 13 Stats.KeyBytes: 0 != 995 Stats.KeyCount: 0 != 13 Stats.ValBytes: 0 != 2926 Stats.ValCount: 0 != 79 Stats.IntentBytes: 0 != 51 Stats.IntentCount: 0 != 1 Stats.SysBytes: 0 != 1226 Stats.SysCount: 0 != 13] replica.go:1366

on-disk and in-memory state diverged: [RaftAppliedIndex: 68 != 69 Lease.Expiration.WallTime: 1506007046679528500 != 1506007055678808700 Lease.DeprecatedStartStasis.WallTime: 1506007046679528500 != 1506007055678808700 Lease.ProposedTS.WallTime: 1506007037679539500 != 1506007046678811100] replica.go:1366

```

These look at least like two distinct classes of problems. Perhaps one of them (the ones where the disk-state is empty) is linking two clusters together accidentally, but the other one looks more serious because it's always an off-by-one. I think what's happening here is that we run out of disk space (or some similar i/o error) while committing a Raft batch which right now marks the replica as corrupted, but then allows the assertion to run in a situation in which the in-memory state was updated, but the actual write failed. I'll send a patch to make that case fail differently, in the hope that we won't be seeing any more of the above assertion failure (or if we do, that it's an actual failure and not fallout from a full disk etc).

**Comment by tschottdorf** [comment]
Closing as not actionable, but we've since identified a few issues that could be at fault here, most prominently https://github.com/cockroachdb/cockroach/pull/19448 and https://github.com/cockroachdb/cockroach/pull/19447.
