### ISSUE TITLE
ui: edit time series settings

### ISSUE THREAD

**Issue by ansarizafar** [cockroachdb/cockroach#16016]
Add settings page for database/cluster settings eg:

- Allow setting the interval at which sampling to happen, Currently, it can be set with COCKROACH_METRICS_SAMPLE_INTERVAL environment variable.
- Allow setting the interval at which time series data clears automatically.
- A button to clear time series data that powers all the admin UI's graphs.
- Other settings.

**Comment by a-robinson** [comment]
More than just for timeseries-related settings, letting users modify [all cluster settings](https://www.cockroachlabs.com/docs/cluster-settings.html) through the UI would be useful.

**Comment by bdarnell** [comment]
This would indeed be useful, but it can't be done until we have proper authentication in the UI (#6307)

**Comment by vilterp** [comment]
We now have a page that shows cluster settings. Updating title to reflect the intent to edit time series settings.
