### ISSUE TITLE
sql: support "SET SESSION CHARACTERISTICS AS TRANSACTION READ ONLY"

### ISSUE THREAD

**Issue by reschke** [cockroachdb/cockroach#16033]
PGJDBC maps

  https://docs.oracle.com/javase/7/docs/api/java/sql/Connection.html#setReadOnly(boolean)

to

  SET SESSION CHARACTERISTICS AS TRANSACTION READ ONLY

(for true), which fails with a syntax exception.

(see https://issues.apache.org/jira/browse/OAK-6238 for context)

**Comment by jordanlewis** [comment]
This is more than a syntax thing - we'd need to plumb this status around a lot and return errors on non-read-only operations. This isn't a big deal but it's definitely not getting into 1.1.
