### ISSUE TITLE
sql: JDBC ResultSetMetaData precision incorrect

### ISSUE THREAD

**Issue by reschke** [cockroachdb/cockroach#16032]
For a column created with

  DATA varchar(16384)

the JDBC ResultSetMetaData.getPrecision  (<https://docs.oracle.com/javase/7/docs/api/java/sql/ResultSetMetaData.html#getPrecision(int)>) apparently returns 2GB.

(see also <https://issues.apache.org/jira/browse/OAK-6238>)

**Comment by jordanlewis** [comment]
CockroachDB doesn't currently store the precision/length of `VARCHAR` types, but it seems that `getPrecision` in JDBC is supposed to return the length of the returned value. Is that correct?

What `JDBC` driver are you using? Unless I misunderstand, I don't believe `pgjdbc` supports `getPrecision`: https://github.com/pgjdbc/pgjdbc/blob/8be516d47ece60b7aeba5a9474b5cac1d538a04a/pgjdbc/src/main/java/org/postgresql/jdbc/PgParameterMetaData.java#L55

We don't officially support Java Postgres drivers other than `pgjdbc`, for what it's worth.

**Comment by reschke** [comment]
"but it seems that getPrecision in JDBC is supposed to return the length of the returned value. Is that correct?"

Yes, that's correct.

"What JDBC driver are you using?"

It's PGJDBC, and it works with ProstgreSQL. The code is here: https://github.com/pgjdbc/pgjdbc/blob/8be516d47ece60b7aeba5a9474b5cac1d538a04a/pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSetMetaData.java#L321 (you were looking at a different class)

**Comment by jordanlewis** [comment]
I see - thanks for the report and pointer. Actually it seems that `getPrecision` does in fact get the maximum precision of the column type, and has nothing to do with the returned value. We won't be able to support that for the time being because we don't make a distinction between `VARCHAR` and `STRING` types like I mentioned above.

Based on the remark in the issue you linked, it seems like you're using the precision to determine what kind of data you store in that column. As a workaround, you could try to use a different method to detect that information, such as checking the name of the column?

**Comment by reschke** [comment]
How does the name of the column help?

FWIW, if I wanted to add support for cockroachdb what *would* help would be a reliable way to detect that I'm indeed connecting to cockroachdb, not PostgresSQL. Is there one?

**Comment by dt** [comment]
@reschke to distinguish a cockroachdb server from Postgres, there's a `crdb_version` parameter included in the connection-setup status report, or the sql function `version()` includes "CockroachDB". Does that help?

**Comment by reschke** [comment]
@dt - (1) can I get info from the connection setup in JDBC? (2) will try that...

**Comment by justinj** [comment]
FWIW this issue is related to #15927, if we were to include the length of a `STRING/VARCHAR` field it would be in `atttypmod`.

**Comment by jordanlewis** [comment]
Thanks for the pointer @justinj - makes sense.

To fully solve this issue, we'll need to make sure that the conversion from column type (as represented in `structured.proto`) to datum type preserves the type modifiers, including the precision and length, just as is already done for collated strings and their locales. To do this, we'll need to augment the relevant type structs (including `tFloat`, `tDecimal`, `tString`) with precision and size fields.

**Comment by cuongdo** [comment]
@jordanlewis please triage

**Comment by jordanlewis** [comment]
This isn't making it into 1.1.

**Comment by jordanlewis** [comment]
@justinj can you check to see if this is fixed?

**Comment by justinj** [comment]
Seems not fixed.
