### ISSUE TITLE
sql/pgwire: insufficient error logging

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#16046]
Most error conditions in pgwire are not logged anywhere, making debugging difficult. For instance, 
#16044 was caused by a timestamp parsing error that didn't show up when `--vmodule=executor=2` was enabled, which is the usual way of detecting problems with client statements.

We should add some `--vmodule` guarded logging to `pgwire` to make it easier to debug situations like that.

**Comment by petermattis** [comment]
@jordanlewis you know what is needed/desired here.
