### ISSUE TITLE
distsql: stream rows from the left input rather than reading a whole group in AlgebraicSetOp

### ISSUE THREAD

**Issue by asubiotto** [cockroachdb/cockroach#16064]
We currently fully consume whole groups (defined as the set of rows equal under a set of ordering columns) from both the left and right input when executing `EXCEPT ALL` (output rows from the left side that have no matching row on the right side). I believe it's only necessary to fully consume a group from the right input and stream rows from the left.

**Comment by arjunravinarayan** [comment]
This isn't currently being planned in 1.1, so this performance optimization can wait until we plan set operations. Moving to 1.2

**Comment by jordanlewis** [comment]
This issue is pretty old. Is it subsumed by any of the recent work on algebraic set ops? cc @abhimadan

**Comment by abhimadan** [comment]
I believe so. After #21896, we'll be using the mergeJoiner and hashJoiner for set op queries, so queries without any ordering will fall back to the hash joiner, which has the behaviour @asubiotto described.

**Comment by jordanlewis** [comment]
Great! Please add "Closes #16064" to that pull request so this will automatically close when your pr merges.
