### ISSUE TITLE
wrong logic of interval.Range.Equal method

### ISSUE THREAD

**Issue by yaojingguo** [cockroachdb/cockroach#16079]
The existing Equal method considers Range A and Range B to be equal if
A's Start is equal to B's End and A's End is equal to B's Start. The
correct logic is to consider Range A and Range B to be equal if A's Start
is equal to B's Start and A's End is equal to B's End.

**Comment by bdarnell** [comment]
@dt just noticed this recently too. This method is unused and we should just delete it.

**Comment by a-robinson** [comment]
Looks like this got fixed in #8867
