### ISSUE TITLE
Container crash when inserting a too-large value into a DECIMAL column

### ISSUE THREAD

**Issue by dhannum** [cockroachdb/cockroach#16081]
If you send a very large BigDecimal into an unbounded DECIMAL column, you will crash Cockroach.

If you bound the BigDecimal (e.g. DECIMAL(10,2)) it works fine and correctly rejects the too-large value. If you just make a column of type DECIMAL, the container crashes. The docs imply that precision and scale are optional, but don't list a default value.

When I made this happen by accident, I saw a stacktrace referring to a slice issue. I wanted to paste it here but when I run my test case, the container simply crashes with no stack trace. Still, I can give you my test code

Here are the logs I do have (version and such)

*
* WARNING: running in insecure mode, this is strongly discouraged. See --insecure.
*
CockroachDB node starting at 2017-05-23 13:53:26.517384398 +0000 UTC
build:      CCL v1.0 @ 2017/05/10 13:19:57 (go1.8.1)
admin:      http://advda-roach.docker:8080
sql:        postgresql://root@advda-roach.docker:26257?sslmode=disable
logs:       /cockroach/cockroach-data/logs
store[0]:   path=/cockroach/cockroach-data
status:     initialized new cluster
clusterID:  381f7b33-46a6-4fac-b995-8c2b8d99aa80
nodeID:     1

I've attached a Spock test case that causes the crash.

[bigDecimalTestCase.txt](https://github.com/cockroachdb/cockroach/files/1022383/bigDecimalTestCase.txt)

**Comment by justinj** [comment]
Thanks so much for the report @dhannum! Here's a pure-sql repro of this panic:

```sql
CREATE TABLE a (b DECIMAL);
INSERT INTO a VALUES (142378208485490985369999605144727062141206925976498256305323716858805588894693616552055968571135475510700810219028167653516982373238641332965927953273383572708760984694356069974208844865675206339235758647159337463780100273189720943242182911961627806424621091859596571173867825568394327041453823674373002756096);
SELECT * FROM a;
```
