### ISSUE TITLE
security: take entire chain into account when computing certificate lifetime

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#16095]
After #15027, we have monitoring of CA and node certificates.
For node certificates, we look at the `NotAfter` field inside the certificate itself. If the certificate was signed by a CA that expires sooner, we will not notice.

The following scenario would result in node certs becoming invalid without us sending an alert:
1. have ca certificate/key `ca-1` with expiration date in 5 years
1. create node certificate `node` with expiration date in 10 years
1. create new ca certificate/key `ca-2` with expiration in 10 years

The node will report 10 years for the CA and node certificates. However, the certificate chain for `node` expires when `ca-1` does, after 5 years.

To properly handle this, we need to examine the entire certificate chain and report the earliest expiration date.

**Comment by tschottdorf** [comment]
@mberhault should this be in 2.1 or not?

**Comment by mberhault** [comment]
Probably not. It's only possible with our own CA and then we already have alerts for CA expiration. Not sure it needs to be kept open, there's a TODO in the code already.

**Comment by mberhault** [comment]
This is becoming less and less doable with the new certificate types where we may not even see the CA, but an intermediate one. Each certificate's expiration date is monitored (server/client/ca/ui/client-ca/ui-ca).
