### ISSUE TITLE
security: monitor client certificate expiration

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#16094]
We now have monitoring for CA and node certificates.
However, the complex part of rolling out new certificates is making sure the clients are up to date.

We should be able to extract client certificate information on incoming requests (username and expiration date, perhaps even certificate chain) and compile a list. This can then be exposed through a debug page (similar to `/debug/certificates`) and monitoring.

Jira issue: CRDB-6072

**Comment by tschottdorf** [comment]
@mberhault should this be in 2.1 or not?

**Comment by mberhault** [comment]
I don't think we need to. 1) it can't work for already-expired certificates (which is when people will care about alerts) and 2) anyone using certificates should setup regular rotation with a period much shorter than the client lifetime.
If they're using our certificates, they have 10 years. If not, they're on their own anyway.

**Comment by mberhault** [comment]
@rolandcrosby for triage. I'm not sure this is so useful mainly because client certificates are often outside the operator's control (nothing worse than getting an alert where the only resolution is to ask someone else to please do something).

**Comment by knz** [comment]
cc @jtsiros for tracking
