### ISSUE TITLE
sql: `GRANT on db.*` hangs

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#16106]
In a root sql shell on a server running 1.0, I ran `grant select on registration.* to a_user;`. It's been running for a couple of minutes now without returning. It appears to be locking some of the system tables; `show databases` in another shell also hangs. I'm trying to debug but haven't  found anything yet.

**Comment by bdarnell** [comment]
This appears to have knocked the cluster more or less completely offline. Symptoms include high lock contention on the Replica mutex, and profiling shows a lot of time being spent in the timestamp cache (especially ExpandRequests). I don't know why `GRANT` would do this.

**Comment by bdarnell** [comment]
The node where the query was running eventually ran out of memory and crashed. The logs show a lot of timeseries-related stuff just before the crash: 

```
I170524 20:11:56.732135 74 server/status/runtime.go:225  [n1] runtime stats: 6.9 GiB RSS, 137316 goroutines, 2.0 GiB/283 MiB/6.9 GiB GO alloc/idle/total, 72 MiB/96 MiB CGO all
oc/total, 319.96cgo/sec, 1.34/0.06 %(u/s)time, 0.00 %gc (0x)
W170524 20:11:57.327494 253850299 storage/replica.go:1730  [n1,s1,r2893/3:/System/tsd/cr.store.capacity…] context canceled while in command queue: Scan [/System/tsd/cr.store.c
apacity.available//10s/2017-05-24T19:00:00Z,/System/tsd/cr.store.capacity.available//10s/2017-05-24T21:00:00Z)
W170524 20:12:01.425510 253901076 storage/replica.go:1730  [n1,s1,r2615/1:/System/tsd/cr.store.queue.re…] context canceled while in command queue: Noop, Noop, Noop, Noop, Noop
, Noop, Noop, Noop, Noop, Noop, Noop, Noop, Noop, Noop, Noop, Noop, Noop, Noop, Noop, Noop, ... 374 skipped ..., Noop, Noop, Noop, Noop, Noop
fatal error: runtime: out of memory
```

When the node restarted its memory usage immediately jumped back to a high level (same as what happened when the GRANT statement was issued), so it appears to be resuming whatever badness was occurring before the crash. It may just be catching up on the timeseries backlog (memory appears to be declining now, but was growing before. Maybe it'll recover on its own).

**Comment by bdarnell** [comment]
Restarting all nodes appears to have gotten the cluster working again. Further profiling showed that a lot of the stuff in the timestamp queue was DeleteRange operations, which I think were on the timeseries ranges.

**Comment by cuongdo** [comment]
@bdarnell I'm not sure how we can make progress. Should this be closed until we have a way of reproducing?

**Comment by bdarnell** [comment]
If we've tried running `GRANT` statements on a cluster under load (I never tried after the initial incident) and it hasn't reproduced, then yeah, I guess we should just close this.
