### ISSUE TITLE
sql: panic in EncodeSecondaryIndex on composite values

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#16111]
https://sentry.io/cockroach-labs/cockroachdb/issues/279602612/

```
*errors.errorString: *errors.errorString v3.go:353
  File "github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go", line 353, in func1
  File "github.com/cockroachdb/cockroach/pkg/sql/executor.go", line 499, in func1
  File "github.com/cockroachdb/cockroach/pkg/sql/sqlbase/table.go", line 1296, in EncodeSecondaryIndex
  File "github.com/cockroachdb/cockroach/pkg/sql/sqlbase/table.go", line 1327, in EncodeSecondaryIndexes
  File "github.com/cockroachdb/cockroach/pkg/sql/sqlbase/rowwriter.go", line 87, in encodeSecondaryIndexes
...
(27 additional frame(s) were not displayed)

*errors.errorString v3.go:353
```

The panic is at sqlbase/table.go:1296:

```
    if val == parser.DNull || (col.isComposite && !val.(parser.CompositeDatum).IsComposite()) {
```

the only thing that can panic here is the cast. @eisenstatdavid thoughts?

(@jordanlewis or is this also something related to the recent TC flake?)

**Comment by knz** [comment]
https://sentry.io/cockroach-labs/cockroachdb/issues/279592488/

**Comment by jordanlewis** [comment]
I don't know - it's frustratingly difficult to determine whether any given sentry failure is an "in-the-wild" failure or a "produced by testing your code" failure. The build is v1.0-rc2 FWIW.

**Comment by knz** [comment]
Even testing code should not *panic* here. I think it's a legitimate bug.

**Comment by eisenstatdavid** [comment]
Assuming no corruption, either type checking failed or a non-canonical instance of `NULL` slipped through somehow (`dNull` isn't a `CompositeDatum`). It would be nice to know from what type the conversion failed.

**Comment by cuongdo** [comment]
@knz please triage

**Comment by knz** [comment]
I have scouted the sentry logs and this error has never been reported since then. Either it was fixed or it was in a dev build using modified code. Closing.
