### ISSUE TITLE
build: don't mark non-master builds as "release"

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#16126]
we use the "release" vs "development" distinction of a build to control some runtime behavior, like crash reporting.

CI builds of proposed changes intuitively are "development", but since "release" vs "development" also controls toolchain selection are currently marked as "release", and then behave as such at runtime.

We should figure out how to ensure that only master (or at some point only nightly/snapshot/etc) builds actually get marked as "release".

**Comment by benesch** [comment]
Was this fixed by #16154?

**Comment by tamird** [comment]
I think so
