### ISSUE TITLE
kv: primary key violation when inserting distinct rows (logic_test/distsql_numtables:25 primary key violation)

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#16143]
Discovered in https://github.com/cockroachdb/cockroach/pull/16137 // https://teamcity.cockroachdb.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=257118

```
[TestLogic/5node/distsql_numtables] logic_test.go:1712: 
	testdata/logic_test/distsql_numtables:25: expected success, but found
	pq: duplicate key value (y)=(2000) violates unique constraint "primary"
logic_test.go:1722: 
	testdata/logic_test/distsql_numtables:25: error in statement, skipping to next file
```

**Comment by tschottdorf** [comment]
Also seen around my PRs, for example in https://teamcity.cockroachdb.com/viewLog.html?buildId=257483&buildTypeId=Cockroach_UnitTests

**Comment by RaduBerinde** [comment]
This is the only insertion statement in that table:

`INSERT INTO NumToStr SELECT i, to_english(i) FROM GENERATE_SERIES(1, 100*100) AS g(i)`

In both cases linked, the problem appears at the first range boundary `2000`.

**Comment by RaduBerinde** [comment]
Could not repro (tried locally and in an azworker, with various `-p` values).

In any case, this is a problem in `kv` or below, probably some race or internal retry is causing the duplicate key; updating title.

**Comment by RaduBerinde** [comment]
Tried reproing again locally and on azworker, with various `-p` values. Tried with a tree from mid-June as well. No luck.

**Comment by RaduBerinde** [comment]
I tried making the test a lot "worse" (100 or 500 ranges) and still no luck reproing. Given that the only known instances happened a while back (on the same day), my guess is that it was a temporary regression. I don't have the tree sha for the occurrences to try to repro on that (the logs are gone). I'm closing this issue; if we see this again we can investigate the new run.
