### ISSUE TITLE
sql: GRANT ALL ON database should check for username 

### ISSUE THREAD

**Issue by zopyx** [cockroachdb/cockroach#16169]
GRANT ALL ON database 

does not check for the related user id...so you can GRANT to non existing user ids without error message. An explicit check for the user id would make sense.

GRANT ALL ON database foo TO a2uezwqouezwqiezowqewqee1;
GRANT

GRANT ALL ON database foo TO doesnotexist;
GRANT

**Comment by zopyx** [comment]
Looks as if Cockroachdb will implicitly create user accounts which is either a bug or a weird design decision.

**Comment by jordanlewis** [comment]
Thanks for the report - it does look like `GRANT` on a missing user implicitly creates the user.

**Comment by mberhault** [comment]
Odd, this used to be on purpose.
Before password authentication was added, users using client certificates did not need an entry in the users table.
Now it seems we always check that a user exists, even when using client certs.

Personally, I this we should relax this and let cert-based clients authenticate.
I realize this is different from postgres, but this is a case where I think they got it wrong. If you're able to create a certificate for a user, an extra entry in the table won't do a damn thing security-wise. The only time it would be useful is to revoke access to existing certificates but right now this would require deleting a user which is a bit of a big hammer.

**Comment by mberhault** [comment]
Discussed this a bit offline.
My proposal risks being surprising to a lot of users. Additionally, creating a user entry when creating certificates is pretty low overhead.
Thus, we should require all users to have an entry in the users table. Any operations involving users (for now I think it's just `grant`, `revoke`, and `show grants`) should fail on non-existing users.

Someone from the sql side of things should probably take this, I haven't poked around in this code in ages.

**Comment by mberhault** [comment]
@cdo for assignment.

**Comment by knz** [comment]
This has been addressed in CockroachDB 2.0.
