### ISSUE TITLE
storage: reapply patch for range lease and node liveness durations

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#16164]
https://github.com/cockroachdb/cockroach/pull/15331 was reverted in https://github.com/cockroachdb/cockroach/pull/16148 since it introduced notable flakiness.

We should investigate why that is and reapply the patch.

**Comment by a-robinson** [comment]
Just a reminder that this should happen sooner rather than later given the instability it's likely to cause.

**Comment by spencerkimball** [comment]
I'm not going to have time to do it. Could someone else take it on? I think
it was just one acceptance test failing. We probably should have skipped
the test instead of reverting.

**Comment by bdarnell** [comment]
It caused flakiness in at least two tests: an acceptance test (which has since been deleted), and one regular test (#16073)

In light of the liveness-span GC problem, I'm in no rush to redo this change.

**Comment by a-robinson** [comment]
Closed by #17340
