### ISSUE TITLE
tracing: make COCKROACH_ENABLE_TRACING a cluster setting

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#16165]
Also affects COCKROACH_LIGHTSTEP_TOKEN.

Since tracing is disabled by default, it can only be fully enabled through a rolling cluster restart. Situations are popping up in which it would be advantageous to change these settings on-the-fly, mostly to get insight into net/trace, but it also seems to make sense to be able to reconfigure the trace collector address without incurring restarts.

I think we haven't done that so far because it's a bit awkward to plumb and it takes some thinking about how to handle traces that are active while the underlying tracer gets reconfigured.

It would be useful though, and now that we have our own tracer, perhaps it's more straightforward.

@RaduBerinde, how hard do you think this would be?

**Comment by RaduBerinde** [comment]
I think this is doable with the new implementation. Child spans could inherit the configuration from the parent, and new root spans would get the updated configuration.

**Comment by RaduBerinde** [comment]
I think we should do this in two stages - first just make the `ENABLE_TRACING` option a cluster setting and support turning it on and off.

Then we can work on doing the same for the lightstep address. If we want to do that with minimal overhead, having infrastructure for callbacks for cluster settings would help.
