### ISSUE TITLE
sql: `CREATE TABLE; CREATE INDEX; ALTER TABLE` in same txn

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#16182]
Discovered in while working on #16175:

The ActiveRecord example app's creation migration looks like this (trimmed):
```
    ....
    create_table :orders do |t|
      t.decimal :subtotal, precision: 18, scale: 2, null: false
      t.belongs_to :customer, index: true, null: false
    end
    add_foreign_key :orders, :customers
```
The SQL that produces looks like this:
```
BEGIN
CREATE TABLE "customers" (...)
CREATE TABLE "products" (...)
CREATE TABLE "orders" ("id" serial primary key, ... "customer_id" integer NOT NULL)
CREATE INDEX "index_orders_on_customer_id" ON "orders"  ("customer_id")
ALTER TABLE "orders" ADD CONSTRAINT "fk_rails_3dad120da9" FOREIGN KEY ("customer_id") REFERENCES "customers" ("id")
...
```

Now, looking at the schema that ActiveRecord snapshotted to `schema.rb` via introspection:
```
create_table "orders", id: :bigint, default: -> { "unique_rowid()" }, force: :cascade do |t|
    t.decimal "subtotal",    null: false
    t.bigint  "customer_id", null: false, index: true
    t.index ["customer_id"], name: "index_orders_on_customer_id"
    t.index ["customer_id"], name: "orders_auto_index_fk_rails_3dad120da9"
  end
```

The `blah__auto_index_blah` index's name indicates it was automatically added by CockroachDB for a `FOREIGN KEY` relationship (though that should not happen during ALTER TABLE, see #16175). This is unexpected -- the previously added `index_orders_on_customer_id` looks like it should serve just fine.

Adding some addition logging to the `resolveFK` function, it looks like the copy of the table it was operating on during `ALTER TABLE` did not contain the `index_orders_on_customer_id` index, so something about our handling of DDLs in transitions looks suspect here.

cc @vivekmenezes @jordanlewis

**Comment by vivekmenezes** [comment]
@dt the index being created is placed in the mutation queue in the DELETE_ONLY state. I suspect we need to lookup the mutation queue while looking up the index for the foreign key.

**Comment by dt** [comment]
I think the issue that after `CREATE INDEX` returns successfully, a subsequent statement thinks it can assume the index exists and use it, but that's not true since we've only queued it?

**Comment by vivekmenezes** [comment]
I'd assume so. It's definitely only queued up as a mutation for sure. A lot of schema code is okay with it being queued up but perhaps the FK doesn't check

**Comment by vivekmenezes** [comment]
this issue is the same as #24626
