### ISSUE TITLE
sql: truncate while converting an HLC timestamp to a SQL microsecond timestamp

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#16213]
We currently round an HLC timestamp when converting it to a SQL microsecond timestamp. This can result in SQL at times seeing a timestamp in the future when we round up. It might be better for us to always truncate the timestamp with SQL seeing a timestamp in the past. Care must be taken
to check what postgres does when parsing nanosecond timestamps presented as strings.

**Comment by jordanlewis** [comment]
@vivekmenezes is this still relevant? I don't understand what the desired vs current behavior is exactly - how do you see this badness?

**Comment by vivekmenezes** [comment]
I'm closing this issue because it's no longer relevant. We no longer associate sql timestamps with txn timestamps.
