### ISSUE TITLE
sql/parser: division by zero?

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#1622]
Should math errors (such as division by zero) cause the entire expression to error, or for the individual operation to return NULL? The former might be better for an application program while the latter behavior is probably desired for ad-hoc queries. Should the behavior be configurable.

**Comment by tamird** [comment]
Is there any precedent for the latter? I'm leaning toward the former for consistency with our preference for strictness.

**Comment by petermattis** [comment]
I think MySQL returns NULL on division by zero. Or some system does. I'd prefer to return a "divide by zero" error. We can also provide a function (e.g. `div_ieee`) which provides standard ieee floating point semantics (e.g. `1.0/0.0` -> `+inf`)
