### ISSUE TITLE
Kubernetes: cockroachdb/cockroach-k8s-init image is too old to deal with domains

### ISSUE THREAD

**Issue by rumyantseva** [cockroachdb/cockroach#16223]
I was installing cockroachdb to kubernetes v1.5.6 and found a problem.

I used [this instruction](https://github.com/cockroachdb/cockroach/blob/master/cloud/kubernetes/) and found that the file [cloud/kubernetes/cockroachdb-statefulset.yaml](https://github.com/cockroachdb/cockroach/blob/master/cloud/kubernetes/cockroachdb-statefulset.yaml) contains this part of code:

```
pod.alpha.kubernetes.io/init-containers: '[
            {
                "name": "bootstrap",
                "image": "cockroachdb/cockroach-k8s-init:0.1",
                "imagePullPolicy": "IfNotPresent",
                "args": [
                  "-on-start=/on-start.sh",
                  "-service=cockroachdb"
                ],
...
```

The image `cockroachdb/cockroach-k8s-init:0.1` doesn't support dealing with domains, see comment [here](https://hub.docker.com/r/cockroachdb/cockroach-k8s-init/). 

To be able to deal with domains I had to make my own image from the new version of peer-finder and it looked like this:

```
pod.alpha.kubernetes.io/init-containers: '[
            {
                "name": "bootstrap",
                "image": "webdeva/cockroach-init:0.0.2",
                "imagePullPolicy": "IfNotPresent",
                "args": [
                  "-on-start=/on-start.sh",
                  "-service=cockroachdb",
                  "-domain=k8s.cluster"
                ],
...
```

I think it might be helpful for people - to make a new image for `cockroachdb/cockroach-k8s-init` from the actual version of peer-finder. And also it might be helpful to add information how to deal with domains.

**Comment by a-robinson** [comment]
Thanks for raising this issue, @rumyantseva! I wish Docker Hub comments would notify me. I'll rebuild the `cockroach-k8s-init` image with the new peer-finder.

**Comment by a-robinson** [comment]
And weighing in on (or contributing to) https://github.com/kubernetes/contrib/pull/2268 might help move upstream forward a bit faster. I had to build my own peer-finder locally since the upstream version has been ignored for so long.

**Comment by rumyantseva** [comment]
Thank you for the quick solution! 
cockroachdb is the best! :)
