### ISSUE TITLE
sql: RSG parse format not idempotent

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#16226]
`rsg_test.go:294: Parse followed by Format is not idempotent: "EXPLAIN (OVERLAY, IS, CROSS, REGPROCEDURE, INT) ALTER TABLE \"real\".\"decimal\".explain.* SPLIT AT ((((TABLE ident ORDER BY placeholder DESC LIMIT -375))))" != "EXPLAIN (OVERLAY, IS, CROSS, REGPROCEDURE, INT) ALTER TABLE \"real\".\"decimal\".explain.* SPLIT AT ((((TABLE ident ORDER BY placeholder DESC LIMIT - 375))))"`

**Comment by eisenstatdavid** [comment]
The discrepancy here is the space between `-` and `375` in the limit clause. It's unclear to me how the space got omitted on the first `Format`.

**Comment by eisenstatdavid** [comment]
Still scratching my head. I'll send a PR to show the original string too so that we can repro next time.

**Comment by jordanlewis** [comment]
Can we give the RSG a random seed so we can reproduce runs?

**Comment by mjibson** [comment]
Not at the moment. The statement generator uses lots of random calls to determine which branch to take and how to generate datums, and there are many go routines running at the same time doing that. It'd have to be refactored to use a single random source per go routine, and print the seed for each.

**Comment by mjibson** [comment]
Another with the extra print:

`rsg_test.go:294: Parse followed by Format is not idempotent: "ALTER INDEX DECIMAL @ LOCAL TESTING_RELOCATE VALUES ( DEFAULT ) ORDER BY PLACEHOLDER ASC OFFSET EXISTS ( VALUES ( DEFAULT ) ) ROWS FETCH FIRST -412 ROWS ONLY" -> "ALTER INDEX \"decimal\"@local TESTING_RELOCATE VALUES (DEFAULT) ORDER BY placeholder ASC LIMIT -412 OFFSET EXISTS (VALUES (DEFAULT))" != "ALTER INDEX \"decimal\"@local TESTING_RELOCATE VALUES (DEFAULT) ORDER BY placeholder ASC LIMIT - 412 OFFSET EXISTS (VALUES (DEFAULT))"`

**Comment by eisenstatdavid** [comment]
The problem is that we go from storing a negative integer directly as a constant to a unary expression, and the latter's formatter puts a space before `-`. Any objection to making `-` hug its argument?

**Comment by mjibson** [comment]
SGTM
