### ISSUE TITLE
ui: provide insight in current/measured clock offsets

### ISSUE THREAD

**Issue by Freeaqingme** [cockroachdb/cockroach#16242]
Is this a question, feature request, or bug report?

**FEATURE REQUEST**

Currently the --max-offset parameter exists to determine the maximum time offset any cluster member may have compared to the rest of the cluster. This was increased before going GA from 250ms to 500ms because in some cloud environments it's hard to get all nodes in sync, time wise.

Google uses a max of 7ms. In the [Cockroach blog post about time keeping](https://www.cockroachlabs.com/blog/living-without-atomic-clocks/) (really good read) it's described that the higher the allowed offset, the longer some (uncertainty-based) read queries can take. Therefore, as an optimization one may want to lower this offset for performance reasons. 

On the other hand, if all nodes are near this offset all the time, it may be desirable to increase it, or at least be aware of this. That could possibly prevent any number of nodes from crashing themselves, or could an administrator alert to check out his timekeeping setup.

Therefore, it would be nice if the admin console could display the measured clock offsets, and allow administrators to eventually monitor this. 

Currently, the alternative is to monitor a central NTP server from all nodes (at least that's what I do), but that only approximates the Cockroach measurements at best, especially in multi-region deployments.  As a follow-up feature (but is even more long-term than this issue), perhaps it could be possible to dynamically set the offset, based e.g. on a rolling-average/mean clockskew + 2x std dev. Having said that, the fact that at the moment it's necessary to fully stop the cluster when modifying this parameter  may suggest that there's something inherent about the used algorithm (the paper went a bit over my head) that makes this difficult.

3. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

This doesn not impact Cockroach's direct functionality, but it's a gap in what we're currently able to monitor, and with the last leap second we were surprised when a few hours past midnight our cluster fell apart because of this. Aka: Prio is low, but given the potential impact if multiple nodes encounter time skew for whatever reason it should be a must-have once all other must-haves have been implemented :)

**Comment by petermattis** [comment]
@Freeaqingme Thanks for the report. We actually do track and export metrics for clock offsets, but we don't display these metrics on the admin UI. The `/_status/vars` endpoint shows all of our exported metrics (in prometheus format). The clock offset metrics are `clock_offset_meannanos` and `clock_offset_stddevnanos`.

**Comment by mrtracy** [comment]
We did graph these stats at one point early in beta, but we removed the graph because of some sort of inaccuracy, which i'm guessing is no longer present; is this something we could just throw back on the dashboard?  It's likely that if we graphed the max offset across all nodes, it would be useful for this purpose in the short term.

**Comment by dianasaur323** [comment]
This might be better served with a warning vs a time series graph. Punting to 1.2 when we re-explore what warnings we want to surface.

**Comment by bdarnell** [comment]
I think we removed this graph to simplify the dashboard, not because it was inaccurate. We've had this graph in our grafana templates for a long time. We need to reintroduce this, even if it's kind of hidden on a debug page. See also #18253

**Comment by dianasaur323** [comment]
@bdarnell sounds like you want this graph in 1.2. Would you be okay with us punting on #18253 and doing just this graph for now? Either way, I'm going to have trouble committing any of the admin UI engineers to this, so cc @vivekmenezes to find someone else who might be able to help out? This seems like something that could be added by someone outside of the admin UI team.

**Comment by bdarnell** [comment]
Yes, I think this needs to go in 1.2/2.0, and I'd be fine with adding this graph and not the rest of #18253.

**Comment by dianasaur323** [comment]
great, looks like @vivekmenezes is going to take this on. Moving the other issue to 2.1.

**Comment by vivekmenezes** [comment]
closed with https://github.com/cockroachdb/cockroach/pull/21411
