### ISSUE TITLE
perf: investigate using rocksdb::ReadOptions::table_filter on regular reads

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#16257]
When reading a versioned key, creating of a rocksdb iterator requires that rocksdb open every sstable that contains the key. Usually, we only care about reading the most recent version. For example, consider a key that has 5 versions:

```
foo@t5  -> L2.sst
foo@t4  -> L3.sst
foo@t3  -> L4.sst
foo@t2  -> L5.sst
foo@t1  -> L6.sst
```

In order to read `foo@t5` we have to open 5 sstables. If all we're interested in is `foo@t5`, we've done 5x the number of reads than the minimum necessary.

It may be possible to optimize creation of the rocksdb iterator so that it doesn't open lower sstables if a higher one has a matching and newer key. Possibly this could be done using the timestamp bounds we encode into sstable metadata and `rocksdb::ReadOptions::table_filter`. If that mechanism isn't workable, perhaps a new one could be added.

**Comment by petermattis** [comment]
I don't think `rocksdb::ReadOptions::table_filter` will work here. A `table_filter` allows excluding an sstable from consideration when an iterator is created. What we need is a new mechanism that allows excluding an sstable for consideration during `Seek/Next`.

**Comment by jordanlewis** [comment]
Closeable? @petermattis

**Comment by petermattis** [comment]
Yep.
