### ISSUE TITLE
sql/parser: implement cast operations and remove implicit type conversions

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#1626]
Implicit type conversions can lead to unexpected conversion chains. For example, `string -> float -> bool` can allow the value `"1.0"` to evaluate to true, while `string -> bool` would currently be an error. MySQL is big on doing implicit conversions. Postgres does some conversions, but also requires being more explicit. Our experience with Go and type conversions lends weight to being explicit.

**Comment by vivekmenezes** [comment]
Let's be explicit! Please!

**Comment by tschottdorf** [comment]
I've also always found implicit conversions scary and unpredictable (from a user perspective) except when obvious.

**Comment by petermattis** [comment]
We can certainly disallow implicit conversions everywhere. I imagine its easier to loosen the conversion rules later than it is to tighten them.

FYI, slightly surprising behavior from postgres:

```
~ psql
psql (9.4.4)
Type "help" for help.

pmattis=# select 1 + '2';
 ?column?
----------
        3
(1 row)

pmattis=# select '1' + '2';
ERROR:  operator is not unique: unknown + unknown
LINE 1: select '1' + '2';
                   ^
HINT:  Could not choose a best candidate operator. You might need to add explicit type casts.
```

The conversion from string to number is allowed if one of the arguments is a number.

**Comment by petermattis** [comment]
We're now only performing implicit type conversions between int and float in a handful of mathematical operations. I plan to soon add support for cast operations via both the `CAST(<expr> AS <type>)` syntax and the postgres extension `<expr>::<type>`. Once that is done, I think it makes sense to remove implicit conversions completely.

**Comment by tamird** [comment]
Agreed.
