### ISSUE TITLE
sql: actively cancel queries when client connection drops

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#16262]
Reported in #16168: if a long query is issued and the client connection is dropped, the query remains running in the background. 

The problem with this is that some apps may issue a long query, timeout on the lack of result and close their connection, and open a new connection to try again, resulting in a mounting pile of queries that end up all slowing each other down and making the server less and less responsive.

There are three proximate causes that both need to be addressed to solve this:

1) the connection being closed must result in the context being visibly cancelled. This is not currently the case: *while a query is running*, pgwire does not interact with the connection (no reads/writes), and thus the net package has no reason to find that the connection has been closed . This may be partially alleviated once #7775 is addressed, but not completely: any query that does a lot of processing before a single row is returned (e.g. full table scan + filter) or when there are no rows (e.g. insert) would still be susceptible.
2) the local SQL engine must learn to regularly check the context to see if it's been cancelled. 
3) context cancellation at the gateway must propagate through the network of distsql processors.

cc @andreimatei for technical insight
cc @petermattis @cuongdo for triage and prioritization

**Comment by petermattis** [comment]
To address 1, we'll need to have a separate goroutine that reads from the connection vs the one that executes queries. I think that is independent of #7775 (though I suppose it could be done at the same time). As long as we're deriving contexts correctly, we get 3 for free.

**Comment by andreimatei** [comment]
This issue is part of @itsbilal's project, isn't it?

**Comment by knz** [comment]
Not that I know, no. Bilal's project is about cancelling queries/sessions remotely (from another session), not reacting from a connection drop by a client.

**Comment by cuongdo** [comment]
Reassigning unassigned 1.1 issues. Is this staying in 1.1?

**Comment by petermattis** [comment]
The restructuring of how we read from the pgwire connection is relatively small. Assuming Bilal's work properly deals with watching the `Context` for cancellation, I think the remaining work here should be straightforward.

**Comment by andreimatei** [comment]
> The restructuring of how we read from the pgwire connection is relatively small

Yeah... For a better woman, perhaps.
This has been addressed following the principle of  maximal intrusion in https://github.com/cockroachdb/cockroach/pull/22277.
