### ISSUE TITLE
build: non-release builds are getting pushed to docker hub

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#16267]
Something about our detection of which builds qualify as official releases isn't working properly, since it looks like CI builds against the release-1.0 branch are getting considered official releases and pushed to Docker Hub:

<img width="1298" alt="screen shot 2017-06-01 at 10 51 15 am" src="https://cloud.githubusercontent.com/assets/7085343/26685534/6f0e5266-46b8-11e7-8597-b5946e0dd2a6.png">

In the screenshot above, `release-1.0` shouldn't exist and `latest` should have been pushed at the same time as `v1.0.1`.

**Comment by a-robinson** [comment]
This got messed up during the big move from shell to go in #15410 and isn't working because now whether to push is just [keyed on whether the build branch is master](https://github.com/cockroachdb/cockroach/blob/master/build/teamcity-publish-artifacts.sh#L12).

@tamird can you fix this plumbing? It's not immediately obvious how to mimic the new `isStableRelease` logic from the new go code into the shell scripts.

I've removed the offending tags and re-pushed 1.0.1 as latest, but it'll break again as soon as anyone cherrypicks something else to the release-1.0 branch.

**Comment by a-robinson** [comment]
We're pushing alphas to the `latest` tag, too. Pushing them isn't necessarily terrible, but we definitely don't want them to be considered `latest` and going back to not pushing them would be best.

<img width="1278" alt="screen shot 2017-06-01 at 2 41 16 pm" src="https://cloud.githubusercontent.com/assets/7085343/26695317/76fdc086-46d8-11e7-9555-424cd363bbdb.png">

**Comment by a-robinson** [comment]
A separate repo (e.g. `cockroachdb/cockroach-alpha`) would be best if we wanted to publish alpha images.

**Comment by tamird** [comment]
By the way, I'm pretty sure this wasn't broken in #15410 since the old shell scripts simply did not deal with this new alpha-foo scheme that we have: https://github.com/cockroachdb/cockroach/pull/15410/files#diff-facec76c92fac463f09d1ef7bf5b943eL19

**Comment by a-robinson** [comment]
True, the new alpha scheme would have broken anyways. Thanks for fixing it!
