### ISSUE TITLE
storage: support SSTable ingestion

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#16263]
Umbrella issue for #16159.

- [x] determine whether it's worth jumping through hoops to move some of this
  code to CCL (testing complicated unless we soften the boundary some).
- [x] tests for maybeInline
- [x] fix up some locks
- [x] tests for maybeSideload
- [x] tests for replicaGC
- [x] tests for log truncation
- [x] test for snapshot's constructed Raft log entries (must be inlined)
- [x] implement actual on-disk storage
  - [x] decide on/implement actual storage location
  - [x] clean up `addSSTablePostApply`
- [ ] performance counters, stats & visibility into stored files
- [x] make naming more consistent: currently there is fat, thin, sideloaded,
  SSTable, payload, ...
- [x] provide a method `(*Replica).RaftConsistentSnapshot()` which makes sure the snapshot does not see an ingestion which hasn't officially applied yet (as of the snapshot). This wouldn't do much more than just hold raftMu when acquiring the snapshot.

**Comment by danhhz** [comment]
@tschottdorf what's the status here? anything left to do for 1.1?

**Comment by tschottdorf** [comment]
Just what's above, but they're small items. I got it.
