### ISSUE TITLE
backup: reduce effect on p95/p99 of non-backup traffic

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#16276]
I just did a really quick and dirty test. I ran a cluster under the highest load it would sustain, which you'd never do in production but will give us worst case numbers. Looks like p95 and p99 both doubled. We should rerun the same test with the cluster under 80% load and use that to pick a goal for how much backup is allowed to increase the p95/p99. This can be used to guide our performance tuning for 1.1 and there may also be some potential perf wins here.

**Comment by danhhz** [comment]
Note: pre-measurement @petermattis and I both feel that a 20% increase of p99 under 80% load of the kv load generator would be a good goal. Next step is to measure where we're at now

**Comment by danhhz** [comment]
Let's rerun these numbers pre 1.1

**Comment by dianasaur323** [comment]
this is an issue that our friendly user pointed out was a problem as well, so we should allocate some love towards this in 1.2

**Comment by cuongdo** [comment]
@dt have you made any progress on this? should this move to 1.2?

**Comment by danhhz** [comment]
Whoops. Fairly sure no work has happend for this. I meant to move it to 1.2

**Comment by dt** [comment]
yes, we should move this to 1.2.

I ran a few more tests and some had less impact while other runs killed the cluster (node liveness :( ).

Here's a tpch10 backup on lapis this morning:
<img width="1036" alt="screen shot 2017-09-28 at 10 11 32 am" src="https://user-images.githubusercontent.com/15615/30971311-8733f83e-a435-11e7-8c48-340a267cdf48.png">

**Comment by vivekmenezes** [comment]
punting on this for 2.1. We'd like to share our C++ prototype with peter and see how we can get into a working shape.

**Comment by dt** [comment]
The current default value of the export limiter is 5, but on stores with fewer than 5 cores, this likely means that a BACKUP will monopolize all cores until it completes. We should probably set the limiter to no more than numcpu-1 or  numcpu/2 or something so when running on hosts with fewer cores, we leave some for foreground traffic regardless of the setting.

**Comment by bdarnell** [comment]
As a data point (similar to #32209 but more recent), on a 5-node cluster of AWS m5.large (2 vcpu) instances with a 62GB database, an incremental backup took 5 minutes, and during those 5 minutes throughput of the cluster was reduced to around 10% of the steady state. Setting `kv.bulk_io_write.concurrent_export_requests=1` (from the default of 5) improved matters, but throughput was still reduced by half during the backup. 

It appears to be the case that even with concurrency reduced to 1, a backup will reduce throughput by 1/N, where N is the number of CPUs per node. I think this is still too high; we should aim to throttle backup traffic to consume substantially less than one cpu/node. 

As an aside, the backup was actually faster with the concurrency turned down: 5 minutes by default, 3 minutes with the setting changed.

**Comment by danhhz** [comment]
Is this the same data point as the slack discussion where it was mentioned that the load generator was uncapped and maxing out the cluster? If so, that's pretty much a worst case for how much effect BACKUP will have. I recall when we did the initial testing that we saw a superlinear effect when going from something like 80% (I don't recall the exact number) to maxed out. I'd be interested to see what happens on a cluster that's got some headroom.

Either way, the likely first step is to get a handle on which resource(s) what we're maxing out. Could be any number of things: cpu, network, disk, rocksdb cache, some mutex or semaphore somewhere. (For example, I think DistSender has a limiter in it somewhere that was tuned for normal traffic and is overdue to be retuned for mixed normal+ExportRequest traffic.)

**Comment by bdarnell** [comment]
> Is this the same data point as the slack discussion where it was mentioned that the load generator was uncapped and maxing out the cluster? 

Yes.

> Either way, the likely first step is to get a handle on which resource(s) what we're maxing out. Could be any number of things: cpu, network, disk, rocksdb cache, some mutex or semaphore somewhere.

Disk and network metrics increase during the backup, but not by enough that I'd expect to see problems. Total CPU usage doesn't really change. The impact appears to vary based on the number of CPUs in the machine - on a 2-cpu machine the throughput drops by half, with 4 cpus it drops by 25%, etc. This sounds like it's a single thread that's maxing out its cpu (either a special goroutine or one that holds a lock).

**Comment by rolandcrosby** [comment]
@adityamaru27 While you're doing load tests can you see whether your C++ changes improve the p99 here?

**Comment by mwang1026** [comment]
Closing since we did work in 2019 and we'll open a new one if there's an example of work to do here.
