### ISSUE TITLE
ui: add under-replicated ranges count to the summary 

### ISSUE THREAD

**Issue by kuanluo** [cockroachdb/cockroach#16288]
Under-replicated ranges could turn into unavailable ranges.  Would be helpful to add that to a summary on the right. 

Assigning to @mrtracy, so you can properly re-assign if necessary. 

@robert-s-lee

**Comment by mrtracy** [comment]
This has been done for a while, under-replicated ranges appear on the cluster overview.

![screen shot 2018-02-28 at 2 24 55 pm](https://user-images.githubusercontent.com/6969858/36808481-2d59d3fc-1c93-11e8-9a0f-78861a6c383f.png)
