### ISSUE TITLE
*: provide better means for users to op-out of auto-reporting

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#16298]
The issue here is that we already have some reports that users do not like the auto-reporting being opt-out, and find the frequency of once per hour too intrusive.

**The fact that these complaints are emerging is a signal that documentation, tooltips or other such written notices about how to opt-out are insufficient.**

Side constraints:

- having auto-reporting enabled at many user sites is pretty much essential to the success of Cockroach Labs' business, and a major way for us to keep a handle on quality 
- currently it is technically unwise to reduce the reporting frequency when reporting is enabled, because doing so may cause memory usage in each node to grow excessively (due to more data accumulated between reporting events). 

Observation: *it is not **necessary** for auto-reporting to be enabled at **all** user sites by default.* 

We can (and this issue argues we should) provide a choice to those users who care about this.

Some proposals:
- make pre-built binaries have auto-report *enabled* by default, but **change the build rules so that manually built binaries have auto-report disabled by default**. Users that "go for the source" for "more confidence/trust in what they are using" also get the more conservative program behavior.
- (my preference) **publish two sets of pre-built binaries**, with two download buttons under each other on the download page; the bigger one with auto-reporting enabled and the 2nd set "privacy conscious" be just the same build with the different default.

**Comment by knz** [comment]
cc @dt @dianasaur @petermattis

**Comment by dt** [comment]
I mean, given that you can opt-out via a setting or env var, we already "provide a choice", without fragmenting binaries with different features.

I think we can communicate here that this data only used _in aggregate_ e.g. `70% of users are using foreign keys but aren't interleaving`, or `70% of deployments have more than 3 nodes`, etc which lets us prioritize what features to focus on, document, etc.

w.r.t. the frequency... nothing says we need to _report_ stats every time we _clear_ collected stats -- quick-fix here is we just switch back to our previous daily reporting interval, and, yes, we'll just clear and discard stats the other 23h. eventually, we randomize which period we sample for reporting to make what we get more representative, but that can come later.

-1 on fragmenting with different builds for different behavior: flags/settings/env-vars are for tuning runtime behavior -- another dimension to debug on, possible confusion, etc.  That said, non-"release" binaries (e.g. if you just run `make build`) already skip crash reporting but I generally think the binaries we distribute should behave as close as possible to what we build/test/develop day-to-day -- every difference we introduces just add more opportunities for bugs to hide in the discrepancy.

**Comment by dt** [comment]
fwiw, I think when we have an explicit `init`step, it can have a first-class flag(s) for enabling/disabling reporting, which should make this a tad cleaner (when you run `cockroach init --help` you'll see it as one of the options to set).

also, fwiw, as another datapoint, how docker messages their diagnostic data collection (at the bottom of the initial welcome popup, and then in preferences pane):
<img width="404" alt="screen shot 2017-03-24 at 10 44 59 am" src="https://cloud.githubusercontent.com/assets/15615/26749950/46eea5a0-47e5-11e7-9f57-d8d82fe8a2fe.png">
<img width="492" alt="screen shot 2017-06-02 at 10 44 27 pm" src="https://cloud.githubusercontent.com/assets/15615/26749940/169a0f8e-47e5-11e7-90b5-9fb6e055a2d7.png">

**Comment by knz** [comment]
I hear your rational arguments but that's, I fear, insufficient. People who are complaining about this **despite the fact we're pretty clear already about what happens** will not listen to the argument "but you can disable reporting if you want." 

The issue we're having here is that there is an emotional knee-jerk reaction to what is perceived as a breach of trust by a user **who did not initially read our instructions** / admin UI messages and only discovers after the fact they may have exposed their private data.

Once this reaction is triggered, we have a potential PR problem, which we want to avoid altogether.

**Working with the assumption that we need to work with users WHO WILL NOT READ** it is reasonable to seek to provide a path that makes it *unavoidable* for them to face the choice to opt-in/opt-out and make a decision before they use the binary.

Perhaps a confirmation pop-up with instructions could be useful?

**Comment by knz** [comment]
I saw your docker reference just afterwards. Yes, such a UI would be appropriate. Perhaps `cockroach init` can help, or perhaps even a migration function on the DB that sets a flag after an interactive confirmation by the user?

**Comment by dt** [comment]
note that we should (and do) make sure that the reported metrics don't contain private data, there should be much to be upset about but yes, we definitely don't want to to come as a surprise to anyway that their nodes were doing something.

**Comment by knz** [comment]
> note that we should (and do) make sure that the reported metrics don't contain any "private data", so there should not be much to be upset about

A user who did not read the doc will not know the metrics don't contain private data. The conservative assumption they will make is that private data is reported, amplifying the emotional nature of the reaction.

**Comment by bdarnell** [comment]
Providing separate binaries would be a very expensive way to address this. We have a lot of installation options and that number will only grow as we add things like deb/rpm packages. We don't want to multiply that by two for reporting and non-reporting versions. I like the `init` command as a more direct place to provide this disclosure along with an immediately actionable opt-out, although it's not foolproof (there will probably still be situations where `init` is scripted away, out of sight of the user).

**Comment by knz** [comment]
(answer from mail)

> The concerns are over-blown in my opinion. Tons of closed source products collect usage data and you have no idea what data is being collected. We're an open-source product. The user can literally look at the code to see what data is being collected and there is nothing nefarious being done. I think we should hold our heads high and proudly indicate we're collecting this data to make the product better. And we should get out in front of messaging how different this is from the data being collected by Google/Facebook/Instagram/etc. 

> Providing a version of the binaries which disables opt-in by default is a non-starter (again, in my opinion).

**Comment by knz** [comment]
(answer from mail)

> It may be over-blown and not entirely rational (hourly reporting is no worse for privacy than daily reporting for an always-on server product, but it *feels* worse), but that doesn't necessarily mean we can ignore it. We've stood our ground against a much larger group of users asking for the name to change (and this is just two users so far complaining about our opt-out reporting), but there's a real security/privacy worry underlying the complaints here. 

> We need to make sure that users don't feel betrayed when they learn about our usage reporting. Part of that comes before they start using the product: we disclose the fact that we collect this data and give them a chance to opt-out before proceeding (and this is something that ought to be considered in all of our installation methods: if someone uses our kubernetes configs, what is the right way for them to opt-out?). Part of it comes after: when someone who has been using CRDB for a while learns that "cockroach uploads your queries!!1!", how do we put them at ease? One way would be to show them a personalized report of *exactly* what we collect: a page in the admin UI that shows what we have reported (or would report, if they have opted out). 

> Consider the worst-case scenario: our registration database is compromised and its contents posted publicly. That would obviously be a huge embarrassment for *us*, but what about our users? If our users' interests would be harmed by this compromise (or if they would feel like their interests were harmed), we should reconsider how much data we're collecting and storing.

**Comment by knz** [comment]
One thought which I already posted earlier on the issue: the reaction we're discussing here most evidently 1) comes from users who have not paid attention to the written notices already present 2) is emotional not rational (betrayal, sadness, etc)

We can't solve this by just advisory written notices -- a user who already doesn't read written notices during install will not read more written notices during install.

Some other data points, Docker (mentioned by David) and Mozilla products have both a pop-up during install (Docker) or on first run and *also* upgrades (Mozilla) which reminds the user that telemetry is enabled by default. 

I like the first run / upgrade popup because it is not on the path to install; the path to install is where users are in a hurry to try things out and typically pay less attention (software installs are mostly auto-pilot these days, **users have been trained by microsoft to unconsciously ignore licensing/disclaimers during install**), and we want that path to be as short as possible.

Now that said:

- a user might not launch the admin UI at all when trying us out. A pop-up in the admin UI is obviously insufficient.
- the idea of a "pop up" in a CLI utility is ... weird and technically hard-ish to implement.
- the future `init` command may be the good place to do this, but then again it might be automated away.

Assuming we don't go the road of multiple binaries what about a combination of approaches deployed together:

- [ ] make the CLI `sql` shell display the telemetry settings [ **rationale:** users are likely to launch the CLI shell to try things out even if they automate node creation! This will be even more true when users buy into CockroachDB as a hosted service, either from us or from others ]
- [ ] make the `cockroach start` command display the current setting on startup with a link to doc on how to change it [ **rationale:** even when automating, users are likely to look at the output of `cockroach start`, either on the console or in logs, to check everything was fine ]
- [ ] provide a build flag to change the default, and document this in our "build from source" instructions [ **rationale:** paranoid users will build from source, and will appreciate that option there ]
- [ ] make `init` ask for confirmation / provide a flag to opt out (already suggested)
- [ ] pop up in admin UI on first use (already suggested)

**Comment by knz** [comment]
(Note that by the same argument, we should really do something about `--insecure`. I foresee users feeling betrayed when they realize what it really means.)

**Comment by petermattis** [comment]
There are definitely improvements we can make to messaging and optics around our collection, but let's not blow this problem out of proportion. There is an argument to be made that the data collection we're currently doing is in our users best interest. It allows us to see which queries are being used and optimize the product for the actual usage. Not doing this collection would require users to report that info manually, which tends to not happen. 

Also, we have taken care to ask actual users about this data collection and none expressed concern when we described what we were doing. More than one suggested this sort of data collection themselves, unprompted. Clearly, there will be a subset of users who will take issue with what we're doing. That's unavoidable. Let's make reasonable efforts to improve our transparency to assuage the concerns. I don't think we need to throw the kitchen sink at this problem.

**Comment by knz** [comment]
(from mail)

> In terms of addressing this in docs, we already have a callout at the end of the installation procedure: https://www.cockroachlabs.com/docs/install-cockroachdb.html. A few other things we could do:

> - In the instructions for starting the first node of a cluster (both local and distributed), we could explicitly call out the env variable to opt out right away as well as info about opting out after cluster startup via the cluster setting. Or is that overkill? 
> - We could add a tip about this to the stdout on node startup, perhaps just with a link to the page explaining diagnostic reporting and opting out.

> Just initial thoughts. We can discuss here or at next week's docs meeting.

**Comment by petermattis** [comment]
I don't think there is any urgency to doing something here in the 1.1 time frame. Punting to 1.2.

**Comment by knz** [comment]
We have made progress in explaining this and the rate of complaints has decreased.
