### ISSUE TITLE
sql: missing support for SET NAMES

### ISSUE THREAD

**Issue by faiverson** [cockroachdb/cockroach#16297]
**BUG REPORT**
Laravel framework (probably Symphony too) is creating this bug when you setup the database:
```
[PDOException]                                                              
  SQLSTATE[XX000]: Internal error: 7 ERROR:  unimplemented at or near "utf8"  
  set names 'utf8'  
```

This is because it is setting `set names 'utf8'` always
I guess we need compatibility with the charset

**Comment by knz** [comment]
Thank you for filing this!

**Comment by knz** [comment]
cc @cuongdo for triage and prioritization
