### ISSUE TITLE
Support for adding int and float

### ISSUE THREAD

**Issue by eldos-dl** [cockroachdb/cockroach#16303]
**FEATURE REQUEST**

Support for adding `int` and `float`. Getting
```
InternalError: unsupported binary operator: <int> + <float>
```
Any reason why `int` + `decimal` is allowed but `int` + `float` is not even though casting from `int` to `float` is also supported?

**Comment by knz** [comment]
The general principle is that CockroachDB does not perform implicit conversions / heterogeneous operations when the result is not exact.

int + decimal always has an exact result, so that is allowed.

**Comment by knz** [comment]
Please consult

https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/typing.md

and

https://www.cockroachlabs.com/blog/revisiting-sql-typing-in-cockroachdb/

for details on how typing works in CockroachDB's sql.

**Comment by eldos-dl** [comment]
Okay, thanks for the clarification.
