### ISSUE TITLE
distsql: OOM with tpch queries 1, 8, 9

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#16320]
cluster: `navy`
load: `photos` running on 6 nodes, 2-way concurrent `tpch` running queries 1, 7, 8, 9
_no chaos_

This crash seems easily reproducible. The last time I reproduced this, it took 27 minutes from the start of the load.

memory profile:
[profile001.pdf](https://github.com/cockroachdb/cockroach/files/1052530/profile001.pdf)

log of a node where `cockroach` OOMed:
[cockroach.stderr.txt](https://github.com/cockroachdb/cockroach/files/1052531/cockroach.stderr.txt)

`cockroach` is using 8.5 GiB of Go memory:
```
I170605 15:34:08.190809 158 server/status/runtime.go:225  [n4] runtime stats: 13 GiB RSS, 293 goroutines, 5.2 GiB/2.7 GiB/8.5 GiB GO alloc/idle/total, 3.6 GiB/4.4 GiB CGO alloc/total, 92577.03cgo/sec, 3.26/0.28 %(u/s)time, 0.00 %gc (1x)
```

These two lines in `(*hashJoiner).buildPhase()` correspond to nearly all of its memory use:
```
  121.03MB   121.03MB    230:		b.rows = append(b.rows, rowIdx)
         .    55.50MB    231:		h.buckets[string(encoded)] = b
```

**Comment by cuongdo** [comment]
build: 0bf5973

**Comment by cuongdo** [comment]
I'm trying to see if there's a simpler repro for this.

**Comment by cuongdo** [comment]
I've found a simpler repro for this OOM:

`./tpch -v -max-errors=0 -queries=1,8,9 -loops=0 -concurrency=3 <database_URL>`

[DDLs are here](https://github.com/cockroachdb/loadgen/blob/master/tpch/ddls.go)
Queries: [query 1](https://github.com/cockroachdb/loadgen/blob/master/tpch/query1.go) [query 8](https://github.com/cockroachdb/loadgen/blob/master/tpch/query8.go) [query 9](https://github.com/cockroachdb/loadgen/blob/master/tpch/query9.go)

OOMs occurred within an hour of starting the load.

**Comment by RaduBerinde** [comment]
The memory profile shows only 400MB total usage.. Nothing looks off in that profile.
Is it possible to set things up to automatically collect a mem profile when total usage goes beyond a certain value?

**Comment by cuongdo** [comment]
Mem profiles were being collected every minute. So, that mem profile was collected when the RSS for `cockroach` was already ~13 GiB and close to being killed.

**Comment by petermattis** [comment]
> Is it possible to set things up to automatically collect a mem profile when total usage goes beyond a certain value?

Not currently, though we could consider adding that. Usually I run `COCKROACH_MEMPROF_INTERVAL=10s` and collect a lot of profiles.

**Comment by petermattis** [comment]
@cuongdo Do you have logs from the node that died? Specifically, `runtime.go` prints Go vs CGo memory usage every 15s or so.

**Comment by cuongdo** [comment]
Yes, it's in `cockroach.stderr.txt` linked to in the first part of this issue.

**Comment by petermattis** [comment]
Something seems off here. The profile indicates 400MB of allocated memory while the `runtime.go` messages indicate 2.7GB. I believe the profile is supposed to scale the value based on the sampling.

**Comment by cuongdo** [comment]
Yes, I was wondering about that. I thought that scaling was supposed to happen as well, based on previous Go profiling I've done.

**Comment by cuongdo** [comment]
Going to rerun without memory profile sampling.

**Comment by cuongdo** [comment]
Here are the `cockroach` stderr log and memory profile on a host that OOMed with `GODEBUG="memprofilerate=1,gctrace=1"`:

[cockroach.stderr.txt](https://github.com/cockroachdb/cockroach/files/1055789/cockroach.stderr.txt)
[profile001.pdf](https://github.com/cockroachdb/cockroach/files/1055790/profile001.pdf)

Last runtime stats before OOM kill:
```
I170606 15:46:58.576908 197 server/status/runtime.go:225  [n5] runtime stats: 13 GiB RSS, 353 goroutines, 7.5 GiB/1016 KiB/8.7 GiB GO alloc/idle/total, 3.5 GiB/4.2 GiB CGO alloc/total, 357.93cgo/sec, 0.59/0.36 %(u/s)time, 0.00 %gc (0x)
```

Memory profiles were already enabled for every 10s.

**Comment by RaduBerinde** [comment]
I have been playing locally with query 8. Just one instance of it exceeds the budget on my machine, and I wasn't able to find a discrepancy between usage and accounting.

However, its obvious there are huge opportunities for better planning of these queries. For example, in query 8 the last hashjoiner is joining ~1300 rows on the left with ~365K rows on the right. We store 365K rows when we could be storing just 1k. There are likely even more dramatic improvements to be made by changing the order of the joins (the smaller 1k row set should come in play much earlier).

We don't have a query optimizer that could figure these things out. But in the interim we could tweak the hashjoiner to first read a bunch of rows from both left and right, in the hope that one of them is going to be small (in which case we decide which of them to store).

**Comment by RaduBerinde** [comment]
@cuongdo again there is a discrepancy there - the profile shows ~4GB allocated, the stats show 7.5GB. Note that the available budget is 3.7GB which seems to be around what we have allocated according to the profile.

**Comment by petermattis** [comment]
Looks like most of the memory is in `hashJoiner.buildPhase`, exactly what you saw earlier. @RaduBerinde beat me to the point that there still seems to be a discrepancy here between the `runtime.go` log messages and the profile.

**Comment by cuongdo** [comment]
It's worth nothing that almost 1 GiB of "idle" memory is being held by the Go runtime and hasn't been released to the OS. This is enough to tip us into OOM territory.

**Comment by petermattis** [comment]
The most recent gctrace message shows:

`gc 1862 @2335.362s 3%: 0.20+3850+0.14 ms clock, 0.83+4071/3849/0+0.56 ms cpu, 7222->7476->4227 MB, 7738 MB goal, 4 P`

See https://golang.org/pkg/runtime/ (search for gctrace) for an explanation of the fields. The `7222->7476->4227 MB` bit indicates that the heap started at 7222 MB when GC was initiated, grew to 7476 MB when GC finished and there are 4227 MB of live heap data. I think this explains the discrepancy between the heap profile numbers and the runtime stats. When the heap gets large, the Go runtime is waiting a long time between GC runs.

**Comment by petermattis** [comment]
@RaduBerinde I like your suggestion for a short term fix: have `hashJoiner` read X rows (i.e. 10k) from both the left and right streams in the hopes of reaching the end of one of the streams.

**Comment by RaduBerinde** [comment]
Another HashJoin in query 8 has 10K rows on the left, 9M rows on the right. Ouch.

**Comment by petermattis** [comment]
Rather than reading X rows from both the left and right, you could read X MB.

**Comment by cuongdo** [comment]
did #16380 resolve this?

**Comment by RaduBerinde** [comment]
I reran these queries on a single-node instance with scalefactor=1. Query 8 which used to blow through a multi-gig budget now takes between 256-512Mb. Query 1 under 32Mb. Query 9 still exceeds the budget.

Closing this (remaining tasks like mergejoins and disk-based joins are tracked elsewhere).
