### ISSUE TITLE
storage: new "unsplittable" request flag

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#16338]
The WriteBatch request (as well as the upcoming one to work with IngestExternalFile) has a payload that includes encoded keys. These payload are opaque to the normal kv mechanisms, so if a request is constructed and sent for a span that has split, it will error and let the client retry (splitting the payload into multiple requests).

We could save some network traffic and serialization/deserialization if we had a new "unsplittable" flag for range requests that would cause distsender to error if the request span crosses range boundaries. This will still need to be checked during command evaluation, this just short-circuits the case when distsender knows it will need to be split

This is pretty low priority as the ranges these requests currently operate on are empty and so it's unexpected that they would split

**Comment by petermattis** [comment]
@danhhz Is there still something to do here?

**Comment by danhhz** [comment]
This was done in 50f01ffb
