### ISSUE TITLE
rpc/client: clock updates should be done one level higher

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#1633]
The `rpc` package is cockroach's wrapper around `net/rpc`. Within it, `client` currently:
- caches rpc clients such that there is at most one per outbound address (in a single global variable)
- periodically heartbeats the remote side, and updates a clock which is passed by reference into the `NewClient` factory method

The users of `rpc/client` are `multiraft`, `gossip`, and `kv` (namely `DistSender`). As far as I can tell, only `kv` relies on the clock synchronization to do its work; `gossip` and `multiraft` don't care. Furthermore, it has been suggested in #1283 that having just one `net/rpc.Client` per remote address is not ideal.

I suggest we dismantle `rpc/client` and move its responsibilities to `rpc/send` (the interface used by `kv.DistSender`). The only thing we should keep there is the current use of `rpc/codec`.

`gossip` and `multiraft` don't even need `rpc/codec`, since they are used _only_ between cockroach nodes, and would work just fine using Go's default `gob`-based codec. They should use the regular `net/rpc` facilities.

**Comment by tschottdorf** [comment]
some remarks:

* I think we eventually want (or at least wanted) `proto` for everything (to avoid buying into `gob` for parts of the system). That may have changed.
* measuring clock offset is a cluster-wide task. It doesn't really matter what the client wants, we should measure the clock offset whenever RPCs are sent in the cluster (not necessarily if we have multiple clients per peer pair, but I'm not sure what you're planning). The awkward thing about the offset is mostly the current API (clients shouldn't really have to deal with it, but when the offset is out-of-range some callback should notify a central part of the system).

What would happen to the client cache in your proposal?

**Comment by tamird** [comment]
> I think we eventually want (or at least wanted) proto for everything (to avoid buying into gob for parts of the system). That may have changed.

This decision predates me, but I think it was done for ease of implementation of client libraries in other languages. For raft/gossip, it's irrelevant. @petermattis probably knows more.

> The awkward thing about the offset is mostly the current API (clients shouldn't really have to deal with it, but when the offset is out-of-range some callback should notify a central part of the system).

So this is kind of interesting. I haven't investigated this completely, but as far as I can tell, the only action ever taken when the offset is out of range is on the out-of-range node itself: it commits suicide. In that sense, there's no need to notify a central anything: whatever part of the system performs the clock updates would just `log.Fatal` when the offset is too high.

> What would happen to the client cache in your proposal?

First, I think it's important to acknowledge that there is no evidence to suggest that one client per node-pair is optimal. If we discover (or decide on faith) that we actually need a client cache, it should probably go on the successor to `rpc.Context`. Otherwise, we could just remove it.

**Comment by tschottdorf** [comment]
Sorry, cluster-wide task is a slight misnomer. It's independent of the clients using the connection. Only the node which finds out  it's over the limit dies, but each measurement gives information on to both peers.

**Comment by tamird** [comment]
@tschottdorf right, and that information is only used by the machinery in `kv.DistSender` (right?).

If we decide to keep the client cache on the context, this would amount to moving the heartbeat loop to the `DistSender`, using a client retrieved from the cache.

**Comment by tschottdorf** [comment]
I don't know that the `DistSender` plays a special role. What I was trying to say above is that if our node talks to any other node, we should check the offsets. We don't do that for any individual part of the system (not the `DistSender`, not a `Store` - it's really for all of the running process, i.e. `Server`) so it would look weird to me if that functionality lived on the `DistSender`. It might as well be in `rpc/client` (or whoever owns the client cache) and going over offset could fire a callback (which would likely call into `Server`).

> First, I think it's important to acknowledge that there is no evidence to suggest that one client per node-pair is optimal. If we discover (or decide on faith) that we actually need a client cache, it should probably go on the successor to rpc.Context. Otherwise we could just remove it.

Isn't it likely though? Go's `rpc/client` is already built to handle parallelism efficiently and keeping the TCP connections open can't be a bad idea. Also we'll always want to keep some state on our peers and mark nodes as available or dead, so doing everything ad-hoc will be hard. Of course I agree that if the underlying assumptions change, we might want to cook up something else.

Re: gob: that's not how it went as far as I recall. I think we really don't wanted to use `gob`. See https://github.com/cockroachdb/cockroach/issues/629

btw,  I'm still surprised you just ditched your PR #1523 - if nothing else it improved on the previous state.

**Comment by bdarnell** [comment]
I agree with @tschottdorf: we want to have one connection per pair of nodes, we want to measure clock offsets any time two nodes communicate no matter what package initiated the communication, we don't want to use gob anywhere, and #1523 still seems like a good idea.

**Comment by petermattis** [comment]
@tamird I imagine this will be revisited as part of your gRPC work.
