### ISSUE TITLE
Read only command don't wait if read timestamp is less or euqal than minimum timestamp of read caches which covers the read interval.

### ISSUE THREAD

**Issue by yananzhi** [cockroachdb/cockroach#1634]
A read only command will wait if cmdQ has a write command which has overlap with read command. I think this is used to avoid a wirte command with a lower timeatmp execute after thre read command. @spencerkimball  @tschottdorf Is that right?
We define a timestamp called minReadCacheTs which is minimum timestamp of read cached entrys that covers the interval of read command, if the timestmap of read command is less or equal than minReadCacheTs, it need not wait if cmdQ has a write command which overlaps with read command becuase write command can not commit with a lower timestamp than minReadCacheTs. even the read command need not require a leader lease.
@spencerkimball  @tschottdorf  is that idea practicable?

**Comment by vivekmenezes** [comment]
This is considered a read that is happening in the "past" as far as all
nodes are concerned. We maintain an uncertainty interval to deal with time
uncertainty concerning the "present time" between nodes. But if you want to
do a read, for instance, of the entire DB at a timestamp in the "certain
past" we know such reads need not block on transactions happening in the
"present". The basic idea is once you've gained certainty that you need not
queue waiting on any other operation, you can move forward with the
operation.

Are you trying to force a past timestamp on the operation and thus need the
"minReadCacheT". I hate the idea of it talking about a "cache". I'd rather
we create a concept like "most recent past timestamp". And for now we might
just implement it using a simple formula like 5 second in the past.

**Comment by yananzhi** [comment]
@vivekmenezes May be I have not expressed clearly. 
Object Range has a method beginCmd, each command to be executed on range will call the methed beginCmd, the beingCmd method check the cmdQ of range, if there has command which has overlap with current command in the cmdQ,, current command will wait until the overlap commands completed.
the read command can be blocked by write command, the write command can be blocked read command and write command. My question is why we do this?  Is it can be optimized?

I think it is used to ensure correctness of MVCC, the commit timestamp of transaction is not the timestamp when a transacton execute commit action. If a key(from start to end) has been read on read_ts, we should insure the key can' be write with a timestamp lower than the read_ts. so each range has a tsCache to record latest read timestamp.

 My thought is if a read command found there has a latest readTS, and timestmap of read command is less or equal than latest readTS , the read command can be executed directly on range with out wait overlap write command in cmdQ and require a leader lease. 
as the MVCC rule, read command can only see the result which commit before the timestamp of read, if there has a readTS for given keys, mean the given keys can't be write with a earlier timestamp than readTS and current replica has the lease for the readTS. 
It is hard to describe it to me, you can view the code to see whether there has any problem:
https://github.com/yananzhi/cockroach/tree/minreadcache

**Comment by vivekmenezes** [comment]
Thanks for pointing me to the code.

I agree that conceptually we could make an optimization for situations
where when a lot of reads hit the same data, one read can end up
benefitting the other reads. I think this is a good optimization akin to
the benefits of using a cache. But I'd like to better understand the
benefits here, not necessarily numerically but conceptually at a minimum.
Before we look at a particular PR it will be nice to understand the goals.
A few thoughts on what a goal might be:

1. The read cache is used currently to push writes in the immediate past,
into the future, to provide linearizability on the key:value . You would
like to also use the same cache to service reads done in the immediate
past. At a minimum this saves us reading the value from the current leader
(an rpc).
2.Road block: If there is a write intent between the two reads we want to
push the read timestamp to the timestamp of the write intent. Do you know
how this is done? Perhaps the write intent's timestamp is reflected in the
read cache (it has got to) thus allowing the read to be pushed.

Most importantly, I feel that before making such a change it would be worth
adding what you would like to do to the design doc. If your aim is to
introduce a read cache for faster reads, let that be the goal and add it to
the design doc (see the section on transaction interactions). I'm very much
in favor of mechanisms that speed up read performance. Any database is
guaranteed to have read hotspots, and we need the best solution for that.

Thank you

Vivek

**Comment by yananzhi** [comment]
@vivekmenezes Read command only push the intent with a lower timestmap than its timestap, we assume second read timestamp is less than first read timestamp, if a write command execute after first read command done, the timestmap of write intent is greater than timestamp of first read command, the second read command will ignore the intent to read the prev version.   
You are right about the goal: speed up read/write performance for the hotspots keys, a write command will not be blocked by a optimized read command. It is not a well considered idea, I will do some test for the correctness and performance.

**Comment by spencerkimball** [comment]
`A read only command will wait if cmdQ has a write command which has overlap with read command. I think this is used to avoid a wirte command with a lower timeatmp execute after thre read command. @spencerkimball @tschottdorf Is that right?
`

Yes, that's correct.

`We define a timestamp called minReadCacheTs which is minimum timestamp of read cached entrys that covers the interval of read command, if the timestmap of read command is less or equal than minReadCacheTs, it need not wait if cmdQ has a write command which overlaps with read command becuase write command can not commit with a lower timestamp than minReadCacheTs. even the read command need not require a leader lease.
@spencerkimball @tschottdorf is that idea practicable?
`

Yes, that idea is workable. We can also let any replica serve reads for timestamps which occur before the leader lease start time, as those start times must monotonically increase.

To your earlier suggestion, I think we can be more aggressive on the leader. I think we can look at the write timestamp cache when servicing a read and if the read is at a timestamp earlier than the highest write timestamp in the cache, then we can go ahead with the read. Not sure how useful that optimization will be in practice though, although I can imagine certain overlapping transactional use cases where it would be handy.

**Comment by yananzhi** [comment]
@spencerkimball 
```
We can also let any replica serve reads for timestamps which occur before the leader lease start time, 
as those start times must monotonically increase.
```
I can understand optimization of read timestamp cache and write timestamp cache, both of them can guarantee the future write command can't commit with a earlier timestamp than them. But I can't understand why any replica can serve reads for timestamps which occur before the leader lease start time,

**Comment by bdarnell** [comment]
@yananzhi No leader will commit a command with a timestamp older than its lease, so once a replica knows about a lease, it knows that nothing older than that lease will change.

**Comment by yananzhi** [comment]
@bdarnell I check the code again, Could not find a place which block a write with a lower timestamp than current lease's starttime. the method ```Covers``` of Lease only check timestamp less than the Expiration.
I write a simple test, it also passed.
```
// TestWriteWithLowerTsThanLeaderLease verifies that write with a timestamp lower than the
// start time of current lease can execute succeed.
func TestWriteWithLowerTsThanLeaderLease(t *testing.T) {
	defer leaktest.AfterTest(t)

	tc := testContext{}
	tc.Start(t)
	defer tc.Stop()

	clock := tc.clock

	// Ts0 <  leaseStart < leaseExpired
	ts0 := clock.Now()

	gArgs := getArgs(proto.Key("a"), 1, tc.store.StoreID())

	// Force request a new lease.
	gArgs.Header().Timestamp = clock.Update(clock.Now().Add(int64(DefaultLeaderLeaseDuration), 0))
	_, err := tc.store.ExecuteCmd(context.Background(), &gArgs)
	if err != nil {
		t.Fatal(err)
	}

	l := tc.rng.getLease()
	if l.Start.Less(ts0) {
		t.Fatalf("ts0=%v is not less than lease's starttime=%v", ts0, l.Start)
	}
	t.Logf("ts0=%v, lease's starttime=%v lease's expired time=%v", ts0, l.Start, l.Expiration)

	// Test that a write with a timestamp lower than current lease's start time can execute succeed..
	pArgs := putArgs(proto.Key("a"), []byte("valuea"), 1, tc.store.StoreID())
	pArgs.Header().Timestamp = ts0
	_, err = tc.store.ExecuteCmd(context.Background(), &pArgs)
	if err != nil {
		t.Fatal(err)
	}
}
```

**Comment by bdarnell** [comment]
@yananzhi The mechanism is the timestamp cache (`Range.tsCache`). When a new lease is granted, the low-water timestamp is reset, and any new commands with an older timestamp will be rejected in `addWriteCmd`. As an optimization, this only occurs when the holder of the lease changes - if the same node holds two consecutive leases (as in your test), the low-water timestamp is not reset.

**Comment by yananzhi** [comment]
@bdarnell This is the key point:```if the same node holds two consecutive leases (as in your test), the low-water timestamp is not reset.``` , If I want read consistency data with a lower timestamp than start time of current lease in a replica which is not current range leader, the low-water timestap must be updated even the same node holds two consecutinve leases.
I got it, thanks.

**Comment by bdarnell** [comment]
Ah, good catch. So replicas can't automatically serve reads from before the current lease; they can only serve reads before the current leader's first lease (which is probably a long time ago). We also can't reset the low-water timestamp to the current time when a leader renews its own lease; this would be too disruptive to transactions in progress. Maybe renewing the lease could advance the low-water timestamp by some amount without going all the way to the current time; this would keep the low-water mark close enough to the current time to allow followers to serve some reads.
