### ISSUE TITLE
ui: staggered version node diagnosis page

### ISSUE THREAD

**Issue by kuanluo** [cockroachdb/cockroach#16359]
@jseldess @mrtracy and I discussed to have a page linked from the staggered version alert, so users can see the versions the nodes are on.

@dianasaur323 @nstewart, can you chime in and prioritize this accordingly? Perhaps 1.2?

**Comment by dianasaur323** [comment]
Let's do 1.2

**Comment by BramGruneir** [comment]
We do now have a node diagnostics page that does show this.  But this shouldn't be what we link the staggered version warning from.

/debug/nodes

**Comment by kuanluo** [comment]
Interesting! If we already have the information, perhaps we can just point to this url in the alert? That would be an easy win. @dianasaur323, @mrtracy thoughts?

**Comment by dianasaur323** [comment]
I think we need to discuss the broader /debug page strategy - my assumption was that these weren't going to be super user facing, and were only going to be used for true debugging issues. I think the inability to easily see your node configurations is still an issue though - instead, perhaps we could tell them what CLI to run?

**Comment by kuanluo** [comment]
> I think we need to discuss the broader /debug page strategy - my assumption was that these weren't going to be super user facing, and were only going to be used for true debugging issues.

Agree. 

> I think the inability to easily see your node configurations is still an issue though - instead, perhaps we could tell them what CLI to run?

The problem we're trying to solve is to give hints on how someone can possibly fix the alert. Ideas so far are: 

1. Give CLI command
2. Create a new node version page that only links to from the alert. 
3. Add the node version on "node list" page. 

Any other suggestions, @dianasaur323 @BramGruneir @mrtracy? The next step can be weigh the pro and con as a group and decide on a solution?

**Comment by dianasaur323** [comment]
I vote option 3 - we could think about what configs to show at the node level there. a [...] button might be enough for v1 of this fix. I think once we figure out cluster visualization, we should show node configs on that page instead of in the existing monitoring page.

**Comment by BramGruneir** [comment]
I wrote a super basic version of option 3.  See #16495.

**Comment by kuanluo** [comment]
Per our discussion in design meeting today, option 3 seems like the best approach for 1.1. @BramGruneir please let me know if you need any additional design help. I commented on #16495 that we could hide the summary table for now. And when our new designer Josué joins, we can figure out a better design.

**Comment by couchand** [comment]
I'm considering this closed by #16495.
