### ISSUE TITLE
cluster failed, exit status 255

### ISSUE THREAD

**Issue by foreachsky** [cockroachdb/cockroach#16351]
Is this a question, feature request, or bug report?

**QUESTION**

i‘m try to deployment 3 nodes 
https://www.cockroachlabs.com/docs/manual-deployment.html

the first node start ok，but the second node start error

the error msg is 

cockroach start --background --logtostderr --certs-dir=/data/cockraoch/certs/ --host=192.168.18.231 --join=192.168.18.230:26257
I170607 16:21:52.805480 1 cli/start.go:591  CockroachDB CCL v1.0.1 (linux amd64, built 2017/05/25 15:17:49, go1.8.1)
I170607 16:21:52.913462 43 cli/start.go:338  starting cockroach node
W170607 16:21:52.918959 43 gossip/gossip.go:1196  [n?] no incoming or outgoing connections
I170607 16:21:52.931752 49 gossip/client.go:131  [n?] started gossip client to 192.168.18.230:26257
I170607 16:21:52.932994 43 storage/engine/rocksdb.go:380  opening rocksdb instance at "/data/cockraoch/cockroach-data"
F170607 16:21:52.933517 68 server/server.go:162  [n?] fewer than half the known nodes are within the maximum offset of 500ms (0 of 1)
goroutine 68 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x0, 0x37a4599a, 0x2bf9300, 0x10)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:858 +0xa7
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x2bfaae0, 0xc400000004, 0x248a899, 0x10, 0xa2, 0xc420010ae0, 0x54)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:724 +0x591
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x7f6adbfff9c8, 0xc420345a10, 0x4, 0x2, 0x0, 0x0, 0xc420a09cf8, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:158 +0x4b3
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x7f6adbfff9c8, 0xc420345a10, 0x1, 0x4, 0x0, 0x0, 0xc420a09cf8, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:68 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatal(0x7f6adbfff9c8, 0xc420345a10, 0xc420a09cf8, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:171 +0x76
github.com/cockroachdb/cockroach/pkg/server.NewServer.func1()
        /go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:162 +0xba
github.com/cockroachdb/cockroach/pkg/rpc.(*Context).runHeartbeat(0xc42055bef0, 0xc42029c2c0, 0xc4201d6cc0, 0x14, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:415 +0x55a
github.com/cockroachdb/cockroach/pkg/rpc.(*Context).GRPCDial.func1.2.1(0x7f6adbfff9c8, 0xc42031b980)
        /go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:297 +0x6b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc42045c3d0, 0xc4201203c0, 0xc420345b60)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xf7
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:216 +0xad
E170607 16:21:52.986509 1 cli/error.go:68  exit status 255
Error: exit status 255
Failed running "start"

**Comment by mberhault** [comment]
The fatal message is: `F170607 16:21:52.933517 68 server/server.go:162 [n?] fewer than half the known nodes are within the maximum offset of 500ms (0 of 1)`
This indicates that the clocks on your nodes are too far apart for us to guarantee consistency.

[We recommend](https://www.cockroachlabs.com/docs/recommended-production-settings.html#clock-synchronization) running with time synchronization on all your instances such as ntp, openntp, or chrony.
