### ISSUE TITLE
server: Refactor node ID initialization

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#16363]
In order for a node to learn its node ID, it must first initialize its stores. The node ID is stored in `Node.Descriptor.NodeID` by `Node.initNodeID`. However, the `Node.Descriptor` struct is shared between the store and the node by a pointer passed to `NewStore`. Both store and node access this struct without synchronization (which is fine for everything but the node ID, as the rest of the fields are read-only after construction).

The Store needs to access the NodeDescriptor with proper synchronization, and we may need to do an audit to ensure that all such accesses can handle the possibility of accessing the node descriptor before it is fully initialized. 

The node ID is only set once at startup, and this race is not triggered by our current startup sequence. Changing store initialization as in #16354 exposed the race.

**Comment by a6802739** [comment]
@bdarnell  could I have a try for this?

**Comment by bdarnell** [comment]
This is related to some changes @adamgee is working on in #16371. Let's wait until that's done and see if changes are still needed.

**Comment by a6802739** [comment]
@bdarnell, okay. Got it.

**Comment by cuongdo** [comment]
@ben 1) does this need to go into 1.1? it seems late to be refactoring
2) would this make a good starter (1-2 week) core project?

**Comment by bdarnell** [comment]
Moved to 1.2. I think it would probably be a good core starter project.

**Comment by a6802739** [comment]
@bdarnell, If it's milestones is 1.2, I think we could offer some help here.

**Comment by bdarnell** [comment]
Great, thanks!

**Comment by a6802739** [comment]
@bdarnell , Do you mean we should call use `sync.Once` to initialize the NodeID? 

And what do you mean about synchronization between store and node access? If we don't do anything about this synchronization, what will happen?

**Comment by bdarnell** [comment]
It's more than `sync.Once`. The `NodeDescriptor` is mutable, but we share it between the store and node without any synchronization. This happens to work because the node only writes to the node descriptor once, very early, and the store doesn't do much before then, but it's still not very safe.

We partially solved this with the `base.NodeIDContainer` type. I think the right answer is probably some sort of `NodeDescriptorContainer` struct which could contain the node descriptor and a lock. We'd need to pass this around instead of a `*NodeDescriptor`. I'm not sure whether we can replace NodeIDContainer or not, because of package dependency rules.

**Comment by a-robinson** [comment]
> This happens to work because the node only writes to the node descriptor once, very early, and the store doesn't do much before then, but it's still not very safe.

I haven't yet been able to reproduce the exact code path orderings involved, but not having the `NodeID` when it's needed is behind the somewhat frequent panics in https://github.com/cockroachdb/cockroach/issues/18085

**Comment by arjunravinarayan** [comment]
I'm bumping the milestone on this to 2.1, since it's not making it into 2.0 @a6802739 are you still going to be working on this?

**Comment by a6802739** [comment]
@arjunravinarayan , Sorry for late response, just come back from `Chinese New Year`.
Yes, I'm still working on this.

**Comment by tschottdorf** [comment]
I think we can call this fixed -- `(*Node).start` now first loads the nodeID (allocating one if there isn't one yet) and then touches the stores.
