### ISSUE TITLE
ui: make tooltip icon more visible 

### ISSUE THREAD

**Issue by kuanluo** [cockroachdb/cockroach#16366]
3 out of 5 people in we interviewed missed the tooltips. The suggestion is to make it next to the title, and slightly larger (16px, with 12px font).

![image](https://user-images.githubusercontent.com/1486483/26848825-ce551ece-4acf-11e7-82e8-524dc0179dd2.png)

**Comment by dianasaur323** [comment]
I think this is a good idea, and unlikely to take a long time to implement. I made it 1.1 for now, and perhaps @mrtracy can take a look?
