### ISSUE TITLE
server: dynamically adjust GOGC when heap gets large

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#16368]
As seen in #16320, the behavior of the Go GC can lead to excessive amounts of "idle" memory when the heap gets large. Go GC has a single tunable, the GC percent (set via the `GOGC` env var or `debug.SetGCPercent`). The default value is 100. A collection is triggered when the ratio of freshly allocated data to live data remaining after the previous collection reaches this percentage. For example, if there was 1 GB of live data at the end of the previous GC cycle, the next cycle wouldn't start until the heap grows to 2 GB. 

When the heap is smallish, the overhead here isn't problematic. For example, with 500 MB of live data the heap will grow to 1 GB in size before GC kicks in. But when the heap is multiple GBs the overhead is significant. The default value of `--max-sql-memory` is 25% of physical memory. But the GC behavior means the Go heap might temporarily use 50% of physical memory.

Setting `GOGC` lower by default has a measurable performance impact (TBD, but anecdotally I've seen this in the past). As an alternative, we can dynamically adjust the GC percent value based on the heap size to constrain the overhead. We already periodically retrieve the heap size in `server/status/runtime.go:RuntimeStatSampler.SampleEnvironment()`.

**Comment by RaduBerinde** [comment]
I like the idea of tweaking it only when usage goes above a certain threshold (e.g. half of `--max-sql-memory`). Unfortunately, the usage can spike suddenly when a big query comes in so we may not be responsive enough.

**Comment by petermattis** [comment]
Doing this relies on go1.9 (otherwise `SetGCPercent` implies a stop-the-world GC) which we're not using yet.

**Comment by petermattis** [comment]
The Go folks are experimenting with a `runtime.SetMaxHeap` setting. I don't think we should do anything in this area that would be hacky. Let's just wait for that functionality to arrive.

**Comment by tschottdorf** [comment]
@petermattis I think you've tossed several A-server issues into the CF&S project (unfortunately Github doesn't emit events for that). I understand why you did that, but at the moment I own only `A-core-*`. So if you think `server` belongs to CF&S (I really think CF&S already owns enough stuff, but I also agree that we de facto do own it) then that label should be renamed `A-core-server`.

**Comment by petermattis** [comment]
@tschottdorf Yes, I did do that. I agree that CF&S already owns enough stuff, but not associating `A-server` with CF&S leaves those issues in limbo. Let's rename the label.
