### ISSUE TITLE
sqlbase: panic in RowFetcher.finalizeRow()

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#16379]
https://sentry.io/cockroach-labs/cockroachdb/issues/286804754/

```
*errors.errorString: *errors.errorString v3.go:353
  File "github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go", line 353, in func1
  File "github.com/cockroachdb/cockroach/pkg/sql/executor.go", line 499, in func1
  File "github.com/cockroachdb/cockroach/pkg/sql/sqlbase/rowfetcher.go", line 595, in finalizeRow
  File "github.com/cockroachdb/cockroach/pkg/sql/sqlbase/rowfetcher.go", line 542, in NextRow
  File "github.com/cockroachdb/cockroach/pkg/sql/sqlbase/rowfetcher.go", line 552, in NextRowDecoded
...
(24 additional frame(s) were not displayed)

*errors.errorString v3.go:353
```

Stack trace points to:

```
        panic("Non-nullable column with no value!")
```

cc @danhhz

**Comment by knz** [comment]
https://sentry.io/cockroach-labs/cockroachdb/issues/286804754/

**Comment by vivekmenezes** [comment]
Was a schema change running while this was happening

**Comment by knz** [comment]
The stack trace doesn't say

**Comment by vivekmenezes** [comment]
No I meant was there an ongoing schema change in the background (add/drop column)? When we're adding/deleting a column that is NON Nullable we temporarily make it nullable during the rollout of the backfill. Just wondering if that is failing here.

**Comment by vivekmenezes** [comment]
I think at a minimum we should dump the table descriptor and column descriptor in this panic to start with?

**Comment by knz** [comment]
The Sentry reports are generated by auto-reporting from user clusters. There is no more information provided about the panic than the stack trace, version number and a couple of other build-related details. In particular there is (currently) no detail about other ongoing activities in the cluster.

**Comment by knz** [comment]
cc @dt for suggested additions to the panic report

**Comment by vivekmenezes** [comment]
assigning to @RaduBerinde because he is making lots of optimization here at the moment. Perhaps you an add more table descriptor information to the panic without compromising user privacy. Thanks!

**Comment by RaduBerinde** [comment]
We should never be reading columns that are in the progress of backfilling, no? I thought those are not visible to queries until the backfill is complete.

**Comment by vivekmenezes** [comment]
We allow reading a non-nullable column when the column is also a part of a new index. Whenever we try to generate an index entry during an update for instance the update reads the column entry.

But this not a problem because we deliberately set the column as nullable during the backfill process so I don't know how this panic can happen. Unless you have a better idea its probably better to just print the schema in the panic and wait till we see it again.

**Comment by RaduBerinde** [comment]
I don't think it's safe to send out the schema to Sentry.

**Comment by RaduBerinde** [comment]
Maybe with some anonimizing of column names that would be ok? @dt what do you think?

**Comment by dt** [comment]
I think we should avoid sending column names. We could potentially try to include column descriptors after the reflection de-string-ifier rips over them, but my first reaction is to take a very conservative approach to adding to our data collection.

**Comment by petermattis** [comment]
I agree we should be conservative in adding to our data collection. 

Enhancing the panic is only one approach to fixing this issue. Code inspection and an attempt to trace through the various possibilities for how this panic could have occurred have allowed similar bugs to be fixed recently. So how could this assertion have been tickled? Can we set up similar conditions in a test?

**Comment by jordanlewis** [comment]
cc @mjibson did you look at something similar to this?

**Comment by petermattis** [comment]
Specifically, #18076 had the same error.

**Comment by mjibson** [comment]
This could be the second error listed in https://github.com/cockroachdb/cockroach/issues/22924 which is caused by data being split mid row. Did this happen again?

**Comment by vivekmenezes** [comment]
this is panic reported by sentry last June. We're just wondering if this
could have been seen due to an IMPORT

**Comment by mjibson** [comment]
Yes, definitely. IMPORT was causing exactly this kind of thing. I think it could have happened in June.

**Comment by knz** [comment]
Ok cool so this has been addressed. Closing.
