### ISSUE TITLE
cli: show message on start if anonymous usage details are sent

### ISSUE THREAD

**Issue by WhiteTrashLord** [cockroachdb/cockroach#16389]
Please add a message which indicates if the reporting of anonymous usage details is turned on or off when Cockroach starts.

I want to know if my env setting really worked.

**Comment by benesch** [comment]
Thanks for the suggestion! We're working on improving the transparency of our anonymous reporting more broadly—feel free to join in on the discussion at #16298.

It's not clear exactly what steps we'll take yet, but it's likely this will be one of them. (If not, we'll close this issue with rationale.)

**Comment by bdarnell** [comment]
There are a couple of ways that you can verify that the environment variable has worked.  First
, once the cluster is running, you can query for the diagnostic reporting setting:

```
root@:26257/> SHOW CLUSTER SETTING diagnostics.reporting.enabled;
+-------------------------------+
| diagnostics.reporting.enabled |
+-------------------------------+
| false                         |
+-------------------------------+
(1 row)
```

Second, in the log file, if there are any environment variables that are changing the operation of the server, we print them out like this (so if you misspelled the variable name, for example, this line would be missing):

    I170607 16:47:21.640032 11 cli/start.go:342  using local environment variables: COCKROACH_SKIP_ENABLING_DIAGNOSTIC_REPORTING=1

**Comment by dianasaur323** [comment]
Perhaps we can make this more clear in the docs. @jseldess Do you mind taking a look?

**Comment by jseldess** [comment]
Just opened a docs PR to address this, @dianasaur323.

**Comment by jseldess** [comment]
In docs PR https://github.com/cockroachdb/docs/pull/1548, I made the various opt-out options more explicit, and explained how to verify that opt-out worked. Closing this.
