### ISSUE TITLE
sql: support AT TIME ZONE for tz casts

### ISSUE THREAD

**Issue by leonardb** [cockroachdb/cockroach#16382]
Feature Request

Description:
pgsql supports casting timestamp with time zone into any other time zone.
```
select NOW() AT TIME ZONE 'America/New_York'
```
We run all our postgres servers configure for UTC, and heavily use the casting mechanisms when reading data to display/export data in user-specific time zones, as well as with range queries using timestamps.

```
SELECT * from report where tstamp >= user_tz_to_utc($1, $2) and tstamp < next_day(user_tz_to_utc($1, $3))
```
where:
* $1 is the user id
* $2 is start tstamp (local to user)
* $3 is end tstamp (local to user)
* user_tz_to_utc/2 converts the tstamp from user's configured TZ to UTC
* next_day sets a UTC tstamp to 00:00:00 the following day

**Comment by leonardb** [comment]
Hi @bdarnell 

Thanks for the follow up. Unfortunately this means **connections** are now TZ specific so does not really work as a work-around where we use connection pooling.

If the option time zone could be set within a transaction it might be feasible.

Thanks,
Leonard

**Comment by bdarnell** [comment]
You can change the time zone as often as you want, so to use this workaround you'd need to set the time zone in each transaction that does anything time-zone related. (it's not reset when the transaction ends, so if any transaction changes it, all transactions have to)

**Comment by tlvenn** [comment]
Hi Guys,

Is there any chance to support this fairly soon ?

I store all our dates in `TIMESTAMP` and I usually deal with timezone conversion in my code however I now need to run some aggregate queries which implies that I need to convert the dates to the correct timezone before I aggregate and therefore I really need the `at timezone` support.

Thanks a lot in advance !

**Comment by tlvenn** [comment]
I guess for now, I will aggregate on my side ;)

**Comment by knz** [comment]
@tlvenn as a workaround, is there no way for you to do the conversion inside SQL via a conversion to int, add the offset (in seconds) and then back to timestamp?

**Comment by tlvenn** [comment]
@knz I dont think it's doable with DST as soon as your range is crossing over.

**Comment by tlvenn** [comment]
yes you are right @knz my bad, this can be used as a workaround. Not enough sleep and too much RRULE logic lately... ;)

**Comment by tlvenn** [comment]
Coming back to this topic to check if there is any chance to prioritize this a tiny bit. For anyone dealing with timezones, the current lack of timezone related functions in CDB is pretty painful.

Thanks in advance.
