### ISSUE TITLE
sql: allow specifying namespaced types

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#16395]
`psql` emits the following query when you try to describe a table with `\d foo`:

```
SELECT c.relchecks, c.relkind, c.relhasindex, c.relhasrules, c.relhastriggers, c.relrowsecurity, c.relforcerowsecurity, c.relhasoids, '', c.reltablespace, CASE WHEN c.reloftype = 0 THEN '' ELSE c.reloftype::pg_catalog.regtype::pg_catalog.text END, c.relpersistence, c.relreplident
FROM pg_catalog.pg_class c
 LEFT JOIN pg_catalog.pg_class tc ON (c.reltoastrelid = tc.oid)
WHERE c.oid = '3546415663';
```

We currently don't support specifying types with namespaces, such as `pg_catalog.text`. We may want to add a trivial amount of support for this kind of specification to improve compatibility.

**Comment by dianasaur323** [comment]
@jordanlewis Do you mind explaining if this is a compatibility issue related to ORMs, GUIs or just everything in general? Trying to get a sense for how often and in what situations this issue would occur.

**Comment by jordanlewis** [comment]
It's a compatibility issue related to any client program that uses this syntax. So far I've only observed it to be used by `psql`. This is not a high priority task.

**Comment by jordanlewis** [comment]
@rohany did this get fixed?

**Comment by rohany** [comment]
This is possible now, but some work will need to be done for type resolution on these virtual schemas.

**Comment by jordanlewis** [comment]
It would be cool to get just the `pg_catalog` prefix done if it's easy, as that comes up from time to time in ORM compat stuff.

**Comment by rohany** [comment]
Yeah it seems pretty easy. I'll take a look this week.
