### ISSUE TITLE
sql: DROP USER is missing

### ISSUE THREAD

**Issue by dimsmol** [cockroachdb/cockroach#16391]
`CREATE USER` is supported, but `DROP USER` is surprisingly missing

**Comment by benesch** [comment]
Marking as `helpwanted` unless you object, @mberhault. Seems like a good project for a first time contributor.

**Comment by stevencnix** [comment]
I'll give this a go. However this is my first time so if some one manages to get it before me no hard feelings.

**Comment by benesch** [comment]
Sounds great, @stevencnix! Please don't hesitate to ping us on Gitter if you get stuck.

**Comment by stevencnix** [comment]
I don't think I am going to be able to do this right now. I need to better learn GO, the scripts, and CockroachDB overall first.

**Comment by benesch** [comment]
No problem, @stevencnix. Thanks for the heads up.

**Comment by mpoornima** [comment]
@benesch Can you assign this to me. I've been going through the source and I think I have figured out where all changes need to be done. Thanks.

**Comment by benesch** [comment]
@mpoornima, afraid we can't assign issues to folks who aren't a member of the cockroachdb organization. Your comment here is enough to indicate you're working on it, though—and thanks for the help!

**Comment by mpoornima** [comment]
@benesch I've opened a PR. Please have a look at https://github.com/cockroachdb/cockroach/pull/16442

**Comment by knz** [comment]
Fixed by #16442
