### ISSUE TITLE
sql/pgwire: wrong protocol state after COPY FROM error

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#16393]
Our pgwire implementation seems to get out of sync with `psql` when a `COPY FROM` operation returns an error half way through:

```
test=> create table z(a int);
CREATE TABLE
test=> copy z(a) from stdin;
Enter data to be copied followed by a newline.
End with a backslash and a period on a line by itself.
>> not an int
>> \.
ERROR:  could not parse 'not an int' as type int: strconv.ParseInt: parsing "not an int": invalid syntax
message type 0x5a arrived from server while idle
```

In that example, the connection seems to stay in sync after receiving the unexpected message. In this next example, the connection gets hopelessly confused until I close and re-open `psql`:

```
test=> copy z(a) from stdin;
Enter data to be copied followed by a newline.
End with a backslash and a period on a line by itself.
>> 1 2
>> \.
ERROR:  could not parse '1 2' as type int: strconv.ParseInt: parsing "1 2": invalid syntax
test=> select * from z;
test=> ;
 a
---
(0 rows)

test=> select * from z;
test=> ;
 a
---
(0 rows)
```

Notice that the results from each `select` don't return until i send another `;` to the server.

**Comment by knz** [comment]
Dup #16392.

**Comment by jordanlewis** [comment]
This is not a dupe! this is a bug, the other one is a feature request as you pointed out.

**Comment by knz** [comment]
Woops I had not seen that you were using the pg client here. My bad.
