### ISSUE TITLE
misleading AWS deployment instructions in Docs

### ISSUE THREAD

**Issue by komuW** [cockroachdb/cockroach#16404]
**BUG REPORT**

1. N/A.

2. Please describe the issue you observed:

- What did you do?
I was following this guide on how to setup cockroachDB in AWS:

https://www.cockroachlabs.com/docs/deploy-cockroachdb-on-aws.html

- What did you expect to see?
I expected the blogpost to describe how you should use the load balancers CNAME

- What did you see instead?
There was this part in the post:
```Launch the built-in SQL client, with the --host flag set to the load balancer's IP address:

cockroach sql \
--certs-dir=certs \
--host=<load balancer IP address>
```                                 

I think that is a bit misleading, because an AWS load-balancer can change the IP-addresses that it has at any point and developers shouldn't rely on that IP address remaining static, instead, developers should only rely on the load-balancers CNAME

**Comment by dianasaur323** [comment]
@komuW Thanks for your report - I updated the title to reflect that the page you are referring to is in docs, and am including @jseldess to take a look.

**Comment by mberhault** [comment]
The docs can be changed to mention "load balancer CNAME" everywhere instead of "load balancer IP address".

**Comment by jseldess** [comment]
Thanks, all. I have a docs issue open to address this: https://github.com/cockroachdb/docs/issues/1534

**Comment by komuW** [comment]
thanks guys.
closing..
