### ISSUE TITLE
sql: support COPY FROM STDIN DELIMITER

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/cockroach#16407]
CockroachDB supports COPY.. STDIN with default tab delimiter.  Many extracts use alternate delimiter such as x0A, comma, and way to specify special character such as E'\t'.   A workaround to replace non default delimiter to the default can work, but this will impact performance of the import.  Some tools with direct connection cannot use the workaround.

Example below from TPC-H orders schema with two rows. 

COPY orders (o_orderkey,o_custkey,o_orderstatus,o_totalprice,o_orderdate,o_orderpriority,o_clerk,o_shippriority,o_comment) FROM STDIN ( DELIMITER E'|');
1|36901|O|173665.47|1996-01-02|5-LOW|Clerk#000000951|0|nstructions sleep furiously among
2|78002|O|46929.18|1996-12-01|1-URGENT|Clerk#000000880|0|foxes. pending accounts at the pending, silent asymptot

The following options are available that could be specified.  Of these, the DELIMITER is requested in this.

    FORMAT format_name
    OIDS [ boolean ]
    FREEZE [ boolean ]
    DELIMITER 'delimiter_character'
    NULL 'null_string'
    HEADER [ boolean ]
    QUOTE 'quote_character'
    ESCAPE 'escape_character'
    FORCE_QUOTE { ( column_name [, ...] ) | * }
    FORCE_NOT_NULL ( column_name [, ...] )
    FORCE_NULL ( column_name [, ...] )
    ENCODING 'encoding_name'

**Comment by rafiss** [comment]
See also #41608

**Comment by rafiss** [comment]
DELIMITER and NULL were added in https://github.com/cockroachdb/cockroach/pull/59790 (21.1)
