### ISSUE TITLE
failed to upgrade from 1.0 to 1.0.1

### ISSUE THREAD

**Issue by zhaohansprt** [cockroachdb/cockroach#16403]
BUG REPORT

Please describe the issue you observed:
OS:  centos 7.1   x64  (not vm)

I want to upgrade 1.0 to 1.0.1 , so  i    `ps aux|grep cock` and  ` kill -9 xxx`  all  cockroach processes and copy  1.0.1 binary( which i downloaded from https://binaries.cockroachdb.com/cockroach-v1.0.1.linux-amd64.tgz)
  to /usr/local/bin/  to overwrite the 1.0 binary ,and finally  stucked with starting the node ` cockroach start --insecure --host=192.168.212.127`

Here's the log from starting :

root@localhost cdb]# cockroach start --insecure --host=192.168.212.127 --port=26257  --http-port=8781 --logtostderr
W170608 15:03:52.183956 1 cli/start.go:585  RUNNING IN INSECURE MODE!

- Your cluster is open for any client that can access 192.168.212.127.
- Any user, even root, can log in without providing a password.
- Any user, connecting as root, can read or write any data in your cluster.
- There is no network encryption nor authentication, and thus no confidentiality.

Check out how to secure your cluster: https://www.cockroachlabs.com/docs/secure-a-cluster.html
I170608 15:03:52.184205 1 cli/start.go:591  CockroachDB CCL v1.0.1 (linux amd64, built 2017/05/25 15:17:49, go1.8.1)
I170608 15:03:52.284639 42 cli/start.go:338  starting cockroach node
I170608 15:03:52.288325 42 storage/engine/rocksdb.go:380  opening rocksdb instance at "/root/cdb/cockroach-data"
I170608 15:03:52.313572 42 server/config.go:436  1 storage engine initialized
I170608 15:03:52.313933 42 server/server.go:672  [n?] sleeping for 473.989659ms to guarantee HLC monotonicity
W170608 15:03:52.917237 208 storage/store.go:1339  [n1,s1,r5/4:/Table/{0-11}] could not gossip system config: [NotLeaseHolderError] r5: replica (n1,s1):4 not lease holder; lease holder unknown
I170608 15:03:52.917262 42 storage/store.go:1252  [n1] [n1,s1]: failed initial metrics computation: [n1,s1]: system config not yet available
I170608 15:03:52.917625 42 server/node.go:467  [n1] initialized store [n1,s1]: {Capacity:53660876800 Available:13235208192 RangeCount:302 LeaseCount:0}
I170608 15:03:52.917690 42 server/node.go:351  [n1] node ID 1 initialized
I170608 15:03:52.917814 42 gossip/gossip.go:297  [n1] NodeDescriptor set to node_id:1 address:<network_field:"tcp" address_field:"192.168.212.127:26257" > attrs:<> locality:<> 
I170608 15:03:52.917969 42 storage/stores.go:296  [n1] read 5 node addresses from persistent storage
I170608 15:03:52.918128 42 server/node.go:608  [n1] connecting to gossip network to verify cluster ID...
I170608 15:03:52.918157 42 server/node.go:633  [n1] node connected via gossip and verified as part of cluster "19786856-8c85-49a9-8af7-d9aa3d220bcf"
I170608 15:03:52.918188 42 server/node.go:405  [n1] node=1: started with [[]=/root/cdb/cockroach-data] engine(s) and attributes []
I170608 15:03:52.918250 42 sql/executor.go:338  [n1] creating distSQLPlanner with address {tcp 192.168.212.127:26257}
I170608 15:03:52.921845 42 server/server.go:735  [n1] starting http server at 192.168.212.127:8781
I170608 15:03:52.921887 42 server/server.go:736  [n1] starting grpc/postgres server at 192.168.212.127:26257
I170608 15:03:52.921913 42 server/server.go:737  [n1] advertising CockroachDB node at 192.168.212.127:26257
W170608 15:03:52.926592 208 storage/store.go:1339  [n1,s1,r5/4:/Table/{0-11}] could not gossip system config: [NotLeaseHolderError] r5: replica (n1,s1):4 not lease holder; lease holder unknown
W170608 15:03:52.942860 208 storage/store.go:1339  [n1,s1,r5/4:/Table/{0-11}] could not gossip system config: [NotLeaseHolderError] r5: replica (n1,s1):4 not lease holder; lease holder unknown
W170608 15:03:52.963361 208 storage/store.go:1339  [n1,s1,r5/4:/Table/{0-11}] could not gossip system config: [NotLeaseHolderError] r5: replica (n1,s1):4 not lease holder; lease holder unknown
W170608 15:03:52.995115 208 storage/store.go:1339  [n1,s1,r5/4:/Table/{0-11}] could not gossip system config: [NotLeaseHolderError] r5: replica (n1,s1):4 not lease holder; lease holder unknown
W170608 15:03:53.047655 208 storage/store.go:1339  [n1,s1,r5/4:/Table/{0-11}] could not gossip system config: [NotLeaseHolderError] r5: replica (n1,s1):4 not lease holder; lease holder unknown
W170608 15:03:53.123095 208 storage/store.go:1339  [n1,s1,r5/4:/Table/{0-11}] could not gossip system config: [NotLeaseHolderError] r5: replica (n1,s1):4 not lease holder; lease holder unknown
W170608 15:03:53.221381 208 storage/store.go:1339  [n1,s1,r5/4:/Table/{0-11}] could not gossip system config: [NotLeaseHolderError] r5: replica (n1,s1):4 not lease holder; lease holder unknown
I170608 15:03:53.290181 345 vendor/google.golang.org/grpc/clientconn.go:806  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp [::1]:27257: getsockopt: connection refused"; Reconnecting to {localhost.localdomain:27257 <nil>}
W170608 15:03:53.295654 343 gossip/client.go:125  [n1] failed to start gossip client to localhost.localdomain:27257: rpc error: code = Unavailable desc = grpc: the connection is unavailable
W170608 15:03:53.397852 208 storage/store.go:1339  [n1,s1,r5/4:/Table/{0-11}] could not gossip system config: [NotLeaseHolderError] r5: replica (n1,s1):4 not lease holder; lease holder unknown
W170608 15:03:53.665005 208 storage/store.go:1339  [n1,s1,r5/4:/Table/{0-11}] could not gossip system config: [NotLeaseHolderError] r5: replica (n1,s1):4 not lease holder; lease holder unknown
W170608 15:03:54.035915 208 storage/store.go:1339  [n1,s1,r5/4:/Table/{0-11}] could not gossip system config: [NotLeaseHolderError] r5: replica (n1,s1):4 not lease holder; lease holder unknown
I170608 15:03:54.289412 388 vendor/google.golang.org/grpc/clientconn.go:806  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 192.168.212.127:26258: getsockopt: connection refused"; Reconnecting to {192.168.212.127:26258 <nil>}
W170608 15:03:54.289462 386 gossip/client.go:125  [n1] failed to start gossip client to 192.168.212.127:26258: rpc error: code = Unavailable desc = grpc: the connection is unavailable
W170608 15:03:54.595546 208 storage/store.go:1339  [n1,s1,r5/4:/Table/{0-11}] could not gossip system config: [NotLeaseHolderError] r5: replica (n1,s1):4 not lease holder; lease holder unknown
I170608 15:03:55.289504 403 vendor/google.golang.org/grpc/clientconn.go:806  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 192.168.212.127:26259: getsockopt: connection refused"; Reconnecting to {192.168.212.127:26259 <nil>}
W170608 15:03:55.289589 33 gossip/client.go:125  [n1] failed to start gossip client to 192.168.212.127:26259: rpc error: code = Unavailable desc = grpc: the connection is unavailable
W170608 15:03:55.485217 208 storage/store.go:1339  [n1,s1,r5/4:/Table/{0-11}] could not gossip system config: [NotLeaseHolderError] r5: replica (n1,s1):4 not lease holder; lease holder unknown
^CI170608 15:03:55.958969 1 cli/start.go:444  received signal 'interrupt'
Note: a second interrupt will skip graceful shutdown and terminate forcefully
I170608 15:03:55.959336 1 cli/start.go:469  initiating graceful shutdown of server
initiating graceful shutdown of server
I170608 15:03:56.289683 380 vendor/google.golang.org/grpc/clientconn.go:806  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 192.168.212.127:27259: getsockopt: connection refused"; Reconnecting to {192.168.212.127:27259 <nil>}
W170608 15:03:56.290040 378 gossip/client.go:125  [n1] failed to start gossip client to 192.168.212.127:27259: rpc error: code = Unavailable desc = grpc: the connection is unavailable
W170608 15:03:56.563643 208 storage/store.go:1339  [n1,s1,r5/4:/Table/{0-11}] could not gossip system config: [NotLeaseHolderError] r5: replica (n1,s1):4 not lease holder; lease holder unknown

**Comment by a-robinson** [comment]
Hi @zhaohansprt, thanks for the report. To clarify, were you running a multi-node cluster? If you previously had multiple nodes running, you'll have to restart a majority of them before the cluster will start working again.

If it really was only a single node cluster, could you try again, let it run for more than the 3-4 seconds your above logs indicate, and upload what happens?

**Comment by zhaohansprt** [comment]
Yes i  made  three nodes  cluster just follow the  [](https://www.cockroachlabs.com/docs/start-a-local-cluster.html)  ,and i killed the three nodes  for upgrading ,but failed to restart the majority of them as the default store path is  

> cockroach-data  can tell 

and such error msgs continully  shows no matter how long it been throuth !
` W170608 15:03:54.035915 208 storage/store.go:1339 [n1,s1,r5/4:/Table/{0-11}] could not gossip system config: [NotLeaseHolderError] r5: replica (n1,s1):4 not lease holder; lease holder unknown`

**Comment by a-robinson** [comment]
I'm sorry, I can't quite understand your past message when you say you "failed to restart the majority of them firstly". Can you be more specific about which nodes you restartd and with what flags?

It's very possible that you've run into #16268, but even that won't prevent your cluster from starting back up if you start all 3 nodes at once.

**Comment by zhaohansprt** [comment]
I  start them asynclly solved

**Comment by a-robinson** [comment]
Good to hear. I'm sorry about the difficulties!
