### ISSUE TITLE
Crashing nodes

### ISSUE THREAD

**Issue by JackHerring** [cockroachdb/cockroach#16419]
Node 1 was the last one to die, reports a 'panic' in the logs. Node 3 also crashed a little while ago but we don't have the same error reported in the logs. Logs attached.

Fyi: @jrote1

[debug.zip](https://github.com/cockroachdb/cockroach/files/1063413/debug.zip)

**Comment by JackHerring** [comment]
Here is a log for node 3 crashing
[debug.zip](https://github.com/cockroachdb/cockroach/files/1064151/debug.zip)

**Comment by jordanlewis** [comment]
Thanks for the report.

I believe this is #15950 - https://sentry.io/cockroach-labs/cockroachdb/issues/274120395/events/5779014820/

**Comment by tschottdorf** [comment]
@JackHerring, could you by any chance share the workload you were running? We're aware of this bug but so far haven't managed to reproduce it in our tests.

**Comment by JackHerring** [comment]
We are running 3 nodes with 1 core and 1gb of RAM. We were then inserting,updating and reading about 50 times a second for sustained time and the first node died when the table got to about 250mb. We not longer have the exact data as we reset everything as the nodes were even crashing when trying to delete when the table size was 500mb with 1mil rows.

**Comment by tschottdorf** [comment]
Could you share (prototypes of) the queries you were running? Apologies if they're already somewhere, but I believe not.

**Comment by petermattis** [comment]
@JackHerring To add to what @tschottdorf said, the crash is due to an assertion failure in a data structure but so far we've been unable to figure out why the assertion is failing. We've only 4 instances of this assertion failure (and never in our own tests or test clusters). It's likely that you won't experience the problem again, but there is a small chance it is related to your workload so any additional details you can provide would be useful.

**Comment by JackHerring** [comment]
@petermattis We work work on replicating this again and will get back to you if we do and if not will give you what we are doing

**Comment by petermattis** [comment]
@JackHerring Thanks. I'm going to take another whack at stressing the code in question to see if I can reproduce locally.

**Comment by jrote1** [comment]
@petermattis I guess I must be unlucky as my home clusters randomly crashes all the time and test one work with @JackHerring haha

**Comment by petermattis** [comment]
@jrote1 Thanks for trying to reproduce. I believe I fixed this issue (and #15950) earlier today. The problem was bad accounting for an in-memory data structure which triggered the assertion. The fix will be going into 1.0.3 which will come out in a few weeks.
