### ISSUE TITLE
sql: AS OF SYSTEM TIME should support at least `current_timestamp() - INTERVAL X

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#16424]
`AS OF SYSTEM TIME` currently can only take constant expressions (i.e. '2017-09-09' but not `current_timestamp()`). This is because at the time at which the expr is evaluated, much of the evaluation context is not yet available.

We should at least allow `current_timestamp()` be used on top of that. That is hopefully straightforward and enables the most likely use case for `AS OF SYSTEM TIME`: reading something slightly in the past.

At the time of writing, our enterprise backup docs do that, though I'm about to fix them.

**Comment by tschottdorf** [comment]
Once fixed, should undo https://github.com/cockroachdb/docs/pull/1549.

**Comment by andreimatei** [comment]
+1. It's very surprising how limited the what we accept for the time in AOST is.
