### ISSUE TITLE
sql: `CREATE TABLE` returns retryable error; should retry internally

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#16450]
When a statement is run outside of a transaction (i.e. in an implicit auto-commit transaction), the server is supposed to be responsible for handling any retryable errors (since it has the entire transaction available for the retry). This doesn't appear to be working for `CREATE TABLE` statements, as seen in #15733. I can't be sure that this is limited to `CREATE TABLE`. That's the only place where I've been seeing it, but in these tests errors in other statements aren't logged as visibly. 

`org.postgresql.util.PSQLException: ERROR: restart transaction: HandledRetryableTxnError: TransactionRetryError: retry txn "sql txn" id=f9637e48 key=/Table/0/0 rw=true pri=0.01474274 iso=SERIALIZABLE stat=PENDING epo=0 ts=1494037334.449734196,1 orig=1494037332.150969729,0 max=1494037332.151492593,0 wto=false rop=false seq=6`

@andreimatei is it expected that a "handled" retryable error would make it out to the client like this?

**Comment by jordanlewis** [comment]
I believe this is also the cause of the flakiness in the examples orms tests in #16200 and others.

**Comment by andreimatei** [comment]
If the statement is an implicit transaction, then indeed I don't think this error should escape to the client. Let me see if I can repro with the jepsen scripts. Or do you think it's easy to repro with one of the other tests?

**Comment by andreimatei** [comment]
I'm able to repro about half the time with the Jepsen `sets` test, but not very reliably. Figuring out how to have the test run an instrumented binary and looking.

**Comment by bdarnell** [comment]
If you push a branch to the main cockroachdb/cockroach repo and then trigger the jepsen tests on that branch with teamcity, it will run with a build from that branch (it'll take two hours because it runs all the tests, but a full run is almost certain to hit this error a couple of times)

**Comment by andreimatei** [comment]
I've made the sqlalchemy test working under stress, and I'm able to reproduce that failure. In the case of that test, the `create table` statement is done in a client transaction, so at a first approximation, it's not illegal for the retryable error to make it to the client. @bdarnell, do you know if that transaction is avoidable with sqlalchemy?

The error is due to the fact that the `create table` transaction has been pushed, likely by the split of an early range that takes up much of the initial key space (`{System/tse-Max}`). Perhaps the split is caused by the recent creation of a previous table.
I don't know if this push is surprising or not. We don't generally push transactions any more, but perhaps a split is still expected to do some pushes? I'll continue investigating exactly what the txn conflict is.

**Comment by bdarnell** [comment]
> do you know if that transaction is avoidable with sqlalchemy?

It seems like it should be, but I can't find where that transaction is coming from. 

If it's in a (multi-step) client transaction, then it's legitimate to let this error escape. That's really unfortunate, though, since it means injecting retry loops into a lot more places for things like this (unless we can disable the transaction completely).

In the clojure example, I believe we were seeing this happen *without* a client-side transaction, although I didn't verify this with wireshark. 

Was the transaction actually pushed or did it run into the timestamp cache? The former would be a surprise to me, but the latter seems more likely.

**Comment by andreimatei** [comment]
> Was the transaction actually pushed or did it run into the timestamp cache? The former would be a surprise to me, but the latter seems more likely.

Well I can tell you that someone did send a `PushTxn` request at some point, but it could be unrelated to our txn. And I can also tell you that the "retry reason" of the `TxnRetryError` is `RETRY_SERIALIZABLE`. And that it's generated on `COMMIT`; if the txn would have run into the timestamp cache, would that have result in an error immediately, or at commit time?

**Comment by bdarnell** [comment]
Yes, the timestamp cache would have resulted in an error immediately. So something's sending a PUSH_TIMESTAMP PushTxn, which means a read encountering a WriteIntentError. 

How exactly did you run this under stress? Adding `--vmodule=replica_command=1` will show a little more detail about pushes. We're not supposed to push any more unless there's a deadlock. Could a split deadlock with a table creation? I hope not, but I'd have to trace through both transactions to be sure.

**Comment by andreimatei** [comment]
As we discussed, the timestamp cache will not, in fact, give you an error immediately; the error will be deferred to the commit. And it appears that it is indeed the timestamp cache that sometimes bumps the timestamp of the `CREATE TABLE` txn.

I'm able to reproduce this easily in a test doing concurrent table creations in explicit transactions. I have not been able to reproduce in the same test by doing non-transactional table creations - so my hope is still that the Jepsen test, and everybody else experiencing this error, is using explicit transactions.
In any case, for now investigating these explicit transactions.

I'm able to produce two types of retryable errors:
1. When creating tables with different names, the increment on the shared counter use to get new descriptor ids can fail with a WriteTooOldError (that's swallowed and resurfaced at commit time).
2. When creating tables with the same name, the timestamp cache can detect a conflict on the entry mapping the table name to a descriptor id.

The previous speculations about a split causing a create to fail have not been seen yet. Although they probably can happen too.

For 1), I think we should do that counter increment non-transactionally. And if we burn some ids that will not actually be used for a descriptor, so be it.
For 2), and in general for various other possible retryable errors that a CREATE TABLE might encounter, Ben had an interesting suggestion - we could automatically retry the first statement sent after a `BEGIN`, even if it is not sent in the same batch of statements with the `BEGIN` (currently we only retry automatically the batch with the `BEGIN` in it). The reasoning here is that the client logic that issues the first query is not conditional on anything read in the transaction.

I'll work on these things.

**Comment by vivekmenezes** [comment]
1. is related to https://github.com/cockroachdb/cockroach/issues/13180

**Comment by jordanlewis** [comment]
I can confirm that the SQLAlchemy ORM test does in fact generate all of its `CREATE TABLE` DDLs within a transaction. Here's the log with `--vmodule=executor=2`:

```I170621 23:47:07.645964 444 sql/executor.go:1021  [client=[::1]:52128,user=root,n1] executing 1/1: BEGIN TRANSACTION
I170621 23:47:07.645977 444 sql/executor.go:1204  [client=[::1]:52128,user=root,n1] BEGIN TRANSACTION
I170621 23:47:07.646002 444 sql/executor.go:1204  [client=[::1]:52128,user=root,n1] BEGIN done
I170621 23:47:07.646122 444 sql/executor.go:634  [client=[::1]:52128,user=root,n1] execRequest: SHOW TABLES
I170621 23:47:07.646155 444 sql/executor.go:1021  [client=[::1]:52128,user=root,n1] executing 1/1: SHOW TABLES
I170621 23:47:07.646173 444 sql/executor.go:1204  [client=[::1]:52128,user=root,n1] SHOW TABLES
I170621 23:47:07.647142 444 sql/executor.go:1643  [client=[::1]:52128,user=root,n1] query not supported for distSQL: unsupported node *sql.delayedNode
I170621 23:47:07.647167 444 sql/executor.go:1204  [client=[::1]:52128,user=root,n1] SHOW TABLES (0 results) done
I170621 23:47:07.647482 444 sql/executor.go:634  [client=[::1]:52128,user=root,n1] execRequest: SHOW TABLES
I170621 23:47:07.647507 444 sql/executor.go:1021  [client=[::1]:52128,user=root,n1] executing 1/1: SHOW TABLES
I170621 23:47:07.647518 444 sql/executor.go:1204  [client=[::1]:52128,user=root,n1] SHOW TABLES
I170621 23:47:07.648226 444 sql/executor.go:1643  [client=[::1]:52128,user=root,n1] query not supported for distSQL: unsupported node *sql.delayedNode
I170621 23:47:07.648249 444 sql/executor.go:1204  [client=[::1]:52128,user=root,n1] SHOW TABLES (0 results) done
I170621 23:47:07.648459 444 sql/executor.go:634  [client=[::1]:52128,user=root,n1] execRequest: SHOW TABLES
I170621 23:47:07.648486 444 sql/executor.go:1021  [client=[::1]:52128,user=root,n1] executing 1/1: SHOW TABLES
I170621 23:47:07.648497 444 sql/executor.go:1204  [client=[::1]:52128,user=root,n1] SHOW TABLES
I170621 23:47:07.649187 444 sql/executor.go:1643  [client=[::1]:52128,user=root,n1] query not supported for distSQL: unsupported node *sql.delayedNode
I170621 23:47:07.649210 444 sql/executor.go:1204  [client=[::1]:52128,user=root,n1] SHOW TABLES (0 results) done
I170621 23:47:07.649454 444 sql/executor.go:634  [client=[::1]:52128,user=root,n1] execRequest: SHOW TABLES
I170621 23:47:07.649484 444 sql/executor.go:1021  [client=[::1]:52128,user=root,n1] executing 1/1: SHOW TABLES
I170621 23:47:07.649504 444 sql/executor.go:1204  [client=[::1]:52128,user=root,n1] SHOW TABLES
I170621 23:47:07.650257 444 sql/executor.go:1643  [client=[::1]:52128,user=root,n1] query not supported for distSQL: unsupported node *sql.delayedNode
I170621 23:47:07.650280 444 sql/executor.go:1204  [client=[::1]:52128,user=root,n1] SHOW TABLES (0 results) done
I170621 23:47:07.651091 444 sql/executor.go:634  [client=[::1]:52128,user=root,n1] execRequest:
CREATE TABLE customers (
	id INTEGER DEFAULT unique_rowid() NOT NULL,
	name VARCHAR,
	PRIMARY KEY (id)
)

I170621 23:47:07.651197 444 sql/executor.go:1021  [client=[::1]:52128,user=root,n1] executing 1/1: CREATE TABLE customers (id INTEGER NOT NULL DEFAULT unique_rowid(), "name" VARCHAR, PRIMARY KEY (id))
I170621 23:47:07.651221 444 sql/executor.go:1204  [client=[::1]:52128,user=root,n1] CREATE TABLE customers (id INTEGER NOT NULL DEFAULT unique_rowid(), "name" VARCHAR, PRIMARY KEY (id))
I170621 23:47:07.651517 444 sql/executor.go:1643  [client=[::1]:52128,user=root,n1] query not supported for distSQL: unsupported node *sql.createTableNode
I170621 23:47:07.654768 444 sql/executor.go:1204  [client=[::1]:52128,user=root,n1] CREATE TABLE done
I170621 23:47:07.654988 444 sql/executor.go:634  [client=[::1]:52128,user=root,n1] execRequest: COMMIT
I170621 23:47:07.655023 444 sql/executor.go:1021  [client=[::1]:52128,user=root,n1] executing 1/1: COMMIT TRANSACTION
I170621 23:47:07.655035 444 sql/executor.go:1204  [client=[::1]:52128,user=root,n1] COMMIT TRANSACTION
I170621 23:47:07.655889 444 sql/event_log.go:101  [client=[::1]:52128,user=root,n1] Event: "create_table", target: 51, info: {TableName:customers Statement:CREATE TABLE customers (id INTEGER NOT NULL DEFAULT unique_rowid(), "name" VARCHAR, PRIMARY KEY (id)) User:root}```

**Comment by bdarnell** [comment]
> For 1), I think we should do that counter increment non-transactionally. And if we burn some ids that will not actually be used for a descriptor, so be it.

SGTM

> 2 When creating tables with the same name, the timestamp cache can detect a conflict on the entry mapping the table name to a descriptor id.

In this case, the table creation is going to fail no matter what, right? It's just a question of which error is returned? Although I guess it could be a problem for CREATE IF NOT EXISTS. 


Also, I took a closer look at what clojure is doing and it does indeed wrap everything in a transaction by default. There doesn't appear to be any concurrency, but the split race could probably explain the retry errors.

**Comment by andreimatei** [comment]
> In this case, the table creation is going to fail no matter what, right? It's just a question of which error is returned? Although I guess it could be a problem for CREATE IF NOT EXISTS.

Right.

> Also, I took a closer look at what clojure is doing and it does indeed wrap everything in a transaction by default. There doesn't appear to be any concurrency, but the split race could probably explain the retry errors.

By Clojure you mean the Jepsen tests, right?

**Comment by jordanlewis** [comment]
Does "first batch" in the closing PR correspond to "first SQL statement" only? If so, neither this nor #16200 should have been closed.

The offending `CREATE TABLE` statement actually occurs after several `SHOW TABLES` statements in the transaction generated by SQLAlchemy.

**Comment by andreimatei** [comment]
The "first batch" refers to the first batch of statements after a trailing `BEGIN`.
I missed all the `SHOW` statements done by sqlalchemy. It's not doing them in the `CREATE TABLE` batch, so indeed this PR won't help. And I guess neither can anything else on the crdb side; if the client is doing reads, it needs to drive the retries. Do you think we can customize it to do so?

Anywho, let's hope that the other improvements made recently about making `CREATE TABLE` less likely to get a retryable error will make our tests not flake any more. If they do, we can reopen #16200.
This current issue I think can stay closed; it outlived its usefulness.

**Comment by jordanlewis** [comment]
Sounds good!
