### ISSUE TITLE
sql: support `SET datestyle TO ISO` (its absence makes some pg client libs fail on start)

### ISSUE THREAD

**Issue by dimsmol** [cockroachdb/cockroach#16452]
Some popular PostgreSQL client libs execute `SET datestyle TO ISO` right after connecting to database, for instance `postgresql-simple` does [this](https://github.com/lpsmith/postgresql-simple/blob/be85ee90b35a35f5de099d820cd18c7239c4eea0/src/Database/PostgreSQL/Simple/Internal.hs#L238):

```haskell
let settings
      | version < 80200 = "SET datestyle TO ISO;SET client_encoding TO UTF8"
      | otherwise       = "SET datestyle TO ISO;SET client_encoding TO UTF8;SET standard_conforming_strings TO on"
_ <- execute_ wconn settings
```

Currently `SET datestyle TO ISO` fails with `unknown variable: "datestyle"`, preventing such client libs to connect.

Supporting this command with the only option `ISO` should be easy (the command should effectively does nothing) and would definitely help.

**Comment by jordanlewis** [comment]
Thanks! We'll get to this at some point - in the meantime if you or anyone else feels like taking this one on, contributions are very welcome and this should be a pretty straightforward patch.

See #10087 for a very similar addition.

**Comment by jordanlewis** [comment]
Since that patch we've moved where these variables live actually, but the patch should still be straightforward. Have a look at [`pkg/sql/vars.go`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/vars.go#L182) - the setting for `standard_conforming_strings` for instance should be quite similar to this as we only support one setting for it.

**Comment by dimsmol** [comment]
[client_encoding](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/vars.go#L262) is even better example. The new one should be basically the same, but ensure the value is `ISO`.
Not sure if it should uppercase before checking, though.

**Comment by asitm9** [comment]
I will try to fix it.

**Comment by asitm9** [comment]
I have created a pull request [](https://github.com/cockroachdb/cockroach/pull/16557). 
This is my very first commit, so please bear with me.

**Comment by mattnenterprise** [comment]
Should this be closed since https://github.com/cockroachdb/cockroach/pull/16557 has been merged ?

**Comment by knz** [comment]
Yes it should be closed. Thanks!
