### ISSUE TITLE
storage: 1.0.1: a snapshot application was attempted outside of the streaming snapshot codepath

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#16460]
https://sentry.io/cockroach-labs/cockroachdb/issues/292210580/

```
*errors.errorString: replica.go:2769 programming error: a snapshot application was attempted outside of the streaming snapshot codepath
  File "github.com/cockroachdb/cockroach/pkg/storage/replica.go", line 2769, in handleRaftReadyRaftMuLocked
  File "github.com/cockroachdb/cockroach/pkg/storage/replica.go", line 2710, in handleRaftReady
  File "github.com/cockroachdb/cockroach/pkg/storage/store.go", line 3409, in processReady
  File "github.com/cockroachdb/cockroach/pkg/storage/scheduler.go", line 217, in worker
  File "github.com/cockroachdb/cockroach/pkg/storage/scheduler.go", line 168, in func2
...
(1 additional frame(s) were not displayed)

replica.go:2769 programming error: a snapshot application was attempted outside of the streaming snapshot codepath
```

**Comment by tschottdorf** [comment]
Assertion is from https://github.com/cockroachdb/cockroach/pull/9292

**Comment by tschottdorf** [comment]
https://sentry.io/cockroach-labs/cockroachdb/issues/292210585/

Seems related. Probably from the same cluster in much the same moment. This assertion from HandleSnapshot.

**Comment by jordanlewis** [comment]
I did add that assertion - I'll take a look, but as far as I know the snapshot code has changed a ton since I last looked at it, so I might not be the right investigator for this one.

**Comment by tschottdorf** [comment]
Yeah, feel free to reassign. Maybe toss it to @petermattis for triage.

**Comment by jordanlewis** [comment]
So this panic is triggered in the `handleRaftReadyRaftMuLocked` when `raftGroup.Ready()` returns a `Ready` with a populated raft snapshot, but we're processing an ordinary raft message that was sent via `HandleRaftRequest`. We never expect snapshots to be sent via the normal Raft RPC - they must all be sent via the streaming RPC.

I believe this panic is caused by a bug that allows raft messages with snapshots to be sent over the normal, non-streaming RPC.

Definitely could use @petermattis's eyes on this as I'm not familiar with the new raft snapshot queue.

**Comment by petermattis** [comment]
Raft initiated snapshots are always sent via the `raftSnapshotQueue`. The logic in `Replica.sendRaftMessage` is simple to follow. I don't see how this is happening. We could move the assertions higher in the stack. For example, `RaftTransport.SendAsync` could verify the message is not a snapshot. And `RaftTransport.handleRaftRequest` could perform a similar check.

**Comment by petermattis** [comment]
`RaftTransport.SendAsync` already has this assertion:

```
	if req.Message.Type == raftpb.MsgSnap {
		panic("snapshots must be sent using SendSnapshot")
	}
```

So somehow we a `raft.Ready` contains what appears to be a Raft-initiated snapshots even though that snapshot was not over the wire. @bdarnell any thoughts?

**Comment by bdarnell** [comment]
One possibility for rare events like this is that someone's fuzzing the server, sending us messages that we did not actually generate (so this should be an error, not a panic). But I think it's more likely that it's some flaw in the way we're tracking whether we're in the streaming snapshot path or not. There's a lot of distance between the incoming streaming snapshot handling and this `handleRaftReady` call. Is there any way we could pass the snapshot into raft so it gets queued up in the Ready struct without actually calling handleRaftReady (in `Store.processRaftRequest`)? I'm looking but I don't see anything yet.

**Comment by petermattis** [comment]
>  Is there any way we could pass the snapshot into raft so it gets queued up in the Ready struct without actually calling handleRaftReady (in Store.processRaftRequest)? I'm looking but I don't see anything yet.

I don't see anything either. Here's another crazy idea: perhaps `Replica.handleRaftReadyRaftMuLocked` returned an error and the process was panicing. In the process of panicing we released the locks for the `Replica` but the Raft scheduler was already about to process the replica and called `Replica.handleRaftReady` again and encountered the snapshot.

**Comment by petermattis** [comment]
My theory has some legs to it: https://sentry.io/cockroach-labs/cockroachdb/issues/292210585/. Both this event and the one in the original message occurred at the same time.

**Comment by bdarnell** [comment]
Yeah, that seems totally plausible. And errors from handleRaftReady are not that unusual; I think that's where we die if the disk fills up.

**Comment by petermattis** [comment]
Should we be converting various assertion-style panics to `log.Fatal{,f}`? The latter has the benefit of not releasing locks. 

Cc @dt

**Comment by bdarnell** [comment]
Makes sense to me to prefer `log.Fatal` for these.

**Comment by dt** [comment]
of course the different runtime behavior should be the deciding factor, but for the purposes of crash reporting,`log.Fatalf` also gets to include its format message in the crash report, whereas panics include only the callsite and type for now (since they can't be sure if it was sprintf'ed user data or not), so, all else being equal*, log.Fatalf is more useful.

* obviously often isn't.

**Comment by tschottdorf** [comment]
Nothing left to do here, it seems. Reopen if you disagree.
