### ISSUE TITLE
sql: don't unnecessarily add `NOT NULL` constraint when grouping

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#16477]
When doing `SELECT MIN(x)`, if we have an index on `x` we can read only one value. However, this value should not be `NULL`, so we need to add an `x NOT NULL` filter (which in turn affects the span on the index).

If we don't find an index, we still add the filter (this is because the filter is added early and index selection is later). Evaluating this unnecessary filter is overhead in large scans - in one example, about 10% according to a profile of `SELECT MIN(l_extendedprice) FROM tpch.lineitem` query on TPC-H.

**Comment by andy-kimball** [comment]
The cost-based optimizer only adds the filter when it's needed. Closing as "Fixed".
