### ISSUE TITLE
sql: dropping an interleave index causes backreference preventing DDL activities

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/cockroach#16471]
```sql
create table t1 (id1 int primary key, id2 int, id3 int);
create index c on t1 (id2)
   storing (id1,id3)
   interleave in parent t1 (id2);
drop index t1@c;
```

```
x=> drop table t1;
ERROR:  invalid interleave backreference table=t1 index=2: index-id "2" does not exist
x=> drop database x;
ERROR:  invalid interleave backreference table=t1 index=2: index-id "2" does not exist
x=> drop table t1 cascade;
ERROR:  invalid interleave backreference table=t1 index=2: index-id "2" does not exist
```

build:      CCL v1.0.1 @ 2017/05/25 17:12:12 (go1.8.3)

**Comment by dianasaur323** [comment]
@jseldess This seems like awkward behavior. Do you mind documenting it as a known limitation for now?

**Comment by jseldess** [comment]
Sure. Just created an issue: https://github.com/cockroachdb/docs/issues/1589. Unfortunately, we don't yet have broader docs on interleaving secondary indexes, though. We need to add that as well.

**Comment by cuongdo** [comment]
@knz can you please triage?

**Comment by knz** [comment]
Still repros in v1.1-alpha

**Comment by knz** [comment]
The first step of the investigation will be to check whether the problem can yield to schema corruption (e.g. dangling descriptors).

If so please ping back to me to prioritize. 

If the problem cannot yield schema corruption this issue can be considered as a low-pri bugfix (just the error message needs to be improved).
