### ISSUE TITLE
cli: let commands return partial information when run against unavailable/broken clusters

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#16489]
Users expect to be able to get some information after running cockroach node status, even in the case of partitioning or loss of quorum.

It would be helpful to reveal some information from the local node (basically a warning that the node is no longer able to communicate with the rest of the cluster).

**Comment by davibo-oc** [comment]
An example - Cassandra gives a status information in the following form:

```$ nodetool status

Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address    Load       Tokens       Owns    Host ID                               Rack
UN  127.0.0.1  4.08 GiB   1            ?       5e5167f6-94cd-4170-b295-262699afae16  rack1
DN  127.0.0.2  3.17 GiB   1            ?       025d4078-1ede-49ef-a0ae-6a3f5bd497d7  rack1
DN  127.0.0.3  3.98 GiB   1            ?       a54e0391-fa16-4025-acc2-f4bb13214527  rack1
```

Where U and D signals whether a node is reachable. 

The current CockroachDB behaviour when there is a serious problem and the quorum is lost is to hang indefinitely on `cockroach node status` which is a bit unexpected.

**Comment by arjunravinarayan** [comment]
Thanks @davibo-oc for the context. That's very helpful, and appreciated!

**Comment by shawnrichards** [comment]
Hope you guys are going to give this the focus it deserves. Admin functions that fail to respond along with everything else precludes it from use in some of the crisis situations for which it was designed.

**Comment by dianasaur323** [comment]
@shawnrichards thanks for the additional nudge here. Unfortunately, this isn't going to make it into our 1.1 release, but it is slotted for investigation in the 1.2 release.

**Comment by dianasaur323** [comment]
Draft Acceptance Criteria -- Accepting Comments

**Rationale**
Currently, we offer a confusing UX when quorum is lost. Users cannot access the admin UI, and also cannot check node status. 

**Feature Scope**
- [ ] Offer a solution similar to Cassandra - show the liveness of other nodes in the cluster from the perspective of the queried cluster. This could simply be an additional column that shows whether or not a given node can talk to another node. Leaving details of implementation to the engineering team
- [ ] This new column should be part of the generic cockroach node status command (not the cockroach node stats -all command)

**PM Acceptance Testing**
- [ ] Force a cluster to lose quorum
- [ ] Run cockroach node status
- [ ] Force a network partition
- [ ] Run cockroach node status

**Comment by dianasaur323** [comment]
@cuongdo I don't think @mrtracy is the right person to put on this issue anymore given how much is already on his plate. Can we triage to someone else?

**Comment by tschottdorf** [comment]
Also: time out after trying for a while.

**Comment by tschottdorf** [comment]
In my opinion, we should fold `node ls` into `node status`  (the former already
completely calls into the latter internally). Then, we should make `node status`
resilient. By that, I mean the following:

1. no matter the state of the cluster, have at least the information from Gossip exposable. The sources of information here are
    - node addrs+descriptor (`gossip.KeyNodeIDPrefix -> roachpb.NodeDescriptor`)
    - liveness (`*roachpb.Liveness`) which has "recent activity" for all nodes
    - we can't really know about nodes that were long gone (or are missing after the whole cluster went offline),
      but that's ok as long as it's properly documented.
2. when user specifies a --timeout which expires, return with an error but also print the partial information from above,
    explaining the caveats (info might be missing).
3. default to a (say) 15s timeout
4. allow users to explicitly only ask for the gossip-sourced information.

The desired result is that when the cluster is healthy, `node status` makes use of the information stored in the KV store to
print pretty much what it prints today. When the cluster is unhealthy, it *attempts* to get that information, but failing to
do so within a reasonable time frame, the user will receive an error but with it at least the information from Gossip (plus
any other partial results obtained). Additionally, the user can use a flag to indicate that they are only interested in Gossip
information (`--resilient`?)

**Comment by tschottdorf** [comment]
I don't think any more work for this is planned to go into 2.0, though we're in a good position to revisit early in 2.1 since the building blocks are in place (@dsaveliev is working on a PR that swaps out the existing impl for one that uses SQL, and from then on we can iterate on what we actually want to show and prefer gossip-sourced information for the basic view).

**Comment by dianasaur323** [comment]
Thanks @tschottdorf! I've allocated time in our roadmap to close this out in 2.1, so modifying the milestone sounds good to me.

**Comment by Nishant9** [comment]
@tschottdorf If no one is working on this, I can pick this up.

**Comment by tschottdorf** [comment]
@Nishant9 I think we're not quite at the point here where we know what exactly we want, so if you took this on you'd spend a lot of time stuck in limbo. However, there's another issue I could use [your help with](https://github.com/cockroachdb/cockroach/issues/26222#issuecomment-393677039) if you're interested.

**Comment by tschottdorf** [comment]
@nstewart who's in charge of this now on the PM side? We're basically ready to change how `node status` works, but this entails changing the returned fields somewhat. Before we just go and do that I wanted to check in that that's still what we want to do, and that everyone is clear that this requires a docs update, and changes what is returned to users, possibly breaking any homegrown scripts they use to interpret the output.

**Comment by nstewart** [comment]
@piyush-singh is tackling this. @piyush-singh can you follow up here?

**Comment by piyush-singh** [comment]
spoke to @tschottdorf and we'll prioritize this up as part of the  CLI team's upcoming 2 day bugfixing cycle
