### ISSUE TITLE
sql/parser+pgwire: invalid/incomplete encoding of strings in arrays

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#16487]
This may or may not impact compatibility with postgres clients that use array types in query results.

pg:
```
select array[e'a\x10b']
{a\x10b}
```

crdb:
```
select array[e'a\x10b']
{e'a\x10b'}
```

(Found while working on #16459)

cc @jordanlewis

**Comment by knz** [comment]
The root cause of the issue is that the way `parser.encodeSQLString` is written makes it hard to *not* print the `e'` prefix according to some `bareStrings` boolean.

**Comment by jordanlewis** [comment]
This seems to have gotten... slightly worse?

```
root@127.0.0.1:49875/defaultdb> select array[e'a\x10b'];
   array
+----------+
  {a\020b}
(1 row)
```

```
psql (10.5)
Type "help" for help.

jordan=# select array[e'a\x10b'];
  array
----------
 {a\x10b}
(1 row)
```

**Comment by jordanlewis** [comment]
Update:

```
demo@127.0.0.1:26257/defaultdb>  select array[e'a\x10b'];
     array
---------------
  {"a\\x10b"}
```

**Comment by knz** [comment]
This has been fixed, the result is now the same for both pg and crdb.

(Jordan what you're observing is how the crdb sql client displays the array client-side. The result is in fact compatible with pg. It would display the same when connecting to a pg server.)
