### ISSUE TITLE
Confused about Proto.KeyMax

### ISSUE THREAD

**Issue by thundercw** [cockroachdb/cockroach#1648]
Is the KeyMax(Infinity =[ ]byte{0xff,0xff}, KeyMax=Infinity ) used for user key space or encoded key space? or both? In the encoding pkg, the encoded key is guaranteed less than infinity symbol is very cleary. But I also see some places are using it to compare user key. For example ,ValidateRangMetaKey, it limits the user key smaller than 0xff0xff.

Look forward to your feedback.

**Comment by bdarnell** [comment]
This is kind of broken right now; see #437. `\xff\xff` is supposed to be in the encoded key space, and it cannot be represented in the user key space. But we currently mix encoded and un-encoded keys incorrectly. The plan to fix this is to require use of the structured table layer, so user code cannot set raw keys.

**Comment by thundercw** [comment]
Got it ,thanks @bdarnell
