### ISSUE TITLE
sql: time datatype

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#16490]
Postgres supports a `time` datatype, which represents a time of day without a date. Hibernate exposes it, it's not clear how much demand there is for it, however.

[Postgres docs on `time`](https://www.postgresql.org/docs/10/static/datatype-datetime.html)

**Comment by bdarnell** [comment]
Here's a sample real-world table that uses the `TIME` type [from musicbrainz.org](https://github.com/metabrainz/musicbrainz-server/blob/0f7efdd2ff0ba2bd5e776240064d36e7a2aa1abd/admin/sql/CreateTables.sql#L690)

Note that postgres has two time types, `TIME WITHOUT TIME ZONE` and `TIME WITH TIME ZONE`. The `WITH TIME ZONE` variant is said to have "questionable usefulness" in the postgres docs.

**Comment by jordanlewis** [comment]
I suggest that we avoid implementing `TIME WITH TIME ZONE`. Besides calling that variant "questionably useful", the Postgres docs also recommend that new applications avoid using it.

**Comment by jordanlewis** [comment]
🎉

**Comment by vivekmenezes** [comment]
@couchand you have been randomly picked to QA this feature. QA is an independent evaluation of the feature through the eyes of a user. It's probably best that you do not interview the developers involved in creating this feature, nor look at the implementation. Thanks!
