### ISSUE TITLE
ui: remove schema changes from the events log

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#16500]
Once the jobs table is visible on the admin UI with schema change jobs listed on the jobs table, we should remove schema changes from the events log.

**Comment by dianasaur323** [comment]
Let's discuss this when we revamp the events log, which will occur in 1.2.

**Comment by dianasaur323** [comment]
Based on our events on graph discussion, we all agreed that we are going to keep schema changes as events. I'm going to close this out, but feel free to re-open with comments if you disagree.
