### ISSUE TITLE
sql: convert tests to use session tracing instead

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#16512]
Thanks to session tracing we can now collect the work done by queries in the trace, in replacement for EXPLAIN(DEBUG).

However tests that use EXPLAIN(DEBUG) may need to be converted -- to a query that inspects `crdb_internal.session_trace` with a suitable filter.

cc @andreimatei

**Comment by RaduBerinde** [comment]
In addition to inspecting the traces, we probably need a special "verbose" mode to session tracing which causes us to emit a trace for every row scanned (e.g. in `RowFetcher`).

**Comment by jordanlewis** [comment]
This is done (show trace and show kv trace are used in tests now).
