### ISSUE TITLE
sql : paralleling load data 

### ISSUE THREAD

**Issue by a6802739** [cockroachdb/cockroach#16516]
**FEATURE REQUEST**

Now, when we use `copy` command to load data, it will convert into paralleling `insert` statement, but it just execute on only one node.
Could CockroachDB support load data from multi-nodes, just like `GreenPlum` use `gpfdist` to load data parallelly?

**Comment by petermattis** [comment]
Distributed bulk ingest of data is on the roadmap and actively being worked on. See https://github.com/cockroachdb/cockroach/issues/15933.

**Comment by vivekmenezes** [comment]
closing this issue.
