### ISSUE TITLE
sql: renderNode not elided when column needs renaming

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#16535]
From https://github.com/cockroachdb/cockroach/pull/16533#issuecomment-308756655.

Whenever we need to rename a result column, `renderNode` cannot be elided.

```
root@:26257/> EXPLAIN (VERBOSE) select k, v FROM test.t;
+-------+------+-------+-------------+---------+----------+
| Level | Type | Field | Description | Columns | Ordering |
+-------+------+-------+-------------+---------+----------+
|     0 | scan |       |             | (k, v)  |          |
|     0 |      | table | t@primary   |         |          |
|     0 |      | spans | ALL         |         |          |
+-------+------+-------+-------------+---------+----------+
(3 rows)
root@:26257/> EXPLAIN (VERBOSE) SELECT k AS lol, v FROM test.t;
+-------+--------+----------+-------------+----------+----------+
| Level |  Type  |  Field   | Description | Columns  | Ordering |
+-------+--------+----------+-------------+----------+----------+
|     0 | render |          |             | (lol, v) |          |
|     0 |        | render 0 | test.t.k    |          |          |
|     0 |        | render 1 | test.t.v    |          |          |
|     1 | scan   |          |             | (k, v)   |          |
|     1 |        | table    | t@primary   |          |          |
|     1 |        | spans    | ALL         |          |          |
+-------+--------+----------+-------------+----------+----------+
(6 rows)
```

Some ideas:
 - when eliding renderNodes, see if we can rename the column of the source node instead of keeping the renderNode. This will probably depend on the node type (unless we want to add a `planNode` API to rename columns).
 - or, use a different mechanism to properly name the final columns. Once names are resolved, the names of intermediary columns inside a query are not important, only the final columns.

CC @knz

**Comment by andreimatei** [comment]
What should happen to this TODO calling out to this issue in light of this issue having been resolved?

https://github.com/cockroachdb/cockroach/blob/1f37eee5ea928d2198af9d54db7b9d5998882412/pkg/sql/group.go#L553

**Comment by RaduBerinde** [comment]
@andreimatei I think that "if" can be removed.
