### ISSUE TITLE
sql: unnecessary runtime.Callers via checkSupportForNode

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#16549]
`distSQLPlanner.checkSupportForNode` returns an error generated using `errors.Errorf` for simple queries and unsupported queries. Internally, `errors.Errorf` generates a stacktrace using `runtime.Callers` which shows up in profiles.

Changing `distSQLPlanner` to use `fmt.Errorf` is easy. I'm wonder if we should globally use `fmt.Errorf` instead of `errors.Errorf` as we almost never use the generated stack traces.

Cc @RaduBerinde, @tamird

**Comment by RaduBerinde** [comment]
Interesting. This is one of the rare cases where we have an error in the "normal" path (for unsupported queries), so it's not unreasonable to use `fmt.Errorsf` here even if we stay with using `errors.Errorf` in general.

**Comment by petermattis** [comment]
I'd be fine with that too, though we'd want to make it clear that these `fmt.Errorf`s should be converted back to `errors.Errorf` at some point. Perhaps `CheckSupport` should return a string for the second argument instead of an error. I haven't looked at it too closely yet, so take that suggestion with a grain of salt.

**Comment by tamird** [comment]
Perhaps we should be using a custom error type, here.
