### ISSUE TITLE
log: funky stderrThreshold in trace_test.go

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#16551]
Check out this line:
https://github.com/cockroachdb/cockroach/blob/3b2519aa59995ead2f7c00e6bdb8cde043752bb2/pkg/util/log/trace_test.go#L95
```
	logging.stderrThreshold = Severity_FATAL
```

I believe this is funky. First of all, this is an atomic, and it has a setter. Second, I think it should be restored when the test is done. Third, I think modifying that global is generally horrible because... it's a global (think parallel tests).

I'm curious what motivated this change exactly. What did we want to keep out of stderr? If I run with TESTFLAGS=-v, I want all logs in stderr, right? And if I run without that, no logs go to stderr regardless of their level and this threshold, right?
And also it's unclear to me what log statements in this test are affected by this statement. As far as I can see, there's only one logging statement (as opposed to tracing events): VEvent(ctxWithSpan, logging.verbosity.get()+1, "test2"). Is that the target?

The line was added here:
https://reviewable.io/reviews/cockroachdb/cockroach/12662#-Kmi37uFDqXyeqdHugDs

There are other uses of `logging.stderrThreshold` in that PR that I haven't looked at.

**Comment by tschottdorf** [comment]
@andreimatei is this still a thing?

**Comment by knz** [comment]
I think it is. thanks for pinging me.
