### ISSUE TITLE
distsql: make `SHOW TRACE FOR` work with distsql

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#16562]
Currently any query under `SHOW TRACE FOR <stmt>` is run locally - the plan tree root is a `traceNode` which we can't distribute.

We either need to allow hybrid queries where we have distsql running under some planNodes, or we need to make `distSQLReceiver` handle `SHOW TRACE FOR <stmt>`.

CC @knz @andreimatei

**Comment by andreimatei** [comment]
From a Slack convo:

KNZ [3:28PM]
What we could do is handle `show trace for` separately in the executor, and run the query surrounded by the necessary `set tracing`

Andrei Matei [3:28 PM] 
doing that would probably change the current semantics of `SHOW TRACE FOR stmt`, which is that we'll only run one attempt for the stmt, no retries. But the change would probably be a good thing.

**Comment by jordanlewis** [comment]
I am interested in this feature!

**Comment by andreimatei** [comment]
@jordanlewis are you interested in... working on it? :D
Note that queries using DistSQL can be traced with session recording (i.e. `SHOW TRACE FOR SESSION`).
