### ISSUE TITLE
distsql: make snowball tracing work with distsql

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#16563]
This issue tracks the work to pass through recorded snowball traces from processors back to the gateway.

**Comment by tschottdorf** [comment]
Didn't you fix this the other day? #16655

**Comment by RaduBerinde** [comment]
Ah, yes, but there is still one outstanding issue, SHOW TRACE FOR doesn't run with distsql.

**Comment by RaduBerinde** [comment]
There is a separate issue for that problem (#16562) so I'm closing this one.
