### ISSUE TITLE
ui: favicon in admin ui is wrong

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#16572]
The icon used with the debug endpoints is larger and has a transparent background.

The one in the admin ui should be updated to match, or at least be transparent.

<img width="212" alt="screen shot 2017-06-16 at 18 39 08" src="https://user-images.githubusercontent.com/1614265/27247111-fa5edd38-52c3-11e7-9b30-199dc27447cc.png">
<img width="195" alt="screen shot 2017-06-16 at 18 45 44" src="https://user-images.githubusercontent.com/1614265/27247119-128dffec-52c4-11e7-8feb-7c7549b23e11.png">

**Comment by kuanluo** [comment]
@mrtracy Here you go!
![cl_logo_mark](https://user-images.githubusercontent.com/1486483/27351013-0846f0c6-55ca-11e7-92ae-9ad2751ae3f1.png)
