### ISSUE TITLE
String truncation in SHOW QUERIES could break UTF-8 code sequences

### ISSUE THREAD

**Issue by itsbilal** [cockroachdb/cockroach#16570]
Currently, CockroachDB isn't UTF-8 friendly in truncation of long SQL queries when presenting them in `SHOW QUERIES` and `SHOW SESSION`. A sequence of bytes representing one UTF-8 character could be partially overwritten with ASCII ellipses, resulting in an invalid UTF-8 string.

The relevant part of code is [in session.go](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/session.go#L689).

We should backtrack until we find the first ASCII character, and then split the string at that point.

**Comment by tamird** [comment]
Did we actually verify that this was a real issue before "fixing" it? This was filed from https://reviewable.io/reviews/cockroachdb/cockroach/16543#-Kmi1exgQ_5mIG0rLhnu:-Kmi1exgQ_5mIG0rLhnv:b-hm9r77 but AFAICT, sql statements are already re-encoded into "\u1234" syntax by the time they get here. I'm pretty sure the fix in #16602 doesn't do anything for that reason.
