### ISSUE TITLE
sql: support DISCARD family of statements

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#16587]
As reported by [this forum post](https://forum.cockroachlabs.com/t/syntax-error-on-npgsql/739), some drivers send `DISCARD` statements to reset session state. We should support this mechanism even though we don't support most of the session state that `DISCARD` operates on just yet.

According to [the Postgres docs](https://www.postgresql.org/docs/9.6/static/sql-discard.html), the only variant that we'd need to implement with more than a no-op is `DISCARD ALL`, which should reset all session variables and deallocate all prepared statements.

**Comment by Colemalban** [comment]
I can look into this!

**Comment by arjunravinarayan** [comment]
Hey @Colemalban, thanks for expressing interest! @couchand has already begun work on this, but there are many other issues you could take a look at. I would start with issues that have the `easy` label that don't have a current assignee: https://github.com/cockroachdb/cockroach/issues?q=is%3Aopen+label%3Aeasy+no%3Aassignee
