### ISSUE TITLE
cli: export metrics in debug.zip

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#16584]
We frequently ask users who are experiencing problems to send us screenshots of ui graphs. It would be nice if `./cockroach debug zip` could include a variety of relevant renders of the ui. In a perfect world, that would be browsable (i.e. work much like the current ui), but that is not a strict requirement.

@mrtracy says:

> so the UI itself is built so that info can be transferred from one UI session to another
that’s something that redux enables
we would have to do some work to support it, but basically you would be able to render the UI, export the data from the UI, and then render the UI based on that data somewhere else
however, that only includes the info currently visible in the UI
like, the current graphs and stuff
it wouldn’t let you browse the UI especially well
another alternative would be to have cockroach debug spit out timeseries information and node statuses
and then have another “debug” command that starts a server that serves the UI over that information
but that is quite a bit more work, in my opinion, which would involve significant backend support for that scenario

Based on this information, exporting a number of individual views (different timescales x individual nodes) looks like a promising first version of this.

**Comment by tschottdorf** [comment]
I've experimented a tiny bit with this:

https://github.com/tschottdorf/roacheteer

Creates pictures like so: 

![out](https://user-images.githubusercontent.com/5076964/29904816-bc0fbf02-8dd8-11e7-9221-24692c3b0cac.png)

Definitely would need more love, in particular, automatic creation of the links.

I feel this is way too low-tech and that we should be able to cook up a better thing using react. I believe I chatted with @mrtracy about this but haven't written down the results.

Can we somehow store the "redux state" and load it into a shim ui so that the redux state is all we would have to request from folks?

@mrtracy, could you spill some wisdom? I think it'd be good to do something here very early in 1.2 to more easily debug clusters we can't readily access.

cc @cuongdo

**Comment by dianasaur323** [comment]
So this is on our roadmap for 1.2, but marked as lower priority when compared to some of the other features we are building. I think if we could limit the scope of this to something that would be helpful for support purposes, we should limit it as much as possible. Also, I think it would be nice to bundle the debug pages in as well.

**Comment by tschottdorf** [comment]
I chatted with @mrtracy and my key takeaways were that that saving the redux state isn't going to get us where we ultimately want to go (it's too similar to just taking automated screenshots unless we chip in a lot of extra work and complexity). Instead, letting `./cockroach debug zip` dump (some of the) time series state from which we can then construct a new single-node cluster (the UI of which can then show the graphs) seems more promising.

For those users who have headless chrome available, my tiny script above could serve as a stop-gap in the meantime, once we let it navigate to some of the graphs pages as well.

**Comment by jordanlewis** [comment]
Is this something that KV is working on, @tbg? I heard a rumor, but please disavail me of any incorrect reports. This came up in a recent postmortem.

**Comment by tbg** [comment]
No, nothing we're actively working on due to bandwidth constraints. However - the combination of the WIPs https://github.com/cockroachdb/cockroach/pull/50728 and https://github.com/cockroachdb/cockroach/pull/50432 would give us raw timeseries data in `debug.zip`. We already have a "baby setup" to visualize this dump locally:

https://github.com/cockroachdb/cockroach/blob/master/scripts/localmetrics/README.md

However, this doesn't just give you the timeseries to explore, you have to set each one up individually - not ergonomical. So we'd also want this:
https://github.com/cockroachdb/cockroach/issues/46103
which is basically
https://github.com/cockroachdb/cockroach/issues/54178.

I'm happy to advise here - but as said, unlikely that the KV team will be picking this up. It's possibly a good area that we could contract out, though I have no experience on how well that works in general.

**Comment by tbg** [comment]
Just a heads up that this issue is unlikely to be pursued. Instead, we're going to add a dump of timeseries to `debug zip`. @vrongmeal is working on the first step now: https://github.com/cockroachdb/cockroach/pull/57481

**Comment by knz** [comment]
Closing this in favor of #57710 and  #60611 which contain much more refined suggestions.
