### ISSUE TITLE
storage: replace DeepEqual in `(*EvalResult) MergeAndDestroy`

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#16591]
`DeepEqual` is slow and it should be replaced by a new method `(*EvalResult).IsZero` (which has an appropriate test and won't rot as we add fields to EvalResult or its substructs).

**Comment by a6802739** [comment]
@tschottdorf  I could do this.

**Comment by bdarnell** [comment]
We could use the `gogoproto.equal` option to generate a comparison function for ReplicatedEvalResult. Then we'd only need a hand-written IsZero function for the EvalResult struct (which only has three fields). 

Alternately, the reason we can't use the `==` operator for `ReplicatedEvalResult` is the fact that it contains `start_key` and `end_key` fields (of type `roachpb.Key`). These fields also take up a lot of space, as reported in #16075. If we could figure out a way to get rid of these fields (perhaps replacing them with a range descriptor sequence number as mentioned in https://github.com/cockroachdb/cockroach/issues/16075#issuecomment-303474702), we could go back to using `==`.

**Comment by a6802739** [comment]
@bdarnell , how could I use `protoc` command to generate `*.pb.go` file for `*.proto` file?

**Comment by jordanlewis** [comment]
@a6802739, we have a `Makefile` target for that: `make protobuf`.
