### ISSUE TITLE
how to trim the fragmentary garbage data to optimize the  system's health

### ISSUE THREAD

**Issue by zhaohansprt** [cockroachdb/cockroach#16592]
In our dev env , we only have about  10K‘s rows data  (it grows naturally as client daily  uses through a month)  but it take up  3GB disk space in the storing dir; and it  extremely slows  the syncing to a  newly joined node;
when i dump them to sql's file  they only take up 1.8MB disk space  and  even after restore them  to  a  spec node ,  `du -sh`  the  storing dir  it only take 3MB;
 So  how to trim the fragmentary garbage  to recycle the space

**Comment by a-robinson** [comment]
Hi @zhaohansprt! I just have a couple questions to narrow down what's going on:

1. Has your workload involved updating or deleting a bunch of rows such that the cumulative total amount of data that you had entered in your system might approach 3GB? And if so, did a lot of those updates/deletes happen within the last 24 hours?
1. Have you double checked that there aren't any large tables that you didn't include in the dump?

**Comment by bdarnell** [comment]
I think the data here is probably timeseries data (which lives outside of any table and would not be included in a dump. Currently, there's nothing you can do about this (but it will stop growing after 30 days as we'll start deleting older data). We have a couple of open issues tracking the option to reduce (#15931) or disable (#12675) this data collection.

**Comment by mrtracy** [comment]
Closing this, there's nothing here that isn't captured in other issues.

+ #15931 is fixed; users can now reduce the amount of time that time series are retained via the cluster setting `timeseries.resolution_10s.storage_duration`.
+ #12675 is fixed; users can now completely disable time series storage using cluster setting `timeseries.storage.enabled`.

In addition to these, #21601 will be landing in 2.1. Rollups will provide a third avenue for reducing the amount of space needed to store time series information.
