### ISSUE TITLE
stability: OOM on adriatic

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#16594]
`adriatic` has been OOMing repeatedly over the week-end.
It's running the 1.1-alpha.20170622 (#16538) sha: 2d9abc8

Memory profiling was not enabled for some reason. Enabled and restarted. I'll update here.

**Comment by mberhault** [comment]
goroutine spike before OOM:
![adriatic](https://user-images.githubusercontent.com/5901480/27286885-c0ff39d0-54cf-11e7-9fa7-10a3531fb63f.png)

**Comment by petermattis** [comment]
@mberhault Was this the jemalloc bug? Lots has been fixed since June. Is there anything actionable here?

**Comment by mberhault** [comment]
Could have been, I've honestly lost the context here. Closing.
