### ISSUE TITLE
ui: pause / unpause / cancel schema changes in admin UI

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#16604]
Breaking out the ability to manage schema changes between two issues - SQL and admin UI.

SQL issue here: https://github.com/cockroachdb/cockroach/issues/16018

**Comment by dianasaur323** [comment]
I'm currently no longer convinced we need to add administrative capabilities into the admin UI by 1.2 anymore. Will update milestone post admin UI scoping exercise.

**Comment by jordanlewis** [comment]
Hi @dhartunian / @celiala, pinging you on this one - maybe this is a duplicate, as it's super old, but all the infrastructure for this is here now on the db side, we think!

**Comment by dhartunian** [comment]
I'm gonna close this. Hasn't come up as a feature request.
