### ISSUE TITLE
storage/engine: instrument scans to log how many tombstones they've encoutered

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#16608]
We've had multiple instances of people running workloads with many deletes, that generate large numbers of tombstones. Latest suspect: #16595. To trace these, it'd be nice if somebody logged how many tombstones were discarded by a scan (if it's above some threshold).

cc @tschottdorf

**Comment by tschottdorf** [comment]
This has been "done", except you need to run a manual trace to see it, AND (big and) we disabled it because it somehow made things really slow. See https://github.com/cockroachdb/cockroach/issues/17229#issuecomment-408517535

**Comment by tschottdorf** [comment]
Closing for https://github.com/cockroachdb/cockroach/issues/17229#issuecomment-408517535
