### ISSUE TITLE
run driver_test.go failed

### ISSUE THREAD

**Issue by veteranlu** [cockroachdb/cockroach#1662]
run sql/driver/driver_test.go failed, with error message, cannot found 'cockroach' driver, i fixed it, add import "github.com/cockroachdb/cockroach/sql/driver".

**Comment by petermattis** [comment]
The import shouldn't be necessary as `sql/driver/driver_test.go` is part of the `sql/driver` package. Did you do `go run sql/driver/driver_test.go`? If so, that's not the correct way to run tests in go. You should be doing `go test ./sql/driver`.

**Comment by veteranlu** [comment]
I got it, thanks.
I think the tips should be added into CONTRIBUTING.md, it's helpful for someone who play golang not long. :)
