### ISSUE TITLE
storage: inform non-retryable transactions early that they can't commit once they've been pushed

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#16678]
We have this policy of allowing transactions to continue even when we know that they won't be able to commit, because we want them to lay down their intents in the hope that, after a restart, the transaction will write to the same keys. Since intents have been laid down early, those intents will keep other transactions away, so that our original txn is more likely to commit on its 2nd attempt.
This happens at least in two cases: when a txn has its timestamp bumped by having one of its writes run into the timestamp cache and on a WriteTooOldError.

This mechanism is cool, but not helpful for transactions that have no intention to retry - e.g. SQL explicit txns that didn't use the `savepoint cockroach_restart` statement. These guys would benefit from being told early that they can't commit. And also it'd make debugging them easier, as the conflict causing them to fail would be more easily apparent.

**Comment by andreimatei** [comment]
Note to self that we can already do this at the sql level (we already do it while the txn is in the `FirstBatch` state).

**Comment by a6802739** [comment]
@andreimatei , could I have a try for this?

**Comment by andreimatei** [comment]
sure. Let me know if the issue isn't clear or if you don't know what to do about it.

**Comment by a6802739** [comment]
@andreimatei , Thank you very much.

I don't quite understand what do you mean `lay down their intents`?

From my understanding, for the transaction which has been pushed will be abort when the coordinator try to commit it, then the coordinator will restart the transaction, and the intents that the transaction has left will be overwritten when the transaction try to execute again, right?

 So what kind of transaction that has no intent after the transaction has been executed, and what we should do with these kind of transaction?

**Comment by andreimatei** [comment]
> From my understanding, for the transaction which has been pushed will be aborted when the coordinator try to commit it, then the coordinator will restart the transaction, and the intents that the transaction has left will be overwritten when the transaction try to execute again, right?

That's not quite right. A pushed transaction is not "aborted"; aborting is different [1]. An aborted transaction is not allowed to continue running - as soon as the coordinator node finds out that its transaction has been aborted, execution stops. A pushed transaction, however, is allowed to continue until it attempts to commit (it might even be allowed to commit, depending on the isolation level at which it's running). "Pushed" means that the transaction's commit timestamp has been modified. 
A transaction has two timestamps: 
- [orig_timestamp](https://github.com/cockroachdb/cockroach/blob/3a9fd60f88742e47e9c1b6c7d37e0ac362cdfa77/pkg/roachpb/data.proto#L285) is the timestamp at which you read.
- [timestamp](https://github.com/cockroachdb/cockroach/blob/3a9fd60f88742e47e9c1b6c7d37e0ac362cdfa77/pkg/storage/engine/enginepb/mvcc.proto#L58) is the timestamp at which you write (also know as the "commit timestamp").

Pushed means that `timestamp` has been increased with respect to `orig_timestamp`. *Serializable* txns can only commit if the two are the same. *Snapshot* transactions can commit regardless.

So, what we do when a (serializable) transaction is pushed is that we allow it to continue, even though we know that it won't be allowed to commit) so that it continues writing intents. The point is that the intents will keep other transactions away.
When it attempts to commit, we *restart* the transaction: we don't wipe out the intents, but we increase the txn's epoch. When it tries to commit again, only intents from the last epoch will be committed. Intents from older epochs will be cleared.

Now, the present issue says that sometimes we're misguided in letting a (serializable) transaction continue after it's been pushed. If the transaction is not going to be retried, then all the intents will be cleared anyway, so there's no point in letting it run. We should detect that we've been pushed and just abort early.

See [this code](https://github.com/cockroachdb/cockroach/blob/3a9fd60f88742e47e9c1b6c7d37e0ac362cdfa77/pkg/sql/executor.go#L1566) and [this](https://github.com/cockroachdb/cockroach/blob/3a9fd60f88742e47e9c1b6c7d37e0ac362cdfa77/pkg/sql/executor.go#L1588-L1603).

Does this help?


[1] Both "pushing" and "aborting" are done by `PushTxn` RPCs, but they're really different actions.

**Comment by a6802739** [comment]
@andreimatei. Thank you for your kind explanation. That really helps.

So what we should do is try to abort the transaction that couldn't commit as early as possible. These transaction will not be retried again, which means will not be restarted again. And most of these transactions are kind of explicit txns, which means they will use explicit `BEGIN` in these transactions.

If my understanding is right is right, I still don't know how to deal with this issue. I mean, in normal situation, when we try to `COMMIT` these  explicit txns, we'll know these txns has been aborted, right? 

So now it means we should response to the client that the txn should be aborted if we already make sure it couldn't commit in the future?

So we should know if the transaction is not going to be retried, if the transaction's timestamp has been pushed,  if the transaction is serializable. 

If the transaction matches the three conditions above, we should return an error directly to the client, and not continue,right?

**Comment by andreimatei** [comment]
> So what we should do is try to abort the transaction that couldn't commit as early as possible. These transaction will not be retried again, which means will not be restarted again. And most of these transactions are kind of explicit txns, which means they will use explicit BEGIN in these transactions.

Correct. If we know that the transaction will not be retried, there's no point in letting it run when we know that it can't commit.
Currently, at the KV level, we generally don't know whether a transaction will be retried or not.
At the SQL level, however, we do know. A transaction will be retried while we can do automatic retries (i.e. we're in the AutoRetry state) or if the client has indicated that it implements the client-directed retry mechanism by issuing a `SAVEPOINT cockroach_restart`. This is indicated by a  `TxnState.retryIntent`.
So, I suggest we only do changes at the SQL level - if we're not going to auto-retry and that `retryIntent` is not set, we should detect pushed transactions after every statement and perform cleanup.
This is similar to the detection that we already have (the links I gave you in the previous comment), except we should be doing it always, not just while we're in the `AutoRetry` state as we do now. I expect the change to be quite small - perhaps just adding the `retryIntent` check to this line (plus tests): https://github.com/cockroachdb/cockroach/blob/3a9fd60f88742e47e9c1b6c7d37e0ac362cdfa77/pkg/sql/executor.go#L1566

Does this answer everything?

cc @bdarnell in case he's got a different opinion about the level where these pushed transactions should be detected.

**Comment by bdarnell** [comment]
I agree that we should be detecting this at the SQL level.

**Comment by a6802739** [comment]
@andreimatei, Thank you very much.

So I should just change it to:

```
(txnState.State() == AutoRetry && txnState.isSerializableRestart()) ||
			(txnState.retryIntent && txnState.isSerializableRestart()) {
```
right?

And how could I add a test for it, any reference?

**Comment by andreimatei** [comment]
> So if we don't want the transaction retry again, we'll add a condition judgement like:

Yeah, something like that should be right (I'd need to see an actual patch to check how the condition fits with the `AutoRetry` one).

To test it, I'd add a test probably to `txn_restart_test.go`: I'd start txn A, insert a row, then, on a different connection, do a read over the same data in a high-priority transaction (`BEGIN TRANSACTION PRIORITY HIGH`) which should push A, then back in A I'd run some other statement and expect to get the retriable error as a result.
