### ISSUE TITLE
storage: Adding to replica GC queue upon removal can race with scanner's call to shouldQueue

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#16691]
If a replica gets added to the replica GC queue due to another member of its range telling it that it's been removed, then normally it'll fairly quickly get processed and GC'ed. However, if the scanner happens to call into `replicaGCQueue.shouldQueue` between when it gets added and when it gets popped off the queue for processing, `shouldQueue` will say that it doesn't need to be queued and the base queue will remove it. This is because `shouldQueue` bases its decision almost entirely on time since last processing and not on whether the replica is still a member of the range. We could fix it by also taking the replica's local range descriptor copy into account in `shouldQueue`.

This is hardly urgent (if we even care to fix it at all), but I'm making note of it since it was causing some troubles with trying to test that the number of replicas on each store in a test dropped back down to a correct number.

**Comment by bdarnell** [comment]
I don't think this is unique to the replica GC queue - we try to manually enqueue replicas on all the queues when we can, and this may not exactly correspond to `shouldQueue` returning true. It's kind of strange that the scanner could cause a queued replica to get removed; we should probably just let queued replicas stay in the queue until they get processed.

**Comment by a-robinson** [comment]
Yeah, as far as I know keeping something in a queue should be harmless even if `shouldQueue` doesn't think it needs to be queued. I'll make that change as well as my above tweak to the replica GC queue and hopefully we'll find out before 1.1 if that violates any assumptions.
