### ISSUE TITLE
Replace `net/rpc` server

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#1669]
Go's `net/rpc` has some significant drawbacks for our use. The biggest is that the server spawns a new goroutine for each request, so that the order of requests on the wire is not preserved. This leads to performance problems in raft, when out-of-order messages result in unnecessary retries. Secondary issues include the memory impact of creating an unbounded (and difficult to monitor) number of goroutines, the use of separate Go methods for each RPC method (which we then fold back into a single `executeCmd` bottleneck), and the use of reflection to find and expose all public methods with two arguments. 

We've already replaced the guts of `net/rpc` with our own protobuf-based codec, so I'm going to replace the (relatively small) remaining portions of `net/rpc.Server` in `cockroach/rpc.Server`. The client side of `net/rpc` hasn't caused us any problems so I'm going to leave it as-is.

**Comment by petermattis** [comment]
We use `net/rpc` both for raft messages and "dist sender" messages. Are you proposing to replace it for both usages, or only for raft?

**Comment by bdarnell** [comment]
Both, but for the dist sender the behavior will be essentially unchanged. I'll continue to spawn goroutines for those instead of preserving order.

**Comment by petermattis** [comment]
Sounds good.

**Comment by MBerhault** [comment]
@tamird and I starting looking at grpc. While it seems to have most of what we would like for authentication purposes (mostly being able to add hooks at connection establishment, and being able to pass some context around), I don't know whether it would help for this. If so, it might be the right way to go.

**Comment by tamird** [comment]
Yeah, I think grpc could be a nice fit here. It's definitely more work, since we'll have to rewrite both sides of the transport. In particular, it seems that in order to get things to be serial we'll need to use streamed responses, which means inverting the raft model (followers long-poll the leader).

**Comment by petermattis** [comment]
Wouldn't the performance (or lack thereof) of grpc make it a non-starter for this usage. Since this communication is entirely internal, I see little benefit to using grpc. This contrasts with potentially using grpc for client-server communication which could see a big benefit to using a widely supported rpc library.

**Comment by tamird** [comment]
We haven't really benchmarked grpc enough to confidently say one way or the other. In particular, we haven't tested streaming at all.

**Comment by bdarnell** [comment]
"Non-starter" is a little harsh; from my understanding of the GRPC protocol there's not anything inherently slow about it, it's just that the implementations (and the HTTP/2 implementations they depend on) haven't been very well optimized yet. I'd love to be able to ditch our rpc/codec in favor of something more broadly supported; it just remains to be seen whether GRPC will be able to get enough traction (in or out of google) to get that kind of support.

**Comment by spencerkimball** [comment]
I suggest we wait before going whole hog on GRPC. We're one step away with no unknowns from the original proposal to swap out the rest of rpc/server. I'm reluctant to swap GRPC in, even for the client/server comms, much less our more critically-performant inter-node comms. I think we'd need a more compelling benefit than "broad support" to usher in the myriad issues a new protocol would invariably present--we already know performance will suffer; in naive testing this was a factor of 2x vs. Go RPC. I don't doubt there would be other issues. Let's not cast ourselves unnecessarily in the role of guinea pigs.

**Comment by petermattis** [comment]
"Non-starter" might be a bit harsh. How about "premature"? I really liked the original proposal of customizing our own version of `net/rpc` for internal traffic. Switching to GRPC (or something else) is a much bigger decision.
