### ISSUE TITLE
sql: draining a node might result in an illegal use of a table descriptor lease

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#16706]
When we drain a node we aggressively delete all table leases that the node has acquired. However there can be transactions using one of the leases, and we should check if a transaction could use an illegal lease when a node is draining in the midst of a schema change.

**Comment by knz** [comment]
cc @asubiotto

**Comment by vivekmenezes** [comment]
assigning to self because I wanted to review this. There might not be any bug here.

**Comment by knz** [comment]
my comments from earlier:
> so the issue I see is that the regular signal-based shutdown system for a node, either launched interactively in a terminal or via a process manager, will fail to shut down the node _gracefully_ as soon as there is at least 1 client connected. Therefore, any admin will either interactively or via their process manager cause the node to be shut down forcefully (2nd signal)
> so I foresee that early release of leases as is now implemented is going to be the *common case*, not the exception
> now if the cluster is busy with lots of transactions and schema updates, this in turn implies we may have incorrect transaction resolution upon node shutdown

**Comment by asubiotto** [comment]
Draining only deletes leases from `system.lease` with a refcount == 0, so if a lease is in use while a node is draining, that lease will only be deleted once the refcount drops to 0 and if the node shuts down while a lease is held, that lease will still be present in `system.lease`. @knz, I'm not sure I understand your last comment, why would a node fail to shut down gracefully as soon as there is at least 1 client connected?

**Comment by vivekmenezes** [comment]
This is not an issue. Verified alfonso's comment. Thanks alfonso!
