### ISSUE TITLE
security: figure out cert/key rotation

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#1674]
We need a good way to handle cert/key rotation without having to restart all the nodes.
Pretty low priority.

**Comment by mberhault** [comment]
Throwing a basic outline of requirements and future improvements:
 
Requirements:
* be able to specify multiple CA certs and node cert/key pairs for a single node. needed to be able to read/validate "old" certs and "new" certs.
* ability to reload certificates without restarting the process

Future improvements:
* add support for cert revocation
* warnings/metrics about certificate expiration time
* customizable certificate lifetime in `cert` command

Specifying multiple CA certs or cert/key pairs can be done in a number of ways:
* repeated flags (does not help if we do not know the names in advance)
* overwrite existing files (if a node gets restarted before all nodes have the new certificate, it would effectively be disconnected from the cluster)
* glob/naming scheme/directory for certs/keys. Potential security issue if someone else can write files with the name. Can partially avoid by checking ownership/mode.

Reloading certs is probably best done through issuing the `SIGHUP` signal, unless we want to watch the directory/files. The former would probably be less surprising.
Using new client/server certificates can be done by setting `tls.Config.GetCertificate` and `tls.Config.GetClientCertificate`. CA certs can just be added to the pool

[detailed outline of cert rotation in go](https://diogomonica.com/2017/01/11/hitless-tls-certificate-rotation-in-go/)

**Comment by petermattis** [comment]
Cc @bdarnell

**Comment by bdarnell** [comment]
Let's separate CA cert rotation from the other cases - it's significantly easier because no cockroach process needs to touch the CA private key (or should even have access to it), and it's trivial to use multiple CA certs at once. In fact, when we have multiple CA certs, I don't think we ever need to use multiple keypairs at any node or client. On the other hand, clients need the CA cert too, so we must consider clients in the key rotation story.

The rotation process (assuming all the certs are expiring at the same time, although pieces of this process also work on their own) would be:
1. Deploy old+new CA cert `.pem` (or equivalent) files to all nodes (and clients). Reload with SIGHUP or equivalent. 
2. Once all nodes and clients are using the new CA configuration (need monitoring to make this visible - must report on at least the number of known CA certs; maybe a fingerprint to identify the exact config), begin the process of rolling out new node and client keypairs, signed by the new CA. Each node needs to load its new TLS config and start using it for all new connections. 
3. Once all nodes and clients have been updated (again, need monitoring), do another CA cert update to remove the old CA cert from all nodes and clients.

**Comment by mberhault** [comment]
Yeah, I think we may want to decouple CA and server/client cert lifetimes, it's insane to have them expire at the same time, potentially forcing a refresh of everything.

Ultimately, we won't be able to monitor client CA expiration, the best we can do is figure out which CA was used to sign the client cert.

I propose we keep things reasonably simple for now. Specifically:
## Cert expiration:
* make default CA expiration much longer (eg: 10 years)
* keep node/client cert expiration at 1 year
* metrics for CA/node cert expirations
* alert on CA expiration within 6 months
* alert on node expiration within 1 month

The actual expiration time can be set at cert creation-time, but the defaults should differ for CA/server/client certs.
If we want to make these more configurable, we can have alerts based of fraction of lifetime remaining.
Alerts should be both in the admin UI and in publicly-available prometheus rules.

## CA rotation:
* allow an arbitrary number of CA certs. Any non-expired CA cert gets added to the pool (I'm pretty sure the tls lib does that for us anyway).

Admins can cleanup old CAs quickly, but don't have to.

## Server cert rotation:
* allow multiple node certs to be present
* reload certs on `SIGHUP`
* use cert with `NotBefore < time.Now` and latest `NotAfter`.

I don't think we want to go much more complex than this. Any sort of cluster-wide gating system will fail if certs expire and nodes can't talk to each other.
CA renewal too close to node cert renewal will always cause problems if clients aren't updated quickly enough.

## Concurrent CA/Server cert rotation:
If this really needs to happen, there's very little we can do to make sure clients have the updated CA.

Even gating server cert rollout is tricky, any type of global switch requires functional communication between nodes. We can signal a node to load new certs but we can't control when a node restarts, picking up new certs in the process. The gating process is effectively sighup/restart after pushing new certs.

## Loading multiple certs:

We really want to support multiple files, especially for CA certs, having more than one is perfectly reasonable and allows for slow rollout.

Multiple node cert files is debatable. If we always use the more recent valid one, we could overwrite the file, but if we want to allow not-yet-valid certs, we need more than one file.

How to specify multiple files is open for debate. Both globs and auto-detection within a directory are fragile in the face of odd filenames, but still doable. We could make things simpler by having our PEM contain both certificate and private key, we currently move both around together anyway.

## Rotating certs for new connections:

Refreshing CAs and node certs are easy through the standard tls.Config:
* add CA cert to the shared root/client CA pools (we need a wrapper to lock those properly)
* set `tls.Config.Get(Client)Certificate` to return the latest valid certificate

We need to make sure that those are properly used by grpc. We may need to go through grpc's `TranportCredentials` and swap the entire `tls.Config`. Both are described in the `Hitless TLS Certificate Rotation` post listed above.

**Comment by mberhault** [comment]
Draft RFC for online certificate rotation can be found in #14254

**Comment by mberhault** [comment]
This is merged.

A few issues remain but can mostly be addressed later.
#14985: figure out cert lifetimes
#15027: certs debug page and monitoring
#15028: other methods to trigger certificate reload
