### ISSUE TITLE
server: reporting is currently losing data because protos sent using json and can't deal with field renames

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#16748]
generally proto field/type renames are considered safe, since wire encoding is by ID, but when encoded as json (in the usage and diagnostic reporting), the field names are currently being used, making those renames no longer safe.

We either need to ban renames or not use them on the wire. Renaming is generally useful (allows for more expressive, self-documenting code) so I'm pretty sure we want to stop using the json encoding that includes them.

**Comment by knz** [comment]
What about not using JSON. Instead encode the bytes and send the bytes over http.

**Comment by knz** [comment]
Marking high priority because we are losing usage data as long as this is not fixed.

**Comment by dt** [comment]
@knz eh -1 on that title -- this issue is about how cockroach is handling it, not the reg collector, which _could_ handle this with versioned protos for decoding.

**Comment by knz** [comment]
added "currently"

**Comment by knz** [comment]
the problem is that the people who will be responsible for keeping an eye on progress need to be reminded explicitly this is a business critical bug and not some minor internal annoyance

**Comment by dt** [comment]
@knz note that this *isn't* in 1.0.x.

**Comment by knz** [comment]
do we not care about the users of 1.1-alpha?

**Comment by dt** [comment]
I think we should switch to encoding the cockroach protos (so the schema and stats) as native protobuf bytes strings that are hex or base64 encoded for inclusion in json requests to the reg API.

Obviously we could also switch to a non-json API and send raw protos instead, but I'm not crazy about that. We could also try to keep json encodings of all the data and avoid breaking changes -- either by imposing extra constraints on what we do to those protos or by adding json tags to prevent renames from changing their encoding, but this seems brittle and likely to just add confusion -- people may forget what is safe and what isn't, mismatched names could cause confusion, etc.

**Comment by petermattis** [comment]
@dt This is done, right?

**Comment by dt** [comment]
yeah, whoops, this was done awhile ago
