### ISSUE TITLE
server: In-memory `size` attribute sizes cache, not store

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#16750]
The store specification for an in-memory store has a `size` parameter, which is supposed to set the size of the store. However, [when we use this value](https://github.com/cockroachdb/cockroach/blob/e164c2e16f3770bc49835374bd1aee9e35805d4b/pkg/server/config.go#L448), [it is passed as the cache size](https://github.com/cockroachdb/cockroach/blob/e164c2e16f3770bc49835374bd1aee9e35805d4b/pkg/storage/engine/in_mem.go#L29-L35), not the store size (the store is always hard-coded to 512MB). This is low-priority since in-memory stores are test-only, but it would still be nice to clean this up.

**Comment by soniabhishek** [comment]
@bdarnell so should i set the cache size as store size or there should be a new parameter for store size. ??

**Comment by bdarnell** [comment]
I'm not sure if it even makes sense to use a cache with an in-memory store. Try just using a zero-byte cache and see what happens.

**Comment by soniabhishek** [comment]
@bdarnell Yes I tried working with 0 size cache and got the concept, every thing is working fine. i made small change in this.
 

> func NewInMem(attrs roachpb.Attributes, storeSize int64) InMem {
	cache := NewRocksDBCache(0)
	defer cache.Release()
	rdb, err := newMemRocksDB(attrs, cache, storeSize)
	if err != nil {
		panic(err)
	}
	db := InMem{RocksDB: rdb}
	return db}

I am not sure what else needs to be changed and taken care of. should i change all test questions which earlier are using

>  1<<20

 as cache size to use 

> 512<<20

 as store value. or I am missing anything else

**Comment by bdarnell** [comment]
In most cases, the tests that are using `1<<20` should keep using `1<<20`. Most tests don't use much data, and the intention was always for that argument to control the size of the store. If any tests run out of space with `1<<20` then you can change those tests to use a higher value.

**Comment by knz** [comment]
Re-opening since Rafi is working on it in #64095.
