### ISSUE TITLE
security: cert deployment

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#1675]
We need a certificate deployment story in general, and actual implementation in cockroach-prod to be able to run in secure mode.

**Comment by dianasaur323** [comment]
@mberhault does this issue https://github.com/cockroachdb/cockroach/issues/1674 address what you had in mind here?

**Comment by mberhault** [comment]
not quite, but this is partially obsolete (especially the cockroach-prod mention). We have enough bugs open for cert stuff that this is pretty much covered.
