### ISSUE TITLE
backup/restore: allow backing up history (not only values live at given timestamp)

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#16779]
I found out today that backup/restore doesn't actually work the way I *thought* it would.

I assumed that a full backup would basically keep everything that's reachable by `AS OF SYSTEM TIME` reads for timestamps less than or equal to the given backup timestamp (within the limits dictated by GC policy), but it doesn't do that - it just preserves `AS OF SYSTEM TIME backup_timestamp()`.

That could be a problem for users of `AS OF SYSTEM TIME` as restoring such a backup would make historical reads fail for however long in the past they were reading. For example, reading 24h ago would only work after 24h. Maybe not everyone will want to pay the extra storage, but it should at least be an option (perhaps even arguably the default, as you naively expect a restore to get the system as close to backed up state as possible).

Similarly, incremental backups don't keep intermediate versions (if a key is written at `t1`, changed at `t2`, deleted at `t3`, changed at `t4`, then an incremental backup from `t1` to `t4` does not contain the mutations at `t2` and `t3`).

It also seems that from an implementational point of view, the current system is really just a special case of the one I imagined we were doing (where you're preserving 0 historical reads). That suggests that there isn't much overhead to supporting both (though the current code would have to be generalized).

**Comment by dianasaur323** [comment]
We might actually address this in 1.2, so bumping this up in priority

**Comment by rolandcrosby** [comment]
Implemented by `BACKUP WITH revision_history`
