### ISSUE TITLE
acceptance test doesn't register when a node dies

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#1678]
I would've expected the test to fail if one of the nodes dies unexpectedly (such as happens frequently with the Put test). Instead, I'll only find out when that happens a) if Raft progress stops because the majority is gone or b) I check the logs and see that peers are unreachable.
I should add that those node failures are almost always due to panic or OOM.

**Comment by petermattis** [comment]
Hmm, this must have been broken recently. The acceptance tests are supposed to watch for unexpected docker events.

**Comment by tschottdorf** [comment]
Maybe we broke it, shifted some code around there last week. I'll check it out.

**Comment by petermattis** [comment]
Yep. Or maybe docker 1.7 broke it.

**Comment by tamird** [comment]
@tschottdorf did you ever get to the bottom of this?

**Comment by tschottdorf** [comment]
no. I'll look at it when I investigate/fix some logging issues with the acceptance tests.

**Comment by tschottdorf** [comment]
There is something here. I can run `make acceptance TESTS=TestPut TESTFLAGS='-v -d 50s'` and kill one of the nodes (`docker kill <id>` (sends `SIGKILL`)), and the test will complete happily.

**Comment by tschottdorf** [comment]
looks like the events stuff is working correctly, it's just not being used by most tests. I'm taking a look.
