### ISSUE TITLE
review feed buffering

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#1680]
the current `util.Feed` contains a buffered channel and will panic if the consumer can't keep up. The discussion in https://github.com/cockroachdb/cockroach/pull/1658 suggests un-buffering this channel or switching to another interface.

I'm personally in favor of not keeping the current unbuffered channel (at least with the panicking) behavior. We should be careful about blocking though: different publishers may want different behavior (back-pressure vs. dropping messages).

**Comment by mrtracy** [comment]
As an opening salvo, I would suggest splitting feed's subscribe method into two methods,  a `Subscribe()` and `SubscribeAsync()` (or other appropriate names).  The feed would maintain two separate lists of subscribers - those subscribed using one method would block (thus applying back-pressure)

**Comment by tschottdorf** [comment]
wasn't there a comment here @mrtracy?

**Comment by mrtracy** [comment]
Yeah I didn't mean to post it, I accidentally pressed 'close and comment'.  I want to think about it a bit.

**Comment by tamird** [comment]
Buffered channels are gone from util/feed.
