### ISSUE TITLE
Cockroach 1.0.2 doesn't run on OpenBSD

### ISSUE THREAD

**Issue by mrijkeboer** [cockroachdb/cockroach#16812]
**BUG REPORT**

After failing to compile `master` on OpenBSD (issue #16811) I tried to compile version 1.0.2. This version compiles fine with the following:

```
$ CC=egcc CXX=eg++ gmake build TAGS=stdmalloc
```

Unfortunately, when I try to start cockroach it does nothing except slowly eating all CPU resources. For instance, when I run `coachroach version` it hangs without showing anything and starts eating all CPU resources. However, I can kill it by pressing `CTRL+C`. Cockroach  1.0.1 shows exactly the same behavior.

It doesn't seem to be an issue with OpenBSD, because the version I used in the past (0f59bf40038aa01c0ab25373ffd7980cc91e4d2e) compiles and runs fine.

```
$ ./cockroach version
Build Tag:    0f59bf400
Build Time:   2017/06/30 11:54:01
Distribution: CCL
Platform:     openbsd amd64
Go Version:   go1.8.3
C Compiler:   gcc 4.9.4
Build SHA-1:  0f59bf40038aa01c0ab25373ffd7980cc91e4d2e
Build Type:   development
```

Some more info about the system:

```
$ sysctl kern.version
kern.version=OpenBSD 6.1-current (GENERIC.MP) #70: Thu Jun 29 14:30:19 MDT 2017
    deraadt@amd64.openbsd.org:/usr/src/sys/arch/amd64/compile/GENERIC.MP

$ go version
go version go1.8.3 openbsd/amd64
```

**Comment by knz** [comment]
Hi @mrijkeboer - I am looking into this but unfortunately we will not make further portability changes to Cockroach 1.0 since the release of 1.1 is imminent. I am closing this, let's continue the discussion on #16811.

**Comment by mrijkeboer** [comment]
Hi @knz: I agree with discussion this further on #16811.
