### ISSUE TITLE
server: Gateway-only mode

### ISSUE THREAD

**Issue by bra-fsn** [cockroachdb/cockroach#16810]
**FEATURE REQUEST**

In a multi-node setup (in which CRDB is mostly used I guess), one possible architecture could be to deploy CRDB clients (the application, which uses CRDB) to the same nodes as CRDB and specify localhost to the client.
However there are multiple cases where this doesn't fit and therefore the clients must somehow access the CRDB cluster.
This could be done by using some kind of a load balancer, which checks for CRDB nodes' health and remove ones which don't work.
Another approach could be to deploy CRDB client nodes to the hosts which run the application, which could then connect to the CRDB cluster, but without serving data.
This could be superior to the external load balancer case because CRDB client node knows the actual cluster state, can direct the queries right to the node which serves them and handling a failed server could also be smoother than a simple TCP-based load balancer, which has to break the client's TCP connection and build up a new one if the selected server fails.

This is similar to what other databases do, like elasticsearch, where each node can be of multiple purposes.

**Comment by bdarnell** [comment]
We've talked about this before and it's an interesting idea. It almost works today: you just need to create a server with no stores. The problem is that you still need to allocate a node ID and store it somewhere (or make sure that it's possible to run a node without a node ID), as well as persisting the cluster membership so you can handle stale `--join` flags. 

You could also just give these gateway-only nodes a store but use zone configurations to ensure that they are never actually assigned any replicas.

**Comment by arjunravinarayan** [comment]
The former path means we definitely need another flag to configure the external storage `TempStore`'s path. If the thinking is the gateway nodes can provide additional compute capacity, the workload is probably one where they would benefit from external storage for query execution.

**Comment by bra-fsn** [comment]
@bdarnell, these workarounds sound good. I have some environments without any local storage (of course a tempfs is always there, so some files can be stored locally, although temporarily).
The best would be to just have this function anyways. :)

**Comment by bra-fsn** [comment]
Any news/ideas on this?

**Comment by bra-fsn** [comment]
> We've talked about this before and it's an interesting idea. It almost works today: you just need to create a server with no stores. 
Is this possible with recent releases?

**Comment by bdarnell** [comment]
No, I don't think anything has changed in this area.

**Comment by knz** [comment]
This has been implemented in v20.2 for multitenancy.

**Comment by knz** [comment]
The code is implemented but we're not planning to _document_ it until v21.1.

**Comment by bra-fsn** [comment]
> The code is implemented but we're not planning to _document_ it until v21.1.

It's been a while, did you actually document this feature? Can't find it.
