### ISSUE TITLE
sql cli: error coming from batch of statements with results is swallowed by cli

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#16825]
Send a batch of statements that first produces some results (the `select 1`), then an error for a subsequent statement. The error is not displayed on the console (but the session state is shown as `ERROR`).
In this particular case, the error is `pq: retryable error from another txn. Current txn ID: 8a4be5f8-63fd-4ced-9e2c-937f2cea5e1c: HandledRetryableTxnError: forced by crdb_internal.force_retry()`, (the fact that we return that error is a bug in own right). But I assume the problem is general

(reproduce at commit `6e89e2d51c3e8ad5e31e48ed34635c0c269e565f`)

```
CREATE TABLE kv (
  k CHAR PRIMARY KEY,
  v CHAR
)

root@:26257/test> BEGIN TRANSACTION; select 1; INSERT INTO kv(k, v) VALUES ('auto_retry', 'b') RETURNING NOTHING; SELECT crdb_internal.force_retry('1000000ms':::INTERVAL); rollback;
+---+
| 1 |
+---+
| 1 |
+---+
(1 row)
root@:26257 ERROR> rollback;
ROLLBACK
```

**Comment by knz** [comment]
I believe this is a dup of #16519; can you check?

**Comment by knz** [comment]
dup #16519 indeed.
