### ISSUE TITLE
Support for Quoted Integer

### ISSUE THREAD

**Issue by rmxhaha** [cockroachdb/cockroach#16823]
This is a question and feature request.

I cannot find something similar issues with a quick search in your github issues and google. I hope this is not a duplicate or me miss reading the documentation regarding quoted integer. 

I am currently using nodejs and sequelize. Sequelize is an ORM which support postgresql and many more. 
Sequelize add quote to id.
For example:

`UPDATE files set filePath='somewhere' WHERE id = '258117330542034945'; `

where the id is suppose to be an integer type
This can run in postgresql but cockroachdb spit out error

> pq: unsupported comparison operator: <int> = <string>

Is there a way to support quoted integer in cockroachdb ? 

I currently directly changing sequelize dataStructure in my node code to convert id to integer
It's a hackish way to do it. 
I would rather not do that everywhere I need id.

**Comment by jordanlewis** [comment]
Is there a way you can change your app to explicitly cast the integer string to an integer with `::integer`?

**Comment by rmxhaha** [comment]
Yes, there is away to do that. 
It works but I would rather not do that because It will be messy hack all over the code.
I am trying to modify sequelize ORM to automatically cast all integer string into integer if the column is integer type but haven't figure out how to do it, yet.

I guess it's not trivial to support integer string in cockroachdb ?

**Comment by rmxhaha** [comment]
I will close this because the lack of reply ... 

Thank you for your participations

**Comment by tschottdorf** [comment]
@rmxhaha it's perfectly normal not to receive a response during the weekend.

**Comment by kiddouk** [comment]
I am running in the same issue at the moment. I am wondering who is really at fault here. If this is sequelize or cockroachdb though. 🤔

**Comment by benesch** [comment]
We're working on it from both the Sequelize end and the CockroachDB end. See https://github.com/cockroachdb/sequelize-cockroachdb/pull/2 and #15903.

**Comment by dianasaur323** [comment]
@benesch have we met this issue at this point? Can we close this out?

**Comment by benesch** [comment]
Indeed, this was fixed by #15903.
