### ISSUE TITLE
sql: primary key updates during index backfills are broken

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#16828]
The secondary index update algorithm used in `RowUpdater.UpdateRow` does not take into account the state of a secondary index during an index backfill, and can produce incorrect update failures.

For example, consider the following scenario:

```
CREATE TABLE test (k INT PRIMARY KEY, v INT);
INSERT INTO test VALUES (1, 2);
-- begin index backfill: `CREATE INDEX foo ON test(v)`
-- before backfill starts, execute:
UPDATE test SET k=3 WHERE v=2;
```
If performed in the correct sequence, the `UPDATE` will produce the following error:

```
pq: got 3 values but expected 2
```

I haven't tracked down the precise cause of this, but it's basically because the `RowUpdater` isn't sufficiently aware of all of the possible states an index backfill can be in.

**Comment by vivekmenezes** [comment]
Glad you found it. You should be able to add a test to descriptor_mutation_test.go by running the UPDATE while the mutation is in a particular state and reproduce this more predictably.

**Comment by jordanlewis** [comment]
I have a test in `schema_changer_test.go` that produces it reliably.
