### ISSUE TITLE
docs: Node.js + Sequelize | Postgres docs don't show how to use TLS certs to authenticate in production

### ISSUE THREAD

**Issue by grempe** [cockroachdb/cockroach#16837]
The current docs for Node.js applications using Sequelize or Postgres npm packages are all created assuming operation in a non-production `--insecure` environment. When bringing an application to a shiny and new production environment, configured to use TLS for node and client authentication, I ran into a brick wall with how to use those packages to communicate with CRDB.

https://www.cockroachlabs.com/docs/stable/build-a-nodejs-app-with-cockroachdb-sequelize.html

https://www.cockroachlabs.com/docs/stable/build-a-nodejs-app-with-cockroachdb.html

After much digging around (I only found a single hint that allowed me to get it to work) I came up with the following solution which seems to be working for me.

Note the addition of the `dialectOptions` property which includes the three required certificates as string values. I have also been able to make this work by storing those string values as environment variables instead of reading from a local filesystem's `certs` dir.

```
const fs = require('fs')
let Sequelize = require('sequelize-cockroachdb')

let sequelize = new Sequelize('MYDB', 'MYUSER', 'MYPASS', {
  dialect: 'postgres',
  dialectOptions: {
    ssl : {
        rejectUnauthorized : false,
        ca   : fs.readFileSync("./certs/ca.crt").toString(),
        key  : fs.readFileSync("./certs/client.foo.key").toString(),
        cert : fs.readFileSync("./certs/client.foo.crt").toString(),
    }
  },
  host: '10.0.0.0',
  port: 26257
})

const User = sequelize.define('user', {
  name: {
    type: Sequelize.STRING
  }
})

User.sync({force: true}).then(() => {
  User.create({
    name: 'Bill'
  }).then(result => {
    User.findAndCountAll().then(result => {
      console.log(result.count)
      // console.log(result.rows)
    })
  })
})
```

Please update the documentation and samples to include usage in the required production TLS setup.  This may also be an issue for other runtimes/ORM's that you document with examples.

**Comment by grempe** [comment]
PS Thanks to @brianc for the tip

https://github.com/brianc/node-postgres/wiki/SSL-support

**Comment by dianasaur323** [comment]
@grempe Thanks for your suggestion. Improving our documentation around using certs has been on our radar for quite some time now. I've assigned @jseldess so that he can prioritize and take a look.

**Comment by knz** [comment]
This is a docs issue, closing in favor of https://github.com/cockroachdb/docs/issues/3416.
