### ISSUE TITLE
sql: funky recursivity caused by prepared statements - no 1pc for EXECUTE

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#16844]
When seeing an `EXECUTE` stmt, the `Executor` recurses into `execParsed()`.
https://github.com/cockroachdb/cockroach/blob/cdfc68af81c962831033098551de3846e409cec1/pkg/sql/executor.go#L593
https://github.com/cockroachdb/cockroach/blob/cdfc68af81c962831033098551de3846e409cec1/pkg/sql/executor.go#L1350

This is generally not cool because it makes thinking about the executor state machine difficult; it's difficult enough without recursion. We now have a `client.Txn.Exec()` closure running inside another `client.Txn.Exec()` closure.
One concrete consequence of this is that 1PC will always be disabled for prepared statements executed through `EXECUTE` (because it looks to the `Executor` like the inner stmt is always executed inside a higher-level txn). Another one is that, in case of errors of the prepared statement, this breaks some assumptions leading to error messages:
- `client.Txn.Exec()` assumes that, if the closure didn't return an error, the transaction proto is not `Aborted`.
https://github.com/cockroachdb/cockroach/blob/cdfc68af81c962831033098551de3846e409cec1/pkg/internal/client/txn.go#L685
- the `Executor.execParsed()` assumes that errors and state transitions happen in unison.
https://github.com/cockroachdb/cockroach/blob/cdfc68af81c962831033098551de3846e409cec1/pkg/sql/executor.go?utf8=%E2%9C%93#L782

These both seem like sane assertions to me, and they are invalidated by the fact that, in the case of `EXECUTE`, there's now an outer statement and an inner statement, and state transitions happen without the cooperation of the outer statement. In other words, an assumption of the outer `execStmtInOpenTxn()` is broken because the state changes from under it.

I've thought about doing something for a bit, but decided to leave it to the experts. I think we should translate the `EXECUTE` into the real statement without recursion.

Also, please do something about the naming of `e.ExecutePreparedStmt()` - the executor also has a `ExecutePreparedStatement()`.

I'm not sure who to assign this to, but I think it's pretty important we find someone to fix it :). Or perhaps you can argue that the recursion is necessary, but then I think other things need to be changed in the `Executor`.

Touches #7881

cc @knz @mjibson

**Comment by jordanlewis** [comment]
Hmm that's messed up - thanks for noticing. I'll try to fix this up soon. To be clear this only happens in a SQL `EXECUTE preparedStmt` statement - the pre-existing pgwire prepare/execute pipeline is unaffected and continues to behave correctly as before.
