### ISSUE TITLE
testserver - travisCI - illegal instruction (core dumped)

### ISSUE THREAD

**Issue by b3ntly** [cockroachdb/cockroach#16845]
**BUG REPORT**

1. Log File unavailable (this took place in Travis)

2. Please describe the issue you observed:

- What did you do?

I attempted to start a testserver within a Travis Build but it led to a -1 exit with the output shown [here](https://travis-ci.org/b3ntly/twelvefactor/builds/249727045)

- What did you expect to see?

I expected the test to pass as it did on my local machine.

- What did you see instead?

The -1 exit code.

RESOLUTION:

On a hunch I was able to resolve the issue by adding the following line at the top of my travis.yml file:

sudo: true

I'm assuming there are constraints in the non-sudo environment that prevented the cockroachdb testserver from running, either way it would be nice to remove the sudo requirement as it does slow down builds.

**Comment by andreimatei** [comment]
@mberhault, can this be the avx2 regressions discussed here?https://github.com/cockroachdb/cockroach/pull/16808#issuecomment-312619183

I forgot which version the testserver downloads by default.

**Comment by bdarnell** [comment]
`testserver` downloads builds from `master`, not the release: https://github.com/cockroachdb/cockroach-go/issues/19
