### ISSUE TITLE
sql: "SHOW INDEXES" claiming table does not exist

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#16858]
`build:      CCL b5fffc159 @ 2017/07/05 16:23:29 (go1.8.1)`

- What did you do?
`cockroach sql -d test`
```
root@:26257 ?> CREATE DATABASE test;
root@:26257/test> show tables;
+-------+
| Table |
+-------+
+-------+
(0 rows)
root@:26257/test> CREATE TABLE "A" ("id" serial NOT NULL PRIMARY KEY, "uni" varchar(1000) NOT NULL);
CREATE TABLE
root@:26257/test> SHOW INDEXES FROM a;
pq: table "a" does not exist
root@:26257/test> show create table a;
+-------+-------------------------------------------------+
| Table |                   CreateTable                   |
+-------+-------------------------------------------------+
| a     | CREATE TABLE a (␤                               |
|       |     id INT NOT NULL DEFAULT unique_rowid(),␤    |
|       |     uni STRING(1000) NOT NULL,␤                 |
|       |     CONSTRAINT "primary" PRIMARY KEY (id ASC),␤ |
|       |     FAMILY "primary" (id, uni)␤                 |
|       | )                                               |
+-------+-------------------------------------------------+
(1 row)
root@:26257/test>
```
- What did you expect to see?
Some indexes.

- What did you see instead?
`pq: table "a" does not exist`

**Comment by eisenstatdavid** [comment]
Looks like SHOW INDEXES isn't looking up its argument in a case-insensitive fashion, since the table name is `"A"` (i.e., capital A).

What does `SHOW INDEXES FROM "A"` do?

**Comment by knz** [comment]
It works fine. I just checked.

This is an instance of the code doing what it should ultimately do :)

**Comment by knz** [comment]
This will benefit from the changes in https://github.com/cockroachdb/cockroach/pull/16760.

**Comment by JYKeith123** [comment]
seems it's not fixed?

I just created this table, and 'show index' is not working on the table.
`
create table if not exists "Makgeolli_v1_temp_data" (
	id			 		serial primary key,
	data_time			timestamp not null default current_timestamp(),
	outer_temperature	float not null,
	outer_humidity 		float not null CONSTRAINT valid_humidity check (outer_humidity between 0.0 and 100.0),
	inner_temperature 	float not null,
	index date_time_idx (data_time)
);
`

`
docker@cockroach:~/cockroach_binary/cockroach-latest.linux-amd64$ ./cockroach version
Build Tag:    v1.0.6
Build Time:   2017/09/14 15:15:48
Distribution: CCL
Platform:     linux amd64
Go Version:   go1.8.3
C Compiler:   gcc 6.3.0
Build SHA-1:  8edb4c9235a7bb8aa80761375db12bb4a7e5afeb
Build Type:   release
docker@cockroach:~/cockroach_binary/cockroach-latest.linux-amd64$
`

`
CREATE TABLE
root@:26257/brew_data> show tables from brew_data;
+------------------------+
|         Table          |
+------------------------+
| Makgeolli_v1_temp_data |
+------------------------+
(1 row)
root@:26257/brew_data> select * from Makgeolli_v1_temp_data;
+----+-----------+-------------------+----------------+-------------------+
| id | data_time | outer_temperature | outer_humidity | inner_temperature |
+----+-----------+-------------------+----------------+-------------------+
+----+-----------+-------------------+----------------+-------------------+
(0 rows)
root@:26257/brew_data> SHOW INDEX FROM Makgeolli_v1_temp_data;
pq: table "makgeolli_v1_temp_data" does not exist
root@:26257/brew_data>
`
