### ISSUE TITLE
sql: ParallelizeQueue is too pessimistic and doesn't parallelize writes to the same table

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#16862]
Writes are treated by the `ParallelizeQueue` as touching the whole table they operate on, which means that writes to the same table are not executed concurrently. This seems like a big limitation and I think that generally we can do better and figure out what keys will be written.

cc @robert-s-lee

**Comment by andreimatei** [comment]
@nvanbenschoten you said this was improved, right?

**Comment by nvanbenschoten** [comment]
Yes, it was improved in https://github.com/cockroachdb/cockroach/pull/17757. I'm going to close this issue, as I don't see us improving things any further with the ParallelizeQueue.
