### ISSUE TITLE
sql: ON CONFLICT UPDATE (UPSERT) of timestamp column from clock_timestamp() fails with wrong type failure

### ISSUE THREAD

**Issue by HeikoOnnebrink** [cockroachdb/cockroach#16873]
**BUG REPORT**

CockroachDB node starting at 2017-07-03 04:33:31.340059911 +0000 UTC
build:      CCL 82c3153-dirty @ 2017/06/19 05:22:23 (go1.8.3)
admin:      http://api-1.openstack.local:8080
sql:        postgresql://root@10.96.214.113:26257?sslmode=disable
logs:       /cockroach/cockroach-data/logs
locality:   datacenter=dus10
store[0]:   path=/cockroach/cockroach-data
status:     restarted pre-existing node
clusterID:  5042aeec-cc3e-4fce-91a4-47aa1da7c505
nodeID:     1

Testcase
```
CREATE TABLE A (col int PRIMARY KEY, date TIMESTAMP); 
INSERT INTO A VALUES (1,clock_timestamp())
ON CONFLICT (col) DO UPDATE SET date = clock_timestamp() WHERE col = 1;
```

First (insert branch) execution of above SQL works fine and inserts a record with timestamp into A
Second (update branch) execution raises error..

```
pq: value type timestamptz doesn't match type TIMESTAMP of column "date". 
```

Direct execution of update command works 

```
UPDATE a SET date = clock_timestamp() WHERE col = 1
```

**Comment by jordanlewis** [comment]
This is easily reproducible. Note that `clock_timestamp` has `timestamp` and `timestamptz` producing variants, indicating that this is likely an issue with overload resolution.
