### ISSUE TITLE
sql: simple EXPLAIN has confusing output

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#16890]
```
root@:26257/> EXPLAIN SELECT 1;
+-------+---------+-------+-------------+
| Level |  Type   | Field | Description |
+-------+---------+-------+-------------+
|     0 | render  |       |             |
|     1 | nullrow |       |             |
+-------+---------+-------+-------------+
```

This seems like it could be made a little friendlier. Postgres calls this a `result` plan - that makes more sense to me. This could cause confusion if it were embedded in a deeper plan, so I think we should improve the output here.

cc @knz for his thoughts

**Comment by knz** [comment]
Can you be a bit explicit about what you expect here?

I personally expect the output of EXPLAIN to be a *faithful* description of the data structures used for the query plan. It so happens that the `nullrow` is a rather fundamental necessary jigsaw piece to make `select 1` work in the absence of a `from` clause.

**Comment by jordanlewis** [comment]
I expect a user-friendly name in the `type` field, something like "explicit value". The use case I'm concerned with is a situation where a user is trying to understand how CockroachDB has planned a very large query. Deep in the query, there might be an explicit `SELECT` like this that produces the scary sounding (IMO) plan type `nullrow`. This could produce user confusion and panic!

I'm just suggesting to change the name from `nullrow` to something that sounds less like a problem. To a user who is inexperienced with any kind of software system, `null` often indicates that there's an problem with the software.

**Comment by knz** [comment]
here you see I think I am detecting a misundersting on your part.

`nullrow` is doing precisely what is says on the label: it produces a single (hence the singular form) row of NULL values. 

It is not about "explicit values" - in this case the explicit values are produced by the render expressions in the renderNode.

**Comment by jordanlewis** [comment]
Ah! Yes, an absolute misunderstanding. Thank you for explaining.

In that case, I propose suppressing the `nullrow` value for `SELECT` statements without data sources.
