### ISSUE TITLE
cli/node+config: Get node networking information

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/cockroach#16895]
`cockroach node status` includes an `address` for each node, but does not include other relevant networking information such as:

- `host` vs. `advertise-host`
- If `cockroach` is listening on all interfaces or only the `address` listed
- Admin UI port (or preferably known address)

Also, the `advertise-host` value isn't printed at node startup (though it is surfaced in the admin UI).

**Comment by jseldess** [comment]
The ability to recall this information came up once before. The solution then was to print it all to the logs as well as to stdout. I like the idea of using a command to get this info though.

**Comment by knz** [comment]
This information is now available via crdb_internal tables.

**Comment by jseldess** [comment]
@knz, I really want to finish the api policy docs work we started some months ago, but just checking: Is it ok for us to tell users how to get these details via the internal tables? I do still think it would be wonderful to be able to easily retrieve the start flags and/or the details printed to stdout after joining a node.

**Comment by knz** [comment]
we'll want to distinguish "reserved" from "public" columns
otherwise yes that will be the way forward
