### ISSUE TITLE
restore: push SSTable ingestion write amplification to 1x

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#16937]
We currently make a copy of the sideloaded SSTable and ingest the copy. We should instead be able to ingest the original, but the fact that RocksDB may mutate the file (in a predictable way: writing a sequence number) makes this nontrivial.

It would be enough to write a "sanitizer" that reads a SSTable from disk but nulls out the sequence number again.

This is, of course, assuming that no other modifications to the SSTable are possible. Even if these modifications are inconsequential for the ingested data, it will trip up our checksumming.

**Comment by bdarnell** [comment]
Another thing to watch out for is that if we're using hard links we must make sure we never ingest the same file twice, since each ingestion will try to make conflicting modifications to the file.

**Comment by dt** [comment]
#22281
