### ISSUE TITLE
restore: investigate "ingestion behind" option for SSTables

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#16934]
From https://github.com/facebook/rocksdb/wiki/Creating-and-Ingesting-SST-files: I wonder if that is a useful option for SSTable ingestion during restore. Sure seems to me at first glance and it could help avoid anomalies that required special care in #16924 when there is already data in the range.

Ingestion Behind

Starting from 5.5, IngestExternalFile() will load a list of external SST files with ingestion behind supported, which means duplicate keys will be skipped if ingest_behind==true. In this mode we will always ingest in the bottom mode level. Duplicate keys in the file being ingested to be skipped rather than overwriting existing data under that key.

Use case

Back-fill of some historical data in the database without over-writing existing newer version of data. This option could only be used if the DB has been running with allow_ingest_behind=true since the dawn of time. All files will be ingested at the bottommost level with seqno=0.

**Comment by tschottdorf** [comment]
I guess the problem is with deletions, huh? Probably hard to overcome those...

**Comment by danhhz** [comment]
I don't think ingest behind actually solves any of our issues. The hard part about removing the range clear that we currently do is fixing the mvcc stats computation. I think this feature is more targeted towards a RocksDB instance that doesn't use mvcc keys

**Comment by tschottdorf** [comment]
Ack, closing.
