### ISSUE TITLE
sql: proposal to add a virtual table to query time series metrics

### ISSUE THREAD

**Issue by rjnn** [cockroachdb/cockroach#16957]
Currently, adding time series metrics to the Admin UI is difficult, because the workflow involves two somewhat orthogonal sets of operations:
1) Think hard about the metric you want, reason about its semantics, and add the code to capture the metric.
2) Write UI code to display this metric in a new graph in the Admin UI.

The problem is that when we see bugs in a graph (of which there have been many), or even when simply adding a new metric, debugging whether we've made a subtle mistake in the semantics (part 1) or in the display code (part 2) is difficult to isolate, and we waste a lot of time debugging this. The testing cycle is also unnecessarily long, as we cannot add unit tests for metrics easily. Bugs also creep in as we "eyeball" metrics.

I propose that we add a virtual table that exposes all the time series metrics in the SQL terminal. This way, we can reason about (1) in isolation and add tests for the semantics of various metrics. Second, this means that writing UI code for engineers new to the UI is also easier to debug: you just need to ensure the UI shows exactly the same numbers as the virtual table.

It's not clear to me if
1) this already exists in some other form, in which case the work to be done is just adding more documentation
2) this is difficult/impossible for some reason that I can't see
3) this is deemed not worth the effort

cc @cuongdo @couchand @mrtracy for thoughts.

Jira issue: CRDB-6055

**Comment by a-robinson** [comment]
Without commenting on whether we should do this (beyond noting that mapping/restricting SQL queries to timeseries queries will take quite a bit of thought), I'll just say that pushing to a prod cluster and using Grafana has worked great for me in the past when I wasn't sure about a metric.

**Comment by a-robinson** [comment]
Although at the very least a tool to do some basic timeseries queries from the command line would be nice, since we don't seem to have any code for making timeseries requests other than in our UI.

**Comment by dianasaur323** [comment]
you know, some users have also asked about if they could do these types of queries as well. However, I don't think this would be a particularly valuable tool for users as of yet (given relatively few requests for this), so would be more of a tool to speed things up internally. Engineering's call on if we do this, but we would have to take time away from some other things we are working on to accommodate?

**Comment by a-robinson** [comment]
I already threw together a very primitive `cockroach debug timeseries` command for my own use. It won't be suitable for a whole lot other than very basic debugging, but I'll send it out for inclusion in a release once I get a little free time.

**Comment by dianasaur323** [comment]
Sounds good. Thanks! I'll put it in 1.2 for now.

**Comment by knz** [comment]
I have investigated this further and it would require a large refactor of the vtable infrastructure if indeed provided as vtable.

What we can do instead is to create a new kind of tableReader (that would read the data "as it goes" from KV) and a dedicated virtual SQL schema that would enable the new tableReader to translate the ts data from KV into SQL datums fit for further query processing.

It's no small task though. Also it's not a UI project - rather, a SQL project.

@jordanlewis what do you think? Perhaps a starter project for a new hire?

**Comment by asubiotto** [comment]
cc @piyush-singh for prioritization

**Comment by knz** [comment]
This came up earlier this week in the context of providing troubleshooting tooling for a customer (not named here) who is unwilling/unable to access their admin UI. 

We want them to scrape out historical metrics from their cluster in a way we can reuse.

This could be achieved by introducing a SQL-level facility to query the tsd. MAybe a vtable is not the best way (as identified above) and instead we could work with some kind of built-in function or something else entirely (not sure what yet).

The end goal though should be to provide some way to get historical monitoring data out of crdb's tsd via SQL.
