### ISSUE TITLE
hlc: Detect local time jumps

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#16959]
We currently detect clock offsets with RPC heartbeats, which cannot be run too frequently because of the associated network traffic. We could have local-only detection of clock jumps using a goroutine that loops on a Ticker and compares the actual time when it wakes up to the expected time. A significant deviation from the expected interval is a sign that the clock has jumped (or that the process has been blocked by something like GC stop-the-world, but that amounts to the same thing for the risk of stale reads). Since clock jumps are unlikely to be perfectly synchronized across nodes, this would indicate that we are likely to need to restart when our next RPC heartbeat offset measurement is performed, so we could go ahead and abort the process when the clock jump is detected. This would narrow the window in which we could serve stale reads.

**Comment by petermattis** [comment]
I whipped this up a while back while investigating something: https://github.com/petermattis/cockroach/commit/4c0eef90bc847c40aa07108eac621b503cbe5d18
