### ISSUE TITLE
restore: TPC-H restore from azure is broken on master

### ISSUE THREAD

**Issue by arjunravinarayan** [cockroachdb/cockroach#16966]
`git checkout master`
`make build`
`./cockroach start --insecure --background`
`./cockroach sql --insecure`
```
root@:26257/> create database tpch;
CREATE DATABASE
root@:26257/> set cluster setting enterprise.enabled = true;
SET
root@:26257/> RESTORE tpch.* FROM 'azure://backup-test/benchmarks/tpch/scalefactor-1?AZURE_ACCOUNT_NAME=<omitted>&AZURE_ACCOUNT_KEY=<omitted>';
pq: failed to read backup descriptor: failed to create azure reader: Get https://cockroachbackuptest.blob.core.windows.net/backup-test/benchmarks/tpch/scalefactor-1/BACKUP: x509: failed to load system roots and no roots provided
```

Checking out `v1.0.3` and running the above commands does not result in the same error; it restores fine.

**Comment by danhhz** [comment]
@mjibson looks like the azure export storage is acting up

**Comment by mjibson** [comment]
I wasn't able to reproduce this on my machine. What environment are you running on? Docker, GCE, AWS, laptop? The cert error is suspicious.

**Comment by arjunravinarayan** [comment]
laptop (OS X), just vanilla checkouts of master and v1.0.3 respectively.

**Comment by arjunravinarayan** [comment]
Closed as unreproducible, it appears there was some certificate failures, that could have been caused by not doing complete `make clean && make build` builds.
