### ISSUE TITLE
build-docker-dev.sh delete dpkg files

### ISSUE THREAD

**Issue by YuleiXiao** [cockroachdb/cockroach#1698]
I execute build-docker-dev.sh to build docker image. but I found this script will delete  /var/lib/{apt,dpkg,cache,log}. after this , when I execute apt-get update, it report "failed to open package info file `/var/lib/dpkg/status' for reading". 

I think we should not delete these files.

Building Docker Cockroach images...
Sending build context to Docker daemon 20.99 kB
Sending build context to Docker daemon 
Step 0 : FROM golang:1.4.2
 ---> 124e2127157f
Step 1 : MAINTAINER Tobias Schottdorf <tobias.schottdorf@gmail.com>
 ---> Using cache
 ---> f2bcb169f9e3
Step 2 : RUN apt-get update -y && apt-get dist-upgrade -y && apt-get install --no-install-recommends --auto-remove -y git build-essential pkg-config file npm &&  apt-get clean autoclean &&  apt-get autoremove -y &&  rm -rf /tmp/* /var/lib/{apt,dpkg,cache,log} && ln -s /usr/bin/nodejs /usr/bin/node

**Comment by tschottdorf** [comment]
Hi @YuleiXiao, yes. Feel free to open a PR making that change.
Thanks,
Tobias

**Comment by YuleiXiao** [comment]
OK, I will open a PR. Thank you.
@tschottdorf
