### ISSUE TITLE
acceptance: max clock offset exceeded in nightly photos test

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#16999]
* build: 6b48d06
* failed test: [continuous photos load, 4 hours 6 nodes ](https://teamcity.cockroachdb.com/viewLog.html?buildId=294155&buildTypeId=Cockroach_Nightlies_ContinuousPhotos4Nodes6hours)
* [logs for failing node](https://teamcity.cockroachdb.com/viewLog.html?buildId=294155&buildTypeId=Cockroach_Nightlies_ContinuousPhotos4Nodes6hours&tab=artifacts#!12njl7i)

The issues started right after node startup:

```
W170712 06:20:05.975087 13418 storage/replica.go:2561  [n4,s4,r1/4:/{Min-System/}] context cancellation after 0.0s of attempting command RequestLease [/Min,/Min)
I170712 06:20:08.875706 3559 vendor/google.golang.org/grpc/transport/http2_client.go:954  Client received GoAway with http2.ErrCodeEnhanceYourCalm.
```

About 19 minutes after node startup, a stream of these warnings occurs:

```
W170712 06:39:41.891737 3469 ts/db.go:114  [n4,ts-poll] error writing time series data: storage/store.go:2460: rejecting command with timestamp in the future: 1499841581846724547 (508.613846ms ahead)
```

25 minutes into the test, the node crashes:

```
W170712 06:45:21.896630 3469 ts/db.go:114  [n4,ts-poll] error writing time series data: storage/store.go:2460: rejecting command with timestamp in the future: 1499841921882653599 (549.905815ms ahead)
E170712 06:45:28.058467 3445 util/log/crash_reporting.go:183  [n4] Reported as error 8145a85be92040209c25cf967d00ecc5
F170712 06:45:28.058489 3445 server/server.go:178  [n4] clock synchronization error: this node is more than 500ms away from at least half of the known nodes (2 of 4 are within the offset)
```

This is the first time this error has occurred since I first setup the disabling of the HyperV time sync on Azure. So, I suspect that a579c27fbc4f8951cf2e18a939ff9dee33d97ef3 is the culprit.

cc @mberhault in case he has thoughts on this

**Comment by cuongdo** [comment]
The call to `ntpdate -b` is failing:

```
[02:12:26][Step 3/3] null_resource.cockroach-runner.2 (remote-exec): + sudo apt-get -qqy install ntpdate
[02:12:26][Step 3/3] null_resource.cockroach-runner.2 (remote-exec): + sudo timedatectl set-ntp false
[02:12:27][Step 3/3] null_resource.cockroach-runner.2 (remote-exec): + sudo ntpdate -b ntp.ubuntu.com
[02:12:27][Step 3/3] null_resource.cockroach-runner.2 (remote-exec): 12 Jul 06:12:27 ntpdate[13692]: the NTP socket is in use, exiting
```

**Comment by cuongdo** [comment]
Actually, I'll look into this, since I have Terraform setup already.

**Comment by mberhault** [comment]
Yeah, `timedatectl set-ntp false` doesn't let ntpdate run, the socket it
still busy.

**Comment by RaduBerinde** [comment]
Hm, can't repro on azworker, tried `while true; do date; sudo timedatectl set-ntp false; sudo ntpdate -b ntp.ubuntu.com; sudo timedatectl set-ntp true; done`

**Comment by mberhault** [comment]
Do the azworkers have ntp installed? If not, that's probably why.

**Comment by RaduBerinde** [comment]
It has the systemd timesync service installed by default. Do these systems install ntp in addition to that?

Maybe adding the `-u` flag would help (https://superuser.com/a/639516/595017)

**Comment by RaduBerinde** [comment]
I see that we install `ntp` in `main.tf`. We should not do that. Or, if we want to standardize on using ntp instead of systemd-timesync, we should install ntp in the azworker as well and revert the change to this script.

**Comment by RaduBerinde** [comment]
Note that when `ntp` is installed, when we stop the service, `systemd-timesyncd` takes over and still syncs the clock. So the correct thing to do is to still disable the latter with `timedatectl set-ntp false`. This is all very confusing so I think the best thing is to stop using ntp and just rely on the default systemd mechanism.
