### ISSUE TITLE
sql: support for ORDER BY PRIMARY KEY would be useful

### ISSUE THREAD

**Issue by arjunravinarayan** [cockroachdb/cockroach#17005]
The precise syntax is bikesheddable, but it would be nice to have a shorthand syntax for ordering results by primary key ordering.

Postgres doesn't officially guarantee ordering if the ordering is unspecified, but typically a `SELECT * LIMIT 1` gives you the first row by PK order (at least, in my experience). In a distributed setting like CockroachDB, this is far less likely to be the case: You just get the first row that's (latency-wise) closest to you. The ordering volatility is far higher with CockroachDB than Postgres, so having helper syntax to mitigate this is more important for us than what just following Postgres' feature-set would indicate.

Sometimes I work with a table that has a complex multi-column primary key, and typing "ORDER BY" with a subquery on `information_schema` is tedious. It would be nice to have a syntactic shorthand for this. This situation also occurs frequently in testing when I'm probing a table to choose a split point (for subsequently using `ALTER TABLE SPLIT AT VALUES...`).

cc @knz

**Comment by knz** [comment]
So we already have a syntax to specify indexes, e.g. `select * from mytable@primary` will order by the PK as long as the create table statement didn't override the PK index' name.

Is it right to understand that you would like to extend this ability to make it possible to guarantee PK index selection even if it has a different name?
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by arjunravinarayan** [comment]
Yes. I don't know why people ever rename their primary key indexes, but apparently they do.

**Comment by andreimatei** [comment]
Does the `select for table@index` imply an ordering?

**Comment by knz** [comment]
@andreimatei this syntax is a crdb extension, it currently happens to work and we could from now on also specifies that it works.

**Comment by arjunravinarayan** [comment]
1. What would be the point of reading from a specific index and not following that index's order?
2. The `select from table@index` isn't well documented. (Basically just the syntax diagrams)

**Comment by andreimatei** [comment]
The point is to force index selection. E.g. consider the non-obvious choice between a covering index and an index that limits the search space but is not covering.
I don't think that the syntax currently has anything to do with ordering; I don't think that it "happens to work" as @knz says. But I haven't checked the code so I could be wrong. (Or maybe it works by virtue of DistSQL not accepting this syntax?)

**Comment by knz** [comment]
@andreimatei distsql does support the syntax. Which also implies my idea is bogus - the ordering has nothing to do with which index is used, so it's not sound to recycle the index selection syntax to determine ordering.

**Comment by arjunravinarayan** [comment]
Well, then I got lucky using that syntax to get an ordering (or maybe didn't notice that I was getting wrong results!).

Nevertheless, it would be nice to have `ORDER BY <index>`. Are we agreed on that?

**Comment by knz** [comment]
yes I am working on it now.
