### ISSUE TITLE
sql: collated strings don't always need to be "composite" key/values

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#17015]
We have the ability to decide on a per-row basis whether a specific datum requires composite encoding (via `CompositeDatum.IsComposite`). We use this for decimals (only those ending in a `0` need to be composite).

I think we should consider doing the same for collated strings - if the collation key happens to match the string exactly (which in practice should be very common I think?) we don't need the composite decoding.

CC @knz @eisenstatdavid

**Comment by eisenstatdavid** [comment]
The collation key is never equal to the string as far as I can tell -- the algorithm to construct it logically outputs integer weights that get encoded as bytes. I don't know how to fast path this code without destroying the sort order, and for people for whom that's OK, there's `STRING`.
