### ISSUE TITLE
stability: OOMs on v1.1x due to jemalloc 5.0.0 changes.

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#17013]
Lightstep tracing has been disabled on our test clusters since we moved it to a cluster setting. I just re-enabled it this morning as part of cluster setting initialization: https://github.com/cockroachlabs/production/pull/443

Shortly after filling in the lightstep token, clusters started either OOMing (`omega`, `adriatic`) or experiencing massive memory spikes (`blue`, `cyan`). All running v1.1. The 1.0 cluster are still getting their lightstep tokens through environment variables and have not been experiencing this.

Here are a few examples: lightstep tokens were set fleet-wide around 14UTC.
Cyan: not OOMing because of the frequent continuous-deployment restart.
![cyan](https://user-images.githubusercontent.com/5901480/28141178-7b8c766c-6729-11e7-8a0c-7e8f8cfde445.png)

Adriatic: OOming:
![adriatic](https://user-images.githubusercontent.com/5901480/28141217-a44a75fe-6729-11e7-8a5d-ceb9161c5357.png)

Jira issue: CRDB-7187

Epic CRDB-20293

**Comment by mberhault** [comment]
may be related to #16964

**Comment by mberhault** [comment]
`trace.debug.enable` was also set to true. I'm thinking this may have an impact as well, albeit not as huge as lightstep.
I'll try to reproduce this with clean runs. eg: disable all tracing, full stop/start cluster (not rolling), selectively enable tracing

**Comment by mberhault** [comment]
Debug tracing and lightstep have been disabled for a while, but multiple clusters are still OOMing, albeit less frequently.
`omega` is slow growing over time and OOMing from time to time, even with the `kv` load generator turned off.
This all seems to be coming from C with odd stats being  returned by jemalloc:
Here's a sample on `cockroach-omega-0006` from shortly after startup (needs `vmodule=runtime_jemalloc=2`) until manually stopped (nodes tend to freeze up for tens of minutes after OOM).
```
I170717 15:03:02.286970 1 cli/start.go:611  CockroachDB CCL bf59245 (linux amd64, built 2017/07/17 03:46:54, go1.8.3)
I170717 15:06:14.000415 345 server/status/runtime_jemalloc.go:120  [n6] jemalloc stats: Allocated: 4.8 GiB Active: 5.4 GiB Metadata: 41 MiB Resident: 6.8 GiB Mapped: 6.8 GiB Retained: 1.6 GiB
I170717 15:26:44.008764 345 server/status/runtime_jemalloc.go:120  [n6] jemalloc stats: Allocated: 4.7 GiB Active: 5.2 GiB Metadata: 59 MiB Resident: 11 GiB Mapped: 11 GiB Retained: 4.7 GiB
```

This is 20 minutes and mapped memory keeps increasing, but active it fairly stable.
For more info, here are the entries from the man page:
```
"stats.mapped" (size_t) r- [--enable-stats]
	   Total number	of bytes in active chunks mapped by the	allocator.
	   This	is a multiple of the chunk size, and is	larger than
	   "stats.active". This	does not include inactive chunks, even those
	   that	contain	unused dirty pages, which means	that there is no
	   strict ordering between this	and "stats.resident".

       "stats.retained"	(size_t) r- [--enable-stats]
	   Total number	of bytes in virtual memory mappings that were retained
	   rather than being returned to the operating system via e.g.
	   munmap(2). Retained virtual memory is typically untouched,
	   decommitted,	or purged, so it has no	strongly associated physical
	   memory (see chunk hooks for details). Retained memory is excluded
	   from	mapped memory statistics, e.g.	"stats.mapped".
```

While tracing and lightstep may be making this worse, I'm rather suspecting problems due to the recent switch to jemalloc 5.0.1.

**Comment by mberhault** [comment]
And to illustrate, this is `cockroach-omega-0006` after about 10 minutes without load generator:
![omega_mem](https://user-images.githubusercontent.com/5901480/28279019-23b44272-6aed-11e7-80fa-34f96587a016.png)

**Comment by mberhault** [comment]
I think this may be due to https://github.com/jemalloc/jemalloc/commit/63b5657aa566ceab270ff6e9d4f366233d2d0b79 which went into 5.0.1. This removes the dirty pages from a ratio-based process (it used to default to 8:1 ratio of active/dirty pages) and towards a decay-based one.

**Comment by mberhault** [comment]
To confirm this, I added `dirty_decay_ms:0` to `MALLOC_CONF`. This forces all dirty pages to be released right away:
```
opt.dirty_decay_ms (ssize_t) r-
Approximate time in milliseconds from the creation of a set of unused dirty pages until an equivalent set of unused dirty pages is purged (i.e. converted to muzzy via e.g. madvise(...MADV_FREE) if supported by the operating system, or converted to clean otherwise) and/or reused. Dirty pages are defined as previously having been potentially written to by the application, and therefore consuming physical memory, yet having no current use. The pages are incrementally purged according to a sigmoidal decay curve that starts and ends with zero purge rate. A decay time of 0 causes all unused dirty pages to be purged immediately upon creation. A decay time of -1 disables purging. The default decay time is 10 seconds. See arenas.dirty_decay_ms and arena.<i>.muzzy_decay_ms for related dynamic control options. See opt.muzzy_decay_ms for a description of muzzy pages.
```

Dirty page count is now always zero, and cgo mapped memory is now much more in line with active.
Here's a comparison of two ~7-10 minute runs, the first with default jemalloc 5.0.1 options, the second with `dirty_decay_ms:0`:
![omega_mem_nodecay](https://user-images.githubusercontent.com/5901480/28281129-145fe4dc-6af4-11e7-955e-79fe40b640c5.png)

**Comment by mberhault** [comment]
Correction, https://github.com/jemalloc/jemalloc/commit/63b5657aa566ceab270ff6e9d4f366233d2d0b79 went into 5.0.0 not 5.0.1.

This is present in v1.1-alpha.20170713, although as this issue shows I thought it was due to re-enabling tracing.

Here are a few things to do:
* report upstream and see what can be done and whether this is a bug
* roll back to pre 5.0.0

Before going back to 5.0.0, we'll need to figure out if some changes went in to jemalloc to help us, if we need to change default settings, or if we need to figure out how to make our usage of rocksdb not get hit by this.

**Comment by mberhault** [comment]
This is rolled back to 4.5.0 for now, and I've filed https://github.com/jemalloc/jemalloc/issues/956 with jemalloc.
Keeping this open until we can figure out how to move to 5.0.

**Comment by petermattis** [comment]
Have we revisited this? Was the upstream issue resolved?

**Comment by mberhault** [comment]
No movement on the issue, I'll ping it and look at upgrading jemalloc in the next cycle although it's not urgent in any way.

**Comment by tschottdorf** [comment]
@mberhault we're in no particular rush to do this for 2.1, correct? Think we should anyway?

**Comment by tschottdorf** [comment]
Removing the stability label because this doesn't actually affect anyone unless we decide to update jemalloc again.

**Comment by jordanlewis** [comment]
Close?

**Comment by bdarnell** [comment]
Reopening this because we're still pinned to jemalloc 4.5 and will need to resolve this in order to update.

**Comment by bdarnell** [comment]
Comments on https://github.com/jemalloc/jemalloc/issues/956 indicate that we should probably be enabling jemalloc's `background_thread` option.

**Comment by nicktrav** [comment]
Note to self - we now have the [`crl-release-5.2.1`](https://github.com/cockroachdb/jemalloc/tree/crl-release-5.2.1) branch on our fork that we can use to test this out.

There was also some testing done last year ([internal thread](https://cockroachlabs.slack.com/archives/CAC6K3SLU/p1626712210259500)) that showed that the difference between using jemalloc and stdmalloc was still material. It's likely that we'll want to keep jemalloc around.
