### ISSUE TITLE
sql: Support RANGE types

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#17022]
Postgres has a [set of RANGE](https://www.postgresql.org/docs/current/static/rangetypes.html) types. Basic support for these types would be pretty easy (they're essentially pairs of values with a few extra functions/operators), although the most interesting capabilities of these types require GIST indexes. 

Requested in https://github.com/cockroachdb/cockroach/issues/14988#issuecomment-315236230

**Comment by knz** [comment]
Superseded by #27791.
