### ISSUE TITLE
sql: better document the details of orderings

### ISSUE THREAD

**Issue by rjnn** [cockroachdb/cockroach#17028]
Orderings of streams is a complicated topic. The process of reviewing #16997 revealed that there are many subtleties in combining orders (e.g. when considering what ordering will result when merging two streams for a JOIN). These subtleties are not well documented, or particularly well understood outside the authors of the specific ordering code.

First, orderings are not well defined (and hence potentially non-deterministic) over two values that are semantically equal but representationally different (e.g. decimal `1.0` vs decimal `1.000`). This needs clarification, documentation, and potentially, addressing. This is complicated by the fact that we sometimes refer to columns as `exact match columns` (all values have the exact same value). Do we mean same representation, or same semantic meaning? I think in practice we mean the former, but it's not clear.

Second, what ordering implies what other ordering is subtle, and requires documenting with examples. For instance, an ordering of `3+,5-,4-` does not imply an ordering of `3+,4-`. Consider:

```
3 5 4         3 4
-------------------
1 2 2         1 2
1 2 1    ->   1 1
1 1 3         1 3
```

(Example courtesy @RaduBerinde). This might be obvious to someone experienced with the intricacies of orderings, but is not obvious to someone new to the subject (i.e. me). This requires some documentation that builds intuition and underlying concepts in a more structured way.

Finally, sometimes, one can underspecify the ordering one desires: e.g. sorted on column 1 Ascending, sorted on column 2 in either direction, sorted on column 3 descending. We don't really have a good way to represent this, and abuse things like `exact-match columns` in certain places to "defer" the decision of whether to treat an ordering as ascending or descending. This also requires a little bit more explanation.

Addressing this either needs a tech-note, or a large comment block at the start of `sql/ordering.go`, where the `orderingInfo` struct is defined.

cc @knz.

**Comment by cuongdo** [comment]
@arjunravinarayan are you the owner for this? if not, please reassign

**Comment by arjunravinarayan** [comment]
I'm happy to be the owner for this, but we should decouple this from the 1.1 milestone. It's not user-facing in any way.

**Comment by jordanlewis** [comment]
Something like this would still be nice!
