### ISSUE TITLE
log: on Fatal, dump any trace in ctx to logs

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#17036]
When we encounter a fatal (and perhaps even regular) error we should print the trace (if any) to stderr before exiting. This will likely involve some hackery using reflection as neither lightstep nor net/trace added anything to their `opentracing.Span` implementation that would facilitate this.

cc @RaduBerinde

**Comment by a6802739** [comment]
@tschottdorf  Maybe I could look at it. :)
