### ISSUE TITLE
server: can't hook initialization steps past cluster settings propagation

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#17032]
This is stalling progress on e.g.  #17020: I can't find a place in the code to put an initialization steps that runs 1) *after* the cluster settings are loaded / propagated via gossip but 2) *before* the server is ready for client connections.

**There should be a hook in the code, clearly documented as such, where one can add initialization code.**

@dt suggests:

> I'd probably go for the nonblocking write to a chan struct{} in settingsworker.go, the add a read (maybe w/timeout) to the startup path in server (maybe wrapped in a helper). could also go with a waitgroup if you made sure to only call Done the first time, or a cond var? not a perf-sensitive code path, so I would probably take simple over fast.

Unfortunately I was not myself able to translate this into code.

**Comment by bdarnell** [comment]
Potentially related to reworking of the server startup flow in #16371

**Comment by ajwerner** [comment]
I believe this is stale. We load settings before accepting client connections now IIUC. At least in secondary tenants this definitely happens and I'm working on unifying the behavior in #69269. I don't think this issue is providing anybody with value so I'm going to close it.
