### ISSUE TITLE
security: allow different security settings for admin UI vs cluster

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#17046]
Request from user as detailed here: https://forum.cockroachlabs.com/t/deactivate-ssl-on-the-dashboard-when-in-non-insecure-mode/807/3

Essentially, the user wants to run a secure cluster with an insecure admin UI dashboard. This is because they are already using a secured load balancer to connect to the admin UI. This is needed for easy integration with Rancher.

**Comment by bdarnell** [comment]
See also #14272, which asks for the ability to use different certificates (more browser-friendly) on the UI port than on the inter-node port. As I said in the forum thread, this is somewhat at odds with our desire to add richer functionality to the UI (which will make it unwise to run the UI insecurely). Unless problems like this are very widespread, it would be better for Rancher to be fixed to handle security properly.

**Comment by couchand** [comment]
I don't think this is something we're going to take up at this point.  We're moving in the direction of locking the admin UI down more consistently, not the other way.
