### ISSUE TITLE
restore/ingest: distributed ingestion without external/cloud storage

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#17057]
Currently RESTORE and distributed bulk-ingest in general works by each node fetching the files it needs directly from a cloud/external storage provider (s3 or some other http service, hdfs, etc).

We added a local filesystem reader option as well, but it doesn't really work for *distributed* ingestion -- any given node might need any given file in the backup, so opening a "local" disk to find a file only really makes sense if it is some shared, network filesystem like NFS.

Ideally though we would not impose a dependency on an external storage system like s3 or NFS to distribute data between nodes, and could instead allow pointing a node (or multiple nodes) local files that they then distribute to the other nodes as needed.

As a strawman, this could be as simple as, say, starting up a static file HTTP server in the backup directory, then using its address as the base URL for an HTTP storage scheme in a restore job. In practice, we probably want something a little fancier (i.e. that provides some auth or security).

cc @danhhz

**Comment by dt** [comment]
Some rough thoughts, cc @danhhz @tamird @bdarnell for feedback:
I think I'd like go approximately the route of the above strawman, but  use our existing gRPC service for this, just adding a new `blob` service to it. Reusing our gRPC server gets its auth/security, flow control, etc, rather than needing to re-roll all of that, with main downside just looking like plumbing.

Concretely, I think I want to define a `Blob` service in roachpb, make blob requests specify a name and namespace, then allow handlers to register for a namespace. We'd have a handler that can be pointed at an arbitrary directory on disk and serves static files by name.

A Restore/Ingest would create one of these file-backed handlers and register it with a namespace based on the restore jobID or something.

**Comment by dt** [comment]
One consideration: a nice-to-have here would be the ability of a client shell, i.e. a non-node process, to supply a RESTORE with its files. I'm tempted to say this is out-of-scope for now (sql clients don't participate in gossip, so it seems like a tall order) but it is worth thinking about in case we decide to built it later.

**Comment by bdarnell** [comment]
This seems scary from a security perspective. How would you configure this? (Specifically, I don't want SQL-level `root` access to be trivially escalatable to read arbitrary files from a node's disk). What if instead of configurable directories, we supported a directory under the store (`cockroach-data/ingest`), and admins could move (or symlink) files to be ingested there. 

I think for clients to supply files they could just start an HTTP server and the nodes talk back to them that way. Or we have them upload the data using the COPY protocol and the gateway does the ingestion work to convert them into restorable format.

**Comment by dt** [comment]
That's fair.

I think there's a pretty strong argument to be able to point directly to e.g. `/mnt/backups/db/2017...` though: it seems *very* likely that backups would be on a different device (i.e. big, low-IOPS disks are cheaper for bulk cold storage, keeping backups on separate devices to avoid SPOF, etc). A manually created symlink is thus a no-go. A manual copy into data dir before restore might be an operational obstacle though, as it could be expensive if not impossible just based on disk sizes (it also increases operational friction, but that's kinda the point).

Note that *currently* a root SQL shell can point at an arbitrary local path to *ingest* data -- that's reason `RESTORE` requires superuser, and not just any `CREATE` priv on the target DB.  Currently if you were to point it at something other than cockroach data though, it would just fail, so it seems unlikely to be a great way to read arbitrary files. We could add some of that sanity checking in the blob server too, and only send blobs that look like cockroach data (sst extension, backup desc or some sentinel file in same dir, etc).

I think if we don't allow pointing at arbitrary dirs, we're still going to need a story for those users with data outside their data-dir that they can't/don't want to copy, whether that is a standalone http server we ship or a just a doc on how to fire up nginx+mod-webdav. If we go that route, for simplicity I think we just use it for all local-file ingestion?

**Comment by bdarnell** [comment]
Why is a manually-created symlink a no-go? (symlinks have no problem spanning devices)

**Comment by dt** [comment]
Oh, yeah, you're right, cross-device symlinks should be fine. Given that, I'm happy to start by requiring supplied paths must begin with a storedir.

I think there's still a chance that, operationally, the ease of being able to just point to a backup, without needing to ssh in and manually symlink first, might be nice -- we may, down the road, convince ourselves that we can look at a dir and sufficiently determine if it is safe to expose, but that can always be a relaxation of the "must-be-in-storedir" rule we use initially.

**Comment by danhhz** [comment]
Optimistically saying this is closed by https://github.com/cockroachdb/cockroach/pull/17291
