### ISSUE TITLE
backup/restore: additional production testing

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#17059]
- [x] nightly benchmark for 2tb restore
- [x] nightly benchmark for tpch-10 on 4 & 10 nodes
- [x] turn on chaos on all nodes on lapis
- [x] test restore on clusters with existing data
- [x] TODO what additional testing?
- [x] automated chaos testing

**Comment by danhhz** [comment]
I'm removing "nightly backups of production cluster" and splitting it out into its own issue. this is done otherwise

**Comment by benesch** [comment]
Where's the new issue for nightly backup of production cluster?

**Comment by danhhz** [comment]
I took a mental bet whether anyone would ask that and I just won! It's in the registration cluster repository: https://github.com/cockroachlabs/registration/issues/76
