### ISSUE TITLE
backup/restore: 16 TB, 100 node finishes smoothly

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#17060]

**Comment by dianasaur323** [comment]
@mjibson @dt I updated this issue to reflect our large cluster definition going into 1.2.

**Comment by nstewart** [comment]
@dt what is the status of this? Is this still an active issue?

**Comment by dt** [comment]
we're not currently running a 100 node Backup/Restore test so this isn't resolved, but it isn't active either as neither matt nor I are working on it right now with our shifted focus to migration tools

**Comment by mwang1026** [comment]
closing. we'll recreate test goals when we do scale testing.
