### ISSUE TITLE
sqlccl: TestLoadCSVPrimaryDuplicate: csv_test.go:179: unexpected error: no files in backup

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#17073]
https://teamcity.cockroachdb.com/viewLog.html?buildId=298340&buildTypeId=Cockroach_UnitTests_Testrace

**Comment by mjibson** [comment]
Initial investigation didn't show anything obvious, and I have no ideas. Will monitor and see if it happens again.

**Comment by mjibson** [comment]
Happened again: https://teamcity.cockroachdb.com/viewLog.html?buildId=334483&buildTypeId=Cockroach_UnitTests

**Comment by tschottdorf** [comment]
also spotted here: https://teamcity.cockroachdb.com/viewLog.html?buildId=339287&buildTypeId=Cockroach_UnitTests

Does it repro locally, @mjibson?

**Comment by mjibson** [comment]
Haven't been able to get it to repro locally, no. Part of me wonders if there's a teamcity or other thing that's deleting these files. Really unsure what's causing this.

**Comment by mjibson** [comment]
Closed in favor of #18423.
