### ISSUE TITLE
windows: cannot use `--background` flag on Windows binary

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/cockroach#17082]
From user research; `cockroach start --background --insecure` doesn't actually background the process on Windows.

@BramGruneir @tamird I cannot repro since I don't have a Windows machine. Is this something we're aware of?

**Comment by BramGruneir** [comment]
This is known.  I thought we addressed it somewhere in the docs.  
Windows works differently than linux and so the background flag just won't work.

**Comment by sploiselle** [comment]
@BramGruneir Is there any way to produce an error message if you use the `--background` flag on Windows?

**Comment by BramGruneir** [comment]
Of course, should be easy to do.

**Comment by sploiselle** [comment]
+1 on that; think it would make for an improvement in UX, which helps adoption!

**Comment by bdarnell** [comment]
The current implementation of the `--background` flag won't work on windows (because we reused some non-portable code implementing a `systemd` integration protocol), but there's no fundamental obstacle to implementing this flag in a windows-friendly way.

**Comment by BramGruneir** [comment]
Windows doesn't have the same concept as fore/back ground tasks that linux does.  We would have to create a process and kick it off or open it in a hidden command window.  

See https://superuser.com/questions/198525/how-can-i-execute-a-windows-command-line-in-background

The correct way around this is make an installer that can install cockroach as a windows service.  And redirect all logs to the correct windows logging system.  That would be a lot of work.

**Comment by knz** [comment]
We're going to slowly deprecate --backround and start to emphasize the use of service / task managers. Closing this as "wontfix".
