### ISSUE TITLE
Adding CRC32 internal function

### ISSUE THREAD

**Issue by leomkkwan** [cockroachdb/cockroach#17081]
CRC32 is a very common function to do simple error detection.

Although PostgreSQL does not come with it, but from a Mysql user to have this function will make their life easier when they try to port their system from Mysql to CRDB.

**Comment by bdarnell** [comment]
CRC32 functions (both IEEE and castagnoli variants) are coming in version 1.1 (and they've been available in our alpha releases [since June 1](https://www.cockroachlabs.com/docs/releases/v1.1-alpha.20170601.html#sql-language-changes))
