### ISSUE TITLE
[Bug?] source name "table" not found in FROM clause

### ISSUE THREAD

**Issue by kocoten1992** [cockroachdb/cockroach#17104]
I have 2 table:
```
// persons
-------------
' id ' name '
-------------

// phones (person_id reference id on persons)
----------------------------
' id ' person_id ' number '
----------------------------
```

When I select as follow, it throw me error:
```sql
SELECT * FROM "persons" WHERE "phones"."person_id" = "persons"."id";
```

That query execute normally on sqlite or mysql, so I think it a bug here.

**Comment by jordanlewis** [comment]
You're trying to reference a column from a table that isn't available in any of the data sources in your `FROM` clause. This is not valid SQL, and doesn't in fact work in sqlite either:

```
sqlite> create table persons (id int, name text);
sqlite> create table phones (id int, person_id int, number text);
sqlite> select * from persons where phones.person_id=persons.id;
Error: no such column: phones.person_id
```

Perhaps you meant to use a join clause?

```
SELECT persons.* FROM persons JOIN phones ON persons.id=phones.person_id;
````

**Comment by kocoten1992** [comment]
My apologies, I think I'm getting XY problem, here is the real sql that work in sqlite and didn't work in cockroachdb yet:

```sql
SELECT * FROM "phones" WHERE EXISTS (SELECT * FROM "persons" WHERE "phones"."person_id" = "persons"."id")
```

**Comment by jordanlewis** [comment]
We don't support correlated subqueries yet, which is why that query doesn't work. That's tracked in #3288.

I think you can get the same behavior in this case with an (inner) join, since your intent seems to be to select only those rows of phones that have a corresponding person in the persons table.

```
SELECT "phones".* FROM "phones" JOIN "persons" ON "persons"."id"="phones"."person_id";
```
