### ISSUE TITLE
reporting: report hostname & port number

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#17101]
Discussed with @dt today:

- we probably want (a hash of) each node's hostname, so as to enable detection/measuring of how often users run multiple nodes on the same machine
- also report the port number, to estimate how often people run on a different port by default

**Comment by knz** [comment]
feel free to reassign

**Comment by dt** [comment]
Are either of these actionable? I'm inclined to not collect them unless we have a concrete thing we'd do with the answers

**Comment by knz** [comment]
yeah since that really hasn't come up in discussions since then I'm inclined to not keep.
