### ISSUE TITLE
reporting: move reporting of some data from update to reporting loop

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#17102]
Discussed with @dt today: some of the node/cluster details are reported as query arguments on the update ping performed by nodes every hour.

Some of this info is "legitimate" for an update ping like platform, version.

Others are more dubious: uuid, nodeid, uptime, insecure.

We should move this data to the reporting loop instead of the update loop.

In the case where we still want uptime information we can either use the node start-up time already being logged, or we could scan the monitoring data to find the earliest monitoring timestamp to estimate cluster age.

**Comment by knz** [comment]
feel free to reassign

**Comment by dt** [comment]
we now send update checks and diagnostics data based on the same setting, so there's no longer really any real reason to include something in one or the other in particular.
