### ISSUE TITLE
sqlccl: make BACKUP/RESTORE aware of source data locality

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#17125]
If a cluster is geographically distributed (us-east, us-west, europe, etc) and a RESTORE is run from data in a single cloud storage location (us-east), then in some cases it will be cheaper & faster to ingest into ranges in us-east and rebalance after.

One idea for how to accomplish this is to allow the user to set the zone config for the tables about to be restored before the restore. Then, RESTORE makes sure to check zone configs when doing it's presplits and scatters.

**Comment by rolandcrosby** [comment]
Locality-aware BACKUP is merged; locality-aware RESTORE is in progress via #39602.
