### ISSUE TITLE
How about the performance of the transaction?

### ISSUE THREAD

**Issue by XisiHuang** [cockroachdb/cockroach#1712]
Our people very care about of the performance of the transaction, have any test  with benchmark such as TPCC?

**Comment by petermattis** [comment]
We've heard rumors some folks have run TPC-C, but I don't know of the details or how it was even possible. We'd certainly like to run it when the SQL support is more fleshed out. Note that very little effort has been put into performance optimization yet. There is tons of low hanging fruit. Any measurements taken now are not going to be reflective of the eventual performance.

**Comment by XisiHuang** [comment]
Communities are developing SQLLayer, but i think it is long time that it be able to support the TPC-C test suite.
In fact, the community version supports TPC-C, will not only help the community to carry out the  performance test, but also help the community to carry out the function and stability test, it is great.

I have an idea: using Mysql or SQLITE, quickly build SQLLayer to form standard test suite base TPC-C.
