### ISSUE TITLE
Will the cockroachdb support NoSql ?

### ISSUE THREAD

**Issue by goodforever** [cockroachdb/cockroach#17129]
Will the cockroachdb support NoSql ?

**Comment by arjunravinarayan** [comment]
If by `NoSQL` you mean treat it like a key-value store, we do not provide API access to the lower layers directly. However, [as indicated in our FAQ](https://www.cockroachlabs.com/docs/stable/frequently-asked-questions.html#can-i-use-cockroachdb-as-a-key-value-store), you can use a very simple SQL schema that translates directly down in a one-to-one mapping to key-value mappings. This allows you to treat CockroachDB as a NoSQL key-value store, but leaves you with the optionality if you change your mind later.
