### ISSUE TITLE
Update sqllogictests

### ISSUE THREAD

**Issue by rampage644** [cockroachdb/cockroach#17134]
Right now empty string values are not rendered as [documentation](https://www.sqlite.org/sqllogictest/doc/trunk/about.wiki) suggests:

> In the results section, integer values are rendered as if by printf("%d"). Floating point values are rendered as if by printf("%.3f"). NULL values are rendered as "NULL". Empty strings are rendered as "(empty)". Within non-empty strings, all control characters and unprintable characters are rendered as "@".

Some problems arise with empty strings. Sometimes empty string is not added to the row (while parsing test file and query result), and sorting sorts "interleaved" rows instead (because it expects 5 columns and get only 4 thus taking 1 element from neighbor row). Simple fix solves that but requires to rewrite logictest files.

I'm ready to submit a PR for that.

**Comment by jordanlewis** [comment]
This has always bothered me - thanks for trying to fix it. Please submit your PR and we discuss further in the comments.

**Comment by rampage644** [comment]
Okat, will do.
