### ISSUE TITLE
sql: `ADD COLUMN IF NOT EXISTS` returned duplicate col error

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#17147]
The diagnostics collector service runs migrations on startup of the form `ADD COLUMN IF NOT EXISTS`, with the expectation that they are no-ops after first run.

yesterday a new version on startup was trying to add a new column and hung beyond the timeout, so a second, with the same migration, started up.

one of them then received the error `duplicate column name: "maxnodeid"`, which seems unexpected with `IF NOT EXISTS`.

cc @vivekmenezes @jordanlewis

**Comment by dt** [comment]
also weird: after the above error, the proc was restarted, ran the migration without issue, and then got errors trying to use that col:

```
pq: column "maxnodeid" does not exist
```

**Comment by vivekmenezes** [comment]
#16367 has fixed the problem with the error ```duplicate column name``` being returned. We used to return no error for ```IF NOT EXISTS``` only if the column had already been completed added (the schema change was complete).

The ```pq: column "maxnodeid" does not exist``` is returned because the column is still in the process of being added. We aught to make this error better.

**Comment by jordanlewis** [comment]
Last updated on 2017, no clear repro.
