### ISSUE TITLE
sql: multi-statement transactions don't properly report schema change errors

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#17144]
Observe:

```
root@localhost:26257/test> CREATE TABLE dupe (a int);
CREATE TABLE
root@localhost:26257/test> INSERT INTO dupe VALUES (1), (1);
INSERT 2
root@localhost:26257/test> CREATE UNIQUE INDEX ON dupe(a);
pq: duplicate key value (a)=(1) violates unique constraint "dupe_a_key"
root@localhost:26257/test> BEGIN TRANSACTION;
Now adding input for a multi-line SQL transaction client-side.
Press Enter two times to send the SQL text collected so far to the server, or Ctrl+C to cancel.
You can also use \show to display the statements entered so far.
                        ->
BEGIN
root@localhost:26257/test  OPEN> CREATE UNIQUE INDEX ON dupe(a);
CREATE INDEX ## <- we expect this to succeed even though it's kinda weird because we don't support transactional DDLs
root@localhost:26257/test  OPEN> commit;
COMMIT ## <- this should return the error that the create unique index produced
```

cc @vivekmenezes @tso

**Comment by vivekmenezes** [comment]
This happens because the COMMIT will see the error, but the result for the CREATE INDEX has already been returned to the user. We could consider returning the error to the COMMIT in these circumstances.

```BEGIN TRANSACTION; CREATE UNIQUE INDEX ON dupe(a); COMMIT``` returns an error because the COMMIT is seen in the same request as the CREATE INDEX

**Comment by tso** [comment]
Is there a reason to avoid attaching the error to the commit? Or to any other result?

I'm moderately invested in changing the behavior since it would make streaming results much simpler to implement.

The change seems simple enough unless there's hidden complexity that I'm not seeing.

**Comment by vivekmenezes** [comment]
@tso I think we can change these semantics to return an error after a statement or after a commit if the statement is a DDL

**Comment by mjibson** [comment]
This has apparently been fixed sometime during the executor refactor.
