### ISSUE TITLE
possible bug unused variable in /pkg/cli/start.go

### ISSUE THREAD

**Issue by zcspencer** [cockroachdb/cockroach#17143]
Just browsing the code and noticed on [/pkg/cli/start.go#L626]( https://github.com/cockroachdb/cockroach/blob/master/pkg/cli/start.go#L626) `func addrWithDefaultHost` has an `addr` variable that is not being used anywhere in the function, but it looks like [/pkg/cli/start.go#L649](https://github.com/cockroachdb/cockroach/blob/master/pkg/cli/start.go#L649) is expecting that variable to be the `serverCfg.AdvertiseAddr`. I am not confident enough with the domain to try to fix it , so I am just leaving this here as an FYI.

**Comment by a-robinson** [comment]
Thanks for pointing this out! It's definitely wrong, and may be what's behind https://github.com/cockroachdb/cockroach/issues/10374.

**Comment by a-robinson** [comment]
After a bit more investigation, it turns out that this wasn't actually breaking anything, but it was certainly bad code. I've included a fix for it in https://github.com/cockroachdb/cockroach/pull/17145. Thanks again, @zcspencer!

**Comment by petermattis** [comment]
@a-robinson This is fixed, right?

**Comment by a-robinson** [comment]
No, because I bundled it up with a more controversial change. I'll pull it out into its own PR.
