### ISSUE TITLE
release: v1.0.4

### ISSUE THREAD

**Issue by m-schneider** [cockroachdb/cockroach#17148]
Candidate SHA: 5b757262d33d814bda1deb2af20161a1f7749df3
Deployment status: adriatic, blue, cerulean, omega

[Release process checklist](https://github.com/cockroachdb/cockroach/wiki/Release-Process)

Prep date: 2017-07-20
- [x] [Pick a sha](https://github.com/cockroachdb/cockroach/wiki/Release-Process#pick-sha), fill in `Candidate SHA` above.
- [x] Deploy to test clusters, fill in `Deployment status` above
- Keep an eye on clusters until release date.

Release date:  2017-07-27
- [x] [Check cluster status](https://github.com/cockroachdb/cockroach/wiki/Release-Process#check-cluster)
- [x] [Tag release](https://github.com/cockroachdb/cockroach/wiki/Release-Process#tag-release)
- [x] [Trigger release build](https://github.com/cockroachdb/cockroach/wiki/Release-Process#trigger-build)
- [x] [Check binaries](https://github.com/cockroachdb/cockroach/wiki/Release-Process#check-binaries)

- For stable releases only:
  - [x] Update the [Homebrew Formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/cockroach.rb)
  - [x] Update the image tag in our [Kubernetes configurations](https://github.com/cockroachdb/cockroach/wiki/Release-Process#kubernetes-configurations)
  - [x] Update the version label in our [Red Hat Atomic Docker image](https://github.com/cockroachdb/cockroach/blob/master/build/deploy/rhel/Dockerfile). For major/minor releases, also update the documentation link in the [image's help file](https://github.com/cockroachdb/cockroach/blob/master/build/deploy/rhel/help.1)
  - [x] Announce version to the [registration cluster](https://github.com/cockroachlabs/production#publishing-a-new-release-version)

- [x] Update docs
- [x] External communications for release
- [x] File issue for next release and assign to release coordinator

**Comment by mberhault** [comment]
We seem to be missing the last step: `file issue for next release`. That would be 1.1-alpha-20170803 (unless we're moving to beta, but probably not)
