### ISSUE TITLE
sql: prepared statements should cache a query plan

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#17158]
Similar to #13618 and based on data from #14927, prepared statements should cache a query plan. Analysis of simple queries indicate that query planning consumes ~25% of the service time. Additionally, query planning is a large contributor to allocations (38%) and allocated bytes (30%).  By caching the query plan, we can directly eliminate the time for query planning and significantly reduce GC pressure. For simple queries, the expected performance gain is 20-25%.

**Comment by jordanlewis** [comment]
I'm loosely planning to work on this next development cycle.

**Comment by vivekmenezes** [comment]
while doing this the table descriptor leases used to create the plan should be checked for expiration. The plan needs to expire if the lease expires and a renewed lease bringing up a descriptor with a different version.

**Comment by knz** [comment]
xref #17480

**Comment by jordanlewis** [comment]
We're not going to do this pre-optimizer anymore. I'll assign this to @andy-kimball for triage or close, since presumably this kind of thing is already in the optimizer roadmap.

**Comment by andy-kimball** [comment]
I ended up doing this in September. There's more we can and will do in the 2.2 timeframe, but since prepared statements now cache a query plan, I'm closing this as fixed. We'll track additional 2.2 work in other ways.
