### ISSUE TITLE
run build-docker-dev.sh in ubuntu, but it always connect to debian

### ISSUE THREAD

**Issue by YuleiXiao** [cockroachdb/cockroach#1716]
I run build-docker-dev.sh in ubuntu 14.04 in office. I found it connect to debian sourcelist but not ubuntu. But at home, it is ok. What make it decide which one to connect?

./build-docker-dev.sh 
Building Docker Cockroach images...
Sending build context to Docker daemon 20.48 kB
Sending build context to Docker daemon 
Step 0 : FROM golang:1.4.2
 ---> 124e2127157f
Step 1 : MAINTAINER Tobias Schottdorf <tobias.schottdorf@gmail.com>
 ---> Using cache
 ---> f63a69d6f272
Step 2 : RUN apt-get update -y && 	apt-get dist-upgrade -y && 	apt-get install --no-install-recommends --auto-remove -y git build-essential pkg-config file npm &&  	apt-get clean autoclean &&   apt-get autoremove -y &&  	rm -rf /tmp/* && 	ln -s /usr/bin/nodejs /usr/bin/node
 ---> Running in 7e19238782ad
Err http://httpredir.debian.org jessie InRelease
  
Err http://httpredir.debian.org jessie-updates InRelease
  
Err http://httpredir.debian.org jessie Release.gpg
  Could not resolve 'httpredir.debian.org'
Err http://httpredir.debian.org jessie-updates Release.gpg
  Could not resolve 'httpredir.debian.org'
Err http://security.debian.org jessie/updates InRelease
  
Err http://security.debian.org jessie/updates Release.gpg
  Could not resolve 'security.debian.org'
Reading package lists...
W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie/InRelease  

W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie-updates/InRelease  

W: Failed to fetch http://security.debian.org/dists/jessie/updates/InRelease  

W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie/Release.gpg  Could not resolve 'httpredir.debian.org'

W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie-updates/Release.gpg  Could not resolve 'httpredir.debian.org'

W: Failed to fetch http://security.debian.org/dists/jessie/updates/Release.gpg  Could not resolve 'security.debian.org'

W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
Package file is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package pkg-config is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Unable to locate package build-essential
E: Package 'pkg-config' has no installation candidate
E: Package 'file' has no installation candidate
E: Unable to locate package npm

**Comment by tschottdorf** [comment]
Hi @YuleiXiao,

the error `Could not resolve 'httpredir.debian.org'` indicates that you've got a DNS problem at one of the locations.

**Comment by YuleiXiao** [comment]
Hi @tschottdorf ,
I know the reason, the proxy problem. I close it.

**Comment by wintersylf** [comment]
I'm having the same issue.  what proxy problem could I be having?  I can ping httpredir.debian.org from the host (the environment from which I run docker) but in building an image I get the same errors.  I'm running this on brand new installation of Ubuntu 14.04 LTS

**Comment by tamird** [comment]
So you can ping `httpredir.debian.org` but are getting `Could not resolve 'httpredir.debian.org'` errors?

**Comment by wintersylf** [comment]
yes, I can ping that host but apparently whilst doing a docker build the host name is not available...  I've pasted the output here: http://pastebin.com/1dAjy9vb

**Comment by tamird** [comment]
Can you ping that host from inside a docker container?

**Comment by wintersylf** [comment]
`docker run -it ubuntu bash` and I can't ping it.  a look at `/etc/resolv.conf` indicates that the only name server is that of my VPN

**Comment by tamird** [comment]
You've reached the end of my docker knowledge. Perhaps it's time to talk to
the docker folks.

**Comment by wintersylf** [comment]
thanks  tamird.  I guess I'll hope someone else responds

**Comment by wintersylf** [comment]
solved.  [norasky](https://norasky.wordpress.com/2015/06/09/docker-build-could-not-resolve/) figured out that in /etc/default/docker the DOCKER_OPTS line could be commented out.  after that, just restart the docker daemon `sudo restart docker` and done.  worked for me!

**Comment by tschottdorf** [comment]
Thanks @wintersylf!

**Comment by wintersylf** [comment]
it's always good to leave a trail of crumbs.  I spent a lot of time googling.  maybe someone else will come across this.  thanks for supporting this.

**Comment by tburnett80** [comment]
Must be something with google dns, I commented out the /etc/default/docker the DOCKER_OPTS line and restarted and boom it works.
