### ISSUE TITLE
sign CLA always fail

### ISSUE THREAD

**Issue by YuleiXiao** [cockroachdb/cockroach#1717]
When I sign CLA on cockroach contributing, it always fail. Error message is "We're sorry, but something went wrong."

**Comment by bdarnell** [comment]
Yeah, CLAHub is having issues and may be going away (clahub/clahub#111). We're considering alternatives.

**Comment by tschottdorf** [comment]
I wonder if it's possible to legally "sign" a CLA by adding relevant information to a file in our repo (`CLASIGNERS.md`). Would be nice not to rely on anything that can break.

**Comment by bdarnell** [comment]
I think something like that could work, but the real value of CLAHub was the bot that watched all our pull requests and checked whether the author had signed.

**Comment by tschottdorf** [comment]
ok. Possibly could have a group that we add all users to after they sign the CLA for the first time. But yes, if CLAHub just came back up...

**Comment by bdarnell** [comment]
Yeah. I'm hoping someone will just take it over and make it work again; if not there's another similar service at https://cla-assistant.io/

**Comment by petermattis** [comment]
I thought the clahub code was open source. Can we run the service ourselves?

**Comment by bdarnell** [comment]
We could; are you volunteering? (it's a rails app) It wouldn't be any easier to migrate to self-hosted clahub than another service like cla-assistant (also open source, node.js this time). 

Unlike CI services that have clear upsell opportunities for capacity and privacy, it's unclear how a CLA service could ever be more than a hobby, so I'm not sure how to find one that won't fold out from under us. Self-hosting is one way around that but it sounds like a pain.

It's also worth noting that the node.js project has stopped using a CLA (https://www.joyent.com/blog/broadening-node-js-contributions), on the theory that submitting a PR to a repository with a clearly-stated license constitutes an intention to put the contributed code under that license (this was a year ago now; I don't know if anyone has followed in their footsteps but in my experience CLAs have only been getting more common over the last few years). We could see how comfortable the lawyers are with that idea.

**Comment by petermattis** [comment]
No, I'm not volunteering. And I don't know rails. Perhaps @tamird wants to volunteer?

**Comment by tamird** [comment]
I like the idea of following joyent's lead. If we decide to go the route of running clahub ourselves I could do it. I can't imagine it'll be much work.

**Comment by spencerkimball** [comment]
I'll ping the lawyers on CLAs and point them at node.js.

**Comment by tamird** [comment]
@bdarnell has moved us to cla-assistant, so this should be good to close.
