### ISSUE TITLE
perf: packets per/op regression from 1.0.3 to 1.1

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#17177]
Noticed while examining 1.0.3 vs 1.1 performance:

<img width="1403" alt="screen shot 2017-07-23 at 4 36 50 pm" src="https://user-images.githubusercontent.com/6201335/28502672-3cb9c5d0-6fc5-11e7-9064-03a7094d9b25.png">

The segment on the left is 1.1 and the right is 1.0.3. This is aggregate packets received/transmitted on the cluster. The workload is `kv --read-percent 95 --max-rate 10000 --splits 200 --concurrency 100`. That's a 45% increase in packets for the same workload.

Initial guess is that this is due to a change in gRPC.

**Comment by petermattis** [comment]
Bisection points to 791944c04ccff341ec1387d59cfcae5af9f1eab4. I suspect the interceptor is adding something to the requests/responses which is causing different behavior in gRPC.

Cc @RaduBerinde

**Comment by petermattis** [comment]
There may be two problems. 791944c04ccff341ec1387d59cfcae5af9f1eab4 caused an increase from 96k packets/sec to 120k packets/sec. But master is showing 136k packets/sec.

**Comment by petermattis** [comment]
Disabling the opentracing client and server interceptors in `rpc/context.go` brings master back down to 108k packets/sec.

**Comment by petermattis** [comment]
@RaduBerinde Can we use https://github.com/grpc-ecosystem/grpc-opentracing/blob/master/go/otgrpc/options.go#L32 to not add a span if tracing is disabled?

**Comment by petermattis** [comment]
Further bisection is pointing at a2b80c18fe8a3b8198acb5049a0631ea5df575a8 as causing the packets/sec to grow from 120k to 136k. Not at all clear why. I'll look closer tomorrow.

**Comment by a-robinson** [comment]
> Further bisection is pointing at a2b80c1 as causing the packets/sec to grow from 120k to 136k. Not at all clear why. I'll look closer tomorrow.

That might be a red herring given that we reverted it in #16772, though.

**Comment by petermattis** [comment]
> That might be a red herring given that we reverted it in #16772, though.

Strangely, 40b86c1e1573636c725c072ac1d47ccad2da186b does not bring the packets/sec back down to 120k.

**Comment by RaduBerinde** [comment]
Wow, this is surprising. When tracing is disabled, `Inject` doesn't do anything. But the interceptor still creates a `NewOutgoingContext` which may be causing the difference. `IncludingSpans` would indeed circumvent that. I can come up with a patch, if I send it to you can you retest to confirm if fixes the regression?

**Comment by RaduBerinde** [comment]
@petermattis I posted a diff in #17185

**Comment by petermattis** [comment]
@RaduBerinde Roger, I'll take a look when I get to the office.

**Comment by petermattis** [comment]
Something is either off with the packets/sec metric or I'm miscounting the number of packets we should expect for a read operation. As I count it, a simple read operation should generate 1 received packet at the pgwire level and 1 transmitted packet for the pgwire response. If the request is for a remote range, there will be 1 transmitted packet to the remote node and 3 received packets (3 due to gRPC badness) for the response. On a 6-node cluster and evenly balanced load and ranges we'd expect 5/6 of the requests to touch a remote range. At 10k ops/sec, this translates into 53k packets/sec total, but I'm seeing nearly double that.

**Comment by petermattis** [comment]
Verified the metric by looking at `/sys/class/net/eth0/statistics/tx_packets`. On a single node cluster performing only reads, the Tx and Rx packets/sec almost exactly matches the ops/sec.

**Comment by petermattis** [comment]
Perhaps related to the remaining 1.0.3 vs 1.1 discrepancy: 1.1 sees a steady stream of not-leaseholder errors when there shouldn't be any while 1.0.3 does not. Tracking this down now.

**Comment by petermattis** [comment]
The proximate cause of the problem is that `rpc.Context.ConnHealthy(<local server>)` is always returning false. Something in 1.1 change that is causing that. There is an easy hack to always make the local server connection appear hacky, though I'd like to find out the root cause of why these connections are not healthy.

**Comment by RaduBerinde** [comment]
Distsql planning also depends on `ConnHealthy`.

**Comment by petermattis** [comment]
@RaduBerinde Roger. I have a PR coming that will fix this. Looks like it was broken by https://github.com/cockroachdb/cockroach/pull/16612.

Cc @tamird

**Comment by a-robinson** [comment]
> The proximate cause of the problem is that rpc.Context.ConnHealthy(<local server>) is always returning false.

Are you saying that the `ConnHealthy` problem was causing the `NotLeaseholder` errors?

**Comment by petermattis** [comment]
Yes. `kv/transport.go` always sends RPCs to unhealthy connections after healthy connections.

**Comment by tschottdorf** [comment]
Wow, yikes. Good find, Pete.

**Comment by petermattis** [comment]
Between #17196 and #17185, this is now fixed.
