### ISSUE TITLE
sql: homogeneize / abstract access to db / table descriptors

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#17188]
So while polishing #15388 I realize I do not really have an answer to "how do I get a db descriptor by ID" (other than, I know already, constructing the descriptor key and talking to KV manually)

Actually this pulled up some more questions:
- how can I access "old" versions of database descriptors? (Is that at all possible?)
- how do I get a table desc by ID?
- how do I get a *cached* table desc by ID?
- when exactly should I care whether I should request a cached version of a desc or not?

In general **I am missing an internal descriptor access API**. Currently all the code to access descriptors is ad-hoc, not documented in a central place and the schema lease API is not optimized for fast access to descriptors by ID.

What is needed here is:

- an interface `schemaResolver` or something, with a stable API documented in a single place
  - make that API able to resolve descriptors either by name or by ID
  - make that API take a boolean flag "historical query" or something usage-oriented which take ownership of answering the question of whether to use a cached descriptor or not
  - make that API stateful with a "local state" object and make it able to *cache lookups within the context of a single caller even when not using the lease manager* (so that multiple lookups of the same table by the same caller in a row doesn't hit KV too much)
- have `*planner` (or whatever)  implement that API
  - ensure data structures ensure equally fast by-name and by-ID resolution

**Comment by vivekmenezes** [comment]
while I agree that there is room for improvement here, a lot of work has been done on table descriptors to bring them more inline with how we want them to be used. See the RFC:
https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/table_descriptor_lease.md

for discussions on table descriptor versions and how they should be used.

More work needs to be done to improve the API in the code and I expect to do some of that work for 1.2.

Unfortunately this still doesn't cover database descriptors and we have work to do here too. it has just not been a priority.

**Comment by knz** [comment]
This may be fixed by #22275

**Comment by vivekmenezes** [comment]
closing in favor of #22275
