### ISSUE TITLE
sql: speedup restart of job coordinator

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#17187]
first reported by a user when trying a DROP TABLE and complaining about the command stalling. The particular problem with a slow DROP TABLE has been fixed by #17016, but there still exists a short window when a job is running and the coordinator node fails resulting in a new coordinator restarting in like 6 minutes (schema change lease interval). 

We could fix this by reducing the schema change lease interval window

**Comment by lucy-zhang** [comment]
No longer applicable now that schema changes are run as jobs (I think the original issue was referring to the async schema change manager not picking up these "jobs").
