### ISSUE TITLE
stability: investigate recovery from permanent unavailability

### ISSUE THREAD

**Issue by hxiaodon** [cockroachdb/cockroach#17186]
Hi,
I proposed this issue in gitter at last weekend. It should be helpful if the disaster recovery tool is provided:)

Hi,All. I started a local cockroachdb cluster with 3 instances(node1,node2,node3), node2 and node3 join node1, all works fine even one node is crashed. When I crash node1 and node2(clean data folder and restart), node3 could not provide service(It's expected), but I could not dump data from node3.Suppose we have this scenario, if 2 nodes are just permanently dead and the daily backup operation was triggered long time ago while the rest healthy node keep the latest data(until service unavailable) compared with the backup one, at this time, I could not use the healthy node's data(dump/backup) with adding other 2 new nodes to provide the service. Does it make sense? Thanks!
What I mean is that cluster do not provide service when minority nodes left make sense, but it does not make sense to block dumping data(raft committed one) when minority nodes keep the complete copy(replication number equal to cluster nodes number)

Andrei Matei's reply
@hxiaodon indeed, we want to provide some type of data recovery tools for this situation, but we haven’t gotten to it yet

Jira issue: CRDB-6362

**Comment by dianasaur323** [comment]
@hxiaodon Thanks for bringing this up. There is nothing coming up in our 1.1 yet, but we are currently scoping out what a solution for this scenario might look like. The scenario you are hitting is that if you lose 2 out of 3 replicas, you'll have to restore from a backup. 

Quick question for you, in this use case, would you rather force the single remaining replica to up-replicate, or would you prefer some form of incremental recovery that brings you closer to the most updated version of your database?

**Comment by hxiaodon** [comment]
@dianasaur323 
I'd like to choose the former one, although its implementation would be complex; The latter way need me to restore the backup and apply the incremental change manually to new created cluster, but it should be easier for you to provide quickly:)

**Comment by petermattis** [comment]
One challenge with recovering data from a below-quorum range is that we can't know that we have the most recent data. This is inescapable. But it is feasible to build a tool which does a best-effort reconstruction of data. What I'm imagining would be offline and might utilize some of the mapreduce-like infrastructure being used for bulk ingest and we'd want to pair that with some SQL fsck tool which would recover a consistent state given schema constraints. Seems large in scope, but doable.

**Comment by hxiaodon** [comment]
@petermattis

**Comment by dianasaur323** [comment]
@hxiaodon this won't make it into the upcoming minor release, although we will be working on something that may enable the second solution I discussed. If we have extra time in the next minor release, we may get to an RFC to explore this further.

**Comment by tschottdorf** [comment]
Copying over from #19645:

Suppose you run a cluster and one of more permanent node outages occur, leaving at least some ranges permanently in minority. Currently, there is no way to recover from this situation and we must come up with one. Generally, since data may have been lost, it may not be possible to completely recover. However, in many situations it would at least be possible to recover most of the state, save a few lost writes (due to having to take data from a follower that isn't up to date).

There are a few model cases:

1. three node cluster, two nodes catch fire and melt. Should be able to lose only some writes, but this could still mean partial transactions and violation of SQL integrity constraints.
1. five node cluster, three nodes disappear. Might lose a few whole ranges, but in principle most of the data may be recoverable. Big chunks of data might be missing.

@lego, would be interested in which types of corruption #19327 would be able to catch. Running these integrity checks would definitely be one of the steps carried out in this setting, and it would be nice to have that leave as little remaining room for error as possible.

One aspect that was pointed out is that it would be nice if AS OF SYSTEM TIME could be used in the recovery to roll back to a consistent view of the data. Perhaps there is a connection with follower reads: if the lease holder dies in the unavailability event, the follower would still be able to serve "old enough" queries.

We've also previously talked about using AS OF SYSTEM TIME to create backups, which ties into this issue as long as AS OF SYSTEM TIME can be routed appropriately in the unavailable cluster.

@petermattis wrote:

>
Agreed that any recovery would likely need to work in concert with SQL SCRUB in order to ensure consistent table state.
>
Using AS OF SYSTEM TIME to generate a backup and then restoring from the backup would be a nice general approach.

**Comment by lego** [comment]
> @lego, would be interested in which types of corruption #19327 would be able to catch. Running these integrity checks would definitely be one of the steps carried out in this setting, and it would be nice to have that leave as little remaining room for error as possible.

Yea definitely. #19327 is only checking the index integrity, but it will also be able to check other SQL integrity problems soon.

Maybe we can use SCRUB to find violations and their corresponding write timestamps, then take use a timestamp just before those for AS OF SYSTEM TIME. Alternatively, this is where some kind of repair mechanism is helpful. It would be easy tack on some logic to read the SCRUB errors and handle those in the disaster recovery to produce a consistent table.

Aside: we already have the mechanisms for making sure ranges are found, yea? Are there other things that might go awry, like the integrity of table descriptors in relation to other descriptors?

**Comment by dianasaur323** [comment]
i think @bdarnell had some strong opinions on this topic, so mentioning him here

**Comment by bdarnell** [comment]
My feeling is that until we have a very comprehensive SCRUB (covering secondary indexes, foreign keys, etc), it's best to try and determine a known-good timestamp (ideally making use of the max-safe-timestamp mechanism once we have that), make a backup at that time, then restore that backup. (once we have CDC, using that to maintain a streaming backup would be even better)

This leaves dead ranges around in the keyspace that are unreferenced. A nice way to resolve this would be to implement merging of empty ranges, and then treat the dead ranges as "empty" and stitch the keyspace closed over them.

If the data loss affects meta or system ranges, is there any way to recover, or are we still going to have catastrophic data loss scenarios even if we implement this?

**Comment by a-robinson** [comment]
> Maybe we can use SCRUB to find violations and their corresponding write timestamps, then take use a timestamp just before those for AS OF SYSTEM TIME.

This also provides motivation for wanting to be able to run `SCRUB` as of a system time, since you'd also want to verify that the time you're restoring to didn't have issues of its own.

**Comment by dianasaur323** [comment]
Do we have a sense on if the timeline for this has been moved up? I currently have it saved in our backlog with no prioritization, but sounds like more and more people have been asking for something here.

**Comment by tschottdorf** [comment]
I was thinking of the following half-baked workflow to nurse a cluster back to life in the case in which ranges are unavailable (say two out of five nodes die in a 3x-replicated cluster, so a bunch of ranges are toast, including perhaps some system ranges):

- restart all nodes in the cluster in "recovery mode". I think this could just be [initializing mode](https://github.com/cockroachdb/cockroach/blob/d67df9993074428f3f78af5053462fca01791133/pkg/server/servemode.go#L29) but it may be worth disabling other moving parts (for example, we certainly don't want to be GC'ing replicas now).
- user runs `./cockroach recover <list>`, where `<list>` is a list of node IDs (or do we need *addresses* if gossip is unable to connect?)
- the command contacts the nodes, asking them for their on-disk replicas
- for each discovered range that lacks quorum according to `<list>`, compute a new range descriptor with enough dead nodes subtracted to re-establish quorum.
- overwrite all copies of the old range descriptor with that one (includes meta range entries), adjusting the MVCC stats in the process. (This would have to be able to bypass Raft, so perhaps something like the [KVDebug service](https://github.com/cockroachdb/cockroach/pull/18661). I think the copies are one on each replica, one in meta2 and (only for meta2 ranges) one in meta1.
- note that this process is restartable, i.e. a crash half-way through doesn't prevent the next attempt from making progress.
- additionally, should sanity-check (the highest-commit-indexed replica of each range within the) the meta ranges (to make sure we're not missing a range completely, in which case our keyspace has gaps: we could stitch this up too by lengthening the previous range, but I think that's not in initial scope).
- restarting the cluster, all replica sets should now be live, and upreplication should happen.
- `SCRUB` the data (to see whether the status quo is safe to use) or roll back to a safe `AS OF SYSTEM TIME` or backup.

I wonder what other ideas people had for this. It certainly seems attractive to get back to a running cluster without having to shuffle lots of data around. The complexity of the approach seems manageable. We could use RocksDB checkpoints before attempting the repair which is a space-saving way that keeps the original data intact and allows a botched repair to be rolled back.

**Comment by bdarnell** [comment]
That is more or less what I had in mind for an "in place lossy recovery". I still wouldn't prioritize working on this until after we have "read from follower in the past without quorum" (which would enable an after-the-fact backup/restore-based recovery), though. There's a lot of tricky logic here that will be rarely exercised, and I'd rather work on things that bring us closer to other things we need than a lot of special cases for this kind of recovery.

> restart all nodes in the cluster in "recovery mode". I think this could just be initializing mode but it may be worth disabling other moving parts (for example, we certainly don't want to be GC'ing replicas now).

Maybe it's better if this is an offline process: stop all the nodes and run a `cockroach recover` command on each one with a list of node ids that will be purged from all range descriptors. 

> overwrite all copies of the old range descriptor with that one

At what timestamp? Is this rewriting history or inserting a new value? What about the uncommitted tail of the raft log? 

> note that this process is restartable, i.e. a crash half-way through doesn't prevent the next attempt from making progress.

It's restartable, but it's not reversible. Once you start this process, you're committed (so you can't abort this recovery process if you manage to revive the "dead" nodes). 

> SCRUB the data (to see whether the status quo is safe to use) or roll back to a safe AS OF SYSTEM TIME or backup.

If SCRUB finds errors it can't fix, then you're back to the "rewrite all data" option (or perhaps a more limited version, like dropping and recreating an index). So the viability of this option will depend on how likely this kind of inconsistency will be. I'm worried that errors will be common, and it'll be a while before SCRUB is able to fix a lot of them.

**Comment by spencerkimball** [comment]
With #21056 we can introduce a more sophisticated mechanism for
**consistent**, lossy recovery. Nodes could periodically persist the
information from Raft heartbeats used to determine max safe timestamp for
all ranges.

On recovery, we could find the minimum max safe timestamp across all
surviving nodes’ ranges (if quorum, wall time; otherwise use maximum of
surviving replica max safe timestamps). We could then send commands to
revert newer writes across the entire system – absent the revert mechanism
I proposed a while back, we could do this using a time bounded iteration,
similar to what’s done for intent range resolution in #21078.

**Comment by tim-o** [comment]
Just noting that this recently came up again - we receive requests to provide a tool to recover from a single replica at least once per quarter. It hasn't been a blocker yet but users seem to be confused by the fact that the option isn't available.

**Comment by tim-o** [comment]
Zendesk ticket #[2298](https://cockroachdb.zendesk.com/agent/tickets/2298) has been linked to this issue.

**Comment by tbg** [comment]
Related: https://github.com/cockroachdb/cockroach/issues/41411

**Comment by isoos** [comment]
Is there any update on this one? I have a 600+ GB single-node replicate from a failed 3-node cluster that I'd rather recover somehow...

**Comment by mwang1026** [comment]
Nothing likely on the timeline you need, unfortunately. We're exploring the technical options we have here and once we have a good sense of which path we'll take we'll figuring out when to schedule the work.

**Comment by erikgrinaker** [comment]
Tooling for best-effort loss of quorum recovery (i.e. without guarantees of data consistency, so could end up with e.g. dangling foreign key references or missing index entries or other problems), was released in 22.1 via the subcommand `cockroach debug recover`. See the [RFC](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20211103_loss_of_quorum_recovery.md) for details. 23.1 will improve this tooling to recover ranges while the cluster is still online (see [RFC](https://github.com/cockroachdb/cockroach/blob/611ce71548acb5df472fc60475a085cdd7fe08a3/docs/RFCS/20221101_half_online_loss_of_quorum_recovery.md)).
