### ISSUE TITLE
docs: “bad connection” warning when using cockroach console over Haproxy

### ISSUE THREAD

**Issue by yaojingguo** [cockroachdb/cockroach#17184]
`yao-0` is Haproxy over 7 cockroach nodes. If I wait for about 1 minute to input another command to cockroach console, the following warning shows up:

```
driver: bad connection
connection lost; opening new connection and resetting session parameters...
```

Here is the detailed scenario:
```
[cloud-user@yao-0 ~]$ cockroach sql --insecure --host=yao-0
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.
root@yao-0:26257/> show databases;
+--------------------+
|      Database      |
+--------------------+
| crdb_internal      |
| information_schema |
| insecurenodetest   |
| pg_catalog         |
| system             |
+--------------------+
(5 rows)
root@yao-0:26257/> SHOW DATABASES;
driver: bad connection
connection lost; opening new connection and resetting session parameters...
root@yao-0:26257/>
```
But running cockroach console over cockroach nodes does not have this problem. And it seems that this problem is related to #15970. 

cockroach version:

```
Build Tag:    v1.0.3
Build Time:   2017/07/06 17:46:06
Distribution: CCL
Platform:     linux amd64
Go Version:   go1.8.3
C Compiler:   gcc 6.3.0
Build SHA-1:  b692a7cc7acc57022d1441034b93b85d860b7e86
Build Type:   release
````

**Comment by jordanlewis** [comment]
@yaojingguo, generally when we see that message after a command is entered it indicates that the node you're connected to has crashed. The issue you linked to is an example of that. However, the message merely indicates that the connection was closed for some reason.

In this case, though, you've got a `haproxy` in between your client and your server. I suspect that the proxy is doing something funny to the connection (like closing and reopening it) after a timeout. I don't think this is actively harmful.

**Comment by a-robinson** [comment]
Without looking into things at all, this smells like we may want to add a TCP keep-alive to the haproxy config. Calling @mberhault

**Comment by yaojingguo** [comment]
My haproxy.conf which is generated by `cockroach gen haproxy`:

```
global
  maxconn 4096

defaults
    mode                tcp
    timeout connect     10s
    timeout client      1m
    timeout server      1m

listen psql
    bind :26257
    mode tcp
    balance roundrobin
    server cockroach1 yao-1:26257 check
    server cockroach2 yao-2:26257 check
    server cockroach3 yao-3:26257 check
    server cockroach4 yao-4:26257 check
    server cockroach5 yao-5:26257 check
    server cockroach6 yao-6:26257 check
    server cockroach7 yao-7:26257 check
```

And even with only one cockroach node behind haproxy, I have the same problem. Here is the `haproxy.conf` for one cockroach node:

```
global
  maxconn 4096

defaults
    mode                tcp
    timeout connect     10s
    timeout client      1m
    timeout server      1m

listen psql
    bind :26257
    mode tcp
    balance roundrobin
    server cockroach1 yao-1:26257 check
```

**Comment by a-robinson** [comment]
Yeah, it looks like the `timeout client` setting of `1m` is likely terminating these connections. Would you mind trying increasing that value?

I'm not quite sure why we put it there in the first place, though, so I'll probably wait for @mberhault to chime in when he's back before changing the value that we generate.

**Comment by yaojingguo** [comment]
After setting `timeout client` to `100s`, I still have the problem. Here is the `haproxy.cfg`:

```
global
  maxconn 4096

defaults
    mode                tcp
    timeout connect     10s
    timeout client      100s
    timeout server      1m

listen psql
    bind :26257
    mode tcp
    balance roundrobin
    server cockroach1 yao-1:26257 check
```

**Comment by a-robinson** [comment]
Ok, thanks for checking! Given that, we'll probably want to explicitly enable TCP keepalive from haproxy to the client (we don't need it to the server since the server already sends keepalives). It looks like that means we'll want to enable the [`clitcpka` setting](https://cbonte.github.io/haproxy-dconv/1.7/configuration.html#4.2-option%20clitcpka).

**Comment by mberhault** [comment]
I can enable tcp keep-alives. There doesn't seem to be a way to set the keep-alive interval1, just enable it and even that is system-dependent.

I'm kind of surprised this is being hit. The most likely culprit is the client timeout. If the client remains idle for a minute, haproxy will close the connection, requiring a new connection to be opened. This is gracefully handled by both client and server, and the `connection lost; opening new connection and resetting session parameters...` message is fairly benign.

We could tweak the timeout settings, but there's no way we're going to find something that works for everyone. Instead, the goal of the options there was to show some of the important things to configure. The generated file is not supposed to be the ultimate haproxy config, just a sample.

**Comment by mberhault** [comment]
Oh, and if you leave any of the timeout lines out, you get:
```
[WARNING] 211/093031 (21248) : config : missing timeouts for proxy 'psql'.
   | While not properly invalid, you will certainly encounter various problems
   | with such a configuration. To fix this, please ensure that all following
   | timeouts are set to a non-zero value: 'client', 'connect', 'server'.
```

**Comment by yaojingguo** [comment]
Adding `clitcpka` does not solve this problem. This problem is caused by the following haproxy configuration options:

```
    timeout client      1m
    timeout server     1m
```

If I set `2m` to both options, the warning shows up after about 2 minutes. 

And I have verified that both options have an impact on the timing of the warning.

**Comment by mberhault** [comment]
The TCP keep-alive timeouts are pretty large by default (though it's system dependent). Eg: on linux, the first keep-alive will be sent after 2 hours:
```
$ cat /proc/sys/net/ipv4/tcp_keepalive_time
7200
```

If your client does not send queries very often, you'll want to increase the timeouts. Or, you could just ignore the warning as it just means it re-created a connection.

**Comment by yaojingguo** [comment]
In https://www.cockroachlabs.com/docs/stable/manual-deployment.html, the generated haproxy file  is used to running `cockraoch sql` over the haproxy. So it is highly possible that a CocckraochDB user will see this warning since the timeout values are only 1 minute. 

By contrast, MySQL has an `interactive_timeout` option which is 8 hours by default. So MySQL client can stay idle for any duration less than 8 hours and be reused again without seeing any warning. It seems that PostgreSQL does not have such an option.  But I have done some test on PostgreSQL client `psql`.  I let `psql` stay idle for about one hour and can use it again without seeing any warning.

So I think that it is better to increase the timeout value to give a user experience similar to MySQL and PostgreSQL.

**Comment by dianasaur323** [comment]
I'm going to reopen this issue so that it doesn't fall through the cracks while @mberhault decides on the best approach to address this.

**Comment by mberhault** [comment]
`psql` talking to cockroachdb behaves the same way.
With the default haproxy config with 1m timeout, I get the following (waiting a bit more than 1m after the first query):
```
root=> show databases;
      Database      
--------------------
 crdb_internal
 information_schema
 pg_catalog
 system
(4 rows)

root=> show databases;
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Succeeded.
root=> show databases;
      Database      
--------------------
 crdb_internal
 information_schema
 pg_catalog
 system
(4 rows)

```

As I've mentioned before: I'm fine with increasing the timeout. However, there will never be a good value that works for everyone. Even if we put it at 8 hours, you may end up with client doing incredibly rare queries. But as long as the client driver handles setting up new connections properly, it should not be an issue.

**Comment by yaojingguo** [comment]
I agree that there will never be a good timeout value that works for everyone. 

My suggestion is to have some way to generate a haproxy file for the use case of `cockroach sql`. Or it should be mentioned that the timeout value should be adjusted for `cockroach sql` in the following two documents. Otherwise, the unexpected warning might give the user a bad impression about CockroachDB.

- https://www.cockroachlabs.com/docs/stable/manual-deployment-insecure.html
- https://www.cockroachlabs.com/docs/stable/manual-deployment.html

**Comment by dianasaur323** [comment]
@yaojingguo thanks for the feedback. cc @jseldess so that we can adjust our documentation.

**Comment by yaojingguo** [comment]
@dianasaur323 That is great.

**Comment by jseldess** [comment]
Thanks for assigning, @tschottdorf. I lost track of this issue.

I've created https://github.com/cockroachdb/docs/issues/2952 and will take care of this soon.
