### ISSUE TITLE
sql: timezone info consistency for DATE between insert and select

### ISSUE THREAD

**Issue by leomkkwan** [cockroachdb/cockroach#17199]
Not sure if this is a bug or I am missing something. For "Date" datatype, how do we store and retrive timezone info?

For example, if we change the time zone for a session to EST.

```
root@fdn5:26257/wolf> CREATE TABLE datetest (value DATE);
CREATE TABLE
root@fdn5:26257/wolf> insert into datetest values ('2017-01-01');
INSERT 1
root@fdn5:26257/wolf> select * from datetest;
+---------------------------+
|           value           |
+---------------------------+
| 2017-01-01 00:00:00+00:00 |
+---------------------------+
(1 row)
root@fdn5:26257/wolf> SET "time zone" = 'America/New_York';
SET
root@fdn5:26257/wolf> insert into datetest values ('2018-01-01');
INSERT 1
root@fdn5:26257/wolf> SELECT * FROM datetest;
+---------------------------+
|           value           |
+---------------------------+
| 2017-01-01 00:00:00+00:00 |
| 2017-12-31 00:00:00+00:00 |
+---------------------------+
(2 rows)
```

----------------------------------------------------------
What I expect is like how we do for timestamp datatype, which save everything in GMT and ignore session time zone.

```
root@fdn5:26257/wolf> create table timetest(value timestamp);
CREATE TABLE
root@fdn5:26257/wolf> insert into timetest values ('2017-01-01');
INSERT 1
root@fdn5:26257/wolf> select * from timetest;
+---------------------------+
|           value           |
+---------------------------+
| 2017-01-01 00:00:00+00:00 |
+---------------------------+
(1 row)
root@fdn5:26257/wolf> SET "time zone" = 'America/New_York';
SET
root@fdn5:26257/wolf> insert into timetest values ('2018-01-01');
INSERT 1
root@fdn5:26257/wolf> select  * from timetest;
+---------------------------+
|           value           |
+---------------------------+
| 2017-01-01 00:00:00+00:00 |
| 2018-01-01 00:00:00+00:00 |
+---------------------------+
(2 rows)
```

----------------------------------------------------------
Or like timestamptz type which handle timezone by session setting

```
root@fdn5:26257/wolf> CREATE TABLE timetest2 (value TIMESTAMP WITH TIME ZONE);
CREATE TABLE
root@fdn5:26257/wolf> insert into timetest2 values ('2017-01-01');
INSERT 1
root@fdn5:26257/wolf> select * from timetest2;
+---------------------------+
|           value           |
+---------------------------+
| 2017-01-01 00:00:00+00:00 |
+---------------------------+
(1 row)
root@fdn5:26257/wolf> SET "time zone" = 'America/New_York';
SET
root@fdn5:26257/wolf> INSERT INTO timetest2 VALUES ('2018-01-01');
INSERT 1
root@fdn5:26257/wolf> select * from timetest2;
+---------------------------+
|           value           |
+---------------------------+
| 2016-12-31 19:00:00-05:00 |
| 2018-01-01 00:00:00-05:00 |
+---------------------------+
(2 rows)
```

**Comment by leomkkwan** [comment]
I've see there is a Doc update for Timestamp datatype on alpha.20170803 release,but I beleive for Date datatype, that's not only doc change, but an actual bug.

If no timezone set, insert will save as UTC., select will show UTC. 
If timezone is set, insert will save as local time , but select is still in UTC.

There is a work around by using timestamptz to store date, but we are trying to save every single byte here as much as possible.

**Comment by knz** [comment]
Hi Justin! Could you please investigate this; clarify whether the current behavior is the expected behavior (in particular how well it's compatible with what pg does) and, if applicable, identify what needs to be fixed?

**Comment by justinj** [comment]
Yes this indeed looks to be wrong to me and inconsistent with pg. It appears to me that the use of either `time.UTC` or `loc` [here](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/parser/datum.go#L1101-L1106) is incorrect, but we have tests that fail if I change either so I think a bit more investigation is in order.
