### ISSUE TITLE
tracing: TestTrace passes when snowball tracing is broken

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#17191]
`TestTrace` essentially checks if we see a `/Batch` span in all cases. With gRPC interceptors, we have a client-side span and a server-side span (both with the same name). If snowball tracing is broken and the server-side span doesn't show up, the test is still satisfied by the client-side span.

This could be fixed by adding a tags column to session_trace, and ignoring the `/Batch` spans that have the `span.kind=client` tag (which is set by the interceptor).

**Comment by RaduBerinde** [comment]
@tbg @andreimatei not sure this issue still make sense.

**Comment by tbg** [comment]
I mean, this is probably still the case, but we have testing for the grpc interceptors now and those definitely catch that sort of thing: https://github.com/cockroachdb/cockroach/blob/eba03c4243693df39c0152680c13c8d875428b27/pkg/util/tracing/grpc_interceptor_test.go#L49-L52

So the real danger is that we somehow "forget" to set up the server side interceptor properly, but this is not that test's job to check neither. I like to think that it would prominently show up at least somewhere, so will close.
