### ISSUE TITLE
security: Insecure mode should not allow passwords to be set

### ISSUE THREAD

**Issue by liuliyun1** [cockroachdb/cockroach#17204]
recreation steps:

1. create a user with password 
2. grant priviliges on database to the user
3. connect to the database through jdbc, without setting password:

```
    Connection conn = null; 
    try 
    { 
        Class.forName("org.postgresql.Driver"); 
        String url = "jdbc:postgresql://10.202.202.102:26257/bigdata"; 
        try 
        { 
            conn = DriverManager.getConnection(url, "bdadmin", ""); 
            System.out.println("Succesfully connected to database : " + conn.getCatalog());
        } 
        catch (SQLException e) 
        { 
            e.printStackTrace(); 
        } 
    } 
    catch (ClassNotFoundException e) 
    { 
        e.printStackTrace(); 
    } 
    
  }

```

the output:

```
Successfully connected to database : bigdata
```

cockroach version:

```
Build Tag:    v1.0.3
Build Time:   2017/07/06 17:46:06
Distribution: CCL
Platform:     linux amd64
Go Version:   go1.8.3
C Compiler:   gcc 6.3.0
Build SHA-1:  b692a7cc7acc57022d1441034b93b85d860b7e86
Build Type:   release
```

**Comment by bdarnell** [comment]
`--insecure` mode is completely insecure and does not support any sort of authentication. You must configure your cluster with TLS certificates on the nodes to use authentication. For your clients you can either use TLS certificates or passwords for authentication (but client TLS certificates are recommended).

**Comment by bdarnell** [comment]
Given this, it's probably a bug that we allow you to set a password in an insecure cluster, where it will never be used.

**Comment by liuliyun1** [comment]
@bdarnell Thanks for your quick response!  So this is not a real problem in --insecure mode.
Closing issue.
