### ISSUE TITLE
Hash mismatch when apt-get update in build-docker-dev.sh build a docker image

### ISSUE THREAD

**Issue by YuleiXiao** [cockroachdb/cockroach#1723]
when build docker image , it report hash mismatch. build process can not continue. 

./build-docker-dev.sh 
Building Docker Cockroach images...
Sending build context to Docker daemon 20.48 kB
Sending build context to Docker daemon 
Step 0 : FROM golang:1.4.2
 ---> 124e2127157f
Step 1 : MAINTAINER Tobias Schottdorf <tobias.schottdorf@gmail.com>
 ---> Using cache
 ---> 6779403f4903
Step 2 : RUN apt-get update -y && 	apt-get dist-upgrade -y && 	apt-get install --no-install-recommends --auto-remove -y git build-essential pkg-config file npm &&  	apt-get clean autoclean &&  	apt-get autoremove -y &&  	rm -rf /tmp/* && 	ln -s /usr/bin/nodejs /usr/bin/node
 ---> Running in f3b531115198
Get:1 http://security.debian.org jessie/updates InRelease [63.1 kB]
Get:2 http://security.debian.org jessie/updates/main amd64 Packages [139 kB]
Get:3 http://httpredir.debian.org jessie InRelease [134 kB]
Get:4 http://httpredir.debian.org jessie/main amd64 Packages [9019 kB]
Get:5 http://httpredir.debian.org jessie-updates InRelease [133 kB]
Get:6 http://httpredir.debian.org jessie-updates/main amd64 Packages [3616 B]
W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie/main/binary-amd64/Packages  Hash Sum mismatch

E: Some index files failed to download. They have been ignored, or old ones used instead.
Fetched 9493 kB in 13s (695 kB/s)
The command '/bin/sh -c apt-get update -y && 	apt-get dist-upgrade -y && 	apt-get install --no-install-recommends --auto-remove -y git build-essential pkg-config file npm &&  	apt-get clean autoclean &&  	apt-get autoremove -y &&  	rm -rf /tmp/* && 	ln -s /usr/bin/nodejs /usr/bin/node' returned a non-zero code: 100

**Comment by tschottdorf** [comment]
this is a temporary error likely caused by a proxy caching old metadata, or just bad luck. We've seen it a few times on CI, and it's been transient. In any case, it's nothing we can fix.

**Comment by MaerF0x0** [comment]
+1  I suspect CircleCI caching in our case.  No proof tho.
