### ISSUE TITLE
acceptance: Test with `sslmode=verify-full`

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#17244]
Our acceptance tests currently use a secured server, but the clients do not verify the server's certificate. We have reports that `verify-full` does not work as expected for java clients, so we need to be testing this for every language in the acceptance tests. The diff below turns on `verify-full` for most languages (java is different; see `java_test.go`), but it fails because the certs have not been generated with the right hostname. We should regenerate certs so that they can pass this check and then enable it for all tested languages.

```
diff --git a/pkg/acceptance/util.go b/pkg/acceptance/util.go
index 2a6645749..70b69a634 100644
--- a/pkg/acceptance/util.go
+++ b/pkg/acceptance/util.go
@@ -512,8 +512,10 @@ func defaultContainerConfig() container.Config {
 		Image: postgresTestImage,
 		Env: []string{
 			fmt.Sprintf("PGPORT=%s", base.DefaultPort),
-			"PGSSLCERT=/certs/node.crt",
-			"PGSSLKEY=/certs/node.key",
+			"PGSSLCERT=/certs/client.root.crt",
+			"PGSSLKEY=/certs/client.root.key",
+			"PGSSLROOTCERT=/certs/ca.crt",
+			"PGSSLMODE=verify-full",
 		},
 	}
 }
```

Epic CRDB-10439

Jira issue: CRDB-6043

**Comment by knz** [comment]
Alfonso thanks for the re-triage.

@rafiss I could issue a PR with the change suggested by Ben, but you'd need to take any CI fallout from it on your team. Would that work for you?

**Comment by rafiss** [comment]
@knz thank you! Going ahead with this sounds good to me, and I'm happy to stay on top of CI fallout.

**Comment by knz** [comment]
I'm not able to look into this myself.
I'd like the test infra CS team to pick this up.
cc @tbg for triage.
