### ISSUE TITLE
perf: quantify benefit of disabling Go GC assist

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#17243]
The Go GC contains a facility for conscripting mutators (i.e. an application's goroutines) into performing work on behalf of the GC. This "GC assist" is needed to prevent a heavily allocating goroutine from allocating faster that GC can keep up. Unfortunately, it seems to have an outsize effect on tail latencies and a modest effect on peak throughput. 

<img width="930" alt="screen shot 2017-07-26 at 3 49 05 pm" src="https://user-images.githubusercontent.com/6201335/28640535-fc273942-7219-11e7-81db-a8442edfa584.png">

The segment on the left of the above graph is with stock go1.8.3. The segment on the right is with GC assist disabled (a 1-line change). That's a very significant improvement. The above was generated on a 6-node cluster running `kv --read-percent 95 --splits 2000 --concurrency 384 --max-rate 40000`. The rate limit was specified so that both runs were performing essentially the same number of ops/sec. Disabling the rate limit shows that peak throughput shows a modest improvement in the 5% range (TODO: provide a more precise number).

It would be desirable to get an upstream change to the GC assist facility. Perhaps the facility can be tuned to be less aggressive. It is possible there is simply a bug. 

There is concern that outright disabling of GC assist could lead to excessive memory usage. We need to quantify how much larger the Go heap is with GC assist disabled and to test under load which stresses allocations more heavily (e.g. TPC-H).

**Comment by petermattis** [comment]
Changes in go1.10 (presumably the GC changes) have significantly reduced 95%-tile and 99%-tile latencies:

```
go1.9:
_____N_____ops/sec__avg(ms)__p50(ms)__p95(ms)__p99(ms)
   192     14760.2      2.4      0.8     13.6     37.7

go-tip:
_____N_____ops/sec__avg(ms)__p50(ms)__p95(ms)__p99(ms)
   192     14998.5      1.1      0.8      2.9      8.9
```

**Comment by tschottdorf** [comment]
Nice!
