### ISSUE TITLE
roachtest: resurrect 1->6 allocator test

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#17240]
Failed test: [1->6 allocator test with 108 GB of data](https://teamcity.cockroachdb.com/viewLog.html?buildId=305532&buildTypeId=Cockroach_Nightlies_AllocatorTest1to6_108g&tab=buildLog)
Build: 5b74eda

I've attempted to run this test twice. The first time it timed out. The second time (the one linked to above) stalled. After 8 minutes, there were no allocator events, but the range counts weren't balanced. Excerpt from log ([source](https://teamcity.cockroachdb.com/viewLog.html?buildId=305532&buildTypeId=Cockroach_Nightlies_AllocatorTest1to6_108g&tab=buildLog&_focus=17139)):

```
[02:13:03][Step 3/3] --- FAIL: TestUpreplicate_1To6Medium (23368.47s)
[02:13:03][Step 3/3] 	allocator_test.go:202: 8m13s691ms394��s elapsed without changes, but replica count standard deviation is 591.14 (>52.00)
```

Things seem to have gotten backed up. There are a lot of slow commits in the logs. There are some of these errors:

```
E170726 06:03:41.686618 81328 storage/replica_range_lease.go:200  [replicate,n4,s4,r759/2:/Table/51/1/3{176744…-221596…}] context deadline exceeded
W170726 06:03:41.687114 196 storage/replica.go:1391  [replicate,n4,s4,r759/2:/Table/51/1/3{176744…-221596…}] have been waiting 1m0s attempting to acquire lease
```

and some of these:
```
E170726 06:06:08.462695 80627 storage/replica_range_lease.go:200  [n4,s4,r1638/2:/Table/51/1/433{22497…-66463…}] mismatch incrementing epoch for {NodeID:1 Epoch:1 Expiration:1501048781.667354611,0 Draining:false Decommissioning:false}; actual is {NodeID:1 Epoch:1 Expiration:1501048787.386022286,0 Draining:false Decommissioning:false}
```

and some:

```
E170726 06:01:38.668454 8491770 storage/replica_range_lease.go:200  [n2,s2,r1044/2:/Table/51/1/62{38000…-42405…}] context deadline exceeded
E170726 06:01:38.668823 195 storage/queue.go:658  [raftlog,n2,s2,r1044/2:/Table/51/1/62{38000…-42405…}] failed to send RPC: sending to all 2 replicas failed; last error: {<nil> rpc error: code = DeadlineExceeded desc = context deadline exceeded}
```

@a-robinson could you take a look? also, feel free to defer this work until after 1.1 feature freeze

**Comment by a-robinson** [comment]
Thanks @cuongdo! This actually looks quite similar to #17198, which I recently ran into on indigo. I'll be sure to track it down next week if I don't have enough time this week.

**Comment by nvanbenschoten** [comment]
Taking this over while investigating #17198.

**Comment by petermattis** [comment]
Are we still seeing problems with this test?

**Comment by a-robinson** [comment]
It looks like we've stopped running this test, actually. The last run appears to have been in mid-August: https://teamcity.cockroachdb.com/viewType.html?buildTypeId=Cockroach_Nightlies_AllocatorTest1to6_108g&tab=buildTypeHistoryList&branch_Cockroach_Nightlies=__all_branches__

**Comment by petermattis** [comment]
Oh. Well we should resurrect as part of the move to `roachtest`.

**Comment by petermattis** [comment]
@danhhz Is there anything left to do here?

**Comment by danhhz** [comment]
Nope! They got folded together and the resulting test is run nightly https://github.com/cockroachdb/cockroach/blob/6f1ba7656c00e0b8f1ddf1e95ffbfb5a390ca666/pkg/storage/allocator.go
