### ISSUE TITLE
Refactor MVCCStats and add a new structure for incremental update data  

### ISSUE THREAD

**Issue by kkaneda** [cockroachdb/cockroach#1724]
mrtracy wrote:

Looking to further improvements, the confusing bit here is that the logic for accumulating an incremental updates may be different than the logic for simply summing two MVCCStats (for example, these timestamps or especially the intent age field). I think the most correct model would be to create an entirely different structure for incremental update data, even if it is as simple as type MVCCDiff MVCCStats.

Then the (immutable) method signatures for MVCCStats would be:

```
type MVCCStatsInterface interface {
  // Accumulate from an incremental update.
  Accumulate(diff MVCCDiff) MVCCStats
  // Add values of two MVCCStats together.
  Add(other MVCCStats) MVCCStats
  // Subtract the values of another MVCCStat.
  Subtract(other MVCCStats) MVCCStat.
}
```

**Comment by vladdy** [comment]
I'm stating working on this.

**Comment by petermattis** [comment]
Given @tschottdorf's recent work here, is there anything left to be done?

**Comment by tschottdorf** [comment]
I think we can close this.
