### ISSUE TITLE
sql: plan not properly Close()d when an error occurs during plan expansion

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#17274]
panic: txn: unexpected leftover memory: 1555 bytes [recovered]
    panic: panic while executing "SELECT ROW ( ) AS OUT FROM [ SHOW CLUSTER QUERIES ] WITH ORDINALITY AS NUMERIC , [ SHOW CREATE VIEW STRING ] WITH ORDINALITY AS TYPE AS OF SYSTEM TIME 9.062206800374198e+17 WHERE TRUE IS TRUE": txn: unexpected leftover memory: 1555 bytes [recovered]

https://teamcity.cockroachdb.com/viewLog.html?buildId=307567&buildTypeId=Cockroach_Nightlies_RandomSyntaxTests

Found with RSG.

**Comment by knz** [comment]
Simplified:
```sql
select * from [show cluster queries], [show create table nonexistent];
```

The following queries do work properly:
```sql
SELECT * FROM [show create table nonexistent], (select 1);
SELECT * FROM (select 1), [show create table nonexistent];
SELECT * FROM [show create table nonexistent], [show cluster queries];
```

Without looking at the code, this tells me, the logic for `ShowClusterQueries` incorrectly registers memory towards a monitor (probably by allocating a `RowContainer` in the constructor). FYI RowContainers  should only be allocated after the logical plan has been successfully constructed, e.g. in the `Start` method or using a `delayedNode`.

@itsbilal can you have a look?

**Comment by knz** [comment]
hmm it's more complicated than that, I'm still investigating.

**Comment by knz** [comment]
Simpler even:
```sql
create table kv(k int, v int);
create index aa on t.kv(v);
select k from crdb_internal.jobs, kv@{force_index=aa,no_index_join};
```

When plan expansion encoutners an error (e.g. in this example no_index_join and non-covering index), expansion, optimization and planning is aborted, but the partially constructed plan is not `Close()`d. 

In the example above, the error was due to the `initialCheck()` method in delayedNode, but the problem is general, due to the way `optimizePlan()` was written.
