### ISSUE TITLE
distsql: ensure backward compatibility during upgrade

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#17277]
The RFC in #16977 describes a mechanism for upgrade without downtime. DistSQL went through some backward incompatible changes; we need to go back through them and fix `distsqlrun` to provide backward-compatibility, as well as gate use of new features in the planner.

CC @spencerkimball

**Comment by RaduBerinde** [comment]
An alternative is to get the changes to tolerate SetupFlow failures by rescheduling the flow on the gateway (#15637). However this is not ideal because during upgrade DistSQL queries might run on a small number of nodes - in the worst case, if 1 node is upgraded, any queries processed by that node will run all the flows on that same node - causing potential query regressions (in terms of how long they take to run, or even if they run at all due to memory usage).

**Comment by cuongdo** [comment]
@RaduBerinde please triage

**Comment by RaduBerinde** [comment]
Andrei is handling this, PR #17497

**Comment by andreimatei** [comment]
We're now not planning DistSQL flows on nodes that are running an incompatible version. This should be good for now; I'll defer the fallback stuff for later since it proved to not be so easy.

**Comment by jordanlewis** [comment]
I think the solution we have in place is already good enough.
