### ISSUE TITLE
sql: view dependencies are unnecessarily redundant

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#17275]
The fields `TableDescriptor.DependedOnBy` is an array of structs containing `TableDescriptor_Reference`, i.e. (TableID, []ColumnID) items.

Currently with the way view dependencies are computed (`backrefCollector` in `create.go`), if the same table is used multiple times in the query there will be multiple entries for the same table ID in `DependedOnBy`. For example with

```sql
 create view v as select a.k, b.v from kv a, kv b
```

we'd have `DependedOnBy` in `kv` set to `(id_of_v, [0]), (id_of_v, [1])`

Instead the `backrefCollector` should merge the `TableDescriptor_Reference` items that refer to the same table ID together.

**Comment by mattnenterprise** [comment]
@knz: Is this work still needed after https://github.com/cockroachdb/cockroach/commit/e28811cc07249cabaf82d002182ab0295cca8f40 ?

**Comment by knz** [comment]
Nope, well spoted! Thanks @mattnenterprise.
