### ISSUE TITLE
sql: perf difference between implicit and explicit transactions

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#17289]
In writing a new load generator I noticed a significant performance difference between using implicit and explicit transactions. I'm guessing that the explicit transaction is not hitting the 1PC code path while I think it should.

In both case the transaction contains a single `UPDATE` statement. The implicit version:

```
UPDATE test.rmw SET data='%s' WHERE id='%s'
```

And the explicit version:

```
BEGIN; UPDATE test.rmw SET data='%s' WHERE id='%s'; COMMIT;
```

The schema is:

```
CREATE TABLE IF NOT EXISTS test.rmw (
  id STRING PRIMARY KEY,
  data STRING
)
```

With the implicit transactions, a single worker is able to perform 850 ops/sec. With a the explicit transaction I see only 450 ops/sec. 

@andreimatei You tend to play around in this area of the code. Please reassign if there is someone better to look at this.

**Comment by andreimatei** [comment]
Hmm well we have no COMMIT elision at the sql level, so there's can't be a 1PC here. I guess you're saying there should be.

**Comment by petermattis** [comment]
I thought there was equivalent performance for these two queries at one point. Perhaps I'm misremembering. Eliding the COMMIT at the sql level isn't necessary, just looking ahead past the currently executing statement to see if the next is a COMMIT.

**Comment by arjunravinarayan** [comment]
Assigned to @richardwu for investigation.

**Comment by richardwu** [comment]
cc: @andreimatei who is refactoring the executor.

**Comment by jordanlewis** [comment]
Closing due to staleness.

**Comment by andreimatei** [comment]
Well but this issue is very valid, and actionable, and everything. If anything, the fact that it's old makes it more import, not less... Why close?

**Comment by jordanlewis** [comment]
Nobody's encountered or tested this scenario since 2017. Do you think it's still valid? I don't see the value in keeping something like this open if there's no movement or planned work on it. That being said, happy to keep open if you find it useful.

**Comment by andreimatei** [comment]
I think it's still valid, yeah. However it looks like we tried to do something about it in #18664 and it proved to not be entirely trivial.

**Comment by andreimatei** [comment]
Folded into #4703
