### ISSUE TITLE
config: add a StaticSplit to isolate the node liveness span

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#17297]
The node liveness span is critical to cluster operation. When investigating a cluster, it is very helpful to know that it is not sharing its range with anything else.

**Comment by bdarnell** [comment]
Zone config boundaries also imply split points, so if we give the liveness span its own zone config (#14990), that will make the split happen automatically. Probably still a good idea to use the simple StaticSplit mechanism for these critical ranges, though.

**Comment by petermattis** [comment]
Adding a static split for node liveness seems reasonable for 1.1, but let's leave changing the default zone config until 1.2.

**Comment by cuongdo** [comment]
@m-schneider We're getting pretty close to the freeze for 1.1. How is the fix for this issue going?

**Comment by m-schneider** [comment]
Going to send out the PR today.
