### ISSUE TITLE
keys: add the meta2 span to NoSplitSpans

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#17296]
We still haven't fixed https://github.com/cockroachdb/cockroach/issues/2266 and may not do so for a while. Real deployments don't easily split their meta2 ranges (as they don't grow very quickly) but if they did, we may see pretty chaotic behavior due to the linked issue.

In the interim, we should add a corresponding span to `keys.NoSplitSpans`.

**Comment by petermattis** [comment]
Fixed by #17565.
