### ISSUE TITLE
ui: add Raft message breakdown page

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#17298]
We don't have good visibility into Raft, which is always a problem when investigating a cluster. We need a ui facility similar to the screenshot below. The data is already scraped; just need to add a page for it in the ui. That page can be hidden by default if ui polish is a concern.

![image](https://user-images.githubusercontent.com/5076964/28737983-08cd05c2-73bf-11e7-8142-4ebbc5302c64.png)

**Comment by cuongdo** [comment]
@dianasaur323 do you have thoughts on how to integrate this with the admin UI?

**Comment by dianasaur323** [comment]
I think it's unlikely any of our users would actually know how to debug by looking at this Raft page. My thought is to hide this with the other debug pages, and package it in the export feature we are building in 1.2. I believe @couchand's recent commit essentially does this.
