### ISSUE TITLE
sql: panic: prepare values

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#17312]
`prepare a as (VALUES (DEFAULT, DEFAULT) ORDER BY PRIMARY KEY "substring".ident DESC);`

Doesn't fail without the prepare.

https://teamcity.cockroachdb.com/viewLog.html?buildId=308887&buildTypeId=Cockroach_Nightlies_RandomSyntaxTests

Found with RSG.

**Comment by knz** [comment]
Simpler query:
```sql
PREPARE a AS (SELECT 1) ORDER BY PRIMARY KEY foo;
```
