### ISSUE TITLE
How does cockroach compare to treode ?

### ISSUE THREAD

**Issue by atrniv** [cockroachdb/cockroach#1731]
I just came across a new database called Treode built in Scala that seems to have several very interesting features. From what I could gather Treode seems to be more scalable and flexible in the type of workloads it could handle (analytical + transactional),  however it's an embedded database currently. Has the cockroach db team taken a look at it ? How would treode compare to cockroachdb ?

**Comment by spencerkimball** [comment]
I haven't used Treode directly, but from what I've seen, it's a
well-designed and capable system. There are many similarities to
CockroachDB in terms of transactionality, MVCC, and scalability. A big
difference, but one which wouldn't necessarily be visible to the end user,
is that while Cockroach implements a monolithic sorted map, Treode uses a
variant of consistent hashing. That difference will be visible or not
depending on your use case. I'm not clear from the design I've read how
Treode handles clock offsets during transactional reads or whether its
shard replication is consistent.

In addition, CockroachDB is now moving aggressively to support SQL and
Treode is focused on a NoSQL API.

Hope this helps!

Spencer

**Comment by atrniv** [comment]
What would be the pros and cons of the monolithic sorted map and the consistent hashing approach as the data size grows ? Also will cockroach have any of the capabilities of trenode like the way of using timestamps in transactions in future ?

https://forum.treode.com/t/eventual-consistency-and-transactions-working-together/36

**Comment by spencerkimball** [comment]
A monolithic sorted map allows for very large global indexes to be built
and queried efficiently. Consistent hashing is faster when accessing keys
for reading and writing, as no index lookups are required. The lower
latency on key access is mostly relevant when a node has recently restarted
and its index lookup cache is empty, as there's generally a lot of locality
when accessing key ranges.

Cockroach has no plans for doing what Treode calls OMVCC. Cockroach does
support historic reads at arbitrary timestamps (dependent of course on what
TTL you set for your data, once overwritten--by default it's 1 day).

**Comment by atrniv** [comment]
Thank you for the insights :+1:  :) !
