### ISSUE TITLE
release v1.1-alpha-20170803

### ISSUE THREAD

**Issue by m-schneider** [cockroachdb/cockroach#17329]
Candidate SHA: [`1e88c32`](https://github.com/cockroachdb/cockroach/commit/1e88c32588fd3d7cad826437c18b349fd70e4762)
Deployment status: `adriatic`, `blue`, `cerulean`, `omega`

[Release process checklist](https://github.com/cockroachdb/cockroach/wiki/Release-Process)

Prep date:  `2017-07-31`
- [X] [Pick a sha](https://github.com/cockroachdb/cockroach/wiki/Release-Process#pick-sha), fill in `Candidate SHA` above.
- [X] Deploy to test clusters, fill in `Deployment status` above
- Keep an eye on clusters until release date.

Release date: `2017-08-03`
- [x] [Check cluster status](https://github.com/cockroachdb/cockroach/wiki/Release-Process#check-cluster)
- [x] [Tag release](https://github.com/cockroachdb/cockroach/wiki/Release-Process#tag-release)
- [x] [Trigger release build](https://github.com/cockroachdb/cockroach/wiki/Release-Process#trigger-build)
- [x] [Check binaries](https://github.com/cockroachdb/cockroach/wiki/Release-Process#check-binaries)
- [x] Update docs
- [x] External communications for release
- [x] File issue for next release and assign to release coordinator

**Comment by couchand** [comment]
Next week's release here: #17426
