### ISSUE TITLE
storage: ReadWithinUncertaintyIntervalError with concurrent inserts

### ISSUE THREAD

**Issue by jonbonazza** [cockroachdb/cockroach#17337]
We are evaluating the use of Cockroachdb and have a 5 node cockroach cluster running in docker containers in a single docker swarm. These containers span multiple nodes, with some instances running on the same node. According to the dashboard, all nodes are healthy and resource utiliztion is far under the constratins provided to docker swarm.

I have a small Go app that scans a table in HBase with ~7600 rows and for each cell in the scan, inserts into cockroachdb. These inserts are **not** batched and we are using the GORM library to create the tables and do the inserts. Before each run, we drop the database and recreate it to ensure a clean slate. Also, each insert is performed in a separate goroutine, guarded by a semaphore with a capacity of 5, ensuring that no more than 5 inserts can occur concurrently (I've also tried this with 100 and 20 capacities, and didn't notice any differences).

The issue I am seeing is that occasionally during the migration, the following lib/pq error is encountered:
```
(pq: restart transaction: HandledRetryableTxnError: ReadWithinUncertaintyIntervalError: read at time 1501535378.485976367,0 encountered previous write with future timestamp 1501535378.503491077,0 within uncertainty interval)
[2017-07-31 14:09:39]

(pq: current transaction is aborted, commands ignored until end of transaction block)
[2017-07-31 14:09:39]
```

At the end of the migration, ~1200/7600 rows were missing from cockroachdb.

It should be noted that this issue **does not** occur when inserts are performed synchronously.

Unfortunately, I cannot provide the schema for the tables that I am inserting into, as they belong to a very high profile company.

I can say, however, that the main table has an integer primary key that is generated using the ```unique_rowid()``` function in cockroachdb, and contains a number of relations and associations. The other, related tables all have primary keys based on a combination of fields that will be unique for each occurance. 

We are using the following cockroachdb environment:
Build Tag:    v1.0.4
Build Time:   2017/07/27 17:54:36
Distribution: CCL
Platform:     linux amd64
Go Version:   go1.8.3
C Compiler:   gcc 6.3.0
Build SHA-1:  5b757262d33d814bda1deb2af20161a1f7749df3
Build Type:   release

**Comment by jonbonazza** [comment]
Also, FWIW, the actual migration code looks like so:
```go
func migrate(tableName string, concurrency int, hbaseClient gohbase.Client, db *gorm.DB) error {
	table := hbase.NewTable(tableName, hbaseClient, nil)
	scanner, err := table.Scan(context.Background())
	if err != nil {
		return err
	}
	defer scanner.Close()
	var row *hrpc.Result
	sem := make(chan struct{}, 5)
	for err != io.EOF {
		if row, err = scanner.Next(); err == nil {
			go processRow(row, db, sem)
		} else if err != io.EOF {
			return err
		}
	}
	for i := 0; i < cap(sem); i++ {
		sem <- struct{}{}
	}
	return nil
}

func processRow(row *hrpc.Result, db *gorm.DB, sem chan struct{}) {
	sem <- struct{}{}
	defer func() { <-sem }()
	for _, cell := range row.Cells {
		fmt.Println("Proccessing row " + string(cell.Row[5:]))
		var p Product
		if err := json.Unmarshal(cell.Value, &p); err != nil {
			fmt.Fprintln(os.Stderr, err)
			continue
		}
		if err := db.Create(&p).Error; err != nil {
			fmt.Fprintln(os.Stderr, err)
		}
	}
}
```

**Comment by jonbonazza** [comment]
At @tschottdorf request in GItter, I have run the following query:
```SELECT count, max_retries, anonymized FROM crdb_internal.node_statement_statistics ORDER BY count DESC;```
and the results are:
```
| count | max_retries |                                                                                                                     anonymized                                                                                                                     |
+-------+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 13149 |           0 | SELECT * FROM _ WHERE (_._ = $1) AND (_._ = $2) ORDER BY _._ ASC LIMIT _                                                                                                                                                                           |
|  9922 |           0 | INSERT INTO _(_, _, _) SELECT $1, $2, $3 WHERE NOT EXISTS (SELECT * FROM _ WHERE ((_ = $4) AND (_ = $5)) AND (_ = $6))                                                                                                                             |
|  3587 |           0 | INSERT INTO _(_, _) VALUES ($1, $2) RETURNING _._                                                                                                                                                                                                  |
|  2361 |           0 | INSERT INTO _(_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27) RETURNING _._ |
|  1880 |           0 | UPDATE _ SET _ = $1, _ = $2, _ = $3, _ = $4, _ = $5, _ = $6 WHERE _._ = $7                                                                                                                                                                         |
|  1828 |           0 | INSERT INTO _(_, _, _, _, _, _, _) VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING _._                                                                                                                                                               |
|  1648 |           0 | INSERT INTO _(_, _) SELECT $1, $2 WHERE NOT EXISTS (SELECT * FROM _ WHERE (_ = $3) AND (_ = $4))                                                                                                                                                   |
|  1617 |           0 | INSERT INTO _(_, _, _) SELECT $1, $2, $3 WHERE NOT EXISTS (SELECT * FROM _ WHERE ((_ = $4) AND (_ = $5)) AND (_ = $6))                                                                                                                             |
|  1611 |           0 | INSERT INTO _(_, _, _) SELECT $1, $2, $3 WHERE NOT EXISTS (SELECT * FROM _ WHERE ((_ = $4) AND (_ = $5)) AND (_ = $6))                                                                                                                             |
|  1601 |           0 | INSERT INTO _(_, _) SELECT $1, $2 WHERE NOT EXISTS (SELECT * FROM _ WHERE (_ = $3) AND (_ = $4))                                                                                                                                                   |
|  1194 |           0 | INSERT INTO _(_, _) SELECT $1, $2 WHERE NOT EXISTS (SELECT * FROM _ WHERE (_ = $3) AND (_ = $4))                                                                                                                                                   |
|  1118 |           0 | UPDATE _ SET _ = $1, _ = $2, _ = $3, _ = $4, _ = $5 WHERE _._ = $6                                                                                                                                                                                 |
|   391 |           0 | INSERT INTO _(_, _, _, _, _, _, _) VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING _._                                                                                                                                                               |
|   391 |           0 | SELECT * FROM _ WHERE _._ = $1 ORDER BY _._ ASC LIMIT _                                                                                                                                                                                            |
|   232 |           0 | INSERT INTO _(_, _) SELECT $1, $2 WHERE NOT EXISTS (SELECT * FROM _ WHERE (_ = $3) AND (_ = $4))                                                                                                                                                   |
|   227 |           0 | INSERT INTO _(_, _) SELECT $1, $2 WHERE NOT EXISTS (SELECT * FROM _ WHERE (_ = $3) AND (_ = $4))                                                                                                                                                   |
|   217 |           0 | INSERT INTO _(_, _, _, _, _) VALUES ($1, $2, $3, $4, $5) RETURNING _._                                                                                                                                                                             |
|   141 |           0 | INSERT INTO _(_, _) SELECT $1, $2 WHERE NOT EXISTS (SELECT * FROM _ WHERE (_ = $3) AND (_ = $4))                                                                                                                                                   |
|    86 |           0 | SELECT _, _, _, _, _, _ FROM _ WHERE _ ORDER BY _ DESC LIMIT $1                                                                                                                                                                                    |
|    41 |           0 | UPDATE _ SET _ = $1, _ = $2, _ = $3, _ = $4, _ = $5 WHERE _._ = $6                                                                                                                                                                                 |
|     5 |           0 | SELECT _ FROM _ WHERE _ = $1                                                                                                                                                                                                                       |
|     3 |           0 | SELECT _ FROM _ WHERE (_ = $1) AND (_ = $2)                                                                                                                                                                                                        |
|     2 |           0 | SELECT * FROM _ WHERE _._ = $1 ORDER BY _._ ASC LIMIT _                                                                                                                                                                                            |
|     2 |           0 | INSERT INTO _(_, _, _, _, _, _) VALUES ($1, $2, $3, $4, $5, $6) RETURNING _._                                                                                                                                                                      |
|     1 |           0 | SELECT _ FROM crdb_internal.node_statement_statistics                                                                                                                                                                                              |
|     1 |           0 | SELECT _, _ FROM crdb_internal.node_statement_statistics ORDER BY _ DESC                                                                                                                                                                           |
```

**Comment by petermattis** [comment]
@jonbonazza Can you provide more details about your schema? I'm suspicious that you're encounter uniqueness violations which are being misreported as `ReadWithinUncertaintyIntervalError` (that's a bug in cockroach). But why are you getting uniqueness violations? One possibility is the row returned by `scanner.Next()` is being reused by the scanner. You could try printing out the rows you're inserting.

@tschottdorf The `ReadWithinUncertaintyIntervalError` might be the issue with conditional puts we saw #17108.

**Comment by jonbonazza** [comment]
@petermattis I unfortunately cannot provide the schema, however my ORM does log when uniqueness constraints are violated and I have ensured that none of these logs are issued.

**Comment by petermattis** [comment]
@jonbonazza How is your ORM detecting unique constraint violations? We believe there is a bug in cockroach where we'll return `ReadWithinUncertaintyIntervalError` instead of the correct unique constraint violation when concurrent inserts are performed. Printing out the rows you're inserting (or the values of the primary key) would be an easy way to sanity check your code.

Are you using `github.com/tsuna/gohbase` or another hbase client?

**Comment by jonbonazza** [comment]
Okay, I have narrowed down the issue to the following obfscuated schema:
```go
type M struct {
	ID    int64
	K   string
	M string
	R   string
	T  int
	U   string
}

type P struct {
	ID        uint   `gorm:"primary_key"`
	M []M `gorm:"many2many:p_Ms"`
}
```
I have many other fields in the "P" model, however if I only remove the M field, it all works fine, so there is something weird here.

Also, yes, I am using the tsuna/gohbase lib.

**Comment by jonbonazza** [comment]
Hmm... Since M's ID is not a ```unique_rowid()```  but instead a pregenerated from the source data,  I wonder if multiple goroutines are trying to create M with the same ID at once and causing that's causing issues?

**Comment by jonbonazza** [comment]
I'm not seeing the unique constraint violation logged, but perhaps GORM is doing something under the hood to hide it, and cockroach doesn't know how to react?

**Comment by petermattis** [comment]
@tschottdorf I'm pretty sure the `ReadWithinUncertaintyIntervalError` is the same issue with conditional puts we saw #17108. We definitely generate `ReadWithinUncertaintyIntervalError` before checking the value on conditional puts. I'm not sure if the impact of changing this.

**Comment by bdarnell** [comment]
@jonbonazza  This is a "restart transaction" error. Such errors can occur in principle at any time in CockroachDB, so applications need to be prepared to handle them ([more docs](https://www.cockroachlabs.com/docs/stable/transactions.html#client-side-intervention)). In Go, you can use [our library](https://github.com/cockroachdb/cockroach-go/blob/master/crdb/tx.go) for this. 

In #17108, we're investigating the theory that these ReadWithinUncertaintyIntervalErrors should be turned into ConditionFailedErrors instead (which would be reported to the client as "unique constraint violation"). In that issue, this change would make the problem go away, because the queries used there specify `ON CONFLICT DO NOTHING`. Gorm does not use the `ON CONFLICT` clause (as far as I can tell), so while a resolution to #17108 would give you a clearer error message, the errors would still be there.

**Comment by tschottdorf** [comment]
@spencerkimball how will this behave with your recent changes? I expect that the retry would be made internal, and that you'd get the condition failed error back. Is that correct?

**Comment by spencerkimball** [comment]
@tschottdorf that's correct. Unless there's there are refreshed spans which indicate a possible serializable error (unlikely in this case and in #17108), this will retry at the txn coord sender at a higher timestamp, get the condition failed error, and return to the client without and error.

**Comment by tschottdorf** [comment]
@nvanbenschoten could you decide what to do with this (especially the milestone)? Looks like a performance tradeoff to be considered.
