### ISSUE TITLE
sqlccl: clean up fallout from last minute csv->sstable in distsql work

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#17330]
The distributed csv -> BACKUP process got a little last minute and we incurred some technical debt. This issue is a meta-issue to make sure it doesn't get lost.

- [ ] Decide whether to export distSQLPlanner so it can be roundtripped through sqlccl and the PlanHook
- [ ] Filter out unhealthy nodes in the "planning"
- [x] Consider making FinalizePlan take a map of nodeID -> address explicitly instead (or in addition to) the PlanCtx
- [x] Make `(*distSQLPlanner).Run` work without a txn for non-transactional flows

**Comment by danhhz** [comment]
Alright @RaduBerinde @andreimatei @mjibson lets hash out this `distSQLPlanner` thing. Here's the issue at hand:

- The planHook for LOAD lives in `sqlccl`, it gets a `PlanHookState` interface which is implemented by `sql.planner`
- loadPlanHook needs to (at some point) run a distsql flow. Currently the code to do this lives in `sql`, so to make this work we need to roundtrip the distSQLPlanner through `sqlccl` via the PlanHookState. As merged, this is accomplished by making a new exported struct `DistLoader` and passing that through PlanHookState

The other options as I see them:
1) Make a new distSQLPlanner. This requires passing a lot of other stuff through PlanHookState: distsqlrun.ServerImpl, rpc.Context, etc (I consider this not workable)
2) Executor has a via PlanHookState, roundtrip it through PlanHookState. This is difficult as there is no Executor available from planner (which is our implementation of PlanHookState) and it seems to have intentionally been avoided; planner gets an Executor upon creation but only saves the pieces it needs (I consider this not workable)
3) Export distSQLPlanner so we can roundtrip it through PlanHookState. distSQLPlanner currently has a bunch of exported methods that accept unexported types, which is a no-no on an exported struct, so we'd have to address that (workable)
4) Make an interface for the relevant parts of distSQLPlanner, pass the interface via PlanHookState and move the logic we currently have in sql to sqlccl. Naively, this would mean that `planningCtx`, `physicalPlan`, and `distSQLReceiver` would need to be exported (essentially a subset of (3). workable)
5) Pass the entire PlanHookState to `sql.LoadCSV`. Cast it to a `planner` and get the distSQLPlanner out of that. @mjibson points out that this could also simplify the signature of `sql.LoadCSV` as we don't have to pass the `client.DB` or the `ExecCtx` individually. (I feel like this will be less maintainable in the long run)
6) Pass distSQLPlanner through PlanHookState as an `interface{}` (this is pretty gross)
7) Move absolutely everything into sql (this is unfortunate and I feel like we have to solve this problem eventually)
8) Leave it as is
9) Anything I've missed?

**Comment by RaduBerinde** [comment]
It would be useful to expand on "needs to run a distsql flow". The main question I have is if the `sqlccl` code must necessarily figure out all the details of the flow, or if there is some higher-level description of what it's trying to do that it can pass to distSQLPlanner, and let it worry about the details of the physicalPlan.

We can take the path of least resistance for now (leave as is) and clean up later - we can make a better judgement when can look at the code to generate the flow and see exactly what it needs to do.

**Comment by mjibson** [comment]
I'm ok with Radu's suggestion to wait for now. We could also wait for a second user of the code (index backfills maybe) and then be able to make some better decisions.

**Comment by mjibson** [comment]
This has mostly all been done or refactored away.
