### ISSUE TITLE
sqlccl: unique violation error may be swalloed, needs refactor

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#17336]
https://teamcity.cockroachdb.com/viewLog.html?buildId=310737&buildTypeId=Cockroach_UnitTests_Testrace

**Comment by tschottdorf** [comment]
is it possible that `ioutil.WriteFile` doesn't sync and that this leads to a don't-see-your-own-write situation? I checked the code and it does `close()` but it does look like `Sync()` does do more.

**Comment by bdarnell** [comment]
`Close()` guarantees that your data has been flushed to the kernel, so you'll get it back if you open the file and read it. (I think the recent case where an explicit `Sync()` was needed was on a network filesystem, and the sync was needed to make sure that the data would be visible to a remote process) However, closing a file which has unsynced writes can fail, so we should be sure to check errors returned by `os.File.Close` (it's currently in our `errcheck_excludes` list).

**Comment by tschottdorf** [comment]
The `Close()` in this case happens in `ioutil.WriteFile` and is checked. Any other theories?

**Comment by tschottdorf** [comment]
Ok, this repros pretty easily on my macbook, so will probably be able to get this tomorrow.

**Comment by tschottdorf** [comment]
@mjibson the error is here:

```go
	group.Go(func() error {
		var err error
		defer func() {
			// prints: SST creation error at /Table/51/2/3/0; this can happen when a primary or unique index has duplicate keys: Invalid argument: Keys must be added in order
			fmt.Println(err)
			close(contentCh)
		}()
		kvCount, err = writeRocksDB(gCtx, kvCh, tempEngine, sstMaxSize, contentCh, walltime)
		if job != nil {
			if err := job.Progressed(ctx, 2.0/3.0, jobs.Noop); err != nil {
				log.Warningf(ctx, "failed to update job progress: %s", err)
			}
		}
		return err
	})
```

The goroutine that gets the error closes the channel and then returns, so naturally there's no guarantee that another goroutine that waits on the channel doesn't error out first.

Should be simple to fix, though the structure here needs to change.
