### ISSUE TITLE
sql: Upsert does not respect WHERE clause constraints

### ISSUE THREAD

**Issue by jcoene** [cockroachdb/cockroach#17339]
Hello!

I'm evaluating CockroachDB for a new project which would insert or update records only when certain constraints are met. Looking at the documentation, this appears to be supported:

<img width="513" alt="screen shot 2017-07-31 at 4 50 50 pm" src="https://user-images.githubusercontent.com/283933/28800006-6fac0ace-7610-11e7-8d3b-c509e3d5511d.png">

Unfortunately, it appears that the `where_clause` in `on_conflict` is being silently discarded. I'm not sure if this is a regression or an issue with the documentation, but thought it worth raising.

- What did you do?

```
root=> create database stuff;
CREATE DATABASE
root=> create table stuff.people (id int primary key, name string, register int);
CREATE TABLE
root=> insert into stuff.people (id, name, register) values (1, 'Person', 1);
INSERT 0 1
root=> select * from stuff.people;
 id |  name  | register 
----+--------+----------
  1 | Person |        1
(1 row)

root=> insert into stuff.people (id, name, register) values (1, 'Bad Data', 0) on conflict (id) do update set name = excluded.name, register = excluded.register where excluded.register > register;
INSERT 0 1
root=> select * from stuff.people;
 id |   name   | register 
----+----------+----------
  1 | Bad Data |        0
(1 row)

root=> insert into stuff.people (id, name, register) values (1, 'Worse Data', 0) on conflict (id) do update set name = excluded.name, register = excluded.register where the_king_of_the_north > the_white_walkers;
INSERT 0 1
root=> select * from stuff.people;
 id |    name    | register 
----+------------+----------
  1 | Worse Data |        0
(1 row)
```

- What did you expect to see?

The existing values of `name` and `register` to be retained because the WHERE clause was not satisfied.

- What did you see instead?

The values of `name` and `register` are updated regardless of the contents of the WHERE clause.

**Comment by jordanlewis** [comment]
Thanks for the report. You're right - we do completely ignore any `WHERE` clause specified in an `ON CONFLICT DO UPDATE` clause. As far as I can tell this is just an oversight - there's no good reason why we do that.

As such, we can probably provide a fix shortly.

**Comment by jcoene** [comment]
Glad to hear that it’s likely a straightforward fix. Thanks for the quick response!
