### ISSUE TITLE
sql, storage: SCATTER doesn't do anything

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#17341]
```sql
root@:26257/ro> ALTER TABLE devices SCATTER;
+-----+--------+
| key | pretty |
+-----+--------+
+-----+--------+
(0 rows)
root@:26257/ro> SHOW TESTING_RANGES FROM TABLE devices;
+-----------+---------+----------+--------------+
| Start Key | End Key | Replicas | Lease Holder |
+-----------+---------+----------+--------------+
| NULL      | NULL    | {1,2,3}  |            3 |
+-----------+---------+----------+--------------+
```
The scatter command returns instantly and nothing changes (I can repeat the above many times and always see the same lease holder).

```
root@:26257/ro> alter table raw_visits scatter;
+-----+--------+
| key | pretty |
+-----+--------+
+-----+--------+
(0 rows)
root@:26257/ro> SHOW TESTING_RANGES FROM TABLE raw_visits;
+-----------+---------+----------+--------------+
| Start Key | End Key | Replicas | Lease Holder |
+-----------+---------+----------+--------------+
| NULL      | /1      | {1,2,3}  |            2 |
| /1        | /10     | {1,2,3}  |            1 |
| /10       | /20     | {1,2,3}  |            1 |
| /20       | /50     | {1,2,3}  |            1 |
| /50       | /100    | {1,2,3}  |            1 |
| /100      | NULL    | {1,2,3}  |            1 |
+-----------+---------+----------+--------------+
(6 rows)
root@:26257/ro> ALTER TABLE raw_visits SCATTER;
+-----+--------+
| key | pretty |
+-----+--------+
+-----+--------+
(0 rows)
root@:26257/ro> SHOW TESTING_RANGES FROM TABLE raw_visits;
+-----------+---------+----------+--------------+
| Start Key | End Key | Replicas | Lease Holder |
+-----------+---------+----------+--------------+
| NULL      | /1      | {1,2,3}  |            2 |
| /1        | /10     | {1,2,3}  |            1 |
| /10       | /20     | {1,2,3}  |            1 |
| /20       | /50     | {1,2,3}  |            1 |
| /50       | /100    | {1,2,3}  |            1 |
| /100      | NULL    | {1,2,3}  |            1 |
+-----------+---------+----------+--------------+
(6 rows)
```

This is on a 3-node cluster. I expect the lease holders to change when we scatter. Is this no longer the case? @benesch

**Comment by a-robinson** [comment]
The recent revamp may have swung things a little too far toward restore's use case. It now just eagerly runs all the included ranges through the allocator logic, which means that if the leases in the cluster are already balanced overall, it won't do anything to scatter the specific set of ranges that you care about. I assume that's the problem you're seeing -- that overall the leases are properly spread, just not for the `raw_visits` table.

**Comment by RaduBerinde** [comment]
Yeah, we want scatter to re-spread the leases of a table (e.g. to get a different distsql plan for testing or performance purposes).

**Comment by benesch** [comment]
Perhaps we need two different versions of scatter? The old version was much
closer to what you need, no? cc @danhhz

**Comment by RaduBerinde** [comment]
Would it be possible to plumb some kind of flag to force the allocator to get a new configuration even if everything is balanced? I suspect that would be ok for restore too, if not we can have two flavors of it.

**Comment by benesch** [comment]
@a-robinson is the expert here, but I don't think such a flag is possible given the design of the allocator. Specifically, the allocator is "stateless" in that it can only suggest the best action to take to balance the cluster for any given range, based on the number of ranges/leases on each store. It doesn't keep any state of its own, e.g. an internal map of which stores should have which ranges/leases that could be easily shuffled.

@RaduBerinde, do you disable replica rebalancing (or _could_ you disable replica rebalancing) whenever you need `SCATTER` for DistSQL? I suspect any flakiness from the version of scatter you wrote resulted from races with the replicate queue.

**Comment by jordanlewis** [comment]
Related to #17153 , which tracks scatter not producing output.

**Comment by RaduBerinde** [comment]
We want to be able to use SCATTER even in real deployments if we need to re-distribute a table. It's not that critical for testing, we can fall back to TESTING_RELOCATE and move things manually.

**Comment by danhhz** [comment]
One thing we've learned in the 1.1 work is that making SCATTER work on real deployments with non-trivial data in the ranges is _really_ hard. You have to account for rate limiting of snapshots, which IIUC is surprisingly difficult with the way the rebalance queue is currently written. The 1.0 implementation of SCATTER also would not work on a real cluster, most of the ranges would come back with a "snapshot rate limit exceeded" error and would not have been moved.

So the tl;dr here is there's certainly something we can do in the 1.1 timeframe to address your above example, but "We want to be able to use SCATTER even in real deployments if we need to re-distribute a table." is actually a pretty ambitious project and should probably go through product/airtable for prioritization.

**Comment by benesch** [comment]
Oooof, yes, if you want to scatter ranges with real data, you'll need a "scatter" queue to avoid immediately bumping up against snapshot apply limit. That queue will be fighting the replicate queue, since it'll be unbalancing the global state; you'd need to be somehow convince the replicate queue not to touch any of the ranges you're scattering.

This sounds like it might need range hints. A scatter queue plus a "don't touch me for _x_ minutes" hint might do the trick. cc @BramGruneir 

But 100% agreed with @danhhz: this is a huge project.

**Comment by RaduBerinde** [comment]
This issue was not intended for 1.1.

My thought was that we should look at trying to still use the replicate queue, just somehow keep track of a hint somewhere that it should pretend a particular range is new when choosing locations for the replicas (it can choose them according to its normal logic - if the only possible setup that is consistent with a balanced cluster is the current one, so be it).

**Comment by benesch** [comment]
I'm not sure I follow, @RaduBerinde. The allocator IUIU doesn't have any concept of a new range vs an existing range. It just sees ranges. Eventually, if splits cause a node to have too many ranges, the allocator will instruct the replicate queue to move whatever random range happens to be fed in first to an underfull store. (Plus a whole bunch more complexity for taking zone configs and load into account.)

**Comment by RaduBerinde** [comment]
Ah, right, that makes sense.

If all a scatter does is "eagerly runs all the included ranges through the allocator logic", couldn't we have done that for the new range whenever we split a range? Restore wouldn't need a separate scatter operation if we just prioritize split ranges (which seems like a good idea in general).

**Comment by benesch** [comment]
Yup, both halves of split ranges are already auto-added to the replicate queue. The problem, though, is that the replicate queue only makes decisions for the ranges it's the leaseholder for. If leases are unbalanced, the replicate queue has to first transfer away the lease. The new leaseholder has no idea the range was just split, and so the range might not end up back in the replicate queue for an entire scanner cycle. We could auto-add ranges to the replicate queue on the new leaseholder when the lease changes hands—and in fact, we probably should do this—but restore has likely split the range again by this point, so the rebalancing will only impact the left half of the range. Sending a scatter command is a nice way to guarantee that the range has balanced its lease and replicas before proceeding with the next split.

**Comment by RaduBerinde** [comment]
I see, thanks for the explanation.

**Comment by a-robinson** [comment]
While scattering replicas around in a new way would require a fair amount of work, randomizing the lease distribution (and then relying on the normal replicate queue to later even things back out) would be fairly simple (and that code essentially already existed in 1.0).

**Comment by bdarnell** [comment]
Another thought: In general, we want to SCATTER ranges because we know that changes in either data size or query traffic are coming that are expected to cause the equilibrium to shift, and we want the rebalancer to make those changes now while they're less disruptive. So one way to think of the scatter operation is to artificially boost the size or traffic stats for the affected ranges before running them through the replication queue. It's not about "new ranges" per se, but a size-based split is a good sign that a range is growing, so temporarily boosting the size of a recently-split range for the purposes of rebalancing would make sense. I don't have concrete thoughts about how we'd implement this, though.

**Comment by petermattis** [comment]
The allocator has a number of tunable threshold knobs (i.e. the thresholds at which it considers the cluster to be balanced). We could make these knobs configurable on a per-allocation basis and then have SCATTER set much lower thresholds.

**Comment by a-robinson** [comment]
@RaduBerinde @benesch should I assume given the lack of follow-up that improving the lease scattering isn't needed for 1.1? How serious of an issue is it?

**Comment by RaduBerinde** [comment]
It's not critical for 1.1 but it would be nice to address in the future (hence the "Later" milestone).
