### ISSUE TITLE
reported database size discrepancy between load csv vs conventional  

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/cockroach#17355]
TPC-H SF=1 loaded with load csv command smaller than expected.
 
1.

cockroach version
Build Tag:    v1.1-alpha.20170720
Build Time:   2017/07/20 15:21:15
Distribution: CCL
Platform:     darwin amd64
Go Version:   go1.8.3
C Compiler:   4.2.1 Compatible Clang 3.8.0 (tags/RELEASE_380/final)
Build SHA-1:  a1af558e5859b668ee9823267bb27bb5929481b4
Build Type:   release

2. Please describe the issue you observed:

- What did you do?

load csv - see 02-tpch-create-sst.sh and 02-tpch-create-sst.log to create the backup set.

[Archive.zip](https://github.com/cockroachdb/cockroach/files/1191346/Archive.zip)

- What did you expect to see?

restore - see 03-tpch-load-sst.sh and 03-tpch-load-sst.log showing restore size to be over 1 GB

- What did you see instead?

The data is correctly loaded and content is correct; however, the database size reported by the UI admin does not reflect the true size.

<img width="1288" alt="screen shot 2017-08-01 at 11 59 57 am" src="https://user-images.githubusercontent.com/6315124/28837011-41fe644c-76b9-11e7-8fdd-bbe45e09015c.png">

**Comment by jordanlewis** [comment]
@robert-s-lee also noticed that running an `ALTER TABLE ADD COLUMN WITH DEFAULT` against this CSV-loaded dataset caused the following crash, which didn't reoccur with the original dataset or a direct `RESTORE`. This seems to indicate further that some data is missing.

```
I170801 13:32:52.782229 1086 sql/backfill.go:134  [client=[::1]:49582,user=root,n1] Running backfill for "lineitem", v=6, m=2
panic: Non-nullable column with no value!

goroutine 12725 [running]:
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*RowFetcher).finalizeRow(0xc44b036300)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/rowfetcher.go:573 +0x27e
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*RowFetcher).NextRow(0xc44b036300, 0x7916b80, 0xc420a9c700, 0xc44b092c00, 0x40137b8, 0x700, 0x55f07c0, 0x1, 0xc421df4300)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/rowfetcher.go:544 +0x13d
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*RowFetcher).NextRowDecoded(0xc44b036300, 0x7916b80, 0xc420a9c700, 0xc420224f00, 0x1, 0x1, 0x1, 0x1, 0xc8)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/rowfetcher.go:554 +0x4c
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*columnBackfiller).runChunk.func1(0x7916b80, 0xc420a9c700, 0xc44b038000, 0x0, 0x0)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/columnbackfiller.go:204 +0x8a6
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).Txn.func1(0x7916b80, 0xc420a9c700, 0xc44b038000, 0xc420292858, 0x54b9720, 0xc4202928a0)
    /go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:517 +0x43
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).Exec(0xc44b038000, 0x7916b80, 0xc420a9c700, 0xc420010101, 0xc4202928b0, 0xc42049ec00, 0x6b682c0)
    /go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:675 +0xb6
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).Txn(0xc42022df80, 0x7916b80, 0xc420a9c700, 0xc4213f00f0, 0x0, 0x0)
    /go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:518 +0x142
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*columnBackfiller).runChunk(0xc44b036000, 0x79168c0, 0xc457737950, 0xc420a9c6c0, 0x1, 0x1, 0xc42030d530, 0x9, 0x10, 0xc4211ba300, ...)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/columnbackfiller.go:241 +0x166
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*backfiller).mainLoop(0xc44b036000, 0x79168c0, 0xc457737950, 0x564a09a, 0x8)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/backfiller.go:129 +0x5d8
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*backfiller).Run(0xc44b036000, 0x79168c0, 0xc457737950, 0xc44ee1fe00)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/backfiller.go:82 +0x224
created by github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Start
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:332 +0x337
```

**Comment by benesch** [comment]
Punting this to @mjibson and @dt, since it's CSV related. :)

**Comment by mjibson** [comment]
I need the create table statements, and the specific ALTER TABLE statement that caused this. Can someone provide those? (I know I can get the TPCH create table statements in a variety of places, but I want the specific ones here because they may contain indexes and that could be affecting this.)

**Comment by robert-s-lee** [comment]
Attached is DDL used at AMEX

[tpch-ddl.sql.zip](https://github.com/cockroachdb/cockroach/files/1264802/tpch-ddl.sql.zip)

**Comment by mjibson** [comment]
I can't reproduce this, using your scripts on master (7d914b11163f69e56e1603df160419ad73d75ca1).

![ss](https://user-images.githubusercontent.com/41181/29896770-591656a8-8dac-11e7-9ca1-d04460b7df2e.png)

**Comment by mjibson** [comment]
We've fixed a lot of stuff since July 17, so I'll assume this was one of those. Can you close if you're ok with that?

**Comment by robert-s-lee** [comment]
Tried on 0819.  works correctly.  Thank you.
