### ISSUE TITLE
sql: build a user-facing UI around crdb_internal.node_statement_statistics (EXPLAIN?)

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#17353]
note: this differs from  #17549 in that this issue is about revealing the information via SQL, whereas  #17549 is about the admin UI / `cockroach zip` -- not the same work.

Discussed on Gitter:

> @jonbonazza: In the end as long as I can go somewhere to find help on that table (`crdb_internal.node_statement_statistics`) it would be useful. I have been using it a lot since Tobias showed it to me. We are doing an evaluation for using in our company and these statistics have been super useful.

The challenge is to find a proper balance between the following two constraints:
- user want (and we want to suggest users to use) a feature that details the phase times for single statements
- we do not want to publicly advertise (and commit to the stability of) `crdb_internal` tables.

The proper course of action is to design, implement and document a user-facing front-end for this data outside of the `crdb_internal` namespace. My initial idea would be to extend `EXPLAIN` in that direction, after all that's what other SQL databases do.

However until this is done we probably want to expose *some* documentation about that table for the benefit of users (with a disclaimer that the interface is subject to change without notice). Toby suggests an additional row in the table carrying help strings. 

Toby suggests that to ease troubleshooting and adoption we must do *something* about this issue in the 1.1 timeframe, and possibly polish the "good" solution only later in 1.2.

**Comment by knz** [comment]
Other concrete suggestion:

> @jonbonazza While we are discussing potential features, something else handy would be to show the query time in the CLI after each query. For instance, right now, it says "(x rows)" Would be nice if it also said "(took x seconds)" or w/e.

**Comment by cuongdo** [comment]
cc @dianasaur323

**Comment by dianasaur323** [comment]
Clarifying question - what does CRDB internal have that EXPLAIN does not?

**Comment by knz** [comment]
It knows about detailed measurements of how long a query was running, errors it encountered, how many rows it processed, etc.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by knz** [comment]
Also FYI 'crdb_internal.node_statement_statistics' is the name of a table containing details about all statements ran on the node. So it's also a privileged table.

it's uncommon/unconventional to present this information as a table whereas other SQL engines use a separate statement.

Also the fact it is privileged makes it cumbersome to use by developers who may not be DBAs.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dianasaur323** [comment]
And how long is this history stored? when crdb_internal.node_statement_statistics is accessed, can users see the entire history? I'm assuming this might be a problem as a table for security / access reasons. I agree with you in terms of looping this into EXPLAIN. Making that more user friendly is on the roadmap for 1.2. You think that might be too late?

**Comment by knz** [comment]
The history is stored for one hour, technically until the point it's sent to our registration server, then it's reset.

1.2 would be good. In 1.1 I already added a stop-gap feature which prints query latency in the CLI shell.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dianasaur323** [comment]
Great - I saw your query latency PR land! 👍 

Ok - we can do 1.2. Thanks!

**Comment by bdarnell** [comment]
> it's uncommon/unconventional to present this information as a table whereas other SQL engines use a separate statement.

FYI MySQL uses tables in the [`performance_schema` database](https://dev.mysql.com/doc/refman/5.7/en/performance-schema.html) for similar purposes.

**Comment by jordanlewis** [comment]
EXPLAIN ANALYZE has been built, I think this is subsumed by that work.
