### ISSUE TITLE
perf: verify utility of {Lock,Unlock}OSThread in WAL sync goroutine

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#17367]
The WAL sync goroutine contains this code:

```
func (r *RocksDB) syncLoop() {
	// Lock the OS thread to prevent other goroutines from running on it. We
	// don't want other goroutines to run on this thread because of the
	// relatively long (multiple millisecond) Cgo calls that are
	// performed. Scheduling other goroutines on this thread would introduce
	// latency to those goroutines whenever this goroutine needs to sync the WAL.
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
...
}
```

Need to verify the utility of the `LockOSThread` call by running a multi-node write scalability performance test. The use of `LockOSThread` here was a bit speculative, though I did have some test (which I've since lost) which demonstrated a benefit. Need to look at both throughput and latency.

**Comment by petermattis** [comment]
From [a comment](https://github.com/cockroachdb/cockroach/pull/17425#issuecomment-320040618) in #17425:

I'm not sure if the diff here is noise or if there is a very tiny benefit to LockOSThread. Certainly doesn't seem harmful to leave this in. NB: the blue lines are before this change and the red lines are with this change.

<img width="1261" alt="28935138-7d7296e4-7851-11e7-94a1-9b1d9b133894" src="https://user-images.githubusercontent.com/6201335/29036783-d83ad242-7b6e-11e7-932d-b25f18b1bd5a.png">

**Comment by a-robinson** [comment]
I'm fine with leaving this in, but shouldn't the default generally be to *not* use a generally discouraged language feature if it doesn't provide a noticeable benefit?

**Comment by petermattis** [comment]
I don't feel strongly either way, though where is `LockOSThread` generally discouraged?

**Comment by a-robinson** [comment]
Sorry, upon looking it up it seems "discouraged" is the wrong word. The docs just say that it's "notoriously difficult to use correctly" - https://github.com/golang/go/wiki/LockOSThread

**Comment by petermattis** [comment]
And yet we seem to be using `LockOSThread` correctly. Or, we're not using it so incorrectly that it causes noticeable problems.

I'm fine with removing. The simplification in cognitive complexity is probably worth it. @tschottdorf (or anyone else) care to weigh in?

**Comment by tschottdorf** [comment]
I'd probably remove it. The less clutter, the better.
