### ISSUE TITLE
perf: provide per-node performance self-test report

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#17369]
Provide a cluster performance self-test report that shows inter-node latencies, CPU capacity, disk throughput and disk latencies (reads, writes and syncs). This would have been useful during a recent forum debugging effort to highlight the usage of spinning disks and the resulting effect on disk syncs. 

Jira issue: CRDB-6040

**Comment by petermattis** [comment]
Some Azure VMs throttle disk writes in pretty horrible fashion. The performance self-test should detect this throttling.

**Comment by awoods187** [comment]
This will likely by ops/tools

**Comment by tschottdorf** [comment]
On the face of it, we should be able to use `cli/synctest` for a part of this.
