### ISSUE TITLE
perf: reduce LeaseHolderCache memory usage

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#17388]
#17202 was a non-starter because the `UnorderedCache` used internally by `LeaseHolderCache` updates an LRU list on every access. `LeaseHolderCache` is accessed on every RPC putting it in the critical path. Rather than a single `UnorderedCache`, we could shard `LeaseHolderCache` based on the range ID, providing a lock per shard. This would be relatively straightforward.

While we're mucking in this code, we might want to trim down the data stored by `LeaseHolderCache`. Currently it caches a `ReplicaDescriptor`, but only `ReplicaDescriptor.StoreID` is needed.

**Comment by a6802739** [comment]
@petermattis , could I have a see on it?

**Comment by petermattis** [comment]
Go for it. Be sure to add a benchmark showing the improvement (or lack of improvement) for concurrent access. See `rpc.BenchmarkRPCDial` for inspiration.

**Comment by a6802739** [comment]
@petermattis  So we should change `LeaseHolderCache` just like:
```
// A LeaseHolderCache is a cache of replica descriptors keyed by range ID.
type LeaseHolderCaches struct {
	lu    syncutil.Mutex
        caches map[int] LeaseHolderCache
}
```
And shard caches based on on the range ID? 

If the  above is true, what exactly the modulo value should we use? maybe 16?

**Comment by petermattis** [comment]
I think it would actually look like:

```
const leaseHolderCacheShards = 64 // or 128 or 256

type LeaseHolderCache struct {
  shards [leaseHolderCacheShards]LeaseHolderCacheShard
}
```

There is no need for a mutex in this structure as the mapping to shard is deterministic. Using an array is faster than a map. `LeaseHolderCacheShard` would be the same as the existing `LeaseHolderCache` and the new `LeaseHolderCache` structure would have the same interface, forwarding to the appropriate shard.

**Comment by a6802739** [comment]
@petermattis  Thank you very much. And about the benchmark, where is the `rpc.BenchmarkRPCDial`?

**Comment by petermattis** [comment]
@a6802739 https://github.com/cockroachdb/cockroach/blob/master/pkg/rpc/context_test.go#L710

**Comment by a6802739** [comment]
Sorry, this issue is not be fixed completely. we should still try to  trim down the data stored by `LeaseHolderCache`.

**Comment by petermattis** [comment]
Fixing `TestDistSQLReceiverUpdatesCaches` to check something other than the `ReplicaID` seems reasonable. Fixing `spanResolverIterator.ReplicaInfo` is more involved. `StoreIDs` are globally unique so we could have gossip maintain a map from `StoreID` to `NodeID`. 

I'm going to re-title this issue to reflect the remaining work, but I don't think this work is particularly urgent.
