### ISSUE TITLE
Multi-node testing: after killing first node, other nodes has been trying to reconnect to gossip

### ISSUE THREAD

**Issue by zimulala** [cockroachdb/cockroach#1738]
steps to reproduce:
0. init db0, db1, db2
1. start three servers
./cockroach start --stores=ssd="./db0" --addr=":8080" --gossip=":8080"
./cockroach start --stores=ssd="./db1" --addr=":8081" --gossip=":8080"
./cockroach start --stores=ssd="./db2" --addr=":8082" --gossip=":8080"
2. kill the first server that address is 8080
result：
other servers reported errors：
rpc/client.go:119 client localhost:8080 failed to connect: dial tcp 127.0.0.1:8080: connection refused

My operation is a problem?
Can you tell me what's the problem?

**Comment by zimulala** [comment]
If I don't kill the first server, kill the second, only the first server reported errors:
rpc/client.go:119 client localhost:8081 failed to connect: dial tcp 127.0.0.1:8081: connection refused
Then it blocked operations like "./cockroach kv scan"

**Comment by tschottdorf** [comment]
This looks like expected behavior. You're killing one of the servers, but the others will still try to connect to it (so that if you restart, the node catches up and becomes a full member again). Hence you're seeing errors from those operations. If any other issues arise (for instance, if the cluster becomes unresponsive) please reopen this ticket and report. Ideally you provide full logs in this case.
Thanks,
Tobias

**Comment by tschottdorf** [comment]
Sorry, did not see your second message. With a cluster of three, you should be able to kill the second server and the client should continue working (**unless** you're using it to talk to the second server, of course). Do you have a log file/shell session example?

**Comment by zimulala** [comment]
about the first problem, why you think this is expected? the distributed system shouldn't be down a server, others can continue to provide service? 
about the second, I means I used the local command line operation about: "./cockroach kv scan". And I also tried to open db used url about: "https://root@localhost:8080", then do a put operation. But both two all blocked.

**Comment by zimulala** [comment]
Gotcha
