### ISSUE TITLE
sql: CREATE VIEW or FKs over system tables do not set the system config trigger

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#17405]
Both CREATE TABLE and CREATE VIEW can modify descriptors of other tables/views than the one being created, to update either their depended-on list (for CREATE VIEW) or their index list (for CREATE TABLE with FKs).

When creating a view over a system table, or creating a new index on a system table for a FK from a non-system table, *a system descriptor is updated*.

In order to ensure that the update is propagated the KV transaction should be anchored on the system range (using `SetSystemConfigTrigger`), or cause an error if the anchor is already set.

This is not currently done / checked properly. This causes possible inconsistent state of the system descriptors across the cluster.

Found while working on #17310.

**Comment by knz** [comment]
cc @cockroachdb/sql-async 
Also @andreimatei

**Comment by knz** [comment]
@vivekmenezes for triage

**Comment by vivekmenezes** [comment]
Can you point to the transactions where SetSystemConfigTrigger() should be called?

**Comment by knz** [comment]
It's the `*client.Txn` carried by `planner.txn`.

**Comment by vivekmenezes** [comment]
I'd be grateful if you can add in the exact CREATE statements that are causing this problem, and what is observed. If the update is not gossiped a old lease on a table will be used, resulting in delayed execution of a schema change. I'm not sure what you mean by inconsistent state of descriptors? Thanks!

**Comment by knz** [comment]
I found this problem in a test but I cannot reproduce it on the SQL shell. In the SQL shell I observe (as I expect) an error due to the txn anchor already being set. I can't provide an exact repro so I will simply close this for the time being.
