### ISSUE TITLE
DistSQL runs on one node when running count(*) on 150k row table

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/cockroach#17432]
NODE 1
I170803 20:51:31.732120 1 util/log/clog.go:975  [config] file created at: 2017/08/03 20:51:31
I170803 20:51:31.732120 1 util/log/clog.go:975  [config] running on machine: ubuntu-512mb-sfo1-01
I170803 20:51:31.732120 1 util/log/clog.go:975  [config] binary: CockroachDB CCL 8e4b34a (linux amd64, built 2017/08/03 16:48:03, go1.8.3)
I170803 20:51:31.732120 1 util/log/clog.go:975  [config] arguments: [/usr/local/bin/cockroach start --insecure --advertise-host=10.134.8.165 --join=10.134.9.162]

NODE 2
I170803 20:53:50.138391 1 util/log/clog.go:975  [config] file created at: 2017/08/03 20:53:50
I170803 20:53:50.138391 1 util/log/clog.go:975  [config] running on machine: ubuntu-512mb-sfo1-02
I170803 20:53:50.138391 1 util/log/clog.go:975  [config] binary: CockroachDB CCL 8e4b34a (linux amd64, built 2017/08/03 16:48:03, go1.8.3)
I170803 20:53:50.138391 1 util/log/clog.go:975  [config] arguments: [cockroach start --insecure --join=10.134.8.165 --advertise-host=10.134.9.162]

NODE 3
I170803 20:55:35.508466 1 util/log/clog.go:975  [config] file created at: 2017/08/03 20:55:35
I170803 20:55:35.508466 1 util/log/clog.go:975  [config] running on machine: ubuntu-512mb-sfo1-03
I170803 20:55:35.508466 1 util/log/clog.go:975  [config] binary: CockroachDB CCL 8e4b34a (linux amd64, built 2017/08/03 16:48:03, go1.8.3)
I170803 20:55:35.508466 1 util/log/clog.go:975  [config] arguments: [/usr/local/bin/cockroach start --insecure --join=10.134.8.165 --advertise-host=10.134.4.235]

Please describe the issue you observed:

- What did you do? 
loaded tpch data into a 3 node cluster. 
EXPLAIN(DISTSQL) SELECT count(*) FROM customer; (150k rows)
EXPLAIN(DISTSQL) SELECT count(*) FROM lineitems; (6M rows)

- What did you expect to see? 
I expected to see a query plan that spanned multiple nodes in both cases.

- What did you see instead?
The query plan for the customer table did not span nodes.

![image](https://user-images.githubusercontent.com/894257/28945142-3bea3098-7873-11e7-921d-2d9165963747.png)

Additionally, in both cases the lease holder was node 1 across all ranges
![image](https://user-images.githubusercontent.com/894257/28945162-578d63d8-7873-11e7-849b-c629d62306e1.png)
![image](https://user-images.githubusercontent.com/894257/28945164-5dff2058-7873-11e7-8dba-26ff3f9ef200.png)

after running alter table scatter the nodes rebalanced, but the query for customer still didnt span nodes.

**Comment by nstewart** [comment]
cc @RaduBerinde

**Comment by RaduBerinde** [comment]
There are two problems here:
 - all ranges in these tables have lease holders on node 1. I don't think this is expected after a restore? CC @danhhz 

In any case, running SCATTER spread them around:
![image](https://user-images.githubusercontent.com/16544120/28945572-16787c82-7875-11e7-87eb-f57fbbc407d2.png)
Given the discussion in #17341, scatter only moves things around if it knows there is an imbalance. So this suggests that the system was aware that it needs to rebalance things, it just didn't get around to doing it yet (?) CC @benesch @a-robinson 

 - after scattering the customers table, we have the two ranges on different nodes:
![image](https://user-images.githubusercontent.com/16544120/28945475-a7a01680-7874-11e7-82ed-50d7f5e39fb3.png)
But a `COUNT(*)` query is still not being distributed:
![image](https://user-images.githubusercontent.com/16544120/28945491-b97ea45c-7874-11e7-91e9-f1d484d2d003.png)
This was the case even after running the query a few times - which should have triggered updates to the range caches @andreimatei

**Comment by andreimatei** [comment]
I'll take a look at the cache invalidation part :S

**Comment by a-robinson** [comment]
> Given the discussion in #17341, scatter only moves things around if it knows there is an imbalance. So this suggests that the system was aware that it needs to rebalance things, it just didn't get around to doing it yet

Most likely, if I understand you correctly that the leases were imbalanced before the scatter but more balanced afterwards. I'd be surprised if the leases stayed imbalanced for more than 10 minutes or so, though. Had they been skewed toward node 1 for longer than that?

**Comment by RaduBerinde** [comment]
> that the leases were imbalanced before the scatter but more balanced afterwards

Right, see the [image](https://user-images.githubusercontent.com/894257/28945164-5dff2058-7873-11e7-8dba-26ff3f9ef200.png) in the description vs the [image](https://user-images.githubusercontent.com/16544120/28945572-16787c82-7875-11e7-87eb-f57fbbc407d2.png) in my comment.

**Comment by nstewart** [comment]
> I'd be surprised if the leases stayed imbalanced for more than 10 minutes or so, though. Had they been skewed toward node 1 for longer than that?

I loaded the tpch data via distributed restore ~20 hours earlier.

**Comment by RaduBerinde** [comment]
I investigated the COUNT planning issue. I think that the testing_ranges output is misleading:

![image](https://user-images.githubusercontent.com/16544120/28945475-a7a01680-7874-11e7-82ed-50d7f5e39fb3.png)

I am not sure what the empty key is about but I believe that the table really only has a single range of interest, not two. So the query would never be distributed for this table. I'll investigate more what the deal is with testing_relocate output.

**Comment by andreimatei** [comment]
Seems that the issue remaining here is that the leaseholder are not scattered after a restore. Assigning to... Dan.

**Comment by danhhz** [comment]
Pretty sure whatever was happening with scatter during restore has long since been fixed. Assigning to @mjibson for confirmation

**Comment by vivekmenezes** [comment]
@mjibson please close this issue if there is nothing more to be done. Thanks!

**Comment by vivekmenezes** [comment]
I'm actually gonna go ahead and close this.
