### ISSUE TITLE
ui: match event log widget to drop down toggle settings

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#17430]
From Nate: The admin UI defaults to cluster level events, but when I switch to the node filter in the top level nav the events are still cluster level rather than node level. I would expect those to honor the top level filter given our current information architecture. I think the summary widget may have the same problem.

Will need @josueeee to help out here to figure out what design makes the most sense.

cc @nstewart

**Comment by couchand** [comment]
The events in the log have a field `ReportingID` which specifies which node reported the event, which we could conceivably use for this filter.

However, it's not clear that all or even most event types are relevant here: should database or table events only show up on the node that the DDL executed on?  That seems a bit surprising.

I think this will require a bit more specification before we'd be able to take it on, so I'm moving it out of this milestone.

**Comment by jordanlewis** [comment]
Closing due to age.
