### ISSUE TITLE
Cannot start insecure node on windows

### ISSUE THREAD

**Issue by JackHerring** [cockroachdb/cockroach#17442]
When starting an insecure node on windows 10 64bit I am getting the following error:

`Not implemented: SyncWAL() is not supported for this implementation of WAL file`

**Comment by petermattis** [comment]
@tamir and/or @BramGruneir I'm not sure if this is an oversight or intentional in RocksDB. `WinWritableFile` does not implement `IsSyncThreadSafe` and thus gets the default of `false`. From my brief perusal of the implementation, it seems like it is thread safe.

**Comment by tschottdorf** [comment]
Does this also mean that our CI never actually starts a windows server nor runs any tests that use an on-disk instance of RocksDB?

**Comment by tamird** [comment]
We have no Windows CI.

On Fri, Aug 4, 2017 at 12:28 PM, Tobias Schottdorf <notifications@github.com

**Comment by benesch** [comment]
We kind of do. https://github.com/benesch/bincheck

**Comment by benesch** [comment]
Hmm, I suppose bincheck shouldn't use in-memory stores.

**Comment by benesch** [comment]
FWIW, this isn't caught by RocksDB's Windows CI because they don't run the `db_wal_test` on Appveyor: https://github.com/facebook/rocksdb/blob/627c9f1abb263ab8d2072a1ac9d30a6e4bc3dde4/appveyor.yml#L14.

**Comment by benesch** [comment]
Sorry for the quadruple-post, but I just discovered a comment in the source that suggests `WinWritableFile` is not always thread safe: https://github.com/facebook/rocksdb/blob/72502cf2270db7323d447cc7a504dbea251d432a/db/column_family_test.cc#L3132-L3133.

**Comment by benesch** [comment]
@petermattis, thoughts on working around this by having the sync loop issue an empty write with `write_options.sync = true` on Windows instead of calling `SyncWAL`? (I haven't actually verified that this fixes the problem.)

**Comment by petermattis** [comment]
@benesch That seems like a reasonable workaround to me. Care to implement it?

**Comment by fire** [comment]
This is blocking me from using a recent version of cockroachdb alpha on Windows. Currently testing using a July version.

My uses require a uuid data type so that's why I'm on the alpha version.

**Comment by petermattis** [comment]
@fire For development purposes, you can disable the WAL sync:

```
set cluster setting kv.raft_log.synchronize = false
```

**Comment by fire** [comment]
How do you enter the sql client if you can't do:

.\cockroach.exe start --insecure

**Comment by BramGruneir** [comment]
@JackHerring, @fire 
This fix was too late for our next alpha release, but it will be in, in the one after that.
You can also compile from source or I can provide a build if needed to unblock you right now if needed.

**Comment by JackHerring** [comment]
@BramGruneir Perfect, we can wait for the next release - thank you.
