### ISSUE TITLE
storage: local 4-node cluster not rebalancing to 4th node

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#17456]
Build: 824b97524
OS: macOS 10.12.6

1. Start local 4-node cluster:

```
cockroach start --insecure --port=26257 --http-port=8080 --store cockroach-data/1 --cache=512MiB --background
cockroach start --insecure --port=26258 --http-port=8081 --store cockroach-data/2 --cache=512MiB --join=localhost:26257 --background
cockroach start --insecure --port=26259 --http-port=8082 --store cockroach-data/3 --cache=512MiB --join=localhost:26257 --background
cockroach start --insecure --port=26260 --http-port=8083 --store cockroach-data/4 --cache=512MiB --join=localhost:26257 --background
```

2. Look at [admin UI's node list](http://localhost:8080/#/cluster/nodes)

Here's a screenshot from mine:

<img width="1257" alt="screenshot 2017-08-04 16 38 51" src="https://user-images.githubusercontent.com/1564582/28986050-6f9ba960-7933-11e7-9082-bb20102e6f66.png">

(Notice that though node 4 has been up for 8 minutes, it has 0 replicas.)

I originally reproduced this with the 3 to 5 small allocator nightly test.

Here are the logs for the node that with no replicas:

[cockroach-4.txt](https://github.com/cockroachdb/cockroach/files/1201575/cockroach-4.txt)

I don't notice anything odd in the logs except:

```
W170804 16:31:27.693125 36 sql/jobs/registry.go:165  [n4] unable to get node liveness: node not in the liveness table
W170804 16:31:27.693131 36 sql/jobs/registry.go:290  [n4] canceling all jobs due to liveness failure
```

and some instances of:

```
I170804 16:33:39.721187 445 vendor/google.golang.org/grpc/grpclog/grpclog.go:60  Client received GoAway with http2.ErrCodeEnhanceYourCalm.
I170804 16:33:39.721199 445 vendor/google.golang.org/grpc/grpclog/grpclog.go:60  transport: http2Client.notifyError got notified that the client transport was broken EOF.
I170804 16:33:39.721200 335 vendor/google.golang.org/grpc/grpclog/grpclog.go:75  transport: http2Server.HandleStreams failed to read frame: read tcp [fe80::88:606b:eb3:c5ff%en0]:26260->[fe80::88:606b:eb3:c5ff%en0]:53215: use of closed network connection
```

**Comment by cuongdo** [comment]
`git bisect` shows that d22e91772b6beba7de5206fff74d050bb7072029 (usage- and write-based rebalancing) changed this behavior

**Comment by tamird** [comment]
Possibly also causing TestRebalance_3To5Small to fail:
```
allocator_test.go:203: 8m15s746ms873��s elapsed without changes, but replica count standard deviation is 133.25 (>14.00)
```

https://teamcity.cockroachdb.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=316667

**Comment by cuongdo** [comment]
Yes, I ran `TestRebalance_3To5Small` manually, and it stalls very early on with the first 3 nodes having the vast majority of replicas and the 4th and 5th nodes having close to none.

**Comment by a-robinson** [comment]
For what it's worth, I've been having trouble reproducing this. I've tried both a more recent head (87d179cd66d906436265ae534544163a05e5319e) and the original commit you mentioned (824b97524a196e24e3d5def151d6c6532f57ac3d), and I've tried varying the timing of how I bring up the nodes (e.g. to leave a gap between nodes 1-3 and node 4). After 10+ attempts node 4 has always been rebalanced to well within 30 seconds of being brought up. I guess I'll try using the acceptance test instead.

Unfortunately, the acceptance test that @tamird linked appears to have suffered from a test infrastructure problem so we don't have any logs from it:

```
[02:32:41]Publishing artifacts
[02:32:41][Publishing artifacts] Collecting files to publish: [/home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts]
[02:32:41][Publishing artifacts] Artifacts path 'artifacts' not found
```

That's been happening for the 3-to-5 test each of the last few nights, even though the artifacts have been getting successfully published for the 1-to-3 tests. I'm not sure what's going on there.

**Comment by cuongdo** [comment]
I can still repro with a build using the latest `master` code, on both my home Mac and my `azworker`. It happens consistently if I run `sleep 10` before starting the 4th node.

Would you like me to keep my `azworker` up so you can poke around?

**Comment by a-robinson** [comment]
Alright, I'm able to reproduce it. The question is whether you consider this a sufficient result:

<img width="1309" alt="screen shot 2017-08-11 at 4 04 00 pm" src="https://user-images.githubusercontent.com/7085343/29229947-db7cc904-7eae-11e7-9af3-964be95f6c34.png">

That's what I get when running with #17593. The reason it doesn't rebalance them until they're perfectly even is to avoid thrashing - we consider being within 5% of the mean or 5 replicas of the mean to be acceptable. Adding the "or 5 replicas" was important for avoiding thrashing in small clusters (because otherwise 5% of the mean is less than one replica). While it makes this balance look somewhat silly, I don't know that it's important to do much better for such small clusters. What do you think?

**Comment by cuongdo** [comment]
I think that this is much better than having 0 replicas on a node, which makes it look like something's wrong with that node. Further balancing is probably not necessary unless we get user feedback saying that this is a problem.
