### ISSUE TITLE
v1.1-alpha.20170803 on 3 nodes does not complete TPC-H SF1 restore

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/cockroach#17452]
bug

**BUG REPORT**

$ cockroach version
Build Tag:    v1.1-alpha.20170803
Build Time:   2017/08/03 17:19:14
Distribution: CCL
Platform:     darwin amd64
Go Version:   go1.8.3
C Compiler:   4.2.1 Compatible Clang 3.8.0 (tags/RELEASE_380/final)
Build SHA-1:  1e88c32588fd3d7cad826437c18b349fd70e4762
Build Type:   release

2. Please describe the issue you observed:

- What did you do?

started 3 node cluster

$ roachdemo -n 3
2017/08/04 15:18:28 process 1884 started: cockroach start --insecure --port=26257 --http-port=26258 --store=cockroach-data/1 --cache=256MiB
2017/08/04 15:18:28 process 1885 started: cockroach start --insecure --port=26259 --http-port=26260 --store=cockroach-data/2 --cache=256MiB --join=localhost:26257
2017/08/04 15:18:28 process 1886 started: cockroach start --insecure --port=26261 --http-port=26262 --store=cockroach-data/3 --cache=256MiB --join=localhost:26257
2017/08/04 15:18:28 serving: http://localhost:9999

ran restore commands
create database tpch;
restore tpch.* FROM  'nodelocal:/Users/rslee/data/backup/tpch';
set database=tpch;
show tables;

- What did you expect to see?

restore to complete in about a minute

- What did you see instead?

waited over 10 minutes.  the restore does not complete.  show jobs does not show progress.  4 nodes cluster does complete the restore.
[debug.zip](https://github.com/cockroachdb/cockroach/files/1201441/debug.zip)

**Comment by dianasaur323** [comment]
@danhhz mind triaging?

**Comment by danhhz** [comment]
@benesch do we think this got fixed?

**Comment by benesch** [comment]
Kind of. @nstewart ran another TPCH1 restore which completed... but took 9 hours. We need to start doing our own geo-distributed testing.

**Comment by dianasaur323** [comment]
I just added a little note on testing Backup / Restore that also covers geo-distributed clusters in Airtable. As we push harder as a company on the multi-datacenter intra-continent and inter-continent story, we need to make sure backup / restore can meet those setups. I'll create actual GitHub issues for relevant roadmap items with acceptance criteria, so I'll ping y'all when I get to doing that. Probably sometime next week.

**Comment by danhhz** [comment]
@benesch this was not geo-distributed. all nodes were on one machine

**Comment by benesch** [comment]
Oh sorry, I meant to post on #17522. Copying my post there. This one should be fixed, but I'll verify now.

**Comment by benesch** [comment]
Yup, this now works for me. Marking as fixed.
