### ISSUE TITLE
acceptance: run straight on the host machine, without docker

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#17464]
This will be a lot faster, likely less flaky and allows us to also test non-linux.

I tentatively plan to look into this in the next month.

**Comment by tschottdorf** [comment]
As of https://github.com/cockroachdb/cockroach/pull/17686, we do this for a few tests.

Open TODOs:

- [ ]: add support for InitModes and then run the Init tests against a LocalCluster instead of with Docker
- [ ]: add certs

**Comment by petermattis** [comment]
@tschottdorf Is there anything else you plan to do here?

**Comment by tschottdorf** [comment]
No, thanks for the ping.
