### ISSUE TITLE
sql: check backup/restore of views defined over system descriptors?

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#17476]
This is a question / request for information about the current situation, in order to guide the work on #15388 / #17475.

1) what currently happens when backing up a view which is defined over a system descriptor? (e.g. `create view s as select id from system.descriptor`) What would be the desired result?

2) what happens when restoring a view defined over a system descriptor? Is the dependency list updated properly?

I have already parts of a solution to make view descriptors over system tables "just work" *if they don't currently*, however if you think it shouldn't be supported and/or the current handling is fine and/or you already have other plans, I'd like to hear that ASAP.

Depending on the outcome of the discussion we may also trigger some docs updates.

cc @danhhz @mjibson

**Comment by knz** [comment]
Discussed with Dan:
1. backing up a view descriptor is always possible
2. currently, restoring a view fails if it depends on a table that's not also restored
3. so backing up view descriptors over system tables is possible but (usually) they can't be restored.

**Comment by knz** [comment]
I'll move forward with #15388 / #17475 and update/close this issue when I'm confident about the behavior.

**Comment by dt** [comment]
I don't think there is anything special to do with views that reference system tables as described here. There is a general case of views referencing tables that are not restored, including those not even in the backup, and system tables aren't special. We're providing some workarounds here (@lucy-zhang landed #38597 and our next new-hire will be augmenting `SHOW BACKUP` to print the `CREATE` statements for the tables _and views_ in the BACKUP to make recreating them easier) so I think we can close this particular issue.
