### ISSUE TITLE
storage: Diversity scores not working as intended in allocator

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#17479]
Diversity scores aren't working well for properly spreading replicas around different localities in indigo. All the nodes are well-balanced across all dimensions, but close to half of all ranges have two replicas in the same locality (and one locality without a replica). This looks like it was broken even before #16878, but it's probably a bit worse now because ad9e5523f2ab54075bbc7861390eabc22765cd22 separated out the converge score from the constraint score, so there's no chance for the possibility of convergence to help us do the right thing anymore.

There are two problems here, one really easy to fix and one I still need to think about a little more.

1. When considering a rebalance, we use one diversity score method for existing replicas and a different one for other replicas. We consider an existing replica to have good diversity if we can remove it and the range will still be diverse, but we only consider a new replica diverse if it doesn't overlap with any existing replica's locality. That means that we never choose to rebalance from one node in a locality to another node in the same locality. This is easy to fix.
1. `diversityRemovalScore` doesn't seem to do what we want. It returns the max diversity of any remaining pair of replicas in a range. That means that if a range has 6 replicas (say it's down-replicating from 6 to 5) in localities [a, b, c, c, c, c] respectively, it'll consider all replicas to be equally valid for removal because no matter which one is removed, there will still be a pair of replicas with no locality tiers in common. To a human, this seems like an obviously bad choice. We may want to do something like average locality remaining after removing a replica to ensure that in cases like this we'd pick one of the replicas in locality c to remove.

Or maybe it's just fundamentally a bad idea to prioritize diversity over all other aspects of balance. If one locality has significantly more capacity than another, perhaps it would be better to keep all the replicas in `c` and remove one of the ones in `a` or `b`. I don't think that's going to be the case in most deployments, though.

**Comment by a-robinson** [comment]
Part 1 is done. Part 2 is too big/risky of a change to fit in for 1.1 Moving to the 1.2 milestone.

**Comment by a6802739** [comment]
@a-robinson，could I have a try for this?

**Comment by a-robinson** [comment]
Certainly! Once you've thought through an approach, it may be worth writing down and sharing before making the code changes, since it's worth thinking this one through a bit.

**Comment by a6802739** [comment]
> When considering a rebalance, we use one diversity score method for existing replicas and a different one for other replicas. We consider an existing replica to have good diversity if we can remove it and the range will still be diverse, but we only consider a new replica diverse if it doesn't overlap with any existing replica's locality. That means that we never choose to rebalance from one node in a locality to another node in the same locality. This is easy to fix.

@a-robinson, Sorry, I couldn't quite understand why we couldn't `rebalance from one node in a locality to another node in the same locality`?

> diversityRemovalScore doesn't seem to do what we want. It returns the max diversity of any remaining pair of replicas in a range. That means that if a range has 6 replicas (say it's down-replicating from 6 to 5) in localities [a, b, c, c, c, c] respectively, it'll consider all replicas to be equally valid for removal because no matter which one is removed, there will still be a pair of replicas with no locality tiers in common. To a human, this seems like an obviously bad choice. We may want to do something like average locality remaining after removing a replica to ensure that in cases like this we'd pick one of the replicas in locality c to remove

Sorry, I just couldn't understand why `That means that if a range has 6 replicas (say it's down-replicating from 6 to 5) in localities [a, b, c, c, c, c] respectively, it'll consider all replicas to be equally valid for removal`, obviously, we have 4 replicas in locality c, if we remove one of these 4 replicas, we still have 3 replicas in the same locality.

**Comment by a6802739** [comment]
@a-robinson, For your specified case `6 replicas (say it's down-replicating from 6 to 5) in localities [a, b, c, c, c, c] respectively`, for replica `a` or `b`, I think it's `diversityRemovalScore` will be greater than zero, for replica `c`, it's `diversityRemovalScore` will be zero, right? So what do you mean `it'll consider all replicas to be equally valid for removal`?

And about the `average locality`, do you mean we should consider about the replicas's whole diversity locality if we remove one replica.
in the case [a, b, c, c, c, c], for example:
1. if we remove a, the whole diversity score will be `b<->c`, `b<->c`... `c<->c`
2. if we remove b, the  whole diversity score will be `a<->c`, `a<->c` ... `c<->c`
3. if we remove c,  the  whole diversity score will be `a<->b`, `a<->c`... `b<->c`...`c<->c`

For `average locality`, we could just use `the whole diversity score` divide the number of replicas.

I don't know if it's appropriate, hope get some reference from you.

Thank you very much.

**Comment by a-robinson** [comment]
> @a-robinson, Sorry, I couldn't quite understand why we couldn't rebalance from one node in a locality to another node in the same locality? We will have two replicas in the same locality after the rebalance, but I think we still could remove one of them after the rebalance, right?

This first point was referring to how the code worked before https://github.com/a-robinson/cockroach/commit/587e3e92801b89e617fd694465196b25d8969a82. It's not true anymore, since we now use the new `rebalanceToDiversityScore` instead of `diversityScore` when calculating diversity scores for rebalancing.

> Sorry, I just couldn't understand why `That means that if a range has 6 replicas (say it's down-replicating from 6 to 5) in localities [a, b, c, c, c, c] respectively, it'll consider all replicas to be equally valid for removal`, obviously, we have 4 replicas in locality c, if we remove one of these 4 replicas, we still have 3 replicas in the same locality.

I was saying that `diversityRemovalScore` isn't very good if it thinks that removing the replica from `a` is just as good as removing a replica from `c` in that configuration, which was the case at the time. https://github.com/a-robinson/cockroach/commit/587e3e92801b89e617fd694465196b25d8969a82 alleviated the worst of the problem, and perhaps could have closed this issue.

However, what you described in your most recent comment is exactly what I was thinking we'd want to do, and would indeed be an improvement over what we currently do. Implementing that change (along with corresponding tests of course) would be great!
