### ISSUE TITLE
sql: fix PREPARE statement use of schema

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#17480]
Looking at the code I'm seeing any place where a particular prepare statement is associated with a particular version of the schema. prepare statement execution should happen like this:
1. PREPARE: parse/plan statement and attach version of schema used in statement preparation.
2. Execution: Acquire table descriptors used in the statement preparation. If the versions are the same move along as usual. If the versions are different repeat step 1 and 2.

**Comment by vivekmenezes** [comment]
@knz @jordanlewis heads up

**Comment by knz** [comment]
Two things:

1) pg actually doesn't guarantee the same descriptors are used between prepare and execute. Actually the behavior in pg rather specifically mandates *not* preserving the descriptors between PREPARE and EXECUTE:

```sql
CREATE TABLE foo(x INT); INSERT INTO foo VALUES(42);
PREPARE a AS SELECT * FROM foo;
ALTER TABLE foo RENAME TO bar;
CREATE TABLE foo(x INT); INSERT INTO foo VALUES(69);
EXECUTE a; -- shows 69, not 42
```

The only thing that pg checks (and that CockroachdB currently checks too) is that the result column names and types do not change between prepare and execute.

2) the concern you are raising here will need to be taken into account when we start caching query plans (which we currently do not do). When we cache plans, the cache must be invalidated if any of the descriptors used in the cached plan has changed between prepare and execute. That's a known concern, although it's good to have a tracking issue for this. I'll link this Github issue on the Airtable item for plan caching.

**Comment by vivekmenezes** [comment]
The example above proves that the execution of a statement is performed on an updated descriptor in pg.

https://github.com/cockroachdb/cockroach/issues/16062
is the closed issue that tracked the particular case of ensuring that result column names and types match correctly. While the tests for that fix make sense we should reconsider the fix once we fix this  issue which addresses a more general problem.

Care must be taken to not hold on to a table descriptor lease for a PREPARE statement. The execution path can use ```getTableVersionByID``` to execute the statement and check the versions.

**Comment by vivekmenezes** [comment]
No we don't since we do not associate a PREPARE statement with a descriptor. I was just documenting it for the person who creates such as association and fixes this issue.

**Comment by jordanlewis** [comment]
I think this is done via the plan caching work, isn't it? cc @andy-kimball

**Comment by awoods187** [comment]
ping on this @RaduBerinde or @andy-kimball

**Comment by RaduBerinde** [comment]
Yes, when an opt plan (memo) is cached, the data sources are re-resolved on each execution, and if any of the descriptor IDs or versions differ, the plan is rebuilt from scratch.

**Comment by vivekmenezes** [comment]
@RaduBerinde can you point me to this code. I actually need to use it somewhere else :-)

**Comment by RaduBerinde** [comment]
The main logic is in Memo.IsStale. It calls CheckDependencies which reresolves the sources and calls Equals which compares descriptor versions (implementation of the catalog is in sql/opt_catalog.go).
