### ISSUE TITLE
sql,bulk: clarify/restrict the transactional behavior of RESTORE (and possibly IMPORT)

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#17498]
Currently RESTORE (and upcoming IMPORT) do not respect the current open SQL transaction, if any. For example the descriptors created during the bulk import are immediately public even if the SQL transaction subsequently aborts. Similarly the Go trace info in the Context struct doesn't bind cleanly to RESTORE/IMPORT. Also the search path in the SQL session is not respected.

The root cause of these various issues is that the bulk I/O statements are not really regular SQL statements, and are currently mistakenly allowed as such, allowed to be interleaved inside explicit SQL txn blocks, and inconsistently following the session variables.

The result of this problem is that a user who, out of curiosity, issues `BEGIN; RESTORE; ROLLBACK` (or `COMMIT`), will be rather surprised (and probably disappointed) by the effects. Especially if the BEGIN..ROLLBACK / BEGIN..COMMIT block contains other schema change statements.

The solution to this is a three-pronged approach:
- restrict in Executor in which context non-transactional bulk I/O statements can be used, and reject uses between BEGIN and COMMIT with an explanatory error message
- review in which way the bulk I/O statements can be made compatible with session variables (in particular the current database and the search path). If complete compatibility is not possible, then find a way to instead disable any influence of the session variables on bulk I/O, so as to reduce the amount of surprise.
- document clearly (in docs) what users are to expect about the transactional aspects of bulk I/O statements and how they interact with regular SQL sessions and transactions.

**Comment by dianasaur323** [comment]
@knz Is this on your plate of things to fix? We haven't allocated time for this in the bulk io team. What are your proposed next steps?

**Comment by knz** [comment]
I think we must change the product to disallow using `RESTORE`, `BACKUP` and `IMPORT` inside a `begin`..`commit` block. @danhhz what do you think?

**Comment by danhhz** [comment]
cc @mjibson and @dt, who have taken over the day-to-day of BACKUP/RESTORE/IMPORT

**Comment by dt** [comment]
@knz where is the session db not being used?

**Comment by knz** [comment]
AFAIK the session db is used but the session path not, unless that has changed?

**Comment by dt** [comment]
ah, yeah, that's right. Ideally we should probably move `descriptorsMatchingTargets()` to sqlbase (or even to `parser`  if we switched it to not operate on `sqlbase.Descriptor`s directly?) so it could share more logic with the regular sql resolution stuff.

**Comment by knz** [comment]
Agreed.

Do you also agree on refusing the ccl statements when there's a txn active?

**Comment by dt** [comment]
@knz yeah, they're not transactional -- they spin up their own txn's internally because they'd time out otherwise -- so it doesn't make any sense to let them run in a txn. That said, some client libs might wrap everything in a txn whether the user expects transactional semantics or not, and the restriction may trip those up, but I'm sure there are workarounds.

**Comment by dianasaur323** [comment]
@dt do you think we'll get to this? if not, i think it may be time for us to start moving milestones?

**Comment by knz** [comment]
@dianasaur323 David fixes this in  #21488.

**Comment by dianasaur323** [comment]
thanks @knz
