### ISSUE TITLE
REST Kinks

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#175]
since the REST API will be prominent in our upcoming beta, let's collect some potentially confusing points

* values are base64-encoded by the JSON marshaler
* keys returned by range scans are also base64-encoded
* byte-wise ordering means that "A" < "a" (well, that's just how it is)

Since it doesn't look like we can change anything about the above without a considerable amount of hacks, let's at least document this properly in examples. Speaking of document, I wasn't able to find a synopsis of the REST API. Did I miss it @andybons?

**Comment by spencerkimball** [comment]
@tschottdorf what's status of this?

**Comment by tschottdorf** [comment]
the REST API has since been removed.
