### ISSUE TITLE
distsql: physical planning refactor

### ISSUE THREAD

**Issue by arjunravinarayan** [cockroachdb/cockroach#17519]
The DistSQL physical planner needs some cleanup as it is rough around the edges.

Issues that need addressing (at the very least, documentation of the current state of things, even if no refactor is done) include:

- The `planner` follows a stateful pattern, where processors are added in groups, connecting to the existing `ResultRouters` - the output streams from the current last stage. Additional mutable state includes `ResultTypes`, `MergeOrdering`, and `planToStreamColMap`.
- Complicating this is that for packaging reasons, `planToStreamColMap` is in the struct `sql.PhysicalPlan`, whereas the others are in `distsqlplan.PhysicalPlan.
- Processors are added into a slice `PhysicalPlan.Processors`, and streams are added into the slice `PhysicalPlan.Streams`. Result Routers are indexes into the processors slice, and `planToStreamColMap` is a slice that maps Column I to streams `planToStreamColMap[i]`.
- We currently have helpers for some set of this, but the helpers only set some subset of the mutal `PhysicalPlan` state based on some other subset of state. For instance, Streams connect Processor pairs. But Processor specs include lists of streams for that processor. The current helpers will fill the latter information from the former information. This can only really be gleaned from cargo-culting existing specs.
- `stageCounter` is currently used only for cosmetic (i.e. plan diagram output) reasons, although it could be used, since processors are added in stages anyway.
- Nevertheless, sometimes invariants are enforced on processors of the same stage, e.g. when adding post-process specs to all result routers.
- Much of the planning process involves manually ranging over various subsets of slices, and appending with the right indexes. This is error-prone, and particularly complex in the case of merging multiple plans (e.g. Joins and other binary SQL operators).

This needs to be documented, and where possible, extracted into helper pure functions that encapsulate mutable state, to make physical planning easier.

cc @mjibson who has seen some of the problems in this area recently with fresh eyes, so might have some valuable input to add. cc @andreimatei as well for any thoughts.

**Comment by RaduBerinde** [comment]
> Complicating this is that for packaging reasons, planToStreamColMap is in the struct sql.PhysicalPlan, whereas the others are in `distsqlplan.PhysicalPlan.


This is not for packaging reasons. The `planToStreamColMap` is not a concept that belongs in `PhysicalPlan`. We only need it because of the particular way in which we build physical plans (from planNodes).

**Comment by vivekmenezes** [comment]
This project should consider the work being done on the optimizer. A lot of the code implemented in the physical planner can move to the optimizer over time.

**Comment by vivekmenezes** [comment]
@arjunravinarayan we should consider closing this issue. Most of the planning is moving to the optimizer

**Comment by arjunravinarayan** [comment]
Good point. Agreed.
