### ISSUE TITLE
settings: move back to a global (but indexing-only) registry

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#17512]
#17486 removed the singletons from the cluster settings package in a large refactor. Unfortunately, that refactor went a bit further than reviewers had hoped: it centralizes the registration of all settings in the `settings/cluster` package.

@RaduBerinde pointed out that we could keep a global registry which packages can call into to register a setting (which allows setting registration to remain close to settings usage).

This new "registry" wouldn't be much like the old. It would only store a mapping from (say) cluster setting key name to an index (which is incremented on each registration call into the registry).

Additionally, there is a matching `Settings` object that is passed around (today's `cluster.Settings`) which is then used to access the previously-defined settings.

I think it's worth setting this up in a toy example and perhaps write up in a small RFC. For example, it's not clear to me what the `Settings` object will look like. I think the intention in the suggestion above is that one does not have to make any changes to the `Settings` object when registering a new setting, but that means that `Settings` will be opaque, with only some methods to access each setting by id. This means that settings need to implement a common interface, something they don't today, and there are other issues to bikeshed such as how callbacks are registered.

@RaduBerinde, could you share your thoughts on this?

**Comment by RaduBerinde** [comment]
So here's a toy example for bool settings.

```go
type Settings struct {
  intVals [maxSettings]int32
  onChange [maxSettings]func() // may need to be atomic pointers
}
```

The `settings.common` struct is changed a bit:

```go
type common struct {
  description string
  hidden      bool
  idx         int  // gets assigned by RegisterBoolSetting, each setting has a different idx.
}


`BoolSetting` stays the same, except that we remove the value `v` and `Get` and `set` now take a `*Settings` argument:

// Get retrieves the bool value in the setting.
func (b *BoolSetting) Get(st *Settings) bool {
	return atomic.LoadInt32(&st.intVals[b.idx]) != 0
}

// Set retrieves the bool value in the setting.
func (b *BoolSetting) set(st *Settings, v bool) {..}
```

Registering callbacks can be done through a method on `common` (of course, these can't be global calls anymore):

```go

func (i *common) OnChange(st *Settings, f func()) {
  st.onChange[i.idx] = f
}

**Comment by petermattis** [comment]
We probably want to do this before 1.2 or it will make cherry-picking changes back to 1.1 more onerous. @RaduBerinde do you think you'll have time to get to this next week? Perhaps someone else can pick this up.

**Comment by RaduBerinde** [comment]
I'll work on it.

**Comment by tschottdorf** [comment]
Thanks Radu!
-- 

-- Tobias
