### ISSUE TITLE
sql: support stored procedures

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#17511]
CockroachDB needs stored procedures in the long term.
This is a placeholder issue to group action items:

- [x] support name scopes properly (work: planning)
- [x] support the Apply relational operator to be used by corr. subqueries, user-defined functions and proceudres (work: planning, execution)
- [x] support CTEs (work: planning)
- [x] support query compilation (work: planning, execution)
- [x] advance the deployment of auto-generated IR code in CockroachDB (work: language, planning)
- [ ] research an encoding in KV for stored procedure descriptors, define versioning semantics and whether they are editable
- [ ] research and design an AST for stored procedures. Ancillary questions: common AST for multiple languages? API if languages are provided externally (Lua, others)? Compile this AST. (work: language, planning)

gz#6812

gz#7833

Jira issue: CRDB-13448
Epic: CRDB-799

**Comment by knz** [comment]
A user has written a PDF about why it makes sense from a PM perspective: https://u23433218.dl.dropboxusercontent.com/u/23433218/PSM4CRDB%20EARLY%20DAFT%20BY%20CAMUEL%20GILYADOV.pdf

**Comment by camuel** [comment]
Thanks @knz, I have updated the document and here is the second version: https://tinyurl.com/ybq4tvqw

I'm impatiently waiting for a feedback and further guidance and I'm interested in implementing this feature. I do have a few questions:

1. Is there any big decisions which are already made? Such as commitment to support SQL/PSM or perhaps a firm decision not to. This will immediately narrow the scope of work for me.
2. Regarding 'support query compilation' mentioned above, what is meant here? Compiling the query to vectorized native code with perhaps LLVM for performance considerations? Impala did this for example. Or something entirely different?
3. How could common AST exist for multiple languages? Well some languages are similar but some are pretty different. Doing a common AST for Lua, SQL/PSM and Python is not feasible, does it? Will appreciate some elaboration.
4. It seems a lot of work, how we will go about it? Depth first or breadth first. I mean one way is to implement minimal UDF right now and then UDAF and a bit more constructs of PSM language, then SP, then triggers and etc.. Breadth first is to initially research the whole topic, write a design, will be a small book easily, do some experiments here and there, and then carry out the implementation.  Given multiple existing SQL/PSM implementations in the open, almost zero requirement risk, perhaps waterfall approach is not too crazy. Also, is this the only RFC or some other RFCs would be created for a smaller tasks?

Sorry for nooby questions and thanks again

**Comment by knz** [comment]
Hold your horses! We are welcoming input but **it is just too soon.** If you really want to help with this, please wait at least until January 2018.

If you and your team would like to help improve CockroachDB in the mean time, especially in areas that will enable later work on stored procedures, please let us know. In particular it would be great if you could get in touch with Nate Stewart <nate@cockroachlabs.com> to discuss your overall strategy, how and why you plan to contribute to CockroachDB, and see how well your plans/intents/interests match our roadmap. (Also we can take input from you!)

**Comment by tschottdorf** [comment]
If we introduce stored procedures, we'll also have to change [FmtAnonymize](https://github.com/cockroachdb/cockroach/blob/691ae16f70bae20a37e9fcb5c7bc784fd1e6e69e/pkg/sql/sem/tree/format.go#L105) to strip at least user-defined function names.

**Comment by fire** [comment]
Is there a status update on this?

**Comment by knz** [comment]
Yes: "not yet".

**Comment by Bertg** [comment]
Hi. It's been over year since the last status update. Can we get a new one, and if so, what would the content of that status update be?

**Comment by knz** [comment]
Hi Bert! Thanks for your inquiry.

We're currently exploring user-defined (stored) _functions_, but not procedures yet.

This year, the priority is to get our hosted service on the rail, increase the stability of existing features and invest into new (forward-looking) market differentiators. So it seems unlikely that we'll see a heavy investment into stored procedures, barring new information. But please check again next year.

**Comment by knz** [comment]
NB: We're currently hiring. If anyone reads this and feels strongly motivated in investing into stored procedures or other SQL features, maybe they should consider having CRL to pay them to do the work. Go here: https://www.cockroachlabs.com/careers/

**Comment by rustrial** [comment]
The recent rise of WASM makes me wonder whether CRDB could support stored functions/procedures provided in WASM format, which can access certain CRDB functionality via a clearly defined WASM ABI (Application Binary Interface) provided by CRDB. This way CRDB would not mandate any specific programming language but just provide a runtime and developers can use the language of their choice (if it supports WASM as target) to develop stored procedures.

**Comment by msdrigg** [comment]
Hey team, I am back once again a year later asking for a status update on this. I am interested because I was linked here from this other issue: https://github.com/cockroachdb/cockroach/issues/28296

**Comment by knz** [comment]
This is currently queued, thanks for your interest!

We're considering looking at user-defined functions before stored procedures, as they are more commonly used and less complex to support.

**Comment by kevinelliott** [comment]
This is the one feature holding me back from migrating from postgres to cockroach.

**Comment by rustrial** [comment]
@knz user-defined functions (UDF) as kind of a MVP for stored-procedures sound like a solid plan. Especially, if such user-defined functions could also be used in _check constraint_ and _default_ expressions.

Is there any roadmap information for UDFs?

## Example Use Case for UDFs

UDFs would allow us for example to enforce things like data domiciling (although that does not necessarily need UDF support, as it could also be achieved by supporting SQL select statements in _check constraint_ and _default_ expressions). 

```SQL
create table car_table
(
  -- Set data domiciling
  crdb_region  crdb_internal_region not null default lookup_region_of_tenant(tenant_id),
  tenant_id    uuid not null,
  ...
  constraint car_tfk foreign key (tenant_id) references tenant_table(id),
  -- Enforce data domiciling, 
  -- making sure the row is always stored in the region (country) associated with the tenant.
  constraint enforce_data_domiciling check (crdb_region = lookup_region_of_tenant(tenant_id)),
) regional by row as crdb_region;
```

**Comment by wadeschulz** [comment]
Also interested in timeline updates that would allow support for .NET/EF migrations (https://github.com/npgsql/efcore.pg/issues/2270)

**Comment by jordanlewis** [comment]
We're currently making progress on user-defined functions. You can follow progress in this issue: https://github.com/cockroachdb/cockroach/issues/58356

**Comment by Ranguna** [comment]
@jordanlewis just FYI seem @mgartner closed that issue in favour of all the other open ones.

**Comment by Enalmada** [comment]
[Drizzle ORM](https://github.com/drizzle-team/drizzle-orm) migrations output in the following syntax.  There is a growing segment of new startups passing on CockroachDB because of lack of compatibility here. 

```
DO $$ BEGIN
 CREATE TYPE "status" AS ENUM('ACTIVE', 'COMPLETED');
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
 ALTER TABLE "task" ADD CONSTRAINT "task_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;

```

**Comment by gerwim** [comment]
@jordanlewis Is there an update? Since the UDF issue has been merged. I'm here because of a different but related issue (https://github.com/npgsql/efcore.pg/issues/2270).
