### ISSUE TITLE
Distributed restore on cross global cluster taking hours to complete

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/cockroach#17522]
**BUG REPORT**

1. Please supply the header (i.e. the first few lines) of your most recent
   log file **for each node in your cluster**. On most unix-based systems
   running with defaults, this boils down to the output of

     grep -F '[config]' cockroach-data/logs/cockroach.log

root@pm-cluster-ams2-01:~#  grep -F '[config]' cockroach-data/logs/cockroach.log
I170808 16:53:15.996788 1 util/log/clog.go:975  [config] file created at: 2017/08/08 16:53:15
I170808 16:53:15.996788 1 util/log/clog.go:975  [config] running on machine: pm-cluster-ams2-01
I170808 16:53:15.996788 1 util/log/clog.go:975  [config] binary: CockroachDB CCL 60673bf (linux amd64, built 2017/08/05 16:43:27, go1.8.3)
I170808 16:53:15.996788 1 util/log/clog.go:975  [config] arguments: [cockroach start --certs-dir=certs --advertise-host=146.185.156.213 --join=192.241.150.167:26257]

root@pm-cluster-nyc1-02:~# grep -F '[config]' cockroach-data/logs/cockroach.log
I170808 13:41:12.612761 1 util/log/clog.go:975  [config] file created at: 2017/08/08 13:41:12
I170808 13:41:12.612761 1 util/log/clog.go:975  [config] running on machine: pm-cluster-nyc1-02
I170808 13:41:12.612761 1 util/log/clog.go:975  [config] binary: CockroachDB CCL 60673bf (linux amd64, built 2017/08/05 16:43:27, go1.8.3)
I170808 13:41:12.612761 1 util/log/clog.go:975  [config] arguments: [cockroach start --certs-dir=certs --advertise-host=165.227.80.203 --join=192.241.150.167:26257]

root@pm-cluster-sfo2-01:~# grep -F '[config]' cockroach-data/logs/cockroach.log
I170807 20:46:27.133722 1 util/log/clog.go:975  [config] file created at: 2017/08/07 20:46:27
I170807 20:46:27.133722 1 util/log/clog.go:975  [config] running on machine: pm-cluster-sfo2-01
I170807 20:46:27.133722 1 util/log/clog.go:975  [config] binary: CockroachDB CCL 60673bf (linux amd64, built 2017/08/05 16:43:27, go1.8.3)
I170807 20:46:27.133722 1 util/log/clog.go:975  [config] arguments: [cockroach start --certs-dir=certs --advertise-host=138.197.195.129 --join=165.227.80.203:26257]

![image](https://user-images.githubusercontent.com/894257/29090259-f514bd86-7c4c-11e7-817d-81138f346f1b.png)

2. Please describe the issue you observed:

- What did you do?
1. I setup a 4 node cluster in digital ocean: 2 nodes in NYC, 1 node in SF, 1 node in amsterdam. 
2. I tried to run an enterprise distributed restore to load the TPC data set (scale factor 1)

- What did you expect to see?
I expected to see this load in under an hour

- What did you see instead?
The restore did not complete even after several hours. According to

`SELECT id, type, fraction_completed, modified - started, (modified - started) / fraction_completed AS estimate, started FROM crdb_internal.jobs where id=268922315940036608;`

This was going to take 81 hours.

![image](https://user-images.githubusercontent.com/894257/29090322-33fd2d08-7c4d-11e7-82b1-8050473f9a9f.png)

**Comment by benesch** [comment]
@nstewart ran another TPCH1 restore which completed... but took 9 hours. We need to start doing our own geo-distributed testing.

**Comment by cuongdo** [comment]
I doubt this is getting fixed in 1.1, but this needs to be a high priority for 1.2.

**Comment by dianasaur323** [comment]
I'm not sure what happened, but I just ran a restore that finished in around 10 minutes. Perhaps @danhhz fixed this when he played around with our cluster?

**Comment by danhhz** [comment]
How much data were you restoring? tpch-1?

**Comment by dianasaur323** [comment]
Yes, although looks like @nstewart's original bug was also tpch scale factor 1?

**Comment by danhhz** [comment]
Yeah, it was. TPCH-1 should take less than a minute, so even though this got better, I'm inclined to leave this issue open.

**Comment by arjunravinarayan** [comment]
@dt I believe this bug can be closed. Can you please confirm what the TPCH-1 restore time is? in any case, it requires a milestone bump if we're going to leave this issue open.

**Comment by benesch** [comment]
I think performance still sucks :/. Let me check.

**Comment by arjunravinarayan** [comment]
In that case we should bump the milestone, since we're not going to improve the restore speed in the 2.0 timeframe.

**Comment by benesch** [comment]
Done.

**Comment by benesch** [comment]
Some TPCC numbers.

Non-distributed cluster (`roachprod create -n3`), three nodes:

```
+----------------+-----------------+
|     table      |    duration     |
+----------------+-----------------+
| csv.warehouse  | 441ms826µs      |
| csv.district   | 413ms34µs       |
| csv.customer   | 1m32s629ms174µs |
| csv.history    | 29s20ms226µs    |
| csv.order      | 25s812ms769µs   |
| csv.new_order  | 2s395ms340µs    |
| csv.item       | 961ms502µs      |
| csv.stock      | 3m6s169ms839µs  |
| csv.order_line | 3m6s645ms352µs  |
+----------------+-----------------+
```

Geo-distributed cluster (default `roachprod create -n3 --geo`), three nodes:

```
+----------------+-----------------+
|     table      |    duration     |
+----------------+-----------------+
| csv.warehouse  | 2s676ms282µs    |
| csv.district   | 2s67ms33µs      |
| csv.customer   | 2m57s799ms108µs |
| csv.history    | 41s834ms366µs   |
| csv.order      | 35s58ms228µs    |
| csv.new_order  | 9s22ms783µs     |
| csv.item       | 7s568ms948µs    |
| csv.stock      | 4m38s908ms245µs |
| csv.order_line | 4m1s174ms693µs  |
+----------------+-----------------+
```



Local cluster, one node:

```
+----------------+-----------------+
|     table      |    duration     |
+----------------+-----------------+
| csv.warehouse  | 399ms904µs      |
| csv.district   | 354ms300µs      |
| csv.customer   | 1m53s700ms18µs  |
| csv.history    | 42s219ms413µs   |
| csv.order      | 37s267ms110µs   |
| csv.new_order  | 2s223ms342µs    |
| csv.item       | 867ms528µs      |
| csv.stock      | 2m59s630ms559µs |
| csv.order_line | 3m47s176ms298µs |
+----------------+-----------------+
```

So things are looking pretty good! I'll leave it up to @dt to decide whether we're good enough to close.

**Comment by dt** [comment]
Thanks for the numbers @benesch, looks like there's minimal difference here.
