### ISSUE TITLE
https://www.cockroachlabs.com/blog/sql-cockroachdb-column-families/

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/cockroach#17525]
https://www.cockroachlabs.com/blog/sql-cockroachdb-column-families/

The following links in the blog are no longer valid

https://github.com/cockroachdb/cockroach/blob/master/docs/stable/RFCS/sql_column_families.md
https://github.com/cockroachdb/cockroach/blob/master/docs/stable/RFCS/sql_column_families.md#heuristics-for-fitting-columns-into-families

**Comment by jseldess** [comment]
Moved to https://github.com/cockroachlabs/hugo-website/issues/164
