### ISSUE TITLE
storage: add cluster setting for timestamp cache size

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#17531]
Replace the `COCKROACH_CONSISTENCY_CHECK_INTERVAL` env var with a cluster setting and allow the consistency checker to be disabled. The default 24h interval might be inappropriate for large numbers of ranges.

Add cluster settings for `kv.defaultLeaseHolderCacheSize` and `kv.defaultRangeDescriptorCacheSize`. The default leaseholder cache size is 64k which is too small for large numbers of ranges. Sort of strange that the default range descriptor cache size is 1m. The result is we can cache 1m range descriptors, but only 64k leaseholders.

**Comment by bdarnell** [comment]
For the consistency queue, we could also put a floor on the value returned by `consistencyQueue.timer`. This would have the effect of slowing down the queue automatically as the number of ranges increases.

It's just silly that the range descriptor and lease holder cache sizes are different. These should probably be a function of the memory available to the process.

**Comment by petermattis** [comment]
> For the consistency queue, we could also put a floor on the value returned by consistencyQueue.timer. This would have the effect of slowing down the queue automatically as the number of ranges increases.

One downside to doing this is that it makes the description of `server.consistency_check.interval` more complex. "I want a 24hr interval between consistency checks of a range except if I have too many ranges in which case I want a minimum 10s between individual range checks on a store."

> It's just silly that the range descriptor and lease holder cache sizes are different. These should probably be a function of the memory available to the process.

We also have `defaultTimestampCacheSize` (64 MB) and `defaultRaftEntryCacheSize` (16 MB). Any suggestion on how to set these based on memory available to the process? Adding more cluster settings is a cop out, but it least it is obvious. One downside to cluster settings here is that we might want per-node control when nodes are heterogeneous.

**Comment by bdarnell** [comment]
> One downside to cluster settings here is that we might want per-node control when nodes are heterogeneous.

If the setting is a size, that is. We could make the settings be fractions, then they'd adjust automatically. That seems harder to use, though. (I think we could give the timestamp cache 5-10% of the physical ram; scaling the raft entry cache with memory size seems less effective)

**Comment by petermattis** [comment]
Is there every a reason to have a different size for the range descriptor cache and the leaseholder cache? I'm thinking to add a single setting that controls the sizes of those caches and changing the timestamp cache size to be `X%*<cache-size>/num-stores`.

**Comment by bdarnell** [comment]
I think that would be fine. (in theory leases move around more often than range descriptors change, so expanding the lease holder cache is less likely to be useful than the range descriptor cache, but I don't think that level of micromanagement is likely to be helpful)

**Comment by petermattis** [comment]
While developing a change to size the timestamp cache as `X%*<cache-size>/num-stores` I discovered that doing so impacts performance if the configured cache size is significantly larger than the current cache size (64 MB). This appears to be due to increased Go GC. Given the lateness in the current cycle and that this isn't really a bug fix, I'm going to punt configuration of the timestamp cache size to 1.2.

**Comment by petermattis** [comment]
@nvanbenschoten We should have a cluster setting for the timestamp cache size, just as we have such settings for other caches in the system.

**Comment by arjunravinarayan** [comment]
These additional cluster settings are not going to be done in 2.0. I'm bumping the milestone to 2.1. Feel free to push back.

**Comment by nvanbenschoten** [comment]
This is still on my plate for 2.0. The change should be very small.
