### ISSUE TITLE
settings: mark cluster settings that gate features more explicitly

### ISSUE THREAD

**Issue by rjnn** [cockroachdb/cockroach#17536]
Currently, one can either view an individual cluster setting by name, or by querying all cluster settings with `SHOW ALL CLUSTER SETTINGS`. This returns a large table of settings (~30), including knobs that no sane production user should tune (`kv.snapshot_rebalance.max_rate`, `kv.allocator.lease_rebalancing_aggressiveness`).

We are starting to also use cluster settings to gate L and XL features in releases, setting them to default off (one current candidate for such a gated feature: merge joins in DistSQL). These features are those that we *would* like users to try out, and we want to expose them more gently, and perhaps advertise the set of experimental features in a consistent way in our documentation, to encourage this.

Thus, I propose that we add another syntax: `SHOW EXPERIMENTAL FEATURES` or something of that sort (bikeshed that away). Another alternative is to allow for WHERE clause filtering, and having a column "feature". As long as we limit the list of experimental features to some reasonable set of options and "graduate" features with each release, this would make users more likely to use them. This requires some PM input on how best to present these (cc @nstewart), but 

I would like to take this on, if we get consensus on which direction we would like to take.

cc @dt @knz

Jira issue: CRDB-6033

**Comment by dt** [comment]
my initial reaction is we should try highlighting in docs/release notes first, before adding more surface area to core settings stuff, but we could also consider namespacing feature flags together, if we think these settings are qualitatively different, and the emphasis on that is more valuable than their being grouped with related functionality's knobs.

**Comment by nstewart** [comment]
I like the idea of separating tuning knobs from functionality that is useful (with caveats) but not quite ready to be turned on by default. SHOW EXPERIMENTAL FEATURES works for me or perhaps SHOW BETA FEATURES (assuming we know they work correctly for some documented set of use cases)

If we wanted to start with docs, we could create a table in an “experimental features” page that just had the names of all the cluster settings as rows. I think that would be a fine start.

**Comment by knz** [comment]
So from my experience working with other projects with such "feature flags" is that in practice it is rather hard to make a 1:1 mapping between the thing you can tune and a "feature" in the marketing sense.

In practice rather a single setting will enable multiple "features" at once, or a setting that influences 1 feature will also influence another feature. 

Also very common, and very problematic for the naive approach suggested above: dependency graphs and constraints between features (as in, "to enable this feature that other feature must be enabled first" and "this feature can only be enabled if that other parameter is within this value range")

So in summary, *although I am very much in favor of only showing things by default that we actually encourage users to look at* (or conversely, trying a bit to hide things we don't want them to tune without supervision) I don't think you can effectively achieve that by thinking about this using the words "feature", "feature gate" or "functionality". 

### What then?

**What does work, in my experience, is conveying the idea of intent and maturity** in relationship to our experience and documentation, i.e. "how much or little supervision we require to change some flags".

- Regarding maturity: from a PR perspective word "maturity" can't be written (even though everyone knows that's what matters), so instead people tend to use the word "visibility" (with "maturity" as hidden meaning). In practice:
  - an extra attribute "visibility" for all settings
  - e.g. "internal" for things we really don't want users to tune themselves
  - e.g. "experimental" for things we expect can break in surprising ways
  - e.g. "public" for things that we document very well and where we are confident users won't break things in subtle and difficult-to-troubleshoot ways
- Regarding intent:
  - another extra attribute "category" for all settings
  - e.g. "tuning" for things that do not change the functional behavior in any way
  - e.g. "admin" for things that change the functional behavior in ways that are not visible to client apps
  - e.g. "apps" for things that change the functional behavior visible to client apps
- add a new variant `show cluster settings` (no "all") that displays only public items by default (And show the category/intent for each setting)
- make `show all cluster settings` display everything like currently
- **change docs to advertise primarily the first variant without "all"**

### Example

( just an idea -- I'm not feeling strongly about any of this )

Intent | Maturity/Visibility | Setting | Description
-- | -- | -- | --
apps | public | kv.transaction.max_intents | maximum number of write intents allowed for a KV transaction
apps | public | sql.defaults.distsql | Default distributed SQL execution mode [off = 0, auto = 1, on = 2]
apps | experimental | sql.defaults.distsql.tempstorage | set to true to enable use of disk for larger distributed sql queries
admin | public | cluster.organization | organization name
admin | public | diagnostics.reporting.enabled | enable reporting diagnostic metrics to cockroach labs
admin | public | diagnostics.reporting.interval | interval at which diagnostics data should be reported
admin | public | diagnostics.reporting.report_metrics | enable collection and reporting diagnostic metrics to cockroach labs
admin | public | diagnostics.reporting.send_crash_reports | send crash and panic reports
admin | public | server.remote_debugging.mode | set to enable remote debugging, localhost-only or disable (any, local, off)
admin | public | sql.metrics.statement_details.dump_to_logs | dump collected statement statistics to node logs when periodically cleared
admin | public | sql.metrics.statement_details.enabled | collect per-statement query statistics
admin | public | sql.metrics.statement_details.threshold | minimum execution time to cause statistics to be collected
admin | public | sql.trace.log_statement_execute | set to true to enable logging of executed statements
admin | public | sql.trace.session_eventlog.enabled | set to true to enable session tracing
admin | public | sql.trace.txn.enable_threshold | duration beyond which all transactions are traced (set to 0 to disable)
admin | public | trace.debug.enable | if set, traces for recent requests can be seen in the /debug page
admin | public | trace.lightstep.token | if set, traces go to Lightstep using this token
admin | public | trace.zipkin.collector | if set, traces go to the given Zipkin instance (example: '127.0.0.1:9411'); ignored if trace.lightstep.token is set.
tuning | public | kv.bulk_io_write.max_rate | the rate limit (bytes/sec) to use for writes to disk on behalf of bulk io ops
tuning | public | kv.snapshot_rebalance.max_rate | the rate limit (bytes/sec) to use for rebalance snapshots
tuning | public | kv.snapshot_recovery.max_rate | the rate limit (bytes/sec) to use for recovery snapshots
tuning | public | server.web_session_timeout | the duration that a newly created web session will be valid
tuning | internal | kv.allocator.lease_rebalancing_aggressiveness | set greater than 1.0 to rebalance leases toward load more aggressively, or between 0 and 1.0 to be more conservative about rebalancing leases
tuning | internal | kv.allocator.load_based_lease_rebalancing.enabled | set to enable rebalancing of range leases based on load and latency
tuning | internal | kv.allocator.range_rebalance_threshold | minimum fraction away from the mean a store's range count can be before it is considered overfull or underfull
tuning | internal | kv.allocator.stat_based_rebalancing.enabled | set to enable rebalancing of range replicas based on write load and disk usage
tuning | internal | kv.allocator.stat_rebalance_threshold | minimum fraction away from the mean a store's stats (like disk usage or writes per second) can be before it is considered overfull or underfull
tuning | internal | kv.gc.batch_size | maximum number of keys in a batch for MVCC garbage collection
tuning | internal | kv.raft_log.synchronize | set to true to synchronize on Raft log writes to persistent storage
tuning | internal | kv.raft.command.max_size | maximum size of a raft command
tuning | internal | rocksdb.min_wal_sync_interval | minimum duration between syncs of the RocksDB WAL
tuning | internal | server.declined_reservation_timeout | the amount of time to consider the store throttled for up-replication after a reservation was declined
tuning | internal | server.failed_reservation_timeout | the amount of time to consider the store throttled for up-replication after a failed reservation call
tuning | internal | server.time_until_store_dead | the time after which if there is no new gossiped information about a store, it is considered dead
tuning | experimental | sql.distsql.distribute_index_joins | if set, for index joins we instantiate a join reader on every node that has a stream; if not set, we use a single join reader
tuning | experimental | sql.distsql.merge_joins.enabled | if set, we plan merge joins when possible


### Respect users & docs are fine too

Coming back to the notion of "feature gate" and 1:1 mapping between settings and features: we can *try* implementing/designing "feature gate" settings but in my experience it's a waste of time and going to cost us a lot both in engineering and explaining. I do think that despite all odds users are able to appreciate tuning knobs for being just that -- **knobs that you can only look at in the context of a larger picture drawn by documentation**. If someone can understand a plane doesn't need separate buttons to take off and land, they can understand that the buttons in CockroachDB do not map 1:1 to features.

**Comment by dianasaur323** [comment]
Ha! The bikeshedding got intense. Regardless of how you choose to do this, this sounds like a great idea. For certain features, this would give us a gestation period where we can fix bugs that only users can find. Re mapping 1:1 to settings and features, I worry that many users don't actually fully read our documentation.

**Comment by dianasaur323** [comment]
Given that we are actively starting to mark things in beta, I think we should decide on a platform-based approach going into 1.2. Bumping priority to 1.2. Depending on what we decide to do, we may have to allocate airtable love to this.

**Comment by dianasaur323** [comment]
@arjunravinarayan How much time do you think it would take to implement this? I would love to have a SHOW EXPERIMENTAL as well as a SHOW NONDEFAULT (for nondefault values as detailed here https://github.com/cockroachdb/cockroach/issues/18696)

**Comment by arjunravinarayan** [comment]
Not very long at all, less than a day.

**Comment by dianasaur323** [comment]
hmm... ok good to know. let's hold off for a bit until I get the chance to formulate thoughts on if this is really the right approach.
