### ISSUE TITLE
ui: show statement statistics in admin UI and results of `cockroach zip`

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#17549]
Forked off #13968

- [ ] add an admin RPC to extract current statement statistics for 1 node or the whole cluster 
- [ ] use said admin RPC in `cockroach zip` (to ease troubleshooting etc)
- [ ] create an admin UI page to report statement statistics to the user interactively as well

**Comment by dianasaur323** [comment]
Definitely not going to make it into 2.0, but we are scoping modifications to this feature in 2.1, so let's discuss what this looks like then.

**Comment by jordanlewis** [comment]
This is the statements page.
