### ISSUE TITLE
sql: enable users who wish so to reveal more details to Cockroach Labs

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#17548]
Forked from #13968.

- [ ] add a cmdline flag to identify the operator/user
  - [ ]  add a setting for the user
  - [ ] link the registration form to editing this user

The idea here is that when a user has a support contract we want to link their cluster data to their support contract so we can better troubleshoot their problems.

Identity linking should not be enabled by default, and customizable using setting variables.

To be discussed via RFC also together with sales / PM.

**Comment by dianasaur323** [comment]
I marked this down for our next release, but would prefer for us to get some stronger pull from our customers before putting this formally on the roadmap.

**Comment by knz** [comment]
we've achieved this by linking the license and cluster ID
