### ISSUE TITLE
sql: SELECT * FROM generate_series() vs SELECT FROM generate_series()

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#17546]
I was surprised with @tso to find out that there's a difference between the two. The 2nd one doesn't seem to produce results until the function terminates producing the whole result table, whereas the first one "streams" results out. Is that expected?

**Comment by knz** [comment]
There is no such syntax `SELECT FROM generate_series()`. Please clarify.

The syntax `select * from generate_series(1,100)` should produce results incrementally without accumulating in memory. 

The syntax `select generate_series(1,100)` is a join in disguise + the join is executed locally as a hash join, so yes you only get results once the join has completed.

**Comment by andreimatei** [comment]
yeah, I guess I meant `select generate_series(1,100)`. What's the join?

**Comment by knz** [comment]
it's an artifact from the fact `select <genfuncion>` is a degenerate syntax that shouldn't exist. It's only supported for compatibility with pg. We don't care about its performance.

**Comment by andreimatei** [comment]
`SELECT <table-valued function>` seems legit to me, just like `SELECT <table name>` is legit. And Tristan has typed it, so users want it :)
I'm not saying this is the most important thing to work on, but I think the issue is valid.
You can tell me that it's technically unfeasible, but then you'd make me curious why :)

**Comment by knz** [comment]
`SELECT <tablename>` is not legit either.
It's a weird bug in the pg syntax that has been deprecated on pg mailing lists for ages.

If you want an entire table (or generating function) the standard SQL syntax is `TABLE <tablename>` (probably `TABLE generate_series()` should work too.

We ought to error out on `SELECT <tablename>` really and I'm considering having a flag in the SQL CLI that rejects anything we just happen to support for pg compatibility but that is otherwise obnoxious.

**Comment by knz** [comment]
@andreimatei if I were to close this issue and open another instead to "introduce a beginner mode in the SQL CLI, where constructs that are recognized but not recommended get a suggestion and need a confirmation to continue", would you be OK with that?

(Such an issue would also push to receive confirmation on `DELETE FROM <table>` which is also insanely problematic).

**Comment by petermattis** [comment]
Hopefully this "beginner mode" would not be CLI specific, but enabled via a session variable. `DELETE FROM <table>` is almost always problematic. I can see wanting to prevent applications from accidentally doing that as well.

**Comment by knz** [comment]
yes I was thinking about a session variable too. These checks will be done server-side.

**Comment by petermattis** [comment]
I seem to recall that some other database has user permissions regarding certain expensive and dangerous operations such as `DELETE FROM <table>`. Perhaps I'm misremembering.

**Comment by cuongdo** [comment]
One thing I've used in the past: https://dev.mysql.com/doc/refman/5.7/en/mysql-command-options.html#option_mysql_safe-updates
