### ISSUE TITLE
ui: node overview displays incorrect node status after refresh

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#17554]
1. Start a cluster and kill a node.
2. Open the Admin UI, click on "View nodes list."
3. Click on the killed node.
4. Observe the "suspected" or "dead" status in the node summary box on the top right.
5. Refresh the page.
6. Observe that the node summary box erroneously displays the status as "healthy."

**Comment by dianasaur323** [comment]
I think this might have to do with the length of time it takes for a node to be recognized as dead? @mrtracy

**Comment by cuongdo** [comment]
Yeah, there is a small amount of time (1 minute?) that needs to pass for a node to turn yellow, then more time (5 minutes?) for it to turn red. @benesch have you tried waiting longer?

**Comment by benesch** [comment]
The point is that regardless of whether a node is _actually_ suspect or dead, reloading the page will show the node as healthy. After a reload, if you renavigate to the node overview page from the homepage, it'll have the correct status (suspect or dead). I suspect the node overview page isn't properly reloading the node liveness data; it relies on the node**s** overview (note the s) page to do so. This works in the common case when you navigate to the node overview page from the nodes overview page, but not when you load the node overview page directly.

**Comment by dianasaur323** [comment]
Got it - you're basically pointing out a situation when there is some data discrepancy. There might not be time to do this in 1.1, but let's address this in 1.2.
