### ISSUE TITLE
ui: Graphs interpolate a little too generously between distant data points

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#17552]
Indigo was failing to write timeseries metrics for more than two and a half days. Once they started getting written again, any time period that includes times both before and after the outage will try to interpolate between the data points despite that massive gap in time between them:

<img width="936" alt="screen shot 2017-08-09 at 11 28 04 am" src="https://user-images.githubusercontent.com/7085343/29129866-3314f458-7cf6-11e7-8aa4-36fe5acee78b.png">

It'd be more accurate to not graph lines when there's a large gap between consecutive points in a stream. I expect this would also affect cases where a node was taken offline for a while -- when it comes back up, per-node graphs for that node will try to interpolate between the last point before it went down and the first point after it came up, rather than graphing that time period as zero.

**Comment by dianasaur323** [comment]
Hm.... this seems to be a bigger problem than some other remaining 1.1 bugs. Let's still consider this as a nice-to-have versus a nice to have though.

**Comment by couchand** [comment]
This won't be fixed by #18620, but it will be much easier to fix after that.

**Comment by couchand** [comment]
As mentioned on #22490, we should mark as "no data" the most recent data points as well, if some nodes have reported a metric but others have not.  I think that will naturally roll into this issue, which should mark as "no data" anywhere that we are missing data points.
