### ISSUE TITLE
sql: SET does not support placeholders

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#17563]
```
error executing 'SET CLUSTER SETTING enterprise.license = $1': pq: got 1 parameters but the statement requires 0
```

@knz says:

> it's because Set does not currently implement the prepare protocol
> `plan.go` function `prepare()`
> (if you do not move the logic from the planNode constructror to a Start() method, then the SET will take effect as soon as the PREPARE is run, which is most definitely not correct)
> the constructor needs to type check yes
> but the logic that effects the change must migrate to Start()

Assigning to @knz for triage.

**Comment by dt** [comment]
when we get to this yak, I'd like to get the LHS too.

**Comment by knz** [comment]
yes, well understood.
