### ISSUE TITLE
storage: split failed, duplicate key value

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#17560]
While running a large number of splits (via `ALTER TABLE ... SPLIT AT`), one of the splits failed with:

`2017/08/09 20:02:15 pq: storage/replica_command.go:2745: split at key /Table/51/1/7280155548282103922 failed: duplicate key value (timestamp,uniqueID)=('2017-08-09 20:02:07.429024+00:00',269479231017549824) violates unique constraint "primary"`

I believe this is coming from insertion into the `system.rangelog` table. Since none of the nodes restarted while this was occurring, it seems like we must be mishandling a conditional put. Perhaps on a retry.

This appears to be reproducible (it has happened more than once), though not easily.

**Comment by tamird** [comment]
Just hit this on denim while running `roachperf test denim nightly`.

**Comment by petermattis** [comment]
Reproduced with additional logging. On one node we have:

```
I170819 12:31:06.072444 41296 storage/replica_command.go:2703  [n6,s6,r997/3:/Table/51/1/-1727{9140…-4665…}] initiating a split of this range at key /Table/51/1/-1727681550511414974 [r3636]
I170819 12:31:06.076604 41296 storage/replica_command.go:2742  [n6,s6,r997/3:/Table/51/1/-1727{9140…-4665…}] logging split: /Table/51/1/-1727681550511414974 [r3636]
I170819 12:31:06.082473 41296 sql/parser/builtins.go:2640  GenerateUniqueInt 272221687259004928
```

And on another node:

```
I170819 12:31:06.072447 104844 storage/replica_command.go:2703  [n4,s4,r1221/3:/Table/51/1/5470{4816…-7748…}] initiating a split of this range at key /Table/51/1/5470672550704321813 [r3689]
I170819 12:31:06.081202 104844 storage/replica_command.go:2742  [n4,s4,r1221/3:/Table/51/1/5470{4816…-7748…}] logging split: /Table/51/1/5470672550704321813 [r3689]
I170819 12:31:06.082472 104844 sql/parser/builtins.go:2640  GenerateUniqueInt 272221687259004928
```

Oh boy! 2 uniquely generated unique IDs. Why do they have the same node id in the low bits? The log messages for the goroutine indicate that one occurred on `n4` and the other `n6`.

Oh, looks like the node ID isn't being populated. `272221687259004928` is `0x3c7202ea93b0000` in hex. Similarly, from the original message the colliding unique ID was `269479231017549824` which is `0x3bd61eecf258000`. Where are my low order node id bits?

**Comment by petermattis** [comment]
Hmm, this isn't reproducible from the sql shell. So we're probably not populating the `EvalCtx` correctly on the code path used for logging splits. Phew, not nearly as serious as I was imagining.

**Comment by petermattis** [comment]
This is very likely a bug in 1.0.x as well. Not sure it is worth fixing there as we haven't heard of any reports and it requires doing an excessive number of concurrent splits. The effect is only a crash, not data corruption.

**Comment by petermattis** [comment]
Cc @bdarnell

**Comment by bdarnell** [comment]
Is this a crash? It looks like the split is returning an error cleanly. 

If we do a 1.0.6 release we might as well throw this in, but I don't think this alone is a sufficient reason to do a patch release when 1.1 is coming so soon.

**Comment by petermattis** [comment]
I misspoke. This isn't a crash, but a failed split that gets reported as such. Definitely doesn't seem to rise to the level of a patch to 1.0.
