### ISSUE TITLE
dangerous: Encounter a terrible thing when join a node into cluster!!!

### ISSUE THREAD

**Issue by EamonZhang** [cockroachdb/cockroach#17567]
**DESCRIB**

Test Fault Tolerance & Recovery

3 separate machines

1. shut down one node.  --- cluster available
2. now try to rejoins this node into the cluster

case A

add the node into cluster use below command

`cockroach start --certs-dir=certs --host=127.0.0.1`

This cause cluster unavailable

It is very dangerous in the production environment!!!

The mistake is easy to make but the result was serious.  as you can imagine lots of node in your cluster ， 
wo wo wo

case B

1. `cockroach start --certs-dir=certs`  --- forget  --host flag
2. `cockroach start --certs-dir=certs  --host=host ip` 

This node can not rejoin into the cluster  again !

Prompt Dead Nodes  IN admin ui
127.0.0.1:26257

**Comment by a-robinson** [comment]
Thanks for the report, @EamonZhang! Can you be more specific about which nodes had which host flags, both the first time they were started up and after restarting them?

Changing the `--host` flag should only break things if the new host name/IP isn't routable from all the other nodes. In your case B, are you saying that just directly starting the node the first time with `--host=<host ip>` works, but it doesn't work if you've previously started it without the `--host` flag?

cc @dianasaur323

**Comment by EamonZhang** [comment]
@a-robinson 

I have three nodes;
IP 10.2.0.12 ,10.2.0.13,10.2.0.14  

Through further testing ， this  depends on the start order. 

step 1.  init cluster 10.2.0.12 -> 10.2.0.13 -> 10.2.0.14
```
cockroach start --background --certs-dir=certs --host=10.2.0.12
CockroachDB node starting at 2017-08-11 08:49:12.319904916 +0800 CST
build:      CCL v1.0.4 @ 2017/07/27 17:54:36 (go1.8.3)
admin:      https://10.2.0.12:8080
sql:        postgresql://root@10.2.0.12:26257?sslcert=certs%2Fclient.root.crt&sslkey=certs%2Fclient.root.key&sslmode=verify-full&sslrootcert=certs%2Fca.crt
logs:       /opt/crdb/cockroach-data/logs
store[0]:   path=/opt/crdb/cockroach-data
status:     initialized new cluster
clusterID:  2eafd205-5828-44c7-8025-bcb3973d8b18
nodeID:     1
```
```
cockroach start --background --certs-dir=certs --host=10.2.0.13 --join=10.2.0.12
CockroachDB node starting at 2017-08-11 08:51:19.171319844 +0800 CST
build:      CCL v1.0.4 @ 2017/07/27 17:54:36 (go1.8.3)
admin:      https://10.2.0.13:8080
sql:        postgresql://root@10.2.0.13:26257?sslcert=certs%2Fclient.root.crt&sslkey=certs%2Fclient.root.key&sslmode=verify-full&sslrootcert=certs%2Fca.crt
logs:       /opt/crdb/cockroach-data/logs
store[0]:   path=/opt/crdb/cockroach-data
status:     initialized new node, joined pre-existing cluster
clusterID:  d09da71f-d87b-4c3a-a48a-55bb7407ad60
nodeID:     2
```
```
cockroach start --background --certs-dir=certs --host=10.2.0.14 --join=10.2.0.12
CockroachDB node starting at 2017-08-11 08:52:21.285668847 +0800 CST
build:      CCL v1.0.4 @ 2017/07/27 17:54:36 (go1.8.3)
admin:      https://10.2.0.14:8080
sql:        postgresql://root@10.2.0.14:26257?sslcert=certs%2Fclient.root.crt&sslkey=certs%2Fclient.root.key&sslmode=verify-full&sslrootcert=certs%2Fca.crt
logs:       /opt/crdb/cockroach-data/logs
store[0]:   path=/opt/crdb/cockroach-data
status:     initialized new node, joined pre-existing cluster
clusterID:  d09da71f-d87b-4c3a-a48a-55bb7407ad60
nodeID:     3
```
step 2.  stop and rejoin , operation results differ at different nodes
a. node: 10.2.0.12
```
pkill -9 cockroach
cockroach start --certs-dir=certs --host=127.0.0.1 --logtostderr
```
cluster unavailable

b. node: 10.2.0.13 
```
pkill -9 cockroach
cockroach start --certs-dir=certs --host=127.0.0.1 --logtostderr
```
node 10.2.0.13 unavailable

c. node: 10.2.0.14 
```
pkill -9 cockroach
cockroach start --certs-dir=certs --host=127.0.0.1 --logtostderr
```
it seems no problem ,

**Comment by bdarnell** [comment]
Starting the nodes with `--host=127.0.0.1` tells the processes to only use the loopback network interface, which means that they're only able to talk to other processes on the local node. This is a legitimate thing to do for a single-node testing "cluster", but as you see here it will break any multi-node cluster. But what makes this mistake easy to make, and what would you like to see us do differently? It will always be possible for operators to misconfigure their clusters in ways that we won't be able to prevent.

**Comment by dianasaur323** [comment]
It looks like perhaps we should prevent users from restarting a node with a different host name, although I could see scenarios where someone might want that flexibility?

**Comment by bdarnell** [comment]
It's sometimes necessary to restart with a different hostname when your network changes. Other than treating `--host=127.0.0.1` as a special case (disallowing it when there are non-localhost join addresses), I don't see how we could detect this (so the question is whether this is a common enough case to be worth special casing). And then if we *did* detect it, what would we do? We could crash the node, but that won't bring your cluster back up. The operator will have to notice that it's not working and change the config to undo the mistake; there's no way around that.

**Comment by dianasaur323** [comment]
If my  understanding is correct, if you only mess up the ```--host=127.0.0.1 flag``` with one node, the other two nodes should still be up and available. Perhaps this could be as simple as a warning that gets logged if the user then subsequently tries to change the settings of a second node that is still part of the working cluster? I agree with you that there might not be anything we can do on our end.

**Comment by bdarnell** [comment]
> Perhaps this could be as simple as a warning that gets logged if the user then subsequently tries to change the settings of a second node that is still part of the working cluster?

We can't tell that until it's too late. The other nodes can't tell the difference between a node that has `--host=127.0.0.1` and one that is simply down, and you can't change the `--host` flag until after you've already taken the second node down.

**Comment by bdarnell** [comment]
I don't think there's anything specific we can do here.
