### ISSUE TITLE
storage: Don't let one poorly-performing node slow down an entire cluster

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#17572]
If one node in a cluster has very low throughput / high latency for whatever reason, it can have a pretty drastic effect. For example, on indigo, node 5's disk throughput is significantly worse than all other nodes for some reason (see #17478), and it leads to situations where **removing** node 5 has the drastic effect on performance seen at 15:00 in the below graph:

<img width="1396" alt="screen shot 2017-08-10 at 11 39 57 am" src="https://user-images.githubusercontent.com/7085343/29178887-e044590a-7dc0-11e7-8183-76d458bc94fa.png">

That's a 10x increase in performance caused by reducing the total compute/storage resources in the cluster, which is very counterintuitive. Ideally, adding a node (even if it's slower than the others) would at worst have no negative impact on performance, and at best provide at least a little more throughput.

This may look something like recognizing when a node is overloaded (based on some latency measurement - perhaps disk latency) and take that into account when rebalancing, such that a node performing significantly worse than other nodes will continually have replicas taken away from it until it's no longer performing significantly worse (even if that means going all the way to zero). We would have to make this condition noticeable to users in some way, because it may be quite surprising to them.

**Comment by a-robinson** [comment]
It is worth noting that load-based rebalancing as implemented for 1.1 can make this situation worse - since we balance on keys written per second, if one node isn't capable of writing as many keys per second, we'll consider it a good rebalancing target, thus reducing the total number of keys-per-second that can be written across the entire cluster. I don't think this should have a huge effect, since we require 2 dimensions to be out of balance before moving a replica, but it may make it somewhat worse.

**Comment by petermattis** [comment]
This is an extreme example of heterogenous nodes which we need to address eventually. Using op latency seems reasonable, though perhaps we could do some exploration of which metrics are sensitive to this scenario. 

PS One way to simulate heterogenous nodes is to set `GOMAXPROCS` to some value less than `runtime.NumCPU()`.
