### ISSUE TITLE
sql: batched statements should be aborted on error

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#17573]
Currently, we deviate from Postgres in that we execute every statement in a batch of statements regardless of the status of statements earlier in the batch. Postgres gives up after the very first error.

It's hard to notice this because the `psql` client automatically un-bundles a statement with internal semicolons into several statements and sends them in sequence - whereas our client doesn't do such un-bundling. Props to @tso for noticing that.

We should do the same thing: stop executing statements in a batch once one of them fails.

**Comment by tso** [comment]
Should be fixed by https://github.com/cockroachdb/cockroach/pull/17019.

**Comment by mjibson** [comment]
I wasn't able to reproduce this on either v1.1-alpha.20170810 or master, so am closing.
