### ISSUE TITLE
cli: better error message for COPY FROM STDIN

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#17577]
The Cockroach CLI doesn't support COPY FROM STDIN.

Currently it gives a garbage error when a user tries `COPY`:

```
root@:26257/test> copy kv from stdin;
pq: unknown response for simple query: 'G'
error retrieving the transaction status: driver: bad connection
connection lost; opening new connection: all session settings will be lost
```

We should detect users trying to use this unsupported command and provide a better message.

cc @cockroachdb/sql-ui

**Comment by knz** [comment]
Hmm no here the error is really in `lib/pq`.
