### ISSUE TITLE
Don't retry forever on transport errors

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#1759]
The http senders retry forever on all transport errors (it's difficult to tell transient from persistent errors) as well as some http response codes.
We should move the retry logic higher up.

Example:
running a server in secure mode (https) and starting a client with an http:// target will retry forever with little or no information logged. We should either set a (fairly low) MaxRetries count, or bail out right away and let a higher level handle the retry logic.

**Comment by petermattis** [comment]
`client.httpSender` has been removed for a while and `client.rpcSender` does not retry.
