### ISSUE TITLE
sql: get rid of the Session.TableCollection

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#17597]
Currently the Session has a TableCollection member: https://github.com/cockroachdb/cockroach/blob/57423bafbfda80679cab22204b8c4ccb436297c6/pkg/sql/session.go#L248

It contains descriptors and leases used by the current transaction. I believe the idea was, at some point, that transactions should reuse descriptors.
I think it'd be great if we managed to get rid of this member. First of all, if this structure is per-transaction and not per-session, then it's placed in the wrong place.
More importantly, as of recently, we're good about giving correct descriptors to transactions based on the transaction's timestamp. I'd be great if this stayed the single mechanism by which correct descriptors are used.

There might be some considerations around this TableCollection around table name -> table id mappings. There I forgot what the story is and I don't know what transactional considerations apply as tables get renamed. But in any case, this doesn't have to do with descriptors themselves.

**Comment by vivekmenezes** [comment]
@andreimatei TableCollection is holding a lot of stuff and I'm planning to add more :-) so perhaps we should just close this issue

**Comment by andreimatei** [comment]
Oh no :)
Any thoughts on the points, though? 
> First of all, if this structure is per-transaction and not per-session, then it's placed in the wrong place.
Also everything about the timestamp being sufficient.

Basically, perhaps except for uncommitted tables, why does the thing need to exist?

**Comment by vivekmenezes** [comment]
well I'm working on a change that's going to add uncommittedCreatedTables to this data structure. I thing the way this works is you use it as a dumping ground until it becomes unwieldy and then someone comes around and breaks it up and renews order. But I still think that doesn't warrant an issue.

**Comment by andreimatei** [comment]
The problem is that it's not clear (at least not to me) what stuff is dumped in this dumping ground. The last instance where I ran into this  is in relation with "internal statements" - when one executes something using the `InternalExecutor` in the context of a session, does the internal executor need to share the `TableCollection`? What if it further executes the statement in the context of the current txn? I've got no idea. Stemming for the fact that it's not clear to me why it exists in the first place. Any documentation you can add would be most valuable.

**Comment by lucy-zhang** [comment]
Closing this because it doesn't really reflect our current plans for the TableCollection anymore - I think the current plan is to move it into a separate leasing/caching-related package and have a more principled API for it, as a way to store leased objects and uncommitted objects. "Getting rid of it" is probably too strong. cc @ajwerner
