### ISSUE TITLE
perf: optimize Raft ticking of quiesced ranges 

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#17609]
After creating 1m mostly empty ranges on `sky` (each node contains ~15k ranges), the nodes are churning through 50% of the cpu on the machine and a significant fraction of that is Raft tick processing. Stats indicate that basically all of the ranges are quiescent.

<img width="1208" alt="screen shot 2017-08-11 at 8 20 42 pm" src="https://user-images.githubusercontent.com/6201335/29235983-944a9074-7ed2-11e7-9e63-1943f9e694d7.png">

[pprof001.svg.zip](https://github.com/cockroachdb/cockroach/files/1219341/pprof001.svg.zip)

Very strange to see the synchronization primitives so prominently. Ditto for `sync.Map`. 

Once Raft pre-vote is enabled, we can get rid of the call to `TickQuiesced`. Perhaps we can also avoid enqueueing the replica on the Raft scheduler as well. I doubt it is good that ticking shares the same scheduler resource as other Raft processing. Might be worthwhile to have a separate set of goroutines for ticking. 

Note the default tick interval is 200ms and we call an election after 15 missed ticks (making the Raft election timeout 3s). Perhaps we should increase the tick interval and reduce the timeout ticks. @bdarnell Can you remind me of the downsides to adjusting these values?

**Comment by petermattis** [comment]
#17612 is certainly exacerbating the problem here: we have 3x as many replicas as expected which means we're spending 3x as much time ticking.

**Comment by bdarnell** [comment]
> Note the default tick interval is 200ms and we call an election after 15 missed ticks (making the Raft election timeout 3s). Perhaps we should increase the tick interval and reduce the timeout ticks. @bdarnell Can you remind me of the downsides to adjusting these values?

The specified election timeout is a lower bound; the actual timeout is randomized between `N` and `2*N` ticks. Setting the tick interval to 1s and the election timeout to 3 ticks (for example)  would increase the risk of failed elections as two followers would be more likely to call their elections at the same time. There's also another tick-related value: we currently send a heartbeat every 5 ticks and would need to adjust that accordingly too. 

Changing the effective heartbeat interval or election timeout (as opposed to changing the number of ticks per heartbeat/election while leaving the overall time the same) is tricky to do without downtime.

**Comment by petermattis** [comment]
Still need to investigate adjusting the Raft tick settings.

**Comment by petermattis** [comment]
Once Raft pre-vote lands and we don't have to tick quiesced ranges, another optimization possibility here is to keep track of active replicas (which are usually a small fraction of the total replicas on a store) so that we only loop over the active replicas on each tick cycle. There are some locking challenges in doing this, but they don't seem insurmountable.

**Comment by petermattis** [comment]
I don't think there is anything left to do here for 1.1.
