### ISSUE TITLE
debug: Loading problem ranges fails with RangeNotFoundError

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#17614]
This is on sky, which certainly isn't in a happy place, but a debug page that's meant to find broken ranges probably shouldn't break because it found a broken range:

<img width="926" alt="screen shot 2017-08-12 at 12 27 11 am" src="https://user-images.githubusercontent.com/7085343/29237847-2bc1b500-7ef5-11e7-825f-3c07e6720cff.png">

@BramGruneir

**Comment by BramGruneir** [comment]
Interesting.  This Is clearly a deep internal error.  I'll take a look to see if I can track down where it failed.

**Comment by couchand** [comment]
@BramGruneir do you think this is still an issue?  I wonder if it's related to what I was seeing on the reg cluster a few weeks ago.

**Comment by BramGruneir** [comment]
I remember looking, but fixing this required changing how we do the range lookup and making the range visitors not fail if something is really amiss. (I clearly should have updated this issue with my finding, not sure why I didn't.) 

@couchand, did you notice this error on reg?

**Comment by couchand** [comment]
Per the above comment, closing.
