### ISSUE TITLE
[Bug] column names are always returned lowercased when explicitly targeted

### ISSUE THREAD

**Issue by wzrdtales** [cockroachdb/cockroach#17616]
# Foreword

This bug report is about an unexpected and probably unwanted behavior.

# Description

When requesting a column explicitly from a query it is being returned lowercased even when requested otherwise and also if aliased as well. The only exception where it gets returned correctly is when passing the column target quoted.

# Reproducing

### Execute

```sql
SELECT testId FROM table;
```

### Result

{ "testid": 12345 }

### Expectation

{ "testId": 12345 }

### Execute

```sql
SELECT testId AS testId FROM table;
```

### Result

{ "testid": 12345 }

### Expectation

{ "testId": 12345 }

### Execute

```sql
SELECT "testId" FROM table;
```

### Result

{ "testId": 12345 }

### Expectation

{ "testId": 12345 }

# Test results

- [ ] Passing unquoted column
- [ ] Passing unquoted column with alias
- [x] Passing quoted column

**Comment by jordanlewis** [comment]
Hi @wzrdtales,

Thanks for the report. This is actually expected and intended behavior - SQL identifiers are case-insensitive unless they're quoted.

**Comment by wzrdtales** [comment]
Okay @jordanlewis stepping in on this, as I can't completely agree. From a user perspective it is a clearly unexpected behavior, not questioning the SQL Standard though, but isn't handling it case-insenstive and returning inconsistently something different than what was requested (which is about the unexpected part).

But especially for aliases this should not be expected and also this is pretty inconsistent in other cases. For example if I do `SELECT * FROM` I do get the *correct* name back, while when I request the column explicitly I do not.

So I politely disagree and I do kite MySQL/MariaDB here, they **also** treat identifiers case insenstivie, but they return them correctly as the user was requesting them, just the real column name behind is handled case insensitive. So I think that this point is still worth the discussion if the current implementation could be considered incorrect or not. For my portion, this is my opinion, while I most strongly suggest that an alias should not be altered by the database to something else like what the user was requesting.

**Comment by wzrdtales** [comment]
Fair enough about the postgres point, I also just looked it up. I never was a postgres user before though :)

Inconsistent is the following:

You create a table with a column named helloIGotUppercase
The column is correctly named helloIGotUppercase everywhere you look
You get the column name correctly when requesting just everything from the table
And now you request just helloIGotUppercase and the database delivers you helloigotuppercase, here starts being inconsistent
Then you think ok strange lets alias it
Same stuff happens

Also I don't think that is really wanted, as completely not handling case sensitivity I would consider a very bad thing though. I was well aware about the fact that column names are **handled** case insensitive, but I never expected the database to return me something I did not asked for.

Let me explain how I stumbled over this, this may also partly explains the viewing angle:

I have a JSON Schema, for the purpose of doing some stuff just very quickly I just rawly throw in this JSON  schema as a TEXT column, unfortunately CRDB does not yet support JSON (can't wait for it though :) ). Now some time later I decided to clean up the mess and convert this JSON schema to real columns. All good, creating the columns and stuff, as we talk about JSON and especially in JS it is very widespread to write stuff like typeId, stuffId and so on and making heavily use of camelCase. Now when I convert this to columns, I naturally don't want to change this portion to something like stuff_id. So just moving it over and finally stumbling over it when the migration tasks suddenly fails and claims that it can't find any column that is named stuffId, b/c of course as I discovered I am forced to double quote names :)

**Comment by wzrdtales** [comment]
To be more exact on the consistency point: So basically the DB is not even returning the real column name anymore, but the name of the column passed in by the user and altered into the lower cased version.

**Comment by wzrdtales** [comment]
So neither the name the DB internally knows for that particular column, nor what the user requested is being returned. But instead what the database computed :)

**Comment by jordanlewis** [comment]
For the reasons I mentioned above, we're not going to fix this. Sorry! Quote your column identifier names.

**Comment by jkassismz** [comment]
yuck. database-level or connection-level option to do this would be nice. why does it need to be standard?

**Comment by wzrdtales** [comment]
@jkassismz 
b/c they decided to stick strictly to postgres protocol instead of independent. Probably has a few reasons, the biggest is probably that they do not need to develop the client portion themselves and followed by that compatibility for "a lot" of applications. In reality the latter is not true at all, I did not walked past a single application that was developed on top of postgres, that is even near to be compatible to cockroachdb. The reason for this is that for some reason devs that work with postgres tend to go for the `fancy` things. This means especially going kinda off standard with extensions and using all the fancy that is available in postgres, but not in cockroachdb. That is why I weighed the first reason higher than the second, b/c it is completely negligible for almost all applications in the wild.

**Comment by toha70** [comment]
@jordanlewis I tried with quoted Alias and still got a lower case results: 

SELECT distinct "db_dfd05429"."table_time_series_19_covid_combined_csv"."Lat" AS "19751c73-5e7e-46e9-80e5-55a8932ef207", COUNT("db_dfd05429"."table_time_series_19_covid_combined_csv"."Deaths") AS "b930b9a2-1685-4d81-bc97-3305e93fb1ec-Count" From "db_dfd05429"."table_time_series_19_covid_combined_csv"   GROUP BY "db_dfd05429"."table_time_series_19_covid_combined_csv"."Lat"   LIMIT 100000


Got this back: 
"19751c73-5e7e-46e9-80e5-55a8932ef207":"28.0339","b930b9a2-1685-4d81-bc97-3305e93fb1ec-count":"107"

so I guess even double quoting doesn't fix this issue.
