### ISSUE TITLE
distsql: memRowContainer always decodes rows, making lots of allocations

### ISSUE THREAD

**Issue by rjnn** [cockroachdb/cockroach#17655]
`memRowContainer` always decodes rows, since its based on top of `sqlbase.RowContainer`, which only stores raw `Datums`. We could lift the representation to store `EncDatumRows`, which could prevent unnecessary decoding. In particular, `memRowContainer` is used by `hashRouter` to buffer rows, which can cause needless decoding (for example, a `TableReader` routing by hash, which has the correct encoding for routing by hash, does not need to be decoded at all), churning lots of allocations.

**Comment by RaduBerinde** [comment]
It's not ideal to store lots of encoded datums; their encodings can be pieces of larger slices (e.g. the entire value of a KV) so they might cause us to hold on to a lot more memory than we account for. Also, unfortunately `EncDatum`s are currently huge (there are some other issues open to address that).

**Comment by jordanlewis** [comment]
Closing as wontfix, the plan is to move away from these containers toward the vectorized engine.
