### ISSUE TITLE
ui: add in ability to pause / cancel jobs from the admin UI

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#17658]
Original 1.1 suggestion is below:

![image](https://user-images.githubusercontent.com/5768024/29327469-3933264a-81bd-11e7-808e-2eba092a6e0c.png)

@benesch please add in your sketch? Thanks!!

cc @kuanluo

**Comment by benesch** [comment]
![2017-08-15 13 33 00](https://user-images.githubusercontent.com/882976/29327894-a959416a-81be-11e7-85b6-0a2f293594df.png)

Basically, I think we should create a modal dialog that pops up when you click on a row with all of the information from SHOW JOBS:

```
id                 | 271140301392478208
type               | RESTORE
description        | RESTORE tpch.* FROM 'azure://backup-test/benchmarks/tpch/scalefactor-1' WITH into_db = 'tpch1'
username           | root
descriptor_ids     | {55,56,57,58,59,52,53,54}
status             | succeeded
created            | 2017-08-15 16:50:53.300373+00:00
started            | 2017-08-15 16:50:53.320615+00:00
finished           | 2017-08-15 16:53:07.761062+00:00
modified           | 2017-08-15 16:53:07.761063+00:00
fraction_completed | 1
error              | 
```

The modal also feels like the right place for the "SQL to pause/cancel this job" pictured above. All of this is feasible for 1.1.

For 1.2, we should additionally include the information that's returned by BACKUP and RESTORE, namely:

```
rows		index_entries		system_records	bytes
86586082	562088471		0				17428920858
```

I think that would fit nicely in the modal too.

**Comment by kuanluo** [comment]
I like the modal idea! 

- What's the benefit of showing some of info (type, description, status, started, etc) twice in the popup? 
- From a UX perspective, clicking on the row isn't obvious. We could potentially still use the `...` circle?

**Comment by benesch** [comment]
You mean duplicating information that's already shown in the table? I figure the modal will cover those columns, so we need to reproduce them. I'm also a bit afraid that the `...` will require more engineering work than I have time for before 1.1. The existing table component has no way to render a button to the right of the row.

Thinking about it more, for 1.1, perhaps we could make the jobs table function like the node list table? That is, the job description would be a link that would take you to a job details page. That would be wonderfully simple to implement.

**Comment by kuanluo** [comment]
I hear your concern about rendering the button outside of the table, but I do think it's better to show the command to pause/cancel the SQL on the same page. Clicking into a details page seems to add an unnecessary step. 

Another idea is to add a column "More" and clicking on the link in the cell to show the modal?

**Comment by dianasaur323** [comment]
I'm on the same page with @kuanluo in that having a modal would be better than moving over to a new page, since that new page will look a bit sparse. I also agree that we might not want to duplicate that much information, since we expect users to click in to take action on that information. If we don't view the information as actionable, we may not need to include it in the modal. Adding a new column instead of a button to the right of the table sounds fine to me.

**Comment by dianasaur323** [comment]
Another edge case here: apparently we can't pause / cancel schema changes yet, so if they do appear in the jobs stable, we need some kind of equivalent tooltip that tells users that we don't support cancellation / pausing of schema changes yet.

**Comment by dianasaur323** [comment]
as discussed, since we don't support pause / cancel schema changes yet, we can't ship the ability to pause / cancel all jobs. Instead, we'll punt this feature for 1.2 when we do support schema change pause and cancellation, and only message that pause / cancellation is working for backup / restore.

**Comment by piyush-singh** [comment]
We now have an interface we can use to pause and cancel jobs from the UI. We should add ways to do this directly in the UI. We will need to ensure Authz is working correctly for these commands. For more details, reach out to Michael or DT.
