### ISSUE TITLE
ui: better "no results" page

### ISSUE THREAD

**Issue by kuanluo** [cockroachdb/cockroach#17666]
Our current "no results" page is a bit under-designed. Perhaps we can make it more interesting? One idea below:

Current | Proposal
------------ | -------------
![image](https://user-images.githubusercontent.com/1486483/29330290-faf37058-81b5-11e7-951d-89dd5228ea02.png) | 
![no results](https://user-images.githubusercontent.com/1486483/29331486-ce27d998-81b9-11e7-9f87-aa2e84d1c039.png)

cc: @benesch @dianasaur323

**Comment by dianasaur323** [comment]
I like this new design, but since @mrtracy is strapped for time finishing up some features, going to aggressively move this into 1.2

**Comment by dianasaur323** [comment]
cc @nstewart this is the first outstanding issue that no results looks weird.

**Comment by BramGruneir** [comment]
@kuanluo can you send me the no results image please, spider and text included!

**Comment by kuanluo** [comment]
@BramGruneir I just slacked it to you. Github doesn't support SVG files. :)
