### ISSUE TITLE
ui: Table column header toggle ux polish

### ISSUE THREAD

**Issue by kuanluo** [cockroachdb/cockroach#17664]
Two minor visual nits:

1. On any table, one column header should always be highlighted, so this shouldn't happen:
![image](https://user-images.githubusercontent.com/1486483/29329778-36dcd606-81b4-11e7-9863-15d5cedc347f.png)

Essentially, user shouldn't be able to deactivate column header A by clicking on it. A would be deselected if someone clicks on B automatically. 

2. The little triangle in the table header is a different ratio comparing to that in the dropdown buttons. Let's stick with the dropdown button triangle.

cc: @dianasaur323

**Comment by dianasaur323** [comment]
Thanks @kuanluo. I know I mentioned that 1.1 was fine, but since we are aggressively trying to free up development time, and this isn't mission critical, let's do it in 1.2.

**Comment by ECourant** [comment]
Just wanted to confirm that this issue is still relevant? I see it was references in November as still being needed but wanted to be sure.
