### ISSUE TITLE
distsql: expose knob for limiting query disk space usage

### ISSUE THREAD

**Issue by arjunravinarayan** [cockroachdb/cockroach#17663]
Currently, temporary disk space usage is hardcoded to 25% of total disk space. This is reasonable, but results in queries taking a long time to fail, when they are planned pathologically. Case in point: [TPC-H query 9](https://github.com/cockroachdb/loadgen/blob/master/tpch/query9.go) is a 6 way join. The intention of the query is to suss out if we are ordering our joins cleverly, to keep the intermediate state to a manageable level. Of course, we are not, which currently results in us generating gigantic intermediate cross-join state, until we hit the disk accounting limit and error out.

On a recent run on @asubiotto's laptop, it generated 62 gigabytes of state, running for 2 hours, before hitting the limit. [1] This gives us the sense that this knob could be tuned down by default, to give more responsive answers to pathological cross-join queries, and we can allow users to turn this up if they're explicitly running large queries with very large working sets. We could make this knob an environment variable, or a cluster setting.

As an aside, it is worth noting that bad things happen if a Cockroach node hits 100% disk space utilization. And with the current 25% limit, a 75% full disk appears relatively safe to an operator, but is in fact at the risk of a single adversarial query killing the entire cluster (which distsql will helpfully schedule on all nodes).

[1] As an aside, this is impressive throughput!

**Comment by RaduBerinde** [comment]
25% seems excessive to me, especially if the disks are large. Maybe there should be both a percentage and a hard limit (e.g. 10GB).

**Comment by arjunravinarayan** [comment]
I agree that there should be a hard limit as well as a percentage, and your numbers seem sane to me (whichever is smaller?). We also need to expose this as a knob, and also perhaps show the amount of space used by a query in the `crdb_internal.cluster_queries` table.
