### ISSUE TITLE
storage: scatter acceptance test

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#17660]
Per [a comment](https://github.com/cockroachdb/cockroach/pull/17644#issuecomment-322537278) in #17644, we need an acceptance test for scatter. One option is to bundle the split+scatter test that uncovered #17644 into an acceptance test:

> Yes, scatter needs better testing. The test would essentially be `kv --concurrency 512 --splits 1000000 --max-ops 1`. Question is how to determine whether scatter worked well. I suppose we could look at the number of replicas vs ranges and the balance across the cluster.

**Comment by petermattis** [comment]
This shouldn't be difficult to do, but it is not necessary to do in 1.1. Hopefully we'll get to it in September.

**Comment by petermattis** [comment]
Let's make this into a nightly test.

**Comment by benesch** [comment]
Moving to 2.1. We've survived this long without a scatter nightly; we can survive a little longer.

/ping @danhhz who's looking for tests to write, though.

**Comment by petermattis** [comment]
@a-robinson Re-assigning to you given your work in this area and the small likelihood either @benesch  or I will get to this any time soon.
