### ISSUE TITLE
internal/client: db.Txn cannot detect wrapped HandledRetryableTxnErrors

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#17667]
Discovered in #17656. In short, if `txn.Op` below returns `HandledRetryableTxnError`, the `errors.Wrap` call will (incorrectly) prevent the transaction from being retried.

```go
db.Txn(ctx, func(...) error {
    if err := txn.Op(...); err != nil {
        return errors.Wrap(err, "whoopsie")
    }
})
```

The solution is probably an `errors.Cause` somewhere in `internal/client`.

**Comment by danhhz** [comment]
cc @bdarnell who was opposed to this the last time I asked. This is easy enough to get wrong (and has happened in practice at least 3 times) that I think we should revisit that decision

**Comment by bdarnell** [comment]
Related: cockroachdb/cockroach-go#16

My opposition to this is weak; given our experience we should probably make the change in both places. (although it's unfortunate to introduce the new dependency in the public client package)

**Comment by knz** [comment]
Could this be the cause of #17836 / #17698?
Andrei please triage

**Comment by andreimatei** [comment]
I don't think this has anything to do with those two bugs - that's about a retryable error, this is about the lack of a retryable error.

For this wrapping, I'd be in favor of wrapping retryable errors keeping the retryable character.
For the external cockroach-go lib, adding support for the pkg/errors package while that's not in the standard library seems arbitrary to me.

**Comment by bdarnell** [comment]
Yes, pkg/errors is arbitrary and non-standard (despite someone's clever squatting on a good github account name). But I still think cockroach-go should be consistent with our own internal transaction functions. Currently, users of cockroach-go are required to return errors without wrapping in any way. If that's good enough for our users, why isn't it good enough for us?

**Comment by andreimatei** [comment]
I happen to think it's good enough for us too :)
But if others think it's not, we have the luxury of a controlled environment and we already depend on this pkg/errors package. If cockroach-go uses the package, would it vendor it?
