### ISSUE TITLE
log,reporting: crash_reporting.go logs "a panic has occurred" but the server doesn't stop

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#17679]
Run `select crdb_internal.force_panic('foo')` in client.

Observe:

- the message "a panic has occurred" is shouted to stderr, printed to the log
- the client connection drops;
- however, the server continues to run.

**Comment by knz** [comment]
cc @dt @bdarnell

**Comment by knz** [comment]
This doesn't reproduce reliably. I think it depends on the network settings. If the reporting server cannot be reached or there's some kind of TCP blockage, then the reporting function hangs and the panic never propagates. Is this OK?

**Comment by tschottdorf** [comment]
Seems better to fire off a goroutine and have the caller goroutine wait for a (generous) timer or the panic to be returned, whichever happens earlier.

**Comment by knz** [comment]
Actually happens also in 1.1. May be related to our sentry credits running out.
