### ISSUE TITLE
ui: add de / re commissioning nodes to event log

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#17677]
We want to surface important events in the event log - we currently include node joins, and should also include de / re commissioning events. 

This is the final outstanding item in #6198 (comment).

**Comment by cuongdo** [comment]
@benesch Are you going to get to this by 1.1?

**Comment by benesch** [comment]
Welp, seems unlikely.

**Comment by a-robinson** [comment]
Adding new event log events is actually fairly easy. I don't think I'll have time today given the investigations I'm in the middle of, but if we'd be open to cherrypicking it Monday or Tuesday we could probably get it in. Just depends on how important it is.

**Comment by dianasaur323** [comment]
I'm not sure this will be important enough to cherry pick into the release branch... Perhaps we should just punt to 1.2.

**Comment by benesch** [comment]
Turns out I have a half-finished branch. Trying to finish this up right now.
