### ISSUE TITLE
storage: Disk FractionUsed is a bad metric for clusters without much data in them

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#17691]
On new or small clusters, our replica balancing is pretty hamstrung by the semantics of the `Capacity` and `Available` metrics that are included in each store's gossiped `StoreCapacity`.

`Capacity` and `Available` respectively refer to the total amount of disk space on the store's disk and the amount of that disk space that is unused. That's fine if Cockroach's data makes up the majority of the used space on each disk, but is bad when most of that used space is composed of non-CockroachDB-owned files (like, for example, the OS).

This previously has been a good definition because we only really used them to identify if a node was too full to give more data to, not to determine how full it was in general.

Stats-based rebalancing adopted these fields to try to balance the `FractionUsed` of each store, but in practice this doesn't work well because when a cluster is new, cockroach's data will often only account for a minority of the space used on each disk. Thus, using `FractionUsed` as a signal is not good -- it will result in inaction if each node is pretty balanced in non-cockroach disk usage, or will result in a bias towards balancing to certain nodes if some have less non-cockroach disk usage than others.

While the definition of `Available` seems good, stats-based rebalancing should switch to defining capacity more like:

Capacity = (total capacity of disk) - (non-cockroach disk usage)
where
(non-cockroach disk usage) = (total disk usage) - (disk usage of everything in cockroach's store directory)

It seems like this definition change may actually be safe to use in the existing `Capacity` field. This aligns pretty much exactly with @mrtracy's existing suggestions in #13548.

**Comment by a-robinson** [comment]
There's also the follow-up point that we're balancing replicas based on just their `LiveBytes` field. Should we also be including `IntentBytes` and `SysBytes` in those calculations?

**Comment by a-robinson** [comment]
Also, graphs that show the cause/effect of this:

<img width="1570" alt="screen shot 2017-08-16 at 11 32 15 am" src="https://user-images.githubusercontent.com/7085343/29372664-c6440d6c-8279-11e7-908d-543eb63dbf54.png">

<img width="1565" alt="screen shot 2017-08-16 at 11 33 22 am" src="https://user-images.githubusercontent.com/7085343/29372668-caae1cbc-8279-11e7-960b-3d94cd0dbcb4.png">

The first screenshot shows that a human would want to rebalance ranges in this context (there are a few ranges receiving all the QPS, not just one). The second screenshot shows why the allocator isn't doing so -- because range count and fraction of disk used are still balanced, even though live bytes and writes per node isn't even close to balanced.

**Comment by cuongdo** [comment]
Yes, I encountered this when I previously started working on the allocator. This may affect first impressions of our software.

**Comment by cuongdo** [comment]
(I had also previously removed this metric from consideration by the allocator because of this.)

**Comment by dianasaur323** [comment]
We could do something in 1.2? The correlated UI issue is marked for 1.2.
