### ISSUE TITLE
sql: go postgres driver's syntax for isolation level is unsupported

### ISSUE THREAD

**Issue by arjunravinarayan** [cockroachdb/cockroach#17709]
It appears that the Go SQL postgres driver, when an isolation level is explicitly provided, issues some weird syntax, namely `BEGIN TRANSACTION SET ISOLATION LEVEL SERIALIZABLE READ WRITE`. That `READ WRITE` at the end is throwing off Cockroach. It works fine on Postgres.

- What did you do?
```
package main

import (
	"database/sql"

	"net/url"

	"context"
	"fmt"

	"github.com/cockroachdb/cockroach-go/crdb"
)

func main() {
	dbURL := "postgresql://root@localhost:26257?sslmode=disable"

	parsedURL, err := url.Parse(dbURL)
	if err != nil {
		panic(err)
	}

	db, err := sql.Open("postgres", parsedURL.String())
	if err != nil {
		panic(err)
	}

	err = crdb.ExecuteTx(context.Background(),
		db,
		&sql.TxOptions{Isolation: sql.LevelSerializable},
		func(tx *sql.Tx) error {
			rows, err := tx.Query("SELECT * FROM tpcc")
			if err != nil {
				panic(err)
			}
			for rows.Next() {
				cols, err := rows.Columns()
				if err != nil {
					panic(err)
				}
				fmt.Println("%+v", cols)
			}
			rows.Close()
			return nil
		},
	)
	if err != nil {
		fmt.Print(err)
	} else {
		fmt.Println("Things seem to work")
	}
}
```
- What did you expect to see?
```
> ./isolation
Things seem to work
```
- What did you see instead?
```
> ./isolation
pq: syntax error at or near "read"
BEGIN ISOLATION LEVEL SERIALIZABLE READ WRITE
```

cc @jordanlewis for approval on adding this syntax support to Cockroach. If you approve, I will add support to accept this syntax (please don't go ahead and do it yourself, I want to do the fix).

**Comment by jordanlewis** [comment]
Go ahead - I believe we already support a very similar form, but not the `READ WRITE` part. I'm not sure what that means. Check the `txn` logic test for an example of what we do support.

**Comment by andreimatei** [comment]
I think we should support `WRITE` and `READ WRITE`, but I'm not sure about `READ` (if we're not enforcing anything to be read-only)
