### ISSUE TITLE
ui: surface usage of external storage for distSQL queries

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#17703]
With the new capability of using external storage to process intermediate distSQL query results, we should consider if we want to surface this in the admin UI. I think the answer is yes, as it is an important resource utilization metric.

**Comment by vilterp** [comment]
Several different levels on which you can show this:
- Time series across all queries
- Average on a query fingerprint (i.e. group of queries which are the same when literals are removed)
- As part of the query plan view for an individual query.
  - Postgres does this: if you do an `EXPLAIN ANALYZE` on a query that spills to disk, it will say on that planNode how much disk was used. (Will do the same for RAM I believe; e.g for sort nodes or hash joiners)

**Comment by dianasaur323** [comment]
Yeah, I was reading about PostgreSQL tools, and it would be nice to be able to track how many queries flow over into external storage on a per query basis. We should talk about this in the context of the larger query analysis work we are doing

**Comment by piyush-singh** [comment]
@vilterp we now capture this on EXPLAIN ANALYZE (DISTSQL) right? Alfonso's annotated plans have the amount spilled to disk for each processor. Will close this if that is indeed the case

**Comment by vilterp** [comment]
Yes, I think `EXPLAIN ANALYZE` (you don't need to add the `(DISTSQL)` anymore) addresses this.
