### ISSUE TITLE
sql: hide internal error details from client sessions

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#17714]
Extends/supersedes #5452.

See discussion with @dt and myself as starting point: https://github.com/cockroachdb/cockroach/issues/5452#issuecomment-301552941

- [ ] make all errors generated by the SQL packages themselves carry a PG error code
  - [ ] starting with `sql/parser` #17708.
- [ ] extend pgwire to `log.Error()` all errors generated that do not carry a PG error code
- [ ] create and use a new pgerror.Wrap/Wrapf to add a PG error code to all the errors generated by "leaf" dependencies of sql: `apd`, `time`, `uuid`, etc. To achieve this:
  - [ ] instrument the call to log.Error added at a previous step to detect+record any error that does not have a PG error code; run this in the `sql` tests: `make test PKG=./pkg/sql/*` and `make testlogic` to discover most (all?) unhandled external errors that can be generated in SQL
  - [ ] avoid these log.Error invocations by adding the missing pgerror.Wrap calls
- [ ] for every error that bubbles up to pgwire without a PG code, migrate the error *message* to the *details* field in pgwire, and replace the pgwire error title by "internal error"
- [ ] tally these errors without PG error code and report them to our reg server / sentry

**Comment by knz** [comment]
cc @cockroachdb/sql-wiring @jordanlewis @justinj

**Comment by jordanlewis** [comment]
While this isn't done by name, the work has evolved in a separate direction and is in a much better place than Aug 2017, so closing.
