### ISSUE TITLE
sql: Substitute TRUNCATE for DELETE without WHERE clause

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#17713]
To empty a whole table people know to use DELETE without a WHERE clause more often / better than to use TRUNCATE.

However currently DELETE on CockroachDB is always very slow, and TRUNCATE is rather fast (or at least appears to be fast: it operates by renaming the current table, creating a new table, and dropping the old table asynchronously).

To improve the apparent performance of DELETE without a WHERE clause, an optimization can be applied:

- DELETE without WHERE clause and RETURNING NOTHING is specified: run TRUNCATE instead
- DELETE without WHERE clause and no RETURNING clause specified: run `COUNT(*)` first (can be distributed), then TRUNCATE, then return result of COUNT(*)
- DELETE without WHERE clause and RETURNING (not NOTHING): run plain SELECT, stream results, then issue TRUNCATE

**Comment by petermattis** [comment]
Is this feasible given that `DELETE` is transactional while `TRUNCATE` isn't?

**Comment by knz** [comment]
what is not transactional about truncate?

**Comment by petermattis** [comment]
It operates as a schema change. I'm not familiar with the new implementation and don't know if the results of the `TRUNCATE` would be visible on the next statement in the same transaction. And what is the interaction with `ON DELETE CASCADE`?

**Comment by jordanlewis** [comment]
`TRUNCATE` should not be permitted if there are any foreign key constraints on the table, unless `TRUNCATE CASCADE` is specified. If `TRUNCATE CASCADE` is specified, then all linked tables should be truncated in the same operation. I'm not sure if we currently handle that.

**Comment by knz** [comment]
So the current behavior is implementing a RENAME for TRUNCATE, which is transactional (and visible in the same txn). 

@vivekmenezes when you're back can you check this last comment by @jordanlewis and see if the current behavior is safe. Then perhaps you can comment on feasability.

**Comment by dt** [comment]
@knz pg is similar -- `TRUNCATE` is fast specifically because it doesn't do row-level MVCC, while `DELETE` does. Also, as @jordanlewis points out, when you `TRUNCATE CASCADE`, it _truncates_ the dependent tables, whereas when you `DELETE ... CASCADE`, it row-by-row deletes only those rows in other tables which would become orphans.

**Comment by dt** [comment]
@jordanlewis we do handle `TRUNCATE CASCADE`

**Comment by knz** [comment]
Hm the point about MVCC is the one that caught my attention the most in this story. Just that point alone makes my initial proposal completely unsound. Thanks for the input on the other points too everyone!
