### ISSUE TITLE
release: v1.0.5 - 20170824

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#17715]
Candidate SHA: 6255bbf89152218db590c9838976aa8780e4770e
Deployment status: blue, omega, adriatic, cerulean

[Release process checklist](https://github.com/cockroachdb/cockroach/wiki/Release-Process)

Prep date: 2017-08-17

- [x] [Pick a sha](https://github.com/cockroachdb/cockroach/wiki/Release-Process#pick-sha), fill in `Candidate SHA` above.
- [x] [Deploy to test clusters](https://github.com/cockroachdb/cockroach/wiki/Release-Process#deploy-to-test-clusters)
- [x] fill in `Deployment status` above
- Keep an eye on clusters until release date.

Release date: 2017-08-24

- [x] [Check cluster status](https://github.com/cockroachdb/cockroach/wiki/Release-Process#check-cluster)
- [x] [Tag release](https://github.com/cockroachdb/cockroach/wiki/Release-Process#tag-release)
- [x] [Trigger release build](https://github.com/cockroachdb/cockroach/wiki/Release-Process#trigger-build)
- [x] [Check binaries](https://github.com/cockroachdb/cockroach/wiki/Release-Process#check-binaries)

- For stable releases only:
  - [x] Update the [Homebrew Formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/cockroach.rb)
  - [x] Update the image tag in our [Kubernetes configurations](https://github.com/cockroachdb/cockroach/wiki/Release-Process#kubernetes-configurations)
  - [x] Update the version label in our [Red Hat Atomic Docker image](https://github.com/cockroachdb/cockroach/blob/master/build/deploy/rhel/Dockerfile). For major/minor releases, also update the documentation link in the [image's help file](https://github.com/cockroachdb/cockroach/blob/master/build/deploy/rhel/help.1)
  - [x] Announce version to the [registration cluster](https://github.com/cockroachlabs/production#publishing-a-new-release-version)

- [x] Update docs
- [x] External communications for release
- [x] File issue for next release and assign to release coordinator

**Comment by knz** [comment]
cc @bdarnell for release notes PR

**Comment by jordanlewis** [comment]
Assigning @swatikumar16 to close when all communications are finished.
