### ISSUE TITLE
ui: Intermediate page with error message always loads first when going to range debug page

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#17744]
On indigo, whenever I try to load a range debug page by changing the range ID in the URL and reloading the page, it always flashes this error page on the screen for about a second before redirecting to the actual page:

Intermediate page:
<img width="404" alt="screen shot 2017-08-17 at 5 36 53 pm" src="https://user-images.githubusercontent.com/7085343/29434881-bf73836a-8372-11e7-9590-046334954c2f.png">

End page:
<img width="699" alt="screen shot 2017-08-17 at 5 37 05 pm" src="https://user-images.githubusercontent.com/7085343/29434882-c1f379c4-8372-11e7-84e0-3c08cb2d2dd5.png">

This happens every time when I switch back and forth between the page for range 15 and the page for range 16

**Comment by a-robinson** [comment]
And for what it's worth, indigo is currently running aec9e343759a6528ae317fff8866e1936959e322 plus #17733.

**Comment by BramGruneir** [comment]
Sounds like we're handling a case of still loading as an error, I'll take a look.
