### ISSUE TITLE
settings: unable to change default for trace.debug.enable

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#17759]
If I change the default for `trace.debug.enable` (in the code), net-trace debugging is not enabled when I start a cluster. The `Tracer.Reconfigure` callback does not seem to be called except when the value changes. Perhaps this isn't a problem in practice, but it sure was surprising that it isn't called once at startup.

**Comment by RaduBerinde** [comment]
This is even more serious for `COCKROACH_TEST_LIGHTSTEP_TOKEN` env var which will be effectively ignored.

@tschottdorf I think we just need to call `tracingOnChange()` once in `MakeClusterSettings`, after we register the settings.

**Comment by petermattis** [comment]
@RaduBerinde Does this need to be fixed for 1.1?

**Comment by RaduBerinde** [comment]
Ah, I'm pretty sure #18001 already fixed this. I'll verify before closing.

https://github.com/cockroachdb/cockroach/blob/master/pkg/util/tracing/tracer.go#L146

**Comment by RaduBerinde** [comment]
Changing the default for settings like the lightstep trace collector works as expected. 

Note that changing the `trace.debug.enable` default doesn't work anymore since #17944 (it's true by default and gets disabled after the cluster is setup).
