### ISSUE TITLE
build: make protobuf requires internet access

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#17752]
It's hardly the end of the world, but is there an easy way to make building our protocol buffers not require internet access? If I change a proto (e.g. by adding a new enum value to `storage/log.proto`) and try to run `make protobuf` without being connected to the internet, it always hangs on an npm command:

```
⸨░░░░░░░░░░░░░░░░░░⸩ ⠧ normalizeTree: sill install loadCurrentTree
```

I also got it hung in this other place once when I disconnected from the internet while `make protobuf` was in the middle of running:

```
⸨    ░░░░░░░░░░░░░░⸩ ⠴ fetchMetadata: sill mapToRegistry uri https://registry.npmjs.org/taffydb
⸨    ░░░░░░░░░░░░░░⸩ ⠇ fetchMetadata: verb afterAdd /Users/alex/.npm/marked/0.3.6/package/package.json written
```

Connecting to the internet fixes things. I don't remember it having always been this way.

cc @cockroachdb/build

**Comment by benesch** [comment]
I'm pretty sure this is due to a bug in protobuf.js (https://github.com/dcodeIO/protobuf.js/issues/716). We very intentionally run `yarn install`, which will avoid hitting the network if all deps are satisfied, but `pbjs` runs `npm install` behind our back. It's pretty terrible.

**Comment by a-robinson** [comment]
This works for me now.
