### ISSUE TITLE
storage: overabundance of directories in auxiliary

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#17769]
After creating hundreds of thousands of ranges on a cluster, I noticed the `auxiiliary` directory use for side-loaded storage contained hundreds of thousands of empty directories. Do we have to create the side-loaded storage directory for a replica if it is never used? I have mild performance concerns about having so many entries in a single directory, but mostly this is just an aesthetic issue.

**Comment by bdarnell** [comment]
We want to support more than 50k ranges per store; historically, common file systems have had hard limits that prevented that many subdirectories of one parent directory (ext3 had a limit of 32k; early versions of ext4 had a limit of 64k although this appears to have been lifted well before the earliest kernel version we support). It looks like the major filesystems today don't impose these limits, but it might still be worth sharding these directories before the 1.1 release while we still can do it easily. (only creating the directories when non-empty would help, but a large RESTORE could still give us a huge number of non-empty auxiliary directories)
