### ISSUE TITLE
pgwire+sql: support the `datestyle` session parameter

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#17779]
Reported on https://forum.cockroachlabs.com/t/odbc-and-cockroachdb/779/3

The pg ODBC driver attempts to set several session parameters including `datestyle`, which is not yet supported by CockroachDB.

We should look at the default value in pg and accept at least this default value (as a no-op) instead of returning an error. Then check if that is sufficient to enable ODBC compatibility.

**Comment by dianasaur323** [comment]
cc @nstewart for prioritization

**Comment by bdarnell** [comment]
Duplicate of #16452 

I think this was fixed for 1.1 with #16557, although issue #16452 has not yet been closed. Can someone verify that this works with a 1.1 alpha?
