### ISSUE TITLE
build: build broken on FreeBSD CURRENT, with clang 5.0.0

### ISSUE THREAD

**Issue by krionbsd** [cockroachdb/cockroach#17773]
Here is the build on FreeBSD:
http://pkg.krion.cc/data/12amd64-default/2017-08-20_14h14m52s/logs/errors/cockroach-1.0.4.log

Do you have any workarounds?

**Comment by benesch** [comment]
You might be able to work around it with:

```
CXXFLAGS=-Wno-unused-lambda-capture make build
```

You could also try building `master`, which uses an updated RocksDB which might not have that problem.

**Comment by knz** [comment]
I am currently successful building crdb 2.1 on freebsd-current, so closing this.
