### ISSUE TITLE
Separate `stores` types

### ISSUE THREAD

**Issue by jspc** [cockroachdb/cockroach#1777]
I can't see if this exists with a ten minute look through; if it does I'd appreciate a link or pointer.

It'd be very handy to be able to manually specify different stores for different parts of the schema/ different schemata and for different types of data. Consider the oracle split of tablespace,indexspace, log.

This should allow for fine grained disk tuning on the host volumes- I can have space optimised for random read for indices, random write for tablespace, append-only for loggy/profiley stuff etc.

**Comment by spencerkimball** [comment]
This is definitely allowed. In the previous KV-oriented API, this was done with zone configurations. In the new structured API, this will be done on a per-table basis. You'll have complete customizability including which types of stores (hdd or spinny disk, or arbitrary classifications) as well as which types of nodes (geographic location per-replica, as well as arbitrary node classifications, such as whether the node has a GPU, for example).
