### ISSUE TITLE
storage: Add an index on RangeID to the rangelog

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#17781]
Otherwise, retrieving the log for just a single range could become problematic in large clusters such as in our recent 1M range testing.

**Comment by petermattis** [comment]
This probably isn't urgent. On a cluster with 250k ranges, `show testing_ranges from table system.rangelog` shows 6 ranges. Scaling that up to 1m ranges in the cluster would result in 24 ranges for `system.rangelog`. Doing a scan over 24 ranges isn't great, but distsql helps.
