### ISSUE TITLE
storage: Normalize the range log table to pull info out of JSON column

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#17780]
This is far from urgent, just tracking a concern brought up in #17755 that we're putting a lot of extra info about rangelog events into a single json column. This may be ok once we support json, but it's pretty clunky for now, and keeps us from indexing on any of the info inside.

**Comment by petermattis** [comment]
Indexing the info inside the json column isn't terribly interesting to me (because what would we index). The bigger downside is the inability to query based on the contents of the json column. Definitely doesn't seem urgent.

**Comment by vilterp** [comment]
Filed #20418 now that we have JSON
