### ISSUE TITLE
sql: support ON DELETE SET NULL on foreign key constraints

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#17803]
Requested on Gitter by @somecallmemike. Used in some Sequelize use case.

This is comparatively much easier than ON DELETE CASCADE.

cc @cockroachdb/sql-language

**Comment by somecallmemike** [comment]
The default behavior in Sequelize when setting up relationships appears to set the column up with "ON DELETE SET NULL ON UPDATE CASCADE", so this should be handled by cockroach if Sequelize is being promoted as a supported client.  

Here is the details of how Sequelize was setup and the full error:

Running on top of the latest version (1.0.4) and getting the error 'unimplemented at or near "null"'

`
Executing (default): CREATE TABLE IF NOT EXISTS "users" ("id" SERIAL , "first_name" VARCHAR(255) NOT NULL, "last_name" VARCHAR(255) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "companyId" INTEGER REFERENCES "companies" ("id") ON DELETE SET NULL ON UPDATE CASCADE, PRIMARY KEY ("id")); Unhandled rejection SequelizeDatabaseError: unimplemented at or near "null"
`

My Sequelize config looks like this:

`
const Company = Conn.define('company', {
    id: {
        type: Sequelize.INTEGER,
        primaryKey: true
    },
    name: {
        type: Sequelize.STRING,
        allowNull: false
    }
})

const User = Conn.define('user', {
    id: {
        type: Sequelize.INTEGER,
        primaryKey: true
    },
    first_name: {
        type: Sequelize.STRING,
        allowNull: false
    },
    last_name: {
        type: Sequelize.STRING,
        allowNull: false
    }
})

Company.hasMany(User)
User.belongsTo(Company)
`

It was complaining about the NULL next to the ON DELETE.

**Comment by benesch** [comment]
Sorry you're running into this, @somecallmemike. This has been previously discussed on the cockroach-sequelize repo: https://github.com/cockroachdb/sequelize-cockroachdb/issues/10. As a temporary workaround, you can try:

```
Company.hasMany(User, { onDelete: 'restrict', onUpdate: 'restrict' });
```

**Comment by somecallmemike** [comment]
Unfortunately this also errors out with `error: unimplemented at or near "restrict"`.

**Comment by benesch** [comment]
Ah, sorry, didn't realize you were running a stable release. The `restrict` trick will only work with v1.1. If you don't mind running an unstable alpha release, we do publish v1.1 binaries: https://www.cockroachlabs.com/docs/dev/install-cockroachdb.html.

**Comment by cuongdo** [comment]
This will be one of Solon's starter projects.

**Comment by cuongdo** [comment]
@BramGruneir this is a good place to get your feet wet on the path to supporting `ON DELETE CASCADE`.

**Comment by benesch** [comment]
This is fixed thanks to @BramGruneir! https://github.com/cockroachdb/cockroach/issues/14848#issuecomment-363870833
