### ISSUE TITLE
storageccl: AddSSTable complains about mismatched end key

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#17819]
running tpch line item SF 10 import:
```
addsstable [/Table/59/1/11018023/3/0,/Table/59/1/11036803/2/0/NULL):
verifying sstable data: key /Table/59/1/11024007/2/0 not in request range
[/Table/59/1/11018023/3/0,/Table/59/1/11024007/2)
```

Generated/Imported using this runbook: https://docs.google.com/document/d/18Gls6c3dyUuoiUc1zP6QnBp52U7hWiviB54n0E_oO5s/edit

**Comment by dt** [comment]
Some investigation so far: this is the verify call done by addSSTable, the start/end are computed by for the batch, not passed in by the csv code so, uh... scary?

Going to add a log of `batchEndKey` to `sstBatcher.Finish` and try to repro again.

**Comment by danhhz** [comment]
I suspect this is going to be exceptionally hard to repro. Leaving the issue open but don't think there's anything to be done for 1.1

**Comment by dt** [comment]
@mjibson just saw this again in #19399:
```
importing 324 ranges: addsstable [/Table/56/9/2/20/289690669019889664/0,/Table/56/9/3/12/289690135848779776/0/NULL): verifying sstable data: key /Table/56/9/2/63/289688124228730880/0 not in request range [/Table/56/9/2/20/289690669019889664/0,/Table/56/9/2/63/289688124228730880)
```

**Comment by dt** [comment]
so reading though the code again, the bounds printed in the `addsstable` prefix of the message are the start and end from `evalImport`'s batcher, which are what get passed to the `AddSSTable` call, and I would expect to match what we then pass to `verifySSTable` in `evalAddSSTable`, where we print them into the error again. The fact that the end key has changed, and is smaller, really _looks_ like the request got split, [i.e. by `pkg/kv.truncate`](https://github.com/cockroachdb/cockroach/blob/master/pkg/kv/batch.go#L84).

**Comment by dt** [comment]
@tschottdorf Does it actually make sense to split an AddSSTableRequest? off the top of my head, that seems wrong, unless process the sst to only include the updated range? IIRC, we don't do that though?

**Comment by tschottdorf** [comment]
I think you're correct in that it only makes sense if we also clip the key range that is actually ingested. Alternatively, you could add capability to return errors from `truncate` and have the import machinery track the key ranges that are required through these errors. The former looks preferable: though it sends a bit more over the network, it seems more "straightforward".

**Comment by dt** [comment]
at the very least, if we don't split / limit the ingested SST, I'd at least like to assert that local == true in truncate and error otherwise.

**Comment by tschottdorf** [comment]
Yeah, that's the nuclear option, but that would tear down the whole import, right? I think it's fairly reasonable to assume that ranges would split, given that restore is supposed to be resumable, but a range that has once seen data might just split. Also this would be super likely if you were to import into a keyspace that has a smaller target range size than the backup.

**Comment by dt** [comment]
yeah, agreed though currently blows up the import anyway (when the sst doesn't match) and moving it up to the sending side would just catch it sooner. But handling it gracefully is obviously nice.

that said, this _shouldn't_ be expected, even with different target range sizes: we're already iterating an *assigned key range* of a backup SST to produce this ingestion SST in `evalImport`, with the intent that our assigned bounds produce an SST that maps 1:1 with our range. If our restore cluster has a smaller target range size, we *should* just be assigning bounds accordingly when sending the `ImportRequest`s, so that the ingestion SST produced in `evalImport`  is the right size, rather than expecting to split it again after `evalImport` before `evalAddSSTable`. 

So while we _can_ handle it gracefully and probably should, it isn't expected.

Anyway, I'm going to try stressing this with restores on cluster with much smaller target range size than the backup cluster to see if that does indeed tickle it, and if so, take a look at how we generate import request ranges.

**Comment by dt** [comment]
One annoying point is that i don't think we can _reliably_ generate ImportRequests to hit a given target size, since we'd need to actually iterate the real keys to get the mvccstats for that. I think the best we'll be able to do is assume data size is evenly distributed across K/Vs within a backup sst. Hmm.

**Comment by dt** [comment]
Accidentally created a reliable repro of this today when I was messing with zone config hooks, so I'll look at actually fixing it this week with the client-side split and retry.
