### ISSUE TITLE
distsql: test query cancellation with TPC-H

### ISSUE THREAD

**Issue by arjunravinarayan** [cockroachdb/cockroach#17858]
Now that #17527 is merged, we need to test cancellation of various long-running TPC-H queries on production clusters, to ensure that cancellation works as intended.

This issue is a tracking issue for those tests. A simple verification that query cancellation when randomly inserted during various TPC-H queries running concurrently is all that's needed here.

**Comment by arjunravinarayan** [comment]
More ongoing work, in particular, #19951.

**Comment by arjunravinarayan** [comment]
Assigning @asubiotto since he's actively working on this. I think this is closeable when #20088 merges, as we've done a lot of other testing on this as well.

**Comment by vivekmenezes** [comment]
closing in favor of #21878
