### ISSUE TITLE
distsql: add a cli flag for overriding the temp store location

### ISSUE THREAD

**Issue by arjunravinarayan** [cockroachdb/cockroach#17859]
We default for using a subdirectory of store 1 for the temp store, but we want to allow users to override this, for instance, when they have a VM with a persistent disk and an ephemeral disk.

Add a CLI flag to set the temp store directory.

**Comment by dianasaur323** [comment]
We probably need documentation for this. cc @jseldess

**Comment by arjunravinarayan** [comment]
There's an open PR (#18544), so let's wait until that is resolved and cherry-picked before we document it. Thank you!

**Comment by jseldess** [comment]
Thanks, @dianasaur323. We have an issue for documenting external storage. Not sure we'll get it done for the release, but in any case, I've link these issues: https://github.com/cockroachdb/docs/issues/1797.
