### ISSUE TITLE
ui: point towards jobs cancellation docs in jobs table

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#17855]
As discussed, instead of surfacing what SQL command to run in the jobs table, we'll point users towards the appropriate docs page for this feature so that they know the feature is available. 

@kuanluo do you mind mocking up what this might look like for @benesch?

cc @jseldess @cuongdo

**Comment by kuanluo** [comment]
Is this part of #17658?

**Comment by dianasaur323** [comment]
@kuanluo we aren't going to implement #17658 in 1.1 for now, since it highlights that we can't do that with schema changes, and seems a bit odd from a user perspective. We do want users to know that they can cancel backup / restore though, but I'm not sure how to best surface that in the admin UI.

**Comment by kuanluo** [comment]
Idea: If the tooltip to docs is universal in the jobs table, we could surface ℹ️  icon, as the one on time series graphs, next to JOBS title? On hover, it would show the tooltip with copy, exactly as how it would behave on the graph. 

![image](https://user-images.githubusercontent.com/1486483/29938648-7d6a5148-8e57-11e7-94a7-d8ffa6c7a5b9.png)

**Comment by jseldess** [comment]
I like that, @kuanluo. 

cc @sploiselle, who's writing the relevant docs.

**Comment by dianasaur323** [comment]
I'm fine with that. @cuongdo does anyone have capacity for this at this point?

**Comment by benesch** [comment]
I have a PR coming later tonight to address this.

**Comment by dianasaur323** [comment]
Amazing, thanks @benesch!!
