### ISSUE TITLE
ui: incorporate a "loading" page status when pages are waiting to load

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#17861]
@mrtracy based on our discussion today, it seems like the jobs table shows the "no results" view instead of a loading view. Could we create a loading view? 

cc @kuanluo for design.

We also need to consider if this is a big change vs a bug fix, so please let me know. Thanks! If this is a bug fix, let's get this in by 1.1

cc @nstewart 
cc @cuongdo

**Comment by kuanluo** [comment]
We have a loading spinner for graphs that perhaps can be used here?
