### ISSUE TITLE
storage: Raft "state.commit out of range" panic

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#17872]
The `state.commit is out of range` panic in [raft.loadState](https://github.com/coreos/etcd/blob/897cadc88c5f4b01a8df6b760ec4b68ff1ece842/raft/raft.go#L1233-L1240) has been seen in the wild in the 1.0.4 release.

Not much to go on, but here's the crash report: https://sentry.io/cockroach-labs/cockroachdb/issues/333988648/

**Comment by petermattis** [comment]
Could this be the same as #14231?

**Comment by bdarnell** [comment]
I don't think so. #14231 indicates we've gotten a raft message that is inconsistent with our on-disk state. This panic indicates that our on-disk state is inconsistent with itself.

**Comment by bdarnell** [comment]
#19172 is probably the same issue. Closing this one in favor of the newer issue which has more detail.
