### ISSUE TITLE
sql/parser: go-fuzz our SQL parsing

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#1788]
https://github.com/dvyukov/go-fuzz

**Comment by tamird** [comment]
:+1: that would be pretty awesome

**Comment by tschottdorf** [comment]
the list of go compiler bugs found is amazing https://github.com/dvyukov/go-fuzz/blob/master/examples/gotypes/main.go

**Comment by petermattis** [comment]
Anyone is welcome to take this on. Just assign it to yourself so we don't duplicate work.

**Comment by tschottdorf** [comment]
I'll play around with it tomorrow. Will assign once I'm actually doing meaningful work towards this issue.

**Comment by tschottdorf** [comment]
the good news is that @dvyukov fuzzed vitess' parser: https://github.com/dvyukov/go-fuzz/tree/master/examples/sqlparser

that gives us a decent corpus to start with.

What's less ideal is that the way our `sql.y` is set up, it ignores large swaths of grammar we don't support. These in turn allow things to get parsed with `nil` entries in the structs where you shouldn't have `nil`, and then the easiest route to fuzz is dead (taking a successfully parsed statement, turning it back into a string, parsing again and checking that the statements are equal).
I think we'll have to comment out those parts that we simply drop on the floor so that they generate parse errors instead of slipping through.

I'll have my WIP up in a branch shortly.

**Comment by tschottdorf** [comment]
What's also missing is a way to print out the syntax tree. `%+v` doesn't work since that falls back to `fmt.Stringer` and gives us the SQL (and there are many cases in which the SQL appears to be the same, but the tree not `DeepEqual`), and `%#v` doesn't go deeper.

**Comment by petermattis** [comment]
The current grammar setup doesn't guarantee that SQL -> parsed -> SQL will result in the same SQL. When there is alternate syntax, we only generate one. For example, the recent typecast stuff `1::text` -> `CAST(1 AS TEXT)`. Making the SQL roundtrip exactly is a lot of work for little value. 

Yes, there are large swaths of the grammar that we don't currently support (e.g. `ALTER`). I suppose we could comment these out in the short term.

**Comment by tschottdorf** [comment]
I'm talking about taking a parsed statement and going to string and back to statement again. That should always do the same thing, and if it's not like that, then it's an indication that we've parsed something from the original string into the first expression that got lost the second time around. Of course, currently that's almost always a `nil` somewhere.

> I suppose we could comment these out in the short term.

Wouldn't we want to comment those out in the long term as well (until they're actually implemented) or do you already have parsing tests for parts of them?

**Comment by petermattis** [comment]
You're correct. Going from parsed to string and back to parsed should result in the same syntax tree.

`sql/parser/parser_test.go:TestParseSyntax()` contains various bits of syntax that we parse that we don't generate syntax trees for. There are actually a lot more examples than those test cases (e.g. all of the `ALTER` statements). Adding the syntax tree support for these statements is straightforward, though lower priority than getting base functionality working.

**Comment by dvyukov** [comment]
You can disable DeepEqual check if the input contain some particular substrings, e.g. "::text" or some unsupported sql constructs. That still allows to verify equality for the rest of inputs.
Or write a custom comparison function, see e.g. https://github.com/dvyukov/go-fuzz/blob/master/examples/fuzz/util.go

**Comment by tschottdorf** [comment]
a usable state is here https://github.com/tschottdorf/cockroach/tree/fuzzing
I update this branch with my current corpus and code. Where should it eventually go? Probably an extra repo.

**Comment by tschottdorf** [comment]
https://github.com/cockroachdb/go-fuzz/pull/1
