### ISSUE TITLE
sql: support secondary indexes in INSERT

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#1789]
`INSERT` currently only creates key/value pairs the for the columns. We also need to create key/value pairs for any secondary indexes.

**Comment by XisiHuang** [comment]
Have you guys got some ideas on inplement secondary index?

**Comment by tamird** [comment]
The design is specified in https://github.com/cockroachdb/cockroach/blob/master/docs/structured.md

Go ahead and implement if you'd like.

**Comment by XisiHuang** [comment]
Great  :)

**Comment by tamird** [comment]
@XisiHuang I added basic support for secondary indexes in insert/delete in #1886 but you could work on:
- uniqueness checking (right now we blindly overwrite primary keys and do not check uniqueness of secondary indexes).
- supporting secondary indexes in SELECT (and maybe UPDATE, when #1845 lands.

**Comment by petermattis** [comment]
@tamird I'm working (slowly) on adding support for indexes to SELECT.

**Comment by XisiHuang** [comment]
@tamird   got  it.
