### ISSUE TITLE
ui: node claims to have voted for replica 0

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#17909]
![image](https://user-images.githubusercontent.com/5076964/29686857-7ab20406-88e8-11e7-8479-16fd6bd4e45d.png)

Not clear where the root cause for this is or what it means.

**Comment by BramGruneir** [comment]
It means that it did not vote in the last election.
I can replace them with a `-` if you think that would be clearer.

On Thu, Aug 24, 2017 at 4:23 PM, Tobias Schottdorf <notifications@github.com

**Comment by tschottdorf** [comment]
That can't be true, if two out of three nodes didn't vote, how is there a leader?

**Comment by tschottdorf** [comment]
I *guess* this could happen when we switch out members of the original replica set?

**Comment by bdarnell** [comment]
Yeah, newly added nodes don't have a vote, so you could remove a node that cast a vote and then be left with this situation.

**Comment by tschottdorf** [comment]
Ok. Nothing to do except remove the 0 with a placeholder then.
