### ISSUE TITLE
stability: make debug tools useful for wedged/underreplicated clusters

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#17904]
For a cluster whose kv store is not available, we can still return useful information. For example,

`./cockroach node ls --insecure`

could still return a list. Gossip has a lot of information.

It's easy to iterate on these things: stand up a 3x cluster, kill two nodes, see which debug tools break and think about which information they still *should* be able to return.

More seriously, having locked down the vmodule endpoint with a cluster setting means we're now unable to change it on a wedged cluster, something that @nvanbenschoten and I are presently unhappy about.

**Comment by a-robinson** [comment]
+1 to this.

Related issues:
https://github.com/cockroachdb/cockroach/issues/16489
https://github.com/cockroachdb/cockroach/issues/15342

> Gossip has a lot of information.

We do have `./cockroach debug gossip-values`, in case you weren't aware.

**Comment by tschottdorf** [comment]
I think these other issues are good enough, thanks!
