### ISSUE TITLE
"Capacity Used" showing as 0.00% despite using 7% capacity.

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/cockroach#17912]
**BUG REPORT**

![image](https://user-images.githubusercontent.com/894257/29687831-c9a9719a-88eb-11e7-912a-7d224cb1b172.png)

"You are using 10.7 GiB of 146.8 GiB usable storage capacity across all nodes." -> this should show 7.02%

cockroach version
Build Tag:    798df64
Build Time:   2017/08/21 15:05:23
Distribution: CCL
Platform:     linux amd64
Go Version:   go1.8.3
C Compiler:   gcc 6.3.0
Build SHA-1:  798df647566b6bd5391f533f865d2e85bc756ca8
Build Type:   release-gnu

**Comment by jordanlewis** [comment]
`blue` has this, which also seems sketchy:

![image](https://user-images.githubusercontent.com/43821/29689062-d77036d4-88ef-11e7-8f28-59c61bbed054.png)

**Comment by bdarnell** [comment]
This was changed in #17733. CC @a-robinson

**Comment by a-robinson** [comment]
I'm bad at math and parentheses

![image](http://www.reactiongifs.com/r/shm2.gif)

**Comment by a-robinson** [comment]
Thanks for pointing this out, @nstewart!
