### ISSUE TITLE
ui: Admin UI Jobs Table is ambiguous 

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/cockroach#17910]
**FEATURE REQUEST**

In the jobs table, the database on which the jobs are running in ambiguous since we only show the table name: 

![image](https://user-images.githubusercontent.com/894257/29687262-b3d2a762-88e9-11e7-9f8d-481336817213.png)

We need another column or some other way to indicate which database is being impacted given the jobs table is scoped to the cluster.

cockroach version
Build Tag:    798df64
Build Time:   2017/08/21 15:05:23
Distribution: CCL
Platform:     linux amd64
Go Version:   go1.8.3
C Compiler:   gcc 6.3.0
Build SHA-1:  798df647566b6bd5391f533f865d2e85bc756ca8
Build Type:   release-gnu

**Comment by dianasaur323** [comment]
according to @benesch this looks specific to schema changes, although the database name might still be removed in certain restore jobs. assigning @jordanlewis to take a quick look. Essentially, we want to be able to show that certain jobs are associated with certain databases.

**Comment by benesch** [comment]
It occurs to me that I think this would also fail to include the database for a backup job if someone runs `SET DATABASE = foo; BACKUP bar....`. We need some way of asking the parser package to fully specify the database name in the stringified query.

**Comment by dianasaur323** [comment]
yep! although hopefully in practice people don't do that as often. Either way, I believe database name is something we should be surfacing. Do you think this will make it into 1.1? We are getting super close to cutting a branch.

**Comment by benesch** [comment]
Might slip; afraid I've got a bunch of other performance/stability issues to tackle first.

**Comment by dianasaur323** [comment]
@benesch that's fine - I understand that there are some other issues with BU/R that you need to work on first. We can allocate time to bug fix this in 1.2, although getting this out in 1.1 is better. I think it's become clear that trying to build out admin UI features during bug fixing stage is not really the best approach, so we'll adjust in 1.2.

**Comment by dianasaur323** [comment]
ok, bumping over to @dt. As discussed, best to get in 1.1, but the world won't end if it doesn't make it in. Thanks all!
