### ISSUE TITLE
DELETE FROM ... [returning nothing] crashes a node

### ISSUE THREAD

**Issue by AnyCPU** [cockroachdb/cockroach#17921]
A cluster has 3 nodes running on Cockroachdb 1.0.5 (Linux, 64bit)
A db has about 195 millions of records.
Scheme is 
```
CREATE TABLE stats (
	numa STRING(32) NULL,
	bytes INT NULL,
	amount DECIMAL NULL,
	ts TIMESTAMP NULL,
	da INT NULL,
	INDEX idx_stats_ts (ts ASC) STORING (numa, bytes, amount, da),
	FAMILY "primary" (numa, bytes, amount, ts, da, rowid)
)
```
The db has data of an one month.
I want to delete data starting from second day of month, so
I run either  `delete from stats where ts > '2017-01-01 23:59:59'::timestamp;` or `delete from stats where ts > '2017-01-01 23:59:59'::timestamp returning nothing;`.
I use the `cockroach sql --insecure --host = ...` command to run my query.
After some minutes an used node dies.
A db driver returns - bad connection.
And there are a lot of messages like that `context canceled while in command queue: ResolveIntent...` in the log.

All nodes have free space.

Do I have to delete data by chunks?

Thanks.

**Comment by AnyCPU** [comment]
I cannot even remove a half a day.

**Comment by AnyCPU** [comment]
I have tried to remove data for an one hour but I got
```pq: kv/txn_coord_sender.go:428: transaction is too large to commit: 478692 intents```

**Comment by AnyCPU** [comment]
It is possible to remove data by ten-minutes chunks :-(

**Comment by tschottdorf** [comment]
Hey @AnyCPU, you're running into the fact that as of the time of writing, support for large writing transactions is not ideal in CockroachDB. You've pretty much experienced all the problems: them never succeeding, or failing with the "too large to commit" error. While deleting in small chunks is currently the best option, rest assured that we're working on improving this (see the issue above). We have workarounds in place for the case in which you want to drop/truncate the whole table (which we can do more efficiently by essentially swapping out the table with a new one), but that's clearly not going to help you.

Tracking issue: https://github.com/cockroachdb/cockroach/issues/15849

**Comment by AnyCPU** [comment]
Thank you @tschottdorf

**Comment by tschottdorf** [comment]
Despite many improvements, this is still an issue in `master` at the time of writing, though we now have a test that reproduces this reliably: https://github.com/cockroachdb/cockroach/pull/22876

**Comment by tschottdorf** [comment]
@spencerkimball let's move the discussion from #22876 here. I agree that the easiest way to diagnose this is to get heap profiles.

@petermattis if I were to introduce such a facility into `roachtest`, how do you think I should do it? I think it would be reasonable to write a little standalone program (or bash script for starters) that does little except periodically store heap dumps to artifacts on all relevant nodes (so that we can just run it in tests that want it, like a load gen). That way, it won't get in the way of perf tests. To get fancy, we could let the program assert on the heap dump, though I'd like to punt on that.

**Comment by petermattis** [comment]
For heap profiles, you can already do `roachprod start -e COCKROACH_MEMPROF_INTERVAL=1m ...`. Did you mean something different by "heap dumps"?

**Comment by petermattis** [comment]
Also, when diagnosing, it is easiest to create a cluster using `roachprod create` and then run the test using `roachtest run -c <existing-cluster>`.

**Comment by tschottdorf** [comment]
> For heap profiles, you can already do roachprod start -e COCKROACH_MEMPROF_INTERVAL=1m .... Did you mean something different by "heap dumps"?

No, that's what I mean. Forgot about the env var, thanks!

**Comment by tschottdorf** [comment]
With #22991, this seems to be making steady progress:

<img width="863" alt="image" src="https://user-images.githubusercontent.com/5076964/36581270-1d0307ba-183a-11e8-9858-a6c3d670b637.png">

Remains to be seen whether it manages to commit.

**Comment by tschottdorf** [comment]
Reopening as there are still problems with such deletions. They should either fail gracefully or succeed; not hang indefinitely.

**Comment by tschottdorf** [comment]
Reopening to verify fix.

**Comment by tschottdorf** [comment]
Ah, already done: https://github.com/cockroachdb/cockroach/pull/23258#issuecomment-369726447
