### ISSUE TITLE
storage engine, badger

### ISSUE THREAD

**Issue by pkieltyka** [cockroachdb/cockroach#17929]
Hey guys, fantastic over the years on CRDB. I was wondering if you had considered to try github.com/dgraph-io/badger in place of rocksdb? It would be interesting to see performance comparisons after removing the cgo overhead.

**Comment by a-robinson** [comment]
Hey @pkieltyka, we've played around with badger a little bit (https://github.com/dgraph-io/badger/issues/95), but it would be a pretty massive project to change from rocksdb to badger given how many features of rocksdb we're using that badger doesn't have. We'll be keeping an eye on badger as it improves, but don't have plans to switch to it anytime soon.

**Comment by pkieltyka** [comment]
@a-robinson just a note in case you're not following badger -- they've added transaction support https://blog.dgraph.io/post/badger-txn/

it would be interesting to know what other features cockroachdb requires to replace rocksdb as its storage engine

**Comment by arjunravinarayan** [comment]
Hi @pkieltyka, here are some incomplete thoughts on the RocksDB features we use. I don't know which ones are in badger; I'll let you be the judge of that. Given the number of features, IMO we are unlikely to ever move to something else in the next year or so timeframe, unless any such project reaches the maturity level (and has the kinds of perf gains) that mean that all these features are there. The lack of even one of these features would likely result in a significant performance degradation in CockroachDB.

* Backward iteration on iterators
* Prefix bloom filters
* Custom key comparators
* Snapshots
* Range deletion tombstones
* Direct ingestion of SSTables

I understand from the other issue you linked that you find Cgo worrisome, but a far bigger worry would be using a completely untested storage engine. There's a lot of things a storage engine can get wrong, and RocksDB is a mature project that we rely on quite a bit.

**Comment by pkieltyka** [comment]
@arjunravinarayan awesome, thanks for taking the time to go over the requirements.

**Comment by ivanjaros** [comment]
Any progress with this?
