### ISSUE TITLE
perf: evaluate impact of rocksdb::Options::max_open_files

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#17959]
We currently default `rocksdb::Options::max_open_files` to `-1` if the open file limit is sufficiently high. This is done per the [RocksDB Tuning Guide](https://github.com/facebook/rocksdb/wiki/RocksDB-Tuning-Guide):

> max_open_files -- RocksDB keeps all file descriptors in a table cache. If number of file descriptors exceeds max_open_files, some files are evicted from table cache and their file descriptors closed. This means that every read must go through the table cache to lookup the file needed. Set max_open_files to -1 to always keep all files open, which avoids expensive table cache calls.

Because restore ingests relatively small (2MB) sstables, the calculations about the max number of sstables and thus the max open files are way off. Rather that crash when the number of open files is too large, we should set `rocksdb::Options::max_open_files`. The question to answer here is what is the impact of doing so even when we're well underneath the number of open file limit. Plan is to run the `roachperf` `kv_0` and `kv_95` tests with `max_open_files = -1` and `max_open_files = 10000`. 

Cc @benesch 
See #17928 
See #17958

**Comment by bdarnell** [comment]
If the open file limit is sufficiently high, why aren't we just setting max_open_files to that sufficiently high value? It seems dumb to ever set it to -1 when we know the real limit.

**Comment by petermattis** [comment]
The overhead to `max_open_files != -1` isn't about re-opening the file, but about going through the table cache. I measured this in the past and can't recall what the overhead was. The task here is to measure it again. I don't think it will be significant and certainly not enough to stop us from merging #17958.

**Comment by petermattis** [comment]
Using `max_open_files = 10000` provides no measurable performance hit.

Tested `kv --read-percent-95 --splits=1000` on a 6-node cluster, varying `--concurrency` from 6 up to 384:

<img width="719" alt="screen shot 2017-08-29 at 1 22 18 pm" src="https://user-images.githubusercontent.com/6201335/29834593-5bea2516-8cbd-11e7-9da9-7b07c6706032.png">

Red is with `max_open_files = -1` and blue is `max_open_files = 10000`.
