### ISSUE TITLE
storage: Delayed update of per-store write stats can cause rebalance thrashing

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#17970]
After a rebalance has happened, the `LogicalBytes` and `WritesPerSecond` logically change for the store that the replica was added to or removed from. If the `LogicalBytes` stat changes by a large amount, then the store will re-gossip its `StoreCapacity` ahead of schedule. While it isn't guaranteed by any means, in practice this does a mostly decent job of getting updated information spread throughout the cluster quickly enough that a bunch more rebalance operations aren't based on outdated information.

The same is not true for `WritesPerSecond`, though. We don't start counting `WritesPerSecond` stats until a replica has been on a new store for 5 seconds, so a good deal more rebalancing decisions can be made without considering the additional writes on the node. In some circumstances (as seen on indigo), this can make for rebalance thrashing where we add a replica to a node, then decide that the replica isn't a good fit for it. If the store's `WritesPerSecond` stat had been updated, we wouldn't move the replica.

As seen on indigo, this was closely intertwined with #17971.

@BramGruneir has previously suggested passing along `WritesPerSecond` stats as part of a rebalance to combat this. I'm still not sure about that, but the leaseholder that made the rebalance decisions should be capable of updating its own local copy of the other store's descriptor so that it has a more accurate view when deciding which replica to remove as part of a rebalance.

**Comment by a6802739** [comment]
@a-robinson, here is my understanding:

After a replica being rebalanced, which means it was added to a target node. However, it's statics information was not immediately being counted be the target store, so it would be removed possibly because of the next round rebalance?
if the target node has a newest information of all the stores' statics, it won't remove the new rebalanced target?
Hope get some reference, Thank you very much.

**Comment by a-robinson** [comment]
Yes, that's correct. The node making rebalancing decisions needs more up-to-date statistics about the target node after rebalancing a range onto it before deciding which replica to remove from the range.

**Comment by a6802739** [comment]
@a-robinson , Thank you very much.

So here is my thought:

we should try to get the newest statistics about the target before we try to remove a range. Before, we get these information just from gossip, right?
1. we could wait some interval time, because gossip will finally broadcast these information to this node which decide to remove the replica.
2. we could just send an RPC request to the target node to get the newest statistics, it is more effective, but more complicated.

Hope could get some help, Thank you.

**Comment by a-robinson** [comment]
> 1. we could wait some interval time, because gossip will finally broadcast these information to the node which decide to remove the replica.

I'm a little worried about how reliably we'll be able to know how long to wait, but something along those lines could work. It would have a pretty noticeable effect on how the replicate queue behaves that we'd have to think carefully about, though.

> 2. we could just send an RPC request to the target node to get the newest statistics, it is more effective, but more complicated.

That'll either involve a fair amount of tracking (when do we need to do an RPC vs using the gossiped value?) or too many RPCs. There will also still be waiting involved unless we change [the logic that avoids tracking writes for the first 5 seconds of a replica's existence](https://github.com/cockroachdb/cockroach/blob/af58807e9c4023b05a1c2d96b816c594040dbec5/pkg/storage/store.go#L2308), which was added to reduce anomalous measurements.

The other two options I've considered are the ones in the final paragraph of the initial comment -- either including statistical information about the range along with preemptive snapshots (which would be pretty invasive for such a small, unrelated issue) or just having the replica that made the rebalance decision locally modify its own copy of the other store's stats. The local update would enable it to make a more accurate remove decision immediately after the add, and its local modifications would be overwritten as soon as new gossip is received from the other store.

Can you think of any issues with that last approach?

**Comment by a6802739** [comment]
@a-robinson, Yeah, we could update the local copy of the other store's stats, but how could we guarantee it will be overwritten by the new gossip info from other store, the gossip info is updated by comparing the timestamp info between local copy and remote store info.

**Comment by a-robinson** [comment]
> Yeah, we could update the local copy of the other store's stats, but how could we guarantee it will be overwritten by the new gossip info from other stores, the gossip info is updated by comparing the timestamp info between local copy and remote store info, right?

By not updating the copy in gossip :) We could update the [copy held in the local `StorePool`](https://github.com/cockroachdb/cockroach/blob/master/pkg/storage/store_pool.go#L221).

> And we only need to update the target store's Capacity info after we add a replica to this store during the rebalance, right?

Correct.
