### ISSUE TITLE
bug: cockroach dump produces invalid SQL due to NaN values

### ISSUE THREAD

**Issue by d4l3k** [cockroachdb/cockroach#17981]
**BUG REPORT**

1. Please supply the header (i.e. the first few lines) of your most recent
   log file **for each node in your cluster**. On most unix-based systems
   running with defaults, this boils down to the output of

     grep -F '[config]' cockroach-data/logs/cockroach.log

   When log files are not available, supply the output of `cockroach version`
   and all flags/environment variables passed to `cockroach start` instead.

```
I170828 16:38:03.018296 1 util/log/clog.go:975  [config] file created at: 2017/08/28 16:38:03
I170828 16:38:03.018296 1 util/log/clog.go:975  [config] running on machine: ashley
I170828 16:38:03.018296 1 util/log/clog.go:975  [config] binary: CockroachDB CCL v1.1-alpha.20170817 (linux amd64, built 2017/08/17 22:29:49, go1.8.3)
I170828 16:38:03.018296 1 util/log/clog.go:975  [config] arguments: [cockroach start --insecure --host=localhost --http-port 8181]
```

2. Please describe the issue you observed:

- What did you do?

```
$ cockroach dump pok --insecure > cockroach-dump.sql
$ cockroach sql -d pok --insecure < cockroach-dump.sql
```

- What did you expect to see?

It insert the data successfully.

- What did you see instead?

```
 ~/sd  cockroach sql -d pok --insecure < cockroach-dump.sql
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
INSERT 1
INSERT 4
INSERT 76
INSERT 12
pq: name "nan" is not defined
Error: pq: name "nan" is not defined
Failed running "sql"
```

`cockroach dump` produced a bunch of lines in the form
```
INSERT INTO training_metrics (id, created_at, updated_at, deleted_at, model_id, epoch, "name", value) VALUES
        (273189741280493569, '2017-08-22 22:34:52.663422+00:00', '2017-08-22 22:34:52.663422+00:00', NULL, 273184959855853569, 1, 'Cast:0', NaN),
        (273189902991851521, '2017-08-22 22:35:42.040055+00:00', '2017-08-22 22:35:42.040055+00:00', NULL, 273184959855853569, 2, 'Cast:0', NaN),
```
but NaN is not recognized by the SQL parser.

**Comment by benesch** [comment]
This looks to be a bug in the way sql/parser stringifies floats; the constants +Inf, -Inf, and NaN need to be wrapped in single quotes.

**Comment by d4l3k** [comment]
And if it's a decimal field they need to be wrapped in `CAST('NaN' as
DECIMAL)`

**Comment by benesch** [comment]
It's safe and more portable—I _think_—to leave off the cast. Since the literal is used in a `VALUES` clause where the type is known from the table's schema, it'll coerce to `FLOAT` or `DECIMAL` as appropriate.

**Comment by knz** [comment]
@justinj @nvanbenschoten can you have a look a this? I think you poked at this code more recently than Matt.

**Comment by nvanbenschoten** [comment]
@d4l3k nice to hear from you again! Hope everything is going well back at school.

It looks like we weren't using `FmtParsable` format flag in `cockroach dump`. I'm putting together a fix now.
