### ISSUE TITLE
ui: update tooltips to accurately describe metrics

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#17994]
Currently tooltips show the following:

![image](https://user-images.githubusercontent.com/5768024/29833485-9a0a5e28-8cb9-11e7-9b97-e8ad9cb55977.png)

However, it's more accurate to say that it is the 10-sec rolling average number of queries that started processing per second. We need to update this tooltip since it was confusing.

Addresses https://github.com/cockroachdb/cockroach/issues/17948

cc @cuongdo this seems like a relatively quick fix. Anyone in mind who can help out?

**Comment by mrtracy** [comment]
This should be rolled into #13766
