### ISSUE TITLE
sql: support LIMIT for DELETEs

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#18006]
MySQL has a `LIMIT` clause for `DELETE` that allows one to incrementally delete rows from a table. Instead of deleting all rows at once, one can execute `DELETE ... LIMIT N` until there are no more rows to be deleted. This reduces the duration of the transaction containing the `DELETE`. (See the [MySQL DELETE docs](https://dev.mysql.com/doc/refman/5.7/en/delete.html) for more details.)

This is a workaround for large `DELETE`s until we have support for [support for larger transactions](https://github.com/cockroachdb/cockroach/issues/15849). This would improve the user experience described in #17921.

The one downside I can think of this approach is that [Postgres's DELETE](https://www.postgresql.org/docs/9.6/static/sql-delete.html) does not support the `LIMIT` clause, which means that ORMs' Postgres dialects won't generate queries that use `LIMIT`s.

**Comment by knz** [comment]
There's another advantage: if the table is not indexed, but the user knows ahead of time there's only N rows that match the delete condition, then the delete loop can stop scanning the table as soon as N rows have been deleted.

**Comment by cuongdo** [comment]
That was remarkably fast. There goes another starter project! (Note that I didn't make it clear that this was intended to be a starter project, so you couldn't have known.)

**Comment by knz** [comment]
Well TBH I was also very concerned by #17921. Your idea is a very good way to alleviate that in 1.1.

**Comment by tschottdorf** [comment]
Yeah, I'm pretty happy we now have a workaround in 1.1.

**Comment by cuongdo** [comment]
Definitely. This was the right call.
