### ISSUE TITLE
yacc issue: index out of range

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#1801]
likely identical twin of https://github.com/youtube/vitess/issues/767

```go
	s := "SELECT(F(F(F(F(F(F(F" +
		"(F(F(F(F(F(F(F(F(F(F" +
		"(F(F(F(F(F(F(F(F(F(F" +
		"(F(F(F(F(F(F(F(F(F(F" +
		"(F(F(F(F(F(F(F(F(F(T" +
		"(F(F(F(F(F(F(F(F(F(F" +
		"(F(F(F(F(F(F(F(F(F(F" +
		"(F(F(F(F(F(F(F(F(F(F" +
		"(F(F(F(F(F(F(F(F(F(F" +
		"(F(F(F(F(F(F(F(F(F((" +
		"F(0"

	Parse(s)
```

test code in #1802

stack trace:

>
goroutine 1 [running]:
github.com/cockroachdb/cockroach/sql/parser.sqlParse(0x2208386ac0, 0x2083ba400, 0x0)
	/var/folders/yy/4q8rrssd27vdgbr59w9qbffr0000gn/T/go-fuzz-build896428593/src/github.com/cockroachdb/cockroach/sql/parser/yaccpar:207 +0x548df
github.com/cockroachdb/cockroach/sql/parser.Parse(0x2083b1380, 0xcb, 0x0, 0x0, 0x0, 0x0, 0x0)
	/var/folders/yy/4q8rrssd27vdgbr59w9qbffr0000gn/T/go-fuzz-build896428593/src/github.com/cockroachdb/cockroach/sql/parser/parse.go:50 +0x16a

**Comment by petermattis** [comment]
This seems to be some problem in the generated code during error recovery when `sqlMaxDepth` (default 200) is reached.
