### ISSUE TITLE
cli/decommission: decommission hangs with 3-node cluster

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#18029]
I ran all of these locally (using macOS):

```
cockroach start --insecure --port=26257 --http-port=8080 --store cockroach-data/1 --cache=256MiB --logtostderr
cockroach start --insecure --port=26258 --http-port=8081 --store cockroach-data/2 --cache=256MiB --logtostderr --join=localhost:26257
cockroach start --insecure --port=26259 --http-port=8082 --store cockroach-data/3 --cache=256MiB --logtostderr --join=localhost:26257
```

Then I ran:

```
cockroach node decommission 3 --insecure
```

Instead of outputting an error or completing, the CLI repeats the following output forever:

```
+----+---------+-------------------+--------------------+-------------+
| id | is_live | gossiped_replicas | is_decommissioning | is_draining |
+----+---------+-------------------+--------------------+-------------+
|  3 | true    |                14 | true               | true        |
+----+---------+-------------------+--------------------+-------------+
(1 row)
```

The fix is complex, so the best thing to do now is document as a known limitation. cc @jseldess

**Comment by jseldess** [comment]
Thanks, @cuongdo. The idea here is that, since there's no other node for rebalancing node 3's replicas, decommissioning can't ever make progress?

**Comment by tschottdorf** [comment]
Yeah, exactly. More generally, if the zone configurations don't allow for a balanced cluster in the absence of this node, then the decommissioning progress will wait until that is resolved (i.e. potentially forever). More practically speaking, the rebalancer won't break the rules to move data off the node.

**Comment by jseldess** [comment]
Got it. Thanks, @tschottdorf. Will incorporate this into the decommissioning docs and add a known limitation.

**Comment by sploiselle** [comment]
@tschottdorf Can I get a quick blurb describing this known limitation w/r/t the impact to user experience? Ideally, we need it by Friday 10/26 for the 2.1 Known Limitations page. Posting it on this issue and/or pinging me would be great.

**Comment by tschottdorf** [comment]
The `cockroach node decommissioning` command will hang when used to target a set of nodes that can't be removed without breaking the configured replication rules.

Example: decommissioning a node in a three node cluster won't work because ranges don't want to be underreplicated. More complex examples are possible if you set up constraints.

Does that help?

**Comment by ulfjack** [comment]
Does this apply even after setting the number of replicas to 1?
I ran ```ALTER RANGE default CONFIGURE ZONE USING num_replicas=1;```

I've started the decommission of nodes 2 and 3, but it seems to hang at replicas=20, even though the first node has a copy of all the data.

**Comment by ulfjack** [comment]
Is there any way to go from 3 nodes back down to 1? (Apologies if this is the wrong place to ask.)

**Comment by tbg** [comment]
@ulfjack yes, use [replication zone configs](https://www.cockroachlabs.com/docs/stable/configure-replication-zones.html) to specify only one replica, and decommission two of the nodes.

**Comment by knz** [comment]
We've iterated around this in the last two months and there's now consensus that we want decommission to obey the replication rules, so it is indeed not possible (and will hang forever) to decommission one node out of 3 if the replication factor is 3.

Closing this issue as unactionable.

**Comment by jseldess** [comment]
@knz, ok for me to remove this known limitation from all versions of the docs then? https://www.cockroachlabs.com/docs/dev/known-limitations.html#cannot-decommission-nodes

**Comment by knz** [comment]
Yes this is not a "known limitation" inasmuch as "please understand what's going on before you run an operation". Is the behavior wrt the replication factor documented elsewhere?

**Comment by jseldess** [comment]
Yes, we cover that here: https://www.cockroachlabs.com/docs/stable/remove-nodes.html#considerations. I'll remove this limitation throughout all versions of the page.
