### ISSUE TITLE
ui: TypeError while loading range debug page on broken range

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#18035]
On a cluster affected by #17989, trying to load up a problematic range on a functioning node only displays the message below. It may be related to the fact that node 1 doesn't is supposed to have a copy of replica 357 but hasn't yet processed the split that created it. This is annoying, but not incredibly urgent.

<img width="887" alt="screen shot 2017-08-30 at 2 09 54 pm" src="https://user-images.githubusercontent.com/7085343/29887923-039667c8-8d8d-11e7-99e7-9e2ca050b205.png">

**Comment by tschottdorf** [comment]
One more:

![image](https://user-images.githubusercontent.com/5076964/30245939-10e0a906-95b8-11e7-8f42-7c50c7cae20b.png)

@dianasaur323 I think these are easy to fix and that getting them into 1.1 would be of great value. These things prevent you from making progress when you are at your most desperate.

**Comment by dianasaur323** [comment]
Ok! Well @BramGruneir is probably the one best suited to do it. I'm definitely underqualified in that area. @BramGruneir would you mind updating this for 1.1?

**Comment by BramGruneir** [comment]
These conditions will only occur when there is some missing data.  The next time anyone sees this, I would love to see the data that caused it so we can fix the undefined errors. 

Since this only happens on very broken ranges, I'm going to punt this to 1.2.
