### ISSUE TITLE
storage: allow splitting meta2 ranges

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#18032]
See #16266 for the initial issue before it diverged into a bug hunt.

#17565 disallowed splits in meta2 ranges due to problems with `RangleLookups`. `RangeDescriptors` for user ranges whose keyspan straddled meta2 ranges would not always be seen if a `RangleLookup` went to the left meta2 range. This was because meta `RangeDescriptors` are stored at `RangeMetaKey(desc.EndKey)`, which will be on the right meta2 range for these "straddling" user ranges. We should adjust the handling of `RangleLookup` in the `RangeCache` and in `Replica` to address this case. After that, we should be able to turn meta2 splits back on.

**Comment by a6802739** [comment]
@nvanbenschoten, could I have a try for this?

**Comment by nvanbenschoten** [comment]
Hi @a6802739, I've already done most of the heavy lifting on this one and was planning on getting a change out later this week. We've been putting our heads down and focusing on v1.1 over the past few weeks, but this seems important enough to prioritize regardless. 

#17979 is an area with less active progress and one which you've also shown interest recently. Could I point you over there for the time being?

**Comment by a6802739** [comment]
Yeah, That would be good. Thank you very much.
