### ISSUE TITLE
sql: LeaseStore.WaitForOneVersion() doesn't like servers draining

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#18034]
I haven't investigated in detail exactly what's wrong, but I believe something definitely is.
`LeaseStore.WaitForOneVersion()` seemingly retries some actions forever, without responding to servers shutting down.
Here's how to reproduce some badness: 
If you insert a bogus `t.Fatal()` at this place:
https://github.com/cockroachdb/cockroach/blob/f50c95326743d7bd0a63bc578a7ac8de0c294c81/pkg/sql/rename_test.go#L203

the test will time out with the `ALTER TABLE` statement being blocked in this `retry.Next()` call:
https://github.com/cockroachdb/cockroach/blob/f50c95326743d7bd0a63bc578a7ac8de0c294c81/pkg/sql/lease.go#L245

I believe the problem, at least at a superficial level, is that we're not setting a closer channel on the `retry.Options`; I think that closer should somehow be tied to the server's stopper.

**Comment by vivekmenezes** [comment]
to be looked at later.

**Comment by andreimatei** [comment]
@ajwerner do you think there's something here?

**Comment by ajwerner** [comment]
No, but it's sort of indirect. The reason we don't have a problem anymore is that this is called underneath jobs (the schema change job mostly, but some others like restore and import). The job registry cancels the context of jobs when the stopper is being stopped. That propagates.
