### ISSUE TITLE
rpc: fail at handshake time when node versions are incompatible

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#18058]
see https://github.com/cockroachdb/cockroach/issues/17659.

We can do this in our `rpc` connection cache: before a connection becomes healthy, we require that both peers run with compatible binaries, and perhaps even compare their cluster IDs.

Should be a decent starter project. cc @cuongdo.

**Comment by a-robinson** [comment]
While checking binary versions, we should definitely also check cluster IDs to fix https://github.com/cockroachdb/cockroach/issues/15898 and https://github.com/cockroachdb/cockroach/issues/15801 while we're at it.

**Comment by cuongdo** [comment]
Moving to 1.1 because of #13027, which this issue contributes to resolving

**Comment by cuongdo** [comment]
actually, just noticed https://github.com/cockroachdb/cockroach/issues/14231#issuecomment-326823454, so moving back to 1.2

**Comment by tschottdorf** [comment]
Note that the gossip server (`gossip/server.go`) already has a check like this (which would be obsolete if all connections got validated as suggested above):

```go
// Gossip receives gossiped information from a peer node.
// The received delta is combined with the infostore, and this
// node's own gossip is returned to requesting client.
func (s *server) Gossip(stream Gossip_GossipServer) error {
	args, err := stream.Recv()
	if err != nil {
		return err
	}
	if (args.ClusterID != uuid.UUID{}) && args.ClusterID != s.GetClusterID() {
		return errors.Errorf("gossip connection refused from different cluster %s", args.ClusterID)
	}
```

**Comment by cuongdo** [comment]
Reassigning to @solongordon as his 2nd starter project.
