### ISSUE TITLE
sideloading: remove empty directories

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#18068]
See the following TODO from https://github.com/cockroachdb/cockroach/pull/17787:

```go
func (ss *diskSideloadStorage) TruncateTo(ctx context.Context, index uint64) error {
	// TODO(tschottdorf): if we end up removing *all* files, we could also
	// remove the directory.
```

@cuongdo this should be easy. Perhaps too easy for a starter project.

**Comment by bsnyder788** [comment]
@tschottdorf  I would love to take a stab at this one.

**Comment by bsnyder788** [comment]
link to PR: https://github.com/cockroachdb/cockroach/pull/18148

**Comment by bsnyder788** [comment]
@tschottdorf this one waas merged awhile back and can probably be closed out on there

**Comment by tschottdorf** [comment]
Thanks @bsnyder788 !
