### ISSUE TITLE
ui: warn if cluster is using a version < largest binary version seen on live node

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#18060]
Say a three-node cluster is running version 1.0 but the binaries are 1.1. There will be no mixed-version warning in the ui because all the nodes are running binary version 1.1. However, the user must explicitly run `SET CLUSTER SETTING version = '1.1'` and until they have done so, we should warn in the ui (and, periodically, in the logs).

I'm not familiar with ui land but pretty sure that this should be a good ui starter project, perhaps with a small core component (periodic logging and plumbing of the necessary info, though I think that's been done already).

@cuongdo for assignment.

**Comment by vilterp** [comment]
I think this is a dup of #22686.
