### ISSUE TITLE
jobs table is surfacing import jobs strangely

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#18079]
I'm running an import job using the tpch-csv stored in azure. 

It is failing with this error ```pq: azure://tpch-csv/sf-1/lineitem.tbl.1?AZURE_ACCOUNT_NAME=roachfixtureswestus&AZURE_ACCOUNT_KEY=MeIazPB%!F(MISSING)otG3dMtPjsMbJt2U1DnDuG9oFmxgFLSjI1W5JU294j2kENG6vvY2Sadv5CR7i2La%!B(MISSING)icviATClt3JXQ%!D(MISSING)%!D(MISSING): row 1: expected 16 fields, got 1```, but the job table is surfacing the jobs even though it threw an error.

![image](https://user-images.githubusercontent.com/5768024/29933513-dd3b274e-8e45-11e7-9f48-59b603caeb01.png)

These jobs should probably either fail, or not show up at all?

**Comment by dt** [comment]
(note, before anyone gets all excited, that key has been rotated)

**Comment by knz** [comment]
Also I see `%!D(MISSING)%!D(MISSING)` in the message, which means that an URL is being passed as format argument to a `printf` function, no good.

**Comment by benesch** [comment]
(https://github.com/cockroachdb/cockroach/pull/18090/files)

**Comment by benesch** [comment]
Looks like `FinishedWith` isn't getting called in all cases, @dt?
