### ISSUE TITLE
ui: Event log overview truncated awkwardly

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#18087]
![image](https://user-images.githubusercontent.com/160562/29936666-05f646c2-8e51-11e7-9a1d-d0193a4f565c.png)

The event log shown on the overview page is narrow, but the messages are fairly verbose and the portion shown here is not very useful. The "U" in the cluster setting messages is for "User", as in "Cluster Setting Changed: User root set trace.debug.enable to false". We should either give the log messages enough room to be legible or reword them to put the most interesting part (the setting name) near the beginning.

**Comment by dianasaur323** [comment]
Thanks Ben. I think this is related to https://github.com/cockroachdb/cockroach/issues/17717, when we'll try to redesign or revamp the event log.

**Comment by bdarnell** [comment]
OK, let's close this one and keep the discussion on #17717
