### ISSUE TITLE
ui: formatting fixes for import csv with jobs tables

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#18080]
The current import csv format doesn't conform with the other jobs in the jobs table. 

![image](https://user-images.githubusercontent.com/5768024/29933571-1eef2474-8e46-11e7-892d-11a27b457e8d.png)

We should make these match by capitalizing IMPORT and surfacing the actual SQL statement utilized. Since it might be overkill to show the entire statement including paths to CSVs, we should consider what we want to truncate. We also want to be careful not to reveal cloud storage account keys if those are expected to be private. 

cc @kuanluo

**Comment by dianasaur323** [comment]
Also, I think we want to be able to filter by import? 

![image](https://user-images.githubusercontent.com/5768024/29937688-6893fe52-8e54-11e7-98b4-35c8ee25a974.png)

**Comment by kuanluo** [comment]
+1 to IMPORT. 

Re: CSVs, what's the logic for RESTORE/BACKUP with private keys? We should use the same logic there.

**Comment by dt** [comment]
@dianasaur323 the tricky thing right now is that there isn't one SQL statement to one job right now -- `IMPORT` runs two jobs -- one that converts data, one that restores it. We don't have the concept of sub-jobs (yet).

**Comment by dianasaur323** [comment]
Hmmm.. @dt I just ran into that issue, where I ran and import and then saw a restore show up as well. I think something odd is going on in terms of when the import job shows up as well - I've been running a lot of failed imports to try to fix my configs, but they all show up on the jobs table. 

![image](https://user-images.githubusercontent.com/5768024/29943009-d0387356-8e65-11e7-9743-5140218b8ad2.png)

**Comment by benesch** [comment]
Fixed by #18157 and #18106, I believe.
