### ISSUE TITLE
storage: panic in processRaft after handleRaftReady

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#18084]
https://sentry.io/cockroach-labs/cockroachdb/issues/268859810/

```
*errors.errorString: *errors.fundamental store.go:3411
  File "github.com/cockroachdb/cockroach/pkg/storage/store.go", line 3411, in processReady
  File "github.com/cockroachdb/cockroach/pkg/storage/scheduler.go", line 217, in worker
  File "github.com/cockroachdb/cockroach/pkg/storage/scheduler.go", line 168, in func2
  File "github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go", line 215, in func1

*errors.fundamental store.go:3411
```

**Comment by a-robinson** [comment]
@cuongdo this is one of our most frequent panics in Sentry. Seems worth investigation for 1.1, even if it requires changes past the code freeze. Possibly related to #18082

**Comment by tschottdorf** [comment]
We're panicking while applying a preemptive snapshot. I don't have much else to go on, but #18229 should give us something more actionable as folks upgrade to v1.6.

**Comment by tschottdorf** [comment]
We have something in place for 1.0.6 (#18272, #18229) so hopefully we know soon what the actual crash is about. I'll have to put something similar together for 1.1.

**Comment by tschottdorf** [comment]
Moving to 1.2 now that we'll get better insight into the error on sentry.

**Comment by tschottdorf** [comment]
Marking as resolved, as after https://github.com/cockroachdb/cockroach/pull/20104 we'll see the actual RocksDB messages, and currently (i.e. without that PR) we see lots of errors emanating from RocksDB. Anything else will be tracked under new issues in sentry already.
