### ISSUE TITLE
restore: stuck restore command

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#18097]
Set up a clean 3 node cluster. Restored TPCH scalefactor 10. The job completed in the UI, but the SQL command never returned.

```
root@:26257/> SET CLUSTER SETTING kv.bulk_io_write.max_rate = '30MB';
SET CLUSTER SETTING

Time: 37.3833ms

root@:26257/> CREATE DATABASE tpch;
CREATE DATABASE

Time: 36.9632ms

root@:26257/> restore tpch.* from 'azure://backup-test/benchmarks/tpch/scalefactor-10?AZURE_ACCOUNT_NAME=cockroachbackuptest&AZURE_ACCOUNT_KEY=...';
```

Goroutines dump shows multiple goroutines stuck in [restore.go:882](https://github.com/cockroachdb/cockroach/blob/13f468f784fa9df8525601e2b8f6a4b4b500eae3/pkg/ccl/sqlccl/restore.go#L881) and [restore.go:643](https://github.com/cockroachdb/cockroach/blob/13f468f784fa9df8525601e2b8f6a4b4b500eae3/pkg/ccl/sqlccl/restore.go#L642)

[goroutines.txt](https://github.com/cockroachdb/cockroach/files/1268254/goroutines.txt)

Logs (`n1` was the host running the restore):
[logs.zip](https://github.com/cockroachdb/cockroach/files/1268257/logs.zip)

**Comment by benesch** [comment]
Thanks so much for helping us debug this, @RaduBerinde! Going to optimistically mark this as fixed by #18101.
