### ISSUE TITLE
backup: investigate turning off snappy compression in backups

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#18103]
when profiled, a big chunk of restore time is decompression and the key prefix compression in sstables might mean that the backup files aren't much bigger uncompressed

**Comment by dt** [comment]
flip-side: most backups are never restored, but do sit and take up space for some long retention period.

**Comment by danhhz** [comment]
yeah, I don't know that this is a clear win, but worth looking into. at the same time, we should even look into whether going the other way on the cpu usage vs space compression tradeoff makes sense

**Comment by petermattis** [comment]
I'd worry more about the network usage than the space or cpu usage.

**Comment by mwang1026** [comment]
Given the memory pressure of holding SSTables compression is saving us enough to be worth the minimal overhead
