### ISSUE TITLE
storage: stuck pre-candidate phase

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#18129]
As observed on `blue` and `adriatic` this week:

![image](https://user-images.githubusercontent.com/10536690/29967125-1a165e5c-8ee3-11e7-8281-7ecbafa37f33.png)
![image](https://user-images.githubusercontent.com/10536690/29967131-205eb82c-8ee3-11e7-8963-28b0a71fc86c.png)

`adriatic`:
![image](https://user-images.githubusercontent.com/10536690/29967143-33d82dd4-8ee3-11e7-91c5-f9cc289d4d98.png)
`blue`:
![image](https://user-images.githubusercontent.com/10536690/29967196-73940a24-8ee3-11e7-8e62-89323e6b7cf4.png)

MsgPreVote{,Resp} counts with later rolling restarts. notably didn’t flatline at a non-zero count (did still end up getting stuck but for a seemingly different reason).
![image](https://user-images.githubusercontent.com/10536690/29967168-526acfd6-8ee3-11e7-85d2-7e5269bf43f1.png)

**Comment by bdarnell** [comment]
Note that in this screenshot with four replicas, the one in the pre-candidate state had been removed but not yet garbage collected. It's expected that a replica in such a state would be in pre-candidate (it would be in the candidate state if pre-vote were disabled), although it's not expected that it would stay this way for long without GC.

On adriatic, we saw many instances of this with only three replicas: one leader, one follower, and one pre-candidate. The pre-candidate node in this case was not far behind the others.

**Comment by irfansharif** [comment]
+cc #18151.

**Comment by irfansharif** [comment]
Closing in favor of #18151, +cc https://github.com/coreos/etcd/issues/8501. See https://github.com/cockroachdb/cockroach/issues/18151#issuecomment-327280655:
> This sufficiently explains #18129, [...] It aligns with the fact that problem ranges didn't _always_ persist through chaos as with enough leadership changes, replicas stuck in the PreCandidate phase with higher terms were eventually overtaken by healthy replica pairs (with ever increasing terms).
