### ISSUE TITLE
sql: auto-retries are hard to test using the CLI because of the injection of extra statements

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#18120]
Consider (one batch per line):
```
BEGIN;
SELECT crdb_internal.force_retry(interval '10s');
```

We have a nice feature that allows for the second batch to be retried even though the transaction technically began on the previous batch. However, if you do perform these queries in the CLI, you'll notice that the 2nd batch is not retried automatically. That's because the shell injects statements behind batches to show the current database and transaction status. The statements break the inter-batch magic.
I'd like an option to have the shell not run statements under me.

And btw, I've noticed that the pg protocol passes the transaction status back and forth transparently, so in principle we don't need to run a `show transaction status` to get it. Except I guess that doesn't support our extended `RestartWait` state?

**Comment by knz** [comment]
You can use psql as workaround.

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
