### ISSUE TITLE
sql: cancel import jobs

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#18139]
The transformation phase of `IMPORT` jobs should support pause/resume/cancel.  

https://github.com/cockroachdb/cockroach/issues/16018 is tracking this for schema changes.

**Comment by dianasaur323** [comment]
Thanks, @benesch! I also added a line item in airtable so that we can track capacity.

**Comment by dianasaur323** [comment]
**PM Acceptance Testing**
- [ ] Run an import job
- [ ] Pause the job
- [ ] Resume the job
- [ ] Cancel the job
- [ ] Check that this surfaces currently in the admin UI
- [ ] Check for leakage in show queries
- [ ] Check how this surfaces in show jobs
- [ ] Experience should be the same as backup / restore and schema changes
