### ISSUE TITLE
ERROR:  internal/client/txn.go:836: attempting to use transaction with wrong status or finalized: COMMITTED true

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/cockroach#18133]
Please use TBL and schema from https://github.com/cockroachdb/cockroach/issues/18076

**BUG REPORT**

1. Please supply the header (i.e. the first few lines) of your most recent
   log file **for each node in your cluster**. On most unix-based systems
   running with defaults, this boils down to the output of

$ cockroach version
Build Tag:    391d19f
Build Time:   2017/08/31 16:02:30
Distribution: CCL
Platform:     darwin amd64
Go Version:   go1.8.3
C Compiler:   4.2.1 Compatible Clang 3.8.0 (tags/RELEASE_380/final)
Build SHA-1:  391d19f65fc1583fba632c203c82985442322545
Build Type:   release

[logs.zip](https://github.com/cockroachdb/cockroach/files/1270422/logs.zip)

2. Please describe the issue you observed:

- What did you do?

cat > copy.lineitem.sql <<EOF
copy lineitem from stdin;
EOF
cat copy.lineitem.sql lineitem.tbl | psql "port=26257 user=root host=127.1 dbname=tpch"

- What did you expect to see?

Data loaded.

- What did you see instead?

$ cat copy.lineitem.sql lineitem.tbl | psql "port=26257 user=root host=127.1 dbname=tpch"
ERROR:  internal/client/txn.go:836: attempting to use transaction with wrong status or finalized: COMMITTED true

Committed 100 rows instead of not committing.

$ wc -l lineitem.tbl
 6001215 lineitem.tbl

> select count(*) from lineitem;
+----------+
| count(*) |
+----------+
|      100 |
+----------+

**Comment by robert-s-lee** [comment]
@andreimatei This maybe the same issue as https://github.com/cockroachdb/cockroach/issues/17941

**Comment by andreimatei** [comment]
Thanks Robert, will look soon.

**Comment by andreimatei** [comment]
@robert-s-lee can you please attach your input file?

This might be #18175 which I just found; I think `COPY` is very broken at the moment.

**Comment by robert-s-lee** [comment]
datafile  below.  DDL attached.

https://drive.google.com/open?id=0B4ylwRfb_1ifWVQ0MFpCZWpYZk0

[tpch-ddl-cockroach.sql.zip](https://github.com/cockroachdb/cockroach/files/1271817/tpch-ddl-cockroach.sql.zip)
