### ISSUE TITLE
sql: error message with distsql=always

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#18166]
```
root@:26257> SET DISTSQL=ALWAYS;
SET

Time: 514.645µs

error retrieving the database name: pq: unsupported node *sql.valuesNode without SQL VALUES clause
```

This error also shows up on every subsequent query (presumably every time the cli prompt is rendered).

cc @knz, @mjibson

**Comment by knz** [comment]
Use \unset smart_prompt 
As workaround
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by RaduBerinde** [comment]
Always shouldn't be used, it was used for debugging. It's not a viable value for a user to set because some statements just won't work. We can remove it altogether if it keeps causing confusion.

**Comment by justinj** [comment]
I see, will close this issue then!
