### ISSUE TITLE
sql: SELECT(ROW()) -> SELECT (())

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#1817]
> 
SELECT(ROW())
data0: "SELECT (())"
panic: syntax error at or near ")"
SELECT (())

go-fuzz

**Comment by petermattis** [comment]
Explicit rows `ROW ()` are currently always output as implicit rows `()`. That clearly isn't correct in this case.

**Comment by tschottdorf** [comment]
probably a similar one:
> data0: "SELECT ((SELECT)) AS D"
data1: "SELECT (SELECT) AS D"
panic: not equal
