### ISSUE TITLE
sql: CREATE DATABASE A B C -> CREATE DATABASE A

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#1818]
> 
--- FAIL: TestParse (0.02s)
        parse_test.go:239: expected CREATE DATABASE A B C, but found CREATE DATABASE A

There needs to be an odd number of identifiers or there's a parse error.
Probably again an issue with dropping things in `sql.y`.

**Comment by petermattis** [comment]
We don't have syntax tree elements for the optional database settings that postgres allows. See http://www.postgresql.org/docs/9.0/static/sql-createdatabase.html. Probably worthwhile to just remove support for those optional elements from the grammar (e.g. `createdb_opt_with`, `createdb_opt_list`, etc).
