### ISSUE TITLE
embedding

### ISSUE THREAD

**Issue by deepch** [cockroachdb/cockroach#18237]
This is not bug, but question.
I don't want to run separate cockroach instance, but want to integrate cockroach into own program.
What is the proper way to do that (in case of master branch).
What is the proper way now?

**Comment by bdarnell** [comment]
Thanks for your interest, but we do not support (and do not plan to support) this kind of embedding. Instead, you can bundle a copy of the `cockroach` executable with your program and run it as a child process.

**Comment by deepch** [comment]
cockroach have build arm?

**Comment by bdarnell** [comment]
We do not regularly test on arm platforms or publish binaries for them, but as of this May (#14405) building from source worked on 64-bit arm (we do not support any 32-bit platforms).

**Comment by tschottdorf** [comment]
I think @nvanbenschoten has played around with this recently, and I think we broke it in some ways but perhaps he already jerry-rigged it back to working. Nathan?

**Comment by nvanbenschoten** [comment]
We broke the arm64 build with a recent change (47ccc407fbaf61d9c95d36112b9af38625e90914) that allowed us to better support older x86 architectures. @benesch and I were discussing fixing this earlier this week. I opened #18319 to track this.
