### ISSUE TITLE
ui: typography of no results

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#18244]
Should this typography look different from the rest of the ui?

![image](https://user-images.githubusercontent.com/5768024/30117924-a71a0802-92ef-11e7-9dc5-834417003277.png)

Looks like it's times new roman instead of the other font we use.

**Comment by kuanluo** [comment]
Definitely shouldn't.

**Comment by BramGruneir** [comment]
This is an easy fix, since the image is just an asset.
