### ISSUE TITLE
ci: nightly stress runs are noops

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#18240]
https://teamcity.cockroachdb.com/viewLog.html?buildId=344333&buildTypeId=Cockroach_Nightlies_Stress&tab=buildLog

We should've known something is up since there haven't been any nightly failures in a while. Example:

https://teamcity.cockroachdb.com/repository/download/Cockroach_Nightlies_Stress/344285:id/stress.log

I think it's enough to bump the `stress` dependency which I'm trying to do right now.

**Comment by jordanlewis** [comment]
Did this fix the issue?

**Comment by tschottdorf** [comment]
Definitely in local testing, but we'll know tomorrow - I'm very sure we get failures every night.

**Comment by tschottdorf** [comment]
(re: how I found out -- I was running `make stress PKG=./pkg/server TESTS=MyFlakyTest` and it printed `SUCCESS` && exit 0 right after a fat exploding stacktrace).

**Comment by tschottdorf** [comment]
judging by the 28 new stress failures opened tonight, there's little doubt that it now works again.
