### ISSUE TITLE
ui: Update graphs to match grafana

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#18253]
We synchronized the set of graphs shown in the admin UI with grafana in #12279, but it's gotten out of sync again. (Specifically, the `clock_offset_meannanos` graph, necessary for verifying NTP functionality, is not present). We should go back through and make sure that all graphs in grafana are present in the admin UI (even if some of them are buried under an advanced/debug tab).

**Comment by dianasaur323** [comment]
Ok - we can take a look at this in 1.2.

**Comment by bdarnell** [comment]
The clock offset graph is there, and I don't think there are any significant charts missing from the UI at this point.
