### ISSUE TITLE
sql: investigate spurious grpc failures with dead node in cluster

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#18264]
When decommissioning with a dead node in the cluster, we spuriously get grpc errors from an event log query, which is unexpected since it's a single-statement select query:

```go
		rows, err = db.Query(`
		SELECT "eventType", "targetID" FROM system.eventlog
		WHERE "eventType" IN ($1, $2) ORDER BY timestamp`,
			sql.EventLogNodeDecommissioned, sql.EventLogNodeRecommissioned,
		)
```

Something to investigate.

See the comment in https://github.com/cockroachdb/cockroach/pull/18220#issuecomment-327519642 and the CI failure https://teamcity.cockroachdb.com/viewLog.html?buildId=344802..

**Comment by tschottdorf** [comment]
PS: first step could be to make sure errors of the type "pq: rpc error: code = Unavailable desc = grpc: the connection is unavailable" are annotated with enough information to find out where they originated.

**Comment by jordanlewis** [comment]
Closing as stale.
