### ISSUE TITLE
ui: Incorrect tooltip for Leaseholders per Store

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#18274]
The **Leaseholders per Store** tooltip on the **Replication** dashboard is wrong:

![screen shot 2017-09-06 at 6 01 46 pm](https://user-images.githubusercontent.com/15893490/30136584-9b27dde2-932d-11e7-803c-8ecc48bd9afe.png)

It should say something like:

> The number of leaseholder replicas on each store. A leaseholder replica is the one that receives and coordinates all read and write requests for its range.

**Comment by dianasaur323** [comment]
@vilterp do you mind fixing this tool tip in addition to the other one we mentioned today?

cc @cuongdo

**Comment by vilterp** [comment]
Yep, should be able to
