### ISSUE TITLE
storage: epoch-based leases for meta2 ranges

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#18276]
Currently, we use traditional expiration-based range leases for any ranges located at or before the range containing liveness records. This includes all meta1 and meta2 ranges. As the RFC that introduced epoch-based leases [touched upon](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20160210_range_leases.md#performance-implications):

> This might be problematic in the case of meta2 address record ranges, which are expected to proliferate in a large cluster. This lease traffic could be obviated if we moved the node liveness records to the very start of the keyspace, but the historical apportionment of that keyspace makes such a change difficult. A rough calculation puts the number of meta2 ranges at between 10 and 50 for a 10M range cluster, so this seems safe to ignore for the conceivable future.

Epoch-based leases have avoided a huge bottleneck and I think it's clear that they were a necessary change. Still, I think at the moment we rely on expiration-based leases for more than we need to. I discussed this with @tschottdorf and @spencerkimball and it sounds like the only reason we can't use epoch-based leases for meta2 ranges right now is that we need meta2 to find the range-descriptor for the node liveness range. This means that if we used epoch leases for meta2 then we would create a circular dependency between meta2 and node liveness.

However, there are ways to get around this. For instance, we could gossip the node liveness descriptor like we gossip range 0's descriptor. This would allow us to use epoch leases for meta2 and avoid the overhead of expiration leases. However, even with 50 meta2 ranges, we'd only expect to see ~20 reqs / second (using the same calculations as the original RFC). Clearly, this means that it's not a pressing issue, but I figured I'd file it and start the discussion.

It's also possible I'm missing a more fundamental reason why we can't use epoch leases for meta2, in which case I'd be curious to learn.

cc. @bdarnell

**Comment by bdarnell** [comment]
`NodeLivenessSpan` is currently in `NoSplitSpans`, but I don't think this is a fundamental requirement - liveness information could (theoretically) be in multiple ranges, not just one. 

If we gossiped the liveness span's descriptor, we could use epoch-based leases for both meta1 and meta2; only the liveness span itself would need expiration-based leases. However, gossiping a range descriptor like this has tricky bootstrapping issues (which we've resolved for range 1, but I'd prefer not to duplicate this if we can avoid it)

The alternative of treating the liveness span as "meta2" range(s), resolved via meta1 (which may or may not involve actually moving them to a different part of the keyspace) is appealing as a clean-slate solution, although I don't know how we'd manage the migration. Then only meta1 and the liveness ranges would need expiration-based leases. Something to consider if we ever undertake a more fundamental migration here (such as moving to non-mvcc-based liveness records or storing descriptors under their start keys and using reverse scans).

Also note that while the number of requests used to refresh meta2 leases will grow in larger clusters, larger clusters have more capacity to handle them. In a cluster large enough to need 50 meta2 ranges, 20 reqs/sec would be negligible. We can probably just ignore this issue.

**Comment by spencerkimball** [comment]
It would be dangerous to remove the `NoSplitSpans` directive is required as
one range is responsible for gossiping the liveness records. If you remove
that and multiple ranges participate, getting to the point where I'd be
comfortable that things would behave properly would become difficult.

I think the simplest solution is to put the liveness table at the very
start of the keyspace. Given the current values for meta1 and meta2 we use
(0x00 and 0x01 prefixes) this will be very difficult from a migration
perspective, but it would require the least additional complexity to
understand how to access node liveness once it was completed.

I agree it's not worth tackling this now.
