### ISSUE TITLE
sql: add SelectClause under insertNode for default values

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#18277]
Discussed in the first comment of https://github.com/cockroachdb/cockroach/pull/17757#issuecomment-326266996.

`INSERT` statements transparently add columns to rows that do not explicitly specify
values for all columns. When a column with a default expression is not specified,
the default expression is used to generate a value. When a column without a default
expression is not specified, NULL is used for the value.

In CockroachDB, this works in two different ways, depending on the source of values in
an `insertNode`. If the source is a `ValuesClause `, the default values
both inside the tuples (`parser.DefaultVals`) and the default values for columns
not specified in the tuples are populated in [`fillDefaults`](https://github.com/cockroachdb/cockroach/blob/1a71f80dbcccb51b908089ee42ee41f2598866fb/pkg/sql/insert.go#L556). This means that by the time `insertNode` [creates a plan](https://github.com/cockroachdb/cockroach/blob/1a71f80dbcccb51b908089ee42ee41f2598866fb/pkg/sql/insert.go#L152) for the data source (in this case a `valuesNode`), the plan will be able to create all columns needed for each row. This behavior was needed for [recent optimizations](https://github.com/cockroachdb/cockroach/pull/17757) to parallel statement execution.

However, for other data sources like subqueries, we do something different. Instead of
modifying the data source that `insertNode` holds onto, we instead modify the rows that
the data source provides in [`insertNode.Next`](https://github.com/cockroachdb/cockroach/blob/1a71f80dbcccb51b908089ee42ee41f2598866fb/pkg/sql/insert.go#L384). Here, if any rows are shorter than the number of columns, they are appended to with default values. It messy that we have two ways to do this.
A cleaner way would be to wrap any data source plans that haven't gone through
`fillDefaults` (any non-`valuesNodes`) with a `SelectClause` which takes care of
creating all default values. We could then rely on values for all columns being present in each
row by the time the rows reach `insertNode`.

@mjibson you pulled `GenerateInsertRow` out into an exported function a little while ago. Was this because you were relying on the defauly expression handling?

**Comment by mjibson** [comment]
We need `GenerateInsertRow` for CSV creation:

https://github.com/cockroachdb/cockroach/blob/73336d4b4408f94ffe159d76d1c4321e3b4c1a48/pkg/ccl/sqlccl/csv.go#L428

Using that function is really useful for the CSV package because then CSV doesn't have to worry about a lot of that logic, including evaluating default expressions (which is mostly used in CSV import for `_rowid` calculation). Keeping an API that allows CSV stuff to use the same code path as the INSERT logic would be really nice.

**Comment by sum12** [comment]
@nvanbenschoten I wanted to pick up this issue. It looks like the bug could give more insights into the code.

**Comment by nvanbenschoten** [comment]
@sum12 absolutely, let me know where you'd like me to provide more insight. I just reread the issue and it seems pretty comprehensive to me, but that's probably because I'm familiar with the code. In the meantime, getting comfortable with how [`sql/insert.go`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/insert.go) works will be a big help. Specifically, focus on how default values work with the `INSERT` statement both in the case of a `VALUES` clause and a sub-query (see `fillDefaults` and `GenerateInsertRow `).

**Comment by jordanlewis** [comment]
@RaduBerinde please triage or close.
