### ISSUE TITLE
DNS Issue in Kubernetes

### ISSUE THREAD

**Issue by valentin2105** [cockroachdb/cockroach#18289]
Hi !

I try to deploy CockRoach in a k8s cluster (not on cluster.local domain) and I expected issues. 

My first pod created w/ the Statefullset, doesn't start correctly and I got this error : 

```
root@dev-cluster# docker ps |grep cockro
acb2bf1f8645        cockroachdb/cockroach-k8s-init                        "/peer-finder -on-..."   1 second ago

root@dev-cluster# docker logs -f acb
2017/09/07 06:37:06 lookup cockroachdb.default.svc.k8s-dev.my.cluster.com on 10.32.0.10:53: no such host

root@cockroachdb-0:/# dig cockroachdb.default.svc.k8s-dev.my.cluster.com @10.32.0.10 +short
192.168.178.195
```

It strange that it say `no such host` and while digging from the container, `kube-dns` work fine.

I have tried with `cockreachdb` short service name and got his : 
```
2017/09/07 06:25:44 lookup cockroachdb on 10.32.0.10:53: server misbehaving
```

Any idea ? 

Thanks.

**Comment by a-robinson** [comment]
Can you share the configuration file that you used? Most importantly, which version of the `cockroachdb/cockroach-k8s-init` image you're using?

**Comment by valentin2105** [comment]
Hi @a-robinson ,

I use `cockroachdb/cockroach-k8s-init:0.2`

The only change I made from the Statefulset of your doc is : 

try this : 

```
        args:
        - "-on-start=/on-start.sh"
        - "-service=cockroachdb.default.svc.k8s-dev.cluster.com"
```
and use `EmptyDir` to replace PV/PVClaim.

**Comment by a-robinson** [comment]
Hey @valentin2105, I'm really sorry for the slow follow-up on this.

I think that if you set your args to this, things will work better for you:

```
        args:
        - "-on-start=/on-start.sh"
        - "-service=cockroachdb"
        - "-domain=k8s-dev.my.cluster.com"
```

That's what the comment above the `initContainers` part of the config is trying to explain. Let me know how that works for you, and if you have any suggestions on improving that comment in the config file.

**Comment by valentin2105** [comment]
Hey @a-robinson , Thanks for your answer, it work at glances !
