### ISSUE TITLE
sql: enforce permissions on sql endpoint

### ISSUE THREAD

**Issue by MBerhault** [cockroachdb/cockroach#1830]
Short-term solution:
* add a namespace descriptor containing: repeated read/write string corresponding to user names
* read/write apply to the entire namespace (database). this means table creation, and all read/write operations on the table.
* default read/write entries are the root user only. a separate admin command will allow modification.

Further considerations:
* KV permissions enforcement is removed and the mysql user is passed down to the KV layer for logging purposes.
* KV endpoint restricted to root (maybe even node user)
* proper roles/policies/etc...
* alternate storage location (maybe a table) 
* get/set through sql api (create role, grant * to role, etc...)

**Comment by tamird** [comment]
> command-line tool to set permissions using database/table names

This bit is not strictly necessary IMO.

**Comment by MBerhault** [comment]
Well, we need some way of doing it. The currently prefix-based config tool assume that you know what the mapping is. It's trivial enough to do the conversion automatically.

**Comment by MBerhault** [comment]
Ok, I don't think this will work. Having authorization done at the KV layer requires way too many prefixes (unique namespace ID, namespace prefix, table prefix, etc...).
A more reasonable solution for the near-term is to store permissions in the namespace/table descriptors and perform the authorization check at the sql layer.

I'll write something up.

**Comment by MBerhault** [comment]
Privileges are enforced. Closing in favor of #2005
