### ISSUE TITLE
sqlccl: more thorough validation of data during RESTORE

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#18317]
In https://github.com/cockroachdb/cockroach/issues/18076, it looks like RESTORE happily imported some data that had been written by an early version of csv import. This early version had some bugs, so after RESTORE completed successfully, it left the cluster in a bad (and very confusing state). We should be much more thorough about validating imported data. This will definitely cause RESTORE to slow down, but current state seems too dangerous. Potentially they could be put behind a flag. A non-exhaustive list:

- validate that any NON-NULL columns are present in any row
- validate each CHECK constraint
- validate that each key and value are well-formed. we currently validate the kv entry checksum but we could also check that each primary key column is present in the kv key as well as a tailing column family and row key suffix (if applicable). kv values should be decodable and should not have any extra data at the end

**Comment by dt** [comment]
I think the answer here now is if you wanted you could choose to run scrub (or individual `VALIDATE CONSTRAINT or VALIDATE INDEX commands) if you wanted post-RESTORE validation.
