### ISSUE TITLE
storage: clean up lastTerm caching and improve testing

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#18336]
#18327 fixed [an issue](https://github.com/cockroachdb/cockroach/issues/17524) with `r.mu.lastTerm`, but didn't include any testing to accompany the change because we wanted a contained cherry-pick. We should improve testing around raft snapshots and `lastTerm` caching such that the bug fixed in #18327 would have been caught.

While doing so, there may be some room for cleaning up our handling of cached `lastTerm` and `lastIndex`. See @tschottdorf's comments in #18327.

**Comment by petermattis** [comment]
@nvanbenschoten Given that I introduced this bug in the first place, I'm willing to take on the task of adding a proper test for the fix. Do you need me to take this off your plate or have you already started on it?

**Comment by nvanbenschoten** [comment]
@petermattis I haven't started working on this, so feel free to reassign. 

`TestSnapshotAfterTruncation/differentTerm` was just re-enabled. I was thinking the test here would look similar but would avoid a restart of each node so that the in-memory caching state is preserved.
