### ISSUE TITLE
debug: link to NodeLiveness range directly from /debug

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#18360]
The state of the `NodeLiveness` range is either the root cause or an informative symptom of a ton of the wedged clusters we look at. However, it currently takes a few steps to find the range, especially on clusters where not all ranges are replicated on all nodes. This is because the range does not have a consistent rangeID. Usually what I do now is search `/_status/ranges/local` pages until I find it, but maybe there's already an easier way. If not, it would be really nice to have a `/reports/liveness-range` link on the debug page that redirects to `/reports/range/{node-liveness-range-id}`. I'd expect it to be straightforward enough to determine which range contains `NodeLiveness`.

Jira issue: CRDB-6012

**Comment by nvanbenschoten** [comment]
@vilterp may be interested in this as well.

**Comment by vilterp** [comment]
How would you determine which range contains `NodeLiveness`?

**Comment by tschottdorf** [comment]
There are several ways. The official way is to query meta2 but that won't work well when a cluster is sufficiently broken.
Sending an Rpc to all nodes and having those that have that range return its information is less brittle. We already have such an Rpc that returns all ranges, so I think all we need is adding a predicate.
Then there's also the option of gossipping the node liveness range's range descriptor from the l lease holder, but there may not be a lease holder when things break.

**Comment by nvanbenschoten** [comment]
Using a similar technique to the RPC that returns all ranges was what I had in mind. However, I think we'd only want to do any inter-node coordination if the gateway node doesn't already know about the range. Availability in the face of cluster issues is pretty important because of the nature of when/why we use these debug pages.
