### ISSUE TITLE
acceptance: nightly tpch10 restore test consistently failing

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#18367]
Latest failure:

https://teamcity.cockroachdb.com/viewLog.html?buildId=347198&buildTypeId=Cockroach_Nightlies_RestoreTpch10&tab=buildLog&_focus=2084

Looks like an Azure API auth issue.

**Comment by benesch** [comment]
Yup, looks like we forgot to rotate the fixtures bucket credentials in the nightly test. We've got a test running now that's successfully loaded the fixtures bucket, so going to optimistically mark this as fixed. (https://teamcity.cockroachdb.com/viewLog.html?buildId=347611&buildTypeId=Cockroach_Nightlies_RestoreTpch10&tab=buildLog.)

Thanks for the prod, @cuongdo!
