### ISSUE TITLE
c-deps: Investigate RocksDB DeleteRange bug

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#18371]
The TiDB team found a data corruption bug in RocksDB ([blog post](https://pingcap.github.io/blog/2017/09/08/rocksdbbug/), [issue](https://github.com/facebook/rocksdb/issues/2752), [PR](https://github.com/facebook/rocksdb/pull/2799)). We need to determine whether we are affected by this; if so we need to patch in the fix for 1.1. 

The bug relates to the `DeleteRange` operation and snapshots; we use both features and based on the test case in facebook/rocksdb#2799 I don't see any reason to assume that we're immune. The symptom is data that was deleted by DeleteRange could reappear.

**Comment by petermattis** [comment]
Sounds like the "snapshots" being referred to are TiKV range-level snapshots and the bug requires a combination of `DeleteRange` + `IngestExternalFile`. If that is the case, it would only affect restore. Still reading about this, I could be mistaken.

Cc @danhhz, @benesch

**Comment by petermattis** [comment]
Ah, the TiKV-folks talk about using `IngestExternalFile`, but the test case only uses RocksDB snapshots.

**Comment by petermattis** [comment]
I ported the test case in https://github.com/facebook/rocksdb/pull/2799/files to our code base yet I'm not seeing a failure. Sort of curious that we haven't seen any consistency check failures recently. We've been using `DeleteRange` for a while and this isn't a new bug.

**Comment by petermattis** [comment]
Oh, looks like their test is missing a `CompactRange`. After adding that, I can reproduce. I'm not seeing any reason this couldn't happen in our code. It just requires a specific order if `DeleteRange`, snapshots and compactions. 

One mitigating factor is that it looks like an explicit snapshot created via `DB::GetSnapshot` is necessary. The implicit snapshot used by iterators doesn't seem to tickle the bug. That said, we still use snapshots frequently, such as during rebalancing and splitting.

I'm going to attempt to reproduce by convincing replica GC and rebalancing to create the correct intermingling of RocksDB operations. It is possible that one of the existing remove-and-re-add tests sees this bug, but a) we're not checking for it and b) we don't use `DeleteRange` unless there are a certain number of keys.

**Comment by petermattis** [comment]
Btw, the fix is [relatively small](https://github.com/facebook/rocksdb/commit/4c05a1b38137c320c026dbd2d8b800ce1fa04dda.patch) and I've verified it fixes my reproduction. We might want to just apply it.

**Comment by benesch** [comment]
Agreed, given the size of the patch I think we should just apply it. What are the other options for 1.1? Disabling `DeleteRange` entirely?

**Comment by bdarnell** [comment]
Yeah, let's just apply it.

**Comment by petermattis** [comment]
Ok. I'll add it to #18374.

**Comment by bdarnell** [comment]
Since the bug's been around a while, should we backport it to 1.0 too?

**Comment by petermattis** [comment]
> Since the bug's been around a while, should we backport it to 1.0 too?

Are we going to do a 1.0.7? Or should we squeeze it into 1.0.6? I can whip up a cherrypick quickly.

**Comment by bdarnell** [comment]
I think if it's ready today we could put it in 1.0.6 (we haven't started qualifying a specific build yet)

**Comment by petermattis** [comment]
The RocksDB patch didn't apply cleanly to the version of RocksDB we're using on the `release-1.0` branch.
