### ISSUE TITLE
ui: window title always "Cockroach Console"

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#18408]
This isn't particularly helpful, and makes it complicated to navigate the history.

It should be more descriptive, for example `Cockroach - Report - Range 767` but anything is better than what we have today.

@dianasaur323 for triage (I'd suggest 1.2 unless it's a lot of work, which I hope it's not).

**Comment by dianasaur323** [comment]
Ha! Okay, we can get to it when we squash some bugs in 1.2. Funny - I never have this problem because I always have too many tabs open.

**Comment by tschottdorf** [comment]
This is a problem you're gonna have if you navigate the UI for a bit, for example to check out various debug or graph pages:

![image](https://user-images.githubusercontent.com/5076964/30307749-798ed350-974e-11e7-8463-69a2e21cb163.png)

**Comment by dianasaur323** [comment]
ah, good to know. thanks for the additional detail. That looks annoying...

**Comment by couchand** [comment]
Yes. :+1::+1: for getting changing page titles as you navigate around.  That would be big.  Shouldn't be much work, just bikeshedding on names is all.

**Comment by dianasaur323** [comment]
Cools, just bumped it up in priority, so we should get to it when we do our bug squashing week.
