### ISSUE TITLE
Feature request: cast strings to arrays

### ISSUE THREAD

**Issue by ivan** [cockroachdb/cockroach#18419]
PostgreSQL can cast strings to arrays:

```
postgres=# SELECT '{}'::int[];
 int4 
------
 {}
(1 row)

postgres=# SELECT '{}'::oid[];
 oid 
-----
 {}
(1 row)
```

while CockroachDB fails with `invalid cast`:

```
root@:26257/> SELECT '{}'::int[];
pq: invalid cast: string -> INT[]
root@:26257/> SELECT '{}'::oid[];
pq: invalid cast: string -> OID[]
```

This came up while attempting to rewrite the [postgrex bootstrap query](https://github.com/elixir-ecto/postgrex/blob/f31048a8e9b21984a9e7b68eae069bd12a3691c7/lib/postgrex/types.ex#L73-L82) to not use a [correlated subquery](https://github.com/cockroachdb/cockroach/issues/3288); i.e. from

```sql
SELECT t.oid, t.typname, t.typsend, t.typreceive, t.typoutput, t.typinput,
       t.typelem, coalesce(r.rngsubtype, 0), ARRAY (
  SELECT a.atttypid
  FROM pg_attribute AS a
  WHERE a.attrelid = t.typrelid AND a.attnum > 0 AND NOT a.attisdropped
  ORDER BY a.attnum
)
FROM pg_type AS t
LEFT JOIN pg_range AS r ON r.rngtypid = t.oid;
```

to

```sql
SELECT t.oid, t.typname, t.typsend, t.typreceive, t.typoutput, t.typinput,
       t.typelem, coalesce(r.rngsubtype, 0), coalesce(atttypids, '{}'::oid[])
FROM pg_type AS t
LEFT JOIN pg_range AS r ON r.rngtypid = t.oid
LEFT JOIN (
  SELECT attrelid, array_agg(atttypid) AS atttypids
  FROM pg_attribute
  WHERE attnum > 0 AND NOT attisdropped
  GROUP BY 1
) a ON a.attrelid = t.typrelid;
```

That second `coalesce` fails because it can't cast `'{}'`.

As a workaround, I found the PostgreSQL-incompatible `array[]:::oid[];` (I am totally bewildered by the triple colon) and `ANNOTATE_TYPE(array[], oid[])`, also incompatible.

**Comment by dianasaur323** [comment]
thanks for the request @ivan. We will take a look and triage.

**Comment by justinj** [comment]
Hey @ivan! This has been added in #18588, unfortunately it doesn't look like it's going to make it into CockroachDB 1.1, but you can expect it in 1.2!
