### ISSUE TITLE
improve UX of decommissioning node

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#18447]
I'm currently trying to decommission a node, and the scrolling record format seems like a relatively odd experience in the terminal....

![image](https://user-images.githubusercontent.com/5768024/30332704-0320bdf4-97a9-11e7-8747-6ac813fa51c3.png)

Is there any way for us to show a scrollbar of progress instead?

**Comment by tschottdorf** [comment]
That sounds like a ball of hair to me, but I think @knz knows better whether that's a feasible (and/or worthwhile) goal.

**Comment by knz** [comment]
The current UI choice is ... odd. I think we can find a saner default. I'll look into it.
