### ISSUE TITLE
ui: inactive range shown as problematic when raft lease wanders off

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#18453]
Forked from https://github.com/cockroachdb/cockroach/issues/18339#issuecomment-328886494.

The range below is likely quiescent (though this isn't showed, filed as #18450) and its Raft leader at some point moved away from the lease. If there were a write on this range, the situation would remedy itself, but until that happens, the problem ranges endpoint will consider this range as "no lease". That isn't ideal as there doesn't appear to be a problem.

@petermattis suggested:

> We could unquiesce a range when leader-not-leaseholder is detected. When the range quiesces it will try to move the leader to the leaseholder. Seems straightforward to do this, though I wonder if there will be unforeseen side-effects.

![image](https://user-images.githubusercontent.com/5076964/30335301-efca9b88-97af-11e7-9907-5a64c5733e56.png)

@cuongdo for triage.

**Comment by BramGruneir** [comment]
I'm going to add the raft state of `quiescent` to the range debug page.
See #18450 as the tracking issue.
