### ISSUE TITLE
ui: problemranges page should show whether replica is quiesced

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#18450]
It shows "dormant" but not quiesced.

@cuongdo for triage.

**Comment by cuongdo** [comment]
@vilterp could you take a look at this? note that this is for 1.1

**Comment by BramGruneir** [comment]
So, to start off, here are the conditions for all of the problem ranges:
```
Unavailable:          metrics.RangeCounter && metrics.Unavailable,
LeaderNotLeaseHolder: metrics.Leader && metrics.LeaseValid && !metrics.Leaseholder,
NoRaftLeader:         !storage.HasRaftLeader(raftStatus) && !metrics.Quiescent,
Underreplicated:      metrics.Leader && metrics.Underreplicated,
NoLease:              metrics.Leader && !metrics.LeaseValid && !metrics.Quiescent,
```
Note that to be listed as `no lease`, requires that the range not be quiesced.

As for the raft state, we currently call a replica/range `dormant` if it has no raft state.   But we actually should be able to detect if it is quiesced at that point too.  So I'll be threading that into the range debug page and replacing `dormant` with `quiescent` when the range has been quiesced.  But it will also be grayed out and treated exactly as `dormant` replicas are treated currently.
