### ISSUE TITLE
A confuse point in design.md

### ISSUE THREAD

**Issue by YuleiXiao** [cockroachdb/cockroach#1846]
In Range Metadata, there is a sentence below:
Note: we append the end key of each range to meta[12] records because the RocksDB iterator only supports a Seek() interface which acts as a Ceil().

My confuse point is that what is "meta[12]" meaning? meta1 and meta2? But I see meta{1,2} in other place to express meta1 and meta2.

**Comment by tamird** [comment]
Looks like a typo to me. Can you send a PR?

**Comment by YuleiXiao** [comment]
@tamird sure, I am very glad to do this.
