### ISSUE TITLE
sql: provide better visibility into SQL statements that conflict

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#18473]
When a SQL statement needs to be retried due to a conflict the user sees this error suggesting a need to retry:
```
pq: restart transaction: HandledRetryableTxnError: TransactionRetryError: retry txn "sql txn" id=63a1d5ad key=/Table/61/1/"job_node3_13"/3/0 rw=true pri=0.01104549 iso=SERIALIZABLE stat=PENDING epo=0 ts=1
505263218.003813988,662 orig=1505263218.003813988,508 max=1505263218.003813988,508 wto=false rop=false seq=3
```

A user would also like to dive into why their query is seeing a conflict. This can mean returning the sql statements involved in the conflict for instance. What we see in this error is some internal key which cannot be connected to the user domain easily.

**Comment by dianasaur323** [comment]
assigning for 1.2 milestone, but feel free to move it around.

cc @awoods187

**Comment by bdarnell** [comment]
On the "distributed" tab of the admin dashboard, there's a graph of "kv transaction restarts". this won't help you find any specific conflict but it will tell you what category of transaction restarts is most common on your cluster. In 1.1, these reason codes are included in the TransactionRetryError message. If it's "forwarded timestamp (iso=serializable)", then you may be able to reduce these by running the restarting transactions in SNAPSHOT isolation mode (if you're ok with the possibility of write skew anomalies). Interpretation of the other restart reasons is less clear-cut.

**Comment by andreimatei** [comment]
The truth is that I don't think general progress on this issue is easy;  I'm going to remove my name and the milestone because I don't know what to do about it in a general sense. Going from conflicts to statements is sometimes impossible (if you ran into the ts cache, you don't know performed the respective read - in fact, it might not be one query).  On a write/write there's no way to go from an intent to a query; perhaps there could be if we somehow plumbed debug data to all the intents, but we'd have to figure out the security implications (who can see what other queries).

**Comment by tschottdorf** [comment]
I think this will become more relevant as we see more users with complex contended workloads. I was running such a workload today on a geo-distributed cluster (https://github.com/cockroachdb/cockroach/issues/17611) and ended up with minute-long transactions and apparently complex interaction patterns. There was no way to visualize those; tracing is supposedly our tool for this task but the number of spans is overwhelming and it's hard to glean any patterns from it.

For example:

![image](https://user-images.githubusercontent.com/5076964/32807927-82718e3e-c95f-11e7-937b-dfc7892fa0ff.png)

![image](https://user-images.githubusercontent.com/5076964/32807952-99dd21a0-c95f-11e7-9a67-6ebc34165f7a.png)



It's not clear what the right visualization is, though.

**Comment by dianasaur323** [comment]
If you come up with any metrics, please add them to this open issue https://github.com/cockroachdb/cockroach/issues/19476. Eventually, this will wrap into a query analysis tool that many existing databases have, but this is a first step to collecting the metrics we need.

**Comment by asubiotto** [comment]
cc @tbg do you want to keep this open?
