### ISSUE TITLE
sql: UPSERT should behave like INSERT ON CONFLICT

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#18474]
```
CREATE TABLE a (
    pk INT PRIMARY KEY,
    no_def STRING,
    def STRING default 'default'
);
 
insert into a values (1, 'foo', 'not the default');
select * from a; -- def column does not have the default
upsert into a values (1, 'bar');
select * from a; -- upsert has overridden the non-default value with the default value
```

this behavior is similar to mySQL and to achieve the expected behavior the user has to use
INSERT ON CONFLICT.

http://www.postgresqltutorial.com/postgresql-upsert/

suggests that INSERT ON CONFLICT is postgres's UPSERT. I think it makes sense for us to
change the behavior of UPSERT to be inline with INSERT ON CONFLICT

**Comment by vivekmenezes** [comment]
https://www.cockroachlabs.com/docs/stable/upsert.html

suggests they are the same

**Comment by robertslee** [comment]
An option to think about is to change name of the current "upsert" to "replace" and create upsert 
 with options that do not overwrite so that current users of upsert the do want the "replace" behavior is not surprised by different behavior.

**Comment by knz** [comment]
Wow

1) the work description in this issue is far-reaching in UX changes. This work *must* go through a RFC. 

2) the work here is probably non-trivial. Vivek perhaps we can brainstorm to check this fits in Joey's time frame

A more reasonably sized chunk of work is found in #8330, which overlaps with this issue but is limited to the current functionality.

**Comment by bdarnell** [comment]
UPSERT already behaves similarly to INSERT ON CONFLICT. The question is how the query rewriting happens (whether default values are used for the UPDATE case or only for the INSERT). It's not obvious to me which form is "correct" or expected, although it does seem like it's probably more useful to only use the explicit columns in the UPDATE portion (the justification for the alternative is that in general, UPSERT means "make this row look like it would after this INSERT, even if it already exists". Additionally, an UPSERT that overwrites with defaults can take advantage of the 1PC optimization. One that keeps unreferenced columns the same cannot)

However, even if the proposed behavior is desirable, we have to be careful with backwards compatibility. Given that the partial overwrite is possible with an explicit INSERT ON CONFLICT, I think I'm -1 on making this change.

**Comment by vivekmenezes** [comment]
I'm inclined to close this issue and ask docs to document this difference

**Comment by dianasaur323** [comment]
this sounds like something that @awoods187 or @nstewart could provide an opinion on.

**Comment by knz** [comment]
I have analyzed this issue further and I am of the opinion we should keep the current behavior but update the docs to highlight this difference.

**Comment by knz** [comment]
@rmloveland do you want to take this over?

**Comment by rmloveland** [comment]
@knz yes, thanks - created a linked docs issue

**Comment by asubiotto** [comment]
@RaduBerinde could you triage/close?

**Comment by RaduBerinde** [comment]
The desired effect can be achieved by specifying the subset of the columns that we are upserting on:
```
> upsert into a (pk, no_def) values (1, 'bar');
> select * from a;
  pk | no_def |       def
-----+--------+------------------
   1 | bar    | not the default
(1 row)
```
