### ISSUE TITLE
ui: new version available warning does not line up with events log / summary

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#18480]
If we redesign the event log, this might be rendered useless, but this currently does not line up.

![image](https://user-images.githubusercontent.com/5768024/30386819-ce3c1c34-9878-11e7-9937-f2310ec01c62.png)

p.s. @kuanluo we might have to account for how warnings will show up in our cluster events on graphs re-design.

**Comment by kuanluo** [comment]
Good points, @dianasaur323. Thank you for catching that - let's take a look on events on graph first, and then determine what to do about this issue. Regardless, it'd be a very easy fix for @mrtracy.
