### ISSUE TITLE
exterminate crash

### ISSUE THREAD

**Issue by YuleiXiao** [cockroachdb/cockroach#1850]
bc@ubuntu:~/work/my_cockroach/bin$ ./cockroach  exterminate --stores=./ccdata
E0729 21:27:56.663584 28603 cli/start.go:193  failed to initialize context: invalid or empty engines specification "./ccdata", did you specify --stores?
bc@ubuntu:~/work/my_cockroach/bin$ ./cockroach  exterminate --stores=ssd=./ccdata
I0729 21:28:12.695688 28680 server/context.go:168  initialized 1 storage engine(s)
I0729 21:28:12.956275 28680 cli/start.go:204  shutdown node in anticipation of data extermination: ok

I0729 21:28:12.956382 28680 cli/start.go:210  exterminating data from store [ssd]=./ccdata
F0729 21:28:12.956760 28680 cli/start.go:212  unable to destroy store [ssd]=./ccdata: IO error: lock ./ccdata/LOCK: Resource temporarily unavailable
goroutine 1 [running]:
github.com/cockroachdb/cockroach/util/log.stacks(0xc2080be301, 0x0, 0x0, 0x0)
	/home/bc/work/my_cockroach/src/github.com/cockroachdb/cockroach/util/log/clog.go:867 +0xcd
github.com/cockroachdb/cockroach/util/log.(*loggingT).outputLogEntry(0x18d99c0, 0x3, 0x156b714, 0xc, 0xd4, 0x0, 0xc2080be3c0)
	/home/bc/work/my_cockroach/src/github.com/cockroachdb/cockroach/util/log/clog.go:739 +0x11b
github.com/cockroachdb/cockroach/util/log.AddStructured(0x0, 0x0, 0x7f9700000003, 0x2, 0x11d9f90, 0x1e, 0xc2080e3b78, 0x2, 0x2)
	/home/bc/work/my_cockroach/src/github.com/cockroachdb/cockroach/util/log/structured.go:39 +0x120
github.com/cockroachdb/cockroach/util/log.logDepth(0x0, 0x0, 0x1, 0xc200000003, 0x11d9f90, 0x1e, 0xc2080e3b78, 0x2, 0x2)
	/home/bc/work/my_cockroach/src/github.com/cockroachdb/cockroach/util/log/log.go:65 +0x82
github.com/cockroachdb/cockroach/util/log.Fatalf(0x11d9f90, 0x1e, 0xc2080e3b78, 0x2, 0x2)
	/home/bc/work/my_cockroach/src/github.com/cockroachdb/cockroach/util/log/log.go:168 +0x75
github.com/cockroachdb/cockroach/cli.runExterminate(0x1837480, 0xc208036e60, 0x0, 0x1)
	/home/bc/work/my_cockroach/src/github.com/cockroachdb/cockroach/cli/start.go:212 +0x6d6
github.com/spf13/cobra.(*Command).execute(0x1837480, 0xc208036e10, 0x1, 0x1, 0x0, 0x0)
	/home/bc/work/my_cockroach/src/github.com/spf13/cobra/command.go:496 +0x65c
github.com/spf13/cobra.(*Command).Execute(0x1835400, 0x0, 0x0)
	/home/bc/work/my_cockroach/src/github.com/spf13/cobra/command.go:561 +0x18d
github.com/cockroachdb/cockroach/cli.Run(0xc20800a010, 0x2, 0x2, 0x0, 0x0)
	/home/bc/work/my_cockroach/src/github.com/cockroachdb/cockroach/cli/cli.go:119 +0x88
main.main()
	/home/bc/work/my_cockroach/src/github.com/cockroachdb/cockroach/main.go:49 +0x29d

goroutine 5 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x18d99c0)
	/home/bc/work/my_cockroach/src/github.com/cockroachdb/cockroach/util/log/clog.go:1019 +0x75
created by github.com/cockroachdb/cockroach/util/log.init·1
	/home/bc/work/my_cockroach/src/github.com/cockroachdb/cockroach/util/log/clog.go:606 +0xcc

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 7 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 19 [select]:
net/http.(*persistConn).writeLoop(0xc20806c000)
	/usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:661 +0xcbc

goroutine 18 [IO wait]:
net.(*pollDesc).Wait(0xc208010530, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010530, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2080104d0, 0xc208032c00, 0x400, 0x400, 0x0, 0x7f97a9677208, 0xc20810c0d8)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc208104028, 0xc208032c00, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
crypto/tls.(*block).readFromUntil(0xc2080a0c90, 0x7f97a967aa40, 0xc208104028, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:454 +0xe6
crypto/tls.(*Conn).readRecord(0xc20808c580, 0x17, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:539 +0x2da
crypto/tls.(*Conn).Read(0xc20808c580, 0xc20810a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:904 +0x166
net/http.noteEOFReader.Read(0x7f97a967aea8, 0xc20808c580, 0xc20806c058, 0xc20810a000, 0x1000, 0x1000, 0xf871c0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc2080b2080, 0xc20810a000, 0x1000, 0x1000, 0xc208014400, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc2080b00c0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc2080b00c0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc20806c000)
	/usr/local/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:660 +0xc9f

**Comment by MBerhault** [comment]
I'm getting that too when calling exterminate with a running server. It works fine when the server is not running. I'll take a look.

**Comment by MBerhault** [comment]
Two things:
* cockroach exterminate does not consume the --addr flag, so it always issues the /quit to localhost:8080
* it does not wait until the server has actually quit so the lock file will not be released

the first one's easy. The second one may need polling of some sort after issuing the quit command.
We should also fail more gracefully.

**Comment by YuleiXiao** [comment]
We should not crash after fail.

**Comment by MBerhault** [comment]
Fixed crash and missing connection parameters (needed to issue the quit).
If the server is running, this may fail even if the quit succeeds due to the rocksdb.Destroy being called too quickly. In this case, the same command should be run again.
