### ISSUE TITLE
sql: strange message after running \q

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#18509]
A little bit of a nitpick UI issue, but when I run \q as suggested by the sql client, I get the following message.

![image](https://user-images.githubusercontent.com/5768024/30493420-fd867d50-9a11-11e7-8ad4-11cfd9a65db2.png)

The error message and failure probably isn't what we want to expose to users?

cc @awoods187

**Comment by jordanlewis** [comment]
I can't reproduce this - @dianasaur323 please re-open if you can!
