### ISSUE TITLE
pgwire: ODBC error: "unknown variable: transaction_isolation" with crdb 1.1

### ISSUE THREAD

**Issue by dcs76** [cockroachdb/cockroach#18506]
While initially opening an ODBC connection to a crdb cluster, using the official PG driver, I get error: "unknown variable: transaction_isolation".

**Comment by knz** [comment]
The pgwire connection manager should recognize this variable when the connection is established, and configure the default transaction isolation level accordingly. Needs to check the format that pg uses when connecting, it may be different than what used in a BEGIN statement.

**Comment by mjibson** [comment]
I was not able to reproduce this error. I installed the postgres odbc from the ubuntu package https://packages.ubuntu.com/xenial/odbc-postgresql which uses 09.03.0300. I was able to connect to a cockroach server using isql and run some queries. Can you describe your system and the various versions of cockroach, postgres-odbc and whatever else may be relevant?

**Comment by knz** [comment]
@dcs76 please share to us the connection code that you use to open the connection.

**Comment by dcs76** [comment]
The system where the cluster is running is a Windows 2012 R2 Server.

I've tried to connect to the cluster locally and also from a Windows 7 Enterprise Workstation, using the official PostgreSql x64 driver, the version I'm using is: 09.06.0410 downloaded from here:
https://ftp.postgresql.org/pub/odbc/versions/msi/psqlodbc_09_06_0410-x64.zip

I'm starting the cluster with these parameters (I'm leaving out the server's host name below):

```
start --insecure --http-port=9090 --host=<serverhostname> --store=type=mem,size=20GiB

CockroachDB node starting at 2017-09-21 11:01:48.3062494 -0500 CDT (took 0.7s)
build:      CCL v1.1-beta.20170907 @ 2017/09/07 20:47:24 (go1.8.3)
admin:      http://<serverhostname>:9090
sql:        postgresql://root@<serverhostname>:26257?application_name=cockroach&sslmode=disable
logs:
store[0]:   type=mem,size=20 GiB
status:     initialized new cluster
clusterID:  931cb50f-1d11-4927-813f-16a167ea3054
nodeID:     1
```

I see the error in the Windows ODBC Manager while trying to test the connection with these parameters:

```
Database: rtdb
Server: <serverhostname>
Port: 26257
SSL Mode: disabled
```

Thanks,

Daniel.

**Comment by BrianSullivan1956** [comment]
Some drivers issue 'show transaction_isolation' as part of the initialization handshake
Cockroach returns the error:  unknown variable: "transaction_isolation"
Believe it expects the value from: 
    select setting from pg_settings where name= 'transaction isolation level';
    
Any driver can issue the command and validate the reply.

**Comment by knz** [comment]
Thanks I'm addressing this in #20264.
