### ISSUE TITLE
Is the column "table_catalog" missing in the table "information_schema.table_constraints"?

### ISSUE THREAD

**Issue by Vincent-Pang** [cockroachdb/cockroach#18525]
According to the SQL spec ISO/IEC 9075:1999 (sorry for that I don't have any newer spec),
section "21.40 TABLE_CONSTRAINTS base table", the following columns are missing in cockroachdb:

TABLE_CATALOG
IS_DEFERRABLE
INITIALLY_DEFERRED

FYI:
The reason that I concern with the column "table_catalog" is because I am using an ORM lib [typeorm](https://github.com/typeorm/typeorm) with typescript. When it try to synchronize my schema classes with the db, it will perform sth like
```
SELECT xxx FROM information_schema.table_constraints WHERE table_catalog = yyy ....
```

Thanks.

**Comment by jordanlewis** [comment]
Thanks for reporting this, I agree that we're missing these columns.

**Comment by jordanlewis** [comment]
@vivekmenezes for triage, could be a good quick ramp up to learn about our virtual tables

**Comment by bsnyder788** [comment]
I would like to take this one on @jordanlewis. Any pointers on this one?

**Comment by jordanlewis** [comment]
@bsnyder788 very sorry for the delay. This dropped off my radar. You are more than welcome to pitch in here.

Check out `information_schema.go` for the definition.

**Comment by bsnyder788** [comment]
thanks @jordanlewis, I will check it out!

**Comment by catroot** [comment]
Also pls add some more sensitive columns:
`peewee.ProgrammingError: relation "information_schema.constraint_column_usage" does not exist`
is it possible to make an `information_schema` 1-to-1 like it done in postgres?

**Comment by jordanlewis** [comment]
Hi @catroot, going to open a new issue for `constraint_column_usage`. This one should have been closed earlier.
