### ISSUE TITLE
sql: ignore casing for non-quoted identifiers

### ISSUE THREAD

**Issue by MBerhault** [cockroachdb/cockroach#1852]
most sql servers ignore casing for all identifiers, except when quoted.
Some upper-case everything (mysql), others lower-case (postgres). Most also have an option to enable case-sensitivity.

Currently, we lower-case databases when writing the id entry, but not when looking it up. Out table names are entirely case-sensitive.

We should figure out what to do. At the very least, we need to be consistent.

**Comment by bdarnell** [comment]
MySQL's case-sensitivity for table and database names depends on the underlying filesystem and table type (https://dev.mysql.com/doc/refman/5.0/en/identifier-case-sensitivity.html).

**Comment by MBerhault** [comment]
yeah, I saw that part. it's even more insane than casing everything consistently and is exactly the type of behavior I want to avoid.
I would propose we pick one (I prefer lowercase, I don't particularly like having computers shout at me), and apply it to everything. I would also suggest we ignore casing within quotes, but there may be a good argument for those, I just can't think of it.

**Comment by bdarnell** [comment]
What do you mean by "ignore casing within quotes"?

**Comment by MBerhault** [comment]
in case-insensitive mode (sometimes the default, sometimes an option, depending on the sql server implementation), case sensitivity is still applied to quoted identifiers.
eg: select "Foo" from blah would keep Foo capitalized, even in case-insensitive mode.
select foo from blah would not.

**Comment by tamird** [comment]
Is this implemented in https://github.com/cockroachdb/cockroach/pull/2021?

**Comment by petermattis** [comment]
#2021 Uses case-insensitive matching for table names and column names. Quotes are ignored. So `"Foo"` and `foo` are equivalent. I'll add a test case demonstrating this behavior. Whether this is the desired behavior is different, but we should be consistent now in always doing case-insensitive comparisons of names.
