### ISSUE TITLE
distsql: de-duplicate local aggregations for distributed aggregation functions

### ISSUE THREAD

**Issue by richardwu** [cockroachdb/cockroach#18534]
## Background

For some aggregation functions, we can locally compute the aggregate values on the range leaseholders before finally computing the value aggregate value in a [local-final aggregation architecture](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/distsqlplan/aggregator_funcs.go#L92L227).

## Inefficiency 

Between any `n` aggregations on the same columns, many compute the same `n` local aggregations (e.g. if we performed `AVG` and `SUM` on column `@1`, they both compute `SUM(@1)` on all local nodes). These `n` equivalent local aggregations (equivalence defined on equivalent column id and aggregate function) can be reduced to just `1` aggregation each.

## Visualization

In a contrived and more complex example, many of these [local aggregations are duplicated](https://cockroachdb.github.io/distsqlplan/decode.html?eJzcVk-Lo04Qvf8-hdTJkIJJq_nnqcJkAsJvMrsmmcsig5suJJCxQ2tglyHffVF3NiqbdiGXkFt1Vz3fq3oF7QekSvIyfucM_G8gAMEBBBcQPEAYQoRw0GrLWaZ0UVIBAvkD_AHCLj0c8-I6QtgqzeB_QL7L9ww-rOPvew45lqwBQXIe7_YlyUHv3mP9k2Scx4AQcipZ-xYJtMhBi1y0yEPLtkn0yen1ye31yYPohKCO-Zkwy-OEwRcn_HdRsyTRnMS5amlabZ5tEj3AKnKK6PFls1z_jstb90_k1fJlvPoazoPFov4NUasRjRqng2fYu9isc7HZc4_HVGnJmmWjxeh05ThWm-e3oBDaGsOn5FrFqDgtguXs_7fVej5_erVpjDRBmp4Tr7MwmC0fn2wSAyQhkMR5AqLkaG7Gw-di0PCBRmjRGC2aoEXTi9NyG9MSt7ivHaLua1-dW3SgQ9R9OeDeogMdou7LAe8WHegQdV8OdPwihJwdVJpx6_X8-5cHxavKMuHqCc7UUW_5i1bbkqY6vpS48kJylldZUR2CtEoVAutgYQQ7DbBogx0zcwe1a0R7ZrB3je6hETwyM4-uYR4bwRMz8-Qa5qnZq0HHmpiXrM0dnf77FQAA__-t0YJ8).

## Additional thoughts

One could also make the argument that we can de-duplicate aggregation functions in the final stage. For simple 1-function final stages, this maps 1-1 to the SQL function and thus can be optimized by the query optimizer. For 2+ final stages (e.g. `AVG`), duplication may exist on the distributed aggregation level that will not be handled by the query optimizer.

cc: @RaduBerinde @vivekmenezes

**Comment by andreimatei** [comment]
FWIW, Postgres has added support for reusing intermediate aggregations across aggregation expressions in a recent version.
