### ISSUE TITLE
sql: support pg_get_viewdef builtin

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#18537]
This straightforward builtin function returns the statement that a view was created from.

https://www.postgresql.org/docs/9.6/static/functions-info.html

We don't need to support the deprecated overloads that take a view name - just the ones that take an `oid`.

**Comment by bsnyder788** [comment]
@jordanlewis I would like to take a stab at this one, if its up for grabs. Any pointers appreciated, thanks!

**Comment by jordanlewis** [comment]
Sure @bsnyder788 your help would be appreciated!

Check out the implementation of `SHOW CREATE VIEW` in `show.go`, and the implementation of the `pg_get_indexdef` builtin in `pg_builtins.go`. Let me know if you need some more pointers.

**Comment by bsnyder788** [comment]
Thanks Jordan, I appreciate the nudge in the right direction.

**Comment by bsnyder788** [comment]
Link to PR: https://github.com/cockroachdb/cockroach/pull/18618

**Comment by jordanlewis** [comment]
Closed by #18618.
