### ISSUE TITLE
Non Blocking IO based java driver.

### ISSUE THREAD

**Issue by jRoadie** [cockroachdb/cockroach#18559]
Any plan about that? World is going async.

**Comment by jordanlewis** [comment]
Sorry, we don't have plans (or resources) to create custom language drivers for CockroachDB at this time. There's good news though: any Postgres-compatible driver will work at the wire level with CockroachDB. I suggest checking on any efforts to create an NIO JDBC driver for Postgres, as those will likely satisfy your need.
