### ISSUE TITLE
ui: Stack/sum user+system CPU time

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#18550]
The total CPU time in use is more interesting than the user/system split, so the CPU time graph would be better if we stacked the graphs instead of plotting them individually (if our graph framework doesn't make stacked graphs easy, a single graph of the sum is probably more useful than two separate graphs)

**Comment by dianasaur323** [comment]
ok thanks ben. Will triage for 1.2.

**Comment by vilterp** [comment]
Fixed by #28596. It just sums them, since our graphing framework doesn't (yet) support stacking.
