### ISSUE TITLE
How do I remove a node from a cluster?Not quit

### ISSUE THREAD

**Issue by springrain** [cockroachdb/cockroach#18583]
How do I remove a node from a cluster?Not quit
I didn't find it in the document,Thanks very much.

**Comment by knz** [comment]
`cockroach node decommission`

(also: `cockroach quit --decommission`)

**Comment by knz** [comment]
https://www.cockroachlabs.com/docs/v1.1/remove-nodes.html

**Comment by knz** [comment]
@springrain does this answer your question? Do you need to know anything else?

**Comment by dianasaur323** [comment]
ps, this is a 1.1 feature, which hasn't been released yet.

**Comment by springrain** [comment]
That's my answer, thank you very much
