### ISSUE TITLE
core: backup/restore seems to affect node liveness

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#18598]
In lieu of the work we are doing in 1.2 to improve node liveness...

I ran a simple tcph scale factor one backup to an amazon s3 bucket. I've now successfully messed up the admin UI:

![image](https://user-images.githubusercontent.com/5768024/30605656-ef761b20-9d3c-11e7-98d2-44b04bb80c9e.png)

![image](https://user-images.githubusercontent.com/5768024/30605663-f4c62a70-9d3c-11e7-9014-2163a09d594b.png)

It came back up after 5 minutes, but I wouldn't expect backup / restore to effect my ability to monitor both backup / restore progress and the cluster in general.

**Comment by a-robinson** [comment]
Interesting, I knew we had seen liveness issues during restores but I didn't know we had run into them during backups. Is this something you've hit before, @benesch?

**Comment by benesch** [comment]
Backup definitely impacts P99 latency, but I don't know that we've seen liveness failures before. @danhhz would know more.

**Comment by dianasaur323** [comment]
I'm currently running another incremental backup on a database, and am experiencing the same issue. Can't see anything on the admin UI.

**Comment by danhhz** [comment]
I've also never seen this on a backup before

**Comment by dianasaur323** [comment]
it might have to do with the fact that we are using really small DO machines (I believe we are on 2GB machines).

**Comment by a-robinson** [comment]
They're also very geographically spread out, right?

**Comment by dianasaur323** [comment]
yes, but actually I just saw a PR land where @mrtracy is fixing how sensitive the admin UI is to node liveness, so that should fix the fact that all nodes look dead. I'm still stuck on why the time series metrics don't show up though.

If we are going to push out the geographic story in 1.2 with partitioning, this appears to be something we should test...

**Comment by a-robinson** [comment]
Node liveness was made much more stable back in December, so this is probably closable as fixed, but do you have reproduction steps @dianasaur323?

**Comment by dianasaur323** [comment]
@a-robinson I haven't seen this in a while, so I think it's safe for us to close for now

**Comment by benesch** [comment]
:tada:
