### ISSUE TITLE
ui: double check all metrics in database page

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#18593]
Some of these numbers and columns don't seem to match up with what I am observing in the database. I will update this issue later, but assigning to myself for PM investigation for now.

- [x] https://github.com/cockroachdb/cockroach/issues/18594
- [x] https://github.com/cockroachdb/cockroach/issues/13888
- [ ] https://github.com/cockroachdb/cockroach/issues/19347

**Comment by couchand** [comment]
The last issue stands on its own.
