### ISSUE TITLE
backup/restore: cockroach dump status tracking

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#18592]
This may be a question more so than a feature request, but how do I figure out if cockroach dump is running?

![image](https://user-images.githubusercontent.com/5768024/30603652-2fbf3484-9d36-11e7-967a-a962b5205c55.png)

I'm running a dump of all data and tables in tpch on the pm cluster, which I know will take a while, but I'm not able to see that it is running on the cluster, and I can't figure out how far along I am.

**Comment by tschottdorf** [comment]
ls -lh yourfile.sql

**Comment by bdarnell** [comment]
It should show up in `SHOW QUERIES`. You can also install the `pv` program and pipe it between the `cockroach dump` command and `> backup_customer.sql`:

    cockroach dump tpch --certs-dir=./certs | pv > backup_customer.sql

**Comment by dianasaur323** [comment]
Next step here is for diana to try this out and see if there are any UX improvements needed

**Comment by dianasaur323** [comment]
I'm doing this again, and it seems like the natural fit for this would be in the jobs table, or perhaps a long-running queries table when we have it. Actually, maybe long-running queries is where we should put it. perhaps no to do for now.

**Comment by dianasaur323** [comment]
hmmm dump is such a lovely tool, but I really think we can do better here. I just tried to dump a huge file so that we could see what the logical size of it was. However, it crashed halfway through, and now I have no way of knowing if it actually finished. It would be great to do some kind of status checking if at all possible. Perhaps next release...

**Comment by mjibson** [comment]
Which side crashed? dump or the server? What's the error message? It is very reasonable to make dump resilient to server crashes by waiting and retrying. Also possible to have it display a kind-of-progress meter.

**Comment by dianasaur323** [comment]
So I had it running on a detached screen terminal, and on returning to check if it was done, I got the following error:

Error: driver: bad connection
Failed running "sql"

I'm assuming that means that the cluster crashed? Looking back at the admin UI, it does look like the node I was connected to running dump did crash about an hour after I ran dump (if I'm doing my UTC math correctly).

**Comment by mjibson** [comment]
dump should be able to recover from a node dying, as long as it comes back up or there's a load balancer in front of it. We can put that on the list.

**Comment by dianasaur323** [comment]
Ok, 2.1 here we come :)
