### ISSUE TITLE
backup/restore: incremental table backup takes longer than full table backup

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#18599]
I'm running an incremental backup on just tpch.nation, and see something strange:

From a full backup: 

![image](https://user-images.githubusercontent.com/5768024/30606134-aef4e714-9d3e-11e7-8044-4dadce723c13.png)

From an incremental one:
![image](https://user-images.githubusercontent.com/5768024/30606139-b4869ace-9d3e-11e7-84cc-60e8dabac5bb.png)

**Comment by mwang1026** [comment]
Close. TBI enabled and also no clear repro
