### ISSUE TITLE
backup/restore: bump import csv to beta status with cluster setting

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#18608]
Based on our discussion, we are moving import csv to beta so that users have a experience that matches their expectations. We will work on adding usability polish to import csv in 1.2

@jseldess this needs to be documented. Also, we need to mention that import csv will be free while in beta period. also cc @sploiselle 

@cuongdo @danhhz for triage.

**Comment by mjibson** [comment]
What's the rationale for a cluster setting to turn this on? It already has a fairly high bar to use and no one is going to successfully accidentally run it. Can we just say it's beta in the docs and not gate it behind anything?

I was under the impression that CSV import will be free forever.

**Comment by dianasaur323** [comment]
So the rationale of putting it behind a cluster setting was that we still have some usability polish to work on (correct me if you disagree here), and that by putting it behind a "beta" flag, we would be signaling that users should expect to hit some usability speed bumps. This feature will always be free, although we had discussed the possibility of gating it at some point, as some other open source tools do with smaller features like import csv.

**Comment by dianasaur323** [comment]
Ok, I'm back - I ran this by @nstewart to get his thoughts, and since we are going to be flagging all beta features this way, it makes sense to use the same treatment for everything. I think we have a meeting later today though, so we can chat about it then as well.

**Comment by jseldess** [comment]
@dianasaur323, @nstewart, please let me know if there are other "beta" features in 1.1 that we should document as such.

**Comment by sploiselle** [comment]
@dianasaur323 @nstewart Who has information about enabling beta features in cluster settings?

**Comment by dianasaur323** [comment]
Nope, just import CSV for now, although there are a couple that I think will be on the docket for 1.3

**Comment by mjibson** [comment]
@dianasaur323 you also mentioned possibly gating it at some point (that is, not the beta cluster setting). Do you know what that would look like? What is the purpose of that?

**Comment by dianasaur323** [comment]
@mjibson Ok, I thought about this, and although it is rushed, I think it's best for us to bite the bullet so that we create a consistent process going forward. The other rationale we talked about around marketing / brand quality is also important (people often miss things in docs). I looked at the outstanding issue to run SHOW EXPERIMENTAL FEATURES and it doesn't change the naming scheme of cluster settings. We could do something like sql.bulk.importcsv or just sql.importcsv. That being said, let me know if this takes you more than an hour or has some hidden complexity. 

Regarding gating this, we had discussed potentially asking users for an email. Other open source companies do it as well for small but helpful features, and we could use that info to get more feedback about people's experience and get a better understanding for who is using us.

**Comment by dianasaur323** [comment]
Also, I realized that we had this entire conversation in the prod / eng meeting, and I subsequently forgot to tell you about these changes in person. I'll make sure to do so next time so that I don't blindside you.

**Comment by mjibson** [comment]
If we want this to be an experimental feature, then those should all have the same prefix. Like `experimental.importcsv`.

I would ask you to reconsider the email gating. If it were me, I'd just fat finger a bogus email address to get around it, and be really annoyed at the company for even doing that at all. If they sent some turn-it-on magic link TO that email address I'd just not use their product. I dislike these kinds of things so much that I'd refuse to implement it in cockroach.

**Comment by nstewart** [comment]
Email gating is outside the scope of what we need to do here. We will collect emails when we roll out self service enterprise license keys, but we don't have plans to collect them to turn on experimental features (that's a much bigger conversation for the reasons you highlighted)

The goal for this ticket is to create a simple cluster setting that can be toggled like anything else. Next step is simply to agree on the flag name.

**Comment by dianasaur323** [comment]
Yep, don't worry about email gating. It isn't something we've decided on yet, and we would have a larger conversation about it at that point. experimental.importcsv sounds fine to me.
