### ISSUE TITLE
sql: Add GRANT|REVOKE statements

### ISSUE THREAD

**Issue by MBerhault** [cockroachdb/cockroach#1860]
This is the most user-friendly way to set privileges, and is needed for #1830 

Listing privileges is more annoying. postgres uses \du, mysql uses "show grant". Most allow a table lookup on the privileges table.

Until we figure out where permissions go, we should do a special command (maybe similar do psql's \du).

**Comment by petermattis** [comment]
Would be good to figure out what permissions we wish to support. Postgres (and I believe MySQL) support more than just read/write. See http://www.postgresql.org/docs/9.4/static/sql-grant.html.

**Comment by tamird** [comment]
Postgres even supports row-level security in 9.5

**Comment by MBerhault** [comment]
oh yeah, there are a lot of various privileges, and even crazier levels they apply to. For the very first pass, I want to keep it simple: database-level read/write.
Eventually, we will most likely want some subset of the permissions (create, select, insert, update, delete). This is the kind of thing that isn't too complicated to add once the framework is in place.
