### ISSUE TITLE
I can't drop the database

### ISSUE THREAD

**Issue by springrain** [cockroachdb/cockroach#18616]
Server version: CockroachDB CCL v1.1-beta.20170907 (linux amd64, built 2017/09/07 20:43:25, go1.8.3) (same version as client)

root@10.0.9.33:26257/> CREATE DATABASE springrain;
pq: database "springrain" already exists
root@10.0.9.33:26257/> DROP DATABASE springrain;
pq: database "springrain" is not empty and CASCADE was not specified

I can't drop the database,Thank you very much for your help.

**Comment by a-robinson** [comment]
As the error message indicates, the database isn't empty. If you're sure that you want to delete everything contained within the database, run `DROP DATABASE springrain CASCADE`.

https://www.cockroachlabs.com/docs/dev/drop-database.html#drop-a-database-and-dependent-objects

**Comment by springrain** [comment]
Thank you very much.
This is the beta version of the feature, I have been looking at the stable document, sorry.

**Comment by a-robinson** [comment]
Nothing to apologize for! The unreleased version's documentation isn't particularly easy to find unless you know it's there.

**Comment by croatiangrn** [comment]
`DROP DATABASE eem CASCADE;`

And it gives me this error:

invalid syntax: statement ignored: syntax error at or near "cascade"
DROP DATABASE eem CASCADE;
                                       ^

**Comment by a-robinson** [comment]
@croatiangrn what version of CockroachDB are you using? You can tell by running `./cockroach version` on the command line. The `CASCADE` modifier when dropping a database was added in version 1.1. If you're using version 1.0, `DROP DATABASE eem` will use the `CASCADE` behavior by default.

**Comment by croatiangrn** [comment]
I'm using v 1.1.1

**Comment by a-robinson** [comment]
Sorry for not also asking this in the first place, but could you also run `SELECT version();` from the SQL shell? That will tell you the version of the server, whereas I'm assuming you ran `./cockroach version` on the binary that you were using as the client.

**Comment by croatiangrn** [comment]
+--------------------------------------------------------------------------+
|                                version()                                 |
+--------------------------------------------------------------------------+
| CockroachDB CCL v1.1.1 (linux amd64, built 2017/10/19 15:31:46, go1.8.3) |
+--------------------------------------------------------------------------+
(1 row)

**Comment by knz** [comment]
@croatiangrn I believe the error you are finding is due to the use of a CockroachDB 1.0 client with a 1.1 server. Can you check whether the client is also 1.1?

**Comment by knz** [comment]
We have addressed the issue of mismatched client/server versions in both 1.1 and 2.0. Closing this.
