### ISSUE TITLE
ui: allow user defined events to show up in the admin UI

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#18614]
@bdarnell 

I'm logging this in since I think it's an awesome idea, but we won't have time to get it into 1.2. I think optimistically, this could go into 1.3 or the release right after that when we do some more administrative features.

Notes from our convo:
It would be good to be able to have users annotate their own external events
For example, when you roll out a new application, mark that event on a graph
This would be user-defined, so some sort of command would allow them to add an event with a description and timestamp

**Comment by piyush-singh** [comment]
One of our community members noted a request for this today and mentioned that they like the existing solution datadog employs:

https://raw.githubusercontent.com/DataDog/integrations-extras/master/gremlin/images/events-overlay.png
