### ISSUE TITLE
ui: Render graphs with D3 directly, replacing use of NVD3

### ISSUE THREAD

**Issue by mrtracy** [cockroachdb/cockroach#18620]
We have used the NVD3 library to draw our metrics graphs since the creation of the Admin UI.  However, we are rapidly outgrowing the restraints of this system:

 + We have numerous graph-related bugs that are proving difficult to analyze. As the graphing logic is largely contained in this third party library (which is not exceptionally well documented), we do not have a sufficient intuition of how to analyze or fix these bugs.
+ We have a desire to add more advanced features to graphs (#13378, #13752) which require features that do not intuitively fit into the NVD3 framework.

NVD3 is a library meant to provide a reasonable level of graph utility for a wide array of use cases; we now need a more advanced level of graph utility for a narrower use case.  Therefore, we should begin rendering our graphs using D3 directly; this will afford us greater control and understanding of the rendering process, allowing us to debug issues more effectively and add advanced features more easily.

---

EDIT 2019: Related issues.

Features this will directly or indirectly enable:
- #5980 - "step chart"
- #10014 - "log y scale"
- #12899 - "second axis"
- #13378 - "events on graphs"
- #13389 - "histogram on hover"
- #13752 - "zoom on time scale"
- #16855 - "show configured cache size"
- #20021 - "ghost time series"
- #27934 - "boxplot for distribution"

Bugs this will likely obselete (let's not repeat them, though):
- #12973
- #16505 
- #17552
- #18452
- #19271
- #19490
- #21630
- #22572
- #23480
- #27094
- #27954
- #30286
- #30287
- #33717

**Comment by couchand** [comment]
I've broken down the major steps to replacing our use of NVD3 for the time series charts.  This is where I'll be tracking the progress as I work on this:

- general functionality
  - [X] basic static charting
  - [ ] multiple series
  - [ ] legends
  - [ ] update on new data
  - [ ] sliding animation
  - [ ] timeseries data integration
  - [ ] react integration
- scales
  - [ ] time scale
  - [ ] count scale
  - [ ] byte scale
  - [ ] duration scale
  - [ ] percentage scale
- interactivity
  - [ ] hover tooltip
  - [ ] linked guidelines
