### ISSUE TITLE
ui: Enable TSX rules in TS-Lint

### ISSUE THREAD

**Issue by mrtracy** [cockroachdb/cockroach#18625]
TSLint has a number of TSX related rules that are available through [this package](https://github.com/palantir/tslint-react).  We are already manually attempting to enforce a number of these (based on recommendations from the [AirBnB JSX style guide](https://github.com/airbnb/javascript/tree/master/react)), but we should enable these in a linter to ensure they are effectively captured and consistently enforced.

The rules I am most interested in that could be enabled immediately:
+ jsx-alignment
+ jsx-self-close
+ jsx-wrap-multiline
+ jsx-key (would save debugging time)

Many of the other rules are a bit more nit-picky, but we can consider them individually. In the case of the lambda-expression rules, I think we should leave them off for now and consider turning them on in the future; I don't think we're yet ready to trade ease of development for performance improvements at that level.

**Comment by jordanlewis** [comment]
Closing due to age
