### ISSUE TITLE
ui: show backup / restore size in jobs table

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#18622]
This is open for discussion, but I've been running a bunch of backup / restores and incremental backups. It would be nice to see the sizes of each so that I can figure out how the amount of time each one of these takes is correlated with the size of the backup.

@benesch would love your opinion here (you probably won't be the one to implement this, just want your thoughts!)

**Comment by vilterp** [comment]
This would be good. Closest thing I see is `BackupDescriptor > EntryCounts > DataSize`. Would be nice to expose this on some virtual / system table; not sure how. Thoughts, @mjibson?

**Comment by mjibson** [comment]
This sounds nice, but will take some work to ensure we are providing correct information.

**Comment by dianasaur323** [comment]
Perhaps we hold off on this until we do more admin like or scheduling stuff in the future. I think this is a nice to have for now
