### ISSUE TITLE
import: ignore errors on import of foreign key tables

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#18638]
Our current import of tables after a dump results in tables that are sorted in alphabetical instead of an order that supports semantic constraints. Allow a function where you can tell the database to ignore such constraints and move ahead with import.

This is a customer request.

**Comment by brucemcpherson** [comment]
I had this issue with a conversion from a mySQL database, The solution  I used was to extract all the foreign key definitions, and apply alter statements after all the data was inserted - in other words 3 stages - create tables/insert values/alter tables. However this means that cockroach cant restore its own dumps.

**Comment by dianasaur323** [comment]
@mjibson this seems like an annoying usability nit. How long do you think it would take to fix it? I'm assuming this does not qualify as a project big enough to put onto the roadmap explicitly?

**Comment by mjibson** [comment]
RESTORE has an option that allows this. IMPORT should be able to get the same. If that's the case then you're correct, this is small and doesn't need to be on the roadmap.
