### ISSUE TITLE
backup/restore: UX suggestions to improve dump (and potentially restore)

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#18637]
From customer requests:
1) Allow exclusion of tables - say your database has hundreds of tables. How can you export the majority of them, while excluding just a handful without typing out all the table names?
2) Export just the indexes of a dump file (I'm not as clear on this request, so perhaps others have more context)
3) Export only certain data in a table - enable some filtering so that only certain rows are exported

**Comment by bdarnell** [comment]
I think the second item is because it's faster to load your data without secondary indexes, then add the indexes later. It would be ideal to dump the table(s) in three files/phases: the CREATE TABLE statement (without any indexes), the data, then the CREATE INDEX statements.

**Comment by dianasaur323** [comment]
Based on @mjibson, you really shouldn't be doing 2, since we perform better without that. 3 should be output format csv.

**Comment by mjibson** [comment]
Solved by other things.
