### ISSUE TITLE
sqlccl: LOAD CSV needs progress

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#18630]
When performing a large `LOAD CSV` operation, there's no indication of progress. That's a significant irritant when loading large amounts of data, such as `LOAD CSV` with TPC-H scale factor 100 data. Ideally, we'd report similar information that we do for other long-running jobs.

**Comment by dt** [comment]
for the record, our current job progress is updated after the sampling to 1/3 done, then to 1 when we finish the SSTs.

**Comment by dianasaur323** [comment]
also related to this larger meta issue: https://github.com/cockroachdb/cockroach/issues/17946, although that refers to more than just load csv.
