### ISSUE TITLE
docs: integrate docs generation tools into development workflow

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#18644]
Need to move the docs generation tools, as well as the content they generate, into the repo. The docs repo can copy these files from a cockroach checkout prior to building the docs site (or include them directly from ../cockroach/... if it wants I guess).

We'll also want to re-run that generation in CI to ensure it is up-to-date and that any changes were included in the correct changeset.

This should mean that a change to sql.y or a builtin will also include re-generating the derived docs content, though actually integrating that regenerated content into the docs site is out of scope for now.

**Comment by dt** [comment]
open question: should we move the generated docs files in here too, and then just reference or copy them into the docs repo when building there?

advantage of this is that a change adding a new builtin or grammar would could include the addition of the generated doc for it, making it easier to review that related fields are well-formed (i.e. the categorization or docstring fields on a builtin are only really used by the doc generator).

the downside is that this splits the docs content across repos.

This could also be an argument for moving all the docs content into the repo that it documents... something something versioning /cc @benesch

**Comment by jseldess** [comment]
By generated doc files, you mean all the relevant diagram and function files in `_includes`? I'd be open to that, though I don't really understand what the process would be. I'd also be open to further discussion of the idea to merge these repos, though, again, I don't really understand what this means in terms of our process. Should I set up a meeting to start talking about this, or to get your help to understand the impacts here?

**Comment by dt** [comment]
let's wait for @benesch to get back next week to chat more about to what degree moving / merging the docs content makes sense -- for now I'll proceed with just moving the code which we want to do either way.

**Comment by benesch** [comment]
Thanks @dt! I think we should hold off on including the generated diagrams in cockroachdb/cockroach and instead shoot to merge the two repos entirely. 

@jseldess, if you're up for starting the conversation about repo-merging, I think a quick meeting next week would be helpful! People who are interested from the eng side include @knz, @andreimatei, me, and presumably @bdarnell.

**Comment by jseldess** [comment]
OK, thanks, @benesch, I'll set up a meeting.

**Comment by dt** [comment]
We'll move forward with moving the generators in to the repo as well as their generated files which will then, for now, just be periodically copied into the docs repo before it is built.

**Comment by mjibson** [comment]
Closing because we fixed the major problem here.
