### ISSUE TITLE
sql: track and include in diagnostics reporting the number of parse errors

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#18641]
we can't include any data about unparsable queries themselves as we're unable be sure they're sanitized without parsing them, but we could at least record number / % of statements that hit a parse error.

**Comment by dianasaur323** [comment]
@knz thanks! this falls under metrics reporting, and @awoods187 has some issues open. Assigning to him so that he can reorganize as he sees fit.

**Comment by awoods187** [comment]
Added to 2.1 tracking in Airtable

**Comment by knz** [comment]
@dt I think this was addressed right?

**Comment by dt** [comment]
yep
