### ISSUE TITLE
storage: investigate busy loop in split queue

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#18646]
Both #18199 and #15997 observed the split queue showing up in profiles/participating in obvious contention.

In #15997 we were writing a range chock full of illegal split keys. The split operation should back off more and more (owing to the doubling of the in-memory split target size), but this perhaps doesn't happen. Also, reading an engine snapshot in a tight loop appears to have interfered pretty severely with Raft handling in my testing, leading to up to 50s instances of `handleRaftReady`.

**Comment by petermattis** [comment]
We don't double the split target size if an error is returned from `EnsureSafeSplitKey`. Perhaps we should. 

Removing the engine snapshot from `MVCCFindSplitKey` is trivial. There is also some other low-hanging performance changes there which I'll send out a PR for. But it will be worthwhile to figure out what is causing the long `handleRaftReady`. If it is the engine snapshot, then I clearly don't understand something.
