### ISSUE TITLE
sqlccl: cannot transform sf-100 csv with distsql

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#18652]
Running a large IMPORT with distributed on a sf-100 dataset fails with:

```
pq: query execution canceled: [n1] communication error: rpc error: code = Canceled desc = context canceled
```

It took almost 9 hours to fail like this. I see nothing in the logs near the failure time besides normal stuff.

**Comment by mjibson** [comment]
See #15332

**Comment by cuongdo** [comment]
As discussed today, the next step here is to wrap `Context.WithCancel()` to inject more debugging info (such as a stack trace) to determine what the real issue here is.

**Comment by mjibson** [comment]
This works now.
