### ISSUE TITLE
ui: add Schema Change column to Database Tables page

### ISSUE THREAD

**Issue by couchand** [cockroachdb/cockroach#18658]
Broken out of the conversation from #18631:

>  vivekmenezes commented 18 hours ago
> 
> I think it will be valuable for users to see if there are an existing schema changes scheduled for the job with a link to the jobs page perhaps? But I'm also happy for you to merge this and create another issue that creates a plan to do that correctly like provide a link to a filtered jobs table reflecting only jobs for schema changes associated with the table.
> 
> vivekmenezes commented 18 hours ago
> 
> perhaps this column can have a check mark or something indicating that a schema change exists

**Comment by dianasaur323** [comment]
Since we already have the jobs table, and we also have a lot of issues to go through, I'm going to bump this to 1.3, and we can bring it back in if we want.

**Comment by piyush-singh** [comment]
Given the small amount of time left for 2.1, bumping this to Later. We can bring this back into scope when we have time.
