### ISSUE TITLE
conncet err by navicat premium

### ISSUE THREAD

**Issue by skyformat99** [cockroachdb/cockroach#18653]
1）install cockroachdb on linux
2)  use cockroach sql  command for test it,  all ok
3)  then use navicat premium to conncet db,   error:
     "ERROR:  table  pg_tablespace does not exist."
I don't know what's wrong.    The following is the database:

/> show databases;
+--------------------+
|      Database      |
+--------------------+
| bank               |
| crdb_internal      |
| information_schema |
| pg_catalog         |
| system             |
+--------------------+
(5 rows)

**Comment by a-robinson** [comment]
Hi @skyformat99! Unfortunately, we don't yet emulate all the internal tables (such as `pg_catalog.pg_tablespace`) that navicat relies on. See https://github.com/cockroachdb/cockroach/issues/5583 for more details, which is the tracking issue for supporting navicat.
