### ISSUE TITLE
ui: Consider upgrade from D3 v3 to v4 (or v5!)

### ISSUE THREAD

**Issue by mrtracy** [cockroachdb/cockroach#18665]
The Admin UI currently uses D3 version 3.  Version 4 of D3 is a non-trivial upgrade, but claims a number of benefits:

+ Modularity (import only the features needed)
+ More consistent parameters to callback functions
+ More in-depth typescript support

Our usage of v3 is not currently crippling, but it might be better to upgrade sooner rather than later.

**Comment by vilterp** [comment]
Welp, now there's v5: https://github.com/d3/d3/releases/tag/v5.0.0
