### ISSUE TITLE
ui: Replace moment.js with immutable alternative

### ISSUE THREAD

**Issue by mrtracy** [cockroachdb/cockroach#18662]
moment.js is the library we are currently using to work with timestamps in the Admin UI. However, this library's lack of immutability is clunky when used alongside the rest of our frameworks. Moment.js is also not particularly performant.

We should replace our usage of moment.js with an alternative, immutable library.  My current front-runner is [date-fns](https://github.com/date-fns/date-fns), but there are likely other alternatives to consider.

**Comment by jtescher** [comment]
Have you also considered https://github.com/moment/luxon ?
