### ISSUE TITLE
backup/restore: RESTORE ... AS OF SYSTEM TIME (acceptance criteria)

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#18679]
Tracking issue for https://github.com/cockroachdb/cockroach/pull/18547 when it gets pushed, here is a list of manual tests I'll run.

- [ ] Run BACKUP with 'mvcc_all' enabled using tpch scale factor 1
   - [ ] How much storage should I provision for BACKUP with 'mvcc_all'?
- [ ] Run some queries (eventually add / drop tables when we get that fixed)
- [ ] Run an incremental backup with 'mvcc_all' enabled
- [ ] Run some queries (eventually add / drop tables when we get that fixed)
- [ ] Run an incremental backup with 'mvcc_all' disabled
- [ ] Restore as of system time to the first full, then the second incremental, then the third incremental
- [ ] Normal restore to first full, then the second incremental, then the third incremental

**Usability considerations**
- [ ] How much storage should I provision for BACKUP with 'mvcc_all'?
- [ ] What happens if I don't have enough storage?
- [ ] What do our error messages look like? What happens if I run 'AS OF SYSTEM TIME' on a backup that doesn't support that functionality?
- [ ] What happens if I have a cluster running on two different versions? What will the error message be?
- [ ] How will I determine what system time to use?

**Sanity Check**
- [ ] Does this meet the use case of: I discovered an error that occurred at a point in time between two backups, and need to recover to that point.

**Comment by arjunravinarayan** [comment]
Ping @dianasaur323, can this issue be closed, or moved off the 2.0 milestone?

**Comment by dianasaur323** [comment]
Thanks! I haven't run these yet - will do so tomorrow

**Comment by dianasaur323** [comment]
Actually, nvm I've done this. Closing!
