### ISSUE TITLE
ui: Investigate Switch from Lodash to Ramda

### ISSUE THREAD

**Issue by mrtracy** [cockroachdb/cockroach#18670]
The Admin UI currently uses Lodash as a functional utility library.  [Ramda](http://ramdajs.com/) is an alternative.

Lodash does not seem to be causing any major problems with our code; however, the appeal of Ramda is its consistent functional philosophy; its API greatly resembles a pure functional language, with currying and composition as core concepts.  I see this as a slight quality-of-life improvement for our developers.

A switch to this library may be more effective if done sooner rather than later.

**Comment by mrtracy** [comment]
As part of this, we should stop using lodash for simple loops over arrays; we should use `Array.map`, `array.forEach`, or `for..of` loops instead.  Previously, I had believed using lodash methods was providing additional compatibility or consistency, but I no longer believe this to be the case; my original instinct was not founded on any specifics.

**Comment by bdarnell** [comment]
After 2 years with no action I think it's safe to say this won't happen.
