### ISSUE TITLE
backup/restore: 1.0 backup throws an error

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#18695]
I am trying to run a backup on our registration cluster, and I can not, for the life of me, figure out what is going on. 

```BACKUP DATABASE registration TO 'path';```

Get this error:

```pq: exporting 264 ranges: error response from server: 501 Not Implemented "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>NotImplemented</Code><Message>A header you provided implies functionality that is not implemented</Message><Header>Transfer-Encoding</Header><RequestId>___</RequestId><HostId>___</HostId></Error>"```

I've already checked the enterprise setting.

@dt do you mind taking a quick look to help me sanity check this? We need it soon since it's part of a project that @awoods187 is working on as a starter project.

**Comment by dt** [comment]
@dianasaur323 what's the scheme of `path`?

**Comment by dianasaur323** [comment]
@dt https://s3.amazonaws.com/crdbcsvtest/registration/

**Comment by dt** [comment]
for s3, I think you want `s3://...`, not `https://`, and you might need credentials too. https://www.cockroachlabs.com/docs/stable/backup.html#backup-file-urls

**Comment by dianasaur323** [comment]
ah, why does it work for the new backup restore, and not for the old one?

**Comment by dt** [comment]
er, I don't think we support using `https://` for S3 in any version?

**Comment by dianasaur323** [comment]
that's how I've been running all my backups / restores though. and they've worked in 1.1

**Comment by dt** [comment]
huh, i guess in some setups an S3 bucket's http API might support GET and PUT, enough to work, but apparently we're using some HTTP parameters it doesn't like. The supported `s3://` uri should work though.

**Comment by dt** [comment]
(verified offline that an s3:// uri works).
