### ISSUE TITLE
hang at gc_queue when lots of goroutine started in processKeysAndValues function

### ISSUE THREAD

**Issue by YuleiXiao** [cockroachdb/cockroach#1869]
Operation Steps:
1. Insert a lot of data, more than ten million
2. Drop whole data inserted via drop range
3. Restart cockraoch

After started, Cockroach's CPU is very high and memory is more than 7GB for a long time.

I add some log to debug. From logs, we can see Cockroach will do GC in gc_queue after start. But if there are many range to GC, it will start lots of goroutine in processKeysAndValues function. In my logs it is about more than 30000. After that goroutine hang, it can not add cmd, also can not process in processRaftCommand. They all not work.

I try to add sleep 100ms in processKeysAndValues to limit the starting speed. It works fine.

So I think maybe there is some problem in goroutine schedule. 
And we should do some flow control in gc_queue for start many goroutine at the same time.

**Comment by spencerkimball** [comment]
Did you do this using a transaction? The GC code will start up a goroutine for each unresolved intent, which is probably a mistake if there are a large number of them.

I can reorganize the code to limit the number of outstanding intent resolves.

**Comment by YuleiXiao** [comment]
@spencerkimball yes, it is a transaction.

**Comment by spencerkimball** [comment]
Oh, sorry, didn't see you were interested in fixing. I have a PR outstanding to fix. There's more to the fix, which is going to involve supporting batches through Raft that should make this incredibly efficient.
