### ISSUE TITLE
distsql/kv: queries processed by distsql can propagate incorrect GatewayNodeID

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#18700]
The [`DistSender` attaches a `GatewayNodeID` field to all batches that it sends](https://github.com/cockroachdb/cockroach/blob/9f0bb3691c10beb74911b22baa7839c21bf85dac/pkg/kv/dist_sender.go#L471) as a way of representing which node served as the gateway for the request. This enables us to [rebalance leaseholders towards where requests are coming from to reduce latency](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20170125_leaseholder_locality.md).

However, this method of attaching a `GatewayNodeID` with the local node's ID doesn't work so well when a `DistSQL` processor on a node that isn't the true gateway is the one sending the batch request through the `DistSender`.

@jseldess ran into this when running tpcc on a cluster distributed across the US, and it made leases not get moved as well as they should have because as many as half of the requests to some ranges were getting counted as coming from the node that their leaseholder was on rather than the node that was actually receiving all the SQL connections.

Tracing `Send(` calls up the stack is pretty frustrating due to how widely used and overloaded it is, so I'll start by asking. @andreimatei, do distsql nodes know the node ID of the SQL coordinator and how far separated is that knowledge from where distsql is constructing its `BatchRequest`s?

**Comment by andreimatei** [comment]
As it just so happens, as of recently, `DistSQL` *processors* (not "nodes") do know the `NodeID` of  the *gateway* node ("gateway" is the word we generally use at the SQL level; "coordinator" is used more at the KV level in relation with transaction heartbeats and is a concept perhaps we'll be able to eliminate).
I think it'd be easy enough to have all the processors that send `BatchRequests` fill in the right value. I can do that.

I worry, though, that it'll be too easy to forget to do this for some processors, now and in the future. Do you think it's infeasible to have `DistSender` freak out if someone forgot to fill in the value (and thus to require everyone to fill it in)?

**Comment by andreimatei** [comment]
Btw, I think this problem with DistSQL appearing to only make local requests to KV was flagged when the lease balancing RFC was going around, but I guess we all dropped the ball on doing anything about it :P

**Comment by a-robinson** [comment]
> I think it'd be easy enough to have all the processors that send BatchRequests fill in the right value. I can do that.

Thanks!

> I worry, though, that it'll be too easy to forget to do this for some processors, now and in the future. Do you think it's infeasible to have DistSender freak out if someone forgot to fill in the value (and thus to require everyone to fill it in)?

It'll require a workaround for tests, but I think it would be feasible. I can take on that task after you do your best to fill in the real code paths.

> Btw, I think this problem with DistSQL appearing to only make local requests to KV was flagged when the lease balancing RFC was going around, but I guess we all dropped the ball on doing anything about it :P

Yup, I definitely dropped the ball on that.

**Comment by andreimatei** [comment]
> Yup, I definitely dropped the ball on that.

I think it's more me than you :)
