### ISSUE TITLE
about cockroach multi-raft 

### ISSUE THREAD

**Issue by Frank-Jin** [cockroachdb/cockroach#1872]
@spencerkimball @tschottdorf 
We have tried to migrate an application on top of cockroach, but when configing ranges to three-replica, we find multi-raft is not mature, include performance and stability(for example split range lead to panic).
I think multi-raft is the foundation of cockroach, Are there any plan that consolidate the range replica and range admin(split/merge/add).

look forward to your reply.

**Comment by spencerkimball** [comment]
@bdarnell is currently working to address some overlapping set of the problems you're experiencing. See his recent spate of RFCs: #1864 #1865 #1866 #1867.

**Comment by tschottdorf** [comment]
this is on our radar and currently being worked on in multiple issues, so closing this specific one. If you have specifics to add @Frank-Jin, we'd love to hear them.
