### ISSUE TITLE
client: Support C# as first class

### ISSUE THREAD

**Issue by lwansbrough** [cockroachdb/cockroach#18729]
We're big fans of CockroachDB. We think it will be the right choice for us once it's a little more mature, but we're a bit concerned with where the priorities lie for the CockroachDB team. If you don't mind, I'd like to give my two cents:

CockroachDB's product is a database. It's a database which presents itself as a solution for companies with truly massive data requirements. Given that, you'd expect CockroachDB to be fully focused on supporting the languages used by their potential customers the most. I may be wrong, but I would suspect C# users would be near the top of that list: they're enterprise users with lots of money, and they have _big_ data requirements that often require novel solutions. Not only that, but C# is moving more and more into the open and is gaining ground quickly, with growing interest in (ASP) .NET Core.

I don't think we're alone when we say that CockroachDB would be a very interesting solution for us, and we'd consider it heavily, **but there's not a single mention of C# anywhere on the CockroachDB site! [0]** With work being done to ensure there's support for absolutely (sorry) insignificant languages like Rust and Closure, it's absolutely baffling to me that there isn't more focus being put on **the number 4 most used language in the world [1].**

I hope the CockroachDB team can work to re-evaluate their business strategy a bit (I say that without negative judgement) to ensure they're capitalizing on markets where their product can be utilized most effectively! We really want to be able to use this product, but we don't think it makes much sense for us to be forced to forge ahead without some official support.

[0] https://www.cockroachlabs.com/docs/stable/install-client-drivers.html
[1] https://www.tiobe.com/tiobe-index

**Comment by dianasaur323** [comment]
Hello again, @lwansbrough! Thanks for the feedback - @BramGruneir recently tried npgsql, and it worked for him, although we don't claim to officially support it. Regardless, we should do a better job. I'll put it on our list to discuss this week, along with better GUI compatibility.

**Comment by lwansbrough** [comment]
Thanks Diana, truly appreciate the responsiveness!

**Comment by dianasaur323** [comment]
Ok, @awoods187 will take this issue over to see what we can deliver in the 1.2 timeframe.

**Comment by BramGruneir** [comment]
@lwansbrough You're absolutely right about how our lack of C# is quite concerning. 
I was working on it during my free time, but no longer.  We're upgrading it so I can dedicate some time to get it officially supported.  

As @dianasaur323 mentioned, I've been testing out npgsql and it's been great.  Not the server explorer, but the straight driver.

To get started, here's a sample of how I was able to get npgsql working against the windows binary.
Please give it a try (use the latest 1.1 beta) and let me know if you run into any errors.
```
class Program
    {
        const string connString = "Host=Hal9000;Port=26257;Database=bank;Username=maxroach;";

        static void Main(string[] args)
        {
            Simple();
        }

        static void Simple()
        {
            using (var conn = new NpgsqlConnection(connString))
            {
                // Connect to the "bank" database.
                conn.Open();

                // Create the "accounts" table.
                new NpgsqlCommand("CREATE TABLE IF NOT EXISTS accounts (id INT PRIMARY KEY, balance INT)", conn).ExecuteNonQuery();

                // Insert two rows into the "accounts" table.
                using (var cmd = new NpgsqlCommand())
                {
                    cmd.Connection = conn;
                    cmd.CommandText = "INSERT INTO accounts(id, balance) VALUES(@id1, @val1), (@id2, @val2)";
                    cmd.Parameters.AddWithValue("id1", 1);
                    cmd.Parameters.AddWithValue("val1", 1000);
                    cmd.Parameters.AddWithValue("id2", 2);
                    cmd.Parameters.AddWithValue("val2", 250);
                    cmd.ExecuteNonQuery();
                }

                // Print out the balances.
                System.Console.WriteLine("Initial balances:");
                using (var cmd = new NpgsqlCommand("SELECT id, balance FROM accounts", conn))
                using (var reader = cmd.ExecuteReader())
                    while (reader.Read())
                        Console.Write("\taccount {0}: {1}\n", reader.GetString(0), reader.GetString(1));
                Console.ReadKey();
            }
        }
    }
```

**Comment by BramGruneir** [comment]
I think everything is done here.  If there are any issues with C# please reopen or open a new issue.
