### ISSUE TITLE
ui: reduce impact of embedded.go bottleneck

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#18735]
I'm personally a bit confused about the scope of this issue, but since the Airtable record was becoming a discussion about implementation anyway, I wanted to open this up, assign @BramGruneir and @benesch to it, and move the discussion here.

Since we are actively going to start making some bigger changes to the admin UI starting in around a month, I'm assuming it would be nice to have this in by then.

cc @cuongdo

**Comment by BramGruneir** [comment]
This issue is already being addressed and will be closed as soon as #18349 lands.
