### ISSUE TITLE
perf: reduce space overhead for unreplicated and non-versioned keys

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#18731]
Forked from [a comment](https://github.com/cockroachdb/cockroach/issues/18659#issuecomment-331269820) in #18659:

Non-versioned keys have their values stored at the "metadata" key (i.e. the key with the zero timestamp). Currently, the value is always stored in the `MVCCMetadata.raw_bytes` field and the other fields of `MVCCMetadata` are left zero. Due to the use of proto2 and non-nullable fields, the encoded size of a zero-value `MVCCMetadata` is 12 bytes. Due to the consistency checker, it is difficult to do anything about this 12 byte overhead for replicated keys and it isn't clear if they are any of concern. 

There are several unreplicated keys for which this 12 bytes of overhead is significant:

```
/Local/RangeID/X/u/RaftLog/logIndex:Y
/Local/RangeID/X/u/RaftLastIndex
/Local/RangeID/X/u/RaftHardState
/Local/RangeID/X/r/RaftAppliedIndex
/Local/RangeID/X/r/LeaseAppliedIndex
```

Note that #18717 is going to remove `RaftLastIndex` and #13392 discusses getting rid of `RaftAppliedIndex` and `LeaseAppliedIndex`.

The total size of the `RaftHardState` key/value pair is ~40 bytes. The total size of a Raft log key/value (minus the value) is ~30 bytes. Reducing these sizes by 12 bytes is both significant and relatively painless: we can create a parallel `MVCCMetadata` proto that makes every field nullable. This reduces the encoded size of the zero value to 0 bytes and is also backwards compatible so downgrading to a previous version is not a problem (unlike the version dance that will be necessary for removing `RaftLastIndex`, `RaftAppliedIndex` and `LeaseAppliedIndex`).

**Comment by nvanbenschoten** [comment]
Moving to 2.1, as this will not be addressed in 2.0.
