### ISSUE TITLE
sql: transaction / session cancellation

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#18736]
**Rationale**
This is follow-up work related to query cancellation. We currently do not allow cancellation of transactions or sessions. These are both important features that other SQL databases offer, so we should offer these features to improve manageability and parity.

**PM Acceptance Testing**
- [ ] Run a transaction
- [ ] Observe what things look like in Show Queries and Show Sessions
- [ ] Cancel transaction
- [ ] Run multiple queries from a single session
- [ ] Cancel session

**Comment by vivekmenezes** [comment]
https://github.com/cockroachdb/cockroach/pull/17252

**Comment by dianasaur323** [comment]
thanks @vivekmenezes!

**Comment by vivekmenezes** [comment]
sorry @dianasaur323 . not yet!

**Comment by dianasaur323** [comment]
=.='

**Comment by arjunravinarayan** [comment]
@awoods187 can you please take a look at this issue and close it if appropriate? We've made great strides in session/transaction cancellation, so this should be very straightforward.

**Comment by jordanlewis** [comment]
We still haven't implemented session or transaction cancellation, and it's not going to happen for 2.0.

**Comment by dianasaur323** [comment]
yep, time is allocated in 2.1. Thanks for moving the milestone.

**Comment by nstewart** [comment]
Can we get an update on what's left to do here now that https://github.com/cockroachdb/cockroach/pull/23861 merged? cc @vivekmenezes

**Comment by vivekmenezes** [comment]
assigning @andreimatei because he would like to make some improvement here. I'm not sure whether this works but it should definitely be QA-ed once andrei is happy with it.

**Comment by andreimatei** [comment]
I would actually close this since we now have session cancelation and also `set statement_timeout`. This issue also talks about "txn cancelation", but that's not defined here so I think this issue is not serving any purpose.
