### ISSUE TITLE
sql: index sizes do not match on registration cluster

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#18744]
Forked from #18705.

The size of the primary index on the `updates` table of the `registration` database does not match the size of the secondary index `updates_timestamp_idx` on `updates.timestamp`. This is reproducible both on the registration cluster itself and on a restored backup on a more recent branch.

```
root@localhost:26257/registration> SELECT count(*) FROM updates@primary;
+----------+
| count(*) |
+----------+
|  1436200 |
+----------+
(1 row)
root@localhost:26257/registration> SELECT count(*) FROM updates@updates_timestamp_idx;
+----------+
| count(*) |
+----------+
|  1436341 |
+----------+
(1 row)
```

As you can see, the secondary index has *more* entries than the primary index, suggesting perhaps that secondary index updates aren't getting rolled back synchronously with primary index updates.

**Comment by jordanlewis** [comment]
Assigning @vivekmenezes for general ownership. cc @dt who is also involved in this investigation.

**Comment by dt** [comment]
Running `SELECT timestamp FROM updates@primary WHERE (timestamp > '2017-08-13 05:00:00') AND (timestamp < '2017-08-13 06:00:00') order by timestamp;`, I've found a timestamp that is in the `timestamp` index but not in primary: `2017-08-13 05:18:49.992346+00:00`

**Comment by dt** [comment]
reg was running 1.0.2 at the time according to prometheus.

**Comment by dt** [comment]
so looking at row counts by day, I isolated days where we first started seeing the counts differ (pk on right):
```
|     6083 |  6083 | 2017-08-08 00:00:00+00:00 |
|     4991 |  4989 | 2017-08-09 00:00:00+00:00 |
|     4086 |  4072 | 2017-08-10 00:00:00+00:00 |
|     3587 |  3563 | 2017-08-11 00:00:00+00:00 |
|     2026 |  2022 | 2017-08-12 00:00:00+00:00 |
|     1764 |  1757 | 2017-08-13 00:00:00+00:00 |
|     3030 |  3001 | 2017-08-14 00:00:00+00:00 |
|     2077 |  2077 | 2017-08-15 00:00:00+00:00 |
|     5198 |  5198 | 2017-08-16 00:00:00+00:00 |
|     8868 |  8868 | 2017-08-17 00:00:00+00:00 |
```
It does look like the cluster was pretty sad around those days -- elevated CPU and latency, more transfers, a few snapshots. 

https://monitoring.crdb.io/dashboard/db/cockroach-leases?from=1501545600000&to=1502841600000&var-cluster=register&var-node=All&var-rate_interval=30s&orgId=1

https://monitoring.crdb.io/dashboard/db/cockroach-sql?from=1501545600000&to=1502841600000&var-cluster=register&var-node=All&var-rate_interval=30s&orgId=1

**Comment by vivekmenezes** [comment]
Are you able to use AS OF SYSTEM TIME to check if the timestamp is there in the primary index at that time? Did the row get deleted later?

**Comment by dt** [comment]
sadly I don't think we can time travel back that far.

**Comment by dt** [comment]
for anyone else digging into this: trying to dig into the one orphaned row I mentioned above, the request at that timestamp on 8/13 appears in reg 4's logs. reg 4's http proc error logs are all about being out of open files. the cockroach proc logs have been rotated and are gone.

**Comment by bdarnell** [comment]
Both 1.0.3 and 1.0.4 fixed bugs that could result in inconsistencies like this when requests race with lease transfers. (#16775 and #17141). I think there's a very good chance that it's one of those two. Unfortunately, neither of them left much trace so I don't think we'd be able to determine this for certain.

**Comment by dt** [comment]
@bdarnell thanks. think we can close this then? or should we keep it until we come up with a fix for the current data e.g. sql `fsck` util?

**Comment by bdarnell** [comment]
Since we can fix the inconsistencies here by dropping and recreating the index I think we should probably do that and then close this issue. (Can we create a new index on the same column(s) before dropping the existing one, or do we need to drop the index first and go index-less for a time?)

**Comment by dt** [comment]
we don't do anything to prevent creating identical indexes other than require the index names be unique, so unless queries are using explicit index name hints (which the app in this case doesn't), we should be fine with a create-then-drop sequence.

**Comment by jordanlewis** [comment]
Closing this, not much we can do about it now.
