### ISSUE TITLE
build: base docker image needs updating

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#18747]
When creating the build/deploy docker image from the 1.1 branch and then trying to run it, my container is printing the errors:

```
/cockroach/cockroach: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /cockroach/cockroach)
/cockroach/cockroach: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /cockroach/cockroach)
/cockroach/cockroach: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /cockroach/cockroach)
```

Seems like the base image needs updating.

**Comment by a-robinson** [comment]
There might be a little more going on here. I was able to put https://binaries.cockroachdb.com/cockroach-v1.1-beta.20170921.linux-amd64.tgz into an image based on debian:8.7 and run it just fine. When you built your release image, did you build it within a `build/builder.sh` container? I wonder if it ended up with the wrong dependencies somehow.

We'd benefit from using a more up-to-date base image anyways for security purposes, but I'm not sure if it's the cause for these errors.

**Comment by mjibson** [comment]
I built this from my own Debian installation, so that was likely the problem.
