### ISSUE TITLE
storage: move evaluation of BatchRequests to a separate package

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#18784]
Broken out from https://github.com/cockroachdb/cockroach/issues/18779.

**Comment by tschottdorf** [comment]
There's a bit of movement yet to do, but I don't think it makes sense to cherry-pick that into 2.0, so I'm moving the milestone.

**Comment by tschottdorf** [comment]
Not sure it's worth tracking this. There's a bit left to do (around EndTransaction) but this issue won't fix that. Someone running into it and getting annoyed will.

**Comment by nvanbenschoten** [comment]
@tschottdorf more to do beyond https://github.com/cockroachdb/cockroach/pull/26917?

**Comment by tschottdorf** [comment]
I think there's some stuff around the commit triggers that isn't really home in replica_command.go, see this comment from the PR you linked:

```
The one-phase commit logic still lives in storage and, unfortunately,
ends up tightly coupled with the EndTransaction machinery in batcheval,
but this is a step in the right direction. By contrast, the extraction
of writeInitial[Replica]State into the stateloader package goes quite
smoothly.
```
