### ISSUE TITLE
bulk: stabilize distributed bulk ingest

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#18819]
This is a parent issue for distributed bulk ingest work going into 1.2. The overall goal for the team is to put usability front and center, since this feature is so important to our users!

- [ ] Pause, cancel, and resume import CSV (+ survive node failures) https://github.com/cockroachdb/cockroach/issues/18139
- [ ] Allow import into an existing table @robert-s-lee 
- [ ] Automatically break up large CSVs transparently to users

**TBD after more research, but hope to keep this to a S / M**
- [ ] Polish error handling (PM to do some research on what other databases do right now)
   - [ ] Handle weird characters
   - [ ] Allow users to ignore errors and import anyway
   - [ ] Multiple tables (stretch), and perhaps interleaved tables

**Acceptance Testing**
- Stress test import CSV by TPC-H scale factor (aim to support TPC-H 100 after all our fixes have been made)
- Kill a node and observe that import CSV can survive node failures
- Pause, cancel, and resume import CSV
- Document performance of target TPC-H scale factor. Is it unreasonable for this to be the same as large clusters in production testing?

cc @dt @mjibson @danhhz @benesch @cuongdo  for comments

**Comment by robertslee** [comment]
If time allows, it is possible add support for interleaved tables.

**Comment by danhhz** [comment]
Off the top of my head, I'd guess Interleaved tables probably aren't much work once multiple tables are supported, but that's definitely a pre-requisite

**Comment by dianasaur323** [comment]
Let me add that as a stretch note in multiple tables. I believe we don't support a great restore story for interleaved tables either yet, so I was prioritizing that first.

**Comment by cuongdo** [comment]
@danhhz @benesch @mjibson @dt do we have tests that perform any SELECTs or writes after finishing a RESTORE? (if not, I really think we should add something simple to an existing test)

**Comment by dt** [comment]
@cuongdo [most of our tests](https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/sqlccl/backup_test.go) do a `SELECT count(*)`, some also [verify verify rows before and after](https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/sqlccl/backup_test.go#L1182).

**Comment by dianasaur323** [comment]
so apparently, I did not realize that we don't break up large CSVs right now, so I added that as an item for 1.2. Given that we need to start supporting data of larger scale, we should do better here. Let me know if you disagree? Also bumped off import into existing table and import without temp storage due to time constraints. cc @robert-s-lee

**Comment by mjibson** [comment]
Breaking up large CSVs is somewhere between medium and hard in terms of difficult and time. We can do it, but I think we only should if it has a fairly high level of custom value.

**Comment by dianasaur323** [comment]
@mjibson what is the current size limitation if we don't break up CSVs?

**Comment by mjibson** [comment]
We may be talking about different things. I understood breaking up CSVs to mean that if a user has one huge CSV file, then our distributed import is able to chunk that file up and process chunks in parallel. What do you think it means?

The only size limitations we have now are that there's enough temp space to hold intermediate data.

**Comment by cuongdo** [comment]
This list is a good set of issues, but it seems like we also need a prioritized list of nightly tests similar to #19170.

**Comment by dianasaur323** [comment]
@mjibson yep, that was my understanding. So based on what you said, this is a speed issue, not a size issue? We would be able to import a huge CSV file, it would just be slow?

Perhaps we should talk about this in our meeting?

**Comment by mjibson** [comment]
I'd say "not as fast as it could be" rather than slow. It's one of the various performance improvements we could make, some of which are already in our issues list. It would allow us to do some kinda cool things, though, like parallelize reading csv files among all nodes in the cluster, regardless of the number of imported files, which could result in some fairly large speed improvements. (But again, this would be a large project, and maybe complicated enough we scrap it.)

**Comment by mjibson** [comment]
Closing because these are all covered elsewhere or not going to get done soon.
