### ISSUE TITLE
stability: longer and more extensive testing of mixed version clusters

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#18811]
`TestVersionUpgrade` was initially failing in #18689 due to improper handling of mixed-version clusters. Our testing of such clusters is quite weak at the moment. We should probably have a nightly test that runs a mixed-version cluster and perhaps manually test such clusters periodically.

**Comment by tschottdorf** [comment]
What could have caught https://github.com/cockroachdb/cockroach/issues/18825#issue-261000347?

I think a test that runs a cluster under high pressure (to incentivize many lease changes) and with aggressive timings while cycling the binary versions back and forth for an hour, verifying at the end that certain invariants are met (for example, index equal => statemachine equal) would've done, as this is essentially what triggered #18825.

Probably a local acceptance test would do. This doesn't seem very dependent on the cloud, but some random latency wouldn't hurt.

**Comment by tschottdorf** [comment]
Closing for https://github.com/cockroachdb/cockroach/issues/15851.
