### ISSUE TITLE
backup/restore: track when the last backup was run on a table

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#18823]
This is to improve the general manageability of backup / restore. This could be surfaced in the admin UI, and should also be queryable through SQL. 

That being said, I doubt we have time to do this in 1.2, so marking this for 1.3.

**Comment by dt** [comment]
Off the time of my head, I a few potential ways to track this:

1) We could add a `lastBackup` to TableDescriptor (time and URI or something).
2) We could inspect the jobs table records to determine it.
3) We could add a new system table or tables recording the time, location and tables included in successful backups.

I don't like 1) very much.

2) seems like it might work, but I think the opaque, binary payload of the `system.jobs` rows means that to find backup jobs for a given table, we'd need potentially need to read everything and deserialize it to determine which jobs apply to a given table.

3) seems like it should work though in general I'm not crazy about adding new system tables left-and-right. In this case it might make sense though, and I think we could probably design it to also serve any future scheduling UI or whatever.

**Comment by dt** [comment]
@dianasaur323 I think this one wants a little more detailed definition of what we want feature-wise, both short term and, to whatever degree it is a subset, longer term for backup mgmt UI, before we're ready to pick a technical design here.

**Comment by dianasaur323** [comment]
@dt ok, go it. That means we need to allocate time to think about the feature requirements for this if we want to get it into 1.3. Putting onto my plate to take a look.

**Comment by mwang1026** [comment]
Schedules + job give you history, show backup enumerates what's available to be restored
