### ISSUE TITLE
sql: now() doesn't get evaluated before index selection

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#18836]
```
root@:26257/test> CREATE TABLE bydate(a TIMESTAMP NOT NULL);
CREATE TABLE
root@:26257/test> explain SELECT * FROM bydate WHERE a > (now() - '1h':::interval);
+-------+--------+-------+----------------+
| Level |  Type  | Field |  Description   |
+-------+--------+-------+----------------+
|     0 | render |       |                |
|     1 | scan   |       |                |
|     1 |        | table | bydate@primary |
|     1 |        | spans | ALL            |
+-------+--------+-------+----------------+
(4 rows)
```

Even though we've added a constraint to the index key, the query planner produces a full table scan. This is incorrect. We should be able to evaluate `now() - '1h':::interval` before index selection so we can add it as a constraint to the index span.

**Comment by petermattis** [comment]
`now()` is marked as impure while the comment about `impure` says:

```
	// Set to true when a function potentially returns a different value
	// when called in the same statement with the same parameters.
	// e.g.: random(), clock_timestamp(). Some functions like now()
	// return the same value in the same statement, but different values
	// in separate statements, and should not be marked as impure.
```

If we marked `now()` were marked as pure I believe it would participate in constant folding.

**Comment by knz** [comment]
It's not pure because the txn timestamp is reset across retries. We want `now()` to have a timestamp aligned with the timestamp of the txn *as finally committed*, not the timestamp of the first retry attempt.

**Comment by knz** [comment]
(I say "we want" in that the Jepsen tests have shown us this to be necessary for cases when people use now() to reflect progress of their changes. We could have two txn timestamp built-in functions side by side, and document the difference.)

**Comment by bdarnell** [comment]
Alternately, when an impure function is used in a where clause like this, we could evaluate it before planning and then re-plan on any transaction retry.

**Comment by bdarnell** [comment]
And as a workaround for applications affected by this, the current time can be computed on the client side and passed in as a query parameter: `SELECT * FROM bydate WHERE a > ($1 - '1h':::interval)`

**Comment by knz** [comment]
re-planning on each attempt *if time-based functions are used* is ... interesting. With the "sql leaf data" proposal, we can avoid doing all the planning and merely defer the (re)computation of spans to each retry attempt.

**Comment by knz** [comment]
I found the proper direction for a solution, see #26582.

**Comment by knz** [comment]
User faced this see #33696

**Comment by RaduBerinde** [comment]
I am putting this (along with #26582 which is tracking the more general problem) in the high priority for 20.2 bucket, I really think it's time to fix it.

**Comment by korpa** [comment]
Will this include an optimization for "AT TIME ZONE" as well?

```sql
CREATE TABLE table1 (id TEXT, ts TIMESTAMPTZ, kpi1 INT, kpi2 INT, PRIMARY KEY (id));

CREATE INDEX ON table1 (ts) STORING (kpi1,kpi2);
```

without "AT TIME ZONE":

```sql
EXPLAIN
WITH
days AS (
  SELECT generate_series( '2020-04-01T00:00:00', '2020-04-30T23:59:59', interval '1' day)::date  as "dateday"
),
kpis AS (
  SELECT
    date_trunc('day', "ts")::date AS "ts",
    sum("kpi1") as kpi1,
    count("kpi2") as kpi2
  FROM "table1"
  WHERE "ts" BETWEEN '2020-04-01 00:00:00' and '2020-04-30 23:59:59'
  GROUP BY 1
)
SELECT
  days.dateday::DATE as "date",
  COALESCE( kpis.kpi1, 0 ) as "kpi1",
  COALESCE( kpis.kpi2, 0 ) as "kpi2"
FROM days LEFT JOIN kpis ON days.dateday = kpis.ts
ORDER BY days.dateday DESC;
```
![image](https://user-images.githubusercontent.com/2982785/80595750-8c455b00-8a25-11ea-93a3-d0e7e3c590a0.png)

with "AT TIME ZONE"
```sql
EXPLAIN
WITH
days AS (
  SELECT generate_series( '2020-04-01T00:00:00', '2020-04-30T23:59:59', interval '1' day)::date  as "dateday"
),
kpis AS (
  SELECT
    date_trunc('day', "ts" AT TIME ZONE 'Europe/Berlin')::date AS "ts",
    sum("kpi1") as kpi1,
    count("kpi2") as kpi2
  FROM "table1"
  WHERE "ts" AT TIME ZONE 'Europe/Berlin' BETWEEN '2020-04-01 00:00:00' and '2020-04-30 23:59:59'
  GROUP BY 1
)
SELECT
  days.dateday::DATE as "date",
  COALESCE( kpis.kpi1, 0 ) as "kpi1",
  COALESCE( kpis.kpi2, 0 ) as "kpi2"
FROM days LEFT JOIN kpis ON days.dateday = kpis.ts
ORDER BY days.dateday DESC;
```

![image](https://user-images.githubusercontent.com/2982785/80595878-bc8cf980-8a25-11ea-9322-a318072d0a36.png)

**Comment by RaduBerinde** [comment]
@korpa thanks for the detailed report, I filed separate issue https://github.com/cockroachdb/cockroach/issues/48149

**Comment by jseldess** [comment]
Documented in https://github.com/cockroachdb/docs/pull/7311.
