### ISSUE TITLE
data race in TestRequestLeaderEncounterGroupDeleteError

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#1883]
Discovered in #1839. Log: https://circleci.com/gh/cockroachdb/cockroach/5243 (https://circle-artifacts.com/gh/cockroachdb/cockroach/5243/artifacts/0/tmp/circle-artifacts.3ysJikK/testrace.log)

**Comment by yananzhi** [comment]
@tamird I will take a look.

**Comment by yananzhi** [comment]
@tamird #1898

**Comment by tamird** [comment]
Fixed in #1898.
