### ISSUE TITLE
sql: Support INET column type operators

### ISSUE THREAD

**Issue by lego** [cockroachdb/cockroach#18847]
INET column types were added (#18171, #18585) but we have not yet added the of the operators found in the [postgres "Network Address Functions and Operators", Table 9-36](https://www.postgresql.org/docs/current/static/functions-net.html).

The only ones we have so far are basic comparisons, `>`, `<`, and `=`. The following operators are all of the ones provided in postgres not in CockroachDB:

| Operator | Description | Example|
|---|---|---|
|<= | is less than or equal | inet '192.168.1.5' <= inet '192.168.1.5'|
|>= | is greater or equal | inet '192.168.1.5' >= inet '192.168.1.5'|
|<> | is not equal | inet '192.168.1.5' <> inet '192.168.1.4'|
|<< | is contained by | inet '192.168.1.5' << inet '192.168.1/24'|
|<<= | is contained by or equals | inet '192.168.1/24' <<= inet '192.168.1/24'|
|>> | contains | inet '192.168.1/24' >> inet '192.168.1.5'|
|>>= | contains or equals | inet '192.168.1/24' >>= inet '192.168.1/24'|
|&& | contains or is contained by | inet '192.168.1/24' && inet '192.168.1.80/28'|
|~ | bitwise NOT | ~ inet '192.168.1.6'|
|& | bitwise AND | inet '192.168.1.6' & inet '0.0.0.255'|
|\| | bitwise OR | inet '192.168.1.6' \| inet '0.0.0.255'|
|+ | addition | inet '192.168.1.6' + 25|
|- | subtraction | inet '192.168.1.43' - 36|
|- | subtraction | inet '192.168.1.43' - inet '192.168.1.19'|

Because a few of these operators are infrequent (`<<=`, `>>=`), the infrequent ones should be implemented using functions (`sql/parser/builtins.go`) as opposed to operators (`sql/parser/eval.go`). Any new operators will also have to introduce special cases to parse the multi-character operators into tokens (`sql/parser/scan.go`).

**Comment by jkominek** [comment]
I was thinking about working on this, but I don't understand how it would be possible to implement the infrequent operators using builtin functions. PostgreSQL has a whole mechanism for assigning functions to operators, but I can't find any hint of that in Cockroach. (It seems like there'd be something in `sql/parser/eval.go` or `sql/parser/expr.go` where a failure would fall through to some additional mechanism for finding the appropriate function; but I'm not seeing it.)
What am I missing?

While I'm at it; what's the cut off for infrequent operators on this list? I feel like the containment operators would see more use on the inet type than > and <.

**Comment by lego** [comment]
We do have a mechanism for that!

Also, when I mentioned infrequent operators, I meant operators that aren't defined for many types, not by their use frequency.

The differentiation is that the operators that are defined on multiple types have mappings for handling the various  (as you may have found already in [sql/parser/expr.go](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/parser/expr.go#L281-L326) -- the groups of operators are `BinaryExpr`, `UnaryExpr` and `ComparisonExpr`). Then they have the corresponding logic of the operator in [sql/parser/eval.go ](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/parser/eval.go#L146-L155). You should be able to search that file for strings of operators to see if they're already done here, e.g. searching for `"~"` yields `RegMatch`.

On the other hand, the less used operators that are mapped to functions happens mainly in two places:
- [sql/parser/sql.y](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/parser/sql.y#L5151-L5154), the SQL grammar file. If you search for all instances the operator in the example `REMOVE_PATH` you'll see a few places where it's defined that will be similar for this addition.
- [sql/parser/builtins.go](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/parser/builtins.go#L1613-L1616) where the function is defined and the operator logic is.

You'll also need to teach the scanner to scan new tokens, inside [sql/parser/scan.go](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/parser/scan.go#L452-L456). This is required for operators that are more than 1 character (due to how YACC grammars work). 

PS, thanks for jumping on this @jkominek, I hope this helps! I'm happy to help mentor and review :). You can also reach out to me on our gitter channel if you need more help.

**Comment by lego** [comment]
Hey @jkominek, Checking in to see if you've made any progress. If you're no longer able to work on this, that's a-okay!

**Comment by mwistrom** [comment]
I'd like to pick this issue up if no one else is working on it.

**Comment by lego** [comment]
@mwistrom feel free to, I haven't picked this up yet.

**Comment by mwistrom** [comment]
So, I've got a couple of comments/questions. Lemme know if there is another forum for posting them.

1. I assume the functional spec is generally "Make it work like Postgresql".

2. I've got most of the operations fleshed out, except for <<, >> and &&. It is not clear to me how to overload those specific ones. 

<< and >> are currently implemented as the BinaryExpr bit shift operators. << and >> should return a Boolean for the INet types, but it isn't clear how a BinaryExp would do that. Usually it is a ComparisonExpr. 

I don't see how to overload the && operator. It seems to be special.

I haven't looked too far into the code to come up with any proposed solutions yet. Just wondering if there is a quick simple answer, that I haven't seen yet.

3. Is it desirable to have the same error numbers as Postgresql for the specific errors? Specifically, I don't see 22003, which is returned in Postgresql to indicate an overflow. Should I add 22003 or just pick another error code? Seems that the error codes were copied from Postgresql, but some were left out and there was some manual munging.

Thanks in advance for your help/answers.
Mark

**Comment by lego** [comment]
This place is perfect for any questions.

1. Yep, exactly that.

2. In eval.go there are the `BinOp` definitions for LShift and RShift, which also have a specified left/right input and output types(1). You should be able to just specify `LeftType: types.INet, RightType: types.INet, ReturnType: types.INet` and the function body there just as you would for the functions.  

(1): https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/tree/eval.go#L1141-L1150 

3. Yes, it is preferable to have the same error numbers. All of the codes should be present in [sql/pgwire/pgerror/codes.go](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/pgwire/pgerror/codes.go), which `22003` is. Usually, to track down the error code for things, we will run the statement in postgres after using `\set VERBOSITY 'verbose'` and that will return the error code that can then be cross-referenced in `codes.go`.

(Sidenote: I realize the code links in the above comment were outdated after a major shuffling of files, so I've updated that but the line numbers are still a bit off. The file names are similar, just the paths changed.)

**Comment by mwistrom** [comment]
Finishing the tests. Last 10% of the work seems to always be a lot more than 10%.   :|

**Comment by lego** [comment]
If you'd like, you can push up the branch to your fork and I'd happy to take a look at it if there is anything in particular :)

**Comment by mwistrom** [comment]
Whoops. I think I went ahead and submitted a PR. Paying too much attention to the football game.

I'm still a little hazy on the precedence order for the operators that I implemented "<<=, >>=, &&". I added them to the same line as RShift and LShift, which are of course, all related.

**Comment by nvanbenschoten** [comment]
Was this fully addressed by #21437, or is there more to this issue?

**Comment by mwistrom** [comment]
It was fully addressed by my PR.

 

18847 can be closed.

**Comment by nvanbenschoten** [comment]
Thanks @mwistrom!

**Comment by mwistrom** [comment]
It was fun!!
