### ISSUE TITLE
sql: descriptor acquisition waits for in-flight lease acquisition unnecessarily

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#18851]
https://github.com/cockroachdb/cockroach/blob/4a23ce1082a8d8802f09c2d75209d0eaf1ddf901/pkg/sql/lease.go#L592

The misnamed `tableState.acquire()` is given a timestamp and asked to return a descriptor valid for that timestamp. It invariably waits for any in-flight lease acquisitions, even if the timestamp is below the frontier at which leases are needed.

**Comment by andreimatei** [comment]
cc @vivekmenezes

**Comment by lego** [comment]
This was fixed by #19005
