### ISSUE TITLE
server: alert on dubious --advertise-host

### ISSUE THREAD

**Issue by acacio** [cockroachdb/cockroach#18850]
Hi,

I've just finished tracking a replication issue across a cluster. The issue was a missing --advertise-host= flag BUT the troubleshooting was hampered by the lack of logging on failed replication actions.

Overview:
- 4 machines
- 3 in a datacenter (Hetzner)
- 1 as a VM replica (Scaleway)
- VM has a private IP (10.x) which is NAT'ed to a public IP (51.x.x.x)
- I had missed the --advertise-host=51.x.x.x flag

2. Please describe the issue you observed:
- The cluster was well connected and reporting all 4 nodes
- The VM had ZERO replicas (the rest had 200 replicas per node) and there were NO errors in the logs.
- I had full verbosity turned on the cluster settings.
- The other only hint was that there were "Pending Actions" roughly the same number as the "Replicas per Node"
- I was able to connect from the other hosts to the VM with "cockroach sql"
- In that connection, I was able to see cluster config, databases, etc... BUT NOT able to do a SELECT. Would get a "No inbound stream". 

Once I fixed the --advertise-host=51.x.x.x config all the replicas flowed to the VM without an hitch and now SELECT's also work.

My request is that the __logging for failed "Pending Actions" should be increased__ to help with troubleshooting, in other similar cases.

**Comment by acacio** [comment]
<img width="749" alt="screen shot 2017-09-28 at 00 24 48" src="https://user-images.githubusercontent.com/165871/30940997-a502babe-a3e3-11e7-9788-21895d3c51c0.png">
<img width="746" alt="screen shot 2017-09-28 at 00 25 28" src="https://user-images.githubusercontent.com/165871/30940996-a5021e56-a3e3-11e7-8dfd-38ee7e17c367.png">

**Comment by acacio** [comment]
<img width="749" alt="screen shot 2017-09-28 at 00 24 48" src="https://user-images.githubusercontent.com/165871/30941109-35412d18-a3e4-11e7-96bf-4ca9b31e0e7e.png">
<img width="746" alt="screen shot 2017-09-28 at 00 25 28" src="https://user-images.githubusercontent.com/165871/30941111-3543ec38-a3e4-11e7-8b65-771d5af52d02.png">
<img width="629" alt="screen shot 2017-09-28 at 00 29 40" src="https://user-images.githubusercontent.com/165871/30941110-35427164-a3e4-11e7-9f02-ba755505c6a0.png">

**Comment by dianasaur323** [comment]
@acacio I've actually personally had the same issue! It's frustrating for sure. I actually think we can do better here - this is a problem with the nodes not being able to talk to each other, so we could better report how networking is flowing across nodes. We have two features coming up in the next year that should address this issue. I'll keep this issue open until we release the features I'm talking about (still being defined), and will update with more details when we get there.

**Comment by acacio** [comment]
Would it not be possible to just log dial errors? 
That would be enough to enable troubleshooting connection issues, at a cost of additional logging. Maybe sample the logging, if the rate of dial'ing is too high.

**Comment by a-robinson** [comment]
We do need to do more here, but I'm actually surprised that no dial errors showed up in the logs. They typically do get logged, looking something like:

```
I171002 14:46:57.097208 48 vendor/google.golang.org/grpc/clientconn.go:806  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 45.77.103.118:26257: i/o timeout"; Reconnecting to {45.77.103.118:26257 <nil>}
```

And we have logic for throttling them, since as you mention they can get pretty annoying:

https://github.com/cockroachdb/cockroach/blob/master/pkg/util/grpcutil/log.go#L97

In this case, I'd have expected to see those log messages once per minute on all the nodes other than the one behind the NAT.

**Comment by tschottdorf** [comment]
@mberhault assigning you to revisit.

The below are the error messages you see when using my "repro" script.

```
I180524 22:04:59.298145 226 storage/replica_proposal.go:202  [n1,s1,r21/1:/Table/5{0-1}] new range lease repl=(n1,s1):1 seq=3 start=1527199461.735422189,0 epo=1 pro=1527199499.292040400,0 following repl=(n1,s1):1 seq=2 start=1527199461.735422189,0 exp=1527199470.735644995,0 pro=1527199461.735669933,0
I180524 22:04:59.298658 112 storage/replica_raftstorage.go:520  [replicate,n1,s1,r21/1:/Table/5{0-1}] generated preemptive snapshot 575e7e1e at index 18
I180524 22:04:59.298688 112 storage/replicate_queue.go:226  [replicate,n1,s1,r21/1:/Table/5{0-1}] snapshot failed: breaker open
I180524 22:04:59.359786 112 storage/replica_raftstorage.go:520  [replicate,n1,s1,r21/1:/Table/5{0-1}] generated preemptive snapshot 189ba583 at index 18
I180524 22:04:59.359867 112 storage/replicate_queue.go:226  [replicate,n1,s1,r21/1:/Table/5{0-1}] snapshot failed: initial connection heartbeat failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded
I180524 22:04:59.475615 112 storage/replica_raftstorage.go:520  [replicate,n1,s1,r21/1:/Table/5{0-1}] generated preemptive snapshot 4e524ce9 at index 18
I180524 22:04:59.475662 112 storage/replicate_queue.go:226  [replicate,n1,s1,r21/1:/Table/5{0-1}] snapshot failed: breaker open
I180524 22:04:59.696677 112 storage/replica_raftstorage.go:520  [replicate,n1,s1,r21/1:/Table/5{0-1}] generated preemptive snapshot 874a68a9 at index 18
I180524 22:04:59.696709 112 storage/replicate_queue.go:226  [replicate,n1,s1,r21/1:/Table/5{0-1}] snapshot failed: breaker open
I180524 22:05:00.112895 112 storage/replica_raftstorage.go:520  [replicate,n1,s1,r21/1:/Table/5{0-1}] generated preemptive snapshot 3a096eba at index 18
I180524 22:05:00.112972 112 storage/replicate_queue.go:226  [replicate,n1,s1,r21/1:/Table/5{0-1}] snapshot failed: initial connection heartbeat failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded
I180524 22:05:00.909592 112 storage/replica_raftstorage.go:520  [replicate,n1,s1,r21/1:/Table/5{0-1}] generated preemptive snapshot 8848062a at index 18
I180524 22:05:00.909679 112 storage/replicate_queue.go:226  [replicate,n1,s1,r21/1:/Table/5{0-1}] snapshot failed: initial connection heartbeat failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded
E180524 22:05:00.909727 112 storage/queue.go:778  [replicate,n1,s1,r21/1:/Table/5{0-1}] failed to replicate after 5 retries
I180524 22:05:00.915977 241 storage/replica_proposal.go:202  [n1,s1,r19/1:/Table/2{2-3}] new range lease repl=(n1,s1):1 seq=3 start=1527199461.735422189,0 epo=1 pro=1527199500.909784016,0 following repl=(n1,s1):1 seq=2 start=1527199461.735422189,0 exp=1527199470.735644995,0 pro=1527199461.735669933,0
I180524 22:05:00.916485 112 storage/replica_raftstorage.go:520  [replicate,n1,s1,r19/1:/Table/2{2-3}] generated preemptive snapshot b8fe543c at index 18
I180524 22:05:00.916530 112 storage/replicate_queue.go:226  [replicate,n1,s1,r19/1:/Table/2{2-3}] snapshot failed: breaker open
I180524 22:05:00.972936 112 storage/replica_raftstorage.go:520  [replicate,n1,s1,r19/1:/Table/2{2-3}] generated preemptive snapshot d0d8fcb1 at index 18
I180524 22:05:00.972980 112 storage/replicate_queue.go:226  [replicate,n1,s1,r19/1:/Table/2{2-3}] snapshot failed: breaker open
```

**Comment by tschottdorf** [comment]
https://github.com/cockroachdb/cockroach/issues/25316 is a related problem I folded into this one. There, the advertise host is correct, but a firewall accidentally prevented communication (but only for one host). Ideally we warn in that scenario as well.

**Comment by mberhault** [comment]
duplicate of #24630

**Comment by tschottdorf** [comment]
Reopening as we'll try to do something about this in the 2.1 timeframe, and #24630 won't see any more activity until 2.2 (and is wider in scope).

**Comment by tschottdorf** [comment]
Another user requested this: https://github.com/cockroachdb/cockroach/issues/25316#issuecomment-431101852
