### ISSUE TITLE
testing: TestCluster should by default create a cluster with servers running with different clocks

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#18864]
The thinking here is that it will better simulate a real cluster.

It's likely that parts of 
https://github.com/cockroachdb/cockroach/pull/18553
need to be reverted

Creating this issue to check if this is something we should do.

**Comment by lunevalex** [comment]
TestCluster does use a different clock per server and recent work in #8299 added support for a custom ClockSource via the server.TestingKnobs.
