### ISSUE TITLE
sqlccl: better rate limiting for disk writes

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#18869]
https://github.com/cockroachdb/cockroach/blob/14c5215987e857d881c46749dbcf42f1a724ae1d/pkg/ccl/acceptanceccl/backup_test.go#L80

**Comment by dt** [comment]
I think we decided that fsyncing was our next approach here, before more limiting, and also that we're not going to put too much effort into accommodating bad azure disks.
