### ISSUE TITLE
sqlccl: filter out unhealthy nodes

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#18877]
https://github.com/cockroachdb/cockroach/blob/14c5215987e857d881c46749dbcf42f1a724ae1d/pkg/ccl/sqlccl/csv.go#L1075

**Comment by dt** [comment]
Closing this one until we actually see this in practice or something. Also, maybe we should consider not having individual features do this, but something more reusable, e.g. have only healthy nodes handed out by the gossip list's public helpers or something so we don't need to do this same filtering over and over.
