### ISSUE TITLE
sqlccl: further tune split and scatter

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#18878]
https://github.com/cockroachdb/cockroach/blob/14c5215987e857d881c46749dbcf42f1a724ae1d/pkg/ccl/sqlccl/restore.go#L557

Talk to Dan for context.

**Comment by dt** [comment]
bug triage question: is this still applicable with a) more recent scatter rewrites b) the fact we switched to splitting and scattering as we go?

**Comment by lunevalex** [comment]
Closing based on last comment from @dt and age.
