### ISSUE TITLE
sqlccl: delete imported data when a RESTORE fails

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#18881]
https://github.com/cockroachdb/cockroach/blob/14c5215987e857d881c46749dbcf42f1a724ae1d/pkg/ccl/sqlccl/restore.go#L921

Recording some thoughts:
You can cancel running or failed jobs.
When user clicks cancel, we send deletion of all the ranges out.
When something fails, we leave it alone so you can retry if you want, or cancel.
We consider surfacing number of failed (but not canceled) jobs.

**Comment by dt** [comment]
This seems particularly important in the case where a user runs the explicit cancel action. If you're able to explicitly cancel a failed job, having cancel be where we clean up the ranges could be a solution here, or just having a failure callback run it.

**Comment by dianasaur323** [comment]
@mjibson I seem to remember seeing you merging a fix for this? Can we close out in that case?

**Comment by mjibson** [comment]
Yes!
