### ISSUE TITLE
storageccl: retry AddSSTable when it races with a range split

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#18882]
https://github.com/cockroachdb/cockroach/blob/14c5215987e857d881c46749dbcf42f1a724ae1d/pkg/ccl/storageccl/add_sstable.go#L100
https://github.com/cockroachdb/cockroach/blob/14c5215987e857d881c46749dbcf42f1a724ae1d/pkg/ccl/storageccl/import.go#L187

Change these to comments instead of TODOs.

**Comment by mjibson** [comment]
@danhhz I forget: what is the user-facing impact of this? Does the restore fail?

**Comment by dt** [comment]
this one seems really hard to hit, right? like, what would split that range during the restore?

**Comment by danhhz** [comment]
Yes, restore would fail, but this is very hard to hit.

**Comment by dt** [comment]
dupe #17819
