### ISSUE TITLE
storageccl: lots of cgo calls in Backup

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#18884]
https://github.com/cockroachdb/cockroach/blob/14c5215987e857d881c46749dbcf42f1a724ae1d/pkg/ccl/storageccl/engineccl/mvcc.go#L44
https://github.com/cockroachdb/cockroach/blob/14c5215987e857d881c46749dbcf42f1a724ae1d/pkg/ccl/storageccl/export.go#L144

This should reduce p99 by a lot.

**Comment by dt** [comment]
likely cause of #16276

**Comment by rolandcrosby** [comment]
Fixed by #37496
