### ISSUE TITLE
sqlccl: Consider compacting after Ingest

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#18886]
After AddSSTable, it may be smart to run a rocksdb compaction. We could also add a compact sql statement, or an option during a restore. But we want something that's good for users most of the time.

Importing data with AddSSTable makes lots of little files. These *might* be bad:

To test:
1) create two identical clusters
2) measure baseline QPS/latency perf and open files of some workload on a) to get a baseline.
3) backup a) and restore on b), perform same workload and measurement, compare to baseline.

Based on the results:
- If perf and open files looks the same, nothing to do here.
- If perf is lower, we might want an explicit SQL-level compaction command.
- If open files looks high during or after, we might need to look at having restore (or any caller of AddSSTable) run compactions as it goes to keep open-file count reasonable.

**Comment by dt** [comment]
next action item here: 
1) create two identical clusters
2) measure baseline QPS/latency perf and open files of some workload on a) to get a baseline.
3) backup a) and restore on b), perform same workload and measurement, compare to baseline.

- If perf and open files looks the same, nothing to do here.
- If perf is lower, we might want an explicit SQL-level compaction command.
- If open files looks high during or after, we might need to look at having restore (or any caller of AddSSTable) run compactions as it goes to keep open-file count reasonable.

**Comment by mwang1026** [comment]
Storage team is working on read-based compaction heuristics cc @petermattis in case you want to reopen
