### ISSUE TITLE
ui: healthy nodes can appear suspect if client clock is wrong

### ISSUE THREAD

**Issue by couchand** [cockroachdb/cockroach#18896]
While #18260 fixed the spurious suspect node issue (#17840) when it is due to network latency, it didn't quite resolve every way this sort of problem could manifest.  Specifically, if the client's clock differs from the server's clock by more than the liveness interval, we'll call that suspect.

We should probably just send the server's timestamp back with the results, and use that instead.

**Comment by tschottdorf** [comment]
*Maybe* this is what I'm seeing. I'm in Germany (though my laptop remains on EST) and I'm running a local 10 node cluster (don't ask why) and everything except the node whose UI I'm looking at is suspect:

![image](https://user-images.githubusercontent.com/5076964/31610849-fe21e864-b279-11e7-9ea2-329254ce974d.png)

Though now that I've checked back, most of the nodes are actually green.

Either way, it seems unfortunate that when a node is suspect there isn't any information as to how the ui came to that conclusion.
