### ISSUE TITLE
ui: trim generated javascript protos

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#18906]
`ui/src/js/proto.js` contains the generated javascript code for all of the protos in the system. This is overly large because many of these protos are not actually used. For example, `MVCCMetadata` is not used by the UI (AFAICT). Is something in the build system is stripping this unused code?

**Comment by benesch** [comment]
This should be verified, but I believe UglifyJS performs tree shaking on the final compiled bundle. So `protos.js` is theoretically only bloating our repo (and that'll be fixed by #18349).
