### ISSUE TITLE
build/deploy: missing ca certificates

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#18905]
Attempting to run a BACKUP from the deploy docker image:

```
x509: failed to load system roots and no roots provided
```

I think deploy/Dockerfile just needs `RUN apt-get update && apt-get -y upgrade && apt-get install -y ca-certificates`

But I can't test it because of #18904

**Comment by mjibson** [comment]
Update: that did fix the problem. I'll submit a PR.

**Comment by a-robinson** [comment]
Thanks, @mjibson!
