### ISSUE TITLE
build: cannot find -lroach

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#18904]
Running `./build/builder.sh make build TYPE=release-linux-gnu` (from a Debian machine):

```
# github.com/cockroachdb/cockroach/pkg/storage/engine
/x-tools/x86_64-unknown-linux-gnu/lib/gcc/x86_64-unknown-linux-gnu/6.3.0/../../../../x86_64-unknown-linux-gnu/bin/ld.bfd: cannot find -lroach
/x-tools/x86_64-unknown-linux-gnu/lib/gcc/x86_64-unknown-linux-gnu/6.3.0/../../../../x86_64-unknown-linux-gnu/bin/ld.bfd: cannot find -lprotobuf
/x-tools/x86_64-unknown-linux-gnu/lib/gcc/x86_64-unknown-linux-gnu/6.3.0/../../../../x86_64-unknown-linux-gnu/bin/ld.bfd: cannot find -lrocksdb
/x-tools/x86_64-unknown-linux-gnu/lib/gcc/x86_64-unknown-linux-gnu/6.3.0/../../../../x86_64-unknown-linux-gnu/bin/ld.bfd: cannot find -lsnappy
collect2: error: ld returned 1 exit status
Makefile:177: recipe for target 'build' failed
make: *** [build] Error 2
```

**Comment by a-robinson** [comment]
I... know next to nothing about our build details or the guts of the builder image, and this is unrelated to the tweak I made to the deploy image last week. @benesch, do you have time to check into this with me shoulder surfing next to you this week?

**Comment by benesch** [comment]
Sure thing. In the meantime, @mjibson, you might have luck with `build/builder.sh make clean TYPE=release-linux-gnu`.

**Comment by a-robinson** [comment]
Great! I'm already being pretty interrupt-driven this week so just let me know when you're checking it out and I'll come join

**Comment by mjibson** [comment]
Haven't seen this since (but haven't tried much either). Could have been a git bug. Closing unless it happens again.

**Comment by mjibson** [comment]
This happened again while building master on a Debian machine.

**Comment by benesch** [comment]
Can you list the exact steps you took? Ideally also the first few lines of
make output.

**Comment by benesch** [comment]
I'm pretty sure a corrupted GOPATH got into your zcgo_flags files.

**Comment by a-robinson** [comment]
@mjibson is this still relevant?

**Comment by mjibson** [comment]
Haven't seen it since.
