### ISSUE TITLE
perf: quantify network space overhead

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#18919]
Similar to #18659 I decided to look at the overhead in `Batch{Request,Response}` for simple "kv" reads (i.e. a single `Scan{Request,Response}` in the batch). 

```
  BatchRequest:               191
  BatchRequest.Header:        156
  BatchRequest.Header.Txn:    122
  BatchRequest.Requests[0]:   30
  BatchResponse:              189
  BatchResponse.Header:       138
  BatchResponse.Header.Txn:   122
  BatchResponse.Responses[0]: 46
```

The `Scan{Request,Response}` consume exactly 20% of the total bytes sent/received. The request and response txn consume 64% of the bytes. The response txn is nearly identical to the request txn with only `Transaction.MaxTimestamp` having changed. 

There are some small gains to be had by converting `Batch{Request,Response}`, `Transaction` and `TxnMeta` to proto3 to avoid encoding zero value primitive fields. There is a large gain to be had by only returning the delta of the transaction in the response. 

Cc @andreimatei who suggested last week that we develop a more principled way to update the transaction upon receiving a response.

**Comment by tschottdorf** [comment]
+1 to only returning a transaction delta (at least for common cases).

**Comment by petermattis** [comment]
@tschottdorf Do you have time to tackle only sending a transaction delta in the response? I think you're the most knowledgeable person about this code. If not, perhaps you can give guidance to someone else. Feels like a fairly small project, though I might be missing subtleties.

**Comment by tschottdorf** [comment]
Ack, assigning.

**Comment by andreimatei** [comment]
I think we probably agree that what should be returned by the server is not a brute "delta", but a specific set of instructions about what the server wants the client to do (to the transaction).

**Comment by petermattis** [comment]
@andreimatei That might be cleaner, though it also might add an unfortunate migration story.

**Comment by tschottdorf** [comment]
@andreimatei I was picturing something like the below which gets terminated at `TxnCoordSender` (i.e. `client.Txn` would still see the full proto). This is provisional and I have to figure out what to stick in the error messages.

I'm not too worried about the migration with regards to correctness. We can add the new field and populate it only when the cluster version indicates this is safe.

Let me know if you pictured something different.

```proto
message TxnMetaDelta {
  // Never needed.
  // optional bytes id = 1;

  // Never changes.
  // optional IsolationType isolation = 2;

  // Never returned in a reply.
  // optional bytes key = 3; // TODO(tschottdorf): [(gogoproto.casttype) = "Key"];

  // Never returned in a reply.
  // optional uint32 epoch = 4 [(gogoproto.nullable) = false];

  optional util.hlc.Timestamp timestamp = 5;
  optional int32 priority = 6;

  // Never useful on responses.
  // optional int32 sequence = 7;

  // Never useful anywhere on the wire.
  // optional int32 batch_index = 8;
}

message TransactionDelta {
  // NB: TxnMetaDelta will be inlined and we'll reorder fields that are most
  // likely to be set to low field tags.
  optional storage.engine.enginepb.TxnMetaDelta meta_delta = 1;

  // I believe this isn't necessary except for EndTransaction, so we could also
  // just give a new flag to EndTransaction. Or in fact, it doesn't even seem
  // necessary because the client will know what they asked for and if they get
  // success, they know the new state (i.e. if you try to commit and you're in
  // fact aborted, a TransactionAbortedError is the result, not a successful
  // response with an ABORTED delta).
  optional TransactionStatus status = 4;

  optional util.hlc.Timestamp last_heartbeat = 5;
  // Never updated, only reset on Restart
  // optional util.hlc.Timestamp orig_timestamp = 6;

  // Never updated.
  // optional util.hlc.Timestamp max_timestamp = 7;

  // Often will only receive zero or one timestamp, but can receive more than one
  // for multi-range requests at the DistSender level.
  repeated ObservedTimestamp observed_timestamps = 8;

  // Note that the unmarshaler can be smart about EmptyMessage and simply return
  // a pointer to a singleton struct{}, i.e. no allocs. This is OK because
  // writing to an empty struct through a pointer is actually a no-op:
  // https://github.com/tschottdorf/goplay/blob/master/race_emptystruct_writes/emptystruct_test.go.
  // Should check that gogoproto knows that.
  optional EmptyMessage writing = 9;
  optional EmptyMessage write_too_old = 12;
  optional EmptyMessage retry_on_push = 13;

  // Never sent back in a reply, only ever set in EndTransactionRequest.
  // repeated Span intents = 11;
}
```

**Comment by petermattis** [comment]
I think `observed_timestamps` can be `optional Timestamp observed_timestamp` as we only ever return a single timestamp and that is for the node that received the request.

When do we return `last_heartbeat`? I'm probably just missing the code path. 

Rather than separate `writing`, `write_too_old` and `retry_on_push` fields, could you have a bitfield?

**Comment by tschottdorf** [comment]
@petermattis re `observed_timestamps`, the inline comment addresses this: We only ever return one from a single BatchRequest, but DistSender needs to glue them together and multi-range requests may return more. We could optimize that somehow, but above DistSender we'll definitely want the slice. Or we terminate it at `DistSender` but transaction updates happen in `TxnCoordSender` and I don't think that should change.

You're right, I missed `last_heartbeat`. It's returned only from `HeartbeatTxn` but that should just return the whole txn anyway.

> Rather than separate writing, write_too_old and retry_on_push fields, could you have a bitfield?

We could, but is that better? The `EmptyMessage` versions are alloc-free, and `write_too_old` and `retry_on_push` are rarely set. I don't think we can do anything smaller than an empty message on the wire?

**Comment by andreimatei** [comment]
What I was imagining was "the server" returning to "the client" a list of explicit instructions on what it wants the client to do. Most, but not all, of these instructions would result in the client updating its copy of the proto and using the updated proto when sending subsequent requests. Some of the instructions can be carried by successful responses, some of them can be carried by errors (particularly retriable error).

In my book, this would be a *major* step forward in the clarity/comprehensibility/readability/greppability of the "KV" layer. We can call it "logical transaction updates", in contrast with the current "physical" transaction updates.

For example, there'd be an instruction to record an observed timestamp:
```
message RecordObservedTimestamp {
  node_id NodeID;
  ts Timestamp;
}
```
There'd be an "instruction" informing the client that the transaction started "writing":
```
message TxnEnteredWritingMode {
}
```
There'd be an instruction telling the client that the transaction has been pushed (and yet it can continue to run if the client so choses):
```
message TxnPushed {
  old_ts Timestamp;
  new_ts Timestamp;
  commit_will_surely_be_rejected bool;
}
```
There'd be one informing the client that the transaction was found to have been aborted (maybe more generally one about the status being found to have been updated asynchronously, I'm not sure):
```
message TxnAborted {
  // reason?
}
```

For retriable errors:
There'd be one informing the client that it needs to retry at a higher epoch:
```
message Restart{
// epoch? Or can the epoch be entirely computed by the client?
// minPriority?
}
```
Something for `TransactionAbortedError`, telling the client to retry with a completely new transaction:
```
message TryAgain {
  // minPriority?
}
```

**Comment by tschottdorf** [comment]
@andreimatei  I like the idea of naming them instructively, though I'm less sold on returning a list (=slice?) of updates. This isn't necessary when the updates are "orthogonal", and if they overlap, there's always a straightforward rule to merge them (plus it appears that that should be rare). WDYT?

**Comment by andreimatei** [comment]
I don't particularly care about returning a list of updates versus a "map" of them (i.e. they can all be in one flat proto). What I care about is changing the mindset from saying that the server returns "an updated proto" (or, equivalently, a delta) to saying that the server returns a list of... facts, for lack of a better word. Conceptually, these should be more abstract than a delta. For example, there's a difference between the server telling to the client "Btw, my current timestamp is _t_. Do what you will with this information." and then the client choosing to use _t_ to update something versus the (current) server telling the client "the list of observed timestamps in your txn proto should be [..., _t_, ...] (or even the slightly better (proposed here) "you should add _t_ to the list of observed timestamps in your proto"). The distinction is that in one case it's clear what I need to trace in the code to see who's producing the "observed timestamp" fact, in the other I have to trace in a more opaque structure. Also, the former clearly expresses an intent, the latter not so much (if some observed timestamps are not in the delta, should they be removed? Can the delta even encode a removal?).

Perhaps this seems like a distinction without a difference; the difference becomes more clear in the case of restarts. For example, for a `TransactionAbortedError`, talking about a "delta" doesn't even make sense: the server wants the client to create a brand new transaction!

Am I making sense?

**Comment by petermattis** [comment]
I'm not too particular about the interface, but let's remember to pay attention to performance here. There are two axes I'm thinking of: the size of the "transaction update" as sent over the wire and the memory and cpu overhead for encoding and decoding the update. With @tschottdorf's proposal, I can see the network size reduction and understand that the decoding overhead will be less. I'm less sure about your proposal, but that's primarily because it is less concrete.

@tschottdorf Yep, I missed the inline comment about observed_timestamps. That's a good point, though a given `BatchResponse` RPC as returned from a node will only have a single timestamp. We could consider a refactor of the `DistSender` code so that each received RPC could update state back in the `TxnCoordSender`. Mildly onerous, but it would get rid of including the node id in the `TransactionDelta` response which is redundant information (we know which node we sent the RPC to).

> > Rather than separate writing, write_too_old and retry_on_push fields, could you have a bitfield?
>
> We could, but is that better? The EmptyMessage versions are alloc-free, and write_too_old and retry_on_push are rarely set. I don't think we can do anything smaller than an empty message on the wire?

I'm not sure it is better, just mentioning it as an alternative. If we were setting multiple of these booleans in the response, then I think the bitfield would encode smaller. But this is all marginal savings.

Note with proto3, using `optional bool writing` would be fine too. When sending the `false` value, nothing is encoded on the wire. If we're adding a new proto, we should probably make it use the proto3 encoding.

**Comment by tschottdorf** [comment]
@petermattis I have a PR out but this won't be ready for the feature freeze and is not going to be cherry-pickable. I suggest we punt this for 2.1.

**Comment by nvanbenschoten** [comment]
@m-schneider recently began looking into this again. The approach taken was more similar to what @petermattis discussed in https://github.com/cockroachdb/cockroach/issues/18919#issuecomment-336594163 than what was prototyped in https://github.com/cockroachdb/cockroach/pull/21458. Specifically, unchanged txn proto fields were zeroed out before being returned in a `BatchResponse`. Now that the `Transaction` proto is using proto3, this meant that the unchanged fields were omitted during serialization. Special care was needed with the transaction's ID field, as this is a custom type (`uuid.UUID`) with custom serialization/deserialization logic.

Masha, do you mind providing an overview of the approach you took along with a discussion of the effect that you observed the change have on network traffic and general performance? This will be helpful in demonstrating how impactful we expect the change to be.
