### ISSUE TITLE
sql: numeric type discrepancy in node driver

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#18929]
Not sure what the root cause of this is, but some differences from Postgres in the following code:

```javascript
client.query({
  text: 'SELECT 3 a',
}, (err, r) => {
  let val = r.rows[0].a
  console.log(`value is ${val}, type is ${typeof val}`);
});
```

Cockroach:
```
value is 3, type is string
```

Postgres:
```
value is 3, type is number
```

They both have strings if the number is large enough:
```javascript
client.query({
  text: 'SELECT 9999999999 a',
  values: []
}, (err, r) => {
  let val = r.rows[0].a
  console.log(`value is ${val}, type is ${typeof val}`);
});
```

Cockroach:
```
value is 9999999999, type is string
```

Postgres:
```
value is 9999999999, type is string
```

Also, maybe related - this errors (`CodeNumericValueOutOfRange`) in Postgres but not Cockroach:
```javascript
...
  text: 'SELECT 9999999999::INT a',
...
```

Perhaps node-postgres is setting some max integer value somewhere that we're not respecting?

cc @benesch

**Comment by benesch** [comment]
Afraid I don't think there's much to do here unless we decide to support (proper) `int4`s in Cockroach. In psql:

```
# select pg_typeof(9999999999), pg_typeof(3);
 pg_typeof | pg_typeof 
-----------+-----------
 bigint    | integer
(1 row)
```

In Cockroach:

```
root@:26257/> select pg_typeof(9999999999), pg_typeof(3);
+-----------------------+--------------+
| pg_typeof(9999999999) | pg_typeof(3) |
+-----------------------+--------------+
| int                   | int          |
+-----------------------+--------------+
(1 row)
```

The node-pg driver is smart enough to realize that an int4 can always be represented exactly as a JavaScript Number and casts it accordingly.

**Comment by justinj** [comment]
I see, that's too bad.
