### ISSUE TITLE
perf: investigate perf diff from batched reads

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#18935]
Against a single-node local cluster, there is a huge performance difference between batched and unbatched reads. For the tests below, `kv` is generating read operations with the form `SELECT ... WHERE K IN (...)`. The keys being read are uniformly randomly distributed.

The difference between the 2 runs is the work taking place in the `sql` layer. `kv` uses prepared queries, but we don't currently cache query plans. With `--batch=1` we're doing twice as much query planning as with `--batch=2` for the same number of keys being read. And we're generating twice as many `BatchRequest` RPCs, though inside those RPCs we have the same number of `ScanRequest` operations (one per key). Need to verify that it is the overhead of `sql` processing that is the difference here and not some other effect. 

```
~ kv --read-percent=95 --batch=1 --duration=10s
_elapsed___errors__ops/sec(inst)___ops/sec(cum)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)
      1s        0        22439.3        22438.9      0.5      1.8      3.7     11.0
      2s        0        22782.3        22610.9      0.5      1.8      3.8     11.0
      3s        0        22492.6        22571.6      0.5      1.8      3.5     10.5
      4s        0        22101.1        22454.0      0.5      1.9      3.7     14.2
      5s        0        22400.5        22443.3      0.5      1.8      3.4     15.7
      6s        0        22245.6        22410.3      0.5      1.8      3.9     15.7
      7s        0        22175.5        22376.8      0.5      1.9      3.7     14.2
      8s        0        22302.6        22367.5      0.5      1.9      3.8     16.3
      9s        0        21791.4        22303.5      0.5      2.0      3.9     17.8
     10s        0        21808.0        22254.0      0.5      2.0      3.8     13.6

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)
   10.0s        0         222556        22254.0      0.7      0.5      1.9      3.7     17.8

~ kv --read-percent=95 --batch=2 --duration=10s
_elapsed___errors__ops/sec(inst)___ops/sec(cum)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)
      1s        0        40591.5        40590.5      0.6      2.0      3.8     12.6
      2s        0        42268.2        41429.3      0.6      2.0      3.8      8.9
      3s        0        42079.7        41646.2      0.6      1.9      3.8     11.5
      4s        0        41995.9        41733.5      0.6      2.0      3.9     13.6
      5s        0        39571.8        41300.9      0.6      2.0      3.9     21.0
      6s        0        41070.3        41262.5      0.6      2.0      3.9     15.2
      7s        0        41079.3        41236.3      0.6      2.0      4.1     14.7
      8s        0        40496.3        41143.9      0.6      2.0      4.1     19.9
      9s        0        39172.9        40924.8      0.6      2.1      4.1     18.9
     10s        0        40440.8        40876.4      0.6      2.0      3.9     17.8

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)
   10.0s        0         408816        40876.2      0.8      0.6      2.0      3.9     21.0
```

Anecdotally (because I need to re-run the numbers), `--batch=2` shows negligible performance benefit on a 6-node cluster. That too deserves investigation and explanation.

**Comment by petermattis** [comment]
Cc @spencerkimball

**Comment by petermattis** [comment]
@nvanbenschoten Not sure if we have time to do any investigation here in 2.1. Assigning to you for triage.

**Comment by nvanbenschoten** [comment]
We should re-run these numbers with the next 2.1 alpha and see if any have changed. Playing with the batch size on a read-heavy workload is interesting because it allows us to isolate the overhead of SQL statements while holding KV request count constant. One thing I'd also like to explore is whether we see the same performance difference if we send multiple reads together in a single pgwire batch.

**Comment by knz** [comment]
cc @nvanbenschoten for re-triage

**Comment by nvanbenschoten** [comment]
Closing. We now benchmark this regularly with the `kv95/enc=false/nodes=3/batch=16` benchmark.
