### ISSUE TITLE
backup/restore: improved usability work for 1.3

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#18936]
Given that we want to spend more time polishing backup / restore, punting some 1.2 features, and tracking those features here for 1.3.

- [ ] Better handle restoring multiple tables (including multiple tables with FKs)
- [ ] Better handle restoring interleaved tables

cc @mjibson @dt @cuongdo for comments!

**Comment by mjibson** [comment]
LGTM

**Comment by dianasaur323** [comment]
Closing in favor of filing specific issues
