### ISSUE TITLE
distsql: equivalent table with different alias should be read once in TableReader 

### ISSUE THREAD

**Issue by richardwu** [cockroachdb/cockroach#18946]
When I was looking at the DistSQL plan for query 8 of TPC-H
```
SELECT
	o_year,
	SUM(CASE
		WHEN nation = 'CANADA' THEN volume
		ELSE 0
	END) / SUM(volume) AS mkt_share
FROM
	(
		SELECT
			EXTRACT(year FROM o_orderdate) AS o_year,
			l_extendedprice * (1 - l_discount) AS volume,
			n2.n_name AS nation
		FROM
			part,
			supplier,
			lineitem,
			orders,
			customer,
			nation n1,
			nation n2,
			region
		WHERE
			p_partkey = l_partkey
			AND s_suppkey = l_suppkey
			AND l_orderkey = o_orderkey
			AND o_custkey = c_custkey
			AND c_nationkey = n1.n_nationkey
			AND n1.n_regionkey = r_regionkey
			AND r_name = 'AMERICA'
			AND s_nationkey = n2.n_nationkey
			AND o_orderdate BETWEEN DATE '1995-01-01' AND DATE '1996-12-31'
			AND p_type = 'ECONOMY POLISHED STEEL'
	) AS all_nations
GROUP BY
	o_year
ORDER BY
	o_year;
``` 
I noticed that for `nation n1` and `nation n2`, we do [two separate reads via 2 separate `TableReader` processors](https://cockroachdb.github.io/distsqlplan/decode.html?eJzUWO9v4kYQ_d6_wtovJO2eyu7y01KkReA2VAROwKmqKlT58JZYIjZaG-miU_73yibFsR3PZAsNzpcoYJ5n3njmvR1_J0Hoqan7oCJi_0kYoYQTSgRZUbLT4VpFUaiTS4cfjr1vxG5S4ge7fZx8vaJkHWpF7O8k9uOtIjZZul-3aq5cT2lCiadi19-mN99p_8HVj3Ln6phQ8ou_jZW2Ldm2bqyGM5xNZ3d_WJ9nk_Hi1hlZi6XjTBq2bS-W8_H0V0LJbB_blmRUtsnqiZJwHz8nkcX--mjdu9F9Pq5kZPW0oiSK3Y0iNnuiZyQT7Xe7rZ9ePebXMs2PSp5LkZ81xa0fKD9WDy9T5FQKKjtUdk-qpahMNLvPPgi1p7TycndaJUjsJ6-wvXWj-99CPyiS3aq_4yvJrm-0v7lP_zvSPXBtUdmmsktlj8q-IWlOZSffQ626EaeSH7kn6Wb0RUq8k3I3JV6YnHbdWOcf91wFXqIo6lus3XV81XhUrs4kJKkKtWTrxytm2_bIGY7vBpNPsp182aXW9MtkcvhbKNKLAnRMBnMafgp3-bT_zVAyag0HC-f3W2cqxU1jOJgORoMs1WXyPXcmC6eZpepMR9RKlaIiu65JdoPNRquNG4e69MwpGY-c6fK5qosvd1eSH_8T16f1UO-EHjovDZp7HJL_LEV1bfsmtV2EOi52rGQ_Vd6dN99QlNdK8nzXNzVfZfC8IbKP4jasbvLzXm5TA-IXcJsasL6s2yCDeWG3QbKrh9uY9VBt3Aap7Yluwz-K4P_XRMO_Qk-mjzjKcmxWlqdlEjRRC6g4xbBpaYr7axa7fdYns95HcfgA76ZZ7M5ZYwdu7IfBy8jV7d79nyNXi1jvrJG12hwiH19tcOvGagzunPl4OHj9XUZ1bv3K3N7b_nJjXS1a1bJyGb_OjijiOteI0BQwVlsWLMeiBekI4x-ExfNx8TSTr7aJWhwU32svqAHxC-wFNWB92b0Aca0L7wVIdvXYC8x6qDZ7AVLbM76FeuXucxXtwiBSb3rH1EyKpryNOlQ4Cvd6rT7rcJ2GOXycpbh02_FUFB-utg8fxsHhUpLg28GsdQpacBjNQDQSGgYzcQpaMBjNYfQpYIbUDAndhNHCoOLcDFyouCG6UPESumXQ44ZghtCG0YUeL6HbRXTzJbqTAzeL4A4I7sLgLph3D24UGMy6p6AFIkk9kHUfZt0HwQyZD1YStBxcICVniKwgwRFJw9QUCY5Rh5UFGRIEjYkDAsfUgcHigsgDgsb0AYFjAsFK-pLv2DbScrDAMERhWEliTFQCQWMygcAxnWAlmclT7yHUYZ1BpaKkNEazDqPRWUeCI7lzWOY4gyvHS0qTh_eR6KVhz8ORpuOlecvDkabj8LzxDgKH560AL007hy29kHwZDrd8oXRlONzyhQdXhpu0vCmaITqJBW8ix094VcGOvsiahJ19kT0JsTcBOztibwgaszcEjtmbgIddCFhqBDzsooXA4cM7ojQIGrM3BI7Zm4CVRiDOLmClKdnb6umHfwIAAP___azW0Q==) (pan to the top part of node 3). 

An optimization we can do here is to consolidate all the columns we need to read for a given table, then use a mirrored output router to map the correct streams to all their input destinations. This would require some additional logic to ensure the correct streams are being mapped from this consolidated output.

It doesn't seem like we consolidate the table readers [even if the columns read are the same](https://cockroachdb.github.io/distsqlplan/decode.html?eJzUWG-PosgTfv_7FKTf6PyuN0d3g39IJmmj3I2XUTfq5XK5mAsrfQ6JAwYw2clmvvsFmVUBqRpWb8R3CD5U1dNVz9PNN-IHrho7zyoi1l-EEUo4oUSQBSWbMFiqKArC5FH6x6H7lVg6JZ6_2cbJ7QUlyyBUxPpGYi9eK2KRufNlrabKcVVIKHFV7Hjr3cs3offshC9y44QxoeQXbx2r0NKkqd1rDbs_GU9Gf2qfJ4_D2YM90GZz235sWJY1m0-H418JJZNtbGmSUWmSxSslwTZ-S-IQ-8uL9uRET9m4kpHF64KSKHZWiljslV6wmGi72ay93dN9fkbV_KjkmRT5RVNce77yYvV8nCKnUlDZorJ9FpeiNNHDe7Z-ELoqVG7mTYsEif3lRLUPTvT0W-D5-WLX6p-4KdndfeitnnZX-3LTWg0qTSrbVHao7FLJdCoZq1g8T_k66iWjbgRQyfccJOkeaBA7AlrfOfghAnKTZNat-uzyT5XvJgqjvsahs4ybjRflhAdJobJ1RzVp_L_JLMsa2P3hqPf4SZrJzQ7VZJtqspsj6Kj4VpUhHQefgk025e_ZSUa1fm9m__Fgj6W4b_R7496gd0hzntzn9uPM1g9p2uMBTTpbkwbVCoJ4lGW7Spa91SpUKycOwsK6UzIc2OP5G7Oz30dNyfdXIrkaDcdNaeyvzLvzeqtzRm_996XRzPJJ_rMU-Fp0q6zFLAjjfJdL9lPp27n-DsJO0fX21nc1bWnwrKmyW3EsVjfJ-mjHqgEBV3SsGlR_PcdChrQmjoVkWV_HqtZbN-FYyFqc6Vj8VkzjRxMN_g5cuVv-6JCjXkqPUSVoojAQOfmwO2rKF9686Most1EcPMNn5EPs1kVj-07sBX6-J0qDt68ZvHPR4KFapcH3H1q4dq81eiN7Ouz3Tn9Z4aW5dUtz-2jjzA13eSOxcn25jtmLvdkbd7mmSPd6rfJaWM1q4af2rWxfSFFxj2rhN1JLZv953t6g3EFqse_86GNHDQi44rGjBtVf79iB2FpNjh1IlvU9dlTrrZs4diBrccEPZSfePlXRJvAj9a7PYHpCqHJXKmU_CrbhUn0Og-UuTPpzssPtDlOuiuL0qZn-GPrpoyTB94OZcQ5acBjNQDQSGgYzcQ5aMBjNYfQ5YIZwhoTWYbSowDivBs4xXhGdY7yANir0eEUwQ8qG0bkeL6DNPFo_RrcyYD0PboHgNgxug3l34EaBwax9DlogktQBq-7CVXdBMEPmgxUELQMXCOUMkRUkOCJpmJoiwbHSYWVBhgRBY-KAwDF1YLC4IPKAoDF9QOCYQLCCvmQ71kRaDhYYhigMK0hMFZVA0JhMIHBMJ1hBZrKld5DSYZ1BpaKgNJVmHUajs44ER3LnsMxxBjPHC0qThXeR6IVhz8KRpuOFecvCkabj8LzxFgKH5y0HL0w7hy09l3wRDrd8jroiHG753MIV4VVaviqaITqJBdeR7Sd8VMG2vsgxCdv7IuckxN4E7OyIvSFozN4QOGZvAh52IWCpEfCwCwOBw5t3RGkQNGZvCByzNwErjUCcXcBKU7C3xev__g0AAP__zA4D2w==), for example in the given query where `nation` columns `@1, @2, @3` are read for both
```
SELECT
	o_year,
	SUM(CASE
		WHEN nation = 'CANADA' THEN volume
		ELSE 0
	END) / SUM(volume) AS mkt_share,
	MIN(n1name),
	MIN(n2region)
FROM
	(
		SELECT
			EXTRACT(year FROM o_orderdate) AS o_year,
			l_extendedprice * (1 - l_discount) AS volume,
			n2.n_name AS nation,
			n1.n_name AS n1name,
			n2.n_regionkey AS n2region
		FROM
			part,
			supplier,
			lineitem,
			orders,
			customer,
			nation n1,
			nation n2,
			region
		WHERE
			p_partkey = l_partkey
			AND s_suppkey = l_suppkey
			AND l_orderkey = o_orderkey
			AND o_custkey = c_custkey
			AND c_nationkey = n1.n_nationkey
			AND n1.n_regionkey = r_regionkey
			AND r_name = 'AMERICA'
			AND s_nationkey = n2.n_nationkey
			AND o_orderdate BETWEEN DATE '1995-01-01' AND DATE '1996-12-31'
			AND p_type = 'ECONOMY POLISHED STEEL'
	) AS all_nations
GROUP BY
	o_year
ORDER BY
	o_year;
```

cc: @arjunravinarayan @RaduBerinde #

Jira issue: CRDB-5988

**Comment by arjunravinarayan** [comment]
It's tricky to do this in a principled fashion (or perhaps there is a solution that I don't see) but the main problem in mirroring outputs is that if the readers don't consume the rows in tandem, then you have to buffer the outputs. If you mirror outputs but don't add the ability for outputs to buffer if one reader is far ahead of another, you can potentially get into a deadlocked scenario (see #17097). It's not clear to me when we can statically determine that consumers *will* read in lockstep, and thus there will never be the need to buffer rows if you use a single `TableReader` and mirror the outputs.

Do you have any thoughts on when we can make this determination and thus safely make this optimization?

**Comment by jordanlewis** [comment]
@RaduBerinde / @justinj  could you PTAL and triage or close? Thanks!

**Comment by RaduBerinde** [comment]
Might be worth thinking about a rule where we transform two scans of the same table into a CTE (when we'll have `With`). CC @justinj
