### ISSUE TITLE
sql: COPY queries aren't accounting their stats

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#18945]
A user reported COPY not showing up in any connection or sql byte traffic in the admin UI.

cc @jordanlewis

**Comment by dianasaur323** [comment]
@mjibson I had originally put this in the admin UI bug list, but after discussing with @cuongdo, sounds like we are moving this bug into bulk-io. Do you still think this should sit in 1.3?

**Comment by mjibson** [comment]
I'm surprised this is in bulkio. I think it belongs in SQL. But wherever it goes, I think it's worth doing for 1.2 because I think it will be a small change and it is fairly important for user visibility.

**Comment by cuongdo** [comment]
assigning to @vivekmenezes for triage

**Comment by dianasaur323** [comment]
ok, moving off our plate (woohoo!) and assigning to 1.2.

**Comment by mjibson** [comment]
FWIW I just hit this on my side project and it's really annoying.

**Comment by dianasaur323** [comment]
@vivekmenezes do we still want to do this by 2.0? cc @awoods187

**Comment by andreimatei** [comment]
I'm about to attempt to rewrite our COPY IN support. If someone knows what metrics exactly we want to contribute to, I can probably make sure it does.

**Comment by vivekmenezes** [comment]
@andreimatei not familiar with COPY but these should be the same stats we report on all the other queries.

**Comment by jordanlewis** [comment]
@andreimatei, could you please provide an update on where we are here after your conn_executor rewrite?

**Comment by andreimatei** [comment]
I don't know for sure. I'm pretty sure the bytes counters should work, and I'm not sure what other stats are relevant. I'll check. In any case, the 2.0 milestone can go away; this is not a particularly big deal.

**Comment by andreimatei** [comment]
It's time for this issue to go away since it's not very clear what it's talking about. Hopefully it's been all fixed since.
