### ISSUE TITLE
acceptance: refactor TestDocker.*ReferenceVersion

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#18960]
These two tests are currently somewhat hacky and not very useful any more now that we have real migrations and also more sophisticated load generators.

What I would like to do here is

- remove these tests
- add library functionality to some of our load gens (i.e. provide an entry point I can call from the acceptance test runner instead of firing up the binary as a subprocess -- not difficult):
   - something bank-like (`zerosum`)
   - kv (with splits!)
   - tpc{c,h}
   - perhaps `allocsim`
- vendor these load generators (do we expect import cycles? Presumably not except for the old generators that I wouldn't wanna touch anyway)
- add new tests that stand up a reference version cluster,
- have the load generators (perhaps in parallel) against the reference version cluster
- after (say) 500 ops (each generator):
- run repeated sanity checks
  - bank: compare sum
  - tpc{c,h}/kv: run some COUNT(*), ...)
  - no problem ranges/no underreplication
- while upgrading the cluster (perhaps repeatedly, until reaching the new version):
  - rolling update & stay until loadgens have run 500ops each
  - rolling downgrade (because that shouldn't break things) & stay until loadgens have run 500 ops each
  - `SET CLUSTER VERSION` & stay until loadgens have run 500 ops each
- run the load for (say) 10s longer
- run sanity checks again
- declare success (hopefully).

These tests likely would've caught #18834 #18950 #18835.

Any thoughts on the above?

**Comment by petermattis** [comment]
This sounds great, though I bet you could start with a single load generator and get most of the benefit. Especially something like `zerosum` which provides an easy verification step.

**Comment by tschottdorf** [comment]
@mjibson @cuongdo mentioned that bulk i/o also had an interest in mixed-version testing. It's not inconceivable that we could do some of that in localcluster-acceptance testing (small backup-restores across different versions to test compatibility for example). Curious to hear what you had in mind.

**Comment by mjibson** [comment]
We'd like to do a full and incremental backup of some data on 1.0 and a restore on 1.1.

**Comment by tschottdorf** [comment]
Won't happen for 2.0.

**Comment by tschottdorf** [comment]
It has been deleted 💛
