### ISSUE TITLE
ui: don't ask safari for client certs in secure mode 

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#18961]
When running a secure cluster, attempting to access the UI in Safari on an OS X host that is auth'ed to iCloud pauses before page load with a browser dialog to select from available client certificates. The list contains a single cert that appears to be related to OSX's iCloud integration. Clicking cancel leads to the expected untrusted cert warnings, but the client cert picker reappears again on page loads, and even periodically even after the UI is loaded.

If you accidentally click accept rather than cancel and attempt to use the iCloud cert, it turns in to whack-a-mole keychain signing request dialog boxes.

Since the UI isn't sharing the gRPC port, and we're doing our own password/session driven auth, it seems like we should just disable client certs so safari doesn't try to get in the way.

**Comment by dt** [comment]
cc @bdarnell @benesch

**Comment by couchand** [comment]
cc @mberhault

**Comment by mberhault** [comment]
This shouldn't be too hard, we just need to craft a separate TLS config using the same certificate, but with `ClientAuth = NoClientCert` instead of `VerifyClientCertIfGiven`. I can take this one.
Not sure this is critical enough to be 1.1 though, setting to 1.2.

**Comment by couchand** [comment]
@mberhault have you had a chance to look into this?  @dt is this still an issue?

**Comment by benesch** [comment]
Yeah, it's still an issue. :(

**Comment by dt** [comment]
huh, i'm not sure what I changed (maybe high sierra?) but I don't get it anymore. it _does_ ask about remembering exceptions in keychain now, so maybe it's a pref i changed.

**Comment by benesch** [comment]
Huh, It also disappeared after I upgraded High Sierra. But my home laptop
still runs Sierra and it's definitely still happening there.

**Comment by dt** [comment]
I'm fine closing this if it doesn't repro on current safari/macOS.
