### ISSUE TITLE
kv: reconsider RangeDescriptorCache eviction policy

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#18988]
See https://github.com/cockroachdb/cockroach/pull/18709#issuecomment-331725580.

At the moment, when we [evict a `RangeDescriptor`](https://github.com/cockroachdb/cockroach/blob/a07fe20c2bb29210a446bafd6a942b258ad9e4db/pkg/kv/range_cache.go#L428) from the `RangeDescriptorCache`, we evict all meta descriptors that point to that descriptor as well. For instance, if we evict a descriptor with the `EndKey` `"m"`, we'll also evict the descriptors with keys `"/meta2/m"` and `"/meta1/m"`. 

This is expensive but has justifications. We currently only do inconsistent RangeLookups for the `RangeDescriptorCache`. This means that if we find a descriptor that's stale, we don't know where the staleness came from. If we moved away from inconsistent RangeLookup scans, we'd be able to evict one meta level at a time instead of eagerly evicting multiple levels because we're not sure where we got bad information.

#18970 will play nicely into this because it now sends `RangeLookup` scans through `DistSender`.
This means that `RangeDescriptorCache` and `DistSender` mutual recurse as they perform `RangeLookup` scans which continue to miss the cache for the descriptor required to perform the scans. This mutual recursion means that we can let `DistSender` evict a single descriptor (meta or otherwise) at the exact point where the descriptor is found to be stale. The analogy to this approach in the current code would be to use the `evictionToken` returned [here](https://github.com/cockroachdb/cockroach/blob/a07fe20c2bb29210a446bafd6a942b258ad9e4db/pkg/kv/range_cache.go#L417) when the `RangeLookup` below indicates that the descriptor used for the `RangeLookup` was stale, but this is not as straightforward and doesn't take advantage of the logic already existing in `DistSender`.

This may actually work even with inconsistent range lookup scans. I'm not sure if it's possible for a range lookup scan on a stale meta2 descriptor to return a stale user-space descriptor instead of catching the staleness, in which case we'd continue to evict the user-space descriptor indefinitely. @bdarnell any insight into this?

**Comment by bdarnell** [comment]
Inconsistent range lookups can be arbitrarily far behind without reporting any problems - the only time an inconsistent range lookup is expected to return an error due to staleness is when it's sent to a replica that has been GC'd. But it may be OK anyway because of the way we alternate consistent and inconsistent lookups (assuming that still works - the current aggressive eviction means we're not relying on it and may not be testing it well)

**Comment by bdarnell** [comment]
#26608 has found significant performance problems related to range descriptor cache invalidations, so this is increasing in priority. There are a number of issues here, but the most fundamental one is that *invalidating* the cache (and stalling all requests to that range) is a blunt instrument and should only be used when we are reasonably certain that our cached range descriptor is outdated to the point of uselessness.

Currently, we keep using a stale descriptor as long as it contains the leaseholder, and when the leaseholder moves outside of our current replica set, we invalidate and block. Single-replica errors are (mostly) ignored as long as the leaseholder is found, even though this serves as a signal that our descriptor is out of date. We should trigger an asynchronous refresh of the descriptor in this case.

Additionally, every time we complete a request on the leaseholder, that leaseholder knows the current range descriptor. We could exchange range descriptor versions on every request to serve as an additional refresh trigger. 

One reason we use our current blunt eviction logic is that this is how we flip between the committed and intent versions of the descriptor. I think we could avoid this by combining the two versions (when two exist): use the smaller of the two EndKeys and the union of the replica sets. I think that's all we need for the DistSender, although I haven't confirmed this.

**Comment by a-robinson** [comment]
> Currently, we keep using a stale descriptor as long as it contains the leaseholder, and when the leaseholder moves outside of our current replica set, we invalidate and block.

I know you realize this since you commented about it (https://github.com/cockroachdb/cockroach/pull/26608#issuecomment-397970589), but just to clarify for anyone else reading and to make sure the bug doesn't get lost: this is how we want it to work, but currently we'll also evict a descriptor if the replica that we think is leaseholder has been removed from the range, even if the new leaseholder is in our cached descriptor.

**Comment by bdarnell** [comment]
Right. What I meant is that we could hold a stale range descriptor longer than we should:

1. Range has replicas on A, B, C. Lease is held by A
1. Replica C is moved to D
1. Lease is moved from A to D

With a lazy/async refresh, we could have updated our cache after step 2 and be ready for the move in step 3, but currently we hold onto the original A,B,C descriptor.
