### ISSUE TITLE
removing InternalBatch

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#1899]
With the decision for SQL, it seems that we won't have external KV clients at all and thus, all our KV protos are internal.
It would make sense to unite `InternalBatch` and `Batch`, which currently makes for some awkward conversions.
We could also consider stripping the other `Internal*` methods of their prefix, though I don't have a strong opinion on that.

**Comment by petermattis** [comment]
This is fine by me (including stripping all of the `Internal` prefixes), though others working closer to that code should chime in as well.

**Comment by spencerkimball** [comment]
:+1:

**Comment by tamird** [comment]
If we remove all the `Internal*` we should also get unite `RequestUnion` + `InternalRequestUnion` and `ResponseUnion` + `InternalResponseUnion` + **`ReadWriteCmdResponse`**
