### ISSUE TITLE
acceptance: failure in sqlalchemy test due to retry error

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#19019]
Found in:
https://teamcity.cockroachdb.com/viewLog.html?tab=buildLog&buildTypeId=Cockroach_ExampleORMs&buildId=368595

```
[Step 2/2] Traceback (most recent call last)
[...]
[Step 2/2] sqlalchemy.exc.OperationalError: (psycopg2.extensions.TransactionRollbackError) restart transaction: HandledRetryableTxnError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE): "sql txn" id=3a9084f0 key=/Table/SystemConfigSpan/Start rw=true pri=0.03555282 iso=SERIALIZABLE stat=PENDING epo=0 ts=1507108623.460698685,1 orig=1507108623.452700367,0 max=1507108623.452700367,0 wto=false rop=false seq=17
```

**Comment by sibblegp** [comment]
Does anyone know what causes this error?

**Comment by raevangregson** [comment]
Using flask with sqlAlchemy and cockroach db we randomly get this error it seems when doing POST or PUTS into the database.

Any suggestions or help is appreciated.

**Comment by andreimatei** [comment]
@sibblegp @raevangregson this issue is about a particular test failure.
Retriable errors are generally a thing in cockroach db - see https://www.cockroachlabs.com/docs/stable/transactions.html#transaction-retries

**Comment by andreimatei** [comment]
@jordanlewis for triage

**Comment by andreimatei** [comment]
related? #16715

**Comment by jordanlewis** [comment]
Closing this for #16715.
