### ISSUE TITLE
Habitat plan

### ISSUE THREAD

**Issue by themightychris** [cockroachdb/cockroach#19030]
I just contributed a habitat build plan for cockroach: https://github.com/habitat-sh/core-plans/pull/834

It only builds and packages the binaries right now, I haven't yet put any work into creating service hooks that would enable habitat to configure and supervise a running daemon. Not sure if an issue is the best way to share but I did a search here for habitat first. Habitat is a good way to provide consistent builds and minimal docker containers, check it out! If there's interest I'd be happy to contribute a PR to this repo that adds a git-based build

**Comment by a-robinson** [comment]
Nice work, @themightychris! If you'd like to share it more widely, our [forum](https://forum.cockroachlabs.com/) and [Gitter channel](https://gitter.im/cockroachdb/cockroach) would be good places to do so. Or Twitter, of course :)

What would be involved in the git-based build? We're generally a little wary about maintaining additional methods of building given how much work can be involved in maintaining each of them.

**Comment by themightychris** [comment]
@a-robinson either a habitat directory containing `plan.sh` could be merged into the application's main repo, so you could just check out any version and run `hab pkg build .` within the main repo directory. They key difference between that plan and the one I made already would be that it would dynamically determine the version number via git ([example](https://github.com/PublicMapping/DistrictBuilder/pull/453/files)) rather than having one declared and using that to fetch a release archive

Or, a plan could be kept in a separate repo where a branch/ref is either a config option in `plan.sh` or a submodule adjacent to it points to a commit like you see here. This plan would, in addition to dynamically determining the version string like above, also handle pulling and cleaning a working directory to run the build in ([example](https://github.com/CodeForPhilly/ops/pull/27/files#diff-6df74aa0ea05d3317aa3945392df13d2))

The habitat build plan would be the easiest of all to maintain, and can replace your existing docker build process. It's basically just a bash script with the key build workflow commands and a granular list of dependent packages. You'd only ever need to update it to add a new dependency or make a dependency version more specific. Habitat simplifies things so much by eliminating the concept of a "base system", the app instead becomes the center of the world and it gets built and run in an isolated context that only includes exactly the environmental code specified. There is no base docker image or base operating system full of code you run on top of and have to constantly adapt to stay in sync with and worry about the evolving state of.

Once a habitat build or plan works it works exactly the same forever. A build can be installed on bare metal, in a VM, or exported to a minimal container image.

**Comment by mjibson** [comment]
Thanks for that description. I don't think we're going to add it to our repo yet, though, for the reasons described above.

**Comment by themightychris** [comment]
@mjibson only the plan I originally linked to that builds from a designated release archive will possibly get merged into habitat's `core-plans` repository. If I create a git-based plan for developers that can be run from a sep repo and pointed at a branch/commit via config or submodule, could I contribute it to a repo under your org called `cockroach-habitat` or something? Happy to just post to by own github if there's too much friction there, I just want to put it wherever anyone else who might find it useful is likely to find it in the future.

**Comment by mjibson** [comment]
I think using your own repo is the best choice here. We don't want to have repos under our organization that we don't actively maintain or test, and we don't have the resources to do that right now for habitat.

**Comment by themightychris** [comment]
I'm usually not a fan of using forks as a mean of "syndication" but is that worth considering? It shouldn't really need updates frequently

**Comment by mjibson** [comment]
No, sorry, I think a fork implies the same level of commitment, so that's not going to work for us either.

**Comment by jordanlewis** [comment]
Thanks for the contribution but we don't have the resources for this at the moment.
