### ISSUE TITLE
sql: clarify why explain delete showing secondary index instead of primary 

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/cockroach#19037]
**BUG REPORT**

1. Please supply the header (i.e. the first few lines) of your most recent
   log file **for each node in your cluster**. On most unix-based systems
   running with defaults, this boils down to the output of

cockroach version
Build Tag:    v1.1-beta.20170921
Build Time:   2017/09/21 15:46:53
Distribution: CCL
Platform:     darwin amd64
Go Version:   go1.8.3
C Compiler:   4.2.1 Compatible Clang 3.8.0 (tags/RELEASE_380/final)
Build SHA-1:  be60cc5a4ccfb6a597a47f5eb9d0a88a0e1b1289
Build Type:   release

2. Please describe the issue you observed:

- What did you do?

```
CREATE TABLE t1 (
                    f1 VARCHAR(64) NOT NULL,
                    f2 VARCHAR(64) NOT NULL,
                    f3 TIMESTAMP NOT NULL,
                    CONSTRAINT "primary" PRIMARY KEY (f1)
                    ,INDEX uuid (f1)
              );
```
- What did you expect to see?

Using primary key instead of the secondary key 

- What did you see instead?

Select and update show use of primary key, but update is using secondary index

```
EXPLAIN select * FROM t1 WHERE f1 = '1';
+-------+------+-------+---------------+
| Level | Type | Field |  Description  |
+-------+------+-------+---------------+
|     0 | scan |       |               |
|     0 |      | table | t1@primary    |
|     0 |      | spans | /"1"-/"1\x00" |
+-------+------+-------+---------------+
(3 rows)

EXPLAIN update t1 set f2 = '1' WHERE f1 = '1';
+-------+--------+-------+---------------+
| Level |  Type  | Field |  Description  |
+-------+--------+-------+---------------+
|     0 | update |       |               |
|     0 |        | table | t1            |
|     0 |        | set   | f2            |
|     1 | render |       |               |
|     2 | scan   |       |               |
|     2 |        | table | t1@primary    |
|     2 |        | spans | /"1"-/"1\x00" |
+-------+--------+-------+---------------+
(7 rows)

EXPLAIN DELETE FROM t1 WHERE f1 = '1';
+-------+--------+-------+---------------+
| Level |  Type  | Field |  Description  |
+-------+--------+-------+---------------+
|     0 | delete |       |               |
|     0 |        | from  | t1            |
|     1 | render |       |               |
|     2 | scan   |       |               |
|     2 |        | table | t1@uuid       |
|     2 |        | spans | /"1"-/"1\x00" |
+-------+--------+-------+---------------+
(6 rows)
```

**Comment by jordanlewis** [comment]
Hmm this might be a confusing output, but it's not strictly a bug I don't think. The secondary index only has field `f1` available, so it's not selected in the first 2 queries that require both `f2` and `f1`. The final query only requires `f1`, so it's a valid choice to pick the secondary index. If you changed the query to say `EXPLAIN DELETE FROM t1 WHERE f1 = '1' AND f2='1'` the output would show the primary index.

And of course the delete has to touch both indexes in the end anyway.
