### ISSUE TITLE
sql: regexp_replace backreference escapes

### ISSUE THREAD

**Issue by hexasoftware** [cockroachdb/cockroach#19046]
**BUG REPORT**

1. cockroach version (git latest)
Build Tag:    v1.2-alpha.20170901-617-g5e8f3a6fe
Build Time:   2017/10/04 23:00:46
Distribution: CCL
Platform:     linux amd64
Go Version:   go1.9
C Compiler:   gcc 7.2.0
Build SHA-1:  5e8f3a6fe180e7c697635be06ebbb0bd7159b697
Build Type:   development

2. Please describe the issue you observed:
the builtin function regexp_replace does not properly escape the back references

- What did you do?
`select regexp_replace('ReRe','R(e)','1\\1','g');`
- What did you expect to see? 
`1\11\1`
- What did you see instead?
`1\e1\e`

**Comment by mjibson** [comment]
Thanks for this report. Assigning for triage.
