### ISSUE TITLE
sql: INSERT only needs CPut on the first non-null column

### ISSUE THREAD

**Issue by XisiHuang** [cockroachdb/cockroach#1905]
because we have known the primary key is legal if  insert the first column(portion of the primart key) success.

**Comment by petermattis** [comment]
Which `CPut()` are you wanting to remove? We use `CPut()` for the primary key in order to get an error if the row already exists. If we used `Put()` the `INSERT` would blindly overwrite whatever was there.

**Comment by tamird** [comment]
I think the suggestion is that we not use CPut for anything other than the columns making up the primary key? Doesn't seem worth it to me.

**Comment by XisiHuang** [comment]
since all the columns' key of a row is starting with the same prefix, eg, the table id + the primary key value.
so we need only use CPut for the first column. Then we can be sure if the row exist or not.
Put is much effective than CPut, So I think it might be worth it.

**Comment by petermattis** [comment]
Ah, got it. You're correct that we only need `CPut` on the first column, though we have to be careful in case that first column is nullable in which case it may not contain an entry. A related optimization: currently we output a key/value pair for each column that is part of the primary key. We could instead output only a single key/value pair, or no key/value pairs at all if another non-nullable column exists.

**Comment by spencerkimball** [comment]
I believe that F1 always stores a sentinel value for every row to avoid the
all-null columns problem. I couldn't locate the citation for that however.
