### ISSUE TITLE
backup/restore: restore databases

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#19055]
Currently RESTORE does not create databases, it only creates tables in existing databases.

Assuming you run `BACKUP DATABASE foo TO 'path/to/foo.backup'` and then want to restore it:

1. If you run `RESTORE DATABASE foo FROM 'path/to/foo.backup'`, we fail saying unsupported. The error suggests trying `RESTORE foo.*` instead.

2. If you run `RESTORE foo.* FROM 'path/to/foo.backup'`, we attempt to restore each table in the backup that had the parent named "foo" when it was backed up, restoring into this cluster's database named "foo". We fail if this cluster does not currently have an existing database named "foo".

3. If you run `RESTORE foo.bar FROM 'path/to/foo.backup'`, we attempt to restore the table `bar` in the backup which has a parent named `foo`, into this cluster's database named "foo". We fail if this cluster does not currently have an existing database named "foo".

However it seems less than ideal that the simplest use case -- `BACKUP DATABASE foo` followed by `RESTORE DATABASE foo` doesn't just work out of the box, but instead asks you to go re-create databases by hand, even though you backed them up.

I think we should make 1 "just work", and there's potentially room for 2 and 3 to be a little friendlier too.

**Comment by dt** [comment]
For case 1), it seems like the most straightforward semantics would be to a) require that the database `foo` does NOT exist and b) then create it from the backed up database descriptor before c) proceeding into essentially case 2).

For cases 2) and 3), we could just leave them as-is, but it might be friendlier if they also learned to create databases for you, though it is slightly less obvious that they need to do so than in case 1). 
As a straw man: when restoring a table with a parent db of `foo`, if db `foo` already exists, the table is restored into it, otherwise a new db `foo` is created from the backed up descriptor. When restoring into an existing DB, if a table already exists with the same name and error is returned.

**Comment by dt** [comment]
CC @dianasaur323 @mjibson (and @danhhz) for thoughts on what semantics we want here.

**Comment by danhhz** [comment]
> For case 1), it seems like the most straightforward semantics would be to a) require that the database foo does NOT exist and then b) create it from the backed up database descriptor

I agree this is a clear and obvious win

> For cases 2) and 3), we could just leave them as-is, but it might be friendlier if they also learned to create databases for you

The semantics of this are really hard. Some part of me expects it to work like `CREATE TABLE` and use the session database, but some other part of me thinks the database it was in when backed up should be relevant. I'm personally okay with not doing anything here until we get complaints about it

**Comment by dianasaur323** [comment]
Agreed with @danhhz. I think case 1 seems to be the one we should address. One thought though is, if you were running this in production, you might want to not have the application experience downtime, correct? So in this case, wouldn't it be better for us to keep the foo database, import with foo_new, and then do a swap? Perhaps I'm coming from an uninformed perspective.

**Comment by dt** [comment]
This is done.
