### ISSUE TITLE
ui: combine jobs table and event log

### ISSUE THREAD

**Issue by kuanluo** [cockroachdb/cockroach#19071]
While discussing #13378, @couchand mentioned that we should have only 1 event log for all types of events: jobs, schema changes, etc. UX-wise, it makes a lot of sense, and will help consolidate single jobs tables into one useful log. 

cc: @dianasaur323 @vivekmenezes @mrtracy @vilterp @cuongdo @josueeee

**Comment by cuongdo** [comment]
+1 on this. Basically, we'd have a unified log for all cluster events.

**Comment by dianasaur323** [comment]
Based on the specs we've written out in the events on graphs issue, I believe we do actually surface jobs already (or we will once we implement it). Did I misunderstand this issue?

**Comment by kuanluo** [comment]
@dianasaur323 This issue aims to combine the current "jobs" table as well as the full event logs page, since they're all jobs surfaced in the event log. Does that make sense?

**Comment by dianasaur323** [comment]
@kuanluo ah, I know where the communication gap is - I just assumed that all the events showing on the events on graphs would also be persisted into the event log. Could we actually port the commenting over to this issue? https://github.com/cockroachdb/cockroach/issues/17717

**Comment by kuanluo** [comment]
@dianasaur323 Heh, we still aren't talking about the same things here. This issue is for pages like the Jobs table, or schema change table in the future. Instead of adding new full pages with icon in the global left nav, we should combine all those pages into a better full events page. We can sync offline to make sure we're on the same page. #13378 will address #17717.

**Comment by vivekmenezes** [comment]
FYI we still need to maintain a jobs table to manage the state of a job and coordinator lease for the job. So the jobs table is not going to go away. We already have an events log that stores schema change events/node up/down events.

**Comment by kuanluo** [comment]
@vivekmenezes Don't worry - the jobs table is not going away. :) The current thinking from the team is that there might be **a better place** for its functionalities that would make more sense.

**Comment by dianasaur323** [comment]
@kuanluo and I synced up offline. Basically, this involves wrapping job tables info and event log info into a more seamless user experience, since they are both considered cluster events in the grand scheme of things. Not in scope for 1.2 for now.

**Comment by jordanlewis** [comment]
Closing due to age.
