### ISSUE TITLE
release: v1.1.0-rc2

### ISSUE THREAD

**Issue by richardwu** [cockroachdb/cockroach#19074]
Candidate SHA: XXX EDIT ME XXX.
Deployment status: XXX EDIT ME XXX.

[Release process checklist](https://github.com/cockroachdb/cockroach/wiki/Release-Process)

Prep date: `2017-10-05`
- [ ] [Pick a sha](https://github.com/cockroachdb/cockroach/wiki/Release-Process#pick-sha), fill in `Candidate SHA` above.
- [ ] [Deploy to test clusters](https://github.com/cockroachdb/cockroach/wiki/Release-Process#deploy-to-test-clusters)
- [ ] fill in `Deployment status` above
- Keep an eye on clusters until release date.

Release date: `2017-10-12`
- [ ] [Check cluster status](https://github.com/cockroachdb/cockroach/wiki/Release-Process#check-cluster)
- [ ] [Tag release](https://github.com/cockroachdb/cockroach/wiki/Release-Process#tag-release)
- [ ] [Trigger release build](https://github.com/cockroachdb/cockroach/wiki/Release-Process#trigger-build)
- [ ] [Check binaries](https://github.com/cockroachdb/cockroach/wiki/Release-Process#check-binaries)
- [ ] Update docs
- [ ] External communications for release
- [ ] File issue for next release and assign to release coordinator

**Comment by mberhault** [comment]
FYI: this need to be deployed today. The sha is (probably) 583badd0d5ff91e49fb9ad3ba83617828b2f5d9c and we should build and tag a bit early (Monday or so), with the goal of having a 1.1 that's just a re-tag of a RC.
@bdarnell, @mjibson: do we want the two latest cherrypicks in? One's a `repeat` panic, the other dropped tables on backup.

**Comment by richardwu** [comment]
As determined by consensus, the commits since `rc1` in `release-v1.1` will be patched in `v1.1.1`. No release until `1.1`.
