### ISSUE TITLE
Foreign keys defined on columns with a primary index cannot be dropped

### ISSUE THREAD

**Issue by AlistairDoswald** [cockroachdb/cockroach#19084]
**BUG REPORT**
This is a bug report. I've tested this issue on the following releases: 1.0.6, v1.1-beta.20170921 and v1.1.0-rc.1

## The header (i.e. the first few lines) of your most recent log files
**node 1:**
I171006 11:31:24.274915 1 util/log/clog.go:983  [config] file created at: 2017/10/06 11:31:24
I171006 11:31:24.274915 1 util/log/clog.go:983  [config] running on machine: ADDCloudTrustVM
I171006 11:31:24.274915 1 util/log/clog.go:983  [config] binary: CockroachDB CCL v1.1-beta.20170921 (linux amd64, built 2017/09/28 15:33:39, go1.8.3)
I171006 11:31:24.274915 1 util/log/clog.go:983  [config] arguments: [cockroach start --host=localhost --insecure]
**node 2:**
I171006 11:31:29.752979 1 util/log/clog.go:983  [config] file created at: 2017/10/06 11:31:29
I171006 11:31:29.752979 1 util/log/clog.go:983  [config] running on machine: ADDCloudTrustVM
I171006 11:31:29.752979 1 util/log/clog.go:983  [config] binary: CockroachDB CCL v1.1-beta.20170921 (linux amd64, built 2017/09/28 15:33:39, go1.8.3)
I171006 11:31:29.752979 1 util/log/clog.go:983  [config] arguments: [cockroach start --host=localhost --port=26258 --http-port=8081 --insecure --store=node2 --join localhost:26257]

### What I did:
From a new installation:
_step 1: tables creation._

create database keycloak;

CREATE TABLE keycloak.client (
	id STRING(36) NOT NULL,
	enabled BOOL NOT NULL DEFAULT false,
	full_scope_allowed BOOL NOT NULL DEFAULT false,
	client_id STRING(255) NULL,
	not_before INT NULL,
	public_client BOOL NOT NULL DEFAULT false,
	secret STRING(255) NULL,
	base_url STRING(255) NULL,
	bearer_only BOOL NOT NULL DEFAULT false,
	management_url STRING(255) NULL,
	surrogate_auth_required BOOL NOT NULL DEFAULT false,
	direct_grants_only BOOL NOT NULL DEFAULT false,
	realm_id STRING(36) NULL,
	protocol STRING(255) NULL,
	node_rereg_timeout INT NULL DEFAULT 0:::INT,
	frontchannel_logout BOOL NOT NULL DEFAULT false,
	consent_required BOOL NOT NULL DEFAULT false,
	"name" STRING(255) NULL,
	CONSTRAINT constraint_7 PRIMARY KEY (id ASC),
	UNIQUE INDEX uk_b71cjlbenv945rb6gcon438at (realm_id ASC, client_id ASC),
	INDEX fk_p56ctinxxb9gsk57fo49f9tac (realm_id ASC),
	FAMILY "primary" (id, enabled, full_scope_allowed, client_id, not_before, public_client, secret, base_url, bearer_only, management_url, surrogate_auth_required, direct_grants_only, realm_id, protocol, node_rereg_timeout, frontchannel_logout, consent_required, "name")
);

CREATE TABLE keycloak.client_node_registrations (
	client_id STRING(36) NOT NULL,
	value INT NULL,
	"name" STRING(255) NOT NULL,
	CONSTRAINT constraint_84 PRIMARY KEY (client_id ASC, "name" ASC),
	CONSTRAINT fk8454723ba992f594 FOREIGN KEY (client_id) REFERENCES keycloak.client (id),
	FAMILY "primary" (client_id, value, "name")
) ;

_step 2: attempt to drop foreign key._

**SHOW CONSTRAINTS FROM keycloak.client_node_registrations;**
+---------------------------+--------------------+-------------+-----------------+-------------+
|           Table           |        Name        |    Type     |    Column(s)    |   Details   |
+---------------------------+--------------------+-------------+-----------------+-------------+
| client_node_registrations | constraint_84      | PRIMARY KEY | client_id, name | NULL        |
| client_node_registrations | fk8454723ba992f594 | FOREIGN KEY | client_id       | client.[id] |
+---------------------------+--------------------+-------------+-----------------+-------------+

**alter table keycloak.client_node_registrations drop constraint fk8454723ba992f594;**
ALTER TABLE

**SHOW CONSTRAINTS FROM keycloak.client_node_registrations;**
+---------------------------+--------------------+-------------+-----------------+-------------+
|           Table           |        Name        |    Type     |    Column(s)    |   Details   |
+---------------------------+--------------------+-------------+-----------------+-------------+
| client_node_registrations | constraint_84      | PRIMARY KEY | client_id, name | NULL        |
| client_node_registrations | fk8454723ba992f594 | FOREIGN KEY | client_id       | client.[id] |
+---------------------------+--------------------+-------------+-----------------+-------------+

### What I expect to see
The foreign key should be dropped. 

### What I saw instead
The foreign key is not dropped. It can be seen with SHOW CONSTRAINTS or SHOW CREATE TABLE, and trying to create a new foreign key on the column returns a message that a foreign key already exists.

Further testing showed that the case only happens when the foreign key is defined on a column with a primary index. The method does not matter (created with the table or added after).

**Comment by dt** [comment]
Thanks for the detailed and clear report! I'll look at this today and see what's happening.
