### ISSUE TITLE
sql: unique indexes need to allow multiple NULL rows

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#1909]
In SQL `NULL != NULL`, which means a **unique** index must allow multiple `NULL`s. Our current secondary index encoding doesn't allow this. See #1886.

**Comment by petermattis** [comment]
I seem to recall that MySQL or Postgres or somebody doesn't allow the columns of a unique index (including the primary key) to be NULL.

**Comment by tamird** [comment]
I think that's just the primary key, which has an implicit not null
constraint.

**Comment by tamird** [comment]
Confirmed in #2013 that Postgres does allow NULL (multiple NULLs, at that) in a unique index.

**Comment by petermattis** [comment]
That's interesting. I just confirmed the postgres behavior as well. Sort of surprising, but then not surprising as it follows logically from the behavior of `NULLs`. So an indexed `NULL` needs to have a unique value. I propose that we encode such fields as `NULL/PrimaryKey`. We know `PrimaryKey` is unique for the table and the primary key columns are not `NULL`. The `NULL/` portion would be some type specific prefix for `NULL` values.

**Comment by tamird** [comment]
@petermattis interesting, I didn't know all the primary key columns were NOT NULL, but I've confirmed that this is how they are treated by postgres.

I did something hacky in #2020, seems sane?

**Comment by jusongchen** [comment]
Different RDBMS  use different implementations when indexing null values.
In Oracle, NULL values are not indexed. This behaviour can be verified by
running this script:



create table person(

first_name varchar2(200),

last_name varchar2(200),

SSN char(9) NULL,

constraint Unique_SSN unique(SSN)

-- unique constraint implicitly create a unique index

)
;

create index idx_name on person(last_name,first_name);

insert into person values ('John','Smith',null);
insert into person values ('Jusong','Chen',null);
commit;


ANALYZE index Unique_SSN COMPUTE STATISTICS;
ANALYZE index idx_name COMPUTE STATISTICS;

select index_name,table_name,num_rows from USER_IND_STATISTICS where
table_name='PERSON';


script output:

table PERSON created.
index IDX_NAME created.
1 rows inserted.
1 rows inserted.
committed.
index UNIQUE_SSN analyzed.
index IDX_NAME analyzed.
INDEX_NAME                       TABLE_NAME            NUM_ROWS
------------------------------- -------------------- ----------
*UNIQUE_SSN                      PERSON                        0 *
*IDX_NAME                        PERSON                        2 *


On the contrary , MSSQL choose to store those NULL values in index
structure. Either way has its pro and cons.

HTH,

Jusong Chen


On Fri, Aug 7, 2015 at 8:57 AM, Tamir Duberstein <notifications@github.com>
wrote:

> @petermattis <https://github.com/petermattis> interesting, I didn't know
> all the primary key columns were NOT NULL, but I've confirmed that this is
> how they are treated by postgres.
>
> I did something hacky in #2020
> <https://github.com/cockroachdb/cockroach/pull/2020>, seems sane?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/1909#issuecomment-128746288>
> .
>



-- 
Jusong Chen
408 315 2288
