### ISSUE TITLE
ui does not show warnings when certs are improperly generated

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#19091]
This is probably a question - but I remember the expected behavior to be that you should be able to see a single node in the admin UI, but you would lose quorum if you added another node. 

I am currently running on Digital Ocean with v1.0.6. I set up three servers all based in NYC. I ran the following command:

![image](https://user-images.githubusercontent.com/5768024/31287071-187d80cc-aa8e-11e7-8593-697e5c35e0e8.png)

I went to the admin UI, and would have expected to see a single node. Instead I get this:

![image](https://user-images.githubusercontent.com/5768024/31287109-34e3a994-aa8e-11e7-8eb3-903a9e9250ab.png)

Running cockroach node status returns:

![image](https://user-images.githubusercontent.com/5768024/31287133-46e6213a-aa8e-11e7-90ff-6ca999e850e4.png)

Odd, no?

On further investigation with @tschottdorf it appears that I did not correctly include the host name upon certificate generation. The cluster was running normally since all the nodes could talk to each other, but the admin UI was using the hostname for certificates, and wasn't able to show anything. Going through the debug page showed this:

![image](https://user-images.githubusercontent.com/5768024/31287776-70ded66a-aa90-11e7-807c-fe1cf43a64bc.png)

We should surface this warning to users so that they are aware of this issue.

**Comment by tschottdorf** [comment]
More specifically, it seems that you made the certificate valid for a hostname of `hostname` (as opposed to filling in the real thing, i.e. the output of running the command `hostname`.

**Comment by dianasaur323** [comment]
Hmm.. i think the docs are pretty clear - they use <> to show that you are supposed to fill it in. It's just really easy to make a mistake when you are copying and pasting and typing things manually.
