### ISSUE TITLE
sql: normalize IS/IS NOT to IS NOT DISTINCT FROM/IS DISTINCT FROM

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#19111]
`IS` and `IS NOT` expressions are specializations of `IS NOT DISTINCT FROM` and `IS DISTINCT FROM`, respectively. These specialized expressions behave the same way as their more general forms but have a limited set of allowable values (`NULL`, `UNKNOWN` (same as null), `TRUE`, `FALSE`, `NaN`) as their right operand. On the other hand, the general forms can have any arbitrarily-complex expression as their right operand. Unlike standard comparison operations that propagate `NULL` values if seen for either of their operands, these four expressions all treat `NULL` like an ordinary value (see [Postgres' docs](https://www.postgresql.org/docs/9.6/static/functions-comparison.html#FUNCTIONS-COMPARISON-PRED-TABLE)). 

It doesn't make sense for us to worry about four comparison operators during index selection or evaluation if `IS` and `IS NOT` can be normalized to their more general forms. In fact, because we don't perform this normalization in all cases right now, our index selection logic is lacking in certain cases for the `IS (NOT) DISTINCT FROM` expressions. We should add the following normalization rules to `normalize.go` (`ComparisonExpr.normalize`) and remove all references to the `Is` and `IsNot` operator above the normalization step (expr simplification, index selection, evaluation):
```
ComparisonExpr{Is,   left,right} -> ComparisonExpr{IsNotDistinctFrom,left,right}
ComparisonExpr{IsNot,left,right} -> ComparisonExpr{IsDistinctFrom,   left,right}
```

**Comment by prashcr** [comment]
I'd like to work on this! Will give it a shot over the next 2-3 days

**Comment by nvanbenschoten** [comment]
@prashcr Go for it!

**Comment by yuhit** [comment]
Hello, is this issue still "free"? I would like to work on it as my first issue.

**Comment by prashcr** [comment]
Hi, feel free to go for it!

**Comment by yuhit** [comment]
@nvanbenschoten @prashcr I noticed that `Is` and `IsNot` have been normalized to 
```
ComparisonExpr{Is,   left,right} -> ComparisonExpr{EQ,   left,right} and ComparisonExpr{IsNot,   left,NULL}
ComparisonExpr{IsNot,left,right} -> ComparisonExpr{NE,   left,right} or  ComparisonExpr{Is,      left,NULL}
```
and have done something for `Is/IsNot` NULL in index selection and evaluation.
I am not clear why Is/IsNot need normalized to `IsDistinctFrom/IsNotDistinctFrom` in this issue when index selection logic is lacking in certain cases for the `IS (NOT) DISTINCT FROM` expressions.

**Comment by nvanbenschoten** [comment]
@yuhit What you said about

> index selection logic is lacking in certain cases for the `IS (NOT) DISTINCT FROM` expressions

is exactly the problem here. Right now we do our best to normalize away from `Is/IsNot` wherever possible to allow us to take advantage of improved index selection rules. We also have logic in index selection for `Is/IsNot NULL`. But none of these rules apply to `IsDistinctFrom/IsNotDistinctFrom` at the moment!

 Since `IsDistinctFrom/IsNotDistinctFrom` is just a more general form of `Is/IsNot`, we should perform the normalization:
```
ComparisonExpr{Is,   left,right} -> ComparisonExpr{IsNotDistinctFrom,left,right}
ComparisonExpr{IsNot,left,right} -> ComparisonExpr{IsDistinctFrom,   left,right}
```
and then change all index selection rules to match on  `IsDistinctFrom/IsNotDistinctFrom` instead of `Is/IsNot`. This will allow us to unify a lot of logic between the two operator types and eliminate inconsistencies. Does that make sense?
