### ISSUE TITLE
opt: Support hints and/or planning constraints in the cost-based optimizer

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#19117]
As our SQL planning gets more complex it will get more unpredictable for our users. This issue is involved with introducing a SQL so that a user can specify a specific join order as well as join type (merge versus hash) in their queries.

See explicit join order specifications in postgres:

https://www.postgresql.org/docs/current/static/explicit-joins.html

(edit knz 2019-01-02:) Note that a "hint" is something that the planner may choose to disregard; whereas a "constraint" must be obeyed. For example, by this definition, the current "force index" syntax in CockroachDB is a constraint, not a hint; the ORDER BY clause is usually a hint when it is not at the top level, except in a few documented places where it is a constraint. The new feature described in this issue should be composed of both hints and constraints.

**Comment by knz** [comment]
@vivekmenezes ok to work on this, but this work is highly cross-team and will be deeply meshed in the optimizer story. I am thus requesting a work buddy from that team, probably Becca or Justin would be best.

**Comment by vivekmenezes** [comment]
I think this needs more PM investigation before we move forward on it.

**Comment by awoods187** [comment]
I'm splitting join reordering off into https://github.com/cockroachdb/cockroach/issues/32885 and renaming this to focus on hints

**Comment by awoods187** [comment]
@RaduBerinde can you link the PRs to this issue

**Comment by RaduBerinde** [comment]
Yes just #35183

**Comment by awoods187** [comment]
Great thanks!
