### ISSUE TITLE
build: cannot find -ltinfo

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#19116]
```
$ make build
GOPATH set to /home/mjibson
Running make with -j12
GEN pkg/cli/zcgo_flags.go
GEN pkg/server/status/zcgo_flags.go
GEN pkg/storage/engine/zcgo_flags.go
GEN pkg/ccl/storageccl/engineccl/zcgo_flags.go
make[1]: Nothing to be done for 'build_lib_static'.
[ 62%] Built target snappy
[100%] Built target snappy-unittest
[100%] Built target roach
[ 85%] Built target roach
[100%] Built target roachccl
[100%] Built target libprotobuf
[  0%] Built target build_version
[100%] Built target rocksdb
go build -i -o ./cockroach -v  -tags ' make x86_64_linux_gnu' -ldflags ' -X github.com/cockroachdb/cockroach/pkg/build.typ=development -X "github.com/cockroachdb/cockroach/pkg/build.tag=v1.2-alpha.20170901-695-gcb3503fc4" -X "github.com/cockroachdb/cockroach/pkg/build.utcTime=2017/10/09 01:09:56" -X "github.com/cockroachdb/cockroach/pkg/build.rev=cb3503fc4ba9737e7a02a274dc763018a1c70102" -X "github.com/cockroachdb/cockroach/pkg/build.baseBranch=v1.2-alpha.20170901"' .
github.com/cockroachdb/cockroach/vendor/github.com/knz/go-libedit/unix
# github.com/cockroachdb/cockroach/vendor/github.com/knz/go-libedit/unix
/usr/bin/ld: cannot find -ltinfo
collect2: error: ld returned 1 exit status
Makefile:191: recipe for target 'build' failed
make: *** [build] Error 2
```

The recent go-libedit changes aren't building on my system (debian).

I had to `sudo apt-get install libtinfo-dev` to get this to work. It is my opinion that we should not include C code that requires 3rd-party packages to be installed because of stuff like this.

**Comment by knz** [comment]
the terminfo library already exists on debian but I suspect with a different name.
Can you provide me the output of `ldd /usr/bin/reset` or `ldd /usr/bin/clear`?

**Comment by knz** [comment]
Huh I just checked on my debian system here (debian 8)
```
kena@debian:~$ ldd /usr/bin/reset
        linux-vdso.so.1 (0x00007fff6e968000)
        libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007f5e20a69000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5e206be000)
        /lib64/ld-linux-x86-64.so.2 (0x000055d7d4845000)
```

libtinfo is there without me having to install anything.

**Comment by knz** [comment]
```
kena@debian:~$ dpkg -l|grep tinfo
ii  libtinfo5:amd64                       5.9+20140913-1+b1                amd64        shared low-level terminfo library for terminal handling
```

**Comment by knz** [comment]
I'm still interested in the output of `ldd` on your debian, whatever it is!

**Comment by knz** [comment]
(FYI: the terminfo library is part of the Linux Standard Base specification, which all linux distros implement nowadays - http://refspecs.linuxfoundation.org/LSB_5.0.0/LSB-Common/LSB-Common/requirements.html#TBL-CORELIB - however perhaps your version of debian has chosen to do that without splitting the terminfo library from the ncurses library. If that is the case, I'd be interested to learn that.)

**Comment by knz** [comment]
(What I meant to say is that it is certainly not a "third party depedency" - it's a base system dependency)

**Comment by mjibson** [comment]
Here's the output from a different machine (ubuntu) than the one I originally tested on, but this now makes two different distributions that don't have this working by default.

```
$ ldd /usr/bin/reset
        linux-vdso.so.1 =>  (0x00007ffe3c18a000)
        libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007f5842b16000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f584274c000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f5842d3f000)
```

**Comment by knz** [comment]
As you can see the libtinfo is present on that system, which confirms the link should succeed. Yet it does not on yours (it does on mine). I am baffled. Will investigate.

**Comment by mjibson** [comment]
For the archives from a debian machine:

```
$ ldd /usr/bin/reset
        linux-vdso.so.1 (0x00007fffcf5b4000)
        libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007f38d4f9b000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f38d4bfc000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f38d53cb000)
```

**Comment by mberhault** [comment]
I think this is because the libtinfo.so symlink is only created by the dev package:
```
/var/lib/dpkg/info$ grep libtinfo\.so *.list
libtinfo5:amd64.list:/lib/x86_64-linux-gnu/libtinfo.so.5.9
libtinfo5:amd64.list:/lib/x86_64-linux-gnu/libtinfo.so.5
libtinfo-dev:amd64.list:/usr/lib/x86_64-linux-gnu/libtinfo.so
```

It's fairly standard for dev packages not to be installed, and for binary packages you only need the actual library, not the non-versioned symlink.

**Comment by knz** [comment]
Oooh, that's ... interesting!
I know how to work around that -- just create a fake symlink in a location known to the linker. Will do this in a later patch. Thanks Marc for finding this out!

**Comment by mberhault** [comment]
Why a fake symlink? It's perfectly reasonably to have dependencies on dev packages. Most modern distros don't come with build tools for example, and we need those.

**Comment by knz** [comment]
I was under the impression since the beginning of the libedit discussion is that "we should not be introducing extra build dependencies". If you think it's acceptable to require this, I'd be ok with it.
