### ISSUE TITLE
storage: limit number of Replicas per-node to limit memory usage

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#19129]
This is prompted by an OOM error that I saw when performing as many splits as
possible on `lapis`. In this case, `Replica`-related memory usage was the source
of about **75%-80%** of memory usage at the time of failure.

The desired approach to limiting the number of Replicas on each node in a Cockroach
cluster is to rebalance replicas away. Cockroach already does this transparently, and
the number of heuristics we use to decide when to rebalance is always being improved.
However, there comes a point where even with replicas perfectly balanced, there are still
too many for each node to handle. 

If each `Replica` is under heavy load then there's not much we can do; the system
is simply overloaded. However, we should be able to support configurations with
a huge number of ranges but where most are not under load (cold). We currently
quiesce `Ranges` when not under load, but this is not quite enough. As soon as a
`Replica` is accessed on a given node, it is instantiated and held in memory. This
means that even if all nodes on a system are inactive to the point where they can
be quiesced, they'll still take up part of a node's limited memory budget.

One idea here is to create an LRU policy on `Replicas` stored on a given `Store`.
The `Store` would then deallocate `Replicas` that are the most inactive. We already
lazily-activate `Replicas`, so this can be seen as an extension of that. However, 
a major concern here is thrashing. If we start deallocating `Replicas` only to have to
immediately re-allocate them, then we'll slow down the entire system. If we're loud
about this though, it's probably still preferable to crashing. A related question is
about the various queues that scan over all `Replicas` on a node. We wouldn't want
these to contribute to a thrashing issue.

**Comment by petermattis** [comment]
The number of replicas per node should be proportional to the disk storage per node. If you're attaching TB of storage to a particular node, we likely need to be recommending that you increase your memory accordingly.

**Comment by nvanbenschoten** [comment]
I'd expect that the memory per node would need to be proportional to the activity per node, not the raw amount of data stored on it. If a deployment has a TB of storage on a particular node but is accessing it in some kind of uneven distribution (think zipf) such that most of it is never touched, should the memory still need to grow proportionally with storage?

**Comment by donpdonp** [comment]
Im not sure if this is related but I'm running a single cockroachdb on a 1GB ram VPS  with a very modest dataset. A dozen tables and a few megabytes of data.  SQL queries stopped responding (just hangs). I checked the DB box (coreOS running docker cockroachdb-latest). The RAM is currently maxed out, so I looked at the dashboard and the only thing that looks puzzling to me is the "Replicas per Node" is at 200. Is this out of bounds? Is it something I can tune?

![screenshot from 2017-10-11 10-35-29](https://user-images.githubusercontent.com/13176/31457094-95b783cc-ae70-11e7-86a9-94c51c4f3ade.png)

**Comment by nvanbenschoten** [comment]
Hi @donpdonp, it certainly sounds like something's stuck, but I don't think that's the same issue as what we have filed here. Do you mind opening a new issue and describing what you're seeing? Thanks!

**Comment by donpdonp** [comment]
will do. it might be IO ops on the cloud server (unrelated to cockroach), hard to diagnose from just the VPS. thanks for the quick reply.

**Comment by bdarnell** [comment]
I think there's probably a lot of low-hanging fruit to reduce the footprint of an idle Replica before we get into removing them completely. Scanner queues already reduce the savings from quiescence and idle Replicas are currently accessed even more frequently for monitoring purposes, so thrashing is a significant risk, and adding a way for objects like this to be removed always has subtle synchronization risk (have we already addressed all of these for replica GC, or would there be new ones for removing "live" replicas?)

We could also invest in more streaming interfaces and increase the range size, which would reduce a lot of problems (while creating new ones in the short term, of course).

**Comment by petermattis** [comment]
I'm not sure if there is a lot of low-hanging fruit left on Replica, but there is almost certainly fruit left to pluck. I wonder how much memory we currently use per Replica. Would be good to do that analysis and see where it is going.

**Comment by tschottdorf** [comment]
We're aware of the memory impact of replicas. Between storage-layer memory accounting and fixing the #31125 roachtest, I don't think this issue adds anything new.
