### ISSUE TITLE
perf: Improve the throughput performance of distsql TableReader and some Aggregators

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#19120]
The idea here is to improve the throughput performance of some simple aggregation queries like COUNT(block_id), COUNT(*), etc:

- [ ] `SELECT COUNT(*)`
- [ ] `SELECT COUNT (DISTINCT) column_name`
- [ ] Large scans with a very sparse `WHERE` clause.
- [ ] Distributed sorting over large datasets
- [ ] queries using MIN/MAX/AVG

This can achieved via:
1. Creating a mechanism below TableReader to buffer a ton of kv data so that it can be handed over to distsql in a burst, or
1.1 Generate random data purely for distsql to process as if it were handed over quickly from the KV layer.
2. Consider buffering and releasing data in bursts post TableReader before each processor to see how it performs when it has to process a burst of data.

A followup to this issue is to develop custom benchmarks for each processor with synthetic loads.

**Comment by jordanlewis** [comment]
We've been doing a lot of benchmarking in this area. Closing for lack of specifics.
