### ISSUE TITLE
sql: consider desugaring operators into function calls where possible

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#19128]
To continue the discussion on #19109.

This issue is concerned with whether operators such as `&` or `|` which are not treated specially by any AST manipulating or index selection code should be parsed directly as function calls, rather than as operators. The argument being (I think) to maintain a clear separation of operators which are introspected on in that way and those which are not.

**Comment by knz** [comment]
@petermattis:

> I don't see much point in de-sugaring the existing operators (or any of the operators introduced in this PR). Maintaining the ability to round-trip queries is also an important principle for the AST (one which we've not adhered to 100%).

@knz:

> "Maintaining the ability to round-trip queries is also an important principle for the AST" - I do not know this to be true; given that 1) we certainly have not documented so anywhere 2) I can list several reasons why this is not desirable, in practice and in principle.

> Of course the reasons I have in mind may not be well informed, so before I put my foot in my mouth you could perhaps indulge and explain your position first. After all you were the person who introduced this idea in the first place, so if there's a good reason and it's not documented yet, perhaps you should really have the first shot at explaining.

**Comment by petermattis** [comment]
I'm thumbs down on doing this as a) it feels like busy work and b) it removes the ability to round-trip queries. As stated in #19109:

> Maintaining the ability to round-trip queries is also an important principle for the AST (one which we've not adhered to 100%).

The reason for that principle (as I've been informed) is quite straightforward: if you need to display the query back to the user it should be close to what they input. This allows the user to more easily "grep" for where the query occurs in their code. For example, we're displaying the query back to the user for query stats. It would be confusing for a user to see a query that contained `BITAND(a, b)` in some report of slow queries but be unable to find the string `BITAND` in their code base. We could certainly document around it, but the point of the principle is to remove the need to do so in the first place.

Note that there are a decent number of places in the AST where we have nodes or state purely for round-tripping purposes. For example, `ParenSelect` and `ParenExpr` and the specific join operation where `JOIN`, `INNER JOIN` and `CROSS JOIN` are all equivalent.

**Comment by knz** [comment]
The counter-point:

1) each single new AST node type has a *multiplicative* effect on code size: there must be dedicated handling code for each subsequent transform of the AST. Less code is better code.

2) each time we have two different AST node types for things that are semantically equivalent or contain common functionality, we create a risk to fail to update one set of code paths when we change another, which is a source of hard-to-find bugs (because unit tests typically do not check all syntactic variants, for good reason). 

3) each time we have two different AST node types for things that are semantically close we increase the cognitive overheads of contributors wanting to understand the semantics of the AST.


4) we already desugar *many* expressions for the reasons above so the argument "we already do this" does not hold

**Comment by petermattis** [comment]
Well, long term we shouldn't be doing transforms on the AST anyways. Instead, the AST should be converted to the IR representation which is when the de-sugaring would take place. I would much rather spend effort on introducing the IR representation than removing semantically equivalent AST nodes. And, in the instance of binary operators, I don't see much of a difference between a new operator and a function call.

**Comment by knz** [comment]
Well I tend to agree on the line of thought, but then if there is nothing happening on the AST other than desugaring to an IR, there's a technical argument to be made in favor of letting the parser desugar so as to not waste allocations/memory on something we throw immediately away.

**Comment by petermattis** [comment]
Yes, that argument can be made, but let's make it once we have the IR work well under way. Worrying about those extra allocations is premature optimization.

**Comment by knz** [comment]
Ok, we can agree on that.

**Comment by andy-kimball** [comment]
I'm closing this down, because we can now de-sugar (or not) when we build the opt memo. I also agree that the AST should reflect the original syntax as much as possible.
