### ISSUE TITLE
storage: Test framework for simulating allocator in different cluster configurations

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#19131]
We currently test the allocator's decisions in a few manually specified configurations in unit tests, and very few of these do anything interesting with large clusters or multi-locality clusters. More complicated testing has to be done manually with `allocsim`, which means it doesn't get done often enough of on diverse enough configurations, leading to the possibility of user bug reports like #19013.

We would likely benefit from a simulator [like we have for gossip](https://github.com/cockroachdb/cockroach/blob/master/pkg/gossip/convergence_test.go) that ensures convergence, i.e. no thrashing. To be of the most benefit, the simulator could randomly generate a configuration of x nodes, spread throughout y localities, with randomly assigned numbers (and sizes) of replicas to start out. The cluster would then be expected to converge and stop rebalancing after some time.

Not required for, but would be nice to help validate https://github.com/cockroachdb/cockroach/issues/17979.

**Comment by tschottdorf** [comment]
@a-robinson  could this be closed for #24818? (I'm just going to do it and rely on your reopening)

**Comment by a-robinson** [comment]
It's a different idea, but given that this is just an idea for tests that we don't have active plans to write, I'm fine with closing it. It'd be useful, but there are a lot of things we can do that will be useful.
