### ISSUE TITLE
storage: break up giant raftMu critical section downstream of raft

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#19156]
In testing our single-range write throughput (https://github.com/cockroachdb/cockroach/issues/18657), it's become clear that `raftMu` is the primary bottleneck. We hold it for a **very** long time as [`handleRaftReadyRaftMuLocked`](https://github.com/cockroachdb/cockroach/blob/8cbe74cb81ca2ede4fa948677574cbca4cd59136/pkg/storage/replica.go#L3197) executes.

In my testing in #18657 it's not unusual for `raftMu` to be held for many tens of milliseconds at a time, and occasionally more than 100ms. And from adding some poor man's tracing to the code, it appears as though the bulk of the time is spent [sending messages](https://github.com/cockroachdb/cockroach/blob/8cbe74cb81ca2ede4fa948677574cbca4cd59136/pkg/storage/replica.go#L3411) and [applying committed entries](https://github.com/cockroachdb/cockroach/blob/8cbe74cb81ca2ede4fa948677574cbca4cd59136/pkg/storage/replica.go#L3451), with the latter being the worst (and least predictable) offender.

There seem to be three ways to attack this:

1. Try to make the message sending and applying of committed entries faster. There may be less big wins available here, but long term it'd likely reduce CPU usage the most.
1. Parallelize the sending of messages (and maybe also the applying of committed entries?). This would help single range throughput, but potentially at the expense of total cluster throughput in workloads that aren't skewed toward a single range. Load-based splitting (#19154) could probably get similar results but in a more generalized way.
1. Break up the big critical section. This would mean unlocking and re-locking `raftMu` as necessary rather than holding it throughout the entire process. I'll need some guidance (from @bdarnell? @petermattis?) on whether this is even remotely feasible, since it's possible that all of that work really does need to be done as part of a single critical section. If we can break it up, though, it opens up opportunities for pipelining, for example having one goroutine persisting new log entries, one sending messages, and one applying committed entries.

According to the [etcd-raft usage instructions](https://github.com/coreos/etcd/tree/master/raft#usage), it'd be safe for us to advance the raft node as soon as we've persisted the new raft entries to disk (i.e. before the two slow steps referenced above), but those steps as written today do appear to rely on some things protected by `raftMu`. That would seemingly make option 3 viable in the sense that `handleRaftReadyRaftMuLocked` could return as soon as it had synced new entries to disk and `Advance`d the raft group, with the message-sending and applying continuing in the background so long as we ensure that all messages/entries are processed in the order they were returned by raft.

Sorry for the giant block of text, but I wanted to explain where I'm at with single-range performance and make it possible to get the information I want about the viability of breaking up the big `raftMu` critical section.

**Comment by a-robinson** [comment]
And cc https://github.com/cockroachdb/cockroach/issues/18779, since this could be a bit of a refactoring project.

**Comment by petermattis** [comment]
I think we need mutual exclusion on handling of Raft ready messages. But perhaps that could be achieved with the addition of another mutex (`raftReadyMu`?). Gah, my head is hurting looking at this locking again.

**Comment by a-robinson** [comment]
Do you think that we need that due to how raft works or due to how our various above-raft mechanisms work? My reading of raft itself is that it would be ok to pipeline the different stages of handling the Raft ready messages, as long as we:

* Finish persisting new entries before doing anything else with a given Raft ready
* Advance the Raft state before moving on to a new Raft ready
* Process each Raft ready in order at each stage of the pipeline

> Gah, my head is hurting looking at this locking again.

Yeah, it is possible that load-based splitting and optimizing the work being done (rather than the locking/ordering) would be a better place to focus efforts.

**Comment by petermattis** [comment]
My statement was based on how our various above-Raft mechanisms work. I think it would be problematic for multiple routines to be running `processRaftCommand` simultaneously.

I can understand why `raftMu` is held for tens of milliseconds: the call to synchronously commit a batch can be slow. What I'm surprised at is that this causes problems because the only call I see to lock `raftMu` is in `Replica.propose` (the one in `maybeInitializeRaftGroup` should rarely be called). And you said that removing the `raftMu.Lock` in `Replica.propose` didn't help performance. So is there some other usage of `raftMu` that I'm not seeing that is causing problems?

**Comment by tschottdorf** [comment]
Where exactly are we spending significant amounts of time when sending messages? `sendRaftMessage` itself looks like it should be rather fast, and the remaining stuff there deals with sideloading and doesn't (shouldn't) actually do anything in your testing.

> I can understand why raftMu is held for tens of milliseconds: the call to synchronously commit a batch can be slow. What I'm surprised at is that this causes problems because the only call I see to lock raftMu is in Replica.propose

Can we revisit #18657? I'm curious how the single-range case compares against the multi-range one (assuming no `raftMu` acquired during proposals). Naively the amount of syncing going on should be about the same (assuming enough concurrency). Each proposal should eat about 1-2 sync latencies (since it has to wait out the ongoing sync, and then its own sync) and throughput should be the same. Probably both of my statements are wrong, but I think it's going to be helpful to find out. Also, how does `min_wal_sync_interval=1ms` or even `5ms` influence things?

**Comment by a-robinson** [comment]
> My statement was based on how our various above-Raft mechanisms work. I think it would be problematic for multiple routines to be running processRaftCommand simultaneously.

Ack, thanks.

> I can understand why raftMu is held for tens of milliseconds: the call to synchronously commit a batch can be slow.

In my printf-style tracing, the synchronous committing of new raft log entries never took more than a few milliseconds. The truly slow part was doing the rest of the processing after that to respond to raft messages (occasionally) and apply committed commands (most frequently).

> So is there some other usage of raftMu that I'm not seeing that is causing problems?

Not that I've noticed. The problem I've observed is that `handleRaftReadyRaftMuLocked` for a given batch takes a very long time, preventing the next batch of requests from beginning processing. Hence the suggestion to pipeline the different stages of `handleRaftReadyRaftMuLocked`.

**Comment by a-robinson** [comment]
> Where exactly are we spending significant amounts of time when sending messages?

The time here doesn't seem to get spent in any large outliers, rather it just takes a while to send so many messages when a large batch of requests has built up. For example, some trace outputs include:

* Sending ~125 messages taking 4.2ms
* Sending ~70 messages taking 2.7ms
* Sending ~175 messages taking 3.5ms
* Sending ~125 messages taking 7.9ms

It appears to be more of an issue on the leader than on the followers. It's certainly not a ton of time, but every millisecond that we're holding the lock to send messages is blocking new requests from making progress. Although it'd be less impactful than speeding up the applying of committed commands, moving the message-sending out of the critical section would be the easiest change from a safety perspective.

> Can we revisit #18657? I'm curious how the single-range case compares against the multi-range one (assuming no raftMu acquired during proposals).

I'll re-test it today, but I can't remember a single configuration of #18657 that I've tested in which a split didn't give a considerable spike to throughput (and a corresponding decrease in dropped raft messages. The bottleneck for single range writes is waiting for the previous raft ready to finish processing before new messages can be processed.

> Each proposal should eat about 1-2 sync latencies (since it has to wait out the ongoing sync, and then its own sync) and throughput should be the same.

That *might* be true if we didn't build up so big of a backlog (100 raft requests) that we started dropping new ones, requiring them to be re-sent. But even so, it's not so much about sync latencies at this point (which are only a few milliseconds) as it is about `handleRaftReady` processing time as a whole, since the applying of commands is dwarfing the syncing of entries.

> Probably both of my statements are wrong, but I think it's going to be helpful to find out. Also, how does min_wal_sync_interval=1ms or even 5ms influence things?

For the single range case, switching to 1ms had no noticeable effect (which makes sense given that the time taken by apply, which doesn't require syncing, is the main bottleneck). Switching to 5ms hurt throughput and latency by a small, but noticeable amount, around 5-10%.

**Comment by a-robinson** [comment]
> Can we revisit #18657? I'm curious how the single-range case compares against the multi-range one

Here's a single split. Ignore the actual values since they're being affected by my very verbose logging; just focus on the relative changes:

<img width="929" alt="screen shot 2017-10-11 at 10 25 33 am" src="https://user-images.githubusercontent.com/7085343/31446916-b7f766a2-ae6e-11e7-9ae2-f39af4c234a2.png">
<img width="1245" alt="screen shot 2017-10-11 at 10 25 48 am" src="https://user-images.githubusercontent.com/7085343/31446920-ba331f92-ae6e-11e7-9499-fcf916f26ded.png">


And here's splitting from 2 ranges to 21 ranges (by setting max range size down to 8MiB):

<img width="933" alt="screen shot 2017-10-11 at 10 31 06 am" src="https://user-images.githubusercontent.com/7085343/31447180-5b50b416-ae6f-11e7-8af6-d628b7b1261e.png">
<img width="1253" alt="screen shot 2017-10-11 at 10 31 13 am" src="https://user-images.githubusercontent.com/7085343/31447188-5f69fb0c-ae6f-11e7-9003-cd16046fd3d7.png">

**Comment by tschottdorf** [comment]
> The time here doesn't seem to get spent in any large outliers, rather it just takes a while to send so many messages when a large batch of requests has built up.

Hmm, that just seems like... a lot, but I missed that `sendRaftMessage` acquires `replicaMu`, which it would then do 125x and that mutex we *do* lock a bunch during proposing. Seems like an obvious improvement here to avoid re-locking over and over again (bet you could just skip that lock without things blowing up too much for your testing). Once that's done and it's still not where we'd like it to be, we could have `sendRaftMessage` be called in a goroutine, or better, have an on-demand worker goroutine that handles message sending (just as you proposed).

> Although it'd be less impactful than speeding up the applying of committed commands

Oh, I see. Sorry, I had made the misguided assumption that by "applying committed entries" you meant the sync, but I'm not sure why I thought that.

You're right that it's unfortunate that we're still holding on to `raftMu` while we apply committed entries and your initial idea of moving the `Advance` up to after the sync and passing the rest of to a worker goroutine seems like the right way to address this. (The way I imagine these goroutines is that they're singletons and shut down when they've been idle for `O(seconds)` and are recreated on demand). I think it shouldn't be too hard to prototype this to see what the impact would be (or rather, confirm that that gets you where you think we should be).

In carrying out the steps above, we may have to change the mutex the sideloaded storage is tied to (currently `raftMu`, but there's no deeper reason for that other than it being convenient at the time), but let's see about that when it becomes relevant. Certainly doesn't matter for workloads that don't `RESTORE`.

**Comment by bdarnell** [comment]
Transplanting my comments from https://github.com/cockroachdb/cockroach/issues/18657#issuecomment-336721843

If raftMu is only used to guard against concurrent replica GC (which was the original idea but I'm not sure if it's stayed true as things have evolved), maybe there's room to turn raftMu into a RWMutex and lock it in read mode everywhere but in creation and destruction of the raft group.

The RWMutex suggested at https://github.com/cockroachdb/cockroach/blob/1811c61925c2bc7bfd9b5b132613657b609ac75a/pkg/storage/store.go#L440-L443 could be a replacement for raftMu.

**Comment by a-robinson** [comment]
Thanks for helping to clarify things @bdarnell and @tschottdorf! I'm excited to continue this line of testing soon.

**Comment by bdarnell** [comment]
As I rediscovered in https://github.com/cockroachdb/cockroach/issues/19172#issuecomment-337061024, raftMu has an important use in handling the split/snapshot race (and this use requires an exclusive lock; it won't be easy to replace it with an RWMutex. A sync.Cond with an explicit state variable might work)

**Comment by a-robinson** [comment]
> Hmm, that just seems like... a lot, but I missed that sendRaftMessage acquires replicaMu, which it would then do 125x and that mutex we do lock a bunch during proposing. Seems like an obvious improvement here to avoid re-locking over and over again (bet you could just skip that lock without things blowing up too much for your testing).

Just moving the locking of `replica.mu` outside the loop over all messages has a pretty negligible impact on throughput and latency. It looks like it may be slightly better, but not by much:

Locking/unlocking in every `sendRaftMessage` call:
<img width="942" alt="screen shot 2017-10-25 at 11 31 05 am" src="https://user-images.githubusercontent.com/7085343/32007996-1d8dc492-b979-11e7-874f-3d91fad4adfb.png">

Locking/unlocking just once, outside the loop over messages:
<img width="946" alt="screen shot 2017-10-25 at 11 37 54 am" src="https://user-images.githubusercontent.com/7085343/32008048-3c6d3d7a-b979-11e7-9bc4-a6bb5102d559.png">

**Comment by a-robinson** [comment]
Naively parallelizing the sending of messages with the applying of committed commands using a `sync.WaitGroup` had a small, but a little more noticeable effect on throughput:

<img width="944" alt="screen shot 2017-10-25 at 12 58 43 pm" src="https://user-images.githubusercontent.com/7085343/32011930-42cbfffc-b984-11e7-8f7f-fd8799ce2326.png">

Probably not worth spending too much time on in isolation.

**Comment by nvanbenschoten** [comment]
Closing, as the learnings and ideas presented here have diffused into a number of other issues, many of which have been addressed.
