### ISSUE TITLE
backup: prevent mistaken use of `nodelocal`

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#19158]
Some feedback on `nodelocal` from external users and even internal users -- engineers and PMs who are familiar with using a distributed database -- have made it clear that `nodelocal` is confusing.

 In a distributed cluster, what does "write this thing to the local disk" even mean? Clearly no one is sure.

Example, from the QA pass on EXPORT:

> * Problems with providing nodelocal paths with different (possibly invalid?) numbers of slashes (confusing trying to map to/from the template of `[scheme]://[host]/[path]?[parameters]` in the  docs -- if everything goes into the external I/O dir, why is the starting slash even needed?):
> ```
> root@:26257/defaultdb> EXPORT INTO CSV 'nodelocal:' FROM SELECT * from startrek.quotes;
> pq: Local storage requested but path not provided
> root@:26257/defaultdb> EXPORT INTO CSV 'nodelocal:/tmp/csv1' FROM SELECT * from startrek.quotes;
> +----------+------+-------+
> | filename | rows | bytes |
> +----------+------+-------+
> | n1.0.csv |  200 | 20918 |
> +----------+------+-------+
> root@:26257/defaultdb> EXPORT INTO CSV 'nodelocal://tmp/csv1' FROM SELECT * from startrek.quotes;
> pq: nodelocal does not support hosts: nodelocal://tmp/csv1
> root@:26257/defaultdb> EXPORT INTO CSV 'nodelocal:///tmp/csv1' FROM SELECT * from startrek.quotes;
> +----------+------+-------+
> | filename | rows | bytes |
> +----------+------+-------+
> | n1.0.csv |  200 | 20918 |
> +----------+------+-------+
> ```
> * For nodelocal mode, it’s really unintuitive where the file goes.
>   * I think the docs need to more strongly call out what’s needed for NFS/nodelocal to make sense. Using it without setting the `--external-io-dir` flag is basically nonsensical even if all the nodes are on the same machine, since the resulting file location(s) can't be known in advance.
>   * I got pretty confused at first trying to find the output file, not realizing it was written into the leaseholder’s store directory (not the absolute filesystem path, or on gateway node, or on the sql shell’s node).
> * Parameters that aren’t recognized should be an error. Instead, they’re silently ignored
> ```
> root@:26257/defaultdb> EXPORT INTO CSV 'nodelocal:///tmp/csv1?AWS_ACCESS_KEY_ID=foo' FROM SELECT * from startrek.episodes;
> +----------+------+-------+
> | filename | rows | bytes |
> +----------+------+-------+
> | n3.0.csv |   79 |  3021 |
> +----------+------+-------+
> root@:26257/defaultdb> EXPORT INTO CSV 'nodelocal:///tmp/csv1?foo=bar' FROM SELECT * from startrek.episodes;
> +----------+------+-------+
> | filename | rows | bytes |
> +----------+------+-------+
> | n3.0.csv |   79 |  3021 |
> +----------+------+-------+
> ```

## Feature

Ensure that BACKUP destination is the same across all nodes (since non-cloud paths like `nodelocal://` or even `http://` may point at local paths).

## backstory
A recurring source of confusion is the local file storage for backups/imports/etc.

`nodelocal` is the simplest and easiest backup location in a single-node cluster.

In multi-node clusters though, if a given node writes a file to a path on its local disk, that isn't particularly useful to the other nodes if/when they need that file, unless that path happens to be backed by something like NFS or another network file system. So far though, this seems to be easy to overlook, and both internal testers and external customers have run into this.

After initial internal users hit it, we changed the scheme from `file://` (or no scheme at all, and just allowing e.g. `BACKUP foo.* to '/mnt/foo'`) to be `nodelocal`  in the hopes that it would make it a little more clear what it did, or at least that its unfamiliar name would give a user pause and lead them to look at the docs where we added callout box that said much or the above.

However it seems we have not adequately addressed the potential pitfall, since we are still encountering internal and external users hitting this. We can continue to make the docs warning more explicit, but some users may not read it (if they see an existing example and crib it, forget the warning, etc).

The scariest part of this is that a user might run a `BACKUP ... nodelocal://` that completes successfully and think their data is backed up and later lose data because their backup isn't usable.  Ideally we should make this mistake harder to make.

One option would be to return an error, rather than writing a (likely useless backup) if `nodelocal` is used on a multi-node cluster. This would catch that mistake right away and make it clear what's wrong (versus an opaque "missing file" error at restore), but breaks the legitimate (though maybe uncommon) use case of an actual network-backed filesystem. We could add a URI flag like `?fs=nfs` to skip the error, or we could add an alias for `nodelocal` like `nfs` that does the same.

**Comment by jseldess** [comment]
+ @sploiselle, in case he sees any quick edits we can make to the docs prior to the 1.1 release.

**Comment by benesch** [comment]
Why not write out a PROGRESS descriptor, checksum it, and then ask each node in the cluster via RPC to verify the checksum on the version of the file they see before proceeding with a nodelocal backup?

**Comment by dt** [comment]
Our io dir limits seem like they'll probably push more users to look at the docs, so I think we can close this, at least for now, unless it comes up again.

**Comment by nstewart** [comment]
per our discussion: if backup succeeds, restore should succeed. we also noted we need a flag for people who really, really want to write data that can't be read from all nodes.

**Comment by dt** [comment]
new plan: the gateway already writes to the store to confirm it is writable and lock out accidental concurrent writers -- we just need the export request to confirm they can see that sentinel write before they proceed. They could do something fancy like opening it an comparing a nonce or something that was in the RPC, but even just verifying it exists means "yeah, it looks like i'm supposed to be writing a backup here", so that's probably enough.

We should add a flag to ExportRequest that requests this behavior, and optionally have a cluster setting for "yes, i know, i want to blindly write" that omits the flag.

**Comment by dt** [comment]
we added support for `nodelocal` URIs to have a nodeID in the host component (e.g. `nodelocal://3/...`). It is currently a) optional and b) ignored, but the plan is that if it is there, we'd check that it is actually the node ID of the node doing the writing, so e.g. if you run a BACKUP to `nodelocal://1/foo` which sends an ExportRequest to node 2 for some range, it would fail: node 2 would go to write to the backup destination, but then see the ID mismatch and complain, rather than writing a file where the user didn't expect it. This would help make it clearer where files actually end up.

Once we do that, we'd also require a node ID to be passed. Optionally we could allow some special meta value (say 0) that opts out of the strict check, in case the filesystem in question is actually NFS or some other setup where the user explicitly wants every node writing to its own, separate local disk, but in practice that is usually a mistake rather than desired.

**Comment by dt** [comment]
#41990 
#45764
