### ISSUE TITLE
sql: Move structured code to sql directory

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#1917]

**Comment by tamird** [comment]
I'm not sure we should do this. The separation doesn't hurt anything, and there's nothing SQL-specific in structured AFAIK.

**Comment by MBerhault** [comment]
well, that's not entirely true. descriptors are starting to have parser.* stuff in them, mostly for permissions. There will probably be more and more too.

**Comment by tamird** [comment]
That might be a reason to move permissions into sql.

**Comment by vivekmenezes** [comment]
well, there is very little in structured at the moment. Perhaps there is
value to moving stuff from sql into structured. But, I think we should just
kill it for now, and recreate it at a later time
when we know we want to create a structured-API.

**Comment by petermattis** [comment]
While the separation between sql and structured doesn't particular hurt, it also isn't providing any benefit. I'm mildly in favor of this change for the simplification.

**Comment by petermattis** [comment]
@MBerhault We talked about doing this move earlier this week. Care to take it on?

**Comment by MBerhault** [comment]
that's my next step, just waiting to merge that damn privilege thing.
