### ISSUE TITLE
backup / restore: 1.2 testing!

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#19170]
Encapsulating our last bulk-io meeting comments into a github issue now, and would love for you all the bikeshed and vote on what you think makes sense for us to do, and what doesn't.

**Goals**
Test backup / restore on cluster configurations that we expect users to run in the wild.
We need to test full, incremental, and point-in-time on these.

- [ ] Geo-distributed cluster (since we are pushing partitioning in 1.2)
- [ ] Large cluster - 64 nodes and ~16TB tpch https://github.com/cockroachdb/cockroach/issues/17060
- [ ] Linear scaling
- [ ] Experimental_fingerprint (? not sure what this is, but @danhhz mentioned it so must be good?)
- [ ] Automated EL pipeline from reg to pm (I can handle this one). Also doubles as long-running non-wiped clusters.
- [ ] Chaos

Things we mentioned in the meeting that I think we could potentially punt (or at least just try running once versus doing nightlys)
- [ ] multi-version cluster / rolling upgrades

cc @danhhz @mjibson @dt 

also, @cuongdo I think you were concerned about capacity, so maybe we should bump some of these down to things we can punt?

**Comment by cuongdo** [comment]
cc @mberhault since these might influence the ephemeral cluster scripts

**Comment by cuongdo** [comment]
@dianasaur323 I think that each of those takes some amount of work to set up and maintain. So, a rough prioritization would be helpful. Also, we don't yet support automated chaos testing, so that'll take more work.

**Comment by dianasaur323** [comment]
@cuongdo to be honest, I think chaos is least interesting to me from a nightlys perspective, so if it takes too long, we can punt. @mjibson and @dt and I will meet on Monday, so we can attach expected complexity of work to each of these items and scope it down.

**Comment by dianasaur323** [comment]
Ok, closing this issue and focusing on geo-distributed and large clusters.
