### ISSUE TITLE
ui: distinguish live non-decommissioning nodes from live decommissioning nodes

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#19179]
We show nodes as "decommissioned" if they're dead and marked as decommissioning. However, nodes may be decommissioned but still live (for example, if the operator doesn't shut down the process, or if the node is accidentally restarted). There should be a visual cue in the live nodes list if a node is in decommissioning status.

cc @dianasaur323, taken from #18478 which I accidentally closed because there was more going on that I kept track of 😄 

@cuongdo for triage.

**Comment by dianasaur323** [comment]
thanks, @tschottdorf. I was getting confused myself! This is perfect :+1:

**Comment by couchand** [comment]
Closed in #22237.
