### ISSUE TITLE
We have detected that multiple versions of CockroachDB are running in this cluster. 

### ISSUE THREAD

**Issue by sinfomicien** [cockroachdb/cockroach#19217]
## VERSION
Build Tag:    v1.1.0-rc.1
Build Time:   2017/10/05 15:33:25
Distribution: CCL
Platform:     linux amd64
Go Version:   go1.8.3
C Compiler:   gcc 6.3.0
Build SHA-1:  8b865035e21aa4fa526ee017ba9dc685d7af649c
Build Type:   release-gnu

## OS
Linux cockroachdb-1 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u5 (2017-09-19) x86_64 GNU/Linux

## Problem
The admin UI of the cluster is complaining about multiple versions of CockroachDB

## How to reproduce
Create a 4 to 7 cluster with version 1.0.6 of cockroach. Decommission the last node
Then upgrade all other nodes to 1.1.0-rc1

The decommissioned one, stay in version 1.0.6, then the alert is shown in the Admin UI.

##  Discussion

In my case, i won't restart the node... As the VM has been deleted. I tried to definitely delete a node, but didn't find any way to do so.

But at some point, the alert can also just remove the decommissioned nodes from the verification ?

**Comment by tschottdorf** [comment]
Hi @sinfomicien, I have good news and bad news for you -- good news: this is a known issue and we know it's annoying and will fix it. Bad news: we haven't yet. Please follow https://github.com/cockroachdb/cockroach/issues/15534 instead -- I'll close this, but thanks for your report!
