### ISSUE TITLE
certs: avoid common misconfigurations

### ISSUE THREAD

**Issue by kresic-ivan-nsoft** [cockroachdb/cockroach#19233]
**BUG REPORT**

1. Log file headers look like:

[config] file created at: 2017/10/13 10:09:18
[config] running on machine: db1
[config] binary: CockroachDB CCL v1.1.0 (linux amd64, built 2017/10/12 14:50:18, go1.8.3)
[config] arguments: [cockroach start --certs-dir=certs --advertise-host=IP1]

[config] file created at: 2017/10/13 10:10:09
[config] running on machine: db2
[config] binary: CockroachDB CCL v1.1.0 (linux amd64, built 2017/10/12 14:50:18, go1.8.3)
[config] arguments: [cockroach start --certs-dir=certs --advertise-host=IP2 --join=IP1:26257]

and similar for the third one.

2. The upgrade didn't go smoothly. The second and third node (that joined the original one) went fine. When the original node was shutdown and upgraded (upgraded last), it failed to start. When it did start, and other two nodes joined in, the admin UI says "Connection to CockroachDB node lost.", even though the status says:

+----+-----------------------+--------+---------------------+---------------------+
| id |        address        | build  |     updated_at      |     started_at      |
+----+-----------------------+--------+---------------------+---------------------+
|  1 | IP1:26257 | v1.1.0 | 2017-10-13 10:14:30 | 2017-10-13 10:09:22 |
|  2 | IP2:26257 | v1.1.0 | 2017-10-13 10:14:30 | 2017-10-13 10:10:10 |
|  3 | IP3:26257 | v1.1.0 | 2017-10-13 10:14:30 | 2017-10-13 10:10:16 |
+----+-----------------------+--------+---------------------+---------------------+

Any help here?

**Comment by tschottdorf** [comment]
@kresic-ivan-nsoft, is the admin UI unavailable on all nodes or just one? Can you use your browser's debugging tools to find out whether you're getting some non-200 HTTP error codes from the request the UI makes? For me under Chrome, this is right click -> Inspect -> Network and then wait a bit (here everything is OK, but you'll likely see something red):

![image](https://user-images.githubusercontent.com/5076964/31543067-cecb5850-b014-11e7-944e-2709f49f5ce3.png)

When there's something unhappy (say `health`) click it, and copy-paste the "headers" tab, please.

Thanks for your report!

**Comment by kresic-ivan-nsoft** [comment]
@tschottdorf I'm getting internal server error (500) on all admin UIs.

Here are the request headers for :

Request URL:https://[domain].sparkbp.com/_status/nodes
Request Method:GET
Status Code:500 Internal Server Error
Remote Address:172.104.152.190:443
Referrer Policy:no-referrer-when-downgrade
Response Headers
view source
Cache-Control:no-cache
Connection:keep-alive
Content-Encoding:gzip
Content-Length:182
Content-Type:application/x-protobuf
Date:Fri, 13 Oct 2017 10:50:22 GMT
Server:nginx/1.10.2
Request Headers
view source
Accept:application/x-protobuf
Accept-Encoding:gzip, deflate, br
Accept-Language:en-US,en;q=0.8,hr;q=0.6,sr;q=0.4,bs;q=0.2
AlexaToolbar-ALX_NS_PH:AlexaToolbar/alx-4.0
Authorization:Basic ZGJhZG1pbjpWN2NLOEFiQWM2ZGg=
Cache-Control:no-cache
Connection:keep-alive
Content-Type:application/x-protobuf
DNT:1
Grpc-Timeout:10000m
Host:[domain].sparkbp.com
Pragma:no-cache
Referer:https://[domain].sparkbp.com/
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36.


Do you need anything else?

**Comment by tschottdorf** [comment]
Actually, what's in the `Response` tab? If it's not gibberish it'll likely be the actual error.
Is there anything in the logs that looks suspicious (For example, `rpc: Attempting to marshal runtime.errorBody` which we saw in #19195).

**Comment by kresic-ivan-nsoft** [comment]
Hi @tschottdorf,

the errors are the same: connection error: desc = "transport: authentication handshake failed: x509: certificate is valid for li1668-xxx.members.linode.com, [domain].sparkbp.com, localhost, li1420-yyy.members.linode.com, li1420-yyy, not li1668-xxx".

But the nodes start, so the certificates shouldn't be to blame, right?

**Comment by tschottdorf** [comment]
This does look like the certificates are to blame. Try [fixing the certs](https://www.cockroachlabs.com/docs/stable/secure-a-cluster.html) but make sure to generate a unique cert on each node (the docs are somewhat unclear here because the example assumes it's on one host). And you're right, maybe we can do a better job at warning about this at startup (though there are probably situations in which the node itself can't figure it out).

**Comment by kresic-ivan-nsoft** [comment]
Hmmmm, the certificates are unique and haven't been changed. The error happened after the upgrade. The cluster is running and I can connect via a node or a load balancer and do queries, everything is working fine, I just can't get any info from the admin UI.

**Comment by kresic-ivan-nsoft** [comment]
Anyways, I changed the server hostname from li1668-xxx to li1668-xxx.members.linode.com and it's working again. It's weird that the cluster started in the first place if there was a hostname issue.

Anyways, thanks a lot for your help, much appreciated.

**Comment by tschottdorf** [comment]
I'll reopen this so that we can fix the fact that you had to find out the hard way. 👍

@mberhault can you pin this on certificate handling changes we carried out between 1.0.6 and 1.1.0?

**Comment by dianasaur323** [comment]
Great, thanks for reopening! Was about to do the same thing :)

**Comment by mberhault** [comment]
Certificate handling hasn't changed between 1.0 and 1.1.
I can think of a couple of different reasons for this:
* we changed the way we determine our own hostname. eg: 1.0 determined it to be  li1668-xxx.members.linode.com, but 1.1 says  li1668-xxx
* certs or hostnames got mixed up:  cert is for li1420-yyy, but hostname is li1668-xxx
* the `--host` or `--advertise-host` flags were changed
* hostnames themselves were changed

@kresic-ivan-nsoft: can you clarify what command line arguments you used for each version and what the contents of the cert files were? Along with the hostname (`hostname` and `hostname -f`, feel free to obfuscate parts of it).

**Comment by kresic-ivan-nsoft** [comment]
Hi everyone,

the certs weren't mixed up and the flags haven't been changed. As I can recall, I changed the default hostnames at the initial server setup phase. If the hostnames somehow got reset or whatever on our side, which I'm not excluding at this point, that still leaves a question why the cluster started up if there was a hostname issue, which may point to your first point.

It seemed as though the cluster and the admin UI had different ways of handling the hostname/certs.

**Comment by dianasaur323** [comment]
@kresic-ivan-nsoft yes, another user of our just had the same issue. The solution was to add the hostname to the certs generation command. We are actively working on making these two experiences the same. Ongoing discussion is occurring here - https://github.com/cockroachdb/cockroach/pull/17145

**Comment by arjunravinarayan** [comment]
If I squint a little, this looks like this was fixed by #18049, but given the fact that that was resurrected out of #17145, closing this issue got dropped. @dianasaur323 / @a-robinson can you confirm?

**Comment by a-robinson** [comment]
I think you squinted too hard :) I'm not seeing how #18049 would have fixed this. https://github.com/cockroachdb/cockroach/pull/19426 should have, though.
