### ISSUE TITLE
release: 1.1.1

### ISSUE THREAD

**Issue by lego** [cockroachdb/cockroach#19239]
Candidate SHA: f3bc578c89627d02f2ca30f02b835388278a1c83
Deployment status: Pushed to test clusters

[Release process checklist](https://github.com/cockroachdb/cockroach/wiki/Release-Process)

Prep date: `Monday 10/16/2017`
- [x] [Pick a sha](https://github.com/cockroachdb/cockroach/wiki/Release-Process#pick-sha), fill in `Candidate SHA` above.
- [x] [Deploy to test clusters](https://github.com/cockroachdb/cockroach/wiki/Release-Process#deploy-to-test-clusters)
- [x] fill in `Deployment status` above
- Keep an eye on clusters until release date.

Release date: `Thursday 10/19/2017`
- [x] [Check cluster status](https://github.com/cockroachdb/cockroach/wiki/Release-Process#check-cluster)
- [x] [Tag release](https://github.com/cockroachdb/cockroach/wiki/Release-Process#tag-release)
- [x] [Trigger release build](https://github.com/cockroachdb/cockroach/wiki/Release-Process#trigger-build)
- [x] [Check binaries](https://github.com/cockroachdb/cockroach/wiki/Release-Process#check-binaries)

- For stable releases only:
  - [x] Update the [Homebrew Formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/cockroach.rb)
  - [x] Update the image tag in our [Kubernetes configurations](https://github.com/cockroachdb/cockroach/wiki/Release-Process#kubernetes-configurations)
  - [x] Update the version label in our [Red Hat Atomic Docker image](https://github.com/cockroachdb/cockroach/blob/master/build/deploy/rhel/Dockerfile). For major/minor releases, also update the documentation link in the [image's help file](https://github.com/cockroachdb/cockroach/blob/master/build/deploy/rhel/help.1)
  - [x] Announce version to the [registration cluster](https://github.com/cockroachlabs/production#publishing-a-new-release-version)

- [x] Update docs
- [ ] External communications for release
- [x] File issue for next release and assign to release coordinator

**Comment by lego** [comment]
Nominating @jordanlewis for this release :)

**Comment by lego** [comment]
Nominating @vivekmenezes as the next release manager.

**Comment by mberhault** [comment]
We should probably deploy this soon, release is Thursday.
