### ISSUE TITLE
docs: explain cloudfoundry support

### ISSUE THREAD

**Issue by cforce** [cockroachdb/cockroach#19248]
Please provide options for the cloud native application plattform **cloudfoundry** 

* On demand service time for PCF. Option for PCF Multisite/**hybrid**  cloud deployment.
* Bosh deployment for PCF/Kubo
* Cockroach (Open) Service Broker for Azure, AWS deployment,GCP,..

**Comment by a-robinson** [comment]
We have a service broker, but haven't built anything beyond that.

https://github.com/cockroachdb/pcf-crdb-service-broker

**Comment by cforce** [comment]
Where/how is cockroach instantiaed?

**Comment by a-robinson** [comment]
You have to instantiate it yourself, so you get to choose. As stated in the "Prerequisites" section of the repo I linked to: "Set up one or more CockroachDB instances. These don't need to live on CF."

**Comment by knz** [comment]
cc @tim-o @jseldess for next action plan

**Comment by kannanlakshmi** [comment]
There is no next step here until we have more customers ask for either higher level of integration or something else re: what we have today. Jesse, Tim, Alex - let me know if you disagree.
