### ISSUE TITLE
perf: get rid of Txn.BatchIndex

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#19244]
Txn.BatchIndex is never used except at the storage layer [here](https://github.com/cockroachdb/cockroach/blob/751a182b64008fbd75ded7441fe3a003e5aa2a8e/pkg/storage/replica.go#L5091) and [here](https://github.com/cockroachdb/cockroach/blob/751a182b64008fbd75ded7441fe3a003e5aa2a8e/pkg/storage/engine/mvcc.go#L1077) but it's a non-nullable field and so it's always put on the wire unnecessarily.

We can make it nullable and populate it when required using a `sync.Pool` or slab allocator.

**Comment by petermattis** [comment]
The switch to using proto3 for `Transaction` would also eliminate the overhead.

**Comment by tschottdorf** [comment]
Is that something we can consider though? I thought that changed the encoding and was thus a non-starter.

**Comment by petermattis** [comment]
proto3 changes the wire encoding in a backward compatible way. We can't easily change "below Raft protos", but anything on the network is fair game. See some of my recent changes where I provided proto2 and proto3 versions of the same message, using the proto2 for on-disk encoding and proto3 for stuff that goes on the network.

PS Isn't this issue actually about `TxnMeta.BatchIndex`? I think it is still safe to convert that proto to proto3 as `TxnMeta` is not a below Raft proto.

**Comment by nvanbenschoten** [comment]
This was fixed in https://github.com/cockroachdb/cockroach/pull/18930, which converted TxnMeta to a proto3. Txn.BatchIndex is also being deprecated in https://github.com/cockroachdb/cockroach/pull/25728.
