### ISSUE TITLE
sqlccl: backup: result is ambiguous (job lease expired)

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#19252]
While running a backup on v1.1.0-rc.1, I got a result on the sql cli of `pq: result is ambiguous (job lease expired)` yet the job continues to progress in the UI. This is pretty odd behavior to the user, and also a curious error message.

@benesch any ideas what this is?

**Comment by benesch** [comment]
Yep, this means the node coordinating the backup experienced a liveness
failure and so lost its lease to coordinate the job. Another node (or
potentially the same node if it was a momentary blip in liveness) resumed
the job, but the original SQL session no longer knows the status of the job
and is forced to return an ambiguous result.

If this is confusing you, it's definitely confusing our users. I don't have
any concrete suggestions to improve the UX, though.

**Comment by mjibson** [comment]
Ok. Agreed that it's unclear what to do.

**Comment by arjunravinarayan** [comment]
The UX could be improved by changing 
`pq: result is ambiguous (job lease expired)` 
to 
`pq: result is ambiguous (job lease expired). check SHOW JOBS for up-to-date status`
or something of that sort.

**Comment by nstewart** [comment]
Why do we surface that error at all if the cluster is smart enough to keep going? Are we saying some % of the time "result is ambiguous" would actually equal job failure in this scenario?

**Comment by arjunravinarayan** [comment]
Essentially the connection from the job to the client has been lost (and closed). The job is still running, but the client will get no more updates. So something has to be returned. Returning nothing is what happens when the job completes successfully, so we can't do that.

**Comment by benesch** [comment]
We could, in theory, automatically try to reconnect to the job to avoid sending an ambiguous result error for a temporary blip in node liveness. Eventually, though, we have to give up and return an ambiguous result—say, because the node that was originally running the job can no longer communicate with the rest of the cluster.

**Comment by mjibson** [comment]
Closing after the leniency change.
