### ISSUE TITLE
Clarify license text

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#19263]
The top-level `LICENSE` file in this repo is the CCL, which [could be interpreted](https://forum.cockroachlabs.com/t/seeking-clarification-about-licensing/1014) as placing any files without explicit license headers under the CCL instead of the APL (but we intended the source files to be APL by default). I think we should move the CCL text from `LICENSE` to `CCL.txt` and update all references, then put a note describing the use of APL and CCL in `LICENSE`: source files are APL unless otherwise noted, although the `cockroach` binary is covered by the CCL (this might be a good place to mention the `buildoss` target). We should also fill in license headers on files that are missing them. 

Additionally, we have some files which were copied from other projects (pkg/util/interval/llrb_based_interval.go, pkg/util/syncutil/int_map.go, and pkg/sql/parser/) that reference their own "BSD-style" license in a file named "LICENSE"; we need to copy these licenses into the repo and update these references.

**Comment by dianasaur323** [comment]
should we cc @dt and @couchand and @benesch?

**Comment by benesch** [comment]
Ack, happy to take this on if no one else gets to it first.
