### ISSUE TITLE
sql: system tables should *never* allow direct write access

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#19277]
At present, we have the following system tables:

* `namespace`
* `descriptor`
* `users`
* `zones` (#17251)
* `settings`
* `lease`
* `eventlog`
* `rangelog`
* `ui`
* `jobs`
* `web_sessions`

Scarily, only `namespace` and `descriptor` prevent root write access. This permits all manner of crazy things:

```
DELETE FROM system.jobs;
INSERT INTO system.zones (id, config) VALUES (42424242, 'crap protobuf');
INSERT INTO system.settings ... <invalid setting>
INSERT INTO system.eventlog ... <fake event>
```

Many of these tables allow write access because, historically, manual `INSERT`s/`UPDATE`s were the only method of interacting with the tables. E.g., `system.settings` started out this way, but now we have `SET CLUSTER SETTING`. Similarly, the zone config CLI previously needed to run `UPSERT INTO system.zones`, but we're soon getting dedicated SQL syntax for zone configs.

By 1.2, it should be possible to prevent root write access to _every_ system table. Internally, we can execute SQL against these tables by using `security.NodeUser`.

Jira issue: CRDB-5982

**Comment by arctica** [comment]
I find it very nice to be able to do open heart surgery so to speak. I've been able to get some good insight into behaviour by looking into the system tables. Please retain read access from SQL at least and maybe even write for the root user.

**Comment by benesch** [comment]
You'll definitely still have read access as the root user!

**Comment by couchand** [comment]
It seems like there might be value in splitting these system tables up into two types/namespaces.  For things like cluster settings and locations, the table is a convenient model, since it allows user security customization through the normal grant process.  For others that hold internal implementation details, no user should have write access.

**Comment by ajwerner** [comment]
It turns out being able to modify these system tables at times is invaluable but unfortunately also very difficult. My feeling is that we should be more explicit in how we allow manual, unsafe repair to these tables. 

https://github.com/cockroachdb/cockroach/issues/50948

**Comment by ajwerner** [comment]
Of these, `system.jobs` being root writable is scary but we probably want to add an affordance for deleting terminal job rows in a more curated manner. `system.lease` probably shouldn't be writable.

**Comment by ajwerner** [comment]
I feel like we've come around to this being handy in some cases. In others, it is too scary. I'm going to close this as too general.
