### ISSUE TITLE
sql: evaluate and/or specify what happens when the default zone config goes missing or corrupt

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#19282]
Due to #19277, it's possible to have entries in `system.zones` that don't correspond to actual object IDs. For example:

```
INSERT INTO system.zones (424242, SELECT config FROM system.zones WHERE id = 0);
```

Or even delete the root zone config:

```
DELETE FROM system.zones WHERE id = 0;
```

We don't properly test these scenarios right now. We should.

Jira issue: CRDB-5981

**Comment by knz** [comment]
@dt ran the into the latter issue in #30408.

**Comment by dt** [comment]
in my case I have a record with id 0, it just seemed like we can no longer read it?

**Comment by knz** [comment]
@benesch what do you mean with "we should test this"? The fact the things can be deleted is known to be a thing. Do you want to add a test that verifies that yes, indeed, it is possible to make a cluster unusable in that way?

IF you are suggesting that these changes should be disallowed instead, then the title should not be "add a test".

**Comment by benesch** [comment]
It shouldn’t make a cluster unusable though!  Deleting the root zone config should simply use the hard coded default zone config from the config package. Corrupting a zone config should cause a lot of log spam but not break anything. That’s what should be tested. Alternatively we can just lock down `system.zones`.

**Comment by knz** [comment]
David observed a borked zone config struct with num_replicas = 0 but no sub zones. This broke table deletions because it was not found any more by zone lookups.

**Comment by benesch** [comment]
🤦‍♂️ how does one manage to end up in that state? I thought `cockroach zone set` rejected `num_replicas: 0` since the beginning of time. Oh well.

**Comment by knz** [comment]
@benesch direct write to `system.zones`

**Comment by benesch** [comment]
Do you think someone did that??? I guess they could have.

**Comment by knz** [comment]
that or a bug in the zone config validate function that was since corrected

**Comment by knz** [comment]
Who should be the PM on this? @rolandcrosby @awoods187 what do you think?
