### ISSUE TITLE
storage: ranges not being properly split after drastically reducing max range size

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#19296]
I had been gradually decreasing my cluster's max range size while trying to reproduce https://github.com/cockroachdb/cockroach/issues/19236, going from 64MiB to 8Mib to 4Mib to 2Mib before trying to drop down to 64Kib. Splits happened as expected all the way down to 2Mib, leaving the cluster with about 850 ranges, but didn't happen for the last drop down to 64Kib. I can see from the admin UI that the split queue processed a bunch of replicas, but the number of ranges in the cluster didn't actually change, meaning no splits were actually carried out.

1. This is basically impossible to debug without modifying the binary, unless I'm missing something. There aren't even any verbose tracing messages in the split queue.
2. I don't see why splits wouldn't happen, given that the ranges I've looked at are much larger than 64KiB (most appear to be around 450KB), and there are multiple logical keys in each range (given the load generator involved in #19236, there are `26^3`, or `17576`, keys).

**Comment by a-robinson** [comment]
And for reproducibility, this is running the v1.1.0 release.

**Comment by a-robinson** [comment]
Ok, so the gist of what's happening here is that our `MVCCFindSplitKey` code exits eagerly once it's reached the ideal split distance into the range, even if it hasn't yet moved on from the first row. So if the first row (including its old MVCC versions) contains more data than the `targetSize` for the LHS of the range post-split, the code will return the row key for the first row, which higher levels of the stack interpret as meaning that no split should be done.

This is not a good decision if the first row only accounts for a small portion of the current range size. For example, say we have the following row sizes and want to split the range to size 32:

| row | size |
|-----|------|
| 1   | 64   |
| 2   | 64   |
| 3   | 64   |
| 4   | 64   |

The existing code will return row 1's key, which will be interpreted by the higher layers as a "do not split" / "already split" decision, when clearly it'd be better to return row 2 or 3's key.

This issue appears to predate the move to C++ in #18718.

It doesn't look like fixing this should be too hard, but it may incur a performance overhead to have to compare keys against the start key. I'll send out a possible fix.

**Comment by petermattis** [comment]
You can probably avoid comparing against the start key by keeping a count of how many keys have been scanned.

**Comment by a-robinson** [comment]
I'm not sure I quite understand you. A raw count of keys, even if we ignore different MVCC versions of the same key, isn't enough since some of them could be different column families of the same row.

Not being able to rely on `keys.EnsureSafeSplitKey` from within cgo means we'll have to change the logic around a bit. Perhaps we could pass down something like `keys.EnsureSafeSplitKey(desc.StartKey).PrefixEnd()` through cgo as a minimum returnable split key.

**Comment by petermattis** [comment]
Ah, I wasn't thinking about safe split keys. Passing down a minimum returnable split key sounds reasonable.
