### ISSUE TITLE
grpc: the connection is unavailable

### ISSUE THREAD

**Issue by couchand** [cockroachdb/cockroach#19295]
I am again seeing the original underlying issue brought up in #19195.  When starting a new single-node cluster on my MBP and opening the admin UI, every once in a while I get 503 errors on every API call with the message "#grpc: the connection is unavailable" apparently protobuf-encoded (Firefox just shows a bunch of bytes, but Chrome can decode the message)

![screen shot 2017-10-16 at 5 21 14 pm](https://user-images.githubusercontent.com/793969/31635906-86779ed6-b296-11e7-8344-232ba5a2e53d.png)
![screen shot 2017-10-16 at 5 21 30 pm](https://user-images.githubusercontent.com/793969/31635908-868e072a-b296-11e7-8941-53ef36a389a5.png)

Some details from the logfile:

The first few lines:
```
I171016 21:14:41.157873 1 util/log/clog.go:992  [config] file created at: 2017/10/16 21:14:41
I171016 21:14:41.157873 1 util/log/clog.go:992  [config] running on machine: Andrews-MBP
I171016 21:14:41.157873 1 util/log/clog.go:992  [config] binary: CockroachDB CCL v1.2-alpha.20170901-856-gc9b813425-dirty (darwin amd64, built 2017/10/16 21:13:06, go1.9)
I171016 21:14:41.157873 1 util/log/clog.go:992  [config] arguments: [./cockroach start --insecure --store ui-8]
```

The apparent issue arising:

```
I171016 21:14:41.323481 661 sql/event_log.go:103  [n1] Event: "node_join", target: 1, info: {Descriptor:{NodeID:1 Address:{NetworkField:tcp AddressField:Andrews-MBP:26257} Attrs: Locality: ServerVersion:1.1-3} ClusterID:5b0bca77-091e-416c-812c-bd62770c222d StartedAt:1508188481276062975 LastUp:1508188481276062975}

... (several lines of range splits elided) ...

I171016 21:14:41.367837 291 vendor/google.golang.org/grpc/grpclog/grpclog.go:75  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp 192.168.12.166:26257: getsockopt: connection refused"; Reconnecting to {Andrews-MBP:26257 <nil>}
```

One thing that's curious about this is the IP address it's trying to hit, since the result of `ifconfig` on my machine says I'm `192.168.12.137`.

Not sure what other information would be helpful here, let me know if I can provide anything else.

cc @tschottdorf @petermattis

**Comment by tschottdorf** [comment]
See whether you can exacerbate this issue by 1. starting Cockroach 2.
changing the IP of the interface (as could happen during DHCP renewals,
etc). 3) accessing UI through new IP? I think when this happened to me my
laptop had suspended.

> --

-- Tobias

**Comment by couchand** [comment]
@tschottdorf That seems to manifest in a slightly different way: it takes much longer for the 503 responses to come back, and the logs also have a bunch of messages saying:

```
I171017 14:18:17.440728 250 vendor/google.golang.org/grpc/grpclog/grpclog.go:75  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp 192.168.12.137:26257: connect: host is down"; Reconnecting to {Andrews-MBP:26257 <nil>}
```

In addition, I dont't think this reflects the way the issue comes up for me.  It happens immediately after starting a new cluster, so there's not time for my laptop to suspend, for the DHCP lease to refresh, etc.

**Comment by couchand** [comment]
Ok, I've found the source of the issue.  There were _two machines_ on the local network advertising _the same hostname_.  Sometimes the DNS lookup would resolve to my local machine, and sometimes it would resolve to the other one.  When it resolved to my local machine, everything was groovy.  When it resolved to the other one, all behavior other than the admin UI was fine, but the admin UI was broken because grpc-gateway tried making calls to the other machine rather than the local one.

It sounds like most local RPC calls special case a single-node cluster to just use the local loopback, but this isn't the case for the admin UI.  @bdarnell seemed to think there was an issue to change this so grpc-gateway has consistent behavior, but I am unable to find that.

So it seems like mostly this was an error of local configuration, which, while very strange for several reasons, is not really the domain of CockroachDB to identify or fix (though if anyone has ideas on how to make the user experience here better, I'd be interested).  However, this has highlighted what seems to be a  legitimate problem: running every HTTP request through a second round of the network stack to make a gRPC call just to hit the local host.

This makes me wonder, why would we need to make a gRPC call to fulfill an HTTP request at all?  Looking back through old issues, I can't seem to find the discussion on why this approach was taken.  The various comments I've seen indicate that it was an attempt to DRY up any admin and status endpoints which might be accessed from both the CLI and the web.  Though that's a good goal, if the cost of this is to disadvantage the HTTP endpoints this doesn't seem like an ideal solution.

**Comment by couchand** [comment]
Also see discussion on #17145 regarding always making grpc-gateway use a local connection.

**Comment by couchand** [comment]
Also see #10873, which is basically a dupe of the original issue.

**Comment by couchand** [comment]
Given that the changes I've suggested are being considered elsewhere, I'm going ahead and closing this issue.
