### ISSUE TITLE
sql: special characters in column names are not handled properly

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#19307]
Identified by @bdarnell in https://github.com/cockroachdb/cockroach/pull/18576#issuecomment-330672033 and https://github.com/cockroachdb/cockroach/pull/18576#issuecomment-336720926:

> Do CSV readers interpret \n in this way? My understanding is that the way to represent a cell containing a newline in a CSV is to enclose the value in quotes and then include the literal newline

This pertains to the following output by the csv and tsv formatters:

```sql
> \set display_format csv
> select e'ab\ncd' as "ef
gh";
```

result:

```
"ef\ngh"
"ab
cd"
```

i.e. the value part is properly formatted according to tsv/csv rules (value contains literal newline) but not the column name part.

**Comment by adamyaoqinglin** [comment]
Hey, @knz , I want to code for this issue. However, I am curious whether this issue should be suspend until #18576 pushed.

**Comment by knz** [comment]
I have investigated this further. The problem is not in the formatter -- the problem is in the SQL layer. Special characters in column names are escaped internally, which is not the expected behavior (pg doesn't). Removed the "easy" label.

**Comment by knz** [comment]
After investigating yet further, it seems that the output via pgwire is still fine. But the data presented to the formatter isn't. Perhaps the issue is in `pq`. Investigating further.
