### ISSUE TITLE
how to deal with failure

### ISSUE THREAD

**Issue by Kevin-GuanJian** [cockroachdb/cockroach#1930]
how to deal with a node failure or zone failure (e.g. fault detection and fault recovery)?
@spencerkimball @bdarnell

**Comment by bdarnell** [comment]
This is still a work in progress. @BramGruneir is working on a system to detect failed nodes and replicate their ranges to other nodes.

**Comment by BramGruneir** [comment]
Hey @Kevin-GuanJian,
I'm just getting started on this but expect to see some progress very soon. But if you have any question, please ask away.

**Comment by Kevin-GuanJian** [comment]
Hey @BramGruneir thanks for your reply
l'm very concerned about this feature.
Do you want to use out-of-band system or just implement yourself use existing distributed mechanism？I want to know your plan or design.

**Comment by BramGruneir** [comment]
The design at this point is just some scribbled notes I have in a notebook here from a discussion with Spencer and Ben.  But I can give you the gist of it.  We're going with our own internal system.
The plan is to use the gossip system to find out when a node has been offline for some time (somewhere in the range of around 5 to 10 mins, this value may be tunable or tied to another value) and assume that it's dead.  All replicas (or perhaps only the raft leaders or the one with the leader lease or perhaps some other designation) will occasionally scan for the health of the other replicas.  If any notice that they have a replica on a dead node and still have a consensus of alive replicas, it will start the process of adding in a new replica and removing the old one.
The allocation of a new replica is already in the system, so it should be fairly straightforward.  Obviously, there were be a number optimizations and whatnot that will be needed.
What are you concerns?

**Comment by Kevin-GuanJian** [comment]
same plan, but may have some problems,
As fault detection, do you mean anyone connects to the dead node as the owner of the failure, broadcast it via gossip and gc the replicas? but this may can't distinguish the network partition and the real dead

**Comment by BramGruneir** [comment]
Gossip has the last time a node gossiped its status.  Based on this, we can know when a node is no longer reporting its status.

**Comment by bdarnell** [comment]
In addition to node-level health, we need to look at raft log positions (probably at less frequent intervals). Since we are not implementing segmented storage (#1866), it is possible for a replica to be stuck in an uninitialized state, and if this condition doesn't resolve itself then the replica will need to be moved away. This could also detect network partitions.

**Comment by Kevin-GuanJian** [comment]
@bdarnell that's a good idea, I need this feature, and also working on this, just lack of detection,hope to see impementation of segmented storage soon.

**Comment by bdarnell** [comment]
We've decided not to implement segmented storage; see the discussion in #1866.

**Comment by Kevin-GuanJian** [comment]
your opinion is use the raft index far behind leader to detect network partitions, did i get the point?

**Comment by bdarnell** [comment]
The raft log index will be used to detect several kinds of problems, including (some) network partitions. It won't be able to detect all partitions (for example, if all three members of a range can talk to each other but other nodes can't talk to them, then the ranges will be fine but we will experience failures or queuing at the DistSender), but it should be able to detect the ones that can be solved with rebalancing.

**Comment by Kevin-GuanJian** [comment]
I've some other questions
1、In addition to detect node failure, just use gossip maybe flawed,  (assume a scenario : nodeA  crash and some nodes detect this, but these node also crashed before gossip nodeA's failure, the other nodes will never get nodeA's failure via gossip),so maybe raft log positions is necessory, or use other entity?
2、you know, when a node with so many ranges crash, reboot it before migrating the replicas is the cheapest way, so who is more appropriate in charge of  this ? and how to cooperate with auto rebalance?
3、If reboot can not solve the problem, who is more appropriate in charge of cleaning the invalid data?

**Comment by bdarnell** [comment]
1. Gossip reports healthy nodes, not unhealthy ones. Each node gossips its own health periodically, and it is considered unhealthy when it hasn't been heard from in a long time.
2. Cockroach itself will not be able to reboot failed nodes. A node must be dead for at least X minutes before the repair process starts, so there is time for a reboot to occur. This is a tradeoff between minimizing "wasted" repair work and ensuring that the repair process completes before another node can fail.
3. Currently the `rangeGCQueue` will examine the node's ranges one at a time and remove them if they are no longer live. This could be optimized in the case of a node that recovers after a long downtime, since most of its ranges can be presumed dead.

**Comment by Kevin-GuanJian** [comment]
Ah，i have got it wrong，forget it.
 what is your plan to control cockroach node life cycle（e.g “boot” or reboot）, use third-party system？

**Comment by BramGruneir** [comment]
For bringing a new node online, it just needs to be pointed at another cockroach node and it will become part of the cluster.  You can look at our documentation on how that works, but it should be straightforward.
For rebooting, that will depend on the environment that you're running in. And for now, that's beyond our scope.

**Comment by petermattis** [comment]
@BramGruneir, @bdarnell Is there specific work remaining here? If yes, perhaps we should create some new issues detailing that work and close this issue.

**Comment by bdarnell** [comment]
This was implemented as a part of the repair queue.
