### ISSUE TITLE
build: Lint against `if err != nil { return nil }`

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#19316]
https://github.com/cockroachdb/cockroach/issues/19172#issuecomment-337061024 is the most recent occurrence of a bug we've seen before:

```
if err != nil {
    return nil
}
```

Most of the time we want to return an error if we see a non-nil error anywhere (usually `err` itself or a wrapper around it). Sometimes we do mean to swallow an error and return nil, but this is rare and should have a comment when it occurs. We should have a linter to detect this case (maybe contribute it upstream to golint/staticcheck/something).

More precisely, the linter should look for an if statement whose condition is comparing a value of type `error` against nil, then returning `nil` as a  return value of type `error`. If there is any comment inside the `if` block, it should be allowed.

**Comment by tschottdorf** [comment]
As part of #19172 I was hoping to just bang this out, but now it looks like it needs more time than I imagined. Here's my (non-compiling) WIP:

```go
diff --git a/build/style_test.go b/build/style_test.go
index 9ce8eb3b1..bba14a420 100644
--- a/build/style_test.go
+++ b/build/style_test.go
@@ -1188,6 +1188,39 @@ func checkConvertFloatToUnsigned(j *lint.Job) {
 	})
 }
 
+func containsErrComparison(j *lint.Job, expr ast.Expr) {
+	binExpr, ok := expr.(*ast.BinaryExpr)
+	if !ok || binExpr.Op != token.NEQ {
+		return
+	}
+	for _, pair := range [2][2]ast.Expr{{binExpr.X, binExpr.Y}, {binExpr.Y, binExpr.X}} {
+		errExpr, nilExpr := pair[0], pair[1]
+		typ := j.Program.Info.TypeOf(errExpr)
+		pkg := j.Program.Info.ObjectOf(errExpr).Package()
+		obj, _, _ := types.LookupFieldOrMethod(typ, true, pkg, "Error")
+		if obj == nil {
+			continue
+		}
+		if nilExpr.String() != "nil" {
+			continue
+		}
+		j.Errorf(expr, "foo")
+	}
+}
+
+func checkReturnNilWithErr(j *lint.Job) {
+	forAllFiles(j, func(n ast.Node) bool {
+		ifStmt, ok := n.(*ast.IfStmt)
+		if !ok {
+			return true
+		}
+		if !containsErrComparison(j, ifStmt.Cond) {
+			return true
+		}
+		return true
+	})
+}
+
 func walkForStmts(n ast.Node, fn func(ast.Stmt) bool) bool {
 	fr, ok := n.(*ast.ForStmt)
 	if !ok {

```

**Comment by bdarnell** [comment]
https://github.com/cockroachdb/cockroach/issues/43067#issuecomment-566289735 looks like another instance of this.
