### ISSUE TITLE
highlight non-default values in cluster settings

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#19317]
Breaking out an acceptance criteria item from this open issue https://github.com/cockroachdb/cockroach/issues/18696 

Looks like overall though, this feature is almost ready for acceptance testing, so I think we can start documenting it @jseldess

**Comment by dianasaur323** [comment]
Actually, let me close out this issue for now - I might be able to combine it with some other cluster setting work.

**Comment by dt** [comment]
`SELECT * FROM system.settings` only shows overrides.

**Comment by tschottdorf** [comment]
Though that also outputs values that aren't fit for human consumption, such
as `version`.

> --

-- Tobias
