### ISSUE TITLE
Would not repleace import code while regenerate golang protobuf source code on linux platform.

### ISSUE THREAD

**Issue by XisiHuang** [cockroachdb/cockroach#1932]
I modified api.proto, while I rebuild the project after regenerate golang source code with command 'make -C .. -f cockroach/build/protobuf.mk', I got follow error message:
proto/api.pb.go:59:8: cannot find package "github.com/cockroachdb/fmt" in any of:
        /home/ccb/tools/go/src/github.com/cockroachdb/fmt (from $GOROOT)
        /home/ccb/git-warehouse/cockroachdb/src/github.com/cockroachdb/fmt (from $GOPATH)

because script protobuf.mk did not repleace "github.com/cockroachdb/fmt" with "fmt", I find sed 's option '-E' is work on Mac or FreeBSD os, We should with '-r' option while the os  platform is Linux .

**Comment by tamird** [comment]
Looks like GNU sed should accept `-E` - it's an undocumented alias for `-r`. What version of `sed` are you using? What linux distribution are you using?

**Comment by XisiHuang** [comment]
Suse 11 OS
http://www.grymoire.com/Unix/Sed.html#uh-62f3

**Comment by tamird** [comment]
I'm not sure why your sed isn't working, but GNU sed supports `-E`: http://git.savannah.gnu.org/cgit/sed.git/tree/sed/sed.c#n314

**Comment by XisiHuang** [comment]
I use GNU sed version 4.1.5  and community use 4.2.2.  There is problem in my version.
