### ISSUE TITLE
sql: placeholder in RHS of ANY doesn't get type inferred

### ISSUE THREAD

**Issue by jorise7** [cockroachdb/cockroach#19338]
```
CREATE TABLE test(
    names  STRING ARRAY NOT NULL DEFAULT ARRAY[]
);
```
```
db.Query(`SELECT * FROM test WHERE 'a'=ANY(names);`)
```
it works.

```
db.Query(`SELECT * FROM test WHERE $1=ANY(names);`, []interface{ "a" });
```
it doesn't work, i got this error:
pq: could not determine data type of placeholder $1

cockroach 1.1   stable
pq / golang

**Comment by jordanlewis** [comment]
Hi @jorise7, thanks for the report. This is a deficiency in our type-checker.

As a workaround, you should be able to use a type assertion on the placeholder:

`SELECT * FROM test WHERE $1:::STRING=ANY(names)`

**Comment by asubiotto** [comment]
Closing due to age. This issue is also tracked in #43007
