### ISSUE TITLE
ui: database page loading state should be better

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#19347]
Here's the loading states:

![image](https://user-images.githubusercontent.com/5768024/31734338-6587dc32-b40c-11e7-934c-2e6d20766550.png)

and: 

![image](https://user-images.githubusercontent.com/5768024/31734352-73200784-b40c-11e7-9193-1f34f86808b9.png)

**Comment by arctica** [comment]
Please also provide a way to refresh the values without reloading the whole page (which takes a bit of time as there's this problem of it redownloading several MiB of data each time). The other admin pages auto refresh but this one seems static.

**Comment by dianasaur323** [comment]
hmm.. interesting point. Thanks for the feedback @arctica

**Comment by vilterp** [comment]
This is because it makes a lot of requests: two per table. #22941 tracks changing that to load in one shot; that'll fix this.

Re: refreshing — that's an issue which applies to nearly every page in the admin ui. Filed #24085 to track it.
