### ISSUE TITLE
sql: incorrect key property for unique indexes with nullable columns

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#19343]
The current code assumes that a UNIQUE index implies distinct values. But that's not quite true because of NULL columns - a unique index operates under the assumption that NULL != NULL so it allows multiple NULL values.

One place where we use the key information is to elide DISTINCT:

```sql
create table kv (k INT PRIMARY KEY, v INT, UNIQUE INDEX idx(v));

root@:26257/test> select distinct * from (select v from kv);
+------+
|  v   |
+------+
|    1 |
|    2 |
| NULL |
+------+
(3 rows)

root@:26257/test> select distinct * from (select v from kv@idx);
+------+
|  v   |
+------+
| NULL |
| NULL |
| NULL |
|    1 |
|    2 |
+------+
(5 rows)
```

We incorrectly elide the distinctNode:

```
root@:26257/test> explain select distinct * from (select v from kv);
+-------+----------+-------+-------------+
| Level |   Type   | Field | Description |
+-------+----------+-------+-------------+
|     0 | distinct |       |             |
|     1 | render   |       |             |
|     2 | scan     |       |             |
|     2 |          | table | kv@primary  |
|     2 |          | spans | ALL         |
+-------+----------+-------+-------------+

root@:26257/test> explain select distinct * from (select v from kv@idx);
+-------+--------+-------+-------------+
| Level |  Type  | Field | Description |
+-------+--------+-------+-------------+
|     0 | render |       |             |
|     1 | scan   |       |             |
|     1 |        | table | kv@idx      |
|     1 |        | spans | ALL         |
+-------+--------+-------+-------------+
```

**Comment by petermattis** [comment]
Note that in the second example, we can elide the distinct in a slightly different query:

```
select distinct * from (select v from kv@idx where v is not null)
```

Any predicate which is NULL-intolerant (never allows a NULL value to evaluate to true) allows us to utilize the UNIQUE index as a key. I think you're aware of this from other discussions, just recording for others.

**Comment by RaduBerinde** [comment]
Yes, and in fact most common predicates (e.g. `x = 1`, `x > 10`, `x IN [..]`) are NULL-intolerant so this is an important case. I'm not sure what capabilities of figuring out NULL-intolerance we have currently though.

**Comment by petermattis** [comment]
I don't think we have any tooling for NULL-intolerance right now, but it wouldn't be difficult to add. We don't even need to be 100% correct, just no false positives.
