### ISSUE TITLE
RESTORE: restore revisions when restoring full mvcc backups

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#19342]
Currently restore only restores the latest revision in a backup -- for latest-only backups that is all that they contain and for full backups, we pick only the latest as of the restored time (either the backup end time or an AS OF SYSTEM TIME clause).

This means that time-travel over the _restored_ data isn't possible. However those revisions are _in_ the backup for full mvcc backups, so we could potentially enable that if we did restore them. We'd need to add an option and then do something to prevent them from immediately being GCed, and potentially some other considerations as well.

**Comment by mjibson** [comment]
Until there's a user request around this I'm not convinced it's useful.

**Comment by dianasaur323** [comment]
@mjibson I would agree with you on that
