### ISSUE TITLE
support for uppercase column names by default

### ISSUE THREAD

**Issue by jozn** [cockroachdb/cockroach#19359]
currently, cockroachdb  lowercases every sql column names:
```
CREATE TABLE groups (
GroupId INT PRIMARY KEY,
Name STRING);
```
now querying the table
`SELECT * FROM groups;`

will return the following - with column names lowercased:
```+---------+------+
| groupid | name |
+---------+------+
+---------+------+
(0 rows)
```
what i expect is:
```+---------+------+
| GroupId | Name |
+---------+------+
+---------+------+
(0 rows)
```
This is the behaviors of PostgreSQL and cockroachdb follows the same path, but i have arguments why lowercasing columns names is not a good idea for a new database.

Both Mysql and Sql Server respect uppercase, we currently use mysql and all hundreds of columns are in uppercase.
Most of the programing languages using camelCase or CamelCase for structs or classes fields: Go, java, swfit, javascripts, c# ... . Mapping one-to-one of the table's columns to class or struct fields are common. we use go language and mysql we use the same namings for both tables and structs. 
when the database expects and restricts names be lowercase or names be quoted things get very annoying.

You can say that there is a solution for this: put everything in the quote, but quoting is good when we want to have a table like this:
```
CREATE TABLE groups (
GroupId INT PRIMARY KEY,
"have space or $% * () " STRING,
"中華" STRING,
"العری" STRING,
"👍" STRING
);
```

but for uppercase, this should be supported by default.

What About compatibility with PostgreSQL if cockroachdb support uppercase?
A desire to cockroachdb be compatible with PostgreSQL is a valid one, but try to make adopt every behavior of it while those are inferior are not good decisions, most of the user will not get affected by this change, but this change will make it easier for those that are coming from other databases engines.

in PostgreSQL community it is recommended to use lowercase for column names, so they will not get affected by this change.
those that use uppercase in the quote they will not get affected by this change.

I think it will be misstep for a new database to not support uppercase in this time - with so many programming languages are mixedCase -just for out of desire to be compatible with every edge of a  database that decided to lower case everything 20 years ago, in an era that snake_case was common. 
Implementing this that is trivial too.

And if you guys decided to support uppercase for column names, it would be great if you add support for tables with uppercase too.

Update: cockroachdb can give an optional **flag** to start the database without case-folding names like the way Mysql and Sql Server works, this way it is both compatible with postgresql and give support for mixed casing.

**Comment by jozn** [comment]
And i should mention that we use a custom orm-like code generator that looks at the database and generates all the structs and query builder for us in the Go, and some java codes, and protocol buffer. something like https://github.com/xo/xo.

**Comment by justinj** [comment]
Hi @jozn, I believe that we have this behaviour for Postgres compatibility, and it's not something that we can reasonably change. However, if you want your column names to respect casing, you can wrap them in double quotes:

```
root@:26257/> select 123 A, 123 "B";
+-----+-----+
|  a  |  B  |
+-----+-----+
| 123 | 123 |
+-----+-----+
```
Does that do what you need?

**Comment by jozn** [comment]
Hi @justinj, thanks for your response.
I dug more into issues and found that this behavior has already reported as a bug in #17616, and there is valid arguments in there too.
This is a valid and wise argument to cockroachdb be compatible with Postgresql to support existing tools around that.

In this case, cockroachdb  can give an optional **flag** to start the database without case-folding names like the way Mysql and Sql Server do. (the other two databases that i'm aware of).

We are looking to adapt CDB for some of our tables that are growing rapidly, 
We have hundreds of columns in our tables and all of them are in mixed cases, quoting every column is a pain and will slow down our adaptation of CDB. I look at CDB as potentially our future goto database, as we must first see how this DB gets evolved.

**Comment by jordanlewis** [comment]
We're not going to change our behavior here, and I don't think we'll be adding a flag to change this any time soon, as it's fundamental to our Postgres-based syntax. We require that you quote column names.
