### ISSUE TITLE
backup/restore/*: local filesystem interactions using network-supplied paths

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#19357]
The initial implementation of backup and restore read and wrote to local files, not unlike something like `pg_dump`, except that it is executed by the server, not a client process.

We added various cloud providers, and have frequently said we discourage using a node's local system due to incompatibility with distributed clusters (unless a network-filesystem is used), but we've kept local file support around and use it when running a single node for testing or in our automated tests, as it is significantly simpler and easier than adding external system.

However, despite our discouraging, it sometimes confuses users of multi-node deployments.

Important though **allowing direct local file system interactions with paths supplied from from network requests raises security concerns.**

Indeed, that is why we restricted the BACKUP and RESTORE statements to root-only even though we also check the SELECT or CREATE privs on the tables/databases.

Obviously there is also whatever OS and FS permissions restrictions that apply to the path, the process and its shell user, though those are highly deployment-specific and may be missing/overlooked.

One suggestion is that this functionality should be gated and require an operator to enable/disable it:

- A cluster setting to enable/disable local file access it would not significantly mitigate the security concerns, as cluster settings can be set by the root SQL user anyway.

- A cli flag to enable/disable or whitelist base paths could work, but would require a cluster restart to change -- this could be concern if the motivation to BACKUP or RESTORE is part of an incident that may be exacerbated by a cluster restart.

If we go with some scheme of whitelisted paths supplied via the cli, we potentially could mitigate the "you must restart to change this" limitation by including some path(s) by default (e.g. maybe a subdirectory of the store directory) so that an operator has _some_ option (including symlinking from there) if they cannot restart at the moment.

If we add whitelisted prefixes, we'd also need to decide if "local" paths specified in commands/queries are absolute or relative to the whitelisted prefix. If multiple locations can be whitelisted, how do we pick?

If we wanted to get fancy, we potentially could also potentially add the support to update flags without a restart, via a file + HUP or local socket or, for that matter, could even add cluster settings that can only be updated via session on a local socket -- though there you'd still be trusting other nodes to have done the same when they send the gossip update, so a compromised node or cert is a risk.

**Comment by bdarnell** [comment]
I'd prefer a command-line flag, which can default to a subdirectory of the first store. I think that the paths specified in commands should be relative to the designated directory instead of absolute. I don't think it's worth the trouble to be able to specify multiple locations; admins can simulate this with symlink farms.

**Comment by dt** [comment]
👍 

Over to @dianasaur323 for feedback on the ux change:

Motivation for adding this restriction is that there may well be people who can connect to your database (either intentionally or not) who can't access your computer directly, but if we let the database read and write arbitrary files, we've given them a way in. There are a couple mitigating factors (permissions, currently hard to write anything other than compressed SSTs, etc), but locking it down means we don't need to count on those or worry about what we may have missed.

The current concrete proposal here is restrict all local file interactions from backup/restore/import to a designated directory, controlled via a new command line flag. Attempts to use paths anywhere outside that directory would result in an error.

The default value of this flag would be some subdirectory e.g. `exports` or `extern` under the (first?) store directory.

An administrator can change this to e.g. `/mnt/backups/db/` if they wish, though this will require a restart.

Most filesystems also support some form of aliases, e.g. "symlinks", that can also be used to make one path appear under another path for instance, in the above example, you could symlink to `/mnt/backups/db/` from inside the designated store directory. This could allow using whatever paths an administrator wants without requiring a restart.

This change potentially adds a little extra friction to on boarding with e.g. `IMPORT` since something like `IMPORT ... CSV DATA /home/david/Downloads/demo.csv` will no longer work, but it we'd just need to say something like "copy or symlink the csv into /home/david/cockroach-data/extern".

**Comment by dianasaur323** [comment]
Just adding in what we decided yesterday - go with the CLI whitelist, but still check for multi-node using local. Also, make sure to emit a reasonable warning message so that users know how to adjust their commands.

**Comment by dt** [comment]
Fixed in #19865
