### ISSUE TITLE
ui: "New version available" on a new pure 1.1 cluster

### ISSUE THREAD

**Issue by jeromew** [cockroachdb/cockroach#19376]
**BUG REPORT**

I installed a new cluster from scratch using 1.1.0 version (not an upgrade from 1.0.6)

When I initialize the cluster, I get the following events in the UI

```
Node Joined: Node 1 joined the cluster | a few secs ago
-- | --
Cluster Setting Changed: User node set trace.debug.enable to false | a few secs ago
Cluster Setting Changed: User node set version to 1.0-3 | a few secs ago
Cluster Setting Changed: User node set diagnostics.reporting.enabled to true | a few secs ago
Schema Change: User node began a schema change to alter table eventlog with ID 0 | a few secs ago


```

And then the "New Version available" tip appears .

I suspect there might be something wrong with the fact that the node sets version "1.0-3" ? Is this expected ?

Don't hesitate to ask if you need more info.

**Comment by mberhault** [comment]
v1.1.1 is in the process of being released. The binaries are built, and the service clusters use to find new versions has been updated.
However, we haven't pushed the release notes yet. We've adjusted our release process to make sure we don't update the version until everything is ready.

**Comment by mberhault** [comment]
Release notes for v1.1.1 are now available: https://www.cockroachlabs.com/docs/releases/v1.1.1.html
