### ISSUE TITLE
backupccl: better handle restoring interleaved tables

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#19377]
Currently, you have to restore all tables involved in interleaving. We should improve the UX of restoring interleaved tables.

**Comment by dianasaur323** [comment]
I'm not sure I'm convinced we really need to do this in the 2.1 timeframe. Punting to later 

cc @mjibson and @dt

**Comment by mwang1026** [comment]
We currently allow restoring of whole interleaved hierarchy. We're not going to invest further given plans to deprecate interleaved. cc @jordanlewis
