### ISSUE TITLE
build: consider using: dep ensure -no-vendor -dry-run

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#19383]
This is a recent feature in dep (https://github.com/golang/dep/releases/tag/v0.3.2) and seems like it may be good in a linting step to verify things are in sync.

**Comment by tamird** [comment]
This checks the lock file, but not the vendor directory...?

**Comment by dt** [comment]
What does this get us over the current linter of running a non-dry-run ensure and asserting nothing changed?

**Comment by mjibson** [comment]
Dunno, just read the release notes and thought it had the possibility to be useful. I wasn't aware of what we did already, and I thought we weren't doing a full check because I recall previous problems with vendor getting out of sync.

**Comment by dt** [comment]
it did get out of sync -- we bumped the version of `dep` which seemed to fix that though.

I think our current check is stricter than `--dry-run`, but a little more expensive. We only run it on change sets that touch `gopkg.lock` though, so i'm pretty happy with the current lint situation.
