### ISSUE TITLE
weird QualifiedName.Base ("\xc8rray")  panics on reproduce

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#1938]
culprit: `Base: (parser.Name) (len=5) "\xc8rray",`
full AST and error: see
https://gist.github.com/tschottdorf/3913a87b72061b2f6f65

(#gofuzz @dvyukov)

**Comment by petermattis** [comment]
Can you add the original query that fails to parse?

**Comment by tschottdorf** [comment]
I didn't save that unfortunately. But looking at the AST again, it's got an `ArrayIndirection` and looks like it crashed there as well - so maybe it's just a dupe of #1941?

**Comment by petermattis** [comment]
I'm not able to reproduce an error here. I'm going to close. Reopen or create a new issue if you see this again and be sure to provide the original query.
