### ISSUE TITLE
sqlccl: restore of `load csv` data failed

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#19399]
Ran `load csv` on some data, then tried to RESTORE. Failed with:

importing 324 ranges: addsstable [/Table/56/9/2/20/289690669019889664/0,/Table/56/9/3/12/289690135848779776/0/NULL): verifying sstable data: key /Table/56/9/2/63/289688124228730880/0 not in request range [/Table/56/9/2/20/289690669019889664/0,/Table/56/9/2/63/289688124228730880)

Initial CSV data, schema, and `load csv` output available on request.

**Comment by dt** [comment]
#17819
