### ISSUE TITLE
cli: `--cache` and `--max-sql-memory` are tricky to use with percentages

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#19393]
Encountered this on gitter: cockroach was configured through systemd with `--cache=25%` and `--max-sql-memory=25%` which are reasonable values.
However, systemd uses `%` inside configs, so the proper way to escape it is to use `%%`.

The cluster started properly, but any attempt at a sql connection failed with
```
Error: unable to connect or connection lost.
Please check the address and credentials such as certificates (if attempting to
communicate with a secure cluster).
EOF
Failed running "sql"`
```

We dug around thinking it was certificates or `--host`, but no. We finally saw:
```
E171019 22:30:22.461609 51001 server/server.go:753 [n1,client=[::1]:54828] unable to pre-allocate 21504 bytes for this connection: root: memory budget exceeded: 112640 bytes requested, 25 bytes in budget
```

A few things we could/should do here:
1. document that `%` may need to be escaped (CC: @jseldess)
1. warn/error on `start` for really really small values (me I guess?)
1. return a better error message on connection failure due to memory budgets (CC: @knz)

**Comment by jseldess** [comment]
@mberhault, does this same guidance apply to other `start` flags that accept percentages as well (e.g., `--max-disk-temp-storage=5%`, `--store=path=/mnt/ssd01,size=20%`)?

**Comment by mberhault** [comment]
Yup, pretty much all of them, at least the potential need for escaping. We may also want to try to have sensible warnings for "odd" values whenever we can.

**Comment by knz** [comment]
An alternative would be to change the syntax to take a fraction, e.g. `.25` to mean '25%'.

**Comment by bdarnell** [comment]
This came up on the forum again: https://forum.cockroachlabs.com/t/startup-init-file-command/1340/8

Maybe we should recognize the word `percent` as an alias for `%`? `--cache=25percent`. This would avoid encoding confusion, but we'd need to use it consistently throughout the docs and examples in order for it to be more discoverable than escaping the `%` with `%%` (since most people running into this aren't even aware that it's a potential issue and the punctuation is hard to search for)

**Comment by knz** [comment]
I'm not fond of the word "percent" but I champion support for an alternate syntax.

What's wrong with supporting `--cache=.25` as an alias to 25%? It's both mathematically accurate and easy to explain/remember.

**Comment by bdarnell** [comment]
Using fractions for this sounds good to me.
