### ISSUE TITLE
500 response code in TestStatusLocalLogs

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#1940]
Discovered in #1839.

https://circleci.com/gh/cockroachdb/cockroach/5404
https://circle-artifacts.com/gh/cockroachdb/cockroach/5404/artifacts/0/tmp/circle-artifacts.oO88rMP/testrace.log

**Comment by tamird** [comment]
Another instance.

https://circleci.com/gh/cockroachdb/cockroach/5526
https://circle-artifacts.com/gh/cockroachdb/cockroach/5526/artifacts/0/tmp/circle-artifacts.F4In60q/testrace.log

**Comment by BramGruneir** [comment]
Yeah, I've seen it a few times now.  I'll investigate.

**Comment by tamird** [comment]
Now the test times out (with the retry logic added):

relevant logs: https://gist.github.com/tamird/6df602f3931e4024e23d

build: https://circleci.com/gh/cockroachdb/cockroach/6313
test.log: https://circle-artifacts.com/gh/cockroachdb/cockroach/6313/artifacts/0/tmp/circle-artifacts.v625idu/test.log

**Comment by tamird** [comment]
OK that last report looks like just broken retry. Should be fixed in #2230, but this issue remains valid afaik.

**Comment by BramGruneir** [comment]
Hopefully this should give us more insight into why we're getting a timeout. It seems to just get stuck occasionally.

**Comment by tamird** [comment]
I'm actually concerned that we won't see failures at all because the retry logic will paper over the issue. Remains to be seen, though.

**Comment by tamird** [comment]
Here we go, another one:
https://circleci.com/gh/cockroachdb/cockroach/6858
https://circle-artifacts.com/gh/cockroachdb/cockroach/6858/artifacts/0/tmp/circle-artifacts.c9cyXRx/testrace.log

**Comment by tamird** [comment]
Another one. https://circleci.com/gh/cockroachdb/cockroach/6949
https://circle-artifacts.com/gh/cockroachdb/cockroach/6949/artifacts/0/tmp/circle-artifacts.LtvEvpn/testrace.log

Looks like a bunch of timeouts:
```
	status_test.go:230: could not GET https://127.0.0.1:46511/_status/logs/local?level=INFO&pattern=Info|Error|Warning - Get https://127.0.0.1:46511/_status/logs/local?level=INFO&pattern=Info|Error|Warning: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
	status_test.go:230: could not GET https://127.0.0.1:46511/_status/logs/local?level=INFO&pattern=Info|Error|Warning - Get https://127.0.0.1:46511/_status/logs/local?level=INFO&pattern=Info|Error|Warning: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
	status_test.go:230: could not GET https://127.0.0.1:46511/_status/logs/local?level=INFO&pattern=Info|Error|Warning - Get https://127.0.0.1:46511/_status/logs/local?level=INFO&pattern=Info|Error|Warning: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
	status_test.go:230: could not GET https://127.0.0.1:46511/_status/logs/local?level=INFO&pattern=Info|Error|Warning - Get https://127.0.0.1:46511/_status/logs/local?level=INFO&pattern=Info|Error|Warning: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
	status_test.go:230: could not GET https://127.0.0.1:46511/_status/logs/local?level=INFO&pattern=Info|Error|Warning - Get https://127.0.0.1:46511/_status/logs/local?level=INFO&pattern=Info|Error|Warning: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
	status_test.go:251: There was an error retrieving https://127.0.0.1:46511/_status/logs/local?level=INFO&pattern=Info|Error|Warning
```

Maybe the timeout is too short for a race build?

**Comment by tschottdorf** [comment]
do we know what the timeout is? If it's relatively low maybe the test is just flaky on the slow machines (unlikely if it's something like `10s` though).

**Comment by tamird** [comment]
3 seconds

**Comment by tschottdorf** [comment]
hmm. Could picture that being too slow sometimes. Should increase that if we can.

**Comment by tamird** [comment]
Closing in favour of #2440.
