### ISSUE TITLE
release:  1.2-alpha.20171026

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#19408]
Candidate SHA: 40ad8d55809c6936be170b9214db12019dc2a4f6
Deployment status: adriatic, omega.

[Release process checklist](https://github.com/cockroachdb/cockroach/wiki/Release-Process)

Prep date: 2017-10-20
- [x] [Pick a sha](https://github.com/cockroachdb/cockroach/wiki/Release-Process#pick-sha), fill in `Candidate SHA` above.
- [x] [Deploy to test clusters](https://github.com/cockroachdb/cockroach/wiki/Release-Process#deploy-to-test-clusters)
- [x] fill in `Deployment status` above
- Keep an eye on clusters until release date.

Release date: `2017-10-26`
- [x] [Check cluster status](https://github.com/cockroachdb/cockroach/wiki/Release-Process#check-cluster)
- [x] [Tag release](https://github.com/cockroachdb/cockroach/wiki/Release-Process#tag-release)
- [x] [Trigger release build](https://github.com/cockroachdb/cockroach/wiki/Release-Process#trigger-build)
- [x] [Check binaries](https://github.com/cockroachdb/cockroach/wiki/Release-Process#check-binaries): kinda broken: libtinfo on some linux versions, last-minute patches for windows, no idea about docker.

- [x] Update docs
- [x] External communications for release
- [x] File issue for next release and assign to release coordinator

**Comment by dt** [comment]
okay, over to docs

**Comment by bdarnell** [comment]
Docs are live: https://www.cockroachlabs.com/docs/releases/v1.2-alpha.20171026.html

**Comment by dt** [comment]
#19590
