### ISSUE TITLE
"SELECT A[A'']"

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#1941]
AST here:
https://gist.github.com/tschottdorf/d3495597e36581d621bd

reproduces as
> "SELECT A%!s(PANIC=runtime error: invalid memory address or nil pointer dereference)"

go-fuzz.

**Comment by tschottdorf** [comment]
this is probably the `ArrayIndirection` being buggy.

**Comment by petermattis** [comment]
Yeah. I'll fix.

**Comment by petermattis** [comment]
What's the failing query? I've tried `SELECT A[A]` and `SELECT A[A"]`. The former parses while the latter hits a syntax error due to an unterminated string. Ah, never mind, it's: `SELECT A[A'']`. That double single-quote looks like a double-quote.

**Comment by petermattis** [comment]
The base problem is that `A''` is parsed as a valid expression for which there is non semantic action. Still trying to figure out why that's a valid expression.
