### ISSUE TITLE
sqlccl: import problem from different s3 region

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#19435]
Copied from https://stackoverflow.com/q/46852338/864236:

---

I try to bulk import into a cockroach db from a S3 bucket in the eu-west-1 region
    
    IMPORT TABLE osm.nodes (
            id INT PRIMARY KEY,
            version INT NOT NULL,
            lat DECIMAL NOT NULL,
            lon DECIMAL NOT NULL,
            changeset_id INT NOT NULL,
            visible BOOLEAN NOT NULL
        )
        CSV DATA ('s3://cockroach-import/nodes.csv?AWS_ACCESS_KEY_ID=<snip>&AWS_SECRET_ACCESS_KEY=<snip>')
        WITH
            temp = 's3://cockroach-import/?AWS_ACCESS_KEY_ID=<snip>&AWS_SECRET_ACCESS_KEY=<snip>',
            delimiter = ','
        ;

I get the error message:

    failed to create s3 reader: 400: "The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-west-1'"

How can I specify the S3 region in the import statement?

**Comment by mjibson** [comment]
I was able to repro this, using the 1.1.1 release.

**Comment by mjibson** [comment]
@bdarnell One of the fixes for this would be to cherrypick https://github.com/cockroachdb/cockroach/commit/860b80ca7541f3db1eeb0a34d3c4d1a6c338c99e into 1.1. We could do this in a way that wouldn't require a change to the vendor subdirectory, just Gopkg.lock. What are your thoughts about including that change? The other options are make a new from-scratch change (since we no longer use this package), or just document this known limitation.

**Comment by bdarnell** [comment]
Cherry-picking that change SGTM. Since it's removing a dependency rather than adding one, I'd be OK with updating `vendor` too (unless it's easier for you to avoid that step and just update Gopkg.lock).

**Comment by Gubaer** [comment]
Did this become part of v1.2-alpha? The [release notes](https://www.cockroachlabs.com/docs/releases/v1.2-alpha.20171026.html) don't mention it explicitly.

**Comment by mjibson** [comment]
Yes, this fix was merged into 1.2 about a month ago: https://github.com/cockroachdb/cockroach/pull/18902

**Comment by bdarnell** [comment]
Sorry, I left this out of the 1.2-alpha release notes because I thought it had already gone out in 1.1.1, but I was wrong (it'll be in 1.1.2 later this week).

**Comment by Gubaer** [comment]
I today run the import from the eu-west-1 region with 1.2-alpha - everything looks fine now!
