### ISSUE TITLE
build: Replace GOVERS with a minimum version

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#19431]
CockroachDB is unusual in setting both an upper and a lower bound on the version of Go we will allow to be used. In CRDB 1.0.x, we required Go version 1.8, which caused headaches for downstream packagers when Go 1.9 was released while 1.0 was still the current version of CRDB (examples: [1](https://www.freshports.org/commit.php?category=databases&port=cockroach&files=yes&message_id=201710220805.v9M85fiU031470@repo.freebsd.org) [2](https://github.com/Homebrew/homebrew-core/pull/18100))

This restriction is overly conservative; new Go versions have not had a history of causing problems for us (the new linters that come with those new Go versions often require code changes, but the compiler and runtime haven't been a problem). It's fine to be strict about versioning for code we vendor, but since we're depending on an external Go toolchain we should be less strict about its version. We should only require a minimum, not a maximum.

 Alternatively, if we do want to keep the maximum version check, we should commit to making patch releases to keep older releases of CockroachDB building with all Go versions released during their supported lifetimes.

**Comment by petermattis** [comment]
Fine by me. I can't recall why we were being so restrictive.
