### ISSUE TITLE
sql+cli/sql: improve trans-version compatibity

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#19445]
This is a list of multiple work items:

- [x] make 1.1 clients work with 1.0 server, in particular should not fail if the server doesn't support `sql_safe_updates` #20935
- [x] change in 1.1/master: print a warning on the screen if the client has a minor version higher than the server, like "warning: features or SQL syntax from 1.1 are not available in a 1.0 server" #20935
- [x] introduce a new mechanism to perform syntax checks server-side without impacting the txn state. Perhaps reuse that to also test the current txn state and merge this new feature with SHOW TRANSACTION STATUS which is already special-cased. 
  - [x] in master #19793 #21119
  - ~[ ] in 1.1?~ - ruled out by ben see comment below
- [x] change in 1.1, ~1,0~ and master: 
  - print an warning on the screen if the server has a higher version than the client, and
  - disable client-side syntax checking preemptively (so that the old client doesn't complain when the user uses new syntax) 
  - **already done on master by #21119** / 1.1 with #21135

**Comment by knz** [comment]
cc @bdarnell does this sound like a plan?

**Comment by bdarnell** [comment]
Yes, although I think I'd only backport a minimal version check to 1.0/1.1 and would leave everything else (especially the server-side syntax checks) to 1.2.

**Comment by knz** [comment]
ok most of the work is done here. There is one more thing I can do here: patch 1.0/1.1 to disable client-side syntax checking if the versions don't match. Would that be ok?

**Comment by bdarnell** [comment]
I'd be OK with disabling client-side syntax checking in older versions if the versions don't match, although I'm also OK with not doing it (I wouldn't want to do a 1.0.7 release just for this).

**Comment by knz** [comment]
ok just 1.1 it is then, and we'll let 1.0 complain about syntax in the old way.
