### ISSUE TITLE
distsql: support semi-joins and anti-joins

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#19450]
Extend the hashjoiner and mergejoiner to support semi-joins (all the rows on one side that have a "match" from the other side) and anti-joins (all the rows on one side that DON'T have a match). These will be necessary when we have an optimizer that is able to rewrite various queries.

**Comment by RaduBerinde** [comment]
"Good first issue" is debatable but I think it would make for a good starter project for someone who wants to get familiar with distsql.

**Comment by vivekmenezes** [comment]
assigning to @richardwu because he's been recently thinking about joins

**Comment by lego** [comment]
Out of curiosity, what will the anti-joins look like? Do we want to add syntax for anti-joins, because there isn't any precedent for this any databases I know of. e.g. `SELECT * FROM t1 ANTI JOIN t2 t1.x = t2.x`.

**Comment by RaduBerinde** [comment]
I don't think we necessarily want to expose then through SQL syntax. They're just a primitive that the optimizer may convert stuff to.

**Comment by RaduBerinde** [comment]
Of course we can add some internal/uncodumented syntax if we need it internally.

**Comment by jordanlewis** [comment]
I don't think databases generally include explicit anti join syntax. They seem to be exposed via the `NOT IN <subquery>` / `NOT EXISTS` syntax. And possibly a normal join where one side is constrained to be null.

**Comment by vivekmenezes** [comment]
A possible starter project. Don't work on this before talking to us.

**Comment by vivekmenezes** [comment]
This work can also include "nested loop join" and CROSS APPLY and OUTER APPLY

**Comment by petermattis** [comment]
Note that the `APPLY` syntax is not part of the SQL standard, but the "apply" operator arises from correlated subqueries. The work proposed is to support an "apply" distsql processor. I'm not quite sure what the form of that takes. Nested-loop join, semi-join and anti-join have much better specs.

**Comment by RaduBerinde** [comment]
NL joins and apply are different beasts, in that the inputs are not just consumed, but one input is repeatedly "set up" or "restarted" with a set of results. There are many things to figure out there in terms of infrastructure.

**Comment by petermattis** [comment]
@RaduBerinde Yes, I forgot about that. NL joins and apply are similar in needing "rewindable" sources. More thought is needed to figure out how to support them. Perhaps we need a "spool" operator as well.

**Comment by jordanlewis** [comment]
@pbardea we can close this right?!
