### ISSUE TITLE
c-rocksdb needs update because of  null pointer exception in DBBatch

### ISSUE THREAD

**Issue by thundercw** [cockroachdb/cockroach#1946]
Continuous Range splits will cause panic sometimes. We have found that the panic was from `rocksdb::WBWIIteratorImpl`. It used the `skip_list_iterator` to scan a `skiplist`. Sometimes the `skiplist` is empty and the `WBWIIteratorImpl.Valid()` does not check the `skip_list_iterator.Valid()`. In this situation, `skip_list_iterator.Next()` called by `WBWIIteratorImpl.Next()` cause the `node_  nullptr exception`.

I found that the bug has been fixed by rocksdb. Please update it to the fixed version. Thanks.

**Comment by tamird** [comment]
I'm on it!

**Comment by thundercw** [comment]
Good :)

**Comment by thundercw** [comment]
@tamird  Version 3.11.2 did not fix the bug ,See  https://github.com/facebook/rocksdb/commit/821cff114e57efa67711c1c1c105aa02831a0d23 .
We must update the upstream to 3.12.1 at least .

**Comment by tamird** [comment]
Ouch, I missed those newer releases because they don't have release notes
on https://github.com/facebook/rocksdb/releases. I'll fix this today.
