### ISSUE TITLE
OOM issues cause 0 QPS but nodes just keep running?

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#19478]
Currently running v1.2-alpha.20170901-985-g70eeefd

Looking at the PM cluster -> got some notifications that it has been in a 0 QPS state. It looks like some kind of OOM error is causing this, based on the log message here:

![image](https://user-images.githubusercontent.com/5768024/31922929-dda66ef8-b845-11e7-9646-8c538853181b.png)

All of the log files from all of the nodes appear to have suffered this issue.

Looking at this graph doesn't tell me much.. how am I supposed to know how much memory is available in the system?

![image](https://user-images.githubusercontent.com/5768024/31923001-45bc9ada-b846-11e7-92d4-2ff6e5601b2a.png)

Is there some sort of best practice here that I'm missing? 

Odd thing is, I can actually still run queries through the SQL client against this cluster...

**Comment by a-robinson** [comment]
For what it's worth, that log message is not an OOM, and it almost certainly is unrelated to the 0 QPS issue. It's just indicating that it determined the available memory on your computer to be `2.0 GiB`.

You make a good point about not being able to tell how much memory is in the system from the graphs, though, and there's still the 0 QPS situation to figure out.

**Comment by dianasaur323** [comment]
@a-robinson ah, I see -> it's not a warning, just an info statement. Hmmm.. maybe I'll do more digging tomorrow. Kind of late right now.

**Comment by dianasaur323** [comment]
This wasn't the problem I expected, so closing out for now.
