### ISSUE TITLE
sql: store tracing results over a period of time in queryable stats table

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#19474]
We had originally discussed doing **something** with tracing, but given that we already have per session and per statement tracing and our already very full 1.2 plate, I'd rather us punt this until it becomes clear what we actually want to do here.  Also don't think we have enough time or demand to properly scope this out.

On the docket for this feature would have been:
- Tracking the run time metrics of a random set of queries over a user-specified period of time
- Storing of the results of the tracing into a queryable stats table

Similar to the Oracle feature discussed here: http://www.oracle.com/technetwork/database/manageability/ppt-active-session-history-129612.pdf

Creating an issue here just for documentation. In case you needed a reminder of context, we discussed it in our 1.2 Aggregated Query Stats Kick-off (should be searchable in our Google drive).

cc @RaduBerinde @andreimatei @knz @vivekmenezes

**Comment by knz** [comment]
this work has been completed.
