### ISSUE TITLE
sql: "SELECT~~+~++~\xbd(*)" and handling *StarExpr in EvalExpr

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#1948]
```
Expr: (*parser.StarExpr)(0x20849c028)({
 TableName: (*parser.QualifiedName)(<nil>)
})
panic: eval: unsupported expression type: *parser.StarExpr
```

I'm not sure whether

* the above SELECT should actually parse (doesn't for Postgres, obviously)
* a *StarExpr needs to be handled in EvalExpr. It contains a QualifiedName, which generally needs to be evaluated.

#gofuzz

**Comment by petermattis** [comment]
Definitely a bug, but I need to think about this further. Expanding `StarExpr` into the full list of columns isn't necessarily correct for aggregation functions like `COUNT(*)`.
