### ISSUE TITLE
sql/parser: comment out/disable unsupported portions of SQL grammar

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#1949]
(thought we had an issue for this already, but could not find it).

**Comment by petermattis** [comment]
Yeah, there isn't another issue for this. There are still swaths of the grammar for which there are no semantic actions. We need to either comment these out or remove them when there is no desire to implement them (e.g. the recently removed postgres extension for generic literal syntax).

**Comment by tamird** [comment]
@petermattis should this be closed now that #2060 is in?

**Comment by petermattis** [comment]
Not yet. There are still portions of the grammar which do not have supporting semantic actions. For example, `ALTER INDEX foo.bar RENAME TO blah`. This example will probably be tackled soon, but there are lots of others. I really just need to audit the grammar and add the semantic actions for things we're going to support and remove the rules we're not.
