### ISSUE TITLE
ui: hidden graph lines reappear on next refresh

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#19490]
If you click either of the colored circles to hide a few of the lines in the graph, that will be reset on the next refresh (so after ~10s).

![image](https://user-images.githubusercontent.com/5076964/31948175-7d05cc4c-b8d6-11e7-87a7-9b0ac9f29939.png)

**Comment by bdarnell** [comment]
I didn't know those were clickable!

While someone's attention is on this feature, it would be nice if the y axis were recomputed when lines are toggled on or off. That was you could disable the line with the highest values to "zoom in" on lines that may be clustered near the bottom of the graph.

**Comment by couchand** [comment]
Both of these comments should be fixed by #18865.
