### ISSUE TITLE
running drop database nuked the admin UI

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#19492]
I'm in the PM cluster -> I ran a drop database statement so that I can restore more up to date data into an empty database. However, running drop database caused the admin UI to become unresponsive. 

![image](https://user-images.githubusercontent.com/5768024/31950248-32e19894-b8a9-11e7-8aae-eb1314515eaa.png)

Just empty. I can still run sql queries in the sql client, and cockroach node status is responsive. Now what?

**Comment by dianasaur323** [comment]
Ah! It's back. Is there anyway I can debug that problem?

**Comment by couchand** [comment]
Open developer tools and check the network tab.  My suspicion is that the static asset requests are either pending or failed, and knowing which and with what status will provide more information for future investigation.

**Comment by dianasaur323** [comment]
ok, once my restore is back, i'll be able to restore and drop the database again, so I will update this issue if I see it happen. If it works next time, I'll close out.

**Comment by dianasaur323** [comment]
I haven't seen this in a while - closing
