### ISSUE TITLE
Cockroach getting stopped with no error in logs

### ISSUE THREAD

**Issue by debraj-manna** [cockroachdb/cockroach#19507]
This is discussed in [forum](https://forum.cockroachlabs.com/t/cockraoch-getting-stopped-with-no-error-in-logs/1041).

I am seeing cockroach getting stopped with no errors in log. I am using the below version of cockroach in Ubuntu

```support@vrni-platform:~$ cockroach version
Build Tag: v1.1.0
Build Time: 2017/10/12 14:50:18
Distribution: CCL
Platform: linux amd64
Go Version: go1.8.3
C Compiler: gcc 6.3.0
Build SHA-1: 8b865035e21aa4fa526ee017ba9dc685d7af649c
Build Type: release-gnu
support@vrni-platform:~$
```
The log files are attached in the forum [discussion](https://forum.cockroachlabs.com/t/cockraoch-getting-stopped-with-no-error-in-logs/1041).

Cockroach was started like below-

```
sudo cockroach start --insecure --host=localhost --store=path=/var/cockroach_data --log-dir=/var/log/cockroach --background
```
I am running a single node cluster. I have verified `/var/log/dmesg`, `/var/log/syslog`. I don;t see anything stating that cockroach is killed by OS.

**Comment by debraj-manna** [comment]
[cockroach.log](https://github.com/cockroachdb/cockroach/files/1413375/cockroach.log)
[cockroach.vrni-platform.root.2017-10-24T17_45_07Z.022430.log](https://github.com/cockroachdb/cockroach/files/1413376/cockroach.vrni-platform.root.2017-10-24T17_45_07Z.022430.log)

**Comment by tschottdorf** [comment]
Thanks for your report! The memory usage in the logs looks low, so OOM killing looks unlikely especially seeing that you haven't seen any indications that that's what happened.

Perhaps something `SIGKILL`ed (`kill -9`) the process? That would look similar. I don't think there's any evidence here - try to restart the node but logging the exit code of the process (i.e. not using `--background`).

**Comment by debraj-manna** [comment]
The VM in which was cockroach was set-up was getting restarted. So the cockroach was getting stopped. No issue in cockroach side.
