### ISSUE TITLE
sql: `SELECT` wont return the rows that don't have values specified during `INSERT`

### ISSUE THREAD

**Issue by arypurnomoz** [cockroachdb/cockroach#1950]
```
CREATE TABLE kv (k VARCHAR PRIMARY KEY, v VARCHAR)
INSERT INTO kv (k) VALUES ('a')
-- these two won't return any row
SELECT * FROM kv
SELECT (k, v) FROM kv
-- only this one will return a row
SELECT (k) FROM kv
```

This issue also effecting `UPDATE` statement, due it's dependency on `SELECT` https://github.com/cockroachdb/cockroach/pull/1944

**Comment by tamird** [comment]
This is probably an issue with INSERT not actually writing those unspecified values.

**Comment by petermattis** [comment]
I think it is fine that the columns are not written in INSERT. SELECT needs to be filling columns that aren't present in a row with NULL. This should be fairly straightforward to fix.
