### ISSUE TITLE
sql: rsg func timeout

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#19500]
RSG had a function timeout during its execution:

`func exec timeout: SELECT COL_DESCRIPTION(NULL::oid, 9223372036854775807::int)`

https://teamcity.cockroachdb.com/viewLog.html?buildId=387419&buildTypeId=Cockroach_Nightlies_RandomSyntaxTests

I can't easily reproduce this locally. Assigning for triage.

**Comment by knz** [comment]
@justinj please have a look? Otherwise ask vivek for triage.

**Comment by justinj** [comment]
Just based on a glance I'm...extremely stumped. The function in question does [literally nothing](https://github.com/cockroachdb/cockroach/blob/17cf3606f241743c989df1481a22317baa0b4601/pkg/sql/parser/pg_builtins.go#L301-L310), so I think whatever hangup occurred here was probably unrelated to the function being called?

**Comment by mjibson** [comment]
Certainly possible. Closing as a probably not-RSG error.
