### ISSUE TITLE
backup/restore: transient network error

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#19502]
4 node cluster, SFO, NYC, NYC2, AMS. 

Running  show backup sometimes throws this error message: 

pq: importing 395 ranges: could not find s3 bucket's region: ServiceUnavailable: Service Unavailable
	status code: 503, request id: 207652C3D187982A, host id: age9rSo8QLjHrzOOkpdTm6vzuWFB6A9MTT+QsGHGGTsASX7L+5dXNk6Lcu7+8Rlm6UgrJauHJWg=

**Comment by mjibson** [comment]
If an error like this shows up again please log a new issue. We've fixed this specific call to retry, but we expect others will fail in the future.
