### ISSUE TITLE
clusterviz: node canvas, no aggregation

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#19517]
For this iteration, let's start out with placing single nodes in a circle with no aggregation. I think this should be relatively straightforward.

- [ ] Node component with metrics @kuanluo We need to think of a better name for replicas - the current mock has it as (RPCS) which I think doesn't cut it. 
- [ ] Warning messages when users get to more than 8 nodes
- [ ] Radio buttons to show bubble metrics
- [ ] For bubble metrics: let's do %CPU, QPS, Replicas, %Memory
- [ ] For users adding more than 8 nodes, we'll just have to make the circle bigger and allow zoom and zoom out -> please let me know your thoughts on this
- [ ] Need to show new nodes (these should really just be the node join event)
- [ ] Need to show decommissioning nodes
- [ ] Need to show dead nodes
- [ ] Again, let's be careful about loading states

cc @kuanluo @cuongdo @couchand @vilterp @mrtracy

**Comment by kuanluo** [comment]
>  Node component with metrics @kuanluo We need to think of a better name for replicas - the current mock has it as (RPCS) which I think doesn't cut it.

Fair enough... Maybe just "Rep"? cc: @Amruta-Ranade 

> For users adding more than 8 nodes, we'll just have to make the circle bigger and allow zoom and zoom out -> please let me know your thoughts on this
I still prefer the current option that's a grid, imagining the scenario in my mind. For 5+ nodes, it's more readable without any interaction. We can take a look at prototype and have a more informed discussion then?

**Comment by dianasaur323** [comment]
@kuanluo I'm fine with the grid option, although it's an uphill battle that I'm not sure is worth fighting. I think what we could do, is try the non-prototype option and see how bad it gets from a usability perspective? Rep still seems odd to me. Although it looks like we only have room for around 4 letters?

**Comment by couchand** [comment]
Yes it looks like we currently only have room for 4 letters, but I'd strongly recommend against abbreviating if we can avoid it.

I'm :-1: on any kind of zooming, and :-1: on showing a circle for very many nodes, though I am :+1: on the network view and the metrics view looking similar, so I don't know where I come out.  I really don't think the circle is more natural than the grid, both of them are imposing an arbitrary organization on the nodes.

**Comment by Amruta-Ranade** [comment]
I agree with @couchand and recommend against abbreviating. But if we have to, I would suggest REPL or RPL.

**Comment by dianasaur323** [comment]
I think the benefit of the grid is that then you can overlay the network on the grid, so you can see how things are related and talking to each other. 

I can be convinced to be 👍  on using the circle up to however many nodes makes sense, and flipping to the grid once it gets crazy. That being said, I do think we have an uphill battle about the grid, so we might want to show the circle and how bad it looks?

**Comment by dianasaur323** [comment]
I think @Amruta-Ranade's suggestions sound good, but we probably want to provide some sort of hover over so users can figure out what that number means?

**Comment by kuanluo** [comment]
> I think the benefit of the circle is that then you can overlay the network on the circle, so you can see how things are related and talking to each other.

What about a hybrid approach of having <=6 nodes in a circle, and >6 goes to grid? More than 6 nodes with no localities, the network traffic will look crazy anyways.

> Actually, maybe it doesn't matter since we will have a radio button?

We also need to make sure it's a checkbox rather than a radio button. :)

**Comment by dianasaur323** [comment]
Closing for now, since it seems like this conversation was a bit pre-emptive
