### ISSUE TITLE
build: make non-release builds compile C++ code with -O2 or -Ofast instead of -O3

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#19511]
On my computer -O3 causes build times for protobuf/rocksdb to jump by at least 30% overall, 60%+ on some files over -O2/-Ofast. Meanwhile the performance benefit is -- for my work -- negligible.

Given I am spending more time waiting for my builds to finish than on CockroachDB to do work for me, reducing the build time will help me more than the marginal performance improvement of -O3.

So, I kindly request we use -O2 or similar instead for non-release builds.

**Comment by petermattis** [comment]
I have no objections to doing this, but why are protobuf/rocksdb rebuilding so frequently for you. They almost never rebuild for me.

Also, is using `ccache` an option for you? If you're switching back and forth between branches which contain changes to protobuf/rocksdb, using `ccache` is an even bigger win than -O2/-Ofast.

**Comment by knz** [comment]
Yes ccache helps greatly but there's just the odd case like today where my laptop is not on power, so cpu is slow(er) and I need to rebuild from scratch on a pinch because I didn't have an up to date `master` since last week. It happened also a few times earlier this year, every time while traveling, checking out the latest version before either showing something or testing a new thing.

I think as we increase the number of demos/tests "on the move", the traveling engineers will find themselves more often faced with the situation that they need a cockroachdb build on short notice. We should have at least one configuration that gives a working binary super-fast, even if our prod builds go for more bells and whistles.

**Comment by petermattis** [comment]
Perhaps the working binary super-fast should be the exception. The usual case is that rocksdb and protobuf do not need to be recompiled. I hate having to debug a performance issue and track it down to the wrong type of build (which I've done many times in my career). Are you sure this yak is worth shaving? Perhaps we can give you hooks so that you can specify `-Ofast` via some env var.

**Comment by knz** [comment]
Oh, if an env var is possible that would be just great. If you tell me what to use I could even document it myself so that anyone in the future can find the trick.

**Comment by petermattis** [comment]
@benesch Will have to speak up here. I'm not terribly familiar with what controls cmake provides.

**Comment by benesch** [comment]
I haven't looked into this in any detail, but I'm not sure where `-O3` would be coming from. RocksDB sets `-O2` by default, for example: https://github.com/facebook/rocksdb/blob/master/CMakeLists.txt#L157

**Comment by knz** [comment]
Ugh, then I'm utterly confused.

**Comment by knz** [comment]
I have found in practice that I can manually tweak the makefile when traveling, and it's not an issue otherwise. closing.
