### ISSUE TITLE
sql: have a solution for maintaining a canonical list of column types

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#19515]
This is mostly a brainstorming issue - for testing purposes, it would be really nice to be able to write tests that range over all valid column types (note that `TypesAnyNonArray` denotes datum types and also doesn't really solve this problem) that would ensure they were added in all the right places (like pg_catalog), but there's a bootstrapping problem that Go doesn't really provide a way to ensure that the list of column types itself is exhaustive (and "exhaustive" here is ill-defined for column types that can have parameters like `DECIMAL`). Short of some kind of lint rule or just the common knowledge that a new column type needs to be added to the list I'm not sure what the right solution is here.

cc @mjibson @jordanlewis @knz 

Jira issue: CRDB-5969

**Comment by jordanlewis** [comment]
https://github.com/haya14busa/gosum is a possibility.

**Comment by knz** [comment]
our IR code generator can also generate these loops automatically.

**Comment by petermattis** [comment]
Which column types do you want to iterate over? `ColumnType.SemanticType`? The generated protobuf code provides an array of the legal values. The various `Datum` implementations? Somewhat harder, but I think something is doable here. Something else?

**Comment by justinj** [comment]
Specifically I want to be able to iterate over the allocated instantiations of `parser.ColumnType` (for example, including but not limited to [these](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/parser/col_types.go#L96-L107))

**Comment by lego** [comment]
was also experimenting with ways improve linting to achieve this, similar to gosum. It is still very WIP, https://github.com/lego/go-tools. In particular:
- Checking if switches cover all cases over a type annotated explicitly as an enum (see [this commit](https://github.com/lego/go-tools/commit/54d2e4840cb31af924191cc0afe5fad718c07420)). I was approaching this where the enums required explicit comment annotations.
  ```go
  // StaticCheck: ENUM = MyType
  type MyType int

  const (
    FirstType MyType = iota
    SecondType
  )
  var v MyType
  switch v { // Lint error thrown due to missing case for SecondType
  case FirstType:
  default:
  }
  ```

  Additionally, the switches themselves could be given an annotation to make this more of an eased in change. If there needed to be explicit exemptions, that also could be an annotation but it does become far less friendly at this point.
- Checking type switches are exhaustive over a particular interface (see [this commit](https://github.com/lego/go-tools/commit/9e57aa09621d7692e569500ab2abbb8c15acbfd9), which was running against cockroach to check Datums). Similar to enums, I think this is best introduced if the switches themselves are annotated for being linted.

I was hoping to get meaningful results sometime soon and see how useful this could be, even if checks are only introduced to a few types/switches and this only lives on a separate branch.

**Comment by jordanlewis** [comment]
Closing as wontfix / no longer relevant (we have a bunch of handcoded arrays for stuff like this).
