### ISSUE TITLE
clusterviz: more obvious aggregated nodes design

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#19514]
Based on our discussion yesterday, we are going to need a version of the aggregated node that is more obviously aggregated. 

@kuanluo could you try your hand at this? We can go ahead with the square if that turns out to be the best option, but would like to see what other options we have.

**Comment by kuanluo** [comment]
Yes, will do once we see how the square looks in prototypes. Definitely non-blocking to development at the moment.

**Comment by dianasaur323** [comment]
@kuanluo kk, i think that's fine particularly given our earlier discussions today!

**Comment by dianasaur323** [comment]
Closing for now
