### ISSUE TITLE
ui: use position: sticky for header

### ISSUE THREAD

**Issue by couchand** [cockroachdb/cockroach#19522]
The header on the time series chart pages uses a scroll-linked effect.  This has some minor issues interacting with newer browsers' asynchronous scrolling.  The CSS attribute `position: sticky` should be used instead to let the browser's compositor handle rendering the header in the right place on scroll.

See https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Scroll-linked_effects

**Comment by shekhar108** [comment]
Hello, I am a first time contributor here and I would to work on this. As much as I can understand, the change needs to be made in the ui package for the file styl/layout/layout.styl. 

Correct me if I am wrong.

**Comment by couchand** [comment]
Hello @shekhar108, thanks for volunteering, and welcome!

Currently we use [react-sticky](https://github.com/captivationsoftware/react-sticky) for the header on a few pages.  That library is no longer being maintained, and since `position: sticky` is supported by the major browsers, we can migrate to using that.

If you grep for the usages of `react-sticky` you'll find the components that need to change.  I believe it's just `src/views/app/containers/layout/index.tsx` and `src/views/shared/components/pageconfig/index.tsx`.  I haven't experimented with it, but I think the container can just be dropped from the layout, and the `position: sticky` applied to the `PageConfig` component.

Our new trend is to put the styles alongside the component they are for, so you could just add a new `.styl` file next to `pageconfig/index.tsx` and import it from there to get it included in the bundle.  Take a look at a recent PR with styling for an example, perhaps https://github.com/cockroachdb/cockroach/pull/21553/files#diff-a7136d176ad999f305351465d89a36daR15

Let me know if you've got any other questions.

**Comment by couchand** [comment]
Closed by #24616
