### ISSUE TITLE
config: sort out package dependencies

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#19525]
`pkg/config` depends on `sql/parser`, knows how to construct table keys, and really wants to be able to use `sqlbase.ID`, but `sqlbase` depends on `config`. Ideologically, `config` shouldn't really know about SQL, but the current ZoneConfigHook that lives in SQL and gets installed in config at init-time is pretty ugly. 

This should all be sorted out somehow. I don't have any bright ideas, though.

**Comment by jordanlewis** [comment]
@ajwerner cleaned this up recently, I think it's better now.

**Comment by benesch** [comment]
> *: remove sqlbase

Never thought I'd see the day!
