### ISSUE TITLE
clusterviz: hover over networking

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#19521]
This one needs a design view first: cc @kuanluo 

- [ ] Hover over one node to show network connections to all other nodes
- [ ] This needs to match with what we are seeing in the Cockroach cluster, so if a certain node can not be communicated with, the network line should not show up
- [ ] Metrics: in / out, RTT. We can drop latency - I believe that was shown before, but it's query latency, which is weird in a network graph. Perhaps we can put RTT in the bubble instead
- [ ] Show error state if a node can't be reached

cc @kuanluo @cuongdo @couchand @vilterp @mrtracy

**Comment by cuongdo** [comment]
Under metrics: by "in/out" do you mean "network bandwidth in / out"

**Comment by dianasaur323** [comment]
Closing for parent issue
