### ISSUE TITLE
storage: sprinkle assertions about negative MVCCStats

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#19546]
![image](https://user-images.githubusercontent.com/5076964/32025646-13923d20-b9af-11e7-9639-c02fc8afbcc7.png)

To get this, I started a four node cluster and decommissioned the initial node so that all of the ranges were moved away from it, resulting in the negative stats.

There's a chance that this is because some of these stats have `ContainsEstimates` set and are plainly wrong (makes sense since there were only time series ranges and splits happened), but wanted to file this anyway because we should at least bottom out the stats at zero (i.e. don't allow negative numbers in a replica's MVCCStats. Instead, if they occur, assert that ContainsEstimates is set, and report zeroes instead in the appropriate place. Or even store the zeroes).

**Comment by tschottdorf** [comment]
New idea here is to add assertions in some frequent-enough-but-not-too-frequent places that assert that everything is positive if ContainsEstimates is false. That should be straightforward.
