### ISSUE TITLE
sql: TRUNCATE interleave parent TRUNCATEs child as well

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#19584]
It looks like `TRUNCATE` is unaware of interleaved tables.

```
root@:26257/test> create table parent (a int primary key);                                                                                                                                                                    CREATE TABLE

root@:26257/test> create table child (a int, b int, primary key(a, b)) INTERLEAVE IN PARENT parent (a);                                                                                                                       CREATE TABLE

root@:26257/test> insert into parent values (1), (2);
INSERT 2

root@:26257/test> insert into child values (1, 2), (2, 4);
INSERT 2

root@:26257/test> select * from parent;
+---+
| a |
+---+
| 1 |
| 2 |
+---+
(2 rows)

root@:26257/test> select * from child;
+---+---+
| a | b |
+---+---+
| 1 | 2 |
| 2 | 4 |
+---+---+
(2 rows)

root@:26257/test> TRUNCATE parent;
TRUNCATE

root@:26257/test> select * from parent;
+---+
| a |
+---+
+---+
(0 rows)

root@:26257/test> select * from child;
+---+---+
| a | b |
+---+---+
+---+---+
(0 rows)
```

Note that this is not a problem with `DELETE`.

cc. @jordanlewis

**Comment by vivekmenezes** [comment]
That's how we decided to implement it. It's been like this since 1.0 and in 1.1 we implement TRUNCATE using a schema change that involves a change in descriptor ID so in effect by changing the descriptor ID of the parent it is truncating the child tables. One cannot DROP a parent table without also dropping the children. I don't think this is odd.

**Comment by vivekmenezes** [comment]
closing for now. Feel free to reopen if needed.

**Comment by jordanlewis** [comment]
Hmm, if this is in fact intended, it certainly needs to be documented - neither the [`TRUNCATE`](https://www.cockroachlabs.com/docs/stable/truncate.html) nor the [`INTERLEAVE IN PARENT`](https://www.cockroachlabs.com/docs/stable/interleave-in-parent.html) docs mention it.

That being said, I think that the current behavior is very dangerous and possibly unintuitive. At the very least, `TRUNCATE` on parent interleave tables should require the `CASCADE` modifier to also truncate child tables, don't you think? Reopening to deal with this point.

`CASCADE` generally represents a strong protection opportunity for accidental data deletion. It would make me much happier to see `TRUNCATE` on parent tables unconditionally fail without the `CASCADE` modifier, regardless of whether the child table has any data at all, even if that's a little imprecise.

**Comment by vivekmenezes** [comment]
https://cloud.google.com/spanner/docs/schema-and-data-model suggests adding ON DELETE CASCADE to the schema for interleaved tables. One option is for us to disallow a child row to exist without a corresponding parent row (making the relationship a FK). When DELETE-ing from a parent  table the user will be forced to use the ON DELETE CASCADE clause. This will be a bigger change.

**Comment by jordanlewis** [comment]
We already optionally support that mode, simply by adding a `FOREIGN KEY` relationship from the child to the parent.

Even if `ON DELETE CASCADE` (which of course we don't support yet) were added to the foreign key constraints of the child, `TRUNCATE` should still not delete the child table without `CASCADE`.  It's just too dangerous to permit users to `TRUNCATE` more than one table at a time without explicitly permitting it with the `CASCADE` operator.

**Comment by jordanlewis** [comment]
See for instance this paragraph in the [Postgres `TRUNCATE` documentation](https://www.postgresql.org/docs/10/static/sql-truncate.html):

> TRUNCATE cannot be used on a table that has foreign-key references from other tables, unless all such tables are also truncated in the same command. Checking validity in such cases would require table scans, and the whole point is not to do one. The CASCADE option can be used to automatically include all dependent tables — but be very careful when using this option, or else you might lose data you did not intend to!

**Comment by dt** [comment]
=@jordanlewis I think it should behave like the FKs: `TRUNCATE` should fail unless the child is also being truncated (either explicitly or via cascade).
