### ISSUE TITLE
Concurrent txns against a single node fail to commit

### ISSUE THREAD

**Issue by cosmicturtlesoup** [cockroachdb/cockroach#1958]
Large numbers of concurrent txns against a single key on a single node will fail to commit.  Small numbers work fine.  

For example, 55 concurrent txns finish in just a few seconds, but if the same test is run with 105 concurrent txns, only a small number complete (like 5 or so) and even those take a long time to commit... and then the system fails to commit any further txns and eventually times out.  

Tested in both CentOS7 and Ubuntu 15.04.  I'm submitting a pull request shortly which demonstrates this issue.

Sample args (test added in pull req):
make acceptance TESTS=TestSingleKeySingleNodeConcurrentTxn TESTFLAGS="-num 3 -numTrans 55 -d 4s -v"

See [example] (https://gist.github.com/cosmicturtlesoup/9d00c9b9e95939828c10) for output of a small test which passes and larger test which fails.

**Comment by tschottdorf** [comment]
I'm moving the discussion to the original issue #628.
