### ISSUE TITLE
server: log spam for unhealthy cluster at startup

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#19599]
I've started a node out of a 3-node cluster while the other two were down. The following was logged at a high rate. It stopped when I turned up the other nodes.

```
W171027 18:58:42.965667 55908 storage/replica_range_lease.go:333  can't determine lease status due to node liveness error: node not in the liveness table
```

**Comment by dianasaur323** [comment]
I've seen the same problem in a 3-node cluster where the node kept coming back to life as well.
