### ISSUE TITLE
sqlccl: Estimation of time remaining in job is way off

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#19607]
I realize estimating how long a job will take is super hard, but the estimate that I've been seeing for a a CSV IMPORT is so far off (by an order of magnitude, potentially) that it seems worth at least filing an aspirational issue for:

<img width="1279" alt="screen shot 2017-10-27 at 5 41 46 pm" src="https://user-images.githubusercontent.com/7085343/32126343-225e8aee-bb3e-11e7-8891-e5a310d8109c.png">

It's been estimating "01:21:40 remaining" for a while now, which means the 33% number is clearly not correct, but also this is a job that apparently takes at least 7 hours according to @dt's comment that his identical IMPORT job broke after more than 7 hours of running (https://github.com/cockroachdb/cockroach/pull/19436#issuecomment-339206066).

To be specific, this is a TPC-H SF=100 lineitem IMPORT on 3 GCE n1-highcpu-4 nodes using local SSD.

**Comment by a-robinson** [comment]
Sorry for the incomplete initial post. Edited.

**Comment by dt** [comment]
AFAIK, the time estimate is extrapolating from % complete and time elapsed... we're just wrong to say 33% after first read of the CSVs (to sample the key distribution) is done.... probably makes more sense to guess that that is... 5 or 10%?

**Comment by dt** [comment]
@benesch how would you feel about an alternative signature for `Progressed` that takes a percentage to add rather than an absolute one, and then handles the retry loop required to read/add/write?

I'm thinking that could simplify distributed progress, letting each chunk write a "i finished 1/x" update as it wraps up, rather than needing to plumb those back to a coordinator that writes the sums? I guess the downside is a write storm in widely distributed jobs if everyone finishes at the same time

**Comment by benesch** [comment]
Certainly not opposed, but fair warning: in the days leading up to the 1.1 release, progress tracking could occasionally brick a restore. We had a bug where, if we were unlucky, several dozen concurrent writers would try to update the progress at once. This would overwhelm the command queue, causing additional concurrent writers to pile up; eventually we'd end up with fifty or sixty goroutines all trying to update the progress at once, essentially serializing the restore. I'm not convinced that we were entirely at fault—our performance under contention leaves a lot to be desired—but tread carefully.

**Comment by dt** [comment]
We might be able to get away with this in IMPORT where concurrency is limited by number of import files... I'll play with it, thanks!

**Comment by mjibson** [comment]
Fixed.
