### ISSUE TITLE
sql: support COPY from stdin binary

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#19603]
The binary mode is used by https://github.com/jackc/pgx and would be nice to be able to use as an alternative to lib/pq's funky COPY support that mandates a transaction.

From: https://www.postgresql.org/docs/9.2/sql-copy.html

> The `binary` format option causes all data to be stored/read as binary format rather than as text. It is somewhat faster than the text and CSV formats, but a binary-format file is less portable across machine architectures and PostgreSQL versions. Also, the binary format is very data type specific; for example it will not work to output binary data from a `smallint` column and read it into an `integer` column, even though that would work fine in text format.
> 
> The `binary` file format consists of a file header, zero or more tuples containing the row data, and a file trailer. Headers and data are in network byte order.

**Comment by rafiss** [comment]
See also #41608 for additional COPY syntax

**Comment by solongordon** [comment]
Sending to Bulk I/O backlog since we don't have COPY expertise on SQL Features. Would you be able to evaluate how difficult this implementation is? Per @vy-ton we want to shore up features required by pgx so that we can recommend it to customers.

**Comment by dt** [comment]
@mjibson which usage were you thinking of? the file upload stuff?

**Comment by mjibson** [comment]
COPY BINARY is just what pgx hard codes as its COPY implementation. Nothing to do with IMPORT or file uploads.

**Comment by dt** [comment]
Ah, okay, so this is about supporting the `binary` format modifier to the SQL `COPY .. FROM` statement, which gets planned as an INSERT? Got it -- I don't think that overlaps with any bulk-io stuff then

**Comment by solongordon** [comment]
Stealing this back to SQL Features, thanks for looking.
