### ISSUE TITLE
rsg: needs JSONB support

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#19605]
https://teamcity.cockroachdb.com/viewLog.html?buildId=390952&buildTypeId=Cockroach_Nightlies_RandomSyntaxTests

**Comment by vivekmenezes** [comment]
@justinj do you think we should do this? I'm assuming this will turn on random JSON testing which will be good.

**Comment by justinj** [comment]
I know we did some of this - I forget how much, I'll take a look

**Comment by justinj** [comment]
Yes, we do this now.
