### ISSUE TITLE
sqlccl: `BACKUP... WITH revision_histroy` missing dropped tables

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#19600]
Currently the spans that must be included in a backup are generated based on the tables that match as of the end time, but that means that a table dropped since the previous backup will not be included and thus its spans will not have their history, up to the point the table was dropped, captured.

**Comment by dt** [comment]
I want to gracefully handle changing spans soon, but in the meantime, I'm thinking of requiring the spans on revision_history backups exactly match the previous backup to prevent creating a broken backup. This breaks some legit use cases, e.g.
`BACKUP <everything> TO foo` followed by `BACKUP <small> TO bar INCREMENTAL FROM foo WITH revision_history`, but it makes sure you can't miss the fact that that your incremental with revision history is missing the changes up to the point the table was dropped.

**Comment by dt** [comment]
After discussing some fringe / edge case user stories with @dianasaur323, our plan here, for now, is to include a descriptor if it:
* matches the target spec, as of the BACKUP time (stmt time / explicit `AS OF SYSTEM TIME`), i.e. our current matching behavior.
* at any point in the time window, has a parent ID matching a DB that is expanded by the target spec (`DATABASE foo` or `foo.*`).

Concretely, this means that a backup made by running `BACKUP DATABASE foo WITH revision_history` should include the history for up until dropping a table that was in `foo`, or the history for a table moved into or out of `foo`, the history both before and after a `truncate`, etc.

However, some places where this could potentially behave in an unexpected way come up when a table had a different name at some point in that window but is named explicitly in the BACKUP command -- e.g. `BACKUP foo.bar`. For example, if someone runs renames a table (ID 51)  `bar` to `baz` and then creates a new table (ID 52) `bar` before running `BACKUP foo.bar WITH revision_history`, while obviously we should include ID 52, we struggled a bit with how to handle ID 51. 

We went back and forth a bit here, but concluded the approach which seemed the simplest to understand/explain is the rules above, which implies that 51 is _not_ included. Adding an additional rule such as "has the same name at some point as a descriptor that is matched" would include 51, but seems to complicate the story -- e.g.  you could already include it if you wanted to, by adding `baz` to the target spec, but, if we added that additional rule, you'd be out of luck you _didn't_ want to include `baz`?

However this gets a bit messier when you can't refer to the old table by name, e.g. if it has been dropped, or, in particular, truncated.. It certainly feels like `BACKUP foo.bar WITH revision_history` should capture the history before and after a `TRUNCATE foo.bar` but, according to our proposed rues, it would not -- you'd need to use `BACKUP DATABASE foo` to capture both tables.
This seems pretty gross: the fact that they are different tables is supposed to just be an implementation detail of truncate.

Overall though I think we still like these semantics, and might look at explicitly fixing truncate (by recording the ID of the original table or something) rather than adding more complex name matching rules?

**Comment by dianasaur323** [comment]
@dt I think that sounds like a good approach. It is a gross surprise, although I work around isn't too much worse than what you might have to do with other databases. I think intuitively, it makes sense and is easier for users to reason about. Interestingly enough, Oracle seems to have the same issue.

![image](https://user-images.githubusercontent.com/5768024/35394254-4599a0ee-01b5-11e8-9d1c-87d7a617ed60.png)

**Comment by dt** [comment]
#21717
