### ISSUE TITLE
client: audit use of SetSystemConfigTrigger

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#19617]
We're not properly setting the system config trigger everywhere we write to system config tables. RESTORE doesn't, for example. (Maybe it gets away without the trigger because we're writing new descriptors, so no leases to invalidate?)

I don't have a great sense of how table descriptor leases, schema changes, gossip, and the system config trigger interact, and the current API doesn't do much to abstract away the complexity. I think we should localize usage of `SetSystemConfigTrigger` to just a few functions: the functions that handle `INSERT`s and `UPDATE`s on system config tables, plus one or two helper functions for e.g. writing out name/descriptor keys. (Right now, we do raw CPuts all over the place to create new tables/databases.)

@vivekmenezes, can you triage?

**Comment by vivekmenezes** [comment]
leaving assigned to self.
