### ISSUE TITLE
sql: any plan of implementing 'UPSERT' or 'ON DUPLICATE KEY UPDATE' ?

### ISSUE THREAD

**Issue by arypurnomoz** [cockroachdb/cockroach#1962]

**Comment by petermattis** [comment]
There are no immediate plans. There is also `REPLACE` (https://dev.mysql.com/doc/refman/5.0/en/replace.html).

**Comment by tamird** [comment]
This would just require a flag on `parser.Insert` which would cause `sql.(*planner).Insert` to use `Put` instead of `CPut`. Tagging easy.

**Comment by petermattis** [comment]
@tamird Not sure if just changing `Put` to `CPut` would be sufficient. On a duplicate primary key you would have to delete old column values and secondary indexes as `Update` does. It still isn't too difficult, but maybe not easy.

**Comment by fire** [comment]
Postgresql has its own implementation of ["Upsert"](https://wiki.postgresql.org/wiki/UPSERT).

**Comment by petermattis** [comment]
Thanks for the pointer, @fire. I imagine we'll implement upsert for 1.0, though it isn't currently on our roadmap.

**Comment by archiecobbs** [comment]
+1 This is a must-have for me.

I simply want to use CockroachDB as a key/value store.

Since using CockroachDB directly as a key/value store is [not recommended/possible](https://groups.google.com/forum/#!topic/cockroach-db/WHsuUWDuwmI), the only way to do this is by using SQL and creating a simple table with key and value columns.

OK fine...

But without this functionality there's no way to do a PUT!

**Comment by petermattis** [comment]
@archiecobbs Thanks for the prioritization. We've wanted UPSERT for some of our internal uses.

**Comment by paperstreet** [comment]
@archiecobbs I'm starting on this and considering adding mysql's [REPLACE](http://dev.mysql.com/doc/refman/5.7/en/replace.html) first and then adding ON CONFLICT UPDATE/ON DUPLICATE KEY later as it's needed. I think REPLACE is enough for your key/value use, do you agree?

**Comment by archiecobbs** [comment]
@paperstreet Yes, that will work great. Thanks for the fast turnaround.

**Comment by paperstreet** [comment]
Sorry for the lack of updates, I've been taking this opportunity to clean some stuff up a bit: http://github.com/cockroachdb/cockroach/pull/6211. With that out of the way, I'm on to REPLACE itself
