### ISSUE TITLE
cli/sql: Don't display statement tags

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#19625]
Our CLI currently displays postgres-style "statement tags" at the end of each command: the top-level SQL verb followed by the number of rows affected:

```
root@:26257/test> INSERT INTO test.kv VALUES (123, 2);
INSERT 1

Time: 1.873649ms
```

This [can be confusing](https://forum.cockroachlabs.com/t/insert-on-conflict-behavior/1031) for complex statements like `INSERT ON CONFLICT DO UPDATE`: it always resports `INSERT N` whether the rows were affected by the `INSERT` or `UPDATE` branches of the query. I think it would be better to drop the statement tag (which provides no new information if it's just repeating the first word of the query) and instead state more clearly that the number is the count of rows affected. We could follow mysql's output format:

```
mysql> insert into test.a values(123);
Query OK, 1 row affected (0.00 sec)
```

Jira issue: CRDB-5965

**Comment by knz** [comment]
I looked into this and I am not too fond of the idea: the tag genuinely informs the user about what occurs in other CLI commands, e.g. `cockroach user set --password` with either report INSERT or ALTER depending on whether the user existed before.

**Comment by petermattis** [comment]
Could we do Ben's suggestion only for interactive queries?

**Comment by knz** [comment]
I suppose we could yes
