### ISSUE TITLE
sqlccl: OOMs in distributed IMPORT CSV job

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#19635]
Is there anything that tries to limit the memory used by IMPORT? I ran two experimental import jobs on Friday (https://github.com/cockroachdb/cockroach/pull/19436#issuecomment-340057144) in an attempt to test out some node liveness improvements, and could hardly even examine the results afterward because the memory usage was so bad that the processes necessary to allow me to SSH to the VMs got OOM-killed on 4 of the 6 VMs.

The OOMs kicked in less than 10 minutes after the import started actually writing data to disk. Node liveness issues also started popping up around the same time, but node liveness issues shouldn't cause OOMs.

These were on separate 3 node clusters using 4-core, 4GB VMs with local SSDs, following the instructions in https://github.com/cockroachdb/cockroach/pull/19436#issuecomment-339669076.

Is the cause of these OOMS understood? Is there anything that can be done about them separate from the liveness issues?

@dt @mjibson

**Comment by a-robinson** [comment]
I imagine it makes zero difference, but here's the serial console log from one of the VMs that got so badly OOM'ed that I couldn't even SSH to it afterwards. The fact that the OOM killer chose the wrong process(es) to kill first is really a GCE/debian/linux problem more than anything, but still bad:

[serial.log](https://github.com/cockroachdb/cockroach/files/1427678/serial.log)

**Comment by a-robinson** [comment]
There was also this pthread error on one of the nodes. It might just be the same OOM problem, or might just be due to so many threads getting blocked in cgo, but could be indicative of something worse, like a thread leak in cgo.

```
runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0x7efe57e56fcf m=2 sigcode=18446744073709551610

goroutine 0 [idle]:

goroutine 1 [select, 563 minutes]:
github.com/cockroachdb/cockroach/pkg/cli.runStart(0x2f26320, 0xc420080ff0, 0x0, 0x5, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/cli/start.go:655 +0x67c
github.com/cockroachdb/cockroach/pkg/cli.MaybeDecorateGRPCError.func1(0x2f26320, 0xc420080ff0, 0x0, 0x5, 0xc420683ca0, 0x177ea90)
        /go/src/github.com/cockroachdb/cockroach/pkg/cli/error.go:35 +0x57
github.com/cockroachdb/cockroach/pkg/cli.MaybeShoutError.func1(0x2f26320, 0xc420080ff0, 0x0, 0x5, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/cli/error.go:66 +0x51
github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).execute(0x2f26320, 0xc420080fa0, 0x5, 0x5, 0x2f26320, 0xc420080fa0)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:698 +0x47a
github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x2f22360, 0x6062b9, 0xc420080260, 0xc420683ef0)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:783 +0x30e
github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).Execute(0x2f22360, 0xc420683ee8, 0x0)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:736 +0x2b
github.com/cockroachdb/cockroach/pkg/cli.Run(0xc420010080, 0x6, 0x6, 0xc42001a088, 0xc420026c00)
        /go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:159 +0x6d
github.com/cockroachdb/cockroach/pkg/cli.Main()
        /go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:52 +0x16c
main.main()
        /go/src/github.com/cockroachdb/cockroach/main.go:26 +0x20

goroutine 6 [chan receive, 1 minutes]:
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).flushDaemon(0x344bee0)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:1005 +0x81
created by github.com/cockroachdb/cockroach/pkg/util/log.init.0
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:581 +0xbf

goroutine 34 [syscall, 563 minutes]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:131 +0xa6
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x41

[...]
```

**Comment by mjibson** [comment]
No, IMPORT doesn't do anything explicit to attempt to limit memory use during distributed transform. This is because, we thought, that since the data is being streamed to RocksDB instances, that memory would be constrained because everything would be on disk. Fixing these kinds of things is the next thing on my list after adding job cancel support to IMPORT.

**Comment by dt** [comment]
I definitely see mine get OOM killed, but so far I'e been lucky(?) and always had the OS pick cockroach first.

**Comment by a-robinson** [comment]
The logging in #19649 has confirmed that the OOMs happen after `generated 968 splits; begin routing for job IMPORT TABLE ...` gets logged but before `finished job` get logged.

**Comment by a-robinson** [comment]
And the jobs page looks like this after restarting the two OOM-killed nodes:

<img width="1261" alt="screen shot 2017-10-30 at 5 55 05 pm" src="https://user-images.githubusercontent.com/7085343/32197672-88871a2a-bd9b-11e7-968e-003f80b01080.png">

**Comment by mjibson** [comment]
Ok. That state is where distsql reads through all the CSVs, routes KVs to the appropriate node, and then writes them to disk. The disk usage makes sense. However the OOM does not. I wonder if something is holding on to references, or maybe starting `968/<number of nodes>` distsql processors per node is just a huge amount of memory.

I think we should consider refactoring the distributed import functionality. Instead of starting N processors per node, it should be 1. That processor can dump all its incoming KVs into the same rocksdb instance, and read through them per SST. That may reduce the memory usage considerably, assuming the problem is per-processor memory.

**Comment by a-robinson** [comment]
To clarify, does that code path involve using the temp rocksdb at all? Or is it just writing SSTs directly to the filesystem and calling `IngestExternalFile`? For the sake of node liveness I'm curious what writing is being done.

**Comment by dt** [comment]
writing SSTs to local disks and calling ingest doesn't start until the RESTORE job, which I don't think we're getting to based on your screenshot.

At a high level:
1) read CSV files to produce KV pairs and sample their distribution, discarding the results.
2) read CSV files to produce KV pairs and push them into DistSQL sort, routed to buckets picked based on above distribution.
3) write bucket contents to (remote/cloud) "temp" storage
4) (aka standard RESTORE) download SSTs from remote storage into memory, re-key them to map into this cluster's keyspace and write them to disk, then call ingest external file on that.

step 2) is likely to cause distsql to spill to its temp, disk-backed rocksdbs, in lots of little writes to rocks.
step 4) writes big files to disk, more or less all at once (the re-key processor throughput is pretty high and it is reading from memory).

4) does apply a good deal of memory pressure -- at least two copies of the SST data are kept in memory at some points -- but we limit the concurrency. For 2) I don't have much familiarity with the runtime behavior of the distsql side / how the disk spill works.

**Comment by dt** [comment]
also, I just noticed your import OOMed on SF=10? yikes.

**Comment by a-robinson** [comment]
Ok, so this was failing on step 2 of your description, meaning that the temporary DistSQL store was where the problematic writes were happening.

> also, I just noticed your import OOMed on SF=10? yikes.

Yeah. The machines only had 3.6GB of memory, though, if that makes you feel any better.

**Comment by mjibson** [comment]
Yes, this did fail in step 2 as described above. But the description is slightly inaccurate. It doesn't do the normal in-memory then spill-to-disk stuff that most distsql stuff does. Instead it always writes to disk (see https://github.com/cockroachdb/cockroach/blob/96753c76d4876ee5a02c1e604c8ea9d3d1bce5e2/pkg/ccl/sqlccl/csv.go#L1421). The exact source of the memory pressure is still unknown, though, since this was supposed to be relatively constrained there.

**Comment by a-robinson** [comment]
> maybe starting 968/<number of nodes> distsql processors per node is just a huge amount of memory.

@mjibson If I understand you properly, are all of those `968/<number of nodes>` processors running and writing to disk in parallel?

**Comment by mjibson** [comment]
Yes, they are.

**Comment by a-robinson** [comment]
Yowza, thanks.

**Comment by a-robinson** [comment]
Another data point: 2 out of 3 nodes OOM'ed when trying to run an SF-100 IMPORT on 3 n1-highmem-8 instances, which have 8 cores and 52GB of memory each.

**Comment by mjibson** [comment]
Yikes, ok. Maybe we thought it was a node liveness problem but was really oom. Sorry we didn't do more testing of this :(

**Comment by a-robinson** [comment]
Node liveness is definitely also an issue. It's both :)

**Comment by a-robinson** [comment]
Looks like there may still be dragons here. On a 3-node roachprod cluster with 16GB memory per machine, I ran an import of sf-100 (as I did in https://github.com/cockroachdb/cockroach/issues/20498) with `--cache=25% --max-sql-memory=50%`, and hit an OOM after the IMPORT checkpoint (i.e. after the sampling phase). Node 1, the gateway/coordinator for the IMPORT OOM'ed while the other two nodes survived:

Node 1 memory:
<img width="921" alt="screen shot 2017-12-05 at 4 21 40 pm" src="https://user-images.githubusercontent.com/7085343/33631463-a5d6817a-d9d8-11e7-84ec-69abc057eb3d.png">

Total cluster memory:
<img width="914" alt="screen shot 2017-12-05 at 4 24 20 pm" src="https://user-images.githubusercontent.com/7085343/33631521-c6e00ce2-d9d8-11e7-8ea4-198691fcdb68.png">

**Comment by mjibson** [comment]
Good news? I'm trying to reproduce the memory increase reported above but things appear stable after 6 hours. The IMPORT job is still running and memory has been fairly flat. This is on a 3 node default roachprod cluster. I've extended its time to see if it will complete.

![ss](https://user-images.githubusercontent.com/41181/33698059-24adc990-dad8-11e7-87dc-e132d265a64d.png)

**Comment by mjibson** [comment]
Didn't make it. The OOM killer killed node 1:

```
[49375.218000] Killed process 2950 (cockroach) total-vm:36433312kB, anon-rss:14954776kB, file-rss:0kB, shmem-rss:0kB
```

![ss](https://user-images.githubusercontent.com/41181/33735965-fb915176-db5e-11e7-83c8-17aef0fe4e8b.png)

**Comment by mjibson** [comment]
Also interestingly the temp directory only had a BACKUP-CHECKPOINT file in it, which means no SSTs were successfully uploaded.

**Comment by mjibson** [comment]
Latest OOM was due to #20700. Trying again on GCE with a 4 node cluster.

**Comment by mjibson** [comment]
sf-100 failed:

```
root@:26257/> import table lineitem create using 'gs://cockroach-fixtures/tpch-csv/schema/lineitem.sql' CSV DATA (
           -> 'gs://cockroach-fixtures/tpch-csv/sf-100/lineitem.tbl.1',
           -> 'gs://cockroach-fixtures/tpch-csv/sf-100/lineitem.tbl.2',
           -> 'gs://cockroach-fixtures/tpch-csv/sf-100/lineitem.tbl.3',
           -> 'gs://cockroach-fixtures/tpch-csv/sf-100/lineitem.tbl.4',
           -> 'gs://cockroach-fixtures/tpch-csv/sf-100/lineitem.tbl.5',
           -> 'gs://cockroach-fixtures/tpch-csv/sf-100/lineitem.tbl.6',
           -> 'gs://cockroach-fixtures/tpch-csv/sf-100/lineitem.tbl.7',
           -> 'gs://cockroach-fixtures/tpch-csv/sf-100/lineitem.tbl.8'
           -> ) WITH temp = 'gs://cockroach-tmp/csvtest-mjibson-100/', delimiter='|', transform_only, distributed;
pq: memory budget exceeded: 12204080 bytes requested, 3941917696 bytes in budget
```

**Comment by mjibson** [comment]
For now this is blocked in #20761

**Comment by mjibson** [comment]
I think this is fixed.
