### ISSUE TITLE
stability: investigate recovery from permanent unavailability

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#19645]
Suppose you run a cluster and one of more permanent node outages occur, leaving at least some ranges permanently in minority. Currently, there is no way to recover from this situation and we must come up with one. Generally, since data may have been lost, it may not be possible to completely recover. However, in many situations it would at least be possible to recover most of the state, save a few lost writes (due to having to take data from a follower that isn't up to date).

There are a few model cases:

1. three node cluster, two nodes catch fire and melt. Should be able to lose only some writes, but this could still mean partial transactions and violation of SQL integrity constraints.
1. five node cluster, three nodes disappear. Might lose a few whole ranges, but in principle most of the data may be recoverable. Big chunks of data might be missing.

@lego, would be interested in which types of corruption #19327 would be able to catch. Running these integrity checks would definitely be one of the steps carried out in this setting, and it would be nice to have that leave as little remaining room for error as possible.

**Comment by tschottdorf** [comment]
One aspect that was pointed out is that it would be nice if `AS OF SYSTEM TIME` could be used in the recovery to roll back to a consistent view of the data. Perhaps there is a connection with follower reads: if the lease holder dies in the unavailability event, the follower would still be able to serve "old enough" queries.

We've also previously talked about using `AS OF SYSTEM TIME` to create backups, which ties into this issue as long as `AS OF SYSTEM TIME` can be routed appropriately in the unavailable cluster.

**Comment by petermattis** [comment]
Is this a dup of https://github.com/cockroachdb/cockroach/issues/17186?

Agreed that any recovery would likely need to work in concert with SQL SCRUB in order to ensure consistent table state.

Using `AS OF SYSTEM TIME` to generate a backup and then restoring from the backup would be a nice general approach.

**Comment by tschottdorf** [comment]
Closing for #19645.
