### ISSUE TITLE
cli: improve ux when cluster is unavailable

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#19646]
Using, say, the `cockroach node` series of commands is ill-fated when the cluster is having problems. This is because commands tend to request information that queries internal system tables, and get stuck trying to do so. We should audit our cli commands for such shortcomings and address them appropriately by letting them return partial information.

**Comment by dianasaur323** [comment]
related to https://github.com/cockroachdb/cockroach/issues/16489

This is a 1.2 priority

**Comment by tschottdorf** [comment]
Ah, that issue is better. Thanks!

Closing for #16489.
