### ISSUE TITLE
cli: Support "Home" and "End" Key

### ISSUE THREAD

**Issue by leomkkwan** [cockroachdb/cockroach#19641]
I am using ubuntu and connect to terminal by putty from Windows. In Crdb Cli, arrow keys are working, also backspace and delete key. However, Home and End keys are not working. It's not a big deal, but it will be nice if that keys work.

**Comment by lego** [comment]
Hey @leomkkwan, it seems to be working for me (on OS X with iTerm) and someone else I poked using ubuntu. It may be how your shell is configured, how putty sends over the keystrokes, or just that we don't handle a different terminal code that your system is sending for Home + End.

Can you check what gets printed when you press Home and End through `cat`? For example, when I do it
```bash
# This one is home (omitting the ^C from CTRL+C)
$ cat
^[[H
# This one is end (omitting the ^C from CTRL+C)
$ cat
^[[F
```

**Comment by leomkkwan** [comment]
Thank you for looking into this.. This is what I get from my terminal.
For Home key
^[[1~
For End Key
^[[4~

**Comment by lego** [comment]
Yep it seems like putty is sending a pretty non-standard terminal code. I'd guess you're also not able to use Home+End in other applications.

It's an issue with how putty is configured, and you should be able to follow an answer here to fix that. https://superuser.com/questions/94436/how-to-configure-putty-so-that-home-end-pgup-pgdn-work-properly-in-bash. Hope that helps :)

Going to close this and rename the title to help anyone else who stumbles upon this.

**Comment by leomkkwan** [comment]
That's strange. vim and mysql cli are working for me. 

I will dig in and try to figure this out. Thanks again.

**Comment by leomkkwan** [comment]
My issue is gone magically when  I am testing on v1.2-alpha.20171211. Thank you.

**Comment by lego** [comment]
Great to hear! Thanks for letting me know @leomkkwan :)
