### ISSUE TITLE
storage: Test behavior when disk fills up

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#19656]
Prior to #19447, certain disk errors (the most likely being `ENOSPC`) were not being handled correctly, and we suspect that inconsistent reads could be served after this had happened. We need more testing of our behavior after disk writes have failed. 

One way to do this would be a process that alternately writes a file to fill up the disk (or maybe just `fallocate()`), waits a bit, then deletes the file (and restarts the cockroach process if it crashed). Maybe this would make sense as a new jepsen nemesis.

**Comment by tschottdorf** [comment]
Adding this to Jepsen might still make sense for the correctness aspect of this, but we have the infra for doing this in roachtest-land available. The test that comes to mind is

1. start a cluster with some background workload (one of the scaledata correctness tests comes to mind) and with a ballast file on one node
1. fill up disk on the node with the ballast file
1. wait until the process crashes
1. verify that background workload does not stall (#7882)
1. delete ballast file and restart node
1. verify that node becomes healthy and participates in cluster again

**Comment by tschottdorf** [comment]
#31187 also added the infra to run on a charybdefs and inject these errors, in case we don't want fallocate.

**Comment by tschottdorf** [comment]
Folding into https://github.com/cockroachdb/cockroach/issues/7882 (the other way than I originally planned to).
