### ISSUE TITLE
sql: finishInternalPlanner should close memory account

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#19662]
@justinj in #19575:

> I think finishInternalPlanner should also close the memory account associated with the planner's EvalContext? (via EvalContext.Stop()).

**Comment by jordanlewis** [comment]
@justinj I totally forget what this is about.

**Comment by knz** [comment]
@andreimatei i think you've killed the internal planner, right?

**Comment by andreimatei** [comment]
I haven't killed it, but I think this had been fixed since I've made the ctor for the internal planner return a cleanup function and made people call it.
