### ISSUE TITLE
sql: struct vs. interface for DJSON

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#19668]
It's known that interface dispatch in Go can be somewhat slow. DJSON is a natural union type (a DJSON can be one of `true`, `false`, `null`, a number, a string, an array, or an object). This leads to two obvious implementations: an interface type with a struct implementation of each of the seven, or a single struct containing a tag field and a separate field for each type requiring data. The second option is what has been implemented [at the moment](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/parser/datum.go#L1982-L1992) with an eye towards trying the other option. This issue tracks the other option and is a place to document the discussion regarding it.

I have a branch that implements all the features currently supported on master via an interface, and a very [rudimentary benchmark](https://gist.github.com/justinj/ac53d2ee36dcce403a2a6c5919d8a265) (`Compare` was the only operation on master when I wrote this and the document is just from the Wikipedia page).

The results of the benchmark are this:

Struct implementation (currently on master):
```
BenchmarkJSON-8          2000000               894 ns/op
```
Interface implementation (on my local branch):
```
BenchmarkJSON-8          1000000              2095 ns/op
```

However, the struct version is *significantly* heavier in terms of memory size of a datum - even just a `true` datum takes ~120 bytes to store given the bloat of all the other fields, compared to just a pointer for the interface implementation.

It's not immediately clear to me which direction to take this trade-off, although I'm leaning towards the interface implementation given that the memory difference is so significant. It's possible (though I haven't tried this yet) that some kind of hybrid approach is possible where we store some smaller/common types in a struct (`true`, `false`, `null`, ints) with a pointer to the larger ones?

I could also take both implementations further down the line to support storing them in columns to allow for a more detailed benchmark.

Interested in your thoughts @knz @jordanlewis @m-schneider @nvanbenschoten @petermattis

**Comment by nvanbenschoten** [comment]
`Compare` really isn't testing very much. In fact, I think I'd be more interested in the benchmark of `ParseDJSON` between the two.

> However, the struct version is significantly heavier in terms of memory size of a datum

Exact numbers here will be helpful in guiding your decision.

> It's possible that some kind of hybrid approach is possible where we store some smaller/common types in a struct (true, false, null, ints) with a pointer to the larger ones

This may be a smart optimization to make in the future if we go with the interface approach, but I don't think it should be factored in heavily to the decision here. Also, remember that `DBoolTrue`, `DBoolFalse`, and `DNull` are already shared between all uses so putting them in an interface won't incur any extra allocations. I think there was also talk of an intern table for small `DInts` a while ago. I'm not sure if that was ever pursued seriously.

I'd also consider how you plan to encode/decode `DJson` objects. I'd expect the interface approach to be a lot more conducive to sharing existing code (and using some of our batch allocation optimizations).

Finally, do all `DJson` variants behave exactly as they would if they weren't part of the `DJson` structure? For instance, is a `string` within a nested `DJson` object meant to be treated exactly the same as a normal `DString` when it comes to expression evaluation?

**Comment by justinj** [comment]
Very good call! The same JSON file with the parsing done in the benchmark:

Struct:
```
BenchmarkJSON-8      100000      15750 ns/op
```
Interface
```
BenchmarkJSON-8      100000      14218 ns/op
```

Which, given the memory considerations, sort of invalidates this whole debate, I guess! But I'll answer your other questions as well:

As far as exact numbers go, here are my test cases for `Datum` size for interface:
```
{`true`, 16},
{`false`, 16},
{`null`, 16},
{`"hello"`, 37},
{`["hello","goodbye"]`, 92},
{`{"a":"b"}`, 82},
```
and for struct:
```
{`true`, 120},
{`false`, 120},
{`null`, 120},
{`"hello"`, 125},
{`["hello","goodbye"]`, 372},
{`{"a":"b"}`, 258},
```

`DJSON` values are distinct from their corresponding SQL values - a JSON string is not the same as a SQL string, JSON `null` is distinct from SQL `NULL`, etc. Interestingly there isn't actually a nice way in Postgres to directly convert a JSON string to a SQL string: [see this question](https://stackoverflow.com/questions/27215216/postgres-how-to-convert-json-string-to-text) (we should maybe add a function for this).

**Comment by cuongdo** [comment]
What are the relative differences in memory allocation as you store larger JSON objects? I'm guessing that your test cases may not be representative of what users would typically store in a JSON column.

**Comment by justinj** [comment]
That's a good point, I tried the example document on wikipedia:
```json
{
  "firstName": "John",
  "lastName": "Smith",
  "isAlive": true,
  "age": 25,
  "address": {
    "streetAddress": "21 2nd Street",
    "city": "New York",
    "state": "NY",
    "postalCode": "10021-3100"
  },
  "phoneNumbers": [
    {
      "type": "home",
      "number": "212 555-1234"
    },
    {
      "type": "office",
      "number": "646 555-4567"
    },
    {
      "type": "mobile",
      "number": "123 456-7890"
    }
  ],
  "children": [],
  "spouse": null
}
```
 and (I realized I was actually under-counting for the struct version and fixed it for this measurement):
```
struct: 5992 bytes
interface: 1424 bytes
```

So it seems to hit around 4x difference. Given that and the perf difference for `ParseDJSON` (and the fact that the code I have using interfaces is nicer than the code I have using structs, I think it seems reasonable to go with interfaces.

**Comment by nvanbenschoten** [comment]
> DJSON values are distinct from their corresponding SQL values - a JSON string is not the same as a SQL string, JSON null is distinct from SQL NULL, etc.

Do the comparison of these types within JSON objects have the same semantics as the comparison of them outside of JSON objects? In other words, will be able to use the existing `CmpOps` for scalar JSON variants?

> So it seems to hit around 4x difference. Given that and the perf difference for ParseDJSON (and the fact that the code I have using interfaces is nicer than the code I have using structs, I think it seems reasonable to go with interfaces.

I agree. That seems like the right approach to pursue for now.
