### ISSUE TITLE
ui: NaN capacity

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#19666]
Seen on `register`.

![image](https://user-images.githubusercontent.com/5076964/32199551-63f0efd0-bda3-11e7-8376-e10585b3ef32.png)

**Comment by a-robinson** [comment]
On 1.0 or 1.1? There was an issue like this that got fixed at some point.

**Comment by tschottdorf** [comment]
This is a node on 1.1 in a cluster that's mostly 1.0.6, but I'll check what it looks like once everyone's on 1.1.1.

**Comment by tschottdorf** [comment]
Now that all nodes are on 1.1, the issue has resolved.
