### ISSUE TITLE
log: allow throttling log messages

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#19671]
Several times now I've wanted to be able to write something like:

```
log.OnceEvery(time.Minute).Info(ctx, "some spammy message")
```

Sometimes there's a struct handy where you can stash a `lastLogged` timestamp, but often not. It wouldn't be hard for the log package to maintain a global map of when messages were last logged, keyed by `{file, line}`, though. First candidate would be occasionally logging broken zone config decoding in #19551.

The jobs registry and anything else that logs node liveness failures could also benefit from this.

/cc @tschottdorf @a-robinson

**Comment by jordanlewis** [comment]
Cool idea - I like it!

**Comment by tschottdorf** [comment]
We have `log.Every` which does this. You can make a package-local variable and use that.
I'm going to close this issue, but feel free to reopen if you think there should be sugar around it.

**Comment by benesch** [comment]
🎉 nope, this is basically exactly what I had in mind.
