### ISSUE TITLE
sql: add the missing tests to the planning changes around FOR UPDATE

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#19676]
PR #19650 has added planning support for FOR UPDATE, propagating the flag throughout the data source hierarchy.

However the planning changes in that PR were not complemented by tests that would check the flag indeed propagates to those table scans involved in the SELECT clause, and not to other tables.

This should be tested via EXPLAIN.

Hence the following suggestion:
1. store the bit in the scanNode (even though the intents are not laid yet)
2. have the plan walker (`sql/walk.go`) reveal that bit
3. add EXPLAIN tests that show what happens for 1) simple queries 2) UPDATE/DELETE etc 3) with a join 4) with a join where only a subquery specifies the flag, e.g. `select ... from (select ... for update), (select ...)`

**Comment by rytaft** [comment]
PR #19650 was reverted with PR #20024.  It was decided that `SELECT FOR UPDATE` support would be postponed in PR #19577. Closing this issue.
