### ISSUE TITLE
jepsen: Dashboard

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#19695]
We've been running jepsen tests on a nightly basis for some time, but to the outside world it looks like we just did a one-off test last fall (I've been asked several times whether we still pass jepsen tests or have any updates since Kyle's analysis). We should have a publicly-visible dashboard of our jepsen test status/history, to show that everything's still working (or not, as the case may be).

Ideally this dashboard would show results for each of the release branches in addition to master, and distinguish between test automation failures (which are by far the most common) and actual failures of tested invariants.

**Comment by petermattis** [comment]
This is a good idea. We should consider this a product feature and note the marketing benefits.

Cc @nstewart, @jess-edwards

**Comment by jess-edwards** [comment]
This sounds very cool. Who would be interested in viewing something like this?

@bdarnell Ben - when you say you've been asked several times, who is asking you?

**Comment by bdarnell** [comment]
> Who would be interested in viewing something like this?

Mainly the same people who view our jepsen blog posts. Aside from the full dashboard, we may want some sort of badge elsewhere on the site like "Jepsen status: passed. Last verified: 2017-11-01" (or something similar on each release notes page, etc) that links to it. It could be a complement to a performance/benchmark dashboard. 

> when you say you've been asked several times, who is asking you?

Most recently it came up in two separate conversations at the HPTS conference. Aphyr's post has the date prominently displayed in its title, so people see it as a point in time rather than a repeatable analysis (which is fair - it took us a while to get everything automated and running smoothly).
