### ISSUE TITLE
Streamsets JDBC PostgreSQL Producer fails to INSERT data to CockroachDB

### ISSUE THREAD

**Issue by korpa** [cockroachdb/cockroach#19711]
As the error appeared in the Streamsets log file, I opened an issue in Streamsets' JIRA. But I'm not 100% sure if this is a Streamsets bug, I want to let you know and ask you if you could have a look as well: https://issues.streamsets.com/browse/SDC-7747

**Comment by jordanlewis** [comment]
Hi @korpa, it looks like this is a problem on the CockroachDB side. We're returning a syntax error from that query because we don't support `_pg_expandarray` or its special output column naming. Please follow #16971.

There may be a workaround for Streamset, but I can't say for sure.

**Comment by korpa** [comment]
Thanks for the quick reply. As workaround I will try to use "Streamsets JDBC Query" instead of "Streamsets JDBC Producer". 
I used "Streamsets JDBC Query" and CockroachDB already for UPSERT, as UPSERTs are not supported by "Streamsets JDBC Producer" currently. Hopefully pure INSERTS are faster, as UPSERTs in CockroachDB seem to be very slow.

**Comment by korpa** [comment]
Streamsets JDBC Query can be used as workaround. But INSERTs are as slow as UPSERTs.

**Comment by vivekmenezes** [comment]
@korpa are you happy with this resolution?

**Comment by korpa** [comment]
@vivekmenezes No, I'm not. Sorry. It is working, but as it is not optimized it is damn slow. So sadly CockroachDB is no option for my use case at the moment.

**Comment by vivekmenezes** [comment]
@korpa thanks for trying it out! I'm curious as to what performance numbers you saw and what you were expecting? We're working on improving performance significantly and it would be very valuable for us to hear your story. Your input is very much appreciated! Thanks
