### ISSUE TITLE
sql: prepare/execute and query datasources don't work together correctly

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#19716]
Observe the following sketchy interaction:

```
root@:26257/test> prepare u as SELECT $1:::int i, 'foo' t;
PREPARE

Time: 424.189µs

root@:26257/test> prepare v as select * from [execute u(3)] where t=$1;
pq: unsupported comparison operator: <string> = <int>
```

The problem here is evidently that the placeholder type information for the inner query overwrites that of the outer query. Inner queries of this form need to properly preserve the state of placeholders in the outer queries and restore them after they're finished.

cc @knz 

Hoping to roll a fix in for this in with the leaf placeholders PR sequence related to #19424.

**Comment by knz** [comment]
Woah, nice catch.
