### ISSUE TITLE
Reject ProposeRaftCommand from removed replicas

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#1972]
When a replica of a gossiped range is removed, the gossip goroutines may persist after the removal, and call ProposeRaftCommand. This will recreate the group in raft and hang the goroutine indefinitely. Store.ProposeRaftCommand should reject any commands for ranges that are not in the current `Store.ranges` map. 

Discovered in #1928.

**Comment by tschottdorf** [comment]
is this still current?

**Comment by bdarnell** [comment]
Fixed yesterday in #2893
