### ISSUE TITLE
build: stress runner ignores moving pkg

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#19733]
imagine the following:

1. commit 1: in pkg/foo, add a test `TestFoo`.
1. commit 2: move `pkg/foo` to `pkg/bar`
1. run CI
1. it will fail because the stress tester will try to run `TestFoo` in `pkg/foo` but that package is now absent.

Happened in #19663 before squashing.

Epic CRDB-10439

Jira issue: CRDB-5957

**Comment by knz** [comment]
cc @benesch
