### ISSUE TITLE
sql: limit size of primary and secondary keys

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#19751]
[cockroach.log.zip](https://github.com/cockroachdb/cockroach/files/1438992/cockroach.log.zip)

The above log from the pm cluster contains a single 1MB log message. The cause of the large log message is a range with an excessively long start key which is a sanitized SQL query that is part of the primary key for a table. Unfortunately, the cluster no longer contains table 60 so I'm not able to see the schema.

Besides causing very long log messages, such a large range start key will cause various operations on the range to be expensive. And the in-memory footprint of the range will be much larger than expected.

Possibly related to #19746.

**Comment by tschottdorf** [comment]
@jordanlewis from the discussions I've had about this, it seemed likely that this sort of restriction would be implemented at the SQL layer.

**Comment by ajwerner** [comment]
Big keys are a big problem. I don't really know what to do about this. The logging problems have been addressed with log message caps. There is work to do in #19746 but it's not quite clear who or when that will be addressed. I have a feeling that in upcoming cycles we're going to think harder about index keys for compliance reasons, maybe that'll be an opportunity to think harder also about size limits.
