### ISSUE TITLE
ui: [WIP] properly respond to CCL in admin UI

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#19759]
For tracking purposes - still TBD what this will exactly look like post a couple meetings next week.

This will cover two mainpoints
- incorporating CCL warnings in admin UI
- create a view when CCL license has expired
- create a view when user does not yet have CCL license

cc @couchand -> created this issue to track what you had mentioned in our meeting

Some additional notes: 
The question came up on #19850 what the fallback behavior should be in case a user of the OSS build tries a route that's only in the CCL version. My recommendation (alluded to above, but not made explicit) is that it just redirects to a nearby valid page if one makes sense.

An alternative would be a specific 404 page mentioning that the feature is only available with an enterprise license, with a link to https://www.cockroachlabs.com/product/cockroachdb-enterprise/

**Comment by couchand** [comment]
Closing as not actionable.
