### ISSUE TITLE
sql_safe_updates documentation is incorrect

### ISSUE THREAD

**Issue by jethrogb** [cockroachdb/cockroach#19775]
**bug report (documentation)**

The documentation for [`sql_safe_updates`](https://www.cockroachlabs.com/docs/stable/set-vars.html) reads:

> `true` for interactive sessions from the built-in SQL client, `false` for sessions from other clients

This appears to be incorrect, the variable is set to `true` even for non-interactive sessions:

```
$ cockroach sql --insecure -e 'DROP DATABASE IF EXISTS public'
# Server version: CockroachDB CCL v1.1.2 (linux amd64, built 2017/11/02 19:32:03, go1.8.3) (same version as client)
# Cluster ID: e39bd61a-bb22-49ea-ab30-2f2133f7f663
Error: pq: rejected: DROP DATABASE on non-empty database without explicit CASCADE (sql_safe_updates = true)
Failed running "sql"
$
```

**Comment by dianasaur323** [comment]
cc @jseldess

**Comment by jseldess** [comment]
cc @knz, is this supposed to happen even when using the sql client form the command line (now as an interactive shell)?

**Comment by knz** [comment]
Thanks Diana for finding this out!
There are two problems here:

1. Diana just found out that our detection of whether we're running interactively is probably incorrect. I would argue that our (or, at least, mine) understanding of what constitutes "interactive" is flawed: Until now, I, in accordance with my experience with other unix tools, expected "interactive" to refer to the interactive CLI shell only; however, the code currently determines a command is "interactive" as soon as the user is invoking it  manually on a terminal (like in Diana's example). It might well be that we have a mismatch between the docs and the code for other commands as well (insofar that other commands too change their behavior depending on whether they think they are running "interactively"). Probably, to resolve that mismatch, we should introduce a separation of concepts between "interactive via the SQL shell" and "emitting output on a user terminal", which is reasonably matching common unix terminology as well. This distinction must exist both in the code (that's probably on me) and in the docs (when necessary; we can talk again after I've audited the code).

2. Diana's issue also raises one of UX: *should* we protect the user against "dangerous" statements ran via `-e`? I really haven't thought about that use case when we initially introduced `sql_safe_updates`. *I personally think the current behavior is acceptable + desirable* (and thus perhaps the docs needs updating). However this decision does need a bit more consideration. To decide what we do here, we probably need to look at MySQL where this feature is coming from. I'll look into it too.

In any case, thanks for finding this out.

**Comment by knz** [comment]
Just for reference, initially I was thinking of non-interactive use when a user does `cat somefile.sql | cockroach sql`, in that case AFAIK if the file contains DROP DATABASE it will not be prevented by sql_safe_updates.

**Comment by jethrogb** [comment]
`-e` use is very common in shell scripts, see also `sed`, `perl`, `ruby`, etc.

**Comment by jethrogb** [comment]
Also, this still doesn't work:
```
$ echo "DROP DATABASE IF EXISTS public;" |cockroach sql --insecure
pq: rejected: DROP DATABASE on non-empty database without explicit CASCADE (sql_safe_updates = true)
Error: pq: rejected: DROP DATABASE on non-empty database without explicit CASCADE (sql_safe_updates = true)
Failed running "sql"
```
