### ISSUE TITLE
ui: NaN cluster capacity used

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#19782]
![image](https://user-images.githubusercontent.com/5076964/32389137-3634cb5c-c0a0-11e7-9304-0b52204aad8c.png)

Reported in https://forum.cockroachlabs.com/t/decommissioned-nodes-still-affect-admin-ui-cluster-overview/1079 on 1.1.2.

obligatory ping to @dianasaur323 (though I'm not sure you're really the person to throw these to, if not let me know!)

**Comment by dianasaur323** [comment]
@tschottdorf Thanks for filing! Yes, you can keep pinging me, since I add them to our backlog of UI things to fix. We should be able to fix this in our upcoming bug fix week.

**Comment by couchand** [comment]
Closed in #22864
