### ISSUE TITLE
acceptance: prettify RunInitCommand

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#19791]
`RunInitCommand` has a retry loop that is problematic. It should be rewritten into a retry loop that hits the health endpoint, and then a single invocation of the `Init` RPC.

This is fallout from https://github.com/cockroachdb/cockroach/pull/19753.

**Comment by petermattis** [comment]
Is there anything you want to do here given the new `roachprod/roachtest` world order?
