### ISSUE TITLE
ui: Reconcile github.io Plan Diagram Generator with Admin UI

### ISSUE THREAD

**Issue by mrtracy** [cockroachdb/cockroach#19807]
Currently, the output of "EXPLAIN" for SQL statements contains a URL to `cockroachdb.github.io` which will generate a visual diagram of the plan.  This works, however, there are a couple of oddities we should reconcile:

1.) CockroachDB already serves an Admin UI which is capable of generating this visualization; we may not need to link the user's to an external service.
2.) Even if the external service is appropriate (or even preferable for some reason), it's not clear to me that it is appropriately version-aware; that is, would a graph generated in a older version of CockroachDB still work when rendered at the github.io site?

We should evaluate the tradeoffs of the external site and make adjustments accordingly.

**Comment by dianasaur323** [comment]
@mrtracy thanks for looking into this. Just to add some context into this issue, my understanding is that this current visual diagram is made for CockroachDB developers, and we might have to repackage it for use by actual CockroachDB users. In light of that, I think when we do decide to build something here, we can go with approach 1 for the user-facing version that is no longer hosted on an external site. I'm ambivalent on whether or not the CockroachDB internal-facing tool is also ported over to match the user-facing one.
