### ISSUE TITLE
How to connnect to cr cluster?

### ISSUE THREAD

**Issue by guotie** [cockroachdb/cockroach#19804]
Is this a question, feature request, or bug report?

**QUESTION**

How to connect to the cluster by use github.com/lib/pg driver

**Comment by mberhault** [comment]
I assume you mean lib/pq. You can find examples in various languages in our docs. Here is the one for go using lib/pq: https://www.cockroachlabs.com/docs/stable/build-a-go-app-with-cockroachdb.html

**Comment by guotie** [comment]
Thanks.

The example only connect to a single node, How to connect to multiple node to make high-available?

**Comment by mberhault** [comment]
You can either handle multiple connections yourself, or setup a load balancer in front of all the cockroach nodes. We show how to setup haproxy in our docs: https://www.cockroachlabs.com/docs/stable/manual-deployment.html#step-5-set-up-haproxy-load-balancers
