### ISSUE TITLE
sql: select 1 from [delete from sometable] panics server

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#19805]
Incidentally, I think we should restrict the things permitted in the special `[stmt]` source to `EXPLAIN` and `SHOW`, to capture the original intent of adding this source syntax in 7ddde64d0a2d0abadfbc61651a84cf84ae15b4a3 and no more. This syntax is tricky and unseats assumptions about how plans can work.

```
        panic: panic while executing "select 1 from [delete from x];": runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0x47d4c16]

goroutine 254 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc4207762d0, 0x6817b20, 0xc420562570)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:181 +0x136
panic(0x5882380, 0xc420397660)
        /usr/local/Cellar/go/1.9.1/libexec/src/runtime/panic.go:491 +0x283
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve.func1(0xc42016b800, 0x6817b20, 0xc420cf7980)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:423 +0xa1
panic(0x5882380, 0xc420397660)
        /usr/local/Cellar/go/1.9.1/libexec/src/runtime/panic.go:491 +0x283
github.com/cockroachdb/cockroach/pkg/sql.(*Session).maybeRecover(0xc420479000, 0x5a7dee4, 0x9, 0xc42068152a, 0x1e)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/session.go:1384 +0x262
panic(0x584b180, 0x6d09500)
        /usr/local/Cellar/go/1.9.1/libexec/src/runtime/panic.go:491 +0x283
github.com/cockroachdb/cockroach/pkg/internal/client.(*Batch).appendReqs(0x0, 0xc421130328, 0x1, 0x1)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/internal/client/batch.go:308 +0x26
github.com/cockroachdb/cockroach/pkg/internal/client.(*Batch).DelRange(0x0, 0x5943dc0, 0xc42102a798, 0x5943dc0, 0xc42102a7b0, 0xc42028ca00)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/internal/client/batch.go:563 +0x197
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*RowDeleter).DeleteRow(0xc42102a708, 0x6817a60, 0xc4208df040, 0x0, 0xc42043b590, 0x1, 0x1, 0xc42102a700, 0x0, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/rowwriter.go:898 +0x3de
github.com/cockroachdb/cockroach/pkg/sql.(*tableDeleter).row(0xc42102a708, 0x6817a60, 0xc4208df040, 0xc42043b590, 0x1, 0x1, 0x0, 0xc4211305a8, 0x4f930c0, 0xc42102a6e0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/tablewriter.go:673 +0x7f
github.com/cockroachdb/cockroach/pkg/sql.(*deleteNode).Next(0xc42102a6e0, 0x6817a60, 0xc4208df040, 0xc420479210, 0xc42102a2c0, 0x7fffffffffffffff, 0x1)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/delete.go:173 +0x1f2
github.com/cockroachdb/cockroach/pkg/sql.(*renderNode).Next(0xc42102a2c0, 0x6817a60, 0xc4208df040, 0xc420479210, 0x0, 0x0, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/render.go:108 +0x56
github.com/cockroachdb/cockroach/pkg/sql.forEachRow(0x6817a60, 0xc4208df040, 0xc420479210, 0x6818420, 0xc42102a2c0, 0xc4211306a0, 0x0, 0xc42174c6c8)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:2024 +0x53
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execClassic(0xc4200a8900, 0xc420479210, 0x6818420, 0xc42102a2c0, 0x6823b80, 0xc42016b800, 0x0, 0x0)
```

**Comment by knz** [comment]
The error was due to a simple error in the DELETE code, see #19822.

>  I think we should restrict the things permitted in the special [stmt] source to EXPLAIN and SHOW, to capture the original intent of adding this source syntax in 7ddde64 and no more.

The intent was clear: every statement is a potential data source and should be usable as such. We should support more (ideally: all) statements in that position over time, not less. (I think the buck stops at DDL statements, but only insofar that they never return rows.)

> This syntax is tricky 

IMHO the word "tricky" doesn't apply to `SELECT ... FROM [<stmt>]`.

> [This syntax] unseats assumptions about how plans can work.

This is actually a good thing. The assumptions it unseats, are, IMHO, assumptions not worth holding. We should have more pure behavior, not less. The idea of "statement" in SQL is a syntactic construct; from the perspective of query execution there are *only* relational operators that return relations. INSERT/UPDATE/UPSERT/DELETE are merely relational operators with side effect in that regard.

**Comment by jordanlewis** [comment]
Thanks for the quick fix!

I didn't mean that the syntax itself is tricky - I think that it's actually a very natural way to express subqueries in datasource positions. Kudos on coming up with it. By the way, is there a good phrase you've been using for this syntax? Source statements? Statement sources? Something else? I have to re-decide what to call it every time :)

I meant that I'm nervous that the menagerie of new possible plans introduced by the syntax contain potential trickiness. The nested `EXECUTE`s are a big one, which #19809 solved., but I'm not yet convinced there are other problems. We do permit DDLs in source statements at the moment, which I'm definitely nervous about. Can we remove those? I wonder how they currently interact with auto retries, for example.
