### ISSUE TITLE
sqlccl: support IMPORT of empty csv files

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#19834]
Currently it errors with `pq: could not get first key`.

Originally from https://forum.cockroachlabs.com/t/import-observations-v1-2-alpha-20171026-darwin/1077

**Comment by danhhz** [comment]
Assigning to @mjibson for prioritization

**Comment by dianasaur323** [comment]
@danhhz thanks for filing and adding the label! tears of joy
