### ISSUE TITLE
storageccl: support s3-protocol compatible internal clouds in IMPORT/BACKUP/RESTORE

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#19832]
There are packages for running your own storage server that is compatible with the s3 protocol. Presumably, we should be able to support this in IMPORT/BACKUP/RESTORE by passing host overrides down to ExportStorage.

This is originally from a user request on the forum: https://forum.cockroachlabs.com/t/import-csv-does-not-work-with-minio-s3-store/1083/1

**Comment by danhhz** [comment]
Assigning to @mjibson to confirm that we indeed can't do this right now and for prioritization

**Comment by mjibson** [comment]
@dianasaur323 Could you prioritize this issue?

**Comment by glerchundi** [comment]
This would be fantastic, it can open up a wide range of solutions like ceph
& its ceph object gateway s3 api (using rook in a cloud-native fashion).

**Comment by dianasaur323** [comment]
@mjibson Yep! Added it into our backlog of features / ux next to another usability issue. Looking at our backlog, I think there are several testing initiatives that come in at a higher priority than this, but we might be able to get to it in 1.2.

**Comment by mjibson** [comment]
Also note that this can probably be completed in just a few hours. Most of the work will be in figuring out how to name this and writing a test. The actual implementation is really easy.

**Comment by dianasaur323** [comment]
Good to know. I'm not opposed to just getting this in, but I also don't think we need to context switch onto this over some of the other things we have prioritized right now. Your call, but it's currently marked as 1.2.
