### ISSUE TITLE
TestMultiuser is flaky

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#1984]
The following test appears to have failed:

[#5544](https://circleci.com/gh/cockroachdb/cockroach/5544):

```

```
Please assign, take a look and update the issue accordingly.

**Comment by tamird** [comment]
This was TestMultiuser.

**Comment by MBerhault** [comment]
yeah. it's flaky. I'll take a look.

**Comment by MBerhault** [comment]
This entire test is gone. There are no longer multiple users in KV.
