### ISSUE TITLE
BACKUP/RESTORE: mark revision_history and RESTORE AOST as experimental?

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#19887]
There are some untested corner cases, like how these interact with dropped or truncated tables (right now the table desc isn't available to restore it, the data isn't in the backup, etc).

I'm thinking we need more robust testing of these features before we call them GA-ready (and it sounds like the team agreed on this at our discussion). We could leave it as-is while we're testing it, and wait until 1.2 gets closer to decide how if we think it is ready before cutting the release. Alternatively, we could mark it experimental now, and then, if we're feeling better, remove that if we're feeling more confident later.

Also, if we are going to mark it, there's a bike shed to paint on the mechanics: setting vs syntax, on the backup option, the restore ASOT option, or both.

**Comment by dt** [comment]
cc @mjibson @danhhz

**Comment by dianasaur323** [comment]
ok, I took a look at the RFC https://reviewable.io/reviews/cockroachdb/cockroach/19175. It looks like SQL language extensions should be marked with EXPERIMENTAL directly in the syntax. However, since I kind of view Backup / Restore as separate from the generic SQL language, I'm still in the camp of using a cluster setting. This also makes the user experience a bit smoother, since once some administrator opens up that feature, people can proceed as usual.

**Comment by danhhz** [comment]
Is it crazy to do both? I personally don't think so. The cluster setting gives administrators the ability to globally disable things they are not comfortable with and adding EXPERIMENTAL in the syntax very clearly tells someone writing a query that it's not guaranteed to be up to our usual quality bar. Both add different value.

It's really not hard on our side to do both.

**Comment by danhhz** [comment]
Either way, in favor of making both of these experimental for a release

**Comment by mjibson** [comment]
Only the root user can even run these, so it's not quite as scary.

**Comment by dt** [comment]
2¢ `experimental_revision_history` on backup and ` EXPERIMENTAL AS OF SYSTEM TIME` on restore.

**Comment by dianasaur323** [comment]
@dt so not both, just SQL syntax?

**Comment by dt** [comment]
yeah, my suggestion is SQL syntax on both the BACKUP and RESTORE option.

**Comment by dianasaur323** [comment]
@dt Go with what you think makes the most sense. I'm wondering if one of our customers integrates this into some automated work with the EXPERIMENTAL flag though, and then has to re-write everything when we turn experimental off? Would we have to create an alias for it?

**Comment by danhhz** [comment]
i've been thinking about this more and i'm coming around on EXPERIMENTAL in the syntax but no cluster setting, btw

@dianasaur323 unless I'm missing something, aliases are pretty cheap technical debt

**Comment by dianasaur323** [comment]
nope, I think they are cheap. sounds like there is a majority with going with EXPERIMENTAL? @mjibson -> no strong concerns here?

**Comment by mjibson** [comment]
Nope. Whichever.
