### ISSUE TITLE
feature request: support faster snapshots 

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#19881]
This is a user request with more info here: https://forum.cockroachlabs.com/t/database-snapshot/1075

Sticking this in as a placeholder for tracking purposes. The use case is to allow quick snapshots of a point in time to support dev environments. There could also be the additional use case of restoring or importing a new cluster, where some of the safety rails / throttles we've created so as not to impact existing cluster traffic could be raised.

**Comment by dt** [comment]
backup/restore is our answer here (with incremental or various combinations of as-of-system-time).
