### ISSUE TITLE
ui: admin UI broken in Firefox on Linux

### ISSUE THREAD

**Issue by couchand** [cockroachdb/cockroach#19903]
In Firefox on Linux, the admin UI loads, but then redlines the CPU and is nonresponsive.  The browser can switch tabs, but no refresh, scroll, or input events are no longer handled.  The dev console can open, but it just sits with a loading indicator, and also doesn't respond to events.

This behavior started in 2016 some time.

**Comment by knz** [comment]
Behavior repros in both FF 56 and 57.

**Comment by couchand** [comment]
What's curious about this is that I do most of my development in Firefox, frequently on Ubuntu.  I'm currently on FF 56.  We'll need to dig into this to figure out what the difference is.

**Comment by JYKeith123** [comment]
Also not working on Windows 10 (firfox v.56.0.2 64bit). Firfox stops when I enter 'View nodes list' page.

**Comment by jordanlewis** [comment]
Closing due to age, please reopen a new issue if you still have this issue

**Comment by knz** [comment]
I confirm it is solved in the latest version of crdb with latest firefox.
