### ISSUE TITLE
ui: debug range page fails to load on the first time

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#19920]
The first time I visit `/#/reports/range/<rangeID>` I see a message about "Updating cluster status", but the page never loads. If I reload that URL the range debug info shows up almost immediately. This is very repeatable for me on a 3-node GCE cluster. Happens for every range I try.

**Comment by dianasaur323** [comment]
ah, this happened to me earlier too! +1

**Comment by couchand** [comment]
I can replicate this, but only when switching from one range to another.  Going to the range page from anywhere else loads fine.  Is that the same behavior you're seeing?

**Comment by a-robinson** [comment]
> I can replicate this, but only when switching from one range to another. Going to the range page from anywhere else loads fine. Is that the same behavior you're seeing?

That's the behavior I've seen.

**Comment by BramGruneir** [comment]
I can replicate it as well.  I'll try to track it down at some point.

**Comment by petermattis** [comment]
> I can replicate this, but only when switching from one range to another. Going to the range page from anywhere else loads fine. Is that the same behavior you're seeing?

Yep, that's the behavior I'm seeing.

**Comment by a-robinson** [comment]
Fixed by https://github.com/cockroachdb/cockroach/pull/20828
