### ISSUE TITLE
cockroach node status should show when a node is dead

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#19924]
I would expect cockroach node status to tell me if a node is dead. In the below example, one of my nodes is **definitely** dead, but it only shows up if I add the --all flag.

![image](https://user-images.githubusercontent.com/5768024/32574779-29bbeaf0-c4a0-11e7-9b31-73e497897c0f.png)

![image](https://user-images.githubusercontent.com/5768024/32574795-31160a6a-c4a0-11e7-8905-7b304407bc28.png)

I guess the updated at timestamp gives some insight, but it seems a little odd for it to not be more clear...

**Comment by tschottdorf** [comment]
Closing for #16489.
