### ISSUE TITLE
sql: background lease renewal for tableID=55 tableName=“blocks” failed: descriptor not found

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#19940]
During a nightly blockwriter load test.

https://teamcity.cockroachdb.com/viewLog.html?buildId=403237&buildTypeId=C_BW_4Nodes_6Hours&tab=buildResultsDiv#

The first, third and fourth nodes post this in a busy loop:

```
E171109 11:18:43.095282 6355217 sql/lease.go:992  background lease renewal for tableID=55 tableName=“blocks” failed: descriptor not found
E171109 11:18:43.101027 6355246 sql/lease.go:992  background lease renewal for tableID=55 tableName=“blocks” failed: descriptor not found
E171109 11:18:43.105208 6355253 sql/lease.go:992  background lease renewal for tableID=55 tableName=“blocks” failed: descriptor not found
```

the third node has no such flurry of errors, but instead

```
E171109 11:19:55.066369 150 sql/jobs/registry.go:154  error while adopting jobs: database “system” does not exist
```

Additionally, two of the four block writers spam

```
2017/11/09 11:19:43 pq: relation "blocks" does not exist
2017/11/09 11:19:43 pq: relation "blocks" does not exist
2017/11/09 11:19:43 pq: relation "blocks" does not exist
```

**Comment by tschottdorf** [comment]
@vivekmenezes for triage, this seems pretty serious.

**Comment by vivekmenezes** [comment]
```E171109 11:19:51.962846 206 sql/jobs/registry.go:154  error while adopting jobs: database "system" does not exist```

doesn't look very good

**Comment by vivekmenezes** [comment]
assigning to @nvanbenschoten who is likely to be investigating a similar issue on the PM cluster

**Comment by nvanbenschoten** [comment]
Unless we see this again, I think it's safe to say that this was an artifact of https://github.com/cockroachdb/cockroach/issues/19947. As we saw in that issue, replicas seemed to be missing large chunks of their keyspace, which could materialize in missing table descriptors. I'm going to close for now, but will reopen if we see this in isolation without the associated consistency check failures.
