### ISSUE TITLE
stability: consistency anomalies after RocksDB upgrade

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#19947]
We're seeing a lot of consistency violations on various clusters since RocksDB has been upgraded. For example, #19906 #19940 #19939 and a bunch of nightly failures are suspected to have this as a root cause.

From what I've seen, the consistency checker always finds that some replicas are missing big chunks of keyspace.

We should roll back the RocksDB upgrade to verify that this restores sanity, and then go searching for the origins of the problem. There is also the unlikely (and undesirable) case in which this is not actually related to the RocksDB bump, which we also want to assess quickly.

**Comment by tschottdorf** [comment]
The upgrade has been rolled back and tentatively it's looking good so far. Assigning @mberhault to figure out what the problem is.

**Comment by mberhault** [comment]
uh. Thanks. I guess I can try to reproduce it so it happens reasonably quickly, then bisect rocksdb. Fun fun.

**Comment by tschottdorf** [comment]
Feel free to kick this elsewhere, but you seemed like the canonical entry point. I think I mentioned this before, but disabling range deletion tombstones and seeing whether that "fixes" the problem would be one thing to try. If that does fix it, we might be able to spot the offending commit. Otherwise, yeah, it'll be more annoying...

**Comment by mberhault** [comment]
I'm trying to reproduce this.

I started with a 5 node ephemeral cluster running in insecure mode with envs:
```
  COCKROACH_CONSISTENCY_CHECK_INTERVAL=1m,
  COCKROACH_CONSISTENCY_CHECK_PANIC_ON_FAILURE="true",
```

The 1m is probably a problem, that's too aggressive.

Each node has `kv --concurrency 64 --tolerate-errors --min-block-bytes=8 --max-block-bytes=128 --read-percent=50 --splits=1000` running against it (localhost)

Within minutes, the first node OOMs, then OOMs upon restart every time.
Enabling jemalloc profiling shows:
```
Total: 12914.1 MB
 12910.7 100.0% 100.0%  12910.7 100.0% std::_Rb_tree::_M_emplace_equal
     1.2   0.0% 100.0%      1.2   0.0% rocksdb::ReadBlockContents
     0.6   0.0% 100.0%      0.6   0.0% rocksdb::CoreLocalArray::CoreLocalArray
     0.5   0.0% 100.0%      0.5   0.0% rocksdb::LRUCache::LRUCache
     0.5   0.0% 100.0%      1.0   0.0% std::vector::vector
     0.5   0.0% 100.0%      0.5   0.0% std::__cxx11::basic_string::_M_construct [clone .isra.206]
     0.0   0.0% 100.0%   6265.6  48.5% DBImpl::NewIter
     0.0   0.0% 100.0%      0.6   0.0% DBMakeOptions
     0.0   0.0% 100.0%   6265.6  48.5% DBNewIter
     0.0   0.0% 100.0%      0.6   0.0% DBOpen
```

[jemalloc.pdf](https://github.com/cockroachdb/cockroach/files/1471302/jemalloc.pdf)

**Comment by mberhault** [comment]
Ok, trying again with the 1h consistency check, I get two nodes crashing with:
```
F171114 15:14:48.938361 1374995 storage/replica_command.go:978  [n4,s4,r5183/3:/Table/51/1/368{38653â<80>¦-94789â<80>¦}] consistency check failed with 1 inconsistent replicas
```
In less than 10 minutes. Will keep trying to see if it's semi-reliable.

**Comment by tschottdorf** [comment]
Note that @richardwu claims to have seen the inconsistency on current `master`.

**Comment by nvanbenschoten** [comment]
Looks like @richardwu's cluster was still using RocksDB 5.9:

```
Nathans-MBP:node5$ head OPTIONS-000461
# This is a RocksDB option file.
#
# For detailed file format spec, please refer to the example file
# in examples/rocksdb_option_file_example.ini
#

[Version]
  rocksdb_version=5.9.0
  options_file_version=1.1
```

He said the branch he was running may not have been rebased off of the RocksDB 5.9 revert, so it looks like everything there checks out.

**Comment by mberhault** [comment]
That's reassuring, I'm almost done with my bisection (assuming my <10m crash estimate is correct and not just luck. So far it's been ~7m and I've been letting things run for at least 20).

Current state after 9 runs:
```
#######BAD 593d3de No need for Restart Interval for meta blocks
2b22baf Add a template for issues
ab0542f Fix for when block.cache_handle is nullptr
#######TESTING 5df172d fix deletion-triggered compaction in table builder
385049b WritePrepared Txn: Recovery
#######GOOD 8c724f5 Default one to rocksdb:x64-windows
```

**Comment by tschottdorf** [comment]
🍿

**Comment by mberhault** [comment]
Oh fun:
```
#######BAD 593d3de No need for Restart Interval for meta blocks
#######SKIPPED 2b22baf Add a template for issues
#######GOOD ab0542f Fix for when block.cache_handle is nullptr
```

The skipped one is just a .md file.
The culprit according to my run is https://github.com/facebook/rocksdb/commit/593d3de37171d99a761ce2ab34ffa12654acd055, but I have no idea what's going on there.

**Comment by petermattis** [comment]
That change seems innocuous. How hard did you try to reproduce at ab0542f?

**Comment by mberhault** [comment]
I'm rerunning it now. So far, all my failing runs failed around 7-8 minutes, and all the passing ones ran for at least 20.
There are three good runs close to each other: either I'm really unlucky, or this indeed the problem:
```
#######BAD 880411f disable populating block cache for in-place updates
d27258d WritePrepared Txn: Rollback
bb38cd0 Limit number of merge operands in Cassandra merge operator
cf51d3e Remove an "unused" variable
983028f RocksJava build target for Docker on ppc64le
2a3363d ldb dump can print histogram of value size
#######BAD 593d3de No need for Restart Interval for meta blocks
#######SKIPPED 2b22baf Add a template for issues
#######GOOD ab0542f Fix for when block.cache_handle is nullptr
#######GOOD 5df172d fix deletion-triggered compaction in table builder
385049b WritePrepared Txn: Recovery
#######GOOD 8c724f5 Default one to rocksdb:x64-windows
```

**Comment by mberhault** [comment]
After re-running it, I'll pick some other failing ones, reproduce, revert, run again.

**Comment by petermattis** [comment]
On the other hand, 593d3de does change the restart interval for range deletion blocks. If there is a problem with that commit, it is likely the change to `table/block_based_table_builder.cc`.

**Comment by mberhault** [comment]
Saving my git bisect log here for info:
```
$ git bisect log
git bisect start
# bad: [f1b040c14a5b645a8127709ff9cefc5ecd288031] Blob DB: Fix flaky BlobDBTest::GCExpiredKeyWhileOverwriting test
git bisect bad f1b040c14a5b645a8127709ff9cefc5ecd288031
# good: [dc5f29f32f6c3abaf73f961817f61653236f81b6] EnvWrapper: Forward more functions
git bisect good dc5f29f32f6c3abaf73f961817f61653236f81b6
# bad: [880411f54cdcb8da216722bc2f7bbe9ae6859e00] disable populating block cache for in-place updates
git bisect bad 880411f54cdcb8da216722bc2f7bbe9ae6859e00
# good: [9a970c81af9807071bd690f4c808c5045866291a] Fix WriteBatchWithIndex::GetFromBatchAndDB not allowing StackableDB
git bisect good 9a970c81af9807071bd690f4c808c5045866291a
# good: [be97dbb15c1bb59f54916afac62b7abf39e18d02] Fix WritePreparedTransactionTest::SeqAdvanceTest ASAN failure
git bisect good be97dbb15c1bb59f54916afac62b7abf39e18d02
# good: [8c724f5c7fb6dbba35db2a43d52c24592c215acf] Default one to rocksdb:x64-windows
git bisect good 8c724f5c7fb6dbba35db2a43d52c24592c215acf
# bad: [593d3de37171d99a761ce2ab34ffa12654acd055] No need for Restart Interval for meta blocks
git bisect bad 593d3de37171d99a761ce2ab34ffa12654acd055
# good: [5df172da2f6acd3e3e6cd928bd0b66db722357df] fix deletion-triggered compaction in table builder
git bisect good 5df172da2f6acd3e3e6cd928bd0b66db722357df
# skip: [2b22baf3044c417832d2352ee968b1eaf65cbb00] Add a template for issues
git bisect skip 2b22baf3044c417832d2352ee968b1eaf65cbb00
# good: [ab0542f5ec6e7c7e405267eaa2e2a603a77d570b] Fix for when block.cache_handle is nullptr
git bisect good ab0542f5ec6e7c7e405267eaa2e2a603a77d570b
# only skipped commits left to test
# possible first bad commit: [593d3de37171d99a761ce2ab34ffa12654acd055] No need for Restart Interval for meta blocks
# possible first bad commit: [2b22baf3044c417832d2352ee968b1eaf65cbb00] Add a template for issues
```

**Comment by mberhault** [comment]
Second run at ab0542f was happy.
Trying head of 5.9 branch + revert of 593d3de.

**Comment by mberhault** [comment]
Reverted head looks ok after 18m. Trying f1b040c again. Then will re-run all this a couple of times.
So far, all failures/successes confirm the problem at 593d3de.

**Comment by tschottdorf** [comment]
What if you only revert the one line change in `table/block_based_table_builder.cc`?

**Comment by mberhault** [comment]
Don't know yet, but 5.9.fb is now passing. My initial failure was with https://github.com/cockroachdb/rocksdb/commits/crl-release-5.9.0 which is 5 commits behind + 2 custom patches.

**Comment by mberhault** [comment]
Ok, I reran f1b040c (which passed the first time). It properly failed the last two times, so there is some flakiness in my good/bad test.
I'm re-running f1b040c with reverted 593d3de and will do so a few times.
So far, that one successful run of f1b040c is the only outlier.

**Comment by bdarnell** [comment]
I've found something that looks like the bug, but it looks so basic that I feel like I must be missing something: `Block::NewIterator` assumes that [any block with no restart points is empty](https://github.com/facebook/rocksdb/blob/175d5d6a9e7c6138e678429618759504f7f7e6e4/table/block.cc#L434-L440). I think that 593d3de is the culprit in that it caused some non-empty blocks to have no restart points, and the only reason that appeared to work is that the blocks affected by this are usually either A) actually empty or B) read through non-iterator interfaces. This is *probably* the range-deletion block since that's the usual candidate for "rocksdb feature we use that most people don't".

**Comment by tschottdorf** [comment]
Looks like we were right to suspect range deletions before we even started testing anything. Time to file upstream, it seems?

**Comment by bdarnell** [comment]
Yeah, I'll file it upstream.

**Comment by petermattis** [comment]
I'm not sure if that is the bug. It looks like blocks always have at least one restart point. See the `BlockBuilder` constructor.

**Comment by bdarnell** [comment]
Yeah, I just saw that too. I'll file the upstream issue anyway (our bisection seems solid enough at this point) but without pointing the finger at this particular piece of code.

**Comment by mberhault** [comment]
5.9 + revert of 593d3de is still ok after 1h. I'll let it run overnight.

**Comment by mberhault** [comment]
Cluster died due to out-of-disk a few hours ago (I forgot to rebuild roachprod, so I was still on small local PSSDs). No other errors seen.

**Comment by zhangjinpeng1987** [comment]
@tschottdorf Can you dump RocksDB's manifest and check if there are something wrong with the range of SST files.
