### ISSUE TITLE
sql: support TIMESTAMP and DATE column types

### ISSUE THREAD

**Issue by arypurnomoz** [cockroachdb/cockroach#1995]

**Comment by petermattis** [comment]
Support for `TIMESTAMP` and `DATE` columns still needs to be implemented. Doing so isn't particularly difficult if anyone wants to take this on, it just needs to be plumbed through a variety of places (e.g. expression evaluation, value marshaling, key encoding/decoding, client-side arguments, etc).

**Comment by vivekmenezes** [comment]
I'm working on this.

**Comment by vivekmenezes** [comment]
https://github.com/cockroachdb/cockroach/pull/2314

**Comment by petermattis** [comment]
FYI, your commit descriptions can reference bugs. See https://help.github.com/articles/closing-issues-via-commit-messages/ and https://guides.github.com/features/issues/#notifications.
