### ISSUE TITLE
kv: local server optimization is brittle

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#19991]
In https://github.com/cockroachdb/cockroach/issues/17611, I realized that the local server optimization path was *never* taken. Investigating, I found that the nodes were running without `--host` but with `--advertise-host`. As a result, all outgoing RPCs were addressed to `<hostname>.crdb.io` (from `--advertise-host`) but the node identified itself with its default host flag, `<hostname>`. This was "fixed" by using `--host <hostname>.crdb.io` instead of `--advertise-host`, but this mechanism shouldn't be so easy to accidentally break.

It may also not even be possible for everyone to set this up this way. For example, it's at the very least super annoying that with the change, the process doesn't listen on localhost any more.

**Comment by tschottdorf** [comment]
@cuongdo for triage.

**Comment by tschottdorf** [comment]
I think the code here should simply use `AdvertiseAddr` except for `Addr` (depending on what `AdvertiseAddr` is initialized to in the absence of `--advertise-host` (I'm assuming it equals `Addr` in that case)?

```go
// GetLocalInternalServerForAddr returns the context's internal batch server
// for target, if it exists.
func (ctx *Context) GetLocalInternalServerForAddr(target string) roachpb.InternalServer {
	if target == ctx.Addr {
		return ctx.localInternalServer
	}
	return nil
}
```

**Comment by a-robinson** [comment]
Yeah, I think switching that method to use `AdvertiseAddr` would do the trick. We do set `AdvertiseAddr` to the same as `Addr` in the absence of `--advertise-host`, and `AdvertiseAddr` is always the address we advertise as associated with the node (as you would expect given the name).

Good find!
