### ISSUE TITLE
sqlccl: http export storage is too restrictive in what codes mean success

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#20017]
There is an explicit check for `if resp.StatusCode != 200 {`, but 200 is not the only status code that means success. This request is from one of our customers.

**Comment by mjibson** [comment]
I need some more context here. What is the status code they are getting instead? Which http server was this running against? Which operation (read/write/head/delete) was this?

**Comment by kaavee315** [comment]
I was running on nginx server with the configuration as suggested here https://www.cockroachlabs.com/docs/stable/create-a-file-server.html#using-nginx-as-a-file-server
nginx sends statusCode `201` and `204` on success of `PUT` request, which is not being handled correctly

**Comment by mjibson** [comment]
Great, thanks. Will fix.

**Comment by mjibson** [comment]
This has been fixed and will be in the next alpha release. Thanks for the report.
