### ISSUE TITLE
release v1.2-alpha.20171120

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#20026]
Candidate SHA: ab5c4ecf070d137d0e8671a7de6d53dc76dbb39a.
Deployment status: adriatic, omega.

[Release process checklist](https://github.com/cockroachdb/cockroach/wiki/Release-Process)

Prep date: `2017-11-14`
- [X] [Pick a sha](https://github.com/cockroachdb/cockroach/wiki/Release-Process#pick-sha), fill in `Candidate SHA` above.
- [x] [Deploy to test clusters](https://github.com/cockroachdb/cockroach/wiki/Release-Process#deploy-to-test-clusters)
- [x] fill in `Deployment status` above
- [x] Connect to a node (`crl-sql adriatic 1`) and ask it to crash `select crdb_internal.force_panic('testing');` to verify that the crash report appears in sentry.io.
- Keep an eye on clusters until release date.

Release date: `2017-11-20`
- [ ] [Check cluster status](https://github.com/cockroachdb/cockroach/wiki/Release-Process#check-cluster)
- [ ] [Tag release](https://github.com/cockroachdb/cockroach/wiki/Release-Process#tag-release)
- [ ] [Trigger release build](https://github.com/cockroachdb/cockroach/wiki/Release-Process#trigger-build)
- [ ] [Check binaries](https://github.com/cockroachdb/cockroach/wiki/Release-Process#check-binaries)
- [ ] Update docs
- [ ] External communications for release
- [ ] File issue for next release and assign to release coordinator

**Comment by couchand** [comment]
Due to the issues noted in #20118, we have not been collecting status information from the test clusters for the past three days.  Since we don't have enough information to qualify this release, we will not be releasing this week.

**Comment by couchand** [comment]
Next release: #20176
