### ISSUE TITLE
ui: show "ghost" time series for context

### ISSUE THREAD

**Issue by couchand** [cockroachdb/cockroach#20021]
@bdarnell suggested that the most useful view for the time series charts would show the past 24 hours along with the same time period from the previous week.  @danhhz confirmed that this has been valuable for him in the past as well.

This seems like a good way to add more helpful context to the chart.  There are a few questions about how to generalize the principle as the user changes time scales, and how exactly to display it.

Jira issue: CRDB-5944

**Comment by cuongdo** [comment]
This would've been useful for the databases I've administered in the past.

**Comment by bdarnell** [comment]
> There are a few questions about how to generalize the principle as the user changes time scales

There are two parts to my suggestion: default to 24h, and show a one-week-old "ghost". The former is debatable (for a new cluster it's nice to get a more closely-zoomed view) and should at least be configurable, but I've found that no matter what time scale I look at the week-ago view is a helpful point of comparison. 

The biggest drawback to this is that it doubles the number of lines on the graph, so it gets really confusing when more than one timeseries is visible on the same graph.

**Comment by dianasaur323** [comment]
@bdarnell We can have design mock up some views that make the number of lines more consumable. That being said, I don't think this is going to make it into 1.2. Marking it for 1.3 for now, unless there is significant pushback, in which case we would have to drop something from the current development plan.
