### ISSUE TITLE
cli/conn: cockroach sql stalls if trying to connect to the UI port

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#20029]
Trying to connect to the admin UI port (instead of the pgwire port) just blocks the client instead of saying anything. I really hope there's something better we can do.

@vivekmenezes how do we go about triaging cli bugs? :S

```
[andrei:~/work/src/github.com/cockroachdb/cockroach] c726df221+ ± ./cockroach sql --insecure -p 26260
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.
#

<and now we wait>
```

**Comment by bdarnell** [comment]
The UI port is just an HTTP server, so there's not much we can do here. I think it would be possible to set something up with cmux to detect this and route it to a dummy pgwire implementation to return an error, but that seems like an awfully heavyweight solution just to give a better error message for one very specific mistake.

**Comment by nvanbenschoten** [comment]
@bdarnell should we just close this then?

**Comment by bdarnell** [comment]
Yes, I think so.
