### ISSUE TITLE
sql: don't use a SELECT node when not needed in DELETE, UPDATE

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#2004]
Currently, DELETE and UPDATE always construct a SELECT statement even if not needed (eg: `DELETE FROM t` or `DELETE FROM t WHERE 1 = 1`)

One implication is that we always required `READ` (and in the future `SELECT`) privileges for `DELETE` and `UPDATE`. Both postgres and mysql required `SELECT` only when needed based on the `WHERE` clause.

**Comment by tschottdorf** [comment]
after the sanitation step suggested by @petermattis that boils down to checking whether `p.Where` is a `DBool`, and deleting all/none accordingly, right?

Of course, that would likely allow `DELETE FROM t WHERE t IN (SELECT 1)` because a `SELECT 1` would be optimized away as well, but that seems acceptable.

**Comment by tamird** [comment]
@paperstreet can you give an update here?

**Comment by paperstreet** [comment]
We've started to move away from using the public SELECT code inside UPDATE and DELETE because they needed to be able to fetch columns in mutations. I haven't looked at the privileges, but there's no reason it couldn't work similarly to how `scanVisibility` got plumbed down.

**Comment by tamird** [comment]
Cool; I'm going to assign you to this one. Low priority, something to look it between context switches.

**Comment by spencerkimball** [comment]
@danhhz @knz is this still a problem?

**Comment by knz** [comment]
Yes there is still a select clause in there.

**Comment by spencerkimball** [comment]
We're trying to figure out 1.0 milestones. Please either move this off of the 1.0 milestone or set its priority.

**Comment by knz** [comment]
Sorry priorities have not been explained to me yet. I do not know what to do.
This is a feature bug where privileges are not checked properly. There are workarounds, so we may be able to pass it as a known limitation in docs. However either that or a fix must make it to 1.0.

**Comment by spencerkimball** [comment]
OK, I reclassified it.

**Comment by jseldess** [comment]
Limitation documented with https://github.com/cockroachdb/docs/pull/1381#pullrequestreview-37154653

**Comment by dianasaur323** [comment]
Is this still a bug? If so, we should make sure it doesn't remain hidden under the no milestone bucket... Moving to 1.2.

**Comment by knz** [comment]
After the two years this issue has been open, no user ever complained to us that they were bothered by the permissions. The implementation of the mutations uses a common code path (the PK is read by a table scanner, which checks for SELECT permissions) and it would be odd to plumb booleans just to have a different permission checking depending on the context.

The trade-off is not beneficial, so i am closing this issue.
