### ISSUE TITLE
sql: allow index hints for UPDATE and DELETE

### ISSUE THREAD

**Issue by couchand** [cockroachdb/cockroach#20048]
Index hints (e.g. `SELECT foo FROM bar@baz` to use the `baz` index on `bar`) are a good way to force the use of a particular index when the user knows the right access pattern for a given query.  Unfortunately, they currently only work on `SELECT` queries, but we could extend them to be available for use on `UPDATE` and `DELETE` queries, too.

Community request from Gitter.

**Comment by couchand** [comment]
@awoods187 assigning to you for triage/roadmapping.

**Comment by bsnyder788** [comment]
I would like to work on this one.  If you guys have any pointers feel free to send them my way :)

**Comment by bsnyder788** [comment]
Thanks @justinj, I will wait for more input before digging in then.

**Comment by RaduBerinde** [comment]
The relevant index selection code is "above" the index constraint generation code which changed, so it wouldn't affect this kind of change.

**Comment by knz** [comment]
Fixed in #31012.
