### ISSUE TITLE
kv: add optional common key prefix to batch writes and scan responses

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#20059]
Currently, a large batch of `PutRequest`s to keys with a common prefix is wasteful with respect to memory use on the sender side as well as (pre-compression) network bandwidth: the common prefix is repeated in each `PutRequest.Span`.

This is especially wasteful when putting a batch of keys with a very long common prefix. This can happen in several situations. Here are some examples:
- Writing keys to a table with a multi-column primary key, where the first column is a large value and is repeated across all of the new keys
- Writing keys to a deeply nested interleaved index
- Writing inverted index keys for a very deep JSON object

The same inefficiency is present in `ScanResponse` objects which contain keys with shared prefixes.

It would be nice to find a way to elide the shared prefixes from the API and associated in-memory objects. This could have a performance impact for large table scans (cc @arjunravinarayan) and write batches.

One way of doing this would be to augment the `BatchRequestHeader` and `ScanResponse` protos with a `sharedPrefix` field that contains the shared prefix. I'm sure there are a lot of pitfalls here, though. I'd like to get some opinions on how feasible and potentially impactful this idea is.

cc @justinj @nvanbenschoten @petermattis

**Comment by petermattis** [comment]
Interesting idea. I think returning a `WriteBatch` will be a bigger win, but this is orthogonal (we could pull the shared prefix from the `WriteBatch` as well). 

Doing this for `ScanResponse` will be complicated by the need to combine responses. See `ScanResponse.combine`. Not impossible to deal with, just a complication.

Should definitely do some measurements to see how much of a win this could be. Also would need to check the benefit when RPC-level compression is enabled.

**Comment by nvanbenschoten** [comment]
Another complication for doing this in request messages is that on the receiver side we have a few data structures (`spanSet`, `cmdQueue`, `tscache`, etc.) that work directly on the key spans specified in `BatchRequests`. If we were to make a change like this, these structures would either need to:
- be modified to handle shared key prefixes. Instead of holding onto `[]byte` keys, they'd probably have to hold onto some kind of `{prefix *[]byte, suffix []byte}` structure.
- denormalize the shared prefixes (`key1 = append(prefix, suffix1)`, ...) to work on the full keys again, essentially eliminating any benefit we get from the common key prefixes and resulting in extra work and memory usage.

**Comment by nvanbenschoten** [comment]
Moving this to "later". It's still an interesting idea, but I agree with Peter that there is almost certainly more lower hanging fruit.

**Comment by jordanlewis** [comment]
@nvanbenschoten I'm going to unassign this. You should feel free to close it, there's no point in keeping it around probably.

**Comment by nvanbenschoten** [comment]
There might actually be renewed interest in this as we look towards namespacing the kv keyspace with a tenant identifier in a multi-tenant cluster. For now, though, let's close.

> Also would need to check the benefit when RPC-level compression is enabled.

This seems like a much less invasive way to achieve most of the same benefits. If we take another look at this later, comparing a prototype against RPC-level compression is the first thing we should do.
