### ISSUE TITLE
cloud: Secure Kubernetes certificate manager doesn't work on clusters with RBAC enabled

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#20065]
Our Kubernetes certificate manager (https://github.com/cockroachdb/k8s/tree/master/request-cert) relies on being able to read and write secrets via the Kubernetes API, which isn't allowed by default when [RBAC](https://kubernetes.io/docs/admin/authorization/rbac/) is enabled. This leads to the init container failing with the error:

```
2017/11/14 21:55:38 failed to read from secrets: secrets "default.node.cockroachdb-0" is forbidden: User "system:se
rviceaccount:default:default" cannot get secrets in the namespace "default"
```

We don't have this problem on GKE because for backwards compatibility reasons they let use cases like ours keep working, but [their docs](https://cloud.google.com/kubernetes-engine/docs/role-based-access-control) make it sound like on 1.8+ clusters (which will become the default very soon) we'll have the same problem, so this is something we do need to get working.

**Comment by a-robinson** [comment]
If anyone wants to learn some Kubernetes, this would be a good task. Otherwise, I can take it if @mberhault doesn't want to.

**Comment by a6802739** [comment]
@a-robinson, could I have a try?

**Comment by a-robinson** [comment]
Absolutely! I don't have much guidance other than to check the Kubernetes RBAC docs, but let me know if you run into any issues :)

**Comment by a-robinson** [comment]
I've confirmed that we don't work on GKE when using Kubernetes version 1.8, which will likely become the default sometime in the next month or two. Testing out #20116 now.
