### ISSUE TITLE
sql: Speed up scan over composite primary key

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#20068]
I have a table with a composite primary key (k1, k2) and there are roughly 10000 values of k2 for every value of k1. For a query `SELECT DISTINCT k1 from table WHERE k1 > 0 and k1 < 100`, it ends up scanning all rows in the table with 0 < k1 < 100 including the ones with various values of k2 for the same value of k1, and then does the distinct filtering. This is what I gather it does from an EXPLAIN on such a query. It should be possible to skip over all different values of k2 when iterating.

Perhaps we need to modify the MultiRowFetcher to solve this?

**Comment by RaduBerinde** [comment]
I think any key-skipping logic needs to be at a lower level.. The row fetcher can only do something between fairly large batches of keys.

Something like this would also be useful for interleaved tables - if we're reading a parent table, we want to skip children rows.

**Comment by RaduBerinde** [comment]
CC @richardwu who was thinking about this for interleaved tables.

**Comment by petermattis** [comment]
@RaduBerinde I had the same thought: any skipping would need to be performed at the KV-level. Otherwise, the RPC overhead will dominate any savings. Even if we didn't skip scanning the keys at the KV-level, not sending back the unnecessary KV pairs would be a big win.

**Comment by richardwu** [comment]
A think some sort of "skipping hint" that can be passed on to the KV layer is very beneficial for interleaved tables.

In my benchmarks with interleaved joins thus far, a "typical interleave hierarchy" (parent has many children, children has many grandchildren, etc.) yields really poor performance for joins between the smaller tables (e.g. a join between parent and child results which consists of << 50% of rows unnecessarily scans and propagates grandchildren rows up to `MultiRowFetcher`). I think the biggest overhead here is the # of unnecessary CGo calls to decode the key just to discard it.

We could pass in some hint where if the key retrieved at the C++ layer matches some prefix `X`, it would seek forwards to the next key with prefix `Y`. This could be some function from `f: X --> Y`.

For example in the case of an interleaved join between `parent` and `child` with `grandchild` rows interleaved as well, prefix X would be some key
```
/<pid>/#/<cid1>/<cid2>/#/<gcid>
```
We'd have to tell the C++ layer how our encoding works. Our function `f` for the interleave case would truncate at `<pid>` and logically increment it. 

If "seeking" is not possible, we could skip keys instead. The same idea could be applied to the composite key example.

**Comment by petermattis** [comment]
> We'd have to tell the C++ layer how our encoding works. Our function f for the interleave case would truncate at <pid> and logically increment it.

I don't think this needs to go down to C++, at least not initially. A big portion of the benefit could be had by passing the hint to `MVCCScan` and letting that routine skip keys that aren't needed.

**Comment by petermattis** [comment]
> I think the biggest overhead here is the # of unnecessary CGo calls to decode the key just to discard it.

@arjunravinarayan's and @asubiotto's work will reduce this substantially.

**Comment by arjunravinarayan** [comment]
cc @andreimatei and @tschottdorf who are working on a scheme to enable this (#20080). This is unlikely to be done in the 1.2 timeframe, given the scope of work required to enable filtering at the KV layer.

**Comment by jordanlewis** [comment]
Bumping this out of 2.0. I think there is likely something we can do here without #20080, which seems very far off, but definitely not in the next few weeks.

**Comment by RaduBerinde** [comment]
I think this would be an "index skip scan" which is tracked elsewhere.

**Comment by Bessonov** [comment]
@RaduBerinde I'm not sure that "elsewhere" is helpful. I would like to subscribe to it.

**Comment by RaduBerinde** [comment]
Sorry, was triaging a bunch of issues. This is tracked in #37725.
