### ISSUE TITLE
Check against cloning source repo into a non-Go path

### ISSUE THREAD

**Issue by richardwu** [cockroachdb/cockroach#20061]
If one attempts to `make build` from the source files in a non-Go path, go package resolution will fail because of how Go's build system works.

We should adding a very big warning/error message if someone attempts to this. We should probably add a note to the install instructions under "Build from Source" too https://www.cockroachlabs.com/docs/stable/install-cockroachdb.html.

cc: @benesch

**Comment by benesch** [comment]
We actually check for this now!
