### ISSUE TITLE
sql: wrong error reported for unique constraint with interleaved tables

### ISSUE THREAD

**Issue by NuSkooler** [cockroachdb/cockroach#20067]
**BUG REPORT**

**Header**:
```
I171114 23:21:13.589519 1 util/log/clog.go:992  [config] file created at: 2017/11/14 23:21:13
I171114 23:21:13.589519 1 util/log/clog.go:992  [config] running on machine: host-10
I171114 23:21:13.589519 1 util/log/clog.go:992  [config] binary: CockroachDB CCL v1.1.2 (darwin amd64, built 2017/11/02 20:52:23, go1.9.2)
I171114 23:21:13.589519 1 util/log/clog.go:992  [config] arguments: [cockroach start --certs-dir=/Users/kopreschko/Dropbox/dev-config/certs/cockroach/]
```

**Steps:**
1. Create the following tables:
```
CREATE TABLE parent (
    parent_id INT,
    name STRING(50) NOT NULL,

    PRIMARY KEY(parent_id)
);

CREATE TABLE child (
    parent_id INT,
    child_id INT,
    name STRING(50) NOT NULL,

    PRIMARY KEY(parent_id, child_id),
    CONSTRAINT uq_name UNIQUE(name)
) INTERLEAVE IN PARENT parent(parent_id);
```

(`INTERLEAVE` is crucial to this bug)

2. Insert some values:
```
BEGIN TRANSACTION;
INSERT INTO parent VALUES (1, 'John Doe');
INSERT INTO child VALUES (1, 1, 'John Doe Junior');
COMMIT;
```

3. Now, attempt to insert duplicate values that will fail the unique constraint (`uq_name` in this case):
```
BEGIN TRANSACTION;
INSERT INTO parent VALUES (2, 'John Doe');
INSERT INTO child VALUES (2, 1, 'John Doe Junior');
COMMIT;
```

**Expected:**
Expect the following error: `pq: duplicate key value (name)=('John Doe Junior') violates unique constraint "uq_name"`

**Results:**
`pq: duplicate key value (parent_id,child_id)=(2,1) violates unique constraint "primary"`

**Notes:**
- Without `INTERLEAVE`ing the tables, the proper error is returned.
- Additionally tested with the following version with the same results on a Linux machine: 
```
Build Tag:    v1.2-alpha.20170901-1738-g9e9b94f
Build Time:   2017/11/14 23:22:54
Distribution: CCL
Platform:     linux amd64
Go Version:   go1.9.2
C Compiler:   gcc 5.4.0 20160609
Build SHA-1:  9e9b94f5bf198f73a7dd8c7e317b77d37498280c
Build Type:   development
```

**Comment by couchand** [comment]
I've confirmed this is still an issue on master.  Sending over to @richardwu since he's been in interleaved tables recently.

**Comment by richardwu** [comment]
Looks to be a bug with how we handle unique constraints with interleave tables as 
```
INSERT INTO child VALUES(4, 5, 'John Doe Junior');
```
gives some irrelevant error
```
pq: unexpected value: raw_bytes:"G\022\301\336\003\211\211" timestamp:<wall_time:1510761620271203333 >
```

**Comment by richardwu** [comment]
Just to add some context to someone who wants to jump at this: I tried to add a logic test for the above query (with the irrelevant error) and the logic tests actually produced the "wrong" (but not `pq: unexpected value` error. It's when you actually spin up an instance where you get the `pq: unexpected value` error. This implies there's some deviation between the `TestCluster` and the actual cluster being spun up.

I reckon it's something to do with pgwire but I could be wrong.
