### ISSUE TITLE
sql docs: document the cluster_logical_timestamp built-in

### ISSUE THREAD

**Issue by couchand** [cockroachdb/cockroach#20076]
The built-in `cluster_logical_timestamp` gives access to the CRDB internal transaction timestamp, which corresponds with what we refer to repeatedly in documentation as the "transaction timestamp".

There is potentially value in exposing this to the user, though there are some serious caveats to its usage that need to be made clear.  Documenting this function would give us an opportunity to explain those caveats definitively.

Cf. #20075 regarding better documenting `transaction_timestamp()`

**Comment by andreimatei** [comment]
another related forum discussion
https://forum.cockroachlabs.com/t/how-to-have-a-correct-log-table-that-contains-all-the-inserts-updates-and-deletes/1598/2
