### ISSUE TITLE
SQL: driver is opening a new connection for every transaction

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#2007]
The Go SQL driver is supposed to recycle a connection after a transaction with the server. I'm seeing it open a new connection for every call to db.Begin()
var db *sql.DB
tx, err := db.Begin()

**Comment by tamird** [comment]
Is it unbounded? The Go SQL driver doesn't start recycling until the pool is full, I believe. See:
http://godoc.org/database/sql#DB.SetMaxIdleConns
http://godoc.org/database/sql#DB.SetMaxOpenConns

**Comment by vivekmenezes** [comment]
Looks like it just hangs after reaching the limit. It really should use a free connection rather than opening a new one.

**Comment by tamird** [comment]
> Looks like it just hangs after reaching the limit.

Interesting. Can you write a test that repros this?

> It really should use a free connection rather than opening a new one.

Heh, this is out of our control.

**Comment by vivekmenezes** [comment]
yeah will write a test as I work on a fix

**Comment by vivekmenezes** [comment]
I was not calling Commit() on the transaction because our current version of Commit() is unimplemented and returns an error. Once I call it, it works. This is not a bug.
