### ISSUE TITLE
sql: add JSON builtins

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#20120]
Tracking issue for various JSON builtins. Most of these have a `json` version and a corresponding `jsonb` version. Details [here](https://www.postgresql.org/docs/9.5/static/functions-json.html).

I think basically any of these would be a good first PR:

* [x] `to_json`
* [x] `array_to_json`
* [x] `json_build_array`
* [x] `json_build_object`
* [x] `json_object`
* [x] `json_array_length`
* [x] `json_each`
* [x] `json_each_text`
* [x] `json_extract_path`
* [x] `json_extract_path_text`
* [x] `json_object_keys`
* [x] `json_array_elements`
* [x] `json_array_elements_text`
* [x] `json_typeof`
* [x] `json_strip_nulls`
* [x] `jsonb_set`
* [x] `jsonb_pretty`
* [x] `jsonb_insert`

The below exist in Postgres, but don't apply to CockroachDB right now since we don't support row or record types:
* [ ] ~`row_to_json`~
* [ ] ~`json_populate_record`~
* [ ] ~`json_populate_recordset`~
* [ ] ~`json_to_record`~
* [ ] ~`json_to_recordset`~

**Comment by joe-el-khoury** [comment]
Are the ones with the ~strikethrough~ complete or not required?

**Comment by justinj** [comment]
Hey, @joe-el-khoury, I should have been more clear in the description - the strikethough'd functions don't apply to us right now since we don't have row or record types.

**Comment by joe-el-khoury** [comment]
Currently trying to build cockroachdb, will try to tackle one once I'm able to build it. Should be a fun Go learning exercise.

**Comment by justinj** [comment]
Sweet, feel free to hit me up here or on gitter if you have any questions. If you're looking for ones that would be particularly straightforward given that you're new to Go, `json_array_length` and `json_typeof` should be not bad (look around `builtins.go` to get a feel for how builtins are implemented), `json_extract_path` and `json_extract_path_text` already have implementations to support the `#>` and `#>>` operators. Ones like `json_each` will be interesting I think, but a bit more involved, since they require returning a set of results. You can check out the implementation of `generate_series` and others in `generator_builtins.go` for some guidance on those.

**Comment by joe-el-khoury** [comment]
I will give `json_array_length` a go. I didn't realize I was supposed to restart nodes with the new binary when adding a builtin, so I never saw my changes being reflected in the SQL terminal. Now that I know that I should be off to the races, and I will message you on Gitter when I have any questions.

**Comment by jinchengJL** [comment]
Thinking of taking a stab at this as a first PR. Is this checklist still up-to-date? Based on referenced PRs here it looks like `json_typeof, json_array_elements{_text}, json_object_keys, to_json, json_array_length` are all done or being worked on. If this is accurate I'll probably start with `json_build_object`.

**Comment by justinj** [comment]
Hey @jinchengJL, yeah the list is just tracking completed ones, but it might be useful for it to track what's being worked on as well, that's an interesting thought. And go for it!

**Comment by heyihong** [comment]
Hi @justinj, I wonder if it is necessary to support array_to_json, since only JSON needs it for pretty-print purpose. Also, is json_strip_nulls being worked on? I would like to finish it if possible.

**Comment by justinj** [comment]
@heyihong Interesting, I didn't realize that there was no `array_to_jsonb`, it might still be good to support `array_to_json` in terms of compatibility though, even if it won't be exactly the same?

I don't think json_strip_nulls is being worked on! Feel free to add it.

**Comment by heyihong** [comment]
@justinj If it is good to implement `array_to_json`, I wonder if it is also good to add `array_to_jsonb`. Also, for compatibility, we should add pretty_print argument. Since we need to store pretty json array in db, a way to implement it I could find is to add a new struct called jsonPrettyArray inherits jsonArray and rewrite some methods(e.g. Format, encode). For encoding part, we need to add a tag for identifying whether jsonArray is pretty. Is it ok to do that?

**Comment by jordanlewis** [comment]
Claiming this as a starter project for SQL Execution's intern.
