### ISSUE TITLE
PARTITION BY doesn't support multiple columns

### ISSUE THREAD

**Issue by nkzawa** [cockroachdb/cockroach#20143]
Is this a question, feature request, or bug report?

This is bug report

**BUG REPORT**

1. Please supply the header (i.e. the first few lines) of your most recent
   log file **for each node in your cluster**. On most unix-based systems
   running with defaults, this boils down to the output of

     grep -F '[config]' cockroach-data/logs/cockroach.log

   When log files are not available, supply the output of `cockroach version`
   and all flags/environment variables passed to `cockroach start` instead.

```
Build Tag:    v1.1.2
Build Time:   2017/11/02 20:53:00
Distribution: CCL
Platform:     darwin amd64
Go Version:   go1.9.2
C Compiler:   4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.38)
Build SHA-1:  c726df22152a771cdd1882679c772d4e7799440d
Build Type:   development
```

```
cockroach start --host=localhost --store=$HOME/cockroach-data/node1 --background
cockroach start --host=localhost --store=$HOME/cockroach-data/node2 --background --port=26258 --http-port=8081 --join=localhost:26257
cockroach start --host=localhost --store=$HOME/cockroach-data/node2 --background --port=26259 --http-port=8082 --join=localhost:26257
```

2. Please describe the issue you observed:

- What did you do?

I created a test table and values like the following:

```
create table data (
    id serial primary key,
    a VARCHAR,
    b VARCHAR
);

insert into data (a, b) values
('foo', 'a'),
('foo', 'b'),
('foo', 'b'),
('bar', 'b'),
('bar', 'a'),
('foo', 'b');
```
 
And ran sql which display rank like the folling:

```
SELECT *, rank() OVER (PARTITION BY a, b ORDER BY id DESC) FROM data;
```

- What did you expect to see?

I expect rank is partitioned by multiple columns (`a` and `b`).

- What did you see instead?

Rank is partitioned only by the last column (`b`).

```
+--------------------+-----+---+--------------------------------+
|         id         |  a  | b | rank() OVER (PARTITION BY a, b ORDER BY id DESC) |
+--------------------+-----+---+--------------------------------+
| 297992315749990401 | foo | a |                              2 |
| 297992315750023169 | foo | b |                              4 |
| 297992315750055937 | foo | b |                              3 |
| 297992315750088705 | bar | b |                              2 |
| 297992315750121473 | bar | a |                              1 |
| 297992315750154241 | foo | b |                              1 |
+--------------------+-----+---+--------------------------------+
```

I tested the same query on PosrgreSQL, and the result is expected one (partitioned by multiple columns).

**Comment by nvanbenschoten** [comment]
Thanks for catching this @nkzawa. Looks like this was broken in 278e2e7daca6a1c2d6c95ed0d9220cae66af7d96 and slipped through a gap in our testing.
