### ISSUE TITLE
tracing: some query errors are returned as a result of SHOW TRACE FOR <stmt>

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#20157]
Query errors are not supposed to cause `SHOW TRACE FOR <stmt>` to fail. However, it would appear that planning errors do:

```
root@:26257/t> show trace for select * from ttt;
pq: relation "ttt" does not exist
```

**Comment by jordanlewis** [comment]
This error is from planning. Do we expect `SHOW TRACE` to include results from planning?

**Comment by andreimatei** [comment]
Yes, `SHOW TRACE` traces the planning too. I think it's useful for `SHOW TRACE` to never error.

**Comment by jordanlewis** [comment]
SHOW TRACE FOR <stmt> is dead, having been replaced by some CLI magic that accomplishes the same thing. Closing unless you think this is reproduceible with normal SHOW TRACE FOR SESSION.
