### ISSUE TITLE
release v1.1.3

### ISSUE THREAD

**Issue by couchand** [cockroachdb/cockroach#20176]
Candidate SHA: 0629bcd52ab22637f0f5e7dc3d13a9d170a1c690
Deployment status: `adriatic` `omega`

[Release process checklist](https://github.com/cockroachdb/cockroach/wiki/Release-Process)

Prep date: `2017-11-21`
- [x] [Pick a sha](https://github.com/cockroachdb/cockroach/wiki/Release-Process#pick-sha), fill in `Candidate SHA` above.
- [x] [Deploy to test clusters](https://github.com/cockroachdb/cockroach/wiki/Release-Process#deploy-to-test-clusters)
- [x] fill in `Deployment status` above
- [x] [Verify node crash reports](https://github.com/cockroachdb/cockroach/wiki/Release-Process#verify-crash-reports)
- Keep an eye on clusters until release date.

Release date: `2017-11-27`
- [x] [Check cluster status](https://github.com/cockroachdb/cockroach/wiki/Release-Process#check-cluster)
- [x] [Tag release](https://github.com/cockroachdb/cockroach/wiki/Release-Process#tag-release)
- [x] [Trigger release build](https://github.com/cockroachdb/cockroach/wiki/Release-Process#trigger-build)
- [x] [Check binaries](https://github.com/cockroachdb/cockroach/wiki/Release-Process#check-binaries)

- For stable releases only (**stable** means: no dash in the version):
  - [x] Update the [Homebrew Formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/cockroach.rb)
  - [x] Update the image tag in our [Orchestrator configurations](https://github.com/cockroachdb/cockroach/wiki/Release-Process#orchestrator-configurations)
  - [x] Update the version label in our [Red Hat Atomic Docker image](https://github.com/cockroachdb/cockroach/blob/master/build/deploy/rhel/Dockerfile). For major/minor releases, also update the documentation link in the [image's help file](https://github.com/cockroachdb/cockroach/blob/master/build/deploy/rhel/help.1)
  - [x] Announce version to the [registration cluster](https://github.com/cockroachlabs/production#publishing-a-new-release-version)
  - [x] Upgrade the registration cluster (reg runs latest stable version)

- [x] Update docs
- [x] External communications for release
- [x] File issue for next release and assign to release coordinator

**Comment by mberhault** [comment]
Filed https://github.com/cockroachdb/cockroach/issues/20272 for next alpha.
