### ISSUE TITLE
sql: multiple contradictory AS OF SYSTEM TIME clauses allowed in a query

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#20182]
Currently, an AOST clause is supposed to only be permitted at the topmost level of a query, and it's supposed to be inherited by all the data sources in the query. However, that's not enforced. As long as there is a top level AOST, every other one will be silently ignored. 
For example, this doesn't give any errors.
```
select * from (select * from t.t AS OF SYSTEM TIME '2017-11-19') AS OF SYSTEM TIME '2017-11-20';
```

The code in charge of (insufficiently) enforcing AOST is here:
https://github.com/cockroachdb/cockroach/blob/6ac47c7bc03879b6553980658388d07197593185/pkg/sql/render.go#L302

See also discussion in #20162. cc @knz

**Comment by mjibson** [comment]
My current idea is to have `func isAsOf` walk the statement for children and looking for anything with isasof. However the docs for WalkStmt say it doesn't go into subqueries. Do we have a way to walk all expressions of a statement? @knz maybe?

**Comment by knz** [comment]
I would love to have a look at this issue too. We can do it together, or I can give it a try while y'all are celebrating thanksgiving.

**Comment by andreimatei** [comment]
Well but I think we do want it in subqueries. And also I think not having it in subqueries is not sufficient. I think the rule we want is that there can't be some "datasources" with a aost and some without (or, better yet, that all the data sources need to have equivalent aosts).
And on the execution side, it'd be great if it was the `scanNodes` that implement it by modifying the transaction instead of the Executor so that the Executor doesn't need to understand this. And so aost would need to be pushed down if its specified at a high level.

And even better, it'd be great if we could support different aosts for different data sources. This would imply that the reads for an aost data source become non-transactional. I think that at least conceptually that's not too hard.

**Comment by knz** [comment]
There are different layers in your wishlist. :)
I'd support a first PR which properly rejects multiple AOST clauses, as well as any clause that's not at the top level. 
Then we can think about a way for the scanNode to direct the timestamp at which they want to read (that may need some changes in the kv fetcher), and if we find a solution we can have every data source use their own timestamp, to much rejoicing of everyone.

**Comment by andreimatei** [comment]
> There are different layers in your wishlist. :)

I'm like Maslow in that.

**Comment by mjibson** [comment]
I'm unassigning myself from this bug because it's pretty low down on my priority list and maybe someone else wants to take it.

**Comment by tschottdorf** [comment]
While we're doing wishlists, something that I mentioned to @andreimatei today is that one very practical special case for this is one I've encountered during debugging: you have a client app that uses some framework and you can't just grab a connection. You want to trace a query while also getting the result set. Naively that is

```
SET TRACING=on;
STUFF AS OF SYSTEM TIME X;
SHOW TRACE FOR SESSION;
SET TRACING=off;
```

But there's (say) some ORM you have to use and below that, perhaps even transparently, a load balancer, so you have to pin yourself to a connection somehow. The straightforward way of doing that is by opening a transaction (which forces that) and then running the query. But it's currently unsupported.

**Comment by knz** [comment]
@tschottdorf re https://github.com/cockroachdb/cockroach/issues/20182#issuecomment-346197243 I think that's a separate issue, I split it as #20266.

**Comment by knz** [comment]
@tschottdorf I think I may have a temporary workaround until we have a solution for #20266.

I'm assuming you have a library/ORM which gives you a separate API for transactions. For example something like this:

```
conn = driver.Open(...)   # not a real connection, goes to a load balancer
conn.Exec("some sql")  # this is not pinned to a single connection
txn = conn.OpenTxn()  # this pins txn to a connection and issues BEGIN
txn.Exec("foo"); txn.Exec("bar")  # all these are guaranteed to go to the same conn
txn.Close() # issues COMMIT/ROLLBACK, unpins
```

IF you have something like that, then you can do what you want above like this:

```
txn = conn.OpenTxn()
txn.Exec("COMMIT") # if you're lucky, it will not peek into the string; you get a pinned conn but without the txn
txn.Exec("SET tracing=on")
... SELECT queries with ASOT set ...
txn.Exec("SET tracing=off"), txn.Query("SHOW TRACE FOR SESSION")
txn.Exec("BEGIN") # so that Close() below isn't confused
txn.Close() # close "txn", unpin connection
```

would something like that work for you?
