### ISSUE TITLE
sql: primary keys silently discard NULL attribute

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#20202]
```
root@:26257/test> create table hmm (a bytes null, primary key(a asc));
CREATE TABLE

Time: 4.946049ms

root@:26257/test> insert into hmm values (null);
pq: null value in column "a" violates not-null constraint
```

This is confusing. Shouldn't having a primary key constraint on a column that was already explicitly marked as `NULL` just fail during table creation? Postgres also suffers from this issue, FWIW.

**Comment by petermattis** [comment]
I think "primary key" implied not-NULL and that we were following Postgres behavior here. That's my reading of the Postgres docs: https://www.postgresql.org/docs/9.5/static/ddl-constraints.html

@lego Can you verify that we're doing something different than Postgres? I don't think we can "fix" this ux-surprise if doing so causes us to differ from Postgres.

**Comment by jordanlewis** [comment]
I'm not sure where the patch ended up, but my original thinking was that it's reasonable to return an error in this case even though Postgres doesn't.

```
jordan=# create table z (a int null primary key);
CREATE TABLE
jordan=# \d z
                 Table "public.z"
 Column |  Type   | Collation | Nullable | Default
--------+---------+-----------+----------+---------
 a      | integer |           | not null |
Indexes:
    "z_pkey" PRIMARY KEY, btree (a)
```

This is just silly! It should return an error to the user because the created table is not what the user expects. I don't think we are going to be hurting anyone's compatibility by making this an error case.

**Comment by petermattis** [comment]
> This is just silly! It should return an error to the user because the created table is not what the user expects. 

Agreed on the silliness if the user explicitly asked for a `NULL` column. If the column is implicitly `NULL`-able the argument for upgrading to `NOT NULL` is stronger. 

> I don't think we are going to be hurting anyone's compatibility by making this an error case.

I'm not sure about this. Users/ORMs can do some mighty weird things.

**Comment by bdarnell** [comment]
Mysql does the same thing:

```
mysql> create table z (a int null primary key);
Query OK, 0 rows affected (0.02 sec)

mysql> show create table z;
+-------+-----------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                        |
+-------+-----------------------------------------------------------------------------------------------------+
| z     | CREATE TABLE `z` (
  `a` int(11) NOT NULL,
  PRIMARY KEY (`a`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 |
+-------+-----------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

So this isn't just a postgres quirk, it's something that at least two databases do, which raises the chance that someone is relying on it. Still, the statement clearly contradicts itself so I'd be OK making it an error. I think this will have a much lower chance of causing problems than many of our other deviations from postgres (like our opposition to implicit casts).

**Comment by knz** [comment]
cc @vivekmenezes for triage

**Comment by vivekmenezes** [comment]
I'd be happy just closing this given that we've chosen to be postgres compatible. Feel free to reopen.
