### ISSUE TITLE
DESC indexes invert signage of spans in EXPLAIN

### ISSUE THREAD

**Issue by richardwu** [cockroachdb/cockroach#20203]
Given a `DESC` index `b`
```
CREATE TABLE bar (
  b INT,
  INDEX b(b DESC)
)
```

```
EXPLAIN SELECT * FROM bar WHERE b = -5
```
shows a misleading table scan on the span `/4 - /5` (instead of `/-5 - /-4`)
```
+-------+------+-------+-------------+
| Level | Type | Field | Description |
+-------+------+-------+-------------+
|     0 | scan |       |             |
|     0 |      | table | bar@b       |
|     0 |      | spans | /4-/5       |
+-------+------+-------+-------------+
```

The reverse is also true
```
EXPLAIN SELECT * FROM bar WHERE b = 5
```
outputs a scan on `/-6 - /-5` (instead of `/5 - /6`)
```
+-------+------+-------+-------------+
| Level | Type | Field | Description |
+-------+------+-------+-------------+
|     0 | scan |       |             |
|     0 |      | table | bar@b       |
|     0 |      | spans | /-6-/-5     |
+-------+------+-------+-------------+
```

Fortunately, the query returns the correct results so this is a matter of UX.

**Comment by richardwu** [comment]
The issue is that the visitor that sets the `spans` `attr` for the `explainPlanNode` [invokes `PrettySpans`](https://github.com/cockroachdb/cockroach/blob/1ccd71373ffc2137448f0661ef517875aadd37c4/pkg/sql/walk.go#L143) which does not factor in ascending or descending columns when it eventually invokes `key.String() --> PrettyPrintKey(key) --> keys.prettyPrintInternal(key) --> decodeKeyPrint(key) --> encoding.PrettyPrintValue() --> encoding.prettyPrintFirstValue()`.

In `prettyPrintFirstValue` we assume all [`Int` encoded values are `Ascending`](https://github.com/cockroachdb/cockroach/blob/1ccd71373ffc2137448f0661ef517875aadd37c4/pkg/util/encoding/encoding.go#L1068-L1070). Since descending keys are encoded as ascending but with a bitwise `NOT`, we get these inverted spans.

I'm thinking we'll need to propagate down the `IndexDescriptor` to retrieve `ColumnDirections` at some point to a function in `sql` that will pretty print spans with column information. This could be a direction bool hint once it reaches the encoding layer.

Thoughts? @nvanbenschoten

**Comment by jordanlewis** [comment]
I think this is probably also the cause of the display issues in `SHOW CREATE TABLE` with partitions on descending indexes. cc @danhhz
