### ISSUE TITLE
sql: columns and column families are indexed differently

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#20201]
```
root@:26257/test> create table a (a int, b int, c int, primary key (a, b), family "a" (a), family "b" (b, c));
pq: primary key column 2 is not in column family 0
```

As you can see, columns are 1-indexed but column families are 0-indexed. This is confusing. I propose making column families 1-indexed for consistency with columns and other 1-indexed SQL concepts like arrays.

**Comment by lego** [comment]
Was there a consensus on making it 1-indexed for all future tables?

I'd guess there would be some tricky parts here if code assumes 0 (or some constant) is the default column family.

**Comment by jordanlewis** [comment]
This seems like not an important thing to fix.
