### ISSUE TITLE
storage: New follow-the-workload demo works on 1.1 but not on master

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#20213]
Reproduction steps: https://www.cockroachlabs.com/docs/stable/demo-follow-the-workload.html

Reported by @jseldess

**Comment by a-robinson** [comment]
So I tested this out this morning and it still worked for me, but the lease transfers took longer to happen. The first one happened 33 seconds in, and the second one happened 4m55s in (out of the allotted 5 minutes).

@jseldess, would you mind trying again with a longer duration for the second run of `kv`? Assuming you don't think that making the demo take longer makes the feature seem drastically less useful. I'm not sure yet why the timing is so different on 1.2-alpha than on 1.1. There aren't any obvious `Allocator` or `replicaStats` changes in the git history.

**Comment by jseldess** [comment]
You're right, @a-robinson. It's working for me again as well. In fact, it took a bit longer for the range to move the second time on 1.1 than on master this time. I think I'll update the tutorial to run kv the second time for 7 min instead of 5, just to be safe. Thanks for testing.
