### ISSUE TITLE
P99 Latency does not agree with node latency

### ISSUE THREAD

**Issue by twiden** [cockroachdb/cockroach#20221]
In the Admin UI: "P99 Latency" does not agree with "Service Latency: SQL, 99th percentile" for any of the nodes. See P99 value in the top right box and the individual nodes in the popup over the graph.

Also, while running benchmarks (cockroachdb/loadgen kv) the P99 Latency displayed here seems to be a lot higher then from the clients perspective.

CockroachDB version 1.1.2

![latency_diff](https://user-images.githubusercontent.com/7657952/33124645-ff75eaa0-cf7d-11e7-8b69-ee8def2ff1d9.png)

**Comment by mberhault** [comment]
I believe the latency shown in the side bar is a max over some the displayed period. Given that, it still looks a bit off.
@mrtracy: can you confirm? the sidebar and the "Service Latency: SLQ 99th percentile" both use `cr.node.exec.latency-p99`, with the sidebar using `aggregateMax`.

**Comment by twiden** [comment]
In that case it does not compute max over the same time span as the graph shows?

**Comment by a-robinson** [comment]
It does look like the peak of the red line in the graph is right around 113ms, so I'd guess it's either taking the max point from whatever is graphed or just the max point from the last 10 minutes. That's a pretty harsh way of determining the cluster-wide P99 latency.

**Comment by twiden** [comment]
I don't think it's max from the graph display period. Here's an example
<img width="1316" alt="screen shot 2017-11-22 at 21 01 43" src="https://user-images.githubusercontent.com/7657952/33147566-85745a84-cfc8-11e7-9a63-c8c7c1865bcf.png">

**Comment by dianasaur323** [comment]
We are actually removing that cluster summary view in favor of another view going into the 1.2, but we'll think of something to address this issue in that view.

**Comment by vivekmenezes** [comment]
@vilterp are you actively working on this? Wondering if @mrtracy can pick this up for 2.0

**Comment by vilterp** [comment]
Nope, I'm all-in on clusterviz at this point.

**Comment by mrtracy** [comment]
These are actually just displaying different metrics.  The graph is displaying `cr.node.sql.service.latency-p99`, the summary bar is displaying `cr.node.exec.latency-p99`.
