### ISSUE TITLE
ui: indicate timeseries size clearly

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#20223]
Currently, the space taken up by the timeseries data must be inferred by looking at bytes usage and subtracting any user data. This is a fairly poor approximation of the "extra" space taken up by the timeseries data.

We should investigate ways of displaying it more clearly, resulting in less surprise about its disk usage (this is a recurring question on support channels).

Given the fact that timeseries are not using a db/table this may be a bit tricky and may not be doable without some major plumbing for non-sql bytes reporting.

**Comment by mberhault** [comment]
@mrtracy for thoughts.

**Comment by a-robinson** [comment]
Heh, I also opened an issue for this yesterday -
https://github.com/cockroachdb/cockroach/issues/20210

@mrtracy just close one of them when you get around to looking at this.

**Comment by mberhault** [comment]
Ah, I thought I remembered something like it, but I couldn't find it when searching around. I'll close mine.
