### ISSUE TITLE
How to make they have candidates? Cluster for three-node.

### ISSUE THREAD

**Issue by zimulala** [cockroachdb/cockroach#2022]
steps to reproduce:
0. init db0, db1, db2
1. start three servers
./cockroach start --stores=ssd="./db0" --addr=":8080" --gossip=":8080,:8081,:8082" 
./cockroach start --stores=ssd="./db1" --addr=":8081" --gossip=":8080,:8081,:8082"
./cockroach start --stores=ssd="./db2" --addr=":8082" --gossip=":8080,:8081,:8082"
why appeared the error here below:
20:13:08.136940 19189 storage/queue.go:308  failure processing range range=1 [""-"\xff\xff") from replicate queue: storage/allocator.go:204: unable to allocate a target store; no candidates available

Than, I try to start use the following way
./cockroach start --stores=ssd="./db0" --addr=":8080" --gossip=":8080,:8081,:8082"  --attrs=a,ssd
./cockroach start --stores=ssd="./db1" --addr=":8081" --gossip=":8080,:8081,:8082"  --attrs=a,ssd
./cockroach start --stores=ssd="./db2" --addr=":8082" --gossip=":8080,:8081,:8082"  --attrs=a,ssd

And, set zone
./cockroach zone set "haha" zone.cfg

zone.cfg content as follows:
![2015-08-08 17 32 42](https://cloud.githubusercontent.com/assets/4242506/9149910/849a376e-3df3-11e5-8b7d-a9149cb7ad49.png)

However, there are still errors 
E0808 11:22:56.087701 16670 storage/queue.go:308  failure processing range range=1 [""-"haha") from replicate queue: storage/allocator.go:204: unable to allocate a target store; no candidates available
E0808 11:23:01.087816 16670 storage/queue.go:308  failure processing range range=2 ["haha"-"hahb") from replicate queue: storage/allocator.go:204: unable to allocate a target store; no candidates available
E0808 11:23:06.087927 16670 storage/queue.go:308  failure processing range range=3 ["hahb"-"\xff\xff") from replicate queue: storage/allocator.go:204: unable to allocate a target store; no candidates available

How to make they have candidates?

**Comment by tamird** [comment]
did you `cockroach init` any of those nodes?

**Comment by zimulala** [comment]
yep, but if only init one of them, as follows:
./cockroach init --store=ssd=./db0,ssd=./db1,ssd=./db2
At this time, wether all of the stores will be on the same machine？Because they are initialized on one machine.

**Comment by zimulala** [comment]
I'm sure that there are something wrong on my opinion, otherwise all the nodes of data is stored on one machine.
Please tell me, what's wrong with my steps? I want to make ranges have correct replica group.

**Comment by tschottdorf** [comment]
You only run `init` on one cluster, and you only need to pass one of the stores (you can pass more stores when you start). The other two nodes then join the cluster (started with their respective stores, but without init).

**Comment by zimulala** [comment]
Gotcha.
Thanks.
