### ISSUE TITLE
stability: please add way to recover from rocksdb corruption errors

### ISSUE THREAD

**Issue by d4l3k** [cockroachdb/cockroach#20222]
I just ran into an issue where I had to hard reboot my dev machine and ran into some rocksdb corruption errors. It lead to my single cockroachdb node being completely unresponsive and throwing this error:
```
F171122 10:36:45.864086 115 storage/store.go:3662  [n1,s1] {while committing batch}: while committing batch: Corruption: block checksum mismatch
goroutine 115 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x33eef00, 0x14f9621828e10d15, 0x2c0d0a2, 0x10)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:833 +0xcf
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x33eef00, 0xc400000004, 0x2c0d0a2, 0x10, 0xe4e, 0xc420f5c060, 0x5d)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:736 +0x620
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x2f27ac0, 0xc420d04000, 0xc400000004, 0x2, 0x1f37769, 0x6, 0xc420f4ded0, 0x2, 0x2)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:153 +0x2fc
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x2f27ac0, 0xc420d04000, 0x1, 0x4, 0x1f37769, 0x6, 0xc420f4ded0, 0x2, 0x2)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:56 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(0x2f27ac0, 0xc420d04000, 0x1f37769, 0x6, 0xc420f4ded0, 0x2, 0x2)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:150 +0x7e
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processReady(0xc420175000, 0x2f27ac0, 0xc420d04000, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3662 +0x4d3
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4208385a0, 0x2f27ac0, 0xc420d04000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:216 +0x259
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x2f27ac0, 0xc420d04000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:167 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4204b63c0, 0xc42017c870, 0xc4204b63b0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:198 +0xf3
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:191 +0xad
```
Full Log: https://gist.github.com/d4l3k/2d00a8f87b17624326aa8cc6807846fa

It'd be really nice if there was a way to disable the rocksdb corruption errors and attempt to dump what data is still available. While some data loss might occur, still better than total data loss. To be fair this is probably an edge case since you should be running with multiple nodes in production.

I ended up having to manually disabling those checks and recompiling before dumping the database.

https://github.com/d4l3k/cockroach/commit/f09fa68bd4fee9af630fcce7c3ed5785d94cdeb1

Sort of related to #17186

**Comment by tschottdorf** [comment]
@d4l3k have you tried https://github.com/facebook/rocksdb/wiki/RocksDB-Repairer?

It should be bundled into `cockroach` via `./cockroach debug ldb <X>`

**Comment by YuriyNasretdinov** [comment]
I ran into a similar issue where rocksdb became corrupted on a single-node. I tried to repair rocksdb using ./cockroachdb debug rocksdb (I was using 1.0.4) and after rocksdb "repaired" data, database still would not start:

* ERROR: cockroach server exited with error: cannot verify empty engine for bootstrap: unable to read store ident: store has not been bootstrapped

No simple actions allow to force server start. More recent version 1.1.3 prints the same message as above. I can provide with (pretty small) dataset if needed.

**Comment by dianasaur323** [comment]
@bdarnell curious to get your opinion on this? is there anything we could do here on the Cockroach side?

**Comment by bdarnell** [comment]
I don't think there's anything we can reasonably do here. Ignoring checksum errors would have a high chance of breaking all kinds of stuff (even worse that recovering an intact replica that is part of a cluster that has lost a majority, which I'm also skeptical of but I think it is higher priority).

**Comment by dianasaur323** [comment]
ok, i'll mark this as later for now then

**Comment by tschottdorf** [comment]
@dt this seems like it would fit in with the proposed backup-restore driven plan for #17186, right?

**Comment by tschottdorf** [comment]
Closing for https://github.com/cockroachdb/cockroach/issues/17186.
