### ISSUE TITLE
mvcc: the get buffer do not need reset in the release function

### ISSUE THREAD

**Issue by wuguojun** [cockroachdb/cockroach#20257]
File: storage/engine/mvcc.go   
Line number: 511

**Comment by petermattis** [comment]
@wuguojun Thanks for the interest in low-level performance. Can you elaborate on why you think the reset is not needed and what benefit there is to removing it? The reset ensures that we don't accidentally share data from one usage of the buffer to another. An alternative would be to reset in `newGetBuffer`, but the effect is the same. Removing the reset (if we could prove doing so is safe) would be a very small reduction in CPU that I would be surprised if you could measure. That said, profiling and hard numbers are very convincing.

**Comment by petermattis** [comment]
Closing as the reset, one way or another, seems to be necessary.
