### ISSUE TITLE
sql: LIMIT and ORDER BY do not work in views 

### ISSUE THREAD

**Issue by ZiCog** [cockroachdb/cockroach#20262]
I created a view like so:

    CREATE VIEW aview 
    AS 
        SELECT source_id, timestamp, value 
        FROM   series_1 
        WHERE  source_id = 9999 
        ORDER  BY timestamp DESC 
        LIMIT  10; 

And use it in a query:

    SELECT * 
    FROM   aview; 

Problem: All rows in the table, rather than only the last 10 were returned.

Next I change the view definition to use a sub-select:

    CREATE VIEW aview 
    AS 
        SELECT source_id, "timestamp", value
        FROM (
            SELECT source_id, "timestamp", value
            FROM series_1
            WHERE source_id = 9999
            ORDER BY "timestamp"
            DESC LIMIT 10)
        AS temp ORDER BY timestamp ASC;

Problem:  Now only 10 rows are returned but the order is wrong.

Next I change the view to use a sub-sub-select:

    CREATE VIEW aview 
    AS 
        SELECT source_id, "timestamp", value
        FROM (
            SELECT source_id, "timestamp", value
            FROM (
                SELECT source_id, "timestamp", value
                FROM series_1
                WHERE source_id <= 4
                ORDER BY "timestamp"
                DESC LIMIT 100)
            AS temp ORDER BY timestamp ASC)
        ORDER BY timestamp ASC;

This works!

Conclusion, LIMIT and ORDER do not work in views.

Sorry if my raising an issue for this is inappropriate. benesch already has a pull request (#20246) for a fix after my discussing this on the forum. I just wanted it here so I can keep an eye on it.

https://github.com/cockroachdb/cockroach/pull/20246

**Comment by mberhault** [comment]
Fix under review in https://github.com/cockroachdb/cockroach/pull/20246

**Comment by benesch** [comment]
Fixed by #20246! Thanks for the report, @ZiCog. This'll be released in the alpha after next (i.e., not the alpha slated for 12/4.)

**Comment by ZiCog** [comment]
Excellent. Well done everybody.

**Comment by benesch** [comment]
And FWIW, raising an issue here is _always_ appropriate. We'd much rather have duplicate issues—we can always close the extras—than no issues at all.
