### ISSUE TITLE
restore: cleanup is reliant on export storage availability

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#20261]
At present, when a restore resumes, it downloads or re-downloads the backup descriptor from the export storage. This is obviously necessary on the initial resume, and reasonable enough on subsequent resumes: if you're modifying your backup while doing a restore, you're just asking for trouble. 

If a restore is canceled or otherwise fails, we re-download the backup descriptor once more to determine what table descriptors to delete. This is less reasonable: we shouldn't be relying on the availability of the export storage to properly clean up after ourselves. Suppose, for example, someone runs a backup to S3, starts a restore, and then accidentally deletes that backup from S3. The restore will fail, but _also_ fail to clean up after itself because the backup descriptor will no longer be accessible. We should keep better track of what data we're writing so we can always clean it up, even if the backup descriptor goes away.

This is a harder project than it sounds. I was hopeful that simply knowing the table IDs would be sufficient because those are already stored in the jobs table payload. Sadly, because we simulate a drop table to get the schema changer to do our cleanup work for us, we need the entire table descriptor available. This would require storing the table descriptor in the jobs table, which we've so far avoided because of size concerns, as every progress update requires rewriting the entire jobs row.

I see two solutions:

   * Extract a separate `jobs_progress` table. We could use this opportunity to build support for "phased" jobs with separate progress bars that @danhhz has long dreamed of.

   * Change our restore cleanup to issue a `DelRange` on the affected spans, which should be derivable from the existing table rewrite information, instead of going through the schema changer.

**Comment by dt** [comment]
might be fixed with matt's move of the descriptor into the job record -- @mjibson will confirm and close
