### ISSUE TITLE
sql: support AS OF SYSTEM TIME for entire transactions

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#20266]
Requested by @tschottdorf in https://github.com/cockroachdb/cockroach/issues/20182#issuecomment-346197243:

> one very practical special case for this is one I've encountered during debugging: you have a client app that uses some framework and you can't just grab a connection. You want to trace a query while also getting the result set. Naively that is

```sql
SET TRACING=on;
STUFF AS OF SYSTEM TIME X;
SHOW TRACE FOR SESSION;
SET TRACING=off;
```

> But there's (say) some ORM you have to use and below that, perhaps even transparently, a load balancer, so you have to pin yourself to a connection somehow. The straightforward way of doing that is by opening a transaction (which forces that) and then running the query. But it's currently unsupported.

(unsupported because one cannot use AS OF SYSTEM TIME in a txn that's already open)

Example alternative behavior: TiDB supports setting the time travel timestamp txn-wide, using a SET statement, [see here](https://pingcap.com/docs/op-guide/history-read/).

**Proposed solution:** extend both BEGIN and SET to allow setting the time travel timestamp txn-wide, in the same manner that a client can set the isolation level using either BEGIN or SET at first statement. For example:

```sql
BEGIN;
SET transaction_as_of_time = '...';
SELECT .... -- with or without 'AS OF SYSTEM TIME', but if present must match
COMMIT;
```

Alternatively:
```sql
BEGIN TRANSACTION AS OF SYSTEM TIME '...';
SELECT ....
COMMIT;
```

cc @andreimatei

**Comment by andreimatei** [comment]
Well, if a transaction has such a timestamp set, would it be readonly (and we'd enforce that)? Or what timestamps would we accept?
And what about uncertainty restarts - would these be allowed or not (they're not for the current AOST queries)?

**Comment by knz** [comment]
I wouldn't do anything we don't already do for AOST. That includes:

- continuing to exclude write statements
- continuing to refuse uncertainty restarts

what do you think?

**Comment by andreimatei** [comment]
Well, but how would you do that for a transaction?
I'm not particularly against anything here, but I personally would be reticent into putting too much effort and/or code into this. FWIW, Tobi's original request came from a combination of a contrived API that he was using (gorm) and a bug with SHOW TRACE FOR, not too mention that the whole thing he was doing proved to be a wild goose chase.

**Comment by knz** [comment]
How to do -- like we already allow setting the priority and isolation level with SET, as long as it's the first statement after BEGIN (or as options on the BEGIN statement itself).

**Comment by andreimatei** [comment]
But what I'm saying is that we don't have code to make a txn read-only, for example.

**Comment by knz** [comment]
woah, actually yes you're right, and probably there's even a bug with the form we already support. looking into it.

**Comment by tschottdorf** [comment]
The main point here has now shifted: we want to be able to run AOST with high priority, but this isn't possible unless you use AOST inside of a txn (or find extra syntax to set the priority for individual statements outside of a txn). See https://github.com/cockroachdb/cockroach/issues/25405.

**Comment by knz** [comment]
@ajwerner you addressed this right? please confirm and close as applciable thanks.

**Comment by ajwerner** [comment]
Confirmed.
