### ISSUE TITLE
can't init cluster, faile open rockesdb instance 

### ISSUE THREAD

**Issue by savechina** [cockroachdb/cockroach#2027]
When I init the cockroach cluster ,it's is error. could not open rocksdb install

[vagrant@localhost cockroach]$ ./cockroach init --stores=ssd=/vagrant/tmp/db1
I0809 19:38:09.116095 19597 server/context.go:170  initialized 1 storage engine(s)
I0809 19:38:09.126075 19597 storage/engine/rocksdb.go:99  opening rocksdb instance at "/vagrant/tmp/db1"
E0809 19:38:09.249680 19597 cli/start.go:73  unable to bootstrap cluster: storage/engine/rocksdb.go:109: could not open rocksdb instance: IO error: directory: Invalid argument

**Comment by MBerhault** [comment]
Can you show output of `ls -l /vagrant/tmp/db1` as well as its contents?

The email for this issue showed the error `opening rocksdb instance at "/vagrant/tmp/db7ap5fk"`, but the issue itself shows `opening rocksdb instance at "/vagrant/tmp/db1"`. Is this just a weird github thing? which one is the actual error received?

**Comment by savechina** [comment]
it can show dir contents.
I run cockroach in centos on virtual box  , local use  mac osx .the "/vagrant/tmp/db1" is  share forlder for virtual mactine use  local forlder . 
when I set stores file is linux local dir not problem ,but use share forlder can't open rocksdb instance.

**Comment by MBerhault** [comment]
can you show the outputs of all the following:
```
$ ls -l /vagrant/tmp/db1
$ ls -ld /vagrant/tmp/db1
$ mount
```

My guess would be either bad permissions, or something odd with the way rocksdb wants to use vboxfs.

**Comment by savechina** [comment]
outputs of all the follow:

<pre>
[vagrant@localhost cockroach]$ ls -l /vagrant/tmp/db1
总用量 12
-rw-r--r--. 1 vagrant vagrant  0 8月   9 20:01 000021.log
-rw-r--r--. 1 vagrant vagrant 16 8月   9 20:01 CURRENT
-rw-r--r--. 1 vagrant vagrant 37 8月   9 19:57 IDENTITY
-rw-r--r--. 1 vagrant vagrant  0 8月   9 19:57 LOCK
-rw-r--r--. 1 vagrant vagrant 59 8月   9 20:01 MANIFEST-000020
[vagrant@localhost cockroach]$ ls -ld /vagrant/tmp/db1
drwxr-xr-x. 1 vagrant vagrant 238 8月   9 20:01 /vagrant/tmp/db1
[vagrant@localhost cockroach]$ mount
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime,seclabel)
devtmpfs on /dev type devtmpfs (rw,nosuid,seclabel,size=244588k,nr_inodes=61147,mode=755)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev,seclabel)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,seclabel,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,seclabel,mode=755)
tmpfs on /sys/fs/cgroup type tmpfs (rw,nosuid,nodev,noexec,seclabel,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpuacct,cpu)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
configfs on /sys/kernel/config type configfs (rw,relatime)
/dev/mapper/centos-root on / type xfs (rw,relatime,seclabel,attr2,inode64,noquota)
selinuxfs on /sys/fs/selinux type selinuxfs (rw,relatime)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=32,pgrp=1,timeout=300,minproto=5,maxproto=5,direct)
mqueue on /dev/mqueue type mqueue (rw,relatime,seclabel)
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,seclabel)
/dev/sda1 on /boot type xfs (rw,relatime,seclabel,attr2,inode64,noquota)
/dev/mapper/centos-root on /var/lib/docker/devicemapper type xfs (rw,relatime,seclabel,attr2,inode64,noquota)
none on /vagrant type vboxsf (rw,nodev,relatime)
[vagrant@localhost cockroach]$

**Comment by MBerhault** [comment]
ok, got it. The error comes from: https://github.com/facebook/rocksdb/blob/868bfa40336b99005beb9f4fc9cf2acc0d330ae1/util/env_posix.cc#L1016
which does an fsync on the directory. Apparently, vboxsf does not support fsync on directories.
I'm afraid that means you'll need either an alternate way to mount the directory, or not mount it at all.

**Comment by bdarnell** [comment]
I've had a lot of trouble with vboxfs in other apps (it also doesn't support hard links). You can use vagrant's nfs mount option instead.
