### ISSUE TITLE
addsstable: try adding fsync of smaller chunks more often

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#20279]
From in-person discussion with @petermattis: we've observed that sending very large writes to disk all at once can cause smaller writes to see large latency spikes. Forcing those larger writes to fsync more often as they go may help prevent choking out those smaller writes, and improve issues eg. with node liveness.

**Comment by dt** [comment]
cc @mjibson @a-robinson

**Comment by petermattis** [comment]
Per our in-person discussion, we should probably be fsync'ing every 256KB-1MB of data written.

**Comment by a-robinson** [comment]
I've tried setting `options.bytes_per_sync` to both 256KiB and 4MiB when running [my test program](https://github.com/a-robinson/cockroach/blob/diskcontention/pkg/cmd/diskcontention/main.go) from https://github.com/cockroachdb/cockroach/issues/19699#issuecomment-342947639 that does bulk writes against one rocksdb instance and small syncs against another. I didn't measure the bulk write throughput/latency, but the small syncs didn't noticeably improve with either setting. They still got drastically slowed down and occasionally stalled.

**Comment by a-robinson** [comment]
Correction: `bytes_per_sync` is great, it just wasn't enabled due to our lack of build flags (https://github.com/cockroachdb/cockroach/issues/19699#issuecomment-348026440). If you aren't already planning on getting this in for 1.2, then I will.

**Comment by dt** [comment]
Off the top of my head, we'll probably also want to sync every 512kb around the `ioutil.WriteFile` in `diskSideloadStorage` and the `io.Copy`in `localFileStorage.WriteFile`

**Comment by dt** [comment]
Did this. made everything reliable and reliably slow.
