### ISSUE TITLE
release v1.2-alpha.20171204

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#20272]
Candidate SHA: 224e8607c1dbc8b3aeadd3a89254c0ec917a8bf8
Deployment status: `adriatic`, `omega`

[Release process checklist](https://github.com/cockroachdb/cockroach/wiki/Release-Process)

Prep date: `2017-11-27`
- [x] [Pick a sha](https://github.com/cockroachdb/cockroach/wiki/Release-Process#pick-sha), fill in `Candidate SHA` above.
- [x] [Deploy to test clusters](https://github.com/cockroachdb/cockroach/wiki/Release-Process#deploy-to-test-clusters)
- [x] fill in `Deployment status` above
- [x] [Verify node crash reports](https://github.com/cockroachdb/cockroach/wiki/Release-Process#verify-crash-reports)
- Keep an eye on clusters until release date.

Release date: `2017-12-04`
- [x] [Check cluster status](https://github.com/cockroachdb/cockroach/wiki/Release-Process#check-cluster)
- [x] [Tag release](https://github.com/cockroachdb/cockroach/wiki/Release-Process#tag-release)
- [x] [Trigger release build](https://github.com/cockroachdb/cockroach/wiki/Release-Process#trigger-build)
- [x] [Check binaries](https://github.com/cockroachdb/cockroach/wiki/Release-Process#check-binaries)
- [x] Update docs
- [x] External communications for release
- [x] File issue for next release and assign to release coordinator

**Comment by jseldess** [comment]
Issue for next week's release notes: https://github.com/cockroachdb/cockroach/issues/20457
