### ISSUE TITLE
Panic in kv_bank example

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#2028]
Running against a remote server, this happens reproducibly within a minute or two of starting.

```
E0809 14:37:40.349856 27567 client/txn.go:323  failure aborting transaction: kv/txn_coord_sender.go:408: cannot commit a read-only transaction; abort caused by: kv/txn_coord_sender.go:408: cannot commit a read-only transaction
F0809 14:37:40.349909 27567 examples/kv_bank/main.go:154  kv/txn_coord_sender.go:408: cannot commit a read-only transaction
goroutine 19 [running]:
github.com/cockroachdb/cockroach/util/log.stacks(0xc2080e8e01, 0x0, 0x0, 0x0)
	/Users/bdarnell/demo/src/github.com/cockroachdb/cockroach/util/log/clog.go:867 +0xcd
github.com/cockroachdb/cockroach/util/log.(*loggingT).outputLogEntry(0x50db960, 0x3, 0x50075f3, 0x18, 0x9a, 0x0, 0xc2080e8e40)
	/Users/bdarnell/demo/src/github.com/cockroachdb/cockroach/util/log/clog.go:739 +0x11b
github.com/cockroachdb/cockroach/util/log.AddStructured(0x0, 0x0, 0x3, 0x2, 0x0, 0x0, 0xc208563f40, 0x1, 0x1)
	/Users/bdarnell/demo/src/github.com/cockroachdb/cockroach/util/log/structured.go:39 +0x120
github.com/cockroachdb/cockroach/util/log.logDepth(0x0, 0x0, 0x1, 0x4000000000000003, 0x0, 0x0, 0xc208563f40, 0x1, 0x1)
	/Users/bdarnell/demo/src/github.com/cockroachdb/cockroach/util/log/log.go:65 +0x82
github.com/cockroachdb/cockroach/util/log.Fatal(0xc208563f40, 0x1, 0x1)
	/Users/bdarnell/demo/src/github.com/cockroachdb/cockroach/util/log/log.go:161 +0x75
main.(*Bank).continuouslyTransferMoney(0xc20800b0c0, 0x64)
	/Users/bdarnell/demo/src/github.com/cockroachdb/cockroach/examples/kv_bank/main.go:154 +0x313
created by main.main
	/Users/bdarnell/demo/src/github.com/cockroachdb/cockroach/examples/kv_bank/main.go:271 +0x47d
```

**Comment by tschottdorf** [comment]
`kv/txn_coord_sender.go:408: cannot commit a read-only transaction` indicates that the client sent an `EndTransaction` command for a transaction which hadn't started before (i.e. nothing that would lay down an intent). Could you get some traces from the server? The last transactional one before the panic should be the offender. You're not load-balancing, right? There's a chance you'd get this too when switching nodes during the txn.

**Comment by bdarnell** [comment]
Ah yes, I was load balancing (on AWS). The first crash happened after several minutes because that's when my `cockroach-prod add-nodes 2` call reached the point of updating the LB; after that it happens more quickly.

**Comment by spencerkimball** [comment]
Seems like this panic should be relaxed. Why panic here?

**Comment by bdarnell** [comment]
The panic (actually a log.Fatal) is in `kv_bank/main.go`; it's not in any production code.

We have a check for switching gateways mid-transaction, so I'm not sure why we'd get "can't commit read-only transaction" instead of "can't write to multiple coordinators". Maybe it's something else: the transaction exits early if `fromAccount.Balance` is too low, so it shouldn't commit, but maybe it's trying anyway. `proto.IsTransactionWrite(&proto.BatchRequest{})` is true, so maybe the logic to disassemble batch requests is failing.

**Comment by bdarnell** [comment]
It's neither of those; it's a race in the coordinator between the `HeartbeatTxn` and the regular RPCs. I can reproduce it without a load balancer, but it does seem to require a three-node cluster to produce the necessary timing.

The problem occurs whenever a transaction is aborted and the coordinator learns about this via a failing `HeartbeatTxn`. 

1. Txn 1 writes intents on rows A and B.
2. Txn 2 tries to write to row A, sees the conflicting intent and aborts Txn 1
3. The coordinator's heartbeat thread sees via `HeartbeatTxnResponse` that the transaction is aborted, so it tears down its internal state including the list of pending intents.
4. The client who created Txn 1 is oblivious to this, so it sends the `EndTransaction` anyway to attempt to commit the transaction.
5. The coordinator would previously pass the `EndTransaction` call to the server unconditionally, and get back a `TransactionAbortedError`. This would cause the client to (correctly) retry the transaction. Now it's a `util.Errorf("cannot commit a read-only transaction")`, which is not retryable.

The error is "cannot commit a read-only transaction" instead of "transaction must not write on multiple coordinators" because that check is done only when `proto.IsTransactionWrite()` returns true, and it is false for `EndTransaction`. We need to include `EndTransaction` in the "multiple coordinators" check.

I think we need to add a `CoordinatorID` field to `Header.Txn` so we can distinguish "the client used multiple coordinators" from "this was the right coordinator, but we have forgotten about the transaction". We need to be able to send a retryable error code in this case (but it's not always an error! the transaction may have committed and the client is retrying its `EndTransaction` due to a network fault). We may want `heartbeat()` to wait for `clientTimeout` before unregistering the transaction, or allow the coordinator to look up the transaction record to see if the transaction is completed (if it is, it's safe to send the request and allow the response to be served from the response cache).

**Comment by tschottdorf** [comment]
What if the heartbeat simply didn't quit if it found the `Transaction` had been aborted (instead, it would remain running, just not attempting further heartbeats)? After all, it's servicing the client and its associated state on `TxnCoordSender` and that expires when the client terminates the `Transaction` or when we're sure the client has abandoned us.

Does that leave anything open?

**Comment by tschottdorf** [comment]
It could even tell the client what's up: If heartbeat finds out we're aborted, but client is happily writing more intents, we could "poison" its response (injecting a `TxnAbortedError`) to have it restart early. I doubt that's a worthwhile optimization for now though, with heartbeats being fairly infrequently.

**Comment by bdarnell** [comment]
Yes, I think that simply leaving the heartbeat goroutine open until the client either attempts to commit or abandon would work. Injecting an early TxnAbortedError could be a useful optimization for mapreduce-style transactions (we expect those to potentially go through multiple restarts before their priority gets bumped up enough to succeed), but we don't need to do that now.

**Comment by tschottdorf** [comment]
Ok. Let me know if you want me to do it.
