### ISSUE TITLE
sql: Add guides for working with sql.y

### ISSUE THREAD

**Issue by lego** [cockroachdb/cockroach#20294]
We can definitely improve the developer experience of editing `sql.y`. In particular, adding new statements. Even if it's just a small bit of documentation that mentions these are the places you add tokens, statements, and the interface you implement. Is there an appropriate place for this documentation?

(This also generalizes outside of `sql.y` for adding new column types, making it easier to introduce a new type even if it's just slightly better than cargo-culting an existing PR).

Also slightly related, you can add a new statement type that is parsed but forget to implement `Statement`, i.e. not add the cargo-cult code in `pkg/sql/parser/tree/stmt.go`. It will happily go through the parser, but cause unexpected problems on the other side. The main source of confusion on this was `TestParse` failures do not clearly indicate when `Statement` is not implemented. This would be an easy change to make, tbh.

cc: @RaduBerinde @knz

**Comment by knz** [comment]
Yes there is a codelab in the docs/ directory. This needs to be updated in light of the recent code shuffling, but it's the place to explain these things.

**Comment by RaduBerinde** [comment]
Oh, that codelab is pretty good. Maybe we should add a pointer to it at the top of `sql.y`.
