### ISSUE TITLE
cli/config: create blacklist of known buggy configurations

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#20311]
As more developers try out CockroachDB, we're inevitably going to run into issues where interactions with specific configurations are broken. The configurations may be certain cloud providers, certain operating systems, certain virtualizations, certain network stacks, or any number of other variables outside of Cockroach's control. We've already seen examples of this kind of issue.

While debugging these problems the first time will be a time-consuming necessity, being forced to debug them a second time will be a waste. We should create a blacklist of system configurations that we know to interact poorly with Cockroach. Each blacklisted config should be able to choose how strongly to complain, ranging from an innocent log warning to a complete refusal to let Cockroach run. On startup, a Cockroach node will compare the system config that it's running on against this blacklist and act accordingly. This will save us time in the future and help users from running into issues that we've already diagnosed.

cc. @andreimatei, who this idea originated from.

**Comment by cuongdo** [comment]
Would this make a good core starter project?

**Comment by petermattis** [comment]
I think this is a bit under-specified for a starter project. Before handing it off to someone new I'd like to see a few concrete examples of bad configs that we'd want to blacklist and how we'd go about doing it. 

And the project exists outside of core for the most part.

**Comment by nvanbenschoten** [comment]
The driving example of this was Ubuntu 14.04 on EC2 with Xen networking. I'm not sure how much of this we'd be able to detect without root privileges, but I think we'd be able to figure out some way of roughly determining if we're running on that config. 

If that's the only example we have then maybe it's not time to invest effort into creating this blacklist. Still, I expect that we're going to stumble upon more of these going forward so we should keep this issue open to track future additions.

I also agree that this is outside of core, although it's not a terrible general starter project.

**Comment by bdarnell** [comment]
Other known issues include machines with less than 2GB of ram and some very azure-specific issues noted in cockroachdb/docs#1356. I'm not sure how practical it would be to detect cases like these.

**Comment by dianasaur323** [comment]
we can definitely scope this out further -> we do have a couple things that I think could make this list lying around in either airtable, some usability docs, or in issues. What was your perceived timing here?

**Comment by nvanbenschoten** [comment]
I think the 1.3 milestone makes sense. In the meantime, we should document these known issues (https://github.com/cockroachdb/docs/issues/2268).

**Comment by tbg** [comment]
Closing for #32906 which is a bit more specific in scope.
