### ISSUE TITLE
sql: fix duplicate key error message

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#2032]
The error message currently references the encoded key which shouldn't be leaked to the user and is mostly unintelligible. The message should be translated to refer to a column and the conflict values. See:

https://github.com/cockroachdb/cockroach/blob/master/sql/insert.go#L121
https://github.com/cockroachdb/cockroach/blob/master/sql/update.go#L174

**Comment by tamird** [comment]
Depends on https://github.com/cockroachdb/cockroach/issues/1891
