### ISSUE TITLE
sql: CREATE TABLE with a Foreign Key reference doesn't create a table immediately

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#20327]
Whenever we create a table with a FK reference a new table is added with a schema change to the referenced table. The newly created table is placed in the ADDING state and becomes live only once the schema change to the referenced table has gone live.

The above behavior prevents an INSERT statement in the same transaction as the CREATE TABLE with FK from functioning.

**Comment by justinj** [comment]
dup #17949?

**Comment by vivekmenezes** [comment]
yes closing
