### ISSUE TITLE
roachtest: test filesystem corruption via CORDS

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#20337]
We've known for a while about the [CORDS paper] from earlier this year which tested how various distributed systems react to filesystem-level corruption of a single block. Their conclusion on CockroachDB is reproduced below. My main takeaways from it are

1. We *often* do the right thing (terminate the affected node, hopefully leaving the rest of the cluster to operate normally) **but**
1. Apparently we sometimes replicate corruption to followers. I think this means that the corrupted data makes it through [our CRC32 checksumming] and RocksDB's as well.

The second point is scary, and needs to be understood better. Is it perhaps possible that the corruption targets RocksDB metadata that isn't itself checksummed (i.e. for example the SSTables itself are checksummed, but not the indexing structure)?

Fortunately, [the code] is public (though the specific testing setup for CockroachDB is missing), and while getting the infrastructure to run this kind of test in place is going to be work, a lot of it has already been done by Ganesan et al.

> CockroachDB is a SQL database built to survive disk,
machine, and data-center failures. It uses a tuned version
of RocksDB underneath for storage; the storage engine
is an LSM tree that appends incoming data to a persistent
log; the in-memory data is then periodically compacted
to create the sst files. The manifest and the current files
point to the current version of the database.
Summary and Bugs: Most of the time, CockroachDB
simply crashes on corruptions and errors on any data
structure, resulting in reduced redundancy. Faults in the
log file on the leader can sometimes lead to total cluster
unavailability as some followers also crash following the
crash of the leader. Corruptions and errors in a few other
log metadata can cause a data loss where CockroachDB
silently returns zero rows. Corruptions in sst files and
few blocks of log metadata cause queries to fail with error
messages such as table does not exist or db does not
exist. Overall, we found that CockroachDB has many
problems in fault handling. However, the reliability may
improve in future since CockroachDB is still under active
development.

I don't understand the "silently returns zero rows" portion well, but perhaps that is more clearly discernible from a thorough look at [the code], which seems well worth doing either way.

Thanks to @aganesan4 and her collaborators for their work!

[our CRC32 checksumming]: https://github.com/cockroachdb/cockroach/blob/1ea9c20ae771fb736fa38f698895fbdd2d2e9791/pkg/storage/engine/mvcc.go#L486
[CORDS paper]: https://www.usenix.org/system/files/conference/fast17/fast17-ganesan.pdf
[the code]: https://github.com/aganesan4/CORDS

**Comment by tschottdorf** [comment]
This is probably getting ahead of the curve, but we may also find it useful to test RocksDB in relative isolation, i.e. run a shim workload directly on top of an engine and see if we can manage to get unnoticed corruption there. And before that, probably worth a look at what corruption resilience testing RocksDB run themselves; perhaps there are vulnerabilities that they're aware of.

**Comment by petermattis** [comment]
Injecting bit errors into sstables and the WAL would be easy with a wrapper RocksDB env. We could also simulate corruption of filenames (which would probably look like missing files to RocksDB).

**Comment by arjunravinarayan** [comment]
Our first step should be to reproduce the errors, for which we would greatly appreciate help from @aganesan4 and @ramanala.

**Comment by ramanala** [comment]
Hi, we can help with this effort. I am currently working on a few other things - so give me some time (maybe a day or two) and I can provide the workloads and checkers that we used. In case you want to analyze some of the issues before that, I reported them in detail on the forum: https://forum.cockroachlabs.com/t/disk-corruptions-and-read-write-error-handling-in-cockroachdb/258. I had also attached the server logs for three distinct problems. Please take a look at it.  Thx!

**Comment by tschottdorf** [comment]
cc @lego

**Comment by ramanala** [comment]
Hello,
I have checked in the cockroachdb init and workload scripts in the CORDS repo if you want to run them yourselves. I am also linking the results directory that we preserved from our original experiments at this URL [](http://pages.cs.wisc.edu/~ra/CORDS/Cockroach/). There are two files: one for the read workload and the other for update workload. Please untar them.

Inside each directory, you will find many directories. Each subdirectory corresponds to a run in which CORDS injected a single corruption or an error. The directory names are formatted as follows:
result_{NODE_ID}_{FILENAME}_{BLOCK_NUM}_{OPERATION}_{ERR_TYPE}. For example, "result_2_000003.log_21_r_eio" means that on **node 2**'s **000003.log** file, an EIO was injected for a read operation for logical block number 21. With each run directory, you will find the results for that directory: there are server logs, and more important the client's log of what data it received from the servers. 

Please let us know if you need any sort of help with this. We would be glad to help. Thanks!

**Comment by petermattis** [comment]
See also https://github.com/scylladb/charybdefs.

**Comment by bdarnell** [comment]
Yeah, testing for the xfs+san issue would require something different. Charybdefs can't help there; I'm not sure what would.
