### ISSUE TITLE
sql: OID doesn't support any comparison operators besides equality

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#20332]
I was doing some randomized testing and hit a strange case where an OID primary key column didn't support comparison to OID datums. @jordanlewis mentioned that OIDs weren't really meant to be used as primary keys, so perhaps we should error if they are? Or maybe fix this comparision. Dunno, I really don't have any background here.

```
> CREATE TABLE o (a OID PRIMARY KEY);
> SELECT * FROM o WHERE a < 3;
pq: unsupported comparison operator: <oid> < <int>
> SELECT * FROM o WHERE a < 3::oid;
pq: unsupported comparison operator: <oid> < <oid>
> SELECT * FROM o WHERE a < 3:::oid;
pq: unsupported comparison operator: <oid> < <oid>
```

Assigning to @jordanlewis for triage.

**Comment by jordanlewis** [comment]
This is just an omission - we never added the CmpOp for oid<->oid comparisons besides the equality one. I think we should just add it.
