### ISSUE TITLE
sql: asynchronous ALTER TABLE name [ADD|DROP] COLUMN ...

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#2035]
Lots of work to make this happen. Adding a non-unique column should be a straightforward change to the `TableDescriptor`. Adding a unique column would also require adding a unique index which will require the infrastructure for the multi-step process of:

* Adding the index to the `TableDescriptor` but marking it as write-only.
* Waiting for the `TableDescriptor` change to propagate to all of the nodes.
* Backfilling the index with some sort of mapreduce over the table.
* Marking the index as read-write in the `TableDescriptor`.

Dropping a column (assuming it is not referenced by an index) will also be a multi-step process:

* Marking the column as deleting in the `TableDescriptor`.
* Waiting for the `TableDescriptor` change to propagate to all of the nodes.
* Deleting the column with some sort of mapreduce over the table.
* Removing the column from the `TableDescriptor`.

**Comment by petermattis** [comment]
If you'd like, I can do the grammar changes required for this.

**Comment by tamird** [comment]
The remaining work here is tracked by #2845.
