### ISSUE TITLE
docs: highlight treatment of NULLs in SELECTs with ORDER BY clause

### ISSUE THREAD

**Issue by richardwu** [cockroachdb/cockroach#20356]
In the postgres docs, the [`ORDER BY` section](https://www.postgresql.org/docs/9.0/static/sql-select.html#SQL-ORDERBY) mentions how `NULL`s are treated in both `ORDER BY ASC` and `ORDER BY DESC`.

Postgres sorts `NULL`s last and first with `ASC` and `DESC` directions, respectively.

In Cockroach, `NULL`s sort first and last with `ASC` and `DESC`, respectively. Note: this deviates from postgres behavior.

This is briefly noted in the ["NULL handling" section of the docs](https://www.cockroachlabs.com/docs/stable/null-handling.html#nulls-and-sorting) for `ASC`, but not for `DESC`. We should also crosslink this section in the [`ORDER BY` section of the docs](https://www.cockroachlabs.com/docs/stable/select.html#sorting-retrieved-values).

**Comment by jseldess** [comment]
Moved to the docs repo: https://github.com/cockroachdb/docs/issues/2233
