### ISSUE TITLE
sqlccl: No protection against running multiple IMPORTs into the same table

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#20370]
This was mostly user error, but here's my story:

1. Spin up a 3 node roachprod cluster
1. Enable the `experimental.importcsv.enabled` setting
1. Run an IMPORT of tpc-h sf100 into the table `tpch.lineitem`
1. It OOMs the gateway node many hours later (https://github.com/cockroachdb/cockroach/issues/19635)
1. Restart the OOM'ed node.
1. The import job shows up as still running, and I can't cancel it (https://github.com/cockroachdb/cockroach/issues/18139)
1. Start up another import job into the same table (my mistake) but using a different temporary store and different data source (tpc-h sf10). I only remembered to use a different temp store because of the really nice "already contains a BACKUP-CHECKPOINT file (is another operation already in progress?)" error, so kudos for that 👍
1. The system accepts the job, but some tens of minutes later spits out the error: `pq: IO error: While open a file for appending: /mnt/data1/cockroach-temp804042042/027171.log: No such file or directory`

Maybe it was something else, but it naively seems most likely to me that it was caused by doing two imports into the same nonexistent table at the same time.

@mjibson

**Comment by a-robinson** [comment]
Hm, maybe it is something else. I tried doing the sf-10 restore into a different database and got a similar error: `pq: IO error: While open a file for appending: /mnt/data1/cockroach-temp242505443/026383.log: No such file or directory`

The logs on node 2 are full of entries like:
```
E171201 01:12:08.466616 152093 storage/engine/disk_map.go:256  [n2] unable to clear range with prefix [247 6 196]: IO error: While open a file for appending: /mnt/data1/cockroach-temp804042042/027171.log: No such file or directory
E171201 01:12:08.472408 152015 storage/engine/disk_map.go:256  [n2] unable to clear range with prefix [247 6 134]: IO error: While open a file for appending: /mnt/data1/cockroach-temp804042042/027171.log: No such file or directory
E171201 01:12:08.482725 152090 storage/engine/disk_map.go:256  [n2] unable to clear range with prefix [247 6 193]: IO error: While open a file for appending: /mnt/data1/cockroach-temp804042042/027171.log: No such file or directory
E171201 01:12:08.490319 152182 storage/engine/disk_map.go:256  [n2] unable to clear range with prefix [247 7 12]: IO error: While open a file for appending: /mnt/data1/cockroach-temp804042042/027171.log: No such file or directory
E171201 01:12:08.504708 152154 storage/engine/disk_map.go:256  [n2] unable to clear range with prefix [247 6 240]: IO error: While open a file for appending: /mnt/data1/cockroach-temp804042042/027171.log: No such file or directory
E171201 01:12:08.512026 152098 storage/engine/disk_map.go:256  [n2] unable to clear range with prefix [247 6 201]: IO error: While open a file for appending: /mnt/data1/cockroach-temp804042042/027171.log: No such file or directory
E171201 01:12:08.513663 152
[...]
```

It may be a more serious corruption issue. Does this ring any bells with you, @mjibson?

**Comment by a-robinson** [comment]
Node 3 has the same log entries. Nodes 2 and 3 are the ones that didn't OOM during the initial sf-100 IMPORT attempt.

**Comment by a-robinson** [comment]
Hm, or maybe it's related to the fact that node 1 had the necessary scopes to write to the temp GCS bucket but nodes 2 and 3 didn't. I think they were all able to read from it, though.

**Comment by mjibson** [comment]
When you restart a node with a running IMPORT job, then the job will be listed as running in the jobs tab, although nothing is actually running (this is a known problem with a complicated fix). As of yesterday you can now "CANCEL JOB <id>" and it'll mark it canceled. But there almost certainly weren't two jobs running at the same time.

Nothing comes to mind here. The error messages suggest that the temp rocksdb store is having problems creating its files to store the temporary KVs. I don't think it's a GCS roles issue (unless the error message is a red herring) because the phase when its writing to the rocksdb temp store is before that.

If your binary is at most ~1 week old, try using `nodelocal:///tmp` as your temp dir. That should dump the data into `/mnt/data1/extern/tmp` which would prove it's not a GCS problem.

**Comment by a-robinson** [comment]
I took down the nodes last night, but saved the data directories to GCS if you want to try using them to reproduce: 
https://storage.googleapis.com/cockroach-alex/import-corruption1.tar.gz
https://storage.googleapis.com/cockroach-alex/import-corruption2.tar.gz
https://storage.googleapis.com/cockroach-alex/import-corruption3.tar.gz

**Comment by dt** [comment]
The distsql tempdir cleanup issue (deleting the file and file not found) has been fixed here.

The fact that you can start IMPORTs (or RESTOREs) to the same table (or db), and both will run until one finishes and writes the table descriptors is a known pitfall, but we don't have any current plans on how to fix it.

**Comment by dt** [comment]
The IO errors on this were a bug that was fixed. The name collisions were a known limitation (names didn't get reserved until we were done importing so they went live all at once) but with the shift to `IMPORT INTO` all imports now reserve names up front too, so it isn't possible to import the same table twice.
