### ISSUE TITLE
sql/parser: keep token position information in all syntax tree nodes

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#2037]
`scanner.Error` pretty-prints errors during parsing, showing their exact location. But position information is not maintained in syntax tree nodes which means that errors during expression evaluation are much less precise.

**Comment by petermattis** [comment]
Punting this to 1.0 as it won't affect on-disk formats.

**Comment by tamird** [comment]
@RaduBerinde do you still intend to tackle this? Perhaps @nvanbenschoten would be interested in taking a look.

**Comment by RaduBerinde** [comment]
I wasn't planning to work on it any time soon, so it's up for grabs.

**Comment by knz** [comment]
This came up again. We need either to extend `goyacc` or switch to a different parser generator. I was looking at GNU bison, which may be appropriate -- it supports multiple languages via parser templates, so we could perhaps give it a Go template.

**Comment by jordanlewis** [comment]
Closing as unimportant / we're not going to do it.
