### ISSUE TITLE
storage: tscache skiplist has a key size limit of 64K

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#20389]
https://sentry.io/cockroach-labs/cockroachdb/issues/412094857/

```
*log.safeError: stopper.go:179: string
  File "github.com/cockroachdb/cockroach/pkg/storage/tscache/interval_skl.go", line 589, in addNode
  File "github.com/cockroachdb/cockroach/pkg/storage/tscache/interval_skl.go", line 305, in addRange
  File "github.com/cockroachdb/cockroach/pkg/storage/tscache/interval_skl.go", line 246, in AddRange
  File "github.com/cockroachdb/cockroach/pkg/storage/tscache/skl_impl.go", line 80, in Add
  File "github.com/cockroachdb/cockroach/pkg/storage/tscache/skl_impl.go", line 86, in SetLowWater
...
(16 additional frame(s) were not displayed)

stopper.go:179: string
```

**Comment by mberhault** [comment]
I was just looking through that.
Turns out @andy-kimball's neat skiplist used in the tscache has a max key size of 255 (uint16).
I don't think we impose that limit anywhere.

Assigning to @nvanbenschoten who's been poking at this the most.
I'll dedup a couple other sentry crashes with the same trace.

**Comment by mberhault** [comment]
https://sentry.io/cockroach-labs/cockroachdb/issues/412303651/

**Comment by mberhault** [comment]
https://sentry.io/cockroach-labs/cockroachdb/issues/412303364/

**Comment by andy-kimball** [comment]
uint16 has a limit of 65535, not 255. That limit comes from Badger, originally. At the cost of an extra 4 bytes per node, it could be easily increased to uint32. Or it could go to a 24-bit number with a bit more work without increasing the bytes per node, if a key size limit of ~16M bytes is large enough.

Does Cockroach have any particular limit on key size?

**Comment by mberhault** [comment]
Oops, I got uint8 in my head for some reason.

I'm don't think we have an actual key size limit, but we should at least be
aware of our dependencies.

From the sha, I'm guessing this happened during our nightly tests. I'll see
if I can find more details.

**Comment by nvanbenschoten** [comment]
What @mberhault said is correct, we currently don't place any restrictions on key lengths. That said, we've recently run into other issues with excessively long keys (https://github.com/cockroachdb/cockroach/issues/19746, https://github.com/cockroachdb/cockroach/issues/19751) and there is a proposal to bound the size of keys that we allow (which conveniently happens to be at 64 KB). I'll prioritize this now that there are other structures that expect a limit and which panic without one.

@andy-kimball when you say we could increase `keySize` to a 24-bit number, are you referring to stealing bits from `height` field by merging both into a `uint32`? That's not a bad idea, although you're right that it would increase the complexity of the `node` struct. Regardless, there will still be a fixed limit on the key size so we'll need to bound things somewhere, either by limiting key size directly or alternatively losing precision in the timestamp cache by truncating keys to a fixed length.

**Comment by andy-kimball** [comment]
Yes, re: 24-bit I mean we could steal the height bits. We'd make a single uint32 with a couple of accessor methods to get/set the height/keySize values. I actually almost did that when I wrote the code originally, but it wasn't too important to my demo code, so I decided not to do it.

**Comment by nvanbenschoten** [comment]
@andy-kimball I'll make that change if you're ok with it. Even if we do limit keys to 64 KB in Cockroach, it seems like a clear win that will give us some breathing room if we ever want to increase the key limit

**Comment by andy-kimball** [comment]
Sure, sounds good.
