### ISSUE TITLE
storage: Move node liveness to non-versioned keys

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#20399]
We've previously discussed (https://github.com/cockroachdb/cockroach/issues/14990, https://github.com/cockroachdb/cockroach/issues/19699) reducing the GC TTL on the node liveness range in order to make sure GC doesn't interfere with the liveness range. Most recently, @bdarnell proposed that we should go further and change how node liveness keys are written so as to avoid creating garbage at all. Quoting him from https://github.com/cockroachdb/cockroach/issues/19699#issuecomment-341145963:

> GC is expensive too, which has been known to exacerbate problems here. A better solution would be to migrate liveness to non-versioned keys. This would enable various rocksdb optimizations when keys are overwritten (as opposed to new keys written and old ones deleted). The reason we have versioned liveness keys is just so we can (ab)use the commit trigger mechanism; in order to move to non-versioned keys we'd need to introduce some sort of trigger that can be used for normal KV ops. The migration will probably be the hardest part of making this change. I think this would be a very big win, though.

Opening a separate issue for this based on recent discussion with @petermattis.

**Comment by petermattis** [comment]
Related to the discussion are some stats from a node liveness from a user's cluster:

```
      "stats": {
        "contains_estimates": false,
        "last_update_nanos": 1512063410465255605,
        "intent_age": 0,
        "gc_bytes_age": 1966278291870,
        "live_bytes": 77994,
        "live_count": 18,
        "key_bytes": 3517608,
        "key_count": 18,
        "val_bytes": 6818341,
        "val_count": 293107,
        "intent_bytes": 0,
        "intent_count": 0,
        "sys_bytes": 724,
        "sys_count": 10
      },
```

So the range has 76KiB of live data, but 9.8MiB of total data. Notice that there are 8 non-system keys and 293107 values. That's 36638 versions per key.

Cc @spencerkimball, @tschottdorf

**Comment by tschottdorf** [comment]
I think this would be nice, but the added complexity may not be worth it for a long time after @spencerkimball is through with his current spurt of GC improvements.

NodeLiveness would profit naturally from being able to set more general GC policies that are implemented by amortizing the deletion of old versions over writes of the new versions. I know @spencerkimball is a fan of this sort of thing, though we've resolved that it won't be trivial to enact those.

**Comment by petermattis** [comment]
We can also revive https://github.com/cockroachdb/cockroach/pull/17628 and place a shorter GC TTL on the node liveness range.

**Comment by nvanbenschoten** [comment]
@tschottdorf what added complexity do you foresee? For what it's worth, we already [do this](https://github.com/cockroachdb/cockroach/blob/2b54eb39c3c7ab0fa31b078c842e39efbb2adc98/pkg/server/status/recorder.go#L414) for `NodeStatus` keys.

**Comment by tschottdorf** [comment]
@nvanbenschoten allowing transactions on inline values. This is not something that currently exists, so either it needs to be introduced or we need to find a different mechanism for the gossip update. I'd wager that the latter is likely the preferable option if all we want to do is make NodeLiveness more robust.

The latest GC changes should deal with this pretty nicely, including chunking up the GC of keys with many versions into manageable bits. I'd hold off on further action until we see that the current approach isn't sufficient.

**Comment by tschottdorf** [comment]
@petermattis shortening the TTL by default seems generally reasonable, but I'd also hold off on it until we see whether the recent changes leave anything to be desired.

**Comment by a-robinson** [comment]
To follow up on this, the default node liveness TTL was shortened by https://github.com/cockroachdb/cockroach/pull/17628
