### ISSUE TITLE
build: master binaries report wrong version

### ISSUE THREAD

**Issue by arctica** [cockroachdb/cockroach#20406]
@tschottdorf mentioned in another ticket the following way to get a build for the latest master:

`wget https://edge-binaries.cockroachdb.com/cockroach/cockroach.linux-gnu-amd64.LATEST -O cockroach && chmod +x ./cockroach`

But when I did that today and started up the cluster, I noticed the nodes report the following build version:

`v1.2-alpha.20170901-2166-g7773d2a`

This is neither the build date and commit id for the latest master nor even the latest v1.2-alpha tag which would be `v1.2-alpha.20171113` as of this posting.

I do believe though that this binary includes the code for the latest master commit as I've seen new things in the admin ui that I haven't seen before and that were definitely not in the 20170901 build. Therefor it seems to be purely a wrong version info output.

**Comment by mberhault** [comment]
This is just the default git version, it picks up the latest tag, adds the number of commits since and the current sha.
So for master binaries, the only part you really care about is the last bit: `g7773d2a` which tells you that it was built at sha 7773d2a

**Comment by arctica** [comment]
Hm but it's not the latest tag as far as I can tell. That should have been `v1.2-alpha.20171113` like mentioned. Thanks for clearing up the other parts  of the version string (especially last one), that's more descriptive.
