### ISSUE TITLE
ui: missing favicon

### ISSUE THREAD

**Issue by arctica** [cockroachdb/cockroach#20407]
Running current master `v1.2-alpha.20170901-2166-g7773d2a`, the admin ui seems to be missing the favicon.

Requesting /favicon.ico returns a 404 error. This used to work and was helpful in spotting the cockroach admin panel tab when having lots of tabs open.

**Comment by jseldess** [comment]
Thanks for the report, @arctica. I just checked using current master, and I'm not seeing this problem. Can you update your copy of master and try again?

**Comment by arctica** [comment]
@jseldess thx for checking it. I've just updated to the latest master as of this posting (`v1.2-alpha.20170901-2176-g8d3ab8d`) and still can reproduce the issue.

The HTML of the admin UI contains this bit: `<link href="favicon.ico" rel="shortcut icon">` and trying to request http://host:8080/favicon.ico gives a 404.
Interestingly though I can't find any request to this file in the network tab of the dev console.

Maybe it was cached in your browser? Try to force refresh the page or maybe an incognito window.

I'm using FF 57.0. When I tried to reproduce this problem in Safari 7.0.2, the whole UI wouldn't render because it throws an error: `[Error] ReferenceError: Can't find variable: Promise (vendor.dll.js, line 52)`. In Chrome on the other hand everything seems to work fine, including the favicon. Not sure where it actually comes from, probably not the /favicon.ico url but some data url in a css file? Dunno.

**Comment by jseldess** [comment]
@arctica, thanks for the additional details. I can't reproduce this in FF or Safari. @mrtracy or @couchand, do either of you have ideas?

**Comment by couchand** [comment]
@arctica did you recently update Firefox?  This happened to me on updating Firefox to 57.  I don't have a satisfactory reason why it would happen, but the solution for me was to clear the cache and restart Firefox.  Can you try that and let us know if that fixes it?

**Comment by arctica** [comment]
@couchand that's exactly what I did and after following your recommendation, the favicon seems to be back. Very strange as I remember that I restarted the browser a couple times before that already but never in combination with a cache clear. This is probably just some weird Firefox behaviour when updating to version 57 while also having a previous version of the page in cache. I know that in this FF version a lot has changed, especially the CSS engine.

Might still make sense to remove the <link> tag for the favicon file that doesn't exist but I'm going to close the issue as it's not a CockroachDB issue.

**Comment by couchand** [comment]
@arctica The favicon file does indeed exist at that URL (at least on every version I tested).  I'm not sure why you'd be seeing a problem requesting the file directly, that isn't consistent with anything I've seen.

Glad to hear this was solved, though.

**Comment by arctica** [comment]
@couchand wow, that's very weird as I just verified that the file does indeed exist but I'm 100% sure this was giving me a 404 error before. Must be connected to the update and FF not showing it.
