### ISSUE TITLE
sql: supporting better errors or type-casting for DEFAULT expressions (like now())

### ISSUE THREAD

**Issue by lgo** [cockroachdb/cockroach#20402]
While trying to run ActiveRecord tests, a [schema definition](https://github.com/rails/rails/blob/master/activerecord/test/schema/postgresql_specific_schema.rb#L21) I've run across generates:

```sql
CREATE TABLE ... (<col> data DEFAULT now())
``` 

This does not work because `now()` has to be explicitly cast to `date`. This is annoying because:
- Some ORMs/libraries may auto-generate the `now` statement. This may only be the case for `timestamp` columns, I'd need a citation on this point.
- Any existing code snippets like this will just not work.
- The error raised is rather confusing, `pq: unknown signature: now() (desired <date>)`.

While doing type-casts here may be out of the question[1], a few solutions may be:
- Define the built-in `now()` with different return type signatures for all sane types `timestamp` can be cast to.
- Spew out a more reasonable error, suggesting the user use `::<TYPE>` to resolve the problem.

(let's try the first solution, and if it doesn't work possibly give the second a shot)

[1]: Doing implicit type-casts is a separate long discussion on its own and is large in scope.

**Comment by mapleleafss** [comment]
@lego ,could I have a try? And I have a difficult to understand the below sentence

` Define the built-in now() with different return type signatures for all sane types timestamp can be cast to.`

Which type ensure all sane types timestamp can be cast to? Is it the date type? And when all sane types timestamp cast to another type, time zone problems need to be considered.  Should I need to create a function now() which return a date value(E.g 2017-12-4)?

**Comment by lego** [comment]
@mapleleafss right now we are not sure if we want to add the overloaded functions, an opinion expressed by @andreimatei.

Because of that, I don't think this issue should be done unless we have reports from other people about this confusion.

**Comment by mapleleafss** [comment]
@lego Okay. I got it.

**Comment by jviksne** [comment]
Hi, I'd also like to vote for this to be implemented. I'm migrating from PostgreSQL to CockroachDB and the inserts into date fields that used NOW() to populate the current date fail in CockroachDB.
For the fields that use timezone I guess the input should be treated as current timestamp with no timezone info passed - which in PostgreSQL I guess defaults to system's timezone.

**Comment by jordanlewis** [comment]
Thanks @jviksne. As a reminder, we do have a workaround for this issue: add a cast to `now()` in your default expression, like `now()::date`.

Does that workaround solve your problem?

**Comment by jviksne** [comment]
Great, thanks!

**Comment by jordanlewis** [comment]
Closed by #37284.
