### ISSUE TITLE
tscache: skiplist implementation OOMs stress tests

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#20401]
Something about the new skiplist-based tscache causes our stress tests to quickly OOM on certain packages in certain configurations. See:

* #20394
* #20387 
* #20386
* #20385
* #20384
* #20383
* #20382
* #20381
* #20379 
* #20377

**Comment by mberhault** [comment]
Are you sure it was OOMs and not panics due to #20389?

**Comment by benesch** [comment]
Possible it's _both_, but we repro'd the OOM reliably on at least one of the failed packages.
