### ISSUE TITLE
ui: page doesn't change and JS errors

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#20415]
After looking at the jobs page, I click on other pages and the URL changes but the page doesn't. The dev console shows some JS errors:
![screenshot 2017-12-01 18 45 39](https://user-images.githubusercontent.com/377201/33508396-13998c20-d6c8-11e7-8820-c7490e8c2d91.png)

Matt, perhaps you can route this.

**Comment by vilterp** [comment]
The decoded error: `Attempted to update component `Connect(NotLiveNodeList)` that has already been unmounted (or failed to mount).`

I've seen this once or twice; haven't had time to look into it.

**Comment by couchand** [comment]
I'm seeing a handful of errors in the console before the React one:

![screen shot 2017-12-04 at 11 42 11 am](https://user-images.githubusercontent.com/793969/33564303-39838194-d8e8-11e7-9bd1-890ce9bf2e97.png)

I suspect those are the original issue, and the attempt to update the unmounted component is an side effect.  Are you guys seeing the same thing?

**Comment by couchand** [comment]
PR #20527 takes approach number one above.  I'm punting on two and three for now, I'm not sure that two is the right way to go, and three is a larger initiative than I want to tackle at the moment.
