### ISSUE TITLE
server,sql: use new json type for system tables which contain json

### ISSUE THREAD

**Issue by vilterp** [cockroachdb/cockroach#20418]
Namely `rangelog` and `eventlog`. This will allow us to filter & project using the new JSON operators!

Not sure what would be required to migrate the existing text contents to JSON in existing clusters.

cc @justinj

**Comment by tschottdorf** [comment]
I'm at a loss for labeling this. A-sql-something?

**Comment by knz** [comment]
I think this lands in core too, because we need a careful migration strategy for this. SQL has nothing to do with `rangelog`.

**Comment by tschottdorf** [comment]
I can guarantee that nothing will ever happen if this lands in CF&S, so we might as well leave it dangling.

**Comment by tschottdorf** [comment]
Looking at this again, we'd probably introduce a new rangelog table and a cluster version based on which nodes decide which one to write to. The ui has to query both for one release cycle. I don't think we're going to rewrite anything at the core layer.

**Comment by knz** [comment]
Or maybe we leave the core / system stuff as-is and define a SQL view to convert to the JSON type? That would be significantly easier.

**Comment by knz** [comment]
I'm going to close this. If the UI folk need to use JSON operators to query rangelong/eventlog, they can define a new view in the `system` database that casts the text field to JSON, and use that.
