### ISSUE TITLE
ui: don't load font files from fonts.googleapis.com

### ISSUE THREAD

**Issue by arctica** [cockroachdb/cockroach#20425]
Running the latest master `v1.2-alpha.20170901-2176-g8d3ab8d` (but this problem existed for a long time).

The admin UI loads over 5 megabytes of javascript on a pageview. protos.dll.js 1MiB, vendor.dll.js 2MiB and bundle.js 2.1MiB.

I think that's a bit excessive but it would help a lot of the static asset files were at least cached (make use of ETags) and not re-loaded on every page refresh. It's especially painful when not having a very fast connection to the cockroachdb node in question. It can take a few minutes to load the page when out in a more remote place on a mobile connection.

The page also needlessly leaks information like the IP, browser and cockroachdb hostname of the request to fonts.googleapis.com. Considering that CockroachDB is to be also used in enterprise environments, it might make sense to host the little .css file from there in CockroachDB itself.

**Comment by benesch** [comment]
Assigning @mrtracy who added the Google font face @import. @mrtracy, we can just use the bundled Lato instead, no?

**Comment by benesch** [comment]
Addressed the caching problem in #20429. Thanks for the report! It's incredibly helpful to have feedback like this. We clearly haven't been testing the web UI on slow connections.

**Comment by couchand** [comment]
@arctica, as I mentioned on your previous ticket, we've already made #18668 to address the ETags.  Thanks @benesch for taking care of that so quickly!

We also have #18789 to work on removing any dependencies we're pulling in that aren't needed.

I appreciate your general concern about the size of the bundle, it's definitely something that's on our radar to improve.  If you have any specific advice about ways to cut down the size, we're more than happy to see a PR on the subject.

Regarding that font file being loaded from `fonts.googleapis.com`, good catch.  This is pulled in by an in-development component, and we certainly won't be loading remotely in a released version.  In the meantime, you can run `make buildoss` to get a version that doesn't include that dependency, or use 6ea7d54c1 or any SHA before that to avoid this.

**Comment by arctica** [comment]
@couchand oh sorry, I forgot about that previous ticket. And yea thanks @benesch for putting together such a fast fix.

I'm just in a situation where I sometimes am accessing the UI from a mobile connection from literally around the globe with latencies of 500ms avg and sometimes going to 2s so every slow load is amplified greatly :)

Another fun way to think about the big filesize if not cached: I could load the page about 30 times each day before exhausting the monthly data cap (5GiB) :)

**Comment by arctica** [comment]
@benesch I think this issue shouldn't be closed via #20429 since the fonts issue isn't resolved with that commit, especially since the title here was changed due to the caching issue which #20429 is about having already another issue opened #18668.

**Comment by benesch** [comment]
Sigh, it wasn't supposed to. I guess "Partially fixes #20425" is enough to trigger GitHub's automatic issue closing. Thanks for catching.
