### ISSUE TITLE
sql/parser: flesh out the support for functions

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#2042]
Currently we only support `length`, `lower` and `upper`. There are a lot more string and math functions and most of them should be relatively straightforward to implement given the infrastructure in [builtins.go](https://github.com/cockroachdb/cockroach/blob/master/sql/parser/builtins.go).

**Comment by thschroeter** [comment]
Happy to tackle support for builtin math functions as mentioned in Peter's todo in [builtins.go](https://github.com/cockroachdb/cockroach/blob/master/sql/parser/builtins.go#L64).

**Comment by vivekmenezes** [comment]
Go for it. I'm unable to assign this to you for some reason, but I'm definitely not working on it. Thank you!

**Comment by spencerkimball** [comment]
Could somebody formulate the list of remaining functions?

**Comment by petermattis** [comment]
We don't have a canonical list of all of the functions we want to support. Do we want to support all of the functions in postgres? That seems excessive. Here is a list of some additional work in this area:

* `greatest(...)` - requires hooking up semantic actions in the grammar
* `least(...)` - requires hooking up semantic actions in the grammar
* `trim(...)` - requires hooking up semantic actions in the grammar
* `substring(...)` - requires hooking up semantic actions in the grammar
* `position(...)` - requires hooking up semantic actions in the grammar
* `overlay(...)` - requires hooking up semantic actions in the grammar
* `regexp_{match,extract,replace}()`
* Make all string functions work on character positions, not byte positions.
* Add analogs of all of the string functions which work on `bytes`.

**Comment by lambdawizard** [comment]
Might be useful to split off the remaining builtin functions as separate issues. I'm waiting for a 5 hour C++ build so I will have a look at the trim function.

**Comment by vivekmenezes** [comment]
Thanks for taking this on James. Feel free to create a separate issue for
trim if you'd like

**Comment by lambdawizard** [comment]
I will create a separate issue. I’ve added a `builtin` for trim and added to `builtins`, added the grammar and now trying to wrap my brain around your SQL `Parse(…)` to integrate it in correctly. 


—

**Comment by nvanbenschoten** [comment]
I have a few questions about the remaining unimplemented regexp functions that I was hoping someone could speak towards
- Should we add `regexp_split_to_array` and `regexp_split_to_table` to the list?
- It looks like Postgres uses `substring(string from pattern)` instead of `regexp_extract`. Which one would we like to support?
- `regexp_matches` and a few others of these need support for returning multiple rows. Is that currently supported for builtin functions? It looks like `DTuple`s are disallowed as return types, but they don't seem quite right for this situation anyway.

**Comment by petermattis** [comment]
Functions which require array support will likely need to wait for #2115.

I think we'll end up needing both `regexp_extract` and `substring(string from pattern)`. Hopefully the implementation can be shared. Similarly, I think we'll need `regexp_match` even though we have `SIMILAR TO`.

**Comment by nvanbenschoten** [comment]
As the name suggests for `regexp_split_to_array`, the function is going to have to wait for array support. In addition to this though, both of the builtin functions `regexp_matches` and `regexp_split_to_table` need support to return multiple rows of data. Is this currently possible, and if not, is support for it on the roadmap?

Also, do we want to add support for Postgres-esque [regexp matching operators](http://www.postgresql.org/docs/9.1/static/functions-matching.html#FUNCTIONS-POSIX-TABLE). Branching off this, we might want to add some of the PostgreSQL-specific operators like `~~` and `ILIKE`.

**Comment by petermattis** [comment]
No, it isn't possible for a function to return multiple rows. We do have such support for subqueries, but those are handled differently. The only support on our roadmap is the necessity to implement these functions, which I think is low priority right now. Better to tackle some of the other work here like `trim`, `position`, `overlay` and `bytes` analogs of the existing string functions.

The Postgres regexp matching operators are postgres extensions. I don't see a strong reason to implement them at this time. Better to turn our attention to some of the standard SQL functionality that hasn't been implemented.

**Comment by JackKrupansky** [comment]
Seems like this issue is mostly addressed for Beta. Is there a list of other functions that are intended to be in Beta?

And then there is the issue of experimental_unique_... - seems like that stuff should get settled for Beta  since it will impact the on-disk format for tables that don't have PKs.

**Comment by tamird** [comment]
Should we just close this? Doesn't seem to be tracking anything meaningful.

**Comment by petermattis** [comment]
I think we should do a pass through the functions and open individual issues for the ones that need to be added. In particular, I believe some of the functions that operate on `string` should also work on `bytes` (see the `TODO(pmattis)` in `sql/parser/builtins.go`). I'd like to leave this issue open until those issues are created or we determine that there is nothing to do.

**Comment by spencerkimball** [comment]
@petermattis I'm closing this issue due to age and likely obsolescence.
