### ISSUE TITLE
storage: under replicated ranges persists during heavy write

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/cockroach#20434]
**Question**

1. $ cockroach version
Build Tag:    v1.1.3
 
2. Please describe the issue you observed:

- What did you do?

3 node cluster on a Mac

cat > test.yaml <<EOF
range_min_bytes: 1048576
range_max_bytes: 1048577
gc:
  ttlseconds: 600
num_replicas: 3
constraints: []
EOF

cockroach zone set .default --insecure -f test.yaml

CREATE TABLE t8 (id INT PRIMARY KEY, id2 int, id3 int, id4 int, id5 int, id6 int, id7 int, id8 int)

./[rand](https://github.com/cockroachdb/loadgen/tree/master/rand) -batch 10 dbname t8

the CPU is at 100% during the test
 
- What did you expect to see?

when the load generator is running, the under replicated ranges is non zero which was un-expected.

<img width="1280" alt="screen shot 2017-12-03 at 5 22 24 pm" src="https://user-images.githubusercontent.com/6315124/33530572-6f76f9d2-d84f-11e7-8cd1-6ad3f4278a5a.png">

- What did you see instead?

- [ ] what causes the under replicated ranges during heavy system load? 

- [ ] what could happen to committed data if one of the nodes goes down while under replicated ranges is non zero

**Comment by tschottdorf** [comment]
I have to double-check this, but I think our heuristic which decides under-replication is too optimistic. Essentially it looks for Raft groups that have too few members, but also have members that are "too far behind". Under heavy load, replicas can seem "too far behind" even though they're catching up as quickly as they can. If the theory is correct, it addresses your first question at the bottom of your post.

For your second, if you lose one node then the cluster will become unresponsive, but you don't technically lose data (i.e. there's still a live copy). So if the node comes back, all is well. If the node is permanently dead, you need a recovery mechanism that we don't have today (i.e. it would be manual and carried out by us).

**Comment by petermattis** [comment]
@tschottdorf is correct regarding what causes under-replicated ranges. This is a known problem with the metric, though we don't know how to fix it. We want the measure of "too far behind" to be large enough to not register most ranges that are just a few log entries behind, but small enough that we actually do notice misbehaving replicas quickly. Definitely open to suggestions here.

**Comment by robert-s-lee** [comment]
If a write finished on two out of three replicas, commit is sent back to the client and the third write is in transit.  Does this get reported as a momentary under replicated range?

**Comment by petermattis** [comment]
> If a write finished on two out of three replicas, commit is sent back to the client and the third write is in transit. Does this get reported as a momentary under replicated range?

For a single write operation? No. The same replica has to fall 10 operations behind for the range to be considered under-replicated.

**Comment by nvanbenschoten** [comment]
Closing as stale.
