### ISSUE TITLE
support dashes "-" in usernames so vault can create credentials

### ISSUE THREAD

**Issue by Rio** [cockroachdb/cockroach#20441]
While exploring the use of vault in our infra we've run into the issue of cockroach usernames not supporting the dash character. Vault creates usernames that look like `v-token-readonly-1s9zw5r376s91163z5tp-1512398389`.

Right now when configuring vault to create credentials on a cockroach database using the postgres driver results in `pq: syntax error at or near "-"`

**Comment by mberhault** [comment]
We can probably expand the allowed syntax, we just started out "trivial".
Be aware that using hyphens in usernames will require the use of double quotes around it for every single sql statement.

**Comment by Rio** [comment]
I think that should be ok since we already require quotes around the password. makes it a bit more uniform. That said I'm not intimately familiar with all the statements, I'm probably missing some.

**Comment by mberhault** [comment]
@Rio: this is merged and will be in 2.0 (sometime in April I believe). It allows hyphens anywhere but the first character. Just like postgres, you will need to quote usernames containing hyphens. eg: `CREATE USER "foo-bar";`.

**Comment by Rio** [comment]
Thanks very much! This should help a lot, looking forward to version 2.
