### ISSUE TITLE
sql: i18n of SQL identifiers

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#2044]
We currently require table names (and other SQL identifiers) to be ASCII. MySQL and Postgres both allow at least some non-ASCII characters; we should decide what we want to do here. Note that our current implementation of case-insensitivity will fail for languages such as Turkish which have different ToLower() rules. We should probably also normalize everything to NFC (or NFD; we just need to pick one).

I vote for following the same rules as Go identifiers (allow the unicode "letter" and "digit" classes plus underscores; may not begin with a digit), and making all identifiers case-sensitive (I don't see how we can do case-insensitivity correctly in a global multi-tenant namespace).

**Comment by petermattis** [comment]
Looks like postgres allows any byte inside double quotes. Not sure why I did this differently in our scanner. Curious why case-insensitivity will fail for Turkish. Can you expand on why `ToLower()` fails for such languages?

**Comment by bdarnell** [comment]
Actually, I was mistaken - we allow characters between 128 and 255, which is kind of silly - it gets us the accented latin letters, but also a lot of punctuation. We allow `create table test.foo¿ (a int primary key);` but no ascii punctuation. 

Turkish has both a "dotted `i`" and a "dotless `i`" (the related Azeri language has the same thing; these are the only instances of locale-sensitive ToLower() I'm aware of). In a foolish-in-retrospect attempt to save space in the character set, the lowercase dotted `i` and the uppercase dotless `I` use the ASCII characters, and they created new characters for uppercase dotted `i` and lowercase dotless `i`. This means that in turkish, `ToLower("I")` (with an ASCII capital `I`) returns a lowercase dotless `i`, not `i`. 

This won't completely break things for Turkish users - it should still work as long as they act as if things are case-sensitive (and they may even get lucky with case-insensitive use if their table names don't contain either form of `i`). But it stinks to have this odd edge case and have to document that "table names are case-insensitive (except in Turkish)", and I don't think that the benefits of case-insensitivity are that large to begin with.

**Comment by spencerkimball** [comment]
I'd definitely be surprised if table names required case sensitivity. That's not to say we shouldn't be case sensitive given the obnoxious problems with Turkish, but just that I do see non-trivial benefits to case insensitivity.

**Comment by petermattis** [comment]
[This page](http://www.i18nguy.com/unicode/turkish-i18n.html) talks about the problems with Turkish dotted and dotless "I", though it is really just a verbose version of what Ben wrote.

**Comment by petermattis** [comment]
Would it be so irritating to Turkish users if we map `\u0130` (turkish capital dotted-i) and `\u0131` (turkish lowercase dotless-i) both to `i`? Actually, the only additional normalization is `\u0131` to lowercase dotted-i. The biggest irritation for us is that we'd need to be careful to use our own comparison routines instead of using `strings.ToLower()` or `strings.EqualFold()`.

**Comment by bdarnell** [comment]
That seems reasonable to me; the only thing you'd lose would be the ability to have two tables whose names differ only in the dottedness of their i's. But the fact that I haven't seen this discussed as a potential solution is a bit of a concern (we really shouldn't be the ones to blaze a new trail here), so it's probably worth consulting some turkish speakers before going down this path.

**Comment by petermattis** [comment]
The page I linked to [earlier](http://www.i18nguy.com/unicode/turkish-i18n.html) mentions:

```
Often companies adopt a quick workaround: They use the Turkish case rules except the case of the letter i remains as in English. This fixes the logic problems, but irritates Turkish end-users since functions that depend on case now do the wrong thing with the four i letters.
```

**Comment by spencerkimball** [comment]
I think irritating our sizable Turkish user contingent is a reasonable price to pay if we can be case insensitive as a result.
