### ISSUE TITLE
cli/debug: make estimate-gc useful to determine space savings

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#20459]
Action items:

- [ ] introduce `--ttl` parameter
- [ ] make this useful: online version that operates on per-table basis. Naively this will be expensive (full scan), but should be able to use `GCBytesAge` for a cheap lower bound.

From a user:

> How do I know how much disk space I can expect to to get freed? Also, when run for the entire directory with multiple ranges, the command does not print any aggregated stats across ranges, without which it does not seem that useful.

> Related but separate question. How do I interpret the output of the estimate-gc command

> It explicitly states that a hardcoded 24 hour TTL is used. I want to figure out how much wins I would get from reducing the ttl to say 3 hours. How can I do that?

cc @cuongdo another starter project.

Jira issue: CRDB-5929

**Comment by tschottdorf** [comment]
cc @vilterp the relation between space savings and the numbers returned here are similarly not what users expect as the database size tab in the UI. Thus there's likely overlap in the explanations here.

**Comment by tschottdorf** [comment]
cc @garvitjuniwal

**Comment by knz** [comment]
This is a KV issue, not Server.

**Comment by knz** [comment]
probably a storage issue, even.

cc @itsbilal

**Comment by tbg** [comment]
I filed this originally but I would either close this or bury it where nobody looks. I don't think there's a lot of value to be added here.

**Comment by nicktrav** [comment]
> I filed this originally but I would either close this or bury it where nobody looks. I don't think there's a lot of value to be added here.

Given the age of the ticket, the relative inactivity, and the relative importance, I can't see this being prioritized. Rather than keep it in backlog purgatory, I'm going to close it out.

Feel free to re-open if any of that is inaccurate!
