### ISSUE TITLE
release v1.2-alpha.20171211

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#20457]
Candidate SHA: b2ecbf313b38fa5e255eb8d44b74cd88f6a8b3bb
Deployment status: Adriatic and Omega

[Release process checklist](https://github.com/cockroachdb/cockroach/wiki/Release-Process)

Prep date: `2017-12-04`
- [x] [Pick a sha](https://github.com/cockroachdb/cockroach/wiki/Release-Process#pick-sha), fill in `Candidate SHA` above.
- [x] [Deploy to test clusters](https://github.com/cockroachdb/cockroach/wiki/Release-Process#deploy-to-test-clusters)
- [x] Fill in `Deployment status` above
- [x] [Verify node crash reports](https://github.com/cockroachdb/cockroach/wiki/Release-Process#verify-crash-reports)
- Keep an eye on clusters until release date.

Release date: `2017-12-11`
- [x] [Check cluster status](https://github.com/cockroachdb/cockroach/wiki/Release-Process#check-cluster)
- [x] [Tag release](https://github.com/cockroachdb/cockroach/wiki/Release-Process#tag-release)
- [x] [Trigger release build](https://github.com/cockroachdb/cockroach/wiki/Release-Process#trigger-build)
- [x] [Check binaries](https://github.com/cockroachdb/cockroach/wiki/Release-Process#check-binaries)
- [x] Update docs
- [ ] External communications for release
- [x] File issue for next release and assign to release coordinator

**Comment by dianasaur323** [comment]
On cluster status, everything in omega looking good other than the VM issue on omega-4. Unlikely to be cockroachdb related. Adriatic LGTM, other than the latency spikes that we think is hardware related.

**Comment by petermattis** [comment]
Assuming this can be closed.
