### ISSUE TITLE
ui: can't see cluster summary when scrolled down on TS dashboard

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/cockroach#20466]
**BUG REPORT**

![image](https://user-images.githubusercontent.com/894257/33590669-f03c5d64-d94e-11e7-8106-96b23b4cbe6a.png)

2. Please describe the issue you observed:

- What did you do?
I scrolled down to the bottom of the web ui to look at some graphs

- What did you expect to see?
I expected to be able to see an overview of the cluster that would tell me how many nodes were currently running so I could compare that with what I saw with the bottom charts

- What did you see instead?
The sidebar scrolled out of view

----
We should look at other sidebars across the web and see how they keep relevant info visible no matter how far down you've scrolled.

**Comment by dianasaur323** [comment]
We are actually moving the cluster summary out into the overview, so that module won't be there anymore. That being said, the event log should stay in the same place. Adding as a UI bug for now.
