### ISSUE TITLE
sql: Ensure functions return the Datum specified in the return signature

### ISSUE THREAD

**Issue by lego** [cockroachdb/cockroach#20465]
A recent panic was caused by a built-in function returning a datum type that did not match the built-in signature. From brief testing, this discrepancy appears to work in very basic queries when running in the local execution engine, but will cause panics in the distributed execution engine when streaming rows.

See #20464 for the specific panic that came up.

One preventative solution would be to make builtins check datums being returned during logictests, making sure they match the type signature (before casts). cc: @knz as you're probably interested in these testing improvements. An extension of this can also test all other operators, not just built-ins.

Alternatively, this may be a specific problem with the distSQL streamers where the types should be properly handled. I'm not knowledgeable in this, so I'd love some input. While returning an error instead of panic-ing would be nice, implicitly casting does not seem like the way to go.

**Comment by knz** [comment]
yes a check only active in logic tests seems to be the right way to go.
