### ISSUE TITLE
sql: integrate migrations after some number of releases

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#20476]
We're piling up sql migrations to the system tables and making just about everything more complex (testing, migrations handling, etc...).

We should start removing migrations into the base code after a handful of releases. Probably two, forcing you to go through intermediate minor releases. eg: you can't upgrade from 1.0 to 1.2 without going through 1.1 first.

**Comment by vivekmenezes** [comment]
I'm not sure what our strategy is here. Did we decide at anytime that a user had to go through the last minor release for a major release before upgrading to the next major release.

**Comment by bdarnell** [comment]
Our current policy is that you can't skip minor releases (in the semver definition of "minor", i.e. the `y` in `x.y.z`). You can't go from 1.0 to 1.2 without going through 1.1 first.

**Comment by knz** [comment]
cc @benesch for triage

**Comment by mberhault** [comment]
Oh right, this was done in #24868
