### ISSUE TITLE
sql: normalize tuple equalities to conjunctions

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#20473]
We should normalize `(a, b, c) = (x, y, z)` to `(a = x) AND (b = y) AND (c = z)`. Both cases are handled for index selection, but the former requires specialized code (note that it requires more specialized code than inequalities, where only a prefix of the tuples can be preserved).

This would allow us to simplify the index selection code; in addition, we will get immediate benefits from the existing `splitFilter` code.

**Comment by andy-kimball** [comment]
The cost-based optimizer does this, so closing.
