### ISSUE TITLE
sql: old table leases never deleted

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#20485]
If a node dies (ungracefully), the table leases it was holding at the time of its death "leak" and are never deleted from the `system.lease` table. These leaked leases will prevent a schema change on the table. This is very easy to reproduce.

When a node restarts, it should look for any leases in the `system.lease` table and delete any that are expired.

**Comment by tschottdorf** [comment]
Who will remove table leases for nodes that are never coming back?

**Comment by petermattis** [comment]
> Who will remove table leases for nodes that are never coming back?

That's an excellent question.

Looking at this further, it is possible this isn't as big of a problem as I thought as we count only unexpired leases:

```sql
SELECT COUNT(version) FROM system.lease 
  WHERE "descID" = $1 AND version = $2 AND expiration > $3
```

Regardless, we should be cleaning up these old leases somewhere, somehow.
