### ISSUE TITLE
sql/tree: desugar IS/IS NOT to IS {NOT} DISTINCT FROM during parsing

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#20482]
See https://github.com/cockroachdb/cockroach/pull/20346#issuecomment-348344217.

After #20346 is merged we'll be normalizing IS/IS NOT to IS NOT DISTINCT FROM/IS DISTINCT FROM. We could then take a step further and remove the `tree.Is` and `tree.IsNot` operators entirely and desugar `IS/IS NOT` expressions directly to `tree.Is{Not}DistinctFrom`. 

While doing that, we may want to maintain some state so that strings can round trip through our AST. An alternative is to that (as suggested in https://github.com/cockroachdb/cockroach/pull/20346#issuecomment-348488933) would be to format these comparisons using `IS/IS NOT` whenever possible (based on the right-hand operand).

cc. @knz @RaduBerinde

**Comment by nvanbenschoten** [comment]
@yuhit do you want to take this one as well?

**Comment by knz** [comment]
No roundtripping during pretty-printing is necessary.

**Comment by yuhit** [comment]
OK, I will work on this after #20346 is merged.

**Comment by yuhit** [comment]
@nvanbenschoten We will add many codes witch not easy to read to maintain the state, is it necessary?
If  format possible comparisons using IS/IS NOT, means we still need tree.Is/tree.IsNot?

**Comment by RaduBerinde** [comment]
@yuhit I would keep just `tree.Is{Not}DistinctFrom` but tweak its formatting to be "IS {NOT} NULL" when the right operand is `NULL`. I wouldn't add extra state, it's fine if we are given a `IS NOT DISTINCT FROM NULL` and we print it out as the simpler `IS NOT NULL`.

**Comment by nvanbenschoten** [comment]
@knz did you mean "No, roundtripping during pretty-printing is necessary" or "Roundtripping during pretty-printing is not necessary"?

**Comment by RaduBerinde** [comment]
It's not necessary, at least not in general, or we wouldn't have [TestParse2](https://github.com/cockroachdb/cockroach/blob/bd828feaa309578142fe7ad2d89ee1b70adbd52d/pkg/sql/parser/parse_test.go#L930)

**Comment by nvanbenschoten** [comment]
👍
