### ISSUE TITLE
server: unable to compute metrics: lstat [...].sst: no such file or directory

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#20480]
Seen on 6377b6d310fb69f44ec4b18f484de76689870829 while dropping a large table. Likely some code that is computing the disk space is doing something that's not atomic with RocksDB removing some files out from under it.

```
W171205 16:56:20.502027 126 server/node.go:737  [n1] [n1,s1]: unable to compute metrics: lstat /Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/cockroach-data/000777.sst: no such file or directory
```

cc @cuongdo for triage.

**Comment by a-robinson** [comment]
Ah, this was probably broken by https://github.com/cockroachdb/cockroach/pull/20440.
