### ISSUE TITLE
sql: DROP takes ~6min until async deletion begins

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#20488]
@vivekmenezes pointed me in the general vicinity of this code:

```go
func (s *SchemaChangeManager) Start(stopper *stop.Stopper) {
	stopper.RunWorker(s.ambientCtx.AnnotateCtx(context.Background()), func(ctx context.Context) {
		descKeyPrefix := keys.MakeTablePrefix(uint32(sqlbase.DescriptorTable.ID))
		gossipUpdateC := s.gossip.RegisterSystemConfigChannel()
		timer := &time.Timer{}
		delay := 360 * time.Second
		if s.testingKnobs.AsyncExecQuickly {
			delay = 20 * time.Millisecond
		}
```

I'm not clear why that 360 second delay is introduced. Once a `DROP` is issued, the user expects data to be cleared out immediately. (and so did I, and it was confusing that nothing would happen).

**Comment by jordanlewis** [comment]
I think this delay is only for the async path, which gets entered when there are other active schema changers on that table. In normal operation, running `DROP foo` will take the synchronous path and not have a delay at all.

**Comment by tschottdorf** [comment]
No, there's definitely a delay. @vivekmenezes explained this to me saying that we use the async path for the drop. Additionally, there's a six minute delay introduced when the async handler picks it up that I don't understand.

**Comment by vivekmenezes** [comment]
The async path always takes 6 minutes to allow the sync path to run the schema change. This was an arbitrary decision and we could easily make this say 10 seconds I suppose.
