### ISSUE TITLE
ui: "connection lost" alert is too pessimistic

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#20499]
Using our UI on a real cluster is currently scary. Warning pop up all the time about nodes being down or unreachable only to quickly disappear. The most concrete instance of this is the red "Connection to CockroachDB node lost" alert that seems to appear whenever I navigate back to an Admin UI tab. The live nodes indicator in the summary pane has a similar issue.

From a UX perspective, this isn't great. Anyone not familiar with Cockroach is going to think that something is seriously wrong with their Cluster when they see these. We should be a lot more careful about showing warnings, waiting until we're sure that a node is unreachable or down before alerting the user. In practice, this might mean trying to contact the UI server more than once before declaring failure for certain operations.

I've discussed this with @BramGruneir a few times but I figured it should live in an issue.

**Comment by couchand** [comment]
Note that #17840 covers some of the concerns about the suspect nodes.

My suggestion is that we change the criteria for the connection lost warning.  Currently we're issuing requests to the server every 2 seconds just for the purpose of checking the connection.  We shouldn't really need to do that - if there's a network issue we'll notice it on any other (substantive) request anyway.  Adding in retry logic is a possibility (though I'd hesitate to do that in the first pass), and softening the alert as suggested in #20510 can make the experience less stressful.
