### ISSUE TITLE
jepsen: Failure logs not collected

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#20496]
Something changed recently (in the last 2 weeks) and the log tarballs that used to appear in the artifacts tab of teamcity are no longer appearing for the nightly jepsen test runs.

**Comment by jordanlewis** [comment]
It looks like artifacts are still being uploaded to TC from the artifacts directory. That seems to imply that whatever used to collect the logs tarball from the remote cluster is no longer getting invoked.

I think this stanza from `teamcity-jepsen-run-one` is what is supposed to do that:

```
else
    progress "Test failed: exit code $?. Grabbing artifacts from controller..."
    exitcode=1

    # Show the last few lines from the Jepsen run into the build log.
    ssh "${SSH_OPTIONS[@]}" "ubuntu@${controller}" "tail -n 100 jepsen/cockroachdb/invoke.log" >&2 || echo "Failed to extract the last lines from invoke.log." >&2

    progress Creating archive from controller output
    # Now grab all the artifacts.
    # -h causes tar to follow symlinks; needed by the `latest` symlink.
    ssh "${SSH_OPTIONS[@]}" "ubuntu@${controller}" "tar -chj --ignore-failed-read -f- jepsen/cockroachdb/store/latest jepsen/cockroachdb/invoke.log" >"${artifacts_dir}"/failure-logs.tbz || echo "Failed to copy the files." >&2

    progress Resetting latest run for next test
    # Reset the link for the next test run.
    ssh "${SSH_OPTIONS[@]}" "ubuntu@${controller}" "rm -f jepsen/cockroachdb/store/latest" || echo "Failed to remove the latest alias." >&2

    tc Failed "$testName"
fi
```

Did the name `failure-logs.tbz` perhaps change in a Jepsen version upgrade?

**Comment by bdarnell** [comment]
This may have been a transient issue - more recent failures do have logs. (and failure-logs.tbz is created by this snippet, not by jepsen)

**Comment by jordanlewis** [comment]
>  (and failure-logs.tbz is created by this snippet, not by jepsen)

Oh, yeah. Oops.

**Comment by bdarnell** [comment]
Closing unless this happens again.
