### ISSUE TITLE
ui: showing multiple entries of the same node

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#20509]
How is this possible? 

![image](https://user-images.githubusercontent.com/5768024/33632570-087d0170-d9dc-11e7-984d-61f310a00f34.png)

**Comment by a-robinson** [comment]
Discussed in person - they have different node IDs, so they aren't the same node. It was different in this case, but for future reference this is typically because you stopped the node and restarted it without its old data directory.
