### ISSUE TITLE
distsql/ui: Confusion over Active Flows for Distributed SQL Queries graph

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#20501]
In a 3 node cluster, I started a distributed CSV IMPORT command on alex-import-0001. In the admin UI, I see 1 "Active Distributed SQL Query", which makes sense given the import, but I only see an "Active Flow" on alex-import-0002 and alex-import-0003, none on alex-import-0001 even though it's the gateway node / coordinator.

<img width="919" alt="screen shot 2017-12-05 at 3 23 38 pm" src="https://user-images.githubusercontent.com/7085343/33629312-8e86ad58-d9d1-11e7-9d6c-24fad26e1105.png">

It seems fishy that there isn't an active flow registered on the coordinator, but @mjibson and I aren't familiar enough with distsql to be sure what to make of this. @asubiotto thought it might be a measurement error, but wasn't sure.

[This call](https://github.com/cockroachdb/cockroach/blob/28d51086b4e9ba8becd465724412b801ff8480e9/pkg/sql/distsqlrun/server.go#L346) to `flow.Start` without a corresponding call to `metrics.FlowStart` does seem like it might be a bug, but cc @andreimatei as someone who knows much more about this than me.

**Comment by RaduBerinde** [comment]
We're missing a FlowStart/FlowStop in `ServerImpl.RunSyncFlow`.

**Comment by a-robinson** [comment]
Thanks, that's what it looked like. I'll send a fix.
