### ISSUE TITLE
add test for #2039 (reverse scan bug)

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#2051]

**Comment by tschottdorf** [comment]
@thundercw if you happen to be up for taking this over, let me know. I certainly wouldn't mind.

**Comment by thundercw** [comment]
OK，I will take it.

**Comment by tschottdorf** [comment]
Thanks chengwei. Appreciate it.

**Comment by tschottdorf** [comment]
@thundercw I just invited you to the Developers team. Once you accept you should be able to assign yourself.

**Comment by thundercw** [comment]
@tschottdorf  The test sample has been pulled . Is it the test sample that you expect?  PTAL.

**Comment by thundercw** [comment]
#2066 was merged.
