### ISSUE TITLE
cli/sql: shell displays BYTEA differently than psql

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#20525]
This leads to lots of confusion, particularly when it comes to converting between string and bytes, which can already be unintuitive. I'm not sure how difficult this would be to fix given our dependence on lib/pq.

```
$ cockroach sql --insecure
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.
#
# Client version: CockroachDB CCL v1.2-alpha.20171204-245-gaebbf4b (darwin amd64, built 2017/12/06 17:29:17, go1.9)
# Server version: CockroachDB CCL v1.2-alpha.20171204-244-g46415a8-dirty (darwin amd64, built 2017/12/05 21:28:57, go1.9)
# Cluster ID: e58fe3e2-c0b0-49b8-b1e0-f511ed033207
#
# Enter \? for a brief introduction.
#
root@:26257/> select 'hi'::bytea;
+-------------+
| 'hi'::BYTEA |
+-------------+
| hi          |
+-------------+
(1 row)

Time: 782.765µs
```
```
$ psql --port=26257 host=localhost
psql (10.1, server 9.5.0)
Type "help" for help.

justin=> select 'hi'::bytea;
 'hi'::BYTEA
-------------
 \x6869
(1 row)
```

I think we should match Postgres here and format `BYTES`/`BYTEA` in the `\x<hex>` form in the CLI.

cc @benesch, @cockroachdb/sql-ui, @cockroachdb/cli

**Comment by mjibson** [comment]
This may not be a lib/pq problem. Could just be cockroach sql. Here's a cockroach cli client connected to postgres:

```
$ ./cockroach sql --port 5432 --insecure --user postgres --unsafe-updates
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.
#
unable to retrieve the server's version
#
# Enter \? for a brief introduction.
#
error retrieving the transaction status: pq: syntax error at or near "STATUS"
error retrieving the database name: pq: unrecognized configuration parameter "database"
postgres@:5432 ?> select 'hi'::bytea;
+-------+
| bytea |
+-------+
| hi    |
+-------+
(1 row)
```

**Comment by knz** [comment]
`cockroach sql` connecting to pg still uses lib/pq, does it not?

**Comment by knz** [comment]
Anyway perhaps we can still do something about that.

@justinj mind sharing with us the expected behavior?

**Comment by knz** [comment]
Investigated this further: the problem is that `lib/pq` interprets the bytes received from the server to reverse-engineer a go `[]byte` slice. In contrast `psql` prints out what is received from the server as-is, subject to the setting of `bytea_output`.

It would not be very user-friendly to decide an arbitrary representation client-side when `bytea_output` is actually customizable -- it would give the wrong impression that `bytea_output` has no effect. I'm still thinking of a solution here.
