### ISSUE TITLE
sql: RowFetcher does not detect unknown FamilyID or ColumnIDs

### ISSUE THREAD

**Issue by lgo** [cockroachdb/cockroach#20538]
The RowFetcher did not detect a few errors that I would have expected it to. In particular:
- Unknown FamilyIDs
- Unknown ColumnIDs in the primary index

These issues are simply ignored, whereas we may want to log them or return an error. This is from https://github.com/cockroachdb/cockroach/pull/19961#issuecomment-347275797. Now, I could be missing something here in my testing, but having someone chime in about whether or not this should be the case would be helpful. You can find the tests attempting to produce errors [here](https://github.com/lego/cockroach/blob/094a05c7bd7c6d0ea15724dfe11b2ccd366e130d/pkg/sql/scrub_test.go#L818-L1027).

cc: @vivekmenezes for triage.

**Comment by vivekmenezes** [comment]
If we print an error or take any action we should also check that that the unknown familyID or ColumnID is not one from the Mutations lists. The table can be in the middle of a schema change.
