### ISSUE TITLE
sql: audit pg_catalog tables for missing columns

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#20549]
We were missing two columns (`rolreplication` and `rolbypassrls`) from the `pg_catalog.pg_roles`.
We should audit the`pg_catalog` tables against current and older versions of postgresql and make sure we populate as much as possible.

I mention older because some columns get dropped (eg: postgres 9.5 dropped the `rolcatupdate` column from `pg_roles`).

**Comment by vivekmenezes** [comment]
unassigning for now until we can find a good use case

**Comment by mberhault** [comment]
We keep having to add columns or tables one by one to support various orms. We should just go through the list once and add as many as we can.

**Comment by jordanlewis** [comment]
No need to keep this open, though the sentiment is appreciated.
