### ISSUE TITLE
 '_%' doesn't match strings like 'ab' in "like expression"

### ISSUE THREAD

**Issue by xu-hao** [cockroachdb/cockroach#20556]
Hello,

'_%' doesn't match strings like 'ab' in "like expression", which seems to be different from postgres. 

Thanks. 

cockroachdb (1.1.3):
```
root@:26257/> SELECT 'ab' LIKE '_%';
+----------------+
| 'ab' LIKE '_%' |
+----------------+
| false          |
+----------------+
```

postgres (9.5.10):
```
Type "help" for help.

postgres=# select 'ab' like '_%';
 ?column? 
----------
 t
```

**Comment by dianasaur323** [comment]
thanks for the bug report @xu-hao, assigning to @awoods187 for triage
