### ISSUE TITLE
distsql: audit passing ProducerMetadata by value

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#20552]
Every call to `RowSource.Next()` is currently returning a 64-byte `ProducerMetadata`, but this struct is almost always empty. Similarly, `RowReceiver.Push()` takes a `ProducerMetadata` argument but it is almost always empty. Lastly, `RowChannelMsg` embeds a `ProducerMetadata` bloating the size of channels and causing additional unnecessary copying of this empty 64-bytes.

We should probably be using `*ProducerMetadata` everywhere and allocating it on the heap in the relatively few places it is non-zero. This is something of a micro-optimization, and speculative because I haven't done any profiling, but worth investigating given that `RowSource.Next()` and `RowReceiver.Push()` are at the core of distsql processing.

Cc @RaduBerinde

**Comment by petermattis** [comment]
> Do we ever actually do that? A quick check of the code reveals no.

Ah, found an instance in `orderedSynchronizer.consumeMetadata`. It looks like we continue to call `Next` in order to get all of the metadata. Seems like that could be accomplished by an explicit `Metadata` method. Perhaps something like:

```
type RowSource interface {
  Types() []sqlbase.ColumnType
  Next(ctx context.Context) sqlbase.EncRowDatum
  Close(ctx context.Context) ProducerMetadata
}
```

**Comment by petermattis** [comment]
And `RowReceiver` would be modified to look like:

```
type RowReceiver interface {
  Push(row sqlbase.EncRowDatum) ConsumerStatus
  Close(meta ProducerMetadata)
}
```

**Comment by RaduBerinde** [comment]
We normally drain and forward metadata in error cases, see `DrainAndClose`. All processors forward metadata received at any time (this might not be obvious, it might be hidden behind a `NoMetadataRowSource`). I don't know if we're using metadata during queries right now, but it is a mechanism that might be valuable; e.g. we may want to push stats through periodically while a long query is running.

CC @andreimatei who designed the metadata parts of the API.

**Comment by petermattis** [comment]
Ok, I see that metadata forwarding both in `NoMetadataRowSource` and in specific processors (e.g. `hashJoiner.receiveRow`). Let me think about this some more. @andreimatei do we actually use that metadata while the query is being processed? Part of my concern here is an efficiency one, and part is confusion on what the semantics of `Next()` currently are.

**Comment by andreimatei** [comment]
> do we actually use that metadata while the query is being processed?

You're asking if metadata is ever sent inline with rows and whether that's useful? I don't think that we ever do, although we should be sending tracing data early as Radu was saying. And I'm sure there will be more cases in the future when producers will want to signal things to consumers...
And there's got to be a reason why the comments on `Next()` say that rows can be returned after an error, albeit that's probably not important for consumers - see below.

> Part of my concern here is an efficiency one, and part is confusion on what the semantics of Next() currently are.

What bothers you about the semantics of `Next()`? The fact that rows can come after an error? That was probably a convenience for some implementer - probably it's convenient for someone to just forward whatever it gets from some other source and not deal with draining its sources until the consumer starts draining. In other words, that comment is just saying that it's undefined what rows come after an error; consumers should not rely on them and they should call `ConsumerDone()`.

**Comment by petermattis** [comment]
> You're asking if metadata is ever sent inline with rows and whether that's useful? I don't think that we ever do, although we should be sending tracing data early as Radu was saying. 

Do you have a vision for how you would send tracing data early? 

> What bothers you about the semantics of Next()? The fact that rows can come after an error? That was probably a convenience for some implementer - probably it's convenient for someone to just forward whatever it gets from some other source and not deal with draining its sources until the consumer starts draining. In other words, that comment is just saying that it's undefined what rows come after an error; consumers should not rely on them and they should call ConsumerDone().

I would expect an error to indicate we won't receive any more rows and the source should fail-stop. I suppose the challenge is for something like `MultiplexedRowChannel` where you want to keep sending metadata for all of the inputs even though 1 of the inputs encountered an error. 

Ok, I'm coming to a much better understanding of the current design. Let me retract my proposal for `RowSource` above and consider another way to break things.

**Comment by arjunravinarayan** [comment]
@petermattis do you have an updated proposal?

**Comment by petermattis** [comment]
> do you have an updated proposal?

Nope. Right now I'm leaning towards making no changes to the `RowSource` API.

**Comment by petermattis** [comment]
> Right now I'm leaning towards making no changes to the RowSource API.

I take that back. I'm still planning to do the proposal in the original message: pass `*ProducerMetadata` everywhere instead of `ProducerMetadata`. This is semantically the same, though it should be a small performance win.
