### ISSUE TITLE
distsql: investigate modeling outbox directly as a RowReceiver

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#20568]
Related to #20553 and #20550.

`outbox` currently embeds a `RowChannel` for receiving rows and has a dedicated goroutine for gathering rows from the `RowChannel`, packaging them into an RPC and sending them to a gRPC stream. It looks feasible to remove the `RowChannel` and to have `outbox` implement `RowReceiver.Push()`. If/when #20555 is implemented, we could have `outbox.Push` package the RPC and send to the gRPC directly. In the near term, we'd still need a dedicated goroutine to loop picking up buffered rows and sending them, though I think this would be somewhat more efficient in that it could pick up batches of buffered rows instead of gathering them one at a time from `RowChannel.Next()`.

**Comment by RaduBerinde** [comment]
The thought of the design was that we want (some amount of) computation to happen while we're connecting to another node. If we remove the channel, we will block on the first RPC call. Perhaps this is not important if we buffer enough before the first call.

**Comment by petermattis** [comment]
Yes, upstream processing would block while connecting to the other node, but that doesn't seem too problematic. The current approach uses the `RowChannel` as the buffer. Once the `RowChannel` fills up, upstream will block calling `RowChannel.Push()` until the RPC stream is established.

**Comment by arjunravinarayan** [comment]
It's hard to say what the cost of blocking upstream processing on startup is without some benchmarks. I'm tempted to say this is lower priority than the the performance issues we're tackling for 2.0 and we should circle back to this later on in the cycle.

**Comment by jordanlewis** [comment]
No longer relevant since we introduced vectorized.
