### ISSUE TITLE
sql: printable characters in string datums are unnecessarily escaped

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#20562]
```
> create table test (a string collate de primary key);
CREATE TABLE

Time: 3.724452ms

root@:26257/q> insert into test values ('ü' COLLATE de);
INSERT 1

Time: 3.059665ms

root@:26257/q> insert into test values ('ü' COLLATE de);
pq: duplicate key value (a)=(e'\u00FC' COLLATE de) violates unique constraint "primary"
```

Seems like we should be getting a literal `'ü'` in the error message.

@justinj can you triage?

**Comment by knz** [comment]
Actually it's the pretty-printing of any string:

```
root@127.0.0.1:38291/defaultdb> show syntax 'insert into t(t) values (''ü'');';
  field |               message
+-------+-------------------------------------+
  sql   | INSERT INTO t(t) VALUES (e'\u00FC')
(1 row)
```

Really just an artifact of how `EncodeSQLStringWithFlags` is implemented.

**Comment by knz** [comment]
I think from a UX perspective I am very a-OK with the value proposal "all error messages and formatted SQL only use ASCII characters" which seems to be what we are doing right now.

**Comment by benesch** [comment]
Yeah, I am too. I’m trying to remember if there was a deeper problem when I
filed this issue, because otherwise it doesn’t really seem like an issue.
Perhaps @justinj knows? Maybe pgcompat?

Anyway, seems like we could just close this one out.
