### ISSUE TITLE
cli: machine/network qualification tool

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#20579]
It would be useful to have a tool that could do some basic diagnostics on your machine to determine if there's something wrong with it or whether it will perform particularly poorly. @arjunravinarayan has been considering this for a while now, and unintuitive disk behavior has come up multiple times in cloud environments. The thought is that it would test out disk and network performance as well as just report the available CPU and memory on the machine, printing out some sort of summary indicating how it performed and if there are any red flags.

@robert-s-lee thinks that this would be useful for customers to run both before they set up their cluster as well as once their cluster is in place if they run into performance problems. He also suggested giving an estimate of how many operations per second a given cluster could do, but that's a bit more involved.

Prior art: https://github.com/cockroachdb/cockroach/pull/19618, https://github.com/cockroachdb/cockroach/pull/20352#issuecomment-348286066, https://www.postgresql.org/docs/current/static/pgtestfsync.html

Tagging as 1.2 on the thought that @arjunravinarayan and/or I can knock this off on a Friday or two given that it's a nicely self-contained task, but no guarantees. If anyone else wants to try this instead, the help would be welcome!

**Comment by arjunravinarayan** [comment]
Additional prior art: cockroachdb/loadgen#107

**Comment by petermattis** [comment]
Perhaps we should integrate something like [pinger](https://github.com/petermattis/pinger) into a `debug` command. Then we could have `debug synctest`, `debug nettest`, etc.

**Comment by dianasaur323** [comment]
I'm going to move this into 2.1, since there is time slotted in to work on something like this then. Unless someone gets to it before then?

**Comment by knz** [comment]
@andreimatei you should track this issue in your master plan
