### ISSUE TITLE
ci: bake npm and related ui dependencies into builder image

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#2058]
Every CI build reinstalls mocha, stylus, tslint, typescript, chai and probably some other items. It should be possible bake these deps into the builder image. See [build/builder.sh init](https://github.com/cockroachdb/cockroach/blob/master/build/builder.sh#L7). The old `deps-docker.sh` script accomplished this for the `cockroachdb/cockroach-dev` image, but I think the technique will have to be modified for `build/builder.sh init`. Or maybe not, I haven't looked in depth.

**Comment by tamird** [comment]
Caching this stuff saved 2 seconds, so this is not worth the trouble. Closing.
