### ISSUE TITLE
build: Cockroach 1.1.3 is failing to build with gcc-7.2 and go-1.9.2.

### ISSUE THREAD

**Issue by williamh** [cockroachdb/cockroach#20596]
Hello,

I am the packager for Cockroach on Gentoo Linux.
I am getting a report from @toralf, one of our users, that Cockroach 1.1.3 is failing to build with gcc 7.2 and go 1.9.2.

Below is the bug report [1] and a link to the build log [2], which is also on the bug report.

Do you have any suggestions as to what may be going on?

Thanks,

William

[1] https://bugs.gentoo.org/show_bug.cgi?id=640428
[2] https://640428.bugs.gentoo.org/attachment.cgi?id=509138

**Comment by mberhault** [comment]
It seems the cmake target for snappy found gtest installed and is trying to use it, but something's going wrong. What exactly, I'm not sure.

We don't include gtest with our source tarball, so cmake must have picked it up from somewhere else. 

Does @toralf have the `CMAKE_MODULE_PATH` env variable set? That would allow cmake (even deep inside our build pipeline) to find an installed version. Other ways are described in https://cmake.org/Wiki/CMake:How_To_Find_Libraries#How_package_finding_works

**Comment by williamh** [comment]
@mberhault Should I unset this variable in the gentoo build script for cockroach?

**Comment by mberhault** [comment]
If it is set, then yes.
Ultimately it would be good to find the real issue, it could be as simple as us using an old version of snappy. I'll try and reproduce the problem. Could you let me know which version of gtest is present?

**Comment by williamh** [comment]
I just spoke with him, and it is gtest-1.8.
That would also explain why I can't reproduce it since I do not have gtest installed. :-)

**Comment by mberhault** [comment]
Thanks for the info. Please let us know the status after clearing the env variable.
I'll try on my end to see what's wrong. The fewer build issues, the better.

**Comment by mberhault** [comment]
I've been able to reproduce it by installing `libgtest`. Turns out this does not impact our master branch as we are now building the `snappy` target explicitly.
The 1.1 branch does not provide a target so unittests are built as well. Since we don't run them, there's no point in building them. I'll send a patch for 1.1.4.
