### ISSUE TITLE
sql: RSG needs to be updated to keep track of read-only transaction state

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#20605]
https://teamcity.cockroachdb.com/viewLog.html?buildId=436128&buildTypeId=Cockroach_Nightlies_RandomSyntaxTests&tab=buildLog&_focus=2120

```
panic: pq: cannot execute CREATE DATABASE in a read-only transaction
```

**Comment by mjibson** [comment]
RSG already tries to not start transactions (https://github.com/cockroachdb/cockroach/blob/ca5eaaf0c5775f7976a9305b639c0c2a2bb3ea93/pkg/sql/tests/rsg_test.go#L100), but maybe there's some syntax it doesn't know about.

**Comment by jordanlewis** [comment]
The problem is the `SET SESSION CHARACTERISTICS AS TRANSACTION READ ONLY` statement which changes how statements behave outside of transactions as well.

**Comment by mjibson** [comment]
Seems like this is still happening: https://teamcity.cockroachdb.com/viewLog.html?buildId=444532&buildTypeId=Cockroach_Nightlies_RandomSyntaxTests
