### ISSUE TITLE
generate_series for timestamp types

### ISSUE THREAD

**Issue by derkan** [cockroachdb/cockroach#20608]
Is this a question, feature request, or bug report?

> This is a  feature request

**QUESTION**

Have you checked our documentation at https://cockroachlabs.com/docs/stable/? If you could not find an answer there, please consider asking your question in our community forum at https://forum.cockroachlabs.com/, as it would benefit other members of our community.

Prefer live chat? Message our engineers on our Gitter channel at https://gitter.im/cockroachdb/cockroach.
> Tried but, gitter was inaccessible.

**FEATURE REQUEST**

1. Does an issue already exist addressing this request? If yes, please add a :+1: reaction to the existing issue. If not, move on to step 2.

2. Please describe the feature you are requesting, as well as your proposed use case for this feature.

> `generate_series(start, stop, step)` with `timestamp` or `timestamp with time zone` for `start` and `stop` parameters and for `step` interval. Example: `SELECT generate_series('2017-11-11 00:00:00'::TIMESTAMP, '2017-11-11 03:00:00'::TIMESTAMP, '1 hour');` will produce:
```
'2017-11-11 00:00:00'
'2017-11-11 01:00:00'
'2017-11-11 02:00:00'
'2017-11-11 03:00:00'
```

3. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

> nice-to-have. No feasible workarounds.

**BUG REPORT**

1. Please supply the header (i.e. the first few lines) of your most recent
   log file **for each node in your cluster**. On most unix-based systems
   running with defaults, this boils down to the output of

     grep -F '[config]' cockroach-data/logs/cockroach.log

   When log files are not available, supply the output of `cockroach version`
   and all flags/environment variables passed to `cockroach start` instead.

2. Please describe the issue you observed:

- What did you do?

- What did you expect to see?

- What did you see instead?

**Comment by jordanlewis** [comment]
Thanks for the feature request.

This should be fairly straightforward to add, if anyone's looking for a good first issue.

The file to modify is `pkg/sql/sem/builtins/generator_builtins.go` - a few new overloads must be added to the `generate_series` builtin.

**Comment by justinj** [comment]
Not an ideal workaround, but in the meantime you can do something like:
```
select '2017-11-11 00:00:00'::timestamptz + generate_series(0, 3) * '1 hour'::interval;
```

**Comment by nkprince007** [comment]
Hi, I'm a newcomer to golang and I'd like to work on this issue.

**Comment by lego** [comment]
Hey @nkprince007, currently someone else is working on the issue and there is a pull request already open. It's referenced just above your comment. Sorry!
