### ISSUE TITLE
acceptance: allocator tests are failing

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#20618]
Example failing tests (basically, any allocator test):
https://teamcity.cockroachdb.com/viewLog.html?buildId=437858&tab=buildResultsDiv&buildTypeId=Cockroach_Nightlies_Steady_6Medium
https://teamcity.cockroachdb.com/viewLog.html?buildId=437845&tab=buildResultsDiv&buildTypeId=Cockroach_AllocatorTest3to510g
https://teamcity.cockroachdb.com/viewLog.html?buildId=437844&tab=buildResultsDiv&buildTypeId=Cockroach_AllocatorTest1to310g

The commonality is that the `cockroach.log` file for each failed node has many occurrences of the following messages:

```
I171211 07:21:42.316965 983 gossip/client.go:136  [n?] closing client to uprep-1to3s-pedanticliskov-cockroach-1.eastus.cloudapp.azure.com:26257: stopping outgoing client to node 0 (uprep-1to3s-pedanticliskov-cockroach-1.eastus.cloudapp.azure.com:26257); loopback connection
I171211 07:21:43.318116 995 gossip/client.go:129  [n?] started gossip client to uprep-1to3s-pedanticliskov-cockroach-1.eastus.cloudapp.azure.com:26257
I171211 07:21:43.318686 944 gossip/server.go:219  [n?] received initial cluster-verification connection from {tcp uprep-1to3s-pedanticliskov-cockroach-1:26257}
I171211 07:21:43.319268 995 gossip/client.go:136  [n?] closing client to uprep-1to3s-pedanticliskov-cockroach-1.eastus.cloudapp.azure.com:26257: stopping outgoing client to node 0 (uprep-1to3s-pedanticliskov-cockroach-1.eastus.cloudapp.azure.com:26257); loopback connection
I171211 07:21:44.320949 998 gossip/client.go:129  [n?] started gossip client to uprep-1to3s-pedanticliskov-cockroach-1.eastus.cloudapp.azure.com:26257
I171211 07:21:44.321629 990 gossip/server.go:219  [n?] received initial cluster-verification connection from {tcp uprep-1to3s-pedanticliskov-cockroach-1:26257}
I171211 07:21:44.322235 998 gossip/client.go:136  [n?] closing client to uprep-1to3s-pedanticliskov-cockroach-1.eastus.cloudapp.azure.com:26257: stopping outgoing client to node 0 (uprep-1to3s-pedanticliskov-cockroach-1.eastus.cloudapp.azure.com:26257); loopback connection
```

The timing and symptoms suggest that #20163 is causing this.

For context, these tests download tarred/gzipped copies of stores and puts them on new machines. So, that might be confusing the cluster ID verification mechanism. All of the downloaded store data should have the same cluster ID though.

**Comment by solongordon** [comment]
It's looking like these failures were unrelated to the cluster ID change. The first commit where they fail is b7c50d4f. I'm testing out a fix.
