### ISSUE TITLE
release v2.0-alpha.20171218

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#20616]
Candidate SHA: e23cfcc1f.
Deployment status: stable.

[Release process checklist](https://github.com/cockroachdb/cockroach/wiki/Release-Process)

Prep date: `2017-12-11`
- [x] [Pick a sha](https://github.com/cockroachdb/cockroach/wiki/Release-Process#pick-sha), fill in `Candidate SHA` above.
- [x] [Deploy to test clusters](https://github.com/cockroachdb/cockroach/wiki/Release-Process#deploy-to-test-clusters)
- [x] fill in `Deployment status` above
- [x] [Verify node crash reports](https://github.com/cockroachdb/cockroach/wiki/Release-Process#verify-crash-reports)
- Keep an eye on clusters until release date.

Release date: `2017-12-18`
- [x] [Check cluster status](https://github.com/cockroachdb/cockroach/wiki/Release-Process#check-cluster)
- [x] [Tag release](https://github.com/cockroachdb/cockroach/wiki/Release-Process#tag-release)
- [x] [Trigger release build](https://github.com/cockroachdb/cockroach/wiki/Release-Process#trigger-build)
- [x] [Check binaries](https://github.com/cockroachdb/cockroach/wiki/Release-Process#check-binaries)

- For stable releases only (**stable** means: no dash in the version):
  - [ ] Update the [Homebrew Formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/cockroach.rb)
  - [ ] Update the image tag in our [Orchestrator configurations](https://github.com/cockroachdb/cockroach/wiki/Release-Process#orchestrator-configurations)
  - [ ] Update the version label in our [Red Hat Atomic Docker image](https://github.com/cockroachdb/cockroach/blob/master/build/deploy/rhel/Dockerfile). For major/minor releases, also update the documentation link in the [image's help file](https://github.com/cockroachdb/cockroach/blob/master/build/deploy/rhel/help.1)
  - [ ] Announce version to the [registration cluster](https://github.com/cockroachlabs/production#publishing-a-new-release-version)
  - [ ] Upgrade the registration cluster (reg runs latest stable version)

- [x] Update docs
- [ ] External communications for release
- [ ] File issue for next release and assign to release coordinator

**Comment by jordanlewis** [comment]
Omega and Adriatic appear stable, but all nodes are marked suspect in the admin UI. Not sure what's up with that, but it doesn't seem normal... or does it?

**Comment by bdarnell** [comment]
There are known issues with the "suspect" status (#17840) although I thought the problem had now been fixed unless the client's clock is wrong. As long as the other graphs are OK (e.g. SQL QPS and latency are at expected levels) I think we can ignore the "suspect" state for now.

FWIW, I don't see any "suspect" nodes on either adriatic or omega right now.

**Comment by jordanlewis** [comment]
I should have screenshotted the admin UIs. Both clusters had all nodes marked suspect over the weekend - I don't see any suspect nodes now either.

**Comment by nvanbenschoten** [comment]
Can this issue be closed?

**Comment by jordanlewis** [comment]
Thanks..

**Comment by jordanlewis** [comment]
Oops, sorry for the sarcastic sounding double period typo :)
