### ISSUE TITLE
core: forget a decommissioned node

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#20639]
I can't find an existing issue for this.

Per user request: it would be nice to be able to really forget a node after decommission in cases where the node is truly gone (intentional removal or lost data).

This should either be a separate command or a special flag on decommission for safety.

**Comment by tschottdorf** [comment]
I think this is covered by various items from https://github.com/cockroachdb/cockroach/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+decommissioned

Let's say #19863 #19541 #19863

In short, you don't need a separate command. Just decommission the node in absentia and it should be removed from the UI and various other pages.

**Comment by mberhault** [comment]
I'm not sure that's quite the same. The other issues are about still including decommissioned nodes as if they were dead. Even when that is fixed, they will still show up as decommissioned nodes. The ask here is to forget about them completely: they wouldn't even show up under "Decommissioned"

**Comment by dianasaur323** [comment]
yep, this has been requested from quite a few users.

**Comment by tschottdorf** [comment]
@mberhault https://github.com/cockroachdb/cockroach/issues/15609#issuecomment-321727184

I'll retitle that issue. My general intuition is that we should do "dead + decommissioned = don't show the node anywhere".

**Comment by fat0** [comment]
What happens if a new node comes up with the same IP of a decommissioned node IP? Ideally, we should be able to re-use old IPs that are not used by the cluster any more.

**Comment by a-robinson** [comment]
Reusing IPs should already work. As long as it isn't started up with the old node's data directory, it will be treated as a new node that hasn't been decommissioned. Have you run into any problems doing so?
