### ISSUE TITLE
sql: vacuum

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#20631]
https://www.postgresql.org/docs/9.1/static/sql-vacuum.html

Deleted data in Cockroach sticks around for a TTL period. Sometimes users want to immediately reclaim disk used up by deleted data  and can issue VACUUM to explicitly cleanup most of the deleted data on a table.

**Comment by tschottdorf** [comment]
The grapevine says "people hate vacuum". I think the ongoing work in #19329 plus zone configs sufficiently address this.

**Comment by dianasaur323** [comment]
An alternative grapevine heard about vacuum from a user, and it sounds like maintenance overhead that we can hopefully avoid.
