### ISSUE TITLE
ui: explain table size numbers

### ISSUE THREAD

**Issue by vilterp** [cockroachdb/cockroach#20638]
As seen in #18667, there are many different ways of counting how big a table is (physical, logical, live, etc). We need to pick one and say in the UI clearly (i.e. with a tooltip or text of some kind) what it means.

Note: the `tooltip` values passed to the `SummaryHeadlineStat` component currently are thrown away. (they're insufficient anyway)

**Comment by dianasaur323** [comment]
@vilterp it seems like all three would be useful for different reasons, and there are different use cases associated with each. 
1) Someone wants to know how much disk they need to provision for capacity planning purposes, and to make sure their cluster doesn't run out of disk (physical)
2) Someone wants to know how big their database would be if they exported it, either in a backup / restore or in an import CSV (logical)
3) Someone wants to debug some performance issue, where the live dataset is actually quite different from the entire dataset associated with a table (live)

After mapping these user stories out, it seems like we really only usefully meet the first use case in our current admin UI. It's possible for us to surface 2 in our jobs table, but that seems out of scope for this release. Is it possible that our best approach here is to just go with a physical data size and mark it as such, with a disclaimer that your exported CSV or backup may be a different size? What are your thoughts here?

**Comment by couchand** [comment]
It seems like for capacity planning (1), the size of an individual database isn't all that helpful - mostly you'd be looking at cluster usage in the aggregate.  So it seems like the most common use of the database size (at least in the context of the updates on #20627) is actually the export case (2).

But maybe we can't get away from showing multiple, subtly different metrics here.  That means we have more of a responsibility to be very clear about each of them.

**Comment by dianasaur323** [comment]
Yeah, I think we definitely can't get away with not doing 1, so 1 is definitely required. 2 is an interesting one, and one that users actually do ask about -> how do I know how much space to provision for my backup. I'm wondering if we should go about this in a workflow approach, where we show you a metric depending on what you are trying to do. Maybe the answer is to just get rid of that size number in the database table and move it over to some other page that makes sense eventually. For now, should we just label the metrics correctly with a tool tip and call it a day?

**Comment by dianasaur323** [comment]
Ok, we spoke about this offline, and the consensus was to show both logical and physical table sizes on the database page. woot!

**Comment by dianasaur323** [comment]
@vilterp I think we both had convos with @tschottdorf and decided that what we have right now works fine. In light of that, should we close this out?

**Comment by vilterp** [comment]
Yeah, I'd say so.

**Comment by dianasaur323** [comment]
Yay!
