### ISSUE TITLE
roachtest: combined split+kill chaos

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#20651]
Jepsen found #20629 because it happens to kill a node immediately after creating a table (which triggers a split). This makes it much more likely to hit the right window to trigger this bug. We should try to expose bugs like this more aggressively (in both jepsen and our other chaos testing) by performing manual splits just before killing nodes.

**Comment by danhhz** [comment]
Pretty sure peter is already working on this

**Comment by petermattis** [comment]
Not actively working on this (distracted with other concerns this week and next), but I'd like to. If anyone else has time, feel free to take this on.

**Comment by petermattis** [comment]
@tschottdorf For prioritization with other new roachtests.
