### ISSUE TITLE
sql: system.localities uses a single level of locality

### ISSUE THREAD

**Issue by couchand** [cockroachdb/cockroach#20653]
The initial version of the `system.locality` table (#19652) stores lat/long information according to a single key/value pair of localities, on the assumption that these are globally unique.  If two values on the same key have the same value, but are nested under different parent localities, they will be treated as distinct for most purposes, but they can't both be assigned lat/long data.  For instance, if one node in a cluster is started with `--locality=region=west,datacenter=1` and another with `--locality=region=east,datacenter=1`, the system table doesn't support assigning lat/long at the datacenter level.

There seem to be two potential solutions to this issue: validate the locality flags assigned to nodes in the cluster and fail if there's a collision, or expand the system table to track all ancestor key/value pairs, not just a single level.

In the meantime, we should probably document the limitation.

**Comment by bdarnell** [comment]
Does the allocator make the same assumption that these names are globally unique, or does it look at the entire hierarchy?

**Comment by vilterp** [comment]
### An example of what you can't do

maybe we can put this in the docs cc @Amruta-Ranade

1. Set up locality flags like this:

```
region=us-east-1
  az=a
region=eu-west-1
  az=a
```

2. Try to add locations to both az=a's:
Primary key uniqueness violation, since the primary key is `localityKey, localityValue`.

### What you would do instead:

1. Set up your locality flags the same way:

```
region=us-east-1
  az=a
region=eu-west-1
  az=a
```

2. Add locations at the region level, since az's within a region are effectively in the same place anyway.

**Comment by vilterp** [comment]
True, could also do

```
region=us-east-1
  az=us-east-1a
region=eu-west-1
  az=eu-west-1a
```

**Comment by vilterp** [comment]
@Amruta-Ranade if you've sufficiently documented this limitation, maybe we should close this out or move it to 2.1, since we don't have a plan to address this before 2.0.

**Comment by Amruta-Ranade** [comment]
Moving it to 2.1 (documented as discussed for 2.0)

**Comment by jseldess** [comment]
Added to 2.0 known limitations in https://github.com/cockroachdb/docs/pull/2823.

**Comment by jseldess** [comment]
Closing this. Will open a new issue once this is addressed in 2.1.

**Comment by sploiselle** [comment]
@vilterp @couchand Is this still a known limitation?

**Comment by couchand** [comment]
@sploiselle yep, no change.
