### ISSUE TITLE
sql: support interleaved prefix/subset joins in `InterleavedReaderJoiner`

### ISSUE THREAD

**Issue by richardwu** [cockroachdb/cockroach#20661]
## Outline
As described in [the interleaved table joins RFC](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20171025_interleaved_table_joins.md), there are more general cases of joins between interleaved tables where we can take advantage of the interleaved table locality. 

[Prefix joins](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20171025_interleaved_table_joins.md#3b-prefix-joins) and [subset joins](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20171025_interleaved_table_joins.md#3b-prefix-joins)  are the general cases for join keys used in an interleaved join.

## Implementation details

The RFC describes two approaches for prefix joins:
1. Approach one is identical to the logic of `streamMerger`, where rows from both sides are buffered. The one caveat is `streamMerger` requires a left and right `RowSource interface`. Furthermore, `streamMerger` does not read from both sources concurrently. This means after reading a row in the `InterleavedReaderJoiner`, we have to buffer all of the left rows before `streamMerger` will read from the right source. There is a `RowBuffer struct implements RowSource` that has a non memory-accounted buffer. We'd need to create a new `RowSource` that has a `memRowContainer` to prevent OOMs while buffering the left rows.
2. Approach two may be too complicated for marginal memory footprint improvements, so I'd say approach one that re-uses `streamMerger` is better (`streamMerger` would also take care of subset joins once hybrid merge-hash joins #16580 are implemented).

For subset joins, if approach one is implemented for prefix joins with `streamMerger` AND we implement hybrid merge-hash joins in `streamMerger`, then in theory we can support subset joins.

### Special case: uniqueness on a part of the interleaved prefix

Although currently we require [a match on the full interleaved prefix](https://github.com/cockroachdb/cockroach/blob/f35be206cad350da0260b04a1576f34f6fbba094/pkg/sql/distsql_plan_join.go#L367-L375) in order to stream the joined rows, this is not strictly required. Consider the hierarchy
```
parent                         (pid)
   child                         (pid, cid)
      grandchild             (pid, cid, gcid)
```
Currently if we do
```sql
SELECT * FROM child JOIN grandchild USING (cid)
```
this would default to a merge join. However if we know that `cid` is unique then we can simply stream join `child` and `grandchild` without buffering.

## Why go through these hoops?

Recent performance results in #20586 showed that when given the option, it is much better to do joins locally than hash routing them to a `MergeJoiner`.

Since interleaved tables guarantee locality, we can see some pretty significant improvements.

For example "an average case" (case 3 in #20586) sees a 50% throughput increase for interleaved tables vs regular tables and a 90% throughput increase for `InterleavedReaderJoiner` vs two `TableReaders` hash routing to `MergeJoiner` (multiplied by the # of data nodes). 

I would reckon eliminating the pseudo-randomness of hash routing to `MergeJoiner`s will yield performance improvement somewhere in between the two relative improvements above for interleaved tables in the prefix and subset cases.

cc: @RaduBerinde @arjunravinarayan

**Comment by yuzefovich** [comment]
The interleaved reader joiner has been removed on master, and we intend to move away from the concept of interleaving altogether, so closing.
