### ISSUE TITLE
*: prevent 4-byte chars in test names, or fix TeamCity

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#20681]
Our TeamCity server stores data in a MySQL database whose charset is `utf8`. For some ungodly reason, MySQL's `utf8` can't store 4-byte chars, like emoji, so we need to migrate to a database that uses the `utf8mb4` charset instead.

Alternatively, we could write a lint that lists all test names and verifies that no 4-byte chars are used.

Jira issue: CRDB-5917

**Comment by nnovoice** [comment]
Is this up for grabs? I would like to take a look. Thank you.

**Comment by petermattis** [comment]
Yes, this is up for grabs. Probably worthwhile sketching out what you're planning to do here. The irritating part as I understand it, is that test names are sometimes programmatically generated for subtests. Grep'ing for `func Test' or using `go test -list .` won't find these subtest names.

**Comment by nnovoice** [comment]
Thank you @petermattis! I will sketch out and share a plan. Thank you for the heads up about the test names being generated programmatically.
