### ISSUE TITLE
clusterviz: release acceptance criteria

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#20685]
- I want a high-level overview of my cluster so that I know whether or not to take further action
  - ~[ ] Inter-node network traffic and latency between aggregated localities (likely out of scope)~ (pushed to 2.1)
-  I want to identify and preempt any scenarios (including changing configurations) that might cause downtime, service issues, or otherwise negatively impact cluster health
   - ~[ ] Observe network traffic between nodes to see if there are networking issues (likely out of scope)~ (pushed to 2.1)
   - [x] Observe if a node went down so that the user knows to bring it back up (also includes decommissioned and new nodes) 

- Usability
   - [ ] Onboarding
      - User Stories:
         - [ ] Enterprise license with no localities
            - [ ] I want to add localities to my nodes so that I can see them aggregated
            - ~[ ] I want to know whether or not my license is about to expire~ (pushed to later)
         - [ ] Enterprise license with localities
            - [ ] I want to add lat / long to my localities so that I can view them on a geographical map
            - [ ] I want to know whether or not I've set up my lat / long correctly and if I've missed any nodes
            - [ ] I want to know what my locality and lat/long settings are so that I can check if they are correct
         - [ ] OSS only
            - [ ] I want to know which features are enterprise features, even if I don't have access
            - [ ] I want to know how to get access to enterprise features
            - ~[ ] I want the admin UI to notify me if my license has changed~ (pushed to later)
         - [x] Edge cases
            - ~[ ] I want to know how to change my locality names so that they fit nicely on the screen~ (pushed to later)
            - [x] I want to be able to differentiate between aggregated and non-aggregated nodes, in case not all the nodes I've set up need localities
            - [x] I want to group my nodes on the geographical map into localities so that they don't clog up the map
            - ~[ ] I want to get an error message if I set a non-unique locality~ (pushed to later)
   - [x] Confirm that Segment is working
   - [x] CCL https://github.com/cockroachdb/cockroach/issues/19759

**Comment by couchand** [comment]
@vilterp It looks like the remaining items are related to the onboarding work you're doing.  I think they're sufficiently tracked by #23516 and #23871 so I'm closing this out.

**Comment by vilterp** [comment]
Sounds good.

The other unchecked item basically amounts to upselling people to enterprise from OSS, which I think we've decided not to do.
