### ISSUE TITLE
sql: allow GROUP BY of ungrouped non-aggregate columns if the GROUP BY contains the primary key

### ISSUE THREAD

**Issue by lgo** [cockroachdb/cockroach#20729]
This was introduced in postgres 9.1. See the [GROUP BY](https://www.postgresql.org/docs/10/static/sql-select.html#SQL-GROUPBY) clause documentation. In particular, this exerpt:
> When GROUP BY is present, or any aggregate functions are present, it is not valid for the SELECT list expressions to refer to ungrouped columns except within aggregate functions or **when the ungrouped column is functionally dependent on the grouped columns**, since there would otherwise be more than one possible value to return for an ungrouped column. **A functional dependency exists if the grouped columns (or a subset thereof) are the primary key of the table containing the ungrouped column.**

If a group by clause contains all of the primary key columns for a table then non-aggregated, ungrouped columns from that table can also appear in the group by clause. Note that concern should be taken if considering a group-by containing multiple tables.

For example, we can do the following in postgres:

```sql
CREATE TABLE t (id INT PRIMARY KEY, data INT, fkey INT);
CREATE TABLE other (id INT, v INT);
INSERT INTO t VALUES (1, 314, 1);
INSERT INTO t VALUES (2, 217, 2);
INSERT INTO other VALUES (1, 2);
INSERT INTO other VALUES (1, 3);

SELECT t.data, array_agg(other.v) FROM t LEFT JOIN other ON t.fkey = other.id GROUP BY t.id;
 data | array_agg
------+-----------
  314 | {2,3,2,3}
  217 | {NULL}
```

Whereas in CockroachDB, you get:

```
pq: column "data" must appear in the GROUP BY clause or be used in an aggregate function
```

(this was discovered in the 💎on🛤  test suite)

**Comment by jordanlewis** [comment]
This doesn't strike me as a wildly important compatibility fix, but I could be wrong. I wouldn't guess that most people understand that this feature is available. The normal rules for `GROUP BY` are pretty straightforward - all columns must exist either in the `GROUP BY` clause or be used in an aggregate.

**Comment by petermattis** [comment]
Is the primary key the only functional dependency that is check for? A unique index where all of the columns are not-NULL would also act as a key. And functional dependencies can arise if the input relation to the group-by is a join. Just wondering how for Postgres took this.

**Comment by lego** [comment]
I just tested unique indexes and joined equivalent columns. It seems that only the primary key is considered a functional dependency, as the documentation indicates.

**Comment by jordanlewis** [comment]
@RaduBerinde didn't you just fix this? Maybe we had 2 issues open for it.

**Comment by RaduBerinde** [comment]
Yeah, dup of #26709.
