### ISSUE TITLE
ui: account for all key ranges in database overview

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#20738]
We show the approximate on-disk sizes of all tables in the UI, but we don't at all expose other parts of the keyspace that can be sizeable, the prime example being timeseries data.

We should add (at least) an entry on the "databases" page that approximates the size for all non-table data. It likely makes sense to break out time series as their own though, since that's the only large space eater I know of. Others are the liveness ranges, etc, but I'd be more comfortable bundling them up under "other internal disk usage" because they'll be distracting 99.99% of the time and if need be, we can drill into their MVCCStats and draw conclusions from that.

I'd be comfortable adding these entries into the `system` database even though they don't correspond to actual tables, but the various alternatives should be weighted. We can also introduce placeholder tables to make the duality better, and especially move the special-casing away from the ui into the server that handles the respective `TableStatsRequest`. (That is, `TableStats` would be tasked with translating these placeholder table descriptors into their corresponding internal spans and then things should "just work").

I think the technical implementation is straightforward and not too onerous.

@dianasaur323 for triage - I think this'll bite us at some point. Folks are always confused by time series/disk usage and it'd be good if we accounted for 100% of the data in the cluster.

**Comment by dianasaur323** [comment]
hmm.. i'm honestly not too sure if anyone has time to do this. I definitely think we won't have time to do it on the admin UI side, so we would have to get someone else to take a look. @vivekmenezes is there anyone who might have time to do this in the 2.0 timeframe? Otherwise we might have to punt until the next release.

**Comment by vilterp** [comment]
Done for time series data (thx @mrtracy); next step is to decide how to label the other stuff (liveness, meta ranges, etc). Like Tobi said, maybe "internal" or "system".

**Comment by petermattis** [comment]
Another huge hole on the database overview page is that in-progress restores do not show up (at least, I think they don't show up, I'll do another restore to verify). This is problematic for large restores where a table can have thousands or 10s of thousands of ranges that don't show up on the Databases page.

**Comment by vilterp** [comment]
According to #21087 the database shows up, but none of its tables or ranges.

**Comment by vilterp** [comment]
@celiala is now working on #24767; closing this as a dup of that
