### ISSUE TITLE
storage: refactor rebalanceCandidates selection to do less comparing across localities

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#20751]
When deciding whether or not to rebalance from one store to another, our comparisons of which stores are too full or too empty don't do a great job of considering localities and diversity. We construct a single list of all non-dead stores in the cluster, then compute various averages based on those stores to use in picking rebalance candidates.

However, this can be very unfair if the number of nodes in each locality is very different. For example, if localities A and B have 2 nodes each and locality C has 4 nodes, we'd expect the nodes in locality C to be half as full as the nodes in A and B. It's inaccurate to directly compare them, and can lead to situations where we're too eager to rebalance between nodes in C and not very willing to rebalance between nodes within A or B.

#20241 is a great reproduction of this. I've been fixing the replica thrashing in that by extending #18364 and will send out that change soon, but it still leaves the issue of us being less willing to rebalance between nodes in the smaller localities. Thinking about the problem has made clear that the current structure of the code isn't really aligned with the problem when localities are in play. Rather than one large `StoreList` containing all the stores, I think we want something like separate `StoreList`s per locality (or set of "equivalent" localities) so that we don't label all stores in A and B as overfull and all stores in C as underfull.

@cuongdo - this could make for a good introduction to the allocator code for someone - it should take on the order of a week or so. It'd be really nice to get into 2.0 given the focus on global deployments, but isn't absolutely necessary.

**Comment by bdarnell** [comment]
> For example, if localities A and B have 2 nodes each and locality C has 4 nodes, we'd expect the nodes in locality C to be half as full as the nodes in A and B.

On the other hand, sometimes we do want to compare across localities. if there are four localities, and A and B have 2 nodes each and C and D have 4, we'd want things to adjust so that each node is equally full even across localities (in the absence of other constraints).

**Comment by a6802739** [comment]
@a-robinson , could I have a try?

**Comment by a-robinson** [comment]
> On the other hand, sometimes we do want to compare across localities. if there are four localities, and A and B have 2 nodes each and C and D have 4, we'd want things to adjust so that each node is equally full even across localities (in the absence of other constraints).

Yeah, that's where something like the sets of "equivalent" localities that I mentioned would have to come into play. For example, if a range had replicas in localities A, B, and C, and didn't in D, we might use equivalence classes {A, D}, {B, D}, {C, D} when deciding whether a rebalance would be beneficial.

> @a-robinson , could I have a try?

Of course! If you want to talk more about the problem at all, just let me know.

**Comment by a6802739** [comment]
@a-robinson  if we use `separate StoreLists per locality`, how could we know the store within each locality is overfull or underfull?

And what do you mean `set of "equivalent" localities`?

Thanks!

**Comment by a-robinson** [comment]
@a6802739 I'm actually working on this currently as part of https://github.com/cockroachdb/cockroach/issues/19985. I'll send something out for it this week.
