### ISSUE TITLE
sql: some filters not pushed down through left joins

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#20765]
Hibernate emits `LEFT JOIN` queries when loading entities that have relationships with foreign entities, both one-to-one and one-to-many.

CockroachDB doesn't seem to correctly plan these queries: the joined table is searched with a full table scan instead of the available index.

Further, if the filter is specified on the column of the joined table instead of the first table, a full table scan is used on both sides of the `JOIN`.

The following log should summarize the issue.

```
root@:26257/test> create table a (a int primary key);
CREATE TABLE
root@:26257/test> create table b (a int primary key);
CREATE TABLE
root@:26257/test> explain select * from a left join b using(a) where a=3;
+-------+--------+----------------+-------------+
| Level |  Type  |     Field      | Description |
+-------+--------+----------------+-------------+
|     0 | render |                |             |
|     1 | join   |                |             |
|     1 |        | type           | left outer  |
|     1 |        | equality       | (a) = (a)   |
|     1 |        | mergeJoinOrder | +"(a=a)"    |
|     2 | scan   |                |             |
|     2 |        | table          | a@primary   |
|     2 |        | spans          | /3-/3/#     |
|     2 | scan   |                |             |
|     2 |        | table          | b@primary   |
|     2 |        | spans          | ALL         |
+-------+--------+----------------+-------------+
(11 rows)

root@:26257/test> explain select * from a left join b on a.a=b.a where b.a=3;
+-------+--------+----------------+-------------+
| Level |  Type  |     Field      | Description |
+-------+--------+----------------+-------------+
|     0 | filter |                |             |
|     1 | join   |                |             |
|     1 |        | type           | left outer  |
|     1 |        | equality       | (a) = (a)   |
|     1 |        | mergeJoinOrder | +"(a=a)"    |
|     2 | scan   |                |             |
|     2 |        | table          | a@primary   |
|     2 |        | spans          | ALL         |
|     2 | scan   |                |             |
|     2 |        | table          | b@primary   |
|     2 |        | spans          | ALL         |
+-------+--------+----------------+-------------+
(11 rows)

Time: 1.694ms
```

Assigning @RaduBerinde for triage.

**Comment by jordanlewis** [comment]
Note that this bug isn't present with inner joins.

**Comment by RaduBerinde** [comment]
Added @knz. These require a bit more sophistication in filter pushdown.

**Comment by petermattis** [comment]
@RaduBerinde When you push a filter to the right side of a left join, would we transform it into `col IS NULL OR <filter>`? That seems relatively straightforward, so I'm probably missing something. 

As I think about this more, this isn't so much a difficulty with filter push-down, as it is with filter inference. When we're inferring filters for a left join, column equivalency generates a different predicate for the right side than it does for the left.

**Comment by RaduBerinde** [comment]
I don't get it. The NULLs added by an outer join don't come from the actual table. Maybe I'm misunderstanding something.

In the first case, we should infer "right.a=3". This should be straightforward.

The second case is more subtle. The key there is to realize it is equivalent to an inner join, and thus all those optimizations apply. Any left join that places a not-null restriction on a right column is equivalent to an inner join. This shouldn't be hard to add either, we already have code to infer non-null constraints (in fact we could use physicalProps).

**Comment by petermattis** [comment]
> I don't get it.

That's probably because what I wrote didn't make any sense. So ignore it. 

With fresh morning eyes, I'm wondering why we can't always push the filter to both sides of the join. Consider:

```
select * from (values (1), (2)) as a(x) left join (values (1)) as b(x) on (a.x=b.x);
+---+------+
| x |  x   |
+---+------+
| 1 |    1 |
| 2 | NULL |
+---+------+
```

If we add a where clause for `a.x=2` it is clear that we can filter rows from both the left and right. The query could be:

```
select * from (values (2)) as a(x) left join (values (NULL)) as b(x) on (a.x=b.x);
+---+------+
| x |  x   |
+---+------+
| 2 | NULL |
+---+------+
```

If we add a where clause for `b.x=2` we could also filter at the lower level, but we'd have to maintain the filter after the join as well because the left join allows columns that are part of the join condition to become NULL.

I'll have to think more about the mechanics of how this could be achieved. `opttoy` likes to have separate filter inference and filter push-down steps. But I'm not seeing right now what rule would maintain the `b.x=2` filter after the join. Perhaps there is something about `b.x` being NULL-able while `a.x` is non-NULL.

**Comment by RaduBerinde** [comment]
We should, we just don't do it right now. We need to take into account equality of columns and the type of join when we call splitFilter.

If you add a where clause for "b.x=2", it becomes an inner join. Maybe you're thinking of an ON clause?

**Comment by petermattis** [comment]
> If you add a where clause for "b.x=2", it becomes an inner join.

Oh, that's a good point that I missed in your earlier message.

**Comment by jordanlewis** [comment]
Going to make an attempt at this today.

Writing down some notes, I notice that there's also some sketchy behavior with the `ON` condition, which seems to only get propagated to the *right* side by accident:

```
root@:26257/test> explain select * from a left join b on a.a=b.a and b.a=1;
+-------+------+----------------+-------------+
| Level | Type |     Field      | Description |
+-------+------+----------------+-------------+
|     0 | join |                |             |
|     0 |      | type           | left outer  |
|     0 |      | equality       | (a) = (a)   |
|     0 |      | mergeJoinOrder | +"(a=a)"    |
|     1 | scan |                |             |
|     1 |      | table          | a@primary   |
|     1 |      | spans          | ALL         |
|     1 | scan |                |             |
|     1 |      | table          | b@primary   |
|     1 |      | spans          | /1-/1/#     |
+-------+------+----------------+-------------+
(10 rows)
```

I think the filter condition and the on condition both need to be passed into the join filter split function on both sides, somehow. Perhaps they can be combined with an `AND` before passing in to the splitter. I'll experiment a little.

**Comment by RaduBerinde** [comment]
That is not an accident, it would be incorrect to propagate it on the left. Every row on the left side of a left join generates at least one output row. There is an RFC here with more details: https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20161215_join_filters.md

We do implement the rules in the RFC, but we're not doing the best job generating `leftExpr`, `rightExpr`.

**Comment by RaduBerinde** [comment]
I have filed a separate issue for detecting unnecessary outer joins (the second example). This issue now tracks the problem shown by the first example, as far as I understand this is the case relevant to HIBERNATE.
