### ISSUE TITLE
Inserting into INTERLEAVEd table gives error: pq: unexpected value

### ISSUE THREAD

**Issue by derkan** [cockroachdb/cockroach#20780]
Is this a question, feature request, or bug report?
BUG REPORT
**QUESTION**

Have you checked our documentation at https://cockroachlabs.com/docs/stable/? If you could not find an answer there, please consider asking your question in our community forum at https://forum.cockroachlabs.com/, as it would benefit other members of our community.

Prefer live chat? Message our engineers on our Gitter channel at https://gitter.im/cockroachdb/cockroach.

**FEATURE REQUEST**

1. Does an issue already exist addressing this request? If yes, please add a :+1: reaction to the existing issue. If not, move on to step 2.

2. Please describe the feature you are requesting, as well as your proposed use case for this feature.

3. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

**BUG REPORT**

1. Please supply the header (i.e. the first few lines) of your most recent
   log file **for each node in your cluster**. On most unix-based systems
   running with defaults, this boils down to the output of

     grep -F '[config]' cockroach-data/logs/cockroach.log

   When log files are not available, supply the output of `cockroach version`
   and all flags/environment variables passed to `cockroach start` instead.

```
I171217 09:35:49.289550 1 util/log/clog.go:992  [config] file created at: 2017/12/17 09:35:49
I171217 09:35:49.289550 1 util/log/clog.go:992  [config] running on machine: derkan
I171217 09:35:49.289550 1 util/log/clog.go:992  [config] binary: CockroachDB CCL v1.1.3 (linux amd64, built 2017/11/27 13:59:10, go1.8.3)
I171217 09:35:49.289550 1 util/log/clog.go:992  [config] arguments: [cockroach start --insecure --host=localhost --store=./db/data,attrs=ssd,size=2GiB --log-dir=./db/log --http-port=8088]

```
2. Please describe the issue you observed:

- What did you do?

Hi, I've inserted a record before to `account_dids` table. But now I can't insert second row.
I had to recreate account_dids table without interleaved in `acounts` to insert second row successfully.
FK Relations: `user_dids.account_did_id` -> `account_dids.did` and `account_dids.account_id -> accounts.id`

```sql

CREATE TABLE accounts
(
  id uuid NOT NULL,
  name character varying(128) NOT NULL,
  CONSTRAINT accounts_pkey PRIMARY KEY (id),
  CONSTRAINT accounts_name_key UNIQUE (name)
);

CREATE TABLE account_dids
(
  id uuid NOT NULL,
  account_id uuid NOT NULL,
  did character varying(32) NOT NULL,
  assigned_on timestamp without time zone NOT NULL,
  is_ext boolean DEFAULT false,
  ext_password character varying(256),
  ext_subnets character varying(512),
  CONSTRAINT account_dids_pkey PRIMARY KEY (id),
  CONSTRAINT account_dids_account_id_fkey FOREIGN KEY (account_id)
      REFERENCES accounts (id),
  CONSTRAINT account_did_unq UNIQUE (account_id, did),
  CONSTRAINT account_dids_did_key UNIQUE (did)
) INTERLEAVE IN PARENT accounts(id);

CREATE TABLE user_dids
(
  id uuid NOT NULL,
  account_did_id uuid NOT NULL,
  assigned_on timestamp without time zone NOT NULL DEFAULT now(),
  user_id uuid NOT NULL,
  CONSTRAINT user_dids_pkey PRIMARY KEY (id),
  CONSTRAINT user_dids_account_did_id_fkey FOREIGN KEY (account_did_id)
      REFERENCES account_dids (id),
  CONSTRAINT user_dids_user_id_fkey FOREIGN KEY (user_id)
      REFERENCES users (id),
  CONSTRAINT user_dids_user_id_account_did_id_key UNIQUE (user_id, account_did_id)
);

INSERT INTO account_dids(id, account_id, did, is_ext, ext_subnets, assigned_on) VALUES ('2440f15c-6743-4ad9-8347-ab18138aad50', '26c8e73d-7e6b-46d5-94e5-095a873855cd', '908503778821', false, '', '2017-12-15T11:27:17.601103+00:00'::TIMESTAMP);
pq: unexpected value: raw_bytes:"\373\366\313@\003\022\013\254{Q\267\242F\220\241\326\277N\020Y\357>\000\001" timestamp:<wall_time:1513331897255798404 logical:0 >
```

- What did you expect to see?
Should be inserted without error

- What did you see instead?

```
pq: unexpected value: raw_bytes:"\373\366\313@\003\022\013\254{Q\267\242F\220\241\326\277N\020Y\357>\000\001" timestamp:<wall_time:1513331897255798404 logical:0 >
```

**Comment by lego** [comment]
cc: @richardwu, you might have an idea about why this is happening.

**Comment by richardwu** [comment]
Hi @derkan,

The error message you see is unexpected and is currently being tracked in https://github.com/cockroachdb/cockroach/issues/20067. It may be a unique constraint violation error that is being masked by a parsing error by the pgwire protocol.

Can you post the previous record (i.e. `INSERT` statement) that you inserted previously that is conflict with your second `INSERT` statement? I can't seem to reproduce it with just the one statement.

**Comment by richardwu** [comment]
Just an update: a fix was found for the bug for the seemingly irrelevant error message. The error message is most likely a unique constraint violation error.
