### ISSUE TITLE
sql: support statement_timeout

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#20789]
`SET statement_timeout` sets the statement timeout. From the docs:

> Abort any statement that takes more than the specified number of milliseconds, starting from the time the command arrives at the server from the client. If log_min_error_statement is set to ERROR or lower, the statement that timed out will also be logged. A value of zero (the default) turns this off.

This should be doable if we hook into query cancellation.

https://www.postgresql.org/docs/10/static/runtime-config-client.html

Required by the admin tool PSequel.

**Comment by dianasaur323** [comment]
@jordanlewis is this related to https://github.com/cockroachdb/cockroach/issues/5924?

**Comment by leofiore** [comment]
Should it be possibile to backport the statement_timeout to 2.0.5? Because of the problems reported in #29056 i'm having serious troubles using CRDB in production, having some applications hanging for hours waiting for queries to complete.
