### ISSUE TITLE
backup/restore: point-in-time restore ux questions

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#20812]
So last time I only checked whether or not the restore would work. I'm finally getting around to doing some more specific scenarios, and I'm noticing some odd behavior that I wanted your opinions on (cc @mjibson @dt)

- I'm allowed to restore an experimental mvcc backup with a normal restore? What happens then? Should we warn the user?
- I made an mvcc backup at 11/22 16:30, and am somehow allowed to restore as of system time on 11/23?

**Comment by dt** [comment]
> I'm allowed to restore an experimental mvcc backup with a normal restore? What happens then? Should we warn the user?
Yes, you'd just be restoring to the end time.

> I made an mvcc backup at 11/22 16:30, and am somehow allowed to restore as of system time on 11/23?

bug. need to add a check.

**Comment by dt** [comment]
@dianasaur323 think this is fixed

**Comment by dianasaur323** [comment]
Great - let me test it one last time, and then I'll close out.

**Comment by dianasaur323** [comment]
Yay! got error message that you cannot specify timestamp in the future. Check! Closing out.
