### ISSUE TITLE
tests: schema_changer_test hangs forever if stmt exec errors

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#20846]
unfortunately makes it very difficult to discover what actually broke.

@lego : Yea looks like the test waits on a channel for success but the routine fails and never sends the message.
https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/schema_changer_test.go#L675
In particular I think this routine is failing to let the test finish when an error is encountered. https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/schema_changer_test.go#L453-L462

**Comment by vivekmenezes** [comment]
@dt I don't know what this is about. Feel free to close .
