### ISSUE TITLE
cli: liveness error while decommissioning recently restarted node

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#20863]
The below was reported privately. The error occurs when the node trying to run the decommission can't find the liveness information for node 4. This could occur if the target node has recently been restarted (but actually a little more must have happened; I don't think liveness records are discarded by the nodes ever once seen, so perhaps the node trying to decommission was also recently restarted).

On issuing a `node decommission 4` command to node X, we saw this error:

```
stderr: Error: while trying to mark as decommissioning: rpc error: code = Unknown desc = during liveness update 4 -> true: unable to get liveness: node not in the liveness table
```

Node X had been recently restarted, and we waited until `node status` returned success before attempting the `node decommission`. Is it possible that the liveness gossip was just not available to node X yet? What would be a reasonable command to wait for to determine that the node is fully ready?

@dianasaur323 for triage.

**Comment by dianasaur323** [comment]
@vivekmenezes similar to the last issue I mentioned on, could we get someone assigned to fix these decommissioning issues?

**Comment by tschottdorf** [comment]
Fixed in https://github.com/cockroachdb/cockroach/pull/23082.
