### ISSUE TITLE
sql: consider letting FmtAnonymize imply FmtHideConstants

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#20864]
We currently have an odd-looking setup for statement pretty-printing:

1. `FmtAnonymize` anonymizes all names: `select x, y from z where myconst = 'secret'` becomes `select _, _ from _ where _ = 'secret'`
2. `FmtHideConstants` does what's on the tin but leaves names: `select x, y from z where myconst = _`

It's odd that `FmtAnonymize` doesn't actually anonymize the statement.

The only real user of this is `appStats`, where @knz has the following:

> the in-memory appstats memo remove the constants to reduce the amount of information, but keeps the names, so that the queries for different tables go to different bins
> however we further remove the names when sending to reg server
> so yeah, FmtAnonymize could definitely imply FmtHideConstants (but not the other way)

I ran into this in the somewhat unrelated context #20799 but I think we should resolve this in a separate PR.

**Comment by jordanlewis** [comment]
We've changed so much about anonymization that it would be better to make a new issue with holistic, desired changes here, than do this issue-as is. So I'll close.
