### ISSUE TITLE
sql: sparse partitionings should use minimal number of ranges

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#20875]
Currently the following table

```sql
CREATE TABLE ... PARTITION BY LIST (pkey) (
  PARTITION p VALUES IN (1, 3, 5)
)
```

will create seven ranges, but it only needs to create three.

**Comment by danhhz** [comment]
After https://github.com/cockroachdb/cockroach/pull/20933, it doesn't make sense to do this. It's unfortunate that there's no way for the user to opt into a minimal number of ranges, but cest la vie
