### ISSUE TITLE
intervalccl: make OverlapCoveringMerge O(n log m) instead of O(nm)

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#20878]
Instead of scanning each of the input coverings for each output range, use a heap. In practice this shouldn't matter much for either of the current uses of OverlapCoveringMerge (which both have reasonably low numbers of input coverings), but we may as well cover the worst case.

This should also be very benchmark-driven, in case the priority queue makes it slower for small inputs

**Comment by mwistrom** [comment]
I'd like to investigate this.

**Comment by psdh** [comment]
@mwistrom Did you get a chance to look at this?

**Comment by jiten-thakkar** [comment]
Hi, if no one is working on this then I would like to take this one. Trying to get get started with this project and this seems interesting.

**Comment by psdh** [comment]
Hey @jiten-thakkar, I've already started working on this as it didn't seem that mwistrom was still looking at it :)

**Comment by ridwanmsharif** [comment]
quick question I had when taking a quick look at this: does the order of the payloads matter in the final range array? 

For example here, for the range [1, 2) can the payload be 'da' instead of 'ad'

https://github.com/cockroachdb/cockroach/blob/9e3aeb3cc547eff4e094122860fa8a76c7d57434/pkg/ccl/utilccl/intervalccl/overlap_merge.go#L45

**Comment by khalibartan** [comment]
@knz @mjibson Any updates on this?

**Comment by shivamYoda** [comment]
Hey is anyone working on this ? I would really like to work on this.

**Comment by jordanlewis** [comment]
Nobody's working on this.

**Comment by shivamYoda** [comment]
@jordanlewis Thanks for the update , it would be great if you could guide me a bit regarding the problem and the project structure.

**Comment by jordanlewis** [comment]
Please check out the file `pkg/ccl/utilccl/intervalccl/overlap_merge.go`. The function in question, `OverlapCoveringMerge`, is at the bottom of the file. The comment embedded provides a pretty good overview of this item:

```
	// TODO(dan): This is O(number of coverings * total number of input ranges).
	// The number of ranges in the output is O(total number of input ranges) and
	// each has a payload that is O(number of coverings), so we can't do any
	// better without changing the output representation. That said, constants
	// matter so if this ever turns out to be too slow, we could sort all start
	// and end points (each point becomes an "event" to either start or end a
	// range) and scan them in order, maintaining a list of intervals that are
	// currently "open"
```

There are unit tests in `overlap_merge_test.go`. Please see `CONTRIBUTING.md` for more details on contributing to CockroachDB.

Thanks for your interest!

**Comment by shivamYoda** [comment]
@jordanlewis Thanks a ton :)

**Comment by shivamYoda** [comment]
@jordanlewis As I read from the comment over the function OverlapCoveringMerge , The order of payload in the output range array should be according to the order in Coverings. Can you please confirm that this is the case ? Or the payloads in each range in final array can be ordered in any way ?

**Comment by jordanlewis** [comment]
@shivamYoda to be honest, I don't know. Maybe @danhhz knows, but it's been a while since he's touched that code as well. Perhaps you could see what the unit tests require?

**Comment by shivamYoda** [comment]
@jordanlewis Sure, no problem.

**Comment by C0rWin** [comment]
The issue seems to be staled for a while, hence took a liberty and created PR#45139.

**Comment by dt** [comment]
#45139
