### ISSUE TITLE
cloud: Copy secure Kubernetes work over to our Helm chart

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#20889]
We maintain a [Helm chart for CockroachDB](https://github.com/kubernetes/charts/tree/master/stable/cockroachdb), which is basically just a template-ized version of our yaml file. I've copied over some of our simpler recent improvements in https://github.com/kubernetes/charts/pull/3105, but we should also copy over the option to run securely, as requested by https://github.com/cockroachdb/docs/issues/875#issuecomment-345415530.

**Comment by tlvenn** [comment]
Hi @a-robinson , it would be awesome if this could be completed.

**Comment by tlvenn** [comment]
Hi @a-robinson , any news on this ? We rely on your helm chart to release CDB in our K8 cluster and it would be great to have it secured outside of the box.

**Comment by a-robinson** [comment]
No news, but thanks for the reminder. I'll get to this in the next week or two if no one else does.

**Comment by a-robinson** [comment]
Opened https://github.com/kubernetes/charts/pull/4463 to fix this. If you try it out and have any feedback, please let me know!

**Comment by a-robinson** [comment]
Fixed by https://github.com/kubernetes/charts/pull/4463

**Comment by tlvenn** [comment]
Thanks a lot @a-robinson !
