### ISSUE TITLE
sqlccl: `SELECT foo PARTITION (p1)` syntax

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#20885]
This syntax is alluded to in the partitioning rfc: https://github.com/cockroachdb/cockroach/blob/e185c344507ad0a8ca8bd6d8adbdb2c017f63afd/docs/RFCS/20170921_sql_partitioning.md#query-planning-changes

Essentially, it rewrites your query with additional filters in the WHERE clause to limit it to only the given partition. This proposed impl isn't guaranteed to work for sovereignty, but is still useful in the meantime.

**Comment by danhhz** [comment]
This is not going to make 2.0

**Comment by danhhz** [comment]
Sounds like someone else is going to do this in 2.1, assigning to @vivekmenezes for triage

**Comment by rohany** [comment]
@jordanlewis is this something we can do at the SQL level, or is it something that optimizer team should look at? Or is this already done by the work that @ridwanmsharif has done?

**Comment by jordanlewis** [comment]
I think the optimizer would mostly likely have to be involved in this item. It has not been done by Ridwan's work. I believe the idea here would be that a query containing a partition limiting syntax would be transformed into the equivalent filter clause, which would then further be transformed into spans.
