### ISSUE TITLE
sqlccl: PARTITION LIKE

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#20886]
It's expected that partitioning users will use the same partitioning across many tables/indexes in the same cluster. It would be nice if there was some way to define this once and share it across all of them (even keeping them in sync if the one definition changed). A new syntax `PARTITION LIKE table` was proposed in the rfc, but got cut because there were too many rough edges and it wasn't a priority in the initial implementation. (See https://github.com/cockroachdb/cockroach/pull/18683 for context). We should revisit at some point.

**Comment by awoods187** [comment]
We should also consider including zone configs in this idea or have a similar `CONFIGURE ZONE USING table foo` that does the same thing for zone configs

**Comment by jordanlewis** [comment]
@solongordon @danhhz should we close this?

**Comment by damienhollis** [comment]
From an end user perspective, it is great what you have done in 9.2 with regards to making zone configurations easier to setup.  But it is still a pain to setup the same partitioning on many tables/indexes.  We currently use a lot of interleaving to make this easier but it means we are using interleaving for the wrong reason in quite a few places (and sometimes paying the price with regards to contentions on the parent table/row).  

I would like to see a way that a partitioning scheme could be defined and then applied to many tables/indexes.  Is there any plans around this?

**Comment by jordanlewis** [comment]
Yes! I agree. I think internally we had decided we probably weren't going to go ahead with this particular implementation, but I wasn't positive - that's why I was asking. Totally agreed that we need to be doing better here in one way or another!
