### ISSUE TITLE
lock down KV endpoints

### ISSUE THREAD

**Issue by MBerhault** [cockroachdb/cockroach#2089]
KV endpoints should be internal only.
Some or all of the following should be done:
* restrict KV api to the `node` user (possibly `root` as well for now)
* remove HTTP endpoint

**Comment by tschottdorf** [comment]
we should also port the bank example to the acceptance tests first. and we need to work on the usability of testing the system using the acceptance tests. getting at the logs is always a hassle so far (ok, different issue).

**Comment by MBerhault** [comment]
yes, the points I mentioned above were just the end results. The side affects are fairly sizable: tests, client, bank example, etc..

**Comment by petermattis** [comment]
When this is done, we should also move the http sender code from `client` to `sql/driver`.

**Comment by MBerhault** [comment]
@petermattis: do we plan to do sql over rpc at some point soon? Without it, rpc enforcement is a lot simpler. If we do, there'll be a teensie bit more trickery involved.

**Comment by petermattis** [comment]
Given that rpc has benchmarked as significantly faster than http, I would plan for it happening at some point.

**Comment by tschottdorf** [comment]
what's the plan about porting all the tests? I'm assuming we won't have to rewrite every single test to use certain key ranges or something like that.

**Comment by MBerhault** [comment]
there's not all that much to change. In addition to `node` which will always be needed, I'm still allowing `root` for now. I never finished porting all the tests to using `testuser`, so the change was fairly minimal. See #2193

**Comment by MBerhault** [comment]
KV endpoint now requires `root` or `node`. Permissions have been removed entirely.
Eventually, I think we want to require `node` only. This would emply:
* remove `Request.Header.User` field and hard-code to `node` (see GetUser in proto/*.go for examples).
* remove `root` as an accepted user
* cleanup all client code to no longer specify `Header.User`

This would effectively make the KV endpoint unusable without `node` certificates, meaning anyone messing around with it would have to do so intentionally.

**Comment by petermattis** [comment]
Nice. There are some follow-on tasks mentioned in this issue, such as removing support for the KV http endpoint and moving the http sender code from `client` to `sql/driver`. Are you going to tackle those?

**Comment by MBerhault** [comment]
Yup. I'm seeing "restrict to `node`" as part of this, and all others as cleanup/refactor for which I'll probably file other issues. For this week though, I'll be focusing on the structured configs.

**Comment by MBerhault** [comment]
filed #2271 for follow-up refactoring and cleanup.
