### ISSUE TITLE
sql: expose partition values in a structured way

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#20891]
#21307 introduced a vtable, `crdb_internal.partitions`, with the following schema:

```
+--------------------------+--------------------------------+
|          Table           |          CreateTable           |
+--------------------------+--------------------------------+
| crdb_internal.partitions | CREATE TABLE partitions (␤     |
|                          |     table_id INT NOT NULL,␤    |
|                          |     index_id INT NOT NULL,␤    |
|                          |     parent_name STRING NULL,␤  |
|                          |     "name" STRING NOT NULL,␤   |
|                          |     columns INT NOT NULL␤      |
|                          | )                              |
+--------------------------+--------------------------------+
```

Notably missing are the actual boundaries, i.e., the ellipses in `VALUES IN (...)` or `VALUES FROM (...) TO (...)`. It's rather difficult to include these in a virtual table, as the types of the datums varies by the index being partitioned, and `DEFAULT`, `MINVALUE`, and `MAXVALUE` are magic values that are not datums.

We'll eventually need to expose this information. So far, though, the best representation we've come up with so far is a bunch of `string` columns storing raw SQL snippets, which is pretty gross. Punting on this until the admin UI or user requests can shape the design of this feature; right now we're speculating as to what's reasonable and what's gross without any concrete guidance.

**Comment by vilterp** [comment]
Once this is done, Interested in showing partitions in the UI 👍

**Comment by rohany** [comment]
I think #39053 implements what is being requested here.

**Comment by jordanlewis** [comment]
Does the linked PR deal with non-integer datatypes ok? If I recall correctly part of the difficulty with doing this was making sure other datatypes got printed right. In either case, I think closing this is probably appropriate.

**Comment by rohany** [comment]
I believe it does -- 

```
root@127.0.0.1:50950/defaultdb> show partitions from table t;
  database_name | table_name | partition_name | parent_partition | column_names | index_name |               partition_value               | zone_constraints
+---------------+------------+----------------+------------------+--------------+------------+---------------------------------------------+------------------+
  defaultdb     | t          | p1             | NULL             | x            | t@primary  | (MINVALUE) TO ('2017-12-04 00:00:00+00:00') | NULL
  defaultdb     | t          | p2             | NULL             | x            | t@primary  | ('2017-12-04 00:00:00+00:00') TO (MAXVALUE) | NULL
(2 rows)
```
