### ISSUE TITLE
backup: TestBackupRestoreNegativePrimaryKey flakiness in CI

### ISSUE THREAD

**Issue by richardwu** [cockroachdb/cockroach#20904]
https://teamcity.cockroachdb.com/project.html?projectId=Cockroach_UnitTests&buildTypeId=&tab=testDetails&testNameId=-3236096413596094857&order=TEST_STATUS_DESC&branch_Cockroach_UnitTests=__all_branches__&itemsCount=50

cc: @benesch  @danhhz

**Comment by benesch** [comment]
You sure this is flaky? It's never failed on master.

**Comment by benesch** [comment]
Ah, it is indeed, but it's due to the same root cause as #21026. Closing in favor of that issue. Thanks for the spot, @richardwu!
