### ISSUE TITLE
backup: TestAsOfSystemTimeOnRestoredData flakiness in CI

### ISSUE THREAD

**Issue by richardwu** [cockroachdb/cockroach#20903]
https://teamcity.cockroachdb.com/project.html?projectId=Cockroach_UnitTests&buildTypeId=&tab=testDetails&testNameId=-9198777658099507709&order=TEST_STATUS_DESC&branch_Cockroach_UnitTests=__all_branches__&itemsCount=50

cc: @danhhz @dt

**Comment by danhhz** [comment]
@mjibson for triage

**Comment by dt** [comment]
huh, so, on most of those runs where it failed, _lots_ of other tests failed too... usually all complaining bout wrong number of starting ranges... sad agent?

There is one where it looks like the restore tests themselves actually got unexpected results: https://teamcity.cockroachdb.com/viewLog.html?buildId=450083&buildTypeId=Cockroach_UnitTests_Testrace&tab=buildResultsDiv

**Comment by richardwu** [comment]
Hrm that last test might be a symptom of an issue in my PR and not the test itself. That might be the case for the other 2 failed branches too.

**Comment by mjibson** [comment]
Closing cuz old and we don't have these logs anymore.
