### ISSUE TITLE
ui: cluster overview alignment is off

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#20916]
I am so sorry for being nitpicky! It looks like the alignment of the cluster overview is still a bit off. We have the right text and styling now, but the margins on the overview page are different from those on the cluster page. Could we make those consistent?

cc @couchand

**Comment by couchand** [comment]
@dianasaur323  can you add a screenshot to illustrate what you mean?

**Comment by dianasaur323** [comment]
Of course! It looks like it's the padding on the title. So this is the cluster overview:
![image](https://user-images.githubusercontent.com/5768024/34502977-2683fe30-efe4-11e7-93b2-dc8b8522d61f.png)

whereas this is the time series metrics: 
![image](https://user-images.githubusercontent.com/5768024/34502988-30058ea6-efe4-11e7-9968-14fda987aa3d.png)

When you flip between the cluster overview and the time series metrics, the padding is slightly different.
