### ISSUE TITLE
CI: ReplicationTest: expected 3 replicas, only found 2

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#2091]
The following test appears to have failed:

[#5885](https://circleci.com/gh/cockroachdb/cockroach/5885):

```
=== RUN TestRangeReplication
--- PASS: TestRangeReplication (20.23s)
=== RUN TestSingleKey
--- PASS: TestSingleKey (16.09s)
=== RUN TestStatusServer
--- FAIL: TestStatusServer (38.76s)
	testing.go:150: acceptance/replication_test.go:72: condition failed to evaluate within 20s: expected 3 replicas, only found 2
FAIL
ok github.com/cockroachdb/cockroach/acceptance 1337s

```
Please assign, take a look and update the issue accordingly.

**Comment by tschottdorf** [comment]
well, always hard to say whether that is a fluke or not. With CircleCI, I lean towards fluke. No way to find out now, is there?

**Comment by BramGruneir** [comment]
I thought that we had tackled this before. I'll try to get a closer look to see what's going on, but it's a very hard to diagnose issue.

**Comment by tschottdorf** [comment]
I think it's hopeless unless we get our hands on the server logs. From the looks of it we're not storing them - we used to save all container output, but I think that got lost transitioning to the new CI scripts. We should consider putting that back into place, or at the very least having the acceptance tests log to the artifacts directory.

**Comment by tamird** [comment]
Hasn't been seen in a while, closing.
