### ISSUE TITLE
ui: jobs table showing alter table roles entry?

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#20913]
I was just running a local build off master, and noticed this job when I spun up CockroachDB. I definitely did not create any users.. @mberhault thoughts?

![image](https://user-images.githubusercontent.com/5768024/34187284-9df8498a-e4fe-11e7-82bf-560a58ebce84.png)

**Comment by mberhault** [comment]
That's one of the migrations needed for rbac. Since it's causing a
backfill, it's registered as a job. We could prevent migrations from
showing up as jobs, but I'm not sure how hard that would be.

**Comment by dianasaur323** [comment]
hmm.. i think we want to avoid confusing users with that job entry. is there anyway for us to delete it from the jobs table after the fact, or just don't let it show up on the admin UI?

**Comment by mberhault** [comment]
I have no idea how complex it would be to elide certain jobs (or remove them after the fact).
We need input from someone who knows how jobs are reported. @mjibson perhaps?

**Comment by bdarnell** [comment]
I think migrations generally *should* be shown as jobs - if we have one that takes significant time you'd still want to be able to see what's going on. We don't want to make the system even more opaque and hiding moving parts. I'd rather relent on my insistence that we go through the migration process even for new clusters than make migrations go through a new class of hidden jobs.

**Comment by mberhault** [comment]
True, although we could mark them as "system migrations" and not show them by default.
As for migrations, I think your insistence is well placed. I would however like to see migrations rolled back into the standard code after some number of releases (see #20476).

**Comment by dianasaur323** [comment]
so if I understand correctly, is this only happening because I was upgrading an older version to the new one? So if I just start from scratch with a newer version, this wouldn't happen? I guess I don't fully understand what a system migration means.

**Comment by mberhault** [comment]
We use migrations to modify existing system tables. In this case, the migration is adding a new column named `isRole` that indicates whether the entry in the `system.users` table is a user or a role.

We use migrations both to upgrade old versions and to setup brand new cluster, mostly because it's easier to have a single code path.

The reason this migration shows up is that adding a new column with a non-null value causes a backfill of the existing entries. Backfills are registered in the jobs table.

**Comment by dianasaur323** [comment]
ok, so i ran this buy some admin ui peeps, and the consensus is that this isn't a huge deal. One option would be to label this as an internal job. How hard would that be? If it is a bit complicated, let's just close this issue out and wait until users start complaining / asking questions.

**Comment by mberhault** [comment]
I would leave it for now we revisit if too many people start asking about it. More selective views in the admin UI is a good thing to have overall, and more thought needs to be put into it than just hiding system jobs.

**Comment by dianasaur323** [comment]
ok, closing for now! thanks for the discussion :)
