### ISSUE TITLE
sql: support ALTER COLUMN TYPE char(N)/varchar(N)

### ISSUE THREAD

**Issue by lego** [cockroachdb/cockroach#20927]
PostgreSQL char and varchar column types support limits, see https://www.postgresql.org/docs/10/static/datatype-character.html.

Right now, you cannot execute a schema change to modify a column to be one of these types.

```sql

root@:26257/test> create table t (id string);
CREATE TABLE

Time: 14.153116ms

root@:26257/test> alter table t alter column id type char(10);
invalid syntax: statement ignored: unimplemented at or near ";"
DETAIL: source SQL:
alter table t alter column id type char(10);
                                           ^
``` 

From the postgres spec: these column types can be used as `character(N)`, `char(N)`, `varchar(N)`, `character varying(N)`. The difference between `char` and `varchar` types is that `char` is fixed-length and will be padded with spaces. For these columns if a schema change is altering a column to specify a type with a limit, the schema change will fail if any row violates the limit.

**Comment by justinj** [comment]
We do support some of this now:
```
root@:26257/d> create table y (x char(10));
CREATE TABLE

Time: 4.395538ms

root@:26257/d> insert into y values ('asdfasdfasdfasdfasdfasdfa');
pq: value too long for type STRING(10) (column "x")
```
but they're all just aliases for `STRING(n)`.

Could you extend the issue description with the difference between this and what we have now? I know the behaviour for ex. `CHARACTER` is different (I think it's just a direct alias for `STRING`, but I think that is a conscious decision, see #16826).

**Comment by lego** [comment]
Egad, I thought I posted the statement that was failing. The statement that wasn't working was a alter column type. Suspected it wasn't supported at all because there are syntax rules that don't have limits in them, which may be the source of this statement not working.

```sql

root@:26257/test> create table t (id string);
CREATE TABLE

Time: 14.153116ms

root@:26257/test> alter table t alter column id type char(10);
invalid syntax: statement ignored: unimplemented at or near ";"
DETAIL: source SQL:
alter table t alter column id type char(10);
                                           ^
```

**Comment by lego** [comment]
Even more 🤦‍♂️. Didn't see we don't support ALTER COLUMN TYPE at all, #9851. Closing this issue.
