### ISSUE TITLE
ui: factor out an InfoTooltip component

### ISSUE THREAD

**Issue by vilterp** [cockroachdb/cockroach#20921]
Factor this: https://github.com/cockroachdb/cockroach/blob/ede0950b97b03e615b03c62a40fb8a918af19347/pkg/ui/src/views/jobs/index.tsx#L183-L189

And this: https://github.com/cockroachdb/cockroach/blob/a24aa9f6d4d99078565d8f2c5cc46c4020b0073b/pkg/ui/src/views/cluster/components/visualization/index.tsx#L44-L50

Out into a common component (maybe `<InfoTooltip info={}>...children...</InfoToolTip>`) that we can use all over the place to give details on stuff.

**Comment by couchand** [comment]
Not sure about how to handle the BEM classes there.  If we're saying this is a component of its own, maybe they can be unified?

Proposed usage:
```
<Tooltip>
  { /* tooltip contents - text or markup */ }
</Tooltip>
```

**Comment by vilterp** [comment]
Yeah, hopefully they can be unified. Agree with the proposed usage.

**Comment by jayshrivastava** [comment]
Hello! Is this issue still active? I was wondering if I could take it on as a first issue 😄

**Comment by oeph** [comment]
I gave it a try in #64555 - please have a look if this would be ok

**Comment by oeph** [comment]
@maryliag this ticket wasn't closed automatically after merging the PR - could you please close it :)
