### ISSUE TITLE
SQL transaction restart behavior

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#2094]
our KV Transactions restart quite often and are expected to. The `client.Txn` interface expects a retryable function and thus deals with this quite nicely.
The SQL interface limits us to the interface `tx.{Begin,Commit,Rollback}()`.

This raises the question on how restarts are going to be handled, especially for multi-phase transactions (i.e. where the client sends `BEGIN TRANSACTION`, does some work, goes for a coffee and finally types `END TRANSACTION`), but even for one-key single-phase transactions which may well just restart because of clock uncertainty.

The two options are:

* propagate every transaction error to the client; clients need to retry anyways. The issue with that is that once a `Txn` is running, we depend on the client telling us when it gives up. The SQL `Tx` interface doesn't really give us that; in practice I think it would boil down to
  ```go
  var err error
  Tx.Begin()
  for /* some cond to limit retries */ {
    doWork(txn)
    if err := txn.Commit(); // needs to update the session's Txn data, even on error
  }
  if err != nil {
    txn.Rollback() // we need this so that the Txn can end on the KV store
  }
  // only now done with txn
  ```

  Note that there are multiple calls to `Commit()` but only one for `Begin()` (and that's necessary, unless you enforce a `Rollback()` to clear `Txn` state from the `Session`, which doesn't make the interface any nicer.

* handle some retries at the gateway. More precisely, anything that doesn't `ABORT` the `Txn` gets retried transparently through a KV client. I've outlined this [here](https://github.com/cockroachdb/cockroach/pull/2076#issuecomment-130620740). In effect the client would see a retry precisely when the `Txn` gets aborted, in which case it isn't running any more on the server and no state needs to be kept. For multi-phase transactions, we explicitly abort the Txn server-side if we realize that we need to restart, but can't replay everything the client has done. So multi-phase would be less performant: it doesn't rely on the client to do the right retrying but always assumes the client gives up.

I think the second option matches up both interfaces more nicely and works better for the expected use case (single-roundtrip transactions), where it will also be more performant due to less client-kv round-trips.

**Comment by petermattis** [comment]
The Go `database/sql` package only provides for `{Begin,Commit,Rollback}`, but there is no reason we can't provide a convenience routine in our `sql/driver` package that works similarly to `client.Txn` and takes a retryable function.

As I noted in the PR this issue sprang from, all SQL databases can error transactions in ways that they should be retried. The most common reason I've seen is during database failover, but aborts due to deadlock are also a possibility. I think its good that we expose the need for a retry loop or interface that automatically performs retries.

If the client sends `BEGIN TRANSACTION` the client is going to need to perform the retry loop. If they go to coffee between the `BEGIN` and `COMMIT` then there transaction will likely not commit successfully, but that's their problem.

I'm not terribly fond of the terms multi-phase and single-phase, but if I'm interpreting this correctly a single-phase transaction is one that is started on the server side. Such transactions should definitely be retried on the server side. Perhaps better terminology would be single-statement and multi-statement. 

Whatever we can do to reduce client round-trips will be useful for performance, but I don't think it will resolve the need to have transactions performed in retry loops on the client.

**Comment by tschottdorf** [comment]
> The Go database/sql package only provides for {Begin,Commit,Rollback}, but there is no reason we can't provide a convenience routine in our sql/driver package that works similarly to client.Txn and takes a retryable function.

It doesn't matter what we provide in our `sql/driver` package because it needs to work for those who aren't using it.

> As I noted in the PR this issue sprang from, all SQL databases can error transactions in ways that they should be retried

Yes, but that's more to my point: In our case, those retryable errors actually leave the transaction running on the server. That's contrary to what's expected in SQL-land. Retrying corresponds to having your `Txn` aborted. What you're saying makes more sense with my suggestion.

> If the client sends BEGIN TRANSACTION the client is going to need to perform the retry loop. If they go to coffee between the BEGIN and COMMIT then there transaction will likely not commit successfully, but that's their problem.

agreed, but with the above caveat that a SQL-retry actually means that your Txn **failed**. Not that it's waiting for the internal KV client retrying and possibly blocking concurrent writers.

> I'm not terribly fond of the terms multi-phase and single-phase, but if I'm interpreting this correctly a single-phase transaction is one that is started on the server side. Such transactions should definitely be retried on the server side. Perhaps better terminology would be single-statement and multi-statement.

All transactions are started on the server side. Multi- vs Single-Statement rings wrong because `BEGIN TRANSACTION; DO STUFF; END TRANSACTION` is a "single-phase" transaction, but multi-statement. Maybe we can settle for single-roundtrip or single-request?

> Whatever we can do to reduce client round-trips will be useful for performance, but I don't think it will resolve the need to have transactions performed in retry loops on the client.

This misses my point. I was suggesting having clients retry on an abort, so I'm not suggesting that clients don't retry. What I'm suggesting is that the right condition to expose to clients is that their KV-Transaction has been aborted because that's what doesn't leak internal resources.

**Comment by petermattis** [comment]
On Thu, Aug 13, 2015 at 1:38 PM, Tobias Schottdorf <notifications@github.com
> wrote:

> The Go database/sql package only provides for {Begin,Commit,Rollback}, but
> there is no reason we can't provide a convenience routine in our sql/driver
> package that works similarly to client.Txn and takes a retryable function.
>
> It doesn't matter what we provide in our sql/driver package because it
> needs to work for those who aren't using it.
>
I'm suggesting we provide a small utility routine to help with the retries.
Folks can choose not to use it and to handle the retries themselves.

> As I noted in the PR this issue sprang from, all SQL databases can error
> transactions in ways that they should be retried
>
> Yes, but that's more to my point: In our case, those retryable errors
> actually leave the transaction running on the server. That's contrary to
> what's expected in SQL-land. Retrying corresponds to having your Txn
> aborted. What you're saying makes more sense with my suggestion.
>
Why aren't we aborting the transaction on retries? That was my
understanding of what was going on, so clearly I'm missing details about
reality.

**Comment by spencerkimball** [comment]
There are retries which just cause an epoch increment on the transaction. Such as when restarting due to read uncertainty or because a serializable txn encountered more recent timestamps than the original transaction timestamp while reading or writing. In these cases, you want to keep your intents in place so you're more likely to finish the txn on restart.

**Comment by tschottdorf** [comment]
> I'm suggesting we provide a small utility routine to help with the retries. Folks can choose not to use it and to handle the retries themselves.

Ah, ok. Sorry, I thought you were suggesting the helper to work around the awkwardness we would impose on the interface with option one.

Now that the confusion about Txns is resolved, do you still consider option one worthwhile? My suggestion will actually expose to SQL clients what you were suggesting.

**Comment by vivekmenezes** [comment]
On Thu, Aug 13, 2015, 4:31 PM Tobias Schottdorf <notifications@github.com>
wrote:

> I'm suggesting we provide a small utility routine to help with the
> retries. Folks can choose not to use it and to handle the retries
> themselves.
>
> Ah, ok. Sorry, I thought you were suggesting the helper to work around the
> awkwardness we would impose on the interface with option one.
>
> Now that the confusion about Txns is resolved, do you still consider
> option one worthwhile? My suggestion will actually expose to SQL clients
> what you were suggesting.
>

Are you also suggesting we make use of the more efficient restarts at the
sql client level using the logic

if restartErr, ok := err.(proto.TransactionRestartError); ok {

      if log.V(2) {

        log.Warning(err)

      }

      if restartErr.CanRestartTransaction() ==
proto.TransactionRestart_IMMEDIATE {

        r.Reset()

        continue

      } else if restartErr.CanRestartTransaction() ==
proto.TransactionRestart_BACKOFF {

        continue

      }

**Comment by tschottdorf** [comment]
No, that's exactly when we should abort the KV transaction. If a client gets an error from `Commit()`, then it rightfully assumes that the transaction is gone and any retry starts a new one. If we keep it running on the server and trust the client with an awkward dance around an interface that doesn't support the semantics, everybody will have a bad time. The only sane thing (at least to me) seems aborting the transaction properly. That prevents proper ratcheting of priorities, etc. but that can be worked around with a bit more `Session` state later.

**Comment by petermattis** [comment]
`database/sql.Tx.{Commit,Rollback}()` cause `database/sql.Tx.close()` to be called (and there is no way for the database driver to prevent that). Once closed, a `Tx` cannot be reused and the underlying `driver.conn` will be reused for other statements. I think the only possible retry loop at the end user level is to create a new transaction using `database/sql.DB.Begin()`.

**Comment by petermattis** [comment]
I think we absolutely need an error from `Tx.Commit()` to cause the transaction to be aborted.

`database/sql.Tx.{Commit,Rollback}()` cause `database/sql.Tx.close()` to be called after which it is invalid to call any commands on the `Tx`. There is no hook for the driver to change this behavior. The underlying `driver.conn` will also be released back to the connection pool and reused for other statements.

**Comment by tschottdorf** [comment]
Yes. So you agree that we're going with solution two above?

**Comment by petermattis** [comment]
Yep. I don't think we have a choice. Or more accurately, the pseudo-code you outlined for option one isn't workable with the interface `database/sql` enforces.

**Comment by tschottdorf** [comment]
@vivekmenezes looked like you were working on this. Care to assign?

**Comment by vivekmenezes** [comment]
Reopen this issue if we want something specific implemented. Thanks!
