### ISSUE TITLE
sql: implement ALTER SEQUENCE ... RESTART

### ISSUE THREAD

**Issue by vilterp** [cockroachdb/cockroach#20956]
- `ALTER SEQUENCE my_seq RESTART WITH num`: Sets the "restart with" setting on `my_seq`.
- `ALTER SEQUENCE my_seq RESTART`: Sets `my_seq` to its "restart with" setting.

Jira issue: CRDB-5906

**Comment by sinagolchi** [comment]
Any news on the Implementation of RESTART and CYCLE?

**Comment by rafiss** [comment]
Closing this in favor of https://github.com/cockroachdb/cockroach/issues/74496
