### ISSUE TITLE
sql: use regclass instead of string in arguments to sequence functions

### ISSUE THREAD

**Issue by vilterp** [cockroachdb/cockroach#20958]
**Expected:**

As explained in the centered note in the [PG docs](https://www.postgresql.org/docs/10/static/functions-sequence.html), the PG sequence functions take a regclass, not a string, as the argument to sequence functions (`nextval`, etc). The sequence name is looked up at `CREATE TABLE` or `ALTER TABLE` execution time, and from then on is bound to the OID. Thus, it continues working when the sequence is renamed.

**Current state:**

Cockroach's sequence functions take strings as arguments. Thus, if you rename the sequence, the DEFAULT expression still has the old name as a string, and your next insert will fail:

```
root@:26257/test> create sequence test_seq;
CREATE SEQUENCE

Time: 6.849ms

root@:26257/test> create table test_tbl (id int primary key default nextval('test_seq'), foo text);
CREATE TABLE

Time: 6.229ms

root@:26257/test> insert into test_tbl (foo) values ('foo');
INSERT 1

Time: 8.797ms

root@:26257/test> select * from test_tbl;
+----+-----+
| id | foo |
+----+-----+
|  1 | foo |
+----+-----+
(1 row)

Time: 2.509ms

root@:26257/test> alter sequence test_seq rename to not_test_seq;
RENAME SEQUENCE

Time: 75.653ms

root@:26257/test> insert into test_tbl (foo) values ('foo');
pq: nextval(): relation "test_seq" does not exist
root@:26257/test>
```

A smaller, though still useful step would be just to validate the sequence name's existence when a DEFAULT expression with nextval is set.

**Comment by ajwerner** [comment]
@the-ericwang35 fixed this with https://github.com/cockroachdb/cockroach/pull/59396.
