### ISSUE TITLE
sql: removing partitioning should work with a pure oss binary (no ccl)

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#20951]
Obviously, this also needs to be tested

**Comment by benesch** [comment]
I've been thinking about this. It would be much easier if we removing partitioning required a CCL binary but allowed invalid/expired licenses. Is that a nonstarter?

**Comment by danhhz** [comment]
cc @awoods187

**Comment by danhhz** [comment]
Talked this over again and adding the ability to do this with a pure OSS binary (when it required a CCL one to get there in the first place) is fine to leave for later. Let's add a test for doing it with an expired license and call it a day.

**Comment by awoods187** [comment]
im fine with that
