### ISSUE TITLE
sql: avoid using "prefix" in partition error messages

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#20960]
@nstewart was confused today about our usage of "prefix" when talking about partitioning. Indeed, it's not immediately clear whether prefix refers to the columns or the values within the columns.

We're down to exactly one error message that uses the word prefix:

```
declared partition columns \(a, b, c\) are not a prefix of index being partitioned \(a, b\)
```

Perhaps we can find some way to remove the use of "prefix" or otherwise reword it for clarity:

**Comment by danhhz** [comment]
Our q/a buddy brought this up as confusing, too. I agree this is worth addressing

**Comment by danhhz** [comment]
I thought about this a bit today and the alternatives I came up with were either synonyms of prefix or simply less specific. Inclined to do nothing here this this particular error message seems reasonably clear to me ("declared partition columns" along with the actual column names), but kicking this back to you in case you feel strongly.
