### ISSUE TITLE
gossip: high water stamp assertion tripped

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#20986]
https://sentry.io/cockroach-labs/cockroachdb/issues/421853510/

```
*log.safeError: stopper.go:179: infostore.go:198
  File "github.com/cockroachdb/cockroach/pkg/gossip/infostore.go", line 198, in addInfo
  File "github.com/cockroachdb/cockroach/pkg/gossip/gossip.go", line 806, in addInfoLocked
  File "github.com/cockroachdb/cockroach/pkg/gossip/gossip.go", line 800, in AddInfo
  File "github.com/cockroachdb/cockroach/pkg/storage/replica.go", line 5225, in gossipFirstRange
  File "github.com/cockroachdb/cockroach/pkg/storage/replica_proposal.go", line 499, in leasePostApply
...
(11 additional frame(s) were not displayed)

stopper.go:179: infostore.go:198
```

**Comment by tschottdorf** [comment]
```go
	if i.OrigStamp == 0 {
		i.Value.InitChecksum([]byte(key))
		i.OrigStamp = monotonicUnixNano()
		if highWaterStamp, ok := is.highWaterStamps[i.NodeID]; ok && highWaterStamp >= i.OrigStamp {
			panic(errors.Errorf("high water stamp %d >= %d", highWaterStamp, i.OrigStamp))
		}
	}
```

@spencerkimball, any ideas?

**Comment by tschottdorf** [comment]
Looks like the info here is made by

```
// newInfo allocates and returns a new info object using the specified
// value and time-to-live.
func (is *infoStore) newInfo(val []byte, ttl time.Duration) *Info {
	nodeID := is.nodeID.Get()
	if nodeID == 0 {
		panic("gossip infostore's NodeID is 0")
	}
	now := monotonicUnixNano()
	ttlStamp := now + int64(ttl)
	if ttl == 0 {
		ttlStamp = math.MaxInt64
	}
	v := roachpb.MakeValueFromBytesAndTimestamp(val, hlc.Timestamp{WallTime: now})
	return &Info{
		Value:    v,
		TTLStamp: ttlStamp,
		NodeID:   nodeID,
	}
}
```

so OrigStamp will be zero and we'll set it in the above block (in my last comment). Not sure how that assertion would fail, then. We only ever update the map entries in the code below `if i.OrigStamp == 0`. Is this perhaps something stupid with `monoTime` overflowing?

**Comment by tschottdorf** [comment]
Reminder to self: cherry-pick #20989 into release-1.1.

**Comment by a-robinson** [comment]
https://sentry.io/cockroach-labs/cockroachdb/issues/434144848/

**Comment by spencerkimball** [comment]
@tschottdorf I couldn’t for the life of me find the text I’d the error message in sentry. I thought we’d changed it so it would be visible.

**Comment by tschottdorf** [comment]
We did, but that panic is on an alpha from early December, and I improved the reporting only just before the holidays :(

**Comment by tschottdorf** [comment]
Moving to 2.1 milestone, there's really nothing to do here until we get a sentry report (post 2.0 most likely).

**Comment by tschottdorf** [comment]
https://sentry.io/cockroach-labs/cockroachdb/issues/508291313/

**Comment by tschottdorf** [comment]
@spencerkimball we now have reports with the timestamps in them. There doesn't seem to be any overflow issue.

**Comment by mberhault** [comment]
Sentry issue: [COCKROACHDB-GA](https://sentry.io/cockroach-labs/cockroachdb/issues/557845701/)

**Comment by mberhault** [comment]
Sentry issue: [COCKROACHDB-GH](https://sentry.io/cockroach-labs/cockroachdb/issues/560258185/)

**Comment by mberhault** [comment]
Sentry issue: [COCKROACHDB-GG](https://sentry.io/cockroach-labs/cockroachdb/issues/560257259/)

**Comment by bdarnell** [comment]
The issues Marc links in the last few comments are all on release 1.0 (we just had [another](https://sentry.io/cockroach-labs/cockroachdb/issues/570967975/)), which we don't really care about any more (but who's out there still running it?). However, it's still happening on current releases. The one Alex linked is 2.0.0.

**Comment by tim-o** [comment]
New sentry issue: https://sentry.io/cockroach-labs/cockroachdb/issues/586614683/?referrer=slack#

**Comment by tim-o** [comment]
This is 2.0.3.

**Comment by tim-o** [comment]
Sentry issue: [COCKROACHDB-H4](https://sentry.io/cockroach-labs/cockroachdb/issues/586614683/)

**Comment by petermattis** [comment]
2.0.5 event https://sentry.io/cockroach-labs/cockroachdb/issues/678019279/?environment=v2.0.5

**Comment by petermattis** [comment]
The prior failures all came via `MaybeGossipNodeLiveness`. The latest failure came via `MaybeGossipSystemConfig`. Probably nothing relevant there. 

I wonder if this was fixed by https://github.com/cockroachdb/cockroach/pull/29413. In particular, before that PR we were allowing a remote node to send us an info that was generated on the local node. Normally that is fine, but consider what happens right at startup. The remote node sends us an info and we update `infoStore.highWaterStamps` and then later we generate a new info which possibly has a lower timestamp due to a backward clock jump right. In fact, a large enough backward clock jump would cause the server to crash due to the max offset checks and upon restarting we're likely to run into exactly this issue. Partial corroboration for this scenario is that the most recent occurrence on sentry says the server uptime was `<10s`. Additionally, https://sentry.io/cockroach-labs/cockroachdb/?query=cluster%3A%227595e225-7350-4c3e-bb2e-4c7c51f8e96c%22 indicates that the cluster this occurred on has 24k (!!!) crashes due to clock offset.

@a-robinson and @tschottdorf Does this scenario make sense to you? Should I backport #29413 to 2.0.x?

**Comment by petermattis** [comment]
Cc @bdarnell who might have looked at this in the past as well.

**Comment by bdarnell** [comment]
@petermattis I think you've got it right. 

The first commit in #29413 might be worth backporting to 2.0, but as I just commented on that issue, I'm wary of disallowing loopback gossip (which is the part that would fix these assertions). Instead, maybe we should detect loopback gossip and advance `gossip.monotonicUnixNano` if it has a timestamp in our future. 

Or maybe we should be handling this with more aggressive clock-jump detection (#25109). Allowing the loopback gossip to advance our clock is just papering over other issues here. If the cluster is experiencing a lot of clock jumps it *should* be failing, just not here.

**Comment by petermattis** [comment]
> Or maybe we should be handling this with more aggressive clock-jump detection (#25109). Allowing the loopback gossip to advance our clock is just papering over other issues here. If the cluster is experiencing a lot of clock jumps it should be failing, just not here.

Well, the cluster where we're seeing these gossip timestamp assertions on sentry has seen only a handful of such events, and 24k max-clock offset assertions. So we're mostly catching clock jump errors elsewhere.

**Comment by tschottdorf** [comment]
Nice, thanks @petermattis!
