### ISSUE TITLE
sql: INSERT ... ON CONFLICT DO NOTHING error

### ISSUE THREAD

**Issue by baitxo** [cockroachdb/cockroach#20985]
Server log (just one node on the cluster):

```
I171221 12:42:33.080411 1 util/log/clog.go:992  [config] binary: CockroachDB CCL v1.1.3 (darwin amd64, built 2017/11/27 14:52:00, go1.9.2)
I171221 12:42:33.080411 1 util/log/clog.go:992  [config] arguments: [cockroach start --insecure]
```

Expected (PG behavior):

`INSERT ... ON CONFLICT DO NOTHING` executes normally 

Current state:

`INSERT ... ON CONFLICT DO NOTHING` raises: 
`ERROR: there is no unique or exclusion constraint matching the ON CONFLICT specification`

**Comment by jordanlewis** [comment]
@baitxo, can you give a complete example including the table schema that's being inserted into as well as example values?

**Comment by baitxo** [comment]
Hi @jordanlewis,

Hope it helps, 

```
cockroach sql --insecure -e "CREATE DATABASE insert_test" --database=insert_test
cockroach sql --insecure -e "CREATE TABLE test (user_id INT PRIMARY KEY, user_email STRING)" --database=insert_test
cockroach sql --insecure -e "INSERT INTO test VALUES (1, 'test_email') ON CONFLICT DO NOTHING" --database=insert_test
```

**Comment by glerchundi** [comment]
@jordanlewis friendly ping.

Still happening on the latest unstable release: `v2.0-alpha.20171218`.

**Comment by jordanlewis** [comment]
Sorry for the delay.

You currently need to explicitly specify the conflict columns:

```
INSERT INTO test VALUES (1, 'test_email') ON CONFLICT (user_id) DO NOTHING
```

**Comment by baitxo** [comment]
Thanks @jordanlewis!
