### ISSUE TITLE
sql: TestLogic/5node-distsql-disk/distsql_distinct_on is flaky

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#20999]
Locally, I find that it sometimes fails with the following error message:

```
-- FAIL: TestLogic/5node-distsql-disk (0.00s)
        --- FAIL: TestLogic/5node-distsql-disk/distsql_distinct_on (0.57s)
            logic_test.go:2066:
                testdata/logic_test/distsql_distinct_on:56:
                expected success, but found
                pq: while adding target n1,s1: snapshot failed: (n1,s1):?: remote declined snapshot: store busy applying snapshots and/or removing replicas
```

**Comment by RaduBerinde** [comment]
I ran into this too. The test looks fine, testing_relocate is hitting a problem. CC @benesch 

As short-term hack/fix, we could try adding `sleep 1s` between the SPLIT and TESTING_RELOCATE.

**Comment by richardwu** [comment]
I added some retry logic to logic tests (as suggested by @BramGruneir) (i.e. a `retries` directive) in #21009.

**Comment by benesch** [comment]
#21012, which pushes the retry loop into `TestingRelocateRanges`, is my alternative proposal!
