### ISSUE TITLE
Getting 503 on distributed restore

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/cockroach#20994]
**BUG REPORT**
Creating a new issue per: https://github.com/cockroachdb/cockroach/issues/19502

root@Cockroach-ApiLoadB-1VS9VT3U1E5O5-17264908.us-west-1.elb.amazonaws.com:26257/> RESTORE registration.* FROM 's3://cockroach-reg-backups/20171219?AWS_ACCESS_KEY_ID=[KEY]&AWS_SECRET_ACCESS_KEY=[KEY]';

pq: importing 708 ranges: could not find s3 bucket's region: ServiceUnavailable: Service Unavailable
    status code: 503, request id: F640BE2E747096DE, host id: +zD/sN3vBNPjY2Vf0RfGbBYwLou8A1piRK0hk2GHNmf77cBaOpvGZAbhu1z0UCJ7hQCjvsSathM=

![image](https://user-images.githubusercontent.com/894257/34268005-1751800e-e64d-11e7-8be3-3ac12d835eb8.png)

2. Please describe the issue you observed:
I ran a distributed restore from s3 and the job failed with a ServiceUnavailable (503)

**Comment by dianasaur323** [comment]
@mjibson do you mind taking a look? I think we had made a fix a while back for this error, but the error is back!

**Comment by mjibson** [comment]
The fix was never ported back to 1.1. I've opened a PR to cherrypick it.

**Comment by dianasaur323** [comment]
ah, nice! thanks matt!
