### ISSUE TITLE
SSL for all inter-node comms

### ISSUE THREAD

**Issue by andybons** [cockroachdb/cockroach#21]
from irc:
the cluster should be able to generate SSL certs (invoke openssl I guess) for internode comms as well as act as a certificate authority to generate certs for client access.
the end goal would be to allow people to set up a cockroach cluster without having to understand any of that stuff, but for larger orgs, they can specify configuration more particularly

**Comment by spencerkimball** [comment]
@MBerhault is this still under development or ready to be crossed off the list? (I know there's still endless work associated with this, but perhaps that follow on stuff should get new issues).

**Comment by MBerhault** [comment]
the inter-node part is done. I'll file different issues for client certs (the main chunk of the work left) and key management for nodes.
