### ISSUE TITLE
ui: icons aren't the same density, look like different colors

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#21006]
This is an extremely minor nit, but it has stuck out to me a few times so I guess it would fall under a UI polish issue. In the admin UI, the "database" icon seems to have thinner lines than the other three, making it look almost like its a different color.

![screen shot 2017-12-21 at 2 04 44 pm](https://user-images.githubusercontent.com/5438456/34274180-75055154-e665-11e7-9dd2-6b06b2197efa.png)

Cluster icon close-up (3px wide):

<img width="374" alt="screen shot 2017-12-21 at 3 44 29 pm" src="https://user-images.githubusercontent.com/5438456/34274714-cfd86f24-e667-11e7-8931-38241d8d6daf.png">

Database icon close-up (2px wide):

<img width="367" alt="screen shot 2017-12-21 at 3 44 20 pm" src="https://user-images.githubusercontent.com/5438456/34274723-dac1992e-e667-11e7-9c70-8171601cf602.png">

cc. @kuanluo @josueeee

**Comment by kuanluo** [comment]
Thanks for noticing, @nvanbenschoten! It's been on the list to be fixed for a while now. The latest ui clean-up by @couchand should address this issue. Assigning it to him so it can be sure to be closed in January.

**Comment by nvanbenschoten** [comment]
Thanks @kuanluo!

**Comment by couchand** [comment]
Yep, we updated all the icons except the databases one, because there was some weirdness in the SVG for that one.  This should be fixed when we get the new one in there.

Have you had a chance to look at that yet @kuanluo?

Thanks for the report @nvanbenschoten!

**Comment by kuanluo** [comment]
@couchard, I couldn't figure out why that one isn't working... I've tried to re-export the file, and I will slack them to you (when will Github support svgs...). And we can try again. Otherwise, we will have to bump up the outline to 2px, which might fix the problem.
