### ISSUE TITLE
sql: reduce allocations in show_create.go

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#21064]
Currently, there's a lot of wasteful string copying present in `show_create.go` to create the end representations of various SQL structures.

It would be better to convert everything there to use `bytes.Buffer` instead of `fmt.Sprintf` and friends. See the conversation in #20788 for more details on what the problem is.

**Comment by williamyangyt** [comment]
Hi @jordanlewis , Is this issue free? I'd like to pick it up if possible.

**Comment by jordanlewis** [comment]
Yes, please have at it!
