### ISSUE TITLE
sql: allow renaming tables between databases

### ISSUE THREAD

**Issue by XisiHuang** [cockroachdb/cockroach#2106]
`ALTER TABLE test.t RENAME to otherdb.t` will cause syntax error. 
The grammer doesn't allow the new table name contain a database prefix.

**Comment by petermattis** [comment]
@XisiHuang It should be easy to modify the grammar. We just need to change the target `name` to a `qualified_name` and adjust the `RenameTable` struct.

**Comment by XisiHuang** [comment]
Yeah, I will fix it later.
