### ISSUE TITLE
sql: hidden column is returned to client

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#21089]
The JSON column of EXPLAIN (DISTSQL) is hidden, but it is still returned to the client:

```
root@:26257/test> EXPLAIN (DISTSQL) VALUES (1);
+-----------+-----------------------------------+-------------------------+
| Automatic |               URL                 |          JSON           |
+-----------+-----------------------------------+-------------------------+
| true      | https://cockroachdb.github.io/... | {"nodeNames":["1"], ... |
+-----------+-----------------------------------+-------------------------+
(1 row)

root@:26257/test> SELECT * FROM [ EXPLAIN (DISTSQL) VALUES (1) ];
+-----------+-----------------------------------+
| Automatic |               URL                 |
+-----------+-----------------------------------+
| true      | https://cockroachdb.github.io/... |
+-----------+-----------------------------------+
(1 row)
```

**Comment by lego** [comment]
Hidden columns are only shown if they are specified in the render. This is important to be able to show the rowid _only_ when you explictly specify it, and not with `*`, as is being exhibited here.

I don't know if any action needs to be done here. Maybe the inner query needs to modify the column to be non-hidden so outer queries will render it with `*`

**Comment by RaduBerinde** [comment]
The problem isn't that the second query hides it, the problem is that the first one doesn't (which was the reason for making it hidden in the first place, and @knz said it worked as expected before so it's likely a regression).
