### ISSUE TITLE
ui: indicate restore in progress on databases page

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/cockroach#21087]
To reproduce, run a distributed restore and look at the database table. 

![image](https://user-images.githubusercontent.com/894257/34416931-daad9a26-ebc3-11e7-8200-5db5003a6e12.png)

You see the above placeholder while the restore is running
![image](https://user-images.githubusercontent.com/894257/34416958-fc45df68-ebc3-11e7-91c3-7c07e9440b8c.png)

We need a better empty/loading state (or just don't create the placeholder until the database is actually there). I'll defer to the web ui team on a solution. 

cc @josueeee

**Comment by dianasaur323** [comment]
Yes, this happens when you create an empty table and then subsequently try to restore it. We won't have time to get to it before this release, but we've talked about fixing these states in the next one.

**Comment by josueeee** [comment]
Here are some explorations: https://www.figma.com/file/NEacS7ODqlLMTIQE1VgSpHCs/Database?node-id=7%3A99
