### ISSUE TITLE
2 ranges under replicated hours after running distributed restore on v2.0-alpha.20171218

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/cockroach#21102]
I ran a distributed restore of about 18GiB on a 5 node cluster of t2.larges on AWS running v2.0-alpha.20171218. Hours after the RESTORE completed 2 of the 500+ ranges were still under-replicated. 

Note that during the restore some of the notes periodically died and where restarted.

Startup logs from one node
![image](https://user-images.githubusercontent.com/894257/34422869-514d2f1c-ebe6-11e7-9fa6-12050e1aa26a.png)

Cluster overview
![image](https://user-images.githubusercontent.com/894257/34422889-81552aa2-ebe6-11e7-87d1-82dacebaddd8.png)

Range info
![image](https://user-images.githubusercontent.com/894257/34422928-cb9ecf8c-ebe6-11e7-9180-de96f4e1ec58.png)

Full range pdf from the debug page
[Under replicated range.pdf](https://github.com/cockroachdb/cockroach/files/1592075/Under.replicated.range.pdf)

**Comment by a-robinson** [comment]
Did you happen to save the logs from this cluster? The allocator wants to create a new replica, but something must be failing along the way of actually creating the new replica.

**Comment by nstewart** [comment]
I kept the cluster alive, will send you a link

**Comment by a-robinson** [comment]
Thanks for the zip you sent! Snapshots weren't being allowed due to an issue with newly restarted nodes thinking they're behind and not ever getting caught up - https://github.com/cockroachdb/cockroach/issues/20519. It's not clear from the logs what eventually caused them to catch up, but I'll start reviewing how it works.

**Comment by a-robinson** [comment]
The under-replication is fixed by https://github.com/cockroachdb/cockroach/pull/21386. The nodes dieing during the restore still seems bad, though, and you should probably open an issue for that as well.
