### ISSUE TITLE
ui: under-replicated and unavailable range labels are not actionable

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/cockroach#21104]
Feature/enhancement request

In the alpha admin UI, we have several indicators on the overview page. Some are more FYI ie "you are using 20% of your disk capacity" whereas others may require the user to take some action ie "you have an unavailable range"

It would be great to be able to go from that problem indicator to something like the debug page (or a more end-user friendly version of that) that can help me quickly figure out what's going wrong.

For example from here:
![image](https://user-images.githubusercontent.com/894257/34423164-3ee64adc-ebe8-11e7-8209-db4d1e697728.png)

I would love a way to get to here. 
![image](https://user-images.githubusercontent.com/894257/34423193-60b9d1a6-ebe8-11e7-92b4-5178830304e2.png)

If I didn't know about the debug pages I'd be completely stuck and wouldn't have great info to give back to the CRDB team. This is, of course, part of a bigger actionability initiative for the admin ui, but noting as an issue as I ran into this when I encountered #21102

**Comment by BramGruneir** [comment]
As per the note, but I wanted to highlight this, this is also true for unavailable as well as under-replicated ranges.  I'm going to change the title of this issue to reflect that both are an issue.

**Comment by vilterp** [comment]
A few suggestions
- on range detail debug page, say table name (top table if it's an interleave hierarchy)
- on databases page (or table detail page), show count of underreplicated/unavailable ranges

**Comment by drewdeally** [comment]
The issue came about as customer noticed he had an unavailable range but could not tell how it impacted him ( amex user )
The range values were not available



I believe the situation was created by some combination of 
	system getting overloaded - and creating response issue to heartbeat or NTP bringing down CR process
	instead of restart CR process, they decommisioned and started a new process
	decommission instructions followed without wait=live and never confirmed proper removal of there node

**Comment by piyush-singh** [comment]
reproducing Drew's comment above sans sensitive info:

The issue came about as customer noticed he had an unavailable range but could not tell how it impacted him. The range values were not available. I believe the situation was created by some combination of system getting overloaded - and creating response issue to heartbeat or NTP bringing down CR process. Instead of restarting CR process, they decommissioned and started a new process. Decommission instructions followed without wait=live and never confirmed proper removal of their node.

**Comment by piyush-singh** [comment]
This is going to be a major theme for 2.2, bumping the milestone.
