### ISSUE TITLE
sql: incorrect evaluation of tuple != when NULLs are present

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#21113]
An inequality of the form `(a, b, c) != (1, NULL, 3)` is true when `(a, c) != (1, 3)` and NULL otherwise. The semantics are that NULL means "unknown value", so if `(a, c) != (1, 3)`, the condition is true for any value in NULL's place.

The following should both be true (verified against pg):

```sql
root@:26257/test> SELECT (2, 2, 3) != (1, NULL, 3);
+---------------------------+
| (2, 2, 3) != (1, NULL, 3) |
+---------------------------+
| true                      |
+---------------------------+
(1 row)

root@:26257/test> SELECT (1, 2, 4) != (1, NULL, 3);
+---------------------------+
| (1, 2, 4) != (1, NULL, 3) |
+---------------------------+
| NULL                      |
+---------------------------+
(1 row)

Time: 1.064732ms
```
CC @knz @nvanbenschoten

**Comment by nvanbenschoten** [comment]
It looks like we have the same issue with tuple equality (which is actually a good thing). The following should be false (verified against pg and mysql):
```
root@:26257/> SELECT (1, 2, 4) = (1, NULL, 5);
+--------------------------+
| (1, 2, 4) = (1, NULL, 5) |
+--------------------------+
| NULL                     |
+--------------------------+
(1 row)
```
