### ISSUE TITLE
TestSingleKey: no txn persisted, yet intent has heartbeat

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#2111]
The following test appears to have failed:

[#5940](https://circleci.com/gh/cockroachdb/cockroach/5940):

```
=== RUN TestPut
--- PASS: TestPut (22.56s)
=== RUN TestRangeReplication
--- PASS: TestRangeReplication (12.07s)
=== RUN TestSingleKey
--- FAIL: TestSingleKey (19.64s)
	single_key_test.go:125: txn "acceptance/single_key_test.go:101 func·008" id=d508bfcc key="test-key" rw=false pri=87.92241271 iso=SERIALIZABLE stat=PENDING epo=1 ts=1439565620.755168676,2 orig=1439565620.742974281,0 max=1439565620.992974043,0: no txn persisted, yet intent has heartbeat
=== RUN TestStatusServer
--- PASS: TestStatusServer (18.48s)
FAIL
ok github.com/cockroachdb/cockroach/acceptance 1337s

```
Please assign, take a look and update the issue accordingly.

**Comment by tschottdorf** [comment]
A Push finds no txn entry in the table, but the intent's Txn has a heartbeat. That likely means that the txn entry was auto-gc'ed, but it didn't commit in one round-trip, so that a concurrent actor had time to run into it and tries to push the transaction (which at that point had already been deleted).

From the above, I would suggest to just dismantle the check that triggered the above error.

**Comment by spencerkimball** [comment]
Yes, that check is clearly no longer valid.

How can an actor which encounters an intent and is able to push the attached txn distinguish between the txn having been auto-committed (meaning the intent will have been concurrently cleaned up) vs. still pending (in which case the txn record should be written as either ABORTED or with a pushed timestamp)?

**Comment by tschottdorf** [comment]
I'll post my reply in #2062 because it's relevant there.
