### ISSUE TITLE
settings: Policy for removing cluster settings

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#21129]
We're starting to remove cluster settings: #21070 removes one with a migration to remove the old value; #21078 removes one without (as of this writing) doing anything to clean up the old value. We should be consistent about this, and either always clean up the old value or never do so (if the latter, we should probably keep some record of previously-used settings so we don't reintroduce new uses of old names in the future).

**Comment by spencerkimball** [comment]
I've added a migration to my PR. I think we should remove them. Where should this policy be stated?

**Comment by bdarnell** [comment]
`pkg/settings/doc.go`?
