### ISSUE TITLE
sql: type checking improvements

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#21123]
This is grab bag of observations from looking at the type checking code recently. Some of the observations may be misplaced, but I thought it best to capture them somewhere while they were fresh on my mind.

The type checking code currently works on scalar expressions, transforming `tree.Expr` to `tree.TypedExpr`. Type checking is much more than just checking types: it involves inferring types for untyped constants and placeholders by looking at their usage and having knowledge of the overloaded operations. For a simple example, `a + b` could involve adding two integers, two floats, two decimals, an integer and a decimal, etc. Type checking both determines the types of `a` and `b` and verifies that there is a valid overload for the operation.

The type checking algorithm and heuristics use intimate knowledge of the `sql/sem/tree.Expr` structures. This intimate knowledge is apparent in places like `typeCheckComparisonOp` which has specialized code for the right-hand side of the comparison. For example, there is special handling if the operator is `In` and the right-hand side is `*tree.Tuple`. This is necessitated for type inference, but tightly couples the code. Note that `a IN b` is handled differently depending on whether `b` is `*tree.Tuple` or `*sql.subquery`.

Separate from the intimate knowledge of `sql/sem/tree.Expr`, is intimate knowledge of the concrete types. For example, `typeCheckSameTypedTupleExprs` has a special case if the desired type is `types.TTuple`. This tight coupling prohibits extension (i.e. adding a new tuple-like type). Rather, the `types.T` interface should be able to specify attributes that allow the type checking code to make its decisions without inspecting the concrete type.

As mentioned earlier, type checking works on scalar expressions, leaving typing of relational expressions to higher level code. Relational expressions have types too and these types integrate with scalar expressions via subqueries. Currently this integration happens outside of the type checking code. See `sql/subquery.go` and the various calls to `analyzeExpr()`. At a high-level, it would be more intuitive to type check a relational expression which would recursively type check all of the scalar expressions. In the near term, we should keep this in mind while developing `sql/opt` and consider given all `sql/opt.expr` nodes a type. For relational expressions, the type would be either a tuple of the column types or something like `types.TTable`.

Cc @nvanbenschoten, @knz, @RaduBerinde 

Jira issue: CRDB-5900

**Comment by knz** [comment]
Your analysis so far is correct.

> At a high-level, it would be more intuitive to type check a relational expression which would recursively type check all of the scalar expressions.

Yes I agree. The current structure of the code is a historical artifact, and this interleaving of plan building and type checking has made our life more difficult than necessary. I'd like new code to avoid this.

> we should keep this in mind while developing sql/opt and consider given all sql/opt.expr nodes a type. For relational expressions, the type would be either a tuple of the column types or something like types.TTable.

:+1: :sparkling_heart: :sparkling_heart: :sparkling_heart: :sparkling_heart:

**Comment by petermattis** [comment]
> Yes I agree. The current structure of the code is a historical artifact, and this interleaving of plan building and type checking has made our life more difficult than necessary. I'd like new code to avoid this.

One complexity is that name resolution needs to take place before type checking. And name resolution more naturally happens when we have the relational tree structure (I suppose it could be done directly on the AST, but we'd need side structures to augment the name lookup). This makes me think that there might be a Typing v3 someday that works on something like the `expr` tree.

**Comment by knz** [comment]
I stand by my earlier statement that there is no need for the current 'tree' data structures when 'expr' exists and that the parser should produce that directly. So yes type checking, constant folding and name resolution need to adapt accordingly. It's for the better and I don't even think it's going to be painful.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by petermattis** [comment]
> So yes type checking, constant folding and name resolution need to adapt accordingly. It's for the better and I don't even think it's going to be painful.

Getting rid of the `sql/sem/tree` structures will involve a lot of work that I wouldn't want to make a prerequisite of the planner work. While you mentioned constant folding, the more general work item is expression evaluation. There are also various scalar expression normalizations that would need to be converted. I wouldn't describe any of this as particularly painful work, but it will take a while.

**Comment by nvanbenschoten** [comment]
> Rather, the types.T interface should be able to specify attributes that allow the type checking code to make its decisions without inspecting the concrete type.

Could you expand more on what you mean by attributes? Back when we were looking into typing v2 we spent some time considering a Hindley-Milner-inspired approach, where typing checking would iteratively refine expression types through propagated type constraints. Is this what you have in mind?

Another way to take this is that we would introduce a notion along the lines of type families and use this throughout our type checking algorithm. I know @knz has some ideas and strong opinions here.

> At a high-level, it would be more intuitive to type check a relational expression which would recursively type check all of the scalar expressions.

We've discussed this in the past and I think we're all on-board with moving to an approach like this. The current type checking limitations at subquery boundaries continues to be pretty painful.

**Comment by petermattis** [comment]
> Could you expand more on what you mean by attributes? Back when we were looking into typing v2 we spent some time considering a Hindley-Milner-inspired approach, where typing checking would iteratively refine expression types through propagated type constraints. Is this what you have in mind?

Currently the `types.T` interface allows checking for equivalence and family equivalence. I was imagining something where it could also provide info about structure. For example, `T.Children()` could return child types so that `tuple{A,B,C}` would have children `A`, `B`, `C`. I'm not at all sure what this would look like in practice.

**Comment by knz** [comment]
The idea of "children" is only well-defined for ordered aggregate types, and that's very specifically tuples and arrays. 

The more general idea is to say that some types have parameters that constrain their definitions. How these parameters are used "internally to the type" can change per-type. But we could imagine an interface to retrieve the parameter(s) of a type.
