### ISSUE TITLE
Import CSV with nodelocal

### ISSUE THREAD

**Issue by leomkkwan** [cockroachdb/cockroach#21136]
Try to import a csv file into CRDB.

On v1.1.3, the import was successful; however, on 2.0, this will run into error

IMPORT TABLE t_baseallid (bid INT PRIMARY KEY, email STRING) CSV DATA ('nodelocal:///home/leo/bid.csv') WITH temp = 'http://192.168.8.22:2015/dfs/d2/upload/';

pq: nodelocal:///home/leo/bid.csv: open /home/leo/cockroach/d1/extern/home/leo/bid.csv: no such file or directory

**Comment by dianasaur323** [comment]
@leomkkwan we made some changes to our nodelocal syntax in our 2.0 release to prevent users from using nodelocal incorrectly. Do you mind trying the syntax referenced here? https://github.com/cockroachdb/cockroach/pull/19326

**Comment by leomkkwan** [comment]
IMPORT TABLE t_baseallid (bid INT PRIMARY KEY, email STRING) CSV DATA ('nodelocal:///bid.csv') WITH temp = 'http://192.168.28.8:2015/home/leo/caddy/';
 works!

May be I am wrong. It's now need all nodes to have the file under the extern directory. Previously, only the node doing import need to have that file.

Thanks for the quick response!!!! Happy New Year!!!

**Comment by dianasaur323** [comment]
@leomkkwan excellent! Precisely, all nodes need to have access to the file, not just the one running the import job. happy new year! I'll close this issue for now, but feel free to reach out with further questions.
