### ISSUE TITLE
cli: open RocksDB in ReadOnly mode for debug commands

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#21130]
Cockroach supports a number of debug commands that inspect an existing store directory. The commands include `debug key`, `debug range-data`, `debug raft-log`, and many others (see `cockroach debug --help`). None of these commands will actually modify the store, they just scan over its contents.

These seem like cases where we should be opening the underlying RocksDB database in ["read-only mode"](https://github.com/facebook/rocksdb/blob/b5c99cc908a7e34fa65d588b2706c33000786935/include/rocksdb/db.h#L123). Read-only mode provides a few benefits for these use cases:
1. No compactions or other unexpected background tasks will be performed.
2. Multiple processes can operate on the store at once if they are all in read-only mode. This means that multiple debug commands could be run concurrently.
3. Reads from the store should generally be faster because read-only mode allows RocksDB to [bypass a number of locks](https://github.com/facebook/rocksdb/wiki/RocksDB-Basics#readonly-mode).
4. Once the store is set in read-only mode, there's less of a chance that a bug in the debug commands could accidentally modify the store.

**Comment by pocockn** [comment]
Hi there, I was looking into this. Need a few pointers to get me started. Would this involve editing the function 'openExistingStore' withing debug.go and using the NewReadOnly() function within the package engine, file rocksdb.go? Thanks!

**Comment by nvanbenschoten** [comment]
Thanks for the interest @pocockn. You're on the right track with `openExistingStore`. I think you'll want to add a `ReadOnly` flag to `engine.RocksDBConfig` and set it in that function. You'll then need to plumb the flag down into C++ through `C.DBOptions`, where `C.DBOpen` can finally decide whether to call `rocksdb::DB::Open` or `rocksdb::DB::OpenForReadOnly `.

**Comment by pocockn** [comment]
Thanks, will look into this more tomorrow

**Comment by pocockn** [comment]
I've added the read_only flag to the C.DBOptions in rocksdb.go, there is a DBOptions within libroach.h do I add the new flag here? Or I can see there's another DBOptions struct in options.h? Is there an easier place to have a quick chat then Github? Thanks

**Comment by nvanbenschoten** [comment]
@pocockn You're going to want to add the flag to the struct in libroach.h.

I'm away from a computer for the next few days but after that we can hop on gitter if you'd like.

**Comment by pocockn** [comment]
Cool, that's where I added it. 

That would be great.

**Comment by pocockn** [comment]
Hey when would be a good time to jump on gitter and have a chat about this?

**Comment by nvanbenschoten** [comment]
@pocockn I reached out to you on gitter 😃
