### ISSUE TITLE
sql: Interval operator symmetry

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#21145]
The `*` operator for multiplying an interval by a scalar is defined inconsistently for ints and floats. For ints, the operands can be in either order, but for floats, the interval must be the first argument.

https://github.com/cockroachdb/cockroach/blob/a188d42c0f9c3114c82799b598626f975b36456f/pkg/sql/sem/tree/eval.go#L855-L879

Note that `select 2.0 * interval '1 second'` works, I guess due to different type inference rules for untyped literals, but `select float '2.0' * interval '1 second'` doesn't. 

We should make sure that all of the mixed-type `+` and `*` operators support operands in either order. 

(The user who reported this was trying to multiply an interval by a decimal, which we don't support at all. Should we? It's a difference from postgres, and within the domain of intervals the loss of precision from `decimal * interval -> interval` doesn't bother me as much as with raw numbers)

**Comment by MohamedElqdusy** [comment]
Hi @bdarnell, I'm working on this issue.
After I have implemented `float * interval -> interval` , I found that `select 2.0 * interval '1 second'` didn't work any more with an output `pq: unsupported binary operator: <decimal> * <interval>  `, so I have implemented `decimal * interval -> interval` and `interval * decimal -> interval`. I have made a check list for all the mixed-type `+` and `*` operators are exciting in either order.
