### ISSUE TITLE
ui: retitle Node Liveness to Node Status

### ISSUE THREAD

**Issue by couchand** [cockroachdb/cockroach#21156]
From chat:

> [10:46 AM] Nate Stewart
> ![pasted image at 2017_12_28 11_45 am](https://user-images.githubusercontent.com/793969/34490808-a72c5520-efa6-11e7-9d38-dd57a409d0a6.png)
> Thoughts on calling this “node status” rather than “liveness”? I feel like status is easier to understand and its consistent with how we handle replication. we also don’t have the word “liveness” in the documentation
>
> [12:37 PM] Ben Darnell
> +1. "liveness" is a weird word that somehow stuck in our code, but we don't need to be showing it to users

**Comment by couchand** [comment]
@nstewart @bdarnell What about the Distributed Dashboard?

![screen shot 2018-01-02 at 10 23 16 am](https://user-images.githubusercontent.com/793969/34490959-32ca2bfc-efa7-11e7-9dd3-e20d479438f2.png)

**Comment by nstewart** [comment]
I'll defer to @bdarnell for that report

**Comment by bdarnell** [comment]
I'd probably remove the word "liveness" and just call those "node heartbeats".
