### ISSUE TITLE
sql: Support user/role-level defaults for session variables

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#21151]
In postgres, any session variable can be set at the [user/role level](https://www.postgresql.org/docs/current/static/sql-alterrole.html) so it will be set automatically when that user connects. For example, this could be used to set a user-scope default time zone without changing the global default from UTC or dealing with the raciness of cluster settings. 

    ALTER USER foo SET timezone='America/New_York';

This is especially useful because postgres drivers don't typically have the facility to automatically issue a `SET TIME ZONE` command at the start of each session (a feature which is commonly found in mysql drivers, for example). 

Epic CRDB-2507

**Comment by vy-ton** [comment]
Another use case that comes up is being able to configure `statement_timeout`, `idle_in_session_timeout`, or `idle_in_transaction_session_timeout` for different roles associated with different workloads.

**Comment by awoods187** [comment]
The lack of flexibility in settings these on a user/role basis has come back to limit us a few times now.

**Comment by bdarnell** [comment]
Another example is in the recurring debate between @andy-kimball and myself about how disruptive it is to close a client connection. One reason that postgres drivers don't have good ways to reestablish session variables after a connection reset is because in postgres you can set these variables on the user/role.

**Comment by knz** [comment]
copy-pasting my comment from elsewhere:

When looking at this the importance of role-level (or db-level, or application_name-level) settings should not be underestimated. An implementation restricted to user-level configs would not be sufficient.

This is important to consider, because the security best practice would be to use different SQL user accounts within the same client app, to distinguish privilege groups, and a lack of shared configurability dicincentivizes that.

**Comment by bdarnell** [comment]
Yes, it should cover both users and roles (I don't think we supported roles at the time this issue was created). 

I'm not sure about db or appname-level settings. I could see it being useful, but it brings us farther away from postgres compatibility (while user and role settings bring us closer). The more places we have to define settings, the trickier it becomes to define precedence and avoid surprises.

**Comment by ajwerner** [comment]
The Postgres docs are quiet on how defaults for session variables get inherited. It's a tough problem because a user may be granted many roles. How would we decide which setting to use if there are conflicts. My guess (haven't tested) is that Postgres doesn't try.

**Comment by rafiss** [comment]
It looks like there is a `pg_roles.rolconfig` where the defaults are stored. https://www.postgresql.org/docs/current/view-pg-roles.html

I'll check out the behavior with inherited roles / conflicts.

**Comment by rafiss** [comment]
Postgres does not implement inheritance of session variable defaults. 

SQL Experience will start work on this in the June milestone.
