### ISSUE TITLE
acceptance: Disable crash reporting

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#21158]
The acceptance tests create clusters with reporting enabled. For example, [this issue](https://sentry.io/cockroach-labs/cockroachdb/issues/427178392/) was a failure in an acceptance test (in the 1.0.5 cluster created to test version upgrades). Node failures in acceptance tests matter, of course, but they should be reported through the test runner instead of going out to sentry. Most of the acceptance tests use the current build which has reporting disabled automatically since it's a non-release build. The version upgrade test may be the only one affected by this.

**Comment by jordanlewis** [comment]
I think this is already done, right @dt?
