### ISSUE TITLE
sql: efficiently dealing with LIMIT in DistSQL.

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#21167]
Complete implementation of LIMIT in distsql as described in 
https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20170602_distsql_limit.md

**Comment by solongordon** [comment]
Current status of this: I've implemented the short-term proposal in the RFC for hard limits only. Next up would be soft limits, which are somewhat more complicated because they require a new control mechanism so the table readers will not scan too eagerly.
