### ISSUE TITLE
storage: "IO error" crash in addSSTablePreApply

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#21162]
Perhaps we don't care to better handle I/O errors in this code, but I'm not familiar enough with the intent to say for sure. We cared about https://github.com/cockroachdb/cockroach/issues/17817, at least.

https://sentry.io/cockroach-labs/cockroachdb/issues/424234836/

```
*log.safeError: stopper.go:179: IO error
  File "github.com/cockroachdb/cockroach/pkg/storage/replica_proposal.go", line 612, in addSSTablePreApply
  File "github.com/cockroachdb/cockroach/pkg/storage/replica.go", line 4408, in processRaftCommand
  File "github.com/cockroachdb/cockroach/pkg/storage/replica.go", line 3481, in handleRaftReadyRaftMuLocked
  File "github.com/cockroachdb/cockroach/pkg/storage/store.go", line 3183, in processRaftRequest
  File "github.com/cockroachdb/cockroach/pkg/storage/store.go", line 3541, in processRequestQueue
...
(5 additional frame(s) were not displayed)

stopper.go:179: IO error
```

**Comment by bdarnell** [comment]
> Perhaps we don't care to better handle I/O errors in this code

Depends on the kind of I/O error. If it's a file descriptor limit like #17817 was, that's generally within our control and we want to handle it better. Most other IO errors (out of space, the disk failed, permissions are broken, someone deleted a directory out from under us, etc) we can't really handle any better and we currently want to panic/fatal.

**Comment by tschottdorf** [comment]
2.0 will report more details of that message, so we should defer action until then. This is likely either out of space or open files exceeded as @bdarnell suggested.

**Comment by tschottdorf** [comment]
^- #20104 is what I mean specifically. I'm going to kick this back to @a-robinson but I don't think there's much we need to do here except keep watching sentry after 2.0 and making sure the errors are better in practice -- not sure we need to keep this issue open for that since we're doing so anyway.

**Comment by a-robinson** [comment]
Thanks @tschottdorf. You're right, since future reports will include more info we can take action as they arise.
