### ISSUE TITLE
Roadmap link in the README doesn't work

### ISSUE THREAD

**Issue by alex** [cockroachdb/cockroach#2120]
It goes to the "create a new wiki" page.

**Comment by bdarnell** [comment]
We're in the process of updating our roadmap; we deleted the wiki page which was quite out of date but forgot to look for links to it. We'll get the updated version online in the next week.

**Comment by alex** [comment]
In the meantime, could you replace the link in the README with a "coming soon"?

**Comment by tschottdorf** [comment]
I've re-added the page with a placeholder. We'll replace it shortly.

**Comment by jess-edwards** [comment]
I've updated the Roadmap to direct here: https://github.com/cockroachdb/cockroach/issues/2132

**Comment by alex** [comment]
Thanks!
