### ISSUE TITLE
logictest: --rewrite-results-in-testfiles is broken

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#21204]
Running the logictests with `--rewrite-results-in-testfiles` should generate no diffs on `master`. It is used to update tests when something changes a lot of them.

Currently it generates a diff like this on `cascade`:

```diff
-# LogicTest: default parallel-stmts distsql
-
-subtest DeleteCascade_Basic
+### Delete cascade double self reference
+# se
 ### Basic Delete Cascade
 #     a
 #    / \
@@ -96,7 +95,6 @@ DROP TABLE b1;
 statement ok
 DROP TABLE a;
 
-subtest DeleteCascade_PrimaryKeys
...
-subtest DeleteCascade_CompositeFKs
...
```
This is likely due to the recent changes around subtests.

**Comment by BramGruneir** [comment]
Ah, we'll have to add back in the subtest lines, shouldn't be tough. 

How quickly is this needed?  I can try to work on it on Friday.

**Comment by RaduBerinde** [comment]
That part is easy. I'm still not understanding how that top comment gets screwed up though (it's a comment from further down in the file)

I can take care of the changes since I'm working with this flag right now.

**Comment by RaduBerinde** [comment]
Ah, I think there's something bad going on when passing `bytes.Buffer` by value. The internal slice can point to the array inside `bytes.Buffer` which doesn't get updated correctly when we copy it.
