### ISSUE TITLE
distsql: investigate reducing memory allocations between processors

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#21222]
Due to the use of `RowChannel` as glue between processors on a node (see #20550), `ProcOutputHelper.ProcessRow` currently transfers ownership for the row being output to the `RowChannel` which passes that ownership on to the next processor. The downstream processor that consumes the row and usually discards the memory immediately. The effect is a steady stream of allocations for rows at upstream processors which the GC needs to keep up with: otherwise known as GC pressure.

Local SQL processing takes a different approach to ownership between execution nodes:

```
	// Values returns the values at the current row. The result is only valid
	// until the next call to Next().
	//
	// Available after Next().
	Values() tree.Datums
```

Allowing the processor to reuse the memory for an output row significantly reduces allocations. The downstream processor needs to copy the row if it doesn't consume it immediately, but often times this copying can occur naturally. Changing the semantics of `RowSource.Next` would be a heavy lift, but we can probably have processors implement an optional interface and provide glue for processors which expect ownership to be transferred to the downstream.

The expectation is that this will be a significant performance improvement. The micro-benchmarks of the processors show that GC is the top cpu consumer and the majority of allocations are happening in `ProcOutputHelper.ProcessRow`.

**Comment by jordanlewis** [comment]
This was closed by #24589.
