### ISSUE TITLE
distsql: refactor processors to implement RowSource

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#21220]
This issue tracks the work remaining to have all distsql processors implement `RowSource`.

- [x] `aggregator` [#21147]
- [x] `algebraicSetOp` [#21560]
- [x] `distinct` [#20584]
- [x] `hashJoiner` [#27706]
- [x] `mergeJoiner` [#21219]
- [x] `interleavedReaderJoiner` [#27641]
- [x] `joinReader` [#27038]
- [x] `noopProcessor` [#21147]
- [x] `tableReader` [#20584]
- [x] `sorter` [#21703]
- [x] `valuesProcessor` [#20584]

The `*Backfiller` processors are lower priority because they are not involved in user queries, only schema changes:

- [ ] `columnBackfiller`
- [ ] `indexBackfiller`

The `sample*` processors are lower priority because they are not involved in user queries, only statistics collection:

- [ ] `sampleAggregator`
- [ ] `samplerProcessor`

Distributed CSV import processors are also lower priority:

- [ ] `readCSVProcessor`
- [ ] `sstWriter`

**Comment by jordanlewis** [comment]
Going to close this as we've finished all of the major processors.
