### ISSUE TITLE
distsql: investigate "unfusing" selection, projection and limit from processors

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#21221]
All distsql processors support "fused" selection, projection and limit processors via `ProcOutputHelper`. The processing of "selection", "projection" and "limit" takes place in `ProcOutputHelper.ProcessRow`. Rather than always checking for whether "selection", "projection" and "limit" are present, we could wrap a `RowSource`-style processor with `selection`, `projection` and `limit` processors during flow setup. 

The effect of such unfusing should be identical and there is unlikely to be a performance impact one way or the other. The benefit to doing so is that it aligns the distsql processors more naturally with the local sql processors.

**Comment by jordanlewis** [comment]
It seems unlikely we'll get to this.
