### ISSUE TITLE
ui/debug: Range debug page should link to the correct CommandQueue viz page

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#21239]
The range debug page attempts to only show a link to the leader's CommandQueue viz page. Unfortunately, clicking on this link brings us to the current gateway's CommandQueue viz page, which may not be the leader and may not even contain a replica in the range. The former will show an empty CommandQueue (almost always, although it is technically possible for a follower to have commands in its CommandQueue) and the latter will throw an error (see https://github.com/cockroachdb/cockroach/issues/21238). This should be improved. There are two things we can do here:
1. The gRPC-gateway endpoint could internally redirect to the leaseholder's node which would in-turn look for the `Range` in its `Store`. This would allow all admin UI gateways to be useful, not just the leaseholder's admin UI gateway.
2. The link could redirect to the correct admin UI gateway. 

The first option is probably better as it fits with how this kind of thing is done in other places. The only downside is that it may be tricky to guarantee that we'll end up redirecting to and reading from the `CommandQueue` of the correct `Replica`.

**Comment by couchand** [comment]
Since we don't control the user's network topology, we can't reliably do the second option (there may only be one node's admin UI exposed, or they could be behind a load balancer, for instance), so we'll have to go with the first option.

@nvanbenschoten can you clarify what's tricky about making sure we're sending the request to the right node?  Also, can you clarify if this should be the raft leader or the leaseholder (or is that part of why it's tricky)?

**Comment by nvanbenschoten** [comment]
> can you clarify what's tricky about making sure we're sending the request to the right node

The tricky part is that the redirect may race with the leaseholder moving from node to node, so we may end up chasing the lease around. This isn't a huge concern though, as it should be rare.

> can you comment on how valuable this page is likely to be for debugging issues in the field

I don't think this is critical for 2.0. Moving to 2.1.

**Comment by vilterp** [comment]
@a-robinson suggests following the (clumsy but effective) pattern from `EnqueueRange` and others, which just forwards the request to every node.

**Comment by vilterp** [comment]
This page is deleted in #32865
