### ISSUE TITLE
ui: problemranges page never loads on local cluster

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#21236]
If I start a local cluster from scratch on current master (fa9a248617ffe4ab06f22c3b5cfef9165091a9a4) with fresh data directories and try to load the problemranges page, it hangs forever during the "Loading cluster status..." phase. There are no errors in the console.

I also saw this behavior when running on a 3-node cluster that had data in it when one node was down.

**Comment by a-robinson** [comment]
And to be as specific as possible, by "local cluster" I mean I ran these three commands in separate terminals:

```
./cockroach start
./cockroach start --port=26258 --http-port=8081 --join=localhost --store=cockroach-data2
./cockroach start --port=26259 --http-port=8082 --join=localhost --store=cockroach-data3
```

and tried to load https://localhost:8080/#/reports/problemranges

**Comment by a-robinson** [comment]
It's also failing to load on a roachprod cluster - ping me if you want to look directly at it sometime in the next day or two. It'd be really nice to get this fixed, since it is a really valuable page.

**Comment by a-robinson** [comment]
I see a few of these errors in the logs from the node I was connected to:

```
W180116 23:59:08.493727 7370677 server/server.go:1450  [n1] error closing gzip response writer: http: request method or response status code does not allow body
```

**Comment by dianasaur323** [comment]
I'm also having the same problem, which is odd because this cluster previously did show the problem ranges page successfully, and I haven't updated the version.

**Comment by BramGruneir** [comment]
Weird.  I'll take a look today.
