### ISSUE TITLE
ui/debug: CommandQueue viz page should display errors

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#21238]
Errors on the `/reports/range/<rangeID>/cmdqueue` page are not displayed to the user. Instead, the page will continuously say "loading..." (see attached image). These errors can occur for a number of reasons, including that we're talking to a node that does not contain a replica in the range. We should display these errors prominently.

![screen shot 2018-01-04 at 2 45 44 pm 2](https://user-images.githubusercontent.com/5438456/34581385-32c899c8-f15e-11e7-9396-685577a9aee5.png)

**Comment by vilterp** [comment]
Note: there isn't a consistent pattern for displaying loading and error indicators in admin UI pages. This is another place where a `Loader` component or some other pattern could be used.
