### ISSUE TITLE
sql: clarify error message on ambiguous ON CONFLICT

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#21249]
```
qWrite := fmt.Sprintf(`INSERT INTO %s VALUES ($1, $2) ON CONFLICT(k) DO UPDATE SET v = v + 1`, table)
```

```
Error: pq: column reference "v" is ambiguous
```

This could be clearer -- user needs to specify either `excluded.v` or `theirtable.v`; the error message could point that out.

**Comment by nvanbenschoten** [comment]
+1 For what it's worth, we've seen users get confused by this as well.

**Comment by andreimatei** [comment]
I'm not a very good target. @jordanlewis you want it?

**Comment by jordanlewis** [comment]
```
root@:26257/test> insert into x values(1,2) on conflict (a) do update set a=a+1;
pq: column reference "a" is ambiguous (candidates: excluded, x)
```

How's that?

**Comment by andreimatei** [comment]
SGTM !

**Comment by bdarnell** [comment]
The name `a` is referenced three times in that statement (and twice in the one in the first message). What could we do to point out that it's the last one that the message refers to?
