### ISSUE TITLE
sql: normalize = ANY to IN

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#21240]
`= ANY (SELECT ..)` is equivalent to `IN (SELECT ..)`. We should perform this normalization.

**Comment by knz** [comment]
cc @andy-kimball for prioritization

**Comment by RaduBerinde** [comment]
With the optimizer, these currently get built to the same underlying operator.

**Comment by knz** [comment]
Great. If there's a test for it already, then the issue can be closed.

**Comment by andy-kimball** [comment]
This is a tested part of the new optimizer.
