### ISSUE TITLE
sql: revisit TTuple use for subqueries

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#21273]
Consider `a IN (SELECT x FROM t` or `a < ALL(SELECT x FROM t)` (say `a, x` are INTs). In our current code, the type of the subquery (`sql.subquery` tree.Expr node) is `TTuple{Int}`.

This feels wrong. `TTuple` is the type of a tuple. The tuple `(1, 2)` has the type `TTuple{Int, int}`; the tuple `(1, 2, 3)` has the type `TTuple{Int, Int, Int}`. If we think of the results of the subquery as a tuple, we don't know how many members there are, so we can't have a "correct" `TTuple` type for it. `TTuple{Int}` is the type of a single-element tuple.

In addition, `TTuple` allows each value to have a different type (e.g. `(1, 'a')`); in our case they necessarily have the same type.

Finally, this allows queries like `a < ALL(1, 2, 3)` which is invalid in postgres.

We should be using a `TTable` or a new special type instead (or perhaps a `TArray`?).

This is mentioned in this TODO in [subquery.go](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/subquery.go#L450):

```go
	if multiRow {
		// The subquery is in a multi-row context. For example:
		//
		//   SELECT 1 IN (SELECT * FROM t)
		//
		// Wrap the type in a tuple.
		//
		// TODO(peter): Using a tuple type to represent a multi-row subquery works
		// with the current type checking code, but seems semantically incorrect. A
		// tuple represents a fixed number of elements. Instead, we should either
		// be using the table type (TTable) or introduce a new vtuple type.
		result.typ = types.TTuple{result.typ}
	}
```

There is some related validation missing in `ComparisonExpr.memoizeFn` (used by `NewTypedComparisonExpr*`):

```go
func (node *ComparisonExpr) memoizeFn() {
...
	case Any, Some, All:
...
		case types.TTuple:
			// For example:
			//   x = ANY(SELECT y FROM t)
			//   x = ANY(1,2)
			rightRet = t[0]
		}
	}
```
In this code we should be asserting that the types of the tuple are the same. This is more tricky than it first appears, because some of the types might be NULL, e.g. `SELECT x = ANY(1, 2, NULL)`. Simply ignoring NULLs is not enough either, we could have tuples of tuples like `((1, NULL), (NULL, 2))`; we would need recursive logic similar to `TypeCheckSameTypedExprs` to validate this correctly.

**Comment by RaduBerinde** [comment]
CC @petermattis @knz

**Comment by petermattis** [comment]
Duplicate of #21124?

**Comment by RaduBerinde** [comment]
Ah, indeed.
