### ISSUE TITLE
sql/opt: bug with index selection for `WHERE b`

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#21271]
Prior to #21270, the `aggregate` logic test contained:

```
statement OK
DELETE FROM bools WHERE b

query BB
SELECT BOOL_AND(b), BOOL_OR(b) FROM bools
----
false false
```

The `SELECT` is failing because the `DELETE` statement is failing to delete any rows. The problem appears to be with the `WHERE b` clause because `SELECT * FROM bools WHERE b` fails to match any rows even though `SELECT * FROM bools` shows that there are 3 rows containing `true`.

Disabling the new index selection code via `const useExperimentalIndexConstraints = false` also allows the `DELETE` to work, presumably because we're scanning the entire table.

**Comment by petermattis** [comment]
We figured out in #21270 that the problem was caused by a missing `MakeDBool` causing "uninterned" bools to be used. But it is still curious that an "uninterned" bool caused the new index selection code to do something different than the old code. Especially since there isn't an index on the table in question. Radu suspects something with the code to trim the filter, but we're not precisely sure what the difference is.

**Comment by RaduBerinde** [comment]
It looks like the difference is in the processing of the expression that the old code did. With the old code
```
I180106 14:42:29.137669 20 sql/logictest/logic.go:770  SELECT * FROM bools WHERE b;
Remaining filter: b = true
```
With the new code:
```
I180106 14:35:23.771817 11 sql/logictest/logic.go:770  SELECT * FROM bools WHERE b;
Remaining filter: b
```

These are both valid so it's not a bug, but this explains why the `MakeDBool` problem manifested this way.
