### ISSUE TITLE
distsql: support apply

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#21302]
Correlated subqueries can be transformed into variants of joins where the right input depends on values from the left input. Consider the query:

```
SELECT * FROM a WHERE EXISTS (SELECT * FROM b WHERE a.x = b.x)
```

Straightforward translation to something like the relational algebra results in:

```
select
 ├── columns: a.x:int a.y:int
 ├── filters
 │    └── exists [type=bool]
 │         └── select [outer=(0)]
 │              ├── columns: b.x:int b.z:int
 │              ├── filters
 │              │    └── eq [type=bool]
 │              │         ├── variable (a.x) [type=int]
 │              │         └── variable (b.x) [type=int]
 │              └── inputs
 │                   └── scan
 │                        └── columns: b.x:int b.z:int
 └── inputs
      └── scan
           └── columns: a.x:int a.y:int
```

The optimizer will transform the correlated subquery into an `apply` variant:

```
semi-join (apply)
 ├── columns: a.x:int a.y:in
 └── inputs
      ├── select
      │    ├── columns: a.x:int a.y:int
      │    └── inputs
      │         └── scan
      │              └── columns: a.x:int a.y:int
      └── select
           ├── columns: b.x:int b.z:int
           ├── filters
           │    └── eq [type=bool]
           │         ├── variable (a.x) [type=int]
           │         └── variable (b.x) [type=int]
           └── inputs
                └── scan
                     └── columns: b.x:int b.z:int
```

In this case, the `apply` variant is a [`semi-join`](https://github.com/cockroachdb/cockroach/issues/19450) (which we also need to add support for). The optimizer will attempt to eliminate the `apply`, replacing it with a plain `semi-join` in this case, but the optimizer might fail to do so.

Additionally, sometimes apply is the most efficient execution plan, similar to the way [`nested-loop join`](https://github.com/cockroachdb/cockroach/issues/21301) is sometimes the most efficient join.

In order to execute an `apply` operation directly, we need to read rows from the left side and for each row execute the query on the right side. Note the right query will already have been planned, but we may need to perform index span generation. (@RaduBerinde I think we wouldn't want to go through full index-selection, but can we parameterize index selection on something akin to a placeholder?)

**Comment by RaduBerinde** [comment]
> I think we wouldn't want to go through full index-selection, but can we parameterize index selection on something akin to a placeholder?

I'd have to think on it more thoroughly. I think it's hard to parametrize the index spans in general, there would still need to be some post-processing to intersect or merge spans. For simple conditions sure, but for those rerunning the index constraints code is not a big deal. I could see leaving behind some information from index constraint generation and reusing pieces that aren't affected.

There is still the question of how to choose the correct index.. the index selection code would need to convey that an index is useful even though it can't generate spans without the values. A simple initial solution would be to replace the unknown values with some arbitrary values during initial planning. These could be a class of special Datums (which would be treated differently when consulting stats/histograms).

**Comment by petermattis** [comment]
> A simple initial solution would be to replace the unknown values with some arbitrary values during initial planning. These could be a class of special Datums (which would be treated differently when consulting stats/histograms).

Could we use `Placeholder` here?

**Comment by RaduBerinde** [comment]
Perhaps. The code will have to have separate cases depending on `EvalCtx.HasPlaceholders`.

**Comment by jordanlewis** [comment]
This is subsumed by #25658 and #25678, I think. Feel free to re-open if not.
