### ISSUE TITLE
build: the docker images use unsecure http for apt

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#21311]
Found via `https://teamcity.cockroachdb.com/viewLog.html?buildId=471016&buildTypeId=Cockroach_UnitTests`

The `apt-get` commands used by e.g. `verify-archive.sh` use a `apt.sources.list` with `http` archive URLs instead of `https`.

**Comment by bdarnell** [comment]
AFAIK, this is still standard practice for `apt-get`. You have to jump through some hoops to enable https; it's not just a matter of switching the URLs. ([SO](https://unix.stackexchange.com/questions/90227/why-there-is-no-https-transport-for-debian-apt-tool)  `apt-get` verifies its downloads with GPG even when using HTTP, so it's not as insecure as it looks.

**Comment by knz** [comment]
I had missed the note about the GPG signature verification. Nothing to see here.
