### ISSUE TITLE
security: determine username format and enforce

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#2131]
The only requirement on usernames for now is non-empty.
We should establish the constraints on user names and enforce them in the following places:
- client cert generation
- user entry in the global user config
- privileges in the database/table descriptors

We may also need to tie the above three together to ensure consistency. This may involve requiring all users to be defined in the global config.

Some things to be aware of:
- avoid reserved users: `root`, `node` (and potentially a yet-to-be-defined `PUBLIC` user)
- sql grammar: currently defined as `name: IDENT | unreserved_keyword | col_name_keyword`

**Comment by mberhault** [comment]
I believe this is 1.0, along with all user-related stuff (web authentication, password-based pg authentication, etc...).
Some of this does apply to the sql syntax and certs, so we may want to think about it sooner.

**Comment by spencerkimball** [comment]
@mberhault I assume this isn't going into 1.0. Reassign the milestone if you disagree.

**Comment by mberhault** [comment]
this particular issue is just to pick and enforce username constraints (length, allowed chars, etc...).
If we're going to do this, we should probably do it for 1.0, it'll be easier to relax later.

**Comment by spencerkimball** [comment]
Ok this doesn't seem so hard. HAve we looked into restrictions imposed by postgres / oracle? How long will this take to actually do? If you're sure we should do this, re-lAbel it 1.0 milestone.

**Comment by mberhault** [comment]
I'm not sure at all. The constraints will mostly be on the sql side, not certs or the user table.
@cockroachdb/sql: any opinions?

**Comment by vivekmenezes** [comment]
PostgreSQL

Must contain 1 to 63 alphanumeric characters.
Must begin with a letter or an underscore. Subsequent characters can be letters, underscores, or digits (0-9).
Cannot be a word reserved by the database engine.

is what I could find.

**Comment by mberhault** [comment]
Thanks Vivek.

The remaining question at this point is whether we want to do this for 1.0.
My personal opinion is that these kinds of restrictions are better put in early, but that doesn't necessarily make it a priority.

**Comment by vivekmenezes** [comment]
let's put it in for 1.0. assigning to alfonso, feel free to reassign
