### ISSUE TITLE
distsql: support the spool processor

### ISSUE THREAD

**Issue by rjnn** [cockroachdb/cockroach#21327]
Some upcoming processors (e.g. [nested loop joins](#21301) and [apply](21302)) require a "spool" operation - a processor that buffers a stream of rows, and provides multiple passes over that stream. This operator requires some careful design, as it isn't easily compatible with the current distsql stream interface.

Currently, distsql streams are a unidirectional "push" interface. Processors push to their outputs, which gets consumed by downstream processors. Processors can choose to stop consuming a stream, but this has relatively simple implementation semantics - since any rows that are sent since the close event can simply be discarded. Streams also have an accompanying bidirectional metadata stream, which currently only supports close and error messages in either direction.

In contrast, a spool interface requires some careful thought as to what API the spool processor would support. A simple contract is to add a "reset" metadata message, which results in the upstream consumer sending a sentinel metadata message followed by the stream from the start. The sentinel message is required to indicate at what point the stream actually restarted, since the existing eager push API means that other messages might be in flight.

A different contract is to add a random access pattern, where metadata messages can include requests for rows from various indices. This is considerably more complex, and its not clear if its necessary.

It also bears thinking through whether these patterns are efficiently compatible with the `RowSource` interface (since a spool is likely to be placed locally to its immediate consumer), and how they would affect row batching.

This issue is intended to serve as a starting point for the discussion. I welcome any thoughts @RaduBerinde @petermattis @asubiotto @jordanlewis.

**Comment by RaduBerinde** [comment]
The alternative to generalizing the infrastructure is to incorporate the spool operation into the apply and/or join processor. Conceptually it's not much different than what the hashjoiner is doing.

**Comment by jordanlewis** [comment]
Another use case for spool is multi-use common table expressions, in which a data source's results are named and reused. In that case, the spool operator would permit us to safely plan and execute such statements.

Another alternative to a bidirectional protocol is to have the spool processor send all of its rows in a loop, separated by a reset message. This wouldn't be a suitable protocol if a spool consumer needed the ability to actively jump back to the beginning of the buffer, but I'm not sure if that's a requirement.

**Comment by petermattis** [comment]
I was imagining a `spool` operator would write the incoming to a temporary RocksDB instance using the normal index key encoding. We can certainly stream data out from this spool using the `RowReceiver` interface, or pull data from it using the `RowSource` interface. But perhaps more interesting is providing a `RowScan` interface that would allow reading ranges of rows. This would allow more flexibility in the CTE use case: we can buffer the CTE in a spool and different uses can query out the rows they need using something that would be akin to `tableReader`.

**Comment by knz** [comment]
FWIW, the local execution already supports `spool` now, as it was required to properly support mutation statements and CTEs.

**Comment by jordanlewis** [comment]
We only use this for mutations now, and undoubtedly if/when we distribute mutations we'll think of a different thing to do with spool.
