### ISSUE TITLE
release v2.0-alpha.20180116

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#21321]
Candidate SHA: 1b2eabdd8562
Deployment status: `adriatic`, `omega`

[Release process checklist](https://github.com/cockroachdb/cockroach/wiki/Release-Process)

Prep date: `2018-01-08`
- [x] [Pick a sha](https://github.com/cockroachdb/cockroach/wiki/Release-Process#pick-sha), fill in `Candidate SHA` above.
- [x] [Deploy to test clusters](https://github.com/cockroachdb/cockroach/wiki/Release-Process#deploy-to-test-clusters)
- [x] fill in `Deployment status` above
- [x] [Verify node crash reports](https://github.com/cockroachdb/cockroach/wiki/Release-Process#verify-crash-reports)
- Keep an eye on clusters until release date.

Release date: `2018-01-16`
- [x] [Check cluster status](https://github.com/cockroachdb/cockroach/wiki/Release-Process#check-cluster)
- [x] [Tag release](https://github.com/cockroachdb/cockroach/wiki/Release-Process#tag-release)
- [x] [Trigger release build](https://github.com/cockroachdb/cockroach/wiki/Release-Process#trigger-build)
- [x] [Check binaries](https://github.com/cockroachdb/cockroach/wiki/Release-Process#check-binaries)
- [x] Update docs
- [x] External communications for release
- [x] File issue for next release and assign to release coordinator

**Comment by benesch** [comment]
Release was withdrawn due to potential consistency violations: https://github.com/cockroachdb/docs/pull/2366.
