### ISSUE TITLE
sql/logictest: annoying messages from consistency checker showing up while running logic tests.

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#21324]
These consistency errors keeps showing up while running logic tests:

```
E180108 18:13:20.575508 80186 storage/consistency_queue.go:106  [replica consistency checker,n1,s1,r1/1:/M{in-ax}] computing own checksum: rpc error: code = Unavailable desc = transport is closing
```

This is a minor issue, but it does get a little worrying when I see this show up a good 9 times when `make testlogic' is run. Note that this does not affect the outcome of the tests themselves.

**Comment by jordanlewis** [comment]
I see these all the time as well - I *think* they're just normal conditions that get logged during node shutdown, right? I agree that it's gross that they're error-level.

**Comment by benesch** [comment]
Ugh, I think I may not have fixed this. Reopening.

**Comment by benesch** [comment]
Punting to 2.1 as this is a problem with our test infrastructure, not the infrastructure under test.

**Comment by tschottdorf** [comment]
@benesch fixed this.
