### ISSUE TITLE
sql: plan  shown with `--vmodule=plan=3` differs from plan actually run

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#21331]
So we have this tracing ability to print out the plan executed in the server log when V(3) is true in `plan.go`.

This was meant to print out the logical plan after optimization, that is intended to print out the plan being run.

However, during `startPlan()` (which runs later), there is yet a last optimization: propagating the limits post-evaluation, which can change the plan in drastic ways. 

The tracing/logging code should be modified to show the plan being run after those optimizations (or find a way to make the optimization occur earlier).

**Comment by knz** [comment]
Found with andrei while investigating a CI failure in https://github.com/cockroachdb/cockroach/pull/21305#issuecomment-356106958.

**Comment by jordanlewis** [comment]
This is no longer a problem in the CBO.
