### ISSUE TITLE
storageccl: support custom HTTPS certs in HTTP storage

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#21338]
Probably with a cluster setting specifying the cert/certs to use. Should maybe use the default namespace (like the GCS key), and if we need to support more than 1 cert at once then can use other names and specify which one is desired as a URL param, perhaps.

**Comment by dt** [comment]
We could also just have a cluster setting the flips on `InsecureSkipVerify`, if you want to use TLS for on-the-wire security but aren't worries about host identity verification.
