### ISSUE TITLE
cli/start: display+log warning on start if effective user = root

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#21342]
This user https://forum.cockroachlabs.com/t/database-tables-are-lost-when-re-start-of-database-instance/1265/7 was able to start `cockroach` in `/usr/local/bin` and create a `cockroach-data` directory there.

We need to make the cockroach binary more foolproof and have it be more discouraging if the effective user is root (e.g. launched via sudo or setuid bit).

**Comment by bdarnell** [comment]
It's quite common to run as root in containers (our own published docker images do it). 

While running as a less-privileged account is generally a good idea, I don't think that running as root is so harmful that we need to actively warn against it (if we do, we'll also need to tell people how to create that less-privileged user and correctly-owned directories, etc...). The real solution here is to provide more OS-integrated packages (deb, rpm, etc) which can automate this and other parts of the installation process.
