### ISSUE TITLE
Document SQL commands.

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#2134]
We need clear documentation of all sql commands.
This includes:
* grammar for each command
* explanation of each variant for a command
* privileges required for each variant

**Comment by jusongchen** [comment]
# About
This part describes Cockroach SQL languages and datatypes included with cockroach that can be used in application development. It contains the following chapters:
- Cockroach Data Types
- Cockroach SQL 

# Cockroach Data Types

This chapter discusses the Cockroach built-in datatypes, their properties, and how they map to datatypes of Other RDBMS.

## Introduction to Cockroach Datatypes

Each column value in a SQL statement has a datatype, which is associated with a specific constraints, and a valid range of values. When you create a table, you must specify a datatype for each of its columns.
Cockroach provides the following categories of built-in datatypes:

- Character types
- Binary string types
- Numeric types
- Datetime types
- Boolean type?
- Interval type?

## Character Datatypes

### Overview of Character Datatypes
The character datatypes store character data in strings. 


### Fixed-length Character type
char type
max length? in bytes or in characters? Sql example? 

### Variable-length Character type
varchar type
max length? in bytes or in characters? Sql example? 

### Character Large Object 
CLOB data type
max length? in bytes or in characters? Sql example? 

### Character encoding forms
UTF8 UTF16 UTF32 Sql example? 

### collation
Sql example? 
### character sets

- ASCII
- WE8ISO8859P1
- UTF8
- UTF16
Sql example? 

Is a default character set specified when a database is created?

### Use of Unicode Data in Cockroach 


## Binary string types

### Fixed-length Binary type
binary type
max length in bytes? SQL example?

### Variable-length binary string type
varbinary?
max length in bytes? SQL example?

### Binary Large Object 
BLOB type
max length in bytes? SQL example?

## Numeric types

### Exact numeric types

#### Numeric

numeric[ (p[ , s] )]

    Fixed precision and scale numbers. 
   Max values of p and s?

p (precision)

    The maximum total number of decimal digits that will be stored, both to the left and to the right of the decimal point. 

s (scale)

    The number of decimal digits that will be stored to the right of the decimal point. the default value?

DECIMAL
SMALLINT
INTEGER
BIGINT

### approximate numeric types
#### Float
range? 

#### Real
range? 

#### Double Precision
supported? range? 

## Boolean type

Does cockroach have a boolean type?

## datetime types

### Date

### time types

Time
Time with time zone ?

## Timestamp types
Timestamp 
Timestamp  with time zone 

## Interval type

Interval

Probably not supported right now?

**Comment by mjibson** [comment]
As an experiment, I've auto-generated railroad diagrams from sql.y:

http://mattjibson.com/cockroach-sql-grammar/cockroach.xhtml

Steps to create at https://github.com/mjibson/cockroach-sql-grammar

**Comment by petermattis** [comment]
Neat, though I think this exposes too many grammar implementation details to use as-is in our documentation. For example, `select_claause` vs `simple_select` vs `select_with_parens`. Is there anyway to tweak the resulting output?

**Comment by petermattis** [comment]
Or annotate the input grammar?

**Comment by mjibson** [comment]
Yes, the grammar needs to be reduced. When we start to actually work on this I plan on automating that by doing things like combining options when all left or right sides are identical, and other techniques. This should reduce down the grammar quite a lot, especially the ones with optional parens on either side. My goal is to have it be as nice as the sqlite diagrams (http://sqlite.org/lang_select.html).

**Comment by petermattis** [comment]
Documentation issues are now captured in https://github.com/cockroachdb/docs. See https://github.com/cockroachdb/docs/issues/18.

**Comment by jseldess** [comment]
Data types, privileges, and many sql statements have been documented. Continuing work tracked in the docs repo.
