### ISSUE TITLE
timestampz alias not fully supported?

### ISSUE THREAD

**Issue by arctica** [cockroachdb/cockroach#21343]
Running a fairly recent master build

`CockroachDB CCL up-727-gb28fb8e (linux amd64, built 2018/01/05 00:30:19, go1.9)`

I have tried to use the `timestampz` alias when I noticed that the `age()` function can't take a `timestamp` value but it seems that only the full name `timestamp with time zone` works.

Fails: `SELECT age(created) FROM x` with `pq: unknown signature: age(timestamp)`

Fails: `SELECT age(created::timestampz) FROM x` with `invalid syntax: statement ignored: syntax error at or near "timestampz"`

Fails: `SELECT CAST(created AS timestampz)` with `invalid syntax: statement ignored: syntax error at or near "timestampz"`

Works: `SELECT age(created::timestamp with time zone) FROM x`

According to the [documentation](https://www.cockroachlabs.com/docs/stable/timestamp.html#aliases), all of the above should work.

Also it would be nice if `age()` would have a variant that accepts a timestamp value, similar to the other date and time functions that have two versions.

**Comment by jordanlewis** [comment]
Hi @arctica,

It's `timestamptz`, not `timestampz`. The mnemonic is that it's "with Time Zone" so you add `tz` to the end.

Hope that helps!

**Comment by arctica** [comment]
Hi @jordanlewis,

Doh... now I feel stupid.

Thanks for pointing out the misspelling. Works as it should. Still would be nice if `age()` accepted a timestamp but I'm going to close this issue and just pretend it never existed :)
