### ISSUE TITLE
sql,sql/opt: constraint generation is not tight on descending columns

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#21372]
Suppose I have a table with a primary key over two columns, the first ascending and the second descending:

```
> CREATE TABLE t (a INT, b INT, PRIMARY KEY (a, b DESC)); 
```

When I apply a constraint like `a > 7 AND b < 7`, I get a tight span:

```
> EXPLAIN SELECT * FROM t WHERE a > 7 AND b < 5;
+------+-------+-------------+
| Tree | Field | Description |
+------+-------+-------------+
| scan |       |             |
|      | table | t@primary   |
|      | spans | /8/4-       |
+------+-------+-------------+
```

If the constraint on `b` is flipped, however, to `a > 7 AND b > 5`, I get a loose span:

```
EXPLAIN SELECT * FROM t WHERE a > 7 AND b > 5;
+------+-------+-------------+
| Tree | Field | Description |
+------+-------+-------------+
| scan |       |             |
|      | table | t@primary   |
|      | spans | /8-         |
+------+-------+-------------+
```

In this case I think the proper span is `/8-/8/6/#`. (I might be off by a few bytes, but I think there exists at least some tighter end key for this span.) And indeed, when I create a table with a primary key over just the descending column, both directions work properly:

```
> CREATE TABLE t2 (a INT, b INT, PRIMARY KEY (b DESC));
> EXPLAIN SELECT * FROM t2 WHERE b < 5;
+------+-------+-------------+
| Tree | Field | Description |
+------+-------+-------------+
| scan |       |             |
|      | table | t2@primary  |
|      | spans | /4-         |
+------+-------+-------------+
(3 rows)
 > EXPLAIN SELECT * FROM t2 WHERE b > 5;
+------+-------+-------------+
| Tree | Field | Description |
+------+-------+-------------+
| scan |       |             |
|      | table | t2@primary  |
|      | spans | -/6/#       |
+------+-------+-------------+
(3 rows)
```

With @knz's guidance I added the following test to `opt/testdata/index-constraints`

```
build-scalar,normalize,index-constraints vars=(int, int) index=(@1, @2 desc)
@1 > 2 AND @2 > 5
----
[/3 - /3/5]
```

—again, I wasn't quite sure what the end of the span key should be—but it failed with

```
    	opt_test.go:281: testdata/index-constraints:195: @1 > 2 AND @2 > 5
    		expected:
    		[/3 - /3/5]
    		
    		found:
    		[/3 - ]
    		Remaining filter: @2 > 5
```

suggesting that the new index selection code has the same issue.

It's of course possible that there's some reason it's not actually possible to generate a span in this case. Pretty printing and descending indexes are messing with my head.

**Comment by RaduBerinde** [comment]
You need to think more in-depth about what spans we can generate in these cases :)

I believe that you are making the incorrect assumption that a two-column index can restrict results along the two axes at the same time (i.e. range queries, a rectangle in a 2d plane). This is not the case; the index is still flattened to one dimension. An index on `(a, b)` with a span `/x/y - ` does not restrict to `a >= x AND b >= y`. It restricts to `(a = x AND b >= y) OR (a > x)`. So the `/y` is not as useful as it might seem - it just excludes results from a single `a`.

Let's go through your examples. First, notice that an index on `(a, b DESC)` with condition `a >= 7 AND b <= 5` is similar with an index on `(a, b)` and condition `a >= 7 AND b >= 5` (I'm changing the conditions to be inclusive just to make this discussion easier). In both cases, we can generate a "starting point" of `/7/5`. As discussed above, the span isn't "tight": it includes results like `(9, 1)`  so we still need to evaluate the condition on `b` on every tuple. You can see this in your example with VERBOSE:

```
root@:26257/radu> EXPLAIN (VERBOSE) SELECT * FROM t WHERE a > 7 AND b < 5;
+------+-------+------+--------+-------------+---------+----------------------------+
| Tree | Level | Type | Field  | Description | Columns |          Ordering          |
+------+-------+------+--------+-------------+---------+----------------------------+
| scan |     0 | scan |        |             | (a, b)  | a!=NULL; b!=NULL; key(a,b) |
|      |     0 |      | table  | t@primary   |         |                            |
|      |     0 |      | spans  | /8/4-       |         |                            |
|      |     0 |      | filter | b < 5       |         |                            |
+------+-------+------+--------+-------------+---------+----------------------------+
```

At a high level, the span `/7/5 - ` is only mildly better than the span `/7 - `: the former excludes results like `(7, 1), (7, 2)` but neither excludes results like `(8, 1), (8, 2), (9, 1), (9, 2)` etc.

Now consider an index on `(a, b DESC)` with condition `a >= 7 AND b >= 5`; this is similar with an index on `(a, b)` and condition `a >= 7 AND b <= 5`. There is no starting point better than `/7` here; there is no 

> `EXPLAIN SELECT * FROM t WHERE a > 7 AND b > 5;`
> In this case I think the proper span is /8-/8/6/#.

This span doesn't look close to being correct. It does not include results like `(9, 9`). I think this would be the span for `a = 8 AND b > 5`

```
build-scalar,normalize,index-constraints vars=(int, int) index=(@1, @2 desc)
@1 > 2 AND @2 > 5
----
[/3 - /3/5]
```
Like before, this is not correct. The span doesn't include results like (4, 6), (5, 6), etc.

**Comment by benesch** [comment]
Ah, you are entirely correct. My mistake! Thanks for such a detailed explanation.

(I was in fact thinking of the `a = 7 and b > 5` case; I don't know why I insisted upon writing that as `a >= 7 and b > 5`.)
