### ISSUE TITLE
sql/pgwire: support ArrayOid decoding in pgwire binary format

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#21433]
Our pgwire implementation is currently able to decode many more array types in the text format than in the binary format by [treating them like strings](https://github.com/cockroachdb/cockroach/blob/40bed20826fc4f6e714d4be2ffad7400922f9b90/pkg/sql/pgwire/types.go#L669). This leads surprising results where certain types are only supported when a client driver uses the text format to send arrays of datums. An example of this is boolean arrays (oid 1000). Since applications often have little control over the format that drivers send datums in, we should make an effort to maintain parity between the two formats both for decoding and encoding.

See https://forum.cockroachlabs.com/t/bool-arrays-incompatible-with-github-com-lib-pq/1234/7

**Comment by dnguyenglu** [comment]
is this scheduled for any upcoming release?
