### ISSUE TITLE
engine: RocksDB read/write/space tuning

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#21434]
RocksDB offers a lot of settings that affect various [tradeoffs](http://rocksdb.blogspot.com/2013/10/SparrowTheorem.html) between read performance, write performance, and space amplification. We have mostly tuned these to improve read and write performance at the expense of increased space amplification, but some users may have different preferences. 

We should give users some way to select different rocksdb configurations. Exposing the entire set of rocksdb options would be relatively straightforward for us but daunting for the users. A few different "profiles" (read-optimized, space-optimized, etc) would be easier if we could identify a few sweet spots in the massive configuration space.

**Comment by petermattis** [comment]
> Exposing the entire set of rocksdb options would be relatively straightforward for us but daunting for the users.

I've had a similar thought in the past. I believe MyRocks exposes everything. We probably should too. Adding profiles would be easier for the user but harder for us to verify the profiles.

**Comment by petermattis** [comment]
One approach to exposing full control of the RocksDB settings is to allow the specification of a file to read the options from. The RocksDB `LoadOptionsFromFile()` call then then be used to parse these options. The format is what can be seen in the `OPTIONS-xyz` file in the storage directory.

**Comment by petermattis** [comment]
@bdarnell Any opinion on how to expose this functionality? We could add a `--rocksdb-options-file` flag. A cluster setting doesn't seem feasible as RocksDB initialization needs to happen too early. And I suppose we'd want this controlled on a per-node basis anyway.

**Comment by bdarnell** [comment]
Yes, I think either a `--rocksdb-options-file` flag or an addition to `base.StoreSpec` would be the way to go.
