### ISSUE TITLE
Bad connection when running select count(*) from schemas 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#21464]
I logged into NY PM cluster

Then the SQL client:
cockroach sql --certs-dir=certs

Then set DB to registration(this took 12s yesterday):
set database=registration;

Then tried to run this query:
select count(*) from schemas;

`root@:26257/registration> select count(*) from schemas; driver: bad connection warning: connection lost! opening new connection: all session settings will be lost warning: error retrieving the transaction status: dial tcp 127.0.0.1:26257: getsockopt: connection refused warning: connection lost! opening new connection: all session settings will be lost warning: error retrieving the database name: dial tcp 127.0.0.1:26257: getsockopt: connection refused root@:26257 ?> packet_write_wait: Connection to 192.241.150.167 port 22: Broken pipe`

**Comment by awoods187** [comment]
Tried again this morning and got:

`pq: query execution canceled: [n1] communication error: rpc error: code = Canceled desc = context canceled`

**Comment by jordanlewis** [comment]
@awoods187 could you take a look at the logs on the cluster from around the time that you got the bad connection message? Perhaps one of the nodes crashed.

**Comment by dianasaur323** [comment]
Looks like based on : https://github.com/cockroachlabs/pm/issues/16 this has to do with cockroachdb/cockroach#21165. That being said, why is it that we have to dig through logs to find OOM errors like that? Is there a better way to surface that? 

cc @benesch

**Comment by benesch** [comment]
Nope, that's just how OOM works. The process that gets OOM-killed has no say in the matter, nor any opportunity to print out what's happened.

The solution is to never OOM. That's a big game of whack-a-mole, but we're working on it.
