### ISSUE TITLE
json: inverted index encoding has extra bytes in it

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#21485]
The [inverted index RFC](https://github.com/cockroachdb/cockroach/blob/f9f565ee1d211bd044ef707ce6f514699a37cb0f/docs/RFCS/20171020_inverted_indexes.md) (Section `Key encoding JSON objects`) specifies the following format for inverted index keys:

```
TableId/IndexId/NOTNULL/json-string-key/NOTNULL/json-string-key2/.../json-value-type-tag/json-value/pk-cols
```

For example, the payload `{"a": {"b": true}}` would be encoded:

```
TableId/IndexId/NOTNULL/a/NOTNULL/b/BOOL/true/pk-cols
```

The reason that these `NOTNULL` tags are necessary is that there needs to be a way to distinguish the keys of the inverted index key (`a` and `b` in the above example) from the value of the inverted index key (`true`) so that it's possible to determine when the primary key columns begin in the index.

Therefore, there either needs to be a separator byte between the key part and the pk part, wasting a byte per key, or the key components need to be distinguishable from the leaf value component so that the decoder knows that the next values after the leaf value are the primary key columns. We chose the latter method in the RFC.

The current implementation of inverted index key encoding stores an extra tag per key component. The above example is encoded as the following:

```
TableId/IndexId/NOTNULL/BYTES/a/NOTNULL/BYTES/b/BOOL/true/pk-cols
```

which wastes a byte per key component. We should fix this encoding before we release JSON inverted indexes to prevent wasted on-disk bytes and a costly migration.

cc @petermattis

**Comment by petermattis** [comment]
The `NOTNULL` byte certainly does seem wasteful, though I'm not seeing an obvious way to get rid of it. What other encoding marker do you think could be used here?

One bit that could be addressed here is to encode all the json path components in a single `BYTES` encoding. Note that the `BYTES` encoding includes 2 trailing bytes for the escape character and terminator. Could we use some other escape character as a separator between path components?

**Comment by jordanlewis** [comment]
I'm talking about getting rid of the `BYTES` byte, like the RFC proposes, but keeping the `NOTNULL` byte.

That's an interesting idea to try to store everything in a single `BYTES` encoding. I don't know if it's possible, though. NULL bytes are allowed in JSON strings, for example.

**Comment by petermattis** [comment]
How do you get rid of the `BYTES` marker? The resulting encoded string wouldn't be decodable unless you went through and re-placed `NOTNULL` with `BYTES`. I suppose that works. Could be a big ugly and I worry about corner cases.

Concretely, my suggestion is to add an `escapeSep`. Then encoding a JSON path would look like:

`TableId/IndexId/<BYTES>/a/<ESC><SEP>/b/<ESC><TERM>/<BOOL>/true/pk-cols`

Contrast this with the current encoding:

`TableId/IndexId/<NOTNULL><BYTES>/a/<ESC><TERM><NOTNULL><BYTES>/b/<ESC><TERM>/<BOOL>/true/pk-cols`

And your proposal:

`TableId/IndexId/<NOTNULL>/a/<ESC><TERM><NOTNULL>/b/<ESC><TERM>/<BOOL>/true/pk-cols`

Using the `escapeSep` seems like the winner. Let me take another look at this later to make sure I didn't mess something up.

**Comment by jordanlewis** [comment]
I didn't realize that bytes were encoded with a terminator like this. I thought they were length encoded, which in retrospect obviously makes no sense because that would break sorting.

I like this idea. We'd add another const `escapeSep byte = 0x02` or something. `0x00 0x02` is guaranteed not to appear elsewhere in the sequence, because we replace all naturally occurring`0` bytes with `0x00 0x0ff`.

We'd need to square this with the array encoding as well, which needs a special array separator every time an array appears in an index path. We could add yet another escape separator to avoid leaving the `BYTES` encoding domain altogether, or we could exit the `BYTES` encoding domain with `<ESC><TERM>`, write an `ARR` byte, and then re-enter the `BYTES` encoding domainm.

**Comment by petermattis** [comment]
@jordanlewis Yeah, your description of `escapeSep` looks accurate. I'll let you and @masha take it from here. Ping me if you run into another stumbling block.
