### ISSUE TITLE
release v2.0-alpha.20180122

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#21480]
Candidate SHA: 9da836000c7cc1ca058a4082a80c741c942b58c3
Deployment status: `adriatic`, `omega`

[Release process checklist](https://github.com/cockroachdb/cockroach/wiki/Release-Process)

Prep date: `2018-01-16`
- [x] [Pick a sha](https://github.com/cockroachdb/cockroach/wiki/Release-Process#pick-sha), fill in `Candidate SHA` above.
- [x] [Deploy to test clusters](https://github.com/cockroachdb/cockroach/wiki/Release-Process#deploy-to-test-clusters)
- [x] fill in `Deployment status` above
- [x] [Verify node crash reports](https://github.com/cockroachdb/cockroach/wiki/Release-Process#verify-crash-reports)
- Keep an eye on clusters until release date.

Release date: `2018-01-22`
- [x] [Check cluster status](https://github.com/cockroachdb/cockroach/wiki/Release-Process#check-cluster)
- [x] [Tag release](https://github.com/cockroachdb/cockroach/wiki/Release-Process#tag-release)
- [x] [Trigger release build](https://github.com/cockroachdb/cockroach/wiki/Release-Process#trigger-build)
- [x] [Check binaries](https://github.com/cockroachdb/cockroach/wiki/Release-Process#check-binaries)
- [x] Update docs
- [x] External communications for release
- [x] File issue for next release and assign to release coordinator

**Comment by nvanbenschoten** [comment]
As discussed on the release channel, we're going to want to make sure that https://github.com/cockroachdb/cockroach/pull/21493 makes it into this release. @benesch could you re-deploy with a sha that includes that patch?

**Comment by benesch** [comment]
New candidate SHA is 9da836000c7cc1ca058a4082a80c741c942b58c3. Deployed to `adriatic` and `omega`.

**Comment by benesch** [comment]
Cherry-picking a known correctness issue. Redeploying 098b426bd50d40d90a3ff02f9fe7df738629629f to `adriatic` and `omega`.
