### ISSUE TITLE
sql: executor_opt_interface doesn't cleanup after the planner

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#21482]
`executor_opt_interface:NewExecFactory()` creates an "internal planner" but never calls `finishInternalPlanner()` with it. No biggie, but it should be called after the user of said planner is done with it. It's unclear to me what that point is, though.

Shortly I'll send a PR where I'm changing the `makeInternalPlanner()` function to return the cleanup function explicitly - among others to prevent this mistake. I'm going to continue ignoring the cleanup; I hope you can take over then :)

**Comment by knz** [comment]
@andreimatei I think this issue is obsolete?

**Comment by andy-kimball** [comment]
I think this is obsolete, so closing. @andreimatei, you can reopen if you disagree.
