### ISSUE TITLE
Indefinite cluster unavailability when taking down 2 of 5 nodes

### ISSUE THREAD

**Issue by jgehrcke** [cockroachdb/cockroach#21496]
We are using 5-node CockroachDB 1.1.4 clusters.

In the course of doing resilience testing we have seen that taking 2 out of 5 nodes down can result in a *persistent* failure state where the three surving nodes do not serve read requests anymore (indefinitely, as far as we can tell). In that state, our application went down because all SQL clients (`psycopg2` in that case) were hanging in blocking socket read calls (that's how we noticed something is wrong).

We did further debugging with CockroachDB's SQL client and found that the failure state looks like this from a client's point of view:
    
- the SQL client `connect()`s to a CockroachDB node and establishes a TCP connection.
- the SQL client performs a 'handshake' with CockroachDB (which includes reading data from the TCP socket).
- the SQL client writes the SQL expression to the TCP socket.
- the SQL client waits forever on data to arrive on the TCP connection (at least for as long as we waited).

## Repro

The following is my attempt for providing a minium viable repro. Notes:

- This requires `cockroach-v1.1.4.linux-amd64.tgz` in the current working directory, and deletes and creates a directory `cockroach114-repro`.
- This does not insert payload data and demonstrates the read issue by querying the `information_schema` table. In production, we ran into the issue when querying a payload table (but that does not seem to be a requirement for the repro).

`repro.sh`:
```bash
set -ex

rm -rf cockroach114-repro && mkdir cockroach114-repro && cd cockroach114-repro
tar xzf ../cockroach-v1.1.4.linux-amd64.tgz

for i in 1 2 3 4 5;
do
    mkdir crdb-data$i
done

./cockroach-v1.1.4.linux-amd64/cockroach start --host=localhost --port=8091 --http-port=22341 --store=./crdb-data1 --insecure  &>> cockroach-1.outerr &
./cockroach-v1.1.4.linux-amd64/cockroach start --host=localhost --port=8092 --http-port=22342 --store=./crdb-data2 --join=localhost:8091 --insecure  &>> cockroach-2.outerr &
./cockroach-v1.1.4.linux-amd64/cockroach start --host=localhost --port=8093 --http-port=22343 --store=./crdb-data3 --join=localhost:8091 --insecure  &>> cockroach-3.outerr &
./cockroach-v1.1.4.linux-amd64/cockroach start --host=localhost --port=8094 --http-port=22344 --store=./crdb-data4 --join=localhost:8091 --insecure  &>> cockroach-4.outerr &
CRDB_4_PID=$!

./cockroach-v1.1.4.linux-amd64/cockroach start --host=localhost --port=8095 --http-port=22345 --store=./crdb-data5 --join=localhost:8091 --insecure  &>> cockroach-5.outerr &
CRDB_5_PID=$!

# Wait for the cluster to equilibrate.
sleep 5

# Emit details about running CockroachDB processes.
ps afx | grep cockroach

# Confirm that all nodes in the cluster serves reads.
for i in 1 2 3 4 5;
do
    ./cockroach-v1.1.4.linux-amd64/cockroach sql \
    --insecure --host=localhost --port=809$i \
    --execute 'select count(*) from information_schema.statistics;'
done

# Kill nodes 4 and 5 (two out of five, not the first one started).
kill -9 "$CRDB_4_PID" "$CRDB_5_PID"

# Emit details about running CockroachDB processes, once again.
ps afx | grep cockroach

# Wait for an arbitrary duration and then do a read.
sleep 10
strace -o read-strace.log -f \
    ./cockroach-v1.1.4.linux-amd64/cockroach sql \
    --insecure --host=localhost --port=8091 \
    --execute 'select count(*) from information_schema.statistics;'
```

## Symptom: no data arrives

For me, `repro.sh` reproduced the problem in 10 out of 10 attempts.

In my environment (Lenovo T450s with Fedora 26) `repro.sh` results in the final `cockroach sql` process to not return, indefinitely.

The last few output lines of the repro script, also showing the `^C` which indicates that I stopped the SQL client with a `SIGINT`:

```
+ strace -o read-strace.log -f ./cockroach-v1.1.4.linux-amd64/cockroach sql --insecure --host=localhost --port=8091 --execute 'select count(*) from information_schema.statistics;'
# Server version: CockroachDB CCL v1.1.4 (linux amd64, built 2018/01/08 17:32:42, go1.8.3) (same version as client)
# Cluster ID: a9ff1090-e3c7-400c-9a67-02270a85c52a
^C
```

The `read-strace.log` file collected above can be used to look at the TCP information flow:
```
[...]
4797  connect(4, {sa_family=AF_INET, sin_port=htons(8091), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 EINPROGRESS (Operation now in progress)
4797  epoll_create1(EPOLL_CLOEXEC)      = 5
4797  epoll_ctl(5, EPOLL_CTL_ADD, 4, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=1291319520, u64=140502556473568}}) = 0
4797  epoll_wait(5, [{EPOLLOUT, {u32=1291319520, u64=140502556473568}}], 128, 0) = 1
4797  getsockopt(4, SOL_SOCKET, SO_ERROR, [0], [4]) = 0
4797  getsockname(4, {sa_family=AF_INET, sin_port=htons(53722), sin_addr=inet_addr("127.0.0.1")}, [112->16]) = 0
4797  getpeername(4, {sa_family=AF_INET, sin_port=htons(8091), sin_addr=inet_addr("127.0.0.1")}, [112->16]) = 0
4797  setsockopt(4, SOL_TCP, TCP_NODELAY, [1], 4) = 0
4797  write(4, "\0\0\0k\0\3\0\0extra_float_digits\0002\0app"..., 107) = 107
4797  read(4, 0xc42009e000, 4096)       = -1 EAGAIN (Resource temporarily unavailable)
4797  epoll_wait(5, [], 128, 0)         = 0
4797  epoll_wait(5, [{EPOLLIN|EPOLLOUT, {u32=1291319520, u64=140502556473568}}], 128, -1) = 1
4797  read(4, "R\0\0\0\10\0\0\0\0S\0\0\0\31client_encoding\0UT"..., 4096) = 233
4797  read(4, "Z\0\0\0\5I", 4096)       = 6
4797  write(4, "Q\0\0\0000SELECT * FROM crdb_internal"..., 49) = 49
4797  read(4, 0xc42009e000, 4096)       = -1 EAGAIN (Resource temporarily unavailable)
4797  epoll_wait(5, [{EPOLLOUT, {u32=1291319520, u64=140502556473568}}], 128, 0) = 1
4797  epoll_wait(5, [{EPOLLIN|EPOLLOUT, {u32=1291319520, u64=140502556473568}}], 128, -1) = 1
4797  read(4, "T\0\0\0P\0\3node_id\0\0\0\0\0\0\0\0\0\0\24\0\10\377\377\377\377\0"..., 4096) = 357
4797  read(4, "Z\0\0\0\5I", 4096)       = 6
4797  write(1, "# Server version: CockroachDB CC"..., 116) = 116
4797  write(1, "# Cluster ID: da3a70fb-0ed9-4915"..., 51) = 51
4797  write(4, "Q\0\0\0 SET sql_safe_updates = TRUE"..., 33) = 33
4797  read(4, 0xc42009e000, 4096)       = -1 EAGAIN (Resource temporarily unavailable)
4797  epoll_wait(5, [{EPOLLOUT, {u32=1291319520, u64=140502556473568}}], 128, 0) = 1
4797  epoll_wait(5, [{EPOLLIN|EPOLLOUT, {u32=1291319520, u64=140502556473568}}], 128, -1) = 1
4797  read(4, "C\0\0\0\10SET\0Z\0\0\0\5I", 4096) = 15
4797  write(4, "Q\0\0\0008select count(*) from inform"..., 57) = 57
4797  read(4, 0xc42009e000, 4096)       = -1 EAGAIN (Resource temporarily unavailable)
4797  epoll_wait(5, [{EPOLLOUT, {u32=1291319520, u64=140502556473568}}], 128, 0) = 1
4797  epoll_wait(5,  <unfinished ...>
4798  <... pselect6 resumed> )          = 0 (Timeout)
4798  futex(0x322ea18, FUTEX_WAIT, 0, {tv_sec=60, tv_nsec=0} <unfinished ...>
4799  <... futex resumed> )             = -1 ETIMEDOUT (Connection timed out)
4799  futex(0x322ea18, FUTEX_WAKE, 1)   = 1
[...]
```

The "handshake" can be seen on file descriptor `4`, and the query being emitted. After that, the non-blocking socket throws `EAGAIN` to indicate that no data is there and beyond what's shown here the socket never reports back as readable (no data arrives).

## Timing: entire cluster unavailable, indefinitely (or more than 10 minutes)

`repro.sh` leaves three CockroachDB nodes running on the system, and one SQL client hanging in the attempt to read from node 1.

In that state I have done further manual poking to demonstrate that the entire cluster has turned into an unavailable state, also for *new* connections, for as long as I looked (10 minutes):

-    0 s: repro.sh runs last SQL client, request to node 1 hangs
-    5 s: request to node 2 hangs (manually invoked)
-  6 min: both requests still hang
-  7 min: a new request to node 2 hangs (manually invoked)
-  7 min: a new request to node 3 hangs (manually invoked)
-  9 min: first request still hangs, a new request to node 2 hangs
- 10 min: first request still hangs, new requests to either node hang

(subsequent "requests" were all issued with `cockroach sql --insecure --host=localhost --port=809<X> --execute 'select count(*) from information_schema.statistics;'`)

## Impact, other versions affected

This came as a surprise for us. Our motivation for running five nodes is that we would like to be able to survive two failing nodes without downtime, i.e. we would like to see the remaining three nodes to serve reads (*this* is what we care about, performance not so much). Is this a wrong expectation, do we need to change settings?

I also tried `repro.sh` with CockroachDB 1.0.6. Four times. There it reproduced three out of four times (in one attempt, the last `cockroach sql` client invocation returned the expected result).

**Comment by tschottdorf** [comment]
@jgehrcke just to check the obvious, are you running with five-fold replication? The default is 3x, which means that you tolerate only one node outage. From your report, it looks a bit like you think you're running with 5x? See [the replication docs](https://www.cockroachlabs.com/docs/stable/configure-replication-zones.html).

**Comment by jgehrcke** [comment]
> @jgehrcke just to check the obvious

Thanks! What seems to be obvious now probably was not obvious to us for a while.

https://www.cockroachlabs.com/docs/training/replication-rebalancing-fault-tolerance.html is very precise:

>  (n-1)/2 where n = a replication factor of 3. It's important to note that this is not the number of nodes. If you had a 100-node cluster, but with a replication factor of 3, you could still only be certain to tolerate 1 failure.

I also see https://github.com/cockroachdb/docs/issues/1782 which shows that you are on top of that.

I also see

> Use zone configs to increase the replication factor from 3 (the default) to 5. You can do this for the entire cluster or for specific databases or tables.

and

> To survive two simultaneous failures, you must have five replicas.

on https://www.cockroachlabs.com/docs/stable/recommended-production-settings.html which is unambiguous. Not sure how we missed that.

(Besides that, I think https://www.cockroachlabs.com/docs/stable/demo-automatic-rebalancing.html could be modified to mention that changing the replica count is recommended when using 5 nodes)

The default for `num_replicas` is `3` which seems to at least not hurt for single-node deployments / test environments. 

What are the disadvantages of operating a 3-node cluster with `num_replicas` set to `5`?

For completeness, I have changed the repro script to take care of configuring `num_replicas` (more or less reliably) and will provide some stats comparing the cases where the _only_ difference in teh repro script is in the `num_replicas` value.

**Comment by a-robinson** [comment]
> What are the disadvantages of operating a 3-node cluster with num_replicas set to 5?

There aren't any, unless you count the occasional log message about there not being enough nodes in the cluster to meet your desired replication level.

**Comment by nvanbenschoten** [comment]
>There aren't any, unless you count the occasional log message about there not being enough nodes in the cluster to meet your desired replication level.

@a-robinson are you sure about that? A 3-node cluster with a 5x replication factor won't allow you to lose any nodes because it will act like 2 nodes are always down, right? Or is this only the case if we're able to up-replicate to 5 nodes at some point before dropping back down to 3 nodes.

**Comment by a-robinson** [comment]
Thanks for asking, but that's only the case if it has previously up-replicated to 5 nodes. As long as it stays at 3 nodes, the cluster will work alright. It will be able to handle a node outage because each raft group is only of size 3. I think it'll persistently mark all the ranges as under-replicated, but that'll only affect monitoring.

I would not recommend changing such a cluster from 3 nodes to 4, though. You'd want to go straight to 5 nodes when you decided to grow.

**Comment by bdarnell** [comment]
Another thing to watch out for is that if you move the cluster from one set of three machines to another (as seen in [this blog post](https://www.cockroachlabs.com/blog/cross-cloud-migration/), for example), it will temporarily have more than 5 nodes, and having num_replicas set too high may cause issues when shrinking the cluster back down to three. 

While it will mostly work to have `num_replicas` set higher than the number of nodes (and in fact is quite common for the specific case of a single-node cluster with the default `num_replicas=3`), I wouldn't recommend deliberately running a cluster in this state. It's better to only set num_replicas to 5 when you reach the point of expanding your cluster to 5 or more nodes with the intention to keep it that way.

**Comment by knz** [comment]
@jgehrcke I think we have answered your concerns so I'm going to close this issue. 
Filed a docs issue to track your extra question as FAQ. Let us know if there's anything else you want to know.
