### ISSUE TITLE
batcheval: clarify semantics of RangeStatsKey and GetMVCCStats

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#21509]
As a performance optimization, we are usually not declaring the range stats key. This key is written to for each Raft command to apply a stats delta, but since applying these deltas is commutative, this seems correct.

However, there is a problem with this approach for commands that need to read the range stats. These commands usually declare a read on that key. However, since none of the actual updates declare the write (they declare nothing, see above), doing so adds no protection.

This means that a batch evaluation function that calls `GetMVCCStats` multiple times can get different results each time, which is almost certainly not something that the caller expects. I think what the caller expects is something that requires the whole range to be declared.

When I ran into this in [`RecomputeStats`](https://github.com/cockroachdb/cockroach/pull/21345) (which was particularly vulnerable because it declares basically nothing and uses some tricks to get away with it), I was able to use stats commutativity again to patch this skew up: I open a snapshot in the evaluation function, and use it for everything, including reading the MVCCStats. Since all that matters is emitting a delta and applying that delta commutes (and is independent of the specific snapshot taken), there wasn't a problem.

It seems like the other uses (`ClearRange`, `splitTrigger`) also declare the whole range, so they *should* be safe. However, we may try to loosen some of these requirements, particularly for split, and when we do, we're likely to introduce bugs.

Should take a step back and decide whether it makes sense to have `GetMVCCStats` at all. Seems like a footgun.

**Comment by bdarnell** [comment]
RangeStatsKey is no more.

I agree that this unsynchronized accessor is a little risky, but what's the alternative? The split trigger and ClearRange need access to the stats somehow. And even if we do introduce a bug here and the split trigger works with an inconsistent view of the stats, we have ways of fixing up the stats later.

I think this is basically fine as-is, perhaps with a warning added to the EvalContext version of this method (Replica.GetMVCCStats is also used in a lot of other places, but where synchronization is not expected).
