### ISSUE TITLE
ui: redesign expand button on jobs table (currently "...")

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#21510]
@kuanluo filing a follow-up issue - sounds like we are going with this truncated approach, although it would be nice to have the '...' match the overall aesthetic. Do you mind taking a quick pass at it?

![image](https://user-images.githubusercontent.com/5768024/35050632-454d1f84-fb71-11e7-8e0f-d338a2efbd54.png)

cc @mjibson

**Comment by kuanluo** [comment]
Yes, will send something over by EOD tomorrow.

**Comment by kuanluo** [comment]
@josueeee and I took a look, and thought we can use the "expand" icon from Events on Graphs (button). An alternative would be to use an outline (top) that's more inline with the icons on the side navigation bar. 

![image](https://user-images.githubusercontent.com/1486483/35229258-f158517a-ff60-11e7-9b8c-59c2c832f02a.png)

Thoughts?

**Comment by dianasaur323** [comment]
I think the downside of the top one is that it looks like an icon where you can add a job or something versus expand for more info. Looks like we should also make sure the ... are the same font as the command.

**Comment by kuanluo** [comment]
Good point! Let's go with the bottom one then, and yes, we should add a white space between the command and the `...` so they aren't too close together.

**Comment by couchand** [comment]
@kuanluo my initial complaint about whitespace before the ellipsis was that you don't want it to fall off to its own line.  but i suppose if we use `&nbsp;` that's not a concern.

My other thought was that the whole cell should be clickable, does that seem right?
