### ISSUE TITLE
distsql: algebraicSetOp's EXCEPT ALL does not emit the correct number of duplicates

### ISSUE THREAD

**Issue by abhimadan** [cockroachdb/cockroach#21530]
Page 276 of the SQL 1999 standard states that the number of duplicates of a row in the result of an `EXCEPT ALL` operation should be equal to `max(leftDuplicates - rightDuplicates, 0)`. I modified `algebraic_set_op_test.go` and added the following test case:
```go
...
		{
			spec: AlgebraicSetOpSpec{
				OpType: AlgebraicSetOpSpec_Except_all,
			},
			inputLeft: sqlbase.EncDatumRows{
				{v[2], v[3]},
				{v[5], v[6]},
				{v[2], v[3]},
				{v[5], v[6]},
				{v[2], v[6]},
				{v[3], v[5]},
				{v[2], v[9]},
			},
			inputRight: sqlbase.EncDatumRows{
				{v[2], v[3]},
				{v[5], v[6]},
				{v[5], v[6]},
			},
			expected: sqlbase.EncDatumRows{
				{v[2], v[3]},
				{v[2], v[6]},
				{v[3], v[5]},
				{v[2], v[9]},
			},
		},
...
```

(Note that `v[i] == i`.)

However, I get the following error: `invalid results: [[2 6] [3 5] [2 9]], expected [[2 3] [2 6] [3 5] [2 9]]`.

Instead of emitting one `[2 3]` (2 left duplicates - 1 right duplicate), we emit 0 copies of it.

**Comment by arjunravinarayan** [comment]
Thanks @abhimadan! I'll fix this shortly and get the processor up to spec.
