### ISSUE TITLE
Creating Time Column Not Working

### ISSUE THREAD

**Issue by nikkomiu** [cockroachdb/cockroach#21548]
**BUG REPORT**

1. Please supply the header (i.e. the first few lines) of your most recent
   log file **for each node in your cluster**. On most unix-based systems
   running with defaults, this boils down to the output of

     grep -F '[config]' cockroach-data/logs/cockroach.log

   When log files are not available, supply the output of `cockroach version`
   and all flags/environment variables passed to `cockroach start` instead.

```
I180118 18:09:39.547055 1 util/log/clog.go:1031  [config] file created at: 2018/01/18 18:09:39
I180118 18:09:39.547055 1 util/log/clog.go:1031  [config] running on machine: cockroach
I180118 18:09:39.547055 1 util/log/clog.go:1031  [config] binary: CockroachDB CCL v1.1.4 (linux amd64, built 2018/01/08 17:32:42, go1.8.3)
I180118 18:09:39.547055 1 util/log/clog.go:1031  [config] arguments: [/cockroach/cockroach start --insecure]
```

2. Please describe the issue you observed:

- What did you do?

```sql
CREATE DATABASE testing;
CREATE TABLE testing.time (t TIME);
```

- What did you expect to see?

The table `testing.time` successfully created with the `t` column of type `TIME`

- What did you see instead?

```sql
CREATE TABLE testing.time (t TIME);
invalid syntax: statement ignored: syntax error at or near "time"
DETAIL: source SQL:
CREATE TABLE testing.time (t TIME);
                             ^
HINT: try \h CREATE TABLE
```

**Comment by benesch** [comment]
Hi @nikkomiu, thanks for giving CockroachDB a spin!

The `TIME` data type wasn't available in v1.1, but was added by https://github.com/cockroachdb/cockroach/pull/19923 and will be available in v2.0. In the meantime, if you'd like to give it a try, you can use our latest alpha release: https://www.cockroachlabs.com/docs/releases/#testing-releases.

Let us know if that works for you!

**Comment by nikkomiu** [comment]
Alright, thank you! I'm not sure how I missed that on the documentation page.

That works for me.

**Comment by benesch** [comment]
No problem—that's why we're here! I'll go ahead and close this out. Let us know if you run into any other trouble!
