### ISSUE TITLE
sql: sequences: lack of `is_called` flag causes minor differences

### ISSUE THREAD

**Issue by vilterp** [cockroachdb/cockroach#21564]
Postgres stores a flag "`is_called`" on each sequence, which is mutated by `nextval`
and `setval`, and affects the behavior of `nextval`. We don't have this flag,
because getting and setting it would require another round trip to the KV layer
to increment a sequence. This causes sequence behavior to differ slightly from
PG.

# Behavior

## PG

In pseudocode:

```python
def create_sequence():
  seq = Sequence()
  seq.is_called = False
  seq.value = 1
  return seq

def nextval(seq):
  was_called = seq.is_called
  seq.is_called = True
  if not was_called:
    return seq.value
  seq.value += 1
  return seq.value

def setval(seq, value, is_called):
  seq.is_called = is_called
  seq.value = value
```

## CR

```python
def create_sequence():
  seq = Sequence()
  seq.value = 0
  return seq

def nextval(seq):
  seq.value += 1
  return seq.value

def setval(seq, value, is_called):
  if is_called:
    seq.value = value
  else:
    seq.value = value - 1
```

# Noticeable differences

## On sequence creation

|                                       | PG       | CR      |
|---------------------------------------|----------|---------|
| `CREATE SEQUENCE seq`                   |          |         |
| `SELECT last_value, is_called FROM seq` | 1, false | 0, true |
| `SELECT nextval('seq')`                 | 1        | 1       |
| `SELECT nextval('seq')`                 | 2        | 2       |
| `SELECT last_value, is_called FROM seq` | 2, true | 2, true |

## On `setval`

(Once the three-arg form of `setval` is merged in #21541:)

|                                       | PG       | CR      |
|---------------------------------------|----------|---------|
| `SELECT setval('seq', 5, false)`        |          |         |
| `SELECT last_value, is_called FROM seq` | 5, false | 4, true |
| `SELECT nextval('seq')`                 | 5        | 5       |
| `SELECT nextval('seq')`                 | 6        | 6       |
| `SELECT last_value, is_called FROM seq` | 6, true | 6, true |

In PG, `setval(seq_name, value, is_called)` allows you to set the `is_called`
flag. This is used for SQL dumps, so you can set the value and control what
value is given out next by `nextval`. In CR, we just emulate this behavior by
setting it to a lower value.

# Options

- Keep it the way it is & document as a known limitation; see if anyone cares.
- Store an `is_called` flag. I suspect this might be slow because sequence
  operations would have to read and write to it in a transaction with their
  actual `Inc` operation (multiple KV round trips). I haven't actually benchmarked it though.

Jira issue: CRDB-5882

**Comment by petermattis** [comment]
>  I'm suspicious this might be slow because sequence
operations would have to read and write to it in a transaction with their
actual Inc operation (multiple KV round trips), which I suspect might be
slow. I haven't actually benchmarked it though.

I think the performance of this would make it a non-starter.

Is the `is_called` flag session specific or does it apply across sessions? That is, could we store a flag in the session state to indicate that `nextval` was called for a particular sequence?

**Comment by jordanlewis** [comment]
Nice writeup. I would be pretty surprised if anybody cared about this field, but I've been surprised many times at what dark crevices of Postgres people rely on.

Maybe try searching GitHub to see if any open source projects reference that field.

I would be in favor of having it always return true and marking it as a known limitation.

**Comment by vilterp** [comment]
@petermattis Unfortunately it's global, not per-session. Don't really see a way around storing it as a KV key.

@jordanlewis A quick [search](https://github.com/search?p=1&q=setval+postgres+false&type=Code&utf8=%E2%9C%93) shows a bunch of usages of `setval(seq, val, false)`, but none that immediately check the value by selecting (although that could be happening elsewhere)… I suspect we'll end up documenting this as a known limitation. cc @jseldess @lhirata

**Comment by justinj** [comment]
Mentioned in the PR for setval, but a consequence of this is that `setval(seq, MINVALUE, false)` will error in Cockroach, but not Postgres, which seems like it could possibly be problematic and should probably also be explicitly documented as a known limitation.

**Comment by vilterp** [comment]
Before merging that PR, I moved the check so that `setval(seq, MINVALUE, false)` works and added a test: https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/sequences#L442

**Comment by rafiss** [comment]
https://github.com/cockroachdb/cockroach/issues/52552 describes a more obvious bug that I believe is related to our lack of `is_called`

```
CREATE SEQUENCE seq_testx INCREMENT BY 3 MINVALUE 1 MAXVALUE 12;
ALTER SEQUENCE seq_testx INCREMENT BY 8 MINVALUE 1 MAXVALUE 12 ;
SELECT nextval('seq_testx') ;
```
expected:
```
nextval
-----------
       1
```
got:
```
  nextval
-----------
        6
```
