### ISSUE TITLE
sql: RowFetcher should avoid decoding unneeded key columns

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#21566]
It currently unconditionally decodes all key columns. We should apply the same optimization that's done for value columns: don't decode them or inflate them into `Datums` if they're not needed.

This should probably get done before #21565.

**Comment by jordanlewis** [comment]
Err, this isn't actually done. #21571 avoids decoding the entire index key if no index keys columns are present. This issue was supposed to track avoiding decoding a particular index key column if that column is not needed.

**Comment by asubiotto** [comment]
This is done in the cfetcher using `SkipTableKey` but looks like the row fetcher doesn't do this.

**Comment by jordanlewis** [comment]
Closing as won't fix.
