### ISSUE TITLE
jobs: improve system.jobs table

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#21561]
- add a column family separating details and/or progress from the rest so that updating just progress doesn't rewrite the whole thing
- make the default GC time for system.jobs 10 minutes so that, in the case of IMPORT CSV which does update the details frequently for its distributed progress, the row never grows too large.

**Comment by benesch** [comment]
The TTL made it in to 2.0. Splitting out a separate column family will have to wait until 2.1.

**Comment by mjibson** [comment]
Column families got done by @dt. Closing.
