### ISSUE TITLE
ui: warn users if they've turned off time series storage

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#21592]
Now that we've introduced a toggle for users to turn off time series storage, we should also notify them on the admin UI. We could use the existing notification module for connection issues. 

Not a rush to get this in by 2.0, so a nice to have. Marking it as 2.0 just in case we have time, but otherwise okay to clean up later on.

**Comment by couchand** [comment]
There's a toggle to turn off time series?  Yes, that should definitely be surfaced on the Admin UI.  Like the whole thing is replaced by a static page that says "sorry, you turned this off".

**Comment by dianasaur323** [comment]
Haha, yes precisely! The toggle is timeseries.storage.enabled

**Comment by couchand** [comment]
Ugh. FTR: #21314

**Comment by dianasaur323** [comment]
@bdarnell I think that almost merits a separate issue, since like you mention, this one is probably higher priority. I think we can live with timeseries.resolution_10s.storage_duration / admin UI compatibility not making it into this release, especially since that case in general has a few more edge cases.

New issue here: https://github.com/cockroachdb/cockroach/issues/21659

**Comment by dianasaur323** [comment]
fyi @robert-s-lee this is related to that issue we talked about yesterday - still marked for 2.0 priority, but we'll see if it gets in once we move to bug fix period.

**Comment by dianasaur323** [comment]
Popping over to @piyush-singh
