### ISSUE TITLE
ui: make ui's node liveness definition match server's

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#21632]
After testing the ability to change the time it takes for a node to be recognized as dead / trigger rebalancing, there is one last item before we can mark this as feature complete. Currently, the admin UI's display of node liveness is not dependent on the setting, and is instead hard coded. This is confusing from a user perspective. We should make the definition of node liveness in the admin ui match the corresponding cluster setting. 

More detail here https://github.com/cockroachdb/cockroach/issues/18696

**Comment by mrtracy** [comment]
#18896 is related; the proposed solution for 18896 is to move the determination of "dead" or "suspect" completely onto the server, which would remove these constants from the client completely.

**Comment by dianasaur323** [comment]
@mrtracy thanks for that context - what are our plans for #18896? Our current usability story on this particular issue could definitely be improved, it's very strange right now. what was your thinking in terms of timing of that issue?

**Comment by couchand** [comment]
Closed in #22237.
