### ISSUE TITLE
ui: colors in admin UI graphs don't match the hover over component

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#21630]
Odd, the colors on the graphs don't seem to match the hover over component. In the hover over component, the dot is green, whereas the line is red?

![image](https://user-images.githubusercontent.com/5768024/35198390-3040d70e-febc-11e7-9403-11bc99276dd4.png)

**Comment by couchand** [comment]
wat?  that's very very surprising

**Comment by dianasaur323** [comment]
I know right? Confused...
