### ISSUE TITLE
distsql: Implement INTERSECT and EXCEPT plans using semi-joins and anti-joins

### ISSUE THREAD

**Issue by abhimadan** [cockroachdb/cockroach#21661]
The `INTERSECT` operator is similar to a left semi-join, where rows on the left side are output if and only if they have a match on the right side, and all columns are equality columns. Similarly, `EXCEPT` is similar to a left anti-join, where rows on the left side are output if and only if they don't have a match on the right side, and all columns are equality columns. Therefore, it makes sense to plan these operations using joins, which would also allow us to leverage existing DistSQL join planning logic to distribute the computation.

The primary roadblock on this is the difference in duplicate semantics between `{INTERSECT,EXCEPT} ALL` and {semi,anti}-joins. Suppose a row has n duplicates on the left side and m duplicates on the right side. `INTERSECT ALL` requires that the result table contains min(n, m) duplicates, while a left semi-join will contain n duplicates. Similarly, `EXCEPT ALL` requires that the result table contains max(n-m, 0) duplicates, while a left anti-join will contain 0 duplicates.

**Comment by abhimadan** [comment]
Actually, due to the duplicate behaviour, it might be simpler to just create special join types for the set ops (`intersectAllSetJoin` and `exceptAllSetJoin`, or something along those lines). While similar to semi and anti-joins in terms of row matching conditions, their duplicate behaviour prevents these set ops from being directly implemented by semi/anti joins. Duplicate information is lost once the joiner processors merge the two streams together, so duplicates must be correctly produced at the joiner processor level.

A disadvantage of this approach is that the joiner processors already have quite a bit of special-case logic, and adding more would make that code even more complex (and possibly slower with more inner-loop branches). However, aside from beefing up algebraicSetOp to make it as robust as the joiners, or adding a new processor to massage the streams so that the joiner produces the correct number of duplicates, I'm not sure of another way of tackling this.

**Comment by petermattis** [comment]
Adding new join types seems reasonable to me. Independent of new join types, the existing join type checks are a bit of a wart. Rather than a `joinType` enum I've been thinking we should have a `joinType` interface. I'm not quite sure what would go into the interface yet. We don't want low-level calls like `shouldEmitUnmatchedRow`. Rather, I think we'd want something where we pass a batch of rows that match on the join columns.
