### ISSUE TITLE
sql: add support for LIMIT/OFFSET

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#2166]
Should be relatively straightforward to do.

**Comment by jusongchen** [comment]
An alternative way to implement LIMIT/OFFSET is to use row_number() analytic function. It seems LIMIT/OFFSET is a mySQL dialect while row_number() is an ANSI window function supported by Oracle, MSSQL and others.

Here is code of using row_number() to implement LIMIT/OFFSET

--drop table person

create table person(
first_name varchar(200),
last_name varchar(200),
SSN char(11) NULL,
height numeric(4,1),
constraint Unique_SSN unique(SSN)
)
;

insert into person (first_name,last_name,SSN,height) values ('Jusong','Chen','736-38-3295',175);
insert into person (first_name,last_name,SSN,height) values ('John','Doe',null,173);
insert into person(first_name,last_name,SSN,height) values ('John','Smith','873-87-8375',182.3);


select * from
 (select ROW_NUMBER()over (order by height desc) rn , *
  from person 
  ) r
where rn between 2 and 3

**Comment by petermattis** [comment]
LIMIT/OFFSET is implemented in a lot more than MySQL (https://en.wikipedia.org/wiki/Select_%28SQL%29#Result_limits) including Postgres which our grammar is based off of.

**Comment by jusongchen** [comment]
Hi Peter,

Where can I find the document defines cockroach SQL syntax? PostgreSQL has
some very odd  proprietary SQL syntax.

If the grammar is too close to Postgres, customers using Oracle MSSQL etc
may find that it is too hard to migrate to cockroach as high percentage of
app SQL statements have to be rewritten. For long term, cockroachDB should
target market shares of big DB players and I think postgres only has a very
small share in commercial world.

If any possible, cockroachDB should adopt ANSI SQL 2008 syntax so it can be
more competitive.

Jusong


On Fri, Aug 21, 2015 at 4:09 AM, Peter Mattis <notifications@github.com>
wrote:

> LIMIT/OFFSET is implemented in a lot more than MySQL (
> https://en.wikipedia.org/wiki/Select_%28SQL%29#Result_limits) including
> Postgres which our grammar is based off of.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/2166#issuecomment-133374048>
> .
>



-- 
Jusong Chen
408 315 2288

**Comment by petermattis** [comment]
There is no documentation at present for the SQL syntax. See #2134. Any help in this area would be appreciated.

Postgres does have a number of proprietary extensions, but so does every RDBMs. The base syntax (lexical structure, statements etc) is ANSI and the Postgres folks seem to take conformance reasonably seriously (certainly more so than MySQL). For instance, while Postgres supports LIMIT/OFFSET, it also supports the SQL:2008 FETCH FIRST/NEXT syntax. 

Coming from the startup/tech world, I'm not very familiar with "commercial" usage of DBs. I've seen usage of MySQL and Postgres and the functionality used is pretty straightforward (at least for OLTP-style usage, OLAP usage can get a bit crazy). I'm very curious to know what the common SQL functionality you've seen used and what you think a good base level of SQL support would be. 

Have you actually seen folks in the commercial world switch easily between Oracle, MSSQL, etc? I've always imagined doing so would be a pain, regardless of whether the SQL syntax is compatible.

**Comment by jusongchen** [comment]
Peter,

I post a initial draft of a chapter which discuss cockroach data type at
#2134 <https://github.com/cockroachdb/cockroach/issues/2134>. I have
difficulty to find information I need. Is there a place I can see  all of
SQL statements that cockroach supports right now?

Jusong

On Fri, Aug 21, 2015 at 4:50 PM, Peter Mattis <notifications@github.com>
wrote:

> There is no documentation at present for the SQL syntax. See #2134
> <https://github.com/cockroachdb/cockroach/issues/2134>. Any help in this
> area would be appreciated.
>
> Postgres does have a number of proprietary extensions, but so does every
> RDBMs. The base syntax (lexical structure, statements etc) is ANSI and the
> Postgres folks seem to take conformance reasonably seriously (certainly
> more so than MySQL). For instance, while Postgres supports LIMIT/OFFSET, it
> also supports the SQL:2008 FETCH FIRST/NEXT syntax.
>
> Coming from the startup/tech world, I'm not very familiar with
> "commercial" usage of DBs. I've seen usage of MySQL and Postgres and the
> functionality used is pretty straightforward (at least for OLTP-style
> usage, OLAP usage can get a bit crazy). I'm very curious to know what the
> common SQL functionality you've seen used and what you think a good base
> level of SQL support would be.
>
> Have you actually seen folks in the commercial world switch easily between
> Oracle, MSSQL, etc? I've always imagined doing so would be a pain,
> regardless of whether the SQL syntax is compatible.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/2166#issuecomment-133592072>
> .
>



-- 
Jusong Chen
408 315 2288

**Comment by petermattis** [comment]
Wow, thanks for taking a crack at starting the documentation. We'll definitely need to figure out a structure for it soon, but using the markdown format seems fine for the present. The best list of supported SQL statements right now is probably the `sql/testdata/*` files.

**Comment by jusongchen** [comment]
Hi Peter,

Is there a file list all cockroach SQL keywords(those cannot be used as a
table name)? If yes, can you let me know where it is?

thank you
Jusong

On Tue, Aug 25, 2015 at 8:51 AM, Peter Mattis <notifications@github.com>
wrote:

> Wow, thanks for taking a crack at starting the documentation. We'll
> definitely need to figure out a structure for it soon, but using the
> markdown format seems fine for the present. The best list of supported SQL
> statements right now is probably the sql/testdata/* files.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/2166#issuecomment-134641443>
> .
>



-- 
Jusong Chen
408 315 2288

**Comment by petermattis** [comment]
The grammar [reserved_keyword](https://github.com/cockroachdb/cockroach/blob/master/sql/parser/sql.y#L3946) rule contains all of the keywords that must be quoted for use as a table/column/index name.
