### ISSUE TITLE
Build roachprod/fixture based infrastructure for nightly tests

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#21680]
As noticed repeatedly during recent dev cycles, there's a big gap between our unit testing (including the unit acceptance testing) and our manual production testing:

- unit tests run for short periods of time and exercise lots of variety. They answer the question: do all of this features work in small toy cases?
- production tests run for long periods of time (weeks or months). They are severely limited in variety and basically set up ad-hoc, and as such are hard to maintain. They test very little: most of our clusters run a simple load generator and maybe some cronjob-driven chaos testing. They want to answer the question "do all of these features work in realistic settings?" but fail to do so, and in particular require a human to look at graphs and manually determine problems (though there is an amount of reasonable monitoring).

The proposition here is to build a maintainable bit of infrastructure that gives us the flexibility to run a variety of workloads and operations on real clusters for any amount of time (it's expected that standard durations are on the order of hours).

We built [such infrastructure (via terraform)](https://github.com/cockroachdb/cockroach/tree/master/pkg/acceptance/terrafarm) before and it is used in some nightly tests:
 https://github.com/cockroachdb/cockroach/blob/8c0f19014167787ab14e7bd526afbf9caa70d46e/pkg/acceptance/continuous_load_test.go#L85

See also [our teamcity config](https://teamcity.cockroachdb.com/project.html?projectId=Cockroach_Nightlies&tab=projectOverview).

Terrafarm has some shortcomings that are problematic. It uses terraform, which is a complicated beast that is too general for what we need, and has been a barrier of entry. It was forced into the existing acceptance tests which force the provisioned system into a rigid cage that isn't flexible enough to comfortably write the kinds of versatile tests that we need in the future. It's been unpleasant to use it for long-running tests, as it requires a long-running test runner. Additionally, it's a huge hassle to run these tests manually, or even more ambitiously, to run their logic against an experimental cluster.

On the other hand, we have the tools https://github.com/cockroachlabs/roachprod and https://github.com/cockroachdb/roachperf. The former sets up clusters (i.e. roughly what terraform did, except it doesn't put any binaries anywhere) and the latter was conceived to run benchmarks against clusters created by the former via an incantation of `roachperf <clustername> test <testname>` (after having run another `roachperf` incantation that deploys binaries, and starts and configures the cluster).

These tools are useful and if you squint, you can see how to run tests via

```
roachprod create x
roachperf put x ./cockroach
# either (use the local machine as test runner)
roachperf test x mytest
# or (using one of the nodes as test runner)
roachprod ssh x 1 "roachperf test x mytest --background"
```

We should work towards making this a reality and port the existing terraform tests over to this new infrastructure (which in the process needs to be hashed out).

Some items and ideas to keep in mind here are:

1. A bias for less abstractions. These tests currently run against GCE and that is fine for now, but in the medium term we'll also want to run against AWS. We'll likely end up with a small subset of tests that tie somewhat deeply into the specific system used (imagine testing file system corruption or having to install certain packages to generate i/o pressure on the hard drives), but it's preferable to let these tests figure out the differences at first rather than trying to build abstractions into the test harness too early. (Go templates could go a long way in removing duplication here).

2. mixed version testing (https://airtable.com/tblD3oZPLJgGhCmch/viwOj1Qb7D4gjtemc/recom67pixgSeyDIw). It's desirable to have tests that can work against mixed version clusters do so. This is somewhat in opposition to 1) which suggests leaving it up to the test to place the binaries on the nodes. My suggestion would be to make sure that the terraform-ported tests (which can surely run against mixed version clusters) come in a flavor that does so, and that guidelines are put into place that suggest doing so for all appropriate tests forward.

3. Preference for SQL over cli commands. We are in the process of making sure that all `cli` functionality is available through SQL. Tests should almost never run random `./cockroach X` incantations on the remote servers.

4. Nemeses. Some nemeses will require an upfront setup, for example the toxiproxy network nemesis, or a disk corruption nemesis. Others can be started when desired (a crash nemesis, for example, is just a `kill -9` via ssh and a later restart). In keeping with 1), an initial preference for not baking these nemeses into the infrastructure is suggested.

5. Crash protection. Tests should generally be able to tell when nodes crashed half-way through. An easy way to do so is to periodically measure the uptime of the nodes (note that when nemeses are running, this must be relaxed as crashes are expected). Again, this should be developed as an auxiliary mechanism a test can chose to start (and by default does). Baking such a mechanism deep into the acceptance test framework in our existing infrastructure was unfortunate since it turned quite complicated when chaos was added.

6. Integration with https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/workload (in the sense, that this tool is readily available to tests and is the go-to staple for running load and loading fixtures). This is a tool that creates and caches large data sets. Getting large data sets during tests was historically painful; it is no more.

**Comment by petermattis** [comment]
Some other items to keep in mind:
1. Adding a new nightly test should not require teamcity adjustments (i.e. there should be a meta nightly job that spawns all of the real nightly tests).
2. Some thought needs to be put into gathering debug output. It is very easy to go overboard. Tar'ing up the cockroach debug logs would be a start.
3. There needs to be some minimal UI. Again, it is easy to go overboard here. A teamcity expert should provide some guidance.
4. Performance tests are nightly tests too.

**Comment by petermattis** [comment]
Cc @danhhz

**Comment by tschottdorf** [comment]
https://github.com/cockroachdb/roachprod/pull/27

**Comment by petermattis** [comment]
@tschottdorf While there is still more work to be done on `roachtest` infrastructure, do you think this high-level issue is still useful? For remaining work, I think we should create individual issues.

**Comment by petermattis** [comment]
@tschottdorf Ping. I think we should close this issue and rely on more specific issues regarding enhancing our nightly test infrastructure.

**Comment by tschottdorf** [comment]
Agree.
