### ISSUE TITLE
distsql: EXCEPT ALL can be refactored as a left anti semi join

### ISSUE THREAD

**Issue by arjunravinarayan** [cockroachdb/cockroach#21706]
Currently we have a separate EXCEPT ALL processor. It can be refactored to use the new anti and semi join code, to reduce the maintenance burden of porting features (e.g. external storage) to more processors.

When doing this refactor, careful attention should be paid to behavior regarding duplicate rows. See #21530 for more details.

See the conversation in #21560, which refactored the EXCEPT ALL processor.

**Comment by abhimadan** [comment]
Also see #21661, which addresses the query planning side this issue.
