### ISSUE TITLE
sql: investigate interaction between computed columns and cascading foreign key refs

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#21709]
It's possible these don't play nicely together as-is, but we should investigate once they're both in.

**Comment by knz** [comment]
@justinj @BramGruneir do you recall what prompted this issue? What is left to investigate?

**Comment by BramGruneir** [comment]
Originally, the code to perform the computation for computed columns was in the sql package and it needed to be moved to sqlbase to support cascading.  I believe this has been done, so it should unlock the possibility to mix these together.

**Comment by jordanlewis** [comment]
Closing as unactionable unless someone has a concrete idea of what to do here.
