### ISSUE TITLE
pgwire: too much work for serializing arrays

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#21711]
We allocate a new `writeBuffer` every time we need to serialize an array. This seems very heavy. Can't we do something else? Like use the connections `writeBuffer` or keep around a specially built one?
https://github.com/cockroachdb/cockroach/blob/c4bd367001722c77886533079ff0eb9321a20314/pkg/sql/pgwire/types.go#L391

**Comment by jordanlewis** [comment]
Good point - did you notice any performance issues stemming from this, or did you just notice an inefficiency in the code?

**Comment by andreimatei** [comment]
I was just trolling the code cause I'm changing the ctor for these buffers

**Comment by knz** [comment]
@jordanlewis what project do you reckon this belongs to?

**Comment by lamnguyen21** [comment]
@jordanlewis Is anyone working on this issue? If not, I would like to take on it as my first issue. 😄

**Comment by knz** [comment]
go ahead.

**Comment by knz** [comment]
cc @rafiss for re-triage

**Comment by rafiss** [comment]
@lamnguyen21 thanks for your interest!

some pointers:
- familiarize yourself with `BenchmarkEncodings` in `pkg/sql/pgwire/encoding_test.go`. this tool should help you confirm if your changes are improving the number of allocations. you'll probably only want to focus on running the tuple and array benchmarks.
- make sure your change updates both the tuple and array cases here: https://github.com/cockroachdb/cockroach/blob/f5ed0e24804ead802a791d6ec858d8a59fe54aff/pkg/sql/pgwire/types.go#L447 and https://github.com/cockroachdb/cockroach/blob/f5ed0e24804ead802a791d6ec858d8a59fe54aff/pkg/sql/pgwire/types.go#L480
- i think a fine approach here would be to keep around a special `writeBuffer` that is used specially for writing arrays and tuples. (note -- you need to have a separate one for each connection. maybe you could make it an internal field of the existing "actual" `writeBuffer`, but you'd want to add some safety guards around it. make sure to clear this "temp" `writeBuffer` out each time an array/tuple is moved over to the "actual" `writeBuffer`
