### ISSUE TITLE
sql: test against mixed-version clusters

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#21710]
We perform very little testing of mixed versions, that is, clusters in which the nodes run different versions of CockroachDB. Specifically, we also do not focus on SQL/DistSQL. This could be a problem if queries no longer work across versions for production users. We need to expand our use of mixed version testing in the SQL codebase.

**Comment by awoods187** [comment]
CC @tkschmidt @petermattis

**Comment by vivekmenezes** [comment]
one thought here is to have roachprod have the capability of using two binaries. We can then run the entire suite of tests run over roachprod over a mixed version cluster.

**Comment by petermattis** [comment]
FYI, `roachprod` currently knows nothing about running clusters. `roachperf` does. I'm not sure if `roachprod`/`roachperf` is necessary here. Running a local mixed-version cluster might be sufficient.

**Comment by jordanlewis** [comment]
This has gotten much better since Jan 2018. We're still working on it, but this is such a blanket issue it'll never get closed, so closing.
