### ISSUE TITLE
acceptance: speed up CI

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#21724]
On recent PRs, acceptance takes about 12 minutes while everything else takes about half that.

That's unfortunate. We should make the acceptance tests faster. I experimented with this (parallelizing the Docker and non-docker tests) but `log.Scope` (which I'm generally critical of since it sits on a singleton, though I'm sure it solves a problem) makes this impossible.

TestDockerCLI is the worst offender, with TestDecommissioning next.

We could shard out these tests instead.

See https://gist.github.com/tschottdorf/76ce7149eb116f38a5ac4699ff960a21 for complete timings taken today.

**Comment by benesch** [comment]
In theory, log.Scope would make this easier, not harder. Without scoping logs, output from tests running in parallel will be uselessly intermingled.

**Comment by tschottdorf** [comment]
I agree that scoping logs is something that's necessary for this to work nicely, but the basic ingredient to get that is to have `log` not be a singleton (at least in `acceptance`). `log.Scope` doesn't do that, and blows up spectacularly when used in parallel (for good reasons), so it's more in the way than not. `log.Scope` on a non-singleton `log` is what we need.

**Comment by benesch** [comment]
Are you proposing to plumb a per-server logger to every logging call? Not opposed, just overwhelmed:

```
$ git grep 'log\.' | wc -l
    3011
```

**Comment by tschottdorf** [comment]
If it were easy, I would've done it two years ago 😄 The plumbing is pretty intimidating. It's like adding `context.Context`, but worse. I'd prefer it, but it hasn't been that important yet, is a lot of work, and probably even more work is convincing everyone that it's worth it.

Then again, this can be rolled out piecemeal, so it doesn't have to be a forklift. Either way, I think there should be some buy-in before going down the road.

**Comment by tschottdorf** [comment]
Bumping this since I just had to up our acceptance time limit to 30min (#23402). We need to do something here sooner rather than later; this absolutely dominates time-to-merge.

I think the way to go is to reduce the amount of Docker where possible, and to possibly delegate some tests to nightlies.

**Comment by petermattis** [comment]
`acceptance` currently takes in the 20-25m time range. I'll echo the desire to reduce the amount of Docker where possible and to move some of the existing tests to roachtest nightlies.

**Comment by tschottdorf** [comment]
It turns out the Docker tests aren't necessarily the worst offenders here:

![image](https://user-images.githubusercontent.com/5076964/43143688-a47b5f74-8f5b-11e8-9220-8bcf3de87878.png)

Making TestCli faster will certainly be good, but at most it'll save us ~3 minutes.

**Comment by benesch** [comment]
Do we expect the TestGossipRestart tests to take on the order of minutes? That seems awfully slow given what they do.

**Comment by tschottdorf** [comment]
Unclear. There's also the chance that the timings displayed there are just wrong.

**Comment by petermattis** [comment]
With the move of many acceptance tests to roachtests, is there anything else to do here? We can't easily run the roachtest-based acceptance tests in parallel right now, but that could be done with a bit of elbow-grease by allowing multiple local clusters (e.g. `local-1`, `local-2`, ...).
