### ISSUE TITLE
sql: add support for GROUP BY

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#2174]
We'll need to add a `groupNode` similar to `sortNode`. There will likely be similarities to ORDER BY in terms of handling grouping on arbitrary expressions.

See also #2043 as aggregate functions are tied together with GROUP BY.

**Comment by dt** [comment]
#3494 added GROUP BY support using arbitrary expressions (though grouping by an existing column still pending, see #3549 )
