### ISSUE TITLE
cli/start: support MacOS X cgo traceback

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#21755]
We currently don't generate stack traces from profiles for C++ code on Mac OS X because `github.com/ianlancetaylor/cgosymbolizer` is linux only. Need to investigate if there is something that can be done to hook up C++ stack traces on Mac OS X. [`backtrace`](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man3/backtrace.3.html) may possibly be adapted. See https://golang.org/pkg/runtime/#SetCgoTraceback for details.

**Comment by bdarnell** [comment]
FWIW, `backtrace` exists on [linux (glibc)](http://man7.org/linux/man-pages/man3/backtrace.3.html) too. If it works, it could be a portable alternative to `ianlancetaylor/cgosymbolizer`.

**Comment by petermattis** [comment]
Apparently, there is also a darwin version of [libunwind](https://opensource.apple.com/source/libunwind/).

**Comment by petermattis** [comment]
I may be doing something wrong, but with a simple test program I can't get the callback specified by `runtime.SetCgoTraceback` to be invoked on Mac OS X. I did a little instrumentation of the runtime and I can see that the traceback code is being called (`runtime.gentraceback`), but `tracebackCgoContext`, the method which calls the cgo traceback function, is never called. I need to perform a little experimentation on Linux to verify I'm not doing something stupid, but I suspect `runtime.SetCgoTraceback` doesn't work on Mac OS X right now.

**Comment by petermattis** [comment]
Verified the same non-functional behavior on both go1.9.3 or go1.10beta2.

**Comment by benesch** [comment]
Welp, I wasted a train ride yesterday coming to the same conclusion as you. I filed https://github.com/golang/go/issues/24518 upstream. I'm muddling my way through a CL to resolve the issue. https://go-review.googlesource.com/c/go/+/102438.
