### ISSUE TITLE
sql/parser: CREATE STATISTICS should enclose the column list between parentheses

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#21750]
... for consistency with INSERT, CREATE TABLE, CREATE VIEW etc.

i.e. change
```
 CREATE STATISTICS name ON name_list FROM table_name
```

to 

```
 CREATE STATISTICS name ON '(' name_list ')' FROM table_name
```

Found while toying with the feature, also while working on #21753.

cc @RaduBerinde @rytaft

**Comment by knz** [comment]
Also I don't fully understand why not use the syntax `CREATE STATISTICS <name> ON <table_name> '(' <name_list> ')'` to mirror CREATE INDEX.

Was there a particular reason?

(I want to highlight that now is the good time to make this change, before the release locks us into backward compatibility.)

**Comment by RaduBerinde** [comment]
I chose that syntax because it was close to pg: https://www.postgresql.org/docs/10/static/sql-createstatistics.html

**Comment by knz** [comment]
Oh I see. Never mind then, carry on.
