### ISSUE TITLE
[v1.0.4] Hang on disk full

### ISSUE THREAD

**Issue by gpaul** [cockroachdb/cockroach#21752]
**BUG REPORT**

1. Please supply the header (i.e. the first few lines) of your most recent
   log file **for each node in your cluster**. On most unix-based systems
   running with defaults, this boils down to the output of

     grep -F '[config]' cockroach-data/logs/cockroach.log

   When log files are not available, supply the output of `cockroach version`
   and all flags/environment variables passed to `cockroach start` instead.

```
 $ /opt/mesosphere/active/cockroach/bin/cockroach version
Build Tag:    v1.0.4
Build Time:   2017/08/16 13:06:30
Distribution: CCL
Platform:     linux amd64
Go Version:   go1.8.3
C Compiler:   gcc 4.8.5
Build SHA-1:  5b757262d33d814bda1deb2af20161a1f7749df3
Build Type:   development
```

```
/opt/mesosphere/active/cockroach/bin/cockroach start --logtostderr --cache=100MiB --store=/var/lib/dcos/cockroach --certs-dir=/run/dcos/pki/cockroach --advertise-host=10.0.7.61 --host=10.0.7.61 --http-host=127.0.0.1 --http-port=8090 --pid-file=/run/dcos/cockroach/cockroach.pid --join=10.0.7.205,10.0.6.103
```

2. Please describe the issue you observed:

- What did you do?
I have a 3-node cluster. 
I filled up the 80GB partition on the 1st node, the one on which the cockroachdb store directory is located. 
All was well. 
I then filled up the same partition on the 2nd node. 

- What did you expect to see?
I expect CockroachDB to exit on ENOSPC.

- What did you see instead?
Any queries to any of the three nodes now hang indefinitely.

I collected stacktraces for all three running instances. 

Nodes 1 and 2 (the ones whose disks I filled up) appear to be trying to acquire a mutex in the log package.

Node 3 shows no such issue and is presumably waiting for nodes 1 or 2 to ensure it has quorum and can serve requests.

Also, freeing up disk space did not resolve the issue.

Restarting node 1 caused queries to node 1 and node 3 to work again, but node 2 still does not respond. Restarting node 2 then brings it back to life, too.

Stacktraces:
[stack-1.txt](https://github.com/cockroachdb/cockroach/files/1660923/stack-1.txt)
[stack-2.txt](https://github.com/cockroachdb/cockroach/files/1660924/stack-2.txt)
[stack-3.txt](https://github.com/cockroachdb/cockroach/files/1660925/stack-3.txt)

**Comment by nvanbenschoten** [comment]
@gpaul thanks for the report. Could you provide the stack trace you captured that shows the locking in the log package?

**Comment by gpaul** [comment]
Ah right! Attached.

**Comment by nvanbenschoten** [comment]
Thanks!

**Comment by gpaul** [comment]
We also ran into what appeared to be the exact same issue on v1.0.6. I haven't tried reproducing this issue on v1.0.6 but I'm happy to if you think the code may have changed between v1.0.4 and v1.0.6.

**Comment by nvanbenschoten** [comment]
This sounds a lot like https://github.com/cockroachdb/cockroach/pull/17871, which was never ported back to v1.0.6. @bdarnell are we planning on doing any other v1.0 patch releases?

**Comment by a-robinson** [comment]
Yup, definitely looks like #17871.

**Comment by bdarnell** [comment]
We don't have any other 1.0.x release scheduled, but we can do them if there is demand. 

@gpaul if we released 1.0.7 with this fix, would you upgrade to it, or would you rather go to 1.1.x? 

Note that while we've fixed things so that nodes will crash rather than deadlock when the disk fills up, our handling of out-of-space errors is not exactly graceful in any version.

**Comment by gpaul** [comment]
@bdarnell If a CockroachDB v1.0.7 is released that handles ENOSPC (either gracefully or by crashing) we'd certainly prefer to upgrade to it on our v1.10.x branch. We are wary of bumping minor versions of components on stable branches. 

That said, CockroachDB v1.0.x appears to be approaching EOL whereas our current stable release will be maintained for a while still. That may force us to upgrade to CockroachDB v1.1.x on that branch anyway.

Our master branch has already upgraded CockroachDB to v1.1.4 and will upgrade to v1.1.5 for https://github.com/cockroachdb/cockroach/pull/21804 once released.

**Comment by bdarnell** [comment]
1.0.7 is out with this fix.

**Comment by gpaul** [comment]
Note that this is also triggered when systemd-journald is restarted on older versions of systemd.
