### ISSUE TITLE
sql: add support for HAVING

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#2175]
HAVING clauses are like WHERE clauses but are evaluated after GROUP BY while WHERE clauses are evaluated on the rows from a table. Once GROUP BY is implemented (see #2174), support for HAVING should be straightforward.

**Comment by petermattis** [comment]
While this is currently earmarked for 1.0, the implementation should be straightforward once #2201 lands and we have a `groupNode`. We just need to evaluate the `HAVING` clause for correctness and then use it to filter the output of a `groupNode` similar to the `WHERE` clause filters the output of a `scanNode`.

**Comment by dt** [comment]
Fixed in #3547
