### ISSUE TITLE
sql: remove column duplication in index key/values

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#2178]
Consider the following table:

```
CREATE TABLE t (
  a INT,
  b INT,
  c INT,
  PRIMARY KEY(a, b),
  CONSTRAINT bc1 INDEX (b, c),
  CONSTRAINT bc2 UNIQUE (b, c)
```

(Yes, this is contrived, you would never have two indexes for the same set of columns where one is unique and the other is not). 

The key addressing for the non-unique index `bc1` looks like `/t/bc1/b/c/a/b/c`. This is because we currently append the full-primary key to non-unique index keys in order to make them unique. This is both obviously correct and inefficient. It would be better to only append primary index key columns that are not otherwise contained in the index key. So the key addressing for `bc1` should look like `/t/bc1/b/c/a`.

Similarly, for unique indexes, we store the primary key column values in the value. In this example, the values for `bc2` look like `/a/b/c`. Again, there is unnecessary duplication. We only need to place primary key columns in the value which are not otherwise present in the index key: `/a`. 

I believe both issues can be addressed by adding an `IndexDescriptor.ExtraColumnIDs` field and populating this field at index creation with the primary key columns that are not otherwise part of the index. Various places where we're using `TableDescriptor.PrimaryIndex.ColumnIDs` would need to start using the `ExtraColumnIDs` field instead, but I think this will be an overall simplification in addition to an efficiency win.

**Comment by vivekmenezes** [comment]
Pete,

Can you update the structured api design doc to reflect this change?

Thanks

Vivek

**Comment by petermattis** [comment]
Yeah, I've got a TODO for myself to move `docs/structured.md` into `sql/doc.go` (which is horrifically out of date). Let me make an actual issue out of that.
