### ISSUE TITLE
Synchronize system database across all nodes.

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#2179]
The system database currently contains:
* database descriptors
* table descriptors

And may soon contain all other configs.

We need efficient access to all information contained in the system database.
The most likely solution is to use gossip to propagate this across all nodes. See [pending RFC](https://github.com/tamird/cockroach/blob/schema-gossip/docs/RFCS/schema_gossip.md)

**Comment by vivekmenezes** [comment]
A lot of the work done in this issue needs to be reverted/deleted. With the new descriptor lease RFC 
https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/table_descriptor_lease.md
will make this work obsolete.

**Comment by petermattis** [comment]
We'll still want to gossip the database descriptors and system tables. Actually, all I'm planning to change is to replace gossiping of the `system.descriptor` table with gossiping of table versions.

**Comment by mberhault** [comment]
We always knew schema migrations were an issue with caching (see #2655). The cache needs to handle them properly. As for other gossiped info, the configs should still be fine, they're less susceptible to propagation delays.

**Comment by petermattis** [comment]
Agreed the configs should be fine. There was no plan to change them. I think we'll also continue to gossip `DatabaseDescriptors` and the namespace table.

**Comment by petermattis** [comment]
@vivekmenezes: This is all done now, correct?
