### ISSUE TITLE
sql: test JSON with a large data set with load

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#21794]
We should run a nightly test that tests/benchmarks JSON with the inverted index on a large data set with load. This could mean modifying one of the allocator tests or adding a new test to do this.

**Comment by vivekmenezes** [comment]
@jordanlewis @m-schneider

**Comment by jordanlewis** [comment]
Great idea. Before we do that, I suggest writing some Go benchmarks for inserting large objects into inverted indexes.

**Comment by justinj** [comment]
cc @benesch if he has any thoughts given his QA buddy status
