### ISSUE TITLE
cli/sql: history-search result is messed up by line navigation

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#21826]
At the prompt, press Ctrl+R to get the history search, then type something to get a result:
```
root@:26257/t> alter table s add constraint b_unique unique (b);                                                                                                                   bck:alte
```

Now, I like my result but I want to edit it, so I press right arrow. At this point, the result is messed up because the characters `[C` show up at the beginning of the line. Escape sequence gone wrong?
This is with iterm2.

After pressing the right arrow, the line looks like this:
```
root@:26257/t> [Calter table s add constraint b_unique unique (b);
```

If you poke into the history code to fix this and you also do #21825 for me, you get my peer ack :P

Jira issue: CRDB-5873

**Comment by knz** [comment]
I'll blame the terminal. This never happens to me. Have you tried with apple's regular terminal?

Also there's no special code in the current implementation to do this. The escape sequences to clear the line, move the cursor home, redraw the prompt, are all sent without any complication from the terminfo/termcap spec to the terminal. I'm wary to 1) spend hours to figure how your terminal diverges from expectations 2) bake a custom fix into some arbitrary fork of libedit (presumably we need to find the copy they use for osx, who knows what other osx-specific code there's in there) 3) vendor that 4) deal with the fallout when our vendored version becomes out of sync with whatever fixes needed upstream when folk upgrade their osx release.

So yeah, no. I'll leave the issue open until this can be further qualified, but I will certainly not work on it myself.

**Comment by andreimatei** [comment]
Happens to me with OSX's Terminal app too. It doesn't happen on a Linux term?

Just in case this is news and rings a bell, `[C` is some sort of escape code for the right arrow.

Can I get another another person to confirm that this happens on iTerm2 and it's not just me - maybe I have a weird key binding in some config somewhere. @tschottdorf would you mind?

**Comment by tschottdorf** [comment]
Happens to me too, in both.

**Comment by rmloveland** [comment]
@andreimatei I found a workaround for Terminal.app

1. Open Preferences
2. Go to **Keyboard** tab
3. Click **+** to add a new keycode
4. For **Cursor Right** key with no modifier, choose to **Send Text**.  In the text area, I hit Ctrl-f (forward char in Emacs binding) to enter that code (you may want something else, this worked for me)
5. Now when I find a result and press the right arrow, the cursor moves forward a char but does not insert the escape sequence and I can continue editing normally

**Comment by knz** [comment]
we'll look into it during cli bug fixit day

**Comment by andreimatei** [comment]
Claim that bounty!

**Comment by knz** [comment]
ok I found the bug, it's in upstream. While the history search mode is activated, the thing only recognizes regular key presses. an escape sequence like an arrow key is handled as an ESC key followed by `[`, `A`. The initial ESC character is interpreted as a request to abandon history search, and then the two characters `[` `A` are handled as regular key precesses.

**Comment by knz** [comment]
The proper behavior can be obtained like this:

- press `^R` to start searching
- find the entry you want in the search
- **press enter** to activate the selection
- then, start to navigate to edit the entry

**Comment by knz** [comment]
oh wow no "enter" actually also runs the command. now I understand why this won't do

**Comment by knz** [comment]
Found a workaround: after finding your history entry press `Ctrl+A` or `Ctrl+E` or simply `Ctrl+L`.
