### ISSUE TITLE
libroach: more time than expected spent copying from iterator to WriteBatch

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#21837]
While profiling a `COUNT(*)` over the 100 million rows of `tpcc.stock` with 1000 warehouses, I noticed that we spend over twice as long copying data from the RocksDB iterator into the WriteBatch we pass back from C++ to Go as we do actually moving the RocksDB iterator.

This is unexpected, because copying to the WriteBatch is just running `std::string::append()` on the data returned from the iterator under the hood.

![image](https://user-images.githubusercontent.com/43821/35462429-de4aac48-02b9-11e8-8fda-e6eaa815de51.png)

We don't preallocate the WriteBatch, so appending to its internal buffer does cause allocations. However, after changing `LD_LIBRARY_PATH` on the profiling machine to include debug symbols for `libstdc++`, it appears that the slow part of appending to the `WriteBatch` is in fact the required `memcpy` operations, not the allocations.

![image](https://user-images.githubusercontent.com/43821/35462474-1baa5d36-02ba-11e8-9a66-283cf54b6872.png)

I've attached the profile I'm looking at for these screenshots. It has symbols for `libroach`, `rocksdb` and `libstdc++`, and represents a 400-second sample of a 632-second `count(*)` operation.

[pprof-symbs-long.gz](https://github.com/cockroachdb/cockroach/files/1669300/pprof-symbs-long.gz)

**Comment by petermattis** [comment]
I did some brief sanity checks that the above is true by wrapping the calls to `WriteBatch::Put` and `Iterator::{Next,Seek}` with timing code. The profile numbers match this timing instrumentation. My testing utilized `BenchmarkMVCCScan` with `rows=10000` and `valueSize=8`. This resulted in batches that were ~330k in size. The time spent performing `WriteBatch::Put` calls varied from 10s of microseconds to 200-300 microseconds. The variation was quite large. 

We're probably seeing cache effects here. Note that copying 330k in 300 microseconds is 1 GiB/sec. Doing that copy in 20 microseconds is a rate of 15.4 GiB sec which is likely hitting caches.
