### ISSUE TITLE
sql: index constraints no longer working for LIKE 'string%'

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#21831]
v2.0-alpha.20180116-650-gaf29319fc:

```
> create table d.t (s string primary key);
CREATE TABLE

Time: 29.1546ms

root@:26257/> explain select * from d.t where s like 'test%';
+------+-------+-------------+
| Tree | Field | Description |
+------+-------+-------------+
| scan |       |             |
|      | table | t@primary   |
|      | spans | ALL         |
+------+-------+-------------+
```

v2.0-alpha.20171218:

```
>  create table d.t (s string primary key);
CREATE TABLE

Time: 53.351523ms

root@:26257/>  explain select * from d.t where s like 'test%';
+-------+------+-------+-----------------+
| Level | Type | Field |   Description   |
+-------+------+-------+-----------------+
|     0 | scan |       |                 |
|     0 |      | table | t@primary       |
|     0 |      | spans | /"test"-/"tesu" |
+-------+------+-------+-----------------+
```

This broke a query I was running (time went from ~ms to +30s).

**Comment by justinj** [comment]
Would also be nice to support this for collated strings, which a user has asked for on gitter in the past. Not sure how much work that would be on top of this, and it would probably include supporting the `LIKE` operator for collated strings independent of index selection. I can open a separate issue for that if it's too distinct from this one.

**Comment by petermattis** [comment]
We probably also regressed on `SIMILAR TO`.

**Comment by RaduBerinde** [comment]
This fell through the cracks. In my defense, we have no logictests for it, and no tests for it in opt_index_selection_test.go. The old code rewrites the expression before handing it off to the index selection code. I will look at adding the corresponding code as a normalization step. 

@justinj Please file a separate issue, collated strings are an extra layer of difficulty.
