### ISSUE TITLE
engine: experiment with passing a fixed-size buffer from Go to C++ to avoid copies

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#21840]
Currently, on a fully-local scan operation, the backing RocksDB data gets copied at least twice on its path from the RocksDB iterator to SQL-land:

1. In `libroach/mvcc.h:addAndAdvance`, we copy the data from the iterator-provided `rocksdb::Slice` to the `WriteBatch` that we plan to return back to Go across the CGo barrier. This is a *required* copy: RocksDB does not provide an interface to keep values around after the iterator is moved, because the values returned by RocksDB iterators are computed, not living permanently in some pinned page or anything like that.
2. In `rocksdb.go`'s `rocksDBIterator.MVCCScan`, we call `cSliceToGoBytes` on the `WriteBatch` mentioned above. This copies the memory from the C++-managed `WriteBatch` to a Go-managed `[]byte`, so that the C++ memory can be freed.

There are a couple of interesting things to notice here.

First of all, we are effectively allocating the memory for this `WriteBatch` twice: once on the Go side and once on the C++. In practice we're allocating more than twice the required memory, because we don't know the size of the `WriteBatch` until we know the size of all of the keys and values that will go into it. This causes dynamic resizing.

Second, we are copying this data twice, and for the same reasons as mentioned regarding dynamic resizing we're actually copying this data more than twice.

@arjunravinarayan suggested a way to avoid doing these multiple copies and allocations: passing a fixed-size buffer from Go to C++ for the `WriteBatch`. To do this, the C++ MVCC implementation would have to be modified to stop returning keys when the buffer is full, and there would need to be some fallback logic for the case where a single KV pair is bigger than the fixed size buffers.

The fixed-size buffer's size needs to be well estimated, or else we'll routinely mis-size the buffer and waste time. One proxy we have to the correct size is the size of the batch that the client requested for the scan.

We should try this out and see if it changes anything.

**Comment by petermattis** [comment]
There are number of practical irritations to experimenting with this. The first is that we'd have to reimplement parts of the `WriteBatch` code. It might be easier to experiment with not copying the C++ memory to Go. I think we can do this for the `MVCCScan` benchmarks due to the way they utilize the iterators and this would give us some idea of the performance benefit.

**Comment by petermattis** [comment]
Ok, that was easier to experiment with than expected. `new` uses `cSliceToUnsafeGoBytes` instead of `cSliceToGoBytes` to pass the batch data back to `MVCCScan` and thus avoids the copy. The benefit of avoiding the copy shows up at larger value sizes for `BenchmarkMVCCScan`:

```
name                                                   old time/op    new time/op    delta
MVCCScan_RocksDB/rows=1000/versions=1/valueSize=512-8     430µs ± 1%     302µs ± 1%  -29.80%  (p=0.000 n=9+10)
```

**Comment by petermattis** [comment]
I should note that the experiment shows the potential benefit. The approach taken can't be easily used as we can't easily keep the C++ memory around for the correct lifetime (i.e. we don't know the lifetime of the results return from `MVCCScan`).

**Comment by petermattis** [comment]
Also for future exploration is `ReadOptions::pin_data` (see https://github.com/facebook/rocksdb/wiki/Reducing-memcpy-overhead-when-using-Iterators). The comments say you can't use that option if you use key delta encoding, but looking at the code it seems like nothing prevents it from working for values. For many workloads, the value is as large or larger than the key. Avoiding the copy would be significant.

Also, the exploration here lends weight to pushing projection and filtering down into C++ so that we move less data around.

**Comment by jordanlewis** [comment]
> There are number of practical irritations to experimenting with this. The first is that we'd have to reimplement parts of the WriteBatch code. It might be easier to experiment with not copying the C++ memory to Go. I think we can do this for the MVCCScan benchmarks due to the way they utilize the iterators and this would give us some idea of the performance benefit.

I tried prototyping code that passes Go memory into C++ for it to fill up. Some of the difficulties I've encountered so far, besides having to write C++:

1. Lots of callers of MVCCScan pass in MaxInt64 as the batch size, so you can't really preallocate Go bytes based on the batch size without making some extra assumptions.
2. Presizing the buffer is impractical because you don't know the size of the values ahead of time.
3. Test callers of MVCCScan assume that they will always get back the full scan so various tests will need to be augmented to do the resume span dance.

One way to get around these problems is to have C++ fill the fixed-size Go-memory buffer as much as possible, and spill extra data into a fresh C++-allocated buffer like we do today. Then, returning a non-null "spill buffer" to Go indicates that there's more data to read besides what's in the Go buffer. Go will then extend its original buffer by the size of the C++ buffer and copy the bytes from the spill buffer into the original, extended buffer.

This way we could keep the same number of CGo boundary crossings but have far fewer copies in the common case, assuming we could make a decent estimate of the final data size.

**Comment by petermattis** [comment]
> assuming we could make a decent estimate of the final data size

That seems like a big assumption, but perhaps it isn't necessary. Perhaps we could do something like you suggested in the previous paragraph: Go allocates a 4KB buffer to start with and if C++ fills it we return to Go and it doubles the size. Heck, we don't even need to return to Go directly. We could have a Go function that C++ calls to allocate a larger buffer. Double the size each time to get amortized constant time appends. I recall a Cgo crossing is ~50 nanoseconds and we're looking at low hundreds of microseconds for the data copying.

**Comment by jordanlewis** [comment]
I like the idea of having C++ call a Go function directly to up the buffer size, rather than returning, which complicates the interface. I'll try adding that to my prototype.

**Comment by jordanlewis** [comment]
Okay, I tried this out. Here's my `growSlice` function:

```
//export growSlice
func growSlice(cSlice C.DBSlice) C.DBSlice {
	slice := cSliceToUnsafeGoBytes(cSlice)
	newSlice := make([]byte, cap(slice)*2)
	copy(newSlice, slice)
	return goToCSlice(newSlice)
}
```

Either I am doing something wrong or CGo prohibits this muckery. From the [CGo documentation](https://golang.org/cmd/cgo/):
> A Go function called by C code may not return a Go pointer.

I think that's exactly what we're doing here - returning a Go pointer from a Go function called by C code. This appears to be borne out by the runtime, which causes a crash when C asks for more memory:

```
panic: runtime error: cgo result has Go pointer

goroutine 16 [running]:
github.com/cockroachdb/cockroach/pkg/storage/engine._cgoexpwrap_cc38f3e0149b_growSlice.func1(0xc420465418)
        github.com/cockroachdb/cockroach/pkg/storage/engine/_test/_obj_test/_cgo_gotypes.go:1003 +0x5c
github.com/cockroachdb/cockroach/pkg/storage/engine._cgoexpwrap_cc38f3e0149b_growSlice(0xc42054c000, 0x70000004af38, 0xc420598000, 0x95e70)
        github.com/cockroachdb/cockroach/pkg/storage/engine/_test/_obj_test/_cgo_gotypes.go:1005 +0x18a
github.com/cockroachdb/cockroach/pkg/storage/engine._Cfunc_MVCCScan(0x6905dd0, 0xc42001c500, 0x7, 0xc42001c680, 0x8, 0x5, 0x0, 0x3e8, 0x0, 0x0, ...)
        github.com/cockroachdb/cockroach/pkg/storage/engine/_test/_obj_test/_cgo_gotypes.go:935 +0x74
github.com/cockroachdb/cockroach/pkg/storage/engine.(*rocksDBIterator).MVCCScan.func1(0x6905dd0, 0xc42001c500, 0x7, 0xc42001c680, 0x8, 0x5, 0x0, 0x3e8, 0x0, 0x0, ...)
```

**Comment by petermattis** [comment]
The Cgo prohibition is meant to avoid exactly the problem you hit: you allocated Go memory which you passed to C++, but you didn't retain a reference to it in Go. When the GC runs it will merrily collect that memory. We have to do something a bit fancier than what you're doing here and pass a pointer to a Go object through C++ and back out to the `growSlice` function and then store the new slice in that Go object. For experimentation purposes, it would suffice to hold a reference to the slice in a global.

**Comment by jordanlewis** [comment]
That doesn't seem to be allowed either:

> Go code may pass a Go pointer to C provided the Go memory to which it points does not contain any Go pointers.

I think the reason for this is that the GC might move pointers. See https://github.com/golang/go/issues/12416#issuecomment-136473697

**Comment by jordanlewis** [comment]
Hmm, but in practice it doesn't seem to warn about this. I have a fully working patch now that seems to demonstrate some pretty nice gains:

```
name                                old time/op    new time/op    delta
WideTableIgnoreColumns/Cockroach-8    12.2ms ± 2%     9.7ms ± 1%  -20.25%  (p=0.000 n=10+10)
```

```
name                                                    old time/op    new time/op    delta
MVCCScan_RocksDB/rows=1000/versions=10/valueSize=512-8    2.05ms ± 1%    1.89ms ± 2%   -8.07%  (p=0.000 n=10+10)

name                                                    old speed      new speed      delta
MVCCScan_RocksDB/rows=1000/versions=10/valueSize=512-8   249MB/s ± 1%   271MB/s ± 2%   +8.79%  (p=0.000 n=10+10)

name                                                    old alloc/op   new alloc/op   delta
MVCCScan_RocksDB/rows=1000/versions=10/valueSize=512-8     606kB ± 0%     994kB ± 0%  +63.98%  (p=0.000 n=9+10)

name                                                    old allocs/op  new allocs/op  delta
MVCCScan_RocksDB/rows=1000/versions=10/valueSize=512-8      3.00 ± 0%      4.00 ± 0%  +33.33%  (p=0.000 n=10+10)
```

The allocation numbers look awful but they're not, because the benchmark doesn't take into account the allocation that C++ was doing before. Now it's all done in Go.

Not including all of the MVCCScan numbers because the benchmark fails in certain cases both before and after my change. Not sure what's up with that, but I'll include all of the numbers when I find out what the deal is.

**Comment by nvanbenschoten** [comment]
@jordanlewis there's undoubtedly more we could do here in the long-term future, especially if we move to Pebble. Do you think it's worth keeping this issue open?

**Comment by petermattis** [comment]
I think we can close this.
