### ISSUE TITLE
storage: usage accounting and enforcement

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#2185]
We need to aggregate bytes/keys usage by table and database and enforce limits.

This includes:
- determine which metrics to count/limit (eg: bytes before/after replication, keys, pending GC, etc...)
- aggregation at various levels
- quotas in accounting config
- enforcement when quotas are exceeded

**Comment by mberhault** [comment]
Bumping. We'll need this for cloud stuff at least. Large organizations with many teams/users may also be interested. Re-assigning to product to take a look and keep track of it.

**Comment by lunevalex** [comment]
Closing in favor of #19721 and #51551
