### ISSUE TITLE
sql: query/schema aware test generation

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#21853]
Given a query and a schema, generate test data which exercises interesting execution code paths: [Query-aware Test Generation Using a Relational Constraint Solver](http://users.ece.utexas.edu/~khurshid/papers/2008/08ase-query-aware.pdf). This is the idea mentioned in https://github.com/cockroachdb/cockroach/issues/21215#issuecomment-355176685.

This issue is about drawing attention to the feasibility of the problem, not to suggest that we should duplicate the approach of the paper.

**Comment by petermattis** [comment]
Cc @andy-kimball, @RaduBerinde

**Comment by jordanlewis** [comment]
SQLSmith is this, maybe? Seems related. @mjibson you might be interested in reading that paper. Please close this if you think we're not going to get to it or don't need it.

**Comment by mjibson** [comment]
This sounds pretty fun, but it isn't sqlsmith. I'm interested in it though! I'm all about more kinds of automated randomized testing, especially if there's already a paper and code that describes how to do novel ideas like this.

**Comment by jordanlewis** [comment]
Peter, I'm going to close this - not because I don't think we should do it, but because I don't think it's actionable to have this issue lying around. If you have objections, let me know!
