### ISSUE TITLE
ui: alert user when cluster is dangerously low on disk?

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#21862]
Currently, our UI doesn't do anything to call out to the user when a cluster is nearly or completely out of disk. For example, last night cyan looked like this, with one node having already died due to running out of disk space:

<img width="1265" alt="screen shot 2018-01-29 at 12 40 49 am" src="https://user-images.githubusercontent.com/7085343/35517903-df1f13c2-04dd-11e8-8b58-48bda3a5bcbf.png">
<img width="1244" alt="screen shot 2018-01-29 at 12 40 38 am" src="https://user-images.githubusercontent.com/7085343/35517905-e27a9aaa-04dd-11e8-9003-33196bcd3866.png">

The cluster overview page is certainly an improvement over the graph dashboard, but it's still not really making it clear that the cluster is teetering on the edge of complete failure in a way that only the cluster admin can do anything about.

While I'm not up-to-date on our current feelings about displaying alerts/warnings in the UI, if we aren't opposed to the idea then this would seem to be one of the most natural times to do so.

@dianasaur323

**Comment by dianasaur323** [comment]
@a-robinson thanks for the suggestion - this highlights that we need to do better alerting for these types of scenarios in the admin UI. I marked it as 2.1 for now so as not to make the 2.0 admin UI issue list blow up, but we'll see what we can get to after our bug triage meeting today.

**Comment by piyush-singh** [comment]
This is a natural fit for work that we are doing in 2.2, updating the milestone. Also added this issue to our corresponding air table entry for future reference.
