### ISSUE TITLE
cockroach start --dev not so seamless

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#2186]
Perhaps I'm missing something, but `cockroach start --dev` seems to require an existing set of certs in the `certs` directory. I think it should create those automatically.

**Comment by tamird** [comment]
I've been using `./cockroach start --dev --insecure`. I could change `--dev` to imply `--insecure`, but that would require an accompanying `--insecure` passed to `./cockroach {kv,sql}`. Thoughts?

cc @MBerhault

**Comment by MBerhault** [comment]
We could have `--dev` be a global flag. For everything other than start, it would just specify default values for `--insecure` and `--addr`

**Comment by MBerhault** [comment]
oh, this means that the instructions would be something along the lines of:
* no init or certs
* `./cockroach start --dev`
* all other cockroach commands must have `--dev`. eg: `./cockroach kv --dev a b`

Another alternative would be to remember the `--dev` flag from the start command, but I'd rather not.

**Comment by tschottdorf** [comment]
This is one of the things that would run much smoother if we accepted passing of flags via the environment:

```bash
export COCKROACH_DEV=true
./cockroach start
./cockroach kv scan
```

And serious deploys sanitize their environment anyways, for example via `env -i`.

**Comment by petermattis** [comment]
We could support `COCKROACH_DEV` as a special case.
