### ISSUE TITLE
qa: SEQUENCE

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#21868]
QA SEQUENCE support

**Comment by mberhault** [comment]
The [rename sequence docs](https://www.cockroachlabs.com/docs/v2.0/rename-sequence.html) state:

Warning:
If you rename a sequence that's being used in a table, the change will not propagate to the DEFAULT expressions that reference the sequence.

However, if I have the following:
```
root@:26257/db> show columns from marc.t;
+-------+------+-------+----------------------------+-------------+
| Field | Type | Null  |          Default           |   Indices   |
+-------+------+-------+----------------------------+-------------+
| id    | INT  | false | nextval('db.bar':::STRING) | {"primary"} |
+-------+------+-------+----------------------------+-------------+
(1 row)

root@:26257/db> select * from information_schema.sequences where sequence_name = 'bar';
+------------------+-----------------+---------------+-----------+-------------------+-------------------------+---------------+---------------------+---------------+---------------------+-----------+--------------+
| sequence_catalog | sequence_schema | sequence_name | data_type | numeric_precision | numeric_precision_radix | numeric_scale |     start_value     | minimum_value |    maximum_value    | increment | cycle_option |
+------------------+-----------------+---------------+-----------+-------------------+-------------------------+---------------+---------------------+---------------+---------------------+-----------+--------------+
| db               | public          | bar           | INT       |                64 |                       2 |             0 | 9223372036854775807 | -1            | 9223372036854775807 | -1        | NO           |
+------------------+-----------------+---------------+-----------+-------------------+-------------------------+---------------+---------------------+---------------+---------------------+-----------+--------------+
(1 row)
```

Attempting to rename the sequence fails, contrary to what is stated in the docs:

```
root@:26257/db> alter sequence bar rename to bar2;
pq: cannot rename relation "bar" because view "marc.public.t" depends on it
HINT: you can drop marc.public.t instead.
```

Which is the desired behavior? The current one, or what the docs state?

**Comment by mberhault** [comment]
CC: @vilterp

**Comment by vilterp** [comment]
I think the current behavior (you get an error telling you it can't be renamed) is good. I think it's better to get that error than to have it successfully rename, and then have inserts into the sequence-using table fail because they can't find the sequence.

So, I think the docs should be updated to show that you'll get this error, and that to rename the sequence you'll need to (1) drop the DEFAULT expression from the sequence-using table, (2) rename the sequence, and (3) add the DEFAULT expression back.

**Comment by mberhault** [comment]
Closing this, QA was finished a while back. The only remaining issue is #23719 scheduled for 2.1.
