### ISSUE TITLE
qa: SCHEMA

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#21870]
@knz is going to be adding ```schema``` into our table naming convention for postgres compatibility as described here:

https://github.com/cockroachdb/cockroach/pull/21456

**Comment by bdarnell** [comment]
Assigning to @vivekmenezes to ensure someone gets assigned for this.

**Comment by rytaft** [comment]
I completed QA last week and created the following issues:
#22964
#22966
#22969
#22974
#22995
#22996
#23002
#23025
#23028
#23103
[#2559](https://github.com/cockroachdb/docs/issues/2559)
Also rediscovered existing issue in #16519

**Comment by knz** [comment]
very nice QA work. Pleasure working with you.

**Comment by rytaft** [comment]
Thanks! Same here :)
