### ISSUE TITLE
qa: RBAC

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#21872]
QA:  Role Based Access Control

**Comment by mberhault** [comment]
@BramGruneir: this is ready for QA. Draft docs (mine, so please don't expect the usual quality) are in https://github.com/cockroachdb/docs/pull/2433

**Comment by BramGruneir** [comment]
Why does SHOW ROLES return a username?  This is quite confusing. How about Rolename?  Or just Role?
```sql
root@:26257/> show roles;
+----------+
| username |
+----------+
| admin    |
+----------+
(1 row)
```

It would be really useful to know if a member is a role or a user:
```sql
root@:26257/> SHOW GRANTS ON ROLE admin;
+-------+--------+---------+
| role  | member | isAdmin |
+-------+--------+---------+
| admin | root   |  true   |
+-------+--------+---------+
(1 row)
```
This should really return 4 columns, one for users, one for roles.  Or something that indicates if the member is a role or a member.

**Comment by BramGruneir** [comment]
I was able to remove all permissions from the admin role.  And even remove the root user from the admin role.

The RFC says that shouldn't be possible.
`The admin role cannot be deleted, and cannot be empty. The special root user cannot be dropped or removed from the admin role.`

**Comment by BramGruneir** [comment]
There is no error message if a grant already exists:
```
root@:26257/test> grant myrolea to myroleb;
GRANT

Time: 7.231ms

root@:26257/test> grant myrolea to myroleb;
GRANT

Time: 2.5ms
```

**Comment by BramGruneir** [comment]
While not in the spec, `SHOW ROLES FOR user` seems like a natural extension and a useful command.

**Comment by mberhault** [comment]
Thanks for testing, good catches!

* Why does SHOW ROLES return a username: good point, that's silly. I'll fix it.
* It would be really useful to know if a member is a role or a user: I'll file this one under "additions", I'll focus on bugs first
* I was able to remove all permissions from the admin role: oops, me too. not good.
* And even remove the root user from the admin role: I was not able to do that part. Did you use `REVOKE admin FROM root`?
* There is no error message if a grant already exists: I copied postgresql's behavior for all of these, it issues a notice, not an error.

```
postgres=# \set VERBOSITY verbose
postgres=# GRANT foo TO bar;
GRANT ROLE
postgres=# GRANT foo TO bar;
NOTICE:  00000: role "bar" is already a member of role "foo"
LOCATION:  AddRoleMems, user.c:1498
GRANT ROLE
```

* SHOW ROLES FOR user seems like a natural extension: you can use `SHOW GRANTS ON ROLE FOR USER marc` for this.

**Comment by BramGruneir** [comment]
> And even remove the root user from the admin role: I was not able to do that part. Did you use REVOKE admin FROM root?
Hmm... you're correct.  I was not able to do that.  Not sure why I wrote it.

Do we have the equivalent of a set verbosity?  I didn't see any notices.

> SHOW ROLES FOR user seems like a natural extension: you can use SHOW GRANTS ON ROLE FOR USER marc for this.

Yeah, just seemed like a good alias for that.  Also it would be nice if it walked the roles tree.
```
root@:26257/test> SHOW GRANTS ON ROLE FOR myuser;
+---------+--------+---------+
|  role   | member | isAdmin |
+---------+--------+---------+
| admin   | myuser |  false  |
| myrolec | myuser |  false  |
+---------+--------+---------+
(2 rows)

root@:26257/test> SHOW GRANTS ON ROLE FOR myrolec;
+---------+---------+---------+
|  role   | member  | isAdmin |
+---------+---------+---------+
| myroleb | myrolec |  false  |
+---------+---------+---------+
(1 row)

Time: 1.307ms

root@:26257/test> SHOW GRANTS ON ROLE FOR myroleb;
+---------+---------+---------+
|  role   | member  | isAdmin |
+---------+---------+---------+
| myrolea | myroleb |  false  |
+---------+---------+---------+
(1 row)

Time: 1.338ms
```

**Comment by BramGruneir** [comment]
To be honest, I find the syntax to be fairly awkward.  I know it comes from pg, but it still is hard to understand and reason around.

**Comment by mberhault** [comment]
On Mon, Feb 12, 2018 at 11:36 PM, Bram Gruneir <notifications@github.com>
wrote:

> And even remove the root user from the admin role: I was not able to do
> that part. Did you use REVOKE admin FROM root?
> Hmm... you're correct. I was not able to do that. Not sure why I wrote it.
>
> pfew! Glad to hear it.


> Do we have the equivalent of a set verbosity? I didn't see any notices.
>

We don't do notices, so we're left with the choice of error or success.
This one's definitely success.

> SHOW ROLES FOR user seems like a natural extension: you can use SHOW
> GRANTS ON ROLE FOR USER marc for this.
>
> Yeah, just seemed like a good alias for that. Also it would be nice if it
> walked the roles tree.
>
We could probably add that later. For now, `SHOW GRANTS` is what mysql uses
(except they don't have "ON ...", they mix both privileges and roles).
As for walking the roles, that would require another indication of direct
vs indirect membership. We can probably add that too, but I've left it out
for now.
For programmatic access, the information_schema tables have full expansion.

**Comment by mberhault** [comment]
And yes, I agree that the syntax sucks, you should see what nastiness this did to the parser. Manipulation is straight from postgres. It does not have `SHOW GRANTS`, but mysql does, albeit just a `SHOW GRANTS [FOR user]` which combines both privileges and role memberships. In my opinion a bad idea.

**Comment by mberhault** [comment]
Ugh. I have this for privilege enforcement of the `admin` role:
```
// TODO(mberhault): we'll need to enforce minimum privileges
// for the admin role as well, but we can't until migrations are done.
```

I'll need to find a way to also toggle enforcement when migrations are done running.

**Comment by mberhault** [comment]
Tweaking the column name in `SHOW ROLES` in #22680.

**Comment by mberhault** [comment]
Fixed. I believe to covers it all. Closing QA issue. @BramGruneir: please re-open if you disagree.
