### ISSUE TITLE
qa: DISTINCT ON (distinct on partial columns)

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#21875]

**Comment by asubiotto** [comment]
This was a fairly easy change to QA, nothing surprising or wrong with the implementation. I created a table `(x INT, y INT, z INT)` with some `NULL` values and ran some distinct on queries (`x`, `x%2`, `y-y`, column with nulls) and checked the results against postgres. Also ran this [tutorial](http://www.postgresqltutorial.com/postgresql-select-distinct/) example.
