### ISSUE TITLE
qa: Enable stars in views & schema mutations on tables being depended on by views

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#21874]
this is still a work in progress for @knz . We can push it to 2.1 if this work cannot be completed.

**Comment by RaduBerinde** [comment]
@knz - please advise if/when the work is done and point me to whatever RFC/documentation we have around the feature. Thanks!

**Comment by knz** [comment]
So the work was pushed to 2.1 already. We'll do the qa on this in a few months.
Thanks for checking this!
