### ISSUE TITLE
qa: Specifying replica location via zone config

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#21881]

**Comment by vivekmenezes** [comment]
should this be assigned to someone with more bandwidth

**Comment by a-robinson** [comment]
cc @benesch, who I believe already did (at least some) QA on this.

**Comment by benesch** [comment]
Ugh, sorry, I never updated this. I did somewhat comprehensive testing while testing partitioning; I can send you more details later today.

**Comment by benesch** [comment]
Ok, I don't understand how this is different from #23018. Can we just close it in favor of that issue? I'm posting a status update there now.

**Comment by a-robinson** [comment]
Yeah, I'm not sure why there's two separate issues for this either. Closing.
