### ISSUE TITLE
release: 1.1.5

### ISSUE THREAD

**Issue by mrtracy** [cockroachdb/cockroach#21890]
Candidate SHA: ec52ded95a5235d71f26b6cbc59924bd6733fb3a
Deployment status: deployed to omega and adriatic.

[Release process checklist](https://github.com/cockroachdb/cockroach/wiki/Release-Process)

Prep date: `01/29/2018`
- [x] [Pick a sha](https://github.com/cockroachdb/cockroach/wiki/Release-Process#pick-sha), fill in `Candidate SHA` above.
- [x] [Deploy to test clusters](https://github.com/cockroachdb/cockroach/wiki/Release-Process#deploy-to-test-clusters)
- [x] fill in `Deployment status` above
- [x] [Verify node crash reports](https://github.com/cockroachdb/cockroach/wiki/Release-Process#verify-crash-reports)
- Keep an eye on clusters until release date.

Release date: `02/05/2018`
- [x] [Check cluster status](https://github.com/cockroachdb/cockroach/wiki/Release-Process#check-cluster)
- [x] [Tag release](https://github.com/cockroachdb/cockroach/wiki/Release-Process#tag-release)
- [x] [Trigger release build](https://github.com/cockroachdb/cockroach/wiki/Release-Process#trigger-build)
- [x] [Check binaries](https://github.com/cockroachdb/cockroach/wiki/Release-Process#check-binaries)

- For stable releases only (**stable** means: no dash in the version):
  - [x] Update the [Homebrew Formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/cockroach.rb)
  - [x] Update the image tag in our [Orchestrator configurations](https://github.com/cockroachdb/cockroach/wiki/Release-Process#orchestrator-configurations)
  - [x] Update the version label in our [Red Hat Atomic Docker image](https://github.com/cockroachdb/cockroach/blob/master/build/deploy/rhel/Dockerfile). For major/minor releases, also update the documentation link in the [image's help file](https://github.com/cockroachdb/cockroach/blob/master/build/deploy/rhel/help.1)
  - [x] Announce version to the [registration cluster](https://github.com/cockroachlabs/production#publishing-a-new-release-version)
  - [x] Upgrade the registration cluster (reg runs latest stable version)

- [x] Update docs
- [x] External communications for release
- [x] File issue for next release and assign to release coordinator

**Comment by knz** [comment]
Adriatic and omega have been healthy all week with no surprises. No "interesting" behavior worth documenting. Suggesting a "go" for this week's release.

cc @cockroachdb/release

**Comment by knz** [comment]
Done
