### ISSUE TITLE
sql: encoding NULL values into indexes should do something real

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#2196]
We currently skip encoding these values entirely, which results in a panic when decoding the next segment of a composite index (e.g. `CONSTRAINT a INDEX (k, v)` where `k` is `NULL`).

We should encode `NULL` with a sentinel so we can handle it correctly on decoding.

**Comment by petermattis** [comment]
I have a series of commits which fixes this, though there is clean up work to be done around the edges before sending a PR.
