### ISSUE TITLE
clean up key comparisons wrt range-local addressing

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#2198]
due to range-local addressing, there are two types of keys:

those for which `keys.KeyAddress(key)` is the identity, and those for which it strips the range-local prefix. We're inconsistent in taking this into account. For example, `(*RangeDescriptor).ContainsKey{,Range}` doesn't check it, and there are various other locations that simply use `.Less()` when they probably should not.

On top of that, we're not properly taking into account the fact that we don't want to allow key ranges which begin locally but end globally. This isn't really used anywhere, but should be cleaned up.

I suggest updating all functions that deal with key (ranges) being "contained" to use `KeyAddress` properly and scan the codebase for all uses of `.Less` and `bytes.Compare` which may need to be aware of the distinction.

**Comment by bdarnell** [comment]
This is related to #437.

**Comment by petermattis** [comment]
Once we lock down the kv endpoints, user data will be entirely in tables and prefixed with `\xff[\x08-\x10]`: `\xff` is `TableDataPrefix` and `[\x08-\x10]` is the first byte of the encoded table id.

**Comment by tschottdorf** [comment]
This isn't really the issue, it's more about, for example, the transaction table and other things which are in the range-local range specifically.

**Comment by tschottdorf** [comment]
reminder for myself: when addressing this, take care of `TestTruncate` from #2141.

**Comment by tschottdorf** [comment]
another reminder: there's a TODO in `TestMultiRangeEmptyAfterTruncate` from #2141.
