### ISSUE TITLE
Distributed transactions

### ISSUE THREAD

**Issue by andybons** [cockroachdb/cockroach#22]
This is an umbrella issue for now for accounting purposes. Smaller issues should be created for the various paths a transaction can take.

**Comment by yorkxu** [comment]
Hi, 
I read the distribute transaction part of cockroach desin doc. 
I have some doubt about how to choose a timestamp:

> For multiple nodes, the timestamp of the node coordinating the transaction t is used. In addition, a maximum timestamp t+ε is supplied to provide an upper bound on timestamps for already-committed data (ε is the maximum clock skew). As the transaction progresses, any data read which have timestamps greater than t but less than t+ε cause the transaction to abort and retry with the conflicting timestamp tc, where tc > t. The maximum timestamp t+ε remains the same. This implies that transaction restarts due to clock uncertainty can only happen on a time interval of length ε.

If the data read have timestamp greater than t-ε but less than t, how to decide whether that transaction write this data committed before start timestamp of the read transaction or after?

Or there is other mechanism can guarantee all data which have timestamp greater than t-ε but less than t has commited before the transaction above start?

Thank you very much.

**Comment by tschottdorf** [comment]
Hi @yorkxu, the transaction won't read such data (it will come back with a higher timestamp). We optimize that a bit more using the node's timestamp (which limits these restarts to one per node), but essentially within that uncertainty interval [t, t+eps) you will restart as you encounter values, moving your start timestamp forward. If you pass `t+eps`, you know that anything that you see after must have started after you in absolute time.
We never read uncommitted values. If there is a provisional value, the standard intent resolution procedures kick in.
If you find committed values in your past (maybe that's what you're asking about?), of course you always read them.

I hope that helped,
Tobias

**Comment by yorkxu** [comment]
Thank you @tschottdorf  

If a transaction named txn1 has start timestamp  t1. As the transaction progress, it read a data with commit timestamp  t2 (t2 is greater than t1-ε but less than t, ε is the maximum clock skew), then will txn1 read this data?

Thank you very much

**Comment by tschottdorf** [comment]
t1 will read t2's write (which is in its past) if t2 has committed at that point. That is, either there is a committed value or it sees a provisional value and checks on t2's central transaction record. This record will either confirm the value as committed (in which case again it is read) or not committed, in which case t2 and t1 will undergo conflict resolution and the result of the read depends on its outcome (and may have to mean that t1 has to wait for t2 to complete if it can't abort it).

**Comment by tschottdorf** [comment]
See also the section "Transaction interactions" in https://github.com/cockroachdb/cockroach/blob/master/docs/design.md.
