### ISSUE TITLE
build-cache: unnecessary rebuilds on circleci?

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#2212]
Since the upgrade to go 1.5 I'm seeing slightly increased circleci run times. The culprit seems to be unnecessary rebuilds of various tools:

```
+ go install -v github.com/cockroachdb/c-protobuf/cmd/protoc github.com/cockroachdb/yacc github.com/gogo/protobuf/protoc-gen-gogo github.com/golang/lint/golint github.com/jteeuwen/go-bindata/go-bindata github.com/kisielk/errcheck github.com/tebeka/go2xunit golang.org/x/tools/cmd/goimports golang.org/x/tools/cmd/stringer
github.com/cockroachdb/c-protobuf/cmd/protoc
github.com/gogo/protobuf/protoc-gen-gogo
github.com/golang/lint/golint
github.com/jteeuwen/go-bindata/go-bindata
github.com/kisielk/errcheck
golang.org/x/tools/cmd/goimports
golang.org/x/tools/cmd/stringer

real	2m30.526s
user	2m29.908s
sys	0m11.002s
```

Need to track down why these tools are not being cached appropriately.

**Comment by petermattis** [comment]
So strange. In build [#6345](https://circleci.com/gh/cockroachdb/cockroach/6345) I can see the build-cache can't find cache entry for `github.com/cockroachdb/c-protobuf/cmd/protoc` (sha `959b11f7965e97d6b213d69d83c7cf668ad671c9`). But looking [#6329](https://circleci.com/gh/cockroachdb/cockroach/6329) which was about 19 hours earlier, the cache definitely has the desired sha. The circleci cache directory behavior is so strange.

**Comment by tamird** [comment]
@petermattis is it possible an intervening build didn't include the change to go1.5? i'm imagining a branch that hasn't been rebased.

**Comment by petermattis** [comment]
The branch for build #6345 was created this morning while I was on the train. It definitely was created from a master branch that has the go1.5 change.

**Comment by petermattis** [comment]
This doesn't seem to be happening any more. Closing until it reappears.
