### ISSUE TITLE
scripts: release note contributor list should clarify first-time contributors

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#22206]
@bdarnell in https://github.com/cockroachdb/cockroach/pull/21515#discussion_r164614015

> It's confusing to see first-time contributors who don't appear in the preceding list (as in this week's release). I think we should either exclude CRDB employees from the first-timers list (my first choice) or say something about who these first-time non-community contributors are.

The core of the issue is that a person who joins CRL without any prior experience contributing to CockroachDB would never appear in the release notes. This is quite unfair.

We need to find a good way to solve this. @jseldess how do you propose to format the "first time contributor" section so as to properly highlight everything without being unfair to new CRL employees?

**Comment by jseldess** [comment]
Hmm, to me, it is a bit strange to thank employees. Makes sense for external contributors. So I'd opt to just remove employees, but if you feel strongly, @knz, We could do something like:

> We would like to thank the following contributors from the CockroachDB community, with special thanks to first-time contributors:
> - Aye Aye
> - Bee Bee (first-time)
> - Cee Cee
> - Dee Dee (first-time, employee)
> We would also like to congratulate the following Cockroach Labs employees for their first-time contributions:
> - Ben Darnell
> - Spencer Kimball
