### ISSUE TITLE
distsql: SHOW KV TRACE does not work for distributed queries

### ISSUE THREAD

**Issue by solongordon** [cockroachdb/cockroach#22216]
Distsql execution ignores the `set trace=kv` session flag, so `SHOW KV TRACE FOR SESSION` does show row-level info for distsql queries. This seems to mainly be a case of missing plumbing. See TODO here: https://github.com/cockroachdb/cockroach/blob/bfbc66dbf9b444a38afb49a0f7dc2907060d7d4e/pkg/sql/distsqlrun/tablereader.go#L183-L187.

**Comment by jordanlewis** [comment]
This got fixed.
