### ISSUE TITLE
sql: use IDs for columns instead of names in serialized expressions/queries

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#22212]
Instead of storing the name of columns in expressions, we should instead store column IDs.  This makes renaming a column super quick.  And should speed up evaluation as no string matching needs to occur.  

Applications:

- view queries
- stored DEFAULT and CHECK expressions
- perhaps other places (e.g. the statement used for a background job?)

**Comment by knz** [comment]
@BramGruneir can you remind me what prompted this issue? Where do we store expressions in a place that would benefit from storing IDs instead?

**Comment by BramGruneir** [comment]
This was prompted from when I was exploring some of the column renaming logic.  It seemed to me that we optimized for the wrong part, the pretty printing, instead of the more common case of evaluation.  Evaluating any expression should never rely on the column names and they should be converted to IDs as soon as possible.  

It's been a while since I looked at that code, but I remember being confused by it.

**Comment by knz** [comment]
FYI the column names are converted to numeric IDs very early on (during name resolution), so for the purpose of query execution we already do what you suggestion.

The one area where this is not yet true is when storing an expression in a descriptor, e.g. for DEFAULT or CHECK. Was this what you had in mind?

**Comment by BramGruneir** [comment]
Yep.  I was dealing with both of those during my deep dive into FK land.

**Comment by knz** [comment]
Ok then this issue greatly overlaps with #10083.

What we need is a serialization format which doesn't embed names, just IDs. USe that both for views and other things that store queries/expressions.

**Comment by knz** [comment]
For reference, how postgres does it: when a SQL query/expression gets serialized, it translates the names of things (table names, column names etc) to OIDs, and it stores the OID. The OID is translated back to a name when pretty-printing.

We may be able to do something similar.

**Comment by ajwerner** [comment]
Related to #56592 and #24559.

**Comment by ajwerner** [comment]
Duplicates #10083.
