### ISSUE TITLE
sql: scan should propagate how many rows it expects to kv fetcher

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#22219]
The KV fetcher accepts a hint for the size (in keys) of the batches it will return. Currently, as far as I can tell, the only queries that set that hint are queries with `LIMIT` clauses.

Simple scans that know how many rows they expect should set this limit hint as well. Doing so will enable optimizations at lower levels of the code that try to allocate a reasonable amount of memory for these batches in one go. See #21855.

**Comment by jordanlewis** [comment]
To do this properly I think we need to know when spans are tight. I don't really know how to get this information without plumbing it all the way from the part of index selection that creates spans from filters when possible.

Is there another way? Maybe we can just iterate over all the spans and see whether their end keys are the PrefixEnd of their start keys.

**Comment by petermattis** [comment]
> Is there another way? Maybe we can just iterate over all the spans and see whether their end keys are the PrefixEnd of their start keys.

That sounds expensive.

**Comment by jordanlewis** [comment]
Yeah, true

**Comment by jordanlewis** [comment]
cc @knz

**Comment by RaduBerinde** [comment]
I believe that we do propagate limit hints today.
