### ISSUE TITLE
sql: support other arguments to encode/decode

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#22233]
We currently only support `"hex"`. We should support `"base64"` and `"escape"` as well.

A warning on this issue - `cockroach --sql` and `psql` display bytestrings differently. Highly advise using `psql` to test your implementation, rather than `cockroach --sql` to avoid confusion.

https://www.postgresql.org/docs/10/static/functions-binarystring.html

**Comment by bsnyder788** [comment]
I will try my hand at this one @justinj

**Comment by nathanaaron** [comment]
base64 encode and decode would be extremely helpful for us.

**Comment by knz** [comment]
`escape` implemented in #23512, `base64` in #25002. Work completed.
