### ISSUE TITLE
ui: investigate incorporating NPS survey tool into admin UI

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#22246]
We want to be able to ask users for feedback on the admin UI - investigate what it looks like to incorporate a tool here. If it gets to complicated to add this in, this may slip into 2.1.

cc @vilterp and @couchand -> I can take this on for now

**Comment by couchand** [comment]
My gut reaction is that this raises too many questions to address to be able to squeeze it in, but I'll leave final judgement until we see the results of your investigation.

**Comment by dianasaur323** [comment]
haha, i think your gut might be right, but i'll take a quick look just in case.

**Comment by dianasaur323** [comment]
Popping over to @piyush-singh

**Comment by piyush-singh** [comment]
Moving this to Later - this definitely merits a follow up given the difficulty we have soliciting feedback, but we still need to flesh this out more completely.
