### ISSUE TITLE
sql: store stmtstats in internal table

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#22248]
The existing stmtstats table has proved useful in helping users optimize their queries and diagnose performance improvements. However, it is currently stored in memory and not persisted on disk.

Consider storing this data in an internal table. May be encompassed in the overall effort related to https://github.com/cockroachdb/cockroach/issues/19476, but tracking this issue here for now.

fyi @robert-s-lee

**Comment by vilterp** [comment]
A couple other options I've been discussing w/ @knz, @mrtracy, and @vivekmenezes:
- keep time series per query fingerprint — something like `cr.stmtstats.[query fingerprint].{latency, rows_returned, count}.[node]`
- keep time series per table — `cr.tablestats.[table name].{inserts, selects, updates, deletes}.[node]`

These would probably need to be at 1hr resolution to prevent data blow-up.
