### ISSUE TITLE
sql: table does not exist when repeatedly dropping/recreating database

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#22256]
The following will occasionally flake on the `INSERT` lint with `relation "foo" does not exist` if run in a loop

```
sqlDB.Exec(t, `DROP DATABASE IF EXISTS test`)
sqlDB.Exec(t, `CREATE DATABASE test`)
sqlDB.Exec(t, `CREATE TABLE foo (a INT PRIMARY KEY)`)
sqlDB.Exec(t, `INSERT INTO foo VALUES (1), (2), (3)`)
```

Discovered by some workload test flakes. Pushing a skipped test that references this issue soon. Assigning to @vivekmenezes for triage.

**Comment by vivekmenezes** [comment]
please do push the skipped test but I'd like to unskip it through a fix that's under review.
Thanks!

https://github.com/cockroachdb/cockroach/pull/21686

**Comment by danhhz** [comment]
Merged! You should now be able to pull past it an unskip in your PR

**Comment by vivekmenezes** [comment]
Much appreciated!
