### ISSUE TITLE
sql: create a Table interface

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#22275]
in the SQL code we maintain a cache of table descriptors currently stored in the LeaseManager. The LeaseManager has methods like getTableVersion() that return a ```*TableDescriptor``` which in turn is used everywhere in the code. Unfortunately there is no place to store table specific information that can be computed once as opposed to repeatedly computed on every SQL query.

This proposal is around creating a new TableInterface and passing it around in the code. The Table Interface can initially contain an embedded TableDescriptor. We can then go about speeding up functions that ask questions like, "Does this table have a computed column".

I suspect this is also going to cleanup code that combines columns and mutation columns and similarly for indexes.

**Comment by vivekmenezes** [comment]
#31794

**Comment by vivekmenezes** [comment]
@BramGruneir as discussed this is the issue for the ExtendedTableDescriptor. We do need a better name.

**Comment by BramGruneir** [comment]
Thanks @vivekmenezes!

**Comment by eriktrinh** [comment]
Added immutable and mutable table descriptor in #32603 and #31794.
