### ISSUE TITLE
storage: Wake ranges in background on node failure

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#22286]
Throughput drops substantially after node failure, especially in low-concurrency clients. This is because each request that wakes a new range must block until it has gone through its raft election and lease acquisition. 

If instead of waking ranges up solely on user activity, we had a queue to wake up ranges in the background (ideally prioritized by how much traffic they've gotten recently), we could move this latency out of the user-visible path. We'd have to be careful not to overwhelm the cluster with this election traffic, though, and to ensure that waking up an idle range is done at a lower priority than user-facing traffic.

**Comment by knz** [comment]
cc @nvanbenschoten for re-triage

**Comment by nvanbenschoten** [comment]
This is still a good idea that we'll want to explore when we focus on failure recovery again.
