### ISSUE TITLE
perf: investigate protobuf marshaling optimization

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#22280]
All of our protobuf marshaling code has a pattern that looks like:

```
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
```

We're allocating a zero-initialized slice and then overwriting it. Per #22244, we could do a similar hack to allocate an uninitialized slice.

**Comment by nvanbenschoten** [comment]
Closing because this did not appear to make a noticeable impact on performance.
