### ISSUE TITLE
Include channel partner information in diagnostic reporting

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/cockroach#22283]
We’ve seen a lot of interest from partners like Red Hat and Mesosphere in offering CockroachDB containers in their marketplaces. Unfortunately, we have no way of knowing which channels are actually useful to customers. 

Let’s update the CockroachDB binary to check for an environment variable (most likely set in a Dockerfile) indicating the channel through which the container was obtained. This will let us hold ourselves and our partners accountable for making CockroachDB available in the best locations for our users. 

This update should ultimately send simple strings like “red hat container store” or “dc/os universe”

And of course, this must honor the user's [reporting preferences](https://www.cockroachlabs.com/docs/stable/diagnostics-reporting.html).

**Comment by dt** [comment]
I was wondering if it made sense to use ldflags inject the intended distribution channel in to the binaries themselves when we package for these platforms /cc @benesch

**Comment by benesch** [comment]
Yeah, my conclusion was we'll want to allow channels to be both baked into the binary and dynamically set via an environment variable.
