### ISSUE TITLE
sql: DMLs with RETURNING stream results that violate constraints

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#22304]
```
\set display_format csv
create table a(a int primary key);
insert into a values(1);
insert into a select generate_series(1,3000) returning a;
```

If you run this, you'll see that the last statement returns `1` to the client immediately, despite the fact that the statement will not eventually commit because `1` violates the unique constraint.

Related to #20732.

**Comment by knz** [comment]
will followup in #23156
