### ISSUE TITLE
sqlccl: sqlccl testrace flaky - time out after 25m (TestRepartitioning reported)

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#22308]
Seen on master build and also on one of my random builds

https://teamcity.cockroachdb.com/viewLog.html?buildId=502728&buildTypeId=Cockroach_UnitTests

The test running when the timeout hits is TestRepartitioning, but I don't know if that's the culprit.

**Comment by benesch** [comment]
Closing in favor of #22360.
