### ISSUE TITLE
Support XA distributed transactions in CockroachDB

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#22329]
[X/Open XA](https://en.wikipedia.org/wiki/X/Open_XA) is a standard for distributed transaction processing *across multiple database engines*. This is used in enterprise scenarios where data is spread across different technologies but applications need to preserve ACID semantics for transactions that span multiple database engines.

PostgreSQL supports XA transactions by a combination of two mechanisms:
- internally it supports the [`PREPARE TRANSACTION`](https://www.postgresql.org/docs/9.3/static/sql-prepare-transaction.html) statement which enables a SQL transaction manager (TM) to "take over" transaction management
- the official pg ODBC driver contains an implementation of the standard MSDTP API (Microsoft's view on what XA should look like), so that pg becomes interoperable with other MSDTP-aware databases.
- ditto JDBC

For enterprise users CockroachDB should provide a path towards XA compatibility:

- provide a mechanism / API so that an external TM can take over transaction control in CockroachDB
- provide one or more driver extension that interoperates with one or more industry standard API (perhaps MSDTP or the java equivalent)

Strict compatibility with pg's `PREPARE TRANSACTION` would enable providing a XA API via pg's own ODBC driver.

cc @awoods187 for prioritization. cc @bdarnell for technical insights.

Also mentioned here: https://forum.cockroachlabs.com/t/xa-distributed-transactions/1336

Jira issue: CRDB-5863

**Comment by SebTardif** [comment]
While looking if I 'could' use CockroachDB instead of PostgreSQL, I found out this was not yet implemented. It's a big deal. Without it you end-up with convoluted solution like -> https://senoritadeveloper.medium.com/microservices-transaction-management-patterns-46ef2df9a9c4

This would probably help thinking about how to test it -> https://docs.hazelcast.com/hazelcast/5.2/pipelines/xa

**Comment by nvanbenschoten** [comment]
Closing as complete, now that the following PRs have merged:
* https://github.com/cockroachdb/cockroach/pull/129295
* https://github.com/cockroachdb/cockroach/pull/129297
* https://github.com/cockroachdb/cockroach/pull/129298
* https://github.com/cockroachdb/cockroach/pull/137409
* https://github.com/cockroachdb/cockroach/pull/129448
* https://github.com/cockroachdb/cockroach/pull/137457

Remaining work will be tracked in more specific issues(https://github.com/cockroachdb/cockroach/issues/137636 and https://github.com/cockroachdb/cockroach/issues/137549).
