### ISSUE TITLE
sql: support any/some/all for non-homogenous comparisons

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#22333]
For any/some/all we currently require that the values on the right are all the same type as the value on the left. This prevents their use with things like the JSON "exists" operator `?`. This would be particularly nice because it would allow us to desugar `?&` and `?|` into any/some/all rather than as distinct operators.

cc @andy-kimball @knz 

Jira issue: CRDB-5862

**Comment by mgartner** [comment]
We're having a hard time understanding the potential benefit of this, so I've closed it.
