### ISSUE TITLE
Support for the decode() function

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#22331]
**FEATURE REQUEST**

A user in this [forum post](https://forum.cockroachlabs.com/t/cockroach-v2-0-alpha-20180129-insert-fails-type-string-doesnt-match-type-bytes/1337/2) expected to be able to use Postgres's [`decode()`](https://www.postgresql.org/docs/9.4/static/functions-binarystring.html) function to insert a hexadecimal byte array into a `BYTES` column.

cc: @awoods187, @knz

**Comment by justinj** [comment]
We do have this in the version of Cockroach this user was using, but I recently changed it to be (I thought) the same as the Postgres one - I think something strange is going on with the types, I will investigate.

**Comment by jseldess** [comment]
Oh, I missed that. Thanks for the clarification, @justinj. I'll update the post.

**Comment by justinj** [comment]
After discussing with @knz we realized that the fix, in #22230, was actually not part of the most recent alpha, so the next release should fix the user's problem.

**Comment by justinj** [comment]
To clarify, there *was* an implementation of this in the version the user was using, but it had a bug.
