### ISSUE TITLE
sql: TestLogic/5node-distsql/distsql_join flaky - EXPLAIN(DISTSQL) has some non-determinism?

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#22342]
I got the following in a stress. The two plans render identically as far as I can tell, and yet there is a small different in the encoding towards the end of the string.

@RaduBerinde do you want this? I'd take it but I'm freaking out about something else at the moment...

        --- FAIL: TestLogic/5node-distsql/distsql_join (7.34s)
        	logic.go:2070:
        		testdata/logic_test/distsql_join:90: SELECT "URL" FROM [EXPLAIN (DISTSQL) (SELECT * FROM (SELECT a,b FROM data AS data1) JOIN (SELECT c,d FROM data AS data2 ORDER BY c,d) ON a=c AND b=d ORDER BY c,d)]
        		expected:
        		    https://cockroachdb.github.io/distsqlplan/decode.html?eJzclk1r20AQhu_9FWFOLdmCdyXnQ1DQNYUmJe2t-KBYW1vgeM1qDQ3B_73YSjGS4nk9rGuMj4r1aEazz-TVK81dae-LZ1tT9os0KTKkKCFFKSka0kjRwruxrWvn17c0wF35h7KBomq-WIb1n0eKxs5byl4pVGFmKaOfxdPMPtqitJ4UlTYU1WxTZOGr58K_5GURClL0sAzZRa5Vbmi0UuSW4e2Z20c9vVxMi3rafsw_ZKSoDsXEUqZX6n-1l6g87bS3rWskdX84H7olc32pcnMZ-_7Jzj62j3K-tN6WO-vvfec7r_bN-on96qp59_1m9nf4-IZ--uKryXR72TJA8YNO41_wnbbv3We3aN2_q_6wVV-ftv8HbU_gP6h7NP_1uftvTtu_g7Yn8A_UPZp_5tz9S07bv4O2J_AP1D2af8m5-5eetn8HbU_gH6h7NP_Sc_cPfOg_2nrh5rXd68tysH4fW05sM63aLf3YfvduvCnTXD5suM2HTWnr0PyaNBd38-andYP7wzcxsDZR9FUMbQY8rbv0oEW34EEXNoKBGxl8EwN3Bi6lr2LozsB7dMIOPOVPK-VPS_PHNYzZDx4G-8HDaD8ADfaDp9F-XLETv-YHfh2zHzwM9oOH0X4AGuwHT6P9uInZj9sYw3kYGM7DyHBAA8N5GiZAL0BaE9fgn4ruJYhEckADywGNNEc48BzgSHTdyxGJ6bqXIxLVAQ1cBzSSHeHAdoBD3fkM1UOguyRE-2cuSVEpDXUX5agUh7rzSYp0l0SplEa6i8JUjCPdRXHax_k81bdAd0mi9s9cEqlSGuouClUpjnQ3fKp2dR-tPvwNAAD__1XEQ9M=

        		but found (query options: "") :
        		    https://cockroachdb.github.io/distsqlplan/decode.html?eJzclk1r20AQhu_9FWFOLdmCdyXnQ1DQNYUmJe2t-KBYW1vgeM1qDQ3B_73YSjGS4nk9rGuMj4r1aEazz-TVK81dae-LZ1tT9os0KTKkKCFFKSka0kjRwruxrWvn17c0wF35h7KBomq-WIb1n0eKxs5byl4pVGFmKaOfxdPMPtqitJ4UlTYU1WxTZOGr58K_5GURClL0sAzZRa5Vbmi0UuSW4e2Z20c9vVxMi3rafsw_ZKSoDsXEUqZX6n-1l6g87bS3rWskdX84H7olc32pcnMZ-_7Jzj62j3K-tN6WO-vvfec7r_bN-on96qp59_1m9nf4-IZ--uKryXR72TJA8YNO41_wnbbv3We3aN2_q_6wVV-ftv8HbU_gP6h7NP_1uftvTtu_g7Yn8A_UPZp_5tz9S07bv4O2J_AP1D2af8m5-5eetn8HbU_gH6h7NP_Sc_cPfOg_2nrh5rXd68tysH4fW05sM63aLf3YfvduvCnTXD5suM2HTWnr0PyaNBd38-andYP7wzcxsL6Kok0MbQY8rbv0oEW34EEXNoKBGxl8EwN3Bi6lTQzdGXiPTtiBp_xppfxpaf64hjH7wcNgP3gY7QegwX7wNNqPK3bi1_zAr2P2g4fBfvAw2g9Ag_3gabQfNzH7cRtjOA8Dw3kYGQ5oYDhPwwToBUhr4hr8U9G9BJFIDmhgOaCR5ggHngMcia57OSIxXfdyRKI6oIHrgEayIxzYDnCoO5-hegh0l4Ro_8wlKSqloe6iHJXiUHc-SZHukiiV0kh3UZiKcaS7KE77OJ-n-hboLknU_plLIlVKQ91FoSrFke6GT9Wu7qPVh78BAAD__1-IQ9M=

**Comment by RaduBerinde** [comment]
![image](https://user-images.githubusercontent.com/16544120/35758180-705e0446-0827-11e8-9f75-aab645216c76.png)

It looks like we are outputting the edges from a router in a non-deterministic order.

**Comment by RaduBerinde** [comment]
It looks like every now and then two nodes "swap places" in the span partitioning, even though the partitioning is set up by the test (and verified via `SHOW TESTING_RANGES`).

Expected:
```
span partitions:
1 -/1 /5-/6
2 /1-/2 /6-/7
3 /2-/3 /7-/8
4 /3-/4 /8-/9
5 /4-/5 /9-
span partitions:
1 -/1 /5-/6
2 /1-/2 /6-/7
3 /2-/3 /7-/8
4 /3-/4 /8-/9
5 /4-/5 /9-
```

Failure:
```
span partitions:
1 -/1 /5-/6
2 /1-/2 /6-/7
4 /2-/3 /7-/8
3 /3-/4 /8-/9
5 /4-/5 /9-
span partitions:
1 -/1 /5-/6
2 /1-/2 /6-/7
4 /2-/3 /7-/8
3 /3-/4 /8-/9
5 /4-/5 /9-
```

I looked through the logs and I notice:
```
I180203 20:03:47.601410 1317 storage/replica_command.go:1745  [n1,s1,r4/1:/Table/51/1/{3-4}] change replicas (ADD_REPLICA (n3,s4):2): read existing descriptor r4:/Table/51/1/{3-4} [(n1,s1):1, next=2]

I180203 20:03:47.872470 1317 storage/store.go:3655  [n1,s1,r8/1:/Table/51/1/{7-8}] streamed snapshot to (n4,s3):?: kv pairs: 9, log entries: 5, rate-limit: 2.0 MiB/sec, 0ms
```

So we have node 3 with store 4 and node 4 with store 3. The values in `TESTING_RELOCATE`, `TESTING_RANGES` are store IDs.

I see two possibilities:
 - fix things so that for the purposes of the logic test, the store IDs always match the node IDs
 - change the commands to support node IDs instead of store IDs

**Comment by RaduBerinde** [comment]
I don't understand how getting mismatched node and store IDs is possible. It looks like test servers are started one at a time, and allocation of node and store IDs happens synchronously as part of start. But it does happen:
```
MEH allocated Node ID 1
MEH allocated Store ID 1
MEH allocated Node ID 2
MEH allocated Store ID 2
MEH allocated Node ID 3
MEH allocated Store ID 3
MEH allocated Node ID 4
MEH allocated Node ID 5
MEH allocated Store ID 4
MEH allocated Store ID 5
```

I am probably missing some path where the store ID gets allocated later.

**Comment by RaduBerinde** [comment]
Ah, there is the `n.bootstrapStores` call that runs in a `RunAsyncTask`. The least invasive fix would be to add a channel to notify when the stores are bootstrapped and have testserver wait for that.
