### ISSUE TITLE
sql: panic: Non-nullable column "users:isRole" with no value

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#22386]
This looks like it happened during server start.

```
panic: Non-nullable column "users:isRole" with no value! Index scanned was "primary" with the index key columns (username) and the values ('placeholder')

goroutine 1080 [running]:
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*RowFetcher).finalizeRow(0xc420455bc0, 0x2e96b40, 0xc42188a990)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/rowfetcher.go:1128 +0x96f
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*RowFetcher).NextRow(0xc420455bc0, 0x2e96b40, 0xc42188a990, 0xc42152a870, 0x3, 0x3, 0x0, 0x0, 0x0, 0x0)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/rowfetcher.go:898 +0x180
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*tableReader).Next(0xc420455500, 0xc420455530, 0x1, 0x1, 0x0)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/tablereader.go:200 +0x31a
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.Run(0x2e96a80, 0xc4215d9340, 0x2e977c0, 0xc420455500, 0x2e82600, 0xc420ee2240)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go:159 +0x35
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*tableReader).Run(0xc420455500, 0xc4212e2530)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/tablereader.go:132 +0x6b
created by github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Start
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:466 +0x3c5
```

https://teamcity.cockroachdb.com/viewLog.html?buildId=506175&buildTypeId=Cockroach_Nightlies_RandomSyntaxTests

Assigning for triage since it looks related to rbac stuff.

Found with RSG.

**Comment by mjibson** [comment]
Another:

https://teamcity.cockroachdb.com/viewLog.html?buildId=505468&buildTypeId=Cockroach_Nightlies_RandomSyntaxTests

```
panic: Non-nullable column "users:isRole" with no value! Index scanned was "primary" with the index key columns (username) and the values ('placeholder') [recovered]
    panic: panic while executing 1 statements: DROP USER _, _, _; caused by Non-nullable column "users:isRole" with no value! Index scanned was "primary" with the index key columns (username) and the values ('placeholder') [recovered]
```

**Comment by mberhault** [comment]
My guess would be that the backfill isn't done running, but I'm not completely sure.
The second failure shows:
```
SQL panic has occurred while executing "DROP USER PLACEHOLDER , PLACEHOLDER , PLACEHOLDER": Non-nullable column "users:isRole" with no value! Index scanned was "primary" with the index key columns (username) and the values ('placeholder')
```

Is there a way to know exactly what the query was?

For the first one, I can't tell what it's doing. Still guessing on unfinished backfill though.

**Comment by mjibson** [comment]
I don't think there's a way to see what query specifically was being run since we anonymized them. However this is happening very fast every day on the RSG tests, so if you run them yourself it should repro immediately.

**Comment by mberhault** [comment]
There's nothing odd about the statements being run. However, I'm unable to reproduce this when running with `-rsg-routines=1`. Anything higher than that causes problems.
Is it possible the way the test is being run causes issues?

**Comment by mberhault** [comment]
Ok, that's definitely due to multiple goroutines. When running with just two, I'm seeing one stall while the other runs approximately 30 statements.

Here's an example of the statements run, prefixed with the worked ID. The `Found: ...` is output of a `select * from system.users`.

The callback to `testRandomSyntax` select all users and prints them, then prints `Executing ...`, executes the statement, then prints `Finished ...`.

Worker 1 is in the middle of executing a `ALTER USER`:
```
##### [1] Found: "admin" "" true
##### [1] Found: "bit" "$2a$10$KUGlLVPcyiIXyvXaQzdqFucGyGnT2YrRKhRb9szfDC8W1kbpPRjMu" false
##### [1] Found: "error" "" false
##### [1] Found: "extract_duration" "$2a$10$aPu335nssG.s14ydHwgvK.xy8CIIFOrMWkbwNYL8YhA7Gi6qO6R7q" false
##### [1] Found: "like" "$2a$10$Qd.m1tIle3mWEcsvG2Sws.U3MRmKBaQNhPPkyM2WdOjef5t1TqKxS" false
##### [1] Found: "placeholder" "$2a$10$Tx8RuTSdt13D/eXzDu8ht.UWg7NsqZ1fLHsJVyYc5ds2QtqOJxT/e" false
##### [1] Found: "root" "" false
##### [1] Found: "string" "$2a$10$OfmNoUms4erfEXOLs3TU8uS.XDmMJmTWSByB8fNu8G6li4eBn0Caa" false
***** [1] Executing "ALTER USER IF EXISTS PLACEHOLDER WITH PASSWORD TIMESTAMPTZ"
```

No results for a while from worker 1. During that time, worker 0 executes approximately 35 statements, including:
```
##### [0] Found: "admin" "" true
##### [0] Found: "bit" "$2a$10$KUGlLVPcyiIXyvXaQzdqFucGyGnT2YrRKhRb9szfDC8W1kbpPRjMu" false
##### [0] Found: "error" "" false
##### [0] Found: "extract_duration" "$2a$10$aPu335nssG.s14ydHwgvK.xy8CIIFOrMWkbwNYL8YhA7Gi6qO6R7q" false
##### [0] Found: "like" "$2a$10$Qd.m1tIle3mWEcsvG2Sws.U3MRmKBaQNhPPkyM2WdOjef5t1TqKxS" false
##### [0] Found: "placeholder" "$2a$10$Tx8RuTSdt13D/eXzDu8ht.UWg7NsqZ1fLHsJVyYc5ds2QtqOJxT/e" false
##### [0] Found: "root" "" false
##### [0] Found: "string" "$2a$10$OfmNoUms4erfEXOLs3TU8uS.XDmMJmTWSByB8fNu8G6li4eBn0Caa" false
***** [0] Executing "DROP USER IF EXISTS PLACEHOLDER , 'string' , PLACEHOLDER , PLACEHOLDER , JOIN"
***** [0] Finished "DROP USER IF EXISTS PLACEHOLDER , 'string' , PLACEHOLDER , PLACEHOLDER , JOIN": <nil>
```

This succeeds.

Finally, worker 1 gets to print the executed statement poking at user `PLACEHOLDER` with no error:
```
***** [1] Finished "ALTER USER IF EXISTS PLACEHOLDER WITH PASSWORD TIMESTAMPTZ": <nil>
```

But the server panics with:
```
panic: Non-nullable column "users:isRole" with no value! Index scanned was "primary" with the index key columns (username) and the values ('placeholder')
```

The reason for the delay is simple: `ALTER USER ... WITH PASSWORD ...` changes the password. This includes running bcrypt to compute the password hash. It's supposed to take a while.

**Comment by mberhault** [comment]
btw: alter just runs the following:
```
  internalExecutor := InternalExecutor{ExecCfg: params.extendedEvalCtx.ExecCfg}
  n.run.rowsAffected, err = internalExecutor.ExecuteStatementInTransaction(
    params.ctx,
    "create-user",
    params.p.txn,
    `UPDATE system.users SET "hashedPassword" = $2 WHERE username = $1 AND "isRole" = false`,
    normalizedUsername,
    hashedPassword,
  ) 
```

Is there any reason this would be problematic if someone else deletes the entire row?

**Comment by mjibson** [comment]
(Just FYI, you're going to have to assign or ping someone else to this bug if you want help. I only reported it because I watch the RSG stuff. Someone from the SQL team should be helping here.)

**Comment by mberhault** [comment]
@jordanlewis: could you take a look?

**Comment by jordanlewis** [comment]
Hmm... will take a look at this now.

**Comment by vivekmenezes** [comment]
@mberhault sounds like you are able to reproduce this. Can you paste the instructions?

**Comment by mberhault** [comment]
This is just from the RSG runner: https://teamcity.cockroachdb.com/viewLog.html?buildId=506175&buildTypeId=Cockroach_Nightlies_RandomSyntaxTests&tab=buildLog&_focus=457

```
build/builder.sh make test PKG=./pkg/sql/tests TESTS=TestRandomSyntax 'TESTFLAGS=-v -rsg=10m -rsg-routines=20' TESTTIMEOUT=1h
```

Or simplified to:
```
pkq/sql/tests$ go test --run TestRandomSyntaxGeneration --rsg-routines=2 --rsg=5s .
```

**Comment by vivekmenezes** [comment]
will take a look after the 15th

**Comment by mjibson** [comment]
Is anyone looking at this? It's still panicking and has been over a month. We should not release with this bug.

**Comment by vivekmenezes** [comment]
I'm looking at this

**Comment by mberhault** [comment]
I am no longer able to reproduce this with the above commands. At the time of the comment 26 days ago, it happened within seconds. I'll try to bisect this to see if it's an accidental fix, change in testing, or something else.

**Comment by mberhault** [comment]
Bisect shows a clear change in behavior at https://github.com/cockroachdb/cockroach/commit/8faa7bb55619640932ccea36e13d383f5323ccfc. Before this change, it failed almost instantly. After the change, I cannot make it fail even with increased concurrency or test duration. I'm not saying this is fixed, but it is marked as fixing https://github.com/cockroachdb/cockroach/issues/22543 which sounds incredibly similar.

**Comment by mberhault** [comment]
According to Spencer, https://github.com/cockroachdb/cockroach/commit/8faa7bb55619640932ccea36e13d383f5323ccfc fixes this change by properly taking tombstones into account when refreshing. This therefore should fix this problem. @mjibson: you mentioned 2 days ago that you were still seeing this panic. Is that the case? On more recent builds, my rsg runs have encountered some panics, but not this specific one.

**Comment by mjibson** [comment]
Oops, yes, RSG is erroring on other stuff now but it happened so seamlessly I didn't notice the error change. I think we can close this.

**Comment by mberhault** [comment]
Ah, good. I'm still glad I traced the commit though, it's comforting to know that it was a serious bug but it is fixed.

**Comment by vivekmenezes** [comment]
Thanks Marc, I was having nightmares about this one only yesterday
