### ISSUE TITLE
perf: investigate outbox batch sizes

### ISSUE THREAD

**Issue by asubiotto** [cockroachdb/cockroach#22385]
Whenever rows are sent over the wire in a distsql query, an `outbox` receives rows and buffers them before sending them over. This buffer policy is controlled by two factors:
https://github.com/cockroachdb/cockroach/blob/e74b46e2552608f85dbdc1ad32c98bce1a8c559d/pkg/sql/distsqlrun/outbox.go#L28
https://github.com/cockroachdb/cockroach/blob/e74b46e2552608f85dbdc1ad32c98bce1a8c559d/pkg/sql/distsqlrun/outbox.go#L29

That is, whenever an outbox has accumulated `outboxBufRows` or an `outboxFlushPeriod` has elapsed, the `outbox` sends over what it has. We could likely amortize the cost of sending rows over the network by making `outboxBufRows` larger (or dynamically determining the batch size). There is a tradeoff to consider here for queries that send over less rows than a batch.

This might include passing down information from upstream processors. Take a `TableReader` for example. It could be set up to tell when a `NextRow` call to the `RowFetcher` would produce a fetch, which would be a good time to flush the outbox.

**Comment by petermattis** [comment]
I'd be interested in knowing if the current tuning values in `outbox` were determined experimentally. `grpc` will group concurrent writes to different streams into the same network packets, so there may be no benefit to buffering at all.

**Comment by RaduBerinde** [comment]
> I'd be interested in knowing if the current tuning values in outbox were determined experimentally

Not AFAIK

**Comment by asubiotto** [comment]
Spun up a 6-node cluster to run `SELECT * FROM tpch.lineitem ORDER BY l_extendedprice LIMIT 1000`
![screen shot 2018-02-05 at 4 58 23 pm](https://user-images.githubusercontent.com/10560359/35830896-cc5c0840-0a95-11e8-8676-5b7292915063.png)

with `outboxBufRows` set to 1000 and `outboxFlushTicker` bumped up to `500*time.Millisecond` (don't think the ticker was necessary in this experiment) and got a 25% improvement (average latency over 7 runs)

**Comment by jordanlewis** [comment]
Wow, nice!

Do you have a sense of what class of queries would suffer given this bigger outbox? Ideally, we would be able to find the right point in the space of buffer size and flush ticker given some prior knowledge about what the query is expected to do.

**Comment by petermattis** [comment]
Very interesting. I'd be very anxious about changing the value of `outboxFlushTicker` as it seems easy to pessimize an existing workload. Can you see if the improvement is still present when only changing the value of `outboxBufRows`?

**Comment by asubiotto** [comment]
The average query latency stays the same when only changing `outboxBufRows`.

**Comment by jordanlewis** [comment]
I think we should explore making `outboxFlushTicker` a dynamic value that depends on the number of flushed outboxes per query. The longer a query lasts, the less it matters to have a long flush ticker.

For example, a flush ticker that creeps up to `500ms` won't significantly affect the latency of a query that returns in 100 seconds, even if there's 500 completely wasted milliseconds toward the end of the query's execution.

**Comment by asubiotto** [comment]
Interestingly enough, increasing the `outboxFlushTicker` to `500ms` and keeping `outboxBufRows` at `16` exhibited the same performance improvement on the query as having `outboxBufRows` at `1000`. A dynamic ticker would be an interesting idea to explore.

**Comment by jordanlewis** [comment]
Wow that is interesting. What if you had `outboxFlushTicker = 500ms` and `outboxBufRows=1`?

**Comment by asubiotto** [comment]
Same gains. I ran the query again with the original settings to confirm the performance hit with the same binary. This is very surprising, there might be a lower layer doing some batching but why wouldn't it get triggered by the ticker? We call the same `flush` function.

**Comment by asubiotto** [comment]
Tried `outboxBufRows=1` and `outboxFlushPeriod=100µs`, and also got the performance hit. Seems like the dominating factor is the ticker.

**Comment by jordanlewis** [comment]
Is there a bug that causes the flush ticker to do work even if the outbox is empty?

**Comment by asubiotto** [comment]
Not that I can see, there's a call to `flush` on every tick but it returns after checking for an empty `outbox`:
https://github.com/cockroachdb/cockroach/blob/ea109a8a2f4e14971c1b08939cb0ae4143187d04/pkg/sql/distsqlrun/outbox.go#L138

**Comment by petermattis** [comment]
> Not that I can see, there's a call to flush on every tick but it returns after checking for an empty outbox

But we're calling `flush()` 10,000 times per/sec per outbox. That can't be good for performance. I don't think a ticker is appropriate here. Rather we should be blocking on the upstream `RowChannel` and then using a timer whenever we have buffered rows.

**Comment by asubiotto** [comment]
Closing as there are no pending action items.
