### ISSUE TITLE
sql: ::: operator does not respect type parameterizations

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#22383]
I believe the ::: operator only understands *datum* types, although the expression it's applied to on the right is in fact, a *column* type:

```
root@:26257/> select 'hello':::string(3); 
+---------------------+
| 'hello':::STRING(3) |
+---------------------+
| hello               |
+---------------------+
(1 row)

Time: 333.078µs

root@:26257/> select 'hello'::string(3);
+--------------------+
| 'hello'::STRING(3) |
+--------------------+
| hel                |
+--------------------+
(1 row)

Time: 536.356µs
```

Happy to look into this if we deem it important, but in the interim assigning @knz for triage.

**Comment by knz** [comment]
@nvanbenschoten can you have a brief look and share in a comment what you think needs to be done here. It's unclear to me what the correct course of action is.
