### ISSUE TITLE
sql: support multi-table INSERT/UPSERT statements

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#22388]
Forking off from https://github.com/cockroachdb/cockroach/issues/19177#issuecomment-339704669.

Oracle has an extension for multi-table inserts: `INSERT ALL INTO foo VALUES (...) INTO interleaved_foo VALUES (...)`. We should consider introducing a similar extension. The
reason for the extension is that:
1. it would allow us to group writes to multiple tables into a single `client.Batch`. This is important because it makes it possible for writes to multiple tables to hit the 1PC transaction fast path. 
2. it would make it possible to write to multiple tables transactionally in an implicit txn. This in turn makes it possible to push all retry logic onto the server and avoid any explicit txn overhead.

This change has been prototyped in [this](https://github.com/nvanbenschoten/cockroach/commit/8531338593249e6400b41c6303aa09593a04342b) branch. Experimentation with the change in a privately reported issue showed expected results. When tables were not interleaved, the syntax demonstrated almost identical performance to running RETURNING NOTHING insert statements within a transaction. This makes sense because a KV batch containing writes to non-interleaved tables will always be split up by `DistSender` and parallelized. This reduces down to doing almost exactly the same amount of work as running multiple insert statements with RETURNING NOTHING. The only real difference in this case is that the multi-table insert statement can take advantage of the benefits of implicit txns while the parallel statements must be run in an explicit transaction. However, this overhead can be mostly avoided if the entire txn string is sent together like `BEGIN; INSERT ... RETURNING NOTHING; INSERT ... RETURNING NOTHING; COMMIT;`.

The biggest improvement comes when tables are interleaved. In this case, the single KV batch created by the multi-table insert statement can be sent as a 1PC transaction. This results in a huge win because we avoid the extra `EndTransactionRequest` latency and don't even need to write a transaction record. In my testing with upserts to two tables, this improved latency by over 50%!

Because this syntax is for the most part identical to parallel statements when tables are not interleaved, I think it's fair to look at this as a performance improvement specifically targetted at interleaved tables. In some sense, it parallels https://github.com/cockroachdb/cockroach/pull/19028.

**Comment by jordanlewis** [comment]
Awesome! If you haven't done so already, I would be interested to see how this affects TPCC performance when the dataset was loaded with `-interleave`.

**Comment by vivekmenezes** [comment]
related https://github.com/cockroachdb/cockroach/issues/20250

**Comment by nvanbenschoten** [comment]
@jordanlewis any specific queries you can point me to that would benefit from this syntax? I'm not seeing any transactions that consist solely of inserts.

**Comment by jordanlewis** [comment]
Hmm I didn't read at first that this only applies for transactions that consist solely of inserts.

You could use `tpcc -load` as a benchmark, though, since loading does exactly that.

**Comment by nvanbenschoten** [comment]
Sorry I was pretty unclear about that. This syntax can be used in any transaction, but its performance characteristics are equivalent to running multiple INSERTs with RETURNING NOTHING in all cases except implicit txns with interleaved tables. The key here is that we're able to access the 1PC txn fast-path if both of those criteria are met, which isn't possible with parallel statements.

**Comment by nvanbenschoten** [comment]
This idea is related to and obviated by the proposal in #16026.

**Comment by knz** [comment]
I believe this is supported in CockroachDB with 

```sql
with a as (insert ... returning...), 
        b as (insert ... returning...)
select count(*) from (table a union all table b)
```

**Comment by nvanbenschoten** [comment]
Will that actually put the writes into the same `client.Batch`?

**Comment by nvanbenschoten** [comment]
Transactional pipelining has eliminated most of the reason to add this functionality. The one remaining benefit of it is the ability to achieve 1PC transactions for writes to a set of interleaved tables. Moving to the "later" milestone.

**Comment by knz** [comment]
@nvanbenschoten do you think this is still relevant now we can have multiple insert statements as CTEs?

**Comment by nvanbenschoten** [comment]
> do you think this is still relevant now we can have multiple insert statements as CTEs?

This is a good point - I think we can close this.
