### ISSUE TITLE
sql: add support for {,NOT} {LIKE,SIMILAR TO}

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#2242]
LIKE is pattern matching. SIMILAR TO is regex matching. Both should be relatively straightforward to implement.

**Comment by nvanbenschoten** [comment]
@petermattis I can take `SIMILAR TO` if you want. It should be pretty straightforward, although we may need to work around some differences with the [SQL standard's definition](http://www.postgresql.org/docs/9.0/static/functions-matching.html) of a regular expression.

**Comment by vivekmenezes** [comment]
We should use the RE2 regexp package for this implementation. Any reason not to?

**Comment by tamird** [comment]
@nvanbenschoten go ahead.

@vivekmenezes is it worth the cgo shenanigans?

**Comment by bdarnell** [comment]
Go's regexp package is by the same author as RE2 (Russ Cox) and has the same basic design. What does RE2 do that go's regexps don't?

**Comment by petermattis** [comment]
Yes, just use Go's regexp package. We'll almost certainly need to handle the SQL regexp syntax. Can that be done via a transformation step just as you're doing for transforming `LIKE` patterns into regexps?

**Comment by jusongchen** [comment]
@peter, as for SIMILAR TO, would it better to implement it as a regular
expression function? e.g. Oracle has four regexp functions:


   - *REGEXP_LIKE*

SELECT first_name, last_name
FROM employees
WHERE REGEXP_LIKE (first_name, '^Ste(v|ph)en$');

see more detail at
http://docs.oracle.com/cd/B12037_01/server.101/b10759/conditions018.htm


   -  REGEXP_SUBSTR

SELECT
  REGEXP_SUBSTR('500 main street , Pleasanton, CA 94566',
                ',[^,]+,') "REGEXPR_SUBSTR"
  FROM DUAL;
//the above  looking for the first substring bounded by commas

see more details at
http://docs.oracle.com/database/121/SQLRF/functions164.htm#SQLRF06303


   -  REGEXP_REPLACE

SELECT
  REGEXP_REPLACE(country_name, '(.)', '\1 ') "REGEXP_REPLACE"
  FROM countries;

//the above replace append a whitespace to each charactor in country_name
see more detail at
http://docs.oracle.com/cd/B19306_01/server.102/b14200/functions130.htm


   -  REGEXP_INSTR

see details at
http://docs.oracle.com/database/121/SQLRF/functions162.htm#SQLRF06300


Implementing this as functions reduces reversed keywords with benefit of
 more simple and graceful syntax.

Regards,

Jusong


On Thu, Sep 17, 2015 at 2:05 PM, Ben Darnell <notifications@github.com>
wrote:

> Go's regexp package is by the same author as RE2 (Russ Cox) and has the
> same basic design. What does RE2 do that go's regexps don't?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/2242#issuecomment-141228196>
> .
>



-- 
Jusong Chen
408 315 2288

**Comment by petermattis** [comment]
@jusongchen I don't have the ANSI SQL standards on hand, but the postgres docs say that `SIMILAR TO` [was added to SQL:1999](http://www.postgresql.org/docs/9.4/static/functions-matching.html).

**Comment by bdarnell** [comment]
I'm not convinced we'll need the `SIMILAR TO` SQL-style regexes. Every database seems to have "real" regexes with posix-style syntax, often as a function instead of an operator (without a consistent name). The SQL-standard regexes with `_` and `%` wildcards seem to be less commonly implemented.

This [SO post](http://dba.stackexchange.com/questions/10694/pattern-matching-with-like-similar-to-or-regular-expressions-in-postgresql) says that SIMILAR TO was only in an early draft of the SQL standard.

**Comment by petermattis** [comment]
Ah, interesting: the postgres docs lie! I'd be happy to toss out the SQL-style regex syntax if it isn't actually a standard. Interestingly, `SIMILAR TO` seems to have infiltrated some other SQL databases (Firebird, Amazon Redshift, etc).

**Comment by jusongchen** [comment]
it seems  SIMILAR TO is part of ANSI standard. Here are a list of
predicates defined in SQL 2008:

<comparison predicate>,
 <between predicate>,
 <in predicate>,
 <like predicate>,
 <similar predicate>,
 <regex like predicate>,
 <null predicate>,
 <quantified comparison predicate>,
 <exists predicate>,
 <unique predicate>,
 <match predicate>,
 <overlaps predicate>,
 <distinct predicate>,
 <member predicate>,
 <submultiset predicate>,
 <set predicate>,
 <type predicate>.


On Thu, Sep 17, 2015 at 6:46 PM, Ben Darnell <notifications@github.com>
wrote:

> I'm not convinced we'll need the SIMILAR TO SQL-style regexes. Every
> database seems to have "real" regexes with posix-style syntax, often as a
> function instead of an operator (without a consistent name). The
> SQL-standard regexes with _ and % wildcards seem to be less commonly
> implemented.
>
> This SO post
> <http://dba.stackexchange.com/questions/10694/pattern-matching-with-like-similar-to-or-regular-expressions-in-postgresql>
> says that SIMILAR TO was only in an early draft of the SQL standard.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/2242#issuecomment-141304266>
> .
>



-- 
Jusong Chen
408 315 2288

**Comment by jusongchen** [comment]
The ANSI way of regexp_substring() is like this:

<regular expression substring function> ::=
SUBSTRING <left paren> <character value expression> SIMILAR <character
value expression>
ESCAPE <escape character> <right paren>


On Thu, Sep 17, 2015 at 6:59 PM, Jusong Chen <jusong.chen@gmail.com> wrote:

> it seems  SIMILAR TO is part of ANSI standard. Here are a list of
> predicates defined in SQL 2008:
>
> <comparison predicate>,
>  <between predicate>,
>  <in predicate>,
>  <like predicate>,
>  <similar predicate>,
>  <regex like predicate>,
>  <null predicate>,
>  <quantified comparison predicate>,
>  <exists predicate>,
>  <unique predicate>,
>  <match predicate>,
>  <overlaps predicate>,
>  <distinct predicate>,
>  <member predicate>,
>  <submultiset predicate>,
>  <set predicate>,
>  <type predicate>.
>
>
> On Thu, Sep 17, 2015 at 6:46 PM, Ben Darnell <notifications@github.com>
> wrote:
>
>> I'm not convinced we'll need the SIMILAR TO SQL-style regexes. Every
>> database seems to have "real" regexes with posix-style syntax, often as a
>> function instead of an operator (without a consistent name). The
>> SQL-standard regexes with _ and % wildcards seem to be less commonly
>> implemented.
>>
>> This SO post
>> <http://dba.stackexchange.com/questions/10694/pattern-matching-with-like-similar-to-or-regular-expressions-in-postgresql>
>> says that SIMILAR TO was only in an early draft of the SQL standard.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/cockroachdb/cockroach/issues/2242#issuecomment-141304266>
>> .
>>
>
>
>
> --
> Jusong Chen
> 408 315 2288
>



-- 
Jusong Chen
408 315 2288

**Comment by nvanbenschoten** [comment]
I just threw together a PR, so if we do want to include SIMILAR TO functionality, it would probably look something like that. Note that I wasn't able to find any differences between SQL-standard regexes and Go's regexes other than their handling of wildcards, so I was able to translate them pretty easily.

**Comment by petermattis** [comment]
We need to add caching of the compiled regular expressions to avoid recompiling them every time the `{LIKE,SIMILAR TO}` expression is evaluated.

**Comment by nvanbenschoten** [comment]
How were you picturing this caching implemented? Should we have some kind of global temporal regex cache mapping string patterns to compiled regexps for a given period of time so that they can be shared across calls to `LIKE`, `SIMILAR TO`, and other functions that require regexp compilation? 

I see we already have a [util.cache](https://github.com/cockroachdb/cockroach/blob/master/util/cache/cache.go) package that supports TTLs and eviction policies so we can limit its growth.

**Comment by petermattis** [comment]
I was thinking we should cache the compiled regex in the `ComparisonExpr`, similar to the way `BinaryExpr` caches the function to use. There is a bit of work to do to reorg the code to make this possible and I haven't look at it closely enough to know how I'd want to do it. Perhaps the `cmpOps` can take an extra `cache *interface{}` parameter.

**Comment by petermattis** [comment]
Having a global cache would be a possibility to, though I think regex compilation is fast enough to not warrant that. We mainly want to avoid recompiling the regex 1000s of times in a single query (i.e. if you're scanning a thousand rows).
