### ISSUE TITLE
sql: computed column incorrectly computed after FK check

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#22428]
Got:

```
> create table u(x int unique, y int as x stored references u(x));
CREATE TABLE
> insert into u(x) values (2);
pq: foreign key violation: value [2] not found in u@u_x_key [x]
```

Expected: no failure (x = 2 implies y = 2 implies FK validation succeeds)

**Comment by justinj** [comment]
I think this one was actually the case we meant to block, at least for the time being, stored columns shouldn't be able to be an FK reference.

**Comment by knz** [comment]
then the blocking is not complete yet

**Comment by justinj** [comment]
yes correct, just making a note (mostly for myself :) )
