### ISSUE TITLE
perf: investigate removing `hashRouter` `RowChannel` overhead

### ISSUE THREAD

**Issue by asubiotto** [cockroachdb/cockroach#22444]
Routers are used in distributed sql queries to route rows to a certain destination according to a policy specific to a router.

We have a couple of routers in our codebase:
1) The pass through router which is just an output stream.
2) The `mirrorRouter` where each row is sent to all of its output streams.
3) the `hashRouter`, where each row is sent to a specific stream, chosen by hashing certain columns of the row.
4) The `rangeRouter`, where each row is sent to a specific stream according to preset boundaries for the values of certain columns of the row.

The `mirrorRouter` is not currently used and the `rangeRouter` is only used in `IMPORT CSV`. This issue will focus on the `hashRouter`.

Routers implement `RowReceiver` and are run in a goroutine. Rows are pushed to them, stored, and then pushed to output streams according to a policy. In the case of a `hashRouter`, the outputs are always `n` `RowChannel`s connected to outboxes and 1 `RowChannel` connected to a local `HashJoiner` (I'm not 100% sure about this but anything else wouldn't make sense).

Note that currently this results in `n+1` goroutines reading from another goroutine. I don't know how well this might work but here's a proposed solution:

Change the `hashRouter` to implement `RowSource`, however this `RowSource` is only ever called by the local downstream processor.

A call to `Next` results in `m` calls to the `hashRouter`'s input's `Next` method up until a row is found to correspond to the local destination.

In the meantime, any row that doesn't belong to the local destination is `Push`ed by the `hashRouter` to its corresponding outbox. Hopefully this won't require an extra goroutine with (https://github.com/cockroachdb/cockroach/issues/20568), but in the near term we could batch rows retrieved in one `Next` call over this channel to amortize the overhead.

**Comment by petermattis** [comment]
> Routers implement RowReceiver and are run in a goroutine. Rows are pushed to them, stored, and then pushed to output streams according to a policy. In the case of a hashRouter, the outputs are always n RowChannels connected to outboxes and 1 RowChannel connected to a local HashJoiner (I'm not 100% sure about this but anything else wouldn't make sense).

Seems like it would also make sense for there to be 0 local HashJoiners (i.e. they are all remote). 

With your proposed solution, `hashRouters` would still be connected by `RowChannel` with the `outboxes`. Another option is to model `hashRouter` as N `RowSources`. That is, `hashRouter` exposes a `RowSource` per output. Flow setup would have to connect everything up properly, but that doesn't seem any different than the current flow setup requirements. The downside of this approach is that we'd need to change `outbox` to utilize a `RowSource` input.

**Comment by asubiotto** [comment]
> With your proposed solution, hashRouters would still be connected by RowChannel with the outboxes. 

But if the outboxes are changed to implement `RowReceiver`, we would not need these `RowChannel`s.

> Another option is to model hashRouter as N RowSources. That is, hashRouter exposes a RowSource per output.

I was thinking about this but came to the conclusion that it would create more problems than it would solve. Even if each concurrent reader calls its corresponding `RowSource`, the rows have to be routed correctly to each `RowSource`, and I'm not sure how to do that without having a goroutine decide where each row goes. How would a `Next` call look? Would we buffer all rows that don't belong to us in the other `RowSource`s? If we do, there's a concurrency problem with the reader of that `RowSource` so we need a `RowChannel` or a mutex, defeating the purpose of this change.

**Comment by petermattis** [comment]
> I was thinking about this but came to the conclusion that it would create more problems than it would solve. Even if each concurrent reader calls its corresponding RowSource, the rows have to be routed correctly to each RowSource, and I'm not sure how to do that without having a goroutine decide where each row goes. How would a Next call look?

Each of the `hashRouterOutput.Next` calls would call into an internal `hashRouter.next(outputID int)` method. The `hashRouter.next(outputID)` method would require synchronization (because it is called concurrently) and would need a buffer per output. If the buffer for the desired output is empty, `hashRouter` would grab the next row from its input and place it in the appropriate output. There would certainly need to be some flow control to prevent using too much memory.

I'm not sure how much different this is in practice from your proposal as we'd need a goroutine per `outbox` connected to the `hashRouter`.

**Comment by jordanlewis** [comment]
@asubiotto and I continued talking about this issue today. We concluded that it should be possible to remove the extra goroutines by replacing the "routerOutput" structs and their associated goroutines with a new kind of DistSQL processor `BufferingRowChannel` that implements both `RowSource` and `RowReceiver`.

I think we might have independently discovered what @petermattis suggests in this issue, but I'll rephrase in case it differs.

`BufferingRowChannel` has two buffers, a condition variable, and no associated goroutine. Its `Push` method locks the first buffer, adds the row, unlocks the first buffer, and signals the condition variable.

Its `Next` method checks to see whether the second buffer has any rows. If so, it pops a row and returns. If not, it waits on the condition variable. When its woken up, it locks the first buffer, copies all rows from it into the second buffer, unlocks the first buffer and continues.

This should permit us to remove the `n` extra goroutines from the HashRouter. The HashRouter still needs to use a semaphore of size `n` to prevent runaway buffering, but that can be accomplished without coordination from the new `BufferingRowChannel`s.

**Comment by jordanlewis** [comment]
Well, this strategy didn't pan out. There are two main issues with it.

1. We can no longer tell in a granular fashion whether or not the consumers of the `hashRouter` are blocked. Previously, we assumed that during a call to `Push` on the downstream consumer, the consumer was blocked. Now, we'd have to assume that the consumer is blocked any time it's *not* in the `hashRouter`'s output `BufferingRowChannel.Next` method. This would make the semaphore used to detect complete blocked-ness almost always at 0, which would result in slow, lock-step processing. Even with some grace buffer for `Push`ers, this would likely give bad performance.
2. Even worse, the `outbox` needs to consume from an actual Golang channel to permit `select`-style blocking on both the channel, the flush ticker, and the drain signal. In the proposed model, the `outbox` would have to call `Next` on its upstream `hashRouter`, which isn't a channel, so it can't have `select`-style nonblocking reads.

**Comment by jordanlewis** [comment]
@asubiotto close?
