### ISSUE TITLE
engine: Try rocksdb `manual_wal_flush`/`FlushWAL`

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#22443]
RocksDB has independent options for flushing (the `write()` system call) and syncing (`fdatasync()`) data. We sync roughly half of our writes, but we still flush all of the unsynced writes. We might be able to improve performance if we set `manual_wal_flush` in options and used `FlushWAL` instead of `SyncWAL` in the sync loop. This would allow small non-synced writes to be fully batched with the system calls of the next synced write.

**Comment by petermattis** [comment]
Huh, I wasn't aware of the `manual_wal_flush` option or `FlushWAL`. Always new corners of RocksDB to explore. This one seems relatively straightforward to experiment with.
