### ISSUE TITLE
kubernetes: revisit removal of health checks

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#22468]
We gave up our readiness/liveness checks in https://github.com/cockroachdb/cockroach/pull/13580 (with good reason), but would benefit from bringing some form of them back. What we do should be informed by the resolution of https://github.com/cockroachdb/cockroach/issues/22424

**Comment by bdarnell** [comment]
I think we need multiple kinds of health checks. One for load balancers ("is this node ready to receive sql traffic?") and one for process managers ("has this node started? is it so unhealthy that it needs to be put out of its misery?").

**Comment by a-robinson** [comment]
Note: health checks can't be re-added until a stable release that includes #22911 has been published to docker hub.

**Comment by a-robinson** [comment]
Including liveness checks ("is this server so unhealthy it needs to be restarted" is a bit awkward given that the `/health` endpoint isn't served until after the cluster been initialized. That means that unless we change the orchestration system to automatically run the init command as soon as it creates the cockroachdb cluster, the cockroach processes will keep being killed as non-live until the user gets around to running init. And the processes getting killed could make it tougher to run init if the user tries to run it during a restart.

@bdarnell is there any philosophical reason why we don't want to serve `/health` while waiting for cluster init? Was it just an oversight? Or is it because it's hard to serve just one thing over the http<->grpc gateway before serving everything?

**Comment by bdarnell** [comment]
Mainly an oversight. Note that the grpc gateway is not an issue because `/health` is served on the HTTP port instead of the GRPC port. (I hadn't thought about that distinction; that would be one reason to use a GRPC-generated endpoint instead of the raw `/health` handler)

**Comment by a-robinson** [comment]
> Note that the grpc gateway is not an issue because /health is served on the HTTP port instead of the GRPC port

Are you sure? We expose it on the HTTP port, but it certainly [looks to me like it's using the gateway mux](https://github.com/cockroachdb/cockroach/blob/658fd5267f513587145e0fd5eb3b05a9f18f1c66/pkg/server/server.go#L1193), meaning we're [forwarding it through the gateway](https://github.com/cockroachdb/cockroach/blob/658fd5267f513587145e0fd5eb3b05a9f18f1c66/pkg/server/server.go#L1117).

**Comment by bdarnell** [comment]
No, I'm not sure. I was going by the fact that the `cockroach gen haproxy` config used to set up a health check on `/health` on the HTTP port.

**Comment by a-robinson** [comment]
I spent a bunch of time last night experimenting with the liveness/readiness checks from #23478 on top of all the recent changes, and I'm seeing some questionable behavior from `kv` (despite updating our docker image cockroachdb/loadgen-kv to a more recent build after seeing initially suspicious results) and/or the connection draining logic. I wasn't seeing the same behavior outside of Kubernetes, at least not in a couple attempts.

I set server.shutdown.drain_wait and server.shutdown.query_wait to 15s each, then ran `/kv --splits=16 --read-percent=95 --concurrency=100 --max-rate=1000 --tolerate-errors`. Whenever I ran the `kubectl kill cockroachdb-$N` command to gracefully shut down one of the pods, loadgen would look like this after wait periods:

```
     30s        0         1005.6          999.8      1.8      9.4     18.9     37.7
     31s        0          972.9          998.9      1.8     25.2     52.4    104.9
     32s        0          766.3          991.6     16.8    369.1    570.4    671.1
     33s        0         1080.2          994.3      3.3    151.0    260.0    939.5
     34s        0         1002.7          994.6      1.9      8.9     13.6     21.0
[...]
   1m39s        0         1015.0          998.1      1.8     26.2     54.5     75.5
   1m40s        0         1000.5          998.1      1.7     14.2     32.5     50.3
_elapsed___errors__ops/sec(inst)___ops/sec(cum)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)
   1m41s        0          833.8          996.5      1.5    142.6    251.7    369.1
   1m42s        0         1078.5          997.3      1.4    159.4    335.5    453.0
   1m43s        0         1000.5          997.3      1.2      8.4     18.9     46.1
```


Kubernetes appears to be doing the right thing, at least at the API level. Its readiness checks correctly judged the pods as not ready:

```
$ kubectl describe pod cockroachdb-1
[...]
  Warning  Unhealthy              4s (x3 over 6m)  kubelet, gke-cockroachdb-default-pool-aef56f4a-w66w  Readiness probe failed: HTTP probe failed with statuscode: 503
```

And the unready pod was removed from the service's endpoints list:

```
$ kc describe endpoints cockroachdb-public
[...]
  Addresses:          10.16.6.18,10.16.7.12
[...]
```

I didn't try introspecting into the iptables rules on the loadgen-kv pod's node.

Things actually seemed to work better without the k8s readiness check and without the customized `server.shutdown.query_wait` setting. I was able to get the below latency spike below the first time I killed a pod (running kv with `-max-rate=500` this time), but couldn't get real qps dips on subsequent pod killings.

```
      7s        0          500.0          499.8      1.3      5.0      9.4     15.7
      8s        0          500.1          499.8      1.4      6.8     10.5     18.9
2018/03/08 04:55:37 pq: server is not accepting clients
2018/03/08 04:55:37 pq: server is not accepting clients
      9s        2          498.0          499.6      1.4      6.6     10.0     12.1
     10s        2          500.0          499.7      1.3      4.2      7.3      9.4
     11s        2          499.0          499.6      1.4      5.2      9.4     14.7
     12s        2          499.8          499.6      1.4      7.1     28.3     33.6
     13s        2          501.2          499.7      1.4      5.5     10.0     15.7
     14s        2          499.0          499.7      1.3      4.7      9.4     16.3
     15s        2          501.0          499.8      1.4      6.8     12.6     25.2
     16s        2          500.0          499.8      1.4      6.0     13.1     25.2
     17s        2          500.0          499.8      1.4      5.5     10.5     16.3
     18s        2          413.0          495.0      1.4      6.0     11.5    167.8
     19s        2          586.5          499.8      1.4    104.9    226.5    234.9
     20s        2          500.4          499.8      1.3      6.0     12.6     17.8
```

It's possible that this is more of a client-side issue than a Kubernetes or server-side issue, but it seems worth getting to the bottom of soon.

**Comment by a-robinson** [comment]
After setting `-max-rate` down lower to rule out blips due to reduced capacity when a node goes down in an attempt to isolate draining-specific issues, I haven't been able to reproduce meaningful blips with the default `server.shutdown.drain_wait` setting of 0 seconds. I have, however, been able to reproduce the occasional problem when running with `server.shutdown.drain_wait` set to 15 seconds. The symptom is that seconds before the server shuts down, some requests appear to stall. In both of the instances below, the requests finished (i.e. the latencies spiked) precisely when the server finished shutting down.

It's not clear to me yet why the requests would be stalling, or why this behavior only appears to happen when the drain_wait setting is non-zero.

The start of this snippet coincides with when the graceful shutdown was started. It may not be relevant, but it seems noteworthy that the requests appear to have started stalling 25 seconds after the drain started, which was the sum of `server.shutdown.drain_wait` and `server.shutdown.query_wait`:


```
 4h7m24s        3          199.0          200.0      1.8      4.5      7.9     16.3
 4h7m25s        3          199.8          200.0      1.9      6.6      8.9     17.8
 4h7m26s        3          201.2          200.0      1.9      7.1      8.9     14.7
 4h7m27s        3          200.0          200.0      1.8      5.5      7.1     10.5
 4h7m28s        3          200.0          200.0      1.8      4.7      9.4     12.1
 4h7m29s        3          199.0          200.0      1.9      4.7      7.9      8.9
 4h7m30s        3          201.0          200.0      1.9      4.5      7.9      8.4
 4h7m31s        3          200.0          200.0      1.9      5.2     12.1     15.2
 4h7m32s        3          200.0          200.0      1.8      6.8     15.2     18.9
 4h7m33s        3          200.0          200.0      1.8      3.4      7.3     13.6
 4h7m34s        3          200.0          200.0      1.8      4.1     14.2     15.7
 4h7m35s        3          199.4          200.0      1.9      6.0      8.9     14.7
 4h7m36s        3          200.6          200.0      1.8      7.1     10.5     12.1
 4h7m37s        3          200.0          200.0      2.1      8.9     21.0     92.3
 4h7m38s        3          200.0          200.0      2.1      6.3      8.9     12.6
 4h7m39s        3          200.0          200.0      2.0      6.6     11.5     26.2
 4h7m40s        3          200.0          200.0      2.5      5.0      7.1     13.1
_elapsed___errors__ops/sec(inst)___ops/sec(cum)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)
 4h7m41s        3          200.0          200.0      2.2      4.2      9.4     12.6
 4h7m42s        3          200.0          200.0      2.4      6.8    100.7    113.2
 4h7m43s        3          200.0          200.0      2.4      8.9     15.7     19.9
 4h7m44s        3          200.0          200.0      2.4     14.2     48.2     60.8
 4h7m45s        3          199.8          200.0      2.2      7.3     10.5     16.3
 4h7m46s        3          186.2          200.0      2.4      8.9    218.1    218.1
 4h7m47s        3          200.0          200.0      2.1      6.8     11.5     12.6
 4h7m48s        3          200.0          200.0      2.2      5.5      8.9     14.2
 4h7m49s        3          200.0          200.0      2.1      5.5      7.9      8.4
 4h7m50s        3          199.9          200.0      2.0      5.2      8.9      9.4
 4h7m51s        3          214.1          200.0      2.2   5100.3   5100.3   5100.3
 4h7m52s        3          200.0          200.0      1.9      6.3     12.1     15.2
 4h7m53s        3          200.0          200.0      1.8      6.6     10.5     12.6
 4h7m54s        3          200.0          200.0      2.0      7.6     21.0     35.7
```

Or an older occurrence, albeit for this one I'm not positive when the graceful shutdown started:

```
3h16m46s        3          200.0          199.9      2.5      8.9     23.1     24.1
3h16m47s        3          200.0          199.9      2.5      3.8     13.6     15.2
3h16m48s        3          200.0          199.9      2.5      3.9     17.8     18.9
3h16m49s        3          156.0          199.9      2.6     14.7    243.3    251.7
3h16m50s        3          200.0          199.9      2.6      5.8     18.9     22.0
3h16m51s        3          200.0          199.9      2.6      6.8     14.2     16.8
3h16m52s        3          200.0          199.9      2.8      6.0     14.2     23.1
3h16m53s        3          200.0          199.9      2.5     12.1     17.8     23.1
3h16m54s        3          243.8          199.9      2.5   5100.3   5368.7   5368.7
```

**Comment by a-robinson** [comment]
So I've spent a little more time reproducing this, and have tracked down the issue to PEBCAK - it occurs when I kill a node too quickly after a previous killed node has just restarted but hasn't yet fully caught up. The common issue in these cases was that the restarted node needed raft snapshot in order to get caught up.

So there isn't an issue here with draining or the kubernetes readiness checks or kubernetes connection management or `kv`, but it's very odd that raft snapshots are needed so frequently on restarts under this 95% read workload, particularly given that the nodes are only down for 10-30 seconds. A majority of the raft snapshots needed on startup are actually needed by the node liveness range, which seems crazy to me given how small our liveness writes are. Why are we truncating the node liveness raft log so frequently?

On a likely related note, the raft log queue on this cluster seems surprisingly busy. I turned off the loadgen workload so that there are no clients running against the cluster, yet it's still doing work every second:

<img width="981" alt="screen shot 2018-03-21 at 4 05 16 pm" src="https://user-images.githubusercontent.com/7085343/37734648-2e3b4162-2d22-11e8-862e-15e3f1c44a52.png">

Why are we so aggressive truncating the raft log? When I enable verbose logging of the raft log queue, I see that we're truncating timeseries ranges' range logs every few entries / every couple seconds:

```
[raftlog,n3,s3,r4/3:/System/{NodeLive…-tsd}] truncating raft log 1123-1127: size=67583
[raftlog,n3,s3,r4/3:/System/{NodeLive…-tsd}] truncating raft log 1127-1131: size=67586
[raftlog,n3,s3,r4/3:/System/{NodeLive…-tsd}] truncating raft log 1131-1135: size=67582
[raftlog,n3,s3,r5/3:/System/ts{d-e}] truncating raft log 1660-1662: size=97383
[raftlog,n3,s3,r5/3:/System/ts{d-e}] truncating raft log 1662-1664: size=97383
[raftlog,n3,s3,r5/3:/System/ts{d-e}] truncating raft log 1664-1666: size=97383
```

And we truncate the node liveness range's raft log quite aggresively in terms of its size:

```
I180321 20:21:35.269400 248452 storage/raft_log_queue.go:257  [raftlog,n3,s3,r3/3:/System/NodeLiveness{-Max}] truncating raft log 2703-2807: size=18982
I180321 20:23:36.734030 251766 storage/raft_log_queue.go:257  [raftlog,n3,s3,r3/3:/System/NodeLiveness{-Max}] truncating raft log 2807-2912: size=19241
I180321 20:25:34.975609 254950 storage/raft_log_queue.go:257  [raftlog,n3,s3,r3/3:/System/NodeLiveness{-Max}] truncating raft log 2912-3014: size=18749
I180321 20:27:35.043507 258165 storage/raft_log_queue.go:257  [raftlog,n3,s3,r3/3:/System/NodeLiveness{-Max}] truncating raft log 3014-3117: size=18913
```

Do we really need to truncate the node liveness range's raft log every 4 entries?

More importantly to this issue, we appear to continue truncating when a node is down. I killed cockroachdb-1, while watching the logs of cockroachdb-2:

```
W180321 20:34:10.162644 269396 vendor/google.golang.org/grpc/clientconn.go:830  Failed to dial cockroachdb-1.cockroachdb.default.svc.cluster.local:26257: context canceled; please retry.
I180321 20:34:14.130713 269541 storage/raft_log_queue.go:257  [raftlog,n3,s3,r4/3:/System/{NodeLive…-tsd}] truncating raft log 1609-1613: size=67553
I180321 20:34:26.952934 269938 storage/raft_log_queue.go:257  [raftlog,n3,s3,r4/3:/System/{NodeLive…-tsd}] truncating raft log 1613-1617: size=67558
I180321 20:34:28.067382 269947 storage/raft_transport.go:459  [n3] raft transport stream to node 2 established
I180321 20:34:28.078777 269962 storage/replica_raftstorage.go:520  [raftsnapshot,n3,s3,r4/3:/System/{NodeLive…-tsd}] generated Raft snapshot 3f1faefd at index 1618
```

The node was unreachable for all of 18 seconds, yet we truncated r4's raft log twice, enough to require a raft snapshot when cockroachdb-1 came back up. I didn't think we were supposed to do this. Is this intended behavior, @tschottdorf?

**Comment by a-robinson** [comment]
> Do we really need to truncate the node liveness range's raft log every 4 entries?

Sorry, I meant to ask this question about the timeseries ranges, not the node liveness range. The node liveness range is getting truncated due to our 100 entry threshold.

**Comment by a-robinson** [comment]
Hm, truncating r4 multiple times while n1 was down in the above example may have just been because we don't store much data in that range and the raft log entries are larger than the real compressed data, so the raft log size is greater than the data size.

The same appears to be true for the truncations of the node liveness range that I've been able to repro while a node is down. Closing as WAI.
