### ISSUE TITLE
perf: reduce allocations in `ProcOutputHelper.ProcessRow` in some cases

### ISSUE THREAD

**Issue by asubiotto** [cockroachdb/cockroach#22462]
In distsql queries, processors use a `ProcOutputHelper` to output rows to the next stage. At this output stage, a new row is allocated and this new row is sent over. Experimentation has shown that these allocations are a significant overhead (https://github.com/cockroachdb/cockroach/pull/20621#issuecomment-351201076).

The reason for these allocations lies in our use of `RowChannel`s for asynchronous communication between processors. The upstream processor does not know when the downstream processor is done with the row, so it must allocate a new row in order to not reuse memory that the downstream processor will possibly read at a later point.

However, with work happening on `RowChannel` elision (https://github.com/cockroachdb/cockroach/issues/20550) and thus synchronous communication between processors, it is now possible to avoid these allocations between some processors as the ownership of the memory is clearly defined.

**Comment by jordanlewis** [comment]
We need to clear up the contract around `Next()`. It's unclear to me whether any processor currently returns memory from `Next()` that it expects to then modify. If no processor does that, then we can avoid these allocations.

Processors that do expect to be able to keep their output should be the only ones that have to perform that copy.

**Comment by andreimatei** [comment]
I don't understand the original comment about the `RowChannel` - when is passing along a row by a processor no bueno?

**Comment by asubiotto** [comment]
Consider a `tableReader` hooked up to a `RowChannel`. The `RowFetcher`'s `NextRow` semantics are that a row is only valid until the next call. The `tableReader` gets its first row, writes asynchronously to the `RowChannel`. Before the downstream processor can call `Next()` on the `RowChannel`, the `tableReader` gets a second row, which overwrites the row written to the `RowChannel`.

**Comment by andreimatei** [comment]
If that's what the `tableReader` does, then it's breaking the contract of `RowReceiver.Push()`
