### ISSUE TITLE
sql: add support for SELECT DISTINCT

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#2247]
Also see the `DISTINCT ON (expr-list)` syntax Postgres supports.

**Comment by vivekmenezes** [comment]
I'm going to start implementing this.

**Comment by jusongchen** [comment]
It seems DISTINCT ON  is a postgre dialect? Neither Oracle nor MS SQL has this syntax and I really don't see a value to have it implemented (the query using DISTINCT ON can be rewritten as GROUP BY, or using Window functions).

Is  Cockcoach SQL syntax going to be 100% compatible to PostGres? It appears to me that Cockcoach SQL syntax is under very strong influence of Postgre - Good for users who knows Cockroach well, but users who are more familiar with Oracle , SQL server , Sybase, DB2, informix etc would find things look odd.

**Comment by petermattis** [comment]
@jusongchen No, Cockroach SQL syntax is not going to be 100% postgres compatible. There are lots of postgres extensions that we're not implementing. Our syntax is definitely inspired by postgres because our grammar is. Is that really a problem?

**Comment by jusongchen** [comment]
I find it difficult to understand why postgres need to have DISTINCT ON
(also something like IS UNKNOWN).  I consider them as postgres dialect (I
could be wrong here.  But I have intensively professional experience on
Oracle and MSSQL for long long time, when I see something like this, I am
wondering why big commercial RDBMS venders do not have the same
functionality/syntax).   Supporting postgres dialects leads to complicated
SQL syntax and  it will be difficult to remove them once the product is
released.

On Wed, Sep 16, 2015 at 10:43 AM, Peter Mattis <notifications@github.com>
wrote:

> @jusongchen <https://github.com/jusongchen> No, Cockroach SQL syntax is
> not going to be 100% postgres compatible. There are lots of postgres
> extensions that we're not implementing. Our syntax is definitely inspired
> by postgres because our grammar is. Is that really a problem?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/2247#issuecomment-140815926>
> .
>



-- 
Jusong Chen
408 315 2288

**Comment by petermattis** [comment]
It appears that `DISTINCT ON` is historical in postgres and `GROUP BY` is usually more performant. I think it would be overly limiting to restrict CockroachDB to what commercial RDBMS vendors support, but in this particular case I can see an argument for stripping out support for `DISTINCT ON`.
