### ISSUE TITLE
ui/build: update gobindata references to the correct source

### ISSUE THREAD

**Issue by couchand** [cockroachdb/cockroach#22478]
The user who created`go-bindata` deleted their account, and someone else recreated it.  We probably shouldn't trust that dependency anymore.

**Comment by couchand** [comment]
cc @benesch

**Comment by couchand** [comment]
Whatever we do here, we probably want to cherry-pick into 1.1 as well.

**Comment by a-robinson** [comment]
We have a vendored version of it. We should be very wary about updating that vendored dependency, but what's the urgency to do something about it now?

The recreation happened today, as far as I'm aware.

**Comment by bdarnell** [comment]
I think the urgency is just that if we don't do something about it while it's on our minds, we may forget about it by the next time we do a blanket dependency bump.

**Comment by couchand** [comment]
It sounds like my intuition that we need to cherry-pick anything for this is wrong, since we don't as a rule cherry-pick dep bumps.  Otherwise, it makes sense to do this soon while we're thinking about it, but it doesn't need to be this week.

Thanks for the thoughts!

**Comment by benesch** [comment]
As it turns out, we don't use jteeuwen's fork: https://github.com/cockroachdb/cockroach/blob/37bc4d05d8a3cb4b649677e95816c97e88ec8510/Gopkg.toml#L55

So: nothing to do here! 🎉

**Comment by couchand** [comment]
@benesch are you sure?  We sure have `https://github.com/jteeuwen/go-bindata` sprinkled about our codebase, such as here:

https://github.com/cockroachdb/cockroach/blob/master/Makefile#L355

Does the `Gopkg.toml` constraint section mean we resolve it to a different place?  Perhaps we could `s/jteeuwen/dim13/g` to make that more obvious?

**Comment by benesch** [comment]
> Does the Gopkg.toml constraint section mean we resolve it to a different place?

Yep, that's what source means: https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md#source

> Perhaps we could s/jteeuwen/dim13/g to make that more obvious?

Yep, definitely, but I'm a bit swamped at the moment.

**Comment by couchand** [comment]
Great, thanks for the clarification.  Given that the docs recommend against relying on that directive long-term, updating the references seems like the way to go.  I'm reopening this issue and retitling it to reflect this information.
