### ISSUE TITLE
sql: joins don't handle equality columns with different types correctly

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#22519]
```
root@:26257/test> create table t (x INT);
root@:26257/test> insert into t values (1), (2), (3);
root@:26257/test> create table u (y FLOAT);
root@:26257/test> insert into u values (1), (2), (3);

root@:26257/test> select * FROM t JOIN u ON x = y;
+---+---+
| x | y |
+---+---+
+---+---+
(0 rows)

root@:26257/test> select * FROM t JOIN u ON x+1-1 = y;
+---+---+
| x | y |
+---+---+
| 1 | 1 |
| 2 | 2 |
| 3 | 3 |
+---+---+
(3 rows)
```

The field `cmpFunctions` in `joinPredicate` seems to be related, but it's not used AFAICT.

In any case, the problem is that we create equality columns and then rely on their encodings matching. We should check if they have the same type before adding them as equality columns.

CC @knz @jordanlewis

**Comment by jordanlewis** [comment]
In case it helps, `git log -S cmpFunctions` shows that we stopped using them in 45ded23285f8a2efb7c1026c53ae4aa6bc330050 with a rationale about using hash join everywhere.

**Comment by knz** [comment]
Wow I fucked up pretty bad on that one.

**Comment by RaduBerinde** [comment]
Even with that check, it was still wrong if we hashed the columns.

Columns that can't be hashed shouldn't be in the equality columns at all. We should move them to an ON condition.
