### ISSUE TITLE
sql: errors are swallowed in some log messages

### ISSUE THREAD

**Issue by asubiotto** [cockroachdb/cockroach#22550]
Doing some debugging, I came across https://github.com/cockroachdb/cockroach/blob/0e42ad6a247c81a801c3367f0242f03c3bc68db5/pkg/sql/lease.go#L1489
Which fails to inform what error was encountered and caused the log message to be printed. There's another instance of this above. We might want to add this to the linter.

**Comment by jordanlewis** [comment]
@asubiotto did you fix this problem? What's left to do here?

**Comment by asubiotto** [comment]
I did not and don't plan to do so in the near future. The action item here is to think about how to prevent this and audit existing log messages. Not sure it's worth to keep this open.
