### ISSUE TITLE
opt: make test report the origin of unexpected "errors"

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#22578]
Currently the code in `sql/opt` uses `panic()` to report errors instead of Go's standard `error` returns.
This is then further used in tests that check expected errors.

This seems to work on the most cases, except that it creates a concrete problem if there's a legitimate `panic` emitted somewhere else for something that's really not "just an error". Currently the origin of that panic is swallowed in the `opt` tests and only the headline of the panic is printed instead.

The specific example that prompted this issue is a panic in `sqlbase` due to an invalid call to `GetTableDescriptor`, but the panic message was just saying `database missing` which didn't tell me where to look.

The `opt` tests should instead always print the full stack trace alongside *unexpected* "errors" so that they can be troubleshooted more easily.

**Comment by RaduBerinde** [comment]
We are accidentally catching all errors thrown as panics. I have a PR out that is addressing this.

**Comment by rytaft** [comment]
I think @knz may also be referring to the first version of the opt code we created that will be going away soon (the stuff that still contains the index constraints code).  That code is catching all panics, and has no concept of `builderError`.  It's an easy fix so I'll do that now.

**Comment by knz** [comment]
thank you!
