### ISSUE TITLE
cli: provide feedback when joining an uninitialized cluster

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#22579]
When starting a new node and joining it to an uninitialized cluster, nothing is output to stdout or stderr until the cluster is initialized. After the cluster is initialized we print the usual header:

```
CockroachDB node starting at 2018-02-11 20:22:23.564316475 +0000 UTC (took 25.9s)
...
```

Before cluster initialization occurs, we should output something to stdout/stderr indicating that the cluster is initialized.

**Comment by bdarnell** [comment]
It's a bit tricky to do this without false positives - how do you tell the difference between "an uninitialized cluster" and "an initialized cluster, but we haven't yet connected to an initialized node"?

**Comment by petermattis** [comment]
Doesn't the node itself know that it is uninitialized? I was imagining it would output something like `new node; waiting to create or join cluster`.

**Comment by bdarnell** [comment]
Yes, we can do that. (We already do in the logs, we just need to send it to stderr too). We just can't distinguish at this point whether we're a new node being added to an existing initialized cluster or part of a brand new cluster awaiting initialization. (and we may need to tweak the message so it doesn't encourage the init command too much. If people incorrectly assume that they need to init each new node bad things could happen)
