### ISSUE TITLE
release: v2.0-alpha.20180219

### ISSUE THREAD

**Issue by arjunravinarayan** [cockroachdb/cockroach#22588]
Candidate SHA: XXX none XXX.
Deployment status: XXX EDIT ME XXX.

[Release process checklist](https://github.com/cockroachdb/cockroach/wiki/Release-Process)

Prep date: XXX fill me in XXX
- [ ] [Pick a sha](https://github.com/cockroachdb/cockroach/wiki/Release-Process#pick-sha), fill in `Candidate SHA` above.
- [ ] [Deploy to test clusters](https://github.com/cockroachdb/cockroach/wiki/Release-Process#deploy-to-test-clusters)
- [ ] fill in `Deployment status` above
- [ ] [Verify node crash reports](https://github.com/cockroachdb/cockroach/wiki/Release-Process#verify-crash-reports)
- Keep an eye on clusters until release date.

Release date: XXX fill me in XXX
- [ ] [Check cluster status](https://github.com/cockroachdb/cockroach/wiki/Release-Process#check-cluster)
- [ ] [Tag release](https://github.com/cockroachdb/cockroach/wiki/Release-Process#tag-release)
- [ ] [Trigger release build](https://github.com/cockroachdb/cockroach/wiki/Release-Process#trigger-build)
- [ ] [Check binaries](https://github.com/cockroachdb/cockroach/wiki/Release-Process#check-binaries)

- For stable releases only (**stable** means: no dash in the version):
  - [ ] Update the [Homebrew Formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/cockroach.rb)
  - [ ] Update the image tag in our [Orchestrator configurations](https://github.com/cockroachdb/cockroach/wiki/Release-Process#orchestrator-configurations)
  - [ ] Update the version label in our [Red Hat Atomic Docker image](https://github.com/cockroachdb/cockroach/blob/master/build/deploy/rhel/Dockerfile). For major/minor releases, also update the documentation link in the [image's help file](https://github.com/cockroachdb/cockroach/blob/master/build/deploy/rhel/help.1)
  - [ ] Announce version to the [registration cluster](https://github.com/cockroachlabs/production#publishing-a-new-release-version)
  - [ ] Upgrade the registration cluster (reg runs latest stable version)

- [ ] Update docs
- [ ] External communications for release
- [ ] File issue for next release and assign to release coordinator

**Comment by BramGruneir** [comment]
This release is being skipped due to https://github.com/cockroachdb/cockroach/issues/22642.
