### ISSUE TITLE
ui: clusterviz: Layout broken in Firefox

### ISSUE THREAD

**Issue by vilterp** [cockroachdb/cockroach#22594]
<img width="1680" alt="screen shot 2018-02-12 at 1 08 19 pm" src="https://user-images.githubusercontent.com/7341/36111961-eeeea1b4-0ff5-11e8-82cf-15b1753cf3de.png">

Maybe something is going wrong in the math, creating these `NaN`s in the translate. Or maybe those `NaN`s exist in Chrome too, but it tolerates them and FF doesn't. Maybe the problem is something else entirely.

Any ideas, @couchand or @mrtracy?

**Comment by mrtracy** [comment]
This has been an issue for quite a while, I investigated it briefly in december; as far as I can tell, the "NaN" values are coming out of the D3 projection function; this only happens in firefox, and I have no idea why this is happening.

I would suggest using a breakpoint to confirm that the NaN values are coming from the projection.

**Comment by couchand** [comment]
there are definitely d3 maps that work in Firefox, so I'd be very surprised if that were the ultimate source of the issue. I spent a little while in January trying to figure it out, without much success, though at the time I was chasing through several issues. I've had it in the back of my mind for a while, figure we'll look into it after freeze.
