### ISSUE TITLE
unable to join a second node to cluster

### ISSUE THREAD

**Issue by couchand** [cockroachdb/cockroach#22592]
On the latest master, I am unable to start a fresh new cluster with more than one node in it.  Every node past the first hangs, repeatedly logging:

```
E180212 17:33:41.278581 225 rpc/context.go:516  [n?] removing connection to localhost:25267 due to error: redialing
W180212 17:33:41.278639 265 vendor/google.golang.org/grpc/clientconn.go:830  Failed to dial localhost:25267: context canceled; please retry.
W180212 17:33:42.282085 168 vendor/google.golang.org/grpc/clientconn.go:1158  grpc: addrConn.createTransport failed to connect to {localhost:25267 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp [::1]:25267: getsockopt: connection refused". Reconnecting...
```

**Comment by couchand** [comment]
cc @bdarnell 

@vivekmenezes for triage

**Comment by couchand** [comment]
@benesch is unable to repro this.

**Comment by vivekmenezes** [comment]
Is this still an issue? Reproduction instructions would be nice to have.

**Comment by benesch** [comment]
The repro instructions are essentially “attempt to start a two node cluster.” I am curious to know if things were better at home, @couch?

**Comment by couchand** [comment]
Yesterday I still had trouble on my home network (removing the weird DNS entry for localhost as a confounding factor), but I can't recall now if that was because of this issue or the one with doing an upgrade of a cluster between last week and this week.

This is still an issue for me today.

How I'm trying:

- pull down latest master
- `make clean && make`
- term 1: `./cockroach start --insecure --store cockroach-data-1 --logtostderr`
- term 2: `./cockroach start --insecure --store cockroach-data-2 --join 127.0.0.1:25267 --port 25268 --http-port 8081 --logtostderr`

Alternatives attempted:
- joining with `localhost`
- joining with my hostname
- setting `advertise-host` to `127.0.0.1` and trying all three of the join variations
- setting `advertise-host` to my hostname and trying all three of the join variations

(as an aside, it looks like the issue upgrading from last week to this week was never logged, but since I'm facing this one, I can't really provide repro instructions for that one.  perhaps @benesch, since you could repro that one it would be worth filing an issue?)

**Comment by couchand** [comment]
For completeness, I'll mention that the error messages have changed slightly (I'm assuming because of #22620).  Now the errors are:

```
W180213 14:49:15.086447 101 vendor/google.golang.org/grpc/clientconn.go:1158  grpc: addrConn.createTransport failed to connect to {fhwdgads:25267 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:25267: getsockopt: connection refused". Reconnecting...
W180213 14:49:15.086552 20 gossip/client.go:123  [n?] failed to start gossip client to fhwdgads:25267: initial connection heartbeat failed: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
W180213 14:49:16.089802 101 vendor/google.golang.org/grpc/clientconn.go:1158  grpc: addrConn.createTransport failed to connect to {fhwdgads:25267 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:25267: getsockopt: connection refused". Reconnecting...
W180213 14:49:17.039274 101 vendor/google.golang.org/grpc/clientconn.go:1158  grpc: addrConn.createTransport failed to connect to {fhwdgads:25267 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:25267: getsockopt: connection refused". Reconnecting...
```

**Comment by couchand** [comment]
Curiously, the "connection refused" is only seen by a node trying to join the cluster.  I'm able to successfully open the connection for other purposes, such as `cockroach sql --insecure` and `curl localhost:26257`.

**Comment by couchand** [comment]
🤦‍♂️ `25267 != 26257`

**Comment by couchand** [comment]
In all the confusion about the `heartbeat failed on epoch increment` issue and the weird DNS entry for localhost I must have missed that I mistyped the port number.

Moving on now to investigate the other problem and file an issue.

**Comment by petermattis** [comment]
Oops. For the future, it is usually easier to start multi-node local clusters using `roachdemo` or `roachprod`. For example, `roachprod create local -n 3; roachprod start local`.

**Comment by couchand** [comment]
@petermattis Indeed.  To be clear, my usual workflow had been to just restart a previously-running cluster.  In the course of trying to sort out the `heartbeat failed on epoch increment` issue upgrading , my usual workflow got disrupted.

**Comment by bdarnell** [comment]
Note that if you omit the port number it will use the default, so you should be able to use `--join=localhost`

**Comment by PARKINHYO** [comment]
@bdarnell thank you👍
