### ISSUE TITLE
client: retryable Txn errors should require acknowledgment from clients

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#22615]
See https://github.com/cockroachdb/cockroach/pull/22337#issuecomment-362825647.

During retryable error handling, a `client.Txn` will reset its state to prepare for a retry internally before returning the error that triggered the retry. When doing this, the transaction will either increment its epoch or replace its ID. Either way, the transaction throws out all work it has previously performed*.
After this point, the new incarnation of the transaction can be used just like it is a new transaction.

This allows for abuses of `db.Txn` and `txn.Exec`, where a retry loop does not restart on a retryable error. For instance, in the following example, if the second `txn.Put` fails with a retryable error, the transaction will finish without either of the `Put` operations' results being committed.

```
err := db.Txn(func (ctx context.Context, txn *client.Txn) error {
  if err := txn.Put(ctx, "key", "val"); err != nil {
    return err
  }
  // Don't really care if this succeeds.
  _ := txn.Put(...)
  return nil
})
```

In order to avoid this type of misuse, we should require some kind of buy-in from users of `client.Txn` before a retried transaction can be used again. This could be as simple as requiring `PrepareForRetry` to be called before the next operation. This is already called in the `db.Txn` retry loop when it sees retryable Txn errors, so it should be invisible in almost all cases where `client.Txn` is being used correctly.

This will be addressed partially by https://github.com/spencerkimball/cockroach/commit/9decb1619fbe2f58d8455bf68fbadea670a8d34d, which forces all txn aborted errors to propagate up to the `db.Exec` retry loop. 

[*] this is not completely true, as a transaction with an incremented epoch will not need to write a new txn record and will still keep track of previous intents, but that is all transparent to users of `client.Txn`.

**Comment by tschottdorf** [comment]
@andreimatei  @nvanbenschoten is this still 2.1 material?

**Comment by nvanbenschoten** [comment]
This is a part of @andreimatei's upcoming refactoring of the `client.Txn` api, so I'll defer to him on that.

**Comment by andreimatei** [comment]
RFC about related things: https://github.com/cockroachdb/cockroach/pull/42766

**Comment by ajwerner** [comment]
Thoughts on unassigning this from @andreimatei? Seems like a good project but I feel like he's not working on it.

**Comment by andreimatei** [comment]
unassigned
