### ISSUE TITLE
sqlccl: reuse the descriptorResolver in more places

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#22632]
This is a followup to #22371: with the introduction of the new `descriptorResolver` in `targets.go`, there is now a consistent data structure that maps descriptor IDs back to descriptors.
This ought to be reused in more places across the ccl package(s).

Suggested/requested by @benesch in
https://github.com/cockroachdb/cockroach/pull/22371#issuecomment-365024027

cc @dt

**Comment by jordanlewis** [comment]
@dt, this is pretty clearly a backup thing, since `descriptorResolver` is package private in `backupccl`, right? Unless we think SQL Schema owns name resolution within backups, which I think is pretty borderline. I'm reassigning back to your board, but please feel free to close this if you wish!

**Comment by dt** [comment]
I think the big ones are backup and restore and they both use it. The others use the planner like normal sql and that seems fine. don't think there is anything to do here.
