### ISSUE TITLE
storage: conditional puts do not respect the optional nature of value checksums

### ISSUE THREAD

**Issue by couchand** [cockroachdb/cockroach#22636]
Upgrading a cluster across 75cbeb84848c807437ce84dcb93229d17fbb4a7e causes a never-ending stream of `heartbeat failed on epoch increment` errors, and the cluster is unable to serve requests.

Steps to reproduce:

- `git checkout 75cbeb84848c807437ce84dcb93229d17fbb4a7e~` (note the ~)
- `make`
- start a cluster
- `git checkout 75cbeb84848c807437ce84dcb93229d17fbb4a7e`
- `make`
- restart that cluster

**Comment by bdarnell** [comment]
We see the same symptom in #22581.

**Comment by nvanbenschoten** [comment]
I just ran into this with local testing as well. I'm guessing one of the liveness CPuts is causing issues. Investigating now.

**Comment by nvanbenschoten** [comment]
Yeah, we're going to need CPut to ignore the checksum when performing its existing value comparison in `mvccConditionalPutUsingIter`. This normalization will need to be in place on all nodes before we can remove checksums from `roachpb.Value` across the board. I think we'll want to take the following steps:
1. revert 75cbeb8
2. add the normalization in `mvccConditionalPutUsingIter` to 2.0, along with the same normalization in other places where we compare roachpb.Value.RawBytes directly
3. reintroduce 75cbeb8 behind a 2.1 isMinVersion check
4. remove isMinVersion in 2.2

Even if we decide not to pursue steps 3 and 4, I think step 2 is still important. The reason for this is that even before 75cbeb8, value checksums were meant to be optional, so comparing rawBytes directly like we do in `mvccConditionalPutUsingIter` is violating this contract. This is why we need code like https://github.com/cockroachdb/cockroach/blob/b0b6553d7b4e95db6a6bfab771629909dcf625af/pkg/sql/sqlbase/rowfetcher.go#L1060-L1070

**Comment by benesch** [comment]
Haven't thought this through entirely, but why can't you reintroduce 75cbeb8 behind a 2.0 isMinVersion check?

**Comment by nvanbenschoten** [comment]
> Haven't thought this through entirely, but why can't you reintroduce 75cbeb8 behind a 2.0 isMinVersion check?

Yeah if we get step 2 in place by the 2.0 release then you're right that we can put it behind a 2.0 isMinVersion check.

**Comment by benesch** [comment]
Should be fixed if you pick up https://github.com/cockroachdb/cockroach/pull/22637.

**Comment by nvanbenschoten** [comment]
@BramGruneir Adriatic is no longer seeing this after #22637, right?

**Comment by BramGruneir** [comment]
Yep, all good. Wanted to let it bake a while and Adriatic is looking great right now.

**Comment by nvanbenschoten** [comment]
For posterity, I'm kind of skeptical that we can follow through with step 4:
> 4. remove isMinVersion in 2.1

The reason is that checksums are used so prevalently, so early into node startup, and at such low levels (for instance, in liveness heartbeats). Because of this, I don't know if we can ever rely on the check that clusters are upgraded through every major release to "bake in" the knowledge that a 2.1 node is talking to at least 2.0 nodes like we do for ["baked in" SQL migrations](https://github.com/cockroachdb/cockroach/pull/22358).

**Comment by bdarnell** [comment]
We check versions very early in the RPC pipeline, so we should be confident that a 2.1 node will never connect to a pre-2.0 node.
