### ISSUE TITLE
roachtest: port terrafarm nightly tests to roachtest

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#22646]
Tracking issue for porting terrafarm-based nightly tests to `roachtest`.

- [x] TestRebalance_3To5Small
- [x] TestRebalance_3To5Small_WithSchemaChanges
- [x] TestSteady_3Small
- [x] TestSteady_6Medium
- [x] TestUpreplicate_1To6Medium
- [x] TestContinuousLoad_BlockWriter
- [x] TestContinuousLoad_Photos
- [x] BenchmarkRestoreBig
- [x] BenchmarkRestoreTPCH10/numNodes={1,3,10}
- [x] BenchmarkBackup2TB
- [x] BenchmarkRestore2TB

**Comment by danhhz** [comment]
`TestContinuousLoad_BlockWriter` does the same thing as the two `kv` tests in Workload Nightly, so I think we can check that one. TestContinuousLoad_Photos should be easy to add once we have a workload impl of photos

**Comment by danhhz** [comment]
Ported `BenchmarkRestore2TB` in https://github.com/cockroachdb/cockroach/pull/22859 (forgot to link this issue there). I don't think either of `BenchmarkRestoreBig` or `BenchmarkRestoreTPCH10` are really pulling their weight, so I'm going to skip both of them unless someone objects

**Comment by benesch** [comment]
No objections. I say delete them outright! 🔨

**Comment by petermattis** [comment]
Do we want to bother porting `photos` to `workload`? TPC-C seems like a better workload.

**Comment by danhhz** [comment]
Agreed. I'll skip that one too

**Comment by danhhz** [comment]
Okay, the only one left is the schema change one. @vivekmenezes just to confirm, do we think that's still useful and worth porting?

**Comment by petermattis** [comment]
I'm not familiar with the details of the existing schema change test, but we definitely want a nightly schema change test.

**Comment by vivekmenezes** [comment]
@danhhz yes that's a super useful test! Thanks

**Comment by arjunravinarayan** [comment]
@danhhz it appears you have done all the tasks for this issue, save closing it. Can you please confirm and close?

**Comment by benesch** [comment]
I think there's one final task: removing the old Terraform tests. Dan did all the hard work here so I don't want to spoil his fun. Punting out of 2.0 in the meantime, though.
