### ISSUE TITLE
distsql: investigate time to cancel query

### ISSUE THREAD

**Issue by asubiotto** [cockroachdb/cockroach#22650]
Running some query cancellation QA uncovered that distsql queries take a lot more time to respond to cancellation than inserts/non-distsql selects.

For example, `SELECT l_shipmode, AVG(l_extendedprice) FROM tpch.lineitem GROUP BY l_shipmode` (on scalefactor 10 data), took ~15s to respond to cancellation (have the connection return `pq: query execution canceled`) versus a near-instantaneous response time when running it after `SET DISTSQL=off;`

@abhimadan, you might want to take a look at this as part of your transaction timeout work.

**Comment by abhimadan** [comment]
Looking through the aggregator processor code, it seems like it's not consulting a `CancelChecker` when it's accumulating rows. As a result, it won't know about the cancellation until it tries to push a row to its consumer. I think that would explain the slow cancellation time in at least that specific query.

I'm going to audit the distsql processors that do any expensive pre-processing before emitting rows to see if they use a `CancelChecker` or not.

**Comment by asubiotto** [comment]
Hmm, checking for usages of `CancelChecker` seems to only come up with usages in `hashjoiner.go` and `mergejoiner.go` + `Sort` in the row container. A query with a scan + aggregation like above would seem to never check for cancellation. In fact, what's probably happening is:
1) We cancel a query on the gateway node.
2) The flow's `cancel` method gets called through context cancellation.
3) The distSQLReceiver gets canceled set, which seems to only be observed in its `Push` method.
This seems to imply that we don't ever cancel a query until we output the first row. For long-running queries that do a lot of processing before outputting a row this could take a long time. Also, the `CancelChecker`s will only pick up a context cancellation on the gateway node for the original query.

We probably need to extend our distsql infrastructure for query cancellation. I see this as an RPC that cancels a flow. The gateway would send this RPC to every participating node in the query, which would cancel a context associated with this flow (created in `distsqlrun.ServerImple.SetupFlow`. This cancellation would be picked up and stop work on remote nodes.

**Comment by asubiotto** [comment]
Actually, I don't think we need to add any infrastructure. It seems that outboxes on remote nodes already listen for drain signals from consumers. The only thing is that we don't ever send a drain signal until we receive the first row and attempt to push it to the `distSQLReceiver` and get back a `ConsumerClosed` status. I verified this on the same example query and setup as before.

This is definitely something we want to fix (have `processInboundStream` check for cancellation maybe?). We also need to verify that this signal stops all work.

The other issue is the cancellation check as @abhimadan points out. Some processors can accumulate all rows before checking for any cancellation (the sorter is another one I'm thinking about in addition to the aggregator).

**Comment by abhimadan** [comment]
#22684 addresses the concerns about aggregators not checking for cancellation.

**Comment by asubiotto** [comment]
@abhimadan are there any remaining work items to close this issue?

**Comment by abhimadan** [comment]
Don't think so. The query in the issue can be cancelled quickly, and from some testing I've done, query cancellation doesn't seem to have any more unexpected slowness. (I was actually just about to close it :) )
