### ISSUE TITLE
sql: allow adding computed columns in a schema change

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#22652]
Presently we only support adding a computed column in the initial `CREATE TABLE` statement. This is because doing the necessary backfill requires some extra machinery that doesn't presently exist in the backfiller.

**Comment by vivekmenezes** [comment]
related to https://github.com/cockroachdb/cockroach/issues/22508

**Comment by scottmas** [comment]
Where is this feature at? It's unclear from this history....
