### ISSUE TITLE
storage: RangeLookup accesses meta keys stored in other range

### ISSUE THREAD

**Issue by kkaneda** [cockroachdb/cockroach#2266]
Suppose that we have the following two ranges: R0 and R1:

```
    meta2a   meta2b  meta2\xff\xff   meta3   a    \xff\xff
+------+-------+-------+--------------+------+-----+
|     R0       |                R1                 |
+--------------+-----------------------------------+
```

A lookup of a range containing "a" is routed to R0, which contains "meta2a". Then, R0 scans ["meta2a\x00", "meta3") and finds a range descriptor of R1, which is stored at key "meta2\xff\xff" (= meta(R1 end key)). "meta2\xff\xff" belongs to R1, not R0.

The issue was originally discussed in #2100 .

**Comment by tschottdorf** [comment]
We should bump this up. This is actually a real bug without even a plan for a solution.

**Comment by tschottdorf** [comment]
I suppose `RangeLookup` can do validation and make sure it doesn't scan outside of its Replica's bounds. If the first-level cache gets invalidated on the returned error (which it would be), we should be fine.

**Comment by kkaneda** [comment]
Hmm, is there any potential race with range split? I wonder a range might be split while `RangeLookup` finishes its validation.

I also wonder simply disabling the split of the meta space might be fine as a temporarily solution..

**Comment by tschottdorf** [comment]
reads are blocked during execution of an `InternalCommitTrigger` (see the recently introduced `(*Replica).readOnlyCmdMu`. We probably don't need to worry about split meta ranges for beta too much, but it seems straightforward enough to test and fix.

But you have a point, to avoid the same problem for other operations (`Scan`, etc) the key range check must actually happen **under** the above mutex. It doesn't at the moment. Good call.

**Comment by kkaneda** [comment]
Ah, thanks for the explanation! Didn't follow the change. 

Totally unrelated to this issue, but we use `batch.Defer(callback)` to release `r.readOnlyCmdMu.Unlock`. Is there any chance that `Commit()` fails and the callback is never invoked (and hence the lock is never released)?

**Comment by tschottdorf** [comment]
We manually do it if the split trigger fails. If something goes wrong
between there and the batch commit (for example, if the batch commit itself
failed), then we're screwed. Anything like that needs to be a
ReplicaCorruptionError (and I think to date, it is).

**Comment by MulberryComic20** [comment]
Hello

**Comment by kkaneda** [comment]
Ah, you're right!

As for the original issue, how will we redirect a request to R1 while key `meta2a` is still in R0? Do we need a special retry logic that bdarnell mentioned in #2100?

> We need some retry logic in DistSender/RangeCache to check if RangeLookup returned no results, and if so to retry with a new key (computed from the EndKey of the meta range we just looked at).

**Comment by bdarnell** [comment]
Yes, that retry logic looks like the right fix for the root issue here.

We definitely need more tests of what happens when there are splits in the meta2 span, and of cases where ranges are not contiguous on a single store. I wonder if it would be worthwhile for `Store.Engine()` to take a `RangeDescriptor` and return a wrapped `Engine` that panics if access is attempted outside the given range.

**Comment by tschottdorf** [comment]
> I wonder if it would be worthwhile for Store.Engine() to take a RangeDescriptor and return a wrapped Engine that panics if access is attempted outside the given range.

I also think so. If for some reason that is prohibited by performance, we should still find an (elegant enough) way during testing.

**Comment by tschottdorf** [comment]
I've obviously had this assigned for a long time without doing anything about it. Unassigning, but this still needs fixing. Might also be a good nontrivial starter project for someone looking into core.

The first part which is to be done here is to make sure that `RangeLookup` doesn't read outside its range (there's a general problem to be solved here as discussed above, of course).

Then we'll need a mechanism to communicate back to the caller that the range descriptor isn't located here along with a hint on where to find it. Naively, one such hint is another meta2 key to hit (i.e. in the above example, return `meta2b` as hint).

But, and that isn't really fleshed out but only an idea, maybe we can turn `RangeLookup` into a range request (it is right now a point request). The point is that that would allow `DistSender` to hit multiple ranges until it finds the information it needs. What information does it need? Let's do the above example: we definitely want to get a RangeDescriptor back. So we would send a `BatchRequest` with a global response count bound of one (or more, if we're prefetching). Next, the key span for our request would be `[meta2a, meta2\xff\xff)` (it would look different and possibly trickier when looking up in reverse order).

Of course the above idea simply mirrors the fact that `RangeLookup` really isn't much more than a bunch of `MVCCScan`s. I think that exposing that more directly will simplify things here.
