### ISSUE TITLE
ui: After a partition, the Live Node Count graph looks as if no nodes were ever dead

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#22673]
I created a 6 node cluster spread across 3 datacenters. I partitioned one of the datacenters (containing 2 nodes) for a few minutes by shutting off network connectivity to/from the datacenter, then turned it back on. The Live Node Count graph looked correct during the partition, but after the partition made it look as if all the nodes were live the whole time.

**During the partition**

<img width="929" alt="screen shot 2018-02-13 at 4 32 48 pm" src="https://user-images.githubusercontent.com/7085343/36184065-75998d50-10e6-11e8-9615-3c91f60da966.png">

During the partition, the two nodes were definitely considered non-live by the rest of the cluster. Hitting their `/_admin/v1/health` endpoint gave:

```json
{
  "error": "node is not live",
  "code": 14
}
```

**Immediately after healing the partition**

<img width="929" alt="screen shot 2018-02-13 at 4 33 25 pm" src="https://user-images.githubusercontent.com/7085343/36184070-7e36feac-10e6-11e8-9742-d2ef9b1c24a1.png">

This isn't a super important issue, but, I'd expect the graph to continue reflecting the fact that the two partitioned nodes were not "live". Maybe I'm making a mistake in interpreting "live" to refer to "node liveness" when it's really meant to mean "live" as in "the process was alive".

Detailed reproduction steps using Docker Compose are at https://www.cockroachlabs.com/docs/stable/training/network-partition-troubleshooting.html

**Comment by mrtracy** [comment]
This is a tricky issue.  The issue is, the dead node itself is reporting the total number of nodes when it goes down, and also when it comes back up, and the aggregator is interpolating between those two points.

**Comment by a-robinson** [comment]
Yeah, I don't have any easy fixes immediately in mind. And as I mentioned, it's not critically important. I wouldn't label it as 2.0 since I assume there's many more important issues you're already tackling.
