### ISSUE TITLE
sql: IN comparison wrong with tuples containing NULLs

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#22670]
Found while investigating #22371.

The comparison e.g. `(1, NULL) IN ((1, NULL))` should return NULL, but currently CockroachDB returns `true`. This is incorrect.

~Incidentally, the current code code for SHOW GRANTS (`sql/show_grants.go`) uses an invalid query that should not return any result, but the incorrect behavior above kicks in and makes SHOW GRANTS work nonetheless. Once the bug above is fixed, the query used by SHOW GRANTS should be double-checked~ (fixing in #22371)

**Comment by knz** [comment]
cc @RaduBerinde @nvanbenschoten

**Comment by RaduBerinde** [comment]
This needs to be fixed in both the expression evaluation code and the index constraints code.

**Comment by RaduBerinde** [comment]
It looks like it's broken for equality as well:
`SELECT ((1, 1), (2, NULL)) = ((1, 1), (2, NULL))` returns true.

Here's the kicker: it's also broken in postgres:

```
radu=> SELECT (1, NULL) = (1, NULL);
 ?column? 
----------
 
(1 row)

radu=> SELECT ((1, NULL::int), (2, 2)) = ((1, NULL::int), (2, 2));
 ?column? 
----------
 t
(1 row)

**Comment by RaduBerinde** [comment]
`(1, NULL) IS NOT DISTINCT FROM (1, NULL)` is also broken.

**Comment by RaduBerinde** [comment]
Fixing the "deep" tuple equality issue requires a lot of refactoring. I went down a few paths for a "contained" fix and they were all dead-ends. The proper way to do this would be to augment the `Datum.Compare` function to take a "mode" flag, and return a flag that indicates an ambiguous (NULL) result. This change is too big for 2.0, and the fact that it's also broken in postgres indicates these cases are not important in practice.

I am filing a separate issue for this. This issue tracks fixing NULL handling for IN and IS (NOT) DISTINCT FROM for tuples that are 1 level deep.
