### ISSUE TITLE
ui: alert when upgrade not completed and auto-upgrade disabled

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#22686]
As a final step of upgrading a cluster, the new version must be set using the command:

`SET CLUSTER SETTING version = (SELECT crdb_internal.node_executable_version())`

This is an easy step to forget or skip unintentionally. We should display a warning, similar to our new version available warning, calling on the user to run this command.

This warning should only display if all the nodes are already updated to the new version.

**Update (vilterp)**: we're going to upgrade the cluster version automatically (per @windchan7's RFC), but will display this banner if the user has opted out of the auto-upgrade.

**Comment by a-robinson** [comment]
There are users out there who may go for a long time without actually setting the version (e.g. packaged software developers who ship larger systems that run in their customers' datacenters), so I'd be wary about making this sort of warning too annoying.

**Comment by BramGruneir** [comment]
I'm not saying something jarring or annoying, but a warning like the
"there's a new version of cockroach available".

**Comment by vilterp** [comment]
This alert doesn't really have a good place to live at present. Thinking about an alerts page for 2.2; hopefully it can live there.
