### ISSUE TITLE
roachpb: Nil pointer dereference in RequestUnion.GetInner

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#22691]
https://sentry.io/cockroach-labs/cockroachdb/issues/463450155/

```
*log.safeError: stopper.go:179: runtime.errorString: runtime error: invalid memory address or nil pointer dereference
  File "github.com/cockroachdb/cockroach/pkg/roachpb/api.go", line 375, in GetInner
  File "github.com/cockroachdb/cockroach/pkg/storage/replica.go", line 1950, in makeCacheRequest
  File "github.com/cockroachdb/cockroach/pkg/storage/replica.go", line 1921, in done
  File "github.com/cockroachdb/cockroach/pkg/storage/replica_proposal.go", line 119, in finishRaftApplication
  File "github.com/cockroachdb/cockroach/pkg/storage/replica.go", line 4518, in processRaftCommand
...
(12 additional frame(s) were not displayed)

stopper.go:179: runtime.errorString: runtime error: invalid memory address or nil pointer dereference
```

**Comment by BramGruneir** [comment]
This is in version 1.1.5.

Assigning to @bdarnell for triage.  It looks like @petermattis touched this code last.

**Comment by bdarnell** [comment]
The same cluster had a similar panic in https://sentry.io/cockroach-labs/cockroachdb/issues/462680307/. The stack trace is slightly different, though:

```
stopper.go:179: runtime.errorString: runtime error: invalid memory address or nil pointer dereference
github.com/cockroachdb/cockroach/pkg/roachpb/api.go in GetInner at line 375
github.com/cockroachdb/cockroach/pkg/keys/keys.go in Range at line 680
github.com/cockroachdb/cockroach/pkg/storage/replica.go in done at line 1915
github.com/cockroachdb/cockroach/pkg/storage/replica_proposal.go in finishRaftApplication at line 119
github.com/cockroachdb/cockroach/pkg/storage/replica.go in processRaftCommand at line 4518
github.com/cockroachdb/cockroach/pkg/storage/replica.go in handleRaftReadyRaftMuLocked at line 3495
github.com/cockroachdb/cockroach/pkg/storage/replica.go in handleRaftReady at line 3187
github.com/cockroachdb/cockroach/pkg/storage/store.go in processReady at line 3578
github.com/cockroachdb/cockroach/pkg/storage/scheduler.go in worker at line 216
github.com/cockroachdb/cockroach/pkg/storage/scheduler.go in func2 at line 167
github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go in func1 at line 196
```

In `done()`, a call to `Range` always precedes a call to `makeCacheRequest`:  

https://github.com/cockroachdb/cockroach/blob/7ce237555bf7d1f62723f4b017b0784802afa69d/pkg/storage/replica.go#L1914-L1921

Both `Range` and `makeCacheRequest` end up calling `GetInner` on every element of the batch, so it doesn't make sense that we could see a panic in `makeCacheRequest` without also seeing a panic in the previous `Range` call, unless there's a race and something is concurrently modifying the batch.

**Comment by bdarnell** [comment]
The panicking function is `RequestUnion.GetInner`, which is a single line (`return ru.GetValue().(Request)`. I've been assuming that the error here is that `GetValue()` returns nil, and then the type conversion panics. It does panic, but with a different message, at least when I reproduce this pattern [in isolation](https://play.golang.org/p/drg4h36WxyG): `interface conversion: interface is nil, not Request` (and I've also verified this with the older version of go used for 1.1.5).

Is there any other way that the `nil pointer dereference` panic could be triggered here? I don't see any. `ru` in that line is a struct, so it can't be nil, and I don't see any way short of a memory-stomping bug that `GetValue` could panic. 

This happened twice on one cluster, and that cluster hasn't seen any other errors, so it does look like there's something to it, but I'm not sure what else we can do to track this down. Moving to 2.1.

**Comment by tschottdorf** [comment]
The sentry issue does not exist any more. If the problem still exists, we should use a more recent report to kick off a new investigation.
