### ISSUE TITLE
cli: tab completion error messages are counterproductive

### ISSUE THREAD

**Issue by arjunravinarayan** [cockroachdb/cockroach#22706]
When I press `tab` on the cockroach command line shell, I get the following message:

`tab completion not supported; append '??' and press tab for contextual help`

In particular, when I paste SQL that has tabs in it, it causes my shell to barf a lot of unhelpful error messages (not always, but sometimes. [It might have something to do with how the pasting is handled by the terminal emulator?](https://cirw.in/blog/bracketed-paste)). This is particularly annoying because large SQL queries are hard to understand, so I go to a lot of trouble to format them in an emacs buffer with lots of tabs, and then paste them into the shell for execution. This entire workflow is annihilated by these error messages.

This did not use to happen. While it might be helpful for new users, there could be a flag to turn this behavior off. I would like tabs to be silently ignored.

**Comment by knz** [comment]
@arjunravinarayan until I look at this, try `M-x untabify` after selecting your entire buffer.

**Comment by arjunravinarayan** [comment]
Of course there's an emacs command for that. Thank you!

**Comment by knz** [comment]
@benesch feel free to bump the vendor dep to catch your fix
