### ISSUE TITLE
sql: equality, IN incorrect when dealing with "deep" tuples

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#22717]
`SELECT ((1, 1), (2, NULL)) = ((1, 1), (2, NULL))` and `SELECT ((1, 1), (2, NULL)) IN (((1, 1), (2, NULL)))` return true instead of NULL.

See https://github.com/cockroachdb/cockroach/issues/22670#issuecomment-365772466

**Comment by knz** [comment]
@RaduBerinde I think this issue still exists right?

**Comment by RaduBerinde** [comment]
Yes.

**Comment by jordanlewis** [comment]
Wait, but to be clear, we've decided that this is also a bug in Postgres, right?

This doesn't seem like an issue that people are going to notice in practice.

**Comment by jordanlewis** [comment]
(notice or care about)

**Comment by RaduBerinde** [comment]
Yes, it is also in PG. I agree it's probably not very important.

**Comment by jordanlewis** [comment]
Reassigning to @knz since he knows about this. Feel free to close this if you think it's not important.

**Comment by knz** [comment]
I was addressing this #27885. Will look further.

**Comment by jordanlewis** [comment]
Closing this - the first one works as expected, and the second one is identical to Postgres.
