### ISSUE TITLE
Latest tag for docker image pointing to v1.0.7

### ISSUE THREAD

**Issue by F21** [cockroachdb/cockroach#22727]
**BUG REPORT**

1. Please supply the header (i.e. the first few lines) of your most recent
   log file **for each node in your cluster**. On most unix-based systems
   running with defaults, this boils down to the output of

    N/A

2. Please describe the issue you observed:

- What did you do?
Pulled the docker image using the latest tag to run some tests.

- What did you expect to see?
The UUID type should be supported

- What did you see instead?
UUIDs did not work correctly.

The `latest` tag on docker hub was pointing to the `1.1.x` series. There was a newer build in the `1.0.x` series 2 days ago and the latest tag is now pointing to `1.0.7`. This broked a few development environments where we were assuming the `latest` tag will always be the newest version that's is tagged.

**Comment by BramGruneir** [comment]
Thanks for reporting this!

I've re-pushed our latest to be v1.1.5.
https://hub.docker.com/r/cockroachdb/cockroach/tags/

Let me know if it works.

That being said, relying on the latest tag is sadly not a good choice.  See http://container-solutions.com/docker-latest-confusion/ for more details as to why.
