### ISSUE TITLE
Split tables into their own ranges.

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#2272]
Multiple reasons:
* need to gossip the system tables
* zone configs will be applied per table. sequential tables with the same zoning could avoid splits, but that seems like an unnecessary complication: #2090 
* accounting will be made easier (not critical)

We can either create a sentinel value when creating a table and split at `CREATE` time, or we can delay the split until the first write.
This would effectively create a range for each: `<tableprefix>/<tableid>`

**Comment by bdarnell** [comment]
Why do we need to wait until the first write? Do we have a problem with zero-width splits?

**Comment by MBerhault** [comment]
Not sure, I need to investigate that. We may.

**Comment by spencerkimball** [comment]
There's no reason zero-width splits won't work, short of fixable bugs. Let's split as soon as a table is created; no sense in adding complexity with a sentinel. We'll also want splits at bootstrap for each system table.

So, at bootstrap let's say we have system tables for users and databases. We'd split the key space immediate at <users-start> and <dbs-start>. This basically means we end up with three ranges: KeyMin -> <users-start>, <users-start> -> <dbs-start>, <dbs-start> -> KeyMax.

If adding table T1, we'd split again at <T1-start>.

**Comment by MBerhault** [comment]
system tables are just the same as regular tables as far as that goes (same `<tableprefix><tableid>` key prefix), we'll just call split somewhere else is all. The rule for non-mergable ranges will be the same.

**Comment by tschottdorf** [comment]
how are interleaved tables affected by this? Any op that touches more than one table will suffer from having to span ranges and allow for contention (because transactions begin writing intents), so we'll really need interleaving at some point.

**Comment by petermattis** [comment]
A child table of a parent table in an interleaved setup will have to share the zone configuration with the parent table.

**Comment by MBerhault** [comment]
What will they look like at the kv level though? will they be under the same prefix, or still have two separate table IDs? If the latter, are they even guaranteed to be sequential?

I agree ultimately that we'll want to be more conservative with creating ranges but as a first pass, forced splits per table might be easier.

Ultimately, we'll need to worry about the efficiency of cross-range transactions since any sizable table will span multiple ranges.

**Comment by petermattis** [comment]
Interleaved tables will share the prefix of the parent table. The child table will have a separate table ID, but all of its keys will be prefixed with the primary key of the parent table. This hasn't been completely fleshed out yet, but sort of follows from the term "interleaved". The child keys are interleaved with the keys of the parent. This makes joining the parent and child table on the primary key extremely efficient.
