### ISSUE TITLE
sql: implement privilege-related built-ins.

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#22734]
The postgresql list is: https://www.postgresql.org/docs/8.4/static/functions-info.html#FUNCTIONS-INFO-ACCESS-TABLE

name| return type | description
-- | -- | --
has_any_column_privilege(table, privilege) | boolean | does current user have privilege for any column of table
has_column_privilege(user, table, column, privilege) | boolean | does user have privilege for column
has_column_privilege(table, column, privilege) | boolean | does current user have privilege for column
has_database_privilege(user, database, privilege) | boolean | does user have privilege for database
has_database_privilege(database, privilege) | boolean | does current user have privilege for database
has_foreign_data_wrapper_privilege(user, fdw, privilege) | boolean | does user have privilege for foreign-data wrapper
has_foreign_data_wrapper_privilege(fdw, privilege) | boolean | does current user have privilege for foreign-data wrapper
has_function_privilege(user, function, privilege) | boolean | does user have privilege for function
has_function_privilege(function, privilege) | boolean | does current user have privilege for function
has_language_privilege(user, language, privilege) | boolean | does user have privilege for language
has_language_privilege(language, privilege) | boolean | does current user have privilege for language
has_schema_privilege(user, schema, privilege) | boolean | does user have privilege for schema
has_schema_privilege(schema, privilege) | boolean | does current user have privilege for schema
has_server_privilege(user, server, privilege) | boolean | does user have privilege for foreign server
has_server_privilege(server, privilege) | boolean | does current user have privilege for foreign server
has_table_privilege(user, table, privilege) | boolean | does user have privilege for table
has_table_privilege(table, privilege) | boolean | does current user have privilege for table
has_tablespace_privilege(user, tablespace, privilege) | boolean | does user have privilege for tablespace
has_tablespace_privilege(tablespace, privilege) | boolean | does current user have privilege for tablespace
pg_has_role(user, role, privilege) | boolean | does user have privilege for role
pg_has_role(role, privilege) | boolean | does current user have privilege for role

Obviously some do not apply to us, but we could easily implement table/schema/role related functions.

**Comment by mberhault** [comment]
@jordanlewis mentioned the need for `has_schema_privilege` for external tools.

**Comment by jordanlewis** [comment]
That's needed for #15441.

**Comment by nvanbenschoten** [comment]
Related to https://github.com/cockroachdb/cockroach/issues/20784 as well. @jordanlewis we can probably close that in favor of this issue.

I mocked out `has_schema_privilege` and pgweb began working like a charm! We should aim to get this in for the 2.0 release.
