### ISSUE TITLE
ui: hovering over an events summary entry should show the full entry in the cluster overview

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#22742]
Having to click on 'view all events' shouldn't be needed.

**Comment by couchand** [comment]
Yeah, that is annoying.

We've got a lot of changes to the events log backed up behind other stuff and they didn't make it into 2.0.  I could see this being useful to get in, but it's not as critical as the many other bugs we've already prioritized, so I'm pushing it back to 2.1.

Feel free to do it if you feel differently and you have time, @BramGruneir.

**Comment by BramGruneir** [comment]
Yeah, I just put in the 2.0 to get it triaged :)

I'll get to it if I have chance in bug fix land.  Got bigger fish to fry for now.
