### ISSUE TITLE
build: push minor tags to docker hub

### ISSUE THREAD

**Issue by F21** [cockroachdb/cockroach#22756]
**FEATURE REQUEST**

1. Does an issue already exist addressing this request? If yes, please add a :+1: reaction to the existing issue. If not, move on to step 2.

2. Please describe the feature you are requesting, as well as your proposed use case for this feature.

It would be nice if minor tags for images can be pushed to docker hub. For example, `1.1` would point to the latest image in the `1.1.x` series, `1.0` would point to the latest in the `1.0.x` series. This would allow us to pin our images to a certain series since we generally don't care about which patch release we are using, as long as it's the latest version in that series.

3. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

nice-to-have

**Comment by rail** [comment]
@jlinder sounds like we implemented this already https://hub.docker.com/repository/registry-1.docker.io/cockroachdb/cockroach/tags?page=1&ordering=last_updated&name=latest

**Comment by jlinder** [comment]
Yes, we do publish the latest minor version tags to Docker Hub now, though the format is `latest-vX.Y`. For example: `latest-v21.1`.

Thank you for pointing this out.
