### ISSUE TITLE
Multiraft: snapshot/compaction integration

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#228]
We need to be able to produce and apply snapshots so we can garbage collect the raft logs. This will work somewhat differently from MemoryStorage: We can synthesize snapshots on-demand in the Storage.Snapshot method instead of tying snapshot creation to an explicit Compact call. We can then advance Storage.FirstIndex whenever we discard old log entries.

**Comment by spencerkimball** [comment]
@bdarnell is this still open?

**Comment by bdarnell** [comment]
This is done.
