### ISSUE TITLE
Native JSON / JSONB types

### ISSUE THREAD

**Issue by 0xbaadf00d** [cockroachdb/cockroach#22802]
**FEATURE REQUEST**

Is it possible to implement native JSON and/or JSONB types? Since PostgreSQL can handle these types, a lot of ORM use it when developer use List and HashMap fields on model.

```
We got the following error: ERROR: syntax error at or near "json" Détail :
source SQL:
create table merchant (
 id bigserial not null,
 display_name varchar(30) not null,
 description varchar(255),
 opening_time json, ^ Indice : try \h CREATE TABLE [ERROR:0, SQLSTATE:42601], while trying to run the SQL script.
```

Regards

**Comment by a-robinson** [comment]
JSONB will be included in the upcoming 2.0 release in early April. If you want to try it before then, you can download the latest alpha release from our website here: https://www.cockroachlabs.com/docs/dev/install-cockroachdb.html
