### ISSUE TITLE
Show node locality on web UI

### ISSUE THREAD

**Issue by 0xbaadf00d** [cockroachdb/cockroach#22801]
**FEATURE REQUEST**

Please add a way to see node locality (ex: region=eu,datacenter=ovh-roubaix) from the web UI.

Maybe it could be nice to have a "geo" map of node too

**Comment by a-robinson** [comment]
I believe this will be more obvious in the 2.0 release, but will let @couchand speak on that.

In the meantime, in v1.1 you can see each node's locality on the admittedly hard-to-find node diagnostics page at `/#/reports/nodes`

**Comment by couchand** [comment]
Yep, 2.0 adds two new pages that specifically address this:

- The landing page is a new cluster overview.  The enterprise version has a geographical map showing the location of datacenters and some top-level metrics.
- There is also a debug page listing the organization of localities & nodes, which is available in both the enterprise and open source versions.  This can be found at `/#/reports/localities`.

Thanks for the suggestion, @0xbaadf00d.  When you get a chance, please do take a look at the new pages and give us any feedback or ideas you have about making these pages more useful.

**Comment by couchand** [comment]
Closed by #22763.
