### ISSUE TITLE
roachtest: verify translation invariance of store directories

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#22846]
You're supposed to be able to move a store directory to a different location (or even machine). This can be broken accidentally. For example, specifying a DistSQL temp dir in absolute terms is likely going to lead to that absolute path to leak into the text file we put into the store dir (for later cleanup). Bugs like that need to be caught in a test that takes an existing cluster, moves the store locations, and starts it back up again.

@petermattis assigning you for thoughts on how this should be achieved with `roachtest` as it stands today.

**Comment by petermattis** [comment]
I'd do this via a sequence of commands:

```
roachprod start <cluster>
roachprod stop <cluster>
roachprod run mv /mnt/data1/cockroach /mnt/data1/cockroach.new
roachprod start -a --store=/mnt/data1/cockroach.new
```

Unfortunately, the paths that are specific to local vs remote. I think we could add a `{store-dir}` variable to alleviate that. Am I misunderstanding what the challenge is here?

**Comment by tschottdorf** [comment]
Hmm, you'd call roachprod directly? I thought we'd want to go through `roachtest` and I wasn't clear on how easy that would be. I suppose I could plumb `-a` through an option to `Start` or somehow make `newCluster` work, but you're probably right that I'd be better off to just peel back all of that.

**Comment by petermattis** [comment]
> Hmm, you'd call roachprod directly?

No, my previous comment was shorthand. I'd plumb through a mechanism for passing arguments to `roachprod start`. Something like:

```
c := newCluster(ctx, t, nodes+1, "--local-ssd")
defer c.Destroy(ctx)

c.Put(ctx, cockroach, "./cockroach", c.Range(1, nodes))
c.Put(ctx, workload, "./workload", c.Node(nodes+1))
c.Start(ctx, c.Range(1, nodes))
c.Stop(ctx, c.Range(1, nodes))
for i := 1; i <= nodes; i++ {
  c.Run(ctx, i, "mv {store-dir} {store-dir}.new")
}
c.Start(ctx, c.Range(1, nodes), Arg("--store={store-dir}.new")))
```

The `option` stuff was intended to support this, I just didn't get around to fleshing it out for this purpose yet.

**Comment by petermattis** [comment]
@tschottdorf Putting this back on your plate as I think the `roachprod` support is there. Not necessary for 2.0, but I think we should add this test soon.
