### ISSUE TITLE
sql: no way to wait for database descriptor updates?

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#22841]
The following sequence of SQL statements was observed to flake in logictests (https://github.com/cockroachdb/cockroach/issues/22798):

```
GRANT DROP ON DATABASE privs TO testuser
-- change user to "testuser"
DROP DATABASE privs CASCADE
-- pq: user testuser does not have DROP privilege on database privs
```

It seems the node executing the `DROP DATABASE` does not have an updated copy of the database descriptor. @petermattis suggests blocking the connection until the new descriptor has been gossiped—I guess we do this for schema changes?—but according to @mberhault that infrastructure only exists for table descriptors, and not for database descriptors.

Assigning to @vivekmenezes for triage.

**Comment by mberhault** [comment]
My comment about having this for tables and not databases comes from https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/grant_revoke.go#L107:

```
		switch d := descriptor.(type) {
		case *sqlbase.DatabaseDescriptor:
			if err := d.Validate(); err != nil {
				return nil, err
			}

		case *sqlbase.TableDescriptor:
			if err := d.Validate(ctx, p.txn); err != nil {
				return nil, err
			}
			if err := d.SetUpVersion(); err != nil {
				return nil, err
			}
			p.notifySchemaChange(d, sqlbase.InvalidMutationID)
		}
	}
```

`notifySchemaChange` **seems** to make the local node wait refresh descriptors faster. I could not find an equivalent for database descriptors. But I'm not intimately familiar with the schema change code.

This mechanism is used for privileges as well as role changes (the role cache uses the `system.role_members` table version to mark things as expired). Without it, logic tests would require lots of sleeping (or some other type of coordination).

If this is indeed what this does, then having an equivalent for database descriptors would be a nice way of deflaking the linked test (as well as provide equivalent behavior when changing database privileges).

**Comment by knz** [comment]
To recap: schema changes are properly synchronized upon because table descs are versioned. Database descriptors are not. There was previously logic to wait on propagation of db desc changes in logic tests. Recent PR removed that logic. Needs to be added back. cc @andreimatei

**Comment by benesch** [comment]
If our logic tests need it, our users need it to. Can we do something more reusable this time around?

**Comment by vivekmenezes** [comment]
@knz both the above statements are DDL statements and so should not be reading any cached versions of the database. This could be caused by your change.

**Comment by knz** [comment]
@vivekmenezes the problem here is not with the cache. I think the problem is that the change on 1 node is not propagating fast enough to another node in the test cluster.

**Comment by benesch** [comment]
Now that I think about it: do logic tests round-robin SQL queries to different nodes in the test cluster, or do they all hit the same node?

**Comment by petermattis** [comment]
> Now that I think about it: do logic tests round-robin SQL queries to different nodes in the test cluster, or do they all hit the same node?

I believe there is a connection per user, but note how the test in question is using 2 different users. Shouldn't be a problem for a single node cluster, though.

**Comment by benesch** [comment]
Oh, good point. Looks like "default" logic tests only start a one-node cluster. (I was misled by the use of `StartTestCluster`.)

So perhaps it _is_ a problem with the cache. @knz are you sure there isn't a missing `skipCache` in the new DROP DATABASE codepath?

**Comment by knz** [comment]
I checked grant/revoke but not drop yet. Will do when I'm back in two hours.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
