### ISSUE TITLE
optimizer: convert many point lookups into a single scan

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#22851]
The optimizer can help with some queries that translate today into a group of point lookups. The point lookups are close to each other can be translated into a single scan lookup for the entire range covering all point lookups

**Comment by petermattis** [comment]
@vivekmenezes Do you have an example query/schema this would help?

**Comment by jordanlewis** [comment]
```
CREATE TABLE t (a INT PRIMARY KEY, b TEXT);

SELECT * FROM t WHERE a IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10);
```

**Comment by petermattis** [comment]
We already perform only a single scan for that query. 

```
root@localhost:26257/t> EXPLAIN SELECT * FROM t WHERE a IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10);
+------+-------+-------------+
| Tree | Field | Description |
+------+-------+-------------+
| scan |       |             |
|      | table | t@primary   |
|      | spans | /1-/10/#    |
+------+-------+-------------+
(3 rows)
```

To get multiple spans there would have to be separation between the values:

```
root@localhost:26257/t> EXPLAIN SELECT * FROM t WHERE a IN (1, 3, 5, 7, 9);
+------+-------+-----------------------------------------+
| Tree | Field |               Description               |
+------+-------+-----------------------------------------+
| scan |       |                                         |
|      | table | t@primary                               |
|      | spans | /1-/1/# /3-/3/# /5-/5/# /7-/7/# /9-/9/# |
+------+-------+-----------------------------------------+
(3 rows)
```

But we're only sending out a single batch request here. It might be worthwhile to combine this into a single `ScanRequest`. It also might not.

**Comment by jordanlewis** [comment]
Oh. I don't know what Vivek meant, then. I guess there's some kind of heuristic that could be applied. This seems tricky.

**Comment by vivekmenezes** [comment]
I believe what @arjunravinarayan and me were hypothesizing that for this kind of a query there is a bottleneck in rocksdb when n queries translate to n * k rocksdb lookups on the same range and it would be better to have n scan lookups. @arjunravinarayan has a workload where he has seen this with large values of k.

**Comment by petermattis** [comment]
@vivekmenezes Seems like a reasonable hypothesis, though it would be helpful to have a specific query to optimize for. Perhaps my second example above suffices. @arjunravinarayan?

**Comment by jordanlewis** [comment]
cc @solongordon relates to an earlier conversation. So we do do some of this stuff, it's just at the SQL level and not at KV.

**Comment by jordanlewis** [comment]
I don't think this is too important.
