### ISSUE TITLE
distsql: ensure versioning of new functionality is recorded

### ISSUE THREAD

**Issue by arjunravinarayan** [cockroachdb/cockroach#22856]
DistSQL has an inbuilt versioning system to ensure that incompatible changes are not planned in mixed version clusters. Some discussion revealed that we have not been thorough in ensuring that any breaking changes were properly versioned. This is a tracking issue for changes that might require bumping the version number. Please add in any changes that you suspect might require a version change.

As a rough start, any changes that modified `processors.proto` almost certainly requires a version bump.

We will also need to do some mixed version cluster testing.

- [x] Intersect, Except processors (@abhimadan )
- [x] Lookup joins (@pbardea )
- [x] IMPORT with no primary key (@mjibson )
- [x] antijoins/semijoins. These are not planned, but they still should enforce cluster versions. (@pbardea )
- [x] `json_agg` (cc @justinj)
- [x] TableReader changes since 1.1 (@arjunravinarayan to investigate) 

All we need to do right now is to upgrade the version number and cherry-pick it, but we should thoroughly document all our breaking changes in `distsqlrun/version_history.txt` so please let me know what I should write for the bit I've assigned to you.

**Comment by mjibson** [comment]
import with no primary key: the CSV read proto changed its file list to add an index field. Version mismatch would cause the receiving side to think it had 0 files to process, so it would silently be incorrect. So I think that means bumping the min version?

**Comment by abhimadan** [comment]
If the addition of `json_agg` causes problems, then `array_agg` may be a problem as well, as that was recently added to DistSQL.

**Comment by arjunravinarayan** [comment]
:+1:.

What's going to happen is:

1) We're going to bump the version, and say there were a miscellany of changes (and list them all out for completeness in `version_history.txt`). If we forget one, that's a _documentation_ problem, not an actual problem, since it will be covered with the version bump.
2) Any users using published releases will not observe any problems, since 1.1.x will be on DistSQL version 8, and 2.x will be on version >9 (min version 9).
3) However, there are commits in our repository that, if manually built, will cause crashes in mixed-version clusters since there are no version checks. This issue will have to serve as a documentation of that fact, since the ball has already been dropped.
4) I'll be more vigilant in the future to ensure this doesn't happen going forward.

**Comment by pbardea** [comment]
For semi/anti and lookup joins respectively:
```
  - Two new join types (LEFT_SEMI, LEFT_ANTI) were added to the JoinType enum
    to support new types of joins that can be used to improve performance of
    certain queries. The new join types would not be recognized by a server
    with an old version number.
  - The JoinReaderSpec was modified by adding three new properties
    (lookup_columns, on_expr, and index_map) to enable the JoinReader to perform
    lookup joins enabling more efficient joins for certain queries. Old server
    versions would not recognize these new properties.
```

**Comment by abhimadan** [comment]
INTERSECT/EXCEPT and ARRAY_AGG notes:
```
- Two new join types (INTERSECT_ALL, EXCEPT_ALL) were added to the sqlbase.JoinType enum
  to support INTERSECT and EXCEPT queries. These "set operation" queries can now
  be planned by DistSQL, and older versions will not be capable of supporting these
  queries.
- The ARRAY_AGG aggregate function was added to the AggregatorSpec_Func enum.
  Older versions will not recognize this new enum member, and will not be able to
  support aggregations with ARRAY_AGG.
```

**Comment by justinj** [comment]
`JSON_AGG` is the same situation as `ARRAY_AGG`.

**Comment by arjunravinarayan** [comment]
Thanks everyone. I've opened a PR including all of your notes. It's at #22886 if you'd like to review it.
