### ISSUE TITLE
workload: handle botched fixture creations

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#22867]
It has happened to me a few times today that I was trying to create a large fixture, say,

```
workload fixtures store tpcc --warehouses 500
```

and then I accidentally close my laptop and the process barfs. You can't re-run it as the GCS directory exists; you have to manually go and delete it (and picking the right folder may not be easy).

I'd be better to write a marker file when the creation is complete, and to nuke the existing directory in the absence thereof.

**Comment by jordanlewis** [comment]
There's a workaround for this: specify a different seed. You can also delete the half created fixture by hand with `gsutil`: `gsutil ls gs://cockroach-fixtures/workload/tpcc`
