### ISSUE TITLE
sql: Include query in "leftover bytes" report 

### ISSUE THREAD

**Issue by solongordon** [cockroachdb/cockroach#22865]
#22685 changed the "unexpected leftover bytes" assertion to only report to Sentry rather than panic in release builds. But now those reports no longer include the relevant SQL statement, which limits how useful the reports are. Find a way to include the statement, probably by passing it down through a context.

**Comment by dt** [comment]
just for the record, that'll need to be a _scrubbed_ query if we send it to sentry. We already have that computed in some cases, e.g. we have an `AnonymizedStr` on `PreparedStatement`.
