### ISSUE TITLE
cli/dump: nice-to-have - dump command for a table could include row selection criteria

### ISSUE THREAD

**Issue by rjaxin** [cockroachdb/cockroach#22901]
something like:

`cockroach dump <mydb> <mytable> --where="<mycolumn> = '<myvalue>' AND ..."`

This would be handy for duplicating subsets of data for testing purposes, etc.

Workaround proposed by @justinj in https://gitter.im/cockroachdb/cockroach:

```
INSERT INTO new_table SELECT * FROM old_table WHERE ...
and then dump the new table
```

This workaround will work, but submitting RFE as requested.

Thanks!

**Comment by dianasaur323** [comment]
@rjaxin for use cases like the one you mentioned, we have been suggesting that users run a select and pipe the results into a CSV file. For example, you can try running cockroach sql --e "SELECT ..."  > output. csv --format=csv with the flags you need included in that command as well. Does that work for your use case, or did you specifically need things in the dump format?

**Comment by rjaxin** [comment]
@dianasaur323 I had tried that as well.  The difference with this and dump is that:

1. No control over the export format (data, table schema, or both)
2. Table name is hard-coded to `result` rather than the actual table name

**Comment by dianasaur323** [comment]
@rjaxin Got it, yes, it's annoying that the data and table schema format are disjoint when you don't use dump. We can look into how hard it would be to support this, or at least to fix these usability edge cases you are hitting. 

Regarding import csv, we are actually taking the experimental flag off of import csv in 2.0. We have also removed the temp storage requirement, so you won't need to specify a temporary storage space. That being said, you will still need to have a url hosting the csv file, unfortunately.

It's interesting that you mention that it being experimental kept you from exploring further. If you don't mind me asking, how do you feel about us labeling features as experimental? Do you think it helps you as a user?

**Comment by piyush-singh** [comment]
Discussed with @knz today: we have EXPORT now (which we didn't have back then) which satisfies this use case.
Closing unless there's a reason to have a dump-specific variant of this.
