### ISSUE TITLE
sql: tests for all uses of txn.CommitTimestamp

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#22909]
The SQL layer occasionally uses txn.CommitTimestamp() instead of txn.OrigTimestamp() so that it observes the commit timestamp instead of the start timestamp.

Add tests for all cases where sql explicitly calls CommitTimestamp() so it's use case is well understood.

**Comment by andreimatei** [comment]
Isn't this what #22440 is trying to do?

**Comment by vivekmenezes** [comment]
https://github.com/cockroachdb/cockroach/pull/22932

**Comment by vivekmenezes** [comment]
@spencerkimball for advice on how to create conflict in a sql test that will trigger the kv layer push. I'd like to write a number of tests that do this.

**Comment by jordanlewis** [comment]
@vivekmenezes I don't understand the thrust of this issue. Is it still important? It would be great to get context on this if it's still important, or close it. Thank you!

**Comment by vivekmenezes** [comment]
I'm closing this in favor of simply removing CommitTimestamp() and fixing https://github.com/cockroachdb/cockroach/issues/17698
