### ISSUE TITLE
NPE in raft.removeNode(mcc.msg.NodeID)

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#2291]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x8 pc=0x4671397]

goroutine 4154 [running]:
github.com/coreos/etcd/raft.(*multiNode).run(0xc820463020)
        /Users/tschottdorf/go/src/github.com/coreos/etcd/raft/multinode.go:253 +0x14e7
created by github.com/coreos/etcd/raft.StartMultiNode
        /Users/tschottdorf/go/src/github.com/coreos/etcd/raft/multinode.go:56 +0x30d
```

offending code:
```go
			case pb.ConfChangeRemoveNode:
				group.raft.removeNode(mcc.msg.NodeID)
```

in (not raft-pertinent) WIP freshly rebased on top of master at time of writing. Can't reproduce.

**Comment by mrtracy** [comment]
Ben opened a few pull requests against etcd last week for similar NPEs:

coreos/etcd#3396
coreos/etcd#3404

These all related to configuration changes.

**Comment by bdarnell** [comment]
Probably too late now, but do you have any more information? Which test case was this panic in? Do you have any more of the logs?

I suspect it's a race involving Store.RemoveReplica (in TestReplicateAddAndRemove), which might put this failure in the same category as #1911.

**Comment by bdarnell** [comment]
Just went back to the logs in #1911; this is an exact dupe.
