### ISSUE TITLE
storage: bad node liveness state on restarted cluster

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#22921]
Continuing investigations for #22787 on a 3-node cluster has left the cluster in a very unhappy state: no node can successfully start up.

The admin ui is unresponsive, goroutine dumps seem to show a bunch of threads trying to acquire leases, and the logs on all 3 nodes contain an endless parade of:

```
W180222 05:02:58.413362 161 storage/node_liveness.go:481  [n1,hb] slow heartbeat took 4.5s
W180222 05:02:58.413382 161 storage/node_liveness.go:413  [n1,hb] failed node liveness heartbeat: context deadline exceeded
W180222 05:03:02.913797 161 storage/node_liveness.go:481  [n1,hb] slow heartbeat took 4.5s
W180222 05:03:02.913823 161 storage/node_liveness.go:413  [n1,hb] failed node liveness heartbeat: context deadline exceeded
```

@a-robinson can I please get a moment of your time to help me look at this? This is on the `jordan-tpcc` roachprod cluster, which you should be able to poke around at.

**Comment by jordanlewis** [comment]
PEBKAC.

**Comment by a-robinson** [comment]
What did you do wrong?

**Comment by jordanlewis** [comment]
I was running a build that contained some new tracing I've been working on to instrument slow lease requests. Apparently that new tracing had a horrible bug in it - reverting the code change immediately removed the problem.
