### ISSUE TITLE
importccl: various import failures

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#22924]
Build v2.0-alpha.20180212-736-gd2b6b62 (note: I can't find a commit containing gd2b6b62 so I'm not sure what commit this is at).

Running:

```
import table lineitem create using 'gs://cockroach-fixtures/tpch-csv/schema/lineitem.sql' CSV DATA (
'gs://cockroach-fixtures/tpch-csv/sf-100/lineitem.tbl.1',
'gs://cockroach-fixtures/tpch-csv/sf-100/lineitem.tbl.2',
'gs://cockroach-fixtures/tpch-csv/sf-100/lineitem.tbl.3',
'gs://cockroach-fixtures/tpch-csv/sf-100/lineitem.tbl.4',
'gs://cockroach-fixtures/tpch-csv/sf-100/lineitem.tbl.5',
'gs://cockroach-fixtures/tpch-csv/sf-100/lineitem.tbl.6',
'gs://cockroach-fixtures/tpch-csv/sf-100/lineitem.tbl.7',
'gs://cockroach-fixtures/tpch-csv/sf-100/lineitem.tbl.8'
) WITH  delimiter='|';
```

on a 4 node GCE cluster with local SSDs. It got to near the end (not sure how far, unclear if it was in its final cleanup to add the table desc or not, probably not) and then printed to the console:

> pq: could not mark job 324978771508101121 as failed: context canceled: context canceled

But then it restarted itself since it couldn't mark itself as failed, but then later failed (around 80%) with:

> addsstable [/Table/51/2/5194978/2/0,/Table/51/2/7777216/5): verifying sstable data: last key /Table/51/2/6485383/4/0 not in request range [/Table/51/2/5194978/2/0,/Table/51/2/6485383/4)

So two bugs.

1) Gotta figure out these context canceled errors.
2) I thought I fixed the second error. Guess not.

**Comment by a-robinson** [comment]
Did you save the logs from this? Was there any indication of node liveness problems?

**Comment by mjibson** [comment]
No. There's a nightly roachtest for this now, but it hasn't been running due to other problems.

**Comment by nvanbenschoten** [comment]
I just saw a run of `workload fixtures load tpcc --warehouses=5000` fail with the error:
```
Error: restoring fixture: pq: could not mark job 328706682499104769 as failed: importing 6026 ranges: context canceled: context canceled
```

@mjibson do you want me to take a look at my cluster?

**Comment by mjibson** [comment]
I would, but I can't find a job with that id on any test cluster with your prefix. Did the job with the failure above restart itself (it should have)? If so, did it fail or succeed that time (that would have only been visible in the jobs tab, not in the console)?

**Comment by mjibson** [comment]
I attempted to trigger the addsstable bug by restarting an import in a stress test with various sstable chunk sizes and samplings but was unable to do so. My current plan is to wait until it is reported again before investigating more.

**Comment by mjibson** [comment]
These have been fixed or tracked down.
