### ISSUE TITLE
sql: the new conn logic forgets to call `Executor.RecordError`

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#22930]
This method is meant to track unimplemented features.
It is called by `v3.go` but not the new `conn.go`.

cc @dt

**Comment by knz** [comment]
Needs cherry pick to 2.0

**Comment by knz** [comment]
So @dt points me to the fact the new code calls `recordUnimplementedErrorMaybe` not `RecordError`. So it's not so bad. The rest will be caught by #22912.

**Comment by dt** [comment]
We probably will want to cherrypick #22912 though since it does fix a case where, depending on how the error was returned to conn_executor, it could go uncounted -- we were only making that call in the `payload.(payloadWithError)` case but no in the non-nil `res.Err()` case.

**Comment by knz** [comment]
yes indeed.

**Comment by andreimatei** [comment]
Hey friends, thanks for all your fixes. Is there anything left for me to do around here?

**Comment by knz** [comment]
Andrei not you no. David picking this up from here.
