### ISSUE TITLE
sql: pg compatibility with Zabbix

### ISSUE THREAD

**Issue by ikzelf** [cockroachdb/cockroach#22937]
I try to get a postgres application running on cockroachDB. Apparently it issues settings that are not needed or/and not implemented in cockroachDB.
For postgres compatibility it would be nice to implement these in cdb or at least to ignore this kind of settings and only log them, if they have no real meaning for cdb in a way that it would interfere with the application's functions.
set **escape_string_warning** to off
Looking into the source I expect that the next message will have to do with
set **bytea_output**=escape;

For what it's worth ... the application recognises cdb as PostgreSQL Server version: 90500

Jira issue: CRDB-5835

**Comment by knz** [comment]
OK we'll have a look.

Out of curiosity what application would that be?

**Comment by knz** [comment]
Can you also run this app against a real pg server and report everything it sends to the server when it initially connects? This way we can verify if there's any more work needed beyond `escape_string_warning` and `bytea_output`.

**Comment by ikzelf** [comment]
https://www.zabbix.com
I downloaded the sources and checked src/lib/zbxdb/db.c for settings done while connecting and I listed the ones I found. Currently compiling with some little hacks.

**Comment by ikzelf** [comment]
@knz I ignored the errors and now:
```
 32588:20180222:172008.329 [Z3005] query failed: [0] PGRES_FATAL_ERROR:ERROR:  unknown variable: "escape_string_warning"
 [set escape_string_warning to off]
 32588:20180222:172008.329 query [txnlev:0] [show standard_conforming_strings]
 32588:20180222:172008.329 query without transaction detected
 32588:20180222:172008.329 query [txnlev:0] [set bytea_output=escape]
 32588:20180222:172008.330 [Z3005] query failed: [0] PGRES_FATAL_ERROR:ERROR:  unknown variable: "bytea_output"
 [set bytea_output=escape]
 32588:20180222:172008.330 End of DBconnect():0
 32588:20180222:172008.330 query [txnlev:0] [select 1 from information_schema.tables where table_name='dbversion' and table_schema='public']
 32588:20180222:172008.438 DBcheck_version() "**dbversion**" does not exist
 32588:20180222:172008.438 query [txnlev:0] [select 1 from information_schema.columns where table_name='config' and column_name='server_check_interval' and table_schema='public']
 32588:20180222:172008.478 Cannot upgrade database: the database must correspond to version 2.0 or later. Exiting ...
 32588:20180222:172008.478 End of DBcheck_version():FAIL
```
It looks like it is also looking for a real dbversion check. I can imagine this .....
So close to having this run.

**Comment by knz** [comment]
The version check is something we can also add compatibility for. Thank you for spotting it.

If you can collect this query data with a real pg server that will be helpful.

**Comment by knz** [comment]
cc @awoods187 for tracking

**Comment by ikzelf** [comment]
@knz also missing is the ability to set the current schema. I now have the app running by changing the code. If we could issue '`set schema X`' it again is more postgres compatible.

**Comment by knz** [comment]
`set schema` will be supported in 2.0

**Comment by ikzelf** [comment]
# Server version: CockroachDB CCL v2.0-beta.20180312 (darwin amd64, built 2018/03/12 17:47:59, go1.10) (same version as client)
# Cluster ID: c4257215-3ccf-43d7-842e-c75cb89eed18
#
# Enter \? for a brief introduction.
#
root@:26257/zabbix> set schema zabbix;
SET

Time: 274.24Âµs

this seems to be working.
Thanks!

**Comment by syepes** [comment]
@ikzelf I have seen that your trying to use CDB for zabbix, have you managed to make it work OOTB? 
I am getting errors when trying to create the db schema.sql

**Comment by ikzelf** [comment]
Yes, I have the server running. Not the web part yet. You need crdb v2 and foreign keys need to be indexed.

Groeten,
Ronald Rood

**Comment by syepes** [comment]
@ikzelf Nice!

Would it be possible to talk about these Zabbix related topics out of this thread?

I have also been doing some testing with TimeScaleDB and it could be great to get your insights on CDB + Zabbix.

**Comment by ikzelf** [comment]
Sure, dm @ik_zelf on Twitter.

Groeten,
Ronald Rood

**Comment by gnuowned** [comment]
Hi, any follow up on this?

**Comment by knz** [comment]
There is work ongoing to reduce the compatibility friction across a wide range of tools, not just Zabbix. Expect progress in CockroachDB v2.1.

**Comment by jordanlewis** [comment]
This might work now - anyone want to try again? :) I'll close this for now, feel free to comment or re-open if you find issues after testing again.
