### ISSUE TITLE
ui: databases page never updates table details

### ISSUE THREAD

**Issue by couchand** [cockroachdb/cockroach#22944]
From a cursory review of the code, it looks like the databases page will never update the data shown in the tables table.  This would seem to introduce a potential for user confusion, if they're expecting things to update after schema changes, for instance.

We should probably investigate this, and make sure that we're showing up-to-date stats on databases and tables.

This seems to be the likely culprit of some of the strange behavior witnessed on #21109.

This may get wrapped up in the fix for #22941, but documenting it here as a separate concern.

**Comment by vilterp** [comment]
Do you mean it doesn't autorefresh, or it doesn't update even if I reload the page?
