### ISSUE TITLE
ui: databases page makes too many requests to fetch data

### ISSUE THREAD

**Issue by couchand** [cockroachdb/cockroach#22941]
The databases page makes a ton of requests for fine-grained data: one to get a list of all the databases, _one per database_, then **two per table**, all of them spammed out at once on page load.  This isn't really getting a lot of data, and we always want to load all of it.  The overhead of individual requests is pretty significant in this case.

We should introduce an endpoint that just returns the info for all databases and their tables in one shot.

Jira issue: CRDB-5833

**Comment by jordanlewis** [comment]
Hi @celiala and @dhartunian, we're doing some re-triage of old issues and this one came up. Is it still a thing? Specifically, #31421 was theorized to be caused by lots of tables or databases slowing down the admin UI. I'm going to close that one, but just wanted to re-raise this in your consciousnesses to check on it!

**Comment by dhartunian** [comment]
This is still a thing and blocked some UI updates from being possible for 20.1

In particular, db-level stats are computed by pulling down all tables and doing client-side computation. I'd love for that to be done by the DB if possible.

I was also hoping to introduce pagination to the table listings.

**Comment by vy-ton** [comment]
A user experienced this on a [Forum](issue) and @ajwerner mentioned this came up recently with another customer as well.

**Comment by tbg** [comment]
This came up on a support call the other day as well. Paraphrasing the customer: "oh, the database page never works. <shows me the browser debug tools> look it's making hundreds of requests and then times out".

**Comment by dhartunian** [comment]
We have a short-term fix for this here that's been backported to 20.2 https://github.com/cockroachdb/cockroach/pull/55559

**Comment by tbg** [comment]
Nice, the customer is on 20.1 but it's nice to hear that they'll get a
better experience once they upgrade. Thanks for the heads up!

**Comment by dhartunian** [comment]
Would a 20.1 backport make an impact here? I know it was cherry-picked for a custom build on 20.1 but that was a one-off.

**Comment by tbg** [comment]
No, for that customer I don't think so, they were mostly pointing out that problem because we ran into it, not because they were particularly bothered by it. That said - they wouldn't complain for sure.
