### ISSUE TITLE
ui: health pings seem unnecessary

### ISSUE THREAD

**Issue by couchand** [cockroachdb/cockroach#22943]
We're constantly pinging the server for health checks.  This doesn't really seem to add much value, since we'll find out about network concerns when we make the inevitable data requests, and it makes debugging more difficult because the network tab and the redux actions get spammy with health checks.

We might take care of this in the course of fixing #20499, but I'm making this issue to document the concern, in case we end up going another route over there.

**Comment by vilterp** [comment]
I think if the connection is truly lost (e.g. if the node goes down), having an alert like we do now is better UX than seeing spinners forever the next time you try to load some data. Are you proposing bubbling HTTP errors up to something which would show sed popup? Sounds hard.

Aside from the annoying Redux errors, I actually think the pings are a decent solution. (i.e. I can't think of a better one)

**Comment by couchand** [comment]
I don't think it would be any harder to show an error when a real data request comes back in error than it is to show the error for the health ping -- isn't it exactly the same logic?

Perhaps it would make sense to ping if the user hasn't requested data recently, but that almost never actually happens, as most pages are constantly updating.

**Comment by couchand** [comment]
Yes, I would expect that a new reducer would watch for errors on any network call and respond accordingly.

**Comment by piyush-singh** [comment]
Since we've already made some copy changes partially addressing #20499 and it seems unlikely that we'll address this in 2.1, moving this to Later for now.
