### ISSUE TITLE
migrations: "failed to run migration" when upgrading 1.0 to 1.1 to 2.0

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#22955]
I have some ancient 1.0 store dumps (starting with the 1node-17gb-841ranges allocator test) that I'm trying to upgrade to 2.0. I tried starting up using 1.1.5, running `SET CLUSTER SETTING version = '1.1'`, shutting everything down, and starting up using 2.0. The 2.0 binary panics with the following

```failed to run migration "grant superuser privileges on all objects to the admin role": table "namespace" is encoded using using version 1, but this client only supports version 2 and 3```

Am I doing something wrong?

Dunno who's the most up to date on this. cc @benesch @a-robinson @nvanbenschoten ?

**Comment by a-robinson** [comment]
calling @mberhault

**Comment by benesch** [comment]
I suspect that this is not a problem with the migration but a missing call to TableDescriptor.MaybeUpgradeVersion.

**Comment by benesch** [comment]
And I'll bet it was introduced by Raphael's pgcompat change.

**Comment by benesch** [comment]
Oh, no, looks like a problem with the migration itself.

**Comment by danhhz** [comment]
Validated that adding a `MaybeUpgradeFormatVersion` fixes the problem. I'll PR it

**Comment by danhhz** [comment]
Fixed by #22962
