### ISSUE TITLE
importccl: IMPORT transform blocked on write

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#22973]
An import with transform to google cloud has been stalled at the same percent for many hours. The stack dump suggests it is blocked on a write to GCS.

[goroutine.txt](https://github.com/cockroachdb/cockroach/files/1749656/goroutine.txt)

**Comment by mjibson** [comment]
IMPORT TABLE ""."".history (h_c_id INTEGER, h_c_d_id INTEGER, h_c_w_id INTEGER, h_d_id INTEGER, h_w_id INTEGER, h_date TIMESTAMP, h_amount DECIMAL(6,2), h_data VARCHAR(24), INDEX (h_w_id, h_d_id), INDEX (h_c_w_id, h_c_d_id, h_c_id)) CSV DATA ('http://localhost:8081/csv/tpcc/history', 'http://localhost:8081/csv/tpcc/history', 'http://localhost:8081/csv/tpcc/history', 'http://localhost:8081/csv/tpcc/history', 'http://localhost:8081/csv/tpcc/history', 'http://localhost:8081/csv/tpcc/history', 'http://localhost:8081/csv/tpcc/history', 'http://localhost:8081/csv/tpcc/history', 'http://localhost:8081/csv/tpcc/history', 'http://localhost:8081/csv/tpcc/history', 'http://localhost:8081/csv/tpcc/history', 'http://localhost:8081/csv/tpcc/history', 'http://localhost:8081/csv/tpcc/history', 'http://localhost:8081/csv/tpcc/history', 'http://localhost:8081/csv/tpcc/history', 'http://localhost:8081/csv/tpcc/history', 'http://localhost:8081/csv/tpcc/history', 'http://localhost:8081/csv/tpcc/history', 'http://localhost:8081/csv/tpcc/history', 'http://localhost:8081/csv/tpcc/history', 'http://localhost:8081/csv/tpcc/history', 'http://localhost:8081/csv/tpcc/history') WITH "nullif" = 'NULL', transform = 'gs://cockroachdb-backup-testing/teamcity-530934-import-tpcc-warehouses-1000-nodes-4/tpcc/version=1.0.0,interleaved=false,now=2006-01-02%252015:04:05,seed=1,warehouses=1000/history'

**Comment by bobvawter** [comment]
@mjibson Here's what I've found so far doing a code-dive:

* The GCS `Writer.open()` method is trying to make a remote call to set up a resumable upload and, presumably, is receiving retryable errors, given that `gax.Sleep` is on-stack.
* The `runWithRetry()` that `open()` calls looks like it would respect any deadline or cancellation in the `Context` passed into `gcsStorage.WriteFile()`

When I trace back where all of this code is getting called from, it looks like it's being invoked by the job registry. Taking a look at [`registry.go: makeCtx()`](https://github.com/cockroachdb/cockroach/blob/47cb9bff9978b9a08446805ae12c2f3466f584d0/pkg/sql/jobs/registry.go#L113),  I don't see (or have just plain missed) any code that suggests that the job registry supports setting deadlines on the context ultimately passed into `Resumer.Resume()`

**Comment by mjibson** [comment]
If we want to put a deadline on a context, we can make a new context. For example, in https://github.com/cockroachdb/cockroach/blob/b6c934ccee6293b697dff5880cf364c2370bf758/pkg/ccl/storageccl/export_storage.go#L624 we could add `ctx, _ = context.WithDeadline(ctx, time.Minute * 10)` to limit the write to 10 minutes.

**Comment by mjibson** [comment]
FYI, we've been adding timeouts and retries at the lowest level so far, instead of high up the stack. This is a whack-a-mole approach when we find these network issues, but it's worked well so far.

**Comment by bobvawter** [comment]
How does a PR sound that would update all implementations of `ExportStorage` with timeouts on the methods that are going to talk to remote services?  I'm thinking a half hour would be a reasonable timeout choice in case the user has very large files.

**Comment by mjibson** [comment]
I don't know what's best in this case. It might make sense to just do GCS here because we've observed that bug. It might make sense to do what you propose because it seems like most of the Go APIs for those external services support context cancellations. It might be best to use context timeouts at a layer higher than export storage (i.e., putting the timeouts in the backup/import/restore code).

But yes, I like your suggestion. Let's try that first.

**Comment by bobvawter** [comment]
Multi-hour reads are a thing, so we want to only protect the write path for 2.0.
