### ISSUE TITLE
RevScan [x,KeyMax) range descriptor lookup

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#2298]
I think when scanning a key range like the above in reverse order, we can run into the error
```go
return NewInvalidRangeMetaKeyError("body of meta2 range lookup is >= KeyMax", key)
```

in `ValidateRangeMetaKey`.
Logged here for investigation and writing a test.

**Comment by tschottdorf** [comment]
@thundercw please correct me if I'm wrong.

**Comment by thundercw** [comment]
@tschottdorf  You are right. I wrote a test in cli_test.go for it.
```
func Example_revscan() {
	c := newCLITest()
	c.Run("kv put a 1 b 2 c 3 d 4")
	c.Run("range split c")
	c.Run("kv revscan a \xff\xff")
	c.Run("quit")

	// Output:
	// kv put a 1 b 2 c 3 d 4
	// range split c
	// kv revscan a \xff\xff
	// "d"	"4"
	// "c"	"3"
	// "b"	"2"
	// 3 result(s)
	// quit
	// node drained and shutdown: ok
}

Error: reverse scan failed: "\x00\x00meta2\xff\xff" is not valid range metadata key: body of meta2 range lookup is >= KeyMax
```

Why do we need to add this constraint? I think if want to deal with boundary of Scan in RangeLookup ,we can handle it like `Meta1KeyMax` in `MetaScanBounds` .
```
	if key.Equal(Meta2KeyMax) {
		// Special case Meta2KeyMax: this is the last key in Meta2, we don't want
		// to start at Next().
		return key, Meta2Prefix.PrefixEnd()
	}
```
Is my understanding right？

**Comment by tschottdorf** [comment]
I'm assuming this check simply predates reverse operations: If you're looking for `\meta2\xff\xff` in a forward request, it means you're starting your scan (or whatever) at `\xff\xff`, and this is invalid (
But with reverse, that can actually happen (since the "start" key is the end, and it's exclusive).
So if `ValidateRangeMetaKey` also got a `reverse` flag it would be able to accept it in that case. But `ReverseMetaScanBounds` already returns an error, so probably better to have `MetaScanBounds` return an error as well, and then it can run only those checks which are relevant to it (and `ValidateRangeMetaKey` can run the common checks, but is only called from each of the ScanBounds functions and can become unexported).

**Comment by thundercw** [comment]
OK ,I will try to fix this problem according to your suggestion .

**Comment by tschottdorf** [comment]
Thanks chengwei, your help is appreciated.
