### ISSUE TITLE
sql: not possible to filter string[] column with {is, is not} null

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#22996]
```
root@:26257/t> select * from pg_catalog.pg_proc where proargmodes is not null limit 5;
pq: unsupported comparison operator: <string[]> IS DISTINCT FROM <NULL>
```
In the above example, `proargmodes` is a column in `pg_catalog.pg_proc` of type `string[]`. It has a default value of `NULL`, so it's clearly possible for it to have a null value.  It should be possible to check this in a query.

**Comment by RaduBerinde** [comment]
CC @andy-kimball This is the type inference code.

**Comment by andy-kimball** [comment]
I don't think this is related to any opt code; something broke in the main SQL code path. It repros even when EXPERIMENTAL_OPT = OFF. The type inference code for this operator is trivial - it just returns Bool for this expression, so NULL inputs are fine.

**Comment by RaduBerinde** [comment]
Ah. This must be specific to arrays, @justinj can you take a look?

**Comment by justinj** [comment]
Thanks for catching!
