### ISSUE TITLE
increased 99th percentile latency over a few day period

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#22999]
https://cockroach-omega-0001.crdb.io:8080/#/metrics/overview/cluster

The 99 percentile latency on this cluster grew from about 169ms to 367ms over the course of 2 days.

**Comment by mrtracy** [comment]
Don't really have much insight into why this would happen, but the jumps in latency correspond exactly with increases in the number of replicas:

<img width="983" alt="screen shot 2018-02-23 at 2 01 19 pm" src="https://user-images.githubusercontent.com/6969858/36611661-36dee3ee-18a2-11e8-8759-f0758426cfb7.png">
<img width="984" alt="screen shot 2018-02-23 at 2 01 30 pm" src="https://user-images.githubusercontent.com/6969858/36611662-36ec5d08-18a2-11e8-8e88-d0f1f934da9f.png">

**Comment by jordanlewis** [comment]
@vivekmenezes this issue isn't particularly actionable. What outcome do you wish to see in the 2.0 timeframe?

**Comment by vivekmenezes** [comment]
Looks like after it rose initially it remained flat over a week, so I suppose there is nothing to be done here. I'm going to close this issue.
