### ISSUE TITLE
qa: expressive zone config

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#23018]
QA the expressive zone config as implemented in this PR:
https://github.com/cockroachdb/cockroach/pull/22819

**Comment by a-robinson** [comment]
Any estimate on when this will happen?

**Comment by benesch** [comment]
I did an initial round of testing last Friday and didn't find anything. I'm
going to take a more principled approach now that leaseholder preferences
have landed. Probably today.

**Comment by benesch** [comment]
Here's a summary of what I've done. I'v validated that the new constraint syntax doesn't have any obvious bugs. Each of these constraints either roundtrips or produces the error I expect.

```
constraints: [+1, +2, +3]

constraints: [-a=b, -c=d]

constraints:
  "+a=b": 2
  "+b=c": 1
  
constraints: {"+a=b": 2, "+b=c": 1}

constraints: {"+a=b": 2, "+b": 1}

constraints: {"+a=b": 2, "-b=c": 1}
Error: pq: could not validate zone config: only required constraints (prefixed with a '+') can be applied to a subset of replicas

constraints: {"+a=b": 2, "+b=c": 29}
num_replicas: 30
Error: pq: could not validate zone config: the number of replicas specified in constraints (31) cannot be greater than the number of replicas configured for the zone (30)

constraints: {"+a=b": 2, "+b=c": 29, "+c=d": -1}
num_replicas: 30
Error: pq: could not validate zone config: constraints must apply to at least one replica

constraints: {"+a=b": 2, "+b=c": 29, "+c=d": 0}
num_replicas: 30
Error: pq: could not validate zone config: constraints must apply to at least one replica

constraints: {"+a=b,-b=c,+d=f": 0}
```

Then I created a nine node cluster with 300 ranges and moved them around a bunch.

```
roachprod create benesch-test -n9
roachprod start benesch-test --racks 9 --sequential
```

```

CREATE DATABASE d;
USE d;
CREATE TABLE t1 (a INT);
CREATE TABLE t2 (a INT);
CREATE TABLE t3 (a INT);

ALTER TABLE t1 SPLIT AT SELECT generate_series(1, 100);
ALTER TABLE t2 SPLIT AT SELECT generate_series(1, 100);
ALTER TABLE t3 SPLIT AT SELECT generate_series(1, 100);

Various combinations of 
ALTER TABLE t1 EXPERIMENTAL CONFIGURE ZONE 'constraints: {"+rack=0:1"}';
```

The cluster stayed balanced as long as I only applied constraints to one of the three tables (17:30-17:42). I verified with `SHOW TESTING RANGES` that the replicas were placed in compliance with the constraints. Then I verified that I could force all ranges onto just three nodes (17:42). Unconstraining one table allowed the cluster to regain a bit of balance (17:46). 

![screenshot 2018-03-20 13 46 40](https://user-images.githubusercontent.com/882976/37674919-4d20c4ae-2c4a-11e8-8b30-e0f5ea827797.png)

Then I applied a much more complicated set of constraints and the cluster managed to balance while satisfying all constraints without a hitch:

```

a: 1/2/3
b: 4/5/6
c: 7/8/9

n: 1/4/7
e: 2/5/8
s: 3/6/9

one: 1/5/9
two: 2/6/7
thr: 4/8/3

roachprod start benesch-test:1 --args=--locality=letter=a,cardinal=n,num=one
roachprod start benesch-test:2 --args=--locality=letter=a,cardinal=e,num=two
roachprod start benesch-test:3 --args=--locality=letter=a,cardinal=s,num=thr
roachprod start benesch-test:4 --args=--locality=letter=b,cardinal=n,num=thr
roachprod start benesch-test:5 --args=--locality=letter=b,cardinal=e,num=one
roachprod start benesch-test:6 --args=--locality=letter=b,cardinal=s,num=two
roachprod start benesch-test:7 --args=--locality=letter=c,cardinal=n,num=two
roachprod start benesch-test:8 --args=--locality=letter=c,cardinal=e,num=thr
roachprod start benesch-test:9 --args=--locality=letter=c,cardinal=s,num=one

ALTER TABLE t1 EXPERIMENTAL CONFIGURE ZONE 'constraints: {"+letter=a:1": 1, "+cardinal=n": 1, "+num=one": 1}';
ALTER TABLE t2 EXPERIMENTAL CONFIGURE ZONE 'constraints: {"+letter=b:1": 1, "+cardinal=e": 1, "+num=two": 1}';
ALTER TABLE t3 EXPERIMENTAL CONFIGURE ZONE 'constraints: {"+letter=c:1": 1, "+cardinal=s": 1, "+num=thr": 1}';
```

@a-robinson, are there obvious gaps in my testing?

**Comment by a-robinson** [comment]
It doesn't cover everything, but I don't know that QA buddying is meant to be exhaustive. That's what the automated tests I wrote are for.

The main thing it didn't cover that may be worth covering is how it behaves when nodes stop running or are declared dead, and then when they come back from the dead. I seriously doubt there would be any surprises, but that's an important part of the allocator's behavior.

**Comment by knz** [comment]
The initial QA was completed, and user feedback was received since. Closing the QA issue.
