### ISSUE TITLE
hello I would like to collaborate with your project by serving as a translator to Spanish which is my native language could translate the readme and contribute

### ISSUE THREAD

**Issue by UlisesTJ** [cockroachdb/cockroach#23038]
Is this a question, feature request, or bug report?

**QUESTION**

Have you checked our documentation at https://cockroachlabs.com/docs/stable/? If you could not find an answer there, please consider asking your question in our community forum at https://forum.cockroachlabs.com/, as it would benefit other members of our community.

Prefer live chat? Message our engineers on our Gitter channel at https://gitter.im/cockroachdb/cockroach.

**FEATURE REQUEST**

1. Does an issue already exist addressing this request? If yes, please add a :+1: reaction to the existing issue. If not, move on to step 2.

2. Please describe the feature you are requesting, as well as your proposed use case for this feature.

3. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

**BUG REPORT**

1. Please supply the header (i.e. the first few lines) of your most recent
   log file **for each node in your cluster**. On most unix-based systems
   running with defaults, this boils down to the output of

     grep -F '[config]' cockroach-data/logs/cockroach.log

   When log files are not available, supply the output of `cockroach version`
   and all flags/environment variables passed to `cockroach start` instead.

2. Please describe the issue you observed:

- What did you do?

- What did you expect to see?

- What did you see instead?

**Comment by knz** [comment]
Dear @UlisesTJ,
I see you are creating this kind of issue on many projects on Github.
Your effort to find an an opportunity to contribute to an open source project is laudable!

Unfortunately this is not how github, and open source projects in general, work. 

As a previous contributor of translations myself, I have some friendly advice for you. 

There are four scenarios:

|   | You want to volunteer your time and effort for free | You want to get paid |
|---|-----|------|
| Software has a translation project already | Simply contribute | Get in touch with the organizers |
| Software does not have a translation project | Start the project | It's very hard, see below |

If the open source project is not yet accepting translations, there is virtually zero chance for you to find a way to get paid for translations. Get in touch with the project maintainers and ask them if their funding includes support for translations. If they don't reply, take that as a no. If there's no funding for translations yet, ask them to keep your name on file so they can contact you later.

Also please remark how the 4 scenarios above do not include "create an issue on github to ask about translations". I personally think that creating an issue on github is not the optimal way to get in touch with the right people. Most open source projects have a mailing list or a discussion forum; this is the place where you should engage that conversation.

In the case of CockroachDB, we do not yet have a translation project. If you want to contribute for free, feel free to create your own translation project and show us the result. For paid contributions, I fear we are not taking paid translations at this time.

**Comment by knz** [comment]
I will close this issue, since we cannot follow up on this on Github. Feel free to follow up this conversation on the forum.
