### ISSUE TITLE
system.descriptor column `desc` is a reserved keyword.

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#2304]
Which means that we can't query it specifically:
```
fishmonger:8080> show columns from system.descriptor;
+-------+-------+------+
| Field | Type  | Null |
+-------+-------+------+
| id    | INT   | true |
| desc  | BYTES | true |
+-------+-------+------+
fishmonger:8080> select id from system.descriptor;
+----+
| id |
+----+
| 1  |
| 2  |
| 3  |
| 4  |
+----+
fishmonger:8080> select desc from system.descriptor;
query error: syntax error at or near "desc"
select desc from system.descriptor;
       ^
```

We could either change the name (eg: `descriptor`), change the grammar to allow reserved keywords (might be tricky), or change `desc` to not be a reserved keyword (might also be tricky).

**Comment by petermattis** [comment]
Probably should change the name of the field. Note that you can do `SELECT "desc" FROM system.descriptor` to use a reserved keyword as a column name.

**Comment by mberhault** [comment]
Yeah, rename might be best. I'll also remove the quotes around names in the `CREATE TABLE` statements to make sure we catch those. I have no problem with reserved keywords in general, but using one be default just makes life tricky.
