### ISSUE TITLE
pkg/ui/src/util/vector.ts is CCL-licensed

### ISSUE THREAD

**Issue by srh** [cockroachdb/cockroach#23058]
As of commit aa88086248c26cd8db49675a873f3a0d4495f85c.

It looks like pkg/ui/src/util/locations.ts uses the file, and pkg/ui/src/views/reports/containers/localities/index.tsx uses util/locations, and I guess it might in fact contaminate a buildoss build, I haven't followed the chain further than that.

Edit:

For example after `make buildoss` you get this line in a build output file...
pkg/ui/distoss/bundle.js
28070:// Licensed under the Cockroach Community Licence (the "License");

**Comment by knz** [comment]
cc @bdarnell @cockroachdb/admin-ui

**Comment by bdarnell** [comment]
Thanks for the report. This looks like a mistake; the license should have been changed when the file was moved out of the CCL directory in #22303.

**Comment by couchand** [comment]
@srh thanks for catching that!
