### ISSUE TITLE
sql: turn the vtable constructors into generators

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#23052]
This is an alternate strategy from #22504, which will solve the same problem and then some more.

the proposal here is to flip the interface used to construct the vtable contents from its current from (loop to populate a row container, then use the row container) into proper generators (vtables produce their contents in a streaming fashion).

This would make any filter downstream of a vtable generator do its job properly (hence solving the problem that motivated #22504), and also avoid bloating RAM for vtables that legitimately produce lots of data, as motivated in the discussion on #22344.

cc @jordanlewis @nvanbenschoten @vilterp

**Comment by jordanlewis** [comment]
Flagging this as a potential intern project.
