### ISSUE TITLE
Can I replace traditional SQL database with CockroachDB? also Entity Framework support

### ISSUE THREAD

**Issue by enemyofthedawn** [cockroachdb/cockroach#23060]
I'm new to NewSQL databases. I've been using relational databases my entire life. Is that true NewSQL databases like CockroachDB provide the best of both worlds and I can replace both NoSQL and SQL with it?

https://www.cockroachlabs.com/docs/stable/frequently-asked-questions.html#can-a-postgresql-or-mysql-application-be-migrated-to-cockroachdb

> Yes, although CockroachDB is unlikely to be a drop-in replacement at this time. 

What would be the answer if I'm creating completely new application and I want to use CockroachDB?

I'm primarly using C# and ASP.NET Core with Entity Framework Core **Code First**. I heard it's possible to use Npgsql and use it with Entity Framework Core. Is this production ready?

- Can I accomplish things like many-to-many relations? 
- Are there any benchmarks comparing CockroachDB with MySQL and PostgreSQL?

**Comment by knz** [comment]
Dear @enemyofthedawn 

thanks for your interest in CockroachDB!

- We have some preliminary tests with Npgsql and it appears to work fine with CockroachDB. Why don't you try it out?

- There are probably many benchmarks comparing CockroachDB to other things. We even intend to publish some of our own performance measurements on the company blog before the summer. If you run your own benchmarks, or if you try to find existing benchmark results online, be sure that they do not compare apples with oranges: the default configuration of CockroachDB provides better safety and correctness than the default configuration of MySQL and PostgreSQL, but that comes at a slight performance cost.

Does this answer your questions?
