### ISSUE TITLE
sql: test current reg cluster/unimplemented errors to ensure that the current process works as expected

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#23079]
Setup a cluster and look at the actual reg data to ensure it reports its attributes correctly

**Comment by awoods187** [comment]
I was able with (DT's help) to review unimplemented features.

And we need to do end to end testing for current fields plus new fields.

**Comment by dt** [comment]
Latest point release fixed this, right @awoods187 ? does the data you're seeing now look right?

**Comment by awoods187** [comment]
It does appear to be working but it would be nice to make sure we were 100% confident via a test
