### ISSUE TITLE
perf: YCSB Benchmark

### ISSUE THREAD

**Issue by mrtracy** [cockroachdb/cockroach#2309]
The [Yahoo Cloud Serving Benchmark](https://github.com/brianfrankcooper/YCSB) was created to provide a comparison between NoSQL databases.  It can run against an arbitrary data store, as long as their standard "client" interface is implemented for that database.

Assuming it can be set up with reasonably little effort, this benchmark might be a fairly high-reward source of workload when we start looking towards performance tuning; especially because we will be able to compare performance against some established competitors. 

As a non-transactional workload it will not exercise many of Cockroach's valuable features, but it may help identify areas for performance improvement when handling more basic workloads.

**Comment by tschottdorf** [comment]
I like the idea of testing against some "established" benchmarks but at the end of the day I think the major value in that is to be able to gauge (and sell) where we are compared to others out there.
For performance-tuning purposes, at least for now, I think what we need are very specific benchmarks which work their way up the stack (for example, it makes exactly zero sense to run transactional SQL benchmarks right now). Just getting the hot path on a single put as fast as can be is a good step, then the same for some other ops with varying sizes on a single range, then moving on to single-range Txns (which should optimize away, so hopefully easy), and when we've done the same game for specific workloads which target a small number of ranges, I would consider looking at bottlenecks highlighted by YCSB or others. So while I like the idea, there are a couple of (large) baby steps before that.

**Comment by bdarnell** [comment]
This looks like as good a place as any to track benchmarks we may want to run. Here's one from facebook based on their social graph: https://github.com/facebook/linkbench

**Comment by petermattis** [comment]
It is possible that CockroachDB would work with https://github.com/brianfrankcooper/YCSB/tree/master/jdbc and the Postgres JDBC driver.

**Comment by spencerkimball** [comment]
https://github.com/cockroachdb/loadgen/pull/8
