### ISSUE TITLE
ui: node liveness is off when adding a new node, and when a node is suspect

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#23099]
Perhaps some of this behavior is expected, but humor me. 

I'm currently testing how the cluster viz behaves when adding, decommissioning, and killing nodes. I created a new node, and instead of coming up as a new node, it is marked as dead.

![image](https://user-images.githubusercontent.com/5768024/36689821-8d83d372-1afe-11e8-8854-e4cd49c39543.png)

That is odd, since the time series of that node shows that it's alive: 

![image](https://user-images.githubusercontent.com/5768024/36689843-9e517e84-1afe-11e8-85f2-7a4f942a3904.png)

The even odder thing is that the node liveness graph is off - it is removing the suspect node as well.

![image](https://user-images.githubusercontent.com/5768024/36689874-b86b44ee-1afe-11e8-82bc-cacf00efe2c1.png)

![image](https://user-images.githubusercontent.com/5768024/36689878-bcda11c2-1afe-11e8-92a6-b2d8962fbb22.png)

**Comment by dianasaur323** [comment]
Also, why does a dead node still have uptime?

![image](https://user-images.githubusercontent.com/5768024/36689949-df5cd356-1afe-11e8-9f9a-2e1d77bd9942.png)

**Comment by vilterp** [comment]
Second issue filed as #23250

**Comment by vilterp** [comment]
Can't repro the "new node comes up as dead" issue; new nodes come up green. Not sure why the suspect node isn't in the graph; seems like a separate issue. Gonna close this for now; we can reopen or file separate issues if we see more stuff like this.

**Comment by dianasaur323** [comment]
it's possible that the node itself never really successfully became alive, since that cluster has been having issues anyway. thanks for closing!
