### ISSUE TITLE
sql: make NULL an inhabitant of every type

### ISSUE THREAD

**Issue by andy-kimball** [cockroachdb/cockroach#23101]
This will help solve problems like this:

```
select pg_typeof(1=null);
```

EXPECTED: Same result as Postgres: `boolean`
ACTUAL: Cockroach returns `NULL`

**Comment by justinj** [comment]
cc @knz

**Comment by knz** [comment]
cc @nvanbenschoten 

The _result_ of a comparison with NULL should be NULL, while its _type_ should stay BOOL.

The problem we have here is that once type checking simplifies an expression to NULL, it cannot attach any other type to it than Unknown.

**Comment by petermattis** [comment]
The phrasing of this issue title is a bit weird to me. My current conception of NULL is that it is an attribute of the value and not of the type. I suppose this is why Postgres has the Unknown type to represent the type of a NULL constant. Related: for columnarized storage and evaluation, NULL is often represented as a bitmap that is parallel to the column values. The column has a concrete (known) type and, if the column is NULL-able, we pass along a bit per value indicating whether it is NULL.

**Comment by knz** [comment]
yes null is "an attribute of the value and not of the type" indeed, although CockroachDB (currently) gets this wrong.

The phrasing "an attribute of the value" is also technically incorrect: NULL _is_ a valid _value_, which extends the set of all possible values of the underlying type.

It's similar as floats in other programming languages. Intuition has it that a finite type that represents "numbers" should have a set of possible values between [minval, maxval] and yet the domain for floats is [minval, maxval] ∪ {-∞, +∞, -0, NaN}.

The correct way to think about this is thus that for every "programming" type T with range R, the SQL equivalent of T has range R ∪ {NULL}.

Also FYI in PL theory it's said "X is an inhabitant of type T" to mean "the set of all possible values for type T contains value X". See https://duckduckgo.com/?q=value+inhabits+type.

**Comment by knz** [comment]
Whether we implement "NULL is an inhabitant of every type" using a bitmap alongside the value (recommended) or with a separate Go object (current code, horrendous for performance) is an implementation detail.
