### ISSUE TITLE
roachtest: test store dir backward compatibility

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#23107]
In https://github.com/cockroachdb/cockroach/pull/23030#issuecomment-368249963, the allocator tests were migrated to roachtest. They use backups now, but used to use store dumps and had caught a couple regressions in store directory backward compatibility:

> We have gotten some infrequent value out of reusing a store directory as a test of backwards compatibility, e.g. #18817 found an inconsistency caused by a protocol buffer change and #9029 found an issue with a rocksdb version bump.

We should replace this coverage with a more targeted test.

I can see this working one of a few different ways. We could download a store dump snapshot like the old tests used to and start up a binary. Another idea is to download an old binary, use it to create data, and migrate it through some versions. Does anyone have an opinion on how this should work? @a-robinson @tschottdorf @petermattis ?

**Comment by danhhz** [comment]
@bobvawter, peter suggested that you could pick this off. I'm happy to help with any roachtest questions, but I don't have a lot of context for the details of what this would look like, I suggest you ping @nvanbenschoten or @tschottdorf for that

**Comment by bobvawter** [comment]
Questions:
* If we go the route of using dumps from previous versions, do we support loading a 1.0 dump into 2.0?
* Are the dumps platform-independent?  If I fire up a 1.X binary on my mac to create the test data, will that load into a 2.0 build running on CI?
* Are there specific features that need to exist in the test schema (e.g. secondary indices) to make this test reasonably robust?
* Is there an existing tool to create a generic dataset for testing?

**Comment by danhhz** [comment]
Excellent questions. @tschottdorf has thought about this much more than I have, so definitely get ahold of him if you can and get his opinions before you commit to anything.

> If we go the route of using dumps from previous versions, do we support loading a 1.0 dump into 2.0?

You have to go through each "minor" version. So you start a 2.0 binary on 1.0 data, you need to (briefly) start up a 1.1 binary on it first. At startup, crdb runs some data migrations, so IIUC by the time the `cockroach start` command finishes, the necessary migrations are finished and you can immediately shut it back down and move on to 2.0.

> Are the dumps platform-independent? If I fire up a 1.X binary on my mac to create the test data, will that load into a 2.0 build running on CI?

No idea, but I doubt it. @bdarnell ?

> Is there an existing tool to create a generic dataset for testing?

The `workload` tool does this. Others might have a better opinion on this, but I'd suggest starting with `tpcc --warehouses=1`. Something like `workload init tpcc --warehouses=1` will load some data for you (if you end up needing larger datasets, use the `workload fixtures` stuff instead of `init)

> Are there specific features that need to exist in the test schema (e.g. secondary indices) to make this test reasonably robust?

I'd start with running `workload run tpcc --duration=<something>`. This exercises enough of the system to get started.

**Comment by bdarnell** [comment]
> Are the dumps platform-independent? If I fire up a 1.X binary on my mac to create the test data, will that load into a 2.0 build running on CI?

I don't know of anything that would be platform-dependent, so I would expect this to work. (at least as well as moving between machines of the same platform). Note that we don't properly support moving data directories around, even though it may work in some cases. I think there's a current bug in which we may persist absolute paths so you can't even move it to a different location on the same machine. 

Copying store dirs around is generally a good way to get into trouble - the reincarnated store will try to talk to its old peers (and may succeed, if they're also running with the same cluster id). It's unsafe to allow a store to move back in time (i.e. to restore it from an old snapshot once a peer has observed newer state from that node). What's the goal of this issue? Is this something we want to provide better support for? I'm not sure it's worth the effort to support this as a general feature, although it might be feasible for the specific case of getting data into roachtest clusters.

**Comment by danhhz** [comment]
This issue is ultimately about a test to prevent on-disk backward compatibility regressions. We shouldn't need to move the store dir around to a different node or path to do this.

I'm imagining something like start up an old binary, write some data, run some load, shut it down, start it up with a newer binary, run some load and/or integrity checks to verify that everything works.

**Comment by bobvawter** [comment]
@danhhz Does this test in roachprod already basically take care of this scenario?

https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/version.go

It looks like it installs a `1.1.5` cluster and then drops in the version under test.  Would extracting this into a multi-version loop take care of what you want to do?

**Comment by benesch** [comment]
Yeah, let's close this issue out. I think we're better covered by the version upgrade test than we ever were by the allocator tests.
