### ISSUE TITLE
ui: remove decommissioned nodes from dropdown on time series page

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#23110]
I decommissioned node 4:

![image](https://user-images.githubusercontent.com/5768024/36694128-63dffc28-1b0b-11e8-8001-c2f063a69f5c.png)
 
But can still get to it from the admin UI drop down. Meanwhile, the node list is correct:

![image](https://user-images.githubusercontent.com/5768024/36694153-74822d58-1b0b-11e8-929c-500e2cfc3db5.png)

**Comment by mrtracy** [comment]
Keep in mind that the decommissioned node still existed at some point, and you can view historical data on the graphs page.

A possibly different solution I'll throw out: since we're appending the NodeID already, we can add a marker (e.g. "d") into the node ID, and sort them after all other nodes.  So something like "137.197.195.129:26257 (d, n4)", and it appears at the end of that list.

Otherwise, yes, they can be removed from that dropdown.

**Comment by dianasaur323** [comment]
Hmmm.. I see - good point. That being said, at some point, regardless of whether or not we label it as (d, n4), we should remove the node especially after the time frame is out. I also have a suspicion that the behavior isn't what we expect - I don't remember the exact specifics, but I seem to remember that right after I decommissioned the node, I was no longer able to view time series metrics (it just shows no data available), which indicates that it's possible that the minute a node is decommissioned, we stop showing the time series? I believe when @m-schneider made some fixes, she removed the time series or decommissioned nodes from the graphs, and this might be the reason for this behavior. In that context, if we can't see the historical time series of the decommissioned nodes anyway, maybe the path of lease resistance is to just remove them from the dropdown? Open to thoughts.

**Comment by couchand** [comment]
The current behavior (as I understand it) is that we continue to show the time series for the decommissioned node until it rolls out of the time window.  (I will go verify that now).  It would be a reasonable extension of this to also remove the node from the dropdown selector at this point in time, though that's a nontrivial change unfortunately.

I also like the idea of annotating such nodes as decommissioned for as long as they are still visible, both in the dropdown as well as the details tooltip (though I think we should be more obvious than just a 'd').

Just for reference, the changes @m-schneider made for this (#21476) never landed, as it seemed that (#22626) took care of the usability concern without breaking historical data.
