### ISSUE TITLE
distsql: Improve explain diagrams for count(*) queries

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/cockroach#23113]
Currently the `EXPLAIN (DISTSQL)` diagrams report the `Out:` rows for processors to be empty for queries that are performing a `COUNT(*)`, which looks odd since it appears that nothing is outputted form the processor. The diagram (in `flow_diagram.go`) could be extended to better indicate this case.

**Comment by RaduBerinde** [comment]
Maybe `Out: ∅`
