### ISSUE TITLE
*: add iterator leak test 

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#23138]
Forgetting to close a RocksDB iterator causes all manner of subtle bugs: file descriptors run out, or the disk fills up, and often hours after the iterator was leaked. #23117 is the most recent example of this.

Since Go can't do us any favors here, we should teach `leaktest.AfterTest(t)` to check for leaked iterators so we can avoid this class of bug once and for all. We could also consider a flag to enable "time-bomb" iterators that explode if kept open for more than ~1m.

**Comment by bdarnell** [comment]
Rocksdb exports a couple of stats for this: `rocksdb.num-snapshots` and `rocksdb.oldest-snapshot-time`. We can add those to our `DBStatsResult` to track them in timeseries, and also assert that num-snapshots is zero when closing the rocksdb instance.

**Comment by petermattis** [comment]
Asserting the num-snapshots or iterators is zero when closing the rocksdb instance would probably go a long way and is easy to do. Marking this for 2.0 because we've been bitten by this twice recently.

**Comment by petermattis** [comment]
`rocksdb.num-snapshots` doesn't seem to include the implicit snapshots held by iterators, but I think that is ok because we can maintain the number of open iterators ourselves in the `libroach` code.

**Comment by benesch** [comment]
The stat that does reflect the implicit snapshots is `rocksdb.num-live-versions`. It'll sit at `1` even with an open iterator until a new SST is created, though, so it's not granular enough to use for leak detection. Agreed that the easiest approach is to refcount iterators ourselves.

Are you actively working on this, @petermattis?

**Comment by petermattis** [comment]
> Are you actively working on this, @petermattis?

Not actively, but I can certainly do it.

**Comment by benesch** [comment]
Now that #23183 is in the works with a different approach, is it still worth tracking `num-snapshots`, `oldest-snapshot-time`, and `num-live-versions`? I have a half-baked PR to do so.

A graph of `num-live-versions` might be a handy way of spotting an SST leak in production, but perhaps it won't come up if we refcount iterators properly.

**Comment by bdarnell** [comment]
I think it would be nice to go ahead and get those plumbed into timeseries (and for `oldest-snapshot-time`, let's subtract it from now so the timeseries is `oldest-snapshot-age`). We do sometimes use snapshots that don't come from iterators (and we might do more in the future; this could let us reduce read blocking in the command queue).
