### ISSUE TITLE
sql: joins with subquery to extract max are slow

### ISSUE THREAD

**Issue by dfaust** [cockroachdb/cockroach#23147]
I wrote a small test programm to evaluate cockroachdb, you can find it with some instructions at: https://github.com/dfaust/cockroachdb-test

It works on a table with versioned items:

```sql
CREATE TABLE docs (
  user_id uuid,
  doc_id uuid,
  revision int,
  payload bytes,
  PRIMARY KEY (user_id ASC, doc_id ASC, revision DESC)
);
```

The goal is to retrieve the latest version of some items. This can be done using a subquery like:

```sql
SELECT
    docs.user_id, docs.doc_id, docs.revision, docs.payload
FROM
    (SELECT
        user_id, doc_id, MAX(revision) as max_revision
    FROM
        docs
    WHERE
        docs.user_id = $1
    AND
        docs.doc_id IN ($2)
    GROUP BY
        user_id, doc_id
    ) AS temp
LEFT JOIN
    docs
ON
    docs.user_id = temp.user_id
AND
    docs.doc_id = temp.doc_id
AND
    docs.revision = temp.max_revision
```

With postgresql such a query takes about 0.5 - 2 ms - depending on the batch size.
With cockroachdb queries take at least 1000x as long, sometimes even minutes. The spread is high and the duration depends on the available memory.

Some notes about the test program:
It has two actions, `load` and `run`. During the load phase data is created using a pseudo random number generator, and during the run phase some of that data is retrieved with some random characteristics.

Versions tested:
cockroachdb 2.0-alpha.20180212
postgresql 10.2

**Comment by knz** [comment]
Hi @dfaust!

Thanks for your interest in CockroachDB.
Your issue here is highlighting four different problems that we can look at:

- the MAX aggregation does not make use of the primary index of the table optimally. This causes the subquery to be much more costly than necessary. I have filed  #23149 separately to track this. 

- the join currently use an inefficient algorithm for your use case. We have recently added support for a better algorithm, but that is not enabled by default. You can try it out by using `set experimental_force_lookup_join = on` in the client session before issuing your test query (you may also need a more recent 2.0 alpha release to get access to this new feature).

- your query is using a left outer join; I think for your use case an inner join would be more appropriate. (Inner joins are also slightly faster in CockroachDB).

- although a join should be faster (that's why we're going to look into #23149) a much more optimal version of the same query, which should already work faster with CockroachDB, is the following:

```sql
SELECT DISTINCT ON(user_id, doc_id)
    user_id, doc_id, revision, payload
FROM docs
WHERE docs.user_id = $1 AND docs.doc_id IN ($2)) as docs
ORDER BY user_id, doc_id, revision DESC
```

Can you try it out with your data set and share the results with us?

**Comment by knz** [comment]
My colleague @RaduBerinde points out that you can also simplify the query as follow, based on the ordering of columns in the primary key:

```sql
SELECT
    docs.user_id, docs.doc_id, docs.revision, docs.payload
FROM
    (SELECT
        user_id, doc_id, revision as max_revision
    FROM
        docs
    WHERE
        docs.user_id = $1
    AND
        docs.doc_id IN ($2)
    ORDER BY user_id, doc_id, revision DESC
    LIMIT 1
    ) AS temp
LEFT JOIN -- can also use JOIN without LEFT I think
    docs
ON
    docs.user_id = temp.user_id
AND
    docs.doc_id = temp.doc_id
AND
    docs.revision = temp.max_revision
```

(This will still benefit from the better algorithm described in my previous comment)

**Comment by dfaust** [comment]
@knz Thank you for the quick reply.

* You are right, this should actually be an INNER JOIN, but it doesn't really change anything for my results because the queries still take way too long for any measurements to make sense.

* The query from https://github.com/cockroachdb/cockroach/issues/23147#issuecomment-368871456 is faster, though still very slow (~10s). But it is also wrong, because it returns only one row (LIMIT 1), my goal was to return a batch of rows.

* The query from https://github.com/cockroachdb/cockroach/issues/23147#issuecomment-368854163 on the other hand works very well, it's about 40% as fast as postgresql. (I updated the plot at https://github.com/dfaust/cockroachdb-test)

* I also tried experimental_force_lookup_join, but it's not available, yet. In case you are interested, I wouldn't mind testing it, when new binaries become available.

From my point of view this issue is solved, because the workaround is better anyway.
Thank you very much!

**Comment by knz** [comment]
> But it is also wrong, because it returns only one row (LIMIT 1), my goal was to return a batch of rows.

With the restriction in your example (`WHERE        docs.user_id = $1    AND        docs.doc_id IN ($2)`) there can only be 1 row that matches. I assume your real test uses multiple values for doc_id? In that case indeed the simplification doesn't work. The DISTINCT ON solution is best though.

**Comment by knz** [comment]
I'm happy that you have found a satisfactory way forward. We'd be delighted to see the progress of your testing on the newer 2.0 binaries. I will close this issue until then.

**Comment by knz** [comment]
@dfaust tip in your plots you can make txn/s use the "secondary y-axis" so the values become more clear.

**Comment by dfaust** [comment]
> I assume your real test uses multiple values for doc_id?

You're right, I didn't make that very clear.

And thanks for the tip, I updated the plots.

**Comment by dfaust** [comment]
@knz: I just ran my test with the subquery against cockroachdb 2.0-beta.20180305 with `set experimental_force_lookup_join = true` and the query time dropped from 10s to 16ms. :+1:

**Comment by knz** [comment]
Oh wow excellent news! Shoutout to @pbardea who did the bulk of the work.
