### ISSUE TITLE
sql: reduce (eliminate?) support for sessions without a current database set

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#23145]
Discussed with @nvanbenschoten and @jordanlewis while working on #21456 and #23045.

pg does not support client sessions without a current database set. The virtual schemas (especially pg_catalog) are not well-defined if there is no current database. 

Also in their current implementation they can generate a large amount data if queried by a client without a current database set, putting pressure on the SQL allocation pool.

The discussion on #21456 suggests evolving CockroachDB so that client sessions more often find themselves with a current database set by default. There's a spectrum of approaches:

- have the current database set to `system` if not specified in the conn string / pgwire options
- have the current database set to some arbitrary constant (e.g. `default`) and encourage the user via `cockroach sql` to create the database if it doesn't exist yet
  - might be a UX issue since only admin users can create databases
- have the current database set to the username (like in pg), encourage the user to create
  - same UX problem as above
- make every new cluster contain a "default" database, set that as default current database for new sessions that don't specify otherwise
- same as above, but create the "default" db on-demand automatically

cc @bdarnell

**Comment by bdarnell** [comment]
Personally coming from a mysql background (where having no current database is perfectly normal), I find the postgres behavior annoying.

In postgres, creating a database is a non-sql command, so there's no question of how do you connect to the database to create your first database. We have `CREATE DATABASE` as a SQL statement, so you need to be able to connect somehow (either to some default (possibly `system`) or to a database name that doesn't yet exist). Both of these seem weird to me; I think I'd rather keep the no-database state (even if it means disallowing unqualified access to the virtual schemas).

**Comment by knz** [comment]
Of the various options listed above, none include the situation "refuse the user a connection because the db in the conn string doesn't exist yet".

I'd personally like that the user always finds a database already available for them if they don't really know what they're doing (yet), this will lower the onramp.

**Comment by bdarnell** [comment]
> Of the various options listed above, none include the situation "refuse the user a connection because the db in the conn string doesn't exist yet".

Understood, but the fact that we allow this is something that makes CRDB unusual. Other DBs only allow you to connect to databases that already exist. I happen to like this, but "connect to a non-existent database and create it as your first action" feels like a non-intuitive clever trick rather than something we have to ask everyone to do when they're first starting out.

**Comment by knz** [comment]
Ok, so don't you also support the idea to make a default db exist automatically?

**Comment by bdarnell** [comment]
Of the proposals here, I think that a `default` database created at cluster initialization time is the best option, but even that has strange edge cases. What if you drop or change permissions on the default database?

**Comment by knz** [comment]
I'd say that no users should have DROP or GRANT permission on it. If root wants to disallow CREATE after other databases have been set up, that would be kosher with me.
