### ISSUE TITLE
sql: support string_to_array() - cut a string at a given delimiter

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#23144]
This is for compatibility with PostgreSQL, also needed for #19337.

https://www.postgresql.org/docs/10/static/functions-array.html

`string_to_array()` also enables nifty aggregations, like collecting the parts of a single columns into two columns, e.g.:

```sql
select array_agg(x[1]) as firstnames, array_agg(x[2]) as lastnames
  from (select string_to_array(users.name, ' ') from users)
```

**Comment by justinj** [comment]
`string_to_array` was added in #22391, so going to close this

**Comment by knz** [comment]
woooo nice! thanks
