### ISSUE TITLE
sql: support pg_column_size

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#23173]
Postgres has a function `pg_column_size` that tells you the number of bytes that a datum is stored as. Since we recommend that users keep datums below 1MB, for datums where the storage size is a bit more opaque than `BYTES`, like `JSONB` and arrays, it would be useful to provide this function so that users can write `CHECK` constraints or inspect their data.

**Comment by isoos** [comment]
any plans to support this?

**Comment by jordanlewis** [comment]
Yes, we'd like to. Should be simple if anyone out there is looking for a good first issue!

**Comment by C0rWin** [comment]
@jordanlewis I gave it a try, can you please take a look here PR#55312?

**Comment by solongordon** [comment]
Fixed by #55312, thanks @C0rWin!
