### ISSUE TITLE
Performance optimization：need add cache for Raft truncated state

### ISSUE THREAD

**Issue by thundercw** [cockroachdb/cockroach#2320]
We did a performance test and found that  `r.raftTruncatedState()`  is a performance bottleneck.
See call stacks:
```
stack1: multinode.go:run -> node.go:newReady()->r.raftLog.nextEnts()->l.slice()->mustCheckOutOfBounds()
->l.firstIndex()->l.storage.FirstIndex()->raftTruncatedState()
stack2: r.raftLog.term()->l.firstIndex()->l.storage.FirstIndex() ->raftTruncatedState
```
If there is a lot of ranges and  write requests are heavy， It will become a bottleneck .

**Comment by tschottdorf** [comment]
related to #1135. We're still working on stability/correctness for Raft, so performance hasn't been touched  yet.
