### ISSUE TITLE
cli: cockroach gen haproxy doesn't accept url flags

### ISSUE THREAD

**Issue by arjunravinarayan** [cockroachdb/cockroach#23222]
`cockroach gen haproxy` accepts `--host`, `--port`, etc. in order to connect to a cluster and generate a load balancer configuration file using the information about all the nodes connected to that cluster. However, it does not take `--url`, as `cockroach sql` does. There's no reason for this incompatibility, and we should add support for `--url` as well.

**Comment by knz** [comment]
Dup #4984
