### ISSUE TITLE
sql: dropping large table blocks creation of new table with the same name

### ISSUE THREAD

**Issue by rjnn** [cockroachdb/cockroach#23223]
there has been a regression in schema changes w.r.t. dropping tables.

I ran the following commands:

`ycsb --splits=1000`

Then I ran `ycsb --splits=1000 -drop`, which drops the existing table, and recreates a new table and fills it. I got the following error:

`2018/02/28 17:28:52 Setting up database failed: pq: table is being dropped`

This is not supposed to happen. This was previously reported in #7348 and fixed in #13908, but seems to have regressed since them.

Assigned to @jordanlewis for triage as to importance and assignment. Tentatively assigned to 2.1 milestone.

**Comment by vivekmenezes** [comment]
likely same as https://github.com/cockroachdb/cockroach/issues/22256

**Comment by vivekmenezes** [comment]
If the drop is happening on one node and the create on another node this is expected behavior. This should have nothing to do with how large the table is.
