### ISSUE TITLE
sql: drop table taking more than 5 minutes to drop a table with 2 rows

### ISSUE THREAD

**Issue by m-schneider** [cockroachdb/cockroach#23244]
I've been trying to reproduce an unrelated panic by repeatedly creating and dropping the same table. Steps to reproduce the slowness are:

1. Start a local insecure cluster with 3 nodes.
2. Create a table with multiple columns.
3. Add 2 rows to the table.
4. Add an index for a column.
5. Restart every node in the cluster.
6. Drop the table.
7. Wait 1-6 minutes.

**Comment by m-schneider** [comment]
@vivekmenezes, can you please triage?

**Comment by justinj** [comment]
I've seen this before, something to do with a node having a lease and then dying, and then the rest of the cluster having to wait for the lease to expire?

**Comment by vivekmenezes** [comment]
I suspect it is because the alter index kills a node and that node has a schema change lease on the table. Currently schema change leases last for 5 minutes (SchemaChangeLeaseDuration)

**Comment by m-schneider** [comment]
The 5 minutes is very consistent with what I'm seeing.

**Comment by benesch** [comment]
Huh, this is a case where teaching schema changes to use node liveness-based leases, like we do for backup/restore, would actually significantly improve their performance. With a liveness-based lease, restarting a node will (typically) expire all its leases.
