### ISSUE TITLE
sql: Implement SET TIME ZONE

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#2327]
This is to improve the presentation of the TIMESTAMP type for our users.

**Comment by keyan** [comment]
@vivekmenezes are you tackling this? I'm trying to get started contributing to cockroach. If this isn't a good issue to start with I'm happy to try something else if you have suggestions.

**Comment by petermattis** [comment]
Hi @keyan. Would love to have your help, though @vivekmenezes will have to speak to whether he has started on this or not. Another good issue to tackle (currently also on Vivek's plate) is #2242.

**Comment by vivekmenezes** [comment]
@keyan please take a stab at it. I'm happy to review your PR. Thanks for
taking it on!

**Comment by vivekmenezes** [comment]
@keyan do you need any help with this issue? I'm happy to discuss this with you.
