### ISSUE TITLE
split under-replicated and slow stats

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#23297]
Right now, a slow replica is reported to be under-replicated.  This is confusing users.

I propose that we split this into two states, under-replicated and slow (or perhaps behind?).  With geo-distributed clusters, slow replicas is much more common, but under-replication is a problem.

This might be a simple starter project and it would touch a number of different systems.

**Comment by dianasaur323** [comment]
Just so I understand this issue, is your proposal to split out "slow ranges" both in the time series graphs that are relevant, and in the problem ranges debug pages?

**Comment by BramGruneir** [comment]
exactly, and the RPC endpoint as well and possibly metrics reporting.

This came up in a client meeting in which the orange under-replicated ranges stat was showing up and it was due to slow replicas and not true under-replicated ranges.  In geo-distributed clusters, it will not be uncommon for a single replica to be slower than the others while under load.

**Comment by dianasaur323** [comment]
Ok, will add it to the 2.1 roadmap, although priority comes after some other items that we've been wanting to do.

**Comment by BramGruneir** [comment]
I marked this as a "good first issue" for a reason.  It should be relatively easy to do and if I had more time, I'd have already done it myself.  

This cleans up some basic confusion that both devs and clients have seen and I think it should be relatively high priority.

**Comment by dianasaur323** [comment]
ok noted!
