### ISSUE TITLE
sql: support coercing string literals to arrays

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#23299]
In PostgreSQL, the following statement works fine:

```
#  select '["a", {"b":1}]'::jsonb #- '{1,b}';
 ?column?  
-----------
 ["a", {}]
```

CockroachDB complains

```
> select '["a", {"b":1}]'::jsonb #- '{1,b}';
pq: unknown signature: json_remove_path(jsonb, string)
```

unless you specifically make the RHS an array:

```
> select '["a", {"b":1}]'::jsonb #- array['1', 'b'];
+------------------+
| json_remove_path |
+------------------+
| ["a", {}]        |
+------------------+
> select '["a", {"b":1}]'::jsonb #- '{1,b}'::text[];
+------------------+
| json_remove_path |
+------------------+
| ["a", {}]        |
+------------------+
```

We should support automatically coercing string literals to arrays. According to @justinj this isn't trivial.

/cc @knz

**Comment by nstewart** [comment]
We just had a customer run into this. cc @jseldess since it looks like it won't be fixed for 2.0. cc @awoods187

**Comment by knz** [comment]
Complement: #24746

**Comment by knz** [comment]
see  #33341

**Comment by awoods187** [comment]
See https://stackoverflow.com/questions/55047689/sum-of-differences-over-a-jsonb-array-field-in-cockroachdb/55048350#comment96898607_55048350
