### ISSUE TITLE
sql: Add useful Date/Timestamp functions.

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#2329]
http://www.postgresql.org/docs/8.0/static/functions-datetime.html
lists all the functions. I think we should at least implement

age(timestamp, timestamp)
age(timestamp) -> interval
current_date
current_timestamp/localtimestamp/now

**Comment by petermattis** [comment]
We should also implement `extract` which looks like the workhorse for pulling components (year, month, day, hour, etc) out of a date/timestamp.
