### ISSUE TITLE
sql: Add implicit casting from a string to Date/Timestamp/Interval types

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#2330]

**Comment by petermattis** [comment]
We don't add implicit casting in other domains are we sure we want to do so here. As an alternative, we should support the `DATE '<date>'` and `'TIMESTAMP '<timestamp>'` syntax, which is effectively a cast of the string to the specified type.

**Comment by vivekmenezes** [comment]
I like the alternative at least as a medium term solution. The downside is that a user needs to specify DATE/TIMESTAMP.

**Comment by petermattis** [comment]
The `{DATE,TIMESTAMP} '<date|timestamp>'` syntax is supported by postgres, mysql and others. See http://www.postgresql.org/docs/9.4/static/datatype-datetime.html and search for `literal`.

**Comment by vivekmenezes** [comment]
Hey that's great. I wasn't working on it.
