### ISSUE TITLE
sql: refactor descriptors to have all manipulations done in a single place.

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#2331]
There are a bunch of things we need to do when manipulating descriptors, others that we will, or may need:
* validate descriptors after reading, and before writing
* go through the gossip version of the descriptors (coming in #2179)
* set the systemDB trigger (maybe, this is still TBD in #2324)

**Comment by petermattis** [comment]
Is there anything else to be done here?

**Comment by mberhault** [comment]
this was cleanup. obsolete.
