### ISSUE TITLE
sql: whole floats print as ints

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#2332]
Currently `DFloat(1.0).String() == "1"`, which means we end up with integers if we parse -> print -> parse whole floats.

**Comment by petermattis** [comment]
Yeah, this is the behavior of `strconv.ParseFloat` when passing `-1` for the precision. Is there anything particular wrong about it, or just surprising? I suppose we could suffix `.0` if the formatted float does not contain a decimal point.

**Comment by jmank88** [comment]
While investigating this issue, I discovered that a float may be output as +Inf or -Inf, but neither of those will parse as an input expression. Is this expected behavior? Or was I incorrect to assume that data.String() output should produce legal input?

**Comment by petermattis** [comment]
Yeah, we should probably support `[+-]Inf{,iniity}` and `NaN`. Should be a relatively small change to the scanner.
