### ISSUE TITLE
roachtest: `t.Status` is not ergonomical

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#23336]
`t.Status("asd")` will have the test runner periodically print status lines mentioning `asd` as the currently active command. However, it's hard to use this in non-confusing ways.

For example,

```go
c.Run(something) // calls t.Status()
time.Sleep(time.Hour)
```

will make it look like `c.Run` got stuck for an hour.

```go
go func() {
  t.Status("a")
}()
go func() {
  t.Status("b)
}()
```

^- This doesn't make a lot of sense and yet it is in our code since we usually need to orchestrate several long-running operations (think: two load generators).

The intention in `t.Status` is good: when watching a test, we need an indication of what the the test is currently doing, in particular when operations just take a long time.

In an ideal world, the test harness would keep track of all the goroutines that are direct children of the test's and would be able to look up the line of code they are in, so that in the `time.Sleep` example the test runner would output something like

```
> goroutine 2: time.Sleep(time.Hour)
```

This looks like it would be possible with a little bit of guerrilla parsing of `debug.Stack()`, but it's unsavory. Perhaps there's something better.

cc @petermattis for ideas.

**Comment by petermattis** [comment]
> In an ideal world, the test harness would keep track of all the goroutines that are direct children of the test's and would be able to look up the line of code they are in, so that in the time.Sleep example the test runner would output something like

That's an interesting idea. I wonder if the output will be overwhelming. A 10-node test could easily have 10+ goroutines (one for a load generator on each node + monitor goroutine). 

Perhaps `t.Status()` should take two parameters, the status message and a status key. The key is arbitrary. The periodic status output would display all of the keys with non-empty messages. Your multi-load generator example would look like:

```
go func() {
  t.Status("1", "a")
  defer t.Status("1", "")
}()
go func() {
  t.Status("2", "b")
  defer t.Status("2", "")
}()
```

This doesn't address the `time.Sleep(time.Hour)` problem directly, but really a test shouldn't be doing that.

Thoughts?

**Comment by petermattis** [comment]
@tschottdorf Any thoughts about my counter-proposal?

**Comment by tschottdorf** [comment]
> This doesn't address the time.Sleep(time.Hour) problem directly, but really a test shouldn't be doing that.

I think tests will be doing that on and off, by accident. But maybe that's ok.

Your proposal is definitely a lot better than what we have today and it seems straightforward to introduce. I'd like to see it tried out.
