### ISSUE TITLE
ui: network report does not display after pkill -9

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/cockroach#23349]
bug report

**BUG REPORT**

v2.0-alpha.20180129

2. Please describe the issue you observed:

- What did you do?

https://localhost:8080/#/reports/network
pkill -9 cockroach
restart the database
go back to `https://localhost:8080/#/reports/network`
the page will wait with the below
```
NETWORK DIAGNOSTICS
Loading cluster status...
```

- What did you expect to see?

Display of latency table

- What did you see instead?

The cockroach.log will have the below

>Error: could not cleanup temporary directories from record file: could not lock temporary directory /cockroach/cockroach-data/cockroach-temp491020999, may still be in use: IO error: While lock file: /cockroach/cockroach-data/cockroach-temp491020999/TEMP_DIR.LOCK: Resource temporarily unavailable

To resolve the issue,

`rm -rf /cockroach/cockroach-data/cockroach-temp491020999` will restore the functionality

**Comment by dianasaur323** [comment]
hmm... not sure if this behavior is unexpected, but perhaps @BramGruneir has an opinion?
