### ISSUE TITLE
storage: SCATTER should have an option to randomize replicas

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#23358]
Both `ALTER TABLE tpcc.warehouse SCATTER` and `ALTER TABLE tpcc.warehouse SCATTER FROM (0) TO (5000)` do not seem to be doing anything. Specifically, `SHOW TESTING_RANGES FROM TABLE tpcc.warehouse` reveals the replicas are on the same ranges and the leaseholders do not appear to have moved. I haven't investigated further. Possibly user error.

**Comment by petermattis** [comment]
Cc @a-robinson (in case you're aware of this)

**Comment by petermattis** [comment]
think the lack of replica movement is expected given the current implementation of scatter which simply forces a replica onto the replicate queue. I would expect the leases to be moving around, though. Perhaps they are and I'm not paying close enough attention.

**Comment by a-robinson** [comment]
As you mention, replica movement isn't expected as currently implemented. Leases for the table should be randomly scattered, though.

And it appears to work for me. I just tested on adriatic and eyeballing shows a majority of the leaseholders having changed. Given that you'd expect 2/3 to change, it looks about right. Excerpt pasted below. The leases per store graph in the admin UI also showed some shuffling happening

Do you have a specific cluster or reproducible case I can look at? If your cluster is new enough to have the custom graph debug page, you should be able to look at the `leases_transfers_success` metric. Or you can just eyeball it on the `/_status/vars` page before and after running scatter. I see that jump by more than 100 per node when I run the `SCATTER` on adriatic.

```
root@:26257/> select * from [show testing_ranges from table test.kv] order by "Range ID" limit 30;
+-----------------------+-----------------------+----------+----------+--------------+
|       Start Key       |        End Key        | Range ID | Replicas | Lease Holder |
+-----------------------+-----------------------+----------+----------+--------------+
| NULL                  | /-9205147582991822299 |       12 | {1,2,4}  |            4 |
| /-1271340494264031    | /16755206705823991    |       13 | {4,5,6}  |            6 |
| /4618973309224404983  | /4637104073477560876  |       14 | {1,3,5}  |            3 |
| /2307150480577560789  | /2325379315868213406  |       15 | {2,3,5}  |            5 |
| /6923178504782837975  | /6941083175137397392  |       16 | {1,2,5}  |            2 |
| /1151307145826154336  | /1169262572337986016  |       17 | {1,5,6}  |            5 |
| /5769585157399936016  | /5787483029920448293  |       18 | {1,4,6}  |            6 |
| /8073011912347482450  | /8091012671830356243  |       19 | {1,4,6}  |            1 |
| /1727621844133744327  | /1745556385030681056  |       20 | {1,3,6}  |            1 |
| /-4611401448529411532 | /-4593407443710265847 |       21 | {3,5,6}  |            3 |
| /-6916897709211075065 | /-6899335905418210822 |       22 | {1,5,6}  |            6 |
| /-2302421216743507422 | /-2284150853354272210 |       23 | {2,3,5}  |            5 |
| /3462122301603131088  | /3480443850563807809  |       24 | {1,2,5}  |            5 |
| /-8070526731882729225 | /-8052777842739029732 |       25 | {1,3,4}  |            3 |
| /-3456344315612239773 | /-3438151565045684090 |       26 | {1,5,6}  |            6 |
| /-5766601605813055235 | /-5748086566665007523 |       27 | {3,4,5}  |            4 |
| /-1155453314427052410 | /-1137212124268349458 |       28 | {2,3,5}  |            5 |
| /2884428637450377871  | /2902454439382628344  |       29 | {3,4,5}  |            5 |
| /4040782916273237664  | /4058938066623895529  |       30 | {2,5,6}  |            6 |
| /5195129706318391684  | /5212925297656784603  |       31 | {3,5,6}  |            3 |
| /6345067590346941754  | /6363015590180775512  |       32 | {1,3,5}  |            3 |
| /8650467652735167521  | /8668120727789125636  |       33 | {1,3,5}  |            1 |
| /7499132892205561834  | /7516807806821916192  |       34 | {1,3,6}  |            3 |
| /2016468534343683054  | /2034630666228700203  |       35 | {2,5,6}  |            5 |
| /1438616322132166777  | /1456437716089812877  |       36 | {2,3,5}  |            5 |
| /6634468774086344420  | /6652325999977700183  |       37 | {2,5,6}  |            6 |
| /5481884871928968680  | /5499761389398655150  |       38 | {3,5,6}  |            5 |
| /8361720618197468921  | /8379666077723240040  |       39 | {1,5,6}  |            5 |
| /6055982835075865310  | /6074018447398849940  |       40 | {1,5,6}  |            5 |
| /-8648079883172208518 | /-8629755558947178825 |       41 | {1,2,5}  |            1 |
+-----------------------+-----------------------+----------+----------+--------------+
(30 rows)

Time: 856.080413ms

root@:26257/> alter table test.kv scatter;

[...]

root@:26257/> select * from [show testing_ranges from table test.kv] order by "Range ID" limit 30;
+-----------------------+-----------------------+----------+----------+--------------+
|       Start Key       |        End Key        | Range ID | Replicas | Lease Holder |
+-----------------------+-----------------------+----------+----------+--------------+
| NULL                  | /-9205147582991822299 |       12 | {1,2,4}  |            2 |
| /-1271340494264031    | /16755206705823991    |       13 | {4,5,6}  |            6 |
| /4618973309224404983  | /4637104073477560876  |       14 | {1,3,5}  |            1 |
| /2307150480577560789  | /2325379315868213406  |       15 | {2,3,5}  |            2 |
| /6923178504782837975  | /6941083175137397392  |       16 | {1,2,5}  |            1 |
| /1151307145826154336  | /1169262572337986016  |       17 | {1,5,6}  |            1 |
| /5769585157399936016  | /5787483029920448293  |       18 | {1,4,6}  |            6 |
| /8073011912347482450  | /8091012671830356243  |       19 | {1,4,6}  |            6 |
| /1727621844133744327  | /1745556385030681056  |       20 | {1,3,6}  |            3 |
| /-4611401448529411532 | /-4593407443710265847 |       21 | {3,5,6}  |            5 |
| /-6916897709211075065 | /-6899335905418210822 |       22 | {1,5,6}  |            5 |
| /-2302421216743507422 | /-2284150853354272210 |       23 | {2,3,5}  |            2 |
| /3462122301603131088  | /3480443850563807809  |       24 | {1,2,5}  |            2 |
| /-8070526731882729225 | /-8052777842739029732 |       25 | {1,3,4}  |            1 |
| /-3456344315612239773 | /-3438151565045684090 |       26 | {1,5,6}  |            1 |
| /-5766601605813055235 | /-5748086566665007523 |       27 | {3,4,5}  |            5 |
| /-1155453314427052410 | /-1137212124268349458 |       28 | {2,3,5}  |            5 |
| /2884428637450377871  | /2902454439382628344  |       29 | {3,4,5}  |            3 |
| /4040782916273237664  | /4058938066623895529  |       30 | {2,5,6}  |            6 |
| /5195129706318391684  | /5212925297656784603  |       31 | {3,5,6}  |            3 |
| /6345067590346941754  | /6363015590180775512  |       32 | {1,3,5}  |            5 |
| /8650467652735167521  | /8668120727789125636  |       33 | {1,3,5}  |            3 |
| /7499132892205561834  | /7516807806821916192  |       34 | {1,3,6}  |            3 |
| /2016468534343683054  | /2034630666228700203  |       35 | {2,5,6}  |            5 |
| /1438616322132166777  | /1456437716089812877  |       36 | {2,3,5}  |            5 |
| /6634468774086344420  | /6652325999977700183  |       37 | {2,5,6}  |            2 |
| /5481884871928968680  | /5499761389398655150  |       38 | {3,5,6}  |            6 |
| /8361720618197468921  | /8379666077723240040  |       39 | {1,5,6}  |            6 |
| /6055982835075865310  | /6074018447398849940  |       40 | {1,5,6}  |            5 |
| /-8648079883172208518 | /-8629755558947178825 |       41 | {1,2,5}  |            1 |
+-----------------------+-----------------------+----------+----------+--------------+
```

**Comment by a-robinson** [comment]
And adriatic is running the current canddiate SHA (https://github.com/cockroachdb/cockroach/issues/23093), for what it's worth

**Comment by petermattis** [comment]
I'm testing on the `peter-tpcc` cluster on `roachprod`. It is currently down, but I'll bring it back up in a bit.

**Comment by petermattis** [comment]
Moving to 2.1 as I don't think there is anything to do here for 2.0.

`AdminScatterRequest` contains a `RandomizeLeases` field. I wonder if we should add a `RandomizeReplicas` field which forces a rebalance action even if the cluster is already balanced.

**Comment by a-robinson** [comment]
> Moving to 2.1 as I don't think there is anything to do here for 2.0.

Does that mean you couldn't reproduce your problem, or just that you didn't try? If leases aren't scattering, then there is something to do for 2.0.

> AdminScatterRequest contains a RandomizeLeases field. I wonder if we should add a RandomizeReplicas field which forces a rebalance action even if the cluster is already balanced.

If we have a good reason for it, sure. It'll be more complex to implement, though, given the need to respect constraints, disk fullness, diversity, etc. along the way. For leases we can just arbitrarily move them and rely on the knowledge that even if we move them somewhere suboptimal (e.g. in violation of the user's specified lease placement preferences), transferring leases back and forth is cheap and safe.

**Comment by petermattis** [comment]
> Does that mean you couldn't reproduce your problem, or just that you didn't try? If leases aren't scattering, then there is something to do for 2.0.

I didn't try. I assume your testing was more extensive than mine. I mainly filed this bug due to the replica imbalance which SCATTER doesn't address by design (at the moment). I'll be trying this again in a few hours and will move back to 2.0 if the lease imbalance persists.

> > AdminScatterRequest contains a RandomizeLeases field. I wonder if we should add a RandomizeReplicas field which forces a rebalance action even if the cluster is already balanced.
>
> If we have a good reason for it, sure. It'll be more complex to implement, though, given the need to respect constraints, disk fullness, diversity, etc. along the way. For leases we can just arbitrarily move them and rely on the knowledge that even if we move them somewhere suboptimal (e.g. in violation of the user's specified lease placement preferences), transferring leases back and forth is cheap and safe.

I was imagining that we'd pass a `forceRebalance` flag to `processOneChange` and then go through the normal allocation machinery which respects constraints and other factors.

**Comment by petermattis** [comment]
@a-robinson Are you working on this? If yes, let's reassign.

**Comment by a-robinson** [comment]
Yes, done.
