### ISSUE TITLE
jobs/workload: tpcc-5k load on 10 node cluster produced fractionCompleted outside of allowable range

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#23355]
With @danhhz's suggested `100x`ing of the CSV chunk size, I tried a restore of `tpcc-5k` on a 10 node cluster and on a 4 node cluster.

The 10 node cluster didn't finish in 12 hours and had a few problems along the way, such as the following message that Dan noticed. Unfortunately, the cluster got torn down before I could collect any more diagnostic information.

```
Job: fractionCompleted 1.000000 is outside allowable range [0.0, 1.0]
```

The 4 node cluster finished okay, however:

![image](https://user-images.githubusercontent.com/43821/36947537-218b67e2-1f9b-11e8-865a-c47d4596e26a.png)

@danhhz for triage.

**Comment by mjibson** [comment]
That's a cool bug. I think I know what it is.
