### ISSUE TITLE
cli: "Failed running" message may print a flag rather than the command

### ISSUE THREAD

**Issue by 0xbaadf00d** [cockroachdb/cockroach#23350]
When a command doesn't works, the CLI print an error message like `Failed running "..."`. According to the arguments order, this message is not correct, it can't blindly take the first element of the args string.

**Correct**
```
shell> ./cockroach sql --certs-dir=cert --host localhost
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.
#
Error: unable to connect or connection lost.

Please check the address and credentials such as certificates (if attempting to
communicate with a secure cluster).

dial tcp 127.0.0.1:26257: getsockopt: connection refused
Failed running "sql"
```

**Not correct**
```
shell> ./cockroach --certs-dir=cert --host localhost sql
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.
#
Error: unable to connect or connection lost.

Please check the address and credentials such as certificates (if attempting to
communicate with a secure cluster).

dial tcp 127.0.0.1:26257: getsockopt: connection refused
Failed running "--certs-dir=cert"

**Comment by dt** [comment]
Looks like our top-most `cli.Main` is indeed just grabbing the first arg on error including when, say, arg parsing/validation fails. Off the top of my head, we could try to do something smarter if we were able to match a command but not some/all flags, or we could just do `os.Args[1:]` instead, but I'll let someone who's more familiar with the CLI figure it out.

@knz IIRC you've looked quite a bit at the UX of the cli and/or would know who to direct this one towards.
