### ISSUE TITLE
ui: clusterviz: improve the capacity usage metrics in the cluster overview

### ISSUE THREAD

**Issue by josueeee** [cockroachdb/cockroach#23366]
**Current:**
![screen shot 2018-03-05 at 10 56 29 am](https://user-images.githubusercontent.com/29442020/36985015-2a13fae0-2064-11e8-81af-f4ca32c110e7.png)

**Improved:** 
<img width="1344" alt="cluster-overview-improvements" src="https://user-images.githubusercontent.com/29442020/36985051-4229b3d6-2064-11e8-9d6d-8b41c42f3f0d.png">

The improved design provides details about the used and available capacity for the entire cluster. This helps the user have a better understanding of these metrics.

**Comment by dianasaur323** [comment]
nice, was the plan to incorporate this in 2.0? if so, mind adding that as the milestone?

**Comment by vilterp** [comment]
I think we may want to say `usable` instead of `available` here, since elsewhere `available` means the amount of free space, not the amount of usable space.

https://github.com/cockroachdb/cockroach/blob/31e4299ab73a43f539b1ba63ed86be5ee18685f6/pkg/storage/metrics.go#L146-L153

**Comment by couchand** [comment]
Ongoing discussion about this terminology on #23686.
