### ISSUE TITLE
ui: rename "graph" to "chart"

### ISSUE THREAD

**Issue by couchand** [cockroachdb/cockroach#23419]
This is a graph:

![graph example](http://mathworld.wolfram.com/images/eps-gif/CocktailPartyGraph_700.gif)

This is a chart:

![chart example](http://nvd3.org/examples/img/stackedarea.png)

**Comment by BornToWin** [comment]
is this issue still open?

**Comment by couchand** [comment]
Hi @BornToWin, this will be closed by #23904 when I get around to rebasing that.  Thanks!
