### ISSUE TITLE
ui: double scrolling behavior in Node selector

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#23420]
If the Node selector needs to scroll, it doesn't prevent scrolling in the underlying page. In the animation below I'm just using the scroll wheel while hovering over the Node selector drop down. This is a UI nit and low priority. Feel free to bump to 2.1.

![weird scrolling](https://user-images.githubusercontent.com/6201335/37000079-2f83d14a-2090-11e8-8baa-95665b33df1d.gif)

**Comment by vilterp** [comment]
Not really sure what a better design would be here. Make dropdown bigger? Only works to a limited extent. Otherwise, not sure how to avoid double scrolling. Thoughts @josueeee?

**Comment by petermattis** [comment]
> When the mouse is positioned within the dropdown, scrolling should only affect the dropdown, not the page.

Exactly.

**Comment by josueeee** [comment]
I think it's both an interaction and design issue. The drop-down selector is not designed for long lists of items and if we think production clusters will reach this size, then we need to rethink the way someone filters content on a per-node basis.

**Comment by couchand** [comment]
Yes, there's definitely a problem if a cluster has more than a handful of nodes and the user is trying to pick a specific one by opening this dropdown and scrolling to a particular item.  We should consider that as part of our ongoing IA investigations.  But let's keep this particular issue focused on the bug as reported.
