### ISSUE TITLE
importccl: TestImportStmt/allow-default flake

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#23430]
csv_test.go:873: unexpected: pq: could not parse "" as type int: strconv.ParseInt: parsing "": invalid syntax

https://teamcity.cockroachdb.com/viewLog.html?buildId=547783&buildTypeId=Cockroach_UnitTests

**Comment by tschottdorf** [comment]
also got this, fwiw: https://teamcity.cockroachdb.com/viewLog.html?buildId=548223&buildTypeId=Cockroach_UnitTests
