### ISSUE TITLE
sql: `SET CLUSTER SETTING` can return ambiguous result

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#23445]
```go
		log.Infof(ctx, "upgrading cluster version to %s", cv)
		if _, err := db.Exec(fmt.Sprintf(`SET CLUSTER SETTING version = '%s'`, cv)); err != nil {
			t.Fatal(err)
		}
```

Seen in TestVersionUpgrade [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=548223&buildTypeId=Cockroach_UnitTests).

It seems that this should be retried internally since it's idempotent, though I'm not sure how hard that is to implement due to the tracking work involved.

If nothing else, it'd be good to have a wrapper that we can use for idempotent operations so that client applications can terminate ambiguous results when they run idempotent statements.

@andreimatei, you're probably a good candidate to decide what to make of this.

Jira issue: CRDB-5817

**Comment by andreimatei** [comment]
@jordanlewis passing it over to you :)
Trying to shed some test failures.

**Comment by tbg** [comment]
@jordanlewis would you mind making a column in your project that eats all the issues assigned to SQL Execution? Otherwise roachdash won't recognize them while they're in triage. Thanks!

**Comment by cucaroach** [comment]
The error in CI was lost to time so there's no telling what the original problem was.  @tbg do you remember?   I suspect the conn_executor now retries queries issued for "SET CLUSTER SETTING" but I have no idea.  @rafiss any ideas?

**Comment by rafiss** [comment]
I don't have an idea either. Since `TestVersionUpgrade` no longer exists, we should probably just close this.

**Comment by cucaroach** [comment]
Closing, @tbg please reopen if you think there's anything still actionable here.
