### ISSUE TITLE
roachtest: COCKROACH_DEV_LICENSE must be set to run tests

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#23442]
Most of the `roachtest` tests require enterprise features to run successfully. Without them, the tests usually fail with an error along the lines of `Error: restoring fixture: pq: use of RESTORE requires an enterprise license`. This requirement should be made more explicit and the error should not be swallowed. We should probably also fail the test immediately if the environment variable (which is used by [roachprod](https://github.com/cockroachdb/roachprod/blob/5c307e57996e150235abe4689079287db5663732/main.go#L674)) is not set.

**Comment by tschottdorf** [comment]
We should also consider whether we can make the test fixtures skip the enterprise check and/or whether it's worth factoring out the tests that use enterprise features into a subpackage.

In the short term, I suppose we could add the fatal and explain in the message that you can circumvent it by setting the var to the empty string.
