### ISSUE TITLE
sql: internal executor makes 1PC hard for things like table descriptor lease acquisition

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#23506]
When [acquiring](https://github.com/cockroachdb/cockroach/blob/bd9f99da94567de30408bdde962842456419803e/pkg/sql/lease.go#L140) the most recent lease on a table descriptor, `LeaseStore` opens a `client.Txn`. Inside this `txn`, it performs three steps:
1. it reads the existing table descriptor, given the tableID
2. it inserts into the `system.lease` table with an internal planner
3. it commits the transaction

If the entire transaction took place in the `client.Txn` domain, the KV write could be batched with the commit by using  `CommitInBatch`. This would allow the txn to run as a 1-phase commit txn. Unfortunately, at the moment the mismatch between the `client.Txn` and the `internalPlanner` is preventing us from performing an auto-commit that could be run as a 1-phase commit. We should explore ways to fix this.

In the short-term, we may be able to hook into the planner's `autoCommit` flag.

A more long-term and general goal would be for the `connExecutor` to look ahead in its `StmtBuf` for `COMMIT` statements. If it saw a `COMMIT` directly following another statement, it could conceivably run the first statement in "auto-commit" mode, which would allow it to hit the 1PC path. It could then ignore the `COMMIT` statement entirely.

**Comment by jordanlewis** [comment]
@ajwerner thoughts on this guy? I think we could close, since we're reimagining some of this stuff, right?

**Comment by andreimatei** [comment]
> A more long-term and general goal would be for the connExecutor to look ahead in its StmtBuf for COMMIT statements. If it saw a COMMIT directly following another statement, it could conceivably run the first statement in "auto-commit" mode, which would allow it to hit the 1PC path. It could then ignore the COMMIT statement entirely.

The issue I think complains mostly about awkwardness with the internal executor. However this general point about merging a `COMMIT` statement with a previous statement I think might be important. A lot of drivers and orms wrap single statements in explicit transactions. I'm not sure when the `COMMIT` - whether its pipelined with the statement or only sent after the statement's response. If anybody pipelines, then we'd definitely benefit a lot from detecting it.

**Comment by ajwerner** [comment]
Andrei want to reformulate the issue around providing an interface for system table usages of the internal executor to autocommit and thus maybe hit 1PC?

**Comment by ajwerner** [comment]
@nvanbenschoten I get the desire to make this 1pc but these things don't happen *that* often except for initial acquisitions. I'm closing this as premature optimization for now.
