### ISSUE TITLE
Error: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by inaxium** [cockroachdb/cockroach#23507]
**QUESTION**

In the certs Directory is the following:

```
[frank@instance-1 ~]$ ls certs
ca.crt  client.frank.crt  client.frank.key
```

Login with this command Work fine:

`cockroach sql --certs-dir=certs --host=10.132.0.3 --user=frank`

Result:

```
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.
#
# Server version: CockroachDB CCL v1.1.5 (linux amd64, built 2018/02/05 17:40:57, go1.8.3) (same version as client)
# Cluster ID: 0d85b746-f06a-4378-83af-c227944790b9
#
# Enter \? for a brief introduction.
#
frank@10.132.0.3:26257/>  
```

Following command:

`cockroach sql --url="postgresql://frank@10.132.0.3:26257?sslmode=verify-full&sslcert=certs/client.frank.crt&sslkey=certs/client.frank.key&sslroot=certs/ca.crt"`

Produced this error:

```
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.
#
Error: x509: certificate signed by unknown authority
Failed running "sql"
```

I tried a lot of combination. But I couldn't find the right one.

I need this for my golang connection.

Documentation Source:

[https://www.cockroachlabs.com/docs/stable/use-the-built-in-sql-client.html](https://www.cockroachlabs.com/docs/stable/use-the-built-in-sql-client.html)

Perhaps somebody else have an idea.

**Comment by inaxium** [comment]
I think finally that was an write error in the Dokumentation. It musst be:

`sslrootcert`

Not

`sslroot`

```
cockroach sql \
--url="postgresql://maxroach@12.345.67.89:26257/critterdb?sslcert=certs/client.maxroach.crt&sslkey=certs/client.maxroach.key&sslmode=verify-full&sslroot=certs/ca.crt"
```

**Comment by dt** [comment]
Thanks for digging into this @inaxium ! I'll make sure those docs get fixed!
