### ISSUE TITLE
*: Exercise code at high verbosity levels

### ISSUE THREAD

**Issue by abhimadan** [cockroachdb/cockroach#23503]
Some bugs, like #23198 (and likely other similar bugs), don't get caught immediately because code gated under high verbosity levels isn't typically run. To find more of these bugs, it would be useful to run tests at different verbosity levels to exercise that gated code.

Alternatively, it may also be worthwhile to investigate the usage of the `if log.V(n)` pattern and reduce usage of it. For example, `log.VEventf` could be used instead in some cases, which would allow the log's arguments to be evaluated and prevent things like nil pointer bugs from slipping through the cracks. If `VEventf` isn't appropriate, then gating the logs with `log.ExpensiveLogEnabled` may work, as it allows these logs to be in traces without enabling high verbosity, and also allows them to be executed more frequently.

**Comment by jordanlewis** [comment]
One easy way to do this is to run our test suite with `-verbosity=10`. In fact, doing so has already produced a panic #23505. We should fix these panics and add this kind of thing to our nightly tests.

**Comment by jordanlewis** [comment]
I thought this was finished.
