### ISSUE TITLE
ui: clusterviz: zoom to content

### ISSUE THREAD

**Issue by vilterp** [cockroachdb/cockroach#23513]
- On load of the node map, zoom to the minimum bounding box containing the child localities of the current locality.
- On clicking a locality, zoom to the minimum bounding box containing its sub-localities.

**Comment by vilterp** [comment]
cc @mrtracy

**Comment by vivekmenezes** [comment]
@mrtracy are you going to be able to get to this issue for 2.0

**Comment by mrtracy** [comment]
@vivekmenezes yes, PR should be going out today.
