### ISSUE TITLE
stability: "missing stock row"

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#23519]
While running against the tpcc-10k dataset, I'm periodically seeing a "missing stock row" error. This occurs when the `newOrder` txn doesn't get all of the rows it expects.

Some additional logging provides more context:

```
5: missing stock row
SELECT s_quantity, s_ytd, s_order_cnt, s_remote_cnt, s_data, s_dist_05
FROM stock
WHERE (s_i_id, s_w_id) IN ((6879, 2615), (8447, 5535), (15502, 2615), (15567, 2615), (94436, 2615), (98429, 2615))
ORDER BY s_i_id
```

The `5` indicates that this was the last row (0-based index). Curiously, all 6 rows appear to be present:

```
root@localhost:26257/tpcc> SELECT COUNT(*) FROM stock 
WHERE (s_i_id, s_w_id) IN ((6879, 2615), (8447, 5535), (15502, 2615), (15567, 2615), (94436, 2615), (98429, 2615)); 
+-------+
| count |
+-------+
|     6 |
+-------+
```

Here's another instance:

```
0: missing stock row
SELECT s_quantity, s_ytd, s_order_cnt, s_remote_cnt, s_data, s_dist_06
FROM stock
WHERE (s_i_id, s_w_id) IN ((16641, 3428), (49897, 3137), (61754, 3137), (73026, 3137), (74538, 3137), (82097, 3137), (97858, 3137))
ORDER BY s_i_id
```

Running that query by hand produces:

```
+------------+-------+-------------+--------------+---------------------------------------------------+--------------------------+
| s_quantity | s_ytd | s_order_cnt | s_remote_cnt |                      s_data                       |        s_dist_06         |
+------------+-------+-------------+--------------+---------------------------------------------------+--------------------------+
|         21 |     1 |           1 |            0 | d9cxNWM9cGi1PisNhsHswUv55LfT0woDO                 | LJoNY1EJ8oUBmx4ZrEv03nwl |
|         31 |     0 |           0 |            0 | hmYBZchJ2XkTroMNw7zlz0rMgJZ4HEZS1jVPQL3Ws9m47gxL  | RFCsCgypns8ETW4DSmEyPcxP |
|         51 |     0 |           0 |            0 | TPto84xxOGIhMpxgwZnhCBwfERaQgDMQnRiuHK3ANXUfLplw2 | JIvxyM98pQLZepqz9BDJSgRj |
|         69 |     0 |           0 |            0 | fctCjgUrCp6mZPYA1Mp5ebwY7L5hMydEarjsLq            | 59IA2mTPIjpTDDFrX5MymvhU |
|         77 |     0 |           0 |            0 | L1sp2o1mODnXuB6EhvISmsGLDDCUa9rnabMjavcgCtE       | Am0cqZRCQYTQdflwZcQT120T |
|         32 |     7 |           1 |            0 | hrGkBMswDZxd22eRSZEJdN7QuVqkSmo9fL58              | MxTH7pI2Sx3EpKkoX7PhxbDJ |
|         75 |     0 |           0 |            0 | y2UVk0zm7VMaYqBLXM3bUMPZm7F9Jjp7DEdKgH77w         | ows1MwMR9lMjGXOlgm3Adx1J |
+------------+-------+-------------+--------------+---------------------------------------------------+--------------------------+
```

This is running `cockroach-v2.0-beta.20180305-143-gf95187e` (the current release-2.0 head).

**Comment by petermattis** [comment]
I just added a bit of additional logging to check `rows.Err()` and it is `nil` when this problem occurs.

**Comment by jordanlewis** [comment]
I reproduced this problem on the same cluster. While adding my own debugging information, I decided to modify the query to output the `s_i_id` column that it's supposedly ordering by, to figure out which of the rows the query was skipping. So with the example above it'd become:

```
SELECT s_i_id, s_quantity, s_ytd, s_order_cnt, s_remote_cnt, s_data, s_dist_06
FROM stock
WHERE (s_i_id, s_w_id) IN ((16641, 3428), (49897, 3137), (61754, 3137), (73026, 3137), (74538, 3137), (82097, 3137), (97858, 3137))
ORDER BY s_i_id
```

Un(?)fortunately, this query modification prevented the problem from reoccurring. This smells like a planning or execution bug to me.

**Comment by petermattis** [comment]
I got another reproduction this morning:

```
5: missing stock row: [4297 6193 16712 16781 74149        ]
SELECT s_i_id, s_quantity, s_ytd, s_order_cnt, s_remote_cnt, s_data, s_dist_09
FROM stock
WHERE (s_i_id, s_w_id) IN ((4297, 2090), (6193, 2090), (16712, 2090), (16781, 2090), (31167, 2090), (43873, 2090), (46953, 2090), (65127, 2090), (72105, 2090), (72581, 2090), (73161, 2090), (74149, 8968), (82360, 2090))
ORDER BY s_i_id
```

Reformatting the queried values makes this a little clearer:

```
(4297, 2090),
(6193, 2090),
(16712, 2090),
(16781, 2090),
(31167, 2090),
(43873, 2090),
(46953, 2090),
(65127, 2090),
(72105, 2090),
(72581, 2090),
(73161, 2090),
(74149, 8968),
(82360, 2090)
```

It is very suspicious that the error occurred after retrieving one item from a different warehouse. Definitely seems like a query execution bug.

**Comment by petermattis** [comment]
And another reproduction:

```
7: missing stock row: [31748 49289 59724 78138 82234 96874 98314 ]
SELECT s_i_id, s_quantity, s_ytd, s_order_cnt, s_remote_cnt, s_data, s_dist_06
FROM stock
WHERE (s_i_id, s_w_id) IN (
(31748, 2272),
(49289, 2272),
(59724, 2272),
(78138, 2272),
(82234, 2272),
(90636, 9354),
(96874, 2272),
(98314, 2272))
ORDER BY s_i_id
```

This time the missing row is the one in a different warehouse. Again, the data is definitely present:

```
root@localhost:26257/> select s_i_id, s_w_id from tpcc.stock where (s_i_id, s_w_id) = (90636, 9354);
+--------+--------+
| s_i_id | s_w_id |
+--------+--------+
|  90636 |   9354 |
+--------+--------+
```

Cc @nvanbenschoten, @tschottdorf as this is looking more like a bug in dist sender or below. Any ideas for additional instrumentation to add?

**Comment by petermattis** [comment]
More evidence:

```
12: missing stock row: [8193 8322 12434 30570 43111 43151 49154 54354 56962 65682 69778 93330 ]
SELECT s_i_id, s_quantity, s_ytd, s_order_cnt, s_remote_cnt, s_data, s_dist_03
FROM stock
WHERE (s_i_id, s_w_id) IN (
(8193, 5802),
(8322, 5802),
(12434, 5802),
(30570, 5802),
(43111, 5802),
(43151, 5802),
(49154, 5802),
(54354, 5802),
(56962, 5802),
(65682, 5802),
(69778, 5802),
(93330, 5802),
(98450, 6394))
ORDER BY s_i_id
```

**Comment by petermattis** [comment]
FWIW, this error happens on `master` as well.

**Comment by nvanbenschoten** [comment]
One idea proposed by @arjunravinarayan was to look into whether this is in any way related to DistSQL. We realized in the perf weekly meeting that because the `newOrder` transaction begins with a write which takes place before this read, DistSQL will not be used for the query.

**Comment by petermattis** [comment]
Note that when I'm manually running the query distsql is on. I'll try reproducing again and then manually running with distsql off.

**Comment by nvanbenschoten** [comment]
@petermattis can you confirm whether we've ever seen this on non-partitioned tables?

**Comment by spencerkimball** [comment]
@nvanbenschoten doing a write before read no longer disables distSQL.

**Comment by petermattis** [comment]
This has only occurred on partitioned tables.

**Comment by nvanbenschoten** [comment]
> While adding my own debugging information, I decided to modify the query to output the s_i_id column that it's supposedly ordering by, to figure out which of the rows the query was skipping.

> Un(?)fortunately, this query modification prevented the problem from reoccurring.

@jordanlewis how long did you try to reproduce the issue after making this change? I just confirmed that the queries with and without the added column result in the same spans, so if this does make a difference then it would indicate that we should be looking at the SQL layer.

> doing a write before read no longer disables distSQL

@spencerkimball I was not aware of this, and apparently neither were others in the perf meeting. For posterity, mind pointing to the PR that changed this?

**Comment by petermattis** [comment]
> @jordanlewis how long did you try to reproduce the issue after making this change? I just confirmed that the queries with and without the added column result in the same spans, so if this does make a difference then it would indicate that we should be looking at the SQL layer.

I'm reproducing with the query modification. Jordan was "lucky" in not reproducing it.

**Comment by nvanbenschoten** [comment]
> I'm reproducing with the query modification. Jordan was "lucky" in not reproducing it.

Got it. So you can confirm that the missing `s_i_id` is always from the remote warehouse, right?

**Comment by petermattis** [comment]
> Got it. So you can confirm that the missing s_i_id is always from the remote warehouse, right?

No, it isn't always from the remote warehouse. But there is always a remote warehouse involved in the query.

**Comment by jordanlewis** [comment]
> doing a write before read no longer disables distSQL

@petermattis in that case, can you set `distsql=off` for that query and try to reproduce?

**Comment by petermattis** [comment]
> @petermattis in that case, can you set distsql=off for that query and try to reproduce?

I'm trying that now.

**Comment by spencerkimball** [comment]
@nvanbenschoten https://github.com/cockroachdb/cockroach/commit/dc22c39cb98ebd3ddd8a021e74fb85526e9f16da

**Comment by petermattis** [comment]
Heh, naively turning of distsql for all transactions causes performance to tank. I'm turning it off just for `newOrder`...

**Comment by petermattis** [comment]
Ran for 25m without error with `distsql=off` for the `newOrder` txn, before hitting `error in payment: pq: TransactionStatusError: transaction deadline exceeded`. I'm not sure if this is definitive indication of a problem in `distsql`. Trying again to reproduce.

**Comment by petermattis** [comment]
The fix was https://github.com/cockroachdb/cockroach/pull/23541
