### ISSUE TITLE
sql: implement zig-zag merge join

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#23520]
Consider the following schema and query:

```
CREATE TABLE t (a INT PRIMARY KEY, b INT, c INT);
CREATE INDEX ON t(b);
CREATE INDEX ON t(c);

SELECT * FROM t WHERE b=0 AND c=1;
```

Currently, we plan this with a simple index join, using one of the secondary indexes and the primary indexes.

This can be inefficient. For example, if there are many rows where `b=0` and many rows where `c=1` but only a few where both of those conditions are true, then no matter which index we pick to scan, we will have many rows to search over in the primary index. Therefore, the only way to make this query efficient today is to add an index that contains both attributes.

Zig-zag merge join permits a more efficient way of executing this query. It allows using both secondary indexes to search for the desired intersection by jumping back and forth between the two indexes based on the fact that they share a sorted order in their key suffix. Using this technique, the number of processed results will be roughly equal to the size of the final output set - nonmatching rows will not be fetched at all.

More concretely, since both indexes output a sorted set of primary keys given a fully pinned set of index columns, we can efficiently search both indexes at once by alternating scanning for a join value in one index and looking up in the other.

In context with the example schema above, let's say our secondary indexes contained this:

```
b | a        c | a
------       -----
0   1        1   1
             1   2
             1   3
             1   4
             1   5
             1   6
             1   7
             1   8
             1   9
0   10       1   10
0   11
0   12
0   13       1   13
...
```

In other words, the primary keys 1, 10, and 13 are in the intersection (have `b=0` and `c=1`), the keys 2-9 have `c=1` but `b!=0`, and the keys `11-12` have `b=0` and `c!=1`. In this case, the algorithm would:

1. begin reading from the `b` index for values of `b=0`.
2. notice that the first value on the left side is primary key `1`
3. (zig) begin reading from the `c` index for values of `c=1` and primary key `>=1`
4. output a match, since the `c` side has a value for primary key `=1`
5. continue reading on the `c` side, noticing primary key `2` next
6. (zag) begin reading from the `b` index for values of `b=0` and primary key `>=2`
7. no match: the next key on the `b` side is primary key `10`
8. (zig) begin reading from the `c` index for values of `c=1` and primary key `>=10`

... and so on.

This allows the algorithm to be able to skip over keys `2-9` and `11-12`, which can't happen in the current index join implementation.

I think that the requirements for planning this algorithm are (at least):

1. The join condition is in the suffix part of the key
2. The prefix of all participating indexes is fully specified
3. The suffix part of all participating indexes are sorted in the same order

cc @RaduBerinde, @knz

References:

https://www.youtube.com/watch?v=ofhEyDBpngM
https://cloud.google.com/appengine/articles/indexselection

**Comment by RaduBerinde** [comment]
CC  @andreimatei (we talked about this a few times).

Note that in this example, it's critical that the filter is equality (the results are sorted by PK only within each indexed value).

This technique is also useful for regular joins if the result of the join is significantly smaller than the sizes of the tables.

The execution part is tricky. With distsql, we need to send a "signal" upstream of the dataflow to tell one reader to skip ahead. We also need to "synchronize" the readers so that one is not significantly ahead of the other. Not clear exactly how this would work. A single processor that reads from both sides is probably a more viable option.

**Comment by jordanlewis** [comment]
Another compelling use case for this kind of join is processing inverted index queries with multiple contains conditions. That was discussed here: https://github.com/cockroachdb/cockroach/pull/18992#issuecomment-333964539

Currently, such queries are planned as an index join with a filter for the second contains. With zig-zag merge join, both contains operators could utilize the index.
