### ISSUE TITLE
ts/ui: decommissioned nodes should record one last data point before quitting

### ISSUE THREAD

**Issue by couchand** [cockroachdb/cockroach#23525]
When a user does a `cockroach quit --decommission`, it's possible for the last recorded data point for that node's replicas time series to not be zero, which gives the mistaken impression that the node was quit before being completely drained (as noticed on #21882).  It would be a nice usability win to make sure that the last data point is always zero.  I can imagine a number of ways to do this, but perhaps the simplest is to just hold off on quitting until one time series window has passed after we know it's safe to quit.

cc @mrtracy

**Comment by tschottdorf** [comment]
Nodes can be decommissioned in absentia and often are (after they break), so they wouldn't be able to do it themselves. Similarly, it's hard to decide whether it's fair game to write time series for another node.

It *seems* that once https://github.com/cockroachdb/cockroach/issues/23480 is fixed we won't have a problem here, right? Either the hover wouldn't show a data point for that node at all, or it would indicate its staleness. Both would make any further workaround unnecessary as far as I'm concerned.

**Comment by couchand** [comment]
I think there's still an improvement to be made for the happy case where nodes are decommissioned alive.  If the last data point recorded for number of replicas is non-zero, it potentially raises questions about the trustworthiness of the decommissioning process.

Totally agree about nodes decommissioned when already dead, their series will be all *no data*, and it's easy enough to explain why.
