### ISSUE TITLE
sql: Implement "ESCAPE"

### ISSUE THREAD

**Issue by 0xbaadf00d** [cockroachdb/cockroach#23538]
**FEATURE REQUEST**

Please, implement the keyword `ESCAPE`, it is used by ORM (like ebean or hibernate) when a LIKE predicate is present.

Official PostgreSQL says:

> string LIKE pattern [ESCAPE escape-character]
> string NOT LIKE pattern [ESCAPE escape-character]
> string SIMILAR TO pattern [ESCAPE escape-character]
> string NOT SIMILAR TO pattern [ESCAPE escape-character]
> 
> The default escape character is the backslash but a different one can be selected by using the ESCAPE clause. To match the escape character itself, write two escape characters.

**Query sample:**
```
SELECT * FROM account WHERE first_name LIKE 'bob' ESCAPE '';  -- ORM generated query
SELECT 'A' LIKE '\A' ESCAPE '\';  -- return true
```

**Comment by nvanbenschoten** [comment]
This should be pretty straightforward. `replaceUnescaped` and `unescapePattern` in `eval.go` are both aware of escape tokens already, and @richardwu ensured that this was [thoroughly tested](https://github.com/cockroachdb/cockroach/blob/98ee04b09bb340d63112e044626395648f3cf189/pkg/sql/sem/tree/eval_internal_test.go). However, in practice, this token is [hardcoded](https://github.com/cockroachdb/cockroach/blob/98ee04b09bb340d63112e044626395648f3cf189/pkg/sql/sem/tree/eval.go#L4010) as a backslash. The meat of this task will be threading the optional `escape-character` down from the grammar through the AST to the evaluation function.

**Comment by bdarnell** [comment]
SQLAlchemy 1.2 [uses this feature](http://docs.sqlalchemy.org/en/latest/changelog/migration_12.html#new-autoescape-option-for-startswith-endswith) too.
