### ISSUE TITLE
cmd/workload: adjust tpcc.history.rowid generation

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#23544]
The `tpcc.history.rowid` column appears to be generated using contiguous values. A recent change to the `tpcc` tool (https://github.com/cockroachdb/loadgen/pull/155) switched to using random 63-bit integers for the `rowid` column. We should change the `workload` fixture generation as well otherwise certain parts of the `history` key space have more ranges, which fouls up evenly distributing the key space across the cluster using partitioning.

**Comment by petermattis** [comment]
I just took a brief look at this and I think the current `rowid` generation is actually in import. I think we should change the `tpcc.history` schema to have an explicit `rowid INT PRIMARY KEY` and then populate that column in `workload/tpcc/generate.go:tpccHistoryInitialRow()`. 

@danhhz Does that sound right?

**Comment by danhhz** [comment]
Yes, assuming that replacing a hidden column with an explicit one doesn't break other things (queries). Whoever does this change should remember to bump the Version in the tpcc generator's metadata so we can keep the fixtures straight.

**Comment by petermattis** [comment]
The `tpcc` tool already explicitly fills this column. We'd need to fix `workload/tpcc` to fill it as well.
