### ISSUE TITLE
ui: Network diagnostics page fails to load on single node cluster

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#23552]
Repro steps:

1. Build cockroach from head (I used b6c934ccee6293b697dff5880cf364c2370bf758)
2. Start a single cockroach node against a fresh data directory: `./cockroach start --logtostderr [--insecure]`
3. Go to http://localhost:8080/#/reports/network or https://localhost:8080/#/reports/network depending on whether you're running in secure mode

I've tried this on my macbook running securely as well as on my gceworker running with `--insecure`. Both of them just hang. This is what the linux gceworker page looks like:

<img width="1850" alt="screen shot 2018-03-07 at 2 40 48 pm" src="https://user-images.githubusercontent.com/7085343/37114424-50340860-2216-11e8-9291-9197dea8696f.png">

The logs of both processes repeatedly include this message that may be related:

`W180307 19:43:54.188056 592 server/server.go:1513  [n1] error closing gzip response writer: http: request method or response status code does not allow body`

cc @mrtracy in case @BramGruneir is too busy to look at this soon. This may be related to other, less easily reproducible flakiness I've seen on this page before in larger clusters. Maybe related to #23349, although that involved killing a node whereas this is much simpler to repro.

**Comment by BramGruneir** [comment]
I'm seeing this on our master recently as well.  Without killing any nodes.
Looking into it.
