### ISSUE TITLE
sql: cannot run TRUNCATE on system.locations

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#23584]
From Gitter:

> (10:38) < 0xbaadf00d> I can add location on system.locations, but can't truncate the table
> (10:39) < 0xbaadf00d> 
> ```
> root@:26257/system> TRUNCATE locations;
> pq: user root does not have DROP privilege on relation locations
> ```

(To provide some context for anyone coming to this discussion without that technical background: DROP on a system table is a no-no because the value of the table ID is important)

@vivekmenezes can you triage this

**Comment by knz** [comment]
I advised the user to use DELETE instead

**Comment by vivekmenezes** [comment]
do we think this is a bug?

**Comment by knz** [comment]
I don't know -- it is a UX surprise I'd say. Probably needs to be documented at the least.

Maybe also a fall-back in the code: if TRUNCATE is issued on a system table, then fall back to the DELETE code.

**Comment by dt** [comment]
I don't think this is specific to the system tables at all -- having only CRUD privs seems pretty likely in which case you'd be allowed to run `DELETE FROM foo` but not `TRUNCATE foo`.

**Comment by dt** [comment]
-1 on silently downgrading a `TRUNCATE` to a `DELETE`: they have _very_ different performance characteristics, so I'd definitely prefer to predictably do what I asked or refuse, not maybe go do something else that has very different implications, all unbeknownst to me.

**Comment by knz** [comment]
The alternative is to have TRUNCATE check the DELETE permission instead of DROP.

**Comment by dt** [comment]
postgres has a separate `truncate` permission fwiw.

**Comment by knz** [comment]
that might be even better then.

**Comment by petermattis** [comment]
I thought we couldn’t truncate system tables because truncate is
implemented as drop and recreate which implies a new table ID and the
system table IDs are hard coded.

**Comment by knz** [comment]
Peter yes you're right (there's a sentence at the top level of this issue that reminds the reader of that)

But the core of the issue here is that a user expects TRUNCATE to delete rows, not to drop the table, and will be surprised by seeing a message related to DROP. There should be something better happening here.

**Comment by dt** [comment]
Yep, even if we did switch to `TRUNCATE` requiring its own privilege rather than DROP+CREATE, we still wouldn't grant it on the system tables for that reason.

**Comment by mberhault** [comment]
I would prefer to move the other direction and disallow all direct modifications to the system tables. This would require disallowing even `root` from writing to them, changing everything to use internal ops run by `node` (or a new user). See https://github.com/cockroachdb/cockroach/issues/19277 for details.

**Comment by knz** [comment]
would work for me, but then we need a proper user story for `system.locations`.

**Comment by mberhault** [comment]
I agree, it would need utility functions to manipulate locations through sql.

**Comment by dianasaur323** [comment]
yeah, the system.locations thing was a bandaid solution we put in in lieu of having something better. Going into 2.1, I think we should 1) bring it into SQL and 2) consider allowing manipulation at the admin UI level. 

cc @piyush-singh for prioritization.

**Comment by couchand** [comment]
+1 for making this editable from the admin ui, but I maintain that it's unwise to make an exception to the security model, so we would need login first.

**Comment by dianasaur323** [comment]
+1 more points for user login!

**Comment by jordanlewis** [comment]
Closing as wont fix.
