### ISSUE TITLE
roachtest: rebalance/3to5 failure

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#23612]
https://teamcity.cockroachdb.com/repository/download/Cockroach_Nightlies_WorkloadNightly/552108:id/20180308-552108/rebalance/3to5/test.log

```
last range event: split for range 5/store 4 (3m0.331681s ago)
num replicas stddev = 18.308468, max = 10.000000
cluster took 2h35m1.374368s to rebalance
2830 range events
```

@a-robinson Not sure why we didn't achieve the desired balance. Do we have to relax the passing criteria?

**Comment by a-robinson** [comment]
The standard deviation for the test is too low. We used to run the 3to5 test with an acceptable standard deviation of 42: https://github.com/cockroachdb/cockroach/blob/3748d21f9fd9cb1f0d9f7f0a2a720f599aa52ee5/build/teamcity-nightly-acceptance.sh#L38

Although the output of this test is no longer enough to properly debug it. Is there an option to set the `-vmodule` of roachtest tests to maintain the previous level of output? Are the node logs even collected for these tests? It's not clear whether the log you linked to is all the output for the test or if there's more somewhere else that I haven't been able to find.

I can add extra logging to the test itself on failures, such as dumping the `system.rangelog` table on failure, if running at higher verbosity would be tough with the current infrastructure. Let me know, @danhhz.
