### ISSUE TITLE
roachtest: schemachange test failure

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#23613]
https://teamcity.cockroachdb.com/repository/download/Cockroach_Nightlies_WorkloadNightly/552108:id/20180308-552108/schemachange/test.log

```
running schema changes over test.kv
starting schema change: ALTER TABLE test.kv ADD COLUMN created_at TIMESTAMP DEFAULT now()
hit schema change error: pq: relation "test.kv" does not exist, for ALTER TABLE test.kv ADD COLUMN created_at TIMESTAMP DEFAULT now(), in 839.947Âµs
```

@danhhz Assigning to you for triage as the error above seems like a problem with the test. If it isn't feel free to reassign.

**Comment by danhhz** [comment]
Closed by #23615.
