### ISSUE TITLE
sql: make it possible to specify the order of aggregations

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#23620]
I was documenting ORDER BY in https://github.com/cockroachdb/docs/pull/2658 and I realized we don't have a reliable way to determine in which order aggregations are performed. This matters because we have non-commutative aggregation functions (`array_agg`, `concat_agg`).

@RaduBerinde says:

> Regarding array_agg and concat_agg - strictly speaking (SQL standard), I don't think they need to respect the datasource ordering. But in practice, I'm guessing people expect it. Postgres doc says "it will usually work" but notes that it's not portable; the recommended way is to use an ORDER BY clause inside the aggregate function call: `SELECT array_agg(a ORDER BY b DESC) FROM table`, which we don't support.

CockroachDB should be extended to support the syntax `SELECT <aggfunc>(<column> ORDER BY ...)`.

cc @rytaft @andy-kimball

**Comment by knz** [comment]
Currently CockroachDB recognizes the syntax but drops the ORDER BY specification on the floor, which is even arguably worse.

**Comment by knz** [comment]
One step further:

1) I changed CockroachDB to reject the syntax `agg(x order by y)` until it's actually supported

2) I asked a user on gitter what they think about this.

> <@knz> currently, _by accident_ it seems that `select concat_ws(x) from (select x from ... order by x)` appears to do it
> <@erichocean> oh, that's a nice way to do it
> <@knz> or `select concat_ws(x) from (select x from ... order by y)`
> <@knz> *but*
> <@knz> however
> <@knz> the standard SQL way to do it is `select concat_ws(x order by y) from ...`
> <@knz> (which is not yet supported by cockroachdb)
> <@erichocean> wow, I didn't even know that was legal
> <@erichocean> [...]
> <@knz> the reason why this latter syntax exists
> <@knz> is that you can want different orders for different aggregations
> <@knz> for example `select agg1(x order by y), agg2(x order by z) from ...`
> <@erichocean> did you learn that in a class called: How to write glacially slow SQL?
> <@knz> hahaha
> <@knz> I certainly hope cockroachdb grows to make that non-slow :)
> <@erichocean> I really like the way it works now.
> <@erichocean> logically, I think of a result set, and then I do the agg on it
> <@knz> the reason why _we_ don't like it is that it breaks some other important optimizations
> <@erichocean> so `select concat_ws(x) from (select x from ... order by y)` is really readable to me
> <@knz> yeah
> <@knz> to me too.

**Comment by knz** [comment]
This conversation strongly suggest that we could intendedly extend the SQL standard and make non-commutative aggregations respect the ordering of their immediate data source, if there's no other relational operator. 

Is there a way to make this work without too much architectural churn / special casing in the optimizer?

**Comment by rytaft** [comment]
I believe this is what @justinj already mostly implemented in https://github.com/cockroachdb/cockroach/pull/24815

**Comment by knz** [comment]
#24815 would preserve any implicit ordering not just the explicit orderings. I'd rather we document that we preserve explicit orderings and make it a hard requirement of future implementation changes. @justinj thoughts?

**Comment by rytaft** [comment]
I believe #24815 is already doing this correctly - we only set the `Ordering` property in the `optbuilder` if there is an explicit `ORDER BY` clause.  Whether or not a source actually provides that ordering or requires an explicit sort is determined later in the optimizer.

**Comment by justinj** [comment]
Yeah, that PR was only ever about explicit orderings, from the PR description:

>This commit allows inputs which have an explicit ordering to have that
>ordering be passed up to the group by.

**Comment by andy-kimball** [comment]
Following up here: we now respect the `ORDER BY` clause when used with aggregations that are sensitive to order. We don't yet support `ORDER BY` as a clause within the aggregate function.

**Comment by awoods187** [comment]
This was the top requested feature based upon telemetry data and we should consider including in 2.2

**Comment by knz** [comment]
Question from Gitter:

> @mikedamm Is this still in the pipeline for 2.2?

@andy-kimball care to comment?

**Comment by knz** [comment]
OK But then to whomever will look into this in the code: **do not close this issue when a PR to support just 1 ordering is merged** -- and also be careful to keep the "unimplemented error" reported and pointing to this issue when more than 1 ordering is requested.
