### ISSUE TITLE
sql: provide a way to temporarily disable foreign key checks on a session basis

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#23624]
MySQL provides an option `SET FOREIGN_KEY_CHECKS=0;` which temporarily disables all foreign key checks on a session basis. This would be useful to have in CockroachDB as well.

**Comment by bdarnell** [comment]
How does this relate to DEFERRABLE constraints (#9897)?

**Comment by dt** [comment]
Also curious if the proposed functionality in #19444 meets the same use case.

**Comment by dt** [comment]
Specifically, if we did add a session setting like this instead of the DISABLE ALL mutation on the tables, I think it should a) require ALTER on the tables it writes to and b) must mark all FKs it ignores as unvalidated, if they’re not already, since it may have invalidated them.

**Comment by jordanlewis** [comment]
Oops. Dupe of #19444. This came up in context of testing TPCC - it would be nice to be able to disable foreign key checks via a session setting to test performance with and without those checks.

**Comment by jordanlewis** [comment]
Oh, wait. No, this is specifically about a session setting that evilly skips validating foreign key constraints regardless of the state of the schema.

https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_foreign_key_checks

> Setting foreign_key_checks to 1 does not trigger a scan of the existing table data. Therefore, rows added to the table while foreign_key_checks=0 will not be verified for consistency.

**Comment by knz** [comment]
@jordanlewis can you clarify what the use case is? It sounds a bit like "I want a tool to shoot myself in the foot"

**Comment by BramGruneir** [comment]
I don't think this is a good idea.  The only use case I can think of is for bulk inserts to existing already partially filled tables.

Mysql has this option because they don't have `deferred`.  But if I recall, when you turn fk checks back on, it doesn't then go perform them all.  It just assumes you know what you're doing.

I covered this in https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20171201_cascade.md

See the https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20171201_cascade.md#survey-of-other-databases for how they all deal with it.

**Comment by dt** [comment]
I do not think we should implement it exactly as mysql does -- *just* disabling the check code. I think,  if you've chosen to not check FKs at all, we need to record on those FKs that we can no longer make promises about their on-disk data... until you run `VALIDATE CONSTRAINT` to re-assert that they're okay.

**Comment by petermattis** [comment]
This issue arose from a desire to temporarily disable the FK checks in order to determine their performance impact. I could be satisfied with an easy way to do this via recompilation. @jordanlewis pointed out that MySQL has a setting for it. I have had this desire, I imagine users might as well. It seems reasonable to make it clear how absolutely dangerous this setting is.

**Comment by dt** [comment]
👍 it does indeed seem like a not uncommon desire to quantify the cost of checking constraints. To clarify my concern, I'm not opposed to disabling checks, but rather to, on that re-enabling them the database should not make potentially false claims.

**Comment by petermattis** [comment]
@dt Agreed. Either we need to document that the foreign keys might be invalid, or provide a mechanism for re-validating them.

**Comment by dt** [comment]
Yep, we have that mechanism for re-validating -- `VALIDATE CONSTRAINT` -- that can be run on constraints in the `UNVALIDATED` state, which is when we enforce the constraint on new writes but cannot vouch for it on-disk until validated.

**Comment by knz** [comment]
Related: #23663 

you may want to extend the mechanism to also disable CHECK validation

**Comment by knz** [comment]
Re-thinking this with a cool head, I realize that if any one session would enable the setting to disable FK checks, then FK constraints potentially become invalidated for _every_ other session, not just the one.

For me this 100% turns this feature into a cluster-wide setting.

Also the action of changing the setting from "on" (no FK checks) back to "off" (FK checks enabled) should edit _all_ the table descriptors to mark constraints as `UNVALIDATED`.

**Comment by knz** [comment]
Also, should a client violate the FK constraints, this means the table stats would go out of whack, and the query optimizer would subsequently start to make very bad choices.

**Comment by knz** [comment]
(I'm overall :-1: on this feature due to the disorderly spill of invalidity)

**Comment by knz** [comment]
Anyone who further looks into this **please** carefully envision the interaction with a user who mistakenly sets this and starts (unintendedly) corrupting their database.

How would **you** explain this user how to put their database back into a valid state? How do you suggest they identify which writes were violating their FK constraints? How do you suggest they go back in history to fix/remove these writes (made with the setting enabled) and no other (made with the setting enabled)?

**Comment by knz** [comment]
The UX story here in the "bad case" is so supremely horrendous that it makes me shudder.

Perhaps we should requalify this issue to become a **build flag** instead.

**Comment by dt** [comment]
@knz fwiw, I think it also makes sense to consider https://github.com/cockroachdb/cockroach/issues/19444 as an alternative -- disabling the FKs *themselves* in the schema via a schema change command. That makes it readily apparent that they're disabled to all observers, unlike per-session state, and has clear semantics for what happens after: re-enabling them is done explicitly and can include (perhaps with an option) re-validation.

**Comment by knz** [comment]
Yes  #19444 sounds much saner to me.

**Comment by dt** [comment]
I think we should close this, and if we want the ability to disable constraints checking, pursue the approach in #19444. 

I still think #19444 is a safer, less foot-gun solution to the underlying desire to temporarily disable constraints for performance reasons, but given that constraints are making promises about the table data, recording that they're disabled _on the table_ seems much safer to me than just in one client's in-memory session.

**Comment by knz** [comment]
agreed
