### ISSUE TITLE
build: QA actual binaries intended for release

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#23621]
Capturing some in-persion discussion.

Goals:
We want to QA the actual binary we plan to release.
We want the "release" itself to just be a matter of copying the QA'ed binary into the public bucket and publishing the tag and notes.
We want the binary, during QA to report errors or crashes in an easy to identify way.

Our current plan:
- A CI job that you can trigger with parameters for the desired revision and tag as which it will be released. That CI will bake a binary that believes it *is* that version (overriding the usual `git describe`), have the channel and other meta-data baked in all as if it is the release binary. We push it to the release-test bucket.
- QA (deploying to the clusters, running roachtest, etc) will be done with the binary downloaded from the release-test bucket.
- When QA is complete, we click a deploy job button on that CI that pushes the artifact to the real bucket as well and pushes the tag to GitHub (and maybe updates reg too?)

Error reporting will switch to be controlled by the official channel value, and will report to sentry with its `environment`  (which sentry expects to be something like "production" or "staging" and around which sentry has built the most filtering) as the baked in version, with the exception that it will truncate  extra `git describe` suffixes down to just `-dev` -- it will still have the original SHA in the `rev` field for more specific identification if needed, but this should make it easier to identify the new actual betas.

**Comment by dt** [comment]
worked on the error reporting part in #23631.

**Comment by knz** [comment]
@bdarnell @danhhz I think you recently addressed this, right?

**Comment by danhhz** [comment]
Oh I didn't even know we had an issue for this. I have partially addressed it. The 2.2 alpha going out today was tested with the new process, but I still have to actually do the bit where I mark the binary as final. I wasn't able to get to switching over the roachtests, so there's a bit more work to do before closing this out.

**Comment by jlinder** [comment]
Closing this issue. The [new release process](https://github.com/cockroachdb/cockroach/issues/50955) we are rolling out now supersedes this. (It's creating nearly the same binary for qualification / QA as for release with the one difference being the version name.)
