### ISSUE TITLE
ui: cluster viz label "cluster" hops around

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#23662]
This is a UI nit, and in no way high priority, but on the node map, when I change the time selector, the middle title "Cluster" seems to budge around a little. 

cc @piyush-singh

**Comment by couchand** [comment]
Yes, we were fighting with this for a while.  Low priority, but if we get a chance to clean up that header (it's kind of hacky in a few ways) it would be nice to figure this out.

**Comment by piyush-singh** [comment]
Given the amount of work we have remaining for 2.1 and that this is low priority, moving milestone to "Later" for now.
