### ISSUE TITLE
go test ./sql/driver/... -count=100 fails

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#2366]
It fails in TestOverlappingTransactions where the second transaction fails every once in a while.

**Comment by tschottdorf** [comment]
> F0904 17:44:11.049706 10255 sql/driver/driver_test.go:325  txn "sql/server.go:104 sql" id=55162289 key="\xff\n\x02\n\x01\tt\x00\x01\n\x03" rw=false pri=10.06285353 iso=SERIALIZABLE stat=PENDING epo=0 ts=1441403050.665928364,0 orig=1441403050.665928364,0 max=1441403050.665928364,0 failed to push "sql/server.go:104 sql" id=48199f86 key="\xff\n\x02\n\x01\tt\x00\x01\n\x03" rw=true pri=95.21316518 iso=SERIALIZABLE stat=PENDING epo=0 ts=1441403050.665928364,1 orig=1441403050.658169746,0 max=1441403050.658169746,0

**Comment by tschottdorf** [comment]
I'm not sure about this test. I don't see any priorities set, so whether the second or first transaction wins depends on their relative priorities, which are random. Am I missing something or is this test just flaky by design?

**Comment by vivekmenezes** [comment]
Yeah, turns out it is flaky by design (depend on random priorities). In
fact the test as such is not testing anything at the SQL layer. It's more
like documentation for what we can expect when SQL transactions overlap.
Part of me feels like we should just kill this test and depend on
transaction related tests at the KV layer. The other half tells me that we
should kill this test in favor of a benchmark that reveals what this test
occasionally reveals like long multi second stalls during conflict.

Anyone opposed to just nuking it at this stage. We can develop a better
benchmark later when we are focusing on performance.

**Comment by vivekmenezes** [comment]
One option is to convert this test into a test that tests for
serializability like the one in client/client_test.go. While again that
wouldn't really be testing anything new, it will at least give us
confidence that serializability is working at the SQL layer (the layer
users are using). It will be valuable to be able to point a user at a SQL
test that tests serializability when they look at us in disbelief.

**Comment by vivekmenezes** [comment]
I'm going to just delete this test. Peter's benchmark runs many
transactions in parallel and tests serializability.
