### ISSUE TITLE
sql: enable checking CHECK constraints on existing rows

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#23663]
When a CHECK constraint is added to a table that already has some rows, the constraint is not validated for the existing rows.

This is unintuitive and diverges from the behavior with foreign key.

There should be a way to have the constraints validated for exisiting rows, like we can do for FKs.

**Comment by dt** [comment]
er, really isn't that what https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/alter_table.go#L201 is doing?

**Comment by dt** [comment]
@knz can you add steps to reproduce to the issue?

**Comment by knz** [comment]
It's fixed indeed. I was mislead by our current documentation. Sorry for the noise.
