### ISSUE TITLE
odd error message when dropping database

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#23661]
I ran the following commands: 

```
root@:26257/registration> drop database registration cascade;
DROP DATABASE

Time: 8.089766625s

warning: error retrieving the database name: pq: database "registration" does not exist
```

The drop ran successfully, but I'm not sure why I get an error message afterwards?

Running show databases confirms that the database is gone.

**Comment by dt** [comment]
I'm guessing this has to do with it being your current session DB and the cli's state polling that @knz added?

**Comment by knz** [comment]
The problem is that your current database is "registration" and you're just deleting that database.

I think I may fix this error by preventing a DROP in the CLI if the current database is the one being dropped.

**Comment by dianasaur323** [comment]
Yeah, I think you're right. I think another option is to DROP the database and then automatically punt the user back to the schema level (is that what we are calling it now)?
