### ISSUE TITLE
ui: overview: total ranges count runs out of space when too high

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#23669]
Version: v2.0-beta.20180305-204-g7c7b179

![screenshot 2018-03-09 12 15 58](https://user-images.githubusercontent.com/882976/37220134-a25bb86c-2393-11e8-8034-c74629dd5bb1.png)

The cluster overview looks a little funky when the number of ranges has five digits—it runs right into the underreplicated stats.

The capacity usage on this cluster is also broken. I'll file a separate issue for that, but the cluster overview should also not try to render a capacity that's greater than 100%.

@couchand for triage.

**Comment by vilterp** [comment]
Wow, how did you get your cluster into a state where it reports using 626% of available capacity?

**Comment by petermattis** [comment]
> Wow, how did you get your cluster into a state where it reports using 626% of available capacity?

Happens every time. I think there must be a simple math bug somewhere in the UI or backend.

**Comment by petermattis** [comment]
In particular, from another part of the UI we have:

```
You are using 2.1 TiB of 356.6 GiB usable storage capacity across all nodes.
```

The 2.1 TiB number is accurate, but the 356.6 GiB number looks like the capacity for a single node and there are 24 nodes in this cluster.

**Comment by vilterp** [comment]
Forgot a plus sign. Fix (and a unit test) coming up.

```diff
diff --git a/pkg/ui/src/redux/nodes.ts b/pkg/ui/src/redux/nodes.ts
index fb16f0723..7391f2c7a 100644
--- a/pkg/ui/src/redux/nodes.ts
+++ b/pkg/ui/src/redux/nodes.ts
@@ -181,7 +181,7 @@ export function sumNodeStats(
 
         result.capacityUsed += used;
         result.capacityAvailable += available;
-        result.capacityUsable = usable;
+        result.capacityUsable += usable;
         result.capacityTotal += n.metrics[MetricConstants.capacity];
         result.usedBytes += BytesUsed(n);
         result.usedMem += n.metrics[MetricConstants.rss];
```

**Comment by petermattis** [comment]
Oops!

**Comment by piyush-singh** [comment]
@josueeee flagging for your attention.
