### ISSUE TITLE
ui: jobs page: job text can overflow cell bounds

### ISSUE THREAD

**Issue by vilterp** [cockroachdb/cockroach#23679]
Collapsed:
![image](https://user-images.githubusercontent.com/7341/37226935-8e3424e4-23a9-11e8-8904-298568bd70b8.png)

Expanded:
![image](https://user-images.githubusercontent.com/7341/37226942-9207fe38-23a9-11e8-9f6b-88a5f808902f.png)

Doesn't get any better even when the window is expanded to have plenty of space:
![image](https://user-images.githubusercontent.com/7341/37226877-5a43cb1c-23a9-11e8-8351-d4e54654b50c.png)

**Comment by vilterp** [comment]
@couchand I think you've suggested in the past that the solution is to break out the fields of the job descriptor. But we've gotta do something here, even if it's basic text layout and overflow styling tweaks.

**Comment by vilterp** [comment]
Note about showing a structured representation: it'll take some backend endpoint rejiggering to get the details we want, since the current endpoint is based on the `crdb_internal.jobs` table, which doesn't expose the details we need here (URL, etc):

https://github.com/cockroachdb/cockroach/blob/a26506b90889899b7087a939b7349b57cec5cfbd/pkg/sql/crdb_internal.go#L382-L396

**Comment by vilterp** [comment]
Knew I had seen this before. Dup of #23499.

**Comment by couchand** [comment]
> it'll take some backend endpoint rejiggering

Yep, that's why it's not been started yet!  Thanks for looking into this.
