### ISSUE TITLE
build: Open Source build needs CI enforcement

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#23677]
Originally, our rule was that you can delete the ccl directory(s) to get an unencumbered source tree, and then run `make buildoss` to get an untainted binary from that tree, sure that all source linked was APL2 licensed. We verified that by hand at times, but it looks like it's rotted over time:
```
$ find . -name *ccl -exec rm -rf {} + ;
$ make buildoss

GOPATH set to /Users/david/go
find: ./pkg/ui/ccl: No such file or directory
Running make with -j8
/bin/bash: pkg/ccl/storageccl/engineccl/zcgo_flags.go: No such file or directory
/bin/bash: pkg/ccl/storageccl/engineccl/zcgo_flags_x86_64_apple_darwin17.3.0.go: No such file or directory
make: *** [pkg/ccl/storageccl/engineccl/zcgo_flags_x86_64_apple_darwin17.3.0.go] Error 1
make: *** Waiting for unfinished jobs....
make: *** [pkg/ccl/storageccl/engineccl/zcgo_flags.go] Error 1
```

We currently only have one CI, that primarily tests against ccl binaries: While we've discussed at times that we at some point may want CIs testing pure-OSS builds -- i.e. running tests against binaries that don't link ccl code and thus lack the potential side effects of doing so.  So far however we've said that those side effects are still reasonably restricted to the ccl features, and thus we're comfortable vouching for non-ccl functionality's correctness when it is tested in a ccl binary.

At the very least though, we should add CIs that ensure that the pure-OSS build process that we expect to work (currently `delete *ccl` + `make buildoss`) doesn't rot.

**Comment by dt** [comment]
Looks like a `mkdir -p pkg/ccl/storageccl/engineccl` lets it advance.

Looks like `CGO_FLAGS_FILES` has a mix of ccl and oss directories, and breaking that up and then depending on the right ones might be kinda annoying -- might be easier just to change the "rule" to from "can delete all *ccl directories" to "can delete all files in *ccl directories"  to get an untainted source tree and binary.

**Comment by benesch** [comment]
Yeah, we've let this rule slip over time. The build problems get even worse if you remove `c-deps/libroach/ccl`, because CMakeLists.txt will utterly blow up if you remove source files it expects. So we'd have to split that CMakeLists.txt into two, which would slow down the CCL build (though arguably not that much).

If we care about this property we definitely need CI enforcement.
