### ISSUE TITLE
storage: hung AdminSplit request during restore

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#23673]
A tpcc `RESTORE` hung because an `AdminSplit` request is never finishing. The stuck `AdminSplit` operation is continually retrying and never succeeding. The problematic range was discovered by download all of the logs from the cluster and running:

```
grep split *.logs/*.log | egrep -o -w 'r[0-9]+' | sort | uniq -c | sort -rn | head
```

This revealed that `r50573` had been mentioned in split logs thousands of times. Grep'ing the logs further shows:

```
I180309 17:39:51.461610 355025 storage/replica_command.go:838  [n13,s13,r50573/3:/Table/56/1/72{32/2/…-47/2/…}] initiating a split of this range at key /Table/56/1/7234/1/-1785/9 [r59635]
I180309 17:39:52.490205 355025 storage/replica_command.go:838  [n13,s13,r50573/3:/Table/56/1/72{32/2/…-47/2/…}] initiating a split of this range at key /Table/56/1/7234/1/-1785/9 [r59636]
I180309 17:39:53.506252 355025 storage/replica_command.go:838  [n13,s13,r50573/3:/Table/56/1/72{32/2/…-47/2/…}] initiating a split of this range at key /Table/56/1/7234/1/-1785/9 [r59637]
I180309 17:39:54.618152 355025 storage/replica_command.go:838  [n13,s13,r50573/3:/Table/56/1/72{32/2/…-47/2/…}] initiating a split of this range at key /Table/56/1/7234/1/-1785/9 [r59638]
I180309 17:39:55.574723 355025 storage/replica_command.go:838  [n13,s13,r50573/3:/Table/56/1/72{32/2/…-47/2/…}] initiating a split of this range at key /Table/56/1/7234/1/-1785/9 [r59639]
I180309 17:39:56.438992 355025 storage/replica_command.go:838  [n13,s13,r50573/3:/Table/56/1/72{32/2/…-47/2/…}] initiating a split of this range at key /Table/56/1/7234/1/-1785/9 [r59640]
```

So we're trying to split `r50573` every second and failing. The range debug page reveals a problem:

![screen shot 2018-03-09 at 12 49 02 pm](https://user-images.githubusercontent.com/6201335/37221513-4bac79fc-2398-11e8-9f00-cf338234672f.png)

The node trying to perform the split is `n13`, but the range doesn't have a replica on that node. Further down on the range debug page we have:

![screen shot 2018-03-09 at 12 50 00 pm](https://user-images.githubusercontent.com/6201335/37221544-662fa718-2398-11e8-8473-3bc5a7bb3457.png)

So at `17:07:13` the replica on `n13` was removed. `n13` seemed to be having trouble around this time:

```
W180309 16:59:02.672418 358035 storage/node_liveness.go:501  [n13,s13,r9881/1:/Table/58/1/25{5/305…-6/348…}] slow heartbeat took 60.0s
E180309 16:59:02.672429 358035 storage/replica_range_lease.go:282  [n13,s13,r9881/1:/Table/58/1/25{5/305…-6/348…}] context canceled
```

The `liveness.heartbeatfailures` metric indicates that there was only a single heartbeat failure on the cluster which happened at `17:07:15`. 

Independent of the liveness heartbeat failure, `AdminSplit` shouldn't be getting stuck. I haven't traced through what error `Replica.AdminSplit` is looping on. Seems easy enough to generate this scenario in a test. Should `ReplicaCommand.AdminSplit` have a check in its loop that it is still the leaseholder?

**Comment by bdarnell** [comment]
Yeah, AdminSplit should probably check that it's still the leaseholder. (It doesn't *have* to be the leaseholder as long as it's still a member, but it's probably better to check for the lease than for membership)

**Comment by nvanbenschoten** [comment]
> Yeah, AdminSplit should probably check that it's still the leaseholder.

Agreed. There should be a check at the top of `adminSplitWithDescriptor` to verify this.

> It doesn't have to be the leaseholder as long as it's still a member, but it's probably better to check for the lease than for membership.

I think even this could result in the infinite looping we saw here if the replica performing the AdminSplit was a follower that had fallen behind and missed an update to its range descriptor. In this case, the initial CPut to update the range's local descriptor could indefinitely hit a `ConditionFailedError` error. 

The more dramatic variant of this where the follower has been removed from range entirely and therefore missed at least one range descriptor update is what I suspect we hit here.

**Comment by bdarnell** [comment]
> I think even this could result in the infinite looping we saw here if the replica performing the AdminSplit was a follower that had fallen behind and missed an update to its range descriptor. In this case, the initial CPut to update the range's local descriptor could indefinitely hit a ConditionFailedError error (which is retried).

This should still be finite in practice as a replica that can't keep up should get removed from the range. (although I don't know if we currently act on this specifically in the allocator)
