### ISSUE TITLE
losing transactions in BenchmarkBank

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#2368]
via @petermattis from #2364:

Run as:

```
go test -run - -bench BenchmarkBank -vmodule=bank_test=1
```

Fairly quickly, you'll see log messages like:

```
I0904 13:34:59.427848 25874 stopper.go:229  draining; tasks left:
2      kv/txn_coord_sender.go:466
```

That number takes seconds to drop to 0 (on the scale of the client inactivity timeout, pointing at abandoned heartbeat goroutines).

**Comment by tschottdorf** [comment]
it appears that the rollback fails in some cases. I see the call to `rollbackTxnAndReturnResultWithError` as much as I expect, but it appears that `planMaker.txn` is `nil` sometimes (though there aren't any non-txns in that code).

**Comment by tschottdorf** [comment]
this code here looks suspicious:

```
func (p *planner) CommitTransaction(n *parser.CommitTransaction) (planNode, error) {
	err := p.txn.Commit()
	// Reset transaction.
	p.txn = nil
	return &valuesNode{}, err
}
```

This means that if the commit fails, there's no transaction (and it's quite expected that a commit fail).

**Comment by tschottdorf** [comment]
setting to `nil` only when there's no error doesn't fix the issues, instead spits out a bunch of errors which indicate that we're trying to cancel transactions which aren't tracked by the coordinator.
Will have to dig deeper but it looks like we need more testing coverage for those things.

**Comment by vivekmenezes** [comment]
Tobias, Do we need to call rollback explicitly if p.txn.Commit() fails?

**Comment by bdarnell** [comment]
Depends on the type of failure. If it's a `TransactionRetryError`, then the transaction's timestamp has been pushed, but the transaction is still open. When this happens, you're expected to retry the entire transaction from the beginning, but reuse the same transaction ID. If you can't (and I'm not sure we can in SQL), then you'll have to abort the transaction explicitly. For other kinds of error, the transaction has been aborted and closed on the server, so there is no need to explicitly abort.
