### ISSUE TITLE
panic encountered when ctrl+c-ing a query

### ISSUE THREAD

**Issue by arjunravinarayan** [cockroachdb/cockroach#23694]
I have a 4 node roachprod cluster with a TPC-C 100 warehouse dataset, loaded with
` bin/workload fixtures load tpcc  --warehouses=100 'postgres://root@35.190.154.175:26257?sslmode=disable'`

I ran the following query:
`(SELECT ol_w_id, ol_d_id, ol_o_id FROM order_line WHERE ol_delivery_d IS NULL ORDER BY ol_w_id, ol_d_id, ol_o_id DESC)                                                         EXCEPT ALL                                                                                                                                                                                                  (SELECT o_w_id, o_d_id, o_id FROM "order"@primary ORDER BY o_w_id, o_d_id, o_id DESC)`

After approximately 10 seconds, I knew I had done something wrong in constructing my query since I wanted a query that finished quickly, so I ctrl+c-ed out. This caused the node to crash with the following log message:

```
E180310 00:22:29.377528 917 sql/conn_executor.go:512  [n1,client=10.142.0.10:60920,user=root] a SQL panic has occurred while executing "(SELECT ol_w_id, ol_d_id, ol_o_id FROM order_line WHERE ol_delivery_d IS NULL ORDER BY ol_w_id, ol_d_id, ol_o_id DESC) EXCEPT ALL (SELECT o_w_id, o_d_id, o_id FROM \"order\"@primary ORDER BY o_w_id, o_d_id, o_id DESC)": can't overwrite err: write tcp 10.142.0.9:26257->10.142.0.10:60920: write: connection reset by peer with err: write tcp 10.142.0.9:26257->10.142.0.10:60920: write: connection reset by peer
E180310 00:22:29.377757 917 util/log/crash_reporting.go:182  [n1,client=10.142.0.10:60920,user=root] a panic has occurred!
E180310 00:22:29.378065 917 util/log/crash_reporting.go:440  [n1,client=10.142.0.10:60920,user=root] Reported as error 8f4f265d29474b49881eea0716a63983
panic: can't overwrite err: write tcp 10.142.0.9:26257->10.142.0.10:60920: write: connection reset by peer with err: write tcp 10.142.0.9:26257->10.142.0.10:60920: write: connection reset by peer [recovered]
        panic: panic while executing 1 statements: (SELECT _, _, _ FROM _ WHERE _ IS _ ORDER BY _, _, _ DESC) EXCEPT ALL (SELECT _, _, _ FROM _@_ ORDER BY _, _, _ DESC); caused by can't overwrite err: write tcp 10.142.0.9:26257->10.142.0.10:60920: write: connection reset by peer with err: write tcp 10.142.0.9:26257->10.142.0.10:60920: write: connection reset by peer

goroutine 917 [running]:
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc426576000, 0x2661c60, 0xc426a08500, 0x2038c00, 0xc426da0110)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:526 +0x365
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func2(0xc426576000, 0x2661c60, 0xc426a08500)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:487 +0x61
panic(0x2038c00, 0xc426da0110)
        /usr/local/go/src/runtime/panic.go:505 +0x229
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*commandResult).SetError(0xc4265c8c80, 0x2643460, 0xc424f10190)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/command_result.go:187 +0x134
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc426576000, 0x2661c60, 0xc420b2dac0, 0x26645a0, 0xc420b2da40, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:556 +0x853
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc426576000, 0x2661c60, 0xc420b2dac0, 0x26645a0, 0xc420b2da40, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:342 +0x9c7
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc426576000, 0x2661c60, 0xc420b2dac0, 0x26645a0, 0xc420b2da40, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:83 +0x358
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc426576000, 0x2661c60, 0xc426a08500, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:908 +0x1cc8
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc4203d7dc0, 0x2661c60, 0xc426a08500, 0xc426573054, 0x8, 0xc426573009, 0x4, 0x0, 0x0, 0x264b120, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:489 +0xf53
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl.func3(0xc4203d7dc0, 0x2661c60, 0xc426a08500, 0xc420349500, 0x5400, 0x15000, 0xc420a42cd0, 0xc426e52690, 0xc426cd8c50, 0xc426e52680)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:260 +0xfc
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:259 +0xf14
(END)

```

The cockroach binary is the current head of the release-2.0 branch, so this is worrying:
```
Build Tag:    v2.0-beta.20180305-206-g2329ca0
Build Time:   2018/03/09 15:55:07
Distribution: CCL
Platform:     linux amd64
Go Version:   go1.10
C Compiler:   4.2.1 Compatible Clang 3.8.0 (tags/RELEASE_380/final)
Build SHA-1:  2329ca0f1e926bb7dba8abd558bc4631bbddd04c
Build Type:   development
```

Assigned to @jordanlewis for triage.

**Comment by arjunravinarayan** [comment]
One interesting curiosity is that the following query does not cause a crash:

`(SELECT ol_w_id, ol_d_id, ol_o_id FROM order_line WHERE ol_delivery_d IS NULL ORDER BY ol_w_id, ol_d_id, ol_o_id DESC)                                                         EXCEPT ALL                                                                                                                                                                                                  (SELECT o_w_id, o_d_id, o_id FROM "order"@primary ORDER BY o_w_id, o_d_id, o_id DESC) LIMIT 1`

This is because the hard limit causes a completely different plan that is not distributed. Consider [the crashing query plan](https://cockroachdb.github.io/distsqlplan/decode.html?eJzkllFr2zAQx9_3Kcw9bVSFSMrSxTDwGB0EuqS0GQyGGW58SwyuZSQFFkq--7A9ltjNdAlKHkIebemnu__5R5QXKFSK4-QZDYQ_gAMDAQwkMOhDzKDUaobGKF0tN5tH6W8Iewyyolza6nXMYKY0QvgCNrM5QgjT5CnHB0xS1MAgRZtkeV2g1NlzoleR0inqn3lWIDD4kuUWdRhEN8HoMRh_u7sDBpOlDYNIskiwiEO8ZqCW9m_FTaGnVbBIzKJdJOI1JSFexwyMTeYIIV-zY_d_gi7Ff7vcnFbXxrR72hWLxBWL5HXVxkG7dwzgK-o5PqKdlG1wuioxDG6_f769nwaf6g-V4y_7duvAdx91Nl-0X_2b1Cbz9qQ2-eUe-ZfFrkw7Y4zVtSo723YX7rcK8zPX-yj9n1xvfuF6izO37Cj9n9wyceGWyTO3TF749yP-qjygKVVhcK9brlfFxHSOzTCNWuoZ3ms1q8s0j5Oaq3-dUzS2WRXNw6holqoG94cHPvDQB-bcTfMDQovD4IEPPPSBO6Ff0aJL97Zp6Z6YdMK8PbJel-77SOaGCcncMCGZG6Yke-8jmRsmJHPDhGRumJJs4CPZjY8mbpjQxA0TmrhhSpMPPpq4YUITN0xo4oYpTYY-mnCvO4ugCVEImjCFoMlr69UF4BxbvH7zJwAA___LXMUa) versus [the non-crashing query plan](https://cockroachdb.github.io/distsqlplan/decode.html?eJysklFrwjAUhd_3K8p92vAKthUGgUHGcCA4FXUwGGV0zV0XqE1IUpiI_300hbkWdQp7zEm-c3JusoVSCZqma7LAXiEEhCEkCNqojKxVppabQ2PxBWyAIEtduVpOEDJlCNgWnHQFAYNV-l7QglJBBhAEuVQW3lgbuU7NhisjyLwVsiRAeJSFI8MCfhuMl8H0eTIBhFnlWMBj5BHyEJIdgqrcPtG6NCdg4Q7_-1ZnZ0dHs_eRVek9SbQCk5r868iBAk9kclqSm-n2_VcbTSwYvTyM5qvg3o-voA93zcMe8qiHPO7f3BmZf7aln6ahbxoDwkSupQuOd45bncPT856qvtLd4gdth5fYLshqVVo6y3lQz5FETs27WFWZjOZGZf7FmuXMc14QZF2zGzWLcem3_D_7DYcXwFEXjk7CcQsedOH4JDzswMnu6jsAAP__XlVAFQ==). The crashing query plan is distributed, while the non-crashing one is not.

**Comment by arjunravinarayan** [comment]
Ctrl+c-ing the query when the results are streaming does not crash the cluster, only when it's in its computing results state.

I am able to reliably reproduce this across multiple cluster restarts.

**Comment by jordanlewis** [comment]
@andreimatei this looks like a con_executor kind of thing.

**Comment by andreimatei** [comment]
looking
