### ISSUE TITLE
sql: an error on the 1PC code path for update, etc, may fail with an invalid txn state?

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#23700]
Found the following code path:

```go
  if autoCommit == autoCommitEnabled {
    // An auto-txn can commit the transaction with the batch. This is an
    // optimization to avoid an extra round-trip to the transaction
    // coordinator.
    err = tb.txn.CommitInBatch(ctx, tb.b)
  } else {
    err = tb.txn.Run(ctx, tb.b)
  }

  if err != nil {
    return sqlbase.ConvertBatchError(ctx, tableDesc, tb.b)
  }
  return nil
```

Is it guaranteed that  `CommitInBatch` never fails after the EndTxn batch command has been processed?
Otherwise, `err` is not nil, but the txn is committed, and `ConvertBatchError` will fail with "using txn in COMMITTED state".

@nvanbenschoten thoughts? This is low priority since I don't recall seeing this in the wild. Maybe my understanding is limited.

**Comment by nvanbenschoten** [comment]
I took a look at `CommitInBatch` and didn't find any code paths that could lead to the "committed but returning error" case that you're hypothesizing. Still, you bring up a good point that the contract of the method could be more explicit. We can't claim that the presence of an error precludes a committed transaction in general (see `AmbiguousResultError`). However, I think we can promise that if we are considering our local copy of a transaction (`client.Txn`) to be committed, that we won't return an error. This is a strong enough guarantee that any consumer of this API can be sure that:
- a `nil` error indicates that the `client.Txn` considers itself committed and that the txn record is committed
- a `non-nil` error indicates that the `client.Txn` does not consider itself committed (but without more details about the error, doesn't say anything concrete about the txn record)

We could then add in assertions for these conditions to `CommitInBatch`, if you think that's justified.

**Comment by knz** [comment]
>  We can't claim that the presence of an error precludes a committed transaction in general (see AmbiguousResultError).

Is AmbiguousResultError only possible on committed transactions?

If so, then, this raises another question. For context, let's remind ourselves `ConvertBatchError` will issue an additional KV lookup _on the same txn object_ in order to produce the error message.

What if a batch contains two commands, one that generates some error and and EndTxn which triggers AmbiguousResultError?

Then CommitInBatch would either of the two errors but the entire batch would still cause the underlying kv transaction to be unusable (because of AmbiguousResultError). What happens then when ConvertBatchError tries to issue a KV lookup?

**Comment by nvanbenschoten** [comment]
> Is AmbiguousResultError only possible on committed transactions?

No it's not. An AmbiguousResultError is always possible.

> For context, let's remind ourselves ConvertBatchError will issue an additional KV lookup on the same txn object in order to produce the error message.

This is only the case when the batch error is a `ConditionFailedError`, in which case we know that the EndTxn wasn't even evaluated.

**Comment by knz** [comment]
Ok thanks for explaining!
