### ISSUE TITLE
storage: Stop liveness heartbeats when disk is blocked

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#23734]
If a node gets errors when it writes to disk, it will crash. But if the disk is slow, all threads that touch the disk will eventually get blocked while other threads keep going. In particular, this could allow the node to continue heartbeating its liveness record, preventing other nodes from taking over its leases, while all actions on the ranges it owns are blocked. 

We should have some sort of monitoring for slow disks and nodes should stop updating their liveness record if it gets too slow. This is primarily a concern for network-attached storage devices that can block for long periods of time without failing.

**Comment by petermattis** [comment]
Would it be sufficient to have the liveness goroutine synchronously write to the local RocksDB store (via a store-local key) before updating its liveness record? The synchronous RocksDB write would block if the local store is excessively slow.

**Comment by bdarnell** [comment]
Yes, that's what I was thinking of doing.
