### ISSUE TITLE
server: pg URL printed on server start-up improperly sets application_name

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#23739]
```
CockroachDB node starting at 2018-03-12 16:36:27.725280134 +0000 UTC (took 0.8s)
build:               CCL unknown @  (go1.10)
admin:               http://localhost:8080
sql:                 postgresql://root@localhost:26257?application_name=cockroach&sslmode=disable
...
```

Notice how the URL embeds `application_name`. We don't want this! it ruins the stats.

cc @dt.

I'm on it (fixing #23725 and #22376 together with this)

**Comment by dt** [comment]
What is this leaking? This is a local log file or stdout, right?

**Comment by knz** [comment]
Sorry I wasn't clear. The problem is that the string `application_name=cockroach` appears in the reported URL. People will copy-paste that string in their app, and break our PM assumption that mostly our CLI utilities use this specific value.

**Comment by jordanlewis** [comment]
Great catch! I'm glad we're fixing this before it spreads. FWIW This isn't really a leak - that implies that we're accidentally printing private information.

**Comment by knz** [comment]
> This isn't really a leak 

yes great catch

**Comment by dt** [comment]
We initially had our CLI use the known app name "cockroach" so we could look for that app name's hash in the reported stats, and thus back out usage information about our CLI commands. However at @bdarnell's suggestion, @BramGruneir recently switched the reporting of those stats to salt the app name with a random, per-cluster secret salt, so the original thinking that we could count internal CLI command usage by looking for a specific hash no longer applies.

**Comment by knz** [comment]
Ok but nevertheless for the DBA's convenience it would be good to use different app names.
