### ISSUE TITLE
ui/storage: Leader statistics may be undercounted if ranges are quiescent

### ISSUE THREAD

**Issue by mrtracy** [cockroachdb/cockroach#23747]
After the fix to #21109, the estimated total range count from metrics should now be considerably more consistent. 

However, this fix does *not* fix the case where statistics which require RaftState are undercounted (for example, the total Leader count).  In a cluster that has both a large number of quiescent ranges (which seems likely) and has nodes which are restarting, the cluster will end up with a large number of ranges where a subset of the replicas do not have raft state in memory, and this conflicts with our expectations in regards to these metrics (where we might expect every range to count a leader at all times).

Some possible solutions:

 +Attempt to restore raft state into memory when computing these counters (might be too expensive)
+ Add a scanner queue which "pings" ranges in order to make sure all replicas have raft state most of the time
+ Find an alternative way to compute these counters which doesn't involve reading the in-memory raft state
+ Attempt to better message the nuances of these counters (e.g. a low "Leader" count is a normal part of a long running cluster).
+ Abandon ship on these specific metrics.

**Comment by tschottdorf** [comment]
@nstewart I'm not sure why you added S-3-erroneous-edge-case here. Can you elaborate? This is just a case in which we need to put in extra work to arrive at numbers that make sense.
