### ISSUE TITLE
sql/driver: support database/sql/driver.Result

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#2377]
This might be non-trivial. We'll want to return `database/sql/driver.ResultNoRows` on DDL statements, which means we'll need to propagate it (or a placeholder for it) from the server.

https://godoc.org/database/sql/driver#Result

**Comment by petermattis** [comment]
As a hack, I was thinking that a statement like `planner.Update` could return `valuesNode` populated with N empty rows where N is the number of rows that were affected. Or we could add `Result.rows_affected` which would only be set on requests that don't return rows.

**Comment by tamird** [comment]
Looks like hardly anyone uses `driver.ResultNoRows` in the wild, which is kind of sucky. Here's one example of its use: https://github.com/tilinna/go-nuodb/blob/86bb8a66c16a7c15c1a1fcdc142d5be727fde9e3/nuodb.go#L58

I generally dislike using a regex here, but it seems OK in this case. Thoughts?

**Comment by petermattis** [comment]
The use of the regex is because the nuodb protocol is not telling the client that it is a DDL statement. We can easily pass back that bit in the response so I think we should avoid the regex.

**Comment by tamird** [comment]
Implemented in #2614.
