### ISSUE TITLE
config/storage: Allow prohibited constraints in expressive zone configs and lease preferences

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#23789]
We initially disallowed the prohibited constraint type in per-replica constraints and in leaseholder preferences due to concerns about them getting used improperly in ways that are hard to foresee and protect against.

After getting in a little more experience using them and spending more time thinking about them, I'm more confident that allowing them is the right them to do. It's very late in the release cycle, so we don't have to do it for 2.0 (cc @petermattis as a second opinion on that), but we should at least plan on allowing them in 2.1 pending feedback from 2.0.

**Comment by petermattis** [comment]
Agreed that it is too late to add this to 2.0. Can you expand on the rationale for wanting prohibited constraints in per-replica constraints? It will save our future selves from reconstructing that reason.

**Comment by a-robinson** [comment]
There's no single compelling reason. But a few thoughts:

* They're useful for leaseholder preferences if you want the lease to be in one of a couple different places without a preference between those places. For example, if you have a replica in localities `zone=a`, `zone=b`, and `zone=c`, and want the lease in zone a or b but want to let the system choose between them, you'd want a constraint of `-zone=c`. If you have shared higher-level localities you can do that (e.g. if you have `region=us-east1,zone=a`, `region=us-east1,zone=b`, `region=eu-west1,zone=c` you could say `+region=us-east1`), but not if you don't which may reasonably be the case if the two zones you want the lease in are in different regions or even countries.
* I can come up with similar situations for replica placement, although they admittedly tend to be more contrived than lease placement scenarios.
   * For example, perhaps you want to make sure you have one replica in `country=sweden` because you have a lot of users there and want to pin the lease there, but your cluster also includes some nodes in `country=china` and for regulatory reasons you don't want any of your EU data there, but you otherwise don't care where your other replicas live.
   * As another example, say you have a datacenter or certain high-performance nodes in your cluster that is/are reserved for certain, high-priority data, and isn't/aren't intended for storing/serving other arbitrary data. You may want to pin a replica in `+country=us`, but prohibit the replica from being in that special datacenter or on special nodes via `+country=us,-dc=special` or `+country=us,-high-perf`
* If we really didn't trust prohibited constraints, we wouldn't let you use them or mix them with required constraints at all. They aren't inherently more dangerous when constraining a single replica in a range than when constraining an entire range, so long as diversity scoring works properly --
 which I believe it does as of 2.0.

**Comment by tschottdorf** [comment]
@a-robinson could you adjust the milestone to 2.2 if you think that's reasonable at this point? Or are you planning to get those in?
