### ISSUE TITLE
sql: inverted index queries with contains on non-toplevel empty arrays/objects are incorrect

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#23819]
JSON evaluation produces the following:
```
root@:26257/test> select '{"a": {"b": "c"}}' @> '{"a": {}}';
+--------------------------------+
| '{"a": {"b": "c"}}' @> '{"a":  |
|              {}}'              |
+--------------------------------+
|              true              |
+--------------------------------+
(1 row)
```

But the equivalent inverted index query produces a different result:
```
root@:26257/test> create table j (j json, inverted index j_j_idx(j));
root@:26257/test> insert into j values ('{"a": {"b": "c"}}');
root@:26257/test> select * from j where j  @> '{"a": {}}';
+---+
| j |
+---+
+---+
```

The problem is that the fix added in de9cb8eb0dcff898f184a4a238fe7e9d2047fed6 to ensure that queries of the form `SELECT * from t WHERE j @> '{}'` create full table scans was insufficient. Empty objects and arrays can exist anywhere in an object tree, not just at the top level. We need additional logic to produce index spans that contain everything that has a prefix of all of the path elements up to the final empty leaf container.

Marking as 2.0 as this is a correctness issue. If we can't make it by 2.0, we can mark it as a known limitation.

**Comment by justinj** [comment]
Have we decided if this is going to be fixed for 2.0? I feel pretty strongly that if that's possible we should try, in particular it will make blackbox testing against Postgres much simpler. If not we should probably disallow these queries given that they're statically recognizable.

**Comment by vivekmenezes** [comment]
I don't know how difficult this is to pull off. Any chance you can give it a short?

**Comment by jordanlewis** [comment]
It shouldn't be too bad. Here's one strategy:

A new input parameter is added to `EncodeInvertedIndexKeys`, which indicates whether or not empty leaf containers should be included in the output keys. This will be true when generating keys for storage, but false when generating keys for lookup.

A new output parameter is also be added, which indicates whether or not the encoder omitted an empty leaf container byte sequence at the end.

If that input parameter is false, the encoder will simply output nothing for the final leaf value if it's empty, indicating so via the new output parameter. Finally, the index selection code will be modified to say that the span isn't tight if that new output parameter was set, which will ensure that the scan will perform the filter again.
