### ISSUE TITLE
rpc: evaluate what to do with ConnHealth

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#23829]
https://github.com/cockroachdb/cockroach/pull/22658 "broke" ConnHealth since we don't keep broken connections in the connection pool. The method now has a comment:

> // NB: as of #22658, this does not work as you think. We kick
// connections out of the connection pool as soon as they run into an
// error, at which point its ConnHealth will reset to ErrNotConnected.
// ConnHealth does no more return a sane notion of "recent connection
// health". When it returns nil all seems well, but if it doesn't then
// this may mean that the node is simply refusing connections (and is
// thus unconnected most of the time), or that the node simply hasn't
// been connected to but is perfectly healthy.

This is an unsavory state of things. We should consider whether we want ConnHealth to go back to its former meaning (meaning we add some more state to `rpcContext`) or whether it should be removed.

**Comment by bdarnell** [comment]
What's wrong with returning ErrNotConnected for nodes without a live connection? This still functions as a (pessimistic) indicator of node health. ConnHealth won't recover until something tries to connect to the node in spite of its health status, but as long as this method is just used for prioritization it should still be fine.
