### ISSUE TITLE
cli/config: Warn if zoneinfo not available or up to date

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#23828]
CockroachDB will use the system zoneinfo database if available for timezone computations (otherwise, the go standard library embeds a snapshot). Since the zoneinfo database is updated several times a year, it is better to get this data from the system (assuming the system keeps it up to date) than to rely on the internal snapshot. We should document this fact and encourage the use of system zoneinfo (the use of a docker image without zoneinfo is especially common among alpine users: https://github.com/cockroachdb/cockroach/issues/16053#issuecomment-373028977)

**Comment by knz** [comment]
There is no "internal snapshot". The go distribution ships a file `zoneinfo.zip` in $GOROOT but it is not embedded inside the `cockroach` binary so a prod system would not be able to use it.

We actually provide our own custom `LoadLocation` wrapper (`timeutil/zoneinfo.go`) which ensures that if Go's `zoneinfo.zip` is not found (a common occurrence), the error message is meaningful.

As a result, I would be surprised if `cockroach` worked properly in a docker image without a system zoneinfo database.

**Comment by bdarnell** [comment]
> As a result, I would be surprised if cockroach worked properly in a docker image without a system zoneinfo database.

Yeah. It would be nice to try to resolve a time zone at startup to detect this and log an error instead of just waiting for the first query that uses a time zone. 

Reporting the age of the zoneinfo database as a metric would be nice, but I'm not sure if we can easily get that information.
