### ISSUE TITLE
ui: map view should be resilient to nodes without localities

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/cockroach#23849]
Right now if I have a large cluster and add even a single node with a new locality, I lose the ability to visualize the global entire cluster. We should come up with a better way to handle the case when clusters are expanding geographically over time. 

![image](https://user-images.githubusercontent.com/894257/37422572-cd0f6840-2791-11e8-95af-d2b83d16df15.png)

From @vilterp right now the logic is `show a map if all nodes under the current locality have localities and locations assigned to those localities`

**Comment by vilterp** [comment]
Mostly a design question, so cc @josueeee.

In my mind, it's another argument for splitting the screen between map and table, so you can at least see your nodes in a table if they're not on the map.

**Comment by piyush-singh** [comment]
One possibility might be to have a kind of visual catchall bucket for nodes that do not have locations/localities set up correctly. Def worth a conversation with Josué

**Comment by vilterp** [comment]
Yeah, or maybe a number somewhere, like "5 nodes aren't displayed on this map because they don't have localities", and link to some list of them.
