### ISSUE TITLE
server: sessions endpoints return UUID error

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#23842]
Repro instructions:

1. Start a local 1-node cluster (mine is secure, fwiw)
2. Open a SQL shell as root and start a long-running query (e.g. `SELECT pg_sleep(60);`)
3. Try to load all queries being run by the user root by opening up https://localhost:8080/_status/local_sessions?username=root or https://localhost:8080/_status/sessions?username=root

Both endpoints return the error:
```
{
  "error": "uuid.UUID declared custom type github.com/cockroachdb/cockroach/pkg/util/uuid.UUID but it is not convertible to \u003cnil\u003e",
  "code": 2
}
```

If I load either page when not running the sleep query, they work fine:

```
{
  "sessions": [
    {
      "nodeId": 1,
      "username": "root",
      "clientAddress": "[::1]:58906",
      "applicationName": "cockroach",
      "activeQueries": [
      ],
      "start": "2018-03-14T16:47:05.593326154Z",
      "kvTxnId": null,
      "lastActiveQuery": "SHOW database"
    }
  ],
  "errors": [
  ]
}
```

Assigning to @couchand for triage / delegation

**Comment by couchand** [comment]
@knz if you feel strongly that this should be investigated for 2.0, can you take a look into it?  Thanks!
