### ISSUE TITLE
storage: reevaluate gc queue and replica gc queue timer settings

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#23870]
The `{gc,replicaGC}QueueTimerDuration` settings impose a minimal time between the processing of replicas. This mechanism is very old and most queues include other throttling and pacing mechanisms. We recently (#23869) reduced the value for `raftLogQueueTimerDuration` from 50ms to 0 in order to alleviate a bad feedback loop that occurs when raft-log truncation does not keep pace with writes. Should we do the same with `{gc,replicaGC}QueueTimerDuration`?

**Comment by tschottdorf** [comment]
I'm not planning to revisit in the near future. @petermattis I think you've been involved with the queues a little more recently. Do you think there's enough of a concern there to keep this issue open?
