### ISSUE TITLE
ui: ensure correct defaulting to node map vs cluster viz

### ISSUE THREAD

**Issue by vilterp** [cockroachdb/cockroach#23871]
Cases:

1. OSS: see no selector for node list vs node map; always show node map.
2. CCL, no license: default to node list, have persistently-dismissable popup telling you about node map? (This is what's on Josue's design)
3. CCL, license: default to node map

cc @couchand

**Comment by vilterp** [comment]
Currently in master: Enterprise build always goes to node list; you have to click the dropdown to see existence of & go to node map.

Not sure if dropdown properly disappears in OSS build.

**Comment by couchand** [comment]
> Not sure if dropdown properly disappears in OSS build.

it does!

![no-dropdown](https://user-images.githubusercontent.com/793969/37731977-04a73930-2d1a-11e8-9500-50528e1e28f7.png)

**Comment by vilterp** [comment]
Thanks for checking! Could use a little more spacing, but pretty good!

**Comment by couchand** [comment]
@josueeee you want to add that to #24125?

**Comment by vilterp** [comment]
@couchand would be nice to default to the node map if configured; think we can do that for 2.0, or just leave it as is? (currently defaults to node list)

**Comment by couchand** [comment]
would be nice, but it seems like a big ask for this point in the cycle.  if you can figure something low-touch out in the next day or so we can probably get it in.

**Comment by vilterp** [comment]
Not doing any more on this for 2.0.
