### ISSUE TITLE
sql: require inverted indexes using gin syntax to specify jsonb_path_ops

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#23888]
It seems to me that we implicitly use jsonb_path_ops, but that's *not* the default in Postgres, so we should probably require the user explicitly specify it? Otherwise we'll have some tool which thinks we support this in the same way as Postgres but has a lot of its queries require full table scans?

Feel free to close if I'm misunderstanding.

**Comment by justinj** [comment]
ping, would like to figure out what, if anything needs to be done here for 2.0. if this is indeed a problem the fix is easy

**Comment by jordanlewis** [comment]
I don't think this is a serious problem. Our index representation will permit us to index on the operators missing from `jsonb_path_ops` over time. As a reminder, here are the missing operators:

```
?	text	Does the key/element string exist within the JSON value?	'{"a":1, "b":2}'::jsonb ? 'b'
?|	text[]	Do any of these key/element strings exist?	'{"a":1, "b":2, "c":3}'::jsonb ?| array['b', 'c']
?&	text[]	Do all of these key/element strings exist?	'["a", "b"]'::jsonb ?& array['a', 'b']
```

These are all trivially implementable with our inverted index representation. It's true that at launch these will all require full table scans, but I'm not particularly concerned.

Would your proposal be to just error out if the user doesn't specify `jsonb_path_ops` explicitly?

**Comment by justinj** [comment]
Yes, that would be my proposal. I'm nervous that tools/orms might expect those operations to be fast. I'm not convinced this is not an issue but at this point in time I'm happy to err on the side of "known limitation".
