### ISSUE TITLE
sql: errors in client due to use of pg_catalog with non-existent db as current

### ISSUE THREAD

**Issue by tlvenn** [cockroachdb/cockroach#23893]
It seems there is a regression with the latest v2 alpha (20180312) as  I am now seeing the following error when Ecto is trying to create the DB from scratch:

```
** (Postgrex.Error) ERROR 3D000 (invalid_catalog_name): database "postgres" does not exist
    (db_connection) lib/db_connection/connection.ex:148: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

**Comment by knz** [comment]
Can you share the query that caused the error with us?

**Comment by tlvenn** [comment]
The code to create the database is as follow:

```
def storage_up(opts) do
    database = Keyword.fetch!(opts, :database) || raise ":database is nil in repository configuration"
    encoding = opts[:encoding] || "UTF8"
    opts     = Keyword.put(opts, :database, "postgres")

    command =
      ~s(CREATE DATABASE "#{database}" ENCODING '#{encoding}')
      |> concat_if(opts[:template], &"TEMPLATE=#{&1}")
      |> concat_if(opts[:lc_ctype], &"LC_CTYPE='#{&1}'")
      |> concat_if(opts[:lc_collate], &"LC_COLLATE='#{&1}'")

    case run_query(command, opts) do
      {:ok, _} ->
        :ok
      {:error, %{postgres: %{code: :duplicate_database}}} ->
        {:error, :already_up}
      {:error, error} ->
        {:error, Exception.message(error)}
    end
  end
```

As far as I can see, Ecto will connect to the `postgres` system database in order to issue the create database command. Somehow that system database either does not exist anymore (doubtful) or the user has no access to it (but it's the root user...)

**Comment by knz** [comment]
There is no database called `postgres` in CockroachDB -- at least none created by default.
This has not changed between 1.0, 1.1 and 2.0.

The only database created by default is called `system`.

Can you enable `sql.trace.log_statement_execute` (`set cluster setting sql.trace.log_statement_execute = true`), try connecting Ecto again, and then paste a copy of the newly created `cockroach-sql-exec.log` from your log directory?

**Comment by bdarnell** [comment]
CockroachDB allows connections to non-existent databases, so you can connect (as root) to the database you want to create and then create it once you're connected. (For the same reason, you shouldn't be getting an error connecting to the `postgres` database). Or at least this was true in 1.1 - did it break with the schema changes in 2.0?

**Comment by knz** [comment]
>  Or at least this was true in 1.1 - did it break with the schema changes in 2.0?

I just tried in a SQL shell and it seems to work for me.

What does not work anymore (and for good reason) is a query that tries to read from the `pg_catalog` tables before the database has been created. That used to "work" (but produce bogus results).

So here maybe the advice I'd give is ensure the Ecto client doesn't try to access information_schema/pg_catalog before it creates the database.

**Comment by tlvenn** [comment]
Thanks guys for the feedback, I will dig deeper and report back.

**Comment by tlvenn** [comment]
Ya so back to this issue now that I have upgraded to CRDB 2.0

The SQL causing the issue is the following:

```
I180409 03:51:33.625941 1278 sql/exec_log.go:168  [n1,client=127.0.0.1:51861,user=root] 40 exec "" {} "SELECT t.oid, t.typname, t.typsend, t.typreceive, t.typoutput, t.typinput, t.typelem, COALESCE(r.rngsubtype, 0), NULL FROM pg_type AS t LEFT JOIN pg_range AS r ON r.rngtypid = t.oid" {} 0.811 0 "database \"postgres\" does not exist"
```

@knz is there any reason the client should not try to read from `pg_type` before the database has been created ? It seems that along the change that happened toward `pg_catalog`, it affected the ability to query `pg_type` before the database has been created as well.

**Comment by knz** [comment]
> is there any reason the client should not try to read from pg_type before the database has been created ? 

answer:

>  That used to "work" (but produce bogus results) 

We're going to try to provide some workaround, but please note that the use case (trying to do anything before the database exist) is something that would not be supported in pg anyway. This is really stretching the idea of "pg compatibility" very far.

**Comment by knz** [comment]
Oh I just got an idea: is it possible that you open the connection with `system` as current database instead of `postgres` to issue CREATE DATABASE?

**Comment by knz** [comment]
> Would it be possible to somehow alias the CRDB system database transparently to postgres in a read only fashion ?

Yes this is one of the solutions suggested in  #24598. I'm researching the options.

**Comment by knz** [comment]
@tlvenn we're currently prototyping some solution that enable clients to connect and use cockroachdb when no current db is set. However that does not cover your case where the Ecto library is set on using a current db called `postgres`.

For that case, we'd like to recommend as workaround that you create an empty database called `postgres` prior to using the Ecto client. That would solve your problem too. Would that solution be appropriate for your use case?

**Comment by tlvenn** [comment]
Totally easy and doable in dev, more awkward in Staging / Prod where CRDB is operated in Kubernetes with Helm. I will have to use a Helm post-install hook to create the `postgres` database which might be a little bit tricky.

I will submit a patch to Ecto later today to customize the default database, that would solve this cleanly but it does not solve the larger issue that by default Postgresql does come with a default database named `postgres` that will be leveraged in some ways by some tooling.

**Comment by knz** [comment]
> it does not solve the larger issue that by default Postgresql does come with a default database named postgres that will be leveraged in some ways by some tooling.

Yes we came independently to the same conclusion and that's why we decided to also provide a `postgres` compatibility database in #24735.

**Comment by knz** [comment]
That said, @tlvenn the changes in #24735 are too large for a patch release and we won't be able to push that change in the release channel until 2.1. You'll be able to pick it up in alphas. Apologies for the inconvenience.

**Comment by arnodirlam** [comment]
As a temporary workaround on this problem, I've forked ecto and tagged the current version [v2.2.10_cdb](https://github.com/arnodirlam/ecto/tree/v2.2.10_cdb) with the default database changed to "system". It works with Cockroach DB 2.0 using this.

To use it, add this line to your `mix.exs`:
```
{:ecto, "~> 2.1", github: "arnodirlam/ecto", tag: "v2.2.10_cdb", override: true},
```
