### ISSUE TITLE
ui: SQL syntax highlighting disappears on reload

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#23903]
Navigating to the table schema from the "Databases" page initially shows beautiful syntax highlighting. 

![screen shot 2018-03-15 at 12 01 04 pm](https://user-images.githubusercontent.com/6201335/37475268-a813d910-2848-11e8-924f-0f674ac0e8c9.png)

Reload the page (via command-R) and the syntax highlighting disappears. 

![screen shot 2018-03-15 at 12 01 11 pm](https://user-images.githubusercontent.com/6201335/37475270-a9a2791c-2848-11e8-808b-d2e64db81006.png)

Witnessed on the 2.0 release branch, and tagging as 2.0, but this is clearly very low priority.

**Comment by couchand** [comment]
That's very weird and easily reproducible.

**Comment by vilterp** [comment]
Odd indeed. The `componentDidMount` hook which calls the highlighter fires on reload (inserted a log), but `hljs.highlightBlock(this.createStmtNode)` fails to do anything. (`this.createStmtNode` comes out in the log as a perfectly good `pre` element)
