### ISSUE TITLE
sql: integration tests for json+inverted indexes with ORMs

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#23907]
Any of these may or may not expose json/inverted indexes directly but we need to investigate if they do.

* [x] Sequelize - Justin
* [ ] ActiveRecord - ?
* [x] SqlAlchemy - Justin
* [x] Hibernate - ?
* [x] Gorm - ?

@m-schneider @jordanlewis do either of you have any time to look into one or two of the remaining ones?

**Comment by jordanlewis** [comment]
GORM doesn't seem to have support for JSON queries - just grabbing jsonb payloads from the wire. http://gorm.io/docs/dialects.html#PostgreSQL

**Comment by jordanlewis** [comment]
Hibernate doesn't support JSONB out of the box. You have to implement a UserMapping. Therefore, I conclude it also doesn't support specialized JSONB queries. https://www.vojtechruzicka.com/postgresqls-jsonb-type-mapping-using-hibernate/

**Comment by jordanlewis** [comment]
ActiveRecord supports JSONB out of the box, but requires that you write your own queries:

https://nandovieira.com/using-postgresql-and-jsonb-with-ruby-on-rails

**Comment by justinj** [comment]
Rails does seem to support `USING GIN` when defining schemas, though: https://stackoverflow.com/questions/18725081/rails-4-pgsql-add-index-with-type-gin-or-gist
