### ISSUE TITLE
storage: addsstable can rewrite already read history 

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#23908]
Currently `addSSTable` can rewrite previously read history -- a read a time `x` can return a different value after `addSSTable` than it did before. This is unusual in our kv's API -- usually we'd reject such a write. 

It looks like this is because:
1) We do not currently consult the ts cache when adding an sst.
2) Even if we did consult the tscache, we do not currently verify anything about actual timestamps in the keys added by the SST -- they could be older or newer than the command's timestamp. 

To prevent rewriting read history here, it seems like we'd need to 1) consult the ts cache and 2) require the timestamps in the SST match the addSST command timestamp. We already iterate the SST to compute stats and check its bounds, so it shouldn't add significant overhead to check the timestamps too.

I believe we initially assumed we didn't need checks like this, since we were ingesting only into ranges that were not yet in use, and thus no one would be reading it anyway. However if indeed no one is reading it, that implies that the check would not be hit, so adding it shouldn't hurt anything. If our assumption that no one is reading is violated though, adding the check would mean we don't do anything unexpected.

(I haven't thought about write/write conflicts or intents yet, just thinking about history rewriting so far).

cc @cockroachdb/core

**Comment by dt** [comment]
Changing this should not break the existing usage of `addSSTable`: both `RESTORE` and `IMPORT` would need to set their generate keys' timestamps, but they can do so freely, as it has no effect on their result as there's currently no way to see the edit time on SQL data and even if there was, it isn't clear that the RESTORE time isn't correct -- if you'd read before that time, you would not have seen it.

We would need them to pick a time in `evalImport` though when they generate their SSTs, after the fresh lease holder on the newly split and scattered range has started its tscache.

**Comment by bdarnell** [comment]
> We would need them to pick a time in evalImport though when they generate their SSTs, after the fresh lease holder on the newly split and scattered range has started its tscache.

We'd also need to regenerate the SSTs after a WriteTooOldError. Currently the tscache low-water mark can be pushed forward by lease rebalancing. In the future we will move the timestamp cache forward automatically to support follower reads, which would put an upper limit on time from SST generation to ingestion.

**Comment by dt** [comment]
| We'd also need to regenerate the SSTs after a WriteTooOldError.

Yep -- we'd handle that in `evalImport`, but we'd assume that it is rare in practice since we *just* rebalanced the range when we're calling this.

**Comment by dt** [comment]
As we start looking at index backfilling via addsstable, our approach will be different if we expect addsstable to return WriteTooOldErrors vs allowing us to rewrite already read history. The later makes the backfill somewhat easier, but we could probably figure out some combination of retrying smaller batches or other fallbacks if we should expect the former.

I guess our question now is if @cockroachdb/core is OK the fact it can rewrite read history and indeed that it will used to do that intentionally in backfills of key space that other SQL process are hitting, or if that was only tolerated when we were promising only to use it against ~inactive keysapce.

**Comment by bdarnell** [comment]
My tentative answer is that I'd rather allow AddSSTable the freedom to write into the past (we need this to restore with revision history, for example) and continue to disallow its use on "active" keyspace. We may need to refine the definition of active keyspace - an index being backfilled is more active than a table being restored, but it's still not getting "real" traffic. We'll need to study that to see whether it's safe.

**Comment by dt** [comment]
Perfect, thanks.
