### ISSUE TITLE
ui: databases page overflows horizontally

### ISSUE THREAD

**Issue by couchand** [cockroachdb/cockroach#23902]
For some reason the databases page seems to overflow horizontally, though there doesn't appear to be any content to the right of the initial viewport.  Needs investigation to determine the root cause.

**Comment by vilterp** [comment]
Probably because of the tooltips that show up when you mouse over the (i)s next to the stats. Didn't know they changed the page width before they've ever showed up. Maybe those tooltips should go to the left.

**Comment by couchand** [comment]
LIkely fixed by #30297, needs validation.

**Comment by vilterp** [comment]
Just verified on Cyan; I think this is fixed.
