### ISSUE TITLE
roachtest: Reuse clusters across test families

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#23915]
Our jepsen test suite currently runs 70 permutations of test+nemesis. In porting this to roachtest, these would ideally each be their own `testSpec`, but since each `testSpec` gets a new cluster this would cause the cluster setup time to dominate (including both VM creation and installing java and other dependencies that aren't used by our other tests). We should be able to have a cluster that is shared across all jepsen tests to amortize this cost.

The workaround is to make the entire jepsen test suite a single "test", but this has limitations for error reporting.

**Comment by petermattis** [comment]
Since cluster creation and destruction is now part of the infrastructure (and outside of the test's control), it seems feasible to reuse clusters between tests when they have the same specification.

**Comment by bdarnell** [comment]
Yeah, I was thinking the cluster spec would gain some argument that would select an initialization function. Or we could bake all of this initialization into a disk image with packer. If we had pre-built disk images, would we still want to reuse clusters that share a disk image, or would that get the cost low enough that we'd just create a new cluster each time? (Our current setup runs 40 jepsen configurations, each of which runs for ~7 minutes).

**Comment by petermattis** [comment]
I've been thinking about how to reuse clusters between tests and not particularly liking an approach where I have to match up node specs and initialization functions to clusters and determining when a cluster can be destroyed vs reused.

As an alternative, we could introduce a concept of sub-tests similar to Go's `testing` sub-tests. All of the sub-tests would reuse the cluster for the parent test and would be run sequentially. There would be a lot less magic involved with this approach.
