### ISSUE TITLE
sql: test that @> index lookups always match @> expression evaluation

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#23927]
Pasted from a slack conversation:

1. insert large amounts of random json
2. for each json, do a contains query on all of its paths
3. assert that the results contain the json that the path came from 
4. assert that every result in the result sets contains the path according to the expression evaluator

This test will
1. catch the bug with scalar contains
2. catch the bug with empty leaves
3. maybe catch more bugs
4. ensure that the scary bear of “does index lookup contains match expression contains always” is appeased.

**Comment by jordanlewis** [comment]
This is done right @justinj?

**Comment by justinj** [comment]
Yes fixed by #24007
