### ISSUE TITLE
ui: page displaying cluster settings

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#23923]
The admin UI should have a page displaying the cluster settings (i.e. `show all cluster settings`). I'm a bit surprised we don't already have such a page.

**Comment by vilterp** [comment]
@BramGruneir has been meaning to make this page; don't know if he has already filed an issue.

**Comment by a-robinson** [comment]
It's not as good as an actual web page, but if someone gets desperate to know the settings on a 2.0 build, know that there is the `/_admin/v1/settings` endpoint.

**Comment by petermattis** [comment]
> It's not as good as an actual web page, but if someone gets desperate to know the settings on a 2.0 build, know that there is the /_admin/v1/settings endpoint.

Can we add that link that to the `/#/debug` page?

**Comment by a-robinson** [comment]
Sure: https://github.com/cockroachdb/cockroach/pull/23925

**Comment by couchand** [comment]
Provisionally sending over to @BramGruneir, but feel free to unassign yourself.

**Comment by dt** [comment]
fwiw, we actually scrubbed settings values *out* the event log in the UI for 2.0 due to lack of auth, since the settings values were considered root-only.

**Comment by a-robinson** [comment]
Discussion continued on https://github.com/cockroachdb/cockroach/issues/24028
