### ISSUE TITLE
sql: normalize col->foo @> bar to col @> {"foo": bar}

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#23929]
Currently, queries of the form

```
SELECT * FROM t WHERE j->key @> path
```

cannot use inverted indexes. Only queries of the form `j->key = value` can. It's straightforward to normalize the above example to one of the correct form:

```
SELECT * FROM j WHERE j @> {key: path}
```

so we should do this.

**Comment by justinj** [comment]
This was completed in #27726.
