### ISSUE TITLE
roachpb: value type is not BYTES

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#23946]
version: v2.0-beta.20180305-252-g65bafd6 (cluster setting version is `2.0`).

While running a statement `update players set skill = $1 where game = $2 and blizzid = $3`, got an error:

`ERROR: value type is not BYTES: UNKNOWN (SQLSTATE XX000)`

At this time, there is currently a schema change (index addition) executing, with 3 queued:

Executing: `CREATE INDEX ON hots.public.players (build ASC, hero ASC, mode ASC, hero_level ASC) STORING (winner, talents, skill)`

Another create and 2 drops are queued.

Is this indicative of a problem with our schema change stuff?

Schema for the table:

```
CREATE TABLE players (
	game INT NOT NULL,
	mode INT NULL,
	"time" TIMESTAMP NULL,
	map INT NULL,
	length INT NULL,
	build INT NULL,
	region INT NULL,
	hero INT NULL,
	hero_level INT NULL,
	team INT NULL,
	winner BOOL NULL,
	blizzid INT NOT NULL,
	skill INT NULL,
	battletag STRING COLLATE en_u_ks_level1 NULL,
	talents INT[] NULL,
	data JSON NULL,
	CONSTRAINT "primary" PRIMARY KEY (game ASC, blizzid ASC),
	INDEX players_region_blizzid_time_idx (region ASC, blizzid ASC, "time" DESC),
	INDEX players_region_battletag_idx (region ASC, battletag ASC),
	INDEX players_build_map_mode_hero_level_idx (build ASC, map ASC, mode ASC, hero_level ASC) STORING (hero, winner),
	INDEX players_build_map_hero_level_idx (build ASC, map ASC, hero_level ASC) STORING (hero, winner),
	INDEX players_build_hero_level_idx (build ASC, hero_level ASC) STORING (hero, winner),
	INDEX players_build_hero_idx (build ASC, hero ASC) STORING (winner, hero_level, length, map, mode),
	INDEX players_build_hero_map_mode_hero_level_idx (build ASC, hero ASC, map ASC, mode ASC, hero_level ASC) STORING (winner, talents),
	INDEX players_build_hero_map_hero_level_idx (build ASC, hero ASC, map ASC, hero_level ASC) STORING (winner, talents),
	INDEX players_build_hero_mode_hero_level_idx (build ASC, hero ASC, mode ASC, hero_level ASC) STORING (winner, talents),
	INDEX players_build_hero_hero_level_idx (build ASC, hero ASC, hero_level ASC) STORING (winner, talents),
	INDEX players_build_mode_hero_level_idx1 (build ASC, mode ASC, hero_level ASC) STORING (hero, winner, skill),
	INDEX players_build_map_mode_hero_level_idx1 (build ASC, map ASC, mode ASC, hero_level ASC) STORING (hero, winner, skill),
	FAMILY "primary" (game, mode, "time", map, length, build, region, hero, hero_level, team, winner, blizzid, skill, battletag, talents, data)
)
```

Assigning for triage, not sure if there's a better person.

**Comment by mjibson** [comment]
Also of note, there were some schema changes completed right before this (a drop, create, drop create).

**Comment by mjibson** [comment]
And updating to a more recent v2.0-beta.20180305-342-g9740b2a didn't help either.

**Comment by mjibson** [comment]
So clearly there's some corrupt data here right? Could have also happened because this is a 3 node cluster on preemptible instances. So maybe a write was going on when a node rebooted maybe? Unclear if that could cause something.

**Comment by vivekmenezes** [comment]
This looks very bad because it appears that it's reading some data with an UNKNOWN tag on the data. The failure is happening during decoding. Also the index is of type BYTE so I suspect it is a bad index entry.

**Comment by mjibson** [comment]
Running `experimental scrub table players with options index all` to see what happens.

**Comment by bdarnell** [comment]
> Could have also happened because this is a 3 node cluster on preemptible instances. So maybe a write was going on when a node rebooted maybe? Unclear if that could cause something.

RocksDB writes are atomic and the files have internal checksums, so it's very unlikely that you'd see this symptom because of a reboot. (we have experience with flaky azure disks that shows that the checksums work, and other tests with unclean shutdowns have shown that the latest rocksdb write can get rolled back but the writes are still all or nothing)

>  Also the index is of type BYTE so I suspect it is a bad index entry.

But the query's WHERE clause specifies the table's PK, so the update should only be reading there and writing to the secondary indexes. Have you changed any columns in this table recently, or just indexes?

**Comment by mjibson** [comment]
Just been adding and dropping indexes. No column adds or drops.

**Comment by mjibson** [comment]
I did a BACKUP/RESTORE of this data and it appears to be fine now. I no longer have access to broken data so can't repro this any more. But I wonder if it's related to https://github.com/cockroachdb/cockroach/issues/23984. The data from this bug was created with version from earlier in the year. I'm to close on that assumption.
