### ISSUE TITLE
roachtest: import/tpch/nodes=8 failure

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#23950]
See https://teamcity.cockroachdb.com/downloadBuildLog.html?buildId=577625&plain=true

```
[09:14:24] :	 [Step 3/3] --- FAIL: import/tpch/nodes=8 (15338.69s)
[09:14:24] :	 [Step 3/3] 	import.go:88: pq: job 331304217787891713: node liveness error: restarting in the background
```

Strangely, I don't see any additional information in the [`test.log`](https://teamcity.cockroachdb.com/repository/download/Cockroach_Nightlies_WorkloadNightly/577625:id/20180316-577625/import/tpch/nodes%3D8/test.log) artifact.

I'll note that I saw this same error when generating a tpcc-20k dataset this morning. In that case, the IMPORT seemed to finish ok.

Is there anything we can do to make this test a bit more robust against this occurrence? For example, when that error occurs could the test switch to polling the jobs table? Or do we want to make sure we squash all these node liveness errors?

Marking as 2.1, but we really need to deflake this test soon before we get accustomed to it failing.

**Comment by mjibson** [comment]
When https://github.com/cockroachdb/cockroach/pull/23913 goes in, it *should* fix these issues. If it doesn't, then I'll do something to improve the resiliency of the test.

**Comment by benesch** [comment]
https://github.com/cockroachdb/cockroach/pull/23913 is expected to resolve this.

**Comment by benesch** [comment]
Whoops, sorry. GitHub bugged out.
