### ISSUE TITLE
sql: index selection code doesn't actually use thickness of index

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#23966]
I might be misunderstanding, but I think the following code is wrong:

https://github.com/justinj/cockroach/blob/7a4d3c16f5f1dfd86ba053311ffba6d2a8323534/pkg/sql/opt_index_selection.go#L285-L302

```
	// The base cost is the number of keys per row. 
	if v.index == &v.desc.PrimaryIndex {
		// The primary index contains 1 key per column plus the sentinel key per
		// row.
		v.cost = float64(1 + len(v.desc.Columns) - len(v.desc.PrimaryIndex.ColumnIDs))
	} else {
		v.cost = 1
		if !v.covering {
			v.cost += float64(1 + len(v.desc.Columns) - len(v.desc.PrimaryIndex.ColumnIDs))
			// Non-covering indexes are significantly more expensive than covering
			// indexes.
			v.cost *= nonCoveringIndexPenalty
		}
	}
```

I think the intention is that this has lower cost for indexes with fewer columns, but we always use the number of columns in the table and the number of columns in the primary key. I think we should be using the index in question in the second branch.

However, I think this is also currently masking a bug involving index selection with inverted indexes, so I think this shouldn't be changed in the 2.0 timeframe.

cc @RaduBerinde, @jordanlewis for clarification

**Comment by RaduBerinde** [comment]
This is trying to estimate the number of KVs. All indexes have a KV per entry. The formula inside `v.covering` is there because you have to do an index join so you scan the primary table too. There are some later adjustments to `cost` which result in preferring indexes with fewer columns:
```
		v.cost *= float64((numIndexCols + numExtraCols)) / float64(numCols)
```

We also have this code which removes unconstraine inverted indexes from the list of candidates (note that these are never considered "covering"):
```
	if s.noIndexJoin {
		// Eliminate non-covering indexes. We do this after the check above for
		// constant false filter. We're also removing inverted indexes that don't
		// generate spans.
		for i := 0; i < len(candidates); {
			spans, ok := candidates[i].ic.Spans()
			if !candidates[i].covering ||
				(candidates[i].index.Type == sqlbase.IndexDescriptor_INVERTED && (!ok || len(spans) == 0)) {

```

**Comment by RaduBerinde** [comment]
Oh, wait. This only runs if we have the "no index join" hint. I don't think that's what was intended CC @masha I think we need to move the inverted index check outside the `if noIndexJoin` (sorry I didn't catch this when I reviewed it).

**Comment by justinj** [comment]
While there is something to be fixed, it's not the one outlined by this issue as Radu explained, so closing.
