### ISSUE TITLE
sql: get rid of TableDescriptor lease renewal

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#23978]
For descriptors with versions V0, V1, V2 each written at timestamps T0, T1, T2, a descriptor at V0 cannot be used with a timestamp T >= T2.

A lease renewal is about extending the expiration time of a lease. A node has a table descriptor at version V0 with a lease with an expiration time because the descriptor is cached and can only be used if V2 is never written. The lease applies pressure on the schema changer and doesn't allow it to write version V2.

Truth is the schema changer can see that a node has a lease on V0 and also has access to node liveness information. It can declare a lease  as expired based on node liveness. By eliminating the need for extending the expiration time a node need not renew a lease.

Under normal operations a lease is created by a node and only deleted when it is draining.

Changes that need to be made:
1. Introduce the notion of lease epoch based on node epoch.
2. Under normal operations a lease is created by a node and only deleted when the node is being drained.
3. To accommodate for the fact that certain leases will not get deleted because of an ungraceful shutdown, a lease is allowed to be declared invalid based on some criterion around the lack of node liveness + a delta time period D.
3. leases not explicitly dropped are GCed. #20485

 On the read write path we can do one of the following
1. Set a deadline based on hlc + delta (related to D above) (easy)
2. Relate writes to node liveness of gateway node. (probably hard, or an unnecessary check on a hot path).

See related: https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20160210_range_leases.md

**Comment by vivekmenezes** [comment]
Just adding a not so well thought out idea, a node acquiring an epoch based lease (just one lease) can acquire a lease for the entire table descriptor space at a particular timestamp. As tables get updated, the nodes get notified to reacquire this lease, which they do for the entire table space. A schema change can make progress if the version V for a table it is trying to upgrade to V+1 has a ModificationTime that is less than the timestamp on all node leases.

The epoch is purely for the purpose of cleaning up leases that were left behind by dead nodes that didn't gracefully cleanup their lease.

Nodes will assign deadlines to transactions at commit time will use the frontier provided by the epoch based lease.

All of this needs to up discussed in an update to the RFC

**Comment by vivekmenezes** [comment]
https://github.com/cockroachdb/cockroach/pull/28628

**Comment by ajwerner** [comment]
Given the decision to not move forward with epoch-based schema leases, this is now stale.
