### ISSUE TITLE
bulk: restore produces different row counts on different runs

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#23977]
After restoring a tpcc-10k workload fixture earlier today, the `tpcc` tool encountered a variety of unexpected conditions. I tracked this down to a large number of missing rows in some tables. The smallest such table is `tpcc.customer`:

```
root@localhost:26257/> select count(*) from tpcc.customer;
+-----------+
|   count   |
+-----------+
| 299157429 |
+-----------+
```

That table is supposed to have exactly `300000000` rows (30k customers * 10k warehouses). The above restore was performed on a 24-node cluster by running: `./workload fixtures load tpcc --warehouses=10000`.

I decided to verify the consistency of the other tpcc datasets which all look fine (correct number of rows and pass various tpcc checks). I then restored just the tpcc-10k customer table into a freshly created cluster: `RESTORE csv.customer FROM 'gs://cockroach-fixtures/workload/tpcc/version=2.0.0,interleaved=false,seed=1,warehouses=10000/customer' WITH into_db = tpcc;`

This is exactly the same backup that was restored by the workload command. Lo-and-behold, the table has the right number of rows:

```
root@localhost:26257/> select count(*) from tpcc.customer;
+-----------+
|   count   |
+-----------+
| 300000000 |
+-----------+
```

One additional datapoint: during the `workload`-initiated restore I saw `Error: restoring fixture: pq: job 331478132192411649: node liveness error: restarting in the background`. This happened before the restore of the `customer` table completed. Of the 9 tpcc tables, 6 completed before that error and all 6 had the correct number of rows. The 3 tables that completed after that error (`customer`, `stock` and `order_line`) were all truncated.

This seems very serious.

**Comment by dt** [comment]
Woah, that's scary. I'll look into this tomorrow morning and see if I can repro.

If you happen to have the `RESTORE` result row, I'd be curious to know how may rows `RESTORE` thought it wrote, but i'm guessing workload didn't expose that.

**Comment by petermattis** [comment]
`workload` doesn't expose the `RESTORE` output. And `workload` exited after the `liveness error`.

**Comment by benesch** [comment]
I’ve been trying to figure out where to even start debugging this. Talk about a terrifying bug.

The fact that you observed corruption only in the tables after resume provides strong evidence that the bug is in the tracking of completed work. It’s also easy to imagine why a bug in that code would cause a restore to think it succeeded; if we incorrectly bump the low water mark we’ll just skip restoring data on resume. It’s hard to imagine a bug exhibiting similar behavior anywhere else in the codepath—I guess the export storage layer silently blanking out SSTs might do it? Seems unlikely.

It would be a huge help if you could preserve the cluster if this ever happens again, Peter. The pattern of empty ranges (assuming it is entirely missing ranges) would be illuminating. In the meantime I suppose we should stress pause/resume of TPCC 10k restores.

**Comment by dt** [comment]
Just reproduced this -- I upped the concurrent import limit a bit to make a liveness error almost certain and ran `./bin/workload fixtures load tpcc --warehouses=10000`.  Lo and behold:
```
> select count(*) from tpcc.customer;
299336959 
```
We have 663,041 missing rows.

(note: the _secondary_ index  knows it it's 300M if you do `select count(*) from tpcc.customer@customer_idx`). 

Any given `c_w_id` value should have 30000 rows in customer so I pulled row-count by id found a few holes, 9439-9440, 9460-9467, and 9469-9482. Looking at the first (and smallest):

```
9438: 30000
9439: 634
9440: 533
9441: 30000
```

Diving into 9439, I tried `SHOW KV TRACE FOR select count(*) from tpcc_broken.customer@primary where c_w_id = 9439;`, it looks like it hits a couple ranges, one of happily counts the 634 rows we got but nothing from the others:
```
| Scan /Table/59/1/94{39-40}                      | [n1,client=127.0.0.1:57068,user=root]              |     | sql txn        |    0 |
| querying next range at /Table/59/1/9439         | [client=127.0.0.1:57068,user=root,txn=f6719ed3,n1] |     | dist sender    |    3 |
| r31522: sending batch 1 Scan to (n5,s5):2       | [client=127.0.0.1:57068,user=root,txn=f6719ed3,n1] |     | dist sender    |    3 |
| querying next range at /Table/59/1/9439/1/635   | [client=127.0.0.1:57068,user=root,txn=f6719ed3,n1] |     | dist sender    |    3 |
| r31561: sending batch 1 Scan to (n10,s10):4     | [client=127.0.0.1:57068,user=root,txn=f6719ed3,n1] |     | dist sender    |    3 |
| querying next range at /Table/59/1/9439/1/635/0 | [client=127.0.0.1:57068,user=root,txn=f6719ed3,n1] |     | dist sender    |    3 |
| r31568: sending batch 1 Scan to (n5,s5):2       | [client=127.0.0.1:57068,user=root,txn=f6719ed3,n1] |     | dist sender    |    3 |
| fetched: /customer/primary/9439/1/1 -> NULL     | [n1,client=127.0.0.1:57068,user=root]              |     | sql txn        |    0 |
| fetched: /customer/primary/9439/1/2 -> NULL     | [n1,client=127.0.0.1:57068,user=root]              |     | sql txn        |    0 |
...
fetched: /customer/primary/9439/1/634 -> NULL   | [n1,client=127.0.0.1:57068,user=root]              |     | sql txn        |    0 |
```

Looking at `SHOW TESTING_RANGES`, it looks like there is indeed a split at 635... or two actually?:
```
/9439/1/635 | /9439/1/635/0 | 31561 | {3,5,10} | 10
/9439/1/635/0 | /9440/10/2468 | 31568 | {3,5,19} | 5
/9440/10/2468 | /9440/10/2468/0 | 31627 | {3,5,8} | 5
/9440/10/2468/0 | /9442/10/1263 | 31687 | {3,5,8} | 5
```

I'm going to dig around those ranges and see if I can find out what makes them special.

**Comment by dt** [comment]
@benesch if you're wanting to poke at a cluster with a repro, `david-restore` has it. I renamed the db to `tpcc_broken` so I could try some other things, but the tables, and the empty ranges, are there.

**Comment by dt** [comment]
@benesch checkpointing and progress are my top suspect, along with as you mention accidentally blanking an SST (but an empty file should error -- we'd need to make a _well formed_ empty sst which seems less likely), or something about the fact the cluster as a whole got kinda sad for awhile: 
part way though we see addsstable applications drop to ~0, lots add/remove replicas and rocksdb compactions spike up (part of the replicas moving?).

Interetingly, leading up to it falling over, the % of addsstable calls that had to copy shot up... I wonder if that's what pushed the disks too far.

**Comment by dt** [comment]
@benesch huh i might have offered that repro cluster too soon as I just looked and that cluster is nearly unresponsive now 😬

**Comment by benesch** [comment]
I seem to have partially succeeded in nursing the cluster back to health. Restarting very, very slowly brought things back online; several of the nodes are stuck early in startup, thirty minutes later, with symptoms that look like #21901.

**Comment by dt** [comment]
Okay, more conclusive indication that it is something about job progress tracking and checkpointing:
fresh 3-node cluster, no altered bulk io settings.

Run `RESTORE csv.customer FROM 'gs://cockroach-fixtures/workload/tpcc/version=2.0.0,interleaved=false,seed=1,warehouses=10000/customer' WITH into_db = tpcc;`

In screen, `while true; do ./cockroach sql --insecure -e "pause job 332355677884022785"; sleep 5; ./cockroach sql --insecure -e "resume job 332355677884022785"; sleep 60; done`

`SHOW JOBS` says it succeeded. 
```
root@localhost:26257/> select count(*) from tpcc.customer;
+-----------+
|   count   |
+-----------+
| 242263121 |
+-----------+
(1 row)

Time: 7m16.237158016s
```

To rule our thrashing due to liveness:
```
$ roachprod run david-restore2 "grep liveness logs/cockroach.log"
david-restore2: grep liveness logs/cockroac... 4/4
   1: W180319 22:06:35.273348 9 sql/jobs/registry.go:233  [n1] unable to get node liveness: node not in the liveness table
   2: W180319 22:06:36.006139 20 sql/jobs/registry.go:233  [n2] unable to get node liveness: node not in the liveness table
   3: W180319 22:06:36.688833 12 sql/jobs/registry.go:233  [n3] unable to get node liveness: node not in the liveness table
   4: W180319 22:06:37.387212 14 sql/jobs/registry.go:233  [n4] unable to get node liveness: node not in the liveness table
```

I hesitate to say this is _proof_: it _could_ still be some sort of race with in replicas moving and/or addsstable but that seems unlikely -- this is has so far been a rare bug, and on a healthy cluster with little replica thrashing, we'd have to have been very lucky to spot it, so all indications point to our progress tracking. I'll start combing over that and see what I find.

**Comment by dt** [comment]
It also happens on single node, running locally, so *that* clearly rules out any possible race with moving replicas. Digging in to the low water mark now.
