### ISSUE TITLE
ui: [suggestion] clusterviz storage is too prominent relative to CPU

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/cockroach#23970]
My cluster is red lining but everything looks fine in the UI.
![image](https://user-images.githubusercontent.com/894257/37555416-23ce8170-29bd-11e8-97dc-6e8c57c36a0f.png)

When talking to @robert-s-lee about strategies for debugging performance issues he noted that CPU is the first thing he checks. At this point, we have several internal and external examples of CPU causing issues that take a long time to figure out. The web ui should easily be able help here. 

Today, when glancing at the cluster viz, everything looks OK/stable when in reality the nodes could be red-lining. I think this is an information architecture opportunity with our core gauge component.

We should re-evaluate/stress-test the user story that made us put storage as the primary indicator of "capacity." I think this will sort itself out when we start the project help people identify bottlenecks faster, but want to track this usability issue that I've run into a few times now.

**Comment by couchand** [comment]
Yes, we should go back to the drawing board with the cluster viz.  This first version was much too focused on a particular visual idea, without enough credence given to the actual usability.

**Comment by josueeee** [comment]
There never was any valid reasoning for making "capacity" the primary metric. For the most part, this metric was the only one that "fit" the gauge component. From research, CPU, QPS, and MEM were more important metrics. However, as @couchand mentioned, we need to reevaluate the cluster viz design and our use of the gauge in terms of usability and make the necessary changes. In regards to redlining, we dropped any "alerting" when crossing any critical thresholds for this release and we should prioritize it once we get more feedback from customers on the UX.

**Comment by nstewart** [comment]
Thanks for the context. For my initial purposes, solving the metric visualization problem would solve my redlining issue. I don't think I need specific alerting functionality to fix the bottleneck I had.

**Comment by josuerr** [comment]
Ahhhh, that's good to know. You're right it should just be an IA issue we can solve for.

**Comment by vilterp** [comment]
For one thing, we don't know when the cluster is "redlining" because we don't know how many cores each node has. Once we gather this (possibly as a new time series), we'll know how much CPU is available and possibly give a true percentage, or some kind of fraction (e.g. "using 50 out of 70 cpu secs / sec").
