### ISSUE TITLE
sql: duplicate key value on non-unique index

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#23984]
version (master branch at d23c18ad82bb79c26bde98b38365af65af5b7cfb + a patch dealing with the job registry): CockroachDB CCL v2.0-alpha.20180212-1682-g3d9738f

Running a job that does a bunch of updates (`update players set skill = $1 where game = $2 and blizzid = $3`) and got an error:

`ERROR: duplicate key value (build,map,mode,hero_level)=(67,14,1,1) violates unique constraint "players_build_map_mode_hero_level_idx" (SQLSTATE 23505)`

See the schema below. There is clearly no unique index beside the PK, and the UPDATE didn't change any columns in the PK.

For the schema:

```
CREATE TABLE players (
	game INT NOT NULL,
	mode INT NULL,
	"time" TIMESTAMP NULL,
	map INT NULL,
	length INT NULL,
	build INT NULL,
	region INT NULL,
	hero INT NULL,
	hero_level INT NULL,
	team INT NULL,
	winner BOOL NULL,
	blizzid INT NOT NULL,
	skill FLOAT NULL,
	battletag STRING COLLATE en_u_ks_level1 NULL,
	talents INT[] NULL,
	data JSON NULL,
	CONSTRAINT "primary" PRIMARY KEY (game ASC, blizzid ASC),
	INDEX players_region_blizzid_time_idx (region ASC, blizzid ASC, "time" DESC),
	INDEX players_region_battletag_idx (region ASC, battletag ASC),
	INDEX players_build_map_mode_hero_level_idx (build ASC, map ASC, mode ASC, hero_level ASC) STORING (hero, winner, skill),
	INDEX players_build_map_hero_level_idx (build ASC, map ASC, hero_level ASC) STORING (hero, winner),
	INDEX players_build_mode_hero_level_idx (build ASC, mode ASC, hero_level ASC) STORING (hero, winner, skill),
	INDEX players_build_hero_level_idx (build ASC, hero_level ASC) STORING (hero, winner),
	INDEX players_build_hero_idx (build ASC, hero ASC) STORING (winner, hero_level, length, map, mode),
	INDEX players_build_hero_map_mode_hero_level_idx (build ASC, hero ASC, map ASC, mode ASC, hero_level ASC) STORING (winner, talents, skill),
	INDEX players_build_hero_map_hero_level_idx (build ASC, hero ASC, map ASC, hero_level ASC) STORING (winner, talents),
	INDEX players_build_hero_mode_hero_level_idx (build ASC, hero ASC, mode ASC, hero_level ASC) STORING (winner, talents, skill),
	INDEX players_build_hero_hero_level_idx (build ASC, hero ASC, hero_level ASC) STORING (winner, talents),
	FAMILY "primary" (game, mode, "time", map, length, build, region, hero, hero_level, team, winner, blizzid, skill, battletag, talents, data)
)
```

**Comment by knz** [comment]
So the most surprising thing from the UX perspective in this error is that not only does the UPDATE not change anything in the PK, it doesn't change anything in the conflicting index either.

_however_ I think the logic in rowwriter's UpdateRow re-encodes every index when any value in the row is changed. I think this FK violation error can be encountered if the txn gets a conflict in-between the update to a PK and the update to a secondary index -- when another txn successfully writes to the same PK row "underneath". UpdateRow doesn't "see" that the txn is aborted and instead runs into a KV conflict and thinks it's a uniqueness violation.

This is precisely the scenario that @bdarnell and @nvanbenschoten were discussing yesterday.

@vivekmenezes I'm off for a week, this should be looked at by someone until then. Can you please divert until I'm back?

@jordanlewis can you check whether this is related to the FK issues that were seen during tpcc testing. I think it is. /cc @tschottdorf

**Comment by knz** [comment]
@mjibson the working hypothesis for that problem is that if your client retries the txn upon encountering this error, the error will disappear. I'm not sure in which scenario you found this, but perhaps a txn retry would be a workaround until the underlying problem is fixed? (Assuming the hypothesis is correct -- we're not yet 100% sure on that)

**Comment by mjibson** [comment]
I reran the job an hour later and had the exact same error, so it doesn't appear to be a txn-related problem.

**Comment by mjibson** [comment]
The code running this is at https://github.com/mjibson/hots.dog/blob/36a7b7834677505b6d342a19195c1de873e26757/elo.go#L203

It sets up a pgx pool and runs a bunch of updates from data incoming over a channel, so there's certainly lots of statements going through the same session, assuming the pool isn't making a new session each execution.

**Comment by vivekmenezes** [comment]
this involves an update to the STORING index where the value of the index is being modified.

```
INDEX players_build_map_mode_hero_level_idx (build ASC, map ASC, mode ASC, hero_level ASC) STORING (hero, winner, skill),
```
note an update to skill results in an update to this index.

**Comment by mjibson** [comment]
Running these manually, this has nothing to do with retries. With no other transactions going on if I just run one of these by hand it fails with this same error. I'm not sure what I can do to get around it. It's delaying a feature :(. Is there any suspicion that using the 2.0 branch would improve this? I'm already on cluster version 2.0-1, so it's not trivial to just drop in a 2.0 binary otherwise I'd try.

**Comment by bdarnell** [comment]
So do you get different results for these two queries?

    select * from players@primary where (build, map, mode, hero_level) = (67, 14, 1, 1);
    select * from players@players_build_map_mode_hero_level_idx where (build, map, mode, hero_level) = (67, 14, 1, 1);

**Comment by mjibson** [comment]
Ok update: I did a BACKUP, started up a release-2.0 cluster, RESTORE, and now everything seems fine.

Would it be useful to spin up a master cluster again to test those queries? Can do.

**Comment by mjibson** [comment]
I was able to (accidentally) recreate this situation on a release-2.0 cluster. The above query returned identical results (13 rows each, no diff). I find it medium weird that a backup/restore cycle did something to change this. I was able to replicate that again just now (i.e, do a backup/restore and it works fine). So...this maybe got weirder.

**Comment by mjibson** [comment]
I did a test to verify some things.

1) Started up a 1-node cluster with no existing data.
2) Ran the import data commands that produced the error from before.
3) Ran the update job that caused the error from before. The error occurred as expected.
4) Ran `cockroach debug keys`.
5) BACKUP/RESTORE into a new empty cluster (so the table IDs would be the same).
6) Ran `cockroach debug keys` on the new cluster.
7) Ran the update job which succeeded (as expected, and as before).
8) diff'd the old and new `debug keys` output. Surprisingly (maybe?), there were zero diffs in the table space above ID 50, which means this bug doesn't appear to be caused by data on disk in the table's data range. Diff is attached if anyone thinks it's interesting.

[diff-keys.txt](https://github.com/cockroachdb/cockroach/files/1828052/diff-keys.txt)

I'll continue investigating tomorrow, but this appears to rule out things like intents or other on-disk transaction stuff.

**Comment by mjibson** [comment]
More updates: doing a `cockroach dump` and then piping that in also makes the problem go away.

**Comment by mjibson** [comment]
Tonight's analysis: added some debug prints during cputs and failures. When I drop all indexes except one, the error is the same. The CPut expected value is `/BYTES/8103143a240000000000000000` (and it's the only CPut now since there's just the one index). The ConditionFailedError.ActualValue error value says it is: `/BYTES/8103143a240000000000000000`, which is exactly what the expected value was, so it is odd that the error is occurring.

**Comment by bdarnell** [comment]
Values contain a checksum, which is not included in their pretty-printed representation. Try printing that out too. 

We tried phasing out the checksum here, but reverted it (#22637) because ConditionalPut considers checksums in deciding whether things match (#22636). CC @nvanbenschoten

**Comment by nvanbenschoten** [comment]
Interesting. If my memory serves me correctly, @mjibson did upgrade to the version with the checksum change before we pulled it. If the lack of a checksum on certain keys is causing this issue then it would make sense that dumping and restoring the data would fix it.
