### ISSUE TITLE
build: pkg/sql/lex/predicates.go:60:14: undefined: reservedKeywords

### ISSUE THREAD

**Issue by nim-nim** [cockroachdb/cockroach#23992]
With:
* go 1.9.4 x86_64
*  github.com/cockroachdb/cockroach ea5f8b22ba951799b76c84502aaab4456fe00a46

While trying to build:

```
/usr/lib/golang/pkg/tool/linux_amd64/compile -o $WORK/github.com/cockroachdb/cockroach/pkg/sql/sem/types.a -trimpath $WORK -shared -goversion go1.9.4 -p github.com/cockroachdb/cockroach/pkg/sql/sem/types -complete -installsuffix shared -buildid 37fb7a082116c7a473b58359e82c82ad215
c6f08 -D _/builddir/build/BUILD/cockroach-ea5f8b22ba951799b76c84502aaab4456fe00a46/_build/src/github.com/cockroachdb/cockroach/pkg/sql/sem/types -I $WORK -I /builddir/build/BUILD/cockroach-ea5f8b22ba951799b76c84502aaab4456fe00a46/_build/pkg/linux_amd64_shared -I /usr/share/gocode
/pkg/linux_amd64_shared -pack ./oid.go ./types.go
github.com/cockroachdb/cockroach/pkg/util/tracing
# github.com/cockroachdb/cockroach/pkg/sql/lex
pkg/sql/lex/predicates.go:60:14: undefined: reservedKeywords
```

**Comment by jordanlewis** [comment]
How are you trying to build cockroach? You need to use `make build`, and not `go build`, because we have a lot of code generators and other things that need to get run outside of the Go toolchain as the first build step.

**Comment by nim-nim** [comment]
ah, drat, I need to pass specific flags to the go parameters for the QA guys, and go flag passing is whoefully under-standardised and a PITA in general

Do you have a make target that does everything needing to be done outside the go toolchain?

**Comment by jordanlewis** [comment]
Just run `make build` first. Then, you can run `go build` afterwards and it will do the right thing.

**Comment by nim-nim** [comment]
Will try it, thanks!

**Comment by salasrod** [comment]
`make build` does not work for me, and it fails with the exact same error.

**Comment by salasrod** [comment]
This is on the `release-2.0` branch.

**Comment by knz** [comment]
@benesch did your PR for this make it through?
