### ISSUE TITLE
storage: node not recovering after being offline for a long time

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#23994]
@jordanlewis's tpcc-new test cluster has a node whose replicate queue is seriously backed up. The tl;dr is that it isn't recovering well after having been offline for about 24 hours. While it was offline, all of its replicas were removed, and many of the ranges that they were a part of are now on an entirely new set of nodes. My raw notes:

* n13 is in a very bad state
* its replicas aren't learning about the fact that they've been removed from the range
  * there are 2 different forms of this -- one where the range is dormant (no active leaseholder) and one where it's alive but n13 doesn't know any of the current replicas because they all changed out from underneath it
* the logs on n13 don't go back far enough to tell exactly when or how long it was down, but judging by the availability of metrics for n13 in the admin UI it was offline from 2018-03-14T17:09:00 to 2018-03-15T17:15:00
  * that explains how it got so out-of-date
* the replicate queue is so backed up because it's trying to acquire the lease on these ranges (of the latter variety, where no replicas are known), which blocks in tryExecuteWriteBatch [1] for the entire 60 second context deadline [2]
* we aren't handling the "raft group deleted" error in a way that triggers us to delete the replica, so we just keep trying over and over every 4.4 seconds for basically forever [3]

We clearly aren't handling the `RaftGroupDeletedError` properly. I can't remember this coming up before, but it'd be very surprising if it hasn't. I'm probably just not remembering/searching properly. Anything come to mind, @petermattis?

[1]
```
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).tryExecuteWriteBatch(0xc4258d3500, 0x25324e0, 0xc43dde0400, 0x151cca16d794416c, 0x0, 0x0, 0x0, 0x2b3f, 0x0, 0x0, ...)
	/home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2764 +0x682
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).executeWriteBatch(0xc4258d3500, 0x25324e0, 0xc43dde0400, 0x151cca16d794416c, 0x0, 0x0, 0x0, 0x2b3f, 0x0, 0x0, ...)
	/home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:2588 +0xae
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).Send(0xc4258d3500, 0x25324e0, 0xc43dde0400, 0x151cca16d794416c, 0x0, 0x0, 0x0, 0x2b3f, 0x0, 0x0, ...)
	/home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1891 +0x69d
github.com/cockroachdb/cockroach/pkg/storage.(*pendingLeaseRequest).requestLeaseAsync.func2(0x25324e0, 0xc43dde0400)
	/home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_range_lease.go:310 +0x5af
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc42051c000, 0x25324e0, 0xc43dde0400, 0xc429044240, 0x35, 0x25502a0, 0xc420312b00, 0xc43a738990)
	/home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:266 +0xe6
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
	/home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:261 +0x133
```

[2]
```
W180317 19:57:13.622870 3432535 storage/replica.go:1502  [replicate,n13,s13,r6258/3:/Table/58/1/1383/3/-1881/6…] have been waiting 1m0s attempting to acquire lease
E180317 19:57:13.622906 3432535 storage/replica.go:1508  [replicate,n13,s13,r6258/3:/Table/58/1/1383/3/-1881/6…] lease acquisition failed: context deadline exceeded
I180317 19:57:13.622926 3432535 storage/queue.go:709  [replicate,n13,s13,r6258/3:/Table/58/1/1383/3/-1881/6…] [NotLeaseHolderError] r6258: replica (n13,s13):3 not lease holder; lease holder unknown; skipping
I180317 19:57:13.622933 3432535 storage/queue.go:642  [replicate,n13,s13,r6258/3:/Table/58/1/1383/3/-1881/6…] done 1m0.000358194s
```

[3]
```
W180317 18:50:13.405686 1486 storage/store.go:3458  [n13,s13,r6258/3:/Table/58/1/1383/3/-1881/6…] got error from r6258, replica (n24,s24):4: raft group deleted
W180317 18:50:13.405778 1823732 storage/store.go:3458  [n13,s13,r6258/3:/Table/58/1/1383/3/-1881/6…] got error from r6258, replica (n19,s19):5: raft group deleted
W180317 18:50:13.405948 1535 storage/store.go:3458  [n13,s13,r6258/3:/Table/58/1/1383/3/-1881/6…] got error from r6258, replica (n9,s9):1: raft group deleted
W180317 18:50:17.804833 1823732 storage/store.go:3458  [n13,s13,r6258/3:/Table/58/1/1383/3/-1881/6…] got error from r6258, replica (n19,s19):5: raft group deleted
W180317 18:50:17.804874 1535 storage/store.go:3458  [n13,s13,r6258/3:/Table/58/1/1383/3/-1881/6…] got error from r6258, replica (n9,s9):1: raft group deleted
W180317 18:50:17.804909 1486 storage/store.go:3458  [n13,s13,r6258/3:/Table/58/1/1383/3/-1881/6…] got error from r6258, replica (n24,s24):4: raft group deleted
...
W180317 20:02:09.805095 1486 storage/store.go:3458  [n13,s13,r6258/3:/Table/58/1/1383/3/-1881/6…] got error from r6258, replica (n24,s24):4: raft group deleted
W180317 20:02:09.805135 1823732 storage/store.go:3458  [n13,s13,r6258/3:/Table/58/1/1383/3/-1881/6…] got error from r6258, replica (n19,s19):5: raft group deleted
W180317 20:02:09.805232 1535 storage/store.go:3458  [n13,s13,r6258/3:/Table/58/1/1383/3/-1881/6…] got error from r6258, replica (n9,s9):1: raft group deleted
```

**Comment by a-robinson** [comment]
I suppose we don't have any code in the write path that recognizes that none of the other replicas are still around, but I'm not yet sure why the replica GC queue isn't kicking in for these ranges.

**Comment by a-robinson** [comment]
Hm, it could be because our replica GC queue had special logic to queue a replica more aggressively when it's in a raft candidate state. That was considered a sign that a replica was out of touch with its peers, but now that prevote is enabled the stuck replicas are in the "precandidate" state. It seems likely we need to update this code to also consider the precandidate state:

https://github.com/cockroachdb/cockroach/blob/512f1543beea26f135938e878e5a3df289c9ff0f/pkg/storage/replica_gc_queue.go#L138:57

**Comment by petermattis** [comment]
I'm not entirely familiar with pre-vote, but it does seem likely that this replicas would never enter the candidate state. Cc @bdarnell who would know for certain.
