### ISSUE TITLE
performance tuning compared to postgres?

### ISSUE THREAD

**Issue by dirkpetersen** [cockroachdb/cockroach#24005]
I have a table with about a billion rows and id like to do fast substring searches like '%blabla%' in some text fields.  The database size on postgres is about 600G .

To test performance i have dumped a smaller table (1.2 G) and imported it to cockroach with psql, however when I run my first test query it seems cockroach is only about half as fast as postgres. Neither database has setup any indices and the hardware is similar, except I am throwing 3 nodes at cockroach and one at postgres.

petersen@rhino2:$ time psql -h gizmog17 -p 26257 -U root petersen -c "SELECT * FROM mountstat WHERE mountstat.mountpoint LIKE '%fast%';" > output

real	0m34.910s
user	0m11.738s
sys	0m1.107s

petersen@rhino2:$ time psql -h mydb -p 32063 -U dirk petersen -c "SELECT * FROM mountstat WHERE mountstat.mountpoint LIKE '%fast%';" > output

real	0m14.661s
user	0m11.995s
sys	0m0.956s

my 3 node cockroach cluster (16 core , 256GB RAM each) is working hard and uses lots of resources  

![image](https://user-images.githubusercontent.com/1427719/37567922-33ddab08-2a8b-11e8-9cb6-1afa72541e97.png)

I just used the default production setup:

cockroach start --insecure \
        --host=n1 \
        --join=n1:26257,n2:26257,n3:26257 \
        --cache=25% \
        --max-sql-memory=25%

**Comment by dirkpetersen** [comment]
I should add that each of the 3 nodes have storage with about 1.5 GB /s throughput, however there is no disk read activity when the query runs, data seems to come all from memory.

also a simple row count seems to be 10 times faster on postgres. 

petersen@rhino2:$ time psql -h gizmog17 -p 26257 -U root petersen -c "SELECT count(*) FROM mountstat;"
 count(*) 
----------
  6610080
(1 row)

real	0m11.303s
user	0m0.001s
sys	0m0.008s


petersen@rhino2:$ time psql -h mydb -p 32063 -U dirk petersen -c "SELECT count(*) FROM mountstat;"
  count  
---------
 6614155
(1 row)

real	0m1.035s
user	0m0.003s
sys	0m0.007s

**Comment by alanhamlett** [comment]
@dirkpetersen just curious, what version of cockroach and postgres are you using here?

**Comment by dirkpetersen** [comment]
I have been using Postgres 9.6.1 and the postgres 10.1 psql client tools . The postgres server is a ubuntu 16.04 machine and postgres runs inside a docker container which was restricted to a single cpu and 1GB memory  

the 3 cockroach machines were running  ubuntu 14.04 and cokroach ran right on the OS (no docker)

```
cockroach version
Build Tag:    v1.1.6
Build Time:   2018/03/12 17:58:05
Distribution: CCL
Platform:     linux amd64
Go Version:   go1.8.3
C Compiler:   gcc 6.3.0
Build SHA-1:  f6b7567d85d54689a7d1b61907336d1bc72b09a4
Build Type:   release-gnu
 ```

**Comment by tim-o** [comment]
@dirkpetersen - if you're still considering CRDB, have you tested the same in a more recent version (currently 2.0.4 or 2.1-alpha)? There have been significant improvements in SQL query execution since March.

Given the age of the issue, I'm going to mark as closed for now as a matter of housekeeping. That said, if you're still running into an issue let us know and we'll look into it. The first step would be to get the schema for your test so that we can see if we can reproduce the same results.
