### ISSUE TITLE
cli: client side load balancing through proxy mode

### ISSUE THREAD

**Issue by alanhamlett** [cockroachdb/cockroach#24001]
**FEATURE REQUEST**

Ability for cockroach to run in a `proxy` mode, where it acts as a load balancer for the localhost machine to connect to the cluster. Instead of connecting to `<node1 address>:26257/<database>` you would run `cockroach proxy --join=<node1 address>:26257,<node2 address>:26257` then the client connects to `localhost:26257/<database>` and it's queries are automatically load balanced to nodes in the cluster.

Think of it like the current haproxy load balancing setup running locally on each client.

An extra bonus would be discovering all node addresses automatically from an initial subset of node addresses.

Related to cockroachdb/docs#978.

This is a Nice-to-have. Current work-around is using a single load balancer for all clients.

Jira issue: CRDB-6359

**Comment by 0xbaadf00d** [comment]
PostgreSQL driver has already this feature, at least the Java version.

```
jdbc:postgresql://node1,node2,node3/accounting?loadBalanceHosts=true
```

**Comment by alanhamlett** [comment]
Yes, but clients in other languages don't support multiple connections. Instead of implementing load balancing in all the client libraries it's easier to just run a local load balancer. Also, this way the load balancer knows about Cockroach's routing and could auto-discover nodes that are part of the cluster.

**Comment by alanhamlett** [comment]
RethinkDB used proxy nodes and one feature was offloading query processing to clients:
https://github.com/rethinkdb/docs/issues/962

Instead of just acting like a load balancer, could a cockroach proxy also offload some query planning to clients?

**Comment by knz** [comment]
@andreimatei in case you need a tracking issue for your work, this one already exists.

**Comment by knz** [comment]
We recommend haproxy and pgbouncer for this.
