### ISSUE TITLE
ui: disable segment.io : malware / tracking ?

### ISSUE THREAD

**Issue by 0xbaadf00d** [cockroachdb/cockroach#24009]
Hello,

Bad surprise from the web UI, why it try to contact segment.io when administrator/tech visiting each pages of the web UI. How to remove it or completly disable it ? It is an admin/stats panel, not a public website who need to collect data and Integrate marketing and analytics stack.

![image](https://user-images.githubusercontent.com/1005086/37583076-0686e2da-2b50-11e8-8848-918d2b0191f9.png)

If this feature is usefull for some peoples, why use this "hardcoded" provider, why not just allow injection of custom html/js tag taken from the configuration.

**Comment by couchand** [comment]
As I mentioned on #17937, the Segment integration provides anonymized analytics to Cockroach Labs to help us understand what features are useful and how to prioritize our development efforts. It plays the same role as that of our query statistics and other diagnostic reporting.

As described in the documentation linked here, you can turn this feature off if it's unacceptable to send this anonymous usage information to us.
