### ISSUE TITLE
server: Harden status/admin endpoints' enforcement of server.remote_debugging.mode setting

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#24019]
As of #23851, we attempt to restrict all sensitive information from the various status/admin endpoints in accordance with the server.remote_debugging.mode setting. However, the implementation of #23851 is fragile -- it added a context annotation step at the start of every admin/status server function that's needed to ensure we can properly tell whether a request came over HTTP or directly on gRPC. If that annotation is forgotten on a future endpoint, it could leak sensitive information.

We need to better harden this. It could just be by writing a better test (#23918), or we could make the context metadata propagation from #23851 impossible to forget, or we could start relying on proper UI authentication.

**Comment by a-robinson** [comment]
As of https://github.com/cockroachdb/cockroach/pull/23851, we attempt to restrict all sensitive information from the various status/admin endpoints in accordance with the `server.remote_debugging.mode` setting. However, the implementation of #23851 is fragile -- it added a context annotation step at the start of every admin/status server function that's needed to ensure we can properly tell whether a request came over HTTP or directly on gRPC. If that annotation is forgotten on a future endpoint, it could leak sensitive information.

We need to better harden this. It could just be by writing a better test (https://github.com/cockroachdb/cockroach/issues/23918), or we could make the context metadata propagation from #23851 impossible to forget, or we could start relying on proper UI authentication.

**Comment by knz** [comment]
cc @aaron-crl @thtruo for tracking

**Comment by knz** [comment]
The `server.remote_debugging.mode` setting has been removed and all the relevant http endpoints are now authenticated.
