### ISSUE TITLE
ui: consistent & useful loading indicators [460]

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/cockroach#24011]
![image](https://user-images.githubusercontent.com/894257/37597137-d6032902-2b54-11e8-84d2-6e5c2d6932e5.png)

- [ ] Page shouldn't say `no results` when in reality its loading
- [x] Page loses highlighted database icon in the left-hand nav so it's not clear where you came from

**Comment by couchand** [comment]
The second point is covered in #24069.  I'm surprised to see that there's not already an issue describing the inconsistent/annoying loading states across all pages.  The closest I can find is #19347, though that is restricted to the databases page (which has it's own issues with data loading).  So I'm repurposing this issue to stand in for regularizing our loading states across all pages.

**Comment by vilterp** [comment]
Agree that a consistent pattern for data loading (and error) states deserves its own issue. #1 highest-value refactor we could do IMO.
