### ISSUE TITLE
kv: rollback after "deadline exceeded" gets retriable error

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#24020]
When investigating #18684, me and @benesch seemed to see a client get a retriable error for an `EndTransaction{commit:false}` request. The transaction was being rolled back because it hit the `TransactionStatusError` because of a deadline exceeded, and then the rollback attempt gets the retriable error - which is nonsensical.
We suspected this code to generate the error on rollback:
https://github.com/cockroachdb/cockroach/blob/f75abe0eaab5b1db975105bfcf614daad5f44354/pkg/kv/txn_coord_sender.go#L1156

cc @spencerkimball in case he just knows what's wrong here

**Comment by benesch** [comment]
A trace of the weirdness is here: https://gist.github.com/benesch/deaca885eb3007069e1b32e7275f2854#file-gistfile1-txt-L815-L840

**Comment by tschottdorf** [comment]
@nstewart I'm not sure why you added S-3-erroneous-edge-case here. Can you elaborate?

**Comment by ajwerner** [comment]
@lunevalex this declaration of bankruptcy without a note that we haven't actually fixed these problems is pretty alarming. I'm re-opening this as we are looking at some related code and @andreimatei notes this is still current.

**Comment by fqazi** [comment]
@ajwerner Took a look, and I tried a few attempts to repro the same scenario, and this issue is confirmed as stale. So, closing it.
