### ISSUE TITLE
sql: assign txn deadline from extended, not initial, lease

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#24041]
The drop roachtest currently sporadically [fails on this line](https://github.com/cockroachdb/cockroach/blob/7555aabc397ec13ec03e5c4e8fa6cbe4bf6dcba5/pkg/cmd/roachtest/drop.go#L61) with a

> transaction status error: deadline exceeded.

As I understand, this is due to the following:

1. the transaction runs for a long time, and its deadline is set when it starts
2. the transaction can be pushed forward in time significantly (but should still be able to commit due to the deadline)
3. the table lease is either not extended (because there are no other new requests coming in for the table) or it is extended but the in-progress transaction does not get to use the new descriptor (even though it theoretically should be able to).

Either way, what *should* happen is that the sql subsystem realizes that there is a long-running transaction holding on to that lease, and extends the lease appropriately, while allowing the transaction to use the extended lease's deadline when it commits.

This is bound to be a relatively common issue with long-running transactions.

See also https://github.com/cockroachdb/cockroach/pull/23982#issuecomment-373993334

cc @benesch for fact checking

**Comment by benesch** [comment]
Yeah, this is my understanding of the issue as well.

**Comment by andreimatei** [comment]
I'm going to close this in favor of #18684 which is the tracking bug for txn deadlines and improvements thereof.
