### ISSUE TITLE
Same node double registerd

### ISSUE THREAD

**Issue by lucevers** [cockroachdb/cockroach#24059]
**BUG REPORT**

. Please describe the issue you observed:

- What did you do?
     Upgrade to v1.1.6
     3 nodes version 1.1.5
     Start update node 1 to v1.1.6 wait until stable.
     Result node1 v1.1.6  node2 v1.1.5  node3 v1.1.5
     If you now stop and start node1 again you get an additional node in the list.
    I have now a node1 (state healthy) , node2 (state healthy), node3(state health), node4 (= Node1) (state Dead)
- What did you expect to see?
    Only the 3  installed nodes
- What did you see instead?
    4 node and one double (dead)

How can I remove node 4 (= Node1 extra same ip)

**Comment by tschottdorf** [comment]
Are you using persistent storage? From your description, it looks like you were running with ephemeral disks (or you specified a different store directory when you restarted the node, so that it joined as a new one).

For your last question, see the [docs on removing nodes](https://www.cockroachlabs.com/docs/stable/remove-nodes.html).

**Comment by lucevers** [comment]
The issue here is not a real problem for the running cluster but caused by the fact that I cannot remove uncommissioned nodes.
The dead nodes stay visual in the Gui, seems not possible to clean up?
After a while, the dead nodes will be a big list, a remove button on the Gui or a cli command would be welcome.

**Comment by tschottdorf** [comment]
Ah. In that case, I think your problem will disappear once you upgrade to v2.0 which is going to be released in April. Note that the node still has to be decommissioned or it will be shown forever even in v2.0. You can run `./cockroach node decommission <nodeid> --wait=live` to achieve this.

**Comment by lucevers** [comment]
Thanks!  I'll wait for v2.0.
