### ISSUE TITLE
partitionccl: partitioning hangs for 30s and has inconsistent UX relative to other ALTERs

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/cockroach#24054]
Ran the command `alter table movr.vehicles partition by list (city) ( partition north_america values in ('new york', 'boston', 'san francisco'), partition europe values in ('paris'))` and saw the following behavior:

This command hung for 30 seconds before completing. There are 50k rows in this table. The schema is:

![image](https://user-images.githubusercontent.com/894257/37633196-cac0a8e4-2bc7-11e8-880d-133efb9af230.png)

I see an event that a schema change started but there's not an end event, even though I see other schema changes ending in the event log.

![image](https://user-images.githubusercontent.com/894257/37633047-378ae346-2bc7-11e8-9222-42a61f3181e7.png)
 
If I have to wait for 30 seconds I would expect this to show up in the jobs table, especially when according to docs "Schema changes through ALTER TABLE" are supposed to be there.

![image](https://user-images.githubusercontent.com/894257/37633151-a2829824-2bc7-11e8-848c-e191994cb4dc.png)

**Comment by nstewart** [comment]
cc @awoods187 @dianasaur323

**Comment by benesch** [comment]
I'm curious if `ALTER TABLE ... RENAME TO ...` exhibits the same problem. If it does, it's definitely not partitioning's fault. @nstewart, next time you're testing the demo, could you see if renaming the table is as slow?

**Comment by nstewart** [comment]
```
root@35.197.68.125:26257/> alter table movr.vehicles rename to movr.vehicle;
RENAME TABLE

Time: 3.172001189s

root@35.197.68.125:26257/> alter table movr.vehicle rename to movr.vehicles;
RENAME TABLE

Time: 6.13844549s

root@35.197.68.125:26257/> alter table movr.vehicles partition by list (city) ( partition north_america values in ('new york', 'boston', 'san francisco'), partition europe values in ('paris'));
ALTER TABLE

Time: 1.988987371s
```

This time it was much faster. Neither of the `rename to` actions showed up in the event log though. We can track that separately.

**Comment by dianasaur323** [comment]
The event log issue is a known issue, and on @piyush-singh's plate for the next release.

**Comment by nstewart** [comment]
@piyush-singh can you share a link to where the event log issue is being tracked?

**Comment by rolandcrosby** [comment]
@jordanlewis can you take a look at this?

**Comment by jordanlewis** [comment]
Hmm, I'm not entirely sure what the ask here is. Is it about the event log in particular, or investigating some slowness? If the latter, I'm inclined to close as this was over a year ago. If it's about the event log, should we rename/make a new issue?

**Comment by rolandcrosby** [comment]
@piyush-singh do you have another issue we can rely on for general improvements to partitioning visibility and status? If so I think we can close this.

**Comment by piyush-singh** [comment]
Yes indeed, Andy is tracking enhancements on #31551. We can probably close out this issue in favor of that one.
