### ISSUE TITLE
sql: Hibernate's use of int/float operations

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#24063]
@justinj to fill out what this is about.

**Comment by justinj** [comment]
Basically there are some operations that Hibernate does that relies on Postgres' implicit conversions (for say, `1::INT + 1::FLOAT`). I don't remember offhand what the context for those are, but it's exercised by `testQuotientConversion` in the Hibernate test suite.

I didn't dig deep enough into this issue in particular to figure out if this could be resolved just by our adding an overload for `+` for `int + float` and `float + int` and other similar situations, though.
