### ISSUE TITLE
storage: Test removal of replicas whose peers have all changed

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#24068]
After enabling raft prevote, we experienced a regression in how a node behaves after being offline for so long that many of the other replicas in the cluster have moved around (https://github.com/cockroachdb/cockroach/issues/23994). The replicas on the offline node were unable to contact any of their peers but didn't take that as a sign that they may have been removed from their respective ranges, leading to a very large buildup in the queues and a very slow GC process for the old replicas.

https://github.com/cockroachdb/cockroach/pull/23995 partially fixed the problem, but we need a test that would catch this kind of behavioral problem. It may be overkill to turn exactly these steps into a roach test, but my process for locally vetting the changes was:

1. Start 3 nodes with locality `a=1`
1. Start 3 nodes with locality `a=2`
1. Create a table
1. Split the table 1000 times
1. Set all replicas in the table to `a=1`: `echo 'constraints: [+a=1]' | ./cockroach zone set test -f -`
1. Wait for the replicas to move
1. Kill n3
1. Set all replicas in the table to `a=2`: `echo 'constraints: [+a=2]' | ./cockroach zone set test -f -`
1. Wait for the replicas to move
1. Restart n3
1. Track its progress at GC'ing replicas

Note that because of https://github.com/cockroachdb/cockroach/issues/24067, we can't test that all old replicas are GC'ed unless we also increment the epochs of n1 and n2 to make n3 realize their old leases aren't still active.

**Comment by tbg** [comment]
Closing for #24067 (which in turn is about to be closed by #32845). @a-robinson could you take a look to confirm that what you're describing above is close enough to what I did?

I suspect the note at the end of your post explains a question I had on the PR, so thanks for that.

**Comment by a-robinson** [comment]
Yes, that test LGTM.
