### ISSUE TITLE
sql: 32 bit SERIAL type

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#24062]
Cockroach's SERIAL type is currently 64 bits. With the new added SEQUENCE functionality it is possible to implement SERIAL as a postgres compatible 32 bit type. 

https://github.com/cockroachdb/cockroach/issues/18688

This might involve setting the current SERIAL type to a supported backwards compatibility type and introducing another type under the hood for new instances of the type. Caching functionality needs to be implemented for performance.

**Comment by vivekmenezes** [comment]
also related to https://github.com/cockroachdb/cockroach/issues/22607

**Comment by knz** [comment]
pg has separate `serial` and `bigserial` types. They correspond to `int/int4` (32-bit) and `bigint/int8` (64 bit) integer types. CockroachDB should arguably do the same.
