### ISSUE TITLE
ui: highlight database sidebar link when on table details page

### ISSUE THREAD

**Issue by couchand** [cockroachdb/cockroach#24069]
The sidebar link for the databases page is not highlighted when on the table details page, because the URL for the index page is `/databases` and the URL for the table details is `/database/:dbName/table/:tableName`.  We should do some teaking to the default logic to make this highlight in the way you'd expect.

**Comment by vilterp** [comment]
Node details is the same thing. (As would be any other page that has a list of items, and then a detail page for each)

**Comment by couchand** [comment]
There's no sidebar link for nodes.

**Comment by vilterp** [comment]
Cluster overview is essentially the link for nodes. It has two states: a list of nodes and a map of nodes, grouped by locality.
