### ISSUE TITLE
ui: reload / autorefresh control

### ISSUE THREAD

**Issue by vilterp** [cockroachdb/cockroach#24085]
Some of our pages autorefresh every ten seconds, some don't. If they don't, you need to reload the whole page, which is slow.

Maybe we could have a standardized control that we put on many pages, which has:
- a "refresh" button (reloads data, not the whole page)
- an "autorefresh" checkbox

This could even be integrated into a data loading higher-order component. cc @mrtracy

**Comment by couchand** [comment]
As a general principle, I think it would be nice for pages to always show up-to-date data.  That seems to be the direction that most modern development is going in, and it makes for a more useful experience in most cases.  If we need to address specific usability concerns to get to that point we should take them as they arise.  For instance, if the particular sequence of API calls is slow (like with the databases page) we should optimize it by making fewer round-trips (particularly dependent round-trips).

There are potential exceptions to this (@BramGruneir has suggested that the n^2 latency chart is a good one), but I think they're restricted to debug pages.  It's worth evaluating these and identifying where they fit in.

**Comment by vilterp** [comment]
I agree that pages should always show up-to-date data. The way I see it, either you achieve that by having your backend push out updates (hard; we won't do this any time soon) or you should be honest about the fact that you don't (and are polling), by providing a refresh button and an autorefresh checkbox. Right now we're in a middle ground where it's not quite clear to the user what's going on, so they reload the entire page out of uncertainty, which is slow.

I realize that it'd be difficult to figure out a place for these controls on every single page.

**Comment by couchand** [comment]
related to  #12860
