### ISSUE TITLE
server: tag internal clusters as internal

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#24111]
mark all instances of testing and otherwise internal clusters with organization "Cockroach Labs"

Related to https://github.com/cockroachdb/cockroach/pull/20790

cc @benesch

**Comment by bdarnell** [comment]
While we're at it we should generally ensure that our internal clusters set the COCKROACH_REPORT_SENSITIVE_DETAILS environment variable so we can tell when they show up in sentry.

**Comment by petermattis** [comment]
@dt This is done, right?

**Comment by dt** [comment]
yep, we send an `internal` flag when the enterprise license is granted to anything containing "Cockroach Labs" I think
