### ISSUE TITLE
ui: cluster viz & overview: color & typography tweaks

### ISSUE THREAD

**Issue by vilterp** [cockroachdb/cockroach#24125]
From @josueeee:

![image](https://user-images.githubusercontent.com/7341/37731616-0a142d34-2d19-11e8-8482-eeca6f395ab2.png)
![image](https://user-images.githubusercontent.com/7341/37731621-0db92c64-2d19-11e8-85e9-ed0e150e1461.png)
![image](https://user-images.githubusercontent.com/7341/37731625-11cce0de-2d19-11e8-8da3-ad1d68db092a.png)
![image](https://user-images.githubusercontent.com/7341/37731634-17ed1650-2d19-11e8-8abd-4e970a0c48c5.png)
![image](https://user-images.githubusercontent.com/7341/37731666-2ae90ec6-2d19-11e8-9af2-75340fe84b7b.png)
![image](https://user-images.githubusercontent.com/7341/37731677-2ff56b26-2d19-11e8-881e-b16f32641c93.png)
![image](https://user-images.githubusercontent.com/7341/37731692-3560c4ca-2d19-11e8-8db4-3481a112bcad.png)

- #3a7de1 replace all the light blue instances with this new blue
- #e2e5ee this is the map water color
- #ffffff the land on the map should be white

**Comment by josueeee** [comment]
Match the padding of the Node List for OSS with the padding from the Cluster Overview:
<img width="562" alt="padding" src="https://user-images.githubusercontent.com/29442020/37732825-97880e4e-2d1c-11e8-961c-d5f47fd3e5e6.png">
