### ISSUE TITLE
build: incrementally recompile protobufs

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#24122]
Our Makefile isn't smart enough to only recompile the protobufs that have changed. This means unnecessary extra rebuilds whenever one protobuf changes, including unnecessary and slow rebuilds of the UI.

Epic CRDB-10447

Jira issue: CRDB-5786

**Comment by rickystewart** [comment]
still relevant, although this is going to be fixed at the Bazel level rather than the `make` level
