### ISSUE TITLE
sql: extract SequenceOperators from the planner

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#24130]
`SequenceOperators` is an interface grouping methods around manipulating sequences. It's functionality is related to `sessiondata.SequenceState`, although the former is more powerful and allows mutations too.
The separation of interfaces might make sense for read-only vs mutation operations, but at least the builtin currval() function is readonly and needs `SequenceOperators` to resolve the name.
DistSQL only has access to `SequenceState`, which makes a query like:
```
SELECT c, currval('distsql_test') FROM t
```
to get the nonsensical error:
```
pq: currval(): cannot backfill such sequence operation
```

I don't know what the best thing to do about it is, since the normal implementer of `SequenceOperators` is the planner, which distsql execution doesn't have access to.

**Comment by andreimatei** [comment]
#24131 adds a test that's skipped because of this issue

**Comment by knz** [comment]
This is a dup of another issue, no time to search for it @vivekmenezes

**Comment by vilterp** [comment]
I think this is done. These now live in the SequenceOperators interface, implemented by `planner`, `subqueryVisitor`, and `dummySequenceOperators` (in DistSQL): https://github.com/cockroachdb/cockroach/blob/5d0be37a789e1746eab06210be298b8b8eab91f9/pkg/sql/sem/tree/eval.go#L2364-L2380

Closing; someone can reopen if I'm wrong and something more needs to be done here.
