### ISSUE TITLE
pgwire: `pq: unexpected message 'E'; expected ReadyForQuery` errors when killing processes on kubernetes

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#24149]
Repro steps:

* Create a 3 node insecure cockroach cluster on kubernetes
* Start up a load generator pod using [this kubernetes config file](https://gist.github.com/a-robinson/893d68096194970138db1fc97a4dae1c): `kubectl create -f loadgen-pod.yaml`
* Start aggressively killing pods in one terminal: `while true; do kc delete pod cockroachdb-0; sleep 60; kc delete pod cockroachdb-1; sleep 60; kc delete pod cockroachdb-2; sleep 60; done`
* Watch the output of the load generator pod: `kubectl logs loadgen-kv`

At some point, you'll see output like:

```
2018/03/22 14:56:15 driver: bad connection
2018/03/22 14:56:15 driver: bad connection
2018/03/22 14:56:15 driver: bad connection
2018/03/22 14:56:15 driver: bad connection
  26m12s      433           62.0          116.9   1342.2   2080.4   2415.9   5905.6
2018/03/22 14:56:16 driver: bad connection
  26m13s      434          104.9          116.8    402.7   3355.4   4831.8   5100.3
2018/03/22 14:56:17 pq: unexpected message 'E'; expected ReadyForQuery
2018/03/22 14:56:17 pq: unexpected message 'E'; expected ReadyForQuery
2018/03/22 14:56:17 pq: unexpected message 'E'; expected ReadyForQuery
2018/03/22 14:56:17 driver: bad connection
  26m14s      438          125.0          116.9    453.0   3355.4   6979.3   6979.3
  26m15s      438          134.0          116.9    385.9    604.0    771.8   1006.6
  26m16s      438          107.1          116.9    201.3    436.2    503.3    503.3
  26m17s      438          110.8          116.9    113.2    318.8    503.3    520.1
  26m18s      438           54.1          116.8     46.1    125.8    134.2    134.2
  26m19s      438            0.0          116.7      0.0      0.0      0.0      0.0
  26m20s      438            0.0          116.7      0.0      0.0      0.0      0.0
2018/03/22 14:56:24 pq: result is ambiguous (error=rpc error: code = FailedPrecondition desc = grpc: the client connection is closing [exhausted])
2018/03/22 14:56:24 pq: result is ambiguous (error=initial connection heartbeat failed: rpc error: code = Unavailable desc = all SubConns are in TransientFailure [exhausted])
2018/03/22 14:56:24 pq: result is ambiguous (error=initial connection heartbeat failed: rpc error: code = Unavailable desc = all SubConns are in TransientFailure [exhausted])
2018/03/22 14:56:24 pq: result is ambiguous (error=initial connection heartbeat failed: rpc error: code = Unavailable desc = all SubConns are in TransientFailure [exhausted])
```

The `pq: unexpected message 'E'; expected ReadyForQuery` errors are suspicious looking. They seem to get emitted while a node is draining. I never saw them when doing more controlled drains (i.e. when waiting more than 1 minute between process restarts).

I'm using a build from a couple weeks ago (47cb9bff9978b9a08446805ae12c2f3466f584d0), in case that matters. 

cc @andreimatei @asubiotto for debugging ideas and prioritization, since I don't have a sense for whether it's important.

**Comment by andreimatei** [comment]
I don't think it does

**Comment by andreimatei** [comment]
Also seen by a customer while decommissioning nodes.

**Comment by jordanlewis** [comment]
Ping @andreimatei have you had any luck reproducing this?

**Comment by andreimatei** [comment]
I haven't tried, but I will. Unless you want to take it :P

**Comment by andreimatei** [comment]
I suspect the problem here is that when a node is draining, we sometimes send two consecutive error messages on a connection, and lib/pq doesn't like that.
I think the way draining works is that, if it's waited enough for transactions to finish, it will then cancel the context of the transaction, which will likely cause an in-flight query to error out. And then we pile on another `AdminShutdown` error after the query error, which appears to be not cool:
https://github.com/cockroachdb/cockroach/blob/b8303ba074c8a6c7cd8698b55da2cb47f0934cde/pkg/sql/pgwire/conn.go#L441

Also discussed in
https://github.com/cockroachdb/cockroach/issues/22630 with some notes on what pg does.

**Comment by andreimatei** [comment]
Time to pass this along to someone better.

**Comment by mjibson** [comment]
> Also seen by a customer while decommissioning nodes

@andreimatei Was this customer using Go and lib/pq or another driver? The [spec](https://www.postgresql.org/docs/10/protocol-flow.html) says

> A frontend must be prepared to accept ErrorResponse and NoticeResponse messages whenever it is expecting any other type of message.

So this may be a lib/pq bug.

**Comment by a-robinson** [comment]
> So this may be a lib/pq bug.

I've actually seen this recently when using lib/pq to talk to stock Postgres, so that's pretty feasible. I don't know what the state of the Postgres cluster was at the time.

**Comment by mjibson** [comment]
Ooh do you happen to know what was going on that caused a double error? I'd love to be able to induce that behavior from postgres so I can provably fix it in lib/pq.

**Comment by a-robinson** [comment]
No, unfortunately I don't have anything more than that. It happened like a month and a half ago so any context I had is long gone.

**Comment by knz** [comment]
I've checked and indeed the pg protocol says there can be multiple E(error) payloads so the client driver should accept it. I don't believe we should do something in crdb for this.
