### ISSUE TITLE
server: can't restart node on windows

### ISSUE THREAD

**Issue by 0xbaadf00d** [cockroachdb/cockroach#24144]
**Description**
Can't restart a node on windows, even if cockroach is run as "Administrator".

I try to delete .LOCK file but cluster don't run anymore. I have to delete data folder to get cockroach working again.

**Version**
```
Build Tag:    v2.0-beta.20180319
Build Time:   2018/03/19 19:04:00
Distribution: CCL
Platform:     windows amd64
Go Version:   go1.10
C Compiler:   gcc 6.3.0
Build SHA-1:  e0b123c2324586c2bd101e27bab468701f8efa5e
Build Type:   release
```

**Console (first start)**
```
PS D:\cockroach> .\cockroach.exe start --insecure
*
* WARNING: RUNNING IN INSECURE MODE!
*
* - Your cluster is open for any client that can access <all your IP addresses>.
* - Any user, even root, can log in without providing a password.
* - Any user, connecting as root, can read or write any data in your cluster.
* - There is no network encryption nor authentication, and thus no confidentiality.
*
* Check out how to secure your cluster: https://www.cockroachlabs.com/docs/v2.0/secure-a-cluster.html
*
CockroachDB node starting at 2018-03-22 06:52:26.0482344 +0000 UTC (took 6.4s)
build:               CCL v2.0-beta.20180319 @ 2018/03/19 19:04:00 (go1.10)
admin:               http://DEMON-CORE:8080
sql:                 postgresql://root@DEMON-CORE:26257?application_name=cockroach&sslmode=disable
logs:                D:\cockroach\cockroach-data\logs
temp dir:            D:\cockroach\cockroach-data\cockroach-temp236256839
external I/O path:   D:\cockroach\cockroach-data\extern
store[0]:            path=D:\cockroach\cockroach-data
status:              initialized new cluster
clusterID:           11421e61-616b-4ed9-ae06-2b6d196c2bd5
nodeID:              1
Note: a second interrupt will skip graceful shutdown and terminate forcefully
initiating graceful shutdown of server
server drained and shutdown completed
*
* INFO: interrupted
*
Failed running "start"
```

**Console (second start)**
```
PS D:\cockroach> .\cockroach.exe start --insecure
*
* WARNING: RUNNING IN INSECURE MODE!
*
* - Your cluster is open for any client that can access <all your IP addresses>.
* - Any user, even root, can log in without providing a password.
* - Any user, connecting as root, can read or write any data in your cluster.
* - There is no network encryption nor authentication, and thus no confidentiality.
*
* Check out how to secure your cluster: https://www.cockroachlabs.com/docs/v2.0/secure-a-cluster.html
*
*
* ERROR: could not cleanup temporary directories from record file: remove D:\cockroach\cockroach-data\cockroach-temp236256839\TEMP_DIR.LOCK: Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus.
*
Failed running "start"
```

**Comment by vilterp** [comment]
Hi @0xbaadf00d, have you checked with the OS that no other process is using that file? I'm not a windows expert, but something like [this](https://stackoverflow.com/questions/3565218/how-to-know-what-process-is-using-a-given-file?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa)?

**Comment by 0xbaadf00d** [comment]
Hello @vilterp 

Just checked again. Even if the server don't run, the second "launch" fail.


1. Run cockroach without --insecure, got a message like  "did you mean to use --insecure?"
2. Run cockroach with the --insecure, FAIL

```
PS C:\Users\thiba\Downloads\cockroach-v2.0-beta.20180326.windows-6.2-amd64> .\cockroach.exe start
*
* ERROR: failed to start server: problem using security settings, did you mean to use --insecure?: problem with CA certificate: not found
*
Failed running "start"
```
```
PS C:\Users\thiba\Downloads\cockroach-v2.0-beta.20180326.windows-6.2-amd64> .\cockroach.exe start --insecure
*
* WARNING: RUNNING IN INSECURE MODE!
*
* - Your cluster is open for any client that can access <all your IP addresses>.
* - Any user, even root, can log in without providing a password.
* - Any user, connecting as root, can read or write any data in your cluster.
* - There is no network encryption nor authentication, and thus no confidentiality.
*
* Check out how to secure your cluster: https://www.cockroachlabs.com/docs/v2.0/secure-a-cluster.html
*
*
* ERROR: could not cleanup temporary directories from record file: remove 
C:\Users\thiba\Downloads\cockroach-v2.0-beta.20180326.windows-6.2-amd64\cockroach-data\cockroach-temp015780739\TEMP_DIR.LOCK: Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus.
*
Failed running "start"
```

**Comment by BramGruneir** [comment]
@0xbaadf00d I've hit this too when testing our builds.  
For now, the guidance would be to just delete the temp directory, or even add a script to delete it.  Don't worry, there's no problem in doing so.

**Comment by nicolasparada** [comment]
Same here. It started with 2.0.

**Comment by bw-smarkwell** [comment]
Attaching log outputs.

Environment
Windows 10 Pro 1709
CockroachDB CCL v2.0.0 (x86_64-w64-mingw32, built 2018/04/03 21:03:23, go1.10)

First log is a series of requests via JDBC.  Second set of logs is during attempt to restart the node via the CLI.  

The process creation in both cases is all managed from the JVM process builder.  I do not believe this to be a root cause of the issue.  I have verified with [Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) and my Java code that both the PID nor the folder directory is held by any Windows process.  

In process explorer, Find -> Find Handle or DLL... then plug in the folder path.  This searches all processes running for any handles to that directory.

[cockroachexe.VAB.VAB_bwScott.2018-04-23T16_59_53Z.007500.log](https://github.com/cockroachdb/cockroach/files/1939276/cockroachexe.VAB.VAB_bwScott.2018-04-23T16_59_53Z.007500.log)
[cockroachexe.VAB.VAB_bwScott.2018-04-23T17_02_22Z.026392.log](https://github.com/cockroachdb/cockroach/files/1939277/cockroachexe.VAB.VAB_bwScott.2018-04-23T17_02_22Z.026392.log)


As with others, this started with the 2.0.0 build.

**Comment by bdarnell** [comment]
@knz Yes, the advisory locks were added in #20854. We used the rocksdb LockFile function so the temp dir should be locked in the same way as the rocksdb store itself. On Windows this uses

    hFile = CreateFileA(lockFname.c_str(), (GENERIC_READ | GENERIC_WRITE),
      ExclusiveAccessON, NULL, CREATE_ALWAYS,
      FILE_ATTRIBUTE_NORMAL, NULL);

I don't think this leaves the file locked after the process exits, but I'm not sure. (whatever it does, the same thing should happen for the data directory. This is not unique to the temp dir, that just happens to be the first filesystem lock we access)

**Comment by knz** [comment]
The lock is properly released when the process shuts down. I'm just proposing that this is not done properly if the process crashes.

**Comment by andreimatei** [comment]
I think we should verify if indeed the data dir has the same problem after a crash on Windows. If it doesn't, maybe we shouldn't use the advisory locks at all on windows for the temp dir if the OS doesn't implement them properly.

**Comment by BramGruneir** [comment]
I tested this with a proper shut down, a quick shutdown (crtl-c crtl-c) and process kill, and the it's the same problem each time.

**Comment by andreimatei** [comment]
So how do we *ever* manage to restart on windows? Do we create the advisory lock lazily the first time a query needs the temp dir?
And RocksDB's locks (if it uses them on Windows) presumably don't have this problem?

**Comment by knz** [comment]
@BramGruneir which was the "proper shutdown"? IS there a difference between a single ctrl+c and `cockroach quit`? (I suspect `cockroach quit` behavior might be different)

**Comment by BramGruneir** [comment]
I didn't try cockroach quit.  I can tonight.

**Comment by knz** [comment]
I'll champion a patch that removes the usage of locks. For the record, I had predicted this problem would occur:

https://github.com/cockroachdb/cockroach/issues/20673#issuecomment-354119194

> I would like to discourage thinking about and using locks for this purpose. Locks have this nasty habit of not working well if the user decides (and that's reasonable) to have their temp dir on a filesystem that doesn't support locks.
