### ISSUE TITLE
"unexpected value" cput error inserting into splitting table 

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#24151]
`TestBackupRestoreControl` uses a zone config hook to set the `RangeMaxBytes` to 5kb before the initial population of a table with 1000 rows via INSERTs.  (it sets that size since it wants to cover logic in RESTORE that handles larger numbers of ranges without waiting for lots of actual data).

While populating the table during setup though, it sometimes fails with a cput error:
```
pq: waiting on split that failed: unexpected value: raw_bytes:"Fv\342\213\003\010\026\022\001\273\032\005\273\211\367\003\002\"\006\010\001\020\001\030\001\"\006\010\002\020\002\030\003(\004" timestamp:<wall_time:1521732451961422564 >

failed insert into bank
github.com/cockroachdb/cockroach/pkg/workload.Setup.func1 pkg/workload/workload.go:290
```

Seems to happen within a few seconds using stress: `make stress PKG=./pkg/ccl/backupccl TESTS=TestBackupRestoreControl/pause TESTTIMEOUT=60s`.

**Comment by nvanbenschoten** [comment]
I was able to reproduce this without 5029c38. I'm going to perform a full bisection.

**Comment by dt** [comment]
could probably write a _much_ smaller/faster test than the one I mentioned, just by calling `backupRestoreTestSetupWithParams` since the one I mentioned is kinda slow.

**Comment by dt** [comment]
huh, interesting... the relevant part of 36a0832 has to be the zone config hook, that means the initial table splits much more as it is populated.

**Comment by nvanbenschoten** [comment]
So we're setting the RangeMaxBytes all the way down to `5KB`? We'd certainly expect write backpressuring in that case.

**Comment by dt** [comment]
yeah, I set it very small so that the table has lots of ranges without having to have lots of actual data -- I need lots of ranges so that when we backup and restore it, we actually cover logic that e.g. chunks batches of ranges and/or is non-deterministic.

**Comment by bdarnell** [comment]
For a quick fix, we could weaken the backpressure by releasing any blocked writes after a failed split. But I think it would be better in the long run to make backpressured writes wait until a split completes successfully. This would require that the split queue retry immediately on a ConditionFailedError instead of putting the range in purgatory to ensure that the retry happens promptly.

**Comment by nvanbenschoten** [comment]
> This would require that the split queue retry immediately on a ConditionFailedError instead of putting the range in purgatory to ensure that the retry happens promptly.

It doesn't look like the splitQueue retries at all in this case. It doesn't have any special logic to detect the errors and it doesn't support a purgatory. I think it's just relying on the fact that if a split fails then the next write to that range will call `splitQueue.MaybeAdd` and kick off another split attempt. I'm having a hard time following the progression of https://github.com/cockroachdb/cockroach/pull/10728 to determine why that is the case. Perhaps @vivekmenezes could weigh in on that.

> For a quick fix, we could weaken the backpressure by releasing any blocked writes after a failed split. 

Do note though that even with this quick fix, the test is still very flaky like I mentioned above. It regularly times out and I also see lots of error like:

```
backup_test.go:963: error executing 'RESUME JOB 333150328835440641': pq: job with status succeeded cannot be resumed
```
