### ISSUE TITLE
ui: cluster overview gets too crowded on narrow screens

### ISSUE THREAD

**Issue by couchand** [cockroachdb/cockroach#24158]
When there's not enough width to fit all the cluster overview metrics on a single line, we should do something to handle the situation.  Currently, it just gets too compressed:

<img width="872" alt="screen shot 2018-03-22 at 3 59 32 pm" src="https://user-images.githubusercontent.com/793969/37795167-09e0715c-2dea-11e8-929e-4b30ed196268.png">

Perhaps the components could stack or something like that.  Will need to do some design exploration.

**Comment by couchand** [comment]
Actually it doesn't look great when the screen is very wide, too:

<img width="1742" alt="screen shot 2018-03-22 at 4 02 01 pm" src="https://user-images.githubusercontent.com/793969/37795272-68fdcc0c-2dea-11e8-977d-813795e8643a.png">

compared to the much nicer-looking mockup:

<img width="1344" alt="cluster-overview-improvements" src="https://user-images.githubusercontent.com/29442020/36985051-4229b3d6-2064-11e8-9d6d-8b41c42f3f0d.png">

**Comment by piyush-singh** [comment]
+ @josueeee #23669 and this issue both highlight sizing issues with the cluster overview and will probably need design help.
