### ISSUE TITLE
ui: discrepancies in reported disk usage

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#24182]
Someone on gitter reported the "current usage" number from the first page on the UI to be different from the sum of "sizes" on the databases page (including the time series); the former is larger with a single-node cluster. I can see that too in a local cluster I had for a while. And I can even get a discrepancy quickly by starting with a fresh store dir. In his case, the discrepancy is even larger than 64MB, so it's not a range rounding thing.
What's going on?

The "current usage" number seems to be close to, but slightly lower, than what `du` reports on my data dir. On the new cluster, all database "sizes" , including time series, are 0 about 10 min after starting the cluster.

@mrtracy are you a good person for this?

**Comment by vilterp** [comment]
See #18667.

Unlikely that we'll ever get these to converge completely, since the numbers on the db page come from RocksDB `GetApproximateSizes`, and the numbers on the overview page come from the file system.

**Comment by couchand** [comment]
Another wrinkle is that there's yet more data in the store not included on the databases page: the meta ranges come to mind, and I think there's others but can't recall offhand what.

As a side note, the zero values you were seeing for database sizes are likely a result of #22944.

**Comment by couchand** [comment]
@andreimatei, it sounds like this user is on a recent version, based on the description, but can you find out which one? Also, do you have the actual values that were reported? It would be really helpful to get the details from `/#/debug/redux`.

**Comment by andreimatei** [comment]
@0xbaadf00d reported this ^

**Comment by couchand** [comment]
Potentially a duplicate of #24767
