### ISSUE TITLE
Self-service license expired message to user

### ISSUE THREAD

**Issue by kannanlakshmi** [cockroachdb/cockroach#24203]
When a trial user uses an enterprise feature after their trial license has expired, they get the following message which isn't very user friendly. 

Current message: 
```root@:26257/> RESTORE d.* FROM 'test';
pq: license expired at 2018-03-01 17:00:00 +0000 UTC```

Suggested new language: 
Use of FEATURENAME requires an enterprise license. Your enterprise trial license expired on DATE. If you're interested in getting a new license, please contact subscriptions@cockroachlabs.com and we can help you out.

**Comment by solongordon** [comment]
@kannanlakshmi Do you have a preferred format for the expiration date? "2018-03-26"?

**Comment by kannanlakshmi** [comment]
Preferably, March 26 2018.

**Comment by kannanlakshmi** [comment]
Does the statement execute in addition to giving a message about license expiring?

**Comment by solongordon** [comment]
No, the user receives the message as an error and nothing executes.

**Comment by kannanlakshmi** [comment]
FYI @sploiselle
