### ISSUE TITLE
roachtest: test that GC does not pull all gc'able keys into memory

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#24214]
Related to https://github.com/cockroachdb/cockroach/pull/24209.

Write a roachtest which creates a large
range (larger than available RAM) and fills it with GC'able data. (A
variant of the `drop.go` test that increases the range size before dropping suitably should do
it).

**Comment by tschottdorf** [comment]
@garvitjuniwal this is up for grabs if one of you would like to take a shot. I'm happy to provide more guidance.
