### ISSUE TITLE
storage: backpressure on busy-looping client transaction

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#24215]
A user reported a cluster outage due to an errant client which was updating the same row in a hot loop. This led to an out-of-disk situation and after restart tickled #24214.

The user is wondering whether we can limit the number of old versions per row or the number of updates per row somehow. This is not possible with the current MVCC layout (some metadata would have to be added and kept current for keys which may be monitored), and fine tuning the constants would be a difficult task to get right.

Still we should take a look at how these problems are solved in other products.

There may be some connection to https://github.com/cockroachdb/cockroach/issues/17229.

**Comment by bdarnell** [comment]
Why wasn't the backpressure introduced in #21777 catching this? That change was supposed to stop ranges from growing beyond the configured max range size.

**Comment by nvanbenschoten** [comment]
> That change was supposed to stop ranges from growing beyond the configured max range size.

The current version of backpressure won't help if a split is impossible because the range consists of only a single row. The queue will continue to [double the size of the range](https://github.com/cockroachdb/cockroach/blob/master/pkg/storage/split_queue.go#L130) without ever succeeding.

**Comment by bdarnell** [comment]
Ah. We should fix that, then. Writes to the range should be blocked until GC succeeds (maybe we allow some overage here but it must stop somewhere). We also need to message this clearly in the logs and UI since this could cause ranges to get stuck for a long time.

**Comment by nvanbenschoten** [comment]
> Writes to the range should be blocked until GC succeeds

Yeah, I think we'll want to limit how many times a range can double in size when it doesn't find a valid split key. Once we hit this limit, splits should start failing and the only recourse for a backpressured write will be to wait on GC to clear up room.

> We also need to message this clearly in the logs and UI since this could cause ranges to get stuck for a long time.

Agreed.

**Comment by tschottdorf** [comment]
Fixing that seems good. To be clear, the original issue is about backpressuring for that specific row. Blocking the range instead is a lot better than running out of space, so perhaps that's good enough.

**Comment by nvanbenschoten** [comment]
I was making the assumption above that there were so many versions of the single row that it would eventually become isolated in its own range, at which point the backpressure should kick in.

If the row is not hot enough to have this effect then it shouldn't result in range sizes getting too large. However, it still will have negative effects on scan performance, so we'll want to explore other means of backpressure to avoid this, which I think is what you were discussing yesterday.
