### ISSUE TITLE
*: how to perform comparative benchmarking?

### ISSUE THREAD

**Issue by matjazmav** [cockroachdb/cockroach#24217]
**QUESTION**

I would like to benchmark regular postgres and cockroachdb and compare results. I searched around and found few possible approaches. I'm trying this approaches and will comment on each one.

I know that you are benchmarking possible on every build, to monitor overall performance. But I couldn't found any documentation on benchmarking and comparing with other databases. Can you give me some directions?

I'm currently looking for simplest way (preferred out of the box tool) to benchmark cockroachdb and postgres.

#### 1. loadgen (kv, ycsb, tpcc)
This one looks most promising, but in early stage. I have opened task [cockroachdb/loadgen/#176](https://github.com/cockroachdb/loadgen/issues/176). Possible problem with outdated docker image.
#### 2. pgbench
Schema and data should be created separately because ´-i´ flag won't work.
#### 3. ycsb
In progress...
#### 4. other
Haven't tried those
- JMeter
- custom scripts

I'll update this post when I found more information about this topic.

Any directions will be much appreciated, thanks :)

**Comment by jordanlewis** [comment]
I responded on the linked `loadgen` issue as well, but the tl;dr is that you should check out our `workload` tool. Run `make bin/workload` to build it.
