### ISSUE TITLE
2.0 node fails to join a 1.1 cluster

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#24229]
Here's a funky one: starting a 2.0 node and asking it to join a 1.1 cluster doesn't seem to work. But upgrading an old 1.1 node to 2.0 does work (i.e. starting the 2.0 node with an existing store).

```
~/cockroach-v1.1.5  start --insecure --store=path=/Users/andrei/tmp/cockroach-data-3 --logtostderr -p 20305 --http-port=8082
...
~/cockroach-v2.0-beta.20180326  start --insecure --store=path=/Users/andrei/tmp/cockroach-data-4 --logtostderr -p 20310 --http-port=8083 --join=127.0.0.1:20305
```

The 2.0 node keeps printing:
```
I180326 20:53:08.231324 52 kv/dist_sender.go:368  [n?] unable to determine this node's attributes for replica selection; node is most likely bootstrapping
```
The 2.0 node fails to serve its admin UI and shows up as "yellow" in the UI served by the 1.1 node.

The 2.0 node had also said:
```
I180326 20:53:05.631241 41 server/server.go:1084  [n?] no stores bootstrapped and --join flag specified, awaiting init command.
...
I180326 20:58:25.608802 52 server/node.go:670  [n?] node connected via gossip and verified as part of cluster "236632b5-0e9a-40a8-af40-05032bd6e117"
```

@bdarnell do you have any time for this?

**Comment by bdarnell** [comment]
The real failure is in a `V(2)` log:

    E180326 21:31:50.814889 65 kv/dist_sender.go:1330  [range-lookup=/System/"node-idgen",range-lookup=/Meta2/System/"node-idgen\x00",n?] RPC error: initial connection heartbeat failed: version compatibility check failed on ping response: cluster requires at least version 1.1, but peer did not provide a version

The new version checks aren't supposed to apply until the cluster version has been set. I'm looking into how this is getting initialized. 

cc @solongordon

**Comment by bdarnell** [comment]
The initialization is here:

https://github.com/cockroachdb/cockroach/blob/f5c27b042c21340f2e420bdf960b91131db0f71d/pkg/storage/stores.go#L395-L409

@tschottdorf  `minUseVersion` looks backwards to me. Shouldn't it be `maxUseVersion` and ratchet forward to the newest use version in any store?

Whether it's min or max, if there are *no* initialized engines, it needs to be set to `minSupportedVersion`. So we either flip it around to be `maxUseVersion` or use a special maxint sentinel value that gets reset to `minSupportedVersion` if there's no other value.
