### ISSUE TITLE
Can I pull down v2.0-beta.20180326 as a docker image to use pgweb?

### ISSUE THREAD

**Issue by MostHated** [cockroachdb/cockroach#24234]
Hey there, I tried to use the following, but it did not work. Is there a different way to try and use 2.0 via docker so I can use pgweb?

services:
  cockroachdb:
    image: cockroachdb/cockroach:v2.0-beta.20180326

Thanks!

(Or if there is another docker image I can use instead of pgweb, I just want to quickly be able to see the data is all)

**Comment by MostHated** [comment]
Got it figured out, sorry!

**Comment by a-robinson** [comment]
For reference to anyone who ends up on this issue later, we publish alpha/beta releases to the `cockroachdb/cockroach-unstable` docker image: https://hub.docker.com/r/cockroachdb/cockroach-unstable/
