### ISSUE TITLE
roachtest: test a queue-type workload

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#24236]
See https://github.com/cockroachdb/cockroach/issues/17229. We should simulate this kind of workload over extended periods of time and ideally have fixtures that come with the degradation built in.

**Comment by tschottdorf** [comment]
So what I think we should start out with here is the following. The idea here is to have a fast-moving write front and put lots of data into a table while not having any contention (which would slow us down). And the point is to create a data set that has lots of RocksDB tombstones, which is achieved by running it for extended periods of time on a cluster with a low GC TTL (say 10min). We can use the created dataset to create a store dump (a backup would not contain the tombstones), and write targeted tests that make sure that we handle the tombstones in a way that doesn't create a huge disruption.

```sql
// Should also add a payload to the key, omitted here.
create table queue(ts int, client_id int, payload byte) // primary (ts, client_id)
```
for client i (i = 1..num_clients):
in iteration j (partitioned monotonically across all clients, i.e. no two clients will ever reuse a j, which is the "timestamp", but so that there's a well-defined write front)
```
INSERT INTO tbl VALUES (j, i, random_payload()), (j+1, i, random_payload()), ..., (j + 999, i, random_payload());
DELETE FROM tbl WHERE ts >= j && ts < j+1000;
j += 1000 // really need to do this before using any j's so that others don't use overlapping ones
```

**Comment by kaavee315** [comment]
@tschottdorf Isn't this similar to what disk space test does. We can just have a test case with low disk fill ratio there and a bit longer GC(can be made configurable as part of test case). Am I missing something?

**Comment by tschottdorf** [comment]
@kaavee315 you're right that this is similar. I would still prefer to make this workload and the corresponding fixture and then plug it into the disk usage test, as opposed to fitting it in right away.

The reason is that the tombstone mine field problem doesn't occur unless you've laid down lots of tombstones and this requires some concurrency in generating the load -- this is why I set up the workload in a way that allows lots of clients to act on the write front independently. At the same time, we're going to want to make this a store fixture -- that is basically a downloadable store dump -- so that the test gets a large prepopulated mine field. The resulting test which only tests one thing in isolation will be nicer to use to inform decisions on how to address this problem.

**Comment by tschottdorf** [comment]
@kaavee315 this is becoming more of a priority on our end, so we'll take this in-house -- unless you have this basically ready, in which case, please let me know! 😄

**Comment by kaavee315** [comment]
@tschottdorf, sorry, I got busy with timestamp oracle stuff. Feel free to take this in-house. It would be great if you could attach the PR here. It would be good to have a look :smile:
