### ISSUE TITLE
storage: rocksdb option compression_pre_level setting

### ISSUE THREAD

**Issue by cppmajor** [cockroachdb/cockroach#24243]
store='path=/xxx/xxx,rocksdb=level_compaction_dynamic_level_bytes=true;compression_per_level=kNoCompression:kNoCompression:kNoCompression:kSnappyCompression:kSnappyCompression:kZlibCompression'
* ERROR: cockroach server exited with error: failed to create engines: could not open rocksdb instance: Invalid argument: Compression type Zlib is not linked with the binary

So how can I get a release version with zlib,zstd, ...(other compress type)? or build one?

**Comment by benesch** [comment]
You'll have to build one, I'm afraid. Here's what we do for Snappy: https://github.com/cockroachdb/cockroach/blob/f7c7839a17bddead3b5562a3e30c3e565b23842b/Makefile#L600

It should be straightforward to change that invocation to pass the requisite ZLIB flags instead.
