### ISSUE TITLE
Implement current_timestamp, current_date, and now() correctly

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#2427]
current_timestamp, current_date, and now() return the time when they were processed. In postgres they return the same consistent time within a transaction scope, where the recorded time is a timestamp taken  at the start of the transaction.

We could either implement postgres semantics or some other modernized semantics.

**Comment by vivekmenezes** [comment]
Assigning to @petermattis to specify modern version of the semantics.

**Comment by petermattis** [comment]
@vivekmenezes You're the one who filed this issue. I'm not sure what sort of modernized semantics you were thinking. I think these functions should return the start time of the transaction. If we want some time functions with different semantics we should add new functions.
