### ISSUE TITLE
roachtest: basic chaos test

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#24279]
https://github.com/cockroachdb/cockroach/issues/20651 asks for a chaos test involving splits. We also need a basic chaos test that cycles around the nodes in a cluster randomly killing and restarting them and verifying some level performance and speed of recovery. Since node recovery is tied to the amount of data on the node, we might want to load a fixture onto the cluster to make the scenario more realistic.

**Comment by tschottdorf** [comment]
Should also weave in a regression test for https://github.com/cockroachdb/cockroach/issues/24025 here. That is, kill nodes while an import is running.

**Comment by andreimatei** [comment]
Also a regression for https://github.com/cockroachdb/cockroach/issues/24149 (assuming we fix it) - run queries while killing nodes and check that no "unexpected" errors are seen.

**Comment by nvanbenschoten** [comment]
@tschottdorf one difficulty I'm having with running benchmarks against a cluster under chaos is that it requires some buy-in from client connections. This buy-in can come in a number of forms. For instance, we could require that all load generators employ a failure-tolerant connection strategy (e.g. round-robin, [RobustDB](https://github.com/scaledata/rksql/blob/4e5b84a7f76d6919d57c9526bae3b7d9948aadd1/src/go/src/rubrik/sqlapp/tx.go#L52), etc.). We could also just stick a load balancer in-front of clusters and point all client connections at that. Either way, it seems like we'll need to do something in `workload` to allow us to enable chaos is arbitrary roachtests.

I'm curious if you had given this any thought. Is there a standard approach you think we should be using to address this in roachtests?

**Comment by tschottdorf** [comment]
`roachtest` had a built-in load balancer that is currently trivial. I thought that would turn into something like RobustDB, but setting up a haproxy should work well too and has the added benefit of dogfooding something we want our users to do.
