### ISSUE TITLE
roachtest: test big machines (cpu and disk)

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#24277]
Current tests primarily use 4 cpu machines with a single local SSD. After the performance tracking infrastructure gets built out more, we should add tests which use larger machines (more CPUs, multiple disks per node) so that we can see how performance varies based on machine size.

**Comment by knz** [comment]
cc @nvanbenschoten for re-triage

**Comment by petermattis** [comment]
We've actually made a lot of progress here recently due to the spanlatch and raft entry cache work. Adding a few kv roachtest configurations for larger (cpu) machines would be an easy way to make sure we don't regress. Sending this to @ajwerner while Nathan is on vacation.

**Comment by ajwerner** [comment]
Sounds good. I'll add some more on bigger machines and run a backfill. 32 cores sound right?

**Comment by ajwerner** [comment]
We did this ages ago.
