### ISSUE TITLE
kv: values in the uncertainty window should bump the txn timestamp rather than return an error

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#24283]
When a scan encounters an uncertain value, it returns an `ReadWithinUncertaintyIntervalError`. If the scan is done through a "root" txn, then the TCS will see the error and attempt to refresh the previous read spans. If that's successful, the scan's batch is sent again at a bump timestamp.
As a customer's issue has made it painfully obvious that uncertainty errors are real, I'm wondering if we could be smarter about them: instead of the scan bailing out as soon as it finds an uncertain value, could it optimistically assume that the refresh will succeed (particularly seeing how many times there will not be anything to refresh if this is the first read), and continue reading at a bumped timestamp? We know that the part of the scan that already ran is not affected by the timestamp bump - otherwise it would have run into an uncertain value earlier. The idea would be that, if the upcoming refresh is indeed successful, there'd no longer be a need to retry anything.

If the scan does this, we'd need to make sure that the timestamp cache is populated at the bumped timestamp. I'm not sure if there's a problem with concurrent writes to the scan's key span - I think there isn't because the command queue is blocking overlapping writes regardless of their timestamp?
I guess there'd be a problem if the scan's batch contains other requests before the scan - those requests would have run at a different timestamp. So maybe we only do this optimization if the scan is alone in the batch - as it is for SQL scans. And I'm not sure what needs to happen in case the scan was straddling ranges and the DistSender split it - maybe we'd need to disable this optimization, but it seems to me that we already don't do refreshes for such batches (the TCS deals with "mixed success" batches).

Does this sound like something doable? Am I missing something?

cc @spencerkimball @tschottdorf @bdarnell @nvanbenschoten

**Comment by spencerkimball** [comment]
Yes I think the suggested change is doable, but there are problems, some of which you've already noted:
- Complexity, especially around things like making sure the timestamp cache is updated appropriately
- We'd be returning inconsistent results for the transaction, even if code further up the stack would ensure that it is consistent or else not return it to the upstream client. This is not just academic. It's a matter of cognitive complexity. You'd be violating what is currently an invariant which is helpful in reasoning about things. This would introduce an exception.
- I thought for the most part we were treating reads as low cost – what's motivating the avoidance of retrying the scan? Presumably performance, but in a non-geo cluster this would be negligible. Could you be more explicit about the goal here?

**Comment by bdarnell** [comment]
> The idea would be that, if the upcoming refresh is indeed successful, there'd no longer be a need to retry anything.

What is "the upcoming refresh"? The call to RefreshSpans that comes just before the commit? I think that's too late, we'd already have returned inconsistent results to the client (which is the same kind of problem as the one that motivated the introduction of the AbortSpan). I think it would be safe if we had the TxnCoordSender refresh all existing prior spans before returning any results from a scan that had had its timestamp bumped in this way, but this adds additional complexity.

**Comment by andreimatei** [comment]
> What is "the upcoming refresh"? The call to RefreshSpans that comes just before the commit?

No; on uncertainty errors we refresh immediately after receiving that error, not wait until commit. I'd keep this behavior, but trigger it by another signal attached to an otherwise successful scan, not by an error.

**Comment by andreimatei** [comment]
Looks like this failed to capture the hearts and minds, and so I'll close this.
But I'll add an observation for posterity - for DistSQL, as well as for concurrent reads done through the TxnCoordSender, the stakes are higher than just retrying one scan - it's retrying the whole flow (or, rather, erroring out as we currently do for DistSQL) or again erroring out for the concurrent reads. If the scan were to succeeded, these would go away.
