### ISSUE TITLE
storage: improve EndTransaction's AbortSpan declaration

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#24285]
See https://github.com/cockroachdb/cockroach/pull/24194#issuecomment-376374014 via @bdarnell:

EndTransaction currently declares the abort span for read/write whether it's a commit or abort:

https://github.com/cockroachdb/cockroach/blob/f111ff400b2098ee39df0e3681b1f0e9f800f0d1/pkg/storage/replica_command.go#L165

Although I think you're right that it doesn't actually need to unless it's an abort and we're resolving local intents.

**Comment by nvanbenschoten** [comment]
@tschottdorf are you planning on addressing this for 2.1? Seems like a 1-line change unless I'm missing some added complication.

**Comment by tschottdorf** [comment]
Not currently in my queue. I'm not aware of any complications. OK if I just give this to you?
