### ISSUE TITLE
roachtest: test network chaos

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#24281]
[Toxiproxy](https://github.com/Shopify/toxiproxy) enables simulating network chaos such as slow links and dropped packets. We should add infrastructure to allow tests to easily set up toxiproxy and add some basic tests of network chaos. Another test would be to replicate [Perseus](https://github.com/rystsov/perseus/blob/master/cockroachdb/README.md), which measures the time-to-recovery of CockroachDB (and has found discrepancies with our expectations).

**Comment by tschottdorf** [comment]
some relevant WIP in https://github.com/cockroachdb/cockroach/pull/23141.

**Comment by bdarnell** [comment]
There's also a standard (?) linux CLI tool `tc` that can do network fault injection. [Jepsen uses it](https://github.com/jepsen-io/jepsen/blob/master/jepsen/src/jepsen/net.clj).
