### ISSUE TITLE
roachtest: improved mixed-version testing

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#24290]
The existing mixed-version roachtest uses only a modest number of features. We need more expansive mixed-version tests that exercise a larger number of features (both in Core in SQL) to verify compatibility between adjacent releases. 

Assigning to @tschottdorf for now, but the exercising of the SQL features might require assistance or insight from SQL folks. Cc @jordanlewis 

See https://github.com/cockroachdb/cockroach/issues/18955

**Comment by tschottdorf** [comment]
Closing for https://github.com/cockroachdb/cockroach/issues/15851.
