### ISSUE TITLE
sql: CTE name resolution incomplete/incorrect

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#24303]
Starting with:

```sql
CREATE TABLE a(x INT);
```

The following query fails:

```sql
> INSERT INTO a(x) 
        (WITH b(z) AS (VALUES (1),(2),(3)) SELECT z+1 AS w FROM b);
pq: relation "b" does not exist
```

Whereas the following (equivalent) query succeeds:

```sql
>  INSERT INTO a(x) 
       (SELECT w 
          FROM (WITH b(z) AS (VALUES (1),(2),(3)) SELECT z+1 AS w FROM b));
```

More worrying, another variant of the query above **where the CTE name `b` is renamed to `a`** does succeed, but with a different error:

```sql
> INSERT INTO a(x) 
      (WITH a(z) AS (VALUES (1),(2),(3)) SELECT z+1 AS w FROM a);
pq: column name "z" not found
```

After experimenting some more, it appears  that the `FROM x` checks that a **stored table** called `x` exists before it checks whether there's a CTE named `x` in the current scope, and if there is no table it errors out with "relation does not exist".

This suggest that name qualification occurs before CTE resolution, which would be incorrect.

**Comment by knz** [comment]
cc @jordanlewis

**Comment by knz** [comment]
This affects the opt code as well, for example the following query fails:

```
(with woo as (values (1)) (with waa as (values (2)) table woo));
```

The error is in `(b *Builder) buildSelect`, the loop over `ParenSelect` incorrectly ignores the WITH clauses.

**Comment by knz** [comment]
cc @rytaft @andy-kimball

**Comment by knz** [comment]
I have a fix ready, PR incoming

**Comment by knz** [comment]
Oops no the fix is not so simple, for example

```sql
with woo as (values (1)) 
  (with waa as (values (2)) 
      table woo) 
  limit (select * from waa))
```

Notice the LIMIT clause it outside of the parentheses so the name `waa` it refers to **cannot** pick up the alias set up by the inner `with waa`. Will iterate.

**Comment by knz** [comment]
I'm pulling my hair over this. The heuristic planner is a mess with regards to this area.

The CTE analysis must preserve the hierarchical scoping across parentheses, as explained in my comment above: https://github.com/cockroachdb/cockroach/issues/24303#issuecomment-427355122

I will add an "unimplemented error" in the meantime.

**Comment by rytaft** [comment]
cc @justinj who was working on this in the optimizer

**Comment by RaduBerinde** [comment]
These examples seem to work fine with the optimizer.

**Comment by andy-kimball** [comment]
Note that the last example Raphael showed also fails in PG:
```
template1=# with woo as (values (1))
template1-#   (with waa as (values (2))
template1(#       table woo)
template1-#   limit (select * from waa));
2020-01-18 08:38:43.417 PST [16240] ERROR:  multiple WITH clauses not allowed at character 1
2020-01-18 08:38:43.417 PST [16240] STATEMENT:  with woo as (values (1))
	  (with waa as (values (2))
	      table woo)
	  limit (select * from waa));
ERROR:  multiple WITH clauses not allowed
LINE 1: with woo as (values (1))
        ^
```
So the "fix" here is just to clean up our error message to match PG's. I'll put out a PR.
