### ISSUE TITLE
sql/parser: AST doesn't distinguish between constraints and indexes

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#2430]
In postgres, constraints specifically exclude INDEX, though adding a UNIQUE constraint creates an index. In cockroach, the two appear to be entirely conflated.

**Comment by petermattis** [comment]
While an INDEX isn't actually a constraint on a table, is there a problem with extending the syntax here as we've done? The alternative is to create entirely new syntax for allowing index creation instead of a `CREATE TABLE` statement.

**Comment by tamird** [comment]
Technically, there is no problem. Socially, there might be. Our syntax is so similar to postgres' that this deviation is very surprising, or at least it was to me.

We should be unafraid to deviate from postgres, but this particular deviation is an accident. It also feels like we crammed index creation into constraint creation because that was the nearest available place, and that feels sloppy.
