### ISSUE TITLE
ui: make capacity usage bar expand to fill available space

### ISSUE THREAD

**Issue by vilterp** [cockroachdb/cockroach#24314]
Would be nice if the bar graph stretched to always line up with the end of the "capacity usable" number.

![image](https://user-images.githubusercontent.com/7341/38062510-407aab88-32c2-11e8-9c12-d018fffc5c1e.png)

Can we achieve this by just using the `width: <n>%` inline attribute on the inner div, instead of doing this in d3?

cc @josueeee: can we use the "constraints" feature in Figma to specify/prototype stuff like this in designs?

**Comment by josueeee** [comment]
Yes, it should expand the full width of the column. And yes, we should design/prototype with constraints.

**Comment by couchand** [comment]
And conversely it should shrink if it doesn't have enough space, and also it should update when the screen size changes.  This was already on my list of things to do when cleaning up the overview in 2.1, thanks for filing an issue @vilterp it will help with visibilty/keeping track of it.

As it's currently implemented we'll need to update the d3 scale range based on the size.  I suppose this particular chart could be implemented with some clever CSS hacks, but I'd rather not go down that path.

**Comment by vilterp** [comment]
Using CSS percentage width to encode percentage full seems like less of a clever hack than piping the size back into JS through a window onresize hook :P

**Comment by vilterp** [comment]
Oh, I guess you need a scale for the axis labels on the bottom. In that case, idk, you're probably right.

**Comment by vilterp** [comment]
I think it's fine if we don't do this.

**Comment by couchand** [comment]
This is still something we need to address, though we should probably wait until we take a more comprehensive review of the overview component after this release cycle.

**Comment by josueeee** [comment]
@couchand Agreed, the current design is not scalable and should be rethought in the context of a "real" dashboard page.
