### ISSUE TITLE
server: better error message when same store dir is used twice

### ISSUE THREAD

**Issue by rjnn** [cockroachdb/cockroach#24315]
Currently, if you start two cockroach nodes on the same machine on the same store directory (but specifying different ports), you get the following error message:

`ERROR: could not cleanup temporary directories from record file: could not lock temporary directory /Users/amruta/go/src/github.com/cockroachdb/cockroach/cockroach-data/cockroach-temp244013569, may still be in use: IO error: While lock file: /Users/amruta/go/src/github.com/cockroachdb/cockroach/cockroach-data/cockroach-temp244013569/TEMP_DIR.LOCK: Resource temporarily unavailable`

We should attempt to detect this state and give a better error message. At the very least, we can prepend this error message with some sort of "are you sure you aren't running a different cockroach node on this store directory?"

**Comment by bdarnell** [comment]
If the `--port` flag has a non-default value that would be a pretty good heuristic for "maybe trying multiple nodes on one machine". 

It's kind of surprising that the temp rocksdb conflict is reached first (and the temp directory has had its own issues that can muddy the waters here). It might be better if we opened the main rocksdb instance before cleaning up the temp dir.

**Comment by petermattis** [comment]
I'm wondering what we want to do here. Catching this error and translating it to something a bit more understandable is one approach and would address the error that occurs when two cockroach servers try to use the same directory for the first store directory. There is another error that occurs in a slightly more complex scenario:

```
~ ./cockroach start --logtostderr --insecure --store=foo --store=bar
...
~ ./cockroach start --logtostderr --insecure --store=bar
...
E180802 18:09:07.359975 1 cli/error.go:119  cockroach server exited with error: consider changing the port via --port: listen tcp :26257: bind: address already in use
Error: cockroach server exited with error: consider changing the port via --port: listen tcp :26257: bind: address already in use
```

And then there is the error if you start the second server on a different port:

```
~ /cockroach start --logtostderr --insecure --store=bar --port=27257 --http-port=27258
...
E180802 18:12:41.378083 1 cli/error.go:119  cockroach server exited with error: failed to create engines: could not open rocksdb instance: IO error: While lock file: /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/bar/LOCK: Resource temporarily unavailable
Error: cockroach server exited with error: failed to create engines: could not open rocksdb instance: IO error: While lock file: /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/pkg/bar/LOCK: Resource temporarily unavailable
```

I think ideally we should bind the port earlier and provide the current error message when there is a port conflict. And we should unify and simplify the error message when two cockroach processes try to use the same store directory (we have to handle the cases where there is a temp directory conflict and when there is not).

Binding the port earlier might not be feasible for 2.1, though.

**Comment by petermattis** [comment]
Punting to early in the 2.2 cycle because I'm anxious about rearranging the startup process this late in the cycle for a better error message.

**Comment by knz** [comment]
Since this has been originally filed, we have extended our documentation to explain this situation.
