### ISSUE TITLE
opt: remove optgen binary from git

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#24327]
@couchand reports: I just noticed that `make clean` at the project root removes `pkg/sql/opt/optgen/cmd/optgen/optgen`, so git reports unstaged changes on a checkout/clean cycle.  Also `make` doesn't recreate it.  Could we either remove the binary from git or move deleting it to the `make maintainer-clean` target?

CC @benesch who is working on some related improvements to the build mechanism.

**Comment by RaduBerinde** [comment]
Ah, it looks like we generate `optgen` into `bin/` as needed. The binary was added in #24273, I'm guessing my accident.

**Comment by couchand** [comment]
Thanks! 👍 🚿
