### ISSUE TITLE
storage: range merge issues

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#2433]
Support for ranges is currently incomplete; this issue tracks the work that must be done to make them safe and usable.
- [x] Merge queue: identify undersized ranges as candidates for merging.
- [x] If necessary, replicate ranges to be merged on to the same set of stores. Ensure that the merge gets aborted cleanly if the rebalance/repair process needs to move one of the replicas before the merge completes.
- [x] Mark the subsumed range as frozen with a special raft command. Ensure that _all_ replicas have processed the freeze command before proceeding with the merge. 
- [x] Once a merge transaction has committed, that transaction must not be replayed onto future replicas (i.e. replicas that were not present when the merging process verified that all replicas had processed the freeze command in the subsumed range) via raft log appends. Snapshots _must_ be used instead.
- [x] Ensure that merges respect zone/prefix boundaries.
- [x] Make checks for collocated replicas transactional (#2431).
- [x] Delete all range-local data stored under `RangeIDKey` (#2426). (#2604)
- [x] `Store.canApplySnapshot` needs to consider the possibility that the snapshot's key span is wider than our present copy's
- [x] Set the `destroyed` attribute on the `Replica`

**Comment by BramGruneir** [comment]
Should we create issues for all of these and track them again our overall roadmap?
Could you classify them as beta, 1.0 or later?

**Comment by bdarnell** [comment]
This is all post-1.0, so I think it's premature to create individual issues.

**Comment by bdarnell** [comment]
Some notes from the investigation of #3306 and development of #3338:

For a time during the merge process, things are in an inconsistent state: the on-disk raft metadata has been deleted (in `mergeTrigger` and the subsequent commit of the batch), but the `Replica` still exists in memory with its cache of certain fields (specifically, the `FirstIndex` and `AppliedIndex` are cached, but the `HardState.Commit` field is not and will be read from disk when needed. When a raft group is created `etcd/raft` verifies that the various log indexes are consistent with each other). 

In `Store.MergeRange`, the raft group is removed before the `Replica` is, and this is not done under a lock (due to the subtleties of avoiding deadlocks between the store and multiraft goroutines). If a message arrives for this group before the `Replica` can be removed (this could be a message from another node or an internally-generated message like the one used to trigger a campaign after a split. The latter was responsible for #3306), multiraft will try to recreate the group, find the in-memory `Replica` object, and mix its cached state with the default values used when `HardState` is not found on disk. 

`mergeTrigger` needs to poison the `Replica` so it cannot be used again (this needs some care since raft is panicky when the storage is failing). We should also consider refactoring the locking/goroutine relationship between `Store` and `multiraft` (especially since the move to `RawNode`) to see if we can make the creation and destruction of raft group and `Replica` atomic.

**Comment by petermattis** [comment]
From #17565, range merging will destroy an invariant that the bounds of range descriptors in a meta range are entirely contained by the bounds of the meta range. Breaking this invariant will cause RangeLookups to be directed to the wrong meta range. We can fix this when range merging is implemented either by taking care to maintain the invariant (i.e. adjusting the bounds of the meta ranges if we're merging 2 ranges that lie on different meta ranges), refusing to merge ranges that lie on different meta ranges, or adding additional logic to DistSender to route RangeLookup requests to the next meta range.

**Comment by benesch** [comment]
My personal todo list:

TODO(benesch): Write tests for at least the following:

-  [ ] Reads/writes should be held until the merge completes.
-  [ ] Reads/writes should be served by the old replica if a merge is aborted.
-  [ ] Transactions on the RHS should work just fine.
-  [ ] Aborted transactions have their abort span record copied to the LHS.
-  [ ] Rebooting the RHS during a merge is OK.
-  [ ] Rebooting the LHS during a merge is OK.
-  [ ] Transferring the lease on the RHS is OK. (Maybe we want to allow any
      Raft-state only commands to proceed to keep the RHS healthy while the
      merge is in progress? At the very least we'll need to allow Subsumed
      requests to skip the mergeCompleteCh.)
-  [ ] Transferring the lease on the LHS is OK.
-  [ ] One RHS replica is down during the merge.
-  [ ] One LHS replica is down during the merge.

Code that might prove useful for the first suggested test above:
```
ch := make(chan struct{}, 1)
sc.TestingKnobs.TestingResponseFilter = func(ba roachpb.BatchRequest, _ *roachpb.BatchResponse) *roachpb.Error {
	for _, req := range ba.Requests {
		if req.Subsume != nil {
			// Send a request to r2.
			go func() {
				gArgs := getArgs([]byte("during-merge"))
				res, err := client.SendWrappedWith(ctx, store2.TestSender(), roachpb.Header{
					RangeID: bDesc.RangeID,
				}, gArgs)
				log.Warningf(ctx, "res=%s", res)
				if !testutils.IsPError(
					err, `r2 was not found`,
				) {
					t.Errorf("expected get on rhs to fail after merge txn started, but got err=%v", err)
				}
			}()
			// Wait for it to reach r2 before allowing the merge to continue.
			<-ch
			break
		}
	}
	return nil
}
sc.TestingKnobs.TestingRequestFilter = func(ba roachpb.BatchRequest) *roachpb.Error {
	for _, req := range ba.Requests {
		if req.Get != nil && req.Get.Key.Equal(roachpb.Key("during-merge")) {
			ch <- struct{}{}
		}
	}
	return nil
}
```

**Comment by benesch** [comment]
All of the TODO items laid out in the issue description have been completed! 🎉 

I've omitted some of the tests that I laid out above that turned out to be less interesting/necessary. I'm pretty confident in the unit test coverage I have added, though, so considering this issue closed!
