### ISSUE TITLE
storage: add SQL-tuned ScanResponse format

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#24342]
Extracted from and related to https://github.com/cockroachdb/cockroach/issues/20080: when projections and filters are added to Scan operations, it will be useful to provide a different format for Scan responses. Currently a `ScanResponse` is a series of key/value pairs. SQL wants rows and columns and likely wants these rows and columns returned in a "columnarized" format.

**Comment by nvanbenschoten** [comment]
Moving to "later" until it's confirmed that this will be addressed in the 2.2 cycle.
