### ISSUE TITLE
roachtest: add a hotspot workload

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#24341]
#21357 added a mechanism to backpressure writes if splits are not able to keep up. As part of our push for improved testing infrastructure, we should perform testing that attempts to create large ranges by writing lots of data to a hotspot. We should verify that splits are able to keep up with the directed load. This also includes bursty workloads.

**Comment by nvanbenschoten** [comment]
This should be pretty straightforward using `kv`. The approach I had take to [experiment](https://github.com/cockroachdb/cockroach/pull/21562#issuecomment-359090789) with this before was to point the following at a fresh Cockroach cluster:

```
kv --read-percent=0 --splits=0 --concurrency=20 --min-block-bytes=512000 --max-block-bytes=512001 
```

We'll then want to assert that while this load generator is running, no ranges get above a certain size threshold. 3 times the max_range_size is probably a reasonable target for this.
