### ISSUE TITLE
windows: error when running on WSL

### ISSUE THREAD

**Issue by billyharvey** [cockroachdb/cockroach#24344]
* ERROR: [n1,s1] Reported as error e282536f6d1545a1a4d65916073217c2
*
F180329 18:18:55.083007 22 storage/store.go:3848  [n1,s1] while committing batch: while committing batch: IO error: While sync_file_range offset 0 bytes 524288: /home/weh/.cockroachdb-data/000016.log: Function not implemented
goroutine 22 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0xc420534500, 0xc420534540, 0x3140000, 0x10)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:930 +0xcf
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x39c0fc0, 0xc400000004, 0x31400c4, 0x10, 0xf08, 0xc424e742c0, 0xaf)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:811 +0x6bf
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x260d8c0, 0xc420864000, 0x4, 0x2, 0x231a903, 0x6, 0xc4275bde60, 0x2, 0x2)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:154 +0x2e5
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x260d8c0, 0xc420864000, 0x1, 0x4, 0x231a903, 0x6, 0xc4275bde60, 0x2, 0x2)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:55 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(0x260d8c0, 0xc420864000, 0x231a903, 0x6, 0xc4275bde60, 0x2, 0x2)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:149 +0x7e
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processReady(0xc4204b7000, 0x260d8c0, 0xc420864000, 0x5)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3848 +0x53a
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4209ac000, 0x260d8c0, 0xc420864000)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:215 +0x259
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x260d8c0, 0xc420864000)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4202f5620, 0xc4201cb290, 0xc4202f5610)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:192 +0xe9
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:185 +0xad

**BUG REPORT**

1. $ grep -F '[config]' cockroach.log
I180329 18:17:03.838746 1 util/log/clog.go:1099  [config] file created at: 2018/03/29 18:17:03
I180329 18:17:03.838746 1 util/log/clog.go:1099  [config] running on machine: Rivendell
I180329 18:17:03.838746 1 util/log/clog.go:1099  [config] binary: CockroachDB CCL v2.0-beta.20180326 (x86_64-unknown-linux-gnu, built 2018/03/26 18:32:12, go1.10)
I180329 18:17:03.838746 1 util/log/clog.go:1099  [config] arguments: [cockroach start --insecure --host=localhost --log-dir=/home/weh/.cockroachdb-logs --store=attrs=ssd,path=/home/weh/.cockroachdb-d
ata]

2. Please describe the issue you observed:
- What did you do?

Launched standalone instance of Cockroach v2.0-beta.20180326 and left it running in the background on WSL Ubuntu.

$ uname -a
Linux Rivendell 4.4.0-17127-Microsoft #1-Microsoft Sun Mar 18 00:47:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux

- What did you expect to see?

Not a crash.

- What did you see instead?

Crash with output above.

**Comment by kittuov** [comment]
Is there a work around for this issue?

**Comment by bdarnell** [comment]
Either use the native windows binary or run the linux binary in a VM. WSL is not supported and we have no plans to work on this in the near future. (patches are welcome, although I think this particular issue will probably require changes to RocksDB)

**Comment by knz** [comment]
cc @tim-o for triage and next actions

**Comment by tim-o** [comment]
Closing as WSL is not supported and there are no plans to add support.
