### ISSUE TITLE
GOPATH detection lacks sanity checks

### ISSUE THREAD

**Issue by mqudsi** [cockroachdb/cockroach#24358]
The [GOPATH detection code](https://github.com/cockroachdb/cockroach/blob/master/Makefile#L196) does not perform any type of sanity checking, in my case, it set `GOPATH` to `/` (and would have proceeded to trash my root volume if I were running make under `sudo`).

Background: I saw the makefile and presumed I could just clone the repository to a subfolder of my home directory (since it is not a pure go project with native dependencies (and modules?)). I was wrong :)

Underlying problem: Makefile expects it's been downloaded via `go get github.com/cockroachdb/cockroach` (i.e. downloaded to a particular location within `GOPATH`), while simultaneously it is not possible to build via `go install github.com/cockroachdb/cockroach`. Cockroach should either rely exclusively on `go get`/`go install` or not at all (i.e. never manually use `GOPATH`).

In addition, `GOPATH` was already set and exported. Suggestion: instead of "calculating" `GOPATH` and using that new value, calculate `GOPATH` as you do currently, but then error out if that doesn't match the reported value of `GOPATH` because the underlying assumptions do not match and it's unsafe to continue at that point.

**Comment by benesch** [comment]
Thanks for the report. Sounds like you’d be interested in https://github.com/cockroachdb/cockroach/pull/23245.

The only reason that’s held up is because I’m worried about breaking the workflow of someone who uses multiple gopaths.

**Comment by benesch** [comment]
Thanks for providing the incentive to get #23245 merged, @mqudsi! Don't hesitate to file another issue if you're still running into trouble.

**Comment by mqudsi** [comment]
Yup, it looks like that does do the trick.

Thanks!
