### ISSUE TITLE
Can't create table with computed columns

### ISSUE THREAD

**Issue by Luonic** [cockroachdb/cockroach#24360]
Hello!
I can't say is that a bug or question but I have following problem:
I need to use computed columns so i updated to build v2.0-beta.20180326 (Ubuntu 16.04). But  when i perform this query:
```
CREATE TABLE my_db.my_table (
  id INT64 PRIMARY KEY,
  username STRING,
  fullname STRING,
  timestamp TIMESTAMP,
  date DATE AS (CAST(timestamp AS DATE)) STORED,
  url STRING,
  text STRING,
  language STRING);
```
I get:
`[XX000] ERROR: cluster version does not support computed columns (>= 2.0 required)`

What am I doing wrong?
Thank you in advance

**Comment by justinj** [comment]
Hi @Luonic,

Cockroach requires you to "finalize" your upgrade to the latest major version before certain features are enabled. Check out [our docs on upgrading](https://www.cockroachlabs.com/docs/dev/upgrade-cockroach-version.html#step-5-finalize-or-revert-the-upgrade) for more details. Computed columns are one of the features gated in this way - even though the binary you're running supports them, the cluster still believes it's running at 1.1 and must be told to upgrade explicitly before it will allow them.

Let me know if you run into any further problems!

**Comment by Luonic** [comment]
@justinj thank you! Your answer was super helpful)
