### ISSUE TITLE
cli/flags: Regression for fractions with units

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#24379]
The `--cache` and `--max-sql-memory` flags support several formats, including fractions, percentages, and suffixes like `GB`. #22460 broke one format that was previously working, non-integer values with a unit suffix like `1.5GiB`, because it assumes that if a dot is present, it's a fraction without units.

**Comment by petermattis** [comment]
@jseldess While we have a fix, it isn't going to be present until 2.0.1 and this bug should be documented as a known limitation.

**Comment by jseldess** [comment]
Documented as a known limitation in https://github.com/cockroachdb/docs/pull/2823.
