### ISSUE TITLE
sql: table descriptors are sometimes missing

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#24374]
This is an umbrella issue for a problem that's been observed in a few settings. Basically, the sequence of operations looks like this:

  * Create a new table, either directly using CREATE TABLE or indirectly using RESTORE, IMPORT, etc.
  * Attempt to query from that table, and get a "relation does not exist" error for the table you just created.
  * Try again a little bit later and watch the same query succeed.

Here's an issue tracking this problem when the `CREATE TABLE` is issued on a different node than the following query: https://github.com/cockroachdb/cockroach/issues/19925

But! We've also observed this happening when the queries are issued from the same node:

  * #22256
  * #24348

Hopefully the fix for #19925, #21686, will also fix the same-node case, but I wanted a separate issue in case the same-node case requires a separate fix.

**Comment by jordanlewis** [comment]
All linked issues have been closed.
