### ISSUE TITLE
opt: make memo output more readable

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#24370]
The `memo` test output currently looks like this:
```
[9: "p:k:1"]
memo
 ├── 10: (true)
 ├── 9: (select 8 5) (scan a,constrained)
 │    └── "p:k:1" [cost=100.00]
 │         └── best: (scan a,constrained)
 ├── 8: (scan a) (scan a@u) (scan a@v)
 │    └── "" [cost=1000.00]
 │         └── best: (scan a)
 ├── 7: (projections 2)
 ├── 6: (select 1 5)
 ├── 5: (filters 4)
 ├── 4: (eq 2 3)
 ├── 3: (const 1)
 ├── 2: (variable a.k)
 └── 1: (scan a)
```

There are various things we can do to improve this:
 - sort the groups topologically, with the root group first
 - hide "orphan" groups (groups unreachable from the root); this should be controlled by a flag though (for debugging garbage accumulation)
 - don't label groups with plain integers; maybe G1, G2, or A, B, C.
 - improve the readability of the physical properties (`p:k:1`); maybe label them with `physical`.

CC @andy-kimball @petermattis

@justinj this could be a good project for you - it's useful and would familiarize you with the memo data structures. If you want to work on it, feel free to reassign.

**Comment by petermattis** [comment]
> sort the groups topologically, with the root group first

FYI, `opttoy/v3` had [topological sort](https://github.com/petermattis/opttoy/blob/master/v3/memo.go#L312) code which could probably be adapted.

> don't label groups with plain integers; maybe G1, G2, or A, B, C.

The plain integer labelling is what we've seen in some of the literature. I'm not sure if another labelling would be better.

**Comment by justinj** [comment]
@RaduBerinde yes sounds good, I'm happy to take this!

**Comment by RaduBerinde** [comment]
I don't think that adding a `G` to the number is a problematic departure from the literature :)
IMO it would help make clear what's referring to a group and what is not, e.g.:

```
 ├── 4: (eq 2 3)
 ├── 3: (const 1)
 ├── 2: (variable a.k)
 └── 1: (scan a)
```
vs
```
 ├── G4: (eq G2 G3)
 ├── G3: (const 1)
 ├── G2: (variable a.k)
 └── G1: (scan a)
```

**Comment by petermattis** [comment]
Yeah, adding a `G` prefix looks ok and it does differentiate group IDs from constant values. I take back my objection.
