### ISSUE TITLE
Log Spam from Queues in TestStatusLocalLogs

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#2437]
Why are the queues spamming at all?  There shouldn't be any.

**Comment by bdarnell** [comment]
https://github.com/cockroachdb/cockroach/blob/ef070566ef24b8cd2543627d3bed2b60ec8d4582/server/status_test.go#L262

The log line in question is a V(1), but could safely be downgraded to V(2) or lower.
