### ISSUE TITLE
Root user can't access database after upgrading to 2.0-release due to privilege problem.

### ISSUE THREAD

**Issue by erichocean** [cockroachdb/cockroach#24382]
c1:

    I180331 04:23:00.299232 1 util/log/clog.go:1104  [config] file created at: 2018/03/31 04:23:00
    I180331 04:23:00.299232 1 util/log/clog.go:1104  [config] running on machine: c1
    I180331 04:23:00.299232 1 util/log/clog.go:1104  [config] binary: CockroachDB CCL v2.0-beta.20180319-219-g1a47bd5 (x86_64-unknown-linux-gnu, built 2018/03/30 06:21:25, go1.10)
    I180331 04:23:00.299232 1 util/log/clog.go:1104  [config] arguments: [cockroach start --certs-dir=certs --host=45.77.71.156 --join=45.77.71.156:26257,45.63.59.53:26257,45.32.71.217:26257 --cache=40% --max-sql-memory=40% --store=/ssd1 --store=/ssd2]

c2:

    I180331 04:28:24.493131 1 util/log/clog.go:1104  [config] file created at: 2018/03/31 04:28:24
    I180331 04:28:24.493131 1 util/log/clog.go:1104  [config] running on machine: c2
    I180331 04:28:24.493131 1 util/log/clog.go:1104  [config] binary: CockroachDB CCL v2.0-beta.20180319-219-g1a47bd5 (x86_64-unknown-linux-gnu, built 2018/03/30 06:21:25, go1.10)
    I180331 04:28:24.493131 1 util/log/clog.go:1104  [config] arguments: [cockroach start --certs-dir=certs --host=45.63.59.53 --join=45.77.71.156:26257,45.63.59.53:26257,45.32.71.217:26257 --cache=40% --max-sql-memory=40% --store=/ssd1 --store=/ssd2]

c3:

    I180331 04:33:23.426293 1 util/log/clog.go:1104  [config] file created at: 2018/03/31 04:33:23
    I180331 04:33:23.426293 1 util/log/clog.go:1104  [config] running on machine: c3
    I180331 04:33:23.426293 1 util/log/clog.go:1104  [config] binary: CockroachDB CCL v2.0-beta.20180319-219-g1a47bd5 (x86_64-unknown-linux-gnu, built 2018/03/30 06:21:25, go1.10)
    I180331 04:33:23.426293 1 util/log/clog.go:1104  [config] arguments: [cockroach start --certs-dir=certs --host=45.32.71.217 --join=45.77.71.156:26257,45.63.59.53:26257,45.32.71.217:26257 --cache=40% --max-sql-memory=40% --store=/ssd1 --store=/ssd2]

c4:

    I180331 04:35:08.502600 1 util/log/clog.go:1104  [config] file created at: 2018/03/31 04:35:08
    I180331 04:35:08.502600 1 util/log/clog.go:1104  [config] running on machine: c4
    I180331 04:35:08.502600 1 util/log/clog.go:1104  [config] binary: CockroachDB CCL v2.0-beta.20180319-219-g1a47bd5 (x86_64-unknown-linux-gnu, built 2018/03/30 06:21:25, go1.10)
    I180331 04:35:08.502600 1 util/log/clog.go:1104  [config] arguments: [cockroach start --certs-dir=certs --host=104.207.152.68 --join=45.77.71.156:26257,45.63.59.53:26257,45.32.71.217:26257 --cache=40% --max-sql-memory=40% --store=/ssd1 --store=/ssd2]

c5:
    
    I180331 04:37:03.873719 1 util/log/clog.go:1104  [config] file created at: 2018/03/31 04:37:03
    I180331 04:37:03.873719 1 util/log/clog.go:1104  [config] running on machine: c5
    I180331 04:37:03.873719 1 util/log/clog.go:1104  [config] binary: CockroachDB CCL v2.0-beta.20180319-219-g1a47bd5 (x86_64-unknown-linux-gnu, built 2018/03/30 06:21:25, go1.10)
    I180331 04:37:03.873719 1 util/log/clog.go:1104  [config] arguments: [cockroach start --certs-dir=certs --host=207.246.111.98 --join=45.77.71.156:26257,45.63.59.53:26257,45.32.71.217:26257 --cache=40% --max-sql-memory=40% --store=/ssd1 --store=/ssd2]

# What did you do?
      
* Upgraded each CentOS 7 machine (above) from 1.1.5 to https://edge-binaries.cockroachdb.com/cockroach/cockroach.linux-gnu-amd64.release-2.0
* Upgraded my own machine (macOS) to https://edge-binaries.cockroachdb.com/cockroach/cockroach.darwin-amd64.release-2.0
* ran `cockroach sql` (this is a secure cluster) and did `SET CLUSTER SETTING version = crdb_internal.node_executable_version();`
* (continuning in cockroach sql), ran `select count(*) on skus;`

# What did you expect to see?
  
One row with the number 2000000 in the first column. 

# What did you see instead?
  
This:

    pq: user admin does not have privileges
    warning: error retrieving the database name: pq: user admin does not have privileges

**Comment by erichocean** [comment]
Also, I followed the upgrade instructions to the letter on https://www.cockroachlabs.com/docs/dev/upgrade-cockroach-version.html#linux

**Comment by justinj** [comment]
@mberhault check the discussion in gitter for some more info, we talked this through a bit - all the queries seemed to imply that admin did in fact have the appropriate permissions, and existed, despite this error message.

**Comment by mberhault** [comment]
Thanks for the report. This looks like a bad migration (2.x runs a bunch of migrations on startup, including adding privileges for `admin` on all tables and databases).

In addition to the migrations, some parts of the code fill in these privileges to catch objects created in a mixed-version setting, but that doesn't seem like the problem here. This filling in is what may make `SHOW GRANTS` return the correct privileges (`admin` and `root` both have `ALL` privileges on everything) while not actually being the case.

Would you happen to still have the logs of the first run using 2.x, this may show us issues while running migrations (that's normally a fatal condition)? As well as logs of the latest run that encounters the error, those may contain details on the specific object failing the check (you can grep for something like `received invalid table descriptor` or `user admin does not have privileges`).

**Comment by mberhault** [comment]
When performing a rolling upgrade from 1.1.5 to 2.0, I did get the same transient error when talking to one of the upgraded nodes before the first upgraded node was finished running migrations. However, this was very short lived, and I should technically have waited until migrations were done running, but I'm not sure we have a good system in place to show that information to the user.

Could you clarify is the error message you encounter is persistent, or short lived?

**Comment by erichocean** [comment]
It's still there today. I've got the logs for each machine, as well as a debug.zip from before the upgrade that I can provide (would prefer that to be confidential though).

**Comment by erichocean** [comment]
I'm not seeing any errors at all in the logs when I run an SQL statement that fails—no `received invalid table descriptor` or `user admin does not have privileges`. Honestly, the logs don't show I've even tried to run any SQL. Even something semi-successful, like `select * from system.users;` doesn't show anything.

**Comment by erichocean** [comment]
In trying to think through possible problems, I _did_ briefly run `CCL v2.1-alpha.00000000-1474-gc88faff` on one of the nodes. Although it claims to be `done ensuring all necessary migrations have run`, I noticed there was this commit https://github.com/cockroachdb/cockroach/commit/ad008adbee5a0acab17df83e26a6107468e0817a that monkeys around with role authorizations. Perhaps it thought it succeeded, but only did so partially? And now bringing up the machines makes a naive check to see if the migrations have run, and thus I'm in a stuck intermediate state?

**Comment by erichocean** [comment]
To clarify, I first ran `CCL v2.1-alpha.00000000-1474-gc88faff` on the first node, because I was getting an error (fixed by commit https://github.com/cockroachdb/cockroach/commit/8aa93520f0832cdeb2e7649707cf97dc97384a81) trying to run the "public" 2.0 beta, but I did not change the cluster version. I stopped that node, then went through the usual rolling upgrade process as described above.

**Comment by mberhault** [comment]
Thanks for the details, I'll try while upgrading to 2.1 first. The migrations that poke at privileges are run as soon as one node upgrades to 2.x, regardless of the cluster setting. Migrations are also supposed to retry forever (or crash the process if it's something that requires manual intervention).

The commit  ad008ad also shouldn't impact this.

If my reproduction doesn't work, would you mind running a latest 2.0 with an additional patch for additional logging (logging a stack trace at the point the validation fails)? I can provide you with the binary (or just the patch if you prefer).

**Comment by erichocean** [comment]
I'd be happy to run a custom bin.

**Comment by mberhault** [comment]
We found the problem, some descriptors (in this case a database descriptor) did not have the minimum required `admin` privileges. This can happen if any descriptors are written by old nodes during a rolling upgrade as the descriptor will be reverted after it's migrated.

I had some automatic filling in of descriptors in some code paths, but I clearly wasn't being paranoid enough. I'll put it in for the other cases, it doesn't cost much anyway.

This will definitely be a 2.0 cherry-pick.

In the meantime, I provided @erichocean with a binary that has a basic version of the upcoming patch and it unwedged his cluster. I'll ping here with a link to the latest 2.0 binary once the patch is in and built.

**Comment by kalman5** [comment]
I fixed this with:

grant all on database XXXXX to admin;

**Comment by erichocean** [comment]
@kalman5 I tried that but it didn't work for me.

**Comment by mberhault** [comment]
This is merged and cherry-picked into 2.0. It should make it into the next 2.0 pre-release but I can also paste the link to the edge binary once our build pipeline is done.

**Comment by mberhault** [comment]
Built binaries with the fix in are now available:
linux: https://edge-binaries.cockroachdb.com/cockroach/cockroach.linux-gnu-amd64.release-2.0
osx: https://edge-binaries.cockroachdb.com/cockroach/cockroach.darwin-amd64.release-2.0

`./cockroach version` for those should show 1421bd19e3f49a44f046d42e306be7a79f7084e2 as the build sha (at least until other patches roll in).

Thanks again for the bug report and the patience debugging this.
