### ISSUE TITLE
cli/config: Sanity-check memory flags

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#24396]
We have two flags `--cache` and `--max-sql-memory` to set the memory used by two specific components, and encourage them to be set to a percentage (e.g. 25%). Not all memory used by the process is covered by one of these two limits, so it's important that they sum to well below 100%. Our conservative recommendation is to use 25% each. We haven't exhaustively tested the limits here but anecdotally setting them to 40% each results in a lot of memory-related crashes. We should introduce warnings and/or errors when the sum of these flags is too high.

**Comment by knz** [comment]
This came up on Gitter recently.
