### ISSUE TITLE
cli/start+config: Log cluster ID with `[config]` tag

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#24395]
We ask users to include all log lines containing the string `[config]` when creating an issue. We should log the cluster ID with the same tag so it can be included in the issue and we can correlate those with our crash reports in sentry.

This is a leak of otherwise non-public information, but since the `[config]` lines include other more readily identifiable details like hostnames and IP addresses in the command line, and the cluster ID is a random UUID with no correlation with anything else, I don't think there is a problem with encouraging it here.

**Comment by knz** [comment]
I briefly checked this: the `[config]` lines are generated by the log package itself on every new log file created (e.g. during rotations). 

So asking a user to "include all log files containing the string" has really been "look at the beginning of the most current log file".

So if we want to log the cluster ID it probably needs to be repeated at the start of every new log file.

**Comment by knz** [comment]
Another thing you write:

> the [config] lines include other more readily identifiable details like hostnames and IP addresses in the command line

I don't believe that's true.

You're mistaking this for the output of `cockroach start`, but that is not logged with `[config]`.

**Comment by knz** [comment]
Oh it does print out the current host name though.
