### ISSUE TITLE
status_test is broken: unable to lookup descriptor for node 0

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#2440]
https://circle-artifacts.com/gh/cockroachdb/cockroach/7190/artifacts/0/tmp/circle-artifacts.dIHALFm/testrace.log

Look for `unable to lookup descriptor for node 0`

Currently affected:
- TestStatusLocalLogs
- TestNodeStatusResponse
- TestStoreStatusResponse

**Comment by tschottdorf** [comment]
@BramGruneir, is this still an issue?

**Comment by BramGruneir** [comment]
fixed a while ago, closing.
