### ISSUE TITLE
ui: the clock offset graph in dashboards: runtime should always show in milliseconds

### ISSUE THREAD

**Issue by erichocean** [cockroachdb/cockroach#24411]
# Feature Request

1. I believe this is a new ask.

2. Currently, graphs "auto-scale", so that when your clock offsets are almost non-existing, you'll get a graph in _microseconds_ that makes it look, at a glance, like your clock offsets aren't event close. It's only when you look over to the Y axis and read the tiny, grey text that you realize your clocks are practically identical, as they should be.

I propose the clock offset graph instead always show milliseconds, since that's the only possible value people could care about.

3. Nice to have.

**Comment by piyush-singh** [comment]
Somehow missed this older issue when filing #35467 - we have a PR open for this. Will continue to track on the other issue.
