### ISSUE TITLE
sql: index not utilized for GROUP BY

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#24415]
A user on Gitter reported a problem where a query was not using an index when it appears it should be. The (anonymized) query was:

```
SELECT id, sum(value) FROM data GROUP BY id;
```

This is run against a table with a large number of columns, even though the query itself only accesses `id` and `value`:

```
CREATE TABLE data (
  id UUID NULL,
  value INT NULL,
  col1 INT NULL,   
  col2 INT NULL,   
  col3 INT NULL,   
  col4 INT NULL,   
  col5 INT NULL,   
  col6 INT NULL,   
  col7 INT NULL,   
  col8 INT NULL,   
  col9 INT NULL,   
  col10 INT NULL,   
  INDEX foo (id ASC) STORING (value)
);
```

`EXPLAIN` shows that the query is scanning the primary index:

```
root@:26257/test> EXPLAIN SELECT id, sum(value) FROM data GROUP BY id;
+----------------+-------------+--------------+
|      Tree      |    Field    | Description  |
+----------------+-------------+--------------+
| group          |             |              |
|  │             | aggregate 0 | id           |
|  │             | aggregate 1 | sum(value)   |
|  │             | group by    | @1           |
|  └── render    |             |              |
|       └── scan |             |              |
|                | table       | data@primary |
|                | spans       | ALL          |
+----------------+-------------+--------------+
```

But the query can be satisfied completely from the `foo` index which we can see be forcing `foo` to be used:

```
root@:26257/test> EXPLAIN SELECT id, sum(value) FROM data@foo GROUP BY id;
+----------------+-------------+-------------+
|      Tree      |    Field    | Description |
+----------------+-------------+-------------+
| group          |             |             |
|  │             | aggregate 0 | id          |
|  │             | aggregate 1 | sum(value)  |
|  │             | group by    | @1          |
|  └── render    |             |             |
|       └── scan |             |             |
|                | table       | data@foo    |
|                | spans       | ALL         |
+----------------+-------------+-------------+
```

Note that the query won't be that much faster using `@foo` vs `@primary`, but it will be scanning less data.

@RaduBerinde Not sure if there is anything to fix here for a 2.0.x release. Perhaps there is something silly going on.

**Comment by RaduBerinde** [comment]
Something silly, indeed. We have a fast path to shortcircuit the entire index selection when we don't have a filter or required ordering: https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/opt_index_selection.go#L98

We could add a check that all columns are needed, but it becomes super-specific. It seems we should remove this fast path completely.

**Comment by petermattis** [comment]
I'd be a bit wary of removing that fast-path in 2.0. Since we'll have a whole new query planner in 2.1, let's make sure the new query planner selects the right index.

**Comment by andy-kimball** [comment]
The cost-based optimizer selects the right index, so closing this out. I've added a regression case in `opt/xform/testdata/external/customer`.

**Comment by bladefist** [comment]
On Version: v2.1.0-beta.20180917

I'm the gitter user that @petermattis mentioned.  This is fixed, however, if you use a window function in the select, it will still select the wrong index.

Change 'sum(value)' to  'rank() over(order by sum(value) desc)' and it will go back to not using an index.

**Comment by knz** [comment]
@andy-kimball what do you think? I acknowledge the opt code does not do window functions yet, however the user is impacted by this limitation. Should we re-open this issue or do we create a new one?

**Comment by knz** [comment]
ok here is the new issue:  #30586
