### ISSUE TITLE
sql,ui: disallow or warn about duplicate indexes

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#24417]
```
CREATE TABLE t (
  k INT PRIMARY KEY,
  v INT,		   
  INDEX v1 (v),
  INDEX v2 (v),
  INDEX v3 (v)
);
```

The above is clearly silly (the `v1`, `v2` and `v3` indexes are identical), yet it is fairly easy to end up in this situation when using the `ALTER TABLE` syntax on a complex table with several indexes. The duplicate indexes are purely a pessimization. Only one will be used for reads, but we'll incur a write cost for the additional indexes. Disallowing identical indexes might be problematic due to compatibility concerns. One possibility is that we could extend `IndexDescriptor` to allow an index to have more than one name and dropping an index only deletes it if the last reference (name) is dropped. Or, we could notice the duplicate indexes and warn about them in the UI. Or perhaps we just document this as something to be wary of.

**Comment by justinj** [comment]
Do we also care to warn about indexes which are prefixes of another index?

```
CREATE TABLE t (
  k INT PRIMARY KEY,
  a INT,
  b INT,	   
  INDEX v1 (a),
  INDEX v2 (a, b)
);
```

In this case `v1` is redundant unless we guarantee that duplicate values of `a` are then sorted by primary key. I'm not sure if we guarantee that or not (but I believe it's true at present, at least).

**Comment by bdarnell** [comment]
We don't yet support this, but I've thought that one solution to our MVCC tombstone problem would be per-index GC thresholds. This would make it potentially useful to have two indexes on the same columns but with different GC thresholds. The query planner would choose one depending on the timestamp of the query. (The idea is that the index with the lower threshold would be used for most queries, and the one with the higher threshold would be used for backups or analytics)

But that's still pretty esoteric so this situation is probably worth at least a warning.

**Comment by dt** [comment]
According to SQL people, these days we sometimes _want_ duplicate indexes for geo-distributed reasons, so I think we want to leave this as-is.
