### ISSUE TITLE
sql: investigate LinkBench benchmark

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#24421]
The [LinkBench benchmark](https://github.com/mdcallag/linkbench) from Facebook is intended to benchmark Facebook's graph store use case on a relational database. It works with PostgreSQL.

We should investigate running this benchmark against CockroachDB.

**Comment by arjunravinarayan** [comment]
I investigated the LinkBench benchmark. LinkBench was created by Facebook using production traces of their internal sharded MySQL deployment. It has a graph-based schema, and graph-traversal based query access patterns. The read/write query throughputs are also set based on their architecture of having heavy read caches in front of the database, which is valuable real world information.

In terms of features, quoting the LinkBench paper:

> The variety of queries in YCSB comprises point reads and writes and range scans, while our workload uses distinct node and edge operations and also edge count operations. The richer variety of operations can require additional database features such as secondary indices and multi-row atomic updates to implement efficiently.

Thus, it is definitely an interesting database usecase that is meaningfully different from TPC-C and TPC-H. However, the query set is small: there are 3 DML queries: INSERTs, UPDATEs, and DELETEs of nodes and edges, but only 3 read queries:

`SELECT ... FROM linktable WHERE id1 = <id1> AND id2 in (<id2s>) AND link_type = <link_type>;` (i.e. get all the out-edges from a specified src-node to a set of specified dest-nodes)

`SELECT COUNT FROM counttable WHERE id = <id1> AND link_type = <link_type>;` (i.e. get the out-edge count of a node from a separate stored count denormalization)

`SELECT ... FROM linktable WHERE id1 = <id1> AND link_type = <link_type> AND  time >= <minTime> AND  time <= <maxTimestamp> AND  visibility = VISIBILITY_DEFAULT ORDER BY time DESC LIMIT <offset>, <limit>;` (i.e. get a range of edges from a specified node ordered by descending time)

These are not particularly SQL-execution intensive queries, so they are not useful in our quest to build an 'OLTP+' benchmark that tests our SQL-execution performance (note for instance that the counts are issued against a dedicated denormalization table that is manually updated, whereas we want to test our performance when such denormalizations are *not* maintained).

I thus conclude that while interesting and valuable as a source of production traces for a modern sharded MySQL deployment, it is not a useful benchmark for us to spend the effort to implement and test. There are also no known standardized benchmarking results that we could compare our numbers against.
