### ISSUE TITLE
importccl: support column mappings, DEFAULT, computed columns

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#24426]
Summary of a discussion with @dt, cc @bobvawter. Opening this issue to document our discussion. Not sure if/when we will implement this. Depends on customer needs.

We would like IMPORT at some point to support DEFAULT expressions, computed columns (#24359), and the ability to ignore or reorder columns in CSV files (a thing we're calling column mapping). DEFAULT and computed columns are related to column mapping because both raise the question of what the CSV file should contain.

For example, take a table with a computed column: `(a int, b int as (a*2) stored)`. What would you expected the CSV file for that to be? It could be one of:

1. a single column specifying `a`: `1`
1. two columns, specifying `a` and then an empty string: `1,`
1. two columns specifying `a` and `b`, where the `b` column must match exactly what the computed column would have produced: `1,2`

DEFAULT columns have a similar question: what happens if you specify or don't specify it during IMPORT?

Our proposal is:

If no column mapping is specified:

- Go through each visible table column in order. If the `i`th table column does not have a user-specified `DEFAULT` and is not computed, it is an error if the CSV row contains less than `i` entries. This means that you may specify computed columns, but they must appear at the end (this is similar to how INSERT works if you don't specify the column list). DEFAULT can either be explicitly specified in the CSV or also appear at the end.

If a column mapping is specified:

- For all columns specified in the map, ensure they are not a computed column.
- For all visible columns not specified in the map, they must be either nullable or have a default.

Unanswered questions: do we need a way to allow the user to optionally specify the value of a default column or to use the `default` expression? That is, to do both `insert into t (1, default)` and `insert into t (1, 2)` in the same CSV file? Like maybe a `defaultif` option similar to the `nullif` option..

**Comment by rolandcrosby** [comment]
Solution for this is to use `IMPORT INTO` after creating a table with the column definitions you want.
