### ISSUE TITLE
sql: panic: unsupported result type: regtype, types.TOid, regtype

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#24423]
`SQL panic has occurred while executing "SELECT CAST(246 AS REGTYPE) FROM ident": unsupported result type: regtype, types.TOid, regtype`

https://teamcity.cockroachdb.com/viewLog.html?buildId=588885&buildTypeId=Cockroach_Nightlies_RandomSyntaxTests

Found with RSG. Assigning for triage.

**Comment by jordanlewis** [comment]
Thanks! This is happening because DistSQL can't deal with regtypes. Didn't we ban these types from getting planned via DistSQL recently? cc @solo

**Comment by jordanlewis** [comment]
Oops, sorry @Solo. I meant to tag @solongordon.

**Comment by solongordon** [comment]
We did, though we're only looking for `CastExpr`s where the target type is an OID. It looks like in this case the expression is just a `DOid` datum. Should be straightforward to ban those too.
