### ISSUE TITLE
backfill: use max cluster capacity during create/drop index

### ISSUE THREAD

**Issue by erichocean** [cockroachdb/cockroach#24439]
I have 120 units of "CPU time" available across a 15 node cluster, with zero SQL activity. I'm adding a large unique index, and it is currently using 7.5 units of CPU across the entire cluster, or 6.25% of the available cluster capacity. The job should, ideally, be able to use 100% when there's no other activity, and less when there is.

I've had a similar experience dropping an index in the past.

**Comment by vivekmenezes** [comment]
will address after #12424

**Comment by jordanlewis** [comment]
Hi @dt, I'm going to move this to your board.

**Comment by mwang1026** [comment]
Closing. Refer to https://github.com/cockroachdb/cockroach/pull/55468
