### ISSUE TITLE
sql: errors from `SHOW SYNTAX` are not counted correctly

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#24432]
Our unit tests use a db/sql connection to send statements and ensure that the error counts and tracking are updated as expected... however, manually recreating that test in a shell, no counts are updated. It looks like the `SHOW SYNTAX` wrapper used by the client is side-stepping the error handling and counting we would otherwise do in the executor.

**Comment by dt** [comment]
cc @awoods187 I verified using `psql` that unimplemented feature errors appear to be correctly tracked but when I tried using `cockroach sql` they disappeared. So we might see an app or ORM hitting one of our defined unimplemented errors, but I'd expect most unimplemented errors to be hit by users experimenting by hand, so probably in the (cockroach) shell.

**Comment by awoods187** [comment]
What is the update for this @knz ? Possible for 2.0.1?

**Comment by knz** [comment]
it's possible.
