### ISSUE TITLE
docker: provide multi-architecture release image

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#24441]
Docker recently gained support for a multi-architecture image type called [manifest lists](https://docs.docker.com/registry/spec/manifest-v2-2/) (also see [here](https://blog.docker.com/2017/11/multi-arch-all-the-things/) and [here](https://docs.docker.com/edge/engine/reference/commandline/manifest/)). This image type represents multiple platform-specific images, all referenced by a single name. It can be thought of as an architecture/os-independent redirect to architecture/os-specific images.

Now that Cockroach release binaries are available for multiple cpu architectures (`x86_64` and `arm64`), we may want to consider adding multi-architecture support to the `cockroachdb/cockroach` Docker image. The biggest challenge here is that each architecture/os-specific sub-image needs to be built on a host with the same architecture. This would dramatically complicate out CI pipeline for deploying these images to Dockerhub.

An alternative would be to create a separate image called `cockroachdb/cockroach-arm64v8`. This would allow us to simplify the CI pipeline, but doing so creates a host of usability issues that manifest lists were purpose-built to address.

For the time being, I don't think we should spend any time here. If there becomes a real demand for an `arm64` Docker image, we can re-evaluate.

Epic RE-227
Jira issue: CRDB-5766

**Comment by vielmetti** [comment]
@nvanbenschoten @benesch - What is the CI pipeline that you are currently building images on? My notes say that you are (or were) using TeamCity. I'd be interested in looking at your CI pipeline to better understand the complications involved.

The multi-architecture manifest lists are making their way slowly into Kubernetes deployments as well, the latest k8s 1.11 has alpha-quality support for them, and the direction is towards beta-quality support for 1.12 in half a year.

**Comment by odidev** [comment]
@nvanbenschoten 

I am also interested in the Linux/ARM64 docker image release for ‘cockroachdb/cockroach’.

To build the docker image on Linux/AMD64 platform, I have followed below steps in “go/src/github.com/cockroachdb/cockroach” path using master branch:
~~~
$ git clone https://github.com/cockroachdb/cockroach.git
$ cd cockroach && chmod -R 777 .
$ git submodule update --init
$ ./build/builder.sh mkrelease linux-gnu
$ cp ./cockroach-linux-2.6.32-gnu-amd64 build/deploy/cockroach
$ cp ./lib.docker_amd64/libgeos_c.so ./lib.docker_amd64/libgeos.so build/deploy/
$ cd build/deploy && docker build -t cockroachdb/cockroach .
~~~
The Linux/AMD64 docker image built successfully.

As the cockroachdb/builder image supports cross-compilation for the AArch64 platform, I followed below steps to build cockroach Linux/ARM64 docker image on the Linux/AMD64 machine:
~~~
$ git clone https://github.com/cockroachdb/cockroach.git
$ cd cockroach && chmod -R 777 .
$ git submodule update --init
$ ./build/builder.sh mkrelease arm64-linux-gnueabi
~~~ 
But the command fails to find the C and CXX compilers for aarch64. Below are some messages from the error logs:
~~~
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown

make: *** [Makefile:673: /go/native/aarch64-unknown-linux-gnueabi/proj/Makefile] Error 1
make: *** Waiting for unfinished jobs....
make: *** [Makefile:667: /go/native/aarch64-unknown-linux-gnueabi/libroach/Makefile] Error 1
make: *** [Makefile:655: /go/native/aarch64-unknown-linux-gnueabi/geos/Makefile] Error 1
make: *** [Makefile:637: /go/native/aarch64-unknown-linux-gnueabi/protobuf/Makefile] Error 1
~~~
I tried exporting CC and CXX in the mkrelease.sh, but that has not helped.

As can be seen from some comments in old tickets <https://github.com/cockroachdb/cockroach/issues/8179#issuecomment-697123668>, I can conclude that above commands should work for building the docker image for ARM64.

Can you please provide any pointers on the above issues?

Once it works for building the docker image locally, then I will check on how the image can be released using Teamcity CI.

**Comment by rail** [comment]
We started shipping multi-arch (amd64/arm64) docker images in 22.2.0-beta.5. \o/
