### ISSUE TITLE
sql: implement lpad, rpad string builtins.

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#24456]
I was trying to get grafana to run on cockroach as the backing db. Quite a few issues (some already filed), but an easy one is support for some missing [string builtins](https://www.postgresql.org/docs/current/static/functions-string.html), specifically:

* `lpad(string text, length int [, fill text])`: Fill up the `string` to length `length` by prepending the characters `fill` (a space by default). If the `string` is already longer than `length` then it is truncated (on the right).
* `rpad(string text, length int [, fill text])`: Fill up the `string` to length `length` by appending the characters `fill` (a space by default). If the `string` is already longer than `length` then it is truncated.

**Comment by bpot** [comment]
taking a look at implementing this
