### ISSUE TITLE
Sharding strategy

### ISSUE THREAD

**Issue by WhiteTrashLord** [cockroachdb/cockroach#24465]
Maybe you could add some more information to your documentation how CockroachDB is sharding data. I could not find any specific information. I also just had an idea that it might be good if the users can change the sharding strategy. For example I was thinking that if you can use only the foreign key (if there is any) for the sharding that this might make joins faster.

**Comment by jseldess** [comment]
Thanks, @WhiteTrashLord. I've moved this over to the docs repo. Please track the issue there: https://github.com/cockroachdb/docs/issues/2862.
