### ISSUE TITLE
roachtest: test loss of quorum

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#24473]
We should have a roachtest that intentionally loses a quorum and

- verifies debuggability:
    - can run `./cockroach debug zip` and get something meaningful back.
    - verifies debug page functionality (this will need headless browsing ➖ 🤕 and likely our frontenders have the best ideas about this -- cc @couchand, @vilterp)
    - verifies that connecting to sql prompt is possible
- verifies specific losses of quorum (for example, in a partitioned cluster, losing only the replicas for data for one partition should no disturb the other partition much).

cc @windchan7 for `debug zip`.

**Comment by vilterp** [comment]
Interesting — what specific debug page functionality would you want to verify? Problem ranges?

We've been discussing how best to add some headless tests which spin up clusters and test their admin UIs… Maybe putting it in roachtest makes sense!

**Comment by dianasaur323** [comment]
can we also test cockroach node status once we fix that?

**Comment by tschottdorf** [comment]
@vilterp for basic stuff you probably want fast-running unit tests, but if we can share some of the setup with the needs for `roachtest` that would be good (or perhaps `roachtest` is fast enough for unit tests; I know @danhhz wants to run a subset on every CI, which kind of seems like it could replace some of the acceptance framework in the long term).

In the context of this issue I'm mostly interested in "if the cluster is in a certain state of unhappiness, can the debug pages still surface the information we expect them to"? Whereas in lots of the frontend tests you probably just want to know "does this work at all".

https://github.com/chromedp/chromedp looks kind of useful for usage from Go tests. (I have not even looked elsewhere. Don't take this as a strong suggestion).

**Comment by tschottdorf** [comment]
@windchan7 now that #24469 is ready to merge, would you look into the corresponding item about `debug zip` above? Concretely, I was imagining the following roachtest:

- starts 3 node cluster, wait for full replication
- kills node 1 and 2
- runs `debug zip` against the third node (from the third node, so it's just executing it against localhost), printing the output into the test runner
- downloads && extracts the zip file and checks that we at least get the gossip_* tables dumped successfully
- and any other commands that we think should finish in that case (not sure if there are even any)

To check the replication, you can use this:

```go
for ok := false; !ok; {
	if err := db.QueryRow(
		"SELECT min(array_length(replicas, 1)) >= 3 FROM crdb_internal.ranges",
	).Scan(&ok); err != nil { /* */ }
}
```

**Comment by couchand** [comment]
> In the context of this issue I'm mostly interested in "if the cluster is in a certain state of unhappiness, can the debug pages still surface the information we expect them to"? Whereas in lots of the frontend tests you probably just want to know "does this work at all".

In a lot of the more interesting cases, we need to be able to spin up a variety of clusters of different configurations.  Being in a "certain state of unhappiness" seems like a special case of being in a certain state.

That's just to say, I'm happy to have this particular issue be a prototype/first pass of doing some headless browsing of the admin UI after/during roachtesting.

**Comment by tschottdorf** [comment]
See https://github.com/cockroachdb/cockroach/issues/29638. Should verify that this works.
