### ISSUE TITLE
docgen: Some JSON functions are grouped under Compatibility

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#24474]
See https://www.cockroachlabs.com/docs/stable/functions-and-operators.html#compatibility-functions or examples (e.g., `json_array_elements(input: jsonb)` and `json_each(input: jsonb)`).

These should be grouped under JSONB Functions: https://www.cockroachlabs.com/docs/stable/functions-and-operators.html#jsonb-functions.

**Comment by knz** [comment]
There are now grouped under "set-returning functions" in docs.
