### ISSUE TITLE
pgwire: JDBC driver requires password even when certs are specified in connection string

### ISSUE THREAD

**Issue by cody-yancey** [cockroachdb/cockroach#24487]
I am attempting to connect to a secure cluster through a local haproxy using the JDBC driver. Connecting through the cli tool works correctly using the 

```
$ cockroach sql --certs-dir /User/yancey/cockroach/certs/ --host cockroachdb-test-secure --port 1234 --user yancey
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.
#
# Client version: CockroachDB CCL v1.1.0 (darwin amd64, built 2017/10/18 08:13:30, go1.9.1)
# Server version: CockroachDB CCL v2.0-beta.20180312 (linux amd64, built 2018/03/12 17:51:27, go1.10)
# Cluster ID: 04a44e90-110b-4877-9379-927cea8acd35
#
# Enter \? for a brief introduction.
#
yancey@cockroachdb-test-secure:1234/> 
```

The host `cockroachdb-test-secure` resolves to a loopback address, but that hostname **is** in the certs for each server host (as should be obvious by the fact that the CLI works). Trying to do the same thing using the JDBC driver:

```
  import java.sql.{Connection, DriverManager}
  val connectionString = "jdbc:postgresql://cockroachdb-test-secure:1234?" +
    "ssl=true" +
    "&user=yancey" +
    "&sslcert=%2FUsers%2Fyancey%2Fcockroach%2Fcerts%2Fclient.yancey.crt" +
    "&sslkey=%2FUsers%2Fyancey%2Fcockroach%2Fcerts%2Fclient.yancey.key" +
    "&sslmode=require" +
    "&sslrootcert=%2FUsers%2Fyancey%2Fcockroach%2Fcerts%2Fca.crt"

  Class.forName("org.postgresql.Driver")
  val driver = DriverManager.getConnection(connectionString)
```

produces an exception:
```
Exception in thread "main" org.postgresql.util.PSQLException: The server requested password-based authentication, but no password was provided.
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:366)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:108)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:32)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:393)
	at org.postgresql.Driver.connect(Driver.java:267)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	...
```

I see one of two potential bugs here, though I am not sure which:

1.) JDBC certificate-based authentication may be broken in the latest 2.0 beta release, or
2.) I have done something incorrect, and a misleading error message is being thrown.

I would expect to at least see something along the lines of "invalid parameter" or "invalid certificate for user yancey" or "couldn't find valid certificate/key at ..." or for it to successfully connect.

I should mention that password-based authentication works just fine and meets my needs for the forseeable future. It was just a bug I ran into while following your docs. I have not tried this on previous releases. Let me know if I can provide any more details. Thanks.

**Comment by mberhault** [comment]
JDBC has an unusual way to specify certificates for authentication. We filed an [issue](https://github.com/cockroachdb/docs/issues/631) to provide language and driver examples in secure more, but have yet to do the jdbc one.

You can find some guidance in [this forum post](https://forum.cockroachlabs.com/t/connecting-to-an-ssl-secure-server-using-jdbc-java-and-client-certificate-authentication/400), but I have not tried them myself.

You mention the possibility of this being a bug in 2.0. Did you get it to work in previous releases?

**Comment by 0xbaadf00d** [comment]
It working, but you have to use Java PKCS8 version of your "Key". You can use this command to convert your client .key file :

```
openssl pkcs8 -topk8 -inform PEM -outform DER -in IN.KEY -out OUT.pk8 -nocrypt
```

**Comment by priitp** [comment]
I'm getting "org.postgresql.util.PSQLException: The server requested password-based authentication, but no password was provided." exception when I do not set the certificate. From the stack trace it is visible that driver does not even try to start SSL connection (org.postgresql.ssl.MakeSSL.convert method seems to be the entry point).

Example code:

`        @Bean
        public DataSource getDataSource() {
                PGSimpleDataSource dataSource = new PGSimpleDataSource();
                        try {
                                dataSource.setUrl(url);
//                              dataSource.setUser(username);
//                              dataSource.setPassword(password);
                                dataSource.setSslCert(cert);
                                dataSource.setSslKey(key);
                                dataSource.setSslRootCert(rootCert);
                                dataSource.setProperty("ssl", "true");
                        } catch (SQLException e) {
                                throw new RuntimeException("Setting dataSource properties failed!", e);
                        }

                return dataSource;
        }
`

**Comment by priitp** [comment]
> that driver does not even try to start SSL connection 

I was wrong here ;) org.postgresql.ssl.jdbc4.LibPQFactory and friends just ignore client certificate related errors and happily proceed even if client authentication fails.

>It doesn't work here, and I was already using the PKCS8 key format

@mqudsi, you might want to set system parameter javax.net.debug to ssl:handshake:verbose (for example by adding parameter -Djavax.net.debug=ssl:handshake:verbose to the command line) and check the output. Failed client authentication will look something like this:
```

*** CertificateRequest
Cert Types: RSA, ECDSA
Supported Signature Algorithms: SHA256withRSA, SHA256withECDSA, SHA384withRSA, SHA384withECDSA, SHA512withRSA, SHA512withECDSA, SHA1withRSA, SHA1withECDSA
Cert Authorities:
<EMAILADDRESS=john.doe@example.com, CN=John Doe, OU=<censored>, L=Stockholm, ST=Stockholm County, C=SE>
main, READ: TLSv1.2 Handshake, length = 4
*** ServerHelloDone
Warning: no suitable certificate found - continuing without client authentication
*** Certificate chain
<Empty>
```
Keys in wrong format should trigger exception from security provider.

**Comment by obissick** [comment]
Having this same issue.

**Comment by rmloveland** [comment]
[Build a Java app with CockroachDB](https://www.cockroachlabs.com/docs/dev/build-a-java-app-with-cockroachdb.html) has just been updated with instructions for connecting a JDBC driver to a secure cluster using certificates for authentication (also Hibernate, FWIW).

The series of steps involved is quite specific, and it took a while to figure out due to non-optimal (sometimes nonexistent) error messages from the Java/JDBC side, but it definitely works.

Since this does not appear to be a CRDB bug, I'm closing this issue.  Please take a look at [the updated docs](https://www.cockroachlabs.com/docs/dev/build-a-java-app-with-cockroachdb.html) and reach out via the [forum](https://forum.cockroachlabs.com) or [gitter](https://gitter.im/cockroachdb/cockroach) if you are still encountering issues.   If you find something incorrect or confusing in the docs, please [file an issue against the docs](https://github.com/cockroachdb/docs/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).

Thanks for reporting this @cody-yancey, and sorry for the wait.  I hope the updated docs help!

**Comment by verglor** [comment]
I have the same problem. I can connect over SSL with any user except root, since it is impossible to connect without password and password cannot be used with root. It also means that I cannot use DBeaver with root user over SSL - it works only in insecure mode without password.
