### ISSUE TITLE
server:  net.go:159: *net.OpError

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#24481]
https://sentry.io/cockroach-labs/cockroachdb/issues/514058976/

```
*log.safeError: net.go:159: *net.OpError
  File "github.com/cockroachdb/cockroach/pkg/server/server.go", line 1113, in 1
  File "github.com/cockroachdb/cockroach/pkg/server/server.go", line 1112, in func15
  File "github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go", line 192, in func1

net.go:159: *net.OpError
```

**Comment by petermattis** [comment]
Not sure what this is about, but it is happening on v2.0.0. @tschottdorf for triage.

**Comment by bdarnell** [comment]
`net.OpError` is pretty broad, and this is not necessarily anything under our control. For example, I think you'd get an OpError here if you ran out of file descriptors, although this condition would also (probably) prevent the process from sending a crash report. I'm not sure what this could be, but I doubt we're going to get anywhere without more information (such as the unredacted server log)
