### ISSUE TITLE
build: libtinfo does not exist on all Linux distributions

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#24492]
Since bbf07b5b98641283d1cf23edfbf3d4f9f37eb5c9 we've required libtinfo for line editing support in our interactive SQL shell. libtinfo is available on almost every Linux distribution we've been able to find, but, crucially, not on CoreOS, where it's packaged as part of ncurses instead.

Note that the damage is not limited to `cockroach sql` because we ship a fat binary. Users without a libtinfo in the right place will be unable to run _any_ `cockroach` command, as the binary will fail to load.

For now, CoreOS users can perform [this workaround](https://github.com/kubernetes/contrib/issues/1675) at their own risk:

```
sudo ln -s /lib64/libncurses.so.5.9 libtinfo.so.5
```

We're looking to fix this for 2.0.1.

**Comment by benesch** [comment]
If we continue to run into trouble, we might want to look into using `dlopen` to load libtinfo. There's no reason that `cockroach start` should fail when libtinfo is missing.

**Comment by bdarnell** [comment]
You mean on coreos outside of any container? I thought the entire point of coreos was that everything you care about ran inside a container so it didn't matter that the outer OS was minimal and potentially quirky.

**Comment by a-robinson** [comment]
Yes, on coreos outside of any container. Mesos doesn't run everything in docker (it runs everything in cgroups/namespaces, but not necessarily on top of a custom filesystem image like a docker image), and it pretty commonly uses coreos as a default OS.
