### ISSUE TITLE
stopper: spammy log message about throttling async task

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#24512]
Run a local cluster and open the Admin UI and navigate to one of the dashboards. Fairly quickly you'll see a lot of log spam that looks like:

```
I180405 16:20:30.549882 1974 util/stop/stopper.go:291  [n1,ts-srv] stopper throttling task from ts.Server: query due to semaphore
```

By default, `ts` uses 8 worker threads, but the admin UI graph dashboards often have many more requests.

We should either remove this spammy log message or adding a flag to `RunAsyncTask` to silence it in this use case.

@bdarnell, @spencerkimball Thoughts?

**Comment by bdarnell** [comment]
That message isn't valuable; we should just downgrade it to log.Eventf.
