### ISSUE TITLE
sql: need improved API for making distsql plans

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#24519]
IMPORT's use of distsql is bad due to some current API limitations.

The SQL layer finds an IMPORT statement and sees that importccl has registered a handler for it and calls the code in importccl. importccl needs to create a distsql plan when reading CSV files. However the methods and fields on `sql.DistSQLPlanner` are unexported. So importccl calls back into the sql directory (https://github.com/cockroachdb/cockroach/blob/c0191d4275a802674578d0747be300c9f70c6a73/pkg/sql/distsql_plan_csv.go#L113) do to the actual distsql planning and execution.

It would be nice if distsql_plan_csv.go could be moved into the importccl package. This would force API changes or exporting to be done such that a distsql plan could be created and executed outside of the sql package.

There are certainly some easy changes to make by just exporting a bunch of stuff. I'm not sure if that will be enough or not. Also we've tried really hard to not export `sql.planner`, and it's unclear if doing this will require that or something close to that.

**Comment by jordanlewis** [comment]
Not sure if we'll get to this, let's reopen if we have plans to.
