### ISSUE TITLE
sql: possible flakiness of logic test rename_table

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#24528]
The following popped up on `master` on a totally unrelated change:
```
[/rename_table] logic.go:2116: 
	testdata/logic_test/rename_table:256: 
	expected success, but found
	pq: relation "d.kv2" does not exist
logic.go:2132: 
	testdata/logic_test/rename_table:256: error while processing
logic.go:2133: pq: relation "d.kv2" does not exist
```

https://teamcity.cockroachdb.com/viewLog.html?buildId=592315&buildTypeId=Cockroach_UnitTests

**Comment by tschottdorf** [comment]
ogic.go:2127: 
    testdata/logic_test/rename_table:256: 
    expected success, but found
    pq: relation "d.kv2" does not exist
logic.go:2143: 
    testdata/logic_test/rename_table:256: error while processing
logic.go:2144: pq: relation "d.kv2" does not exist

https://teamcity.cockroachdb.com/viewLog.html?buildId=683582&buildTypeId=Cockroach_UnitTests

**Comment by petermattis** [comment]
This hasn't failed in many months (the teamcity artifacts are long gone). I'm attempting to stress locally, but so far no reproduction.

**Comment by petermattis** [comment]
```
~ make stress PKG=./sql/logictest/ TESTS='TestLogic//^rename_table$/' TESTFLAGS=-v
...
1739 runs completed, 0 failures, over 20m7s
```

Closing as unreproducible. Something was probably fixed since the above failures occurred.
