### ISSUE TITLE
sql: bad Sql statement causes server panic

### ISSUE THREAD

**Issue by jrote1** [cockroachdb/cockroach#24545]
When running the following query `SELECT id, record_json FROM transaction_records WHERE (record_json -> $1) = $2` where both placeholders are of type STRING. When executed it causes a server panic. The correct sql is `SELECT id, record_json FROM transaction_records WHERE (record_json ->> $1) = $2` note `->>` opposed to `->`.  The query should fail but should not cause a server panic.

![image](https://user-images.githubusercontent.com/4202486/38411404-f0a9d78c-397e-11e8-8d27-f17ce1c3e26d.png)

**Comment by petermattis** [comment]
https://sentry.io/cockroach-labs/cockroachdb/issues/517037310/

**Comment by justinj** [comment]
Sorry you ran into that @jrote1! I've opened #24576 to fix this, which should make it into the next point release. Thanks for the bug report, always appreciated.
