### ISSUE TITLE
sql: views do not track string-based dependencies properly

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#24556]
```sql
CREATE SEQUENCE s;
CREATE VIEW v AS SELECT nextval('s');
ALTER SEQUENCE s RENAME TO u;
SELECT * FROM v;
```

Fails with:

```
pq: nextval(): relation "s" does not exist
```

This is because CockroachDB fails to peek into strings that designate object names.

Other possible failing cases: `'tablename'::regclass` and related constructs.

The reason why pg does not suffer from this is that object name strings are converted to OIDs internally, and those OIDs don't change across renames.

cc @jordanlewis

**Comment by knz** [comment]
It's likely that the logic that restricts BACKUP/RESTORE to work on "closed" sets of objects is similarly flawed.

**Comment by jordanlewis** [comment]
Hey @rohany I'm putting this on your mental roadmap. I think we should fix this kind of thing at some point in the medium term.
