### ISSUE TITLE
cli/sql: client crash resizing console

### ISSUE THREAD

**Issue by kalman5** [cockroachdb/cockroach#24569]
**BUG REPORT**

CRDB 2.0. Linux Kubuntu 17.10

Steps to reproduce: 
$ cockroach sql -d <db_name> --insecure

at this point resizing the console so to have very few columns (horizontal stretch) it crashes and this is the "dump" (some time happens at the first strech some time I need to stretch/enlarge it several time)
 

 Welcome to the cockroach SQL interface.

All statements must be terminated by a semicolon. 
 To exit: CTRL + D.

Server version: CockroachDB CCL v2.0.0 (x86_64-unknown-linux-gnu, built 2018/04/03 20:56:09, go1.10) (same version as client)
 Cluster ID: 258c58b1-5a96-48d1-b5c2-19ee61343f81

Enter \? for a brief introduction.

root@:26257/xxxxxx> fatal: morestack on g0
SIGTRAP: trace trap
PC=0x72cd32 m=0 sigcode=128

goroutine 0 [idle]:
runtime.morestack()
        /usr/local/go/src/runtime/asm_amd64.s:451 +0x22

goroutine 1 [syscall]:
github.com/cockroachdb/cockroach/vendor/github.com/knz/go-libedit/unix._C2func_go_libedit_gets(0x7ff889845000, 0x7ff88980da00, 0x0, 0x0, 0xc4202e75d0, 0xc4202e75d4, 0x1, 0x0, 0x0, 0x0)
        _cgo_gotypes.go:180 +0x5c
github.com/cockroachdb/cockroach/vendor/github.com/knz/go-libedit/unix.EditLine.GetLine.func1(0x7ff889845000, 0x7ff88980da00, 0x0, 0x0, 0xc4202e75d0, 0xc4202e75d4, 0xc400000001, 0x8980da002086f9b8, 0xc420060c00, 0xc42086f978)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/knz/go-libedit/unix/editline_unix.go:267 +0xc8
github.com/cockroachdb/cockroach/vendor/github.com/knz/go-libedit/unix.EditLine.GetLine(0x0, 0x15, 0x7ff88980da00, 0xc42086f9e8, 0x19c4323)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/knz/go-libedit/unix/editline_unix.go:267 +0xe1
github.com/cockroachdb/cockroach/pkg/cli.(*cliState).doReadLine(0xc4200fa820, 0x6, 0x5)
        /go/src/github.com/cockroachdb/cockroach/pkg/cli/sql.go:719 +0x45f
github.com/cockroachdb/cockroach/pkg/cli.runInteractive(0xc42041ae00, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/cli/sql.go:1097 +0x68f
github.com/cockroachdb/cockroach/pkg/cli.runTerm(0x3488ca0, 0xc420854120, 0x0, 0x3, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/cli/sql.go:1179 +0x159
github.com/cockroachdb/cockroach/pkg/cli.MaybeDecorateGRPCError.func1(0x3488ca0, 0xc420854120, 0x0, 0x3, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/cli/error.go:39 +0x5a
github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).execute(0x3488ca0, 0xc4208540c0, 0x3, 0x3, 0x3488ca0, 0xc4208540c0)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:698 +0x46d
github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x3485340, 0x6, 0x0, 0xc4205e7ee8)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:783 +0x2e4
github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).Execute(0x3485340, 0x18, 0xc4205e7f00)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:736 +0x2b
github.com/cockroachdb/cockroach/pkg/cli.Run(0xc42003a150, 0x4, 0x4, 0xc420040078, 0xc420270000)
        /go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:156 +0x6d
github.com/cockroachdb/cockroach/pkg/cli.Main()
        /go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:51 +0x15d
main.main()
        /go/src/github.com/cockroachdb/cockroach/main.go:27 +0x20

goroutine 19 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:139 +0xa6
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 6 [chan receive]:
github.com/cockroachdb/cockroach/pkg/util/log.flushDaemon()
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:1131 +0xf1
created by github.com/cockroachdb/cockroach/pkg/util/log.init.0
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:592 +0x110

goroutine 7 [chan receive]:
github.com/cockroachdb/cockroach/pkg/util/log.signalFlusher()
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:601 +0x105
created by github.com/cockroachdb/cockroach/pkg/util/log.init.0
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:593 +0x128

goroutine 36 [select, locked to thread]:
runtime.gopark(0x241a850, 0x0, 0x23200f3, 0x6, 0x18, 0x1)
        /usr/local/go/src/runtime/proc.go:291 +0x11a
runtime.selectgo(0xc420485f50, 0xc4200a6120)
        /usr/local/go/src/runtime/select.go:392 +0xe50
runtime.ensureSigM.func1()
        /usr/local/go/src/runtime/signal_unix.go:549 +0x1f4
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2361 +0x1

rax    0x17
rbx    0x39e7c80
rcx    0x7307a5
rdx    0x17
rdi    0x2
rsi    0x233c3a3
rbp    0x7fff19ef8070
rsp    0xc420009978
r8     0x7ff88d20d1c0
r9     0x46
r10    0x8
r11    0x216
r12    0xc420106038
r13    0x14
r14    0x11
r15    0x100
rip    0x72cd32
rflags 0x212
cs     0x33
fs     0x0
gs     0x0
`

**Comment by knz** [comment]
@kalman5 thanks for your report! Apologies for the late reaction. We'll look into this. 

Just to clarify, were you using one of our pre-built binaries or did you build CockroachDB yourself from source?

**Comment by kalman5** [comment]
Your binary. And I was using Konsole from KDE

**Comment by knz** [comment]
Thanks. Initial research shows this problem should be independent of the terminal emulator you're using. Can you confirm?

**Comment by knz** [comment]
Was able to reproduce with `xterm` and `st` and other terminals but not `tmux` or `screen`.

This is likely to have something to do with the frequency of the SIGWINCH signal. The "real" terminal emulators send SIGWINCH on every resize event, whereas the terminal multiplexers will batch them together.

Need to investigate further.

**Comment by knz** [comment]
We have addressed this in the code leading to version 19.2.
