### ISSUE TITLE
distsqlrun: improve hash join to use available memory when spilling to disk

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#24580]
DistSQL uses a simple hash join algorithm that spills to a disk container in the probe phase if the hash table exceeds the available memory for the join. This disk container is a RocksDB-managed store that uses RocksDB seeks to do the table lookups.

Once the algorithm decides to spill to disk, it completely abandons its in-memory hash table. From then on, the algorithm doesn't use significant amounts of (Go) memory for the side that was spilled.

The hash disk container should use the memory it spilled... for *something*. There are several things that we could be doing with that memory. For example:

- use memory as a write-through cache for *marked rows*, which are currently written directly to disk with a batch size of at minimum 1 row if all rows match.
- give memory to the disk container RocksDB instance for use as a RocksDB cache. Currently, we use no RocksDB cache for the disk container.
- use memory to implement a more advanced hash join algorithm like GRACE hash join or hybrid hash join. This is a bigger project, but might be a good idea anyway. I'll write up details on those in another issue and link to it later.

**Comment by petermattis** [comment]
> use memory as a write-through cache for marked rows, which are currently written directly to disk with a batch size of at minimum 1 row if all rows match.

Not quite sure what this means, but when I read the title of this issue I thought "we should be batching a decent number of rows for each write to the disk storage container".

> give memory to the disk container RocksDB instance for use as a RocksDB cache. Currently, we use no RocksDB cache for the disk container.

RocksDB cache helps random read performance. I don't think it will do anything for write performance or sequential read performance.

**Comment by petermattis** [comment]
> This data structure needs to perform random reads - we're using it like a hash table. That's why I figured the cache could be useful.

Ah, I was confused with `sorter`. Yes, increasing the RocksDB block cache size could be useful here. Alternately, we could share the block cache with the process-wide block cache that is shared between stores.

**Comment by jordanlewis** [comment]
No longer relevant; superseded by vectorized.
