### ISSUE TITLE
distsqlrun: implement GRACE hash join (for equality joins only)

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#24582]
See #24580 for a description of the current hash join algorithm. The tl;dr is that the current hash join algorithm performs `n` RocksDB disk seeks if the probing side of the hash join has `n` rows in it. This is expensive.

GRACE hash join is a slightly more sophisticated hash join algorithm, usable for equality joins only, that will give us better runtime properties when hash join needs to spill to disk. It operates in two phases, once the join runs out of memory and must spill to disk. The high level view is that it partitions the left and right side into large buckets by a hash function `A`, writes those buckets to disk, then iterates through pairs of those buckets and does a normal hash join with a different hash function `B`.

**Phase 1: partitioning**
In this phase, we iterate through both sides of the join, hashing every row using a hash function `A` that produces `n` partitions. This will produce `n` partitions for each side of the join, which will be persisted to disk separately. As memory fills up, each of these partitions is flushed to disk repeatedly until the inputs are exhausted.

**Phase 2: join**
Now, we retrieve pairs of partitions from disk and join each pair using the ordinary hash join algorithm (and a different hash function `B`). Since we're performing an equality join, we can guarantee that each row on the left side of the join, if it has a match, will be in the same partition on the right side of the join. So, it's safe to do the join in pieces, partition by partition.

If one of the partition hash joins itself runs out of memory, we can recursively apply this algorithm. The partition will be divided into sub-partitions by a new hash function, spilled to disk, and so on.

----

Because of the danger of having to recursively spill to disk, it's important to pick a hash function that partitions the input streams into reasonable sizes. I think this is probably only possible given table statistics because you need to know the approximate size of the table to determine how many partitions you need of the table such that each partition fits into the available SQL memory.

cc @rytaft - will table statistics include the approximate size of the entire table?

**Comment by jordanlewis** [comment]
I forgot to mention that in the happy case (no recursive disk spilling), GRACE hash join will outperform the current hash join algorithm in terms of disk IOs. It has to perform `n * 2` disk seeks where `n` is the number of partitions we choose for the tables.

**Comment by jordanlewis** [comment]
Finally, there's an enhancement to GRACE hash join called hybrid hash join, which AFAICT is basically the same as GRACE hash join except it never flushes partition 0 on each side to disk - it just does the hash join for partition 0 during the partitioning phase. This saves a little bit of time.

See http://www.dcs.ed.ac.uk/home/tz/phd/thesis/node21.htm for more details on both these algorithms.

**Comment by rytaft** [comment]
We don't explicitly track the table size yet - we only track the number of rows. But I think we'll need to add stats for table size or average column size.

cc @RaduBerinde, @andy-kimball

**Comment by RaduBerinde** [comment]
Before we spend effort on this, we should make sure this can outperform sort + mergejoin. My hunch is that it usually won't (given that whenever we put things in RocksDB, we more or less sort them in some way).

**Comment by jordanlewis** [comment]
Closing this, but we'll probably want to use this for the disk spilling vectorized hash joiner.
