### ISSUE TITLE
opt: automatic generation of statistics

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#24586]
Currently statistics can only be generated manually. We need to automatically generate stats periodically. There are many aspects to this:
 - which column(s) do we generate statistics for. A decent choice is based on indexes (including PKs): for an index on `(a,b,c)`, generate cardinality + histogram on `a`, cardinality on `(a, b)` and cardinality on `(a, b, c)`.
 - how often to refresh stats. Ideally this would somehow be adaptive to how much a table is being modified. We really want to avoid refreshing stats for large static tables.
 - how to minimize the effect on a running cluster:
   * don't generate stats for too many tables at the same time
   * schedule stat generation around high load times
   * rate limit the reads for stat generation.

**Comment by awoods187** [comment]
Ran into this today when testing automatic stats https://github.com/cockroachdb/cockroach/issues/34745

**Comment by RaduBerinde** [comment]
Stats are on by default in the latest alpha.
