### ISSUE TITLE
roachtest: drop test fails, space not reclaimed

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#24592]
https://teamcity.cockroachdb.com/viewLog.html?buildId=593804&buildTypeId=Cockroach_Nightlies_WorkloadNightly

>
 drop.go:147,cluster.go:794,errgroup.go:58: Disk space has not been freed within 10 minutes of deletion.

**Comment by tschottdorf** [comment]
We now have the test failures:

```
[06:35:29]	drop.go:154,cluster.go:794,errgroup.go:58: Node 8 space after deletion used: 5.7 GiB
[06:35:29]		disk space usage has not dropped below 100 MiB on all nodes.
```

Not surprising, but at least we see that we're missing this a lot. I wonder how far we can really get here without some insight in the compactor, see #25073.

**Comment by tschottdorf** [comment]
@m-schneider could you investigate this further this week? They way I would do this is to create a cluster and run the test against it repeatedly, with the `--debug` flag. When it fails leave the cluster running (you can hack the test to do this for you by calling `os.Exit(1)` instead of `t.Fatal`), investigate the node(s) that claims the high disk space usage, and see if you can find anything. My guesses would be that a) the compactor doesn't get around to processing the compaction within the 10min interval we give it (see the metrics and log messages) b) compactions are discarded (metrics) or c) there's a more fundamental problem (less likely).

**Comment by m-schneider** [comment]
Did some investigating on this issue. On a 9 node cluster 1 node didn't reclaim space. I left the cluster running several hours after the test failed and the space still wasn't reclaimed. When looking at compactor logs, there weren't any compactions that were started but incomplete. After running  `./cockroach debug compact` the space was reclaimed.

**Comment by tschottdorf** [comment]
Closing for #26147, which gets the nightly posts.
