### ISSUE TITLE
sql: mark internal queries via app name in reporting 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#24603]
Cockroach binary should use constant app name for internal queries and whitelist from hashing when data appears in diagnostic.

This allows identifying or filtering queries such as migrations when analyzing reporting

**Comment by awoods187** [comment]
CC @BramGruneir could you take a look at this since you've been in this code base recently?

**Comment by awoods187** [comment]
CC @dt @knz

**Comment by dianasaur323** [comment]
This sounds like it could also cover "dump"? Did we want to put this in a separate table vs hacking the app name?

**Comment by dt** [comment]
the app name is _supposed_ to identify where queries came from, so it makes sense that we'd use an internal app name to run internal queries e.g. migrations. the missing piece is that we scrub the app names when we report to us -- since they could be sensitive -- but in the case of the special internal name, we can (and maybe should) leave it, since we know it isn't.

**Comment by knz** [comment]
:+1: on dt's proposal.

We can make this reliable by defining some list of known internal app names (e.g. auto-generated from the specific constant values we use for the various CLI commands) and using that as whitelist.

**Comment by knz** [comment]
For the record one of my recent changes ensures that every CLI command uses a different, predefined value for application_name. If we stop scrubbing them out, we'd have the SQL usage broken up by CLI command.

**Comment by knz** [comment]
@dt this issue really wants to live in a github project dedicated to metadata collection and telemetry. Do we have one already?

**Comment by kannanlakshmi** [comment]
Application names beginning with $ sign was decided at the telemtry meeting

**Comment by solongordon** [comment]
Fixed by https://github.com/cockroachdb/cockroach/pull/28413.
