### ISSUE TITLE
cert: bad certs that prevent node startup should log much louder

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#24621]
Node certificates that do not fit an expected format can prevent a cluster from successfully forming. For instance, a user on gitter recently had a difficult time starting a cluster while using certs generated by https://github.com/cloudflare/cfssl because we failed to document that the subject line of the node certificates had to be `O=Cockroach, CN=node`. This was confusing because very little was logged while the nodes were struggling to connect. We can improve documentation to avoid specific issues like this, but in general, we should also log these startup-preventing errors much louder.

**Comment by mberhault** [comment]
On the docs side, it's deep within the [create certificates, openssl tab](https://www.cockroachlabs.com/docs/stable/create-security-certificates-openssl.html#create-the-certificate-and-key-pairs-for-nodes) which has all the details needed to generate the same certs created by `cockroach cert`. Any tool other than `cockroach cert` should adapt the openssl docs.

As for the error, there's unfortunately not a whole lot get can get out of bad certificates, this is deep within the tls code. Just about the only way to get certificate details before handshake is to set `InsecureSkipVerify` and do all the cert checking ourselves (which is just asking for trouble).

**Comment by zllovesuki** [comment]
@mberhault I think the subsection should have a red background instead of blue background to be honest

**Comment by bdarnell** [comment]
Some errors are out of our hands (including CA or SAN failure), but the issue here was the common name field, and isn't that part under our control? (Even the failures that are coming from within the TLS library should return errors that we ought to be able to log, although they may not be plumbed all the way through cmux/grpc).

**Comment by bdarnell** [comment]
Also, we should be able to validate the certs for this particular issue without even going over the network. The server should check at startup that `$(certs-dir)/node.crt` has the correct common name, etc, and crash if not.

**Comment by mberhault** [comment]
Good point. Filed #24632 to perform additional validation. It wouldn't crash, just exit with error since we load certificates before starting anything (eg: try running `cockroach start --certs-dir=not-a-real-dir`).

Also filed #24630 for additional (online and offline) debugging tools.

**Comment by mberhault** [comment]
I've also filed https://github.com/cockroachdb/docs/issues/2899 to look into and maybe document cert generation using `cfssl`.

**Comment by wrouesnel** [comment]
Can I +1 this loudly? I just lost about 16 hours of messing around with certificates which looked and validated correctly, but which would not allow a node to join at all.

The logs for this need to _scream_ that this is the problem and why a cluster node is not joining. This is not at all obvious nor was it mentioned in any of the getting started/securing a cluster documentation.

**Comment by mberhault** [comment]
Sure. #24630 is a more focused issue and describes the work left to be done better. The common issues detectable without connection have been addressed.
