### ISSUE TITLE
sql: support DEFAULT expressions for columns

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#2466]
For example:

```
CREATE TABLE test (
  a INT PRIMARY KEY,
  b INT DEFAULT 22
)
```

We'll need to store the default expression in the `ColumnDescriptor` and utilize it on `INSERT` if a value isn't specified for the column.

**Comment by petermattis** [comment]
Rather then storing the default value in the row on insert, we can define the default value as the value to return for a column when a value has not be sent. This means that changing the default value for a column will cause subsequent SELECT statements to retrieve a new value. Since changing the default value for a column is rare, this shouldn't be too burdensome. We'll want to provide a syntax for baking the existing default value into rows. Something like: `UPDATE tbl SET col=DEFAULT WHERE col=DEFAULT`.

**Comment by fredrikroos** [comment]
Postgres evaluates defaults when the row is created, since the most common use case for them (apart from nullable columns) are timestamps and sequences.

**Comment by petermattis** [comment]
Hmm, that's a good point about timestamps. Thanks for the reminder, @fredrikroos.

**Comment by petermattis** [comment]
In postgres, the default expression can be any variable-free expression. MySQL is more restrictive and only allows constants and `CURRENT_TIMESTAMP`. It does not seem difficult to support the more general case of any variable free expression.
