### ISSUE TITLE
sql: limited applicability of jsonb_array_elements function  due to lack of correlated SQs

### ISSUE THREAD

**Issue by ms-mullins** [cockroachdb/cockroach#24676]
We're attempting to use the _jsonb_array_elements_ function with CockroachDb 2.0 and it appears to generate an error. Here’s the test case to reproduce:
 
```
 create table test(
       id SERIAL,
       data jsonb,
       primary key (id)
    );
 
insert into test(data) values('{"name": "foo", "members": [{"name": "admin", "type": "USER"}]}');

select * from jsonb_array_elements(test.data->'groupMembers');
```
 
We getting: "SQL Error [42P01]: ERROR: no data source matches prefix: test". If we’re doing something incorrect, it’s unclear what that is.

cockroach version
Build Tag:    v2.0.0
Build Time:   2018/04/04 14:43:38
Distribution: CCL
Platform:     darwin amd64 (x86_64-apple-darwin17.3.0)
Go Version:   go1.10.1
C Compiler:   4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)
Build SHA-1:  a6b498b7aff14234bcde23107b9e7fa14e6a34a8
Build Type:   development

**Comment by justinj** [comment]
Hi @ms-mullins,

I agree that error message is not particularly helpful, but what are you trying to achieve? If you want to return every single member of a `members` array, the following will work in Postgres:
```sql
select jsonb_array_elements(data->'members') from test;
```
but not in CockroachDB, since there's an implicit correlated subquery, which we don't support today. I'm not sure if there's a way in CockroachDB's current dialect to achieve this (though we're planning to support correlated subqueries in 2.1).

Can you outline what the output you're hoping for is, and maybe we can find a way to write a query to return it?

cc @knz, I think the root problem here is that the error message doesn't illustrate the fact that the query is actually wrong, or give a hint at how to fix it.

**Comment by knz** [comment]
I filed #24684 to address this (how to detect and report correlation). Justin can you bring that issue to our next roundtable?

**Comment by nvanbenschoten** [comment]
@rnestertsov you're correct that without correlated subqueries the query you posted won't work in Cockroach. This is unfortunate, and we're actively looking to address the issue by adding in support

```
```

**Comment by nvanbenschoten** [comment]
@rnestertsov you're correct that without correlated subqueries the query you posted won't work in Cockroach. This is unfortunate, and we're actively looking to address the issue by adding in correlated subquery support.

For now, you can try the following query, which acheives the same outcome (in a less efficient way):
```sql
SELECT *
FROM
  (SELECT DATA->'name' AS role_name,
          DATA->'members'->generate_series AS user_name
   FROM groups,
     (SELECT generate_series(0,
                               (SELECT max(json_array_length(DATA->'members')) - 1
                                FROM groups)::INT)))
WHERE user_name IS NOT NULL;
```

**Comment by awoods187** [comment]
@jordanlewis and @andy-kimball i was expecting this to work post-Apply and I just checked on master (v19.1.0-beta.20190304-458-g70e3468) and it does not:
```
root@localhost:26257/tpcc> create table test(                                                                                                                                                                                                                                   id SERIAL,                                                                                                                                                                                                                                                               data jsonb,                                                                                                                                                                                                                                                              primary key (id)                                                                                                                                                                                                                                                      );
CREATE TABLE

Time: 1.85184438s

root@localhost:26257/tpcc> insert into test(data) values('{"name": "foo", "members": [{"name": "admin", "type": "USER"}]}');
INSERT 1

Time: 762.728077ms

root@localhost:26257/tpcc> select * from jsonb_array_elements(test.data->'groupMembers');
pq: no data source matches prefix: test
```

**Comment by jordanlewis** [comment]
@awoods187 yeah that one doesn't work because we still don't support the implicit lateral join thing - but the one where you reorder it to put the data source in the FROM (a valid workaround) does.

```
select jsonb_array_elements(data->'members') from test;
```

**Comment by justinj** [comment]
The original query in this issue isn't valid, even in Postgres:
```
postgres=# select * from jsonb_array_elements(test.data->'groupMembers');
ERROR:  missing FROM-clause entry for table "test"
LINE 1: select * from jsonb_array_elements(test.data->'groupMembers'...
```

**Comment by knz** [comment]
> `select * from jsonb_array_elements(test.data->'groupMembers');`

This does not work in pg, however this does:

```sql
select * from test, jsonb_array_elements(test.data->'groupMembers');
```

however, it does not in cockroachdb. 

This is because crdb does not know about the following rule: in a cross-join expression `a,b`, if `b` is a SRF applicaiton, then `lateral` should be implicitly assumed.

**Comment by awoods187** [comment]
Here is the related lateral join issue for tracking https://github.com/cockroachdb/cockroach/issues/24560
