### ISSUE TITLE
sql: incomplete desugaring of type keywords into type names

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#24686]
Noticed while reviewing https://github.com/cockroachdb/docs/pull/2887.

The following PR #18530 introduced support for the special, internal-only type in PostgreSQL called `"char"`.

This is incomplete, see the [comment below](#issuecomment-381128880) for details.

**Comment by jordanlewis** [comment]
I don't really see the problem here - we alias `"char"` to `char` because, unlike PG, we don't have an actual behavioral or internal difference between `char` and `"char"`.

We also now support naming types in quotes, but only the ones that aren't recognized by the SQL standard. This is the same as PG as well. For example:

```
root@127.0.0.1:56746/demo> create table a (a "int8" primary key);
CREATE TABLE

Time: 6.208098ms
```

```
jordan=# create table zxzzz (a "int" primary key);
ERROR:  type "int" does not exist
LINE 1: create table zxzzz (a "int" primary key);
                              ^
jordan=# create table zxzzz (a "int8" primary key);
CREATE TABLE
jordan=#
```

**Comment by knz** [comment]
My point is that the test `if $1 == "char"` is ineffective. 
If you want to make a specially named type called `"char"`, the SQL input syntax for this is `"""char"""` and it will show up after scanning as `$1 == "\"char\""`.

**Comment by jordanlewis** [comment]
No, the input syntax is the INPUT literal `"char"`. Not the string literal `"char"`.

```
jordan=# create table daaz (a """char""" primary key);
ERROR:  type ""char"" does not exist
LINE 1: create table daaz (a """char""" primary key);
```

**Comment by knz** [comment]
Welp, that is then again a sign that the pg docs are wrong.  Thanks for pointing it out.

The situation I am working with is that our docs do not (yet) reflect this properly and the explanation is subtle. I'll need to investigate more before I can have a chat with Lauren and explain what's going on.

**Comment by knz** [comment]
All right I dug into the pg source code and it so happens that both of us were right, although neither of us had the right explanation for it :)

Where I was right:

- pg applies the same lexical rules and name resolution rules for types as it does for other things. That is, _in general_ (but not for `int` and `char`  and a few other specific things, see below) lexically the types `x` and `"x"` are the same if `x` is lowercase.
-  Moreover (what I suspected from the start), `pg_catalog.x` is the same as `x` for any predefined types (because they are defined in pg_catalog), that's why `pg_catalog.int8` is the same as `int8`.
- incidentally, pg will recognize any type reachable via `search_path` with its short name, and no other type beyond that (but see below)

Where you were right:

- you can't use `create table a( a "int")` even though `create a (a "char")` is valid. See below.

Where we were both missing something:

- there is no type called `int` in `pg_catalog` or anywhere else (!!)
- there is no type called `char` in `pg_catalog` or anywhere else (!!!)
- there is a grammar rule which desugars the *keyword* `CHAR` to the *identifier* `varchar` during parsing
- there is a grammar rule which desugars the *keyword* `INT` to the *identifier* `int4` during parsing
- ditto for the following types

Keyword | Desugars to
---|---
`INT` | `int4`
 `INTEGER` | `int4`
`SMALLINT` | `int2`
`BIGINT` | `int8`
`REAL` | `float4`
`DOUBLE PRECISION` | `float8`
`DECIMAL` | `numeric`
`DEC` | `numeric`
`BOOLEAN` | `bool`
`BIT` | `bit` or `varbit` depending on whether a precision is specified
`[NATIONAL] CHAR` | `varchar` or `bpchar`, depending on whether VARYING is specified
`NATIONAL CHARACTER` | ditto
`NCHAR` | ditto

So the input syntax `"char"` identifies the type `pg_catalog.char` because it bypasses the desugaring rule on the CHAR keyword.

**Comment by knz** [comment]
This has been completed (except for NCHAR which is just plainly not supported). Nothing actionable any more here.
