### ISSUE TITLE
distsql: Update internal columns of index join

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/cockroach#24698]
Currently the index join internal columns between an RowSource and a Table is all of the table columns.

It would be advantageous for the index join's internal columns to match those of a lookup join, specifically the row source columns concatenated with the table columns. This would allow the index join to decode fewer columns, since those can be fetched directly from the RowSource (rather than decoding them again).

The index join is implemented in the `joinReader`.

**Comment by jordanlewis** [comment]
Hey @justinj, is this sort of thing rendered unnecessary by the optimizer?
