### ISSUE TITLE
sql/driver: revisit retry behavior on timeout

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#2470]
The `sql/driver` currently has a 60s timeout on requests (recently changed from 3s). If a request times out it is retried. Indefinitely. This caused badness in one of the sqllogictests which was executing a statement that looked like: `INSERT INTO foo SELECT * FROM bar`. This statement copies all of the data from table `bar` into table `foo`. This was occurring outside of an SQL transaction, so the server executed the statement by itself inside a transaction. Because table `bar` had a 1000 rows with several columns and indexes there were 10s of thousands of keys being written and thus the insert was taken longer than 3s. The sql/driver retry timeout fired causing the same request to be sent to the server again which started another transaction which often caused the first transaction to get pushed and boom, we never actually finish executing the statement.

Retrying on timeout needs to be more carefully thought out. Perhaps for non-transactional requests the client should be generating the ID for the implicit transaction instead of letting it be generated server side. That way a retry will reuse the same transaction ID. That still sounds dangerous. Or maybe we shouldn't be retrying on timeout at all within `sql/driver`.

**Comment by bdarnell** [comment]
FWIW, other database drivers don't seem to retry on timeout, and when a network failure occurs you have no way of knowing whether your in-progress operations completed or not (except by querying the DB to see if the data you were trying to insert is there).

Generating a transaction ID on the client side is dangerous; generating a command ID seems safer. @tschottdorf's work is already transforming client-supplied batch IDs into per-request command IDs; we could probably do something similar here (use the client-supplied ID to deterministically generate the KV-level ClientCmdIDs). The tricky thing will be ensuring that the retry generates the same set of KV operations - this may not be possible unless we also put the client in charge of selecting the transaction timestamp.

**Comment by vivekmenezes** [comment]
I see the driver retrying only once when it sees an ErrBadConn error. Could it be possible that you are seeing an rpc timeout or something that is making the client drop the connection. For all other kinds of errors, the driver doesn't retry the command. Also, for the ErrBadConn case, it retries immediately without setting a backoff timer.

**Comment by petermattis** [comment]
@vivekmenezes Not sure what code you're looking at. I'm looking at https://github.com/cockroachdb/cockroach/blob/master/sql/driver/http_post.go#L115

**Comment by vivekmenezes** [comment]
https://golang.org/src/database/sql/sql.go

is what I was looking at. See Exec() ad Query(). The http code you mention was copied from the KV client. What happens when you run the tests without the retry? Do you see a lot of failures?

**Comment by petermattis** [comment]
Yep, I'm aware `database/sql` does not retry. Our driver retries. And up until yesterday it retried after a short timeout. That seems wrong. Hence the issue to discuss what we should do.

**Comment by vivekmenezes** [comment]
It's not obvious what we should do. If we were to use the end-to-end principle we would retry only at the highest layer in the stack where retry capability is expected. In this case my guess is that only an application can decide whether it wants to retry its transactions. It ultimately knows what other aspects of the application are waiting to make progress, what is the cost of completing the transaction, etc.

**Comment by petermattis** [comment]
`sql/driver` is now deprecated and the remaining uses are few and soon to be removed. Closing as will-not-fix.
