### ISSUE TITLE
ui: cluster viz should tell me when my license is expired

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#24701]
I'm seeing this screen:

![image](https://user-images.githubusercontent.com/5768024/38638412-2fbcc5bc-3d9c-11e8-9059-a5c61bc7a85e.png)

I ran show cluster setting enterprise.license, and I do have a license?

**Comment by dianasaur323** [comment]
nvm, my license expired. In that case, we should make it more obvious at some point? cc @piyush-singh, and feel free to close this if you already have an issue open

**Comment by piyush-singh** [comment]
I actually just encountered the same thing yesterday. Was using my self sign up license which expired, but I happened to know that it had expired a few days prior. Agreed that this is not at all obvious, so let's keep this for now.
