### ISSUE TITLE
sql: support setting the transaction isolation level

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#2471]
With our grammar, the syntax is either:

```
BEGIN TRANSACTION ISOLATION LEVEL {SNAPSHOT,SERIALIZABLE}
```

or

```
BEGIN TRANSACTION
SET TRANSACTION ISOLATION LEVEL {SNAPSHOT,SERIALIZABLE}
```

**Comment by vivekmenezes** [comment]
Do you think there is value to also add a priority level like LATENCY_SENSITIVE and BATCH_PROCESS in Beta. These hints can be used by the query scheduler later.

**Comment by petermattis** [comment]
Well, there is no query scheduler component in our system right now, nor one planned for the beta. We do have an internal transaction priority level. It would be straightforward to expose setting that priority level in some manner, but while related to this issue, I think it shouldn't be conflated with it.
