### ISSUE TITLE
distsql: remove the distinction between index join and lookup join during execution

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#24736]
The JoinReader behaves differently depending on whether we are doing an index join or a lookup join (note that #24697 cleaned up most of the complexity of this distinction). There is no reason it should care. We should make it always behave like it currently does for a lookup join and adjust the planning code for index joins. There is even a small potential benefit: instead of re-decoding any needed PKs, we would be able to use the PK values received as input.

This will be an incompatible change though.

**Comment by RaduBerinde** [comment]
CC @pbardea

**Comment by pbardea** [comment]
Related to #24698.

**Comment by RaduBerinde** [comment]
Oh, sorry, didn't realize you filed too. Closing as dup.
