### ISSUE TITLE
builtins: consider adding ULID-based UUID generator

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#24733]
ulid  is a time-based, ordered implementation of UUID generation. See https://github.com/oklog/ulid

Some users have reported smaller data sizes using ulid-derived UUIDs compared to random uuidv4 ids -- potentially due to compression-friendliness of similar keys thanks to being time-based. We potentially could offer a builtin to produce them (though the usual considerations with load distribution time-based keys in some workloads still applies).

**Comment by bdarnell** [comment]
How would this be better than `unique_rowid()` (which is the same idea in 64 bits)?

**Comment by dt** [comment]
I think the primary benefit would just be uuid compatibility -- you can switch generation schemes without switching types.

**Comment by robinbraemer** [comment]
What is the progress on adding ULID?

**Comment by jordanlewis** [comment]
@robinbraemer, we don't have any immediate plans to work on this. However, we do accept contributions! If you're interested in adding a ULID generator builtin, we would be happy to review it.

See `CONTRIBUTING.md` for instructions. Code for builtins goes in `pkg/sql/sem/builtins.go`.

**Comment by SyedMuhammadSufyian** [comment]
@robinbraemer are you working on this issue OR else I would like to work on it ?

**Comment by robinbraemer** [comment]
@SyedMuhammadSufyian No, I haven‘t written any code yet. Thanks for taking your time implementing ULID.

**Comment by SyedMuhammadSufyian** [comment]
@robinbraemer , I am contributing to it.

**Comment by SyedMuhammadSufyian** [comment]
@robinbraemer @jordanlewis How about giving this configuration in the hands of user , to select the uuid generation scheme ?

**Comment by robinbraemer** [comment]
AFAIK, @dt meant ULID will not be a new cockroachdb type but instead an additional choice for the user of how to generate a UUID beside the function ˋgen_random_uuid()ˋ.

As a result an example table could look like this: ˋCREATE TABLE t1 (id UUID PRIMARY KEY DEFAULT gen_ulid(), name STRING);ˋ. Note the id column is still of type UUID but is generated by default using the not yet provided ULID function (not sure if the function name will be used).

**Comment by SyedMuhammadSufyian** [comment]
@robinbraemer I am on it

**Comment by lopezator** [comment]
Any progress with this?
