### ISSUE TITLE
sql: cannot add a JSONB column after upgrading to a 2.0 cluster

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#24748]
After upgrading from a 1.1 cluster to 2.0, but before setting the cluster version, a user can attempt to add a JSONB column. This will fail in a loop in the background. It should instead fail immediately.

**Comment by mjibson** [comment]
The log has:

```
I180412 19:39:56.916302 173 sql/backfill.go:134  [n1] Running backfill for "t", v=3, m=1
W180412 19:39:56.925881 173 sql/schema_changer.go:1146  [n1] Error executing schema change: cluster version does not support JSONB (>= 2.0 required)
```

I've also verified that upgrading the cluster version setting resolves the issue.

**Comment by vivekmenezes** [comment]
```
SET CLUSTER SETTING version = crdb_internal.node_executable_version();
```

to upgrade your cluster after following the instructions in:

https://www.cockroachlabs.com/docs/stable/upgrade-cockroach-version.html

**Comment by knz** [comment]
Arguably the error should be reported to the client immediately, instead of only during the asynchronous processing of the change. If the user does not wish to upgrade immediately, they won't know directly what to do to resolve the errors.
