### ISSUE TITLE
Support pg_catalog.pg_stat_activity

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#24745]
An error pops up in Dbeaver when selecting administer and then sessions:

```SELECT sa.* 
FROM pg_catalog.pg_stat_activity AS sa```

I180409 23:36:18.304008 7381 sql/conn_executor.go:1805  [n1,client=127.0.0.1:58986,user=root] execution error: relation "pg_catalog.pg_stat_activity" does not exist

**Comment by knz** [comment]
@emsal1863 I am assigning this to you as another starter project. Feel free to reach out to me, Bram or @jordanlewis for advice. We aim to make this table exist but it does not need to be populated with meaningful data for now.
