### ISSUE TITLE
Run the Hibernate test suite and capture examples of failed queries 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#24741]
Run the hibernate test suite and capture examples of all the failed queries. We can add them to this issue (https://github.com/cockroachdb/cockroach/issues/16491) as well as track them in our query library.

**Comment by awoods187** [comment]
cc @jordanlewis

**Comment by knz** [comment]
This issue has been addressed - the tests have been run and the results collected in #26657.
