### ISSUE TITLE
sql: support casting arrays to string

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#24746]
No error pops up in Navicat when selecting roles. 

```SELECT fdwname AS name, fdwacl AS acl FROM pg_foreign_data_wrapper WHERE fdwacl::VARCHAR LIKE '%admin%'```

I180409 23:48:05.179837 8072 sql/conn_executor.go:1805  [n1,client=[::1]:59064,user=root] execution error: invalid cast: string[] -> VARCHAR

**Comment by knz** [comment]
For reference in pg:

```
>  select array[1,2,3]::varchar;
  array
---------
 {1,2,3}
```
