### ISSUE TITLE
sql: support CHECK(expr) constraints

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#2474]
A `CHECK` constraint is an expression that is evaluated when a row is inserted or updated and must return `not-FALSE` in order for the check to pass. This enhancement should primarily be a matter of bookkeeping.

**Comment by basukaladagi** [comment]
@petermattis  : Hi Peter, I was interested in contributing to CockroachDB. Please let me know if I can start working on this.
Regards.

**Comment by petermattis** [comment]
@basukaladagi You're welcome to tackle this. Do you need any pointers on where to start?

**Comment by basukaladagi** [comment]
@petermattis  : Yes. Give me some pointers which I can use to navigate through.

**Comment by petermattis** [comment]
@basukaladagi The first step is to hook up semantic actions for `CHECK(expr)` constraints in the grammar. The grammar rules exist, but currently call the `unimplemented()` function. You can see this [here](https://github.com/cockroachdb/cockroach/blob/master/sql/parser/sql.y#L1085) and [here](https://github.com/cockroachdb/cockroach/blob/master/sql/parser/sql.y#L1135).

There are two types of `CHECK` constraints: column-specific and table-level. The column-specific constraint needs to adhere to the [ColumnQualification](https://github.com/cockroachdb/cockroach/blob/master/sql/parser/create.go#L175). The expression for a column-specific `CHECK` constraint must reference that column only. We don't have code to check that condition on expressions (yet), but that's part of the work to do here.

Table-level `CHECK` constraints can only reference columns for the table. See [ConstraintTableDef](https://github.com/cockroachdb/cockroach/blob/master/sql/parser/create.go#L229).

Once you get the semantic actions hooked up you can add test cases to [TestParse](https://github.com/cockroachdb/cockroach/blob/master/sql/parser/parse_test.go#L30).

I think the above is a good bit of work to start on. Get this all working and we can move on to talking about how to store the check expressions in the `TableDescriptor` and how to check them on `INSERT` and `UPDATE`.

**Comment by basukaladagi** [comment]
@petermattis : Thank you so much for the pointers Peter. I will get started on this. Thanks.

**Comment by guanqun** [comment]
@petermattis As @basukaladagi is not working on this, I'd like to take a stab at this issue. One question though, do you prefer several incremental pull requests or a final big pull request? Is it OK to get table column check constraint with some corner cases left as the first PR?

**Comment by petermattis** [comment]
@guanqun Please, go ahead and take this on. I generally prefer smaller PRs. An initial PR that leaves some corner cases unhandled is fine.

**Comment by guanqun** [comment]
Thank you @petermattis I don't have too much free time, but I finally managed to send out a first PR. Please help to review.

**Comment by seiflotfy** [comment]
Should i also support something like
```sql
CREATE TABLE t (
    a INT CHECK (b > 7) DEFAULT 9,
);
```
?

**Comment by petermattis** [comment]
@seiflotfy Well, the table `t` would have to contain a column `b`, but otherwise that should be allowed.

**Comment by seiflotfy** [comment]
My bad i had a different statement and was correcting it. My bad

**Comment by petermattis** [comment]
@seiflotfy Be sure to take a look at the in-progress PR that @guanqun started: #5010.
