### ISSUE TITLE
sql: support vtables information_schema.{routines,parameters}

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#24759]
requested by @awoods187 , Navicat needs this

```sql
FROM information_schema.routines AS r 
LEFT JOIN information_schema.parameters AS p ON r.specific_name = p.specific_name GROUP BY p.specific_name, r.routine_schema, r.routine_name 
ORDER BY r.routine_schema
```

The vtables should be visible to clients (and contain no data initially) even though #17511 is not solved.

**Comment by knz** [comment]
@awoods187 does Navicat fail to run unless this is solved?

**Comment by awoods187** [comment]
Navicat will largely work without this item.

**Comment by rahul4talk** [comment]
Hi @knz @awoods187 I can start working on this..if it's not being worked upon already...

**Comment by knz** [comment]
@rahul4talk feel free! Thank you!

**Comment by emsal1863** [comment]
What's the path to reproducing this issue through the Navicat UI?

**Comment by knz** [comment]
@emsal1863 inspect the stored procedures.

I think you can also check this with PGAdmin
