### ISSUE TITLE
stability: partitioned gossip network caused by ping-ponging of r1's lease

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#24753]
When attempting to make an alpha release all was going fine until I restarted node 1 on adriatic. On node 1 coming up the node status page

```
https://cockroach-adriatic-0003.crdb.io:8080/_status/nodes
```

shows some node status with some nodes reporting

```
 "liveness.epochincrements": 0,
        "liveness.heartbeatfailures": 84,
        "liveness.heartbeatlatency-max": 4718591,
        "liveness.heartbeatlatency-p50": 3145727,
        "liveness.heartbeatlatency-p75": 4194303,
        "liveness.heartbeatlatency-p90": 4194303,
        "liveness.heartbeatlatency-p99": 4718591,
        "liveness.heartbeatlatency-p99.9": 4718591,
        "liveness.heartbeatlatency-p99.99": 4718591,
        "liveness.heartbeatlatency-p99.999": 4718591,
        "liveness.heartbeatsuccesses": 1103,
        "liveness.livenodes": 1,
```

see livenodes=1

and others reporting:

```
 "liveness.epochincrements": 0,
        "liveness.heartbeatfailures": 63,
        "liveness.heartbeatlatency-max": 4980735,
        "liveness.heartbeatlatency-p50": 3407871,
        "liveness.heartbeatlatency-p75": 3538943,
        "liveness.heartbeatlatency-p90": 4063231,
        "liveness.heartbeatlatency-p99": 4980735,
        "liveness.heartbeatlatency-p99.9": 4980735,
        "liveness.heartbeatlatency-p99.99": 4980735,
        "liveness.heartbeatlatency-p99.999": 4980735,
        "liveness.heartbeatsuccesses": 45806,
        "liveness.livenodes": 6,
```

livenodes=6 correctly

I believe the admin UI uses this to report on liveness information

**Comment by a-robinson** [comment]
There's something very weird going on here with gossip. Nodes 1, 2, 3, and 6 don't have `node` or `store` info on nodes 4 and 5 in gossip. And nodes 4 and 5 don't have `node` or `store` info on nodes  1, 2, 3, and 6 in gossip. Node liveness info is being gossiped to all the nodes:

```
# ./cockroach debug gossip-values --certs-dir=certs foo --host=cockroach-adriatic-0001
"cluster-id": f0d036eb-827c-44e9-b3e5-7b19c759ad31
"first-range": r1:/{Min-System/} [(n5,s5):18, (n1,s1):15, (n3,s3):19, next=20]
"liveness:1": {NodeID:1 Epoch:195 Expiration:1523558458.063500141,0 Draining:false Decommissioning:false}
"liveness:2": {NodeID:2 Epoch:126 Expiration:1523558455.193451148,0 Draining:false Decommissioning:false}
"liveness:3": {NodeID:3 Epoch:116 Expiration:1523558455.641398356,0 Draining:false Decommissioning:false}
"liveness:4": {NodeID:4 Epoch:108 Expiration:1523558455.753982688,0 Draining:false Decommissioning:false}
"liveness:5": {NodeID:5 Epoch:140 Expiration:1523558455.593249903,0 Draining:false Decommissioning:false}
"liveness:6": {NodeID:6 Epoch:151 Expiration:1523558458.126363957,0 Draining:false Decommissioning:false}
"node:1": {NodeID:1 Address:{NetworkField:tcp AddressField:cockroach-adriatic-0001:26257} Attrs: Locality: ServerVersion:2.0-3}
"node:2": {NodeID:2 Address:{NetworkField:tcp AddressField:cockroach-adriatic-0002:26257} Attrs: Locality: ServerVersion:2.0-3}
"node:3": {NodeID:3 Address:{NetworkField:tcp AddressField:cockroach-adriatic-0003:26257} Attrs: Locality: ServerVersion:2.0-3}
"node:6": {NodeID:6 Address:{NetworkField:tcp AddressField:cockroach-adriatic-0006:26257} Attrs: Locality: ServerVersion:2.0-3}
"sentinel": f0d036eb-827c-44e9-b3e5-7b19c759ad31
"store:1": {StoreID:1 Attrs: Node:{NodeID:1 Address:{NetworkField:tcp AddressField:cockroach-adriatic-0001:26257} Attrs: Locality: ServerVersion:2.0-3} Capacity:disk (capacity=78 GiB, available=44 GiB, used=21 GiB, logicalBytes=24 GiB), ranges=1607, leases=6, writes=1270.00, bytesPerReplica={p10=0.00 p25=0.00 p50=19331494.00 p75=27926042.00 p90=38394477.00}, writesPerReplica={p10=0.00 p25=0.00 p50=0.60 p75=1.17 p90=1.20}}
"store:2": {StoreID:2 Attrs: Node:{NodeID:2 Address:{NetworkField:tcp AddressField:cockroach-adriatic-0002:26257} Attrs: Locality: ServerVersion:2.0-3} Capacity:disk (capacity=78 GiB, available=52 GiB, used=16 GiB, logicalBytes=19 GiB), ranges=1645, leases=588, writes=1071.23, bytesPerReplica={p10=0.00 p25=0.00 p50=0.00 p75=26411417.00 p90=36689423.00}, writesPerReplica={p10=0.00 p25=0.00 p50=0.00 p75=1.15 p90=1.19}}
"store:3": {StoreID:3 Attrs: Node:{NodeID:3 Address:{NetworkField:tcp AddressField:cockroach-adriatic-0003:26257} Attrs: Locality: ServerVersion:2.0-3} Capacity:disk (capacity=78 GiB, available=56 GiB, used=13 GiB, logicalBytes=15 GiB), ranges=1596, leases=581, writes=1109.94, bytesPerReplica={p10=0.00 p25=0.00 p50=0.00 p75=25455894.00 p90=34026802.00}, writesPerReplica={p10=0.00 p25=0.00 p50=0.00 p75=0.60 p90=1.18}}
"store:6": {StoreID:6 Attrs: Node:{NodeID:6 Address:{NetworkField:tcp AddressField:cockroach-adriatic-0006:26257} Attrs: Locality: ServerVersion:2.0-3} Capacity:disk (capacity=78 GiB, available=46 GiB, used=22 GiB, logicalBytes=26 GiB), ranges=1697, leases=575, writes=1568.93, bytesPerReplica={p10=0.00 p25=0.00 p50=19581573.00 p75=28082041.00 p90=38213679.00}, writesPerReplica={p10=0.00 p25=0.00 p50=0.60 p75=1.17 p90=1.20}}
"system-db": omitted
# ./cockroach debug gossip-values --certs-dir=certs foo --host=cockroach-adriatic-0004
"cluster-id": f0d036eb-827c-44e9-b3e5-7b19c759ad31
"first-range": r1:/{Min-System/} [(n5,s5):18, (n1,s1):15, (n3,s3):19, next=20]
"liveness:1": {NodeID:1 Epoch:197 Expiration:1523564713.013404837,0 Draining:false Decommissioning:false}
"liveness:2": {NodeID:2 Epoch:126 Expiration:1523564714.693427435,0 Draining:false Decommissioning:false}
"liveness:3": {NodeID:3 Epoch:116 Expiration:1523564715.141374736,0 Draining:false Decommissioning:false}
"liveness:4": {NodeID:4 Epoch:108 Expiration:1523564715.255180581,4 Draining:false Decommissioning:false}
"liveness:5": {NodeID:5 Epoch:140 Expiration:1523564715.093342980,0 Draining:false Decommissioning:false}
"liveness:6": {NodeID:6 Epoch:151 Expiration:1523564713.126465632,0 Draining:false Decommissioning:false}
"node:4": {NodeID:4 Address:{NetworkField:tcp AddressField:cockroach-adriatic-0004:26257} Attrs: Locality: ServerVersion:2.0-3}
"node:5": {NodeID:5 Address:{NetworkField:tcp AddressField:cockroach-adriatic-0005:26257} Attrs: Locality: ServerVersion:2.0-3}
"sentinel": f0d036eb-827c-44e9-b3e5-7b19c759ad31
"store:4": {StoreID:4 Attrs: Node:{NodeID:4 Address:{NetworkField:tcp AddressField:cockroach-adriatic-0004:26257} Attrs: Locality: ServerVersion:2.0-3} Capacity:disk (capacity=78 GiB, available=62 GiB, used=6.8 GiB, logicalBytes=7.8 GiB), ranges=1579, leases=645, writes=514.34, bytesPerReplica={p10=0.00 p25=0.00 p50=0.00 p75=0.00 p90=26312819.00}, writesPerReplica={p10=0.00 p25=0.00 p50=0.00 p75=0.00 p90=1.16}}
"store:5": {StoreID:5 Attrs: Node:{NodeID:5 Address:{NetworkField:tcp AddressField:cockroach-adriatic-0005:26257} Attrs: Locality: ServerVersion:2.0-3} Capacity:disk (capacity=78 GiB, available=42 GiB, used=27 GiB, logicalBytes=30 GiB), ranges=1699, leases=692, writes=1731.08, bytesPerReplica={p10=0.00 p25=0.00 p50=25154248.00 p75=29502515.00 p90=39535917.00}, writesPerReplica={p10=0.00 p25=0.00 p50=0.60 p75=1.18 p90=1.20}}
"system-db": omitted
```

**Comment by a-robinson** [comment]
> Node liveness info is being gossiped to all the nodes

Sorry -- I should say it *was* gossiped to all the nodes a while ago. Only nodes 4 and 5 have up-to-date liveness info in their gossip because node 5 is the current leaseholder for the liveness range and the gossip network isn't fully connected. Nodes 4 and 5 are connected to each other but not to any other nodes. Investigating further.

**Comment by a-robinson** [comment]
I haven't yet tracked down how it got into this state, but the cluster appears to have hit a hell of an edge case in gossip that has likely been there for a very long time.

In short, our logic for deciding when to "tighten" the gossip network by reaching out to an additional node only considers reaching out to nodes for which we have a gossiped `node` record. Somehow nodes (1,2,3,6) and (4,5) have separately gotten themselves into a place where they received enough gossip info to get up and running, but not enough to have learned about all the other nodes in the cluster.

**Comment by bdarnell** [comment]
What's supposed to happen here is that the leaseholder for r1 (if any) broadcasts a special gossip key (called the sentinel). Any node which can't receive the sentinel gossip should continually try to reconnect to its `--join` nodes, not just the "tighten" logic you noticed.

**Comment by bdarnell** [comment]
The cluster-id key comes from any replica of r1. The sentinel comes from the leaseholder of r1.

**Comment by a-robinson** [comment]
That's right, thanks.

The lease is indeed ping-ponging around: 

<img width="720" alt="screen shot 2018-04-12 at 5 28 36 pm" src="https://user-images.githubusercontent.com/7085343/38705260-f62e6248-3e76-11e8-9cfc-7502a88d1b93.png">

**Comment by a-robinson** [comment]
So it looks like it's really as simple as that.

* Each node with a replica of r1 attempts to gossip it every 1 minute
* If no replica has an active lease when a node tries to gossip r1, it will acquire the lease
* The lease it acquires only lasts 9 seconds
* We don't proactively renew expiration-based range leases for ranges that aren't actively serving traffic, and apparently nothing else is using r1 in this cluster, so the leases always just expire after 9 seconds
* The 3 replicas just happen to have timed their gossip timer such that they're spaced out enough that there's never an active lease for r1 when any of them want to gossip r1
* The gossiped sentinel key has a TTL of 2 minutes, so it's always renewed on both sides of the "partition" before it expires

**Comment by a-robinson** [comment]
There's a reasonable latency-based argument to be made that we should be actively renewing r1's lease, but that's probably a separate discussion.

**Comment by a-robinson** [comment]
And for the record, the cluster got into this situation in a fairly innocuous way. The gossip network was set up such that n1 was the only thing connecting nodes (2,3,6) with nodes (4,5), then n1 was killed by somebody running `SELECT crdb_internal.force_panic(_);` on it. When n1 came back up, it only connected to the (2,3,6) side of the network.

**Comment by bdarnell** [comment]
Yeah, we should probably be auto-renewing all the expiration-based leases (there are only a few ranges that use them now). Jittering the 1m timer would also ensure we don't get stuck here.

**Comment by garvitjuniwal** [comment]
Even if r1's lease is renewed actively, there is still a possibility that that r1's leaseholder ends up in one half of the cluster which does not have any node that is in the --join flag of the nodes in the other half. What is the expectation on how the --join flag should be configured? What I heard last was that it could be any 3-5 initial nodes in the cluster which allows for many partitions where all join nodes are in one half.  Also, --join flags for a node can become stale after a series of decommissions of the initial nodes.

I'm also wondering why nodes 2,3,6 had no previously gossiped node records for nodes 4,5 while they had liveness records from the past. Given that 2,3,6 knew something about 4,5, they could have tried to tighten the gossip network by trying to talk to them (and vice-versa).

**Comment by bdarnell** [comment]
@garvitjuniwal Which version did you see this on? We think this bug has been present for a long time, but if it's turned up recently for both you and one of our test clusters maybe something changed in 2.0 to make this more likely. 

> What is the expectation on how the --join flag should be configured? What I heard last was that it could be any 3-5 initial nodes in the cluster which allows for many partitions where all join nodes are in one half.

That's still the intention, but as a temporary workaround for this issue you may want to include all the nodes in the join flag. 

> Also, --join flags for a node can become stale after a series of decommissions of the initial nodes.

It's fine if the join flags contain nodes that are no longer part of the cluster (as long as those addresses don't become used for other clusters). While this workaround is required you may want to restart nodes to update their join flags when two or more nodes have been added.

**Comment by a-robinson** [comment]
> That's still the intention, but as a temporary workaround for this issue you may want to include all the nodes in the join flag.

I don't think that would actually help here. The nodes had all the necessary bootstrap addresses, they just all thought they were sufficiently connected and didn't need to try any more of them.

> I'm also wondering why nodes 2,3,6 had no previously gossiped node records for nodes 4,5 while they had liveness records from the past.

Gossip records have TTLs, and node descriptors time out after an hour.

**Comment by tschottdorf** [comment]
Based on a reading of this thread, it seems that the proposed fix is to not let the expiration-based leases expire on this range. Is this correct?

@bdarnell the meta ranges are also expiration-based, and there can be many of them. This seems problematic enough to restrict which ranges this applies to.

**Comment by a-robinson** [comment]
> Based on a reading of this thread, it seems that the proposed fix is to not let the expiration-based leases expire on this range. Is this correct?

Yes.

> @bdarnell the meta ranges are also expiration-based, and there can be many of them. This seems problematic enough to restrict which ranges this applies to.

That was my thinking, but I could certainly be convinced otherwise.

**Comment by bdarnell** [comment]
> the meta ranges are also expiration-based, and there can be many of them.

There can be multiple of them, but they can only ever be a tiny fraction of the cluster size. And I think it's worth keeping leases for them up-to-date to minimize latency variation when we have to do range lookups.

**Comment by garvitjuniwal** [comment]
> In short, our logic for deciding when to "tighten" the gossip network by reaching out to an additional node only considers reaching out to nodes for which we have a gossiped node record.

> What's supposed to happen here is that the leaseholder for r1 (if any) broadcasts a special gossip key (called the sentinel). Any node which can't receive the sentinel gossip should continually try to reconnect to its --join nodes, not just the "tighten" logic you noticed.

Ok, to clear up my understanding. A node will first decide whether it already connected enough to the rest of the cluster (is this only based on being able to see the sentinel key?) Only if it needs to, it will try to connect to nodes in its --join flag, and it will also try to connect to nodes that it has persisted on disk from past gossips (is this called the local gossip infostore?). I'm assuming this is different from the currently gossiped node descriptors and would help in case nodes in --join flag have already been removed from the cluster. Do these persisted records ever expire?

> @garvitjuniwal Which version did you see this on? We think this bug has been present for a long time, but if it's turned up recently for both you and one of our test clusters maybe something changed in 2.0 to make this more likely.

I saw this on 1.2-alpha from 2017/12/04.

> I don't think that would actually help here. The nodes had all the necessary bootstrap addresses, they just all thought they were sufficiently connected and didn't need to try any more of them.

Is there another workaround for a cluster that has gotten into this state? Is there a way to manually send traffic to range 1 so that its leaseholder becomes sticky?

**Comment by garvitjuniwal** [comment]
> It's fine if the join flags contain nodes that are no longer part of the cluster (as long as those addresses don't become used for other clusters).

What is the worst that can happen if those nodes became a part of another cluster? Whatever it is, I'm fairly sure would not apply if you are using secured clusters, right?
