### ISSUE TITLE
ui: Mismatched database size

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#24769]
**Bug report**

After starting ycsb against a 5-node local cluster running 2.0, the database size is different on the Databases overview and `usertable`-specific pages.  To reproduce, just follow the steps on https://www.cockroachlabs.com/docs/stable/training/fault-tolerance-and-automated-repair.html.

```
~/cockroachdb-training$ grep -F '[config]' node1/logs/cockroach.log
I180413 08:19:58.241060 1 util/log/clog.go:1104  [config] file created at: 2018/04/13 08:19:58
I180413 08:19:58.241060 1 util/log/clog.go:1104  [config] running on machine: JESSEs-MacBook-Pro
I180413 08:19:58.241060 1 util/log/clog.go:1104  [config] binary: CockroachDB CCL v2.0.0 (x86_64-apple-darwin13, built 2018/04/03 20:52:33, go1.10)
I180413 08:19:58.241060 1 util/log/clog.go:1104  [config] arguments: [./cockroach start --insecure --store=node1 --host=localhost --port=26257 --http-port=8080 --join=localhost:26257,localhost:26258,localhost:26259]
```

![image](https://user-images.githubusercontent.com/15893490/38725531-9b3aead2-3ed5-11e8-9e17-6c1f82144d1f.png)

![image](https://user-images.githubusercontent.com/15893490/38725536-a1c9d25a-3ed5-11e8-874b-258c27cae6ce.png)

**Comment by jordanlewis** [comment]
Closing due to age
