### ISSUE TITLE
cli/sql: `cockroach sql` fails to save command history if exited with ^C

### ISSUE THREAD

**Issue by erichocean** [cockroachdb/cockroach#24766]
This is a "should have" feature. It's very frustrating working with the sql client and then having to use ^C because it has hung on some query, only to lose your entire working history when you restart it.

**Comment by knz** [comment]
@erichocean which version are you using? We have fixed numerous history-related bugs in 2.0. I just tested with a 2.0 client and I believe the history is properly saved. Could you help us reproduce the problem?

**Comment by erichocean** [comment]
I'm on the public 2.0 release. I can reliably reproduce this behavior.

**Comment by erichocean** [comment]
I get this error: `W180413 22:44:23.478108 1 cli/sql.go:214  cannot save command-line history: write_history: illegal byte sequence`

**Comment by knz** [comment]
@erichocean This is a sign there is an invalid UTF-8 sequence in the history. That's why it cannot be saved. I would recommend opening the file `~/.cockroachsql_history` in a text editor and check visually for invalid characters, especially at the end.

**Comment by knz** [comment]
Closing as non-actionable -- the history is saved upon Ctrl+C.
