### ISSUE TITLE
build,storage: cockroach fails to compile in Fedora / GCC 8.01 due to error in RocksDB

### ISSUE THREAD

**Issue by itamarjp** [cockroachdb/cockroach#24761]
the issue is actually in rocksdb, I reported the bug in upstream,  but affects cockroach too.

https://github.com/facebook/rocksdb/issues/3716

**Comment by knz** [comment]
Thanks for your report!

**Comment by itamarjp** [comment]
full build log with the failure, here ->

https://koji.fedoraproject.org/koji/taskinfo?taskID=26351599

**Comment by itamarjp** [comment]
rocksdb fixed it, https://github.com/facebook/rocksdb/pull/3736

can you update the rocksdb code here ?

**Comment by knz** [comment]
cc @petermattis @benesch for triage

**Comment by benesch** [comment]
Upgrading RocksDB is always treacherous. We'll look into upgrading when the fix makes it into an upstream release, presumably in v5.13, but that likely won't be for a month or two.

Thanks for fixing this in RocksDB, though! Looks like the original attempt in https://github.com/facebook/rocksdb/pull/3433 got waylaid.

**Comment by namibj** [comment]
I'm currently trying to build cockroach with native tuning for Goldmont (current Intel atom), and native tuning for this CPU only made it in to GCC via this (not yet merged) patch: https://www.mail-archive.com/gcc-patches@gcc.gnu.org/msg188184.html
The issue there is, that this patch only seems to work on gcc-mirror/gcc@772a9876020a8b0bef413d512a2147ef6f9953b7, which did not even make it into GCC 8. It seems to work though.
Could someone help me figure out where I'd even need to look for how to fix this? I'd really like to see nice numbers about the performance on this platform, as the nodes seem to be available for rather cheap.

Also, did you ever try to enable more agressive tuning with gccgo? I can't find any artefacts in the repo, but that dowsn't mean much...

**Comment by knz** [comment]
Although we have had some success building CockroachDB with previous versions of gccgo, the performance of the resulting binary was abysmal. We have reasons to believe that GCC 8.1 will  improve this, but we have not tried it yet.
