### ISSUE TITLE
ui: unresponsive after running for some time

### ISSUE THREAD

**Issue by viniciusmiguel** [cockroachdb/cockroach#24775]
CRDB2.0 Running on Linux

Tested on Chrome running on Windows Server 2012.

After some time with the UI opened it gets totally unresponsive, being necessary make a reload (F5).
It happens especially when I left the UI opened from one day to another.

**Comment by vilterp** [comment]
Thanks for the report. I think most devs here don't ever have the UI open for that long, so we may have missed this. Will try to repro.
