### ISSUE TITLE
ui: Node 5 should not appear in tool tip

### ISSUE THREAD

**Issue by james-weitzman** [cockroachdb/cockroach#24787]
Is this a question, feature request, or bug report?

Bug report

<img width="1238" alt="screen shot 2018-04-13 at 1 50 03 pm" src="https://user-images.githubusercontent.com/36422215/38750058-b9f2e85c-3f21-11e8-81de-ee5436e6e664.png">

**BUG REPORT**

1. Please supply the header (i.e. the first few lines) of your most recent
   log file **for each node in your cluster**. On most unix-based systems
   running with defaults, this boils down to the output of

     grep -F '[config]' cockroach-data/logs/cockroach.log

   When log files are not available, supply the output of `cockroach version`
   and all flags/environment variables passed to `cockroach start` instead.

2. Please describe the issue you observed:

- What did you do?

- What did you expect to see?

- What did you see instead?

**Comment by vilterp** [comment]
Hey @james-weitzman, did you kill or decommission node 5 before taking this screenshot? (I assume this was going through the steps in training, but which step in particular were you at at this point?)

**Comment by james-weitzman** [comment]
Hey @vilterp, I did kill node 5 before taking the screenshot - @benesch & I found this bug during training. I believe it was here: https://www.cockroachlabs.com/docs/stable/training/fault-tolerance-and-automated-repair.html (but could be wrong)

**Comment by vilterp** [comment]
Ok, I think this is a dup of #23480. @couchand can confirm.
