### ISSUE TITLE
distsqlrun: limitHint logic in tableReader doesn't make sense when tableReader is used as a RowSource

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#24786]
We have some really hilarious code that tries to fill a `RowChannel` that doesn't (ever?) make sense any more when the `TableReader` is used as a `RowSource` rather than it pushing results downstream.
https://github.com/cockroachdb/cockroach/blob/c5b72972d4515e2be98223fc4af2e4e90591dcda/pkg/sql/distsqlrun/readerbase.go#L37

I think this code is a particular problem now that we use a single `TableReader` for limit queries, which reads across ranges. I'm not completely sure when limit hints are used, but I think it is possible to have one of these singleton `TableReaders` with a limit hint, right?

cc @RaduBerinde @abhimadan

**Comment by andreimatei** [comment]
passing on to... @jordanlewis

**Comment by jordanlewis** [comment]
This is an issue with the comment more than the code, right?

**Comment by andreimatei** [comment]
The code. I think nothing about that `rowChannelBufSize` makes sense when the TableReader is being pulled from.

**Comment by RaduBerinde** [comment]
This code is gone now.
