### ISSUE TITLE
An issue about the correctness of a dependency (arenaskl)

### ISSUE THREAD

**Issue by 0joshuaolson1** [cockroachdb/cockroach#24782]
Possible dependency issue: https://github.com/andy-kimball/arenaskl/issues/3

Where it's used: https://github.com/cockroachdb/cockroach/blob/master/pkg/storage/tscache/interval_skl.go#L27

Permalink: https://github.com/cockroachdb/cockroach/blob/374be5beb91d64cdbc82a706b3a153f0d4ae77bb/pkg/storage/tscache/interval_skl.go#L27

**Comment by nvanbenschoten** [comment]
@0joshuaolson1 thanks for opening this issue. It's always hard to monitor the health of all dependencies in a large project, so we really appreciate you following through with a suspected bug and informing us of it!
