### ISSUE TITLE
ui: Make doc links in node map onboarding open in a new tab 

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#24780]
In the 2.0 node map, the links to docs should open in a new tab so you don't lose the admin ui.

**Comment by couchand** [comment]
Maybe.  My preference is generally to let the user open links in a new tab if they wish, but not force it, though I can see it making sense here.

**Comment by jseldess** [comment]
I also prefer to let the user choose in most cases, but in this specific case, it's seems very unlikely that a user would ever want to lose/close the admin ui.
