### ISSUE TITLE
docs: How do we setup the Disaster Recovery over Multi Datacenter cluster in Cockroach DB?

### ISSUE THREAD

**Issue by vivinjoy** [cockroachdb/cockroach#24791]
Consider we have a separate Datacenter to fallback as part of Disaster Recovery. How do we setup Cockroach DB cluster for this? I believe adding the DR Datacenter instances as part of the same cluster would allow data to be sharded across the DR server instances too, which is not ideal.

I know that we can always do Backup/Restore. But is there a better way?

**Comment by danhhz** [comment]
Hi @vivinjoy. CockroachDB is designed to survive disasters without sacrificing availability or consistency. If your cluster has nodes in 3 datacenters (and the [localities](https://www.cockroachlabs.com/docs/stable/start-a-node.html#locality) are set), then CockroachDB will survive losing a datacenter. Ditto for "regions" or "availability zones" if you're based in the cloud.

**Comment by a-robinson** [comment]
Is there anything to be done here? I'm closing, but feel free to reopen if there are additional questions or requests.
