### ISSUE TITLE
distsqlrun: routers should push synchronously

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#24805]
Today, `router.Push(row)` synchronously decides the proper output for the row,  deposits that row into a buffer for that proper output, signals the router goroutine that something happened, and then finishes.

Separately, the router goroutine is waking up when signaled, grabbing chunks of rows from those output buffers, and calling `Push` on their corresponding output `RowChannel`.

The overhead of the synchronization here is very high. I think that removing it entirely would provide a large performance boost for the routers. Specifically, `router.Push` should directly `Push` to the correct output `RowChannel`. The router's own goroutine can be removed at this point, along with the router's `n` internal buffers.

We should be careful to make sure that doing this doesn't remove any packet coalescing that might occur due to the fact that the router's goroutine takes rows from the router's buffers in chunks. I think that `RowChannel` does this same optimization internally, though, so I think it will be okay.

**Comment by jordanlewis** [comment]
Er, `RowChannel` doesn't do that internally, but `outbox` does.

**Comment by jordanlewis** [comment]
Very early experiments show a ~5x improvement with this strategy but I'm going to leave this alone for now.

**Comment by petermattis** [comment]
Per offline comments, the current structure is due to #17097. See also #22444 and #20568.

**Comment by jordanlewis** [comment]
Turns out that this isn't a good idea for the reasons outlined in the linked issues.
