### ISSUE TITLE
roachtest: test locality awareness

### ISSUE THREAD

**Issue by garvitjuniwal** [cockroachdb/cockroach#24818]
Cockroach uses the `--locality` flag as a factor in replica placement. The general idea is that replicas of a range should have high locality diversity, one advantage of which is that a cluster can tolerate complete locality failures. We should test the following:

- Setup an 8 node cluster with 4 localities, 2 nodes in each. The cluster should use the default 3-way replication.
- Run some load on this cluster that creates data. 
- Verify using crdb_internal.ranges that replicas are always placed in different localities. This might be redundant because the next step anyway tests failure tolerance. But it is nice to be thorough.
- Fail 2 nodes in one locality permanently, at the same time.
- Verify that all data created above is readable.
- Wait a while and ensure that all ranges reach full replication, while still maintaining diversity across the 3 live localities.

Note that we need to start with 4 localities. It might appear that 3 localities should be enough to allow for locality failure tolerance, but there could be cases where a rebalance operation causes a range to be in a transient state of having 4 replicas, 2 of which would be in the same locality. And we would lose quorum on that range if 2 out of 4 replicas died.

Locality information is used as a hint rather than a hard constraint. Cockroach will put two replicas in the same locality, if necessary for full replication. To test this, follow up the above test with:

- Fill up the stores on 2 nodes in one live locality to 99%.
- Run some load to make sure more data can be written, without driving the close-to-full nodes off the cliff.
- Wait a while and ensure that some replicas have been moved from the full locality to other localities to free up some disk space.

We also want to verify that Cockroach will rebalance replicas appropriately if localities change.

- Restart all 8 nodes after swizzling `--locality` flags around. 
- Ensure that all ranges are rebalanced to comply with the new locality information.

**Comment by tschottdorf** [comment]
@a-robinson do we test something like that anywhere?

**Comment by a-robinson** [comment]
The unit tests in allocator_test.go and allocator_scorer_test.go cover the first and third scenarios quite well, albeit not in an end-to-end environment.

On the other hand, while we do have some unit tests regarding full disks, the second scenario is not sufficiently tested anywhere.

**Comment by tschottdorf** [comment]
https://github.com/cockroachdb/cockroach/issues/7882 covers out-of-disk scenarios. The specialty here is that we'd want to make sure that localities are ignored when the node runs out of disk, right?

I'm considering folding this into https://github.com/cockroachdb/cockroach/issues/7882 as well. WDYT?

**Comment by a-robinson** [comment]
I think this is specific enough (how rebalancing with multiple localities behaves in the presence of full disks) that it's fine keeping open separately. It's not a top priority on my end right now, though.
