### ISSUE TITLE
engine: implementation of unused RocksDB API 

### ISSUE THREAD

**Issue by yaojingguo** [cockroachdb/cockroach#24822]
[slice_transform.h](https://github.com/cockroachdb/rocksdb/blob/0edac964ca804c97c69ef18123b5e82d1b57e19e/include/rocksdb/slice_transform.h#L61) says:
``` cpp
// This is currently not used and remains here for backward compatibility.
  virtual bool InRange(const Slice& dst) const { return false; }
```
So I think that the following code in [options.cc](https://github.com/cockroachdb/cockroach/blob/master/c-deps/libroach/options.cc#L44) should be removed:

```cpp
virtual bool InRange(const rocksdb::Slice& dst) const { return Transform(dst) == dst; }
```

**Comment by petermattis** [comment]
I agree that this looks like detritus.

**Comment by petermattis** [comment]
@yaojingguo Yes. Thank you.
