### ISSUE TITLE
LIKE operator does not work correctly with backslashes

### ISSUE THREAD

**Issue by jakob** [cockroachdb/cockroach#24828]
**BUG REPORT**

1. Please supply the header (i.e. the first few lines) of your most recent
   log file **for each node in your cluster**.

```
I180416 15:32:50.076987 1 util/log/clog.go:1104  [config] file created at: 2018/04/16 15:32:50
I180416 15:32:50.076987 1 util/log/clog.go:1104  [config] running on machine: Kleines-Macbook
I180416 15:32:50.076987 1 util/log/clog.go:1104  [config] binary: CockroachDB CCL v2.0.0 (x86_64-apple-darwin13, built 2018/04/03 20:52:33, go1.10)
I180416 15:32:50.076987 1 util/log/clog.go:1104  [config] arguments: [./cockroach start --host localhost --insecure]
```

2. Please describe the issue you observed:

- What did you do?

`select '\' like '\\%', '\' like '%\\', '\' like '%\\%';`

- What did you expect to see?

```
 e'\\' LIKE e'\\\\%' | e'\\' LIKE e'%\\\\' | e'\\' LIKE e'%\\\\%' 
---------------------+---------------------+----------------------
 t                   | t                   | t
(1 row)
```
- What did you see instead?

```
 e'\\' LIKE e'\\\\%' | e'\\' LIKE e'%\\\\' | e'\\' LIKE e'%\\\\%' 
---------------------+---------------------+----------------------
 t                   | t                   | f
(1 row)

```

**Comment by danhhz** [comment]
@nvanbenschoten your name is most of the git blame for the LIKE impl. Can you triage this?

**Comment by nvanbenschoten** [comment]
@windchan7 want to take a look at this? This was recently re-written in https://github.com/cockroachdb/cockroach/pull/20600 and there's a chance something was missed.
