### ISSUE TITLE
sql: Golang GORM not creating the db.

### ISSUE THREAD

**Issue by koalalorenzo** [cockroachdb/cockroach#24838]
**BUG REPORT**
- What did you do?
I have decided to migrate from postgresql to cockroachdb, as according to the documentation (https://www.cockroachlabs.com/docs/stable/build-a-go-app-with-cockroachdb-gorm.html) it should be compatible.

As there is an issue open https://github.com/jinzhu/gorm/issues/740 since 2015, and as there is a PR that was closed to have some support from CockroachDB, I guess that this needs some work on.

- What did you expect to see?
I was expecting all my tests to pass. This is creating the database, the tables and testing some orations over the Structs.

- What did you see instead?
a basic `db.AutoMigrate(profile)` is causing:
```
pq: invalid target name: "profiles"
```
And there is no SQL logged when I do `db.LogMode(true)`

I see errors coming from basic queries like:

```
[2018-04-16 18:05:05]  [1.83ms]  SELECT * FROM "profiles"  WHERE ("id" = 'testuser') LIMIT 1
[2018-04-16 18:05:05]  pq: relation "profiles" does not exist
```
(which I guess it is caused by the database and table not being there)

The struct is pretty basic and has no tag (I deleted them thinking that those were breaking things)

**Comment by danhhz** [comment]
@jordanlewis can you triage this please?

**Comment by koalalorenzo** [comment]
Do we have an ETA for this?

**Comment by jordanlewis** [comment]
Hi @koalalorenzo, sorry for the delay. Perhaps the gorm automigration feature is not working - I'm not familiar with it. If you create your schema first, that will likely work.

Could you please try your app again, but capture the logs from CockroachDB with the flag `--vmodule=conn_executor=2` enabled? Thanks!

**Comment by jordanlewis** [comment]
Hey @koalalorenzo, sorry for the long delay, but the problem here is that the database hadn't been created ahead of time. GORM can create tables just fine, but not databases - you need to do that ahead of time yourself, just like you would in PostgreSQL.
