### ISSUE TITLE
sql: support CREATE TABLE ... AS ...?

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#2483]
Support for `CREATE TABLE ... AS ...` was removed from the grammar in #2479, but it could be easily resurrected. The actual implementation would not be terribly difficult, though it might depend on supporting tables without primary keys (see #2081). 

From a comment in #2479:

> @jusongchen writes:
> CREATE TABLE ... AS is a very useful feature. Without this feature,an end user cannot easily store a query result as a intermediate table. This feature is very useful when it comes to ad-hoc data analysis and it is widely supported by most RDBMS vendors.

**Comment by WillHaack** [comment]
https://github.com/cockroachdb/cockroach/pull/8802

**Comment by knz** [comment]
Closed by #8802.
