### ISSUE TITLE
sql: each database has an empty range

### ISSUE THREAD

**Issue by vilterp** [cockroachdb/cockroach#24847]
*Repro:*

- `select * from crdb_internal.ranges`; see what ranges exist
- Create a database
- `select * from crdb_internal.ranges` again

*Expected:*

I don't see a new range until I create tables in the database.

*Actual:*

See a new range with the descriptor id of the database (can verify that it's the database descriptor id by creating some tables and seeing that it's their parent id).

Is there a good reason for creating an empty range for each database, or is this an oversight?

Only user impact is a tiny bit of overhead, and some confusion about range counts not adding up (see #24767)

**Comment by bdarnell** [comment]
The code that automatically splits at ID boundaries doesn't know whether those IDs belong to tables or databases, so it just splits everything (up to the highest known ID). The extra range per database is not ideal but is probably not worth the extra complexity to prevent.

**Comment by vilterp** [comment]
Okey doke. Where is the splitting code btw? Haven't been able to track it down in the past.

Closing since we're not gonna change this.

**Comment by bdarnell** [comment]
https://github.com/cockroachdb/cockroach/blob/eb569ba0c91099a0c8ab5890691383c692d58dbe/pkg/config/system.go#L238-L246

**Comment by vilterp** [comment]
Closed for real by #30981
