### ISSUE TITLE
build: make check improvements

### ISSUE THREAD

**Issue by jgautheron** [cockroachdb/cockroach#2485]
How about adding the following automated checks in the `make check`:
- [ ] ~~[deadcode](https://github.com/remyoudompheng/go-misc/tree/master/deadcode)~~ (dead project)
- [ ] [gocyclo](https://github.com/fzipp/gocyclo) (https://github.com/fzipp/gocyclo/pull/11)
- [x] ~~[defercheck](https://github.com/opennota/check)~~ (https://github.com/opennota/check/commit/aa37591a11986c7dd6ce70640271a752b37b0ea2)
- [ ] [structcheck](https://github.com/opennota/check) (https://github.com/opennota/check/issues/11)
- [x] [varcheck](https://github.com/opennota/check)
- [x] [errcheck](https://github.com/kisielk/errcheck)
- [x] [dupl](https://github.com/mibk/dupl)
- [ ] [goconst](https://github.com/jgautheron/goconst) (produces little value: https://github.com/jgautheron/goconst/issues/1)
- [x] [safesql](https://github.com/stripe/safesql) (cli code is unsafe, but safesql doesn't catch it)
- [x] [unused](https://github.com/dominikh/go-unused)
- ~~[usedexports](https://github.com/jgautheron/usedexports) (lots of false positives)~~ superceded by unused
- [ ] [interfacer](https://github.com/mvdan/interfacer) (produces little value)

**Comment by tamird** [comment]
Sure. We are already using `varcheck` and `errcheck`. I've tried adding the others at various times but have found them to be [buggy](https://github.com/opennota/check/issues/created_by/tamird). Pull requests are, of course, welcome.

**Comment by jgautheron** [comment]
Alright, I'll see what I can do.

**Comment by tamird** [comment]
Update on this:
- we're already using varcheck and errcheck
- deadcode doesn't do anything and isn't maintained (running it on cockroach results in no output afaict)
- gocyclo isn't useful until https://github.com/fzipp/gocyclo/issues/9 is solved
- `structcheck` isn't useful until https://github.com/opennota/check/issues/11 is solved
- `defercheck` seems not useful in general (at least, we have no violations now, and any future ones are trivial to notice visually)
- `dupl` produces a huge number of false positives. It is added to the Makefile in #3131, but not enforced

I'm going to close this issue, since there's no action to be taken here until some upstream changes are made. If you'd like to follow up on #3131 and try to reduce some duplication, that would of course be quite welcome.

**Comment by tamird** [comment]
Quick addendum, `defercheck` now produces false positives against us. See https://github.com/opennota/check/issues/22 and https://github.com/opennota/check/issues/23

**Comment by jgautheron** [comment]
@tamird this one might prove useful as well: https://github.com/mvdan/interfacer

**Comment by tschottdorf** [comment]
I ran this against our code a couple of days ago, but it didn't turn up
with anything interesting (4 items, all correct but still nothing that made
me want to change code - mostly turning things to `fmt.Stringer`).

**Comment by jgautheron** [comment]
I wrote yesterday a tool that could of some help to you, it's called [goconst](https://github.com/jgautheron/goconst).
It finds repeated strings that could be replaced by a constant.

**Comment by tamird** [comment]
Sure, added. Reopening.

**Comment by jgautheron** [comment]
As expected it doesn't return much (`-min-occurrences 3`).

```
10 occurrences of ", " found:
	/Users/jonathangautheron/workspace/src/github.com/cockroachdb/cockroach/gossip/infostore.go:89:13
	/Users/jonathangautheron/workspace/src/github.com/cockroachdb/cockroach/sql/parser/update.go:51:12
	/Users/jonathangautheron/workspace/src/github.com/cockroachdb/cockroach/sql/parser/select.go:89:12
	/Users/jonathangautheron/workspace/src/github.com/cockroachdb/cockroach/sql/parser/select.go:128:12
	/Users/jonathangautheron/workspace/src/github.com/cockroachdb/cockroach/sql/parser/select.go:265:12
	/Users/jonathangautheron/workspace/src/github.com/cockroachdb/cockroach/sql/parser/select.go:278:12
	/Users/jonathangautheron/workspace/src/github.com/cockroachdb/cockroach/sql/parser/create.go:97:12
	/Users/jonathangautheron/workspace/src/github.com/cockroachdb/cockroach/sql/parser/alter_table.go:50:12
	/Users/jonathangautheron/workspace/src/github.com/cockroachdb/cockroach/sql/parser/values.go:39:12
	/Users/jonathangautheron/workspace/src/github.com/cockroachdb/cockroach/sql/parser/expr.go:499:12
3 occurrences of "NULL" found:
	/Users/jonathangautheron/workspace/src/github.com/cockroachdb/cockroach/sql/driver/wire.go:99:10
	/Users/jonathangautheron/workspace/src/github.com/cockroachdb/cockroach/sql/parser/eval.go:523:9
	/Users/jonathangautheron/workspace/src/github.com/cockroachdb/cockroach/sql/parser/eval.go:550:9
8 occurrences of "tcp" found:
	/Users/jonathangautheron/workspace/src/github.com/cockroachdb/cockroach/gossip/resolver/node_lookup.go:116:16
	/Users/jonathangautheron/workspace/src/github.com/cockroachdb/cockroach/gossip/resolver/resolver.go:59:9
	/Users/jonathangautheron/workspace/src/github.com/cockroachdb/cockroach/gossip/resolver/resolver.go:94:7
	/Users/jonathangautheron/workspace/src/github.com/cockroachdb/cockroach/gossip/resolver/socket.go:51:7
	/Users/jonathangautheron/workspace/src/github.com/cockroachdb/cockroach/gossip/resolver/socket.go:56:16
	/Users/jonathangautheron/workspace/src/github.com/cockroachdb/cockroach/rpc/server.go:288:7
	/Users/jonathangautheron/workspace/src/github.com/cockroachdb/cockroach/util/unresolved_addr.go:47:7
	/Users/jonathangautheron/workspace/src/github.com/cockroachdb/cockroach/util/testing.go:96:7
7 occurrences of "unix" found:
	/Users/jonathangautheron/workspace/src/github.com/cockroachdb/cockroach/gossip/resolver/resolver.go:80:12
	/Users/jonathangautheron/workspace/src/github.com/cockroachdb/cockroach/gossip/resolver/resolver.go:94:14
	/Users/jonathangautheron/workspace/src/github.com/cockroachdb/cockroach/gossip/resolver/socket.go:44:7
	/Users/jonathangautheron/workspace/src/github.com/cockroachdb/cockroach/rpc/server.go:312:7
	/Users/jonathangautheron/workspace/src/github.com/cockroachdb/cockroach/rpc/tls.go:44:17
	/Users/jonathangautheron/workspace/src/github.com/cockroachdb/cockroach/util/unresolved_addr.go:51:7
	/Users/jonathangautheron/workspace/src/github.com/cockroachdb/cockroach/util/testing.go:102:7
```

**Comment by jgautheron** [comment]
Another tool I wrote, [usedexports](https://github.com/jgautheron/usedexports) doesn't return much as well.

```
cockroachdb/cockroach/gossip/simulation/network.go:116:1 func "GetNodeFromAddr" is exported but not used locally
cockroachdb/cockroach/gossip/simulation/network.go:169:1 func "Stop" is exported but not used locally
cockroachdb/cockroach/gossip/simulation/network.go:176:1 func "RunUntilFullyConnected" is exported but not used locally
cockroachdb/cockroach/gossip/simulation/network.go:127:1 func "GetNodeFromID" is exported but not used locally
cockroachdb/cockroach/gossip/simulation/network.go:150:1 func "SimulateNetwork" is exported but not used locally
cockroachdb/cockroach/gossip/simulation/network.go:38:6 type "Node" is exported but not used locally
cockroachdb/cockroach/examples/kv_bank/main.go:48:6 type "Bank" is exported but not used locally
cockroachdb/cockroach/examples/kv_bank/main.go:58:6 type "Account" is exported but not used locally
```

Apart from the `example`, I'm guessing that the `network` exported methods are part of a public API?

**Comment by petermattis** [comment]
I'm not finding these suggestions very compelling. And it looks like you've got an out of date version of the cockroach source code.

**Comment by jgautheron** [comment]
Agreed.
Updated my results above with the latest version.

**Comment by bdarnell** [comment]
Another one to consider: [safesql](https://github.com/stripe/safesql). This enforces that all arguments to `sql.DB.Query` and similar functions are string literals (instead of e.g. the result of `Sprintf`) to guard against SQL injection (and enforce correct use of placeholders). We couldn't enforce this right now because of limitations in our placeholder parsing, but once we fix these issues we may want to use this checker to ensure that we're doing things the right way.

**Comment by tamird** [comment]
I tried `safesql`:
```
safesql .
Found 1 potentially unsafe SQL statements:
- /Users/tamird/src/go/src/github.com/cockroachdb/cockroach/cli/sql_util.go:79:23
Please ensure that all SQL queries you use are compile-time constants.
You should always use parameterized queries or prepared statements
instead of building queries from strings.
```
So long as we have a SQL shell, we won't be able to fix that.

**Comment by bdarnell** [comment]
Yeah, we'll need some way to mark exceptions (safesql is also currently incompatible with common bulk-insert patterns), but I still think it would be worth doing at some point.

**Comment by tamird** [comment]
Looks like some of our linters are misbehaving: https://goreportcard.com/report/github.com/cockroachdb/cockroach

**Comment by mvdan** [comment]
> I ran this against our code a couple of days ago, but it didn't turn up with anything interesting (4 items, all correct but still nothing that made me want to change code - mostly turning things to `fmt.Stringer`).

@tschottdorf I've been thinking of ways to avoid such "false positives" in interfacer, although as you say they are still correct. It's more like they are technically correct, but in practice they make little sense.

I haven't figured out a clean way to get rid of them, though. I could blacklist `fmt.Stringer`, but that doesn't really solve the problem. I can't wrap my head around what makes cases like these special.

I've had a quick look at the warnings on your code, and filed this issue which should remove quite a few: https://github.com/mvdan/interfacer/issues/17

If you have more ideas, let me know :)

**Comment by nvanbenschoten** [comment]
I just stumbled upon https://github.com/dominikh/go-unused, which checks for unused identifiers (constants, variables, functions, and types). Might be worth adding it to the verification suite, although I'm not sure a no-tolerance policy for unused identifiers is a very good idea.

**Comment by tamird** [comment]
pretty sure @petermattis beat you to it
https://github.com/cockroachdb/cockroach/pull/5256

**Comment by jordanlewis** [comment]
Seems like this is ready for closing. Let's create new issues for individual checks we want to add going forward.
