### ISSUE TITLE
storage: can a Snapshot remove the Raft HardState permanently?

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#24854]
[`replica.applySnapshot`](https://github.com/cockroachdb/cockroach/blob/220b62e3e4a7d076f197a1d6df973e748c4e75c4/pkg/storage/replica_raftstorage.go#L673) claims that the HardState parameter it takes:

> may be empty, as Raft may apply some snapshots which don't require an update to the HardState

If this is truly the case then I'm having trouble convincing myself that we don't have a bug. `applySnapshot` first [deletes all](https://github.com/cockroachdb/cockroach/blob/220b62e3e4a7d076f197a1d6df973e748c4e75c4/pkg/storage/replica_raftstorage.go#L764) replicated and unreplicated keys. It then [writes the HardState](https://github.com/cockroachdb/cockroach/blob/220b62e3e4a7d076f197a1d6df973e748c4e75c4/pkg/storage/replica_raftstorage.go#L844), **but only if the HardState provided by Raft is not empty**. How does this work if the HardState provided by Raft is empty? I can't see (and my own testing hasn't found) how a HardState would be written, so it looks like we'll end up with a range without a HardState. This seems really bad, and basic testing has shown that it can lead to [this assertion](https://github.com/coreos/etcd/blob/ff6ff9d6e6b32b7a0d0f10b19fd18463e331e901/raft/log.go#L202) firing (`applied(%d) is out of range`, not `tocommit(%d) is out of range`).

The solution to this, if I'm not missing anything, would be to save the HardState before we clear it and write this old HardState again after the `clearRange` if Raft doesn't provide a new one. However, I'm not even convinced it's possible to raft to provide an empty HardState. This is because [this check](https://github.com/coreos/etcd/blob/ff6ff9d6e6b32b7a0d0f10b19fd18463e331e901/raft/raft.go#L1262) look like it should prevent a snapshot that doesn't also increase the `commit` index. I added in an assertion to test this and our entire test suite passes without it firing.

I ran into this question while performing some nearby refactoring. I began digging into the git history before finding that there's been a [long](https://github.com/cockroachdb/cockroach/pull/7598) [history](https://github.com/cockroachdb/cockroach/pull/7833) around this so I'd like to get input from those who are more knowledgeable about it before trying to make any changes myself.

cc. @bdarnell (who I already spoke to) @tschottdorf @petermattis

**Comment by tschottdorf** [comment]
Looks like we dodged a bullet? I agree that it looks like we're handling the empty HardState incorrectly and that Raft wouldn't ask us to apply such a snapshot. I'm pretty sure that when I wrote [this comment](https://github.com/cockroachdb/cockroach/blame/220b62e3e4a7d076f197a1d6df973e748c4e75c4/pkg/storage/replica_raftstorage.go#L844) I was only afraid that Raft might emit such a HardState, but not sure that it could.

What do you suggest we do? Just reject snapshots with an empty HardState as they shouldn't exist?

**Comment by nvanbenschoten** [comment]
> What do you suggest we do? Just reject snapshots with an empty HardState as they shouldn't exist?

Yes, that's what I was thinking. Adding in logic that won't be exercised seems like a generally bad idea.

**Comment by tschottdorf** [comment]
👍
