### ISSUE TITLE
roachtest: post issues

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#24894]
We run `roachtest` regularly on both master and `release-2.0`. A few tests are failing regularly, and with the expected growth in the number of tests this is unlikely to become better anytime soon.

roachtest failures should match the experience from our unit and acceptance testing in that they open issues for failed runs. This makes these failures visible to triage and assignable.

We do have notifications in a slack channel, but that does not create the same sense of responsiblity and is already not working well. These notifications are an auxiliary tool at best.

**Comment by vilterp** [comment]
How do we create GH issues for unit test runs currently? Is it a script that runs inside of TC, triggered by failed runs?

**Comment by benesch** [comment]
Yep. See build/teamcity-post-failures.py and pkg/cmd/github-post.

**Comment by tschottdorf** [comment]
@petermattis bumping this. Triaging is hard without it.

**Comment by petermattis** [comment]
I wonder if we can just pipe the roachtest output through `cmd/github-post`, similar to what `build/teamcity-stress.sh` does.

**Comment by petermattis** [comment]
`github-post` works if we're using the normal output, but not if we're using the `--teamcity` output. Hrmm. I suppose I could extract the logic from `github-post` into a library and use it directly in `roachtest`. @benesch probably has a better idea.

**Comment by benesch** [comment]
I think you want to invoke build/teamcity-post-failures.py. It looks at the
structured TeamCity test status API and so should handle (in fact require)
the --teamcity output.

**Comment by petermattis** [comment]
@benesch Thanks for the pointer. Looks like it should work, though `teamcity-post-failures.py` doesn't do the de-duplication that `github-post` does.

One advantage to having `roachtest` post issues directly is that we could distinguish between stable and unstable failures.

**Comment by benesch** [comment]
Makes sense. Sounds like it might be time to merge teamcity-post-failures
into github-post and make it a proper library. (I'd really like to avoid a
*third* issue posting script.)

**Comment by petermattis** [comment]
My thought was to pull the guts of `github-post` into a library and use that directly from `roachtest`. Converting `teamcity-post-failures` would be a natural follow-on step when I rewrite that python script in Go. (The xml parsing in Go looks real easy, so I don't expect that to take much time at all).

**Comment by benesch** [comment]
👍🏽
