### ISSUE TITLE
ui: Automated way to identify skew in metrics

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/cockroach#24902]
feature request

**FEATURE REQUEST**

2. Please describe the feature you are requesting, as well as your proposed use case for this feature.

When all nodes in a cluster are participating, the database tends to perform well.  However, localized hot spots tend to materialize their effect with poor performance, un-even performance, instability ...

CockroachDB collects over 250 metrics per node.  Each range has many metrics as well.  Detection of skew is difficult when there are so many metrics to review.  A system that can compare all of the collected metrics at a given time and identify the metrics and the ranges, nodes, localities where the skew is produced would be valuable first step in proactive monitoring.  Subsequent tasks of impact, cause, prevention, remediation can then undertaken.  

For example, one range, one node, one locality could have more data than any other.  This data skew will tend to create poor performance as more workloads could be directed to the range, node, or locality containing the data.  The negative effect will magnify with high concurrency. 

3. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

considered "should-have" as manual examination is the current approach.  The manual approach requires highly technical personnel.  The experience and intuition will narrow the potential problems areas.  Non SME may need to take a look at everything which is time consuming, lowers productivity and potentially classify certain application as unfit.

**Comment by nstewart** [comment]
Passing to @dianasaur323 to understand root issue and determine if this is something being solved in other ways. If the core request is "easy ways to see (or be alerted) if the cluster is unhealthy", we are making strides there in 2.1 with the ops + tools and web ui roadmaps cc @piyush-singh .

Either way, this needs more conversation with pms to move this forward. I'll let @dianasaur323 take the lead here.
