### ISSUE TITLE
feature req: nodeJs client

### ISSUE THREAD

**Issue by gebrits** [cockroachdb/cockroach#2492]
Is an official NodeJS client on the roadmap? If so, any ballpark eta?

**Comment by petermattis** [comment]
Yes, a NodeJS client is on the roadmap. See #2132. We're looking to have the beta (with the NodeJS client) out by the end of the year.

**Comment by petermattis** [comment]
We're supporting the postgres wire protocol now. Any NodeJS postgres client should work, though we haven't done any compatibility testing with NodeJS yet.
