### ISSUE TITLE
sql: assertion tripped: deadline below txn.OrigTimestamp is nonsensical

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#24930]
https://sentry.io/cockroach-labs/cockroachdb/issues/531969578/

```
*log.safeError: txn.go:582: deadline below txn.OrigTimestamp is nonsensical; txn has would have no change to commit. Deadline: %s, txn: %s | hlc.Timestamp; *roachpb.Transaction
  File "github.com/cockroachdb/cockroach/pkg/sql/table.go", line 310, in getTableVersion
  File "github.com/cockroachdb/cockroach/pkg/sql/physical_schema_accessors.go", line 202, in GetObjectDesc
  File "github.com/cockroachdb/cockroach/pkg/sql/logical_schema_accessors.go", line 79, in GetObjectDesc
  File "github.com/cockroachdb/cockroach/pkg/sql/resolver.go", line 208, in LookupObject
  File "github.com/cockroachdb/cockroach/pkg/sql/sem/tree/name_resolution.go", line 296, in ResolveExisting
...
(15 additional frame(s) were not displayed)

txn.go:582: deadline below txn.OrigTimestamp is nonsensical; txn has would have no change to commit. Deadline: %s, txn: %s | hlc.Timestamp; *roachpb.Transaction
```

**Comment by andreimatei** [comment]
Same cluster also had a clock sync crash; maybe it's related
https://sentry.io/cockroach-labs/cockroachdb/issues/431183536/?query=cluster:%221149c0a4-3217-4802-841a-d78801860ddf%22

**Comment by vivekmenezes** [comment]
There are two possibilities here:
1. AcquireByName() returned a bad expiration time
2. OrigTimestamp on the txn was pushed forward in the time sql read the OrigTimestamp() and called UpdateDeadlineMaybe()

Will explore 1. for now and report back.

**Comment by vivekmenezes** [comment]
closing this issue because it's not actionable

**Comment by vivekmenezes** [comment]
reopening this because we've seen this on a couple of 2.0 builds. Unfortunately we need to wait until we see it in 2.1 before we can tell who the culprit is.

**Comment by knz** [comment]
All reports so far in 2.0.

**Comment by vivekmenezes** [comment]
closing this since we haven't seen it in 2.1
