### ISSUE TITLE
server: TestClusterVersionUpgrade1_0To2_0 is taking 35s

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#24940]
Is this expected? Large periods of log spam with `system config is not available`.

`make testshort PKG=./pkg/server TESTFLAGS=-v TESTS=TestClusterVersionUpgrade1_0To2_0`

```
--- PASS: TestClusterVersionUpgrade1_0To2_0 (35.84s)
    --- PASS: TestClusterVersionUpgrade1_0To2_0/1.0 (0.03s)
    --- PASS: TestClusterVersionUpgrade1_0To2_0/1.0-500 (0.03s)
    --- PASS: TestClusterVersionUpgrade1_0To2_0/1.1 (0.03s)
    --- PASS: TestClusterVersionUpgrade1_0To2_0/1.2 (0.03s)
PASS
```

If it's expected, let's skip it on `testshort`. Let me know if I should do that.

**Comment by tschottdorf** [comment]
Not expected.

@windchan7, could you take a look? It's possible that you'll need help here, but for starters try to find out where the test spends the 35 seconds, and then we can figure out the rest together.

**Comment by windchan7** [comment]
Now the test is gone and is renamed to `TestClusterVersionUpgrade`. It's running about 2 seconds. I don't think it's a concern anymore.

**Comment by tschottdorf** [comment]
👍 I'll close it right now.
