### ISSUE TITLE
UUID cannot be null

### ISSUE THREAD

**Issue by Extarys** [cockroachdb/cockroach#24951]
**BUG REPORT**

1. Please supply the header (i.e. the first few lines) of your most recent
   log file **for each node in your cluster**. On most unix-based systems
   running with defaults, this boils down to the output of

     there is no cockroach-data/logs/cockroach.log.

   When log files are not available, supply the output of `cockroach version`
   and all flags/environment variables passed to `cockroach start` instead.

```
Build Tag:    v2.0.0
Build Time:   2018/04/03 20:56:09
Distribution: CCL
Platform:     linux amd64 (x86_64-unknown-linux-gnu)
Go Version:   go1.10
C Compiler:   gcc 6.3.0
Build SHA-1:  a6b498b7aff14234bcde23107b9e7fa14e6a34a8
Build Type:   release
```
Running local with --insecure

2. Please describe the issue you observed:
I want to create a column that store it's parent UUID, if needed.

- What did you do?
```
CREATE TABLE Posts (
  itemId UUID DEFAULT gen_random_uuid(),
  userId INT NOT NULL REFERENCES Users (userId) ON DELETE CASCADE,
  content TEXT NOT NULL,
  embedItemId UUID DEFAULT '',
  createdAt TIMESTAMP NOT NULL DEFAULT now(),
  editedAt TIMESTAMP,
  PRIMARY KEY (userId, itemId),
  INDEX (userId)
);
```

- What did you expect to see?
Creating the table.

- What did you see instead?
```
psql -p 26257 -h 127.0.0.1 -d dbtest -U usertest < sql.sql
SET
DROP TABLE
ERROR:  expected DEFAULT expression to have type uuid, but '0' has type int
ERROR:  relation "users" does not exist
```

On a side note, is it possible to update the editedAt field on update and set createdAt on creation?

Thanks!

**Comment by Extarys** [comment]
Ohh nevermind, it seems that my script was calling another file which had an issue setting default for the uuid field. My mistake, sorry.

**Comment by danhhz** [comment]
Glad you figured it out!
