### ISSUE TITLE
Suggestion: Massive.js support layer for NodeJS

### ISSUE THREAD

**Issue by Extarys** [cockroachdb/cockroach#24964]
**FEATURE REQUEST**

Support layer for https://github.com/dmfay/massive-js

For a huge applications and tables, having to write queries with 50 columns is ugly and hard to maintain in the long run. ORMs like Sequelize need to set all table's columns and may be a bottleneck for complicated queries.

I played lightly with massive.js but it looks very nice and simple for fast development and deployment.
I was wondering if someone else was thinking that it would be a good idea to have this compatible with roach.

Massive get all table's information on connection, so no need to declare them.

Since cockroach is not entirely compatible with postgresql, I asusme if I use it in production I'll eventually get some nasty errors.

the couple of times I used an ORM I decided to ditch them because they wheren't 'useful' enough. I don't know about sequelize. 

What do you think?

**Comment by a-robinson** [comment]
Hi @Extarys, we recommend using either the [`pg` client driver](https://www.npmjs.com/package/pg) or Sequelize for [connecting to us from Node](https://www.cockroachlabs.com/docs/stable/build-a-nodejs-app-with-cockroachdb-sequelize.html), but I can't say I know much about Massive.js.

As a general rule, we don't prioritize explicit support for different frameworks unless there's strong customer demand for them, so I don't expect that we'll look into Massive.js in the near future. If you try using it with cockroach and find any queries that don't work, though, we'd love that sort of information to help us improve our Postgres compatibility.

cc @awoods187

**Comment by Extarys** [comment]
I gave sequelize a try and I'm very surprised and please with it, sorry then. I never really enjoyed ORM before.
