### ISSUE TITLE
sql: lpad: time and memory unbounded

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#24967]
`SELECT lpad('12345'::string, 9223372036854775807::int)`

This uses 100% CPU and takes as much memory as it can, more than the limiter would allow.

Found with RSG.

**Comment by knz** [comment]
Note we've had another functions (concat_ws) that was growing memory usage unreasonably. The solution was to use the memory monitor in the evalctx.

**Comment by knz** [comment]
ditto for various array functions.
