### ISSUE TITLE
sql, server: add partitions and indices to replica matrix endpoint

### ISSUE THREAD

**Issue by vilterp** [cockroachdb/cockroach#24961]
The `ReplicaMatrix` endpoint on the admin server currently returns the number of replicas for each table on each node, by scanning meta2. It should break this down further, returning the number of replicas for each partition on each node.

Discussed this with @benesch; it looks something like (correct me if I'm wrong):
1. Get all the zone configs from `system.zones`, including their subzones (the endpoint currently gets them via `EXPERIMENTAL SHOW ALL ZONE CONFIGS`, which breaks out subzones; we don't want this)
2. for each range in meta2:
    - get the zone config `tableZC` for the table we're in
    - call `tableZC.GetSubzoneForKeySuffix()` for the current range
    - if we see a subzone, there's a partition. add it to the output proto

Jira issue: CRDB-5738

**Comment by knz** [comment]
cc @couchand for prioritization

**Comment by knz** [comment]
@piyush-singh @dhartunian is this issue still current?

**Comment by maryliag** [comment]
No longer a priority
