### ISSUE TITLE
server, ui: Merge Admin and Status endpoints

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#24989]
We have, for historical reasons, two different main endpoints for UI and Status data.

Originally, as we were upgrading the UI, the admin endpoint was supposed to handle all requests that were destined for the admin ui, as opposed to other misc endpoints.  But that distinction is no longer true and never really was.

We also have to make sure that permissions are clear for every endpoint. And having the two endpoints is clearly just complicating that.

For anyone looking to add a new endpoint, there is no clear guidance, this makes doing any admin ui work more complicated.

I started auditing both and here are the endpoints in both right now:

Admin
- Users
- Databases
- Database Detail
- Tables
- Table Stats
- Non-Table Stats
- Events
- UI Data
- Cluster Metadata
- Cluster Settings 
- Diagnostics Report
- Health
- Liveness
- Jobs
- Locations
- Query Plan
- Drain

Status:
- Certs
- Node Details
- Nodes
- Raft
- Ranges
- Gossip
- Allocator Simulation
- Sessions
- Sessions (Local)
- Cancel Query
- Cancel Session
- Span
- Stacks
- Profile
- Metrics
- Log Files List
- Log File
- Logs
- Problem Ranges
- Range 
- Command Queue

It's obvious that there is no clear division between the two endpoints and I recommend that we move all into Status, just because there is less code movement.  We should of course maintain the old links, at least until v2.2 or even v3.0. 

Jira issue: CRDB-5737

**Comment by couchand** [comment]
My proposal, in light of the login work, is that status be endpoints that are accessible anonymously, and admin be endpoints that are not.

**Comment by piyush-singh** [comment]
We will not get to this in 2.1, bumping to Later. We can pull it into 2.2 depending on other priorities.
