### ISSUE TITLE
storage: Marshal RaftCommand outside of Replica mutex

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#24991]
Related to #9827.

#24990 demonstrated that locking in Replica.propose is expensive and that it has a direct impact on throughput. Part of the reason for this is that RaftCommand's are currently [marshaled](https://github.com/cockroachdb/cockroach/blob/ef87ff71f9fa58da5da703bb3079d407d096c911/pkg/storage/replica.go#L3304) to a byte array while holding locks. We should look into ways to perform this marshaling before grabbing the lock(s) required to perform the Raft proposal.

This is a little tricky because we [assign](https://github.com/cockroachdb/cockroach/blob/ef87ff71f9fa58da5da703bb3079d407d096c911/pkg/storage/replica.go#L3060) the command's lease index while holding locks in `insertProposalLocked`. I tested out a prototype where atomic access to these variables (`lastAssignedLeaseIndex` and `LeaseAppliedIndex`) is used to predict their expected value. Using this, we could marshal before grabbing the locks. However, the test had to marshal again after grabbing the locks if its prediction was incorrect. This is a little messy, but it provided about a 4-5% improvement on top of #24990. At a minimum, this demonstrated that there are gains to be had if we do something here.

**Comment by bdarnell** [comment]
Instead of using atomics, we could encode the RaftCommand in two parts. First encode a RaftCommand with every field set but the lease index outside the locks, then inside the lock encode a RaftCommand with *only* the lease index set, then concatenate them. This is a safe use of protobufs (as long as you're only working with top-level fields)

**Comment by nvanbenschoten** [comment]
I considered the idea to create a new Raft command encoding that would allow us to encode most of the `storagebase.RaftCommand` outside the lock and the lease index inside the lock. Essentially we would be storing the lease index outside of the encoded proto entirely. Your proposal sounds like it accomplishes the same thing with much less complexity! Mind pointing to the documentation discussing why/how that is allowed?

**Comment by bdarnell** [comment]
It doesn't seem to be called out anywhere in the public docs, although it can be inferred from the [protobuf encoding](https://developers.google.com/protocol-buffers/docs/encoding) documentation.

**Comment by nvanbenschoten** [comment]
Actually, it's explicit right at the bottom!

> it's sometimes useful to merge two messages by simply concatenating them.

Thanks for the tip @bdarnell.

**Comment by nvanbenschoten** [comment]
I did some benchmarking with a prototype that used the byte slice concatenation trick. When built on top of #24990, I wasn't able to see any significant performance improvement. This benchmarking was more rigorous than the previous one mentioned above, so perhaps that perceived gain was just a fluke. Closing for now.
