### ISSUE TITLE
Most queues should ignore ranges that need to be split.

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#2499]
This is currently done by most of them, but not all. eg: `storage/replicate_queue.go:process`
Queues should check whether a range needs to be split both in `shouldQueue`, and again in `process`.

Since we're doing this so many times, we may want to add a `needNonSplitable` setting for each queue (the split queue should be the only one that accepts ranges that need to be split).

**Comment by spencerkimball** [comment]
Sounds like this should be done in the base queue. In `baseQueue.processOne` perhaps...

**Comment by mberhault** [comment]
yup. my plan is to add something like `skipSplitableRanges` similar to the `needLease` that queues have.
PR should be out for review tomorrow.
