### ISSUE TITLE
stability: Slow snapshot application on restarted node in geo-distributed cluster

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#25010]
In one of @dianasaur323's geo-distributed clusters that spans both the US and Europe, she dropped a large database and restarted a node that had been offline for over a week (I don't know the timing/order of events for sure). Replication to the restarted node is going incredibly slowly, with only ~20 replicas having been moved onto it after an hour, and now ~290 replicas after two hours.

The logs for the restarted node (n4) are very suspicious. Snapshots with very little data in them have been taking minutes to hours to apply:

```
I180423 18:17:59.291347 825 storage/replica_raftstorage.go:732  [n4,s4,r1628/?:/Table/211/1/"UPDATE _ SET _ …] applied preemptive snapshot in 106217ms [clear=106158ms batch=4ms entries=3ms commit=2ms]
I180423 18:25:40.089587 2997 storage/replica_raftstorage.go:732  [n4,s4,r1590/?:/Table/211/1/"{DELET…-INSER…}] applied preemptive snapshot in 507285ms [clear=507226ms batch=8ms entries=0ms commit=2ms]
I180423 18:25:40.288688 7933 storage/replica_raftstorage.go:732  [n4,s4,r1784/?:/Table/211/2/"2{ca6cc…-ff5b5…}] applied preemptive snapshot in 387683ms [clear=387419ms batch=21ms entries=0ms commit=6ms]
I180423 19:57:10.477599 5469 storage/replica_raftstorage.go:732  [n4,s4,r958/?:/Table/183/3/"SELECT {_:…-cl…}] applied preemptive snapshot in 5937578ms [clear=5936506ms batch=23ms entries=30ms commit=60ms]
I180423 19:58:21.526906 12909 storage/replica_raftstorage.go:732  [n4,s4,r498/?:/Table/180/1/"\x1{7\x1…-aŝ\…}] applied preemptive snapshot in 5828724ms [clear=5827868ms batch=17ms entries=56ms commit=115ms]
```

All the slowness is from the `clearRangeData` phase of snapshot application. @tschottdorf does this ring any bells of issues we've had lately? Rocksdb range tombstones or the like?

**Comment by a-robinson** [comment]
And for what it's worth, this is using the dataset that has some really long start and end keys on its ranges.

**Comment by tschottdorf** [comment]
#24029? I suspect you might find that this cluster has lots of range deletion tombstones in its SSTs.

**Comment by a-robinson** [comment]
It looks like it cleaned itself up when someone restarted it after an OOM kill, but symptoms match up very well. After the restart it successfully compacted about 30GB of data and almost all 95+% of its sstables. Closing as a dupe.
