### ISSUE TITLE
sql: SHOW EXPERIMENTAL_FINGERPRINTS races with schema changes

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#25022]
`create table f(x int primary key, y int, index y_idx (y));`
conn 1: `BEGIN`
conn 2: `drop index f@y_idx;`
conn 1: 
```
show experimental_fingerprints from table f;
pq: index [3] not found
```

This is because the `ShowFingerprints` bypasses the table desc cache initially when deciding which indexes to fingerprint, and so thinks that there's two indexes :
```
	// We avoid the cache so that we can observe the fingerprints without
	// taking a lease, like other SHOW commands. We also use
	// allowAdding=true so we can look at the fingerprints of a table
	// added in the same transaction.
	//
	// TODO(vivek): check if the cache can be used.
	p.runWithOptions(resolveFlags{allowAdding: true, skipCache: true}, func() {
		tableDesc, err = ResolveExistingObject(ctx, p, tn, true /*required*/, requireTableDesc)
	})
```

But then actually fingerprinting probably hits the cache which now says that there's a single index. This is related to the fact that dropping the index starts out by overwriting the descriptor and adding a mutation which makes the index invisible to most code. We probably have a bunch of similar problems elsewhere where we mess with the cache usage.

Btw, execution of fingerprinting each index is delegated to `planner.makeInternalPlan()`, which is a bit of an abomination. Ideally, planning a `show experimental_fingerprints` would produce a complete plan and not do more planning at runtime. Somewhat related, I'm removing that `makeInternalPlan` method and delegating to an `InternalExecutor`, but that's unlikely to help this issue.

@jordanlewis please triage this can of worms.
cc @knz @danhhz @vivekmenezes

**Comment by vivekmenezes** [comment]
@andreimatei this is no longer an issue.

Is it possible that we fixed this by the change that got rid of up_version?

**Comment by andreimatei** [comment]
No clue... Glad it's gone...

**Comment by vivekmenezes** [comment]
liked fixed by https://github.com/cockroachdb/cockroach/pull/26346 . Prior to that change the schema change would schedule a drop index without incrementing the version resulting in the fingerprint code reading a descriptor without the index even though it had been deleted.
