### ISSUE TITLE
control placement of secondary index leaseholder on a geo-partitioned table  

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/cockroach#25035]
**FEATURE REQUEST**

Leaseholder placement for secondary keys that do that have partition key cannot be controlled.  On a globally distributed multi-active cluster, performance variance when using secondary index is great.  The variance is un-predictable as the location of the leaseholder of the secondary index can move. 
 
```
CREATE TABLE IF NOT EXISTS orders8(
    id INT PRIMARY KEY,
    customer INT NOT NULL,
    customer1 INT NOT NULL,
    customer2 INT NOT NULL,
    customer3 INT NOT NULL,
    customer4 INT NOT NULL,
    customer5 INT NOT NULL,
    customer6 INT NOT NULL,
    customer7 INT NOT NULL,
    orderTotal DECIMAL(9,2),
    INDEX (customer),
    INDEX (customer1),
    INDEX (customer2),
    INDEX (customer3),
    INDEX (customer4),
    INDEX (customer5),
    INDEX (customer6),
    INDEX (customer7)
  ) PARTITION BY RANGE (id) (
	PARTITION east VALUES FROM (0) TO (1000), 
	PARTITION west VALUES FROM (1000) TO (2000), 
	PARTITION central VALUES FROM (2000) TO (3000)
);
```

**Comment by bdarnell** [comment]
Are you sure it's not possible to do this today? It looks like `ALTER INDEX orders8@customer EXPERIMENTAL CONFIGURE ZONE...` should work.

**Comment by a-robinson** [comment]
@bdarnell is correct, you can already set leaseholder preferences (and placement constraints) on secondary indexes using the syntax he provided (or by using `./cockroach zone set <db>.<table>@<index>`). You can even partition indexes and set leaseholder preferences / placement constraints on the partitioned indexes - `./cockroach zone set <db>.<table>.<partition>@<index>` or `ALTER INDEX <db>.<table>.<partition>@<index> EXPERIMENTAL CONFIGURE ZONE ...`

Are we understanding the request correctly, @robert-s-lee? If so, please pass this along and close the issue. It's also possible this isn't documented very well, so cc @jseldess just incase.

**Comment by jseldess** [comment]
We decided not to document leaseholder placement controls for the 2.0 release, so there are no docs on that, for any type of data. I think we considered it an experimental feature. Are we now ready for this to be exposed via docs, @bdarnell, @a-robinson?

**Comment by bdarnell** [comment]
Lease placement is still experimental, but zone configs for indexes are not experimental and should be documented.

**Comment by a-robinson** [comment]
Sorry, my comment was confusing. I was just referring to documenting the ability to set zone configs on indexes and indexed partitions. Not specifically to setting leaseholder preferences.

**Comment by jseldess** [comment]
Ah, ok. Yeah, we definitely need to document setting zone configs on indexes. That's not mentioned anywhere in our docs. I created a docs issue for this: https://github.com/cockroachdb/docs/issues/3146.
