### ISSUE TITLE
sql: per-user/role/database resource limits (cpu,memory,concurrent queries)

### ISSUE THREAD

**Issue by skunkwerk** [cockroachdb/cockroach#25031]
1.  FEATURE REQUEST

Feature: Allow user/role/database-based resource limits on CPU/memory usage, or limit the number of concurrent queries per user/role/database.

2.  Use case: In a multi-tenant application, there are often hundreds to thousands of users/applications being supported.  If the users have raw SQL access to the database, it is necessary to limit each one's resources to avoid performance issues.

This type of feature is quite common in the case of data warehouses, such as Teradata and Vertica which have to support thousands of users, but can't allow any particular user to hog all the resources due to a badly-written query.

3.  Nice to have.

Jira issue: CRDB-5735

**Comment by a-robinson** [comment]
Thanks for the request, @skunkwerk. This is probably a ways off, since we still have a lot of room to improve analytical query performance before we think about per-role analytical query isolation. But cc @knz for tracking purposes.

**Comment by jordanlewis** [comment]
Resurfacing this just as a tracking item

**Comment by knz** [comment]
we are going to build multi-tenancy in a different way.
