### ISSUE TITLE
ui: investigate supporting SSO (Okta, etc)

### ISSUE THREAD

**Issue by vilterp** [cockroachdb/cockroach#25044]
see Okta's docs on SAML: https://developer.okta.com/standards/SAML/

**Comment by mberhault** [comment]
This is definitely post 2.1, and most likely an enterprise feature.

**Comment by vilterp** [comment]
@bdarnell mentioned in slack that other open source products have SSO and/or ActiveDirectory as an enterprise feature:

- https://www.mysql.com/products/enterprise/security.html
- https://docs.mongodb.com/manual/tutorial/authenticate-nativeldap-activedirectory/

**Comment by VinodAnandan** [comment]
Hi,

Please consider the SSO implementation using OpenID Connect.

https://developer.okta.com/standards/OIDC/

https://github.com/coreos/go-oidc

Thank you,

Vinod

**Comment by dhartunian** [comment]
OIDC Support for the Admin UI is being released as part of 20.2. I'm closing this issue. There's certainly more features to support but we'll create new issues for those as we move forward.

@VinodAnandan we ended up using the library you mentioned!
