### ISSUE TITLE
bulkio,debug: offline creation of BACKUP from on-disk stores

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#25049]
Brainstorming some possible disaster recovery workflows, and how to recover data from an unavailable cluster:

1. Get debug KV to dump SST(s) between start and end
2. Connect to each store dir, run above on each store
  a.  The SSTs are overlapping and contain duplicates, since we exported every replica.
3. Pull those SSTs back to a single bucket
4. Merge-Iterate over those SSTs to de-dupe and handle intents, outputting chunked, non-overlapping SSTs that look like an all-revision backup, spit out a BACKUP-DESCRIPTOR that enumerates the chunked SSTs with proper spans. 

This is proposed as a first pass for a disaster recovery tool that can be used after loss of quorum.
It is _offline_ and requires exporting/importing the entire table, so it might not work well for e.g. very large tables, particularly if they have only lost a small number of ranges. On the other hand, it doesn't touch a running cluster's state or try any scary surgery on replica/raft state, so it seems like a safe first pass.

**Comment by dt** [comment]
This is a jotting down of conversation with @petermattis @m-schneider @tschottdorf and @mjibson.

**Comment by petermattis** [comment]
> Get debug KV to dump SST(s) between start and end

I'd make this a new CLI command and not overload `debug keys` or any of the other `debug` commands. `./cockroach offline-emergency-backup` or something like that. 

> It is offline and requires exporting/importing the entire table, so it might not work well for e.g. very large tables, particularly if they have only lost a small number of ranges. 

To be fair, it should work in that scenario, but it will be slow in comparison to the amount of data that needs to be recovered.

**Comment by lunevalex** [comment]
@mwang1026 should this be folded into #17186

**Comment by mwang1026** [comment]
I think so. It's the same "problem" they want to solve but it's different approaches. I'll take conversation to the other ticket.

**Comment by mwang1026** [comment]
For larger clusters wouldn't be able to fit all data on a single node to run such a tool, so https://github.com/cockroachdb/cockroach/issues/17186 is going to be more scalable. Closing.
