### ISSUE TITLE
ui: investigate supporting authentication with client-side certs

### ISSUE THREAD

**Issue by vilterp** [cockroachdb/cockroach#25040]

**Comment by vilterp** [comment]
update: mimic pgwire: https://github.com/cockroachdb/cockroach/blob/5da4bbd9f24e637fa3fa8768f4132dca545f9cd8/pkg/sql/pgwire/v3.go#L280-L309

**Comment by mberhault** [comment]
Client certificates and browsers are notoriously annoying and tedious.
I would recommend not even attempting to use client certs for web authentication, but relying on passwords only. Of course, this creates quite a problem for `root` which is not allowed a password. (maybe change that decision, or allow a web-only password).

**Comment by mberhault** [comment]
I agree. The main thing to decide is how to perform authorization for cases where only `root` (or members of the `admin` role in enterprise) get to do things.

**Comment by vilterp** [comment]
Closing this, as I think we've agreed not to prioritize web login with client-side certs.
