### ISSUE TITLE
storage: allow creating RocksDB checkpoints

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#25053]
We have a number of "offline" commands that require exclusive access to the RocksDB instance and won't work against a running server.

RocksDB has the option to create [checkpoints](https://github.com/facebook/rocksdb/wiki/Checkpoints), which is just a data directory that can be opened in read-only mode, and whose contents are mostly hard-links into an existing RocksDB instance's SSTables.

This could be used to let a running server create a checkpoint, which can then be introspected using the debugging tools. It can also be used before beginning potentially unsafe operations, such as trying to recovering from unavailability by rewriting range descriptors and Raft state.

**Comment by tschottdorf** [comment]
cc @danhhz in the context of recovery from unavailable quorum. This can turn an "offline" process into one that can work with the server still running, assuming that's somehow helpful (it could be in a large cluster you're unwilling to take offline as a whole).
