### ISSUE TITLE
storage: handle unavailable ranges at the storage level

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#25058]
In the long run, a cluster needs to be able to return to full health from a permanently under-replicated state, though this becomes a lot harder when system ranges are partially or even fully lost. This issue collects a few ideas on dealing with this situation. I'm not suggesting we immediately tackle any of these.

Note that all of these scenarios include possible data loss and resulting with it, inconsistent data (as viewed from SQL). The goal is to get back to a healthy core layer with as little disruption as possible. All of the below will want to create a [RocksDB checkpoint](https://github.com/cockroachdb/cockroach/issues/25053) across all affected nodes in the cluster.

1. all replicas of a user range were lost (or we're willing to lose whatever is left of it). Look up the remaining replicas holding a copy of the range (from the meta ranges), and disable them (forcibly remove them with a MaxInt32 tombstone). Bootstrap a new range on any node with only one replica (giving it a say, 30s grace period until it becomes eligible for replica GC) and rewrite the meta record to point to that newly create range instead. @petermattis also had the idea of manually marking a replica of an an underreplicated range so that it would return empty responses for scans (to allow `COUNT(*)` to work).
1. user replica is underreplicated, with a minority of surviving replicas. Look up the replica with the highest committed index. Destroy all other replicas (forcibly GC + lay down tombstone). On the remaining replica, lock the raft mutex, zero out the raft group, and change the range descriptor to only contain the single replica. Then resurrect the Raft group and run a txn that rewrites the descriptor in the meta keys.
1. node liveness range is unavailable: treat it like a user range above.
1. meta1/2 range is unavailable: have to run an offline process that rebuilds them offline. Not going to be easy. Probably better off creating a new cluster.
1. other system ranges (internal tables, etc): can potentially bootstrap new ones, but losing table descriptors is similarly scary. Probably better off creating a new cluster.

**Comment by bdarnell** [comment]
> all replicas of a user range were lost (or we're willing to lose whatever is left of it). Look up the remaining replicas holding a copy of the range (from the meta ranges), and disable them (forcibly remove them with a MaxInt32 tombstone).

How would you write that tombstone if the replica is down? We can't do anything to the nodes that once held replicas of the range. Instead, we could poison the node liveness record for the dead nodes, such that they will never again be allowed to become live without a wipe. 

For 3, it would also be possible to reconstruct a new node liveness range by scanning for the highest epochs and timestamps seen for all nodes, similar to the way we could reconstruct the meta ranges. We could also reduce the likelihood of problems 3, 4, and 5 (except for 3-node clusters) if we increased the replication factor for those spans.

For 5, losing table descriptors is bad, but users generally have a copy of their CREATE TABLE statements in a migration or setup script. As a last resort we might be able to reconstruct the table descriptors from an external source like this.

**Comment by tschottdorf** [comment]
Folding into #17186
