### ISSUE TITLE
workload: support distributed TPC-C load generation

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#25087]
Throughout all previous TPC-C testing, we have used a single centralized load generator process. Even when running against a 30 node cluster with 10k warehouses, this has not been an issue - the load generator has always been able to produce the desired amount of load. However, now that we're beginning to look into running TPC-C on a distributed cluster, we're going to need to figure out how to distribute the load generator. This is because we're going to move from running all cockroach nodes in a single dc to running them across multiple.

Naively, we would just continue to run a single load generator in one of the data centers and point it only at the dc's local nodes. This would work to some degree, but it would create a huge imbalance of load on that datacenter's nodes. We've already seen how important load distribution is to maximum TPC-C performance, so we'll need to do better. We could point this single load generator at all nodes in the cluster, but then we'd be introducing a huge amount of latency just between the load generator and the remove SQL gateways. Either way, a centralized load generator isn't going to work.

Moving past this idea, the next logical idea is to run the same TPC-C load generator in each data center and point each generator at only its local gateways. We could then combine the tpmC results of all generators. Unfortunately, this would produce invalid results because we would not be correctly respecting TPC-C's enforced `10 workers/warehouse` limit. This would allow us to run too many transactions for a given number of warehouses. Telling each load generator about only a fraction of the warehouses would solve this specific problem, but it would result in an incorrect distribution of remote warehouse accesses so it's also not an option. Instead, we need to divide the workers up amongst the different load generators (remember: each worker is bound to a warehouse) while having each load generator remain aware of the total number of warehouses. The current idea is to add a `--warehouse-range` flag to the load generator. This would indicate that even though there may be `--warehouses` total warehouses in the cluster, the generator should only create individual workers for some subset of those.

An important optimization to this is that the divide should directly correspond to the dataset partitioning. When running TPC-C in a distributed cluster, we are going to partition the dataset on warehouse boundaries. This is already provided by `workload's` `--partition` flag, and it works out pretty well in theory because only 10% of transactions touch remote warehouses. However, if the load generators were unaware of this then they might end up getting bound to remote warehouses. This would result in far more cross-dc transactions, which would destroy performance. To avoid this, we'll need to make sure there's an affinity between the warehouse partitioning and the use of the `--warehouse-range` flag.

@benesch mentioned that the `roachmart` load generator already had to solve this kind of issue. We should explore that solution and see how much of it applies to this issue.

@jordanlewis you're the expert here. Did I miss anything?

**Comment by petermattis** [comment]
The `loadgen/tpcc` load generator (and probably the `workload tpcc` load generator) partitions load amongst the connections based on the partitioning. Specifically, it partitions the warehouses amongst the connections based on the partitioning. It should be straightforward to extend that code to divide the warehouses amongst workers which would in turn divide amongst the connections.
