### ISSUE TITLE
roachtest: add TPC-C benchmarking test/tool

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#25084]
To aid in the evaluation of future performance changes, we should create a roachtest specifically for the purpose of benchmarking TPC-C. We decided that this is the right framework to create this benchmarking tool in for a few reasons:
- roachtests are integrated with roachprod, which simplifies and standardizes cluster management
- roachtests can spin up new clusters or use existing clusters out of the box
- roachtests makes it easy to run arbitrary commands on any nodes in a cluster, which make it flexible enough for our needs
- chaos functionality will be added to the roachtest infrastructure in the near future (TODO @tschottdorf link issue when it's ready)
- roachtests are run nightly, which will prevent this from rotting over time

The test should first configure its cluster with performance-related settings. To start, this can be pulled straight from the recently-published [performance report](https://www.cockroachlabs.com/guides/cockroachdb-performance/). It should then populate the cluster with a TPC-C dataset of the desired size. After this, it should run TPC-C for a set period of time - probably 10 minutes by default. Finally, it should spit out a tpmC number (**in bold!**), along with associated latencies.

Other thoughts:
- TPC-C consistency checks should be opt-in to prevent slowing down testing.
- To start, we can restore a `workload fixture` to populate the dataset. This will work up until around TPC-C 1k, but will probably be too slow at any warehouse count above that.
- We may want to avoid wiping the cluster when the roachtest finishes, so that the test can be run multiple times without restoring the dataset between each change.

**Comment by a-robinson** [comment]
@nvanbenschoten do you have an estimate of when you'll have something working? I'm under the impression you're going to drive this, but let me know if that's not the case.

**Comment by nvanbenschoten** [comment]
Yep, I'm aiming to have a working PR out by the end of the week. Once I do, I'd appreciate help testing it out and iterating on its ergonomics.
