### ISSUE TITLE
ui: Remove "two simple SQL" commands text from map onboarding

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/cockroach#25095]
![image](https://user-images.githubusercontent.com/894257/39307472-e1b79c5c-4930-11e8-8a79-dfc9774013f1.png)

> Step 2: Activate the trial license with two simple SQL commands.

We ended up consolidated this into one command (even easier). For the image we can just show the bottom command. Perhaps for the text we can just say "Activate the license"

> SET CLUSTER SETTING ENTERPRISE LICENSE =

**Comment by couchand** [comment]
Hmmm, [the docs](https://www.cockroachlabs.com/docs/stable/enterprise-licensing.html#set-the-trial-or-enterprise-license-key) don't agree, is this a change?

**Comment by nstewart** [comment]
In the self-service license email that gets kicked off from the link, we take the two commands and put it in one line (separated by a semi-colon) so we don't make the user copy and paste twice. This was a usability enhancement.

**Comment by couchand** [comment]
Fair enough.  So it's not currently wrong, but we could probably align it more.
