### ISSUE TITLE
IF EXISTS or Function Definition in Cockroachdb?

### ISSUE THREAD

**Issue by steedyu** [cockroachdb/cockroach#25093]
Querstion

1 Does cockroachdb support stored procedure, doesn't it? I check the related issue and it maybe not.

2 I am newer for cockroachdb. Can "IF EXISIS/ IF NOT EXISTS" sql statement be used in it?
I tried as below:

if exisit (SELECT 1 ) then 
	select 1;     
end if;

it show me : if syntax error

3 Can I define function in cockroachdb?

**Comment by a-robinson** [comment]
1. Cockroach does not currently support stored procedures.
2. We do not support top-level `IF` statements. They aren't part of standard SQL, they're part of the procedural language used for stored procedures (PL/pgSQL in postgres).
3. Not as of today, and it's not on the roadmap for our release later this year either.

**Comment by steedyu** [comment]
ok, thank you
