### ISSUE TITLE
ui: typo in node map onboarding screen

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/cockroach#25096]
![image](https://user-images.githubusercontent.com/894257/39307686-812d92d2-4931-11e8-85d3-38bbbd61f7e8.png)

> Step 3: Refer this configuration guide to configure the Node Map.

Missing 'to'. Should be 
> Refer to [this guide](https://www.cockroachlabs.com/docs/v2.0/enable-node-map.html) to configure the roadmap

**Comment by vilterp** [comment]
My bad :facepalm:
