### ISSUE TITLE
roachtest: import test hitting error while backpressuring writes

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#25105]
`import/tpcc/warehouses=1000/nodes=4` failed with the following error:

```
workload0Error: pq: waiting on split that failed: result is ambiguous (context finished during distsender send: context deadline exceeded)
```

https://teamcity.cockroachdb.com/viewLog.html?buildId=624804&buildTypeId=Cockroach_Nightlies_WorkloadNightly

**Comment by rytaft** [comment]
There was another error in this test. Not sure if it's the same issue: https://teamcity.cockroachdb.com/viewLog.html?buildId=633237&tab=buildResultsDiv&buildTypeId=Cockroach_Nightlies_NightlySuite.

```
    cluster.go:657,import.go:42,cluster.go:812,errgroup.go:58: roachprod run teamcity-633729-import-tpcc-warehouses-1000-nodes-4:1 -- ./workload fixtures make tpcc --warehouses=1000 --csv-server='http://localhost:8081' --gcs-bucket-override=cockroach-tmp --gcs-prefix-override=teamcity-633729-import-tpcc-warehouses-1000-nodes-4: exit status 1
```

**Comment by nvanbenschoten** [comment]
The roachtest hasn't hit this in a few months. Closing.
