### ISSUE TITLE
sql: sequences: support `AS <datatype>`

### ISSUE THREAD

**Issue by vilterp** [cockroachdb/cockroach#25110]
Currently fails to parse with an unimplemented error: https://github.com/cockroachdb/cockroach/blob/fef4d74b58815452cd51a4a32f7503b8b5d75051/pkg/sql/parser/sql.y#L3935

and we always create the sequence as an int64.

**Comment by vy-ton** [comment]
@rafiss Moving to SQL Experience triage since this was on a closed project. This shows up as a top unimplemented feature on Serverless. I also see some activity on the linked PR :)

**Comment by Jolg42** [comment]
It's indeed a thing on serverless as of today, any idea when it will fixed on the live clusters?

**Comment by vy-ton** [comment]
This will be available with 22.1, our first release in 2022
