### ISSUE TITLE
Provide a way to tell object type from its ID.

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#2511]
eg: given ID=1010, is the corresponding object a table or database?
Currently, we need to fetch its descriptor and attempt to parse it as either a database descriptor, or a table descriptor. see: `sql/config.go:GetZoneConfig` for an example.

Ideally, we should be able to look this up using a single KV get, preferably alongside the descriptor.

Possibilities:
* make `TableDescriptor` and `DatabaseDescriptor` use the same proto message with additional `type` field. Requires slightly stricter validation on creation/use.
* add a `type` column to `system.descriptor`. Would double the number of keys and require two reads.
* separate column or table based on descriptor type. Would need two lookups, one of which would always fail. Moves enforcement of unique ID outside the `system.descriptor` table.
* encode the type into the ID. We would have to be very careful about passing them around.

Future considerations:
Depending on if/how we end up supporting proto fields as columns, having different proto messages may not work.

**Comment by petermattis** [comment]
My preference is merging `TableDescriptor` and `DatabaseDescriptor`. The various possibilities all of their drawbacks, but I feel this one has the fewest and is the clearest transition from what we currently have.

**Comment by spencerkimball** [comment]
:+1:  on merge, although I assume you mean having a union proto type? I wouldn't necessarily want to try to share fields which mean slightly different things depending on type. Those solutions always start to get icky.
