### ISSUE TITLE
backupccl: If a RESTORE fails due to a 403/404 it's not logged in the JOBS table

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/cockroach#25129]
I have a script that periodically restores backups to another database for analysis. At some point, RESTOREs started failing (the backups weren't being created in the first place) but it looked like the RESTORE script itself wasn't running because there was no entry at all in the jobs table. 

I would expect if RESTORE returns a non-syntax error failure message this would be logged in the jobs table as a failed job.

**Comment by mjibson** [comment]
Yeah, this is annoying but I guess makes sense. Or we have to change the API such that it returns a job id and you have to then run `WAIT <jobid>`, but for now I think this is a good rule.

**Comment by rolandcrosby** [comment]
I haven't heard any customer feedback that this is critical for 2.1, but we really ought to fix this, as the docs for SHOW JOBS and for RESTORE both state (with no further qualification) that all RESTORE actions will be logged in the jobs table. @mjibson let's take a stab at fixing this for the Aug 20 milestone, with the understanding that it's not extremely high severity and can get bumped if the solution is more complex than anticipated.

**Comment by rolandcrosby** [comment]
Handled via doc fixes; if/when we build async jobs, then we can make sure that a job ID is always created even when we know up front that the backup will fail.
