### ISSUE TITLE
sql: support a "unique ID" column type

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#2513]
Supporting an `AUTO_INCREMENT` or `SERIAL` column type is problematic because we want to avoid centralized allocation of IDs. Such columns are frequently used for unique ID generation with a mostly monotonically increasing guarantee. (It is possible for transactions to commit the auto-increment/serial column value out of the order in which the values were allocated). 

As an alternative, CockroachDB should support something similar to [Twitter's Snowflake IDs](https://blog.twitter.com/2010/announcing-snowflake): a value composed of `<timestamp>/<nodeID>`. The `<timestamp>` would be guaranteed to be monotonically increasing per node and the `<nodeID>` could be the existing CockroachDB node ID which is guaranteed to be unique per node.

The most straightforward implementation would be to use the hybrid logical clock which is composed of a 64-bit nanoseconds value and a 32-bit logical value. Together with the nodeID, this would be encoded as `varint(nanoseconds)/varint(logical)/varint(nodeID)`. This would encode to 12-13 bytes. If we switched from nanoseconds to milliseconds we could get this down to 10-11 bytes. And there are probably some other space tricks we could play as well by combining the `timestamp` with the `logical` component which might save another byte or two. Squeezing everything into a 64-bit value seems excessive and perhaps overly restrictive (how many bits would we give to the nodeID vs the timestamp component).

**Comment by fire** [comment]
It may also be useful to copy uuid_generate_v1mc() from postgres. The keys are seq because they're time based. So all inserts go to the same data page without random io. However I'm not sure if this optimizes anything.

**Comment by spencerkimball** [comment]
I like this proposal. Generating IDs from a key serving as an allocator would generate many versioned values which could get problematic for a busy allocator.

**Comment by vivekmenezes** [comment]
It will be nice to be able to run a scan over the ids by timestamp range.

Another option for users who'd like an explicit timestamp column in their row is to provide them with a function nodeid() which will allow them to use current_timestamp() and nodeid() as the default values for two columns that together form a primary key.

**Comment by petermattis** [comment]
@fire Thanks for the pointer. The proposal is very much like `uuid_generate_v1mc`, though without using the computer's MAC address. The benefit of mostly sequential IDs is that the writes will go to a single range instead of being scattered across O(num-rows) ranges. When inserting a large number of values, this can be a significant win.

@vivekmenezes `current_timestamp()` is not unique on a given node due to leap seconds and time adjustments.

**Comment by bdarnell** [comment]
Leap seconds only move the clock forward, never backwards. `current_timestamp()` could be monotonic and unique per node if we want it to be (using our HLC instead of the plain system clock). 

I'm opposed to exposing a `nodeid()` function at the sql layer, though. In the future we're going to want to move SQL processing down to the data nodes as much as possible, and that needs to be transparent to the user. That means we can't expose node ID(s) except in higher-level constructs like ID generation (where the IDs themselves are intended to be opaque to the application).

**Comment by vivekmenezes** [comment]
Sorry I meant a function that returns the logical-id and the node-id as an id. Essentially a local monotonically increasing id (per node, per timestamp) that can be added to the database just to make columns <timestamp, id> unique for a row. I think there is value for users to be able to read and interpret the timestamp for their queries while using the id to make the key unique just for the database. The separation is valuable. One of the dangers is users reading the node-id from the id and depending on it for some crazy reason (like monitoring? How many transactions originated from a certain node?)

**Comment by fire** [comment]
@petermattis It uses a random multicast mac if you were not aware.

```uuid_generate_v1mc() 	

This function generates a version 1 UUID but uses a random multicast MAC address instead of the real MAC address of the computer.```

**Comment by bdarnell** [comment]
An important difference between the function proposed here and UUIDv1 is in the order of the components. UUIDv1 puts the MAC address first, while our proposal puts the timestamp first. If we're going to have a timestamp in the ID at all, I think it makes more sense to put it first for more control over data locality (If the high bits of the ID are random, there is little benefit to having a non-random component in the low bits)
