### ISSUE TITLE
roachtest: Test naming rules

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#25137]
Roachtests have names which are used for various purposes, including creating the artifact directories, and creating the test cluster names when used in CI. These two uses have different rules, and because local development often uses a mode that doesn't create a cluster per test, the stricter cluster naming rules are often not encountered until the test is merged to master. 

Specifically, cluster names have fairly short length limits (64 chars, of which teamcity uses ~17) and must be unique after most punctuation is stripped out (so you can't have two tests that differ only in punctuation such as a positive and negative value interpolated into the test name). 

We should either generate cluster names independently of the test name so it doesn't matter what you call the test or enforce the test cluster naming rules no matter how the test is being run.

Additionally, there is a convention for storing key/value pairs in the test such as a directory named `/nodes=5/`. How are these used? Should tests that are hard-coded to a specific number of nodes (such as the single-node clock monitoring tests) still include this? If we expect all tests to use this format we should document/enforce it.

**Comment by petermattis** [comment]
@bdarnell Do you know where the GCE machine length limit is specified? I can't find it looking right now, nor other restrictions on name characters. @benesch You added `makeClusterName` in 95d5faab72081f5bb684ad6a27bf18b38322c424, perhaps you know.

**Comment by petermattis** [comment]
Ah, I see if you use an invalid name, gcloud helpfully says:

```
Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)'
```
