### ISSUE TITLE
cli: error from last message is printed in interactive prompts on ^D

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#25136]
Look at how the error message for the preceding failing statement is reported a 2nd time when CTRL-D is pressed. Probably because some error that we return to Cobra. That's confusing when the prompt is run in interactive mode. And it does *not* happen when it's not run in interactive mode.

```
[andrei:~/work2/src/github.com/cockroachdb/cockroach] master+ ± ./cockroach demo
root@127.0.0.1:63136/demo> select gg;
pq: column name "gg" not found
root@127.0.0.1:63136/demo> ^D
*
* ERROR: pq: column name "gg" not found
*
Failed running "demo"
```

**Comment by knz** [comment]
Fixed in #26287.

(This was specific to `cockroach demo`)
