### ISSUE TITLE
importccl: support compressed csv files

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#25149]
Compression seems likely to effective on some CS-encoded datasets, so supporting CSV compression/decompression in `IMPORT` and `EXPORT` csv handling could allow for significantly smaller file size.

While our internal files often prefer Snappy compression, gzip/bzip seem like better candidates here, as they're more widely supported in commonly available tooling, and interop is the aim of `IMPORT` and `EXPORT`.

**Comment by mjibson** [comment]
Is this done?

**Comment by dt** [comment]
yes

**Comment by dt** [comment]
Implemented in https://github.com/cockroachdb/cockroach/pull/26796
