### ISSUE TITLE
sql: support ability to add columns after a certain other column

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#25167]
There has been a request to support syntax like `... ADD COLUMN ... AFTER previous_column`

Quote from Gitter request:

>Having an option to add a column at a specific position in a table is not mission critical, but when iterating fast (in terms of table changes), the ideal table structure and the production table structure start to differ a lot. Though makes it more confusing to prepare further updates. When also controlling column families as you always append new columns, the family for columns has to be incremented to a different position to not conflict in production.
>
>So the ideal solution for this would be if a column can be added to a certain position and also having the ability to change column families later on.

**Comment by vivekmenezes** [comment]
same as https://github.com/cockroachdb/cockroach/issues/7502
