### ISSUE TITLE
cli: prompted for a password when using certificate auth

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#25165]
When connecting to a secure cluster using `cockroach sql` as a non-root user, I'm prompted for a password even when I have a client certificate present:

```
rm -rf certs ca.key cockroach-data
./cockroach cert create-ca --certs-dir=certs --ca-key=ca.key
./cockroach cert create-node --certs-dir=certs --ca-key=ca.key localhost
./cockroach cert create-client --certs-dir=certs --ca-key=ca.key root
./cockroach cert create-client --certs-dir=certs --ca-key=ca.key foo
./cockroach start --certs-dir=certs --background
./cockroach user --certs-dir=certs set foo
./cockroach sql --certs-dir=certs --user=foo
^ prompts for a password
```

I'm eventually let in to the SQL console regardless of what password I provide. If I delete the client cert, I'm not. So it seems like the authentication is actually working properly—I'm just erroneously getting prompted for a password that will be ignored.

**Comment by mberhault** [comment]
Yeah, this was broken in https://github.com/cockroachdb/cockroach/pull/23725/files#diff-1444ad585f14a980f4f32a4ce4b3648dL457.

We used to check whether we had valid certificates for the user before prompting for the password. This got dropped. Reassigning to @knz.

**Comment by knz** [comment]
thanks for spotting this
