### ISSUE TITLE
verify mysqldump can be imported 

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/cockroach#25163]
[mysqldump](https://dev.mysql.com/doc/refman/8.0/en/mysqldump.html) can be used to export data from MySQL.  This data can be imported into CockroachDB using [import](https://www.cockroachlabs.com/docs/stable/import.html#main-content), 

File Format - tab and insert into values ....
FIELDS TERMINATED BY - single and multiple delimiter characters including x01 
ENCLOSED BY - test for `'`, `"`, `,` and newline in the data file
ESCAPED BY - test for `'`, `"`, `,` and newline in the data file
LINES TERMINATED BY - test for `'`, `"`, `,` and newline in the data file
NULL representation \N and NULL
BLOB

**Comment by dt** [comment]
yeah, that tool is buggy and doesn't work at all
