### ISSUE TITLE
kubernetes: secure multi-region deployments with routable pod IPs

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#25189]
Cockroachdb was designed with multi-region deployments in mind, but so far getting a cockroach cluster set up across multiple kubernetes clusters has been a difficult, manual process for which we've provided little guidance. Making this easier for users is an important priority.

This will be an extension of the insecure version of the same goal (https://github.com/cockroachdb/cockroach/issues/25188), but will need additional solutions for:

1. Creating/distributing node and client certificates that share a root certificate authority
1. Creating a persistent network identity for each pod across kubernetes clusters so that node certificates can be created with the persistent identities
1. Optimizing performance of cross-cluster communication (hopefully not needing to route everything through a `LoadBalancer` or `NodePort` kubernetes service).

**Comment by SJAnderson** [comment]
Hi there,

We’re (www.maestro.io) very interested in the outcome of this issue as we are in the middle of a migration to CRDB on a GKE statefulset deployment.

Ideally we’d like a 3-node per region deployment across us-west, us-central, and us-east. According to your docs this would allow for a whole region to go offline.

We’re about a month out from production, and some issues we’re currently facing and where you’re guides could do a better job of explaining are:
1. How to spin up a cluster in and a second region, and point the nodes to the first region and getting their certificates.
2. Doing step 1. without exposing each node to the public. I believe we could leverage google’s cloud networking to create a private virtual network between a number of regions, which would allow the nodes to see each other privately.
3. New user creation, it’s not very well documented how to get secure user certs (though I do believe I finally found the guide in the PDF email guide regarding GKE).
4. How to setup a multi-provider deployment. E.g. AWS, Alibaba, GCP. Those all have kubernetes deployments, and would allow our team to be confident about spanning to countries where GCP isn’t currently in (e.g. china).
5. Scaling up a stateful-set cluster across regions.

Looking forward to 2.1. In the meantime, does your team have any updates on secure multi-region deployments in GKE? From our findings we do not believe federated deployments are a viable option, we think the “easiest” way it could be done now is to expose each node’s IP to each other behind a private network or just to the public, then using an HTTP(S) loadbalancer for app traffic. Again, this is all just a theory as we get as far as deploying the second cluster and cannot figure out this to get their certificates generated.

**Comment by SJAnderson** [comment]
Posted on the forums with some of our findings [here](https://forum.cockroachlabs.com/t/secure-multi-region-kubernetes-deployment-recommendations/1633)

**Comment by a-robinson** [comment]
Responded on the forum. Thanks for your initial legwork and reporting your progress so clearly.
