### ISSUE TITLE
expose stats in graphite format

### ISSUE THREAD

**Issue by neeral** [cockroachdb/cockroach#25198]
Metrics are currently available for monitoring from Prometheus. Some clusters don't have Prometheus and are already running a different monitoring tool (in my case, Graphite). The Prometheus format can be converted into Graphite-format, using prometheus' library, and pushed to the graphite server.

This is a must-have to allow monitoring of production clusters which have Graphite and not Prometheus.

**Comment by tschottdorf** [comment]
Done in #25227.
