### ISSUE TITLE
importccl: add EXPORT option to write schema to file

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#25204]
`IMPORT` supports reading its `CREATE TABLE` statement from a file, so adding an option to `EXPORT` that writes a compatible `CREATE TABLE`  to a file would make round-tripping easier.

NB: to be round-trip compatible with `IMPORT`, such a `CREATE TABLE` cannot contain FK constraints. Additionally,`EXPORT` can dump arbitrary query results, not just individual tables, so it isn't obvious that the dumped schema is a `SHOW CREATE TABLE` of some existing table at all, but rather maybe just synthesized from the column types (similar to the logic in `CREATE AS` or view creation)

**Comment by devdil** [comment]
@dt can I pick this issue up?

**Comment by asheikm** [comment]
> `IMPORT` supports reading its `CREATE TABLE` statement from a file, so adding an option to `EXPORT` that writes a compatible `CREATE TABLE` to a file would make round-tripping easier.
> 
> NB: to be round-trip compatible with `IMPORT`, such a `CREATE TABLE` cannot contain FK constraints. Additionally,`EXPORT` can dump arbitrary query results, not just individual tables, so it isn't obvious that the dumped schema is a `SHOW CREATE TABLE` of some existing table at all, but rather maybe just synthesized from the column types (similar to the logic in `CREATE AS` or view creation)

@dt shall I take it if no one is working on it

**Comment by shermanCRL** [comment]
Still desirable, will keep it in the backlog.
