### ISSUE TITLE
build: make errors out on docgen.d

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#25201]
```
kena@kenabook ~/cockroach % make buildshort
GOPATH set to /home/spill/go
bin/docgen.d:1197: *** missing separator.  Gestopt.
```

Indeed, at line 1197 in docgen.d:

```
pkg/sql/sem/tree/.#datum.go:
```

The generator should skip over known file names for editor temporary files, including anything matching:

```
.*
#*
```

**Comment by benesch** [comment]
Huh, I'm kind of torn about this. The fact that prereqs is outputting ".#datum.go" means that the Go build system is including it in the build! If anything it's Go that needs to omit such files. Or your editor needs to be reconfigured to change the extension on its temporary files.

That said, prereqs should escape filenames with special characters. I'm happy to make that change. But I'm still confused why this isn't causing you more trouble at the Go compiler level. Are these temporary files empty?

**Comment by knz** [comment]
No they're not empty. Perhaps one command is listing them as part of the build and another is ignoring them automatically? 

This is the standard naming convention with emacs. Somehow I'd be surprised if the Go team didn't cater for emacs users. I do not see any instruction online that emacs needs a custom configuration to work with Go.

**Comment by benesch** [comment]
Yeah, I’ll look to see if the compiler has a special case for Emacs-looking
temp files. (And if so: 🙄. The internals of the Go tool are not properly
exposed in the build package.)

**Comment by benesch** [comment]
Hmm. https://github.com/golang/go/commit/592c97fc8f55d65dc668b1acb3b5bdf46e851f9e
