### ISSUE TITLE
backup: import/tpcc/warehouses=1000/nodes=4 roachtest timed out (hung?)

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#25221]
The test log is [here](https://teamcity.cockroachdb.com/repository/download/Cockroach_Nightlies_WorkloadNightly/633729:id/import/tpcc/warehouses%3D1000/nodes%3D4/test.log). The full artifacts are [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=633729&buildTypeId=Cockroach_Nightlies_WorkloadNightly&tab=artifacts#!10xtn3b,cj3jqrjcsqw,-n0phwjo351ep,-19l7dvgrojye8).

The logs simple show:

```
MONITOR: 4: dial tcp 35.184.215.65:22: connect: connection refused
MONITOR: 2: dial tcp 35.193.226.1:22: connect: connection refused
MONITOR: 3: dial tcp 35.194.42.49:22: connect: connection refused
MONITOR: 1: dial tcp 35.184.61.131:22: connect: connection refused
Error:  dial tcp 35.184.61.131:22: connect: connection refused
```

@mberhault Tracked down that the nodes in the cluster were destroyed via the GCE API, presumably the GC cronjob to destroy expired clusters.

**Comment by mjibson** [comment]
I'm not sure what to do here. I have not seen this test before and I can't see anything in the logs that looks useful. The log has:

```
Nightlies_Roachtest_Nightly_272.log:1200:[01:37:14] :	 [Step 3/3] [  10] import/tpcc/warehouses=1000/nodes=4: creating cluster (1m4s)
Nightlies_Roachtest_Nightly_272.log:1211:[01:38:14] :	 [Step 3/3] [  11] import/tpcc/warehouses=1000/nodes=4: uploading binary (26s)
Nightlies_Roachtest_Nightly_272.log:1216:[01:39:14] :	 [Step 3/3] [  12] import/tpcc/warehouses=1000/nodes=4: ??? (0s)
```

Which make it appear that after uploading the binary nothing started.

**Comment by petermattis** [comment]
There are a lot of those `???` lines in the log. The `???` is a marker used by roachtest to indicate it doesn't know what stage the test is at. Something actionable to do here is to improve the logging by sprinkling `t.Status` and `t.WorkerStatus` messages in the test so that if this happens again we get an indication of where the test hung.

**Comment by mjibson** [comment]
I don't think the test proper even started then because there is a `t.Status("starting csv servers")` line way high up. This failed during c.Put (which runs `c.status("uploading binary")`). Have other tests observed this kind of failure before?

**Comment by petermattis** [comment]
Hmm, that's a good point about `starting csv servers`. What's curious is that the `test.log` shows the the csv servers line should have been run:

```
roachprod run teamcity-633729-import-tpcc-warehouses-1000-nodes-4:1-4 -- ./workload csv-server --port=8081 &> logs/workload-csv-server.log < /dev/null &
...
```

Each of the dots in that output represents 1s. So the total is 44511, or 12.36h. Something must have hung running that `roachprod run` command which is curious because we're running `workload csv-server` in the background. Seems like this is a test infrastructure failure and not something specific to the test.

**Comment by petermattis** [comment]
This is happening pretty reliably. I'm taking another look.

**Comment by petermattis** [comment]
The problem is this line:

```
c.Run(ctx, c.All(), `./workload csv-server --port=8081 &> logs/workload-csv-server.log < /dev/null &`)
```

For some reason that line of code never returns. I can see that the `workload csv-server` command is being run on every node, but the `roachprod` command isn't returning despite the `&`. Easily reproducible outside of a test.
