### ISSUE TITLE
Replace RocksDB with FoundationDB

### ISSUE THREAD

**Issue by magaldima** [cockroachdb/cockroach#25222]
**FEATURE REQUEST**
Now that FoundationDB is open source again, how difficult would it be to use CockroachDB's SQL layer on top of FoundationDB's K/V store?

There seems to be a lot of interest in the FoundationDB forum for this and it seems like there could be a lot of overlap since CockroachDB is already using a sorted key-value store.

**Comment by jazoom** [comment]
I don't know what OP had in mind, and I don't know much about database engineering in general, but I think some of the excitement over FoundationDB is that multiple databases can sit atop the same key-value store. So you could set up one cluster and have a SQL database, a search database, a key-value database, a graph database, etc. all running on the same distributed cluster.

**Comment by petermattis** [comment]
@jazoom Thanks for the additional color, though it doesn't change my response that using CockroachDB's SQL layer on top of FoundationDB would be very difficult.
