### ISSUE TITLE
sql: SELECT DISTINCT can lead to out of memory.

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#2524]
Make two changes to the current implementation:
1. Only hold on to the last result checksum when the results are sorted by result or the DISTINCT ON expressions.
2. return error to user when using a map and the size of the map exceeds a threshold. Request user to use ORDER BY to allow use of DISTINCT.

**Comment by petermattis** [comment]
I'm not sure if this is worth fixing before beta. Note that a simple `SELECT * FROM t` can also lead to out of memory as we buffer all of the key-value pairs and the results in memory.

**Comment by petermattis** [comment]
The DISTINCT ON expressions should also be used for index selection if no ORDER BY clause is present. That is, we should use the DISTINCT ON expressions to bump the weight of an index that returns those expressions in sorted order. We already use ORDER BY expressions to affect index selection, so the path to do this should be clear.

**Comment by vivekmenezes** [comment]
I'd like to implement this for Beta because folks are likely to use a proper ordering when using this and it will be nice to not use up even more memory to do this. Also when folks use a proper ordering they do expect the memory requirements to go down. It's very embarrassing to have to explain what we do!

Besides we've already figured out what we need to do here.

**Comment by petermattis** [comment]
I'm not sure some of the assumptions here (that DISTINCT is used frequently enough to matter for beta and that folks will already be ordering correctly when using DISTINCT), but ok. Given that this is optimization work, it should be prioritized below the remaining feature work. But we certainly may have time to get it done before beta.

**Comment by bdarnell** [comment]
Postgres requires that when DISTINCT ON is used, the results are sorted by that expression (if there is also an ORDER BY clause, the DISTINCT ON expression must be the first thing in it. If there is none, DISTINCT ON X appears to imply ORDER BY X). I think we're safe implementing DISTINCT in such a way that it only has to look at adjacent rows.

**Comment by tamird** [comment]
Pinging some SQL homies that might want to look at this: @RaduBerinde @paperstreet @dt

**Comment by dt** [comment]
we already do #1.

**Comment by dt** [comment]
distinct splits the encoded values into a prefix that contains those that are ordered and a suffix of the rest, and while iterating, it checks the prefix first, so a fully-ordered distinct should use o(1) space for the distinct overhead.

**Comment by tamird** [comment]
> Postgres requires that when DISTINCT ON is used, the results are sorted by that expression (if there is also an ORDER BY clause, the DISTINCT ON expression must be the first thing in it. If there is none, DISTINCT ON X appears to imply ORDER BY X).

Sounds like we just need to confirm that we do this, and then this is good to close.

**Comment by dt** [comment]
we don't require that it.

**Comment by dt** [comment]
I think we can close this particular issue as is: the optimization suggested is implemented if the user chooses to use it. While as far as resource limits, i don't think we want to take an ad-hoc approach, but rather we should approach that in a more holistic way, probably _after_ distributed is implemented.

**Comment by tamird** [comment]
Why not implement the same requirement as postgres?

**Comment by dt** [comment]
> The ORDER BY sort is in memory too, so we're potentially just pushing the problem around if we add the appears as prefix of ORDER BY restriction.

**Comment by tamird** [comment]
That's true, but I don't see the downside to narrowing the constraints on DISTINCT.

**Comment by dt** [comment]
If your data *does* fit in whatever amount of ram you have but isn't ordered, you've added and nlogn sort when you didn't need it. If it doesn't fix, then the sort won't work anyway.  It just doesn't seem to buy us anything yet -- maybe once we have an on-disk or distributed sort, it'd make more sense to add it or something else, but it seems premature to throw ad-hoc restrictions in now that don't buy us much.

**Comment by spencerkimball** [comment]
@knz, is this closeable? Could you determine whether this is still milestone 1.0, unassign yourself and assign someone else if necessary?

**Comment by knz** [comment]
This specific issue was actually fixed by #7608.
