### ISSUE TITLE
sql/pgwire: large insert into a JSON column is causing a lost connection and error

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#25278]
A poster on Gitter has noted that creating a large insert causes a lost client connection.

The conversation is copied below:

> Erich Ocean @erichocean
> I'm getting a large number of "Connection terminated unexpectedly" errors happening talking to my cluster.
> Is there a way to tell if it's CockroachDB that is closing the connections?
> 
> Erich Ocean @erichocean 07:20
> The underlying error is `write EPIPE` on the client side.
>
> Erich Ocean @erichocean 08:15
> I think I've tracked it down to the SQL being sent over the wire being too large for Cockroach to handle.
>
> rytaft @rytaft 09:40
> @erichocean can you give some more details? Is the "Connection terminated unexpectedly" error happening just after you send a SQL query? And how big is the SQL query you are sending?
>
> Erich Ocean @erichocean 09:40
> I suspect they're in the 8MB range
> big single statement inserts
> huge json columns 
> it would have helped with debugging if instead of just dropping the connection, CRDB returned something like "SQL Statement too big" or whatever.
>
> rytaft @rytaft 09:44
> Definitely - sorry you're running into this issue. I'm checking to see if there is a limit on the size of a single statement.
>
> rytaft @rytaft 09:49
> @erichocean this might take some time for me to track down. But in the mean time, could you take a  look at the log and see if you can find a specific error? It's probably a file called cockroach-data/logs/cockroach.log
> if you see a panic somewhere towards the end of the log that could be the culprit
>
> Erich Ocean @erichocean 09:53
> @rytaft grepping for panic didn't find anything
> 
> rytaft @rytaft 09:53
> https://www.cockroachlabs.com/docs/stable/known-limitations.html#write-and-update-limits-for-a-single-statement contains the actual limits on the size of inserts
> Is there any chance you are exceeding 64MiB?
>
> Erich Ocean @erichocean 09:56
> it's possible, yeah
>
> rytaft @rytaft 09:57
> You can try increasing `kv.raft.command.max_size` and see if that fixes the problem
>
> Erich Ocean @erichocean 09:57
> I'm using smaller batches now, if anything, I'd just like to get an error vs. losing the connection.
>
> rytaft @rytaft 09:58
> Did the smaller batches fix the issue?
>
> Erich Ocean @erichocean 09:58
> when you lose the connection without an error, it's hard to know why
> yeah

**Comment by rytaft** [comment]
The user is running cluster version v2.0.0
Also, clarified that it wasn't a crash, just a lost connection with a weird error

**Comment by knz** [comment]
@andreimatei any thoughts about what may be causing this?

**Comment by andreimatei** [comment]
No clue. One thing I'd try is run with `--vmodule=conn_executor=2` and see if we get any errors in the logs then. There might be an opportunity to improve our logging here.
Otherwise, repro instructions would be great.

**Comment by jordanlewis** [comment]
No repro.
