### ISSUE TITLE
ci: should assert that branch contains no merges

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#25275]
Such a commit slipped in in https://github.com/cockroachdb/cockroach/pull/24469. It's not obvious unless you look at the "Commits" tab, but for smaller PRs I don't routinely do so.

cc @petermattis for dev infrastructure triage.

**Comment by petermattis** [comment]
@jordanlewis or @benesch How hard is this to do? Is this something we'd do in `teamcity-check.sh`?

**Comment by jordanlewis** [comment]
I think this would be pretty straightforward. You could assert that there's no output of `git log --merges master..HEAD` (or s/master/the target branch/). And `teamcity-check.sh` seems like a decent place to put this, yes.

**Comment by benesch** [comment]
Just make sure that whatever you do will handle the case of a build on
master. (I think `git log --merges master..HEAD` will properly return
nothing if HEAD is master, but best to be sure.)

**Comment by knz** [comment]
just curious what's the trouble with a branch containing merges?

**Comment by petermattis** [comment]
@tschottdorf I don't particularly care about this. Do you still care? It doesn't seem to be a frequent problem.

**Comment by tschottdorf** [comment]
I still think that we shouldn't merge merges, but it also doesn't seem to be something that happens.

@knz the "trouble" with it is that in all instances I've seen it's someone committing a messy git history, which is then troublesome to work with as you run into it later.
