### ISSUE TITLE
make lint: How to set TIMEOUT longer?

### ISSUE THREAD

**Issue by sydnever** [cockroachdb/cockroach#25271]
**QUESTION**
![656794657](https://user-images.githubusercontent.com/2542184/39561780-79432ccc-4eda-11e8-9a95-b7d646100516.jpg)

**Comment by jordanlewis** [comment]
The Makefile currently doesn't allow customizing the timeout of the lint tests. You can do it manually by adding a timeout flag inside the makefile under the lint target, if you really want.

I'd suggest using `make lintshort` to run a shorter subset of the lint tests. You shouldn't need to run the full suite normally - if you're looking to contribute a patch, when you upload the patch, our CI server will run these tests for you.
