### ISSUE TITLE
build: CI for new roachtests

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#25286]
We've had a few instances recently in which freshly merged roachtests were either flaky, or downright broken. This isn't unexpected: while developing the test, you'll usually use `--local` mode, and the roachtest doesn't even get run during CI (and in the near future, if it got run, it would be in local mode again). A roachtest passing in local mode does not imply that it will pass in remote mode. In fact, most tests turn into a shell of their former self when run locally, sometimes not much more than a sanity check.

An idea for this floated by @nvanbenschoten and @benesch is introducing a nursery: a newly merged test doesn't count as "seriously merged" until it has passed reliably for some amount of time, at which point it graduates. This could work, but it seems like a poor substitute for proper CI.

We're making it easier to run these in remote mode multiple times (https://github.com/cockroachdb/cockroach/issues/25284) but in the medium term we should really have a CI hook that runs the test "for real". Since it's expensive and time-consuming to run a roachtest for every time a PR is pushed, this would have to be a bors-only type run. This comes with its own oddities: bors serializes all writes, so if running the roachtest takes 12h, then all merges will be blocked until then. This might be acceptable as a first pass, perhaps for long-running tests can skip this in CI and run it manually out-of-band before merging.

@petermattis I put this into CF&S but only because I don't see a Dev Infra project. Is assigning you the right thing to do? Edit: marked as A-build-system and removed from CF&S.

**Comment by petermattis** [comment]
Here's another thought: we write a CI check that looks for a new roachtest and fails the build unless the commit message contains a known string (e.g. `roachtest run OK`). The CI failure would indicate that the author should run the roachtest remotely (local is not sufficient) and then add that known string to the commit message. 

> An idea for this floated by @nvanbenschoten and @benesch is introducing a nursery: a newly merged test doesn't count as "seriously merged" until it has passed reliably for some amount of time, at which point it graduates. This could work, but it seems like a poor substitute for proper CI.

Where would we keep this "passed reliably for some amount of time" state? Would this be something flagged in the code, or something that the CI system maintains?

**Comment by nvanbenschoten** [comment]
> I was thinking it would be incumbent upon the test author to graduate their roachtest out of the nursery.

Yes, this is what I was thinking as well. Whoever introduces the test should own it and care for it at least until it graduates into a full-blown roachtest. It's doesn't make sense to be moving responsibility around for a test that was recently created by someone else.

We could add a `Nursery` flag on testSpecs and run them separately from the other tests at night. This will allow us to make non-nursery test failures a lot louder. In order to remove the flag, the original author will need to show some past history demonstrating the absence of flakes.

**Comment by benesch** [comment]
Yeah, I think the benefits of a nursery over the options are a) it is maybe
an hour’s worth of code changes, and b) it won’t require the test author to
repeatedly manually run their test before merging. Even with a count flag
it’s still annoying to have to keep your laptop connected or start a screen
session on a GCE worker.
