### ISSUE TITLE
importccl: IMPORT TABLE statement returns incorrect count of imported rows

### ISSUE THREAD

**Issue by tim-o** [cockroachdb/cockroach#25293]
**BUG REPORT**

**Version Data:**
Tims-MBP:cockroachdb-training tim-o$ cockroach version
Build Tag:    v2.0.1
Build Time:   2018/05/02 21:09:24
Distribution: CCL
Platform:     darwin amd64 (x86_64-apple-darwin17.5.0)
Go Version:   go1.10.1
C Compiler:   4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)
Build SHA-1:  c92bc6e912880c28c0784d3208583fb27f482f76
Build Type:   development

**2. Please describe the issue you observed:**

**- What did you do?**
Attempted to import a 185k row long file. Here are steps to reproduce:

**A. Download & check length of input file:**

Tims-MBP:cockroachdb-training tim-o$ curl 'https://storage.googleapis.com/cockroach-fixtures/tpch-csv/sf-1/orders.tbl.1' > orders.tbl.1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 20.3M  100 20.3M    0     0  20.3M      0 --:--:-- --:--:-- --:--:-- 20.3M
Tims-MBP:cockroachdb-training tim-o$ wc -l orders.tbl.1
  187500 orders.tbl.1

**2. Import file, note row count:**

Tims-MBP:cockroachdb-training tim-o$ ./cockroach sql --insecure --database="import_test" --execute="IMPORT TABLE orders CREATE USING 'https://storage.googleapis.com/cockroach-fixtures/tpch-csv/schema/orders.sql' CSV DATA ('https://storage.googleapis.com/cockroach-fixtures/tpch-csv/sf-1/orders.tbl.1') WITH delimiter = '|';"
+--------------------+-----------+--------------------+------+---------------+----------------+-------+
|       job_id       |  status   | fraction_completed | rows | index_entries | system_records | bytes |
+--------------------+-----------+--------------------+------+---------------+----------------+-------+
| 345073226364846081 | succeeded |                  1 |    0 |             0 |              0 |     0 |
+--------------------+-----------+--------------------+------+---------------+----------------+-------+
(1 row)

Note rows & index entries = 0.

**3. Confirm that imported table is not empty:**

Tims-MBP:cockroachdb-training tim-o$ cockroach sql --insecure
...
root@:26257/> select count(*) from import_test.orders;
+--------+
| count  |
+--------+
| 187500 |
+--------+

**- What did you expect to see?**

Output of the IMPORT TABLE statement should match the # of rows imported into the table.

**- What did you see instead?**
IMPORT table indicated 0 rows were imported, when actual count imported was 187,500.

**Comment by jordanlewis** [comment]
Oh, thanks for filing this! I also noticed this when I was giving the training with @benesch a few weeks ago, but forgot to file an issue.

**Comment by jordanlewis** [comment]
cc @mjibson

**Comment by mjibson** [comment]
Yes, this is currently known. It's not a bug in that it's broken, we just never implemented it. Clearly a ux surprise though.

**Comment by dt** [comment]
28469
