### ISSUE TITLE
acceptance: TestClusterRecovery is flaky

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#25291]
Timed out on this TC run: https://teamcity.cockroachdb.com/viewLog.html?buildId=639637&buildTypeId=Cockroach_UnitTests

Attaching all the artifacts.

[Cockroach_GitHub_CI_39452_artifacts.zip](https://github.com/cockroachdb/cockroach/files/1972602/Cockroach_GitHub_CI_39452_artifacts.zip)

cc @tschottdorf for your collection

**Comment by tschottdorf** [comment]
The test is stuck waiting for node 1 to return to serving, I think. Its log shows messages like

> W180503 18:34:54.281296 38 kv/dist_sender.go:1301  [n1] have been waiting 1m0s sending RPC to r4 (currently pending: [(n1,s1):1]) for batch: Scan [/System/"system-version/",/System/"system-version0")
W180503 18:34:54.282086 278 storage/replica.go:1487  [n1,s1,r4/1:/System/{NodeLive…-tsd}] have been waiting 1m0s attempting to acquire lease
W180503 18:34:54.283006 265 storage/replica.go:1487  [n1,s1,r4/1:/System/{NodeLive…-tsd}] have been waiting 1m0s attempting to acquire lease
W180503 18:34:54.283042 247 kv/dist_sender.go:1301  [summaries,n1] have been waiting 1m0s sending RPC to r4 (currently pending: [(n1,s1):1]) for batch: Put [/System/StatusNode/1,/Min)
W180503 18:34:54.677520 57 storage/replica.go:1487  [replicate,n1,s1,r21/1:/Table/5{0-1}] have been waiting 1m0s attempting to acquire lease
W180503 18:34:54.677557 285 storage/replica.go:1487  [replica consistency checker,n1,s1,r21/1:/Table/5{0-1}] have been waiting 1m0s attempting to acquire lease
E180503 18:34:54.678072 492 storage/queue.go:778  [replicate,n1,s1,r8/1:/Table/1{1-2}] no removable replicas from range that needs a removal: [raft progress unknown]
W180503 18:34:59.832332 388 storage/replica.go:1487  [n1,s1,r4/1:/System/{NodeLive…-tsd}] have been waiting 1m0s attempting to acquire lease
I180503 18:35:04.279435 245 server/status/runtime.go:219  [n1] runtime stats: 185 MiB RSS, 196 goroutines, 110 MiB/544 KiB/125 MiB GO alloc/idl

> E180503 18:49:58.539421 2393 storage/queue.go:778  [replicate,n1,s1,r8/1:/Table/1{1-2}] range requires a replication change, but lacks a quorum of live replicas (2/3)

It's not clear if quorum is actually lost. The other nodes, in the meantime, have this:

> W180503 18:49:56.031215 11503 vendor/google.golang.org/grpc/clientconn.go:1158  grpc: addrConn.createTransport failed to connect to {127.0.0.1:33427 0  <nil>}. Err :connection error: desc = "transport: Error while dialing cannot reuse client connection". Reconnecting...
W180503 18:49:56.031278 11503 vendor/google.golang.org/grpc/clientconn.go:830  Failed to dial 127.0.0.1:33427: context canceled; please retry.
W180503 18:49:56.077211 11606 vendor/google.golang.org/grpc/clientconn.go:1158  grpc: addrConn.createTransport failed to connect to {127.0.0.1:33427 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:33427: connect: connection refused". Reconnecting...
W180503 18:49:57.077130 11606 vendor/google.golang.org/grpc/clientconn.go:1158  grpc: addrConn.createTransport failed to connect to {127.0.0.1:33427 0  <nil>}. Err :connection error: desc = "transport: Error while dialing cannot reuse client connection". Reconnecting...
W180503 18:49:57.077203 11606 vendor/google.golang.org/grpc/clientconn.go:830  Failed to dial 127.0.0.1:33427: context canceled; please retry.
W180503 18:49:57.138621 11621 vendor/google.golang.org/grpc/clientconn.go:1158  grpc: addrConn.createTransport failed to connect to {127.0.0.1:33427 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:33427: connect: connection refused". Reconnecting...
W180503 18:49:58.138620 11621 vendor/google.golang.org/grpc/clientconn.go:1158  grpc: addrConn.createTransport failed to connect to {127.0.0.1:33427 0  <nil>}. Err :connection error: desc = "transport: Error while dialing cannot reuse client connection". Reconnecting...
W180503 18:49:58.138750 11621 vendor/google.golang.org/grpc/clientconn.go:830  Failed to dial 127.0.0.1:33427: context canceled; please retry.
W180503 18:49:58.231193 11625 vendor/google.golang.org/grpc/clientconn.go:1158  grpc: addrConn.createTransport failed to connect to {127.0.0.1:33427 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:33427: connect: connection refused". Reconnecting...

They all seem to have booted up fine, though. Not quite sure what to make of this yet. @bdarnell, any ideas?

**Comment by bdarnell** [comment]
In this test the nodes are started up on different ports on each restart, so these RPC errors are from trying to connect to the old incarnation of node 1. This could be a red herring (the old address has stuck around in gossip persistence) or it could mean that the restarted node 1 isn't broadcasting its new node descriptor (or the other nodes aren't receiving/processing it).

I wonder if this could be the same gossip partition as #24753. cc @a-robinson

**Comment by a-robinson** [comment]
> I wonder if this could be the same gossip partition as #24753. cc @a-robinson

Yeah, it certainly looks like it:

n1:
```
I180503 18:49:54.278969 242 gossip/gossip.go:488  [n1] gossip status (ok, 4 nodes)
gossip client (1/3 cur/max conns)
  4: 127.0.0.1:34545 (16m0s: infos 49/6064 sent/received, bytes 12704B/689412B sent/received)
gossip server (0/3 cur/max conns, infos 49/6064 sent/received, bytes 12704B/689412B sent/received)
```

n4:
```
I180503 18:48:49.815352 29 gossip/gossip.go:488  [n4] gossip status (ok, 4 nodes)
gossip client (0/3 cur/max conns)
gossip server (1/3 cur/max conns, infos 5656/217 sent/received, bytes 646471B/196003B sent/received)
  1: 127.0.0.1:34449 (14m56s)
```

n3:
```
I180503 18:49:49.797706 71 gossip/gossip.go:488  [n3] gossip status (ok, 4 nodes)
gossip client (0/3 cur/max conns)
gossip server (1/3 cur/max conns, infos 274/221 sent/received, bytes 90605B/71409B sent/received)
  2: 127.0.0.1:42359 (15m56s)
```

n2
```
I180503 18:49:53.220831 110 gossip/gossip.go:488  [n2] gossip status (ok, 4 nodes)
gossip client (1/3 cur/max conns)
  3: 127.0.0.1:33055 (15m59s: infos 78/268 sent/received, bytes 32353B/49508B sent/received)
gossip server (0/3 cur/max conns, infos 89/347 sent/received, bytes 34118B/83261B sent/received)
```

**Comment by tschottdorf** [comment]
👍 thanks @a-robinson.
