### ISSUE TITLE
sql: some users of the InternalExecutor could benefit from results streaming / mem accounting

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#25302]
#23690 unified several APIs that we used to have with a new and improved `InternalExecutor`. One of the old API's - `executor.ExecStmtBuffered()` provided memory accounting for the accumulated results (although as far as I can tell all the users were providing an unbounded monitor, so the feature was of little use).
Anyway, the new API currently doesn't provide memory account. It could. It could even provide a streaming interface for the results, probably, to avoid accumulating too many in memory in the first place. In either case, the `InternalExecutor` would need to get a `Query()` method that returns something with a `Close()` method.
Rafa claims that there's uses that could potentially produce many rows, so these things could be useful.

**Comment by yuzefovich** [comment]
closing in favor of #48595
