### ISSUE TITLE
sql/pgwire: each line in `COPY FROM stdin` input gets split into multiple 8KiB records

### ISSUE THREAD

**Issue by briancline** [cockroachdb/cockroach#25306]
I originally asked around in Gitter on 23 April before I went down this rabbit hole -- sorry it took so long to write this up, but it will become evident why.

**BUG REPORT**

1. First few lines of output:

```
I180502 16:40:13.587235 455 util/log/clog.go:1001  [config] file created at: 2018/05/02 16:40:13
I180502 16:40:13.587235 455 util/log/clog.go:1001  [config] running on machine: ws01db01
I180502 16:40:13.587235 455 util/log/clog.go:1001  [config] binary: CockroachDB CCL v2.0.0 (x86_64-unknown-linux-gnu, built 2018/04/03 20:56:09, go1.10)
I180502 16:40:13.587235 455 util/log/clog.go:1001  [config] arguments: [/opt/cockroach/bin/cockroach start --insecure --advertise-host ws01db01-svc.dev.example.com --host ws01db01-svc.dev.example.com --http-host ws01db01.dev.example.com --locality country=us,region=dal,datacenter=dal12,serverroom=sr01,rack=rk260 --max-sql-memory 8GiB --pid-file /var/run/cockroachdb.pid --store path=/data/crdb,attrs=hdd:raid10,size=6TiB --log-dir /var/log/cockroach --log-dir-max-size 10GiB]
```
```
I180502 20:49:43.240006 141 util/log/clog.go:1001  [config] file created at: 2018/05/02 20:49:43
I180502 20:49:43.240006 141 util/log/clog.go:1001  [config] running on machine: ws01db02
I180502 20:49:43.240006 141 util/log/clog.go:1001  [config] binary: CockroachDB CCL v2.0.0 (x86_64-unknown-linux-gnu, built 2018/04/03 20:56:09, go1.10)
I180502 20:49:43.240006 141 util/log/clog.go:1001  [config] arguments: [/opt/cockroach/bin/cockroach start --insecure --advertise-host ws01db02-svc.dev.example.com --host ws01db02-svc.dev.example.com --http-host ws01db02.dev.example.com --locality country=us,region=dal,datacenter=dal12,serverroom=sr01,rack=rk260 --max-sql-memory 8GiB --pid-file /var/run/cockroachdb.pid --store path=/data/crdb,attrs=hdd:raid10,size=6TiB --log-dir /var/log/cockroach --log-dir-max-size 10GiB --join ws01db01-svc.dev.example.com:26257]
```
```
I180502 20:25:41.429271 136 util/log/clog.go:1001  [config] file created at: 2018/05/02 20:25:41
I180502 20:25:41.429271 136 util/log/clog.go:1001  [config] running on machine: ws01db03
I180502 20:25:41.429271 136 util/log/clog.go:1001  [config] binary: CockroachDB CCL v2.0.0 (x86_64-unknown-linux-gnu, built 2018/04/03 20:56:09, go1.10)
I180502 20:25:41.429271 136 util/log/clog.go:1001  [config] arguments: [/opt/cockroach/bin/cockroach start --insecure --advertise-host ws01db03-svc.dev.example.com --host ws01db03-svc.dev.example.com --http-host ws01db03.dev.example.com --locality country=us,region=dal,datacenter=dal12,serverroom=sr01,rack=rk260 --max-sql-memory 8GiB --pid-file /var/run/cockroachdb.pid --store path=/data/crdb,attrs=hdd:raid10,size=6TiB --log-dir /var/log/cockroach --log-dir-max-size 10GiB --join ws01db01-svc.dev.example.com:26257]
```

---

2. Please describe the issue you observed:

- What did you do?
Attempted to import a sql file exported by `pg_dump` which uses tab-separated `COPY FROM stdin` values to import about 900k rows to a single 6-column table. The command used was:
```psql -p 26257 -h $SVC_IP -d wstest -U root -f testdump.sql```

- What did you expect to see?
A successful import of the table's data without errors, preferably with a smile (minus the obvious harmless errors for various `SET` statements at the top of psql's dumps).

- What did you see instead?
CRDB churned through all the things, as it consumed a few cores and took about 20sec, responding afterwards with this error:
```ERROR:  expected 6 values, got 1```

Using the same command to restore to a Postgres instance reports no errors, and the record looks as expected in the Postgres table.

---

3. Optionally write a novella about further findings:

I dug in quite a bit further, with the noble--but unsuccessful--desire to fix this bug myself, before I realized how deep it actually was. I also wasn't knowledgeable enough about how specifically you guys might prefer this to be handled, seeing as parts of the fix may have a potential performance impact.

I tried a variety of things but in the end what I found on a complete whim was that the inserts all worked fine and the full transaction completed successfully if I trimmed each line of `COPY` input to 8191 bytes. (In my case, the 6th table column is the lengthy one, so trimming still kept each line to 6 column values).

Essentially, everything from column 8192 onward was being treated as though it were a separate line of input. Here is the rough sequence of events for an ~8.1KiB line:
1. Column values for each COPY line are read through 8191 bytes
2. Column values successfully inserted
3. Data from 8192 onward parsed as a separate record, as though it were on its own line

So, not dropped entirely, but put into a separate buffer even before reaching `copyMachine.addRow`. Therefore the `expected 6 values, got 1` error is not in reference to the [0, 8192) buffer, but instead finding no other columns to parse out from the second [8192, eol] buffer. (Note: because of what I found below, I expect this occurs at every 8K boundary, not just the first one; but to be clear, I did not test that nuance specifically. Seems Plausible™.)

I modified several `copyMachine` methods in `cockroach/pkg/sql/copy.go` to add a number of log statements so I could see exactly what was in the buffer and how long it was at a number of junctures in the process. Eventually, though, I couldn't find much wrong here - it seemed like the issue was further down in `cockroach/pkg/sql/pgwire/pgwirebase/encoding.go`. I even went so far as to modify some of the buffer allocation sizes, albeit fruitlessly. Ultimately, while `io.ReadFull` was the one returning 8K buffer windows, it appears that the `ReadBuffer.ReadUntypedMsg` method from which it is called also does not account for this sort of scenario specifically.

Later, after a brief cursory reading of the pgwire protocol, which I am otherwise _completely_ unfamiliar with, I added log output to `ReadUntypedMsg` show me exactly how many bytes the protocol was actually indicating in the first 4 bytes of each buffer. For the first 8K of the line, it indicated 0x2003 (8195), and interestingly the [8192, eol] buffer had its own pgwire-prescribed size of 0x79 (121) -- obviously exceeding the actual 8K mark and clearly a separate message. So mayhaps `psql` is deliberately sending these in 8K increments to keep from getting a bit too rowdy with its own buffer sizes, and possibly signaling in a separate typed message what the real length is, or whether or not it's actually a complete record?

I didn't have adequate beer, etc. to proceed any further down the rabbit hole, so that's about where I stopped - clearly someone more knowledgeable than me will have to take the reins on a fix here. 😃

If you'd like a copy of the same one-row sql dump I tested with, you can find it here:
https://gist.github.com/briancline/e74dfce4e064ae165122c0b32120f1c5

(CC: @knz - by his/her request in Gitter)

**Comment by andreimatei** [comment]
I'm looking at this now. Like Brian was hinting, the problem is that the psql client breaks up rows over 8191 bytes into multiple protocol messages (something that the protocol spec explicitly allows it to do) and crdb doesn't expect rows to straddle messages.
Trying to do something about it.

**Comment by andreimatei** [comment]
Sent out a small fix. I'll probably backport it into the next 2.0.x release.
Sorry for taking so long to get back to this and thanks again for the report!
