### ISSUE TITLE
roachtest: add -count flag to run tests multiple times

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#25303]
We should introduce a new `-count` flag to roachtest. Similar to the `-count` flag supported by `go test`, this flag will run each matching test `n` times. This is a small change, but it will make it easier to stress a new test to gain confidence.

**Comment by tschottdorf** [comment]
Duplicate of https://github.com/cockroachdb/cockroach/issues/25284. (Sorry, I told you to file this and then did it anyway).
