### ISSUE TITLE
security: COCKROACH_SKIP_KEY_PERMISSION_CHECK doesn't work for cockroach sql

### ISSUE THREAD

**Issue by jbboehr** [cockroachdb/cockroach#25320]
Although this appears to be caused by new code in github.com/lib/pq: https://github.com/lib/pq/blob/d34b9ff171c21ad295489235aec8b6626023cd04/ssl.go#L112

```
$ cockroach version
Build Tag:    v2.0.0
Build Time:   2018/05/04 08:06:25
Distribution: OSS
Platform:     linux amd64 (x86_64-unknown-linux-gnu)
Go Version:   go1.10.1
C Compiler:   gcc 7.3.0
Build SHA-1:  a6b498b7aff14234bcde23107b9e7fa14e6a34a8
Build Type:   development
```

```
$ COCKROACH_SKIP_KEY_PERMISSION_CHECK=true cockroach sql -e 'show tables'
Error: pq: Private key file has group or world access. Permissions should be u=rw (0600) or less
Failed running "sql"
```

```
$ ls -alh /etc/cockroachdb/certs.d/client.root.key 
lrwxrwxrwx 1 root root 47 May  4 17:37 /etc/cockroachdb/certs.d/client.root.key -> /etc/static/cockroachdb/certs.d/client.root.key
```

```
$ ls -alh /run/keys/cockroachdb-client.root.key 
-r--r----- 1 root keys 1.7K May  4 17:37 /run/keys/cockroachdb-client.root.key
```

**Comment by couchand** [comment]
Thanks for the report @jbboehr.  Indeed as you noticed, the error message you're seeing is coming from libpq, not from cockroach itself.  But as far as I can tell, the only change in the commit you linked was to return the error instead of panicking.  That panic seems to predate our certificate manager entirely, so I don't see how this environment variable ever could have worked.  I may be missing something.

@mberhault, perhaps you have more information here?

**Comment by mberhault** [comment]
The flag is meant to be used to node keys where we control the entire code path. Client usage (through `cockroach sql`) ends up using libpq which we do not control. I'm not sure it's worth adding special error handling for this. The main reason for this flag was to support the odd permission model under windows, not to bypass reasonable security measures.

**Comment by jbboehr** [comment]
> Client usage (through cockroach sql) ends up using libpq which we do not control.

I figured this was the case.

> The main reason for this flag was to support the odd permission model under windows, not to bypass reasonable security measures.

I don't see anything wrong setting it to `0440 root:keys`.

> I'm not sure it's worth adding special error handling for this.

I don't think so either. I'll file an issue against libpq.

**Comment by couchand** [comment]
Sounds like this is working as intended, then.  Thanks @jbboehr for helping us clarify that.
