### ISSUE TITLE
storage: report more information from raftlogger panics

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#25333]
See https://github.com/cockroachdb/cockroach/issues/25217.

**Comment by bdarnell** [comment]
This should be easy: just change the implementation of Panicf from "log.Errorf + panic" to log.Fatalf:

https://github.com/cockroachdb/cockroach/blob/a03c07b1197d397125b951bf97b533a5572926ec/pkg/storage/raft.go#L104-L107

Then we'd recognize the format string as safe and send it to sentry (unparameterized).

**Comment by bdarnell** [comment]
Also note that in 2.0 we include a little more detail for raft panics: we tell sentry not to elide raft stack frames. (#18102. it doesn't look like this was backported to 1.1)

**Comment by tschottdorf** [comment]
I'll try do whip something up on the flight tonight.

**Comment by tbg** [comment]
We should do https://github.com/cockroachdb/cockroach/issues/25333#issuecomment-386927155 and then consider going a step further. Concretely, lots of the Raft panics we're seeing are about broken invariants such as https://github.com/cockroachdb/cockroach/issues/32927. It'd be helpful here to see the additional information in the parameters, which typically isn't user data. We've got to make this safe, though. I think if we taught our raft logger https://github.com/cockroachdb/cockroach/blob/610872ef2bf4d35e44b2ca99e1c601b927d40f0e/pkg/storage/raft.go#L45-L101 to go through the args and wrap all of those that are integer types in a log.Safe, we'd get basically 100% of the way there.

**Comment by tbg** [comment]
> to go through the args and wrap all of those that are integer types in a log.Safe, we'd get basically 100% of the way there.

This basically means something like

```go
fn wrapNumbersAsSafe(v ...interface{}) {
for i := range v {
  switch t := v[i].(type) {
      case int:
        v[i] = log.Safe(v[i])
      case int32:
         // ... same for other numeric types
      default:
  }
}
}
```

and then use that method in all methods on `raftLogger` that accept a `v ...interface{}`.
