### ISSUE TITLE
importccl: IMPORT silently converts `\r\n` to `\n`

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#25344]
Looks like Go's CSV reader is is doing this for us:
> The Reader converts all \r\n sequences in its input to plain \n, including in multiline field values, so that the returned data does not depend on which line-ending convention an input file uses.
-- https://golang.org/pkg/encoding/csv/#Reader

**Comment by dt** [comment]
More details: It appears this is being caused by the behaviour of Golang's encoding/csv library, which folds `\r\n` into `\n` when reading. This was fixed in golang/go#21201 but then reverted golang/go#22746. It appears based on that second issue that Go is unlikely to change that behavior, so we may need to look into using an alternative CSV reader lib.

**Comment by neeral** [comment]
How does forking encoding/csv and applying https://github.com/golang/go/issues/21201 sound? The library itself is very small and consists of a handful of files.
The other approach would be to select another library, which would be a riskier change.

**Comment by dt** [comment]
Yeah, forking the stdlib pkg, with that patch, sounds like a good plan. I guess we could technically just vendor the stdlib package and modify it, but that seems likely to be confusing, so a proper fork, with a distinct import path, seems easier to me.

**Comment by neeral** [comment]
@dt if you can create the fork in the cockroachdb org (I don't have permissions), I can apply the patch to it.

**Comment by dt** [comment]
@neeral Thanks! Actually, looking at this, since it's really just the `reader.go` file, what we've usually done in similar cases is just check the modified stdlib file (and its tests) directly in to the repo, usually somewhere under `pkg/util`. Some examples of this in `syncutil` I believe. I think we could go that route here too?

**Comment by neeral** [comment]
Yes, that works. I'll be sending a PR for this.

**Comment by neeral** [comment]
@dt Could we backport #28181 to release-2.0 please?

**Comment by dt** [comment]
@neeral yep, #28225, Thanks!

**Comment by neeral** [comment]
I think we can close this? Thanks @dt for helping.

**Comment by dt** [comment]
Yep, #28181. Thanks for the fix!
