### ISSUE TITLE
cli: add locality information to node status

### ISSUE THREAD

**Issue by couchand** [cockroachdb/cockroach#25348]
Suggestion from *fat0* [on gitter](https://gitter.im/cockroachdb/cockroach?at=5af0655c5cf0b83004621fe3):  Add a flag to `cockroach node status` to show locality configuration.

> thank you, http://\<host\>:\<port\>/#/reports/localities works for now, would be great if this info was also shown in cockroach node status at some point :grinning:

**Comment by knz** [comment]
Fixed by #39059.
