### ISSUE TITLE
docs/rfcs: revisit RFC template

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#25357]
The RFC template currently contains the following sections:
* Summary
* Motivation
* Guide-level explanation
* Reference-level explanation
* Detailed design
* Drawbacks
* Rationale and Alternatives
* Unresolved questions

Private feedback indicates that this feels heavyweight and burdensome. Some recent RFCs have stripped out various sections without apparent harm. We need to rethink how prescriptive and restrictive the template should be, allowing for variations in the level of rigor needed by various RFCs and the level of rigor various authors like to provide. Yet we also need to keep some level of standardization of RFCs.

**Comment by knz** [comment]
we've done this with @andreimatei
