### ISSUE TITLE
cli: ./cockroach sql against unavailable cluster should work

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#25353]
Currently `./cockroach sql --insecure` hangs forever when run against a cluster for which all ranges have lost quorum. This is suboptimal since we're exposing more and more debugging information via crdb_internal.

This is likely because the shell runs some commands that require the kv layer to work.

**Comment by knz** [comment]
These are the only commands run by the shell (you can inspect via `--echo-sql`):

```
> SELECT * FROM crdb_internal.node_build_info
> SET sql_safe_updates = TRUE
> SHOW SYNTAX 'SHOW SYNTAX ''1'';'
> SHOW TRANSACTION STATUS
> SHOW DATABASE
```

None of these need quorum AFAIK. 
This needs further investigation.

**Comment by knz** [comment]
Oh I see what's going on. There's a query against `system.users` to authenticate the connection.

This looks like we can't do much here?
unless we are to introduce a special unauthenticated more somehow?

**Comment by knz** [comment]
@bdarnell says that if the user is `root` and the connection is authenticated with a certificate we can skip the check in `system.users`.

**Comment by tschottdorf** [comment]
> @bdarnell says that if the user is root and the connection is authenticated with a certificate we can skip the check in system.users.

If the server is in insecure mode, we will also skip the check, correct?
