### ISSUE TITLE
Replica.resolveIntents() can panic if range is removed

### ISSUE THREAD

**Issue by mrtracy** [cockroachdb/cockroach#2535]
There is a race condition in which Replica.resolveIntents() is called after the replica has been removed from Raft.  Relevant code is here:

https://github.com/cockroachdb/cockroach/blob/64be56ae3cb2e5930fd2e10761e3351be152d2fd/storage/replica.go#L1457-L1468

It appears that this code is already expecting a "RangeKeyMismatchError" in some cases, but in the case of the panic an error is returned from Raft (current just a basic errors.New()):

https://github.com/cockroachdb/cockroach/blob/64be56ae3cb2e5930fd2e10761e3351be152d2fd/multiraft/multiraft.go#L40-L42

I'm not entirely sure what the correct thing to do is: should the error be ignored, or is this really a panic situation and the error should be prevented?

**Comment by bdarnell** [comment]
In store.go, we convert ErrGroupDeleted into RangeKeyMismatchError. Either moving that conversion down to the Replica level or treating ErrGroupDeleted and RangeKeyMismatchError as equivalent would fix the panic.

**Comment by bdarnell** [comment]
This appears to have been resolved in @tschottdorf's batch work: we now handle ErrGroupDeleted at the Replica level and turn it into RangeNotFoundError.
