### ISSUE TITLE
sql: ON CONFLICT DO NOTHING doesn't work

### ISSUE THREAD

**Issue by foreverzet** [cockroachdb/cockroach#25363]
**BUG REPORT**

INSERT INTO table(a) VALUES (1) ON CONFLICT DO NOTHING;

The error is:
there is no unique or exclusion constraint matching the ON CONFLICT specification

Although INSERT specification allows to specify no constraints for ON CONFLICT statement.
(https://www.cockroachlabs.com/docs/stable/insert.html)

**Comment by nvanbenschoten** [comment]
@foreverzet what is the schema for `table`?

**Comment by nvanbenschoten** [comment]
@knz assigning you for triage.

**Comment by foreverzet** [comment]
CREATE TABLE t(a INT PRIMARY KEY)
INSERT INTO t(a) VALUES(1) ON CONFLICT DO NOTHING;

**Comment by jordanlewis** [comment]
@foreverzet, you need to explicitly specify which the conflict columns are. In this example, you would do:

```
INSERT INTO t(a) VALUES(1) ON CONFLICT(a) DO NOTHING
```

**Comment by knz** [comment]
As described in https://www.postgresql.org/docs/10/static/sql-insert.html#SQL-ON-CONFLICT
the conflict_target part of ON CONFLICT should be optional for the DO NOTHING case.

CockroachDB does not (yet) support this mode of execution. We could add it as an extension of the current syntax.

**Comment by knz** [comment]
Dup #6639.
