### ISSUE TITLE
import: allow user to specify primary key range on import

### ISSUE THREAD

**Issue by couchand** [cockroachdb/cockroach#25386]
Allowing a user to specify a range of the primary key for an `IMPORT` job, combined with #19432, would allow a user to perform an incremental import of a large file, getting partial results faster and making their import resilient to import errors.

Related to #25350 perhaps.

From **@thstart** on [Gitter](https://gitter.im/cockroachdb/cockroach?at=5af33e9e976405123b34c254):

> The problem is when database is large and after working for days and IMPORT stops all the work done is lost. From other side creating multiple databases comprising a part of the full database makes more difficult to be used for requests - combining 50 UNIONS in each request is not very convenient. The solution I see is following. Let say I have a key like this: 011234, 021234, 031234. As you can see the first two letters are numbers like this 01, 02, 03...50. The full database is 400 mil records / 400 GB. Importing all this can take 5 days and it can stop because a Failure. To avoid failure I can break the DB by 01,02,03... The problem is IMPORT is creating DB from scratch. What is IMPORT can work with ranges? Say I do the 1st IMPORT where the database schema is defined and the range is 01. When this finishes I can continue IMPORT with next range 02. The advantage should be if some IMPORT with some range fails I can repeat the IMPORT. This way the problem with long running IMPORT would be solved.

**Comment by dt** [comment]
If i’m understanding correctly, this would be used to import separate chunks into a given table?

Part of what makes IMPORT work is that it imports into a *new* table — IMPORT into an existing table is still a long way off, and I’m not sure that partial IMPORT would work well without it.

**Comment by couchand** [comment]
Yep, I think #19432 is necessary for this to be useful.

**Comment by dt** [comment]
yeah, append mode / import into an existing table is discussed in #19432, but is not slated on our near-term roadmap.

**Comment by rolandcrosby** [comment]
Mitigated by IMPORT INTO.
