### ISSUE TITLE
build: update bors github permissions

### ISSUE THREAD

**Issue by couchand** [cockroachdb/cockroach#25390]
Before upgrading Bors, we need to be sure that we've added permissive for "Checks".

See https://forum.bors.tech/t/adding-the-github-checks-permission/171

**Comment by couchand** [comment]
@benesch The linked topic is gone and I don't think we've noticed any trouble since you updated so I'm going to close this issue.

**Comment by couchand** [comment]
Oh, here's the updated link: https://forum.bors.tech/t/adding-the-github-checks-permission/169

Relevant snippet:
> You should allow the new permission to be added, so that Bors can push checks (this doesn’t work yet) and can gate on checks (this, on the other hand, has been implemented already).

**Comment by kenliu** [comment]
this seems to not have caused any problems so I am closing.
