### ISSUE TITLE
storage: throughput dips on 15 node cluster, correlated with raft log queue backlog

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#25403]
Reported by used @erichocean [on gitter](https://gitter.im/cockroachdb/cockroach?at=5af26be497f07c7e137c5123). Logging this as an issue to be able to track it.

I'm currently investigating the compaction queue as causing these degradations due to its tendency to be doing work around the time when performance degrades.

**Comment by tschottdorf** [comment]
@erichocean I haven't forgotten about this. The next step here is to run a binary from the release-2.0 branch, which has seen some debugging improvements that I hope to try out. I assume on your end the behavior persists?

Did you ever get around to turning off stats-based rebalancing (`SET CLUSTER SETTING kv.allocator.stat_based_rebalancing.enabled = false;`)? As I mentioned in private communication, there seems to be some amount of rebalancer thrashing, which translates to more disk background activity that could cause these dips.

**Comment by erichocean** [comment]
I'm running the binary you sent me, and did turn off the `stat_based_rebalancing`, but I'm not hitting the cluster as hard recently and am not seeing the same slowdowns. I'll ping you once I do, but it could be a few weeks as we're slowly ramping up our load again through June to where it was when it was causing the issues.

**Comment by tschottdorf** [comment]
Closing; this user isn't running this setup any more.
