### ISSUE TITLE
TestTxnCoordIdempotentCleanup fails with CPU=4

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#2541]
repro: `make test CPUS=4 PKG=./kv TESTS=TestTxnCoordIdempotentCleanup`

You might have to run it a few times. In CI: https://circleci.com/gh/cockroachdb/cockroach/7494

**Comment by tschottdorf** [comment]
actually doesn't even need `CPUS=4`. I'm taking a look.
