### ISSUE TITLE
storage: warn about stores on FUSE file systems

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#25436]
As (re)discovered in #25272, Azure will default temporary disks to NTFS, even on Linux via FUSE. This setup has terrible performance, and we should warn the user. 

Per @bdarnell's advice, any store on a FUSE filesystem deserves a warning in the logs.

**Comment by tschottdorf** [comment]
Dupe of https://github.com/cockroachdb/cockroach/issues/25352, but I'll close that one.

**Comment by benesch** [comment]
🤦‍♂️ my bad, not sure how I missed that.

**Comment by tschottdorf** [comment]
It's because Github's issue search leaves much to be desired.
