### ISSUE TITLE
cli: use ExecerContext and companions in sql_util.go

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#25435]
When porting the `node status` command over to use SQL, we were unable to use context-based cancellation since there is an unaddressed TODO to switch to ExecerContext (etc) in `sqlConnI`. We worked around that using `SET statement_timeout=x` but that's just a crutch.

See https://github.com/cockroachdb/cockroach/pull/25094#issuecomment-387244041.

@knz for triage.

Jira issue: CRDB-6358

**Comment by tschottdorf** [comment]
I just ran into a problem with `QueryRowContext` in the context of #25837 where I cancelled a context and it had no effect, which led to this illuminating comment from @knz:

> two things
first I think the API that enables context cancellation is actually not used here (something to do with which variant of go's `sql` stuff and `lib/pq` are in use)
Also I am not sure our SQL server-side is able to recognize when a client conn drops while a query is running (I think it only picks up the cancellation when the current stmt finishes - not sure)

Especially the former seems troubling. If something takes a context, we expect context cancellation to work. Had we had the contexted API available in #25094 (see link above) we likely would've messed it up (well, hopefully a test would've caught the problem).
