### ISSUE TITLE
roachtest: clockjump/tc=small_forward_enabled is flaky

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#25449]
We're seeing `clockjump/tc=small_forward_enabled` fail periodically in nightly tests. The failures are due to the cockroach node detecting a larger time jump than expected. The test is bumping the time by 150ms, but cockroach sees:

`F180512 05:33:06.475070 72 util/hlc/hlc.go:231  detected forward time jump of 0.275038 seconds is not allowed with tolerance of 0.250000 seconds`

and

`F180511 05:35:17.455660 20 util/hlc/hlc.go:231  detected forward time jump of 0.274999 seconds is not allowed with tolerance of 0.250000 seconds`

and

`F180510 05:32:53.189561 60 util/hlc/hlc.go:231  detected forward time jump of 0.275016 seconds is not allowed with tolerance of 0.250000 seconds`

It is interesting that the detected jump is almost exactly 125ms more than the desired jump. I'm not sure what to make of that. Perhaps we should reduce the desired jump to 100ms. Also interesting that running this test in a loop and I haven't seen any failures.

Cc @vijaykarthik-rubrik and @bdarnell

**Comment by petermattis** [comment]
`StartMonitoringForwardClockJumps` calls `PhysicalNow` every 125ms (250ms / 2). Seems like an idle node could get bad luck and see a clock jump just before it was about to calling `PhysicalNow` again and experience a 275ms time jump since the last call to `PhysicalNow`.

**Comment by petermattis** [comment]
Yes. So saying "Fixes xyz" in a commit message (https://github.com/cockroachdb/cockroach/pull/25433/commits/25361e881c1ffe2d066f091d0f9cfa704925be31) doesn't close an issue anymore?

**Comment by tschottdorf** [comment]
I think we might have to give bors more permissions or something like that? Can bors close issues right now? Because that's what it needs to be allowed to do.

**Comment by tschottdorf** [comment]
Definitely works when mentioned from the PR: https://github.com/cockroachdb/cockroach/issues/25459

I'll try specifically with the issue only next time around.
