### ISSUE TITLE
sql: Driver & ORM List

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#25468]
This is meta issue to serve as a list of known drivers and ORMs that we would like to support. I'll be keeping this top description updated, so if there are any other drivers and ORMs that are not on this list, please comment and I'll add them. Note that these are ordered alphabetically and not by priority. If there is a tracking issue for any of them, it will be linked to from here.

This list is not exhaustive (I just looked for ones we have open issues for), but I would like to keep this as up to date as possible, so it can be somewhat of a source of truth.

C++

- [libpqxx](https://github.com/jtv/libpqxx)
- [SOCI](http://soci.sourceforge.net/)

Clojure

- [JDBC wrapper](http://clojure-doc.org/articles/ecosystem/java_jdbc/home.html)

Elixir

- [Postgrex](https://hexdocs.pm/postgrex/readme.html)
  - [x] #5582 
  - [ ] #33441 Ecto

Go

- [Go-PG](https://github.com/go-pg/pg)
  - [x] #14379 
- [GORM](https://github.com/jinzhu/gorm)
  - [x] #24838 
- [pq](https://godoc.org/github.com/lib/pq)
- [XORM](https://github.com/go-xorm/xorm)
  - [ ] #17161 

Java

- [Hibernate](http://hibernate.org/)
  - [ ] #16491
- [JDBC](https://jdbc.postgresql.org/)

.Net

- [npgsql](http://www.npgsql.org/)
  -  [ ] #25462 
- .NET Core 3.x and NPoco
  - User reports working well

Node.js

- [pg](https://www.npmjs.com/package/pg)
- [Sequelize](https://sequelize.readthedocs.io/en/v3/) 
  - [ ] #33192 - Update to v4
- [TypeORM](http://typeorm.io/#/)
  - [x] #22298 
- [Knex.js](https://knexjs.org/)
- [MeteorJS](https://github.com/meteor/meteor)

Perl

- [DBD::Pg](https://metacpan.org/pod/DBD::Pg)

PHP

- [Doctrine](https://www.doctrine-project.org/)
  - [ ] #19337 
- [PostgreSQL](https://secure.php.net/manual/en/book.pgsql.php)
- [Yii2](https://www.yiiframework.com/)
  - [ ] #25461 
- [Laravel](https://laravel.com/docs/master/eloquent)

Python

- [psycopg2](http://initd.org/psycopg/docs/)
- [SQLAlchemy](https://docs.sqlalchemy.org/en/latest/)
- [Django](https://www.djangoproject.com/)
  - [x] #25608 
- [py-postgresql](https://pypi.org/project/py-postgresql/)
  - [ ] #13191

Ruby

- [ActiveRecord](https://github.com/rails/rails/tree/master/activerecord)
  - [ ] #20932 
- [pg](https://rubygems.org/gems/pg)

Rust

- [Diesel](https://diesel.rs/)
  - [ ] #13787 
- [postgres](https://crates.io/crates/postgres/)

Multiplatform

- [Prisma.io](https://www.prisma.io/)
  - [ ] https://github.com/prisma/prisma/issues/1705

**Comment by kocoten1992** [comment]
Laravel eloquent: https://laravel.com/docs/master/eloquent (it should be similar with ActiveRecord)

**Comment by BramGruneir** [comment]
Thanks @kocoten1992, added!

**Comment by abaumhauer** [comment]
Perl DBIx::Class likely via the DBD::Pg driver

**Comment by BramGruneir** [comment]
Thanks @abaumhauer, added!

**Comment by dtrinh100** [comment]
Not a true ORM, but I would love to see support CockroachDB support for [Prisma](https://www.prisma.io/)

**Comment by BramGruneir** [comment]
Added both Prisma and Knex to our list.  Thanks!

**Comment by drewdeally** [comment]
Bram, Adding MeteorJS as per customer request.

**Comment by BramGruneir** [comment]
@drewdeally Added to the list.  Thanks.

**Comment by irvingpop** [comment]
hi @BramGruneir !  Would you consider adding [sqitch](http://sqitch.org) to the list?  

Against cockroachDB, a `sqitch deploy` fails with an `unimplemented` error:

```
$ sqitch --verbose deploy "db:pg://${USER}:${PASS}@${HOST}/$DB"

ERROR:  unimplemented at or near ","
DETAIL:  source SQL:

        SELECT c.change_id
             , c.script_hash
                 , c.change
             , c.project
             , c.note
             , c.committer_name
             , c.committer_email
             , to_char(c.committed_at AT TIME ZONE 'UTC', '"year":YYYY:"month":MM:"day":DD:"hour":HH24:"minute":MI:"second":SS:"time_zone":"UTC"') AS committed_at
```

**Comment by BramGruneir** [comment]
Hi @irvingpop,

Of course!  But it's a schema change management system, so I've added it to #25469 instead.

I'm pretty sure it's the `to_char` that we don't support.  That's some old postgres syntax that is supposed to be deprecated but is still used all over.  See #3781 for that main issue for that one.

**Comment by BramGruneir** [comment]
@irvingpop I forgot to mention, we offer online schema change, so there might be less of a need for systems like sqitch. They're still useful for testing and dev, but there's now little need for these system in production.  

See https://www.cockroachlabs.com/docs/v2.1/online-schema-changes.html.

**Comment by irvingpop** [comment]
awesome!  thank you @BramGruneir !

**Comment by tim-o** [comment]
We recently received another request about Prisma: http://forum.cockroachlabs.com/t/2575

**Comment by tim-o** [comment]
Zendesk ticket #[3229](https://cockroachdb.zendesk.com/agent/tickets/3229) has been linked to this issue.

**Comment by rkruze** [comment]
Received a request recently for goqu - https://github.com/doug-martin/goqu

**Comment by meddlin** [comment]
It's not on the list, but I recently started working with .NET Core 3.x and NPoco (via npsql, which is on the list). I'm surprised how well this works!

**Comment by vy-ton** [comment]
Closing this meta issue in favor of issues for individual tools
