### ISSUE TITLE
stability: liveness failures during rebalancing

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#25512]
@andy-kimball accidentally exercised adding a new node to an existing 3 node cluster. The result was not good and caused his cluster to be unstable for a significant period of time. The specific steps he took were to provision a 4 node `roachprod` cluster using the instructions in the benchmarking whitepaper. He started a 3 node cluster on nodes 1-3 and imported the tpcc-1k dataset. He then stopped the 3 nodes and restarted cockroach nodes on all 4 machines. Note that the tpcc-1k data set is 208 GB. 

![screen shot 2018-05-15 at 9 53 31 am](https://user-images.githubusercontent.com/6201335/40061426-ea74923c-5826-11e8-9903-802ab1418889.png)

![screen shot 2018-05-15 at 9 53 47 am](https://user-images.githubusercontent.com/6201335/40061430-ecf54876-5826-11e8-8d68-bb6caf50088c.png)

![screen shot 2018-05-15 at 10 18 26 am](https://user-images.githubusercontent.com/6201335/40062485-55e65fda-5829-11e8-8b80-d864a8f08d8c.png)

Above we can see when the 4th node was added and rebalancing started happening, and then liveness failures (the last graph is a custom graph of the `liveness.heartbeatfailures` metric). 

![screen shot 2018-05-15 at 9 54 35 am](https://user-images.githubusercontent.com/6201335/40062526-6c75006c-5829-11e8-8d1c-c87aa4350595.png)

![screen shot 2018-05-15 at 9 54 40 am](https://user-images.githubusercontent.com/6201335/40062536-72ddf85a-5829-11e8-8c80-b93bcbdebd02.png)

It seems like the liveness failures are correlated with replica GC.

![screen shot 2018-05-15 at 9 54 27 am](https://user-images.githubusercontent.com/6201335/40062549-76e804ea-5829-11e8-939e-43306d25aaf1.png)

There was a lot of raft snapshot activity during the rebalancing, which is unexpected. 

![screen shot 2018-05-15 at 10 21 24 am](https://user-images.githubusercontent.com/6201335/40062675-c3edae84-5829-11e8-88ab-a2f579c836f7.png)

Leaseholders per store was a mess, presumably because of the liveness failures.

Assigning to @tschottdorf for triage.

**Comment by andy-kimball** [comment]
This was a 2.0.1 Cockroach binary from our distribution point.

**Comment by tschottdorf** [comment]
@andy-kimball were you running this on underprovisioned machines?

**Comment by tschottdorf** [comment]
Might this have to do with the rogue compactions due to the rebalancing that occurred when the fourth node was added (#26355)? @m-schneider were you able to repro this at all?

**Comment by tschottdorf** [comment]
Closing as inactionable.
