### ISSUE TITLE
ui: provide a count of cpus on the overview page

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#25514]
The cluster overview page provides a count of the number of nodes in the cluster but no indication of the associated cpu power. There is a vast difference between a 3 node cluster with 1 cpu per node vs a 3 node cluster with 16 cpus per node.

**Comment by bdarnell** [comment]
See also #24205

**Comment by vilterp** [comment]
We now show a CPU count for each node in the node list. #29366 tracks getting this right when we're in Docker.
