### ISSUE TITLE
sql: investigate pg_typeof for TTuple

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#25523]
During the review of #25283, the issue of pg_typeof was raised specifically for dealing with TTuples.

Here are @knz's notes:

> I'd be indeed interested to ensure pg_typeof does the right thing for TTuple. However at the same time we must be mindful that pg does not report the detailed type composition of a tuple with pg_typeof (neither for labeled nor non-labeled tuples! Our current implementation, regardless of this PR, is wrong) -- instead, if uses the name of the thing that produced the tuple type. For example:
>
> -   select pg_typeof(kv) from kv -> reported type name is just "kv" even though the implementation of that type is a labeled tuple
> - `select pg_typeof(_pg_expandarray(...)) -> reported type name is just "record"
> - `select pg_typeof(row(1,2,3)) -> also just "record"
>
> We'll implement this transient type name logic in a later iteration. The logic is simple: any composite type derived from a table name gets the name of the table; everything else gets named "record".

**Comment by jordanlewis** [comment]
Closing as there's no concrete action item here. Feel free to re-open if i got it wrong.
