### ISSUE TITLE
storage: TestReplicaTSCacheLowWaterOnLease failure

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#25538]
https://teamcity.cockroachdb.com/viewLog.html?buildId=660075&buildTypeId=Cockroach_UnitTests
https://teamcity.cockroachdb.com/viewLog.html?buildId=660084&buildTypeId=Cockroach_UnitTests

**Comment by vivekmenezes** [comment]
https://teamcity.cockroachdb.com/viewLog.html?buildId=664246&buildTypeId=Cockroach_UnitTests

**Comment by a-robinson** [comment]
This will be fixed by https://github.com/cockroachdb/cockroach/pull/25625
