### ISSUE TITLE
acceptance: need to disable auto-upgrade in `TestVersionUpgrade`

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#25577]
This isn't yet a problem because we don't test upgrading past 2.0, but once we go to 2.1 the manual upgrade will race with the automatic one.

The test should be updated to disable the auto-update path for the versions which have it.

**Comment by windchan7** [comment]
I think instead of running `clusterVersionUpgrade(...)` at the very end, we can actually introduce another step that observes the upgrade happens to prevent the race.

**Comment by tschottdorf** [comment]
Good point! I'm fine switching to automatic upgrades past that version. Could you send a PR?
