### ISSUE TITLE
distsqlrun: verify hashjoiner is spilling to disk for concurrent "small" queries

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#25590]
From a customer reported issue, a query that was unintentionally doing a full table scan and then a hash join was reporting memory budget exceeded errors. These errors only started to occur when concurrency of the queries was turned up. The hypothesis is that the hashjoiner is not spilling to disk when a number of concurrent queries combine to exceed the configured SQL memory.

However, in principle the hashjoiner should be spilling to disk in this instance.

From @asubiotto:

> The criteria are that
>
> 1. The processor hits a limit of sql.distsql.temp_storage.workmem
> 2. or the monitor denies a memory allocation because some other memory limit is hit (i.e. --max-sql-memory). This is the case that should be hit in the hash joiner when multiple concurrent small queries are executing.
>
> We create a monitor [with a limit](https://github.com/cockroachdb/cockroach/blob/b45ad8c4b1352aab7dd22d19a167f5b39e23b774/pkg/util/mon/bytes_usage.go#L213) and start it [here](https://github.com/cockroachdb/cockroach/blob/b45ad8c4b1352aab7dd22d19a167f5b39e23b774/pkg/sql/distsqlrun/hashjoiner.go#L194) so it should be requesting allocations from the upstream monitor (which all queries running on a node use). I'll double check this.

**Comment by asubiotto** [comment]
So I verified that it does spill to disk for concurrent small queries but there are some edge cases where we don't regardless of what limit we hit e.g. [when building buckets](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/distsqlrun/hashjoiner.go#L395)

**Comment by asubiotto** [comment]
Conclusion: the `hashJoiner` spills to disk when multiple concurrent small queries are executing (i.e. we hit `--max-sql-memory`). However, this investigation uncovered a case in which the `hashJoiner` would report out of memory errors (from downstream) https://github.com/cockroachdb/cockroach/issues/25590 and edge cases where it is possible to hit a limit in the `hashJoiner` and not fall back to disk. The resolution of the linked issue will resolve this.
