### ISSUE TITLE
cluster: Allow upgrades with down nodes

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#25592]
From https://github.com/cockroachdb/cockroach/issues/23912#issuecomment-389483525

The automatic upgrade process (#23912) has made it effectively mandatory to decommission dead nodes. This is inconvenient for deployments that need completely hands-off operations. Can/should we offer some way to upgrade clusters that do not decommission nodes when they die?

One option would be to automatically decommission nodes after a certain amount of downtime. If we do this, then we have the inverse problem: If a dead node is eventually revived, it will need to either be wiped or recommissioned before it can be put back into service (maybe this is OK if the threshold for auto-decommissioning is high enough). However, I don't think auto-decommissioning is a good idea since the point of decommissioning is to serve as an affirmative signal from the operator that a node is not expected to recover. Anywhere that auto-decommissioning would be appropriate would (probably) be better served by just treating long-dead and decommissioned nodes the same.

(On the other hand, auto-decommissioning could probably be implemented today in userspace with a script that queries node status and runs the decommission command. If deployments that need this feature are rare enough we could just recommend this as a solution)

I think a cluster setting to allow auto-upgrades as long as either all nodes are running the new version or all dead nodes are at least X hours old would make sense. The biggest risk that I see is that if the binary upgrade causes some but not all of your nodes to crash, the upgrade would eventually be auto-finalized anyway when the wiser action would be to roll back the upgrade. It also makes the timing of the upgrade finalization less predictable, so it may happen when less attention is being paid to the cluster (if a node died before the new version is rolled out, but wasn't yet old enough to be ignored for upgrade purposes)

Another potential issue is that if a node is down across multiple upgrades and then is revived (say a 2.0 node crashes, the cluster is upgraded twice to 2.2 and then the dead node is revived), the node will be unable to rejoin the cluster and will need to be wiped (with our current upgrade compatibility policy). This is probably OK since it implies a node being down for 6+ months and then recovering.

**Comment by gpaul** [comment]
> One option would be to automatically decommission nodes after a certain amount of downtime. If we do this, then we have the inverse problem

Agreed. This seems a bit too magical.

> On the other hand, auto-decommissioning could probably be implemented today in userspace with a script that queries node status and runs the decommission command.

Fair.

> The biggest risk that I see is that if the binary upgrade causes some but not all of your nodes to crash, the upgrade would eventually be auto-finalized anyway when the wiser action would be to roll back the upgrade.

Interesting. So the exact failure scenario you describe is that of a node becoming unresponsive and subsequently being declared dead during the upgrade? Very possible: I imagine a rolling upgrade of a thousand node cluster where the source binary is chmod 0644 instead of 0755.

**Comment by gpaul** [comment]
I wonder if requiring `underreplicated_ranges = 0` is enough? That would guard against any failure at zero risk of data loss.

**Comment by tschottdorf** [comment]
Not necessarily a blocked, but I just want to point out that once you lose all replicas of a given range, that range isn't counted any more in `underreplicated_ranges`. So if you have a perfectly partitioned 6-node cluster and one partition (of three nodes) dies, you'd be left with a zero metric. This is a bit contrived.

**Comment by gpaul** [comment]
@tschottdorf thanks for pointing that out. Would checking both `underreplicated_ranges` and `unavailable_ranges` guard against that?

@bdarnell 

> Out of curiosity, what threshold did you have in mind for the amount of time a node needs to be down before deciding that we can continue the upgrade without waiting for it to come back?

I had in mind the standard node liveness deadline. I believe it is something like 10 minutes? 

In my case an operator is performing a rolling upgrade of an entire server, on which CockroachDB is running as one among many processes, and only proceeds to upgrade the next server once the current one is upgraded and all checks are healthy, otherwise there is a very manual procedure for rolling back his upgrade.

I don't think the upgrade should be considered successful nor the cluster version updated automatically if any ranges are unavailable or underreplicated.

Should we restate my feature request as follows?
> If all live nodes are running the new same version, and that version is newer than the currently configured cluster version, then the cluster version should be updated if and only if there are no underreplicated or unavailable ranges.

**Comment by bdarnell** [comment]
> Would checking both underreplicated_ranges and unavailable_ranges guard against that?

No. Both of these metrics require the range to have at least one replica left. It's extremely unlikely (outside of some contrived zone config scenarios) that you could lose all three replicas of some ranges without losing at least two replicas of others (making them count in unavailable_ranges), but this is still an oversight in our monitoring. I don't think we currently have any metrics that could be used to detect the loss of all replicas of a range.

> I had in mind the standard node liveness deadline. I believe it is something like 10 minutes?

5 minutes. OK, so this mitigates the concern I had about this pushing the upgrade out to a time when no one is watching the cluster. 

> If all live nodes are running the new same version, and that version is newer than the currently configured cluster version, then the cluster version should be updated if and only if there are no underreplicated or unavailable ranges.

Yes, this makes sense (as long as we redefine underreplicated/unavailable ranges to something that includes ranges that have gone completely missing). I think with this safeguard I might even be OK with removing the "no dead nodes" check completely instead of making this configurable.

**Comment by tschottdorf** [comment]
In some future in which the `crdb_internal.gossip_alerts` is mature, we could mandate that it be empty before proceeding with the update.
