### ISSUE TITLE
ui: missing metric graph for SQL memory usage

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#25606]
The SQL memory graph (reporting on the various `sql_mem` metrics) has been removed from the UI at some point (I remember adding it and I cannot find it any more).

Meanwhile it was just requested on Gitter.

I think the graph should be added back in the "SQL" graph page and/or "Runtime".

/cc @couchand

**Comment by jordanlewis** [comment]
This is going to be in 20.2 (#54846 )
