### ISSUE TITLE
server: NodeStatus without the node's store statuses is persisted during node bootstrap

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#25617]
As explained in https://github.com/cockroachdb/cockroach/issues/25488#issuecomment-389601139:

> Node 3 has persisted a `NodeStatus` kv entry, but not with the `StoreStatus` information for its store. This can happen because `node.Start` calls `node.bootstrapStores` asynchronously, and `node.bootstrapStores` is the code path that registers a store with the `NodeStatus` recorder. It appears as though that code almost always runs after the `server.Start` code path that registers the node and writes the first `NodeStatus` entry, and that in rare cases in these partitioning tests it hasn't finished by the time that the `CONFIGURE ZONE SQL` command executes.

This is very low priority as the tests that were affected by it now have a workaround in place, but I don't like having this edge case in place where 99.9% of the time a `NodeStatus` persisted to kv will have all of its stores included, but not the very first one when a node (other than node ID 1) boots up for the first time.

Jira issue: CRDB-5702

**Comment by irfansharif** [comment]
Spent a few hours before finding this; it's come in the way of me trying to write better bootstrap tests in #52526. Given that we're in the area, perhaps we should clean this up.
