### ISSUE TITLE
sql: implement "project set" in distsql

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#25658]
This issue describes the proposed semantics of a ProjectSet operator, along with a discussion of how it would be used on some sample queries.

### ProjectSet

The ProjectSet operator has:
 - an input data source
 - a list of SRFs
 - a list of projected columns

For each row received from the source, all SRFs are applied. Each SRF
application results in a tuple, which we can think of as a bunch of rows with
one column. For each input row, ProjectSet emits as many rows as the largest SRF
application result (others are padded with NULLs as necessary). Each row has one
column per SRF and one column per projected column; the rows emitted for a
single input row have the same values on the projected columns.

These semantics mirror the PostgreSQL 10 semantics when multiple SRFs are used
in a SELECT (e.g. `SELECT unnest(x), unnest(y), ...`). Note that earlier
versions had much crazier semantics for these cases; see the note at the end of
this section:
https://www.postgresql.org/docs/devel/static/xfunc-sql.html#XFUNC-SQL-FUNCTIONS-RETURNING-SET

Example (with pg 10.4):
```
SELECT a, unnest(b), unnest(c) FROM (VALUES (1, ARRAY[1,2,3], ARRAY[4,5])) AS t(a,b,c);
 a | unnest | unnest 
---+--------+--------
 1 |      1 |      4
 1 |      2 |      5
 1 |      3 |       
```

This operator seems relatively straightforward to implement as either a
`planNode` or a distsql processor (preferrably both).

### Basic use

An example of the simplest case for an SRF is part of a Hibernate query:

```
SELECT information_schema._pg_expandarray(indkey) AS keys FROM pg_index
```

This would be a straight-forward application of ApplySRF (with the input being
the table scan).

A slightly more complicated example is:

```
SELECT
  indexrelid,
  (information_schema._pg_expandarray(indclass)).x AS operator_argument_type_oid,
  (information_schema._pg_expandarray(indclass)).n AS operator_argument_position
FROM
  pg_index
```

Here we are just selecting two record fields from the same SRF, but in general
these functions need not be the same. Even if we treat them as separate SRFs,
the results are as expected because of the semantics of ProjectSet (so detecting
that we only need to apply the SRF once would be just an optimization).

### Correlated subqueries

Consider this sample query (posted on the forum):

```sql
SELECT
  g.data->>'name' AS group_name,
  jsonb_array_elements( (SELECT gg.data->'members' FROM groups AS gg WHERE gg.data->>'name' = g.data->>'name') )
FROM
  groups AS g
```

The query looks complicated but it's just trying to emit a `(group_name, member_name)`
row for every member in a group.

This cannot be easily decorrelated today; we can get very close with a join, but
the query behaves differently if there are multiple rows with the same
`data->>'name'`) - the original query errors out.

```sql
SELECT
  g.data->>'name',
  json_array_elements((gg.data->>'members')::json)
FROM
  groups AS g JOIN groups AS gg ON gg.data->>'name' = g.data->>'name'
```

This transformation would be valid if the equality column was a unique
key, but this does not apply to a JSON field (at least not today).

This problem could be solved with a special `MAX_1_ROW` aggregation function
which causes the query to error out if any group receives more than one non-NULL
value. The rewritten query would be something like:

```sql
SELECT
  g.data->>'name',
  json_array_elements(max_1_row(gg.data->>'members')::json)
FROM
  groups AS g JOIN groups AS gg ON gg.data->>'name' = g.data->>'name'
GROUP BY g.data->'name'
```

This is now similar to the basic queries: ProjectSet would be used on the result
of the join.

**Comment by RaduBerinde** [comment]
CC @petermattis @jordanlewis @andy-kimball @justinj

**Comment by knz** [comment]
The execution behavior is not specific to SRFs by the way, it is needed to support postgre's `ROWS FROM (...)` operator. 

In fact the full story is the following:

- `ROWS FROM ( ... ) ` is what the new ApplySRF thing will support.
- there will be a semantic substituion during logical planning that transforms multiple SRFs in render positions to a single `ROWS FROM ( ...)` operand in the data source
- the ApplySRF code can also be used if users enter `ROWS FROM ( ... )` manually.

**Comment by RaduBerinde** [comment]
Right. The underlying logical expression would be the same regardless if `ROWS FROM` or SRF-in-render-position syntax is used.

**Comment by knz** [comment]
I added the underlying `ROWS FROM` operator separately in #26223, so that the person working on this issue has something to work with until the optimizer knows about SRFs.
