### ISSUE TITLE
build: post issues from failures in the nightly sql logic test runs

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#25667]
We should be posting issues whenever the nightly sql logic test runs fail. A recent failure was ignored for a week. This could either be done by having `build/teamcity-sqllogictest.sh` use `github-post` (similar to what `build/teamcity-stress.sh` does), or have use `build/teamcity-post-failures.py` in the same manner as merge-to-master PRs.

**Comment by jordanlewis** [comment]
This is now done
