### ISSUE TITLE
sql: conflicting ColumnTypes error with UNION ALL

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#25674]
As of my commit 63931933c268fc04ec7841a59099380a4aee6832, this test fails (with `-config distsql`):

```
/go/src/github.com/cockroachdb/sqllogictest/test/index/view/100/slt_good_0.test:3437: SELECT pk, col0 FROM tab1 WHERE ((col1 = 459.6) OR col4 IS NULL) OR (col0 = 426) UNION ALL SELECT pk, col0 FROM tab1 WHERE NOT (((col1 = 459.6) OR col4 IS NULL) OR (col0 = 426))
    expected success, but found
    pq: conflicting ColumnTypes: {INT 0 0 [] <nil> INTEGER <nil>} and {INT 0 0 [] <nil> NONE <nil>}
```

The thing is, I don't think the problem is what my commit is doing; it's exposing something that maybe we would get in other contexts.

This is the code where the error shows up:
```go
func MergeResultTypes(left, right []sqlbase.ColumnType) ([]sqlbase.ColumnType, error) {
	if len(left) != len(right) {
		return nil, errors.Errorf("ResultTypes length mismatch: %d and %d", len(left), len(right))
	}
	merged := make([]sqlbase.ColumnType, len(left))
	for i := range left {
		leftType, rightType := left[i], right[i]
		if rightType.SemanticType == sqlbase.ColumnType_NULL {
			merged[i] = leftType
		} else if leftType.SemanticType == sqlbase.ColumnType_NULL {
			merged[i] = rightType
		} else if leftType.Equal(rightType) {
			merged[i] = leftType
		} else {
			return nil, errors.Errorf("conflicting ColumnTypes: %v and %v", leftType, rightType)
		}
	}
	return merged, nil
}
```

We are comparing `ColumnType`s using the protobuf `Equal`. The field that differs is `VisibleType`. My commit changed some code to get the type directly from the table `ColumnDescriptor` instead of converting it from the datum types in `resultColumns`. Note that `DatumTypeToColumnType` does not populate the `VisibleType`. I think this check is too strict.

@knz @jordanlewis what would you recommend as a standard way of checking if two `ColumnType`s are equivalent? I'm thinking converting to `types.T` and using `Equivalent`?

CC @solongordon

**Comment by jordanlewis** [comment]
Yes, I think you're right that this is too strict. I think we should create an `Equivalent` method on `ColumnType` to get around this problem. I'll send a PR.
