### ISSUE TITLE
sql: general purpose Apply operator

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#25678]
The Apply relational operator is used for queries that cannot be decorrelated. It effectively requires re-running a subquery many times, each time with a different set of values for the "outer" columns.

At this point, we think that we will be able to decorrelate the important queries, but there is another use-case for this operator: testing the optimizer decorrelation transforms. We want to be able to run the given query un-optimized (using Apply) and then re-run the optimized, decorrelated plan and cross-check the results.  The good news is that for this use-case, performance of the operator is not critical.

The main difficulty in implementing Apply is that planNodes or distsql processors cannot be reset/restarted, and fixing that across all operators seems like a big task.

A possible alternative would be to use the opt execbuilder to re-generate a new plan for the subquery every time. The Apply planNode contains a callback to the execbuilder which is called for every input row; the callback remembers the right-hand-side expression of the Apply (as an `ExprView`) and generates the execution plan for it. Outer columns could be handled in two ways:
 - use the placeholder infrastructure; the execbuilder would create placeholder nodes for all outer values.
 - pass the values to the callback and have the execbuilder create the plan using the specific values. It is conceivable that we could make the callback even re-optimize the expression given the values (e.g. use them for index constraints).
 
CC @petermattis @jordanlewis @andy-kimball

**Comment by asubiotto** [comment]
Moving to `Later` to reflect the movement in the `SQL Execution` project. This has not been planned for 2.1.
