### ISSUE TITLE
sql: correctness bug with UPSERT and FAMILY

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#25726]
On master:
```sql
CREATE TABLE t (a INT PRIMARY KEY, b INT, c INT, FAMILY (a, b), FAMILY (c));
INSERT INTO t VALUES (1, 2, 3);
UPSERT INTO t VALUES (1, NULL, NULL);
SELECT * FROM t;
```
returns
```
+---+------+---+
| a |  b   | c |
+---+------+---+
| 1 | NULL | 3 |
+---+------+---+
```
but should return `(1, NULL, NULL)`. This reproduces without the `b` column, but I thought the example was more obvious with it.

Looks like the all-NULL column family isn't actually getting a tombstone written. The equivalent UPDATE works fine.  @knz you've touched UPSERT last, mind looking into this?

**Comment by knz** [comment]
found the cause. cooking PR now.
