### ISSUE TITLE
server: add "health alerts" counter metric

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#25757]
https://github.com/cockroachdb/cockroach/pull/25343 introduced a mechanism that gossips a distress signal from nodes when appropriate. We should introduce a metric that is incremented every time a distress signal is emitted.

**Comment by knz** [comment]
this goes into the server queue as the SREs are interested in this

**Comment by tbg** [comment]
Are the really? The counter here would be triggered by metrics, but SREs monitor the metrics directly. For example, a slow raft request would be triggering the counter, but SREs would likely want to watch the metric about slow raft requests directly. SREs also really care about being able to tune how sensitive they are to signals, so a signal as suggested here that is really a predigested hodge podge of other signals isn't going to be very useful for them as they will have to adapt to the noisiest subsignal, which is then effectively the only one they're receptive to.

**Comment by knz** [comment]
Hm but then what is the value of `gossip_alerts`? It suffers from the same limitation, doesn't it?

**Comment by tbg** [comment]
Correct, I don't see that as something the SREs would consume. So far the value it provides is in on-prem deploys / debug.zip-based debugging because we have zero real visibility into metrics in those settings.

**Comment by knz** [comment]
all right then
