### ISSUE TITLE
sql: SELECT 1/3 return error : decimal out of range

### ISSUE THREAD

**Issue by louishust** [cockroachdb/cockroach#25753]
**BUG REPORT**

1. Please supply the header (i.e. the first few lines) of your most recent
   log file **for each node in your cluster**. On most unix-based systems
   running with defaults, this boils down to the output of

```
➜  cockroach git:(master) ✗ ./cockroach version
Build Tag:    v2.1-alpha.20180507-465-g14236e0-dirty
Build Time:   2018/05/21 10:26:24
Distribution: CCL
Platform:     darwin amd64 (x86_64-apple-darwin16.7.0)
Go Version:   go1.10.1
C Compiler:   4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)
Build SHA-1:  14236e0225a7ac420c563a6e794b022a619adc15
Build Type:   development
```

2. Please describe the issue you observed:

- What did you do?

```
root@:26257/> select 1 / 3;
pq: decimal out of range
```

- What did you expect to see?

```
0.33333333333333333333
```

- What did you see instead?

```
pq: decimal out of range
```

**Comment by louishust** [comment]
It seems #25258  make the wrong results

**Comment by knz** [comment]
cc @nvanbenschoten
