### ISSUE TITLE
sql: errors in distsql execution that should be caught much earlier

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#25756]
Running `make testlogic` on master, I see the following errors in the cluster logs:

```
sql/distsqlrun/server.go:391 error setting up flow: error type checking constant value: could not parse "a" as type int: strconv.ParseInt: parsing "a": invalid syntax
```

```
sql/distsqlrun/server.go:391 error setting up flow: could not parse "a" as type int: strconv.ParseInt: parsing "a": invalid syntax
```

```
sql/distsqlrun/server.go:391 error setting up flow: unsupported binary operator: <int> / <int> (desired <int>)
```

```
sql/distsqlrun/server.go:391 error setting up flow: column name "d" not found
```

Because they are in the cluster logs I am not exactly sure which specific logic tests are triggering them. However I am 100% sure these are semantic errors that must be caught during planning, and must never appear during execution. What's going on?

cc @RaduBerinde @asubiotto

**Comment by jordanlewis** [comment]
These happen during schema changes. I don't think it's important to fix this.

**Comment by knz** [comment]
Wait what? Just recategorize, don't close.
