### ISSUE TITLE
backup: job fails with "could not find valid split key" error

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#25770]
I've recently seen backups failing with errors like the following:

```
Error: creating backup for table customer: pq: could not mark job 350118039979982849 as failed: split failed while applying backpressure: could not find valid split key: split failed while applying backpressure: could not find valid split key
```

This is related to https://github.com/cockroachdb/cockroach/pull/25261 and specifically https://github.com/cockroachdb/cockroach/issues/24215. It looks like the jobs table row is growing to over 128MB in size, which is triggering the new backpressure mechanism. I suspect that we're updating the row too often, which is causing this huge amount of MVCC growth. Before the backpressure change, these single row ranges were allowed to grow to arbitrary sizes, but this is problematic for a number of reasons. We should adjust backup so that it doesn't create such a large row footprint. There are a few ways that we could get around this issue:
- reduce how often we update the jobs table to a reasonable rate. Do we really need to checkpoint so often that the row grows to these sizes?
- move commonly changed columns to a different column family. This could help if most of the row (size-wise) is static, and we're just changing a small column constantly.
- make jobs table rows inline. I don't think this is actually the approach we want to take, but it would fix the issue.

This is easily reproducible by running:
```
./workload fixtures make tpcc --warehouses=10000
```

cc. @dt @benesch

**Comment by dt** [comment]
+cc @mjibson @bobvawter

**Comment by nvanbenschoten** [comment]
Also, in case anyone is trying to get around this issue, the most straightforward way is to disable range size backpressure via:

```
SET CLUSTER SETTING kv.range.backpressure_range_size_multiplier=0;
```

Of course, this is disabling an important safeguard and large ranges can be a big issue for cluster health, so the workaround should be used sparingly.

**Comment by dt** [comment]
(assigned to @mjibson for triage)

**Comment by nvanbenschoten** [comment]
I think this issue would be mostly solved by https://github.com/cockroachdb/cockroach/pull/25791 in conjunction with a fix to https://github.com/cockroachdb/cockroach/issues/21561.

**Comment by mjibson** [comment]
We think the underlying issues have been fixed here. Closing.

**Comment by nvanbenschoten** [comment]
I can confirm, this issue seems to have been fixed by a combination of https://github.com/cockroachdb/cockroach/pull/25791, https://github.com/cockroachdb/cockroach/pull/26313, and https://github.com/cockroachdb/cockroach/pull/26458. I didn't hit any issues when I ran the remainder of a `./workload fixtures make tpcc --warehouses=50000` job and the everything appeared to be a lot faster.
