### ISSUE TITLE
TestClientPermissions clocks in at ~2.5s

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#2577]
probably a backoff in there somewhere. The time is spaced out over messages like

> W0921 06:14:55.378630 85113 client/rpc_sender.go:92  failed to send RPC request Server.Batch: client is unhealthy

**Comment by tschottdorf** [comment]
I think some other tests run into this as well, though with a less pronounced outcome. Basically I suspect all tests that have mentions of the above log line could be slowed down by it (there are a lot of tests that take close to .25s, which might be the backoff's fault).

**Comment by mberhault** [comment]
This got a lot slower when I changed the `client/sender.go:InitialBackoff` from 50 to 250ms in #2495 
There's an issue make retry options saner: #2500 but nothing yet.
At the very least, it may be good provide a better way to override timeout options per test (specify them on `client.Open`, or access the `sender.retryOpts`)
