### ISSUE TITLE
NULL Timestamp

### ISSUE THREAD

**Issue by arypurnomoz** [cockroachdb/cockroach#2578]
Can timestamp field be null?

**Comment by vivekmenezes** [comment]
Yes it can. All column types can be null.

**Comment by petermattis** [comment]
We love bug reports, but this is just a pure question and might have been better suited to the mailing list (cockroach-db@googlegroups.com).

PS I suppose the bug might be our lack of documentation, but that is on our roadmap.

**Comment by arypurnomoz** [comment]
Sorry, yesterday i encounter a bug which is the default setting for TIMESTAMP is NOT NULL, but when i don't include it on `INSERT` it will not yield any error, but `SELECT` on that row will throw some kind of "datum nil" error . Today, somehow it's fixed after i restarted the server. But i still don't know how to reproduce the bug.

**Comment by petermattis** [comment]
The default for all columns is NULL-able. That default is independent of column type. If you have an example where this isn't true, please provide the SQL. What you're describing certainly sounds like a bug, but without reproduction details there is little we can do.

**Comment by arypurnomoz** [comment]
I got the issue again. Restarting the server didn't solve the problem.
```
> CREATE TABLE kv (k VARCHAR PRIMARY KEY, v TIMESTAMP);
OK
> SHOW COLUMNS FROM kv;
+-------+-------------+------+---------+
| Field |    Type     | Null | Default |
+-------+-------------+------+---------+
| "k"   | "STRING"    | true | NULL    |
| "v"   | "TIMESTAMP" | true | NULL    |
+-------+-------------+------+---------+
```

**Comment by petermattis** [comment]
What's the issue? All columns default to NULL-able. If you want a
NON-NULL-able column you would have to do:

> CREATE TABLE kv (k VARCHAR PRIMARY KEY, v TIMESTAMP NOT NULL);

OK

> SHOW COLUMNS FROM kv;
+-------+-------------+-------+---------+
| Field |    Type     | Null  | Default |
+-------+-------------+-------+---------+
| "k"   | "STRING"    | true  | NULL    |
| "v"   | "TIMESTAMP" | false | NULL    |
+-------+-------------+-------+---------+
