### ISSUE TITLE
ui: capacity percent overflows

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#25800]
<img width="622" alt="image" src="https://user-images.githubusercontent.com/5076964/40359693-a05bba0c-5d91-11e8-95c8-ad992985be8a.png">

Similar problem: 
<img width="299" alt="image" src="https://user-images.githubusercontent.com/5076964/40359720-b50bf80e-5d91-11e8-91d1-7cc2d0b5477e.png">

Firefox with neutral zoom.

**Comment by couchand** [comment]
Looks like this was taken care of in previous layout updates.
