### ISSUE TITLE
ui: don't reuse the term "insecure mode"

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#25843]
I was slightly surprised by the following in my local (secure) UI:
![login-insecure-mode](https://user-images.githubusercontent.com/5901480/40424185-c9f399d0-5e62-11e8-9f1c-072162f53459.png)

Please, let's not use "insecure mode" (or "secure mode") for anything other than `--insecure=[true/false]`. This should instead say something along the lines of `login disabled`, or `anonymous user`, etc...

**Comment by couchand** [comment]
Good catch.  Yep, it is supposed to mean `--insecure`, but it's not supposed to show up at all unless you've set the environment variable `COCKROACH_EXPERIMENTAL_REQUIRE_WEB_LOGIN`.  This slipped through the cracks.  Will be fixed by #25816.
