### ISSUE TITLE
PostgreSQL JDBC dbMetaData.getPrimaryKeys failing

### ISSUE THREAD

**Issue by iuliant88** [cockroachdb/cockroach#25854]
I've started one node on Ubuntu and created the table accounts in the bank db:
CREATE TABLE bank.accounts (id INT PRIMARY KEY, name STRING);

After that I've tried to use JDBC Kafka connect sink (Confluent) and it fails to insert data. I tried with the latest PostgreSQL driver: postgresql-42.2.2.jar
While debugging I saw it fails here:
dbMetaData.getPrimaryKeys("bank", "public", "accounts"); 

and the error is:

	INFO Querying column metadata for product:PostgreSQL schema:public catalog:bank table:accounts (io.confluent.connect.jdbc.sink.DbMetadataQueries:84)
	org.postgresql.util.PSQLException: ERROR: syntax error at or near "."
	  Detail: source SQL:
	SELECT NULL AS TABLE_CAT, n.nspname AS TABLE_SCHEM,   ct.relname AS TABLE_NAME, a.attname AS COLUMN_NAME,   (i.keys).n AS KEY_SEQ, ci.relname AS PK_NAME FROM pg_catalog.pg_class ct   JOIN pg_catalog.pg_attribute a ON (ct.oid = a.attrelid)   JOIN pg_catalog.pg_namespace n ON (ct.relnamespace = n.oid)   JOIN (SELECT i.indexrelid, i.indrelid, i.indisprimary,              information_schema._pg_expandarray(i.indkey) AS keys         FROM pg_catalog.pg_index i) i     ON (a.attnum = (i.keys).x AND a.attrelid = i.indrelid)   JOIN pg_catalog.pg_class ci ON (ci.oid = i.indexrelid) WHERE true  AND n.nspname = 'public' AND ct.relname = 'accounts' AND i.indisprimary  ORDER BY table_name, pk_name, key_seq
																														^
		at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2182)
		at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1911)
		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:173)
		at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:645)
		at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:481)
		at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:361)
		at org.postgresql.jdbc2.AbstractJdbc2DatabaseMetaData.getPrimaryKeys(AbstractJdbc2DatabaseMetaData.java:3360)
		at io.confluent.connect.jdbc.sink.DbMetadataQueries.getTableMetadata(DbMetadataQueries.java:93)

Can you please advise?

Thanks,
Iulian

**Comment by BramGruneir** [comment]
Hi @iuliant88,

```sql
SELECT NULL AS TABLE_CAT, 
         n.nspname AS TABLE_SCHEM,   
         ct.relname AS TABLE_NAME, 
         a.attname AS COLUMN_NAME,   
         (i.keys).n AS KEY_SEQ, ci.relname AS PK_NAME FROM pg_catalog.pg_class ct   
JOIN pg_catalog.pg_attribute a 
  ON (ct.oid = a.attrelid)   
JOIN pg_catalog.pg_namespace n 
  ON (ct.relnamespace = n.oid)   
JOIN (
  SELECT i.indexrelid, 
         i.indrelid, 
         i.indisprimary,              
         information_schema._pg_expandarray(i.indkey) AS keys         
  FROM pg_catalog.pg_index i
) i     
  ON (a.attnum = (i.keys).x 
    AND a.attrelid = i.indrelid)   
JOIN pg_catalog.pg_class ci 
  ON (ci.oid = i.indexrelid) 
WHERE true 
  AND n.nspname = 'public' 
  AND ct.relname = 'accounts' 
  AND i.indisprimary  
ORDER BY table_name, pk_name, key_seq
```

Sadly, this query uses a version of our old friend `SELECT (i.keys).n FROM (SELECT information_schema._pg_expandarray(indkey) AS keys FROM pg_index) AS i;` which is one of our biggest sources of incompatibility.

It requires a number of fixes that we're actively working on, but I don't expect it to be fixed until our 2.1 release.    
You can follow along with with my progress working on this here: #16971
