### ISSUE TITLE
jobs: retry transient errors

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#25866]
A context canceled error in a job should restart it instead of not. It is possible this will get into an infinite loop if the context canceled error is masking an actual error, but that's not what I've observed so far.

**Comment by vivekmenezes** [comment]
We do support cancelling such jobs if it were to get into an infinite loop right?

**Comment by mjibson** [comment]
Yes, but a user would have to notice. And hopefully they'd report it because it'd be our bug too.
