### ISSUE TITLE
sql: log event for TRUNCATE

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#25867]
@a-robinson, @jseldess and I just spend a merry 30 minutes trying to figure out what was going on on cobalt, one of our production clusters.

The outcome was that someone must have `TRUNCATE`d a large table which left lots of empty ranges, which led to an imbalance of live bytes. We needed to look at raw range boundaries to figure this out.

There should be an event log for `TRUNCATE` similar to the one you get when a table gets created:

<img width="423" alt="image" src="https://user-images.githubusercontent.com/5076964/40443216-a02ac688-5e93-11e8-9adc-4b44335958e2.png">

cc @jordanlewis for triage (and apologies for what is probably the wrong A-sql-* category)

**Comment by a-robinson** [comment]
I'll just knock this out quickly, since adding event log events is fresh in my cache.

**Comment by jordanlewis** [comment]
Thanks, @a-robinson!
