### ISSUE TITLE
ui: does not report the correct number of ranges

### ISSUE THREAD

**Issue by mrtracy** [cockroachdb/cockroach#2596]
The admin UI is not reporting the correct number of ranges when the cluster starts up:

![screen shot 2015-09-21 at 4 35 11 pm](https://cloud.githubusercontent.com/assets/6969858/10004270/db761ee2-607e-11e5-8dc9-9c8b83d81c0e.png)

The total range count above should be '3', but the first range is not reported as existing on nodes 2 and 3.  This is likely an issue with the way that range counts are tabulated: the interaction between our event feeds and the node status needs to be evaluated.

**Comment by petermattis** [comment]
Is this still a problem?

**Comment by mrtracy** [comment]
I have confirmed that this is no longer an issue in latest code.
