### ISSUE TITLE
distsql: support unaryNode

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#26064]
There are many simple queries of the form `SELECT <expr>` which internally use `unaryNode` and cannot run under distsql. We have found that some of these queries would expose bugs - we hit various issues when the same queries were run from the optimizer (which uses a valuesNode instead of the unaryNode). For example: #26063

This issue tracks supporting `unaryNode` (which is a trivial change) plus fixing all the issues that are uncovered.

**Comment by RaduBerinde** [comment]
https://cockroachdb.github.io/distsqlplan/decode.html?eJyMjzFLBDEUhHt_xTKVwgN323Rnd43KFoIcKZZkOBfXvCUvAeHY_y63KcRCuHJmku_jXZA08nn6osGdMMAL1qyBZpqvVXtwjN9wvWBOay3X2guCZsJdUOayEA5v01Jpjz0EkWWal0bsnrr7oQsfNX3aAwQjU2R23WEcD-8nD78JtJZfrpXpTLh-k9vdI23VZPzj_p_sBYxntvtMaw58zRp2TYsv-7-9iLTS1qGFY2rT5re7nwAAAP__9JZoeQ==

**Comment by RaduBerinde** [comment]
As of #26104, the optimizer team is not blocked on this anymore. I unassigned myself as I won't be looking at it for now.

The diff to enable planning for unaryNode is:

```diff
--- a/pkg/sql/distsql_physical_planner.go
+++ b/pkg/sql/distsql_physical_planner.go
@@ -417,7 +417,10 @@ func (dsp *DistSQLPlanner) checkSupportForNode(node planNode) (distRecommendatio
 				}
 			}
 		}
-		return shouldDistribute, nil
+		return canDistribute, nil
+
+	case *unaryNode:
+		return canDistribute, nil
 
 	case *createStatsNode:
 		return shouldDistribute, nil
@@ -2128,6 +2131,9 @@ func (dsp *DistSQLPlanner) createPlanForNode(
 	case *valuesNode:
 		plan, err = dsp.createPlanForValues(planCtx, n)
 
+	case *unaryNode:
+		plan, err = dsp.createPlanForUnary(planCtx, n)
+
 	case *createStatsNode:
 		plan, err = dsp.createPlanForCreateStats(planCtx, n)
 
@@ -2226,6 +2232,31 @@ func (dsp *DistSQLPlanner) createPlanForValues(
 	}, nil
 }
 
+func (dsp *DistSQLPlanner) createPlanForUnary(
+	planCtx *planningCtx, n *unaryNode,
+) (physicalPlan, error) {
+	// No columns; just one empty row.
+	s := distsqlrun.ValuesCoreSpec{NumRows: 1}
+
+	plan := distsqlplan.PhysicalPlan{
+		Processors: []distsqlplan.Processor{{
+			// TODO: find a better node to place processor at
+			Node: dsp.nodeDesc.NodeID,
+			Spec: distsqlrun.ProcessorSpec{
+				Core:   distsqlrun.ProcessorCoreUnion{Values: &s},
+				Output: []distsqlrun.OutputRouterSpec{{Type: 0}},
+			},
+		}},
+		ResultRouters: []distsqlplan.ProcessorIdx{0},
+		ResultTypes:   nil,
+	}
+
+	return physicalPlan{
+		PhysicalPlan:       plan,
+		planToStreamColMap: nil,
+	}, nil
+}
+
 func (dsp *DistSQLPlanner) createPlanForDistinct(
 	planCtx *planningCtx, n *distinctNode,
 ) (physicalPlan, error) {
```

I have fixed a few issues, but there are more that pop up in logictests once this change is made.

**Comment by jordanlewis** [comment]
unaryNode is supported now.
