### ISSUE TITLE
ui: tab freezes chrome after some minutes, can't be refreshed

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#26079]
In Chrome, looking at a table schema view in a tab. After some minutes (5-10) it becomes unresponsive, can't be reloaded (i.e., I have to create a new tab and close the broken one), and the chrome task manager reports it using 150% CPU.

**Comment by vilterp** [comment]
Will try to repro.

**Comment by vilterp** [comment]
K, repro'd by leaving the tab open for about 8 minutes. Grabbed this profile while at 100% CPU: https://drive.google.com/file/d/1XHjom-rBz-HZgdnVcdSRWMiZfxHQGoPH/view?usp=sharing Will load profile back into Chrome and dig in tomorrow.

**Comment by couchand** [comment]
Yes that's very interesting.  Looks like it's spending 88% of the time in some function `l` in vendor, I'll see if I can dig in more so see what's happening here.

**Comment by couchand** [comment]
Oh, it looks like that's in highlight.js.  Not sure what it's doing, but that's one more reason to get rid of that library.

**Comment by couchand** [comment]
I wonder if this has anything to do with it:

![highlight-to-the-max](https://user-images.githubusercontent.com/793969/40805722-32d89b04-64ed-11e8-942f-8b68be3197bf.png)

**Comment by vilterp** [comment]
Incredible. So it adds spans the first time, and then wraps them in more spans each subsequent time? Can we fix this by somehow blowing away the div each time and making it start from scratch?

**Comment by couchand** [comment]
That's basically what's happening.  I think the short-term fix might just be aggressive application of `shouldComponentUpdate`.  I'm actually kind of amazed that they've been able to come up with an algorithm that produces these particular results.
