### ISSUE TITLE
sql: automate the discovery of differences between CockroachDB and PostgreSQL

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#26102]
The idea is to capture a trace of the SQL statements + placeholder values between a client and **postgres** server, then replay this trace using a common client on both pg and CockroachDB and see where they differ.

e.g. run `cockroach sql` on both traces and run `diff` on the output, or some related strategy.

This automation could be captured in a single VM or container and reused for many different kinds of client tools.

**Comment by knz** [comment]
cc @BramGruneir

**Comment by jordanlewis** [comment]
@mjibson does this capture your current work?

**Comment by mjibson** [comment]
Yes this is pretty close.
