### ISSUE TITLE
sql: reveal shortcomings of mutation checks by creating regression tests

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#26105]
So currently the constraint checks (FKs/CHECK/IS NULL) are performed super late in the mutation code, down at the row writer. Meanwhile other processing is happening earlier, and can produce invalid values: computed columns between other things.

- [ ] NULLs in non-NULL columns
  - passed to ISNULL in CHECK constraints, FKs or computed exprs
  - this may not cause silent data errors, but will cause invalid error messages.
- [ ] columns not listed in the mutation column list, but needed for checks / computed exprs
  - this has caused panics in the past
- [ ] values with wrong precision 
  - these may cause silent data errors because the precision is truncated automatically, but after CHECK / FK checks
- [ ] values with wrong type
  - panics computed cols 
    - [X] #25721 
    - [ ] #25742
- [x] using multiple column families #25726

**Comment by jordanlewis** [comment]
This is no longer relevant after the CBO ate checks.
