### ISSUE TITLE
sentry: consistency check failed with %d inconsistent replicas

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#26139]
https://sentry.io/cockroach-labs/cockroachdb/issues/566009564/

```
*log.safeError: replica_consistency.go:154: consistency check failed with %d inconsistent replicas | int
  File "github.com/cockroachdb/cockroach/pkg/storage/replica.go", line 2459, in executeAdminBatch
  File "github.com/cockroachdb/cockroach/pkg/storage/replica.go", line 1897, in Send
  File "github.com/cockroachdb/cockroach/pkg/storage/store.go", line 2732, in Send
  File "github.com/cockroachdb/cockroach/pkg/storage/stores.go", line 214, in Send
  File "github.com/cockroachdb/cockroach/pkg/server/node.go", line 897, in func1
...
(10 additional frame(s) were not displayed)

replica_consistency.go:154: consistency check failed with %d inconsistent replicas | int
```

**Comment by bdarnell** [comment]
We may not be able to get enough information to act on this, but it could be an indicator of a serious bug. A few interesting details from the sentry report:

- It's an OSS build of v2.0.0
- It's tagged with `environment=development`. Shouldn't that have prevented the sentry report?
- The cluster has experienced clock offset panics. This could cause SQL-level inconsistencies, but I don't think it could cause the downstream-of-raft divergence in this report.

**Comment by tschottdorf** [comment]
Similar crash reports have been unactionable as well. I wonder what we can do to do better here. Perhaps we need a dedicated call to action to the operators to reach out to us.

**Comment by bdarnell** [comment]
We could add a "please contact us" to the message, but this cluster has experienced dozens of these crashes so if they haven't reached out to us yet they're probably not paying attention to anything we might be able to do to reach them. 

In any case, this serves as confirmation that consistency failures do still sometimes happen (In #26151 I might have suggested turning the consistency checker off completely in release builds if this hadn't come to my attention).

**Comment by tschottdorf** [comment]
Closing for https://github.com/cockroachdb/cockroach/issues/28699.
