### ISSUE TITLE
distsqlrun: support naive subqueries in DistSQL

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#26149]
Currently, subqueries aren't runnable in DistSQL - any query with a subquery gets punted to the local execution engine, and executed up front, before the rest of the query executes. Subquery results are stored in a memory buffer.

DistSQL should be able to run subqueries. Eventually, we might want to do something more sophisticated than just executing the subqueries up front. For now, though, DistSQL should support subqueries in the same way that local SQL does: by executing the subquery up front, storing the results in a memory buffer, and making them available to the processors that need them.

**Comment by arjunravinarayan** [comment]
Closed by #28580.
