### ISSUE TITLE
acceptance: leaks fds

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#26156]
I ran `make acceptance TESTTIMEOUT=24h TESTS=TestVersionUpgrade TESTFLAGS='-v -l . -count 100'`

After an hour or so, a test failed due to "socket: too many open files".

This suggests that over the lifetime of the binary, we're leaking file descriptors somewhere.

**Comment by tschottdorf** [comment]
We're piling up sockets in CLOSE_WAIT:

`lsof -u tschottdorf | grep CLOSE_WAIT | wc -l` grows by a dozen for every iteration of the upgrade test. I *think* this means that we're not closing some connection properly.
