### ISSUE TITLE
roachtest: log artifacts mixed between subtests?

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#26155]
<img width="221" alt="image" src="https://user-images.githubusercontent.com/5076964/40650956-8c5ae0c0-6302-11e8-81c9-59f6b0d5efe2.png">

Note the "logs" directory. It's not clear which of the subtests it belongs to.

**Comment by petermattis** [comment]
This shouldn't happen. Do you have the link to the build this occurred on? I'll try reproducing.

**Comment by petermattis** [comment]
https://teamcity.cockroachdb.com/viewLog.html?buildId=683856&buildTypeId=Cockroach_Nightlies_WorkloadNightly&tab=artifacts#!17bb5k,st18xb3gyt21

**Comment by petermattis** [comment]
Ah, I see the problem.
