### ISSUE TITLE
sqlccl: Put options in the SQL grammar so types are intuitive

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/cockroach#26150]
When usability testing EXPORT, I noticed that the option `chunk_rows` requires a string to indicate the batch size, even though this argument is conceptually a number.

According to @dt, this is an artifact of how we do options in SQL. The alternative is that we should put the options to these commands in the SQL grammar like we do for normal commands with appropriate types. If we did this, the parser would handle options (and be able to complete them, include them in diagrams, etc) just like normal commands.

Currently, we use a string->string map though so that we don’t have to tell the parser about out options.

Opening this ticket to track the discussion. Outside of a more complex parser, what would be the downside of this? How expensive would this be to implement? As a user, this was a small (but curious) usability issue.

cc @knz 

Jira issue: CRDB-5686

**Comment by knz** [comment]
1) It is customary when a feature is just being developed to avoid locking down types too much (to keep velocity in development iterations). Once we start getting a good feel for the desired UX, that's the moment when it becomes appropriate to settle things down and provide explicit typing. Perhaps now is the time.

2) that said, in this particular case we could have done much better from the start, by allowing any expression type on the RHS of the `=` sign. There are plenty of other places in the grammar that allow this, even though they don't constrain the type of options (e.g. `SET`). I don't really see a good reason why this was not done from the start.
