### ISSUE TITLE
storage: consistency check only mutated ranges

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#26151]
Say you have a 2TB cluster, which today means upwards of 30k ranges (and perhaps around 10 nodes). Today, each range becomes eligible for a consistency check after 24 hours. This means the cluster will consistency check 20 ranges per minute, and in doing so it will read 1.2 gb/min (on three nodes in the cluster).

For the 10 node example, this means an average load of (3.6 gb / min)/(10 nodes) = 6 mb/s.

This may be deemed acceptable, but we could improve it in common scenarios by consistency checking only ranges that haven't been mutated (i.e. split, merged, lease extended, or written to).

**Comment by bdarnell** [comment]
We could also make the consistency checks less frequent by default. The consistency checker was useful when we were developing cockroach (and we'd still want to run them frequently on our test clusters), but I'm not sure it's worth the cost in production environments.

**Comment by tschottdorf** [comment]
That might be a good starter. As another alternative, we could change the knob for that queue so that it specifies a max throughput (mb/s). This would scale better with the cluster size (the more data, the rarer each replica gets checked).
