### ISSUE TITLE
sql: Always add a FK constraint in the invalid state and validate later

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#26166]
We currently add FK constraints via ADD CONSTRAINT in the invalid state and validate the constraint later using VALIDATE CONSTRAINT. For CREATE TABLE that introduces an FK constraint we do not need to do this because the new table has no data and the constraint is assumed to be valid. However, we use a pessimistic strategy of putting the new table in the ADD state invisible to DML transactions until all cached copies of the referee table contain a back reference to the new table. The result is that an INSERT on the table in the same transaction as the CREATE TABLE fails.

 Instead, It will be better to use an optimistic approach and add the table and make it live immediately holding a constraint that has yet to be validated. A schema change is run after the transaction to enforce the validity of the constraint. If by change the constraint is invalid the table will be dropped.

**Comment by vivekmenezes** [comment]
related issues:

https://github.com/cockroachdb/cockroach/issues/17949
https://github.com/cockroachdb/cockroach/issues/20714
https://github.com/cockroachdb/cockroach/issues/25794

**Comment by vivekmenezes** [comment]
We will move to a model where the entire schema will be leased at a specific timestamp. With that model a constraint can transition from the absent -> write_only -> enforced (public) state. So nodes can either be in (absent, write_only), (write_only, enforced), (enforced) states at any point in time. The write_only state means that the FK relationship affects INSERT, UPDATE, UPSERT, DELETE operations and the constraint is going through validation. Once the constraint is validated, the state is moved to enforced. If it cannot be validated it is marked invalid and dropped returning an error to the user.

We will do the same for CREATE TABLE with an FK constraint as well. The table will no longer be placed in the ADD state. It will come alive immediately with the constraint in the write_only state. if the constraint validation fails the constraint is marked invalid with the table still extant. An error will be returned to the user saying the table was added with an invalid constraint. The constraint can be explicitly removed by the user.

@dt  ^

**Comment by dt** [comment]
If we allow writes to the referencing table before the referenced table is checking delete operations, we can create orphan rows -- which we promised we _wouldn't do_ when we said OK to the `CREATE TABLE` that included a FOREIGN KEY.

Concretely, if you have a customers table and then run `BEGIN; CREATE TABLE orders(id int primary key, customer_id int REFERENCES customers); INSERT INTO orders(id, customer_id) VALUES (1, 22); COMMIT;` if we agree to commit that txn, I think we're obligated to ensure that 
a) orders must exist, and must exist as it was created i.e. including the requested constraint 
b) the orders row (1, 22) must actually be written and can't later be lost 
c) there is, and will continue to be a corresponding customer row with ID 22.

If we don't wait for the back-reference in customers to be live on all nodes, we can't promise to maintain c), however checking and maintaining c) was what the user asked for, and we agreed to when we said OK to the create table and then accepted the row.

I might be missing something here, but it doesn't seem like we can make the table live for writes until we're sure referenced tables are checking deletes without violating the correctness of FK semantics?

**Comment by vivekmenezes** [comment]
In today's world because the table orders is created in the ADD state, the INSERT in the same transaction fails. What I'm recommending is we add the table and run the constraint validation later. In that scheme the INSERT (1, 22)  will succeed as long as 22 exists in customers, but there is still a delay on constraint validation and 22 can be deleted by another node unaware of the FK relationship, making the relationship invalid. In that case the constraint is later marked invalid.

I think the above schema is nice in that it doesn't drop data that was confirmed as inserted. It's only broken in that the constraint is violated, but I think that's a reasonable compromise.

BTW the same would happen on BEGIN; ALTER TABLE orders ADD CONSTRAINT customer FOREIGN KEY (customer_id) REFERENCES customers (customer_id); INSERT INTO orders(id, customer_id) VALUES (1, 22); COMMIT;

The above will succeed as long as customers contains 22, but the constraint might not be valid for the entire table.

We will have to document that the constraint will be validated later like any other schema change.

**Comment by lucy-zhang** [comment]
Closing because nowadays FKs are added as validated by default, and I don't think we should move away from this for new tables. There are probably some issues with the way we're handing FKs in new tables right now (especially if there are DML statements in the same transaction), but I don't think this issue is the right place.
