### ISSUE TITLE
ccl: Cockroachdb should support import data to one table which is already exists.

### ISSUE THREAD

**Issue by pananc** [cockroachdb/cockroach#26189]
**FEATURE REQUEST**

1. Does an issue already exist addressing this request? If yes, please add a :+1: reaction to the existing issue. If not, move on to step 2.

2. Please describe the feature you are requesting, as well as your proposed use case for this feature.

Cockroachdb should support import data to one table which is already exists.

```
Imported tables must not exist and must be created in the IMPORT statement. If the table you want to import already exists, you must drop it with DROP TABLE.
```
Cockroachdb import data will require the target table do not exists.    
Now i have one table which contains lots of data, then i want to append some data to the table, i can not drop the table for import data, how can i import the new data?

3. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

must-have

**Comment by bdarnell** [comment]
This is already being tracked in #19432. 

It would definitely be useful, but one of the reasons `IMPORT` can be as fast as it is is that it doesn't have to worry about any existing data in the table. Importing into an existing table would need to be a completely different implementation and would be much slower. For now, you'll just need to convert your data into INSERT statements if you want to add to an existing table.
