### ISSUE TITLE
deps: github.com/codahale/hdrhistogram has been archived

### ISSUE THREAD

**Issue by etsangsplk** [cockroachdb/cockroach#26186]
https://github.com/codahale/hdrhistogram hsa been archived and no active development.
that project has been archived, and there have been multiple PR from fixing overflow to optimization.
Can you guys either own that repo or use one that is more active and maintained

**Comment by bdarnell** [comment]
We haven't had any problems with it, and it's not clear that the open performance and overflow issues really matter for our usage of it. We can always fork it if there's a need, but I'm in no hurry to do so unless there's a more specific reason.

**Comment by jordanlewis** [comment]
Looks like it's been revived.
