### ISSUE TITLE
sql: implement `coalesce()` function

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#2620]
`coalesce()` is a variadic function which returns the first of its arguments that is non-null (all the arguments must presumably have the same type for this to type check sanely). To support this function we need to allow variadic functions with return types determined by the argument types.

Variadic `coalesce()` is standard SQL. Some databases have similar non-standard functions which take exactly two arguments and therefore might be easier for us to implement (mysql calls it `ifnull()`; oracle calls it `nvl()`).

**Comment by petermattis** [comment]
`coalesce()` is like a special case of `case ... when ...`. Implementing within the current builtin function type-system might be tricky, but the actual functionality is not complicated.
