### ISSUE TITLE
importccl: dumped table schema (--dump-mode schema) is not IMPORT-able if table has FKs

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/cockroach#26248]
Problem:
If you want to EXPORT CSV a table and IMPORT it later we don't have a fast way to get a supported schema. 

Today, you can do something like `cockroach dump  --dump-mode=schema  --insecure <db> <table> > order_dump.sql`

but plugging that into IMPORT will result in the following error if the table has an FK: `pq: expected 1 statement, but found 3` since the file includes two ALTER TABLEs to add and validate the constraint. 

Potential solutions:
* enhance EXPORT to support creating an IMPORTable schema
* enhance DUMP to support an IMPORTable schema

cc @mjibson @dt fyi re: our in person discussion

**Comment by mjibson** [comment]
You can get a correct table schema by running `SHOW CREATE TABLE <t>`. I'm inclined to teach EXPORT how to produce a CREATE TABLE file instead of change dump.

**Comment by nstewart** [comment]
`SHOW CREATE TABLE <t>` is a great workaround. I'll just make sure that's documented and we can revisit if we find this isn't good enough. 

`cockroach sql -e "show create table <t> --format raw` does the trick!

**Comment by dt** [comment]
We fixed `dump` to make import-able schemas a while ago and just missed closing this.
