### ISSUE TITLE
sql/pgwire: return (some) structured error information

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#2625]
When we broke the dependency from sql/driver to errors.proto, we lost the ability for the client to determine when it needs to retry a transaction. We should return the `proto.Error.transaction_restart` flag as a part of `driver.Result`, and we should expose error types and/or helper functions in the `driver` package to allow applications to make use of this flag.

**Comment by bdarnell** [comment]
Also, since SQL retries are indistinguishable from brand-new transactions, we are losing an important liveness protection from our KV API: SQL transaction priorities are not ratcheted up on retries, so SQL clients may get stuck in an extended sequence of retries (I've observed 25+ seconds locally with two threads). It's difficult to do this priority update in a generic SQL framework, but a cockroach-specific RunTransaction helper could propagate transaction priorities on restart.

**Comment by tschottdorf** [comment]
this sounds like the simplified transaction handling we settled on in #2094 isn't adequate. The simplistic design was mostly driven by the constraints of the interface: sure, we could keep some state about the transaction in the session even if it fails and use that to ratched the next attempt up, but you never know whether the next attempt is even for the same txn (that could be a negligible problem, of course; or we could hash the request or something funky like that). Can we come up with a plan for that prior to reintroducing this?

**Comment by tschottdorf** [comment]
> We should return the proto.Error.transaction_restart flag as a part of driver.Result

currently those transactions are always aborted. I'm assuming you're suggesting undoing that as well? The issue then is that our system health depends on the SQL clients explicitly doing something after their transaction "aborts" (really the only thing the driver supports, iirc). If they don't retry, the txn dangles, and that would suck.

**Comment by bdarnell** [comment]
No, I'm not suggesting that we stop aborting these transactions, so maybe what I'm asking for is not exactly the `transaction_restart` flag. What I want is to distinguish between "the server said the transaction was aborted" and "I couldn't talk to the server so the transaction is in an unknown state". In the former case I can restart my transaction immediately; in the latter I have to do some additional queries to learn if the previous attempt succeeded before I make a second attempt. Right now we must treat every error from Commit() as if it leaves the transaction in an unknown state.

**Comment by tschottdorf** [comment]
I see. Wouldn't introducing a new default entry in the `TransactionStatus` enum take care of that? It currently defaults to `..._ABORTED`, but for non-`TransactionRestartError`s we could have it set to `..._UNKNOWN`; that would be the signal that the error doesn't tell us anything about our transaction.

**Comment by bdarnell** [comment]
How does the sql client driver see the TransactionStatus enum? I don't think we need to add a new transaction status; we just need to make sure that when the status is known, we report it to the client.

**Comment by tschottdorf** [comment]
what value of `TransactionStatus` would encode the "unknown state"? All "normal" errors return `TransactionStatus_ABORTED` (even when that's not true), I thought that wasn't going to be good enough for what you wanted.

**Comment by bdarnell** [comment]
All `proto.Errors` return `TransactionStatus_ABORTED`; other errors (e.g. network errors) do not have a transaction status (so these are the "unknown" ones). The problem is that this distinction is lost when passing through the SQL layer: we just get a single string error message: https://github.com/cockroachdb/cockroach/blob/9529d0d8ba907b25c6724a7c53032010bd79c233/sql/driver/wire.proto#L65

**Comment by tschottdorf** [comment]
sorry, I thought we were talking about the `TransactionRestart` enum, which sits on `proto.Error` and which defaults to `TransactionRestart_ABORTED`, so even on the `proto.Error` level you couldn't distinguish them (unless you want to start peeking into the `ErrorDetail`, which doesn't seem sleek).
Hence my suggestion to have it default to `.._UNKNOWN` instead so that `_ABORTED` would be reserved for those errors that know for sure you've been aborted.
Were you talking about something else?

**Comment by bdarnell** [comment]
All I'm asking is for a subset of the structure available in `proto.Error` to be exposed via `sql/driver.Result`. We want to avoid depending on the full `proto` package from `sql/driver`, but this is an example of how a little more structure would be helpful.

**Comment by tschottdorf** [comment]
I'm just trying to clarify which field you're trying to expose. I assumed it was `TransactionRestart`, but the discussion above seems like I didn't guess right.

**Comment by petermattis** [comment]
I think @bdarnell wants an additional field in `sql.driver.Result` which indicates if an extant transaction was aborted successfully on error or left in an unknown state. I think this would have to combine the `TransactionRestart` state with whether any automatic abort succeeded.

**Comment by bdarnell** [comment]
I originally asked for `transaction_restart`, but that's not quite right. I think what I want from the server is `TransactionAbortedError`: an indication that the request made it down to the transaction record and saw that it was definitively aborted. This can be combined with client-side knowledge of whether a `COMMIT` was even attempted (I don't think we can trust server-side knowledge of this because there may be retries in a network queue somewhere).

The reason I want this is that transaction-level retries are only trivial when you can know for sure that the previous attempt did not succeed. Error introspection is not the only way to achieve this; we could expose elements of the Session instead (the postgres and mysql protocols both return a bit in every response indicating whether a transaction is active)

**Comment by petermattis** [comment]
Retitled this issue to refer to pgwire. We need to figure out how to send back an indication to the client that a transaction is retryable and for the client to then retry the transaction using the same transaction ID.

**Comment by andreimatei** [comment]
Retryable errors return a specific error code since #5364
