### ISSUE TITLE
sql: DECIMAL index much slower than INTEGER

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#26251]
@robert-s-lee reports that on a table with a primary key containing two DECIMAL columns, queries by that key took 1000ms (all values were integers). Changing those columns to INTEGERS improved the response time by a factor of 100, to 10ms. It looks like there's a lot of room for improvement in our handling of DECIMAL values in indexes.

**Comment by jordanlewis** [comment]
Interesting, we'll take a look at this.

**Comment by jordanlewis** [comment]
Current testing shows closer to a 3x difference. This likely changed a lot with vectorized, so I'll close this and we can revisit if it comes up again.
