### ISSUE TITLE
core: bad checksum on release builds when using encryption at rest

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#26261]
At the time of the first compaction, rocksdb detects a bad checksum:

```
E180530 21:41:29.961699 230 storage/replica.go:4827  [n1,s1,r33/1:/Table/53/1/-8{15009…-09684…}] unable to update the state machine: could not commit batch: Corruption: block checksum mismatch: expected 4061029206, got 769420182  in /mnt/data1/cockroach/000007.sst offset 710670 size 14828
```

This is happening on the release binaries. Oddly enough, it is not happening on the dev binaries build on my local machine (old school linux with gcc 5.4.0 20160609) or the builder dev binaries (4.2.1 Compatible Clang 3.8.0)

CC: @benesch, @windchan7 who assisted in debugging.

I'll double check reproducible binaries and start debugging.

**Comment by mberhault** [comment]
Update for today;
This reproduces trivially with a `release-linux-gnu` build and roachtest kv0 (1 or 3 nodes, local or remote) and encryption enabled.

By lowering `options.write_buffer_size` to 1MB, the first compaction happens fairly quickly and crashes with a checksum failure.

Lots of digging has so far not found anything. I've checked the raw bytes going through encryption, and what comes out is what came in. We're also always using the proper encrypted env and strace shows no unaccounted file access.

One interesting thing: enabling `options.paranoid_file_checks` not only stops crashing, but it also does not spit out any issues.

I think I'll call it a day, I'll dig into instrumenting rocksdb tomorrow.

**Comment by mberhault** [comment]
Ok, I finally have it.
It turns out, the decryption was **not** always correct. From time to time, a single AES block would be decrypted as garbage. I did not notice this before because rocksdb is re-reading the same sstable multiple times, and some reads were fine, some were not.

The multiple reads are all done using the same `Env::RandomAccessFile` which has the same underlying AES cipher object. The timestamps indicate that concurrent reads are going on with the same cipher object.

Now, for the fun part. The reason this works in my local build and fails with `release-linux-gnu` is that the latter causes cryptopp to be built without AESNI instructions, falling back on pure software AES. My guess is that the software one uses much more read/write local state.

The naive verification of sticking a mutex on the cipher object did the trick: I can't get it to fail after many runs when reproduction took no time.

A few things to do here (likely more):
* use a separate cipher object for each rocksdb operation (eg: one Env::Read may still do thousands of AES blocks, but these are processed sequentially)
* figure out how to make cryptopp build AESNI runtime detection as opposed to compile-time defines
* improve tests to do concurrent file operations using the same handle

Summary: this was **not** fun.

**Comment by petermattis** [comment]
> Summary: this was not fun.

Nice debugging. It was fun to read about!
