### ISSUE TITLE
sql import by generic sql dump in insecure mode

### ISSUE THREAD

**Issue by blacklightknight** [cockroachdb/cockroach#26276]
**QUESTION**

I have cdb running in a aws instance inside docker in insecure mode. i created a dump file there for two tables with schema and data both.
I installed docker and cdb inside my system then(in insecure mode only) and transferred that sql dump file from the aws instance to my system.
Then when I tried to import the dump file in my system's cdb by following commands with respective behaviour:

1) `docker exec admin_cockroachdb_1 ./cockroach sql --insecure --database=nakama < /path/to/data.sql`
But nothing happened in the terminal and the terminal got hanged and I couldn't enter any line on that terminal after that. In another terminal window I looked at the db , and the data didn't import as well.
Then I tried:

2) `docker exec admin_cockroachdb_1 ./cockroach sql --database=nakama < /path/to/data.sql`
 but this time I got the following error:
_Error: problem using security settings, did you mean to use --insecure?: problem with CA certificate: not found
Failed running "sql"_

How Can I import this data in the data.sql file into my cdb running inside docker in insecure mode?

**Comment by tim-o** [comment]
Hey @blacklightknight - I saw you posted on the forum with this question as well, I'll follow up with you there and close this out.

**Comment by blacklightknight** [comment]
yup, thanks @tim-o. Sorry for opening the issue here. Reached here before I was able to find the forum.
