### ISSUE TITLE
Docs update kv.raft_log.synchronize with comment

### ISSUE THREAD

**Issue by drewdeally** [cockroachdb/cockroach#26282]
Please Find the kv.raft_log.synchronize description on https://www.cockroachlabs.com/docs/stable/cluster-settings.html

Please add a warning comment, setting this to False will set the cluster to be in an mode where data is not persisted synchronously.

**Comment by petermattis** [comment]
Note that data will still be persisted, but that it won't be persisted in a consistent fashion which will break Raft invariants if a node crashes and restarts. Users should never set this setting to False in production.
