### ISSUE TITLE
deps: Consider replacing UUID package

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#26332]
We currently use version 1.2.0 of github.com/satori/go.uuid. The master branch of that repo contains backwards-incompatible API changes and a major regression that results in UUIDs being partially filled with zeros (satori/go.uuid#73). The maintainer has been unresponsive (PR satori/go.uuid#75 to fix the bug has been open with no response for nearly two months now). It may be time to find a new UUID library.

**Comment by knz** [comment]
We also need to be on the lookout for well-intentioned people on the team who might attempt to refresh our deps. How can we make a blinking neon light warning to not upgrade this package? @benesch thoughts?

**Comment by bdarnell** [comment]
Yeah, as long as we only need v4 UUIDs (and I see no reason to support the other versions), it's simple enough that I see no need for an external dependency. 

>  How can we make a blinking neon light warning to not upgrade this package? 

A pin with a comment in Gopkg.toml should be sufficient.

**Comment by gpaul** [comment]
UUID v4 has structure. Consider using google's uuid package?
https://github.com/google/uuid

**Comment by bdarnell** [comment]
This was done in fd9705b774eb; we no longer use a third-party dependency for UUID generation.
