### ISSUE TITLE
sql: HAVING clause incorrectly processed by the heuristic planner

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#26349]
Postgres:

```
kena=# select 1 having false;
 ?column?
----------
(0 rows)
```

crdb:

```
root@:26257/defaultdb> select 1 having false;
+---+
| 1 |
+---+
| 1 |
+---+
(1 row)
```

cc @RaduBerinde

**Comment by knz** [comment]
the problem is here:

```
func (p *planner) groupBy(
  ctx context.Context, n *tree.SelectClause, r *renderNode,
) (planNode, *groupNode, error) {
  // Determine if aggregation is being performed. This check is done on the raw
  // Select expressions as simplification might have removed aggregation
  // functions (e.g. `SELECT MIN(1)` -> `SELECT 1`).
  if isAggregate := p.txCtx.IsAggregate(n, p.SessionData().SearchPath); !isAggregate {
    return nil, nil, nil
  }
```

we need to process HAVING even if there is no aggregation.

**Comment by RaduBerinde** [comment]
`IsAggregate` returns true if there is a `Having`. We are processing HAVING, and we push it down:
```
root@127.143.38.113:43201/demo> explain (verbose) select 1 having false;
+-------------------------+----------+-------------+---------+-----------+
|          Tree           |  Field   | Description | Columns | Ordering  |
+-------------------------+----------+-------------+---------+-----------+
| render                  |          |             | ("1")   | "1"=CONST |
|  │                      | render 0 | 1           |         |           |
|  └── group              |          |             | ()      |           |
|       └── filter        |          |             | ()      |           |
|            │            | filter   | false       |         |           |
|            └── emptyrow |          |             | ()      |           |
+-------------------------+----------+-------------+---------+-----------+
```
It's just that even with no input, `group` emits 1 row, because of the code I mentioned above.

**Comment by knz** [comment]
oh I see thanks for explaining

**Comment by andy-kimball** [comment]
This is fixed by the cost-based optimizer. It is still a problem with the heuristic planner, however. I suggest we close this out, since we're moving to the optimizer anyway, and this is an edge case.

**Comment by knz** [comment]
I'd be more comfortable closing this by changing the heuristic planner to produce an error in that case. Better no query result than bad results on the fallback path.

**Comment by knz** [comment]
With #31346 the heuristic planner will now produce an error in that case but also refer to this issue as "unimplemented feature"

This issue can be closed when the heuristic planner is removed.

**Comment by jordanlewis** [comment]
@RaduBerinde this is probably closeable, up to you.

**Comment by RaduBerinde** [comment]
Removing this part of the HP is tracked by #34848; we can close this one.
