### ISSUE TITLE
server: log spam from health alerts about underreplicated ranges on single node

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#26343]
Every few secs.
```
W180603 16:05:27.213849 167 server/node.go:802  [n1,summaries] health alerts detected: {Alerts:[{StoreID:1 Category:METRICS Description:ranges.underreplicated Value:26}]}
```
I think we already have some logic for single-node clusters that disables some other similar spam?

**Comment by bdarnell** [comment]
We don't have anything for single-node clusters specifically. The last round of log spam was eliminated via the introduction of the purgatory mechanism for the replica queues.

**Comment by tschottdorf** [comment]
Let's just disable this gossip_alerts thing for clusters that look single-nodeish.

Also, if we did https://github.com/cockroachdb/cockroach/issues/14990#issuecomment-392880795, new clusters could get a zone config of `min_replicas: 1, max_replicas: 3` and the "underreplicated" metric would not fire in that case.

**Comment by bdarnell** [comment]
Even if we added min/max replicas to zone configs, I don't think we'd want to default the minimum to 1. That would swallow too many errors. I'd rather add an explicit single-node mode than do too much to suppress the errors when the cluster is failing to become replicated.
