### ISSUE TITLE
sql: 3-4 unnecessary expression tree traversals to check properties during planning

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#26353]
(This is so gross I first thought it was a joke)

Select expressions are traversed via a tree recursion and a visitor to check properties "does this expression have an aggregation" or "is this a window function application":

- once per target expr by `IsAggregate` in `groupBy()`
- once per target expr by `WindowFuncIsExpr()` in `window()`
- twice per LIMIT, HAVING and other exprs by `AssertNoAggregationOrWindowing()`

All the while `TypeCheck()` is also applied to all these expressions and can determine these properties all the same.

**Comment by RaduBerinde** [comment]
@rytaft I am not sure how many of these traversals optbuilder does? If we can still improve in that area, we should update the issue with up-to-date details; otherwise, we'll close.

**Comment by rytaft** [comment]
This is still happening inside the `optbuilder` code for `LIMIT` and `OFFSET`. I think the reason I left it there was because it was difficult to get the correct error message otherwise. But this is definitely something we should fix -- I've assigned myself to this issue.
