### ISSUE TITLE
sql: Null characters in strings

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#26366]
Our handling of null characters in strings (at least in literals) differs from postgres. 

```
postgres=# select E'\x00';
ERROR:  invalid byte sequence for encoding "UTF8": 0x00

root@127.0.0.1:50159/demo> select E'\x00';
+---------+
| e'\x00' |
+---------+
| \x00    |
+---------+
(1 row)

Time: 482.546µs

```

I'm not sure whether postgres disallows null characters in *all* varchar values or if it's only in literals. 

Additionally, trying to put a literal null character in a string literal reports `unterminated string` (it's possible that this is a client-side bug)

```
$ echo -e "select 'hello\000world';"|cockroach sql --insecure 
pq: unterminated string
DETAIL: source SQL:
select 'hello
       ^
HINT: try \h SELECT
Error: pq: unterminated string
Failed running "sql"
```

This at least is consistent with postgres:

```
$ echo -e "select 'hello\000world';"|psql -Upostgres
ERROR:  unterminated quoted string at or near "'hello"
LINE 1: select 'hello
               ^
```

**Comment by knz** [comment]
The latter is both a client bug in pg and a protocol limitation. If you try to send a nul byte in a packet to a pg server with `cockroach sql`, you get a protocol error.

**Comment by knz** [comment]
Over the course of the years I've paid close attention to semantic issues that may have arisen from accepting NUL bytes, and we've not encountered any.

**Comment by andreimc** [comment]
I am still encountering null bytes

**Comment by knz** [comment]
@andreimc yes, crdb allows nul bytes inside strings. It's one feature where crdb can do more than postgres.

Does it cause any problem in your applications?
