### ISSUE TITLE
sql: MAX(x),MIN(x) should inform index selection

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#2636]
`{MAX,MIN}(x)` should be used to inform index selection when `x` is the first column of an index.

**Comment by bdarnell** [comment]
Or when `x` is not the first column of an index but all preceding columns have been specified. `SELECT MAX(x) FROM t WHERE y = $1` should be able to use an index on `(y, x)`.

**Comment by petermattis** [comment]
Yes, good point.
