### ISSUE TITLE
cli: `debug zip` missing the logs

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#26364]
We recently received a `./cockroach debug zip` file from a user running a 32 node cluster. Curiously, no logs were contained within, for any of the nodes.

This doesn't seem like expected behavior. Perhaps there is a timeout that is too low.

**Comment by garvitjuniwal** [comment]
This happened because the logs were being collected over stdout and being piped to a non-standard location. I think this can be closed.

**Comment by tschottdorf** [comment]
Ack, thanks @garvitjuniwal.
