### ISSUE TITLE
sql: NormalizeExpr and TypeCheckExpr are tangled

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#2638]
It's not clear which function should be run first, and the application of these functions does not commute. For instance, NormalizeExpr does this:
```sql
before: CASE 1 WHEN 1 THEN 'one' WHEN 2 THEN 2 END
after: 'one'
```
Note that this expression does not type-check.

On the other hand, TypeCheckExpr contains the following snippet:
```go
	case Row:
		// NormalizeExpr transforms this into Tuple.

	case *ParenExpr:
		// NormalizeExpr unwraps this.

	case *ComparisonExpr:
		return typeCheckComparisonExpr(t)

	case *RangeCond:
		// NormalizeExpr transforms this into an AndExpr.
```

**Comment by petermattis** [comment]
Yes, `NormalizeExpr` and `TypeCheckExpr` are tangled. I don't think we should try to disentangle, but instead should probably just have `NormalizeExpr` perform type-checking via calls into `TypeCheckExpr`. Maybe. I need to think about this more.
