### ISSUE TITLE
libroach: darwin not building libroachccl tests properly 

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#26385]
Running `make check-libroach` on darwin fails with:

```
5: Test command: /Users/benesch/go/native/x86_64-apple-darwin17.5.0/libroach/ccl_db_test "--gtest_filter=LibroachCCL.DBOpenHook" "--gtest_also_run_disabled_tests"
5: Test timeout computed to be: 10000000
5: Running main() from gtest_main.cc
5: Note: Google Test filter = LibroachCCL.DBOpenHook
5: [==========] Running 1 test from 1 test case.
5: [----------] Global test environment set-up.
5: [----------] 1 test from LibroachCCL
5: [ RUN      ] LibroachCCL.DBOpenHook
5: /Users/benesch/go/src/github.com/cockroachdb/cockroach/c-deps/libroach/ccl/db_test.cc:28: Failure
5: Value of: s.ok()
5:   Actual: false
5: Expected: true
5: expected error "on-disk version does not support encryption, but we found encryption flags", got "DBOptions has extra_options, but OSS code cannot handle them"
5: /Users/benesch/go/src/github.com/cockroachdb/cockroach/c-deps/libroach/ccl/db_test.cc:33: Failure
5: Value of: s.ok()
5:   Actual: false
5: Expected: true
5: expected error "failed to parse extra options", got "DBOptions has extra_options, but OSS code cannot handle them"
```

This error shows that the `DBOpenHook` called is the OSS one when it's supposed to be the CCL one.

**Comment by mberhault** [comment]
@benesch: when you have a chance, can you try running `make check-libroach` to see if this is still the case? I can look into it once I get my hands on a Mac.

**Comment by benesch** [comment]
Well, now it's broken for a different reason.

```
/Users/benesch/go/src/github.com/cockroachdb/cockroach/c-deps/libroach/testutils.cc:16:10: fatal error: 'experimental/filesystem' file not found
#include <experimental/filesystem>
         ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

filesystem is c++17 (not sure about experimental/filesystem), so probably best to avoid. :/

**Comment by mberhault** [comment]
experimental is C++11 on all compilers. XCode took its sweet time with it, but it should be available now. I believe Matt T ran into the same issue a while back and just upgraded.

**Comment by benesch** [comment]
Gah. This laptop is still running Sierra. I'll try again on my work laptop.

**Comment by benesch** [comment]
Shoot. It's only available in Xcode 10 beta. I'd rather not upgrade to that.

**Comment by mberhault** [comment]
Ah. Odd. @mrtracy: do you remember what you upgraded to when you ran into the missing `experimental::filesystem` error in `make check-libroach`?
