### ISSUE TITLE
sql: `sql.trace.log_statement_execute = true` should not log internal queries

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#26395]
Logging internal queries pollutes the logs and isn't helpful (most of the time). 

While It can be useful to show those internal queries, most customers will only want to see their queries in the log.
This setting could be changed from a bool to a an enum, or a second cluster setting could be added.

**Comment by knz** [comment]
I disagree. If there is any problem like a query taking too long, this must be revealed in the logs.

The internal queries are prefixed with a label that indicates they are internal anyway, so a user can easily grep the logs.

**Comment by knz** [comment]
We adressed this with structured logging
