### ISSUE TITLE
sql: hang in parallel EXPERIMENTAL_AUDIT SET OFF

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#26411]
I'm testing schema changes in the RSG by executing a bunch of `alter_table_cmd` productions in parallel on the same column. Various times now the RSG has timedout (15s without the query completing) when executing `ALTER TABLE ident.ident EXPERIMENTAL_AUDIT` in 4 go routines in parallel.

It executed that statement some hundreds of times before without problem. When I have it run only that statement it doesn't break. That is, this seems to break only in the presence of a bunch of other alter_table_cmd productions that have been previously ran. Thus it is possible this is a red herring covering up another problem.

Assigning because you showed up in the blame for EXPERIMENTAL_AUDIT. Stack trace attached once all the (4 in this case) go routines had been stalled.

[trace.txt](https://github.com/cockroachdb/cockroach/files/2071239/trace.txt)

**Comment by knz** [comment]
This statement does nothing else than a schema change. I don't have anything to say other than "schema change". @vivekmenezes please take this.

**Comment by mjibson** [comment]
Ok. Since it is so simple and I haven't seen it fail when that's the only statement it executes, I would have to guess the RSG is then maybe not generating other certain kinds of statements that may also cause a hang. However it is interesting that when it does hang all of the go routines are attempting to execute this statement (I've seen up to 20) and not any other.

**Comment by mjibson** [comment]
I haven't seen this particular hang in a while so I think we can close this issue. I think this was when I was doing some experiments, so I don't remember the exact command, but it was certainly exactly like the nightly RSG tests that run, and they haven't hit this hang in months.
