### ISSUE TITLE
sql: condition for aggregation planning doesn't look at ORDER BY

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#26419]
pg:

```
kena=# select 123 from kv order by max(v);
 ?column?
----------
      123
(1 row)
```

crdb:

```
root@:26257/defaultdb> select 123 from kv  order by max(v);
pq: expression 'max("$1")' has aggregate
```

I think the error is that IsAggregate() doesn't check the order by expressions. 

cc @RaduBerinde

**Comment by RaduBerinde** [comment]
Very strange query. `select 123 from kv` would return as many rows as the table has. Adding an `order by max(v)` changes the semantics completely, always returning one row. This seems to go against the [documentation](https://www.postgresql.org/docs/9.5/static/sql-select.html#SQL-ORDERBY) which says that an ORDER BY just reorders rows. I'm thinking the fact that this query works in pg is more of a consequence of implementation than an explicit semantic decision.

**Comment by RaduBerinde** [comment]
I tried it with the optimizer, it crashes.. CC @rytaft

**Comment by rytaft** [comment]
Ah right - I added a panic there. The error is "aggregate function is not allowed in this context". I can turn that panic back into an error, unless we want to try to support this syntax...

**Comment by knz** [comment]
Stepping back, apparently for pg aggregations in ORDER BY are valid, for example `SELECT count(v) FROM kv ORDER BY max(v)` 

It's a little bit weird because IMHO "ORDER BY" specifies the order pre-aggregation, so having an aggregate in there is a little strange.

Do you think we should reject aggregates in ORDER BY altogether?

**Comment by RaduBerinde** [comment]
No, I think `SELECT count(v) FROM kv GROUP BY k ORDER BY max(v)` is reasonable and semantically sound. Even `SELECT 1 FROM kv GROUP BY k ORDER BY max(v)` is reasonable, because of the group by: the order by doesn't change the grouping, it just changes the order of the results.

**Comment by knz** [comment]
so do you think we should reject aggregations in ORDER BY unless either:

- there is a GROUP BY clause, or
- there is an aggregation in the select targets already

?

**Comment by RaduBerinde** [comment]
> It's a little bit weird because IMHO "ORDER BY" specifies the order pre-aggregation, so having an aggregate in there is a little strange.

ORDER BY specifies the order of the post-aggregation results. Something like `SELECT x FROM xy GROUP BY x ORDER BY y` is not valid. That's why the order by clause follows the group by clause.

> so do you think we should reject aggregations in ORDER BY unless either:
> - there is a GROUP BY clause, or
> - there is an aggregation in the select targets already

Yes.

**Comment by knz** [comment]
ok will work on that asap
