### ISSUE TITLE
jobs: unskip and fix control tests, build better job-control testing infra

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#26428]
The tests around job control need some love.

Currently many of them are skipped due to flakiness. Some have rotted and no longer pass at all if unskipped (BackupRestoreJobControl). Our testing helper blocking response filter has been another source if trouble, causing tests to hang rather than fail.

It seems like we should take a holistic look at testing infra for jobs, perhaps adding knobs to the registry to block on things like resuming or pausing, plumbing cancelable contexts though to these blocking helpers so they don't hang indefinitely and making sure we have a deterministic, non-flaky foundation of helpers on which we can write more jobs-related tests (e.g. #26426 )

**Comment by dt** [comment]
I think this is basically done with the exception of the infamous `TestBackupRestoreControlJob`

**Comment by jordanlewis** [comment]
@spaskob can you look at this and close if it's no longer relevant? It's quite old.

**Comment by spaskob** [comment]
I spent quite some time last release cycle imporving `jobs_test.go` and there are individual issues tracking tests that are still skipped.
I am going to close this one.
