### ISSUE TITLE
sql: make `SHOW TRACE FOR` a wrapper around session tracing

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#26421]
`SHOW TRACE FOR` is less powerful than session tracing, as it can't capture the trace during planning.

When given the choice between session tracing and SHOW TRACE FOR, users likely naturally gravitate towards `SHOW TRACE FOR`, but the output is less clear and [often confusing](https://github.com/cockroachdb/cockroach/issues/25411).

We should consider deprecating `SHOW TRACE FOR`. This means undocumenting it as soon as possible so that it can be removed at some point in the future.

See https://github.com/cockroachdb/cockroach/issues/25411#issuecomment-393491690 for context.

@knz assigning you to put this into the proper hands.

**Comment by jordanlewis** [comment]
I use this feature all the time. It's useful! Please don't delete it.

**Comment by jordanlewis** [comment]
Why don't we change its semantics so it does a session trace under the hood before re executing the statement, stopping the session trace, and outputting?

**Comment by knz** [comment]
@jordanlewis that's exactly what I had in mind.

**Comment by tschottdorf** [comment]
> Why don't we change its semantics so it does a session trace under the hood before re executing the statement, stopping the session trace, and outputting?

I thought if that were an option, we'd be doing it already. Would also prefer this if possible. Changed the title.
