### ISSUE TITLE
rpc: make retry options configurable per-client

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#2642]
This is currently global. See #2641.

**Comment by tschottdorf** [comment]
The state of play:
```
09:29 $ git grep -F client.Open
acceptance/main_test.go:        db, err := client.Open(stopper, str)
acceptance/terrafarm/farmer.go:// ConnString returns a connection string to pass to client.Open().
cli/kv.go:      db, err := client.Open(stopper, fmt.Sprintf(
client/client_test.go:  db, err := client.Open(stopper, fmt.Sprintf("rpcs://%s@%s?certs=%s",
client/client_test.go:  db, err := client.Open(stopper, fmt.Sprintf("rpcs://%s@%s?certs=%s",
client/client_test.go:  db, err := client.Open(s.Stopper(), fmt.Sprintf("%s://%s@%s?certs=%s",
client/db_test.go:      db, err := client.Open(s.Stopper(), fmt.Sprintf("rpcs://%s@%s?certs=%s",
client/db_test.go:      db, err := client.Open(s.Stopper(), "rpc://foo@"+s.ServingAddr())
client/db_test.go:              _, err := client.Open(s.Stopper(), test.addr)
client/doc.go:  db, err := client.Open("rpcs://root@localhost:26257")
client/doc.go:  db, err := client.Open("rpcs://root@localhost:26257")
client/doc.go:  db, err := client.Open("rpcs://root@localhost:26257")
kv/db_test.go:  db, err := client.Open(stopper, fmt.Sprintf("rpcs://%s@%s?certs=%s",
server/status/feed_test.go:     db, err := client.Open(s.Stopper(), fmt.Sprintf("rpcs://%s@%s?certs=%s",
sql/main_test.go:       kvDB, err := client.Open(s.Stopper(), fmt.Sprintf("rpcs://%s@%s?certs=%s",
```

You can see that almost all uses glue things together with `fmt.Sprintf`. Given that this API is internal anyway, I think it makes sense to pass the options in as a struct (which would embed a retry options struct) instead of the query string.

**Comment by ajayaa** [comment]
@tschottdorf  makes sense. I didn't like the idea of putting everything in url but was not sure if changing signature was the right solution. Thanks for the clarification.

I think all the function use should be modified to use [DefaultTxnRetryOptions](https://github.com/cockroachdb/cockroach/blob/master/client/txn.go#L37). What do you think?

**Comment by tschottdorf** [comment]
Yeah. My suggestion would be to remove all the query components, so you'd have a struct

```go
type Options struct {
  TxnRetryOptions, SenderRetryOptions *retry.Options // if `nil`, use defaults
  Certs string
   // ...
}
```

and then `client.Open(stopper, "127.0.0.1:26257", client.Options{ /* .. */ })` (I haven't looked at this as much, so don't take this as for anything more than an initial suggestion).

**Comment by petermattis** [comment]
Passing a URL to `client.Open` made a lot more sense when that was the expected end-user interface. Switching to an options struct or additional parameters to `client.Open` definitely makes sense now. A goal of any work in this area should be to get rid of any modification to `client.DefaultTxnRetryOptions` by tests and to un-export that variable.

PS There are no `SenderRetryOptions` now
