### ISSUE TITLE
sql: agg-in-agg assertion should not recurse

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#26423]
`(v *extractAggregatesVisitor) VisitPre` recurses into the sub-expressions of the window applications to check there is no aggregation-in-aggregation or window-in-aggregation.

This is inefficient. Instead the check should be done on the return path of the recursion, using scalar properties computed on the way down.

cc @RaduBerinde  the opt code is affected in the same way - see TODO in `hasAggregates()`

**Comment by RaduBerinde** [comment]
CC @rytaft

**Comment by rytaft** [comment]
This has been fixed in the optimizer.

**Comment by rytaft** [comment]
`extractAggregatesVisitor` doesn't exist anymore. Closing.
