### ISSUE TITLE
sql: stripped down benchmarking infrastructure tool

### ISSUE THREAD

**Issue by rjnn** [cockroachdb/cockroach#26437]
This is an issue (an RFC-lite) to discuss a tool that I've been thinking about building, to get some early design feedback from @petermattis and @danhhz.

### Background
Benchmarking SQL execution performance so far has been in two directions:

1. `roachtest` and `roachprod` like tools that simulate whole-cluster workloads.
2. `go bench` benchmarks that simulate individual subcomponents.

There's been some frustration, as each tool is suited to particular tasks, and poorly suited for others.

For instance, the subcomponent benchmarks are not thorough enough to test enough working parts to get a holistic understanding. In particular, composing a set of subcomponent benchmarks to get an "end-to-end" understanding is nonlinear and nontrivial due to the overlap in the set of resources that components use. Thus, subcomponent benchmarks are useful to make pointed improvements in _known_ bottlenecks, but are poor for discovering where the bottlenecks are.

On the flip side, whole-cluster workloads, while great for whole cluster workloads like TPC-C, are poor for testing _exclusively_ SQL execution while holding the rest of the software stack constant, due to the high amounts of variance experienced. Running CockroachDB clusters do lots of different things at different layers, including but not limited to: splitting, rebalancing, and replicating ranges; moving leases; compacting SSTs, maintaining queues and rate limiting deferred work.

### A better tool for SQL execution

This reveals a desideratum: an intermediate benchmarking layer, designed to give us reproducible benchmarking results, designed to measure SQL execution speed. I propose building the following:

We create a stripped down tool, which hooks up to a RocksDB instance from a shut down cluster. It spawns a DistSQL server hooked up to a RocksDB engine in read-only mode. It takes a single query (as a command line parameter), parses, and executes the query. The only additional goroutines spawned are in DistSQL. We set up RocksDB in read only mode, and turn off compactions.

There are two levels of this tool:

1. Single node mode. We take a single query, run it on the underlying RocksDB instance. 
2. Multi-node mode. This setting is more complicated, and deferred for later work. The single node mode would be sufficiently useful on its own.

The main complication comes in hooking up DistSQL to RocksDB. Here are some parts that need to be built:

1. We need to populate the `planningCtx` to enable placing the `tableReaders` so that DistSQL physical planning can happen.
2. We need a `client.DB` that's hooked up in a way that subverts all of Raft. `KV GET` commands should run directly on the underlying store. This part seems difficult, but I do know that @danhhz got a similar setup running on top of BACKUPs at one point in the past. I would appreciate any thoughts as to how @danhhz made this happen.
3. We need to hook up that client.DB to a `RowFetcher` thats usable by `TableReader`s.
4. We need to plumb a single context that's used to parse, optimize, and then run this query using the above infrastructure.

cc @cockroachdb/sql-execution, @jordanlewis.

**Comment by danhhz** [comment]
> We create a stripped down tool, which hooks up to a RocksDB instance from a shut down cluster.

I'd love for this tool to take in a workload.Generator impl and give you back your rocksdb instance. The easy way is to start up a cluster, use sql to ingest, and shut it down. But if you only need user table data, we're already doing something very similar to make backups that have the right kvs in them.

> We need a client.DB that's hooked up in a way that subverts all of Raft. KV GET commands should run directly on the underlying store. This part seems difficult, but I do know that @danhhz got a similar setup running on top of BACKUPs at one point in the past. I would appreciate any thoughts as to how @danhhz made this happen.

Before andrei's refactors, this was more or less trivial. `client.DB` was a wrapper around the `client.Sender` interface which takes a BatchRequest and returns a BatchResponse. You just need to implement enough of it to make whatever you're doing work, which is mostly just ScanRequest. I just glanced and client.DB is much more complicated post-refactors, but dunno how much harder it makes your life.

> We need to hook up that client.DB to a RowFetcher thats usable by TableReaders.

RowFetcher has a `StartScanFrom` which lets you provide your own `kvFetcher` implementation. This might be easier than trying to make your own `client.DB`. There's some plumbing there, but it's possible that it's not so hard to add an option to TableReaderSpec that wraps a rocksdb instance in a kvFetcher and hooks it up directly to your RowFetcher. Depends on how much of our stack you want in your benchmarks.

**Comment by andreimatei** [comment]
Since you're only proposing doing stuff for single-node clusters, then I'm not sure I understand why the magic you describe is needed? Why does anything need to bypass Raft, for example?
If we disable all the queues (most of the already allow that through testing knobs), and maybe RocksDB compactions, what noise is left exactly?

**Comment by jordanlewis** [comment]
I'm +1 on what @andreimatei is saying. I thought we were just talking about disabling the various background processes of a cluster. I think most if not all of those are already accessible via testing knobs, like Andrei is saying. What else would we be missing after disabling those things?

**Comment by danhhz** [comment]
My instinct here is to first try building something like what arjun is describing, otherwise you're likely to be playing whack-a-mole forever. OTOH, it's totally possible that you'd have to duplicate so much of the stack to get it working that it's not worth it. I'd vote on some prototyping first

**Comment by petermattis** [comment]
@arjunravinarayan's proposal would certainly isolate SQL execution from other parts of the system. I'm not clear on how it would be achieved, though.

> On the flip side, whole-cluster workloads, while great for whole cluster workloads like TPC-C, are poor for testing exclusively SQL execution while holding the rest of the software stack constant, due to the high amounts of variance experienced. Running CockroachDB clusters do lots of different things at different layers, including but not limited to: splitting, rebalancing, and replicating ranges; moving leases; compacting SSTs, maintaining queues and rate limiting deferred work.

Most of these can be disabled, though knobs may need to be added to make doing so easy. Even RocksDB compactions can be disabled. 

> We need a client.DB that's hooked up in a way that subverts all of Raft

Read operations don't go through Raft, so what are you trying to subvert? Getting a multi-node setup running which doesn't use the existing store machinery (or shuts most of it down), feels like a large task. Perhaps I haven't though it through enough.

**Comment by jordanlewis** [comment]
We've done a lot of benchmarking changes since this was filed, closing.
