### ISSUE TITLE
storage: Cancel pending lease requests in leasePostApply

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#26448]
While investigating #26391, I'm seeing the following cause some requests to take longer than necessary (there's a bit of speculation here because I haven't been able to reproduce it with the right amount of logging).

1. The cluster restarts, putting all nodes in a dormant state
1. One node receives a request, triggering a (successful) raft election
1. A second node receives a request. Both nodes attempt to acquire the lease simultaneously.
1. One node gets the lease and proceeds
1. The other node waits for its lease request to finish, blocking the request that triggered the lease. (Other requests return NotLeaseHolderErrors immediately)
1. A few seconds later, the `reasonTicks` proposal refresh is triggered. The lease request is refreshed and proposed again. Note that due to out-of-order conditions in refreshProposalsLocked, this reproposal occurs even though this command has not been pending for the entire raft election timeout.
1. The refreshed lease request fails because a conflicting lease has already been granted.
1. This error bubbles up and the request that triggered the lease is retried on the correct lease holder.

In `leasePostApply`, we should cancel all pending proposals instead of leaving them to time out via reasonTicks. This is a fairly rare occurrence because new leaseholders are usually accompanied by new raft leaders, and we trigger an immediate refresh on raft leadership change.

**Comment by tschottdorf** [comment]
Could you elaborate on 5.)? Wouldn't that second lease get a forced error right away when it applies which notifies the goroutine waiting for the lease?

**Comment by bdarnell** [comment]
It'll get a forced error when it applies, but it doesn't apply right away. Why doesn't it? Now I'm not sure. I think I was getting a couple of cases mixed up: If the node requesting the lease knows the raft leader, then it should apply. If it doesn't, there should be a `reasonNewLeader` before the `reasonTicks` fires. Maybe I was just getting confused with the spurious retries and the fact that `reasonTicks` is firing too soon. 

We should see if the election-after-restart is still seeing a lot of requests taking 3s after #26509. If not, we can consider this issue closed.

**Comment by tschottdorf** [comment]
This is roughly the below diff, right? (That diff actually deadlocks `make test PKG=./pkg/storage`, so take it with a grain of salt).

```diff
diff --git a/pkg/storage/replica_proposal.go b/pkg/storage/replica_proposal.go
index 21372cddec..ff90fa9a1c 100644
--- a/pkg/storage/replica_proposal.go
+++ b/pkg/storage/replica_proposal.go
@@ -280,6 +280,13 @@ func (r *Replica) leasePostApply(ctx context.Context, newLease roachpb.Lease) {
        // lease but not the updated merge or timestamp cache state, which can result
        // in serializability violations.
        r.mu.Lock()
+       if cancel := r.mu.pendingLeaseRequest.cancelLocked; cancel != nil && r.mu.pendingLeaseRequest.nextLease.Sequence < newLease.Sequence {
+               // If there's an inflight lease request on this replica but we see a higher
+               // sequence lease pop out of Raft, cancel the request. Otherwise, the requests
+               // blocked on it will have to wait until their own outdated lease request
+               // applies, which can add unnecessary latency.
+               cancel()
+       }
        r.mu.state.Lease = &newLease
        expirationBasedLease := r.requiresExpiringLeaseRLocked()
        r.mu.Unlock()
```

Not sure we're going to get to this in 2.1 (mostly because writing the test takes time).

**Comment by bdarnell** [comment]
Yes, I think so.
