### ISSUE TITLE
sql: support user-defined schemas between database and table

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#26443]
CockroachDB currently only supports 1 pre-defined physical schema "public" in every database plus the 3 virtual schemas (`pg_catalog` etc).

Applications also want to create other physical schemas alongside "public" via CREATE SCHEMA etc.

Needed e.g. for the PGAdmin test suite.

@robert-s-lee also requested this on a customer's behalf.

@awoods187 perhaps we should put this on the radar too.

**Comment by knz** [comment]
Note the RFC #13319 was already trying to go in this direction. We can resurrect.

**Comment by awoods187** [comment]
@robert-s-lee  mentioned coming across this on a number of customers especially when using microservices or multi-tenant operations.

**Comment by nstewart** [comment]
Just ran into this when doing a basic migration using `IMPORT PGDUMP`

**Comment by knz** [comment]
RFC: #30916

**Comment by knz** [comment]
re-adding the 2.2 milestone because this work item landed on the roadmap

**Comment by knz** [comment]
@bobvawter as discussed the next step here is to make a call about which data structures to use for name resolution, by exploring experimentally the alternatives presented in #30916.

**Comment by gagandeep** [comment]
RFC https://github.com/cockroachdb/cockroach/pull/30916 is now merged. This is open for what other things? Sorry, If I missed anything.

**Comment by jordanlewis** [comment]
This will be available in 20.2. Thanks for waiting!
