### ISSUE TITLE
ui: you can still go to the login page if login is disabled

### ISSUE THREAD

**Issue by vilterp** [cockroachdb/cockroach#26440]
1. start cluster in secure mode
2. go to login page
3. restart cluster in insecure mode
4. refresh the browser (still at `/login`)

expected: redirects me to front page, since login is no longer necessary.

actual: just see the login page. signing in appears to work (even though it's doing nothing) and redirects me to overview page as expected.

**Comment by vilterp** [comment]
FYI @couchand

**Comment by couchand** [comment]
sure, but 🤷‍♂️
