### ISSUE TITLE
roachtest: `workload bank --ranges 100000` lies about splits performed

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#26456]
```
[tschottdorf@toblerone cockroach (roachtest/quiescing)]$ ./bin/workload run bank --init
I180606 11:37:25.709980 1 workload/workload.go:380  starting 9 splits
_elapsed___errors__ops/sec(inst)___ops/sec(cum)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)
      1s        0        12775.9        13784.5      1.0      2.2      4.2     12.1 transfer
      2s        0        14075.9        13930.2      1.0      2.2      3.9     11.0 transfer
^C
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
    2.6s        0          35619        13794.7      1.2      1.0      2.2      4.2     28.3  transfer

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__result
    2.6s        0          35619        13794.7      1.2      1.0      2.2      4.2     28.3
[tschottdorf@toblerone cockroach (roachtest/quiescing)]$ ./bin/workload run bank --ranges 10000
I180606 11:37:30.066127 1 workload/workload.go:380  starting 9999 splits
I180606 11:37:30.239928 1 workload/workload.go:437  finished 1000 of 9999 splits
I180606 11:37:30.394808 1 workload/workload.go:437  finished 2000 of 9999 splits
I180606 11:37:30.555803 1 workload/workload.go:437  finished 3000 of 9999 splits
I180606 11:37:30.712623 1 workload/workload.go:437  finished 4000 of 9999 splits
I180606 11:37:30.867172 1 workload/workload.go:437  finished 5000 of 9999 splits
I180606 11:37:31.021684 1 workload/workload.go:437  finished 6000 of 9999 splits
I180606 11:37:31.179476 1 workload/workload.go:437  finished 7000 of 9999 splits
I180606 11:37:31.336047 1 workload/workload.go:437  finished 8000 of 9999 splits
I180606 11:37:31.492673 1 workload/workload.go:437  finished 9000 of 9999 splits
```

But the cluster does not have 10000 ranges (it has exactly as many as before).

**Comment by tschottdorf** [comment]
I'm also confused by https://github.com/cockroachdb/cockroach/blob/0a8d2e25d41ce5dfd9685749e0f127b82aee73d9/pkg/ccl/backupccl/backup_test.go#L105 because that method that is called there seems to live in workload as well: https://github.com/cockroachdb/cockroach/blob/104c324ec85274cdbecdb0c91356efd19da5dcfc/pkg/workload/workload.go#L380

@danhhz, could you comment?

**Comment by danhhz** [comment]
The splits method in bank is detritus and should be removed.

I think the first one is because bank silently truncates the number of splits to be the number of rows in the table. This can and should be checked in validate to prevent surprise. But, I'm a little confused about "But the cluster does not have 10000 ranges (it has exactly as many as before)." I'd expect you to have 1000 ranges (the default number of rows) not 10 (the number you made in the first line). I just tested it and saw the behavior I'm expecting, are you sure this is what you saw?

I'm happy to make both these changes.

**Comment by tschottdorf** [comment]
```
./bin/workload run bank --init
I180607 12:14:03.553987 1 workload/workload.go:380  starting 9 splits
```

I think that explains it, it's not doing 1k splits by default but 9. However, the `rows` default is indeed 1000. I think workload splits between each "batch" of inserts and I'm just going to assume that it inserts in batches of 100 in this case.

Mystery solved?

**Comment by danhhz** [comment]
Workload doesn't do any splitting unless the Generator requests them. The 9 splits are coming from the default of 10 for the --ranges flag, I think. `ranges` was just being truncated to `rows` because of the way `bank` is implemented

**Comment by danhhz** [comment]
To be more explicit:

`--rows=1000 --ranges=10` ends up with 9 splits
`--rows=1000 --ranges=10000` ends up with 999 splits, but with my PR will error instead

if unspecified, the default for the rows flag is 1000 and the default for the ranges flag is 10
