### ISSUE TITLE
sql: alter column type round trip formatting

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#26489]
Parse followed by Format is not idempotent: "ALTER TABLE ident.ident ALTER COLUMN ROLLUP TYPE BIT ( 140 ) ARRAY" -> "ALTER TABLE ident.ident ALTER COLUMN rollup TYPE BIT(140)[]" != "ALTER TABLE ident.ident ALTER COLUMN rollup TYPE BIT(140)[] USING 140"

**Comment by knz** [comment]
Two things:

- the type BIT in CockroachDB is incorrectly implemented. @bobvawter I would be grateful if you could also sneak a patch to reject column type conversions that request an unsupported bit precision (I think that's anything above 63 currently). The example 140 here would cause completely bogus results with CockroachDB.

- please double check here for the example what the intended behavior really is. I am not sure that the current behavior (pretty-printing `BIT (N) ARRAY` as `BIT(N)[]`) is invalid. I don't think Matt has written enough words to clearly specify what needs to be done :)

**Comment by mjibson** [comment]
Yeah sorry I was unclear. This was found with RSG and I just pasted the error message in with no explanation.
