### ISSUE TITLE
ui: events table view on metrics dashboards does not refresh

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#26506]
I had the UI open for a few hours. Without switching metrics pages (was on the SQL dashboard). When I looked at it again after a few hours, I was initially confused by events that claimed that my table had been created only 25min prior. This was how long it had been initially, and the timestamps are never refreshed. (I also assume new events wouldn't have shown up).

It's reasonable to assume that some users are going to leave specific pages open for extended periods of time, so that should work better.

@couchand for triage.

**Comment by a-robinson** [comment]
Hm, this was reported/fixed over a year ago :(

https://github.com/cockroachdb/cockroach/issues/14164
https://github.com/cockroachdb/cockroach/pull/15502

Although it may just be that timestamps don't get updated if no new events are found.
