### ISSUE TITLE
engine: reconsider allow_concurrent_memtable_write option

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#26512]
RocksDB supports two modes of write concurrency: single writer and multiple writers. We currently use the latter mode through the [`allow_concurrent_memtable_write`](https://github.com/facebook/rocksdb/blob/45b6bcca9877ffffe3c4d7386089f41a128d7256/include/rocksdb/options.h#L808) setting. Concurrency is implemented via atomic operations and the difference in implementation between the two modes comes down to whether insert uses compare-and-swap operations or atomic store operations. 

Now that all writes to RocksDB are batched through `rocksDBBatch.Commit`, we should reconsider whether multiple writers are needed and whether we should move to the single writer mode. One would [expect](https://spcl.inf.ethz.ch/Research/Parallel_Programming/Atomics/) that an atomic store will have lower latency and higher throughput than an atomic CAS, so this might provide a nice performance win for MemTable writes. It might also be negligible.

**Comment by nvanbenschoten** [comment]
Naively setting this option to `false` without tweaking anything else results in a 15% reduction in throughput when running `./tpcc -load -duration=5m --no-wait -mix='newOrder=1'` on my laptop. This indicates to me that we do still rely on concurrent memtable writes at some point in our persistence stack. If we're going to get any speedup from this change, we'll need to gain a deeper understanding about this option and under what situations we'd expect to see it improve throughput.

**Comment by nvanbenschoten** [comment]
The decision of how to handle concurrent vs. non-concurrent MemTable writes is [here](https://github.com/facebook/rocksdb/blob/92ee3350e0ae02c0973af0fbd40fb67b0b958128/db/memtable.cc#L476).

Notably, this code reveals that non-concurrent writes use the Skiplist MemTable's `InsertWithHint`  method, which is described to some degree [here](https://github.com/facebook/rocksdb/wiki/MemTable#insert-with-hint) in more detail [here](https://github.com/facebook/rocksdb/blob/92ee3350e0ae02c0973af0fbd40fb67b0b958128/memtable/inlineskiplist.h#L93-L99):
```
  // Inserts a key allocated by AllocateKey with a hint of last insert
  // position in the skip-list. If hint points to nullptr, a new hint will be
  // populated, which can be used in subsequent calls.
  //
  // It can be used to optimize the workload where there are multiple groups
  // of keys, and each key is likely to insert to a location close to the last
  // inserted key in the same group. One example is sequential inserts.
```

**Comment by petermattis** [comment]
Huh? I'm surprised that disabling concurrent insert hurts throughput. And now I'm also surprised that #26760 helped throughput given that the insert-with-hint optimization isn't available for concurrent inserts.

**Comment by nvanbenschoten** [comment]
> And now I'm also surprised that #26760 helped throughput given that the insert-with-hint optimization isn't available for concurrent inserts.

Trying to figure this out send me down a rabbit hole. It turns out that there are two memtable skiplist implementations: `SkipList` and `InlineSkipList`. They're similar except that `InlineSkipList` stores key bytes inline. The fast-path I thought we were hitting in #26760 is on `SkipList` and it's independent of whether concurrent inserts are used. The fast-path referenced here is on `InlineSkipList` and is only accessible when concurrent inserts are disabled. I don't yet understand when each is used.

**Comment by petermattis** [comment]
`InlineSkipList` is used for the `MemTable`. `SkipList` is used for `WriteBatchWithIndex`. I think (trust, but verify).

My understanding is that `InlineSkipList` stores keys, values and nodes in an arena (i.e. it is more than just the keys that are stored inline).

**Comment by petermattis** [comment]
No longer relevant now that we've moved off of RocksDB.
