### ISSUE TITLE
ui: query detail page: embed distsql visualizer

### ISSUE THREAD

**Issue by vilterp** [cockroachdb/cockroach#26527]
Linking to the external visualizer from the SQL shell makes sense, because we may not know what host/port your admin UI is at. But on the query detail page (#26525), we'll have the DistSQL plan and should be able to show the viz inline, without having to link to a separate site.

The code lives here https://github.com/cockroachdb/cockroachdb.github.io/tree/master/distsqlplan; maybe we should extract it into an NPM package and use it from both `cockroachdb.github.io` and the admin UI?

FYI @piyush-singh

**Comment by jordanlewis** [comment]
We've got different plans for this one.
