### ISSUE TITLE
sql: descriptor cache needs to handle schema modifications

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#2655]
Worst case scenario: within a single sql transaction, modify the schema (eg: change index, drop table, etc..), then perform a standard operation on this modified table.
If the cache is populated, the planner will use the cached version of the schema rather than the current transaction value.
An example of this can be found in `sql/descriptor_cache_test.go:TestDescriptorCacheSchemaMutation`

**Comment by petermattis** [comment]
This problem is being handled by the table lease descriptor and online schema change work. See #2845.
