### ISSUE TITLE
gossip: change Gossip.systemConfig from pointer to value (and propagate throughout)

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#2657]
See comments on #2599

**Comment by petermattis** [comment]
@tamird This is the kind of cleanup you enjoy, though I'm not sure if it is worth it. Feel free to close if it seems unnecessary.

**Comment by tamird** [comment]
The sql side of this is already done. Gossip still internally stores a pointer, which could be made a value.
