### ISSUE TITLE
sql: support concatenating more types together

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#26585]
Found in #26584:

```sql
> SELECT -- ... some stuff
     CASE WHEN rolconnlimit > 0
               THEN e'\\n  CONNECTION LIMIT ' || rolconnlimit
               ELSE ''
     END
   FROM pg_roles
```

where `rolconnlimit` is an integer.

Arguably since `||` is a string-only operator we could support defining `||` over `types.Any` and then force-coerce (`PerformCast`) both operands to string.

**Comment by justinj** [comment]
I'm not completely sure what you mean by "string-only operator", but I think there are cases that are different from what you're describing:
```
d=# select '[1,2,3]' || '[4,5,6]'::jsonb;
      ?column?
--------------------
 [1, 2, 3, 4, 5, 6]
(1 row)
```

**Comment by knz** [comment]
Oh ok I was not aware of that one :)

It makes the story a bit more difficult. Perhaps we can solve instead by programmatically producing all the overloads, with each combination of types adding the coercions to one side or the other.

**Comment by jordanlewis** [comment]
This is done! 🎉
