### ISSUE TITLE
sql: implement database object comments

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#26617]
PostgreSQL supports adding descriptive comments on arbitrary database objects: https://www.postgresql.org/docs/10/static/sql-comment.html

This is commonly used in UI tools to show a descriptive message to the user about the purpose of a table, column, etc.

Besides compatibility with pg, adding this feature to CockroachDB would enable us to produce contextual help for the various virtual tables in `crdb_internal`. 

/cc @tschottdorf

**Comment by BramGruneir** [comment]
Are comments actually used?  I've never seen them in production deployments.

This seems like a nice to have, but I don't think it should be prioritized over stability, performance, compatibility or even new features.  
Furthermore, it would have to be supported by the Admin UI team as well.

**Comment by jordanlewis** [comment]
Thanks to @hueypark for taking care of this one.
