### ISSUE TITLE
IMPORT: investigate switching to vitess for mysql parsing

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#26635]
We're currently using github.com/xwb1989/sqlparser, which is extracted from vitess, providing a usable Go MySQL parser as a standalone project. It appears to track upstream (they have scripts/patches used to re-run the extraction), meaning any patches we want to submit to extend or add functionality need to be written against and submitted to upstream. Given that it, we might just want to depend on upstream directly if we can do so without significant complication or extra transitive dependencies -- we should investigate what doing so would look like (or if there are any other options for streaming MySQL parsers callable from Go).

**Comment by dt** [comment]
Eh, I tried this today and vitess imports `flag` all over the place, registering flags deep inside helper libraries so I don't think it looks like it'll be easy to consume its libraries as libraries.

**Comment by mjibson** [comment]
Wait but why does that matter if we're only importing this particular package?

**Comment by dt** [comment]
the `sqlparser` package itself is one of the ones that imports `flag` and registers a flag, and it also depends on other packages in vitess.

**Comment by mjibson** [comment]
:(
