### ISSUE TITLE
ui,ts: graphs are totally busted

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#26679]
Something has gone terribly wrong. I suspect it's related to the timeseries work @mrtracy has been doing, but cc @couchand @vilterp just in case.

<img width="994" alt="screenshot 2018-06-13 04 34 18" src="https://user-images.githubusercontent.com/882976/41339559-2449f800-6ec3-11e8-9655-3541d7210789.png">

This is on a very recent master, 5dafdcb, which notably includes ee9522cef.

**Comment by couchand** [comment]
@benesch can you provide more detail about how you got into this state?  was it an old cluster that you'd upgraded to the latest master or was it a fresh one?

**Comment by benesch** [comment]
It was a cluster booted from a 2TB 2.0 store dump—the one we use for the backup 2TB test—with a binary that was basically latest master. So in essence a large 2.0 cluster that had just been upgraded to the latest master.

**Comment by mrtracy** [comment]
Are you sure we can't rule out warping the space time continuum?

But in all seriousness, looks like the graph data is not coming back in sorted order, and I did touch the sorting logic in the C++ code.  I'll see if that's also the cause of the consistency violation.

One question: is the time series data restored as part of the backup?

**Comment by vilterp** [comment]
A little out of my depth here w/r/t TS storage, but could it be as simple as the TS data was written in the old format and read in the new format? Some kind of upgrade process was missed?

**Comment by mrtracy** [comment]
This, along with the consistency checker violation, are definitely the kind of shenanigans I would expect to see if the cluster version was upgraded but there was still one node running a previous version without the new merge code.
