### ISSUE TITLE
sql: include type info in the index key encoding

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#2667]
The `Encode{Null,Varint,Float,Bytes,String}` encoding routines are used to encode our primitive types into byte slices for use as index keys. Currently, decoding of these index keys requires knowing the type that was encoded. This is due to overlap in the encoded values. An encoded integer will start with a byte in the range `\x01-\x11`. An encoded float will start with a byte in the range `\x06-\x23`. And an encoded bytes/string will start with a byte in the range `0x00-0xff` (though the prefix `\x00\x00` is prohibited). 

While this currently works fine, it makes it so that index keys are not self-describing. We currently handle this by making sure we always examine an index key in the context of an index. I think we should make our index keys self-describing. Doing this is a fairly small change to the encoding routines. Essentially, we have to shift the encoding of the first byte for integers to the range `\x02-\x12`, for float values to the range `\x13-\x30` and change the bytes/string encoding routine to prefix the encoded data with `\x31`. Lastly, we could then change the NULL and not-NULL markers to be `\x00` and `\x01` respectively. Summarized, the first byte would indicate:

* `\x00` - NULL
* `\x01` - not-NULL 
* `\x02-\x12` - integer
* `\x13-\x30` - float
* `\x31` - bytes/string

I'm proposing we do this by beta because it would be a backward-incompatible change to the data formats. The only downside of note is that the encoding of bytes/string would increase by a single byte. Seems worth the cost to make all SQL keys self-describing. My only concrete plan for using this self-describing feature is for pretty-printing keys, but it also seems like a nice bit of robustness for the future.

See also #2477. While this proposal would not allow for changing the type of a column that is used in an index, these encodings are also used for columns that are "stored" with indexes. Making the encodings self-describing would allow the type of a stored but not-indexed column to be changed if we also added support for casting the stored value to the correct type when read.

**Comment by tamird** [comment]
:+1:

**Comment by spencerkimball** [comment]
Nice. Go for it.

**Comment by vivekmenezes** [comment]
Great. I'm \x03, I'm an integer.
