### ISSUE TITLE
sql: hibernate test failure due to use of unsupported implicit cast

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#26710]
Found in the Hibernate test suite:

```sql
create table phone_call (
   id int8 not null,
    duration int4 not null,
    call_timestamp timestamp,
    phone_id int8,
    primary key (id)
)

select
    sqrt(call0_.duration) as col_0_0_ 
from
    phone_call call0_
```

This fails with `ERROR: unknown signature: sqrt(int)`
But in postgres, while their documentation doesn't show it, there's seems to be an implicit conversion:
```
# select sqrt(3::int);
       sqrt
------------------
 1.73205080756888
(1 row)

# select pg_typeof(sqrt(3::int));
    pg_typeof
------------------
 double precision
(1 row)
```

It might be worthwhile to audit all of these mathamatical functions to see which ones do allow for this type of implicit type conversion.
https://www.postgresql.org/docs/9.6/static/functions-math.html#FUNCTIONS-MATH-FUNC-TABLE

Jira issue: CRDB-4989

**Comment by jordanlewis** [comment]
Out of curiosity, could you check pg_proc in Postgres to see whether there's really a sqrt built-in with an int argument or if Postgres simply throws another implicit cast onto the input despite you forcing it to be an int? Should be something like `SELECT * FROM pg_proc WHERE proname = 'sqrt'` combined with looking at the argument type column which is named something like `proargtypes`.

**Comment by vy-ton** [comment]
@rafiss Is this still a valid issue?

**Comment by rafiss** [comment]
Yeah, it still does affect the Hibernate test -- In the hibernate test it is marked as skipped for this reason https://github.com/hibernate/hibernate-orm/blob/20273b81ee623d74d4c3d8efed2e7f2ab2f79c4e/documentation/src/test/java/org/hibernate/userguide/hql/HQLTest.java#L1300
