### ISSUE TITLE
cli: extend `cockroach init` (or 1st `start` without `--join`) with SQL initialization

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#26722]
Often requested on Gitter: when initializing a new cluster via container orchestration, it is useful to populate the initial state of the cluster using SQL (e.g. to set up users, zones, initial databases, etc).

The `start` and `init` commands should be extended to support `-f` (read from a file) and `-e` (execute specific statements) like `cockroach sql`.

**Comment by knz** [comment]
cc @piyush-singh

**Comment by frankgreco** [comment]
This feature would be great! My use case is spinning up a lightweight instance of Cockroach locally via Docker so that developers can run short lived tests against it. When the container starts up, bootstrapping the db via this init script would help a lot.

**Comment by gigatexal** [comment]
It would simplify K8s deployments too I think. Having to write jobs for everything is a bit annoying, but running CRDB in a helm chart with a flag to a file or commands just piped to it would be easier.

**Comment by knz** [comment]
Folk we need more details about the use case.

We see two unrelated things:

1) for single-node clusters we assume that the container is running `cockroach start`. My understanding is that the feature is useful because the top-level command in the container is `cockroach start` and you would like this to also run a sql command. Is that right? 

Is there anything that you need to do that wouldn't be supported by a shell script like this:

```sh
#!/bin/sh
cockroach start --background --pid-file=pid
cockroach sql ...
wait $(cat pid)
```

Then the second possible use case:

2) a multi-node cluster. In that case the two separate commands `cockroach start --join` and `cockroach init` are already mandatory anyway. We assume that the containers run `start --join` and `init` is ran by some external tool/orchestrator. Is that right? In that understanding, what prevents you from having the external tool run `init` and then `sql` in that order?

Or, alternatively, a script like this:

```sh
#!/bin/sh
cockroach init ...
cocroach sql ...
```

**Comment by rafiss** [comment]
This seems to relate to (and maybe supersede) this other issue I made: https://github.com/cockroachdb/cockroach/issues/48647

That one describes the convention used by Postgres (and I believe other DBs) to run init scripts that are in ` /docker-entrypoint-initdb.d`. @knz I'll let you decide if the issue I made is a duplicate.

**Comment by knz** [comment]
@rafiss well truth be told, the request to have auto-SQL initialization did come from users who wanted to create containers. If running commands from a `.d` directory is the "best practice", then the best practice will be sufficient and we don't need to make `init` more clever.

The problem I see with the `.d` directory however, is, I don't know how the logic will know when to run these commands. The first time the `cockroach` process starts, the cluster is not initialized yet, so SQL commands will fail. I will copy this comment onto your other issue.

**Comment by knz** [comment]
Closing in favor of #48647

See especially comments at https://github.com/cockroachdb/cockroach/issues/48647#issuecomment-696078276
