### ISSUE TITLE
sql: support the binary operator: <int> / <float>

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#26732]
The following hibernate tests failed: 

- org.hibernate.jpa.test.criteria.basic.PredicateTest testQuotientConversion

In postgres:
```sql
# select 1::int/1.3::float;
     ?column?
-------------------
 0.769230769230769
(1 row)
```

In Cockroach:
```
> select 1::int/1.3::float;
pq: unsupported binary operator: <int> / <float>
```

**Comment by knz** [comment]
Ok we'll just ignore this for now. This is not realistic of client apps and a features we're actively committed to not supporting unless absolutely necessary.
