### ISSUE TITLE
sql: implement string_agg()

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#26737]
Every hibernate test tries to fetch the connection metadata and uses string_agg() as part of it.

While it is not critical to pass the tests, there is no reason why we shouldn't just add the function and there's a todo to so in the code here: https://github.com/cockroachdb/cockroach/blob/e35c4c8848152335adf88849fdbe2c2a9dbe5d5e/pkg/sql/sem/builtins/aggregate_builtins.go#L137

```
 WARN JdbcEnvironmentInitiator:121 - HHH000341: Could not obtain connection metadata : ERROR: unknown function: string_agg()
```

**Comment by knz** [comment]
This is blocked on #10495.

**Comment by olle** [comment]
Hi, I ran into this issue with Spring Boot 2.x, managing schemas using Liquibase - even without Hibernate or JPA enabled.

Sorry for the lack of info. Just though it could be of interest. Thanks!

**Comment by BramGruneir** [comment]
This is done!
