### ISSUE TITLE
sql: panic while inserting into table with composite fks and CHECK in v2.0.2

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/cockroach#26748]
I can crash cockroach by doing an insert into a table with composite fks. Note that I have a check constraint that is failing as a workaround for #23580. Would have expected an error and not a crash.

`cockroach start --insecure --host localhost --background`
`cockroach sql --insecure --host localhost -e "create database movr"`
`cockroach sql --insecure --host localhost -d movr <panic-tables.sql`
`cockroach sql --insecure --host localhost -d movr -e "INSERT INTO rides (id, city, rider_id, vehicle_id, start_address, end_address, start_time, end_time, revenue) VALUES ('4aa80578-b74c-4600-83ec-2999fe75eb39', 'new york', '58a71ca7-2394-4900-8a91-cab58b0c2a4a', '6a9139ae-397e-449c-81ad-1db1c467d325', '2672 Isaiah Gateway\nNew Kristin, PA 26306-7316', '49869 John Parkway\nHeidiborough, IN 16304-9638', '2018-06-15', '2018-06-16', 23);"`

```
*
* ERROR: [n1,client=127.0.0.1:55669,user=root] a SQL panic has occurred while executing "INSERT INTO rides(id, city, rider_id, vehicle_id, start_address, end_address, start_time, end_time, revenue) VALUES ('4aa80578-b74c-4600-83ec-2999fe75eb39', 'new york', '58a71ca7-2394-4900-8a91-cab58b0c2a4a', '6a9139ae-397e-449c-81ad-1db1c467d325', e'2672 Isaiah Gateway\\\\nNew Kristin, PA 26306-7316', e'49869 John Parkway\\\\nHeidiborough, IN 16304-9638', '2018-06-15', '2018-06-16', 23)": fk ids (map[1:3]) missing column id 2
*
*
* ERROR: [n1,client=127.0.0.1:55669,user=root] a panic has occurred!
*
panic while executing 1 statements: INSERT INTO _(_, _, _, _, _, _, _, _, _) VALUES (_, _, _, _, _, _, _, _, _); caused by fk ids (map[1:3]) missing column id 2
```
[panic-tables.sql.txt](https://github.com/cockroachdb/cockroach/files/2106342/panic-tables.sql.txt)

**Comment by jordanlewis** [comment]
@BramGruneir, could you take a look? Or maybe @emsal1863 since you might be touching FKs soon?
