### ISSUE TITLE
opt: investigate stats issues

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#26750]
Filing this issue so we don't lose track of the issues with statistics found in PR #26714.

https://reviewable.io/reviews/cockroachdb/cockroach/26714#-LEzipFGCi33rb0P9YTI:-LEzipFH-o9ht2PogOI5:b-6xka2f

https://reviewable.io/reviews/cockroachdb/cockroach/26714#-LF-phsk69ZeU7Nvo9bc:-LF-phsk69ZeU7Nvo9bd:b-xoe1t7

**Comment by rytaft** [comment]
Thanks for filing! I'll look into it...
