### ISSUE TITLE
Please change product name

### ISSUE THREAD

**Issue by tetor** [cockroachdb/cockroach#2677]
Hello!

I feel CorckroachDB is awesome product and I want to know everyone this project. I'm promising it and hope to do contribution.

However, the bad to say, name of this “cockroach" is disgusting :hankey:  Its googleability is so bad. Why don't you change name to more confortable  name?

**Comment by vivekmenezes** [comment]
Tetor,

We're afraid we cannot change the name. We'd love for you to contribute.
Thanks

**Comment by tetor** [comment]
OK, I got it. Thanks :smile:

**Comment by cup** [comment]
https://github.com/cockroachdb/cockroach/issues/13634

https://github.com/cockroachdb/cockroach/issues/2677
https://github.com/cockroachdb/cockroach/issues/3151
