### ISSUE TITLE
roachtest: posting issue fails when assignee is outside organization

### ISSUE THREAD

**Issue by solongordon** [cockroachdb/cockroach#26788]
Some roachtests were failing on the release-2.0 but failed to post an issue to Github, apparently because the attempted assignee was outside our organization:

https://teamcity.cockroachdb.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=714687&_focus=5878

**Comment by solongordon** [comment]
@petermattis I'm happy to take a look at this if you don't have bandwidth, but figured it's probably a quick fix for you.

**Comment by petermattis** [comment]
I can take a look, but not this week. If you want to poke at this, the relevant code is in `cmd/internal/issues.go`.
