### ISSUE TITLE
sql: improve performance of ON DELETE CASCADE

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#26795]
Picture a parent table with, say, 10 child tables that all specify ON DELETE CASCADE.
Now delete 100 rows from the parent (perhaps read from an index). Due to the CASCADE clauses, for each row scanned from the parent index, we will sequentially issue 10 FK checks/deletions on the child tables for a total of at least 10*100 back-to-back KV round-trips (assuming we fire off blind deletions everywhere, which is not true).

Maybe we're deleting in bulk from the parent after the children have been cleared, not sure, but the basic problem remains -- we're not optimizing the deletions from the children.

The best we can do seems to gather up checks as we scan rows to be deleted from the primary, and send batches of such deletions to the children. In doing so, these batches can benefit from `DistSender` parallelism, which should cut overall latency. In the best case for this example, the query would run as follows:

1. start new batch
1. for i=1..100 read row i and add row i's pk deletion to the batch, and also deletions for all children
1. send off the batch (which now contains 10*100 + 100 deletions)

It's harder to carry this optimization across statements because later statements must observe the prior deletions already, though if we had an in-memory buffer of the data read (up to a certain size) and written, we could do something here. This seems wildly out of scope.

**Comment by RaduBerinde** [comment]
The FK cascades have been reimplemented in 20.2. We now issue a delete "post-query" for each child table and join it with the parent rows that were modified.
