### ISSUE TITLE
sql: investigate the hibernate test org.hibernate.jpa.test.emops.RemoveTest testUpdatedAndRemove

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#26799]
Not sure of the root cause here, but here are the details.

This works when tested directly using two cockroach sql command lines, but the test fails.

```sql
create table Music (
  id int4 not null,
  name varchar(255),
  version int4,
  primary key (id)                                                                                                                                                                 );

insert into Music (name, version, id)                                                values ('classical', 0, 1);
```

transaction 1, open but don't commit it:
```sql
begin;
select id, name, version from music where id = 1;
```

transaction 2, while transaction 1 is still open:
```sql
update music set name = 'rap' where id = 1;
```

back to transaction 1:
```sql
delete from music where id = 1;
commit;
```

It correctly fails with
```
pq: restart transaction: HandledRetryableTxnError: TransactionRetryError: retry txn (RETRY_WRITE_TOO_OLD): "sql txn" id=0a60e9ee key=/Table/28924/1/1 rw=true pri=0.02814406 iso=SERIALIZABLE stat=PENDING epo=0 ts=1529342542.880056817,1 orig=1529342541.139508328,0 max=1529342541.139508328,0 wto=true rop=false seq=5
```

However, this completes incorrectly in:
org.hibernate.jpa.test.emops.RemoveTest testUpdatedAndRemove

From what I can tell, it looks like each statement was issued as a single transaction.

**Comment by knz** [comment]
Can you include a SQL trace of what is received from hibernate in CockroachDB, and in PostgreSQL for comparison? Thanks

**Comment by knz** [comment]
@BramGruneir This issue is improperly qualified. It does neither state what is the deviation (difference between expected behavior and actual behavior) nor what action items should be carried out.

Unless you provide either (preferably both), we can't do anything with this.

**Comment by knz** [comment]
Then the title of the issue is wrong. I am renaming.

**Comment by rafiss** [comment]
This test has been passing in Hibernate
