### ISSUE TITLE
cli: much longer than expected latency using CLI to bulk insert.

### ISSUE THREAD

**Issue by tim-o** [cockroachdb/cockroach#26790]
Using this file: https://ufile.io/w5c6m

And this table:
```
CREATE TABLE product_order_table (
    country STRING,
    region STRING,
    order_id INTEGER,
    id UUID DEFAULT gen_random_uuid(),
    order_date DATE,
	ship_date DATE,
	sales_channel STRING,
	order_priority STRING,
	item_type STRING,
	units_sold INTEGER,
	unit_price FLOAT4,
	unit_cost FLOAT4,
	total_revenue FLOAT8,
	total_cost FLOAT8,
	total_profit FLOAT8,
	PRIMARY KEY(country, order_id, id)
)
```

this command:

```
cockroach-v2.0.2 sql --insecure --database=test < part0000.sql
INSERT 10001

Time: 553.153472ms
```
Takes 10+ minutes to return you to the command line, while this one:

```
tim-o$ psql "postgresql://root@localhost:26257/test" < part0000.sql
INSERT 0 10001 
```

Is nearly instant.

**Comment by knz** [comment]
This is not a CLI issue. Recategorizing.

**Comment by knz** [comment]
oh actually maybe it is.

**Comment by knz** [comment]
@tim-o please upload the test file again! The link has expired.

Also please do not use payware/adware services to host files. Github has a file serving service directly in the issue editor, and the next best thing would be a gist.

**Comment by tim-o** [comment]
Thankfully I had it stored locally:
[part0000.sql.txt](https://github.com/cockroachdb/cockroach/files/2266638/part0000.sql.txt)

I passed on the link provided to me by the customer, but we can rehost them in the future.

**Comment by jordanlewis** [comment]
Closing due to age.
