### ISSUE TITLE
sql: investigate Hibernate's testTemporalType

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#26804]
from org.hibernate.test.annotations.EntityTest testTemporalType

Somehow, a timestamp changes values.  I'm not sure if this is happening during the write or the read.  More investigation is requried.

```sql
create table Flight (                                                                                                                            
  id int8 not null,                                                                                                                                                          
  alternativeDepartureDate timestamp,                                                                                                                                       
  primary key (id)                                                                                                                                                      
);
insert into Flight (id, alternativeDepartureDate) values (1, '1970-01-02 04:59:27.443');
select * from Flight;
```

In the hibernate test output, the value changes:
```
org.junit.ComparisonFailure: expected:<January 2, 1970 at [4]:59:27 AM EST> but was:<January 2, 1970 at [9]:59:27 AM EST>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.hibernate.test.annotations.EntityTest.lambda$testTemporalType$1(EntityTest.java:403)
...
```

**Comment by BramGruneir** [comment]
6 more failures:

- org.hibernate.test.cid.CompositeIdWithGeneratorTest
  - testCompositeIdSimple
  - testDetachedId
  - testDetachedProperty
  - testEvict
  - testLoad
  - testMerge

**Comment by knz** [comment]
This is a time zone problem. Check what is the default time zone expected.

**Comment by knz** [comment]
What is the full syntax of the CREATE TABLE statement? It's truncated above. We need this to fully investigate.

**Comment by BramGruneir** [comment]
That seems like the most plausible explanation.

**Comment by knz** [comment]
@BramGruneir This issue is improperly qualified. It does neither state what is the deviation (difference between expected behavior and actual behavior) nor what action items should be carried out.

Unless you provide either (preferably both), we can't do anything with this.

**Comment by BramGruneir** [comment]
The expected behaviour and actual are spelled out in the issue.

`org.junit.ComparisonFailure: expected:<January 2, 1970 at [4]:59:27 AM EST> but was:<January 2, 1970 at [9]:59:27 AM EST>`

And the create table statement was there in full.  Just poorly formatted.  It has been fixed.

And I still agree, this is most likely a time zone issue.

**Comment by knz** [comment]
The problem might be in Hibernate's testTemporalType instead of CockroachDB. We simply don't know. Renamed the issue to reflect the investigation to be done, instead of the working theory.

**Comment by jordanlewis** [comment]
All of the tests in this issue pass now, as of 2.1! 🎉
