### ISSUE TITLE
ui: sometimes SQL fails to highlight

### ISSUE THREAD

**Issue by couchand** [cockroachdb/cockroach#26826]
The library we're using to highlight SQL (`highlight.js`) sometimes fails to recognize SQL, so the highlighting doesn't work.

Extracted from https://github.com/cockroachdb/cockroach/pull/26711#issuecomment-397113415

> ![image](https://user-images.githubusercontent.com/7341/41382644-146207fc-6f3b-11e8-817c-0c943266d783.png)
> 
> Small bug: certain fingerprints don't syntax highlight when I go to them. Can't tell what the pattern is.

**Comment by vilterp** [comment]
So it's being invoked, but fails to recognize `SELECT`, `FROM`, `WHERE`, and `AND` as SQL keywords? Jeez…

**Comment by couchand** [comment]
I think the language detection is getting screwed up somehow, maybe by the underscores?

**Comment by vilterp** [comment]
Consider doing this on the server size while formatting via https://github.com/mjibson/sqlfmt/issues/38
