### ISSUE TITLE
Transitive dependency issue with the log package.

### ISSUE THREAD

**Issue by AmandaCameron** [cockroachdb/cockroach#2683]
The transitive dependency on github.com/cockroachdb/cockroach/util/log breaks use of the SQL driver in grpc-based application stacks, this is a pretty bad experience. I realise that this is an alpha, however because of thie transitive dependency, you'll get a runtime panic of "logtostderr is already defined" from the flag package.

I can try and whip up a simple example, but any code that happens to also depend on the original glog code will also fail to work.

**Comment by tamird** [comment]
No need for an example, I think this will be relatively easy to fix.

**Comment by bdarnell** [comment]
We've been tracking this in #942 but it hasn't been a priority yet. This is a good reminder that we should do at least the logging portion of #942 before beta. @tamird, have you run into this in your work with GRPC?

**Comment by tamird** [comment]
I haven't, but that's because I submitted a [PR](https://github.com/grpc/grpc-go/pull/218) a while ago that makes glog an optional dependency of grpc. @AmandaCameron is probably intentionally using glog, which is legitimate, and broken by us.

**Comment by AmandaCameron** [comment]
Ah, that explains it. I had a stale  dependency on grpc as thus project is
a bit older, but yeah, removing the dep is desired. As well as if possible
the dep on c-snappy, as it breaks the cross compiling usecase we've got at
darkdna.

I swear I saw a pure go impl of snappy either in the stdlib it in a
golang.org/x/ repo, perhaps that'd be worth pursuing?

**Comment by petermattis** [comment]
There is a pure go implementation of snappy, but a) it is significantly
slower than c-snappy and b) c-rocksdb uses the C++ interface to snappy via
c-snappy. How does c-snappy break cross compilation?

**Comment by tamird** [comment]
@petermattis I think @AmandaCameron just means that sql/driver shouldn't depend on c-snappy, which is a relatively easy change to make.

**Comment by petermattis** [comment]
Ah, yes, so the c-rocksdb dependency isn't important. Yet my first point
about the pure-go snappy being slower than c-snappy still is. We can
certainly get rid of that dep, but blindly replacing it with the pure-go
version without considering the perf impact is a mistake.

I'd still like to understand why c-snappy breaks cross compilation. Is it
that the cross compilation environment doesn't support cgo? I'm pretty sure
that can work if you have the correct CC/etc environment variables set.

**Comment by AmandaCameron** [comment]
@petermattis Last I looked, the setup of CGo-based cross-compiling of Go stuff was largely undocumented, but I'll admit I last looked in the 1.3 days or so.

**Comment by petermattis** [comment]
A quick google search returned: https://gist.github.com/steeve/6905542.
Those instructions seem pretty recent, though I haven't actually tried
them. Which platform (source and dest) are you trying to do cross
compilation for?

**Comment by AmandaCameron** [comment]
OS X -> Linux is my use-case, however I'll research that gist some when I have some free time later tonight.
