### ISSUE TITLE
sql: the output schema of SHOW and EXPLAIN is irregular

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#26840]
# Making the interface of SHOW and EXPLAIN more consistent

Summary: this PR mainly updates the column labels produced for the
output of several SHOW and EXPLAIN statements. The data produced is
generally left unchanged, with two exceptions detailed below.

## Motivation

SHOW and EXPLAIN statements in CockroachDB provide convenient views
over database metadata and query execution.

They constitute a public-facing API and are prominently featured in
documentation and tutorials.

It is thus important that their interface is polished and
consistent. This ensures users can more effectively construct a
reliable mental model of how to use CockroachDB: more regularity and
consistency make the software easier to use. Also, consistency and
more generally design polish give a good impression to users and
increases the chance of reputation-based popularity gains.

In addition, since mid-2017 CockroachDB enables queries to apply SQL
to refine and modify the output of SHOW or EXPLAIN statements. This is
used extensively in tests and during troubleshooting, and incidentally
when teaching CockroachDB. It is thus important that the "in-SQL
interface" of these statements makes the construction of surrounding
queries convenient too.

## Background

As of june 2018 CockroachDb currently supports 39 SHOW and EXPLAIN
statements. They have been added incrementally and organically as need
arised. The following table reports the various syntax forms sorted by
creation order, with their column interface prior to this PR.

| Syntax form                | date added | old parameter list                                                                                                                                                              |
|----------------------------|------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| SHOW COLUMNS               | 2015-06    | "Field", "Type", "Null", "Default"                                                                                                                                              |
| SHOW DATABASES             | 2015-06    | "Database"                                                                                                                                                                      |
| SHOW INDEX                 | 2015-06    | "Table", "Name", "Unique", "Seq", "Column", "Direction", "Storing", "Implicit"                                                                                                  |
| SHOW TABLES                | 2015-06    | "Table"                                                                                                                                                                         |
| EXPLAIN (PLAN)             | 2015-08    | "Tree", "Field", "Description"                                                                                                                                                  |
| SHOW GRANTS                | 2015-08    | "Database", "Schema", "User", "Privileges"                                                                                                                                      |
| SHOW SESSION (var)         | 2015-08    | (var)                                                                                                                                                                           |
| SHOW TRACE                 | 2016-02    | timestamp, age, message, tag, loc, operation, span                                                                                                                              |
| SHOW CREATE TABLE          | 2016-04    | "Table", "ShowCreate"                                                                                                                                                           |
| SHOW CONSTRAINTS           | 2016-07    | "Table", "Name", "Type", "Column(s)", "Details"                                                                                                                                 |
| SHOW CREATE VIEW           | 2016-10    | "View", "ShowCreate"                                                                                                                                                            |
| SHOW SESSION ALL           | 2016-10    | variable, value (*)                                                                                                                                                             |
| SHOW TRANSACTION STATUS    | 2016-11    | transaction_status                                                                                                                                                              |
| EXPLAIN (DISTSQL)          | 2017-02    | "Automatic", "JSON", "URL"                                                                                                                                                      |
| SHOW RANGES                | 2017-03    | "Start Key", "End Key", "Range ID", "Replicas", "Lease Holder"                                                                                                                  |
| SHOW ALL CLUSTER SETTINGS  | 2017-04    | name, current_value, type, description (*)                                                                                                                                      |
| SHOW CLUSTER SETTING (var) | 2017-04    | (var)                                                                                                                                                                           |
| SHOW FINGERPRINTS          | 2017-05    | "index", fingerprint                                                                                                                                                            |
| SHOW BACKUP (default)      | 2017-06    | database, "table", start_time, end_time, size_bytes                                                                                                                             |
| SELECT FROM [...]          | 2017-06    |                                                                                                                                                                                 |
| SHOW JOBS                  | 2017-06    | id, type, description, username, status, created, started, finished, modified, fraction_completed, error, coordinator_id                                                        |
| SHOW QUERIES               | 2017-06    | query_id, node_id, username, start, query, client_address, application_name, distributed, phase (*)                                                                             |
| SHOW SESSIONS              | 2017-06    | node_id, session_id, username, client_address, application_name, active_queries, last_active_query, session_start, oldest_query_start, kv_txn, alloc_bytes, max_alloc_bytes (*) |
| SHOW ZONE CONFIGURATION    | 2017-10    | id, cli_specifier, config_yaml, config_proto                                                                                                                                    |
| SHOW COMPACT TRACE         | 2017-11    | age, message, tag, operation                                                                                                                                                    |
| SHOW USERS                 | 2017-11    | username                                                                                                                                                                        |
| SHOW HISTOGRAM             | 2017-12    | upper_bound, num_range, num_eq                                                                                                                                                  |
| SHOW ROLES                 | 2017-12    | rolename                                                                                                                                                                        |
| SHOW STATISTICS            | 2017-12    | name, columns, created_at, row_count, distinct_count, null_count, histogram_id                                                                                                  |
| SHOW SYNTAX                | 2017-12    | field, text                                                                                                                                                                     |
| SHOW CREATE SEQUENCE       | 2018-01    | "Sequence", "ShowCreate"                                                                                                                                                        |
| SHOW GRANTS ON ROLE        | 2018-01    | role, member, "isAdmin"                                                                                                                                                         |
| SHOW REPLICA TRACE         | 2018-01    | timestamp, node_id, store_id, replica_id                                                                                                                                        |
| SHOW SCHEMAS               | 2018-02    | "Schema"                                                                                                                                                                        |
| SHOW STATISTICS USING JSON | 2018-04    | statistics                                                                                                                                                                      |
| EXPLAIN ANALYZE            | 2018-05    | "Automatic", "JSON", "URL"                                                                                                                                                      |
| EXPLAIN (OPT)              | 2018-06    | text                                                                                                                                                                            |
| SHOW BACKUP (files)        | 2018-06    | path, start_pretty, end_pretty, start_key, end_key, size_bytes, rows                                                                                                            |
| SHOW BACKUP (ranges)       | 2018-06    | start_pretty, end_pretty, start_key, end_key                                                                                                                                    |

The following notes apply:

- column labels are double quoted when they are not valid identifiers,
  either because of casing or because they are restricted SQL keywords.
- `(var)` for SHOW CLUSTER SETTING and SHOW SESSION indicates the column
  of the result is named after the variable being shown.
- `(*)` in the column list for SHOW QUERIES, SHOW SESSIONS, SHOW
  SESSION ALL and SHOW ALL CLUSTER SETTINGS is inherited directly from
  a `crdb_internal` table. This is discussed below.

## Problem statement

The table above reveals the 4 general problems addressed in this PR:

- the result column labels are inconsistently cased. The inconsistency
  itself is hurtful to UX and may give a poor impression of
  CockroachDB's overall design.

- the same conceptual data is named using different words in different
  statements. For example SHOW GRANTS uses "User" but SHOW USERS uses
  "username". SHOW TABLES uses "Table" but "SHOW STATISTICS" uses
  "name". This makes it harder for users to construct a reusable,
  simple conceptual model of how to inspect CockroachDB.

- the use of capitals or restricted keywords in column labels mandate
  double quotes when using the column in a surrounding SQL query with
  `SELECT FROM [...]`. It also creates doubt and confusion as a user
  may remember the label of a column but not which casing to use to
  refer to it.

- a few statement are simple pass-through views to an underlying
  `crdb_internal` table without fixing the list of result columns. If
  an engineer were to modify the `crdb_internal` table, they would
  thus modify the public-facing, documented SQL API of CockroachDB
  without realizing.

## Methodology

The following principles have guided the work in this PR.

- the casing of column labels must be consistent.

- the same concept in different statements should be named using the
  same word.

  For example, `name` -> `variable` in SHOW ALL CLUSTER SETTINGS for
  consistency with SHOW SESSION ALL.

- the labels must be usable by a surrounding query without mandating
  quotes.

  For example, `"Start Key"` -> `start_key`

- underscores to separate words for consistency with
  `information_schema`.

  For example, `"Start Key"` -> `start_key` instead of `startkey`

- avoid abbreviations unless most uses of the word in spoken English
  use the abbreviation already.

  For example, `id` for "identifier" is OK, but `loc` for "location"
  is not.

- for columns akin to "primary keys" (that identify the object being
  described by the remaining columns), words whose meaning is highly
  overloaded must be disambiguated in the label.

  For example, `id` -> `zone_id` or `job_id`; `name` -> `column_name`.

- for database objects that can be referred to by two or more types of
  handles (e.g. by-ID or by-name), the column label must disambiguate
  which type of handle is being reported. This makes it possible to
  later report the other handles in additional columns.

  For example, `table` -> `table_name`, so that `table_id` can be
  added later.

- labels that reproduce data already present in an
  `information_schema` table should use the same labels as the
  `information_schema` table provided it matches the principles above
  already.

A later PR will codify these principles by additions in the `docs/`
directory and possibly a linter.

## Detailed changes

- SHOW COLUMNS:
  - `Field` -> `column_name` (casing, disambiguation, consistency with `information_schema`)
  - `Type` -> `data_type` (casing, disambiguation, consistency with `information_schema`)
  - `Null` -> `is_nullable` (casing, consistency with `information_schema`)
  - `Default` -> `column_default` (casing, keyword avoidance, consistency with `information_schema`)

- SHOW DATABASES:
  - `Database` -> `database_name` (casing, disambiguation)

- SHOW INDEX:
  - `Table` -> `table_name` (casing, keyword avoidance, disambiguation)
  - `Index` -> `index_name` (casing, keyword avoidance, disambiguation)
  - `Unique` -> `non_unique` (casing, keyword avoidance, consistency with `information_schema`)
    Note: this inverts the boolean meaning.
  - `Seq` -> `seq_in_index` (casing, consistency with `information_schema`)
  - `Column` -> `column_name` (casing, disambiguation, consistency with `information_schema`)
  - `Direction` -> `direction` (casing)
  - `Storing` -> `storing` (casing)
  - `Implicit` -> `implicit` (casing)

- `SHOW TABLES`
  - `Table` -> `table_name` (casing, keyword avoidance, disambiguation)

- `EXPLAIN (PLAN)`
  - `Tree` -> `tree` (casing)
  - `Field` -> `field` (casing)
  - `Description` -> `description` (casing)

- `SHOW GRANTS`
  - `Database` -> `database_name` (casing, consistency, disambiguation)
  - `Schema` -> `schema_name` (casing, consistency)
  - `User` -> `grantee` (casing, consistency with `information_schema`, also because it includes roles not just users)
  - `Privileges` -> `privilege_type` (casing, consistency with `information_schema`)

- `SHOW TRACE`
  - `loc` -> `location` (avoidance of abbreviation)

- `SHOW CREATE TABLE`, `SHOW CREATE VIEW`, `SHOW CREATE SEQUENCE`
  - make the TABLE/VIEW/SEQUENCE keyword optional: they all run the same code and
    the users should not have to remember whether their object is a table
    or a view to run SHOW CREATE.
  - `Table`/`View`/`Sequence` -> `object_name` (casing, consistency, keyword avoidance, disambiguation)
  - `ShowCreate` -> `create_statement` (casing, consistency)

- `SHOW CONSTRAINTS`
  - `Table` -> `table_name` (casing, consistency, keyword avoidance, disambiguation)
  - `Name` -> `constraint_name` (casing, disambiguation)
  - `Type` -> `constraint_type` (casing, disambiguation)
  - `Column(s)`/`Details` -> `details` (casing, simplification)

- `SHOW SESSION ALL`
  - fixed the set of output columns instead of passing `crdb_internal` through.

- `EXPLAIN (DISTSQL)`, `EXPLAIN ANALYZE`
  - `Automatic` -> `automatic` (casing)
  - `URL` -> `url` (casing)
  - `JSON` -> `json` (casing)

- `SHOW RANGES`
  - `Start Key` -> `start_key` (casing, word separation)
  - `End Key` -> `end_key`  (casing, word separation)
  - `Range ID` -> `range_id`  (casing, word separation)
  - `Replicas` -> `replicas`  (casing)
  - `Lease Holder` -> `lease_holder`  (casing, word separation)

- `SHOW ALL CLUSTER SETTINGS`
  - `name` -> `variable` (consistency with SHOW SESSION ALL)
  - `type` -> `setting_type` (disambiguation)

- `SHOW FINGERPRINTS`
  - `index` -> `index_name` (keyword avoidance, disambiguation)

- `SHOW BACKUP`
  - `database` -> `database_name` (disambiguation)
  - `table` -> `table_name` (keyword avoidance, disambiguation)

- `SHOW JOBS`
  - `id` -> `job_id` (disambiguation)
  - `type` -> `job_type` (disambiguation)
  - `username` -> `user_name` (space between words)

- `SHOW QUERIES`
  - `username` -> `user_name` (space between words)
  - fixed the set of output columns instead of passing `crdb_internal` through.

- `SHOW SESSIONS`
  - `username` -> `user_name` (space between words)
  - fixed the set of output columns instead of passing `crdb_internal` through.

- `SHOW ZONE CONFIGURATION`
  - `id` -> `zone_id` (disambiguation)
  - `config_proto` -> `config_protobuf` (abbreviation avoidance)

- `SHOW HISTOGRAM`
  - `num_range` -> `range_rows` (abbreviation avoidance)
  - `num_eq` -> `equal_rows` (abbreviation avoidance)

- `SHOW ROLES`
  - `rolename` -> `role_name`

- `SHOW STATISTICS`
  - `name` -> `table_name` (disambiguation)
  - `columns` -> `column_names` (disambiguation)
  - `created_at` -> `created` (consistency with SHOW JOBS)

- `SHOW GRANTS ON ROLE`
  - `role` -> `role_name` (consistency with SHOW ROLES)
  - `isAdmin` -> `is_admin` (casing, word separator)

- `SHOW SCHEMAS`
  - `Schema` -> `schema_name` (casing, consistency, disambiguation)

- `SHOW USERS`
  - `username` -> `user_name` (space between words)

- `EXPLAIN ANALYZE`
  - `Automatic` column removed (not relevant for this syntax form)
  - `JSON` -> `json` (casing)
  - `URL` -> `url` (casing)

## Summary of statement interfaces after the changes

| Syntax form                | new parameter list                                                                                                                                                          |
|----------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| EXPLAIN (DISTSQL)          | **automatic, json, url**                                                                                                                                                    |
| EXPLAIN (OPT)              | text                                                                                                                                                                        |
| EXPLAIN (PLAN)             | **tree, field, description**                                                                                                                                                |
| EXPLAIN ANALYZE            | **json, url**                                                                                                                                                               |
| SHOW ALL CLUSTER SETTINGS  | **variable**, current_value, **value_type**, description                                                                                                                    |
| SHOW BACKUP (default)      | **database_name**, **table_name**, start_time, end_time, size_bytes                                                                                                         |
| SHOW BACKUP (files)        | path, start_pretty, end_pretty, start_key, end_key, size_bytes, rows                                                                                                        |
| SHOW BACKUP (ranges)       | start_pretty, end_pretty, start_key, end_key                                                                                                                                |
| SHOW CLUSTER SETTING (var) | (var)                                                                                                                                                                       |
| SHOW COLUMNS               | **column_name, data_type, is_nullable, column_default**                                                                                                              |
| SHOW COMPACT TRACE         | age, message, tag, operation                                                                                                                                                |
| SHOW CONSTRAINTS           | **table_name, constraint_name, constraint_type, details, validated**                                                                                                        |
| SHOW CREATE SEQUENCE       | **object_name, create_statement**                                                                                                                                           |
| SHOW CREATE TABLE          | **object_name, create_statement**                                                                                                                                           |
| SHOW CREATE VIEW           | **object_name, create_statement**                                                                                                                                           |
| SHOW DATABASES             | **dataase_name**                                                                                                                                                            |
| SHOW FINGERPRINTS          | **index_name**, fingerprint                                                                                                                                                 |
| SHOW GRANTS                | **database_name, schema_name, grantee, privilege_type**                                                                                                                     |
| SHOW GRANTS ON ROLE        | **role_name**, member, **is_admin**                                                                                                                                          |
| SHOW HISTOGRAM             | upper_bound, **range_rows**, **equal_rows**                                                                                                                                 |
| SHOW INDEX                 | **table_name, index_name, non_unique, seq_in_index, column_name, direction, storing, implicit**                                                                             |
| SHOW JOBS                  | **job_id**, **job_type**, description, **user_name**, status, created, started, finished, modified, fraction_completed, error, coordinator_id                                    |
| SHOW QUERIES               | query_id, node_id, **user_name**, start, query, client_address, application_name, distributed, phase                                                                             |
| SHOW RANGES                | **start_key, end_key, range_id, replicas, lease_holder**                                                                                                                    |
| SHOW REPLICA TRACE         | timestamp, node_id, store_id, replica_id                                                                                                                                    |
| SHOW ROLES                 | **role_name**                                                                                                                                                                    |
| SHOW SCHEMAS               | **schema_name**                                                                                                                                                             |
| SHOW SESSION (var)         | (var)                                                                                                                                                                       |
| SHOW SESSION ALL           | variable, value                                                                                                                                                             |
| SHOW SESSIONS              | node_id, session_id, **user_name**, client_address, application_name, active_queries, last_active_query, session_start, oldest_query_start, kv_txn, alloc_bytes, max_alloc_bytes |
| SHOW STATISTICS            | **table_name**, **column_names**, **created**, row_count, distinct_count, null_count, histogram_id                                                                          |
| SHOW STATISTICS USING JSON | statistics                                                                                                                                                                  |
| SHOW SYNTAX                | field, text                                                                                                                                                                 |
| SHOW TABLES                | **table_name**                                                                                                                                                              |
| SHOW TRACE                 | timestamp, age, message, tag, **location**, operation, span                                                                                                                 |
| SHOW TRANSACTION STATUS    | transaction_status                                                                                                                                                          |
| SHOW USERS                 | **user_name**                                                                                                                                                                    |
| SHOW ZONE CONFIGURATION    | **zone_id**, cli_specifier, config_yaml, **config_protobuf**                                                                                                                |

## Backward compatibility

This technically constitutes a backward-incompatible change (change in
public API which may theoretically confuse existing client code). The
reason why the change is nonetheless worth adopting is fourfold:

- automated tools, especially those designed for compatibility with a
  pg server, are more likely to use `pg_catalog` and
  `information_schema` tables instead.

- the EXPLAIN and SHOW statements are still advertised and
  designed/implemented as "porcelain" [1] meant for use by humans.

- There has not been any commitment to their interface for
  backward-compatibility (other than a general guideline that
  evolutions do not remove columns already known to be useful). In
  fact, over time, several SHOW statements have evolved their
  interface and this has not yet been picked up during reviews and QA
  as a source of backward compatibility concern.

- The general UX improvement and its potential benefits for ease of
  adoption outweighs backward compatibility concerns.

[1]: https://stackoverflow.com/questions/6976473/what-does-the-term-porcelain-mean-in-git#6978402

**Comment by knz** [comment]
@bdarnell @jseldess  could you have a look at this proposal and share how you feel about it?

**Comment by benesch** [comment]
❤️ 👍 💯 

One more compatibility argument to consider. Many of these `SHOW` statements are inspired by MySQL. The amount of compatibility varies greatly by statement: `SHOW INDEX` is vastly different, for example, while `SHOW CREATE TABLE` and `SHOW COLUMNS` are nearly identical. I think it's probably safe to say that we have no interest in being compatible with MySQL's SHOW statements, but I think we should explicitly commit to that choice.

**Comment by RaduBerinde** [comment]
Very nice! The names with spaces and capitals are an abomination.

Changes to EXPLAIN and SHOW STATISTICS LGTM to me.

**Comment by jseldess** [comment]
This looks awesome to me, @knz! The principles under "Methodology" seem like stylistic conventions that we should document/store separately for future reference, in case we change or add `SHOW` statements. 

It feels strange that `username` and `rolename` are exceptions to the rule. It's true that `username` is a word in English, but it's also not wrong to use `user_name` and `role_name` for the sake of consistency. Note also `CREATE TABLE`'s syntax:

```
CREATE USER [IF NOT EXISTS] <name> [ [WITH] PASSWORD <passwd> ]
```

That said, I don't feel very strongly here.

**Comment by knz** [comment]
Thanks for the feedback Jesse. I was on the fence about that one. I think I also like `user_name` somewhat better, but I too do not feel strongly either way. Somehow however I believe that since neither of us feel strongly we could perhaps leave it as-is, because the change actually costs some effort and I am not keen on spending this effort if not deemed definitely desirable.

**Comment by jseldess** [comment]
@knz, I understand, though if it's low effort, I'd say it's probably worth it. The inconsistencies may bother us in the future.

**Comment by knz** [comment]
Well then that's ok, but then you did feel sufficiently strongly there :)

**Comment by jseldess** [comment]
Yes, to be clearer, I should've said I prefer the change but would accept leaving it as-is.

**Comment by bdarnell** [comment]
Generally LGTM. I agree with Jesse that `rolename` would be better as `role_name` (I could go either way with `user_?name`). 

Will the references to `database_name` (in statements other than `SHOW DATABASES`) cause problems when we move towards user-createable schemas?

Changing the meaning of the `unique` column in `SHOW INDEXES` might break our sqlalchemy dialect. I think I'd rather leave that as-is instead of changing to non_unique to match information_schema (although I otherwise agree with choosing names consistent with information_schema where we can)

I prefer `num_foo` to `foo_cardinality`. `num` may be an abbreviation but it's much more widely recognized than `cardinality` (I'd also be OK with `count`).

**Comment by RaduBerinde** [comment]
I didn't notice the change to the histogram; `cardinality` is also ambiguous in the context of stats as it can mean distinct count. FWIW SQL Server uses `range_rows` and `equal_rows` for these.

**Comment by knz** [comment]
Updated to use `role_name`, `user_name`, `range_rows` and `equal_rows`.
