### ISSUE TITLE
mon: track "actual" {max,current} memory used

### ISSUE THREAD

**Issue by asubiotto** [cockroachdb/cockroach#26858]
`mon.BytesMonitor` keeps track of the high watermark of allocations through its `mu.maxAllocated` field. However, this is incremented in `reserveBytes` and thus is actually a reflection of the number of bytes **reserved** for allocations rather than the bytes actually **used** (which is equivalent to the sum of all `used` fields of the accounts associated with a given monitor). It would be useful to track how much memory was actually used mostly for reporting purposes.

**Comment by soniabhishek** [comment]
@asubiotto I went through the bytes_usage.go file to get a better understanding of the requirement, I understood the issue and wanted to ask how can we keep track of current usages can you give me some more insight?
