### ISSUE TITLE
sql/stats: stats should use historical queries

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#26859]
Suggested by @nvanbenschoten: the reads performed for table statistics should be historical (AS OF SYSTEM TIME) to avoid interactions with ongoing transactions.

**Comment by RaduBerinde** [comment]
@rytaft fixed this.

**Comment by nvanbenschoten** [comment]
How far in the past are these queries run?

**Comment by rytaft** [comment]
Automatic stats are run at AOST -30s

**Comment by nvanbenschoten** [comment]
Perfect, thanks.
