### ISSUE TITLE
server: improve semantics of decommission of down nodes

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#26880]
When you try to decommission a node that is down, today one has to use `decommission --wait=live` (which does not verify whether the down node is part of any ranges) and manually verify that the cluster has upreplicated all ranges elsewhere. This is far from ideal, in particular since there is no automated way to reliably check this.

We should add a (throttled) periodic full scan of the meta indexes and return only when the node does not have any replicas assigned any more.

**Comment by tschottdorf** [comment]
This would be done in https://github.com/cockroachdb/cockroach/blob/40c2b39798712d6bf24a7340c53e72acc32de2de/pkg/cli/node.go#L316

1. the `--wait=live` flag would be treated like the `--wait=all` flag (and a deprecation warning printed)
2. instead of checking the `resp.ReplicaCount` field, perform a consistent scan of the meta2 ranges and build up authoritative replica counts for each node we care about. This scan would have to paginate, I'd say 10k descriptors at a time (followed by a 1s backoff) is reasonable.
3. return only when that drops to zero.

As a result, decommission will only return when no more replicas are assigned to the decommissioning nodes, whether they are down or not.

**Comment by tschottdorf** [comment]
cc @neeral

**Comment by neeral** [comment]
@tschottdorf I'm trying to understand things a little more:
 * Currently, DecommissionStatus gets the number of replicas per node from metrics (key = replicas). Are these metrics stale?
 * Proposal: to perform a scan of meta2 ranges would replace the calculation above. We could continue to use the `resp.ReplicaCount` field. This lives in `pkg/server/admin.go:DecommissionStatus()`.

**Comment by tschottdorf** [comment]
> Currently, DecommissionStatus gets the number of replicas per node from metrics (key = replicas). Are these metrics stale?

Yes, they're always a little stale since they were computed at some past point in time. Additionally, they count replicas that have de facto been removed (i.e. the Raft group is merrily going forward with a new set of members excluding that replica) but the replica is still around. But most importantly, if the node is down, you will never receive a new replica count. This is because it is computed and broadcast locally by each node.

 > Proposal: to perform a scan of meta2 ranges would replace the calculation above. We could continue to use the resp.ReplicaCount field. This lives in pkg/server/admin.go:DecommissionStatus().

I think that sounds right. Just add a comment on that field explaining how the count is computed (there isn't a comment on it at all now, which is bad).

**Comment by neeral** [comment]
Is this a candidate for backporting to 2.0 ?

**Comment by tschottdorf** [comment]
This has been done.
