### ISSUE TITLE
opt: cluster setting sql.defaults.optimizer is wonky

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#26900]
I've found a few issues while trying out the new cluster setting `sql.defaults.optimizer`.

1) Don't ever set it to 'always' as basic things like creating a database or changing a cluster setting are just broken.  So it will brick your cluster.  This is really dangerous and should be fixed before the next alpha release.

2) It doesn't always seem to take.  From what I can tell, the node (or cluster?) needs to be restarted and the sql session possibly as well.  After doing this a few times, I can get it up and running, or turn it off.

Sadly, `show cluster settings sql.defaults.optimizer;` returns to the value it's set at and does not reflect if it's actually in use.

**Comment by justinj** [comment]
I'm going to remove the "always" option, but you can disable it for your session with `set experimental_opt = 'off'`. The reason you're not seeing it "take" is that it only sets the default for the session variable, so you need to start a new session for it to have any effect.

**Comment by justinj** [comment]
Going to close this as I think the fundamental issue here was a misunderstanding, and `always` is gone now.
