### ISSUE TITLE
sql: add support for UNION/INTERSECT/EXCEPT

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#2691]
For example: `SELECT 1 UNION SELECT 2`. The two queries must be "union compatible". That is, having the same number of output columns and the output columns need to have the same data types.

**Comment by paperstreet** [comment]
I messed up linking my commit message to this issue, so here's a manual annotation. https://github.com/cockroachdb/cockroach/commit/3594cbc94a750f6d9510d4a7be2f84660f595b51 does most of this.
