### ISSUE TITLE
sql: add support for SELECT ... FROM (VALUES) AS foo;

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#2692]
For example, `SELECT * FROM (VALUES (1, 2), (3, 4)) AS foo (a, b)`.

**Comment by RaduBerinde** [comment]
Peter helped me understand how the grammar works. It looks like in this statement VALUES is not a special "table", but a special query/select statement:
```
VALUES (1, 2), (3, 4);
 column1 | column2 
---------+---------
       1 |       2
       3 |       4
(2 rows)
```

So the query `SELECT * FROM (VALUES (1, 2), (3, 4)) AS foo (a, b)` is basically a select inside select, effectively analogous to something like:
```
SELECT * FROM t WHERE k > 0;
 k | v | w 
---+---+---
 1 | 1 | 1
 2 |   |  
(2 rows)

SELECT * FROM (SELECT * FROM t WHERE k > 0) AS foo(a, b);
 a | b | w 
---+---+---
 1 | 1 | 1
 2 |   |  
(2 rows)
```

This can of course go deeper, with each level able to rename the columns:
```
SELECT * FROM (SELECT * FROM (VALUES (1, 2), (3, 4)) AS foo) as bar;
 column1 | column2 
---------+---------
       1 |       2
       3 |       4
(2 rows)

SELECT * FROM (SELECT * FROM (VALUES (1, 2), (3, 4)) AS foo(a, b)) as bar;
 a | b 
---+---
 1 | 2
 3 | 4
(2 rows)

SELECT * FROM (SELECT * FROM (VALUES (1, 2), (3, 4)) AS foo(a, b)) as bar(c, d);
 c | d 
---+---
 1 | 2
 3 | 4
(2 rows)
```

It would be most natural to implement VALUES as a special select statement (which would be a simple exercise). However, we do not currently support recursive select statements. If we want to support these for the beta anyway (at least in some restricted form), we should first work on that.

**Comment by petermattis** [comment]
I agree it would be most natural to implement `VALUES` as a special select statement and, as you've noticed, it is already supported (e.g. `VALUES (1, 2)` works as a top-level statement). We also support limited forms of subqueries `SELECT (VALUES (1))`. (See `sql/subquery.go` and `sql/testdata/subquery`). What we don't support is select statements in the `FROM` clause of queries.
