### ISSUE TITLE
storage: Raft log is still read on elections

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#26946]
coreos/etcd#9073 did not actually do what was intended: it still reads the entire raft log even though it now only needs the last entry. The last index is known so the call to `entries` needs to be adjusted so we only load the data we need. 

This change should be backported to release-2.0 because we intended for this problem to be fixed in 2.0, and it's showing up in #26830.

**Comment by bdarnell** [comment]
Upstream PR: coreos/etcd#9887

**Comment by tschottdorf** [comment]
@bdarnell this is done, right?
