### ISSUE TITLE
importccl: dropped table desc does not set DropTime

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#26956]
When an import fails, a dropped table descriptor is written so that the schema changer erases any data in the table. This dropped table descriptor does not set DropTime, and as a result the schema change takes the slow, non-ClearRange path:

https://github.com/cockroachdb/cockroach/blob/98d2a125821a1641fec3e880d0973d8cd5605a0f/pkg/ccl/importccl/import_stmt.go#L787-L804

There's a TODO in there that says the DropTime field should be replaced with the table's modification time, so maybe we can resolve that TODO while fixing this bug.

**Comment by mjibson** [comment]
Closed by #26959
