### ISSUE TITLE
roachpb: generation is fragile

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#26965]
The code generation in roachpb is very fragile. You can easily break it by removing a request from api.proto and then running `make generate PKG=./pkg/roachpb`. The code generation requires _compiling_ roachpb, but it does so using an out-of-date version of batch_generated.go which references the now-removed request. You have to manually remove batch_generated.go, then rerun `make generate`.

Similarly, resolving a rebase conflict in roachpb requires running `git checkout --ours pkg/roachpb/{api.pb,batch_generated,method_string}.go` and then re-running codegen.

I'm sure this is fixable, but I haven't dug in to exactly how.

Epic CRDB-10447

Jira issue: CRDB-4976

**Comment by jordanlewis** [comment]
This is solved by bazel
