### ISSUE TITLE
build: enable assertions in c deps

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#26973]
With the exception of RocksDB, which gets built with assertions turned on during race builds, we always specify `CMAKE_BUILD_TYPE=Release`, which passes `-DNDEBUG` to the C compiler, which disables assertions. In fact, libroach doesn't even _build_ right now with assertions turned on. We really need to sort this out and periodically run builds with assertions turned on.

Epic CRDB-10447

Jira issue: CRDB-4975

**Comment by knz** [comment]
still relevant

**Comment by rickystewart** [comment]
Not planning on working on this.
