### ISSUE TITLE
sql: show syntax with AOST interval broken?

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#26976]
Ok maybe this one is a real problem?:

```
> show syntax 'select * from t as of system time interval ''-1ns''';
+-------+-----------------------------------------------------+
| field |                       message                       |
+-------+-----------------------------------------------------+
| sql   | SELECT * FROM t AS OF SYSTEM TIME '-1ns':::INTERVAL |
+-------+-----------------------------------------------------+

> SELECT * FROM t AS OF SYSTEM TIME '-1ns':::INTERVAL;
invalid syntax: statement ignored: syntax error at or near ":"
```

The FmtParsable flag that is used here by `show synatx` moves the interval type annotation to after its argument and adds on a `:::<type>`. However the AOST parser doesn't accept that syntax and so it breaks. However I have no idea if there are any bugs here.

1) Is this even a bug?
2) Should FmtParsable not move those type annotations like it is? Can we do something like teach tree.AnnotateTypeExpr about this?
3) Should AOST be taught about type annotations? I think this is fairly difficult because they aren't constants. AOST is clearly being a bit special here. But even still we should probably have a rule that show syntax's output works exactly the same as its input.

**Comment by knz** [comment]
yes there is something we can improve here. will look into it
