### ISSUE TITLE
sql: "index" as column name differs from postgres

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#26993]
CockroachDB does not allow "index" to be used unquoted as a column name when creating a table:

```
root@127.0.0.1:65274/demo> create table t (index int);
invalid syntax: statement ignored: syntax error at or near ")"
DETAIL: source SQL:
create table t (index int);
                         ^
HINT: try \h CREATE TABLE
```

PostgreSQL does:

```
postgres=# create table t3 (index int);
CREATE TABLE
```

`INDEX` is not a reserved word, but this statement breaks because we allow non-unique indexes to be created in the `CREATE TABLE` statement while postgres does not. I'm not sure if there's anything we can reasonably do about this in the grammar. If not, we should at least document this as a difference from postgres. 

Originally reported in cockroachdb/cockroachdb-python#57

**Comment by knz** [comment]
Indeed we've painted ourselves in a corner here by allowing index definitions inside the CREATE syntax. 
What is concerning me however is the linked issue with SQL Alchemy: why is that thing not double quoting column names? It should! There are other places where users would get surprises, e.g. if they decide to call their column "user".

**Comment by bdarnell** [comment]
> why is that thing not double quoting column names? It should! There are other places where users would get surprises, e.g. if they decide to call their column "user".

It has a [list of keywords that will get quoted](https://github.com/zzzeek/sqlalchemy/blob/master/lib/sqlalchemy/dialects/postgresql/base.py#L941-L957), and we can add to this list in our dialect. Of course this is silly; there is no reason for machine-generated SQL to ever use the non-quoted form, but there it is.

**Comment by knz** [comment]
(it's especially jarring since pg specifically provides a built-in function `pg_get_keywords()` that produces this list for clients to peruse)

**Comment by knz** [comment]
Oh in the case of "lateral" it is reserved in pg but it was added recently. I think sqlalchemy simply didn't know about it.

**Comment by jordanlewis** [comment]
Going to close this as wontfix - it's too late for us to remove the ability to do stuff like `CREATE TABLE a (a int, index(a))`.

@rmloveland could you see if this is already documented, and add an issue to do so if it isn't? Thank you!
