### ISSUE TITLE
sql: clarify behaviour of `RecordStatement` in metrics

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#27015]
From https://github.com/cockroachdb/cockroach/pull/26981#issuecomment-400646923:

>I also realize as I am writing this that the call to RecordStatement() below may not make sense if there are automatic retries -- what does it record exactly for every attempt after the first?

**Comment by knz** [comment]
I checked this. There was indeed an error in the implementation and I fixed it: #38028
