### ISSUE TITLE
engine: track abort span in MVCCStats, use for GC decision

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#27055]
In #25233 we have seen situations in which the split trigger can become arbitrarily large. This blow-up occurs when the data that needs to be copied into the RHS of the split grows large, which can happen if the abort span becomes large.

Once in this situation, splits become impossible until the abort span reduces in size, which it typically does after a GC operation. Unfortunately, a GC operation can't be triggered by the size of the abort span, since its size is not tracked in the MVCCStats and its computation thus requires a full scan.

It's not too much work to track the size of the abort span explicitly in MVCCStats. On top of allowing us to trigger GC when necessary, it's an interesting number to track.

I recently landed a mitigation (https://github.com/cockroachdb/cockroach/pull/26934) for this that avoids having to copy *all* of the abort span on splits, making this somewhat lower priority.

**Comment by andreimatei** [comment]
This just bit a user, in the form of an abort span that got so large that GCing it times out (#40815). Raised the priority.
