### ISSUE TITLE
sql: use placeholders instead of underscore in fingerprints

### ISSUE THREAD

**Issue by couchand** [cockroachdb/cockroach#27052]
When we produce a statement fingerprint, we replace all the values with underscores, rendering a string of ~invalid~ *nonsense* SQL.  This is unfortunate, because it means that doing some interesting things with the fingerprint are much more difficult than they should be.  For instance:

- We can't ~reparse the fingerprint to produce an AST and~ extract *expected type* metadata at a later date without extra work,
- SQL syntax highlighters don't always work, and
- ~The fingerprint can't be copy-pasted by the user into a SQL environment without more work.~

The proposal is to replace the values with placeholders instead.  This would allow us to parse the query and produce an AST, it would make SQL highlighting _just work_, and the user could copy-paste the fingerprint to use elsewhere.

@cockroachdb/sql-wiring @cockroachdb/sql-ui

**Comment by mjibson** [comment]
If we implement this it would need a good solution for what to do with existing placeholders. We probably shouldn't change them, but instead should start numbering after all existing ones or something?

Another concern is that not all underscores can be used as placeholders. Consider `CREATE TABLE _ (_ INT)`. Neither of those underscores can be a placeholder instead. We probably shouldn't convert those to placeholders in that case, but I'm not sure of an easy way to determine that other than reparsing the statement each time a _ is replaced to see if it was valid.

**Comment by couchand** [comment]
Sorry, I'm not referring to the scrubbed query, but the fingerprinted one.  I believe your second concern only applies to the scrubbed query.

Regarding your first point, I'd take another approach, that we should just renumber them.  The same query issued with placeholders versus with literal values seem (to me) to be perfectly legitimate to aggregate together.

**Comment by knz** [comment]
1) regarding this:

> When we produce a statement fingerprint, we replace all the values with underscores, rendering a string of invalid SQL. 

I need a couple of examples that demonstrate this is true. I was careful to pick a strategy that keeps the SQL valid so it can be parsed back. And if it is indeed true, that needs to be treated as a bug and fixed.

2) re the idea to use placeholders

placeholders are not a good idea. What you want is representative substitutions with the same lexical nature (= the same token type). Again if you could come up with a couple examples I'd help you determine what needs to be done.

**Comment by couchand** [comment]
You raise a good point, the underscore isn't invalid SQL.  I see that at least our SQL parser parses the underscore just fine as an identifier.  Then it errors out with `column "_" does not exist`, which is not quite as nice as `no value provided for placeholder: $1` but reasonable enough.

I believe your second concern is the same as Matt's second, which is related to the fully-scrubbed query (with table and column names removed), whereas this proposal is about the query fingerprint, which only has constant values removed (it's the result of this: `tree.AsStringWithFlags(stmt.AST, tree.FmtHideConstants)`).

**Comment by knz** [comment]
Again, please provide examples so we can discuss what needs to be done.

**Comment by couchand** [comment]
Discussed with @knz.  We determined that this is going about the right thing in the wrong way.  Yes, we do want to smartly aggregate for the user classes of queries with similar execution regardless of surface-level syntax.  But, (1) this should be for more than just placeholder vs. literal differences, and (2) we shouldn't do it eagerly and thereby lose granularity to the data.
