### ISSUE TITLE
ui: graphs that plot multiple metrics need always-on legend

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#27059]
Unfortunately, screenshots of the admin ui graphs remain a useful debugging tool. These are worthless when you're looking at a graph that plots multiple metrics and does not have a legend shown. Note that it's fine if there are multiple nodes -- I accept that we can't display a possibly unbounded number of names. But for graphs such as those on the Replication dashboard, having to guess from the color coding is not great. For example, the below screenshot would be useless if I hadn't hovered on this particular metric's info toggle.

<img width="527" alt="image" src="https://user-images.githubusercontent.com/5076964/42049850-46395eba-7ad5-11e8-9a03-d16a616ed622.png">

@couchand for triage.

**Comment by couchand** [comment]
On the one hand, we could up the hardcoded limit on the number of series we allow a legend for.  On the other hand, why are there charts with so many series anyway?  Are these number really being meaningfully compared at this level?

In any case, this will almost certainly be obviated by the work we do for per-node vs. aggregate charting following #23379...
