### ISSUE TITLE
ui: Notify user about which timestamp format is used

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#27065]
As a client pointed out, when using multiple different tools during development having to refer to documentation to remember whether a timestamp has a time zone or is UTC can be frustrating. We should just annotate timestamps with this information so users don't have to check when switching from tool to tool.

**Comment by couchand** [comment]
All our timestamps are UTC, universally.  Tools that don't use UTC are pretty much wrong.  I'm not sure we should waste space every time we show a timestamp to indicate that we're not doing things wrong here, but I suppose a `Z` at the end isn't too onerous.
