### ISSUE TITLE
ui: Notify users when Optimizer is turned on by default

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#27067]
Request from the optimizer team: we should notify users in the UI when the optimizer cluster setting is first turned on by default. This alert should:

• Only show if the cluster setting for the optimizer is turned on
• Be dismiss-able. Once the user dismisses this notification, they should not see it again.
• Refer the user to documentation about the optimizer, including documentation on the cluster setting to disable it if necessary

**Comment by bdarnell** [comment]
The optimizer was turned on without this warning in 2.1, so this is moot and should be closed now, right?

**Comment by piyush-singh** [comment]
Agreed
