### ISSUE TITLE
sql: desugar IF(...) to CASE

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#27073]
This was discussed with @andy-kimball  while considering evaluation semantics: it would be useful to concentrate the various syntax forms that need conditional evaluation to as few as possible.

Postgres specifies CASE and COALESCE separately (both with conditional evaluation of their operands), then specifies that IFNULL desugars to COALESCE which we already do correctly.

CockroachDB then also provides IF which is akin to [SQL Server's IIF](https://docs.microsoft.com/en-us/sql/t-sql/functions/logical-functions-iif-transact-sql?view=sql-server-2017), and like SQL Server does, we should desugar it to CASE.

@andy-kimball a case could perhaps be made that COALESCE could also desugar to CASE, but I feel less strongly about that one. Please advise what you recommend.

**Comment by knz** [comment]
Note to implementor: the desugaring should happen during semantic analysis, not parsing, so as to preserve the name "if" in auto-generated column names.

**Comment by RaduBerinde** [comment]
CASE, IF, NULLIF are all built into the same `Case` operator. We still have a separate `Coalesce` operator because it makes it easier to write rules to eliminate it.
