### ISSUE TITLE
importccl: IMPORT MYSQL: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/cockroach#27077]
I get a panic when trying to import a single table from a mysqldump file (created from sample data here: https://github.com/datacharmer/test_db)

```
root@localhost:26257/employees> IMPORT TABLE employees FROM MYSQLDUMP ('nodelocal:///employeedump.sql')
                             -> ;
driver: bad connection
warning: connection lost!
opening new connection: all session settings will be lost
warning: error retrieving the transaction status: dial tcp [::1]:26257: connect: connection refused
```

This table exists in the database.

**Comment by dt** [comment]
We've patched many things since this was filed and I was unable to reproduce the panic.

I did hit a two things that are still unsupported.
`ON DELETE CASCADE` seems to cause a parse error on the FKs. Removing the actions unblocked it (filed as #28553)
`ENUM` type is unsupported (fix in #28550)
