### ISSUE TITLE
importccl: IMPORT MYSQL - could not read definition for table

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/cockroach#27078]
`IMPORT MYSQLDUMP ('nodelocal:///employeedump.sql');`

`pq: nodelocal:///employeedump.sql: could not read definition for table "dept_emp" (possible unsupoprted type?)`

Here is the relevant section from the mysql dump file

```
--
-- Table structure for table `dept_emp`
--

DROP TABLE IF EXISTS `dept_emp`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
 SET character_set_client = utf8mb4 ;
CREATE TABLE `dept_emp` (
  `emp_no` int(11) NOT NULL,
  `dept_no` char(4) NOT NULL,
  `from_date` date NOT NULL,
  `to_date` date NOT NULL,
  PRIMARY KEY (`emp_no`,`dept_no`),
  KEY `dept_no` (`dept_no`),
  CONSTRAINT `dept_emp_ibfk_1` FOREIGN KEY (`emp_no`) REFERENCES `employees` (`emp_no`) ON DELETE CASCADE,
  CONSTRAINT `dept_emp_ibfk_2` FOREIGN KEY (`dept_no`) REFERENCES `departments` (`dept_no`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `dept_emp`
--

LOCK TABLES `dept_emp` WRITE;
/*!40000 ALTER TABLE `dept_emp` DISABLE KEYS */;
INSERT INTO `dept_emp` VALUES
```

**Comment by nstewart** [comment]
It fails on this line `CONSTRAINT `dept_emp_ibfk_1` FOREIGN KEY (`emp_no`) REFERENCES `employees` (`emp_no`) ON DELETE CASCADE`

**Comment by dt** [comment]
yeah, it'll fail on any constraints right now. I'm working on adding constraint support to the upstream mysql parser we use (which is part of google's vitess) but I guess they don't use constraints

**Comment by nstewart** [comment]
In the meantime can we call that out as the reason so users don't have to bisect their schema to find it? 

I see we use this error message for specific type errors, which makes it easy to pinpoint the fix `pq: nodelocal:///employeedump-no-constraints.sql: unsupported mysql type "enum"`

**Comment by dt** [comment]
sadly, no, in the meantime, we don't know what caused it to fail -- the parser we're calling here in this case just returns nothing -- so the work to get a helpful error is almost the same as just fixing it.

**Comment by dt** [comment]
I fixed the parser to throw better errors (and implemented FKs) so I think this is fixed.
