### ISSUE TITLE
Anyone using cockroachdb in production? and what's the benchmark against mysql?

### ISSUE THREAD

**Issue by unisqu** [cockroachdb/cockroach#27088]
1. Anyone using cockroachdb in production? 

2. and what's the benchmark against mysql in general?

**Comment by knz** [comment]
@unisqu thanks for your interest in CockroachDB!

Yes there are plenty of folk using CockroachDB in production. However, note that Github issues are mostly read only by CockroachDB team members. It is unlikely that you will get an answer from other production users here. Perhaps try your luck with the forum and Gitter instead.

As to benchmarks against mysql, check our our blog which reports on benchmarking efforts. MySQL is a very different database so it is hard to compare correctly (or fairly).

**Comment by knz** [comment]
@unisqu I am going to close this issue because it does not corresponds to a request to changes in CockroachDB or its documentation, which is what github issues are for. If you want to start a discussion, please peruse our forum instead. Thank you again!
