### ISSUE TITLE
ui: Chart unreadable: RocksDB Compactions/Flushes

### ISSUE THREAD

**Issue by Flips01** [cockroachdb/cockroach#27094]
Hi,
The  RocksDB Compactions/Flushes-Chart has a terrible scaling if there are few compactions/flushes which makes them barely recognizable. E.g.:

![image](https://user-images.githubusercontent.com/1101291/42155686-59296512-7de9-11e8-8939-44a61111763f.png)

**Comment by lqez** [comment]
@knz @tbg, I made a pull request(#38574) for this issue, what should I do more for the next?
