### ISSUE TITLE
sql: Improve INTERVAL input format

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#2710]
INTERVAL input uses a golang format: '2h2m4s'. While this is a nice modern way of inputting intervals, we should also support the SQL standard format as described here.

http://www.postgresql.org/docs/9.1/static/datatype-datetime.html#DATATYPE-INTERVAL-INPUT-EXAMPLES

**Comment by theangryangel** [comment]
I've got some working code that takes Postgres and iso8601 (with designators only at the moment) input and converts them (possibly somewhat crudely in some instances) to time.Duration.

I'm happy to work on forming this into a patch as and when I have time over the next week, if you're happy to at least look at it? 

If yes, the only question I have is whether or not the intention is to setup a ``SET intervalstyle`` command like Postgres, or guess the format at runtime (should be do-able)?

**Comment by petermattis** [comment]
@theangryangel We're happy to take a look at a patch. It would be preferable to avoid a `SET intervalstyle` command if possible. Let's try for automatic detection of the format and see if and where that falls down.

**Comment by jseldess** [comment]
Docs updated with https://github.com/cockroachdb/docs/pull/462
