### ISSUE TITLE
sql: sqlalchemy is sensitive to the formatting of pg_catalog.pg_get_constraintdef

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#27123]
So I was trying to modify sqlalchemy to use pg_catalog stuff again now that we have extended support (instead of relying on cockroachdb-specific features).

"Interestingly," sqlalchemy uses regular expressions to extract the components of a FK definition.

As it so happens, CockroachDB produces the following:

```
+-------------+-----------------------------------+-----------+
|   conname   |              condef               | conschema |
+-------------+-----------------------------------+-----------+
| fk_x_ref_f1 | FOREIGN KEY (x) REFERENCES f1 (x) | public    |
+-------------+-----------------------------------+-----------+
```

while postgres for the same produces:

```
  conname  |              condef              | conschema
-----------+----------------------------------+-----------
 f2_x_fkey | FOREIGN KEY (x) REFERENCES f1(x) | kena
```

Notice how, unfortunately, crdb places a space character after the table name and before the open parenthesis. SQLAlchemy chokes on this and parses an invalid table name (containing a final space).

I am not sure how many more tools are sensitive to the output of `pg_get_constraintdef` but I surmise we need to be extra careful there.

**Comment by rafiss** [comment]
Closing this since this particular formatting issue is addressed now.
