### ISSUE TITLE
importccl: How to "export" table to a specific location?

### ISSUE THREAD

**Issue by minglinlu** [cockroachdb/cockroach#27124]
what if I want to export a table's data,  is there any examples?

**Comment by knz** [comment]
cc @tim-o @mjibson

**Comment by knz** [comment]
@minglinlu Thanks for your interest in CockroachDB! 

Can you clarify which mechanism you are attempting to use? Are you trying to use the EXPORT statement? or instead `cockroach dump`? or some other mechanism?

**Comment by minglinlu** [comment]
yes, EXPORT statement, export it to an csv file.

**Comment by knz** [comment]
@minglinlu we have documented EXPORT here: https://www.cockroachlabs.com/docs/v2.1/export.html

Does this clarify?
