### ISSUE TITLE
1PC transactions

### ISSUE THREAD

**Issue by spencerkimball** [cockroachdb/cockroach#2716]
If the distributed sender receives a batch with a begin transaction and end transaction, attempt as a single atomic write to Raft in the event that all keys reside within a single range.

**Comment by tschottdorf** [comment]
pieces missing here are only the interplay between chunked sender and DistSender (the former currently always cuts EndTransaction off).
Then: on Replica, enable auto-gc if an executed batch constitutes the all the writes of a transaction (we can tell this from the intents list), closing #2717.

**Comment by tschottdorf** [comment]
this issue has been fixed from the KV side and (at least for elementary inserts) in SQL. See #3364.
