### ISSUE TITLE
Re-enable auto-gc for one-shot transactions

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#2717]
We should re-enable auto-gc when possible.

From comment in ec16f292bf3:

disable txn auto gc
this could lead to spurious test failures:

* txn writes some intents, but not in a single
  round-trip
* concurrent reader runs into open intent, tries to push
* before it gets there, txn finishes with only local intents;
  txn record gets deleted
* push begins, does not find txn entry and fails
* potentially repeat forever or (if a push succeeds) until
  recreated txn entry times out.

I ran into this since it created an endless loop in
conjunction with buggy test code, but it's better to
disable this for now until we actually have the GC
story in place. My intuition is that we'll want to
limit this to single-roundtrip txns, whose intents
are never visible to anyone except the requests in
the batch (and even then we must be careful that
they are not collected as "skipped intents" in
some cases).

**Comment by tschottdorf** [comment]
suggest to re-enable this as described in #2716 when that issue closes.

**Comment by tschottdorf** [comment]
blocked on #2799, but then this should be ok.
