### ISSUE TITLE
rpc: RPC versions

### ISSUE THREAD

**Issue by spencerkimball** [cockroachdb/cockroach#2719]
Communicate and verify version numbers between hosts for the RPC subsystem framing protocol.

**Comment by spencerkimball** [comment]
@bdarnell is this something we need for beta?

**Comment by bdarnell** [comment]
Yes. It doesn't need to be fancy; we just need to send "version 1" in our request headers and reject any request that doesn't say "version 1". We don't expect to change this version often (most changes will be backwards-compatible changes to our existing protobufs) but if we do make a fundamental change we should have a way to make sure that old servers don't misinterpret messages from new ones.

(same for the on-disk version of this issue, which isn't assigned to me and I'm having a hard time finding it)

**Comment by spencerkimball** [comment]
@BramGruneir is this issue done?

**Comment by BramGruneir** [comment]
Sorry, somehow I didn't see this or I would have replied earlier.

No, and the plan right now is to not add the feature until its needed.  I was trying to rush to get it in before beta, but after some pushback, it was determined that until we require the versioning, we should leave it as it.
