### ISSUE TITLE
sql: postgres-compatible endpoint

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#2720]
See #2491 and #2489.

Implement the server-side of the postgres protocol allowing any postgres client to connect to a CockroachDB cluster. There is work to be done on type checking in order to handle prepared queries, work to be done to support TLS connections and likely other bits of unknown work.

- [x] logic tests
- [x] TLS
  - [x] basic support
  - [x] mutual auth
- [x] prepared statements

**Comment by tamird** [comment]
This is mostly done, except for ongoing work to add type inference to various expression types. Closing.
