### ISSUE TITLE
ui: implementation of transient stats for admin UI

### ISSUE THREAD

**Issue by spencerkimball** [cockroachdb/cockroach#2721]
Create new statistics for transient stats at:

- Gateways for client traffic
    - # of requests
    - # of bytes in
    - # of bytes out
    - # of failures
    - Latency of client requests
- Node level (both for Raft & KV traffic)
    - # of RPCs
    - # of bytes in
    - # of bytes out
    - # of failed RPCs
    - Latency of internode requests
- Store level
    - # of store requests
    - # of bytes to storage
    - # of bytes from storage
    - # of failed commands
    - Latency of store requests

**Comment by tschottdorf** [comment]
partial server-side work in #3504 should make it easy to access some of that information already. Others can be added easily. @maxlang, let's talk when you get back.

SQL is missing from the above list.

**Comment by maxlang** [comment]
Here's the new list we're discussing supporting

**Primary (empty)**
- Status - gr health, y unhealthy, r dead ( counts/status): 20 / 4 / 1
- Node name (# nodes)
- Stores (total stores)
- Ranges (total ranges)

**Storage**
- total count/bytes - 180 (54 KiB)
- Live count/bytes - (live count / live value bytes + key bytes) 
- intent count/bytes
- sys count/bytes - metadata, trans records, etc

**Gateway Traffic** - these are totals, or viewable by time range
- SQL CRUD stats
  - TRANSACTIONS (count)
  - SELECTS (count, bytes out)
  - UPDATES (count, bytes in)
  - INSERTS (count, bytes in)
  - DELETES (count)
  - CREATES (count)
  - DROPS (count)

**Internal traffic**
 - Total reqs count/bytes in /bytes out
 - Req Reads count/ bytes out
 - Req Writes count / bytes in

**Range Activity**
 - Leaders (count)
 - Splits
 - Merges
 - Rebalances
 - Availability (%)

**Comment by cuongdo** [comment]
Also need ranges / table endpoint

**Comment by cuongdo** [comment]
For the CRUD stats, does "total" mean the total since the node was started? For example, "total" SELECT count would be the total number of SELECTs issued to a node since it last restarted?

**Comment by spencerkimball** [comment]
@cuongdo should this be closed?

**Comment by cuongdo** [comment]
Not yet. I'm dividing this up into three pieces for manageability.

1. SQL (done)
2. Transactions (SQL & KV) -- in-progress
3. Internal traffic - to be done after grpc stuff settles down

**Comment by cuongdo** [comment]
SQL & KV are now done.

We're punting on on the internal traffic stats until after 1.0. I'll create a new issue for that.
