### ISSUE TITLE
ui: aggregrated graphs in admin UI

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#2722]
We should graph aggregated statistics, not just per-node/store ones.

**Comment by mrtracy** [comment]
@maxlang We already have the capability to query aggregated statistics, and I believe we are already displaying a few on our cluster page.  Is that sufficient to close this issue, or do you want to leave this open to track something else?

**Comment by maxlang** [comment]
Yeah this seems close-able.
