### ISSUE TITLE
ui: expanding a job changes the job table size

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#27231]
And it messes with the widths of the columns a bit too:

<img width="1491" alt="screen shot 2018-07-06 at 16 12 54" src="https://user-images.githubusercontent.com/1614265/42398356-924c1e10-8137-11e8-8564-486a897c162a.png">
<img width="1547" alt="screen shot 2018-07-06 at 16 12 48" src="https://user-images.githubusercontent.com/1614265/42398358-925cbc7a-8137-11e8-84cf-f862cd2f66ec.png">

**Comment by couchand** [comment]
Re the title: that's behaving as specified.  Re the column widths, there's not a lot we can do here without going all the way to fixing the widths, which seems likely to cause more trouble than it fixes.

cc @josueeee in case you have thoughts here
