### ISSUE TITLE
ui: aggregate error/warning table and corresponding admin UI

### ISSUE THREAD

**Issue by spencerkimball** [cockroachdb/cockroach#2724]
Have logger store error and warning level log messages to a system table.
Provide a corresponding admin UI for viewing aggregate system warning+ log messages.

**Comment by petermattis** [comment]
I'm not sure if our `log.{Warning,Error}` messages have had enough consideration to be displayed as-is in the admin UI. Now that we have the event-log facility, I think we should make a pass over the `log.{Warning,Error}` occurrences and consider upgrading some of them to events.

**Comment by petermattis** [comment]
Punting this until after beta.

**Comment by maxlang** [comment]
@mrtracy I'm going to assign to you as this seems related to #3725

**Comment by spencerkimball** [comment]
@mrtracy seems we can close this. I don't believe this is necessary as it hasn't proven to be a pressing ask since it was filed 1.5 years ago. Re-open if you disagree.
