### ISSUE TITLE
Usage with PostgREST

### ISSUE THREAD

**Issue by cmnstmntmn** [cockroachdb/cockroach#27261]
Hei! 

The first thing i want to say is that you're doing a really great work!

My case, like any other frontend developer out there, 
is to consume database as easy as possible, via api requests;

Few days ago i interacted with PostgREST, and i liked the way you cand have a REST api out of the box;

My question so far; 
Does PostgREST can be used with CockroackDB or 
are there any tools available to achieve same results?

thanks in advance.

**Comment by tim-o** [comment]
Hi @cmnstmntmn  - following up from github in case you missed the response there. We don’t have a supported rest API layer at the moment. PostgREST may work out of the box, or may make use of postgres statements or features that aren’t yet available. It may work - out of the box - whether it does or you run into issues, it’d be helpful for the community if you created a forum post with the steps you took.
