### ISSUE TITLE
sql: Intellij IDEA database fails due to missing "pg_catalog.pg_shdescription"”

### ISSUE THREAD

**Issue by zhenruyan** [cockroachdb/cockroach#27271]
log  

[42P01] org.postgresql.util.PSQLException: ERROR: relation "pg_catalog.pg_shdescription" does not exist.
ERROR: relation "pg_catalog.pg_shdescription" does not exist

**Comment by knz** [comment]
Hello @zhenruyan 
Thank you for reporting this issue and your interest in CockroachDB!
This is a duplicate of #26376. We have fixed this in the upcoming CockroachDB 2.1; we encourage you to try the alpha release and report your findings.

Thank you again!
