### ISSUE TITLE
sql: backport the sql syntax for all new features 

### ISSUE THREAD

**Issue by kannanlakshmi** [cockroachdb/cockroach#27288]
Feature request 

When a user tries to use a feature (e.g., changefeed) on an older version of cockroach that doesn't support the feature, they see an error like this 

Error: pq: syntax error at or near "changefeed"
DETAIL: source SQL:
CREATE CHANGEFEED for table movr.rides INTO 'kafka://localhost:9092'
       ^
This makes it look like its a SQL syntax error from the user side. Its also not helpful in diagnosing whats actually wrong with that statement. It would be nice if users saw a message that was more helpful such as "You are using an older version of cockroachdb" or "you need cockroachdb 2.1 or later for this feature"  etc. We should be able to do this for all new features that aren't backported. In theory, we could also do this for sql commands we don't support today but with an appropriately relevant message like "we do not implement this today, if you want it implemented, please file an issue." etc.

**Comment by jordanlewis** [comment]
I'm going to close this unless it's a hard ask from product - I don't think users really expect this level of helpfulness from the product. Customers who have issues like this will come to us and we'll be able to figure out what's going on very quickly without extra work from engineering.
