### ISSUE TITLE
timestamp used by leader lease requests

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#2728]
via @mrtracy on #2714:

> My question is: it appears that when a running command attempts to get the leader lease (through redirectOnOrAcquireLeaderLease()), in most cases we use the timestamp provided by the command arguments as the proposed start of the new lease - for example, in this case it used the timestamp on the batch arguments, which was zero.

> I'm just wondering if that is ever the correct behavior; for example, in a long running transactions, wouldn't it possible for the transaction's timestamp to be further in the past than the current expired lease, thus running into this very same problem?

> As an alternative, why wouldn't the nodes always just use the current node's clock timestamp when attempting to acquire the leader lease? It seems to me that the leader lease is not firmly related to the currently running command, and that all attempts to acquire the leader lease should just use the node's clock (for example, the way that getLeaseForGossip() does).

I see. Yes, that seems weird. When a node gets a leader lease, it also has the lease for all past timestamps, so that's what should be happening. Wanna file an issue? We should have a test for it along with the fix.

**Comment by tamird** [comment]
Arriving here via #3163 #3715.

> As an alternative, why wouldn't the nodes always just use the current node's clock timestamp when attempting to acquire the leader lease? It seems to me that the leader lease is not firmly related to the currently running command, and that all attempts to acquire the leader lease should just use the node's clock (for example, the way that getLeaseForGossip() does).

ISTM that leader leases acquisition attempts should use the command's timestamp, or the node's clock's timestamp, whichever is greater. Does that sound reasonable @tschottdorf @mrtracy?

**Comment by tschottdorf** [comment]
yep, SGTM

**Comment by tschottdorf** [comment]
There are some oddities with the local-clock `LeaderLease` semantics. The current lease holder is supposed to be able to answer all reads. But that could mean that more than one node thinks they're qualified to read (an old lease holder might think they're qualified on their skewed physical clock, while a new lease has already been issued and its owner is qualified based on their own clock). That's not immediately incorrect since historical reads don't change, and the timestamp cache's low water mark will be so high that those reads don't matter for it (on leadership change, it updates using `MaxOffset`), but good to keep in mind. If you can improve the documentation while you're there, that'd sure be helpful.

As a side note, we should also be able to serve historical reads at `ts < OldLeaseExpiration + MaxOffset` from all replicas, though that won't be important until MapReduce-type things start to happen.
