### ISSUE TITLE
ui: migrate off of protobuf.js

### ISSUE THREAD

**Issue by couchand** [cockroachdb/cockroach#27335]
The library we currently use to generate JS code from protobuf definitions is dcodeIO/protobuf.js.  Unfortunately, this library [has](https://github.com/dcodeIO/protobuf.js/issues/716) [given](https://github.com/cockroachdb/cockroach/issues/19808) [us](https://github.com/cockroachdb/cockroach/issues/25260) [numerous](https://github.com/cockroachdb/cockroach/blob/42cb23557c1d9d40169af6e5194c0e77a8c9e4b9/pkg/ui/src/redux/locations.spec.ts#L9) [problems](https://github.com/cockroachdb/cockroach/issues/27333) in the past.  Many of these issues arise from a variety of uncommon and problematic design decisions.  This, plus recent lack of activity in the repo, raise the question of the wisdom of using this libray long term.  It's starting to look like we should cut our losses and investigate alternatives.

One related issue is #20109, the suggestion to stop sending protos across the wire, but instead use JSON.  Even in that case, though, we want to use a library to generate our TypeScript typings for the responses, so this issue is still relevant.

Assigning to @benesch per our meat-space conversation.

**Comment by vilterp** [comment]
So what would we use to generate TS typings from protos?

**Comment by benesch** [comment]
https://github.com/improbable-eng/ts-protoc-gen looks promising.

**Comment by Fale** [comment]
Could [wasm](https://github.com/golang/go/issues/18892) be a solution for cockroach? moving the dashboard from JS to Go would make everything easier in my opinion

**Comment by benesch** [comment]
Hi @Fale, thanks for the suggestion. Unfortunately the Go/Wasm ecosystem is still quite immature, and we have quite a bit of TypeScript code that would need to be rewritten. I'm afraid it's unlikely to be a solution we'll pursue.

**Comment by tamird** [comment]
Related: https://github.com/google/protobuf/issues/1231

**Comment by couchand** [comment]
Related: https://www.cncf.io/blog/2018/10/24/grpc-web-is-going-ga/

**Comment by tamird** [comment]
Looks like it still requires a proxy.
