### ISSUE TITLE
sql: add column on 30k row table never completes

### ISSUE THREAD

**Issue by JakielaAdam** [cockroachdb/cockroach#27402]
Hello,

I am having problems canceling a phantom job on our cockroach cluster. About 24 hours ago I ran a command to add 2 columns to one of our tables (which has about 30,000 rows). The command had ran for about 15 minutes. Thinking that something had crashed, I did a control c and killed the command. Normally running database updates like this only takes a few seconds. 

However, now if I try and run the command again, it complains saying that the operation is already in progress. Assuming that something went wrong, I am trying to cancel the job. However, running ` cancel job 364321789334847496;` returns `pq: job 364321789334847496 is not controllable`. 

How can I cancel the job so I can run this command again? 

**Cockroach version**: `2.0.3`
**Original command**: `alter table rental add column failed_start bool default false, add column phone_info jsonb;`

Relevant output from the `show jobs` command:

```
| 364563581313318917 | SCHEMA CHANGE | ROLL BACK ALTER TABLE movatic_test.public.rental ADD COLUMN failed_start | root     | succeeded | 2018-07-11 16:26:15.742597+00:00 | 2018-07-11 16:26:15.793568+00:00 | 2018-07-11 16:26:16.304039+00:00 | 2018-07-11 16:26:16.30404+00:00  |                   1 |                                                                          |           NULL |
|                    |               | BOOL DEFAULT false, ADD COLUMN phone_info JSONB                          |          |           |                                  |                                  |                                  |                                  |                     |                                                                          |                |
| 364564266360864773 | SCHEMA CHANGE | ALTER TABLE movatic_test.public.rental ADD COLUMN failed_start BOOL      | root     | failed    | 2018-07-11 16:29:44.641964+00:00 | 2018-07-11 16:29:45.619165+00:00 | 2018-07-11 16:29:46.958328+00:00 | 2018-07-11 16:29:54.238132+00:00 | 0.10000000149011612 | index-id "7" does not exist                                              |           NULL |
|                    |               | DEFAULT false, ADD COLUMN phone_info JSONB                               |          |           |                                  |                                  |                                  |                                  |                     |                                                                          |                |
| 364564280913166341 | SCHEMA CHANGE | ROLL BACK ALTER TABLE movatic_test.public.rental ADD COLUMN failed_start | root     | running   | 2018-07-11 16:29:49.243538+00:00 | 2018-07-11 16:29:49.579631+00:00 | NULL                             | 2018-07-11 16:29:49.579633+00:00 |                   0 |                                                                          |           NULL |
|                    |               | BOOL DEFAULT false, ADD COLUMN phone_info JSONB                          |          |           |                                  |                                  |                                  |                                  |                     |                                                                          |                |
| 364564285028335621 | SCHEMA CHANGE | ROLL BACK ROLL BACK ALTER TABLE movatic_test.public.rental ADD COLUMN    | root     | running   | 2018-07-11 16:29:50.499381+00:00 | 2018-07-11 16:29:50.665338+00:00 | NULL                             | 2018-07-11 16:29:50.665339+00:00 |                   0 |                                                                          |           NULL |
|                    |               | failed_start BOOL DEFAULT false, ADD COLUMN phone_info JSONB             |          |           |                                  |                                  |                                  |                                  |                     |                                                                          |                |
| 364564294103171077 | SCHEMA CHANGE | ROLL BACK ROLL BACK ROLL BACK ALTER TABLE movatic_test.public.rental ADD | root     | running   | 2018-07-11 16:29:53.268806+00:00 | 2018-07-11 16:29:53.645918+00:00 | NULL                             | 2018-07-11 16:29:53.645918+00:00 |                   0 |                                                                          |           NULL |
|                    |               | COLUMN failed_start BOOL DEFAULT false, ADD COLUMN phone_info JSONB      |          |           |                                  |                                  |                                  |                                  |                     |                                                                          |                |
| 364564297419325445 | SCHEMA CHANGE | ROLL BACK ROLL BACK ROLL BACK ROLL BACK ALTER TABLE                      | root     | failed    | 2018-07-11 16:29:54.280813+00:00 | 2018-07-11 16:29:54.324837+00:00 | 2018-07-11 16:30:25.781015+00:00 | 2018-07-11 16:30:25.781015+00:00 | 0.10000000149011612 | index-id "3" does not exist                                              |           NULL |
|                    |               | movatic_test.public.rental ADD COLUMN failed_start BOOL DEFAULT false,   |          |           |                                  |                                  |                                  |                                  |                     |                                                                          |                |
|                    |               | ADD COLUMN phone_info JSONB                                              |          |           |                                  |        
```

**Comment by knz** [comment]
@vivekmenezes I am unsure whether we addressed this in 2.1 but we need to provide a way for 2.0 users to get unstuck in this situation.

**Comment by vivekmenezes** [comment]
this issue is similar to #27273 which is being worked on at the moment. Once #27273 is resolved we can see if these are the same issue.

@JakielaAdam  thanks for creating this issue. Can you provide us with the schema for the table. Are there FOREIGN KEYS involved in your schema?

**Comment by vivekmenezes** [comment]
cancelling schema changes is available in 2.1 through https://github.com/cockroachdb/cockroach/pull/25571

But what you're seeing here is not good.

**Comment by JakielaAdam** [comment]
`+-------------------------+-------------+-------+----------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|          Field          |    Type     | Null  |    Default     |                                                                                                                          Indices                                                                                                                          |
+-------------------------+-------------+-------+----------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| id                      | INT         | false | unique_rowid() | {"primary","rental_endRack_idx","rental_end_station_idx","rental_hardware_id_idx","rental_module_idx","rental_startRack_idx","rental_start_station_idx","rental_system_idx","rental_type_idx","rental_user_idx","rental_short_code_key","idx_ratesv2_id"} |
| user                    | INT         | true  | NULL           | {"rental_user_idx"}                                                                                                                                                                                                                                       |
| module                  | STRING(20)  | true  | NULL           | {"rental_module_idx"}                                                                                                                                                                                                                                     |
| message_count           | INTEGER     | true  | NULL           | {}                                                                                                                                                                                                                                                        |
| hardware_id             | INTEGER     | true  | NULL           | {"rental_hardware_id_idx"}                                                                                                                                                                                                                                |
| type                    | INTEGER     | true  | NULL           | {"rental_type_idx"}                                                                                                                                                                                                                                       |
| system                  | INTEGER     | true  | NULL           | {"rental_system_idx"}                                                                                                                                                                                                                                     |
| short_code              | STRING(5)   | true  | NULL           | {"rental_short_code_key"}                                                                                                                                                                                                                                 |
| short_created           | TIMESTAMP   | true  | NULL           | {}                                                                                                                                                                                                                                                        |
| start_station           | INTEGER     | true  | NULL           | {"rental_start_station_idx"}                                                                                                                                                                                                                              |
| start_time              | TIMESTAMP   | true  | NULL           | {}                                                                                                                                                                                                                                                        |
| end_station             | INTEGER     | true  | NULL           | {"rental_end_station_idx"}                                                                                                                                                                                                                                |
| duration                | INT         | true  | NULL           | {}                                                                                                                                                                                                                                                        |
| distance                | INTEGER     | true  | NULL           | {}                                                                                                                                                                                                                                                        |
| charge_amount           | FLOAT       | true  | NULL           | {}                                                                                                                                                                                                                                                        |
| refund                  | INTEGER     | true  | NULL           | {}                                                                                                                                                                                                                                                        |
| refundComment           | STRING(280) | true  | NULL           | {}                                                                                                                                                                                                                                                        |
| lock_count              | INTEGER     | true  | NULL           | {}                                                                                                                                                                                                                                                        |
| reservation_cancel_time | TIMESTAMP   | true  | NULL           | {}                                                                                                                                                                                                                                                        |
| reservation_start_time  | TIMESTAMP   | true  | NULL           | {}                                                                                                                                                                                                                                                        |
| charge_id               | STRING(30)  | true  | NULL           | {}                                                                                                                                                                                                                                                        |
| sentReceipt             | BOOL        | true  | NULL           | {}                                                                                                                                                                                                                                                        |
| notificationLastSent    | TIMESTAMP   | true  | NULL           | {}                                                                                                                                                                                                                                                        |
| possibleIncorrectEnd    | BOOL        | true  | NULL           | {}                                                                                                                                                                                                                                                        |
| rating                  | INTEGER     | true  | NULL           | {}                                                                                                                                                                                                                                                        |
| endRack                 | INTEGER     | true  | NULL           | {"rental_endRack_idx"}                                                                                                                                                                                                                                    |
| startRack               | INTEGER     | true  | NULL           | {"rental_startRack_idx"}                                                                                                                                                                                                                                  |
| failedPinStateCheck     | BOOL        | true  | NULL           | {}                                                                                                                                                                                                                                                        |
| end_lat                 | FLOAT       | true  | NULL           | {}                                                                                                                                                                                                                                                        |
| end_lng                 | FLOAT       | true  | NULL           | {}                                                                                                                                                                                                                                                        |
| start_lat               | FLOAT       | true  | NULL           | {}                                                                                                                                                                                                                                                        |
| start_lng               | FLOAT       | true  | NULL           | {}                                                                                                                                                                                                                                                        |
| reservation             | INT         | true  | NULL           | {}                                                                                                                                                                                                                                                        |
| canceled_on             | TIMESTAMP   | true  | NULL           | {}                                                                                                                                                                                                                                                        |
| charge_success          | BOOL        | true  | NULL           | {}                                                                                                                                                                                                                                                        |
| peach_charge_id         | STRING(60)  | true  | NULL           | {}                                                                                                                                                                                                                                                        |
| ratesv2_id              | INT         | true  | NULL           | {"idx_ratesv2_id"}                                                                                                                                                                                                                                        |
| perk_id                 | INT         | true  | NULL           | {}                                                                                                                                                                                                                                                        |
+-------------------------+-------------+-------+----------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
`

**Comment by JakielaAdam** [comment]
Yes there are foreign keys related to this table. I have attached the scheme as a text doc (wouldn't format properly as a comment.
[rental_table_scheme.txt](https://github.com/cockroachdb/cockroach/files/2185640/rental_table_scheme.txt)

**Comment by JakielaAdam** [comment]
@vivekmenezes would updating to 2.1 fix this issue?

**Comment by vivekmenezes** [comment]
@JakielaAdam 2.1 only comes out in October so that's not a solution for you. We'd like to create a fix and then port the fix to 2.0 so that you can have a fix earlier. Thanks for your patience.

**Comment by JakielaAdam** [comment]
@vivekmenezes Thank you. Do you know when this port will happen? This is currently preventing us from updating our software.

**Comment by vivekmenezes** [comment]
@JakielaAdam we're actively working on  #27273 which we think is related. Once we have a fix for it we can update you on which release it will be in. 

What release are you on now? Thanks

**Comment by JakielaAdam** [comment]
@vivekmenezes we are using 2.0.3

**Comment by jseldess** [comment]
@vivekmenezes, I just reproduced this `index-id` error using a public dataset I created for our performance tuning tutorial. The steps are below, but basically just start a local cluster, start the shell, create and set the `movr` database, import the three movr tables (`rides` will take several minutes cause it has 1MM rows), add foriegn key constraints, and then try to drop the `users.my_col` column, which does not itself have any foreign key dependencies.

```
~$ cockroach start --insecure --background
*
* WARNING: RUNNING IN INSECURE MODE!
*
* - Your cluster is open for any client that can access <all your IP addresses>.
* - Any user, even root, can log in without providing a password.
* - Any user, connecting as root, can read or write any data in your cluster.
* - There is no network encryption nor authentication, and thus no confidentiality.
*
* Check out how to secure your cluster: https://www.cockroachlabs.com/docs/v2.1/secure-a-cluster.html
*
~$ *
* WARNING: neither --listen-addr nor --advertise-addr was specified.
* The server will advertise "Jesses-MacBook-Pro-2.local" to other nodes, is this routable?
*
* Consider using:
* - for local-only servers:  --listen-addr=localhost
* - for multi-node clusters: --advertise-addr=<host/IP addr>
*
*
CockroachDB node starting at 2018-08-17 14:57:36.751570578 +0000 UTC (took 0.5s)
build:               CCL v2.1.0-alpha.20180702-1529-g39ddc67e9c @ 2018/08/14 16:36:20 (go1.10.1)
webui:               http://Jesses-MacBook-Pro-2.local:8080
sql:                 postgresql://root@Jesses-MacBook-Pro-2.local:26257?sslmode=disable
client flags:        cockroach --host=Jesses-MacBook-Pro-2.local:26257 --insecure
logs:                /Users/jesseseldess/cockroach-data/logs
temp dir:            /Users/jesseseldess/cockroach-data/cockroach-temp604286923
external I/O path:   /Users/jesseseldess/cockroach-data/extern
store[0]:            path=/Users/jesseseldess/cockroach-data
status:              initialized new cluster
clusterID:           0c6f423f-2773-4d0a-8a43-c1e5ddba6ad0
nodeID:              1

~$ cockroach sql --insecure
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.
#
# Server version: CockroachDB CCL v2.1.0-alpha.20180702-1529-g39ddc67e9c (x86_64-apple-darwin17.7.0, built 2018/08/14 16:36:20, go1.10.1) (same version as client)
# Cluster ID: 0c6f423f-2773-4d0a-8a43-c1e5ddba6ad0
#
# Enter \? for a brief introduction.
#
root@:26257/defaultdb> CREATE DATABASE movr;
CREATE DATABASE

Time: 5.044487ms

root@:26257/defaultdb> SET DATABASE = movr;
SET

Time: 638.605µs

root@:26257/movr> IMPORT TABLE users (                                                                                                                                                                          id UUID NOT NULL,                                                                                                                                                                                           city STRING NOT NULL,                                                                                                                                                                                       name STRING NULL,                                                                                                                                                                                           address STRING NULL,                                                                                                                                                                                        credit_card STRING NULL,                                                                                                                                                                                    CONSTRAINT "primary" PRIMARY KEY (city ASC, id ASC)                                                                                                                                                     )                                                                                                                                                                                                           CSV DATA (                                                                                                                                                                                                      'https://s3-us-west-1.amazonaws.com/cockroachdb-movr/datasets/perf-tuning/users/n1.0.csv'                                                                                                               );
        job_id       |  status   | fraction_completed | rows | index_entries | system_records | bytes
+--------------------+-----------+--------------------+------+---------------+----------------+--------+
  375021524839268353 | succeeded |                  1 | 1998 |             0 |              0 | 241052
(1 row)

Time: 3.530249544s

root@:26257/movr> IMPORT TABLE vehicles (                                                                                                                                                                       id UUID NOT NULL,                                                                                                                                                                                           city STRING NOT NULL,                                                                                                                                                                                       type STRING NULL,                                                                                                                                                                                           owner_id UUID NULL,                                                                                                                                                                                         creation_time TIMESTAMP NULL,                                                                                                                                                                               status STRING NULL,                                                                                                                                                                                         ext JSON NULL,                                                                                                                                                                                              mycol STRING NULL,                                                                                                                                                                                          CONSTRAINT "primary" PRIMARY KEY (city ASC, id ASC),                                                                                                                                                        INDEX vehicles_auto_index_fk_city_ref_users (city ASC, owner_id ASC)                                                                                                                                    )                                                                                                                                                                                                           CSV DATA (                                                                                                                                                                                                      'https://s3-us-west-1.amazonaws.com/cockroachdb-movr/datasets/perf-tuning/vehicles/n1.0.csv'                                                                                                            );
        job_id       |  status   | fraction_completed | rows  | index_entries | system_records |  bytes
+--------------------+-----------+--------------------+-------+---------------+----------------+---------+
  375021558124642305 | succeeded |                  1 | 19998 |         19998 |              0 | 3558767
(1 row)

Time: 7.250373705s

root@:26257/movr> IMPORT TABLE rides (                                                                                                                                                                          id UUID NOT NULL,                                                                                                                                                                                           city STRING NOT NULL,                                                                                                                                                                                       vehicle_city STRING NULL,                                                                                                                                                                                   rider_id UUID NULL,                                                                                                                                                                                         vehicle_id UUID NULL,                                                                                                                                                                                       start_address STRING NULL,                                                                                                                                                                                  end_address STRING NULL,                                                                                                                                                                                    start_time TIMESTAMP NULL,                                                                                                                                                                                  end_time TIMESTAMP NULL,                                                                                                                                                                                    revenue DECIMAL(10,2) NULL,                                                                                                                                                                                 CONSTRAINT "primary" PRIMARY KEY (city ASC, id ASC),                                                                                                                                                        INDEX rides_auto_index_fk_city_ref_users (city ASC, rider_id ASC),                                                                                                                                          INDEX rides_auto_index_fk_vehicle_city_ref_vehicles (vehicle_city ASC, vehicle_id ASC),                                                                                                                     CONSTRAINT check_vehicle_city_city CHECK (vehicle_city = city)                                                                                                                                          )                                                                                                                                                                                                           CSV DATA (                                                                                                                                                                                                      'https://s3-us-west-1.amazonaws.com/cockroachdb-movr/datasets/perf-tuning/rides/n1.0.csv',                                                                                                                  'https://s3-us-west-1.amazonaws.com/cockroachdb-movr/datasets/perf-tuning/rides/n1.1.csv',                                                                                                                  'https://s3-us-west-1.amazonaws.com/cockroachdb-movr/datasets/perf-tuning/rides/n1.2.csv',                                                                                                                  'https://s3-us-west-1.amazonaws.com/cockroachdb-movr/datasets/perf-tuning/rides/n1.3.csv',                                                                                                                  'https://s3-us-west-1.amazonaws.com/cockroachdb-movr/datasets/perf-tuning/rides/n1.4.csv',                                                                                                                  'https://s3-us-west-1.amazonaws.com/cockroachdb-movr/datasets/perf-tuning/rides/n1.5.csv',                                                                                                                  'https://s3-us-west-1.amazonaws.com/cockroachdb-movr/datasets/perf-tuning/rides/n1.6.csv',                                                                                                                  'https://s3-us-west-1.amazonaws.com/cockroachdb-movr/datasets/perf-tuning/rides/n1.7.csv',                                                                                                                  'https://s3-us-west-1.amazonaws.com/cockroachdb-movr/datasets/perf-tuning/rides/n1.8.csv',                                                                                                                  'https://s3-us-west-1.amazonaws.com/cockroachdb-movr/datasets/perf-tuning/rides/n1.9.csv'                                                                                                               );
        job_id       |  status   | fraction_completed |  rows  | index_entries | system_records |   bytes
+--------------------+-----------+--------------------+--------+---------------+----------------+-----------+
  375021601779843073 | succeeded |                  1 | 999996 |       1999992 |              0 | 339741841
(1 row)

Time: 9m20.329601678s

root@:26257/movr> ALTER TABLE vehicles                                                                                                                                                                      ADD CONSTRAINT fk_city_ref_users                                                                                                                                                                            FOREIGN KEY (city, owner_id)                                                                                                                                                                                REFERENCES users (city, id);
ALTER TABLE

Time: 44.003002ms

root@:26257/movr> ALTER TABLE rides                                                                                                                                                                         ADD CONSTRAINT fk_city_ref_users                                                                                                                                                                            FOREIGN KEY (city, rider_id)                                                                                                                                                                                REFERENCES users (city, id);
ALTER TABLE

Time: 25.672387ms

root@:26257/movr> ALTER TABLE rides                                                                                                                                                                         ADD CONSTRAINT fk_vehicle_city_ref_vehicles                                                                                                                                                                 FOREIGN KEY (vehicle_city, vehicle_id)                                                                                                                                                                      REFERENCES vehicles (city, id);
ALTER TABLE

Time: 29.009131ms

root@:26257/movr> set sql_safe_updates = false;
SET

Time: 486.617µs

root@:26257/movr> alter table vehicles drop column mycol;
pq: index-id "3" does not exist
root@:26257/movr>
```

**Comment by vivekmenezes** [comment]
@jseldess thanks for your help reproducing this issue. It does look like we're looking up a cached table descriptor when we apply an ALTER TABLE somewhere. See below, the command succeeds after a bit. Working on a fix.

```
root@:26257/movr> alter table vehicles drop column mycol;
pq: index-id "3" does not exist
root@:26257/movr> alter table vehicles drop column mycol;
pq: index-id "3" does not exist
root@:26257/movr> alter table vehicles drop column mycol;
pq: index-id "3" does not exist
root@:26257/movr> alter table vehicles drop column mycol;
ALTER TABLE
```
