### ISSUE TITLE
Transactions should be forwarded to the transaction coordinator.

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#2741]
SQL transactions can be started and resumed on different nodes. When this happens, the node resuming the transaction needs to go through the proper transaction coordinator.
The forwarding should be done within the KV client, removing the need for sql to do its own forwarding.

**Comment by tschottdorf** [comment]
You're mostly worried about load balancers, right? We can add the coordinator's NodeID to the `Txn` record and if a coordinator receives a transactional request that isn't its own, it relays it. As a side effect we can do #815 (currently we don't know the local `NodeID` in the coordinator).

**Comment by mberhault** [comment]
yup. But since load balancers and round-robin DNS are likely to be default deployment strategies, this is pretty badly needed. eg: right now, the deployment example will not work well with sql transactions that involve multiple requests.

**Comment by petermattis** [comment]
Mildly related: I've been exploring gRPC more. If we used gRPC for the client communication protocol and sent all of the transaction requests over a single streaming request I think they are guaranteed to go to the same host.

**Comment by tschottdorf** [comment]
@petermattis hmm - looks like more and more like `gRPC` could be beneficial in a bunch of ways - we should discuss this more seriously - do we have an issue for it? #647 maybe?

**Comment by tamird** [comment]
@tschottdorf does it make sense to wrap the DistSender around the TxnCoordSender to achieve this? It looks like the biggest roadblock to doing this is that DistSender is the only thing that knows how to send RPCs on the wire, but we could probably tease that out relatively easily.

**Comment by tschottdorf** [comment]
are you suggesting to have `DistSender` contain a `TxnCoordSender` as opposed to the other way around? That has some advantages, but also some technical challenges and amounts to a pretty significant refactor.
It's unclear to me what we actually want with this here issue. Is the goal to have production support for performant multi-RPC transactions against a round-robin load balancer? That doesn't seem to sit well with the state we keep about transactions - all the state would have to move to the client (not advised).
Do we just want to hack something into place that avoids awkward errors during a demo but has internal round-trips best avoided in production?
Down the road, will we only use the load balancer for gossip bootstrap (optionally) and client discovery (where a client RPCs a node to get a list of actual node addresses)? We'll have to do something like that if we ever want nodes to be able to redirect clients to other nodes in a non-random manner.
So far I get the impression that we just want the hack, but I think it's worth taking a step back and getting some bearings.

**Comment by tamird** [comment]
> are you suggesting to have `DistSender` contain a `TxnCoordSender` as opposed to the other way around?

Yes. While I think we should do that at some point, I suspect the real solution here is to move to a connection-oriented protocol so that disconnects amount to explicit session terminations.

**Comment by tschottdorf** [comment]
> are you suggesting to have DistSender contain a TxnCoordSender as opposed to the other way around?

That's not obviously the right thing to do, but I agree that their relationship needs refactoring. Doubt you want to get into that here though.

**Comment by tamird** [comment]
Closing this because PGWire.

**Comment by mberhault** [comment]
how does PGWire fix it? don't we still need to make sure the transaction is resumed by the right node?

**Comment by tamird** [comment]
PGWire is connection oriented; you're pinned to a node. If your connection dies, your transaction dies with it.
