### ISSUE TITLE
sql: Support MySQL SET types to improve usage of 64 bit ints as bitmasks

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#27415]
A "SET type" (from MySQL) is a datatype where values can contain zero, one or more values from a fixed list of up to 64 different possile values. They behave like a set because duplicates are not allowed and the order is not preserved.

MySQL implements this using a bitmap, with one bit per possible value in the fixed list of allowable values..

So implementation-wise this is really a feature on top of 64-bit integers.

https://dev.mysql.com/doc/refman/5.7/en/set.html

**Comment by knz** [comment]
I double checked:

1) postgres does not support set types; instead it "indirectly" supports them by allowing users to define arrays of enums.
2) oracle does not support neither enums nor set types

So this is a mysql-specific feature really. I'll remove the "pgcompat" label and add this to the wish list.

**Comment by bra-fsn** [comment]
If you ever decide to implement this it would be nice not to limit this to 64 bits.
