### ISSUE TITLE
sql: SHOW JOBS should not abort if it finds invalid data in `system.jobs`

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#27427]
A user is reporting that their `SHOW JOBS` command completely fails with

```
pq: Job: failed to unmarshal Progress as DBytes (was tree.dNull)
```

It seems (due to unrelated issue which will be worked on) that a botched import has improperly populated the progress field. That separate issue will be worked on separately.

In the meantime, SHOW JOBS should be more tolerant of invalid/incorrect input data and instead perhaps report a NULL value in its output and/or an explanatory error text in its results.

**Comment by glaslos** [comment]
I experience the same issue with v.2.1.3 on CANCEL JOB
```
CANCEL JOB 123;
pq: Job: failed to unmarshal Progress as DBytes (was tree.dNull)
```
