### ISSUE TITLE
opt: some filters not pushed down through left joins

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#27431]
As shown here: https://github.com/cockroachdb/cockroach/pull/27409#event-1728726740, the optimizer is not inferring all possible filters using equality columns. 

For example, consider this query:

`SELECT * FROM l LEFT JOIN r USING(a) WHERE a=3`

Here, `a=3` is interpreted as `l.a=3`. The optimizer is only pushing the filter down to the left side, when it should actually be pushed to both sides. The problem is that in the query tree built by the optbuilder, the equality is in the join's ON condition; it's not part of the Select filter. We'll need to use the FDs of the input as well as the filter to map `l.a=3` to `r.a=3` and push to both sides.

**Comment by RaduBerinde** [comment]
Note, this issue is basically #20765 reincarnated.
