### ISSUE TITLE
build: windows binaries failing

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#27435]
As part of #27426, I build test binaries and ran bincheck (simply stick `test:27426` in the `VERSION` file).
It [failed](https://ci.appveyor.com/project/cockroachdb/bincheck/build/1.0.153) while running the windows binary with:

```
C:/projects/bincheck/mnt/cockroach.exe: error while loading shared libraries: libwinpthread-1.dll: cannot open shared object file: No such file or directory
```

Since it didn't seem related to my change, I retried with the most recently-merged PR (#27422). Same [failure](https://ci.appveyor.com/project/cockroachdb/bincheck/build/1.0.154#L23).

@benesch: I can try other PRs but it's a little slow to iterate. Any ideas? I'm going to try pre-rocksdb bump first.

**Comment by mberhault** [comment]
I tested binaries just before (#27309) and after (#27299) the rocksdb bump. Both executed.
I'll keep looking.

**Comment by benesch** [comment]
Eek, sorry, my fault. It's https://github.com/cockroachdb/cockroach/commit/38899a8cf25797e431acb2dfc12823dc4c24a93b#diff-9cbc73b2c5289c9fe79bb5343b77452f again. I'll send a PR your way in a sec.
