### ISSUE TITLE
storage: add a merge jepsen nemesis

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#27447]
Jepsen currently has a split nemesis. We should extend it, or add a similar one, to stress test merges.

**Comment by benesch** [comment]
@bdarnell what's left to do here?

**Comment by bdarnell** [comment]
There's no user control of merges, so we can't make a nemesis for it. Instead, we need to run the split nemesis with merges enabled. I've hacked that together in https://github.com/cockroachdb/jepsen/commits/merge; that needs to be cleaned up (and made optional or just always run it when we run the split nemesis?)
