### ISSUE TITLE
storage: Cluster can't recover if all nodes are decommissioned and restarted

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#27444]
A user on our forum reported that they accidentally decommissioned and restarted all the nodes in their cluster: https://forum.cockroachlabs.com/t/restarting-from-decommissioned-nodes/1826

It turns out that if you do this in any size of cluster (including a local 3 node cluster), the cluster never recovers after the restart because all the nodes still consider themselves in a draining state, which causes all `RequestLease` requests get dropped on the floor:

https://github.com/cockroachdb/cockroach/blob/218a95432fbd3dd9bdde153c7f280eae9a702dd6/pkg/storage/replica_range_lease.go#L527-L531

This affects **all** lease requests, including those for r1, so no range ever gets a leaseholder. This keeps anything from happening in the cluster and even breaks a surprising fraction of our debug pages. It also, of course, prevents the `recommission` command from working.

I was able to "fix" such a cluster by removing the code highlighted above and rebuilding the binary, but that's not a great solution given that in most cases we really don't want to request new leases on decommissioned nodes.

It may be preferable to reject decommissioning attempts that would prevent a cluster from continuing to function. That'd be tough to guarantee, though, if we want to protect all ranges from losing quorum. So perhaps there's a middle ground where we allow draining nodes to take leases for ranges that don't have a known active leaseholder.

I'm curious for @nvanbenschoten and @asubiotto's thoughts.

**Comment by a-robinson** [comment]
Also @tschottdorf

**Comment by tschottdorf** [comment]
I might be missing some additional complication, but in a similar issue my conclusion was that it was a mistake to immediately initiate draining when the node realizes it's decommissioning as that throws a wrench into everything. Instead, draining should be activated once decommissioning is complete. Or, not even at all - the operator will shut down the node which, if done gently, goes through proper draining.

The "similar issue" is https://github.com/cockroachdb/cockroach/issues/27025, and I think it's an exact duplicate, just for the case of a single node.

**Comment by a-robinson** [comment]
Ah, thanks for connecting the two. I can't think of a reason not to delay draining until decommissioning is complete, assuming we define "complete" to mean that the node has no more replicas on it.

**Comment by tim-o** [comment]
Zendesk ticket #[2709](https://cockroachdb.zendesk.com/agent/tickets/2709) has been linked to this issue.

**Comment by tim-o** [comment]
*Comment made from Zendesk by Ricardo Rocha on 2019-07-08 at 14:23:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Closing older ZenDesk forum incidents as per Support meeting on 7/2</p></div></blockquote>
