### ISSUE TITLE
server: node communication issues using 3rd party certificates

### ISSUE THREAD

**Issue by josephmiano** [cockroachdb/cockroach#27450]
Issue/Bug/Question

Summary:
We are using our own certificate authority to create certificates for our Cockroach cluster build.  After creating the certificates, we are experiencing communication issues when attempting to start the cluster. Port communication on 26257 between the nodes does not seem to be an issues since we can telnet after starting the service.  We also verified the node.crt and client.root.crt files against the ca.crt and they return valid.

Steps to reproduce:
Created node.crt and client.root.crt using a third party CA.
Started cockroach on all 3 nodes

Results Expected:
Cluster communication between nodes to be successful.

Results Occured:
Cluster will not start. Following message is returned: WARNING: The server appears to be unable to contact the other nodes in the cluster.

Logs: 
Logs are attached.
[cockroach-10.log](https://github.com/cockroachdb/cockroach/files/2190368/cockroach-10.log)
[cockroach-20.log](https://github.com/cockroachdb/cockroach/files/2190369/cockroach-20.log)
[cockroach-30.log](https://github.com/cockroachdb/cockroach/files/2190370/cockroach-30.log)

Version:
Build Tag:    v2.0.2
Build Time:   2018/05/21 14:55:20
Distribution: CCL
Platform:     linux amd64 (x86_64-unknown-linux-gnu)
Go Version:   go1.10
C Compiler:   gcc 6.3.0
Build SHA-1:  fa2b2bfd802ebe8150030a14b0a36c25fef90b91
Build Type:   release

Certificate Validation:
openssl verify -CAfile ca.crt node.crt
node.crt: OK
openssl verify -CAfile ca.crt client.root.crt
client.root.crt: OK

**Comment by mberhault** [comment]
Let's try a few things:
1) please use 2.0.3
2) using the same start arguments but with `--insecure=true`, does the cluster start? Does the admin UI show all three nodes running and all ranges fully replicated?
3) does each dns name resolve to a locally-bindable address (eg: does `cockroachdb10.us.corp.com` resolve to the value of the `--host` flag?
4) what does `cockroach cert list --certs-dir=/home/cockroachdb/certs` output?
5) what does `openssl x509 -text -in <cert file>` say for each `.crt` file? Especially `node.crt`.

**Comment by mberhault** [comment]
One more thing: you haven't run `cockroach init` against any of the nodes, so they're all still uninitialized.
What happens when you run `cockroach init --host=<one of the nodes> --certs-dir=etc...`?

**Comment by josephmiano** [comment]
First, I upgraded to 2.0.3.

[cockroach-10.log.0713.txt](https://github.com/cockroachdb/cockroach/files/2194330/cockroach-10.log.0713.txt)
[cockroach-20.log.0713.txt](https://github.com/cockroachdb/cockroach/files/2194331/cockroach-20.log.0713.txt)
[cockroach-30.log.0713.txt](https://github.com/cockroachdb/cockroach/files/2194332/cockroach-30.log.0713.txt)

The first test was with the cockroach init on my existing cluster.  The cluster initialized and returned the details are returned on the node that I set as the --host in the init command.  However the other nodes do not initialize.  They continue to have communication issues.  The logs are attached.  I do see "bad certificate" errors in the logs.

I tested each dns name and verified that they resolve to the local IP address. 

I then ran the cockroach cert list on each server.  Should the IP address for each node be listed in the notes for the node.key?  I dont see the IP address there.

Certificate directory: /home/cockroachdb/certs
+-----------------------+------------------+-----------------+------------+-------------------------------------------------------+-------+
|         Usage         | Certificate File |    Key File     |  Expires   |                         Notes                         | Error |
+-----------------------+------------------+-----------------+------------+-------------------------------------------------------+-------+
| Certificate Authority | ca.crt           |                 | 2035/09/16 | num certs: 9                                          |       |
| Node                  | node.crt         | node.key        | 2020/06/29 | addresses: cockroach10,cockroachdb10.us.corp.com |       |
| Client                | client.root.crt  | client.root.key | 2020/06/29 | user: root                                            |       |
+-----------------------+------------------+-----------------+------------+-------------------------------------------------------+-------+

Certificate directory: /home/cockroachdb/certs
+-----------------------+------------------+-----------------+------------+-------------------------------------------------------+-------+
|         Usage         | Certificate File |    Key File     |  Expires   |                         Notes                         | Error |
+-----------------------+------------------+-----------------+------------+-------------------------------------------------------+-------+
| Certificate Authority | ca.crt           |                 | 2035/09/16 | num certs: 9                                          |       |
| Node                  | node.crt         | node.key        | 2020/06/30 | addresses: cockroach20,cockroach20.asia.corp.com |       |
| Client                | client.root.crt  | client.root.key | 2020/06/29 | user: root                                            |       |
+-----------------------+------------------+-----------------+------------+-------------------------------------------------------+-------+

Certificate directory: /home/cockroachdb/certs
+-----------------------+------------------+-----------------+------------+-------------------------------------------------------+-------+
|         Usage         | Certificate File |    Key File     |  Expires   |                         Notes                         | Error |
+-----------------------+------------------+-----------------+------------+-------------------------------------------------------+-------+
| Certificate Authority | ca.crt           |                 | 2035/09/16 | num certs: 9                                          |       |
| Node                  | node.crt         | node.key        | 2020/06/30 | addresses: cockroach30,cockroach30.euro.corp.com |       |
| Client                | client.root.crt  | client.root.key | 2020/06/29 | user: root                                            |       |
+-----------------------+------------------+-----------------+------------+-------------------------------------------------------+-------+

Last test, I tore down the cluster and restarted it in --insecure=true mode.  I had no issues launching the cluster.  Communication between the nodes was just fine.  I was able to run command line sql and create then drop databases. The UI showed all 3 nodes running and fully replicating the data.  See attached image.

![insecure-cluster](https://user-images.githubusercontent.com/38541857/42716507-b9636804-86b0-11e8-9899-f7dfc1aeda28.JPG)

**Comment by mberhault** [comment]
Yes, the certificate needs to contain all addresses that will be used to reach the host. Usually, this means at least one DNS name and one IP address. The error message in the log says: 

```
W180713 20:14:04.374057 1608 vendor/google.golang.org/grpc/clientconn.go:830  Failed to dial 10.99.205.22:26257: connection error: desc = "transport: authentication handshake failed: x509: cannot validate certificate for 10.99.205.22 because it doesn't contain any IP SANs"; please retry.
```

**Comment by josephmiano** [comment]
I attempted to recreate the certificates using our in-house CA, however our CA will not create certificates using IP addresses.  We can use the host name and fully qualified domain name, but not the IP address or localhost. Are there ways around using the IP address? Have you had this issue with other customers using Cockroach with 3rd party CAs?

**Comment by mberhault** [comment]
You're specifying an IP address in `--host`, which means this will be the advertised address (the one other nodes use to reach this one). Given that, it **has** to be in the certificate or it won't be verified. You can leave `--host` out and set `--advertise-host` to a DNS name resolvable (and reachable) from all other hosts.

**Comment by mberhault** [comment]
Thanks for the details.
Could you clarify a few things:
- addresses of all nodes (eg: dns lookup both locally and from another host)
- `openssl x509 -text -in <cert file>` for each certificate (all nodes, as well as the CAs)
- try keeping the nodes up longer after the init, it looks like cockroach20 was just starting to talk to cockroach10.

The commands used to generate the CSRs for the node certificates would be helpful as well.

**Comment by mberhault** [comment]
A small thing I noticed in the logs: it seems that `cockroach30.euro.corp.com` is trying to join `COCKROACH20.gar.corp.intel.com` instead of `cockroach20.asia.corp.com`. That wouldn't be the problem as I agree that cockroach20 and cockroach30 are talking to cockroach10 but for some reason not joining the cluster. Still, it can't hurt to be consistent.

**Comment by tim-o** [comment]
@josephmiano  - see @mberhault's comments above. Please advise if that helped.

**Comment by josephmiano** [comment]
Addresses resolve properly from each node and can be pinged by the host name, fully qualified and address.  

Attached are the openssl x509 commands output.  (the full certificate at the end has been removed from the file for security purposes)
[cockroach10_node_crt.txt](https://github.com/cockroachdb/cockroach/files/2220413/cockroach10_node_crt.txt)
[cockroach20_node_crt.txt](https://github.com/cockroachdb/cockroach/files/2220414/cockroach20_node_crt.txt)
[cockroach30_node_crt.txt](https://github.com/cockroachdb/cockroach/files/2220415/cockroach30_node_crt.txt)

I restarted the cluster again after seeing your response and allowed it to stay up and running for over 30 minutes.  The second and third node did not establish communication during this time.

To create the key: openssl genrsa -out node.key 2048
To create the csr: openssl req -new -key node.key -out node.csr
Signing the CSR with the CA is through an internal website.  The alternative names are defined at that time.

**Comment by mberhault** [comment]
The node certificates act as dual-purpose server/client certificates. You have the `Client Authentication` extended key usage field, but you're missing the `CN=node` field, using it for the DNS name instead. This means that the cockroach nodes see the incoming user as `cockroach.10.us.corp.com` etc... instead of `node` and refuse the connection.

Please see the [Create the certificate and key pairs for nodes](https://www.cockroachlabs.com/docs/v2.0/create-security-certificates-openssl.html#create-the-certificate-and-key-pairs-for-nodes) of the docs for details.

**Comment by josephmiano** [comment]
Changing the CN to 'node' resolved this issue. Communication between the nodes is now working with the --advertise-host.  The admin page is also working as expected!

**Comment by mberhault** [comment]
Glad to hear it. I'm [tweaking the docs](https://github.com/cockroachdb/docs/pull/3423) to make the warning about setting `commonName = node` stronger.
