### ISSUE TITLE
storage: evaluate improved rebalancing heuristics

### ISSUE THREAD

**Issue by mrtracy** [cockroachdb/cockroach#2747]
Cockroach now has the basic ability to relocate replicas between nodes for the purpose of rebalancing; however, the heuristics for determining the details of a specific rebalance are very simple and could use some tuning.

Checklist for completion of this: 
- [ ] Finish the first version of the Rebalancing Simulator, a tool which runs Cockroach's allocator (the brains behind relocation) against a simulated cluster and evaluates the quality of its decisions.
- [ ] Assemble a list of scenarios for the simulator; scenarios would prescribe a cluster configuration (i.e. # of nodes with attribuets), a simulated cluster load (i.e. different write patterns), and would include cluster-modifying events such as adding or removing nodes.
- [ ] Assemble a list of candidate modifications to the rebalancing heuristics; these modifications should be run through the simulator first to see if they result in a better behavior for any of the scenarios.

**Comment by petermattis** [comment]
Closing due to age. The rebalancing heuristics and testing have evolved a lot since this was filed.
