### ISSUE TITLE
storage: unable to use store fixture generated with 2.1 binary with latest 2.1

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#27525]
Running `roachtest run clearrange` with that test configured to use the fixture `gs://cockroach-fixtures/workload/bank/version=1.0.0,payload-bytes=10240,ranges=0,rows=65104166,seed=3` (notice the `seed=3`) and nodes 2-10 exit at startup with the error:

```
Error: cockroach server exited with error: inspecting engines: store <no-attributes>=/mnt/data1/cockroach, last used with cockroach version v1.1, is too old for running version v2.0-8 (which requires data from v2.0 or later)
```

The fixture was generated with version `v2.0-7` (this is stored in the name of the store subdirectory for the above fixture). Did we foul something up with the recent cluster version bumps?

Cc @nvanbenschoten who touched some code in this area recently.

**Comment by petermattis** [comment]
Well, the minimum supported version changed from `v1.1` to `v2.0` in https://github.com/cockroachdb/cockroach/pull/26968, but that should have been ok. The curious bit is why the store fixtures think the stores were created with a v1.1 binary when clearly they were created with a 2.1 binary.

**Comment by petermattis** [comment]
I think there is a real problem here, but it is something of an edge case.

When a cluster is bootstrapped, the bootstrapping node initializes its store cluster-version as `ClusterVersion{MinimumVersion: BinaryVersion, UseVersion: BinaryVersion}`. So a recent 2.1 binary will use `{2.0-8, 2.0-8}`. 

There is a different code path for a node joining a cluster. `Stores.SynthesizeClusterVersion` determines that there are no stores on the node yet and uses `settings/cluster.BinaryMinimumSupportedVersion`. Prior to #26968 such a node would initialize its stored cluster version to `{1.1, 1.1}`. 

This explains something mentioned in the original report: only nodes 2-10 died. Node 1 had a compatible cluster version in the store.

A bit of logging shows that nodes added to the cluster never overwrite their stored cluster version until they are restarted. I think we might be missing setup of `n.storeCfg.Settings.Version.OnChange` when a node is bootstrapped.

Cc @tschottdorf

**Comment by petermattis** [comment]
> I think we might be missing setup of n.storeCfg.Settings.Version.OnChange when a node is bootstrapped.

Nope, that wasn't it. What seems to be happening is that the cluster version changed callback is invoked before the stores are bootstrapped. `Stores.OnClusterVersionChange` is called, but there are no stores so there is nothing to do. Perhaps that callback should also set `Stores.minSupportedVersion`.

@tschottdorf I'm not terribly familiar with how this all works. I'm going to leave this in your hands.

**Comment by tschottdorf** [comment]
Looking. Your analysis seems reasonable.

**Comment by tschottdorf** [comment]
Also https://github.com/cockroachdb/cockroach/issues/27162 is likely hitting the same problem.
