### ISSUE TITLE
Error message "value type is not BYTES: UNKNOWN"

### ISSUE THREAD

**Issue by dbtleonia** [cockroachdb/cockroach#2754]
Hi. I was just playing around with cockroachdb and saw this error:

e42329df51fc:26257> select * from descriptor;
query error: value type is not BYTES: UNKNOWN

Vivek said he hadn't seen this error before and to file a bug.

**Comment by tamird** [comment]
Confirmed I can repro this.

**Comment by petermattis** [comment]
Mea culpa. I'll fix.

**Comment by tamird** [comment]
I got it.

**Comment by petermattis** [comment]
Hmm, internet connection is spotty on the train. Perhaps our messages crossed.
