### ISSUE TITLE
Question: execDistSQL() usage from executor.go.

### ISSUE THREAD

**Issue by minglinlu** [cockroachdb/cockroach#27551]
Hey man, I am a freshman here.
I researched on CRDB's code, and got some confused.
As far as I know, if you type a SQL statement from the client cmd line,
sth like `select * from table`.
and the code would come into `execStmt()` method from executor.go,
next, CRDB would check whether to use `execDistSQL()` according to `useDistSQL` variable.
and then, the code comes to 'e.distSQLPlanner.PlanAndRun(ctx, planner.txn, tree, &recv, planner.evalCtx)' from executor.go.
and then, go to `dsp.Run(&planCtx, txn, &plan, recv, evalCtx)` from distsql_running.go,
and then, a `runnerRequest` is initiated,  
What I wanna know is that:
Where could I found the logic handle method(fetch data) when the runnerRequest is sent to nodes?

To be more cleared, I wanna find where  does it fetch data from kv storage.
For exmaple, `engine.MVCCScan()` would return keyValues.
Thanks in advanced!

**Comment by jordanlewis** [comment]
Take a look at `tablereader.go`, which calls `rowfetcher.go`, which calls `kvfetcher.go`, which finally is the one that sends an MVCCScan request. If you want to know more details, check out the ["life of a query" document ](https://github.com/cockroachdb/cockroach/blob/1bf936f623c43df9bb559e6056ea29215f16b237/docs/tech-notes/life_of_a_query.md).

**Comment by minglinlu** [comment]
breakpoint at `newTableReader()` from `tablereader.go` is debugable!
Thx again! @jordanlewis
