### ISSUE TITLE
sql: the ordering of NULLs is inconsistent with postgres

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#27603]
(Found while investigating #12022.)

https://www.postgresql.org/docs/current/static/sql-select.html#SQL-ORDERBY

> If NULLS LAST is specified, null values sort after all non-null values; if NULLS FIRST is specified, null values sort before all non-null values. 
> If neither is specified, the default behavior is NULLS LAST when ASC is specified or implied, and NULLS FIRST when DESC is specified (thus, **the default is to act as though nulls are larger than non-nulls**).

CockroachDB does this the other way.

This is really a major bummer because the KV encoding requires the default to be the other way. Sigh.

I think that sanity requires here that we accept+keep this difference with pg and instead have a big fat documentation that explains this difference and tells users they have to deal with it.

cc @bdarnell what do you think?

**Comment by bdarnell** [comment]
> I think that sanity requires here that we accept+keep this difference with pg and instead have a big fat documentation that explains this difference and tells users they have to deal with it.

Agreed. Also see https://github.com/cockroachdb/cockroach/issues/6224#issuecomment-213573799 which points out that several non-postgres databases work the way we do and don't have the option of NULLS FIRST/NULLS LAST.

**Comment by knz** [comment]
This is already documented on our docs site (in the page on NULL handling) so there is nothing actionable. Closing in favor of #6224.
