### ISSUE TITLE
sql: always allow GROUP BY expression as result column

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#2761]
This tricky query appears in the SQLAlchemy test suite. `some_table.x + some_table.y` is safe for use as a result column and in the ORDER BY because it is also the GROUP BY expression, but we do not recognize this and return an error: "column "x" must appear in the GROUP BY clause or be used in an aggregate function".

`SELECT count(some_table.id) AS count_1, some_table.x + some_table.y AS lx FROM some_table GROUP BY some_table.x + some_table.y ORDER BY lx`

**Comment by petermattis** [comment]
We don't support group by yet (see #2174), so this error is expected until we do.

**Comment by bdarnell** [comment]
Ah. The error message implied that it would have worked if an aggregate function had been used. I'm also a bit surprised that this was the only use of GROUP BY in (this portion of) the test suite.

**Comment by petermattis** [comment]
That's the right error message for when GROUP BY is supported, but confusing when it isn't.

**Comment by petermattis** [comment]
I believe this is fixed by #3494, but please confirm.

**Comment by dt** [comment]
Yep, I included a paraphrased version of that query in the tests too.
