### ISSUE TITLE
ui: special treatment for empty databases

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#27620]
This page needs some design love.

* We should have some nicer treatment for empty databases, using the legend on the right as a spacer makes this page really ugly. 
* Why is there a line between crossccl and default, but not the others?  (this is no other line at all on the page)
* Unless there is something inside the postgres DB, let's just not show it.
* Perhaps add the ability to hide dbs as well, just a simple expand/minimize type thing.

![screen shot 2018-07-16 at 16 13 24](https://user-images.githubusercontent.com/1614265/42781136-455506ec-8913-11e8-919e-e7988b7e0eb1.png)

**Comment by couchand** [comment]
The `<hr>` separates user-created databases from system-created ones.

I don't like the idea of completely hiding the default databases (for instance, if you tried to create one of them you'd get an error), but it's definitely worth thinking about how to minimize their impact when empty and unused.

**Comment by couchand** [comment]
I guess this got duped by #28234.
