### ISSUE TITLE
remove KV-level key length restriction

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#2765]
We don't seem to rely on it and it's likely to cause weird failures when encountered via the SQL layer (plus likely internally as well; it's not really well-tested). Is there any reason to not just rip it out? If we want to limit the length of keys somehow, we could impose some form of limitation in the schema (blocking creation of indexes which could generate large columns).

**Comment by petermattis** [comment]
Agreed that we should place the limit at the SQL layer and not at the KV layer.

**Comment by mrtracy** [comment]
I thought the key-length restriction was necessary for Key.Prev() or a related function.

**Comment by tschottdorf** [comment]
I think that was on the table originally, but we've made sure to get rid of `.Prev()` since.

**Comment by mrtracy** [comment]
If I remember correctly, the `.Prev()` function was the original inspiration for the maximum key length; if it's gone, then this restriction should be safe to remove completely.
