### ISSUE TITLE
ui: Gossip graph debug page

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#27652]
It's sometimes useful to look at a graph of gossip connections to identify partitions. The edges in the gossip graph are available on a per-node basis in the logs:

```
[n10] gossip status (ok, 9 nodes)
gossip client (2/3 cur/max conns)
  12: n12:26257 (34m1s: infos 5764/7020 sent/received, bytes 2049681B/2854441B sent/received)
  4: n4:26257 (34m1s: infos 1733/33091 sent/received, bytes 791770B/4877590B sent/received)
gossip server (2/3 cur/max conns, infos 76313/46057 sent/received, bytes 16145538B/10178190B sent/received)
  7: n7:26257 (32m20s)
  8: n8:26257 (30m55s)
```

We can aggregate this information across all nodes to produce a graph like this:

![image](https://user-images.githubusercontent.com/160562/42837465-27bf9eda-89cc-11e8-8a1f-acb156381ae5.png)

I'd like to have such a graph in the debug pages (perhaps the `/reports/network` page)

**Comment by vilterp** [comment]
cc @piyush-singh 

Could use https://github.com/dagrejs/dagre to visualize the graph. We already depend on this for the command queue visualization, and its output looks pretty similar to Graphviz.

**Comment by tschottdorf** [comment]
This is pretty high on the list of things that I'd like. If we provided an endpoint that produces the right source data, how hard would it be to slap that together in a debug page? Is there a code sample I could riff off of?

**Comment by couchand** [comment]
@tschottdorf take a look at the command queue page, I think @vilterp is right that we should just use that same library to draw this graph.  https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/src/views/reports/containers/commandQueue/commandQueueViz.tsx

**Comment by vilterp** [comment]
K, looks like thanks to @tschottdorf's 8a758e969b4d2c239e718be857faaeb2a6843b0a, the data to render this page is now exposed via the `Gossip` endpoint https://github.com/cockroachdb/cockroach/blob/a49eaefe9a1c4324ae2243badf704529782cfc92/pkg/server/serverpb/status.proto#L716-L720
