### ISSUE TITLE
storage, ui: Add a new problem range state of Raft Log Size Too Large

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#27709]
When a raft log grows too large it can cause numerous problems.  
We should define a new problem range state when the raft log very large.  > 1MiB or maybe > 10MiB.

This should be piped all the way into the problem ranges report in the ui.

This is a super easy task and I think we can get it into version 2.1.

**Comment by couchand** [comment]
closed in #28034
