### ISSUE TITLE
More time zone issues

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#2773]
The SQL logic tests fail when run after 8pm in New York. The failing test is
```
query T
SELECT now() - current_date()::timestamp < interval '24h10s'
----
true
```

Expanding those two expressions, we see that `now()` is `2015-10-06 01:42:42.244354302 +0000 UTC` and `current_date()::timestamp` is `2015-10-05 00:00:00 +0000 UTC`. `current_date()` is operating in the server's time zone (EDT) instead of the session time zone (UTC). 

`current_date()` is currently a separate code path from `current_timestamp()::date`. We need to either provide some way to mock out the EvalContext timestamps for testing or redefine `current_date()` in terms of a cast so it can't diverge in this way.

There's also an asymmetry in the cast operators: casting a timestamp to a date considers the session time zone, but casting a date to a timestamp does not. This seems incorrect.

**Comment by vivekmenezes** [comment]
in postgres casting a date to a timestamp results in a UTC timestamp and is
unrelated to the session. I think we should use the session time zone for
casting in both directions.

**Comment by tamird** [comment]
> in postgres casting a date to a timestamp results in a UTC timestamp and is
unrelated to the session. I think we should use the session time zone for
casting in both directions.

This is just not true.

```
$ psql test
test=# SET TIME ZONE 'Europe/Rome';
SET
test=# select '2015-07-12'::timestamp with time zone;
      timestamptz
------------------------
 2015-07-12 00:00:00+02
(1 row)
```

**Comment by bdarnell** [comment]
But we don't implement the `timestamp with time zone` type (and the postgres docs recommend that this type not be used). Our timestamps don't have time zones because time zones are a property of the session and not the data.

**Comment by tamird** [comment]
Fair enough, but then it's still the case that "in postgres casting a date to a timestamp results in a UTC timestamp" is not true.

**Comment by vivekmenezes** [comment]
select '2015-07-12'::timestamp

returns a UTC timestamp independent of the session time zone. This is not
how we are going to implement it.

**Comment by tamird** [comment]
@vivekmenezes it returns a timestamp, but it is not UTC because it doesn't have a time zone associated with it.

**Comment by bdarnell** [comment]
In postgres, `current_timestamp` is of type `timestamp with time zone`, not `timestamp`. Reading the docs more closely, postgres discourages the use of type `time with time zone` (i.e. no date portion), but `timestamp with time zone` is fine.

**Comment by vivekmenezes** [comment]
Summary of an offline discussion

The wire/storage  protocol for timestamp/date is a timestamp in UTC. date
when represented as a time.Time value must have a <sec, nsec> value
corresponding to a timestamp at midnight at UTC.

The time zone of a session is to be used for:
1. parsing timestamp strings used as input
2. presenting timestamp on the client side (not supported)
3. casting a timestamp to a date.

Given the above we should not care what location a particular timestamp
value (time.Time) holds on the server side. We just have to ensure on the
server end that we are paying heed to the session location while performing
1 and 3.
