### ISSUE TITLE
sql: a new foreign key column cannot be added in a single transaction

### ISSUE THREAD

**Issue by zacps** [cockroachdb/cockroach#27732]
**Bug report/Feature request**

A foreign key constraint cannot be added in the same transaction as the column:

```sql
CREATE TABLE a(id INTEGER PRIMARY KEY);
CREATE TABLE b(id INTEGER PRIMARY KEY);

BEGIN TRANSACTION;
ALTER TABLE a ADD COLUMN ab INTEGER;
CREATE INDEX "x" ON a(ab);
ALTER TABLE a ADD CONSTRAINT fk_ab_refs_b FOREIGN KEY (ab) REFERENCES b(id);
COMMIT;

-- pq: column "ab" does not exist
```

Workaround: Don't use a transaction.
Limitations: Invalid values could be inserted into the table before the constraint can be applied.

Version: 2.0.1

**Comment by nvanbenschoten** [comment]
cc. @knz for triage.

**Comment by knz** [comment]
I think the code that adds a FK constraints can also accept to create FKs over new columns in mutations?

**Comment by vivekmenezes** [comment]
Thanks for reporting this issue!

closing since it's the same as #24919
