### ISSUE TITLE
log.Fatal in TestStoreRangeSplitAtTablePrefix in multi-cpu

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#2775]
Discovered in #1839

https://circleci.com/gh/cockroachdb/cockroach/8282

https://circle-artifacts.com/gh/cockroachdb/cockroach/8282/artifacts/0/tmp/circle-artifacts.HFeUuK8/test.log

```
F1005 20:41:37.667210 985 storage/replica_command.go:1262  failed to update Store after split: storage/replica_raftstorage.go:378: failed to lookup zone config for Range range=3 ["\xff\f\x03\xe8"-"\xff\xff"): sql/config.go:68: descriptor for object ID 1000 is not a table or database
```

**Comment by tamird** [comment]
Another one:

https://circleci.com/gh/cockroachdb/cockroach/8443
https://circle-artifacts.com/gh/cockroachdb/cockroach/8443/artifacts/0/tmp/circle-artifacts.6DtEWJT/test.log

**Comment by tschottdorf** [comment]
blocks #1839

**Comment by tamird** [comment]
This has morphed slightly. It now fails with:
> failed to update Store after split: storage/replica_raftstorage.go:381: failed to lookup zone config for Range range=3 ["\xff\f\x03\xe8"-"\xff\xff"): value type is not BYTES: INT

https://circleci.com/gh/cockroachdb/cockroach/8897
https://circle-artifacts.com/gh/cockroachdb/cockroach/8897/artifacts/0/tmp/circle-artifacts.7Opja5w/test.log
