### ISSUE TITLE
sql: implement pg_catalog.pg_opclass

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#27765]
See https://www.postgresql.org/docs/10/static/catalog-pg-opclass.html for details.

This is needed for #27763.

To do this, we will require fleshing out some more pg_catalog tables:

* pg_catalog.pg_am needs to be populated
* pg_catalog.pg_authid needs to be implemented and populated
* pg_catalog.pg_opfamily needs to be implemented and populated

**Comment by jordanlewis** [comment]
Duplicate of #48729.
