### ISSUE TITLE
Red Hat container image needs updating

### ISSUE THREAD

**Issue by kannanlakshmi** [cockroachdb/cockroach#27810]
From red hat:
Repository: | cockroachdb/cockroach -- | --
Issue identified: | Security vulnerability patch available but not applied
Action required: | Rebuild and republish your container image
Current Grade: | B
Grade drops on: | August 11, 2018

A security vulnerability has been identified in a Red Hat component which impacts your latest certified container image in repository cockroachdb/cockroach.

This has been fixed by Red Hat and we request that you incorporate these changes in your container image by building and publishing an updated container.

Regular updates are required for your image to maintain its certified status.

Depending on how you update your image, there are two options:

1. If you are manually updating your image, follow these steps:

Ensure your dockerfile installs and applies fixes to critical/important vulnerabilities. This is typically accomplished with the following command within the Dockerfile:
yum -y update-minimal --security --sec-severity=Important --sec-severity=Critical --setopt=tsflags=nodocs
Build a new image
Select the target project in Red Hat Connect (login required)
Go to the “Upload Your Image” tab and see details on how to upload a new, updated image for certification scan
Once the scan is completed successfully, click the publish button for this updated image
2. If you have automated this process:

Your container project status already reflects the need to rebuild. You can find additional details by looking at the “Container Certification API” tab in your project.

**Comment by a-robinson** [comment]
@kannanlakshmi is this the email from July 12? I pushed a new image a few days ago.

**Comment by kannanlakshmi** [comment]
yes, i didnt realize you got those emails too. thanks, will close.
