### ISSUE TITLE
docs: explain using Cockroach with Envoy Proxy?

### ISSUE THREAD

**Issue by perezd** [cockroachdb/cockroach#27814]
**FEATURE REQUEST**

Is this something that would be supportable? Is there any documentation on how to make that work?

**Comment by nvanbenschoten** [comment]
Hi @perezd, thanks for the question. I'm not aware of anyone testing Envoy proxy yet with CockroachDB. However, I can't see any reason why it wouldn't work other than perhaps https://github.com/envoyproxy/envoy/issues/2861. Setting up Envoy Proxy with CockroachDB should be identical to setting it up with PostgreSQL from the proxy side of things. I'd encourage you to give it a try and let us know what you find!

**Comment by perezd** [comment]
I was curious if I would run into introspection issues related to mTLS, I can mess around with it!

**Comment by tim-o** [comment]
@perezd - let us know if you run into further issues, I'll close this for now.

**Comment by dio** [comment]
While you can't do L7 proxying for Postgres today, you can still use Envoy as raw TCP proxy for proxying Postgres server. If you're using TLS, you can also set SNI to route a connection to a certain cluster (via a combination of `tls_inspector` and `filter_chain_match`).

**Comment by perezd** [comment]
Would it make sense to just try cockroach as insecure and let envoy manage
TLS layer?

**Comment by a-robinson** [comment]
@perezd it depends on your threat model. Running cockroach in insecure mode doesn't just mean that inter-node communication is unencrypted -- it also means that any client can log in as root, so you have to trust everyone that is able to connect to any of the nodes.

https://www.cockroachlabs.com/docs/stable/recommended-production-settings.html#security

**Comment by perezd** [comment]
And I assume that can't be disabled independently then ?

**Comment by a-robinson** [comment]
Correct.

**Comment by a-robinson** [comment]
Indeed. See https://github.com/cockroachdb/cockroach/issues/16188 for more context if you're curious.
