### ISSUE TITLE
storage: deadlock in TestStoreRangeRebalance in multi-cpu

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#2781]
https://circleci.com/gh/cockroachdb/cockroach/8300

https://circle-artifacts.com/gh/cockroachdb/cockroach/8300/artifacts/0/tmp/circle-artifacts.BcTDxfs/test.log

**Comment by tamird** [comment]
Another one:
https://circleci.com/gh/cockroachdb/cockroach/8445
https://circle-artifacts.com/gh/cockroachdb/cockroach/8445/artifacts/0/tmp/circle-artifacts.Q7zs5ug/test.log

**Comment by tschottdorf** [comment]
blocks #1839

**Comment by tamird** [comment]
This has morphed into a "use of finalized trace". I'm going to hijack #2593 and close this issue.
