### ISSUE TITLE
sql: leak hlc error to sql client

### ISSUE THREAD

**Issue by yaojingguo** [cockroachdb/cockroach#27823]
I used `cockroach start --insecure --host localhost` to start a single local node on my laptop. Then I used `loadgen/tpcc/tpcc -load` to load data into the CockroachDB node on the same laptop. After some time, there was the following error and `loadgen/tpcc/tpcc` terminated:

```
2018/07/21 16:24:46 error in payment: pq: remote wall time is too far ahead (1.502578179s) to be trustworthy
```
At the same time, the CockroachDB node was still up and running. There is a similar closed issue #3087.

The CockroachDB version is:
```
cockroach version
Build Tag:    v2.0.4
Build Time:   2018/07/17 14:01:56
Distribution: CCL
Platform:     darwin amd64 (x86_64-apple-darwin17.7.0)
Go Version:   go1.10.3
C Compiler:   4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)
Build SHA-1:  d7c99735249c963177eadbc5fd57fc2094de6823
Build Type:   development
```

**Comment by sathyaincampus** [comment]
Is there any update for this? How do we fix this issue?

**Comment by tbg** [comment]
@sathyaincampus if this error occurs in a real cluster, it is usually accompanied by nodes shutting down due to bad clock synchronization. In that case, the solution is simple: synchronize the clocks.

If it happens in local development such as @yaojingguo reported, the issue is usually that the local NTP service abruptly changed the clock, which should be reconfigured to "smear" the updates instead.

**Comment by yaojingguo** [comment]
@tbg By saying `"smear" the updates instead`, do you mean that we need an NTP service which supports leap second smearing?

**Comment by tbg** [comment]
@yaojingguo correct. Or, for local development, disable clock synchronization.

**Comment by yaojingguo** [comment]
@tbg Since the error in my case does occur during leap second adjustment period (The time is `2018/07/21 16:24:46`), it is not caused by the lack of leap second smearing. More digging in NTP shows that NTP has two ways to adjust local clock: `step` and `slew`.  [[ntp:questions] stepping and slewing](http://lists.ntp.org/pipermail/questions/2007-May/014166.html) gives a description about `step` and `slew`:

> step == reset the clock to the correct time in _one_ instantaneous  step. A stepped clock can "move backwards".
> slew == adjust the clock by speeding it up or slowing it down. A slewed clock never "moves backwards"

And `ntpd` has an option to set the step threshold to 600s:

```
Normally, the time is slewed if the offset is less than the step threshold, which is  128
ms by default, and stepped if above the threshold.  This option sets the threshold to 600
s, which is well within the accuracy window to set the clock manually.  Note:  Since  the
slew  rate  of  typical  Unix  kernels  is limited to 0.5 ms/s, each second of adjustment
requires an amortization interval of 2000 s.  Thus, an adjustment as much as 600  s  will
take  almost  14  days  to complete.  This option can be used with the -g and -q options.
Note: The kernel time discipline is disabled with this option.
```
So if we don't want to disable clock synchronization for some reason, we can use nptd's `-x` option.
