### ISSUE TITLE
sql: dotnet core example fail w/Ngpsql 4.0.2 

### ISSUE THREAD

**Issue by ccheets** [cockroachdb/cockroach#27837]
I think I have found a bug. I have been following the tutorial of making a dotnet core application using Npgsql 4.0.2 component. Following the guide here:

[https://www.cockroachlabs.com/docs/v2.0/build-a-csharp-app-with-cockroachdb.html#step-1-create-a-net-project](https://www.cockroachlabs.com/docs/v2.0/build-a-csharp-app-with-cockroachdb.html#step-1-create-a-net-project)

When I run the first example application which creates a table, insert/updates some rows and then reads it back using the NpgsqlDataReader object, but fails.

The error I get is when we execute the reader.GetString(0) and reader.GetString(1) lines on line 45 to get the integer as a string:

> Unhandled Exception: System.InvalidCastException: Can't cast database type bigint to String
>at Npgsql.NpgsqlDefaultDataReader.GetFieldValue[T](Int32 column) in C:\projects\npgsql\src\Npgsql\NpgsqlDefaultDataReader.cs:line 153
>at Cockroach.MainClass.Simple(String connString) in /src/cockroachdb-test-app/Program.cs:line 45
>at Cockroach.MainClass.Main(String[] args) in /src/cockroachdb-test-app/Program.cs:line 16

I expected it to display the values as described in the guide. I tried using Dapper to get the data, and it worked fine (I think this is because it uses the .Fill method on the DataAdapter under the hood instead of NpgsqlDataReader).

I have attached the program example so you can see what the stack trace is for, and to get a better idea if you haven't seen the example on the CockroachDB page.

**Comment by knz** [comment]
@BramGruneir could you check and triage this thanks

**Comment by knz** [comment]
@ccheets I don't see the attachment. Can you provide it again?

**Comment by ccheets** [comment]
See attached.

**Comment by knz** [comment]
@BramGruneir I have briefly looked into this. Is it expected that one can use `GetString` to retrieve the value of an integer column? Based on a quick look at the npgsql docs it is not obvious this should work. Perhaps the example in our doc site needs to be adjusted?

**Comment by alexevon** [comment]
I have the same issue.  Just installed cockroachDB 2.1.1 and running .NET core 2.1 with the example code on:

https://www.cockroachlabs.com/docs/stable/build-a-csharp-app-with-cockroachdb.html

Cockroach itself appears fine as we imported a test mariaDB database into with with ZERO issues (great job btw!), but trying out the C# code from above results in:

cockroachdb-test-app# dotnet run
Initial balances:

Unhandled Exception: System.InvalidCastException: Can't cast database type bigint to String
   at Npgsql.NpgsqlDefaultDataReader.GetFieldValue[T](Int32 column) in C:\projects\npgsql\src\Npgsql\NpgsqlDefaultDataReader.cs:line 154
   at Cockroach.MainClass.Simple(String connString) in /root/cockroachdb-test-app/Program.cs:line 45
   at Cockroach.MainClass.Main(String[] args) in /root/cockroachdb-test-app/Program.cs:line 16


No other messages appear.

Thank you.

**Comment by alexevon** [comment]
<ItemGroup>
    <PackageReference Include="Npgsql" Version="4.0.3" />
  </ItemGroup>

**Comment by BramGruneir** [comment]
This has been moved to the docs repo and you are correct, it was the getstring issue.  

https://github.com/cockroachdb/docs/issues/4139

Closing here.
