### ISSUE TITLE
ui: without file-based logging, UI causes error log output

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#2783]
steps:
`./cockroach start --dev`
open the UI and try to view a log file
stderr logs show:
`E1006 15:54:01.402808 28157 server/status.go:470  open : no such file or directory`

**Comment by BramGruneir** [comment]
@maxlang This should be really easy to fix and a nice way to start working on some Go if you have time.  If not, I'll tackle it.

**Comment by maxlang** [comment]
Good call, I'll try it out

**Comment by cuongdo** [comment]
This doesn't seem to happen any more on master.

**Comment by petermattis** [comment]
Well, file-based logging is on by default. Did you test with it disabled (i.e. running with `--logtostderr`)?

**Comment by cuongdo** [comment]
Yes, I removed my `cockroach-data` directory then ran this:

```
cockroach start --insecure --logtostderr
```

Then, I did the following:

1. Went to admin UI
2. Clicked on "Nodes"
3. Clicked on the single node
4. Clicked on "Logs"

I didn't see any errors emitted to `stdout` or `stderr` on my Cockroach instance.

**Comment by petermattis** [comment]
Great. I apologize for questioning your testing diligence.
