### ISSUE TITLE
ts: downsampling over node restart produces strange results

### ISSUE THREAD

**Issue by couchand** [cockroachdb/cockroach#27855]
Downsampling an interval during which a node restarted produces strange results.  For instance, charting the uptime of nodes should produce sharp drops to zero, but they end up with these softly curving downward slopes.

<img width="452" alt="screen shot 2018-07-23 at 2 15 14 pm" src="https://user-images.githubusercontent.com/793969/43095156-e4d1e1da-8e82-11e8-9b27-cc5401d9beee.png">

I'm not really sure about this, if it's a "real" problem or how to define the problem exactly, but it does seem weird.

Jira issue: CRDB-4939

**Comment by tschottdorf** [comment]
@nstewart I'm not sure why you added S-3-erroneous-edge-case here. Can you elaborate?
