### ISSUE TITLE
sql: TestLogic fails in multi-cpu

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#2785]
Looks like stale descriptors.

https://circleci.com/gh/cockroachdb/cockroach/8303

https://circle-artifacts.com/gh/cockroachdb/cockroach/8303/artifacts/0/tmp/circle-artifacts.p7fpy8s/testrace.log

**Comment by tschottdorf** [comment]
There's also a data race:

==================
WARNING: DATA RACE
Read by goroutine 106:
  github.com/cockroachdb/cockroach/config.(*SystemConfig).ComputeSplitKeys()
      /go/src/github.com/cockroachdb/cockroach/config/config.go:224 +0x59
  github.com/cockroachdb/cockroach/storage.(*splitQueue).shouldQueue()
      /go/src/github.com/cockroachdb/cockroach/storage/split_queue.go:69 +0xdd
  github.com/cockroachdb/cockroach/storage.(*baseQueue).MaybeAdd()
      /go/src/github.com/cockroachdb/cockroach/storage/queue.go:201 +0x3b2
  github.com/cockroachdb/cockroach/storage.(*Store).systemGossipUpdate()
      /go/src/github.com/cockroachdb/cockroach/storage/store.go:669 +0x2a8
  github.com/cockroachdb/cockroach/storage.(*Store).(github.com/cockroachdb/cockroach/storage.systemGossipUpdate)-fm()
      /go/src/github.com/cockroachdb/cockroach/storage/store.go:548 +0x37

Previous write by goroutine 53:
  github.com/cockroachdb/cockroach/sql_test.TestLogic.func1()
      /go/src/github.com/cockroachdb/cockroach/sql/logic_test.go:514 +0x30
  runtime.call32()
      /tmp/workdir/go/src/runtime/asm_amd64.s:437 +0x3d
  testing.(*common).Fatalf()
      /tmp/workdir/go/src/testing/testing.go:379 +0x94
  github.com/cockroachdb/cockroach/sql_test.(*logicTest).execQuery()
      /go/src/github.com/cockroachdb/cockroach/sql/logic_test.go:405 +0x492
  github.com/cockroachdb/cockroach/sql_test.(*logicTest).run()
      /go/src/github.com/cockroachdb/cockroach/sql/logic_test.go:352 +0x185c
  github.com/cockroachdb/cockroach/sql_test.TestLogic()
      /go/src/github.com/cockroachdb/cockroach/sql/logic_test.go:568 +0x9eb
  testing.tRunner()
      /tmp/workdir/go/src/testing/testing.go:456 +0xdc

Goroutine 106 (running) created at:
  github.com/cockroachdb/cockroach/gossip.(*Gossip).updateSystemConfig()
      /go/src/github.com/cockroachdb/cockroach/gossip/gossip.go:366 +0x392
  github.com/cockroachdb/cockroach/gossip.(*Gossip).(github.com/cockroachdb/cockroach/gossip.updateSystemConfig)-fm()
      /go/src/github.com/cockroachdb/cockroach/gossip/gossip.go:161 +0x5f
  github.com/cockroachdb/cockroach/gossip.(*infoStore).processCallbacks.func1()
      /go/src/github.com/cockroachdb/cockroach/gossip/infostore.go:227 +0xee

Goroutine 53 (finished) created at:

**Comment by tschottdorf** [comment]
blocks #1839

**Comment by tamird** [comment]
Fixed that data race in #1839

**Comment by tamird** [comment]
Haven't seen this in a while.
