### ISSUE TITLE
log: data race in multi-cpu

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#2786]
https://circleci.com/gh/cockroachdb/cockroach/8304

https://circle-artifacts.com/gh/cockroachdb/cockroach/8304/artifacts/0/tmp/circle-artifacts.bmXCP9T/testrace.log

looks like we're logging something during test setup. logging singleton strikes again!

**Comment by tschottdorf** [comment]
blocks #1839

**Comment by tschottdorf** [comment]
yeah, this one is going to be awkward to completely avoid for those tests that manually run cobra commands while other goroutines might still be active. The update of the flag would need to lock `logging.mu` in `util/log`, but the flag is in a subpackage that isn't allowed to reach out to `log`. That leaves more awkward hacks such as having a lock on the `logflags` package which is set to `logging.mu` in `util/log`s init. Well.
