### ISSUE TITLE
engine: Limit size of merged rocksdb batches

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#27865]
When many threads are writing to rocksdb at once, a syncer goroutine [collects all their write batches](https://github.com/cockroachdb/cockroach/blob/a8588f785977575a206692c8e688bf1b7f7778d3/pkg/storage/engine/rocksdb.go#L1696) to write at once, minimizing the number of distinct disk writes. However, this can result in very large rocksdb WAL entries, and processing a rocksdb WAL entry during recovery appears to require substantially more memory than writing it the first time. A crash while a very large entry is in the uncompacted portion of the WAL can render the node unable to restart.  Empirically, we've seen a node with 8GB of ram write a 1.6GB entry to the log and be unable to play it back on restart. 

The syncer thread should monitor the size of the batches it builds and limit them to a reasonable size. 

cc @petermattis

**Comment by petermattis** [comment]
I'm a bit surprised this actually occurred in practice. I'd really love to see this super-large batch and verify it contains keys from multiple different ranges. Failing that, I'll probably make an attempt at reproducing the problem first.

**Comment by bdarnell** [comment]
Yeah, this is speculation on my part since I don't know anything about what's actually in this batch. It's  definitely true that there's no limit there now so it *could* produce a batch of unbounded size. It doesn't sound too far-fetched to me that all the node restarts could provide a forcing function that would result in more simultaneous disk writes that would hit this batching mechanism.

**Comment by petermattis** [comment]
I'm pretty sure RocksDB doesn't have a limit on the size of batches that it will merge either. Let me check that.
