### ISSUE TITLE
cli: cockroachdb user set --password not updating the password

### ISSUE THREAD

**Issue by cgebe** [cockroachdb/cockroach#27882]
**BUG REPORT**

Please describe the issue you observed:

- What did you do?

I inserted a new user in a secure cluster setup without a password first 

`cockraochdb user set test --certs-dir=/cockroach-certs --host=cockroachdb-public`. 

Then i tried to update the user with `--password` flag. However, the password was not updated and still remained empty. Therefore, i removed the user again and readded it with `--password` flag.

- What did you expect to see?

The user with empty password to be updated.

- What did you see instead?

User password remained empty.

**Comment by knz** [comment]
which version of CockroachDB are you using?

**Comment by knz** [comment]
cc @piyush-singh

**Comment by cgebe** [comment]
I am using v2. 0.4
