### ISSUE TITLE
sql: rework expression type-checking, normalization and simplification

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#2790]
Expression type-checking, normalization and simplification currently involve large ugly type switches. When a new expression type is added it is easy to miss one of these type switches. We should move this work into methods on the `Expr` interface. It will be the same amount of work to add a new expression, but the compiler will now alert you to all the functionality an expression node needs to implement.

**Comment by tamird** [comment]
Remaining work here is "simplification", which needs a bigger overhaul as tracked by #2791. Actually, I'm going to close this in favour of #2791.
