### ISSUE TITLE
sql: move lossless expr transforms from "simplification" to "normalization"

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#2791]
Expression simplification is currently used during expression analysis for index selection and can perform "lossy" transformations (e.g. `a > 1 AND a != 10` -> `a > 1`). Expression normalization is performed on all expressions and performs non-lossy transformations. Many of the simplifications are also non-lossy and the ones that create equivalent expressions should be moved into normalization (e.g. `a = 1 OR a IN (2, 3)` -> `a IN (1, 2, 3)`).

**Comment by tamird** [comment]
Note: it is also desired to change the simplification implementation to a method-oriented one, but it is not yet clear that this will be possible.

**Comment by tamird** [comment]
@knz @nvanbenschoten I think this has long since been refactored to oblivion. Confirm?

**Comment by knz** [comment]
@tamird no it has not been refactored into oblivion, I think the suggestion still applies.

**Comment by spencerkimball** [comment]
@knz is this still active? Please determine whether this is 1.0 milestone and assign / close as necessary.

**Comment by knz** [comment]
Still active, but not for v1.0

**Comment by knz** [comment]
(The suggestion is still applicable; just checked.)
Not planning on working on this any time soon. But wanting to highlight this is a potential perf gain too, once we introduce caching of query plans.

**Comment by knz** [comment]
This issue has been superseded by the optimizer project. Closing.
