### ISSUE TITLE
roachtest: don't post issues about unstable tests

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#27919]
Unstable tests are inherently, well, unstable. They don't warrant a GitHub issue when they fail.

**Comment by petermattis** [comment]
Posting issues for unstable tests was intentional. Have we found it too annoying?

**Comment by tschottdorf** [comment]
I'd also keep it, unless someone feels strongly that it's not warranted. It's already tempting to forget about unstable tests.

**Comment by petermattis** [comment]
I'm going to leave the issue posting as-is, though I might sneak in a change so that any jepsen failure is routed to @bdarnell.
