### ISSUE TITLE
sql: rework index constraint creation

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#2792]
`indexInfo.makeConstraints` is currently work complicated and subtle. We should explore whether it can be simplified. In particular, `indexConstraint` is similar `RangeCond`. It might be better to explicitly model it as a `RangeCond`, or at least change its implementation so that it is clear that the `start` and `end` expression both refer to the same variable. Open question is how to handle `IN` expressions which have no direct translation to a `RangeCond`.

**Comment by tamird** [comment]
`(*indexInfo).makeConstraints` was broken up into `(*indexInfo).makeOrConstraints` and  `(*indexInfo).makeIndexConstraints` in #5521.

The relevant method is `(*indexInfo).makeIndexConstraints`, and as originally mentioned, `indexConstraint` is quite similar to `RangeCond`, and we should look into modelling `indexConstraint` as a `RangeCond` directly.

I'm going to assign some folks that might be interested in this work.

**Comment by RaduBerinde** [comment]
#6346 already tracks rewriting a lot of this code. I've made a note to consider using `RangeCond`.
