### ISSUE TITLE
ui: boxplot to understand distribution of data

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/cockroach#27934]
**FEATURE REQUEST**

AdminUI show P99 response time as well as other median percentiles.  The P99 by nature always show outliers espically when many ad-Hoc workloads are run.   Always seeing high outlier withtout understanding the distribution can lead to incorrect interpretation of the outliers.   For this and other reasons, boxplot has been used show the distribution.  With the distribution, P99 can be placed as truly an outlier or real issue that should be addressed.  

Jira issue: CRDB-4935

**Comment by vilterp** [comment]
@mrtracy maybe we could save some other percentiles (p100, p75, p50, p25, p0) to the TS database from the histograms we have in memory? It would be more storage, but you achieved a lot of space savings recently; maybe we'd come out even.

Here's a nice box plot chart from @couchand's blog:
![](http://compiledthoughts.couchand.com/wp-content/uploads/2013/10/7-distribution.png)

Time series that look like this would be pretty sweet.

**Comment by robert-s-lee** [comment]
That graph will be helpful.  R with ggplot2 and geom_boxplot was my standard toolbox to understand the distribution in the past.

**Comment by awoods187** [comment]
In addition to boxplot, we likely want to add min, max, average, median, percentiles, etc. to adequately evaluate the shape of the data.
