### ISSUE TITLE
ui: time series charts: negative numbers not rendering as negative

### ISSUE THREAD

**Issue by vilterp** [cockroachdb/cockroach#27939]
![image](https://user-images.githubusercontent.com/7341/43230337-d37ac10e-9035-11e8-89ed-6945044d3322.png)

n6 shows a negative value, but the scale only goes down to 0.

@couchand and @mrtracy, is this a known issue?

(Seen while investigating #27906)

**Comment by piyush-singh** [comment]
Hmm @vilterp given that the time series affected - disk IOPS - shouldn't have had negative values to begin with and we do show negative values in the UI elsewhere correctly (e.g. clock offsets), are we okay to close out this issue?

**Comment by vilterp** [comment]
Yeah, there might still be something wrong here but I haven't seen it recently. Can reopen if we see it again.
