### ISSUE TITLE
sql: incorrect output to EXCEPT query with a filter

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#27969]
The following logic test fails against a distsql config. The final query returns all 3 rows, instead of just the first row.

```
statement ok
CREATE TABLE abc (
  a INT,
  b TEXT,
  c FLOAT,
  PRIMARY KEY (a, b),
  UNIQUE INDEX foo (b),
  INDEX bar (a),
  FAMILY (a, b),
  FAMILY (c)
)

statement ok
INSERT INTO abc VALUES (1, 'one', 1.1), (2, 'two', NULL), (3, 'three', NULL)

query ITR rowsort
SELECT * FROM abc
----
1 one   1.1
2 two   NULL
3 three NULL

query ITR rowsort
SELECT * FROM abc WHERE b > 'p'
----
2 two   NULL
3 three NULL


query ITR
SELECT * FROM abc EXCEPT SELECT * FROM abc WHERE b > 'p'
----
1 one   1.1
```

Explain:
```
root@127.0.0.1:61505/defaultdb> explain(verbose) SELECT * FROM abc EXCEPT SELECT * FROM abc WHERE b > 'p';
+-----------+--------+-------------+-----------+----------+
|   tree    | field  | description |  columns  | ordering |
+-----------+--------+-------------+-----------+----------+
| union     |        |             | (a, b, c) |          |
|  ├── scan |        |             | (a, b, c) |          |
|  │        | table  | abc@primary |           |          |
|  │        | spans  | ALL         |           |          |
|  └── scan |        |             | (a, b, c) |          |
|           | table  | abc@primary |           |          |
|           | spans  | ALL         |           |          |
|           | filter | b > 'p'     |           |          |
+-----------+--------+-------------+-----------+----------+
```

Here is the [generated plan](https://cockroachdb.github.io/distsqlplan/decode.html#eJyckM-L4jAUx-_7V5R3cRcC9peXwEKXHWdGEBXtYWCmh9i80UBtQpLCiPi_D20ZtMVW6vG95PP98U6QS44LdkAD9B08SAgoLVM0RupyVX-Y8S-gLgGRq8KW64RAKjUCPYEVNkOgELNthmtkHPXYBQIcLRNZJau0ODB9jNg2heRMQBb2omMs2yFQ70we8_K6vQg8i8yipk7kOx-F6wbojNSIUrqJ17PFS2cYf0iYJ2GsyFM79ptJIo9EPomCTpfgIZdgoEvY6XIRL3KpOWrkDe2kJO99uRH1lZn9Bu1SjcNm1viokDrTt__TVez8m8-BQIaf9vdPhz9_tdjtr2YgsCwsde6WnAw55RqNkrnBdtmbym7ZEPkO64sZWegUV1qmlU09LiuuWnA0tn7162GW109lwGvY64WDftjvhcMG7LXhYADst-GwF560YifnX98BAAD__-bKbOY=).

**Comment by solongordon** [comment]
Seems to boil down to distsql set operations not handling NULLs properly.
```
root@127.0.0.1:62421/defaultdb> set distsql=always;
root@127.0.0.1:62421/?> VALUES (NULL) EXCEPT VALUES (NULL);
+---------+
| column1 |
+---------+
| NULL    |
+---------+
```
At first glance this is due to distsql implementing EXCEPT using the joiners, which omit rows with NULLs from equality comparisons. We should survey other set operations and special join types to see if they have similar issues. Looks like INTERSECT is also affected, for example.
