### ISSUE TITLE
workload: executing "workload run tpcc --init" fails with "failed insert into warehouse: pq: there is no unique or exclusion constraint matching the ON CONFLICT specification"

### ISSUE THREAD

**Issue by HeikoOnnebrink** [cockroachdb/cockroach#27981]
**BUG REPORT**

Please describe the issue you observed:

- What did you do?
`./workload run tpcc "postgres://root@1.2.3.4:26257/tpcc?sslmode=verify-full&sslrootcert=/home/core/cert/ca.crt&sslcert=/home/core/cert/client.root.crt&sslkey=/home/core/cert/client.root.key" --warehouses=100 --drop --init 
`
- What did you expect to see?
init db with tpcc data

- What did you see instead?
`Error: failed insert into warehouse: pq: there is no unique or exclusion constraint matching the ON CONFLICT specification
`
problem occurred with https://edge-binaries.cockroachdb.com/cockroach/workload.LATEST from 2018/07/24.
Reverting back to older bin worked fine.
Unfortunately workload does not expose version info (suggest to add -v switch for making support easier)

**Comment by knz** [comment]
Which version of CockroachDB are you using? 

For context, the ON CONFLICT feature was changed at some point in the 2.1-alpha timeline, and I think the new `workload` facility is using the 2.1-specific change.

(This is arguably a problem in `workload` -- it should not use implicit ON CONFLICT specifications.)

**Comment by HeikoOnnebrink** [comment]
2.0.4

**Comment by nvanbenschoten** [comment]
> For context, the ON CONFLICT feature was changed at some point in the 2.1-alpha timeline, and I think the new workload facility is using the 2.1-specific change.

@knz, mind pointing me at the 2.1-specific change that introduced support for the implicit ON CONFLICT specification? I didn't realize that was new. 

In the meantime, I'll probably need to revert https://github.com/cockroachdb/cockroach/pull/27727 because there's not an easy way to use an explicit ON CONFLICT specification in workload setup.

**Comment by knz** [comment]
that would be this one: #26465
