### ISSUE TITLE
test: use `-logtostderr=NONE` when running benchmarks

### ISSUE THREAD

**Issue by asubiotto** [cockroachdb/cockroach#27993]
Log output is usually just noise when running benchmarks and messes with results (https://github.com/golang/go/issues/25241). The approach has been to use `log.Scope` to redirect log output to a directory. My understanding (cc @benesch) is that we can use `-logtostderr=NONE` as an additional flag in `make bench{short}` to disable all log output to stderr for benchmarks that do not call `log.Scope`, with the option of preserving logs with the addition of a `log.Scope` to the benchmark. This would silence all benchmarks that do not call `log.Scope`.

The main blocker is that some packages do not recognize the `-logtostderr` flag. These packages need their `main_test.go` files enhanced with a log import similarly to `pkg/util/caller/main_test.go`

**Comment by knz** [comment]
we've fixed this
