### ISSUE TITLE
importccl: provide a mode to import data generated by `cockroach dump`

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#28008]
This came up during a forum discussion: https://forum.cockroachlabs.com/t/question-about-dump-and-import/1866

the user sees the feature "IMPORT from a db dump" and sees IMPORT works with dumps from PostgreSQL and MySQL, but it is surprising it does not work with dumps from CockroachDB.

Really `IMPORT` should be taught to work with the data produced by `cockroach dump`.

**Comment by mjibson** [comment]
We think this works now. Will add a test with a cockroach-dump subdirectory or something.
