### ISSUE TITLE
sql: logic test auto-rewrite breaks EXPLAIN

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#28025]
Found by @RaduBerinde in https://github.com/cockroachdb/cockroach/pull/27970#issuecomment-408727817

> I'm not sure what was the motivation for this change, but it broke rewriting EXPLAIN statements:
```
SELECT tree, field, description FROM [
EXPLAIN (VERBOSE) SELECT a.v FROM kv a, kv b GROUP BY a.v, a.w, a.s
]
----
render      ·           ·
│           render      0
v           └──         distinct
·           ·           │
distinct    on          v,
w,          s           └──
join        ·           ·
│           type        cross
├──         scan        ·
·           │           table
kv@primary  │           spans
ALL         └──         scan
·           ·           ·
table       kv@primary  ·
```

> This is a huge problem for the `sql/opt/exec/execbuilder` tests.

**Comment by knz** [comment]
@RaduBerinde even when I revert  #27970 the specific example you gave becomes broken during a rewrite. This is because of some other change that was made to `logic.go` since that test was written, where the expected results are re-formatted with `formatValues`. 

Looking into it.

**Comment by RaduBerinde** [comment]
I just verified this test on a clean branch and it works fine by just reverting #27970..
