### ISSUE TITLE
sql: Add support for VALID UNTIL with CREATE USER

### ISSUE THREAD

**Issue by tlvenn** [cockroachdb/cockroach#28045]
Adding support of `VALID UNTIL` would open the door to dynamic secrets using Hashicorp Vault
> https://www.vaultproject.io/docs/secrets/postgresql/

This is a good security feature / practice and it would be great to add support for it.

**Comment by glerchundi** [comment]
Do you have an expected ETA for this? Specifically this issue is was a cross in an ongoing certification.

Thanks!

**Comment by asubiotto** [comment]
@RichardJCai is this finished?

**Comment by RichardJCai** [comment]
@asubiotto Yeah it's done

**Comment by asubiotto** [comment]
Great, thanks!

**Comment by glerchundi** [comment]
This is great news!! This will be available in the next release?

**Comment by RichardJCai** [comment]
> This is great news!! This will be available in the next release?

Yes this will be available in the 20.1 release
