### ISSUE TITLE
ui: rename "admin ui" to "web ui"

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#28044]
Forked from #27982.

The doc page should be renamed from `admin-ui-overview.html` to `web-ui-overview.html`. The link in the web UI to the doc page must be updated accordingly.

cc @nstewart @jseldess

**Comment by jseldess** [comment]
@Amruta-Ranade, this pairs with https://github.com/cockroachdb/docs/issues/3437.

**Comment by couchand** [comment]
I think this may be limited to docs & a handful of code comments, unless somebody can find any references I may have missed.

This might be as good a time as any to revisit the question about the window title "Cockroach Console".  We probably want that to be consistent with any titling on the login page, I would expect.  But in that context "Web UI" seems really generic and unhelpful.  Maybe we need a brand.

**Comment by knz** [comment]
`git grep -i 'admin.ui'`

```
pkg/ui/src/util/docs.ts:export const adminUIOverview = docsURL("admin-ui-overview.html");
```

**Comment by Amruta-Ranade** [comment]
@couchand Can we rename (just the window title) to "Cockroach Web UI"?

**Comment by couchand** [comment]
> Can we rename (just the window title) to "Cockroach Web UI"?

We could.  On a web browser it seems a little redundant, though, doesn't it?

**Comment by couchand** [comment]
@knz you weren't looped in but that link is going away, anyway.  But thanks for the heads up!

**Comment by Amruta-Ranade** [comment]
@couchand Yeah..but I would prefer the terms being redundant over being inconsistent. Or ... we could officially change the name to Cockroach Console (don't know its impact though).

**Comment by couchand** [comment]
> I would prefer the terms being redundant over being inconsistent.

I generally agree with you there.  In this case I don't think they're at odds (though, yes, "Console" has always been kind of out of the blue).

There's an element to names that is contextual: things can have local names that are distinct from their global names.  The global name would seem to be "CockroachDB Web UI".  In the context of "CockroachDB" things, that part is implied, so we can just call it the "Web UI".  In the context of "Web UI" things, that part is implied, so we can just call it "CockroachDB" maybe?

**Comment by Amruta-Ranade** [comment]
SGTM!

**Comment by awoods187** [comment]
cc @thtruo to close or address as needed
