### ISSUE TITLE
scripts: gceworker create gets stuck

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#28057]
gceworker create:

```
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
/usr/bin/locale: Cannot set LC_CTYPE to default locale: No such file or directory
/usr/bin/locale: Cannot set LC_ALL to default locale: No such file or directory
Configuring console-setup
-------------------------


  1. ARMSCII-8         8. ISIRI-3342    15. ISO-8859-16  22. ISO-8859-8
  2. CP1251            9. ISO-8859-1    16. ISO-8859-2   23. ISO-8859-9
  3. CP1255            10. ISO-8859-10  17. ISO-8859-3   24. KOI8-R
  4. CP1256            11. ISO-8859-11  18. ISO-8859-4   25. KOI8-U
  5. GEORGIAN-ACADEMY  12. ISO-8859-13  19. ISO-8859-5   26. TIS-620
  6. GEORGIAN-PS       13. ISO-8859-14  20. ISO-8859-6   27. UTF-8
  7. IBM1133           14. ISO-8859-15  21. ISO-8859-7   28. VISCII

Encoding to use on the console: 27 <- I entered this and pressed enter
<hangs>
```

I had to kill the process, restart the node (to release various locks) and ran the bootstrap script again from an interactive ssh session. That worked. This is probably something about not having a proper terminal in the previous run?

**Comment by benesch** [comment]
Yeah, were you doing this from a screen/tmux session on your host or something? This might be a bug in `gcloud`.

**Comment by benesch** [comment]
Can you try to reproduce with `GCEWORKER_NAME=tschottdorf-garbage-worker scripts/gceworker.sh create`?

**Comment by tschottdorf** [comment]
That's exactly what I ran.

**Comment by benesch** [comment]
Ok, I can repro by running 

```
LC_CTYPE=UTF-8 GCEWORKER_NAME=garbage scripts/gceworker.sh create
```

I don't think `UTF-8` is a valid locale. I'm loathe to fix this, as mucking with locales in gceworker.sh is bound to make problems worse for other folks. It seems like it could be a problem with iTerm2: https://gitlab.com/gnachman/iterm2/issues/5478.

**Comment by tschottdorf** [comment]
Thanks a bunch! I now have the correct one in my bashrc. Leaving it to you to close this.

**Comment by benesch** [comment]
🙌 glad we sorted it!
