### ISSUE TITLE
allow omitting port in --addr, --gossip

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#2805]
for example,
`./cockroach start [...] --addr=node1`
`./cockroach start [...] --gossip=node1,node2,node3`

both currently don't work:

> unable to resolve RPC address "macts.local": missing port in address macts.local

should be pretty easy to fix in `./gossip/resolver/resolver.go#NewResolver`.

**Comment by YuleiXiao** [comment]
use default port?

**Comment by tschottdorf** [comment]
Yes, we want to use port 26257 by default. You could do that in `context.InitNode`. My comment about the resolvers was about the `--gossip` flag.

**Comment by YuleiXiao** [comment]
@tschottdorf hi, what is the addressType "lb" mean?

**Comment by tschottdorf** [comment]
Hey Yulei, that's for 'load balancer'. If I remember correctly, it does the
same thing as tcp but the resolver does not get exhausted.
