### ISSUE TITLE
sql: refactor the ORM tests to anchor them to cockroachdb development

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#28069]
The examples-orms job that gets run in CI is extremely flaky. There are several problems:
  1. Its dependencies aren't vendored, so it's hitting public package repositories on every build.
  1. It's not pinned to a particular SHA. The latest master of examples-orms is always used. This can make builds of cockroach that were fine one minute start failing the next.
  1. Its tests aren't correct. There is at least one missing transaction retry loop, probably more.

We should probably just merge examples-orms into this repository.

Jira issue: CRDB-4929

**Comment by awoods187** [comment]
CC @BramGruneir and @knz I think we need to do some work on this in the current milestone. I spoke with @benesch and he said that we could make large progress with a day's worth of work or do everything needed with a week. I say let's not let perfect be the enemy of good and do the day's worth of work here to get ORM testing in place. The last thing we want is to break what ORM functioning we do have in place

**Comment by jlinder** [comment]
@rafiss I've seen you doing some work with examples orms. Is this something that's still interesting? Perhaps it's better on the AppDev board?

**Comment by rafiss** [comment]
Yeah this should be in our board. It looks like points 1 and 2 in the initial description of this issue already have been created as separate issues, independently: https://github.com/cockroachdb/cockroach/issues/42083 and https://github.com/cockroachdb/cockroach/issues/52342

**Comment by jlinder** [comment]
Great. Then we'll close this issue.
