### ISSUE TITLE
test that (*roachpb.Transaction).Update() handles all fields

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#2807]
this method is prone to code rot. A simple way of preventing this is a test that does the following:

* create a test transaction (which is fixed and without zero values)
* use reflection to go over that transaction's fields, erroring when one is the zero value (so that the test fails when a new field is added)
* update a zero transaction with that transaction above
* run the same reflection-based check for the outcome.

**Comment by lizhongz** [comment]
Hi tschottdorf, I would like to work on this.

**Comment by tschottdorf** [comment]
Cool. All yours!

**Comment by lizhongz** [comment]
This issue can be closed. The pull requet #2843 for this issue has been merged.
