### ISSUE TITLE
Rancher 2.0 - CSR approved, but no certificate in response. Waiting some more

### ISSUE THREAD

**Issue by wzrdtales** [cockroachdb/cockroach#28075]
It seems like something is missing in the kubernetes cluster created by rancher 2.0.
Everything works fine except the CSR approval, which ends up with an infinity loop of `CSR approved, but no certificate in response. Waiting some more`.

**Comment by wzrdtales** [comment]
Turns out it needs to be indeed configured first. Here is the issue telling how
https://github.com/rancher/rancher/issues/14041

**Comment by happyyangyuan** [comment]
Could you pease describe how you solved this issue with more details?  Thank you very much.

**Comment by wzrdtales** [comment]
Look at the issue over there, follow the instructions in this link
https://github.com/JasonvanBrackel/metrics-server-on-rancher-2.0.2

Add this to the config

```
    "kubeController": { 
        "type": "/v3/schemas/kubeControllerService",
        "extraArgs": {
        "cluster-signing-cert-file": "/etc/kubernetes/ssl/kube-ca.pem",
        "cluster-signing-key-file": "/etc/kubernetes/ssl/kube-ca-key.pem"
        }
    },
```

**Comment by happyyangyuan** [comment]
The official description
[Enable kubenertes controller manager's default certs signer](https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/#a-note-to-cluster-administrators)

**Comment by smilelikeshit** [comment]
@happyyangyuan thanks solved
