### ISSUE TITLE
refactor TestRangeNoGossipConfig

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#2808]
This test is basically ok, but we should refactor it to use the
`testCases := []struct{some fields}{ {...}, {...} }` form we use elsewhere.

**Comment by lizhongz** [comment]
Hi tschottdorf, I would like to refactor this.
I had a look at the TestRangeNoGossipConfig function. I am kind of confused with the three test cases:
1. A put request and a header with nil Txn (does it mean not creating a new transaction?)
2. An end transaction request and a header with non nil Txn
3. A get request and a header with the same Txn (But the transaction is committed at step 2.)

I was thinking that the procedure should be
1. Put request creating a transaction 
2. Get request
3. end transaction

**Comment by tschottdorf** [comment]
Hi @lizhongz, great! I think the test is simply broken (the index used in `hs` is off by one, we should be sending the `Put` and the `EndTransaction` with `Txn` and the `Get` without).
