### ISSUE TITLE
sql: support dates BC

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#28099]
Currently, CockroachDB has no support for dates with negative years, or BC dates. However, it does permit inputting negative dates via the binary pgwire protocol, which can lead to some issues down the line.

Specifically, our date formatting code will format a BC date by prepending a negative sign to the year. This output date is then unreadable by the parser, leading to an un-roundtrippable datum, which is not permitted.

This needs to be corrected, by either teaching the date parser about negative years, or teaching the date parser about BC dates and teaching the date formatter to output BC when appropriate.

@knz for triage.

**Comment by knz** [comment]
probably to be bundled with #27500

**Comment by jordanlewis** [comment]
Hmm... unfortunate.

**Comment by jordanlewis** [comment]
In that case, this is already broken. I think running `SELECT (-999999)::DATE FROM t` where `t` is some table will throw an error on master.

**Comment by jordanlewis** [comment]
@mjibson ping

**Comment by mjibson** [comment]
Fixed by #36938

**Comment by jordanlewis** [comment]
Nice!
