### ISSUE TITLE
server: collect jemalloc heap profiles

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#28096]
We already collect heap profiles of the Go heap when it becomes large (#26222). Recently we've seen cases where the allocations were on the C side, and consequently we're interested in doing something similar with the jemalloc-maintained heap.

There's a primer here: https://github.com/jemalloc/jemalloc/wiki/Use-Case%3A-Heap-Profiling

Like in #26222, these dumps will be worth a lot more when they're included in `debug zip`.

**Comment by knz** [comment]
This has been achieved, jemalloc profiles are saved when requested, and a summary is printed out in `memstats...txt`.
