### ISSUE TITLE
qa: control statements

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#28138]
This qa work can qa session cancellation and re-QA query cancellation

The following statements gain the ability to operate on multiple entries at once:

CANCEL SESSIONS
CANCEL QUERIES
CANCEL JOBS
RESUME JOBS
PAUSE JOBS

**Comment by nstewart** [comment]
@vivekmenezes can you share an update here?

**Comment by vivekmenezes** [comment]
I brought up a cluster and while restore was restoring it I paused and resumed restore. Works well.
I've used cancel job to cancel schema changes.

This functionality works well. I'm declaring it ready for GA
