### ISSUE TITLE
qa: Policies for controlling leaseholder location

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#28146]

**Comment by vivekmenezes** [comment]
@jordanlewis moving this to the current milestone since you're on QA rotation this week.

**Comment by vivekmenezes** [comment]
@jordanlewis have you done any work on this issue? You can unassign yourself if you can't get to it.

**Comment by jordanlewis** [comment]
No, I haven't. I also missed the last time you pinged me on it for some reason - sorry about that. I don't think I can reasonably get to this any time soon.
