### ISSUE TITLE
qa: finalize upgrade automatically

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#28142]

**Comment by vivekmenezes** [comment]
@dt reminder to QA this item soon

**Comment by nstewart** [comment]
Ping on QA @dt

**Comment by dt** [comment]
I ran though this twice last month, once with the default behavior, though we hadn't yet tagged a 2.1 version at that time, and then once with the preserve setting and no upgrade. I don't remember how much I messed with the preserve case though. I'm OOO for next two weeks though so I likely won't revisit it further before 2.1.

**Comment by vivekmenezes** [comment]
@dt I'm comfortable with us closing this.
