### ISSUE TITLE
qa: ALTER COLUMN TYPE

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#28141]
Note this feature is only implemented for simple ALTER COLUMN TYPE that do not require rewriting the underlying column data.

**Comment by BramGruneir** [comment]
@vivekmenezes Can you point me to the PR or Issue that this feature references?

**Comment by vivekmenezes** [comment]
https://github.com/cockroachdb/cockroach/issues/5950 is the issue. Thanks!

https://github.com/cockroachdb/cockroach/pull/25819 should also be tested. Thanks!

**Comment by vivekmenezes** [comment]
@BramGruneir reminder to QA this item soon.

**Comment by nstewart** [comment]
Ping re: QA -- any update here?

**Comment by BramGruneir** [comment]
Bah, I never got back after the ping.  I did some testing of this and found no issues, but it was on a small set of data.  Planning to do a bit more testing this week on a much larger data set before I close this out.

**Comment by BramGruneir** [comment]
So I've loaded up TPCC into a 3 node cluster and played around with a bunch of trivial and creating/dropping computed columnness changes.

All of them were successful.

I did notice one problem, and it's entirely around messaging.
`alter table stock alter column blah drop stored;` worked on repeated events calls.  Even after the computed column's stored was already dropped.

```sql
root@localhost:26257/tpcc> alter table stock alter column blah drop stored;
ALTER TABLE

Time: 114.998252ms


root@localhost:26257/tpcc> alter table stock alter column blah drop stored;
ALTER TABLE

Time: 114.998252ms
```

Same with:
```sql
alter table stock alter column s_dist_01 type STRING(41);
ALTER TABLE

Time: 112.799158ms

alter table stock alter column s_dist_01 type STRING(41);
ALTER TABLE

Time: 112.799158ms
```

This is minor, but I'm not sure if these should all return without error.  Perhaps we should follow what postgres does.  
Not sure about the computed column dropping of `stored`.  It seems strange to be able to drop it more than once.

**Comment by BramGruneir** [comment]
Sending this back to @bobvawter.

**Comment by vivekmenezes** [comment]
@bobvawter can you create a separate issue for what was uncovered here and close this issue. Thanks!

**Comment by bobvawter** [comment]
Opened #32275.  It's a trivial fix, will get a patch out shortly.

**Comment by bobvawter** [comment]
FWIW, PostgreSQL allows those repeated, no-op `alter type` commands to succeed.
