### ISSUE TITLE
ui: normalize CPU% time series in hardware dashboard to 0-100%

### ISSUE THREAD

**Issue by vilterp** [cockroachdb/cockroach#28154]
### Repro

- Set up a cluster with nodes with > 1 CPU
- Run some load so that you're using multiple cores
- Go to Hardware timeseries dashboard

### Expected

- See a number in the CPU % time series between 0 and 100%

### Actual

- See a number between 0 and `num cores * 100`

### Fix

Divide the CPU percentage by the number of cores. Not sure whether to do this at metric recording time (a new time series?) or query time.

**Comment by vilterp** [comment]
cc @Amruta-Ranade for docs changes.

**Comment by vilterp** [comment]
@ben was pretty strongly in favor of this, and I think I've come around to his viewpoint. Percentages should be 1-100%. Sadly inconsistent with `top`/`htop`/`Activity Monitor`, but consistent with GCP and AWS dashboards.

It will be tricky to show a cluster-wide version of this though, since we'd have to take the number of cores each node has into account while aggregating their values.

**Comment by nstewart** [comment]
@vilterp can you fix it here too? 
![image](https://user-images.githubusercontent.com/894257/43542913-5455b66a-959c-11e8-8a36-84b1f16934c2.png)

**Comment by vilterp** [comment]
Two criteria off the top of my head:
- percentages should be between 1-100 (even though OS tools break this rule)
- resource utilization metrics should be actionable — i.e. if the percentage maxes out at 100 and you're getting close to 100, you need more CPUs. If it doesn't max out at 100, you don't know where the actual max is
