### ISSUE TITLE
qa: IMPORT MYSQLDUMP

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#28157]

**Comment by vivekmenezes** [comment]
reminder to QA this item soon.

**Comment by nstewart** [comment]
ping re: eng QA cc @rolandcrosby

**Comment by knz** [comment]
I am assigned to this issue although I find that Roland's testing far surpasses what I would have been able to do until now :)

I am willing to reserve some time to do more testing myself. Is that still useful?

**Comment by knz** [comment]
mysql and its docs are a junkyard. This QA is very difficult.

![schermafdruk_2019-01-31_17-53-31](https://user-images.githubusercontent.com/642886/52070441-239cd380-2581-11e9-830d-996f4f76099b.png)

**Comment by knz** [comment]
![schermafdruk_2019-01-31_18-02-56](https://user-images.githubusercontent.com/642886/52071037-732fcf00-2582-11e9-85bd-84372de36484.png)
