### ISSUE TITLE
sql: Unique Constraint Violation not Communicated to Driver

### ISSUE THREAD

**Issue by Mohammed90** [cockroachdb/cockroach#28150]
**BUG REPORT**

Please describe the issue you observed, and any steps we can take to reproduce it:

When a table with unique constraint on a column has non-data inserted, the driver doesn't receive the error `integrity_constraint_violation`. This has only been tested with Go's [lib/pq driver](https://github.com/lib/pq). 

- Which version of CockroachDB are you using?

The latest Docker image, which I believe is v2.0.4.

- What did you do?

Run the code at: https://github.com/keratin/authn-server/issues/59#issuecomment-408933444 , reproduced here:
```go
package main

import (
	"database/sql"
	"log"

	"github.com/lib/pq"
)

const (
	CREATE_TABLE_KEY = "create_table"
	INSERT_USER_KEY  = "insert_user"
)

func main() {

	sqlOps := map[string]string{
		CREATE_TABLE_KEY: `
		CREATE TABLE IF NOT EXISTS myTable (
			id SERIAL PRIMARY KEY,
			username TEXT UNIQUE DEFAULT NULL
		)`,
		INSERT_USER_KEY: `INSERT INTO myTable (username) VALUES ($1) RETURNING id`,
	}

	roachDB, roachDBOpenErr := sql.Open("postgres", "postgres://postgres@127.0.0.1:26257/postgres?sslmode=disable")
	if roachDBOpenErr != nil {
		log.Fatalf("roachDB: Couldn't open db: %s", roachDBOpenErr)
	}
	defer func() {
		err := roachDB.Close()
		if err != nil {
			log.Printf("roachDB close err is not nil: %s", err)
		}
	}()

	_, roachExecErr := roachDB.Exec(sqlOps[CREATE_TABLE_KEY])
	if roachExecErr != nil {
		log.Printf("roachExecErr is not nil: %s", roachExecErr)
		return
	}

	// insert first user
	{
		roachRows, roachQRowErr := roachDB.Query(sqlOps[INSERT_USER_KEY], "the_user")
		if roachQRowErr != nil {
			log.Printf("roachQRowErr is not nil: %s", roachQRowErr)
			return
		}
		if !roachRows.Next() {
			log.Printf("roachRows has no next on first insert")
			return
		}

		var firstRoachID int
		roachRows.Scan(&firstRoachID)

		log.Printf("First insert has ID: %d", firstRoachID)
		roachRows.Close()
	}

	// insert second user; expecting error
	{
		roachRows, roachQRowErr := roachDB.Query(sqlOps[INSERT_USER_KEY], "the_user")
		if roachQRowErr != nil {
			log.Printf("roachQRowErr is not nil: %s", roachQRowErr)
			if err, ok := roachQRowErr.(*pq.Error); ok {
				log.Printf("The error name is: %s", err.Code.Class().Name())
			}
			return
		}
		errVal := roachRows.Err()
		if errVal != nil {
			log.Printf("errVal is not nil: %s\n", errVal)
			if err, ok := errVal.(*pq.Error); ok {
				log.Printf("The error name is: %s\n", err.Code.Class().Name())
			}
			return
		}

		if !roachRows.Next() {
			log.Printf("roachRows has no next on second insert")
			return
		}

		var secondRoachID int
		roachRows.Scan(&secondRoachID)

		log.Printf("Second insert has ID: %d", secondRoachID)

		roachRows.Close()
	}

}
```

- What did you expect to see?

The error logging line `errVal is not nil: (...)` is printed along with `The error name is: integrity_constraint_violation`. For the record, using the SQL shell, gives the following message:
`pq: duplicate key value (username)=('the_user') violates unique constraint "mytable_username_key"`

FWIW, PostgreSQL returns an error, as expected.

- What did you see instead?

New IDs generated and returned on both inserts, despite the second one not actually writing data to the table. The table has only 1 record with the ID `369947267340369921`, but the code above prints the following complete output:
```
2018/07/30 19:49:06 First insert has ID: 369947267340369921
2018/07/30 19:49:06 Second insert has ID: 369947267353280513
```
- What was the impact?
Loss of data integrity and resulting in erroneous behavior up at the application level because it received a success message when an error is expected.

**Comment by knz** [comment]
Thanks for your report!

We are aware of this issue; you are encountering a combination of

1) an oddity/bug in `lib/pq` and
2) a bug in CockroachDB that was corrected in version 2.1.

The oddity in `lib/pq` is that CockroachDB *does* report an error for your 2nd insert, but `lib/pq` fails to see it. (As you have found already, CockroachDB indeed detects the constraint error properly, as can be seen `cockroach sql`.)

In order to force `lib/pq` to see the error you have to finish "consuming" `roachRows` with the `Next()` method **until it returns false**. It is not sufficient to call `Next()` just once like you do in your program.  So you can try the following:

```go
   if !roachRows.Next() {
			log.Printf("roachRows has no next on second insert")
			return
   }
   // ...scan secondRoachID...
   for !roachRows.Next() {}
```

The bug in CockroachDB is that really the constraint error should be reported straight away to the client, not after returning some (invalid) initial results. This bug was corrected in the 2.1 development branch but the changes for this are too significant to back-port to 2.0.x. 

I hope this helps. Please let us know if you have more questions or comments.

**Comment by knz** [comment]
(And when you finish consuming `roachRows.Next()` you need to check `roachRows.Err()` *afterwards*).

**Comment by Mohammed90** [comment]
When you say 
> an oddity/bug in lib/pq

do you mean it's something I should report it to them? I found this https://github.com/lib/pq/issues/633 issue. Is this the particular one you're referencing?

**Comment by knz** [comment]
yes that's the one

**Comment by knz** [comment]
I am going to close this issue since we have done the work to fix it. If you have any further request or comment, please let us know.
