### ISSUE TITLE
sql: support INSERT ... ON CONFLICT ON CONSTRAINT

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#28161]
Postgres [supports](https://www.postgresql.org/docs/9.5/static/sql-insert.html) an extension of `INSERT ... ON CONFLICT` where a constraint name is given instead of a set of columns.

We currently don't support this, but we should:
https://github.com/cockroachdb/cockroach/blob/07d85bd1eef62a78d5be2ac9e7574db88c88e35c/pkg/sql/parser/sql.y#L4808

This would have been a solution for #27981 if we supported it.

cc. @knz for triage. Perhaps @emsal1863 would be interested in working on this?

**Comment by knz** [comment]
maybe we should track by reporting the feature as unsupported to our reg server, so we get some PM feedback. may look into this.
