### ISSUE TITLE
sql: logic tests do not suitably exercise distsql infra

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#28184]
So @arjunravinarayan and I were talking about this while reviewing  #28143.

Even with the upcoming merge of execution engines, many of our tests just use `SELECT ...` without a FROM clause, which means that **there will not be any flow planned for them in distsql**.

So really all our scalar tests with just a `SELECT` clause and no FROM are merely testing the interface sql/pgwire/client, and not the distsql flow encoding (and evaluating scalar expressions on distsql processors).

This is sad because we have a wealth of scalar tests and this limitation mean we never really exercised the distsql code paths with them.

Unsure what the solution really is if we want to force flows. Perhaps a special session var for the phy planner to always add an extra layer of flow?

**Comment by knz** [comment]
cc @arjunravinarayan @jordanlewis

**Comment by jordanlewis** [comment]
Once the merge is finished this won't be an issue.

**Comment by knz** [comment]
Are you sure? As Arjun found out even if there's a distsql plan this does not imply there will be a flow set up for select statements without FROM.

**Comment by jordanlewis** [comment]
Yeah I'm sure. With DistSQL merged, everything will get encoded into a flow (at least for the time being until we make that part more performant..)
