### ISSUE TITLE
sql: `replace` on long strings can cause OOM - needs accounting

### ISSUE THREAD

**Issue by vladimirschuka** [cockroachdb/cockroach#28206]
I ran CockroachDB then created a DB and table
`my_first_table (id,txt text,timestamp default now())`
then generated data
`insert into my_first_table values (1,'text ')`
then

`insert into  my_first_table select id + max(id),text||id||text from my_first_table;`

after 32000 rows I had a whatever error that I think related to ,text||id||text
and then I did queries like this:
`insert into  my_first_table select id + (select max(id) from my_first_table),text||id from my_first_table limit 28000;`
and got a state where 
```
testdb=> select count(*) from my_first_table;
 4163768
(1 row)
```
txt field contains values like :
`text 1text 1text 1text 12text 1text 1text 1text 124text 1text 1text 1text 12text 1text 1text 1text 1248text 1text 1text 1text 12text 1text 1text 1text 124text 1text 1text 1text 12text 1text 1text 1text 124816`

some of them is a little bit long

```
[testdb=> select length(txt),count(*) from my_first_table group by 1 order by length  desc limit 10;
 length | count 

 215325 |     1
 117021 |     1
 108829 |     2
 107805 |     2
 107665 |   128
 107661 |     8
 107660 |    20
  59677 |     2
  58653 |     2
  58513 |   128
(10 rows)
```
and when I tried to do an update query:
`update my_first_table set txt=replace(txt,' ','');`

DB crashed with error : Killed

before I noticed that my RAM was filled fully and then Swap was filled in. 
size of *.sst in data directory 869 MB
```
./cockroach start --insecure --host localhost --max-sql-memory=10GiB --cache=1GiB
CockroachDB node starting at 2018-08-02 15:06:59.648341024 +0000 UTC (took 96.7s)
build:               CCL v2.0.4 @ 2018/07/16 20:25:32 (go1.10)
admin:               http://localhost:8080
sql:                 postgresql://root@localhost:26257?sslmode=disable
logs:                .../cockroach-v2.0.4.linux-amd64/cockroach-data/logs
temp dir:            .../cockroach-v2.0.4.linux-amd64/cockroach-data/cockroach-temp032231047
external I/O path: .../cockroach-v2.0.4.linux-amd64/cockroach-data/extern
store[0]:            path=.../cockroach-v2.0.4.linux-amd64/cockroach-data
status:              restarted pre-existing node
clusterID:           86c008e6-0c75-473b-b55e-92128ea9d8c2
nodeID:              1
```
I have 16Gb Ram 16Gb Swap 
CPU i7-3630QM
 Or maybe I do something wrong?

**Comment by knz** [comment]
Your database ran out of memory while running `replace`. 

The problem is that it crashes instead of reporting an error "not enough memory". We'll fix that.

In any case, CockroachDB will not be able to process very long strings in that way.

**Comment by knz** [comment]
cc @justinj 

1) there's accounting in `replace` but not in the right place: it should be checked *before* the call to `Replace` not afterwards.

2) maybe we have other limitations in the KV/SQL interface.

**Comment by knz** [comment]
@vladimirschuka in any case, thank you for your report! that's useful.
