### ISSUE TITLE
ui: databases page: friendly CTA when there are no tables

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/cockroach#28234]
![image](https://user-images.githubusercontent.com/894257/43637088-ea73b8e0-96e1-11e8-8286-d39825d7e0f2.png)

We need something other than this @josueeee @piyush-singh -- this can't be the first impression for new hosted customers. 

Not sure what schedules look like, but maybe a friendly CTA on creating a table or something? Or maybe collapse this? I'll defer to this team

**Comment by josueeee** [comment]
@vilterp The empty state page design can be found here: https://www.figma.com/file/NEacS7ODqlLMTIQE1VgSpHCs/04_Database?node-id=121%3A1
