### ISSUE TITLE
cli: Debug zip should include "report" endpoints

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#28245]
The debug zip includes a lot of raw data, but it doesn't have any of our higher-level analysis like the problem ranges report (specifically, I'm trying to find the ranges that are reported as underreplicated). We should include a copy of the problem ranges report in the debug zip (and/or provide a way to perform the same analysis on the debug data).

**Comment by bdarnell** [comment]
Edited to expand to all of the debug-page "reports" (specifically including the network latency report for my current debugging effort).

**Comment by petermattis** [comment]
The network latency report is generated from the `NodeStatus.Activity[nodeID].Latency` info. This is already available in the debug zip under `node/<ID>/status`. Not nearly as usable as the pretty table, but it is there.
