### ISSUE TITLE
backup: provide ability to schedule backup jobs

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#28266]
Backup is the kind of thing that needs to run regularly. We should investigate providing built-in support for scheduling regular backup (full or incremental).

Some things to take into account:
- how to specify scheduled times (ie: cron-like rules)
- how to specify which tables/databases to backup
- how to persist target storage (careful about credentials)
- monitoring of scheduled backup jobs (ie: custom names for each schedule, exported metrics with timestamps and last job status, custom name as a label)

**Comment by tim-o** [comment]
+1 from an enterprise account

**Comment by mwang1026** [comment]
- Execution of the schedule
- Error handling 
- Creation of schedule
- Updates to history file
- Monitoring / alerting
- Managing the backup full and incremental paths
- Debug pages
- Status pages
- Controls for the schedule (pause, resume)

**Comment by mwang1026** [comment]
https://github.com/cockroachdb/cockroach/issues/51846
https://github.com/cockroachdb/cockroach/issues/51847
https://github.com/cockroachdb/cockroach/issues/51850
