### ISSUE TITLE
Heavy inserts cause database to drop connections

### ISSUE THREAD

**Issue by clanstyles** [cockroachdb/cockroach#28272]
**BUG REPORT**

Please describe the issue you observed, and any steps we can take to reproduce it:

- Which version of CockroachDB are you using? ***2.0.0***

- What did you do? ***Insert a lot of data in a loop***

- What did you expect to see? ***No crash***

- What did you see instead? 
```
pq: Could not complete operation in a failed transaction
pq: initial connection heartbeat failed: rpc error: code = Unavailable desc = all SubConns are in TransientFailure

pq: rpc error: code = Unavailable desc = node waiting for init; /cockroach.sql.distsqlrun.DistSQL/SetupFlow not available
```
- What was the impact?
Database dropped connections to service and service timed out.

We have a 5 node cluster with the following specs. We're seeing desyncs at around 200 queries per second. We have a bunch of data we've tried to insert in. We do check if they exist and a few other queries. Are there better specs for doing this? We noticed if we do these in a transaction, it helps stop the crashing a lot.

 ```
We're only doing about 200 queries.
     Requests:
      cpu:      7
      memory:   8G
That's the request limits on Kubernetes
```

**Comment by jordanlewis** [comment]
Thanks @clanstyles for the report. Were any of the nodes failing during your tests? If possible, could you send us the file output by `cockroach debug zip` in your cluster? It can contain sensitive info, feel free to email it to me if that's better for you - my email is jordan@cockroachlabs.com.

Thanks!

**Comment by tschottdorf** [comment]
@clanstyles, do you have additional input here as requested by jordan? We won't be able to assist knowing only what we know so far.
