### ISSUE TITLE
Improve readability of logs w/r/t liveness

### ISSUE THREAD

**Issue by tim-o** [cockroachdb/cockroach#28282]
**FEATURE REQUEST**

Please describe the feature you are requesting, as well as your proposed use case.

We frequently see customer issues where nodes are unable to join a cluster due to slow heartbeats and liveness failures. For instance, [here](https://github.com/cockroachdb/cockroach/issues/28179) and [here](https://forum.cockroachlabs.com/t/node-has-connected-to-cluster-via-gossip-but-unable-to-contact-the-other-nodes/1813/10). The log errors frequently follow this pattern:

```
W180802 03:24:56.251840 343 storage/node_liveness.go:501  [n17,hb] slow heartbeat took 4.5s
W180802 03:24:56.251860 343 storage/node_liveness.go:438  [n17,hb] failed node liveness heartbeat: context deadline exceeded
W180802 03:24:56.395373 344 sql/jobs/registry.go:300  canceling all jobs due to liveness failure
```
Rinse, repeat.

The challenge is that it's difficult to determine _why_ liveness failed, in part because we don't know which node holds the liveness lease, and there's no easy way to get that information from the UI (apart from stepping through range by range and hoping to hit it early).

@benesch and I were discussing, and one possible solution here would be to just include the node we're attempting to contact in the error message, something like `[n17,hb,nX]` where X is the (supposed) leaseholder. That would help us narrow down whether there's a network partition, and narrow the search to nX to see if there's something funky going on there (i.e.: it's bogged down with writes, in a separate DC, whatever).

**Comment by tschottdorf** [comment]
My approach to this had been to try to log a trace on failed liveness. This isn't as useful today because we haven't worked towards making [traces for cancelled operations useful](https://github.com/cockroachdb/cockroach/issues/26882), but maybe it would already help for the case of liveness.

**Comment by tim-o** [comment]
A trace would be a great solution if we can solve that problem. Would it be easier to implement a means of identifying the node holding the lease as a first step? that could at least trigger the user to trace independently, or help an operator understand which node / network connection might be the source of the issue.
