### ISSUE TITLE
importccl: add telemetry for import size volume

### ISSUE THREAD

**Issue by rolandcrosby** [cockroachdb/cockroach#28349]
When importing data in bulk we should capture some telemetry on what the volume of the import was. Count of rows imported, size of file imported, and count of CSV files imported should get us the data we want. David suggested that we could quickly implement this by adding new feature hit counters for different buckets of data sizes (e.g. imported 10 rows, imported 100 rows, imported 1000 rows).

**Comment by dt** [comment]
@rolandcrosby Can you update this with specific bucket thresholds we're interested in?

**Comment by rolandcrosby** [comment]
Since we can't do multi-dimensional metrics let's send the following metrics for each import:

* Import type:
  * `import.type.csv`
  * `import.type.pgdump`
  * `import.type.mysqldump`
* Import size (rows):
  * `import.row_count.1`
  * `import.row_count.10`
  * `import.row_count.100`
  * `import.row_count.1000`
  * `import.row_count.10000`
  * `import.row_count.100000`
  * `import.row_count.1000000`
* Import file size:
  * `import.file_size.1kb`
  * `import.file_size.1mb`
  * `import.file_size.10mb`
  * `import.file_size.100mb`
  * `import.file_size.1gb`
* Import file count:
  * `import.file_count.1`
  * `import.file_count.10`
  * `import.file_count.100`
  * `import.file_count.1000`

**Comment by dt** [comment]
28726
