### ISSUE TITLE
ui: show how how many times serializable isolation prevented write skew

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/cockroach#28343]
**FEATURE REQUEST**

serializable isolation is a defining feature of CockroachDB.  showing how many times serializable isolation (SI) prevented incorrect SQL execution could help quantify the value of SI.  otherwise, a choice of serializable vs snapshot or any other isolation becomes an academic discussion.  

CockroachDB tracks the number of time serializable kicked in via `txn.autoretries` and `txn.restarts.serializable`.  These metrics can be viewed with customized chart.  Having customer easily see the metrics, count it, and associate value of SI would be important in adoption of CockroachDB.  

Having these charts as a standard UI chart with description of serializable, explanation of importance would be beneficial even for experienced DBA and developers, and architects.   

There was discussion with @bdarnell on whether `txn.autoretries` is included in `txn.restarts.serializable`.

**Comment by vilterp** [comment]
I have no idea how to capture this metric; paging @nvanbenschoten and @tschottdorf.

**Comment by robert-s-lee** [comment]
Sorry for the confusion, but these two metrics are already in TimeSeries.  We need to UI page design for the two metrics.

**Comment by bdarnell** [comment]
The txn.restarts.serializable is already there, I just didn't know where to look for it. It's on the distributed tab, as "forwarded timestamp (serializable)" on the "KV transaction restarts" chart.
