### ISSUE TITLE
TestRaftRemoveRace: panic: [group 1] applied(54) is out of range [prevApplied(0), committed(0)]

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#2837]
Discovered in #1839.

> panic: [group 1] applied(54) is out of range [prevApplied(0), committed(0)]

https://circleci.com/gh/cockroachdb/cockroach/8440
https://circle-artifacts.com/gh/cockroachdb/cockroach/8440/artifacts/0/tmp/circle-artifacts.HHAR97f/test.log

**Comment by bdarnell** [comment]
Fixed by #2868
