### ISSUE TITLE
ui: document each metrics on UI page

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/cockroach#28379]
Follow up from https://github.com/cockroachdb/cockroach/issues/28377 

@piyush-singh  consistency checker does not have the information icon that provides a context of how to interpret this metric.  Any thought on providing context based on this and other related issues to provide general guidance.  

@jess-edwards Any thoughts on how to structure document of these metrics one by one organically.  This will be important to enable self-service diagnostics and scale the adoption.

**Comment by jess-edwards** [comment]
@jseldess I think this one's for you.

**Comment by jseldess** [comment]
Thanks, @jess-edwards. @Amruta-Ranade is really the right person here. 

Our current [admin UI docs](https://www.cockroachlabs.com/docs/stable/admin-ui-overview.html) claim:

> The Admin UI also provides details about the way data is Distributed, the state of specific Queues, and metrics for Slow Queries, but these details are largely internal and intended for use by CockroachDB developers.

If this isn't accurate anymore, and users do need to look at these dashboards, we should both add tooltips and add explicit pages. @Amruta-Ranade, @robert-s-lee, thoughts?

**Comment by Amruta-Ranade** [comment]
I agree. If users need to look at these dashboards, we should add tooltips and docs for them. Will take this up next week (post-Docs 2.1 week), if that's okay.

**Comment by robert-s-lee** [comment]
CockroachDB customers tend to be sophisticated.  Performance, Scalability, Troubleshooting can be aided by understanding how to interpret these metrics.  Post doc 2.1 would be good to re-visit and determine the next steps.

**Comment by Amruta-Ranade** [comment]
Definitely. I am working on a similar project - will put something on the calendar to discuss the next steps.
