### ISSUE TITLE
Performance test the merged execution engine & cost-based OPT

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#28378]
Let's performance test the new opt and merged execution engines to understand differential and minimize performance regressions. Here is a list of things we can test and associated goals

*Merged execution engine testing*
- [x] Test merged execution engine against a simple kv workload to determine what if any performance overhead is present (goal less than 10% degradation) 
- [x] Test merged execution engine against customer workloads (goal to achieve parity with 2.0)
- [x] Test merged execution engine against SQL 20 (goal to achieve parity with 2.0)
- [x] Test merged execution engine against TPC-C (goal to achieve parity with 2.0)

*Opt testing*
- [x] Test Opt against a simple kv workload to determine what if any performance overhead is present (goal less than 10% degradation) 
- [x] Test Opt against customer workloads (goal to achieve parity with 2.0)
- [x] Test Opt against SQL 20 (goal to achieve parity with 2.0)
- [x] Test Opt against TPC-C (goal to achieve parity with 2.0)

*Combined testing*
- [x] Test combined merged execution engine + Opt against a simple kv workload to determine what if any performance overhead is present (goal less than 10% degradation) 
- [x] Test combined merged execution engine + Opt against customer workloads (goal to achieve parity with 2.0)
- [x] Test combined merged execution engine + Opt against SQL 20 (goal to achieve parity with 2.0)
- [x] Test combined merged execution engine + Opt against TPC-C (goal to achieve parity with 2.0)

**Comment by petermattis** [comment]
> Test merged execution engine against TPC-C (goal to achieve parity with 2.0)

@nvanbenschoten and the core perf folks have made a variety of improvements since 2.0 that have benefited TPC-C performance. Is the intention here that we might lose all of these gains? I'm wondering if the bar ("parity with 2.0") is being set appropriately. Perhaps I'm misinterpreting what "parity with 2.0" means.

**Comment by awoods187** [comment]
We don't currently know if the opt and execution engine changes will eat the other performance wins for tpc-c--hence the need to test. We know that they are bad in the kv tests but want to confirm that users don't experience a regression overall in spite of our other wins. Hopefully, this fear is not well founded. 

Perhaps we can also add a tpc-c test comparison for 2.1 with opt & exec on and off as well once we confirm the above.

**Comment by jordanlewis** [comment]
> We know that they are bad in the kv tests

Just to be clear, there's a cap on the "bad"ness here - it's something like a 10% degradation.

We don't expect to see any significant performance losses versus TPCC on master. Performance degradations only occur for extremely short queries that do almost no work at execution time - that's when the very small amount of extra work that we do in opt and always-distribute show up as more than just noise.

**Comment by petermattis** [comment]
I completely agree on the need to test, though my instinct is to set the bar higher for tpc-c: parity with 2.1 using the heuristic planner and non-merged execution engine. I thought we did know that the new optimizer did not eat all of the performance improvements (i.e. we've tested tpc-c with the new optimizer and the performance diff was in the noise). 

To be clear, setting a goal here is done to allow an easy go ahead. If we don't meet the criteria we'd have to look more closely at the performance diff and determine if it is acceptable or if there is a way to mitigate (e.g. only use the merged execution engine for queries that require it).

**Comment by awoods187** [comment]
@jordanlewis isn't that 10% on exec and 10% on opt for ~20% total?

@petermattis we did confirm just the opt achieved ~parity with tpc-c 2.0. We haven't done something similar with the execution engine yet. 

I also agree with setting the ultimate kpi of TPC-C parity with 2.1 using the heuristic planner and non-merged execution engine.

**Comment by andy-kimball** [comment]
Yes, we should be more precise with the goals. I think everyone agrees that
a "Must Have" goal is TPCC parity with 2.0 (we'd choose not to ship new
functionality or even slip our date if this was in jeopardy). And TPCC
parity with the 2.1 heuristic planner + non-merged exec engine should be at
least a "Should Have" goal (we'd feel badly about not hitting this, and
would need to make some hard decisions if we can't get there). It sounds
like whether that gets elevated to "Must Have" is not fully agreed on yet.

I'd like to have our ship criteria laid out and agreed upon as soon as
possible, to minimize the chance that previously unknown criteria gets
added at the last minute and causes contention and fire drills.

**Comment by jordanlewis** [comment]
> @jordanlewis isn't that 10% on exec and 10% on opt for ~20% total?

No. It's ~10% total. We'll have more precise numbers soon, though.

**Comment by jordanlewis** [comment]
I think losing TPCC parity between 2.1-opt-merge and 2.1-heuristic-split shouldn't be a Must Have, although it's important to remember that failing this goal would directly harm another team's goal - the core performance team has OKRs related to total TPCC scalability.

The reason for this is that not having parity with 2.1 wouldn't indicate that we're eating *all* of the performance gains that were made by core, like Peter implied. I think eating some small amount of those gains would be unfortunate but not the end of the world.

That being said, I would still be pretty surprised to see a slip here. We still need to do the measurements, but the kv workload that gives double digit percent slips is the very worst case for planning, which affects both the optimizer and the merged execution engine. The kv workload is nothing like TPCC, whose scalability is limited much more by contention and things in core than planning overhead.

**Comment by andy-kimball** [comment]
The more I think about performance, the higher the priority I put on adding
a query cache. We have to be able to separate compile-time perf from
execution-time perf in our thinking and our measurements. SQL Server has a
sophisticated query cache, and will actually rewrite queries to make it
more likely they'll hit the cache. For example:

SELECT a, b, c FROM t WHERE a=10


would be re-written to something like:

SELECT a, b, c FROM t WHERE a=$1


so that future queries where only the constant has been changed will be
able to reuse the plan.

Ultimately, all of distributed execution planning should be subsumed into
the optimizer. At that point, we'd be free to spend increasing amounts of
time looking for the best plan, since planning time would be amortized away
in nearly every common workload.

**Comment by awoods187** [comment]
Spoke with @nvanbenschoten and he doesn't think YCSB performance is likely to be hit given that contention is the main bottleneck there even though this is a similar workload

**Comment by awoods187** [comment]
Closing this work now that we have tested and understand our performance
