### ISSUE TITLE
backupccl: TestBackupRestoreWithConcurrentWrites fails on replay txn

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#28389]
```
make stressrace PKG='./pkg/ccl/backupccl' TESTS=TestBackupRestoreWithConcurrentWrites

--- FAIL: TestBackupRestoreWithConcurrentWrites (64.34s)
	sql_runner.go:41: error executing 'RESTORE data.* FROM $1': pq: importing 10 ranges: split at key /Table/54/1/3 failed: replay txn
FAIL


ERROR: exit status 1

169 runs completed, 1 failures, over 9m37s
```

"replay txn" I believe means that a `BeginTransaction` request was reordered with the `EndTransaction`. The fact that the client gets this error means that it was still waiting for the `BeginTransaction`'s results - which is weird: if it's still waiting for the begin, why did it send an end?

@danhhz want this?

**Comment by danhhz** [comment]
I'm off backup/restore these days. @mjibson is your man

**Comment by andreimatei** [comment]
Nvm, this is #28231
