### ISSUE TITLE
storage: long time waiting for replication in TestCluster

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#28395]
I can make `TestCluster.WaitForFullReplication` replication take over 20s. Here's a dummy test that reproduces it in about a minute with:
```
make stress PKG='./pkg/ccl/backupccl' TESTS=TestXXX TESTTIMEOUT=20s STRESSFLAGS='-p 1'
```
I don't know what's going on but it doesn't sound good.
I've began looking at this because I've noticed individual ccl tests sometimes taking a long time.

```
+func TestXXX(t *testing.T) {
+       defer leaktest.AfterTest(t)()
+
+       dir, dirCleanupFn := testutils.TempDir(t)
+       var params base.TestClusterArgs
+       params.ServerArgs.ExternalIODir = dir
+       params.ServerArgs.UseDatabase = "data"
+
+       tc := testcluster.StartTestCluster(t, multiNode, params)
+       cleanup := func() {
+               tempDirs := []string{dir}
+               for _, s := range tc.Servers {
+                       for _, e := range s.Engines() {
+                               tempDirs = append(tempDirs, e.GetAuxiliaryDir())
+                       }
+               }
+               tc.Stopper().Stop(context.TODO()) // cleans up in memory storage's auxiliary dirs
+               dirCleanupFn()                    // cleans up dir, which is the nodelocal:// storage
+
+               for _, temp := range tempDirs {
+                       testutils.SucceedsSoon(t, func() error {
+                               items, err := ioutil.ReadDir(temp)
+                               if err != nil && !os.IsNotExist(err) {
+                                       t.Fatal(err)
+                               }
+                               for _, leftover := range items {
+                                       return errors.Errorf("found %q remaining in %s", leftover.Name(), temp)
+                               }
+                               return nil
+                       })
+               }
+       }
+       cleanup()
+}
```

cc @tschottdorf so he's aware, and @benesch cause he likes to look at test failures

**Comment by andreimatei** [comment]
Done some digging and learned some things.
It would appear that the story is that sometimes, soon after the `TestCluster` is started, the replication queue gets the following error for (all?) ranges:
```
[replicate,n1,s1,r9/1:/Table/1{2-3}] range requires a replication change, but lacks a quorum of live replicas (0/1)
```
The 0/1 seems to mean that (someone thinks that) the node that has the replica is not alive. This seems funky but I hear can be a result of gossip delay; I don't know what it means exactly.
After this error, the range is neither put in purgatory, nor re-enqueued. So, it needs to wait for the scanner to come around to it again. And the scanner gets back to it much later. This "much later" has been introduced in #27441 (cc @spencerkimball) which changed the scanner policy, slowing it down at least for cluster with few ranges.

Now what to do about it? I guess that even if we understand and fix that bizarre `0/1` error, upreplication in the cluster's beginning could probably still fail because the other nodes are not necessarily alive yet.
An idea is for the `TestCluster` to get a hook for manually triggering a full scan when all nodes are known to be alive. There already exists an `Store.ForceReplicationScanAndProcess()`. Or maybe we just switch the `TestCluster's` timings; @petermattis presciently suggested that maybe the `TestCluster` needs another policy in #27697.

My heart hopes that that PR is also the cause of our recent-ish `had <x> ranges at startup, expected 22` flakiness plague (e.g. #28320, #28323) - maybe there's split failures combined with split queue slowness. In fact, I vaguely remember @knz lamenting about one of these failures a while ago and saying that he suspects one of Spencer's change - was it #27441 that you suspected, Rafa?
On a tangent, maybe the split failures always existed or maybe they've been exacerbated by the scenario covered in #28270.

cc @alex @bdarnell

**Comment by spencerkimball** [comment]
Try putting the range into purgatory instead? Should be added there anyway I would imagine. Ranges out to get tickled out of purgatory if licenses changes.

**Comment by benesch** [comment]
I also reintroduced a knob recently to control the min and max idle times.
Setting the max idle time to something nice and short in tests might also
help.

**Comment by a-robinson** [comment]
Putting the range into purgatory for such errors looks like it's worth a shot for fixing this flake. It won't help with the split flake, though, so you'll still want to play around with the max idle time knob for that.

**Comment by petermattis** [comment]
Something weird is going on with the scanner and purgatory. We can work around that badness and make `TestCluster.WaitForFullReplication` reliably take less than a second my setting `ScanMaxIdleTime` to 10ms, but I'd like to get to the bottom of the weirdness. I see replicas being added to purgatory, and then purgatory is drained when the 3rd node comes up. But somehow not every replica was added to purgatory and the remaining replicas are scanned very slowly. I'll figure this out the remainder later this week.

Also, this appears to be a different problem than #28746 (the `had X ranges at startup, expected 22` failures). That error occurs even with a 10ms `ScanMaxIdleTime`.

**Comment by andreimatei** [comment]
I've definitely seen that the error I quoted above about `lacks a quorum of live replicas` is not a `purgatoryError`, and thus in those cases, the respective replica is *not* added to the purgatory.
I haven't looked at the logic for what makes an error a `purgatoryError` yet.

**Comment by benesch** [comment]
A purgatoryError is any error that implements purgatoryErrorMarker(). There
are very few such errors.

**Comment by petermattis** [comment]
Yep. I made a new `quorumError` that provides `purgatoryErrorMarker`. Seems to completely fix the problem here. See #28877.
