### ISSUE TITLE
sql: automate the detection of features not yet implemented in CockroachDB

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#28400]
Adding a feature that parses the errored queries in postgres to determine if it’s a missing feature or just an error on the user side.  This could be dynamic and automated.  This would be an M sized project that doesn't necessarily need to sync up with our release cycle.

Jira issue: CRDB-4909

**Comment by jordanlewis** [comment]
This is more or less done at this point with all of the work we've done in this area to help automate missing builtins and virtual tables.
