### ISSUE TITLE
storage: "coreos/etcd/raft" will be moved to "etcd-io/etcd/raft"

### ISSUE THREAD

**Issue by gyuho** [cockroachdb/cockroach#28402]
Hello,

Just here to get this communicated clearly: `github.com/coreos/etcd/raft` will be transferred to `github.com/etcd-io/etcd/raft`, on 5PM (California timezone), Monday, August 27, 2018.

ref. https://github.com/coreos/etcd/issues/9965

(Please feel free to close this! Thanks!)

/cc @bdarnell

**Comment by bdarnell** [comment]
Thanks for the update. We have all our dependencies checked in to a repo so we won't be immediately effected by the change, but we'll need to adjust the next time we update this dependency.

**Comment by tschottdorf** [comment]
Done.
