### ISSUE TITLE
ui: split up embedded.go?

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#2841]
`ui/embedded.go` is now 11MB, the bulk of which is either fonts or third-party dependencies, which change rarely. Our javascript and css are tiny and changes quickly in comparison. This is suboptimal for git: the entire file is downloaded whenever any piece of it changes. It will eventually be compressed away by `git gc`, and clones should use the packed format as well, so it's not awful in the long run, but in general git will store and transmit lots of copies of large files that have changed. It would be nice to split embedded.go up into at least two pieces.

**Comment by maxlang** [comment]
@mrtracy potentially worth looking at as part of what you're doing

**Comment by mrtracy** [comment]
I'll look into it.

**Comment by tamird** [comment]
This may be relatively easy to do with jspm bundles. http://jspm.io/docs/production-workflows.html

**Comment by spencerkimball** [comment]
@bdarnell let's fix this if we're running into problems with it. The `embedded.go` file is currently 10M so doesn't seem like we are. I'm closing this, but please re-open, and change milestone from 1.0 if you disagree.
