### ISSUE TITLE
negative and positive numbers have separate node_statement_statistics fingerprint

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/cockroach#28418]
- Which version of CockroachDB are you using?

v2.1.0-alpha.20180730 

- What did you do?

```
create table t1 (id int primary key, balance int);
insert into t1 values (1,1);
insert into t1 values (2,-1);
```

- What did you expect to see?

metric showing INSERT INTO t1 VALUES (_, _)  was executed twice

- What did you see instead?

Negative value is tracked as  a separate statement.

```
root@:26257/test> select key from crdb_internal.node_statement_statistics where key like 'INSERT INTO t1%';
+-------------------------------+
|              key              |
+-------------------------------+
| INSERT INTO t1 VALUES (_, -_) |
| INSERT INTO t1 VALUES (_, _)  |
+-------------------------------+
```
- What was the impact?

What additional insight can be gleaned from seeing the negative number as a separate fingerprint?

**Comment by vilterp** [comment]
Looks like we need to add a case here to handle `UnaryOp`s (what the `-` is): https://github.com/cockroachdb/cockroach/blob/246afb6a0243f54620ce16fdfc5917ffdd05f514/pkg/sql/sem/tree/hide_constants.go#L30-L45

@knz would we just say "if the unary op is on a constant, just format the unary op as a `_`"? If the unary op is on something other than a plain constant (e.g. a function call), I assume we'd want to capture that in the fingerprint.

**Comment by vilterp** [comment]
I'm pretty sure we wouldn't want to collapse any of those four examples you gave into the same fingerprint; we'd just want to collapse statements where there's a number that can either be negative or not. So, I think we can do it before type checking and constant folding.

**Comment by robert-s-lee** [comment]
Agree that those four example shold be different fingerprint.  I was thinking can separating negative numbers be a feature?  thinking through customer use cases I encountered, one extreme was 8,000 columns of numbers.  with singleton and multirow inserts as two common insert methods,  what can we glean by tracking negative numbers and what resources are consumed to track? is there performance difference because of negative number parsing as a rational for tracking it separatey? 

create table t2 (id int primary key, id1 int, id2 int, id3 int, id4 int)  

- singleton results in expected numbers of fields^2 entries

insert into t2 values (1,0,0,0,-1); insert into t2 values (2,0,0,-1,0); insert into t2 values (3,0,0,-1,-1); insert into t2 values (4,0,-1,0,0); insert into t2 values (5,0,-1,0,-1); insert into t2 values (6,0,-1,-1,0); insert into t2 values (7,0,-1,-1,-1);

select key from crdb_internal.node_statement_statistics;                                                             
| INSERT INTO t2 VALUES (_, _, _, -_, _)                                   |
| INSERT INTO t2 VALUES (_, _, _, -_, -_)                                  |
| INSERT INTO t2 VALUES (_, _, _, _, -_)                                   |
| INSERT INTO t2 VALUES (_, _, -_, _, _)                                   |
| INSERT INTO t2 VALUES (_, _, -_, _, -_)                                  |
| INSERT INTO t2 VALUES (_, _, -_, -_, _)                                  |
| INSERT INTO t2 VALUES (_, _, -_, -_, -_)

- multirow results in two fingerprints

insert into t2 values (1,0,0,0,-1),(2,0,0,-1,0),(3,0,0,-1,-1),(4,0,-1,0,0),(5,0,-1,0,-1),(6,0,-1,-1,0),(7,0,-1,-1,-1);

select key from crdb_internal.node_statement_statistics;                                                             
| INSERT INTO t2 VALUES (_, _, _, _, -_), (__more6__)                      |
| INSERT INTO t2 VALUES (_, _, _, _, -_), (__more6__)                      |

the multirow does not track every single variations.  
the singeton does.

If we want to keep negative constants as separate fingerprints, understanding where this information could be helpful and be documented as such.   The potential resource consumption could be high.

**Comment by knz** [comment]
@vilterp the solution here is not yet one more special case during pretty printing. I'll think about it, I may have a solution.

**Comment by tschottdorf** [comment]
Isn't it shady to track the signs like that? Depending on the workload, this can leak sensitive information. For example, for a bank, it's conceivable that reporting would tell us the number of deposits and withdrawals. (Reporting the anonymized query itself could also leak that type of information already, so I'm not sure where to draw the line - but certainly something to consider before we go that direction).

**Comment by knz** [comment]
Tobias indeed an argument could have been made that it is "shady" to keep the sign visible in scrubbed stats.  After this PR however, this will not occur any more (the point of this PR is specifically to remove this behavior).

**Comment by knz** [comment]
This PR: #28520
