### ISSUE TITLE
sql: allow aggregate functions to handle multiple non-constant expressions

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#28417]
When #28392 is merged, it will improve aggregate functions to take secondary arguments, but only constants expressions.  

Ideally, they should be able to take any number of actual expressions.

The aggregate functions for statistics is a great example of ones that take more than one non-constant expression:
https://www.postgresql.org/docs/current/static/functions-aggregate.html#FUNCTIONS-AGGREGATE-STATISTICS-TABLE

**Comment by jordanlewis** [comment]
@RaduBerinde moving to planning.

**Comment by RaduBerinde** [comment]
This is done (e.g. #44628 this PR added support for `corr`).
