### ISSUE TITLE
metrics: txn duration metric is broken

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#28424]
I noticed this while doing some performance profiling - a histogram was causing a ton of Sprintfs via Error.Errorf. I dug in and found out that the `Durations` histogram that's part of `TxnMetrics` always gets updated with a preposterously large number, which gets capped at 10 seconds. I'm not sure why this happens, probably the `txnStartNanos` is set to 0 or something.

Here's a screenshot of the UI which agrees with my finding:

![image](https://user-images.githubusercontent.com/43821/43939420-02752d42-9c38-11e8-85b9-00e86b750c9b.png)

**Comment by andreimatei** [comment]
see https://github.com/cockroachdb/cockroach/issues/30208#issuecomment-422184574

**Comment by tschottdorf** [comment]
@andreimatei I'm seeing commits referencing this, but no PR (but I think I remember that the PR for the references above has merged). Is this issue still open?

**Comment by andreimatei** [comment]
This was fixed by #30448, but silly github doesn't close it cause the PR message didn't reference it.
