### ISSUE TITLE
pq: there is no unique or exclusion constraint matching the ON CONFLICT specification

### ISSUE THREAD

**Issue by cgebe** [cockroachdb/cockroach#28459]
Is this a bug report or a feature request?

bug

**BUG REPORT**

Please describe the issue you observed, and any steps we can take to reproduce it:

- Which version of CockroachDB are you using?

v2.0.4

- What did you do?

`INSERT INTO products (id, price, description, timestamp) VALUES ($1, $2, $3, $4) ON CONFLICT DO NOTHING`

- What did you expect to see?

Query going through without specifying the unique constraint

- What did you see instead?

`pq: there is no unique or exclusion constraint matching the ON CONFLICT specification`

- What was the impact?

Adding the unique constraint

`INSERT INTO products (id, price, description, timestamp) VALUES ($1, $2, $3, $4) ON CONFLICT (id) DO NOTHING`

Either the doc or the functionality is deviant: https://www.cockroachlabs.com/docs/stable/insert.html#on-conflict-clause

According to https://www.postgresql.org/docs/9.5/static/sql-insert.html the docs are slightly wrong, however executing the query without constraint on postgresql does not throw the error

**Comment by knz** [comment]
@cgebe thank you for your interest in CockroachDB!

We have addressed this limitation in the upcoming CockroachDB 2.1. release. Would be interested to get your feedback on the alpha release.
