### ISSUE TITLE
Multiraft deadlock on circleci

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#285]
https://circleci.com/gh/tschottdorf/cockroach/282

Observed by @tschottdorf

**Comment by tschottdorf** [comment]
one more, maybe the same: https://circleci.com/gh/cockroachdb/cockroach/369

**Comment by tschottdorf** [comment]
are we even logging enough to get the info we need from raft? We might want to bump up the log level in those tests.

**Comment by bdarnell** [comment]
I have some theories about what's going on here but we'll need another stack trace after #286 was merged to be sure. I still haven't been able to reproduce it locally; I'm going to work on a test that more systematically covers different orders of events.

**Comment by bdarnell** [comment]
Another one: https://circleci.com/gh/cockroachdb/cockroach/381

This one is happening in a different test so it might not be the same, but it looks similar. This run includes the expanded log output and I think I've identified the cause.

**Comment by tschottdorf** [comment]
cool!
possible related: https://circleci.com/gh/cockroachdb/cockroach/383 from your PR #293

**Comment by tschottdorf** [comment]
Another one:
https://circleci.com/gh/cockroachdb/cockroach/386

**Comment by tschottdorf** [comment]
Possibly another candidate:
https://circleci.com/gh/tschottdorf/cockroach/301

Would be quite happy to see all of them just vanish with your #295!

**Comment by bdarnell** [comment]
OK, #295 is merged; let's see if this happens again.

**Comment by bdarnell** [comment]
Marking this closed since it hasn't recurred.
