### ISSUE TITLE
sql: Interleaved tables should never leave orphaned child rows

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#28537]
From the RFC on interleaved tables:
> It is frequently desirable to enforce that there is never a row in an interleaved table without a corresponding row in the parent table. This can be done with a table-level foreign key constaint, but a shorthand will also be created: INTERLEAVE IN PARENT customers ON DELETE CASCADE|RESTRICT. ON DELETE CASCADE will delete interleaved rows if a parent is deleted. ON DELETE RESTRICT will allow removal of parent rows with no interleaved rows, but will error if interleaved rows would be orphaned. A missing ON DELETE clause will fall back to table-level (or no) constraints.

The fact that his is not a requirement is extremely troublesome and causes the complexity of handling interleaved tables to have a larger surface space in which orphans (an interleaved table entry without a parent table) need to be considered. Now that ON DELETE CASCADE and ON UPDATE CASCADE are available, we should remove the ability to create an interleaved table with a ON DELETE NO ACTION. Furthermore, it should be impossible to have an interleaved table without a foreign key constraint relying on the parent table.

* Require that all interleaved child tables have a foreign key constraint on the parent table's primary index.
* Require that these constraints both ON DELETE and ON UPDATE can only be RESTRICT or CASCADE
* Consider adding an automatic ON DELETE CASCADE, ON UPDATE CASCADE constraint for all new interleaved tables without an explicit foreign key constraint declaration.

All that being said, we need to ensure that we don't break how clusters where this may already exist behave. So a migration path will have to be provided.

**Comment by BramGruneir** [comment]
cc @vivekmenezes

**Comment by BramGruneir** [comment]
cc @awoods187

**Comment by vivekmenezes** [comment]
@BramGruneir I spoke to @jordanlewis about this. I think we should fix the orphaned children problem first before we tackle the other issue of ensuring that an FK relationship exists. I'd be supportive of a change that prevents a user from creating a database where the children have no parent. This doesn't have to fix the backwards compatibility issue of ensuring that existing data doesn't have orphaned children.

**Comment by BramGruneir** [comment]
@vivekmenezes I'm not advicating doing this all at once. But I think it's the direction we should move toward.  

@bdarnell Can you elaborate on your specific use case a bit?  How is having a dummy parent table useful?

**Comment by bdarnell** [comment]
Interleaving into a dummy table is useful to get 1PC inserts into a table with secondary indexes. Without interleaving, 1PC inserts are only possible as long as the entire table+index fits within a single range. If you have a table and indexes that share a common prefix (for example, a `photos` table with PK `(user_id, photo_id)`, and an index `(user_id, timestamp)`), you can interleave them into a dummy table with PK `user_id` and get 1PC inserts for each *user* whose data fits within a single range. 

Of course, if you had a `user` record you'd just store it in that top-level table and then you'd never have orphaned rows. But it's not unusual for user management to happen somewhere else and leave you with nothing to store in the top level table.

**Comment by BramGruneir** [comment]
What about just having a top level table with only one column, the 'user_id' as PK?
Wouldn't that satisfy the same constraint?  Sure it requires an extra write when inserting, but it should be a 1pc.

I really do like the idea of `INTERLEAVE INTO NOTHING` as a final replacement for this, but I think that would take a lot of work.

**Comment by bdarnell** [comment]
The top level table must have columns in order to interleave into it. When I said it was empty, I meant "no rows", not "no columns". 

Writing a dummy row would work, but it's annoying to make sure it always gets written when it's needed. From a user perspective, I'd much rather not have the "no orphaned child rows" restriction. You say that the existence of orphaned child rows complicates the implementation. That might have been a reason to impose this restriction in the beginning, but now that orphaned rows exist we'd have a long way to go before we could remove all the backwards-compatibility code and reach a net simplification. (I don't quite understand what the complications are here)

**Comment by jordanlewis** [comment]
Closing as wontfix.
