### ISSUE TITLE
crdb misreports available storage when running in docker on mac

### ISSUE THREAD

**Issue by tim-o** [cockroachdb/cockroach#28541]
**BUG REPORT**

Please describe the issue you observed, and any steps we can take to reproduce it:

- Which version of CockroachDB are you using?
2.0.4
- What did you do?
Following these instructions, created a one node cluster and connected to the admin UI: https://www.cockroachlabs.com/docs/stable/start-a-local-cluster-in-docker.html

- What did you expect to see?
~150GB of free space, like I see when I execute CRDB from outside Docker
<img width="565" alt="screen shot 2018-08-13 at 4 58 14 pm" src="https://user-images.githubusercontent.com/38867162/44057843-5037dcb6-9f1a-11e8-8c1f-83289d056eb7.png">

- What did you see instead?
150TB:
<img width="550" alt="screen shot 2018-08-13 at 4 57 16 pm" src="https://user-images.githubusercontent.com/38867162/44057882-714895a8-9f1a-11e8-94b7-ac888215b084.png">

- What was the impact?
None, though it could lead to confusion for users (see https://forum.cockroachlabs.com/t/admin-ui-shows-the-capacity-of-the-node-wrongly/1914/4)

**Comment by a-robinson** [comment]
To be clear, this is almost certainly only an issue on Docker-for-Mac, not Docker in general. Running inside Docker for Mac is very different from running directly on a Mac or running in Docker on Linux.

**Comment by tim-o** [comment]
Fair point!
