### ISSUE TITLE
ui: iops does not match iostat

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/cockroach#28552]
**BUG REPORT**

Please describe the issue you observed, and any steps we can take to reproduce it:

using Rand to perform 100% upsert, 3 nodes, 

`roachprod run $f -- 'PATH=~/:$PATH; rand --batch 10 test factors'`

- Which version of CockroachDB are you using?

roachprod run $f -- 'wget -qO- https://binaries.cockroachdb.com/cockroach-v2.1.0-alpha.20180730.linux-amd64.tgz | tar  xvz; cp cockroach-v2.1.0-alpha.20180730.linux-amd64/cockroach ./'

- What did you do?

- What did you expect to see?

```
$ iostat -x 5
Linux 4.10.0-35-generic (robert-vungle-0001) 	08/13/2018 	_x86_64_	(4 CPU)

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          41.02    0.02    3.65    3.63    0.00   51.68

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     6.95    1.21    2.49    38.19   222.45   140.90     0.02    5.66    1.06    7.89   0.52   0.19
sdb               0.00  1289.61    0.05 1272.74     0.89 77700.41   122.10     0.30    0.24    0.17    0.24   0.17  22.24

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          86.25    0.00    6.70    3.32    0.00    3.73

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     0.00    0.00    0.20     0.00     1.60    16.00     0.00    0.00    0.00    0.00   0.00   0.00
sdb               0.00  1875.40    0.00 1995.20     0.00 114416.80   114.69     1.29    0.64    0.00    0.64   0.21  42.56

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          79.07    0.00    7.16    7.97    0.00    5.80

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     2.00    0.00    4.00     0.00    24.00    12.00     0.00    0.00    0.00    0.00   0.00   0.00
sdb               0.00  2447.20    0.00 2679.40     0.00 47460.00    35.43     0.61    0.23    0.00    0.23   0.18  47.76
```
- What did you see instead?

<img width="1280" alt="screen shot 2018-08-13 at 7 02 08 pm" src="https://user-images.githubusercontent.com/6315124/44062729-a5bf0db0-9f2b-11e8-9faa-d66475b6648f.png">

- What was the impact?

IOPS on the hardware table is misleading

**Comment by vilterp** [comment]
The "Disk IOPS in Progress" graph shows the number of ops that are "in flight" when the sample is taken. Sounds like you're expecting to see read and write ops per second. This is gathered, but not currently graphed; I'll add it. Also, these should all have tooltips explaining what they mean.
