### ISSUE TITLE
sql: panic: interface conversion: types.T is types.tUnknown, not types.TArray

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#28561]
`SELECT information_schema._pg_expandarray(NULL)`

Found with RSG.

**Comment by knz** [comment]
@BramGruneir can you have a look?

**Comment by mjibson** [comment]
I looked into this a bit and it's beyond my familiarity because it touches opt land. I added

```
				if args[0].ResolvedType() == types.Unknown {
					return types.Unknown
				}
```

to the return typer of the builtin and the test then failed because the optimizer was attempting to convert the tUnknown to a TTuple. I gave up at this point because I think someone who knows about sql and opt could fix this way faster than me.

**Comment by BramGruneir** [comment]
Interesting, I'll take a look during bugfix time milestone.
