### ISSUE TITLE
sql: IMPORT pretty-print error

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#28562]
cannot parse output of Format: sql="

```
SELECT ISERROR ( EXISTS ( ( ( ( WITH BETWEEN AS ( CREATE ROLE error ) , BIT ( ident ) AS ( IMPORT TABLE OUT . SIMILAR FROM ident ( ident ) ) SELECT error ) ) ) ORDER BY INDEX POSITION . ident @ ident ASC OFFSET SERIAL4 'string' ROW ) )
```

", formattedSQL="

```
SELECT ISERROR(EXISTS ((((WITH "between" AS (CREATE ROLE 'error') , "bit" (ident) AS (IMPORT "out".similar FROM IDENT ('ident')) SELECT error))) ORDER BY INDEX "position".ident@ident ASC OFFSET SERIAL4 'string'))

```
": syntax error at or near "."

Above is the error message produced by RSG. This might be a problem with the formatting of ISERROR? sqlfmt doesn't handle that, so it could be the culprit?

**Comment by knz** [comment]
No the problem here is the pretty-printing of IMPORT. It's not outputting the TABLE keyword, which is necessary in this case.

I can still have a look though.
