### ISSUE TITLE
cli/sql: allow the user to change the table formatter in-flight

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#28572]
Suggested by @asubiotto on https://github.com/cockroachdb/cockroach/pull/28490#pullrequestreview-145790768

The idea is that if a large number of rows is being buffered with the `table` formatter, a prompt would ask for the user to confirm whether they want to wait with the current formatter, or instead continue with a different formatter.

**Comment by piyush-singh** [comment]
Discussed w/ @knz: we currently already enable changing the display format, what we're missing is enabling a user to take this action while a long standing query is running, this becomes available when we start supporting query cancellation in the client (this is a separate issue)

There is no further work beyond the other feature, so no need to keep this issue open.
