### ISSUE TITLE
build: CONTRIBUTING.md instructions don't work for `make build`

### ISSUE THREAD

**Issue by rolandcrosby** [cockroachdb/cockroach#28593]
I tried to follow the instructions in CONTRIBUTING.md to build the latest master branch (bf3e90d) on my Mac, but running `make build` in a fresh checkout of the cockroach repo didn't work. Make output is [here][build.log], generated by running `make --debug build 2>&1 | tee build.log`.

I was able to get Cockroach to build successfully after making a fresh checkout and manually running `git submodule update --init --recursive` before running `make build`, but I'm not sure why I had to do that. From the Make output, it looks like the `bin/.submodules-initialized` Make target was hit at some point anyway. Maybe there's some other target that needs submodules to be initialized, but that doesn't declare that dependency?

[build.log]: https://github.com/cockroachdb/cockroach/files/2288724/build.log

**Comment by benesch** [comment]
Thanks for catching this, @rolandcrosby!
