### ISSUE TITLE
kv: add support for "put-if-not-older-than" or "put-at-timestamp" operation

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#2860]
In order to support non-transaction backfill of index entries we need a KV operation which can either put a key-value pair at a historical timestamp or put the key-value pair if the desired timestamp is before the most recently written timestamp. See the [online schema change](https://github.com/cockroachdb/cockroach/pull/2842) PR for some discussion.

We'll also need to support "naked delete tombstones". Currently, when perform a delete operation we only write a tombstone when the value previously existed. We would need to adjust this to always add a tombstone so that concurrent delete from the index being backfilled is not lost if the backfill hasn't reached that key yet.

**Comment by petermattis** [comment]
@spencerkimball also says "a means to augment the write path through leader replicas such that
they do not affect the read time stamp cache". Not exactly sure what that was in reference to, but worth capturing here.

**Comment by tschottdorf** [comment]
He doesn't want those writes to influence the timestamp cache.

As for the deletes, we need to figure out what we're going to do for `DeleteRange`.

**Comment by petermattis** [comment]
Secondary index entries are deleted using `Del`, so perhaps we can punt on worrying about `DelRange` or document that it doesn't write tombstones for non-existent data.

**Comment by petermattis** [comment]
Copying the proposal from the online schema change PR discussion so other folks don't have to track it down again:

> Agreed that we could look at the write timestamp to determine if the index key needs to be written. That seems expensive with the existing KV operations. What do you think of adding a PutIfOlderThan(key, value, timetamp) operation? Or perhaps just make OlderThan an option on regular Put operations? Then we could grab the timestamp before starting the index creation (e.g. before the index is added to the descriptor in delete-only mode). Then any write operations (including deletions) that are newer than that timestamp should be preferred over the index backfill.

**Comment by spencerkimball** [comment]
@petermattis @vivekmenezes this isn't happening in 1.0, so removing that milestone. Is this still a real request? If not anywhere near a reasonable expectation, let's close the issue.

**Comment by petermattis** [comment]
We currently perform schema change mutations transactionally. I think we'll eventually want to perform them non-transactionally for performance and this will be necessary to do so. This is almost certainly not going to happen for 1.0.

**Comment by petermattis** [comment]
Cc @jordanlewis as you're looking at schema change performance.

**Comment by petermattis** [comment]
@jordanlewis This is more or less what you implemented with your change to `InitPut`, right?

**Comment by jordanlewis** [comment]
No, this remains unimplemented and a potential method for further improvements to backfills.

**Comment by petermattis** [comment]
Ah, the `InitPut` happens at the current timestamp, not the historical timestamp. Got it.

**Comment by vivekmenezes** [comment]
I doubt we will need to implement this. The current plan is to compute the index at a timestamp and use AddSSTable() to insert the index.

**Comment by vivekmenezes** [comment]
currently closing. If AddSSTable() doesn't work out we can reopen this issue
