### ISSUE TITLE
feature request: dump all databases with a single command

### ISSUE THREAD

**Issue by wzrdtales** [cockroachdb/cockroach#28615]
Hey there,

just shortly shooting a question, or a feature request, depending on the outcome.

Is there any possibility to dump all databases on a cockroachdb cluster, with one command? It does not seem to be possible currently, but is quite common for a microservice environment where due to data ownage und privilege separation many databases that correlate exist.

**Comment by tim-o** [comment]
Hey @wzrdtales - as Roland mentioned, we don't have a feature to do this right now. But here's a simple python script that could do it in the meantime:

```
import psycopg2
import os

crdb = psycopg2.connect(database='any_database', user='root', host='hostname', port=26257)
crdb.set_session(autocommit=True)
crdb = crdb.cursor()
crdb.execute("show databases")
databases = crdb.fetchall()
databases = [x[0] for x in databases]

for database in databases:
	print "Backing up {0}".format(database)
	os.system("cockroach dump {0} --insecure > {0}.sql".format(database))
```

@rolandcrosby , do we have an issue open to track this request already or should we use this one?

**Comment by rolandcrosby** [comment]
@tim-o I did a quick search and didn't see any other requests for this feature, so let's just use this issue.

**Comment by C0rWin** [comment]
I would be glad take this issue, also I think that this feature should be explicit, I mean instead of assuming that we have to dump all database if do not see anything, add a flag say `--all` will make it more obvious and also less intrusive since will preserve old behavior. Thoughts?

**Comment by C0rWin** [comment]
Is there proper way to distinguish system level schemas versus application (user created databases)?

**Comment by dt** [comment]
I think you can query ... `FROM system.namespace WHERE parentID = 0 AND id > $1` where $1 is `keys.MinUserDescID` , but @knz might have a better suggestion

**Comment by C0rWin** [comment]
> I think you can query ... `FROM system.namespace WHERE parentID = 0 AND id > $1` where $1 is `keys.MinUserDescID` , but @knz might have a better suggestion

seems to be an issue, since while trying to select I'm getting following:

```
root@:26257/system> select * from namespace where parentID = '0';
ERROR: column "parentid" does not exist
SQLSTATE: 42703
```

however while selecting from table it seems legit, `select * from system.namespace`

```
  parentID | parentSchemaID |              name               | id
-----------+----------------+---------------------------------+-----
         0 |              0 | defaultdb                       | 50  parentID | parentSchemaID |              name               | id
-----------+----------------+---------------------------------+-----
         0 |              0 | defaultdb                       | 50
```

where `parentID` definitely exists.  @dt could you please also elaborate a bit on `keys.MinUserDescID`? 

I just wondering whenever it's possible to filter system databases, as for instance I can extract all available via:

```
SHOW DATABASES;
```

or 

```
SELECT DISTINCT catalog_name FROM "".information_schema.schemata;
```

given this, I would like to be able to extract or filter out databases which is created builtin.

**Comment by C0rWin** [comment]
An attempt, to provide requested feature #47387, still WP, need to add tests.

**Comment by jordanlewis** [comment]
Quick drive-by: you have to use `"parentID"`, not `parentID`, because of the capitalized letters in the column name.

**Comment by C0rWin** [comment]
> Quick drive-by: you have to use `"parentID"`, not `parentID`, because of the capitalized letters in the column name.

thanks, that's helped.
