### ISSUE TITLE
test new cgo pointer-passing restrictions

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#2862]
I'm not aware of us violating the proposed cgo pointer-passing rules, but it would be good to check early. See [this thread](https://groups.google.com/forum/#!searchin/golang-dev/pointer-passing$20restrictions/golang-dev/S7zPrUEkbKs/3TiVNWDXCQAJ) on golang-dev.

**Comment by tamird** [comment]
I cherry picked https://go-review.googlesource.com/#/c/16003/ onto https://github.com/golang/go/commit/fd8592859b3b4214276ff6ff846db7ead21215c6 and ran the test suite; no issues (though the new `vet` complained about a few minor things).
