### ISSUE TITLE
changefeedccl: test cockroach chaos

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#28639]
The jobs framework should provide crash resistance, but we need end-to-end tests that we maintain or correctness invariants through changefeed jobs being restarted.

**Comment by mrtracy** [comment]
Partially completed by #29047, which creates a new kafka chaos test.  The test currently does not validate any invariants of the feed, it simply verifies that the sink is working from Cockroach's perspective (currently not true).  Once this is no longer true (and Kafka failures no longer cause the changefeed to permanently stop), the test should be expanded to include invariant validation.

**Comment by danhhz** [comment]
I think we can do this one with TestCluster and the validator. Should be pretty straightforward. @mrtracy this is in the 2.1.0 column, is it still on your radar?

**Comment by mrtracy** [comment]
@danhhz I'm in roachtest land right now looking to repair the chaos test, i'll take a look at adding in cockroach chaos to the same test archetype.

**Comment by mrtracy** [comment]
Work on this is in progress, the test is complete but it is currently causing the job itself to fail. I have added appropriate logging to the test and am investigating a cause.

**Comment by mrtracy** [comment]
I have fixed the job failure issue, but still waiting for the test to complete at least once before sending out a PR. Something appears to be causing the test to hang and not exit, might have been a small error on my part.
