### ISSUE TITLE
changefeedccl: support watching partitions

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#28633]
So a geo-partitioned table can have a changefeed on each partition directing it to a geo-local sink. To save cross-ocean bandwidth and eventually for GDPR compliance.

The semantics are fuzzy around what should happen when a watched partition is altered. We could start by erroring either the changefeed or the alter partition and then do something better once we figure out what user expectations are.

Jira issue: CRDB-4905

**Comment by danhhz** [comment]
Related customer feedback https://github.com/cockroachdb/cockroach/pull/25229#issuecomment-398647185

**Comment by rolandcrosby** [comment]
For the first pass at this in 2.1.x we should support changefeeds on partitions and cancel the changefeed if the partition definition changes. We can try to prioritize graceful handling of repartitioning in a follow-on work item but supporting the "easy" case here will be a quick win and unblock customer use cases.

**Comment by rolandcrosby** [comment]
That's fine with me.

**Comment by miretskiy** [comment]
Closing this issue; you can target partition with cdc expressions;
it's true that we don't have ability to target to geo specific sink; but 
we'll tackle it as part of larger push to better work in multi region.

/cc @amruss  -- in case you want to reopen.
