### ISSUE TITLE
changefeedccl: measure overhead with tpccbench

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#28640]
This should wait until the distsql implementation is complete, including planning ChangeAggregators to be local to the data.

**Comment by danhhz** [comment]
Did a manual run of 20 minute periods ramping up from tpcc-1100. Take this with a grain of salt, because it was running a binary with some un-mergable changes on top because of a time-bound iterator bug (described in https://github.com/cockroachdb/cockroach/issues/32104#issuecomment-439249960). Looks like on 3 n1-standard-16s, we are fine until tpcc-1400 or so, are just falling behind at 1450, and crash and burn at 1500.

I recall us claiming to support 1500 warehouses on this hardware, but the `tpcc/nodes=3/w=max` roachtest runs at 1400 because "We haven't demonstrated that we're able to consistently and reliably run 1500 warehouses for 2h in this configuration." (https://github.com/cockroachdb/cockroach/pull/30574#pullrequestreview-158193814) I'm inclined to say the max is somewhere between 1400 and 1500 warehouses. (Further evidence for this: the tpcc loadgen was down to 80-85% efficiency at 1450 and 1500. We should run it without the changefeed to see if that repros.)

Even if the real max is 1500, that puts us at 1400/1500 = 93% efficiency. We should run this for a longer time once the real TBI fix is in to see if this holds up.

```
1100-tpcc
_elapsed_______tpmC____efc__avg(ms)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
 1200.0s    14044.5  99.3%    247.9     48.2    134.2    176.2   9126.8  21474.8
1100-cdc
__avg(ms)__p50(ms)__p75(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
   2798.5   2684.4   2952.8   3087.0   3221.2   9663.7  15032.4

1200-tpcc
_elapsed_______tpmC____efc__avg(ms)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
 1200.0s    15320.0  99.3%    280.0     58.7    159.4    201.3   9663.7  20401.1
1200-cdc
__avg(ms)__p50(ms)__p75(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
   2798.9   2684.4   2952.8   3087.0   3221.2   7784.6  16643.0

1300-tpcc
_elapsed_______tpmC____efc__avg(ms)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
 1200.0s    16529.8  98.9%    405.3    113.2    260.0    335.5  11274.3  38654.7
1300-cdc
__avg(ms)__p50(ms)__p75(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
   3334.2   2818.6   2952.8   3221.2   4831.8  24696.1  26843.5

1400-tpcc
_elapsed_______tpmC____efc__avg(ms)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
 1200.0s    17759.0  98.6%    422.9    167.8    352.3    419.4  11274.3  27917.3
1400-cdc
__avg(ms)__p50(ms)__p75(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
   2973.5   2684.4   2952.8   3087.0   3221.2  16106.1  19327.4

1500-tpcc
_elapsed_______tpmC____efc__avg(ms)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
 1200.0s    15323.5  79.4%   5909.4   4295.0  11274.3  15032.4  42949.7 103079.2
1500-cdc
__avg(ms)__p50(ms)__p75(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
  64180.6  73014.4  98784.2 124554.1 128849.0 137439.0 137439.0

1450-tpcc
_elapsed_______tpmC____efc__avg(ms)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
 1200.0s    15859.1  85.0%   4092.4   1208.0  10200.5  13958.6  33286.0 103079.2
1450-cdc
__avg(ms)__p50(ms)__p75(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
 50167.4  40802.2  68719.5 107374.2 120259.1 137439.0 137439.0

1400-tpcc
_elapsed_______tpmC____efc__avg(ms)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
 1200.0s    17660.0  98.1%    551.2    209.7    453.0    637.5  13421.8  36507.2
1400-cdc
__avg(ms)__p50(ms)__p75(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
  3375.1   2684.4   2952.8   3221.2   7516.2  23622.3  27917.3
```

**Comment by tbg** [comment]
@nvanbenschoten the right move here seems to put this into the `tpccbench` roachtest, right? Could you sort that out between yourself and @ajwerner?

@danhhz what's the right way to measure this, i.e. what changefeed do you suggest and what sink does it go to? Is there a /dev/null sink we should be using, or is that not an appropriate measurement because it fails to account for the outgoing bandwidth? If so, we should probably use a gce bucket with a low TTL.

**Comment by danhhz** [comment]
> what's the right way to measure this, i.e. what changefeed do you suggest and what sink does it go to? Is there a /dev/null sink we should be using, or is that not an appropriate measurement because it fails to account for the outgoing bandwidth? If so, we should probably use a gce bucket with a low TTL.

Great question. Most of the roachtests use kafka because it was the original production sink. We could use the cloud storage stuff, but we'd have to use the option to rate-limit the resolved timestamps or it would make too many files (`WITH resolved='1m'` or `WITH resolved='10m'` instead of `WITH resolved`, which emits them as fast as possible). `experimental-nodelocal` can write everything on the local disks, but it writes to paths relative to a base folder, so I don't think `/dev/null` would work out of the box. Could mount a second hard drive and use it as --external-io-dir? TTL'd gce bucket would also work (and we have one for import tests and crdb/cloud-sink) but I think my first choice is kafka.

**Comment by nvanbenschoten** [comment]
We've since performed these measurements. Any future investigation can use a new issue.
