### ISSUE TITLE
changefeedccl: test with ledger workload

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#28642]
Changefeeds should be able to keep up with https://github.com/cockroachdb/cockroach/pull/26673. Specifically, a roachtest with 3 nodes 20 cpu and 575 txn/s with a mixture of withdraw=50,deposit=50 should pass.

**Comment by mrtracy** [comment]
The "cdc/ledger" workload has been configured with something close to this specification: 3 nodes, 15 cpus, with he "withdraw=50,deposit=50" workload running from a single workload instance.

With no additional actions, it appears to be averaging over 800 TPS, which is well above our goal:

![screen shot 2018-10-22 at 3 06 08 pm](https://user-images.githubusercontent.com/6969858/47322302-50e5f700-d60c-11e8-97c2-debb2ef67333.png)

Next steps would be to try to "redline" the cluster with additional workload instances, to see if this number is the limit of CRDB or if we are being limited by the single workload process; it's possible that more TX/S is available with no additional work.

We should also get acceptable latency numbers for the workload; right now we may be too generous in how far a changefeed can fall behind and still consider the test a pass.

**Comment by mrtracy** [comment]
Resolved by #32303
