### ISSUE TITLE
ui: hardware dashboard: Unable to see total capacity on Memory Usage time series chart

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#28647]
![image](https://user-images.githubusercontent.com/21692034/44165409-a6df7100-a096-11e8-83cc-e521ae6940d1.png)

The change to the Memory Usage chart on the Hardware Metrics dashboard to show percentage usage instead of bytes used (#28598) makes the chart more actionable, however differences in total memory capacity across your cluster are very difficult to see. We should allow users to easily check how much total memory capacity each node has in addition to the percentage usage. Currently, the only way to check this is to navigate back to the Overview page and hover on memory usage percentages to see the total capacity in a tooltip.

We saw an example of when this would be useful recently with a support issue. A cluster had nodes down for a long enough period that raft logs grew to 100 MiB+. When restarting the nodes, the cockroach process would error out with an OOM message. After deploying a custom binary to help solve the issue, some of the nodes had their memory capacity doubled from 8 GB to 16 GB to prevent OOM errors while processing the large raft logs. Unfortunately, the version they were using did not have the hardware dashboard, but if it did they would have benefitted from seeing the capacities because:

- Bumping the RAM meant switching to a dedicated machine which was expensive. They wanted to switch back to a multi-tenant machine as soon as memory usage stabilized to previous values. Seeing capacities on the chart directly would save a step of having to check which machines had been switched over
- Seeing which nodes had larger capacities would help identify other memory issues they were encountering - high usage on the nodes with increased capacity is expected, but high usage on other nodes might indicate a problem

**Comment by vilterp** [comment]
Realizing this is similar to disk capacity. In both we ideally want to show, _per node_:
- how much you have
- how much you're using

…in a way that lets you see what fraction you're using. In #28188 I changed the disk graph to be the available metric, which shows how much you have left. However, that doesn't tell you how much you have (currently have to go to the node list and hover over the disk or memory number to see the total). Not yet seeing a design that elegantly solves all these problems.

**Comment by piyush-singh** [comment]
cc @josueeee
