### ISSUE TITLE
roachtest: Increase parallelism

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#28646]
The nightly roachtest runs are currently taking almost 17 hours. We need to keep an eye on this and make sure it stays under 24 hours, increasing parallelism (or dropping/shrinking some tests) as necessary.

**Comment by petermattis** [comment]
We might need to do something soon. A comment on the script which runs the roachtest nightlies says that teamcity has a 1080 min (18 hr) limit on tests. @benesch, @jordanlewis  Is there an easy way to raise that limit?

**Comment by benesch** [comment]
That limit is set to 1h elsewhere, so it must be easy enough to change.

**Comment by petermattis** [comment]
The `interleavedpartitioned` test is regularly taking ~15h. I haven't looked at that test, but I imagine that can be decreased.

The `kv/splits` test took ~12hr last night, but that was an outlier.

The next baddy is `jepsen` which regularly takes ~9h. We could parallelize the subtests in jepsen to reduce that time in half.

**Comment by petermattis** [comment]
The `interleavedpartitioned` is configured to only run for 10m. That test also has some unusual code for waiting for the workloads to finish. I'm going to make the code idiomatic and I bet a side-effect will fix whatever is causing it to hang for so long after the workload finishes.

**Comment by petermattis** [comment]
Between #28795 and #28797 we have a bit of breathing room.
