### ISSUE TITLE
cli: periodically flush in `cockroach sql --format=csv`

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#28654]
The "sinkless" version of changefeeds continuously streams back results to the user over pgwire. It'd be nice if `--format=csv` eventually printed every row that was returned (even if the stream stops returning results but doesn't close). Currently it doesn't because we never explicitly flush the writer. Flushing after every row would hurt perf too much but maybe we can do something with a timer.

cc @knz who I mentioned this to. Perhaps `--format=table` should get the same treatment. FYI definitely doesn't need to make 2.1 for cdc.

**Comment by knz** [comment]
I checked and currently it's only the csv/tsv and table writers that are buffered.

You can already view your streaming data "live" with the other formatters, probably `raw` and `records` are best for automation.

We can't change the table writer, that's something that we won't revisit any time soon (the thing needs all the rows to compute column widths, and we don't want to rewrite the tablewriter package). But doing the flush on the csv writer seems reasonable.
