### ISSUE TITLE
sql: Exclude SHOW BACKUP FILES/RANGES from auto-generated docs

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#28656]
We're not documenting `SHOW BACKUP FILES/RANGES`, but they're represented in the full grammar docs: https://www.cockroachlabs.com/docs/dev/sql-grammar.html#show_backup_stmt

Please use `/* SKIP DOC */` to exclude these statements: 
https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/parser/sql.y#L2915

cc: @Amruta-Ranade

**Comment by benesch** [comment]
Thanks, Raphael!
