### ISSUE TITLE
changefeedccl: implement the various ALTER CHANGEFEED described in the RFC

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#28668]
Current workaround is to cancel the changefeed and create a new one from where it left off.

Epic CRDB-8670

Jira issue: CRDB-4900

**Comment by lhirata** [comment]
Does this mean that to pause / resume / cancel a changefeed, we still use `PAUSE JOB job_id`, etc. and we just won't have an `ALTER CHANGEFEED`  statement yet?
