### ISSUE TITLE
changefeedccl: collapse adjacent spans with the same timestamp in span_frontier.go

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#28665]
There's a TODO for this. We use its internal entries as checkpoints in the jobs progress proto. Collapsing them will reduce how much data we're storing. Import has had stability problems from large system.jobs rows; so far it hasn't been a problem for changefeeds.

**Comment by danhhz** [comment]
This was in 2.1.x because I was thinking it was a prereq for #29660, but I figured out a way to do that one without this. Moving to 2.2

**Comment by danhhz** [comment]
This only affects the initial scan and post-schemachange backfill scans. Unfortunately, it's not gonna make 2.2

**Comment by miretskiy** [comment]
This is fixed.
