### ISSUE TITLE
changefeedccl: support tables with more than one column family

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#28667]
Changefeeds currently work only for tables with exactly one [column family](https://www.cockroachlabs.com/docs/stable/column-families.html), which is the default for all tables created since sometime before 1.0. But some users may have used this feature and we'll need to do some work before changefeeds work on their tables. This will require a followup fetch for the data in the other column families, so even once it's implemented, the changefeed will be somewhat slower.

One possible workaround in the meantime is to allow for `envelope=key_only` changefeeds on these tables, which is easy to implement and doesn't need the followup fetch.

gz#7511

Epic CRDB-1660

gz#5472

Jira issue: CRDB-4901

**Comment by danhhz** [comment]
This is quite unfortunately not going to make 2.2

**Comment by namibj** [comment]
It would also be nice to get an envelope option that includes (only) what the affected column family contains. This should be relatively easy (mostly gating multi-family tables behind the two restrictive envelopes, and formatting for the envelope).
