### ISSUE TITLE
changefeedccl: better handle rebalancing in the distsql flow

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#28674]
The distsql changefeed flow initially sets up the ChangeAggregator processors on the same node as the leaseholder for the data its watching. The leaseholders may rebalance but there's no mechanism for the ChangeAggregators following them. Likely, this could be solved in the general case by distsql, but we could potentially do something in the meantime. A current workaround is to pause and unpause the changefeed, which will re-setup the flow on the current leaseholders.

Jira issue: CRDB-4897

**Comment by miretskiy** [comment]
Changefeeds support rebalancing mechanism.
