### ISSUE TITLE
backupccl: support backup and restore of changefeeds

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#28671]

**Comment by miretskiy** [comment]
I'm inclined to close this issue.  @amruss thoughts?

**Comment by miretskiy** [comment]
No votes -- so closing this.

**Comment by amruss** [comment]
Heads up I'm going to open a similar issue to this and put it on the backlog. The purpose being we're trying to link all known limitations in the docs to a trackable issue and backup/restore of changefeeds is one of them.

**Comment by amruss** [comment]
https://github.com/cockroachdb/cockroach/issues/73434
