### ISSUE TITLE
acceptance: TestInitModeCommand flake

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#28679]
https://teamcity.cockroachdb.com/viewLog.html?buildId=839900&buildTypeId=Cockroach_UnitTests

From a PR build, but the PR contained only comments.

```
util_cluster.go:191: dial tcp: lookup <nil>: no such host
dockercluster.go:735: unexpected extra event &{0 die} (after [])
------- Stdout: -------
Cluster successfully initialized
test logs left over in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/acceptance/logTestInitModeCommand020215817
```

**Comment by petermattis** [comment]
This was moved to the `acceptance/cluster-init` roachtest. 

The failure appears to be the same as #29170. Attempting to reproduce.

**Comment by petermattis** [comment]
Also the same as #30010 which is super easy to reproduce. Closing as a dup of that bug.
