### ISSUE TITLE
feature: configurable logging format including JSON

### ISSUE THREAD

**Issue by jrasell** [cockroachdb/cockroach#28696]
As far as I can see, there is no option to change the logging format of cockroach. This makes aggregated logging troublesome; which is essential in a distributed environment. It would be awesome if the logging output type could be configurable, including a JSON option, so contextual logs can be gather and shipped to a central location.

**Comment by jordanlewis** [comment]
Thanks for the feature request! cc @rolandcrosby.

I'm guessing we're not going to get to this in the near future, but if you happened to be interested in trying to take this on yourself, we'd love a contribution.

The relevant code is in `pkg/util/log/structured.go`. `addStructured` is invoked each time we're planning to write a log message. `MakeMessage` currently takes the log tags for a message and serializes them to a flat log line - I think that would probably be the place to optionally write them as JSON instead.

**Comment by rolandcrosby** [comment]
Thanks for filing this, @jrasell. To clarify, is it just the log file format that you find problematic, or are there other issues blocking you from shipping your CockroachDB logs to a central location?

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[3762](https://cockroachdb.zendesk.com/agent/tickets/3762) has been linked to this issue.

**Comment by irfansharif** [comment]
Being tracked in #44755.
