### ISSUE TITLE
Rest explorer can't increment counter with 0

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#287]
somewhere the 0 is eaten and you get an empty string in r.Increment. I'm assuming this happens before the POST. I've also had the issue that after playing around for a while, I would get 200's back on increments with (say) 1, 2, 3 but the value would not change (so that I'm assuming it actually POSTed 0), but that I can't reproduce now.

    [POST] 400 /kv/rest/counter/ke: could not parse int64 for increment: strconv.ParseInt: parsing "": invalid syntax

**Comment by andybons** [comment]
Closing for now. If you’ve run into this again, please let me know.
