### ISSUE TITLE
distsql: checkNodeHealth system needs to take into account circuit breaker state

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#28704]
The new node dialer circuit breakers make it so that the current mechanism for node health checks during distsql physical planning aren't sufficient - I think we also need to make sure that the nodeDialer won't return a circuit breaker tripped error for each of the nodes.

We need to figure out a way to keep the liveness check accurate with respect to this circuit breaker, or we'll get spurious failures during flow setup.

**Comment by petermattis** [comment]
> I think we also need to make sure that the nodeDialer won't return a circuit breaker tripped error for each of the nodes.

I'm not following your concern here. Can you elaborate?

> We need to figure out a way to keep the liveness check accurate with respect to this circuit breaker, or we'll get spurious failures during flow setup.

Which liveness checks are you thinking of? Node liveness?

**Comment by jordanlewis** [comment]
> I'm not following your concern here. Can you elaborate?

I meant to say that the node health check mechanism needs to determine whether or not the circuit breaker has been tripped. I think your PR does that. The second question you had is answered in the same way. This issue wasn't particularly clear. If your PR causes the node health check to fail if the node's circuit breaker is tripped, then all my concerns here are answered.
