### ISSUE TITLE
sql: support TRIM function

### ISSUE THREAD

**Issue by jamperry** [cockroachdb/cockroach#2870]
Implement the `TRIM(...)` SQL function.

I've already started by 

1. Adding a `trim` builtin in `builtin.go`
2. Added the grammar context in `sql.y`

I just now need to:

1. Add it into the SQL parser at `sql/parser/sql.go`.
2. Add test cases for a variety of scenarios and edge-cases like `TRIM("")`, `TRIM(1)`

**Comment by vivekmenezes** [comment]
sql/parser/sql.go is auto generated.
Add a few tests to sql/testdata/builtin_function.

query T
SELECT TRIM(LEADING 'xy' FROM 'xTomyx')
----
Tomyx

query T
SELECT TRIM(TRAILING 'xy' FROM 'xTomyx')
----
xTom

query T
SELECT TRIM(BOTH 'xy' FROM 'xTomyx')
----
Tom

**Comment by petermattis** [comment]
FYI, either run `go generate` or `make` in the `sql/parser` directory to regenerate `sql.go` from `sql.y`.

**Comment by nvanbenschoten** [comment]
I didn't notice this until now, but I think my PR yesterday (#3089) took care of this.

**Comment by tamird** [comment]
Looks that way to me.
