### ISSUE TITLE
sql: improve testing of EXPLAIN and EXPLAIN ANALYZE

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#28702]
These code paths aren't fully tested. We should add a logic test mode that automatically runs EXPLAIN on all input queries and verifies that no errors are returned and that the server doesn't panic.

We might want to do the same for EXPLAIN ANALYZE, but it's harder because that could foul up tests if the statement makes a mutation.

**Comment by asubiotto** [comment]
Ran all queries in our logic tests wrapped in an EXPLAIN ANALYZE and analyzed the failures. Merged  https://github.com/cockroachdb/cockroach/pull/29267 and https://github.com/cockroachdb/cockroach/pull/29362 as a result. I'm happy with the testing of explain and explain analyze so closing this issue, feel free to reopen if there are any pending action items I am not aware of.
