### ISSUE TITLE
sql: updates with subqueries with anonymous columns are broken

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#28716]
```
UPDATE abc SET a = 1, (b, c) = (SELECT 1, 2);
```

```
error setting up flow: ((1, 2) AS "?column?", "?column?"): found duplicate tuple label: "?column?"
```

**Comment by arjunravinarayan** [comment]
@jordanlewis looks like you fixed this? I am unable to reproduce. In any case I'm sending out a PR that adds this as a logic test (among other subquery logic tests I was motivated to add).

**Comment by jordanlewis** [comment]
Hm, weird, I can't reproduce either.
