### ISSUE TITLE
ui: cluster viz: normalize CPU % to 0-100 by # cores

### ISSUE THREAD

**Issue by vilterp** [cockroachdb/cockroach#28724]
As of #28596, the CPU graph on the Hardware dashboard is normalized by the number of cores so that it's always between 0 and 100%. However, the cluster viz can still show CPU percentages above 100%. It should be normalized as well.

In this widget:
![image](https://user-images.githubusercontent.com/7341/45119741-3faf5c80-b12a-11e8-8b83-3ab2b4cfc79a.png)

Note: this is not simply an average, since it needs to be weighted by the number of cores in each node.

**Comment by vilterp** [comment]
@Amruta-Ranade we didn't get to this, and it's confusing… Probably should document as a known limitation?

**Comment by Amruta-Ranade** [comment]
Yup..Opening a docs issue to track this.

**Comment by sploiselle** [comment]
@vilterp Can I get a quick blurb describing this known limitation w/r/t the impact to user experience? Ideally, we need it by Friday 10/26 for the 2.1 Known Limitations page. Posting it on this issue and/or pinging me would be great.

**Comment by Amruta-Ranade** [comment]
Here's the blurb from the UI doc:
+++
For multi-core systems, the user CPU percent can be greater than 100%. Full utilization of one core is considered as 100% CPU usage. If you have n cores, then the user CPU percent can range from 0% (indicating an idle system) to (n*100)% (indicating full utilization).
+++

**Comment by nvanbenschoten** [comment]
@piyush-singh could you make a determination about whether we can close this?

**Comment by piyush-singh** [comment]
Not a priority to fix, so closing for now.
