### ISSUE TITLE
build: build broken on BSD

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#28734]
This is a regression introduced by #28565.

In `vendor/github.com/Azure/azure-storage-blob-go/2017-07-29/azblob/zc_mmf_unix.go`

The build tag is too restrictive and should really be `-build windows` or `+build linux darwin freebsd dragonfly ...`

**Comment by mjibson** [comment]
Yikes. This is a problem with a vendor'd dependency. This got fixed at https://github.com/Azure/azure-storage-blob-go/commit/0562badec5489e409f1b18596e3f77a309420a84 but that commit hasn't made it into a tagged release yet. I guess we'll pin master until they tag it?

**Comment by benesch** [comment]
Yeah, seems fine. The only other option is to fork their repository and
backport that one commit, but given that we haven't hit the freeze yet I
say we just bump to master.
