### ISSUE TITLE
storage: TestReplicateReAddAfterDown

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#2873]
The following test appears to have failed:

[#8532](https://circleci.com/gh/cockroachdb/cockroach/8532):

```
E1021 16:55:05.474847 945 storage/client_test.go:497  error reading "a" from engine 2: value type is not INT: UNKNOWN
E1021 16:55:06.475309 945 storage/client_test.go:497  error reading "a" from engine 2: value type is not INT: UNKNOWN
I1021 16:55:07.476165 945 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
I1021 16:55:07.476329 945 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
I1021 16:55:07.476437 945 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- FAIL: TestReplicateReAddAfterDown (3.25s)
	testing.go:157: storage/client_raft_test.go:1405: condition failed to evaluate within 3s: storage/client_test.go:511: expected [16 16 16], got [16 16 0]
=== RUN   TestSetupRangeTree
I1021 16:55:07.477039 945 gossip/gossip.go:175  gossiping node descriptor node_id:1 address:<network_field:"localhost" address_field:"1" > attrs:<> 
I1021 16:55:07.477787 945 kv/range_cache.go:128  lookup range descriptor: key="\x00range-tree-root"
I1021 16:55:07.477814 945 kv/range_cache.go:128  lookup range descriptor: key="\x00\x00meta2\x00range-tree-root"
I1021 16:55:07.478015 945 kv/range_cache.go:189  adding descriptor: key="\x00\x00meta2\xff\xff" desc=range_id:1 start_key:"" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I1021 16:55:07.478134 945 kv/range_cache.go:189  adding descriptor: key="\x00\x00meta2\xff\xff" desc=range_id:1 start_key:"" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I1021 16:55:07.478189 945 kv/range_cache.go:313  clearing overlapping descriptor: key="\x00\x00meta2\xff\xff" desc=range_id:1 start_key:"" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I1021 16:55:07.478349 945 multiraft/multiraft.go:524  node 1 starting
I1021 16:55:07.478462 945 raft/raft.go:406  [group 1] 1 became follower at term 5
--

I1021 16:55:09.238658 945 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestStoreRangeSystemSplits (0.23s)
=== RUN   Example_rebalancing
--- PASS: Example_rebalancing (0.14s)
FAIL
FAIL	github.com/cockroachdb/cockroach/storage	14.120s
=== RUN   TestBatchBasics
I1021 16:54:46.615487 910 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.00s)
=== RUN   TestBatchGet
I1021 16:54:46.616233 910 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.00s)
=== RUN   TestBatchMerge
I1021 16:54:46.618231 910 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestBatchMerge (0.00s)
=== RUN   TestBatchProto

```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment]
Looks like a variant of the issue fixed in #2868 (which was merged right after this)

**Comment by tschottdorf** [comment]
https://circleci.com/gh/tschottdorf/cockroach/1520

>
I1022 14:57:50.001559 975 multiraft/multiraft.go:778  node 3: got message for unknown group 1; creating it
I1022 14:57:50.001692 975 raft/raft.go:409  [group 1] 4 became follower at term 6
I1022 14:57:50.001758 975 raft/raft.go:218  [group 1] newRaft 4 [peers: [1,2,3], term: 6, commit: 17, applied: 17, lastindex: 17, lastterm: 6]
I1022 14:57:50.006880 975 util/tracer/tracer.go:138  Name                 Origin  Ts               Dur        Desc                     File
c525870006369319.41          14:57:50.006419  308.914µs  sending batch            kv/txn_coord_sender.go:306
c525870006369319.41          14:57:50.006455  41.974µs   ·meta descriptor lookup  kv/dist_sender.go:501
c525870006369319.41          14:57:50.006506  218.06µs   ·sending RPC             kv/dist_sender.go:421

>
I1022 14:57:50.006933 975 storage/replica_gc_queue.go:125  destroying local data from range 1
I1022 14:57:50.008722 975 multiraft/multiraft.go:778  node 3: got message for unknown group 1; creating it
W1022 14:57:50.008788 975 multiraft/multiraft.go:782  Error creating group 1 (in response to incoming message): raft group deleted
E1022 14:57:50.012464 975 storage/client_test.go:497  error reading "a" from engine 2: value type is not INT: UNKNOWN
E1022 14:57:50.046618 975 storage/client_test.go:497  error reading "a" from engine 2: value type is not INT: UNKNOWN
E1022 14:57:50.114098 975 storage/client_test.go:497  error reading "a" from engine 2: value type is not INT: UNKNOWN
E1022 14:57:50.248693 975 storage/client_test.go:497  error reading "a" from engine 2: value type is not INT: UNKNOWN
E1022 14:57:50.517442 975 storage/client_test.go:497  error reading "a" from engine 2: value type is not INT: UNKNOWN
E1022 14:57:51.054675 975 storage/client_test.go:497  error reading "a" from engine 2: value type is not INT: UNKNOWN
E1022 14:57:52.055020 975 storage/client_test.go:497  error reading "a" from engine 2: value type is not INT: UNKNOWN
I1022 14:57:53.055838 975 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
I1022 14:57:53.055951 975 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
I1022 14:57:53.056009 975 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
	testing.go:157: storage/client_raft_test.go:1406: condition failed to evaluate within 3s: storage/client_test.go:511: expected [16 16 16], got [16 16 0]

**Comment by bdarnell** [comment]
In this test, a replica is removed and subsequently re-added without giving the GC time to remove it. This means that when it is re-added it catches up by replaying the log instead of by receiving a new snapshot. One of the entries in that log is the ChangeReplicas operation that removed the node, and when this entry is replayed the replica queues itself up for removal. Then the `replicaGCQueue` races with the log replay process: If the log replay reaches the second ChangeReplicas which re-adds the replica, then the `replicaGCQueue` won't do anything and the test passes. If the `replicaGCQueue` wins the race, then the replica is removed, and since the log entries have already been acknowledged the leader won't retry. 

`replicaGCQueue` needs to be more careful about using ReplicaIDs instead of just StoreIDs, and to use the ReplicaID that appears in the incoming raft message instead of the one from the last-known RangeDescriptor.

**Comment by tschottdorf** [comment]
This replicates nicely with

```
function rt ()
{
    PKG="${1}" && TESTS="${2}" && shift && shift && rm -f "${PKG}.test" && make test TESTFLAGS=-c PKG=./${PKG} && while [ $? -eq 0 ]; do
        echo -n "." && ( OUT=$(./${PKG}.test --test.run "${TESTS}" --test.timeout=10s "$@" 2>&1) || ( echo "${OUT}" && false ) );
    done
}

rt storage TestReplicateReAddAfterDown
```
