### ISSUE TITLE
cli/sql: distinguish byte arrays from other types presented as []byte by lib/pq

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#28756]
@jseldess notes that the change in formatting for byte arrays in #28494 is  also affecting collated strings.

This is an artifact of lib/pq presenting collated strings to go as a byte slice (another sign that lib/pq should go).

Given the UX surprise of not being able to view strings, we should either revert #28494 or find a way to distinguish the formatting of values based on the column type instead of the Go type.

**Comment by knz** [comment]
Also @andreimatei notes in  #31528 that interval values are also presented as []byte and not pretty-printed properly.

**Comment by kardianos** [comment]
@knz 
Would it help to to have your printer iinspect the returned ColumnTypes?
[Rows.ColumnTypes](https://godoc.org/database/sql#Rows.ColumnTypes).

**Comment by knz** [comment]
I've confirmed visually that this issue has been addressed: floats, names, collated strings, intervals, timestamps, dates are now all printed correctly.
