### ISSUE TITLE
sql: support ALTER TABLE ALTER COLUMN SET NOT NULL

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#28751]
This is distinct from #9851:

CockroachDB should be able to add the NOT NULL specifier on a column with ALTER, using a job that asserts that indeed no values are NULL.

**Comment by tomholub** [comment]
Ability to do this (w/o creating and moving data to a new column) would be appreciated!

**Comment by sakalaramesh** [comment]
We would also appreciate having this feature as we also run into this issue and ended up running without this constraint

**Comment by knz** [comment]
@awoods187 ^^

**Comment by lopezator** [comment]
Just came here to say `+1` 😄

**Comment by jordanlewis** [comment]
cc @dt moving to schema change's project board.

**Comment by joshimhoff** [comment]
+1

**Comment by awoods187** [comment]
@joshimhoff how do you feel about a temporary solution of create table as?

**Comment by dt** [comment]
In progress: https://github.com/cockroachdb/cockroach/pull/37554

**Comment by joshimhoff** [comment]
@awoods187 LGTM, thx for pointer.
