### ISSUE TITLE
Cancel Job

### ISSUE THREAD

**Issue by leomkkwan** [cockroachdb/cockroach#28784]
I tried to create an index on a table with 400GB of data. I've lost the connection with the server in the middle of process. Once I reconnected, my dbeaver reconnect and re-run the create statement. That's fine and I go in and cancel the extra job. After around a day, I check with "show jobs" command and I see the index creation job is stopped progress but in the state of running, two success roll back jobs were system created. 
`
| 374446927381528578 | SCHEMA CHANGE | CREATE INDEX ON filu.public.t_ds (aid) STORING (vid)     | leo       | running   

| 374470972645703682 | SCHEMA CHANGE | CREATE INDEX ON filu.public.t_ds (aid) STORING (vid)     | leo       | canceled  

| 374834006255828996 | SCHEMA CHANGE | ROLL BACK CREATE INDEX ON filu.public.t_ds (aid) STORING | leo       | succeeded 

| 374948913002020868 | SCHEMA CHANGE | ROLL BACK CREATE INDEX ON filu.public.t_ds (aid) STORING | leo       | succeeded 
`
When I tried to cancel the running job, it will return this error

root@192.168.28.11:26257/defaultdb> cancel job 374446927381528578;
pq: split failed while applying backpressure: could not find valid split key.

Also, this admin page is not response with anything. https://192.168.28.11:8080/#/jobs

I am running a 5 nodes cluster with version v2.1.0-alpha.20180730.

**Comment by vivekmenezes** [comment]
The extra ROLL BACK job you see is because of a problem we fixed with https://github.com/vivekmenezes/cockroach/commit/87869df0f666ad45996af90388b3528ca324291b

The error returned when you run a cancel job is odd and the cluster needs further investigation.

**Comment by vivekmenezes** [comment]
@leomkkwan that's good to know. At this time it's not clear what problem you were having. I've added a fix that will go into the next beta that will have the roll back job reference the original job https://github.com/cockroachdb/cockroach/pull/28857 which will help debugging in the future.

At this time I don't see anything actionable on this issue. If you are happy with the outcome, please close this issue. Thanks!
