### ISSUE TITLE
sql: CockroachDB does not support updating session vars via UPDATE to pg_settings

### ISSUE THREAD

**Issue by glerchundi** [cockroachdb/cockroach#28826]
Is this a bug report or a feature request?

Bug.

- Which version of CockroachDB are you using?

v2.0.5

- What did you do?

`UPDATE pg_settings SET setting = 'true' WHERE name = 'sql_safe_updates';`

- What did you expect to see?

Successful update, `SET` works but `UPDATE` against `pg_settings` doesn't:

```
root@:26257/hydra> SET sql_safe_updates = false;
SET

Time: 579.501µs
```

- What did you see instead?

```
root@:26257/hydra> UPDATE pg_settings SET setting = 'true' WHERE name = 'sql_safe_updates';
pq: user root does not have UPDATE privilege on relation pg_settings
```

- What was the impact?

Unable to send a PR to ORY Hydra without tweaking their code base too much. I would like to send this change to their migration:

```
UPDATE pg_settings SET setting = 'false' WHERE name = 'sql_safe_updates';
```

This way the migration could work in PostgreSQL and CockroachDB.

xref: #28415

**Comment by knz** [comment]
@glerchundi CockroachDB does not support writing to `pg_settings`. 

As documented here: https://www.postgresql.org/docs/10/static/view-pg-settings.html

there is no distinction between using UPDATE or using SET. Why do you not prefer to use SET, which is supported by CockroachDB and much shorter SQL?

**Comment by glerchundi** [comment]
> @glerchundi also I am very surprised; sql_safe_updates in CockroachDB is false by default for non-interactive sessions. It is only set automatically to true for cockroach sql. I suppose that the ORM migration is ran through a client connection, and thus would never see sql_safe_updates other than false already. Why do you think you need to change it?

It was my fault, I saw the migration failing in a concrete step, I manually reproduced those steps and saw that the first one was failing and therefore incorrectly thought that `UPDATE` was failing. I double checked and, as you said, it's working as expected.

Although the `UPDATE` could have sense in case you want to conditionally set some runtime  parameter, this eases creating postgres/cockroach compatible SQL sentences.

Close if you think this doesn't apply, thanks for being this quick answering.

**Comment by knz** [comment]
I'll keep the issue open because it's probably a legitimate compatibility ask; however its priority will remain low for the foreseeable future.

**Comment by jordanlewis** [comment]
Unlikely that we're going to get to this, and it's not really a compatibility question because this is also impossible in Postgres.
