### ISSUE TITLE
ui: use new React ref API

### ISSUE THREAD

**Issue by couchand** [cockroachdb/cockroach#28845]
React has (once again...) changed the preferred API for working with refs.  We should update all our usages to use the new version.

https://reactjs.org/docs/refs-and-the-dom.html

**Comment by tugrulcan** [comment]
Is this issue still valid? If so I would like to help with that

**Comment by couchand** [comment]
@tugrulcan thanks for offering!  Yep, we still have old versions of the ref API sprinkled about.  Look around in `pkg/ui/src` and `pkg/ui/ccl/src`.  Let me know if you have any questions.

**Comment by bithavoc** [comment]
@couchand This issue seems to have been solved https://github.com/cockroachdb/cockroach/search?l=TypeScript&q=ref%3D

Do you closed it with 2.2?

**/me** keeps looking for something else to contribute with.

**Comment by couchand** [comment]
@bithavoc yep, thanks.  Looks like that PR didn't have quite the right incantation for GitHub.  Are you particularly looking for a UI issue to help on?  Here are a couple candidates:

- https://github.com/cockroachdb/cockroach/issues/19520 (another API update, this one is Redux)
- https://github.com/cockroachdb/cockroach/issues/20921 (refactoring out a component for the common markup used for our tooltips)
- https://github.com/cockroachdb/cockroach/issues/17664 (some table header styling cleanup)

Thanks!
