### ISSUE TITLE
changefeedccl: add online help for CREATE CHANGEFEED

### ISSUE THREAD

**Issue by rolandcrosby** [cockroachdb/cockroach#28844]
We don't currently have any online help (\h) for the CREATE CHANGEFEED statement in the `cockroach sql` CLI. We should at least document the syntax and options, especially since invalid statements currently direct the user to consult "\h CREATE".

Epic CRDB-2365

Jira issue: CRDB-4890

**Comment by danhhz** [comment]
I'm not planning on working on this anytime soon, so unassigning for now

**Comment by miretskiy** [comment]
Wow... our online help was bad 4 years ago, and still is bad.
