### ISSUE TITLE
ui: Positioning of tooltips on statements page seems off

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#28869]
When I try to hover over a cell in the Mean Latency column to get more details, the tooltip renders mostly outside of the visible page such that I can't actually see the details:

<img width="1673" alt="screen shot 2018-08-20 at 4 17 49 pm" src="https://user-images.githubusercontent.com/7085343/44367164-9cf1af80-a494-11e8-8ce9-a054e2135b81.png">

And while it isn't a real problem, the tooltips for the rest of the columns show up further right than I'd expect. It doesn't look that weird, but I'm just mentioning it in case it's related:

<img width="636" alt="screen shot 2018-08-20 at 4 14 24 pm" src="https://user-images.githubusercontent.com/7085343/44367131-88151c00-a494-11e8-9f84-a3f45d5d431e.png">

<img width="642" alt="screen shot 2018-08-20 at 4 14 18 pm" src="https://user-images.githubusercontent.com/7085343/44367136-8b100c80-a494-11e8-834d-7e4795f13605.png">

<img width="902" alt="screen shot 2018-08-20 at 4 13 59 pm" src="https://user-images.githubusercontent.com/7085343/44367139-8cd9d000-a494-11e8-8cc9-bc2b7a93a1bd.png">

**Comment by a-robinson** [comment]
There's a similar problem on the databases page, e.g. [on adriatic](https://adriatic.crdb.io:8080/#/databases/tables):

<img width="344" alt="screen shot 2018-08-27 at 12 15 13 pm" src="https://user-images.githubusercontent.com/7085343/44674375-e9883e00-a9f2-11e8-8989-ec9092b03963.png">

**Comment by vilterp** [comment]
@j-low this could be a good issue for you.

I'd just add a class `tooltip--left` or something that forces the tooltip to go to the left (right now it always goes to the right). I think it's fine to hard code that tooltips should go to the left when their triggering UI elements are on the right side of the screen. (e.g. the "mean latency" column and databases page tooltips mentioned here)

**Comment by couchand** [comment]
@vilterp I spent a little while on that exact strategy, and got confounded by a few places where it will require some really ugly hacking, since there is some generic code that renders components to both sides of the screen (specifically on the Statements page).  It might be a reasonable workaround if we're really pressed for time, but given the opportunity I'd much prefer to use a canned solution to this problem such as popper.js to position the tooltips dynamically rather than having to hard code each special case.

**Comment by vilterp** [comment]
Fair enough. Having a robust tooltip solution (i.e. one that can figure out which way it needs to go) does seem like a worthwhile time investment.
