### ISSUE TITLE
newRaft() panic on node init: [group 1] 1 state.commit 10062 is out of range [10, 9570]

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#2886]
ran into this in an acceptance test WIP which repeatedly kills and restarts nodes in a three-node cluster. Code to reproduce here: https://github.com/tschottdorf/cockroach/tree/monkey_test (it happens more often if restarts are limited to the first node, and there are also various other deadlocks happening).

> I1022 14:18:37.128292 1 server/context.go:178  initialized 1 storage engine(s)
I1022 14:18:37.128400 1 cli/start.go:146  starting cockroach cluster
I1022 14:18:37.143595 1 storage/engine/rocksdb.go:103  opening rocksdb instance at "/data0"
I1022 14:18:37.167483 1 gossip/gossip.go:668  starting client to roach1.local:26257
W1022 14:18:37.177636 1 rpc/client.go:226  dial tcp 172.17.3.137:26257: getsockopt: connection refused
I1022 14:18:37.231345 1 server/node.go:286  initialized store store=1:1 ([ssd]=/data0): {Capacity:19507089408 Available:10216960000 RangeCount:0}
I1022 14:18:37.231717 1 server/node.go:213  node ID 0 initialized
I1022 14:18:37.233957 1 gossip/gossip.go:175  gossiping node descriptor node_id:1 address:<network_field:"tcp" address_field:"roach0.local:26257" > attrs:<>
I1022 14:18:37.236509 1 server/node.go:376  connecting to gossip network to verify cluster ID...
E1022 14:18:37.244554 1 raft/raft.go:780  [group 1] 1 state.commit 10062 is out of range [10, 9570]
panic: [group 1] 1 state.commit 10062 is out of range [10, 9570]

>
goroutine 25 [running]:
github.com/cockroachdb/cockroach/multiraft.(*raftLogger).Panicf(0xc82029b420, 0x1462500, 0x2b, 0xc8202ea8c0, 0x4, 0x4)
	/go/src/github.com/cockroachdb/cockroach/multiraft/raft.go:121 +0x1a2
github.com/coreos/etcd/raft.(*raft).loadState(0xc82028ad00, 0x12, 0x3, 0x274e, 0x0, 0x0, 0x0)
	/go/src/github.com/coreos/etcd/raft/raft.go:780 +0x2b3
github.com/coreos/etcd/raft.newRaft(0xc82027f570, 0xc82028c720)
	/go/src/github.com/coreos/etcd/raft/raft.go:205 +0x8f0
github.com/coreos/etcd/raft.(*multiNode).run(0xc82028c3c0)
	/go/src/github.com/coreos/etcd/raft/multinode.go:203 +0x423
created by github.com/coreos/etcd/raft.StartMultiNode
	/go/src/github.com/coreos/etcd/raft/multinode.go:71 +0x30d

**Comment by tschottdorf** [comment]
one more:

>
I1022 14:54:54.177290 1 cli/start.go:146  starting cockroach cluster
I1022 14:54:54.204594 1 storage/engine/rocksdb.go:103  opening rocksdb instance at "/data2"
I1022 14:54:54.227803 1 server/node.go:286  initialized store store=2:2 ([ssd]=/data2): {Capacity:195
07089408 Available:10087813120 RangeCount:0}
I1022 14:54:54.228032 1 server/node.go:213  node ID 0 initialized
I1022 14:54:54.229433 1 gossip/gossip.go:175  gossiping node descriptor node_id:2 address:<network_fi
eld:"tcp" address_field:"roach2.local:26257" > attrs:<>
I1022 14:54:54.230213 1 server/node.go:376  connecting to gossip network to verify cluster ID...
I1022 14:54:54.232769 1 gossip/gossip.go:668  starting client to roach1.local:26257
E1022 14:54:54.246127 1 raft/raft.go:780  [group 1] 2 state.commit 319 is out of range [10, 72]
panic: [group 1] 2 state.commit 319 is out of range [10, 72]

>
goroutine 22 [running]:
github.com/cockroachdb/cockroach/multiraft.(*raftLogger).Panicf(0xc820290e10, 0x1462580, 0x2b, 0xc8202a8340, 0x4, 0x4)
        /go/src/github.com/cockroachdb/cockroach/multiraft/raft.go:121 +0x1a2
github.com/coreos/etcd/raft.(*raft).loadState(0xc8201efd40, 0xb, 0x2, 0x13f, 0x0, 0x0, 0x0)
        /go/src/github.com/coreos/etcd/raft/raft.go:780 +0x2b3
github.com/coreos/etcd/raft.newRaft(0xc820275420, 0xc82028a180)
        /go/src/github.com/coreos/etcd/raft/raft.go:205 +0x8f0
github.com/coreos/etcd/raft.(*multiNode).run(0xc82000fe00)
        /go/src/github.com/coreos/etcd/raft/multinode.go:203 +0x423
created by github.com/coreos/etcd/raft.StartMultiNode
        /go/src/github.com/coreos/etcd/raft/multinode.go:71 +0x30d

**Comment by tschottdorf** [comment]
this one isn't `newRaft`, but created in the same setting.

>
I1022 19:50:25.653423 1 server/server.go:201  starting https server at roach1.local:26257
E1022 19:50:25.661114 1 raft/raft.go:780  [group 1] 2 state.commit 290 is out of range [10, 38]
panic: [group 1] 2 state.commit 290 is out of range [10, 38]

>
goroutine 26 [running]:
github.com/cockroachdb/cockroach/multiraft.(*raftLogger).Panicf(0xc8202a8990, 0x1467820, 0x2b, 0xc82027bc00, 0x4, 0x4)
	/go/src/github.com/cockroachdb/cockroach/multiraft/raft.go:121 +0x1a2
github.com/coreos/etcd/raft.(*raft).loadState(0xc82021aea0, 0xa, 0x3, 0x122, 0x0, 0x0, 0x0)
	/go/src/github.com/coreos/etcd/raft/raft.go:780 +0x2b3
github.com/coreos/etcd/raft.newRaft(0xc82026f5e0, 0xc820272900)
	/go/src/github.com/coreos/etcd/raft/raft.go:205 +0x8f0
github.com/coreos/etcd/raft.(*multiNode).run(0xc8202725a0)
	/go/src/github.com/coreos/etcd/raft/multinode.go:203 +0x423
created by github.com/coreos/etcd/raft.StartMultiNode
	/go/src/github.com/coreos/etcd/raft/multinode.go:71 +0x30d

**Comment by bdarnell** [comment]
Dupilcate of #2592
