### ISSUE TITLE
roachtest: interleavedPartitioned doesn't do txn retries

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#28873]
As far as I can see, `interleavedPartitioned` doesn't do retries. And I've seen it fail on a retriable error (`RETRY_ASYNC_WRITE_FAILURE` - which I think can happen on lease transfers).

@petermattis you seem to have touched this test; want to touch it some more?

**Comment by andreimatei** [comment]
- @emsal1863 
cc @jordanlewis

**Comment by BramGruneir** [comment]
Fixed in #30944
