### ISSUE TITLE
sql: tpcc returns retriable errors to the user

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#28898]
Running TPCC with latest master sometimes produces retriable errors that get propagated all the way up to the user, like the "replay txn" error.

@asubiotto theorizes that this could be because of #24798.

@andreimatei, what do you think?

**Comment by andreimatei** [comment]
I don't think "replay txn" errors can be caused by #24798; this sounds like #28270.

**Comment by jordanlewis** [comment]
I've added more logging to the client - soon we'll know what pgerror code these errors are returning. Plenty of errors are being returned properly as 40001 - it's just a matter of tracking down which ones aren't.

**Comment by jordanlewis** [comment]
As far as I can tell, the only spurious error that gets returned is `replay txn`, which is marked as `XX000` but is caused by a separate issue: see #28389.

I could have sworn I saw a non-replay-txn error pop up, but now I can't reproduce it. I'll keep trying though.

**Comment by jordanlewis** [comment]
Looks like this has always been a problem. I confirmed that it reproduces on release-2.0. The next question is why it didn't come up in TPCC back then. Perhaps these sorts of errors were inadvertently made more likely.

**Comment by jordanlewis** [comment]
The root cause of this issue seems to be the fact that the TransactionCoordSender is currently misconfigured to return a `HandledRetryableTxnError` even in the "leaf txn" configuration, which confuses downstream components into not returning a retryable error.

We found this by adding the diff:

```
diff --git a/pkg/kv/txn_coord_sender.go b/pkg/kv/txn_coord_sender.go
index 5b34d5935f..299894fbab 100644
--- a/pkg/kv/txn_coord_sender.go
+++ b/pkg/kv/txn_coord_sender.go
@@ -21,6 +21,8 @@ import (
 
        "github.com/pkg/errors"
 
+       "runtime/debug"
+
        "github.com/cockroachdb/cockroach/pkg/base"
        "github.com/cockroachdb/cockroach/pkg/internal/client"
        "github.com/cockroachdb/cockroach/pkg/keys"
@@ -711,6 +713,9 @@ func (tc *TxnCoordSender) maybeRejectClientLocked(
                        // priority is not used for aborted errors
                        roachpb.NormalUserPriority,
                        tc.clock)
+               if tc.typ == client.LeafTxn {
+                       log.Infof(ctx, "ALERT %s", debug.Stack())
+               }
                return roachpb.NewError(roachpb.NewHandledRetryableTxnError(
                        abortedErr.Message, tc.mu.txn.ID, newTxn))
        }
```

which produced a stack trace on an in-the-wild cluster:

```
I180822 19:47:31.791747 634332 kv/txn_coord_sender.go:717  [n1] ALERT goroutine 634332 [running]:
runtime/debug.Stack(0x2f4e2c0, 0xc4517f0570, 0xc42e47ca00)
       /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/cockroachdb/cockroach/pkg/kv.(*TxnCoordSender).maybeRejectClientLocked(0xc45d3ff800, 0x2f4e2c0, 0xc4517f0570, 0xc421643318, 0x0)
       /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:717 +0x2c5
github.com/cockroachdb/cockroach/pkg/kv.(*TxnCoordSender).Send(0xc45d3ff800, 0x2f4e2c0, 0xc4517f0570, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
       /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:550 +0xc2
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).sendUsingSender(0xc42076e380, 0x2f4e2c0, 0xc4517f0570, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
       /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:622 +0x135
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).Send(0xc45ccae6e0, 0x2f4e2c0, 0xc4517f0570, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
       /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:783 +0x161
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*txnKVFetcher).fetch(0xc463bf9030, 0x2f4e2c0, 0xc4517f0570, 0xc433704180, 0x26b9da0)
       /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/kvfetcher.go:312 +0x597
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*txnKVFetcher).nextBatch(0xc463bf9030, 0x2f4e2c0, 0xc4517f0570, 0x26b9da0, 0x46e8118, 0x29aef40, 0xc4408e8d00, 0x2f4e2c0, 0xc464fcb500, 0xc428ddddb8, ...)
       /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/kvfetcher.go:400 +0x70
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*RowFetcher).nextKV(0xc42e232c90, 0x2f4e2c0, 0xc4517f0570, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
       /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/rowfetcher.go:486 +0x3ab
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*RowFetcher).NextKey(0xc42e232c90, 0x2f4e2c0, 0xc4517f0570, 0x0, 0x0, 0x0)
       /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/rowfetcher.go:524 +0x8a
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*RowFetcher).StartScanFrom(0xc42e232c90, 0x2f4e2c0, 0xc4517f0570, 0x2f2d6c0, 0xc463bf9030, 0x0, 0x28ffc01)
       /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/rowfetcher.go:447 +0xd9
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*RowFetcher).StartScan(0xc42e232c90, 0x2f4e2c0, 0xc4517f0570, 0xc45ccae6e0, 0xc4338853b0, 0x1, 0x1, 0xc435d86901, 0x0, 0xc44fad6600, ...)
       /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/rowfetcher.go:435 +0x1e8
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*tableReader).Start(0xc42e232800, 0x2f4e2c0, 0xc433884e40, 0xc4425b7f70, 0xbe897f)

/home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/tablereader.go:226 +0x173
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*aggregatorBase).start(0xc44d532a80, 0x2f4e2c0, 0xc433884e40, 0x2a2681c, 0x12, 0x2f4e2c0, 0xc4425b7f88)
       /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/aggregator.go:400 +0x52
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*orderedAggregator).Start(0xc44d532a80, 0x2f4e2c0, 0xc433884e40, 0xc4340a4b00, 0x0)
       /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/aggregator.go:396 +0x56
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).Run(0xc44d532a80, 0x2f4e2c0, 0xc433884e40, 0xc44b031f38)
       /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:738 +0x58
created by github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).StartAsync
```

This should never happen.

**Comment by andreimatei** [comment]
Btw, I've verified that the cause of the "replay txn" error is the scenario described in https://github.com/cockroachdb/cockroach/issues/28270#issuecomment-411535898
A big-ass batch with the `BeginTxn` is sent out, split into sub-batches for different ranges, the sub-batch with the Begin is real slow so an intent from another range manages to be pushed, and then the heartbeat loop notices that it was aborted and sends a rollback, and then eventually the original BeginTxn gets this error.
On a 4-node roachprod cluster with 2 tpcc workers (no -nowait), I see the Begin batch take 20s :S
The Begin corresponds to a transactions doing:
```
UPDATE "order" SET o_carrier_id = 2 WHERE (o_w_id = 375) AND ((o_d_id, o_id) IN ((1, 2104), (2, 2104), (10, 2104), (7, 2104), (8, 2104), (9, 2104), (3, 2104), (4, 2104), (5, 2104), (6, 2104))) RETURNING o_d_id, o_c_id
```

**Comment by andreimatei** [comment]
So I'm looking at the badly wrapped `HandledRetryableTxn` issues. I can't quite tell what's going on. What appears to be happening is that a `TxnCoordSenderFactory.TransactionalSender()` is called by providing a `TxnCoordMeta` with an aborted txn in it. But that seems cray cray... Are we starting a flow in an aborted txn? More digging tomorrow.

**Comment by andreimatei** [comment]
I verified that we are indeed trying to start a flow in an aborted txn. We should add protection against that, as it obviously it will result in a bad time.
But the hole only gets deeper - why exactly are we trying to do that? Presumably there's some sort of a race, but what? There's no parallel statements in TPCC, so how does a client get to know that its txn is aborted async wrt to processing queries? It has to be the heartbeat loop, but how is a transaction whose `BeginTxn` presumably succeeded getting aborted? The only thing I can think of is the hb loop failed to heartbeat for more than 2s (but then succeeding suddenly to notice that someone else aborted the txn). Verifying...

**Comment by andreimatei** [comment]
Well in the cluster I'm running (roachprod 4 node, 3 tpcc workloads running concurrently) I'm seeing heartbeats taking up to 5s. And those heartbeats find their transactions to be aborted.
I'm now satisfied with the theory that these loser heartbeats race with creating a new flow which captures an already-aborted txn.
Will have a patch with protections at different levels soon.
