### ISSUE TITLE
sql: incorrect behavior for ON DELETE CASCADE

### ISSUE THREAD

**Issue by xudongzheng** [cockroachdb/cockroach#28896]
**BUG REPORT**

Please describe the issue you observed, and any steps we can take to reproduce it:

- Which version of CockroachDB are you using?

Reproduced on 2.0.2 and 2.1.0 alpha

- What did you do?

```
CREATE TABLE IF NOT EXISTS example (
        a INT UNIQUE,
        b INT REFERENCES example (a) ON DELETE CASCADE
);

INSERT INTO example VALUES (20, NULL);
INSERT INTO example VALUES (30, 20);
INSERT INTO example VALUES (NULL, 30);

DELETE FROM example where a = 30;
SELECT COUNT(*) FROM example;
```

- What did you expect to see?

Only the second and third row should be deleted; first row should not be deleted. Running the DELETE statement deletes all three rows.

**Comment by BramGruneir** [comment]
@xudongzheng This is a great bug!  Good find!
