### ISSUE TITLE
Connection Lost for select during TPCC run

### ISSUE THREAD

**Issue by drewdeally** [cockroachdb/cockroach#28904]
**While testing tpcc workload.LATEST with the following options 

workload run tpcc --warehouses=1000 --duration=5h  "postgresql://root@drew-cluster-0004:26257/tpcc?sslmode=disable"

,

following error occurred in another session connect to local haproxy

./cockroach sql --insecure

root@:26257/defaultdb> select count(1) from tpcc.order;
+----------+
|  count   |
+----------+
| 30566341 |
+----------+
(1 row)

Time: 28.354179206s

root@:26257/defaultdb> select count(1) from tpcc.order_line;
driver: bad connection
warning: connection lost!
opening new connection: all session settings will be lost
root@:26257/defaultdb>** 

Also found other count count(1) from few other tables would either hang or error out as above.

Also found a few other issues with workload.LATEST
Invoked
 workload run tpcc --warehouses=1000 --duration=5h  "postgresql://root@drew-cluster-0004:26257/tpcc?sslmode=disable"

after 11m 

  11m15s        0            0.0           18.6      0.0      0.0      0.0      0.0 stockLevel
  11m16s        0            0.0           18.5      0.0      0.0      0.0      0.0 delivery
  11m16s        0            0.0          183.3      0.0      0.0      0.0      0.0 newOrder
  11m16s        0            0.0           18.6      0.0      0.0      0.0      0.0 orderStatus
  11m16s        0            0.0          186.4      0.0      0.0      0.0      0.0 payment
  11m16s        0            0.0           18.6      0.0      0.0      0.0      0.0 stockLevel
Error: error in newOrder: driver: bad connection
andrewdeally@drew-cluster-0004:~$ 

workload run tpcc --ramp=30s --warehouses=1000 --duration=5h --split --scatter "postgresql://root@drew-cluster-0004:26257/tpcc?sslmode=disable"

     59s        0           17.0           18.7     83.9    104.9    125.8    125.8 stockLevel
    1m0s        0           15.0           18.6     88.1    104.9    104.9    104.9 delivery
    1m0s        0          223.1          147.5     56.6     92.3    100.7    113.2 newOrder
    1m0s        0           23.0           20.2     12.1     14.7     16.3     16.3 orderStatus
    1m0s        0          190.1          189.2     27.3     62.9     75.5  60129.5 payment
    1m0s        0           20.0           18.7     92.3    142.6    142.6    142.6 stockLevel
Error: error in newOrder: missing stock row

Finally with initial load

workload fixtures load tpcc "postgresql://root@drew-cluster-0001:26257/tpcc?sslmode=disable" --warehouses=1000
I180821 14:01:39.351478 106 ccl/workloadccl/fixture.go:424  loaded district (5m6s, 10000 rows, 0 index entries, 1006 KiB)
I180821 14:02:58.084193 111 ccl/workloadccl/fixture.go:424  loaded item (6m25s, 100000 rows, 0 index entries, 7.8 MiB)
I180821 14:04:31.519700 110 ccl/workloadccl/fixture.go:424  loaded new_order (7m59s, 9000000 rows, 0 index entries, 126 MiB)
I180821 14:06:41.859241 105 ccl/workloadccl/fixture.go:424  loaded warehouse (10m9s, 1000 rows, 0 index entries, 53 KiB)
I180821 14:08:44.721993 109 ccl/workloadccl/fixture.go:424  loaded order (12m12s, 30000000 rows, 60000000 index entries, 1.8 GiB)
I180821 14:09:22.276970 108 ccl/workloadccl/fixture.go:424  loaded history (12m49s, 30000000 rows, 60000000 index entries, 3.8 GiB)
I180821 14:14:25.106953 107 ccl/workloadccl/fixture.go:424  loaded customer (17m52s, 30000000 rows, 30000000 index entries, 17 GiB)
I180821 14:34:38.764888 112 ccl/workloadccl/fixture.go:424  loaded stock (38m6s, 100000000 rows, 100000000 index entries, 31 GiB)
I180821 14:35:17.890415 113 ccl/workloadccl/fixture.go:424  loaded order_line (38m45s, 300013709 rows, 300013709 index entries, 22 GiB)
I180821 14:35:18.558142 1 cmd/workload/fixtures.go:256  fixture is restored; now running consistency checks (ctrl-c to abort)
I180821 14:35:18.628715 1 workload/tpcc/tpcc.go:256  check 3.3.2.1 took 70.523952ms
I180821 14:35:44.463735 1 workload/tpcc/tpcc.go:256  check 3.3.2.2 took 25.834970932s
I180821 14:35:49.010058 1 workload/tpcc/tpcc.go:256  check 3.3.2.3 took 4.546261609s
I180821 14:39:02.800367 1 workload/tpcc/tpcc.go:256  check 3.3.2.4 took 3m13.790230874s

I180821 14:41:35.836653 1 workload/tpcc/tpcc.go:256  check 3.3.2.5 took 2m33.036224867s
I180821 14:51:07.677073 1 workload/tpcc/tpcc.go:256  check 3.3.2.7 took 9m31.840353975s
Error: check failed: 3.3.2.7: pq: memory budget exceeded: 10240 bytes requested, 3782602424 currently allocated, 3782603776 bytes in budget

Provision vi roachprod with 16 cpu high shapes

**Comment by tschottdorf** [comment]
>  driver: bad connection

Probably a node crashed, can you check the ui?

> Error: error in newOrder: missing stock row

I'm not aware of that one, but it looks like this shouldn't happen.

**Comment by drewdeally** [comment]
./cockroach version
Build Tag:    v2.1.0-alpha.20180730
Build Time:   2018/07/30 21:12:13
Distribution: CCL
Platform:     linux amd64 (x86_64-unknown-linux-gnu)
Go Version:   go1.10.3
C Compiler:   gcc 6.3.0
Build SHA-1:  a31bd6bcd5f79481a94873f212ca8b9957fc5766
Build Type:   release

**Comment by drewdeally** [comment]
I had checked and nodes are all running 


n1 | drew-cluster-0001:26257 | 3 hours | 74.2 GiB | 7600 | 7.6 GiB | v2.1.0-alpha.20180730 | Logs
-- | -- | -- | -- | -- | -- | -- | --
n2 | drew-cluster-0002:26257 | 3 hours | 74.4 GiB | 7600 | 8.7 GiB | v2.1.0-alpha.20180730 | Logs
n3 | drew-cluster-0003:26257 | 3 hours | 74.4 GiB | 7600 | 8.5 GiB | v2.1.0-alpha.20180730 | Logs


I have seen the connection issue before without a node abending

**Comment by drewdeally** [comment]
some additional details
roachprod run drew-cluster:1-3  -- 'grep error ~/logs/co*.log' 
drew-cluster: grep error ~/logs/co*.log 3/3
   1: 
Process exited with status 1
   2: /home/andrewdeally/logs/cockroach.drew-cluster-0002.andrewdeally.2018-08-21T16_34_25Z.004643.log:E180821 16:35:49.423974 20272099 storage/consistency_queue.go:125  [replica consistency checker,n2,s2,r5261/3:/Table/59/2/1{5802/9…-8263/1…}] computing own checksum: rpc error: code = DeadlineExceeded desc = context deadline exceeded
/home/andrewdeally/logs/cockroach.drew-cluster-0002.andrewdeally.2018-08-21T16_34_25Z.004643.log:E180821 16:35:49.425821 20272099 storage/queue.go:778  [replica consistency checker,n2,s2,r5261/3:/Table/59/2/1{5802/9…-8263/1…}] computing own checksum: rpc error: code = DeadlineExceeded desc = context deadline exceeded
/home/andrewdeally/logs/cockroach.drew-cluster-0002.andrewdeally.2018-08-21T16_40_20Z.004643.log:E180821 16:41:17.223908 22718905 storage/consistency_queue.go:125  [replica consistency checker,n2,s2,r5173/3:/Table/59/2/{548/14…-3009/2…}] computing own checksum: rpc error: code = DeadlineExceeded desc = context deadline exceeded
/home/andrewdeally/logs/cockroach.drew-cluster-0002.andrewdeally.2018-08-21T16_40_20Z.004643.log:E180821 16:41:17.223925 22718905 storage/queue.go:778  [replica consistency checker,n2,s2,r5173/3:/Table/59/2/{548/14…-3009/2…}] computing own checksum: rpc error: code = DeadlineExceeded desc = context deadline exceeded
/home/andrewdeally/logs/cockroach.drew-cluster-0002.andrewdeally.2018-08-21T16_40_20Z.004643.log:E180821 16:41:33.408488 22842895 storage/consistency_queue.go:125  [replica consistency checker,n2,s2,r5430/3:/Table/59/2/{37874/…-40336/…}] computing own checksum: rpc error: code = DeadlineExceeded desc = context deadline exceeded
/home/andrewdeally/logs/cockroach.drew-cluster-0002.andrewdeally.2018-08-21T16_40_20Z.004643.log:E180821 16:41:33.408503 22842895 storage/queue.go:778  [replica consistency checker,n2,s2,r5430/3:/Table/59/2/{37874/…-40336/…}] computing own checksum: rpc error: code = DeadlineExceeded desc = context deadline exceeded
/home/andrewdeally/logs/cockroach.drew-cluster-0002.andrewdeally.2018-08-21T16_49_12Z.004643.log:E180821 16:50:49.361981 27003551 storage/consistency_queue.go:125  [replica consistency checker,n2,s2,r5185/3:/Table/59/2/{3009/2…-5470/3…}] computing own checksum: rpc error: code = DeadlineExceeded desc = context deadline exceeded
/home/andrewdeally/logs/cockroach.drew-cluster-0002.andrewdeally.2018-08-21T16_49_12Z.004643.log:E180821 16:50:49.361996 27003551 storage/queue.go:778  [replica consistency checker,n2,s2,r5185/3:/Table/59/2/{3009/2…-5470/3…}] computing own checksum: rpc error: code = DeadlineExceeded desc = context deadline exceeded
   3: /home/andrewdeally/logs/cockroach.drew-cluster-0003.andrewdeally.2018-08-21T16_50_17Z.004609.log:E180821 16:52:13.649448 35816467 storage/queue.go:778  [raftsnapshot,n3,s3,r11772/2:/Table/53/2/1{39/3/1…-76/10/…}] snapshot failed: (n2,s2):3: remote couldn't accept snapshot with error: [n2,s2],r11772: cannot apply snapshot: snapshot intersects existing range [n2,s2,r69/3:/Table/53/2/1{01/2/1…-76/10/…}]
Error:  Process exited with status 1
