### ISSUE TITLE
TPCC docs update with proper scsi reference

### ISSUE THREAD

**Issue by drewdeally** [cockroachdb/cockroach#28958]
The Tpcc benchmark white paper  https://www.cockroachlabs.com/guides/cockroachdb-performance/ and https://www.cockroachlabs.com/docs/stable/performance-benchmarking-with-tpc-c.html

specifying the scsi option for SSD use

https://cloud.google.com/compute/docs/disks/local-ssd#create_local_ssd

as a few customers had mistakingly picked incorrect NVM-e drivers and had poor results.
https://cloud.google.com/compute/docs/disks/performance#optimize_local_ssd

as not all customers will use roachprod.

**Comment by jseldess** [comment]
Moving to the docs repo: https://github.com/cockroachdb/docs/issues/3583.
