### ISSUE TITLE
sql: access to pre-update values in RETURNING expression of UPDATE query

### ISSUE THREAD

**Issue by arctica** [cockroachdb/cockroach#28956]
It would be great if there was a way to access the value of a column before it is updated in the RETURNING clause of an UPDATE query.

E.g. accessing the value of column "last_update" before it gets set to the current time in the following query:
`UPDATE t SET last_update = now() WHERE ... RETURNING last_update`

I found through testing that it seems possible to add a "previous value" column which gets set to the old value before the update is evaluated and can be used like this:

`UPDATE t SET last_update_prev = last_update, last_update = now() WHERE ... RETURNING last_update_prev`

But I have not found anything in the docs that suggests that the right behaviour is guaranteed and of course adding an additional column is a bit wasteful.

In Postgres, people seem to resort to an ugly hack where one joins the table against itself and can use the second instance of the table in the RETURNING clause to access the pre-update values.

It would be great if there was an aliased table that could be used conveniently, similarily how Postgres provides a "EXCLUDED" table to access the values specified via VALUES() in the query. E.g. RETURNING EXCLUDED.foo
Not sure what a good name for this special table would be. OLD? PREUPDATE? CURRENT?

In the example query from above, one could use it then like this:
`UPDATE t SET last_update = now() WHERE ... RETURNING CURRENT.last_update`

Jira issue: CRDB-4886

**Comment by knz** [comment]
Thanks for your suggestion. It does seem to be a useful feature indeed.

**Comment by arctica** [comment]
@knz btw should the following work?

`WITH old AS (SELECT last_update FROM t) UPDATE t SET last_update = now() WHERE true RETURNING old.last_update;`

I am getting the following error:

> pq: no data source matches prefix: old

**Comment by knz** [comment]
I'm not sure (needs to investigate) but the following might:

```sql
WITH old AS (SELECT last_update FROM t),
     new AS (UPDATE t SET last_update = now() WHERE true RETURNING last_update)
SELECT * FROM old
```

**Comment by arctica** [comment]
I've just tried that and I see the following issue (apart from needing to also reference "new" in the SELECT or it won't execute the UPDATE query:

Both "old" and "new" have the same data. I also tried switching the order of both and again, same results.

**Comment by asubiotto** [comment]
Hey @RaduBerinde this seems like it could be an optimizer feature. Could you take a look and triage/prioritize?

**Comment by knz** [comment]
The last comment from the OP was actually a bug:

> I've just tried that and I see the following issue (apart from needing to also reference "new" in the SELECT or it won't execute the UPDATE query [...]

This report was in fact a symptom of the halloween problem we fixed in 2018-2019 (by introducing txn sequence steps).

The query I suggested above now works properly:

```sql
> create table t(last_update timestamptz);
> insert into t(last_update) values ('2001-01-01');
> insert into t(last_update) values ('2002-01-01');
> WITH old AS (SELECT last_update FROM t),
    new AS (UPDATE t SET last_update = now() WHERE true RETURNING last_update)
   SELECT * FROM old;
       last_update
--------------------------
  2001-01-01 00:00:00+00
  2002-01-01 00:00:00+00
(2 rows)
```
