### ISSUE TITLE
storage: problemranges should sharpen "expired lease" problem

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#28969]
It's expected for ranges that sit idle to have an expired lease after a while.

What we want to catch is the condition:

```
expired && (commands pending for a while || has been ticking for a while)
```

Note the "for a while", or we'll get spurious positives.

**Comment by tschottdorf** [comment]
Similarly, we should detect when a range that hasn't seen traffic in a while is not quiesced.
