### ISSUE TITLE
schema change: endless context canceled log spam after schema change

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#28991]
I did a `alter table warehouse alter w_ytd type decimal(15,2);` on adriatic. Several things went wrong:
I ran the statement twice. First time I bailed after 1m or so - ctrl-c. Then I ran it again and let it run
The statement took 2.5 min to run. I'm not aware of any running txns at that time; I doubt that there was anything since the load generators were not in a good state. It then succeeded. I'm wondering if we could do something so that the user understands what's taking so long. This schema change did not appear in the jobs table, for example.

While the alter was running, as well as afterwards, the log on node 1 got full of
```
W180823 01:10:32.950320 18569924 sql/exec_util.go:902  [n1,client=127.0.0.1:37392,user=root] error executing schema change: context canceled
```

As of 1h later, these still pop up every 1s more or less.

**Comment by vivekmenezes** [comment]
fixed through #29163
