### ISSUE TITLE
ui: infinity% memory usage

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#28990]
During a rolling upgrade on omega:
![screenshot 2018-08-22 21 00 42](https://user-images.githubusercontent.com/377201/44498773-84c59000-a64e-11e8-9632-3d3d7c715e16.png)

**Comment by andreimatei** [comment]
went away after the upgrade finished

**Comment by vilterp** [comment]
Thx for reporting. This seems to happen when a new UI is looking at an old node, since old nodes don't serve up their total memory, we get `some number / undefined` or similar which renders as `Infinity`. (Good old float math). Will insert a check.
