### ISSUE TITLE
build: How to cross-compile releases >= 2.0.2 for aarch64?

### ISSUE THREAD

**Issue by ibaira** [cockroachdb/cockroach#29005]
Sorry for the inconvenience, I was not sure if this issue should be marked as a bug or a feature request. 

I was checking how to cross-compile Cockroach to run it on an aarch64 based machine. There are some conversations where we can see that it is possible to cross-compile Cockroach as described in [here](https://github.com/cockroachdb/cockroach/issues/20433#issuecomment-379001760). When checking [this](https://github.com/cockroachdb/cockroach/pull/24354/files) pull request I could see that the aarch64 architecture is addressed in the Makefile.

Unfortunately, I didn't find the same for releases >= 2.0.2. Thus, when running:
`build/builder.sh make build TYPE=release-aarch64-linux`

I get the following error since the type 'release-aarch64-linux' is not considered anymore:
`Makefile:178: *** unknown build type release-aarch64-linux.  Stop.`

I would really appreciate if someone could point me out in the right direction on how to cross-compile Cockroach 2.0.2 - 2.0.5 for aarch64.

Thank you in advance and best regards.

**Comment by nvanbenschoten** [comment]
Hi @ibaira, I'm sorry for the delay. It looks like our cross-compilation toolchain was never backported to our 2.0 release branch. On `master` and on our `release-2.1` branch you can cross-compile with the command `build/builder.sh mkrelease arm64-linux-gnueabi`. Is that solution workable to you or were you specifically looking for a 2.0 binary for aarch64?

**Comment by ibaira** [comment]
I think v2.1 should be ok. In case it turns out that I need 2.0 I will contact you again. Thanks for your help @nvanbenschoten

**Comment by benesch** [comment]
Ok, great! Closing this out for now.
