### ISSUE TITLE
storage: single node merge experiment gets stuck

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#29004]
While trying to repro https://github.com/cockroachdb/cockroach/issues/28995 in a smaller setting.

```go
# shell 1
./cockroach start --insecure --logtostderr
# shell 2
./bin/workload run kv --init --splits 10000 --max-ops 1
echo 'SET CLUSTER SETTING kv.range_merge.queue_enabled = true;' | ./cockroach sql --insecure
```

expected: all ranges get merged away
reality: there's a flurry of activity, but that stops abruptly. I still have 9.3k replicas.

I also think we should have some rapid testing like this in our acceptance tests to really put merges through its paces.

**Comment by tschottdorf** [comment]
Oh, it's actually merging a replica every 4-12 seconds. That's too slow for this test, but I'll see about speeding that up. I thought the scanner already operated at full speed at the moment though?

**Comment by tschottdorf** [comment]
![image](https://user-images.githubusercontent.com/5076964/44524851-4d52f400-a6df-11e8-99e0-e523fb6fa42f.png)

That's the tail on a three node cluster. Looks like everything is initially queued for a merge, but once it's chewed through that backlog, it slows down at around 3.5k replicas. Just an observation; I know @benesch wants to work on this once the correctness bugs are ironed out.

**Comment by benesch** [comment]
Yep, I have a plan for fixing this. Basically we want to do what we do for splits: check after every write if we’re now below the merge size threshold and, if so, stick the range in the merge queue.

**Comment by tschottdorf** [comment]
All yours @benesch. Feel free to close if this is already covered elsewhere.
