### ISSUE TITLE
roachtest: hang in version skew upgrade

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#29018]
I'm testing IMPORT in skewed version clusters using roachtest. The below commit sets up a 2.0 node and 2 2.1 nodes in a cluster. It successfully runs an IMPORT on the 2.0 node. Then the 2.0 node is stopped and we try the same on a 2.1 node. It hangs forever. See line 440 of the attached commit (the `select {}`). Run the test locally and then connect to n2 or n3 (`roachprod sql local:2`). Running `select 1` works, but anything touching tables doesn't (`show tables`) for example.

https://github.com/mjibson/cockroach/commit/ef4226d053e881412349d4db9128c64398607982

**Comment by tschottdorf** [comment]
@mjibson thanks for putting this together. Looks like it should be assigned to someone from sql-land, though (unless it turns out to be a core problem - but we have roachtests that run mixed version clusters), or am I missing something? @jordanlewis, could you triage?

**Comment by mjibson** [comment]
This might not be a real problem. I think it is happening because I'm shutting down n1 too soon and n2 and n3 haven't had time to talk to each other yet?

**Comment by mjibson** [comment]
Ok not a real bug. This was occurring because I needed to call waitForFullReplication in the tests before shutting down n1.
