### ISSUE TITLE
importccl,distsql: EXPORT with ORDER BY fails with column-in-index error

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#29024]
From @a-robinson's QA of `EXPORT` in #25223, originally in a tpch 100 table, but reproduced here in isolation:
```
root=> create table foo (i int primary key, x int, y int, z int, index (y));
CREATE TABLE
root=> insert into foo values (1, 12, 13, 14), (2, 22, 23, 24), (3, 32, 33, 34);
INSERT 0 3
root=> EXPORT INTO CSV 'gs://cockroach-tmp/dt/export-1' from select * from foo order by y asc limit 1;
ERROR:  requested column x not in index
```

**Comment by dt** [comment]
@arjunravinarayan @asubiotto @jordanlewis or other @cockroachdb/distsql folk: I'm in slightly unfamiliar territory here: the EXPORT code is a pretty thin wrapper around off-the-shelf distsql: 
the ccl hook does a 
```
sel, err := p.Select(ctx, exportStmt.Query, nil)
```
that gets expanded via the planHook handler's recursive expandPlan thing, and then, in the execution fn, we pass it to `sql.PlanAndRunExport`. That in turn does `p, err := dsp.createPlanForNode(&planCtx, in)` and then just tacks the csv writers on to the end with 
```
	p.AddNoGroupingStage(
		out, distsqlrun.PostProcessSpec{}, ExportPlanResultTypes, distsqlrun.Ordering{},
	)
```

Somehow though when the row fetcher is run in this plan it is unhappy, but when run in the same SELECT but not wrapped in EXPORT, it is fine. I'll start scattering some printlns and see if I can figure out where it diverges, but if you have any ideas off the top of your head, I'm certainly blundering around in the dark a little here.

**Comment by dt** [comment]
that said, it looks like this _does_ come down to planning: the plan for the select when we actually start exec is an indexJoinNode, but the one in my EXPORT subplan, for the *same SQL AST* passed to makePlan, is just a scanNode. hm.

**Comment by knz** [comment]
Ask @jordanlewis he has the most updated understanding. But it is a losing proposal. I think you'll be safer disabling EXPORT with a SELECT clause altogether. It is bound to just not work.

**Comment by knz** [comment]
At the very least mark the feature as experimental! Otherwise you're creating very wrong expectations with users.

**Comment by dt** [comment]
so, the error is coming from `startExec` on the subplan -- which as @jordanlewis points out, we don't need to call at all! We're not going to run this subplan ourselves since we'll just hand it off to distsql, so there's no need to start it. Indeed, if we skip that in plan_hook.go,  it looks like it fixes this bug.

That said, this seems to underscore the point @knz made above -- this feels like the smoke that may indicate a larger fire lurking unseen: lots of the planning logic starts at the top node and walks its way down, so we're almost certainly missing _something_ right now. Also, `EXPORT` in particular is intended for exporting very large result sets from big queries -- where the optimizer might be critical to picking effective execution plans.

I'm not sure a major rewrite is in the cards right now, but ideally we'd either a) have func we can call, in the EXPORT planing, that uses the standard planning code, from as close as top to bottom as possible,  to plan EXPORT's SELECT query, including whatever optimizer/other things are enabled for usual SELECT planning. Right now we're hopping in via `planner.Select(AST) -> planNode`, but that's no longer "the top" of the funnel.

Alternatively, we could try to teach the oss code to plan an EXPORT itself. In EXPORT's case this is actually pretty easy, as there's basically nothing to do other than plan the select and validate couple params to the output stage that gets tacked on the end of the select physical plan. However for some of the other non-free statements, planning isn't so trivial, and depends on code that is considered part fo the non-trivial, non-free IP that we want to keep CCLed. There it isn't as clear that we can easily just move all the planning to the OSS side.
