### ISSUE TITLE
storage: TestStoreRangeMergeReadoptedBothFollowers flaky

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#29031]
https://teamcity.cockroachdb.com/viewLog.html?buildId=859057&buildTypeId=Cockroach_UnitTests

This might just need to be massaged (there's a cheap check that can give you one error, and another later that gives another) but I wasn't immediately able to convince myself that both errors would be expected in the test, so worth a dedicated look.

```
client_merge_test.go:1783: expected "cannot apply snapshot: snapshot intersects existing range" error, but got snapshot failed: (n3,s3):?: remote failed to apply snapshot for reason failed to apply snapshot: snapshot intersects existing range [n3,s3,r2/3:{b-/Max}]
```

**Comment by benesch** [comment]
Centralizing on https://github.com/cockroachdb/cockroach/issues/29078, which will get pinged whenever this thing fails on master. I've copied your comment over there. Thanks for the initial investigation!
