### ISSUE TITLE
importccl: need better storage scheme error message

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#29038]
Before I read the docs and learned how to use the `nodelocal` storage scheme, I tried to run `IMPORT PGDUMP` with a direct path: `IMPORT PGDUMP '/tmp/employees.sql';`. The error I got back was not very helpful: `pq: unsupported storage scheme: ""`. Perhaps this error message could include a link to the relevant docs page?

This was found as part of QA for #28158.

Jira issue: CRDB-4881

**Comment by adityamaru** [comment]
Not closing yet - will want to update the above error message with a link to the soon-to-be dedicated docs page which talks about supported ExternalStorage schemes. cc: @lnhsingh

**Comment by lnhsingh** [comment]
FYI new page here: https://www.cockroachlabs.com/docs/v20.2/use-cloud-storage-for-bulk-operations.html but it's only on dev (v20.2) right now. I plan on porting it to 20.1 docs probably after the release
