### ISSUE TITLE
importccl: inconsistent behavior with constraints in IMPORT PGDUMP

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#29041]
While doing QA for #28158, I found that the two `IMPORT TABLE` variants of `IMPORT PGDUMP` have different behavior with foreign key constraints.

I tried to import a table `dept_manager` which references table `employees` with a foreign key constraint. With one variant, I got an error:
```
> IMPORT TABLE dept_manager FROM PGDUMP 'nodelocal:///employees.sql';
pq: referenced table "employees" not found in tables being imported (dept_manager)
```

The other variant was successful:
```
> IMPORT TABLE dept_manager (
  "emp_no" bigint NOT NULL,
  "dept_no" char(4) NOT NULL,
  "from_date" date NOT NULL,
  "to_date" date NOT NULL,
  PRIMARY KEY ("emp_no","dept_no")
)
PGDUMP DATA ('nodelocal:///employees.sql');
        job_id       |  status   | fraction_completed | rows | index_entries | system_records | bytes  
+--------------------+-----------+--------------------+------+---------------+----------------+-------+
  376791521317617665 | succeeded |                  1 |   24 |             0 |              0 |   628  
(1 row)
```
It seems like the constraint in the first case should just get dropped, similar to the second case.

**Comment by miretskiy** [comment]
Works as intended;
User must specify "with skip_foreign_keys" option.
