### ISSUE TITLE
importccl: IMPORT PGDUMP fails with sequences

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#29046]
As part of QA for #28158, I created a table in Postgres that had a column of type `serial`. 

This causes a `CREATE SEQUENCE` command to be added to the pg_dump file:
```
CREATE SEQUENCE public.t3_b_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
```
CockroachDB chokes on this command with the error: `pq: postgres parse error: unimplemented at or near "start".` Once I commented out the line `AS integer` it worked successfully.

In order to handle sequences in pg_dump files, we need to be able to accept the `CREATE SEQUENCE seq AS integer...` syntax.

**Comment by mjibson** [comment]
For our product planning: this is a new syntax produced by postgres 10. Dumps before that don't have this.

**Comment by DavidOliver** [comment]
I'm getting this importing a dump from PostgreSQL 12.3 into CockroachDB 20.1.1. I was trying a dump from Craft CMS, a popular PHP CMS.

https://www.postgresql.org/docs/12/sql-createsequence.html

> data_type
> The optional clause `AS data_type` specifies the data type of the sequence. Valid types are smallint, integer, and bigint. bigint is the default. The data type determines the default minimum and maximum values of the sequence.
