### ISSUE TITLE
sql: crdb_internal.gossip_* tables are node-local

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#29064]
Noticed in https://github.com/cockroachdb/cockroach/pull/28963#pullrequestreview-149505242. The `crdb_internal.gossip_*` tables are node-local (i.e. they reflect state only on the current node), but do follow the example of other node-local tables (see `crdb_internal.node_*`) either in their naming (no `node_*` prefix) or in the usage of a `node_id` column. For example, in `crdb_internal.gossip_nodes` the `node_id` column specifies the node for which the receiving has information on. In `crdb_internal.node_statement_statistics`, the `node_id` column specifies the ID of the receiving node.

@knz wants to take a look at this to see if regularization is possible. My quick take before writing this issue is that the `crdb_internal.gossip_*` tables make sense as-is, but I'm happy for someone to think about this more deeply.

**Comment by tschottdorf** [comment]
I also find that the current situation is satisfactory.

**Comment by knz** [comment]
Yep, agreed
