### ISSUE TITLE
release-2.1: timeout in  TestAuthenticationAPIUserLogin

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#29096]
```
authentication_test.go:448: login got error Post https://127.0.0.1:44201/login: net/http: request canceled (Client.Timeout exceeded while awaiting headers), wanted error with 401 status
```

Seen in https://teamcity.cockroachdb.com/viewLog.html?buildId=863283&buildTypeId=Cockroach_UnitTests

**Comment by mrtracy** [comment]
This does not reproduce in hundreds of thousands of runs of normal stress on a gce worker; however, I now see that the flake occurs in race mode, so I am now focused on a race reproduction.

**Comment by mrtracy** [comment]
I'm also unable to reproduce this after many thousands of runs of Stressrace against master.  I'll leave it open for the time being in case it reproduces in short order (it apparently reproduced twice in a single PR), and I'll take a closer look at the code directly to see if there's some obvious opportunity for a timeout.

**Comment by tschottdorf** [comment]
Thanks for looking, Matt.
The HTTP client in this test runs with a 10s timeout, which I'm pretty sure fired. Unclear why that happened only in these builds. I was able to repro this simply by completely overstressing the test, but it's clear that this is possible.
Not sure what to do here except either stress these tests less, or bump the timeout.

**Comment by tschottdorf** [comment]
Closing as rare fluke.
