### ISSUE TITLE
sql: combination of DATABASE and USER statements wedges server

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#29090]
See #29089 for a quick test reproduction. RSG tests have been failing because combining a bunch of database and user {create, drop, alter} statements in parallel wedges a server. We had a bug similar to this just a few weeks back that was triggered just by database statements. Tagging @vivekmenezes and @jordanlewis because I'm unsure who wants to triage this.

Found with RSG.

**Comment by dt** [comment]
Another reproduction of this on #29255:
In the TC output linked below, it looks like the only two running are the test runner waiting for result? There are lots of goroutines waiting on the db cache mutex though and also several on txn push. Hopefully someone more familiar with the code involved can tell from those stack traces if this looks alarming or not.

```
panic: timeout: "CREATE USER PLACEHOLDER WITH PASSWORD PLACEHOLDER".
currently executing: map[
CREATE USER PLACEHOLDER WITH PASSWORD PLACEHOLDER:1
ALTER SEQUENCE ONLY ident . MINVALUE RENAME TO BOOLEAN . VIRTUAL . DAY:1 
DROP DATABASE IF EXISTS ident RESTRICT:1 
CREATE USER 'string' PASSWORD RESTORE:1 
RESET CLUSTER SETTING EXPERIMENTAL_AUDIT . ident . HAVING . REAL . ident:1 
CREATE DATABASE IF NOT EXISTS ident:15
```

https://teamcity.cockroachdb.com/viewLog.html?buildId=867074&tab=buildResultsDiv&buildTypeId=Cockroach_Nightlies_NightlySuite

**Comment by mjibson** [comment]
Vivek and I went over this briefly yesterday. There's a stack trace linked in the PR. The db cache lock is being held during a network request that is blocked on an intent and (apparently) not aborting something. Vivek said something about maybe because it's coming from an internal executor. In any case this is somewhere on his plate.

**Comment by vivekmenezes** [comment]
I have a PR out for this. Thanks for finding this! The PR implements the hammer we had originally planned for these kind of issues but didn't because we found another bug that this uncovered. Now we know a legitimate reason why this is happening.
