### ISSUE TITLE
storage: TestStoreRangeMergeRaftSnapshot tests too much

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#29110]
As of #29083, TestStoreRangeMergeRaftSnapshot tests the case where a Raft snapshot spans a merge _and_ a split. It is probably worthwhile to make a separate test for the case where a Raft snapshot spans only a merge.

**Comment by tschottdorf** [comment]
@benesch think you'll get to this in 2.1? If not, I suggest closing this issue. Experience tells me it's in the "will never be done" department.

**Comment by tschottdorf** [comment]
Closing, but reopen if you were actually planning on doing this soon
