### ISSUE TITLE
storage: clear abort span on non-poisoning, aborting EndTransaction request

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#29128]
Forked from https://github.com/cockroachdb/cockroach/pull/28799#issuecomment-414090586.

> Why isn't
>
> https://github.com/cockroachdb/cockroach/blob/f435f61bec59768ad54fe4ff5ae0028059b9bf08/pkg/storage/batcheval/cmd_end_transaction.go#L492-L497
>
> written as:
> 
> ```go
> if txn.Status == roachpb.ABORTED {
> 	if err := SetAbortSpan(ctx, evalCtx, batch, ms, txn.TxnMeta, args.Poison); err != nil {
> 		return nil, err
> 	}
> }
> ```
> 
> The effect of this is that we currently never remove abort span entries if they exist when the `TxnCoordSender` sends an `EndTransactionRequest(Commit=false)`. My understanding of `Poison` and its interaction with the `AbortSpan` is that it is safe to remove the entry when `Poison=false` because that implies an acknowlegement from the `TxnCoordSender` of the transaction's aborted disposition. I wonder if this has any implications on https://github.com/cockroachdb/cockroach/issues/25233.

Response from @tschottdorf:

> I think this comes (came?) down to a lack of trust in that TxnCoordSender was doing the right thing with respect to its "async aborts". Could a txn be aborted (unbeknownst to it) and dispatch a read (which needs to hit the abort span for correctness) that would be "passed" by an async abort but would still return its value to the client? If so, clearing the abort span from the async abort would let the read return something incorrect (i.e. not read what you wrote).
>
> I agree that we should revisit this and that it has a likely connection to #25233!

We should explore this further.

@tschottdorf for triage.

**Comment by tschottdorf** [comment]
@andreimatei can I leave this in your capable hands? It seems likely that this contributed to the large abort spans we've been seeing, and it would be good if we could convince ourselves that clearing is kosher.

**Comment by nvanbenschoten** [comment]
We seem to be hitting AbortSpan issues more and more these days. It's not clear that this would have helped avoid them, but it's also not clear that it wouldn't. I'm going to fix this.
