### ISSUE TITLE
opt,sql: decompose virtual tables to allow pushing down filters

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#29165]
Over the weekend @benesch and I had a discussion over how some virtual tables (`crdb_internal.ranges` in particular) are very slow because any query must accumulate the entire contents in order to process them. This has been brought up before but I wanted to document some options we discussed.

If we have a virtual table with a natural primary key, rather than have the virtual scan directly produce the entire table, we could have the virtual scan merely emit the primary key with a projection on top of it. This would allow us to prune projections that the caller doesn't use, and also push filters down below expensive projections.

In more complex cases, if we could express them as a decomposed join expressions, we could lean on the optimizer's existing ability to push down filters into joins to prevent computing unnecessary rows. How feasible and effective that is would probably depend on the structure of the table itself.

In the particular case of `crdb_internal.ranges`, it's not clear to me how we could cleanly decompose it, but I've heard anecdotally that it takes a very long time to run on a cluster of any size because many of the columns require talking to remote nodes. If those calls to remote nodes could be turned into projections and pruned and/or we could filter before computing them, that seems like it would be a big win.

This is related to #22504 but I suspect might be easier to implement, since it doesn't require generator code to interpret constraints (also related to but slightly different from #23052).

**Comment by knz** [comment]
@jordanlewis wasn't this addressed in #30478?

**Comment by jordanlewis** [comment]
No, we ended up closing that PR without merging it and implementing the vtable as a view. I'm not sure whether there's more work to be done here though -perhaps the approach of decomposing a vtable into a view is sufficient conceptually to solve all the problems here. Does @justinj want to weigh in?

**Comment by justinj** [comment]
Yeah, I think decomposing into a view is the superior approach in pretty much every situation here.

**Comment by RaduBerinde** [comment]
Closing this - we implemented virtual views for the problem of expensive columns. The problem of pushing down filters is tracked separately in #22504.
