### ISSUE TITLE
roachtest: enable logspy periodically on loaded clusters

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#29172]
Prevent regression of issues such as #29170.
If we can't trust that logspy doesn't crash running processes, we won't feel empowered to use it on production deployments.

**Comment by tbg** [comment]
Yes. High verbosity logging is often not exercised sufficiently in tests,
so it may panic and we want to catch that.

**Comment by jordanlewis** [comment]
We have a test for this: https://teamcity.cockroachdb.com/viewType.html?buildTypeId=Cockroach_Nightlies_SqlLogicTestHighVModuleNightly

But I just realized it isn't getting triggered nightly. Will fix.
