### ISSUE TITLE
schema changes: impossible error is happening: mutation already rolled back

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#29190]
Trolling a customer's logs, I see periodic
```
W180827 10:07:57.091015 112 sql/schema_changer.go:1202  [n2] Error executing schema change: mutation already rolled back: {0xc449fe6510 DELETE_AND_WRITE_ONLY ADD 4 true}
```

Code comments on the line producing the error say that it should never happen.

Btw, the printing of that mutation proto is pretty useless. We should put an `option (gogoproto.goproto_stringer) = false;` and write our own `String()`.

Ask me for logs.

**Comment by vivekmenezes** [comment]
this is happening because of #29200 , where the job is unable to update its progress because it has been marked FAILED. This results in a rollback job continuously failing when it attempts to update its progress and then printing this error.

Marking as closed because #29200 has been fixed.
