### ISSUE TITLE
clarify EncodedKey and RawKeyValue: move to storage/engine

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#2925]
`EncodedKey` is currently documented as `EncodedKey is an encoded key, distinguished from Key in that it is an encoded version`. `RawKeyValue` is documented as `RawKeyValue contains the raw bytes of the value for a key.` Neither bit of documentation is particularly insightful. 

Looking at the code, both of these types are tightly related to `storage/engine` and neither is used outside of the `storage` or `storage/engine` packages. I propose we move `{EncodedKey,RawKeyValue}` to `storage/engine` and rename to `{Key,KeyValue}` respectively. We'll then have the types `roachpb.{Key,KeyValue}` and `storage/engine.{Key,KeyValue}`.

**Comment by spencerkimball** [comment]
I'm happy moving it, but let's either call it either `EncodedKey` or `MVCCKey`. 
Also, let's make this a low priority.

**Comment by vladdy** [comment]
I'm working on this.

**Comment by tschottdorf** [comment]
:+1:
