### ISSUE TITLE
sql: RSG timeout with concurrent drop db (deadlock?)

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#29255]
Not sure if this is just TC being slow or if there's something more to it since looking though the stack traces in the TC output linked below, it looks like the only two running are the test runner waiting for result? There are lots of goroutines waiting on the db cache mutex though? also several on txn push. Hopefully someone more familiar with the code involved can tell from those stack traces if this looks alarming or not.

```
panic: timeout: "CREATE USER PLACEHOLDER WITH PASSWORD PLACEHOLDER".
currently executing: map[
CREATE USER PLACEHOLDER WITH PASSWORD PLACEHOLDER:1
ALTER SEQUENCE ONLY ident . MINVALUE RENAME TO BOOLEAN . VIRTUAL . DAY:1 
DROP DATABASE IF EXISTS ident RESTRICT:1 
CREATE USER 'string' PASSWORD RESTORE:1 
RESET CLUSTER SETTING EXPERIMENTAL_AUDIT . ident . HAVING . REAL . ident:1 
CREATE DATABASE IF NOT EXISTS ident:15
```

https://teamcity.cockroachdb.com/viewLog.html?buildId=867074&tab=buildResultsDiv&buildTypeId=Cockroach_Nightlies_NightlySuite

**Comment by vivekmenezes** [comment]
likely related to https://github.com/cockroachdb/cockroach/issues/29090

**Comment by dt** [comment]
Dupe #29090
