### ISSUE TITLE
storage: use gossip to avoid merging away restore/import's splits

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#29268]
Restore/import splits the keyspace and doesn't want the merge queue to merge these splits away. In the absence of "sticky bits" (and perhaps even after we introduce sticky bits) we want to let the merge queue know to respect these (temporary) splits.

The suggestion is for the restore/import job to regularly gossip a key whose value contains a key prefix on which merges are not to be carried out, with a relatively short TTL (minutes).

The merge queue looks out for these keys and will not attempt to merge two ranges when either is marked as protected.

**Comment by petermattis** [comment]
Looks like merging ranges causes import/restore to see Raft snapshots badness. The theory is that this is due to the rebalancing performed by the range merge queue. Regardless I’m going to implement this shortly.
