### ISSUE TITLE
make roachpb.Key.String() pretty-print keys

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#2928]
`roachpb.Key.String()` currently prints keys using `%q` (i.e. `strconv.Quote`), but keys are now self-describing based on their prefix. Showing the raw bytes of a key is not particularly friendly and we can do better. For example, for table data (keys that begin with `keys.TableDataPrefix`) we can use something equivalent to `sql.prettyKey()` to display a more human readable version.

Should be straightforward to address this issue, though it isn't particularly urgent.

**Comment by veteranlu** [comment]
let me try

**Comment by petermattis** [comment]
Working nicely.
