### ISSUE TITLE
importccl: IMPORT MYSQLDUMP failure for timestamp with default value

### ISSUE THREAD

**Issue by rolandcrosby** [cockroachdb/cockroach#29298]
Testing with [this MySQL dump file](https://raw.githubusercontent.com/bartektomas/mojanowa/a2076d8d4c52448c2274df4d7ffab771b4b57cba/backup.sql) I found on GitHub, CockroachDB gave me this error:

```
root@:26257/defaultdb> import mysqldump ('https://raw.githubusercontent.com/bartektomas/mojanowa/a2076d8d4c52448c2274df4d7ffab771b4b57cba/backup.sql');
pq: unsupported default expression for column "created_at": syntax error at or near "0"
```

The error message doesn't specify which table definition this occurred in (see #29297), but the file contains multiple table definitions that have a "created_at" column with a "0" in them, like this one:

```sql
DROP TABLE IF EXISTS `blogs`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `blogs` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `config` text COLLATE utf8_unicode_ci NOT NULL,
  `domain` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `updated_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`id`),
  KEY `blogs_user_id_foreign` (`user_id`),
  CONSTRAINT `blogs_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
```

**Comment by rolandcrosby** [comment]
as discussed at the bottom of the issue linked above, we don't/can't support this kind of datestamp in the first place, so in this case we should return a helpful error to that effect. The current error message I get when importing this file is `pq: could not parse "0000-00-00 00:00:00" as type timestamptz`, which is okay, but it'd be better to catch this explicitly and say we don't support zero dates.

**Comment by rolandcrosby** [comment]
Unfortunately, this particular value appears surprisingly prevalent in real-world MySQL databases. Notably, a clean installation of WordPress generates multiple tables with columns specified as `datetime NOT NULL DEFAULT '0000-00-00 00:00:00'`. 

[MySQL's documentation](https://dev.mysql.com/doc/refman/8.0/en/date-and-time-types.html) explains this value as follows:
> * MySQL permits you to store a “zero” value of '0000-00-00' as a “dummy date.” This is in some cases more convenient than using NULL values, and uses less data and index space. To disallow '0000-00-00', enable the NO_ZERO_DATE mode.

I'm a little leery of silently collapsing this strange null-ish value to null, and I also don't feel great about silently converting a NOT NULL column in the import data into a NULL column in CockroachDB. Maybe we could continue to return an error as we currently do, but offer to collapse the zero values to null (and change 'NOT NULL DEFAULT 0000-00-00' to 'NULL') if the user explicitly passes something like 'WITH mysql_conversion=null_zero_dates' in the IMPORT statement?

**Comment by rolandcrosby** [comment]
@dt and I just discussed this in person and settled on this plan:
- We will always convert date values that are zero (see table below) to NULL.
- For columns that specify one of these values as their default, we will change the column definition to DEFAULT NULL (even if the original column is defined as NOT NULL).
- We will continue to return an error when trying to parse MySQL date values like '2018-09-00' or '2018-00-00'.
- We won't provide any options to change this behavior; we'll just document that we perform these conversions, and tell users to edit the file they're importing if they really need to preserve some sentinel value distinct from NULL.

Here are the conversions to make (table taken from [MySQL's docs](https://dev.mysql.com/doc/refman/8.0/en/date-and-time-types.html)):

Data Type | “Zero” Value | CockroachDB Conversion
-- | -- | --
DATE | '0000-00-00' | NULL
TIME | '00:00:00' | '00:00:00'
DATETIME | '0000-00-00 00:00:00' | NULL
TIMESTAMP | '0000-00-00 00:00:00' | NULL
YEAR | 0000 | NULL

**Comment by dt** [comment]
fixed in 31288
