### ISSUE TITLE
HikariCP connection pool starves when connected through Google LoadBalancer

### ISSUE THREAD

**Issue by zvozin** [cockroachdb/cockroach#29293]
- Which version of CockroachDB are you using?
*2.0.5*

- What did you do?
*Default HikariCP connection pool config, 900 sec timeout on the Google Load Balancer.*

- What did you expect to see?
*Connections get reused.*

- What did you see instead?
*intermittent I/O and connection, and eventual connection starvation*

Would appreciate any advice in configuring Hikari and/or the LoadBalancer in such situation.

**Comment by zvozin** [comment]
With my sincerest apologies, the timeout is already 900 secs (I'm not sure what devil made my fingers type 30 secs when I first posted). Still not enough, though - turns out Hikari's `maxLifetime` default is 1800s. Will adjust Hikari settings and try again. Closing for now, will re-open if anything - thanks!

**Comment by a-robinson** [comment]
Thanks. If you find anything weird going on, I'd love to hear about it!

**Comment by drewdeally** [comment]
Also zvokin you tried the jdbc setting?  tpckeepalive=true JDBC
