### ISSUE TITLE
importccl: Where possible, IMPORT MYSQLDUMP should tell the user where it hit an error

### ISSUE THREAD

**Issue by rolandcrosby** [cockroachdb/cockroach#29297]
Currently, when `IMPORT MYSQLDUMP` hits an error, it doesn't tell the user where in the file the error occurred. According to @dt, this is kind of hard to solve in the general case with the parser library we're using, but there are some cases (like errors when parsing table definitions) that we can more easily identify. In these cases, we should tell the user which table definition was problematic or failed to parse.

**Comment by shermanCRL** [comment]
We’re doing as well as we can here, and don’t have concrete plans to improve it. Closing for now, happy to discuss.
