### ISSUE TITLE
importccl: IMPORT MYSQLDUMP fails with parse error

### ISSUE THREAD

**Issue by rolandcrosby** [cockroachdb/cockroach#29307]
Testing with [this MySQL dump file](https://raw.githubusercontent.com/ejbiva1/joblink/2fe2ccf91eb5307992d2c31931faabde9a9d695c/database/Dump20150621.sql) I found on GitHub, CockroachDB gave me this error:

```
root@:26257/defaultdb> import mysqldump ('https://raw.githubusercontent.com/ejbiva1/joblink/2fe2ccf91eb5307992d2c31931faabde9a9d695c/database/Dump20150621.sql');
pq: mysql parse error: syntax error at position 2533 near 'status'
```

I'm not sure what the issue is - position 2533 in the file is the space after "status" in this table definition, which otherwise looks fine and happily loads into MySQL:

```sql
/*Table structure for table 支付表*/
DROP TABLE IF EXISTS TB_PAYMENT;

CREATE TABLE TB_PAYMENT (
  ID VARCHAR(50) NOT NULL,
  PAYMENT_TYPE INT(11) NOT NULL COMMENT '支付类型: 1 面试; 2 培训; 3 下载简历',
  REFERENCE_ID VARCHAR(50) NOT NULL COMMENT '关联ID',
  PAYMENT_CHANNEL ENUM('wechat', 'alipay') NOT NULL COMMENT '支付渠道',
  PAYMENT_AMOUNT DECIMAL(5,2) NOT NULL COMMENT '金额',
  PAYMENT_USERID VARCHAR(50) NOT NULL COMMENT '支付人ID',
  SUBMIT_DATE DATETIME DEFAULT NULL COMMENT '提交订单日期时间',
  PAYMENT_DATE DATETIME DEFAULT NULL COMMENT '支付日期时间',
  STATUS INT(11) DEFAULT 0 COMMENT '状态  0 未支付  1 已支付',
  PRIMARY KEY (ID),
  UNIQUE KEY (PAYMENT_TYPE, REFERENCE_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='支付表';
```

**Comment by dt** [comment]
Okay, figured this one out: we don't support parsing index defs that don't have names. Started a fix: https://github.com/vitessio/vitess/pull/4166

**Comment by rolandcrosby** [comment]
Sounds good. mysqldump includes a [CLI option](https://dev.mysql.com/doc/refman/8.0/en/mysqldump.html#option_mysqldump_quote-names) to quote identifiers, so I'm fine telling people to just make sure that option is enabled.
