### ISSUE TITLE
importccl: IMPORT MYSQLDUMP fails with "possible unsupoprted type?"

### ISSUE THREAD

**Issue by rolandcrosby** [cockroachdb/cockroach#29305]
I started up a fresh WordPress/[CiviCRM](https://civicrm.org) server and performed a MySQL dump of all the available databases. I uploaded that dump file [here](https://gist.github.com/rolandcrosby/cee15f987b32c0984661b0036f07ac99). CockroachDB failed to import it with the following error:

```
root@:26257/defaultdb> import mysqldump ('https://gist.githubusercontent.com/rolandcrosby/cee15f987b32c0984661b0036f07ac99/raw/fe3e5f88fb43b5a4c989923e5a34c75c7eedd3ab/wordpress_civicrm_dump.sql');
pq: could not read definition for table "columns_priv" (possible unsupoprted type?)
```

Granted, this is an internal MySQL table that it's failing on, but I don't see anything in the table definition that we wouldn't want to support:

```sql

DROP TABLE IF EXISTS `columns_priv`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `columns_priv` (
  `Host` char(60) COLLATE utf8_bin NOT NULL DEFAULT '',
  `Db` char(64) COLLATE utf8_bin NOT NULL DEFAULT '',
  `User` char(80) COLLATE utf8_bin NOT NULL DEFAULT '',
  `Table_name` char(64) COLLATE utf8_bin NOT NULL DEFAULT '',
  `Column_name` char(64) COLLATE utf8_bin NOT NULL DEFAULT '',
  `Timestamp` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `Column_priv` set('Select','Insert','Update','References') CHARACTER SET utf8 NOT NULL DEFAULT '',
  PRIMARY KEY (`Host`,`Db`,`User`,`Table_name`,`Column_name`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='Column privileges';
/*!40101 SET character_set_client = @saved_cs_client */;
```

Also, regardless of what the root cause is here, we should fix the typo in "unsupoprted".

Epic CRDB-8816

Jira issue: CRDB-4873

**Comment by dt** [comment]
If I had to guess, `COLLATE utf8_bin` is not supported in our parser so it is hitting a syntax error, but I haven't verified that yet.

**Comment by dt** [comment]
so `set` *is* unsupported, but that isn't where this is failing -- there's currently a syntax error parsing the default of `current_timestamp()` -- mysql defaults aren't arbitrary expressions, just constants, with a special-case in the parser for `current_timestamp` but that special case didn't allow `()` after.  Extending the parser to allow that then hits the (expected) `set not supported` error.

**Comment by mjibson** [comment]
This has some other things also unsupported:

- `timestamp(6)` specifies microsecond precision (in the `general_log` table)
- `ON UPDATE`

**Comment by dt** [comment]
Just tried `IMPORT MYSQLDUMP 'https://gist.githubusercontent.com/rolandcrosby/cee15f987b32c0984661b0036f07ac99/raw/fe3e5f88fb43b5a4c989923e5a34c75c7eedd3ab/wordpress_civicrm_dump.sql'` and it now fails with a nicer message about SET.
