### ISSUE TITLE
ui: Clicking the logout icon with my username initial does not log me out

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#29310]
Clicking the logout icon doesn't log me out of the cluster. I have to click on the words "log out":

![image](https://user-images.githubusercontent.com/21692034/44815813-8ba05580-abae-11e8-9b4b-50861f8fd2bd.png)

**Comment by piyush-singh** [comment]
@josueeee can you drop your updated design here?

**Comment by vilterp** [comment]
This was fixed by #31218
