### ISSUE TITLE
roachtest: run a subset of tests on aws

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#29334]
We should run a subset of the nightly roachtests on aws (in addition to running these same tests on gce). This will give us additional exposure to aws which is a frequent deployment target for users. 

As an initial subset, I propose the `kv{0,95}/*` tests and the `ycsb/*` tests. These are all very basic tests, but also ones that produce interesting performance numbers that we can use to compare against the same numbers generated on gce.

I think most of the pieces are in place for doing this. `roachprod` can create clusters on aws if credentials are setup. The remaining bits are to figure out if anything is missing from running roachtests on aws (perhaps some flags to specify using aws) and setting up a teamcity config with the appropriate aws credentials.

**Comment by petermattis** [comment]
@jordanlewis or @benesch Can one of you set up a new teamcity config that is a duplicate of the `Roachtest nightly` but uses the new `--cloud=aws` flag? I think we'll want to start with a subset of tests. For example, `kv(0|95)/`. Easy enough to tweak that once it is running reliably. I'd be willing to learn how to fish here, though next week is super busy for me.

**Comment by benesch** [comment]
The steps look something like this, Peter. Copy the config in TeamCity by navigating to "Roachtest Nightly" > Edit Configuration Settings > Actions dropdown > Copy configuration. Let's say you call it "Roachtest Nightly — AWS." Edit the new build config script to pass the right roachtest args to run kv on AWS. (Perhaps also update the build config script to mention the terrible about of duplication.) Then update the Nightly Suite job to depend on not just "Roachtest" Nightly but also "Roachtest Nightly — AWS."

**Comment by benesch** [comment]
I can take care of this later today if you don't beat me to it.

**Comment by petermattis** [comment]
Ack. Do we have AWS credentials set up on teamcity?

**Comment by benesch** [comment]
Whatever publishes S3 binaries has credentials for the binaries bucket. Not
sure if those are what you need.

**Comment by petermattis** [comment]
I'm taking a stab at this.

**Comment by petermattis** [comment]
Ok, I think I have this done. It looks like copying the build configuration automatically added the copy to the `Nightly` suite. Can you or @jordanlewis confirm that?

**Comment by benesch** [comment]
Are you sure you're looking in the right place? It's part of the "Nightlies" project, but it's not part of the "Snapshot Dependencies" of the "Nightly Suite" build: https://teamcity.cockroachdb.com/admin/editDependencies.html?id=buildType:Cockroach_Nightlies_NightlySuite. TC organization works like Go organization. The hierarchy of build projects has absolutely no bearing on the dependencies of the constituent builds, just like directory hierarchies have no bearing on the dependences of the packages within.

**Comment by benesch** [comment]
Everything else looks good, except that I'm not seeing where you're providing the build with AWS reds.

**Comment by petermattis** [comment]
I believe everything is hooked up now on teamcity, though the version of `aws` in the builder image is too old. See #31412.
