### ISSUE TITLE
sql: prevent schema change operations on system tables

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#2937]
We currently can't change the schema of system tables, so we should enforce that any schema change operation on a system table returns an error.

**Comment by mberhault** [comment]
All system tables have `CREATE` privileges prohibited:
```
  // SystemAllowedPrivileges describes the privileges allowed for each
  // system object. No user may have more than those privileges, and
  // the root user must have exactly those privileges.
  // CREATE|DROP|ALL should always be denied.
  SystemAllowedPrivileges = map[ID]privilege.List{
    keys.SystemDatabaseID:  privilege.ReadData,
    keys.NamespaceTableID:  privilege.ReadData,
    keys.DescriptorTableID: privilege.ReadData,
    keys.LeaseTableID:      privilege.ReadWriteData,
    keys.UsersTableID:      privilege.ReadWriteData,
    keys.ZonesTableID:      privilege.ReadWriteData,
  }
```

As long as schema changes require `CREATE` (they should, since it's the same privilege as creating a schema), we should be fine.

**Comment by petermattis** [comment]
Ok. Perhaps all that needs to be done is testing.

**Comment by mberhault** [comment]
There doesn't appear to be any testing of schema changes to system tables. We test privilege enforcement on system objects, and test schema changes (may not be comprehensive) with/without the correct privileges. We just don't check the combination.
I'll add those.

**Comment by petermattis** [comment]
@jordanlewis Was this ever done?

**Comment by jordanlewis** [comment]
First time I'm seeing this - I'll have a look.

**Comment by jordanlewis** [comment]
This is done.
