### ISSUE TITLE
Persist known gossip members to local disk.

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#2938]
Once a node is connected to gossip and has a clusterID, we should persist some or all discovered node addresses to local disk. The list of stored nodes would augment the `--gossip` command-line flag. It does not need to be complete, or up-to-date (ie: long-dead nodes are ok, although we may want some basic ttl to remove old entries).

This would tremendously simplify deployment, removing the need for load-balancer or dns round-robin for node discovery. This does not address discovery methods for clients.
A simple deployment strategy would become:
1) first node is initialized and started with itself as the gossip address
2) node N is started with `--gossip` containing the addresses of nodes `0` through `N-1`

All nodes joining gossip save discovered node addresses to local disk. If the entire cluster is restarted (and most addresses are still valid), the three nodes holding the sentinel should be sufficient to get everyone to join gossip.
The case of the first node is particularly important. As long as some other node in the gossip network connects to it, it will properly join the gossip network.

Storage options:
* rocksdb: easy to do and already structured.
* plain file (json or even plain text): adds custom logic to load/save, but would allow admins to specify their own list of nodes, or modify the existing list if re-addressing nodes, all without custom tools
* both: use rocksdb for our own tracking, but add a local-file resolver that admins can use on the command-line.

Assumptions to double-check:
* make sure the gossip server starts listening as long as we know the cluster ID
* make sure nodes that receive gossip messages join gossip properly, even if all their addresses failed

**Comment by knz** [comment]
Fixed by #3711.
