### ISSUE TITLE
trace: hook log tags up to tracing span tags

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#29401]
We use log tags extensively to add semi-structured information to logs. These tags are attached to contexts, which allow them to propagate through call stacks. It is possible to add log tags to contexts manually using `WithLogTag` functions. It's also possible to add logs tags to each context passing through a component using the `AmbientContext` infrastructure.

Opentracing also has the notion of "tags" which live on `Span`s. These tags are queriable by a number of tracing systems, including Jaeger. We should hook up our log tags to tracing tags when tracing is enabled. This will improve our ability to quicky weed through spans and find those that are interesting.

This is related to the following TODO:

https://github.com/cockroachdb/cockroach/blob/9c59730ad7d792c783fe5613db2cbf1eef0ed9c4/pkg/util/log/trace.go#L129-L130

It's possible that I'm misunderstanding some subtlety in the difference between opentracing "fields" vs "tags" and that our log tags actually map to opentracing fields.

**Comment by RaduBerinde** [comment]
On fields vs tags:
 - the tags are a property of the entire span; each tag can have a single value
 - the fields (mentioned in that TODO) are associated with each message; they are a more structured way of emitting a message. I think we should definitely make each log tag a field, provided it gets rendered in an acceptable way in whatever UI we care about.

The log tags are associated with each message, and in principle the log tags can vary between messages in the same span (and most definitely for messages inside child spans). So there is a bit of an impedance mismatch between the log tags and the span tags.

That said, I think it would work well to record the log tags in the context at span creation time as the span tags. This should be straightforward, other than plumbing a context to all `StartSpan` calls.

**Comment by RaduBerinde** [comment]
I filed a separate issue for using fields for tags (instead of a single "event" field). That change has non-trivial repercussions on the session tracing code so I targeted it for 2.2.

**Comment by RaduBerinde** [comment]
Fixed by #30062.
