### ISSUE TITLE
Support Infinity and NaN

### ISSUE THREAD

**Issue by jmank88** [cockroachdb/cockroach#2943]
From a discussion in #2332

Scanner should support parsing [+-]Inf{,inity} and NaN.

These values can currently be calculated from float expressions and are printed by strconv.PrintFloat() as +Inf/-Inf and NaN. Is this acceptable output? Or would the postgres compatible Infinity/-Infinity be preferred?

**Comment by jmank88** [comment]
I can take a shot, if someone in the know thinks this is easy/helpwanted worthy.

**Comment by petermattis** [comment]
Go for it. Definitely worth doing and it should be straightforward. I think we should support both `{+,-,}{Inf,Infinity}`.
