### ISSUE TITLE
59 second response time to create 2 tables + indexes in 6-node cluster

### ISSUE THREAD

**Issue by rbastic** [cockroachdb/cockroach#29468]
Is this a bug report or a feature request?

Bug report? I think.

**BUG REPORT**

Please describe the issue you observed, and any steps we can take to reproduce it:
Created small cluster, loaded star trek database (observed reasonable performance.)

Went to create additional database and CREATE TABLE, CREATE INDEX for 2 tables. Observed long CREATE TABLE/CREATE INDEX time.

- Which version of CockroachDB are you using?
2.0.5 (latest)

- What did you do?
Created six nodes (1 VCPU, 3.75GB RAM) in Google Cloud Platform.

6 availability zones, 2 overall zones (3 machines in us-east1, 1 each in c, b, d, 3 machines in us-west2, 1 each in b, c, a).

So, in other words, 2 instance groups, with minimally sized instances, 3 per instance group.

- What did you expect to see?

Faster CREATE TABLE / CREATE INDEX response time than I saw

- What did you see instead?

Very slow (59 seconds response time). I realize this is a contrived, potentially very slow setup due to the minimalistic hardware configuration.

However, given the speeds I saw on the Star Trek test, (5ms and under for 99.9% of everything), I wouldn't have expected this to be so long. The CREATE TABLE time on the star trek test appeared to be <500ms.

Here is the SQL:

[lag.txt](https://github.com/cockroachdb/cockroach/files/2342671/lag.txt)

Please note I love what I see so far, and would love to build a number of applications around this DB. 

Hoping that this is fixable! Keep up the great work.

**Comment by rbastic** [comment]
note: nodes are configured with SSL off, btw.

**Comment by vivekmenezes** [comment]
@rbastic looks like you're creating an index on an empty table. This should happen very quickly. What you are seeing is highly unlikely. Are you able to reproduce this?

The only situation under which this can happen is if you shutdown the session in the middle of creating the index, which will result in an asynchronous process kicking in and running the index change. But I highly doubt that is what you are seeing.

**Comment by rbastic** [comment]
Hi,

Yes. I was able to reproduce this today. I've written some instructions and attached a Perl installer script that will help create a reproducible environment in GCP for you. I'm sorry this is all a bit painful to describe, my personal test setup is a bit cumbersome at the moment.

[install-roach.txt](https://github.com/cockroachdb/cockroach/files/2354752/install-roach.txt)

The steps to utilize this are as follows (i can reproduce this with the free tier):

1) Create a control node with SSH keys, so that any other nodes you create in the same VPC can easily be ssh'd into.

2) Copy the install-roach.pl there. I used Ubuntu for the provisioning node but CentOS should work also.

2) Create an instance template for CentOS with 1 VCPU and 3.75GB RAM. 10GB boot disk.

3) Create 2 instance groups, 1 in US-east-1, another in US-west-2. 3 instances each, using the above instance template. Disable autoscaling.

4) Create .ssh/config entries in your control node, like so:

``
Host db1
    HostName 10.142.0.3
    IdentityFile /home/ryan/.ssh/arcadia.key

Host db2
    HostName 10.142.0.4
    IdentityFile /home/ryan/.ssh/arcadia.key

Host db3
    HostName 10.142.0.5
    IdentityFile /home/ryan/.ssh/arcadia.key
``

Including the entries for db4, 5, and 6. Make sure all IP addresses match.

5) Edit the installer so that it has the correct IP addresses. If you used the regions I suggested, they should all be already correct.

6) ssh db1, ssh db2, etc., prompting yes each time, for all potential hosts.

7) Note in the installer code that I am joining all nodes to the first node in the cluster.

Now if you run:
DRY_RUN perl install-roach.pl
it should all look fairly reasonable
and then running
perl install-roach.pl
should boot the whole cluster.

8) The above can be verified by adding an HTTP firewall rule and accessing http://{public_ip}:8080/ on one of the ports, as you'd expect

I've now reproduced this in two scenarios, a completely fresh cluster, and the original situation where I realize now, I had provisioned 6 nodes, added a 7th, killed the first, and so on. It does reproduce reliably now though.

9) Then:
ssh db1
cockroach sql --insecure

Then paste the original SQL file into the console in it's entirety, and watch it hang for 59 seconds.

**Comment by rbastic** [comment]
Please note that I have retested on the latest beta:

` 
CREATE TABLE

Time: 142.80639ms


CREATE INDEX

Time: 1.952011793s

CREATE INDEX

Time: 2.230952034s

CREATE TABLE

Time: 142.74247ms

CREATE INDEX

Time: 1.929706397s

CREATE INDEX

Time: 2.105455575s

root@:26257/lag> 
root@:26257/lag> 
`

Very nice. Great work! Will close.
