### ISSUE TITLE
cockroachdb daemon use much network (cluster are idle)

### ISSUE THREAD

**Issue by kocoten1992** [cockroachdb/cockroach#29462]
Hi, guys

Cockroachdb deamon use more network traffic than expected when there are no write or read to them.

Example:
```nethogs``` gave me:
```
   PID USER     PROGRAM                                              DEV        SENT      RECEIVED       
   3725 root     /usr/local/bin/cockroach                             eno1       46.282      91.735 KB/sec
  23459 root     ndb_mgmd                                             eno1       14.454      15.260 KB/sec
  21077 mysql    /usr/sbin/mysqld                                     eno1        2.755       4.338 KB/sec
```

It not relevant but I've include mysql cluster here for comparision, sent/received on cockroachdb steadily 40-60KB/s , and often spike to 400-600KB/s, while mysql cluster always 14-18 KB/s. Both cluster are idle (no write or read to them).

P/s: I'm using most latest version cockroachdb (build from master)

**Comment by a-robinson** [comment]
Hi @kocoten1992, thanks for the report. Is the cockroachdb process part of a multi-node cluster or is it just running as a 1-node cluster? Roughly how much data is in it?

It's not unexpected that cockroach is using the network more than mysql, but this is something we could potentially look at during future development.

**Comment by kocoten1992** [comment]
I've set up multi-node cluster of 5, virtually no data in it (less than 100kb) and it is idle,

Sometime it burst up to 150KB/s for no reason, sometime I've seen 400KB+ , at worse it going up to 1MB/s (for no reason)

Also I've set up a jenkins job to auto git pull, build and push up to 5 server every 24h (to experiment), interesting stuff happen:

```
- Jenkins git pull, build, push to 5 server
- ssh remote to server 1
- service cockroachdb restart, wait for cockroachdb successfully restart
- ssh remote to server 2
- service cockroachdb restart, wait for cockroachdb successfully restart
- ssh remote to server 3
...
```
When each server restart, the network is going haywire (it push up to 1-2 MB/s network for entire cluster - each server)

This behavior doesn't happen when just simply use ```service cockroachdb restart```
