### ISSUE TITLE
importccl: IMPORT PGDUMP should ignore schema manipulation statements

### ISSUE THREAD

**Issue by rolandcrosby** [cockroachdb/cockroach#29471]
@arjunravinarayan pointed out that IMPORT PGDUMP currently fails on CREATE SCHEMA statements in pgdump input. An example pgdump that causes import problems is [here](https://gist.github.com/rolandcrosby/1a1925dda58d0a5781bc7b919ac53ebc). Cockroach produces the following error:

```
root@:26257/defaultdb> import pgdump ('https://gist.githubusercontent.com/rolandcrosby/1a1925dda58d0a5781bc7b919ac53ebc/raw/a944abc788f7c902a211b1bd8af5ad6b81f17e0d/createschema.sql');
pq: postgres parse error: syntax error at or near "schema": (

--
-- Name: foo; Type: SCHEMA; Schema: -; Owner: roland
--

CREATE SCHEMA foo;)
```

[CockroachDB doesn't support custom schemas](https://www.cockroachlabs.com/docs/v2.1/sql-name-resolution.html#logical-schemas-and-namespaces) at all.

To get around the issue that Arjun encountered, CockroachDB should ignore `CREATE SCHEMA`, `ALTER SCHEMA`, and `DROP SCHEMA` statements when importing a pgdump. Ignoring these statements shouldn't otherwise affect our ability to import the table data from a pgdump file, since we'll still properly parse the schema and table names in `CREATE TABLE` and `COPY` statements.

**Comment by rolandcrosby** [comment]
Note that this change won't allow us to import pgdumps that contain data from non-public schemas -- if you just run `CREATE TABLE foo.bar` you'll get the accurate error message `pq: non-public schemas unsupported: foo`. Because CockroachDB doesn't support non-public schemas, if we wanted to support importing that kind of data, we'd have to do something like mangle the schema and table names together. I'll track that work separately since it necessitates a bit more thinking about how to represent the name, how/where to tell the user what names were changed, etc.

**Comment by mjibson** [comment]
Even if we ignore those statements the import will fail: `non-public schemas unsupported: foo` when it gets to the CREATE TABLE statement. I'm not sure we need to do anything here, at least for 2.1.

**Comment by rolandcrosby** [comment]
Let's disregard this for 2.1 and revisit as part of the 2.2 import work. I'm considering a feature that allows users to specify which tables in a dump file they want to import, and this might make sense to bring in at that point.

**Comment by mjibson** [comment]
We already allow users to specify which tables in a dump they want to import, do we not?

**Comment by rolandcrosby** [comment]
We allow users to specify a single table at a time, which is problematic when there are foreign keys and related tables that need to come in at once.

**Comment by mjibson** [comment]
Yes, that is a known issue. The two solutions are: 1) support importing multiple specified tables, 2) add a WITH option to ignore foreign key constraints (RESTORE can do this).

**Comment by shermanCRL** [comment]
We consider this fixed, for schemas defined in the same pgdump. (For schemas outside the file, we don’t support it.)
