### ISSUE TITLE
roachtest: move cmd/zerosum to a roachtest

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#29486]
Title says it all. `cmd/zerosum` predates the roachtest infrastructure. This test is still interesting because it performs a variety of chaos (splits, lease transfers, node kills) while verifying the consistency of table data.

**Comment by petermattis** [comment]
This also might involve adding a `zerosum` workload. I haven't thought it through fully. Let me know if you need more of a brain dump on what I'm thinking here.

**Comment by m-schneider** [comment]
It looks like I'd need to port the existing code to a workload and add a roachtest with some test specs? Is that what you're thinking?

**Comment by petermattis** [comment]
Yes. The complexity is that `cmd/zerosum` generates not only load, but also performs chaos. That chaos is best performed by the roachtest, though I haven't taken a look at `zerosum` recently to know if we have all of the correct hooks. `zerosum` was written at a time before support was add to SQL for performing replica and leases movement, so perhaps the hooks are all present now. Note that `zerosum` itself is more or less the bank workload. It is possible that a new workload doesn't need to be added but simply a flag to the `bank` workload. The chaos and consistency checks are the more interesting parts here.

**Comment by m-schneider** [comment]
Ok that makes sense, so I need to add the monkey function with SQL hooks for splitting ranges and transferring leases, floppy chaos and consistency checks to the bank workload.

**Comment by petermattis** [comment]
Yeah, well that's the part I'm not sure of. The monkey stuff seems like it belongs in roachtest code, not workload. I suppose it isn't too bad to have a roachtest which has intimate knowledge of the workload's schema.

**Comment by m-schneider** [comment]
Ok, do you think money would be useful as a library vs a part of the bank roachtest?

**Comment by petermattis** [comment]
That feels like overkill in order for a roachtest to know a workload
schema. We already have prior art where roachtests have intimate knowledge
of workloads.
