### ISSUE TITLE
cli/dump: failing to dump string array column

### ISSUE THREAD

**Issue by joeledstrom** [cockroachdb/cockroach#29485]
**BUG REPORT**

Please describe the issue you observed, and any steps we can take to reproduce it:

- Which version of CockroachDB are you using?
2.0.5
- What did you do?
Trying to dump our main database with `cockroach dump --insecure --host [server] [database]`
- What did you expect to see?
A Working db dump being outputted. The same command works for our secondary database hosted in the same three node healthy cockroach cluster. 
- What did you see instead?
It starts outputting parts of the dump, then stop with the following error.
    ```
    Error: unexpected column type STRING(12)
    Failed running "dump"
    ```
- What was the impact?
Can't dump one of our databases

Not sure if this is a known issue with 2.0.5?

If not, I will and try to reproduce it various ways: fresh database, other crdb versions etc.

**Comment by mjibson** [comment]
I just downloaded the 2.0.5 binary, started it up, made a new database, table, and inserted a row. Then I ran dump and it output:

```
./cockroach dump --insecure d
CREATE TABLE t (
        s STRING(12) NULL,
        FAMILY "primary" (s, rowid)
);

INSERT INTO t (s) VALUES
        ('aoeu');
```

which is exactly what I would expect to see. Can you provide the output of `SHOW CREATE TABLE t` where `t` is the name of the table? Another thing to verify is that the server binary and the binary on your CLI are exactly the same. Dump changes over time and sometimes if the client and server aren't the same unexpected things can happen.

**Comment by joeledstrom** [comment]
Okay I'm sorry for a bit of a bad bug report from the beginning. Yes I was using the same versions of both server and CLI. 

I think I've isolated the issue. Apparently its related to string-arrays of fixed length. Doesn't have to be 12 chars.

I can reproduce it using:
```
CREATE TABLE t (
        s STRING(12)[] NULL,
        FAMILY "primary" (s, rowid)
);

INSERT INTO t (s) VALUES
        ('{"aoeu"}'::string[]);
```

**Comment by mjibson** [comment]
This works correctly in our upcoming 2.1 branch. It is unfortunate that you can't use a 2.1 client binary with a 2.0 server with dump, so there's not a simple workaround here.

@knz I think you fixed this in https://github.com/cockroachdb/cockroach/commit/2363d4403aaa43d39dd8b17373851135006adb11#diff-57fbab5a71a2e66e38932592db7fbb9b. I'm not sure if we want to backport that change to the 2.0 branch or not.

**Comment by knz** [comment]
I'd be good backporting that specific PR, it looks like a backward-compatible solution.

**Comment by piyush-singh** [comment]
Will probably not backport this for 2.0 at this point.
