### ISSUE TITLE
sql: incorrect handling of string[] fields when using python connectors

### ISSUE THREAD

**Issue by leofiore** [cockroachdb/cockroach#29483]
cockroachdb 2.0.5 on docker, 5 nodes running in 3 different datacenters.

the same passages can be repeated on CRDB and postgresql in order to compare the output:

* create a table `test (key char(20) primary key, value text[])`

* use a python script to load some values. Most importantly, at least a value should be an array of strings containing at least an element, which contains at least a line feed (\n) charachters in any position of the string.

* use a python script to retrieve the complete `value` array, using `SELECT value FROM test WHERE key = '_somekey_'`

* use a python script to retrieve the single array element of `value` containing the line feed character, using  `SELECT value[_number_] FROM test WHERE key = '_somekey_'`

* repeat the test on postgresql for comparison

**Expected result:** the line feed character is handled correctly and, when `print()`ed, the string is splitted in 2 and the '\n' char is invisible. This is the behaviour using any python connector with postgresql

**Actual result**: using psycopg2, or PyGreSQL, or psycopg2cffi to retrieve the string on CRDB, the line feed character is displayed as 'n', the '\\' char is deleted. Using pg8000 to retrieve the string on CRDB, the result is correct. Using all of the connectors to retrieve only the element of the array containing the line feed, the string is handled correctly. 

[This is the code](https://github.com/cockroachdb/cockroach/files/2345789/pgtest.py.txt) i used to test the libraries. requires the installation of pg8000, psycopg2, psycopg2cffi, PyGreSQL. i tested the script using postgresql 9.3 on docker and CRDB 2.0.5 on docker. The output results:

**Postgresql:**
```
---------------
test line
test line 2
test line
test line 2
---------------
test line
test line 2
test line
test line 2
---------------
test line
test line 2
test line
test line 2
---------------
test line
test line 2
test line
test line 2
```
**CRDB:**
```
---------------
test line
test line 2
test line
test line 2
---------------
test linentest line 2
test linentest line 2
---------------
test linentest line 2
test linentest line 2
---------------
test linentest line 2
test linentest line 2
```

**Comment by leofiore** [comment]
adding some more comments: it is worth noting that the only pure python implementation is pg8000. psycopg2, psycopg2cffi and pygresql relies on the official libpsql library, those are made by a python layer and a C binding on top of the psql library.

However, it looks to me this is not a problem affecting the libpsql library, because:

* querying the database using the classic psql standard obtains the correct values

* building the connectors on top of several distributions (ubuntu, debian) and an alpine container provides the same weird behaviour

**Comment by justinj** [comment]
Hi @leofiore! Thanks for the detailed bug report, it's very much appreciated! I've opened #29558 which should fix this problem.
