### ISSUE TITLE
sql: use the same version of table descriptor for the lifetime of a transaction

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#2948]
The [table descriptor lease](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/table_descriptor_lease.md) mechanism as currently implemented guarantees that the same version of the table is used for the lifetime of a single SQL operation, but different operations within a single transaction can see different versions of the table. A transaction which requires the table version to be unchanging across individual operations seems like it would run afoul of a concurrent schema modification in any case. For example, a `SELECT *` will retrieve any unknown number of columns if a concurrent add/drop column operation occurs. But even if it is safe for the version to be changing within a transaction, it violates the principle of lease surprise for the user.

The table descriptor lease RFC talks about keeping track of which version of a table is used within a transaction and not letting the version change across operations. This is mildly complicated: we have to store the versions in the session transaction object and not release local leases for versions on uncommitted transactions. Marking this as a 1.0 issue because it doesn't seem urgent to address yet we will likely want to address it at some point.

**Comment by tamird** [comment]
Cross-linking #7508.

**Comment by spencerkimball** [comment]
@vivekmenezes @tamird @knz Yikes, is this not the case during a single txn? I'm assigning this to @vivekmenezes to re-assign and prioritize as necessary.

**Comment by vivekmenezes** [comment]
As described in the report, we do use a lease for a stmt, but across statements a close to expiring lease can be released and another lease acquired with the expectation that it is a new lease with the same version. See ```sql.removeLeaseIfExpiring``` . This can easily be fixed to check that the versions are the same but I suspect the tests will prolong the fix. But nonetheless worth putting into 1.0

**Comment by vivekmenezes** [comment]
this is turning into a bigger change than I expected. I'm moving this to 1.1

**Comment by vivekmenezes** [comment]
Closing this issue because we now use the same version of a table descriptor during a transaction and hold the version in a ```TableCollection``` object for the life of a transaction. This is tested by TestTxnObeysTableModificationTime
