### ISSUE TITLE
sql: `UPDATE RETURNING` can return mutation columns

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#29494]
SQL is never allowed to show mutation columns to the user, but `UPDATE RETURNING` allows this:

```
root@:26257/defaultdb> show create table b;
+------------+-----------------------------------------------+
| table_name |               create_statement                |
+------------+-----------------------------------------------+
| b          | CREATE TABLE b (                              |
|            |                                               |
|            |     a INT NOT NULL,                           |
|            |                                               |
|            |     b INT NOT NULL DEFAULT 1:::INT,           |
|            |                                               |
|            |     CONSTRAINT "primary" PRIMARY KEY (a ASC), |
|            |                                               |
|            |     FAMILY "primary" (a, b)                   |
|            |                                               |
|            | )                                             |
+------------+-----------------------------------------------+
(1 row)

Time: 5.947ms

root@:26257/defaultdb> update b set b=-2 where a=-2 returning c;
+---+
| c |
+---+
| 1 |
+---+
(1 row)

Time: 9.762ms
```

To produce this state, I added a new column `c` and restarted the server before the backfill could complete.

**Comment by jordanlewis** [comment]
There's an easy fix for this, will have it soon.

**Comment by knz** [comment]
no need to restart the server, doing the things within an explicit begin..commit block will cause the same problem. I'm looking

**Comment by knz** [comment]
Wait what? Why? You can't just say something like that without providing an explanation or a link.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by vivekmenezes** [comment]
I'll try and fix the underlying issue but I can't promise. Fixing panics
are a top priority.

**Comment by vivekmenezes** [comment]
Since the customer has a workaround I think it is okay to not revert the fix for this issue. I'll work on a fix to the panic in a way that doesn't break this issue. Closing.
