### ISSUE TITLE
sql: CREATE TABLE using a name that has been recently dropped but still in use should return a better error

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#29490]
```
root@:26257/defaultdb> drop table a;
pq: relation "a" does not exist
root@:26257/defaultdb> create table a (a int primary key);
pq: relation "a" already exists
```

I got into this state with the following sequence:

1. create a
2. bunch of schema changes on a
3. alter table a add column ...
4. drop table a (this hung)
5. kill server
6. restart server
7. the above command line transcript happened.

LMK if you need help reproducing...

**Comment by clanstyles** [comment]
I'm having this bug too.

**Comment by vivekmenezes** [comment]
The error here should look something like ```relation "a" still in use for dropped table; waiting for GC to occur```

**Comment by jordanlewis** [comment]
I think this is fixed now.
