### ISSUE TITLE
ui: hardware dashboard: add tooltips

### ISSUE THREAD

**Issue by vilterp** [cockroachdb/cockroach#29525]
Add descriptive tooltips to each graph in the Hardware Metrics dashboard. Should also update docs to match them. (And maybe link to the docs page on this dashboard…? cc @Amruta-Ranade)

**Comment by Amruta-Ranade** [comment]
Yes..however, I haven't documented the new graphs yet. Will get to it asap.

**Comment by vilterp** [comment]
I think we've settled on the final set. If anything read/write time and IOPS per second would be removed, but probably not.

**Comment by Amruta-Ranade** [comment]
@vilterp I need help understanding the new graphs.

**Comment by piyush-singh** [comment]
cc @couchand

**Comment by vilterp** [comment]
Thanks for writing these @piyush-singh!
