### ISSUE TITLE
sql: insert into tbl values (...) slower than insert into tbl (a,b,c) values (...)

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/cockroach#29532]
**BUG REPORT**

Please describe the issue you observed, and any steps we can take to reproduce it:

tried [oltpbenchmark](https://github.com/oltpbenchmark/oltpbench)      
in src/com/oltpbenchmark/types/DatabaseType.java, the 3rd column controls whether the column names are used in the insert.  Examples shown:

- COCKROACHDB("org.postgresql.Driver", false, false, true) produces
INSERT INTO item VALUES ($1, $2, __more3__), (__more100__)
INSERT INTO stock VALUES ($1, $2, __more10__), (__more100__)

- COCKROACHDB("org.postgresql.Driver", false, true, true) produces
INSERT INTO item(i_id, i_name, i_price, i_data, i_im_id) VALUES ($1, $2, __more3__), (__more100__)
INSERT INTO stock(s_w_id, s_i_id, s_quantity, s_ytd, s_order_cnt, s_remote_cnt, s_data, s_dist_01, s_dist_02, s_dist_03, s_dist_04, s_dist_05, s_dist_06, s_dist_07, s_dist_08, s_dist_09, s_dist_10) VALUES ($1, $2, __more10__), (__more100__)

- Which version of CockroachDB are you using?

v2.1.0-beta.20180827

- What did you do?

node_statement_statistics available at 

https://docs.google.com/spreadsheets/d/1jqrN1-QahDC7jTRaALTH8X8W-yWCCUdaK_g3hKPQl7Y/edit?usp=sharing

- What did you expect to see?

Stock table is significantly faster (more than 100,000x faster )with INSERT INTO stock(s_w_id, s_i_id, s_quantity, s_ytd, s_order_cnt, s_remote_cnt, s_data, s_dist_01, s_dist_02, s_dist_03, s_dist_04, s_dist_05, s_dist_06, s_dist_07, s_dist_08, s_dist_09, s_dist_10) VALUES ($1, $2, __more10__), (__more100__)

Item table is faster (2 to 4x faster) with INSERT INTO item(i_id, i_name, i_price, i_data, i_im_id) VALUES ($1, $2, __more3__), (__more100__)

- What did you see instead?

- What was the impact?

Schema below:

```
create table warehouse (
  w_id        integer   not null,
  w_ytd       decimal(12,2),
  w_tax       decimal(4,4),
  w_name      varchar(10),
  w_street_1  varchar(20),
  w_street_2  varchar(20),
  w_city      varchar(20),
  w_state     char(2),
  w_zip       char(9),
  constraint pk_warehouse primary key (w_id)
);

create table district (
  d_w_id       integer       not null,
  d_id         integer       not null,
  d_ytd        decimal(12,2),
  d_tax        decimal(4,4),
  d_next_o_id  integer,
  d_name       varchar(10),
  d_street_1   varchar(20),
  d_street_2   varchar(20),
  d_city       varchar(20),
  d_state      char(2),
  d_zip        char(9),
  constraint pk_district primary key (d_w_id, d_id)
) interleave in parent warehouse (d_w_id);

create table customer (
  c_w_id         integer        not null,
  c_d_id         integer        not null,
  c_id           integer        not null,
  c_discount     decimal(4,4),
  c_credit       char(2),
  c_last         varchar(16),
  c_first        varchar(16),
  c_credit_lim   decimal(12,2),
  c_balance      decimal(12,2),
  c_ytd_payment  decimal(12,2),
  c_payment_cnt  integer,
  c_delivery_cnt integer,
  c_street_1     varchar(20),
  c_street_2     varchar(20),
  c_city         varchar(20),
  c_state        char(2),
  c_zip          char(9),
  c_phone        char(16),
  c_since        timestamp,
  c_middle       char(2),
  c_data         varchar(500),
  constraint pk_customer primary key (c_w_id, c_d_id, c_id)
) interleave in parent district (c_w_id, c_d_id);

create index customer_idx on customer (c_w_id, c_d_id, c_last, c_first)
		interleave in parent district (c_w_id, c_d_id);

create table history (
  hist_id  serial PRIMARY KEY,    
  h_c_id   integer,
  h_c_d_id integer,
  h_c_w_id integer,
  h_d_id   integer,
  h_w_id   integer,
  h_date   timestamp,
  h_amount decimal(6,2),
  h_data   varchar(24),
  index (h_w_id, h_d_id),
  index (h_c_w_id, h_c_d_id, h_c_id)
);

create table new_order (
  no_w_id  integer   not null,
  no_d_id  integer   not null,
  no_o_id  integer   not null,
 constraint pk_new_order primary key (no_w_id, no_d_id, no_o_id)
);

create table oorder (
  o_w_id       integer      not null,
  o_d_id       integer      not null,
  o_id         integer      not null,
  o_c_id       integer,
  o_carrier_id integer,
  o_ol_cnt     integer,
  o_all_local  integer,
  o_entry_d    timestamp,
  constraint pk_oorder primary key (o_w_id, o_d_id, o_id),
  index (o_w_id, o_d_id, o_c_id)
) interleave in parent district (o_w_id, o_d_id);

create unique index order_idx on oorder (o_w_id, o_d_id, o_carrier_id, o_id)
		interleave in parent district (o_w_id, o_d_id);

create table order_line (
  ol_w_id         integer   not null,
  ol_d_id         integer   not null,
  ol_o_id         integer   not null,
  ol_number       integer   not null,
  ol_i_id         integer   not null,
  ol_delivery_d   timestamp,
  ol_amount       decimal(6,2),
  ol_supply_w_id  integer,
  ol_quantity     integer,
  ol_dist_info    char(24),
  constraint pk_order_line primary key (ol_w_id, ol_d_id, ol_o_id, ol_number),
  index (ol_supply_w_id, ol_d_id),
  index (ol_supply_w_id, ol_i_id) 
) interleave in parent oorder (ol_w_id, ol_d_id, ol_o_id);

create table item (
  i_id     integer      not null,
  i_name   varchar(24),
  i_price  decimal(5,2),
  i_data   varchar(50),
  i_im_id  integer,
  constraint pk_item primary key (i_id)
);

create table stock (
  s_w_id       integer       not null,
  s_i_id       integer       not null,
  s_quantity   integer,
  s_ytd        integer,
  s_order_cnt  integer,
  s_remote_cnt integer,
  s_data       varchar(50),
  s_dist_01    char(24),
  s_dist_02    char(24),
  s_dist_03    char(24),
  s_dist_04    char(24),
  s_dist_05    char(24),
  s_dist_06    char(24),
  s_dist_07    char(24),
  s_dist_08    char(24),
  s_dist_09    char(24),
  s_dist_10    char(24),
  constraint pk_stock primary key (s_w_id, s_i_id),
  index (s_i_id)
) interleave in parent warehouse (s_w_id);


alter table district add constraint d_warehouse_fkey foreign key (d_w_id) references warehouse (w_id) ON DELETE CASCADE;;
alter table customer add constraint c_district_fkey foreign key (c_w_id, c_d_id) references district (d_w_id, d_id) ON DELETE CASCADE;;
alter table history add constraint h_customer_fkey foreign key (h_c_w_id, h_c_d_id, h_c_id) references customer (c_w_id, c_d_id, c_id) ON DELETE CASCADE;;
alter table history add constraint h_district_fkey foreign key (h_w_id, h_d_id) references district (d_w_id, d_id) ON DELETE CASCADE;;
alter table new_order add constraint no_order_fkey foreign key (no_w_id, no_d_id, no_o_id) references oorder (o_w_id, o_d_id, o_id) ON DELETE CASCADE;;
alter table oorder add constraint o_customer_fkey foreign key (o_w_id, o_d_id, o_c_id) references customer (c_w_id, c_d_id, c_id) ON DELETE CASCADE;;
alter table order_line add constraint ol_order_fkey foreign key (ol_w_id, ol_d_id, ol_o_id) references oorder (o_w_id, o_d_id, o_id) ON DELETE CASCADE;;
alter table order_line add constraint ol_stock_fkey foreign key (ol_supply_w_id, ol_i_id) references stock (s_w_id, s_i_id) ON DELETE CASCADE;;
alter table stock add constraint s_warehouse_fkey foreign key (s_w_id) references warehouse (w_id) ON DELETE CASCADE;;
alter table stock add constraint s_item_fkey foreign key (s_i_id) references item (i_id) ON DELETE CASCADE;;
```

**Comment by robert-s-lee** [comment]
@jordanlewis created https://github.com/robert-s-lee/oltpbench/tree/cockroachdb which has the changes to support cockroachdb with src/com/oltpbenchmark/types/DatabaseType.java `COCKROACHDB("org.postgresql.Driver", false, true, true)` which is fast.  

Below is steps to run:
```
ant
cockroach sql --insecure -e "create database tpcc"
./oltpbenchmark -b tpcc -c config/sample_crdbtpcc_config.xml --create=true --load=true -s 5 -v -o outputfile
./oltpbenchmark -b tpcc -c config/sample_crdbtpcc_config.xml --execute=true -s 5 -v -o outputfile
```

cockroachdb with src/com/oltpbenchmark/types/DatabaseType.java `COCKROACHDB("org.postgresql.Driver", false, false, true)` which is slow.

**Comment by robert-s-lee** [comment]
@jordanlewis re-running clean setup to re-pro.  no need to do anything for now.

**Comment by robert-s-lee** [comment]
updated the branch for repro.  there are weird things goin on.  will have to continue debugging

1. `COCKROACHDB("org.postgresql.Driver", false, false, true)` is slower, but not all data is in the database.  The execution fails with missing data.
2.  `COCKROACHDB("org.postgresql.Driver", false, true, true)` is about 20 seconds faster and does execute correctly.

@drewdeally can you see if you get same?  Want to make sure I am not fat fingering commands.

```
ant clean
sed -i bak 's/COCKROACHDB.*),$/COCKROACHDB("org.postgresql.Driver", false, false, true),/' src/com/oltpbenchmark/types/DatabaseType.java
ant
cockroach sql --insecure -e "drop database if exists tpcc cascade; create database tpcc"
time ./oltpbenchmark -b tpcc -c config/tpcc_config_cockroachdb.xml --create=true --load=true -s 5 -v -o outputfile
./oltpbenchmark -b tpcc -c config/tpcc_config_cockroachdb.xml --execute=true -s 5 -v -o outputfile

ant clean
sed -i bak 's/COCKROACHDB.*),$/COCKROACHDB("org.postgresql.Driver", false, true, true),/' src/com/oltpbenchmark/types/DatabaseType.java
ant
cockroach sql --insecure -e "drop database if exists tpcc cascade; create database tpcc"
time ./oltpbenchmark -b tpcc -c config/tpcc_config_cockroachdb.xml --create=true --load=true -s 5 -v -o outputfile
./oltpbenchmark -b tpcc -c config/tpcc_config_cockroachdb.xml --execute=true -s 5 -v -o outputfile
```

**Comment by drewdeally** [comment]
@Robert post your xml file here - thanks

**Comment by drewdeally** [comment]
found this issue Error executing: ALTER TABLE history  ADD CONSTRAINT fkey_history_1 FOREIGN KEY(h_c_w_id,h_c_d_id,h_c_id) REFERENCES customer(c_w_id,c_d_id,c_id) ON DELETE CASCADE 
Exception in thread "main" java.lang.RuntimeException: Unexpected error when trying to create the tpcc database

**Comment by drewdeally** [comment]
a few issues which might be encountered - if you are running 8 or 9 java download these files 


javax.activation-1.2.0.jar
http://search.maven.org/remotecontent?filepath=com/sun/activation/javax.activation/1.2.0/javax.activation-1.2.0.jar

jaxb-api-2.3.0.jar
http://search.maven.org/remotecontent?filepath=javax/xml/bind/jaxb-api/2.3.0/jaxb-api-2.3.0.jar

jaxb-core-2.3.0.jar
http://search.maven.org/remotecontent?filepath=com/sun/xml/bind/jaxb-core/2.3.0/jaxb-core-2.3.0.jar

jaxb-impl-2.3.0.jar
http://search.maven.org/remotecontent?filepath=com/sun/xml/bind/jaxb-impl/2.3.0/jaxb-impl-2.3.0.jar

Download above files and copy them into libs folder in the project
Add the imported JAR files in Java Build Path

rebuild and things work fine.

Robert I have confirmed the issue.

**Comment by drewdeally** [comment]
./oltpbenchmark -b tpcc -c config/tpcc_config_cockroachdb.xml --execute=true -s 5 -v 
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.sun.xml.bind.v2.runtime.reflect.opt.Injector (file:/Users/andrewdeally/go/src/github.com/robert-s-lee/oltpbench/lib/jaxb-impl.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of com.sun.xml.bind.v2.runtime.reflect.opt.Injector
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
21:47:09,848 (DBWorkload.java:259) INFO  - ======================================================================

Benchmark:     TPCC {com.oltpbenchmark.benchmarks.tpcc.TPCCBenchmark}
Configuration: config/tpcc_config_cockroachdb.xml
Type:          COCKROACHDB
Driver:        org.postgresql.Driver
URL:           jdbc:postgresql://localhost:26257/tpcc?reWriteBatchedInserts=true
Isolation:     TRANSACTION_SERIALIZABLE
Scale Factor:  1.0

21:47:09,850 (DBWorkload.java:260) INFO  - ======================================================================
21:47:09,866 (DBWorkload.java:813) INFO  - Creating 2 virtual terminals...
21:47:10,008 (DBWorkload.java:818) INFO  - Launching the TPCC Benchmark with 1 Phase...
21:47:10,015 (ThreadBench.java:327) INFO  - PHASE START :: [Workload=TPCC] [Serial=false] [Time=60] [WarmupTime=0] [Rate=10000] [Arrival=REGULAR] [Ratios=[45.0, 43.0, 4.0, 4.0, 4.0]] [ActiveWorkers=2]
21:47:10,016 (ThreadBench.java:477) INFO  - MEASURE :: Warmup complete, starting measurements.
21:48:10,018 (ThreadBench.java:433) INFO  - TERMINATE :: Waiting for all terminals to finish ..
21:48:10,077 (ThreadBench.java:233) INFO  - Starting WatchDogThread
21:48:10,085 (DBWorkload.java:824) INFO  - ======================================================================
21:48:10,086 (DBWorkload.java:825) INFO  - Rate limited reqs/s: Results(nanoSeconds=60001344993, measuredRequests=3425) = 57.08205375062133 requests/sec
21:48:10,089 (DBWorkload.java:682) INFO  - Output Raw data into file: results/oltpbench.csv
21:48:10,286 (DBWorkload.java:736) INFO  - Output into file: results/oltpbench.res
21:48:10,287 (DBWorkload.java:739) INFO  - Grouped into Buckets of 5 seconds


FAILS with the first setting 

sed -i bak 's/COCKROACHDB.*),$/COCKROACHDB("org.postgresql.Driver", false, false, true),/' src/com/oltpbenchmark/types/DatabaseType.java

**Comment by drewdeally** [comment]
also found some issues 

21:53:32,506 (DBWorkload.java:260) INFO  - ======================================================================
21:53:32,524 (DBWorkload.java:813) INFO  - Creating 2 virtual terminals...
21:53:32,617 (DBWorkload.java:818) INFO  - Launching the TPCC Benchmark with 1 Phase...
21:53:32,624 (ThreadBench.java:327) INFO  - PHASE START :: [Workload=TPCC] [Serial=false] [Time=60] [WarmupTime=0] [Rate=10000] [Arrival=REGULAR] [Ratios=[45.0, 43.0, 4.0, 4.0, 4.0]] [ActiveWorkers=2]
21:53:32,625 (ThreadBench.java:477) INFO  - MEASURE :: Warmup complete, starting measurements.
21:54:32,627 (ThreadBench.java:433) INFO  - TERMINATE :: Waiting for all terminals to finish ..
21:54:32,700 (ThreadBench.java:233) INFO  - Starting WatchDogThread
21:54:32,706 (DBWorkload.java:824) INFO  - ======================================================================
21:54:32,707 (DBWorkload.java:825) INFO  - Rate limited reqs/s: Results(nanoSeconds=60000256676, measuredRequests=3454) = 57.566420401357945 requests/sec
21:54:32,709 (DBWorkload.java:682) INFO  - Output Raw data into file: results/oltpbench.1.csv
21:54:32,857 (DBWorkload.java:736) INFO  - Output into file: results/oltpbench.1.res
21:54:32,858 (DBWorkload.java:739) INFO  - Grouped into Buckets of 5 seconds
21:54:32,869 (DBWorkload.java:620) INFO  - ======================================================================
21:54:32,870 (DBWorkload.java:621) INFO  - Workload Histograms:
Completed Transactions:
NewOrder/01          [1521] ********************************************************************************
Payment/02           [1462] ****************************************************************************
OrderStatus/03       [ 147] *******
Delivery/04          [ 141] *******
StockLevel/05        [ 137] *******

Aborted Transactions:
NewOrder/01          [  21] ********************************************************************************
Payment/02           [   0] 
OrderStatus/03       [   0] 
Delivery/04          [   1] ***
StockLevel/05        [   0] 

Rejected Transactions (Server Retry):
NewOrder/01          [   0] 
Payment/02           [   0] 
OrderStatus/03       [   0] 
Delivery/04          [   0] 
StockLevel/05        [   0] 

Unexpected Errors:
NewOrder/01          [  12] ********************************************************************
Payment/02           [  14] ********************************************************************************
OrderStatus/03       [   0] 
Delivery/04          [   0] 
StockLevel/05        [   0] 
21:54:32,870 (DBWorkload.java:622) INFO  - ======================================================================
Andrews-MacBook-Pro:oltpbench andrewdeally$

**Comment by drewdeally** [comment]
another odd find

root@:26257/tpcc> show experimental_ranges from table oorder;
+----------------------------------------------------------+----------------------------------------------------------+----------+----------+--------------+
|                        start_key                         |                         end_key                          | range_id | replicas | lease_holder |
+----------------------------------------------------------+----------------------------------------------------------+----------+----------+--------------+
| NULL                                                     | /2                                                       |       66 | {1,2,3}  |            1 |
| /2                                                       | /2/#/103/1/2716                                          |       78 | {1,2,3}  |            1 |
| /2/#/103/1/2716                                          | /3/#/96/1/1/#/97/2/"OUGHTATIONBAR"/"qwqjbwwemseilj"/2101 |       76 | {1,2,3}  |            1 |
| /3/#/96/1/1/#/97/2/"OUGHTATIONBAR"/"qwqjbwwemseilj"/2101 | /3/#/103/1/329                                           |       79 | {1,2,3}  |            1 |
| /3/#/103/1/329                                           | /4/#/96/1/1/#/97/1/1894                                  |       75 | {1,2,3}  |            1 |
| /4/#/96/1/1/#/97/1/1894                                  | /4/#/96/1/10/#/97/1/1592                                 |       77 | {1,2,3}  |            1 |
| /4/#/96/1/10/#/97/1/1592                                 | /4/#/103/1/91757                                         |       80 | {1,2,3}  |            1 |
| /4/#/103/1/91757                                         | /5/#/96/1/7/#/100/1/255/#/101/1/7                        |       82 | {1,2,3}  |            1 |
| /5/#/96/1/7/#/100/1/255/#/101/1/7                        | /5/#/103/1/49237                                         |       95 | {1,2,3}  |            1 |
| /5/#/103/1/49237                                         | /6/#/96/1/4/#/100/1/1387/#/101/1/6                       |       85 | {1,2,3}  |            1 |
| /6/#/96/1/4/#/100/1/1387/#/101/1/6                       | /6/#/103/1/29714                                         |       88 | {1,2,3}  |            1 |
| /6/#/103/1/29714                                         | /7/#/96/1/3/#/97/1/2451                                  |       83 | {1,2,3}  |            1 |
| /7/#/96/1/3/#/97/1/2451                                  | /7/#/103/1/52534                                         |       87 | {1,2,3}  |            1 |
| /7/#/103/1/52534                                         | /8/#/96/1/10/#/97/1/929                                  |       84 | {1,2,3}  |            1 |
| /8/#/96/1/10/#/97/1/929                                  | /8/#/103/1/90605                                         |       86 | {1,2,3}  |            1 |
| /8/#/103/1/90605                                         | /9/#/96/1/7/#/100/1/900/#/101/1/11                       |       91 | {1,2,3}  |            1 |
| /9/#/96/1/7/#/100/1/900/#/101/1/11                       | /9/#/103/1/84473                                         |       94 | {1,2,3}  |            1 |
| /9/#/103/1/84473                                         | /10/#/96/1/10/#/97/1/1536                                |       92 | {1,2,3}  |            1 |
| /10/#/96/1/10/#/97/1/1536                                | NULL                                                     |       93 | {1,2,3}  |            1 |
+----------------------------------------------------------+----------------------------------------------------------+----------+----------+--------------+
(19 rows)

Time: 12.727908ms

root@:26257/tpcc> show experimental_ranges from table warehouse;                                                                                                                       
+----------------------------------------------------------+----------------------------------------------------------+----------+----------+--------------+
|                        start_key                         |                         end_key                          | range_id | replicas | lease_holder |
+----------------------------------------------------------+----------------------------------------------------------+----------+----------+--------------+
| NULL                                                     | /2                                                       |       66 | {1,2,3}  |            1 |
| /2                                                       | /2/#/103/1/2716                                          |       78 | {1,2,3}  |            1 |
| /2/#/103/1/2716                                          | /3/#/96/1/1/#/97/2/"OUGHTATIONBAR"/"qwqjbwwemseilj"/2101 |       76 | {1,2,3}  |            1 |
| /3/#/96/1/1/#/97/2/"OUGHTATIONBAR"/"qwqjbwwemseilj"/2101 | /3/#/103/1/329                                           |       79 | {1,2,3}  |            1 |
| /3/#/103/1/329                                           | /4/#/96/1/1/#/97/1/1894                                  |       75 | {1,2,3}  |            1 |
| /4/#/96/1/1/#/97/1/1894                                  | /4/#/96/1/10/#/97/1/1592                                 |       77 | {1,2,3}  |            1 |
| /4/#/96/1/10/#/97/1/1592                                 | /4/#/103/1/91757                                         |       80 | {1,2,3}  |            1 |
| /4/#/103/1/91757                                         | /5/#/96/1/7/#/100/1/255/#/101/1/7                        |       82 | {1,2,3}  |            1 |
| /5/#/96/1/7/#/100/1/255/#/101/1/7                        | /5/#/103/1/49237                                         |       95 | {1,2,3}  |            1 |
| /5/#/103/1/49237                                         | /6/#/96/1/4/#/100/1/1387/#/101/1/6                       |       85 | {1,2,3}  |            1 |
| /6/#/96/1/4/#/100/1/1387/#/101/1/6                       | /6/#/103/1/29714                                         |       88 | {1,2,3}  |            1 |
| /6/#/103/1/29714                                         | /7/#/96/1/3/#/97/1/2451                                  |       83 | {1,2,3}  |            1 |
| /7/#/96/1/3/#/97/1/2451                                  | /7/#/103/1/52534                                         |       87 | {1,2,3}  |            1 |
| /7/#/103/1/52534                                         | /8/#/96/1/10/#/97/1/929                                  |       84 | {1,2,3}  |            1 |
| /8/#/96/1/10/#/97/1/929                                  | /8/#/103/1/90605                                         |       86 | {1,2,3}  |            1 |
| /8/#/103/1/90605                                         | /9/#/96/1/7/#/100/1/900/#/101/1/11                       |       91 | {1,2,3}  |            1 |
| /9/#/96/1/7/#/100/1/900/#/101/1/11                       | /9/#/103/1/84473                                         |       94 | {1,2,3}  |            1 |
| /9/#/103/1/84473                                         | /10/#/96/1/10/#/97/1/1536                                |       92 | {1,2,3}  |            1 |
| /10/#/96/1/10/#/97/1/1536                                | NULL                                                     |       93 | {1,2,3}  |            1 |
+----------------------------------------------------------+----------------------------------------------------------+----------+----------+--------------+
(19 rows)

Time: 15.602344ms

root@:26257/tpcc>

**Comment by knz** [comment]
Robert, Drew, can you please peruse the syntax 

\`\`\`
your example ...
\`\`\`

so we get properly preformatted text:

```
your example...
```

thanks

**Comment by robert-s-lee** [comment]
Finally tracked this down.  Not a database issue.  

`loadCustomers()` performs txn load of `Customer` and `History` tables.  `hist_id` was the first column in the schema that shifted the columns requiring column names to run correctly.  Move the `hist_id` to the end so that insert can work or without the column names.   

```
create table history (
  h_c_id   integer,
  h_c_d_id integer,
  h_c_w_id integer,
  h_d_id   integer,
  h_w_id   integer,
  h_date   timestamp,
  h_amount decimal(6,2),
  h_data   varchar(24),
  hist_id  serial,
  constraint h_customer_fkey foreign key (h_c_w_id, h_c_d_id, h_c_id) references customer (c_w_id, c_d_id, c_id) ON DELETE CASCADE,
  constraint h_district_fkey foreign key (h_w_id, h_d_id) references district (d_w_id, d_id) ON DELETE CASCADE,
  index (h_w_id, h_d_id),
  index (h_c_w_id, h_c_d_id, h_c_id),
  primary key (hist_id)
);
```
