### ISSUE TITLE
importccl: IMPORT MYSQLDUMP fails with "columns cannot be used by multiple foreign key constraints"

### ISSUE THREAD

**Issue by rolandcrosby** [cockroachdb/cockroach#29554]
I tried to import the MySQL dump attached to [this FOIA response](https://www.muckrock.com/foi/chicago-169/data-dictionary-mysql-dump-59229/#comm-595769); after downloading and extracting the file, I got this error upon trying to import it:

```
root@:26257/defaultdb> import mysqldump ('nodelocal:/mysqldump/CITYDATADICT_Dump20160319.sql');
pq: columns cannot be used by multiple foreign key constraints
```

**Comment by mjibson** [comment]
This is a known limitation with our FK handling and not an import bug.
