### ISSUE TITLE
cli: `cockroach demo` writes to `cockroach-data` (logs)

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#29567]
`cockroach demo` was meant, I thought, to be diskless. Except that it writes to the cockroach-data directory in the current directory for logs.

Not sure that's a feature or a bug -- @jordanlewis, thoughts?

However something needs to be done because it clobbers the source tree during tests (in the `Example_demo` I recently added). I'll look into the test case.

**Comment by knz** [comment]
IMHO the file logging should be disabled by default unless explicitly requested with --log-dir or --logtostderr. I'll make  a patch.

**Comment by jordanlewis** [comment]
> Not sure that's a feature or a bug -- @jordanlewis, thoughts?

Bug. I didn't intend for `cockroach demo` to write anywhere.
