### ISSUE TITLE
sql: schema change checkpoint writes keep retrying

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#29566]
@leomkkwan reports seeing a lot of these log messages

```
I180830 00:50:29.667945 104739491 sql/distsqlrun/backfiller.go:226  [n4,IndexBackfiller=90] retrying adding checkpoint <foo> to table <bar>
```

This is likely because each processor is given 10 minutes to finish processing after which it writes a checkpoint. If all processors write at approximately the same time they are bound to contend with each other and retry

**Comment by lucy-zhang** [comment]
@dt This seems like a backfiller issue - do you know if it's still applicable? I'm going to kick it back to Bulk IO for now but feel free to move back if you disagree.

**Comment by dt** [comment]
I think this is a non-issue -- there is jitter in the processors and I _think_ we even did some work to avoid tearing them down and re-checkpointing as often.
