### ISSUE TITLE
add the option to make a clone from a running cluster

### ISSUE THREAD

**Issue by ikzelf** [cockroachdb/cockroach#29575]
**FEATURE REQUEST**
When databases grow larger and larger, creating a test cluster from a production cluster takes a lot of time, especially when the process is based on SQL dumps.
It would be *VERY* nice when we could get the option to add clone_node[s] to a cluster that get synchronised with the source cluster, until we decide it is time to activate the clone as a new test cluster based on the latest source database transactions.
Activating the new test cluster should remove the dependency from the source cluster.
Maybe adding a filter to only synchronise certain databases would be smart, in case a cluster contains multiple databases.
An other use case could be to migrate to an other datacenter. In that case, the source cluster will be taken offline when the new cluster is to be activated.

**Comment by mjibson** [comment]
For now the best we can do for high speed cluster clones is BACKUP/RESTORE. Non-voting replicas have been discussed but aren't yet on our roadmap.
