### ISSUE TITLE
pick up work on per-bucket random replica order

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#2957]
This is a good entry-level problem.
Essentially, when figuring out which nodes to talk to, we bucket-sort to try the "most similar" nodes first.
The TODO here is to simply make sure that in each bucket, the entries are randomized among multiple calls, so that the traffic spreads evenly to all candidates.

see https://github.com/cockroachdb/cockroach/pull/2606 for some work-in-progress that can be picked up.

**Comment by lizhongz** [comment]
It seem that this one is helpful to know about the internals. I am happy to work on this :-)

**Comment by tschottdorf** [comment]
Cool! All yours. You'll probably have this done in no time with the
existing PR.

**Comment by yaojingguo** [comment]
@tschottdorf, I have worked out a PR for this issue. Could you please take a look?

**Comment by tschottdorf** [comment]
I picked up the WIP on this and landed it at some point.
