### ISSUE TITLE
sql: enable client to introspect units of metrics in csettings and vtables

### ISSUE THREAD

**Issue by ikzelf** [cockroachdb/cockroach#29571]
**FEATURE REQUEST**
currently setting and metrics tables contain human friendly formatting for the values, which is friendly for humans but clumsy for monitoring tools that try to keep track of values. Please use simple units and/or add the unit that is used for the simple unformatted value.
For example: times in seconds, sizes in bytes, switches in boolean.
Also add the default values so it is easier to pickup settings that are not using the defaults, of course, using the same units as the current values.

**Comment by ikzelf** [comment]
yes, that is correct, using SQL to get the metrics. See [https://github.com/ikzelf/zbxdb](url)

**Comment by knz** [comment]
which metrics table are you looking at?

**Comment by knz** [comment]
Really we need examples of what you'd like to see to scope out the work that needs to be done. Right now the problem statement is too vague as-is.

**Comment by knz** [comment]
ok, I understand better now. thanks for clarifying. Will look into this as part of our general UX improvements on vtables.
