### ISSUE TITLE
sql: Introspection reports invalid precision for row id column 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#29581]
![image](https://user-images.githubusercontent.com/22278911/45097304-7cf6f880-b0f0-11e8-9622-d2f0ba482af3.png)

This is in Dbeaver testing

**Comment by jordanlewis** [comment]
Actually this isn't invalid - it's expected and exactly what postgres does.

![image](https://user-images.githubusercontent.com/43821/56697130-c5285280-66a2-11e9-83dd-28b6e22380fa.png)
