### ISSUE TITLE
sql/storage: EXPERIMENTAL_RELOCATE should give meaningful errors on invalid configurations

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#29607]
The `ALTER TABLE ... EXPERIMENTAL_RELOCATE` command does no validation of the provided store IDs against the relevant zone config. It'll happily let me move replicas onto too many stores, too few stores (even down to just 1 replica), stores that don't match the zone constraints, etc.

Giving manual control to admins is good, but I'd think most admins would want their own configurations to protect them from manual mistakes.

**Comment by a-robinson** [comment]
On a cluster with a lot of ranges, it can take a long time for the allocator to fix these situations, too. I had to wait about 5 minutes after dropping a range down to 1 replica on adriatic before it up-replicated.

**Comment by knz** [comment]
How do you suggest to detect whether a configuration is valid?

**Comment by a-robinson** [comment]
Thanks for bubbling this up, @knz! This actually isn't true anymore. As of https://github.com/cockroachdb/cockroach/pull/29684, we do run all replica additions through the allocator, which will reject those that violate zone configs or are to stores that are too close to running out of disk space. The problem now is likely to be more around making it clear to the user why the `EXPERIMENTAL_RELOCATE` statement couldn't be completed, because the error message isn't going to be something as obviously understandable `store 123 violated zone constraints for database foo`. It'll be more like `none of the remaining targets [n123,s123] are legal additions to [(n2,s2), (n3,s3), (n4,s4)]`.

**Comment by a-robinson** [comment]
> is there a function somewhere that can be called at the time the SQL statement is used?

Not currently, and due to the dependence on some knowledge that's only held in the storage layer, I think this would have to be implemented as part of `AdminRelocateRange` rather than in the sql layer.

> Also shouldn't this be done on CONFIGURE ZONE too?

I'm not quite understanding this question. What do you think should be done on CONFIGURE ZONE?

**Comment by tschottdorf** [comment]
@a-robinson moving this into 2.1 since it seems like you can close it soon.

**Comment by a-robinson** [comment]
This may actually be pretty tricky to give better errors for. Does anyone feel that the errors need to be more descriptive than the aforementioned `none of the remaining targets [n1,s1] are legal additions to [(n2,s2), (n3,s3), (n4,s4)]`? If so, it'll have to be 2.2 work because it would involve breaking into the allocator abstraction to try to pull more meaningful reasons out of it.
