### ISSUE TITLE
select block_id from datablocks.blocks LIMIT 5;

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#2962]
when running the block writer example, this query kills the cluster: write throughput drops to zero permanently and the cluster barfs.
not yet sure what happens there, but from the start this query shouldn't do a table scan. Does it do that maybe?

FWIW, `top -cum` in `pprof` shows (in a 30s profile)

```
         .          .     91:   case *roachpb.ScanRequest:
         .          .     92:           var resp roachpb.ScanResponse
         .      7.88s     93:           resp, intents, err = r.Scan(batch, h, *tArgs)
         .          .     94:           reply = &resp
```

so there definitely is a Scan running wild. Possibly the request triggers some infinite retry loop.

**Comment by petermattis** [comment]
`LIMIT` limits the output, but currently doesn't limit the scan. For simple cases, we could limit the scan to exactly the necessary number of keys. For more complex cases we should be retrieving the key-value pairs for a scan in batches (currently we retrieve them all in a single request) which would allow higher levels of query processing to exit when enough rows have been produced.

**Comment by tschottdorf** [comment]
ok. This should still work though.

**Comment by petermattis** [comment]
You're scanning the table while inserting into it. Could the scan transaction be getting restarted repeatedly?

**Comment by tschottdorf** [comment]
well, the inserts really stop (since the client just stalls) but something like this is likely the culprit.

**Comment by tschottdorf** [comment]
I think I have the culprit (the coordinator used a ridiculously low timeout for sending RPCs, so everything that took over 500ms got cut off). Will submit a PR to avoid these issues in the future.

**Comment by petermattis** [comment]
We definitely need to rethink our timeout-based retries. If a request times out because it was slow, resending it is very likely to exacerbate any slowness. We should also eliminate the unlimited number of results for scan requests. I suspect that is never useful in practice.

**Comment by tschottdorf** [comment]
if we were able to distinguish between requests timing out to an inaccessible node vs. inactivity on the connection, that'd be a big plus. I imagine with http2 it should be possible to send keep-alive frames and to only time out when the connection goes cold.

**Comment by tschottdorf** [comment]
is that again something that gRPC could help us with?

**Comment by petermattis** [comment]
I'm not sure if gRPC would help. I'm pretty sure you can detect connection problems with streaming RPCs. I'm not sure what kind of error you get with single-shot RPCs.

**Comment by bdarnell** [comment]
GRPC will let you test the health of the channel whether you're using streaming RPCs or not (we could do the same with our own RPC protocol. The only protocol where we can't do this easily is HTTP/1, and even then there are hacks we could use). The tricky thing would be communicating channel-level health back to the places that care.

**Comment by changrui82** [comment]
“I think I have the culprit (the coordinator used a ridiculously low timeout for sending RPCs, so everything that took over 500ms got cut off).”
Maybe 500ms really too short. But after I read the code in send.go, my question is: 
when time.After(opts.SendNextTimeout):, we only send to next peer(if we have), and wait for response again. 
We don’t send any new request and we don’t send request again to the first server node neither.
it seems doesn’t give more pressure on first server node(and the gateway node itself), why it can kills the cluster?

**Comment by tschottdorf** [comment]
Hey @changrui82, the issue above was that an individual call would take more than 500ms on the node. That would cause the RPC to fail, and the `DistSender` would retry. In effect, that would send a new request to the first node every 500ms, and they kept piling up, killing the cluster.
In the future, we'll have to be smarter here, but for now it's good to eliminate sources of wedging in normal operation.
