### ISSUE TITLE
sql: support role/user attributes.

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#29633]
Of the [list](https://www.postgresql.org/docs/current/static/role-attributes.html) we only support `password`.

Most others would be nice to have:
* `login`: would allow disabling login. roles cannot login, but users can. Setting to false would disable connections initiated with that user (whether password or certificate auth)
* `superuser`: we currently hard-code the `root` user and `admin` role as superusers. We may want to change that but it's probably not a big priority.
* `database creation` / `role creation`: this would allow a non-superuser to perform user/db management tasks. Note that this allows manipulation/deletion of objects as well, so it is still a high-level privilege
* `initiating replication`: ah! don't care.
* `password`: we already have it.

`login` is the one really missing. The only way to disable login from a given user is to delete them as certificates cannot currently be revoked.

CC: @kannanlakshmi for product view, @vivekmenezes for triage.

**Comment by knz** [comment]
see #41396 for a subset of the demand

**Comment by knz** [comment]
we have implemented this.
