### ISSUE TITLE
sql: type system doesn't handle variadic functions

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#2964]
The builtin function `CONCAT` is defined (in CockroachDB, not elsewhere) as accepting variadic arguments, each of which must be a `DString` or `DNull`. Thus, it should be possible to fail the following case at type-checking time:
```sql
CREATE TABLE kv2 (k CHAR PRIMARY KEY, v INT NOT NULL);
-- OR
CREATE TABLE kv2 (k CHAR PRIMARY KEY, v INT);
SELECT CONCAT(k, v) FROM kv;
```
However, we currently do not pass around nullability in type information, which prevents this case from failing until run time.

**Comment by bdarnell** [comment]
Are you implying that if the table were defined as `(k CHAR PRIMARY KEY, v INT)` the `CONCAT(k, v)` should pass type-check but fail at runtime if any of the rows have non-null values for `v`? That would be surprising to me: my mental model of the type system is that null values still carry the type that they could have had if not null, so a nullable-int cannot be passed to a function expecting a nullable-string even though both have null as a possible value.

**Comment by tamird** [comment]
Yes, that's what I was implying. You make a good point though, and perhaps nullable-int should also not type check: accepting that, this issue becomes "we can't type check variadic functions".

**Comment by tschottdorf** [comment]
@tamird, could you update the issue? This seems to not error at all now:

```
macts.local:26257> CREATE TABLE IF NOT EXISTS kv2 (k CHAR PRIMARY KEY, v INT NOT NULL); SELECT CONCAT(k,v) FROM kv2;
+--------------+
| CONCAT(k, v) |
+--------------+
+--------------+
```

**Comment by tamird** [comment]
@tschottdorf yeah, that's the issue reported here; it should error, but does not. If you insert a row into the table, the `SELECT` will fail (at evaluation-time).

**Comment by petermattis** [comment]
Did @mjibson's work in #3298 enable better behavior here?
