### ISSUE TITLE
set the RocksDB cache size based on (total) ram size

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#2965]
`defaultCacheSize` (the "RocksDB Cache Size") in `server/context.go` is currently hard-coded to `1GB`. We should compute the cache size to use as a function of the total memory available to the system.

* figure out a way to obtain the total memory. [gosigar](https://github.com/cloudfoundry/gosigar) looks promising (and portable), but there may be other options.
* write a function taking that number and returning the proposed cache size. As a first approximation, `max(mem_size/2, 2GB)` should work, but a TODO for digging into the [RocksDB Tuning Guide](https://github.com/facebook/rocksdb/wiki/RocksDB-Tuning-Guide) and figuring out a "good" default should be added (or carried out). The number is eventually used in `storage/engine/rocksdb.go`.
* set `defaultCacheSize` to that value via `func init() { ... }` (for now).

**Comment by thschroeter** [comment]
Happy to take a look.

**Comment by tschottdorf** [comment]
Cool. Thanks.

**Comment by thschroeter** [comment]
Tobias, here are some findings I'd like to discuss. I feel it might be better to let advanced users control the cache from the outside if necessary, e.g. by setting a flag. Let me know what you think. I'm ready to set the `defaultCacheSize` to `max(mem_size/2, 2g)` as you propose. Just want to clarify the following first.

* Assuming we are talking about the RocksDB block cache, it is not obvious to me what the size should be. I understand that RocksDB's block cache is caching uncompressed blocks while the page cache of the OS is caching compressed blocks (see RocksDB [issue](https://github.com/facebook/rocksdb/issues/519) talking about this tradeoff). Therefore the page cache can cache more blocks per size at the cost of spending CPU time for decompression. Increasing the block cache size will reduce CPU  time spent for decompression, but I feel this should be done only when the workload becomes CPU-bound and is not IO-bound.

* When using Go sigar inside a Docker container it reports the available memory of the host machine even if the container memory is restricted by the `memory` flag of Docker. When we use the function you propose, we can end up allocating too much memory for the block cache. The available memory inside a container can be found by accessing the info from the enclosing control group (if `/sys/fs/cgroup` is mounted into the container, default in Docker 1.8) or by querying Docker's API. Both options are not straightforward. We also need to figure out if we are inside a Docker container first.

**Comment by petermattis** [comment]
The cache should definitely be controllable by advanced users as tuning the
cache size for peak performance will likely always require a human's touch.

Choosing a reasonable default is more tractable. We want to make sure the
default doesn't cause a cache size that is larger than available memory
which would lead to out of memory crashes. I think something like
`available-mem/2` where `available-mem` is queried using /sys/fs/cgroup (if
present) or GoSigar if not. And we might want to surface a log message if
the host memory differs significantly from available memory to capture
cases where a user is running on a very large box (e.g. 64gb of ram) but
for some reason the cockroach environment is configured a lot smaller (e.g.
1gb).

**Comment by ajayaa** [comment]
Hi guys,

I was taking a look at this issue and found out that gosigar uses /proc/meminfo[https://github.com/cloudfoundry/gosigar/blob/master/sigar_linux.go#L313] file to find information about available memory which does not work when CockroachDB is running inside a container.

@petermattis I have a 14.04 Ubuntu system. In my host system cat /sys/fs/cgroup/memory/memory.limit_in_bytes gives 18446744073709551615 as output which looks absurd (8 GB machine) whereas inside a docker container in the same host cat /sys/fs/cgroup/memory/memory.limit_in_bytes gives 5001216 which was the amount of memory I allocated to the container when I created it.

A decent solution IMO would be to determine where the CockroachDB process is running and then querying the appropriate file i.e. when it's a vm or baremetal query /proc/meminfo and query /sys/fs/cgroup/memory/memory.limit_in_bytes when it's a container.

Please let me know you thoughts.

**Comment by tschottdorf** [comment]
That sounds like @thschroeter's original suggestion and is fine with me, though if possible I'd like to avoid having to discover whether we're running in a container. Would taking the **smaller** of the two values do the right thing? Meaning that if we're limited by `cgroup`, that should limit what we assume we can use, unless it's more memory available on the machine as per `gosigar` (which presumably would be the host machine's memory in all cases). What do you think?

**Comment by ajayaa** [comment]
@tschottdorf  That sounds like a good solution to me. I will create a PR with this approach.

BTW, do we want to use gosigar? Anyway we have to manually read /sys/fs/cgroup/memory/memory.limit_in_bytes and I think we can read /proc/meminfo in the same way.

**Comment by tschottdorf** [comment]
The upside to using `gosigar` is that it's cross-platform (we don't currently support Windows, but it can't hurt to stay compatible where we easily can), so I think you should use it regardless. Also (though you don't have to worry about it too much for the first draft of the PR) we should attempt to read the `cgroup` information only when we're on linux.
Thanks for tackling this!

**Comment by thschroeter** [comment]
@ajayaa, please let me know if you are working on this.

**Comment by ajayaa** [comment]
@thschroeter Yes I am working on this. There was a discussion regarding making this value configurable. I haven't followed up after that due to other commitments. Let me take it up and finish it. Thanks for putting this back in my TODO list.

**Comment by thschroeter** [comment]
@ajayaa cool. I've opened a pr (#3919) with the parsing of the memory info, maybe we can use that. I didn't know where to log the info and I didn't add a flag.

**Comment by ajayaa** [comment]
@thschroeter Please have a look at https://github.com/cockroachdb/cockroach/pull/3514/files.

**Comment by thschroeter** [comment]
@ajayaa oh, I didn't see that you did a pr already. Will close mine.

**Comment by ajayaa** [comment]
@thschroeter Thanks for your sacrifice. :)

**Comment by petermattis** [comment]
Fixed in #4148.
