### ISSUE TITLE
sql: chunk KV scans to limit the number of keys retrieved at one time

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#2966]
The KV scan performed when doing a table/index scan currently reads all of key-value pairs in the desired range. For large tables the scan can be prohibitively expensive. We should chunk the scan into reasonable sizes (e.g. 1000 or 10000 keys). Depending on the query plan, this can allow a higher-level node in the plan to terminate execution before the full table has been scanned (i.e. if there is a `LIMIT` operator).

**Comment by RaduBerinde** [comment]
If we only have one span, the strategy is straightforward: we limit the number of results in the request and fire off subsequent requests from the last received key onward. These requests can be fired up immediately (in the background) to allow overlap between SQL and KV processing.

The tricky thing is how to efficiently handle multiple spans. We can be optimistic and request `10000 / #spans` results for each span and hopefully that will be enough to fully retrieve most spans, after which we can go through the remaining "large" spans one by one (requesting `10000` results each time).

**Comment by RaduBerinde** [comment]
This is now done for single-span scans. For multi-span scans, this is dependent on #4696

**Comment by RaduBerinde** [comment]
Final fix in #5214
