### ISSUE TITLE
changefeedccl: use span-level progress tracking in restarts

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#29660]
We currently save span-level high-water marks in `jobspb.ChangefeedProgress`, but it's not used when restarting the job. This can potentially duplicate a lot of work (and emit a lot of duplicates), especially during something like the initial scan.

**Comment by danhhz** [comment]
note to self, it's very easy for this to create a huge row in the jobs table, which hoses the cluster. even the initial implementation of this will have to be careful about the size of the payload and how often it's being check-pointed

**Comment by danhhz** [comment]
This mostly only matters if a changefeed restarts (pause/unpause or a node failure) during an initial or backfill scan . Without this, we currently have to re-output the entire scan upon changefeed restart. It was originally implemented part-way, but was pulled out because it caused instability b/c large jobs rows (so we'd have to figure that out but I have some ideas).

Punting this because we should be focused on being more stable and it's not worth adding known instability to get this into 2.1.x

**Comment by danhhz** [comment]
This is not going to make 2.2

**Comment by miretskiy** [comment]
I think this was fixed by https://github.com/cockroachdb/cockroach/commit/2e403906cacad1454e7ce60b00220c1fc99d10fc
@ajwerner  can you double check and reopen if I'm mistaken?
