### ISSUE TITLE
TPCC Benchmark Driver errors - loadgen

### ISSUE THREAD

**Issue by maskayman** [cockroachdb/cockroach#29672]
Is this a bug report or a feature request?
Possible bug
If so, please fill out the template below and we'll be happy to help.

If not, or you're not sure, please file an issue on our forum instead: https://forum.cockroachlabs.com/. You'll get a faster response there for troubleshooting and general questions, and it's likely that someone else has encountered the same issue.

**BUG REPORT**

Please describe the issue you observed, and any steps we can take to reproduce it:

- Which version of CockroachDB are you using?
2.0.4
- What did you do?
Ran TPCC benchmark with 1000 warehouse in a 9 nodes cluster
- What did you expect to see?
No errors
- What did you see instead?
Errors example -

6m15s    newOrder         80.5        89.8   7247.8  36507.2  45097.2 103079.2 103079.2
2018/09/06 11:46:26 error in payment: driver: bad connection
16m16s    newOrder        104.8        89.8   9126.8  66572.0  85899.3 103079.2 103079.2
2018/09/06 11:46:27 error in payment: driver: bad connection
16m17s    newOrder         47.4        89.7   8589.9  98784.2 103079.2 103079.2 103079.2
16m18s    newOrder         85.7        89.7  10737.4  55834.6  94489.3 103079.2 103079.2
2018/09/06 11:46:30 error in payment: driver: bad connection
16m19s    newOrder         78.0        89.7   9126.8  47244.6 103079.2 103079.2 103079.2
2018/09/06 11:46:31 error in payment: driver: bad connection
16m20s    newOrder         77.8        89.7  13421.8  60129.5  66572.0 103079.2 103079.2
2018/09/06 11:46:32 error in payment: driver: bad connection
_time______opName__ops/s(inst)__ops/s(cum)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
16m21s    newOrder        101.8        89.7   9126.8  51539.6  77309.4 103079.2 103079.2
2018/09/06 11:46:32 error in payment: driver: bad connection
2018/09/06 11:46:32 error in payment: driver: bad connection
2018/09/06 11:46:33 error in payment: driver: bad connection
2018/09/06 11:46:33 error in payment: driver: bad connection
16m22s    newOrder        113.4        89.7  11274.3  55834.6  81604.4 103079.2 103079.2
16m23s    newOrder         79.5        89.7  11274.3  62277.0  98784.2 103079.2 103079.2
16m24s    newOrder         66.3        89.7  13958.6  85899.3 103079.2 103079.2 103079.2
2018/09/06 11:46:36 error in payment: driver: bad connection
16m25s    newOrder         58.0        89.7   9126.8  40802.2  42949.7 103079.2 103079.2
2018/09/06 11:46:36 error in payment: driver: bad connection
16m26s    newOrder         35.1        89.6  10737.4  36507.2  40802.2 103079.2 103079.2
2018/09/06 11:46:37 error in payment: driver: bad connection
16m27s    newOrder         10.1        89.5  10737.4  38654.7  38654.7  68719.5  68719.5
2018/09/06 11:46:38 error in payment: driver: bad connection
2018/09/06 11:46:39 error in payment: driver: bad connection
16m28s    newOrder         39.8        89.5  17179.9  57982.1  73014.4 103079.2 103079.2
2018/09/06 11:46:39 error in payment: driver: bad connection
2018/09/06 11:46:39 error in payment: driver: bad connection
2018/09/06 11:46:39 error in payment: driver: bad connection
2018/09/06 11:46:39 error in payment: driver: bad connection
16m29s    newOrder         29.1        89.4  10737.4  36507.2  40802.2  45097.2  45097.2
2018/09/06 11:46:40 error in payment: driver: bad connection
16m30s    newOrder         17.0        89.4   9663.7  73014.4  85899.3 103079.2 103079.2
16m31s    newOrder         14.0        89.3   9126.8  40802.2  40802.2  73014.4  73014.4
16m32s    newOrder          6.0        89.2  36507.2  51539.6  53687.1  53687.1  53687.1
16m33s    newOrder          6.0        89.1  12348.0  17179.9  19327.4  19327.4  19327.4

- What was the impact?
Failed transacitons/poor performance. with 600 Warehouse worked without errors.

I have also seen the errors as shown below on the logs  -

E180906 16:04:11.378392 170902681 storage/consistency_queue.go:125  [replica consistency checker,n1,s1,r14753/3:/Table/109/2/1{44/10â<80>¦-51/8/â<80>¦}] computing own checksum: rpc error: code = DeadlineExceeded desc = context deadline exceeded.

**FEATURE REQUEST**

Please describe the feature you are requesting, as well as your proposed use case.

**Comment by maskayman** [comment]
[cockroach_lplcdb02a.log](https://github.com/cockroachdb/cockroach/files/2358672/cockroach_lplcdb02a.log)
[cockroach_lplcdb02b.log](https://github.com/cockroachdb/cockroach/files/2358674/cockroach_lplcdb02b.log)

**Comment by maskayman** [comment]
I have uploaded logs from 2 nodes of 9 nodes cluster.

**Comment by jordanlewis** [comment]
Hi @maskayman, normally that error message (bad connection) indicates that one of the nodes crashed. Did you observe any node crashes during your test? If so, please upload the logs from those nodes as well.

**Comment by maskayman** [comment]
No. The nodes were intact.

**Comment by jordanlewis** [comment]
You'll have to give us some more details then. How was the load generator configured? What connection strings did you give it for the nodes? Were you using a load balancer? What specs do the machines have? How did you load the data?

**Comment by maskayman** [comment]
1.	What connection strings did you give it for the nodes? 
Downloaded loadgen  from GitHub, compiled and used HAPROX


2.	Were you using a load balancer? 
Yes ha proxy on a separate node configured for the 9 db nodes
3.	I show HAPROXY command below -
[root@lplcdb01a Cockroach]# haproxy -f haproxy.cfg

[root@lplcdb01a Cockroach]# more haproxy.cfg

global
  maxconn 4096

defaults
    mode                tcp
    # Timeout values should be configured for your specific use.
    # See: https://cbonte.github.io/haproxy-dconv/1.8/configuration.html#4-timeout%20connect
    timeout connect     10s
    timeout client      1m
    timeout server      1m
    # TCP keep-alive on client side. Server already enables them.
    option              clitcpka

listen psql
    bind :26258
    mode tcp
    balance roundrobin
    option httpchk GET /health?ready=1
    server cockroach1 lplcdb02a.phx.aexp.com:26257 check port 8080
    server cockroach2 lplcdb02b.phx.aexp.com:26257 check port 8080
    server cockroach3 lplcdb02c.phx.aexp.com:26257 check port 8080
    server cockroach4 lplcdb02d.phx.aexp.com:26257 check port 8080
    server cockroach6 lplcdb02e.phx.aexp.com:26257 check port 8080
    server cockroach7 lplcdb01b.phx.aexp.com:26257 check port 8080
    server cockroach8 lplcdb01c.phx.aexp.com:26257 check port 8080
    server cockroach9 lplcdb01d.phx.aexp.com:26257 check port 8080
    server cockroach10 lplcdb01e.phx.aexp.com:26257 check port 8080
[root@lplcdb01a Cockroach]#


4.	What specs do the machines have? 
 
LSCPU
[root@lplcdb02a ~]# lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             8
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 62
Model name:            Intel(R) Xeon(R) CPU E7-4890 v2 @ 2.80GHz
Stepping:              7
CPU MHz:               2793.269
BogoMIPS:              5586.53
Hypervisor vendor:     VMware
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              38400K
NUMA node0 CPU(s):     0-7
 
 
[root@lplcdb02a ~]# cat /proc/meminfo
MemTotal:       16316804 kB
MemFree:          165212 kB
Buffers:          142572 kB
Cached:          8305988 kB
SwapCached:            0 kB
Active:          8132084 kB
Inactive:        7563696 kB
Active(anon):    5974480 kB
Inactive(anon):  1274856 kB
Active(file):    2157604 kB
Inactive(file):  6288840 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:       4194300 kB
SwapFree:        4194300 kB
Dirty:               104 kB
Writeback:             0 kB
AnonPages:       7247496 kB
Mapped:            46316 kB
Shmem:              1984 kB
Slab:             207564 kB
SReclaimable:     157876 kB
SUnreclaim:        49688 kB
KernelStack:       17984 kB
PageTables:        60760 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    12352700 kB
Committed_AS:   10338096 kB
VmallocTotal:   34359738367 kB
VmallocUsed:      219464 kB
VmallocChunk:   34359509404 kB
HardwareCorrupted:     0 kB
AnonHugePages:    100352 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:       10240 kB
DirectMap2M:    16766976 kB

Df-kh 
 
Filesystem            Size  Used Avail Use% Mounted on
/dev/mapper/rootvg-rootvol
                      9.8G  2.0G  7.3G  22% /
tmpfs                 7.8G     0  7.8G   0% /dev/shm
/dev/mapper/rootvg-lvamex
                      5.1G   25M  4.8G   1% /amex
/dev/sda1             190M  108M   73M  60% /boot
/dev/mapper/datavg-lvdata
                      246G   90G  145G  39% /data
/dev/mapper/rootvg-lvhome
                      2.0G  3.5M  1.9G   1% /home
/dev/mapper/rootvg-lvlogs
                      8.0G   19M  7.6G   1% /logs
/dev/mapper/rootvg-lvopt
                      7.1G  644M  6.1G  10% /opt
/dev/mapper/rootvg-lvvar
                      4.1G  496M  3.4G  13% /var
tmpfs                 7.8G  1.8M  7.8G   1% /tmp
zfsprod2a-nfs.phx.aexp.com:/export/install
                      500G  296G  205G  60% /install
zfsprod1a-nfs.phx.aexp.com:/export/idn_home
                      1.9T  504G  1.4T  28% /idn/home
netappphx01-svm1-lif1.phx.aexp.com:/Cockroach_Test
                      501G  1.1M  501G   1% /Cockroach_Backup


 
6.	This is how I loaded the data
 
./tpcc -drop -load -warehouses=1000 -split -scatter -duration=100s "postgresql://root@lplcdb02a:26257/tpcc?sslmode=disable"
 
7.	This is how I ran with 1000 Warehouses
./tpcc -run -warehouses=1000 -split -scatter -duration=1000s -tolerate-errors "postgresql://root@lplcdb01a:26258/tpcc?sslmode=disable"

**Comment by jordanlewis** [comment]
The latencies you're getting are very high. Perhaps you've overloaded the capacity of your nodes, latencies rise very high, and your haproxy configuration terminates the hung connections.

What kind of disks do you have on your db nodes? Spinning or ssds?

Can you try running a smaller number of warehouses first to see if things work ok? I would try to bisect the number - try 500, if that works ok, 750, etc. If you can't get anything to work, there's probably something wrong with your cluster configuration. If you can find a point at which the load does work consistently with low latencies, it's likely that the nodes are underprovisioned along some dimension.

For what it's worth, our normal test configuration for 1000 warehouses is 3 nodes with the 16-core highcpu configuration that Google Cloud provides, using SSDs and the `nobarrier` mount option. In that configuration, 1000 warehouses runs fine with low and steady latencies.

**Comment by maskayman** [comment]
Hi Jordan,
Can we have a quick call? I will make sure that my sysadmins will attend that call as well. 

We have SSDs (flash storage)

Yes, we have tried running with smaller number of warehouse starting from 10 then 100, 200, 400, 600 then 1000. We have also increased the number of nodes from 5 to 9 to 12. 

Since I have shared my infrastructure specifications, what recommendations do you have on our infrastructure? We see underutilized CPU configuration, on underutilized hardware. We would need more specific information for troubleshooting or reasonable configuration suggestions from you.

**Comment by maskayman** [comment]
Do you have any system settings like dirty ratio etc?

**Comment by drewdeally** [comment]
Jordon I will take it from here since this is not a CR problem.  Perhaps we will have to work with the hw team to make sure the config is proper.

**Comment by maskayman** [comment]
What config are you recommending that would work for COckroach? I don't see any issues at my side. What system setting would you recommend for Cockroach?

**Comment by drewdeally** [comment]
yes - I will respond with a email as follow-up
