### ISSUE TITLE
sql: support FOREIGN KEY constraints

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#2968]
A foreign key constraint specifies that the values in a column (or a group of columns) must match the values appearing in some row of another table and are used to maintain the referential integrity between two related tables.

**Comment by bdarnell** [comment]
As noted in #5957, when we support foreign keys will will also have to support the `CASCADE` and `RESTRICT` options on various `DROP` and `TRUNCATE` commands.

**Comment by dt** [comment]
I think we can go ahead and close this one and any remaining unimplemented behaviors (`CASCADE`, `SET NULL`) can get their own, more specific issues if/when we decide we want them.

**Comment by omidraha** [comment]
Please update this [doc](https://www.cockroachlabs.com/blog/building-application-cockroachdb-sqlalchemy-2/):

- We don’t yet support foreign keys.
