### ISSUE TITLE
sql: panic: select min(null)

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#29695]
Found with RSG.

**Comment by mjibson** [comment]
This is currently failing in the optimizer at https://github.com/cockroachdb/cockroach/blob/846a6e0ad878ec1a9ba72d08c3acb747150be026/pkg/sql/opt/optbuilder/scope.go#L878 because the type checker at https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/tree/type_check.go#L780 detects a NULL argument and returns DNull for the func instead of an actual func.

Commenting out the `return DNull` line of type_check.go:780 fixes this whole problem. I wonder if we should remove the `NullableArgs` property from functions altogether because it's possible to pass NULL to functions that bypasses the type system (`SELECT min((SELECT NULL))` for example).

I have a test that executes all variants of all builtins with different kinds of NULL (`NULL`, `NULL::typ`, `(SELECT NULL)::typ`) which passes with that line commented, suggesting that it's a performance optimization more than a correctness thing.

@knz thoughts?

**Comment by knz** [comment]
I *think* (but nathan would confirm) that we could also run into type ambiguity errors if we disable this…

**Comment by arjunravinarayan** [comment]
I am working on a fix on the `opt` side to fix the panic, without removing this optimization, by simply making `opt` able to deal with the `DNull` possibility. This will reduce the chance of a performance regression this late into the cycle. The conversation can continue, but any generalized fix that might regress performance should wait for the next release.
