### ISSUE TITLE
sql: support non-materialized VIEWs

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#2971]
Non-materialized views are essentially a form of query rewriting (PostgreSQL seems to implement them this way). There might be complexities surrounding view schema changes (e.g. `ALTER VIEW`).

**Comment by bdarnell** [comment]
As noted in #5957, when we support views will will also have to support the `CASCADE` and `RESTRICT` options on various `DROP` and `TRUNCATE` commands.
