### ISSUE TITLE
fix ./gossip/simulation

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#2976]
probably broken during the gossip-proto-refactor (?). Would be nice to run this again, in particular in light of #2967.

```
16:17 $ go build gossip/simulation/gossip.go
# command-line-arguments
gossip/simulation/gossip.go:201: network.Addrs undefined (type *simulation.Network has no field or method Addrs)
gossip/simulation/gossip.go:203: simNode.Addr undefined (type *simulation.Node has no field or method Addr)
gossip/simulation/gossip.go:210: invalid type assertion: val.(int64) (non-interface type []byte on left)
gossip/simulation/gossip.go:218: invalid type assertion: val.(int64) (non-interface type []byte on left)
gossip/simulation/gossip.go:316: nodes[i].Addr undefined (type *simulation.Node has no field or method Addr)
gossip/simulation/gossip.go:316: cannot use int64(cycle) (type int64) as type []byte in argument to node.AddInfo
gossip/simulation/gossip.go:318: nodes[i].Addr undefined (type *simulation.Node has no field or method Addr)
```

**Comment by spencerkimball** [comment]
We should probably make a unittest in that package which runs a simulation
so we know when it breaks.

I'm going to fix this up btw.

On Fri, Oct 30, 2015 at 4:19 PM, Tobias Schottdorf <notifications@github.com

**Comment by tschottdorf** [comment]
I think we use `*simulation.Network` in the `kv` tests, and `go test ./gossip/simulation/` passes right now. I think `go build ./gossip/simulation/gossip.go` is what we need for CI.

**Comment by spencerkimball** [comment]
Could you add that to the CI? I'll fix it as a second commit for this PR.

On Fri, Oct 30, 2015 at 4:24 PM, Tobias Schottdorf <notifications@github.com

**Comment by tschottdorf** [comment]
Sure, I'll add it after you've merged the fix.

**Comment by tamird** [comment]
Assigning to @tschottdorf per discussion above.
