### ISSUE TITLE
Replace usage of and then remove gossip update callback interface

### ISSUE THREAD

**Issue by spencerkimball** [cockroachdb/cockroach#2978]
A more natural callback interface is to get updates from a channel. We should replace the existing usage of the function based callback with the update channel.

**Comment by lizhongz** [comment]
Hi spencerkimball, I am working on this. 

I was wondering that the gossip update here means the update of system configuration or of info store. Since both of them use callback mechanism.

**Comment by tschottdorf** [comment]
@nvanbenschoten, is anything of this left when #3506 lands?

**Comment by nvanbenschoten** [comment]
Do you mean any of #3502? If so, most of the changes in #3502 were dealing with threading a `Stopper` into the constructors of `Gossip` and `Gossip.Server`, which is no longer needed with the notification channel approach, so I don't think there was any shared code. The issue itself should also be complete when #3506 lands.

**Comment by nvanbenschoten** [comment]
Actually, there is another callback layer within `Gossip.infoStore` that could use a similar treatment. I'll look into that after this PR goes through.

**Comment by petermattis** [comment]
We've decided not to do this for the time being. Gossip update callbacks are now serialized which achieves the primary benefit of a channel-based interface.
