### ISSUE TITLE
perf: upgrade from go1.10 to go1.11

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#29827]
`go1.11` was recently released: https://golang.org/doc/go1.11. I ran our standard benchmarks against it to get an idea of what kind of performance we can expect when we upgrade. This will may influence our decision of whether the upgrade before or after our 2.1 release.

All benchmarks were run on GCE `n1-standard-4` linux machines with the `nobarrier` SSD mount option. I ran 3 benchmarks, `kv0`, `kv95`, and `tpcc1-nowait`. Each benchmark was run on a single node cluster and on a three node cluster. Each configuration was run 5 times with `go1.10` and 5 times with `go1.11`. Each trial was run for 3 minutes, with a cluster wipe in-between.

```
name               old ops/sec  new ops/sec  delta
kv0-1node           5.78k ± 4%   6.41k ± 3%  +10.93%  (p=0.008 n=5+5)
kv0-3node           7.11k ± 2%   7.24k ± 1%   +1.81%  (p=0.056 n=5+5)
kv95-1node          9.63k ± 3%  10.58k ± 2%   +9.89%  (p=0.008 n=5+5)
kv95-3node          16.7k ± 1%   16.8k ± 4%   +0.52%  (p=0.151 n=5+5)
tpcc-nowait-1node    75.6 ± 4%    78.2 ± 3%   +3.49%  (p=0.056 n=5+5)
tpcc-nowait-3node    49.8 ± 2%    49.4 ± 5%     ~     (p=1.000 n=5+5)

name               old p50(ms)  new p50(ms)  delta
kv0-1node            10.5 ± 0%     9.4 ± 0%  -10.48%  (p=0.029 n=4+4)
kv0-3node            7.90 ± 0%    7.78 ± 2%     ~     (p=0.333 n=4+5)
kv95-1node           6.30 ± 0%    5.80 ± 0%   -7.94%  (p=0.079 n=4+5)
kv95-3node           3.44 ± 2%    3.40 ± 0%     ~     (p=0.444 n=5+5)
tpcc-nowait-1node    88.1 ± 5%    86.4 ± 3%     ~     (p=0.643 n=5+5)
tpcc-nowait-3node     176 ± 5%     178 ± 6%     ~     (p=0.881 n=5+5)

name               old p99(ms)  new p99(ms)  delta
kv0-1node            29.2 ± 4%    26.4 ± 5%   -9.33%  (p=0.008 n=5+5)
kv0-3node            28.3 ± 0%    28.3 ± 0%     ~     (all equal)
kv95-1node           19.9 ± 0%    17.8 ± 0%  -10.55%  (p=0.079 n=4+5)
kv95-3node           16.3 ± 0%    15.9 ± 2%   -2.21%  (p=0.095 n=4+5)
tpcc-nowait-1node     631 ± 6%     617 ± 3%     ~     (p=0.683 n=5+5)
tpcc-nowait-3node     772 ± 0%     765 ± 5%     ~     (p=0.968 n=4+5)
```

cc. @petermattis @a-robinson @benesch

**Comment by a-robinson** [comment]
I'd go for it, but that would have been my answer before seeing the numbers as well. It's too bad it only makes a real difference on single-node clusters.

**Comment by nvanbenschoten** [comment]
I inventoried the changes that will be included in `go1.11.1`. I found three that I think we should be aware of:
- https://github.com/golang/go/issues/27521
- https://github.com/golang/go/issues/27390
- https://github.com/golang/go/issues/27342

I'm not able to find any estimate of when `go1.11.1` will be released, but previous releases have typically gone about 6 weeks between the minor release and the first patch release. This would put the release of `go1.10.1` somewhere in early October.

My suggestion would be to upgrade the betas to `go1.11` now and update to `go1.11.1` as soon as it is available. Thoughts @bdarnell @petermattis?

**Comment by benesch** [comment]
At the very least I think we should bump master go1.11. I'm updating the builder now.

**Comment by nvanbenschoten** [comment]
Thanks @benesch.

**Comment by petermattis** [comment]
@nvanbenschoten Those 3 changes are all a bit disconcerting, though it seems extremely likely that go1.11.1 will be released before we release 2.1.

**Comment by nvanbenschoten** [comment]
Yes, that was my thought as well. I think we should move to `go1.11` for the next beta release so that we can begin testing with it as soon as possible.

**Comment by nvanbenschoten** [comment]
It doesn't look like we're going to release v2.1 with go1.11, so moving to 2.2.
