### ISSUE TITLE
Store: Fix check for existing overlapping replica

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#2989]
`Store.addReplicaInternal` and `CanApplySnapshot` use `rangesByKey.Has()` to detect if a range already exists, but this only looks at a single key so it may be incorrect when there have been multiple splits or merges. This check should be replaced with one that looks at the start and end points of the replica.

See #2944

**Comment by veteranlu** [comment]
@bdarnell happy to take a look

**Comment by bdarnell** [comment]
Cool, go for it.
