### ISSUE TITLE
Unable to SELECT from tables appearing in "show tables" on database

### ISSUE THREAD

**Issue by mura-admin** [cockroachdb/cockroach#29988]
**BUG REPORT**

Please describe the issue you observed, and any steps we can take to reproduce it:

```
root@:26257/userdb> show tables;
+----------------------+
|        Table         |
+----------------------+
| Client               |
| ClientAuthentication |
+----------------------+
(2 rows)

Time: 4.0984ms

root@:26257/userdb> select * from Client;
pq: relation "client" does not exist
root@:26257/userdb> select * from ClientAuthentication;;
pq: relation "clientauthentication" does not exist

root@:26257/userdb> show tables from userdb.public;
+----------------------+
|        Table         |
+----------------------+
| Client               |
| ClientAuthentication |
+----------------------+
(2 rows)

Time: 3.8137ms

root@:26257/userdb> select * from userdb.public.client;
pq: relation "userdb.public.client" does not exist
```

- Which version of CockroachDB are you using?
v2.0.5

- What did you do?
Selected on valid tables

- What did you expect to see?
Data queried from the select.

- What did you see instead?
relation does not exist error

- What was the impact?
Unable to select from table.

**Comment by asubiotto** [comment]
@mura-admin, This behavior is expected, unquoted identifiers are case insensitive (https://www.cockroachlabs.com/docs/v2.0/keywords-and-identifiers.html#rules-for-identifiers). It looks like you created your tables with double quotes, which means that you'll have to use `SELECT * FROM "Client";` if you want to keep the table name. I recommend renaming your table (https://www.cockroachlabs.com/docs/stable/rename-table.html) by running `ALTER TABLE "Client" RENAME TO client` and `ALTER TABLE "ClientAuthentication" RENAME TO clientauthentication` to not have to worry about this.
