### ISSUE TITLE
gossip: local infostore can diverge from remote infostore at startup

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#29992]
https://github.com/cockroachdb/cockroach/pull/29398 changed `infoStore.combine` to ignore infos that originated at the local node. This was done to prevent "loopback infos" which were causing confusion to parts of gossip that weren't expecting them such as `infoStore.mostDistant` and the assertion in `infoStore.addInfo` that local infos always have a ratcheting timestamp.

As noted in https://github.com/cockroachdb/cockroach/pull/29398#pullrequestreview-153595809, the downside to this approach is that the local infostore will be different from a remote infostore for a short period of time at startup. We don't have a scenario where this is a problem at this time, but it is surprising and might lead to an issue down the line.

Rather than rejecting locally generated infos in `infoStore.combine`, we could either limit their timestamps, remove the assertion in `infoStore.addInfos`, or ratchet the local monotonic clock.

@bdarnell Do you have a preference for any of these approaches or have an alternate approach?

**Comment by bdarnell** [comment]
Removing the assertion isn't safe - our locally-generated info won't propagate correctly without that. We still need to preserve monotonicity if we're going to accept loopback gossip. This could either mean general monotonicity protections as in #25109 or something special-cased to gossip's own monotonic clock.

**Comment by petermattis** [comment]
Hmm good point about monotonicity. The assertion is quite old. It was add in https://github.com/cockroachdb/cockroach/pull/2967 merged on Nov 7, 2015.
