### ISSUE TITLE
sql: eliminate mutation queue for schema changes

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#3000]
The mutation queue was added to queue up pending schema change mutations, which are processed in a FIFO order asynchronously. It was needed because we didn't want to make the index/column descriptors more complex, and thought we should use a different data structure for mutations.

It turns out, the descriptors themselves are going to have states (delete_only, write, public), and the mutation queue is really representing 1. descriptor state delete_only, 2. FIFO ordered schema changes, which can be modeled using the monotonic MutationID, and 3. Final state of schema change (delete_only or public). All these can be easily be modeled within a descriptor.

Furthermore, we have some bug which we can fix in the existing implementation with more code, but are more elegantly fixed without the mutation queue. For example, if a user adds a column and simultaneously drops the same column in another window, we will add the column and report on the window that ran the drop command, that the column doesn't exist. It would be nicer if we just deleted the column without applying the schema change.

**Comment by spencerkimball** [comment]
@vivekmenezes I'm clearing the 1.0 milestone from this issue. No way it's making it in. Please close if this is now moot.

**Comment by vivekmenezes** [comment]
I'm closing this because I don't see us changing our implementation away from the use of the mutation queue for a long long time.
