### ISSUE TITLE
sql: MATCH FULL is incorrectly implemented

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#30026]
This goes along with #20305.  Which is about implementing MATCH SIMPLE.

We don't implement MATCH FULL correctly.

Here's the definition of MATCH FULL:

> MATCH FULL considers a foreign key as valid if every foreign key column is
null or if all foreign key columns are not null and match the referenced
table.

We take this one step too far. 

* If all the values are NULL, it is considered valid (and shouldn't cascade updates or deletes). __We do this correctly.__
* If no values are NULL, they all need to exist in the referenced table. __We do this correctly.__
* If some values are NULL but not all, the reference is incorrect. __We incorrectly deal with this case.__ Instead check for values in the referenced table turning all the NULLs into a value that can be matched against.  

```sql
CREATE TABLE a (
  x INT
 ,y INT
 ,UNIQUE (x, y)
);
CREATE TABLE b (
  x INT
 ,y INT
 ,INDEX (x, y)
 ,FOREIGN KEY (x, y) REFERENCES a (x, y) ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO b VALUES (NULL,NULL);
# This should work. (and does)

INSERT INTO b VALUES (1, NULL);
# This should fail, due to it having a NULL. 
# But instead we get: foreign key violation: value [1 NULL] not found in a@a_x_y_key [x y]
# Postgres reports this correctly (note that I had to include MATCH FULL in the FK reference).
# ERROR:  insert or update on table "b" violates foreign key constraint "b_x_fkey"
# DETAIL:  MATCH FULL does not allow mixing of null and nonnull key values.

INSERT INTO a VALUE (1, NULL);

INSERT INTO b VALUE (1, NULL);
# This should fail, due to it having a NULL. But passes now that (1, NULL) exists in a.
# On postgres, it still fails due to the null/non-null mixing:
# ERROR:  insert or update on table "b" violates foreign key constraint "b_x_fkey"
# DETAIL:  MATCH FULL does not allow mixing of null and nonnull key values.
```

We even outright call this out in our docs:
https://www.cockroachlabs.com/docs/stable/foreign-key.html#null-values

> Multiple-column foreign keys only accept NULL values in these scenarios:
> * The row you're ultimately referencing—determined by the statement's other values—contains NULL as the value of the referenced column (i.e., NULL is valid from the perspective of referential integrity)
> * The write contains NULL values for all foreign key columns

**Comment by BramGruneir** [comment]
cc: @dt

**Comment by BramGruneir** [comment]
cc @vivekmenezes

**Comment by BramGruneir** [comment]
In #28896, I fixed the error in which we would cascade through NULL values, for both single and composite keys.  This issue is specific to the fact that we don't follow the correct SQL standard of MATCH FULL (and even document this incorrect version of it).

What makes this and #20305 important is that we encourage our enterprise customers to use interleaved tables and partitioning, which always involves composite keys, so they are much more prevalent that in a more classic SQL system.

**Comment by knz** [comment]
@BramGruneir I think you fixed this right?

**Comment by BramGruneir** [comment]
Yes!  With both #32693 and #32998.
