### ISSUE TITLE
sql: SQL20 query fails due to memory budget exceeded error

### ISSUE THREAD

**Issue by andy-kimball** [cockroachdb/cockroach#30050]
REPRO:

1. Start Cockroach DB on a GCE machine `(24 vCPUs, 32 GB memory)`, using default options.
2. Load TPCH data using the instructions in `2.1-sql-20`
3. Run the following query in the SQL console:
```
SELECT count(*) FROM lineitem JOIN supplier ON l_suppkey = s_suppkey
```

EXPECTED: This gets planned by the cost-based optimizer using a merge join, and should not exceed the memory budget, since both sides should be streamed.

ACTUAL: The query fails with an error:
```
Error: pq: root: memory budget exceeded: 10240 bytes requested, 134215680 currently allocated, 134217728 bytes in budget
```

Note that the heuristic planner chooses a hash join for this query, and that does *not* run out of memory.

**Comment by RaduBerinde** [comment]
@jordanlewis points out that https://github.com/cockroachdb/cockroach/pull/26914 might be responsible. Indeed, in that diff I only see `Grow`.
