### ISSUE TITLE
qa: BIT sql type

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#30067]
@vivekmenezes Please assign a QA buddy for this work.

**Comment by vivekmenezes** [comment]
@couchand you have been randomly assigned to QA this item

**Comment by nvanbenschoten** [comment]
@vivekmenezes, happy to QA this, although I was the primary reviewer of the code. Is that ok?

**Comment by vivekmenezes** [comment]
@nvanbenschoten I think it's okay to just go ahead and do it. Thanks!
