### ISSUE TITLE
roachpb: address TODO to remove needsRefresh from InitPutRequest

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#30077]
See #30041. This can be addressed in 2.2.

**Comment by tschottdorf** [comment]
This can be done now and not backported, right?

**Comment by nvanbenschoten** [comment]
Yes, although I think I'll still hold off for a few weeks in case it creates any instability. At a minimum, it will change txn refresh behavior (for the better!).
