### ISSUE TITLE
sql: investigate creation of possibly unneeded fk indexes

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#30079]
Consider this situation:
```
root@:26257/defaultdb> create table a (x int, y int, primary key (x, y));
CREATE TABLE

Time: 9.128283ms

root@:26257/defaultdb> create table b (u int, v int, w int, index (v, w), foreign key (w, v) references a (x, y));
CREATE TABLE

Time: 28.288934ms

root@:26257/defaultdb> show create table b;
  table_name |                         create_statement
+------------+-------------------------------------------------------------------+
  b          | CREATE TABLE b (
             |     u INT NULL,
             |     v INT NULL,
             |     w INT NULL,
             |     INDEX b_v_w_idx (v ASC, w ASC),
             |     CONSTRAINT fk_w_ref_a FOREIGN KEY (w, v) REFERENCES a (x, y),
             |     INDEX b_auto_index_fk_w_ref_a (w ASC, v ASC),
             |     FAMILY "primary" (u, v, w, rowid)
             | )
(1 row)

Time: 5.144715ms
```

We create the index `b_auto_index_fk_w_ref_a` because when a row in `a` is modified it needs to know if that modification will break any foreign key references from `b`, however, (as far as I can tell) that index is technically unnecessary in the presence of the index on `(v, w)`.

Perhaps something we can investigate handling once the optimizer can plan mutations.

cc @knz @BramGruneir @dt

**Comment by dt** [comment]
See also #8451

**Comment by lucy-zhang** [comment]
I'm closing in favor or #8451 - I think these basically capture the same underlying issue of not being able to use an index if the columns are in a different order, and the goal in 20.2 is to stop auto-creating indexes entirely anyway.
