### ISSUE TITLE
ui: jobs: Restore time estimates are off by an order of magnitude

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#30084]
When restoring TPCC on the 2.1 RC yesterday, Andy noticed that the estimated time of completion of the jobs was off:

![image](https://user-images.githubusercontent.com/21692034/45381237-c0f76b00-b5d2-11e8-9316-eb3f630fa89e.png)

![image](https://user-images.githubusercontent.com/21692034/45381255-ca80d300-b5d2-11e8-9273-c3618596a596.png)

For some of the restores we originally quote an estimated completion time of ~270 minutes, but that job finished in ~60 minutes.

cc @awoods187 @a-robinson

**Comment by a-robinson** [comment]
As another example, when restoring tpc-c 50k, the time estimates for restoring the stock table said that it was >99% done with <1 minute remaining for the last 40+ minutes of the 1 hour, 50 minute restore time.

**Comment by piyush-singh** [comment]
Alex also pointed out that we are a little over eager in our rounding:

![image](https://user-images.githubusercontent.com/21692034/45381367-22b7d500-b5d3-11e8-9240-626a67e54731.png)

**Comment by couchand** [comment]
I have never been happy with guessing at the time remaining since the very first Jobs page PR.  Way too hard to get even reasonably in real-world scenarios.

Took a look through the code again, and there don't seem to be any obvious logic errors.  @piyush-singh could you please run a job and provide side-by-side screenshots of the Jobs page in the UI and the corresponding data in the SQL shell for a few moments through the execution, perhaps a trend will emerge.

Definitely agree on the percentage rounding: that should be using floor, not round.

**Comment by piyush-singh** [comment]
[show_jobs.txt](https://github.com/cockroachdb/cockroach/files/2376525/show_jobs.txt)
[restore.zip](https://github.com/cockroachdb/cockroach/files/2376526/restore.zip)

@couchand not sure of the best way to share this, let me know if you want me to send these directly via slack. The restore folder has screenshots with timestamps at multiple points through a TPC-C 1k restore, and show_jobs.txt shows the output of `SHOW JOBS;` in the sql shell at corresponding timestamps to the screenshots.

Let me know if you need any other info to help diagnose/repro.

**Comment by couchand** [comment]
I've looked into your results @piyush-singh, and it does seem to me that this can be entirely chalked up to concerns about producing an estimate with too little input.  Here is a chart of how long we think we have left (y axis) versus how long we actually have left (x axis):

![time-estimates-versus-fraction](https://user-images.githubusercontent.com/793969/45646535-a1a88400-ba91-11e8-8c24-e12d27142cd0.png)

When looking at this trend I think there are two forces that come into play:

1) Before 5 minutes have passed, all the jobs are running in parallel.  After 10 minutes have passed, most of the jobs have completed, so the cluster is much quieter.
2) Before about 30% of a given job has completed, the estimates are wildly inaccurate.  This specific value probably depends on what else is happening, per the above.

**Comment by couchand** [comment]
My proposal to address this is to think of it as a UX concern.  By presenting the remaining time estimate to precise hours, minutes, and seconds, we make it seem like the estimate has more fidelity than it actually does.  We should just update it to report approximate values: "about 10 minutes remaining", "less than 5 minutes remaining", "about 30 seconds remaining"...
