### ISSUE TITLE
ui: TOTAL RANGES mismatch

### ISSUE THREAD

**Issue by maskayman** [cockroachdb/cockroach#30101]
Is this a bug report or a feature request?
I think so
If so, please fill out the template below and we'll be happy to help.

If not, or you're not sure, please file an issue on our forum instead: https://forum.cockroachlabs.com/. You'll get a faster response there for troubleshooting and general questions, and it's likely that someone else has encountered the same issue.

**BUG REPORT**

Please describe the issue you observed, and any steps we can take to reproduce it:

- Which version of CockroachDB are you using?
2.0.4
- What did you do?
Run TPCC
- What did you expect to see?
Total range count match between the overview tab and the database tab
- What did you see instead?
Mismatch
- What was the impact?
Confusion. Too many ranges on the overview that I was expecting.

**FEATURE REQUEST**

Please describe the feature you are requesting, as well as your proposed use case.

**Comment by vilterp** [comment]
Thanks for your report @maskayman. We are aware of this and have filed it as #24767, so I'm going to close this as a dup. As that issue explains, there are some categories of ranges (system ranges, database ranges) that don't show up on the databases page; we can fix this. The number is pretty small (22 ranges on a brand new cluster with no data, plus one new range for each `CREATE DATABASE`).
