### ISSUE TITLE
storage/engine: split up package

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#30114]
Capturing some discussion of future work that occurred in #30001, #30043 and #30082 or in discussions around those:

Currently MVCC logic and helpers share a package with rocksdb-interfacing cgo. It would be nice to split this up. 
- @benesch has suggested pulling the rocksdb-specific concrete implementations of interfaces out into  `rocksdb` sub package, leaving `engine` pure-go that just operates in terms of those interfaces. 
- @nvanbenschoten has suggested pulling pure MVCC logic out into a separate package that again just operated in terms of storage interfaces (which would be defined separately from the concrete rocksdb implementations, of course)

**Comment by nvanbenschoten** [comment]
`storage/engine` was moved to `storage` and the cgo bindings for RocksDB will be deleted when RocksDB is removed. Closing since there's not much more to do here.
