### ISSUE TITLE
sql: derive constraints for regex pattern matches like done for LIKE

### ISSUE THREAD

**Issue by ghost** [cockroachdb/cockroach#30124]
- Which version of CockroachDB are you using?
CCL v2.1.0-beta.20180910

- What did you do?
`explain select koopatroopas where field ~ '^yoshi'`

- What did you expect to see?
```
                 └── scan |             |
                           | table       | tm@primary
                           | spans       | /"yoshi"-/"yoshix"
```
- What did you see instead?
```
             └── scan |             |
                      | table       | tm@primary
                      | spans       | ALL
```
- What was the impact?
failed to save the princess

**Comment by benesch** [comment]
Huh, that's an interesting optimization you suggest! It is in general quite difficult to convert a regex to a span constraint, though perhaps it's something we could pursue. CC'ing the optimizer team: @andy-kimball.

In the meantime, you should see the correct span generated if you use the equivalent LIKE operator:

```
SELECT * FROM koopatroopas WHERE field LIKE 'yoshi%'
```

**Comment by knz** [comment]
still current
