### ISSUE TITLE
storage: liveness issues when upgrading from 2.0.4 to 2.0.5

### ISSUE THREAD

**Issue by asubiotto** [cockroachdb/cockroach#30142]
Submitting bug report on behalf of a user

I took a 6 node v2.0.4 cluster and decommissioned 1 node, which was then replaced by 1 v2.0.5 node in the same cluster. Now the nodes in this cluster seem broken in various ways and I am not sure if the cluster is healthy to continue the rolling upgrade:

Different node status reports by the nodes, first 2 not even reporting:

```
> for IP in 10.207.50.244 10.207.45.68 10.187.108.20 10.187.105.7 10.187.106.120 10.207.34.108 ; do echo "==== $IP ====" ; ssh -t $USER@$IP "sudo cockroach node status --certs-dir=/cockroach/certs --host=$IP --port=11400" ; done
==== 10.207.50.244 ====
Error: rpc error: code = Unknown desc = unable to get liveness for 7: node not in the liveness table
Failed running "node"
==== 10.207.45.68 ====
Error: rpc error: code = Unknown desc = unable to get liveness for 7: node not in the liveness table
Failed running "node"
==== 10.187.108.20 ====
+----+----------------------+--------+---------------------+---------------------+---------+
| id |       address        | build  |     updated_at      |     started_at      | is_live |
+----+----------------------+--------+---------------------+---------------------+---------+
|  2 | 10.207.50.244:11400  | v2.0.4 | 2018-09-11 21:05:22 | 2018-09-11 17:21:02 | false   |
|  3 | 10.207.45.68:11400   | v2.0.4 | 2018-09-11 21:05:23 | 2018-09-11 17:21:03 | true    |
|  4 | 10.187.108.20:11400  | v2.0.4 | 2018-09-11 21:05:24 | 2018-09-11 17:24:23 | true    |
|  5 | 10.187.105.7:11400   | v2.0.4 | 2018-09-11 21:05:25 | 2018-09-11 17:24:25 | true    |
|  6 | 10.187.106.120:11400 | v2.0.4 | 2018-09-11 21:05:18 | 2018-09-11 17:24:28 | true    |
|  7 | 10.207.34.108:11400  | v2.0.5 | 2018-09-11 21:05:19 | 2018-09-11 20:18:08 | true    |
+----+----------------------+--------+---------------------+---------------------+---------+
(6 rows)
==== 10.187.105.7 ====
+----+----------------------+--------+---------------------+---------------------+---------+
| id |       address        | build  |     updated_at      |     started_at      | is_live |
+----+----------------------+--------+---------------------+---------------------+---------+
|  2 | 10.207.50.244:11400  | v2.0.4 | 2018-09-11 21:05:22 | 2018-09-11 17:21:02 | false   |
|  3 | 10.207.45.68:11400   | v2.0.4 | 2018-09-11 21:05:23 | 2018-09-11 17:21:03 | true    |
|  4 | 10.187.108.20:11400  | v2.0.4 | 2018-09-11 21:05:24 | 2018-09-11 17:24:23 | true    |
|  5 | 10.187.105.7:11400   | v2.0.4 | 2018-09-11 21:05:25 | 2018-09-11 17:24:25 | true    |
|  6 | 10.187.106.120:11400 | v2.0.4 | 2018-09-11 21:05:28 | 2018-09-11 17:24:28 | true    |
|  7 | 10.207.34.108:11400  | v2.0.5 | 2018-09-11 21:05:19 | 2018-09-11 20:18:08 | true    |
+----+----------------------+--------+---------------------+---------------------+---------+
(6 rows)
==== 10.187.106.120 ====
+----+----------------------+--------+---------------------+---------------------+---------+
| id |       address        | build  |     updated_at      |     started_at      | is_live |
+----+----------------------+--------+---------------------+---------------------+---------+
|  2 | 10.207.50.244:11400  | v2.0.4 | 2018-09-11 21:05:22 | 2018-09-11 17:21:02 | false   |
|  3 | 10.207.45.68:11400   | v2.0.4 | 2018-09-11 21:05:23 | 2018-09-11 17:21:03 | true    |
|  4 | 10.187.108.20:11400  | v2.0.4 | 2018-09-11 21:05:24 | 2018-09-11 17:24:23 | true    |
|  5 | 10.187.105.7:11400   | v2.0.4 | 2018-09-11 21:05:25 | 2018-09-11 17:24:25 | true    |
|  6 | 10.187.106.120:11400 | v2.0.4 | 2018-09-11 21:05:28 | 2018-09-11 17:24:28 | true    |
|  7 | 10.207.34.108:11400  | v2.0.5 | 2018-09-11 21:05:29 | 2018-09-11 20:18:08 | true    |
+----+----------------------+--------+---------------------+---------------------+---------+
(6 rows)
==== 10.207.34.108 ====
+----+----------------------+--------+---------------------+---------------------+---------+
| id |       address        | build  |     updated_at      |     started_at      | is_live |
+----+----------------------+--------+---------------------+---------------------+---------+
|  2 | 10.207.50.244:11400  | v2.0.4 | 2018-09-11 21:05:22 | 2018-09-11 17:21:02 | false   |
|  3 | 10.207.45.68:11400   | v2.0.4 | 2018-09-11 21:05:23 | 2018-09-11 17:21:03 | false   |
|  4 | 10.187.108.20:11400  | v2.0.4 | 2018-09-11 21:05:24 | 2018-09-11 17:24:23 | false   |
|  5 | 10.187.105.7:11400   | v2.0.4 | 2018-09-11 21:05:25 | 2018-09-11 17:24:25 | false   |
|  6 | 10.187.106.120:11400 | v2.0.4 | 2018-09-11 21:05:28 | 2018-09-11 17:24:28 | false   |
|  7 | 10.207.34.108:11400  | v2.0.5 | 2018-09-11 21:05:29 | 2018-09-11 20:18:08 | true    |
+----+----------------------+--------+---------------------+---------------------+---------+
(6 rows)
```

The nodes are reporting differently in the UI, and showing UNAVAILABLE RANGES:

![](https://discourse-cdn-sjc2.com/standard14/uploads/cockroachlabs/original/1X/13c4ac2644dc601e0737289b933a53d264bab5f2.png)

![](https://discourse-cdn-sjc2.com/standard14/uploads/cockroachlabs/original/1X/f3b739db23caf33aedaa4bada024a07a1aa608b7.png)

![](https://discourse-cdn-sjc2.com/standard14/uploads/cockroachlabs/original/1X/5aa754f7f0985c2cb119c1ea24ce3278f87dfb03.png)

![](https://discourse-cdn-sjc2.com/standard14/uploads/cockroachlabs/original/1X/265ca247a8a8eb51b6b7db378c757042119c4842.png)

**Comment by a-robinson** [comment]
Well that's certainly not good. A debug zip would be great along with the output of `cockroach debug gossip-values` on the different nodes. There's a chance that it hit the "gossip partition" bug (https://github.com/cockroachdb/cockroach/issues/24753 / https://github.com/cockroachdb/cockroach/issues/27731).

If it did hit that bug, then restarting the nodes would fix the problem. Even if it is something else, then restarting the nodes is unlikely to hurt anything. At this point, even upgrading would be fine (assuming their upgrade process is just restarting with a new binary, not decommissioning anything), given that upgrades between patch versions are reversible.

**Comment by fat0** [comment]
We are treating our nodes like cattle, not pets. We are running on AWS and the ASG terminates decommissioned nodes. Please try to re-create this in your lab and test further. I have given you all the info I have. I can try to run `cockroach debug gossip-values` on the current nodes for you but not sure if I have the time to.

**Comment by fat0** [comment]
Did more testing on our end, upgrade in place without decommissioning hosts works. Upgrading by replacing hosts fails.

**Comment by petermattis** [comment]
@fat0 I'd be willing to bet this is the gossip partition bug which we can reproduce. If you have logs from near the time of the incident I can make a full determination. We have a mitigation for this issue which we've backported to the 2.0 branch, but which has not yet made it into a release. And we have a more complete fix in the development branch that branch that we should consider backporting. Before doing so, it would be nice to confirm that you're hitting the same bug, which the logs from the time of an incident would show.

**Comment by petermattis** [comment]
@fat0 I'd need logs from all of the nodes. The evidence is unfortunately distributed across all of them. I only need logs for the time period of the outage. In fact, I only need the logs that contain `gossip client` and `gossip server` (and the subsequent lines). Basically, I'm trying to piece together the state of the gossip network during the time of the outage. Feel free to send all of the logs from every node if that would be easier for you.

**Comment by fat0** [comment]
@petermattis - I sent the logs to your gmail :)

**Comment by fat0** [comment]
@petermattis-square - want to make sure this is clear in case it was missed earlier. When we push a change, we do a rolling replacement of all the nodes, ie we decommission a node and then the ASG terminates it, and then a new nodes comes up and joins the cluster. We applied this same method when upgrading and that is when the cluster broke.

**Comment by petermattis** [comment]
@fat0 Yep, understood. Thanks for the reiteration of the scenario which caused the breakage.

**Comment by tschottdorf** [comment]
@petermattis looks like there's little to do here (except figuring out the backports). I'll leave it in your court, feel free to close.

**Comment by petermattis** [comment]
I took another look at the backports. We already have Alex's change to proactively renew the range 1 lease which is the first line of protection against gossip partitions. I'm uncomfortable backporting the changes to increase the frequency of gossiping the sentinel key. That leaves us with 2.0.6 being able to recover from a gossip partition, though such partitions may temporarily exist for up to 2min.
