### ISSUE TITLE
sql: Large spikes of lease-release batch requests every 3m30s

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#30206]
I had a 30 node cluster for running tpc-c 10k tests. I came back to my desk well after some test runs had finished up, meaning there was no SQL workload at all on the cluster and hadn't been for over an hour. I checked out the "Distributed" dashboard in the admin UI, and saw this:

<img width="914" alt="screen shot 2018-09-12 at 11 54 53 pm" src="https://user-images.githubusercontent.com/7085343/45505422-32115c80-b752-11e8-8019-58312a2a3488.png">

Very large spikes of batch requests every 3 minutes and 30 seconds. I did some digging via logspy during one of these spikes to see what these requests were (`/debug/logspy?count=1000&duration=60s&grep=sending%20batch`). I confirmed that the steady background stream was just the timeseries system doings its thing (helpfully marked with the "ts-poll" log tag), and found that the spikes were all caused by the SQL lease management infrastructure (helpfully marked with the "lease-release" log tag), mostly sending requests to the system config span (r7) in very quick succession:

```
...
I180913 04:51:41.529254 35094806 kv/dist_sender.go:1304  [intExec=lease-release,n21,txn=05d63ee5,ts=1536814301.528584487,0] r7: sending batch 1 Get to (n1,s1):1
I180913 04:51:41.529279 35094890 kv/dist_sender.go:1304  [intExec=lease-release,n21,txn=3f0f8d63,ts=1536814301.529075480,0] r7: sending batch 1 Get to (n1,s1):1
I180913 04:51:41.529329 35094652 kv/dist_sender.go:1304  [intExec=lease-release,n21,txn=afcedec1,ts=1536814301.528438911,0] r7: sending batch 1 Get to (n1,s1):1
I180913 04:51:41.529446 35094900 kv/dist_sender.go:1304  [intExec=lease-release,n21,txn=3d541eb8,ts=1536814301.528467050,0] r7: sending batch 1 Get to (n1,s1):1
I180913 04:51:41.529796 35094826 kv/dist_sender.go:1304  [intExec=lease-release,n21,txn=106ace19,ts=1536814301.528471565,0] r7: sending batch 1 Get to (n1,s1):1
I180913 04:51:41.530116 35094890 kv/dist_sender.go:1304  [intExec=lease-release,n21,txn=3f0f8d63,ts=1536814301.529075480,0] r7: sending batch 1 Get to (n1,s1):1
I180913 04:51:41.530186 35094806 kv/dist_sender.go:1304  [intExec=lease-release,n21,txn=05d63ee5,ts=1536814301.528584487,0] r7: sending batch 1 Get to (n1,s1):1
I180913 04:51:41.530230 35094900 kv/dist_sender.go:1304  [intExec=lease-release,n21,txn=3d541eb8,ts=1536814301.528467050,0] r7: sending batch 1 Get to (n1,s1):1
I180913 04:51:41.530255 35094652 kv/dist_sender.go:1304  [intExec=lease-release,n21,txn=afcedec1,ts=1536814301.528438911,0] r7: sending batch 1 Get to (n1,s1):1
I180913 04:51:41.530375 35094826 kv/dist_sender.go:1304  [intExec=lease-release,n21,txn=106ace19,ts=1536814301.528471565,0] r7: sending batch 1 Get to (n1,s1):1
I180913 04:51:41.530763 35094652 kv/dist_sender.go:1304  [intExec=lease-release,n21,txn=afcedec1,ts=1536814301.528438911,0] r7: sending batch 1 Get to (n1,s1):1
I180913 04:51:41.530807 35094890 kv/dist_sender.go:1304  [intExec=lease-release,n21,txn=3f0f8d63,ts=1536814301.529075480,0] r7: sending batch 1 Get to (n1,s1):1
I180913 04:51:41.530824 35094806 kv/dist_sender.go:1304  [intExec=lease-release,n21,txn=05d63ee5,ts=1536814301.528584487,0] r7: sending batch 1 Get to (n1,s1):1
...
```

I also did a logspy specifically to get more details on what the lease-release process was doing, but didn't dig through it too much myself:
[lease-release-logspy.txt](https://github.com/cockroachdb/cockroach/files/2380415/lease-release-logspy.txt)

I will say, though, that it seems kind of silly that in order to delete table leases we run a SQL query that has to acquire table leases.

Again, this was on a cluster that hadn't had any SQL clients connected to it for more than an hour, and here it was spiking up to nearly a thousand batch requests per second (~30 qps per each of the 30 nodes in the cluster) every few minutes.

@vivekmenezes is this expected? Handing off to you to triage.

**Comment by tschottdorf** [comment]
Can #28725 explain that many RPCs? I thought it did "50 leases at a time". How does that add up?

**Comment by vivekmenezes** [comment]
I thought we might as well fix this issue :-)
