### ISSUE TITLE
Init new cluster spams errors on multiple stores

### ISSUE THREAD

**Issue by dendon** [cockroachdb/cockroach#30224]
**BUG REPORT**

Please describe the issue you observed, and any steps we can take to reproduce it:

- Which version of CockroachDB are you using?
v2.1.0-beta.20180910
v2.0.5

- What did you do?
`cockroach-server/cockroach --logtostderr=INFO --certs-dir=certs --cache=.25 --max-sql-memory=.25 --store=path=/mnt/sdb/cockroach-data,attrs=ssd --store=path=/mnt/sdc/cockroach-data,attrs=ssd --store=path=/mnt/sdd/cockroach-data,attrs=ssd start`

```
E180914 01:55:33.320130 1018 storage/queue.go:778  [replicate,n1,s1,r13/1:/Table/1{6-7}] [n1,s1,r13/1:/Table/1{6-7}]: unable to add replica (n1,s2):?; node already has a replica
E180914 01:55:33.520727 1019 storage/queue.go:778  [replicate,n1,s1,r31/1:/Table/2{0-1}] [n1,s1,r31/1:/Table/2{0-1}]: unable to add replica (n1,s3):?; node already has a replica
E180914 01:55:33.721416 1020 storage/queue.go:778  [replicate,n1,s1,r15/1:/Table/1{8-9}] [n1,s1,r15/1:/Table/1{8-9}]: unable to add replica (n1,s3):?; node already has a replica
E180914 01:55:33.921971 42 storage/queue.go:778  [replicate,n1,s1,r14/1:/Table/1{7-8}] [n1,s1,r14/1:/Table/1{7-8}]: unable to add replica (n1,s3):?; node already has a replica
E180914 01:55:34.122777 1022 storage/queue.go:778  [replicate,n1,s1,r9/1:/Table/1{2-3}] [n1,s1,r9/1:/Table/1{2-3}]: unable to add replica (n1,s3):?; node already has a replica
E180914 01:55:34.323352 909 storage/queue.go:778  [replicate,n1,s1,r3/1:/System/NodeLiveness{-Max}] [n1,s1,r3/1:/System/NodeLiveness{-Max}]: unable to add replica (n1,s2):?; node already has a replica
E180914 01:55:34.523953 1023 storage/queue.go:778  [replicate,n1,s1,r13/1:/Table/1{6-7}] [n1,s1,r13/1:/Table/1{6-7}]: unable to add replica (n1,s3):?; node already has a replica
```

This  error seems to continue on and on.

**Comment by asubiotto** [comment]
HI @dendon,

Thanks for submitting this issue. Did you list two versions because you were doing an upgrade/running a mixed version cluster? If so I think these logs could be attributed to some mixed version incompatibilities with regards to replica rebalancing although I am not sure.

cc @a-robinson, want to get this on your radar

**Comment by a-robinson** [comment]
Looks like it was actually a regression between 1.1 and 2.0. Although I should note that the behavior in both cases is the same, it's just that we didn't previously spam the logs about it. I'm guessing that's what @dendon meant by listing both versions -- they're both affected by it.

**Comment by dendon** [comment]
Hey,

I listed both versions, because I tested both version.
The servers were all just created and I simply tried to start cockroach with the mentioned command.

The database was meant to be just run as 1 node because it was meant as a sandbox.

**Comment by a-robinson** [comment]
> The database was meant to be just run as 1 node because it was meant as a sandbox.

In that case, running with more than 1 store isn't going to do any good. Replicas will only ever be stored on the first specified store of a single-node cluster. I'd suggest only specifying the one store.

If you do want to test out cockroachdb's replication and resilience in your one-machine sandbox, though, you'd be better off running 3 separate cockroach processes on the same machine (as in https://www.cockroachlabs.com/docs/stable/start-a-local-cluster.html).

I'll have a fix out for the logging in a few minutes, but it won't change the fact that all replicas will be kept in the first store in a single node cluster.

**Comment by dendon** [comment]
> In that case, running with more than 1 store isn't going to do any good. Replicas will only ever be stored on the first specified store of a single-node cluster. I'd suggest only specifying the one store.

Yeah, that's what I noticed as well, that having more than 1 store is irrelevant, as only one is used.
After encountering this, I also found another thread where it was stated that it is a known limitation.

> If you do want to test out cockroachdb's replication and resilience in your one-machine sandbox, though, you'd be better off running 3 separate cockroach processes on the same machine (as in https://www.cockroachlabs.com/docs/stable/start-a-local-cluster.html).

I was actually just doing some testing as I wanted to see if that would give any benefit.

> I'll have a fix out for the logging in a few minutes, but it won't change the fact that all replicas will be kept in the first store in a single node cluster.

It's just a bit confusing, at least for me, that an ongoing logging of an error, is actually more meant like a warning as everything works regardless.
