### ISSUE TITLE
distsql: swallow errors once the limit is satisfied

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#30235]
Once a proc's limit is satisfied, the proc in question starts draining its inputs. Once this happens, I think it can swallow all errors from its inputs (at least a `ReadWithinUncertaintyInterval` errors).
This might allow us to give some guarantees about automatic retries of some `limit 1` queries (since you'd think the error either is detected before any results are streamed to the client or after the limit is satisfied).

cc @bdarnell @RaduBerinde

**Comment by jordanlewis** [comment]
Didn't you finish this @andreimatei?

**Comment by andreimatei** [comment]
yes, this was done in #32401. Thanks.
