### ISSUE TITLE
cli: command output should be formatted to fit a reasonable terminal width

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#30244]
As noticed in https://github.com/cockroachdb/cockroach/pull/30081#issuecomment-420715929 `node status` outputs lines are now >150 characters in length which does not format nicely on a reasonable terminal width. We should take a pass over all of the CLI commands and make sure that their output formats nicely on a reasonable terminal width. What is reasonable? I'm not sure. My default terminal width is 118. I imagine 100 would be reasonable.

**Comment by arctica** [comment]
I have a terminal with 140 width and this is what `cockroach help sql` looks like:

![Screenshot from 2021-03-06 01-49-02](https://user-images.githubusercontent.com/870630/110160277-b2751d80-7de3-11eb-9fba-05a1d82e2d13.png)

Additionally the SQL shell is behaving super weird when I arrow-up to get to some command in the history that exceeds the width of a line and then start typing each new character will result in a new line being printed and the beginning and end of the lines not showing. When I press enter the correct SQL is executed though. This is on a pretty much standard Ubuntu 20.10 install with no modifications afaik. Have not seen other apps behave this weird.

![Screenshot from 2021-03-06 01-53-00](https://user-images.githubusercontent.com/870630/110160524-07b12f00-7de4-11eb-956e-dc6550784353.png)

**Comment by knz** [comment]
I am going to close this issue. Here are the answers to the 3 issues raised so far:

1. from @petermattis  - the width of the output is an inherent property of the table format. You can use `--format=records` got get a compact, more easily parseable output.
2. from @arctica , regarding the output of `cockroach help`. This is handled in #62304
3. from @arctica regardin the behavior of the 'arrow up' key. This is a known limitation in libedit, already tracked in this issue: #21826
