### ISSUE TITLE
*log.safeError: stopper.go:182: runtime.plainError: send on closed channel

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#30251]
https://sentry.io/cockroach-labs/cockroachdb/issues/687334906/

```
*log.safeError: stopper.go:182: runtime.plainError: send on closed channel
  File "github.com/cockroachdb/cockroach/pkg/storage/replica_proposal.go", line 127, in finishApplication
  File "github.com/cockroachdb/cockroach/pkg/storage/replica_proposal.go", line 118, in finishApplication
  File "github.com/cockroachdb/cockroach/pkg/storage/replica.go", line 5503, in processRaftCommand
  File "github.com/cockroachdb/cockroach/pkg/storage/replica.go", line 4271, in handleRaftReadyRaftMuLocked
  File "github.com/cockroachdb/cockroach/pkg/storage/store.go", line 3876, in func1
...
(9 additional frame(s) were not displayed)

stopper.go:182: runtime.plainError: send on closed channel
```

**Comment by nvanbenschoten** [comment]
I don't know what to make of this. We never close this channel. I audited every use of it and they all look good.

**Comment by petermattis** [comment]
I too audited all of the uses and concur that this can't possibly happen. We never close this channel. We only ever assign `ProposalData.doneCh` when a `ProposalData` is constructed (and we set it to a new channel) and when signaling a proposal is done where we set it to `nil`. My only theory is that we're somehow calling `ProposalData.signalProposalResult` concurrently and that caused this error. But I'd expect us to see other errors in this area if that were true.

I'd be willing to close this as impossible/unreproducible. If it ever comes up again we'll certainly start pay attention.

**Comment by nvanbenschoten** [comment]
> My only theory is that we're somehow calling ProposalData.signalProposalResult concurrently and that caused this error. But I'd expect us to see other errors in this area if that were true.

Yes, I had the same thought and explored that theory, but I convinced myself that that was impossible as well. 

I also looked through the runtime logic in `runtime.chansend` surrounding this error and found nothing suspicious (e.g. could this be caused by a data race on a chan object?). The panic can be hit either if we're sending on a closed channel or we're sending on a channel with insufficient capacity, we block, and the channel is closed while we're blocking. The second case isn't possible for this channel because we always give it enough capactity, so we must be hitting the first case. That also shouldn't be possible because we never close the channel ourselves.

**Comment by nvanbenschoten** [comment]
Oh, it looks like sentry says the line number of the panic in `runtime.chansend` was `185`. This confirms that we're in the first case where we're sending on a channel that has already been closed.

**Comment by nvanbenschoten** [comment]
Closing as unreproducible. I set sentry to ignore the issue until it occurs again.

**Comment by nvanbenschoten** [comment]
By the way, thanks for double checking this @petermattis.
