### ISSUE TITLE
Build fails on Linux Mint 17.2 Virtualbox

### ISSUE THREAD

**Issue by shivshankardayal** [cockroachdb/cockroach#3026]
I successfully compiled and ran it on Mac OS 10.11 but on Linux Mint 17.2 build fails. Also, a tool 6g consumes more than 3GB RAM during compilation. It caused my 5GB virtual machine to eat 3GB of swap. Worse is that while compiling storage/engine/rocksdb it gives make error and no helpful message about error.

**Comment by tamird** [comment]
`6g` is not part of the Go distribution as of 1.5. Cockroach currently requires Go 1.5. Can you try again after upgrading your Go toolchain?

**Comment by shivshankardayal** [comment]
Thanks. I checked that on Mac go was 1.5 while on Linux it was 1.2.1 which was stock. After upgrading Go to 1.5.1 it compiles cleanly and no problems of 6g. Thanks for help.
