### ISSUE TITLE
build: deadlock tests should be run somewhere

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#30265]
When @nvanbenschoten and I tried to find the deadlock that we eventually fixed in #30264, we spent about 15m looking through stack traces for the goroutine to blame. Seeing nothing, we tried to reproduce the deadlock locally—again, nothing! Then we turned on the deadlock detector, and 10s later we had the answer.

The deadlock detector is great. We should run it in CI at least nightly.

**Comment by petermattis** [comment]
I recall that we disabled the combo of stress and deadlock recently because it had too many false positives due to the massive slowdown. Perhaps we should reintroduce it, but with a stress parallelism of 1. Or perhaps not even stress, but a test run with deadlock enabled.

**Comment by benesch** [comment]
The deadlock detector actually rarely caused stress jobs to run into the timeout the way that the race detector does. We disabled the stress/deadlock combo because it seemed like a waste of resources. You don't typically need stress to get the deadlock detector to fire; it usually fires on the first run or not at all. It had been a long time since the stress/deadlock combo had found a bug. 

> Or perhaps not even stress, but a test run with deadlock enabled.

This is exactly what I was thinking. It shouldn't take more than 10m to run all the tests under the deadlock detector, which is completely worth it. The stress/deadlock combo, by contrast, required several hours of agent time.
