### ISSUE TITLE
importccl: support importing Avro data 

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/cockroach#30283]
**FEATURE REQUEST**

Avro is a popular data interchange format.  Spanner for example supports data export in Avro format.  Ability to import data in Avro will reduce friction in adoption.  `avro cat` can be used to dump data in CSV and mostly works; however, the CSV file generated is not pure CSV compliant and cannot be used to CockroachDB.  

An Avro import tool should:

- [ ] suggest CockroachDB schema 
- [ ] allow field names translation in CockroachDB schema  
- [ ] reporting and skipping source rows that have errors but continue otherwise

**Comment by mwang1026** [comment]
https://github.com/cockroachdb/cockroach/pull/43104
https://github.com/cockroachdb/cockroach/pull/43971
