### ISSUE TITLE
ui: custom chart tooltips don't work so well when using the "per node" option on large clusters

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#30286]
Clearly not very important right now since this is just a debug page, but we may have to grapple with this more meaningfully when a per-node breakdown option get added to the main dashboards.

<img width="1349" alt="screen shot 2018-09-11 at 7 50 57 pm" src="https://user-images.githubusercontent.com/7085343/45632978-457b3b00-ba64-11e8-9eeb-0cdf618628c5.png">

**Comment by knz** [comment]
cc @couchand

**Comment by couchand** [comment]
Yep, 😿.   We've got some nice designs for dealing with per-node charts of large clusters, cleaning this up for 2.2 is definitely a priority.

cc @piyush-singh @josueeee

**Comment by piyush-singh** [comment]
Definitely, @josueeee's designs are a fantastic way to handle large node counts (for 2.2):

![image](https://user-images.githubusercontent.com/21692034/45640756-7ddd4200-ba81-11e8-9db8-2d0fbdfa226a.png)

**Comment by couchand** [comment]
Thanks for posting the screenshot @piyush-singh. It does look like we'll still need to do some iteration here to solve the problem described in this issue: if there are too many nodes, the tooltip will just extend past the visible area.  It seems like at some point we should just show a subset of the node values, or a summary of some kind, and possibly provide a way to drill into more details if needed.

**Comment by knz** [comment]
Also maybe instead of using a list use a grid of nodes with little square boxes and the node number inside. And only display the hostname when hovering over the node number.

**Comment by a-robinson** [comment]
Just a note that this is actually pretty painful in practice when there's just one outlier in a per-node graph and you really want to know which node it is. I look forward to some sort of solution :)
