### ISSUE TITLE
ui: timeseries dashboard pages are really slow on large clusters

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#30287]
I was running a 120 node cluster last week as part of TPC-C 50k testing, and the UI was really, really bogging down my browser whenever I had pages with graphs open. I believe it was a client side issue (although I'm sure that loading all the timeseries in the database isn't easy, either) given the way Chrome occasionally became unresponsive.

It didn't help that sometimes the time span selector would automatically switch from 10 minutes to 6 hours when I would reload or switch dashboards without me telling it to. I don't know what was going on there.

I realize this isn't a particularly useful issue since I didn't record any data about the slowness or track it down to anything specific, but I'm planning to spin up another such cluster again for a day this week. Is there anything you'd find useful for me to do/record then? Would you like to poke at it when it's up and running?

@couchand

**Comment by couchand** [comment]
I'm not surprised that there would be trouble trying to make all the per-node requests.  We'll need to look at this pretty closely in the next release cycle.  There will be engineering work and likely also design/product work to address.  Thanks for reporting @a-robinson, no more details needed at the moment.

cc @piyush-singh

**Comment by piyush-singh** [comment]
cc @dhartunian this came up again for a customer recently. We had some plans to tackle tech debt and refactoring this release, and I know we are thinking through possible changes to our charting library. Flagging this to be part of the consideration.

**Comment by dhartunian** [comment]
This was resolved via #62463 in #63087
