### ISSUE TITLE
sql: ./cockroach sql should heartbeat during open transaction

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#3031]
since the transaction coordinator declares a transaction abandoned after (currently) 10 seconds of inactivity, demos of the SQL capability may take the form

```sql
BEGIN TRANSACTION;
INSERT INTO table VALUES(1,'a');
// explain something; 10 seconds pass
COMMIT;
query error: kv/txn_coord_sender.go:376: transaction is already committed or aborted
```

which is not ideal.

While in a transaction, the client should send one-off `SELECT 1;` in the background.

**Comment by tamird** [comment]
`SELECT 1` won't actually help you here, since it won't touch KV at all. Just tested this locally, for what it's worth.

**Comment by tamird** [comment]
LGTM

**Comment by tschottdorf** [comment]
ah, right. Ok, we'll need to do something smarter here. Potentially even a keep-alive RPC is the only clean way to go forward.

**Comment by petermattis** [comment]
If our client protocol was connection oriented we could have the server recognize when the client connection closed unexpectedly and abort the transaction. This would be straightforward to do with either gRPC or pgwire.

**Comment by petermattis** [comment]
Now that we've switched to pgwire, is there something we can/should do here?

**Comment by tamird** [comment]
Yeah, we should consider blurring the line between the pg server and the
CoordTxnSender so that we can keep transactions from timing out in an
interactive console (continue heartbeating so long as the pg connection is
open).

An easier hack is to send an empty KV batch from pg, which will keep the
transaction coordinator's heartbeat running.

**Comment by petermattis** [comment]
How would `pgwire` know it is an interactive session? Should we send a `SET INTERACTIVE = true` statement that the cli would send when opening a connection?

**Comment by tamird** [comment]
Doesn't have to be an interactive session; you could keep the heartbeat going so long as the connection stays open.

**Comment by andreimatei** [comment]
Would this issue be causing this error?
```
W0216 23:13:52.044318 22374 kv/txn_coord_sender.go:637  heartbeat to "sql/executor.go:396 sql" id=97934d2f key=/System/"desc-idgen" rw=true pri=0.02959091 iso=SERIALIZABLE stat=PENDING epo=0 ts=1455682422.039575827,0 orig=1455682422.039575827,0 max=1455682422.289575827,0 failed: retry txn "sql/executor.go:396 sql" id=97934d2f key=/System/"desc-idgen" rw=true pri=0.02959091 iso=SERIALIZABLE stat=PENDING epo=0 ts=1455682427.041274741,0 orig=1455682422.039575827,0 max=1455682422.039575827,0
```

which in turn leads to one of the following when issuing a new statement in the same txn:

```
query error: pq: kv/txn_coord_sender.go:336: transaction must not write on multiple coordinators
``` 
or
```
query error: pq: txn aborted "sql/executor.go:396 sql" id=c3ae6c42 key=/System/"desc-idgen" rw=true pri=0.00927881 iso=SERIALIZABLE stat=PENDING epo=0 ts=1455682705.697667175,0 orig=1455682705.697667175,0 max=1455682705.947667175,0
```

If so, is this issue on anybody's list? It's a big problem :)

**Comment by tschottdorf** [comment]
that first error seems like a standard retry, so no.

The second error indeed looks like a timed-out transaction and the SQL gateway would then abort it (this is code you've been looking at a lot ;) ).

**Comment by andreimatei** [comment]
I see it using the shell. Doing a `BEGIN; CREATE TABLE x.t (a INT);` then waiting a bit and attempting a commit.

The first error seems to be a failure to *heartbeat* the txn, which fails apparently because in turn the txn was pushed. But I find it funny that the `CREATE TABLE` txn was pushed... Since I'm not doing any other txns at the moment.

I do see the following in the log, though:
```
W0216 23:50:20.650278 26152 storage/replica.go:1700  failed to push during intent resolution: conflicting intents on [/Table/2/1/50/"t"/3/1 /Table/3/1/51/2/1]: resolved? false
```

**Comment by paperstreet** [comment]
I talked to @tschottdorf offline and he proposed the following:
- Introduce a sql session config for timeout (`SET INACTIVITY_TIMEOUT = 10m;`)
- Add a Timeout parameter to client.Txn, and populate it with this config (when set)
- client.Txn passes this through when it makes a BeginTransactionRequest
- TxnCoordSender then uses this as the heartbeat interval

Here's a working (but incomplete, untested, unpolished) commit for reference: https://github.com/paperstreet/cockroach/pull/2

**Comment by tschottdorf** [comment]
> Add a Timeout parameter to client.Txn

This could probably go on the options passed into `(*Txn).Exec`. @knz is looking at something similar (for chosing Txn start timestamps from the executor).

**Comment by paperstreet** [comment]
Okay, @bdarnell mentioned on the [code review](https://reviewable.io/reviews/cockroachdb/cockroach/5236#-) that he preferred the the `SELECT 1` strategy.

> I don't understand how changing the heartbeat interval helps. No matter how often we heartbeat, what we need is to change the outcome of hasClientAbandonedCoord. We can do that either by increasing the client timeout or by sending some sort of periodic update from the client. I'm wary of increasing the timeout because it means that interactive transactions from an inactive client could be held open even longer, blocking other transactions until one comes along with a high enough priority to abort it. I'd rather have the client send a hidden SELECT 1 periodically while there is an open transaction (and make sure that the SQL layer pings the KV coordinator to update the transaction).

Thoughts?

**Comment by andreimatei** [comment]
How is sending a `select 1` helping with "interactive transactions from an inactive client"? Or we trying to protect against the case where a sql prompt is stalled, but still able to maintain the TCP connection to the server?

I think we should take this opportunity to introduce transaction timeouts, decoupled from "activity". E.g. you want to say that the client can wait at most 1s for this operation, so the server shouldn't retry it automatically too many times if it keeps failing.

**Comment by bdarnell** [comment]
Not sure what you mean by "sql prompt is stalled".  What we're trying to address here is the fact that if you're doing an interactive transaction and it takes you more than 10s to type your next statement, your transaction gets aborted. Interactive transactions have a lot of other problems due to the restart requirement, so there are inherent limits to how well we can support them (at least in the traditional sql client model), but this is a particularly surprising thing so it would be nice to do something better here.

I withdraw my `SELECT 1` suggestion, though; that would only work for our own client. After reviewing this thread I think it would be better to handle this at the pgwire level: ping the txn coordinator periodically while the connection is open, and abort the transaction when the connection is closed.

**Comment by tschottdorf** [comment]
> After reviewing this thread I think it would be better to handle this at the pgwire level: ping the txn coordinator periodically while the connection is open, and abort the transaction when the connection is closed.

yeah, after reviewing it seems best to introduce `(*TxnCoordSender).Ping(txnID uuid.UUID)` (likely the executor would want to hold on to the plain `*TxnCoordSender` then). Additionally, when the client disconnects with an open transaction, this translates to an attempt to abort the Txn through the Executor. We shouldn't ever abandon transactions unless there's no other option.

**Comment by tschottdorf** [comment]
Small addendum to the above: Periodically having to ping `TxnCoordSender` from the `v3Conn` seems too much if we're invalidating the Txn anyway when that connection closes. Instead, we should have a single call to `TxnCoordSender` (like Ping but with a better name) at the beginning which instructs it to keep heartbeating the transaction indefinitely. @tamird, seems sane (and if so, any sweet ways to get the plumbing done? Current attempt is in https://github.com/paperstreet/cockroach/pull/4/files).

**Comment by tamird** [comment]
That attempt looks OK to me. Left a comment that just agrees with you on the "reactiveness".

**Comment by tschottdorf** [comment]
And how beautiful it is:

```
root@:26257> create table a.b (id int primary key);
CREATE TABLE
root@:26257> begin;
BEGIN
root@:26257> insert into a.b values(1);
INSERT 1
root@:26257> select statement_timestamp();
+-------------------------------------------+
|           statement_timestamp()           |
+-------------------------------------------+
| 2016-03-25 02:46:06.570500715 +0000 +0000 |
+-------------------------------------------+
root@:26257> select statement_timestamp();
+-------------------------------------------+
|           statement_timestamp()           |
+-------------------------------------------+
| 2016-03-25 02:46:08.570417518 +0000 +0000 |
+-------------------------------------------+
root@:26257> select statement_timestamp();
+-------------------------------------------+
|           statement_timestamp()           |
+-------------------------------------------+
| 2016-03-25 02:46:11.122413847 +0000 +0000 |
+-------------------------------------------+
root@:26257> select statement_timestamp();
+-------------------------------------------+
|           statement_timestamp()           |
+-------------------------------------------+
| 2016-03-25 02:46:17.215927622 +0000 +0000 |
+-------------------------------------------+
root@:26257> select statement_timestamp();
+-------------------------------------------+
|           statement_timestamp()           |
+-------------------------------------------+
| 2016-03-25 02:46:20.919850029 +0000 +0000 |
+-------------------------------------------+
root@:26257> select statement_timestamp();
+-------------------------------------------+
|           statement_timestamp()           |
+-------------------------------------------+
| 2016-03-25 02:46:24.832136364 +0000 +0000 |
+-------------------------------------------+
root@:26257> select statement_timestamp();
+-------------------------------------------+
|           statement_timestamp()           |
+-------------------------------------------+
| 2016-03-25 02:46:27.080110239 +0000 +0000 |
+-------------------------------------------+
root@:26257> insert into a.b values(2);
INSERT 1
root@:26257> commit;
COMMIT
```

**Comment by tschottdorf** [comment]
And how beautiful it is:

```
root@:26257> create table a.b (id int primary key);
CREATE TABLE
root@:26257> begin;
BEGIN
root@:26257> insert into a.b values(1);
INSERT 1
root@:26257> select statement_timestamp();
+-------------------------------------------+
|           statement_timestamp()           |
+-------------------------------------------+
| 2016-03-25 02:46:06.570500715 +0000 +0000 |
+-------------------------------------------+
root@:26257> select statement_timestamp();
+-------------------------------------------+
|           statement_timestamp()           |
+-------------------------------------------+
| 2016-03-25 02:46:08.570417518 +0000 +0000 |
+-------------------------------------------+
root@:26257> select statement_timestamp();
+-------------------------------------------+
|           statement_timestamp()           |
+-------------------------------------------+
| 2016-03-25 02:46:11.122413847 +0000 +0000 |
+-------------------------------------------+
root@:26257> select statement_timestamp();
+-------------------------------------------+
|           statement_timestamp()           |
+-------------------------------------------+
| 2016-03-25 02:46:17.215927622 +0000 +0000 |
+-------------------------------------------+
root@:26257> select statement_timestamp();
+-------------------------------------------+
|           statement_timestamp()           |
+-------------------------------------------+
| 2016-03-25 02:46:20.919850029 +0000 +0000 |
+-------------------------------------------+
root@:26257> select statement_timestamp();
+-------------------------------------------+
|           statement_timestamp()           |
+-------------------------------------------+
| 2016-03-25 02:46:24.832136364 +0000 +0000 |
+-------------------------------------------+
root@:26257> select statement_timestamp();
+-------------------------------------------+
|           statement_timestamp()           |
+-------------------------------------------+
| 2016-03-25 02:46:27.080110239 +0000 +0000 |
+-------------------------------------------+
root@:26257> insert into a.b values(2);
INSERT 1
root@:26257> commit;
COMMIT
```

**Comment by andreimatei** [comment]
Beautiful indeed! This was my pet peeve! Thanks Dan! And @nvanbenschoten for the timestamp cache stuff.
