### ISSUE TITLE
sqlmigrations: failed to get list of completed migrations

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#30354]
https://sentry.io/cockroach-labs/cockroachdb/issues/685108184/

```
*log.safeError: server.go:1601: migrations.go:471: caused by *errors.withMessage: caused by *roachpb.internalError
  File "github.com/cockroachdb/cockroach/pkg/cli/start.go", line 591, in 2
  File "github.com/cockroachdb/cockroach/pkg/cli/start.go", line 696, in func3

server.go:1601: migrations.go:471: caused by *errors.withMessage: caused by *roachpb.internalError
```

**Comment by tschottdorf** [comment]
```
	keyvals, err := db.Scan(ctx, keys.MigrationPrefix, keys.MigrationKeyMax, 0 /* maxRows */)
	if err != nil {
		return nil, errors.Wrapf(err, "failed to get list of completed migrations")
	}

```

Mostly curious what the error is here and whether the reported crash can be made more explicit.

**Comment by knz** [comment]
I think the general problem is that we can't safely include the full text of error messages in sentry reports because, in general, error messages can contain PII.

**Comment by a-robinson** [comment]
I'm not sure how this error would ever include PII, though, given that we're scanning a part of the keyspace that, even if keys/values were in the error from `db.Scan`, should only contain keys with migration names in them and not anything user-created. This looks like the kind of thing that we could reasonably mark as safe with `log.Safe`.

**Comment by jordanlewis** [comment]
This is a panic? Why? I'm tempted to close.

**Comment by knz** [comment]
@jordanlewis more words? I don't follow your thinking.

@a-robinson agreed.

**Comment by jordanlewis** [comment]
This happens at startup - I assume there was a retryable error that nothing is setup to retry. I think if a user retries this operation the situation would likely resolve itself.

That being said there's still a bug here, not sure why I said we should close this, that makes no sense.

**Comment by a-robinson** [comment]
Retries would be a good idea, yeah.

**Comment by jordanlewis** [comment]
Closing due to age.
