### ISSUE TITLE
kv: when coordinator considers txn abandoned, should actively abort it & its intents

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#3035]
this would happen in `(*TxnCoordSender).heartbeat`.

**Comment by bg451** [comment]
I'd like to take a look into this

**Comment by tschottdorf** [comment]
Great! Let us know if any questions come up.

**Comment by bg451** [comment]
Is there any way to actively abort a `txn`? So far, the only way I see to do this is to change `txn.Status` to `roachpb.ABORTED` then exit out of the heartbeat or do something similar to `(*TxnCoordSender).updateState` when it receives a `TransactionAbortedError`.

Sorry for taking a while on this, this is my first real dive into the codebase and I'm still getting a handle on it. 

Thanks!

**Comment by tschottdorf** [comment]
Hi Brandon, you abort a transaction by sending an `EndTransaction` call with `Commit: false`.
You'll want to attach the intents collected by the coordinator for that transaction so that they too can be resolved. You'll get those from `tc.txns[id].intents()`, see [here](https://github.com/cockroachdb/cockroach/blob/master/kv/txn_coord_sender.go#L352).

**Comment by nmarasoiu** [comment]
@bg451 @tschottdorf I saw idleness and winder can I try and take this? If you have any suggestions for documentation and coding, please add here.

**Comment by tschottdorf** [comment]
Hi @nmarasoiu, thanks for your interest - I've shamefully left this issue unattended. I've found that probably this issue requires a little more knowledge of how transactions work than suitable for a beginner. If you're ready to dig in (with a little help, but time limits how much can be explained), go for it! But there's also https://github.com/cockroachdb/cockroach/issues/4374, where it should be clearer what the solution looks like. Let me know!

**Comment by nmarasoiu** [comment]
#4374 is "stdlib log bridge always outputs to stderr", i am not sure this is what you meant.
I also realized that this task is more research than I expected, so indeed I will choose another one for starters. Which one do you suggest? The one with arbitrary arithmetics would be a good choice? thanks

**Comment by tschottdorf** [comment]
@nmarasoiu that's the one I mean! Should be a fairly small change (and usually once you do anything, you'll find more to do). #4424 is another small one to get started.
