### ISSUE TITLE
ui: standard deviation is sometimes reported as zero when it actually isn't

### ISSUE THREAD

**Issue by rkruze** [cockroachdb/cockroach#30369]
- Which version of CockroachDB are you using?
v2.1.0-beta.20180917
- What did you do?
Ran a ycsb insert workload, went to the statements page and noticed that the "Overall" item had "ms" on a new line that went through a table border and that some nodes didn't show std. 

- What did you expect to see?
STD for each node and to not have the "ms" label for the "Overall" value go through the table border. 

- What did you see instead?

Screenshot is attached. 
<img width="1132" alt="screen shot 2018-09-18 at 11 26 35 am" src="https://user-images.githubusercontent.com/351857/45698613-6c09a680-bb36-11e8-84fe-38788dee9236.png">
<img width="1155" alt="screen shot 2018-09-18 at 11 26 12 am" src="https://user-images.githubusercontent.com/351857/45698614-6ca23d00-bb36-11e8-8c75-1e32513c22ce.png">

**Comment by couchand** [comment]
@rkruze the line break in the label for overall mean latency is clear enough, and should be quick to fix.

The standard deviation problem is more concerning.  It's something I noticed once and then forgot to look into in more detail.  Thanks for filing!

**Comment by couchand** [comment]
Retitling to reflect the more significant issue here.
