### ISSUE TITLE
changefeedccl: pg_logical_emit_message equivalent

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#30365]
User request in the context of cdc feedback:

> We're using it pretty heavily and it's turned out to be a remarkably powerful primitive. We're using it to transactionally emit domain events across applications, transactionally enqueue jobs into a queuing system, etc. As you all know, transactions are pretty great and extending them to those use cases has been very useful. We could accomplish the same thing with inserts into a table, but we'd probably want to expire rows after a certain amount of time to keep the storage overhead low and that'd be a whole other process to manage.

CDC is pretty fundamentally built on listening to kv changes. So my initial thoughts on implementation are even if it's not exposed to the user this way, this would likely be modeled pretty closely to the latter part of the feedback (inserts into a table with a ttl).

Jira issue: CRDB-4836

**Comment by miretskiy** [comment]
Very stale and entirely supported w/ changefeed expressions and/or ttl tables.
