### ISSUE TITLE
sql: investigate zone config behaviour during dropping of a {table,database}

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#30375]
@nvanbenschoten and I were attempting to drop a database with a GC TTL of 30 seconds, but after we dropped it, it seemed that the zone config we had set up no longer applied, so it fell back to the `.default` zone config. We should clarify and document if this is the actual expected behaviour in this kind of situation.

cc @knz

**Comment by knz** [comment]
This needs to cross-reference #28901.

**Comment by petermattis** [comment]
Yeah, it's possible it is cross layer. My guess from reading this issue and knowing a bit of the code is that the problem (or UX surprise) is in the schema change handling. Assigning to @vivekmenezes for more detailed diagnosis.

**Comment by vivekmenezes** [comment]
This issue couldn't be resolved originally because the database descriptor would get dropped immediately. But now with the creation of a job for the DROP DATABASE being done for #19004
we can have the job delete the zone config after it has completed dropping all the table data.

**Comment by vivekmenezes** [comment]
this is a dup of #24179
