### ISSUE TITLE
perf: TPC-C throughput decreases as ramp period increases

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#30374]
When I ran tpc-c with an increase in ramp time 15, performance got much worse

With standard tpc-c ramptime:
1400 | 17,280.1 | 95.98%

With increase ramptime:

1400 | 14,916.1 | 82.85%
1400 | 13,393.0 | 74.39%

**Comment by awoods187** [comment]
yes good catch

**Comment by nvanbenschoten** [comment]
I think this may be somehow related to https://github.com/cockroachdb/cockroach/issues/27815.

**Comment by awoods187** [comment]
I just re-ran with 3 node 16 vcpu with ramp of 15 starting at 1300:

1300 | 16,201.0 | 96.91%
1400 | 17,393.4 | 96.61%
1500 | 16,178.5 | 83.87%
1600 | 15,963.1 | 77.58%

As we can see the ramp time seems to not have affected performance on 1400. I'm also on the latest beta (9/17) as opposed to the (9/4) from last time

**Comment by awoods187** [comment]
And the five minute ramp looks much worse:

1300 | 16,167.5 | 96.71%
1400 | 14,643.9 | 81.34%

Which is also worse than what i've observed previously (two weeks ago):

1300 | 16,229.8 | 97.08%
1400 | 17,280.1 | 95.98%
1500 | 16,320.7 | 84.61%
1600 | 16,547.0 | 80.42%

**Comment by awoods187** [comment]
I re-ran these numbers today post the kv fix:

Increased ramp (15m):

3 | 16 | 1500 | 18,432.3 | 95.55%
3 | 16 | 1600 | 15,000.6 | 72.90%

Normal ramp (5m):

3 | 16 | 1500 | 18,568.9 | 96.26%
3 | 16 | 1600 | 17,916.5 | 87.07%
3 | 16 | 1700 | 17,329.2 | 79.27%

**Comment by m-schneider** [comment]
How long are you running them for?

**Comment by nvanbenschoten** [comment]
I think Andy's comparing 5m ramps vs 15m ramps. It's possible that we're not doing as good of a job as we thought in ignoring the ramp period in our final tpmc calculation.

**Comment by m-schneider** [comment]
Yes, but what's the runtime of the non ramp part of it? I want to be able to reproduce.

**Comment by nvanbenschoten** [comment]
Oh, good question. I believe it was 10 minutes.

**Comment by m-schneider** [comment]
I ran several clusters following Andy's exact Google Doc, to make sure I was setting everything up the same way he did. I also made sure to reuse clusters by passing the --cluster flag for different ramp times and I played with ramp to runtime ratios. I didn't find correlation between ramp time and performance and in one of the runs performance was actually much better with the longer ramp.

```
> /home/masha/go/src/github.com/cockroachdb/roachprod/roachprod run masha-1538676646-tpccbench-nodes-3-cpu-16:4 -- ulimit -n 32768; ./workload run tpcc --warehouses=2000 --active-warehouses=1400 --tolerate-errors --ramp=5m0s --duration=10m0s {pgurl:1-3}                                                                                                                                                                                                                                                                                    
--- FAIL: tpcc 1400 resulted in 13682.9 tpmC (77.5% of max tpmC)     


> /home/masha/go/src/github.com/cockroachdb/roachprod/roachprod run masha-1538676646-tpccbench-nodes-3-cpu-16:4 -- ulimit -n 32768; ./workload run tpcc --warehouses=2000 --active-warehouses=1400 --tolerate-errors --ramp=15m0s --duration=10m0s {pgurl:1-3}
--- PASS: tpcc 1400 resulted in 17262.7 tpmC (97.8% of max tpmC)
```
Andy, if you see this issue again, make sure you're reusing the cluster so we're not getting quite as much GCE variance.
