### ISSUE TITLE
storage: Nodes crashing with std::bad_alloc within a second of starting up

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#30389]
On my tpc-c 50k cluster (https://github.com/cockroachdb/cockroach/issues/30284) two of the nodes crashed with std::bad_alloc errors. Assuming it was just due to a normal OOM situation, I tried restarting them. They both immediately failed with std::bad_alloc errors again within a second of starting up. Neither of them has anything written in their `logs/heap_profiler/` directories. More suspiciously, neither of them appears to have been using even close to all the memory on the machine (14.4GB) before crashing:

```
I180918 19:07:03.042190 264 server/status/runtime.go:484  [n74] runtime stats: 7.1 GiB RSS, 4361 goroutines, 938 MiB/818 MiB/2.1 GiB GO alloc/idle/total, 4.1 GiB/5.1 GiB CGO alloc/total, 81651.3 CGO/sec, 1219.8/108.7 %(u/s)time, 0.4 %gc (13x), 454.3/379.9/51 (%r/%w/q)disk, 219 MiB/161 MiB (r/w)net
[...] a couple seconds pass
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```

```
I180918 18:16:49.293146 471 server/status/runtime.go:484  [n83] runtime stats: 7.2 GiB RSS, 11668 goroutines, 852 MiB/615 MiB/2.2 GiB GO alloc/idle/total, 4.0 GiB/5.0 GiB CGO alloc/total, 213103.1 CGO/sec, 1235.6/90.2 %(u/s)time, 0.1 %gc (10x), 254.1/244.3/0 (%r/%w/q)disk, 200 MiB/138 MiB (r/w)net
[...] a couple seconds pass
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```

The logs suggest that the nodes were running somewhat slowly before the crash, with lots of `handle raft ready: 0.5s` and `commit took 564.614477ms` errors and some raft snapshot applications. I don't see any particularly large snapshots or outlier writes, though.

It's not at all clear why the nodes are bad_alloc-ing after restart, but it certainly suggests that there's something big rocksdb is picking up off the disks.

It appears likely that this is the same issue as https://github.com/cockroachdb/cockroach/issues/28895#issuecomment-422075438, so cc @nvanbenschoten if you want to be able to poke around at these.

**Comment by nvanbenschoten** [comment]
I only see two small entries in the WAL:

```
nathan@alex-50k-0037:/mnt/data1/cockroach$ ~/cockroach debug rocksdb dump_wal --walfile=090892.log
2150268937,1,61,0,PUT(0) : 0x01736376657200
2150268938,1,61,68,PUT(0) : 0x01736376657200
```

**Comment by nvanbenschoten** [comment]
The largest .sst is only 101MB, so nothing there looks crazy either.

**Comment by a-robinson** [comment]
I've confirmed that this is fixed by https://github.com/cockroachdb/cockroach/pull/30558, which will be merged/backported soon.

And not that it likely matters, but I've also confirmed that after starting up a previously broken node with a patched binary, the old un-patched binary is usable again too.
