### ISSUE TITLE
sql: query takes much longer to complete compared to its corresponding trace

### ISSUE THREAD

**Issue by changangela** [cockroachdb/cockroach#30390]
After running a workload to split the database into many ranges using the following command:
`bin/workload run kv --splits=50000`

Running `set tracing=on; select count(*) from crdb_internal.ranges; set tracing=off;` takes a few minutes to complete. However, when we `show trace for session;`, we see that the entire query took a few seconds.

The last row of the trace shows:
`  2018-09-18 20:39:42.207343+00:00 | 3s755ms510\302\265s | executing: SET TRACING = off in state: NoTxn                                                                                         | [n1,client=[::1]:57724,user=root]               |                             | session recording                                     |      0`

**Comment by knz** [comment]
Angela can you please include the full trace?

**Comment by changangela** [comment]
The full trace is very long (~150000 rows). Should I just include a chunk of the trace?
