### ISSUE TITLE
storage: node panics with MVCCFindSplitKey returned start key of range

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#30396]
Running a restore of several tables (around 50gb I think) on my laptop, more than half an hour in, the node panics with this error. I wiped and tried again, but got the same result.

```
F180919 01:43:17.503592 23580 storage/replica_command.go:274  [n1,split,s1,r1047/1:/{Meta2/Table/…-System/}] MVCCFindSplitKey returned start key of range
goroutine 23580 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0xc0000c0200, 0xc0000c02a0, 0x8005800, 0x1a)
	/Users/david/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:972 +0xd4
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x872bc80, 0xc000000004, 0x80058e6, 0x1a, 0x112, 0xc018e07ec0, 0x5d)
	/Users/david/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:841 +0x80e
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x6c02080, 0xc01310b3e0, 0x4, 0x2, 0x0, 0x0, 0xc0193619c0, 0x1, 0x1)
	/Users/david/go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:85 +0x2d5
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x6c02080, 0xc01310b3e0, 0x1, 0x4, 0x0, 0x0, 0xc0193619c0, 0x1, 0x1)
	/Users/david/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:69 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatal(0x6c02080, 0xc01310b3e0, 0xc0193619c0, 0x1, 0x1)
	/Users/david/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:181 +0x6c
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).adminSplitWithDescriptor(0xc01cc3dc00, 0x6c02080, 0xc01310b3e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/david/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_command.go:274 +0x536
github.com/cockroachdb/cockroach/pkg/storage.(*splitQueue).processAttempt(0xc000366120, 0x6c02080, 0xc01310b3e0, 0xc01cc3dc00, 0xc00a9ba000, 0x34, 0x40, 0x466fc32, 0x3)
	/Users/david/go/src/github.com/cockroachdb/cockroach/pkg/storage/split_queue.go:170 +0x3e4
github.com/cockroachdb/cockroach/pkg/storage.(*splitQueue).process(0xc000366120, 0x6c02080, 0xc01310b3e0, 0xc01cc3dc00, 0xc00a9ba000, 0x34, 0x40, 0x1, 0xc00042c480)
	/Users/david/go/src/github.com/cockroachdb/cockroach/pkg/storage/split_queue.go:127 +0x77
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processReplica(0xc00048a500, 0x6c020c0, 0xc01cc79b30, 0xc01cc3dc00, 0x0, 0x0)
	/Users/david/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:744 +0x368
github.com/cockroachdb/cockroach/pkg/storage.(*baseQueue).processLoop.func1.2(0x6c020c0, 0xc01cc79b30)
	/Users/david/go/src/github.com/cockroachdb/cockroach/pkg/storage/queue.go:627 +0xb8
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc0005650e0, 0x6c020c0, 0xc01cc79b30, 0xc00bcc8330, 0x29, 0x0, 0x0, 0xc00033e460)
	/Users/david/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:324 +0xe6
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
	/Users/david/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:319 +0x134
```

**Comment by dt** [comment]
FWIW, the tables being restored includes one with _VERY LARGE_ values in the primary key, and the logs mention some of those -- the lines before the crash are all `initiating a split of this range at key <20-60kb string>`

**Comment by nvanbenschoten** [comment]
I don't have a good idea of why I added that fatal in. It doesn't seem to make much sense. It's possible that I wasn't clear on the contract of `MVCCFindSplitKey` and thought that it could never return the start key of the range. Regardless, it looks fine to remove.

**Comment by bdarnell** [comment]
I think the idea behind the assertion was that MVCCFindSplitKey would always look past the current key - it would return the first valid split point greater than its input, instead of falling back to the input key just because the first row is too large. I think that's a useful property to preserve - if a range has an oversized first row, we want to split after that row instead of leaving all the rest of the rows behind it in the same range.

**Comment by a-robinson** [comment]
> I think that's a useful property to preserve - if a range has an oversized first row, we want to split after that row instead of leaving all the rest of the rows behind it in the same range.

Isn't that what MVCCFindSplitKey already does, though? https://github.com/cockroachdb/cockroach/pull/19339 and https://github.com/cockroachdb/cockroach/pull/24896 ensure this. As far as I know, we only return the start key of the range if there's only the one SQL row contained in the range. We have some tests for these kinds of situations in `TestFindValidSplitKeys`.

**Comment by bdarnell** [comment]
I'm saying that if there is only one row in the range, MVCCFindSplitKey should return a key just after that row (and the assertion should remain). But if there are off-by-one boundary reasons that can't happen, I'm also fine with the current behavior.

**Comment by a-robinson** [comment]
I'm not understanding why either is preferable to the other. As far as I can tell, we're just discussing what the return value should be when there isn't a valid key to split at in the range. Returning an empty key would perhaps be even more appropriate, but I don't get why returning a key outside the range would be any better than the start key of the range.

**Comment by bdarnell** [comment]
It's a weak preference, but we had the assertion and I could imagine other parts of the system making assumptions that MVCCFIndSplitKey wouldn't return the input key. I think we used to have a bug where this would cause the split queue to busy loop trying to split at the already-split point.

**Comment by nvanbenschoten** [comment]
I have a preference for the approach @bdarnell is discussing as well. If we can't find a split key in a range, I'd expect the returned key to be `desc.EndKey`, not `desc.StartKey` so that `desc.contains(foundSplitKey) == false`. That's probably why I added the misguided assertion.

**Comment by a-robinson** [comment]
Well I have no preference, I'd only stick with what's already there due to the fact that it's already there. Feel free to switch it.

**Comment by nvanbenschoten** [comment]
I think I know why I added that assertion actually. We should be returning a `unsplittableRangeError` in this case. I'm going to see how easily this is to fix.

**Comment by nvanbenschoten** [comment]
I'm not easily able to reproduce this with a new test in `TestFindValidSplitKeys` that creates a range with multiple columns family keys for a single row. The other test cases imply that this should be returning `nil` instead of `StartKey`, and that is indeed what I'm seeing (directly from `it.FindSplitKey`). I suspect that something else is going on here.

@dt do we still have the backup hanging around?

**Comment by dt** [comment]
@nvanbenschoten Yep, it's on s3, let's followup offline.

**Comment by nvanbenschoten** [comment]
I was able to reproduce this with the following steps:
1. start new cluster
2. set `enterprise.license`
3. `create database registration;`
4. `RESTORE registration.clusters, registration.nodes, registration.stmtstats FROM 's3://cockroach-reg-backups/2018-09-18?AWS_ACCESS_KEY_ID=...&AWS_SECRET_ACCESS_KEY=...';`

**Comment by nvanbenschoten** [comment]
Interesting, it looks like the split key we're dealing with here is in `meta2`. The range spans the range `[/Meta2/Table/55/1/"SELECT...",/System/"")`. We're probably doing something strange here due to the meta prefix.

**Comment by nvanbenschoten** [comment]
I think I see what's going on here. We're hitting an issue similar in spirit to https://github.com/cockroachdb/cockroach/pull/24896, except instead of it being a problem with splits between column families, it's a problem with splits between mvcc versions. Interestingly, the fix added to https://github.com/cockroachdb/cockroach/pull/24896 has the side effect of preventing any SQL keys from falling prey to this bug, but meta keys are fair play. `TestFindValidSplitKeys` didn't catch the issue because it only ever creates a single mvcc version for a key.

**Comment by nvanbenschoten** [comment]
https://github.com/cockroachdb/cockroach/blob/69c16a1f5e7a6e64e13d77013f7df25d58118b39/pkg/storage/engine/mvcc_test.go#L3596-L3599

Lies! The bug still exists.
