### ISSUE TITLE
opt: handle EXPLAIN EXECUTE

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#30409]
@mjibson points out that `EXPLAIN (OPT) EXECUTE ..` does not work. This is because `Execute` is not supported inside the optimizer; it is handled separately by the conn executor.

When pulling on that thread, I noticed that `EXPLAIN (VERBOSE) EXECUTE ..` works but it shows the plan that would be generated with the heuristic planner. The following example shows that we error out on correlated subquery:

```root@127.124.94.227:43361/defaultdb> prepare c AS select * from abc where a in (select d from def where e=b);
PREPARE

Time: 517.586µs

root@127.124.94.227:43361/defaultdb> execute c;
  a | b | c  
+---+---+---+
(0 rows)

Time: 663.878µs

root@127.124.94.227:43361/defaultdb> explain (verbose) execute c;
pq: column "b" does not exist
```

**Comment by RaduBerinde** [comment]
This is the executor's special code for `Execute`:
https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/conn_executor_exec.go#L288

It seems that in general we would want this code to handle `tree.Execute` wherever it is inside the statement. However, we don't seem to have general functionality to walk statements.

I think it's reasonable for 2.1 to just support the special case of top-level Explain -> Execute. That would not work when we do `SELECT * FROM [EXPLAIN EXECUTE a (1)]` (which itself could be inside a bigger query). Perhaps we should disallow `EXECUTE` in these contexts altogether (by not implementing `planner.Execute`) to avoid confusion.

Eventually we will want the optimizer to handle `Execute`, but right now I don't quite see how that would work.

CC @knz @andy-kimball

**Comment by knz** [comment]
I think we'd be creating trouble for ourselves by allowing EXECUTE in sub-clauses (because of placeholder renaming and whatnot).

**Comment by RaduBerinde** [comment]
We already allow EXPLAIN EXECUTE to be sub clauses, I think that is the only case. Do you thing we should change that?

**Comment by knz** [comment]
I think "explain execute" as a phrase is problematic to start with.

**Comment by knz** [comment]
it's like "explain begin"

**Comment by RaduBerinde** [comment]
Hm, but it does have a reasonable use case, to see the plan for running a prepared query..  If we introduce different plan caching modes (e.g. one where we just replace placeholders and don't re-optimize), this might be the only way to see the plan that actually gets run.

**Comment by knz** [comment]
I see what you're saying but the machinery for prepare/execute is really unfriendly to being handled in sub-clauses. Maybe we should have an explain statement that reports "the last plan executed" (or prepared) like we do session tracing?

**Comment by RaduBerinde** [comment]
I think it's valuable to be able to see plans without actually running the query (which might be long-running, or might even crash and you're trying to debug that).

What if we simply disallow `EXPLAIN` to be used in sub-clauses if it's explaining an `EXECUTE`? We could even separate it (in the syntax) into a different ExplainExecute top-level statement maybe

**Comment by knz** [comment]
you can `PREPARE a AS EXPLAIN <yourquery with placeholders>` then `EXECUTE a(1,2,3)` to see the plan. How does this not work?

**Comment by mjibson** [comment]
Turns out that doesn't work either:

```
> PREPARE a AS EXPLAIN select 1;
invalid syntax: statement ignored: syntax error at or near "explain"
```

**Comment by knz** [comment]
*sigh* - I am 90% confident this used to work and you're seeing a regression. Looking now.

**Comment by knz** [comment]
yeah it's a regression but fixing it is revealing a couple bugs!! Fixing

**Comment by knz** [comment]
Here you go: #30550

This ensures you can indeed PREPARE an EXPLAIN (and also tests various combinations that were not tested previously).

In practice I am not opposed to the special case Radu suggests above, however I'd like to point out that "EXPLAIN EXECUTE" is an odd / irregular special case in the SQL grammar (the patch in #30550 makes this super-visible) and that is why I think it would be probably better to get rid of it entirely.

**Comment by RaduBerinde** [comment]
I'm good with getting rid of `EXPLAIN EXECUTE`, at least for now. We can consider adding it back (or using some other mechanism similar to tracing like you suggested) if we need it for plan caching.

**Comment by RaduBerinde** [comment]
The context is in this issue.. Note that if we keep it, we should fix it in 2.1 (it lies and shows the non-opt plan currently).

**Comment by jordanlewis** [comment]
Ugh, ignore me, I thought you were discussing `EXPLAIN ANALYZE`. I'm more than happy to let `EXPLAIN EXECUTE` die - it's been a real pain to maintain.

**Comment by knz** [comment]
@RaduBerinde do you mind doing the work to remove explain execute? I am neck deep in mutations and also still not feeling well, so not keen to context switch
