### ISSUE TITLE
sql: Order by Offset not using index

### ISSUE THREAD

**Issue by leomkkwan** [cockroachdb/cockroach#30416]
Runing v2.2.0-alpha.00000000-782-g40ec553

An index will be used in order by clause, but won't use index if we have offset clause. Not sure if this is intended, but would be nice if we can utilize index in offset clause.

```
root@192.168.28.10:26257/defaultdb> explain  SELECT * FROM screenview ORDER BY date LIMIT 200 ;
     tree    | field |          description
+------------+-------+--------------------------------+
  index-join |       |
   ├── scan  |       |
   │         | table | screenview@screenview_date_idx
   │         | spans | ALL
   │         | limit | 200
   └── scan  |       |
             | table | screenview@primary
(7 rows)

Time: 4.643688ms

root@192.168.28.10:26257/defaultdb> explain  SELECT * FROM screenview ORDER BY date LIMIT 200 offset 200;
       tree      | field |    description
+----------------+-------+--------------------+
  limit          |       |
   └── sort      |       |
        │        | order | +date
        └── scan |       |
                 | table | screenview@primary
                 | spans | ALL
(6 rows)

Time: 1.708675ms
```

**Comment by arjunravinarayan** [comment]
hi @leomkkwan, two things would be helpful to debug this further:

1.  do you might sharing your `SHOW CREATE TABLE screenview` so that we can take a closer look at the schema? 

2. can you run `EXPLAIN (OPT) ...` and let us know what the output is? We have recently added a cost-based optimizer, and you're running a bleeding edge version of CockroachDB.

This isn't intended behavior, and this isn't what I see when attempting a minimal reproduction:

```
root@127.2.45.224:35745/defaultdb> create table foo (a int primary key, b date);
CREATE TABLE

Time: 3.484929ms

root@127.2.45.224:35745/defaultdb> create index on foo (b);
CREATE INDEX

Time: 73.84968ms

root@127.2.45.224:35745/defaultdb> explain select * from foo order by b limit 200;
  tree | field |  description   
+------+-------+---------------+
  scan |       |                
       | table | foo@foo_b_idx  
       | spans | ALL            
       | limit | 200            
(4 rows)

Time: 1.10838ms

root@127.2.45.224:35745/defaultdb> explain select * from foo order by b limit 200 offset 200;
    tree    | field |  description   
+-----------+-------+---------------+
  limit     |       |                
   └── scan |       |                
            | table | foo@foo_b_idx  
            | spans | ALL            
(4 rows)
```

So your exact schema would be helpful in debugging this further. Thank you.

**Comment by arjunravinarayan** [comment]
Thanks @solongordon. With that hint, I can now reproduce this. Your `select *` forces an index join, which has a maximum number of values before which it will cease to be effective. This causes the planner to switch back to scanning the primary index and sorting the results. 

You have an index on the `date` column, but not on all the other columns. To fix this, If you have three other columns `foo, bar, baz`, you should explicitly create an index on `date, foo, bar, bar` (or alternatively, `create index on screenview (date) storing (foo, bar, baz)`). Then, `select date, foo, bar, baz from screenview order by date limit 200 offset 200` will work fine.


Let me know if this fixes your problem.

**Comment by leomkkwan** [comment]
Thank you for the workaround(?), but I don't think it is a fixes cause this is not very practical in a real world case that we store all value in an index for sorting and pagination.
Indeed the query were came from DBeaver, which officially support cockroachdb in their newest version of 5.2, when they do pagination from the data viewer.

**Comment by jordanlewis** [comment]
I think this is more of a planning issue, so I'm kicking over to @andy-kimball to take a look. I think the planner is responsible for making a better decision in this case.

**Comment by andy-kimball** [comment]
The problem here is that the `GenerateLimitedScans` rule doesn't work for the `(Limit (Offset` case. I believe what we should do here is create a `PushLimitIntoOffset` rule, something like this (details definitely not quite correct):
```
(Limit
    (Offset
        $input:*
        $offset:(Const $offset:* & (IsPositiveLimit $offset))
        $offsetOrdering:*
    )
    $limit:(Const $limit:* & (IsPositiveLimit $limit))
    $limitOrdering:* & (IsSameOrdering $offsetOrdering $limitOrdering)
)
=>
(Offset
    (Limit
        $input
        (AddConsts $offset $limit)
        $limitOrdering
    )
    $offset
    $offsetOrdering
)
```
Or maybe we only do that when `$input` is a `Scan`, if we're worried about `(Offset (Limit` being slightly less efficient than `(Limit (Offset`?

**Comment by RaduBerinde** [comment]
@ridwanmsharif - this is a self-contained improvement if you are interested.

I don't think there is an execution difference between Offset / Limit and Limit / Offset (in most cases they both end up with a processor that does both at the same time)
