### ISSUE TITLE
ui: telemetry: CORS preventing telemetry from firing on insecure clusters

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#30415]
During testing of #29194, @couchand and @mrtracy uncovered that we are not able to send telemetry to segment for admin UIs on localhost due to browser's CORS policies preventing the requests from succeeding. After further testing, Andrew discovered that this might impact all insecure clusters. Since this will both drastically limit the total amount of telemetry and impose a strong selection effect on the data we receive, we should fix this ASAP for 2.1.

**Comment by couchand** [comment]
I don't think the description here is precisely correct.  Spinning up an insecure cluster on localhost with the latest posts telemetry just fine.  More investigation is needed.

**Comment by piyush-singh** [comment]
Enumerating the different cluster setups and testing each of them:

1. Local insecure cluster
2. Local secure cluster (NOT YET TESTED, will add in a followup)
3. Roachprod insecure cluster
4. Roachprod secure cluster

For all of the above setups I tested, I see some requests succeed:
![image](https://user-images.githubusercontent.com/21692034/45770789-5cab5b80-bc11-11e8-8f10-5331907ea0f4.png)

But I do periodically see 504 errors from the reg cluster:
![image](https://user-images.githubusercontent.com/21692034/45770765-4d2c1280-bc11-11e8-8ae6-d3948b71513b.png)

Along with a reference to a CORS issue:
![image](https://user-images.githubusercontent.com/21692034/45770737-32f23480-bc11-11e8-95e9-7c07b0c2c68f.png)

**Comment by couchand** [comment]
@piyush-singh I would imagine the 504s are related to the recent reg cluster instability.  Any testing here might be a bit muddled due to that, you might wait until that's more stable.

**Comment by couchand** [comment]
@piyush-singh have you had a chance to retest this?

**Comment by piyush-singh** [comment]
Yes! So for quick reference, this is trivially reproducible in 2.0.6:
<img width="525" alt="image" src="https://user-images.githubusercontent.com/21692034/46636659-ea021180-cb26-11e8-8e09-43a110bea7cd.png">

For master:

1. Local insecure
Seems to work correctly (nothing in the console either):
<img width="931" alt="image" src="https://user-images.githubusercontent.com/21692034/46637039-6e08c900-cb28-11e8-8efd-8b0ca4e7cf98.png">

2. Local secure
Also seems to work correctly (nothing in the console either):
<img width="944" alt="image" src="https://user-images.githubusercontent.com/21692034/46637412-18cdb700-cb2a-11e8-8d57-84e924cd9ecc.png">

3. Roachprod secure:
Also seems to work here:
<img width="568" alt="image" src="https://user-images.githubusercontent.com/21692034/46637597-f0928800-cb2a-11e8-884f-95cea9653037.png">

4. Roachprod insecure:
Works here as well:
<img width="939" alt="image" src="https://user-images.githubusercontent.com/21692034/46637684-4ebf6b00-cb2b-11e8-8fdc-7e303a9102a8.png">

I didn't see anything pop up in the console for any of the tests featuring today's master. @couchand let me know if there is anything else I should check out, otherwise I'll close this issue tomorrow.

**Comment by couchand** [comment]
Sounds good, glad to hear we ironed it out. 👍
