### ISSUE TITLE
QA: include hourly BACKUPs of production clusters

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#30421]
In trying to run the latest beta on our internal telemetry collection cluster, we've encountered some bugs.

Often these bugs first surface during a BACKUP, which seems to stress enough parts of the system to get them out of the woodwork -- sending a request to all ranges wakes them up, it does lots of IO, can stress liveness, etc.

We should add periodic BACKUPs to the synthetic load on our QA production clusters to encourage these kinds of issue to crop up there, during QA.

(we could write to a cloud store bucket that has a brief TTL, or stand-up a little HTTP /dev/null service).

**Comment by dt** [comment]
@tschottdorf for routing, since I guess CFS owns prod QA process or knows who does?

**Comment by mberhault** [comment]
This will likely be on hold until QA clusters are recreated with the same setup used for cloud clusters. That will include regular (eg: daily full, hourly incremental) backups.

**Comment by dt** [comment]
the production clusters are gone, but MSO does hourly backups so I'll consider this done for now.
