### ISSUE TITLE
Variable runtime in the same tpcc restore

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#30438]
Variable run time in the same restore from tpcc bench:
3 node 16 cpu tpc-c 2k

Run 1 is 1hr19
![image](https://user-images.githubusercontent.com/22278911/45781884-51672880-bc2f-11e8-9102-3a449bb4eacc.png)
Run 2 is 1hr41
![image](https://user-images.githubusercontent.com/22278911/45781909-63e16200-bc2f-11e8-88c4-8bb0a589e1b1.png)

Three weeks ago I ran this and got 1hr17

**Comment by awoods187** [comment]
I ran a tpc-c restore of 5k on 3 nodes with 32 CPUs and observed a large restore discrepancy: 

Restore 1: 2hr52m
![image](https://user-images.githubusercontent.com/22278911/46121055-0a090b00-c1e0-11e8-8ae8-41bcd0ddc88e.png)

Restore 2: 3hr40m
![image](https://user-images.githubusercontent.com/22278911/46121822-9b2db100-c1e3-11e8-86ba-452af29a729e.png)

**Comment by dt** [comment]
I see variable performance of everything, not just restore. I think a lot of this comes down to getting a bad scatter or not, but I don't think there is much bulk-io can do here.
