### ISSUE TITLE
Variable performance on tpc-c 1k 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#30458]
On the most recent beta, I observe a variable number of support warehouses:

Run 1: starting at 1500

1500 | 15,601.8 | 80.88%
1400 | 14,243.5 | 79.11%
1300 | 15,853.5 | 94.83%

run 2: starting at 1500
1500 | 16,158.5 | 83.77%
1600 | 17,590.8 | 85.49%
1700 | 16,815.7 | 76.92%

run 3: starting at 1300
1300 | 16,167.5 | 96.71%
1400 | 14,643.9 | 81.34%

All with the same ramp, same restore, same nodes etc.

**Comment by awoods187** [comment]
Using master post the KV fix I see less variability in two runs:

run 1
`3    16    1500                        18,449.1    95.64%
3    16    1600                        17,270.1    83.93%
3    16    1700                        16,725.5    76.50%`

run 2
`3    16    1500                        18,568.9    96.26%
3    16    1600                        17,916.5    87.07%
3    16    1700                        17,329.2    79.27%`

**Comment by nvanbenschoten** [comment]
Closing as stale.
