### ISSUE TITLE
ui: admin UI displays blank page when accessed through proxy server

### ISSUE THREAD

**Issue by krishsur** [cockroachdb/cockroach#30471]
Is this a bug report or a feature request?
Bug
If so, please fill out the template below and we'll be happy to help.

If not, or you're not sure, please file an issue on our forum instead: https://forum.cockroachlabs.com/. You'll get a faster response there for troubleshooting and general questions, and it's likely that someone else has encountered the same issue.

**BUG REPORT**

Please describe the issue you observed, and any steps we can take to reproduce it:

- Which version of CockroachDB are you using?
2.0.5
- What did you do?
Installed cockroach db, started the CRD in insecure mode, the clusters came up properly, Admin UI was started and bound to the default port 8080, configured access to Admin UI through HA Proxy server with URI context as /cockroachdbUI, now when I try to access the UI http://<domainname>/cockroachdbUI , the default page that is displayed is blank, upon debugging found that the html page is unable to download the required JS files such as protos.dll.js, vendor.dll.js, bundle.js and banner.js, the reason its failing, the landing html page is trying download these JS files without the uri context /cockroachdbUI like this way http://<domainname>/vendor.dll.js etc , so without the URI context HAProxy is throwing 400 response code 
- What did you expect to see?
The static file should retain the relative path so that the proxy server can route it properly to download 
- What did you see instead?
This is the error message captured from JS console

![image](https://user-images.githubusercontent.com/10214291/45838036-92aa1780-bcc5-11e8-9fba-f797a3e94206.png)

- What was the impact?

Admin UI is blank and doesn't display anything

**FEATURE REQUEST**

Please describe the feature you are requesting, as well as your proposed use case.

**Comment by knz** [comment]
cc @piyush-singh @couchand

**Comment by couchand** [comment]
@krishsur can you provide more details about your HA Proxy configuration?  Also, I'm confused about your browser setup, it looks like your addresses don't have a hostname part?

The referenced files are already listed with relative paths (see https://github.com/cockroachdb/cockroach/blob/a486ce7ce63a887d1bb09d85e140e3506ec56b3d/pkg/ui/ui.go#L85), but we don't do much testing of alternate configurations.  Hopefully we can get to the bottom of this.

**Comment by krishsur** [comment]
@couchand The hostname part in the URL got somehow stripped off after I submitted this git issue, its an internal application(so not accessible to outside world), the URL follows this schema https://ec.domainname/cockroachdbUI , btw I think the code should include / when referenced to download the static contents, in the src attribute, something like this way to address this issue

e.g <script src="/protos.dll.js" type="text/javascript"></script>
