### ISSUE TITLE
perf: throughput should gracefully degrade under heavy load

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#30489]
Throughput should degrade gracefully when a cluster is under heavy load instead of falling off a cliff.

From https://github.com/cockroachdb/cockroach/issues/30227#issuecomment-423406389.

> This shows the performance degradation due to high CPU load causing queries per second (QPS) to > drop significantly:
>
> <img width="985" alt="45859522-a8482d00-bd17-11e8-802f-a360c7505d25" src="https://user-images.githubusercontent.com/5438456/45860306-72657180-bd34-11e8-99d1-b106a0aa52d3.png">
>
> The trigger is reading then deleting rows for an archive pipeline, but cockroach shouldn't face-plant > like this under heavy load.
> 
> This chart shows CPU usage on one of the cockroach machines on the same time scale as the above > charts:
> 
> <img width="496" alt="45859750-8e5b1a00-bd18-11e8-91c9-9c1391a6f6ed" src="https://user-images.githubusercontent.com/5438456/45860310-798c7f80-bd34-11e8-8ffd-0a8ca5af40c0.png">

**Comment by alanhamlett** [comment]
> How much is your load fluctuating?

By load do you mean QPS or CPU usage? I have normal load with spikes when running archive jobs.

> What are the characteristics of your load? (read-heavy? write-heavy? a mix?) What kinds of queries are you running?

Constant writes around 110 INSERT per second, with low number of SELECT except for the archive jobs which cause a spike in SELECT and DELETE along with the all-around performance degradation. The select and delete queries only filter by the dual primary key `user_id`, `timestamp`.

> How many SQL connections do you have open to the database?

Always around 400 active connections according to Cockroach's SQL Dashboard charts.

> How much data is loaded into your database?

200GB

**Comment by nvanbenschoten** [comment]
Closing in favor of more recent thinking about admission control.
