### ISSUE TITLE
ui: compaction queue graph needs separate axes

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#30490]
It's impossible to see the bytes compacted/sec, which is usually measured in MB/s, if there are GB of compactions awaiting:

<img width="979" alt="image" src="https://user-images.githubusercontent.com/882976/45860857-7c3ca400-bd37-11e8-89ae-ffd6f61ed870.png">

These two series would greatly benefit from separate axes.

**Comment by couchand** [comment]
We've got a few charts where we just do this today, and there are probably places we could use it if we supported it.  Should be quick to add after #18620.

**Comment by couchand** [comment]
also see #12899
