### ISSUE TITLE
jobs: paused jobs fail after being paused

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#30505]
over the past few days we've been trying to troubleshoot issues on a sad registration cluster.
often the cluster slows down white trying to run BACKUP and several times I've tried to `PAUSE` the backup job. The `PAUSE` succeeds after a few seconds, and the jobs page shows it as paused. Some time later though -- between 20s and a couple minutes -- the job switches to failed, with a ctx cancelled error. I think someone's seeing the pause cancel and bubbling it up as a failure?

**Comment by mjibson** [comment]
I just ran an IMPORT and one of the nodes went down. It got marked as failed with a context canceled error, even though I added code to specifically not fail on that error but instead restart. Maybe the same bug.

**Comment by mjibson** [comment]
Nope. But I also haven't been pausing anything recently.

**Comment by roncrdb** [comment]
@dt an issue was linked that shows a specific error message, might be helpful in troubleshooting this issue, looking to get the dump file that the user was importing as well.
