### ISSUE TITLE
pgwire: flushInfo.cmdStarts should use a slice, not a map

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#30507]
`flushInfo.cmdStarts` maps a `CmdPos` to the index of the buffer where the results for the respective result begins. `CmdPos` are monotonically increasing and have clear lifetimes imposed by `conn.Flush` and `clientConnLock.RTrim`. We should be able to get rid of the map and replace it with a slice and an offset.

**Comment by m-schneider** [comment]
Thanks, will do!

**Comment by nvanbenschoten** [comment]
#33273 came close to getting this right. The mistake it made was not recycling the `cmdStartsList` slice on `Flush`. I think it could have also just used `lastFlushed` in place of `oldestCmdInBuf`.

I'm now realizing that we create a new map for `cmdStarts` every time we `Flush` the `conn`. That seems pretty terrible, so I expect this to be a nice win.
