### ISSUE TITLE
Automatic replication from mysql to cockroachdb using a continuous import of the mysql binary log

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#30518]
**Feature request**

From Gitter:

Tongxuan Liu @liutongxuan Aug 17 07:29
@petermattis can cockroachDb consume the binlog from MySQL? then i can pull the data from mysql.

kena @knz Aug 17 07:32
@liutongxuan: we do not (yet) support binary formats from other databases.
@liutongxuan: how much data do you wish to import?

Tongxuan Liu @liutongxuan Aug 17 07:36
@knz giga bytes, just try to use cockroachDB in an un-important online service. The strategy is import all history data in mysql(current storage engine), then upper logic switch to: query cockroach DB firstly, if fail, query mysql

kena @knz Aug 17 07:37
please correct me if my understanding is wrong, so you want to set up automatic replication from mysql to cockroachdb using a continuous import of the mysql binary log?

Tongxuan Liu @liutongxuan Aug 17 07:38
yes
using databus

kena @knz Aug 17 07:38
this is ... an interesting and exciting idea
so there are two possible issues that could prevent us from helping you. One is that I'm not sure we support all the SQL data types in the same way as mysql

**Comment by dt** [comment]
We have no concrete plans to build mysql tailing at this time.
