### ISSUE TITLE
stability: improve handling of indexes with large column values

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#30515]
#30399 showed a deficiency in the handling of indexes where an indexed column contains a large value. In that issue, the primary key for the table frequently contains column values that are ~64KB in size. This in turn creates KV-level keys that are ~64KB in size which get inserted into RocksDB. A large key usually (always?) ends up in the index block for an sstable because the key by itself exceeds the size target for a data block. Our current RocksDB settings have prefix compression disabled in the index block (`index_block_restart_interval==1`) resulting in sstables where each data block contains ~1 key/value and the index block is hundreds of megabytes in size. We also have RocksDB configured to pin index and filter blocks in memory. This is done for a mild performance improvement. See https://github.com/cockroachdb/cockroach/issues/7576.

The combination of the large index blocks relative to data size and the pinning of them in memory resulted in OOMs in #30399. There are several workarounds.

1. Use machines with more memory when indexing columns containing large values.
2. Avoid indexing columns containing large values.
3. Use prefix compression in index blocks. This can be done by specifying RocksDB options in the store config: `cockroach start --store=<dir>,rocksdb="block_based_table_factory={index_block_restart_interval=8}"`. The downside to this is that there will likely be a small perf hit which makes us hesitant to make this change late in the 2.1 cycle.
4. Use a [two-level index](https://rocksdb.org/blog/2017/05/12/partitioned-index-filter.html) for sstables: `cockroach start --store=<dir>,rocksdb="block_based_table_factory={index_block_restart_interval=8;index_type=kTwoLevelIndexSearch}"`.

Note that the suggested changes to the settings need to be validated. Changing `index_block_restart_interval` will only help if the keys share a large common prefix. Ideally, the default `index_block_restart_interval` and `index_type` settings would be changed in CockroachDB, but we're too late in the 2.1 cycle to do that. We need to quantify the perf impact of these changes early in the 2.2 cycle. If they are minimal we can consider backporting those settings changes to 2.1.

Cc @jseldess because we'll want to document this as a known limitation for 2.1. Leaving this in the 2.1 milestone even though the engineering work will be targeted at 2.2.

Jira issue: CRDB-4830

**Comment by jseldess** [comment]
Thanks for the heads up, @petermattis. I opened a general [docs issue for 2.1 limitations](https://github.com/cockroachdb/docs/issues/3774).

**Comment by bdarnell** [comment]
Increasing the block size would also reduce the index size. For this table (which is not used for point lookups), we don't benefit from the read performance improvements of small blocks.

In bigtable, block size was one of the most effective knobs to tune (on a per-table basis). This is a situation where it might make sense to be able to have different rocksdb settings per table (managed as multiple rocksdb column families, I guess?)

**Comment by bdarnell** [comment]
Ack. I was thinking (incorrectly) that doubling the block size would halve the index size, but forgot that that breaks down when there are single large keys.

**Comment by sploiselle** [comment]
@petermattis Can I get you to draft a short blurb describing this known limitation for the 2.1 known limitation page? I see the solutions are here, which will be easy to use, but could use a `tl;dr` on how the impacts users' experiences. Posting it on this issue and/or pinging me would be great.

**Comment by petermattis** [comment]
@sploiselle The use of tables with very large primary or secondary index keys can result in excessive memory usage. Specifically, if the primary or secondary index key is larger than 32KB the default indexing scheme for RocksDB sstables breaks down and causes the index to be excessively large. The index is pinned in memory by default for performance. I'd recommend limiting the size of primary and secondary keys to 4KB (we currently do not have a mechanism for enforcing this). If that isn't possible, one or more of the RocksDB tunables mentioned above will have to be explored.

**Comment by petermattis** [comment]
(I can say this again in different words if you need further explanation).

**Comment by bra-fsn** [comment]
@petermattis: could you please elaborate more on the effects of this:

> We also have RocksDB configured to pin index and filter blocks in memory.

I mean will CockroachDB have a linearly growing memory need with growing amount of data? Does it store all data contained in indices in memory?

**Comment by petermattis** [comment]
> I mean will CockroachDB have a linearly growing memory need with growing amount of data? Does it store all data contained in indices in memory?

Yes, all RocksDB sstable index blocks need to be stored in memory. This causes memory consumption to be related to the total data set size. Note that these are RocksDB indexes, not CockroachDB indexes. RocksDB indexes are much smaller than CockroachDB indexes (they are totally different concepts).

I imagine we'll lift this requirement at some point in the future. There is a RocksDB option to do so, but it comes with a performance hit.

**Comment by bra-fsn** [comment]
Thanks @petermattis!
Is it possible to get the amount of memory used for this purpose? (would be best to get it from CockroachDB for tables, if this info can be collected easily -maybe not?)

**Comment by petermattis** [comment]
> Is it possible to get the amount of memory used for this purpose? (would be best to get it from CockroachDB for tables, if this info can be collected easily -maybe not?)

I believe there is a per-node (or per-store) "rocksdb.block.cache.pinned-usage" metric. This will show up on the `/_status/vars` page (prometheus format metrics) as `rocksdb_block_cache_pinned_usage`. I don't think this is exposed elsewhere in the web UI at this time, nor is it exposed via SQL virtual tables.

**Comment by jseldess** [comment]
This is a documented limitations, so I don't think this issue should be closed. I'll change that.
