### ISSUE TITLE
perf: remove locking from hlc.PhysicalNow/hlc.PhysicalTime

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#30520]
`hlc.PhysicalNow` and `hlc.PhysicalTime` provide access to the hybrid logical clock's physical component. Accessing the hlc's state is expensive because it requires a lock acquisition for a lock which is fairly contended. As such, we should be deliberate when using the `hlc` and avoid using it when possible.

In a lot of cases, a system clock is more than sufficient and should be a lot cheaper. These cases include access to time in the:
- [ ] `StorePool`
- [ ] (#30651/@a-robinson) `replicaStats`
- [ ] (TODO/@nvanbenschoten) `replica.lastUpdateTimes`
- [ ] (TODO/@andreimatei) `TxnCoordSender.Send` and `TxnCoordSender.maybeSleepForLinearizable`
- [ ] `rpc/breakerClock` and `rpc/Context`
- [ ] `connExecutor` all over the place
- [ ] `RuntimeStatSampler`
- [ ] `MetricsRecorder`
- [ ] `authenticationServer`
- [ ] `log.selectEventTimestamp`
_... maybe others ..._

We should audit uses of the hlc clock and make sure they actually need the added semantics it provides.

EDIT: the direction of this issue has changed. See https://github.com/cockroachdb/cockroach/issues/30520#issuecomment-424528599.

**Comment by nvanbenschoten** [comment]
I talked to @bdarnell about this and he was surprised that we were grabbing the HLC mutex in `hlc.PhysicalNow`. We do so in order to detect clock jumps, but Ben thinks this goes against the original purpose of the method. It should be a pass-through to the underlying time source which does not require any locking but permits mocking in tests.

I think we should restore the original intention of the method so that we can remove the lock entirely and fix all of these work items in one swoop. To do so, we'll need to audit all callers to make sure none of them rely on the clock jump detection.

**Comment by bdarnell** [comment]
> We do so in order to detect clock jumps, but Ben thinks this goes against the original purpose of the method.

To be clear, the clock jump detection is important, I just think it belongs in `hlc.Clock.Now` instead of `PhysicalNow`.

**Comment by nvanbenschoten** [comment]
Moving this to 2.2 because none of these changes will be backported.

**Comment by a-robinson** [comment]
Sure, I'll take this over.
