### ISSUE TITLE
cockroach workload fails after a few moments when running in Kubernetes

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/cockroach#30567]
I ran `docker run cockroachdb/cockroach-unstable workload run tpcc --warehouses 1 --drop --tolerate-errors [pgurl]` twice from my local machine and once from k8s. This was using the Cockroach client binary `v2.1.0-beta.20180917`. Each run pointed to a cluster running in AWS (v2.0.5 -- betas don't work here either). The first two local runs worked fine, but the run in k8s fails after a few inserts. See the chart below.

![image](https://user-images.githubusercontent.com/894257/45963901-55f65d00-bff2-11e8-964e-986faa147c2c.png)

This was the kubernetes command I ran: `kubectl run tpcc --image=cockroachdb/cockroach-unstable --labels app=cockroachdb -- workload run tpcc --warehouses 1 --drop --tolerate-errors "postgresql://root@cockroachdb-public:26257?application_name=ycsb&sslmode=disable"`

I would have expected this to fail immediately or work as it did when I ran from docker. The pod doesnt crash

```
ubuntu@ip-10-0-20-209:~$ kubectl get pods
NAME                   READY     STATUS    RESTARTS   AGE
cockroachdb-0          1/1       Running   0          1h
cockroachdb-1          1/1       Running   0          1h
cockroachdb-2          1/1       Running   0          1h
tpcc-c654dccf8-cjb4n   1/1       Running   0          9m
```

Unfortunately, tpcc doesn't print any logs while it's loading data so I can't figure out why its hanging.

**Comment by nstewart** [comment]
@a-robinson or @danhhz - anything obvious that I'm overlooking?

**Comment by danhhz** [comment]
Mind assigning someone else to look into this? I don't know anything about k8s and I'm already oversubscribed with changefeed stuff

**Comment by a-robinson** [comment]
By "fails after a few inserts" you mean it just keeps running but stops sending sql queries?

I don't know if it fully explains the behavior, but I suspect that using `--labels app=cockroachdb` is a problem. That label will match the `cockroachdb-public` service's selector, meaning that some of its requests could be getting funneled back to itself. Try again without the label on the workload pod.

**Comment by danhhz** [comment]
As far as I know, workload just passes the url you give it to lib/pq unchanged, so I don't see why it would be any different than another load generator here.

**Comment by nstewart** [comment]
Can confirm, it was `--labels`, didn't realize that was the service selector. What I don't understand is why this works for our non `workload` loads. I'll chalk this up to user error in the meantime.
