### ISSUE TITLE
sql: enable client customization of the name of the auto-retry savepoint

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#30588]
Spring ORM has a built-in transaction template that assumes that you can name savepoints whatever you want. Unfortunately, this does not work with the current implementation of Cockroach restart. 

CRL proposed replicating the process we used with SQLAlchemy. Unfortunately, while Spring is generally customizable it will not work in this use case.

Instead, CRL proposed adding a connection setting. This will allow users to take advantage of client-side retries by removing the check on the name of savepoint. This check currently exists to make sure that users use this functionality to retry transaction and not for the SQL feature savepoints. If users turned this connection setting on and attempted to use the SQL feature savepoints it would not work.

cc @bdarnell to make sure this is captured correctly

**Comment by bdarnell** [comment]
The question I have about this is whether it's actually valuable to go through the ORM's nested-transaction support at all. If you ignore the nested transaction support and just execute the SAVEPOINT commands as if they were updates, do you lose anything? It's entirely possible that you do (the whole reason that we use the SAVEPOINT keyword is because in ORMs like SQLAlchemy, the nested transaction machinery's use of RELEASE and ROLLBACK TO SAVEPOINT serves as cache invalidation triggers), but we should make sure that we're doing this because it's going to be useful and not just to use the nested-transaction commands when a basic execute would work as well.

**Comment by bdarnell** [comment]
Returning to first principles, is a solution other than this SAVEPOINT hack possible?

If we introduced a kind of transaction ID that the client could retrieve on the first attempt of a transaction and set on any retries, this would allow us to connect the retry to a still-open KV level transaction, without allowing any other client-visible magic in the execution of the transaction. The downside to this is that we'd need to keep the KV transaction open for the possibility that it would be resumed, but the client could crash or give up and this might not happen (leaving the transaction open and holding its locks for a timeout). We could discuss this possibility with clients and see if it would be preferable to the contortions necessary to use savepoint for retries. 

(This feels closely related to causality tokens. Not quite the same thing but maybe there's some overlap in the syntax and the client-side sugar needed to make them usable)

**Comment by bobvawter** [comment]
For the docs team:

We'll want to update https://www.cockroachlabs.com/docs/stable/transactions.html#client-side-intervention with text like:

> If the `force_savepoint_restart` session variable is set to `true`, the `SAVEPOINT` command will accept any name for the savepoint, not just `cockroach_restart`.  This allows compatibility with existing code that uses a single `SAVEPOINT` per transaction as long as that `SAVEPOINT` occurs before any statements that access data stored in non-virtual tables.

**Comment by bdarnell** [comment]
The docs need to be clear that this does *not* mean that we support savepoints. This variable changes the semantics of savepoints so that RELEASE SAVEPOINT functions as a real commit. Even with this variable, savepoints can only be used as a part of the transaction retry protocol.
