### ISSUE TITLE
sql: when RETURNING expression is present, only fetch the specific columns used

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#30618]
See the following TODO:

https://github.com/cockroachdb/cockroach/blob/b2bd8e8b6446a566b667be6094e019c1040ed98d/pkg/sql/update.go#L191-L192

We currently fetch all columns when an `INSERT`, `UPDATE`, or `DELETE` statement contains a `RETURNING <exprs>` clause. This is an issue because it forces us to retreive unnecessary data and it can create exrta contention. We should determine which columns the `RETURNING` expression needs and only request those exact columns.

This should be solved in conjunction with https://github.com/cockroachdb/cockroach/issues/18168 for maximum benefit.

**Comment by nvanbenschoten** [comment]
@andy-kimball I've heard you're looking into changes in this area. Mind describing/pointing me at the status of that work? This is currently the only blocker for https://github.com/cockroachdb/cockroach/pull/30624.

**Comment by andy-kimball** [comment]
I've got a PR out for incorporating parts of the `Insert` operation into the optimizer:
https://github.com/cockroachdb/cockroach/pull/32423

I'll soon post a similar PR for `Update`. I'll then work on `Upsert`, `Delete`, and `CreateTable`.

As for your question, I think my PR's set the stage for the time when we can get more specific with the fetched columns. But the time is not yet, as we'd still need to incorporate analysis of check columns, foreign key checks, and maybe other usages of columns before we could figure out a minimal set of fetch columns. The current focus of the optimizer work is to enable decorrelated subqueries in mutation statements, as well as to incorporate latency into the optimizer's coster:

  https://github.com/cockroachdb/cockroach/issues/31955

That focus doesn't require us to figure out the minimal set of fetch columns, so I was not planning on doing it as part of my current work-stream. That said, @knz has been working on revamping SQL mutations, so between the two teams there may be a possibility of doing the necessary work this release.

**Comment by jordanlewis** [comment]
@RaduBerinde, I'm going to move this issue to planning, since I think determining the minimal set of fetch columns is something that only the optimizer can do.
