### ISSUE TITLE
distsql: cluster instability (OS OOM kills) after executing large query

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#30617]
Reported by @bladefist on Gitter

**BUG REPORT**

Please describe the issue you observed, and any steps we can take to reproduce it:

- Which version of CockroachDB are you using?

2.1 [please fill]

- What did you do?

1. database has multiple GBs of data
2. run a 3-node cluster. 32GB of RAM on each node, `--cache=.25 --sql-mem=.25`
2. run a large query (see below)
3. query fails with "budget exceeded: 8GB in budget" (as expected)
4. nodes may start to get killed by OS at this point [to be confirmed]
5. run the large query again
6. the query does not terminate; instead the gateway node is killed by the OS and the client gets a "connection closed"
7. other nodes definitely get killed by OS [to be confirmed]

`dmesg` output for steps 4 and 6 report "process killed because it tried to use more than 32GB of RAM".

- What did you expect to see?

"budget exceeded" error reported reliably each time the query is used; cluster remains otherwise stable.

- What did you see instead?

nodes terminated by OS due to memory usage far above the configured maxima (see flags above)

- What was the impact?

db unstable

cc @jordanlewis for triage

**Comment by knz** [comment]
My suspicion is some distsql memory not being accounted for (window function related).

**Comment by knz** [comment]
The distsql plan for the failing query is here:

https://cockroachdb.github.io/distsqlplan/decode.html#eJzcV91P-kgUfd-_YjJPkB1D7_QDaGIyKGwk0WIQ45pdYiqdIAlS0pbsGsP_vikF6QfMBWH1hw88MOXcj3PnnFve6cT3pOO-ypDaf1GgjHLKqE77jE4DfyDD0A_iR8kP296_1NYYHU2msyg-7jM68ANJ7XcajaKxpDbtuc9j2ZWuJ4NKHM-TkTsaL8JPg9GrG7yJVzcavMiQMtqVE08GNhGcEaEzIsBiRMQf4IxcNu5aD1ctpySsc8227bbTK3e6JQH875mm6VJY5d5Vy4HkUctpslwgoP05o_4sWpa7rvL5jby44Uu2PlFlosZEnfbnfUbDyB1KasOcbWl-HW028QNPBtLLxFtEydPzMJp4_j8yqBjZ3LeNbq_da3cccvFok49KGL27vykJq0xKnW6z1SUXj0SA9nuZMvrHaBzF5JWEQRJCyIol0nCai_NzIsz4t51ZZBMBTHAmdCYsJowcN-uO-daON_TTGA4DOXQjP6hUc2x-ZItbbTiPT06n9-TcX1-XBJQLR7x4pBePjPKKErO853BT5aTnqx93vik-QPtqQlJzNreO1_jkeEHPt0MZvWn8ubFS2Hc6PDMU8_8bilVIvOxi2whWMhOwUplp23azddm-aVx_UM5ZwW3W7Vj7UH7nB1HsnfV8oWdb41d3oGsTWcugG4pw_DN_WuGQ43Zz-lomPey-H7Qftx_gaPtBP5H9gIw7Jb288k5xPxw83xQfeYH_iuth9-kC_671cMyZgPnt6wGhfLUeap9dD3x3f-Y_zp_50fzZPBF_Rsaduvv5G3WK_nzwfNNeACdg0LuPF4zvMuijDiX_L_PrDRqhfGnQPP_v71Pv7xvid2U49Seh3OnVXIvplN5QJtyH_iwYyNvAHyzSJF87C9xi8XgyjJKn9eRLe5I8igvcHQwHgS01GvJoLY3mGbCWB3N1aqRwNVo_BAw1NVpXdm2ouzbUqZHC1WjzEDDX1GhT2bWl7tpSgqvqzFX1LUOuWe0QbanByBVFwIi26squQVN3DYiwkdIROHJLseSIvkBtK4AMHBB1Y8Wr4YjGEDQmMlB7CyDmAgWJ76MzKEh8H6kgaOzCIWhsEakNBqoIbwWL2U8tajh24ZDkmFoKNpNtvY60XvCZ_dSihmNqUaMxtfCCz2Q3AyAvIGqfyaulP__tvwAAAP__boybUw==

**Comment by jordanlewis** [comment]
Do you have the query executed? It's possible that the plan will be enough to go on, but the query will make it even easier.

**Comment by knz** [comment]
@bladefist  can I copy-paste the query here?

**Comment by knz** [comment]
For the record the following information was collected, but not replicated here until user assents on publication:

- cockroachdb log files
- dmesg kernel OOM details
- detailed SQL query
- heap_profiler dumps

The schema is also available and the user has signalled openness to access the test cluster remotely.

**Comment by knz** [comment]
Jordan says:

> it's windower.accumulateRows
> pprof is so good
> this exposes a major flow in mem acocunting
> EncDatumRowAlloc is entirely unaccounted
> and it’s one of the main users of memory in the system

**Comment by jordanlewis** [comment]
Actually, I take it back. The plot thickens, as it seems that those `CopyRow` calls directly follow a call to `Grow` a memory account by the size of the row. So why didn't the memory account hit a limit?

**Comment by bladefist** [comment]
@knz Sure.  

The purpose of the table is a listing of matches.  Users, aka `accountId` play matches, and the query is trying to find and group win streaks together.  When a loss happens, it breaks the win streak.

**Comment by jordanlewis** [comment]
We don't properly track memory used by the `encodedPartitions` bucket IDs, though. Perhaps that's the issue.

I'll send a PR, @bladefist if you like you could try out this patch and see if it fixes your problem.

**Comment by jordanlewis** [comment]
Actually, this doesn't make sense either as that doesn't show up in the allocations profile. Perhaps for some reason the memory is leaked even after the processor is closed? That could happen if the flow sits around for a little while before getting closed itself. We could solve that by setting the map that contains the allocated rows to nil during close. I'll try that as well.

**Comment by knz** [comment]
Here's the query:

```sql
SELECT dt.accountid, 
       Max(cnt) AS Streak 
FROM   (SELECT accountid, 
               playlist, 
               plateform, 
               dummy, 
               Sum(top1) AS cnt 
        FROM   (SELECT accountid, 
                       playlist, 
                       plateform, 
                       top1, 
                       matches, 
                       Sum(CASE 
                             WHEN top1 = 0 
                                   OR matches > top1 THEN 1 
                           END) 
                         OVER ( 
                           partition BY accountid, playlist, plateform 
                           ORDER BY oldid) AS dummy 
                FROM   matches) dt 
        WHERE  top1 > 0 
               AND top1 = matches 
        GROUP  BY accountid, 
                  playlist, 
                  plateform, 
                  dummy) dt 
GROUP  BY dt.accountid 
HAVING Max(cnt) > 5 
ORDER  BY Max(cnt) DESC
```

**Comment by knz** [comment]
schema:

```sql
CREATE TABLE matches (
oldid INT NULL,
accountid UUID NULL,
playlist STRING NULL,
kills INT NULL,
minutesplayed INT NULL,
top1 INT NULL,
top5 INT NULL,
top6 INT NULL,
top10 INT NULL,
top12 INT NULL,
top25 INT NULL,
matches INT NULL,
top3 INT NULL,
datecollected TIMESTAMP NULL,
score INT NULL,
plateform INT NULL,
trnrating DECIMAL NULL,
trnratingchange DECIMAL NULL,
INDEX matches_accountid_idx (accountid ASC),
INDEX matches_accountid_idx1 (accountid ASC) STORING (kills, top1, matches, playlist, plateform),
FAMILY "primary" (oldid, accountid, playlist, kills, minutesplayed, top1, top5, top6, top10, top12, top25, matches, top3, datecollected, score, plateform, trnrating, trnratingchange, rowid)
);
```

**Comment by jordanlewis** [comment]
This has gotten stale, and we've added more memory accounting as of late to window functions. I'm going to close this but feel free to comment again if you have the same issue.
