### ISSUE TITLE
sql: expose table/index stats via a crdb_internal table or builtin

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#30633]
The `databases/tables` page in the web UI currently provides info about each table's size. This is populated via the `Status.SpanStats` endpoint which aggregates `MVCCStats` across all of the ranges for a table. We should expose this info via a `crdb_internal` table or a builtin so that it can be programmatically accessed. `MVCCStats.KeyCount` gives an estimate of the number of rows in a table (though you have to adjust for column families).

**Comment by petermattis** [comment]
Cc @piyush-singh, @rolandcrosby

**Comment by knz** [comment]
Note that postgres has several SQL interfaces already defined to acccess this type of information. For better integration with 3rd party tools (e.g. DB GUIs) that are already able to display table/db stats, we might want to opt in the pre-existing pg interfaces instead of devising our own.

**Comment by jordanlewis** [comment]
Hey @RaduBerinde is this kind of thing possible enough via opt stats that this is closeable?

**Comment by RaduBerinde** [comment]
Yeah, `SHOW STATISTICS FOR TABLE` should give you the table row count. I don't understand the context of the issue enough to know if that's sufficient.

**Comment by jordanlewis** [comment]
@petermattis, I'm closing this as I think things have changed sufficiently since it was filed that it's no longer relevant.
