### ISSUE TITLE
importccl: IMPORT PGDUMP fails with syntax error on `GRANT ALL ON SCHEMA`

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/cockroach#30647]
> Is this a bug report or a feature request?

Bug report.

> Please describe the issue you observed, and any steps we can take to reproduce it:

High level steps (more detail below):

- load data from https://github.com/datacharmer/test_db into local mysql
- imported into local Postgres using pgloader
- pgloader put the data in an "employees" schema
- tried to run `IMPORT PGDUMP 'foo.sql'`, fails with a "non-public schemas not supported" error
- moved the data from the employees schema to a "public" schema in Postgres using the statement `ALTER SCHEMA employees RENAME TO public;`
- Edited the dump file to remove/change data types
- `IMPORT PGDUMP 'foo.sql'` no longer fails with the non-public schema error; now it fails with a `syntax error at or near "public"` error
- Rerun the `pg_dump` again with `--no-privileges` flag
- Edit dump again to remove data types
- `IMPORT PGDUMP 'foo.sql'` now works

It's possible I did something screwy above.  I don't really understand PG schemas, I was just trying to get past the "non-public schema" error.

> Which version of CockroachDB are you using?

`SELECT version()` says:

CockroachDB CCL v2.2.0-alpha.00000000-1019-gb9c9309d81 (x86_64-apple-darwin16.7.0, built 2018/09/24 16:37:02, go1.11)

> What did you do?

Run the following statement to import a file in AWS that causes the failure:

```
> IMPORT PGDUMP 'https://s3-us-west-1.amazonaws.com/cockroachdb-movr/datasets/employees-db/pg_dump/no-privileges-fail/employees-full.sql';
```

> What did you expect to see?

A success response looking something like

```
       job_id       |  status   | fraction_completed |  rows  | index_entries | system_records |  bytes
--------------------+-----------+--------------------+--------+---------------+----------------+----------
 381845110403104769 | succeeded |                  1 | 300024 |             0 |              0 | 11534293
(1 row)
```

> What did you see instead?

The following line (which is very near the end of the file) causes an error:

```
ERROR:  syntax error at or near "public"
source SQL:

--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: rloveland
--

GRANT ALL ON SCHEMA public TO PUBLIC;
                    ^
```

> What was the impact?

In order to dump the database in a state that could be imported into Cockroach, I needed to pass the `--no-privileges` flag to `pg_dump`.  The resulting file is stored at <https://s3-us-west-1.amazonaws.com/cockroachdb-movr/datasets/employees-db/pg_dump/employees-full.sql>.

Importing that file works as expected, e.g., 

```
> IMPORT PGDUMP 'https://s3-us-west-1.amazonaws.com/cockroachdb-movr/datasets/employees-db/pg_dump/employees-full.sql';
       job_id       |  status   | fraction_completed |  rows   | index_entries | system_records |   bytes   
--------------------+-----------+--------------------+---------+---------------+----------------+-----------
 386111590284754945 | succeeded |                  1 | 3919015 |        331636 |              0 | 105854165
(1 row)
```

Jira issue: CRDB-4825

**Comment by shermanCRL** [comment]
I think we now ignore all GRANTs. @adityamaru to confirm.
