### ISSUE TITLE
Increasing CPU performance does not result in a linear increase in TPC-C throughput 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#30658]
I'm testing CPUs affects on TPC-C

On a 3 node 8 cpu cluster:

3 | 8 | 700 | 8,763.1 | 97.35%
3 | 8 | 800 | 9,931.8 | 96.54%
3 | 8 | 900 | 10,785.5 | 93.19%
3 | 8 | 1000 | 9,957.0 | 77.43%

If doubling CPU resulted in a linear increase in supporting TPC-C we'd expect to see ~1800 warehouses supported on a 3 node 16 CPU cluster. Instead, we see:

On a 3 node 16 CPU cluster:

3 | 16 | 1500 | 18,568.9 | 96.26%
3 | 16 | 1600 | 17,916.5 | 87.07%
3 | 16 | 1700 | 17,329.2 | 79.27%

**Comment by awoods187** [comment]
I tried to run 3 node 32 CPU but hit a panic https://github.com/cockroachdb/cockroach/issues/30659

**Comment by nvanbenschoten** [comment]
Closing this as we've made a lot of progress here over the 19.1 release cycle and these values are now out-of-date.
