### ISSUE TITLE
initializing client.Batch outside of txn retryable is dangerous

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#3067]
This here will go horribly wrong (endless retry loop) unless the retryable succeeds on its first attempt.

```go
b := &client.Batch{}
b.Put(key, "test")

s.db.Txn(func(txn *client.Txn) error {
        return txn.CommitInBatch(b)
})
```

Instead, the batch needs to be initialized inside of the retryable (or the error stored within it cleared manually). I ran into this in WIP and took me a bit to track it down. We should reset errors in an appropriate location so that the above isn't a death trap.

**Comment by yaojingguo** [comment]
Happy to work on this.
