### ISSUE TITLE
perf: complete performance comparison between 2.1 and 2.0.5

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#30672]
With https://github.com/cockroachdb/cockroach/pull/30645 merged into the `release-2.1` branch, we should be able to go back and redo comparisons that we believe were affected by that change.

See the `2.1 Performance Benchmark Comparison` spreadsheet and it's associated sources. There are three workloads that need testing. Let's divide these up evenly:
- [x] `kv95` - @m-schneider 
- [x] `Customer Favourites` - @a-robinson 
- [ ] `sysbench` - @nvanbenschoten

**Comment by a-robinson** [comment]
I take it these are all meant to be run as 1 node benchmarks?

**Comment by a-robinson** [comment]
In general it's weird not seeing any desired testing conditions in the spreadsheet(s) - number of nodes, size of node, type/size of disk(s), concurrency of workload, whether the workload is run on the same machine as the database, etc. I can arbitrarily pick answers to these things, but the next time the benchmark is run the person running it may pick completely different things and get different results.

**Comment by nvanbenschoten** [comment]
I agree, I'd go so far as saying that benchmark results are close to useless without the testing conditions provided alongside them. A few of the sources have some of this information, but their choices seem arbitrary and its unclear what they're founded on.

@awoods187 do you know if there are any conditions that are implicit in these spreadsheets across all of the workloads?

**Comment by awoods187** [comment]
CC @jordanlewis and @andy-kimball as they had some opinions on this. In the future, we definitely need to be consistent.

**Comment by jordanlewis** [comment]
The master spreadsheet has measurements from different sources. For example, I was testing kv95 on a single node gce worker, but Becca was testing TPCC on a 4-node roachprod cluster, with the load generator talking only to the node it was colocated with.

I think we should use our judgement. Not every measurement has to be made in the same way, as long as the measurements for a single use case are consistent and have some real meaning. There's no chance we can test against all configurations - we should do our best, by trying to pick benchmarks that we know would be the worst case for opt and merge.

Benchmarking for purposes of evaluating overall 2.0 vs 2.1 performance improvements is different still, and requires knowing in advance what improvement we're looking at showcasing.

**Comment by a-robinson** [comment]
I've added numbers to the master spreadsheet for the Customer Favourites workload, along with linking my source spreadsheet with the exact parameters of what I ran and full data. The performance was effectively identical on a single node on 2.0 and 2.1.

**Comment by nvanbenschoten** [comment]
@m-schneider and I finished our perf comparisons as well. Everything is in the green except Sysbench's select-only workload. However, that workload is in the green with `sql.defaults.distsql=2.0-auto`, which lines up with other benchmark results. 

Thanks for the help everyone!
