### ISSUE TITLE
storage: slow adherence to replication constraints in edge case

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#30695]
https://github.com/cockroachdb/cockroach/issues/27599 details an edge case where adherence to replication constraints is slower than expected. The scenario is as follows:

1. Configure the cluster to have a replication factor of 1.
2. Set the default zone config to constrain replicas to `n4`.
3. Create a table and set the table's zone config to constrain replicas to `n2`.
4. Perform a query which should hit `n2`.

The test was sometimes failing because the range for the table was not being moved to `n2` in a timely fashion. What happens during the failure is that the creation of the table slightly precedes the creation of the zone config. When the table is created it's range is split off and a replica is quickly added to `n4`. The lease is then transferred to `n4`. A bit later, `n4` picks up the range and determines that one of the two replicas should be removed. `selectBad` flips a coin  and we remove `n4` which involves transferring the lease back to `n1`. The scanner on `n1` eventually picks up the range, sees that one of the replicas should be removed. `selectBad` again flips a coin and we remove `n1` which involves transferring the lease back to `n4`.

This ping-ponging is unfortunate and will eventually resolve itself. But there are relatively few attempts to do so in the 45s given to the test. Each ping-pong cycle has to wait for the scanner to pick up the range again (5-10s). Losing 5-10 coin flips in a row isn't impossible. And what I see is that with enough stress we can see a failure within 300-400 runs. (I believe the stress is needed to get us into the ping-ponging scenario in the first place).

One thought here is to proactively add the range to the replicate queue when a node acquires the lease. Something like:

```diff
diff --git a/pkg/storage/replica_proposal.go b/pkg/storage/replica_proposal.go
index 21372cddec..f42565adf5 100644
--- a/pkg/storage/replica_proposal.go
+++ b/pkg/storage/replica_proposal.go
@@ -302,6 +302,14 @@ func (r *Replica) leasePostApply(ctx context.Context, newLease roachpb.Lease) {
                }
        }

+       // When taking over a lease, proactively add the replica to the replicate
+       // queue. We might have been handed the lease by a remote node which wanted
+       // to remove itself from the range.
+       if leaseChangingHands && iAmTheLeaseHolder && r.store.replicateQueue != nil {
+               r.store.replicateQueue.MaybeAdd(r, r.store.Clock().Now())
+       }
+
        if leaseChangingHands && !iAmTheLeaseHolder {
                // Also clear and disable the push transaction queue. Any waiters
                // must be redirected to the new lease holder.
```

Unfortunately, this doesn't work because the replicate queue requires both the lease and Raft leadership. If we proactively add the range to the replicate queue the range will get processed before Raft leadership is transferred and `filterUnremovableReplicas` will say that no replicas are removable. This puts us right back where we started, waiting for the scanner to pick up the range on the next cycle.

Fixing this doesn't seem high priority, but it felt good to document what was going on. `TestShowTraceReplica` has been de-flaked by reducing the scan interval.

**Comment by a-robinson** [comment]
Note that the delay between the lease being transferred and the new leaseholder running the replica through the replicate queue also delays down-replication in rebalance scenarios where the old leaseholder is the replica being removed. The range can be in fragile configurations with an even number of replicas or bad locality diversity for as long as it takes the new leaseholder to finally run through the replicate queue, increasing the likelihood of range unavailability for longer than necessary (e.g. https://github.com/cockroachdb/cockroach/issues/12768).

**Comment by petermattis** [comment]
Something like the diff above could work if done when Raft leadership transfers. Perhaps that isn't too difficult to do. I've just paged out where a good location to do that is. Perhaps @tschottdorf or @nvanbenschoten have a suggestion.

**Comment by nvanbenschoten** [comment]
I don't see a reason why we couldn't reactively add replicas to queues after leadership changes like we do after leaseholder changes. That would address this issue if done in conjunction with the diff above to handle the (much rarer?) case where Raft leadership transfers to `n1` before the lease. Being more reactive to leadership changes would probably also be useful for other tasks that have some dependence on Raft leadership, although nothing is coming to mind.

I think the place you'd want to do it is right around [here](https://github.com/cockroachdb/cockroach/blob/9f191cdad64747f7f19ec4990e559cbb19e6d372/pkg/storage/replica.go#L4285).
