### ISSUE TITLE
sql: Allow for the creation of an index on a json element

### ISSUE THREAD

**Issue by rkruze** [cockroachdb/cockroach#30690]
Currently today in Postgres you can create an index on an element within a json field directly from a CREATE INDEX statement. For example: 

CREATE UNIQUE INDEX IF NOT EXISTS table_unique_idx
 ON test_table
  USING btree
  ((data->>'code'), (data->>'name'), (data->>'email_address')) where data->>'is_active'= 'true';

Something similar can be done in Cockroach but you have to create a computed column first, which in 2.0 can only be done at table creation time. Now in 2.1 you can create computed columns after the fact, so this workflow is easier but it would be great if one could create the index without having to explicitly create the computed column first.

**Comment by justinj** [comment]
This is sort of a dup of #9682.

**Comment by knz** [comment]
yeah it is a duplicate. I copied Roko's example in the other issue.

Roko depending on how important this is to you please push for this to Andy Woods.

**Comment by knz** [comment]
cc @mgartner for triage. See last user update above.

**Comment by ajwerner** [comment]
This seems like it's about allowing forward indexes on json. Loosely relates to https://github.com/cockroachdb/cockroach/issues/17154 which is forward indexes on `ARRAY` types.

**Comment by ajwerner** [comment]
This also directly relates to https://github.com/cockroachdb/cockroach/issues/35730.

**Comment by mgartner** [comment]
I don't think this is about forward indexes on JSON. 

@timgraham the `->` operator returns a `JSON` value, so you can create an inverted index on `"field" -> 'some_key'`:

```sql
CREATE TABLE t (j JSON, INVERTED INDEX ((j->'some_key')));
```

If the value of `'some_key'` is always a string or number, you can use the `->>` operator, which returns a `TEXT` value, and, if necessary, a cast:

```sql
CREATE TABLE t (j JSON, INDEX ((j->>'some_key')));
```

```sql
CREATE TABLE t (j JSON, INDEX (((j->>'some_key')::FLOAT)));
```

The error message is not very clear though. I've opened #69589 to track improvements for the errors.

**Comment by timgraham** [comment]
The example I provided is from a Django test that works on PostgreSQL. Would it be inappropriate for CockroachDB to implicitly add the INVERTED part so that the query works?

If it can't be addressed in CockroachDB, it sounds like we should try to make the Django adapter for CockroachDB rewrite the query to add "INVERTED" to the CREATE INDEX, but offhand I'm not sure how difficult this would be, or if it's even feasible. 

The index is created in Python with `Index('field__some_key', name='func_json_key_idx')`. Alternatively, if query rewriting isn't feasible, it might work to introduce a new `InvertedIndex` class for CockroachDB, but this would mean some code changes would be required to migrate from PostgreSQL to CockroachDB (changing `Index` to `InvertedIndex` where necessary).

**Comment by knz** [comment]
@rafiss can you provide insight re the comment above on Django compatibility?

**Comment by knz** [comment]
@timgraham can you please provide a full python/django program that reproduces the issue, thanks

**Comment by mgartner** [comment]
@timgraham Can you share the example that works in Postgres? I am unable to get it working as you describe.

In Postgres:

```
marcus=# CREATE TABLE t (j JSON);
CREATE TABLE

marcus=# CREATE INDEX ON t ((j->'some_key'));
ERROR:  42704: data type json has no default operator class for access method "btree"
HINT:  You must specify an operator class for the index or define a default operator class for the data type.
LOCATION:  ResolveOpClass, indexcmds.c:1980
```

**Comment by rafiss** [comment]
looks like it has to be `JSONB` for it to work in Postgres

```
rafiss@127:postgres> CREATE TABLE "schema_jsonmodel" ("id" serial NOT NULL PRIMARY KEY , "field" jsonb NOT NULL);

rafiss@127:postgres> CREATE INDEX "func_json_key_idx" ON "schema_jsonmodel" ((("field" -> 'some_key')));
```

In CRDB, `json` and `jsonb` are identical, so not sure what that means for how compatible we can be with Postgres here.

To me, it makes sense that this difference could be handled in the django-cockroachdb adapter, and automatic rewriting sounds like the ideal, if it's feasible.

**Comment by ajwerner** [comment]
FWIW, json forward indexes don't sound crazy to me. Isn't that what postgres is doing? We have a canonical representation in bytes, right? Don't we already sort the keys?

**Comment by knz** [comment]
IIRC the issue is that there's no sortable encoding for JSONB

**Comment by ajwerner** [comment]
> IIRC the issue is that there's no sortable encoding for JSONB

How can that be true? It might be expensive to get one, but the cast from `JSONB` to `STRING` is immutable and strings are sortable.

**Comment by knz** [comment]
I mean, an encoding that preserves the JSON order the same way as postgres?

**Comment by rafiss** [comment]
also linking: https://github.com/cockroachdb/cockroach/issues/35706

apparently this used to not work, but it works now:
```
> create table t (ext json);
> insert into t values ('{"foo": "bar"}');
> select distinct ext->'foo' from t;
```

(In postgres, the above works for JSONB but not for JSON)
