### ISSUE TITLE
sql: a delete query uses the wrong index

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#30734]
Reported privately. The following table (scrubbed of identifying information) produces an incorrect plan when being deleted from.

```
root@127.0.0.1:53703/defaultdb> CREATE TABLE a (
    a INT NOT NULL,
    b STRING NOT NULL,
    c INT NOT NULL,
    d INT NOT NULL,
    e STRING NOT NULL,
    f BOOL NOT NULL DEFAULT false,
    g TIMESTAMP NOT NULL DEFAULT now(),
    h STRING NOT NULL DEFAULT 'foo',
    i TIMESTAMP NOT NULL DEFAULT now(),
    j STRING NOT NULL DEFAULT 'foo',
    k DATE NULL,
    l STRING NULL,
    PRIMARY KEY (a, b, c, d, e, f),
    INDEX (a, e, k, l) STORING (a, b, c, d, e, f),
    INDEX (a, e, k, l) STORING (g, h)
);

Time: 6.448ms

root@127.0.0.1:53703/defaultdb> explain delete from a where a=10 and b='10' and c=1 and d=3;
         tree         | field |   description
+---------------------+-------+-----------------+
  count               |       |
   └── delete         |       |
        │             | from  | a
        └── render    |       |
             └── scan |       |
                      | table | a@a_a_e_k_l_idx
                      | spans | /10-/11
(7 rows)
```

The delete should search the primary index, as it can provide a more precise span.

cc @andy-kimball, but we have to fix this in the heuristic planner if we wish to provide a fix for the 2.0 branch.

**Comment by knz** [comment]
I do not know why this was assigned to me. I never had anything to do with index selection in the heuristic planner. 

@RaduBerinde who do you think has the most up-to-date knowledge on this?

**Comment by RaduBerinde** [comment]
The heuristic planner has some formulas that try to balance between various factors; in this case the relevant one are the number of constrained columns and the size of the index we are scanning. The primary index has 12 columns and can be constrained on 4, the first `a,e,k,l` index has 8 and can be constrained on 1. Granted, preferring the primary index doesn't make much sense in this case, but the fact that these formulas won't work well in many cases is partly why we implemented an optimizer in the first place. This should be fixed once the optimizer supports DML.

We can try to tweak the heuristic planner but it might regress on other cases.

By the way, I'm surprised `INDEX (a, e, k, l) STORING (a, b, c, d, e, f),` is valid (repeating `a` and `e` is silly). Anyway in this case the `STORING` is superfluous since stores all PK columns anyway.

**Comment by knz** [comment]
@awoods187 @jordanlewis my understanding of Radu's response is "it's too complicated to fix in 2.0, and it won't be fixed in 2.1 either" (because the opt code will only learn about mutations in 2.2).

**Comment by jordanlewis** [comment]
> By the way, I'm surprised INDEX (a, e, k, l) STORING (a, b, c, d, e, f), is valid (repeating a and e is silly). Anyway in this case the STORING is superfluous since stores all PK columns anyway.

This is another consequence of the mess that caused #30984, btw, and I'm going to fix it.

**Comment by knz** [comment]
@jordanlewis regarding the original query, is it possible for the customer to use `delete ... from a@specific_index`?

**Comment by awoods187** [comment]
```root@127.0.0.1:63091/defaultdb> explain delete from a@primary where a=10 and b='10' and c=1 and d=3;
invalid syntax: statement ignored: syntax error at or near "@"
DETAIL: source SQL:
explain delete from a@primary where a=10 and b='10' and c=1 and d=3;
                     ^```

**Comment by knz** [comment]
aha. Maybe that's where we should be starting for a workaround. Thanks Andy for checking.

**Comment by knz** [comment]
ok I'll prepare the workaround functionality for 2.0/2.1

**Comment by knz** [comment]
ok the workaround is ready in #31012

unassigning myself again

**Comment by jordanlewis** [comment]
> > By the way, I'm surprised INDEX (a, e, k, l) STORING (a, b, c, d, e, f), is valid (repeating a and e is silly). Anyway in this case the STORING is superfluous since stores all PK columns anyway.

> This is another consequence of the mess that caused #30984, btw, and I'm going to fix it.

Submitted a fix for that in https://github.com/cockroachdb/cockroach/pull/31019.

**Comment by knz** [comment]
Jordan your patch in #31019 has broke the example at the start of this issue!

- this invalidated the test case I produced for #31012 so I have to find another case
- are you sure the customer will be ok with the change?

**Comment by jordanlewis** [comment]
Sorry for the trouble. It's important to ban this case, as it's semantically invalid. The schema above was the one that originally caused the customer issue solved by #31019.

Also, we've confirmed with the customer that it's ok. This is the right thing to do.

**Comment by andy-kimball** [comment]
@jordanlewis, should this issue be closed out now that it's returning an error?

**Comment by jordanlewis** [comment]
Yeah, this is closeable. Thanks for noticing.
