### ISSUE TITLE
sql: prefer a non-primary index to satisfy ORDER BY even if no contraints in WHERE

### ISSUE THREAD

**Issue by leomkkwan** [cockroachdb/cockroach#30742]
I have an index on `date` column in my table.

```
explain select * from universe.screenview  order by date desc ;
sort		
 │	order	-date
 └── scan		
	table	screenview@primary
	spans	ALL
```

When I select only 1 row, it works 

```
explain select * from universe.screenview  order by date desc limit 1;	
index-join		
 ├── scan		
 │	table	screenview@screenview_date_idx
 │	spans	ALL
 │	limit	1
 └── scan		
	table	screenview@primary		
```

But if I select with a where clause, even that row exists as the first row, it still need to scan full table.

```
explain select * from universe.screenview  where ip = '127.0.0.1' order by date desc limit 1; 
limit		
 └── sort		
      │	order	-date
      └── scan		
	table	screenview@primary
	spans	all
```

I would expect that this is a fast query; just like how mysql did, but it doesn't seem like it is.

**Comment by knz** [comment]
An index can only optimize queries that use the indexed columns in the WHERE clauses.

Here you have an index on `date` but you do `WHERE ip = `.

for this query to become fast you need an index on `ip` first, then `date`. Both need to be added to the index. For example:

`CREATE INDEX ON universe.screenview(ip, date)`

Does this help?

**Comment by leomkkwan** [comment]
Make perfect sense, but a surprise as I am used to mysql world. In mysql, the above query will both use the date index. Understand that is different technology and hard to compare, but would be nice if CRDB can handle that more DBA friendly.

**Comment by knz** [comment]
@leomkkwan I have checked and MySQL does not have a different behavior here. Consider:

```
kena@localhost [kena]> create table screenview(ip varchar(10), date date);
Query OK, 0 rows affected (0.03 sec)

kena@localhost [kena]> create index screenview_date_idx on screenview(date);
Query OK, 0 rows affected (0.02 sec)
Records: 0  Duplicates: 0  Warnings: 0

kena@localhost [kena]> explain select * from screenview  where ip = '127.0.0.1' order by date desc limit 1;
+----+-------------+------------+------------+------+---------------+------+---------+------+------+----------+-----------------------------+
| id | select_type | table      | partitions | type | possible_keys | key  | key_len | ref  | rows | filtered | Extra                       |
+----+-------------+------------+------------+------+---------------+------+---------+------+------+----------+-----------------------------+
|  1 | SIMPLE      | screenview | NULL       | ALL  | NULL          | NULL | NULL    | NULL |    1 |   100.00 | Using where; Using filesort |
+----+-------------+------------+------------+------+---------------+------+---------+------+------+----------+-----------------------------+
1 row in set, 1 warning (0.00 sec)
```

Look at the EXPLAIN column "type" - it says ALL, which indicates a full table scan. Also the last column indicates "filesort" meaning the ORDER BY does not use an index.

Compare for example, if I use `WHERE date = ...` (on an indexed column)

```
kena@localhost [kena]> explain select * from screenview where date = '2018-01-01' order by date desc limit 1;
+----+-------------+------------+------------+------+---------------------+---------------------+---------+-------+------+----------+-------+
| id | select_type | table      | partitions | type | possible_keys       | key                 | key_len | ref   | rows | filtered | Extra |
+----+-------------+------------+------------+------+---------------------+---------------------+---------+-------+------+----------+-------+
|  1 | SIMPLE      | screenview | NULL       | ref  | screenview_date_idx | screenview_date_idx | 4       | const |    1 |   100.00 | NULL  |
+----+-------------+------------+------------+------+---------------------+---------------------+---------+-------+------+----------+-------+
1 row in set, 1 warning (0.00 sec)
```

Here the index is used, `type = ref` and `extra = NULL` (no `filesort`).

Only if I create the missing index on `ip` your original query is optimized in MySQL too:

```
kena@localhost [kena]> create index extra_idx on screenview(ip, date);
Query OK, 0 rows affected (0.02 sec)
Records: 0  Duplicates: 0  Warnings: 0

kena@localhost [kena]> explain select * from screenview  where ip = '127.0.0.1' order by date desc limit 1;
+----+-------------+------------+------------+------+---------------+-----------+---------+-------+------+----------+--------------------------+
| id | select_type | table      | partitions | type | possible_keys | key       | key_len | ref   | rows | filtered | Extra                    |
+----+-------------+------------+------------+------+---------------+-----------+---------+-------+------+----------+--------------------------+
|  1 | SIMPLE      | screenview | NULL       | ref  | extra_idx     | extra_idx | 13      | const |    1 |   100.00 | Using where; Using index |
+----+-------------+------------+------------+------+---------------+-----------+---------+-------+------+----------+--------------------------+
1 row in set, 1 warning (0.00 sec)
```

Does this clarify?

**Comment by leomkkwan** [comment]
@knz Thanks again to looking into this....
I have different result then yours, the only different is my test table have primary key.
If I test with a table without primary key, I have the same result as yours.


create table screenview2(id int not null auto_increment primary key, ip varchar(10), date date);
create index screenview2_date_idx on screenview2(date);

mysql> mysql> explain select * from screenview  where ip = '127.0.0.1' order by date desc limit 1;
+----+-------------+------------+------------+-------+---------------+---------------------+---------+------+------+----------+-------------+
| id | select_type | table      | partitions | type  | possible_keys | key                 | key_len | ref  | rows | filtered | Extra       |
+----+-------------+------------+------------+-------+---------------+---------------------+---------+------+------+----------+-------------+
|  1 | SIMPLE      | screenview | NULL       | index | NULL          | screenview_date_idx | 4       | NULL |    1 |    14.29 | Using where |
+----+-------------+------------+------------+-------+---------------+---------------------+---------+------+------+----------+-------------+
1 row in set, 1 warning (0.00 sec)

Although there is no possible key, mysql still use the date index.

mysql> explain select * from screenview where date = '2018-01-01' order by date desc limit 1;
+----+-------------+------------+------------+------+---------------------+---------------------+---------+-------+------+----------+-------+
| id | select_type | table      | partitions | type | possible_keys       | key                 | key_len | ref   | rows | filtered | Extra |
+----+-------------+------------+------------+------+---------------------+---------------------+---------+-------+------+----------+-------+
|  1 | SIMPLE      | screenview | NULL       | ref  | screenview_date_idx | screenview_date_idx | 4       | const |    1 |   100.00 | NULL  |
+----+-------------+------------+------------+------+---------------------+---------------------+---------+-------+------+----------+-------+
1 row in set, 1 warning (0.00 sec)

mysql> explain select * from screenview order by date desc limit 1;
+----+-------------+------------+------------+-------+---------------+---------------------+---------+------+------+----------+-------+
| id | select_type | table      | partitions | type  | possible_keys | key                 | key_len | ref  | rows | filtered | Extra |
+----+-------------+------------+------------+-------+---------------+---------------------+---------+------+------+----------+-------+
|  1 | SIMPLE      | screenview | NULL       | index | NULL          | screenview_date_idx | 4       | NULL |    1 |   100.00 | NULL  |
+----+-------------+------------+------------+-------+---------------+---------------------+---------+------+------+----------+-------+
1 row in set, 1 warning (0.00 sec)

**Comment by knz** [comment]
Interesting, that is worth investigating further.

@RaduBerinde @andy-kimball this problem is suggesting us it would be advantageous to select a non-primary index **to satisfy the sort clause even if there is no index that can be used for the WHERE clause**.

Currently cockroachDB does not do this (it gives up index selection if there are no where constraints?). 

At least this is what I am observing in 2.1.

I think it's useful to look into this as a potential optimization.

**Comment by knz** [comment]
the reason is that if there are more than 1 row, it will be advantageous to utilize the order provided by the index instead of having to add an extra sort stage.

**Comment by andy-kimball** [comment]
This looks like a bug in 2.1 that was introduced as part of my performance work a month or so ago. We should be using that index to satisfy the ordering.

CC: @RaduBerinde

**Comment by andy-kimball** [comment]
Actually, this is more complex than I at first thought. I don't think our recent changes affected this plan after all.

The trouble is that the `date` index does not cover the `ip` column. If we use the `date` index, we have to do the following:

1. Load each row from the `date` index
2. Because the index row does not contain the `ip` column, we need to fetch the corresponding row from the primary index anyway.
3. Once we have the corresponding primary index row, we evaluate the `ip` filter condition.
4. If that's true, then we can exit early.

So this plan would only be better if a high percentage of rows have `ip=127.0.0.0`. The worst case is when there's only one row in the table with `ip=127.0.0.0`, and it's located at the very end of the `date` index. In that case, we'd end up scanning the entire `date` index *plus* probe into every row in the primary index! That'd be way slower than scanning the primary index once and then sorting.

If at all possible, I'd recommend at least adding the `ip` column as a `STORING` column in the `date` index:
```
create index screenview_date_idx on screenview(date) storing (ip);
```
Alternatively, you could add another index as Raphael suggested.

I question MySql using the date index for this query, unless it knows that `ip=127.0.0.0` is true in a fairly large percentage of rows. I bet it doesn't, and it just got lucky with this plan, and that in other circumstances it turns out to be a very bad plan.

**Comment by RaduBerinde** [comment]
I don't think there is any missing optimizer functionality here anymore.
