### ISSUE TITLE
teamcity: failed test: TestCDC

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#30740]
Failed in PR build https://teamcity.cockroachdb.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=930052&_focus=15339 with the error:

```
cdc_kafka_test.go:60: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)
```

**Comment by danhhz** [comment]
in the past these have been some combination of docker + teamcity being flaky. fyi for anyone following along, i'm unlikely to find time to make this more resilient soon

**Comment by danhhz** [comment]
Welp we just got another one. May have to bump this up in priority. Not super sure about what I can do here, perhaps #27292
