### ISSUE TITLE
all: update dependencies

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#30774]
We haven't updated our vendored dependencies in a while.

**Comment by knz** [comment]
@benesch @bdarnell  do we have a process in place to periodically update dependencies?

**Comment by RaduBerinde** [comment]
I don't think so. I was planning to do it this time but forgot about it. I'll try to get to it.

**Comment by tbg** [comment]
We need to audit all the commits we're picking up. I remember that @tamird had some script to do this automatically. @tamird, do you remember where that went?

**Comment by benesch** [comment]
Are you thinking of github.com/dt/depdiff?

**Comment by tbg** [comment]
That's exactly it, thanks!

**Comment by RaduBerinde** [comment]
Great! I will try to do it in multiple batches, and separate out the more important packages (like gRPC), so we can at least bisect if there's a problem.

**Comment by petermattis** [comment]
Note that @benesch and I are bumping RocksDB (which is a massive pain).

**Comment by RaduBerinde** [comment]
Strange, `dep-diff-parser` reports this, of which there is no trace in the Gopkg.lock file:
https://github.com/GoogleCloudPlatform/google-cloud-go/compare/0fd7230b...0ebda48a

**Comment by RaduBerinde** [comment]
Oh, I see, it's a github mirror, never mind.

**Comment by RaduBerinde** [comment]
The protobuf-related deps cannot be updated right now. The new stuff breaks some `Clone` functionality in `gogoproto` that we use; I will need to make a fix upstream first.

**Comment by RaduBerinde** [comment]
I believe that I updated all dependencies, except `github.com/Shopify/sarama` which @danhhz will update later in the release. Some of the dependencies have already had updates since so we may want to do a full update at that point.

I will keep the issue open as a reminder to update deps periodically.
