### ISSUE TITLE
randomize replica order within each bucket

### ISSUE THREAD

**Issue by veteranlu** [cockroachdb/cockroach#3078]
datanode workload lost balance while running readonly stress test, It always choose the first replica as leader, randomize replica order maybe solve this problem, I find a TODO as follow:
`
// TODO(peter): need to randomize the replica order within each bucket.
func (rs replicaSlice) SortByCommonAttributePrefix(attrs []string) int {
`

**Comment by tamird** [comment]
I think this is in progress in #3041

**Comment by veteranlu** [comment]
@tamird That's great, can I close this issue?

**Comment by tamird** [comment]
Yep. Closing as duplicate of #2957.
