### ISSUE TITLE
acceptance: TestDockerCLI/test_url_db_override.tcl failure

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#30796]
I've seen 2 failures of `TestDockerCLI/test_url_db_override.tcl` on release-2.1 CI runs: https://teamcity.cockroachdb.com/viewLog.html?buildId=933292&buildTypeId=Cockroach_UnitTests_Acceptance&tab=artifacts#!-1uziz2a3hy42,-1ozcfozzxxdsw,sq8irxtiezz4

I think the relevant portion of the logs is:

```
.180929 14:49:24.455725815 EXPECT TEST: START TEST: Check that the host flag overrides the host if URL is already set.
spawn /cockroach/cockroach sql --url postgresql://root@localhost:26257?sslmode=disable --host nonexistent -e select 1
Error: cannot dial server.
Is the server running?
If the server is running, check --host client-side and --advertise server-side.

dial tcp: i/o timeout
Failed running "sql"
expect: spawn id exp15 not open
    while executing
"expect {
	$text {}
	timeout { handle_timeout $text }
    }"
    (procedure "eexpect" line 2)
    invoked from within
"eexpect eof"
    (file "/go/src/github.com/cockroachdb/cockroach/cli/interactive_tests/test_url_db_override.tcl" line 91)
non-zero exit code: 1
```

Looks like we can't dial the server, but that seems expected here due to the `--host nonexistent` flag.

**Comment by petermattis** [comment]
I can't reproduce this failure locally on either master or release-2.1.

**Comment by petermattis** [comment]
The problem is the error that is being generated. On teamcity,  the error is `dial tcp: i/o timeout`. Locally, the error is `dial tcp: lookup nonexistent on 127.0.0.11:53: no such host`. The test is looking for the term `nonexistent` in the output and isn't finding it. Perhaps this is a difference in DNS settings between locally and teamcity (though shouldn't they be using the same builder image?).

**Comment by tschottdorf** [comment]
I did bump the teamcity agent image (moving to ubuntu18.04) when I first saw this failure, which might be related. I've sent a PR to skip this test until @knz can take a look next week. #30798

**Comment by andreimatei** [comment]
I've just ran into a failure here, with the purported fix:
https://teamcity.cockroachdb.com/viewLog.html?buildId=1079617&tab=buildResultsDiv&buildTypeId=Cockroach_UnitTests_Acceptance

**Comment by knz** [comment]
Yes thanks I wasn't really convinced my PR would make a difference :)

Thankfully I found a better fix. PR incoming.
