### ISSUE TITLE
panic: RangeLookup dispatched to correct range, but no matching RangeDescriptor was found

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#3079]
> panic: RangeLookup dispatched to correct range, but no matching RangeDescriptor was found: "\x00\x00meta1a" [recovered]
	panic: RangeLookup dispatched to correct range, but no matching RangeDescriptor was found: "\x00\x00meta1a"

https://circleci.com/gh/cockroachdb/cockroach/9143

I haven't been able to reproduce this locally yet, just over 500 runs as of this writing.

**Comment by tschottdorf** [comment]
https://circleci.com/gh/tschottdorf/cockroach/1684

**Comment by tschottdorf** [comment]
hard to reproduce, I should add some logging to `RangeLookup` that gives us a complete history of what was going on if the panic triggers.

**Comment by tschottdorf** [comment]
Reproduces much more readily now. Investigating.
