### ISSUE TITLE
workload: expose pprof http endpoints

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#30810]
`workload` should expose [pprof http endpoints](https://golang.org/pkg/net/http/pprof/) so that it can be debugged in a similar manner to the main CockroachDB process. This is important because performance problems can often be due to client-side issues, so when debugging performance degredations we'll want to confirm that `workload` is behaving correctly.

While doing so, we should make sure to:
- set the mutex profile fraction to have access to mutex profiles: [`runtime.SetMutexProfileFraction`](https://golang.org/pkg/runtime/#SetMutexProfileFraction)
- set the blocking profile fraction to have access to blocking profiles: [`runtime.SetBlockProfileRate`](https://golang.org/pkg/runtime/#SetBlockProfileRate)
- expose a flag to adjust the http server port so that it can be put on port 26258 by roachprod (or some other port that's whitelisted in GCE)

**Comment by nvanbenschoten** [comment]
I'm sure this would have been helpful to @a-robinson during his exploration of #30284.

**Comment by a-robinson** [comment]
> I'm sure this would have been helpful to @a-robinson during his exploration of #30284.

It was helpful -- I did it locally in pkg/cmd/workload/main.go, although not in the most reusable way.

**Comment by m-schneider** [comment]
Thanks Alex!

**Comment by nvanbenschoten** [comment]
To clarify, @a-robinson you haven't done anything here that you actually plan to publish, right?

**Comment by a-robinson** [comment]
Correct, unless you're cool with this very lazy diff:

```
diff --git a/pkg/cmd/workload/main.go b/pkg/cmd/workload/main.go
index 715a0579a8..14c546dbf3 100644
--- a/pkg/cmd/workload/main.go
+++ b/pkg/cmd/workload/main.go
@@ -16,7 +16,10 @@
 package main

 import (
+       "net/http"
+       _ "net/http/pprof"
        "os"
+       "runtime"

        _ "github.com/cockroachdb/cockroach/pkg/ccl/workloadccl/allccl" // init hooks
        _ "github.com/cockroachdb/cockroach/pkg/ccl/workloadccl/cliccl" // init hooks
@@ -24,6 +27,9 @@ import (
 )

 func main() {
+       runtime.SetBlockProfileRate(1)
+       runtime.SetMutexProfileFraction(1)
+       go http.ListenAndServe(":8888", nil)
        if err := workloadcli.WorkloadCmd(false /* userFacing */).Execute(); err != nil {
                // Cobra has already printed the error message.
                os.Exit(1)
```

**Comment by nvanbenschoten** [comment]
Hah, let's keep `workload` clean. I'm sure @danhhz would appreciate it.

One thing to remember when making this change is that `workload` is both a stand-alone cli tool and a library. The pprof server should only be enabled when `workload` is being used on its own.

**Comment by petermattis** [comment]
@m-schneider Is there anything left to do here?

**Comment by m-schneider** [comment]
No, I tested it and it works.
