### ISSUE TITLE
select with limit not working correctly

### ISSUE THREAD

**Issue by damienhollis** [cockroachdb/cockroach#30812]
**BUG REPORT**

Please describe the issue you observed, and any steps we can take to reproduce it:

- Which version of CockroachDB are you using?
v2.1.0-beta.20180924

- What did you do?
```
create table school
(
  id    int   not null primary key,
  name  text  not null
);
create table student
(
 id    int  not null primary key,
 name  text not null,
 school_id int REFERENCES school (id) ON DELETE CASCADE
);

insert into school (id, name) values(1, 'school');
insert into student (id, name, school_id) values(1, 'student', 1);

select stu.* from student stu
 join school sch on stu.school_id = sch.id
 where stu.name = 'student'
 limit 1;
```

- What did you expect to see?
```
+----+---------+-----------+
| id |  name   | school_id |
+----+---------+-----------+
|  1 | student |         1 |
+----+---------+-----------+
(1 row)

```

- What did you see instead?
```
+----+------+-----------+
| id | name | school_id |
+----+------+-----------+
+----+------+-----------+
(0 rows)

```
- What was the impact?
The wrong data is returned.  If we change the limit to 2, the query returns a single row.

We are actively developing against 2.1 beta, it would be good to get this fixed in an upcoming beta.

**Comment by jordanlewis** [comment]
Hi @damienhollis, 

Thanks for the concise report. We'll look into this right away, sorry for the frustration this must have caused.

**Comment by damienhollis** [comment]
@jordanlewis 

We are still seeing some limit issues in the latest beta (v2.1.0-beta.20181008) - was this issue fixed in that beta.  If so, I will raise another bug as we have found another issue.

**Comment by jordanlewis** [comment]
It will be in the next beta.

**Comment by damienhollis** [comment]
Great, thanks
