### ISSUE TITLE
server: Three ports to rule them all

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#30828]
The vision of using `cmux` to combine all cockroach traffic onto a single port never quite materialized. The HTTP interface has been on a separate port due to performance interactions, but now even if those were resolved we'd probably want to keep it on a separate port so it can use a browser-friendly certificate and other TLS settings. 

More importantly, #30821 has shown that combining GRPC and pgwire on the same port is an unnecessary risk. The GRPC interface is only used internally (with a few exceptions for some CLI commands), and the pgwire interface is only used by clients. If these were separate ports, they could have separate firewall rules to provide an extra layer of defense against a bug in the GRPC layer. This is especially important in a hosted environment where the pgwire port may be exposed relatively broadly. 

We should add `crdb_internal` SQL functions for any remaining RPCs that are used by the CLI so that it only interacts with the server over the pgwire protocol. Then we can add an option to run GRPC and pgwire on two separate ports (with the web interface on a third port). We'll still need to support the combined pgwire/grpc port for backwards compatibility, but this will give operators who want it the ability to firewall off the inter-node grpc traffic.

cc @mberhault

**Comment by keith-mcclellan** [comment]
This is something that's being requested by at least one customer.  Ideally, this will allow them to use a different TLS config for SQL connections where they want to host a cluster cert.

**Comment by petermattis** [comment]
@bdarnell Are you working on this?

**Comment by bdarnell** [comment]
No, I'm not working on it.

**Comment by petermattis** [comment]
> We should add crdb_internal SQL functions for any remaining RPCs that are used by the CLI so that it only interacts with the server over the pgwire protocol.

I believe this is by far the largest piece of work here. We use the GRPC interface for decommissioning, quitting, bootstrapping, and various debug requests. I'm not clear on why moving these requests over to a SQL interface would be necessary. I'm probably missing something obvious. Can you elaborate?

**Comment by bdarnell** [comment]
The idea is that in MSO, we'd disallow end-user access to the GRPC port completely. Users would only be able to access the SQL and web interfaces. Of course, in MSO we'd also want to disallow many of the operations that are currently grpc-only (decommissioning, quitting, etc), so maybe we don't actually need to move everything over. I'm not sure what's left on the GRPC port that really needs moving over to the SQL or HTTP ports.

**Comment by petermattis** [comment]
> I'm not sure what's left on the GRPC port that really needs moving over to the SQL or HTTP ports.

Leaving the admin commands alone (decommissioning, bootstrapping, quitting, haproxy), I think the remaining items are debug related: `debug gossip-values`, `debug tsdump`, `debug zip`. I suspect those could be left alone.

Did you have any thoughts about the UX behind specifying an additional port? `--port` should specify the pgwire port. We could then add a `--grpc-port`. How to specify that `--port` should be pgwire only? How to specify the certs to use?

**Comment by bdarnell** [comment]
Yeah, I was thinking we'd add `--grpc-port`, but hadn't gotten much beyond that (I guess you'd also use the grpc ports in the `--join` flag?). The certs would be handled by naming conventions in the certs-dir (for which we already have precedent as we have a number of different variations already).

**Comment by knz** [comment]
IMHO the existing `--port` flag (really, `--listen-addr`, as `--port` has been deprecated since 19.1) should remain dedicated to gRPC.

Then we'd have `--sql-port` (or `--listen-addr-sql` or similar) to split SQL away. If `--sql-port` is not specified, its value would default to that of `--port`.

As to the RPC endpoints. My proposal would be to keep them defined as RPCs in protobufs (and leave them reachable via RPC) and auto-generate SQL built-in functions for all of them, as well as go wrapper functions that would translate a call into a SQL call, given a sql connection.
