### ISSUE TITLE
sql: display newest jobs first in SHOW JOBS output

### ISSUE THREAD

**Issue by rolandcrosby** [cockroachdb/cockroach#30835]
According to @benesch, the output of `SHOW JOBS` is currently displayed in some arbitrary non-chronological order. This should be updated to display in reverse chronological order (i.e. `ORDER BY created DESC`).

**Comment by a-robinson** [comment]
Just a suggestion - we might first want to sort by whether it's completed and then by start time, so that ongoing jobs are always listed at the top. Perhaps the resulting changes in order as jobs finish would be confusing, though.
