### ISSUE TITLE
sql: Provide CREATE TABLE ... LIKE syntax 

### ISSUE THREAD

**Issue by rkruze** [cockroachdb/cockroach#30840]
The functionality desired would be something similar to MySQL's CREATE TABLE ... LIKE functionality. Which is described here: https://dev.mysql.com/doc/refman/5.5/en/create-table-like.html

In Cockroach today the closet you get is a CREATE TABLE AS SELECT * ... LIMIT 0. However, this approach doesn't automatically create any indices that the original table might have had.

**Comment by knz** [comment]
@rkruze what prevents you from issuing `SHOW CREATE ...` and then copy-pasting the result of that command?

**Comment by knz** [comment]
Feature also supported in PostgreSQL btw:

https://www.postgresql.org/docs/10/static/sql-createtable.html

**Comment by victorggsimida** [comment]
@knz 

does cockroach db support sql like this?

below, 

" create table mplist (like template.mplist);
invalid syntax: statement ignored: syntax error at or near "like"
"

**Comment by knz** [comment]
@victorggsimida thank you for your inquiry. To copy-paste the definition of a table, run this:

```
SHOW CREATE TABLE template.mplist;
```

Then copy-paste the output, change the table name,

then run `CREATE TABLE` as usual.

Thank you

**Comment by victorggsimida** [comment]
## 1. show create table 
```
/template> SHOW CREATE TABLE template.mplist;
        table_name       |        create_statement
+------------------------+---------------------------------+
  template.public.mplist | CREATE TABLE mplist (
                         |     a STRING NULL,
                         |     FAMILY "primary" (a, rowid)
                         | )
(1 row)

Time: 46.604259ms

```

## 2. run create table like again

```
* run it in another schema(h30)

/h30> create table mplist ( like templat.mplist);
invalid syntax: statement ignored: syntax error at or near "like"
DETAIL: source SQL:
create table mplist ( like templat.mplist);
                      ^
HINT: try \h CREATE TABLE


run it in the same schema

template> create table one  ( like mplist);
invalid syntax: statement ignored: syntax error at or near "like"
DETAIL: source SQL:
create table one  ( like mplist);
                    ^
HINT: try \h CREATE TABLE


both command fail
