### ISSUE TITLE
cli: stop table formatter printing trailing whitespace

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/cockroach#30856]
> **Is your feature request related to a problem? Please describe.**

The default table formatter prints trailing whitespace that makes git show big red blocks in diffs.  I sometimes edit the trailing whitespace out by hand since they are rather visually distracting. (Screenshot below.)

> **Describe the solution you'd like**

I would like tables to be printed with no trailing whitespace if at all possible please.

> **Describe alternatives you've considered**

There is editor tooling that can remove whitespace, and git can be configured to do some similar things [according to this SO page](https://stackoverflow.com/questions/591923/make-git-automatically-remove-trailing-whitespace-before-committing).  However trailing whitespace also means "insert a break tag" in [Markdown](https://daringfireball.net/projects/markdown/syntax), so it's not entirely straightforward.  I could also add an Emacs macro to try to deal with this, but it will be fragile (and other docs team diffs will still have this issue).

> **Additional context**

I believe this would be alleviated by the table formatting option described in #30851.

A screenshot of a recent git diff for context is below.

![screenshot 2018-10-01 16 33 27](https://user-images.githubusercontent.com/1312291/46314495-ba885d80-c598-11e8-9dc1-eef883718d2d.png)

**Comment by jordanlewis** [comment]
+1, this is really irritating to me as well.

**Comment by knz** [comment]
In the meantime you can do `M-x whitespace-cleanup` in emacs, or even `(add-hook 'before-save-hook 'whitespace-cleanup)` for auto-cleanup on save.

**Comment by knz** [comment]
The upstream table formatter has an option to fix this now.

**Comment by knz** [comment]
Fixing this in https://github.com/olekukonko/tablewriter/pull/148

**Comment by olekukonko** [comment]
@knz sorry for just seeing this.

**Comment by knz** [comment]
@olekukonko we have forked tablewriter to adopt thie change at https://github.com/olekukonko/tablewriter/pull/148

If you merge this PR we'd be glad to move back to your main tree.
