### ISSUE TITLE
sql: support object owners

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#30875]
PostgreSQL supports the OWNER keyword in CREATE DATABASE / VIEW / TABLE etc.

The owner receives permission to modify the object.

This is needed for 3rd party compatibility.

**Comment by solongordon** [comment]
This apparently came up when someone tried to use the Terraform Postgres Provider with CRDB. It failed because it attempted to run `CREATE DATABASE ... WITH OWNER`.

**Comment by RichardJCai** [comment]
Some questions that came out of the features shop talk

- What should we do with existing objects that don't have owners?
- Postgres doesn't allow dropping roles that own objects (or that have permissions on objects but we already allow this) should we also disallow dropping roles that have objects? 
     - Considering we already have ownerless tables and this is how our existing privileges behave, it could make sense to simply remove ownership from objects that a dropped role owns
     - Probably a point for @awoods187 
- Currently for dbs/table, CREATE privilege is essentially pseudo ownership right now, it will be difficult to remove CREATE completely, we would have to assign a user as an owner, if we assign `root` and remove CREATE privilege, users could potentially lose privileges. We could do something like creating a new role as the owner and granting all users that have CREATE to the role, although it is unclear how we would perform this migration.
    - it is likely that we'll have to keep CREATE around, but we can deprecate GRANTing CREATE.

@cockroachdb/sql-features @knz

Not sure who else to tag

**Comment by knz** [comment]
> What should we do with existing objects that don't have owners?

Make `admin` their owner.

> Postgres doesn't allow dropping roles that own objects (or that have permissions on objects but we already allow this) should we also disallow dropping roles that have objects?

I'd say yes. I hope DROP ROLE CASCADE will also work and do what's expected.

>  Considering we already have ownerless tables and this is how our existing privileges behave, it could make sense to simply remove ownership from objects that a dropped role owns

I'd introduce a cluster setting "role for orphan objects" and re-own to that.

> Currently for dbs/table, CREATE privilege is essentially pseudo ownership right now, it will be difficult to remove CREATE completely, we would have to assign a user as an owner, if we assign root and remove CREATE privilege, users could potentially lose privileges. We could do something like creating a new role as the owner and granting all users that have CREATE to the role, although it is unclear how we would perform this migration.

I'm not sure what the best outcome is, but whatever you choose don't use `root`. At worst, choose `admin`; if you need some arbitrary role name, make it a cluster setting (see above).

> it is likely that we'll have to keep CREATE around, but we can deprecate GRANTing CREATE.

Yes sounds like a good first step.

**Comment by RichardJCai** [comment]
> > Postgres doesn't allow dropping roles that own objects (or that have permissions on objects but we already allow this) should we also disallow dropping roles that have objects?
> 
> I'd say yes. I hope DROP ROLE CASCADE will also work and do what's expected.
> 

Interesting that there doesn't actually seem to be a `DROP ROLE CASCADE` in PG, although there is a `REASSIGN OWNED BY`

https://stackoverflow.com/questions/3023583/postgresql-how-to-quickly-drop-a-user-with-existing-privileges
https://www.postgresql.org/docs/current/sql-droprole.html

**Comment by knz** [comment]
> Interesting that there doesn't actually seem to be a DROP ROLE CASCADE in PG

Might be a worthwhile crdb extension, especially if there's no way otherwise to automate this.

**Comment by RichardJCai** [comment]
Closed by https://github.com/cockroachdb/cockroach/pull/51856
