### ISSUE TITLE
sql: authentication failure message should be the same when user does not exist and password does not match.

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#30879]
Password authentication can fail in two ways:
* use does not exist
* password is incorrect

We currently return different error messages (`user foo does not exist` vs `invalid password`). This allows anyone to determine whether a user exists in the cluster or not. We should make this harder by making the message the same. Something along the lines of: `password authentication failed for user foo`).

CC: @vivekmenezes for triage.

**Comment by knz** [comment]
@mjibson do you reckon you could have a look at this? if not I can take it
