### ISSUE TITLE
status: _status/range/x useless on broken cluster

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#30874]
On a cluster reproducing #30832, `/_status/range/1` results in the following output:

```
{
  "error": "all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: failed to write client preface: io: read/write on closed pipe\"",
  "code": 14
}
```

All nodes are live, and even if they weren't, "read/write on closed pipe" looks unlike any error expected in that setting.

We should do a better job at making sure the debug commands work when clusters are unavailable.

**Comment by knz** [comment]
This may be related to #41162.

**Comment by knz** [comment]
Folding into #42828 which has the root cause.
