### ISSUE TITLE
rsg: drop database timeout

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#30893]
TestRandomSyntaxSchemaChangeDatabase:

```
SELECT 1 executed successfully: probably a slow statement
timeout: "DROP DATABASE error". currently executing: map[DROP DATABASE error:1]
panic: statement exec timeout
```

Maybe two database drops locking each other? Current exec time in teamcity is 30s, which is pretty long.

**Comment by vivekmenezes** [comment]
I don't know what to make of this. Have we seen this again?

**Comment by mjibson** [comment]
It's been a while since I've seen this. But it used to happen 2x/month. Unsure if it has stopped or just not happened again.

**Comment by lucy-zhang** [comment]
I'm closing this due to apparent lack of activity but feel free to reopen if it happens again.
