### ISSUE TITLE
Docker image fails on some machines with an Illegal Instruction

### ISSUE THREAD

**Issue by spullara** [cockroachdb/cockroach#309]
Running this on an Macbook Air 11" with an i7 worked fine. Running it on a 2014 Mac Pro caused the error below. Possibly an issue with cgo compilation where gcc optimizes it for the local environment?

$ docker run -p 8080:8080 "cockroachdb/cockroach"     init -rpc="localhost:0"     -certs="resources/test_certs"     -stores="ssd=/tmp/db"
I0209 00:13:49.137376      11 server.go:278] Initialized 1 storage engine(s)
SIGILL: illegal instruction
PC=0x9df705
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall_errno(0x508cc0, 0xc2080e1740, 0x0)
	/usr/src/go/src/runtime/cgocall.go:130 +0xf5 fp=0xc2080e1720 sp=0xc2080e16f8
github.com/cockroachdb/cockroach/storage/engine._Cfunc_DBOpen(0xc20800a9b0, 0xc20802b2d8, 0x7, 0x40000000, 0x1, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/engine/:159 +0x63 fp=0xc2080e1740 sp=0xc2080e1720
github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Start(0xc20800a9b0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:81 +0x1af fp=0xc2080e1888 sp=0xc2080e1740
github.com/cockroachdb/cockroach/storage.(*Store).Bootstrap(0xc208082700, 0xc20805c420, 0x24, 0x100000001, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:457 +0x77 fp=0xc2080e1a10 sp=0xc2080e1888
github.com/cockroachdb/cockroach/server.BootstrapCluster(0xc20805c420, 0x24, 0x7ffb55a698b0, 0xc20800a9b0, 0x1, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/server/node.go:127 +0x54e fp=0xc2080e1be0 sp=0xc2080e1a10
github.com/cockroachdb/cockroach/server.runInit(0x12f0d80, 0xc20800a040, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/server/server.go:160 +0x3a5 fp=0xc2080e1cd8 sp=0xc2080e1be0
code.google.com/p/go-commander.(*Commander).Run(0xc20805ca80, 0xc20800a040, 0x0, 0x0, 0x0, 0x0)
	/go/src/code.google.com/p/go-commander/commands.go:75 +0x776 fp=0xc2080e1e30 sp=0xc2080e1cd8
main.main()
	/go/src/github.com/cockroachdb/cockroach/main.go:87 +0x4f3 fp=0xc2080e1f98 sp=0xc2080e1e30
runtime.main()
	/usr/src/go/src/runtime/proc.go:63 +0xf3 fp=0xc2080e1fe0 sp=0xc2080e1f98
runtime.goexit()
	/usr/src/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2080e1fe8 sp=0xc2080e1fe0

goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x1310360)
	/go/src/github.com/golang/glog/glog.go:879 +0x78
created by github.com/golang/glog.init·1
	/go/src/github.com/golang/glog/glog.go:410 +0x2a7

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/src/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 7 [syscall]:
os/signal.loop()
	/usr/src/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/src/go/src/os/signal/signal_unix.go:27 +0x35

rax     0x19
rbx     0x7fffa7422370
rcx     0x23dcbac
rdx     0x23e25fc
rdi     0x18
rsi     0x1
rbp     0x7fffa7422230
rsp     0x7fffa7422200
r8      0x23e25e4
r9      0x23de020
r10     0x7fffa74224d0
r11     0x7ffb55635890
r12     0x7fffa74227e0
r13     0x23dcbac
r14     0x7fffa74227e0
r15     0x9
rip     0x9df705
rflags  0x10206
cs      0x33
fs      0x0
gs      0x0

**Comment by spullara** [comment]
Here was a reference to something similar happening:

http://michael.stapelberg.de/Artikel/sigill_golang/

**Comment by spencerkimball** [comment]
Could be a bug in roachlib/db.cc. That would be my guess. The outward
evidence of those bugs often looks like what you're seeing. Is this just
running at HEAD?

**Comment by spullara** [comment]
I believe that it downloaded the latest image from docker and ran that. I did a successful:

make clean && make build && make test && docker build .

on master and got a different error when I tried to run it. Could there be an environmental issue associated with the storage engine?

$ docker run -p 8080:8080 06678277f516 init -rpc="localhost:0"     -certs="resources/test_certs"     -stores="ssd=/tmp/db"
I0209 02:10:00.020484       8 server.go:278] Initialized 1 storage engine(s)
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x40000008 pc=0x930b7f]

runtime stack:
runtime.gothrow(0xde8570, 0x2a)
	/usr/src/go/src/runtime/panic.go:503 +0x8e
runtime.sigpanic()
	/usr/src/go/src/runtime/sigpanic_unix.go:14 +0x5e

goroutine 1 [syscall, locked to thread]:
runtime.cgocall_errno(0x4fc1d0, 0xc2080d9740, 0x0)
	/usr/src/go/src/runtime/cgocall.go:130 +0xf5 fp=0xc2080d9720 sp=0xc2080d96f8
github.com/cockroachdb/cockroach/storage/engine._Cfunc_DBOpen(0xc20800abe0, 0xc20802ace8, 0x7, 0x40000000, 0x1, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/engine/:159 +0x63 fp=0xc2080d9740 sp=0xc2080d9720
github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Start(0xc20800abe0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:81 +0x1af fp=0xc2080d9888 sp=0xc2080d9740
github.com/cockroachdb/cockroach/storage.(*Store).Bootstrap(0xc20800c800, 0xc20803dbf0, 0x24, 0x100000001, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:457 +0x77 fp=0xc2080d9a10 sp=0xc2080d9888
github.com/cockroachdb/cockroach/server.BootstrapCluster(0xc20803dbf0, 0x24, 0x7f66375298a0, 0xc20800abe0, 0x1, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/server/node.go:127 +0x54e fp=0xc2080d9be0 sp=0xc2080d9a10
github.com/cockroachdb/cockroach/server.runInit(0x12b8940, 0xc20800a040, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/server/server.go:160 +0x3a5 fp=0xc2080d9cd8 sp=0xc2080d9be0
code.google.com/p/go-commander.(*Commander).Run(0xc20805aa80, 0xc20800a040, 0x0, 0x0, 0x0, 0x0)
	/go/src/code.google.com/p/go-commander/commands.go:75 +0x776 fp=0xc2080d9e30 sp=0xc2080d9cd8
main.main()
	/go/src/github.com/cockroachdb/cockroach/main.go:87 +0x4f3 fp=0xc2080d9f98 sp=0xc2080d9e30
runtime.main()
	/usr/src/go/src/runtime/proc.go:63 +0xf3 fp=0xc2080d9fe0 sp=0xc2080d9f98
runtime.goexit()
	/usr/src/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2080d9fe8 sp=0xc2080d9fe0

goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x12d7f40)
	/go/src/github.com/golang/glog/glog.go:879 +0x78
created by github.com/golang/glog.init·1
	/go/src/github.com/golang/glog/glog.go:410 +0x2a7

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/src/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 7 [syscall]:
os/signal.loop()
	/usr/src/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/src/go/src/os/signal/signal_unix.go:27 +0x35

**Comment by tschottdorf** [comment]
I don't think it has to do with Docker. I just got the same thing running `make test` on my feature branch, without Docker, on my x86_64:

https://gist.github.com/tschottdorf/20bdc7b34424bf4b7991

It's due to this commit:
```
commit 0df7759c6b4eb46ac9ac3d809af6c1d8c55e8fa1
Author: Peter Mattis <pmattis@squareup.com>
Date:   Wed Feb 4 11:08:56 2015 -0500

    Bump rocksdb pointer.
```

so I'm assigning Pete to take a look.

**Comment by cockroach-team** [comment]
Both "make test" and "make acceptance" are working for me on head. But I'm
also seeing this error when running the docker command Sam originally
provided. Let me figure out what is going on.

**Comment by tschottdorf** [comment]
I've actually gotten it to run after a manual `make clean` in rocksdb. Looks like something's being cached again.......

**Comment by cockroach-team** [comment]
To me it looks like the "cockroachdb/cockroach" image in the docker hub is
bad. Building it locally (using build/build-docker-deploy.sh) works fine.
Isn't the "cockroachdb/cockroach" image supposed to be rebuilt by circleci?

We should see about baking the git sha used to build cockroach into the
docker images.

**Comment by tschottdorf** [comment]
it's built by CircleCI. Since I've managed locally to end up with something broken outside of Docker, it's not surprising that the Docker image too had this issue.
Shouldn't your SHA-baking have taken care of this? Likely the relevant build is this one: https://circleci.com/gh/cockroachdb/cockroach/423

Did you already bake sha's by then?

**Comment by cockroach-team** [comment]
I thought the SHA-baking should take care of this. Looking at the logs I
see:

Step 16 : RUN cd $ROCKSDBPATH && git clone
https://github.com/cockroachdb/rocksdb.git &&  cd $ROCKSDBPATH/rocksdb &&
git checkout 853b545bc2572893ef046168f904f558bfd84371 &&  cd $COREOSPATH &&
git clone https://github.com/cockroachdb/etcd.git &&  cd $COREOSPATH/etcd
&& git checkout dd2a46364154ddc80d325c43af690c2af12a732b


So it looks like that layer and subsequent layers should have been
dependent on the rocksdb SHA.

**Comment by tschottdorf** [comment]
Yes, the cache was definitely busted at that step. But that doesn't run `make clean` on the contents of RocksDB so it didn't save us. What we need is, in that line, a `make clean` after the checkout. Something like:

```
RUN \
 cd $ROCKSDBPATH && git clone https://github.com/cockroachdb/rocksdb.git && \
 cd $ROCKSDBPATH/rocksdb && git checkout ROCKSDB_SHA && make clean \
 cd $COREOSPATH && git clone https://github.com/cockroachdb/etcd.git && \
 cd $COREOSPATH/etcd && git checkout ETCD_SHA
```

**Comment by petermattis** [comment]
The theory of operation was that we're cloning rocksdb fresh (the prior
layer does not contain rocksdb) so the "make clean" isn't necessary. Am I
missing something?

**Comment by tschottdorf** [comment]
no, I wasn't looking at it close enough -- my bad. The only thing I can think of now is that we accidentally add some old stuff back in in the Dockerfile in the root repo - pkg directories or something? Sounds weird though.

**Comment by spullara** [comment]
The latest version just worked for me:

```
$ docker run -p 8080:8080 "cockroachdb/cockroach" init -rpc="localhost:0" -certs="resources/test_certs" -stores="ssd=/tmp/db"
Unable to find image 'cockroachdb/cockroach:latest' locally
Pulling repository cockroachdb/cockroach
bd090435ef38: Download complete 
511136ea3c5a: Download complete 
8771fbfe935c: Download complete 
0e30e84e9513: Download complete 
84770bc4b8fc: Download complete 
d37a9316f450: Download complete 
836e797fd75c: Download complete 
5f6588ecd014: Download complete 
4a8026e9b118: Download complete 
7e15aefd1be2: Download complete 
5d2b129b5886: Download complete 
Status: Downloaded newer image for cockroachdb/cockroach:latest
I0301 07:05:28.274563       8 context.go:144] Initialized 1 storage engine(s)
```

**Comment by rmorales-iaa** [comment]
Steps to run cockroach 1.0.2. with  Centos 7 using an old CPU 

```
wget https://binaries.cockroachdb.com/cockroach-v1.0.2.src.tgz
tar xvf cockroach-v1.0.2.src.tgz
cd cockroach-v1.0.2.src.tgz

vi src/github.com/cockroachdb/cockroach/c-deps/rocksdb-0013-cmake-msse.patch
#remove the line
#+    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -msse4.2")

make build
```
