### ISSUE TITLE
ui: Node diagnostics page shouldn't truncate localities

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#30905]
**Describe the bug**

The Node Diagnostics page at `/#/reports/nodes` currently truncates localities that don't fit in the column, which is pretty much all localities with more than one kv pair. You can grab a bit more of them from the "Arguments" row of the table, but that also gets truncated, just slightly further along.

One of the things I most commonly want to see on this page is node localities, and when I'm looking directly at the page I can hover over the columns to get the details, but that's not an option in screenshots sent in by users. Ensuring it doesn't get cut off would be a big improvement.

Examples:

<img width="198" alt="screen shot 2018-10-02 at 5 28 41 pm" src="https://user-images.githubusercontent.com/7085343/46380734-09052d00-c669-11e8-92f9-25897ca07fd0.png">
<img width="248" alt="screen shot 2018-10-02 at 5 30 08 pm" src="https://user-images.githubusercontent.com/7085343/46380732-09052d00-c669-11e8-8354-40131975f51f.png">

**To Reproduce**

1. Set up CockroachDB cluster with some locality kv pairs on each node
2. Load the /#/reports/nodes page of the UI

---

Also, I'm not really sure what's up with the seeing-double header text in the PDF screen grabs (originally reported in our private support repo).

**Comment by knz** [comment]
cc @couchand

**Comment by couchand** [comment]
That is painful and we should clean it up.

As a workaround, you can hover over the cell and see the full text in a tooltip.

**Comment by vilterp** [comment]
Longer-term, we should think about addressing this situation by

- surfacing locality info on the node list with a TreeTable (@josueeee's design [here](https://www.figma.com/file/WzhvMEGkuDi8Wd7va0vgHHiG/Hardware-Metrics?node-id=0%3A1))
![image](https://user-images.githubusercontent.com/7341/46452988-cb89c800-c76c-11e8-823c-c6cc26af1e24.png)
- getting the other info on the node diagnostics page into the main node details page
