### ISSUE TITLE
sql: Using "ANY" in WHERE clause results in poor query plans

### ISSUE THREAD

**Issue by jezell** [cockroachdb/cockroach#30910]
**What is your situation?**

Have an index with three columns. If where clause contains 

WHERE col = ANY ARRAY['a','b'] 

Then the query plan throws away knowledge of a & b 

If the query is rewritten as 

WHERE (col = 'a' OR col = 'b')

Then the query planner uses the knowledge of the values to scan a much smaller range

These two variations should result in the same plan.

**Comment by andy-kimball** [comment]
This should have been fixed in our 19.1 release.
