### ISSUE TITLE
sql: crdb_internal.ranges.replicas should reference nodeIDs, not storeIDs

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#30940]
`crdb_internal.ranges`, `crdb_internal.ranges_no_leases` , and `SHOW RANGES` all have a `replicas` column which includes an array of IDs. Currently, we include the `StoreID` of each of the replicas in this array. I found this very surprising and believe that users will too. My expectation was that this `replicas` column would store the `NodeID` of each of the replicas. These two IDs are roughly correlated, but they do not need to line up.

I think we should make the change, but also understand that there are reason why we shouldn't. Here's an incomplete argument for and against it:

Pros:
- users are more familiar with NodeIDs than with StoreIDs. I don't see a single place outside of the debug pages in the AdminUI that discusses StoreIDs. Meanwhile, node IDs are referenced all over the place
- the `crdb_internal` schema references `NodeID` significantly more often than it references `StoreID` (13x vs 3x)
- These are the best introspection methods available to view the effect of a table partitioning (until the replica matrix). I suspect that it's very common for users to cross-reference the replicas in their partitioned tables with their node list to verify that data is in the correct location. To do so, they currently need to map the replicas to their stores, and then the stores to their nodes. Doing so is bad enough, but it's also unclear and easy to mess up because the column isn't named something like `replica_store_ids`

Cons:
- storeIDs are both more specific and map more directly to how the allocator makes decisions. A counter argument to this is that we never allow multiple replicas for the same range on the same node, even if it has multiple stores
- making this change (if we want to) would be changing existing behavior, so we'd need to be deliberate about doing it

A compromise might be to replace the `replicas` column with two new columns: `replica_nodes` and `replica_stores`. Or we could change `replicas` to `replica_stores`/`replica_store_ids` without adding the other column. My only strong feeling is that we don't leave things the way they are.

cc. @knz for triage. Also cc. @vilterp since this is related to the replica matrix.

**Comment by vilterp** [comment]
Yeah, at a bare minimum it would be nice to call it `replica_store_ids` or something. I was pretty confused about what those numbers were when I first looked at the contents of this table; expected them to be node ids.

**Comment by petermattis** [comment]
This was just reported as https://github.com/cockroachdb/cockroach/issues/43699.

I wonder if store IDs and node IDs should allocate from the same ID range. That would eliminate bugs that accidentally conflate one ID for the other. Well, it wouldn't eliminate them, but it would reveal such bugs as a given store ID wouldn't also be a valid node ID.

**Comment by asubiotto** [comment]
#44312 claims to fix this issue
