### ISSUE TITLE
sql/kv: tableReader should scan ranges in parallel

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#30943]
`tableReader` use of `txnKVFetcher` currently always sets a `MaxSpanRequestKeys`. This is true whether the `tableReader` is performing point lookups, bounded scans, or unbounded scans. When this field is set, `DistSender` refuses to parallelize requests that go to different ranges. The effect of this is that all SQL scans that don't go through DistSQL are serialized across the ranges that they touch, and SQL scans that go through DistSQL are only parallelized to the degree that the DistSQL processors fan out.

The cause of this is a breakdown between SQL and KV. SQL is conservative in how many rows it wants at any given time to limit instantaneous memory usage. KV (DistSender) is conservative in how it treats BatchRequests with a `MaxSpanRequestKeys` set because it doesn't want to fetch any extra kv pairs than it needs to. We should rethink this interface and handle this better. We should then audit SQL's uses of `MaxSpanRequestKeys` and make sure it's doing reasonable things for different use cases given the extra context it has about the operations it's performing.

One extreme alternative on the `DistSender` side of things is to parallelize requests across all ranges and give each of them the same `MaxSpanRequestKeys` limit. It could then strip out any extra kv pairs once it gets all the responses. A somewhat saner alternative is for `DistSender` to adaptively increase its parallelism as previous iterations fail to exceed its key limit. This would reduce the complexity of this operations from linear to logarithmic. The best choice here will be dictated by SQL and the amount of information it can provide.

This is a serious performance issue and came as a surprise to at least me and @drewdeally (because I kept assuring him we parallized SQL scans), and probably others. As a motivating case for why we need to parallelize these scans, consider the following query from TPC-C:
```
SELECT i_price, i_name, i_data FROM tpcc.item WHERE i_id IN (7023, 17231, 23391, 33519, 50158, 62789, 65389, 72347, 73481, 81149, 86958, 96838) ORDER BY i_id
```
The `item` table can't be easily partitioned, so in a distributed cluster it's not unreasonable for the gateway<->leaseholder latency for these items to average around 100ms. Currently, we perform each of these lookups, one after the other. The query alone adds more than a second on to the `newOrder` transaction and accounts for about 80% of its latency in that configuration.

@jordanlewis I'm assigning both of us to triage this problem. I think it's probably stayed under the radar for so long because it straddles teams. Let's ensure that doesn't keep happening.

**Comment by nvanbenschoten** [comment]
It's possible that this helps explain the correlation we see between Range count and throughput in https://github.com/cockroachdb/cockroach/issues/30213. As the Range count grows, certain operations like the query posted above start taking longer because they're split across more ranges. When these queries take longer, txns start taking longer and contention between them grows, exacerbating the whole situation.

**Comment by nvanbenschoten** [comment]
Oh no, we hit this with mutations too! For instance, a query like `DELETE FROM t WHERE k IN ($1, $2, ... $30)`, which is extremely common, will end up serially scanning over all source ranges. In any sufficiently split dataset, we'll perform a separate lookup for every single row we're planning to delete, all serially.

**Comment by jordanlewis** [comment]
Hmm, good point Nathan thanks for noting. Seems like this is becoming higher and higher priority.

**Comment by jordanlewis** [comment]
> Oh no, we hit this with mutations too! For instance, a query like DELETE FROM t WHERE k IN ($1, $2, ... $30), which is extremely common, will end up serially scanning over all source ranges. In any sufficiently split dataset, we'll perform a separate lookup for every single row we're planning to delete, all serially.

Wait, why can't this query issue fast path deletes? I guess there could be secondary indexes or foreign keys to check.

**Comment by nvanbenschoten** [comment]
Yeah, it's because of the secondary indexes.
