### ISSUE TITLE
sql: use descriptor cache for AS OF SYSTEM TIME

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#30967]
Queries with `AS OF SYSTEM TIME` avoid the descriptor cache. This means that even for a very simple point query we have to do a KV op for each query to read the table descriptor. Given that in some cases we have recommended `AS OF SYSTEM TIME` to users to speed up certain workloads, we should fix this.

Here's an idea:
 - keep a timestamp interval, such that reading the descriptor at any timestamp in this interval would return the same version
 - initially, the timestamp interval only contains the timestamp at which we read the descriptor
 - when we get an `AS OF SYSTEM TIME` query, if the timestamp is not within the known interval, then we re-read. After that, we compare the result against the descriptor in the cache; if they are the same version, we extend the known interval to contain the AOST timestamp.

**Comment by RaduBerinde** [comment]
CC @mjibson @knz

**Comment by andreimatei** [comment]
There (should be) no good reason for the desc cache to be avoided for AOST. Both the overall design, and the `LeaseManager` code support maintaining descriptor histories. A descriptor's "validity window" is well defined, and known; there's no need for reading and comparing against the cache and then extending some cache entry.
I'm not sure about the reason why we currently don't use this cache, but I'm pretty sure @vivekmenezes promised to fix this :P

**Comment by vivekmenezes** [comment]
I believe the complication here were issues around name to id mapping and how that might change across a TRUNCATE. I forget exactly, but if we need to make a compromise we can at least allow AOST queries to use the latest version of the descriptor if it is valid for the AOST.
