### ISSUE TITLE
workload/ycsb: add support for uniform load distribution

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#30996]
`workload/ycsb` currently only supports the `zipfian` load distribution. https://github.com/brianfrankcooper/YCSB supports three load distributions: uniform, zipfian and latest. Uniform is the default. 

We should add support for the uniform load distribution to YCSB and a `--request-distribution` flag. The flag should default to `uniform`, like in the real YCSB.

Resources that may be helpful:
- [UniformGenerator.java](https://github.com/brianfrankcooper/YCSB/blob/master/core/src/main/java/com/yahoo/ycsb/generator/UniformGenerator.java)
- [ZipfianGenerator.java](https://github.com/brianfrankcooper/YCSB/blob/master/core/src/main/java/com/yahoo/ycsb/generator/ZipfianGenerator.java)

@m-schneider would you be interested in looking into this?

**Comment by m-schneider** [comment]
Sure!
