### ISSUE TITLE
Busy loop while one range got bunch of requests

### ISSUE THREAD

**Issue by veteranlu** [cockroachdb/cockroach#3101]
I got following log while I run stress test:
>
W1029 15:15:12.827316 26132 rpc/dm_sendtostore.go:223  range 5: performance log 2:send to {9 50 []} rpc timeout method Node.Scan: timeout
I1029 15:15:12.828011 26132 kv/dist_sender.go:822  range 5: performance log 12:distsender retry, err:replica 8:45 not leader; leader is 9:50
W1029 15:15:12.835464 26132 rpc/dm_sendtostore.go:223  range 5: performance log 2:send to {9 50 []} rpc timeout method Node.Scan: timeout
I1029 15:15:12.835808 26132 kv/dist_sender.go:822  range 5: performance log 12:distsender retry, err:replica 8:45 not leader; leader is 9:50
W1029 15:15:12.878494 26132 rpc/dm_sendtostore.go:223  range 5: performance log 2:send to {9 50 []} rpc timeout method Node.Scan: timeout
I1029 15:15:12.878920 26132 kv/dist_sender.go:822  range 5: performance log 12:distsender retry, err:replica 8:45 not leader; leader is 9:50
W1029 15:15:12.891669 26132 rpc/dm_sendtostore.go:223  range 5: performance log 2:send to {9 50 []} rpc timeout method Node.Scan: timeout
I1029 15:15:12.892091 26132 kv/dist_sender.go:822  range 5: performance log 12:distsender retry, err:replica 8:45 not leader; leader is 9:50
W1029 15:15:12.975638 26132 rpc/dm_sendtostore.go:223  range 5: performance log 2:send to {9 50 []} rpc timeout method Node.Scan: timeout
I1029 15:15:12.976018 26132 kv/dist_sender.go:822  range 5: performance log 12:distsender retry, err:replica 8:45 not leader; leader is 9:50
W1029 15:15:12.976829 26132 rpc/dm_sendtostore.go:223  range 5: performance log 2:send to {9 50 []} rpc timeout method Node.Scan: timeout
I1029 15:15:12.977135 26132 kv/dist_sender.go:822  range 5: performance log 12:distsender retry, err:replica 8:45 not leader; leader is 9:50

the scene description as follow:
* One range has 3 replica, e.g. replica A, B, C
* while replica-A is the leader hold, all request sent to replica-A by CN(txnCoorSender)
*  If replica-A has a large number of request, it cann't reply to CN within 500 ms.
* CN sends the request to replica-B instead of replica-A
* But replica-B return `NotLeaderError` to CN, and told CN replica-A is the rangeleader, since replica-A is the Leader Hold
* CN sends the request to replica-A again, then replica-A get more request, loop to the first step.

**Comment by tschottdorf** [comment]
what is the `500ms` timeout you are mentioning? Are you running a (very old) code base by any chance? This seems like a duplicate of #2962. We're not at the stage of doing detailed flow control of requests yet, so such problems are expected when you run with very aggressive retry options.

**Comment by veteranlu** [comment]
the timeout which I talk about is `defaultSendNextTimeout`,  has been changed to 10 seconds, I will test it with the latest version, and figure out if I can reproduce this issue.

**Comment by veteranlu** [comment]
@tschottdorf I cannot reproduce the issue after changing `defaultSendNextTimeout` to 10 seconds.
