### ISSUE TITLE
Secondary Index Performance overhead is high with Sysbench Tests

### ISSUE THREAD

**Issue by drewdeally** [cockroachdb/cockroach#31018]
**Describe the problem**
Problem:  Secondary Index Performance overhead is higher than expected with sysbench.  
QPS is more than 1/2 for a prolonged tests > 600s.

**To Reproduce**

Refer to DOC https://docs.google.com/document/d/1-DHl44sy9i6fWHv2eq3zBUxWz0DfZbrup3T6Xs658nI/

What did you do? Ran Sysbench harness with a few configurations changes, with and without index on sbtest1.  Found the Index overhead was more than a 2X reduction in QPS.  In the above document you will find the details of the test and system metrics. 

Review the chart below
using no indexes as the baseline to compare

![image](https://user-images.githubusercontent.com/39496073/46551175-0abb3480-c8a5-11e8-9367-cf44709421ca.png)

If possible, provide steps to reproduce the behavior:

Setup a 4 node roachprod cluster 
n1-highcpu-8 
SSD 
installed Sysbench

- curl -s https://packagecloud.io/install/repositories/akopytov/sysbench/script.deb.sh | sudo bash
- sudo apt -y install sysbench
- sudo apt -y install make automake libtool pkg-config libaio-dev libmysqlclient-dev libssl-dev libpq-dev
- sudo apt -y install haproxy

More details in https://docs.google.com/document/d/1-DHl44sy9i6fWHv2eq3zBUxWz0DfZbrup3T6Xs658nI/

**Comment by nvanbenschoten** [comment]
Thanks for filing @drewdeally! Performance of secondary index writes is something we're aware of and actively thinking about. The measurements you took line up with other experimental results we've seen.

**Comment by nvanbenschoten** [comment]
Closing this, as we've made significant strides to reduce the impact of secondary indexes on insert throughput. These improvements include batching txn record GC, batching intent resolution, and parallel commits. We'll continue to improve along this dimension going forward.
