### ISSUE TITLE
sql,kv,storage: Deferred writes

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#31055]
This is a proto-RFC for a feature I've been thinking about.

## Goal

The goal is to improve write latency at the expense of throughput and some aspects of consistency. The benefits would be most significant for tables with secondary indexes or for geo-distributed workloads

## Background

This is related to the "Message Queues" concept which was present in the original cockroach design doc but removed in #1968. 

We currently recognize that certain SQL operations (namely `UPSERT ... RETURNING NOTHING` on a table with no secondary indexes) can be performed as "blind writes" without performing any reads. For the purposes of this document, we call those "KV blind writes" and introduce the concept of "SQL blind writes", which are slightly broader. A SQL blind write may need to perform KV reads to maintain secondary index consistency but cannot fail and need not return anything to the client. (SQL blind writes that are not KV blind writes include `UPSERT RETURNING NOTHING` with secondary indexes, and `INSERT ON CONFLICT DO NOTHING RETURNING NOTHING`).

## Overview

From a user perspective: A to-be-determined SQL extension allows some SQL blind writes to be *deferred*. Deferred writes would return to the client after performing a single KV write (to a key that could be geo-partitioned to be within the local region). After this the server would be responsible for (eventually) applying the deferred write to its true destination. Deferred writes would not guarantee the "read your writes" consistency property. 

From the server perspective: The SQL layer serializes the updates to be performed and writes them to some key (discussed below). Note that for KV blind writes this serialized form could be a `roachpb.BatchRequest`, but for the more general case supporting secondary indexes, we must store SQL tuples and translate them to row updates at processing time so we can perform the correct read-modify-write cycle for secondary indexes. A queue on each node processes these queues for each range and (atomically) performs the writes they describe and deletes the key.

### Key

The key used for the serialized update is crucial since it must be able to be partitioned to the right collection of nodes. One option is to store it in a parallel plane alongside regular data rows (like transaction records are stored today). This would require syntax for specifying the deferred writes in conjunction with a regular key (and perhaps tied to a regular write to that key). 

Alternately, we could perhaps allocate some per-locality keyspace for these keys, and automatically write to the location closest to the SQL gateway. However, this is sensitive to the way localities are configured. We would generally want to stay within-region for this keyspace, but not restrict ourselves to within-rack (deployments could auto-deploy "rack" locality labels that don't contain enough nodes).

### Queue problems

This is a queue-like workload, which is a known weakness of CockroachDB. However, it's specialized enough that countermeasures might be available. For example, the keys might not need to be MVCC, depending on how they interact with regular transactions. They could also have separate GC policies, and maybe even separate rocksdb column families to allow prompt cleanup of old entries.

### Secondary indexes

The presence of secondary indexes currently prevents the use of our fast-path insert optimizations (e.g. #31018). Deferred writes would allow the write to execute with the latency of the fast path with the throughput cost of fast path + slow path. 

If deferred writes were stored adjacent to regular data rows, this opens up a workaround for the lack of read-your-writes: Create two tables, one with secondary indexes and one without. Perform an insert to the unindexed table with an attached deferred write to the indexed table. Then primary key lookups can read from the unindexed table (which guarantees read-your-writes) and only queries by secondary index need to read from the eventually-consistent indexed table. 

### Geo-distribution

In a table that cannot be partitioned effectively, writes must span long distances to achieve quorum. Instead, writes destined for such a table could be deferred and written to a local partition, to be replicated asynchronously to the global table. 

## Drawbacks

Giving up "read your writes" is a significant loss of consistency. How common are use cases that can live with this? Can we provide something like a causality token that would help here? (Note that we can't use HLC timestamps as a causality token since the timestamp of the deferred write is not known. But we might be able to use an ID for the deferred write that could poll to see if it is done yet. A causality token format should be flexible enough to accomodate this use case)

This is a further deviation from standard SQL practice and ORM compatibility, so it will only ever be used by a minority of applications which adopt cockroach-specific features. 

Jira issue: CRDB-4813

**Comment by knz** [comment]
I think this is still relevant
