### ISSUE TITLE
storage: Specifying locality tiers differently on different nodes causes undefined rebalancing behavior

### ISSUE THREAD

**Issue by HassanRubrik** [cockroachdb/cockroach#31084]
**Description**
In function DiversityScore() (pkg/roachpb/metadata.go), the values of the Locality Tiers are compared ignoring the key's content. So if the Localities aren't provided in the correct order while starting the node, we may compare wrong keys with each other.

The comment above the function says:
// All localities are sorted from most global to most local so any localities
// after any differing values are irrelevant.
Do we expect that the user will provide the Localities in the correct order?

**To Reproduce**
1. Please put some log (or some way to print) to show the Tiers Key and Value in function DiversityScore().
2. Now start a cockroach cluster with two nodes with the reverse order of locality:
NodeA is started as :  --locality=region=US,datacenter=us-east
Node B is started as:  --locality=datacenter=us-west,region=US
Then NodeA's locality's tier index 0 will point to <region, US>, while NodeB's locality's tier index 0 will point to <datacenter, us-west>.
3. So func DiversityScore() is comparing region and datacenter value with each other, which may not be correct.

**Expected behavior**
To implement copyset, we need the global StoreList to be sorted according to their diversity. For example, we want the all Stores from <region,US> to be side by side in our sorted list. We were planning to sort it according to the Locality's tiers' key-value pair following the comment above function DiversityScore(). We thought that the keys with the same index are the same for all nodes.

**Comment by a-robinson** [comment]
> Do we expect that the user will provide the Localities in the correct order?

Yes. Essentially, this code relies on all nodes having the same locality tiers in the same order, and that they're ordered from most global to most local such that the most important differences come first.

Behavior is currently undefined if the locality tiers on different nodes are specified in different orders or have different keys. Long ago there were plans to warn the user in the UI/logs if the tiers didn't match up, but I don't think that ever got implemented. On the plus side, at least we're clear about it in the docs (https://www.cockroachlabs.com/docs/v2.0/start-a-node.html#locality, https://www.cockroachlabs.com/docs/v2.0/recommended-production-settings.html#basic-topology-recommendations) and the `cockroach start` help text.

So for now, you should make the same assumption as the rest of the system that the tiers are ordered properly. We should get back around to warning about it, though.

@couchand is a warning about poorly specified localities something that we could add to the UI?

**Comment by HassanRubrik** [comment]
Thank you for the clarification.

**Comment by couchand** [comment]
@a-robinson as you mention we've talked about adding a warning like that, but haven't done anything about it yet.  There is a report on the web UI (`/#/reports/localities`) that shows the inferred locality structure, which will show the error though it doesn't highlight it.  cc @piyush-singh
