### ISSUE TITLE
UI: Service latency appears to exclude DistSQL queries

### ISSUE THREAD

**Issue by tim-o** [cockroachdb/cockroach#31093]
**Describe the problem**

When troubleshooting a user's cluster, @vilterp and I observed that service latency appears to exclude distsql latency.

**To Reproduce**
Compare [internal statement statistics](https://docs.google.com/spreadsheets/d/19Yjg0-2Cu3edtohGrvJQ16QZsRmLPjoRIuDaaU9dJCs/edit?usp=sharing) (CRDB only) to the screenshot below.

![screen shot 2018-10-08 at 2 17 27 pm](https://user-images.githubusercontent.com/38867162/46626716-2cffbd00-cb06-11e8-8bec-96f8165627d6.png)

Note that roughly 1/3 of the queries in the internal_statement_statistics table had latency >1s, yet the sql p99 latency graph shows latency of ~100ms, while the distsql p99 latency shows 10s+.

**Expected behavior**
I'd expect that the Service Latency: SQL 99th percentile graph would average all statements. Instead, it appears to exclude distSQL queries.

**Environment:**
v2.0.6

**Comment by vilterp** [comment]
Note also that the "Overview" dashboard (the "front page") of the time series section of the UI has only the "Service Latency: SQL" graph.

- The "Service Latency: SQL, 99th Percentile" graph is of the metric `cr.node.sql.service.latency-p99`
- The "Service Latency: DistSQL, 99th percentile" graph is of the metric `cr.node.sql.distsql.service.latency-p99`

This is where these metrics are updated: https://github.com/cockroachdb/cockroach/blob/7dcdcd25cbb888857d7c3ba7956a45cff61d8e40/pkg/sql/executor_statement_metrics.go#L144-L148

We assumed that `sql.service.latency` included both local and distributed SQL, but it only included local SQL.
