### ISSUE TITLE
sql: Highlight scans with filters in EXPLAIN

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#31100]
I spent some time today hunting down a customer-reported performance problem, and I think a change to the EXPLAIN output would have helped me reach the answer faster. Here's an anonymized version of the problem:

```
root@127.0.0.1:57624/defaultdb> create table t (a int primary key, b int, c int, d int, index (b, c, d));
CREATE TABLE

Time: 4.589ms

root@127.0.0.1:57624/defaultdb> explain select * from t where b=1 and d=2;
  tree | field |  description   
+------+-------+---------------+
  scan |       |                
       | table | t@t_b_c_d_idx  
       | spans | /1-/2          
(3 rows)

Time: 5.895ms

root@127.0.0.1:57624/defaultdb> explain select * from t where b=1 and d=2 and c=3;
  tree | field |  description   
+------+-------+---------------+
  scan |       |                
       | table | t@t_b_c_d_idx  
       | spans | /1/3/2-/1/3/3  
(3 rows)

Time: 1.11ms
```

The two queries here are very different: the first one is only able to use the index to select on column `b` and it throws away rows that don't match on column `d` after it has read them from KV. The second is able to make more precise use of the index and doesn't read anything that it doesn't return to the caller.  

The problem is that this difference in the explain output is subtle: I have to parse the number of columns out of the spans and compare that to the number of columns that "should" be used. The customer's issue was that they had written a query of the first form (filtering on `b` and `d` but not `c`), and they (and I) saw in `EXPLAIN` that it was using the index that they expected, without realizing that it was only partially using the index because of the omitted `c` term.

I think that `scanNodes` with a non-nil `filter` are sufficiently different from regular scans that they should be marked in some way in `EXPLAIN` output. The filter is shown in `EXPLAIN (VERBOSE)`, but I didn't know/think to look there and I think it should be shown by default.

**Comment by jordanlewis** [comment]
I agree - it's always bothered me that filters aren't shown outside of `EXPLAIN (VERBOSE)`. I don't think that makes too much sense. Let's fix it.
