### ISSUE TITLE
sql: ::REGTYPE pseudo-cast does not preserve type aliases

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#31102]
`select 'varchar'::regtype` returns "text" not "varchar"

The problem is that the code to do this does coltype->datum type->oid

The conversion coltype->datum type is lossy.

Instead the code should derive OIDs directly from the coltypes.

This causes confusions in ORMs e.g. TypeORM https://github.com/cockroachdb/cockroach/issues/22298#issuecomment-427961316

(found in CockroachDB 2.1 / master)

**Comment by jordanlewis** [comment]
This is solved:

```
root@127.0.0.1:61035/defaultdb> select 'varchar'::regtype;
        regtype
+---------------------+
  'character varying'
(1 row)
```
