### ISSUE TITLE
sql: implement udt_name (and _schema, and _catalog) in information_schema.columns

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#31101]
This is used by ORMs, eg TypeORM as discussed here: https://github.com/cockroachdb/cockroach/issues/22298#issuecomment-427961316

A prototype implementation was made here: https://github.com/knz/cockroach/tree/20181008-typeorm-tweaks

This needs care in that the type aliases (text vs varchar) must be preserved when generating the column values.

**Comment by jordanlewis** [comment]
Closed by #37271.
