### ISSUE TITLE
about read cache  concurrency 

### ISSUE THREAD

**Issue by Frank-Jin** [cockroachdb/cockroach#3111]
Cockroach uses red-black tree to store read cache，There is a risk of performance at the highly concurrent accesses. Maybe skiplist is a good option.
http://stackoverflow.com/questions/256511/skip-list-vs-binary-tree

**Comment by tschottdorf** [comment]
Hi Frank-Jin, the timestamp cache is accessed with the range lock held. If lock contention shows up as a limiting factor there, then we'll consider this option (though from a cursory search it appears that there's no locking skip list implementation for Go yet and we might have to write our own).
I'm going to close this for now, but please add further comments if you have any.
