### ISSUE TITLE
server: maybe surface unix socket

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#31113]
Requested on gitter.

The unix socket can be a reasonably way to communicate with a CockroachDB node when running on the same machine. We added it a while back for easier testing (easier than dynamic port allocation) but have never advertised or documented it. The flag (`--socket`) is currently hidden.

We should consider surfacing the flag in the CLI and documenting it. We first need to add some additional testing for it, including exercising in test clusters.

CC: @bdarnell for thoughts.

**Comment by bdarnell** [comment]
I'm generally in favor of exposing/encouraging unix sockets as an option. I think the biggest remaining work for this flag has more to do with documentation (especially how to get various clients to connect via the unix socket, which tends to involve a lot of magic) than with testing. 

Also, we should think about the big picture of how the flag would be used. Unix sockets are great for single-node clusters, in which case we might want to be able to disable the TCP ports completely when they are used. Does it ever really make sense to use unix sockets in a multi-node cluster (where the TCP ports are necessary for inter-node traffic and therefore you're probably not using dynamic ports)?

**Comment by knz** [comment]
it's possible unix sockets are faster to communicate with. so a local client for dump/restore eg would get more throughput using the unix socket than over TCP.

**Comment by inieves** [comment]
Please don't make usage of unix domain sockets and TCP/IP sockets mutually exclusive.  They have different use cases that might co-exist.

**Comment by inieves** [comment]
Heads up...

Unlike mysql (whereby the user can specify the full path of a socket file), postgres only allows the user to specify the directory in which the socket file will end up... And then in the case of postgres, the actual name of the socket file is chosen (through some heuristic) by postgres, not the user.  This affects how the user will later connect to the db...  the user will either supply the full path of the socket file in the case of mysql... or the path of the directory where the socket file is, in the case of postgres.

cockroach is attempting to be line compatible with postgres... that means that the user should not tell cockroach the full path of a socket file, but rather the path of the directory in which the socket file resides.  But this is not the case... The user is currently required to give cockroach the full path of a socket file.

This makes connecting to cockroach via driver (such as PHP PDO) over socket *nearly* impossible... 

e.g. I have told cockroach that I would like a socket to be created at: /var/run/cockroach/roach.sock
When I later try to connect to cockroach via PHP PDO, I get barfed on with the following message... notice the socket path that PDO goes looking for...

 Failed Connection: SQLSTATE[08006] [7] could not connect to server: Not a directory Is the server running locally and accepting connections on Unix domain socket "/var/run/cockroach/roach.sock/.s.PGSQL.5432"?


By nearly, I mean that if I tell cockroach to create a socket for me with the path: /var/run/cockroach/.s.PGSQL.5432
And then I tell the PDO driver to look for a socket in /var/run/cockroach, then I might get lucky and it might all work... through sneaky naming.

You probably want to consider using the postgres socket naming semantics, not the mysql socket naming semantics.

**Comment by inieves** [comment]
I was able to work-around the socket naming issue.
I ran into a subsequent issue.  Because I am running cockroach in secure mode, it is expecting connections to be SSL connections.  But socket connections coming from PHP PDO are not SSL...

The socket connections should probably not require SSL, regardless of secure/insecure mode of cockroach.

**Comment by inieves** [comment]
I can add more detail:

I found this: "sslmode is ignored for Unix domain socket communication." at https://www.postgresql.org/docs/10/static/libpq-connect.html.

**Comment by Fornax96** [comment]
I would like to use this too. The lack of TCP/IP and TLS overhead sounds like it could improve performance a lot.

**Comment by jasobrown** [comment]
Another use for the unix domain socket is when fronting CockroachDB with an on-instance TLS terminator (think envoy or haproxy) that processes custom x509 certs for specialized authN. Instead of attempting to put the custom cert handling into cockroach, we can have the proxy do that via a custom plugin, then pass all traffic through to cockroach over the domain socket on the same instance.

**Comment by inieves** [comment]
bravo!!
