### ISSUE TITLE
sql: panic in BitArray.Format

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#31115]
I'm looking to re-enable the partitioning tests, which were skipped as flaky a while ago. They generate random datums of the various column types we support, partition by those datums, and run some checks. The TestInitialPartitioning/BIT one is panic-ing.

Seems to repro pretty quickly under stress, but here's one of the random values I saw fail in case that's easier:
```
CREATE TABLE "BIT" (a BIT PRIMARY KEY) PARTITION BY LIST (a) (PARTITION p VALUES IN (B'0110001110111000010000000110010110010110010110111010101100011001'))
```

    panic: runtime error: index out of range [recovered]
    	panic: runtime error: index out of range
    
    goroutine 1028 [running]:
    github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc421502bd0, 0x2ecfb00, 0xc421538900)
    	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:184 +0x11f
    panic(0x2668ba0, 0x3fe3a40)
    	/usr/local/go/src/runtime/panic.go:502 +0x229
    github.com/cockroachdb/cockroach/pkg/util/bitarray.BitArray.Format(0xc421eb7cd0, 0x1, 0x1, 0xc422f22f41, 0xc423a3fea0)
    	/go/src/github.com/cockroachdb/cockroach/pkg/util/bitarray/bitarray.go:284 +0x310
    github.com/cockroachdb/cockroach/pkg/util/bitarray.BitArray.String(0xc421eb7cd0, 0x1, 0x1, 0xc421eb7b41, 0x0, 0x2)
    	/go/src/github.com/cockroachdb/cockroach/pkg/util/bitarray/bitarray.go:95 +0x6b
    github.com/cockroachdb/cockroach/pkg/util/encoding.prettyPrintFirstValue(0x0, 0xc421eb7bfe, 0x0, 0x2, 0xc422f23168, 0x2, 0x2, 0x2, 0x0, 0x0, ...)
    	/go/src/github.com/cockroachdb/cockroach/pkg/util/encoding/encoding.go:1486 +0x1451
    github.com/cockroachdb/cockroach/pkg/util/encoding.prettyPrintValueImpl(0x0, 0x0, 0x0, 0xc421eb7bf0, 0xe, 0x10, 0x299bd8e, 0x1, 0xc423a3fd50, 0x70, ...)
    	/go/src/github.com/cockroachdb/cockroach/pkg/util/encoding/encoding.go:1386 +0x112
    github.com/cockroachdb/cockroach/pkg/util/encoding.PrettyPrintValue(0x0, 0x0, 0x0, 0xc421eb7bf0, 0xe, 0x10, 0x299bd8e, 0x1, 0x0, 0x1)
    	/go/src/github.com/cockroachdb/cockroach/pkg/util/encoding/encoding.go:1350 +0x9b
    github.com/cockroachdb/cockroach/pkg/keys.decodeKeyPrint(0x0, 0x0, 0x0, 0xc421eb7bf0, 0xe, 0x10, 0x1, 0xc421eb7cc0)
    	/go/src/github.com/cockroachdb/cockroach/pkg/keys/printer.go:494 +0xf6
    github.com/cockroachdb/cockroach/pkg/keys.prettyPrintInternal.func1(0xc421eb7bf0, 0xe, 0x10, 0x4013a65, 0x1, 0x1)
    	/go/src/github.com/cockroachdb/cockroach/pkg/keys/printer.go:530 +0x3cc
    github.com/cockroachdb/cockroach/pkg/keys.prettyPrintInternal(0x0, 0x0, 0x0, 0xc421eb7bf0, 0xe, 0x10, 0xc42000b100, 0x2, 0x100)
    	/go/src/github.com/cockroachdb/cockroach/pkg/keys/printer.go:563 +0x410
    github.com/cockroachdb/cockroach/pkg/keys.PrettyPrintRange(0xc421eb7bf0, 0xe, 0x10, 0xc421eb7c08, 0x2, 0x8, 0x1e, 0x2, 0x0)
    	/go/src/github.com/cockroachdb/cockroach/pkg/keys/printer.go:734 +0xa5
    github.com/cockroachdb/cockroach/pkg/storage.(*atomicDescString).store(0xc422601280, 0x155bc13600000000, 0xc4239da5a0)
    	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:208 +0x1a0
    github.com/cockroachdb/cockroach/pkg/storage.(*Replica).initRaftMuLockedReplicaMuLocked(0xc422601200, 0xc422f387e0, 0xc4213f7b30, 0x0, 0x0, 0x0)
    	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:752 +0x3cc
    github.com/cockroachdb/cockroach/pkg/storage.splitPostApply(0x2ecfb00, 0xc421333680, 0x0, 0x155bc13615e4b599, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2367 +0x148
    github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleReplicatedEvalResult(0xc422600600, 0x2ecfb00, 0xc421333680, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_proposal.go:649 +0x117f
    github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleEvalResultRaftMuLocked(0xc422600600, 0x2ecfb00, 0xc421333680, 0xc423c96600, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_proposal.go:822 +0xaa
    github.com/cockroachdb/cockroach/pkg/storage.(*Replica).processRaftCommand(0xc422600600, 0x2ecfb00, 0xc421333680, 0xc421eb79c0, 0x8, 0x6, 0xf, 0x300000003, 0x1, 0x5, ...)
    	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:5644 +0x979
    github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReadyRaftMuLocked(0xc422600600, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:4460 +0x1356
    github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRequestQueue.func1(0x2ecfb00, 0xc423104990, 0xc422600600, 0x2ecfb00)
    	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3867 +0x109
    github.com/cockroachdb/cockroach/pkg/storage.(*Store).withReplicaForRequest(0xc421ac0b00, 0x2ecfb00, 0xc423104990, 0xc422f2c1a0, 0xc422f25ed0, 0x0)
    	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3518 +0x135
    github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRequestQueue(0xc421ac0b00, 0x2ecfb00, 0xc421538900, 0x127)
    	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3855 +0x229
    github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4213f1d00, 0x2ecfb00, 0xc421538900)
    	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:225 +0x21b
    github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x2ecfb00, 0xc421538900)
    	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:165 +0x3e
    github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4203d1280, 0xc421502bd0, 0xc4203d1270)
    	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:199 +0xe9
    created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
    	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:192 +0xad

**Comment by benesch** [comment]
I dug a little bit and managed to capture one of these bit arrays that can't be formatted:

```
I181022 04:18:05.799505 26512 storage/replica_command.go:300  [n3,split,s3,r266/1:/{Table/86/1/B…-Max}] initiating a split of this range at key "މ:\xfd\x8d\xecT\xfe9\x81V\xb1\x00\xc9" %!s(PANIC=runtime error: index out of range) [r267]
```

**Comment by benesch** [comment]
Ok, here's an instant repro:

```
CREATE TABLE bit (a BIT PRIMARY KEY) PARTITION BY LIST (a) (PARTITION p VALUES IN (B'1000110111101100010101001111111000111001100000010101011010110001'));;
ALTER PARTITION p OF TABLE bit CONFIGURE ZONE USING DEFAULT;
```

The spans that created invoke Next() on the primary key for the listed bit array, and *that* key can't be pretty-printed without panicing.

**Comment by knz** [comment]
@benesch found out that Next() was called on  the PK to increase it to a value that in turns makes it invalid.

However the `Next()` method for bitarrays nver produces invalid values.

I deduce that some code somewhere is trying to manually compute a Next() value on the raw bytes of the PK without using the Next code adequate for the column type.

What code would that be?

**Comment by benesch** [comment]
I believe it’s in partitionccl. The example I posted creates a partition with just one bit array. This results in a range with bounds [key, key.Next()), and the Next() operation is on a roachpb.Key, not a a bit array datum.

I don’t think the solution here is to avoid this call to Next(). We call Next() on keys all over the place, so I’m sure there’s another code path that could Next() a bit array key and then try to print it. I think we have to teach the bit array printer to handle nonsense lastBitArray values without panicking.

**Comment by knz** [comment]
test

**Comment by benesch** [comment]
Apologies. Everywhere I've said Next() above I've been meaning to say PrefixEnd().

**Comment by knz** [comment]
so having a next() function that simply bumps the last byte is not only bad because of this pretty-printing bug, it's might also be semantically incorrect.

If, say I have a bit array `B'XXX(64 bits)XXX'`.
This is encoded by two varints: a varint containing the XXXXX vits and then the "last bits used field" set to 64.

The symbolic "next" value is: `B'XXX(64bits)XXX0` (a 0 appended)

The canonical encoding for this is 3 varints: the XXXXX bits, then a 0 varint, then a last bits used field set to 1.

The bad encoding produced by roachpb.key.next under scrutiny produces 2 varints: the XXXX bits then a lastbits used field set to 65.

So if we just look at the first 2 varints, the bad encoding sorts after the good.

In fact, it sorts "weirdly":

- it sorts after `B'XXXX0` (word X, word 0, lastused 1)
- it sorts before `B'XXXX1` (word X, word 2^63, lastused 1)
- it incorrectly sorts after `B'XXXX0(60 bits unset)0` (word X, word 0, last used 60)
- it correctly sorts before `B'XXXX1(60 bits set)1` (word X, word 1111111, last used 60)

There may be some accidental magic occuring because of the tag bytes in between the varints? 

But maybe the lesson here is that there should be an *additional* tag byte after the lastbitsused varint. So that the roachpb.key.next() method would bump the tag byte, and not the actual varints that participate in the bytearray value?

I'd love to hear some advice from @nvanbenschoten about how to properly approach this.

**Comment by knz** [comment]
please ignore my previous comment -- if the concern is in PrefixEnd() then my comment does not apply.

**Comment by knz** [comment]
My question here is why is the pretty print code for roachpb.keys, originally meant for debug only, involved in a user visible bug?
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by danhhz** [comment]
Looks like it's being used to create the string description of the new replica after a split (see the stack trace in the original issue text).
