### ISSUE TITLE
which range is range local key located? range 1 or range same as non-local key?

### ISSUE THREAD

**Issue by es-chow** [cockroachdb/cockroach#3113]
There is an inconsistence for range local key in these two places:
1. `getCachedRangeDescriptorLocked` in `range_cache.go`, it use `meta()` to generate the metaKey, so a range local key like "\x00\x00\x001ka\x00\x01rtn-" after `meta()` will generate metaKey "\x00\x00meta2\x00\x00\x001ka\x00\x01rtn-\x00", mostly it will target to range 1.

but 
2. comments in `Addr()` in `keys.go`, 
```
However, for    
// local keys, such as transaction records, range-spanning binary tree node     
// pointers, the address is the trailing suffix of the key, with the local key 
// prefix removed. In this way, local keys address to the same range as         
// non-local keys, but are stored separately so that they don't collide with    
// user-space or global system keys.
```
it says that range local key such as range tree node should be located to the same range as non-local key, so range local key like "\x00\x00\x001ka\x00\x01rtn-" should be located in range which contains "a", it may not be range 1. In this case, metaKey for the mentioned range local key should be "\x00\x00meta2a\x00".

So which one is correct? If range local key should be always located to range 1, then why should name it as range local?

**Comment by bdarnell** [comment]
Range-local keys should be on the same range as the corresponding non-local key. If that's ever not true, it's a bug. We're trying to enforce this with the `Key`/`RKey` distinction: range-local keys can never be `RKeys`. `keys.Addr()` is the only safe way to convert a `Key` to an `RKey` (it converts the range-local `Key` `\x00\x00\x001ka\x00\x01rtn-` to the `RKey` `a`). Unless we are incorrectly casting a `Key` directly to an `RKey`, `range_cache.go` should never see a range-local key.

**Comment by es-chow** [comment]
Sorry, It's not a issue. Range-local key had been converted to `RKey` in `sendChunk` in `dist_sender.go`.
