### ISSUE TITLE
sql: some checks for the delete fast paths are redundant

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#31130]
I was staring at this code and I was wondering why the same checks are made multiple times: whether a table has secondary indices, whether it is referenced by FKs, etc.

- previously the fast path was decided based on whether just the *target table* was verifying these predicates
- over the summer Emannuel added another conditional that verifies the predicates over both the target table and its interleaved children

The second conditional subsumes the first partly. Those parts of the first conditional should have been removed when the second was added.

cc @BramGruneir 

![delete](https://user-images.githubusercontent.com/642886/46666599-5e8c8d00-cbc7-11e8-8dcc-21682ce5d8f2.png)

**Comment by BramGruneir** [comment]
Hey, it's always good to measure twice and cut once!

Nice catch by the way.  This should be an easy cleanup.
