### ISSUE TITLE
opt: consider marking more functions as side-effecting

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#31148]
Today, we only mark functions as side-effecting if they are tagged "impure." This means that they explicitly affect the state of the database or might return different results on subsequent calls for the same inputs (say, `nextval()`).

However, in the same vein as division being side-effecting due to the possibility of an error occurring due to division by zero, there's a much larger set of functions which can _error_:

```
root@127.0.0.1:52909/defaultdb> select to_uuid('x');
pq: to_uuid(): uuid: incorrect UUID length: x
```

Since we don't currently give these the same treatment, it's possible that hoisting could result in an error occurring which shouldn't logically occur.

cc @knz

**Comment by knz** [comment]
To reproduce the discussion taken elsewhere:

1) I am of the opinion that hoisting should always be done, except at CASE boundaries

2) Andy disagrees:
  - the currently considered xforms would hoist subqueries across CASE boundaries, this hoisting of subqueries is thus possibly incorrect for functions that can error out
  - Andy thinks the hoisting across CASE should be conditional on side effects, which must be extended to include "whether the function has error cases" 

3) I have looked at postgres and observe that pg stops hoisting **anything** across CASE, including subqueries. For example:

```
kena=> explain(verbose) SELECT * FROM abc WHERE (CASE WHEN a='a' THEN true ELSE (select false) END);
                          QUERY PLAN
---------------------------------------------------------------
 Seq Scan on public.abc  (cost=0.01..18.14 rows=325 width=96)
   Output: a, b, c
   Filter: CASE WHEN (abc.a = 'a'::text) THEN true ELSE $0 END
   InitPlan 1 (returns $0)
     ->  Result  (cost=0.00..0.01 rows=1 width=1)
           Output: false
(6 rows)
```

(the constant, uncorrelated subquery remains inside CASE with an apply operator)

My opinion thus remains: keep the xform rules simple, and **do not consider erroring situations in functions to decide side effects** -- the correctness rule can be "don't hoist anything across CASE" and we won't be any less correct (nor efficient) than pg.

**Comment by rytaft** [comment]
@RaduBerinde do you think we can close this now with the work in the last release to classify functions as immutable/volatile?

**Comment by RaduBerinde** [comment]
Yeah.
