### ISSUE TITLE
storage: "failed to look up recipient replica" errors correlated with large exec.error metric spike

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#31147]
During some rebalancing, I saw the average qps on one of the nodes in my partition-less tpc-c 50k cluster have a huge spike in QPS:

<img width="964" alt="screen shot 2018-10-08 at 10 43 03 pm" src="https://user-images.githubusercontent.com/7085343/46687122-af988300-cbbf-11e8-8d9c-d95d9962d3c2.png">

This was suspicious, since tpc-c isn't a very spiky workload, so I checked out a graph of the `exec.error` metric on each node to see if these were real requests or just retries:

<img width="959" alt="screen shot 2018-10-08 at 10 43 34 pm" src="https://user-images.githubusercontent.com/7085343/46687181-d0f96f00-cbbf-11e8-8a57-32f876cd27c3.png">

The same node had a huge spike in exec errors at roughly the same time.

I dug into the logs for the node, and found a lot of lines that look like:

```
W181009 03:42:44.046274 604 storage/replica.go:5013  [n48,s50,r216912/4:/Table/54/1/4{3308/9-4070/6}] failed to look up recipient replica 1 in r216912 while sending MsgApp: replica 1 not present in (n44,s39):3, [(n45,s34):5 (n48,s50):4 (n44,s39):3]
W181009 03:43:23.522901 589 storage/replica.go:5013  [n48,s50,r216920/4:/Table/54/1/44{070/6-842/10}] failed to look up recipient replica 2 in r216920 while sending MsgApp: replica 2 not present in (n44,s39):3, [(n27,s28):1 (n48,s50):4 (n44,s39):3]
W181009 03:44:08.458030 569 storage/replica.go:5013  [n48,s50,r217173/4:/Table/54/1/41{297/5-985/5}] failed to look up recipient replica 2 in r217173 while sending MsgApp: replica 2 not present in (n64,s65):1, [(n64,s65):1 (n48,s50):4 (n44,s39):3]
W181009 03:42:30.327380 600 storage/replica.go:5013  [n48,s50,r216915/5:/Table/54/1/4{0735/8-1297/5}] failed to look up recipient replica 2 in r216915 while sending MsgApp: replica 2 not present in (n44,s39):3, [(n64,s65):4 (n48,s50):5 (n44,s39):3]
```

Notice that the "failed to look up recipient replica" errors were happening for a variety of ranges, not all the same one.

I tracked the history for one specific range and found:

```
I181009 03:41:49.862773 27940231 storage/replica_raftstorage.go:809  [n48,s50,r216915/?:/Table/54/1/4{0735/8-1297/5}] applied preemptive snapshot in 709ms [clear=2ms batch=410ms entries=0ms commit=296ms]
...
I181009 03:42:26.190551 578 storage/replica_proposal.go:211  [n48,s50,r216915/5:/Table/54/1/4{0735/8-1297/5}] new range lease repl=(n48,s50):5 seq=13 start=1539056509.880386576,0 epo=2 pro=1539056509.880390090,0 following repl=(n64,s65):4 seq=12 start=1539034251.499412432,122 epo=2 pro=1539034251.499412432,123
...
I181009 03:42:28.270730 29664480 storage/replica_command.go:812  [n48,s50,r216915/5:/Table/54/1/4{0735/8-1297/5}] change replicas (REMOVE_REPLICA (n121,s121):2): read existing descriptor r216915:/Table/54/1/4{0735/8-1297/5} [(n64,s65):4, (n121,s121):2, (n44,s39):3, (n48,s50):5, next=6, gen=2]
I181009 03:42:30.285468 29664480 storage/replica.go:3763  [n48,s50,r216915/5:/Table/54/1/4{0735/8-1297/5}] proposing REMOVE_REPLICA((n121,s121):2): updated=[(n64,s65):4 (n48,s50):5 (n44,s39):3] next=6
W181009 03:42:30.316858 600 storage/replica.go:5013  [n48,s50,r216915/5:/Table/54/1/4{0735/8-1297/5}] failed to look up recipient replica 2 in r216915 while sending MsgApp: replica 2 not present in (n44,s39):3, [(n64,s65):4 (n48,s50):5 (n44,s39):3]
...repeated a bunch...
I181009 03:42:34.093287 29765123 storage/store_snapshot.go:615  [n48,s50,r216915/5:/Table/54/1/4{0735/8-1297/5}] sending preemptive snapshot 1db53bff at applied index 23382190
...
I181009 03:42:39.687919 29765123 storage/store_snapshot.go:657  [n48,s50,r216915/5:/Table/54/1/4{0735/8-1297/5}] streamed snapshot to (n45,s34):?: kv pairs: 402570, log entries: 123, rate-limit: 8.0 MiB/sec, 5595ms
I181009 03:42:40.336581 29765123 storage/replica_command.go:812  [n48,s50,r216915/5:/Table/54/1/4{0735/8-1297/5}] change replicas (ADD_REPLICA (n45,s34):6): read existing descriptor r216915:/Table/54/1/4{0735/8-1297/5} [(n64,s65):4, (n48,s50):5, (n44,s39):3, next=6, gen=2]
I181009 03:42:40.660123 29765123 storage/replica.go:3763  [n48,s50,r216915/5:/Table/54/1/4{0735/8-1297/5}] proposing ADD_REPLICA((n45,s34):6): updated=[(n64,s65):4 (n48,s50):5 (n44,s39):3 (n45,s34):6] next=7
I181009 03:42:40.881705 29883377 storage/replica_command.go:812  [n48,s50,r216915/5:/Table/54/1/4{0735/8-1297/5}] change replicas (REMOVE_REPLICA (n64,s65):4): read existing descriptor r216915:/Table/54/1/4{0735/8-1297/5} [(n64,s65):4, (n48,s50):5, (n44,s39):3, (n45,s34):6, next=7, gen=2]
I181009 03:42:41.419457 29883377 storage/replica.go:3763  [n48,s50,r216915/5:/Table/54/1/4{0735/8-1297/5}] proposing REMOVE_REPLICA((n64,s65):4): updated=[(n45,s34):6 (n48,s50):5 (n44,s39):3] next=7
W181009 03:42:41.588227 611 storage/replica.go:5013  [n48,s50,r216915/5:/Table/54/1/4{0735/8-1297/5}] failed to look up recipient replica 4 in r216915 while sending MsgApp: replica 4 not present in (n45,s34):6, [(n45,s34):6 (n48,s50):5 (n44,s39):3]
...repeated a bunch...
W181009 03:42:41.825582 564 storage/store.go:3921  [n48,s50] handle raft ready: 0.5s [processed=46]
...no more errors...
```

So the errors are seemingly just a result of a replica removal being interleaved with other writes to the raft group. It actually looks pretty benign to me, but the huge spike in exec errors at the same time is odd since I'm not sure why dropping raft messages would cause that.

If anyone has thoughts, I'd love to hear them. Otherwise there may not be much to do here.

**Comment by tschottdorf** [comment]
What QPS metric spiked here? I think if nothing else then we should fix (or clarify) the fact that unsuccessful operations seem to be counted. Were you looking at this one?

```
	metaExecSuccess = metric.Metadata{
		Name:        "exec.success",
		Help:        "Number of batch KV requests executed successfully on this node",
		Measurement: "Batch KV Requests",
		Unit:        metric.Unit_COUNT,
	}

```

The update on that one seems sane:

```
// callComplete records very high-level metrics about the number of completed
// calls and their latency. Currently, this only records statistics at the batch
// level; stats on specific lower-level kv operations are not recorded.
func (nm nodeMetrics) callComplete(d time.Duration, pErr *roachpb.Error) {
	if pErr != nil && pErr.TransactionRestart == roachpb.TransactionRestart_NONE {
		nm.Err.Inc(1)
	} else {
		nm.Success.Inc(1)
	}
	nm.Latency.RecordValue(d.Nanoseconds())
}

```

**Comment by a-robinson** [comment]
> What QPS metric spiked here? I think if nothing else then we should fix (or clarify) the fact that unsuccessful operations seem to be counted. Were you looking at this one?

No, it's the qps metric used by load-based rebalancing, i.e.:

https://github.com/cockroachdb/cockroach/blob/55cdc516b9ee8878241f6cc566f2148b1728a0f4/pkg/storage/replica.go#L1996-L2002

Which is known to include errors in its count. Whether or not it should is an interesting question, since requests that result in errors still put load on a replica, but typically not as much as successful requests.

What I was more surprised about was that `failed to look up recipient replica` resulted in requests failing at all. Why does not being able to contact a single raft follower (leading to a single raft message getting dropped) cause a batch request to fail?

**Comment by tschottdorf** [comment]
> What I was more surprised about was that failed to look up recipient replica resulted in requests failing at all. Why does not being able to contact a single raft follower (leading to a single raft message getting dropped) cause a batch request to fail?

Is that what happened? I thought you only saw a correlation between these errors and the spike in QPS. What I'm thinking is that this is somehow a situation in which replicas might generate RangeNotFoundErrors (or something like that) which are retried aggressively by DistSender (well, with a 1s backoff, but add lots of concurrent requests and you get a decent amount of qps all in all).

When that happens, it can really mess with the stats, which is why I was wondering why that metric included failures. It should include *some* failures (`ConditionFailedError`, txn restarts, etc) but not `RangeNotFound`. In a sense, this would better be tracked via a callback from the replica itself (where you know whether you got the error as a result of running the batch or whether it wonked out before).

**Comment by a-robinson** [comment]
> What I'm thinking is that this is somehow a situation in which replicas might generate RangeNotFoundErrors

Hmm, that's possible. I can't remember at this point whether I would have noticed that in any of the graphs I was looking at.

> In a sense, this would better be tracked via a callback from the replica itself (where you know whether you got the error as a result of running the batch or whether it wonked out before).

Agreed. It really just wants to count the number of requests that add load to the replica. It'd be nice to avoid counting anything that returns relatively quickly with an error.
