### ISSUE TITLE
TPCCbench failed under chaos

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#31156]
**Describe the problem**

TPCC bench failed under chaos 
`andy-1539099254-tpccbench-nodes-7-cpu-16-chaos: getting (scp) logs artifacts/tpccbench/nodes=7/cpu=16/chaos/logs
.
   1: done
   2: done
   3: done
   4: done
   5: done
   6: done
   7: done
   8: ~ scp -r -C -i /Users/andrewwoods/.ssh/google_compute_engine -o StrictHostKeyChecking=no andrewwoods@104.196.59.43:logs artifacts/tpccbench/nodes=7/cpu=16/chaos/8.logs
scp: logs: No such file or directory
: exit status 1
: exit status 1skipping cluster wipe
--- FAIL: tpccbench/nodes=7/cpu=16/chaos (10308.30s)
	test.go:570,cluster.go:1318,tpcc.go:663,tpcc.go:333: error running tpcc load generator:
		
		Error: EOF
		Error:  exit status 1
		
		: /Users/andrewwoods/go/bin/roachprod run andy-1539099254-tpccbench-nodes-7-cpu-16-chaos:8 -- ulimit -n 32768; ./workload run tpcc --warehouses=5000 --active-warehouses=2000 --tolerate-errors --ramp=5m0s --duration=10m0s {pgurl:8}: exit status 1
FAIL`

**To Reproduce**

Ran tpcc-bench with chaos on 7 nodes 

**Environment:**
 - CockroachDB version [e.g. 2.1 Beta 09/17]

[cockroach.log](https://github.com/cockroachdb/cockroach/files/2461885/cockroach.log)

**Comment by awoods187** [comment]
Tried to re-run this and it failed on the 2.1 beta 10/08

Didn't see anything in the logs
[cockroach.log](https://github.com/cockroachdb/cockroach/files/2465559/cockroach.log)

**Comment by awoods187** [comment]
cc @nvanbenschoten

**Comment by nvanbenschoten** [comment]
I'm running this now.

**Comment by nvanbenschoten** [comment]
I was able to reproduce this pretty easily.
