### ISSUE TITLE
Dead nodes and underreplicated ranges on tpcc 10K without using partitioning 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#31170]
**Describe the problem**

Using TPCC-Bench and Roachprod to test tpc-c 10K with 30 nodes without using partitioning. 

My cluster has 1 dead node and 28 suspect nodes.

**To Reproduce**

1. Increase ramp dur from tpcc-bench
`@@ -414,7 +414,7 @@ func loadTPCCBench(
        // generation doesn't actually run.
        cmd = fmt.Sprintf("ulimit -n 32768; "+
                "./workload run tpcc --warehouses=%d --split --scatter %s "+
-               "--duration=3m --tolerate-errors {pgurl:1}", b.LoadWarehouses, partArgs)
+               "--duration=8h --tolerate-errors {pgurl:1}", b.LoadWarehouses, partArgs)
        if out, err := c.RunWithBuffer(ctx, c.l, loadNode, cmd); err != nil {
                return errors.Wrapf(err, "failed with output %q", string(out))
        }`

2. Ran tpcc-bench for 30 nodes without using partition
3. Look at UI / log file / client app ...

![image](https://user-images.githubusercontent.com/22278911/46704294-5f89e280-cbf8-11e8-8a97-82d994ef5eca.png)

On node 1 I see lots of errors for example:
E181009 22:54:34.634928 26913171 storage/replica_range_lease.go:296  [n1,s1,r2994/1:/Table/61/1/3{867/5/…-904/4/…}] mismatch incrementing epoch for {NodeID:25 Epoch:1 Expiration:1539125643.219633511,0 Draining:false Decommissioning:false}; actual is {NodeID:25 Epoch:1 Expiration:1539125665.719620766,0 Draining:false Decommissioning:false}

On the dead node 17 I see no errors but all warnings. 

**Expected behavior**
Passing tpcc 10K without using partitioning 

**Environment:**
 - CockroachDB version 2.1 beta 09/17

Dead node 17
[cockroach.log](https://github.com/cockroachdb/cockroach/files/2462555/cockroach.log)

Node 1
[cockroach.log](https://github.com/cockroachdb/cockroach/files/2462710/cockroach.log)

**Comment by awoods187** [comment]
cc @tschottdorf and I extended my cluster to keep it around

**Comment by awoods187** [comment]
Log for dead node 
[cockroach.log](https://github.com/cockroachdb/cockroach/files/2462708/cockroach.log)

**Comment by benesch** [comment]
From the dead node:

```terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc```

This sure looks like https://github.com/cockroachdb/cockroach/issues/30389. @awoods187 can you retry with the latest beta?

**Comment by awoods187** [comment]
Re-running now
