### ISSUE TITLE
changefeedccl: test for memory monitoring

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#31198]
First step is figuring out what the memory monitoring guarantees should be in changefeeds.

There may also be some non-test work to monitor memory usage of the cloud storage sink: https://github.com/cockroachdb/cockroach/blob/4e2e450ecf5c3f73c7de46e48696528468803db7/pkg/ccl/changefeedccl/sink_cloudstorage.go#L172

Epic CRDB-1419

Jira issue: CRDB-4806

**Comment by danhhz** [comment]
#35745 did this for the main changefeed buffer. cloud storage sink is still TODO

**Comment by miretskiy** [comment]
Closing; stale.
