### ISSUE TITLE
TPCC bench failed without partitioning on 30 nodes 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#31193]
**Describe the problem**

TPCC bench failed without partitioning on 30 nodes 

**To Reproduce**

ran `bin/roachtest bench '^tpccbench/nodes=30/cpu=16$$' --wipe=false --user=andy`

We set ramp duration to 8hs:

`+++ b/pkg/cmd/roachtest/tpcc.go
@@ -414,7 +414,7 @@ func loadTPCCBench(
        // generation doesn't actually run.
        cmd = fmt.Sprintf("ulimit -n 32768; "+
                "./workload run tpcc --warehouses=%d --split --scatter %s "+
-               "--duration=3m --tolerate-errors {pgurl:1}", b.LoadWarehouses, partArgs)
+               "--duration=8h --tolerate-errors {pgurl:1}", b.LoadWarehouses, partArgs)
        if out, err := c.RunWithBuffer(ctx, c.l, loadNode, cmd); err != nil {
                return errors.Wrapf(err, "failed with output %q", string(out))`

Observed:
The restore took 48 minutes.

`: exit status 1
: exit status 1skipping cluster wipe
--- FAIL: tpccbench/nodes=30/cpu=16 (32099.78s)
	test.go:570,cluster.go:1318,tpcc.go:663,tpcc.go:333: pq: setting updated but timed out waiting to read new value
FAIL`

**Expected behavior**
I expected tpcc to pass. 

**Additional data / screenshots**
Roachprod destroyed the cluster before I could grab the logs 

**Environment:**
 - CockroachDB version 2.1.beta 10/08

**Comment by awoods187** [comment]
CC @nvanbenschoten

**Comment by nvanbenschoten** [comment]
I think I've seen this issue as well on a loaded cluster. We should bump the SET CLUSTER SETTING timeout to 10 seconds. Sending a PR now.

**Comment by nvanbenschoten** [comment]
FWIW every time I've seen this, the cluster setting statement passes if reissued.
