### ISSUE TITLE
changefeedccl: restart the flow when too many ChangeAggregator processors are no longer scheduled on leaseholders

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#31205]
We schedule the changefeed flow such that every ChangeAggregator is on the leaseholder for the range it's responsible for. But ranges can split, merge, and rebalance and there's no way to update the running flow to move them around. In some future world, perhaps we'll do #28674, which would be a real solution for this. In the meantime, we should monitor how many leaseholders are no longer scheduled local to the ChangeAggregators and restart the flow.

Jira issue: CRDB-4803

**Comment by danhhz** [comment]
This is not going to make 2.2. The manual workaround of periodically pausing and unpausing the changefeed will have to do for now.

**Comment by ajwerner** [comment]
Since 19.2 rangefeeds are used and so leaseholders don't really matter because a rangefeed can use any replica. However, the problem of entropy sneaking in remains an issue.

**Comment by amruss** [comment]
@ajwerner what do you mean by entropy sneaking in?

**Comment by miretskiy** [comment]
We have a mechanism for this in place.
