### ISSUE TITLE
changefeedccl, ui: move changefeeds out of the jobs page in the admin ui

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#31211]
they're really not the same. especially once we do #28668 the user should never know they're implemented as jobs under the hood.

Epic CRDB-2365

Jira issue: CRDB-4802

**Comment by danhhz** [comment]
The RFC proposed a new tab: https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20180501_change_data_capture.md#adminui

**Comment by vilterp** [comment]
Would prefer to keep it on the same top-level page as jobs, to avoid a proliferation of pages… Maybe a new tab on the Jobs page would work, but then we'd want a name for the page that encompasses jobs and changefeeds.

I guess once we have IUMVs, having a tab for the two of them makes sense.
