### ISSUE TITLE
cdc: Put schema change backfill support behind a changefeed option

### ISSUE THREAD

**Issue by mrtracy** [cockroachdb/cockroach#31213]
Issue #30902 introduced CHANGEFEED support for tables undergoing a schema change backfill. However, once the backfill is complete this will result in an entry being emitted for every row in the table, which may be an exceptional amount of data for a large table.

While we believe this to be the correct implementation, we may want to allow customers to return the previous behavior of stopping the changefeed when a backfill occurs. This would be accomplished by adding a changefeed option.

Jira issue: CRDB-4801

**Comment by miretskiy** [comment]
schema_change_policy option lets users control this.
