### ISSUE TITLE
Snapshot failed, mismatch incrementing epoch, and other errors when running tpcc with 30 nodes without partitioning 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#31234]
**Describe the problem**
![image](https://user-images.githubusercontent.com/22278911/46774046-7569d700-ccce-11e8-86bf-b833e3485c88.png)

**To Reproduce**
Changed ramp duration to 8h

`@@ -414,7 +414,7 @@ func loadTPCCBench(
        // generation doesn't actually run.
        cmd = fmt.Sprintf("ulimit -n 32768; "+
                "./workload run tpcc --warehouses=%d --split --scatter %s "+
               "--duration=3m --tolerate-errors {pgurl:1}", b.LoadWarehouses, partArgs)
               "--duration=8h --tolerate-errors {pgurl:1}", b.LoadWarehouses, partArgs)
        if out, err := c.RunWithBuffer(ctx, c.l, loadNode, cmd); err != nil {
                return errors.Wrapf(err, "failed with output %q", string(out))
        }`

Ran `bin/roachtest bench '^tpccbench/nodes=30/cpu=16$$' --wipe=false --user=andy`

**Expected behavior**

**Additional data / screenshots**

2018-10-10 22:54:26 | ERROR | [n1,raftsnapshot,s1,r190/1:/Table/59/1/{692/5/…-1181/3…}] snapshot failed: (n3,s4):4: remote couldn't accept Raft snapshot 5a04dfcf at applied index 13 with error: [n3,s4],r190: cannot apply snapshot: snapshot intersects existing range [n3,s4,r75/4:/{Table/59/1/6…-Max}]

2018-10-10 22:54:26 | ERROR | [n1,replicate,s1,r305/1:/Table/59/1/3619/10/-1503…] change replicas of r305 failed: descriptor changed: [expected] r305:/{Table/59/1/3619/10/-1503-Max} [(n1,s1):1, (n28,s24):2, (n2,s2):3, (n3,s4):4, next=5, gen=0] != [actual] r305:/Table/59/1/3619/10/-1503{-/0} [(n1,s1):1, (n28,s24):2, (n2,s2):3, (n3,s4):4, next=5, gen=1]: unexpected value: raw_bytes:"\001\270\340\017\003\010\261\002\022\t\303\211\367\016#\222\206\372!\032\n\303\211\367\016#\222\206\372!\210\"\006\010\001\020\001\030\001\"\006\010\034\020\030\030\002\"\006\010\002\020\002\030\003\"\006\010\003\020\004\030\004(\0050\001" timestamp:<wall_time:1539212066497189048 >

E181011 00:39:55.229855 14221444 storage/replica_range_lease.go:301  [n1,s1,r40208/1:/Table/61/1/5023/65647{-/0}] mismatch incrementing epoch for {NodeID:27 Epoch:1 Expiration:1539218351.983387584,0 Draining:false Decommissioning:false}; actual is {NodeID:27 Epoch:1 Expiration:1539218369.983334357,0 Draining:false Decommissioning:false}

E181011 00:43:46.696866 15483502 storage/replica_range_lease.go:301  [n1,s1,r41307/1:/Table/61/1/503{3/126…-4/5220}] context canceled

E181010 22:54:16.124941 68 sqlmigrations/migrations.go:370  [n8] failed attempt to acquire migration lease: lease /System/"system-version/lease" is not available until at least 1539212116.073461816,0`

**Environment:**
CockroachDB version 2.1.0 beta 1008

[cockroach.log](https://github.com/cockroachdb/cockroach/files/2466947/cockroach.log)

[cockroach.log](https://github.com/cockroachdb/cockroach/files/2466948/cockroach.log)

**Comment by nvanbenschoten** [comment]
Yikes, I see the issue. We're pointing all the load at node 1 and completely overloading it! If you look at the UI of any of the other nodes, they look a lot better. I'll send a fix for this alongside the fix for #31156.

For context, the goal of the 8-hour ramp change was to give the cluster time to rebalance based off of load. @a-robinson do you have any suggestions on priming a cluster using load-based splitting without overloading it? Is the idea to just gradually increase qps while maintaining the desired load distribution?

The first error log you listed is being looked at in https://github.com/cockroachdb/cockroach/issues/30064. All the others are harmless. There's probably a point to be made about reducing the severity of logs that we know are usually ok, but that's part of a bigger discussion.

**Comment by a-robinson** [comment]
> For context, the goal of the 8-hour ramp change was to give the cluster time to rebalance based off of load. @a-robinson do you have any suggestions on priming a cluster using load-based splitting without overloading it? Is the idea to just gradually increase qps while maintaining the desired load distribution?

I'd expect an 8 hour ramp to work without overloading the cluster. Really, I'd hope for less than 8 hours to get it closer to the speed of using partitioning. If it doesn't work without overloading the cluster, that's something that users will inevitably run into and that we need to fix.
