### ISSUE TITLE
sentry: net.go:159: *net.OpError

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#31254]
https://sentry.io/cockroach-labs/cockroachdb/issues/723268804/

net.go:159: *net.OpError

github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func5

> stacktrace: {u'frames': [{u'function': u'func1', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go', u'module': u'github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker', u'in_app': False, u'lineno': 192, u'filename': u'github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go'}, {u'function': u'func5', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go', u'module': u'github.com/cockroachdb/cockroach/pkg/server.(*Server).Start', u'in_app': False, u'lineno': 1058, u'filename': u'github.com/cockroachdb/cockroach/pkg/server/server.go'}]}
type: *log.safeError
value: net.go:159: *net.OpError

**Comment by tschottdorf** [comment]
@petermattis mind taking a look (haven't yet myself)? It's on 2.0.2 so might be long fixed.

**Comment by petermattis** [comment]
Not much to go on here. This corresponds to the following code in `server/server.go`:

```
	s.stopper.RunWorker(workersCtx, func(context.Context) {
		netutil.FatalIfUnexpected(httpServer.Serve(httpLn))
	})
```

`netutil.FatalIfUnexpected` ignores various errors indicating a closed connection.

I'll take a look at commits in these areas of the code base to see if anything was changed.

**Comment by petermattis** [comment]
`netutil.FatalIfUnexpected` is identical on master and 2.0.2. 

This crash is a duplicate of https://github.com/cockroachdb/cockroach/issues/24481. You added some additional logging in #24833. Unfortunately that PR was never backported to 2.0.x. Do you see anything else to do here other than wait for an occurrence on 2.1?

I'll note that sentry indicates the server had been up for <1m and that this was a single node cluster (the sentry data for the last occurrence has already been deleted, so I can't tell if there is a pattern here).

**Comment by tschottdorf** [comment]
Ah, thanks for looking. I think we can wait for 2.1

Closing for https://github.com/cockroachdb/cockroach/issues/24481
