### ISSUE TITLE
sql: prepared statement memory use is not tracked or bounded

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#31268]
We've seen cases where runaway clients can prepare an unbounded number of statements and blow up memory on a SQL gateway. This memory should be accounted for somehow and bounded to prevent this from hurting performance and causing OOMs.

@knz for triage.

**Comment by knz** [comment]
@andreimatei feel free to take ownership or close with a suitable explanation. I recall we discussed this but I don't remember we wrote the conclusion down anywhere.

**Comment by jordanlewis** [comment]
This is now closed, since prepared statements take into account the size estimate of their embedded memo.
