### ISSUE TITLE
opt: take limit into account when costing lookup join

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#31281]
We've seen a situation where we have a JOIN with a LIMIT. A lookup join should be very attractive in this case because it can finish early; however we are currently costing it as if the entire join will always finish.

We would need to add support for `HardLimit` in `LookupJoin` and add an exploration rule that pushes any limit into the lookup join.

**Comment by awoods187** [comment]
A customer ran into an issue with our lack of support for this issue. They were able to split their queries up into multiple queries to reduce latency as a workaround.

**Comment by RaduBerinde** [comment]
This falls under #34811. I was proposing a different mechanism here, but I believe the general mechanism proposed there is the better way to go.
