### ISSUE TITLE
set time zone 'asia/kolkata'; timezone data cannot be found in ubuntu

### ISSUE THREAD

**Issue by irshadhasmat** [cockroachdb/cockroach#31297]
When I am trying to set timezone in ubuntu server by the command:
set time zone 'asia/kolkata'; 

I am getting **pq: cannot find time zone "asia/kolkata": timezone data cannot be found**

where as this command run without issue in Mac.

I tried to execute this command on cockroach 2.0.5 and 2.0.6 

Server version: CockroachDB CCL v2.0.6 (x86_64-unknown-linux-gnu, built 2018/10/01 13:59:40, go1.10) (same version as client)

oot@:26257/> set time zone 'asia/kolkata';
pq: cannot find time zone "asia/kolkata": timezone data cannot be found
root@:26257/>

**Comment by jordanlewis** [comment]
Hmm, I think we get our timezone information from the system. Perhaps your tzinfo files need updating on Ubuntu?

**Comment by mberhault** [comment]
TImezones in linux (not sure about others) are case sensitive:

```
root@:26257/defaultdb> show time zone;
  timezone  
+----------+
  UTC       
(1 row)

root@:26257/defaultdb> set time zone 'asia/kolkata';
pq: invalid value for parameter "timezone": "'asia/kolkata'"
DETAIL: cannot find time zone "asia/kolkata": timezone data cannot be found

root@:26257/defaultdb> set time zone 'Asia/Kolkata';
SET

root@:26257/defaultdb> show time zone;
    timezone    
+--------------+
  Asia/Kolkata  
(1 row)
```

**Comment by irshadhasmat** [comment]
Thanks @mberhault for your support.

**Comment by pmneo** [comment]
Similar problem here with Europe/Berlin on a Windows machine:

```
root@:26257/defaultdb> set time zone 'europe/berlin';
pq: invalid value for parameter "timezone": "'europe/berlin'"
DETAIL: cannot find time zone "europe/berlin": timezone data cannot be found

```

```
root@:26257/defaultdb> set time zone 'Europe/Berlin';
pq: invalid value for parameter "timezone": "'Europe/Berlin'"
DETAIL: cannot find time zone "Europe/Berlin": timezone data cannot be found
root@:26257/defaultdb>
```

**Comment by pungggi** [comment]
Hi @pmneo  did you find a solution?

**Comment by pmneo** [comment]
@pungggi unfortunately, no. It seems that just few people are interessted in running this on windows ...

**Comment by pungggi** [comment]
@pmneo my quick 'fix' ist to change the timezone of the machine to UTC.. 🥇 👎

**Comment by knz** [comment]
@pmneo @pungggi See the answer above at https://github.com/cockroachdb/cockroach/issues/31297#issuecomment-429315943

1) the time zone is case snesitive. The solution is `Europe/Berlin` or `Asia/Kolkata`

2) the time zone names are different depending on the OS. The names `Europe/Berlin` and `Asia/Kolkata` will work on Linux/macOS but not on windows.

**Comment by pmneo** [comment]
@knz have you read my post https://github.com/cockroachdb/cockroach/issues/31297#issuecomment-430244362 ?

'Europe/Berlin' is no solution for that problem under windows:
root@:26257/defaultdb> set time zone 'Europe/Berlin';
pq: invalid value for parameter "timezone": "'Europe/Berlin'"
DETAIL: cannot find time zone "Europe/Berlin": timezone data cannot be found
root@:26257/defaultdb>

**Comment by knz** [comment]
Have you read my answer? 

> the time zone names are different depending on the OS. The names Europe/Berlin and Asia/Kolkata will work on Linux/macOS but not on windows.

**Comment by pmneo** [comment]
yes, but you have not told me which is the correct one. I have tried Europe/Berlin and europe/berlin ...

**Comment by knz** [comment]
Have you tried "CET"? That's the standard zone name. I am not sure windows support city-based zone names at all.

**Comment by pungggi** [comment]
root@:26257/defaultdb> set time zone CET;
pq: invalid value for parameter "timezone": "'cet'"
DETAIL: cannot find time zone "cet": timezone data cannot be found

**Comment by knz** [comment]
@BramGruneir can you have a quick look? Is Go unable to load named timezones on windows whatsoever?

**Comment by knz** [comment]
@pungggi in the meantime please create as separate issue. This issue about timezones on Ubuntu. We're having an unrelated conversation now.

**Comment by pungggi** [comment]
Already opened #32415
