### ISSUE TITLE
sql: array pgwire encoding broken

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#31315]
`SELECT ARRAY[e'\x01']` appears to be broken when it gets encoded over pgwire. It definitely differs from what postgres returns (with the text format). Examining how pgx encodes arrays (https://github.com/jackc/pgx/blob/master/pgtype/text_array.go#L214) it seems that we overly encode non-graphical runes.

**Comment by knz** [comment]
@mjibson did you not fix this in your recent PR?

**Comment by mjibson** [comment]
Closed by #32144
