### ISSUE TITLE
server/ui: login failing with 503

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#31338]
On master I generated some certs and started up a secure server (on debian). Connecting to localhost:8080 works (with the expected untrusted cert warnings). Login UI shows. I enter a valid u/p. The chrome debugger says that /login returned a 503 error. The response data is kind of garbled (protobuf encoding?) but has some text in it:

`all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: authentication handshake failed: io: read/write on closed pipe"`

I don't think this has anything to do with the cert itself because when I hacked in a valid let's encrypt cert it (that chrome accepted without prompt) the same thing happens.

**Comment by mberhault** [comment]
That is odd. Can you confirm real quick whether you're seeing any issues with the following:
- connecting to `127.0.0.1`
- connecting to SQL
- using a different browser

I could see some odd issues with untrusted certs, but definitely not once the Let's Encrypt ones are installed.

Do you have anything interested configured on your machine? SELinux, odd networking, etc...?

**Comment by mberhault** [comment]
And just to make sure: this also occurs on master without your changes? How are you testing the Let's Encrypt certs, you'd have to use a publicly-resolvable address for that.

**Comment by mjibson** [comment]
127.0.0.1 connection is the same. Using firefox exhibited the same behavior. SQL connection with SSL certs works as expected.

One interesting thing is that the very first time I tried to log in it took about 5 seconds to fail. Each login attempt after that failed instantly. The error message combined with the one-time delay suggests that there is some connection pool that fills up in an error loop or something.

This all happened on master with certs generated from our cli tool. No letsencrypt certs or modifications to cockroach.

**Comment by mberhault** [comment]
uh. odd. Are you starting the node with default `--host` or specifying one? Can you try with `--host=127.0.0.1`, that would get around any odd DNS/networking issues talking to itself.

Beyond that, best I can recommend is more verbose logging and starting from scratch every time just to make sure. When you have a minute, can you list all steps (from cert generation to `start`) and basic environment information.

**Comment by mjibson** [comment]
`--host 127.0.0.1` didn't change anything, and I wasn't specifying one before. The initial delay is closer to 15s.

Logs show:

`W181018 00:45:49.060578 32 vendor/google.golang.org/grpc/clientconn.go:1293  grpc: addrConn.createTransport failed to connect to {127.0.0.1:26257 0  <nil>}. Err :connection error: desc = "transport: authentication handshake failed: io: read/write on closed pipe". Reconnecting...`

I kinda think this is a grpc-related bug.

**Comment by knz** [comment]
Folding into #42828 which has the root cause.
