### ISSUE TITLE
Update log errors to info 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#31373]
Make these errors into info or clarify why they are actually errors

```
2018-10-15 15:51:58    ERROR    
[n1,replicate,s1,r55/1:/Table/5{4/1/1247…-6}] raft status not initialized
```

```
2018-10-15 15:51:58    ERROR    
[n1,replicate,s1,r24/1:/Table/53{-/1/0/0}] change replicas of r24 failed: descriptor changed: [expected] r24:/{Table/53-Max} [(n1,s1):1, (n3,s3):2, (n4,s4):3, (n6,s6):4, next=5, gen=0] != [actual] r24:/{Table/53-Max} [(n1,s1):1, (n3,s3):2, (n6,s6):4, next=5, gen=0]: unexpected value: raw_bytes:"\354\\\206\261\003\010\030\022\001\275\032\002\377\377\"\006\010\001\020\001\030\001\"\006\010\003\020\003\030\002\"\006\010\006\020\006\030\004(\005" timestamp:<wall_time:1539618718754264951 >
```

```
2018-10-15 15:51:59    ERROR    
[n1,replicate,s1,r604/1:/Table/60/1/{353/3/…-409/1/…}] no removable replicas from range that needs a removal: [raft progress unknown]
```

```
2018-10-15 17:43:34    ERROR    
[n1,replicate,s1,r26/1:/{Table/56-Max}] [n1,s1,r26/1:/{Table/56-Max}]: can't set pending snapshot index to 1; pending snapshot already present: 10
```

[cockroach.log](https://github.com/cockroachdb/cockroach/files/2480024/cockroach.log)

**Comment by tschottdorf** [comment]
```
func (r *Replica) setPendingSnapshotIndex(index uint64) error {
	r.mu.Lock()
	defer r.mu.Unlock()
	// We allow the pendingSnapshotIndex to change from 0 to 1 and then from 1 to
	// a value greater than 1. Any other change indicates 2 current preemptive
	// snapshots on the same replica which is disallowed.
	if (index == 1 && r.mu.pendingSnapshotIndex != 0) ||
		(index > 1 && r.mu.pendingSnapshotIndex != 1) {
		return errors.Errorf(
			"%s: can't set pending snapshot index to %d; pending snapshot already present: %d",
			r, index, r.mu.pendingSnapshotIndex)
	}
	r.mu.pendingSnapshotIndex = index
	return nil
}
```

there's something to investigate there if it fires.

**Comment by petermattis** [comment]
I'll take a look. I haven't touched anything in this area of the code in a long time, and this is the first I've heard of this log message firing regularly.

@awoods187 Can you describe what you did to produce the `can't set pending snapshot index to 1` error?

**Comment by tschottdorf** [comment]
I'm seeing it just running tpccbench-nodes-6-cpu-16-partition.

**Comment by awoods187** [comment]
It's all over the clusters in #31409 . Basically reproducible at will

**Comment by petermattis** [comment]
@tschottdorf thanks.

**Comment by tschottdorf** [comment]
(while loading the fixtures)

**Comment by petermattis** [comment]
> Basically reproducible at will

No harm in being explicit, though I think I have enough to go on with running `tpccbench-nodes-6-cpu-16-partition`.

**Comment by awoods187** [comment]
Sounds good

**Comment by tschottdorf** [comment]
I'm also seeing

> E181017 13:46:30.667856 106642 storage/queue.go:791  [n5,replicate,s5,r22468/3:/Table/61/1/4{585/18…-627/61…}] no removable replicas from range that needs a removal: [raft progress unknown]

in this setup, so it's presumably pretty common as well.

**Comment by tschottdorf** [comment]
^- @a-robinson it looks like we'd get this error every time the replicate queue is running on a leaseholder that's not the Raft leader (as in that case no progress will be supplied). Is that accurate and if so, does that imply that the replicate queue doesn't properly downreplicate when the leaseholder and raft leader are not colocated?

**Comment by tschottdorf** [comment]
Oh, I'm actually also seeing that error with a raft group that has progress:

> E181017 13:46:25.706332 106463 storage/queue.go:791  [n5,replicate,s5,r22420/3:/Table/61/1/4{584/14…-627/61…}] no removable replicas from range that needs a removal: [1:0, 2:0, 3*:11, 4:0]

**Comment by awoods187** [comment]
All of the above errors in the top of the issue were observed by me in the various permutations of #31409. That's what prompted me to create the issue as various core team members told me that these were not useful in debugging what was going on.

**Comment by petermattis** [comment]
```
I181017 13:20:25.881254 2301 storage/replica_command.go:300  [n1,s1,r17637/1:/Table/61/1/29{59/37…-79/82…}] initiating a split of this range at key /Table/61/1/2959/37035/0 [r17660]
I181017 13:20:25.926924 2301 storage/store_snapshot.go:615  [n1,s1,r17660/1:/Table/61/1/29{59/37…-79/82…}] sending preemptive snapshot 09fc1509 at applied index 10
I181017 13:20:25.927190 2301 storage/store_snapshot.go:657  [n1,s1,r17660/1:/Table/61/1/29{59/37…-79/82…}] streamed snapshot to (n6,s6):?: kv pairs: 8, log entries: 0, rate-limit: 2.0 MiB/sec, 1ms
I181017 13:20:25.929719 2301 storage/replica_command.go:816  [n1,s1,r17660/1:/Table/61/1/29{59/37…-79/82…}] change replicas (ADD_REPLICA (n6,s6):4): read existing descriptor r17660:/Table/61/1/29{59/37035/0-79/82838} [(n1,s1):1, (n3,s3):2, (n5,s5):3, next=4, gen=0]
E181017 13:20:25.934301 301696 storage/queue.go:791  [n1,replicate,s1,r17660/1:/Table/61/1/29{59/37…-79/82…}] [n1,s1,r17660/1:/Table/61/1/29{59/37…-79/82…}]: can't set pending snapshot index to 1; pending snapshot already present: 10
I181017 13:20:25.951298 2301 storage/replica.go:3902  [n1,s1,r17660/1:/Table/61/1/29{59/37…-79/82…}] proposing ADD_REPLICA((n6,s6):4): updated=[(n1,s1):1 (n3,s3):2 (n5,s5):3 (n6,s6):4] next=5
I181017 13:20:25.953309 2301 storage/replica_command.go:816  [n1,s1,r17660/1:/Table/61/1/29{59/37…-79/82…}] change replicas (REMOVE_REPLICA (n3,s3):2): read existing descriptor r17660:/Table/61/1/29{59/37035/0-79/82838} [(n1,s1):1, (n3,s3):2, (n5,s5):3, (n6,s6):4, next=5, gen=0]
I181017 13:20:25.975080 2301 storage/replica.go:3902  [n1,s1,r17660/1:/Table/61/1/29{59/37…-79/82…}] proposing REMOVE_REPLICA((n3,s3):2): updated=[(n1,s1):1 (n6,s6):4 (n5,s5):3] next=5
I181017 13:20:31.760905 2301 storage/replica_command.go:300  [n1,s1,r17660/1:/Table/61/1/29{59/37…-79/82…}] initiating a split of this range at key /Table/61/1/2960/41000 [r17683]
```

Here is an example of the `can't set pending snapshot index` error. We see `r17660` being created in the first message, and then very quickly the same goroutine (`2301`) which performed the split is adding a replica. While this is happening, the replicate queue picks up `r17660` and tries to do something and hits this error. So perhaps this is expected if we have an `AdminChangeReplicas` or `AdminScatter` occur concurrently with the replicate queue. I'm going to do some more digging to make sure this is what is going on, but if it is, this message could either be elided or logged at Info level.

**Comment by petermattis** [comment]
The logs show a ton of splits and change replicas occurring on goroutine `2301`. I think the explanation for this is the `splitAndScatter` loop in `ccl/backupccl/restore.go`. If the requests hit the local node, they will stay on the same goroutine. I'm going to to tweak the log context to make this clearer and try and reproduce this problem.

**Comment by petermattis** [comment]
> Is that accurate and if so, does that imply that the replicate queue doesn't properly downreplicate when the leaseholder and raft leader are not colocated?

That's accurate. We don't want to accidentally remove a range which is a necessary part of quorum. The leaseholder is not leader situation should resolve itself shortly. We don't need that log message to be an error in that case.

**Comment by petermattis** [comment]
>  I think the explanation for this is the `splitAndScatter` loop in `ccl/backupccl/restore.go`. 

Additional logging shows this is exactly what is happening. The `splitAndScatter` works are quickly splitting and scattering ranges. If the `replicate` queue concurrently tries to rebalance a replica we hit the `can't set pending snapshot index` error. So this log message is innocuous. Only difficulty is figuring out how to remove it. Currently, queue errors are both count in the queue failures statistics and are log as errors. Should this scenario be considered an error for the failure metric?

**Comment by tschottdorf** [comment]
I have a WIP that allows marking some errors from queues as "benign" which makes them not logged (as errors) nor counted in the queue failure counter. Not polished yet, but it's on https://github.com/tschottdorf/cockroach/tree/repro/tpcc-31409.

Not sure if that's the right approach, but short of passing a bool all the way up I don't have a better idea.

**Comment by petermattis** [comment]
Marking certain errors as benign sounds reasonable. I had considered and dismissed trying to pass a boolean up. We already have a precedent for marking errors like this in the form of `purgatoryError`.

**Comment by tschottdorf** [comment]
Here's another error:

> E181022 12:40:35.679092 26 jobs/registry.go:303  error while adopting jobs: adopt-job: could not register flowID {{[189 104 48 119 204 155 74 219 158 52 28 172 98 138 217 152]}} on node 0 because the registry is draining

cc @jordanlewis

**Comment by jordanlewis** [comment]
cc @asubiotto

**Comment by asubiotto** [comment]
That error occurs when a we try to plan a query on a node but when we attempt to set the flow up, the target node is draining. From a general perspective, this should be kept as an error because it would be surfaced back to the user when running a normal query. However, maybe this could be logged as info and retried from an adopt jobs perspective?

**Comment by tbg** [comment]
Another one:

> I181126 09:15:17.771588 1125 storage/split_queue.go:213  [n1,split,s1,r7/1:/Table/{SystemCon…-11}] initiating a split based on load at key /Table/3/1/1/2/1
E181126 09:15:17.771651 1125 storage/queue.go:837  [n1,split,s1,r7/1:/Table/{SystemCon…-11}] unable to split [n1,s1,r7/1:/Table/{SystemCon…-11}] at key /Table/3/1/1/2/1: cannot split range at key /Table/3/1/1/2/1

This also registers as a failure in the split queue. This happens during initial cluster start in import/tpch/nodes=4 before the restore portion does anything interesting, so I suspect it's an automatically computed split key, where I wonder why it would result in one that we can't actually split at.

**Comment by tbg** [comment]
181129 10:12:41.044435 176 storage/allocator.go:625  [n9,replicate,s6,r12/5:/Table/1{5-6}] simulating RemoveTarget failed: must supply at least one candidate replica to allocator.RemoveTarget()

**Comment by irfansharif** [comment]
(Pretending to be the frozen issue bot).
