### ISSUE TITLE
storage: batch raft message to reduce the number of network IO invoking

### ISSUE THREAD

**Issue by veteranlu** [cockroachdb/cockroach#3138]
While I run writeonly test, I find that `syscall.Syscall` is the top 3 sum cpu time function from pporf. The function stack as follow: `rpc.(*server).sendResponses` -> `bufio.(*writer).flush` -> `net.(*conn).Write` -> `syscall.Write` -> `syscall.Syscall`.

I also find there are more than 10 raft messages in the channel of `ch` in function `func (t *rpcTransport) processQueue(raftNodeID proto.RaftNodeID)`, so Can we batch the raft message to reduce the number of rpc? however we should pay attention with some execptions. such as:

* the max size of batch should not bigger than MTU
* snapshot raft message should be sent at once, since its data size is very big.

**Comment by tamird** [comment]
@veteranlu since you reported this issue, the raft RPC system has moved to a streaming grpc service.

Would you mind rerunning your tests and reporting your findings? Your help is appreciated!

**Comment by petermattis** [comment]
In addition to using GRPC, we recently started explicitly batching Raft messages. See #9485.

I don't think there is anything left to do here.
