### ISSUE TITLE
sql: Better error checking in logic test parser

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#3139]
One of the typos fixed in #3135 was in a test data file instead of a comment. A typo like this should have caused the test to fail.

https://github.com/cockroachdb/cockroach/pull/3135/files#diff-582e89cbf57e76e4dab72fc86b31e67aR136

**Comment by petermattis** [comment]
The logic test runner currently skips over commands it doesn't recognize. Should be straightforward to make it recognize and ignore any unimplemented commands. Be sure to run `make -C sql` to run the full logic test suite.

**Comment by tschottdorf** [comment]
fixing this also deals with #2867.

**Comment by tamird** [comment]
@nvanbenschoten should this be closed now?

**Comment by nvanbenschoten** [comment]
Yep, both of these are all set for now
