### ISSUE TITLE
ui: jobs page: handle API call errors

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#31396]
**Describe the problem**

I'm reproing https://github.com/cockroachdb/cockroach/issues/31094#issuecomment-429793161 on 10/08 beta. It was taking a while so I went to the adminui and saw the screenshot below. I then went to the sql shell and ran show jobs.

```
root@localhost:26257/defaultdb> show jobs;
        job_id       |   job_type    |                            description                             | user_name | status  |             created              |             started              | finished |             modified             | fraction_completed | error | coordinator_id  
+--------------------+---------------+--------------------------------------------------------------------+-----------+---------+----------------------------------+----------------------------------+----------+----------------------------------+--------------------+-------+----------------+
  391774989978042369 | SCHEMA CHANGE | CREATE INVERTED INDEX ix_vehicle_ext ON movr.public.vehicles (ext) | root      | running | 2018-10-15 19:10:37.747692+00:00 | 2018-10-15 19:10:48.879045+00:00 | NULL     | 2018-10-15 19:11:07.780042+00:00 |                  0 |       |           NULL  
(1 row)

Time: 2m20.308769578s
```

It took a long time for show jobs to finish. Once it finished, the admin ui functioned again.

**To Reproduce**

Same repro as https://github.com/cockroachdb/cockroach/issues/31094#issuecomment-429793161

**Additional data / screenshots**
![image](https://user-images.githubusercontent.com/22278911/46972696-1d93ed00-d08d-11e8-90ae-7e1aa6653083.png)
![image](https://user-images.githubusercontent.com/22278911/46972824-7feced80-d08d-11e8-848c-b5979bad48ca.png)

**Environment:**
 - CockroachDB version 2.1 beta 1008

Logs
[cockroach.log](https://github.com/cockroachdb/cockroach/files/2480200/cockroach.log)

**Comment by benesch** [comment]
I don't think there's a bug in the admin UI here. All the admin UI does is run `SHOW JOBS` and show you the results on the web. If `SHOW JOBS` isn't working, neither will the admin UI. It sounds like something about movr is overloading your cluster to the point that it can't even execute `SHOW JOBS`.

Did you expect that something different would happen?

**Comment by awoods187** [comment]
I expected it to say in-progress. It looks like its hung and I wouldnt know if it was broken or slow.

**Comment by benesch** [comment]
The problem is neither does the admin UI. It's in general impossible to know whether something will complete if you give it another, say, 10s, or if it's good and permanently wedged.

**Comment by awoods187** [comment]
yeah but i think the experience of in-progress to ultimately failing is better than the experience of it looks like its failing but it ultimately succeeds. We could have a simple heuristic that checks the in-progress after a period of time and if no progress is made errors out. Not sure what the right answer here is it just felt very unexpected in the context of a web user. CC @piyush-singh for his input

**Comment by awoods187** [comment]
Could we say in progress with the spinner? Should we?

**Comment by awoods187** [comment]
<img width="457" alt="screen shot 2018-10-17 at 11 38 25 pm" src="https://user-images.githubusercontent.com/22278911/47130056-df9df100-d265-11e8-9976-72ceb3bd7f8c.png">
Just hit this when looking at my cluster this evening
