### ISSUE TITLE
Cockroach failed to start on fedora 28 because of missing shared libraries libncurses.so.5

### ISSUE THREAD

**Issue by vibolvireak** [cockroachdb/cockroach#31418]
**Describe the problem**

`$ cockroach start --insecure`
> cockroach: error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory

**To Reproduce**

Ruing `$ cockroach start --insecure` in Fedora 28

**Environment:**
 - CockroachDB version [e.g. 2.0.6]
 - Server OS: [e.g. Linux/Fedora 28]

**Remark**
in side `/lib64` only **libncurses.so.6** and **libncurses.so.6.1**

**Comment by knz** [comment]
Thanks you need to install the package `ncurses-compat-libs`

I think `dnf install ncurses-compat-libs` or `yum install ncurses-compat-libs`

Can you confirm this works?

**Comment by vibolvireak** [comment]
dnf install ncurses-compat-libs solved everything.
