### ISSUE TITLE
sql: allow the direction (ADD/DROP) of schema changes to be changed inflight

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#3142]
https://github.com/cockroachdb/cockroach/pull/3136 adds processing of schema changes through mutations. The processing of these mutations will be broken up into steps and run asynchronously in a subsequent change. We do not allow a new schema change to be introduced on the same element (column/index) while another schema change on that element is inflight. Allowing that shouldn't be a big deal, but it's best done in another PR.

**Comment by spencerkimball** [comment]
@vivekmenezes thoughts on this?

**Comment by vivekmenezes** [comment]
Nice to have but given other priorities moved to later.

**Comment by vivekmenezes** [comment]
closing in favor of #16018
