### ISSUE TITLE
Can't connect to 12 node cluster

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#31461]
**Describe the problem**
I saw some unexpected tpc-c results:

`_elapsed_______tpmC____efc__avg(ms)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
  600.0s    18543.4  77.1%   5329.6   4026.5   9663.7  13421.8  31138.5 103079.2
--- FAIL: tpcc 1871 resulted in 18543.4 tpmC (78.6% of max tpmC)`

This should be ~6000 warehouses 

Then I went to check on the cluster and I can't connect to the adminui of my 12 node cluster that ran tpcc 

**To Reproduce**
Use roachtest from two days ago

Change test to:
@@ -675,11 +675,12 @@ func registerTPCCBench(r *registry) {
                        // StoreDirVersion: "2.0-5",
                },
                {
-                       Nodes: 3,
+                       Nodes: 24,
                        CPUs:  16,
 
-                       LoadWarehouses: 2000,
-                       EstimatedMax:   1300,
+                       LoadWarehouses: 20000,
+                       EstimatedMax:   12000,
+                       LoadConfig:     singlePartitionedLoadgen,

Run:
`bin/roachtest bench '^tpccbench/nodes=12/cpu=16/partition$$' --wipe=false --user=andy`

**Expected behavior**

**Additional data / screenshots**

**Environment:**
 - CockroachDB version 2.1 beta 10/08

**Additional context**
andy-1539640724-tpccbench-nodes-12-cpu-16-partition

**Comment by tschottdorf** [comment]
Same as in #31460, all nodes seem to have been shut down.

Both here and there, I see

> [12477.174011] TCP: request_sock_TCP: Possible SYN flooding on port 26257. Sending cookies.  Check SNMP counters.

in the logs. I'm not sure this means much, but I doubt we want that message to show up and should investigate further.

I assume this will reproduce easily. I'll send PRs to add one of these configurations to roachtest (I wonder why it's not already there).

**Comment by tschottdorf** [comment]
Going to fold this into #31460, it's unlikely that there are two separete things going on here and we can just test both.

**Comment by tschottdorf** [comment]
@awoods187 you changed Nodes to 12 here, not 24, right?

**Comment by awoods187** [comment]
Yeah I just fixed this to show it was 12 nodes
