### ISSUE TITLE
Non-serializable behavior in TestConcurrentIncrements

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#3148]
https://circleci.com/gh/cockroachdb/cockroach/9401

```
I1117 00:12:48.817836 865 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
	driver_test.go:483: unexpected max: 1
	driver_test.go:486: unexpected sum: 2
 ```

That is, both records are ending up with the value 1, instead of one being 1 and the other being 2.

**Comment by petermattis** [comment]
That's not good. Has anyone else seen this? Is it repeatable?

**Comment by tschottdorf** [comment]
My first candidate for something like this is always not properly propagating the response transaction properly to the next request. I'll look into it this week, and am going to start a stress test locally to see whether I can repeat it.

**Comment by bdarnell** [comment]
I can reproduce this on about 1 in 200 runs using `make stress PKG=./sql/driver`. It does not reproduce when I narrow the test to `make stress PKG=./sql/driver TESTS=TestConcurrentIncrement`.

**Comment by tschottdorf** [comment]
interestingly, the very first invocation (within the five of the test) failed, and it appears to have had the split take part in the middle of it. All the other 50 iterations in this run (I upped it from `5`) are exactly as expected. So my money, for now, is on losing something about the timestamp cache on the split, but I'm going to investigate further.

```
15:50:44.551441 31526 server/server.go:206  starting https server at 127.0.0.1:58835
15:50:44.584843 31526 multiraft/multiraft.go:959  node 1 campaigning because initial confstate is [1]
15:50:44.591928 31526 storage/split_queue.go:98  splitting range=1 [/Min-/Max) at keys [/Table/1000]
15:50:44.593026 31526 storage/replica_command.go:1238  initiating a split of range=1 [/Min-/Max) at key /Table/1000
15:50:44.605278 31526 multiraft/multiraft.go:959  node 1 campaigning because initial confstate is [1]
15:50:44.605461 31526 storage/replica_command.go:1166  range 2: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC +1447793445.605s
15:50:44.605549 31526 storage/split_queue.go:98  splitting range=2 [/Table/1000-/Max) at keys [/Table/1001]
15:50:44.606957 31526 storage/replica_command.go:1238  initiating a split of range=2 [/Table/1000-/Max) at key /Table/1001
15:50:44.613934 31526 sql/driver/driver_test.go:433  ___________________________________________________________
15:50:44.613989 31526 sql/driver/driver_test.go:441  === 1: BEGIN
15:50:44.619074 31526 sql/driver/driver_test.go:456  === 1: SELECT 0
15:50:44.641979 31526 sql/driver/driver_test.go:441  === 0: BEGIN
15:50:44.642950 31526 sql/driver/driver_test.go:456  === 0: SELECT 0
15:50:44.649129 31526 multiraft/multiraft.go:959  node 1 campaigning because initial confstate is [1]
15:50:44.649780 31526 storage/replica_command.go:1166  range 3: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC +1447793445.649s
15:50:44.662592 31526 sql/driver/driver_test.go:470  === 0: UPDATE 1
15:50:44.667489 31526 sql/driver/driver_test.go:472  === 0: COMMIT: <nil>
15:50:44.667580 31526 sql/driver/driver_test.go:470  === 1: UPDATE 1
15:50:44.672090 31526 sql/driver/driver_test.go:472  === 1: COMMIT: <nil>
```

**Comment by tschottdorf** [comment]
I've since repro'ed this a couple of times and it's always the same sequence of commands and same leader lease message between the selects and updates. Should be able to track this down that way.
For anyone interested, [this branch](https://github.com/cockroachdb/cockroach/compare/master...tschottdorf:repro_3148) exacerbates reproducibility.

**Comment by tschottdorf** [comment]
it's definitely reads hitting the response cache while the splitTrigger is running. I'm still cleaning up some bugs in my other branches but for all intents and purposes this is under control, though we'll need some refactoring to avoid another locking hell.
