### ISSUE TITLE
ui: badge jobs icon to show count of in-progress jobs

### ISSUE THREAD

**Issue by vilterp** [cockroachdb/cockroach#31507]
Users coming to the admin UI are curious about job status; this would quickly let them know that some are running without requiring them to click on the page to find out.

Put together this [design](https://www.figma.com/file/EbR3Dw4vZbJaK7W8IbDlgJ7w/Jobs-Badge?node-id=0%3A1) (cc @josueeee):
![frame](https://user-images.githubusercontent.com/7341/47036183-e899a000-d149-11e8-898e-f5e347953b86.png)

In terms of fetching the data, it seems you'd need
- An endpoint that does something like `SELECT count(*) FROM system.jobs WHERE state = 'IN_PROGRESS'`
- To poll this every few seconds from the Admin UI

We already poll the liveness and nodes endpoints every minute; would be nice not to just add another poll, but short of introducing some kind of websocket I'm not sure what else to do.

Might be another good starter project for @celiala (cc @couchand)

**Comment by josueeee** [comment]
LGTM

**Comment by piyush-singh** [comment]
Have a few comments/questions about UX here:

- Do users always see this when jobs are running? Do we ever dismiss these notifications? For example, after they navigate to the jobs page will we still show them the red notifications for the remainder of the job duration?
- If we do keep these notifications up, they might persist for very long running jobs like schema changes or restores which can take hours, it might be frustrating to not be able to dismiss the notification
- Dismissing the notification after viewing the page could be simple (keep it at the session level; if you close the window and come back they might reappear) for a first pass if we opt for it
- Are we tying the notification to the running jobs in any way? It might be confusing if a user sees a red circle with a number and then navigates to a page and sees a list of jobs (some of which are running) without any indication as to what the red circle was alerting them about. Something small like a red dot  next to running jobs or just some text that says "you have <number> jobs running" with the number in red might be enough.

**Comment by vilterp** [comment]
> Do users always see this when jobs are running? Do we ever dismiss these notifications? For example, after they navigate to the jobs page will we still show them the red notifications for the remainder of the job duration?

I was thinking there would be no way to dismiss; it would always just show the number of jobs currently in progress, on all pages.

> very long running jobs like schema changes

True, could be annoying.

> Something small like a red dot next to running jobs

I think running jobs are fairly prominent, since they have blue progress bars. Having something of the same color would be good though. Maybe the badge should be blue like the progress bars, not red.

Overall, I was thinking of this as just an informative count, not a notification that needs to be dismissed. Blue would probably be good to make it seem less urgent.

**Comment by piyush-singh** [comment]
I think the color change would definitely make this feel less like a notification and more like some extra info. That mostly addresses my concerns above.
