### ISSUE TITLE
perf: Investigate tpcc performance differentials with no barrier on/off 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#31505]
I've recently observed as much as a 35% difference in no barrier on/off behavior on tpc-c 3 node tests. We should understand why this difference occurs and see if we can work to eliminate the difference.

**Comment by nvanbenschoten** [comment]
We've seen nobarrier have much less of an effect on AWS than on GCE. One theory is that this is related to NVMe, which we use with AWS but not GCE. We should test GCE with NVMe and see whether that makes any difference.

**Comment by m-schneider** [comment]
To add more context here. When running the new cockroach IO benchmark we saw that nobarrier on GCE sped up performance by 6X and only by 25% on AWS. I'll rerun the cockroach test with NVMe and see if that shows as much of a difference. Then which variant of TPCC do you think it would make sense to run?

**Comment by nvanbenschoten** [comment]
> To add more context here. When running the new cockroach IO benchmark we saw that nobarrier on GCE sped up performance by 6X and only by 25% on AWS.

That's very interesting. There definitely seems to be something else going on there.

> Then which variant of TPCC do you think it would make sense to run?

I don't think we should immediately run TPC-C to do this comparison - there's too much going on. Let's start with `kv0` and `kv95`.

**Comment by awoods187** [comment]
I'm closing this issue because I think we understand `no barrier` better now and recognize that it will make a performance benefit consistently
