### ISSUE TITLE
Please change name.

### ISSUE THREAD

**Issue by phynalle** [cockroachdb/cockroach#3151]
I'm sorry to post a issue that doesn't relate to bug.
I was interested in your cockroachdb, I become a fan of it.
I wanted to know more information of it, I tried to google it. However, unluckily, I missed the spell 'db', the results made me shocked. Images of cockroach appeared.
I know your intention to name like this. you might hoped the database would be strong, durable, and resistant against unstable environment. but I think the name was the result of overaction.
Somebody may say that i am insectist, or think I'm just kidding. but i'm really serious.

**Comment by spencerkimball** [comment]
Like most things in life, if what you're doing doesn't generate a reaction, nobody pays attention. There are a lot of databases out there and it can be difficult for people who don't have enough time to fully understand the differences and follow up with the subset which do what they want. We think we're building the right set of capabilities and the name is not only evocative (as you say), but it grabs attention and focuses it.

Thank you for your comment; I'm sure there will be many others with similar reservations. But as long as the reaction is mostly favorable, we're going to keep the name as is.

**Comment by cup** [comment]
https://github.com/cockroachdb/cockroach/issues/13634
https://github.com/cockroachdb/cockroach/issues/2677

https://github.com/cockroachdb/cockroach/issues/3151
