### ISSUE TITLE
exec: implement execgen for columnarizer functions and arithmetic select/project ops

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#31518]
The tight loops in `sql/distsqlrun/columnarizer.go` are prime for templatization - they're all the same but the types.

Same with the select and project ops from exectoy.

This issue tracks getting an `execgen` templating machinery going in the Makefile, as well as implementing templated versions of the above.

**Comment by solongordon** [comment]
Implemented by #31554 and #31892.
