### ISSUE TITLE
ui: custom chart page: show descriptions from metric metadata endpoint

### ISSUE THREAD

**Issue by vilterp** [cockroachdb/cockroach#31521]
The current custom graph page doesn't have much in the way of documentation or labelling for metrics:

![image](https://user-images.githubusercontent.com/7341/47046357-e8f26500-d162-11e8-88a8-f92722a3033e.png)

But the info we need exists, since each metric is declared along with a unit and description, e.g.:

https://github.com/cockroachdb/cockroach/blob/526a947cc107b10f61d0d5ae24db30d281d9c3f7/pkg/sql/exec_util.go#L189-L194

This information is exposed via the `MetricMetadata` endpoint:

https://github.com/cockroachdb/cockroach/blob/2f65f192b76df8b1371603fc7e7231969528b964/pkg/server/serverpb/admin.proto#L814-L819

The custom graph page could hit this endpoint on mount, and use the `Help`, `Measurement`, and `Unit` fields to label and configure the graph.

cc @sploiselle @Amruta-Ranade (re docs integration) @couchand

**Comment by Amruta-Ranade** [comment]
Yes..I remembering discussing this with @couchand a few weeks ago..the idea was to make the doc descriptions understandable/user-friendly and then update the code descriptions as well. Not sure if that's the thing you are referring to, but JFYI.

**Comment by Annebirzin** [comment]
@piyush-singh adding designs for metric descriptions on custom charts here: https://zpl.io/VKQxz86

<img width="1094" alt="Screen Shot 2019-11-12 at 10 56 17 AM" src="https://user-images.githubusercontent.com/51920721/68692225-1ca8e580-0543-11ea-825a-35d65669dcaa.png">

Note: this design also includes an update to the search input (aligns with the statement search input component that Vlad worked on here #41537). This could be broken out into a separate issue if needed.

**Comment by Koorosh** [comment]
FYI: Currently, there is many fields with missing **help** description in metadata. It might be needed to review and update them as @Amruta-Ranade mentioned.

If needed, I can provide a full list of metrics with missing descriptions.

![Screenshot 2019-11-19 at 11 58 38](https://user-images.githubusercontent.com/3106437/69137970-7589f800-0ac6-11ea-8591-9a7956af5c04.png)

**Comment by dhartunian** [comment]
Closing this issue as the PR has been merged.
