### ISSUE TITLE
sql: age column in show trace for session output has octal escape sequences

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#31528]
`show trace for session` shows, in the age col, things like `2s834ms688\302\265s200ns`. I don't know what's going on there in the middle but it sure ain't pretty.
cc @knz in case you happen to know anything that might help.

**Comment by andreimatei** [comment]
The type of that column appears to be `interval`.

**Comment by knz** [comment]
This is a CLI issue, lib/pq specifically. We have another issue filed to fix this already. Was hoping to look at this soon.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by andreimatei** [comment]
All yours, my friend.

**Comment by knz** [comment]
Dup #28756
