### ISSUE TITLE
ui: easy links from one node's admin UI to another one's

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#31564]
For some debug pages, you want to be on a specific node (e.g. logspy). It'd be really cool if the admin UI would let me jump from a node to another, or at least if it printed (all?) the IPs of all the node's so that I can construct the URL by hand.

Particularly with roachprod clusters, it's not trivial to go from a node id to an IP - the order of nodes does not generally correspond to the order of machines in the roachprod cluster.
Anything you can give me here, I'll take.

**Comment by vilterp** [comment]
Related to #31540

**Comment by couchand** [comment]
It would be really cool.  Unfortunately there's an awful lot outside our control, we can't necessarily construct the correct URL with the information we have at hand.

However, we could make a best-effort attempt by making the assumption that the same hostname that has the RPC port open has the HTTP port open.  This is good enough for a debug page.

**Comment by Annebirzin** [comment]
@elkmaster @piyush-singh Here is a link to designs for adding node links in the Advanced Debug page. Let me know if you think this works: https://zpl.io/adGNv9E

**Comment by andreimatei** [comment]
@nkodali did you not like this, or did something happen here? I'm constantly finding myself wanting this.

**Comment by andreimatei** [comment]
Reopening this, but please tell me if I'm wrong.

**Comment by dhartunian** [comment]
I think https://github.com/cockroachdb/cockroach/pull/72659 satisfies this need
