### ISSUE TITLE
sql/ui: expose traces in a more machine-readable format for viz

### ISSUE THREAD

**Issue by vilterp** [cockroachdb/cockroach#31562]
Users want to look at traces, but not everyone has Jaeger set up. Some kind of trace viewer could be built into the Admin UI as a debug page, but a shorter-term solution is to make a freestanding site like the DistSQL plan viewer that can be used to view traces. I wrote simple viewer we can use here: https://github.com/vilterp/dist-tracing-view

A trace is probably too much data to put into a URL like `EXPLAIN (DISTSQL)` does, so I was envisioning users pasting the output of `SHOW TRACE FOR SESSION` into the site (maybe in CSV form, via `\set display_format csv`).

The `SHOW TRACE FOR SESSION` output (and the `crdb_internal.session_trace` table) make it difficult to reconstruct the trace tree because they don't have parent span ids for each span. Even if this was added, it'd still be wonky, since we'd have

```
[]tracing.RecordedSpan
=Go=> trace tree
=Go=> SQL rows (some "START SPAN", some log lines) # this is generateSessionTraceVtable: https://github.com/cockroachdb/cockroach/blob/526a947cc107b10f61d0d5ae24db30d281d9c3f7/pkg/sql/exec_util.go#L1352
=JS=> trace tree =JS=> visualization
```

It would be nice to have a syntax that prints out the trace tree directly as a big JSON blob, so we could go

```
[]tracing.RecordedSpan
=Go=> trace tree as JSON (1x1 SQL result)
=JS=> visualization
```

Or even just print out one span on each row and construct the tree on the server side:

```
[]tracing.RecordedSpan
=Go=> SQL rows (1 row per span, all log messages included)
=JS=> visualization
```

cc @andreimatei

**Comment by andreimatei** [comment]
Since a while ago, we can export traces for individual statements as Jaeger JSON files. They files instruct you on how to easily start a Jaeger docker to visualize them. There's many things we could do to make traces more accessible, but I'm gonna close this particular issue.
