### ISSUE TITLE
server: trace admin UI endpoints

### ISSUE THREAD

**Issue by vilterp** [cockroachdb/cockroach#31566]
Admin UI endpoints often do substantial work (KV reads & writes, SQL, RPCs fanning out to multiple nodes, etc), but a root spans never get created for them. (Their sub-operations still show up in the Jaeger UI, as internal executor or Batch traces). This makes it hard to debug performance problems with them.

We should add some kind of gRPC/gRPC-gateway interceptor that creates a root span for each invocation of an endpoint on the admin or status server, so we can see traces for these endpoints.

Maybe it could happen around here, when the servers are registered with gRPC gateway: https://github.com/cockroachdb/cockroach/blob/c762c4a5c835c9adc8086071d0923987f157f61c/pkg/server/server.go#L1299-L1303

**Comment by vilterp** [comment]
Note: this patch causes all RPCs (including Admin UI endpoints) to be traced: 9ddaed4023b16c3971422f28d79272fdcf319bb1 Wouldn't want to merge this (need to figure out how to make it only apply to admin ui servers), but useful for debugging.

**Comment by knz** [comment]
cc @tbg can you have this in scope for future tracing work

**Comment by tbg** [comment]
@andreimatei already fixed this in 88ff81712cb03490315e781a729f5e8e5baacec0 when addressing #34310. When tracing is globally enabled, all RPCs are traced, including those for which the AdminUI is on the other end.
