### ISSUE TITLE
ui: databases page: implement authorization

### ISSUE THREAD

**Issue by vilterp** [cockroachdb/cockroach#31569]
The databases page should only show databases and tables for which the currently-logged-in user has grants. Currently it shows everything.

There are a lot of other things in the webui that need authorization, but I think this is the most egregious one. It seems we'll largely have to do this on a case-by-case basis, to avoid breaking pages which make SQL queries that can only be run as root.

Related to #8767.

Also related to #22941 (refactoring the databases page's data fetching)

**Comment by vilterp** [comment]
I guess we'd have to add a step to the web ui login docs, so it's (1) create a user with a password _(2) grant them permission on the databases_ (3) log in.

cc @piyush-singh @Amruta-Ranade @couchand

**Comment by Amruta-Ranade** [comment]
This is for 2.2, right?

**Comment by vilterp** [comment]
Authorization is, yes.

**Comment by knz** [comment]
Fixed in  #42563.
