### ISSUE TITLE
cli: I want a way to tell the shell to not run the extra statements

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#31567]
It used to be that, when the old `smart_prompt` shell option was `\unset`, the shell would not send requests like `SHOW TRANSACTION STATUS` and `SHOW database` (and also `SHOW SYNTAX`, but this one has gotten its own option to disable in the meantime). 
This was quite nice, as any extra statement is a bummer when you're playing with tracing or automatic retries.
The new way to customize the prompt does not seem to have this effect; even if the respective placeholders are taken out of the prompt, the statements are still run.

I'm looking at the statement run with `set cluster setting sql.trace.session_eventlog.enabled=true;` and then the `/debug/events` page.

As an extra, the `SHOW TRANSACTION STATUS` statement seems to be run **twice** per real statement with the default prompt, but only once with `\set prompt1 nada>`.

**Comment by andreimatei** [comment]
Another thing - if I'd have my druthers, there'd be a single `barebones` option that disables all statements (so it'd include `\unset check_syntax`), cause otherwise it's hard to remember multiple things that you need to set to disable all magic.

**Comment by knz** [comment]
yes thanks for noticing this. This is a regression and an artifact of me not properly reviewing the prompt handling changes that went into 2.1. Will address.

**Comment by andreimatei** [comment]
Btw, if you'll be poking around, one more grievance - I personally find the message display by the prompt after a `begin`, and the fact that I have to press enter again, quite annoying:
```
Now adding input for a multi-line SQL transaction client-side.
Press Enter two times to send the SQL text collected so far to the server, or Ctrl+C to cancel.
You can also use \show to display the statements entered so far.
```

If it was up to me, I'd get rid of it altogether. I think it does more harm than good; I don't really see anyone using a "a multi-line SQL transaction client-side.". I'd also settle for the message telling you how to get rid of it.

**Comment by knz** [comment]
> I don't really see anyone using a "a multi-line SQL transaction client-side."

Happy to hear that given that both you and Ben insisted on having this feature early on (to avoid long-running open interactive SQL transactions, which can cause concurrent txns by other clients to be held up)

**Comment by andreimatei** [comment]
I doubt that I have argued for this particular shell feature, but if I did, old Andrei should be ashamed.
