### ISSUE TITLE
roachtest: tpccbench line search doesn't repartition based on active warehouses

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#31584]
The TPCC database is partitioned based on the number of warehouses, but then the test performs a line search in which it varies the active warehouses.

This means that you need to repartition every time to cleanly split in the middle of the active warehouse range. This isn't happening today, resulting in an uneven load across the partitions.

For example, a 6 node 5k warehouses cluster seems to line search its way all the way to ~1500 active warehouses since it's really just hitting the first partition (thus simulating a 3 node cluster) right now.

As a result, all the partitioned tpcc results in this test that don't match the data set's warehouse count are likely bogus (too low).

**Comment by tschottdorf** [comment]
cc @awoods187

**Comment by nvanbenschoten** [comment]
The test uses the `--active-warehouses` and `--partition-affinity` flags to avoid this exact issue. If you pass an `--active-warehouses` flag and a `--warehouses` flag, the test will determine which warehouses it needs to work on based on the `--partition` flag and the `--partition-affinity` flag. 

So for instance, with:
```
--warehouses=5000
--active-warehouses=500
--partitions=3
--partition-afinity=1 (zero-indexed)
```

an individual `workload` instance will hit warehouses 1667-2166. This is how it gets around repartitioning.

> As a result, all the partitioned tpcc results in this test that ... are too low.

I wish that was the case!

**Comment by nvanbenschoten** [comment]
Actually, @tschottdorf you ran into this with a single load generator, not in the geo-distributed case, right? I still need to convince myself that we're doing the right thing there.

**Comment by nvanbenschoten** [comment]
Yeah, we're definitely not handling the case where `partition-affinity` is omitted properly. Nice find @tschottdorf and sorry for the confusion!

I'm going to pull all of this partitioning logic out while fixing this so we can test it directly. It's become a tangled mess as more options were added.

**Comment by tschottdorf** [comment]
> Nice find @tschottdorf and sorry for the confusion!

I found out the hard way. On the plus side, I'm glad this is just a little config issue!
