### ISSUE TITLE
2.1 1015 Beta Used an additional 100 gb 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#31585]
**Describe the problem**

I ran tpcc 10k on a 9 node 64 cpu cluster on the 10/08 beta  and the 10/15 beta. The 10/15 beta used an additional 100gb.

**To Reproduce**
```diff
index 071ef8a3fe..cd9858eeff 100644
--- a/pkg/cmd/roachtest/tpcc.go
+++ b/pkg/cmd/roachtest/tpcc.go
@@ -677,11 +677,11 @@ func registerTPCCBench(r *registry) {
                        // StoreDirVersion: "2.0-5",
                },
                {
-                       Nodes: 3,
-                       CPUs:  16,
+                       Nodes: 9,
+                       CPUs:  64,
 
-                       LoadWarehouses: 2000,
-                       EstimatedMax:   1300,
+                       LoadWarehouses: 10000,
+                       EstimatedMax:   8000,
                },
```
Then `make bin/roachtest` and finally `bin/roachtest bench '^tpccbench/nodes=9/cpu=64$$' --wipe=false --user=andy`

**Expected behavior**
The same amount of disk space used. 

**Additional data / screenshots**
<img width="1551" alt="screen shot 2018-10-18 at 7 47 58 am" src="https://user-images.githubusercontent.com/22278911/47152262-2f9ea700-d2aa-11e8-88d2-637e35bb1543.png">
<img width="1572" alt="screen shot 2018-10-18 at 7 47 39 am" src="https://user-images.githubusercontent.com/22278911/47152263-2f9ea700-d2aa-11e8-8a54-0ff068e58635.png">

**Additional context**
10/08 Cluster: andy-1539820222-tpccbench-nodes-9-cpu-64
10/15 Cluster: andy-1539833762-tpccbench-nodes-9-cpu-64

**Comment by tschottdorf** [comment]
That could be just noise. Take a look at the sizes taken from the actual data directories:

```
[tschottdorf@toblerone cockroach (repro/tpcc-31409)]$ roachprod ssh andy-1539820222-tpccbench-nodes-9-cpu-64:1-9 -- sudo du -sch /mnt/data1/cockroach | grep total
293G	total
273G	total
282G	total
259G	total
272G	total
272G	total
265G	total
287G	total
255G	total
[tschottdorf@toblerone cockroach (repro/tpcc-31409)]$ roachprod ssh andy-1539833762-tpccbench-nodes-9-cpu-64:1-9 -- sudo du -sch /mnt/data1/cockroach | grep total
295G	total
265G	total
275G	total
266G	total
252G	total
293G	total
264G	total
285G	total
272G	total
```

and their sums

```
[tschottdorf@toblerone cockroach (repro/tpcc-31409)]$ roachprod ssh andy-1539833762-tpccbench-nodes-9-cpu-64:1-9 -- sudo du -sch /mnt/data1/cockroach | grep total | awk '{ sum += $1 } END { print sum }'
2467
[tschottdorf@toblerone cockroach (repro/tpcc-31409)]$ roachprod ssh andy-1539820222-tpccbench-nodes-9-cpu-64:1-9 -- sudo du -sch /mnt/data1/cockroach | grep total | awk '{ sum += $1 } END { print sum }'
2458
```

It's basically the same.

I assume one cluster had been running longer than the other, or compactions had happened on the one or not the other.

**Comment by tschottdorf** [comment]
@mjibson in case you think there's anything else here.

**Comment by mjibson** [comment]
No, looks fine to me.
