### ISSUE TITLE
kv: read-only transactions are considered aborted in txn.aborts metric

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#31595]
The `txn.aborts` currently includes committed read-only transactions. For instance, the following graph shows an instance of `kv0` running and two instances of `kv99` running.

<img width="1007" alt="screen shot 2018-10-18 at 12 01 00 pm" src="https://user-images.githubusercontent.com/5438456/47168005-caf54380-d2cd-11e8-9f61-c8b442ec5aef.png">

The current theory is that the following logic is causing this issue: https://github.com/cockroachdb/cockroach/blob/79191aafceb0b7c6126f48780ec01ffce65ce97e/pkg/kv/txn_interceptor_metrics.go#L105-L110

This is a regression in 2.1 that was not present in 2.0. We should get this fixed before the 2.1 release. Assigning to @andreimatei, who graciously offered to take a look.

**Comment by andreimatei** [comment]
I'll have a fix shortly.
