### ISSUE TITLE
Canceling CREATE TABLE AS Query

### ISSUE THREAD

**Issue by bladefist** [cockroachdb/cockroach#31600]
v2.1.0-beta.20181015

Ran a query `CREATE TABLE AS select from...`

This had very negative impact on the cluster, which I'm working w/ @tim-o on making a ticket for that.  However, once that was determined to be harming the cluster, I ran:

`SHOW QUERIES`

Found the query, got the query ID,  then ran:

`CANCEL QUERY {ID}` and the response was:

`pq: could not cancel query 155e845525f179530000000000000001: query ID 155e845525f179530000000000000001 not found`

Ran Show Queries again, it was still there, I'm confident the query ID was correct.  I can provide a screenshot privately if needed.

**Comment by tim-o** [comment]
@vivekmenezes - two issues here. 1) the CREATE TABLE AS destabilized the cluster, and 2) query in twilight state. I have the schema, I'll ping you privately on Slack.

**Comment by bladefist** [comment]
Correct, the destabilization can be described by:

- Connection timeouts in our app
- The "Databases" tab of the CRDB portal shows empty....no tables/databases
- `cockroach sql` won't connect or is very slow to connect

CPU on the nodes didn't spike though, and nothing ever crashed.  As soon as the query died (however it died), everything went back to normal.  From an outsiders perspective, it just seems like the CREATE TABLE made some table locks in places like information_schema.  

Thanks, I'm on gitter if you need any info.

**Comment by vivekmenezes** [comment]
@bladefist thanks for reporting this problem. I suspect that you hit issue https://github.com/cockroachdb/cockroach/issues/20526

**Comment by bladefist** [comment]
@vivekmenezes I would suspect you're right.  The only thing that doesn't match up is my query runs pretty fast like 15s or less, yet, when I run the full create table as query, it goes a lot longer and fouls everything up.

**Comment by vivekmenezes** [comment]
@bladefist thanks for that bit of input. We can take it from here on our end.

**Comment by lucy-zhang** [comment]
This is likely fixed in the newer `CREATE TABLE AS` implementation, so I'm closing it.
