### ISSUE TITLE
Dead loop problem

### ISSUE THREAD

**Issue by changrui82** [cockroachdb/cockroach#3163]
when `"redirectOnOrAcquireLeaderLease"`
we have code:
```
	if lease := r.getLease(); lease.Covers(timestamp) {
		if lease.OwnedBy(r.store.StoreID()) {
			// Happy path: We have an active lease, nothing to do.
			return nil
		}
		// If lease is currently held by another, redirect to holder.
		return r.newNotLeaderError(lease, r.store.StoreID())
	}
```
I think it has problem under this condition(assume DefaultLeaderLeaseDuration = 5 * time.Second):
1) Node A get the leader leaser at 15:05:07
2) Node A crashed at 15:05:08
3) Gateway node has a new request at 15:05:09, and find A unhealthy, so send to B. B find A has lease which can cover the timestamp(15:05:09 < 15:05:07+5s), then send "NotLeaderError" to gateway node. Then request is sended to A again...
It's an infinite loop, because the timestamp keep the same in the gateway node when retry.

Can we also check current time with lease.Expiration? If current time > lease.Expiration, node B can `requestLeaderLease` itself.

**Comment by tschottdorf** [comment]
see also #2728.
