### ISSUE TITLE
Contention prevents full utilization of 32 cpus in TPCC 10k

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#31633]
CockroachDB 2.1 achieves TPC-C 10K with 21 nodes and 16 CPUs. This is a total of 336 cpus.

I ran a test on 2.1 Beta from 10/15 with 11 nodes and 32 CPUs last night (352 total CPUs the minimum nunber of nodes needed to exceed the 336 nodes above) and saw a top output at 7850:
```
_elapsed_______tpmC____efc__avg(ms)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
  600.0s    85941.4  85.1%   2654.0   2281.7   4295.0   5637.1  12884.9  77309.4
--- PASS: tpcc 7850 resulted in 85941.4 tpmC (86.9% of max tpmC)
```

I upped the nodes to 12 holding CPU constant at 32 (384 total CPUs) and saw a top output at 8750:
```
_elapsed_______tpmC____efc__avg(ms)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
  600.0s    95884.0  85.2%   2963.9   2818.6   4831.8   5637.1   9663.7  98784.2
--- PASS: tpcc 8750 resulted in 95884.0 tpmC (86.9% of max tpmC)
```

I'm now running an experiment with 13 nodes to see if it gets closer to the performance of 21 nodes/16 CPUs. ~Clearly,~ contention likely prevents us from fully utilizing all of the CPUs available. It is only with the addition of new nodes that more CPUs can be taken advantage of. 

Hopefully, this experiment will tell us the number of CPUs that each node can actually take advantage of in this process and quantify our inefficiency.

**Comment by awoods187** [comment]
Well 13 nodes came back squarely in the middle. 
```
_elapsed_______tpmC____efc__avg(ms)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
  600.0s    85947.4  83.5%   4188.6   2952.8   8589.9  11274.3  22548.6 103079.2
--- PASS: tpcc 8000 resulted in 85947.4 tpmC (85.2% of max tpmC)
```

**Comment by awoods187** [comment]
I also tried an experiment out with 9 nodes and 64 CPUs for a grand total of 574 cpus (note that 9 nodes are needed for the disk size not for the number of CPUs). Here I was able to achieve 8250 warehouses:
```
_elapsed_______tpmC____efc__avg(ms)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
  600.0s    90701.7  85.5%   2787.0   2550.1   4563.4   5368.7   9126.8 103079.2
--- PASS: tpcc 8250 resulted in 90701.7 tpmC (87.2% of max tpmC)
 ```
I think this highlights that we have some problem with not adequately taking advantage of larger CPUs with fewer nodes.

**Comment by nvanbenschoten** [comment]
We made a few big improvements around better utilization of large machines in 19.1 and aren't planning on working on this in the near future. Closing.
