### ISSUE TITLE
Election loop in TestRemoveLeader

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#3165]
https://circleci.com/gh/cockroachdb/cockroach/9444

The test falls into an infinite cycle of elections and is unable to complete the removal of a node.

Discovered in #3160

**Comment by petermattis** [comment]
Is this still a problem?

**Comment by bdarnell** [comment]
That test was in the `multiraft` package and has been deleted. The comparable tests in the `storage` package don't seem to be flaky.
