### ISSUE TITLE
Cluster hangs after running DROP INDEX

### ISSUE THREAD

**Issue by fastest963** [cockroachdb/cockroach#31657]
**Describe the problem**

I ran the following query:
```
DROP INDEX IF EXISTS eu_sessions@ts_expired;
```
and it hung the all nodes that had ranges in that index. The nodes stopped responding to queries. I was dropping the index because I created it incorrectly. Once I CTRL+C'd the `cockroach sql` client it seems the index was then deleted and things returned to normal. That might've been a coincidence though. It said the drop index took 32 minutes if I look at the "Jobs" page. This page didn't load while the nodes were hanging but after things returned to normal I could see the page and see that it took that long.

**To Reproduce**

I'm not sure what steps exactly caused this since I've dropped/created indexes before without issue.

**Expected behavior**
I expected it not to hang and to drop/create the index.

**Additional data / screenshots**
Here's the create table:
```
CREATE TABLE eu_sessions (
region                  STRING NOT NULL,
user_id                 STRING NOT NULL,
property_id             STRING NOT NULL,
organization_id         STRING NOT NULL,
expired                 BOOL NOT NULL DEFAULT false,
incrementer             INT NOT NULL DEFAULT 0,
user_ts_created         INT NOT NULL,
ts_created              INT NOT NULL,
pageview_count          INT NOT NULL DEFAULT 0,
pageview_incrementer    INT NOT NULL DEFAULT 0,
ts_last_pageview        INT NULL,
ts_last_engage          INT NULL,
cmp_consent_id          STRING NULL,
ts_added_list           INT NULL,
user_flags              INT NOT NULL DEFAULT 0,
session_flags           INT NOT NULL DEFAULT 0,
conversion_id           BYTES NULL,
subscription_state      INT NULL,
ts_subscription_updated INT NULL,
ts_expired              INT NULL,
version                 INT NOT NULL DEFAULT 0,
submitted_status        INT NULL,
PRIMARY KEY (region, user_id, property_id, organization_id, expired, incrementer),
INDEX "ts_expired" (region, ts_expired, submitted_status, ts_created),
FAMILY "primary" (region, user_id, property_id, organization_id, expired, incrementer, user_ts_created, ts_created, ts_expired, version),
FAMILY "event" (pageview_count, pageview_incrementer, ts_last_pageview, ts_last_engage, cmp_consent_id, user_flags, session_flags, conversion_id),
FAMILY "subscription" (subscription_state, ts_subscription_updated),
FAMILY "submitted" (submitted_status)
)
```
The only errors I could see in the logs were:
```
Oct 19 20:47:27 veto cockroach[28738]: E181019 20:47:27.381019 11042357 server/server.go:1644  [n17,client=10.156.0.10:54143] unknown protocol version 80877102
Oct 19 20:47:27 veto cockroach[28738]: E181019 20:47:27.407000 11042353 server/server.go:1644  [n17,client=10.156.0.12:42677] unknown protocol version 80877102
```
That's the log that was happening hundreds of times.

**Environment:**
 - CockroachDB version: v2.1.0-beta.20181015
 - Server OS: CentOS 7
 - Client app: `cockroach sql`

**Additional context**

I didn't notice anything weird in the metrics other than:
![image](https://user-images.githubusercontent.com/112555/47245134-1559eb80-d3c6-11e8-8a17-029b46091df2.png)

I got a `cockroach debug zip` file after things returned to normal. Not sure if that would help or not.

I've since tried re-creating the index and dropping it again (multiple times) and it seemed to work fine so I'm not sure what happened here.

**Comment by knz** [comment]
cc @vivekmenezes for triage

**Comment by vivekmenezes** [comment]
@fastest963 thanks for reporting this issue. I'm not sure how to proceed with this problem. We do test this kind of creation of index in the presence of traffic and haven't seen this kind of problem before. Perhaps there was something else going on on the cluster at the same time. The next time you do see this I'd recommend taking a look at/capturing the hardware dashboard on this cluster through https://<host>:8080/#/metrics/hardware/cluster

**Comment by fastest963** [comment]
I'll close this for now until I can get it to happen again and then I'll try and look at that debug page and see.
