### ISSUE TITLE
cli/dump: dump produces inserts that are too large to be restored

### ISSUE THREAD

**Issue by isoos** [cockroachdb/cockroach#31676]
I've created a database dump using `cockroach dump [database] >output.sql`. However I'm not able to restore it, neither with native `psql` nor with the `cockroach sql` commands, most likely because the generated inserts are too large.

One of the tables there has rows with binary data, 1MB in size each, and the dump seems to create insert statements in the batch of 100 rows, regardless of the size. I think the inserts fail because the aggregated size is larger than the 64M limit.

**Comment by knz** [comment]
Oh that is nicely spotted.

As a workaround, you can modify `insertRows` in `pkg/cli/dump.go` and re-build to get a custom `cockroach dump` with a different (eg lower) number of rows per insert.

The proper fix on our side will probably be to auto-detect a good size.

**Comment by knz** [comment]
cc @rolandcrosby @mjibson for triage and prioritization

**Comment by knz** [comment]
Oh that is nicely spotted.

As a workaround, you can modify `insertRows` in `pkg/cli/dump.go` and re-build to get a custom `cockroach dump` with a different (eg lower) number of rows per insert.

The proper fix on our side will probably be to auto-detect a good size.

**Comment by tschottdorf** [comment]
@mjibson, could you help István out?

**Comment by knz** [comment]
I had sent a reply earlier today but I think it got lost in the Github
outage.

My answer was as follows:

- as a workaround you can edit the value of `insertRows` in
`pkg/cli/dump.go` to build a custom dump utility with fewer values per
insert.

- eventually CockroachDb should address this by adjusting the number of
values per insert automatically based on the size of the data.

Thanks for reporting the issue.

-- 
Raphael 'kena' Poss

**Comment by zsalab** [comment]
any news on this? maybe a workaround? can I help somehow? (I reported the #51969)

**Comment by knz** [comment]
my comment from https://github.com/cockroachdb/cockroach/issues/31676#issuecomment-431893866 is still applicable

**Comment by dt** [comment]
20.2 made proper binary BACKUP+RESTORE available for non-enterprise users and deprecated text-based `dump`, so we're not planning to go back and extend the deprecated dump functionality to add variable sized insert batches. Closing for now as wont-fix.
