### ISSUE TITLE
gossip: unable to look up descriptor for n0

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#31696]
While reworking `roachtest/decommission`, I got into a state where all nodes would tell me

```
$ ./cockroach node status --insecure --port 26261
Error: pq: unable to look up descriptor for n0
Failed running "node status"
```

I narrowed this down to

```
root@:26257/defaultdb> select * from crdb_internal.gossip_nodes;
pq: unable to look up descriptor for n0
```

and from there to this code (TL;DR something seems to actually gossip the zero node)

https://github.com/cockroachdb/cockroach/blob/2998190f18fab952357133aaca9fdda8bc52d5ac/pkg/sql/crdb_internal.go#L1829-L1839

I think this is the offending code:

https://github.com/cockroachdb/cockroach/blob/2998190f18fab952357133aaca9fdda8bc52d5ac/pkg/gossip/gossip.go#L858

The info that gets created from this is the following:

```
	v := roachpb.MakeValueFromBytesAndTimestamp(val, hlc.Timestamp{WallTime: now})
	return &Info{
		Value:    v,
		TTLStamp: ttlStamp,
		NodeID:   nodeID,
	}
```

It tries to "remove" something from the set of gossiped kv pairs (i.e. gossip a tombstone) but gossiping an empty proto is a poor substitute for that (every consumer must know about this, it's not like the key just disappears). I suspect what it really wants is to create a `nil` `Value` that is then handled accordingly by Gossip (i.e. pretend it's not there).

@a-robinson I think you introduced this feature. Did this rot at some point? What do you think we should do?

**Comment by tschottdorf** [comment]
Couldn't we just gossip a newer version of the old node descriptor with a short TTL?

**Comment by a-robinson** [comment]
> Couldn't we just gossip a newer version of the old node descriptor with a short TTL?

Possibly, although I remember that whole mechanism being fairly subtle to get right, so I'd hate to have to make any changes to it that might be backported to a 2.1.x release.

> Did this rot at some point? What do you think we should do?

Based on a quick re-reading of the code, it looks like https://github.com/cockroachdb/cockroach/commit/23594378b7dac04aab864d2857de19f635577c03#diff-f62b38d7c4e8147652a78f0bc6c69538R1855 is the culprit. Previously the code didn't rely on any lookups by the gossip'ed node ID succeeding, and even in this case the code could easily be reworked to avoid relooking up the descriptor given that it already has a copy of it (which is empty in cases like this).
