### ISSUE TITLE
sql: support timezone abbreviations in date parsing

### ISSUE THREAD

**Issue by bobvawter** [cockroachdb/cockroach#31710]
We don't support the use of "PST" or other abbreviations when parsing timezone values.  This requires access to more tzinfo fields than are readily available in the `time` package to resolve a candidate timezone.

If this is implemented, look at:

* https://github.com/postgres/postgres/tree/REL_10_5/src/timezone
* https://github.com/postgres/postgres/blob/REL_10_5/src/timezone/localtime.c#L1706

**Comment by bdarnell** [comment]
Note that these short abbreviations are ambiguous. For example, the abbreviation IST is used by India, Ireland, and Israel. Therefore it's not just a matter of getting more information from the tzdata files, we need a plan to handle the ambiguity. 

Postgres makes this configurable: https://www.postgresql.org/docs/current/datetime-config-files.html
