### ISSUE TITLE
sentry: stopper.go:182: runtime.errorString: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#31743]
https://sentry.io/cockroach-labs/cockroachdb/issues/740188507/

stopper.go:182: runtime.errorString: runtime error: invalid memory address or nil pointer dereference

runtime in call32

> stacktrace: {u'frames': [{u'function': u'scanframeworker', u'abs_path': u'/usr/local/go/src/runtime/mgcmark.go', u'module': u'runtime', u'in_app': False, u'lineno': 827, u'filename': u'runtime/mgcmark.go'}, {u'function': u'sigpanic', u'abs_path': u'/usr/local/go/src/runtime/signal_unix.go', u'module': u'runtime', u'in_app': False, u'lineno': 388, u'filename': u'runtime/signal_unix.go'}, {u'function': u'panicmem', u'abs_path': u'/usr/local/go/src/runtime/panic.go', u'module': u'runtime', u'in_app': False, u'lineno': 63, u'filename': u'runtime/panic.go'}, {u'function': u'gopanic', u'abs_path': u'/usr/local/go/src/runtime/panic.go', u'module': u'runtime', u'in_app': False, u'lineno': 502, u'filename': u'runtime/panic.go'}, {u'function': u'call32', u'abs_path': u'/usr/local/go/src/runtime/asm_amd64.s', u'module': u'runtime', u'in_app': False, u'lineno': 573, u'filename': u'runtime/asm_amd64.s'}]}
type: *log.safeError
value: stopper.go:182: runtime.errorString: runtime error: invalid memory address or nil pointer dereference

**Comment by tschottdorf** [comment]
Unclear what this is, I filed it with the Go team at https://github.com/golang/go/issues/28353.

**Comment by tschottdorf** [comment]
Oh, and this is linux-amd64.

**Comment by odeke-em** [comment]
Thank you for reporting this issue @tschottdorf! I am coming here from the Go project. Many of us don't have access to that sentry.io URL that you pasted, perhaps if you paste the output in a gist and perhaps provide some more content of what kind of C code call was invoked? I ask because I think that as much of a description could greatly help in trying to reproduce and fix it.

**Comment by jordanlewis** [comment]
@odeke-em  all we know:

```
stopper.go:182: runtime.errorString: runtime error: invalid memory address or nil pointer dereference
runtime/asm_amd64.s in call32 at line 573
runtime/panic.go in gopanic at line 502
runtime/panic.go in panicmem at line 63
runtime/signal_unix.go in sigpanic at line 388
runtime/mgcmark.go in scanframeworker at line 827
```

**Comment by tschottdorf** [comment]
@odeke-em thanks for checking in. As Jordan mentioned, the above is all we know, and it's in the upstream issue https://github.com/golang/go/issues/28353.
Checking the sentry link again, all I have to add is that this has not reoccurred since.

**Comment by tbg** [comment]
Happened once three months ago - I've marked the issue as resolved on sentry so that a new report will be generated should it reoccur.
