### ISSUE TITLE
distsqlrun: implement WITH ORDINALITY processor in distsql

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#31748]
Currently, WITH ORDINALITY cannot be distributed because it doesn't have a DistSQL processor equivalent for `ordinalityNode`.

Implement a DistSQL Processor that performs the `WITH ORDINALITY` work - adds a new ordinality column that contains the current index of the rows that the processor has seen.

- [ ] implement `OrdinalityProcessor` in `pkg/sql/distsqlrun/ordinality.go`
- [ ] implement tests for the above in `pkg/sql/distsqlrun/ordinality_test.go`
- [ ] add DistSQL spec (`OrdinalitySpec`) for `OrdinalityProcessor` in `pkg/sql/distsqlpb/processors_sql.proto`
- [ ] add constructor for `OrdinalityProcessor` from spec in `pkg/sql/distsqlrun/processors.go`
- [ ] add physical planning (translation from `planNode` to `OrdinalitySpec` protobuf) to `pkg/sql/distsqlplan/distsql_physical_planner.go`
- [ ] add planning tests to `pkg/sql/opt/exec/execbuilder/testdata/ordinality`

**Comment by jordanlewis** [comment]
Note that there might be a few small complications here, depending on what the optimizer expects will happen when an `ordinalityNode` is planned. Is it valid to distribute the ordinalityNode, such that the resultant ordinalities are interleaved based on the order that distributed computations happen?

Or, does the ordinality numbering have to match the output ordering?

The answer to this question will dictate whether this node can be easily distributed, or whether it has to be planned on a single node.

**Comment by khalibartan** [comment]
@jordanlewis I would like to work on this one if nobody has started working on this.

**Comment by jordanlewis** [comment]
we are working on this one.

**Comment by jordanlewis** [comment]
@khalibartan we appreciate your contributions! It can be hard to figure out what's a good thing to work on as an external contributor. Can you send me an email at jordan@cockroachlabs.com and we can talk about what might be a good direction for you?
