### ISSUE TITLE
opt: Count null values in distinct counts

### ISSUE THREAD

**Issue by itsbilal** [cockroachdb/cockroach#31746]
Column statistics in the optimizer currently consist of two counts: one for null and one for distinct values. The distinct count currently does not count null values.

This has the side effect of making some formulas more complex, such as the `ColsAreLaxKey` case in `colStatLeaf`:

https://github.com/cockroachdb/cockroach/blob/a8be7a66b013cac608ed9ec8d8338ca1a927e5b1/pkg/sql/opt/memo/statistics_builder.go#L355

By counting nulls as just any other distinct value, we can simplify such formulas, in addition to having a more intuitively understandable definition of distinct counts. Note that the formulas for calculating selectivity from distinct count may have to account for the fact that there's already a separate selectivity calculation for null-elimination, however that added complexity should be minimal.

**Comment by RaduBerinde** [comment]
@rytaft This is fixed by #38041, correct?

**Comment by rytaft** [comment]
Yep! Closing this.
