### ISSUE TITLE
cli/haproxy: increase the default check timeout

### ISSUE THREAD

**Issue by tephrocactus** [cockroachdb/cockroach#31742]
**Environment**

**OS**: darwin 17.6.0
**Haproxy**: 1.8.14-52e4d43
**CockroachDB Cluster**: 3 local nodes (v2.1.0-rc.1)

**The problem**

_cockroach gen haproxy_ generates the following config file:
```
global
  maxconn 4096

defaults
    mode                tcp
    timeout connect     10s
    timeout client      1m
    timeout server      1m
    option              clitcpka

listen psql
    bind :26256
    mode tcp
    balance roundrobin
    option httpchk GET /health?ready=1
    server cockroach1 localhost:26257 check port 26267
    server cockroach2 localhost:26258 check port 26268
    server cockroach3 localhost:26259 check port 26269
```

The problem is that if **timeout check** directive is omitted, haproxy, by default, uses quite aggressive timeout when checking cockroach node health via http. As the result, you can see the following messages in haproxy log:

```
[WARNING] 295/093550 (88996) : Server psql/cockroach1 is DOWN, reason: Layer7 wrong status, code: 503, info: "Service Unavailable", check duration: 3ms. 2 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
```

... this is a false positive one. Cockroach node is alive, but the response to health check request took more time than haproxy expected. Nevertheless one or even all nodes are considered down.

**Possible solution**

When generating haproxy config add **timeout check 1s** (or some other value instead of 1s) to _defaults_ section. This eliminated the problem in my case.

**Additional context**

I faced this situation running a cluster on a single machine, but, in theory, it is also possible with a production cluster under high load.

**Comment by knz** [comment]
@a-robinson what do you think? does this seem reasonable?

@tephrocactus would you be interested to submit a PR to update CockroachDB with your suggestion? We love external contributions.

**Comment by a-robinson** [comment]
I'm not seeing how a timeout in haproxy would be causing a 503 HTTP error code, and I'm very skeptical that haproxy's timeout would be 3ms. Are there other failures in the haproxy log?

I'm not opposed to adding a timeout check default, but I'd prefer to understand what @tephrocactus was seeing first. cc @mberhault who knows more about haproxy than me

**Comment by tephrocactus** [comment]
@a-robinson 
Looks like it's a wrong call. I can reproduce the issue only on some MacOS laptops, it hard to catch.
No such issue on production linux servers, even without **timeout check** directive in haproxy.conf.
Probably not haproxy's fault.

**Comment by knz** [comment]
Thanks for your additional testing / report. Since you think the problem lies elsewhere, I will close this issue. Let me know if there is anything here we can help with.
