### ISSUE TITLE
storage/engine: theoretical RocksDB inconsistency

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#31752]
Certain interleavings of range deletions and compactions can result in keys being incorrectly deleted. To our knowledge the bug has never been observed in a Cockroach cluster, but the bug has only been present since v2.1, which is not yet widely deployed. This issue exists to spur discussion of just how likely the bug is to occur and whether it needs to block the release of v2.1.

Here's what it takes to trigger the bug:

![image from ios](https://user-images.githubusercontent.com/882976/47375122-8696e880-d6bd-11e8-962e-0ab85e59136f.jpg)

1. Keys in the intervals `[b, j]` and `[m, r]` are written to RocksDB. Importantly, no keys are written in the interval `(j, m)`. Key `f` is written at least twice, once at seqno 70 and once at seqno 100. 
2. A range deletion over `[c, p)` is written at seqno 150.
3. Key `o` is written at seqno 180.
4. A series of compactions and flushes occur, creating the three L3 SSTs pictured in the diagram above. Notice how user key `f` is split across two SSTs: the version at seqno 100 is in the leftmost SST, while the version at seqno 70 is in the following SST. The range deletion will be written to all three SSTs, since it overlaps all three SSTs.  

  If a read occurs now, the range deletion tombstone `[c, p) @ 180` will be handled correctly. Note that the tombstone will be loaded three times, once for each SST, but it will be truncated to SST boundaries. For example, when the range deletion is loaded from the rightmost SST, it will be truncated to `[m, p) @ 180` to reflect the boundaries of its containing SST. Due to a complication, however, this truncation will _not_ be performed when loading the tombstone from the leftmost SST; that tombstone will be loaded untruncated as `[c, p) @ 180`. That's ok for the moment, though.

5. The rightmost SST is further compacted to the bottommost level, L6. At this point, to save space, RocksDB will reset the seqno of all keys to 0, since once a key has reached the bottommost level there can't be any earlier versions of it. The range deletion is also "applied" at this point; that is, the keys covered by the tombstone, as well as the tombstone itself, are dropped. So the only key in the compacted SST is `o @ 0`.
 
  Now we have a problem. If a read occurs, it will fail to see `o @ 0`, because the tombstone loaded from the leftmost SST, `[c, p) @ 180`, is untruncated and thus covers `o`!

FYI The issue was fixed in upstream PR https://github.com/facebook/rocksdb/pull/4432, but the fix is (probably) too large and invasive to backport at this point in the release cycle.

What's not clear is how likely the above sequence of events is to be triggered by Cockroach. One interesting property of our workload is that range deletions only occur along range boundaries, as we only issue range deletions when a) a replica is removed from a store or b) a table is dropped.

Here's a scenario that I think could do the trick:

  1. A range R from [/Table/52, /Max) is created. It exists on S1, S2, and S3.
  2. Lots of data is written to the table 52. Let's say it's an update heavy workload with a short TTL so that the total number of bytes in the range never gets so large that a split is triggered, but there's tons of data in RocksDB.
  3. R is rebalanced from S3 to S4. This leaves a tombstone from [/Table/52, /Max) on S3. Since there's lots of data in the key space.
  4. A compaction on S3 is triggered. The compaction gets unlucky and splits some arbitrary key associated with R across two SSTs. The range deletion ends up in both of these SSTs. Since there's lots of data here—maybe a few compactions have already been triggered—these SSTs end up in some relatively high level of the LSM.
  4. A restore starts for table ID 53.
  5. R gets pre-split for the restore, perhaps into [/Table/53/1/42, /Table/53/1/43). Call this range R'.
  6. R' processes an AddSSTable command and fills up with data.
  7. R' gets rebalanced back on to S3.
  8. S3 writes the snapshot for R' to RocksDB.
  9. RocksDB flushes and compacts and moves the data for R' straight to L6 since it's fresh key space. The seqno for all keys in R' is thus reset to 0.
  10. Boom! All of R' is now covered by the tombstone.

@petermattis @bdarnell @tschottdorf curious to hear your thoughts

**Comment by petermattis** [comment]
Note that if R' can move straight to L6 then there isn't a problem because we won't have rewritten the sequence numbers (trivial move lives up to its name and just adjusts metadata).

**Comment by bdarnell** [comment]
Overall this seems pretty unlikely so i'm not too concerned, but it seems plausible to me that this would be most common in workloads that are more common in the real world than in our current test suite. We should run a `kv0` workload with a short cycle length and a batch size greater than 1 in an attempt to reproduce this (the idea is to do distributed transactions, since the mvcc metadata records for intents are the most common case where we rewrite the same keys). Decommissioning and recommissioning nodes while it's running might also trigger the necessary range movements.

Do we have any way to hook into the compaction process and prevent keys from splitting across sstables like this?

**Comment by petermattis** [comment]
> Do we have any way to hook into the compaction process and prevent keys from splitting across sstables like this?

Not that I'm aware.

**Comment by petermattis** [comment]
Something for the casual reader to be aware of: range tombstones are not truncated when stored in an SSTable, but only truncated upon reading. Well, this isn't completely true, they are truncated any time they are added to a `RangeDelAggregator`, including when they are added to a `RangeDelAggregator` in preparation for compaction.

**Comment by petermattis** [comment]
Btw, check out the upstream test which tickles the bug described here: https://github.com/cockroachdb/rocksdb/blob/crl-release-5.13/db/db_range_del_test.cc#L1379-L1492

**Comment by bdarnell** [comment]
Now that 2.1 is out, we should backport the rocksdb fix so we can start testing it.

**Comment by petermattis** [comment]
Are we doing extra testing of 2.1 vs master? I'd be fine with backporting.

**Comment by petermattis** [comment]
I suppose we'll have anxiety about this until the fix is backported. I'll do so shortly.
