### ISSUE TITLE
sql: pg_am table not implemented

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#31761]
See https://www.postgresql.org/docs/9.5/static/catalog-pg-am.html (and note that this table changes between 9.5 and 10.0). Needed for hibernate test org.hibernate.test.schemaupdate.MigrationTest.testIndexCreationViaSchemaUpdate.

**Comment by jordanlewis** [comment]
Possible duplicate of #32624.

**Comment by BramGruneir** [comment]
Indeed it is.
