### ISSUE TITLE
"unknown protocol version 80877102" error caused from cancel() in pq driver

### ISSUE THREAD

**Issue by fastest963** [cockroachdb/cockroach#31763]
**Describe the problem**

Go's pq driver makes a request with a particular version in order to cancel a request: https://github.com/lib/pq/blob/master/conn_go18.go#L98

This ends up causing:
```
E181023 19:30:11.186881 1023923 server/server.go:1644  [n10,client=10.132.0.3:19317] unknown protocol version 80877102
```

**To Reproduce**

I'm not sure exactly what causes this but it looks like when a context is cancelled that's passed to `QueryContext` the `cancel` function is invoked from `watchCancel` to cancel the original operation.

**Expected behavior**
I expect the original operation to be cancelled and an error not be printed to the logs.

**Environment:**
 - CockroachDB: v2.1.0-rc.1
 - Server OS: CentOS 7.4
 - Client app: https://github.com/lib/pq

**Additional context**
What was the impact?

Outstanding queries might not be cancelled that should have been. Context cancellations end up triggering an error on the server-side.

**Comment by tim-o** [comment]
@mjibson - looks like your wheelhouse given this is pq related? Looks like this code has been there a while.

**Comment by mjibson** [comment]
We don't support this particular feature of the postgres wire protocol, nor do we have plans to. To cancel queries you must use [cancel query](https://www.cockroachlabs.com/docs/v2.0/cancel-query.html#main-content).

**Comment by fastest963** [comment]
@mjibson what's the best way for a driver to know what queryID was running? For instance, if your driver accepts a context and it is cancelled and so you want to cancel the running query what's the best way to figure out the associated queryID? If I call SHOW QUERIES the same query might be listed multiple times.

**Comment by knz** [comment]
@fastest963 currently:

- run `SHOW SESSIONS` on the same node. You could issue it on the same connection before you send the query you (later) want to cancel. Obtain the `client_address`.

- when the query is running, and you think it's taking too long and you want to cancel it, run `SHOW CLUSTER QUERIES` on any node, and filter on the `client_address` obtained in the first step.

That gives you the query ID you can then cancel.

Granted, this is cumbersome. We should ease this task. Will file a separate issue.

**Comment by knz** [comment]
Note you do not need the first step. The client apps can "know" the port number it's using to connect to the server, so you can use that directly to filter the output of `SHOW QUERIES`.

**Comment by knz** [comment]
Filed #32055.
