### ISSUE TITLE
storage: `ExportToSST` does not handle intents well

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#31762]
Current on encountering an intent, ExportToSST will immediately return an intent error containing just that first encountered intent. This is unlike MVCCScan which will keep accumulating multiple intents and return them all at once, allowing the resolution of all of them before a retry. In spans with lots of intents, this can lead to very slowly looping through, resolving just one intent per retry, leading to backups that export the same prefix of a span over and over and struggle to make progress.

**Comment by tschottdorf** [comment]
Related to #31664.

**Comment by dt** [comment]
Duplicate: #59704
