### ISSUE TITLE
opt: 2 lookup columns specified, expecting at most 1

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#31777]
Running the hibernate test org.hibernate.test.legacy.FooBarTest.testCollectionsInSelect results in an error: `2 lookup columns specified, expecting at most 1` while executing:

```
SELECT
  foo3_.string_ AS col_0_0_
FROM
  foos AS bar0_
  INNER JOIN jointable AS bar0_1_ ON bar0_.foo_idcolumnname123 = bar0_1_.fooid
  INNER JOIN foo_dep_table AS bar0_2_
  ON bar0_.foo_idcolumnname123 = bar0_2_.fooid
  INNER JOIN bar_join_table AS bar0_3_
  ON bar0_.foo_idcolumnname123 = bar0_3_.bar_id
  LEFT JOIN baz AS baz1_ ON bar0_.baz = baz1_.baz_id_column_
  LEFT JOIN foo_array AS fooarray2_
  ON baz1_.baz_id_column_ = fooarray2_.id_ AND fooarray2_.i < 8
  LEFT JOIN foos AS foo3_ ON fooarray2_.foo = foo3_.foo_idcolumnname123
  LEFT JOIN jointable AS foo3_1_ ON foo3_.foo_idcolumnname123 = foo3_1_.fooid
  LEFT JOIN foo_dep_table AS foo3_2_
  ON foo3_.foo_idcolumnname123 = foo3_2_.fooid
WHERE
  bar0_.foo_subclass_1234 = 'B' AND bar0_.string_ = foo3_.string_;
```

[`explain (distsql)` output](https://cockroachdb.github.io/distsqlplan/decode.html#eJyc1UFvmzAUwPH7PoX1Lr08aRhIQixNsia1E1VFpoydNlQRcCu2FCPbSM2qfPfJsGnJFnuFI4Y__B6lzgu0shZZ-SQ0sC9AoUDolKyE1lLZpfGCtH4GFiA0bdcbu1wgVFIJYC9gGrMXwCAvd3uxFWUt1NsAEGphymY_3LZTzVOpDvxBSg0IN83eCMUIj8g7cvX-ijH2Kd-m2QdA2PSGEU6RR8jpGnlMoTgiyN78ebI25aMARo_4et2tbNpfOHoZ9002rbEzAMKdlN_7jtglIlsLOqWFgy5GvnDawpm20Pni7mvR3U_1IV86idFMYnSZuCvVvfXMMSJfOZnxTGZ8zswPnWDk7vomJ5vP-fWW3G7SDPCE_-OSOfaZkSdO9mImezGNbT-MUqnycAmfWHxGOA3I1z4IoookjLE0y_8zFPI1chogp-5_vuXM-Zbn8z3stFFN_fx7a_hnhmhQvNqLnNoLAqd7NdO9mvZ38W8m4dSBqH0NsXOoZOZQyfSPzb8LnQwWObXrKdqt0J1stTiTuu4cHAsEUT-K8ZdLy15V4qOS1fCY8XAzdMNCLbQZz9LxIG3HUxZ4GlNvHPrj0BtH_jjyxrE_jr3xwh8vvPHSHy-98cofr7xx4o8Tb7z-Ky6Ob34GAAD__10p2FU=)

[sql dump](https://github.com/cockroachdb/cockroach/files/2508962/dump.txt)

**Comment by solongordon** [comment]
It looks like the optimizer is planning a lookup join on two columns even though the index only has one. Here is a significantly tighter repro:
```
CREATE TABLE t (a INT PRIMARY KEY, b INT, c INT, INDEX idx (c));

INSERT INTO t VALUES (1, 2, 3);

SELECT t2.c
FROM t
  JOIN t AS t2
  ON t.a = t2.a AND t.c = t2.c
WHERE t.b = 2;

pq: 2 lookup columns specified, expecting at most 1
```

**Comment by RaduBerinde** [comment]
A non-unique index on `(c)` is actually a unique index on `(c, a)`. So it should be able to use both on a lookup. Maybe it's an unnecessary limitation on the execution side?

**Comment by solongordon** [comment]
Thanks, looks that way. I'll fix and we can decide if it's safer to backport that or limit what the optimizer plans.
