### ISSUE TITLE
sql: role `ADMIN OPTION` ignored for the `admin` role

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#31784]
Membership in the role comes with an optional `ADMIN OPTION`.
When true, it makes the member an administrator of the role, allowing addition/removal of membership.

Here's an example:
```
root> CREATE ROLE foo;
root> CREATE USER marc1;
root> CREATE USER marc2;
root> CREATE USER marc3;
root> CREATE USER marc1;
root> CREATE USER marc2 WITH ADMIN OPTION;
root> SHOW GRANTS ON ROLE;
  role_name | member | is_admin  
+-----------+--------+----------+
  admin     | root   |   true    
  foo       | marc1  |  false    
  foo       | marc2  |   true    
(3 rows)
```

Attempting to modify the membership of `foo` without the `ADMIN OPTION` fails:
```
marc1> GRANT foo TO marc3;
pq: marc1 is not a superuser or role admin for role foo
```

Attempting to modify the membership of `foo` with the `ADMIN OPTION` succeeds:
```
marc2> GRANT foo TO marc3;
GRANT
```

So far so good.
However, if we do the same thing with the `admin` role, the `ADMIN OPTION` check is bypassed because all members of the admin role as superusers.

```
root> GRANT admin TO marc1;
root> SHOW GRANTS ON ROLE admin;
  role_name | member | is_admin  
+-----------+--------+----------+
  admin     | marc1  |  false    
  admin     | root   |   true    
(2 rows)

marc1> GRANT admin TO marc3;
GRANT
marc1> SHOW GRANTS ON ROLE admin;
  role_name | member | is_admin  
+-----------+--------+----------+
  admin     | marc1  |  false    
  admin     | marc3  |  false    
  admin     | root   |   true    
(3 rows)
```

We can even give ourselves the `ADMIN OPTION`:
```
marc1> GRANT admin TO marc1 WITH ADMIN OPTION;
marc1> SHOW GRANTS ON ROLE admin;
  role_name | member | is_admin  
+-----------+--------+----------+
  admin     | marc1  |   true    
  admin     | marc3  |  false    
  admin     | root   |   true    
(3 rows)
```

This breaks the barrier between "admin user who can perform most actions" and "admin user who can create/remove admin users". The latter is considerably more powerful.
Ultimately, the privileges on `system.users` mean that any member of the `admin` role can manually flip the bit (`UPDATE system.users SET "isRole"=true WHERE username='marc3'`), but the behavior is still strange and unexpected.

**Comment by knz** [comment]
@vivekmenezes @jordanlewis we need to cone up with a concerted action plan. This is related to a bunch of other issues that have found that the `system` tables should not generally be writable by all users.

My preference would be to restrict access to `system` tables by the `root` user specifically instead of "any admin user". However we need to hunt down all indirect accesses to `system` tables by other SQL statements to check that they are not assuming anything else.

**Comment by mberhault** [comment]
That's a separate conversation and one we've been having since system tables existed, but the net gain has generally not be thought to be worth the effort. The right answer is likely to remove all write access to the system tables by anyone other than `node`.

For this issue, let's focus on the semantic of the `ADMIN OPTION` bit when it comes to the admin role.

**Comment by vivekmenezes** [comment]
What would happen if we didn't ignore the ADMIN OPTION bit for the admin role?

**Comment by mberhault** [comment]
The same thing that happens for other roles: only members with the `ADMIN OPTION` can add or remove members from the role.

**Comment by vivekmenezes** [comment]
marking this as easy.

**Comment by rohany** [comment]
Is this issue still valid? `create user` doesn't seem to accept the `with admin option` qualifier anymore.

**Comment by jordanlewis** [comment]
Seems like there's still something here, based on a quick grep:

```
		{`GRANT rolea, roleb TO usera, userb WITH ADMIN OPTION`},
```

I don't know how this works however.
