### ISSUE TITLE
storage: differing TBs observed on the same size restore with different nodes 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#31786]
I ran the same import of TPC-C 10K on three different cluster sizes and saw different amounts of data in the cluster.

21 node with 2.1tb:
![image](https://user-images.githubusercontent.com/22278911/47430658-011c4280-d768-11e8-88d9-b6bd0b7d1cfd.png)

11 node with 2.3tb:
![image](https://user-images.githubusercontent.com/22278911/47430666-07122380-d768-11e8-9dcc-ef4865b9ac12.png)

9 node with 2.2tb:
![image](https://user-images.githubusercontent.com/22278911/47430679-0c6f6e00-d768-11e8-8c98-b7e2960e3fd5.png)

I expected that as node size increased, the data would increase as the cluster would need to handle more complexity. The above suggestions that there is something else that may cause differing tbs within the cluster.

**Comment by mjibson** [comment]
I agree with Toby. I don't think there's anything unexpected here.
