### ISSUE TITLE
Restore doesn't scale linearly with the number of nodes 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#31787]
**Describe the problem**

I observed non-linear scaling on restoring TPC-C 10k by the number of nodes. Note that while CPU varies we expect it to not be a factor in restore speed. 

9 node 64 CPU cluster took 4hrs11m to finish restoring TPC-C 10k 
![image](https://user-images.githubusercontent.com/22278911/47431076-180f6480-d769-11e8-8918-94d7b33919b6.png)

11 node 32 cpu cluster took 2h46m
![image](https://user-images.githubusercontent.com/22278911/47431089-1d6caf00-d769-11e8-8ca3-c9a293c2706d.png)

I observe that 22% more nodes did roughly the same amount of work 34% faster.

I expected this trend of increased performance with an increasing number of nodes to continue, however, a 21 node 16 CPU cluster took almost exactly the same time as the 11 node 32 CPU cluster (no screenshot).

This suggests to me that the maximum performance for TPC-C restore of 10k is greater than 9 and less than or equal to 11 nodes.

**To Reproduce**

Run a restore using tpcc-bench on varying node configuration sizes. 

**Environment:**
 - CockroachDB version 2.1 rc 1

**Comment by pbardea** [comment]
We've made several improvements here and are seeing nearly linear scaling until more than 32 nodes. See some sample data of restore2TB in https://github.com/cockroachdb/cockroach/issues/47221#issuecomment-683912966 for concrete numbers.

I think it's safe to close this out for now, and we can re-open if we see restore being bottlenecked on large clusters.
