### ISSUE TITLE
ui: make node map on admin UI the default view for customers

### ISSUE THREAD

**Issue by kannanlakshmi** [cockroachdb/cockroach#31789]
Currently, the default overview page on the Web UI is the node list. You have to find the toggle which was not very easy to find or obvious (to me at leas) and know there exists something else to go to the node map. Given the node map is a key enterprise feature and very helpful for global clusters, we should make this the default overview page rather than the node list. 

We should also explore how to make it more easy and obvious for customers to find the toggle and know there are two different views on the main overview page. 

cc @piyush-singh @vilterp

**Comment by vilterp** [comment]
Kind of want to fix #31699 before we do this.
