### ISSUE TITLE
sql: Performance of repeated DDL degrades

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#31818]
A customer is developing a DDL script and running it repeatedly. The first run took 1m 30s, but subsequent runs took longer, reaching at least 6m 41s.

The script performs the following steps:

- Drop FK indexes using CASCADE
- Drop all (59) tables
- Create all (59) tables
- Create FK indexes
- Create FKs

Cockroach version: 2.0.0. The problem was observed on both a macbook and linux on vmware.

Jira issue: CRDB-4778

**Comment by tschottdorf** [comment]
Isn't this strongly related to https://github.com/cockroachdb/cockroach/issues/28376 and https://github.com/cockroachdb/cockroach/issues/31421 is similar?

In https://github.com/cockroachdb/cockroach/issues/31421#issuecomment-430357354 @vivekmenezes points out that this is something we'll fix in 2.2. Is that still correct? I know @nvanbenschoten has been pretty nervous about this problem for a while and so am I. Is there a proposed solution out there already? So far I've only seen descriptions of the problem.

**Comment by vivekmenezes** [comment]
I suspect this is a different problem, and is likely related to the fact that we do not delete table descriptors and leave them in the DROP state for 24 hours (GC interval). As a result as you CREATE and DROP tables , more and more descriptors build up and all of them need to be scanned in some code paths as well as gossiped every time a descriptor is modified.

**Comment by nvanbenschoten** [comment]
Yes, I agree with @vivekmenezes. This sounds a lot like https://github.com/cockroachdb/cockroach/issues/20753.

I think the short-term solution is dropping the TTL on table descriptors to prevent a huge build-up of them.

**Comment by bdarnell** [comment]
I'm not sure that a short-term workaround is needed here (I recommended iterating on a local `cockroach start --store=type=mem`, which was well-received).  Reducing the ttl on descriptors is dangerous since it limits your ability to use AOST or BACKUP. I think it would need to be pretty low to improve the use case that prompted this issue.

**Comment by vivekmenezes** [comment]
I'm keeping this open to be fixed in 2.2

**Comment by jordanlewis** [comment]
@rohany, I'm assigning this to you to correspond with the work that we're doing to improve DDL roundtrips. I think we should write a benchmark for this and use it as a guiding principle.
