### ISSUE TITLE
roachtest,workload: allow restoration of fixtures on AWS

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#31826]
We need to be able to easily run TPC-C on AWS. 

We use workload to restore a fixture of TPC-C (at 1K, 5K, 10K, 20K, and 50K) that's hosted on GCE. 

We recently improved roachprod to support AWS, however, we cannot use our GCE fixtures on AWS. This is because workload expects to restore from GCE. 

We likely need to teach workload to use AWS.

**Comment by awoods187** [comment]
CC @petermattis to see if you have any ideas we can free up someone to work on this

**Comment by petermattis** [comment]
I have no ideas for who can work on this in the short term. We had a planning failure if this is urgently needed.

**Comment by awoods187** [comment]
CC @kannanlakshmi as it's needed for Managed as well

**Comment by awoods187** [comment]
@nvanbenschoten are you going to backport the fixture creation to 2.1? 

I suppose either way we can close this issue since we can do it on 19.1

**Comment by nvanbenschoten** [comment]
@danhhz backported https://github.com/cockroachdb/cockroach/pull/32237 to 2.1, but not https://github.com/cockroachdb/cockroach/pull/31899, which required a new cluster version. 

Since we're moving away from prebuilt fixtures anyway, I don't think there's anything to do here.

**Comment by danhhz** [comment]
Seconding nathan on all counts. If we have to stand up a fixture on 2.1 AWS, the best way to do that is with the csv-server based `fixtures import`
