### ISSUE TITLE
cli/sql: Add the cli commands `exit` and `quit` to quit the cli.

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#31878]
With the release of postgres 11, they've finally added the ability to quit the cli with the new keywords `exit` and `quit`.

We should do the same.

see: https://www.postgresql.org/about/news/1894/

> The inclusion of the keywords "quit" and "exit" in the PostgreSQL command-line interface to help make it easier to leave the command-line tool

**Comment by a-robinson** [comment]
Do they support ":q"? :)

**Comment by knz** [comment]
Both `psql` and `cockroach sql` have supported `\q` since times immemorial.

**Comment by M-srivatsa** [comment]
can someone guide me on where the code to add this feature exists / is there any documentation that i can refer to. (I am new here)

**Comment by M-srivatsa** [comment]
#31915

**Comment by M-srivatsa** [comment]
Have updated the pull request #31915 
Please check it out
