### ISSUE TITLE
sql: test/evaluate compatibility with Flowable 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#31879]
Test flowable with CockroachDB 
https://www.flowable.org/

**Comment by rolandcrosby** [comment]
Right off the bat, #32098 blocks several of Flowable's `CREATE TABLE` statements. I ran Flowable against Postgres for a while and captured a sample of queries that it uses; will continue to work with the SQL team to determine how to identify other compatibility gaps.

**Comment by awoods187** [comment]
Any update on this after Friday's testing @rolandcrosby ?

**Comment by drewdeally** [comment]
@awoods187 updates are https://github.com/cockroachlabs/support/issues/223

**Comment by awoods187** [comment]
- [ ] https://github.com/cockroachdb/cockroach/issues/35109
- [ ] https://github.com/cockroachdb/cockroach/issues/35108

**Comment by knz** [comment]
#35109 we can probably work around easily. #35108 is a little more work but is probably doable for 19.1, or perhaps 19.1.x. I wouldn't recommend backports to 2.1.

**Comment by knz** [comment]
The linked support issue also mentions #32098.

This is a well-scoped, well-contained new feature that's approximately M-sized (compare to S-sized for the previous two)

**Comment by rolandcrosby** [comment]
I'm 90% sure that #32098 is the only query here that's specific to Flowable. The other two are caused by pg_dump and do not occur in the Flowable application.

(What happened here: we ran Flowable against a Postgres instance that was configured to write all queries to a log file, then ran pg_dump to save the state of the database for later import/analysis; Postgres still had query logging turned on when we ran pg_dump, so all the SQL queries issued by pg_dump also showed up in the log, along with all the queries that were actually issued by the Flowable application.)

**Comment by knz** [comment]
For #32098 it would be good to know whether the customer uses any other precision than 6 in their app.

**Comment by rolandcrosby** [comment]
The Postgres schemas in Flowable only use TIMESTAMP and TIMESTAMP(6). You can search that repo online [here](https://github.com/flowable/flowable-engine/search?q=timestamp+filename%3Apostgres&unscoped_q=timestamp+filename%3Apostgres); I downloaded the code locally to look in more detail. There are a couple occurrences of TIMESTAMP(3) in the repo, but those are only in the MySQL-specific DDL code.

**Comment by awoods187** [comment]
Does that impact your idea @knz ?

**Comment by knz** [comment]
we won't be able to do anything about  TIMESTAMP(3) in the near future. For the other cases, my PR #35128 might help. It's only going to work as long as they don't expect the precision to be preserved in information_schema/pg_catalog.

**Comment by rolandcrosby** [comment]
I believe your PR will solve the problem. Thanks!

**Comment by drewdeally** [comment]
Roland, we can work around these with the create script - if we don't go that route then Flowable needs to have logic to add indexes for RI constraints and they will also fail.

**Comment by vy-ton** [comment]
Flowable is supported with CockroachDB, https://github.com/cockroachdb/docs/issues/6865 tracks updating documentation.
