### ISSUE TITLE
sentry: replica_consistency.go:152: consistency check failed with %d inconsistent replicas | int

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#31874]
https://sentry.io/cockroach-labs/cockroachdb/issues/742856302/

replica_consistency.go:152: consistency check failed with %d inconsistent replicas | int

github.com/cockroachdb/cockroach/pkg/storage.(*Replica).CheckConsistency

> stacktrace: {u'frames': [{u'function': u'1', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go', u'module': u'github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server).serveStreams.func1', u'in_app': False, u'lineno': 680, u'filename': u'github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go'}, {u'function': u'handleStream', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go', u'module': u'github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server)', u'in_app': False, u'lineno': 1249, u'filename': u'github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go'}, {u'function': u'processUnaryRPC', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go', u'module': u'github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*Server)', u'in_app': False, u'lineno': 1011, u'filename': u'github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go'}, {u'function': u'_Admin_EnqueueRange_Handler', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/server/serverpb/admin.pb.go', u'module': u'github.com/cockroachdb/cockroach/pkg/server/serverpb', u'in_app': True, u'lineno': 1997, u'filename': u'github.com/cockroachdb/cockroach/pkg/server/serverpb/admin.pb.go'}, {u'function': u'func1', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go', u'module': u'github.com/cockroachdb/cockroach/pkg/rpc.NewServerWithInterceptor', u'in_app': True, u'lineno': 197, u'filename': u'github.com/cockroachdb/cockroach/pkg/rpc/context.go'}, {u'function': u'func1', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go', u'module': u'github.com/cockroachdb/cockroach/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor', u'in_app': False, u'lineno': 48, u'filename': u'github.com/cockroachdb/cockroach/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go'}, {u'function': u'func1', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/server/serverpb/admin.pb.go', u'module': u'github.com/cockroachdb/cockroach/pkg/server/serverpb._Admin_EnqueueRange_Handler', u'in_app': True, u'lineno': 1995, u'filename': u'github.com/cockroachdb/cockroach/pkg/server/serverpb/admin.pb.go'}, {u'function': u'EnqueueRange', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/server/admin.go', u'module': u'github.com/cockroachdb/cockroach/pkg/server.(*adminServer)', u'in_app': True, u'lineno': 1588, u'filename': u'github.com/cockroachdb/cockroach/pkg/server/admin.go'}, {u'function': u'enqueueRangeLocal', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/server/admin.go', u'module': u'github.com/cockroachdb/cockroach/pkg/server.(*adminServer)', u'in_app': True, u'lineno': 1674, u'filename': u'github.com/cockroachdb/cockroach/pkg/server/admin.go'}, {u'function': u'ManuallyEnqueue', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go', u'module': u'github.com/cockroachdb/cockroach/pkg/storage.(*Store)', u'in_app': True, u'lineno': 4594, u'filename': u'github.com/cockroachdb/cockroach/pkg/storage/store.go'}, {u'function': u'process', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/storage/consistency_queue.go', u'module': u'github.com/cockroachdb/cockroach/pkg/storage.(*consistencyQueue)', u'in_app': True, u'lineno': 117, u'filename': u'github.com/cockroachdb/cockroach/pkg/storage/consistency_queue.go'}, {u'function': u'CheckConsistency', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_consistency.go', u'module': u'github.com/cockroachdb/cockroach/pkg/storage.(*Replica)', u'in_app': True, u'lineno': 161, u'filename': u'github.com/cockroachdb/cockroach/pkg/storage/replica_consistency.go'}]}
type: *log.safeError
value: replica_consistency.go:152: consistency check failed with %d inconsistent replicas | int

**Comment by tschottdorf** [comment]
@benesch looks like this is your doing? This crashed during a manual enqueue.

**Comment by benesch** [comment]
Yessir.
