### ISSUE TITLE
raft: processCommittedEntries: passed in group and fetched group objects do not match

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#3187]
via `TestRaftRemoveRace` in https://circleci.com/gh/tschottdorf/cockroach/1704

```
panic: passed in group and fetched group objects do not match
original:&{groupID:1 replicaID:9 committedTerm:6 leader:{NodeID:1 StoreID:1 ReplicaID:1} pending:map[] writing:false nodeIDs:[1 2 3]}
fetched:&{groupID:1 replicaID:10 committedTerm:6 leader:{NodeID:1 StoreID:1 ReplicaID:1} pending:map[] writing:false nodeIDs:[1 2 3]}


goroutine 6355 [running]:
github.com/cockroachdb/cockroach/multiraft.(*state).processCommittedEntry.func1.1()
	/go/src/github.com/cockroachdb/cockroach/multiraft/multiraft.go:1162 +0x32b
github.com/cockroachdb/cockroach/multiraft.(*state).start.func1()
	/go/src/github.com/cockroachdb/cockroach/multiraft/multiraft.go:668 +0x144f
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8206196e0, 0xc82061eb30)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:88 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x62
```

**Comment by BramGruneir** [comment]
I've run this test 10s of thousands of times and this new panic never occurred.  Grr.  I'll look into it.

**Comment by tschottdorf** [comment]
I also don't get that test to fail locally. Try running on CI.

**Comment by BramGruneir** [comment]
Is there a way to get a test to run a few hundred times in ci?

**Comment by tschottdorf** [comment]
You can start a build with SSH enabled, then connect to the machine and do
that manually (through Docker). It ain't pretty, but it's possible. The
machine stays up for 30 minutes, I think.

**Comment by bdarnell** [comment]
I think we can reduce this panic to a `log.Info`, same as the `!ok` case above it. It's essentially the same scenario, a delete and recreate instead of just a delete. I'm kind of surprised it's so hard to reproduce locally if it happens in CI, but I don't see any way to test this more reliably.
