### ISSUE TITLE
ui: Statements page doesn't perform well when scaling > 1k statements

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#31880]
@BramGruneir was recently running some hibernate tests on a 1-node roachprod cluster, which generated a very large number of distinct statement fingerprints on the order of 3k - 6k. When loading the statements page we noticed a few issues that are worth documenting here:

Rendering times for the page seem to scale linearly with the number of statement fingerprints on the page:
- With 3k statements the page renders in about 5s (navigating to the page, changing sort order, etc.)
- With 6k statements the page renders in about 10s

Anything running on the same thread for rendering the page is blocked during the rendering time (e.g. the loading spinner stops spinning in FF).

@couchand mentioned "all the useful computation is happening in that flurry of activity in the first ~1s.  the rest of it is React spinning its wheels on stuff.  I think this is indicating a misuse of the React API."

**Comment by BramGruneir** [comment]
By the way, to easily repro this, just run the hibernate test.

Follow the directions in https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md

And then run the hibernate test:
`bin/roachtest run hibernate`
