### ISSUE TITLE
Teach Roachprod to only destroy clusters that pass tests 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#31886]
**Is your feature request related to a problem? Please describe.**
I use roachprod and workload to test TPC-C. Originally, I took advantage of the Roachprod feature to kill the nodes after the test completes (either pass or fail). 

After experiencing a few bugs, I now usually pass `--wipe=false` so that if it fails, the cluster remains alive. This allows me to collect logs and other relevant information. 

However, this means I have to be available and able to `rochprod destroy` clusters who tests have passed to save us hosting money. For example, I have several tests that, if they work, will complete sometime between 10p.m.-2 a.m. tonight. 

**Describe the solution you'd like**
I'd like for roachprod to destroy clusters if they pass tests and to keep them alive and extend them 8 hrs if they fail. 

**Describe alternatives you've considered**
Keep the process manual. 
Pros: It works. No eng needed.
Cons: It waste money based on when tests are completed.

**Comment by tschottdorf** [comment]
Have you looked at `--debug`?

```
  -d, --debug                don't wipe and destroy cluster if test fails
```

I think this is exactly what you want. Please close if so!

**Comment by tschottdorf** [comment]
I should mention that this is a `roachtest` command. This kind of flag is misplaced in `roachprod`. If you want to emulate this behavior you could do something like


```bash
roachprod create $cluster .... && roachprod put && ... && ./bin/workload .... && roachprod destroy $cluster
```

The `&&` makes sure that a command only runs if everything "to its left" also ran successfully.

**Comment by tschottdorf** [comment]
BTW we have a repo for roachprod, where this issue should be posted (if it's really about roachprod).

**Comment by awoods187** [comment]
So something like `bin/roachtest bench '^tpccbench/nodes=9/cpu=64$$'  --user=andy --debug` would wipe if pass and stay alive if fail?

Cool!

**Comment by tschottdorf** [comment]
Yep!

**Comment by tschottdorf** [comment]
(to clarify: it would destroy if it passes, i.e. completely remove the cluster. Wiping only refers to deleting the data on the node but leaving it around)

**Comment by awoods187** [comment]
awesome. til!
