### ISSUE TITLE
storage: AdminSplit using descriptor with ReplicaID zero

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#31918]
Got this failure:

```
--- FAIL: import/tpch/nodes=8 (9943.52s)
	test.go:639,cluster.go:1453,import.go:122: pq: split at key /Table/53/1/390157478/5 failed: replica 0 is invalid: ReplicaID must not be zero
```

This originates in https://github.com/cockroachdb/cockroach/blob/a050d569f236fee50960e9b45f3052a6e0d364b4/pkg/roachpb/metadata.go#L222-L234

So we have a replica that has a NodeID and StoreID but a zero replicaID either in https://github.com/cockroachdb/cockroach/blob/62ea444e7b393bbd27e30705e1b04451bd21f49b/pkg/storage/replica_command.go#L348

or in the other call to `updateRangeDescriptor`. I'm taking a look at the logs now. Doubtful that it's at all related to this change.

PS merges are turned off in this testing.

My best bet for this error is that https://github.com/cockroachdb/cockroach/blob/62ea444e7b393bbd27e30705e1b04451bd21f49b/pkg/storage/replica_command.go#L173 returns a descriptor with a replica that has a replica with replicaID zero.

**Comment by tschottdorf** [comment]
Now that I think about it, could this be a replica for which there's only a preemptive snapshot? We send those with ReplicaID zero. Hmm, but as far as I know, those just don't have a replica in the replica descriptors slice for the receiving node. Well, #31918 will tell me something.

**Comment by tschottdorf** [comment]
@petermattis any idea about this? It promptly disappeared (for the time being) when I added debug logging.

**Comment by petermattis** [comment]
@tbg No ideas. Were you able to reproduce this before the #31968?

**Comment by petermattis** [comment]
It is possible that some other change after #31968 caused this to become less likely.

**Comment by petermattis** [comment]
@tbg You've been running a lot of import tests. Have you seen this fail recently? I'm wondering how hard I should try to reproduce this error.

**Comment by tbg** [comment]
No, haven't seen this recently.

**Comment by lunevalex** [comment]
based on the last comments, closing this as it has not reoccured.
