### ISSUE TITLE
storage: sideloading bypasses RocksDB env for some operations

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#31913]
I noticed in https://github.com/cockroachdb/cockroach/issues/31732#issuecomment-433138356 that the sideloaded storage does not perform the `TruncateTo` operation through the RocksDB env:

https://github.com/cockroachdb/cockroach/blob/fa7fb35ebd4ed4a2a4d0c1692cb1560654b73ea6/pkg/storage/replica_sideload_disk.go#L135-L149

This may or may not be a problem, but it's definitely suspicious. Note how `Clear` just above the snippet does go through extra trouble to use the env.

Perhaps this all works as intended, depending on how the RocksDB env is implemented. It does seem to work when encryption is on, probably because the env really just does the same thing writing directly to the FS would do. With encryption, is that still true, i.e. are files still passed through to the filesystem into the same location (mod scrambling the contents)? I suspect it might be, but then why does `Clear` go the extra mile through the env?

This really seems like something needs to be investigated and cleaned up.

Note that there's one case where things are definitely broken, namely the one in which you use an in-memory RocksDB instance. In that case, `TruncateTo` will snoop around on disk, but the env will keep everything in memory (i.e. `TruncateTo` becomes a no-op and garbage will pile up in-mem).

**Comment by petermattis** [comment]
@mberhault Also related to encryption at rest. It is believed that this leaks non-encrypted data to disk.

**Comment by tbg** [comment]
> It is believed that this leaks non-encrypted data to disk.

Hmm, not sure about that. The files are written through the env: https://github.com/cockroachdb/cockroach/blob/2aba151f38c6ee6cb0a8f33e666c9ff513f13edc/pkg/storage/syncing_write.go#L90-L114

@mberhault also tells me in #19783 that the encrypted files have the same size as the unencrypted version, so in my eyes this becomes a cleanup rather than a technical necessity.

**Comment by tbg** [comment]
@petermattis could storage take a look at this? Concretely, whether we're leaking unencrypted data to disk and if not, if we feel good about the status quo.

**Comment by petermattis** [comment]
I think @jbowens possibly already fixed this in 20.2. @jbowens can you see if there is anything left to do here?

**Comment by jbowens** [comment]
> @jbowens can you see if there is anything left to do here?

I think we're all good. Closing.
