### ISSUE TITLE
ui: Statement page total time is confusing

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#31991]
I talked to a user today who was confused by the "total time" displayed on the statement page. They ran a few test queries, then started to explore the UI and saw that their query had a time listed in seconds, which led them to believe their database had severe performance problems. In fact, the query performance was within expectations (this was a geo-distributed cluster so the average per execution of the query was 80ms), but they didn't grasp that we were showing the cumulative total instead of a per-query value (and the dozen or so test queries they had run were enough that the total time looked bad but not completely implausible)

I'm a fan of the "total time" metric, but it's less commonly shown in monitoring tools so I think it might be confusing to show it as the top-line number for a query. I would reorder the metrics shown in the right-hand sidebar to put mean latency, execution count, and total time in that order (and perhaps rename "total time" to something like "cumulative time").

**Comment by knz** [comment]
assigning @couchand for triage

**Comment by couchand** [comment]
We've kicked around a number of ideas for other names but nothing has stuck.  It's arguably more confusing (though less misleading) on the Statements list, where the column is just labeled "Time".

cc @piyush-singh

**Comment by vilterp** [comment]
I agree that mean service latency should be moved up to the top in the sidebar: 
![image](https://user-images.githubusercontent.com/7341/48436855-cea1ac00-e74d-11e8-8a6b-cc08e35f0881.png)

**Comment by piyush-singh** [comment]
We remove this metric from this page as it was ultimately confusing most of our users. We are instead sorting by execution count based on feedback from a few customers and Irfan.
