### ISSUE TITLE
sql: Support the "at tz" operator

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#32005]
Support `<timestamp value> at tz` to convert timezones 

This is a top requested telemetry feature.

**Comment by bobvawter** [comment]
FYI: looking up named zones is slow, might want to properly export https://github.com/cockroachdb/cockroach/blob/master/pkg/util/timeutil/pgdate/zone_cache.go and/or see if #31978 has been solved.

**Comment by tlvenn** [comment]
I believe this is the same ask as in #16382.
