### ISSUE TITLE
perf: test AWS without nobarrier

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#32010]
**Describe the problem**
```
roachprod run andy-tpcc:1 -- "./cockroach workload fixtures import tpcc --warehouses=2000 --db=tpcc"
Error: importing fixture: importing table order_line: pq: job 395960823761633281: node liveness error: restarting in background
Error:  exit status 1
```
```
181030 17:08:53.890789 156378 storage/queue.go:791  [n1,raftlog,s1,r3730/1:/Table/54/1/22{1/858â¦-2/901â¦}] aborted during DistSender.Send: context deadline exceeded
E181030 17:08:53.890867 156379 storage/replica_range_lease.go:293  [n1,s1,r3730/1:/Table/54/1/22{1/858â¦-2/901â¦}] aborted in distSender: context canceled
E181030 17:09:01.506986 156587 storage/queue.go:791  [n1,raftlog,s1,r3674/1:/Table/54/1/174{8/323â¦-9/363â¦}] aborted during DistSender.Send: context deadline exceeded
E181030 17:09:01.507065 156588 storage/replica_range_lease.go:293  [n1,s1,r3674/1:/Table/54/1/174{8/323â¦-9/363â¦}] aborted in distSender: context canceled
E181030 17:09:01.565482 156600 storage/queue.go:791  [n1,raftlog,s1,r3287/1:/Table/54/1/162{2/299â¦-3/338â¦}] aborted during DistSender.Send: context deadline exceeded
E181030 17:09:01.565592 156601 storage/replica_range_lease.go:293  [n1,s1,r3287/1:/Table/54/1/162{2/299â¦-3/338â¦}] aborted in distSender: context canceled
E181030 17:09:01.596697 156574 storage/queue.go:791  [n1,raftlog,s1,r3618/1:/Table/54/1/179{3/540â¦-4/580â¦}] aborted during DistSender.Send: context deadline exceeded
E181030 17:09:01.596831 156575 storage/replica_range_lease.go:293  [n1,s1,r3618/1:/Table/54/1/179{3/540â¦-4/580â¦}] aborted in distSender: context canceled
E181030 17:09:06.540386 157433 server/admin.go:1142  admin-jobs: context deadline exceeded
```
**To Reproduce**
```
roachprod create andy-tpcc -n 4 --clouds=aws
roachprod stage andy-tpcc cockroach
roachprod stage andy-tpcc workload
roachprod run andy-tpcc:1-3 -- 'sudo umount /mnt/data1; sudo mount -o discard,defaults,nobarrier /dev/nvme1n1 /mnt/data1/; mount | grep /mnt/data1'
roachprod start andy-tpcc
roachprod run andy-tpcc:1 -- "./cockroach workload fixtures import tpcc --warehouses=2000 --db=tpcc"
```
**Expected behavior**
Load the fixture without a node liveness failure 

**Additional data / screenshots**
![image](https://user-images.githubusercontent.com/22278911/47736374-f4ef2400-dc44-11e8-9d54-606487445cad.png)

**Environment:**
 - CockroachDB master 
[Logs.zip](https://github.com/cockroachdb/cockroach/files/2530771/Logs.zip)

`andy-tpcc`

**Comment by awoods187** [comment]
Fixed this for the next run but will leave this up in case any from core wants to take a look

**Comment by tschottdorf** [comment]
I think we're all pretty back up, don't keep this running for me.

**Comment by awoods187** [comment]
<img width="1552" alt="screen shot 2018-10-30 at 2 02 12 pm" src="https://user-images.githubusercontent.com/22278911/47739751-74342600-dc4c-11e8-81ad-36210db68728.png">
 Now shows one dead node

**Comment by tschottdorf** [comment]
Did the next runs reproduce this problem (it's unclear to me whether the last picture was from the same or a following run)?

**Comment by awoods187** [comment]
I didn't run this again (due to having run it on all 4 instead of only 3)

**Comment by tbg** [comment]
Ok. I'm going to retitle the issue to perf test AWS without nobarrier.

**Comment by nvanbenschoten** [comment]
This has since been tested.

**Comment by petermattis** [comment]
@nvanbenschoten What was the result of running with `barrier` on AWS? I ask because I recently tested a WAL sync benchmark and saw essentially no difference on AWS between `barrier` and `nobarrier`.

**Comment by nvanbenschoten** [comment]
We see significantly less difference on AWS than we do on GCP. This was discussed in the 2018 cloud report: https://www.cockroachlabs.com/blog/2018_cloud_report/.
