### ISSUE TITLE
sql: SAVEPOINT should open an implicit transaction

### ISSUE THREAD

**Issue by bobvawter** [cockroachdb/cockroach#32022]
Right now, we require `BEGIN; SAVEPOINT`.  A customer has requested that we allow `SAVEPOINT` to create an implicit transaction if one is not currently open.

**Comment by knz** [comment]
This has been discussed before. PostgreSQL does not do this. Neither does any other SQL engine I know that also supports savepoints.

I suspect there is a bug in the client app which causes it to mistakenly issue SAVEPOINT without issuing BEGIN first. This bug should be investigated first.

We can't just say "CockroachDB should introduce support for semantics that's nonsensical in other SQL dialects" without a very strong, clear use case.

Any chance you can dig out where this request is coming from?

**Comment by knz** [comment]
@rolandcrosby I _believe_ I recall this conversation from a customer. Do you recall?

Further than that, until/unless there is a clear use case, this "feature request" as-is is a clear no from me. Closing as unactionable for the time being.

**Comment by rolandcrosby** [comment]
This came out of a customer/partner request, but they have since been able to work around the difference in behavior. No action required at this time. Thanks!
