### ISSUE TITLE
sql: panic in UPDATE with subquery (v2.0.6)

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#32054]
https://sentry.io/cockroach-labs/cockroachdb/issues/748121057/

conn_executor.go:521: panic while executing 1 statements: UPDATE _ SET (_, _) = (SELECT (_ + $1), $2 FROM _ AS _ INNER JOIN _ AS _ ON _._ = _._ WHERE (_._ = $3) AND (_._ = _)) WHERE (_ = $3) AND ((_ + $1) >= _): caused by <redacted>

github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func2

> stacktrace: {u'frames': [{u'function': u'Next', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/update.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*updateNode)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/update.go', u'lineno': 329, u'in_app': True}, {u'function': u'extractValues', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/update.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*tupleSlot)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/update.go', u'lineno': 508, u'in_app': True}, {u'function': u'panicdottypeI', u'abs_path': u'/usr/local/go/src/runtime/iface.go', u'module': u'runtime', u'filename': u'runtime/iface.go', u'lineno': 254, u'in_app': False}, {u'function': u'panicdottypeE', u'abs_path': u'/usr/local/go/src/runtime/iface.go', u'module': u'runtime', u'filename': u'runtime/iface.go', u'lineno': 244, u'in_app': False}, {u'function': u'gopanic', u'abs_path': u'/usr/local/go/src/runtime/panic.go', u'module': u'runtime', u'filename': u'runtime/panic.go', u'lineno': 505, u'in_app': False}, {u'function': u'call32', u'abs_path': u'/usr/local/go/src/runtime/asm_amd64.s', u'module': u'runtime', u'filename': u'runtime/asm_amd64.s', u'lineno': 573, u'in_app': False}, {u'function': u'func2', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'lineno': 489, u'in_app': True}]}
type: *log.safeError
value: conn_executor.go:521: panic while executing 1 statements: UPDATE _ SET (_, _) = (SELECT (_ + $1), $2 FROM _ AS _ INNER JOIN _ AS _ ON _._ = _._ WHERE (_._ = $3) AND (_._ = _)) WHERE (_ = $3) AND ((_ + $1) >= _): caused by <redacted>

```
github.com/cockroachdb/cockroach/pkg/sql/update.go in extractValues at line 508
github.com/cockroachdb/cockroach/pkg/sql/update.go in Next at line 329
```

**Comment by knz** [comment]
This is in v2.0.6

**Comment by jordanlewis** [comment]
```
func (ts tupleSlot) extractValues(row tree.Datums) tree.Datums {
        return row[ts.sourceIndex].(*tree.DTuple).D
}
```

The panic is on the `return` line.

**Comment by knz** [comment]
IIRC @BramGruneir  fixed this in master/2.2; @awoods187 suggests to backport to 2.0.

**Comment by BramGruneir** [comment]
I don't even remember if I did.  I remember looking into it.

**Comment by knz** [comment]
Ok so I went and double checked and we corrected a panic for UPSERT, not UPDATE.

I also double-checked and this code was not changed since 2.0, so if there's a bug there, it's still in `master`.

**Comment by knz** [comment]
Hah! found the bug. Both in `master` and 2.0. PR incoming.
