### ISSUE TITLE
sql: ease the cancelling of queries

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#32055]
See the discussion here:

https://github.com/cockroachdb/cockroach/issues/31763#issuecomment-434652691

It's cumbersome for a client to identify its own session ID and the ID of queries it may want to cancel.

The following should happen:

- [ ] expose the current session's ID via a session var
- [ ] print out the session ID alongside the query ID in `show queries`, so that it becomes possible to filter queries for a given session
- [ ] document how to use all this as a replacement for the pg cancel protocol.

**Comment by fastest963** [comment]
For now I'm doing:
```
CANCEL QUERY IF EXISTS (SELECT query_id FROM [SHOW CLUSTER QUERIES] WHERE client_address=$1 LIMIT 1)
```

Ideally I'd be able to connect to the same node that the query was sent to so I wouldn't have to wait for `SHOW CLUSTER QUERIES`, but that's not easy with what the driver currently exposes.

**Comment by knz** [comment]
@fastest963 can you explain this futher:

> Ideally I'd be able to connect to the same node that the query was sent to so I wouldn't have to wait for SHOW CLUSTER QUERIES,

The node ID is available in the output of both `show queries` and `show sessions`. You can use that to connect to the node with the session directly. What do you miss?

**Comment by fastest963** [comment]
> but that's not easy with what the driver currently exposes.

There isn't a great way for our application (using the `pq` or `pgx` driver) to identify which connections are connected to which IPs. I didn't mean to insinuate this is a problem with CockroachDB, just that there is more driver work necessary to make this easy.

That said, is there a SQL call to get a list of nodes so I can associate `node_id` to node address?

**Comment by knz** [comment]
We have an experimental/internal table called `crdb_internal.gossip_nodes` which you can query from. If you could confirm that is generally useful to you, we could turn it into a feature?

**Comment by fastest963** [comment]
That seems like it would solve my issue, yes.

**Comment by jeffliu27** [comment]
@knz I would love to work on this issue! As a first time contributor, could you give me a bit of guidance on the issue?

**Comment by jordanlewis** [comment]
@jeffliu27 the first step is to add a new session variable that exposes the session id. The code for session variables lives in `pkg/sql/vars.go`. You can follow the pattern and add a new (read-only) one called `session_id`.

To get access to the session id from the read path of the var, you'll need to add it to a structure called `extendedEvalContext` and populate it in `connExecutor.initEvalCtx` which lives in `pkg/sql/conn_executor.go`. The session id itself can be found as a field on the `connExecutor`.

Next you'll need to add the session id to the 2 `crdb_internal` tables in question: `node_queries` and `cluster_queries`. The schema is in `pkg/sql/crdb_internal.go, and the function that populates them is in `populateQueriesTable`.

Hope that helps, and thanks so much for volunteering to contribute!

**Comment by shweta1207** [comment]
It seems that no one is working on this issue currently. I would like to work on this. Can you assign this to me ?

**Comment by knz** [comment]
We don't typically assign issues until some of the work was started already. If you're interested, go ahead.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by georgebuckerfield** [comment]
I've done some work on this - session ID is available as a variable:

```
root@:26257/defaultdb> show session_id;
             session_id             
+----------------------------------+
  15cded3a455c77040000000000000001  
(1 row)

Time: 3.9773ms
```
And from `show queries`:
```
root@:26257/defaultdb> show queries;
              query_id             | node_id |            session_id            | user_name |              start               |        query         | client_address  | application_name | distributed |   phase    
+----------------------------------+---------+----------------------------------+-----------+----------------------------------+----------------------+-----------------+------------------+-------------+-----------+
  15cdee07ca3df59c0000000000000001 |       1 | 15cded3a455c77040000000000000001 | root      | 2019-10-15 21:06:02.246986+00:00 | SHOW CLUSTER QUERIES | 127.0.0.1:39454 | $ cockroach sql  |    false    | executing  
(1 row)

Time: 8.025ms
```
I'll try and get a PR submitted, I just need to tidy up the commits.

**Comment by jordanlewis** [comment]
Fantastic! Thanks for taking a look at this. We'll look forward to reviewing your PR.

**Comment by georgebuckerfield** [comment]
Thanks @jordanlewis - PR is ready to review when you a chance.
