### ISSUE TITLE
sentry: panic when using a window function in a render expression

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#32050]
https://sentry.io/cockroach-labs/cockroachdb/issues/747807062/

conn_executor.go:521: panic while executing 1 statements: SELECT _, _, _, _, count(_) OVER (ORDER BY _) AS _, sum(_) OVER (PARTITION BY count(_) OVER (ORDER BY _) ORDER BY _) FROM (SELECT _, _ - lag(_, _, _) OVER (ORDER BY _) AS _, lead(_, _, _) OVER (ORDER BY _) - _ AS _, IF((_ - lag(_, _, _) OVER (ORDER BY _)) >= _, _, _) AS _ FROM _._._ WHERE (((_ = _) AND (_ = _)) OR ((_ = _) AND (_ = _))) ORDER BY _): caused by <redacted>

github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func2

> stacktrace: {u'frames': [{u'function': u'func3', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go', u'lineno': 260, u'in_app': True}, {u'function': u'ServeConn', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*Server)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'lineno': 491, u'in_app': True}, {u'function': u'run', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'lineno': 911, u'in_app': True}, {u'function': u'execStmt', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'lineno': 87, u'in_app': True}, {u'function': u'execStmtInOpenState', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'lineno': 349, u'in_app': True}, {u'function': u'dispatchToExecutionEngine', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'lineno': 582, u'in_app': True}, {u'function': u'execWithLocalEngine', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'lineno': 634, u'in_app': True}, {u'function': u'forEachRow', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'lineno': 689, u'in_app': True}, {u'function': u'Next', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/window.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*windowNode)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/window.go', u'lineno': 171, u'in_app': True}, {u'function': u'Next', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/render.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*renderNode)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/render.go', u'lineno': 344, u'in_app': True}, {u'function': u'renderRow', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/render.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*renderNode)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/render.go', u'lineno': 697, u'in_app': True}, {u'function': u'Eval', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FuncExpr)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go', u'lineno': 3312, u'in_app': True}, {u'function': u'sigpanic', u'abs_path': u'/usr/local/go/src/runtime/signal_unix.go', u'module': u'runtime', u'filename': u'runtime/signal_unix.go', u'lineno': 388, u'in_app': False}, {u'function': u'panicmem', u'abs_path': u'/usr/local/go/src/runtime/panic.go', u'module': u'runtime', u'filename': u'runtime/panic.go', u'lineno': 63, u'in_app': False}, {u'function': u'gopanic', u'abs_path': u'/usr/local/go/src/runtime/panic.go', u'module': u'runtime', u'filename': u'runtime/panic.go', u'lineno': 505, u'in_app': False}, {u'function': u'call32', u'abs_path': u'/usr/local/go/src/runtime/asm_amd64.s', u'module': u'runtime', u'filename': u'runtime/asm_amd64.s', u'lineno': 573, u'in_app': False}, {u'function': u'func2', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'lineno': 489, u'in_app': True}]}
type: *log.safeError
value: conn_executor.go:521: panic while executing 1 statements: SELECT _, _, _, _, count(_) OVER (ORDER BY _) AS _, sum(_) OVER (PARTITION BY count(_) OVER (ORDER BY _) ORDER BY _) FROM (SELECT _, _ - lag(_, _, _) OVER (ORDER BY _) AS _, lead(_, _, _) OVER (ORDER BY _) - _ AS _, IF((_ - lag(_, _, _) OVER (ORDER BY _)) >= _, _, _) AS _ FROM _._._ WHERE (((_ = _) AND (_ = _)) OR ((_ = _) AND (_ = _))) ORDER BY _): caused by <redacted>

**Comment by jordanlewis** [comment]
```
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go in func2 at line 489
Called from: runtime/asm_amd64.s in call32
github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go in Eval at line 3312
github.com/cockroachdb/cockroach/pkg/sql/render.go in renderRow at line 697
github.com/cockroachdb/cockroach/pkg/sql/render.go in Next at line 344
github.com/cockroachdb/cockroach/pkg/sql/window.go in Next at line 171
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go in forEachRow at line 689
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go in execWithLocalEngine at line 634
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go in dispatchToExecutionEngine at line 582
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go in execStmtInOpenState at line 349
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go in execStmt at line 87
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go in run at line 911
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go in ServeConn at line 491
github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go in func3 at line 260
```

**Comment by jordanlewis** [comment]
This is a new one: looks like an NPE in the last line in the following snippet, perhaps indicating an improperly initialized window function? Either the `FuncExpr.fn` pointer to an `Overload` was nil, or the `Overload.Fn` func itself was nil.

```
// Eval implements the TypedExpr interface.
func (expr *FuncExpr) Eval(ctx *EvalContext) (Datum, error) {
        args := NewDTupleWithCap(len(expr.Exprs))
        for _, e := range expr.Exprs {
                arg, err := e.(TypedExpr).Eval(ctx)
                if err != nil {
                        return nil, err
                }
                if arg == DNull && !expr.fn.NullableArgs {
                        return DNull, nil
                }
                args.D = append(args.D, arg)
        }

        res, err := expr.fn.Fn(ctx, args.D)
```

**Comment by jordanlewis** [comment]
Also worth noting that it's 2.0.2.

**Comment by blkerby** [comment]
Possibly related to https://github.com/cockroachdb/cockroach/issues/33340?

**Comment by jordanlewis** [comment]
This would probably not be a problem if the optimizer were planning window functions.

**Comment by jordanlewis** [comment]
cc @yuzefovich

**Comment by asubiotto** [comment]
This panic came from local sql execution and this code has been removed in #34383. However I managed to reproduce this (or something very similar to this) in distsql when trying to fill in the blanks:
```
root@:26257/defaultdb> SELECT * FROM ints;
  x
+---+
  1
  5
  3
  2
  6
  7
  7
(7 rows)

Time: 5.141ms
root@:26257/defaultdb> SELECT x, count(*) OVER (ORDER BY x) AS y, SUM(x) OVER (PARTITION BY count(x) OVER (ORDER BY x) ORDER BY x) FROM ints;
driver: bad connection
warning: connection lost!
```
cc @yuzefovich 

Stack trace:
```
panic while executing 1 statements: SELECT _, count(*) OVER (ORDER BY _) AS _, sum(_) OVER (PARTITION BY count(_) OVER (ORDER BY _) ORDER BY _) FROM _; caused by runtime error: invalid memory address or nil pointer dereference

goroutine 2006 [running]:
runtime/debug.Stack(0x746b660, 0xc00894c880, 0xc000000003)
	/usr/local/Cellar/go/1.11.2/libexec/src/runtime/debug/stack.go:24 +0xa7
github.com/cockroachdb/cockroach/pkg/util/log.ReportPanic(0x746b660, 0xc00894c880, 0xc00026b300, 0x6b057c0, 0xc008bbdd70, 0x1)
	/Users/asubiotto/go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:212 +0xa6
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc0050d3b00, 0x746b660, 0xc00894c880, 0x68c03a0, 0x9244ff0)
	/Users/asubiotto/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:708 +0x2dd
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc0050d3b00, 0x746b660, 0xc00894c880)
	/Users/asubiotto/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:427 +0x61
panic(0x68c03a0, 0x9244ff0)
	/usr/local/Cellar/go/1.11.2/libexec/src/runtime/panic.go:513 +0x1b9
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FuncExpr).Eval(0xc008ab08c0, 0xc00569a6e0, 0x7488c00, 0x92de1e0, 0x92de1e0, 0x0)
	/Users/asubiotto/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go:3615 +0xb0
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*exprHelper).eval(0xc0091f9c90, 0xc0066cf7a0, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0)
	/Users/asubiotto/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/expr.go:194 +0xe5
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcOutputHelper).ProcessRow(0xc0090cb818, 0x746b720, 0xc008b67b00, 0xc0066cf7a0, 0x2, 0x2, 0xc00594ac00, 0xc00594ac70, 0x0, 0x0, ...)
	/Users/asubiotto/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:375 +0x2f6
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).ProcessRowHelper(0xc0090cb800, 0xc0066cf7a0, 0x2, 0x2, 0x0, 0xe0e43da168f8d7dc, 0x6889d00)
	/Users/asubiotto/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:778 +0x78
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*tableReader).Next(0xc0090cb800, 0xc0082ffbc0, 0xc008bbd950, 0xc007695200, 0xc006db5dc0)
	/Users/asubiotto/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/tablereader.go:290 +0x77
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*windower).accumulateRows(0xc006bad800, 0xc000082800, 0xc006db5e48, 0x400e70f, 0xc0082ffbc0, 0x20)
	/Users/asubiotto/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/windower.go:317 +0x3e
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*windower).Next(0xc006bad800, 0xc0082ffbc0, 0x0, 0xc000082800, 0xc006db5e78)
	/Users/asubiotto/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/windower.go:277 +0x146
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*windower).accumulateRows(0xc009fbc000, 0x400ef98, 0x20, 0x69acec0, 0xc0090f6e01, 0xc0082ffbc0)
	/Users/asubiotto/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/windower.go:317 +0x3e
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*windower).Next(0xc009fbc000, 0x8, 0x746b720, 0xc008bbd920, 0x746b720)
	/Users/asubiotto/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/windower.go:277 +0x146
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.Run(0x746b720, 0xc008bbd920, 0x7477c60, 0xc009fbc000, 0x745cc20, 0xc0053e7c00)
	/Users/asubiotto/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go:175 +0x35
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).Run(0xc009fbc000, 0x746b720, 0xc008b675c0)
	/Users/asubiotto/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:801 +0x92
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Run(0xc00517f6c0, 0x746b720, 0xc008b675c0, 0x6e10458, 0x0, 0x0)
	/Users/asubiotto/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:624 +0x1ec
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc000457a40, 0xc0066cf1a0, 0xc00971af30, 0xc006db68a8, 0xc0008fb8c0, 0xc0050d3f10, 0x0)
	/Users/asubiotto/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:252 +0x8ad
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0xc000457a40, 0x746b720, 0xc008b66c00, 0xc0050d3f10, 0xc0066cf1a0, 0xc00971af30, 0x746d9e0, 0xc007694480, 0xc0008fb8c0)
	/Users/asubiotto/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:839 +0x227
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc0050d3b00, 0x746b720, 0xc008b66c00, 0xc0050d3e50, 0x3, 0xe9e86d0, 0xc0068ad290, 0x1, 0x0, 0x0)
	/Users/asubiotto/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1064 +0x283
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc0050d3b00, 0x746b720, 0xc008b66c00, 0xc0050d3e50, 0xe9e86d0, 0xc0068ad290, 0x0, 0x0)
	/Users/asubiotto/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:909 +0x648
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc0050d3b00, 0x746b720, 0xc008b66c00, 0x7471260, 0xc00894dcc0, 0xc0055f3122, 0x75, 0x0, 0x0, 0x0, ...)
	/Users/asubiotto/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:447 +0xd90
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc0050d3b00, 0x746b720, 0xc008b66c00, 0x7471260, 0xc00894dcc0, 0xc0055f3122, 0x75, 0x0, 0x0, 0x0, ...)
	/Users/asubiotto/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:103 +0x610
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc0050d3b00, 0x746b660, 0xc00894c880, 0xc000b6ee78, 0x5400, 0x15000, 0xc000b6ef10, 0xc000387ee0, 0x0, 0x0)
	/Users/asubiotto/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1178 +0x21f0
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc000a8c1a0, 0x746b660, 0xc00894c880, 0xc0050d3b00, 0x5400, 0x15000, 0xc000b6ef10, 0xc000387ee0, 0x0, 0x0)
	/Users/asubiotto/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:429 +0xce
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl.func4(0xc000a8c1a0, 0xc000294000, 0xc00500cf84, 0xc000387ee0, 0x746b660, 0xc00894c880, 0xc0050d3b00, 0x5400, 0x15000, 0xc000b6ef10, ...)
	/Users/asubiotto/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:331 +0xcf
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl
	/Users/asubiotto/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:314 +0x1040
```

cockroach version: fb3c5c09c17b737f8aa324d6d56a1a4ebd1109bf

**Comment by asubiotto** [comment]
![image](https://user-images.githubusercontent.com/10560359/53758969-3a3e8f00-3e8d-11e9-8783-def0c3991b03.png)

**Comment by asubiotto** [comment]
Looks like this has something to do with the window function being the render expression. The panic occurs here:
https://github.com/cockroachdb/cockroach/blob/1a796ba1524c3db5225bf3be387602c5fea25bd1/pkg/sql/sem/tree/eval.go#L3615
Because `expr.fn.Fn` is nil. However, its `expr.fn.WindowFunc` is set.
