### ISSUE TITLE
kv: Read-only rollback is recorded as committed

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#32061]
#31599 ignores the `Commit` flag of the `EndTransactionRequest`, with the result that any read-only transaction will be recorded in the metrics as "committed" even if the user did `BEGIN; SELECT ...; ROLLBACK`. 

I think the incorrect metrics are the only consequence of this bug, but I'm not 100% sure. I'm looking at whether client/txn or the sql executor might be doing something funny with the transaction that could lead to #31823.

**Comment by knz** [comment]
Incorrect metrics are sorta a big deal, because we're so reliant on them to troubleshoot problems. Having all user-aborted txns included in the successful txn count could mask an otherwise unexpected increase in aborted txns.

(No comment on the other thing.)

**Comment by andreimatei** [comment]
This had been fixed in #61110
