### ISSUE TITLE
sentry: stopper.go:179: string

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#32095]
https://sentry.io/cockroach-labs/cockroachdb/issues/749230798/

stopper.go:179: string

baidu/dba-sz/ndb/pkg/storage.(*raftLogger).Panicf

> stacktrace: {u'frames': [{u'function': u'func1', u'abs_path': u'/go/src/baidu/dba-sz/ndb/pkg/util/stop/stopper.go', u'module': u'baidu/dba-sz/ndb/pkg/util/stop.(*Stopper).RunWorker', u'filename': u'baidu/dba-sz/ndb/pkg/util/stop/stopper.go', u'lineno': 196, u'in_app': True}, {u'function': u'func2', u'abs_path': u'/go/src/baidu/dba-sz/ndb/pkg/storage/scheduler.go', u'module': u'baidu/dba-sz/ndb/pkg/storage.(*raftScheduler).Start', u'filename': u'baidu/dba-sz/ndb/pkg/storage/scheduler.go', u'lineno': 167, u'in_app': True}, {u'function': u'worker', u'abs_path': u'/go/src/baidu/dba-sz/ndb/pkg/storage/scheduler.go', u'module': u'baidu/dba-sz/ndb/pkg/storage.(*raftScheduler)', u'filename': u'baidu/dba-sz/ndb/pkg/storage/scheduler.go', u'lineno': 227, u'in_app': True}, {u'function': u'processRequestQueue', u'abs_path': u'/go/src/baidu/dba-sz/ndb/pkg/storage/store.go', u'module': u'baidu/dba-sz/ndb/pkg/storage.(*Store)', u'filename': u'baidu/dba-sz/ndb/pkg/storage/store.go', u'lineno': 3550, u'in_app': True}, {u'function': u'processRaftRequest', u'abs_path': u'/go/src/baidu/dba-sz/ndb/pkg/storage/store.go', u'module': u'baidu/dba-sz/ndb/pkg/storage.(*Store)', u'filename': u'baidu/dba-sz/ndb/pkg/storage/store.go', u'lineno': 3188, u'in_app': True}, {u'function': u'withRaftGroup', u'abs_path': u'/go/src/baidu/dba-sz/ndb/pkg/storage/replica.go', u'module': u'baidu/dba-sz/ndb/pkg/storage.(*Replica)', u'filename': u'baidu/dba-sz/ndb/pkg/storage/replica.go', u'lineno': 581, u'in_app': True}, {u'function': u'withRaftGroupLocked', u'abs_path': u'/go/src/baidu/dba-sz/ndb/pkg/storage/replica.go', u'module': u'baidu/dba-sz/ndb/pkg/storage.(*Replica)', u'filename': u'baidu/dba-sz/ndb/pkg/storage/replica.go', u'lineno': 564, u'in_app': True}, {u'function': u'func4', u'abs_path': u'/go/src/baidu/dba-sz/ndb/pkg/storage/store.go', u'module': u'baidu/dba-sz/ndb/pkg/storage.(*Store).processRaftRequest', u'filename': u'baidu/dba-sz/ndb/pkg/storage/store.go', u'lineno': 3187, u'in_app': True}, {u'function': u'Step', u'abs_path': u'/go/src/baidu/dba-sz/ndb/vendor/github.com/coreos/etcd/raft/rawnode.go', u'module': u'baidu/dba-sz/ndb/vendor/github.com/coreos/etcd/raft.(*RawNode)', u'filename': u'baidu/dba-sz/ndb/vendor/github.com/coreos/etcd/raft/rawnode.go', u'lineno': 195, u'in_app': False}, {u'function': u'Step', u'abs_path': u'/go/src/baidu/dba-sz/ndb/vendor/github.com/coreos/etcd/raft/raft.go', u'module': u'baidu/dba-sz/ndb/vendor/github.com/coreos/etcd/raft.(*raft)', u'filename': u'baidu/dba-sz/ndb/vendor/github.com/coreos/etcd/raft/raft.go', u'lineno': 810, u'in_app': False}, {u'function': u'stepFollower', u'abs_path': u'/go/src/baidu/dba-sz/ndb/vendor/github.com/coreos/etcd/raft/raft.go', u'module': u'baidu/dba-sz/ndb/vendor/github.com/coreos/etcd/raft', u'filename': u'baidu/dba-sz/ndb/vendor/github.com/coreos/etcd/raft/raft.go', u'lineno': 1081, u'in_app': False}, {u'function': u'handleHeartbeat', u'abs_path': u'/go/src/baidu/dba-sz/ndb/vendor/github.com/coreos/etcd/raft/raft.go', u'module': u'baidu/dba-sz/ndb/vendor/github.com/coreos/etcd/raft.(*raft)', u'filename': u'baidu/dba-sz/ndb/vendor/github.com/coreos/etcd/raft/raft.go', u'lineno': 1135, u'in_app': False}, {u'function': u'commitTo', u'abs_path': u'/go/src/baidu/dba-sz/ndb/vendor/github.com/coreos/etcd/raft/log.go', u'module': u'baidu/dba-sz/ndb/vendor/github.com/coreos/etcd/raft.(*raftLog)', u'filename': u'baidu/dba-sz/ndb/vendor/github.com/coreos/etcd/raft/log.go', u'lineno': 191, u'in_app': False}, {u'function': u'Panicf', u'abs_path': u'/go/src/baidu/dba-sz/ndb/pkg/storage/raft.go', u'module': u'baidu/dba-sz/ndb/pkg/storage.(*raftLogger)', u'filename': u'baidu/dba-sz/ndb/pkg/storage/raft.go', u'lineno': 115, u'in_app': True}, {u'function': u'gopanic', u'abs_path': u'/usr/local/go/src/runtime/panic.go', u'module': u'runtime', u'filename': u'runtime/panic.go', u'lineno': 489, u'in_app': False}, {u'function': u'call32', u'abs_path': u'/usr/local/go/src/runtime/asm_amd64.s', u'module': u'runtime', u'filename': u'runtime/asm_amd64.s', u'lineno': 514, u'in_app': False}]}
type: *log.safeError
value: stopper.go:179: string

**Comment by jordanlewis** [comment]
Not us.
