### ISSUE TITLE
server: one unaccounted-for range

### ISSUE THREAD

**Issue by couchand** [cockroachdb/cockroach#32099]
After @celiala's PR #31830, almost all the ranges are accounted for in the UI.  However, there seems to be a discrepancy there, and one range is missing.

See: https://github.com/cockroachdb/cockroach/pull/31830#discussion_r229870404

**Comment by celiala** [comment]
Appreciate you digging into this, Alex! I think this bread crumb should get me to a solution, but I'll reach out if I run into trickiness. Thanks!

**Comment by knz** [comment]
@celiala @dhartunian is this issue still current?
