### ISSUE TITLE
sql: keep track of execution stats for every query

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#32096]
Execution stats collection will help a variety of systems understand the cost of a query. Understanding the cost of a query is needed in at least 3 use cases:
1. Optimizer: Feedback to the optimizer so the optimizer knows how a plan is faring on the execution side.
2. Admin-UI: User visible information on a statement execution on the Admin-UI to aid in performance tuning
3. Cluster protection system (yet to be built): Understanding the cost of a query by a protection system can make it make good decision on which queries to block when a cluster is loaded.

There is an existing query tracing mechanism that can be used to collect such information, but I've heard that it is quite expensive to turn on for all query executions. Turning it on for a sample will work but it will affect the performance of some queries which will affect max latency for a query type.

I think we need to think about a cheap tracing mechanism that collects execution stats for every query.

**Comment by vivekmenezes** [comment]
@andy-kimball @jordanlewis

**Comment by jordanlewis** [comment]
@asubiotto and co doing this soon.
