### ISSUE TITLE
sql: join processor does not preserve order of left operand

### ISSUE THREAD

**Issue by brentbrent** [cockroachdb/cockroach#32108]
**Describe the problem**

My schema has several interleaved tables that are joined together in a select query. When filtering results using a `where` clause the results come back as expected. When I instead try to filter on the same column in an `on` clause referencing a boolean column that comes back `NULL` in a left join when I'm checking for the value `false` (Yes, it's a mouthful and pretty convoluted) the query fails with `ERROR:  detected badly ordered input.`

Example queries:

Success (Filter on `deleted` in `where`)
```
test_db=> SELECT * FROM cr_users u LEFT JOIN cr_relationships r ON u.user_key=r.user_key LEFT JOIN cr_user_emails e ON u.user_key = e.user_key AND e.deleted = false WHERE (r.deleted IS NOT NULL AND r.deleted = false) AND u.user_key=ANY ARRAY ['5477d5d7-64e3-4e31-979a-8eb59a775214', '4efd269c-f755-4f8b-a7ce-b0d10eba19c3'];
```

Success (Filter on `deleted=true` in `on`)
```
test_db=> SELECT * FROM cr_users u LEFT JOIN cr_relationships r ON u.user_key=r.user_key AND r.deleted = true LEFT JOIN cr_user_emails e ON u.user_key = e.user_key AND e.deleted = false WHERE u.user_key=ANY ARRAY ['5477d5d7-64e3-4e31-979a-8eb59a775214', '4efd269c-f755-4f8b-a7ce-b0d10eba19c3'];
```

Fail (Filter on `deleted=false` in `on`)
```
test_db=> SELECT * FROM cr_users u LEFT JOIN cr_relationships r ON u.user_key=r.user_key AND r.deleted = false LEFT JOIN cr_user_emails e ON u.user_key = e.user_key AND e.deleted = false WHERE u.user_key=ANY ARRAY ['5477d5d7-64e3-4e31-979a-8eb59a775214', '4efd269c-f755-4f8b-a7ce-b0d10eba19c3'];
ERROR:  detected badly ordered input: ...
```

**To Reproduce**

I've attached a sql file taken from our test database (Sorry, I didn't clean up column names and such) that you can use to reproduce.

[backup.txt](https://github.com/cockroachdb/cockroach/files/2539999/backup.txt)

```
cockroach sql --database=... < ~/backup.sql
```
Then run the query:
```
select * from cr_users u left join cr_relationships r on u.user_key=r.user_key and r.deleted = false left join cr_user_emails e on u.user_key = e.user_key and e.deleted = false where u.user_key=any array ['5477d5d7-64e3-4e31-979a-8eb59a775214', '4efd269c-f755-4f8b-a7ce-b0d10eba19c3'];

ERROR:  detected badly ordered input: [***SNIP***] > [***SNIP***], but expected '<'
```
to see the error.

**Expected behavior**
I should get results back not an error.

**Additional data / screenshots**
Attached

**Environment:**
```
$ cockroach version
Build Tag:    v2.1.0
Build Time:   2018/10/30 12:32:34
Distribution: CCL
Platform:     linux amd64 (x86_64-unknown-linux-gnu)
Go Version:   go1.10.3
C Compiler:   gcc 6.3.0
Build SHA-1:  f0dd1dc2d2500155c8b36330ae3d6932c13c1027
Build Type:   release
```

Connected via psql client
```
$ psql --version
psql (PostgreSQL) 10.5
```

**Additional context**
n/a

**Comment by jordanlewis** [comment]
@RaduBerinde, I think this might be related to something you fixed recently?

**Comment by RaduBerinde** [comment]
@jordanlewis I think it's a different issue (that was specific to aggregations). We are probably advertising an incorrect ordering from a left join. I will investigate tomorrow.

@brentbrent thanks for the detailed info! As a workaround, you can try to disable the optimizer, which reverts to what v2.0 would do using `SET optimizer = off` in the session (there is also a `defaults.sql.optimizer` cluster setting which controls the default value of that setting).

**Comment by RaduBerinde** [comment]
@brentbrent thank you again for the sql file which makes reproducing this very easy!

I have a slightly smaller repro: after running the backup.txt:
```
SELECT u.user_key, r.user_key FROM cr_users u LEFT JOIN cr_relationships r ON u.user_key=r.user_key AND r.deleted = false WHERE u.user_key IN ('5477d5d7-64e3-4e31-979a-8eb59a775214', '4efd269c-f755-4f8b-a7ce-b0d10eba19c3') ORDER BY u.user_key;
                user_key               |               user_key                
+--------------------------------------+--------------------------------------+
  5477d5d7-64e3-4e31-979a-8eb59a775214 | 5477d5d7-64e3-4e31-979a-8eb59a775214  
  4efd269c-f755-4f8b-a7ce-b0d10eba19c3 | NULL                                  
(2 rows)
```

The ordering is violated. I have root caused this to the join reader processor. We are doing a left join and the order of the input rows is not being preserved. I added some printfs:

```
input: [{0 [18 78 253 38 156 247 85 79 139 167 206 176 209 14 186 25 195 0 1] <nil>}]
input: [{0 [18 84 119 213 215 100 227 78 49 151 154 142 181 154 119 82 20 0 1] <nil>}]
emitting [{0 [18 84 119 213 215 100 227 78 49 151 154 142 181 154 119 82 20 0 1] <nil>} {0 [18 84 119 213 215 100 227 78 49 151 154 142 181 154 119 82 20 0 1] '5477d5d7-64e3-4e31-979a-8eb59a775214'} {0 [18 27 158 82 52 204 167 78 95 163 51 162 41 168 197 68 203 0 1] <nil>} {0 [18 187 255 246 129 23 163 70 245 189 246 232 116 109 126 39 37 0 1] <nil>} {0 [] <nil>} {0 [] <nil>} {0 [] <nil>} {0 [] <nil>} {0 [] <nil>} {2 [27] false} {0 [] <nil>} {0 [] <nil>} {0 [] <nil>} {0 [] <nil>} {0 [] <nil>} {0 [] <nil>}]
emitting [{0 [18 78 253 38 156 247 85 79 139 167 206 176 209 14 186 25 195 0 1] <nil>} {0 [] NULL} {0 [] NULL} {0 [] NULL} {0 [] NULL} {0 [] NULL} {0 [] NULL} {0 [] NULL} {0 [] NULL} {0 [] NULL} {0 [] NULL} {0 [] NULL} {0 [] NULL} {0 [] NULL} {0 [] NULL} {0 [] NULL}]
```

Notice that the first row is emitted last. The planning side assumes that the ordering of the left input is preserved.

I verified that the queries work with `SET DISTQL = '2.0-off'`.

**Comment by solongordon** [comment]
I'm looking into this. Tighter repro:
```
$ cockroach demo <<EOF
CREATE TABLE t1 (x INT PRIMARY KEY);
CREATE TABLE t2 (x INT, y INT, z INT, PRIMARY KEY (x, y));
INSERT INTO t1 VALUES (1), (2);
INSERT INTO t2 VALUES (2, 0, 0);

SELECT t1.x
FROM t1
  LEFT JOIN t2
  ON t1.x = t2.x
    AND t2.z = 0
WHERE t1.x IN (1, 2)
ORDER BY t1.x;
EOF

  x
+---+
  2
  1
```

**Comment by solongordon** [comment]
The joinreader doesn't even try to preserve the left operand order. (I didn't realize this was a requirement when I wrote the implementation.) It emits matched rows before unmatched rows. I'll put a fix together.

**Comment by RaduBerinde** [comment]
Yeah I don't think it was ever explicitly documented. We should add to the JoinReaderSpec comment (btw and also add a comment for `type` mentioning that only Inner and Left are allowed values).
