### ISSUE TITLE
engine: mvccResolveIntent must create new iterator for unsafeNextKey

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#32142]
MVCCResolveIntent is sometimes called with a time-bounded iterator (from EndTransaction and ResolveIntentRange), with bounds that contain the intent being resolved. However, in some cases the intent resolution process needs to read outside these bounds: 

https://github.com/cockroachdb/cockroach/blob/fb4a974646b8fd440ed60471e70fbfdb79d95a76/pkg/storage/engine/mvcc.go#L2378

This call looks up the next older version behind an intent that is being deleted, so it can be used in stat adjustments. It must use an iterator with no minimum bound, so if the caller passes in a time-bound iterator we must create a new unbounded iterator to use here. 

The main impact of this bug appears to be that "live bytes" metrics may under-count in environments where transaction rollbacks are common. The stats will be corrected by the consistency scanner.

**Comment by petermattis** [comment]
We no longer use time-bound iterators in `EndTransaction` and `ResolveIntentRange`. I don't think there is anything to do here.
