### ISSUE TITLE
Make constants for test timeouts

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#3214]
We have a lot of `SucceedsWithin` and similar calls in our tests which all set their timeouts individually. Many of these are for similar underlying operation so the literal value should be replaced with a constant, e.g. `const replicationTimeout = 3 * time.Second` (see #3213)

**Comment by yaojingguo** [comment]
Happy to take a look.

**Comment by bdarnell** [comment]
Go for it.

**Comment by yaojingguo** [comment]
There are a lot of places with the same timeout values. I have only used a timeout constant if the following criteria are satisfied:

- The timeout values are the same
- The similar operation is performed with `SucceedsWithin`  or `SucceedsWithinDepth` or `IsTrueWithin`
