### ISSUE TITLE
server: stopper.Stop called twice

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#32148]
https://sentry.io/cockroach-labs/cockroachdb/issues/752391374/

stopper.go:179: runtime.plainError: close of closed channel

github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Stop

> stacktrace: {u'frames': [{u'function': u'func1', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/server/admin.go', u'module': u'github.com/cockroachdb/cockroach/pkg/server.(*adminServer).Drain', u'filename': u'github.com/cockroachdb/cockroach/pkg/server/admin.go', u'lineno': 1261, u'in_app': True}, {u'function': u'Stop', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go', u'module': u'github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper)', u'filename': u'github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go', u'lineno': 478, u'in_app': True}, {u'function': u'closechan', u'abs_path': u'/usr/local/go/src/runtime/chan.go', u'module': u'runtime', u'filename': u'runtime/chan.go', u'lineno': 333, u'in_app': False}, {u'function': u'gopanic', u'abs_path': u'/usr/local/go/src/runtime/panic.go', u'module': u'runtime', u'filename': u'runtime/panic.go', u'lineno': 505, u'in_app': False}, {u'function': u'call32', u'abs_path': u'/usr/local/go/src/runtime/asm_amd64.s', u'module': u'runtime', u'filename': u'runtime/asm_amd64.s', u'lineno': 573, u'in_app': False}]}
type: *log.safeError
value: stopper.go:179: runtime.plainError: close of closed channel

**Comment by jordanlewis** [comment]
2.0.6, read of closed channel in `admin.go`.

**Comment by tschottdorf** [comment]
The stopper has no protection against multiple racing calls to `Stop`, yet that's what can happen.

This is in the same code as https://github.com/cockroachdb/cockroach/pull/31692, so I'll fix it there.

**Comment by knz** [comment]
fixed in #37668
