### ISSUE TITLE
Error 'Using skip requires all nodes'  with IMPORT 

### ISSUE THREAD

**Issue by victorggsimida** [cockroachdb/cockroach#32146]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

I use IMPORT to  import mysqldump data 

 IMPORT MYSQLDUMP "http://ip:2015/g18.sql";
pq: Using skip requires all nodes to be upgraded to 2.0-4

**To Reproduce**
 IMPORT MYSQLDUMP "http://ip:2015/g18.sql";

What did you do? Describe in your own words.
 IMPORT MYSQLDUMP "http://ip:2015/g18.sql";

If possible, provide steps to reproduce the behavior:
 IMPORT MYSQLDUMP "http://ip:2015/g18.sql";

1. Set up CockroachDB cluster ...
2. Send SQL ... / CLI command ...
3. Look at UI / log file / client app ...

error

```
pq: Using skip requires all nodes to be upgraded to 2.0-4

```

**Expected behavior**
IMPORT data succeed

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version [e.g. 2.0.x]
 - Server OS: [e.g. Linux/Distrib]
 - Client app [e.g. `cockroach sql`, JDBC, ...]

Build Tag:    v2.1.0
Build Time:   2018/10/30 12:32:34
Distribution: CCL
Platform:     linux amd64 (x86_64-unknown-linux-gnu)
Go Version:   go1.10.3
C Compiler:   gcc 6.3.0
Build SHA-1:  f0dd1dc2d2500155c8b36330ae3d6932c13c1027
Build Type:   release

cockroach sql

**Additional context**
What was the impact?

**Comment by jordanlewis** [comment]
Hi @victorggsimida, is this a cluster that you upgraded over time from 1.1? You'll need to upgrade it by hand to the 2.0 version. https://www.cockroachlabs.com/docs/v2.0/upgrade-cockroach-version.html

**Comment by knz** [comment]
@victorggsimida thank you again for filing the issue. Have you looked at upgrading the cluster version as indicated by Jordan? Did this enable you to move forward?

**Comment by victorggsimida** [comment]
@knz   this my error. because when i use IMPORT, one of my node is down. and it can not confirm the version of the cluster

**Comment by knz** [comment]
Thank you for your reply. Do I understand right that you have been able to upgrade the version since then and you can now run IMPORT successfully?
