### ISSUE TITLE
build: how to create a docker image on armhf

### ISSUE THREAD

**Issue by Serkan-devel** [cockroachdb/cockroach#32147]
**Is your feature request related to a problem? Please describe.**
I'm trying to use cockroachdb within a raspberry pi docker cluster, but I can't an appropriate image or even a dockerfile for this deployment. I've only found instructions to run cockroach [bare metal](https://www.cockroachlabs.com/blog/run-cockroachdb-on-a-raspberry-pi/) and [a wiki entry](https://github.com/cockroachdb/cockroach/wiki/Running%20CockroachDB%20on%20a%20Raspberry%20Pi) which seems to have been deleted.

**Describe the solution you'd like**
Maybe an official docker image for the raspberry pi to deploy. just as the x86-version. The instructions on the official website makes it look like it could work on rpi 2 model b easily (idk).

**Describe alternatives you've considered**
Probably a visible dockerfile where I can change the base image to something which is supported on the pi. There's no dockerfile on [here](https://hub.docker.com/r/cockroachdb/cockroach/)

**Additional context**
I'm trying to run the [minds social network](https://github.com/minds/minds/) locally on a rpi cluster for testing and development purposes. (I also have a fire extinguisher considering their system requirements)

**Comment by medworthy** [comment]
@Serkan-devel,
Remember if you see or smell smoke then run for the nearest exist. Save yourself and think about replacing the hardware later :-P

**Comment by knz** [comment]
@Serkan-devel have you seen the `build/deploy/Dockerfile`? This is the one we use to publish our official docker images. Would that help?

**Comment by Serkan-devel** [comment]
@knz I'd like to run the same image as [this one](https://hub.docker.com/r/cockroachdb/cockroach/) but on a raspberry pi, but the architecture is there different.

The [Dockerfile](https://github.com/cockroachdb/cockroach/blob/master/build/deploy/Dockerfile) there doesn't seem to run cockroach by itself

**Comment by knz** [comment]
@a-robinson is my understanding wrong? I thought the Dockerfile we provided in the location I refernece above is the one used for distributing on docker.io.

**Comment by Serkan-devel** [comment]
but the dockerfile provided, doesn't run cockroach by itself

**Comment by a-robinson** [comment]
What do you mean by "run cockroach by itself"? The Dockerfile linked to by @knz is the one used by https://hub.docker.com/r/cockroachdb/cockroach/.

**Comment by Serkan-devel** [comment]
I tried to build the docker image,but something is missing
<pre>
...
Processing triggers for ca-certificates (20141019+deb8u4) ...
Updating certificates in /etc/ssl/certs... 0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d....done.
 ---> 1d9868442309
Removing intermediate container dce8fe0840d0
Step 3/8 : RUN mkdir -p /cockroach
 ---> Running in 11af450edd17
 ---> b2642cce35c0
Removing intermediate container 11af450edd17
Step 4/8 : COPY cockroach.sh cockroach /cockroach/
lstat cockroach: no such file or directory

</pre>

**Comment by a-robinson** [comment]
Build the Cockroach binary for your desired CPU architecture and then copy it into the `build/deploy` directory before running `docker build`.

**Comment by Serkan-devel** [comment]
>Build the Cockroach binary for your desired CPU architecture
How do I do that?

**Comment by Serkan-devel** [comment]
but I need arm32 on my pi, while it seems to be arm64 which is provided

**Comment by a-robinson** [comment]
Then it seems this may be a deadend. cc @benesch in case arm32 is supported and just not documented, but otherwise this isn't something we're going to be spending time on; you'd have to look into getting such a build working.

**Comment by benesch** [comment]
Ah, sorry @Serkan-devel. We don't currently support 32-bit architectures, nor do we have plans to do so. You can follow #8179 in case we decide to add support in the future, though.

FYI there are 64-bit rPis that can successfully run Cockroach (https://github.com/cockroachdb/cockroach/issues/8179#issuecomment-430322380), though it's certainly not a supported configuration.
