### ISSUE TITLE
sql,ui: add system queries to the statements page

### ISSUE THREAD

**Issue by tim-o** [cockroachdb/cockroach#32153]
**Is your feature request related to a problem? Please describe.**
In [this forum issue](https://forum.cockroachlabs.com/t/unrecoverable-performance-degradation-with-2-1/2121/6?u=tim-o) we ran into a situation where a node became unavailable after spamming the system.public.users table with password queries. The user was able to detect the issue by running `SHOW QUERIES` and noticing that there were tons of long-running queries for passwords. The user asked that we make the same queries available in the statements page, since it's likely to be the first place an administrator would look for a slow query.

**Describe the solution you'd like**
Add system queries to the statements page so there's consistency between the queries in SHOW QUERIES and the UI.

**Comment by knz** [comment]
@tim-o Thanks for this request. I had assumed that we collect stats for every query but actually Andrei changed that back in May (for v2.1).
