### ISSUE TITLE
importccl: OUT OF RANGE error when IMPORT mysqldump data

### ISSUE THREAD

**Issue by victorggsimida** [cockroachdb/cockroach#32150]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**

What did you do? Describe in your own words.
data in mysql

mysql> select * from Account444;
+------------+
| lastipnum  |
+------------+
| 2067439747 |
| 2067439769 |
| 1920058755 |
| 1920058755 |
| 1920058755 |
| 2067447620 |
| 1920058755 |
| 1920058755 |
| 3525343334 |
| 2067439770 |
+------------+
10 rows in set (0.00 sec)

mysql> show create table Account444\G
*************************** 1. row ***************************
       Table: Account444
Create Table: CREATE TABLE `Account444` (
  `lastipnum` int(10) unsigned DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1
1 row in set (0.00 sec)

mysqldump dbname>db.sql

If possible, provide steps to reproduce the behavior:

1. Set up CockroachDB cluster ...
2. Send SQL ... / CLI command ...
3. Look at UI / log file / client app ...
IMPORT the data file

IMPORT 'http://ip:port/db.sql';
 generate insert row: integer out of range for type INTEGER (column "lastipnum")

version：

Build Tag:    v2.1.0
Build Time:   2018/10/30 12:32:34
Distribution: CCL
Platform:     linux amd64 (x86_64-unknown-linux-gnu)
Go Version:   go1.10.3
C Compiler:   gcc 6.3.0
Build SHA-1:  f0dd1dc2d2500155c8b36330ae3d6932c13c1027
Build Type:   release

**Expected behavior**

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version [e.g. 2.0.x]
 - Server OS: [e.g. Linux/Distrib]
 - Client app [e.g. `cockroach sql`, JDBC, ...]

**Additional context**
What was the impact?

**Comment by victorggsimida** [comment]
data below 100000000(10 bit) is ok

but data =999999999(10 bit) is not ok

**Comment by victorggsimida** [comment]
but   insert  directly is ok
select * from one;
        a
+---------------+
      999999999
      999999999
     9999999999
  9999999999999

show create table one;
  table_name |        create_statement
+------------+---------------------------------+
  one        | CREATE TABLE one (
             |     a INT NULL,
             |     FAMILY "primary" (a, rowid)
             | )
(1 row)

**Comment by dt** [comment]
Aha -- when we convert the schema, we go form unsigned to signed, so we actually only accept values up to 2^31 for a when we convert mysql's int4 to our int4. Looks like maybe we should actually go up a size when dropping the unsigned-ness.
