### ISSUE TITLE
storage: add sizes of txn/sequence spans to the MVCC stats

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#3216]

**Comment by petermattis** [comment]
@tschottdorf Anything to be done here for Beta?

**Comment by tschottdorf** [comment]
I hope not, but if testing the GC queue reveals that a lot of old data accumulates, we should be taking action. I talked briefly to @nvanbenschoten about the possibility to explicitly track sequence cache/transaction table size (row count) via `MVCCStats` and it looks like that ought to be possible.
I suggest we move off Beta with the option of revisiting based on the above.

**Comment by tschottdorf** [comment]
The GC queue now emits stats which show these respective sizes, which I think is enough.
