### ISSUE TITLE
sentry: conn_executor.go:670: panic while executing 1 statements: SELECT * FROM ROWS FROM (IF(_ = _, _, _)): caused by <redacted>

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#32162]
https://sentry.io/cockroach-labs/cockroachdb/issues/753895118/

conn_executor.go:670: panic while executing 1 statements: SELECT * FROM ROWS FROM (IF(_ = _, _, _)): caused by <redacted>

github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1

> stacktrace: {u'frames': [{u'function': u'func4', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go', u'lineno': 309, u'in_app': True}, {u'function': u'ServeConn', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*Server)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'lineno': 420, u'in_app': True}, {u'function': u'run', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'lineno': 1200, u'in_app': True}, {u'function': u'execStmt', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'lineno': 95, u'in_app': True}, {u'function': u'execStmtInOpenState', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'lineno': 403, u'in_app': True}, {u'function': u'dispatchToExecutionEngine', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'lineno': 766, u'in_app': True}, {u'function': u'optionallyUseOptimizer', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/planner.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*planner)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/planner.go', u'lineno': 548, u'in_app': True}, {u'function': u'makeOptimizerPlan', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*planner)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/plan.go', u'lineno': 479, u'in_app': True}, {u'function': u'Build', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/builder.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder.(*Builder)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/builder.go', u'lineno': 48, u'in_app': True}, {u'function': u'build', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/builder.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder.(*Builder)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/builder.go', u'lineno': 59, u'in_app': True}, {u'function': u'buildRelational', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational_builder.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder.(*Builder)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational_builder.go', u'lineno': 146, u'in_app': True}, {u'function': u'buildZip', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational_builder.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder.(*Builder)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational_builder.go', u'lineno': 960, u'in_app': True}, {u'function': u'initZipBuild', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational_builder.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder.(*Builder)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational_builder.go', u'lineno': 934, u'in_app': True}, {u'function': u'panicdottypeE', u'abs_path': u'/usr/local/go/src/runtime/iface.go', u'module': u'runtime', u'filename': u'runtime/iface.go', u'lineno': 252, u'in_app': False}, {u'function': u'gopanic', u'abs_path': u'/usr/local/go/src/runtime/panic.go', u'module': u'runtime', u'filename': u'runtime/panic.go', u'lineno': 502, u'in_app': False}, {u'function': u'call32', u'abs_path': u'/usr/local/go/src/runtime/asm_amd64.s', u'module': u'runtime', u'filename': u'runtime/asm_amd64.s', u'lineno': 573, u'in_app': False}, {u'function': u'func1', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'lineno': 418, u'in_app': True}]}
type: *log.safeError
value: conn_executor.go:670: panic while executing 1 statements: SELECT * FROM ROWS FROM (IF(_ = _, _, _)): caused by <redacted>

**Comment by jordanlewis** [comment]
```
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go in func1 at line 418
Called from: runtime/asm_amd64.s in call32
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational_builder.go in initZipBuild at line 934
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational_builder.go in buildZip at line 960
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational_builder.go in buildRelational at line 146
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/builder.go in build at line 59
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/builder.go in Build at line 48
github.com/cockroachdb/cockroach/pkg/sql/plan.go in makeOptimizerPlan at line 479
github.com/cockroachdb/cockroach/pkg/sql/planner.go in optionallyUseOptimizer at line 548
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go in dispatchToExecutionEngine at line 766
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go in execStmtInOpenState at line 403
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go in execStmt at line 95
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go in run at line 1200
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go in ServeConn at line 420

```

Guessing this is @rytaft's domain.
