### ISSUE TITLE
sentry: conn_executor.go:670: panic while executing 1 statements: UPDATE _ SET _ = IFNULL(_ + $1, $1), _ = IFNULL(_ + $2, $2), _ = IF((_ IS _) OR (_ < _), _, _) WHERE (((((_ = $3) AND (_ = $4)) AND (_ = $5)) AND (_ = $6)) AND (_ = $7)) AND (_ = _) LIMIT _ RETURNING *: caused by <redacted>

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#32177]
https://sentry.io/cockroach-labs/cockroachdb/issues/755922465/

conn_executor.go:670: panic while executing 1 statements: UPDATE _ SET _ = IFNULL(_ + $1, $1), _ = IFNULL(_ + $2, $2), _ = IF((_ IS _) OR (_ < _), _, _) WHERE (((((_ = $3) AND (_ = $4)) AND (_ = $5)) AND (_ = $6)) AND (_ = $7)) AND (_ = _) LIMIT _ RETURNING *: caused by <redacted>

github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1

> stacktrace: {u'frames': [{u'function': u'func4', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go', u'lineno': 309, u'in_app': True}, {u'function': u'ServeConn', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*Server)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'lineno': 420, u'in_app': True}, {u'function': u'run', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'lineno': 1200, u'in_app': True}, {u'function': u'execStmt', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'lineno': 95, u'in_app': True}, {u'function': u'execStmtInOpenState', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'lineno': 403, u'in_app': True}, {u'function': u'dispatchToExecutionEngine', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'lineno': 825, u'in_app': True}, {u'function': u'execWithDistSQLEngine', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'lineno': 983, u'in_app': True}, {u'function': u'PlanAndRun', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go', u'lineno': 746, u'in_app': True}, {u'function': u'Run', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go', u'lineno': 253, u'in_app': True}, {u'function': u'StartSync', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go', u'lineno': 602, u'in_app': True}, {u'function': u'Run', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go', u'lineno': 731, u'in_app': True}, {u'function': u'Run', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go', u'lineno': 170, u'in_app': True}, {u'function': u'Next', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go', u'lineno': 205, u'in_app': True}, {u'function': u'Next', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_batch.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*serializeNode)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/plan_batch.go', u'lineno': 123, u'in_app': True}, {u'function': u'BatchedNext', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/update.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*updateNode)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/update.go', u'lineno': 533, u'in_app': True}, {u'function': u'processSourceRow', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/update.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*updateNode)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/update.go', u'lineno': 678, u'in_app': True}, {u'function': u'AddRow', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/row_container.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*RowContainer)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/sqlbase/row_container.go', u'lineno': 280, u'in_app': True}, {u'function': u'gopanic', u'abs_path': u'/usr/local/go/src/runtime/panic.go', u'module': u'runtime', u'filename': u'runtime/panic.go', u'lineno': 502, u'in_app': False}, {u'function': u'call32', u'abs_path': u'/usr/local/go/src/runtime/asm_amd64.s', u'module': u'runtime', u'filename': u'runtime/asm_amd64.s', u'lineno': 573, u'in_app': False}, {u'function': u'func1', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'lineno': 418, u'in_app': True}]}
type: *log.safeError
value: conn_executor.go:670: panic while executing 1 statements: UPDATE _ SET _ = IFNULL(_ + $1, $1), _ = IFNULL(_ + $2, $2), _ = IF((_ IS _) OR (_ < _), _, _) WHERE (((((_ = $3) AND (_ = $4)) AND (_ = $5)) AND (_ = $6)) AND (_ = $7)) AND (_ = _) LIMIT _ RETURNING *: caused by <redacted>

**Comment by vivekmenezes** [comment]
@fastest963 thanks for reporting this problem. @jordanlewis this looks like an issue with RETURNING. @fastest963 are you able to disable RETURNING * and see if this issue is still happening. Thanks!

**Comment by vivekmenezes** [comment]
could be related to https://github.com/cockroachdb/cockroach/issues/29494 which we thought was fixed.

**Comment by fastest963** [comment]
@vivekmenezes Unfortunately, that won't be easy since we require the `RETURNING *` for the application. If it helps, it looks like there were over 300 panics and none of them were caused by the INSERT or SELECT that the application does. Those signatures are:
```
INSERT INTO na_sessions(region, user_id, property_id, organization_id, user_ts_created, ts_created, version) VALUES ($1, $2, ...)
```
and
```
SELECT * FROM na_sessions WHERE ((((region = $1) AND (user_id = $2)) AND (property_id = $3)) AND (organization_id = $4)) AND (expired = _) LIMIT _
```

**Comment by vivekmenezes** [comment]
@fastest963 thanks for sharing your input. That's indicative that the RETURNING is the cause of this. You have 22 columns currently in this schema and you are adding one column making it 23, lining up with the panic report. We will looking into fixing this. Thanks

**Comment by vivekmenezes** [comment]
@knz I suspect https://github.com/cockroachdb/cockroach/pull/31222 broke this. In particular the changes to update.go in 
https://github.com/cockroachdb/cockroach/commit/55706f8e8ff8a0505580447aacf787b8d906ec9f that

**Comment by fastest963** [comment]
@vivekmenezes I don't have the exact queries with values but the best I can do is:

```
UPDATE na_sessions SET pageview_count = $1, pageview_incrementer = $2, ts_created = $3, ts_last_pageview = $4, ts_last_engage = $5, user_flags = $6, session_flags = $7, version = $8 WHERE ((((region = $9) AND (user_id = $10)) AND (property_id = $11)) AND (organization_id = $12)) AND (incrementer = $13) LIMIT 1 RETURNING *
```
```
UPDATE na_sessions SET pageview_count = IFNULL(pageview_count + $1, $1), pageview_incrementer = IFNULL(pageview_incrementer + $2, $2), ts_last_pageview = IF((ts_last_pageview IS _) OR (ts_last_pageview < _), _, ts_last_pageview) WHERE (((((region = $3) AND (user_id = $4)) AND (property_id = $5)) AND (organization_id = $6)) AND (incrementer = $7)) AND (expired = _) LIMIT 1 RETURNING *
```
```
UPDATE na_sessions SET expired = $1, ts_expired = IF((ts_expired = _) OR (ts_expired > _), _, ts_expired) WHERE ((((region = $2) AND (user_id = $3)) AND (property_id = $4)) AND (organization_id = $5)) AND (incrementer = $6) LIMIT 1 RETURNING *
```

Those are some of the updates we do and those all seem to caused the panic at least once.

**Comment by vivekmenezes** [comment]
I'm able to easily reproduce this issue. I'm working on a fix.

**Comment by vivekmenezes** [comment]
@fastest963 I'm pretty confident a workaround to your problem if you need one is to explicitly list all the columns in the returning clause. So instead of using RETURNING * , you can use RETURNING region, user_id, ...

**Comment by fastest963** [comment]
@vivekmenezes thanks for the update and I will responses. I'll modify the application to only request fields it needs for now.

**Comment by knz** [comment]
@jordanlewis can you monitor this until next week when we're back, or perhaps suggest the course of action that will support a combined resolution without revert thanks.

James Hartig <notifications@github.com> schreef op 8 november 2018 08:16:19 GMT-06:00:
>@vivekmenezes thanks for the update and I will responses. I'll modify
>the application to only request fields it needs for now.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/cockroachdb/cockroach/issues/32177#issuecomment-437007829

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
