### ISSUE TITLE
sql: use separate metrics counters for internal queries

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#32187]
the latency stats for internal queries like table lease renewals should not be added to the query stats visible to users. Sometime users are running small workloads and these internal query stats can interfere with a users understanding of their query performance.

**Comment by knz** [comment]
We need to be careful to distinguish here:

- "stats" collected per statement in the stmt stats infrastruture

- "stats" collected via metrics in the timeseries database.

Today they the former are collected with a different application_name, so they can already be filtered out in the "statements" UI page.

However they use the same timeseries metrics counter as regular queries, and so their performance is "merged" with the regular queries, which is the problem you see.

So we should keep the data collection but use different timeseries counters.

This is to be done via new counters in `EngineMetrics`  and conditional choice of metric in `recordStatementSummary` -- both in `pkg/sql/executor_statement_metrics.go`.

**Comment by knz** [comment]
@vivekmenezes I am seeing in the code that Andrei disabled internal queries from the statement statistics, **both the statement stats and the node metrics** back in May 2018. This change made it to v2.1.

Can you confirm your request is limited to 2.0?

If not, can you clarify what led you to this request in v2.1?

I am asking because this change by Andrei is actually conflicting by the request from Tim in #32153. I would like to suggest to restore the accounting for internal queries but instead put them in a separate category (as suggested by my comment above). Let me know if you have any objection.

**Comment by vivekmenezes** [comment]
@knz this was an issue created after a user upgraded to 2.1 and was seeing high p99 latency. Turned out some of the traces for the high latency queries were internal lease release requests. Are these internal queries filtered out from the p99 stats?

**Comment by knz** [comment]
@vivekmenezes if a regular statement issues a lease request "under the hood" it will be included as part of the larger service latency of the regular statement (as expected).

However the lease request "on its own" will not receive a separate stats entry "in addition" to the main/regular statement; collection is disabled for this.

I can also explain using the following table. The vertical dimension is time

| Time | Main statement | Internal query |
|---|---|---|
| 0 | parse: SELECT ... |  |
| 1 | logical planning starts | |
| 2 |        | parse: INSERT INTO leases ...|
| 3 |        | logical planning starts |
| 4 |        | logical planning ends |
| 5 |        | executes |
| 6 |        | query completes |
| 7 | logical planning ends | |
| 8 | executes | |
| 9 | query completes | |

Today, we have a stats entry for the main statement, with latency 9 - 0 = "9".

However, we do not create a separate stats entry for the internal query (with latency 6 - 2 = "4") "in addition" to the main statement, like we did in v2.0.

**Comment by knz** [comment]
This was addressed in #32215.
