### ISSUE TITLE
stability: EBS-backed node wedged

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#32199]
`node-0001` of `big-bison` is completely stuck on disk IO.

![big-bison-iowait](https://user-images.githubusercontent.com/5901480/48280099-9c780d80-e420-11e8-9846-04d69612dd81.png)

From left to right, `node-0000`, `node-0001` and `node-0002`.
The dip in iowait around 8:00 was after killing the node and restarting the instance. Started up again a few hours later.
All aws monitoring shows that we're nowhere near the IOPS limit. All data disks are 50GB `io1` EBS with 2500 IOPS. Current usage is in the single digits.

`node-0001` processes are completely unresponsive as is the disk (eg: even an `ls` will not help).

**Comment by mberhault** [comment]
Performed a second reboot of the instance and the problem hasn't re-occured since. Until reboot, the mounted disk was completely unavailable and any process touching it was wedged.
Everything points to a EBS mount issue, but I've been unable to find such cases online, at least not after the disk was mounted.

I'll leave this open while I keep an eye on the cluster.

**Comment by nvanbenschoten** [comment]
@mberhault are you ok with closing this?

**Comment by mberhault** [comment]
Yes. We have not seen this in a while.
