### ISSUE TITLE
sentry: stopper.go:179: session.go:1345

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#32206]
https://sentry.io/cockroach-labs/cockroachdb/issues/759083813/

stopper.go:179: session.go:1345

github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve.func1

> stacktrace: {u'frames': [{u'function': u'func1', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go', u'module': u'github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith', u'filename': u'github.com/cockroachdb/cockroach/pkg/util/netutil/net.go', u'lineno': 140, u'in_app': True}, {u'function': u'1', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go', u'module': u'github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func9', u'filename': u'github.com/cockroachdb/cockroach/pkg/server/server.go', u'lineno': 750, u'in_app': True}, {u'function': u'ServeConn', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go', u'lineno': 421, u'in_app': True}, {u'function': u'serve', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go', u'lineno': 503, u'in_app': True}, {u'function': u'handleSimpleQuery', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go', u'lineno': 612, u'in_app': True}, {u'function': u'ExecuteStatements', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*Executor)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/executor.go', u'lineno': 642, u'in_app': True}, {u'function': u'execRequest', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*Executor)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/executor.go', u'lineno': 761, u'in_app': True}, {u'function': u'execParsed', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*Executor)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/executor.go', u'lineno': 840, u'in_app': True}, {u'function': u'runWithAutoRetry', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/executor.go', u'lineno': 1023, u'in_app': True}, {u'function': u'runTxnAttempt', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/executor.go', u'lineno': 1200, u'in_app': True}, {u'function': u'execSingleStatement', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*Executor)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/executor.go', u'lineno': 1330, u'in_app': True}, {u'function': u'execStmtInOpenTxn', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*Executor)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/executor.go', u'lineno': 1806, u'in_app': True}, {u'function': u'execStmt', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*Executor)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/executor.go', u'lineno': 2167, u'in_app': True}, {u'function': u'execClassic', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*Executor)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/executor.go', u'lineno': 2020, u'in_app': True}, {u'function': u'forEachRow', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/executor.go', u'lineno': 2036, u'in_app': True}, {u'function': u'Next', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/group.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*groupNode)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/group.go', u'lineno': 356, u'in_app': True}, {u'function': u'Next', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/render.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*renderNode)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/render.go', u'lineno': 113, u'in_app': True}, {u'function': u'renderRow', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/render.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*renderNode)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/render.go', u'lineno': 586, u'in_app': True}, {u'function': u'Eval', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/parser/indexed_vars.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/parser.(*IndexedVar)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/parser/indexed_vars.go', u'lineno': 74, u'in_app': True}, {u'function': u'IndexedVarEval', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/render.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*renderNode)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/render.go', u'lineno': 123, u'in_app': True}, {u'function': u'sigpanic', u'abs_path': u'/usr/local/go/src/runtime/signal_unix.go', u'module': u'runtime', u'filename': u'runtime/signal_unix.go', u'lineno': 290, u'in_app': False}, {u'function': u'panicmem', u'abs_path': u'/usr/local/go/src/runtime/panic.go', u'module': u'runtime', u'filename': u'runtime/panic.go', u'lineno': 63, u'in_app': False}, {u'function': u'gopanic', u'abs_path': u'/usr/local/go/src/runtime/panic.go', u'module': u'runtime', u'filename': u'runtime/panic.go', u'lineno': 489, u'in_app': False}, {u'function': u'call64', u'abs_path': u'/usr/local/go/src/runtime/asm_amd64.s', u'module': u'runtime', u'filename': u'runtime/asm_amd64.s', u'lineno': 515, u'in_app': False}, {u'function': u'maybeRecover', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/session.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*Session)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/session.go', u'lineno': 1360, u'in_app': True}, {u'function': u'gopanic', u'abs_path': u'/usr/local/go/src/runtime/panic.go', u'module': u'runtime', u'filename': u'runtime/panic.go', u'lineno': 489, u'in_app': False}, {u'function': u'call32', u'abs_path': u'/usr/local/go/src/runtime/asm_amd64.s', u'module': u'runtime', u'filename': u'runtime/asm_amd64.s', u'lineno': 514, u'in_app': False}, {u'function': u'func1', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go', u'lineno': 423, u'in_app': True}, {u'function': u'gopanic', u'abs_path': u'/usr/local/go/src/runtime/panic.go', u'module': u'runtime', u'filename': u'runtime/panic.go', u'lineno': 489, u'in_app': False}, {u'function': u'call32', u'abs_path': u'/usr/local/go/src/runtime/asm_amd64.s', u'module': u'runtime', u'filename': u'runtime/asm_amd64.s', u'lineno': 514, u'in_app': False}]}
type: *log.safeError
value: stopper.go:179: session.go:1345

**Comment by jordanlewis** [comment]
v1.1.5.

```
github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go in func1 at line 423
Called from: runtime/asm_amd64.s in call32
github.com/cockroachdb/cockroach/pkg/sql/session.go in maybeRecover at line 1360
Called from: runtime/asm_amd64.s in call64
github.com/cockroachdb/cockroach/pkg/sql/render.go in IndexedVarEval at line 123
github.com/cockroachdb/cockroach/pkg/sql/parser/indexed_vars.go in Eval at line 74
github.com/cockroachdb/cockroach/pkg/sql/render.go in renderRow at line 586
github.com/cockroachdb/cockroach/pkg/sql/render.go in Next at line 113
github.com/cockroachdb/cockroach/pkg/sql/group.go in Next at line 356
github.com/cockroachdb/cockroach/pkg/sql/executor.go in forEachRow at line 2036
github.com/cockroachdb/cockroach/pkg/sql/executor.go in execClassic at line 2020
github.com/cockroachdb/cockroach/pkg/sql/executor.go in execStmt at line 2167
github.com/cockroachdb/cockroach/pkg/sql/executor.go in execStmtInOpenTxn at line 1806
github.com/cockroachdb/cockroach/pkg/sql/executor.go in execSingleStatement at line 1330
github.com/cockroachdb/cockroach/pkg/sql/executor.go in runTxnAttempt at line 1200
github.com/cockroachdb/cockroach/pkg/sql/executor.go in runWithAutoRetry at line 1023
github.com/cockroachdb/cockroach/pkg/sql/executor.go in execParsed at line 840
github.com/cockroachdb/cockroach/pkg/sql/executor.go in execRequest at line 761
github.com/cockroachdb/cockroach/pkg/sql/executor.go in ExecuteStatements at line 642
github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go in handleSimpleQuery at line 612
github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go in serve at line 503
github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go in ServeConn at line 421
```
