### ISSUE TITLE
log: Tests leak gcDaemon goroutines

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#32210]
Commit 968e345bb introduced GC for secondary loggers, and also added them to the leaktest whitelist. The primary logger's gc daemon was on the whitelist because it is a singleton (I think it now may be possible to remove it from the whitelist because it is only started from cli/start.go instead of from something more global where it would affect other tests). Secondary loggers, however, are created once for each server in our test suite, so by the end of a test we have a lot of these goroutines running. We should remove this function from the leaktest whitelist and give it a proper shutdown signal via a stopper or context.

**Comment by knz** [comment]
Fixed in #34826.
