### ISSUE TITLE
sql: ensure Window Functions can spill sorts to disk

### ISSUE THREAD

**Issue by tim-o** [cockroachdb/cockroach#32226]
**Is your feature request related to a problem? Please describe.**
Currently, large sort aggregations cause nodes to OOM. (internal Slack discussion [here](https://cockroachlabs.slack.com/archives/C4UHCCUB0/p1541705929219200). This is blocking a use case for a startup customer, and there is currently no available workaround within CRDB.

**Describe the solution you'd like**
We should support analytics queries, or at least gracefully degrade performance so that the query can eventually complete.

**Describe alternatives you've considered**
N/A - the solution here was suggested by @jordanlewis, though I'm sure we're open to other methods of accomplishing the same goal.

**Comment by jordanlewis** [comment]
I have taken a look at this to refresh my memory. I believe that it should be relatively straightforward to implement this feature.

We'll need to add a new `sortableRowContainer` implementation that optionally stores a row index ordinal along with the rest of the row data. The iterator it returns will be able to access that ordinal along with the row data itself. This will require teaching the container to serialize that ordinal to disk as well, but I don't think it'll be too hard.
