### ISSUE TITLE
storage: avoid batch scan during resume span creation

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#32239]
When an MVCC scan hits a limit, it returns a ["resume span"](https://github.com/cockroachdb/cockroach/blob/a05f15b7223642484ef0364d81ddc462c306e954/pkg/roachpb/api.proto#L91), which acts as a cursor that allows subsequent scans to pick up where the previous partial scan left off. The current approach to computing this resume span is pretty sub-optimal. 

If my reading is correct, we currently pass an extra key back from cgo (`libroach/mvcc.h`) in the response byte buffer. We then iterate through the entire byte buffer in [`buildScanResumeKey`](https://github.com/cockroachdb/cockroach/blob/a05f15b7223642484ef0364d81ddc462c306e954/pkg/storage/engine/mvcc.go#L1842). We do our best to avoid decoding entire kvs, but this is still crazy! We find the offset of the final key and split it off from the rest of the batch represenation and return the final key as the resume span.

We should be able to do something better here. If C++ was made aware of resume keys then we could return them straight from the RocksDB iteration and avoid the entire scan in `buildScanResumeKey`. At a minimum, we should measure the cost of this scan through either a targetted microbenchmark or a SQL-level benchmark that can be modified to conditionally avoid it.

**Comment by nvanbenschoten** [comment]
Sounds like @benesch already has something in the oven.

**Comment by nvanbenschoten** [comment]
@benesch we can close this, right?

**Comment by benesch** [comment]
Indeed. 🎉
