### ISSUE TITLE
ui: How can I tell which user I'm logged in as?

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#32233]
When I'm logged into the admin UI on a cluster that has multiple registered users, I'd like to know which user account I'm logged in as. I may just be missing it, but I can't seem to find anywhere that calls that out.

@piyush-singh

**Comment by piyush-singh** [comment]
Hovering over the logout button should indicate which user you are signed in as. Showing just the first letter of the username is probably not useful/discoverable, and instead we should show the full username. 

<img width="461" alt="screencap" src="https://user-images.githubusercontent.com/21692034/48387055-3f02eb80-e6c2-11e8-8d9b-97c2499d0f0f.png">

**Comment by vilterp** [comment]
Pretty common to show icon + click to see full name and logout link:

![image](https://user-images.githubusercontent.com/7341/48436333-70c09480-e74c-11e8-897e-7b6aaab8323e.png)

![image](https://user-images.githubusercontent.com/7341/48436344-77e7a280-e74c-11e8-8329-d566689e0302.png)

**Comment by a-robinson** [comment]
> Hovering over the logout button should indicate which user you are signed in as. Showing just the first letter of the username is probably not useful/discoverable, and instead we should show the full username.

Well that shows how observant I am. I didn't even notice that the letter changed based on your username since I was so used to seeing a C there on production clusters, and I never would have thought to hover over it.

**Comment by vilterp** [comment]
I think there's a legitimate need for a (small) enhancement here, either a tooltip (instead of a `title` hover), or a clickable dialog like the screenshots above which shows you your username and has a logout link.

**Comment by Annebirzin** [comment]
@piyush-singh attaching designs for the user avatar here: https://zpl.io/aR9n7yN

<img width="414" alt="Screen Shot 2019-11-12 at 10 56 39 AM" src="https://user-images.githubusercontent.com/51920721/68691946-9b515300-0542-11ea-85d3-b675ba25473f.png">

Note: I'm not sure if we'd be able to pull an 'organization' name into the menu. If not we can just go with the user name and 'log out' link.
