### ISSUE TITLE
sql: GRANT admin TO user command hung SQL shell

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#32254]
**Describe the problem**

On a one-node cluster running on master (a05f15b7223642484ef0364d81ddc462c306e954), I added an enterprise license and tried adding my user to the `admin` role. However, when I did so, the command never completed in my SQL shell, it just hung there for minutes on end:

```sql
root@:26257/defaultdb> grant admin to alex;
```

The node's logs were full of the following log spam, where it just kept repeating the same message every couple hundred milliseconds ad infinitum:

```
I181113 09:24:40.895659 483 sql/lease.go:345  [n1,client=[::1]:62257,user=root] publish: descID=23 (role_members) version=2 mtime=2018-11-13 09:24:40.89189 +0000 UTC
I181113 09:24:40.901066 483 sql/lease.go:315  publish (1 leases): desc=[{role_members 23 1}]
I181113 09:24:40.901484 1659 sql/lease.go:876  new lease: 23("role_members") ver=2:1542101372.003237783,0, refcount=0
I181113 09:24:40.927960 483 sql/lease.go:315  publish (1 leases): desc=[{role_members 23 1}]
I181113 09:24:40.976218 483 sql/lease.go:315  publish (1 leases): desc=[{role_members 23 1}]
I181113 09:24:41.062664 483 sql/lease.go:315  publish (1 leases): desc=[{role_members 23 1}]
I181113 09:24:41.254359 483 sql/lease.go:315  publish (1 leases): desc=[{role_members 23 1}]
I181113 09:24:41.472894 483 sql/lease.go:315  publish (1 leases): desc=[{role_members 23 1}]
I181113 09:24:41.696796 483 sql/lease.go:315  publish (1 leases): desc=[{role_members 23 1}]
...
```

The command had successfully taken effect -- the user `alex` was able to do things that required the admin role, but the statement never finished. When I ctrl+C'ed the shell, the log spam stopped with this final message:

```
W181113 09:26:36.644777 483 sql/schema_changer.go:796  [n1,client=[::1]:62257,user=root,scExec] aborted in distSender: context canceled
```

**To Reproduce**

Start a one node cluster at the SHA above. Create a user. Set up an enterprise license. Try to grant the `admin` role to that user.

**Expected behavior**

The command to return.

@mberhault @vivekmenezes

**Comment by vivekmenezes** [comment]
This is a special case of https://github.com/cockroachdb/cockroach/issues/20485 where when the node is killed off while it is gracefully shutting down it leaks a lease. In this case it is leaking a lease to the system.role_member table . The GRANT command is incrementing the version for the table descriptor so it hangs waiting for the unowned lease to expire, and eventually succeeds after 5 minutes (lease expiration timeout).

If you do not shutdown the node and try the command it will not hang.

**Comment by vivekmenezes** [comment]
This is becoming an important issue and I'm prioritizing to fix it before the new schema leasing system is built out.

**Comment by BramGruneir** [comment]
I just hit this too, on master, so it still exists.

The jobs pages shows that it's stuck in "Draining Names".

**Comment by a-robinson** [comment]
I ran into again yesterday when using our tooling for managing managed clusters.

**Comment by vivekmenezes** [comment]
on it :-)

**Comment by bladefist** [comment]
I follow this issue, just to mention, this isn't strictly related to roles.  Granting users access to tables/databases will cause the same issue at times.

**Comment by vivekmenezes** [comment]
Yes, this issue is related to running the following actions:
1. Restarting the cockroach server
2. Running any schema change after that.

It has likely become more pronounced in 2.1 after https://github.com/cockroachdb/cockroach/pull/28725
