### ISSUE TITLE
roachtest: run sqlsmith nightly against cockroachdb 

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#32269]
- setup sqlsmith to run as a nightly test
- This is to be augmented with generating random table descriptors , generate random data ,and then run sqlsmith against this

**Comment by jordanlewis** [comment]
Steps for running sqlsmith:


1. Clone `https://github.com/cockroachdb/sqlsmith/`
2. checkout branch `cockroach`
3. build: `make`
4. start a Cockroach server
5. populate Cockroach server with schemas and data - the more the better
6. run: ./sqlsmith --target="postgres://root@localhost:26257/dbname?sslmode=disable"

7. observe all the panics

**Comment by vivekmenezes** [comment]
https://github.com/cockroachdb/cockroach/pull/32364

**Comment by vivekmenezes** [comment]
@BramGruneir do you want to close this issue?

**Comment by BramGruneir** [comment]
Yep!  Done.  Now if only we could unskip the test.

Once it starts passing, I'd like to add more schemas to it from our workloads.
