### ISSUE TITLE
build: dynamic linking of libtinfo.so.5 breaks on ubuntu 18.04

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#32281]
The latest Linux distributions, like Ubuntu 18.04, are shipping libtinfo.so.6, i.e., a backwards-incompatible ABI change. This is problematic because we currently ship our release binaries that link against libtinfo.so.5. 

I don't see a good way of fixing this besides statically linking libtinfo.

**Comment by petermattis** [comment]
Dynamic libs are the devil spawn.

**Comment by knz** [comment]
We have already replied to folk with similar problems on the latest centos to use the compat package provided with their distro.

This needs to be called out more prominently in docs but it is a durable workaround that can carry us 3-6 months forward.

The solution, which has already been discussed, may not be implemented before 2.3. also, as a major refactor/feature change is not suitable for backports / minor releases anyway.

Also Ben and Piyush need to allocate resources on the cli team to make this happen (together with other cli backlog trimdowns).

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
