### ISSUE TITLE
keys: better PrettyPrint for meta keys

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#3228]
`keys.PrettyPrint` displays meta keys as: `/System/Meta2/"\xff\f\x03\xe8"`. Meta keys are keys about keys. `PrettyPrint` should recursively pretty print the `\xff\f\x03\xe8` suffix of the meta key which is itself a key.

@veteranlu

**Comment by veteranlu** [comment]
@petermattis Do u mean I should pretty print `/System/Meta2/"\xff\f\x03\xe8"` like `/System/Meta2/Table/..`?
What's about `/System/Meta1`, does it should be pretty print recursively?

**Comment by petermattis** [comment]
Yeah, that's what I was imagining. And yes, I think we should do this for all `/System/Meta*` keys.
