### ISSUE TITLE
sql: refactor regexp manipulation using regexp/syntax.Parse and friends

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#3231]
Now that https://github.com/golang/go/issues/12980 is fixed, we should be able to go back and clean this up for Go 1.6.

See discussion in https://github.com/cockroachdb/cockroach/pull/2855#discussion_r42315310.

cc @nvanbenschoten

**Comment by nvanbenschoten** [comment]
Do we want to make this change before Go 1.6 is released? I believe it may break a couple of unit tests until your change is introduced.

**Comment by tamird** [comment]
Right, we won't be able to merge it before the project has been fully ported to 1.6, but it's now possible to write and test this change, so I thought it was time to track it.

Hopefully somebody picks this up, but if not, we'll revisit post-1.6.

**Comment by nvanbenschoten** [comment]
Should we throw a "1.6" label on to this issue (and others that rely on future releases of Go) so it's easier to track?

**Comment by petermattis** [comment]
A `go-1.6` label sounds reasonable.
