### ISSUE TITLE
security: XSRF protection for user-accessible endpoints

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#3232]
Any endpoints that are not read-only and are accessible with a user certificate (e.g. the sql handler used in #3220) need XSRF protection.

**Comment by mberhault** [comment]
I believe this is 1.0, along with all user-related stuff (web authentication, password-based pg authentication, etc...)

**Comment by dianasaur323** [comment]
@mberhault is this still 1.0? Looks like Spencer moved it off 1.0. I moved it to 1.1 for now.

**Comment by bdarnell** [comment]
Closing this because #3220 was closed and we have not yet introduced non-read-only pages to the UI. When we do so, we will of course need to implement XSRF protection, but there's no need to keep this issue open at this point.
