### ISSUE TITLE
get zone config not readable

### ISSUE THREAD

**Issue by YuleiXiao** [cockroachdb/cockroach#3235]
I set zone config like this.
replicas:
    - attrs: []
    - attrs: []
    - attrs: []
    - attrs: []
range_min_bytes: 104857600
range_max_bytes: 671088640

but get zone config become []byte

I1127 14:32:43.937295 45050 context.go:169  running in insecure mode, this is strongly discouraged. See --insecure and --certs.
[]byte{0xa, 0x0, 0xa, 0x0, 0xa, 0x0, 0xa, 0x0, 0x10, 0x80, 0x80, 0x80, 0x32, 0x18, 0x80, 0x80, 0x80, 0xc0, 0x2}

**Comment by mberhault** [comment]
it seems something has changed in the way we retrieve the config. I'll have it fixed soon.

**Comment by mberhault** [comment]
@YuleiXiao: this is fixed, and now has a test to verify the output format.
Please be aware that the `zone set` command has changed. The config is now specified on the command line, not a flag. See the help message for an example.
