### ISSUE TITLE
ui: Awkward text wrapping of "Insecure Mode" icon text in admin UI sidebar

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#32365]
This is a screenshot of the bottom left portion of the admin UI from a roachprod cluster running a recent master, with the page being loaded in Chrome 70.0.3538.77 for Mac on an external monitor:

<img width="82" alt="screen shot 2018-11-14 at 3 34 04 pm" src="https://user-images.githubusercontent.com/7085343/48517320-8a84d900-e82b-11e8-80af-31fa251fde03.png">

**Comment by couchand** [comment]
here's a workaround: use secure mode :trollface:

**Comment by a-robinson** [comment]
😩

**Comment by couchand** [comment]
I believe this has been resolved.
