### ISSUE TITLE
distsql: physical plan diagram should contain TableReader spans

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#32373]
The diagrams (`explain (distsql)...`) contain some info for the TableReaders: the index and table name, the limit, but they don't contain the key span that's being read. It'd be most useful.

**Comment by jordanlewis** [comment]
@georgeutsin I'd like you to take a look at this. The long and short of it is that we have some infrastructure that allows you to view a "Visual plan" that we use all the time, which you can access with `EXPLAIN (DISTSQL) <query>`, and it's missing some useful information. For example:

```[16:53]% ./cockroach demo                                                                                                                                                                                                                                             jordan@Termato:~/repo/src/github.com/cockroachdb/cockroach on sync-pool-batch -> mine/sync-pool-batch
#
# Welcome to the CockroachDB demo database!
#
# You are connected to a temporary, in-memory CockroachDB
# instance. Your changes will not be saved!
#
# Web UI: http://127.0.0.1:62411
#
# Server version: CockroachDB CCL v2.2.0-alpha.20181217-403-g5e14c5e8fd (x86_64-apple-darwin18.2.0, built 2019/01/05 00:19:05, go1.11) (same version as client)
# Cluster ID: aa5252d5-31d1-4cdb-89d9-9badcb4af8e3
#
# Enter \? for a brief introduction.
#
root@127.0.0.1:62410/defaultdb> create table a (a int primary key);
CREATE TABLE

Time: 3.55ms

root@127.0.0.1:62410/defaultdb> explain(distsql) select * from a where a > 5 and a < 10;
  automatic |                                                                                                                                              url
+-----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
    false   | https://cockroachdb.github.io/distsqlplan/decode.html#eJyMjzFLBDEUhHt_xtQBd9tUtteoHHaSIm6GI7CXF97LgnLkv8slhVgIljOTfB_vhiKJz_FKg3_HiuBQVTaaid6r-eCUPuEXh1zq0e51cNhECX9Dy20nPN7ix84zY6I-LnBIbDHvA1s1X6N-PUWE7iBH-6FYixfCr93933SmVSnGX5K_yEsPDkwXzmtMDt34qrINzYwv498oEq3NdZ3hVObUQ3_4DgAA__-AuGSo
(1 row)

Time: 8.317ms

root@127.0.0.1:62410/defaultdb> explain select * from a where a > 5 and a < 10;
  tree |  field   | description
+------+----------+-------------+
  scan |          |
       | table    | a@primary
       | spans    | /6-/9/#
       | parallel |
(4 rows)

Time: 608µs
```

That link takes you to https://cockroachdb.github.io/distsqlplan/decode.html#eJyMjzFLBDEUhHt_xtQBd9tUtteoHHaSIm6GI7CXF97LgnLkv8slhVgIljOTfB_vhiKJz_FKg3_HiuBQVTaaid6r-eCUPuEXh1zq0e51cNhECX9Dy20nPN7ix84zY6I-LnBIbDHvA1s1X6N-PUWE7iBH-6FYixfCr93933SmVSnGX5K_yEsPDkwXzmtMDt34qrINzYwv498oEq3NdZ3hVObUQ3_4DgAA__-AuGSo which is a visual representation of the simple plan created for this query.

The missing piece is shown in the textual `explain` below - the spans of the scan. A span (or keyspan) is a range of keys to select from the underlying kv store. The visual plan is much harder to read without the spans, especially when there is more than one node in the mix. You should add the spans to the visual plan.

The relevant code is in `pkg/sql/distsqlpb/flow_diagram.go`. It should be a relatively simple matter of updating the `summary` method of `TableReaderSpec` to include the spans.
