### ISSUE TITLE
gossip: cluster restarts on AWS flaky

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#3238]
Playing with #3229 and its cousin https://github.com/cockroachdb/cockroach-prod/pull/50, I noticed that `TestGossipRestart` and `TestGossipPeerings` are flaky as hell since Gossip won't reconnect properly. I can usually get it back to working by manually restarting a number of the nodes repeatedly, but haven't noticed a general pattern (it does seem to get better though as I replace the load balancer with an explicit peer list in the `--gossip` flag).

I've also seen these in the process:
```
I1127 17:09:50.815065 2261 gossip/client.go:75  gossip client to ec2-52-91-72-96.compute-1.amazonaws.com:26257: gossip/server.go:80: addr ip-172-31-60-140:26257 could not be converted to net.Addr: lookup ip-172-31-60-140 on 172.31.0.2:53: dial udp 172.31.0.2:53: socket: too many open files
```

`ulimit -a` shows a limit of `1024`, which I imagine ought to be enough for an idle node.

**Comment by tschottdorf** [comment]
This now seems stable, but I'm going to leave this open since I've seen hundreds of goroutines stuck/looping over `.Gossip()` and spamming each other over extended periods of time. This was observed in scenarios in which not all nodes were available.

**Comment by tschottdorf** [comment]
It's still pretty flaky, but now in a different way:

The first node manages to connect to itself but it's unable to open any further outgoing connections:

```
W1222 14:31:06.427008 1519 gossip/gossip.go:674  not connected to gossip; check that gossip flag is s
et appropriately
W1222 14:31:06.541994 1519 rpc/client.go:300  rpc/codec/tls.go:62: unexpected HTTP response: 404 Not
Found
W1222 14:31:07.262652 1519 rpc/client.go:300  rpc/codec/tls.go:62: unexpected HTTP response: 404 Not
Found
I1222 14:31:07.369467 1519 gossip/gossip.go:700  starting client to cockroach-tobias-elb-573673336.us
-east-1.elb.amazonaws.com:26257
I1222 14:31:07.374610 1519 gossip/client.go:77  closing client to cockroach-tobias-elb-573673336.us-e
ast-1.elb.amazonaws.com:26257: gossip/server.go:92: connection already closed; ignoring gossip
W1222 14:31:07.512391 1519 rpc/client.go:300  rpc/codec/tls.go:62: unexpected HTTP response: 404 Not
Found
W1222 14:31:07.837688 1519 rpc/client.go:300  rpc/codec/tls.go:62: unexpected HTTP response: 404 Not
Found
W1222 14:31:08.301017 1519 rpc/client.go:300  rpc/codec/tls.go:62: unexpected HTTP response: 404 Not
Found
I1222 14:31:08.370400 1519 gossip/gossip.go:700  starting client to cockroach-tobias-elb-573673336.us
-east-1.elb.amazonaws.com:26257
W1222 14:31:08.373821 1519 rpc/client.go:300  rpc/codec/tls.go:62: unexpected HTTP response: 404 Not
Found
W1222 14:31:08.675763 1519 rpc/client.go:300  rpc/codec/tls.go:62: unexpected HTTP response: 404 Not
Found
I1222 14:31:08.730795 1519 gossip/client.go:77  closing client to cockroach-tobias-elb-573673336.us-e
ast-1.elb.amazonaws.com:26257: gossip/server.go:92: connection already closed; ignoring gossip
W1222 14:31:08.988642 1519 rpc/client.go:300  rpc/codec/tls.go:62: unexpected HTTP response: 404 Not
Found
I1222 14:31:09.321664 1519 gossip/client.go:77  closing client to cockroach-tobias-elb-573673336.us-e
ast-1.elb.amazonaws.com:26257: gossip/server.go:92: connection already closed; ignoring gossip
W1222 14:31:09.355092 1519 rpc/client.go:300  rpc/codec/tls.go:62: unexpected HTTP response: 404 Not
Found
I1222 14:31:09.371511 1519 gossip/gossip.go:700  starting client to cockroach-tobias-elb-573673336.us
-east-1.elb.amazonaws.com:26257
```

The logs look identical to the other nodes', they don't seem to get a hold of the first one (I've checked and the load balancer shows all of them as active, so they should get there). For kicks I tried to have a node on localhost join the first node, but the same happens:

```
W1222 09:52:45.161282 43481 rpc/client.go:300  rpc/codec/tls.go:62: unexpected HTTP response: 404 Not Found
```

So it seems that the Gossip endpoint actually isn't registered yet. That seems odd because this is in its logs:

```
I1222 14:10:11.038606 1633 server/node.go:248  Started node with [[sdd]=data] engine(s) and attributes []
I1222 14:10:11.038643 1633 multiraft/multiraft.go:998  node 1 campaigning because initial confstate is [1]
I1222 14:10:11.039599 1633 server/server.go:230  starting http server at ip-172-31-61-242:26257
```

**Comment by petermattis** [comment]
@tschottdorf, @spencerkimball Is this flakiness still present? Gossip has had a serious revamp since this was reported.

**Comment by tschottdorf** [comment]
We should put something in the nightlies that tests this against a remote cluster.

`make acceptance TESTS=Gossip TESTFLAGS='-remote -d 5m'`

or some variation thereof. Nothing really tests this on AWS at the moment.

**Comment by spencerkimball** [comment]
@mberhault any idea if this is still an issue?

**Comment by mberhault** [comment]
Hard to tell what this is about exactly, but no, I don't think so. I'll close for now and let @tschottdorf re-open if needed.
