### ISSUE TITLE
TPC-C on AWS has a limit of 98%

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#32386]
When using Master to run TPC-C on AWS, we can't seem to get above 94% efficiency. On GCE we get to ~99% on the warehouses we easily support before falling off. 

warehouses | tpmC | efficiency
-- | -- | --
1000 | 12,138 | 94.38%
1100 | 13,362 | 94.46%
1200 | 14,586 | 94.52%
1300 | 15,764 | 94.29%
1400 | 17,006 | 94.46%
1500 | 18,183 | 94.26%
1600 | 19,443 | 94.49%
1700 | 20,638 | 94.40%
1800 | 21,798 | 94.17%
1900 | 22,943 | 93.90%
2000 | 24,090 | 93.66%
2100 | 25,205 | 93.33%
2200 | 26,079 | 92.18%
2300 | 25,095 | 84.84%

Perhaps there is some sort of throttling? Or an error in our implementation? 

**Reproduction steps**
roachprod create andy-tpcc-16-c -n 4 --clouds=aws  --aws-machine-type-ssd=c5d.4xlarge
roachprod stage andy-tpcc-16:1-3 cockroach
roachprod stage andy-tpcc-16:4 workload
roachprod run andy-tpcc-16:1-3 -- 'sudo umount /mnt/data1; sudo mount -o discard,defaults,nobarrier /dev/nvme1n1 /mnt/data1/; mount | grep /mnt/data1'
roachprod start andy-tpcc-16:1-3
roachprod sql andy-tpcc-16:1
SET CLUSTER SETTING kv.range_merge.queue_enabled = false
roachprod run andy-tpcc-16:1 -- "./cockroach workload fixtures import tpcc --warehouses=2500 --db=tpcc"
roachprod run andy-tpcc-16:4 "./workload run tpcc --ramp=5m --warehouses=2300 --duration=300s --split --scatter {pgurl:1-3}"

**Comment by awoods187** [comment]
With an increase of duration to 15m we can see a new limit of 98%


1100 | 13907.2 | 98.31%
-- | -- | --
1200 | 15171.7 | 98.31%
1300 | 16437.1 | 98.32%
1400 | 17684.7 | 98.23%
1500 | 18958.3 | 98.28%

**Comment by awoods187** [comment]
FYI still seeing a cap around 98% efficiency

**Comment by nvanbenschoten** [comment]
We don't expect to ever hit 100%. Doing so would indicate that transactions take 0s, which is not possible. We've made a few changes to workload over the past year to make the reporting more accurate and to avoid miscounting efficiency, which might explain why we remember being able to hit 100% (and even > 100%) in the past.
