### ISSUE TITLE
teamcity: bad reporting of failed tests

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#32399]
I see two TC runs for which it claims (in the UI) that two tests failed each time, but in reality, looking at the logs, it seems that only a single one did.
I have to admit that, after trying to parse the logs to provide more info, I have failed.
@tbg Peter claims that perhaps you mucked with some script involved in informing TC of the failed tests? Are you a good victim for this?
cc @jordanlewis @benesch 

https://teamcity.cockroachdb.com/viewLog.html?buildId=1014728&buildTypeId=Cockroach_UnitTests
TestLogGC - legit race
TestTxnAutoRetriesDisabledAfterResultsHaveBeenSentToClient/no_client_make - innocent victim?

https://teamcity.cockroachdb.com/viewLog.html?buildId=1013042&buildTypeId=Cockroach_UnitTests
TestStoreRangeMergeAbandonedFollowersAutomaticallyGarbageCollected - legit failure
TestParse/ParseModeYMD/990108/23:59:59.999999/ParseTime - innocent victim?

**Comment by benesch** [comment]
One thing that would be helpful is downloading the raw test.log/testrace.log files before TC GCs them. That should make for an easy reproduction. I'd do it myself but I need to head out shortly.

**Comment by andreimatei** [comment]
Done.
[TestStore:TestParse.log](https://github.com/cockroachdb/cockroach/files/2587294/TestStore.TestParse.log)
[TestLogGC:TestTxnAuto.log](https://github.com/cockroachdb/cockroach/files/2587295/TestLogGC.TestTxnAuto.log)

**Comment by tbg** [comment]
See https://github.com/cockroachdb/cockroach/issues/32025. This is harder to see here because we don't have the original test runner output in the artifacts (why not? The script should put them to artifacts/test.log).

**Comment by tbg** [comment]
Maybe the failing "assert workspace clean" thing nukes the artifacts by "accident"?

**Comment by tbg** [comment]
Here's what it actually looks like (taken from #32434).

<img width="972" alt="image" src="https://user-images.githubusercontent.com/5076964/48700435-4c513600-ebec-11e8-93c3-b6775d4dcb62.png">

I assume `make` prints the error to stderr, but it gets lumped in with the test output.

**Comment by tbg** [comment]
Well, this would explain why:

<img width="481" alt="image" src="https://user-images.githubusercontent.com/5076964/48700669-d8fbf400-ebec-11e8-9c40-87c51c709a41.png">

**Comment by knz** [comment]
To fix the `tee` behavior we can use `| stdbuf -oL tee ...`

**Comment by knz** [comment]
will send patch

**Comment by knz** [comment]
The PR I made was not sufficient to fix this.

**Comment by knz** [comment]
@tbg @andreimatei I would suggest that:

1) we stop using `tee` and `2>&1` to redirect stdout/stderr to an artifact log file (also see point 3 below)

2) we use `go-test-teamcity` only on the stdout stream, as your favorite Deity intended, ie the commands would become `make ... | go-test-teamcity`  (I am assuming that test results go to stderr? If not we can make this happen via a redirect inside the Makefile, instead of redirecting the entire `make` output)

3) use the `script` command to record all the I/O to a file for the artifacts. This will capture everything in a good order for human analysis.

WDYT?

**Comment by knz** [comment]
Yes I was observing the same.

Additionally I also want to be able to study the interleaving of errors on stderr and stdout, so that I can get some idea of the global sequence of events. The capture by `script` will achieve that.

**Comment by knz** [comment]
We have addressed this using the new json support in go test
