### ISSUE TITLE
Documentation Improvement.

### ISSUE THREAD

**Issue by slateraus** [cockroachdb/cockroach#32398]
https://www.cockroachlabs.com/docs/stable/configure-replication-zones.html

You set the num_replicas  = 4 I assume it should be 5 looking at the example commands.

ALTER TABLE t CONFIGURE ZONE USING range_min_bytes = 0, range_max_bytes = 90000, gc.ttlseconds = 89999, num_replicas = 5, constraints = '[-region=west]';

then the doc shows the command show all zone configurations:

zone_config_test.t | ALTER TABLE zone_config_test.public.t CONFIGURE ZONE USING
                     |     range_min_bytes = 0,
                     |     range_max_bytes = 90000,
                     |     gc.ttlseconds = 89999,
                     |     num_replicas = 4, <- should be 5
                     |     constraints = '[-region=west]'

Sorry for being picky :-)

**Comment by knz** [comment]
Thank you for your suggestion!

**Comment by jseldess** [comment]
Thanks for reporting this, @slateraus. That particular example was extraneous and will be removed in https://github.com/cockroachdb/docs/pull/4087.
