### ISSUE TITLE
kv/storage: create new CountKeys request type, powered by MVCCStats

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#32403]
`MVCCStats` acts as a denormalized view of the keys in a range. It aggregates information about the the number of keys, the size of the keys, the size of the values, the number of intents, etc. There are some interesting ways that we could use this information to speed up SQL queries. For instance, we can use it to dramatically speed up `COUNT(*)` queries. We should introduce a new `CountKeys` request type that transactionally reads the number of keys in a span at a given timestamp. A prototype of this change can be found [on this branch](https://github.com/nvanbenschoten/cockroach/commits/nvanbenschoten/countKeys).

The overview of the change is:
1. we introduce a new field to the `MVCCStats` called `MaxWriteTimestamp`. This is updated whenever a Range performs a transactional write (non-transactional write or commits an intent).
2. we introduce a new `CountKeys` request that scans a span and returns the number of keys in the span. This request is transactional, so like `Scan` it will bump the timestamp cache.
3. we introduce a fast-path for `CountKeys` that returns the `MVCCStats.LiveCount` instead of scanning the Range iff: the `CountKeys` request spans the entire range, the stats don't contain estimates, the stats indicate that the Range has no intents, and the stats have a `MaxWriteTimestamp` equal to or below the request's timestamp.

There are a few open questions with this approach. The first is how we want to expose it in SQL. One option would be to use it for all `COUNT(*)` statements. Another would be to make it a separate experimental builtin function until we gain confidence that the result is always correct. A middle-ground would be to run a `CountKeys` request alongside an `Scan` request when computing `COUNT(*)` statements and assert that they agree. After running in this mode for some time, we can switch over to only using the `CountKeys` request. In the interim period, we could stick the only-`CountKeys` strategy behind a cluster setting.

Another complication is making this the cluster upgrade work correctly. Of course, we'll need to gate usage of the `CountKeys` request behind a cluster version that indicates that all other nodes can handle it. The more interesting upgrade complication is that MVCCStats are persisted, so no version of Cockroach can be sure that their `MVCCStats` are able to power a CountKeys request. We could version the `MVCCStats` object that we write to disk, but we can probably use the `MaxWriteTimestamp` as this upgrade marker as well. If it's set, we know we can use it... **but** this means that to set the `MaxWriteTimestamp` we need one of two conditions to hold:
1. it must not be set and the Range's leaseholder that is setting it must observe that the cluster has a version that indicates that all nodes can correctly handle it. When originally setting the field on a non-empty Range, it should be set to `hlc.Now()` by the leaseholder.
2. it must already be set, which indicates that a previous leaseholder proved that it was safe to set

Another thing to note is that we'll need to determine how this interacts with `RecomputeStats` requests. It might work correctly without any changes, but we may need to consistently load the `MVCCStats` from the RocksDB batch instead of using the in-memory version.

cc. @ridwanmsharif @jordanlewis 

Jira issue: CRDB-4749

**Comment by danhhz** [comment]
Hey @nvanbenschoten is there an issue for the larger work of making this work with COUNT(*) or is this it?

I realized after the demo of that branch that we need to be careful here about interleaved tables and column families. Clearly we have to disable this optimization if the table is interleaved or if it has more than one column family (we write them lazily so you can't just divide # keys by # families). Less clearly, we should consider if there's ever a situation where we have interleaved keys in there but no descriptor for them (table has been dropped or something). Ditto for if the table had two column families and recently went down to one.

**Comment by nvanbenschoten** [comment]
> Hey @nvanbenschoten is there an issue for the larger work of making this work with COUNT(*) or is this it?

I was planning on this being focused on the KV part of this change because that's the area that @ridwanmsharif may pick up. I opened https://github.com/cockroachdb/cockroach/issues/32406 to track this.
