### ISSUE TITLE
ui: add node localities to Node List

### ISSUE THREAD

**Issue by slateraus** [cockroachdb/cockroach#32400]
It would be sweet if you included the node "--locality=" in the Cluster Overview Node List like you do on the Node Map.

**Comment by couchand** [comment]
Hi @slateraus, thanks for the suggestion.  Making it easier to get that information is definitely already on our radar.  Our general idea is to enable a grouping by locality in that node list, somewhat like the Localities debug page (`/#/reports/localities`).  I was surprised to see that we didn't already have an issue filed for that enhancement, so thanks for filing this!
