### ISSUE TITLE
sql: commitPrepStmtNamespace is allocation heavy and almost never needed

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#32427]
<img width="1185" alt="screen shot 2018-11-16 at 3 42 42 pm" src="https://user-images.githubusercontent.com/5438456/48646245-4a9e2d00-e9b6-11e8-9435-4d9fc4e35dce.png">

Above is a screenshot of a CPU profile from a `kv95` run on a single-node `m5d.12xlarge` cluster. We can see that `commitPrepStmtNamespace` is responsible for **2.48%** of CPU utilization. This is pretty insane considering there's nothing in the prepared stmt namespace that needs rolling back.

We should page this `prepStmtNamespace` stuff back in (including its interaction with the pgwire protocol) and then audit all uses of it. We should then make it cheaper to use, introduce fast-paths that avoid touching it at all when not necessary, or do some combination of both.

cc. @knz @andreimatei 

Jira issue: CRDB-4747

Epic CRDB-42584

**Comment by knz** [comment]
@jordanlewis @petermattis which team / project is this landing in?

**Comment by petermattis** [comment]
That code is in no-man's land. I think the SQL execution team might have more bandwidth for this, though. @jordanlewis feel free to push back if you disagree.

**Comment by jordanlewis** [comment]
We can take this on eventually, though it doesn't seem particularly high priority, and I wouldn't make a claim about having any extra bandwidth.

**Comment by nvanbenschoten** [comment]
There's a **6.4%** speedup sitting here for sysbench's `oltp_point_select` workload (and presumably `kv100`). I'll see if I can knock this out later this week.

**Comment by nvanbenschoten** [comment]
I took a shot at this in this branch: [`nvanbenschoten/prepStmtPerf`](https://github.com/cockroachdb/cockroach/compare/master...nvanbenschoten:nvanbenschoten/prepStmtPerf). The approach was to only copy these `prepStmtNamespaces` when they were actually changed. What I didn't take into consideration is that their portals are almost always mutated because clients repeatedly bind with prepared statements, so the change didn't have the desired effect.

@andreimatei this got me thinking about whether we have the wrong structure here. We need to be able to roll back prepared statements during a txn retry, but do we need to be able to roll back portals? Will clients ever rely on the result of a previously prepared statement binding instead of just rebinding every time they want to use a prepared statement? If not then we could constrain the namespace checkpointing to just prepared statements and fix this easily. If we do need to be able to roll back portals then we'll need to rework the `connExecutor`'s interaction with the `prepStmtNamespaces` checkpointing. We'll need to push down information about when it's ok to modify the checkpoint directly (e.g. when we're running an implicit txn and can't possibly roll it back).

**Comment by andreimatei** [comment]
> We need to be able to roll back prepared statements during a txn retry, but do we need to be able to roll back portals?

I don't know; I don't know what the lifetimes of both portals or prepared statements is, and the docs unfortunately are not very clear.

**Comment by knz** [comment]
This is still relevant it seems.

**Comment by rafiss** [comment]
Closing since this is an old issue, and it seems that https://github.com/cockroachdb/cockroach/pull/134183 addressed the current known improvement. Since performance optimization is an active area of effort, this will resurface through future testing if needed.
