### ISSUE TITLE
kv: DistSender async throttling can lead to deadlock

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#32453]
`DistSender.sendPartialBatchAsync` may fail if the concurrency limit is reached, and returns a boolean to indicate whether or not this has occurred. This method promises to write to `responseCh` if and only if it returns true, but the (only) call site in `divideAndSendBatchToRanges` does not check this return value. This results in a deadlock when it tries to read from the response channel which no one will write to.

Either `sendPartialBatchAsync` should return an error instead of a bool so that callers will be required to handle the error or it should return nothing and guarantee that it will write exactly one value to `responseCh` no matter what.

**Comment by nvanbenschoten** [comment]
Is it possible that you missed the line-wrap in the `if` statement that calls `DistSender.sendPartialBatchAsync`?

https://github.com/cockroachdb/cockroach/blob/5377795af4f3064fe7059ffb016463e989be3e58/pkg/kv/dist_sender.go#L920-L921

**Comment by bdarnell** [comment]
Yes, I did.
