### ISSUE TITLE
Quotas per user

### ISSUE THREAD

**Issue by benoit-ponsero** [cockroachdb/cockroach#32450]
Hello,

Do you have any plan to implement some quota per sql user ?  
(req/sec, number of tables, size of data) 

which would allow to isolate user load in a cluster. 

Thanks

**Comment by knz** [comment]
There is no immediate plan to implement resource isolation in CockroachDB. Even if plans were made now, the work required is sufficiently large that you wouldn't see much of it before 2-3 years down the line.

**Comment by benoit-ponsero** [comment]
Whoo thanks for your fast answer ! 

So, i think the best way to isolate a user should be creating a "subcluster" with his data.

Is it possible to join a cluster with only a specific database to replicate and not all ?

**Comment by knz** [comment]
The best way to isolate users is to run multiple CockroachDB clusters side by side and use OS facilities to restrict the `cockroach` processes.

**Comment by knz** [comment]
Note that we are now proposing a "Managed CockroachDB service" which will help achieve this.

**Comment by benoit-ponsero** [comment]
Yes
Managed CockroachDB is interesting but i didn't found any pricing plans. 
I know it's currently in Beta, but it's difficult to plan about without prices.

I love cockroach, and i would use it in my future next company, so i'm exploring all cases :)

**Comment by knz** [comment]
Fair enough. I'll ensure someone reaches out to you to discuss prices too, so you have a fuller picture.

**Comment by knz** [comment]
We have implemented this in multi-tenant CockroachDB.
