### ISSUE TITLE
roachprod: cluster didn't timeout

### ISSUE THREAD

**Issue by m-schneider** [cockroachdb/cockroach#32466]
While trying to test geo-distributed TPCC, I spun up a cluster on AWS with ```roachprod create masha-test --clouds=aws --geo``` and left it running. Several days later I tried to spin up another masha-test and discovered that the old one was still running. Output from roachprod list is 
```
masha-test:                         [aws]  1   (-76h43m19s)
```
with details it's:

```
masha-test: [aws] expired 76h44m26s ago
  masha-test-0004       ip-172-31-5-138.eu-west-2.compute.internal      172.31.5.138    35.178.251.98
```

**Comment by petermattis** [comment]
The shared host was out of disk space which was preventing `roachprod gc` from syncing the hosts.
