### ISSUE TITLE
IMPORT failing to create inverted indexes 

### ISSUE THREAD

**Issue by tim-o** [cockroachdb/cockroach#32468]
**Describe the problem**

Running 2.1.0, bulk CSV import fails to create an inverted index for [this payload (CockroachLabs only)](https://drive.google.com/open?id=16zmZHbWOpVpn0ZERMxlweetP5qLTaUS6).

The index can be created successfully on the same table as long as its done after the import.

**To Reproduce**

1) Attempt to import and create an index, get a SST creation error:
```
root@:26257/defaultdb> IMPORT TABLE defaultdb.public.skusv2_30 (id UUID PRIMARY KEY, skujson JSONB, masterskuid UUID, createdby UUID, createddate string, lastsavedby UUID, lastsaveddate string, isdeleted BOOL, availabilityjson JSONB, quantityjson JSONB, INVERTED INDEX quantityjson_idx (quantityjson)) CSV DATA ('nodelocal:///SkusV2_full_export30.csv.gz') WITH decompress = 'gzip', "nullif" = '', skip = '1';
pq: SST creation error at /Table/85/2/"quantities"/Arr/"quantity"/0/"\x00\xc5\xf1\x1d\xf8bMۭ\x9f\x95\xe5\x84\xf6\xf7\xb6"/0; this can happen when a primary or unique index has duplicate keys: Invalid argument: Keys must be added in order
```
2) Remove the inverted index, complete import:
```
root@:26257/defaultdb> IMPORT TABLE defaultdb.public.skusv2_30 (id UUID PRIMARY KEY, skujson JSONB, masterskuid UUID, createdby UUID, createddate string, lastsavedby UUID, lastsaveddate string, isdeleted BOOL, availabilityjson JSONB, quantityjson JSONB) CSV DATA ('nodelocal:///SkusV2_full_export30.csv.gz') WITH decompress = 'gzip', "nullif" = '', skip = '1';
        job_id       |  status   | fraction_completed |  rows  | index_entries | system_records |   bytes
+--------------------+-----------+--------------------+--------+---------------+----------------+------------+
  401644233494659073 | succeeded |                  1 | 166493 |             0 |              0 | 6303594991
(1 row)
```
3) Create the index without an issue:
```
root@:26257/defaultdb> create inverted index on skusv2_30 (quantityjson);
CREATE INDEX

Time: 17.085579657s
```

**Comment by mjibson** [comment]
Looks like we never tested inverted indexes. We should probably fix this and backport to 2.1.

**Comment by tim-o** [comment]
@mjibson who should we assign?

**Comment by mjibson** [comment]
I think the bulkio team is in charge of triaging these.

**Comment by tim-o** [comment]
Assigning @dt for triage.

**Comment by lucy-zhang** [comment]
This happens because it's possible to generate identical inverted index keys for different JSON tree nodes, and we reject SST k/v batches with duplicate keys. There's a flag in the BulkAdder that's flipped for the index backfiller to ignore duplicates, which we can turn on for IMPORT with `experimental_direct_ingestion` as well. It's probably not worth fixing for the current IMPORT implementation.

**Comment by jordanlewis** [comment]
I'm going to close this for 20.1, since #45564 will cause inverted indexes to stop producing duplicate keys.
