### ISSUE TITLE
changefeedccl: support decimal columns in avro changefeeds

### ISSUE THREAD

**Issue by rolandcrosby** [cockroachdb/cockroach#32471]
When attempting to create a changefeed on the `entry` table of the `ledger` workload, I get the following error in the jobs table:

job_id|job_type|description|user_name|status|running_status|created|started|finished|modified|fraction_completed|error|coordinator_id
-|-|-|-|-|-|-|-|-|-|-|-|-
401656549032820737|CHANGEFEED|"CREATE CHANGEFEED FOR TABLE entry INTO 'kafka://10.142.0.8:9092' WITH confluent_schema_registry = 'http://10.142.0.8:8081', format = 'experimental_avro'"|root|failed|NULL|2018-11-19 16:50:51.14528+00:00|2018-11-19 16:50:51.165853+00:00|2018-11-19 16:50:52.212268+00:00|2018-11-19 16:50:52.212269+00:00|0|-76.760 will not roundtrip at scale 1|1

It looks like we may be picking an inappropriate Avro representation of one of the DECIMAL columns in the table:

<details><summary>CREATE TABLE statement</summary>

table_name|create_statement
-|-
entry|CREATE TABLE entry (<br>	id INT NOT NULL DEFAULT unique_rowid(),<br>	amount DECIMAL(20,3) NULL,<br>	customer_id INT NULL,<br>	transaction_id STRING(255) NOT NULL,<br>	system_amount DECIMAL(24,7) NULL,<br>	created_ts TIMESTAMP NOT NULL,<br>	money_type STRING(1) NOT NULL,<br>	CONSTRAINT "primary" PRIMARY KEY (id ASC),<br>	CONSTRAINT fk_customer_id_ref_customer FOREIGN KEY (customer_id) REFERENCES customer (id),<br>	INDEX entry_auto_index_fk_customer (customer_id ASC),<br>	CONSTRAINT fk_transaction_id_ref_transaction FOREIGN KEY (transaction_id) REFERENCES transaction (external_id),<br>	INDEX entry_auto_index_fk_transaction (transaction_id ASC),<br>	FAMILY "primary" (id, amount, customer_id, transaction_id, system_amount, created_ts, money_type)<br>)

</details>

<details><summary>Avro schema</summary>

```
{
  "type": "record",
  "name": "entry",
  "fields": [
    {
      "name": "id",
      "type": "long"
    },
    {
      "name": "amount",
      "type": [
        "null",
        {
          "type": "bytes",
          "logicalType": "decimal",
          "precision": 20,
          "scale": 3
        }
      ]
    },
    {
      "name": "customer_id",
      "type": [
        "null",
        "long"
      ]
    },
    {
      "name": "transaction_id",
      "type": "string"
    },
    {
      "name": "system_amount",
      "type": [
        "null",
        {
          "type": "bytes",
          "logicalType": "decimal",
          "precision": 24,
          "scale": 7
        }
      ]
    },
    {
      "name": "created_ts",
      "type": {
        "type": "long",
        "logicalType": "timestamp-micros"
      }
    },
    {
      "name": "money_type",
      "type": "string"
    }
  ]
}
```

</details>

**Comment by danhhz** [comment]
Heh, the bug is even simpler than that. Fixed by the following diff, but needs a test
```diff
diff --git a/pkg/ccl/changefeedccl/avro.go b/pkg/ccl/changefeedccl/avro.go
index 52f4f051fe..7b3049c994 100644
--- a/pkg/ccl/changefeedccl/avro.go
+++ b/pkg/ccl/changefeedccl/avro.go
@@ -252,6 +252,7 @@ func tableToAvroSchema(tableDesc *sqlbase.TableDescriptor) (*avroSchemaRecord, e
                colIdxByFieldIdx: make(map[int]int),
        }
        for colIdx, col := range tableDesc.Columns {
+               col := col
                field, err := columnDescToAvroSchema(&col)
                if err != nil {
                        return nil, err
```
