### ISSUE TITLE
sql: invalid aggregation in UPDATE causes server crash

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#32477]
Repro:

```sql
CREATE TABLE t(x INT);
INSERT INTO t VALUES (1);
UPDATE t SET x = count(x) WHERE TRUE;
```

Expected behavior: "planning error - aggregation not allowed in this context"

Actual behavior: server panic

Course of action: prevent aggregations (and probably other special functions) in UPDATE SET expression analysis.

Also reported as:

https://sentry.io/cockroach-labs/cockroachdb/issues/769213141/

conn_executor.go:521: panic while executing 1 statements: UPDATE _ SET _ = _ || count(_)::STRING WHERE _ = _: caused by <redacted>

github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func2

> stacktrace: {u'frames': [{u'function': u'func3', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go', u'lineno': 260, u'in_app': True}, {u'function': u'ServeConn', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*Server)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'lineno': 491, u'in_app': True}, {u'function': u'run', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'lineno': 911, u'in_app': True}, {u'function': u'execStmt', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'lineno': 87, u'in_app': True}, {u'function': u'execStmtInOpenState', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'lineno': 349, u'in_app': True}, {u'function': u'dispatchToExecutionEngine', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'lineno': 582, u'in_app': True}, {u'function': u'execWithLocalEngine', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'lineno': 625, u'in_app': True}, {u'function': u'countRowsAffected', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/executor.go', u'lineno': 2054, u'in_app': True}, {u'function': u'forEachRow', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/executor.go', u'lineno': 2030, u'in_app': True}, {u'function': u'Next', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/update.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*updateNode)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/update.go', u'lineno': 305, u'in_app': True}, {u'function': u'Next', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/render.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*renderNode)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/render.go', u'lineno': 344, u'in_app': True}, {u'function': u'renderRow', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/render.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*renderNode)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/render.go', u'lineno': 697, u'in_app': True}, {u'function': u'Eval', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*BinaryExpr)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go', u'lineno': 2560, u'in_app': True}, {u'function': u'Eval', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*CastExpr)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go', u'lineno': 2701, u'in_app': True}, {u'function': u'Eval', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FuncExpr)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go', u'lineno': 3312, u'in_app': True}, {u'function': u'sigpanic', u'abs_path': u'/usr/local/go/src/runtime/signal_unix.go', u'module': u'runtime', u'filename': u'runtime/signal_unix.go', u'lineno': 388, u'in_app': False}, {u'function': u'panicmem', u'abs_path': u'/usr/local/go/src/runtime/panic.go', u'module': u'runtime', u'filename': u'runtime/panic.go', u'lineno': 63, u'in_app': False}, {u'function': u'gopanic', u'abs_path': u'/usr/local/go/src/runtime/panic.go', u'module': u'runtime', u'filename': u'runtime/panic.go', u'lineno': 505, u'in_app': False}, {u'function': u'call32', u'abs_path': u'/usr/local/go/src/runtime/asm_amd64.s', u'module': u'runtime', u'filename': u'runtime/asm_amd64.s', u'lineno': 573, u'in_app': False}, {u'function': u'func2', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'lineno': 489, u'in_app': True}]}
type: *log.safeError
value: conn_executor.go:521: panic while executing 1 statements: UPDATE _ SET _ = _ || count(_)::STRING WHERE _ = _: caused by <redacted>

**Comment by rytaft** [comment]
cc @knz this seems like it might be in your territory...
