### ISSUE TITLE
sentry: stopper.go:175: runtime.errorString: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#32478]
https://sentry.io/cockroach-labs/cockroachdb/issues/769221943/

stopper.go:175: runtime.errorString: runtime error: invalid memory address or nil pointer dereference

github.com/cockroachdb/cockroach/pkg/storage.(*Replica).withRaftGroupLocked

> stacktrace: {u'frames': [{u'function': u'func1', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go', u'module': u'github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask', u'filename': u'github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go', u'lineno': 263, u'in_app': True}, {u'function': u'func2', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_range_lease.go', u'pre_context': [u'\t\t\t\t\t\tlog.Error(ctx, err)', u'\t\t\t\t\t}', u'\t\t\t\t}'], u'module': u'github.com/cockroachdb/cockroach/pkg/storage.(*pendingLeaseRequest).requestLeaseAsync', u'in_app': True, u'post_context': [u'\t\t\t\tif err != nil {', u'\t\t\t\t\tpErr = roachpb.NewError(newNotLeaseHolderError(&status.Lease, p.repl.store.StoreID(), p.repl.Desc()))', u'\t\t\t\t}'], u'filename': u'github.com/cockroachdb/cockroach/pkg/storage/replica_range_lease.go', u'context_line': u'\t\t\t\t// Set error for propagation to all waiters below.', u'lineno': 310}, {u'function': u'Send', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go', u'pre_context': [u'// GetLastRequestTime returns the most recent time in nanos', u'// when the last rate was recorded.', u'// NOTE: This should only be used for load based splitting, only'], u'module': u'github.com/cockroachdb/cockroach/pkg/storage.(*Replica)', u'in_app': True, u'post_context': [u'func (r *Replica) GetLastRequestTime() time.Time {', u'\tr.splitMu.Lock()', u'\tdefer r.splitMu.Unlock()'], u'filename': u'github.com/cockroachdb/cockroach/pkg/storage/replica.go', u'context_line': u'// works when the load based splitting cluster setting is enabled.', u'lineno': 1867}, {u'function': u'maybeInitializeRaftGroup', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go', u'pre_context': [u'}', u'', u'// GetMVCCStats returns a copy of the MVCC stats object for this range.'], u'module': u'github.com/cockroachdb/cockroach/pkg/storage.(*Replica)', u'in_app': True, u'post_context': [u'// synchronization with any concurrent writes.', u'func (r *Replica) GetMVCCStats() enginepb.MVCCStats {', u'\tr.mu.RLock()'], u'filename': u'github.com/cockroachdb/cockroach/pkg/storage/replica.go', u'context_line': u'// This accessor is thread-safe, but provides no guarantees about its', u'lineno': 1843}, {u'function': u'withRaftGroupLocked', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go', u'pre_context': [u'// withRaftGroup calls the supplied function with the (lazily initialized)', u'// Raft group. It acquires and releases the Replica lock, so r.mu must not be', u'// held (or acquired by the supplied function).'], u'module': u'github.com/cockroachdb/cockroach/pkg/storage.(*Replica)', u'in_app': True, u'post_context': [u'// If mayCampaignOnWake is true, the replica may initiate a raft', u'// election if it was previously in a dormant state. Most callers', u'// should set this to true, because the prevote feature minimizes the'], u'filename': u'github.com/cockroachdb/cockroach/pkg/storage/replica.go', u'context_line': u'//', u'lineno': 598}, {u'function': u'Campaign', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/rawnode.go', u'module': u'github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.(*RawNode)', u'filename': u'github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/rawnode.go', u'lineno': 140, u'in_app': False}, {u'function': u'Step', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/raft.go', u'module': u'github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.(*raft)', u'filename': u'github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/raft.go', u'lineno': 851, u'in_app': False}, {u'function': u'campaign', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/raft.go', u'module': u'github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.(*raft)', u'filename': u'github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/raft.go', u'lineno': 731, u'in_app': False}, {u'function': u'campaign', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/raft.go', u'module': u'github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.(*raft)', u'filename': u'github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/raft.go', u'lineno': 733, u'in_app': False}, {u'function': u'becomeLeader', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/raft.go', u'module': u'github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.(*raft)', u'filename': u'github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/raft.go', u'lineno': 710, u'in_app': False}, {u'function': u'becomeLeader', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/raft.go', u'module': u'github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.(*raft)', u'filename': u'github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/raft.go', u'lineno': 710, u'in_app': False}, {u'function': u'appendEntry', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/progress.go', u'module': u'github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft.(*raft)', u'filename': u'github.com/cockroachdb/cockroach/vendor/github.com/coreos/etcd/raft/progress.go', u'lineno': 120, u'in_app': False}, {u'function': u'sigpanic', u'abs_path': u'/usr/local/go/src/runtime/signal_unix.go', u'pre_context': [u'\t\tthrow("fault")', u'\tcase _SIGSEGV:', u'\t\tif (g.sigcode0 == 0 || g.sigcode0 == _SEGV_MAPERR || g.sigcode0 == _SEGV_ACCERR) && g.sigcode1 < 0x1000 {'], u'module': u'runtime', u'in_app': False, u'post_context': [u'\t\t}', u'\t\t// Support runtime/debug.SetPanicOnFault.', u'\t\tif g.paniconfault {'], u'filename': u'runtime/signal_unix.go', u'context_line': u'\t\t\tpanicmem()', u'lineno': 388}, {u'function': u'panicmem', u'abs_path': u'/usr/local/go/src/runtime/panic.go', u'pre_context': [u'', u'func panicmem() {', u'\tpanicCheckMalloc(memoryError)'], u'module': u'runtime', u'in_app': False, u'post_context': [u'}', u'', u'func throwinit() {'], u'filename': u'runtime/panic.go', u'context_line': u'\tpanic(memoryError)', u'lineno': 63}, {u'function': u'gopanic', u'abs_path': u'/usr/local/go/src/runtime/panic.go', u'pre_context': [u'\t\treflectcall(nil, unsafe.Pointer(d.fn), deferArgs(d), uint32(d.siz), uint32(d.siz))', u'\t\tp.argp = nil', u''], u'module': u'runtime', u'in_app': False, u'post_context': [u'\t\tif gp._defer != d {', u'\t\t\tthrow("bad defer entry in panic")', u'\t\t}'], u'filename': u'runtime/panic.go', u'context_line': u'\t\t// reflectcall did not panic. Remove d.', u'lineno': 505}, {u'function': u'call32', u'abs_path': u'/usr/local/go/src/runtime/asm_amd64.s', u'pre_context': [u'\tCALL\truntime\xb7reflectcallmove(SB)', u'\tRET', u''], u'module': u'runtime', u'in_app': False, u'post_context': [u'CALLFN(\xb7call64, 64)', u'CALLFN(\xb7call128, 128)', u'CALLFN(\xb7call256, 256)'], u'filename': u'runtime/asm_amd64.s', u'context_line': u'CALLFN(\xb7call32, 32)', u'lineno': 573}]}
type: *log.safeError
value: stopper.go:175: runtime.errorString: runtime error: invalid memory address or nil pointer dereference

**Comment by jordanlewis** [comment]
```
github.com/cockroachdb/cockroach/pkg/storage/replica.go in withRaftGroupLocked at line 598
github.com/cockroachdb/cockroach/pkg/storage/replica.go in maybeInitializeRaftGroup at line 1843
github.com/cockroachdb/cockroach/pkg/storage/replica.go in Send at line 1867
github.com/cockroachdb/cockroach/pkg/storage/replica_range_lease.go in func2 at line 310
github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go in func1 at line 263
```
