### ISSUE TITLE
sql: rollback of dropped unique index can block future schema changes

### ISSUE THREAD

**Issue by eriktrinh** [cockroachdb/cockroach#32486]
A rolled back set of mutations containing a drop unique index can error again if the uniqueness constraint has been violated. Currently the error is ignored, leaving the mutations at the head of the mutations list to be tried again by a future schema changer. It will block future changes from advancing through the schema changer until the uniqueness constraint can be validated.

The failed rollback trying to create the index again should be removed along with the orphaned data.

**Comment by lucy-zhang** [comment]
I'd opened #47712 before seeing this, but I'm closing this in favor of the other issue since it has a little more detail and is updated as of 20.1.
