### ISSUE TITLE
backupccl: compress files before uploading

### ISSUE THREAD

**Issue by bladefist** [cockroachdb/cockroach#32498]
Backups simply upload the underlying data to the destination as many files.  As databases grow, the size of the database backups mean more time spent uploading/downloading, as well as cloud storage and bandwidth costs.

I've seen with other databases backup compression can take a 500gb database down to 70gb, every database is different obviously based on how they store their data.  

I'd like to see compression as an option, that at the least would zip before upload, and even better, employ some compression strategy that makes sense for the specific way cockroach/rocksdb stores data

**Comment by rytaft** [comment]
@bladefist thanks submitting this request.

@rolandcrosby do you know if compression of backup files is on the roadmap?

**Comment by rolandcrosby** [comment]
Note that the data in the SST files written and read by `backup`/`restore` are already compressed using Snappy, so it's dubious whether any additional compression would be an improvement.

**Comment by bladefist** [comment]
I did some basic testing, a 10.5GB  database (from CRDB Backup):

z7:  8.6GB
zip: 9.6GB

**Comment by dt** [comment]
So I don't _think_ we do a compaction on restart, but eve if we did, I'd be surprised if you saw that change BACKUP: we do a logical read for BACKUP at a specific timestamp, so RocksDB compactions shouldn't factor into what we backup at all.

Restarting a node _does_ wipe its temp cache which is mostly used for distributed SQL Execution and for IMPORT, but that shouldn't affect backup sizes.

So, if you're observing a big difference backing up the same table(s) before and after a restart, something else might be going on... does this reproduce?

**Comment by bladefist** [comment]
@dt I think i stated it wrong, I believe it's the temp data.  Restarting must clear that, and that data is being included in the backup.  

We can reproduce, yes.  The temp data will grow until the node is restarted, if the node has been stable for a while, we get large temp data, and thus, large backups.   

We can verify this next week, I have a channel in slack if you want to work through it w/ me. The nodes were restarted yesterday so there isn't much temp data growth yet.

**Comment by rolandcrosby** [comment]
Not planning to invest in this at the moment, since SSTs are already made of compressed blocks.
