### ISSUE TITLE
sentry: server.go:219: clock_offset.go:226

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#32514]
https://sentry.io/cockroach-labs/cockroachdb/issues/770765445/?referrer=webhooks_plugin

server.go:219: clock_offset.go:226

github.com/cockroachdb/cockroach/pkg/rpc.(*Context).runHeartbeat

> stacktrace: {u'frames': [{u'function': u'func1', u'abs_path': u'/Users/laibaohua/code/cockroach-v2.0.4/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go', u'pre_context': [u'\t\tctx = opentracing.ContextWithSpan(ctx, nil)', u'\t\tdefer s.Recover(ctx)', u'\t\tdefer s.stop.Done()'], u'module': u'github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker', u'in_app': False, u'post_context': [u'\t}()', u'}', u''], u'filename': u'github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go', u'context_line': u'\t\tf(ctx)', u'lineno': 192}, {u'function': u'1', u'abs_path': u'/Users/laibaohua/code/cockroach-v2.0.4/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go', u'pre_context': [u'\t\t\tif err := ctx.Stopper.RunTask(', u'\t\t\t\tctx.masterCtx, "rpc.Context: grpc heartbeat", func(masterCtx context.Context) {', u'\t\t\t\t\tctx.Stopper.RunWorker(masterCtx, func(masterCtx context.Context) {'], u'module': u'github.com/cockroachdb/cockroach/pkg/rpc.(*Context).GRPCDial.func1.1', u'in_app': False, u'post_context': [u'\t\t\t\t\t\tif err != nil && !grpcutil.IsClosedConnection(err) {', u'\t\t\t\t\t\t\tlog.Errorf(masterCtx, "removing connection to %s due to error: %s", target, err)', u'\t\t\t\t\t\t}'], u'filename': u'github.com/cockroachdb/cockroach/pkg/rpc/context.go', u'context_line': u'\t\t\t\t\t\terr := ctx.runHeartbeat(conn, target, redialChan)', u'lineno': 508}, {u'function': u'runHeartbeat', u'abs_path': u'/Users/laibaohua/code/cockroach-v2.0.4/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go', u'pre_context': [u'\t\t\tctx.RemoteClocks.UpdateOffset(ctx.masterCtx, target, request.Offset, pingDuration)', u'', u'\t\t\tif cb := ctx.HeartbeatCB; cb != nil {'], u'module': u'github.com/cockroachdb/cockroach/pkg/rpc.(*Context)', u'in_app': False, u'post_context': [u'\t\t\t}', u'\t\t}', u'\t\tconn.heartbeatResult.Store(heartbeatResult{'], u'filename': u'github.com/cockroachdb/cockroach/pkg/rpc/context.go', u'context_line': u'\t\t\t\tcb()', u'lineno': 642}]}
type: *log.safeError
value: server.go:219: clock_offset.go:226

**Comment by rytaft** [comment]
cc @petermattis, I think you were working on clock offset issues

**Comment by tbg** [comment]
Nothing to do here, this is an intentional crash due to clock offsets.
