### ISSUE TITLE
sql: very spammy "bytes usage increases to X"

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#32510]
on master, seen in the logs for `import/tpch/nodes=4`. https://github.com/cockroachdb/cockroach/issues/16409 fixed something in this area but that was long ago.

This rotates anything interesting away quickly, so it's somewhat high priority.

```
I181120 12:54:29.296591 28440 util/mon/bytes_usage.go:608  internal-planner: bytes usage increases to 260 KiB (+10240)
I181120 12:54:29.362271 28440 util/mon/bytes_usage.go:608  internal-planner: bytes usage increases to 260 KiB (+10240)
I181120 12:54:29.462242 28440 util/mon/bytes_usage.go:608  internal-planner: bytes usage increases to 130 KiB (+10240)
I181120 12:54:29.464263 28440 util/mon/bytes_usage.go:608  internal-planner: bytes usage increases to 260 KiB (+10240)
I181120 12:54:29.519923 28440 util/mon/bytes_usage.go:608  internal-planner: bytes usage increases to 260 KiB (+10240)
I181120 12:54:29.581209 28440 util/mon/bytes_usage.go:608  internal-planner: bytes usage increases to 130 KiB (+10240)
I181120 12:54:29.700530 28440 util/mon/bytes_usage.go:608  internal-planner: bytes usage increases to 130 KiB (+10240)
I181120 12:54:29.769978 28440 util/mon/bytes_usage.go:608  internal-planner: bytes usage increases to 130 KiB (+10240)
I181120 12:54:29.855860 28440 util/mon/bytes_usage.go:608  internal-planner: bytes usage increases to 130 KiB (+10240)
I181120 12:54:30.008223 28440 util/mon/bytes_usage.go:608  internal-planner: bytes usage increases to 260 KiB (+10240)
I181120 12:54:30.083590 28440 util/mon/bytes_usage.go:608  internal-planner: bytes usage increases to 130 KiB (+10240)
I181120 12:54:30.105202 28440 util/mon/bytes_usage.go:608  internal-planner: bytes usage increases to 260 KiB (+10240)
I181120 12:54:30.149030 28440 util/mon/bytes_usage.go:608  internal-planner: bytes usage increases to 130 KiB (+10240)
I181120 12:54:30.387567 28440 util/mon/bytes_usage.go:608  internal-planner: bytes usage increases to 130 KiB (+10240)
I181120 12:54:30.451131 28440 util/mon/bytes_usage.go:608  internal-planner: bytes usage increases to 130 KiB (+10240)
I181120 12:54:30.565372 28440 util/mon/bytes_usage.go:608  internal-planner: bytes usage increases to 260 KiB (+10240)
I181120 12:54:30.591294 28440 util/mon/bytes_usage.go:608  internal-planner: bytes usage increases to 260 KiB (+10240)
I181120 12:54:30.659587 28440 util/mon/bytes_usage.go:608  internal-planner: bytes usage increases to 130 KiB (+10240)
```

**Comment by tbg** [comment]
cc @knz in case this is a one-liner I can throw in somewhere.

**Comment by jordanlewis** [comment]
There's a few env variables that control stuff like this.

COCKROACH_NOTEWORTHY_INTERNAL_MEMORY_USAGE is default 100kb, and leads to this spam. You can increase it on the command line. We should probably just tune it upward.

**Comment by tbg** [comment]
What do you think I should increase the default to? 10MB? Note that this is during IMPORT so if this captures the SST allocations no default will really cover it (in our testing and in users' production). Also, we should be wary about anything that logs at that high a frequency. Can this conveniently be rate limited (i.e. is there some root object in scope that can hold a `log.EveryN`)?

**Comment by jordanlewis** [comment]
This doesn't capture the SST allocations. I'm not exactly sure which queries are getting run through the internal planner, but it seems like logging this information is completely pointless. I think 10MB would be sufficiently unusual that it would warrant further investigation. 100kb seems like not a big deal.

**Comment by knz** [comment]
Both your proposals have merit. I think 10MB is too high a global limit. For everything SQL, an alloc north of 1MB should be cause for concern. 

We can either do a "backoff" solution like suggested by @tbg 

or we can make the "noteworthy" thing configurable by monitor. and inherited for sub-monitors.

Then the import thing would set its noteworthy limit to much higher while everything else uses the default.

**Comment by tbg** [comment]
Verified that the last run of import/tpch/nodes=4 doesn't have these messages.
