### ISSUE TITLE
dump creates invalid syntax for set null

### ISSUE THREAD

**Issue by brucemcpherson** [cockroachdb/cockroach#32529]
**Describe the problem**
Dumping the schema from a v2.1.0 database generates invalid syntax for ALTER statements which include SET NULL
Please describe the issue you observed, and any steps we can take to reproduce it:
Dump a table with on delete set null in the defintion
**To Reproduce**
```
kubectl exec -i cockroachdb-client-secure -- ./cockroach dump fid "smsStatistic" --dump-mode=schema --certs-dir=/cockroach-certs --host=cockroachdb
-public > x.sql
```
What did you do? Describe in your own words.
The result included these two lines
```
ALTER TABLE "smsStatistic" ADD CONSTRAINT "smsStatistic_ibfk_1" FOREIGN KEY ("senderID") REFERENCES users (id) ON DELETE SET_NULL ON UPDATE CASCADE;
ALTER TABLE "smsStatistic" ADD CONSTRAINT "smsStatistic_ibfk_2" FOREIGN KEY ("receiverID") REFERENCES users (id) ON DELETE SET_NULL ON UPDATE CASCADE;
```

If possible, provide steps to reproduce the behavior:

1. Set up CockroachDB cluster ...
2. Send SQL ... / CLI command ...
3. Look at UI / log file / client app ...

**Expected behavior**
Should have exported SET NULL rather than SET_NULL
When you try to apply this, SET_NULL is reported as an error

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version [e.g. 2.0.x]
 - Server OS: [e.g. Linux/Distrib]
 - Client app [e.g. `cockroach sql`, JDBC, ...]
kubernetes, cockroach sql v2.1.1 client and server

**Additional context**
What was the impact?
Need to edit sql dump files before they are are usable

**Comment by mjibson** [comment]
Thanks. I'll take a look at some point.

**Comment by knz** [comment]
Note: I think the same problem would occur with SET DEFAULT.
