### ISSUE TITLE
v2.1.1,ERR: split failed while applying backpressure: could not find valid split key

### ISSUE THREAD

**Issue by derkan** [cockroachdb/cockroach#32524]
**Describe the problem**

After upgrading 2.1.1, table updates failed on our system with error:

```
InternalError: (psycopg2.InternalError) split failed while applying backpressure: could not find valid split key
 [SQL: 'UPDATE requests SET q_checked_on=%(q_checked_on)s WHERE requests.id = %(id_1)s'] [parameters: {'q_checked_on': datetime.datetime(2018, 11, 21, 0, 50, 6, 316859), 'id_1': UUID('323ea26d-8105-45ac-9984-7ec8ecd8900e')}]
```
Target is not a cluster, standalone local CRDB database(with --insecure).

This is log from db:
```
W181121 07:52:54.991908 535049 storage/replica_backpressure.go:135  [n1,s1,r191/1:/Table/77/1/"2{>\xa2â<80>¦-pgA\xâ<80>¦}] applying backpressure to limit range growth on batch [txn: 5260ab3a], BeginTransaction [/Table/77/1/"2>\xa2m\x81\x05E\xac\x99\x84~\xc8\xecØ<90>\x0e"/0,/Min), Put [/Table/77/1/"2>\xa2m\x81\x05E\xac\x99\x84~\xc8\xecØ<90>\x0e"/0,/Min)
W181121 07:52:54.992258 535049 internal/client/txn.go:532  [n1,client=127.0.0.1:32300,user=xxxx] failure aborting transaction: split failed while applying backpressure: could not find valid split key; abort caused by: split failed while applying backpressure: could not find valid split key
```

**To Reproduce**

```sql
CREATE TABLE requests (
	id UUID NOT NULL,
        q_checked_on TIMESTAMP NULL,
        content BYTES NULL,
        CONSTRAINT requests_pkey PRIMARY KEY (id ASC));
UPDATE requests SET q_checked_on=%(q_checked_on)s WHERE requests.id = %(id_1)s
```
**Environment:**
CockroachDB CCL v2.1.1 (x86_64-unknown-linux-gnu, built 2018/11/19 18:24:21, go1.10.3)
CentOS 7.5.1804

**Additional context**

After setting 

```sql
SET CLUSTER SETTING kv.range.backpressure_range_size_multiplier=0;
```
clients started to work normally.

**Comment by derkan** [comment]
@nvanbenschoten thanks for answer. I think size of `content` column causes this error as you mentioned. Not shown in DDL I've send before, but there are `status` and ` updated_on` columns which are updated frequently until job is completed. So should I make a different column family for `status,updated_on` or for `content`?

**Comment by nvanbenschoten** [comment]
>  So should I make a different column family for status,updated_on or for content?

Let's do it for `content`. Your schema will look something like:
```
CREATE TABLE requests (
	id UUID NOT NULL PRIMARY KEY,
        q_checked_on TIMESTAMP NULL,
        ... <all other columns> ...,
        content BYTES NULL,
        FAMILY (id, q_checked_on, status, updated_on, ... <all other columns>),
        FAMILY (content));
```

You can even specify it like 
```
CREATE TABLE requests (
	id UUID NOT NULL PRIMARY KEY,
        q_checked_on TIMESTAMP NULL,
        ... <all other columns> ...,
        content BYTES NULL,
        FAMILY (id),
        FAMILY (content));
```

because all unspecified columns will be added to the first column family.

**Comment by derkan** [comment]
Hi,
Not to face this `split failed while applying backpressure` in other CRDB cluster in v2.1.0, I tried to move columns to another column family, but cluster is now not stable.(#32880) `select id from requests limit 1` works, but `select count(*) from requests` waits forever.
This is PROD db, and after 14 hours db is still not stable with errors:

`snapshot failed: aborting snapshot because raft log is too large` 
```
E181206 09:52:07.425384 283779 storage/queue.go:793  [n4,timeSeriesMaintenance,s4,r2900/4:/System/tsd/cr.node.sql.mem.c…] context deadline exceeded

W181206 09:52:09.751892 472 server/node.go:886  [n4,summaries] health alerts detected: {Alerts:[{StoreID:4 Category:METRICS Description:queue.tsmaintenance.process.failure Value:1}]}

E181206 09:52:41.800703 285852 storage/queue.go:793  [n4,replicate,s4,r639/4:/System/tsd/cr.node.sql.mem.c…] 1 matching stores are currently throttled
```

**Comment by nvanbenschoten** [comment]
@derkan is `SET CLUSTER SETTING kv.range.backpressure_range_size_multiplier=0;` still set? How long did you run with that value set before attempting this schema change?

Could you provide a [`debug zip`](https://www.cockroachlabs.com/docs/v2.1/debug-zip.html#synopsis) from your cluster?

**Comment by derkan** [comment]
Hi Nathan,
I am not sure about time but it may be a week. Today I set its value back to 2.
I've send logs to your e-mail.
Thank you.

**Comment by nvanbenschoten** [comment]
@derkan thanks for the email. I received it and am taking a look.

I see plenty of logs like: 
```
I181206 09:22:04.349628 487128 storage/replicate_queue.go:260  [n3,replicate,s3,r1554/2:/Table/428/1/"\{t\xaa…-vZ\xb…}] snapshot failed: aborting snapshot because raft log is too large (25483921 bytes after processing 7 of 15269 entries)
```

7 Raft entries taking up more than 25MB is surprising. That's more than 3MB per entry. Do you have an estimate for how large these `content` columns are?

**Comment by nvanbenschoten** [comment]
We also see nodes hitting the following condition and shutting themselves down:
https://github.com/cockroachdb/cockroach/blob/11405f234963fa7822aab97dbe19612853facb26/pkg/cli/start.go#L863-L864

**Comment by nvanbenschoten** [comment]
Got it, has anything changed in your cluster since last week? Is it still in the same state? Either way, an updated version of the `debug zip` output would be helpful so we can observe the progress the cluster is making while recovering.

What we see from the logs is that node 2 ran into an issue somewhere and was told to rebalance all of its Ranges to the other three nodes. The nodes are working through the rebalance but they're having trouble with these very large Ranges and their snapshots are timing out. One thing we could try is to run the following statements:
```
SET CLUSTER SETTING kv.snapshot_rebalance.max_rate='32MiB'
SET CLUSTER SETTING kv.snapshot_recovery.max_rate='32MiB'
```

This should help the rebalance process.

Is there still load on the cluster? If so, how much?

**Comment by derkan** [comment]
uptime command outputs:
Node1: load average: 3.26, 3.30, 3.40
Node2: load average: 3.06, 3.11, 3.09 (crdb is shutdown now)
Node3: load average: 0.26, 0.72, 0.62
Node4: load average: 1.86, 1.86, 1.40

**Comment by tbg** [comment]
@nvanbenschoten note that this is the same cluster as https://github.com/cockroachdb/cockroach/issues/32896, which had disk issues on n2. I also saw RocksDB deadlocked on n1, though apparently the storage worked (I'm going to look at a new debug zip later today).

**Comment by nvanbenschoten** [comment]
Closed with https://github.com/cockroachdb/cockroach/issues/32896.
