### ISSUE TITLE
cli/start: certificate error if no IP in cert (--listen translates hostname to addr and addr not in cert)

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#32539]
From @SpeedyCoder on https://github.com/cockroachdb/cockroach/issues/32501#issuecomment-440706118

> Do you guys have any idea why we are seeing the warning about the listen address not being in the node certificate? We are running the container with the following command

```
command:
- "/bin/bash"
- "-ecx"
- "exec /cockroach/cockroach start --logtostderr=WARNING --certs-dir /cockroach/cockroach-certs --advertise-addr $(hostname -f) --http-addr 0.0.0.0 --join cockroachdb-0.cockroachdb,cockroachdb-1.cockroachdb,cockroachdb-2.cockroachdb --cache 25% --max-sql-memory 25%"
```

> so the `--advertise-addr` is set. I've tried setting the `--listen-addr` to `0.0.0.0`, but that didn't have any effect. Setting it to `$(hostname -f)` resolved to an IP address and complained again. The cluster seems to be working fine otherwise, it's just not very comforting seeing that message and I don't really have any idea how to get rid of it... 😅

**Comment by SpeedyCoder** [comment]
The message I'm seeing on all nodes is 
```
+ exec /cockroach/cockroach start --logtostderr=WARNING --certs-dir /cockroach/cockroach-certs --advertise-addr cockroachdb-2.cockroachdb.partner.svc.cluster.local --http-addr 0.0.0.0 --join cockroachdb-0.cockroachdb,cockroachdb-1.cockroachdb,cockroachdb-2.cockroachdb --cache 25% --max-sql-memory 25%
W181121 15:50:18.829078 66 base/addr_validation.go:293  [n?] listen address "::" not in node certificate (IP=127.0.0.1; DNS=localhost,cockroachdb-2.cockroachdb.partner.svc.cluster.local,cockroachdb-2.cockroachdb,cockroachdb-proxy,cockroachdb-proxy.partner.svc.cluster.local; CN=node)
Secure node-node and SQL connections are likely to fail.
Consider extending the node certificate or tweak --listen-addr/--advertise-addr.
*
* WARNING: [n?] listen address "::" not in node certificate (IP=127.0.0.1; DNS=localhost,cockroachdb-2.cockroachdb.partner.svc.cluster.local,cockroachdb-2.cockroachdb,cockroachdb-proxy,cockroachdb-proxy.partner.svc.cluster.local; CN=node)
* Secure node-node and SQL connections are likely to fail.
* Consider extending the node certificate or tweak --listen-addr/--advertise-addr.
*
```
Running a 3 node cluster in secure mode with version `v2.1.1`.

**Comment by knz** [comment]
@roncrdb @tim-o please qualify further -- either we need a doc update or the issue description should highlight the desired behavior.

**Comment by knz** [comment]
I have looked at this closer today. The cause of the problem is simple but the solution escapes me. I would welcome input from @mberhault or @bdarnell as to how to proceed further.

What happens is as follows.
1. suppose the user starts with `--listen-addr=localhost:26257`. We'll use this example because it is simple to understand but there is no loss in generality; the rest of the problem is identical regardless of the combination of flags used.
2. the string `localhost:26257` gets populated into `cfg.Addr` by flag parsing.
3. then in `ValidateAddrs()`, `cfg.Addr` gets copied into `cfg.AdvertiseAddr`.
4. then we call `net.Listen()`, followed by
5. `UpdateAddrs()` which extracts the address computed by `net.Listen()` and stores it back in `cfg.Addr`, in this example setting it to `127.0.0.1:26257`. this picks up the address after DNS resolution but also normalization if the user had used `--listen-addr=0.0.0.0` or similar
6. then we see the call to `CheckCertificateAddrs`, which in turns
7. asserts that both:
   a. `cfg.Addr` is present in the certificate
   b. `cfg.AdvertiseAddr` is present in the certificate

So if the user had created the certificate with just the CN `localhost`, the check 7.a is going to fail (but 7.b succeed). If they create it with just the IP address `127.0.0.1`, check 7.a  would succeed (but 7.b would fail).

I have tried to twist this in several ways:

A. call `CheckCertificateAddrs()` before `net.Listen`. This is bad because if the cert contains an IP address for the host and the user starts with `--listen-addr=:26257` (no host, implies 0.0.0.0), cert check will fail. The cert check should really happen after `net.Listen` has computed an address.

B. keep a copy of the configured value for `--listen-addr` (`OrigRequestedAddr` or something) and use that in `CheckCertificateAddrs` as follows: *"if the cert check fails with the `cfg.Addr` post-listen, then try checking the one pre-listen, and if that's OK then let's consider the cert to be validated".* However I feel this logic is insecure: this does not protect against DNS hijacks.

What should we do? 

- We could perhaps "take a stance" and simply document + recommend users to populate certs with the "final" listen address, not the one they use as input in the flag. I.e. promote IP addresses more strongly. But that may be inconvenient with deployments with variable IP addresses (eg cloud). 

- Or maybe we could reverse-lookup the post-listen IP addr into a hostname, and if the IP address is not in the cert, check that the reverse hostname is, and if that is OK consider the cert validation OK too?

**Comment by knz** [comment]
Discussed this offline with @mberhault. 
Marc explained/reminded me that `CheckCertificateAddrs()` is advisory and meant to help the user configure the security. There is no requirement to cover all the edge cases in there because the main security checks are performed separately (in the go std lib).

We have found how to proceed:

1. the main problem observed here is that we are checking that the listen address is in the cert. This check is superfluous. The address that matters for cert validation is the advertise address. I will proceed to remove the check on the listen address.`

2. the check on the advertise address is what matters. However, the advertise address does not get resolved/changed by net.Listen. This means that during `CheckCertificateAddrs` if we don't find the advertise addr in the cert, we should also name-resolve the advertise addr and consider the check satisifed if the resolved addr is in the cert.
