### ISSUE TITLE
sql: release-2.3: follow up on changing INT size (#26925)

### ISSUE THREAD

**Issue by bobvawter** [cockroachdb/cockroach#32534]
Placeholder issue for tracking the cleanups identified in https://github.com/cockroachdb/cockroach/issues/26925#issuecomment-437154424.

Jira issue: CRDB-4738

**Comment by jordanlewis** [comment]
@bobvawter is it time to do this part now?

**Comment by jordanlewis** [comment]
@bobvawter I could use your help on re-identifying what you meant by this issue. I find the linked issue very hard to follow.
