### ISSUE TITLE
roachtest: getDiskUsageBytes can get confused

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#32545]
While running `restore2TB/nodes=10` I periodically see: `diskusage: 21:55:25 restore.go:197: node #3: strconv.Atoi: parsing "du: cannot access '/mnt/data1/cockroach/001133.sst': No such file or directory\n18085084": invalid syntax`

I'm guessing that the `sst` mentioned in the message disappeared while `du` was running.

**Comment by tbg** [comment]
The method already handled this. Do you want the error message to be hidden?

**Comment by petermattis** [comment]
Yeah, the error message is disconcerting if in fact it is being handled. Perhaps we should look for that error and retry a few times.

**Comment by andreimatei** [comment]
I just ran into this message and I'd also vote for it to go away :)
