### ISSUE TITLE
sql: INSERT with placeholders causes panic in plan_node_to_row_source

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#32540]
https://sentry.io/cockroach-labs/cockroachdb/issues/772136028/?referrer=webhooks_plugin

conn_executor.go:670: panic while executing 1 statements: INSERT INTO _(_, _, _, _, _, _, _, _, _) VALUES ($1, $2, __more7__) RETURNING _._: caused by <redacted>

github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1

> stacktrace: {u'frames': [{u'function': u'func4', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go', u'lineno': 309, u'in_app': True}, {u'function': u'ServeConn', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*Server)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'lineno': 420, u'in_app': True}, {u'function': u'run', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'lineno': 1200, u'in_app': True}, {u'function': u'execStmt', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'lineno': 95, u'in_app': True}, {u'function': u'execStmtInOpenState', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'lineno': 403, u'in_app': True}, {u'function': u'dispatchToExecutionEngine', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'lineno': 825, u'in_app': True}, {u'function': u'execWithDistSQLEngine', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'lineno': 983, u'in_app': True}, {u'function': u'PlanAndRun', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go', u'lineno': 746, u'in_app': True}, {u'function': u'Run', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go', u'lineno': 253, u'in_app': True}, {u'function': u'StartSync', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go', u'lineno': 602, u'in_app': True}, {u'function': u'Run', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go', u'lineno': 731, u'in_app': True}, {u'function': u'Run', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go', u'lineno': 170, u'in_app': True}, {u'function': u'Next', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go', u'lineno': 213, u'in_app': True}, {u'function': u'DatumToEncDatum', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/encoded_datum.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/sqlbase', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/sqlbase/encoded_datum.go', u'lineno': 161, u'in_app': True}, {u'function': u'gopanic', u'abs_path': u'/usr/local/go/src/runtime/panic.go', u'module': u'runtime', u'filename': u'runtime/panic.go', u'lineno': 502, u'in_app': False}, {u'function': u'call32', u'abs_path': u'/usr/local/go/src/runtime/asm_amd64.s', u'module': u'runtime', u'filename': u'runtime/asm_amd64.s', u'lineno': 573, u'in_app': False}, {u'function': u'func1', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'lineno': 418, u'in_app': True}]}
type: *log.safeError
value: conn_executor.go:670: panic while executing 1 statements: INSERT INTO _(_, _, _, _, _, _, _, _, _) VALUES ($1, $2, __more7__) RETURNING _._: caused by <redacted>

**Comment by rytaft** [comment]
Not sure who should own this one... looks like a datatype mismatch:
https://github.com/cockroachdb/cockroach/blob/20cf97874eb2457296976a8ed76ac08dfa3e7644/pkg/sql/sqlbase/encoded_datum.go#L161
cc @knz, @jordanlewis

**Comment by knz** [comment]
```
*log.safeError: conn_executor.go:670: panic while executing 1 statements: INSERT INTO _(_, _, _, _, _, _, _, _, _) VALUES ($1, $2, __more7__) RETURNING _._: caused by <redacted>
  File "github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go", line 418, in func1
  File "runtime/asm_amd64.s", line 573, in call32
  File "runtime/panic.go", line 502, in gopanic
  File "github.com/cockroachdb/cockroach/pkg/sql/sqlbase/encoded_datum.go", line 161, in DatumToEncDatum
  File "github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go", line 213, in Next
  File "github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go", line 170, in Run
  File "github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go", line 731, in Run
  File "github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go", line 602, in StartSync
  File "github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go", line 253, in Run
  File "github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go", line 746, in PlanAndRun
  File "github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go", line 983, in execWithDistSQLEngine
  File "github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go", line 825, in dispatchToExecutionEngine
  File "github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go", line 403, in execStmtInOpenState
  File "github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go", line 95, in execStmt
  File "github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go", line 1200, in run
  File "github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go", line 420, in ServeConn
  File "github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go", line 309, in func4
```

**Comment by knz** [comment]
The report is for v2.1.0.

There are placeholders in this query. It may be that the actual type of the value passed via the placeholder differs from the type decided during planning. @jordanlewis thoughts?

**Comment by jordanlewis** [comment]
Hm, I'll take a look, though I doubt up front that this is directly related to PNTRS- more likely in my mind an issue with the types reported by returning. But either way definitely something suspicious.

**Comment by jordanlewis** [comment]
This was fixed on `master` - there's a guard making sure that `nil` datums can't be passed into `DatumToEncDatum` now.
