### ISSUE TITLE
ccl/backupccl: surprises due to late creation of restored table descriptor

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#32543]
AFAICT (and correct me if this is wrong), RESTORE does not populate `system.descriptor` until the restore is finished. This has two surprising effects. The first is that a table being restored does not show up on the databases page in the admin UI. The second is that the first range of a table being restored is a merge candidate with the previous range because the merge queue does not see a need for a split point between the two ranges. This latter problem is addressed #32538 by disabling merges for tables being restored.

I'm guessing that `system.descriptor` is not populated until the restore is done to prevent people from attempting to read or write the table while it is being restored. This is reasonable on the surface, but I think it would be better to have an explicit bit in the table descriptor preventing access. Then users could see the table, and at least introspect its schema.

**Comment by rolandcrosby** [comment]
We could switch this to the new IMPORTING state after validating that everything else is checking that state correctly.

**Comment by dt** [comment]
@pbardea this can be closed as done, correct?

**Comment by pbardea** [comment]
Yep, closed by #39698.
