### ISSUE TITLE
sql: support ALTER TABLE ... RENAME CONSTRAINT

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#32555]
**Describe the solution you'd like**

Enable renaming constraints with `ALTER TABLE ... RENAME CONSTRAINT`

https://www.postgresql.org/docs/10/sql-altertable.html

**Comment by femiagbabiaka** [comment]
@knz 👋 first time contributor, making a first pass at this. first, thanks for the phenomenal contributing documentation. wanted to make a few questions about some assumptions I'm making.

For reference, here's my work so far: https://github.com/femiagbabiaka/cockroach/pull/1

- How do I know which constraints an operation needs? Why do I have the choice between MySQL and Postgres if only Postgres permissions get passed in?
- Where does requireTableDesc come from?
- I see that tableDesc holds pointers to each index, which information about those indexes -- what I don't see is where the _names_ of those indexes are, the IndexDescriptor struct doesn't seem to hold them.

**Comment by awoods187** [comment]
Needed for https://github.com/cockroachlabs/support/issues/267

**Comment by knz** [comment]
Fixing in #35091.

**Comment by knz** [comment]
@awoods187 lmk if this needs a backport to 2.1
