### ISSUE TITLE
sql: support INSERT ... ON CONFLICT(...) WHERE ...

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#32557]
**Describe the solution you'd like**

Support a WHERE clause after the conflict column specification in INSERT...ON CONFLICT

This is the "WHERE index_predicate" sub-clause in the "conflict_target" clause of https://www.postgresql.org/docs/10/sql-insert.html.

**Comment by jordanlewis** [comment]
This appears to be done and is no longer linked from the code at all.

```
demo@127.0.0.1:58341/defaultdb> insert into a values(1,2) on conflict(a) do update set b=3 where excluded.b=1;
INSERT 0

Time: 1ms total (execution 1ms / network 0ms)
```
