### ISSUE TITLE
importccl: enable importing GEOMETRY columns from MySQL

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#32559]
IMPORT with GEOMETRY columns should succeed.

Note: This will need solving #21286 as a prerequisite.

Epic CRDB-8825

Jira issue: CRDB-4732

**Comment by knz** [comment]
cc @otan @sumeerbhola for tracking

**Comment by otan** [comment]
not sure how mysql changes things (i think this should work as is) -- but will test this out later.

**Comment by dikshant** [comment]
With IMPORT MYSQLDUMP being deprecated: #93660 and [Schema Conversion Tool](https://www.cockroachlabs.com/docs/cockroachcloud/migrations-page) being better for schema migrations this is no longer needed and can now be closed.
