### ISSUE TITLE
importccl: enable importing MySQL BIT columns

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#32561]
https://dev.mysql.com/doc/refman/5.7/en/bit-type.html

> The BIT data type is used to store bit values. A type of BIT(M) enables storage of M-bit values. M can range from 1 to 64. 

Under the hood MySQL's BIT is really just a 64-bit integer and behaves as such with regards to arithmetic.

This is *very* different from postgres' BIT type (a bit array of arbitrary length with special operators). 

This type can be imported into CockroachDB as an integer.

Epic CRDB-8825

Jira issue: CRDB-4730

**Comment by rolandcrosby** [comment]
The error message on this is also misspelled:
`pq: unimplemented: cannot improt BIT columns at this time`

This should be simple to automatically map to a 64-bit integer. I'm adding `good first issue` in case anyone in the community feels like taking this on.

**Comment by devdil** [comment]
@rolandcrosby can I pick this up?

**Comment by knz** [comment]
@devdil you can give it a try

**Comment by dikshant** [comment]
With IMPORT MYSQLDUMP being deprecated: #93660 and [Schema Conversion Tool](https://www.cockroachlabs.com/docs/cockroachcloud/migrations-page) being better for schema migrations this is no longer needed and can now be closed.
