### ISSUE TITLE
importccl: enable importing MySQL SET columns

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#32560]
https://dev.mysql.com/doc/refman/5.7/en/set.html

> A SET is a string object that can have zero or more values, each of which must be chosen from a list of permitted values specified when the table is created. SET column values that consist of multiple set members are specified with members separated by commas (,). A consequence of this is that SET member values should not themselves contain commas. 

Technically, the MySQL "SET" pseudo-type is a 64-bit bitmask under the hood. Each bit in the bitmask is given a name in the table descriptor. 

This can be imported into cockroachdb as an integer.

Epic CRDB-8825

Jira issue: CRDB-4731

**Comment by kurokochin** [comment]
Hi, I'm interested to work on this. I might need a few pointers regarding what changes needed to be made.

My current understanding:
- We just want to consider `SET` as an integer (need to made changes in `pkg/ccl/importccl/read_import_mysql.go` and modify `case mysqltypes.Set` from throwing error to define the type `def.Type = types.Int`)
- Need to add test inside `everything.cockroach-schema.sql` and modify the expected result in `everything.sql`

cc @knz kindly correct me I'm wrong

Thanks in advanced!

**Comment by dikshant** [comment]
With IMPORT MYSQLDUMP being deprecated: #93660 and [Schema Conversion Tool](https://www.cockroachlabs.com/docs/cockroachcloud/migrations-page) being better for schema migrations, this is no longer needed and can now be closed.
