### ISSUE TITLE
sql: support sequence CACHE options with parameter >1

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#32567]
https://www.postgresql.org/docs/10/sql-createsequence.html

> The optional clause CACHE cache specifies how many sequence numbers are to be preallocated and stored in memory for faster access. The minimum value is 1 (only one value can be generated at a time, i.e., no cache), and this is also the default.

This could be implemented as a no-op. 

Users are invited to document / report how this feature is used in their application.

Jira issue: CRDB-4728

**Comment by otan** [comment]
now supported!
