### ISSUE TITLE
sql: JSONB vs JSON, and using json_object_keys()

### ISSUE THREAD

**Issue by antoniuslin** [cockroachdb/cockroach#32566]
Hello,

First I'm not certain if this is a true bug, or just a (me) user-error. But I was going through a different problem for which I posed a question in [CockroachLabs forum](https://forum.cockroachlabs.com/t/built-in-json-functions-and-documentations/2192/2) , and [a new friend](https://forum.cockroachlabs.com/u/jesse/summary) was not able to reproduce my issue and suggested I open a GitHub issue here.

The problem(s) statement could be:
**I created a table with a field using JSONB datatype, however the table was created as a JSON datatype instead. Further, when I queried the table, a simple query works just fine but a query using [`json_object_keys`](https://www.cockroachlabs.com/docs/v2.1/functions-and-operators.html#jsonb-functions) or `jsonb_object_keys` (which I tried for due-diligence even though I couldn't find it in the docs) function returned an error.**

I do notice from [CockroachDB docs](https://www.cockroachlabs.com/docs/stable/jsonb.html) that:
> In CockroachDB, JSON is an alias for JSONB.

whereas:
> Note:
In PosgreSQL, JSONB and JSON are two different data types. In CockroachDB, the JSONB / JSON data type is similar in behavior to the JSONB data type in PostgreSQL. 
Please describe the issue you observed, and any steps we can take to reproduce it:

Here are the steps to reproduce:
```
vagrant@ubuntu-bionic: ~
$ cockroach version
Build Tag:    v2.0.6
Build Time:   2018/10/01 13:59:40
Distribution: CCL
Platform:     linux amd64 (x86_64-unknown-linux-gnu)
Go Version:   go1.10
C Compiler:   gcc 6.3.0
Build SHA-1:  d30787727998a453fcae13c5a0c90f27f02a69f2
Build Type:   release

root@:26257/> create database testcrdb;
CREATE DATABASE

Time: 46.49159ms

root@:26257/gigya_proxy> use testcrdb;
SET

Time: 409.22µs

root@:26257/testcrdb> create table "ProcessLogs" ( "key" string(128) not null, data jsonb not null, iso_timestamp timestamp with time zone not null, unix_timestamp int not null, source string not null, constraint "primary" primary key (key asc));
CREATE TABLE

Time: 29.916392ms

root@:26257/testcrdb> show create table "ProcessLogs";
+---------------+-------------------------------------------------------------------------+
|     Table     |                               CreateTable                               |
+---------------+-------------------------------------------------------------------------+
| "ProcessLogs" | CREATE TABLE "ProcessLogs" (                                            |
|               |                                                                         |
|               |     key STRING(128) NOT NULL,                                           |
|               |                                                                         |
|               |     data JSON NOT NULL,                                                 |
|               |                                                                         |
|               |     iso_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,                    |
|               |                                                                         |
|               |     unix_timestamp INT NOT NULL,                                        |
|               |                                                                         |
|               |     source STRING NOT NULL,                                             |
|               |                                                                         |
|               |     CONSTRAINT "primary" PRIMARY KEY (key ASC),                         |
|               |                                                                         |
|               |     FAMILY "primary" (key, data, iso_timestamp, unix_timestamp, source) |
|               |                                                                         |
|               | )                                                                       |
+---------------+-------------------------------------------------------------------------+
(1 row)

Time: 3.491826ms
```

... [inserted a few test records] then...

```
root@:26257/testcrdb> select data->'perflogs' from "ProcessLogs";
+--------------------------------------------------------------------------+
|                             data->'perflogs'                             |
+--------------------------------------------------------------------------+
| {"07e9e530-ea12-11e8-b170-51f9d11d2758": {"crumb":                       |
| {"622a1f70-4329-418e-bfa3-39497f24d8ed": {"fn": "validateRequest",       |
... abridged
```

However, either using the function `json_object_keys()` or `json`(**b**)`_object_keys()`
```
root@:26257/testcrdb> select json_object_keys(data->'perflogs') from "ProcessLogs";
pq: column name "data" not found
root@:26257/testcrdb> select jsonb_object_keys(data->'perflogs') from "ProcessLogs";
pq: column name "data" not found
root@:26257/testcrdb> \q
Error: pq: column name "data" not found
Failed running "sql"

```

All of the above had executed successfully in RDS PostgreSQL as I noted in my [forum entry](https://forum.cockroachlabs.com/t/built-in-json-functions-and-documentations/2192/2). And again I'm uncertain if this was a real problem, not a problem, or even two different problems.
Thank you.

**Comment by knz** [comment]
I think the problem is not related to the name of the types, but rather how CockroachDB handles the `jsonb_object_keys()` built-in function. 

@justinj could you skim through the issue description and give your first impression? What is an adequate course of action here?

**Comment by antoniuslin** [comment]
@knz Thanks for your response.
I'm adding an entry here in order to provide a less verbose reproduction steps that can be copy & pasted.
```
root@:26257/testcrdb> create table test2 (id int, data jsonb);
CREATE TABLE

Time: 40.573289ms

root@:26257/testcrdb> show create table test2;
+-------+----------------------------------------+
| Table |              CreateTable               |
+-------+----------------------------------------+
| test2 | CREATE TABLE test2 (                   |
|       |                                        |
|       |     id INT NULL,                       |
|       |                                        |
|       |     data JSON NULL,                    |
|       |                                        |
|       |     FAMILY "primary" (id, data, rowid) |
|       |                                        |
|       | )                                      |
+-------+----------------------------------------+
(1 row)

Time: 5.215572ms

root@:26257/testcrdb> insert into test2 values (1, '{"perflogs": {"07e9e530-ea12-11e8-b170-51f9d11d2758": {"crumb": [1, 2, 3]}}}');
INSERT 1

Time: 23.84091ms

root@:26257/testcrdb> select * from test2;
+----+--------------------------------------------------------------------------+
| id |                                   data                                   |
+----+--------------------------------------------------------------------------+
|  1 | {"perflogs": {"07e9e530-ea12-11e8-b170-51f9d11d2758": {"crumb": [1, 2,   |
|    | 3]}}}                                                                    |
+----+--------------------------------------------------------------------------+
(1 row)

Time: 1.329273ms

root@:26257/testcrdb> select data->'perflogs' from test2;
+----------------------------------------------------------------+
|                        data->'perflogs'                        |
+----------------------------------------------------------------+
| {"07e9e530-ea12-11e8-b170-51f9d11d2758": {"crumb": [1, 2, 3]}} |
+----------------------------------------------------------------+
(1 row)

Time: 1.743274ms

root@:26257/testcrdb> select json_object_keys(data->'perflogs') from test2;
pq: column name "data" not found
```

**Comment by knz** [comment]
Oh I see it now. You seem to be using crdb 2.0. Also your query is (implicitly) correlated.

Crdb 2.0 cannot support this type of correlated subquery I think. Can you check with crdb 2.1?

Thanks
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by antoniuslin** [comment]
Hi @knz,

You're right! It's a version issue, as in I was using 2.0.6 and didn't know 2.1 was already out. `JSONB` data typing now even shows up as `JSONB` as specified. Thanks so much!

*Snippets indicating the topical problem I raised in this ticket is non-existent with v2.1.1.*
```
vagrant@ubuntu-bionic: ~
$ cockroach version
Build Tag:    v2.1.1
Build Time:   2018/11/19 18:24:21
Distribution: CCL
Platform:     linux amd64 (x86_64-unknown-linux-gnu)
Go Version:   go1.10.3
C Compiler:   gcc 6.3.0
Build SHA-1:  4523f9819d2dde9b054fc8faf1568e107f130986
Build Type:   release

vagrant@ubuntu-bionic: ~
$ cockroach sql
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.
#
# Server version: CockroachDB CCL v2.1.1 (x86_64-unknown-linux-gnu, built 2018/11/19 18:24:21, go1.10.3) (same version as client)
# Cluster ID: b2b07108-ed15-4b0c-b8c9-ff803778cf28
#
# Enter \? for a brief introduction.
#
root@:26257/defaultdb> create table test3 (id int, data jsonb);
CREATE TABLE

Time: 42.448199ms

root@:26257/defaultdb> show create table test3;
  table_name |            create_statement
+------------+----------------------------------------+
  test3      | CREATE TABLE test3 (
             |     id INT NULL,
             |     data JSONB NULL,
             |     FAMILY "primary" (id, data, rowid)
             | )
(1 row)

Time: 3.62459ms

root@:26257/defaultdb> insert into test3 values (1, '{"perflogs": {"07e9e530-ea12-11e8-b170-51f9d11d2758": {"crumb": [1, 2, 3]}}}');
INSERT 1

Time: 29.063914ms

root@:26257/defaultdb> select * from test3;
  id |                                     data
+----+------------------------------------------------------------------------------+
   1 | {"perflogs": {"07e9e530-ea12-11e8-b170-51f9d11d2758": {"crumb": [1, 2, 3]}}}
(1 row)

Time: 3.247192ms

root@:26257/defaultdb> select json_object_keys(data->'perflogs') from test3;
            json_object_keys
+--------------------------------------+
  07e9e530-ea12-11e8-b170-51f9d11d2758
(1 row)

Time: 1.572645ms

root@:26257/defaultdb> select jsonb_object_keys(data->'perflogs') from test3;
           jsonb_object_keys
+--------------------------------------+
  07e9e530-ea12-11e8-b170-51f9d11d2758
(1 row)

Time: 1.616957ms
```

A few side questions, if I may? (Please do let me know if I should move these questions to a forum instead: I began evaluating and using CRDB on 2018/10/19, at which time it was at v.2.0.6. And I didn't know nor follow the release progression from 2.0.6 to 2.1 just around the corner on 2018/10/30. And just a few days ago, there's a minor bump to v2.1.1.

* There seems to also have "internal" things that seems to have changed, such as `show tables` and `show create table` which had shown `Table` to now show `table_name` in the result set column name. How often are "object names" changed from release to release? Is there a set of standard criteria for these type of (object name) changes?
* Although CRDB uses PostgreSQL wire protocol, the commands runnable using `cockroach sql` cli seem to follow MySQL rather than `psql` cli. Is it crdb dialect closer to `psql` or `mysql`?
* While I understand each DB platform/vendor may have their own preferred dialect mixes, does CRDB team have plans to follow [ANSI SQL](https://blog.ansi.org/2018/10/sql-standard-iso-iec-9075-2016-ansi-x3-135/), aside from CRDB's own preferred differentiators?
* If I have a set of query, triggers, procedures, functions, etc. scripts that have worked properly in PostgreSQL, how big of a compatibility plane coverage do we get from crdb that it uses PostgreSQL wire protocol? 100% from pg transferable to crdb?
* Do we have a documentation comparison (similar to how we have one here https://www.cockroachlabs.com/docs/stable/cockroachdb-in-comparison.html, except for the SQL dialect? (I tried to read through the Product and SQL FAQs but couldn't find the info I sought). I found a mention of _standard SQL_, but it doesn't specify which standard. Is there also a standard for the cli?
* Last (for now), I would like to better understand and follow CockroachLabs release and versioning schemes. Does CRDB team have a formal release schedule that can be followed for the Community edition? Eg., perhaps something similar to how Canonical/Ubuntu does its [release cycles](https://www.ubuntu.com/about/release-cycle), LTS, significant jump, minor but critical fixes, etc? 

Thank you very much for your time and patience with me and all my questions.

**Comment by knz** [comment]
>    There seems to also have "internal" things that seems to have changed, such as show tables and show create table which had shown Table to now show table_name in the result set column name. 

The `SHOW` commands are "porcelain" meant for use by humans and not automation. For automation use `information_schema` or `pg_catalog`. That won't change.

> How often are "object names" changed from release to release?

Existing objects won't change usually across releases. This time an exception was made because the naming was previously extremely irregular.

> Is there a set of standard criteria for these type of (object name) changes?

This has been discussed in #27098.

>    Although CRDB uses PostgreSQL wire protocol, the commands runnable using cockroach sql cli seem to follow MySQL rather than psql cli. Is it crdb dialect closer to psql or mysql?

I do not understand what you mean. 
The dialect is that of PostgreSQL. **In addition** there are CockroachDB extensions, for example `USE` is an alias for `SET database = ` and there are `SHOW` commands that inspect `information_schema` and `crdb_internal` "under the hood".

>    While I understand each DB platform/vendor may have their own preferred dialect mixes, does CRDB team have plans to follow ANSI SQL, aside from CRDB's own preferred differentiators?

"ANSI SQL" is not a thing in the real world. There is an ISO standard but every SQL engine under the sun will have its own specific interpretations of it. 

CockroachDB follows PostgreSQL's example first; when PostgreSQL is unclear we look at the SQL standard for inspiration, then at other engines (eg MSSQL).

>    If I have a set of query, triggers, procedures, functions, etc. scripts that have worked properly in PostgreSQL, how big of a compatibility plane coverage do we get from crdb that it uses PostgreSQL wire protocol? 100% from pg transferable to crdb?

No (not yet). CockroachDB does not support triggers, stored procedures, user-defined functions and types, and several other things from postgres.

Please read this: https://www.cockroachlabs.com/blog/why-postgres/

>    Do we have a documentation comparison (similar to how we have one here cockroachlabs.com/docs/stable/cockroachdb-in-comparison.html, except for the SQL dialect? (I tried to read through the Product and SQL FAQs but couldn't find the info I sought). I found a mention of standard SQL, but it doesn't specify which standard. 

Have you tried this:

https://www.cockroachlabs.com/docs/stable/sql-feature-support.html

https://www.cockroachlabs.com/docs/stable/detailed-sql-support.html


> Is there also a standard for the cli?

What are you asking? The CLI interface is only an interface to what the server supports. There are extremely few commands that are specific to the CLI, you see them documented with `\?`:

```
  \q to exit        (Ctrl+C/Ctrl+D also supported)
  \! CMD            run an external command and print its results on standard output.
  \| CMD            run an external command and run its output as SQL statements.
  \set [NAME]       set a client-side flag or (without argument) print the current settings.
  \unset NAME       unset a flag.
  \show             during a multi-line statement or transaction, show the SQL entered so far.
  \? or "help"      print this help.
  \h [NAME]         help on syntax of SQL commands.
  \hf [NAME]        help on SQL built-in functions.
```

>    Last (for now), I would like to better understand and follow CockroachLabs release and versioning schemes. Does CRDB team have a formal release schedule that can be followed for the Community edition? 

Yes. Although it is not documented yet, we aim for:

- 2 major release per year (2.0 end of Q1 2018, 2.1 end of Q3 2018, 2.2 end of Q2 2019, etc)
- point releases every month / 2 months in-between
- bug fixes will be issued for the last release in addition to current betas
- security fixes will be issued for the last 2 releases

This is subject to change because the project is still young and we need to figure things out.

Does this help?

This is not exactly the right platform to discuss this. Please consider perusing the forum instead.

**Comment by antoniuslin** [comment]
@knz 
Lots of great and useful info.
Thanks so much!
