### ISSUE TITLE
sql: support pg_collation_for() and its COLLATION FOR () syntactic sugar

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#32563]
https://www.postgresql.org/docs/10/functions-info.html

The built-in function `pg_catalog.pg_collation_for()` returns the collation of a collated string.

Additionally, the grammar recognizes a special syntax `COLLATION FOR (<expr>)` which is syntactic sugar for a call to `pg_collation_for()`.

**Comment by Zyqsempai** [comment]
Is this still actual? I can take it if it so;)

**Comment by knz** [comment]
yes still actual. feel welcome!

**Comment by Zyqsempai** [comment]
@knz Sorry, it's my first issue here, do we have some kind of documentation or guide how to implement new SQL functions? coz I devied in, found a lot of stuff but don't know where to start.

**Comment by Gurio** [comment]
@knz still actual? :)

**Comment by jordanlewis** [comment]
Yes! Feel free to take a look.

**Comment by Gurio** [comment]
@jordanlewis cool, will do.
