### ISSUE TITLE
kv: timeseries range stats are wildly over estimated

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#32576]
While running `restore2TB` as a part #32538, I was looking for any range merges on the system. About an hour into the run I saw:

`I181123 17:29:34.543462 257031 storage/merge_queue.go:271  [n10,merge,s10,r5/4:/System/tsd{-/cr.sto…}] merging ranges: /System/tsd{-/cr.store.valcount/9/10s/2018-11-23T17:00:00Z} + /System/ts{d/cr.store.valcount/9/10s/2018-11-23T17:00:00Z-e} -> /System/ts{d-e}`

Shortly before that the logs contain:

`I181123 17:29:34.368672 256982 storage/replica_command.go:306  [n10,split,s10,r5/4:/System/ts{d-e}] initiating a split of this range at key /System/tsd/cr.store.valcount/9/10s/2018-11-23T17:00:00Z [r16838]`

It looks like we merged a timeseries range a few hundred milliseconds after it was split. Not that merge queue log message is new instrumentation I added. It is performed after all of the checks for not merging.

I'm not sure what the size of `r5` was before the split or the merge, but right now it is sitting at 46.2 MiB.

**Comment by petermattis** [comment]
One thing to be aware of is that the MVCC stats are estimates for timeseries ranges. When a split occurs that stats are recomputed from scratch. I suspect we overestimate the size for timeseries ranges so after a split the two halves might be significantly smaller than the pre-split estimate.

**Comment by tbg** [comment]
Yes, the timeseries stats are wildly overestimated (I don't have the numbers, but every time I see a recomputation of the stats the delta shrinks the stats a lot). I think we should fix that first.

**Comment by tbg** [comment]
Curiously, we claim to undercount

https://github.com/cockroachdb/cockroach/blob/1d9eb0cadcb2a3c10ef0d00bd2acbd0fdae2fd06/pkg/storage/engine/mvcc.go#L199-L218

but I don't think that's true. The caller supplies the full size of the payload

https://github.com/cockroachdb/cockroach/blob/1d9eb0cadcb2a3c10ef0d00bd2acbd0fdae2fd06/pkg/storage/engine/mvcc.go#L1616-L1617

so we're overcounting the overhead within, every time.

**Comment by irfansharif** [comment]
We'd probably want to stop adding `mvccVersionTimestampSize` to MVCC stats on each merge operation (and probably update the comment to reflect what's actually happening). Each merge (by definition) is getting merged into the same key, so we're not really incurring the metadata overhead each time. Given how frequently merges happen with timeseries data, this alone should make our MVCC stats around this stuff much saner than before.

We'd also want to test this behavior, and seems like `TestMVCCTimeSeriesPartialMerge` has the enough hooks in place that we could graft and construct a specific `TestTimeSeriesMVCCStats` unit test out of.
