### ISSUE TITLE
opt: top-k sort is not accurately reported in EXPLAIN

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#32577]
Given the simple table:

```
root@127.0.0.1:65097/defaultdb> create table a (a int);
CREATE TABLE
```

EXPECTED (with `optimizer=off`):

```
root@127.0.0.1:65097/defaultdb> explain select * from a order by a limit 1;
         tree         |  field   | description
+---------------------+----------+-------------+
  limit               |          |
   │                  | count    | 1
   └── sort           |          |
        │             | order    | +a
        │             | strategy | top 1
        └── render    |          |
             └── scan |          |
                      | table    | a@primary
                      | spans    | ALL
(9 rows)
```

ACTUAL: (with `optimizer=on`):

```
root@127.0.0.1:65097/defaultdb> explain select * from a order by a limit 1;
       tree      | field | description
+----------------+-------+-------------+
  limit          |       |
   │             | count | 1
   └── sort      |       |
        │        | order | +a
        └── scan |       |
                 | table | a@primary
                 | spans | ALL
```

The top-k strategy is more efficient than the full-sort strategy. We should be choosing it when possible (when there's a limit).

**Comment by jordanlewis** [comment]
Hmm, actually, I think the top k sorter might be planned here after all, but the explain output doesn't show that. Either way, something to look into.

**Comment by andy-kimball** [comment]
@RaduBerinde, can you take a look?

**Comment by RaduBerinde** [comment]
@jordanlewis the distsql planner doesn't look at `sortStrategy`.. The top K strategy is used automatically if the sort processor has a Limit.

The optimizer doesn't have any knowledge of this optimization currently. It should, at least from a costing perspective. But in practice, the distsql plan should be as desired in most cases.

**Comment by jordanlewis** [comment]
Oh I see. Okay, yes, the distsql plan is correct - but the `explain` output isn't. We point people to that a lot, so we should really fix it if possible...

**Comment by jordanlewis** [comment]
Actually, perhaps we should just give up on trying to keep the strategies accurate in ordinary `explain`? I'm not really sure... It seems like our `explain` is logical-only, and `explain(distsql)` is physical. Perhaps over time we'll want to unify the two representations somehow.

**Comment by RaduBerinde** [comment]
I do think it's valuable to show this accurately. Note that the EXPLAIN also doesn't show the "streaming sort" (e.g. when we already have an ordering on `a` but we need one on `a,b`) which is distsql-only.

When the optimizer will know about these variants, it will set things up so they are shown accurately by EXPLAIN.

**Comment by rytaft** [comment]
Oops didn't mean to close this. Was going to add that it looks like this still still an issue:
```
create table a (a int);

demo@127.0.0.1:26257/movr> explain (opt,verbose) select * from a order by a limit 1;
                info
-------------------------------------
  limit
   ├── columns: a:1
   ├── internal-ordering: +1
   ├── cardinality: [0 - 1]
   ├── stats: [rows=1]
   ├── cost: 1303.95569
   ├── key: ()
   ├── fd: ()-->(1)
   ├── sort
   │    ├── columns: a:1
   │    ├── stats: [rows=1000]
   │    ├── cost: 1303.93569
   │    ├── ordering: +1
   │    ├── limit hint: 1.00
   │    ├── prune: (1)
   │    └── scan a
   │         ├── columns: a:1
   │         ├── stats: [rows=1000]
   │         ├── cost: 1074.61
   │         └── prune: (1)
   └── 1
(21 rows)

Time: 2ms total (execution 2ms / network 0ms)

demo@127.0.0.1:26257/movr> explain (verbose) select * from a order by a limit 1;
                                         info
---------------------------------------------------------------------------------------
  distribution: full
  vectorized: true

  • limit
  │ columns: (a)
  │ estimated row count: 1
  │ count: 1
  │
  └── • sort
      │ columns: (a)
      │ ordering: +a
      │ estimated row count: 1
      │ order: +a
      │
      └── • scan
            columns: (a)
            estimated row count: 1 (100% of the table; stats collected 5 seconds ago)
            table: a@primary
            spans: FULL SCAN
(19 rows)

Time: 6ms total (execution 5ms / network 1ms)

demo@127.0.0.1:26257/movr> explain (vec) select * from a order by a limit 1;
                info
------------------------------------
  │
  └ Node 1
    └ *colexec.limitOp
      └ *colexec.topKSorter
        └ *colfetcher.ColBatchScan
(5 rows)

Time: 9ms total (execution 8ms / network 0ms)
```
As shown above: The optimizer plan includes a limit hint, and the vectorized plan shows that is uses a top-k sorter. We should also show this in the regular explain.

This will be a good starter project for new members of the team.

**Comment by rharding6373** [comment]
@mgartner and I looked into this today. In line with the comments above, the optimizer still doesn't appear to know when topk is done. The decision to use topk sort is made by distsql in [execplan.go](https://github.com/cockroachdb/cockroach/blob/bc95d8f5e79576e38208b89af65a2050ab52b982/pkg/sql/colexec/colbuilder/execplan.go#L396):

```
	if matchLen > 0 {
...
          } else if post.Limit != 0 && post.Limit < math.MaxUint64-post.Offset {
...
		topK = post.Limit + post.Offset
		inMemorySorter = colexec.NewTopKSorter(
			colmem.NewAllocator(ctx, topKSorterMemAccount, factory), input, inputTypes,
			ordering.Columns, topK,
		)
...
          }
```

`post.Limit` and `post.Offset` look like they are set in [physical_plan.go](https://github.com/cockroachdb/cockroach/blob/bc95d8f5e79576e38208b89af65a2050ab52b982/pkg/sql/physicalplan/physical_plan.go#L723) in `AddLimit()`. Still pulling on threads to determine what variables available in the optimizer `post.Limit` and `post.Offset` are based on.

One option is to have the optimizer infer when topk sort will be used based on the variables above and add the same calculation from distsql to the optimizer, maybe in [emit.go](https://github.com/cockroachdb/cockroach/blob/bc95d8f5e79576e38208b89af65a2050ab52b982/pkg/sql/opt/exec/explain/emit.go#L462), to include this information in EXPLAIN.

Alternatively, should we bring the decision to do topk sort into the optimizer? Is topk sort only supported by the vec exec engine?

**Comment by jordanlewis** [comment]
> Is topk sort only supported by the vec exec engine?

No, it's supported by both vec and row. Moving the decision into the optimizer seems like the right idea to me - I think the more logic we can remove from `execplan.go` the better.

**Comment by jordanlewis** [comment]
cc @rytaft, thoughts on the above?

**Comment by rytaft** [comment]
I agree that the optimizer should make this decision, since it should be included in the cost model for the sort.

**Comment by mgartner** [comment]
We had trouble tracking down where the sort's post processor spec `Limit` value came from in the optimizer world. A sort expression in the optimizer has no hard limit so it must come from it's parent `Limit` expression?

**Comment by rytaft** [comment]
Hmm I guess it must come from the parent. This does make things a bit tricky since currently we only support adding a `Sort` operator as an enforcer. To make this work we'd probably need to add support for a new relational operator called `TopKSort` (or something like that) along with an exploration rule to create it from a `Limit` that has a required ordering. This would definitely be a much more comprehensive change than simply adding a new field to `EXPLAIN`, and probably not an ideal starter project 😂

For now, we could probably do something hacky where we detect the Limit-Sort pattern in the `execbuilder`, add a limit to the factory interface for Sort, and use the limit inside `emit.go` to report the top-k sort. But if this feels too hacky we could also leave this issue aside for the moment and come back to it later.

**Comment by RaduBerinde** [comment]
The way this works currently is pretty subtle. It is done implicitly by the distsql physical planner: we build the sort processor as usual, and subsequently the `limitNode` causes us to set the Limit in the sort processor's `PostProcessSpec`. Then the processor automatically does top-k if it sees a limit in its spec.

I agree this decision should be up to the optimizer. We will want to cost this operation differently (which can be significant because of buffering cost).

In addition to the two options @rytaft mentioned above, we could also improve the required physical properties to store both a "soft" limit (the current LimitHint) and a "hard" limit. Overall, it feels like the `TopKSort` operator is the right thing to do. It might not be too bad of a starter project actually (I would do it in two stages; the first one doesn't change the exec factory at all and we still build `TopKSort` as a sort followed by a limit; then step 2 would be to plumb this through the factory).

**Comment by mgartner** [comment]
It's not the easiest first project, but it'll be a great tour of the optimizer. I'll discuss with @rharding6373 in our meeting today.
