### ISSUE TITLE
sentry: conn_executor.go:670: panic while executing 1 statements: INSERT INTO _(_, _) VALUES (_, _), (__more1__) ON CONFLICT (_) DO UPDATE SET _ = now(), _ = _._ || jsonb_build_object() RETURNING _ AS _, _: caused by <redacted>

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#32579]
https://sentry.io/cockroach-labs/cockroachdb/issues/775906171/?referrer=webhooks_plugin

conn_executor.go:670: panic while executing 1 statements: INSERT INTO _(_, _) VALUES (_, _), (__more1__) ON CONFLICT (_) DO UPDATE SET _ = now(), _ = _._ || jsonb_build_object() RETURNING _ AS _, _: caused by <redacted>

github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1

> stacktrace: {u'frames': [{u'function': u'func4', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go', u'lineno': 309, u'in_app': True}, {u'function': u'ServeConn', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*Server)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'lineno': 420, u'in_app': True}, {u'function': u'run', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'lineno': 1143, u'in_app': True}, {u'function': u'execStmt', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'lineno': 95, u'in_app': True}, {u'function': u'execStmtInOpenState', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'lineno': 403, u'in_app': True}, {u'function': u'dispatchToExecutionEngine', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'lineno': 825, u'in_app': True}, {u'function': u'execWithDistSQLEngine', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'lineno': 983, u'in_app': True}, {u'function': u'PlanAndRun', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go', u'lineno': 746, u'in_app': True}, {u'function': u'Run', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go', u'lineno': 253, u'in_app': True}, {u'function': u'StartSync', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go', u'lineno': 602, u'in_app': True}, {u'function': u'Run', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go', u'lineno': 731, u'in_app': True}, {u'function': u'Run', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go', u'lineno': 170, u'in_app': True}, {u'function': u'Next', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go', u'lineno': 205, u'in_app': True}, {u'function': u'Next', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_batch.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*serializeNode)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/plan_batch.go', u'lineno': 123, u'in_app': True}, {u'function': u'BatchedNext', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/upsert.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*upsertNode)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/upsert.go', u'lineno': 331, u'in_app': True}, {u'function': u'atBatchEnd', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/tablewriter_upsert.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*tableUpserter)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/tablewriter_upsert.go', u'lineno': 431, u'in_app': True}, {u'function': u'updateConflictingRow', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/tablewriter_upsert.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*tableUpserter)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/tablewriter_upsert.go', u'lineno': 498, u'in_app': True}, {u'function': u'eval', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/upsert.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*upsertHelper)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/upsert.go', u'lineno': 683, u'in_app': True}, {u'function': u'Eval', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*BinaryExpr)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go', u'lineno': 2594, u'in_app': True}, {u'function': u'func86', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/sem/tree.glob.', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go', u'lineno': 1236, u'in_app': True}, {u'function': u'MustBeDJSON', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/datum.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/sem/tree', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/sem/tree/datum.go', u'lineno': 2282, u'in_app': True}, {u'function': u'gopanic', u'abs_path': u'/usr/local/go/src/runtime/panic.go', u'module': u'runtime', u'filename': u'runtime/panic.go', u'lineno': 502, u'in_app': False}, {u'function': u'call32', u'abs_path': u'/usr/local/go/src/runtime/asm_amd64.s', u'module': u'runtime', u'filename': u'runtime/asm_amd64.s', u'lineno': 573, u'in_app': False}, {u'function': u'func1', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'lineno': 418, u'in_app': True}]}
type: *log.safeError
value: conn_executor.go:670: panic while executing 1 statements: INSERT INTO _(_, _) VALUES (_, _), (__more1__) ON CONFLICT (_) DO UPDATE SET _ = now(), _ = _._ || jsonb_build_object() RETURNING _ AS _, _: caused by <redacted>

**Comment by rytaft** [comment]
cc @knz, @jordanlewis

**Comment by jordanlewis** [comment]
```
github.com/cockroachdb/cockroach/pkg/sql/sem/tree/datum.go in MustBeDJSON at line 2282
github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go in func86 at line 1236
github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go in Eval at line 2594
github.com/cockroachdb/cockroach/pkg/sql/upsert.go in eval at line 683
github.com/cockroachdb/cockroach/pkg/sql/tablewriter_upsert.go in updateConflictingRow at line 498
github.com/cockroachdb/cockroach/pkg/sql/tablewriter_upsert.go in atBatchEnd at line 431
github.com/cockroachdb/cockroach/pkg/sql/upsert.go in BatchedNext at line 331
github.com/cockroachdb/cockroach/pkg/sql/plan_batch.go in Next at line 123
github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go in Next at line 205
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go in Run at line 170
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go in Run at line 731
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go in StartSync at line 602
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go in Run at line 253
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go in PlanAndRun at line 746
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go in execWithDistSQLEngine at line 983
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go in dispatchToExecutionEngine at line 825
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go in execStmtInOpenState at line 403
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go in execStmt at line 95
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go in run at line 1143
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go in ServeConn at line 420
github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go in func4 at line 309
```

**Comment by jordanlewis** [comment]
```
                &BinOp{
                        LeftType:   types.JSON,
                        RightType:  types.JSON,
                        ReturnType: types.JSON,
                        Fn: func(_ *EvalContext, left Datum, right Datum) (Datum, error) {
                                j, err := MustBeDJSON(left).JSON.Concat(MustBeDJSON(right).JSON)
                                if err != nil {
                                        return nil, err
                                }
                                return &DJSON{j}, nil
                        },
                },
```

@knz how can this happen? The panic is that MustBeDJSON sees something that isn't a json - but the input types are supposed to guarantee that the inputs are DJSON, right?

**Comment by jordanlewis** [comment]
Can't repro.
