### ISSUE TITLE
storage: acquire read latches instead of write latches during range splits

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#32583]
Lifting the discussion from https://github.com/cockroachdb/cockroach/pull/14992#issuecomment-350491793 into its own issue.

We currently acquire write latches for the entire left-hand side and write-hand side of a range split. As a result, splits are very disruptive as they serialize with all other requests on a range. We should explore ways to make them less disruptive.

One way to accomplish this would be to declare the split as a non-MVCC read instead of an MVCC write. In practice, this would mean acquiring a read latch at timestamp 0 instead of a write latch at the transaction's timestamp. The effect of this would be that all concurrent writes to the range would be blocked but all concurrent reads to the range would be allowed.

@bdarnell writing this up did reveal a gap in my understanding about how this all works. We do currently allow reads beneath the split timestamp to be executed concurrently with a split. What makes this safe on the RHS when at any second the RHS can be removed? I think it is because of the `readOnlyCmdMu`, which we hold for the duration of the read, but we're about to remove that in https://github.com/cockroachdb/cockroach/pull/28813.

**Comment by bdarnell** [comment]
I think the proposal (at least in my head) was to use a non-MVCC read on the LHS while continuing to get a write latch on the RHS. This would of course only solve part of the problem, but it's much trickier to do anything for the RHS. I don't think we have any specific proposals for the RHS.

**Comment by nvanbenschoten** [comment]
> but it's much trickier to do anything for the RHS

that's what I'm not understanding about how things currently work. We declare an MVCC write across the entire range, which means that we allow reads at lower timestamps on both the LHS and the RHS. How is that safe? I think it's because of the `readOnlyCmdMu`, but we seem to be ok with removing that.

**Comment by bdarnell** [comment]
Hmm, that sounds like an oversight, then. Maybe it's not safe to remove readOnlyCmdMu without also changing splits to get non-mvcc write latches.

**Comment by nvanbenschoten** [comment]
There are a few items here that we'd like to address. They'll require getting familiar with the `spanlatch.Manager`, `Replica.collectSpans`, the `Replica.readOnlyCmdMu`, and `ReplicatedEvalResult.BlockReads`. The general idea is that we have a number of different mechanisms for serializing request evaluation on a Replica. We'd like to fold that into a single mechanism (`spanlatch.Manager`) while ensuring that we permit the maximum amount of concurrency possible between non-interfering requests.

The ideas we'd like to explore within this theme are:
1. expose a way for requests to declare their latches as "non-mvcc". This is currently exposed to batches that [contain a zero timestamp](https://github.com/cockroachdb/cockroach/blob/cee171c75f88ccae19834c4320511beffe7d87dc/pkg/storage/spanlatch/manager.go#L311-L313), but we'd like to let specific request types opt-in to this behavior. This can be either on a per-latch basis, a per-request basis, or a per-batch basis.
2. use this new mechanism to rework the declaration of latches during a Range split to request a non-mvcc read latch on the LHS and a non-mvcc write latch on the RHS. This should reduce their impact on foreground traffic.
3. similarly, explore the use of this new mechanism to reduce the impact of Range merges on foreground traffic. Are we being pessimistic with the latches that we acquire?
4. explore the removal of `ReplicatedEvalResult.BlockReads`. Step #2 will likely allow us to stop using it for Range splits. Can we do something similar for Range merges and lease acquisitions?
5. explore the removal of `Replica.readOnlyCmdMu`. If we address step #4 then the only remaining use of the mutex will be in `Store.removeReplicaImpl`. There's likely something we could do with the Replica's `destroyStatus` to allow us to remove the mutex entirely.

**Comment by irfansharif** [comment]
> In practice, this would mean acquiring a read latch at timestamp 0 instead of a write latch at the transaction's timestamp. The effect of this would be that all concurrent writes to the range would be blocked but all concurrent reads to the range would be allowed.

shouldn't the read latch be acquired at timestamp infinity? the read latch at t0 would not block out any writes.

**Comment by nvanbenschoten** [comment]
We consider a latch at timestamp zero to be non-MVCC, which is what I meant by that:

https://github.com/cockroachdb/cockroach/blob/cee171c75f88ccae19834c4320511beffe7d87dc/pkg/storage/spanlatch/manager.go#L311-L313
