### ISSUE TITLE
sql: Always set column Mutations (schema change) to nullable in ImmutableTableDescriptor

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#32586]
After introducing ImmutableTableDescriptor as a new type, all columns that are in the mutations list can be marked as nullable in the ImmutableTableDescriptor. This is accurate in accepting that the column is still being backfilled and can be nullable.

If a column is not public it cannot be provided with a value from the outside. However internally computed values coming from default expression/computed column can be evaluated to NULL and those need to be rejected. I think we should just get around this by marking these expressions as non-nullable.

**Comment by knz** [comment]
See my comments in https://github.com/cockroachdb/cockroach/pull/32585#discussion_r236168216 - I believe we should not allow INSERT and other mutations statements to insert NULLs in a column that was *declared* during CREATE as non-NULLable.
