### ISSUE TITLE
roachtest: port sqlsmith to go

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#32595]
sqlsmith routinely finds issues in Cockroach, but there are a number of features of Cockroach that it doesn't test (anything not present in Postgres, for example). We should extend it to have broader coverage of Cockroach's features.

In particular, sqlsmith doesn't generate a schema. It would be helpful if it did so that it doesn't just run queries against virtual tables.

**Comment by vivekmenezes** [comment]
One goal here could be to unskip the nightly sqlsmith tests; they are currently skipped.

@BramGruneir fyi

**Comment by justinj** [comment]
After spending some time trying to understand the sqlsmith codebase, I decided that it would be most productive for me this week, and as a tool for us going forward, to port it to Go and add some features it doesn't support. This has revealed a number of bugs already, namely #32725, #32723, and #32682. I'm confident that we'll only find more the more SQL features we add.

I have a separate repo with the code in it, but it's my hope to eventually fold it into the Cockroach repo so it can make more direct use of the Cockroach AST nodes and surrounding infrastructure. In particular Jordan has a Go implementation of a random schema generator that I think this should eventually be a part of. The code is [here](https://gitlab.com/jaffray/sqlsmith-go), but it's pretty hacky at the moment and will definitely need a cleanup pass before being moved somewhere more official.

**Comment by justinj** [comment]
This ended up in a place where it found a bunch of bugs, but I've got a couple other things on my plate right now taking priority and so I'm going to work on this more when I find some free time. I'll leave this issue open until the work of folding it into the cockroach repo is done.
