### ISSUE TITLE
roachprod: missing flags if the aws tool is not configured

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#32607]
If the aws tool doesn't exist, and moreover if it exists but it isn't properly configured, we have code that makes the aws flags magically disappear. This has given me grief - options disappearing is terrible UI :)

I wanted to turn everything into a runtime check, but I ran into this mysterious note which scared me, so I'd like to delegate to the expert.
https://github.com/cockroachdb/cockroach/blob/a7e13e8fdb1db2094e17c13d25215fb7b711313e/pkg/cmd/roachprod/vm/aws/aws.go#L57-L60

**Comment by bobvawter** [comment]
@andreimatei What behavior do you want if you specify an AWS-specific flag, but roachprod doesn't have AWS access?

Adding some kind of `aws.NoOpProvider` which always injects the Flags a-la https://github.com/cockroachdb/cockroach/blob/a7e13e8fdb1db2094e17c13d25215fb7b711313e/pkg/cmd/roachprod/vm/aws/aws.go#L305-L308, and stubs out the rest of the `vm.Provider` interface ought to do the trick if you just want roachprod to always accept flags for cloud providers that are unavailable.

**Comment by andreimatei** [comment]
The behavior I want is a runtime error saying that I need to setup whatever if the roachprod command I'm running needs to use the `aws` tool.

**Comment by knz** [comment]
@andreimatei arguably you could issue the PR yourself:

```
fmt.Fprintf(os.Stderr, "please setup AWS")
os.Exit(1)
```

**Comment by andreimatei** [comment]
@knz obviously the question is where to put those lines. I only want the thing to fail if I'm actually trying to use aws. Bob's PR is more involved.
