### ISSUE TITLE
backupccl: support backing up data to Baidu Object Storage

### ISSUE THREAD

**Issue by yangliang9004** [cockroachdb/cockroach#32626]
**Is your feature request related to a problem? Please describe.**
Now , CockroachDB can only back up data to Amazon S3, Azure, Google Cloud, HTTP, NFS/Local, S3-compatible services. But in China, most users will choose Baidu Cloud, Ali Cloud or Tencent Cloud to backup data. so  CockroachDB should really support Chinese cloud storage services.

**Describe the solution you'd like**
I suggest that CockroachDB should support BOS(Baidu Object Storage), which is suppled by Baidu Cloud and suitable for storing back up data ,similar to Amazon S3. BOS has also supplied GO SDK for developers on Github:
https://github.com/baidubce/bce-sdk-go. If Cockroach Labs add github.com/baidubce/bce-sdk-go to cockroachdb/vendored, it will be easy to  implement. 

**Describe alternatives you've considered**

**Additional context**

**Comment by knz** [comment]
@rolandcrosby for triage and prioritization
