### ISSUE TITLE
sql: panic: Non-nullable column "jobs:status" with no value! Index scanned was "primary" with the index key columns (id) and the values (403246710670524417)

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#32665]
Discovered by @ajwerner. Perhaps related to or dupe of https://github.com/cockroachdb/cockroach/issues/32530?

build:               CCL v2.2.0-alpha.20181119-259-g1bcb46e @ 2018/11/25 01:06:26 (go1.10.3)

panic: Non-nullable column "jobs:status" with no value! Index scanned was "primary" with the index key columns (id) and the values (403246710670524417)

goroutine 1683060 [running]:
github.com/cockroachdb/cockroach/pkg/sql/row.(*Fetcher).finalizeRow(0xc429681c98, 0x32948a0, 0xc453359140)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/row/fetcher.go:1301 +0x9ea
github.com/cockroachdb/cockroach/pkg/sql/row.(*Fetcher).NextRow(0xc429681c98, 0x32948a0, 0xc453359140, 0xc453359170, 0x1, 0x1, 0x0, 0x10001, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/row/fetcher.go:1046 +0x183
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*rowFetcherWrapper).Next(0xc42e3d99a0, 0x32948a0, 0xc453359140, 0xc44948ac60, 0xc43e0e7890)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/tablereader.go:157 +0x4a
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*tableReader).Next(0xc429681800, 0x0, 0x32948a0, 0xc453359140, 0xc45c5ad780)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/tablereader.go:272 +0x4e
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.Run(0x32947e0, 0xc45c5ad780, 0x329fb60, 0xc429681800, 0x3286d20, 0xc4485e3180)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go:174 +0x35
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).Run(0xc429681800, 0x32947e0, 0xc45c5ad780, 0xc420a5e508)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:768 +0x98
created by github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).startInternal
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:581 +0x308

**Comment by vivekmenezes** [comment]
closing this issue as a duplicate
