### ISSUE TITLE
sql: large numeric constants can cause extremely high memory usage

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#32682]
Running:
```
select 100 << (87 << 41)
```
makes my Cockroach's memory usage balloon:
![image](https://user-images.githubusercontent.com/409075/49171003-8072d800-f30b-11e8-9122-fbcabc52691d.png)

Oddly, this doesn't seem to reproduce for @RaduBerinde, possibly because he's on Linux and I'm on macOS?

Assigning to @knz for triage.

**Comment by knz** [comment]
yeah I confirm it breaks on me too.

I believe it's indeed a difference between macOS/BSD and Linux. The Go library for constants will issue a malloc() for the (expected, gigantic) result slice. Linux will serve the malloc() without blinking (and not initializing anything) whereas macOS/BSD will actually go and allocate the memory.

In any case it's annoying. @nvanbenschoten do you confirm that last time you looked at this, the operators on go constants are constant-folded by the go library? Do you think this is a signal that we should be re-implementing this ourselves?

**Comment by knz** [comment]
@mjibson is this something that you'd have interest to investigate?

**Comment by mjibson** [comment]
One linux user reports this returns 0 in < 2ms. For me (also on linux) it crashes immediately with `fatal error: runtime: out of memory`. So that makes three different behaviors. I'm happy to look into this.

**Comment by nvanbenschoten** [comment]
> do you confirm that last time you looked at this, the operators on go constants are constant-folded by the go library? Do you think this is a signal that we should be re-implementing this ourselves?

I don't remember much about looking at this in the past. The operators are constant-folded by the go library, so if we need to introduce some policy about computation cost, we'll probably need to replace it. That's not a bad idea on its own.

**Comment by RaduBerinde** [comment]
For smaller exponents I also run out of memory.
`select 100 << 4399000000000` returns 0 immediately while `select 100 << 4397000000000` crashes.

**Comment by RaduBerinde** [comment]
This is the cutoff:
```
root@127.63.2.187:38081/defaultdb> select 100 << 4398046510720;
  ?column?  
+----------+
         0  
(1 row)

Time: 277.823µs

root@127.63.2.187:38081/defaultdb> select 100 << 4398046510719;
runtime: out of memory: cannot allocate 549755813888-byte block (23003136 in use)
fatal error: out of memory
```
It's the same with `1 <<` as well..

**Comment by knz** [comment]
What are the limits in postgres?

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by RaduBerinde** [comment]
Go also checks for too many digits after each operation (at least multiplications).

**Comment by mjibson** [comment]
postgres:

```
# select 100 << (87 << 41);
 ?column? 
----------
      100
```

wat

**Comment by mjibson** [comment]
Oh yeah: postgres's shift operators wrap on the bit size of the inderlying int: https://www.cockroachlabs.com/docs/v2.1/porting-postgres.html#shift-argument-modulo

**Comment by knz** [comment]
> Oh yeah: postgres's shift operators wrap on the bit size of the inderlying int: cockroachlabs.com/docs/v2.1/porting-postgres.html#shift-argument-modulo 

I propose we produce an error (with teleemetry) for values that would cause postgres to overflow/wrap. No need to be more generous than postgres (and use more memory) but also no need to add silently weird behavior until we have evidence that users need it.
