### ISSUE TITLE
Support ARM builds for AWS ARM EC2

### ISSUE THREAD

**Issue by richardanaya** [cockroachdb/cockroach#32689]
The cost savings of Cockroach are already pretty high, would would make it even higher if it could run on even cheaper infrastructure like AWS's ARM EC2 instances.

Solution: Support builds of cockroach DB compiled for ARM and their distribution on the website.

https://aws.amazon.com/blogs/aws/new-ec2-instances-a1-powered-by-arm-based-aws-graviton-processors/

Epic CRDB-1463

Jira issue: CRDB-4721

**Comment by vielmetti** [comment]
Previously #14405 - progress has been made, would be good to see this finished up.

**Comment by charsleysa** [comment]
AWS have recently announced that the next generation of General Purpose (M6), Compute Optimized (C6), and Memory Optimized (R6) will have ARM-based variants (eg. M6g, C6g, R6g) with up to 7x the performance compared to their current generation counterparts. This should be looked at more seriously as ARM-based servers are becoming more commonplace.

https://aws.amazon.com/blogs/aws/coming-soon-graviton2-powered-general-purpose-compute-optimized-memory-optimized-ec2-instances/

**Comment by lancel66** [comment]
A large CockroachDB customer has just requested support for ARM in AWS. They are moving other platforms over to ARM and have reported a very significant cost savings. Are there plans to support this platform in the works?

**Comment by christoofar** [comment]
Here.  I made a version of v21.2.2 for ARM64

It should run on an M1 Mac.  

https://hub.docker.com/layers/christoofar/cockroachdb-arm64/21.2.2/images/sha256-f6d9acfffb1b1e3cb251b0c70ba1f629033612379d2adcd32a00111c1cb896a9?context=explore

I also made an all-in-one Dockerfile with all the superdeps, takes several hours to run on a Rock64 but it will yield the same bits:  https://github.com/christoofar/cockroachdb-arm64

You can install DockerCE and fire it up in Docker Swarm or k8s and should work fine or just grab the ARM64 image from Docker Hub.

**Comment by jlinder** [comment]
Cross linking [the latest update](https://github.com/cockroachdb/cockroach/issues/60778#issuecomment-1201704432) here.

**Comment by kenliu-crl** [comment]
Hi. We are posting updates on ARM64 support to these other active issues. 

- https://github.com/cockroachdb/cockroach/issues/60778
- https://github.com/cockroachdb/cockroach/issues/32689
- https://github.com/cockroachdb/cockroach/issues/68648
- https://github.com/cockroachdb/cockroach/issues/58676

[This is the latest update](https://github.com/cockroachdb/cockroach/issues/60778#issuecomment-1201704432).

**Comment by jlinder** [comment]
Hi. We are now publishing _experimental_ Linux ARM64 binaries for the v22.2 release series from v22.2.0-alpha.1 forward. See our [releases page](https://www.cockroachlabs.com/docs/releases/index.html) for download links.

Note: _Experimental_ binaries allow you to deploy CockroachDB on architectures that are not yet qualified for production use. We do not have a timeline for when our Linux ARM64 binaries will be qualified for production use.
