### ISSUE TITLE
sentry: conn_executor.go:639: panic while executing 1 statements: SELECT _._ AS _, _._ AS _, _._ AS _, CAST(COALESCE(_._, _._) AS STRING[]) AS _, CASE WHEN CASE WHEN (SELECT _ FROM _._ LIMIT _ OFFSET _) @> json_agg(CAST(_._ AS OID)) OVER (PARTITION BY _._ ORDER BY _._, _._, _._) THEN min(CAST((SELECT _ FROM _._ LIMIT _ OFFSET _) AS FLOAT8)) OVER (PARTITION BY _._, _._, _._ ORDER BY _._, _._) ELSE min(CAST((SELECT _ FROM _._ LIMIT _ OFFSET _) AS FLOAT8)) OVER (PARTITION BY _._, _._, _._ ORDER BY _._, _._) END IS NOT DISTINCT FROM CAST(_ AS FLOAT8) THEN _._ ELSE [...]: caused by <redacted>

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#32702]
https://sentry.io/cockroach-labs/cockroachdb/issues/783656538/?referrer=webhooks_plugin

conn_executor.go:639: panic while executing 1 statements: SELECT _._ AS _, _._ AS _, _._ AS _, CAST(COALESCE(_._, _._) AS STRING[]) AS _, CASE WHEN CASE WHEN (SELECT _ FROM _._ LIMIT _ OFFSET _) @> json_agg(CAST(_._ AS OID)) OVER (PARTITION BY _._ ORDER BY _._, _._, _._) THEN min(CAST((SELECT _ FROM _._ LIMIT _ OFFSET _) AS FLOAT8)) OVER (PARTITION BY _._, _._, _._ ORDER BY _._, _._) ELSE min(CAST((SELECT _ FROM _._ LIMIT _ OFFSET _) AS FLOAT8)) OVER (PARTITION BY _._, _._, _._ ORDER BY _._, _._) END IS NOT DISTINCT FROM CAST(_ AS FLOAT8) THEN _._ ELSE [...]: caused by <redacted>

github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1

> stacktrace: {u'frames': [{u'function': u'func4', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl', u'in_app': True, u'lineno': 309, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go'}, {u'function': u'ServeConn', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*Server)', u'in_app': True, u'lineno': 389, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go'}, {u'function': u'run', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'in_app': True, u'lineno': 1112, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go'}, {u'function': u'execStmt', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'in_app': True, u'lineno': 96, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go'}, {u'function': u'execStmtInOpenState', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'in_app': True, u'lineno': 402, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go'}, {u'function': u'dispatchToExecutionEngine', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'in_app': True, u'lineno': 824, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go'}, {u'function': u'execWithDistSQLEngine', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'in_app': True, u'lineno': 982, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go'}, {u'function': u'PlanAndRun', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner)', u'in_app': True, u'lineno': 746, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go'}, {u'function': u'Run', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner)', u'in_app': True, u'lineno': 253, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go'}, {u'function': u'StartSync', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow)', u'in_app': True, u'lineno': 602, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go'}, {u'function': u'Run', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase)', u'in_app': True, u'lineno': 731, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go'}, {u'function': u'Run', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun', u'in_app': True, u'lineno': 170, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go'}, {u'function': u'Next', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/windower.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*windower)', u'in_app': True, u'lineno': 267, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/windower.go'}, {u'function': u'accumulateRows', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/windower.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*windower)', u'in_app': True, u'lineno': 309, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/windower.go'}, {u'function': u'Next', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/windower.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*windower)', u'in_app': True, u'lineno': 269, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/windower.go'}, {u'function': u'emitRow', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/windower.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*windower)', u'in_app': True, u'lineno': 399, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/windower.go'}, {u'function': u'computeWindowFunctions', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/windower.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*windower)', u'in_app': True, u'lineno': 638, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/windower.go'}, {u'function': u'Compute', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/builtins/window_builtins.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/sem/builtins.(*framableAggregateWindowFunc)', u'in_app': True, u'lineno': 264, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/sem/builtins/window_builtins.go'}, {u'function': u'Compute', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/builtins/window_builtins.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/sem/builtins.(*aggregateWindowFunc)', u'in_app': True, u'lineno': 213, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/sem/builtins/window_builtins.go'}, {u'function': u'Add', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/builtins/aggregate_builtins.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/sem/builtins.(*jsonAggregate)', u'in_app': True, u'lineno': 1914, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/sem/builtins/aggregate_builtins.go'}, {u'function': u'Add', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/util/json/json.go', u'module': u'github.com/cockroachdb/cockroach/pkg/util/json.(*ArrayBuilderWithCounter)', u'in_app': True, u'lineno': 234, u'filename': u'github.com/cockroachdb/cockroach/pkg/util/json/json.go'}, {u'function': u'Add', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/util/json/json.go', u'module': u'github.com/cockroachdb/cockroach/pkg/util/json.(*ArrayBuilder)', u'in_app': True, u'lineno': 201, u'filename': u'github.com/cockroachdb/cockroach/pkg/util/json/json.go'}, {u'function': u'gopanic', u'abs_path': u'/usr/local/go/src/runtime/panic.go', u'module': u'runtime', u'in_app': False, u'lineno': 502, u'filename': u'runtime/panic.go'}, {u'function': u'call32', u'abs_path': u'/usr/local/go/src/runtime/asm_amd64.s', u'module': u'runtime', u'in_app': False, u'lineno': 573, u'filename': u'runtime/asm_amd64.s'}, {u'function': u'func1', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn', u'in_app': True, u'lineno': 387, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go'}]}
type: *log.safeError
value: conn_executor.go:639: panic while executing 1 statements: SELECT _._ AS _, _._ AS _, _._ AS _, CAST(COALESCE(_._, _._) AS STRING[]) AS _, CASE WHEN CASE WHEN (SELECT _ FROM _._ LIMIT _ OFFSET _) @> json_agg(CAST(_._ AS OID)) OVER (PARTITION BY _._ ORDER BY _._, _._, _._) THEN min(CAST((SELECT _ FROM _._ LIMIT _ OFFSET _) AS FLOAT8)) OVER (PARTITION BY _._, _._, _._ ORDER BY _._, _._) ELSE min(CAST((SELECT _ FROM _._ LIMIT _ OFFSET _) AS FLOAT8)) OVER (PARTITION BY _._, _._, _._ ORDER BY _._, _._) END IS NOT DISTINCT FROM CAST(_ AS FLOAT8) THEN _._ ELSE [...]: caused by <redacted>

**Comment by jordanlewis** [comment]
```
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go in func1 at line 387
Called from: runtime/asm_amd64.s in call32
github.com/cockroachdb/cockroach/pkg/util/json/json.go in Add at line 201
github.com/cockroachdb/cockroach/pkg/util/json/json.go in Add at line 234
github.com/cockroachdb/cockroach/pkg/sql/sem/builtins/aggregate_builtins.go in Add at line 1914
github.com/cockroachdb/cockroach/pkg/sql/sem/builtins/window_builtins.go in Compute at line 213
github.com/cockroachdb/cockroach/pkg/sql/sem/builtins/window_builtins.go in Compute at line 264
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/windower.go in computeWindowFunctions at line 638
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/windower.go in emitRow at line 399
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/windower.go in Next at line 269
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/windower.go in accumulateRows at line 309
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/windower.go in Next at line 267
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go in Run at line 170
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go in Run at line 731
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go in StartSync at line 602
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go in Run at line 253
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go in PlanAndRun at line 746
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go in execWithDistSQLEngine at line 982
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go in dispatchToExecutionEngine at line 824
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go in execStmtInOpenState at line 402
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go in execStmt at line 96
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go in run at line 1112
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go in ServeConn at line 389
github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go in func4 at line 309
```

Caused by the explicit panic:

```
// Add appends JSON to the sequence.
func (b *ArrayBuilder) Add(j JSON) {
	if b.jsons == nil {
		panic(msgModifyAfterBuild)
	}
	b.jsons = append(b.jsons, j)
}
```

@justinj it you?
