### ISSUE TITLE
sentry: conn_executor.go:639: panic while executing 1 statements: SELECT _._ AS _, _._ AS _ FROM (SELECT _._ AS _, _._ AS _ FROM _._ AS _ WHERE setval(CAST(_._ AS STRING), CAST((SELECT _ FROM _._ LIMIT _ OFFSET _) AS INT8)) >= crdb_internal.force_panic(CAST(_._ AS STRING)) LIMIT _) AS _ RIGHT JOIN (SELECT _._ AS _, _._ AS _ FROM _._ AS _ WHERE (SELECT _ FROM _._ LIMIT _ OFFSET _) >= CAST(_ AS DATE)) AS _ RIGHT JOIN _._ AS _ ON (current_date() IS NOT DISTINCT FROM current_date()) ON ((_._ > CAST(_ AS DECIMAL)) OR (_._ IS NOT _)) WHERE (now() < CASE WHEN CAST(_  [...]: caused by <redacted>

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#32703]
https://sentry.io/cockroach-labs/cockroachdb/issues/783664505/?referrer=webhooks_plugin

conn_executor.go:639: panic while executing 1 statements: SELECT _._ AS _, _._ AS _ FROM (SELECT _._ AS _, _._ AS _ FROM _._ AS _ WHERE setval(CAST(_._ AS STRING), CAST((SELECT _ FROM _._ LIMIT _ OFFSET _) AS INT8)) >= crdb_internal.force_panic(CAST(_._ AS STRING)) LIMIT _) AS _ RIGHT JOIN (SELECT _._ AS _, _._ AS _ FROM _._ AS _ WHERE (SELECT _ FROM _._ LIMIT _ OFFSET _) >= CAST(_ AS DATE)) AS _ RIGHT JOIN _._ AS _ ON (current_date() IS NOT DISTINCT FROM current_date()) ON ((_._ > CAST(_ AS DECIMAL)) OR (_._ IS NOT _)) WHERE (now() < CASE WHEN CAST(_  [...]: caused by <redacted>

github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1

> stacktrace: {u'frames': [{u'function': u'func4', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl', u'in_app': True, u'lineno': 309, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go'}, {u'function': u'ServeConn', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*Server)', u'in_app': True, u'lineno': 389, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go'}, {u'function': u'run', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'in_app': True, u'lineno': 1112, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go'}, {u'function': u'execStmt', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'in_app': True, u'lineno': 96, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go'}, {u'function': u'execStmtInOpenState', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'in_app': True, u'lineno': 402, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go'}, {u'function': u'dispatchToExecutionEngine', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'in_app': True, u'lineno': 824, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go'}, {u'function': u'execWithDistSQLEngine', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'in_app': True, u'lineno': 982, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go'}, {u'function': u'PlanAndRun', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner)', u'in_app': True, u'lineno': 746, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go'}, {u'function': u'Run', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner)', u'in_app': True, u'lineno': 253, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go'}, {u'function': u'StartSync', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow)', u'in_app': True, u'lineno': 602, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go'}, {u'function': u'Run', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase)', u'in_app': True, u'lineno': 731, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go'}, {u'function': u'Run', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun', u'in_app': True, u'lineno': 170, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go'}, {u'function': u'Next', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/hashjoiner.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*hashJoiner)', u'in_app': True, u'lineno': 243, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/hashjoiner.go'}, {u'function': u'build', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/hashjoiner.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*hashJoiner)', u'in_app': True, u'lineno': 314, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/hashjoiner.go'}, {u'function': u'receiveNext', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/hashjoiner.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*hashJoiner)', u'in_app': True, u'lineno': 647, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/hashjoiner.go'}, {u'function': u'Next', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/noop.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*noopProcessor)', u'in_app': True, u'lineno': 65, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/noop.go'}, {u'function': u'Next', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource)', u'in_app': True, u'lineno': 218, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go'}, {u'function': u'ProcessRowHelper', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase)', u'in_app': True, u'lineno': 708, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go'}, {u'function': u'ProcessRow', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcOutputHelper)', u'in_app': True, u'lineno': 331, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go'}, {u'function': u'evalFilter', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/expr.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*exprHelper)', u'in_app': True, u'lineno': 172, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/expr.go'}, {u'function': u'RunFilter', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/expr_filter.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/sqlbase', u'in_app': True, u'lineno': 26, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/sqlbase/expr_filter.go'}, {u'function': u'Eval', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*ComparisonExpr)', u'in_app': True, u'lineno': 3335, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go'}, {u'function': u'Eval', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FuncExpr)', u'in_app': True, u'lineno': 3408, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go'}, {u'function': u'func208', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/builtins/builtins.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/sem/builtins.glob.', u'in_app': True, u'lineno': 2816, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/sem/builtins/builtins.go'}, {u'function': u'gopanic', u'abs_path': u'/usr/local/go/src/runtime/panic.go', u'module': u'runtime', u'in_app': False, u'lineno': 502, u'filename': u'runtime/panic.go'}, {u'function': u'call32', u'abs_path': u'/usr/local/go/src/runtime/asm_amd64.s', u'module': u'runtime', u'in_app': False, u'lineno': 573, u'filename': u'runtime/asm_amd64.s'}, {u'function': u'func1', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn', u'in_app': True, u'lineno': 387, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go'}]}
type: *log.safeError
value: conn_executor.go:639: panic while executing 1 statements: SELECT _._ AS _, _._ AS _ FROM (SELECT _._ AS _, _._ AS _ FROM _._ AS _ WHERE setval(CAST(_._ AS STRING), CAST((SELECT _ FROM _._ LIMIT _ OFFSET _) AS INT8)) >= crdb_internal.force_panic(CAST(_._ AS STRING)) LIMIT _) AS _ RIGHT JOIN (SELECT _._ AS _, _._ AS _ FROM _._ AS _ WHERE (SELECT _ FROM _._ LIMIT _ OFFSET _) >= CAST(_ AS DATE)) AS _ RIGHT JOIN _._ AS _ ON (current_date() IS NOT DISTINCT FROM current_date()) ON ((_._ > CAST(_ AS DECIMAL)) OR (_._ IS NOT _)) WHERE (now() < CASE WHEN CAST(_  [...]: caused by <redacted>

**Comment by jordanlewis** [comment]
Caused by `force_panic` - this kind of smells like sqlsmith / @justinj?
