### ISSUE TITLE
distsql: array of tuples cannot be sent over the wire

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#32715]
when the gateway node is the leaseholder for x:
```
root@localhost:26259/defaultdb> select array[(a, b)] from x;
    array
+-----------+
  {"(1,2)"}
(1 row)

Time: 14.924ms
```

when it isn’t
```
root@localhost:26258/defaultdb> select array[(a, b)] from x;
pq: Don't know encoding type for tuple{int, int}
```

The reason is that arrays of tuples don't have an encoding, and so can't be sent over the wire. Now that tuples have an encoding (?) it should be possible to add one.

Unsure if this falls under sql or execution, I think encoding of values falls under sql, but the problem only manifests in execution. cc @knz @jordanlewis

**Comment by knz** [comment]
we can provide a value encoding for these, but I suppose a key encoding is not possible.

**Comment by knz** [comment]
Still relevant - PR #63996

**Comment by rytaft** [comment]
@rafiss moving this to SQL Experience since you've got an open PR.
