### ISSUE TITLE
kv: (*DistSender).RangeFeed stack depth

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#32721]
I was reading the `(*DistSender).RangeFeed` code and realized that `divideAndSendRangeFeedToRanges` recursively calls itself via `partialRangeFeed` when a split happens. I haven't tested this, but I think if one were to call RangeFeed on some span and repeatedly split it, then we'd eventually exceed the maximum stack depth and panic. A repro might need a bit of time in between splits to make sure the RangeFeed had to handle the splits one by one.

I think this is fixable by handing some of the errors at a higher level: https://github.com/cockroachdb/cockroach/blob/master/pkg/kv/dist_sender_rangefeed.go#L124-L144

Jira issue: CRDB-4718

**Comment by tbg** [comment]
@andreimatei can you help @danhhz out with this? I don't think this is time critical, but we'll want to investigate well before the release.

The items to do here are

1. investigate whether #34108 really did fix the problem
2. decide whether writing the test is worth our fuel and if so, write it

**Comment by andreimatei** [comment]
Looks to me like #34108 indeed solved it because the code is not recursive any more `partialRangeFeed` no longer calls `divideAndSendRangeFeedToRanges`, instead the feeds for all sub-ranges are coordinated at the top level. This structure seems sane to me.

So as far as recursivity is concerned, I don't think there's any test to be written. I assume we already have tests covering splits; I haven't looked. I could write a more aggressive one if we don't have enough. Dan?

**Comment by danhhz** [comment]
`DistSender.RangeFeed` is definitely under-tested in the presence of splits. On friday, I just found a bug in `(DistSender) divideAndSendRangeFeedToRanges` (1)  where we need to do the same nextRS trick as `(DistSender).divideAndSendBatchToRanges` (2), but haven't gotten the chance to send out a fix yet. I was imagining a regression test in the rangefeed or kv package that sets up a rangefeed using DistSender.RangeFeed, splits it a bunch, adding data after each split, and makes sure everything works as expected. If you could write that test, it'd be much appreciated.

(1): https://github.com/cockroachdb/cockroach/blob/af7425acc39800287b086452aac4816a4de8820d/pkg/kv/dist_sender_rangefeed.go#L83-L110
(2): https://github.com/cockroachdb/cockroach/blob/af7425acc39800287b086452aac4816a4de8820d/pkg/kv/dist_sender.go#L947

**Comment by andreimatei** [comment]
> I was imagining a regression test in the rangefeed or kv package that sets up a rangefeed using DistSender.RangeFeed, splits it a bunch, adding data after each split, and makes sure everything works as expected. If you could write that test, it'd be much appreciated.

Let me see what I can do.

**Comment by miretskiy** [comment]
Super stale.
