### ISSUE TITLE
storage: TestStoreSplitFailsAfterMaxRetries takes 7s

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#32722]
Seems that it's too long, but I haven't dug into it; could be ok-ish.
I'm skipping the test on `testshort` in #32696.

**Comment by nvanbenschoten** [comment]
The test expects 11 retries with exponential back off between them, so that explains the 7 seconds. It's not great that it takes so long though.

**Comment by nvanbenschoten** [comment]
We could fix this by adding an `adminSplitRetries retry.Options` field to `StoreTestingKnobs`, but that does strike me as being heavyweight for this very specific test. What do you think @andreimatei?

**Comment by andreimatei** [comment]
No opinion on whether a knob is worth it. I don't see why it wouldn't be nice to have, but I don't know if I'd personally put in the effort.
As far as I'm concerned, feel free to close this (I wouldn't have opened it if you hadn't asked for it). Bonus points if you add these findings to the test comment in lieu of the link to this issue (unless you add the knob).
