### ISSUE TITLE
sql: implement chunking of schema change backfill operations

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#3274]
The schema change backfill operations update the entire column/index in one transaction. This is going to be expensive in terms of resources (memory and cpu) and can possibly cause contention on the reads. Change the backfill methods to update the column/index in chunks keeping track of the update key in the mutation.

**Comment by vivekmenezes** [comment]
Along with this fix it will be worth to developing an acceptance test for the online schema change mechanism. This might involve loading up a large table (more than a million rows), applying some insert/update/select load on the table, and running some schema changes, and eventually checking the correctness of the schema change as well as the performance of the operations.

**Comment by vivekmenezes** [comment]
I'm going to start working on this initially for the Add Index and column case.

**Comment by tamird** [comment]
What is the point of closing this in favour of #7115?
