### ISSUE TITLE
build: `make build` produces error when using go 1.8

### ISSUE THREAD

**Issue by zhengxiaochuan-3** [cockroachdb/cockroach#32766]
cockroachdb version : release-2.1

Linux node 3.10.0-514.21.1.ns7.019.jk.mips64el #1 SMP Tue Jul 18 14:20:21 CST 2017 mips64el mips64el mips64el GNU/Linux

centos 7.2

[root@node etc]# go version
go version go1.8.3 linux/mips64le

[root@node cockroach]# make build
Running make with -j4
GOPATH set to /root/go
(echo "// Code generated by goyacc. DO NOT EDIT."; \
 echo "// GENERATED FILE DO NOT EDIT"; \
 cat pkg/sql/parser/gen/sql.go.tmp | \
 sed -E 's/^const ([A-Z][_A-Z0-9]*) =.*$/const \1 = lex.\1/g') > pkg/sql/parser/sql.go.tmp || rm pkg/sql/parser/sql.go.tmp
mv -f pkg/sql/parser/sql.go.tmp pkg/sql/parser/sql.go
goimports -w pkg/sql/parser/sql.go
**sql-gen.y:62:1: expected 'IDENT', found 'func'
sql-gen.y:63:2: expected declaration, found 'return'
sql-gen.y:575:1: expected 'IDENT', found 'const'
yaccpar:11:1: expected 'IDENT', found 'type'
yaccpar:13:1: expected type, found 'type'
yaccpar:15:1: expected ';', found 'func'
yaccpar:16:2: expected declaration, found 'return'
make: *** [pkg/sql/parser/sql.go] Error 2
make: *** Deleting file `pkg/sql/parser/sql.go'**

**Comment by knz** [comment]
@zhengxiaochuan-3, thank you for your inquiry.

1) CockroachDB requires Go 1.11. You are using 1.8. You should update your Go version.

2) please read the contributor guide CONTRIBUTING.md for a list of build dependencies. There are other specific version requirements besides Go.

3) note that we have never tested CockroachDB on MIPS. We thus cannot guarantee that it will work well. However, we would love to hear more from your experiment -- what works, what does not work, how was your experience.

Thank you!

**Comment by knz** [comment]
Hi @zhengxiaochuan-3, since there is not much more we can do from our side on this issue, I will close it for the time being. 
Again I want to remind you we are interested to know your experience using CockroachDB on 64-bit MIPS, which we have never tried before. Feel free to open new issues on github if you encounter new problems.
Thank you

**Comment by zhengxiaochuan-3** [comment]
@knz 

I am still building cockroachdb on mips follow CONTRIBUTING.md , 
got another error , maybe the last one??   :(   

[root@localhost cockroach]# make build
Running make with -j4
GOPATH set to /root/go
go build -o cockroach -v  -tags ' make mips64el_neokylin_linux' -ldflags '-X github.com/cockroachdb/cockroach/pkg/build.typ=development -extldflags "" -X "github.com/cockroachdb/cockroach/pkg/build.tag=v2.1.1-134-g8d807ce-dirty" -X "github.com/cockroachdb/cockroach/pkg/build.rev=8d807ce49978c46ed4daa03e6dbca5b2b5acfcc1" -X "github.com/cockroachdb/cockroach/pkg/build.cgoTargetTriple=mips64el-neokylin-linux"   -X "github.com/cockroachdb/cockroach/pkg/build.utcTime=2018/12/06 06:36:55"' ./pkg/cmd/cockroach
github.com/cockroachdb/cockroach/vendor/github.com/knz/go-libedit/unix
**github.com/cockroachdb/cockroach/pkg/storage/engine
# github.com/cockroachdb/cockroach/pkg/storage/engine
slice.s: Assembler messages:
slice.s:1: Error: junk at end of line, first unrecognized character is `/'**
github.com/cockroachdb/cockroach/vendor/github.com/knz/go-libedit
make: *** [cockroach] error 2

**Comment by zhengxiaochuan-3** [comment]
It`s a empty file ....  , delete the node: // Empty assembly file to allow go:linkname to work.
