### ISSUE TITLE
Add a privilege for creating databases that can be granted to non-superusers

### ISSUE THREAD

**Issue by victorggsimida** [cockroachdb/cockroach#32765]
my question is easy.

i want to create a database with normal user?

and it turn out this error?

create database try;
pq: only superusers are allowed to CREATE DATABASE

how to change a user to be a superuser with community version ?  

Grant role can do that? but it is enterprise only. 

thank you

**Comment by lanzao** [comment]
seems only role or superusers can do that

**Comment by victorggsimida** [comment]
@lanzao  as a MySQL user.

when I face this problem, I think this is unbelievable.

Only if normal user with grant role command ,can create database.


But the grant role is enterprise.....  It means no way to solve this problem with community version

**Comment by tim-o** [comment]
@victorggsimida - I've changed this to an enhancement request. We have not yet implemented postgres's solution to this, `ALTER USER <> CREATEDB;` Until that's implemented, only the root user will be able to create databases in our Core version. We haven't received many requests to add this functionality, but our product team is tracking the feature potentially for 2.2.
