### ISSUE TITLE
Granting privileges only  on database or table seems doesn't make sense

### ISSUE THREAD

**Issue by lanzao** [cockroachdb/cockroach#32783]
When a user was only granted privileges on  tables（without granted on database）,he can't even see the database,  for example:

 `grant all on table mydb.* to testuser`；

'testuser' have privileges on table mydb.* but he has no privilege to see database `mydb`,so this privilege doesn't make sense.

On the other hand，if a user is only granted on database（without granted on any table）,he can't see any table nor create a new table.

My suggestion is that 
1. When a user have the privileges on a table, he was automatically granted 'SELECT' privilege on the corresponding database. 
2. When a user have privileges on a database, he have corresponding privileges on all tables under this database.

**Comment by ajwerner** [comment]
This is captured in https://github.com/cockroachdb/cockroach/issues/16790, closing as a duplicate.
