### ISSUE TITLE
make build error

### ISSUE THREAD

**Issue by zhaoyta** [cockroachdb/cockroach#3278]
root@dockertest:/home/work/cockroachdb/src/github.com/cockroachdb/cockroach# make build
github.com/agtorre/gocolorize                      f42b554bf7f0	[OK]
github.com/biogo/store                             3b4c041f52c2	[OK]
github.com/cockroachdb/c-lz4                       c40aaae2fc50	[OK]
github.com/cockroachdb/c-protobuf                  6a18bfcdd516	[OK]
github.com/cockroachdb/c-rocksdb                   bf15ead80bdc	[OK]
github.com/cockroachdb/c-snappy                    5c6d0932e0ad	[OK]
github.com/cockroachdb/yacc                        443154b1852a	[OK]
github.com/coreos/etcd                             cf2d20c5c99e	[OK]
github.com/cpuguy83/go-md2man                      71acacd42f85	[OK]
# cd /home/work/cockroachdb/src/github.com/docker/docker; git pull --ff-only
error: unable to resolve reference refs/remotes/origin/release/v1.9: Not a directory
From https://github.com/docker/docker
 ! [new branch]      release/v1.9 -> origin/release/v1.9  (unable to update local ref)
error: some local refs could not be updated; try running
 'git remote prune origin' to remove any old, conflicting branches
exit status 1
go build -tags ''  -ldflags '-X "github.com/cockroachdb/cockroach/util.buildTag=alpha-6160-g5fa14d1" -X "github.com/cockroachdb/cockroach/util.buildTime=2015/12/02 09:31:58" -X "github.com/cockroachdb/cockroach/util.buildDeps=github.com/biogo/store:3b4c041f52c224ee4a44f5c8b150d003a40643a0 github.com/cockroachdb/c-lz4:c40aaae2fc50293eb8750b34632bc3efe813e23f github.com/cockroachdb/cockroach:5fa14d11c4d46f8e4445b7ef57ba12a81533ae45 github.com/cockroachdb/c-protobuf:6a18bfcdd5169966cd1235edb71d749c950216e8 github.com/cockroachdb/c-rocksdb:bf15ead80bdc205a19b3d33415b23c156a3cf371 github.com/cockroachdb/c-snappy:5c6d0932e0adaffce4bfca7bdf2ac37f79952ccf github.com/coreos/etcd:cf2d20c5c99ef5ef12bca87b06d9eff8f9fdacbd github.com/cpuguy83/go-md2man:71acacd42f85e5e82f70a55327789582a5200a90 github.com/elazarl/go-bindata-assetfs:d5cac425555ca5cf00694df246e04f05e6a55150 github.com/gogo/protobuf:d3235f01ecae4901dd9f7ea6af57a352c0189deb github.com/google/btree:cc6329d4279e3f025a53a83c397d2339b5705c45 github.com/inconshreveable/mousetrap:76626ae9c91c4f2a10f34cad8ce83ea42c93bb75 github.com/julienschmidt/httprouter:77a895ad01ebc98a4dc95d8355bc825ce80a56f6 github.com/lib/pq:11fc39a580a008f1f39bb3d11d984fb34ed778d9 github.com/montanaflynn/stats:b036e5fbfe87f3ad9cef6e236e81e1973aeb4a1d github.com/olekukonko/tablewriter:a5eefc286b03d5560735698ef36c83728a6ae560 github.com/peterh/liner:4d47685ab2fd2dbb46c66b831344d558bc4be5b9 github.com/russross/blackfriday:300106c228d52c8941d4b3de6054a6062a86dda3 github.com/shurcooL/sanitized_anchor_name:10ef21a441db47d8b13ebcc5fd2310f636973c77 github.com/spf13/cobra:6c0cb34745aa37492239084a1ac4b45630084a09 github.com/spf13/pflag:08b1a584251b5b62f458943640fc8ebd4d50aaa5 golang.org/x/crypto:346896d57731cb5670b36c6178fc5519f3225980 golang.org/x/net:1d9fd3b8333e891c0e7353e1adcfe8a612573033 golang.org/x/text:da608dee4b67711ed1ba96d33dceaa04c5cc9397 gopkg.in/yaml.v1:9f9df34309c04878acc86042b16630b0f696e1de"' -v -i -o cockroach
github.com/cockroachdb/cockroach/rpc/codec
# github.com/cockroachdb/cockroach/rpc/codec
rpc/codec/conn.go:104: c.r.Discard undefined (type *bufio.Reader has no field or method Discard)
make: *** [build] Error 2

**Comment by tamird** [comment]
can you try `/home/work/cockroachdb/src/github.com/docker/docker; git fetch; git reset --hard origin/master` and then try again?

**Comment by petermattis** [comment]
@zhaoyta Looks like you'll also have to upgrade to go 1.5.

**Comment by zhaoyta** [comment]
@petermattis  
version is 1.4.2 
root@dockertest:/home/work/cockroachdb/bin# go version
go version go1.4.2 linux/amd64

**Comment by tamird** [comment]
@zhaoyta cockroach requires go 1.5.1

**Comment by zhaoyta** [comment]
@tamird   docker dir is empty .there is another problem

root@dockertest:/home/work/cockroachdb/src/github.com/cockroachdb/cockroach# make build
github.com/agtorre/gocolorize                      f42b554bf7f0	[OK]
github.com/biogo/store                             3b4c041f52c2	[OK]
github.com/cockroachdb/c-lz4                       c40aaae2fc50	[OK]
github.com/cockroachdb/c-protobuf                  6a18bfcdd516	[OK]
github.com/cockroachdb/c-rocksdb                   bf15ead80bdc	[OK]
github.com/cockroachdb/c-snappy                    5c6d0932e0ad	[OK]
github.com/cockroachdb/yacc                        443154b1852a	[OK]
github.com/coreos/etcd                             cf2d20c5c99e	[OK]
github.com/cpuguy83/go-md2man                      71acacd42f85	[OK]
failed to get: github.com/docker/docker

> go get -v -d github.com/docker/docker
github.com/docker/docker (download)
# cd .; git clone https://github.com/docker/docker /home/work/cockroachdb/src/github.com/docker/docker
Cloning into '/home/work/cockroachdb/src/github.com/docker/docker'...
fatal: unable to access 'https://github.com/docker/docker/': Could not resolve host: github.com
package github.com/docker/docker: exit status 128
exit status 1

> import github.com/docker/docker
cannot find package "github.com/docker/docker" in any of:
	/home/work/gopkg/go/src/github.com/docker/docker (from $GOROOT)
	/home/work/cockroachdb/src/github.com/docker/docker (from $GOPATH)
go build -tags ''  -ldflags '-X "github.com/cockroachdb/cockroach/util.buildTag=alpha-6162-g2b0f52c" -X "github.com/cockroachdb/cockroach/util.buildTime=2015/12/03 01:18:43" -X "github.com/cockroachdb/cockroach/util.buildDeps=github.com/biogo/store:3b4c041f52c224ee4a44f5c8b150d003a40643a0 github.com/cockroachdb/c-lz4:c40aaae2fc50293eb8750b34632bc3efe813e23f github.com/cockroachdb/cockroach:2b0f52cbc7564a3650876c7d2e24291557264a4d github.com/cockroachdb/c-protobuf:6a18bfcdd5169966cd1235edb71d749c950216e8 github.com/cockroachdb/c-rocksdb:bf15ead80bdc205a19b3d33415b23c156a3cf371 github.com/cockroachdb/c-snappy:5c6d0932e0adaffce4bfca7bdf2ac37f79952ccf github.com/coreos/etcd:cf2d20c5c99ef5ef12bca87b06d9eff8f9fdacbd github.com/cpuguy83/go-md2man:71acacd42f85e5e82f70a55327789582a5200a90 github.com/elazarl/go-bindata-assetfs:d5cac425555ca5cf00694df246e04f05e6a55150 github.com/gogo/protobuf:d3235f01ecae4901dd9f7ea6af57a352c0189deb github.com/google/btree:cc6329d4279e3f025a53a83c397d2339b5705c45 github.com/inconshreveable/mousetrap:76626ae9c91c4f2a10f34cad8ce83ea42c93bb75 github.com/julienschmidt/httprouter:77a895ad01ebc98a4dc95d8355bc825ce80a56f6 github.com/lib/pq:11fc39a580a008f1f39bb3d11d984fb34ed778d9 github.com/montanaflynn/stats:b036e5fbfe87f3ad9cef6e236e81e1973aeb4a1d github.com/olekukonko/tablewriter:a5eefc286b03d5560735698ef36c83728a6ae560 github.com/peterh/liner:4d47685ab2fd2dbb46c66b831344d558bc4be5b9 github.com/russross/blackfriday:300106c228d52c8941d4b3de6054a6062a86dda3 github.com/shurcooL/sanitized_anchor_name:10ef21a441db47d8b13ebcc5fd2310f636973c77 github.com/spf13/cobra:6c0cb34745aa37492239084a1ac4b45630084a09 github.com/spf13/pflag:08b1a584251b5b62f458943640fc8ebd4d50aaa5 golang.org/x/crypto:346896d57731cb5670b36c6178fc5519f3225980 golang.org/x/net:1d9fd3b8333e891c0e7353e1adcfe8a612573033 golang.org/x/text:da608dee4b67711ed1ba96d33dceaa04c5cc9397 gopkg.in/yaml.v1:9f9df34309c04878acc86042b16630b0f696e1de"' -v -i -o cockroach
github.com/cockroachdb/cockroach/rpc/codec
# github.com/cockroachdb/cockroach/rpc/codec
rpc/codec/conn.go:104: c.r.Discard undefined (type *bufio.Reader has no field or method Discard)
github.com/cockroachdb/c-protobuf
github.com/cockroachdb/c-rocksdb

**Comment by tamird** [comment]
Looks like a network error?

**Comment by zhaoyta** [comment]
1, echo "192.30.252.131 github.com" >> /etc/hosts
2,echo "nameserver 8.8.8.8 8.8.4.4" >> /etc/resolv.conf
then ok 
thanks @tamird  @petermattis
