### ISSUE TITLE
CockroachDB 2.2 alpha never made it to docker hub

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/cockroach#32787]
The latest unstable in our [docker repo](https://hub.docker.com/r/cockroachdb/cockroach-unstable/tags/) points to 2.1-rc2 rather than the latest 2.2 alpha.

![image](https://user-images.githubusercontent.com/894257/49379352-ec26bd80-f6dc-11e8-9d2a-e512e33ed04c.png)

Can someone add this? It looks like we document this step in our release process https://github.com/cockroachdb/cockroach/wiki/Release-Process#check-the-docker-image

**Comment by a-robinson** [comment]
Huh, I don't see any suspicious recent changes to [the relevant script](https://github.com/cockroachdb/cockroach/blob/master/build/teamcity-publish-artifacts.sh), but I haven't looked at the other build-related changes yet.

I've pushed out this version, but am worried about future releases and whether they'll be pushed. Do any of the recent build changes that you've looked at come to mind as potentially having broken this, @benesch?

**Comment by benesch** [comment]
IIRC there was a bug in that script @BramGruneir had to work around on the fly. I think the result may have been manually built binaries? I'm not sure. @BramGruneir can you chime in?

**Comment by BramGruneir** [comment]
I don't think I did a release of the alpha to docker's unstable.
There is no mention of an unstable release in our release process. https://github.com/cockroachdb/cockroach/wiki/Release-Process
If there was, I would have done it.

All I can see is this:
> if you're doing an alpha or beta release, you want to check an "unstable" image:
> `docker run cockroachdb/cockroach-unstable:${TAG} version`

I think I ran this, but I'm unsure.

**Comment by benesch** [comment]
Yeah, it should happen automatically when the TC "publish release" build is triggered. But without your patch to the script the build would have failed after building binaries but before pushing to Docker Hub, resulting in, I think, exactly the symptoms here.

I guess what I'm asking is, after you fixed the script, did you re-run the publish release build? Or did you skip it because the binaries had been built successfully?

**Comment by BramGruneir** [comment]
Ah, no I did not.

**Comment by benesch** [comment]
I was hoping you'd say that! That means that we can close this issue out, since you already fixed the problem in https://github.com/cockroachdb/cockroach/commit/bf1c7c72bb568bf51a524429ed44169bd0203ebd.

**Comment by benesch** [comment]
(Thanks for reporting @nstewart.)
