### ISSUE TITLE
changefeedccl: include table and column comments as `doc` fields in generated Avro schemas

### ISSUE THREAD

**Issue by rolandcrosby** [cockroachdb/cockroach#32795]
A customer that extensively uses Avro internally mentioned an interesting use case for the `doc` fields in Avro schemas: adding tags to their data so downstream systems can understand things like which fields contain PII. They requested the ability to include metadata like this in the Avro schemas that CockroachDB generates.

At the moment, CockroachDB doesn't support arbitrary user-supplied metadata on tables and columns, but this may be about to change: in #32442, @hueypark has already built a nice extensible implementation of `COMMENT ON TABLE`. The first post on that issue indicates that he is also planning to add support for `COMMENT ON DATABASE` and `COMMENT ON COLUMN`. If this lands soon, we could plumb CockroachDB comments to Avro `doc` fields in our generated schemas, which would provide the requested functionality.

Jira issue: CRDB-4716

**Comment by miretskiy** [comment]
of bit of an exotic use case; it will be possible in the next release to define a user defined function
that returns whatever comments needed, and include that in the changefeed via cdc expressions.
