### ISSUE TITLE
storageccl: allow user to specify an HTTP proxy for cloud storage

### ISSUE THREAD

**Issue by rolandcrosby** [cockroachdb/cockroach#32803]
It's not uncommon for enterprises to have restrictions on which nodes can talk to which external servers, and to require whitelisted external traffic to be piped through an HTTP proxy. Right now, if you want to use an HTTP proxy, you have to proxy all CockroachDB traffic including traffic between nodes; this is not ideal and can lead to network bottlenecks. There is a workaround of sorts where a user can specify an AWS_ENDPOINT parameter for S3 cloud storage operations, which would allow the user to use an internal HTTP server as a transparent proxy to a hardcoded external S3 URL, but this is less flexible than just supporting standard HTTP proxies.

When a user wants to back up their data to cloud storage, or perform other bulk I/O operations like restore and import, CockroachDB should allow the user to specify an HTTP proxy address and port use for these external connections. We should also consider allowing the user to specify a default proxy to use for cloud storage requests, e.g. a `cloudstorage.http.proxy` cluster setting.

**Comment by rolandcrosby** [comment]
@mjibson I saw you sounded optimistic about this feature before; could you look at the cloud storage code and let me know what you think the level of effort to implement it would be?

**Comment by mjibson** [comment]
Ah so this is more general than just bulkio or S3, right? It's that they want all external HTTP connections from any cockroach node to any non-cockroach node to go through an HTTP proxy. That suggests it should be an even more global setting like `net.http.proxy` or something. Does that sound correct?

**Comment by mjibson** [comment]
Looking at things, this appears to be just a bug. We were incorrectly removing the standard HTTP proxy support from HTTP and S3 storage. PR fixes it. Good candidate for a backport.
