### ISSUE TITLE
roachtest: create new test that creates contention, dependency chains, and deadlocks

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#32814]
Inspired by #32582.

We should have a roachtest that runs nightly and stresses the kinds of scenarios that we saw bring down adriatic in the referenced issue. One idea would be to run `kv` with a relatively small `--cycle-length` (e.g. `256`), a moderate `--batch` size (e.g. `16`), and a high `--concurrency` (e.g. `72`). The keyspace would be split up to some fraction of the `--cycle-length` (e.g. `1/4`). We'd want to run this on a large number of small machines (e.g. 6 nodes, each with 2 vCPUs).

We might also want to add an `--update` flag to `kv` so that it performs reads instead of just blind writes. This behavior can also be accomplished by using the existing `--secondary-index` flag.

The test would then use time-series metrics to assert that QPS always stays above some threshold.

**Comment by vivekmenezes** [comment]
@nvanbenschoten what's the status on this? Do you want to hand it over to someone?

**Comment by nvanbenschoten** [comment]
@vivekmenezes, thanks for the prodding :) The PR is all written out and I just needed to make sure the test wasn't flaky. I'm doing that now, and I'll merge if it's not.
