### ISSUE TITLE
ui: Databases page does not show size of data in ycsb table with 10k rows

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#32879]
**Describe the problem**

First found by @timveil-cockroach. When running YCSB workload A, the usertable table has around 10k records, however the table looks completely empty based on the size listed on the /databases page. 

**To Reproduce**

1. Start docker
2. git remote add timveil https://github.com/timveil-cockroach/cdc-example.git
3. git fetch timveil
4. ./run.sh
5. Open localhost:8080 and observe that inserts in the cluster have stopped. Navigate to the databases page:
![image](https://user-images.githubusercontent.com/21692034/49551383-0c14d780-f8bd-11e8-8ac3-29bee3792e18.png)
6. docker-compose exec roach-source-0 /cockroach/cockroach sql --insecure --execute="select count(*) from ycsb.usertable;"
```
 count
+-------+
  10021
(1 row)
```
7. Results should show about 10k records, however there is no indication these exist in the UI

This does not seem to be a repro of #9433 as there is no interleaving on the table:

```
CREATE TABLE usertable (
	ycsb_key INT8 NOT NULL,
	field1 STRING NULL,
	field2 STRING NULL,
	field3 STRING NULL,
	field4 STRING NULL,
	field5 STRING NULL,
	field6 STRING NULL,
	field7 STRING NULL,
	field8 STRING NULL,
	field9 STRING NULL,
	field10 STRING NULL,
	CONSTRAINT "primary" PRIMARY KEY (ycsb_key ASC),
	FAMILY "primary" (ycsb_key, field1, field2, field3, field4, field5, field6, field7, field8, field9, field10)
)
```

**Expected behavior**
I should see around 30 MiB of data (x3 for replicas) for the usertable table.

CC @celiala

**Comment by piyush-singh** [comment]
Also cc @couchand for visibility

**Comment by couchand** [comment]
My first thought is  #22944

**Comment by tbg** [comment]
It's also possible (just guessing wildly) that the memtable never gets flushed and that this confuses the RocksDB-level method we call to approximate the on-disk size of the table.
