### ISSUE TITLE
opt: automatically reorder joins using the cost-based optimizer

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#32885]
Automatically reorder joins using the cost-based optimizer such that it picks the best plan regardless of the original order proposed by the queries.

Add a flag that allows the user to set reordering = 0 to respect the order of the queries as written.

**Comment by awoods187** [comment]
cc @justinj can you link to the pr here?

**Comment by justinj** [comment]
there's a handful but #34170 and #34549 are relevant

**Comment by awoods187** [comment]
Thanks! Closing this issue now!
