### ISSUE TITLE
opt: Support remaining read-only queries with Cost-Based Optimizer

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#32882]
Support all read-only queries with Cost-Based Optimizer instead of the heuristic planner

**Comment by RaduBerinde** [comment]
Unfortunately we didn't get to do window functions in this release; pushing to Later.

**Comment by andy-kimball** [comment]
This is a 19.2 goal.

**Comment by RaduBerinde** [comment]
@justinj please close when you finalize the last remaining item (view/sequence by ref).
