### ISSUE TITLE
during sideloading: IO error: Failed to create a NewWriteableFile

### ISSUE THREAD

**Issue by priyankajax** [cockroachdb/cockroach#32897]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. Set up CockroachDB cluster ...
2. Send SQL ... / CLI command ...
3. Look at UI / log file / client app ...

**Expected behavior**

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version [e.g. 2.0.x]
 - Server OS: [e.g. Linux/Distrib]
 - Client app [e.g. `cockroach sql`, JDBC, ...]

**Additional context**
What was the impact?

**Comment by knz** [comment]
@priyankajax what did you do before the error happened? what SQL statement did you send to CockroachDB?

**Comment by knz** [comment]
@tim-o please qualify further

**Comment by tbg** [comment]
Have to take a closer look, but this could be the same bug fixed in https://github.com/cockroachdb/cockroach/pull/32664 (fix not released, windows specific)

**Comment by kenliu** [comment]
@darinpp are you currently working on this issue?

**Comment by lunevalex** [comment]
@priyankajax we think this issue was fixed in the 19.2 cycle, but the ticket was not updated to reflect that. If you are still having issues, please let us know and we will investigate.
