### ISSUE TITLE
cli: `debug zip` should collect kernel information

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#32905]
A recent incident was tracked down to be related to a buggy kernel. It would be valuable to collect kernel information when creating a debug zip. It's probably as simple as writing the output of `uname -a` to a file in the zip.

**Comment by tbg** [comment]
Even better would be if we could [warn if vulnerable](https://github.com/cockroachdb/cockroach/issues/32906), though that shouldn't get in the way of this.
