### ISSUE TITLE
cli: support non-standard filenames in `debug merge logs`

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#32919]
As implemented in #32790, log files must conform to the naming scheme CRDB uses to write to disk. Users use different mechanism to write, store, and interact with logs leading to log files with wholly different naming conventions. This issue is a feature request to make the command for flexible to easily support merging files named with a different convention.

I imagine supporting a flag like `--log-file-pattern` which takes a regular expression that has a named capture group that at least allows us to determine the host name. Probably we could have names for all of the fields of log.FileInfo as the names for the capture groups. Additionally we may then want to add another flag that supports alternate time formats that applies if `log-file-pattern` is used.

**Comment by tbg** [comment]
I generally like this idea, but I think it's worth taking a small step back conceptually. If I have a bunch of files that don't follow the CRDB naming convention (or any convention for that matter) `merge-logs` without hand-crafted args (except the glob) should "just work" (perhaps this is implied). It won't be able to give you a hostname, but it should still give you the ordered stream of log entries. `--log-file-pattern` seems like a good addition to that in cases where you want to recover some of the information represented in the naming scheme, but it's more of a "nice to have".

**Comment by ajwerner** [comment]
Fixed in #33067.
