### ISSUE TITLE
CDC experimantal_avro message encoding

### ISSUE THREAD

**Issue by melskyzy** [cockroachdb/cockroach#32914]
**Describe the problem**
When testing the CDC with experimental_avro, I received the following (while for other formats all the messages are readable):
   	    NAME 11
    ,	    ,NAME 22
    J	    JNAME 37
    l	    lNAME 54
    €	    €NAME 64
    „	    „NAME 66
    ¢	    ¢NAME 81
    ¦	    ¦NAME 83
    Æ	    ÆNAME 99
    à	    àNAME 112
     	     NAME 144
    Ê	    ÊNAME 165
    î	    îNAME 183
    ü	    üNAME 190
    Š	    ŠNAME 197
    œ	    œNAME 206
    ¼	    ¼NAME 222
    ê	    êNAME 245
    Ž	    ŽNAME 263
    Ü	    ÜNAME 302
    ð	    ðNAME 312
    ú	    úNAME 317
    š	    šNAME 333
    ®	    ®NAME 343
    º	    ºNAME 349
    Î	    ÎNAME 359
    Ô	    ÔNAME 362
    è	    èNAME 372
    ˆ	    ˆNAME 388
    ”	    ”NAME 394
    ¨	    ¨NAME 404
    Â	    ÂNAME 417
    Ö	    ÖNAME 427
    â	    âNAME 433
    ô	    ôNAME 442
    ö	    öNAME 443
    ‚	    ‚NAME 449
    –	    –NAME 459
    ´	    ´NAME 474
    È	    ÈNAME 484
    ¬	    ¬NAME 534
    °	    °NAME 536
    Ð	    ÐNAME 552
    Ô	    ÔNAME 554
    Ø	    ØNAME 556
    ø	    øNAME 572
    Ž		    Ž	NAME 583
    ”		    ”	NAME 586
    ˜		    ˜	NAME 588
    ¶		    ¶	

**To Reproduce**

What did you do? Describe in your own words.
- created a changefeed as described in docs.

**Comment by rolandcrosby** [comment]
@melskyzy specifically, this is the binary Avro format encoded according to the conventions of Confluent's schema registry -- the wire format is described [here](https://docs.confluent.io/current/schema-registry/docs/serializer-formatter.html#wire-format). You can use the `kafka-avro-console-consumer` utility that comes with the Confluent platform to decode the binary format.
