### ISSUE TITLE
sql: hide rowid column from select and inserts

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#3293]
For tables with no primary keys, we (will soon) create an extra column named "rowid". It is not hidden or special in any way. This causes both `INSERT`s with no named columns and `SELECT *`s to fail since the column orders are different than what the user specified.

See line 3091 of https://github.com/cockroachdb/sqllogictest/blob/master/test/select4.test

**Comment by tamird** [comment]
Are you suggesting that we'll be merging that change despite these problems?

**Comment by mjibson** [comment]
Peter said it would be fine to do it in another PR: https://github.com/cockroachdb/cockroach/pull/3286#issuecomment-161410882

**Comment by petermattis** [comment]
I'm of the opinion that it is ok to split implementation of new functionality across multiple PRs as long as the steps are not causing breakage.
