### ISSUE TITLE
storage: node gossip loop panic when own node descriptor deleted

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#32942]
https://sentry.io/cockroach-labs/cockroachdb/issues/798675882/?referrer=webhooks_plugin

stopper.go:182: gossip.go:969

github.com/cockroachdb/cockroach/pkg/server.(*Node).startGossip.func1

> stacktrace: {u'frames': [{u'function': u'func1', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go', u'module': u'github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker', u'in_app': True, u'lineno': 199, u'filename': u'github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go'}, {u'function': u'func1', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/server/node.go', u'module': u'github.com/cockroachdb/cockroach/pkg/server.(*Node).startGossip', u'in_app': True, u'lineno': 740, u'filename': u'github.com/cockroachdb/cockroach/pkg/server/node.go'}, {u'function': u'gopanic', u'abs_path': u'/usr/local/go/src/runtime/panic.go', u'module': u'runtime', u'in_app': False, u'lineno': 502, u'filename': u'runtime/panic.go'}, {u'function': u'call32', u'abs_path': u'/usr/local/go/src/runtime/asm_amd64.s', u'module': u'runtime', u'in_app': False, u'lineno': 573, u'filename': u'runtime/asm_amd64.s'}]}
type: *log.safeError
value: stopper.go:182: gossip.go:969

**Comment by tbg** [comment]
https://github.com/cockroachdb/cockroach/blob/a7b24d602ffb089a14cc243b81c3e0836cb71dd3/pkg/server/node.go#L738-L741

The error is https://github.com/cockroachdb/cockroach/blob/7c3289e7cd816dbc85d1c15caf28f760089916df/pkg/gossip/gossip.go#L966-L970

**Comment by tbg** [comment]
@petermattis is this fixed by https://github.com/cockroachdb/cockroach/pull/34155?

**Comment by petermattis** [comment]
#34155 will certainly avoid this problem as our own node descriptor can no longer be removed by another node. This symptom of the underlying bug is relatively innocuous. The process will crash and hopefully something will restart it, but it isn't as bad as the other symptom where the process would remain running, but receive no traffic.

I think this can reasonably be closed as only a single event occurred months ago.
