### ISSUE TITLE
IO error: Failed to create a NewWriteableFile

### ISSUE THREAD

**Issue by thirtysixmm** [cockroachdb/cockroach#32958]
**Describe the problem**

Cockroachdb crashed during import data from CSV with 1M records

**To Reproduce**

Execute the following command

```
IMPORT TABLE employees (
    USER_ID INT PRIMARY KEY,
    NAME STRING NOT NULL,
    EMAIL STRING NOT NULL,
    EMPID STRING NOT NULL,
    DEPT STRING NOT NULL,
    LOCATION STRING NOT NULL
  ) CSV DATA ('http://localhost/user.csv');
```

**Expected behavior**
Data is supposed to be loaded to the db

**Additional data / screenshots**

> *
> * ERROR: [n1,s1] Reported as error f6922e9905eb4a9fb9f03ede8dd34ce3
> *
> F181209 07:02:31.409832 120 storage/store.go:3901  [n1,s1] during sideloading: during sideloading: IO error: Failed to create a NewWriteableFile: C:\Apps\cocroachdb-jasmine\data\auxiliary\sideloading\29\29.1\i25.t8: The system cannot find the path specified.
> goroutine 120 [running]:
> github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0xc042082200, 0xc0420822a0, 0x3711f00, 0x10)
>         /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:997 +0xd6
> github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x451bc00, 0xc000000004, 0x3711fec, 0x10, 0xf3d, 0xc0425ee700, 0xd1)
>         /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:864 +0x905
> github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x28b67c0, 0xc0420761e0, 0x4, 0x2, 0x235b2ad, 0x6, 0xc042743e60, 0x2, 0x2)
>         /go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:85 +0x2ec
> github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x28b67c0, 0xc0420761e0, 0x1, 0x4, 0x235b2ad, 0x6, 0xc042743e60, 0x2, 0x2)
>         /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:69 +0x93
> github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(0x28b67c0, 0xc0420761e0, 0x235b2ad, 0x6, 0xc042743e60, 0x2, 0x2)
>         /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:172 +0x85
> github.com/cockroachdb/cockroach/pkg/storage.(*Store).processReady(0xc0424b5b80, 0x28b67c0, 0xc0420761e0, 0x1d)
>         /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3901 +0x541
> github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc042d62080, 0x28b67c0, 0xc0420761e0)
>         /go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:214 +0x260
> github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x28b67c0, 0xc0420761e0)
>         /go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:165 +0x45
> github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc04228f150, 0xc0421aecf0, 0xc04228f140)
>         /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:199 +0xf0
> created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
>         /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:192 +0xb4

**Environment:**

*
* WARNING: RUNNING IN INSECURE MODE!
*
* - Your cluster is open for any client that can access localhost.
* - Any user, even root, can log in without providing a password.
* - Any user, connecting as root, can read or write any data in your cluster.
* - There is no network encryption nor authentication, and thus no confidentiality.
*
* Check out how to secure your cluster: https://www.cockroachlabs.com/docs/v2.1/secure-a-cluster.html
*
CockroachDB node starting at 2018-12-09 07:01:52.0422981 +0000 UTC (took 4.2s)
build:               CCL v2.1.1 @ 2018/11/19 18:32:38 (go1.10.3)
webui:               http://localhost:8081
sql:                 postgresql://root@localhost:26258?sslmode=disable
client flags:        cockroach.exe <client cmd> --host=localhost:26258 --insecure
logs:                C:\Apps\cocroachdb-jasmine\data\logs
temp dir:            C:\Apps\cocroachdb-jasmine\data\cockroach-temp835147055
external I/O path:   C:\Apps\cocroachdb-jasmine\data\extern
store[0]:            path=C:\Apps\cocroachdb-jasmine\data
status:              restarted pre-existing node
clusterID:           a610529e-541c-4661-9b80-9790697d64c7
nodeID:              1

**Comment by knz** [comment]
Dup #32897
