### ISSUE TITLE
sql: fetcher uses a Go map too heavily for columnID->ordinal map

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#32968]
During decoding, the row fetcher needs to keep track of the mapping from `ColumnID` to ordinal position in the table. This is because, unlike key columns, value columns don't always come in a predictable order - value columns can be nullable, and if they are, they won't have an encoding in the value at all.

For example, imagine the table:

```
CREATE TABLE a (a INT PRIMARY KEY, b INT NULL, c INT NULL);
INSERT INTO a VALUES(0, NULL, 1);
INSERT INTO a VALUES(1, 1, NULL);
```

On disk, there will be 2 kv pairs:

```
/0/ -> /<ColumnID for b>1
/0/ -> /<ColumnID for c>1
```

Note that column ids are technically encoded as positive differences within the value tag - guaranteeing that the column ids within the value part of the key are strictly increasing.

Back to the matter at hand - the fetcher needs to know that the `ColumnID` for b means that the value must be written to index 1 of the row, and the `ColumnID` for c means index 2 of the row.

The row fetcher/cfetcher both use a Go map to keep track of this relationship: from `ColumnID` to ordinal. Turns out that this is very expensive, since this operation takes place in the innermost loop of the decoding routine: we have to perform a map lookup once per needed column per row.

This shows up in a pprof of a scan-heavy query like TPCH Q1. Looks like we're spending up to 30% of our CPU time just decoding the value part of the key:

![image](https://user-images.githubusercontent.com/43821/49703008-b6e30980-fbcd-11e8-9dd0-076a8c042abd.png)

----

Instead of using a general-purpose hashmap, we should just use a slice and search through it. Expermentation showed that just replacing a hashmap with an `O(n)` search through the slice improved runtime significantly, dropping the percent from 30% to 10% in `processValueBytes`:

![image](https://user-images.githubusercontent.com/43821/49703018-ded26d00-fbcd-11e8-9a18-b16273699c94.png)

But we can do even better, by using the observation that the column ids in a row are always increasing - instead of having to search the whole slice of column ids every time, we can sort it ahead of time and keep a current index within, reducing the whole operation from `O(n^2)` to `O(n)` in the number of columns.

In practice, that optimization seems to not change the runtime or profile at all, suggesting that the constant factor on the map was just so egregiously bad that it overshadows any reduction from `O(n^2)` to `O(n)` in the number of keys.

We should apply this optimization to other things in the fetcher path that need to search for column ids as well, like the needed column set.

**Comment by knz** [comment]
You can also generate the decoder during physical planning (using some kind of bytecode) so that these maps are not needed any more.
