### ISSUE TITLE
sql: ensure that a pgwire-level cancellation request (using a cancel msg) prevents a client freeze

### ISSUE THREAD

**Issue by chessman** [cockroachdb/cockroach#32973]
**Issue summary** (Added @knz 2018-12-14)

The client tries to cancel its request with a pg cancel message and then gets stuck (until a timeout of 2mn) because the server does not respond. Instead CockroachDB should see the pg cancel message and immediately return an error packet and/or close the connection.

**Describe the problem**

1. Create an insert request.
2. Cancel context when the request is executing.

The request will be terminated exactly in 2 minutes.

**To Reproduce**

```
	dbname := "db" + strconv.Itoa(int(uuid.New().ID()))
	connString := fmt.Sprintf("postgresql://root@localhost:26257/%s?sslmode=disable", dbname)
	db, err := sql.Open("postgres", connString)
	if err != nil {
		panic(err)
	}
	_, err = db.Exec(`CREATE DATABASE ` + dbname)
	if err != nil {
		panic("cannot create database: " + err.Error())
	}

	defer db.Exec(`DROP DATABASE ` + dbname)

	_, err = db.Exec(`CREATE TABLE IF NOT EXISTS table1 (id STRING PRIMARY KEY)`)
	if err != nil {
		panic("cannot create schema: " + err.Error())
	}

	for {
		ctx := context.Background()
		ctx, cancel := context.WithCancel(ctx)
		go func() {
			time.Sleep(15 * time.Millisecond)
			cancel()
		}()
		started := time.Now()
		query := `INSERT INTO table1 (id) VALUES ($1)`
		id := uuid.New().String()

		_, err := db.ExecContext(ctx, query, id)
		if err != nil && err != context.Canceled {
			panic(err)
		}

		fmt.Println("inserted:", time.Since(started))
		if time.Since(started) > 1*time.Second {
			panic("too long")
		}
	}
```

**Expected behavior**
The request should be terminated immediately after the context is canceled.

**Environment:**
 - CCL v2.1.1 @ 2018/11/19 18:24:21 (go1.10.3)
 - Server OS: Debian
 - Golang (database/sql, lib/pq)

**Comment by tbg** [comment]
@knz could you triage?

**Comment by knz** [comment]
@mjibson what do you think? Is this just driver-side or is there anything to do on our end?

**Comment by chessman** [comment]
@mjibson I can't reproduce it with `github.com/jackc/pgx`. It seems, it more properly handles context cancelation. But still strange that this bug doesn't reproduce with Postgres and `lib/pq`.

**Comment by mjibson** [comment]
Did you use pgx directly or via database/sql? database/sql and lib/pq may be interacting in broken ways.

**Comment by knz** [comment]
@chessman thanks for the additional information. As noted above, CockroachDb does not support the cancel protocol, however it does cancel a query if the connection gets closed. This will also achieve the desired effect.

**Comment by chessman** [comment]
`lib/pq` sends the cancelation code and just waits for EOF. Maybe Cockroach can return EOF for this code? It might be even "not implemented" error, any result will unblock the driver.

**Comment by knz** [comment]
Yes that seems reasonable.

**Comment by knz** [comment]
@mjibson even though we may not support the pg cancel protocol, do you see any way we can detect when it is received *while a query is running*? And respond with an error immediately? I'm not sure.

Maybe @andreimatei you have an opinion about this too?

**Comment by andreimatei** [comment]
The cancel signal is sent by drivers on new connections, not the connection processing the query being performed. These dedicated connections are identified from the get-go; the docs say:

> To issue a cancel request, the frontend opens a new connection to the server and sends a CancelRequest message, rather than the StartupMessage message that would ordinarily be sent across a new connection. The server will process this request and then close the connection.

So it seems that we should just close connections when a `CancelRequest` is received. Probably easy to do.

**Comment by mjibson** [comment]
The cancel docs also state that

> For security reasons, no direct reply is made to the cancel request message.

Implying that we shouldn't even return a "not implemented" error.

There are unsolved problems when dealing with the cancel protocol:

1) Cockroach is distributed so we have to figure out what, if anything, to do if a server receives a request for an ID it doesn't recognize. Should it tell the other nodes?
2) The IDs are two 32bit numbers. Cockroach queries use a single 128bit identifier, so we can't just use that ID verbatim. Do we only use the top or bottom half? Generate (and thus store) a 64bit ID? Use some 64bit hash function on the 128bit ID? Something else?

Answering these questions isn't currently on the roadmap, so I'm not sure anything will move here soon.

**Comment by knz** [comment]
@mjibson we can close the connection upon receiving a cancel message and *not do anything else*.

**Comment by knz** [comment]
(except bumping a telemetry counter, that is)

**Comment by mjibson** [comment]
Yes, we should be doing that. If we aren't that's pretty surprising. Confirmed that psql also hangs when you run pg_sleep and hit ^C, which should do that.

**Comment by knz** [comment]
@mjibson could you casually investigate what the current situation is in the code? ie what cockroachdb does/says wyhen it receives a cancel msg? Depending on the specific current situation maybe we can do something about it.

**Comment by mjibson** [comment]
I agree. I will do that.
