### ISSUE TITLE
storage: add testing for closed timestamps and concurrent lease transfer

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#32980]
2.2 CDC work and upcoming follower reads rely on having a reliable closed timestamp infrastructure. While the code is unit tested, there is a dearth of testing from a higher level or in the face of concurrent lease transfer.

**Comment by tbg** [comment]
@ajwerner this is still on your plate, right? Asking because I'm trying to shed some work off of @danhhz's.

**Comment by ajwerner** [comment]
Yes, I’m hoping to make some progress here later today
