### ISSUE TITLE
storage: can't decrease HardState.Commit

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#33016]
https://sentry.io/cockroach-labs/cockroachdb/issues/803235403/?referrer=webhooks_plugin

store.go:2151: stateloader.go:630

github.com/cockroachdb/cockroach/pkg/storage.(*Replica).processRaftCommand

```
github.com/cockroachdb/cockroach/pkg/storage/replica.go in processRaftCommand at line 5499
github.com/cockroachdb/cockroach/pkg/storage/replica.go in handleRaftReadyRaftMuLocked at line 4313
github.com/cockroachdb/cockroach/pkg/storage/replica.go in handleRaftReady at line 4005
github.com/cockroachdb/cockroach/pkg/storage/store.go in processReady at line 3735
github.com/cockroachdb/cockroach/pkg/storage/scheduler.go in worker at line 214
github.com/cockroachdb/cockroach/pkg/storage/scheduler.go in func2 at line 165
github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go in func1 at line 198
```

**Comment by tbg** [comment]
```
	if oldHS.Commit > newHS.Commit {
		return errors.Errorf("can't decrease HardState.Commit from %d to %d",
			oldHS.Commit, newHS.Commit)
	}
```

**Comment by tbg** [comment]
On v2.2.0-alpha.20181119-663-g1cd7dcf

**Comment by tbg** [comment]
This commit is from Dec 11th, so it's recent. This is also on the `development` channel. Probably a roachtest, though the cluster ID is redacted.

**Comment by tbg** [comment]
The error originates in synthesizing the Raft HardState below this code:

```
// splitPreApply is called when the raft command is applied. Any
// changes to the given ReadWriter will be written atomically with the
// split commit.
func splitPreApply(
	ctx context.Context, st *cluster.Settings, eng engine.ReadWriter, split roachpb.SplitTrigger,
) {
	// Update the raft HardState with the new Commit value now that the
	// replica is initialized (combining it with existing or default
	// Term and Vote).
	rsl := stateloader.Make(st, split.RightDesc.RangeID)
	if err := rsl.SynthesizeRaftState(ctx, eng); err != nil {
		log.Fatal(ctx, err)
	}
}
```

So we're applying a split trigger, and in the process the HardState regresses. The two crashes we have in sentry (same cluster, node, 8s apart) both have this happen within 1m of the node starting.

**Comment by tbg** [comment]
@bdarnell curious if you have any thoughts here. The new commit index that we're passing in is the applied index that we just loaded from the engine (the raft mu is held thanks to maybeAcquireSplitLock). Isn't the following sequence possible:

1. split occurs on LHS
1. our follower is slow
1. RHS applies a bunch of commands, say, to Raft applied index 50 (from 10 originally)
1. on our follower, RHS raft group gets created through incoming raft message, learns commit index 50 but uninitialized
1. so HardState.Commit = 100
1. LHS catches up, applies the split
1. boom, because the rhs' applied index is 10 (i.e. initial state) but its HardState.Commit is 100

**Comment by tbg** [comment]
S-2 because while this *will* brick your cluster (the split trigger will fail every time), it appears to be quite rare and the fix doesn't seem to be involved.

**Comment by bdarnell** [comment]
Step 4 isn't supposed to happen: the raft leader won't tell a follower about a commit index that the follower doesn't know about (the index must be sent in the same append/snapshot or have been previously acknowledged). 

https://github.com/etcd-io/etcd/blob/a580ec4547563f85b923a0429893a887b6d73f32/raft/raft.go#L549

But that's not happening on all paths. When we send an append instead of a heartbeat, and that append gets truncated (by the per-message size limit), we send the true commit index:

https://github.com/etcd-io/etcd/blob/a580ec4547563f85b923a0429893a887b6d73f32/raft/raft.go#L522

That line should cap the commit index at the last entry being sent.

**Comment by bdarnell** [comment]
It would be good to cap the commit index sent in MsgApp, but that's not the problem here. There's a cap on the receiving side of that message that should prevent the HardState commit from advancing past what we have in our logs.

https://github.com/etcd-io/etcd/blob/a580ec4547563f85b923a0429893a887b6d73f32/raft/log.go#L100

So unless there's another bug in the handling of this commit index (which is entirely possible, the expectations here are subtle), it shouldn't be possible for HardState.Commit to be set before we've processed the split.

**Comment by tbg** [comment]
Isn't there necessarily a bug then? Based on what you're describing, zero is the only valid HardState.Commit for an uninitialized replica. Unless this replica wasn't uninitialized, in which case there should't be a split trigger hitting it.

**Comment by bdarnell** [comment]
Yes, there's necessarily a bug, it's just not the one I pointed at earlier.

**Comment by tbg** [comment]
Ok. Looks like we can place a cheap assertion and hopefully find it.

**Comment by tbg** [comment]
Closing since there's not much we can do except wait.

**Comment by Nishant9** [comment]
We have hit this in couple of our clusters. Following is the partial stack trace from one of them( its 12 node, don't have access to cluster at the moment):
```[n2,s2,r2150/4:/Table/74/1/{794082…-850182…}] can't decrease HardState.Commit from 274382 to 10
goroutine 884 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0xc4200ff600, 0xc4200ff680, 0x40ace00, 0x10)
/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:997 +0xcf
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x49aa0c0, 0xc400000004, 0x40ace70, 0x10, 0x92b, 0xc42b5fa0c0, 0x63)
/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:864 +0x8fe
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x315d900, 0xc42a8b62d0, 0x4, 0x2, 0x0, 0x0, 0xc42b584a88, 0x1, 0x1)
/go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:85 +0x2e5
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x315d900, 0xc42a8b62d0, 0x1, 0x4, 0x0, 0x0, 0xc42b584a88, 0x1, 0x1)
/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:69 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatal(0x315d900, 0xc42a8b62d0, 0xc42b584a88, 0x1, 0x1)
/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:181 +0x6c
github.com/cockroachdb/cockroach/pkg/storage.splitPreApply(0x315d900, 0xc42a8b62d0, 0xc420125980, 0x7f31a3c45180, 0xc42b5c6240, 0x866, 0xc42ad5b800, 0x32, 0x40, 0xc42ad5b840, ...)
/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2347 +0xf4
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).processRaftCommand(0xc42a8a5500, 0x315d900, 0xc42a8b62d0, 0xc42bc43c88, 0x8, 0x6, 0x33, 0x700000007, 0x2, 0x8e, ...)
/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:5467 +0x1395
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReadyRaftMuLocked(0xc42a8a5500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:4362 +0x1118
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReady(0xc42a8a5500, 0x0,  ```
@tbg I think removing the node and adding it back will fix the issue, is that correct? Is there a more trivial fix?

**Comment by tbg** [comment]
Which version are you running, @Nishant9? Re-adding this node *could* fix this but I can't be sure. Feel free to open an internal issue.

**Comment by neeral** [comment]
v2.1

**Comment by irfansharif** [comment]
The issue Nishant/Neeral are running into is something else, it just happens to result in this particular assertion tripping up due to other badness (specifically it seems that we seem to be regenerating the same RangeID).
