### ISSUE TITLE
storage: Replica.Entries does not obey maxBytes parameter internally

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#33066]
`Replica.Entries` takes a `maxBytes` parameter which restricts how much data is returned. Internally, it ignores this parameter because `MVCCIterate` calls `MVCCScan` in a loop, reading 1000 entries at a time. Those 1000 entries can significantly exceed the `maxBytes` setting. This isn't a huge problem, but can make replaying a Raft log with many large entries significantly slower than expected, and consume significantly more memory.

**Comment by lunevalex** [comment]
This was reworked in #44339, closing.
