### ISSUE TITLE
storage: inability to up-replicate if Raft log is too large

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#33071]
This is fallout from #32896.

If the Raft log is too large, preemptive snapshots will not be sent which prevents up-replication. If a range is not experiencing write traffic, it can stay in this state for an extended period of time (perhaps forever) because the Raft log truncation heuristics will refuse to truncate the Raft log. This shows up in the logs as:

```
I181212 18:07:58.829705 90221 storage/replicate_queue.go:260  [n1,replicate,s1,r3437/1:/Table/428/1/"\x0{2\vP…-3A\x…}] snapshot failed: aborting snapshot because raft log is too large (24801729 bytes after processing 12 of 1422 entries)
E181212 18:07:58.829748 90221 storage/queue.go:839  [n1,replicate,s1,r3437/1:/Table/428/1/"\x0{2\vP…-3A\x…}] failed to replicate after 5 retries
```

The full scenario of how this happened is that a large transaction was performed on a 3 node cluster. While the system was digesting the transaction, one of the nodes was taken down and decommissioned while another node was added. This resulted in an excessively large Raft log (2.25 GB) on 3 ranges. The 3 ranges with large Raft logs have now caught up, but they are refusing to up-replicate to the newly added node because the Raft log is too large. The Raft log is not being truncated because the Raft log size is only cached in memory and the size is not recomputed when the Range is loaded. The effect is that the range status debug page (and the `Replica`) think the Raft log is a few hundred kilobytes, while the snapshot machinery knows that the real Raft log size is 2+ GB. 

@bdarnell Any thoughts on what to do here?

**Comment by petermattis** [comment]
Ideally, we'd have a mechanism to truncate the Raft log in these circumstances. Question is what mechanism would accurately determine the Raft log size and update it. Could we have this driven by the code that is failing the snapshot because it is too large?

**Comment by petermattis** [comment]
@tbg Where are we using `RaftLogTruncationThreshold`? Seems like it isn't used by `raftLogQueue` anymore.

**Comment by petermattis** [comment]
Note that `4*RaftLogTruncationThreshold` is the threshold used to prohibit sending preemptive snapshots. I think there is something to fix up here, independent of the inaccurate Raft log size estimate.

**Comment by petermattis** [comment]
I ran the following patch on the user's cluster:

```diff
diff --git a/pkg/storage/replica_command.go b/pkg/storage/replica_command.go
index 69a5b861f4..7a333f4283 100644
--- a/pkg/storage/replica_command.go
+++ b/pkg/storage/replica_command.go
@@ -865,6 +865,19 @@ func (r *Replica) changeReplicas(
                // progress which might be required for this ChangeReplicas operation to
                // complete. See #10409.
                if err := r.sendSnapshot(ctx, repDesc, snapTypePreemptive, priority); err != nil {
+                       if strings.Contains(err.Error(), "raft log is too large") {
+                               // If the snapshot failed because the Raft log is too large, force the
+                               // raft log size to a value that will require truncation and add the
+                               // range to the raft log queue. This still won't truncate the Raft log
+                               // if we're below quorum, but it will truncate an overly large yet idle
+                               // range for which the estimated Replica.mu.raftLogSize is inaccurate.
+                               r.mu.Lock()
+                               if r.mu.raftLogSize < r.mu.maxBytes {
+                                       r.mu.raftLogSize = r.mu.maxBytes
+                               }
+                               r.mu.Unlock()
+                               r.store.raftLogQueue.MaybeAdd(r, r.store.Clock().Now())
+                       }
                        return err
                }
```

This did "fix" the problem allowing the 3 under-replicated ranges to up-replicate, but note that it left a small additional problem: `r.mu.raftLogSize` is now too large on the leader node. I'm not sure why. 

PS A real solution would not peek inside the error message like this.

**Comment by tbg** [comment]
I think this problem would solve itself fall out of truncating proactively, see also https://github.com/cockroachdb/cockroach/issues/26339. When write traffic stops, we basically want to do one last round of truncations before quiescing (this is easily expressed in writing but I think it's a bit finicky to implement). (When a node starts, its raft groups will unquiesce once https://github.com/cockroachdb/cockroach/pull/32845 is in, so that case is handled too). If write traffic doesn't stop, it'll "only" take 100 raft commands until we do a cooperative truncation. We could also designate a special priority with which we can enqueue and force a cooperative (or even aggressive) truncation.

> r.mu.raftLogSize is now too large on the leader node. I'm not sure why.

This tracking is a sore because when it diverges I think it stays that way.

**Comment by bdarnell** [comment]
As we discussed I like the approach in that patch. 

We now have the consistency queue to update MVCCStats; I think it could also be used to update the raft log size to correct long-term discrepancies.

**Comment by petermattis** [comment]
@tbg Good point about truncating proactively, though I'm not sure about doing it immediately before quiescing. I believe quiescence happens so quickly that truncating before quiescence would be too expensive. That's just my intuition, though.

**Comment by petermattis** [comment]
#34287 sounds more involved. I'm for it if you have the time to do it soon.

**Comment by tbg** [comment]
Ack. I'll wait for @bdarnell to sanity check that issue.

**Comment by bdarnell** [comment]
I kind of like the update to `r.mu.raftLogSize` from https://github.com/cockroachdb/cockroach/issues/33071#issuecomment-446718590 more than allowing per-replica truncation state. We have a number of reasons (not just snapshots) to try and keep the raft log small, so making our tracking of the log size more accurate is a good idea.

**Comment by tbg** [comment]
Hmm. Don't you agree that sending past log entries in snapshots is wasteful? I'll add that in the case of import/restore, those log entries are often 22mb each, and we have made the Raft log truncation less aggressive in many cases to avoid overly aggressive truncation in the first place. We already try to be proactive, but I feel strongly that we need to disentangle queues where possible, not the opposite. Even if truncation would do the right thing, we shouldn't rely on a raft log queue run, which may not happen for lots of reasons including the fact that things are queued and queues get blocked.

I generally agree that the more correct our raft log size tracking is the better, but I fail to see how https://github.com/cockroachdb/cockroach/issues/33071#issuecomment-446718590 makes a meaningful attempt at improving its accuracy. We'd need to compute the size of the log under `raftMu` when stepping up as leader.

**Comment by bdarnell** [comment]
Yes, it's wasteful. I was thinking it was an insignificant amount of waste if backpressure and log size tracking was working correctly, but I wasn't thinking about things like import/restore. #34287 seems like a good idea in the abstract (it's what I'd do if we were starting from scratch), so as long as the migration isn't too onerous (and lifting this rock doesn't expose any new bugs) we should do it.

https://github.com/cockroachdb/cockroach/issues/33071#issuecomment-446718590 improves the accuracy of the log size by ratcheting it up towards the snapshot size limit (which also happens to be enough to make the truncation queue and other backpressure mechanisms activate).

**Comment by petermattis** [comment]
Another user encountered this problem. In discussion, @andreimatei think it would be worthwhile to write a method to recompute the Raft log size from the KV entries and to perform that recomputation when a replica becomes the leaseholder. There is a minor danger that recomputing the Raft log size on leaseholder transfer would be too expensive. On the other hand, tracking down these issues is expensive too.

**Comment by tbg** [comment]
Mentioned in private as well, but the computation would only ever have to produce numbers <= 4mb.
Also mentioned in private, but without the glaring bug fixed in #34502 the worst the stats mismatch could do is keep a <4mb Raft log around (which wouldn't fail snapshots).

**Comment by petermattis** [comment]
> Mentioned in private as well, but the computation would only ever have to produce numbers <= 4mb.

Is this true? When you first said that I thought the argument was because any Raft log larger than 4MB (i.e. `RaftLogTruncationThreshold`) would trigger truncation. But if we end up not truncating all of the Raft log then `raftLogSize` will continue to be inaccurate. Note that `Replica.mu.raftLogSize` is the size of all of the Raft log entries, not just the committed ones. We can only ever truncate up to the quorum commit index. Am I misunderstanding the argument for why limiting to 4MB is safe?

**Comment by tbg** [comment]
You're right, sorry about the confusion. Yes, it's possible that the leaseholder repeatedly changes without any of them seeing 4mb being committed to the log. It seems unlikely for that pattern to persist for long, but it's definitely bad.

> Am I misunderstanding the argument for why limiting to 4MB is safe?

If we know that there are >=4mb, we'll truncate what we can (right now never past the quorum index, that's a problem in itself but I think the uncommitted tail of the log is bounded in size since we made a change to Raft to that effect, and the quorum commit index can't lag indefinitely because quota pool). But you're right that the truncation will throw away more than 4mb (so the new raft log size is zero) and if more than 4mb are left, we won't know to truncate again. But we could recompute the log size after TruncateLog as well - this seems like it should get the desired effect. Not sure if it's worth optimizing that much, though.

Also, and I know you know this, but for anyone else reading this, this particular issue should eventually be solved through the fact that the snapshot doesn't have to contain a single log entries, and so the size of the log won't matter for snapshots. We'll still want to avoid the huge Raft log for other reasons, though.
