### ISSUE TITLE
sql,opt: convert existing delegateQuery calls to use CBO

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#33070]
This came out of a discussion with @lucy-zhang re: `SCRUB`.

Many commands, such as `SCRUB`, explicitly defer to the heuristic planner to run helper queries. It's not clear to me how safe/easy it will be to simply replace the implementation of `delegateQuery`.

**Comment by knz** [comment]
Ditto all the CCL statements

**Comment by RaduBerinde** [comment]
This is all done.

**Comment by jordanlewis** [comment]
Congrats!
