### ISSUE TITLE
sentry: conn_executor.go:643: panic while executing 1 statements: SELECT * FROM _._ LIMIT _: caused by <redacted>

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#33085]
https://sentry.io/cockroach-labs/cockroachdb/issues/805237552/?referrer=webhooks_plugin

conn_executor.go:643: panic while executing 1 statements: SELECT * FROM _._ LIMIT _: caused by <redacted>

github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1

> stacktrace: {u'frames': [{u'function': u'func4', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl', u'in_app': True, u'lineno': 313, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go'}, {u'function': u'ServeConn', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*Server)', u'in_app': True, u'lineno': 389, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go'}, {u'function': u'run', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'in_app': True, u'lineno': 1116, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go'}, {u'function': u'execStmt', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'in_app': True, u'lineno': 96, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go'}, {u'function': u'execStmtInOpenState', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'in_app': True, u'lineno': 402, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go'}, {u'function': u'dispatchToExecutionEngine', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'in_app': True, u'lineno': 824, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go'}, {u'function': u'execWithDistSQLEngine', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'in_app': True, u'lineno': 982, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go'}, {u'function': u'PlanAndRun', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner)', u'in_app': True, u'lineno': 758, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go'}, {u'function': u'Run', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner)', u'in_app': True, u'lineno': 253, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go'}, {u'function': u'StartSync', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow)', u'in_app': True, u'lineno': 607, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go'}, {u'function': u'Run', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase)', u'in_app': True, u'lineno': 730, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go'}, {u'function': u'Start', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource)', u'in_app': True, u'lineno': 139, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go'}, {u'function': u'startExec', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql', u'in_app': True, u'lineno': 645, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/plan.go'}, {u'function': u'walkPlan', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql', u'in_app': True, u'lineno': 65, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/walk.go'}, {u'function': u'visit', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor)', u'in_app': True, u'lineno': 101, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/walk.go'}, {u'function': u'visitInternal', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor)', u'in_app': True, u'lineno': 543, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/walk.go'}, {u'function': u'func1', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal', u'in_app': True, u'lineno': 134, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/walk.go'}, {u'function': u'func2', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.startExec', u'in_app': True, u'lineno': 640, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/plan.go'}, {u'function': u'startExec', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/delayed.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*delayedNode)', u'in_app': True, u'lineno': 62, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/delayed.go'}, {u'function': u'func1', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt_exec_factory.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*execFactory).ConstructVirtualScan', u'in_app': True, u'lineno': 130, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/opt_exec_factory.go'}, {u'function': u'func1', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/virtual_schema.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.virtualTableEntry.getPlanInfo', u'in_app': True, u'lineno': 134, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/virtual_schema.go'}, {u'function': u'func38', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/crdb_internal.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.glob.', u'in_app': True, u'lineno': 741, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/crdb_internal.go'}, {u'function': u'ListLocalSessions', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/server/status.go', u'module': u'github.com/cockroachdb/cockroach/pkg/server.(*statusServer)', u'in_app': True, u'lineno': 1385, u'filename': u'github.com/cockroachdb/cockroach/pkg/server/status.go'}, {u'function': u'SerializeAll', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/exec_util.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*SessionRegistry)', u'in_app': True, u'lineno': 854, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/exec_util.go'}, {u'function': u'serialize', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'in_app': True, u'lineno': 2057, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go'}, {u'function': u'panicdottypeE', u'abs_path': u'/usr/local/go/src/runtime/iface.go', u'module': u'runtime', u'in_app': False, u'lineno': 252, u'filename': u'runtime/iface.go'}, {u'function': u'gopanic', u'abs_path': u'/usr/local/go/src/runtime/panic.go', u'module': u'runtime', u'in_app': False, u'lineno': 502, u'filename': u'runtime/panic.go'}, {u'function': u'call32', u'abs_path': u'/usr/local/go/src/runtime/asm_amd64.s', u'module': u'runtime', u'in_app': False, u'lineno': 573, u'filename': u'runtime/asm_amd64.s'}, {u'function': u'func1', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn', u'in_app': True, u'lineno': 387, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go'}]}
type: *log.safeError
value: conn_executor.go:643: panic while executing 1 statements: SELECT * FROM _._ LIMIT _: caused by <redacted>

**Comment by jordanlewis** [comment]
This is the same as #33086.
