### ISSUE TITLE
sentry: conn_executor.go:521: panic while executing 1 statements: SELECT _.*, _ FROM _ AS _ JOIN (SELECT _, max(_) AS _ FROM _ WHERE (_ BETWEEN _ AND _) GROUP BY _) AS _ ON _._ = _._ WHERE ((_._ = _) OR (_._ IN (SELECT _ FROM _ WHERE _ = _))) AND (_._ IN (SELECT _ FROM _ ORDER BY count(_) DESC)): caused by <redacted>

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#33104]
https://sentry.io/cockroach-labs/cockroachdb/issues/805557202/?referrer=webhooks_plugin

conn_executor.go:521: panic while executing 1 statements: SELECT _.*, _ FROM _ AS _ JOIN (SELECT _, max(_) AS _ FROM _ WHERE (_ BETWEEN _ AND _) GROUP BY _) AS _ ON _._ = _._ WHERE ((_._ = _) OR (_._ IN (SELECT _ FROM _ WHERE _ = _))) AND (_._ IN (SELECT _ FROM _ ORDER BY count(_) DESC)): caused by <redacted>

github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func2

> stacktrace: {u'frames': [{u'function': u'func3', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl', u'in_app': True, u'lineno': 260, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go'}, {u'function': u'ServeConn', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*Server)', u'in_app': True, u'lineno': 491, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go'}, {u'function': u'run', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'in_app': True, u'lineno': 964, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go'}, {u'function': u'execStmt', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'in_app': True, u'lineno': 87, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go'}, {u'function': u'execStmtInOpenState', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'in_app': True, u'lineno': 349, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go'}, {u'function': u'dispatchToExecutionEngine', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'in_app': True, u'lineno': 582, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go'}, {u'function': u'execWithLocalEngine', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'in_app': True, u'lineno': 618, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go'}, {u'function': u'start', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*planTop)', u'in_app': True, u'lineno': 417, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/plan.go'}, {u'function': u'evalSubqueries', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/subquery.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*planTop)', u'in_app': True, u'lineno': 114, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/subquery.go'}, {u'function': u'doEval', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/subquery.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*subquery)', u'in_app': True, u'lineno': 144, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/subquery.go'}, {u'function': u'Next', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/sort.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*sortNode)', u'in_app': True, u'lineno': 247, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/sort.go'}, {u'function': u'Next', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/render.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*renderNode)', u'in_app': True, u'lineno': 344, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/render.go'}, {u'function': u'renderRow', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/render.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*renderNode)', u'in_app': True, u'lineno': 697, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/render.go'}, {u'function': u'Eval', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FuncExpr)', u'in_app': True, u'lineno': 3312, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go'}, {u'function': u'sigpanic', u'abs_path': u'/usr/local/go/src/runtime/signal_windows.go', u'module': u'runtime', u'in_app': False, u'lineno': 167, u'filename': u'runtime/signal_windows.go'}, {u'function': u'panicmem', u'abs_path': u'/usr/local/go/src/runtime/panic.go', u'module': u'runtime', u'in_app': False, u'lineno': 63, u'filename': u'runtime/panic.go'}, {u'function': u'gopanic', u'abs_path': u'/usr/local/go/src/runtime/panic.go', u'module': u'runtime', u'in_app': False, u'lineno': 505, u'filename': u'runtime/panic.go'}, {u'function': u'call32', u'abs_path': u'/usr/local/go/src/runtime/asm_amd64.s', u'module': u'runtime', u'in_app': False, u'lineno': 573, u'filename': u'runtime/asm_amd64.s'}, {u'function': u'func2', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn', u'in_app': True, u'lineno': 489, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go'}]}
type: *log.safeError
value: conn_executor.go:521: panic while executing 1 statements: SELECT _.*, _ FROM _ AS _ JOIN (SELECT _, max(_) AS _ FROM _ WHERE (_ BETWEEN _ AND _) GROUP BY _) AS _ ON _._ = _._ WHERE ((_._ = _) OR (_._ IN (SELECT _ FROM _ WHERE _ = _))) AND (_._ IN (SELECT _ FROM _ ORDER BY count(_) DESC)): caused by <redacted>

**Comment by jordanlewis** [comment]
Same as #33106.
