### ISSUE TITLE
storage: kv.raft_log.synchronize is for internal testing only

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#33132]
See: https://github.com/cockroachlabs/support/issues/244#event-2024374098

Based on discussions with @bdarnell and @petermattis, users should never use change the `kv.raft_log.synchronize` to `false`. The consensus is that we should either remove this cluster setting or rename it to include `_unsafe`. @petermattis mentioned that the setting is useful for internal testing, so renaming might be better. 

Also, if there's a way to exclude the setting from the auto-generated cluster setting docs, similar to the `SKIP DOC` function for sql diagrams`, that would be great.

**Comment by petermattis** [comment]
The setting was useful historically. I haven't touched it in a long time. Removing it is also an option.

**Comment by nvanbenschoten** [comment]
I like the idea of suffixing it with an `_unsafe` specifier.

I'm not particularly against leaving it visible though. If anything, it prompts the question about why we don't recommend this and why other databases which do suggest it (especially during perf tests) are being somewhat dishonest.

**Comment by jseldess** [comment]
@nvanbenschoten, if we leave this visible, do you think it's possible to update the help text to sufficiently clarify why this is not good for production?

**Comment by nvanbenschoten** [comment]
Yes, we should absolutely do that.

**Comment by bdarnell** [comment]
One problem with the "unsafe" suffix is that this is a true-by-default setting. To mark it as unsafe we'd probably want to invert the setting: `kv.raft_log.disable_synchronization_unsafe`
