### ISSUE TITLE
qa: V1 of automated "sign-off" for new build on long-running cluster

### ISSUE THREAD

**Issue by mrtracy** [cockroachdb/cockroach#33147]
As part of our process for verifying a new release build, we currently run the candidate build on a multi-node cluster under load for a period of one week.  During this time, it is currently the responsibility of the engineer running the release to "sign-off" that the cluster ran as predicted during that week.

This PR is attempting to take some of the manual work (and guess-work) out of this process by creating an automated tool that will Verify that a cluster has been running correctly for the week.  This does not have to be run continuously; there are several sources of constantly collected by a running cluster that can be verified after the fact:

+ Time series data is collected on all running nodes for a variety of metrics.
+ The cluster event log tracks important changes in the cluster state, including both physical changes (added/removed/down nodes) and metadata changes (schema changes).
+ The range log can be used to inspect the split and rebalancing history of the cluster.
+ Logs are available on all running machines.
+ The schema and data created by the applied workload can be verified as well.

This initial issue is going to keep it simple: it's going to focus on connecting to a cluster, and verifying a few metrics along with the cluster event log.  It will not, in V1, consider the range log, log files, or any data from the workload generators.  With the initial simple prototype, we will still get some immediate value while also gathering more data on the best way to structure this tool to be extended in the future.

Jira issue: CRDB-4702

**Comment by tbg** [comment]
cc @petermattis, this seems related to what would be needed for a long-running roachtest.

**Comment by petermattis** [comment]
Agreed. Matt and I talked about this last week.
