### ISSUE TITLE
build: Update to Go 1.10.6

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#33169]
The newly released go 1.10.6 has a fix for quadratic behavior in certificate validation. This is a potential DoS vector for CRDB clusters exposed to hostile networks. We should use this version of go in our next patch releases.

**Comment by petermattis** [comment]
Rebuilding the builder image takes a few hours. Might as well get started...

**Comment by bdarnell** [comment]
By "next patch releases" i was thinking of the post-holiday ones, not the ones that are scheduled for monday.

**Comment by petermattis** [comment]
Ack. I don't see any reason to delay updating the builder on master though. It is a chore, but easily done in the background. I can delay merging the PR until after Monday.
