### ISSUE TITLE
Windows node crashed due to clock synchronization error

### ISSUE THREAD

**Issue by mdoleary** [cockroachdb/cockroach#33161]
Please describe the issue you observed, and any steps we can take to reproduce it:

One of the (Windows Server 2016) nodes in my cluster terminated after experiencing a fatal error:
*
* ERROR: [n1] Reported as error 3d3731225f9e46529b8cb87cb951148e
*
F181214 13:49:51.487432 2279752 server/server.go:248  [n1] clock synchronization error: this node is more than 500ms away from at least half of the known nodes (2 of 4 are within the offset)
goroutine 2279752 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0xc04248e400, 0xc04248e420, 0x3717f00, 0x10)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:997 +0xd6
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x452ec40, 0xc000000004, 0x3717f83, 0x10, 0xf8, 0xc04278e1b0, 0x88)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:864 +0x905
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x28c4540, 0xc042943740, 0x4, 0x2, 0x0, 0x0, 0xc0481d9c58, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:85 +0x2ec
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x28c4540, 0xc042943740, 0x1, 0x4, 0x0, 0x0, 0xc0481d9c58, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:69 +0x93
github.com/cockroachdb/cockroach/pkg/util/log.Fatal(0x28c4540, 0xc042943740, 0xc0481d9c58, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:181 +0x73
github.com/cockroachdb/cockroach/pkg/server.NewServer.func1()
        /go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:248 +0xb7
github.com/cockroachdb/cockroach/pkg/rpc.(*Context).runHeartbeat(0xc04234aa00, 0xc049399770, 0xc04d8b7a00, 0x11, 0xc04a8ec9c0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:790 +0x66e
github.com/cockroachdb/cockroach/pkg/rpc.(*Context).GRPCDial.func1.1.1(0x28c4540, 0xc048fd0750)
        /go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:668 +0x7b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc04b2d3cd0, 0xc04218d290, 0xc048fd0720)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:199 +0xf0
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:192 +0xb4

****************************************************************************

This node experienced a fatal error (printed above), and as a result the
process is terminating.

**To Reproduce**

There are 3 nodes in my cluster (2 Windows Server 2016, and 1 Debian 9).  I had just updated them to version 2.1.2 yesterday.  This is an evaluation only cluster, so no real activity against it yet.

What did you do? Describe in your own words.
Brought up the cluster yesterday afternoon and then left it running over night.

If possible, provide steps to reproduce the behavior:

1. Set up CockroachDB cluster ...  Two Windows Server 2016  and 1 Linux (Debian 9) all running CockroachDB 2.1.2
2. Send SQL ... / CLI command ...   Not applicable
3. Look at UI / log file / client app ... Not applicable
4. See error (Above)

**Expected behavior**
All three servers in the cluster are using the same Google NTP servers (time1.google.com time2.google.com time3.google.com time4.google.com) as their source, so I would expect them not to crash as a result of a clock synchronization error.

**Additional data / screenshots**
Here is the NTP configuration from the Windows server that crashed:
C:\>w32tm /query /configuration
[Configuration]

EventLogFlags: 2 (Local)
AnnounceFlags: 5 (Local)
TimeJumpAuditOffset: 28800 (Local)
MinPollInterval: 6 (Local)
MaxPollInterval: 10 (Local)
MaxNegPhaseCorrection: 4294967295 (Local)
MaxPosPhaseCorrection: 4294967295 (Local)
MaxAllowedPhaseOffset: 300 (Local)

FrequencyCorrectRate: 4 (Local)
PollAdjustFactor: 5 (Local)
LargePhaseOffset: 50000000 (Local)
SpikeWatchPeriod: 900 (Local)
LocalClockDispersion: 10 (Local)
HoldPeriod: 5 (Local)
PhaseCorrectRate: 1 (Local)
UpdateInterval: 100 (Local)

[TimeProviders]

NtpClient (Local)
DllName: C:\Windows\system32\w32time.dll (Local)
Enabled: 1 (Local)
InputProvider: 1 (Local)
AllowNonstandardModeCombinations: 1 (Local)
ResolvePeerBackoffMinutes: 15 (Local)
ResolvePeerBackoffMaxTimes: 7 (Local)
CompatibilityFlags: 2147483648 (Local)
EventLogFlags: 1 (Local)
LargeSampleSkew: 3 (Local)
SpecialPollInterval: 3600 (Local)
Type: NTP (Local)
NtpServer: time1.google.com time2.google.com time3.google.com time4.google.com (Local)

VMICTimeProvider (Local)
DllName: C:\Windows\System32\vmictimeprovider.dll (Local)
Enabled: 1 (Local)
InputProvider: 1 (Local)
NtpServer (Local)
DllName: C:\Windows\system32\w32time.dll (Local)
Enabled: 0 (Local)
InputProvider: 0 (Local)

C:\>w32tm /query /status
Leap Indicator: 0(no warning)
Stratum: 2 (secondary reference - syncd by (S)NTP)
Precision: -6 (15.625ms per tick)
Root Delay: 0.0140120s
Root Dispersion: 0.0149736s
ReferenceId: 0xD8EF2304 (source IP:  216.239.35.4)
Last Successful Sync Time: 12/14/2018 8:38:47 AM
Source: time2.google.com
Poll Interval: 9 (512s)

If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables. - N/A

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version 2.1.2
 - Server OS: Windows Server 2016 Standard Edition
 - Client app [e.g. `cockroach sql`, JDBC, ...] Not applicable

**Additional context**
What was the impact?  One node in the cluster crashed.
[EPu2016srv2CockrochLogs12-14-2018.zip](https://github.com/cockroachdb/cockroach/files/2680480/EPu2016srv2CockrochLogs12-14-2018.zip)

**Comment by tbg** [comment]
The last sync on the crashed server looks reasonably recent, but I don't know about the other two.

What strikes me as bad is that we don't print the detected time offsets.

**Comment by kenliu** [comment]
removing from dev infrastructure project - should be triaged by another team
