### ISSUE TITLE
TestRangeCommandClockUpdate is flaky

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#3317]
https://circleci.com/gh/cockroachdb/cockroach/9837

```
	testing.go:157: storage/client_replica_test.go:83: condition failed to evaluate within 50ms: storage/client_replica_test.go:80: expected (5, 5, 5), got [5 5 0]
```

50ms may just be too low of a timeout for circleci.

**Comment by petermattis** [comment]
I believe the flakiness in this and similar tests was fixed.

**Comment by bdarnell** [comment]
Yes, the timeout has been increased.
