### ISSUE TITLE
sentry: txn.go:607: deadline below txn.OrigTimestamp is nonsensical; txn has would have no change to commit. Deadline: %s, txn: %s | hlc.Timestamp; *roachpb.Transaction

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#33170]
https://sentry.io/cockroach-labs/cockroachdb/issues/807870548/?referrer=webhooks_plugin

txn.go:607: deadline below txn.OrigTimestamp is nonsensical; txn has would have no change to commit. Deadline: %s, txn: %s | hlc.Timestamp; *roachpb.Transaction

github.com/cockroachdb/cockroach/pkg/sql.(*TableCollection).getTableVersionByID

> stacktrace: {u'frames': [{u'function': u'func3', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl', u'in_app': False, u'lineno': 260, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go'}, {u'function': u'ServeConn', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*Server)', u'in_app': False, u'lineno': 491, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go'}, {u'function': u'run', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'in_app': False, u'lineno': 972, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go'}, {u'function': u'execPrepare', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'in_app': False, u'lineno': 55, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go'}, {u'function': u'addPreparedStmt', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'in_app': False, u'lineno': 122, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go'}, {u'function': u'prepare', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'in_app': False, u'lineno': 214, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go'}, {u'function': u'func1', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).prepare', u'in_app': False, u'lineno': 197, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go'}, {u'function': u'prepare', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*planner)', u'in_app': False, u'lineno': 799, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/plan.go'}, {u'function': u'doPrepare', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*planner)', u'in_app': False, u'lineno': 834, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/plan.go'}, {u'function': u'Insert', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/insert.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*planner)', u'in_app': False, u'lineno': 196, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/insert.go'}, {u'function': u'TablesNeededForFKs', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/fk.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/sqlbase', u'in_app': False, u'lineno': 215, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/sqlbase/fk.go'}, {u'function': u'getTable', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/fk.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*tableLookupQueue)', u'in_app': False, u'lineno': 105, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/sqlbase/fk.go'}, {u'function': u'lookupFKTable)-fm', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/delete.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*planner).(github.com/cockroachdb/cockroach/pkg/sql', u'in_app': False, u'lineno': 88, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/delete.go'}, {u'function': u'lookupFKTable', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/planner.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*planner)', u'in_app': False, u'lineno': 473, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/planner.go'}, {u'function': u'getTableVersionByID', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/table.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*TableCollection)', u'in_app': False, u'lineno': 351, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/table.go'}]}
type: *log.safeError
value: txn.go:607: deadline below txn.OrigTimestamp is nonsensical; txn has would have no change to commit. Deadline: %s, txn: %s | hlc.Timestamp; *roachpb.Transaction

**Comment by vivekmenezes** [comment]
We've seen this happen on 2.0.6 before but never on 2.1 yet. We have some additional debug information in 2.1 which will help us followup on this issue

**Comment by knz** [comment]
Dup #24930
