### ISSUE TITLE
sentry: auto-filed alerts need some improvements

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#33182]
The new sentry autofiler is great, as it strives to prevent people from having to look at sentry. In practice, though, it has some shortcomings.

- [ ] The autofiler claims to be @tbg. We should make it run on the @cockroach-teamcity account.
- [ ] The issues are hard to read and don't have a clear stacktrace, making it necessary to go back to Sentry to retrieve the stacktrace.
- [ ] The issues don't have a Cockroach version number on them, making it necessary to go back to Sentry to retrieve the version number.

@tbg can we work together on this? It's really troublesome. I'd like to start by making a shared Zapier account, so more than just you can edit the Zap, move the webhook to @cockroach-teamcity.

**Comment by tbg** [comment]
Sure, DM me the account details and I'll get it moved over today.

**Comment by jordanlewis** [comment]
This is done, see #33220. Woohoo!
