### ISSUE TITLE
sql: update Sequelize Support to 4.x

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#33192]
Currently we support only version 3.x.  
We need to update our support to 4.0 and give it the full Hibernate treatment.  Find all the rough edges and get a nightly test going.

This may also require updating the npm sequelize-cockroachdb package as well.

**Comment by knz** [comment]
@BramGruneir thank you for filing the issue!

Do you want to give a shot at enumerating a step-by-step list of what actions are needed for this investigation? And who should carry them out? Thanks

**Comment by BramGruneir** [comment]
I can try to lay out the step by step instructions, but I'm not familiar with our Sequalize library at all, so that will take some time.

As for who, I think we can sort that out as a team.  It may fall onto me, which is fine, we just need to prioritize this.

**Comment by vy-ton** [comment]
Sequelize v4 is supported see [commit](https://github.com/cockroachdb/sequelize-cockroachdb/commit/9de566da8346896b58e7b9f2c83a571f16562906)
