### ISSUE TITLE
ui: Show SQL connections by app_name

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#33203]
**Is your feature request related to a problem? Please describe.**
A customer was recently investigating a large number of SQL connections that looked suspicious and may have been related to an outage. Despite setting app_name for each connection, there isn't a convenient way to determine which application is responsible for SQL connections in the Admin UI. cc @tim-o

**Describe the solution you'd like**
We should allow users to investigate which applications are responsible for SQL connections over time: 

- One way of doing this would be to update the SQL connections chart on the SQL dashboard to display connections by application name. This seems heavy handed since we do not know what fraction of users actually set the app_name field via ORMs/DB drivers.
- Another solution might be to just expose this time series and rely on users to chart this via custom charts in cases where it would be helpful. Only exposing this time series via the custom chart debug page poses challenges to discoverability, but this might be fine to start until we learn how common this use case is

Other caveats we should consider:

- What would this chart look like for a huge number of distinct app_names? How many applications are typically making requests to a cluster at one time?

cc @couchand 

Jira issue: CRDB-4699

**Comment by piyush-singh** [comment]
We saw another request for this come in today from a customer. When investigating an issue with the number of connections to a cluster steady increasing from 100 connections to 1500 connections over time, a user had to manually create a time series to represent this using influxdb/grafana. After creating this time series, the user compared # of connections over time to # of web requests, database hardware metrics, etc. to determine the root cause for the spikes in # of connections. The user noted that the number of distinct application names used in their cluster was only 5, which helps us understand what a time series version of this potentially might look like (plotting connections by app_names might be feasible). This still leaves the concern called out above of creating a new method to dynamically chart time series based on user inputs (e.g. distinct app_name values).

A possible approach that might work as an interim solution until we figure out the right UX for this is to at least show a snapshot of the current number of connections using something along the lines of `SELECT application_name, count(*) FROM [SHOW CLUSTER SESSIONS] group by application_name order by count(*) desc;`. At the very least we can expose this as a debug page to track the _current_ number of connections.

It is also worth noting that tracking the number of connections over time by application name will be a critical user story for our managed offering.

**Comment by bladefist** [comment]
@piyush-singh This would be great! A much lower priority query, but perhaps still helpful to some, is:

`SELECT` substring(client_address,0, position(':' in client_address)), count(*) FROM [SHOW CLUSTER SESSIONS] group by substring(client_address,0, position(':' in client_address)) order by count(*) desc;`

**Comment by thtruo** [comment]
Heads up @kevin-v-ngo this looks like it falls into SQL Observability's wheelhouse so I've updated the t-label. Let me know if you have any objections to this change

**Comment by kevin-v-ngo** [comment]
Thanks Tommy. Updated the project so that this falls under our triage board as well.
