### ISSUE TITLE
kv: too much time spent in ScanResponse.combine

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#33200]
While testing a scan over a table with large values, I noticed that a very large portion of CPU time is spent in `ScanResponse.combine`, concatenating byte slices of multiple range's scan responses.

This is totally inefficient and silly. We should improve this situation by "combining" the two byte slices into a slice of slices, rather than appending the slices together.

This might improve scan speed significantly.

![image](https://user-images.githubusercontent.com/43821/50114950-f89a3280-0213-11e9-865a-7feb3415669e.png)

**Comment by jordanlewis** [comment]
I hacked something up for this - it provides a 50% speedup over my test dataset.

Before:
```
root@:26257/defaultdb> select count(*) from t;
  count
+-------+
  10249
(1 row)

Time: 17.098126s
```

After:
```
root@:26257/defaultdb> select count(*) from t;
  count
+-------+
  10249
(1 row)

Time: 10.53048s
```

**Comment by knz** [comment]
cc @nvanbenschoten
