### ISSUE TITLE
Is memory engine supported?

### ISSUE THREAD

**Issue by sunfaces** [cockroachdb/cockroach#3327]
hi all:
    I'm looking for a distributed cache server which supports sql parsing,
   the flow is as below : 
          client  -> sends sql request -> cache server -> cached -> mysql  
   so,  what about this one being a cache server?
   thanks for telling.

**Comment by zhaoyta** [comment]
ignite?

**Comment by knz** [comment]
Hello @sunfaces 
CockroachDB does not offer a caching interface that lets SQL queries through to another DB server.
The product is intended for use as a backing store, i.e. to be placed at the rightmost side of your flow diagram.

However, as our product approaches its first official release, you will be able to let go of this caching architecture altogether: it will be possible to deploy as many cockroachdb servers as needed in your application, and they will synchronize automatically to each other and act as mutual caches, eliminating entirely the need for a separation between a cache and a database.
Stay tuned!
