### ISSUE TITLE
roachtest: Disable error reporting to sentry

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#33275]
It appears that crashes in roachtests get reported to sentry. For example, we see a number of crash reports for [commit 1cd7dcfe1](https://sentry.io/cockroach-labs/cockroachdb/?query=rev%3A%221cd7dcfe1bbf487a714c7f00a5dd709360dbe9e4%22). This was not an alpha release, so it seems unlikely that a regular user would land on a build of this commit with reporting enabled, but this commit [was chosen for that night's roachtest run](https://teamcity.cockroachdb.com/viewLog.html?buildId=1049151&buildTypeId=Cockroach_Nightlies_WorkloadNightly&tab=buildChangesDiv). (as additional evidence that these reports are from roachtests, we see assertions in the hlc package that are expected failures in the roachtests, but are  not otherwise enabled by default)

These crash reports are occasionally useful (#33016, for example), but when they are expected failures there is no reason to send them to sentry. We should instead disable crash reporting and ensure that unexpected failures get reported by roachtest itself instead of going to sentry.

**Comment by petermattis** [comment]
@bdarnell Do you know off-hand how to disable reporting to sentry?

Paging @dt.

**Comment by tbg** [comment]
See the env vars in crash_reporting.go.

**Comment by petermattis** [comment]
Thanks @tbg. Looks like I just need to set `COCKROACH_CRASH_REPORTS` to the empty string.

**Comment by dt** [comment]
Yep, that'll work.

Alternatively, we already disable reporting outside of release binaries -- should we be using dev binaries for roachtests instead of release binaries?

**Comment by petermattis** [comment]
> Alternatively, we already disable reporting outside of release binaries -- should we be using dev binaries for roachtests instead of release binaries?

Let me investigate that. Some of the roachtests are testing performance. I think this is done based on the channel. I'm not sure what channel we use for the roachtests.

**Comment by petermattis** [comment]
Ah, we use the `Publish Bleeding Edge` binaries for the nightly roachtests. Seems better to have `roachprod` add the `COCKROACH_CRASH_REPORTS` env var by default.

**Comment by bdarnell** [comment]
We probably want to disable all reporting with COCKROACH_SKIP_ENABLING_DIAGNOSTIC_REPORTING (I thought we already did that, actually. Are we just relying on the fact that these clusters are too short-lived to mess up our telemetry?)
