### ISSUE TITLE
sql: add telemetry for unsupported JSON

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#33285]
- [ ] `json_to_recordset(json)`
- [ ] `jsonb_to_recordset(jsonb)`
- [ ] `json_populate_recordset(base anyelement, from_json json)`
- [ ] `jsonb_populate_recordset(base anyelement, from_json jsonb)`
- [ ] `json_object_agg`
- [ ]  ensure we have JSON and JSONB aliases

This should be all unsupported Postgres JSONB cc @justinj to confirm

**Comment by justinj** [comment]
lgtm
