### ISSUE TITLE
sql,ui: provide a feature to reset the statements page immediately

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#33315]
I tried to reset the statements page on the UI by following the instructions in the info box:

![image](https://user-images.githubusercontent.com/43821/50324112-277e0600-04ab-11e9-906a-47dfe11ab12a.png)

but it didn't work. I set that value to 1 second, and nothing changed in the UI. I also tried setting the `diagnostics.forced_stat_reset.interval` setting to 1 second which didn't do anything.

Is that setting really about the statements page? It sounds slightly different - either way, it didn't work. Is this a bug in the setting, or the docs on that page, or something else?

**Comment by knz** [comment]
cc @dt 
I hope we havent broken anything in the backend

**Comment by knz** [comment]
@jordanlewis I have investigated this. 

1) The settings (both of them) work as intended, however the new interval only kicks in after the current waiting period (using the previous configured value) is complete.  We do not have a mechanism to force-activate the event when the interval is decreased. With the current implementation it would be hard to do.

2) I think there is a mismatch between what you want to do ("clear the statement stats") and what you were reading in the UI ("how to change the clear frequency").

I think the current behavior (where a new interval only becomes active after the current interval elapses) is adequate/appropriate for the goal announced in the UI ("how to change the frequency")

Meanwhile, there is no feature currently that answer the question "how to clear the statement stats NOW".

What matters most to you? Do you think we should change the title of the issue to "provide a feature that enables users to clear stats immediately"?

**Comment by jordanlewis** [comment]
Ok, this makes sense. Yes, we should add a feature to clear the statement stats now. That is what was missing for the user that prompted me to file this issue.

**Comment by piyush-singh** [comment]
We're currently working on changing how these stats are persisted, I'll add a user story to capture the need to clear stats immediately.

**Comment by couchand** [comment]
OTOH what's the user's goal in clearing these stats at all?  I do understand wanting some management settings to control the storage space used for insight tools like this, which could potentially include an option to clear the data (though I would expect you'd want that to apply to lots of systems beyond just this page).

@jordanlewis, I'd like to know more about what they're trying to accomplish that they want to clear them on-demand.  I suspect it's to "zero them out", but that seems a bit at odds with the direction we're going here.

**Comment by jordanlewis** [comment]
The use case was that they changed the workload/schema/something and were expecting to see a big difference in latency via the statements page, but couldn't find a way to see a before/after. Clearing it seems reasonable. Yes there are timeseries but there's more going on in the cluster than just the statement they were looking for.

**Comment by couchand** [comment]
Great.  That use-case has already been considered and is core to our goals with this moving forward.  I'd much rather take a holistic approach rather than continuing to try to pile on workarounds to our abusing the telemetry data for this purpose.

**Comment by couchand** [comment]
I'm already made uncomfortable by that tooltip: it's telling people to change their diagnostics reporting interval, which will affect the quality of the data we're getting.

**Comment by piyush-singh** [comment]
Reviving this issue as the work in #45082 makes this much simpler to implement.

**Comment by awoods187** [comment]
@asubiotto can you PTAL at this and help determine what we'd need to do here to support this capability?

**Comment by jordanlewis** [comment]
Let's start with a function called `crdb_internal.reset_statement_statistics()` that immediately zeroes all statement statistics counters. There is already code that does this reset that lives on the sql `Server` called `Server.ResetSQLStats`.

The challenge is plumbing this into something that can hang off of an `EvalContext` for a builtin. It's kind of a tricky problem.

Once we have this, we can work on adding a call to this to `adminServer` (or its successor).

**Comment by Azhng** [comment]
Just to clarify, `Server.ResetSQLStats` resets both statement stats and txn stats. Is that what we want? Or we *only* want to clear the statement stats in this case?

**Comment by asubiotto** [comment]
I think it'd probably be better to reset all stats. We can change that if there's need for it, but I think it doesn't make sense to have to think in different time horizons on the different pages (i.e. my transactions have stats since 2 hours ago, but my statement stats were reset 40 mins ago)

**Comment by Annebirzin** [comment]
@Azhng Adding links to designs for the 'Clear transactions' and 'Clear statements' buttons [here](https://www.figma.com/file/MoSPFkEyJfGipCmQvvLg1a/obsrv-query-performance?node-id=1763%3A25247) 

![Screen Shot 2021-03-29 at 11 40 20 AM](https://user-images.githubusercontent.com/51920721/112862838-2ffb1900-9084-11eb-88d4-01bb37ac96da.png)
![Screen Shot 2021-03-29 at 11 39 46 AM](https://user-images.githubusercontent.com/51920721/112862847-31c4dc80-9084-11eb-90a6-322a8e261cf2.png)

**Comment by Azhng** [comment]
Thanks for the update!

Though I think we have a slight issue here, the current backend RPC endpoint resets both statement and txn stats upon invocation. The rationale is what Alfonso mentioned in the previous comment: it would be a bit confusing to think in different time horizons on different pages. 

Do you think it would make sense to have a `Clear Stats` button on both pages that clears both statement and transaction stats?

**Comment by Annebirzin** [comment]
Ah ok, updated to `Clear SQL stats` so it's generic across both pages

![Screen Shot 2021-03-29 at 12 00 59 PM](https://user-images.githubusercontent.com/51920721/112865191-86695700-9086-11eb-98ee-b79c7ce7f14a.png)

**Comment by Azhng** [comment]
Looks great, I will get started implement this now. 😃

**Comment by awoods187** [comment]
This is great! I wonder if we can get text to appear on hover that explains its both the transactions and statements pages? Even if not, this is awesome.

**Comment by Annebirzin** [comment]
Yep agree it would be nice to add some messaging to explain this - maybe we could add a sentence to the current tooltip:

```
Statement history is cleared once an hour by default, which can be configured with the cluster setting
 diagnostics.reporting.interval.

Clicking ‘Clear SQL stats’ will reset SQL stats on the statements and transactions pages.
```

cc @ianjevans
