### ISSUE TITLE
sql: Inconsistent result count when taking UPSERT fast path

### ISSUE THREAD

**Issue by andy-kimball** [cockroachdb/cockroach#33314]
Repro:
```
root@:26257/defaultdb> create table k (k int primary key);
CREATE TABLE

root@:26257/defaultdb> upsert into k (k) values (1);
INSERT 1

root@:26257/defaultdb> upsert into k (k) values (1);
INSERT 1

root@:26257/defaultdb> drop table k;
DROP TABLE

root@:26257/defaultdb> create table k (k int primary key, index(k));
CREATE TABLE

root@:26257/defaultdb> upsert into k (k) values (1);
INSERT 1

root@:26257/defaultdb> upsert into k (k) values (1);
INSERT 0
```

EXPECTED: Adding a secondary index should not change the results of these statements.

ACTUAL: With no secondary index, the 2nd `UPSERT` returns `INSERT 1`. With a secondary index, the 2nd `UPSERT` returns `INSERT 0`.

**Comment by knz** [comment]
@andy-kimball thanks for finding this! This is again a plain bug, albeit just in the result count (the resulting table contents are unaffected of course).

I think this tells us to revisit the semantics of the resulting row count.

**Comment by andy-kimball** [comment]
Note that this problem only repros in the edge case where # primary key columns = # columns in table. When that is true, there are no columns to update, hence `INSERT 0`.

I believe that the right fix for this is to always return `INSERT 1`, even if technically no row was updated. Otherwise, `INSERT 0` will be a surprising edge case that only occurs when # primary key columns = # columns in table.

Furthermore, standardizing on `INSERT 0` will run into issues when mutations are in-progress, because there are implicit extra columns. Therefore, # primary key columns < # columns in table, so our code would return `INSERT 1` even though no user-visible columns have changed. Better to just be consistent in always returning `INSERT 1` rather than trying to differentiate low value edge cases that could theoretically return `INSERT 0`.

**Comment by andy-kimball** [comment]
NOTE: This works correctly with the CBO enabled. Recommend we close as "won't fix" for the heuristic planner, since it's been this way for a long time and we're deprecating it.

**Comment by jordanlewis** [comment]
Closing as wontfix for hp, as you suggest.
