### ISSUE TITLE
sql: Incorrect results when inserting mix of conflicting and non-conflicting rows

### ISSUE THREAD

**Issue by andy-kimball** [cockroachdb/cockroach#33313]
Repro:
```
root@:26257/defaultdb> CREATE TABLE ex(
foo INT PRIMARY KEY,
bar INT UNIQUE,
baz INT);

root@:26257/defaultdb> INSERT INTO ex(foo,bar,baz) VALUES (1,1,1);
INSERT 1

root@:26257/defaultdb> INSERT INTO ex(foo,bar,baz) VALUES (1,2,1), (3,2,2) ON CONFLICT DO NOTHING;
INSERT 0

root@:26257/defaultdb> select * from ex;
  foo | bar | baz
+-----+-----+-----+
    1 |   1 |   1
(1 row)
```

EXPECTED: The second `INSERT` should have inserted one row with values (3,2,2). This is what Postgres does.

ACTUAL: The second value in the `VALUES` clause conflicts with the first and is therefore not added. But these are incorrect semantics, since conflicts should be determined with respect to the data at the start of the transaction, not after one or more mutations have occurred.

**Comment by knz** [comment]
Even with the chosen semantics in CockroachDB, the current behavior in CockroachDB is bogus and is clearly a bug. Thank you for finding it. I do agree it is a problem but it is a problem of implementation not of semantics.

The first row (1,2,1) conflicts with the existing row in the table so should not be added. Then the 2nd row (3,2,2) does not conflict with the table and should be added. This pg-compatible behavior is also what the current CockroachDB semantics would mandate. I want to treat this as a bug concurrently (and independently) to the discussion of desired semantics.

**Comment by knz** [comment]
After investigation I found the bug. It's a rather simple mistake really. Fixing.

**Comment by knz** [comment]
My gosh also the code is just wrong with inverted indexes too...
