### ISSUE TITLE
cli: include collected goroutine dumps in debug zip

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#33318]
This should follow a pattern similar to https://github.com/cockroachdb/cockroach/pull/26797.

**Comment by petermattis** [comment]
I like this idea. Note for implementor: be mildly careful on how frequently this is done as generating a goroutine dump requires temporarily stopping all goroutines. We've previously seen this cause hiccups in performance if done on a regular cadence.

**Comment by tbg** [comment]
I was thinking something like

- poll `runtime.NumGoroutine()` at some regular enough interval (10s?) and keep the last minute worth of values
- if the current value is at least double the max seen over the last minute, trigger a dump
- delete all but the most recent 10 dumps

**Comment by petermattis** [comment]
Sounds reasonable.

> delete all but the most recent 10 dumps

The goroutine dumps are not large. We could probably keep more than 10.

**Comment by tbg** [comment]
> The goroutine dumps are not large. We could probably keep more than 10.

Now that we're dealing with goroutine leaks where these dumps can end up in the range of 10^6 goroutines, I'm not convinced this is true. Perhaps better to budget by file size (i.e. keep any number of dumps, as long as their aggregate size is below X (10mb?), then delete smaller files first.

**Comment by tbg** [comment]
@stevenliang16 is working on this.

**Comment by tbg** [comment]
Re-titling so that this is now about also including the dumps in `debug zip`. This is completely analogous to heap profiles, see

https://github.com/cockroachdb/cockroach/blob/447fe7d6023a3db7473445944ae3693f0f286d17/pkg/server/status.go#L609-L664

and

https://github.com/cockroachdb/cockroach/blob/63448fb1d49b679cae01d57b18e38b5cebe54d6e/pkg/cli/zip.go#L303-L323

**Comment by giorgosp** [comment]
Hi, I have started looking into this. Seems like I just have to use the `GoroutineDumper` in a new switch case in `server/status.go#GetFiles` and add a request for the goroutines dump in `cli/zip.go#runDebugZip`.

**Comment by tbg** [comment]
Yep, that's right! You'll need to add the new status type in `serverpb/status.proto`. Thanks for working on this.

**Comment by giorgosp** [comment]
Hi, I am looking how to test the goroutine dump fetching. I see that the `pkg/server/status_test.go#TestStatusLocalFileRetrieval` only tests that no error is returned and is expecting 0 heap profile files to be returned. Also, `pkg/cmd/roachtest/cluster.go#FetchDebugZip` doesn't check the contents of the downloaded zip file. Is there some test that I am missing that checks the contents of the downloaded debug zip? Thanks!

**Comment by tbg** [comment]
Hi @giorgosp, I think you're right that the testing here is a little poor. Could you do adapt `TestStatusLocalFileRetrieval` as follows:

1. don't call `startServer`, instead just lift the `serverutils.StartServer` call from that method into the test directly, because
2. you want to use `StoreSpecs` that are not in-memory, so basically you want to give each node a `StoreSpec` that has `Path` set
3. you get the path from `testutils.TempDir()`,
4. now you can test that the endpoints actually read files by putting marker files (i.e. just files containing some string "hey i'm a heap profile" into the right place, and checking that the endpoints return them.

Let me know if you have any questions!

**Comment by giorgosp** [comment]
Hi @tbg, thank you for your quick reply!

I have opened a pull request against my fork, https://github.com/giorgosp/cockroach/pull/1, looking forward to your comments.

Also, I notice that the `debug zip` command explicitly asks for a heap profile run and also downloads any other heap profile files created by the heap profiler. Do we want a similar behaviour for the goroutines dump?

**Comment by tbg** [comment]
> looking forward to your comments.

Just open the PR against the main fork, please!

> Also, I notice that the debug zip command explicitly asks for a heap profile run

We already have code in `debug zip` that fetches the current stacks, so that's already present. Just fetching the previously saved goroutine dumper files will need to be added.

Thanks!
