### ISSUE TITLE
ui: network diagnostics page doesn't work when one node times out

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#33321]
Running 3 node cluster on which the first node has a "timeout" toxic enabled:

```
$ ./toxiproxy-cli-darwin-amd64 --host localhost:8475 l
Name			Listen		Upstream		Enabled		Toxics
======================================================================================
cockroach		[::]:36257	127.0.0.1:26257		enabled		2
```

(n1 is advertising :36257). The network diag page times out:

http://localhost:26260/#/reports/network

Should repro easily via `./bin/roachtest run --local network/tpcc --debug` once https://github.com/cockroachdb/cockroach/pull/33282 has merged and is likely straightforward to fix on the server side.

**Comment by couchand** [comment]
Strange, I would expect that to show `X`s.  @BramGruneir?

**Comment by tbg** [comment]
(something to note is that this is injecting tcp-level timeouts, which is a bit mean and probably terrible for lots of other stuff that isn't stmt timeouts, perhaps even messing with grpc context cancellation)

**Comment by couchand** [comment]
Well, since the purpose of this page is to diagnose network issues, it absolutely needs to be resilient to network issues.

(your explanation is helpful, and I'm glad we're being meaner in our testing!)

**Comment by tbg** [comment]
Yep! Just wanted to point out that it does work in simpler cases (for example when the node is just down).

**Comment by BramGruneir** [comment]
So it should be resilient to network flakiness and failures, that's kind of the whole point.  There must be a timeout that's not being abided by.  

And yes, it should show up as X.

I don't have the bandwidth to investigate this, but if it's easy to repro, I can help out as a secondary.
