### ISSUE TITLE
sql: Inconsistent UPSERT behavior when DEFAULT columns are present

### ISSUE THREAD

**Issue by andy-kimball** [cockroachdb/cockroach#33327]
Example #1: Column 'b' has no default value
```
root@:26257/defaultdb> create table abc (a int primary key, b int, c int);
CREATE TABLE

root@:26257/defaultdb> insert into abc values (1, 1, 1);
INSERT 1

root@:26257/defaultdb> upsert into abc (a, c) values (1, 2);
INSERT 1

root@:26257/defaultdb> select * from abc;
  a | b | c
+---+---+---+
  1 | 1 | 2
```

Example #2: Column 'b' has default value
```
root@:26257/defaultdb> create table abc (a int primary key, b int default(10), c int);
CREATE TABLE

root@:26257/defaultdb> insert into abc values (1, 1, 1);
INSERT 1

root@:26257/defaultdb> upsert into abc (a, c) values (1, 2);
INSERT 1

root@:26257/defaultdb> select * from abc;
  a | b  | c
+---+----+---+
  1 | 10 | 2
```

Example #3: Column 'b' has NULL default value
```
root@:26257/defaultdb> create table abc (a int primary key, b int default(null), c int);
CREATE TABLE

root@:26257/defaultdb> insert into abc values (1, 1, 1);
INSERT 1

root@:26257/defaultdb> upsert into abc (a, c) values (1, 2);
INSERT 1

root@:26257/defaultdb> select * from abc;
  a |  b   | c
+---+------+---+
  1 | NULL | 2
```

EXPECTED: All three results should be the same, namely `(1, 1, 2)`. If a column is not explicitly listed in the upsert, it should not be updated. Our docs (https://www.cockroachlabs.com/docs/stable/upsert.html) imply that only explicitly listed insert columns are translated into update columns. In addition, we should always treat nullable columns as if they were `DEFAULT(NULL)` - there should never be a semantic difference that depends on whether `DEFAULT(NULL)` is present or not. As another piece of data, VoltDB always returns `(1, 1, 2)`.

ACTUAL: Each of the three results is different, depending on the DEFAULT value for column 'b'.

**Comment by knz** [comment]
Good find. Thank you for filing.

**Comment by andy-kimball** [comment]
Here's another related case, showing the behavior when insert columns are not explicitly specified:
```
root@:26257/defaultdb> create table abc (a int primary key, b int, c int);
CREATE TABLE

root@:26257/defaultdb> insert into abc values (1, 1, 1);
INSERT 1

root@:26257/defaultdb> upsert into abc values (1, 2);
INSERT 1

root@:26257/defaultdb> select * from abc;
  a | b |  c
+---+---+------+
  1 | 2 | NULL
```
So we do insert NULL values in that case, as if the user had specified all columns.

**Comment by andy-kimball** [comment]
NOTE: This works correctly with the CBO enabled. Recommend we close as "won't fix" for the heuristic planner, since it's been this way for a long time and we're deprecating it.

**Comment by jordanlewis** [comment]
Closing as wont fix.
