### ISSUE TITLE
sql: Upsert fails when dropping computed column that depends on another dropped column

### ISSUE THREAD

**Issue by andy-kimball** [cockroachdb/cockroach#33338]
An error occurs when dropping a computed column along with a column that it depends on. Until the schema change is complete, Upsert operations fail. Repro:
```
root@:26257/defaultdb> create table xyz (x int primary key, y int default(2), z int as (x+y) stored);
CREATE TABLE

root@:26257/defaultdb> begin; alter table xyz drop column y, drop column z;
ALTER TABLE

root@:26257/defaultdb  OPEN> insert into xyz (x) values (1) on conflict do update set x=10;
pq: column "y" does not exist
```

EXPECTED: No error. A new row should be created with x=1, as well as default values for the mutation columns.

ACTUAL: `column "y" does not exist` error.

CC: @vivekmenezes

**Comment by andy-kimball** [comment]
NOTE: This works correctly with the CBO enabled. Recommend we close as "won't fix" for the heuristic planner.

**Comment by jordanlewis** [comment]
Closing as wont fix for HP.
