### ISSUE TITLE
Panic on aggregate function with window: SELECT SUM(_) OVER (ORDER BY _) FROM _

### ISSUE THREAD

**Issue by blkerby** [cockroachdb/cockroach#33340]
**Describe the problem**

I'm seeing a panic when aggregate functions (e.g., SUM, AVG) are used with a window. For example, if I set up a table like this:

```
create table test_table3 (a int, b int);
insert into test_table3 values (0, 10), (1, 11);
```
Then the following statement causes a panic: 

```
select sum(b) over (order by a) from test_table3;
```

This was on CockroachDB v2.1.1, and I tried upgrading to v2.1.3 and am seeing the same problem. Here is a dump of the logs:

> E181224 00:38:10.963782 16082 sql/conn_executor.go:636  [n1,client=100.112.0.11:34314,user=root] a SQL panic has occurred while executing "SELECT avg(b) OVER (ORDER BY a) FROM test_table3": runtime error: index out of range
> E181224 00:38:10.963916 16082 util/log/crash_reporting.go:203  [n1,client=100.112.0.11:34314,user=root] a panic has occurred!
> E181224 00:38:10.964418 16082 util/log/crash_reporting.go:477  [n1,client=100.112.0.11:34314,user=root] Reported as error 2dc5897bbbb3498f927858aa9c74565f
> panic: runtime error: index out of range [recovered]
> 	panic: panic while executing 1 statements: SELECT avg(_) OVER (ORDER BY _) FROM _; caused by runtime error: index out of range
> 
> goroutine 16082 [running]:
> github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc42b452000, 0x30326a0, 0xc427cfab80, 0x2770280, 0x4231d70)
> 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:650 +0x36f
> github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc42b452000, 0x30326a0, 0xc427cfab80)
> 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:387 +0x61
> panic(0x2770280, 0x4231d70)
> 	/usr/local/go/src/runtime/panic.go:502 +0x229
> github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).bufferRow(0xc420959500, 0x3032760, 0xc428ff7890, 0xc4291db1e0, 0x2, 0x2, 0xc42677c2ea, 0x1, 0x1, 0x424e140, ...)
> 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:892 +0x355
> github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*commandResult).AddRow(0xc429266c60, 0x3032760, 0xc428ff7890, 0xc4291db1e0, 0x2, 0x2, 0x4853b80, 0x3048940)
> 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/command_result.go:216 +0x189
> github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLReceiver).Push(0xc42a06a500, 0xc42ad0ae28, 0x2, 0x2, 0x0, 0x2)
> 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:534 +0x8bc
> github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*accountClearingRowReceiver).Push(0xc429005170, 0xc42ad0ae28, 0x2, 0x2, 0x0, 0x2)
> 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:279 +0x83
> github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*copyingRowReceiver).Push(0xc42ad0ae00, 0xc428c32fc0, 0x2, 0x2, 0x0, 0xc400000000)
> 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go:659 +0x191
> github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.Run(0x3032760, 0xc429004e70, 0x303cde0, 0xc420931000, 0x300f720, 0xc42ad0ae00)
> 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go:173 +0x5c
> github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).Run(0xc420931000, 0x3032760, 0xc429004e70, 0x0)
> 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:731 +0x98
> github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).StartSync(0xc42740aa80, 0x3032760, 0xc429004e70, 0x2c30f98, 0xc420b54fc0, 0x300f3e0)
> 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:607 +0x191
> github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc420b77a00, 0xc428c32f00, 0xc429266750, 0xc42c0748d8, 0xc42a06a500, 0xc42b4524b0, 0x0)
> 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:253 +0x879
> github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0xc420b77a00, 0x3032760, 0xc428ff7890, 0xc42b4524b0, 0xc428c32f00, 0xc429266750, 0x3025fa0, 0xc428a69d40, 0xc42a06a500)
> 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:758 +0x24c
> github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc42b452000, 0x3032760, 0xc428ff7890, 0xc42b452418, 0x3, 0x7f9cc47ce1e8, 0xc429266c60, 0xc428ff7401, 0x1, 0x1)
> 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:982 +0x2d8
> github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc42b452000, 0x3032760, 0xc428ff7890, 0x3035de0, 0xc428263600, 0xc428ff7470, 0x1, 0x1, 0xc4267b5890, 0x30, ...)
> 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:824 +0xa8a
> github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc42b452000, 0x3032760, 0xc428ff7890, 0x3035de0, 0xc428263600, 0xc428ff7470, 0x1, 0x1, 0xc4267b5890, 0x30, ...)
> 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:402 +0xb3b
> github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc42b452000, 0x3032760, 0xc428ff7890, 0x3035de0, 0xc428263600, 0xc428ff7470, 0x1, 0x1, 0xc4267b5890, 0x30, ...)
> 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:96 +0x341
> github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc42b452000, 0x30326a0, 0xc427cfab80, 0xc420d300d8, 0x5400, 0x15000, 0xc420d30170, 0xc42580da30, 0x0, 0x0)
> 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1173 +0x1400
> github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc4209fe000, 0x30326a0, 0xc427cfab80, 0xc42b452000, 0x5400, 0x15000, 0xc420d30170, 0xc42580da30, 0x0, 0x0)
> 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:389 +0xce
> github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl.func4(0xc4209fe000, 0x30326a0, 0xc427cfab80, 0xc42b452000, 0x5400, 0x15000, 0xc420d30170, 0xc42580da30, 0xc42580da40, 0xc4277ba060)
> 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:313 +0x81
> created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl
> 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:312 +0x107c
> 

**Expected behavior**
I expected the query to complete successfully, with a result being a column with values 10 and 21 (as it does in PostgreSQL.)

**Environment:**
 - CockroachDB 2.1.1, 2.1.3
 - Server OS: Debian 8.9 (Docker)
 - Client app: PyCharm JDBC

**Additional context**
The cluster returns to normal operation after the node restarts.

**Comment by jordanlewis** [comment]
Thanks very much for the easy reproduction.

**Comment by jordanlewis** [comment]
Interestingly, this doesn't trivially reproduce on `master`, suggesting it's been fixed but not backported. I'll bisect.

**Comment by blkerby** [comment]
Interesting, when I try it on `master` (cc2bf701b5acea511860a62a85f9e48fc00c7628) I get the same panic. I'm building the Docker image like this (after cloning the repo):
```
cd cockroach &&  \
		./build/builder.sh mkrelease linux-gnu && \
		cp ./cockroach-linux-2.6.32-gnu-amd64 build/deploy/cockroach && \
		cd build/deploy && \
			docker build -t ${IMAGE}:${TAG} .
```

**Comment by jordanlewis** [comment]
Do you have any special cluster or session settings set? I still can't reproduce this.

```
[14:39]% ./cockroach demo
#
# Welcome to the CockroachDB demo database!
#
# You are connected to a temporary, in-memory CockroachDB
# instance. Your changes will not be saved!
#
# Web UI: http://127.0.0.1:61581
#
# Server version: CockroachDB CCL v2.1.3-37-g3948b18f3f (x86_64-apple-darwin17.7.0, built 2018/12/24 19:31:34, go1.11.2) (same version as client)
# Cluster ID: eae4b221-23e5-4fd8-b11e-f6d7a87b9ac8
#
# Enter \? for a brief introduction.
#
root@127.0.0.1:61580/defaultdb> create table test_table3 (a int, b int);
CREATE TABLE

Time: 4.985ms

root@127.0.0.1:61580/defaultdb> insert into test_table3 values (0, 10), (1, 11);
INSERT 2

Time: 7.033ms

root@127.0.0.1:61580/defaultdb> select sum(b) over (order by a) from test_table3;
  sum
+-----+
   10
   21
(2 rows)

Time: 3.072ms
```

**Comment by blkerby** [comment]
I'm running a 3-node cluster using a Kubernetes StatefulSet. When I exec into one of the containers and run the commands in `cockroach demo`, it runs fine, the same as what you are seeing:

```
root@cockroachdb-0:/cockroach# ./cockroach demo
#
# Welcome to the CockroachDB demo database!
#
# You are connected to a temporary, in-memory CockroachDB
# instance. Your changes will not be saved!
#
# Web UI: http://127.126.237.36:45937
#
# Server version: CockroachDB CCL v2.2.0-alpha.20181217-283-gcc2bf70 (x86_64-unknown-linux-gnu, built 2018/12/24 05:36:49, go1.10.7) (same version as client)
# Cluster ID: f78300de-1744-4f83-88da-656f661be8be
#
# Enter \? for a brief introduction.
#
root@127.126.237.36:35993/defaultdb> create table test_table3 (a int, b int);
CREATE TABLE

Time: 3.950886ms

root@127.126.237.36:35993/defaultdb> insert into test_table3 values (0, 10), (1, 11);
INSERT 2

Time: 5.979928ms

root@127.126.237.36:35993/defaultdb> select sum(b) over (order by a) from test_table3;
  sum  
+-----+
   10  
   21  
(2 rows)

Time: 701.645µs
```
The appearance of `sql.(*DistSQLReceiver).Push` in the stack trace was making me wonder if this could be specific to distributed execution, but when I use `cockroach sql` to connect to the cluster and run the statements like that, it works fine. So this suggests it could be something different in my client that is a factor, like you suggest. I'm using PyCharm, which doesn't have specific CockroachDB support and so is treating it as a Postgres database, which I know has some issues (for instance, PyCharm complains because it can't find some of the pg_catalog tables that it looks for to get table metadata). Here's the dump of "SHOW SESSION ALL" from PyCharm:

```
variable,value
application_name,PyCharm 2018.3.1
bytea_output,hex
client_encoding,UTF8
client_min_messages,notice
crdb_version,"CockroachDB OSS v2.2.0-alpha.20181217-283-gcc2bf70 (x86_64-unknown-linux-gnu, built 2018/12/24 05:36:49, go1.10.7)"
database,ui_events
datestyle,"ISO, MDY"
default_int_size,8
default_transaction_isolation,serializable
default_transaction_read_only,off
distsql,auto
experimental_enable_zigzag_join,off
experimental_force_lookup_join,off
experimental_force_split_at,off
experimental_optimizer_updates,off
experimental_serial_normalization,rowid
experimental_vectorize,off
extra_float_digits,3
force_savepoint_restart,off
integer_datetimes,on
intervalstyle,postgres
max_index_keys,32
node_id,1
optimizer,on
search_path,public
server_encoding,UTF8
server_version,9.5.0
server_version_num,90500
session_user,root
sql_safe_updates,off
standard_conforming_strings,on
statement_timeout,0
timezone,UTC
tracing,off
transaction_isolation,serializable
transaction_priority,normal
transaction_read_only,off
transaction_status,NoTxn
```
The session settings look the same in `cockroach sql` though:
```
              variable              |                                                       value                                                         
+-----------------------------------+--------------------------------------------------------------------------------------------------------------------+
  application_name                  | $ cockroach sql                                                                                                     
  bytea_output                      | hex                                                                                                                 
  client_encoding                   | UTF8                                                                                                                
  client_min_messages               | notice                                                                                                              
  crdb_version                      | CockroachDB OSS v2.2.0-alpha.20181217-283-gcc2bf70 (x86_64-unknown-linux-gnu, built 2018/12/24 05:36:49, go1.10.7)  
  database                          | ui_events                                                                                                           
  datestyle                         | ISO, MDY                                                                                                            
  default_int_size                  | 8                                                                                                                   
  default_transaction_isolation     | serializable                                                                                                        
  default_transaction_read_only     | off                                                                                                                 
  distsql                           | auto                                                                                                                
  experimental_enable_zigzag_join   | off                                                                                                                 
  experimental_force_lookup_join    | off                                                                                                                 
  experimental_force_split_at       | off                                                                                                                 
  experimental_optimizer_updates    | off                                                                                                                 
  experimental_serial_normalization | rowid                                                                                                               
  experimental_vectorize            | off                                                                                                                 
  extra_float_digits                | 2                                                                                                                   
  force_savepoint_restart           | off                                                                                                                 
  integer_datetimes                 | on                                                                                                                  
  intervalstyle                     | postgres                                                                                                            
  max_index_keys                    | 32                                                                                                                  
  node_id                           | 1                                                                                                                   
  optimizer                         | on                                                                                                                  
  search_path                       | public                                                                                                              
  server_encoding                   | UTF8                                                                                                                
  server_version                    | 9.5.0                                                                                                               
  server_version_num                | 90500                                                                                                               
  session_user                      | root                                                                                                                
  sql_safe_updates                  | off                                                                                                                 
  standard_conforming_strings       | on                                                                                                                  
  statement_timeout                 | 0                                                                                                                   
  timezone                          | UTC                                                                                                                 
  tracing                           | off                                                                                                                 
  transaction_isolation             | serializable                                                                                                        
  transaction_priority              | normal                                                                                                              
  transaction_read_only             | off                                                                                                                 
  transaction_status                | NoTxn                                                                                                               
(38 rows)
```
The only difference I saw was in `extra_float_digits`, which doesn't seem relevant; I tried setting it to `3` in `cockroach sql` and the statements still ran fine. 

I still consistently get a panic when I run the statement `select sum(b) over (order by a) from test_table3` in PyCharm. Any other ideas for how the see what the difference might be between what PyCharm is doing vs. what `cockroach sql` is doing?

**Comment by jordanlewis** [comment]
Very interesting! It probably has to do with prepared statements then, if you can only reproduce from the IDE. You could enable statement logging on your gateway node to find out more about what's going on.

**Comment by jordanlewis** [comment]
Looks like the problem is that, in this case with window functions, the distsql physical planner produces a distsql spec with a different output row width than the equivalent planNode tree's planColumns. This bug is masked by the ordinary sql shell, which doesn't set its expected pgwire result types like a bind+executed statement does, and therefore can make it through this code path without crashing. What's less clear immediately is why nothing else goes wrong with a mismatched result row.

Either way, this should be pretty straightforward to fix.

Investigating this problem also led me to another issue - our handling of hidden columns with pgwire, which is also wrong. See #33352.

**Comment by nexdrew** [comment]
FWIW I was recently testing an upgrade from 2.0.5 to 2.1.3, and I think I'm seeing the same problem on a few `count ... group by` queries:

```
E181230 23:26:39.933485 322 sql/conn_executor.go:636  [n1,client=172.26.0.1:51510,user=root] a SQL panic has occurred while executing "SELECT mpr.comp_plan_id, count(mpr.rep_id) AS count FROM map_comp_plan_rep AS mpr INNER JOIN comp_plan AS p ON p.id = mpr.comp_plan_id INNER JOIN rep AS r ON r.id = mpr.rep_id WHERE ((p.org_id = $1) AND (p.deleted = $2)) AND (r.deleted = $3) GROUP BY mpr.comp_plan_id": runtime error: index out of range
E181230 23:26:39.934200 322 util/log/crash_reporting.go:203  [n1,client=172.26.0.1:51510,user=root] a panic has occurred!
E181230 23:26:39.951305 332 sql/conn_executor.go:636  [n1,client=172.26.0.1:51526,user=root] a SQL panic has occurred while executing "SELECT cr.comp_plan_id, count(cr.id) AS count FROM comp_rule AS cr INNER JOIN comp_plan AS p ON p.id = cr.comp_plan_id WHERE ((p.org_id = $1) AND (p.deleted = $2)) AND (cr.deleted = $3) GROUP BY cr.comp_plan_id": runtime error: index out of range
E181230 23:26:39.951548 332 util/log/crash_reporting.go:203  [n1,client=172.26.0.1:51526,user=root] a panic has occurred!
E181230 23:26:39.971715 415 sql/conn_executor.go:636  [n1,client=172.26.0.1:51530,user=root] a SQL panic has occurred while executing "SELECT q.comp_plan_id, count(q.id) AS count FROM quota AS q INNER JOIN comp_plan AS p ON p.id = q.comp_plan_id WHERE ((p.org_id = $1) AND (p.deleted = $2)) AND (q.deleted = $3) GROUP BY q.comp_plan_id": runtime error: index out of range
E181230 23:26:39.975772 415 util/log/crash_reporting.go:203  [n1,client=172.26.0.1:51530,user=root] a panic has occurred!
I181230 23:26:40.029025 117 storage/replica_proposal.go:212  [n1,s1,r39/1:/Table/6{8-9}] new range lease repl=(n1,s1):1 seq=138 start=1546212395.705848500,0 epo=135 pro=1546212399.979943200,0 following repl=(n1,s1):1 seq=137 start=1546211976.850762600,0 epo=134 pro=1546211988.748510900,0
I181230 23:26:40.225670 105 storage/replica_proposal.go:212  [n1,s1,r192/1:/System/tsd/cr.store.queue.r…] new range lease repl=(n1,s1):1 seq=172 start=1546212400.219898900,0 epo=135 pro=1546212400.219921100,0 following repl=(n3,s3):2 seq=171 start=1546209739.378487600,0 epo=70 pro=1546212399.104793400,0
E181230 23:26:40.426152 322 util/log/crash_reporting.go:477  [n1,client=172.26.0.1:51510,user=root] Reported as error 0a88a35d295044dda9d8e076df0ede77
panic: runtime error: index out of range [recovered]
	panic: panic while executing 1 statements: SELECT _._, count(_._) AS _ FROM _ AS _ INNER JOIN _ AS _ ON _._ = _._ INNER JOIN _ AS _ ON _._ = _._ WHERE ((_._ = $1) AND (_._ = $2)) AND (_._ = $3) GROUP BY _._; caused by runtime error: index out of range

goroutine 322 [running]:
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc425ab4000, 0x3032640, 0xc425a847c0, 0x2770200, 0x4231d70)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:650 +0x36f
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc425ab4000, 0x3032640, 0xc425a847c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:387 +0x61
panic(0x2770200, 0x4231d70)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).convertOrdering(0xc42093ba00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:935 +0x27a
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPlanForLookupJoin(0xc42093ba00, 0xc4277a0720, 0xc42748d6c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:1918 +0x964
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPlanForNode(0xc42093ba00, 0xc4277a0720, 0x3025380, 0xc42748d6c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2273 +0x1284
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPlanForLookupJoin(0xc42093ba00, 0xc4277a0720, 0xc42748d860, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:1844 +0xba
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPlanForNode(0xc42093ba00, 0xc4277a0720, 0x3025380, 0xc42748d860, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2273 +0x1284
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPlanForNode(0xc42093ba00, 0xc4277a0720, 0x3025700, 0xc42765de40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2279 +0xccd
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPlanForNode(0xc42093ba00, 0xc4277a0720, 0x3025180, 0xc427787080, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2289 +0x863
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0xc42093ba00, 0x3032700, 0xc4277ca1b0, 0xc425ab44b0, 0xc4277a0720, 0xc427746990, 0x3025180, 0xc427787080, 0xc426eed400)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:752 +0x126
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc425ab4000, 0x3032700, 0xc4277ca1b0, 0xc425ab4418, 0x3, 0x7fe2b4211a40, 0xc427746ab0, 0xc42779e801, 0x2, 0x2)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:982 +0x2d8
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc425ab4000, 0x3032700, 0xc4277ca1b0, 0x3035d80, 0xc4270dd680, 0xc42779e820, 0x2, 0x2, 0xc42722c120, 0x10b, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:824 +0xa8a
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc425ab4000, 0x3032700, 0xc4277ca1b0, 0x3035d80, 0xc4270dd680, 0xc42779e820, 0x2, 0x2, 0xc42722c120, 0x10b, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:402 +0xb3b
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc425ab4000, 0x3032700, 0xc4277ca1b0, 0x3035d80, 0xc4270dd680, 0xc42779e820, 0x2, 0x2, 0xc42722c120, 0x10b, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:96 +0x341
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc425ab4000, 0x3032640, 0xc425a847c0, 0xc420b512d8, 0x5400, 0x15000, 0xc420b51370, 0xc4257bacc0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1173 +0x1400
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc420a04870, 0x3032640, 0xc425a847c0, 0xc425ab4000, 0x5400, 0x15000, 0xc420b51370, 0xc4257bacc0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:389 +0xce
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl.func4(0xc420a04870, 0x3032640, 0xc425a847c0, 0xc425ab4000, 0x5400, 0x15000, 0xc420b51370, 0xc4257bacc0, 0xc4257bacd0, 0xc425a9a110)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:313 +0x81
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:312 +0x107c
```

Problem goes away when I roll back to 2.0.5. Seems like this is a blocker for upgrading to 2.1 at the moment.

**Comment by jordanlewis** [comment]
Thanks @nexdrew, this is actually a different issue #33342, but we were having issues trying to reproduce that one as well so your help is greatly appreciated. Could you please share the schema for that query as well as the output of `EXPLAIN query` and `EXPLAIN(distsql) query`? We'll try to fix this one as soon as possible as well.

**Comment by jordanlewis** [comment]
@yuzefovich could you take a look at this? :)

**Comment by AndriyKhymera** [comment]
@blkerby have u managed to solve your problem?
