### ISSUE TITLE
SQL Support: Insert into select  from confilct

### ISSUE THREAD

**Issue by victorggsimida** [cockroachdb/cockroach#33353]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

INSERT SQL: support like this?

INSERT INTO a (name,age) select name,age FROM b  ON CONFLICT(name) do nothing

**Comment by knz** [comment]
@victorggsimida have you tried this already? The following forks perfectly for me:

```
root@127.114.151.76:44987/defaultdb> create table a (name string, age int);
CREATE TABLE

Time: 11.171886ms

root@127.114.151.76:44987/defaultdb> create table b (name string, age int);
CREATE TABLE

Time: 18.218917ms

root@127.114.151.76:44987/defaultdb> create unique index on a(name);
CREATE INDEX

Time: 83.133972ms

Time: 12.772448ms

root@127.114.151.76:44987/defaultdb> insert into b values ('martin', 42);
INSERT 1

Time: 899.969µs

root@127.114.151.76:44987/defaultdb> insert into a(name, age) select name, age from b on conflict(name) do nothing;
INSERT 1

Time: 5.528138ms

root@127.114.151.76:44987/defaultdb> insert into a(name, age) select name, age from b on conflict(name) do nothing;
INSERT 0

Time: 4.43777ms


```

Can you explain in more detail what you need / want? What you are observing and how this is different from your expectations?
