### ISSUE TITLE
server: Substantial QPS dips when gracefully quitting a server

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#33351]
I created a test in https://github.com/cockroachdb/cockroach/pull/33188 to test for regressions of https://github.com/cockroachdb/cockroach/issues/22573, which you may notice is named identically to this issue. The new test creates a 3 node cluster and runs a write-only kv workload against the first node in the cluster while periodically shutting down and restarting the third node. It passes as written.

However, when trying to convert the test to send all client connections through haproxy, I found that it sometimes fails with large qps dips lasting roughly up to 9 seconds (the node liveness / range lease duration). In such situations, the `kv` output looked like:

```
   3m17s        0         1000.4          998.0      1.4      2.6      5.8     14.2 write
   3m18s        0          996.0          998.0      1.4      3.0     11.5     22.0 write
E181224 15:14:44.319333 1 workload/cli/run.go:402  EOF
   3m19s      266          359.3          994.7      1.1      2.2      3.4      6.0 write
   3m20s      266            0.0          989.8      0.0      0.0      0.0      0.0 write
E181224 15:14:46.541950 1 workload/cli/run.go:402  ERROR: server is not accepting clients (SQLSTATE 57P01)
_elapsed___errors__ops/sec(inst)___ops/sec(cum)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)
   3m21s      515          249.0          986.1      1.0   2013.3   2013.3   2013.3 write
E181224 15:14:47.905144 1 workload/cli/run.go:402  ERROR: server is not accepting clients (SQLSTATE 57P01)
   3m22s      765          250.2          982.4      1.0   1140.9   1140.9   1140.9 write
   3m23s      765            0.0          977.6      0.0      0.0      0.0      0.0 write
E181224 15:14:50.091175 1 workload/cli/run.go:402  ERROR: server is not accepting clients (SQLSTATE 57P01)
   3m24s      913          148.6          973.5      1.0   2013.3   2013.3   2013.3 write
   3m25s     1015          101.6          969.3      1.1      1.8      2.8      2.9 write
   3m26s     1015            0.0          964.6      0.0      0.0      0.0      0.0 write
```

While `haproxy`'s output would look like:

```
[WARNING] 357/101448 (925) : Server psql/cockroach1 is DOWN, reason: Layer7 wrong status, code: 503, info: "Service Unavailable", check duration: 1ms. 2 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
```

To repro, you should just be able to run the modified roachtest in https://github.com/cockroachdb/cockroach/pull/33349 on GCE. Or for faster iteration time, you can reproduce locally using steps such as the following, which I used to confirm that this isn't just an issue with the new test:

In one terminal:

```shell
roachprod destroy local
roachprod create local -n 3
roachprod start local
./cockroach gen haproxy --insecure
haproxy -f haproxy.cfg
```

In a second terminal:

```shell
./cockroach workload run kv --duration=5m --read-percent=0 --tolerate-errors --max-rate=1000
```

In a third terminal:

```
./cockroach quit --host=:26261 --insecure
roachprod stop local:3
```

If you don't see a dip, try restarting that node (`roachprod start local:3`) and killing a different one (e.g. `--host=:26257` and `roachprod stop local:1`). You should see it after a couple tries.

I doubt the issue was fixed in the past week, but for what it's worth I was using a build of cockroach from SHA 859214b81838a4ba33048b81497442ce5774baa7.

Jira issue: CRDB-4692

**Comment by knz** [comment]
cc @nvanbenschoten @tbg for triage

**Comment by asubiotto** [comment]
Given the `haproxy` log message and uptick in errors, the issue here might be that `server.shutdown.drain_wait` hasn't been set and therefore the load balancer doesn't detect that the server is about to drain and attempt to redirect client connections.

**Comment by irfansharif** [comment]
@knz: does this fall under your purview given our renewed interest in node lifecycle? It may no longer be applicable, but (very) anecdotally I saw the same sort of behavior when running chaos experiments for SIGMOD. Feel free to close it out if you're investigating QPS stability through node quit/restart elsewhere.

**Comment by knz** [comment]
I'd vote to work and repro the issue. As I was working on the draining code I noticed that the readiness probe wasn't doing what it should. This would explain why haproxy did not redirect the traffic.

It's possible that the issue has gone away since.

**Comment by knz** [comment]
> does this fall under your purview given our renewed interest in the node lifecycle? 

If the question is "are you going to try reproducing this issue", the answer is "I could, but not anytime soon". I already plan to work on general workload behavior under various deco/restart scenarios. If the same symptoms come up, I could come back to the issue. If they don't after a while we'll close the issue.
