### ISSUE TITLE
sql: erroneous reporting of hidden columns to pgwire

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#33352]
Noticed this while investing #33340 - if you run a query like `EXPLAIN(distsql)` that has hidden columns in its schema from a client that uses pgwire prepare and execute, we still give the hidden columns back to the client as part of the expected output row shape. So the client expects values for that hidden column as well, which we don't provide, leading to client crashes and/or confusion.

**Comment by knz** [comment]
@jordanlewis I understand what you write but I cannot reproduce. Please show me.

**Comment by jordanlewis** [comment]
I can no longer reproduce either. I was able to reproduce on my home computer but not my work computer. I'll follow up on this when I can reproduce again.

**Comment by jordanlewis** [comment]
Dumping this `MainTest.java` acceptance test patch which I thought would fail but currently passes, for future reference:

```
    @Test
    public void testHiddenColumns() throws Exception {
        PreparedStatement stmt = conn.prepareStatement("EXPLAIN(distsql) select 1");
        ResultSetMetaData rsmd = stmt.getMetaData();
        int advertisedColumnCount = rsmd.getColumnCount();
        ResultSet rs = stmt.executeQuery();
        rsmd = rs.getMetaData();
        Assert.assertEquals(advertisedColumnCount, rsmd.getColumnCount());
    }
```

**Comment by jordanlewis** [comment]
Here's the repro:

<img width="849" alt="image" src="https://user-images.githubusercontent.com/43821/50716338-30480d80-104f-11e9-9706-76692bceefea.png">

As you can see, the client sees a `json` column that shouldn't exist in the output as it is marked as hidden.

**Comment by jordanlewis** [comment]
This no longer repros, yay.
