### ISSUE TITLE
admin-ui: flag to disable dashboard authentication

### ISSUE THREAD

**Issue by andrerocker** [cockroachdb/cockroach#33366]
Here we run our cluster inside private network and don't have problems with unautheticated dashboard, is possible to add a configuration flag to disable this feature?

**Comment by knz** [comment]
@andrerocker I don't understand your question fully. What prevents you from running an insecure cluster?

**Comment by couchand** [comment]
Allowing users to disable authentication in the web UI generally is at odds with the product roadmap, as our current focus is on functionality that will expose more sensitive information and certainly require authorization consideration, not just authentication.

However, there is a place for a curated dashboard that we've decided is safe to enable without authentication.  See #25526.
