### ISSUE TITLE
admin-ui: custom cluster name title/header

### ISSUE THREAD

**Issue by andrerocker** [cockroachdb/cockroach#33365]
Is possible to add a custom name for a cluster, and render this on the title/header from the admin-ui? this helps us with a lot of browser tabs with 1+ clusters

**Comment by knz** [comment]
cc @couchand is this feature available? I don't recall

**Comment by knz** [comment]
(sorry wrong button)

**Comment by couchand** [comment]
If there were a cluster name setting I'd be happy to add it to the page title, but I don't think it should be just a UI thing.

cc @piyush-singh

**Comment by knz** [comment]
We have a setting for `cluster.organization` (used for the license) but no `cluster.name` yet.

**Comment by piyush-singh** [comment]
This now gets picked up from the cluster-name command line flag passed to `cockroach start`.
