### ISSUE TITLE
storage/engine: don't store the entire Transaction in MVCCMetadata

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#3341]
An `MVCCMetadata` currently encodes to ~150-175 bytes primarily due to the size of the embedded `Transaction`. The size of the `Transaction` is dominated by all of the non-nullable fields. But it looks like the `MVCCMetadata` only needs 3 fields from the `Transaction`: `ID`, `Epoch` and `Timestamp`. Breaking out these fields from `Transaction` and storing them in them in the `MVCCMetadata` would give a significant space reduction.

**Comment by tschottdorf** [comment]
You'll need the priority too. We can certainly drop a bunch of fields, but a transaction record from an intent can get around quite a lot and we might find that more fields need to be kept there.

**Comment by bdarnell** [comment]
You also need the key to be able to resolve the intent (and maybe the sequence?). 

How much could be saved by making optional fields nullable (or modifying gogoproto to treat zero values as missing for non-nullable fields)? Although it does look like it'd be cleaner to split the parts of `roachpb.Transaction` that are stored in intents into a separate message from the one passed to the client and stored as the primary transaction record.

**Comment by petermattis** [comment]
Hmm, perhaps I was searching wrong, but it looked like only `Transaction.{ID,Epoch,Timestamp}` are currently used. The only place I see `Transaction.Priority` being used is during pushes, but that priority is coming from the transaction record which is different from what this issue is talking about (the `MVCCMetadata`).

**Comment by tschottdorf** [comment]
I was wrong about the priority, but you'll need the key (`store.go:1456`). Sequence number should be ok, unless we're still acting in the name of that transaction somewhere, which I don't think we do.

**Comment by tschottdorf** [comment]
it's happening.

**Comment by petermattis** [comment]
@tschottdorf Is there anything else to do here? Seems like this work is done.

**Comment by tschottdorf** [comment]
Nope, all set.
