### ISSUE TITLE
ui: currently uses a fork of protobuf.js, switch over after PR is merged

### ISSUE THREAD

**Issue by maxlang** [cockroachdb/cockroach#3342]
It's used in both bower/node in an upcoming PR https://github.com/cockroachdb/cockroach/pull/3340.

Here's the PR to protobuf.js to track https://github.com/dcodeIO/protobuf.js/pull/370

**Comment by maxlang** [comment]
Doesn't look like we use this anymore - @tamird is using the latest protobuf.js

**Comment by tamird** [comment]
Fixed in #4976.
