### ISSUE TITLE
storage: when pushing non-persisted transaction, push should restart instead of abort

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#3344]
This is fallout of @bdarnell's analysis in #3219. Briefly, in the current
implementation, transactions may write intents before writing their transaction
record. Trying to push an intent when the record hasn't been persisted yet
aborts this transaction. This isn't a correctness issue (any more, see #3319)
but a restart would be more performant with `SNAPSHOT` isolation.

We don't currently use `SNAPSHOT` much, so it may not be worth optimizing.

**Comment by petermattis** [comment]
Please change the milestone to 1.0 if this isn't important for Beta.

**Comment by tschottdorf** [comment]
Won't be working on this anytime soon, unassigning.

**Comment by tschottdorf** [comment]
Doesn't seem worth tracking this at this point. I believe there's a TODO in `PushTxn` to this effect.
