### ISSUE TITLE
sql: bring EXPORT under the cost-based optimizer

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#33469]
Currently the logic for EXPORT uses a weird interaction/hack because it's a CCL statement, and does not use the CBO to optimize its input query.

The EXPORT planning code must be amended to utilize the CBO, subject to the `optimizer` session setting.

The litmus test to verify that EXPORT indeed uses the CBO is support for correlated subqueries, for example

```
> create table t(x int); create table u(x int);
> export into csv 'nodelocal:///foo.csv' from select exists(select * from u where u.x = t.x) from t;
```

(currently fails)

**Comment by knz** [comment]
cc @andy-kimball

**Comment by rolandcrosby** [comment]
@adityamaru27 May not need to do the entire refactor but the same technique used in CTAS should work here.

**Comment by knz** [comment]
:tada: thank you!
