### ISSUE TITLE
sql: transform the exec+planning code for CREATE TABLE AS to use a regular CREATE+INSERT plan

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#33476]
Currently CREATE TABLE AS has its own custom,non-optimized,non-batched exec logic which is unusable for large tables.

The goal of this change is to plan `CREATE TABLE AS` like

```
WITH tabledesc AS (CREATE TABLE ...)
INSERT INTO [tabledesc]   ....
```

This needs to:

- deprecate the exec code of the AS clause
- change the planning to produce a CREATE+INSERT plan, leveraging the TableCollection to hold the newly-created-but-not-yet-in-KV table descriptors (this was not available when CREATE TABLE AS was first designed, hence the bad implementation)
- verify that the plan gets optimized suitably by the CBO.

cc @andy-kimball

**Comment by vivekmenezes** [comment]
The insert execution will eventually need to do an EXPORT followed up an IMPORT for large amounts of data. That is outside the scope of this issue.

**Comment by RaduBerinde** [comment]
Closing this. The Bulk IO team has worked on better execution for CREATE TABLE AS.
