### ISSUE TITLE
sql: implement a test generator that exercises SQL mutations for crdb and pg side-by-side

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#33477]
We want a random schema generator + random mutation generator, that generates mutation statements valid for both postgres and cockroachdb.

The generator for schemas must generate
- variable number of families
- variable uses of DEFAULT
- variable uses of CHECK
- variable uses of NOT NULL constraints
- variable index combinations (unique and non-unique)
- variable FK definitions
- variable interleaving definitions
- variable alter column scenarios (i.e. SQL mutations inside a txn with some ALTERs before the mutation statement)

The generator for mutations must generate
- various RETURNING clauses
- various combinations of target columns
- various source data plans
- various uses of USING DEFAULTS
- various uses of the DEFAULT keyword in VALUES clauses
- various column lists in ON CONFLICT(...)
- occurrences of ON CONFLICT DO NOTHING
- various assignments in UPDATE and ON CONFLICT DO UPDATE
- various ORDER BY + LIMIT clauses to control input batching

In all scenarios the code must exercise with different starting situations in the target table: with no data, with some data, with enough data that more than 1 mutation batch is executed.

In all scenarios the comparison code with pg must ensure that:
- the result of the mutation in the target table is compatible with that of pg (same data modulo ordering)
- the result row counts are compatible (when no RETURNING)
- the result sets (with RETURNING) are compatible modulo ordering

Optionally the generator can exercise crdb-only UPSERT syntax (without comparison to pg)

**Comment by jordanlewis** [comment]
@knz some of this work is already done. See `RandCreateTable` in `testutils.go`.

**Comment by knz** [comment]
thanks for the heads up
