### ISSUE TITLE
UI cannot execute SQL in secure mode

### ISSUE THREAD

**Issue by maxlang** [cockroachdb/cockroach#3348]
Repro steps:
 - run a secure cockroach cluster
 - attempt to go the the User or Databases page 

Network request to /sql/Execute returns with the following error:

```security/auth.go:65: no client certificates in request```

Introduced in https://github.com/cockroachdb/cockroach/pull/3340

**Comment by mberhault** [comment]
yeah, that's not new. the UI really need to authenticate people using a combination of user/password and cookies to keep track of credentials. We'll have a different endpoint that verifies the cookies and validates the incoming username.

**Comment by petermattis** [comment]
This issue will go away when #4298 is addressed.
