### ISSUE TITLE
limit: semaphore acquire has potential to deadlock (not currently reachable)

### ISSUE THREAD

**Issue by Sherifabdlnaby** [cockroachdb/cockroach#33554]
I came a cross a bug in pkg `github.com/marusama/semaphore` that may cause deadlock.

Here's my issue in the pkg's repo: https://github.com/marusama/semaphore/issues/3

This package is used in type `ConcurrentRequestLimiter ` in `/pkg/util/limit/limiter.go` @ https://github.com/cockroachdb/cockroach/blob/138ff1fe56a1dc3b5b11046f1d78a0b6251fc335/pkg/util/limit/limiter.go#L21

According to my debugging, It will not happen in this codebase since all weights used to Acquire the semaphore = `1`, the buq occurs when the semaphore is full and a weighted Acquire(`n`) is blocking && `GOMAXPROCS` < `n`, since GOMAXPROCS has a minimum of 1. so currently the bug won't happen.

However It would be safer if it switched to another semaphore implementation.

**Comment by mjibson** [comment]
Thanks for reporting this. We're unlikely to fix it soon because finding another semaphore library that supports dynamic resizing has been difficult. cc @dt

**Comment by dt** [comment]
Thanks for digging in to it and giving us the heads up!

FWIW, I don't think the maintainer is inactive -- we sent a fix for another deadlock a couple months ago and they merged it and cut a new release for us right away. Might just be busy with travel season/holidays/etc.

Like @mjibson said, we haven't found many alternative resizable semaphores -- I think @nvanbenschoten looked at writing his own, but ended up not needing it, so this is what we're using for now.

**Comment by Sherifabdlnaby** [comment]
Yes, the maintainer actually did respond to my issue today, I based my assumption on his/her Github's activity and I guess I was wrong.

**Comment by Sherifabdlnaby** [comment]
@mjibson @dt I've found the bug and submitted a PR and waiting for the maintainers response, unfortunately fixing the bug has a performance cost.
It turns out it was a different reason that what I've mentioned, however it is still *not currently reachable* in cockroach's codebase.

It will only happen when you don't use the same value of weights for acquiring and releasing *across the entire semaphore*.

**Comment by marusama** [comment]
I have merged @Sherifabdlnaby PR, new version is 2.3.0. This fix has halved performance, but looks that there is no way to avoid that 😿

**Comment by mjibson** [comment]
Thanks! Next time we do a dep update this will get picked up, so I'm closing this issue now.
