### ISSUE TITLE
roachprod: pgurl creates bad URL when multiple IPs are present 

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#33556]
When trying to add tracing to a `roachprod` cluster, I ran the following command (copied from [this PR](https://github.com/cockroachdb/roachprod/pull/191)):

```
roachprod run becca-test:1 -- 'sudo docker run -d --name jaeger \
  -e COLLECTOR_ZIPKIN_HTTP_PORT=9411 \
  -p 5775:5775/udp \
  -p 6831:6831/udp \
  -p 6832:6832/udp \
  -p 5778:5778 \
  -p 16686:16686 \
  -p 14268:14268 \
  -p 9411:9411 \
  jaegertracing/all-in-one:latest'
```

Then I tried to start TPC-C as follows:
```
$ roachprod run becca-test:4 -- ./workload run tpcc --warehouses 400 --duration 10m {pgurl:1-3}
```

But I got the error:
```
Error: parse postgres://root@10.142.0.6 172.17.0.1:26257?sslmode=disable: invalid character " " in host name
Error:  exit status 1
```

Upon closer inspection, it seems that `pgurl` is getting confused due to the presence of `jaeger`:
```
$ roachprod run becca-test:4 -- echo {pgurl:1-3}
postgres://root@10.142.0.6 172.17.0.1:26257?sslmode=disable postgres://root@10.142.0.9 172.17.0.1:26257?sslmode=disable postgres://root@10.142.0.7 172.17.0.1:26257?sslmode=disable
```

If I delete the second spurious IP and just run the following, it works:
```
$ roachprod run becca-test:4 -- ./workload run tpcc --warehouses 400 --duration 10m postgres://root@10.142.0.6:26257?sslmode=disable postgres://root@10.142.0.9:26257?sslmode=disable postgres://root@10.142.0.7:26257?sslmode=disable
```

So clearly there is a workaround, but it would be nice if `pgurl` could just handle this....

Epic CRDB-10428

Jira issue: CRDB-4683

**Comment by petermattis** [comment]
I'm guessing that `SyncedCluster.GetInternalIP` is doing the wrong thing when `hostname --all-ip-addresses` returns multiple addresses. I'm not sure what the best fix is. Certainly something can be hacked up so that only one IP address is used, though we want that address to be one that is routable externally to the machine and not one used by docker.
