### ISSUE TITLE
ui: logical plan view: only use square brackets for list attributes

### ISSUE THREAD

**Issue by vilterp** [cockroachdb/cockroach#33569]
Some attributes of plan nodes have a lists of values (e.g. the `render` attribute of the `render` node, which is a list of columns to be rendered), while some will only ever just have one (e.g. the `count` attribute of the `limit` node).

**Expected:**

Attribute values should only be rendered with square brackets around them if they are list-valued.

**Actual:**

Non-list-valued attributes like `count`, `order` and `strategy` rendered with square brackets:
![image](https://user-images.githubusercontent.com/7341/50854152-4d802300-1352-11e9-9bc0-40465c09925f.png)

I'm not really sure how you would know whether an attribute is supposed to be "list-valued" or not. Maybe it's sufficient to just have square brackets if there's more than one value for that attribute, and not have them if there's only one? (I think that was the original behavior of the plan view)

**Comment by couchand** [comment]
We'll be revisiting the designs over the next milestone and so I don't think this will be relevant.  Thanks.
