### ISSUE TITLE
storage: Coalesce Transaction Record GC

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#33574]
**Problem**

Currently when a transaction commits its leaseholder launches an async task to resolve all intents and then subsequently issues a request to GC the transaction record. This means that all committed transactions require an additional raft entry to remove their transaction records. These transaction record deletions could occur in a single batch. For write-only, transactional workloads this could remove almost one raft entry per transaction which is a potentially huge win. 

An implementation will likely involve extending the `storage.intentResolver` to group transaction records on a per-range basis and issue a single batch request per range. While there is a chance that the range may have changed for a given transaction record, the DistSender will deal separating the batch.

**Benchmarking**

Most of the existing write heavy work loads, like kv0 avoid transactions and hit the one-phase-commit fast path. To reveal this change we'll likely need to use kv0 with a large number of splits and a batch size of 2.

**Comment by nvanbenschoten** [comment]
This is also discussed in https://github.com/cockroachdb/cockroach/issues/30780#issuecomment-443761693.

**Comment by ajwerner** [comment]
Preliminary results from a prototype implementation show a modest non-zero throughput win. There's a bunch of knobs about the exact batching behavior but it seems adequately promising to move forward.

Below benchmark was run on 3x n1-standard-4 nodes with 
```
./workload run kv '{pgurl:1-3}' --init --splits=512 --duration 3m --batch 2 --read-percent=0 --concurrency=512
```
```
name       old ops/s  new ops/s  delta
KV0        724 ± 0%   740 ± 0%  +2.18%  (p=0.029 n=4+4)
```

A lot of the performance ends up hinging upon the value of `defaultIntentResolverTaskLimit` which requires a higher value in order to show increased performance with batching. This makes sense because when we hit that limit processing becomes synchronous and batching leads to increased task duration. The above results show both master and the prototype with that value increased from 100 to 1000. Increasing the value on master seems to have minimal impact on throughput though it has a large impact on tail latency. With batching increasing the limit has a profound impact on both throughput and tail latency. It's worth noting that batching exposes even more parameters that need some tuning. :woman_shrugging:, diff to come soon.
