### ISSUE TITLE
Cockroach should listen on localhost by default

### ISSUE THREAD

**Issue by maxlang** [cockroachdb/cockroach#3358]
Currently Cockroach listens on ```<hostname>:26257```. I feel it's both more intuitive and more consistent to listen on ```localhost:26257```

**Comment by bdarnell** [comment]
The default should be "all network interfaces", not only localhost.

**Comment by tschottdorf** [comment]
I believe there are some dragons there. Maybe Gossip? TLS?

**Comment by bdarnell** [comment]
The server needs to broadcast a single address via gossip, and that needs to be its hostname. But I think it should *also* listen on localhost, mainly for ad-hoc curl and browser requests to the status pages. (the TLS cert won't validate in this case but that's OK and expected)

**Comment by petermattis** [comment]
@tamird This has been fixed, correct?

**Comment by tamird** [comment]
Yeah, mostly. Some leftover work to do, but this issue is done.
