### ISSUE TITLE
exec: implement columnar merge join

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#33590]
This issue tracks implementing a merge join operator in the columnar model. The operator should be loosely based off the merge join code we already have, but it must be modified in a few key ways to fit into the columnar model.

As with all columnar operators, only a single pair of columns should be compared at one time, to permit each operator to be templated on the column's datatype.

I suggest taking the following approach for sequencing the project:

- [x] Implement a subset of the operator that performs inner joins only, operates only on int64s, without templating, that can only deal with a single equality column at one time. This should be simpler to start with and require fewer steps. We can iterate on the core algorithm here, before adding any of the templating or multi-column complexity. Some dimensions to think about for the core algorithm: distinct values vs duplicate values in either of the equality columns, dealing with batching boundaries and output, outputting "accessory" columns along with the equality cols
- [x] Add planning to `column_exec_setup.go` so the system can plan this variety of merge joins and we can test the code from logic tests by turning on `experimental_vectorize`.
- [x] Add templating, so that the operator will be usable on any type.
- [x] Add multi-column merge joins.
- [ ] Add outer joins.

**Comment by georgeutsin** [comment]
Doing some tests, I noticed that for queries like

```
SELECT l_extendedprice FROM partsupp INNER MERGE JOIN lineitem ON ps_suppkey = l_suppkey ORDER BY l_extendedprice LIMIT 10;
```

The vectorized merge joiner performance is actually worse than the row by row engine:
Row by row: 1m29.236404s 
Vectorized: 4m40.249121s

Not sure if it's the sorting step, or the planning done outside of the merge join step, but I think its an issue that some queries are slower.

**Comment by jordanlewis** [comment]
Can you show the `EXPLAIN (opt)` and `EXPLAIN (distsql)` output for the query?

**Comment by georgeutsin** [comment]
```
root@:26257/tpch> explain (opt) SELECT l_extendedprice FROM partsupp INNER MERGE JOIN lineitem ON ps_suppkey = l_suppkey ORDER BY l_extendedprice LIMIT 10;
                           text                           
+--------------------------------------------------------+
  project                                                 
   └── limit                                              
        ├── sort                                          
        │    └── inner-join (merge)                       
        │         ├── flags: no-lookup-join;no-hash-join  
        │         ├── scan partsupp@ps_sk                 
        │         ├── sort                                
        │         │    └── scan lineitem                  
        │         └── filters (true)                      
        └── const: 10                                     
(10 rows)

Time: 3.545ms

root@:26257/tpch> explain (distsql) SELECT l_extendedprice FROM partsupp INNER MERGE JOIN lineitem ON ps_suppkey = l_suppkey ORDER BY l_extendedprice LIMIT 10;
  automatic |                                                                                                                                                                                                                                                                  url                                                                                                                                                                                                                                                                    
+-----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
    true    | https://cockroachdb.github.io/distsqlplan/decode.html#eJyckkFr4zAQhe_7K8KcdomWWLazB8OCrlm2TUl6K6ao1tQVtSUxkqEl5L8X29DUJnZJbtZI33vPTzqAsQpvZY0esgfgkDNwZAv03lI76g9s1BtkEQNtXBPacc6gsISQHSDoUCFkcC-fKtyhVEirCBgoDFJXnazzj_5VOEnBN84Bg72TxmeL38Bg24RsIWLIjwxsE076PsgSIeNHdl0GPspAupb0LiptUAesz6VImPgzGSS-JMjeUkBaxcMMgi8n5ZNJ-ZNqYywpJFQD2bwlvztyJuMNUon_rDZIq2QYtMLn8FPw5a-_pMuX_vOzJc5EzEQy-SfpFUWlo6KS5elSgMF_Xeuw4NGk5_oSzx16Z43HcYtnlaO2OlQl9lfhbUMF3pEtOpt-ue24bqDQh3436Rcb0211z_grzGfheABHYzi-wDkew8ksnM47p7PwegTnxx8fAQAA__8u2W5z  

```

**Comment by jordanlewis** [comment]
Can you isolate the performance difference? You could try removing the `ORDER BY` - what happens?

I'm guessing this is caused by the lack of `top k` sorting which currently gives the non-vectorized engine a huge advantage. So try removing the ORDER BY and seeing what happens.

**Comment by jordanlewis** [comment]
Thanks @georgeutsin for a great internship! Closing this and opening a new issue for outer join.
