### ISSUE TITLE
Remove `cockroach user` command in favor of SQL statements

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#33594]
There are two ways to work with users, `cockroach user` and the `CREATE/DROP USER` SQL statements. I think this is the only functionality currently exposed via both the cli and SQL. I think we should limit this functionality to SQL, especially given that we moved zone config work from the CLI to SQL.

**Comment by knz** [comment]
Probably we should have a release cycle where the feature is:

- hidden but functional
- not documented
- produces a deprecation warning upon use
