### ISSUE TITLE
ui: unclear relationship between storage metrics

### ISSUE THREAD

**Issue by couchand** [cockroachdb/cockroach#33631]
**Describe the problem**

Looking at the Storage dashboard on `adriatic`.  Note that Live Bytes significantly exceeds the Capacity Used.

<img width="448" alt="screen shot 2019-01-10 at 1 13 55 pm" src="https://user-images.githubusercontent.com/793969/50988165-cf4e8880-14d9-11e9-853c-fa104fb3be5f.png">
<img width="460" alt="screen shot 2019-01-10 at 1 13 58 pm" src="https://user-images.githubusercontent.com/793969/50988166-cfe71f00-14d9-11e9-97b5-d8cee31ae533.png">

**Expected behavior**

Intuitively I would expect Capacity Used to exceed Live Bytes, by at least the replication factor, but also by the amount of storage amplification.

It would seem there is something going on here that isn't clear from the metric descriptions.  More investigation is needed.

**Comment by couchand** [comment]
cc @piyush-singh filed this regarding our conversation earlier.

**Comment by tbg** [comment]
Live bytes is logical (i.e. very roughly it's the number of bytes stored in the db) and capacity is what's actually on disk. Think about it this way:

storing the string "aaaaaaaaaa" under key "xxxxxxxxx" may be stored multiple times on disk (write amplification of LSM) but at the same time it'll be compressed. So key-value pairs written logically may and usually do deviate from how much space is taken up on disk (which also includes lots of other stuff).

This topic comes up with regularity, and I'm not sure what do to about it on the technical side. Users will want to know how much of their disk is utilized,  and it's useful to know how much logical data there is. But they're not comparable and it isn't possible to compute the space on disk that is "live".

I would hope that the info-bullet for Live Bytes already explains this, but maybe that's not enough.

**Comment by tbg** [comment]
@couchand seems like the ui project doesn't use a column into which triage-issues are moved automatically. Would you mind making one? The reason is that roachdash won't work because we're now using some new projects API that won't recognize an issue as being owned by a project when it's in this state:

<img width="239" alt="image" src="https://user-images.githubusercontent.com/5076964/51181512-a825fb80-18cb-11e9-9944-8e834cc2511b.png">


Thanks!

**Comment by piyush-singh** [comment]
Repurposing this issue for our work to define these metrics more clearly in the UI, and to update metrics to use the appropriate ones in different places throughout the UI. We'll be improving definitions for 20.1 based on work by @taroface with feedback from Bilal. Corresponding docs issue is cockroachdb/docs#6777
