### ISSUE TITLE
rpc: log when breaker trips, including the error

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#33657]
We've seen indications (#31361, #33549) that circuit breakers sometimes open in situations in which it doesn't seem to make a whole lot of sense. If a breaker trips, we'd like to know the error that tripped it and the callsite.

**Comment by ajwerner** [comment]
@tbg I just touched this code the other day. Feel free to put me on reviews or if you're feeling worried you won't have time to get to it you can pass it over to me as I'm sure it will help me debug #31361.

**Comment by tbg** [comment]
Would appreciate your help here, thanks!
