### ISSUE TITLE
lint: make lint tests work with new honnef.co/go/tools release

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#33669]
The new `honnef.co/go/tools` release makes quite a few changes to the API. Unfortunately it's very poorly documented.

I tried fixing up our code to work with the new release; it involved a lot of guess work but in the change linked below I have `TestUnused` building. Unfortunately it times out after 10minutes and uses 30+GB RAM (for reference, it currently takes 30s); so something is wrong but I have very little context with this code to even know where to start looking.

This is what I have so far, hopefully someone can pick this up at some point:
https://github.com/cockroachdb/cockroach/compare/master...RaduBerinde:update-honnef?expand=1

**Comment by RaduBerinde** [comment]
I filed https://github.com/dominikh/go-tools/issues/391 to hopefully get some help on this.

**Comment by RaduBerinde** [comment]
This problem doesn't exist when using go 1.11. I will update these deps after we switch.

**Comment by knz** [comment]
@RaduBerinde I think we switched, perhaps this issue can be closed?

**Comment by RaduBerinde** [comment]
Nope, I ran into other problems even with 1.11; the new release of this repo is slower and uses much more memory (see #34015, https://github.com/dominikh/go-tools/issues/394). We will stay with the old version for the foreseeable future.
