### ISSUE TITLE
distsql: incorrect resolved spans unless SHOW EXPERIMENTAL RANGES is run before

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#33686]
Saw the test flake below. The plans are the same except a span went to a different node. This is exposed (but not caused) by #33571 (CC @georgeutsin).

        --- FAIL: TestExecBuild/5node-dist-opt/lookup_join (1.16s)
            logic.go:2301: 
                 
                testdata/lookup_join:129: SELECT url FROM [EXPLAIN (DISTSQL) SELECT * FROM (SELECT * FROM data WHERE c = 1) AS l NATURAL JOIN data AS r]
                expected:
                    https://cockroachdb.github.io/distsqlplan/decode.html#eJzElEFr2zAUx-_7FOKdZWxJTpoKBj4NMkY6ut6GD1r06LylkpFk2Cj57sP2oE5IZYFLerSsP_8fvyfeMxircaee0IP8DgwocKAggEIJFFZQU2id3aP31vVXxsBW_wFZUGhM24X-uKawtw5BPkNowgFBwoP6ccB7VBpdXgAFjUE1h6Gmdc2Tcn8rrYICCt9aZbwkWc6IMppwYsNPdB4ofGoOAZ0klSAfCZNSbncPG6iPFGwXXqp9UI8Ikh1pOt5n25j_dKso3Rdrf3ct-WUbQ6yRpGK04rQStOoN3XXh9Og1OP4q3AtTZ6zT6FCfANXHC_g7m9k2Z8XZzcvd4qSbpc-NpcwtZ1nOh8mxcXILBzfDNxnc-vqD4-nyeJI8nuXiDeXN8E3k3VxfnkiXJ5LkiSwv31DeDN9E3ub68sp0eWWSvDIbNt8SYTNME2G377tjL8Ddo2-t8Zi0QYt-B6N-xHFhe9u5PX51dj_UjJ93Q2440OjD-JeNH1sz_uoBp2EWDfOTMDsP83jzTLWIpst4uFzCvYqG1_Hm9ZLmm2h4E2_eLGm-jc-qmHkm8Ud23l0fP_wLAAD__w5KJqY=
                    
                but found (query options: "") :
                    https://cockroachdb.github.io/distsqlplan/decode.html#eJzElEFr2zAUx-_7FOKdZWxJTpoKBj4NMkY6ut6GD1r06LylkpFk2Cj57sPxoE5IZEFMerSsP_8fvyfeKxircaNe0IP8DgwocKAggEIJFBZQU2id3aL31vVXhsBa_wFZUGhM24X-uKawtQ5BvkJowg5BwpP6scNHVBpdXgAFjUE1u0NN65oX5f5WWgUFFL61ynhJspwRZTRhxIaf6IDCp2YX0ElSCfKRMCnlevO0gnpPwXbhrdkH9Ywg2Z6m0322jfkPt4jCfbH2d9eSX7YxxBpJKkYrTitBq17QQxeOjy7B8Ytwb0ydsU6jQ30EVO_P4G9sZtucFSc3z3eLo26WPjaWMracZTmfcXATfKPBLW8_OJ4ujyfJ41kuZpQ3wTeSd3d7eSJdnkiSJ7K8nFHeBN9I3ur28sp0eWWSvDLLFzPKm-Abybt_3317Bu4RfWuNx6RtWvT7GPUzDsvb285t8auz20PN8PlwyB0ONPow_GXDx9oMv3rAcZhFw_wozE7DPN48US2i6TIeLq_hXkTDy3jz8prmu2h4FW9eXdN8H59VMfFM4o_stLvef_gXAAD__0eIKhg=

**Comment by RaduBerinde** [comment]
Hm, the second plan is actually the correct one. Each table reader should have 2 spans.

I added a SHOW EXPERIMENTAL RANGES to verify data placement and now the second plan is always reliably generated.

```diff
--- a/pkg/sql/opt/exec/execbuilder/testdata/lookup_join
+++ b/pkg/sql/opt/exec/execbuilder/testdata/lookup_join
@@ -109,6 +109,22 @@ statement ok
 ALTER TABLE data EXPERIMENTAL_RELOCATE
   SELECT ARRAY[i%5+1], i FROM generate_series(0, 9) AS g(i)
 
+# Verify data placement.
+query TTTI colnames
+SELECT start_key, end_key, replicas, lease_holder from [SHOW EXPERIMENTAL_RANGES FROM TABLE data]
+----
+start_key  end_key  replicas  lease_holder
+NULL       /1       {1}       1
+/1         /2       {2}       2
+/2         /3       {3}       3
+/3         /4       {4}       4
+/4         /5       {5}       5
+/5         /6       {1}       1
+/6         /7       {2}       2
+/7         /8       {3}       3
+/8         /9       {4}       4
+/9         NULL     {5}       5
+
```

Without `SHOW EXPERIMENTAL_RANGES`, the last span frequently gets resolved to `n1` instead of `n5`:
```
lastKey: /Table/55/1/1 desc: r20:/Table/55/1/{1-2} [(n1,s1):1, (n2,s2):2, next=3, gen=1] replInfo: (n2,s2):?
lastKey: /Table/55/1/2 desc: r21:/Table/55/1/{2-3} [(n1,s1):1, (n3,s3):2, next=3, gen=1] replInfo: (n3,s3):?
lastKey: /Table/55/1/3 desc: r22:/Table/55/1/{3-4} [(n1,s1):1, (n4,s4):2, next=3, gen=1] replInfo: (n4,s4):?
lastKey: /Table/55/1/4 desc: r23:/Table/55/1/{4-5} [(n1,s1):1, (n5,s5):2, next=3, gen=1] replInfo: (n5,s5):?
lastKey: /Table/55/1/5 desc: r24:/Table/55/1/{5-6} [(n1,s1):1, next=2, gen=1] replInfo: (n1,s1):?
lastKey: /Table/55/1/6 desc: r25:/Table/55/1/{6-7} [(n1,s1):1, (n2,s2):2, next=3, gen=1] replInfo: (n2,s2):?
lastKey: /Table/55/1/7 desc: r26:/Table/55/1/{7-8} [(n1,s1):1, (n3,s3):2, next=3, gen=1] replInfo: (n3,s3):?
lastKey: /Table/55/1/8 desc: r27:/Table/55/1/{8-9} [(n1,s1):1, (n4,s4):2, next=3, gen=1] replInfo: (n4,s4):?
lastKey: /Table/55/1/9 desc: r28:/{Table/55/1/9-Max} [(n1,s1):1, (n5,s5):2, next=3, gen=0] replInfo: (n1,s1):?
```

The cluster is set up in `ReplicationManual` mode. Why is a replica on `n1` being added to each range?
@andreimatei could you take a look?

**Comment by andreimatei** [comment]
Don't know what to say, but I'll look when I can.

**Comment by jordanlewis** [comment]
Hasn't reoccurred since January.

**Comment by RaduBerinde** [comment]
I fixed the test by adding a `SHOW EXPERIMENTAL RANGES`. But that hides the problem. I'd still want this investigated. I'll update the issue title.

**Comment by jordanlewis** [comment]
Oh, sorry, I misunderstood what was happening in the discussion.
