### ISSUE TITLE
Date function does not use index

### ISSUE THREAD

**Issue by yijh** [cockroachdb/cockroach#33696]
**Describe the problem**

When I create an index on the timestamp type column , but the plan display is not used
And this index will not be used with any date function.

**To Reproduce**

create table test2 as select id,status,created from system.jobs;

show create table test2;
  table_name |                 create_statement                   
+------------+---------------------------------------------------+
  test2      | CREATE TABLE test2 (                               
             |     id INT NULL,                                   
             |     status STRING NULL,                            
             |     created TIMESTAMP NULL,                        
             |     FAMILY "primary" (id, status, created, rowid)  
             | )                                                  
(1 row)

## create index
create index on test2(created) storing(id,status);

## get count
select count(*) from test2;
  count  
+-------+
    318  
(1 row)

Time: 1.771449ms

## Get the count of records in 3 days use [now] function
select count(*) from test2 where created>=now()-interval '3' day;
  count  
+-------+
      8  
(1 row)

Time: 3.442852ms

## explain
explain select count(*) from test2 where created>=now()-interval '3' day;
       tree      |    field    |        description         
+----------------+-------------+---------------------------+
  group          |             |                            
   │             | aggregate 0 | count_rows()               
   │             | scalar      |                            
   └── render    |             |                            
        └── scan |             |                            
                 | table       | test2@test2_created_idx    
                 | spans       | /!NULL-                    
                 | filter      | created >= (now() - '3d')  
(8 rows)

Time: 1.600412ms

We see that the spans in the plan are NULL,actually treating the function as a filter

**Expected behavior**
My expected plan is the following
       tree      |    field    |       description        
+----------------+-------------+-------------------------+
  group          |             |                          
   │             | aggregate 0 | count_rows()             
   │             | scalar      |                          
   └── render    |             |                          
        └── scan |             |                          
                 | table       | test2@test2_created_idx  
                 | spans       | /2019-01-10T00:00:00Z-   
(7 rows)

**Environment:**
 - CockroachDB version 2.1.1
 - Server OS: Linux
 - Client app `cockroach sql`,jdbc

**Comment by knz** [comment]
Thank you for your report!

However, we are already tracking this problem in #18836. I am going to close this issue; feel free to subscribe to the other issue for updates, or add more information there.

Thank you again

**Comment by rwrz** [comment]
I'm having a similar issue with this query:

```
SELECT distinct activities.user_id
        FROM activities
        WHERE created_at >= ((date_trunc('day', timezone(activities.timezone, NOW())) - INTERVAL '1 day') AT TIME ZONE
                             activities.timezone)
          AND created_at <    date_trunc('day', timezone(activities.timezone, NOW())) AT TIME ZONE activities.timezone
        order by activities.user_id
        ```
