### ISSUE TITLE
sql: disable running individual subtests in logic tests

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#33699]
In the `schema_change_in_txn` logic test file some of the subtests don't work in isolation since they want tables from other subtests. Others work.
At least the following two don't work:
```
make test PKG='./pkg/sql/logictest' TESTS=TestLogic/local/schema_change_in_txn/truncate_and_insert
make test PKG='./pkg/sql/logictest' TESTS=TestLogic/local/schema_change_in_txn/rollback_mutations
```

**Comment by vivekmenezes** [comment]
The subtests are only acting as documentation in this test. Many of them are broken if run on their own. If we really want this fixed we need to add in automation to run all logic sub tests and check that they don't break.

**Comment by jordanlewis** [comment]
I don't think we'll get to this - the subtests in logic tests aren't that useful as anything but comments, and I don't think adding better support is necessary.
