### ISSUE TITLE
Tools that vendor cockroachdb cannot use go modules

### ISSUE THREAD

**Issue by lopezator** [cockroachdb/cockroach#33709]
Any tool that vendorize cockroachdb cannot migrate it's vendoring system from `dep` to `go mod` as it the following error:

```
go: downloading github.com/cockroachdb/cockroach v2.1.3+incompatible
-> unzip /Users/d.lopez/go/pkg/mod/cache/download/github.com/cockroachdb/cockroach/@v/v2.1.3+incompatible.zip: malformed file path "pkg/cmd/prereqs/testdata/src/example.com/specialchars/a[]*?~ $%#.go": invalid char '*'
```

Seems that the name of the file isn't supported by golang/zip, related issue:

https://github.com/golang/go/issues/28001

Please describe the issue you observed, and any steps we can take to reproduce it:

Clone any repository that vendorize cockroachdb and try to do a, for example:

https://github.com/lopezator/sqlfmt

And:

```
$ export GO111MODULE=on
$ go mod init
$ go build ./...
```
Build will throw the mentioned error.

**Expected behavior**

Being able to build/migrate projects that vendorize cockroachdb to modules.

**Fix**

Not sure what would be the better solution, but seems that the name of the affected test file must be changed.

**Comment by petermattis** [comment]
This isn't difficult to fix, just mildly irritating. The `prereqs` test wants a file containing special characters to verify its handling of such files. We can rewrite the test so that the filename is only in-memory.
