### ISSUE TITLE
Update SQLAlchemy docs to use `run_transaction` with `create_all`

### ISSUE THREAD

**Issue by bobvawter** [cockroachdb/cockroach#33713]
Per #31094, SQLAlchemy doesn't automatically retry DDL transaction.  We should update https://www.cockroachlabs.com/docs/stable/build-a-python-app-with-cockroachdb-sqlalchemy.html to wrap the call to `db.create_all()` inside of a call to `run_transaction()`.  See change in cockroachdb/examples-orms#59.

**Comment by jseldess** [comment]
@rmloveland, @bobvawter, I think our SQLAlchemy docs have been updated in the meantime: https://www.cockroachlabs.com/docs/stable/build-a-python-app-with-cockroachdb-sqlalchemy.html#step-4-run-the-python-code. Can this be closed?

**Comment by bobvawter** [comment]
Yes, I think this issue can be closed.
