### ISSUE TITLE
ui: time-series charts sluggish on 1-month setting

### ISSUE THREAD

**Issue by couchand** [cockroachdb/cockroach#33717]
When looking at the time-series dashboards for the full 1-month time scale, the interface becomes very sluggish.  The browser is getting bogged down with excessive re-renders, which then end up generating a bunch of garbage, which makes us wait for GC pauses, which then pile up the re-renders.

**Comment by petermattis** [comment]
Stupid questions: are there more re-renders for 1-month time scale vs 1-hour? Why? If the problem isn't additional re-renders at larger time scales, are the re-renders slower?

**Comment by couchand** [comment]
The problem exists if there's less data on the page, but it doesn't compound with smaller data sets so it's not really noticeable unless you're looking at the profiler.
