### ISSUE TITLE
sql client database name option is case sensitive

### ISSUE THREAD

**Issue by chriswhite199** [cockroachdb/cockroach#33729]
**Describe the problem**

Creating a new database with uppercase characters gets normalized to lowercase, then attempting to connect to that database (using the original uppercase name) fails

**To Reproduce**

```
16:53 $ docker run -d --name cockroachdb cockroachdb/cockroach start --insecure
9d45f593eb723f70a0ff043988688d24546e7f66bf376eea9b5b05a4c7fec46e
✔ ~ 
16:53 $ docker exec -it cockroachdb ./cockroach sql --insecure
# Server version: CockroachDB CCL v2.1.3 (x86_64-unknown-linux-gnu, built 2018/12/17 19:15:31, go1.10.3) (same version as client)
# Cluster ID: e7cde7cb-ef2a-4600-9da7-bbba871acfda
root@:26257/defaultdb> create database CaseSensitive;
CREATE DATABASE

Time: 36.582ms

root@:26257/defaultdb> show databases;
  database_name  
+---------------+
  casesensitive  
  defaultdb      
  postgres       
  system         
(4 rows)

Time: 13.6821ms

root@:26257/defaultdb> ^D
✔ ~ 
16:54 $ docker exec -it cockroachdb ./cockroach sql --insecure -d CaseSensitive
warning: unable to retrieve the server's version: pq: database "CaseSensitive" does not exist
warning: error retrieving the database name: pq: database "CaseSensitive" does not exist
root@:26257/?> 
```

**Expected behavior**

The `-d` option to the sql cli should normalize the database name in the same way they `CREATE DATABASE xxx` does (IMO)

**Environment:**
 - CockroachDB version: 2.1.3
 - Server OS: Docker
 - Client app: cockroach sql

**Additional context**

Workaround is to just ensure you lowercase the `-d` cli argument

**Comment by jordanlewis** [comment]
Hi @chriswhite199, this is known behavior, the same as what Postgres does. To get a database object (database, table, column, etc) with actual uppercase letters, you need to enclose the object in double quotes when creating it and looking it up both.
