### ISSUE TITLE
sql/sem/tree: CreateTable partition by expressions are not walked

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#33724]
The `CreateTable.walkStmt` implementation is not walking over the expressions inside CreateTable.PartitionBy. This results in abnormal behavior when placeholders or subqueries are used inside those expressions.

CC @knz @danhhz

Jira issue: CRDB-4674

**Comment by knz** [comment]
yes I found this, also it doesn't walk the DEFAULT expressions. Both are problematic.

**Comment by knz** [comment]
This bug still exists in v21.1

**Comment by mgartner** [comment]
Closing as duplicate of #102032.
