### ISSUE TITLE
TestDatabaseDescriptors is flaky: "illegal wireType 6"

### ISSUE THREAD

**Issue by mrtracy** [cockroachdb/cockroach#3373]
[#9985](https://circleci.com/gh/cockroachdb/cockroach/9985)

```
I1209 19:04:03.623843 855 storage/replica_command.go:451  auto-gc'ed 896fbf1f (7 intents)
F1209 19:04:03.625809 855 storage/replica_command.go:1422  failed to update Store after split: storage/replica_raftstorage.go:435: failed to lookup zone config for Range range=2 [/Table/1000-/Max): proto: illegal wireType 6
```

**Comment by tamird** [comment]
Can you repro this locally? Also, I've never seen this failure. Has it ever happened on master?

**Comment by tamird** [comment]
I stand corrected, this just failed on my branch in https://circleci.com/gh/cockroachdb/cockroach/10004

**Comment by tschottdorf** [comment]
some comments in #3776.

**Comment by petermattis** [comment]
I'll take a look at this. Looks straightforward to fix and I encountered a handful of times yesterday.

**Comment by petermattis** [comment]
Reproduces easily (within a few hundred runs) with `make stressrace STRESSFLAGS="-p 96" PKG=./sql TESTS=TestDatabaseDescriptor`.

**Comment by bdarnell** [comment]
Our definition of "reproduces easily" has been ratcheting upwards lately.
