### ISSUE TITLE
sql: in the IndexDescriptor message, parallel column arrays should be normalized into submessages

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#3387]
`column_names`, `column_directions` and `column_ids` should be grouped together.
https://github.com/cockroachdb/cockroach/blob/1133980b5df58fc54f4151a8781bb18f700162da/sql/structured.proto#L80

**Comment by petermattis** [comment]
I'm guessing we're not going to do this now given the headache of performing the data migration. Re-open if you disagree.

**Comment by tamird** [comment]
Let's leave it open. This one is actually on the easy side of things since it's upstream of raft, and might make for a good early exercise.

**Comment by petermattis** [comment]
Using this to test migration seems questionable. We'd have to support the old and new protos for quite a while.

**Comment by bdarnell** [comment]
Let's not look for unnecessary changes just to test migrations. We'll have enough real migrations to do soon enough.

**Comment by tamird** [comment]
I'm not suggesting we prioritize this, just that we not close the issue.

**Comment by petermattis** [comment]
@andreimatei, @knz, @RaduBerinde Are we ever going to bother to do this? Marking this as `Later`, but I'd also be happy to see it closed.

**Comment by knz** [comment]
This is not a "cleanup" but really a performance and stability issue. (Locality of access between the things, ensuring they have the same size.)

I would indeed keep "later" but keep the issue open and change the classification.

**Comment by knz** [comment]
I changed my mind on the benefits of this. Having 3 arrays of homogeneous values provides better access behavior than 1 array of 3-value tuples of heterogeneous types.
