### ISSUE TITLE
statically link everything but libc

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#3392]
Right now, we are statically linking everything, including libc. This forces us to use musl, because statically linking glibc is [insane](https://sourceware.org/bugzilla/show_bug.cgi?id=19341).

We would like to statically link everything but libc, so that we aren't forced to use such an exotic configuration. This may require us to rethink our current collection of `c-*` repositories so that we can use upstream build systems to build static binaries which we link against, while letting the `go` tool dynamically link everything else (which we hope is just libc).

**Comment by petermattis** [comment]
Why do you think the `c-*` repositories are related to this? Those repositories result in the generation of static libs.

**Comment by tamird** [comment]
Not so; static libs are only created if the top level cockroach build is static.

**Comment by petermattis** [comment]
Eh, `c-rocksdb` is not linked dynamically into my cockroach binaries on Mac OS X. Does this differ on Linux?

**Comment by mberhault** [comment]
nope:
```
$ ldd cockroach 
	linux-vdso.so.1 =>  (0x00007fff7654d000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f3647c1d000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f36479ff000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f36476fb000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f36473f5000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f36471df000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3646e1a000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f3647e25000)
```

where `cockroach` is from a plain `make build`

**Comment by tamird** [comment]
I guess I'm fuzzy on the semantics; I expect that libstdc++ is dynamically linked into cockroach as a result of rocksdb's inclusion (and how it was built), but perhaps that is incorrect.

**Comment by petermattis** [comment]
The decision to link libstdc++ statically or dynamically is made when the final cockroach binary is linked and is purely determine by the presence or absence of the `-static` flag being passed to the external linker (e.g. `clang++` or `g++`). I'm about 99% certain that the `c-*` repositories do not affect this.

**Comment by petermattis** [comment]
My readings on the internet suggest that `glibc = {librt,libpthread,libm,libc}` and that all of those libraries should be dynamically linked. `linux-vdso.so.1` (virtual dynamic shared object) comes from the kernel. And `ld-linux-x86-64.so` is the dynamic loader and is required by any program that is linked against shared libraries. That leaves `libstdc++` and `libgcc` that we would like to link statically. Luckily, there is a flag for that (actually 2 flags): `-static-libgcc` and `-static-libstdc++`. I suggest we replace usage of `-static` with those two flags.
