### ISSUE TITLE
sql: while renaming database I am getting - "pq: descriptor not found"

### ISSUE THREAD

**Issue by irshadhasmat** [cockroachdb/cockroach#34005]
Hi Team,

While renaming Database I am getting - "pq: descriptor not found"

ALTER DATABASE a_db RENAME TO b_db;

output: pq: descriptor not found

Server version: CockroachDB CCL v2.1.3 (x86_64-unknown-linux-gnu, built 2018/12/17 19:15:31, go1.10.3) (same version as client)

**Comment by jordanlewis** [comment]
@vivekmenezes PTAL for triage

**Comment by knz** [comment]
@irshadhasmat thank you for your report. Can you provide us more details to reproduce the issue? I have ran the following commands in `cockroach demo` and it appears to work fine:

```sql
> create database a_db;
> alter database a_db rename to b_db;
```

There is no error in that case. How did **you** find an error?

**Comment by jordanlewis** [comment]
Closing as there's been no more data on this issue. @irshadhasmat please feel free to continue commenting if you need further support,
