### ISSUE TITLE
opt: Prune unnecessary columns for set operators

### ISSUE THREAD

**Issue by andy-kimball** [cockroachdb/cockroach#34019]
I recently encountered a customer query that highlighted a missing optimizer rule. The query performs a COUNT(*) over a UNION, similar to this:
```
SELECT COUNT(*)
FROM
(
  SELECT * FROM abc WHERE b IN [1, 2, 3]
  UNION
  SELECT * FROM xyz WHERE y IN [4, 5, 6]
)
```

The performance did not meet expectations because the tables had a large number of columns, and the columns were all being projected by the UNION operator, even though the COUNT does not need them.

The solution is to add new prune column rules for the set operators, such as `PruneUnionCols`, `PruneIntersectCols`, etc. Like other similar rules, this rule will discard columns that are not needed to compute the result.

**Comment by andy-kimball** [comment]
Another good starter project.

**Comment by RaduBerinde** [comment]
Note that columns can be pruned with `UNION ALL` but not with `UNION` (in the general case).
One interesting related rule would be to convert `UNION` to `UNION ALL` when we know they are the same (e.g. if the two sides have conflicting constraints on one column)
