### ISSUE TITLE
backup/restore: Cannot incremental backup after restoring data

### ISSUE THREAD

**Issue by tim-o** [cockroachdb/cockroach#34031]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

In v2.1.2, I'm unable to use an incremental backup after a restore. After backing up, dropping my database, and restoring it, I'm not able to use incremental backup on the same DB. Instead, I receive a `pq: previous backup does not contain table` error.

@rolandcrosby - assigning you for triage and S-3 for now since AFAIK this has not impacted more than one user.

**To Reproduce**

```
root@:26257/test2> create table foo as select * from test.bar;
SELECT 3

Time: 22.143577ms

root@:26257/test2> backup database test2 to 'nodelocal:///backup_test';
        job_id       |  status   | fraction_completed | rows | index_entries | system_records | bytes
+--------------------+-----------+--------------------+------+---------------+----------------+-------+
  417833607389216769 | succeeded |                  1 |    3 |             0 |              0 |    78
(1 row)

Time: 81.739223ms

root@:26257/test2> use test;
SET

Time: 417.152µs

root@:26257/test> drop database test2 cascade;
DROP DATABASE

Time: 84.883501ms

root@:26257/test> restore database test2 from 'nodelocal:///backup_test';
        job_id       |  status   | fraction_completed | rows | index_entries | system_records | bytes
+--------------------+-----------+--------------------+------+---------------+----------------+-------+
  417833815240343553 | succeeded |                  1 |    3 |             0 |              0 |    78
(1 row)

Time: 103.036198ms

root@:26257/test> use test2;
SET

Time: 1.895781ms

root@:26257/test2> select * from foo;
  id | description
+----+-------------+
   1 | Hello
   2 | Hello
   3 | Hi
(3 rows)

Time: 11.485552ms

root@:26257/test2> insert into foo (id, description) values (4,'Hi There');
INSERT 1

Time: 2.093655ms

root@:26257/test2> backup database test2 to 'nodelocal:///backup_test_incremented' incremental from 'nodelocal:///backup_test';
pq: previous backup does not contain table "foo"
```

**Comment by rolandcrosby** [comment]
I think this behavior may be intended. If you back up a table, then drop it, then run RESTORE, your new table will contain the same information as the old table, but it's not going to *be* the same table. In other words, from CockroachDB's perspective, the restored table isn't the same table that the original backup was created from, so an incremental backup can't be made.

The error message needs work here -- the previous backup does contain a table named "foo", but it's not the same table from the perspective of BACKUP.

@dt how does BACKUP determine which table a given backup corresponds to? Is there an internal ID or something? If RESTORE somehow kept track of the internal table ID from the original backup, would it then be possible to create new incremental backups on top of the original backup? Or would that be ill-advised for other reasons?

**Comment by rolandcrosby** [comment]
@zhangquan913 your other issue at the end of that forum post, with the phantom warnings about test_db, definitely look like a bug. Could you open a second issue about that problem, listing the steps you took?

**Comment by zhangquan913** [comment]
@rolandcrosby Ticket created https://github.com/cockroachdb/cockroach/issues/34038

**Comment by dt** [comment]
@rolandcrosby By ID: tables in backups are identified by their table ID from the backing-up cluster. Incremental backups capture a diff of the KV data for some set of IDs -- when making one, we first consult the supplied prior backup to see what IDs it contains and until what time it contains their data, then we check if we have complete MVCC history currently on hand for the key-space of those IDs. If we do, we can generate a diff of that key space from that time to now. That however assumes we're looking at the same key space -- it has to be the same table ID from the same cluster. We store the cluster ID in the backup to check this, and compare tables by their unique ID.

**Comment by dt** [comment]
As stated above, we can only do an incremental backup of _the same table_ as is in a prior backup. A restore makes a new table with the old table's data, but that is not the same table, so there isn't much we can do here.
