### ISSUE TITLE
ui: flash of "this database has no tables" before tables loaded

### ISSUE THREAD

**Issue by vilterp** [cockroachdb/cockroach#34039]
While the RPC to get table names is running, the databases page says "this database has no tables", when the database does in fact have tables.

![image](https://user-images.githubusercontent.com/7341/51215040-a9682000-18ed-11e9-812f-848f275c73fa.png)

It should show a spinner or something instead (prob using `<Loading />` component). (Or combine everything into one big RPC 😛)

cc @couchand @celiala

**Comment by couchand** [comment]
Closed by #32219
