### ISSUE TITLE
cli: debug zip should attempt to collect metrics from all the nodes

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#34042]
Currently it only does so from the node on which the command runs.

**Comment by knz** [comment]
cc @ajwerner not sure whether that's up your alley.

**Comment by ajwerner** [comment]
Sure is. I’ll type it up.

**Comment by ajwerner** [comment]
Do y'all know if there's a good reason why we use SQL as opposed to a metrics request to get the node metrics?

**Comment by andreimatei** [comment]
I don't, nor do I know exactly what "a metrics request" is technically. FWIW, one thing to keep in mind is that this tool needs to do its best to get as much info as possible when nodes are down (and so the SQL query is currently operating on a virtual table that just reports local in-memory data).

**Comment by ajwerner** [comment]
Yeah the Metrics request returns go runtime metrics it seems.

I'm going to split this into two PRs, the stacks one is quick and easy. The reason I suspect that metrics are currently gathered only from the node at which the command was directed and not all nodes is that we don't have an RPC mechanism to get at the data via a single gateway. 

When we fetch information on the cluster nodes we do get addresses for each node but these addresses won't always be routable from the perspective of the requesting client. For example, when  there is a proxy which routes to nodes and has an external address but within the cluster nodes communicate to each other local addresses.

I see two approaches to dealing with this.

1) Extract the addresses for each node from NodeStatus and create SQL connections to each node
   * \+ simpler to implement
   * \- may fail in common situations, would need to change the error handling to not totally barf when we cannot route to other nodes based on their gossipped addresses.
2) Extend the virtual table for metrics to allow querying metrics from different nodes
   * \+ more robust and ultimately from the client perspective
   * \- more work

Thoughts?

**Comment by ajwerner** [comment]
Actually, it seems like we already grab stacks from each of the nodes.

**Comment by ajwerner** [comment]
Turns out we already collect all of the node metrics inside of node status. The metrics file actually ends up being redundant (although maybe somewhat easier to read). The data in `nodes/%d/status` is the same data that drives `crdb_internal.node_metrics`. I'm closing this issue because it seems we already collect the requested information.
