### ISSUE TITLE
server: excessive certificate permission checking

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#34040]
A customer ran into an issue where some certificates in the certs dir weren't readable by the user running cockroach, and this prevents the server from starting. The certs in question were client certs though, not node certs, so I don't think there was a good reason for those files to be checked at all.

Separately, another reason for the server not starting that we ran into was the cockroach user not having the `x` permission on the directory containing all the certs. The fatal log message wasn't clear about that, though. I forgot what it was exactly.

A third issue was that the node also crashes when the certificates have too much permissions: I think if any other users can read it. I guess this was intentional... I'm not completely sure what it accomplishes, though.

@mberhault you want this one, assuming there's something to do here?
cc @bdarnell

**Comment by bdarnell** [comment]
Yeah, we should only validate permissions of the certs we're actually going to use, and not just scan over everything in the directory. 

The `x` permission thing is just standard unix permissions. Not much we can do there besides maybe checking for this specific case and giving it a better error message.

Requiring that permissions on key files not be too loose is something we borrowed from ssh. It may be a little excessive but it's probably good to be paranoid given the security implications of leaking these keys.

**Comment by mberhault** [comment]
I've been unable to reproduce the first issue (client cert of key unreadable). The requirements for started the server are being able to read and load ca.crt, node.crt/key, and if they exist: ui.crt/key, client.node.crt/key. Other client certificates are stat'ed because we stat everything matching the naming scheme but they are not loaded and errors do not cause aborts.

**Comment by andreimatei** [comment]
> Other client certificates are stat'ed because we stat everything matching the naming scheme but they are not loaded and errors do not cause aborts.

So error to stat is ignored? It's possible I was confused when I was looking at the operator; it was a chaotic debugging session.

> The x permission thing is just standard unix permissions. Not much we can do there besides maybe checking for this specific case and giving it a better error message.

Yeah, I remember the error message being confusing.


Generally, feel free to close as far as I'm concerned if there's nothing to do about any of it.

**Comment by knz** [comment]
I investigated and so far I can see the missing perm is not blocking. Feel free to re-open if you envision a better improvement.
