### ISSUE TITLE
distsqlrun: possible deadlock in flowRegistry

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#34041]
I have a debug zip showing what I believe to be a deadlock, or at least a temporary denial of service of sorts. The call below is pushing an error to a RowChannel (a possibly blocking call) while holding `fr.Lock`. So if the `Push()` blocks, nobody can get into the registry.
In the particular case I'm looking at, the push was blocked for 2m by the time the goroutine dump was taken, and indeed many other queries were trying to get into the registry and blocking.
Not sure what to do exactly, haven't re-read the `flowRegistry` code. If it's not possible to push without the lock, maybe we can make a non-blocking push for errors in particular.

Some more details: `is.receiver` is a `RowChannel` and there's also a `routerBase` trying to push to it, also blocked for 2m.

Link to the debug.zip we got from the customer (internal only): https://drive.google.com/open?id=1fbexxTV9S7cn2rPAFp1TvweQ7rfUnjU7

@RaduBerinde, @jordanlewis who wants this?

**Comment by RaduBerinde** [comment]
I assume this is the `Push` inside `RegisterFlow`? I don't see a problem with moving that error handling outside of the lock (or even behind a `go`).

**Comment by andreimatei** [comment]
Yeah, it's this call, I forgot to put the link:
https://github.com/cockroachdb/cockroach/blob/c10ce747e281cc3d2b91ac49224491da4c82096c/pkg/sql/distsqlrun/flow_registry.go#L221

**Comment by RaduBerinde** [comment]
`fr.finishInboundStreamLocked` needs to be called under the lock. I'm like 99% sure it's ok to first `finishInboundStreamLocked` and then `Push` the error later.

**Comment by andreimatei** [comment]
Cool. I'm guessing you don't want to do something about it yourself, so let's make it official: passing to @jordanlewis to find a victim.

**Comment by jordanlewis** [comment]
Great find... @asubiotto please take a look at this next week when you get back from vacation. Could be a hot thread to pull on!

**Comment by andreimatei** [comment]
friendly ping :)

**Comment by asubiotto** [comment]
Ack, will take a look

**Comment by asubiotto** [comment]
Thanks for noticing this, this is definitely an issue, although I'm also concerned as to why the Push would block. @andreimatei, I haven't taken a look at the dump yet but wondering if you noticed anything?
