### ISSUE TITLE
raft: use learner replicas instead of preemptive snapshots

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#34058]
We could stop using preemptive snapshots if we used Raft's support for [learner replicas](https://github.com/cockroachdb/vendored/blob/3f5e5955a4eeffd4c82010e2c249893d94976ffc/go.etcd.io/etcd/raft/raft.go#L117-L126). These catch up on the log and can receive snapshots, but they don't vote, campaign, or count in the commit quorum.

Doing so would unify Raft and preemptive snapshots, would allow us to treat learners as regular replicas in much of the code, and would prevent the replica GC queue from erroneously removing preemptive snapshots (which is a medium-size nuisance today). Instead, we'd need a mechanism that regularly inspects the range descriptor for learners and decides whether a learner should be removed (for example, after a replication change fails without cleaning up the learner).

Naively we could try to rely on the Raft snapshot queue to catch up the learners, but that queue works very poorly. Until it has been redesigned, we would probably be better off sending the snapshot manually like today.

Learner replicas could also be used in conjunction with follower reads to enable historical queries at a remote location. For example, a satellite DC could hold a learner replica of each range whose full members live in another DC, and would allow the satellite DC to carry out historical reads on a copy of the data. Whether this is useful in the presence of CDC is speculation, but I think @bdarnell had opinions in the past.

cc @nvanbenschoten (who suggested learner replicas)

**Comment by petermattis** [comment]
I'm 👍 on trying to reduce the complexity around preemptive snapshots.

> Naively we could try to rely on the Raft snapshot queue to catch up the learners, but that queue works very poorly. Until it has been redesigned, we would probably be better off sending the snapshot manually like today.

The Raft snapshot queue exists to prevent a thundering herd of snapshot activity under various scenarios (i.e. a node being offline for a few minutes, such that Raft logs are truncated). I'm not sure what the "manually like today" option means. Using the preemptive mechanism? Can you elaborate?

**Comment by tbg** [comment]
Yes. A preemptive snapshot is essentially a real snapshot, just for replicaID zero with special behavior around snapshot reservations and a special receive path. I'm suggesting to send a manual snapshot from the replicate queue initially. This would be a Raft snapshot, but with the same rate limiting and reservation behavior applied, though once the snapshot reaches the Raft group it looks like "just another snapshot".

Raft snapshots have lots of unfortunate behavior. The one that matters most in the context of this change is that a Raft snapshot may be held up by the reservation semaphore on the receiver, which would then block the sender's replicate queue.

Ultimately Raft and learner-Raft snapshots should be sent through the snapshot queue, but until the Raft snapshot queue "just works" that's a bad idea. Making the Raft snapshot queue "good" is a separate engineering effort. My observation is that it seems straightforward to not entangle them right from the get-go while maintaining the benefit of removing preemptive snapshots.

**Comment by petermattis** [comment]
Got it. So you would have the replicate queue still send the snapshot (which limits the number of outstanding "preemptive" snapshots on the sender), and leave the existing Raft snapshot queue unchanged?

Btw, can you refresh my memory about the problems with the Raft snapshot queue? It is unfortunate that a problem with one range sending a snapshot can block sending snapshots for another range, but that is also part of the point.

**Comment by tbg** [comment]
Yep, exactly. This is really just a workaround until we can trust the raft snap queue.

> Btw, can you refresh my memory about the problems with the Raft snapshot queue?

https://github.com/cockroachdb/cockroach/issues/32046#issuecomment-434517143 has a little bit on this. Basically there's a lot of little badness adding up to giant badness. [reserveSnapshot](https://github.com/cockroachdb/cockroach/blob/3ef7f68469738d99c59e44d2eeb5e8925542a910/pkg/storage/store_snapshot.go#L342 blocks Raft snapshots on the receiver (it rejects preemptive ones, which is a lot better much of the time). There is also this backoff around "store throttling", where we won't rebalance to a store for 5s after an error. I believe we trigger that behavior accidentally all the time, which of course is terrible for swift rebalancing.

There's also, still, priority inversion. A preemptive snapshot reservation sticks around for ~32s (2mb/s rate limit), so a Raft snapshot may block for 32s or even a multiple of that, and in turn that blocks a Raft snapshot queue somewhere. It's even possible that you block before the snapshot is simply rejected because there's some replica in the way (have to double check that, but wouldn't surprise me).

And lastly we don't have flow control for the Raft snapshots except the hardcoded 8mb/s. We'd want to use more when we can. (This is a secondary concern at the moment, if we got close to 8mb/s of effective throughput on snapshot queue processing that'd be a big win).

The goal should be that a 64 1mb snaps (perhaps to different receivers) can be processed in approximately the time of a single 64mb snap (won't quite get as fast, but you get the idea), even when the receivers sometimes can't accept the snapshots right away. As long as there is one who can accept something, they should get it.

**Comment by bdarnell** [comment]
> These catch up on the log and can receive snapshots, but they don't vote, campaign, or count in the commit quorum.

Do they count towards the quota pool? If they do, then these non-voting learner replicas could still impact write performance. If not, there are various sorts of pathological loops that could result in snapshots being sent repeatedly.

I think this is generally a good idea (if learner replicas had been implemented in etcd/raft when we were starting out, we'd have used them instead of implementing preemptive snapshots), but this is going to be a lot of work to tune and debug.

**Comment by tbg** [comment]
It's definitely a larger change, especially since it matters in so many places (there'll also be plenty of UI work).

The quota pool should ignore the learners. We already don't truncate the log while a snapshot is inflight, so the only effect of that is that they'll be allowed to fall behind arbitrarily, so the Raft log can grow without bounds until the learner either gets upgraded or removed.

**Comment by bdarnell** [comment]
> We already don't truncate the log while a snapshot is inflight, so the only effect of that is that they'll be allowed to fall behind arbitrarily, so the Raft log can grow without bounds until the learner either gets upgraded or removed.

As long as they're temporary. My concern about the quota pool is if we start to have permanent non-voting replicas for follower reads (as suggested).

**Comment by tbg** [comment]
Ah, yes. This is a bigger problem. It seems to make sense to backpressure in that case, though perhaps less aggressively than for quorum members. Anyway, that won't be happening anytime soon, I also don't know if there's a strong enough incentive after CDC.

**Comment by ajwerner** [comment]
I'm closing this. Learner replicas shipped in 19.2.
