### ISSUE TITLE
OOM for Tracker Network when running large queries

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#34060]
Tracker Network is sometimes seeing nodes OOM. I've seen the oom-killer report a heap (anon-rss) of 65GB.
I've got a database backup (attached below, internal only) and the following two queries. 

```
     SELECT
                    platform_id,
                    user_id,
                    username player_name,
                    country_code,
                    avatar_url,
                    twitter,
                    twitch,
                    supporter_end_date,
                    total_games_played matches,
                    kills stat_value,
                    RANK() OVER(ORDER BY kills desc) stat_rank
                FROM bo4_careerstats tbl INNER JOIN bo4_account actTbl ON tbl.Id = actTbl.Id AS OF SYSTEM TIME '-1s'
                WHERE 1=1   AND actTbl.is_banned = false
                ORDER BY stat_rank
                LIMIT @take OFFSET @skip;
```

and 

```
with CTE as (
    select kills as value, 
        case 
            when (CUME_DIST() over (order by kills desc)) < 0.05 then ceiling(CUME_DIST() over (order by kills desc) * 100 * 10) / 10
            else ceiling(CUME_DIST() over (order by kills desc) * 100)
        end cnt     
        from bo4_careerstats as of system time '-1s'
        WHERE 1=1
)
select cnt as percentile, min(value) as value from CTE as of system time '-1s' group by cnt order by cnt desc 
```
(this 2nd one comes with this comment: "this is ran 1 at a time, on a schedule, this is not called by users.  Traditionally I dont think this causes any problems")

Also the following info:
"
We're running about 35 queries per 5m.
the avg query is taking 35s
and many are failing (we have a 60s timeout)
"

We have a debug.zip too showing with heap profiles showing pretty large heaps - I think around 20G. This profile was taken soon after one of the nodes OOMed.

db backup (1.5G): https://drive.google.com/open?id=10Qlzc8NGF3joyPabdsrm8wzv4PLrig9z
debug.zip: https://drive.google.com/open?id=1fbexxTV9S7cn2rPAFp1TvweQ7rfUnjU7

@jordanlewis will you find a victim?

**Comment by andreimatei** [comment]
Tracker Networks runs nodes with `--max-sql-memory=.25 --cache=.25` on machines with 64GB or RAM, no swap.

**Comment by jordanlewis** [comment]
@yuzefovich please take a look at this while investigating the window function disk spillage.

**Comment by andreimatei** [comment]
spilling to disk is one issue, but there's also the problem of the OOM (which is bigger in my book). Spill or no spill, we should never crash and it seemed like in this case our usage was waaay above the set memory limits. Where that usage was exactly, I don't know.

**Comment by yuzefovich** [comment]
A quick update: I have several PRs open that will allow for window functions to spill to disk, so that should help with this issue. I was able to run the two queries mentioned here on my local machine, and both completed in 21-22 seconds and both had to spill to disk. I haven't looked into the OOM Andrei mentioned.

**Comment by asubiotto** [comment]
Closing due to age, we've made several memory monitoring improvements since then.
