### ISSUE TITLE
build: source code cannot compile on PowerPC(ppc64le)

### ISSUE THREAD

**Issue by hehesky** [cockroachdb/cockroach#34097]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:
On a ppc64le machine, build from source as documented here https://www.cockroachlabs.com/docs/stable/install-cockroachdb-linux.html#build-from-source

Upon `make build`, the process will fail.

**To Reproduce**

If possible, provide steps to reproduce the behavior:

1. Download source code to a ppc64le machine with proper environment. Extract it
2. Run `make build`
3. After a while an error will pop out and the process stops

```
-- Build files have been written to: /root/cockroach-v2.1.3/native/powerpc64le-linux-gnu/rocksdb
Scanning dependencies of target build_version
[  0%] Building CXX object CMakeFiles/build_version.dir/build_version.cc.o
c++: error: unrecognized command line option '-march=native'; did you mean '-mcpu=native'?
CMakeFiles/build_version.dir/build.make:62: recipe for target 'CMakeFiles/build_version.dir/build_version.cc.o' failed
make[5]: *** [CMakeFiles/build_version.dir/build_version.cc.o] Error 1
CMakeFiles/Makefile2:4002: recipe for target 'CMakeFiles/build_version.dir/all' failed
make[4]: *** [CMakeFiles/build_version.dir/all] Error 2
CMakeFiles/Makefile2:2494: recipe for target 'CMakeFiles/rocksdb.dir/rule' failed
make[3]: *** [CMakeFiles/rocksdb.dir/rule] Error 2
Makefile:979: recipe for target 'rocksdb' failed
make[2]: *** [rocksdb] Error 2
Makefile:622: recipe for target '/root/cockroach-v2.1.3/native/powerpc64le-linux-gnu/rocksdb/librocksdb.a' failed
make[1]: *** [/root/cockroach-v2.1.3/native/powerpc64le-linux-gnu/rocksdb/librocksdb.a] Error 2
make[1]: *** Waiting for unfinished jobs....
```

```
Scanning dependencies of target protoc
[ 52%] Building CXX object CMakeFiles/protoc.dir/root/cockroach-v2.1.3/src/github.com/cockroachdb/cockroach/c-deps/protobuf/src/google/protobuf/compiler/main.cc.o
[ 53%] Linking CXX executable protoc
make[1]: Leaving directory '/root/cockroach-v2.1.3/src/github.com/cockroachdb/cockroach'
Makefile:6: recipe for target 'all' failed
make: *** [all] Error 2
```

**Expected behavior**
Cockroachdb should compile from source on ppc64le

**Environment:**
 - CockroachDB 2.1.3 source code
 - Server OS:  Ubuntu 18.04 LTS
 - ppc64le architecture

Epic CRDB-10447

Jira issue: CRDB-4670

**Comment by petermattis** [comment]
@hehesky Our build system doesn't currently support PowerPC machines because we don't have any such machines to test on and it isn't something that users have asked for. Temporary access might allow us to fix the problem in the near term, but PowerPC support would likely rot unless we're building for it regularly. If you're willing to do the necessary work and keep it up to date, we'd be happy to consider merging patches (assuming they are not too intrusive, though I think the precedent of Windows support suggests they shouldn't be).

**Comment by knz** [comment]
@hehesky also the error message suggests your C++ compiler is incompatible with CockroachDB. We suggest GCC 7.3+ or LLVM Clang 6+.

**Comment by knz** [comment]
The command that's being run is `c++`, not `gcc`. Is `c++` also pointing to the same gcc?

In any case you've seen the error: `'-march=native'` is not a supported flag. If your gcc build doesn't support it, you'll need to muck in the RocksDB configure script / makefile to avoid it.

**Comment by hehesky** [comment]
@knz  g++ is the same version.
``` 
root@subdean1:~# g++ --version
g++ (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

root@subdean1:~#
```

**Comment by knz** [comment]
the command is `c++` not `g++`

**Comment by hehesky** [comment]
```
root@subdean1:~# c++ --version
c++ (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by ipoddar-ibm** [comment]
@petermattis it is possible to build continuously on ppc64le in travis ci now. Here is an example .travis.yml file: https://github.com/IBM/powerai/blob/master/.travis.yml and build log: https://travis-ci.org/IBM/powerai

**Comment by petermattis** [comment]
@ipoddar-ibm Interesting, I wasn't aware that Travis CI had such support. Unfortunately, we don't currently use Travis CI for our testing. Switching from our current system (Teamcity) to Travis CI would be a large undertaking. Adding support for Travis CI in addition to Teamcity would be a large undertaking. It is possible that there could be some minimal smoke testing done on Travis CI to verify that ppc64le doesn't rot. If this is something you're interested in, we could lend a bit of guidance.

**Comment by hehesky** [comment]
We managed to build it on ppc64le (Ubuntu) with the following:

1. Download the source code and extract it
2. Install the prerequisites
3. Install ncurses library:`apt-get install -y libncurses5-dev`
4. In `src/github.com/cockroachdb/cockroach/c-deps/rocksdb/CMakeLists.txt` file comment this line with “#”; change
`set(CMAKE_CXX_FLAGS “${CMAKE_CXX_FLAGS} -march=native”)`
to
`# set(CMAKE_CXX_FLAGS “${CMAKE_CXX_FLAGS} -march=native”)`
5. Cleanup slice.s file (to fix go compilation error: slice.s:1: Error: junk at end of line, first unrecognized character is `/’)

    ```cp /dev/null src/github.com/cockroachdb/cockroach/pkg/storage/engine/slice.s```
6. Run `make build`
