### ISSUE TITLE
storage: dynamically adjusted replica count heuristic is wonky

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#34122]
The target replica count for a range is computed is limited by the available nodes in the cluster (see `StorePool.GetAvailableNodes` and `storage.GetNeededReplicas`). This is wonky. Consider what happens if you have a 15-node cluster with 15-way replication (as seen in a customer setup). Take down 5 nodes and wait for those nodes to be declared dead. `GetAvailableNodes` will now return 10 which will limit the target replication for the ranges to 9 (can't replicate to an even number). So we'll remove 6 replicas from each of the ranges, and we'll do so fairly quickly. If the 5 nodes are restarted, each of the ranges on those nodes will first have to wait for replica GC, and then we'll have to wait for up-replication to occur. This seems less than optimal.

This can be triggered without waiting for the down nodes to be declared dead. If instead of stopping 5 nodes, the entire cluster is stopped and then only 10 nodes are started, the store pool will only have 10 node descriptors and the same problem will occur. 

Here are steps to hork a local 15-node cluster:

```
~ roachprod create local -n 15
~ roachprod start local --sequential
~ roachprod sql local:1 -- -e "ALTER RANGE default CONFIGURE ZONE USING num_replicas = 15"
~ roachprod sql local:1 -- -e "ALTER DATABASE system CONFIGURE ZONE USING num_replicas = 15"
~ roachprod sql local:1 -- -e "ALTER TABLE system.public.jobs CONFIGURE ZONE USING num_replicas = 15"
~ roachprod sql local:1 -- -e "ALTER RANGE meta CONFIGURE ZONE USING num_replicas = 15"
~ roachprod sql local:1 -- -e "ALTER RANGE system CONFIGURE ZONE USING num_replicas = 15"
~ roachprod sql local:1 -- -e "ALTER RANGE liveness CONFIGURE ZONE USING num_replicas = 15"
... wait for every node to have 20 ranges
~ roachprod stop local
~ roachprod start local:1-10
```

I'm not sure what is going on yet, but this looks very reproducible.

**Comment by petermattis** [comment]
Also easy to reproduce on a 9-node cluster with a replication factor of 9. Wait for full replication. Stop the cluster and restart nodes 1-6. A handful of ranges will appear unavailable. I didn't notice unavailable ranges on the 15-node cluster. Possible I just missed them.

**Comment by petermattis** [comment]
Here is what is going on in the 9-node cluster case. When all 9-nodes are up, a range has 9 replicas and everything is copacetic. When the cluster is taken down and restarted with 6-nodes, `StorePool.AvailableNodeCount` returns 6 (actually, it temporarily returns even fewer than that which is itself problematic) because there are only 6 node descriptors being gossiped. `GetNeededReplicas(9, 6)` returns a value of `5` (it refuses to return an even number for replication). So the replicate queue will start to down-replicate all of the 9-replica ranges to 5 replicas. 

This down-replication sounds reasonable on the surface, but it is fraught because there is no traffic on the cluster. `filterUnremovableReplicas` removes any replicas that are necessary for quorum, but it allows removal of replicas on the down nodes for which we don't know the state. Unfortunately, it also allows removal of replicas on the good nodes. The allocator logs clearly show what is happening to cause a range to become unavailable. We down-replicate from 9 replicas, to 8, to 7, to 6. If the replicas being removed are on the up nodes, we eventually hit a state where there is not a quorum of replicas on up nodes. This deficiency in `filterUnremovableReplicas` should be fixable. We should require that a quorum of replicas is on live nodes.

But I think we shouldn't be down-replicating in the first place. `StorePool.AvailableNodeCount` seems like a problematic signal for the number of nodes in the cluster. For one, it only returns nodes which have gossiped a node descriptor. Second, it only counts non-dead nodes. So after a node has been down for 5 minutes, we may start adjusting the target replication factor for all ranges in the cluster. That doesn't seem like the right thing to do. I think we should consider the cluster node count to be the number of nodes that have been added to the cluster minus the number of decommissioned nodes. If a node dies, it should still be considered part of the cluster until it is decommissioned.

@tbg, @bdarnell, @andreimatei Thoughts on the above? Am I missing anything about how this is supposed to be working?

**Comment by petermattis** [comment]
I think `StorePool.AvailableNodeCount` should be replaced with `NodeLiveness.AvailableNodeCount`. The latter would look at the node liveness records, skipping any nodes that have been decommissioned.

`filterUnremovableReplicas` had a bug due to the handling of "brand new replica". I have a fix on the way. This was only a problem because the calculation for `Replica.mu.lastReplicaAdded` had a bug which was causing it to be set to the maximum replica ID in the range whenever a replica was removed. I have a fix for this on the way. So the problem here appears to be the confluence of 3 separate problems.

**Comment by tbg** [comment]
Ugh. Thanks for digging into this, I'll have more comments on Tuesday. The dynamic replication factor is a lot more problematic than anticipated.

**Comment by bdarnell** [comment]
> I think StorePool.AvailableNodeCount should be replaced with NodeLiveness.AvailableNodeCount. The latter would look at the node liveness records, skipping any nodes that have been decommissioned.

Sounds reasonable to me.

For historical reference, #32949 was a previous attempt to fix the same issue.
