### ISSUE TITLE
storage: Load-based rebalancing doesn't put useful info into the range log

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#34130]
**Is your feature request related to a problem? Please describe.**
When the replicate queue does an action, it includes some useful debugging information in the associated `system.rangelog` entry. This is not true for range rebalancing actions initiated by the `StoreRebalancer`, since it uses the `RelocateRange` admin command which always just adds the reason "admin request" and gives no additional details. This is less than ideal because the range log has historically been the best way of debugging rebalancing decisions after-the-fact.

**Describe the solution you'd like**
For actions initiated by the `StoreRebalancer` to be differentiated from actions initiated by admins, and for the information that motivated the action to be included in the range log's `details` field.

Sorry for not filing an issue about this earlier, but creating now to reference from the rebalancing tech note.

**Comment by knz** [comment]
cc @tbg @nvanbenschoten for triage
