### ISSUE TITLE
sql: observation: CockroachDB v2.0 does not pick a good index, v2.1 does

### ISSUE THREAD

**Issue by idubrov** [cockroachdb/cockroach#34132]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

CockroachDB v2.0.6 (and v2.1 with cost-based optimizer turned off) do not select index that seems to be obviously (well, to me :) ) better for the query.

**To Reproduce**
If possible, provide steps to reproduce the behavior:

Run the following script on CockroachDB v2.0.6 (or on v2.1, but you need to add `SET optimizer = off`, problem does not reproduce with optimizer):

```
SET optimizer = off;
CREATE TABLE some_table(
  column0 VARCHAR(100) NOT NULL,
  column1 VARCHAR(100) NOT NULL,
  column2 VARCHAR(100) NOT NULL,
  column3 VARCHAR(100) NOT NULL,
  column4 VARCHAR(100) NULL,
  column5 VARCHAR(100) NULL,
  PRIMARY KEY (column0, column1, column2, column3),
  INDEX idx0 (column0, column3, column5)
);

EXPLAIN SELECT DISTINCT column2, column1
FROM some_table AS p0
WHERE
  column0 = 'col0' AND column3 = 'col3' AND column5 = 'col5' AND
  column2 = 'col2' AND column4 = 'col4';

CREATE INDEX idx1 ON some_table(column0, column3, column5, column4);

EXPLAIN SELECT DISTINCT column2, column1
FROM some_table AS p0
WHERE
  column0 = 'col0' AND column3 = 'col3' AND column5 = 'col5' AND
  column2 = 'col2' AND column4 = 'col4';


DROP TABLE some_table;
```

Here is what I see for two EXPLAINs.

The first EXPLAIN is before I create another index. For some reason, instead of using `idx0`, which will cover `column0`, `column3` and `column5` it decides to scan primary key (which only does `column0`):

```
    tree    | field  |                                         description                                          
+-----------+--------+---------------------------------------------------------------------------------------------+
  render    |        |                                                                                              
   └── scan |        |                                                                                              
            | table  | some_table@primary                                                                           
            | spans  | /"col0"-/"col0"/PrefixEnd                                                                    
            | filter | (((column3 = 'col3') AND (column5 = 'col5')) AND (column2 = 'col2')) AND (column4 = 'col4')  
```

However, after creating a slightly better index covering `(column0, column3, column5, column4)` (added `column4` at the end), it starts to do index scan:

```
    tree    | field  |                             description                              
+-----------+--------+---------------------------------------------------------------------+
  render    |        |                                                                      
   └── scan |        |                                                                      
            | table  | some_table@idx1                                                      
            | spans  | /"col0"/"col3"/"col5"/"col4"-/"col0"/"col3"/"col5"/"col4"/PrefixEnd  
            | filter | column2 = 'col2'                                                     
```

**Expected behavior**

It seems that it should pick `idx0` index? It looks like it is much better than `primary`.

**Environment:**
 - CockroachDB version v2.0.6 (and v2.1 with cost-based optimizer turned off)
 - OS: Mac OSX running on laptop
 - `cockroach sql`

**Comment by idubrov** [comment]
I guess the reason here is that if that "better" index is used, CockroachDB will have to lookup the row using the primary key so it can filter by `column4` (because it is not in the `idx0`).

And adding this `column4` to `idx1` make that index "perfect" in the sense that it covers all the columns we need.

Am I right?

**Comment by knz** [comment]
@idubrov thank you for your inquiry.

Tou are right that CockroachDB v2.0 was not able to select a good index in many case.

This is why we built a better query optimizer in CockroachDB v2.1.

Does this answer your question? Let us know if you need to know anything else.

Thank you
