### ISSUE TITLE
perf: performance anomaly after conflicting transactions

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#3415]
See the report below. Note that the transaction aborts are expected, but the 30 second hangs after killing one of the sessions are not.

> I have a file t.sql that looks like this:
>  
> set database = d1;
>  
> BEGIN TRANSACTION ISOLATION LEVEL SNAPSHOT;
>  
> update t1 set col2 = 101
> where col1 = 1;
>  
> update t2 set col2 = 101
> where col1 = 2;
> 
> update t3 set col2 = 101
> where col1 = 3;
>  
> update t4 set col2 = 101
> where col1 = 4;
>  
> commit;
>  
> And a small script like this:
>  
> #!/bin/sh
> while [ true ]
> do
>         cli.sh sql < t.sql
> done
>  
> If I kick off two of these simultaneously, I start seeing errors like this:
>  
> 127.0.0.1:8124>              ->              -> query error: txn "sql/executor.go:208 sql" id=a6590d06 key=/Table/1001/1/1/2 rw=false pri=95.13760591 iso=SNAPSHOT stat=PENDING epo=2 ts=1449262513.102872849,2 orig=1449262513.102872849,2 max=1449262513.352517605,0 failed to push "sql/executor.go:208 sql" id=a2aa0dd4 key=/Table/1001/1/1/2 rw=false pri=95.13760595 iso=SNAPSHOT stat=PENDING epo=0 ts=1449262513.102872849,1 orig=1449262513.039840460,0 max=1449262513.039840460,0
> 127.0.0.1:8124>              ->              -> query error: current transaction is aborted, commands ignored until end of transaction block
> 127.0.0.1:8124>              ->              -> query error: current transaction is aborted, commands ignored until end of transaction block
> 127.0.0.1:8124>              ->              -> query error: current transaction is aborted, commands ignored until end of transaction block
>  
> In other database systems, the first statement would acquire a row lock and then proceed while the other session would wait. I believe you said in CockroachDB that you will retry the entire transaction(?).  > Or is this normal behavior and it is up to the application to retry?
>  
> Also, if I change to serializable, it goes for a while cleanly and then hangs for some seconds and then I eventually get this:
>  
> 127.0.0.1:8124>              -> query error: retry txn "sql/executor.go:208 sql" id=644083bb key=/Table/1001/1/1/2 rw=true pri=44.36012620 iso=SERIALIZABLE stat=PENDING epo=1 ts=1449262925.897053242,1 orig=1449262925.897053242,1 max=1449262926.117495298,0
> 127.0.0.1:8124>              -> query error: retry txn "sql/executor.go:208 sql" id=71e215e5 key=/Table/1001/1/1/2 rw=true pri=91.48836736 iso=SERIALIZABLE stat=PENDING epo=1 ts=1449262926.473039865,1 orig=1449262926.473039865,1 max=1449262926.658550739,0
> 127.0.0.1:8124>              -> query error: retry txn "sql/executor.go:208 sql" id=d9a55636 key=/Table/1001/1/1/2 rw=true pri=75.26471847 iso=SERIALIZABLE stat=PENDING epo=1 ts=1449262926.959829330,1 orig=1449262926.959829330,1 max=1449262927.203671455,0
> 127.0.0.1:8124>              -> query error: retry txn "sql/executor.go:208 sql" id=a5eec30f key=/Table/1001/1/1/2 rw=true pri=28.54335421 iso=SERIALIZABLE stat=PENDING epo=1 ts=1449262927.162214518,1 orig=1449262927.162214518,1 max=1449262927.405083656,0
> 127.0.0.1:8124>              ->              -> query error: txn "sql/executor.go:208 sql" id=d9ca8883 key=/Table/1001/1/1/2 rw=false pri=93.13977873 iso=SERIALIZABLE stat=PENDING epo=2 ts=1449262927.341600418,1 orig=1449262927.341600418,1 max=1449262927.546123743,0 failed to push "sql/executor.go:208 sql" id=33c23ce8 key=/Table/1001/1/1/2 rw=false pri=56.92358858 iso=SERIALIZABLE stat=PENDING epo=0 ts=1449262927.341600418,0 orig=1449262927.341600418,0 max=1449262927.341600418,0
> 127.0.0.1:8124>              ->              -> query error: current transaction is aborted, commands ignored until end of transaction block
>  
> If I kill one of the sessions, the second session continues, but very slowly, hanging for 30 seconds, then rapidly doing a few transactions, then hanging again, for a while, etc.

**Comment by tschottdorf** [comment]
Any word on the table schema and existing data?

**Comment by petermattis** [comment]
Checking...

**Comment by nvanbenschoten** [comment]
Did we ever hear back here about the table schema or the existing data in the tables when we saw this issue? Also, I'm assuming this is running on a single node, right?

**Comment by petermattis** [comment]
Nope, never heard back about the table schema. The individual who reported the problem was doing simple tests, so I'd try a simple schema. It is very possible this is no longer a problem, but we should put a little bit of effort into trying to reproduce.

**Comment by nvanbenschoten** [comment]
I've set up a pretty similar scenario and I'm not seeing any hanging when I kill of one of the sessions. In fact, the other session immediately improves its throughput, as I would expect.

Any idea what the SHA was of the version the error was reported on? Or the date, as it seems like this issue was copied from somewhere? I'd like to be able to go back an reproduce it so that we can safely conclude that the issue has been fixed in more recent versions.

**Comment by petermattis** [comment]
This was reported on 12/4/15.

**Comment by tschottdorf** [comment]
If you're doing something similar enough and you can't see the problems, they're likely gone. A lot has changed since.

**Comment by nvanbenschoten** [comment]
I went back to a build at the beginning of December and wasn't able to reproduce the issue either. I'm going to close this for now, and we can re-open if we see an issue like this again.
