### ISSUE TITLE
sql: `information_schema.columns.crdb_sql_type` contains garbage for some int columns

### ISSUE THREAD

**Issue by NathanRThomas** [cockroachdb/cockroach#34161]
**Describe the problem**

database dump started failing some time ago.  I'm sorry i'm not sure if it was around the time of an upgrade or not.

Dump call fails with the message

>Error: type 4 is not a valid CockroachDB type
>Failed running “dump”

**To Reproduce**

> /usr/local/bin/cockroach dump labs --certs-dir=/var/certs --host=10.10.11.12 | bzip2 > dump.sql.bz2

**Environment:**
 - CockroachDB version 2.1.3
 - Server OS: ubuntu 16.0.4
 - Client app: cockroach

I had previously opened a forum topic here
https://forum.cockroachlabs.com/t/failed-running-dump/2344

As per the comment i created the requested log file and sent it to support, since it does contain all our database tables/columns.

**Comment by knz** [comment]
@tim-o can you forward this file to me thanks.

@bobvawter  @mjibson we'll look at this together; the error `type 4 is not a valid CockroachDB type` means that the string `"4"` was present in the `crdb_data_type` column somehow.

**Comment by roncrdb** [comment]
@knz I've sent over the file.

**Comment by knz** [comment]
@NathanRThomas thanks for the data. Two additional questions:

1) how did you create the table called `answers` originally? has there been a schema change over it?

2) what is the output of `SHOW CREATE labs.answers`? Thanks


(Note to self/team: there is indeed a column in `information_schema.columns` where `crdb_sql_type` is exactly the string "4". We need to figure out how that comes to be.)

**Comment by knz** [comment]
I have found the source of the bug. Patch incoming.

**Comment by NathanRThomas** [comment]
for the answers table, currently:
show create table answers;
  table_name |                                                create_statement
+------------+----------------------------------------------------------------------------------------------------------------+
  answers    | CREATE TABLE answers (
             |     id INT NOT NULL DEFAULT unique_rowid(),
             |     question_id INT NOT NULL,
             |     attributes STRING NOT NULL DEFAULT '':::STRING,
             |     display_order INT NOT NULL DEFAULT 0:::INT,
             |     next_flow_id INT NOT NULL DEFAULT 0:::INT,
             |     isle_id INT NOT NULL DEFAULT 0:::INT,
             |     deleted 4 NOT NULL DEFAULT 0:::INT,
             |     answer_mask INT NOT NULL DEFAULT 0:::INT,
             |     CONSTRAINT "primary" PRIMARY KEY (id ASC),
             |     INDEX idx_answer_question (question_id ASC),
             |     FAMILY "primary" (id, question_id, attributes, display_order, next_flow_id, isle_id, deleted, answer_mask)
             | )


so, there has been some history on the answers table.  Based on our database updates here's what i believe the history is.

-- initial create, i believe this table was created on cockroach 1.0.2
-- i've been a fan for a while now

CREATE TABLE IF NOT EXISTS answers (
id              SERIAL PRIMARY KEY,
question_id     INT NOT NULL,
attributes      STRING NOT NULL DEFAULT '',
display_order   INT NOT NULL DEFAULT 0,
include_cohorts STRING NOT NULL DEFAULT '',
next_flow_id    INT NOT NULL DEFAULT 0,
isle_id         INT NOT NULL DEFAULT 0,
deleted         BIT(1) NOT NULL DEFAULT 0);

-- not sure what version of the database was running when these alters were done
ALTER TABLE answers ADD answer_mask INT NOT NULL DEFAULT 0;
ALTER TABLE answers ADD quiz_points INT NOT NULL DEFAULT 0;

-- later point in time this was done
ALTER TABLE answers DROP quiz_points;
ALTER TABLE answers DROP include_cohorts;

Not sure if any of that helps...

**Comment by knz** [comment]
Yes it did! Thank you.
We'll fix this in a next 2.1 release.

**Comment by knz** [comment]
@NathanRThomas until the next release where the bug is fixed, here is a workaround:

For all the columns in the `public.sql` file that you have generated, if the value in the far left is a number (like "4" for `answers.deleted`), use the following statement:

```
ALTER TABLE <tablename> ALTER COLUMN <columname> SET DATA TYPE INT8;
```

it should complete pretty fast regardless of table size, and will subsequently fix your dumps.

(Technically any INT size larger than the bit size you originally used should work, eg you can upgrade the bit(1) to int2, however I have only tested the workaround for int8 which should "fit" everything.)

(Also in the future you should probably use BOOL instead of bit(1) as it has much better optimizer support.)

**Comment by NathanRThomas** [comment]
OH, the BIT(1)
ya, that caused an issue in another upgrade in the past as well.
Great, thanks, that fixed the backups.

Ya, i should use a bool type, my background with mysql made me wary of that data type.

Thanks again!
