### ISSUE TITLE
new github issue 34161

### ISSUE THREAD

**Issue by tim-o** [cockroachdb/cockroach#34166]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#3044](https://cockroachdb.zendesk.com/agent/tickets/3044)
**Group:** Support
**Requester:** nathan@headlinerlabs.com
**Organization:** Headliner Labs
**Assignee:** Ron Arevalo
**Issue escalated by:** Ron Arevalo

**Original ticket description:**

<blockquote><div class="zd-comment zd-comment-pre-styled"><div dir="ltr"><div dir="ltr"><div dir="ltr">
<div style=" font-size: small">I created a new github issue and didn't really want all this public, so sending it here.  Hope it helps.</div>
<div style=" font-size: small"><br></div>
<div>
<font><a href="https://forum.cockroachlabs.com/t/failed-running-dump/2344/2" rel="noreferrer">https://forum.cockroachlabs.com/t/failed-running-dump/2344/2</a></font><br>
</div>
<div><font><a href="https://github.com/cockroachdb/cockroach/issues/34161" rel="noreferrer">https://github.com/cockroachdb/cockroach/issues/34161</a><br></font></div>
<div><font><br></font></div>
<div><font><br></font></div>
<div><font>Thanks,</font></div>
<div><font>-Nathan</font></div>
<div dir="ltr"><div dir="ltr"><div><div dir="ltr"></div></div></div></div>
</div></div></div></div></blockquote>

**Comment by knz** [comment]
Dup #34161
