### ISSUE TITLE
CONFIGURE ZONE USING constraints not working as expected

### ISSUE THREAD

**Issue by timveil** [cockroachdb/cockroach#34172]
**Describe the problem**

executing the following command does not seem to work as expected however a similar command does work as expected..

does not work:
`ALTER TABLE example6.central_west CONFIGURE ZONE USING constraints='[+datacenter=central, +datacenter=west]';`

does work:
`ALTER TABLE example6.central_west_json CONFIGURE ZONE USING constraints='{+datacenter=central: 2, +datacenter=west: 1}';`

**To Reproduce**
https://github.com/timveil-cockroach/docker-examples/tree/master/example-6

See this repo and run `run.sh`.  This spins up a 9 node cluster across 3 regions, creates tables and then applies constraints.  The table `central_west` should be constrained to the `central` and `west` localities. however the above command does not work.  `central_west_json` executes the alternative command and table is properly constrained

**Expected behavior**
`central_west` should be distributed just like `central_west_json` based on my understanding of current docs

**Additional data / screenshots**
![image](https://user-images.githubusercontent.com/3260845/51568933-f22d5500-1e68-11e9-8e84-9ef681f75aea.png)

**Environment:**
 - CockroachDB version: 2.1.3
 - Docker

**Comment by knz** [comment]
@tbg @petermattis who should this issue be routed to these days?

**Comment by timveil** [comment]
tested with v2.1.3 and v2.1.4 docker tags

**Comment by tbg** [comment]
@timveil thanks for the repro.

Right off the bat I have one question: are you sure the first thing is doing what you think? I think you want this to mean "all replicas are either in central or west", but I think it may mean "all replicas are both in central and west at the same time". I can see slight evidence of this in the docs:

https://www.cockroachlabs.com/docs/v2.1/configure-replication-zones.html#types-of-constraints

![image](https://user-images.githubusercontent.com/5076964/51607496-17779d00-1f15-11e9-828c-3daafdb6a8f8.png)

This constraints wants to have all replicas away from west and they must be on SSD. It wouldn't make sense to ask for the disjunction of the two (replicas that are either SSD or not in west -- seems random).

I agree that the docs don't make this very clear (cc @jseldess), and in fact I'm not 100% sure that what I'm saying is correct (but 90%).

Assuming I'm right, for your example, this suggests that you would use `[-datacenter=east]` instead. It's a bit unfortunate that it's not possible to specify it the other way around. Adding a new locality to the cluster later, we wouldn't necessarily want replicas to spread there automatically, but now that's what would happen.

**Comment by timveil** [comment]
just to clarify, i tried to simplify this down from a slightly more complicated scenario where there were data centers in US, Canada, Europe and South America.  I wanted to constrain ranges to US only specifying a list of three US data centers.  In that scenario, the "negative" would not accomplish the desired outcome even though it certainly would in example provided with the repo.  Thoughts?

**Comment by tbg** [comment]
My understanding is that the `[...]` syntax requires all of the constraints to be fulfilled at the same time, so you can't express what you want referring only to the US datacenters. This is unfortunate (and you should raise the issue with the PMs; I'd be surprised if you're the first requesting it), but to the best of my knowledge (which I just obtained from the docs) I don't think we support that.

So you're either going to end up with

`[-region=us-west, -region=latam-south, -region=latam-north, -region=ca-east, ...]` which is clunky or, alternatively, you could give all US nodes an additional tag `us` (on top of their locality) so you can specify `[+us]`.

Does that answer your question or am I misunderstanding the problem?

**Comment by timveil** [comment]
it does!  many thanks.  i'll follow up with PM and @jseldess
