### ISSUE TITLE
remove `cockroach-prod` dependency

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#3418]
I think I want to move the acceptance out of the main repository or,
alternatively, strip out the remote functionality (once the Chaos test
has migrated there in some form). Since the gossip peering tests
have been useful against real clusters as well, moving sounds like
the more appealing option.
There is no significant connection between the `acceptance` package
and any other part of the code, so hopefully this should be a relatively
straightforward task.

I do not want to move `acceptance` into` cockroach-prod` since `acceptance`
carries in it dependencies on `c-lz4` and `c-snappy`, which require a full
build toolchain and require a complete restructuring of how `cockroach-prod`
is tested.

**Comment by petermattis** [comment]
What is the motivation for wanting to move `acceptance` to its own repo? Doing so complicates running the acceptance tests on CircleCI and building the acceptance tests nightly.

Not sure what you mean by there being no significant connection between `acceptance` and any other part of the code. The `acceptance` tests utilize the `{base,client,gossip,keys,roachpb,security,testutils,util}` packages.

**Comment by tschottdorf** [comment]
`acceptance` can run against a remote cluster, so it reaches out to `cockroach-prod`. That's fairly awkward (though it'll work for the time being) since the dependency should go the other way. It also tests the `cockroachdb/cockroach` image, so unless you build that from the current codebase, you're mostly not actually testing the code in the repo.

By "no significant connection" I mean that when we move `acceptance` out of the main repo, nothing in the main repo will miss it (except for the test, but that can just take it from its new location).

This isn't a necessary move, though I'm fairly certain the alternative will be never exercising the acceptance tests against a real cluster in practice and quickly having it rot. The real-cluster testing that is about to happen will be in `cockroach-prod`; the acceptance setup is a bit too "toy" for what I'm trying to do there.

**Comment by bdarnell** [comment]
I agree with Peter that the bulk of the acceptance test code should live in the main repo so we can run tests on docker from a single repo. Maybe we could make a Cluster interface that can be implemented in cockroach-prod, and import the acceptance tests from that package when we want to run them against a real cluster. Or, as long as the stuff we need from the prod repo is just a bunch of terraform config files, why not just move them to the main repo?

**Comment by petermattis** [comment]
Re-titled this issue. Perhaps the dependency on `cockroach-prod` can be removed without moving the `acceptance` repo such as via Ben's suggestion.

**Comment by tschottdorf** [comment]
I like the idea of moving the terraform setup into the main repo (`./acceptance/terraform` is probably a good place). @mberhault?

**Comment by mberhault** [comment]
that might be ok since we only have configs and scripts (not counting the tiny supervisor watcher, but we can probably do without it), but definitely not under `acceptance`. more like `production`

**Comment by tschottdorf** [comment]
I'd avoid the word `production` as long as our terraform stuff is really setting up test clusters. For now, we're using it for cluster testing, so why not name it accordingly and shell it out later.

**Comment by mberhault** [comment]
fair enough. something like `cloud` then. it can contain both testing and real production stuff later.

**Comment by tschottdorf** [comment]
sounds good, I'll get to it.
