### ISSUE TITLE
storage: unable to down-replicate from stores not present in StorePool

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#34187]
`Allocator.RemoveTarget` won't remove a node for which we don't have a descriptor in the store pool. This can occur when a cluster is restarted, but one or more of the nodes fails to start. This is primarily an issue with larger replication factors when the replication factor is changed. Consider a 9-node cluster where the cluster is restarted, but only 6-nodes come back up. If a range with `num-replicas=9` is changed to have `num-replicas=5`, the allocator is unable to remove replicas from the 3 down nodes because they do not have `StoreDescriptors` in the `StorePool`. The allocator won't remove replicas that will drop the range below quorum, so there isn't an urgent danger here, but this behavior is unexpected.

After the time-until-store-dead threshold passes (5m), the replicas on the down nodes will be marked as dead which triggers a different code path that allows for their removal.

How to fix this is non obvious as `Allocator.RemoveTarget` utilizes store metrics to make its decision. If we don't have metrics for the store, should we try to synthesize them in some way? Perhaps this isn't an issue worth fixing anyways, as the 5m time window isn't long and it is possible the down nodes are just taking a bit longer to start.

If we decide to do nothing here, we should at least include additional commentary in the code that this behavior exists.

Jira issue: CRDB-4663

**Comment by tbg** [comment]
We saw this make problems worse over in https://github.com/cockroachdb/cockroach/issues/52528#issuecomment-698262347. Under certain conditions (allocator not having a good view of cluster liveness), the replicate queue may be prone to remove replicas that would lead to loss of quorum. This issue makes this more likely as down-not-dead nodes enjoy accidental protection from removal, meaning the allocator will end up removing live replicas.
