### ISSUE TITLE
ui: jobs listed as successful with duration 0, even though schema change failed

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#34208]
In #34082 we see an example of a Jobs page in the UI showing a bunch of successful jobs with duration 0, and it's very questionable what was successful about them. In particular, the dropping of index `guest_order_updated_date_idx` has not happened. The index is referenced by a mutation in the table descriptor, and the index's data has not been deleted (in particular, as of this writing, it has a bunch of intents).
I suspect what the UI shows as successful is bogus.

Jobs output: https://drive.google.com/open?id=1gAh5JRI3pCy5ejDorZa3Vdhz5rc6pElj
This is a dump of the table descriptor with that index, taken after the the Jobs screenshot.
https://gist.github.com/andreimatei/11566c4ed239dd6ce01cae8e550ddf12

@vivekmenezes would you pls triage

**Comment by lucy-zhang** [comment]
This is likely fixed/no longer applicable with the new schema change jobs.
