### ISSUE TITLE
sql: setting names with sub-identifiers start with digits must be quoted for use

### ISSUE THREAD

**Issue by unixunion** [cockroachdb/cockroach#34222]
**Describe the problem**

Cluster settings not settable as per [documentation](https://www.cockroachlabs.com/docs/stable/cluster-settings.html) for keys:

`timeseries.storage.10s_resolution_ttl 
timeseries.storage.30m_resolution_ttl`

**To Reproduce**

Try set/read the cluster settings in `cockroach sql`

`
SHOW CLUSTER SETTING timeseries.storage.10s_resolution_ttl;  
invalid syntax: statement ignored: syntax error at or near ".10"
DETAIL: source SQL:
SHOW CLUSTER SETTING timeseries.storage.10s_resolution_ttl;
`

**Expected behavior**
Set the setting without error.

**Additional data / screenshots**
As a workaround I have inserted the keys and values directly into system.settings.

**Environment:**
 - CockroachDB version: 2.1.3
 - Server OS: Gentoo
 - Client app: cockroach sql

**Comment by tbg** [comment]
@unixunion this should work:

```
SHOW CLUSTER SETTING "timeseries.storage.10s_resolution_ttl"
```

@knz is this something we can fix in the parser? It trips over the `.10`.

**Comment by bdarnell** [comment]
Yeah, it seems like a good idea for us to avoid setting names that can't be used without quotes (in retrospect, maybe we should have made the quotes mandatory for all settings).

**Comment by knz** [comment]
I'm renaming these two settings (and adding a linter) in #34248. The settings are renamed in a value-preserving manner.
