### ISSUE TITLE
opt: push down FILTER expressions when applicable

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#34236]
Aggregate `FILTER` expressions allow an aggregate to only process some of the inputs it receives, for example:

```
SELECT average(x), sum(x) FILTER (WHERE y >= 0) FROM t
```

Will only get the average of all `x` values, along with the sum of `x` values for which `y` is nonnegative.

In the specific case where every aggregate has a common `FILTER`, we can push the filter down and possibly get a more efficient plan:

```
SELECT sum(x) FILTER (WHERE y >= 0) FROM t
=>
SELECT sum(x) FROM (SELECT x FROM t WHERE y >= 0)
```

**Comment by RaduBerinde** [comment]
Dup of #46903.
