### ISSUE TITLE
TPC-C performance regression on 3 node and 6 node

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#34234]
**Describe the problem**

There seems to be a minor regression on three node tpc-c and a major regression on six node tpc-c. 

Three node tpmC in December:
Run 1: 27,112.7 tpmC 91.67% efficiency on 2300 warehouses

Three node tpmC on bleeding edge  1/24:
Run 1: 25,391.4 86% efficiency on 2300 warehouses 
Run 2: 26,113.1 88% efficiency on 2300 warehouses

Six node tpmC on bleeding edge 1/24:
Run 1: 32,655.2  tpmC 63.5% eff on 4000 warehouses 
Run 2: 35,141.5 tpmC  78.1%  eff  on 3500 warehouses

Linear scalability suggests we should have hit ~4600 warehouses or close to it. We know we had somewhat linear scalability based on hitting 10,000 warehouses with 15-18 nodes in December.

**Comment by awoods187** [comment]
I ran three node tpmC on the 1/14 alpha:
Run 1: 26,609.2  90% efficiency on 2300 warehouses 

A little light on the data but seems to suggest some regression before and after the 1/14

**Comment by jordanlewis** [comment]
#34025 seems to also have been introduced nearby 1/14. Perhaps they could be related. cc @nvanbenschoten

**Comment by awoods187** [comment]
So I realized a couple of things on my six node tests above--they weren't using partitioning and I mistakenly point the load only at three of the six nodes. 

Here is a comparison of the different alphas and master without using partitioning:
Release | Warehouse | tpmC | Efficiency 
-- |-- | -- | --
November | 3750 | 44,863.7 | 93%
December | 4000 | 47,950.8 | 93%
January | 3650 | 43,522.8 | 93%
1/28 Master | 4100 | 47,317.8 | 90%

We see a dip down in January's alpha but an increase back up in 1/28 master (although still a bit below December's tpmC).

**Comment by ajwerner** [comment]
I tried running tpccbench on a couple of times each before and after the lazy transaction record commit and it was very close. tpccbench is probably too noisy

**Comment by awoods187** [comment]
So I finally set partitioning up correctly and I see basically no difference in 6 node tpc-c

-- | -- | -- | --
No partitioning | 4100 | 47,317.8 | 90%
Partitioning | 4100 | 46,655.7 | 89%

**Comment by nvanbenschoten** [comment]
> Three node tpmC in December:
> Run 1: 27,112.7 tpmC 91.67% efficiency on 2300 warehouses
>
> Three node tpmC on bleeding edge 1/24:
> Run 1: 25,391.4 86% efficiency on 2300 warehouses
> Run 2: 26,113.1 88% efficiency on 2300 warehouses

Is the most concerning thing here. I suspect that we're seeing exactly what we saw in https://github.com/cockroachdb/cockroach/issues/34426. I'm in the middle of bisecting this issue.

**Comment by nvanbenschoten** [comment]
Closing this as it's very likely the same issue we saw in #34426. 1/24 is before the fix was [merged](https://github.com/cockroachdb/cockroach/pull/34231#issuecomment-458600364).
