### ISSUE TITLE
opt: add support for window functions

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#34251]
This issue tracks the implementation of window functions in the optimizer, and outlines the work to be done.  All in all I estimate between one and two milestones of work for this feature. I think it would also make a good medium-large intern project.  There's a lot here, but it has the benefit of being largely self-contained and not requiring the modification of too much around existing features.

Here is an incomplete sketch of what the definition of a `Window` operator might look like:
```
# Window is a relational window function operator. A window operator passes its
# input through while appending a single additional column to every row.
[Relational]
def Window {
  Input Expr

  # Render is the expression used to compute the column this Window expression
  # tacks on. Can be a window function or an aggregate, and may include a
  # DISTINCT.  If Render is an aggregate, it can also include a FILTER
  # expression.
  Render ScalarExpr

  _ WindowPrivate
}

[Private]
define WindowPrivate {
  # InputOrdering is the ordering which the window function's computation is
  # relative to (for example, `row_number` computes the ordinality of each
  # row when they are ordered according to this ordering).
  InputOrdering Ordering

  # Partition specifies that the window function should be computed
  # independently for each set of rows which agree on a particular set of
  # columns.
  Partition ColSet

  # FrameDef specifies how the computation of the window frame should be performed.
  # There are several different modes, including RANGE, ROWS BETWEEN, and more.
  # It's not clear to me how much special treatment will be needed for the
  # various modes here, but I think not too much.
  FrameDef FrameDef

  # OutputID is the id of the column this window expression tacks on to its input.
  OutputID ColID
}
```

The heuristic planner has a single parent `windowNode` which contains an array of `windowFuncHolder`s which are the various specific window functions being computed, but I think in the optimizer's paradigm composing discrete operators makes more sense (though we'll probably have to collapse them at execbuild time).

A good primer on window functions (especially as they relate to optimizers) is [Optimization of Analytic Window Functions](http://vldb.org/pvldb/vol5/p1244_yucao_vldb2012.pdf).

**Comment by yuzefovich** [comment]
One thing to keep in mind is that it would be great to be able to recognize that the same window function is used in multiple places in the same query. For example, currently the query like
```
SELECT
    rank() OVER (ORDER BY a), rank() OVER (ORDER BY a)
FROM
    t;
```
requires actually computing the same `rank` function twice. We should be able to reuse the computation when possible.
