### ISSUE TITLE
Docker hub images broken from alpha-6336-g3bb7a52 tag onwards

### ISSUE THREAD

**Issue by roosmaa** [cockroachdb/cockroach#3426]
Looks like something has gone wrong with Docker image building from alpha-6336-g3bb7a52 tag onwards. (Nobody is actually using CockroachDB from Docker?) Even though the binary is there, it's probably corrupted or wrong architecture.

```
$ docker run -it --rm cockroachdb/cockroach:alpha-6336-g3bb7a52 shell
/cockroach # ls
cockroach     cockroach.sh
/cockroach # ./cockroach --help
/bin/sh: ./cockroach: not found
```

Older versions work fine:

```
$ docker run -it --rm cockroachdb/cockroach:alpha-6334-g62054a0 --help
Usage:
  cockroach [command]

<snip>
```

**Comment by tschottdorf** [comment]
You're right, this is pretty broken. We recently switched away from "completely" static builds, but the `cockroachdb/cockroach` container is actually `busybox` (so it doesn't have `glibc`).
Additionally, parts of our CI suite which originally ran the acceptance tests using that docker image on the `master` branch seem to have been removed in some sort of restructuring.
We'll have a fix out soon. Thanks for reporting!

> Nobody is actually using CockroachDB from Docker

Not really. In development and CI, we mostly use the `cockroachdb/builder` image (performance considerations). The (now apparently absent) test for the deploy image and the README are the only users of the other one, as far as I can tell. And while we're probably going to keep having a "production" docker image, we usually just deploy a binary directly in our tests. It's just so much faster on the cloud infrastructure providers that we're using.

**Comment by roosmaa** [comment]
Shouldn't have the size of the docker image have dropped slightly when static linking of libc was removed?

Working image binary:
```
$ docker run -P -it --rm cockroachdb/cockroach:alpha-6334-g62054a0 shell
/cockroach # ls -lh
total 106460
-rwxr-xr-x    1 root     root      104.0M Dec 11 21:21 cockroach
-rwxrwxr-x    1 root     root         110 Dec 11 20:54 cockroach.sh
```

Broken binary size:
```
$ docker run -P -it --rm cockroachdb/cockroach:latest shell
/cockroach # ls -lh
total 106192
-rwxr-xr-x    1 root     root      103.7M Dec 13 02:48 cockroach
-rwxrwxr-x    1 root     root         110 Dec 13 02:24 cockroach.sh
```

Could it be that it's still getting bundled, just not used?

**Comment by tschottdorf** [comment]
I don't think so (skimmed through `nm` just to make sure). We don't link with `-static` (only `-static-libgcc -static-libstdc++`) and the size of the binary drops to ~25% of its size when it's stripped (which we don't do with this binary, though we probably should). Weird that it would only drop by 1mb though (though linking glibc statically will still call out dynamically at runtime, maybe there just wasn't ever any bulk of its code in our binary). @petermattis?

**Comment by petermattis** [comment]
I imagine this was the linker doing its job: stripping out unreachable code. There is very little from glibc that is used by the go runtime.
