### ISSUE TITLE
storage: "aborting snapshot because raft log is too large" causes tight retries

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#34268]
When attempting to send a preemptive snapshot, we error out if the Raft log is too large. When that happens, the `replicateQueue` will retry it 5 times.

Retry loop:
https://github.com/cockroachdb/cockroach/blob/dc2fbcdc0dccb8cc676fc67370375bab36b3cff0/pkg/storage/replicate_queue.go#L255
Error generation:
https://github.com/cockroachdb/cockroach/blob/746abdac46c25eb84d18fa15c33579b16dbc71e5/pkg/storage/store_snapshot.go#L254

A trace of the retries can be seen in the following output from manually enqueuing a range for replication. There's other stuff going wrong in there about some stores being throttled - ignore that.
https://gist.github.com/andreimatei/eeacd0a79eec809e2494961fb9f19be3

cc @petermattis

**Comment by andreimatei** [comment]
I should have spelled out that the retries seem hopeless since the log truncation is not synchronous (at least I don't think).

**Comment by andreimatei** [comment]
Part of the #34269 investigation.

**Comment by petermattis** [comment]
This is happening on v2.1.3. I thought we fixed something in this area recently. Perhaps it wasn't backported.

**Comment by tbg** [comment]
This problem has gone away (in 19.1) because we're not sending any log entries in snapshots any more.
