### ISSUE TITLE
Seeing random Latency Spikes

### ISSUE THREAD

**Issue by 2fours** [cockroachdb/cockroach#34306]
I'm seeing random latency spikes up into the seconds. It's a 3 node cluster, load is pretty low < 100 queries per second. Most of the read/writes/deletes are on one table. Any idea what can cause this?

**Comment by 2fours** [comment]
Are these sort of 99th percentile spikes with 10 second ish latency normal? I'm new to the cockroach world. 

<img width="1357" alt="screen shot 2019-01-30 at 5 01 48 pm" src="https://user-images.githubusercontent.com/3253424/52021113-04cf0c00-24b1-11e9-9f69-f24c3cd29466.png">
](url)

**Comment by jordanlewis** [comment]
Can you give more details - what's your workload? What kind of queries are encountering the high latency? The more detail the more likely it is that we can help. Do you see any correlated slowness in other time series graphs? Check out the storage metrics - anything suspicious there?

**Comment by 2fours** [comment]
It's not that high, < 100 queries/second on average. The infrastructure is the back end for an end to end encrypted messaging app where people can delete their messages, and messages automatically expire after 1000 have been reached - which results in a delete in the chatmessages table. So there's a lot of inserts and deletes on the chatmessages table. It's not a very complicated use case. I don't really see any correlations in other graphs, or anything abnormal anywhere apart from this. I really like what you guys are doing and am willing to do anything I can to help you make your product better so let me know how I can help. Cheers.

**Comment by nvanbenschoten** [comment]
Hi @2fours, has anything changed since this issue was filed?

**Comment by 2fours** [comment]
@nvanbenschoten nothing has changed.
