### ISSUE TITLE
sql: allow the InternalExecutor to work with a modified schema

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#34304]
There are at least 3 applications for schema change validation that require the validation to be done before the schema change goes public, but the validation is done using SQL that can only function on the public schema. What makes sense is to hand a schema from the future to the internal executor so that it can do the right thing.

Jira issue: CRDB-4655

**Comment by vivekmenezes** [comment]
A conversation with @jordanlewis reminded me that if a transaction has a schema change, and a subsequent statement invokes an InternalExecutor, the InternalExecutor doesn't share the TableCollection state of the parent transaction, thus the InternalExecutor can deadlock with the parent transaction over a read to the table descriptor.

**Comment by vivekmenezes** [comment]
@lucy-zhang FYI

**Comment by vivekmenezes** [comment]
I've been able to make some progress on this. I was concerned that we might not be able to fix it, but the problem does look tractable on one of my branches.

**Comment by lucy-zhang** [comment]
#58906 improves the interface slightly. An even better step would be to have the synthetic descriptors be scoped at a per-query/statement level (i.e., for each call to `execInternal`). We'd probably add functional options API to the internal executor (which currently takes just a `sessiondata.InternalExecutorOverride`) to do this. (I made an attempt in #45617, long ago, to put the synthetic descriptors in the `InternalExecutorOverride` struct, but having the descriptors configured separately will be much better.)

**Comment by postamar** [comment]
Synthetic descriptors do the job nicely. Closing.
