### ISSUE TITLE
sql: allow for reusing aggregate builtins

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#34316]
It would be nice if aggregate and window functions builtins could be reset and reused multiple times. Currently, when window functions are computed, a new instance of the builtin is created for every partition and for every window function, so we instantiate `numPartitions x numWindowFns` of them which becomes especially costly when partitions are small (i.e. we create `O(numRows x numWindowFns)` of builtins).

**Comment by knz** [comment]
please clarify what the word "builtin" means - it means something different to me I think

**Comment by yuzefovich** [comment]
@knz I'm uncertain about the right terminology here. Under "builtin" I mean an object that is created here: https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/distsqlrun/windower.go#L563, which is an instance of either an aggregate builtin or a window function builtin.
