### ISSUE TITLE
doc: rip out the "Client Architecture" section from README

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#3432]
https://github.com/cockroachdb/cockroach#client-architecture

it's dated and no more corresponds to the public interface we're planning to offer.

**Comment by petermattis** [comment]
Original issue title was to rip out the `Client Architecture` section. I think the entire README needs to be reworked.

**Comment by jseldess** [comment]
Responding a little late. I'll definitely rework the readme for beta. Want to cut down on redundancy with the docs.

**Comment by jseldess** [comment]
Update the readme and moved all but design overview out of the readme and into an appendix to the design document, so I think this is resolved. Though another task is to update/cleanup the design doc.
