### ISSUE TITLE
Improve partitioning interaction with the replica queue 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#34358]
**Describe the problem**

I set up a 6 node 5000 TPC-C cluster using partitioning. After waiting ~5 hours, the replication queue was still in a sawtooth pattern:

![image](https://user-images.githubusercontent.com/22278911/51911962-1e812e00-23a1-11e9-93ec-31406300e5f4.png)

I then followed these steps:

`SET CLUSTER SETTING kv.snapshot_rebalance.max_rate='64MiB'`
Wait for the replication queue to go to 0 (both pending and successful) then reset the rebalance wait.
`SET CLUSTER SETTING kv.snapshot_rebalance.max_rate='2MiB'`

Note, that the sawtooth almost immediately dropped to near zero (from 1000s). However, at this point, it took another ~2 hours to go from ~30 to 0. (Also we should work on this--presumably if it goes from 1000s to 40s in minutes it shouldnt be hours to go from 40s to 0).

CockroachDB should be smart enough to recognize that partitioning is happening and automatically adjust the snapshot rebalance rate up. Then, CockroachDB should be smart enough to realize that partitioning has finished (either via the jobs table or verifying the replication queue has gone to zero in both pending and successful via https://github.com/cockroachdb/cockroach/issues/31551) and reset the rebalance rate back to the default.

Without this feature, many users will miss the need to adjust the rebalance rate and wait 6x as long as they need to (if it ever finishes?).

**Comment by petermattis** [comment]
> CockroachDB should be smart enough to recognize that partitioning is happening and automatically adjust the snapshot rebalance rate up. Then, CockroachDB should be smart enough to realize that partitioning has finished (either via the jobs table or verifying the replication queue has gone to zero in both pending and successful via #31551) and reset the rebalance rate back to the default.

This is putting a bandaid on a bandaid. The fixed rebalance rate should really be replaced with an automatic mechanism to use the available bandwidth, but prioritize user/foreground traffic. See https://github.com/cockroachdb/cockroach/issues/14768.
