### ISSUE TITLE
jbd2/sda2-8 significant IO of a local cluster when no DB access

### ISSUE THREAD

**Issue by careylam** [cockroachdb/cockroach#34357]
**Describe the problem**
I am testing cockroach in Ubuntu V18.  "jdb2/sda2-8" consumes too much I/O when more than one cockroach instances are running. I run a local cluster for testing with 2 instances. Before any instances is running, jdb2/sda2-8 occupies about 0.3%. When the first one instance is running, it stays normal. Then start 2nd one, it ranges from 6% to 14%. When I close them them, eventually it goes down to the normal level.

The IO of cockroach stays 0.01% - 0.02% through out the test.

**To Reproduce**
1. To monitor the I/O, run # iotop -oPa -d 2
2. From another terminal, starts a cockroach instance. Observe the I/O of "jdb2/sda2-8"
3. Then start 2nd one, Observe the I/O of "jdb2/sda2-8". It starts to jump, ranging from 6% to 14%. 
4. Close them them, eventually it goes down to the normal level.

**Expected behavior**
Since there's no cockroach access, it should not trigger such a high I/O of "jdb2/sda2-8"

**Environment:**
 - CockroachDB version 2.1.3
 - Server OS:  Ubuntu V18.04 Server

**Additional context**
The high I/O is causing the server in-usable.

**Comment by knz** [comment]
Are you using multiple cockroachdb nodes on a single machine? This is not supported and prone to cause I/O errors like you observe.

Please explain what help you would like us to provide. What do you need to know? What would you like to happen?

**Comment by careylam** [comment]
Yes, I am running multiple nodes in a single machine. This is for development and testing only. Could you please explain why multiple nodes would cause this high I/O sumption of "jdb2/sda2-8" when there's no I/O on any of these nodes? I think something is fundamentally wrong.

**Comment by knz** [comment]
CockroachDB performs logging, measurements and background activity continuously. The RocksDB store uses an access pattern that can be heavy for any filesystem / disk combination.

When you start a new node, CockroachDb starts rebalancing ranges across the nodes. This causes reads on the existing nodes and writes on the new nodes. The combination is double the load for the disks and has very poor locality if the node runs on the same machine.

**Comment by careylam** [comment]
Okay, thank you.
