### ISSUE TITLE
sql: AS OF SYSTEM TIME '0,0' (and '0.000000000,0')

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#34371]
This came from a user who was trying to start a changefeed infinitely far in the past (via the cursor option, which uses the same codepath internally as AS OF SYSTEM TIME). Because we gc data, it should be an error to do a select or start a changefeed infinitely far in the past, but this somehow got interpreted this to mean "now", which is surprising.

```
> CREATE TABLE foo (a INT PRIMARY KEY);
> INSERT INTO foo VALUES (0);
INSERT 1
> SELECT * FROM foo AS OF SYSTEM TIME '0,0';
  a
+---+
  0
(1 row)
> SELECT * FROM foo AS OF SYSTEM TIME '0.000000000,0';
  a
+---+
  0
(1 row)
```

**Comment by ajwerner** [comment]
The way we currently enforce that you don't pick a value in the future is by grabbing a physical clock time as a "max" just before evaluating. Then if we parse the as of clause expression as an interval we add that to statement time. Then finally we check to see if it comes after "max". This results in the below loveliness:

```
root@localhost:26257/defaultdb> SELECT * FROM (SELECT now()) AS OF SYSTEM TIME '15000ns';
pq: AS OF SYSTEM TIME: cannot specify timestamp in the future
root@localhost:26257/defaultdb> SELECT * FROM (SELECT now()) AS OF SYSTEM TIME '15000ns';
                now
+----------------------------------+
  2019-01-29 19:28:53.176277+00:00
(1 row)

Time: 1.205445ms

root@localhost:26257/defaultdb> SELECT * FROM (SELECT now()) AS OF SYSTEM TIME '15000ns';
pq: AS OF SYSTEM TIME: cannot specify timestamp in the future
```

I don't see any reason why we don't enforce that the chosen timestamp must precede the statement timestamp.

**Comment by ajwerner** [comment]
There's a little bit on nuance here. Namely that the ParseDuration function rounds to the nearest microsecond. I am going to put up a PR that makes any value which rounds to a zero duration return an error but I can see that being a little bit controversial.

**Comment by tim-o** [comment]
Zendesk ticket #[3030](https://cockroachdb.zendesk.com/agent/tickets/3030) has been linked to this issue.
