### ISSUE TITLE
ui: rename Execution Latency graph

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#34374]
AFAICT the `Execution Latency` refers to latency of KV operations. The name is misleading, it should be `KV Execution Latency` or similar.

**Comment by piyush-singh** [comment]
Example of naming inconsistency @taroface @Annebirzin. Shall we create a tag for these issues? I can try to audit our backlog and see what else is out there.

**Comment by Annebirzin** [comment]
@piyush-singh yes I think it would be great to have a backlog of the known copy issues

**Comment by dhartunian** [comment]
@piyush-singh do we need to update tooltips here too?

```
    <LineGraph
      title="KV Execution Latency: 90th percentile"
      tooltip={
        `The 90th percentile of latency between query requests and responses over a
           1 minute period. Values are displayed individually for each node.`
      }
    >
```

and 

```
    <LineGraph
      title="KV Execution Latency: 99th percentile"
      tooltip={
        `The 99th percentile of latency between query requests and responses over a
          1 minute period. Values are displayed individually for each node.`
      }
    >
```

Also, I see "Execution Latency" referenced in the Statement Details page for individual SQL statements. Let me know if that's something that requires the same clarification as well.
