### ISSUE TITLE
sql: json timestamp stringify doesn't match postgres

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#34372]
cockroach
```
> select json_build_object('foo', now());
               json_build_object
+---------------------------------------------+
  {"foo": "2019-01-29 19:37:52.855198+00:00"}
```

postgres
```
# select json_build_object('foo', now());
              json_build_object
----------------------------------------------
 {"foo" : "2019-01-29T11:50:35.607352-08:00"}
```

Note the "T" between date and time. I think the postgres is something like rfc 3339, but I haven't looked for it in their docs.

Assigning to @justinj for triage

**Comment by justinj** [comment]
assigning @knz for frontend team triage

**Comment by theRealWardo** [comment]
just to add a bit of color here from my use case - we are trying to consume a changefeed and our default golang structs use `time.Time` but we cannot easily JSON unmarshal the time fields from the change field in their current format. I ended up having to write a wrapper doing a custom `time.Parse` for our time fields:
```
t, err := time.Parse("2006-01-02 15:04:05.999999999-07:00", vv)
```

**Comment by knz** [comment]
@mjibson @bobvawter I think that's up your alley and would be nice to work on together. Note that this is relatively important/impactful because our main users for CDC will need something.

**Comment by bobvawter** [comment]
I'll take a look at this today.

**Comment by bobvawter** [comment]
@danhhz Does this need to be backported to 2.1?

**Comment by danhhz** [comment]
Ideally, yes.

**Comment by nicolasparada** [comment]
This is closed but looks like the PR never got merged.
Here having to use `to_char()` to fix this:

```sql
select json_build_object('foo', to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'));
```
