### ISSUE TITLE
build: Unable to clone repo on Windows

### ISSUE THREAD

**Issue by mrtracy** [cockroachdb/cockroach#34380]
It is currently not possible to clone the git repo for Cockroach to a windows machine, due to a filename that contains several characters that are not valid in the windows filesystem:

`error: unable to create file pkg/cmd/prereqs/testdata/src/example.com/specialchars/a[]*?~ $%#.go: Invalid argument`

This precludes the ability to work with source code on a native Windows environment; builds are already not supported, but would be possible using the official Docker builder image or perhaps the Windows Subsystem for Linux.

**Comment by petermattis** [comment]
Hmm, that's an interesting way to prohibit a repo from being used on Windows. Is this issue for posterity, or something you'd like to see fixed soon? The Windows support is somewhat minimal at the moment. Providing binaries is all we've committed to.

**Comment by mrtracy** [comment]
Mostly for posterity, in case anyone else runs into this and wonders if it's their fault.  This has been broken for a long time, so clearly there is very little demand to develop on this platform. I just booted up a VM in hyper-V to get what I needed done; i'm not sure if I could have done something with cygwin.

**Comment by rolandcrosby** [comment]
Just hit this myself. There are ways around this -- you can clone the repo using a Windows Subsystem for Linux version of Git, for example -- but it's not optimal and feels unnecessarily hostile. I tried downloading a source archive from GitHub to see what would happen, and it looks like the "a[]*?~ $%#.go" is present in the archive, but silently doesn't get extracted if you use the built-in zip extraction utility on Windows.

#33709 appears related.
