### ISSUE TITLE
qa: add sql-20 graphs to perf dashboard

### ISSUE THREAD

**Issue by asubiotto** [cockroachdb/cockroach#34408]
We recently noticed a performance degradation on some sql-20 queries https://github.com/cockroachdb/cockroach/issues/34315. These queries and their performance are important to the SQL execution team as they have been picked to represent queries often run on CRDB and reflect the performance of the execution engine.

However, it is hard to notice regressions without spinning up a manual run of these queries, and once a regression is noticed, how to figure out *when* performance regressed without doing a manual bisect.

To address these problems, it would be helpful to add `sql-20` to the performance dashboard along other workloads that are already tracked.

**Comment by awoods187** [comment]
Love this idea!

**Comment by asubiotto** [comment]
Will also add TPCH queries while I'm at it

**Comment by asubiotto** [comment]
sql-20 graph was added. TPCH slipped but will add when I have time.
