### ISSUE TITLE
Bug in error message ("view") when dropping a table with a sequence

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#34415]
```
ALTER DATABASE "foo" RENAME TO bar;
pq: cannot rename database because view "foo" depends on table "foo_seq"
HINT: you can drop event_class_details instead.
```

This should not reference view as there is no view.

**Comment by jordanlewis** [comment]
There's not enough detail in this issue to reproduce. We would need the previously run schema definitions to understand what's going on, so I'm going to close this.
