### ISSUE TITLE
sql: databases with sequence that another table depends upon can't be renamed

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#34416]
Today CockroachDb's implementation of sequences is incomplete and does not allow renaming the database containing a sequence that's depended on by a table it's a limitation in the support of sequences.

**Work Around**
Unfortunately, I think you can't simply drop the DEFAULT expression on the `id` column to get rid of the table -> sequence dependency, because IIRC we don't properly update the dependency information when the DEFAULT expression is changed. (that's another limitation/bug)

maybe (I'm not sure) it's possible to 
1) create a new empty database with the new database name. 
2) rename the sequence to go to the new database. 
3) change the DEFAULT expression for that `id` column to use the new sequence name in the new database (make it use `nextval('newdb.public.seqname')` instead of just `public.seqname`). 
4) "move" the tables from old to new database name using `alter table rename`

**Comment by jordanlewis** [comment]
This seems to be invalid now.

```
root@127.0.0.1:61814/defaultdb> create sequence foo;
CREATE SEQUENCE

Time: 2.996ms

root@127.0.0.1:61814/defaultdb> create table a (a int primary key default nextval('foo'), b int);
CREATE TABLE

Time: 25.014ms

root@127.0.0.1:61814/defaultdb> insert into a (b) values(1);
INSERT 1

Time: 3.494ms

root@127.0.0.1:61814/defaultdb> set sql_safe_updates=false;
SET

Time: 212µs

root@127.0.0.1:61814/defaultdb> alter database defaultdb rename to derp;
RENAME DATABASE

Time: 2.042ms

warning: error retrieving the database name: pq: database "defaultdb" does not exist
root@127.0.0.1:61814/?> use derp;
SET

Time: 405µs

root@127.0.0.1:61814/derp> insert into a (b) values(2);
INSERT 1

Time: 953µs

root@127.0.0.1:61814/derp> select * from a;
  a | b
----+----
  1 | 1
  2 | 2
(2 rows)

Time: 465µs
```

**Comment by arulajmani** [comment]
Reopening this because renaming a database doesn't work if the sequence used is referenced by its FQN. Steps to repro:

```root@127.0.0.1:59882/defaultdb> CREATE SEQUENCE foo;
CREATE SEQUENCE

Time: 3.217ms

root@127.0.0.1:59882/defaultdb> CREATE TABLE t(a INT DEFAULT nextval('defaultdb.foo'));
CREATE TABLE

Time: 25.509ms

root@127.0.0.1:59882/defaultdb> ALTER DATABASE defaultdb RENAME TO default_db;
ERROR: cannot rename database because relation "defaultdb.public.t" depends on relation "defaultdb.public.foo"
SQLSTATE: 2BP01
HINT: you can drop the column default "a" of "defaultdb.public.foo" referencing "defaultdb.public.t" or modify the default to not reference the database name "defaultdb"
```

**Comment by ajwerner** [comment]
This is fixed for new sequences and new tables. There's still a migration to be done but it is tracked by https://github.com/cockroachdb/cockroach/issues/61017.
