### ISSUE TITLE
jobs: API cleanup

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#34418]
I have some questions and/or suggestions for cleanup of the jobs API.

 - The `Resumer` interface looks like the interface for a global/singleton object that works on any job, i.e. we pass the Job to all the methods. It's very confusing that a `Resumer` is actually associated with a single job.

 - If a `Resumer` is associated with a single job, why isn't the `Job` (and `phs`) passed to `ResumeHookFn` so we can associate the object with the job upfront, instead of passing the `Job` to every method?

 - It's strange that the resume hook takes a job type and the jobs code calls all hooks until it finds one. Why isn't the type passed to `AddResumeHook`? (the hooks could be stored in a type->ResumeHookFn map)

This is the first time I looked at these, so I might have misunderstood some things. If I didn't, I can work on cleaning up these issues.

CC @rytaft

**Comment by danhhz** [comment]
Sadly, a lot of our jobs knowledge left with nikhil, so some of this may have to be reconstructed from reading code. I think Resumer is per-type not per-job (like a factory, but it doesn't only create things), which perhaps means it's badly named. Agreed that the resume hooks should be in a map keyed by type. planHook is an even worse example of the same thing (more types and used more frequently).

**Comment by RaduBerinde** [comment]
Resumer is documented as being a "resumable job" (not a "resumable job manager" or whatever)..

If the Resumer is per-type, then the we should just set up a Resumer object and not a function that returns a Resumer.

The main reason I'm asking this is that in #34279, we are storing the planner from `OnResume` and using it in `OnSuccess`, which only works if it's per-job..

**Comment by danhhz** [comment]
Seems like the docs have rotted then. @mjibson do you have any of this still loaded up?

**Comment by mjibson** [comment]
There are no good answers to your question besides jobs is only used in a few places and worked will enough. And there is definitely some weird stuff going on with the Resume/OnSuccess/OnFail callbacks wrt the job object and what fields will have been already populated. I've forgotten all of those details, but I do remember thinking they were weird. I at least documented it *a bit* at https://github.com/cockroachdb/cockroach/blob/407932a95f3ad53d61481e5a7493fc4ed468faa9/pkg/jobs/registry.go#L429 but definitely not enough. I haven't touched job stuff in a while though. We have all improved it ourselves when it was deficient for whatever new thing was using jobs. That's probably my best advice at the moment.

**Comment by RaduBerinde** [comment]
Ok, sounds like cleaning it up a bit would be good, I'll look at that sometime soon and send out a PR.

**Comment by danhhz** [comment]
Yeah, I reread my earlier comments and realized I could be much more explicit. I definitely think there's some wonkiness here and I'd be quite glad for any thoughts and cleanups.

**Comment by vivekmenezes** [comment]
To make matters worse the Jobs are used by back/restore/import jobs correctly, but schema change jobs use the Jobs API only for presentation. The job itself is run by a schema changer that is a different concept. Any help in cleaning this up is much appreciated!

**Comment by RaduBerinde** [comment]
Also look at unifying all the variants `FractionProgressed`, `FractionDetailProgressed` etc. An idea is to have a single `Update` variant where the callback gets just a `*JobUpdater` on which you can call
`SetFractionProgressed()`, `ProgressDetailsUpdated()` etc. This object would store enough information about what we then need to update in the jobs table.

**Comment by RaduBerinde** [comment]
The second cleanup mentioned above was done in #36387.
