### ISSUE TITLE
opt: stats make TPCH Q3 SF1 slower

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#34410]
Running [TPCH Q3](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/opt/xform/testdata/external/tpch#L587-L609) SF1 on my laptop takes around 11s without statistics built, an about 16s with statistics built.

With stats:
* [EXPLAIN(OPT, VERBOSE)](https://gist.githubusercontent.com/justinj/7a5215686c09c7b2b529f290741ab81f/raw/329e4ed88b420df8cd2d6d6c52bab74f62780e2f/gistfile1.txt)
* [EXPLAIN ANALYZE](https://cockroachdb.github.io/distsqlplan/decode.html#eJyUlF9v2zYUxd_3KQi-JNlohX9ESyJQgAm6dt5cZ0ich2EzCs26c7laokFSWIoi332g7LWWanux38jLQ93z47n-jBtbwayswWP1O2Z4QfDG2SV4b13c2h6YVE9YUYJNs2lD3F4QvLQOsPqMgwlrwArPyz_XcA9lBe6aYoIrCKVZd9dunKlL90lbV4HzmOCHTdl4hUaY4DdmHcAppCX6o6VULNEFKwo5omLE5IVS6vXN_EdM8F0bFNKMaE60JDrHBDv7j0cOykohJmn8YYJ9KNdrFEwNCrEkZ4xzjxfPBNs2fG3eh3IFWLFn8nKDP1vT7Pyxw_7WpgEToMYET6392G7Q39Y0yDax8-hhhjTb-YQX-BREp51bRolmjGgm-7YzngkqB655kkqZ0jyCNk0FT2hPwQtGs4x-KfWFLJOU5cd58XN47QeCHwa2bH2wNbgjkcjQK3Rx-ziZvp7M3kZGD_P7yeztPqXsUA6GMchFUox5fdyXOOrrq5226eILVc_KIir_78gBOD-V_kMMFLhr0Wezhr_CpeZXr5xZfQiXml1hgu-hqTok4-8vWUKVUm-mdzfzfKSzK4K0IEinBOkYhahHPSRMCPZfoc8lyTPBeRGT0n1tXycoS_mXQi8nUiS5KGrfcbYOKuRNBQp1RzHBdfmEaqit-4RaD_GupEDvzO2uVBn_cVeg6Pboo6TnhO1mtXKwKoN112mfp47rm9lv72d38_ezx-n0UqcR6cPjux3cfpF_uyWu-ikTVLJiGLIi4TnNMuEPAWCJ7AAc8yrP8fpgXQB3LQc--Yho8UP87zG1CYjRwWiwMf9mMopEcCYLebhpin4599HG5xi5B7-xjYfhRB28mcYxgmoF27H0tnVL-NXZZfeZ7fKu03UbFfiwrbLtYtJsS7HBfTE7KRY9MRuK-RliPhSLk-L0dNvpSbE8LZYnxeOBePH83b8BAAD__4YPhdw=)

Without stats:
* [EXPLAIN(OPT, VERBOSE)](https://gist.githubusercontent.com/justinj/fc9f54d854f67dea478d0d233ccf62b7/raw/18d9ae54a9a3d3360b43297f44fb722d2610bf00/gistfile1.txt)
* [EXPLAIN ANALYZE](https://cockroachdb.github.io/distsqlplan/decode.html#eJy8lV9v2zYUxd_3KQi-NFlphZd_xJhAASbo2nlznCFxHobNKDTrzhVmSQZJYy2KfPdBUrbYiuzCfZifLF4ekefc37W_0KrOcZaVGKj9jQJdMLrx9RJDqH2z1G2Y5J-o5YwW1WYbm-UFo8vaI7VfaCziGqml8-yPNd5hlqO_4JTRHGNWrNvXbnxRZv6zq32OPlBG7zdZFSwZUUbfFeuI3hKnye9bzuWSvILxWI-4HIF-Za19ezX_gTJ6u42WOGBOMKeZu6SM-vrvQDxmuSWgefOhjIaYrdckFiVaAokBLRUEunhktN7G59uHmK2QWnhk3-YQhh2uiwqLiOUBjwCdSfyayZQ5wxzAvsuUcxCgey5NoozS_IhLcdDls7lt1XYH8z1ji0b5tS0DUd2gX-FPdVGhvxD7Ua3xz3jm4PX5G1-sPnZfe_2VzKm2y10MTa8bFdmJwggjuf63sBuHSKRJOYwbztoTdmVSKDAm_a-0RwtPuJDjNG2UZfaJlFjW_jPZBswtEZz8XFwfjFh-K0hyGKTlNsS6RH8AJEPekFfXD5Pp28nsfQPQ_fxuMnu_m6MZmpD-gFxCIpQsD6Oj_nd0fszCxydy1BA54hmchps7rPI2kvT7M0i4tfbd9PZqfjly5pwRJxlxihGnBxgCDVLCEEMgEyPEWOhhiDgoMYiQUOPEcFWGNufaY05CkaMl7dYhrGQyJjfF9VMpL8JfTwVODsOmT4HtarXyuMpi7S_0fp6uyfdq9uuH2e38w-xhOj1zqon0_uHmKdz9oni5JM_3KZNcw7gPmUpA8FSZwbmCRLcBHPKanuL1vvYR_UXa8ylGzMnXlNFpURaRAO-NBqTixWSoBLRKL-Xwpbsfg5OaZk4xcodhU1cB-xM1-GbejBHmK-zGMtRbv8RffL1sj-keb1tdu5BjiF1VdA-Tqi21_4W7YjhBLPpicVSsjp8sTxC_OFkdFes9Me-L9VFxelycHhWbnnjx-N0_AQAA__-J3PNV)

It seems that stats cause a lookup join to be planned, which is worse than the merge join.

**Comment by jordanlewis** [comment]
Q3 now uses a hash join, and we have testing on the plans for TPCH queries.
