### ISSUE TITLE
changefeedccl: support array columns in Avro

### ISSUE THREAD

**Issue by rolandcrosby** [cockroachdb/cockroach#34420]
CockroachDB array columns aren't currently supported in Avro changefeeds. Avro's native [array type](https://avro.apache.org/docs/1.8.1/spec.html#Arrays) seems like it should support everything that CockroachDB's array type does. (CockroachDB arrays are more limited than Postgres arrays - we don't support multidimensional arrays - so we just need to ensure that the CockroachDB array's item type can be represented as Avro.)

**Comment by danhhz** [comment]
@rolandcrosby Unless you object, I'd like to punt this one from the next release. I've done most of the rest of these in https://github.com/cockroachdb/cockroach/pull/34918. I expect that if we get demand for it, the work should be backportable.

**Comment by miretskiy** [comment]
I believe this is done, @HonoreDB ?

**Comment by HonoreDB** [comment]
Yup, done in https://github.com/cockroachdb/cockroach/pull/64251.
