### ISSUE TITLE
sql: support SET results_buffer_size

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#34423]
https://github.com/cockroachdb/cockroach/pull/34385 added support for specifying results_buffer_size as a connection parameter and exposing the current value with `SHOW`. Because of some plumbing issues (and lack of time to add sufficient testing), it was deemed at the time to be too risky to also add support for SET in the same PR, but this should be done at some point.

Jira issue: CRDB-4647

**Comment by rolandcrosby** [comment]
While testing core changefeeds with various clients, I discovered that our current implementation of `results_buffer_size` as a connection parameter doesn't appear to work with libpq-based drivers. When libpq parses a connection string or URL, it validates the passed parameters against a list of parameters that Postgres uses, and returns an error if you try to use a parameter it doesn't recognize. The upshot is that users of libpq-based drivers will not be able to properly set up their connections to consume CockroachDB core changefeeds.

Here's the current list of drivers we support, and what I saw for the ones I tested. I haven't tested all the languages yet but clearly it looks like we need to do something here if we want libpq-based clients to be able to use this feature:

Language | Driver | Uses libpq? | Behavior with `results_buffer_size` in query string
-|-|-|-
Go | pq | no | connection respects setting
Python | psycopg2 | yes | client error before connection
Ruby | pg | yes | client error before connection
Java | jdbc | no (but library is supplied by Postgres) | not tested
Node.js | pg | yes (but also provides pure JS implementation) | setting ignored in both implementations
C | libpq | yes | not tested
C++ | libpqxx | yes | not tested
C# | Npgsql | no | not tested
Clojure | java.jdbc | no (but library is supplied by Postgres) | not tested
PHP | php-pgsql | yes | not tested
Rust | postgres | no | not tested

**Comment by rolandcrosby** [comment]
I was just looking at Postgres docs, and I noticed that libpq actually does have [a supported parameter](https://github.com/cockroachdb/cockroach/issues/34423), as yet unused by CockroachDB, that we might be able to override to pass arbitrary settings to the server:

> `options`
> Specifies command-line options to send to the server at connection start. For example, setting this to `-c geqo=off` sets the session's value of the `geqo` parameter to off. Spaces within this string are considered to separate command-line arguments, unless escaped with a backslash (`\`); write `\\` to represent a literal backslash. For a detailed discussion of the available options, consult Chapter 19.

Ideally we would build the `SET` functionality requested in this issue, but if that's inordinately expensive or difficult, we could consider using this `options` session parameter for all CockroachDB-specific connection options. Since CockroachDB doesn't inherit Postgres's CLI arguments, I don't see any advantage to including the `-c` flags -- instead we could just use a space-separated list of `key=value` strings, so your URL-encoded connection string would look like: 

`postgresql://cockroach-node:26257/?options=results_buffer_size%3D16384%20some_other_option%3Dfalse`

I'm open to other suggestions here if this looks really ugly to you; mainly I just want to make sure that libpq-based clients can set the `results_buffer_size` parameter somehow, since core changefeeds are pretty much unusable without it.

Cc @knz @andreimatei -- any preferences from you about how we might implement this?

**Comment by andreimatei** [comment]
I begged for implementing `SET` at the time but I didn't impress anybody.

Separately, I maintain that controlling this buffer size is not what CDC should be doing. I think the SQL layer should get in the business of understanding when we're streaming "prospective" results to the client and explicitly flush after every result is produced.

**Comment by knz** [comment]
I like this `options` thing, but for an unrelated reason: we have several pg drivers that remove things from the conn URL that they don't understand, and that's really annoying. If they let `options` through, we could solve that entire class of problems this way.

Andrei, we didn't implement SET because we thought it was not the right move. You actually agree with this: you are advising to not make the thing configurable and instead do something else (which I incidentally wholeheartedly agree with). 

Let's do the right thing and stop thinking about SET for that parameter.

**Comment by danhhz** [comment]
> Separately, I maintain that controlling this buffer size is not what CDC should be doing. I think the SQL layer should get in the business of understanding when we're streaming "prospective" results to the client and explicitly flush after every result is produced.

I also think this is how it should work, but I absolutely don't have time to do it right now. Might be a great flex friday project for you, @andreimatei!

> Let's do the right thing and stop thinking about SET for that parameter.

@knz Can you elaborate on this? Making results_buffer_size also work with `SET` seems to me like a small, low-risk change that will open up the experimental core changefeeds to more users in 19.1. It's getting pretty late in the stability period to be introducing the `options` stuff and we certainly can't do the more fancy thing before 19.1 is cut, even if someone had the bandwidth.

**Comment by knz** [comment]
> Separately, I maintain that controlling this buffer size is not what CDC should be doing. I think the SQL layer should get in the business of understanding when we're streaming "prospective" results to the client and explicitly flush after every result is produced.

I think I actually know how to do this in a way that's even easier than implementing SET.

**Comment by danhhz** [comment]
Oooh, I'm listening

**Comment by knz** [comment]
Check out  the interface `tree.ObserverStatement`. See how it's used in `(ex *connExecutor) execStmt()`.

I'd say:

1. define a new interface like that
2. make it implemented by the changefeed stmt, 
3. add a new method to the `RestrictedCommandResult` interface to enable/disable buffering (and change the implementors accordingly)
4. add another conditional in  `(ex *connExecutor) execStmt()` and make it enable/disable buffering based on whether the stmt implements the interface

**Comment by andreimatei** [comment]
> You actually agree with this: you are advising to not make the thing configurable and instead do something else (which I incidentally wholeheartedly agree with).

Not true. I never spoke against making the buffer configurable; in fact I encouraged it. The more configurable it is, the better. I only said that CDC shouldn't use this feature.

>  Might be a great flex friday project for you, @andreimatei!

Thanks for the suggestion.

> add another conditional in (ex *connExecutor) execStmt() and make it enable/disable buffering based on whether the stmt implements the interface

Yeah, something like that, except I think the enabling and disabling of buffering should be more dynamic. You want buffering for the initial set of results, and you want to disable afterwards. And even then, you probably want to buffer chunks of results delivered at the same time, at least with the current poller implementation. So I don't think the `connExecutor` should decide the buffering/flushing; I think it should be closer to the components of the actual query. Like, a processor or planNode. And the keyword is not buffering; the keyword is flushing.

**Comment by danhhz** [comment]
So very early on, I tried something similar to that, but the part I get hung up on is making this do the right thing for something like `SELECT * FROM [EXPERIMENTAL CHANGEFEED FOR foo]`. It's not something we support now, but it is something that would be nice to support in the future and the statement sniffing approach seems brittle.

> Yeah, something like that, except I think the enabling and disabling of buffering should be more dynamic. You want buffering for the initial set of results, and you want to disable afterwards. And even then, you probably want to buffer chunks of results delivered at the same time, at least with the current poller implementation. So I don't think the connExecutor should decide the buffering/flushing; I think it should be closer to the components of the actual query. Like, a processor or planNode. And the keyword is not buffering; the keyword is flushing.

Exactly. This makes sense to me as a long term solution. I tried prototyping it, but I got hung up making it work with the plan hook stuff that changefeeds use. We'd definitely do this before we pull the experimental label off of core chagnefeeds, but I don't see how to make this change in a safe enough way that it's mergeable into 19.1

**Comment by knz** [comment]
oh I had misunderstood the requirement, sorry about that.

I still think it's doable, need to sleep over it once though.

**Comment by knz** [comment]
Side stepped through this: #35529

**Comment by miretskiy** [comment]
No idea how this wound up on CDC; but given that this issue is 4+ years old, closing it.
