### ISSUE TITLE
changefeedccl: tests using RangeFeed take too long

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#34455]
We currently set `kv.closed_timestamp.target_duration` to 1s in the rangefeed tests (since they check resolved timestamps which ultimately depend on closed timestamps) because they flake if it's set lower. But this leads to them taking a while, the package takes ~60s to run, which seems far longer than necessary.

IIRC, the flakes had something to do with schema changes not finishing because they had a txn that was continually pushed by the closed timestamps, but it's been a while.

**Comment by danhhz** [comment]
@tbg we talked about adding a mechanism that proactively tells closedts to try to close a certain timestamp. i suspect that would be a tremendous help here, do you think you could pick that off? (or at least design it?)

**Comment by tbg** [comment]
Yep

**Comment by miretskiy** [comment]
I don't think we'll be working on this directly, but there were many changes, including in test configuration, that made changefeed tests much faster.
