### ISSUE TITLE
distsqlrun: panic / crash on all 3 machines in cluster with 2.1.3

### ISSUE THREAD

**Issue by untoldone** [cockroachdb/cockroach#34468]
Panic on all three machines in a cluster of three in a row (probably a client retrying 3 times?)

I190126 01:07:02.570062 43079671 util/mon/bytes_usage.go:608  flow: bytes usage increases to 8.0 MiB (+10240)
I190126 01:07:11.811383 143 server/status/runtime.go:465  [n3] runtime stats: 1.7 GiB RSS, 161 goroutines, 244 MiB/213 MiB/535 MiB GO alloc/idle/total, 897 MiB/1.1 GiB CGO alloc/total, 5510.6 CGO/sec, 23.9/1.4 %(u/s)time, 0.0 %gc (2x), 1.3 MiB/2.6 MiB (r/w)net
panic: runtime error: index out of range

```
goroutine 43081229 [running]:
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcOutputHelper).ProcessRow(0xc425890c18, 0x3032640, 0xc429381240, 0x0, 0x0, 0x0, 0xb, 0xb, 0xc42bb59400, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:360 +0x6b0
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).ProcessRowHelper(0xc425890c00, 0x0, 0x0, 0x0, 0xc42bb59440, 0x4, 0x4)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:708 +0x78
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*interleavedReaderJoiner).nextRow(0xc425890c00, 0xc4224a8f50, 0xb, 0xb, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/interleaved_reader_joiner.go:239 +0x46c
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*interleavedReaderJoiner).Next(0xc425890c00, 0xc425890c48, 0xb, 0xb, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/interleaved_reader_joiner.go:109 +0x1e0
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.Run(0x3032640, 0xc429381240, 0x303c8c0, 0xc425890c00, 0x300f6c0, 0xc4267a2a80)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go:170 +0x35
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).Run(0xc425890c00, 0x3032640, 0xc429381240, 0xc43014dbc8)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:731 +0x98
created by github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).startInternal
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:558 +0x308
```

Please describe the issue you observed, and any steps we can take to reproduce it:

Unfortunately, I don't have a consistent reproduction, this happened once to our 3 machine cluster.

What did you do? Describe in your own words.

On another machine in the cluster, I had the output
```
E190126 01:08:38.465960 32958514 sql/conn_executor.go:636  [n1,client=130.211.2.145:54539,user=brent] a SQL panic has occurred while executing "SELECT b.b_key, b.wrapped_key, b.wrapped_type, b.avatar, b.name, b.description, b.updated_at, u.b_key AS u_b_key, u.user_key AS u_user_key, u.updated_at AS u_updated_at, u.removed AS u_removed, t.b_key AS t_b_key, t.team_key AS t_team_key, t.updated_at AS t_updated_at, t.removed AS t_removed, m.b_key AS m_b_key, m.user_key AS m_user_key, m.updated_at AS m_updated_at, m.seen_time AS m_seen_time, m.completed AS m_completed, m.override_inboxable_settings AS m_override_inboxable_settings, m.inboxabl [...]": runtime error: index out of range
```

Within a few seconds of the first panic on the other server... so I assume this is related.

**Expected behavior**
No Panic

**Environment:**
CockroachDB 2.1.3
Debian 9
go client

**Additional context**
Result was cluster/ application unavailability.

As a side note, we've hit a number of bugs in the last few days, in particular another panic
https://github.com/cockroachdb/cockroach/issues/34464 -- which also happen during a query that was very similar to this one. This might already be fixed / will upgrade to 2.1.4 soon regardless.

**Comment by jordanlewis** [comment]
Hey @untoldone, thanks for the report. It would be very helpful for us to see the full text of the query in the log message you pasted (it got truncated), as well as the schemas (output of `SHOW CREATE TABLE`) of all of the tables that the query touches. If your schema is sensitive, please feel free to email me at jordan@cockroachlabs.com, or feel free to anonymize the schema beforehand.

**Comment by untoldone** [comment]
I don't quite have enough context from the logs to know specifically which query caused this, but it was one of the following three queries:

```
SELECT
      b.b_key, b.wrapped_key, b.wrapped_type, b.avatar, b.name, b.description, b.updated_at,
      u.b_key as u_b_key, u.user_key as u_user_key, u.updated_at as u_updated_at, u.removed as u_removed,
      t.b_key as t_b_key, t.team_key as t_team_key, t.updated_at as t_updated_at, t.removed as t_removed,
      m.b_key as m_b_key, m.user_key as m_user_key, m.updated_at as m_updated_at, m.seen_time as m_seen_time, m.completed as m_completed,
      m.override_inboxable_settings as m_override_inboxable_settings, m.inboxable as m_inboxable,
      m.override_notification_settings as m_override_notification_settings, m.notification_sound as m_notification_sound,
      m.vip_notifications as m_vip_notifications, m.mute_forever as m_mute_forever, m.mute_until as m_mute_until
    FROM
      blobjects b
    LEFT JOIN
      blobject_user_subscribers u
    ON b.b_key=u.b_key
    LEFT JOIN
      blobject_team_subscribers t
    ON b.b_key=t.b_key
    LEFT JOIN
      blobject_user_metadata m
    ON b.b_key=m.b_key AND (u.user_key IS NULL OR u.user_key=m.user_key)
    WHERE b.b_key=ANY($1)
```

```
SELECT
      b.b_key, b.wrapped_key, b.wrapped_type, b.avatar, b.name, b.description, b.updated_at,
      u.b_key as u_b_key, u.user_key as u_user_key, u.updated_at as u_updated_at, u.removed as u_removed,
      t.b_key as t_b_key, t.team_key as t_team_key, t.updated_at as t_updated_at, t.removed as t_removed,
      m.b_key as m_b_key, m.user_key as m_user_key, m.updated_at as m_updated_at, m.seen_time as m_seen_time, m.completed as m_completed,
      m.override_inboxable_settings as m_override_inboxable_settings, m.inboxable as m_inboxable,
      m.override_notification_settings as m_override_notification_settings, m.notification_sound as m_notification_sound,
      m.vip_notifications as m_vip_notifications, m.mute_forever as m_mute_forever, m.mute_until as m_mute_until
    FROM
      blobjects b
    LEFT JOIN
      blobject_user_subscribers u
    ON b.b_key=u.b_key
    LEFT JOIN
      blobject_team_subscribers t
    ON b.b_key=t.b_key
    LEFT JOIN
      blobject_user_metadata m
    ON b.b_key=m.b_key AND (u.user_key IS NULL OR u.user_key=m.user_key)
    WHERE b.wrapped_key=$1 AND b.wrapped_type=$2
```

```
SELECT
      b.b_key, b.wrapped_key, b.wrapped_type, b.avatar, b.name, b.description, b.updated_at,
      u.b_key as u_b_key, u.user_key as u_user_key, u.updated_at as u_updated_at, u.removed as u_removed,
      t.b_key as t_b_key, t.team_key as t_team_key, t.updated_at as t_updated_at, t.removed as t_removed,
      m.b_key as m_b_key, m.user_key as m_user_key, m.updated_at as m_updated_at, m.seen_time as m_seen_time, m.completed as m_completed,
      m.override_inboxable_settings as m_override_inboxable_settings, m.inboxable as m_inboxable,
      m.override_notification_settings as m_override_notification_settings, m.notification_sound as m_notification_sound,
      m.vip_notifications as m_vip_notifications, m.mute_forever as m_mute_forever, m.mute_until as m_mute_until
    FROM
      blobjects b
    JOIN
      (
        SELECT b.b_key
        FROM blobjects b
          LEFT JOIN blobject_user_subscribers u ON u.b_key=b.b_key AND u.user_key=$1 AND u.removed=false
          LEFT JOIN blobject_user_metadata m ON m.b_key=b.b_key AND m.user_key=$1
          LEFT JOIN blobject_team_subscribers t ON t.b_key=b.b_key AND t.removed=false
          LEFT JOIN team_user_members tum ON tum.team_key=t.team_key AND tum.user_key=$1 AND tum.removed=false
          WHERE (u.user_key IS NOT NULL OR tum.user_key IS NOT NULL) AND ( /* This line ensures a line is either a user sub or a team sub or both */
            /* The Following Lines are all the conditions under which the object is inboxable */ 
            (u.user_key IS NOT NULL) OR /* User - All User subscriptions are inboxable*/
            (u.user_key IS NULL AND tum.user_key IS NOT NULL AND m.user_key IS NULL AND tum.inboxable=true) OR /* No User, Team, No metadata, TeamUser Is Inboxable*/
            (u.user_key IS NULL AND tum.user_key IS NOT NULL AND m.override_inboxable_settings=false AND tum.inboxable=true) OR /* No User, Team, Metadata, MetaOverrideInbox false, TeamUser Is Inboxable */
            (u.user_key IS NULL AND tum.user_key IS NOT NULL AND m.override_inboxable_settings=true AND m.inboxable=true) /* User, No Team, Metadata, MetaOverrideInbox true, MetaInboxable true */
          ) AND (b.updated_at > $3 AND b.updated_at < $4) /* Bound updated_at times */
          AND ( /* These are for the completed switching */
            (m.user_key IS NULL AND $5=false) OR /* No metadata and we're searching for uncompleted blobjects */
            (m.completed=false AND $5=false) OR /* Metadata, Completed is False, Searching for Uncompleted */
            (m.completed=true AND $5=true) /* Metadata, Completed is True, Searching for Completed */
          )
          ORDER BY b.updated_at DESC
          LIMIT $2
        ) as inbox_blob
    ON b.b_key=inbox_blob.b_key
    LEFT JOIN
      blobject_user_subscribers u
    ON b.b_key=u.b_key
    LEFT JOIN
      blobject_team_subscribers t
    ON b.b_key=t.b_key
    LEFT JOIN
      blobject_user_metadata m
    ON b.b_key=m.b_key AND u.user_key=m.user_key
```

I'll follow up with you via email on the schema

**Comment by jordanlewis** [comment]
Hey @untoldone, thanks for the information. Unfortunately, I'm having a hard time reproducing this issue as well.

Going to dump some debugging notes here for myself.

The bug seems to be that, in some cases, the rendered row returned by the interleaved join is the wrong width. The fact that this doesn't occur every time implies that there's nothing wrong with the emitted plan - the indexes and row slices that are required are likely correct. It looks to me like there's some data dependency that causes one of the input rows to the render to be the wrong length itself, which would produce an incorrect length after rendering, which doesn't seem to verify that its input rows are well-formed. Haven't quite gotten to the bottom of how it's happening yet.

My current hypothesis is that the state machine that keeps track of the join between the interleaved child is doing something slightly wrong. 

Here's the stanza that sets up what the right and left row will be:

https://github.com/cockroachdb/cockroach/blob/v2.1.3/pkg/sql/distsqlrun/interleaved_reader_joiner.go#L201-L204

Later on, we compare the rows to see if they're equal, returning 0 if so. If we get 0, then we try to do a render, which is where the potentially incorrect row would be emitted. I can only see that the row might be incorrect if either of the inputs to render are `nil`. But the comparison would only return 0 if the inputs were both nil, not if just one of them were, and we're guaranteed that both rows aren't nil because above we always leave the loop if we get a nil left row...

So, perhaps the problem is that one of the input rows has the wrong size. But that's hard to square as well, because both of the input rows are produced by the very same process - calling an intermediate row render on the same fetcher. If the intermediate render had renders or projections, then it would always produce a row of the same length. But! Just realizing now that if the intermediate render just had a filter or a no-op, it would pass the row through verbatim from the underlying row fetcher.

So is it possible that the underlying row fetcher could return rows of different lengths? This seems like the likeliest answer. I'm going to dig into that more in a bit, but have to leave off for now.

**Comment by untoldone** [comment]
While this may be totally irrelevant I thought I'd mention it in case it helps -- I remember someone else on my team mentioning they hit a bug on an earlier version of cockroach (maybe 2.1.0?) where an alter table had caused issues with our ability to run queries. He mentioned an investigation by someone on the cockroach team who said the issue had caused an incorrect table width. I believe we had dropped and recreated the table to fix it at the time. I don't know specifically which bug this was or the exact details, but its possible we had additional data that hadn't been dropped / recreated in prior versions of cockroach before upgrading to 2.1.3... that said, this issue only happened once (though it did happen on all three machines in the cluster) despite the query being run many times (though also not sure if it had the same parameters / data conditions ever again).

**Comment by knz** [comment]
> So is it possible that the underlying row fetcher could return rows of different lengths? This seems like the likeliest answer. I'm going to dig into that more in a bit, but have to leave off for now.

An incomplete column backfill; or a past encoding bug. We've had suspicions this may happen in the past. I could perhaps envision teaching the row reader to become more defensive about the data it finds.

**Comment by jordanlewis** [comment]
Outdated version.
