### ISSUE TITLE
log: VDepth doesn't work properly when inlined function call follows the call site

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#34461]
I have a function that looks like this:
```go
func (opc *optPlanningCtx) log(ctx context.Context, msg string) {
	if log.VDepth(1, 1) {
		log.InfofDepth(ctx, 1, "%s: %s", msg, opc.p.stmt)
	} else {
		log.Event(ctx, msg)
	}
}
```
and this piece of code:

```go
				if !isStale {
					opc.log(ctx, "YY query cache hit (prepare)")
					opc.log(ctx, "ZZ query cache hit (prepare)")
					opc.flags.Set(planFlagOptCacheHit)
					stmt.Prepared.Columns = pm.Columns
					stmt.Prepared.Types = pm.Types
					stmt.Prepared.Memo = cachedData.Memo
					return opc.flags, false, nil
				}
```

I run with vmodule set for the file and I see the YY messages, but never any ZZ messages. I added some debugging info to `loggingT.setV` and it resolves to a different file - the file that contains the (presumably inlined) implementation of `opc.flags.Set(planFlagOptCacheHit)`.

CC @tbg

**Comment by tbg** [comment]
I think clog.go needs to not call `runtime.Callers` but the alternative
that knows about inlining.

**Comment by nvanbenschoten** [comment]
Are the two calls to `opc.log` actually right next to each other and not in separate functions?

**Comment by RaduBerinde** [comment]
Yes, I believe it's because the PC is the return address, i.e. instruction after the call. And that instruction comes from the code for `flags.Set` (which is in another file).

**Comment by nvanbenschoten** [comment]
Interesting. Well I can't conclusively say whether #35199 will fix this or not. Want to try it out and see?

**Comment by RaduBerinde** [comment]
I tried it and it is fixed on `master`. I double-checked that I can reproduce against a commit without #35199.
