### ISSUE TITLE
ui: scrollbar in dashboard dropdown

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#34474]
The changefeeds dashboard added in #34427 seems to have caused us the dropdown to need a scrollbar, which it'd be nice to avoid.
<img width="182" alt="screen shot 2019-01-30 at 3 33 09 pm" src="https://user-images.githubusercontent.com/52528/52092161-8c795100-256b-11e9-9fc3-01712a0408ba.png">

I tried to look into how to enlarge the box, but didn't find anything obvious and I'm not super familiar with any of this stuff. It's also tricky to inspect that dropdown while it's expanded, since trying to use devtools causes it to close. @vilterp took a quick glance and didn't see anything either. @celiala, @vilterp said you'd have some bandwidth to look into this?

**Comment by vilterp** [comment]
My hope is that we can pass some prop to this third-party `Select` component that will make it resize itself to be big enough: https://github.com/cockroachdb/cockroach/blob/f320f08560a5832bb708df60c46b3be475b5eeb7/pkg/ui/src/views/shared/components/dropdown/index.tsx#L102-L110

Dan tried `autosize` but it didn't work.

**Comment by danhhz** [comment]
> Dan tried autosize but it didn't work.

Someone may want to double check that. It seemed pretty straightforward to try out, but who knows what I may have messed up.
