### ISSUE TITLE
ui: Logical Plan: fix known design issues

### ISSUE THREAD

**Issue by celiala** [cockroachdb/cockroach#34545]
Estimate:
🤔 - tricky
🏃- easy/quick

Status:
💯- merged
👍- on track
⚠- behind

### Fix known design issues (see images below)

Estimate | Status | PR | Description
---|---|---|---
 | | 💯| #34531 | * [x] ~1. Shift up horizontal node-connecting line.~
 | | 💯| #34531 | * [x] ~2. Replace HTML characters with Zeplin icons.~
🤔| | | * [ ] 3. Removing trailing vertical node-connecting line.
🤔| | | * [ ] 4. Fix z-index: orange (warn) nodes should appear in front of connectors.
🤔| | | * [ ] 5. Fix z-index: expanded nodes should appear in front of connectors.
🤔|💯 | #34758 | ~* [ ] 6. Nodes move a little on hover.~
🏃| 💯| #34758 | ~* [ ] 7. Give some vertical air between nodes (2ish px?).~
🏃| 💯| #34758 | ~* [ ] 8. Shift bullet tree left, so root bullet is directly under "Logical Plan" header.~
🏃| 💯| #34758 | ~* [ ] 9. :hover, pointer, leave as default (instead of pointer)~
🏃|💯 | #34758 | ~* [ ] 10. expanded attributes box: add some left air~

![image](https://user-images.githubusercontent.com/3051672/52218034-bed6c700-2867-11e9-9395-5c8cb0e39869.png)

![image](https://user-images.githubusercontent.com/3051672/52218042-c4cca800-2867-11e9-8983-35851714fafb.png)

**Comment by knz** [comment]
All the issues identified here have been addressed.
