### ISSUE TITLE
roachtest: make workload fixtures import blazing fast

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#34540]
While iterating on a roachtest, it can be super useful to run it on the same roachprod cluster that can be brought up very quickly using disk snapshots. It takes more than 30 minutes to restore any TPCC-1K test. This should take less than a minute from a snapshot.

Jira issue: CRDB-4638

**Comment by awoods187** [comment]
This would let us test larger setups much more cheaply. 10K takes ~2-3 hours to restore for example

**Comment by danhhz** [comment]
Vivek asked me in our 1:1 to comment on this with some context. There are two ways we already do this today.

The first is store dir snapshots. There is a `roachtest store-gen` command that sets up a cluster with the given number of nodes, restores a fixture, stops the nodes, and uploads a compressed snapshot of the store directories to google cloud storage. Then these can be downloaded later to start a cluster on top of them. Search for `workload fixtures url` to see how that part works.

The other way is zfs snapshots. ZFS is a filesystem that lets you take a snapshot and later roll back to exactly that point in time very quickly. This is only good if you're iterating on a single cluster that you're not going to destory. Search for "zfs" under pkg/roachtest for examples. Note that it requires you run on a different filesystem than we normally do, so it's unclear if this can be used for performance benchmarking.

Unfortunately, both of these are very manual and come with lots of gotchas. Some of the gotchas are fundamental to the technique and couldn't really be worked around even with staffing.

(I personally think it's possible to make `workload fixtures import` blazing fast once we eliminate the distributed sort in IMPORT (exactly like what we're moving to for index backfills). This would scale to very large sized clusters and avoids many/all of the gotchas with the above to techniques.)
