### ISSUE TITLE
sql: inverted index validation

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#34543]
We have a validation step after index backfill that validates the index https://github.com/cockroachdb/cockroach/pull/34263. We need to extend this for the inverted index case. One idea is:

1.  Create a SQL builtin that counts the number of indexable entries from JSON
2. Count such entries across a table and ensure that they match the size of the index.

**Comment by lucy-zhang** [comment]
validation: #35056
roachtest: #35058
