### ISSUE TITLE
storage/bulk,rocksdb: don't make/ingest many small SSTs, don't DOS L0

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#34579]
IngestExternalFile and AddSSTable take an SST and ingest it directly, dramatically reducing write amplification for large amounts of data compared to writing its contents normally by skipping several layers (raft log storage, WAL, some compactions, etc). This can be a huge benefit for larger files.

However directly if used to add small amounts of data per file, this can have some downsides. The worst of these appears to be the ability of a caller making and sending small SSTs to quickly fill up L0 -- RocksDB is picky about how many files can be in L0. Typically each file in L0 got there by flushing a full memtable, so it's limit of e.g. 20 files in L0 before it starts to complain (i.e. slow down writes) is not unreasonable. However a caller making and directly adding small files can hit that limit very quickly. A cluster with 16 or 32 callers all doing so to each other at once even more so.

The most dire consequence of this could be potentially be mitigated if we back pressured SST ingestion before L0 filled up to the point where it'd make RocksDB unhappy, but even if we did that, we'd still rather not hit it -- a) by definition it'd slow things down and there are still some drawbacks to ingesting a raw SST if it isn't bringing a hefty amount of data in with it.

If an SST overlaps with the memtable, ingesting it can must trigger a memtable flash -- currently this blocks all other requests and while the blcking can be mitigated with an explicit background flush, either flush still yet another file to L0, exacerbating the issue above. 

Finally, even if they somehow manage not to overlap anything and avoid L0, adding an very large number of tiny SSTs would still bloat the metadata, open files counts, etc and is just not ideal.

So, while building and directly ingesting an SST is fantastic compared to writing its content when it is very big, it has some downsides if it is very small. Ideally, if we're only adding a few keys, we'd avoid doing so via an SST build and ingestion and instead use the normal Rocks write path.

**Comment by petermattis** [comment]
I wonder if we can do something at a fairly low-level here. Right before we ingest an SST we could check its size and if it is below a threshold we could convert it into a WriteBatch. 

I had an idea for avoiding the hiccup during ingestion. See https://github.com/petermattis/pebble/issues/25.

**Comment by dt** [comment]
We've tried to mitigate this with #41705, but with pebble on the horizon, I'm excited at the potential to do smarter things in the storage engine. I'm thinking we could e.g. stick small files (contents) in the memtable (basically this PR), split files that span existing data if that would allow ingesting the parts lower, etc.
