### ISSUE TITLE
ui: time series metrics stopped updating in an otherwise healthy cluster

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#34575]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:
A customer experienced a failure of all time series in the admin UI. All time series values were not updated after a fixed point in time with no instability in the cluster or issues with the admin UI.

![image](https://user-images.githubusercontent.com/21692034/52277464-c6a77180-2922-11e9-9481-4340678c4836.png)

![image](https://user-images.githubusercontent.com/21692034/52283543-a8487280-2930-11e9-875c-9524322a11a6.png)

![image](https://user-images.githubusercontent.com/21692034/52283525-9b2b8380-2930-11e9-8e1a-c3c0dc58ac07.png)

![image](https://user-images.githubusercontent.com/21692034/52283586-bf876000-2930-11e9-9921-2b89846749a9.png)

 Note: Nodes 1-6 are not expected to be available - this cluster is healthy.

**To Reproduce**

We will need to discuss with @BramGruneir and @tim-o to identify exact reproduction steps and to grab logs from the cluster as some of the discussion happened via conference call.

**Environment:**
Version: 2.0.4

**Additional context**

This happened immediately before a period where the customer was expecting 4x typical load size. The lack of data in the UI made capacity planning for the impending increased load much more difficult.

**Comment by Fornax96** [comment]
I have a similar issue, in the last month the cluster has only made about 6 measurements:

![image](https://user-images.githubusercontent.com/1247928/58634491-b5c4a680-82eb-11e9-90f8-ead37dd7ce7b.png)

Is there any clue for what's causing this? This cluster is brand new.
