### ISSUE TITLE
server: Collect (and chart) IO time metrics

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#34591]
We use `gopsutil` to collect disk stats, but we only convert part of the information it gives us into timeseries. In particular, the io_time metric is used by node_exporter and has proven to be useful (because it has a known upper bound, so it can be used to compute a percent utilization) We should collect the other timeseries too and consider adding them to the hardware dashboard.

**Comment by awoods187** [comment]
From a conversation with @piyush-singh and @rkruze I've learned that this is a high priority ask but also might be doable in 19.1

The request for adding `await` time - @piyush-singh believe's the `gopsutil` package calls it `io_time` as @bdarnell  mentioned in the issue. The package is already set up thanks to @vilterp  , so if we could plumb additional metrics from the package and expose them as a time series that would help the SE team a ton - @robert-s-lee @rkruze and @drewdeally have all asked for this independently

if someone on core takes a look into it, we might be able to expose this as a time series might to start (i.e. not adding it to a dashboard, but just allowing us to add it to a custom chart on the debug page if the dashbaord part is a bunch of extra work).  cc @tbg

**Comment by awoods187** [comment]
Ping on this @tbg

**Comment by tbg** [comment]
Thanks Andy, I saw this but we're picking this up closer to the release if at all (stability first).
I might add that this really doesn't need to be done by a Core member, it could even be a starter project. cc @andy-kimball who has been looking for starter projects recently.

**Comment by awoods187** [comment]
I think that's a great idea @andy-kimball . It would be meaningful and fairly self-contained
