### ISSUE TITLE
ui, sql: Logical Plans: scrub sampled logical plan

### ISSUE THREAD

**Issue by celiala** [cockroachdb/cockroach#34595]
Do we need to scrub sensitive info from logical plans?

<img src="https://user-images.githubusercontent.com/3051672/52306281-77366500-2965-11e9-8024-42b7cd065218.png" width="400"/>

<img src="https://user-images.githubusercontent.com/3051672/52310979-4d843a80-2973-11e9-8a48-c9ca5cbdd27f.png" width="400"/>

<img src="https://user-images.githubusercontent.com/3051672/52311105-d602db00-2973-11e9-827c-59343007208b.png" width="400"/>

<img src="https://user-images.githubusercontent.com/3051672/52311262-62150280-2974-11e9-9373-12508dc56d46.png" width="400"/>

**Comment by knz** [comment]
This has been addressed. (I went and  manually verified)
