### ISSUE TITLE
Mini-RFC: Create brand new ranges on table creation

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#3460]
I'm not writing this up as a full RFC yet because it may be crazy, but wanted to get some opinions.

Some of the complexity in #3425 are related to the fact that when a table is created, it is a part of the preceding range, and it is later split asynchronously. This requires the [SystemConfig.ComputeSplitKeys](https://github.com/cockroachdb/cockroach/blob/31dff28d633bae74de964de6426a7ec531d508b2/config/config.go#L225) method to know about which tables exist to avoid creating an infinite number of split points. 

Instead, we could make the monolithic sorted map incomplete (and discontinuous due to the reserved table ID space): the initial range does not extend all the way to `KeyMax`; it stops at `TableDataMin`. When we create a table, we create a new range and insert it in the metadata map. This way, data for the table is in the right range from the beginning and never needs to wait on an asynchronous split.

The DistSender would need to be updated to recognize keys that have no corresponding range, and introducing a new way to create ranges (besides bootstrapping and splits) may be touchy, but it seems like this might be more elegant than the current asynchronous split method.

**Comment by petermattis** [comment]
If it would help, the SQL layer could make an explicit call to create a new range when a table is created.

**Comment by tschottdorf** [comment]
It does sound a little crazy to invest in the complexity of having two split mechanisms. Can you elaborate a little more on the motivation? #3425 seemed complicated because it broke a lot of tests' assumptions - were there a lot of other problems? My intuition is that we should work on making the existing method of splits less problematic if they are, and that introducing another mechanism to alleviate pains during testing or table creation just allows us to skirt the problems for the most part.
If the asynchronicity is an issue, it does seem like we could just split synchronously in some scenarios, such as table creation.

**Comment by bdarnell** [comment]
There were two issues in #3425. One was simply that splits are asynchronous. The other is that the final range contains all tables that may be created in the future, collapsed into a single point. We want to split on table boundaries, but only for tables that actually exist. Checking for the existence of tables when determining splits is awkward; it would be simpler in some respects to say that if a range's start key is in a table, it's end key must be in that same table. However, that would disallow the final range from which we slice off keyspace for new tables. 

If we could create ranges for new tables out of nothing instead of slicing them off the final range, we would be able to use a simpler split policy since we would never need to create new splits on table boundaries (the splits would be there from the beginning and we'd just have to make sure not to merge across them). But like I said, it's kind of crazy and involves fairly deep changes relative to the benefits, so I'm happy to drop it unless there are other potential uses for a sparse keyspace.
