### ISSUE TITLE
gossip register fail

### ISSUE THREAD

**Issue by YuleiXiao** [cockroachdb/cockroach#3465]
3 nodes in the same server.
Just start. Gossip register fail. It looks like occur after #3393. 

I1216 14:39:30.644819 223751 cli/start.go:146  starting cockroach cluster
W1216 14:39:30.644844 223751 server/server.go:98  running in insecure mode, this is strongly discouraged. See --insecure and --certs.
I1216 14:39:30.645096 223751 storage/engine/rocksdb.go:107  opening rocksdb instance at "d3"
I1216 14:39:30.645261 223751 gossip/gossip.go:701  starting client to 10.67.136.234:9000
W1216 14:39:30.645842 223751 rpc/client.go:296  rpc/codec/tls.go:63: unexpected HTTP response: 404 Not Found
I1216 14:39:30.646850 223751 server/node.go:271  store store=0:0 ([ssd]=d3) not bootstrapped
I1216 14:39:30.646875 223751 server/node.go:374  connecting to gossip network to verify cluster ID...
I1216 14:39:31.782245 223751 gossip/client.go:78  closing client to 10.67.136.234:9000: gossip/server.go:117: duplicate connection from node 0
I1216 14:39:32.645539 223751 gossip/gossip.go:701  starting client to 10.67.136.234:9000
I1216 14:39:32.646167 223751 gossip/client.go:78  closing client to 10.67.136.234:9000: gossip/server.go:117: duplicate connection from node 0
I1216 14:39:33.645771 223751 gossip/gossip.go:701  starting client to 10.67.136.234:9000
I1216 14:39:33.646427 223751 gossip/client.go:78  closing client to 10.67.136.234:9000: gossip/server.go:117: duplicate connection from node 0

**Comment by tschottdorf** [comment]
can you give your flags (particular --gossip)?

**Comment by YuleiXiao** [comment]
re-init store, and start 3 nodes.
./cockroach init --stores=ssd=d1

start flags:
./cockroach start --verbosity=0 --scan-interval=1m --max-offset=0 --insecure=true --addr="10.67.136.234:9000" --stores=ssd=d1 --gossip="10.67.136.234:9000" > ret1.txt 2>&1 &
./cockroach start --verbosity=0 --scan-interval=1m --max-offset=0 --insecure=true --addr="10.67.136.234:9001" --stores=ssd=d2 --gossip="10.67.136.234:9000" > ret2.txt 2>&1 &
./cockroach start --verbosity=0 --scan-interval=1m --max-offset=0 --insecure=true --addr="10.67.136.234:9002" --stores=ssd=d3 --gossip="10.67.136.234:9000" > ret3.txt 2>&1 &

I think the problem is here ```if lAddrStr, ok := s.nodeMap[args.NodeID]; ok && lAddrStr != lAddr.String()``` in ```Gossip```
When node re-init stores and start, first recived args.NodeID are all 0. So if node 2 come first, it will insert NodeID 0 into ```nodeMap```. And node 3 also come with NodeID 0, but different ```lAddr```, it will return error.

```
canAccept := true
if !s.incoming.hasNode(args.NodeID) {
	s.incoming.setMaxSize(s.maxPeers())
	if !s.incoming.hasSpace() {
		canAccept = false
	} else {
		s.incoming.addNode(args.NodeID)
		// This lookup map restricts incoming connections to a single
		// connection per node ID.
		s.nodeMap[args.NodeID] = lAddr.String()
	}
} else {
	// Verify that there aren't multiple incoming clients from same
	// node, but with different connections. This can happen when
	// bootstrap connections are initiated through a load balancer.
	if lAddrStr, ok := s.nodeMap[args.NodeID]; ok && lAddrStr != lAddr.String() {
		return nil, util.Errorf("duplicate connection from node %d", args.NodeID)
	}
}
```
