### ISSUE TITLE
sqlvalue type is not BYTES: UNKNOWN during index backfill

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#34683]
I have a table `TABLE t (c int, g int, i int, p string, primary key (c, g, i))`

If it matters, It was imported using testdata generated with github.com/dt/idxcsvgen.

I'm running a workload of `UPDATE t SET p = '%s' WHERE c = %d AND g = %d AND i = %d` with random values of `c`, `g`, and `i` in the domain used by the generator and random, 1000 byte encoded in hex for `p`.

As soon as I run `CREATE INDEX slow ON t (g, i, c) STORING (p)` my workload immediately begins returning intermittent `pq: value type is not BYTES: UNKNOWN` errors.

**Comment by jordanlewis** [comment]
Is this a new issue? We were just seeing something similar to this in execution. @yuzefovich was taking a look.

**Comment by yuzefovich** [comment]
Jordan is referring to #34524, but I think these are unrelated issues.

**Comment by vivekmenezes** [comment]
same as #33260 . Super happy you can reproduce!
