### ISSUE TITLE
changefeedccl: make a `rangefeeds are not enabled` error pause the job

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#34691]
Currently it fails the job, which means it has to be re-created. This is a small ux papercut, but given that the first changefeed in a cluster with default settings will hit this error, it might be worth doing.

Epic CRDB-2397

Jira issue: CRDB-4633

**Comment by danhhz** [comment]
Related to #36887

**Comment by miretskiy** [comment]
Closing this issue; we plan on supporting general pause on failure.
