### ISSUE TITLE
opt,distsql: annotate EXPLAIN ANALYZE plans with row count results

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#34723]
A common source of bad query plans is poor cardinality estimation. To find such bad estimates today, one needs to run `EXPLAIN (opt, verbose) ...` on a query to first see the expected row count of an operator, and then run `EXPLAIN ANALYZE` to see the true row count of the operator. We should annotate `EXPLAIN ANALYZE` with the expected row count, as matching these two up can be tricky, especially for someone not familiar with the opt plan format.

One thing that will make this difficult is that physical distsql processors don't match up 1:1 with logical opt operators. I'm not sure how to handle this yet.

cc @asubiotto @piyush-singh

**Comment by knz** [comment]
The logical plan stages should be numbered 1...N and the distsql processors should have a field that lists the number of the logical plan node that is responsible for it. This would make the task of matching them up much easier (and automatable).

**Comment by awoods187** [comment]
@RaduBerinde I think we can close this now with the 21.1 enhancements. What do you think?

**Comment by RaduBerinde** [comment]
Indeed, thanks!
