### ISSUE TITLE
sql: simplifyExpr doesn't coalesce (a, b) IN ((1, 2)) AND a = 1 

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#3472]
This should be simplified to `(a, b) IN ((1, 2))` but it's not. Although `a IN (1) and a = 1` is simplified properly. The analyzer probably doesn't infer much from tuples.

I think this also leads to computing suboptimal index constraints:
`a = 1 AND (a, b) IN ((1, 2))` with index []string{"a", "b"} produces constraint `[a = 1]` (it should produce `[a = 1, b = 2]`) - this is according to a hacked `TestMakeConstraints`.

**Comment by knz** [comment]
So this is rather non-trivial and finding a general solution is opening a pandora's box: to properly detect overlap between inclusion predicates (IN) and other comparisons you need a fully fledged predicate inference engine. My opinion is that we're still a bit early in the product lifetime to make this decision. Also, this type of optimization is rather complex and it is not clear to me yet how much is to be gained: how often is this an issue in practice? How many users are likely affected? I propose to revisit this issue only when we start getting more user feedback.

**Comment by andreimatei** [comment]
I don't remember the details of this exactly, but I think the correct span generation should be simple enough - just take the narrowest span. In fact @RaduBerinde has done some improvements to that code, maybe it's already fine.

**Comment by RaduBerinde** [comment]
It doesn't matter that much if the expression is simplified or not, but we should be generating the correct spans. We should keep this case in mind when we rewrite the span generation code (tracked by #6346).
