### ISSUE TITLE
sql: trimming the filter expression for a select doesn't work for compare expressions other than =

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#3473]
When an index is used for a SELECT, the filter expression used to validate results is trimmed to remove subexpressions that were implicitly evaluated as part of the index constraints. But this trimming isn't perfect - for example neither of the filters `a > 1` or `a < 1` are eliminated when there's an index on `a` and a corresponding constraint has been properly computed. I've left a note about it in `TestApplyConstraints`.

In the case of `a < 1`, this is due, at least superficially, to the following line which shortcuts the trimming if the constraint doesn't have a `start` point. Unclear why it does this.
https://github.com/cockroachdb/cockroach/blob/0dcc29ce74d487641b9effde648d780db31ebfe3/sql/select.go#L825

**Comment by andreimatei** [comment]
Note that some constraints are now rewritten too, which might make this elimination harder (e.g. `a > 5` -> `a >= 6`)

**Comment by andreimatei** [comment]
This is probably one of the first bugs I've filed. I'm dancing inside.

**Comment by mrtracy** [comment]
Over a year old!
