### ISSUE TITLE
New index backfill schema change resulted in error in newOrder: ERROR: no inbound stream connection (SQLSTATE XX000)

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#34738]
**Describe the problem**

While running tpc-c 10k, I created a schema change. The schema change caused an error that stopped QPS.

```
Error: error in newOrder: ERROR: no inbound stream connection (SQLSTATE XX000)
Error:  exit status 1
```

![image](https://user-images.githubusercontent.com/22278911/52493819-691d5a00-2b9a-11e9-95dd-95f20a276b98.png)
![image](https://user-images.githubusercontent.com/22278911/52493828-6e7aa480-2b9a-11e9-8df1-528e434dcbda.png)

**To Reproduce**
Setup TPC-C 1K like normal.

Set flag for new schema change implementation:
Roachprod sql $CLUSTER:1
SET CLUSTER SETTING schemachanger.bulk_index_backfill.enabled = true

Run for 6 hours.
roachprod run $CLUSTER:4 "./workload run tpcc --ramp=5m --warehouses=2000 --duration=6h --split --scatter {pgurl:1-3}"

After five minutes, in another shell, change the zone config ttl to 10 minutes
Roachprod sql $CLUSTER:1
ALTER RANGE default CONFIGURE ZONE USING gc.ttlseconds = 600;

Then create an index or non-unique on any column:
use tpcc
CREATE INDEX ON item (i_price)

**Expected behavior**
Index < 10 minutes 
Look at the front page on admin ui metrics SQL QPS and make sure it never went to less than 80% pre index 

**Environment:**
v2.2.0-alpha.20181217-1144-ge3e4f96

**Comment by awoods187** [comment]
[cockroach.log](https://github.com/cockroachdb/cockroach/files/2846090/cockroach.log)
[cockroach.log](https://github.com/cockroachdb/cockroach/files/2846092/cockroach.log)
[cockroach.log](https://github.com/cockroachdb/cockroach/files/2846093/cockroach.log)

**Comment by awoods187** [comment]
Retried this again on the same cluster after dropping the index and restarting tpc-c. I waited a bit longer but the index took much longer (I assume because of new data) and did not hose the cluster. It did reduce performance:

![image](https://user-images.githubusercontent.com/22278911/52500293-a1796400-2bab-11e9-9b65-cbf035e99649.png)
![image](https://user-images.githubusercontent.com/22278911/52500331-bce46f00-2bab-11e9-8f86-ea2f4f75f8dd.png)

**Comment by vivekmenezes** [comment]
this is related to https://github.com/cockroachdb/cockroach/issues/31361

We should close it unless we can reproduce it.

**Comment by jordanlewis** [comment]
This is 2 releases old at this point; closing.
