### ISSUE TITLE
Unbalanced service latency among three node tpc-c 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#34750]
**Describe the problem**

I'm running TPC-C 1K on a three node cluster. I've been adding and dropping indexes and noticed that service latency isn't equally split among the three nodes:

![image](https://user-images.githubusercontent.com/22278911/52501156-afc87f80-2bad-11e9-99e1-2c8acf385dc6.png)

This didn't seem to happen till I added and removed indexes:
![image](https://user-images.githubusercontent.com/22278911/52501245-e30b0e80-2bad-11e9-9af5-adf666971359.png)

Might also be related to https://github.com/cockroachdb/cockroach/issues/34744.

**Comment by jordanlewis** [comment]
Closing due to age.
