### ISSUE TITLE
Spike in latency to 10s on some nodes in tpcc 10k

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#34759]
**Describe the problem**

A few nodes exhibited sql service latency of more than 10s when running tpc-c 10k on a 15 node 16 cpu cluster. 

![image](https://user-images.githubusercontent.com/22278911/52521500-fff32080-2c45-11e9-821d-13aa0d6b824b.png)

[cockroach.log](https://github.com/cockroachdb/cockroach/files/2847839/cockroach.log)

The final tpmc and efficiency took a corresponding hit:
```
_elapsed_______tpmC____efc__avg(ms)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
  900.0s   117076.0  91.0%   1476.3    771.8   3221.2   4563.4  11811.2 103079.2
```

**Comment by asubiotto** [comment]
I saw something similar when running tpcc on Adriatic to qualify the release and it ended up being a workload bug. I used a modified (b88ade9e23 + removing reference to `experimental_lookup_join`) workload binary that solved this issue. Haven't had the time to track down the offending commit but I would suggest rerunning this. If the binary up on Adriatic serves you, you can scp it (`workload.sep`). Let me know if you want help.

**Comment by lunevalex** [comment]
This report is from 2.2.0-alpha, closing due to age since multiple changes/improvements with TPCC since then.
