### ISSUE TITLE
sql: remove parallel statement execution and deprecate RETURNING NOTHING

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#34789]
_I was planning on making this change immediately but figured I'd get buy-in from relevant stakeholders beforehand so that there's not too much back and forth on the PR itself._

Parallel statement execution has served its role well, but with the introduction of transactional write pipelining, the cases where it is useful or should be recommended have dropped to near-zero. I think it's time to remove it. I also know others feel differently. Here's a list of reasons to remove the feature and reasons to keep it:

### Reasons to remove
- **Technical debt**. This is getting in the way of future development. For instance, it slowed down optimizer development and the team decided to ignore the feature. We also have issues tied to it (#17504 and #18226).
- The feature is rarely needed anymore. Txn pipelining takes almost all of the win away from parallel statement execution (see below)
- The feature is confusing to users. When should they use it? When not?
- Hard to use correctly. How does this work with ORMs? What are the error semantics again?
- Even if we want to allow some kind of concurrency between reads in a transaction, this isn't the way to do it. A better approach is permitting the use of multiple portals concurrently, as @andreimatei and @jordanlewis experimented with.
- Only ~2% of CRDB users have ever used the feature.

### Reasons to keep
- Removing it would be breaking compatibility.
- Removing the feature would prevent it from being extended further.
- There are still rare cases where `RETURNING NOTHING` will be faster than standard txn pipelining, such as when a gateway is far away from a leaseholder.

### Deprecation/Removal Plan

1. Remove all logic about executing statements in parallel (e.g. `ParallelizeQueue`, `DependencyAnalyzer`, `connExecutor.execStmtInParallel`, etc.)
2. Remove all tests for executing statements in parallel
3. Keep `RETURNING NOTHING` syntax but make it a no-op other than still discarding results on succesful queries. Doing this will prevent us from breaking client applications.
4. Remove documentation on parallel statement execution
5. (optional) In some later release, remove the `RETURNING NOTHING` syntax entirely

What do people think? 

cc. @bdarnell @andreimatei @jordanlewis @knz

**Comment by bdarnell** [comment]
SGTM. I kind of like the idea of letting the user explicitly state what they expect to be returned (instead of always giving them the traditional row count that often gets ignored) so I'm mildly in favor of keeping the syntax around indefinitely, but +1 to getting rid of all the complex parallelization logic that comes with this feature.

**Comment by jordanlewis** [comment]
I'm heavily +1 in favor of getting rid of the parallel logic. Maintaining it in the face of changes to the sql infrastructure has already been a minor burden - it will only become more so over time.

**Comment by knz** [comment]
yep SGTM too! thanks for thinking this through.

**Comment by nvanbenschoten** [comment]
@andreimatei does this have your approval?

**Comment by andreimatei** [comment]
yes, in principle.
I haven't had a chance to look at the PR yet, but I'd like to. Feel free to
merge if you're in a hurry, or give me one more day.

**Comment by nvanbenschoten** [comment]
👍 There's no PR yet, just wanted to establish consensus before I ripped everything out.
