### ISSUE TITLE
distsqlrun: routers don't respond to cancellation

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#34796]
A customer has reported a bug with stuck queries. The goroutines of the machine (running 2.1.3) with stuck queries include some like this:

```
goroutine 11365647 [chan send, 3928 minutes]:
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*RowChannel).Push(0xc432e17840, 0xc63c47bdb0, 0x7, 0x7, 0x0, 0x10)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go:424 +0xd3
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*routerBase).start.func1(0x301ffe0, 0xc432e17cc0, 0xc48190c480, 0xc671e9e900, 0xc679c28188)
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/routers.go:324 +0x6e1
created by github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*routerBase).start
    /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/routers.go:278 +0x9f
```

The corresponding code is:

```
func (rc *RowChannel) Push(row sqlbase.EncDatumRow, meta *ProducerMetadata) ConsumerStatus {
        consumerStatus := ConsumerStatus(
                atomic.LoadUint32((*uint32)(&rc.consumerStatus)))
        switch consumerStatus {
        case NeedMoreRows:
                rc.dataChan <- RowChannelMsg{Row: row, Meta: meta}
```

`rc.dataChan` is a fixed-size channel. If nobody reads from it, then this call will block forever. I think what happened in this case is that the query was cancelled (which we know is a possibility since this customer runs with a 30s query timeout on their session), and the consumer of the router quit due to the context cancellation.

Since nothing ever read from the RowChannel's `dataChan` before it quit, the `Push` call will block forever and never find out that somebody set the consumer status on the row channel to `DrainRequested` or `ConsumerClosed`.

I think the solution here should be to give `Push` a context so that it can check for context cancellation in a `select` while trying to push to the `dataChan`, and bail out if its context is cancelled.

**Comment by tim-o** [comment]
Zendesk ticket #[3035](https://cockroachdb.zendesk.com/agent/tickets/3035) has been linked to this issue.
