### ISSUE TITLE
sql: collation information should be exposed via introspection in separate column

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#34831]
Reported here: https://github.com/cockroachdb/cockroach/issues/22298#issuecomment-462707829

Talking about `information_schema.columns.crdb_sql_type`:

> `"name" string COLLATE "en_US"` stores as `STRING COLLATE en_US`
> `"name" string(30) COLLATE "en_US"` stores as `STRING(30) COLLATE en_US`
> it brings little difficulty getting column collation, unlike postgres which stores collation in separate column named `column_collation`

CockroachDB currently does not support `column_collation` - it should probably be added.

**Comment by jordanlewis** [comment]
It got added in #37271.
