### ISSUE TITLE
Invalid Lease

### ISSUE THREAD

**Issue by tzilist** [cockroachdb/cockroach#34844]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:
After running a 3 cluster node, default installed from helm on k8s, the node will eventually stop responding. Attached are screenshots of what is happening. Seemingly restarting the nodes fixes the problem.

**To Reproduce**

What did you do? Describe in your own words.
Nothing in particular, the nodes will eventually stop responding
If possible, provide steps to reproduce the behavior:

**Expected behavior**
Raft consensus should not be failing? Not exactly sure what is going on

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

<img width="974" alt="screen shot 2019-02-12 at 3 24 15 pm" src="https://user-images.githubusercontent.com/14153237/52675081-7740e280-2eda-11e9-8428-7ccdd1a65d18.png">
<img width="1379" alt="screen shot 2019-02-12 at 3 24 07 pm" src="https://user-images.githubusercontent.com/14153237/52675083-7a3bd300-2eda-11e9-9f49-e93daeb238c7.png">
**Environment:**
 - CockroachDB version [e.g. 2.1.4]
 - Server OS: [e.g. Linux/Distrib]
 - Client app [e.g. gorm]

**Additional context**
What was the impact?

We are running on GKE

**Comment by tbg** [comment]
@tim-o could you qualify?

**Comment by tim-o** [comment]
Hi @tzilist - it'd be helpful to get more information about the cluster:

- What machine type are you using for each node? 
- What version of CRDB are you running?
- What workload are you running on the cluster when it stops? What are your DDL and DML for that workload? (general characteristics are helpful here even if you can't give us the exact DDL and DML)
- How much available CPU and memory do you have while that workload is running? Are resources being exhausted on the crashing node?

It also would be helpful to get the output of a [cockroach debug zip](https://www.cockroachlabs.com/docs/stable/debug-zip.html) from the cluster, as well as a timeline (i.e.: my test began at 1:30 UTC, I saw n3 crash at 1:45 UTC, and restarted it at 1:50.)

**Comment by tzilist** [comment]
@tim-o sure thing!

We are on GCP, using GKE. Nodes are 

- n1-standard-2
- Version 2.1.4 (latest I believe)
- DDL = create, insert, delete    DML = select insert update delete, normal (All normal CRUD stuff)
- Our nodes are not out of resources however each cockroach node seems to be using about 2Gb of memory at the time. Other than that I am not super sure.

Next time it happens I will definitely upload the debug zip but it hasn't happened in the last day. It seems to happen periodically. Will keep you posted.

Thanks for your help!

**Comment by tim-o** [comment]
Hey @tzilist , closing this per https://github.com/cockroachdb/cockroach/issues/38616
