### ISSUE TITLE
getting error : pq: transaction is too large to complete; try splitting into pieces so frequently while updating rows

### ISSUE THREAD

**Issue by rajnish4internet** [cockroachdb/cockroach#34876]
Hi ,
I have a table where around 2millions records are present, now I need to update a column value using where clause <column using in where clause is already index>, but i am getting  error:
pq: transaction is too large to complete; try splitting into pieces 

so what I did update with limit 10000 rows  and it is working great, but after 4 -5 times hits it start throwing same error again.
I also tried below setting ,
SET CLUSTER SETTING kv.transaction.max_refresh_spans_bytes=1e6;

# for cluster information , newly setup 3 node cluster  and on admin ui it is showing 37-38 % memory used on all 3 nodes.

**Comment by justinj** [comment]
Hi @rajnish4internet,

What led you to change that setting in particular? It sounds to me like you probably just need to use smaller batches for your updates.

Since it's not clear to me there's a specific product request here, I'm going to close this issue. This kind of question is more appropriate for our [forum](https://forum.cockroachlabs.com/), but feel free to comment if you disagree.

**Comment by rajnish4internet** [comment]
Hi ,
see I just put in this situation lets , I added a new column in table where 2 millions data there now i need to filled the data in that column using concat(col1,col2), this is simple update i wanna to do with 2 millions of rows, is it possible or not I just wanna confirm?

**Comment by justinj** [comment]
If you don't want to batch your updates, one option you have is to create a computed column with the computation you want to do and then turn it into a regular column, we have [docs](https://www.cockroachlabs.com/docs/stable/computed-columns.html#convert-a-computed-column-into-a-regular-column) on how this works.

**Comment by rajnish4internet** [comment]
Thanks it will work for me.
