### ISSUE TITLE
sql: sampled query plans do not have attributes anonymized 

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#34889]
When talking to @jordanlewis about https://github.com/cockroachdb/cockroach/issues/34426, he made a good point that we shouldn't even be pretty printing key spans to begin with. We started digging and found that they aren't being anonymized correctly.

For instance:

<img width="1098" alt="screen shot 2019-02-13 at 8 18 24 pm" src="https://user-images.githubusercontent.com/5438456/52755724-e7c82c00-2fcc-11e9-9af4-3888442b0fb6.png">

@knz @celiala

**Comment by knz** [comment]
Good catch. looking into it
