### ISSUE TITLE
sql: ability to craft CRDB Jobs that include DDL and DML 

### ISSUE THREAD

**Issue by gigatexal** [cockroachdb/cockroach#34909]
**Is your feature request related to a problem? Please describe.**
For users coming from traditional databases like MySQL and from the ORM world where things like Alembic is used to handle migrations being able to group DDLs and DMLs that relate to them into a CRDB Job would be really helpful.

**Describe the solution you'd like**
Some way to do something like `CREATE JOB ... <DDL stmt 0 ... DDL stmt n> ... <DML stmt 0 ... DML stmt N>` so that the user could group atomic updates where something like adding a column (DDL) would not make sense if it were not populated with data from another column (DML). This should all still happen in the background and not block updates, deletes, inserts from the target table.

I see this like adding the & to a unix command where it backgrounds your task. One can aggregate many statements and then place them all in the background at a time.

Maybe even a keyword to inform the work within a transaction is to be a job could work. Basically the ability to influence what becomes a job would be great!

**Describe alternatives you've considered**
The current solution we have come up with so far is a bit hacky. We have seen that we must separate DDL changes from DML changes and both from code changes. But whereas we could just use Alembic to issue a migration and wait and wait and wait until it was done, when it was done, we would know that all migrations be they DML or DDL or both were done and the code deployment could continue. The above feature request would get us somewhat back to that idea but still leverage the killer feature of online schema migrations but would also make for such updates to be a bit more atomic.

**Additional context**

Jira issue: CRDB-4618

**Comment by justinj** [comment]
cc @danhhz for triage

**Comment by danhhz** [comment]
I pick up jobs maintenance here and there, but this sounds like significant new feature work. I'd guess SQL frontend.

**Comment by knz** [comment]
wow that's a super cool idea. I love it :sparkling_heart:

**Comment by gigatexal** [comment]
@knz this is likely a bigger change than most -- is it on the roadmap somewhere?
