### ISSUE TITLE
SQL for getting the names of partitions

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#34907]
We should make it easy for user to retrieve the names of partitions via SQL, similar to how you can currently get other types of objects with `SHOW CREATE`. Something like `SHOW PARTITIONS FOR <table>` would be nice. But it should show ALL partitions for the table, in my opinion, both of the primary and all secondary indexes.

Also, after you define partitions on a table and its secondary indexes, `SHOW CREATE TABLE` only gives you the syntax for creating the partition on the primary index. I wonder if that could be expanded to include partitions on secondary indexes, too. 

*Why it's important to be able to easily retrieve partition names?* After partitioning table data (primary and secondary indexes), you have to create zone configs for each partition. To do that, you need the names of the partitions.

**Comment by nvanbenschoten** [comment]
@jseldess the `crdb_internal.partitions` table should give you the name, table id, and index id of each partition. That doesn't address your second concern, but it addresses the first, right?

**Comment by rohany** [comment]
closed via #39053
