### ISSUE TITLE
AUTHORS.md is out of date

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#3490]
Should it be removed or automatically generated?

**Comment by bdarnell** [comment]
We should get rid of it unless it has some legal/copyright significance.

**Comment by petermattis** [comment]
@spencerkimball ?

**Comment by spencerkimball** [comment]
There's no legal or copyright significance. It's just the list of
contributors for informational purposes, and it's of course very out of
date. I say we just get rid of it and update the copyright headers in each
file which refer to it: "See the AUTHORS file for names of contributors."

We could change that to "See
https://github.com/cockroachdb/cockroach/graphs/contributors for names of
contributors" or we could just leave that as an exercise for the reader.

**Comment by JackKrupansky** [comment]
FWIW, over in Apache open source land, the practice is to not have authors/contributors explicitly mentioned in source code and to use the svn/git commit history and CHANGES.txt and Jira to record the contributions of people. There is also a web page for each Apache project that lists the committers (but not non-committer contributors.) Github graphs/contributors provides a precise listing of who has contributed and how much. A wiki page for third parties who offer consulting, services, and support is common as well.
