### ISSUE TITLE
workload: create `indexes` workload to stress one or more secondary indexes

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#34912]
We added a `--secondary-index` flag to `kv` in https://github.com/cockroachdb/cockroach/pull/31573 to allow easy testing between workloads with and without secondary indexes. This works ok, but we've realized it's insufficient for complete benchmarking of secondary indexes. Here are a few reasons why:
1. it can only support a single secondary index
2. the secondary index contains the entire row, leading to it essentially doubling the storage cost
3. it's not realistic

We should create a new `workload`, and by extension a new `roachtest`, with knobs to specifically stress secondary index performance. Here's a proposed schema:

```
CREATE TABLE indexes (
    key  UUID PRIMARY KEY,
    col0 INT,
    col1 INT,
    col2 INT,
    col3 INT,
    col4 INT,
    col5 INT,
    col6 INT,
    col7 INT,
    col8 INT,
    col9 INT,
    data BYTES(64)
)
```

The workload could have a `--indexes` flag that defaults to zero and can be in the range `[0, 10]`. Depending on this value, we'll index that many `col` columns. Note that the `data` column will constitute about half the size of the row and will never be indexed.

This will give us the ability to slowly ramp up the number of secondary indexes on a table and observe how we scale along this dimension.

@robert-s-lee mentioned that a realistic workload for this would look something like:
> Insert ( as the data has to be loaded first ), then update.  With the update, want to make sure update of columns that do not have secondary indexes do not effect performance.

**Comment by nvanbenschoten** [comment]
@rkruze mentioned that we'll want to add an option to toggle whether indexes are declared as `UNIQUE` or not. This influences where in the secondary index key-value pair we store the primary key.

**Comment by danhhz** [comment]
I have zero context on this issue, but wanted to make sure you're aware that @dt just sent https://github.com/cockroachdb/cockroach/pull/34916 out for review, which might be in the same wheelhouse. (or might not!)

**Comment by dt** [comment]
at first glance this doesn't look quite like #34916 but maybe with a bit of wiggling they could be unified -- #34323 has some pretty specific interests w.r.t. its PK vs Index key layout which don't look quite like this schema but maybe with a little work, they could be closer.

My first reaction is to let them each grow on their own for a bit and then see how much they actually have in common, but I could also be convinced that we'd rather have one, and rather have less churn in the def of a workload over time so historical data is more useful. * shrug *
