### ISSUE TITLE
can we update table using join like we are doing in mysql ?

### ISSUE THREAD

**Issue by rajnish4internet** [cockroachdb/cockroach#34921]
Hi ,
lets say we have 2 table

table1 have columns id,name,address,dept_id,depthod

table2 have columns deptid,depthod

now I want to update table1 column depthod using join , below is the sql,

update table1 t1 join table2 t2 on t1.deptid=r2.deptid set t1.depthod=t2.depthod ;
this is valid on mySQL is it possible in cockroachdb or not ? i tried but it is falling is it any other way to do it?

**Comment by jordanlewis** [comment]
What do you want to have happen? Please phrase your question more clearly - we can't help otherwise.

**Comment by ricardocrdb** [comment]
Hello @rajnish4internet 

Can you let us know what your questions are if you are still running into the same type of issues? 

Cheers,
Ricardo

**Comment by rajnish4internet** [comment]
Yes I am facing same problem.

I am able to run below query on MySQL: now similar query I want to execute
on cockroachDB,
running on mysql, not in cockroach db.
UPDATE T1, T2,
INNER JOIN T1 ON T1.C1 = T2. C1
SET T1.C2 = T2.C2,
    T2.C3 > 100
WHERE T2.ID > 10000;

**Comment by hanhantw** [comment]
Have the same question here.

I'd like to update columns of table a from the columns of table b on the condition that a.id = b.id

Is this feature workable in any version now?
