### ISSUE TITLE
sql/stats: big error dump on control-c of node

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#34926]
I control-c'd my development node and was greeted with a large dump of errors like the following, but repeated many more times. 

I think these should be silenced when a node is draining, as they don't really represent error conditions.

```
E190214 20:22:47.156218 820 sql/stats/automatic_stats.go:290  failed to get table statistics: get-table-statistics: node unavailable; try another peer
E190214 20:22:47.156854 820 sql/stats/automatic_stats.go:290  failed to get table statistics: get-table-statistics: node unavailable; try another peer
E190214 20:22:47.157439 820 sql/stats/automatic_stats.go:290  failed to get table statistics: get-table-statistics: node unavailable; try another peer
```

**Comment by rytaft** [comment]
Thanks for the report! Are you able to reproduce it easily? I haven't been able to reproduce yet.

**Comment by jordanlewis** [comment]
Nope, not able to reproduce easily. The node that I have on this computer has a ton of tables is the only clue I have.

Do tables get enqueued into the statistics collector just when a node starts even without mutating the tables?

**Comment by rytaft** [comment]
Yea that would make sense if you have a ton of tables. All tables get enqueued once at startup for a possible refresh if needed. Thanks for the info!

**Comment by jordanlewis** [comment]
Yeah my guess would be that the node enqueued a ton of tables, slowly is chewing through them, and then I ctrl-c the node and the ones enqueued maybe errored out really quickly in a row after the currently active one stopped with a context cancel / quiescence signal, something like that.
