### ISSUE TITLE
sql: a string is considered to exist if it matches a primitive JSON string

### ISSUE THREAD

**Issue by losinggeneration** [cockroachdb/cockroach#35001]
**Describe the problem**

Based on the documentation for Postgres [JSON](https://www.postgresql.org/docs/current/datatype-json.html#JSON-CONTAINMENT) the following should be true:
```sql
SELECT '"foo"'::jsonb ? 'foo';
```

**To Reproduce**

Postgres:
```
psql (11.1 (Debian 11.1-2), server 11.0 (Debian 11.0-1.pgdg90+2))
postgres=# SELECT '"foo"'::jsonb ? 'foo';
 ?column? 
----------
 t
(1 row)
```

Cockroach:
```
psql (11.1 (Debian 11.1-2), server 9.5.0)
root=# SELECT '"foo"'::jsonb ? 'foo';
?column? 
----------
 f
(1 row)
```

**Expected behavior**
I would expect "foo" to equal the primitive value 'foo' considering the other examples on that page yielded the same results between the two implementations in other cases I tried.

**Environment:**
 - CockroachDB version [v2.1.4]
 - Server OS: [Debian buster/sid, Docker 18.09.1 build 4c52b90]
 - Client app [any]

**Comment by justinj** [comment]
Thanks for the report @losinggeneration! I've opened to #35005 fix this.
