### ISSUE TITLE
Support sliced selects

### ISSUE THREAD

**Issue by bra-fsn** [cockroachdb/cockroach#35026]
Elasticsearch has a very useful and cool feature, named sliced scroll (a scroll is a stateful, server side paging):
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html
I'm looking for a similar feature in cockroach db.
The rationale behind that is to allow for a bunch of clients to work in parallel on chunks of a result set.

I could think of a command like:
`select * from table where slice(0, 10, key)`
The first argument means which slice the user want out of the second number of all slices.
The key should be the column name on which the hashing is done.

In this form it would mean max slice number of parallel scans on all ranges I guess, I'm not sure the ranges itself can be used to help partition the data, like with elasticsearch's shards (which aren't so dynamic like crdb's ranges, where a split can occur anytime).

Also differing from elasticsearch is that this is still stateless, so a paging would be needed on the client side, like:
`select * from table where id>$last_id slice (0, 10, key) limit 100;`

**Comment by jordanlewis** [comment]
Hi @bra-fsn, thanks for the feature request! Are you essentially asking for a way to easily partition all of the ranges of `key`? For example, if your key column were UUIDs, `slice(0,10,key)` would give you a range containing the first 10th of all UUIDs?

This actually comes up a lot, and would be handy to have for other things. `ALTER TABLE SPLIT AT` is an example - you often want to split a table into equal chunks, and normally you have to do a bit of work to write a script to generate the equal chunk boundaries. A builtin that did this in a datatype agnostic way would be pretty nice.

If you're interested, we could help guide you to make a builtin function that does this. You'd add some code to `pkg/sql/sem/builtins/builtins.go` for this.

**Comment by bra-fsn** [comment]
Well, this is kind of a dynamic (not materialized if I can say that) partitioning, yes.
Yes, in the case of UUIDs, this should return 10th of the whole range.
