### ISSUE TITLE
jobs get created multiple times 

### ISSUE THREAD

**Issue by schorzz** [cockroachdb/cockroach#35037]
**Describe the problem**

I tried to alter a table (drop a column) and two jobs got created for a single sql statement.

**To Reproduce**

I tried to alter a table via [Alembic](https://alembic.sqlalchemy.org/en/latest/) AND via cockroach sql. So far this only happens when i want to drop a column. The problem is, that the statement (code or sql-cli) blocks until BOTH jobs are finished. Also, both jobs succeed even though a column can be deleted just once.

1. Create empty schema in a 5 node cockroach cluster
1. insert about 100k rows
1. add column with index
1. drop column
1. Look at UI-JOBS OR sql-cli show jobs  
1. See same job two times with different job-ids

**Expected behavior**
A job for ALTER TABLE should be executed once, and the second job should fail.

**Environment:**
 - CockroachDB version  2.1.4
 - Docker Image 2.1.4 
 - cockroach sql, SQLAlchemy, [Alembic](https://alembic.sqlalchemy.org/en/latest/)

**Comment by schorzz** [comment]
Apparently, cockroach deletes indices implicitly if you drop the column. Although the naming of the jobs are a little bit confusing.

**Comment by awoods187** [comment]
@schorzz I went ahead and opened this issue (https://github.com/cockroachdb/cockroach/issues/35051) to improve upon this so that other users won't be similarly confused. Thank you for sharing your feedback!
