### ISSUE TITLE
schema: Better distinguish between the delete jobs for columns and indices

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#35051]
**Describe the problem**

Better distinguish between the delete jobs for columns and indices (Cockroach drops indices implicitly if you drop the column). 

A user ran into a problem where the job's table wasn't enough to distinguish what was happening on their cluster. https://github.com/cockroachdb/cockroach/issues/35037#event-2148659041

**Comment by jordanlewis** [comment]
@spaskob could you take a look at this? It should be a matter of changing the wording of the job titles that get created for deletion of columns and indexes.
