### ISSUE TITLE
opt: lift mutations into a top-level structure

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#35060]
Today, `[...]` mutations exist in subtrees. This is problematic because the fact that they must be executed interferes with our ability to rewrite certain trees, and it requires a lot of thought around when it's safe to eliminate subtrees. There's been some offhand discussion of this in the past but I wanted to make it concrete.

A strawman proposal is this (I'm not sure how much support this will require from exec, cc @jordanlewis):

We introduce a new operator, `With`:

```
[Relational]
define With {
  Input Expr
  Extra Expr
  ID WithID
}
```

Which, upon evaluation, executes `Extra` entirely including any side-effects, and makes it possible for `Input` to refer to the result of `Extra` via another new operator, `Reference`:
```
[Relational]
define Reference {
  ID WithID
}
```

Initially this can be subject to the limitation our CTEs have today, which is that they can be referenced at most once (though we can lift the restriction that they're referenced *at least* once), but this will also extend to work with temp table support.

There's a hiccup with this that I haven't entirely thought through yet, which is that the `[...]` can be within a correlated subquery, which could possibly block lifting (perhaps we could just disallow that).

cc. @RaduBerinde @rytaft @andy-kimball

**Comment by RaduBerinde** [comment]
Is the `[ .. ]` syntax crdb-specific? If yes, we could disallow correlations that cross the `[` boundary.

As far as I can google, in postgres you need to use `with` anyway, e.g.
```
WITH updated AS (UPDATE test SET description = 'test' RETURNING id)
SELECT * FROM test WHERE id IN (SELECT id FROM updated);
``

**Comment by justinj** [comment]
Yes, it's crdb-specific, so I think it's probably acceptable to disallow correlation there.

**Comment by RaduBerinde** [comment]
@justinj - I think this will be a simple exercise once we have the rules to move mutation `With`s to the top?

**Comment by RaduBerinde** [comment]
#34504 is kind of dependent on this because it would make detecting multiple mutations easier.

**Comment by justinj** [comment]
Yeah, I think it won't be too bad.

**Comment by RaduBerinde** [comment]
@justinj this is done, right?
