### ISSUE TITLE
sql: use common terminology for bind vars

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#3507]
See https://reviewable.io/reviews/cockroachdb/cockroach/3482#-K5lUxm5FRgzkUlv1ioX:-K5mcmqeKZuj9DDPaP4C:-642077114

Also rename valarg: https://reviewable.io/reviews/cockroachdb/cockroach/3482#-K5lrmax5tO4A45iki_s:-K5lrmax5tO4A45iki_t:1233783584

**Comment by petermattis** [comment]
@mjibson Anything left to do here?

**Comment by knz** [comment]
Fixed by #6944.
