### ISSUE TITLE
Connection timed out + memory budget exceeded when partitioning 30 node 8 cpu cluster

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#35096]
**Describe the problem**
I'm attempting to partiton a cluster using roachprod and running into timeout and SQLSTATE errors.
Here is normal pointing at node 1:
```
Andrews-MBP-2:~ andrewwoods$ roachprod run $CLUSTER:31 "./workload run tpcc --warehouses=10000 --partitions=10 --duration=1s --split --scatter {pgurl:1}"
Error: dial tcp 172.31.41.49:26257: connect: connection timed out
Error:  exit status 1
```
I then tried pointing it at node 2.
```
Andrews-MBP-2:~ andrewwoods$ roachprod run $CLUSTER:31 "./workload run tpcc --warehouses=10000 --partitions=10 --duration=1s --split --scatter {pgurl:2}"
Error: preparing
		SELECT c_balance, c_first, c_middle, c_last
		FROM customer
		WHERE c_w_id = $1 AND c_d_id = $2 AND c_id = $3: ERROR: root: memory budget exceeded: 10240 bytes requested, 4055674880 currently allocated, 4055681024 bytes in budget (SQLSTATE 53200)
Error:  exit status 1
```

**To Reproduce**
roachprod create $CLUSTER -n 31 --clouds=aws --aws-machine-type-ssd=c5d.2xlarge
roachprod run $CLUSTER -- "DEV=$(mount | grep /mnt/data1 | awk '{print $1}'); sudo umount /mnt/data1; sudo mount -o discard,defaults,nobarrier ${DEV} /mnt/data1/; mount | grep /mnt/data1"
roachprod stage $CLUSTER:1-30 cockroach
roachprod stage $CLUSTER:31 workload
roachprod start $CLUSTER:1-30 --racks=10 -e COCKROACH_ENGINE_MAX_SYNC_DURATION=24h
roachprod adminurl --open $CLUSTER:1
roachprod run $CLUSTER:1 -- "./cockroach workload fixtures import tpcc --warehouses=10000 --db=tpcc"
roachprod run $CLUSTER:31 "./workload run tpcc --warehouses=10000 --partitions=10 --duration=1s --split --scatter {pgurl:1}"

**Environment:**
v2.2.0-alpha.20190211-254-g1387b4f

**Comment by awoods187** [comment]
Not sure if this is Cockroach or a Roachprod problem so I tagged @tbg and @petermattis

**Comment by awoods187** [comment]
@nvanbenschoten mentioned @RaduBerinde might know more

**Comment by RaduBerinde** [comment]
Does anyone know off hand how much sql memory roachprod configures? The reported budget is 4GB (the machines have 16GB).

**Comment by petermattis** [comment]
> Does anyone know off hand how much sql memory roachprod configures? The reported budget is 4GB (the machines have 16GB).

`--max-sql-memory=25%`. `roachprod` also uses 25% for `--cache`.

**Comment by petermattis** [comment]
Why is so much memory being used for SQL processing? 4GB seems like more than enough.

**Comment by RaduBerinde** [comment]
It's 10000 warehouses so I assume there are a ton of queries running at the same time. We should invest in some infrastructure to give us visibility into what the sql mem budget is used for, something that can be monitored before things go south.

**Comment by awoods187** [comment]
@RaduBerinde technically the load wasn't running yet. It was attempting to begin partitioning (the step before running the load).

**Comment by RaduBerinde** [comment]
The error you pasted contains an "order status" tpcc query.

**Comment by RaduBerinde** [comment]
Oh but it's an error during prepare?! That indeed happens in the beginning. It's not even executing anything during prepare.

**Comment by RaduBerinde** [comment]
Looking at `workload`, it would set up 10000 * 2 connections. We prepare 18 statements on each of those connections to later reuse. Each prepared statement can take on the order of 10KB. That comes out to 3-4 GB.

You can add `--method=simple` to not use the prepare method. But the right thing would be to decrease the number of connections in this case.

We should also have a hard limit on that on the server side.

What's interesting here is that if the query cache is working as intended, all 20k instances of each statement are actually the same structure. But the memory accounting is pessimistic and assumes that each prepared statement could be holding on to the last copy.

**Comment by awoods187** [comment]
A node eventually died due to OOM a while after this filed when I tried to run it again
```
[33357.303219] Out of memory: Kill process 4811 (cockroach) score 964 or sacrifice child
[33357.306144] Killed process 4811 (cockroach) total-vm:29932604kB, anon-rss:15233424kB, file-rss:0kB
```

**Comment by awoods187** [comment]
[memprof.fraction_system_memory.000000014484381696_2019-02-20T22_08_02.294.zip](https://github.com/cockroachdb/cockroach/files/2886799/memprof.fraction_system_memory.000000014484381696_2019-02-20T22_08_02.294.zip)

**Comment by jordanlewis** [comment]
@awoods187 could you please retry this at your leisure?

**Comment by awoods187** [comment]
I'm blocked on https://github.com/cockroachdb/cockroach/issues/41009. I've hit that issue twice in trying to repro this issue.

**Comment by awoods187** [comment]
So I was able to get a cluster similar to this one to import data by adjusting the max sql memory at start by running:
```roachprod start $CLUSTER:1-30 --racks=10 --args "--max-sql-memory=.20";```

I attempted to repro this error with _less_ memory available. It took a long time to progress but eventually started to work:
```
(base) andrewwoods@Andrews-MBP-2:~$ roachprod run $CLUSTER:31 "./workload run tpcc --warehouses=10000 --partitions=10 --duration=1s --split --scatter {pgurl:1}"
Initializing 20000 connections...
Initializing 100000 workers and preparing statements...
```
Only to ultimately crash node 1. Note, I also had trouble sshing into node 1 as `roachprod ssh $CLUSTER:1` hangs in the CLI (no problem on node 2) eventually returning: 
```
(base) andrewwoods@Andrews-MBP-2:~$ roachprod ssh $CLUSTER:1
Warning: Permanently added '3.19.222.31' (ECDSA) to the list of known hosts.
Connection closed by 3.19.222.31 port 22
```
Similarly, get logs failed:
```
(base) andrewwoods@Andrews-MBP-2:~$ roachprod get $CLUSTER:1 logs
andy-30node: getting (scp) logs logs
   1: ~ scp -r -C -o StrictHostKeyChecking=no -i /Users/andrewwoods/.ssh/id_rsa -i /Users/andrewwoods/.ssh/google_compute_engine ubuntu@3.19.222.31:logs logs
Warning: Permanently added '3.19.222.31' (ECDSA) to the list of known hosts.
Connection closed by 3.19.222.31 port 22
: exit status 1
I190927 20:17:46.601178 1 cluster_synced.go:1410  get logs failed
```

**Comment by awoods187** [comment]
The underlying bug for restoring this data has been addressed. As such, I went ahead attempted to repro this again. 

I had the exact same experience as the previous comment. Node 1 fails and SSHing hangs for what I assume is an OOM but I can't prove it. Cluster is `andy-3node` (i mistyped the name but its actually 30 nodes)

**Comment by awoods187** [comment]
```
(base) andrewwoods@Andrews-MacBook-Pro-2:~/scripts$ roachprod run $CLUSTER:31 "./workload run tpcc --warehouses=10000 --partitions=10 --duration=1s --split --scatter {pgurl:1}"
Initializing 20000 connections...
Initializing 100000 workers and preparing statements...
Error: preparing
		SELECT c_balance, c_first, c_middle, c_last
		FROM customer
		WHERE c_w_id = $1 AND c_d_id = $2 AND c_id = $3: ERROR: root: memory budget exceeded: 10240 bytes requested, 4055674880 currently allocated, 4055681024 bytes in budget (SQLSTATE 53200)
Error:  exit status 1
```

**Comment by awoods187** [comment]
Here is the heap profile [heap profiles.zip](https://github.com/cockroachdb/cockroach/files/3714060/heap.profiles.zip)

**Comment by RaduBerinde** [comment]
In general, a big part of the budget is consumed by the prepared statements, which have to be prepared on each connection separately. Thanks to plan caching, most of these should actually be sharing the same memo, but the accounting code is pessimistic and doesn't take that into account.

**Comment by RaduBerinde** [comment]
Can you try skipping that step, or running that step with the additional `--conns 1000` flag?
```
roachprod run $CLUSTER:31 "./workload run tpcc --warehouses=10000 --partitions=10 --duration=1s --conns 1000 --split --scatter {pgurl:1}"
```

CC @nvanbenschoten

**Comment by RaduBerinde** [comment]
Talked to Nathan, the roachtests use a different variant for that step, one that would cut down the connections to 10k:
```
roachprod run $CLUSTER:16 "./workload run tpcc --warehouses=10000 --wait=false --workers=10000 --max-rate=5000 --partitions=5 --duration=1s --split --scatter {pgurl:1}"
```

I updated the instructions in the "Manually Run TPC-C" wiki page.

**Comment by nvanbenschoten** [comment]
Just double checked and the roachtests actually run with this small amount of load for a while as a way to let the system balance replicas and leases based off load. If you don't want to do that (`--duration=1s`) then you might as well drop `--workers=10000` down to `--workers=1`.

**Comment by awoods187** [comment]
I restarted the node and then ran the new version with fewer workers:
```SQL
(base) andrewwoods@Andrews-MacBook-Pro-2:~$ roachprod run $CLUSTER:31 "./workload run tpcc --warehouses=10000 --wait=false --workers=10000 --max-rate=5000 --partitions=10 --duration=1s --split --scatter {pgurl:1}"
Initializing 10000 connections...
Initializing 10000 workers and preparing statements...
_elapsed___errors__ops/sec(inst)___ops/sec(cum)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)
    1.0s        0            0.0            0.0      0.0      0.0      0.0      0.0 delivery
    1.0s        0            0.0            0.0      0.0      0.0      0.0      0.0 newOrder
    1.0s        0            0.0            1.0    453.0    453.0    453.0    453.0 orderStatus
    1.0s        0            0.0            0.0      0.0      0.0      0.0      0.0 payment
    1.0s        0            0.0            0.0      0.0      0.0      0.0      0.0 stockLevel

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
    1.0s        0              1            1.0    444.6    453.0    453.0    453.0    453.0  orderStatus

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__result
    1.0s        0              1            1.0    444.6    453.0    453.0    453.0    453.0
Audit check 9.2.1.7: SKIP: not enough delivery transactions to be statistically significant
Audit check 9.2.2.5.1: SKIP: not enough orders to be statistically significant
Audit check 9.2.2.5.2: SKIP: not enough orders to be statistically significant
Audit check 9.2.2.5.3: SKIP: not enough orders to be statistically significant
Audit check 9.2.2.5.4: SKIP: not enough payments to be statistically significant
Audit check 9.2.2.5.5: SKIP: not enough payments to be statistically significant
Audit check 9.2.2.5.6: SKIP: not enough order status transactions to be statistically significant

_elapsed_______tpmC____efc__avg(ms)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
    1.0s        0.0   0.0%      0.0      0.0      0.0      0.0      0.0      0.0
```

Everything passed as expected. I'm going to close this issue as basically user error in applying how we designed our previous performance testing instructions.
