### ISSUE TITLE
Low performance for TPC-C 10k on a 15 node 16 cpu cluster

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#35104]
**Describe the problem**

Low performance for TPC-C 10k on a 15 node 16 cpu cluster

`roachprod run $CLUSTER:16 "./workload run tpcc --ramp=10m --warehouses=10000 --active-warehouses=10000 --partitions=5 --duration=15m --split --scatter {pgurl:1-15}"` Run 1
```elapsed_______tpmC____efc__avg(ms)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
  900.0s   100603.2  78.2%    300.1    285.2    503.3    604.0    906.0  13958.6```
then right after run 2
```_elapsed_______tpmC____efc__avg(ms)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
  900.0s    74808.6  58.2%    243.4    226.5    436.2    520.1    738.2   7784.6```

We can usually easily hit max performance on this topology. 

**To Reproduce**
https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/59146477/Manually+Run+TPC-C+on+GCP+and+AWS

**Environment:**
v2.2.0-alpha.20190211-254-g1387b4f

**Comment by awoods187** [comment]
Same cluster as https://github.com/cockroachdb/cockroach/issues/35102

**Comment by ajwerner** [comment]
There is a debug zip is `gs://cockroach-internal/debug_for_35104.zip`

The bizarre thing here is that traffic is very poorly spread out over the nodes as can be seen from the hardware and request data in the attached screenshots. 

![screenshot_2019-02-20 queues dashboard cockroach console 1](https://user-images.githubusercontent.com/1839234/53131254-3aa86300-353a-11e9-8584-43f11a3bf32c.png)
![screenshot_2019-02-20 replication dashboard cockroach console 1](https://user-images.githubusercontent.com/1839234/53131255-3aa86300-353a-11e9-970b-a235f845421f.png)
![screenshot_2019-02-20 replication dashboard cockroach console](https://user-images.githubusercontent.com/1839234/53131256-3aa86300-353a-11e9-8427-e53da114e1ce.png)
![screenshot_2019-02-20 hardware dashboard cockroach console 1](https://user-images.githubusercontent.com/1839234/53131257-3aa86300-353a-11e9-8d7b-cfe92f3f18c6.png)
![screenshot_2019-02-20 hardware dashboard cockroach console](https://user-images.githubusercontent.com/1839234/53131258-3aa86300-353a-11e9-83bf-2224ed77f417.png)
![screenshot_2019-02-20 queues dashboard cockroach console](https://user-images.githubusercontent.com/1839234/53131259-3aa86300-353a-11e9-8026-2cf1c7ca38e2.png)

**Comment by ajwerner** [comment]
From goroutine traces from stalled nodes it appears that we're blocking in grpc. I'm attaching a goroutine dump file. Some highlights:

```

goroutine 8499850 [select, 4 minutes]:
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*Stream).waitOnHeader(0xc00d608800, 0x1, 0xc0316413e0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/transport.go:240 +0xcf
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport.(*Stream).RecvCompress(0xc00d608800, 0xc0316413e0, 0xc00b9fa308)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/transport/transport.go:251 +0x2b
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*csAttempt).recvMsg(0xc04c5ca8f0, 0x3079360, 0xc023e661c0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/stream.go:528 +0x627
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*clientStream).RecvMsg(0xc01a1eea80, 0x3079360, 0xc023e661c0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/stream.go:408 +0x43
...
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).commitSQLTransaction(0xc026efe000, 0x3914680, 0xc08aa543f0, 0x3919e00, 0xc025c73120, 0xc024fe7c05, 0x23, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:616 +0xa2
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc026efe000, 0x3914680, 0xc08aa543f0, 0x3919e00, 0xc025c73120, 0xc024fe7c05, 0x23, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:234 +0x2829
```

Seems like we're getting stuck receiving from somewhere. Now to figure out if anything is going on on the other side. 
[goroutine_stalled_client.txt](https://github.com/cockroachdb/cockroach/files/2903215/goroutine_stalled_client.txt)

**Comment by ajwerner** [comment]
We've found that it's stalled resolving intents blocked waiting on responses. I'm debugging.
