### ISSUE TITLE
sql: remove remaining uses of cockroach/sql/driver

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#3511]
Now that we support placeholders in the pgwire protocol, we should be able to remove the few remaining uses of `sql/driver` from tests and benchmarks (other than the `sql/driver` tests): `git grep 'sql.Open("cockroach"'`. Should also do this for the examples in [examples-go](https://github.com/cockroachdb/examples-go).

**Comment by mjibson** [comment]
I don't understand what placeholders have to do with `sql/driver`. I'm looking at `sql.Open` in `cli/sql_util_test.go` and am similarly unsure what that has to do with this. The driver package is not imported in that file. Why does this package only need to be removed from tests and benchmarks? Why can it stay in other packages?

**Comment by petermattis** [comment]
The call to `sql.Open` in `cli/sql_util_test.go` is using the http protocol (implemented by `cockroachdb/cockroach/sql/driver`. I'm proposing that you replace that usage with the pgwire protocol implementation everywhere except for the tests in `sql/driver` which are testing the placeholder support in our http protocol.

Essentially, grep for `github.com/cockroachdb/cockroach/sql/driver` and replace any occurrences with usage of pgwire instead (which will involve change calls to `sql.Open` to use the `"postgres"` driver).

**Comment by tamird** [comment]
This will also require adding a "pgaddr" flag.

**Comment by petermattis** [comment]
Yes, and we need to figure out the default `pgaddr` port to listen on. Listening on 5432 (the actual postgres port) feels wrong. How about 15432 or 25432?

**Comment by mjibson** [comment]
I used 16379 for the redis binding (redis default is 6379), so I'm in favor of 15432.

**Comment by nvanbenschoten** [comment]
To keep track of things, removing [this usage](https://github.com/cockroachdb/cockroach/blob/master/sql/main_test.go#L99) of the cockroach sql/driver is being blocked by the issue Marc is seeing [here](https://github.com/cockroachdb/cockroach/issues/3819#issuecomment-171706072).

**Comment by petermattis** [comment]
After #4081, this will be done. The only remaining usage of `sql/driver` is from the `sql/driver` tests. We should refactor the `sql/driver` package out of existence and look into simplifying the execution of SQL queries over HTTP as used by the Admin UI.

**Comment by petermattis** [comment]
@mjibson Per https://github.com/cockroachdb/examples-go/pull/29 I noticed that the examples in `examples-go` are still using `sql/driver`. It should be straightforward to switch these over to use `lib/pq`.

**Comment by mberhault** [comment]
I'm already working on `examples-go/filesystem` along with other fixes and improvements for it.
