### ISSUE TITLE
opt: json queries with ->> can't use inverted index

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#35117]
The JSON operator `->>` selects an object field as text from a JSON payload. An expression `json->'foo' = 'bar'` is identical to the expression `json @> '{"foo": "bar"}'`, for example.

The optimizer should be able to transform queries of that form into contains queries, so that inverted indexes can be used. This was requested in a forum post: https://forum.cockroachlabs.com/t/question-on-json-index/2443

Here's an example of how it currently works:

```
root@127.0.0.1:56772/defaultdb> explain select * from a where j @> '{"foo":"bar"}';
     tree    | field |             description
+------------+-------+-------------------------------------+
  index-join |       |
   │         | table | a@primary
   └── scan  |       |
             | table | a@a_j_idx
             | spans | /"foo"/"bar"-/"foo"/"bar"/PrefixEnd
(5 rows)

Time: 664µs

root@127.0.0.1:56772/defaultdb> explain select * from a where j ->> 'foo' = 'bar';
  tree | field  |     description
+------+--------+---------------------+
  scan |        |
       | table  | a@primary
       | spans  | ALL
       | filter | (j->>'foo') = 'bar'
(4 rows)
```

The second explain should be the same as the first, ideally.

**Comment by andy-kimball** [comment]
Justin, can you comment on this?

**Comment by justinj** [comment]
We should definitely be able to do this. It's not too much work but we'd have to be careful to think through if there are any gotchas with the transformation. In the meantime, the user should be able to work around this by using `->` instead of `->>`.

**Comment by justinj** [comment]
One gotcha in particular I can think of is that
`x->>y = 'true'` will require scanning two separate spans, one for where `y` is JSON `true` and one where it's the json string `"true"`. And similar for numbers and other non-string values.

**Comment by jordanlewis** [comment]
I think you're just proactively noting the special cases, but in case there was doubt, we do things like this already for some contains queries that might need to emit multiple spans - so it's not unprecedented.

**Comment by justinj** [comment]
Right, I'm just noting that it's not valid to unconditionally transform `x->>y = s` to `x->y = s`. I think we would want something like:

* For values that are not parseable as JSON: `x->>y = 'foo'` => `x->y = '"foo"'::JSON`
* For values that *are* parseable as JSON: `x->>y = 'true'` => `x->y = '"true"'::JSON OR x->y = 'true'::JSON`

And maybe add some additional rules to make the latter case efficient.

It might also be important to note that `'{"a": null}'->>'a'` is `NULL` and not `'null'::JSON`.

**Comment by gomathi** [comment]
@justinj I have one question

root@:26257/umc> explain select movie->'id', movie->'matched_id' from movies where movie->'id' = movie->'matched_id';
    tree    | field  |                       description
+-----------+--------+----------------------------------------------------------+
  render    |        |
   └── scan |        |
            | table  | movies@primary
            | spans  | ALL
            | filter | (movie->'id') = (movie->'matched_id')
(5 rows)

Here, I wonder why index on movie->'id' and movie->'matched_id' are not being used? Is this expected? 

Also could you write some article on how the inverted index on jsonb is used in joins, and queries. That will be very helpful.

**Comment by gomathi** [comment]
@justinj I updated my previous comment.

**Comment by gomathi** [comment]
Also, if I manually create index on json columns in postgres using the following commands,

`
create index on movies((movie->'reference_id'));
create index on movies((movie->'matched_reference_id'));
`

and then if I run the same query as in my previous comment using postgres, then it automatically it uses index that I created previously as shown following

`umc=# explain select f.movie->'reference_id' rid, s.movie->'reference_id' rid2 from movies f,movies s where f.movie->'reference_id' < s.movie->'matched_reference_id';
                                                  QUERY PLAN
--------------------------------------------------------------------------------------------------------------
 Nested Loop  (cost=0.56..31834999353.74 rows=979484737621 width=64)
   ->  Seq Scan on movies f  (cost=0.00..163857.92 rows=1714192 width=624)
   ->  Index Scan using movies_expr_idx9 on itms7_movies s  (cost=0.56..10000.38 rows=571397 width=624)
         Index Cond: ((f.movie -> 'reference_id'::text) < (movie -> 'matched_reference_id'::text))
`

So using inverted index in cockroachdb is not helpful in joins. If I am wrong, please correct me.

**Comment by justinj** [comment]
@gomathi this is a great observation! It seems what you want is the ability for us to do (what we call) a lookup join into an inverted index. We don't support that today, but I don't think there's any reason we couldn't. I've opened #35137 to track this.

**Comment by tim-o** [comment]
Zendesk ticket #[3116](https://cockroachdb.zendesk.com/agent/tickets/3116) has been linked to this issue.

**Comment by justinj** [comment]
Personally, I think this feature is a footgun and should be a wontfix. It's easy to write parameterized queries which are fast for some values and require a full table scan for others. Consider
```
SELECT x WHERE x->>'foo' = $1
```
When `$1` is `'bar'` this query can be fast, and could lead someone to believe it will *always* be fast. But if `$1` is `'{}'` it requires a full table scan. Contrasted to our existing version of this functionality, in any place where a placeholder could reasonably live, no value for that placeholder can change the performance characteristics of the query in this way.

In addition, any realistic version of a query that could be written with `->>` can also be easily written with `->`.

**Comment by justinj** [comment]
I note that Postgres also doesn't implement this:
```
d=# explain select 1 from foo where bar @> '{"a": "b"}';
                           QUERY PLAN
-----------------------------------------------------------------
 Bitmap Heap Scan on foo  (cost=12.01..16.02 rows=1 width=4)
   Recheck Cond: (bar @> '{"a": "b"}'::jsonb)
   ->  Bitmap Index Scan on x  (cost=0.00..12.01 rows=1 width=0)
         Index Cond: (bar @> '{"a": "b"}'::jsonb)
(4 rows)

d=# explain select 1 from foo where bar->>'a' = 'b';
                     QUERY PLAN
----------------------------------------------------
 Seq Scan on foo  (cost=0.00..30.40 rows=7 width=4)
   Filter: ((bar ->> 'a'::text) = 'b'::text)
(2 rows)
```

**Comment by jordanlewis** [comment]
Yeah, I'm fine with closing this as `wontfix`.
