### ISSUE TITLE
sql: using a subselect to provide the criteria against a primary key for an update statement results in a full table scan.

### ISSUE THREAD

**Issue by rkruze** [cockroachdb/cockroach#35110]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

When using a subselect an in update statement which is used as criteria against the primary key, a full table scan is performed instead of using the primary key to look up the value. 

**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. Setup a cockroach cluster. 
2. Create the following table: 

```
CREATE TABLE test (
	id UUID NOT NULL,
	v1 INT8 NOT NULL,
        v2 STRING,
	CONSTRAINT "primary" PRIMARY KEY (id ASC),
	INDEX idx_v1 (v1 DESC)
);
```

Run the following: 

`explain UPDATE test SET v2 = 'value' WHERE id = (SELECT id FROM test ORDER BY v1 LIMIT 1)`

This returns the following: 

```     
       tree           |    field     |                description
+--------------------------+--------------+-------------------------------------------+
  root                     |              |
   ├── count               |              |
   │    └── update         |              |
   │         │             | table        | test
   │         │             | set          | v2
   │         │             | strategy     | updater
   │         └── render    |              |
   │              └── scan |              |
   │                       | table        | test@primary
   │                       | spans        | ALL
   │                       | filter       | id = @S1
   └── subquery            |              |
        │                  | id           | @S1
        │                  | original sql | (SELECT id FROM test ORDER BY v1 LIMIT 1)
        │                  | exec mode    | one row
        └── render         |              |
             └── revscan   |              |
                           | table        | test@idx_v1
                           | spans        | ALL
                           | limit        | 
```

The expected behavior would be that the primary key would be used for the lookup versus a full table scan. 

**Expected behavior**
A lookup using the primary key should be done instead of a full table scan. 

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version [e.g. 2.0.x]: v 2.1.5 and v2.2.0-alpha.20190211
 - Server OS: [e.g. Linux/Distrib] Linux
 - Client app [e.g. `cockroach sql`, JDBC, ...] `cockroach sql`

**Comment by andy-kimball** [comment]
@RaduBerinde, @justinj, the only reason we don't use a lookup join for this query is because we currently don't hoist subqueries that don't have outer columns. To illustrate this, I made the following hacks:
```
--- a/pkg/sql/opt/norm/decorrelate.go
+++ b/pkg/sql/opt/norm/decorrelate.go
@@ -52,7 +52,7 @@ func (c *CustomFuncs) HasHoistableSubquery(scalar opt.ScalarExpr) bool {
 func (c *CustomFuncs) deriveHasHoistableSubquery(scalar opt.ScalarExpr) bool {
        switch t := scalar.(type) {
        case *memo.SubqueryExpr:
-               return !t.Input.Relational().OuterCols.Empty()
+               return true //!t.Input.Relational().OuterCols.Empty()

        case *memo.ExistsExpr:
                return !t.Input.Relational().OuterCols.Empty()
@@ -776,9 +776,9 @@ func (r *subqueryHoister) hoistAll(scalar opt.ScalarExpr) opt.ScalarExpr {
        switch scalar.Op() {
        case opt.SubqueryOp, opt.ExistsOp, opt.AnyOp, opt.ArrayFlattenOp:
                subquery := scalar.Child(0).(memo.RelExpr)
-               if subquery.Relational().OuterCols.Empty() {
-                       break
-               }
+               //if subquery.Relational().OuterCols.Empty() {
+               //      break
+               //}
```
And now show this plan:
```
root@:26257/defaultdb> explain (opt) UPDATE test SET v2 = 'value' WHERE id = (SELECT id FROM test ORDER BY v1 LIMIT 1);
                 text
+-------------------------------------+
  update test
   └── project
        ├── inner-join (lookup test)
        │    ├── scan test@idx_v1,rev
        │    │    └── limit: 1(rev)
        │    └── filters (true)
        └── projections
             └── const: 'value'
```
The tricky part is deciding when to hoist uncorrelated subqueries like this. I'm not sure that it's always the best thing to do. I seem to remember that certain TPCH queries were slower, for example, if we always hoisted. However, that was a while ago, and a lot has changed, so it's worth a new investigation. At the time, my highest priority was to not regress performance from 2.0, so I was conservative with optimization decisions like this.

**Comment by RaduBerinde** [comment]
I think we should be able to come up with a list of common cases where it's always a good idea to hoist - probably anything that results in a join with eq condition is safe to do. Definitely worth investigating in 19.2 timeframe.

**Comment by andy-kimball** [comment]
Or possible a list of cases where it's *not* a good idea to host. I bet that in the majority of cases it's a good thing to do.

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[3522](https://cockroachdb.zendesk.com/agent/tickets/3522) has been linked to this issue.

**Comment by knz** [comment]
we've fixed this

**Comment by RaduBerinde** [comment]
I don't think we did.

**Comment by RaduBerinde** [comment]
But it is a dup of #7042, closing again.
