### ISSUE TITLE
Drop database Failed

### ISSUE THREAD

**Issue by drewdeally** [cockroachdb/cockroach#35138]
Working with ISV and they will upload the debug logs

Server version: CockroachDB CCL v2.1.4 (x86_64-unknown-linux-gnu, built 2019/01/16 16:05:40, go1.10.7) (same version as client)

root@:26257/defaultdb> DROP DATABASE TESTREPUSR CASCADE;
pq: database "testrepusr" does not exist

root@:26257/defaultdb> SHOW DATABASES;
  database_name
+---------------+
  NEWTESTREPUSR
  TESTREPUSR
  TESTREPUSR2
  TESTREPUSR3
  TESTREPUSR4
  TESTREPUSR5
  defaultdb
  io_blitzz
  postgres
  system
(10 rows)

Time: 1.23196ms

It did not drop the database.

**Comment by vjnew** [comment]
I figured out the solution. Now i am able to drop the db. Thanks.

**Comment by nvanbenschoten** [comment]
@vjnew what was the solution you found?

**Comment by vjnew** [comment]
Reframe the drop database command with proper formatting and quotation
marks.

**Comment by nvanbenschoten** [comment]
Got it, thanks.
