### ISSUE TITLE
opt: support lookup joins against inverted indexes

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#35137]
Today we only lookup join against "traditional" indexes, however, @gomathi points out that we could, theoretically, also plan them against inverted indexes in certain cases.
```
root@:26257/umc> explain select f.movie->'reference_id' rid, s.movie->'reference_id' rid2 from movies f, movies s where f.movie->'reference_id' = s.movie->'matched_reference_id';
         tree         |  field   |      description
+---------------------+----------+-----------------------+
  render              |          |
   └── join           |          |
        │             | type     | inner
        │             | equality | (column5) = (column6)
        ├── render    |          |
        │    └── scan |          |
        │             | table    | movies@primary
        │             | spans    | ALL
        └── render    |          |
             └── scan |          |
                      | table    | movies@primary
                      | spans    | ALL
(12 rows)

Time: 1.870431ms
```
This query could do an inverted index scan for one of the tables, and a series of inverted index lookups for the other. I suspect this would require execution support @jordanlewis.

**Comment by mgartner** [comment]
We've implement "inverted joins" which are essentially lookup joins on inverted indexes. Inverted joins are planned on `GEOMETRY` and `GEOGRAPHY` inverted indexes as of 20.2.0. Support for `JSON` and `ARRAY` inverted indexes will be released in version 21.1.0.
