### ISSUE TITLE
Enable computed columns when importing CSV

### ISSUE THREAD

**Issue by mindscratch** [cockroachdb/cockroach#35149]
**Is your feature request related to a problem? Please describe.**
I have a bunch of CSV files that I need to import. The table that I need to create should have a computed column, based on one of the columns in the CSV. Specifically, the CSV has a field representing a created-at date. I need a computed column named "week", that contains a date truncated to the week based on created-at.

**Describe the solution you'd like**
I'd like a computed column to be generated when importing data from CSV.

**Describe alternatives you've considered**
Import data then update table to add the computed column.

**Additional context**

**Comment by rolandcrosby** [comment]
IMPORT INTO should allow definition of computed columns and fix this.
