### ISSUE TITLE
scrub: could not find MergeJoinerSpec in plan

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#35160]
Discovered when I added the following index to `TestRaceWithBackfill`: `CREATE INDEX bar ON t.test(k) STORING (v)`, in #35157 (see the TODO in that one).

As best as I can tell, this isn't an actual error found in the data but rather a violation of the assumption that the query plan will always include a MergeJoiner. 

I suspect this would reproduce outside the `TestRaceWithBackfill` test.

**Comment by lucy-zhang** [comment]
Yeah, I think that's right. The SCRUB fk validation query actually needs to be entirely changed, because it doesn't match the new MATCH FULL/PARTIAL semantics. I'd like to replace it with the new  implementation that's used for VALIDATE CONSTRAINT if possible.
