### ISSUE TITLE
Should test case TestTxnDBLostUpdateAnomaly be included?

### ISSUE THREAD

**Issue by yaojingguo** [cockroachdb/cockroach#3517]
In `kv/txn_correctness_test.go`, `TestTxnDBLostUpdateAnomaly` is skipped by `t.Skip("TODO(spencerkimball): https://github.com/cockroachdb/cockroach/issues/3123")`. But https://github.com/cockroachdb/cockroach/issues/3123 is fixed now. Should TestTxnDBLostUpdateAnomaly be included?

I have run `make test PKG=./kv TESTS='TestTxnDBLostUpdateAnomaly'` many times, it always succeeded.

**Comment by tschottdorf** [comment]
I actually closed the issue under the assumption that the test wasn't skipped. I think reenabling it would be good so we can see whether it's still flaky.
