### ISSUE TITLE
sql,opt: implement Max1RowAgg

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#35181]
The optimizer should be able to decorrelate more correlated subqueries with a new aggregate function, `Max1RowAgg`, that functions the same as `AnyNotNullAgg`, except it returns a runtime error if it sees more than 1 row per group.

This issue tracks adding such an aggregate function to the system.

**Comment by andy-kimball** [comment]
This should be quite straightforward. It will need an `ErrorText` string so that we can specify the error that's raised if the input group has more than 1 row.

**Comment by andy-kimball** [comment]
Though it might be challenging to test in isolation, as it's an internal-only aggregate function.

**Comment by Anthuang** [comment]
Do you mind if I take this?

By `ErrorText` do you mean it should be passed in as an argument? Also, seeing how `any_not_null` is similar, could you point me to how that aggregate is tested?

Thank you!

**Comment by andy-kimball** [comment]
Thanks for your interest. I turns out that this work was actually completed using a slightly different, but related, mechanism, here: https://github.com/cockroachdb/cockroach/pull/48006. So I'll go ahead and close this issue.

**Comment by Anthuang** [comment]
Got it, thanks for letting me know!
