### ISSUE TITLE
changefeedccl: suppress secret keys in SHOW JOBS/web UI jobs table

### ISSUE THREAD

**Issue by rolandcrosby** [cockroachdb/cockroach#35190]
Currently, CREATE CHANGEFEED writes the full sink URL to the jobs table. When using the cloud storage sink, this can lead to credential leaks, because the sink URL can contain access keys/secrets. Other long-running jobs like BACKUP and RESTORE appear to suppress these parameters before writing to the jobs table. CREATE CHANGEFEED should use the same or similar logic to avoid leaking secrets.

![changefeed_ui_jobs](https://user-images.githubusercontent.com/60245/53371090-57b7aa00-391d-11e9-80a8-dafd2b9027ff.png)

**Comment by danhhz** [comment]
Closed by #35257
