### ISSUE TITLE
rocksdb assertion failure

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#352]
RocksDB is compiled with assertions off (`-DNDEBUG`). If you compile with assertions on then one triggers in `column_family.cc:325: is_last_reference` when running the `TestSnapshotMethods` test in storage/engine. Bug in our test? Bug in rocksdb?

**Comment by tschottdorf** [comment]
I think I may have just run into this rather randomly, at least I didn't add -DNDEBUG:

https://circleci.com/gh/tschottdorf/cockroach/349

**Comment by tschottdorf** [comment]
Note all the "[ERROR] Error when reading /tmp/data_1425125833457636721 dir", are those normal?

**Comment by petermattis** [comment]
I don't recall seeing those errors, but you also have the assertion failure and the same test is failing (`TestSnapshotMethods`):

```
engine.test: db/column_family.cc:334: rocksdb::ColumnFamilyData::~ColumnFamilyData(): Assertion `is_last_reference' failed
```

I'll look into this more on Monday. How did rocksdb get built without `NDEBUG` being set?
