### ISSUE TITLE
changefeedccl: add CDC-related feature counters

### ISSUE THREAD

**Issue by rolandcrosby** [cockroachdb/cockroach#35222]
Upon changefeed creation, we should capture the following metrics:
- **sink type** - e.g. changefeed.create.sink.kafka, changefeed.create.sink.experimental-s3, changefeed.create.sink.experimental-http
  - should also include an item for counting core changefeeds, even though they're technically "sinkless"
- **table count** - how many tables is the changefeed set up to consume?
- **format** - e.g. changefeed.create.format.avro, changefeed.create.format.json

It would be nice if we could also count failures, pause/resume, and cancellations. (This would actually be pretty handy to have across all job types, so I'm ok holding off on these metrics until we revisit the job management system in more detail in 19.2.)

**Comment by danhhz** [comment]
Closed by #35257 (didn't do the jobs counters)
