### ISSUE TITLE
UNION on json columns doesn't work

### ISSUE THREAD

**Issue by gabcbrown** [cockroachdb/cockroach#35260]
**Describe the problem**
Came across this while trying to union two selects that contained a json column, and narrowed it down to the json column. The following example fails:

**To Reproduce**
```
> CREATE TABLE t1 (j JSON);
> CREATE TABLE t2 (j JSON);
> INSERT INTO t1 VALUES ('{"a": "b"}');
> INSERT INTO t2 VALUES ('{"c": "d"}');
> (SELECT j FROM t1) UNION (SELECT j FROM t2);
```

Output is `pq: unable to encode table key: *tree.DJSON`

**Expected behavior**
If this is related to https://github.com/cockroachdb/cockroach/issues/24436 (not key-encoding JSON values) then a clearer error message.  Otherwise I would expect:
```
       j         
+------------+
  {"a": "b"}
  {"c": "d"}  
(2 rows)
```

**Environment:**
 - CockroachDB version: 2.1.4
 - Server OS: MacOS High Sierra
 - Client app:`cockroach sql`

**Comment by jordanlewis** [comment]
Thanks for the report - it's indeed related to / the same as #24436.

**Comment by knz** [comment]
I have added telemetry links inside CockroachDB to the underlying/overarching issue #35706.

**Comment by tim-o** [comment]
Zendesk ticket #[3214](https://cockroachdb.zendesk.com/agent/tickets/3214) has been linked to this issue.

**Comment by jordanlewis** [comment]
Closing as duplicate of #35706.
