### ISSUE TITLE
Snapshot Isolation does not support REPEATABLE READ

### ISSUE THREAD

**Issue by yaojingguo** [cockroachdb/cockroach#3527]
In [sql/parser/sql.y](https://github.com/cockroachdb/cockroach/blob/master/sql/parser/sql.y), there is the following text:

```
| REPEATABLE READ
  {
    // Mapped to the closest supported isolation level.
    $$ = SnapshotIsolation
  }
```

The text means that Snapshot Isolation supports REPEATABLE READ. But it is not true. In [1], there is the following text:

> Remark 9. REPEATABLE READ »« Snapshot Isolation.

The remark means that Snapshot Isolation and  REPEATABLE READ are incomparable. Since CockroachDB only supports Snapshot Isolation and SERIALIZABLE, SERIALIZABLE is needed to support REPEATABLE READ.

[1]: http://research.microsoft.com/pubs/69541/tr-95-51.pdf "A Critique of ANSI SQL Isolation Levels"

**Comment by tschottdorf** [comment]
That's correct, thanks. Wanna send a PR?

**Comment by yaojingguo** [comment]
Yes, I will send a PR soon.
