### ISSUE TITLE
EAR: add feature counter for encryption at rest

### ISSUE THREAD

**Issue by rolandcrosby** [cockroachdb/cockroach#35286]
We don't currently have any telemetry for encryption at rest. Before the release of 19.1, we should add a feature counter to our storage engine to indicate whether encryption is enabled on each store or not. It doesn't look like there are any existing feature counters in this part of the codebase. This is probably just a check that we should run on each store at node startup; we can aggregate the results by cluster on the server side after collecting the individual encrypted/not-encrypted counts.

**Comment by mberhault** [comment]
CC: @dt: do we have per-store telemetry somewhere/

**Comment by dt** [comment]
Yes, there is per-store telemetry:
There's a `StoreReport` with many fields about the store: https://github.com/cockroachdb/cockroach/blob/master/pkg/server/diagnosticspb/diagnostics.proto#L54

To add to that, you'd update the proto and then the report collector to populate the proto field, then you'd also need to update the telemetry collector service to read the new proto field, store its value somewhere, etc.

A slightly cheaper/faster option might be to just add a feature counter in store creation, eg. 
```
if cfg.Encrypted {
  telemetry.Count("storage.encryption.enabled")
} else  {
  telemetry.Count("storage.encryption.disabled")
}
```

Calls to these are counted and those counts are reported automatically in existing reporting, without any other code changes in either cockroach or the telemetry collection service.

Obviously this telemetry isn't quite as detailed as the bespoke store report --on a multi-store node, you wouldn't know _which_ store  was encrypted and which one wasn't -- but it is quick and easy, so maybe that tradeoff makes sense?

**Comment by mberhault** [comment]
Hum. I'm not sure feature count will work. From what I understand, the counter gets reset every time we send updates. This means that the count will be 1 for each store (when the store is initialized) at the first update, then be at 0 (or not reported) for further updates. Various nodes restarting at various times will cause the cluster total to fluctuate wildly. Am I understanding this correctly?

The other issue is that all encryption fields are CCL only with odd hooks to go in and out of OSS code. The easiest would be to set an opaque string to describe the encryption setting (ie: the cipher type and size, of which we only have 4 for now) and report that.

**Comment by mberhault** [comment]
Although now I see that we don't report features with zero count. Does that make init-time `telemetry.Count` a supported use case?

**Comment by dt** [comment]
yeah, we don't report 0's.

That's why I was saying to inc one-or-the-other: we'll get exactly one of them on each start, so'll know what % of stores are using it.

That said, if you just want to add it to the `StoreInfo` in diagnostics.proto and then update the func that generates a store report in `updates.go` that's fine with me too.

**Comment by mberhault** [comment]
I think the `StoreInfo` might be better since I'll likely always report the encryption state (it'll just be `plaintext` for most) so we can keep track of reverts, partial rollouts, etc...

**Comment by mberhault** [comment]
@rolandcrosby: the linked PR adds a simple enum to the `StoreInfo` (per store statistics sent to telemetry). On the receiving end, I can turn this into a text column in the stores table. The value will be one of `Plaintext | AES128_CTR | AES192_CTR | AES256_CTR`.
