### ISSUE TITLE
storage: contention queue does not respect priority for read-only, high-priority txns

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#35288]
@danhhz noticed that he was seeing deadlocks in his jepsen-style CDC test. Part of the test performed high-priority scans to push transaction timestamps forward.

It turns out that the `contentionQueue` can prevent these pushes from succeeding even when they should. This is because only read-write transactions will perform [deadlock detection](https://github.com/cockroachdb/cockroach/blob/master/pkg/storage/intentresolver/contention_queue.go#L207) while in the queue. The deadlock detection is what we need for a high-priority transaction to succeed at its push. Since the scan was read-only, it did not enable deadlock detection and never issued a `PushTxnRequest`, which would have seen `ShouldPushImmediately = true`.

The following patch fixed the test, but it's not clear that it's the right solution. Should we bother entering the `contentionQueue` as a high-priority transaction in the first place?

```
diff --git a/pkg/storage/intentresolver/contention_queue.go b/pkg/storage/intentresolver/contention_queue.go
index bab0d2754c..606fd17b14 100644
--- a/pkg/storage/intentresolver/contention_queue.go
+++ b/pkg/storage/intentresolver/contention_queue.go
@@ -48,7 +48,7 @@ func newPusher(txn *roachpb.Transaction) *pusher {
 }

 func (p *pusher) activeTxn() bool {
-       return p.txn != nil && p.txn.IsWriting()
+       return p.txn != nil && (p.txn.IsWriting() || p.txn.Priority == roachpb.MaxTxnPriority)
 }

 type contendedKey struct {
```

**Comment by nvanbenschoten** [comment]
Random note: we could see this same issue materialize as a rangefeed that is unable to push the timestamp of ongoing transactions. This is only possible if the rangefeed isn't the first actor to push an old transaction, so it ends up not being the front of the contention queue.

> Should we bother entering the `contentionQueue` as a high-priority transaction in the first place?

Probably not. In addition to what we see here, read-write transactions wouldn't have seen this issue but will be extra disruptive if they enter the `contentionQueue`, aborting every transaction ahead of them in line.

**Comment by tbg** [comment]
Just to clarify, if there isn't already a queue established for a key, will this still fail to push? In other words, is the strategy of using a high-priority scan to nuke any intents broken right now because instead of pushing the txn will just wait?

**Comment by nvanbenschoten** [comment]
> Just to clarify, if there isn't already a queue established for a key, will this still fail to push? In other words, is the strategy of using a high-priority scan to nuke any intents broken right now because instead of pushing the txn will just wait?

No, this will only fail if the high-priority scan gets stuck behind a non-high priority transaction in the contention queue.

This is similarly broken for regular priority scans getting stuck behind low priority transactions when trying to push a low-priority transaction, but that issue seems far less severe.

**Comment by nvanbenschoten** [comment]
We only use `MinTxnPriority` transactions in a single place: `Replica.maybeWatchForMerge`. This won't ever enter the `contentionQueue`, so we're safe from the previous hazard. Still, I think I'm just going to have min and max priority transactions avoid the `contentionQueue` and make a note that the queue is priority oblivious in-case we ever get back to a state where non-extreme priorities matter.
