### ISSUE TITLE
cli: revisit cli functionality (SQL-awareness?)

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#3529]
With the exception of the `sql` shell, the `cockroach` cli commands do not know about SQL structure. For example, `cockroach range ls` (list ranges) takes a start-key and a count to list ranges for. Constructing the start-key for an SQL table is left to the user and is not easy. We should enhance the various cli commands to know about SQL tables. We should also revisit the utility in exposing the KV commands via the cli (e.g. `kv {get,put,cput,inc,del,delrange,scan,revscan}`). If user data is all stored in SQL tables, it isn't particularly useful to expose the underlying KV data from the command line and it is dangerous to allow its mutation.

**Comment by tschottdorf** [comment]
Do we have a roadmap for what we want even want the `cli` to be in the future?

**Comment by petermattis** [comment]
No, we don't have such a roadmap. Seems like some of the functionality has been subsumed by the `sql` shell (access to user data) and some may be subsumed by the web dashboard. Let's discuss after the holiday break. This issue was intended as a reminder that the cli needs to be revisited. I've renamed the title to make that more explicit.

**Comment by tschottdorf** [comment]
Doesn't seem that the title actually changed.

**Comment by petermattis** [comment]
Grr, I swear github drops edits sometimes. Or perhaps I didn't save the edit.

**Comment by mberhault** [comment]
Some things should definitely be removed, some refactored.
Some random thoughts:
* configs (zones, permissions, eventually quotas, etc..) can be a bit annoying through sql. a cli interface can be convenient. Although if we make the interaction through sql easier (eg: db/table names instead of IDs, that would work too)
* KV should at the very least be hidden behind a flag. I think there is value to be able to poke at this without using a separate tool. I would avoid removing it entirely
* range commands should be sql aware instead (and match zone configs in presentation). There may still be value in having non-interpreted keys (maybe also hidden behind a flag).

Overall, I'd say let's keep the KV stuff, just put it in the background, it will most likely come in handy for debugging. The fact that they will require `node` certs should discourage people from using them, or from assuming there's a supported KV api.

**Comment by petermattis** [comment]
I can see value in the KV read commands (`get`, `scan` and `revscan`), but do we really want the mutating commands (`put`, `cput`, `del`, `delrange`)? Those seem exceptionally dangerous on SQL data.

**Comment by mberhault** [comment]
I agree, but experience tells me those are the kinds of tools you're really glad to have handy when you really really need them. I've had to manipulate metadata manually in the past, and doing quick-and-dirty is just a horrible idea in production.
However, I would also be happy with keeping them entirely separate from the standard binary. eg: some sort of debugging toolbox thing.
Anyway, my point is, we can hide them, or move them, but let's keep them somewhere within reach.

**Comment by petermattis** [comment]
How about we hide all of the KV commands under a `-X` flag similar to what was done with the hidden commands in `bt`? And make the mutating KV commands do nothing unless you pass `-yesireallymeanit`.

**Comment by mberhault** [comment]
I'm very happy with that. Anything at that level should be considered extremely dangerous, and documented as such. Not even showing them by default prevents people from just poking at things.

**Comment by JackKrupansky** [comment]
It would be good to have  a log file of commands executed by the cli, especially for the case where dangerous commands are executed. Helps to answer the proverbial support question of "What did you do? ... I didn't do anything!"

**Comment by petermattis** [comment]
We've talked about having all user actions (e.g. table creation, schema modification, permission changes, etc) placed into an audit log. This audit log should also include mutating KV operations performed by the CLI.

**Comment by petermattis** [comment]
The `zone` commands have been updated to be table aware. I think we can punt till after Beta on doing any work to the `range` and `kv` commands now that they have been moved under the `debug` command group. Speak up if you feel differently.

**Comment by tamird** [comment]
What work is being tracked in this issue? It's not clear from the discussion.

**Comment by petermattis** [comment]
The original motivation was to add SQL awareness (i.e. tables) to the `kv` and `range` commands. For example, it would be nice to be able to list the ranges for a table.

**Comment by petermattis** [comment]
@petermattis unassigning as I'm unlikely to address this soon.

**Comment by spencerkimball** [comment]
Addressed in #4812
