### ISSUE TITLE
ts: time series and metrics should use `-` as separator (not `.`)

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#3530]
@bdarnell [wrote](https://reviewable.io/reviews/cockroachdb/cockroach/3504#-K6ES-tJ55pf_71ytyCu):

> I suggest using - instead of . as the separator in metric names, because we'll probably want to match them with regular expressions at some point and the escaping will be annoying.

**Comment by tschottdorf** [comment]
It's already like that.

**Comment by tschottdorf** [comment]
... but not in time series.

**Comment by mrtracy** [comment]
Pushing this to 1.0.  I think that the decision here is rather arbitrary, but it certainly doesn't effect any functionality in the beta.

**Comment by petermattis** [comment]
Won't changing the separator change the keys used for timeseries? If we change the separator post-beta from `.` to `-` we won't be able to read existing data. That might be ok, but is slightly unfortunate. I'd prefer to bite the bullet and make the change now or accept `.` as the separator forever.

**Comment by cuongdo** [comment]
I prefer the `.` separator, mainly because it reads more easily for me as a
separator. It also seems common enough to be practically a standard.

**Comment by JackKrupansky** [comment]
Dot seems like the natural separator for compound identifiers, analogous to package names. JMX and go-metrics both seem to prefer dot for building multi-part identifiers, not to be confused with using underscore and dash for composing individual names (which may then in turn be compounded.)

**Comment by bdarnell** [comment]
Yeah, I think it's now or never for this change, and since I'm the only one who seems to be in favor of the change and I don't feel strongly about it we can just close the issue.
