### ISSUE TITLE
v19.1.0-beta.20190225: Unknown Event Types in the Web UI for automatic stats

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/cockroach#35319]
**Describe the problem**

Automatic stats are creating `unknown event types` in the Web UI event log

![image](https://user-images.githubusercontent.com/894257/53673249-628f7900-3c54-11e9-88cf-cbf295cbe511.png)

**To Reproduce**

What did you do? Describe in your own words.
Ran the latest beta and sent some test load using https://github.com/cockroachdb/movr. Checked the WebUI and saw a bunch of unknown events.

**Expected behavior**
I'd expect these events to be labeled clearly

**Comment by awoods187** [comment]
Can confirm this happens on SQL 20 too:

![image](https://user-images.githubusercontent.com/22278911/53742887-a6a69780-3e67-11e9-96fe-fbe33f0839a4.png)

**Comment by RaduBerinde** [comment]
Fixing the description for the event is easy: https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/src/util/events.ts#L83

But I don't think we want this showing up as an event since it will be very spammy, and in principle it's not something that a user should need to be concerned with.

**Comment by awoods187** [comment]
@RaduBerinde are all jobs events? it does seem spammy to have it be both an event and a job

**Comment by RaduBerinde** [comment]
No, there is special code to issue an event. I'll add a cluster setting and turn it off by default.

**Comment by RaduBerinde** [comment]
I am planning to make the following improvements:
 - cluster setting to control these events, off by default
 - when events are on, they should have a useful message that contains the table name
 - similarly, the job description should have human-readable information including the table name, not the SQL statement

**Comment by awoods187** [comment]
that sounds great
