### ISSUE TITLE
How to transform sql to kv api?

### ISSUE THREAD

**Issue by minglinlu** [cockroachdb/cockroach#35329]
I wanna know more details about the transformation between SQL and KV .
Is there any specific docs available?

**Comment by nvanbenschoten** [comment]
@minglinlu I believe our best source of information on this is https://www.cockroachlabs.com/blog/sql-in-cockroachdb-mapping-table-data-to-key-value-storage. Let me know if you have specific questions that aren't covered in that blog post.
