### ISSUE TITLE
about forestDB, It looks very good

### ISSUE THREAD

**Issue by Frank-Jin** [cockroachdb/cockroach#3533]
https://github.com/couchbase/forestdb/wiki/Performance-Results

From the report above, The performance is better than rocksdb

Maybe cockroachDB can use this one as the local storage engine.

**Comment by petermattis** [comment]
The numbers certainly look very good, though numbers can mislead and we'd definitely need to perform our own performance comparisons. For an example of just one aspect of how those numbers do not apply directly to Cockroach: they are using a value size of 1 KB. With Cockroach SQL data, values will often be the size of a single encoded column which is likely significantly less than 1 KB. How this would affect the performance of ForestDB vs RocksDB is unclear.

All this is to say that we'd need to gather more data before committing to a switch. And also consider that while RocksDB is a limiter of performance, it is not the current bottleneck in the system. For that, see the SQL and Raft layers.

PS The tree of b-tree structures is somewhat odd in my opinion. I guess I need to read the referenced paper to understand the justification more. My understanding was that [cache oblivious streaming b-trees](http://supertech.csail.mit.edu/papers/sbtree.pdf) were the state of the art in these data structures. Cache oblivious data structures are fascinating and mind-bending.

**Comment by petermattis** [comment]
We're very unlikely to switch the local storage engine at this time. Perhaps longer term this might happen, but at this time RocksDB seems to be serving us adequately.
