### ISSUE TITLE
opt: Reject aliasing with an implied `AS` for hint keywords

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#35347]
**Describe the problem**

Join hints require a specific syntax to work correctly. We should return errors when that syntax is not used in the case of an implicit `AS`. 

Consider this SQL 20 query:
```
root@localhost:26257/tpch> SELECT count(*) FROM lineitem JOIN supplier ON l_suppkey = s_suppkey;
   count
+---------+
  6001215
(1 row)

Time: 7.467556606s
```

Because we allow for implicit aliasing, this query works:

```
root@localhost:26257/tpch> SELECT count(*) FROM lineitem XYZ JOIN supplier ON l_suppkey = s_suppkey;
   count
+---------+
  6001215
(1 row)

Time: 7.255998298s
```
This can be problematic because XYZ is nonsense. In the case of hints, it could lead the user to thinking that a certain hint type has been chosen:

```
root@localhost:26257/tpch> SELECT count(*) FROM lineitem LOOKUP JOIN supplier ON l_suppkey = s_suppkey;
   count
+---------+
  6001215
(1 row)

Time: 7.296768334s

root@localhost:26257/tpch> SELECT count(*) FROM lineitem MERGE JOIN supplier ON l_suppkey = s_suppkey;
   count
+---------+
  6001215
(1 row)

Time: 7.21802905s

root@localhost:26257/tpch> SELECT count(*) FROM lineitem HASH JOIN supplier ON l_suppkey = s_suppkey;
   count
+---------+
  6001215
(1 row)

Time: 7.286066844s

root@localhost:26257/tpch> SELECT count(*) FROM lineitem LOOP JOIN supplier ON l_suppkey = s_suppkey;
   count
+---------+
  6001215
(1 row)

Time: 7.292509493s
```

**Comment by knz** [comment]
@RaduBerinde I told you the choice of syntax was problematic.... Could we perhaps reconsider, in light of this user confusion?

**Comment by RaduBerinde** [comment]
FWIW SQL Server has the same problem.

@knz As of this time I am not aware of a concrete proposal for alternative syntax that is viable (I could not get `JOIN {hint}` or `JOIN @{hint}` to work). Talk to me offline if you have one (or you know how to make `JOIN {hint}` work).

**Comment by knz** [comment]
Yeah SQL Server indeed has the same problem but I won't quote MSSQL as an example of database that "makes data easy".

I'll have a quick look and come back to you. If I don't find anything better than you did, we can simply push back and say "be careful" to users.

(I've meant to create a doc page on "known gotchas" for a long time - one that would also cover e.g. `SELECT x FROM a PARTITION (x)`, `SELECT user FROM t`, etc)

**Comment by RaduBerinde** [comment]
What are your thoughts in general on restricting the alias identifier more when `AS` is not being used?

**Comment by knz** [comment]
1) a terrible idea. *every single time* we've tried to be clever about this in the past, a release later a customer/user comes to us and tells us "my application has broken because of your pg-incompatible decision.

2) I think it would actually be hard to achieve in the grammar, because of identifier/keyword ambiguity.

**Comment by RaduBerinde** [comment]
We decided to stay with the current syntax and possibly add the extended syntax `JOIN@{ ... }` in the next release. We will make sure to call out this pitfall in the docs.

**Comment by awoods187** [comment]
cc @rmloveland for docs

**Comment by rmloveland** [comment]
The documentation portion of this will be addressed (for now) when https://github.com/cockroachdb/docs/pull/4472 merges.
