### ISSUE TITLE
ui: update map logic so it's possible to see where nodes are, even with complex hierarchies.

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/cockroach#35343]
With the following locality tree, it is impossible to see where all the nodes are on the cluster visualization.
![image](https://user-images.githubusercontent.com/894257/53703263-022c4300-3dde-11e9-8999-5b4cdb7e7165.png)

You start with this view of the map:
![image](https://user-images.githubusercontent.com/894257/53703272-225c0200-3dde-11e9-9bc2-8d9715c4c230.png)

Then when you drill down, you have to decide if you want to see where the EITHER the gcp or azure nodes are:
![image](https://user-images.githubusercontent.com/894257/53703276-33a50e80-3dde-11e9-9eb3-6ce27bd5c778.png)

**Describe the solution you'd like**
Make it possible for a user to quickly see where in the world their clusters are deployed. Let's take a second pass at this UX.

cc @timveil

**Comment by piyush-singh** [comment]
I was thinking about this a bit during Jesse's demo of geo-partitioning. The default view here seems to be at the cluster level which is not very helpful - seeing the average location of all nodes in your cluster is unlikely to be meaningful. I've seen some clusters spread across the east coast and western Europe have the default view start in the Atlantic ocean.

After thinking about this, I would suggest starting with the view focusing on the level of the locality hierarchy that is only 1 level above nodes (generally the availability zone or datacenter level). The nice property for the managed service is that we will know the locality hierarchy as we will be the ones setting it up, so getting this right for the MSO console should be a bit easier.
