### ISSUE TITLE
Provide better UX for CCL license expiration

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/cockroach#35342]
**Is your feature request related to a problem? Please describe.**
It is currently not easy to see if an enterprise license is expired. For example, when there is a formerly valid license that has expired the node map just resets to:
![image](https://user-images.githubusercontent.com/894257/53701184-7b20a000-3dc8-11e9-9519-b92c1be81fce.png)

The debug page just says OSS as the license type:
![image](https://user-images.githubusercontent.com/894257/53701194-8ecc0680-3dc8-11e9-9044-526c406c9e34.png)

And the cluster settings for `enterprise.license` don't show up in the UI (/#/reports/settings) despite them showing up in the command line. So it appears the license was never set.

**Describe the solution you'd like**
Audit the UX for trial enterprise license lifecycle (applied | near expiration | expired ) and help users understand what is going on post-expiration and provide next steps.

cc @timveil @robert-s-lee 

Jira issue: CRDB-4593

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[4957](https://cockroachdb.zendesk.com/agent/tickets/4957) has been linked to this issue.

**Comment by piyush-singh** [comment]
Several customers on the CCL license have expressed a desire to check when their license is expiring. That requires opening a support ticket today as there is no self-service way to check the license expiry. Bumping priority on this.
