### ISSUE TITLE
all_keywords.awk does not sort keywords correctly

### ISSUE THREAD

**Issue by yaojingguo** [cockroachdb/cockroach#3539]
Issue the following commands in `cockroach` directory:

```
> cd sql/parser
> touch sql.y
> make
> git status -s
 M keywords.go
```

In the original `keywords.go`, there is:

```
	"CHAR":              CHAR,
	"CHARACTER":         CHARACTER,
```

In the newly generated `keywords.go`, there is:

```
	"CHARACTER":         CHARACTER,
	"CHAR":              CHAR,
```

The cause is that `all_keywords.awk` use `"CHARACTER":         CHARACTER,` and `"CHAR":              CHAR,` instead of `CHARACTER` and `CHAR` to do the sorting. So `"CHARACTER":         CHARACTER,` is placed before `"CHAR":              CHAR,`.  And my locale setting on Ubuntu:
```
> locale
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE=en_US.UTF-8
LC_NUMERIC=zh_CN.UTF-8
LC_TIME=zh_CN.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=zh_CN.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=zh_CN.UTF-8
LC_NAME=zh_CN.UTF-8
LC_ADDRESS=zh_CN.UTF-8
LC_TELEPHONE=zh_CN.UTF-8
LC_MEASUREMENT=zh_CN.UTF-8
LC_IDENTIFICATION=zh_CN.UTF-8
LC_ALL=
```

In my Ubuntu box, a fix is to define `sort` with `sort = "sort -d -t \"\\\"\" -k 2,2"`.

**Comment by petermattis** [comment]
I can't reproduce the bad sorting (even with all of your env variables), though I agree that something with the environment must be causing it. Please send a pull request with your fix.

**Comment by yaojingguo** [comment]
I have just played more with this sorting. Running `export LC_ALL=C` before running make also fixes this problem on my Ubuntu box.
