### ISSUE TITLE
Improve TPC-H in workload

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#35392]
**Describe the problem**

- [x] Workload TPC-H only runs queries `1,3,7,8,9,19` by default. We should allow it to run all 22 TPC-H queries by default. https://github.com/cockroachdb/cockroach/pull/35563
- [x] https://github.com/cockroachdb/cockroach/issues/35418
- [x] https://github.com/cockroachdb/cockroach/pull/35533
- [x] When running tpc-h I hit an error and then received no results. I'd like to receive the results for the queries that did complete even if an error occurs in the workload.
- [ ] Concurrency settings required to finish (https://github.com/cockroachdb/cockroach/issues/35496)
- [x] https://github.com/cockroachdb/cockroach/pull/34891
- [ ] Allow TPCH to be used with AWS (RESTORE tpch.* FROM 'gs://cockroach-fixtures/workload/tpch/scalefactor=1/backup' WITH into_db = 'tpch';)
- [x] Let TPC-H run like the SQL20 using query bench

Current query:
roachprod run $CLUSTER:4 "./workload run tpch --concurrency=1 --scale-factor=1 --tolerate-errors {pgurl:1}

Jira issue: CRDB-4589

**Comment by awoods187** [comment]
Looks like https://github.com/cockroachdb/cockroach/pull/34891 may help here

**Comment by awoods187** [comment]
SET DISTSQL = 'always'; is also set in the process

**Comment by awoods187** [comment]
When running tpc-h I hit an error and then received no results. I'd like to receive the results for the queries that did complete even if an error occurs in the workload.
```
 2h20m6s        0            0.0            0.0      0.0      0.0      0.0      0.0 5
 2h20m6s        0            0.0            0.0      0.0      0.0      0.0      0.0 6
 2h20m6s        0            0.0            0.0      0.0      0.0      0.0      0.0 7
 2h20m6s        0            0.0            0.0      0.0      0.0      0.0      0.0 8
 2h20m6s        0            0.0            0.0      0.0      0.0      0.0      0.0 9
 2h20m7s        0            0.0            0.0      0.0      0.0      0.0      0.0 1
 2h20m7s        0            0.0            0.0      0.0      0.0      0.0      0.0 2
_elapsed___errors__ops/sec(inst)___ops/sec(cum)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)
 2h20m7s        0            0.0            0.0      0.0      0.0      0.0      0.0 3
 2h20m7s        0            0.0            0.0      0.0      0.0      0.0      0.0 4
 2h20m7s        0            0.0            0.0      0.0      0.0      0.0      0.0 5
 2h20m7s        0            0.0            0.0      0.0      0.0      0.0      0.0 6
 2h20m7s        0            0.0            0.0      0.0      0.0      0.0      0.0 7
 2h20m7s        0            0.0            0.0      0.0      0.0      0.0      0.0 8
 2h20m7s        0            0.0            0.0      0.0      0.0      0.0      0.0 9
 2h20m8s        0            0.0            0.0      0.0      0.0      0.0      0.0 1
 2h20m8s        0            0.0            0.0      0.0      0.0      0.0      0.0 2
 2h20m8s        0            0.0            0.0      0.0      0.0      0.0      0.0 3
 2h20m8s        0            0.0            0.0      0.0      0.0      0.0      0.0 4
 2h20m8s        0            0.0            0.0      0.0      0.0      0.0      0.0 5
 2h20m8s        0            0.0            0.0      0.0      0.0      0.0      0.0 6
 2h20m8s        0            0.0            0.0      0.0      0.0      0.0      0.0 7
 2h20m8s        0            0.0            0.0      0.0      0.0      0.0      0.0 8
 2h20m8s        0            0.0            0.0      0.0      0.0      0.0      0.0 9
I190305 04:42:51.979154 20 workload/tpch/tpch.go:208  [10] return 20 rows after 55.86 seconds:
  SET DISTSQL = 'always';
SELECT
	c_custkey,
	c_name,
	sum(l_extendedprice * (1 - l_discount)) AS revenue,
	c_acctbal,
	n_name,
	c_address,
	c_phone,
	c_comment
FROM
	customer,
	orders,
	lineitem,
	nation
WHERE
	c_custkey = o_custkey
	AND l_orderkey = o_orderkey
	AND o_orderDATE >= DATE '1993-10-01'
	AND o_orderDATE < DATE '1993-10-01' + INTERVAL '3' MONTH
	AND l_returnflag = 'R'
	AND c_nationkey = n_nationkey
GROUP BY
	c_custkey,
	c_name,
	c_acctbal,
	c_phone,
	n_name,
	c_address,
	c_comment
ORDER BY
	revenue DESC
LIMIT 20;
Error: pq: sum(): unsupported binary operator: <float> * <int>
Error:  exit status 1
```

**Comment by awoods187** [comment]
https://github.com/cockroachdb/cockroach/pull/35533 will help too

**Comment by jordanlewis** [comment]
You don't need a scale factor flag in TPCH - unlike TPCC, the queries run correctly as long as the data is loaded correctly.

**Comment by danhhz** [comment]
> When running tpc-h I hit an error and then received no results. I'd like to receive the results for the queries that did complete even if an error occurs in the workload.

Have you tried the `--tolerate-errors` flag on `workoad run`? It sounds like exactly what you want

**Comment by awoods187** [comment]
Looks like this is almost done. The main thing is the restore.
