### ISSUE TITLE
use `roachpb.RKey` in more places

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#3541]
from https://reviewable.io/reviews/cockroachdb/cockroach/3513#-K6HL7ThOQQsuLty2pp6-r1-788:

We have types `roachpb.Key` and `roachpb.RKey`. The former is a key as contained by RPCs and it can either be a "real" key or a range-local key. If it's range-local, that means that `keys.Addr(key)` (which is the key to use for looking up the right range) is ` != key`.

That leads to some basic questions which are inconsistently handled in the code. For example, the lower storage layers (MVCC) mostly deal in `roachpb.Key` when it seems reasonable to assume that it should be `RKey`.

**Comment by bdarnell** [comment]
The lower storage layers definitely need to work with `Key`, not `RKey`. The conversion from `Key` to `RKey` (i.e. `keys.Addr`) is lossy and multiple `Keys` may map to the same `RKey`. The use of `RKey` should be limited to those places where we specifically care about range boundaries, and in most cases we should retain the original `Key` and use that once we've mapped the `RKey` to the appropriate range.

**Comment by tschottdorf** [comment]
Hmm, not sure what I was thinking. I think I wanted `Key` to be cast to `RKey` (not via `Addr`), but that doesn't make much sense. Doesn't seem that there's anything to do after all.
