### ISSUE TITLE
Production flag to automatically select the % of mem reserved for sql, rocksdb and other things

### ISSUE THREAD

**Issue by bladefist** [cockroachdb/cockroach#35429]
Our Cockroach nodes are dedicated cockroach nodes, and right now we are utilizing 30% of our memory.  We're using .25/.25 memory/cache flags for 64GB of RAM.

We are going to play with slowly increasing those values, but ideally I would like a flag to utilize all system memory for performance.  This is the default way most databases work, and the non-default method would be to configure an artificial cap if you need to reserve memory for something else.

The database knows best how much RAM it needs for memory vs cache, so having it automatically manage it's memory and maximize it's use would be very powerful for devops.

Thanks!

**Comment by knz** [comment]
dup #8260
