### ISSUE TITLE
sql: add support for sorted GROUP BY results

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#3542]
Currently, even once #3494 lands with initial `GROUP BY`support, we still error with `unimplemented ORDER BY with GROUP BY/aggregation` if both a `GROUP BY` and `ORDER BY` are used.

As noted in the code, adding support will require some changes to how we do sorting (as it currently hooks into the scan node).

**Comment by dt** [comment]
@petermattis At first glance, I appear to have two options for making `sortNode` work with `groupNode`:

  1. make `groupNode` support calling `addRender` and similar, such that it becomes interchangeable with a plain `scanNode` for the purposes of a `sortNode` (pulling the common methods into an interface).

  2. let the existing `sortNode` wrap the `scanNode` *before* the `groupNode` does, so that when it iterates over the render expressions to extract aggregates, it also includes any that the `sortNode` added during wrapping.

At present I think I'm leaning towards 2), after toying with 1), but wanted to solicit feedback before I got too invested in either approach.

**Comment by petermattis** [comment]
I was expecting we would have to do something like option 1. Option 2 seems a bit messier, though perhaps easier to get working. I think it would be nice if neither `sortNode` or `groupNode` took a `scanNode` but instead there was some sort of `renderNode` interface with methods for looping over the render targets and adding new ones.
