### ISSUE TITLE
stats: handle the case where auto stats take longer than the TTL

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#35432]
The minimum TTL we recommend in the docs is 10 minutes. With throttling, we have seen automatic statistic jobs take 2+ hours. We need to have sane behavior in a case like this. I am not sure what the current behavior is, I assume the table scanners would start getting errors and we would keep restarting the job forever.

CC @rytaft @awoods187

**Comment by awoods187** [comment]
Could you clarify what you mean here? What do you mean by sane behavior?

**Comment by RaduBerinde** [comment]
Sane behavior = either make the stats job work somehow despite the short TTL, or disable auto stats altogether in this kind of scenario.

First we need to test what the current behavior is in this case (I suspect there would be periodic stat jobs that fail and no stats would ever be gathered).

**Comment by awoods187** [comment]
When a user sets the TTL to 10 minutes and a stats job is running what happens?
Does it fail? Do we offer a warning? 

I can test this tomorrow as well if needed.

**Comment by RaduBerinde** [comment]
If the job takes longer than 10 minutes, I believe it would fail. There is no warning.

**Comment by RaduBerinde** [comment]
A solution to this problem would be to somehow set up the table readers to use a new transaction/timestamp periodically - we don't really care if some pieces of the table come from different timestamps than others.

**Comment by RaduBerinde** [comment]
I've been trying to repro this but I'm having trouble getting GC to run even when the TTL is low.

**Comment by RaduBerinde** [comment]
Ok, I have a tpcc setup where I set up the `order_line` table to have a low TTL and the data store is pretty small. After the table gets big enough, jobs start failing:

![image](https://user-images.githubusercontent.com/16544120/53914329-5ed06d80-402b-11e9-95ee-42b7b3d8cba3.png)

**Comment by RaduBerinde** [comment]
The change here is non-trivial, I think it's too risky to try to get it in 19.1. We will plan to backport a fix to 19.1.x.

In the meantime, we can document that if you use low TTLs with large tables, you might see stat job failures, in which case you can turn off automatic stats.

**Comment by awoods187** [comment]
I ran into this today with the TTL set to 10m for testing dropping schema changes:
![image](https://user-images.githubusercontent.com/22278911/54467086-495cf100-4759-11e9-9803-ffe004714be2.png)

We should make sure this is documented for 19.1 @rmloveland

**Comment by rytaft** [comment]
cc @rmloveland

**Comment by RaduBerinde** [comment]
I will start working on this so we can hopefully get it backported quickly.
