### ISSUE TITLE
ui: App filter on statements page has too many $internal options

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#35460]
When looking at the `APP:` dropdown on the statements page, we see many distinct categories of internal queries. When a user is looking through these app names to find their own application, it can be frustrating to have to search through > 10 "apps" with the $internal prefix. 

![image](https://user-images.githubusercontent.com/21692034/53893870-097d6780-3ffd-11e9-87d4-5f1c811bd38e.png)

Instead, we should probably group these in the UI under a single internal heading. The additional detail provided for the different internal query types is probably not helpful to most of our users.

cc @jseldess

**Comment by knz** [comment]
So the reason why they are detailed is that the app name serves two separate purposes:

- group the things in the UI
- separate the activities in telemetry.

We want to keep the separation in telemetry which is why the source data should not change. But I agree we can group them in the UI.
