### ISSUE TITLE
import: bad time estimate for import job

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#35472]
In the screenshot below the import for the stock table is estimated to finish in 13s, but that's nowhere near reality.

![screenshot 2019-03-06 15 05 10](https://user-images.githubusercontent.com/377201/53910183-45c2bf00-4021-11e9-9785-cc73a4c71d36.png)

The imports come from `./cockroach-linux-2.6.32-gnu-amd64 workload fixtures import tpcc --warehouses=10000 --db=tpcc`
In another import I've started, the stock table is shown at 0% and no estimate - which is better assuming the thing hasn't started yet because it's waiting on other imports.

@mjibson are you the right person?

**Comment by mjibson** [comment]
@dt is this due to the new workload import thing? Or is that off by default?

Either way, this has been a known problem for years and it's not on any roadmap.

**Comment by dt** [comment]
no, everything I've added recently is off by default until 19.1 ships.
