### ISSUE TITLE
sql: implicit columns in indexes are not used for generating constraints and scan spans

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#3548]
... although they could be, just like regular columns, in the case of non-unique indexes (when the implicit columns are stored as part of the key).

**Comment by tamird** [comment]
cc'ing some SQL folks: @paperstreet @RaduBerinde @knz @dt

**Comment by RaduBerinde** [comment]
I'll put it on my pile since I have #6346
