### ISSUE TITLE
roachprod: my clusters disappeared from the list

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#35483]
I have a cluster that exists (`andrei-repro-1`), and yet it disappeared from the list of clusters (`roachprod sync`). The only unusual thing about the cluster is that it's on GCE, on a different project than the default (it's under andrei-jepsen).
Perhaps the lifetime expired and whatever powers that list of clusters decided that it doesn't exist any more, even though it doesn't have to power to destroy it?
Any idea?

@petermattis @ajwerner

**Comment by petermattis** [comment]
By default, `roachprod` lists clusters in the `cockroach-ephemeral` project. You need to do:

```
~ roachprod list --gce-project=andrei-jepsen
andrei-repro-1:  [gce]  8  (6h58m46s)
...
```

**Comment by petermattis** [comment]
I'm not sure if there is anything we can do about this surprising behavior. It is useful to allow a non-default GCE project to be used, but once you do you're on your own.

**Comment by andreimatei** [comment]
Yes, I actually remembered that parameter later in my dream. I must have been using it for a while and then forgot about it and was pissed that my shit disappeared.
Thank you.
