### ISSUE TITLE
Test Performance Write and Read

### ISSUE THREAD

**Issue by phamtai97** [cockroachdb/cockroach#35488]
## Infomation laptop:
I use Ubuntu 18.04
Memory: 16gb
Processor Intel Core i5-8250U, 1.6GHz x 8
Disk SSD 256gb

## Config server:
I setup server CockroachDB:
- Node1: cockroach start --insecure --listen-addr=localhost:8000
- Node2: cockroach start --insecure --store=node2 --listen-addr=localhost:8001 --http-addr=localhost:8081 --join=localhost:8000
- Node3: cockroach start --insecure --store=node3 --listen-addr=localhost:8002 --http-addr=localhost:8081 --join=localhost:8000

I use  Go Postgres driver. And when I set db.SetMaxOpenConns(200), db.SetMaxIdleConns(50).

## Test function Insert
I create the table as follows:
```go
if _, err := db.Exec(
 "CREATE TABLE IF NOT EXISTS benchmark.accounts (id varchar(18) PRIMARY KEY, balance bigint)");err != nil {
 return err
}
```
I will insert 1000000 rows and measurement of insert time. 
```go
if _, err := db.Exec(
 "INSERT INTO benchmark.accounts (id, balance) VALUES ($1, $2)", msg.Id, msg.Balance); err != nil {
 log.Fatal("Insert msg error: ", err)
}
```
CLI:
```sh
$ benchmark_cdb executor -numGoroutine=1000 -numMsg=1000000 -type=0 
```
And at the end I measured an average of insert `2045 row/s`.

## Test function QueryRow
I try to query 1 line 1000000 times.
```go
id := "1"
if err := db.QueryRow("SELECT * FROM benchmark.accounts WHERE id = $1", id).Scan(&idRes, &balanceRes); err != nil {
 log.Fatal("Query fail: ", err)
}
```
CLI:
```sh
$ benchmark_cdb benchmark_cdb executor -numGoroutine=1000 -numMsg=1000000 -type=1
```
And at the end I measured an average of queryrow `7427 row/s`.

My expected result:
- Write: `> 10000 row/s`
- Read: `> 10000 row/s`

I don't know if I have used the wrong or wrong configuration. You can see my code [here](https://github.com/phamtai97/benchmark_cdb)

**Comment by awoods187** [comment]
@phamtai97 thanks for submitting an issue. What version of CRDB did you test?

**Comment by phamtai97** [comment]
This is cockroach version:
```sh
Build Tag:    v2.1.4
Distribution: CCL
Platform:     linux amd64 (x86_64-unknown-linux-gnu)
Go Version:   go1.10.7
C Compiler:   gcc 6.3.0
```

**Comment by ajwerner** [comment]
Hey @phamtai97, I happy to hear you're trying out CRDB and I hope I can improve the performance that you're seeing. I have a couple of tips which might make a big difference. 

I notice in your code that you insert your messages with sequential IDs. Sequential IDs can limit write throughput (see [here](https://www.cockroachlabs.com/docs/stable/performance-best-practices-overview.html#unique-id-best-practices)). CockroachDB internally splits the data it stores in to ranges which in some ways defines a unit of parallelism. The database starts with just a single range per table. In the upcoming release we have added [a feature that detects heavy write traffic to ranges and splits them automatically](https://www.cockroachlabs.com/docs/v19.1/load-based-splitting.html).  Given that you're running v2.1.4 you could manually split the table using [ALTER TABLE SPLIT AT](https://www.cockroachlabs.com/docs/stable/split-at.html). My hunch is that if your table is pre-split and the keys are randomly ordered the keys you will observe better performance.

Next I notice that your concurrency may be somewhat on the high side, especially given the sequential nature of your workload. That number may be more appropriate as you spread traffic over more ranges.

Lastly it might help if you inserted multiple rows simultaneously as described (here)[https://www.cockroachlabs.com/docs/stable/insert.html#performance-best-practices]. That being said, it is best if when you batch multiple inserts you keep those values contiguous as it is optimal for each statement to write to just a single range.

Let me know if any of that advice doesn't make sense.

**Comment by phamtai97** [comment]
Thank you your advice. I will try it. 
But there is a problem of reading. Reading to me such results is not reasonable. I only read one line and the speed was so low `7427 row/s`
Can you explain help me read the problem ?

**Comment by ajwerner** [comment]
I too am a little surprised by the low throughput on the reads given that it's always reading the same key. My best guess is that it's related to data structure contention on the single range. My hunch is that splitting to multiple ranges will improve your throughput. My guess is once the write traffic is spread over multiple ranges the reads against that one range will improve dramatically. 

Before you do any of this however, maybe it'd be easier for you to try lowering the concurrency of your workload runner. Counter-intuitively it may increase throughput. 

Another suggestion that may be easier than re-writing the code to take advantage of the splits is to update to the latest beta which you can find [here](https://www.cockroachlabs.com/docs/dev/install-cockroachdb-linux.html).

**Comment by phamtai97** [comment]
Thank you your advice.  I tried reducing goroutine to 500, 100 and the results didn't change much

```sh
$ benchmark_cdb executor -numGoroutine=500 -numMsg=1000000 -type=1
```
Result: `7690`

```sh
$ benchmark_cdb executor -numGoroutine=100 -numMsg=1000000 -type=1
```
Result: `6230 msg/s`

**Comment by phamtai97** [comment]
@ajwerner I think reading the same key will be faster than reading multiple ones. The reason? CockroachDb may return cached results and hence much faster.
