### ISSUE TITLE
sql: speed up DROP COLUMN

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#35499]
DROP COLUMN involves the following process:

1. Move the column into the WRITE_ONLY state
2. Move the column into the DELETE_ONLY state
3. scan the entire table and delete the column
4. remove the column

step 3. can take a long time because it is a full scan as well as an update of every row.

What we can do is change this to
1. Move the column into the WRITE_ONLY state
2. Move the column into the DELETE_ONLY state
3. remove the column while keeping the column id in the DELETE_ONLY state so that all future UPDATE/DELETE on the row will continue to delete the column. Assume this is a transaction at time T. We do this to allow a future deletion of the column to be doable at an older timestamp T.
Note: the column name is now reusable.
4. The old column is deleted asynchronously at timestamp T or higher.

When is the old data deleted?

We could immediately delete all the old data but that will double the data held because of MVCC.
So instead we can wait out the data TTL and then delete the column. This will immediately trigger TTL delete on the older version of the data.

Ideally we want to use the AddSSTable bulk ingest mechanism to delete the old column at timestamp T. I don't see any concerns with using it.

**Comment by lucy-zhang** [comment]
Closing this since I think we're taking the https://github.com/cockroachdb/cockroach/issues/47989 approach.
