### ISSUE TITLE
opt: Allow automatic stats to be run on a per table basis

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#35497]
**Is your feature request related to a problem? Please describe.**
Currently, automatic statistics apply to the entire cluster. 

Having a per table toggle may allow somebody to bulk load into a staging table quickly and then move data around to tables more slowly where statistics are applied.

Some tables may need automatic statistics--others may not. 

**Describe the solution you'd like**
Per table toggle to turn Automatic Statistics on or off.

**Comment by rytaft** [comment]
This is a duplicate of https://github.com/cockroachdb/cockroach/issues/40989.
