### ISSUE TITLE
How to create a cluster with 3 docker containers?

### ISSUE THREAD

**Issue by ericjvandervelden** [cockroachdb/cockroach#3550]
Hi,

I tried to do what is written in the README.md, but then with 3 docker containers iso. 3 machines. 

I could not get it right. I can set up a cluster on 1 node using 3 databases. That goes OK, and the banking application runs on it. 

So I created 3 containers, node1, node2, node3,

[eric@almond Logs]$ sudo docker run --net=my-bridge --rm -it --name node1 -P cockroachdb/cockroach shell
[eric@almond Logs]$ sudo docker run --net=my-bridge --rm -it --name node2 -P cockroachdb/cockroach shell
[eric@almond Logs]$ sudo docker run --net=my-bridge --rm -it --name node3 -P cockroachdb/cockroach shell

and on each I did the following,
\# bash
root@18c830761509:/cockroach# PATH=$PATH:.
root@18c830761509:/cockroach# apt-get update && apt-get install openssh-server openssh-client vim
root@18c830761509:/cockroach# mkdir /var/run/sshd
root@18c830761509:/cockroach# vi /etc/ssh/sshd_config
PermitRootLogin yes
root@18c830761509:/cockroach# /usr/sbin/sshd -D&
root@18c830761509:/cockroach# echo "root:root" | chpasswd

Then on node1 I did the following (on the create-node line I used the network name of the nodes and the hostname of them, because I am not sure what to do),

root@18c830761509:/cockroach# cockroach cert create-ca
root@18c830761509:/cockroach# cockroach cert create-node 18c830761509 localhost 1c78f2273514 node2 a31077735387 node3
root@18c830761509:/cockroach# cockroach cert create-client root
root@18c830761509:/cockroach# scp -r certs node2:/cockroach
root@node2's password: root
root@18c830761509:/cockroach# scp -r certs node3:/cockroach
root@node3's password: root

Now I did on node1,

root@18c830761509:/cockroach# cockroach init --stores=ssd=db0

root@18c830761509:/cockroach# cockroach start --stores=ssd=db0 --gossip=localhost:26257,node2:26257,node3:26257
/ or    ,
root@18c830761509:/cockroach# cockroach start --stores=ssd=db0 --gossip=18c830761509:26257,1c78f2273514:26257,a31077735387:26257

I see error messages like, with a strange IP address,
W1229 20:33:00.980191 653 rpc/client.go:300  dial tcp 69.172.201.208:26257: i/o timeout

E1229 20:32:59.042901 653 storage/queue.go:373  failure processing replica range=1 [/Min-/Max) from replicate queue: storage/allocator.go:254: unable to allocate a target store; no candidates available

Hopefully it is not to long. Maybe you can tell me what I do wrong. Thanks!

**Comment by tschottdorf** [comment]
Hi Eric,

I'm not exactly sure what goes wrong there, but it seems like a docker networking issue. `69.172.201.208:26257` above should be an IP address of another node, and if that's not reachable, something is fishy there. You could try manually with `netcat` whether it's a resolution issue, bridge issue or whether the port just isn't being exposed.
Or, if all you want is a running docker cluster and you have a `Go` environment, `make acceptance TESTS=TestPut TESTFLAGS='-v -d 1h -num-local=3'` gives that to you.

**Comment by ericjvandervelden** [comment]
Thank you very much!
