### ISSUE TITLE
sql: DDL has become excessively sensitive to txn retries

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#35549]
For context, I had a coding hiatus in the last 2-3 weeks and I have more sensitivity to "larger scale" differences in the health of our test suite between, say, a month ago and today.

The truth of the matter is **I am seeing a bunch of new test flakes that all point in the direction of SQL DDL suffering from transaction retries in ways that did not exist previously**.

The reader of this issue description should understand that we have **many, many** SQL tests that assume that the allocation of object IDs (table, seq, view, dbs) is deterministic and not subject to retries if there is just 1 client to an entire (multi-node) cluster.

This assumption is currently massively violated.

Some symptoms, which many of you may recognize:

- the allocated IDs are occasionally larger than expected, which indicates the DDL was unexpectedly retried
- the test fails outright with a txn retry error

I will refrain from phrasing an opinion about whether the retries are desirable/acceptable. However I'd like to point out that **if we keep the current behavior, we need to audit and rewrite a very large number of tests throughout SQL** and this task is thoroughly unwelcome so late in the release cycle.

@bdarnell @petermattis please advise.

**Comment by knz** [comment]
@bdarnell @nvanbenschoten  if there was a way to disable txn write pipelining if SystemConfigSpan is listed in the batch, maybe that would help? (unsure)

**Comment by knz** [comment]
Example failure #35463

**Comment by knz** [comment]
Example failure: https://teamcity.cockroachdb.com/viewLog.html?buildId=1168048&

```
------- Stdout: -------
=== PAUSE TestLogic/local/rename_table
            logic.go:2329: 
                
                testdata/logic_test/rename_table:230: 
                expected success, but found
                pq: restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE): "sql txn" id=27f865db key=/Table/SystemConfigSpan/Start rw=true pri=0.01225905 stat=PENDING epo=0 ts=1552061893.764510656,1 orig=1552061893.749514164,0 max=1552061893.749514164,0 wto=false seq=19
            logic.go:2345: 
                testdata/logic_test/rename_table:230: error while processing
            logic.go:2346: pq: restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE): "sql txn" id=27f865db key=/Table/SystemConfigSpan/Start rw=true pri=0.01225905 stat=PENDING epo=0 ts=1552061893.764510656,1 orig=1552061893.749514164,0 max=1552061893.749514164,0 wto=false seq=19
```

**Comment by knz** [comment]
Another spurious failure: https://teamcity.cockroachdb.com/viewLog.html?buildId=1168141&buildTypeId=Cockroach_UnitTests

**Comment by knz** [comment]
ditto https://teamcity.cockroachdb.com/viewLog.html?buildId=1168048&buildTypeId=Cockroach_UnitTests

**Comment by knz** [comment]
I think the recent uptick in `show_trace` failures (cf #33720) is also related.

**Comment by bdarnell** [comment]
If it's RETRY_SERIALIZABLE, I would not expect disabling pipelining to help.

Single-node, single-client-thread tests should not be experiencing retry errors. 

Could it be automatic stats? It looks like we read the table data using AOST -30s, but we scan the table *metadata* at the current time to discover all the tables that exist. That would lead to RETRY_SERIALIZABLE on txns that create tables. We should use AOST on the metadata query too. (and in general, any internal background operations should use AOST for any read-only queries)

**Comment by knz** [comment]
I'll look into the metadata query for stats. Thanks for pointing this out. However:

> Single-node, single-client-thread tests should not be experiencing retry errors.

Our tests are assuming that multi-node, single-client-thread tests are also immune to retry errors in DDL (so that ID allocation is deterministic in single-threaded tests that use multi-node clusters).

**Comment by RaduBerinde** [comment]
I have also noticed that automatic stats resulted in a lot of write txns to the jobs table because of progress updates. These transactions internally have to read system metadata tables every time because system tables don't use the table/lease cache (#23937).

In #35543 I'm changing the frequency to once every 5 seconds instead of once per second, and also making it so that most queries just check the status instead of modifying the table. Unfortunately it still needs to read through metadata tables, and this query can't really use AOST (except perhaps with a very recent time - it checks for job cancellation).

**Comment by knz** [comment]
very recent time will do (`-1s`) .We can tolerate waiting 1 second for jobs to cancel.

**Comment by bdarnell** [comment]
If a transaction contains only a DDL statement, it should not return a retryable error to the client. It may retry internally, though, and I don't know how that interacts with table ID allocation. 

Reading from the jobs table shouldn't cause any issues for txns running CREATE TABLE. The metadata table I was referring to was system.descriptor (a single-key read of the descriptor for the jobs table should also be fine).

**Comment by knz** [comment]
DDL retry will re-allocate a table ID (because we re-plan and re-execute the stmt).

**Comment by vivekmenezes** [comment]
FYI one of the reasons why DDL are more likely to retry is because they read the Commit timestamp using txn.CommitTimestamp().

related issue: https://github.com/cockroachdb/cockroach/issues/17698

**Comment by RaduBerinde** [comment]
The scan of all table metadata for auto stats happens only once at server startup. Perhaps that is still problematic since most tests run on a fresh server. Perhaps we should be moving `ensureAllTables` out of the worker and run it synchronously in `Refresher.Start`.

**Comment by tbg** [comment]
I also got TestLogic/local/rename_table in CI just now.

**Comment by knz** [comment]
I assume this is *after* I merged my patch last weekend on delaying table stats collection?

**Comment by tbg** [comment]
https://teamcity.cockroachdb.com/viewLog.html?buildId=1173509&buildTypeId=Cockroach_UnitTests

Yes, staging on top of https://github.com/cockroachdb/cockroach/commit/9d058d53c8a82fceb2205f1827c26f1bf36c32ba

**Comment by knz** [comment]
@bdarnell @RaduBerinde so the stats were not it. back to the drawing board.

**Comment by vivekmenezes** [comment]
Do we need any help here? Should someone from schema changes take this on?

**Comment by knz** [comment]
Another one here: https://teamcity.cockroachdb.com/viewLog.html?buildId=1177617&buildTypeId=Cockroach_UnitTests

> Do we need any help here? 

YES!!!

> Should someone from schema changes take this on?

No idea. It's hard to see where the problem is.

**Comment by nvanbenschoten** [comment]
I can reproduce this easily with
```
make stress PKG=./pkg/sql/logictest TESTS=TestLogic/.*/rename_table
```

So far I've tracked it down to a read-write conflict tracked through the read timestamp cache. The timestamp cache entry **has** a transaction id, so this is not due to closed timestamps or lease transfers.

**Comment by nvanbenschoten** [comment]
The conflicting write is a `PutRequest` on key `/Table/3/1/57/2/1`. This key is in the `DescriptorTable`. So something is scanning over the descriptor table (presumably at the current time) and pushing concurrent writing transactions (schema changes?).

**Comment by nvanbenschoten** [comment]
Here's the SQL statement that conflicted with the write:
```
CREATE STATISTICS __auto__ FROM [58] AS OF SYSTEM TIME '-1µs'
```

cc. @RaduBerinde

**Comment by nvanbenschoten** [comment]
So I bet this is just a matter of increasing
https://github.com/cockroachdb/cockroach/blob/26955319310e9fb4fc88c7876a69d96aa4ae5338/pkg/sql/logictest/logic.go#L1028

**Comment by nvanbenschoten** [comment]
Bumping that to 10ms resolved the flake. I threw it in a PR here: #35808.

@rytaft do you mind signing off on this? Bumping up the delay is a fine resolution as long as it doesn't make optimizer tests flaky or make them take significantly longer. If it does, we'll probably want some other synchronous form of ensuring that stats are sufficiently up-to-date, as an async delay would be inherintely flaky no matter how short the delay is anyway.
