### ISSUE TITLE
sqlccl: flake in logictestccl/testdata/logic_test/zone

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#35546]
Observed e.g. in https://teamcity.cockroachdb.com/viewLog.html?buildId=1168018&

```
------- Stdout: -------
=== PAUSE TestCCLLogic/5node-dist-opt/zone
=== CONT  TestCCLLogic/5node-dist-opt/zone
--- done: testdata/logic_test/zone with config 5node-dist-opt: 12 tests, 1 failures
--- total: 286 tests, 1 failures
test logs left over in: /tmp/logTestCCLLogic019160877
            logic.go:2313: 
                 
                testdata/logic_test/zone:70: EXECUTE p
                expected:
                    scan  ·      ·
                    ·     table  t@secondary
                    ·     spans  /10-/11
                but found (query options: "") :
                    scan  ·      ·
                    ·     table  t@primary
                    ·     spans  /10-/10/#
```

the spans are nearly equivalent.

if my eyes serve me well, this looks like the problem jordan solved earlier with #33350. Is it possible that a code path was not covered?

**Comment by andy-kimball** [comment]
@RaduBerinde, could this have anything to do with the recent changes you made for making zones work with query caching? It looks like we're not correctly invalidating the cached query in this case.

**Comment by RaduBerinde** [comment]
Hm.. Both the old and the new code path relied on gossip which is asynchronous. I think this would have been flaky either way. We should use the `retry` option.

**Comment by andy-kimball** [comment]
Yeah, I like that theory. I'll try making that change.

**Comment by bdarnell** [comment]
This is still happening with the `retry` option: https://teamcity.cockroachdb.com/viewLog.html?buildId=1174179&buildTypeId=Cockroach_UnitTests
