### ISSUE TITLE
stats: finalize cluser settings

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#35544]
This is a reminder to finalize the cluster settings for stats:
 - [x] remove `experimental_`
 - [x] look at hardcoded parameters and consider adding settings for them (I think `targetFractionOfRowsUpdatedBeforeRefresh` deserves one).

**Comment by rytaft** [comment]
@awoods187 I've made the two changes Radu suggested above. Would you like to see any other configurable parameters? The other important params we aren't currently exposing as cluster settings are:
- Default refresh interval (frequency that each node will check if it needs to refresh stats, currently one minute)
- Default AS OF time (AOST to be used with automatic stats, currently -30 seconds)

There are a few others, but the above two are the only ones I can think of that should possibly be exposed. I would lean towards not exposing them unless our SEs or customers ask, but let me know if you have a different opinion...

**Comment by awoods187** [comment]
What about % of rows changed? That, along with number of rows, seems to be the main way to use this. 

I like the default refresh interval too.

I'm not sure the AOST needs to be done--I can't think why someone would want this update more frequently. That being said, if its easy it may be worth of inclusion.

**Comment by RaduBerinde** [comment]
I would leave AOST setting out because we'll have a somewhat different concept when we fix #35432 and it will be confusing.

**Comment by RaduBerinde** [comment]
Default refresh interval is tricky because it won't get applied until node restart. It's also a somewhat obscure implementation detail, pretty hard to explain.

**Comment by rytaft** [comment]
I've updated the PR to include % of rows changed as well as min total rows changed before refresh.  I think @RaduBerinde is right that the others should probably be kept non-configurable for now.
