### ISSUE TITLE
Nodes unable to start: cannot addReplicaInternalLocked; range ... has overlapping range 

### ISSUE THREAD

**Issue by tim-o** [cockroachdb/cockroach#35559]
**Describe the problem**

A user reports that two nodes on their 15 node cluster running 2.1.5. OOMd. Following the crash, 26 ranges became unavailable, and the nodes have been unable to join the cluster. Attempts to start result in: 
```
E190307 18:01:09.208491 1 cli/error.go:230 cockroach server exited with error: failed to start store: [n10,s10]: cannot addReplicaInternalLocked; range [n10,s10,r88340/3:/Table/16572/1/"\x8{c3\…-d:7…}] has overlapping range r136958:/Table/16572/1/"\x8{b\xb1\xfcB\x8d'J\xe2\xba&@\xa8\xc44\xadA"-eA6\xdf\xe2\xc4N;\x86\x88\x82\x14V\xa7O\x06"} [(n11,s11):1, (n4,s4):2, (n10,s10):3, next=4, gen=0] 
Error: cockroach server exited with error: failed to start store: [n10,s10]: cannot addReplicaInternalLocked; range [n10,s10,r88340/3:/Table/16572/1/"\x8{c3\…-d:7…}] has overlapping range r136958:/Table/16572/1/"\x8{b\xb1\xfcB\x8d'J\xe2\xba&@\xa8\xc44\xadA"-eA6\xdf\xe2\xc4N;\x86\x88\x82\x14V\xa7O\x06"} [(n11,s11):1, (n4,s4):2, (n10,s10):3, next=4, gen=0] 
Failed running "start" 
```

Cockroach debug zip available here (CRL only): https://drive.google.com/drive/u/1/folders/1o_o3WQO8bYnigWfyMqrTjGjnQmKgQKAO

**Comment by tim-o** [comment]
Zendesk ticket #[3071](https://cockroachdb.zendesk.com/agent/tickets/3071) has been linked to this issue.

**Comment by tbg** [comment]
@tim-o a debug zip doesn't have the logs of the down node(s). Were those logs recovered separately? If not, please do so, they likely contain important information.

**Comment by tim-o** [comment]
The user was going to try to pull them - I pinged them for an update, I'll let you know once we received them. Is there anything else I can ask for?

**Comment by tbg** [comment]
Data directories if that is an option -- this kind of bug usually requires digging around at a very low level for cues. I understand this may not be possible if prod data is involved.

**Comment by tim-o** [comment]
Yeah I asked for that too if possible. I'll let you know what they say.

**Comment by lamb84** [comment]
This is Harry, I will try to dig into the failing pods and grab the logs.

**Comment by bdarnell** [comment]
Fixed by https://github.com/cockroachdb/cockroach/pull/35626

**Comment by hongweijia** [comment]
Hi @bdarnell 
Any quick workaround to fix this issue? We have an production cluster ran into this issue. Any idea how to fix it? Thanks!

**Comment by bdarnell** [comment]
@hongweijia To prevent this issue from happening, upgrade to version 19.1.0 or newer (if you're already running a newer version, then it's a different issue than this one). If it's already happened and it's affecting a single node, decommission that node. If it's affecting multiple nodes, you'll probably need to decommission all of them but you'll have to proceed carefully; if you're an enterprise customer submit a support ticket for guidance.
