### ISSUE TITLE
changefeedccl, storageccl: URL parameter names for CDC and cloud storage should be case-insensitive

### ISSUE THREAD

**Issue by rolandcrosby** [cockroachdb/cockroach#35553]
CDC sinks and backup/restore/import URLs use URL parameters for configuration. Right now, all of the [cloud storage URL parameters](https://www.cockroachlabs.com/docs/v19.1/import.html#import-file-urls) are specified in SHOUTING_SNAKE_CASE (e.g. AWS_ACCESS_KEY_ID, AZURE_ACCOUNT_NAME, AUTH), while [CDC-specific URL parameters](https://www.cockroachlabs.com/docs/v19.1/create-changefeed.html#parameters) are in snake_case (topic_prefix is the only one so far).

We should make all of these parameter names case insensitive, and standardize the docs to one case or the other.

Jira issue: CRDB-4575

**Comment by miretskiy** [comment]
params are case insensitive.
