### ISSUE TITLE
Backups stalling for hours

### ISSUE THREAD

**Issue by bladefist** [cockroachdb/cockroach#35580]
This is the second time this has happened.  We run an enterprise backup, which normally takes 30 seconds.  Backup will stall after 95% done,  and it will take 4-8 hours to complete, going 0.1% at a time.

This happened again today, different database, but same cluster.

v2.1.5  @rolandcrosby was helping the first time.

**Comment by miretskiy** [comment]
@bladefist  Can you provide a bit more info on this?
Are you still running 2.1 release (it's really old, and the backup code has changed significantly).

**Comment by bladefist** [comment]
@miretskiy no longer an issue.
