### ISSUE TITLE
we see some additional statements apart from what we are using during perf tests

### ISSUE THREAD

**Issue by kswathihs** [cockroachdb/cockroach#35598]
**we are doing inserts but in the graph we also found select queries **

is it any backend queries cockroach runs for consistency?
- also it is seen that tps is impacted whenever there are more selects
<img width="997" alt="consistencychecker" src="https://user-images.githubusercontent.com/44799888/54119048-70928600-441a-11e9-8707-7cc383b55730.png">
<img width="971" alt="metricsdb-1" src="https://user-images.githubusercontent.com/44799888/54119052-725c4980-441a-11e9-8e40-763046a94dbb.png">
<img width="978" alt="sqlQueries" src="https://user-images.githubusercontent.com/44799888/54119055-72f4e000-441a-11e9-99fd-e970a5130557.png">

statements page show:
<img width="1349" alt="statementspage" src="https://user-images.githubusercontent.com/44799888/54119146-ae8faa00-441a-11e9-8733-5fd354230e8b.png">

- I mostly seek information: data, general advice, clarification.
what are those select queries?

**Comment by jordanlewis** [comment]
What happens when you click on the `SELECT` statement in the statements page?

**Comment by piyush-singh** [comment]
Closing this issue due to a lack of an update. If this is still an issue, we're happy to help triage - we'll need to collect a bit more information before we can help troubleshoot, however.
