### ISSUE TITLE
`LeaderLease` not idempotent; `TestAcquireLeaderLease` flaky

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#3561]
When a store extends its lease on a range, we backdate the start of the lease so there is no gap between the old lease and the new one. However, if the same lease request is retried, it will update the lease without this backdating, recreating the gap. This makes `TestAcquireLeaderLease` flaky (since it verifies the start time of the lease), and was discovered in #3528 (but looks unrelated to that change).

Details:
1. The `testContext` is started with a manual clock and immediately acquires a lease on the first range (for gossip) with start time 0 and expiration time 1 (all times in seconds since epoch; ignoring logical ticks)
2. The test advances the clock to 1.0001, expiring the initial lease. 
3. A new request is issued at timestamp 1.0001, which causes a lease request for 1.0001 - 2.0001
4. The lease request is granted, with the start time backdated to the initial lease's expiration, 1.0000 - 2.0001
5. The lease is occasionally retried (it's unclear exactly why but it's rare and timing-related). In this case the existing lease's expiration is in the future, so it doesn't backdate the start time. The requested lease 1.0001 - 2.0001 overwrites the existing lease for 1.0000-2.0001. 

We don't use the lease start time for much, so it's unclear whether this causes any problems aside from this one test.

**Comment by tschottdorf** [comment]
possibly related: https://github.com/cockroachdb/cockroach/issues/2728
