### ISSUE TITLE
sql: go 1.12 makes tests fail in sqlbase

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#35636]
Running `make test PKG=./pkg/sql/sqlbase` with go 1.12 on my machine:

```
--- FAIL: TestEncDatumSize (0.00s)
    encoded_datum_test.go:656: on {0 [] 1.23E+4}        received 104, expected 136
    encoded_datum_test.go:656: on {0 [44 3 46 0] 1.23E+4}       received 108, expected 140
    encoded_datum_test.go:668: on [{0 [136] <nil>} {1 [135 132] <nil>} {0 [247 48 57] <nil>} {0 [] 123} {0 [246 123] 123} {0 [4] <nil>} {1 [3 63 161 63 255 255 255 255 255] <nil>} {0 [] 123.0} {0 [5 64 94 192 0 0 0 0 0] 123.0} {0 [39] <nil>} {1 [34 252 209 0] <nil>} {0 [] 1.23E+4} {0 [44 3 46 0] 1.23E+4} {0 [18 0 1] <nil>} {1 [19 206 205 204
 29 115 103 255 254] <nil>} {0 [] '12'} {0 [18 49 50 51 52 0 1] '12345'} {0 [20 249 91 50 40 104 136] <nil>} {0 [20 249 91 50 40 116 248 52 191 21] <nil>}]     received 1191, expected 1255

```

**Comment by petermattis** [comment]
The first two errors are due to an enc datum contain a decimal being 32 bytes smaller than expected. The third error is just a side-effect of the previous errors that the total encoded size of all of the enc datums is 64 bytes smaller than expected. I haven't tracked down where the difference is coming from yet, but should be easy to figure out.

**Comment by petermattis** [comment]
On go1.11, the `apd.Decimal.Coeff.Bits()` slice has capacity 5. On go1.12 it has capacity 1. Seems like this a change to the allocator behavior. I'm going to dig further to see exactly where this change occurred, but right now this failure seems innocuous.

**Comment by petermattis** [comment]
Tracked the difference down to https://github.com/golang/go/commit/bfc54bb6f3971346e184fcf3915dd17486db51c7. I'll get around to fixing the test today or tomorrow, but there is nothing to be concerned about here.
