### ISSUE TITLE
stats: CREATE STATS should support options used by auto stats

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#35641]
Currently `CREATE STATISTICS` special-cases the statistic name and if it is` __auto__` then it behaves differently (e.g. throttling).

Instead, we should extend `CREATE STATISTICS` to support these options. Syntax could be similar to `CONFIGURE ZONE USING` which accepts a list of `option = value`.

**Comment by rytaft** [comment]
@RaduBerinde was this fixed by #36069?

**Comment by RaduBerinde** [comment]
Yes, thanks. There are still a few differences (one-job-at-a-time check, plus some cosmetic differences) but I think those are fine for now.
