### ISSUE TITLE
build: Revive homebrew builds

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#35657]
The `cockroach` package in `homebrew-core` cannot currently be built from source, because homebrew's policy forbids pinned dependencies and therefore builds with go 1.12. This fails due to #35637. It is unlikely that we will get these issues resolved in time to support go 1.12 for the release of 19.1. Therefore, we need to either
- Lobby for an exception from `homebrew-core` to let us continue building with go 1.11 (and implement this policy, which I think includes building a brew package for go 1.11 that can coexist with the package for latest stable go).
- Go back to our custom tap (https://github.com/cockroachdb/homebrew-cockroach) so that we can control the build (which could include just downloading our official release binaries instead of building from source in a brew environment).

**Comment by petermattis** [comment]
Now that https://github.com/cockroachdb/cockroach/pull/35789 is merged, is there anything to do here?

**Comment by bdarnell** [comment]
There are two remaining issues in #35637: an insignificant test failure #35792 and homebrew/homebrew-core#37788, in which the go linker crashes while building cockroach. I don't think we have any understanding of the latter yet; we haven't seen it outside of homebrew's CI environment (when building for old versions of macos?). This seems unlikely to be our fault but it's still a blocker for new releases in homebrew. We should try again to see if go 1.12.1 fixed it.

**Comment by jseldess** [comment]
@bdarnell, shouldn't this be flagged as a `known-limitation`?

**Comment by bdarnell** [comment]
Yeah. It was originally flagged as a release blocker, but now we're downgrading it to a known limitation for the first few weeks (probably) of 19.1.

**Comment by jseldess** [comment]
Documented this is a 19.1 known limitation in https://github.com/cockroachdb/docs/pull/4576.

**Comment by knz** [comment]
Some movement on this: https://github.com/cockroachdb/cockroach/issues/35637#issuecomment-493776331

**Comment by bdarnell** [comment]
Homebrew only accepts packages under an OSI-approved license. Now that we've relicensed to the BSL+CCL, CockroachDB 19.2 will no longer qualify for inclusion in `homebrew-core`. We'll have to go back to our own "tap". We had this before (https://github.com/cockroachdb/homebrew-cockroach), so we'll just have to revive this and deprecate `brew install cockroach`.

**Comment by kenliu** [comment]
Hi @bdarnell this issue was carried over from 19.1 into 19.2. I came across this while tidying up the dev infra backlog and was wondering if this is something you were planning to work on for 19.2 or if this is something that dev infrastructure team need to work into our planned backlog.

**Comment by bdarnell** [comment]
I was hoping to nerd-snipe someone into it but would do it if I have to. It's critical for 19.2 because the licensing change means that we will not be able to update our current homebrew package for that version.

**Comment by kenliu** [comment]
Thanks for clarifying the level of importance. I'm labeling this as `S-2` to mark it as high priority even though it doesn't impact users in the way we normally would think about it.
