### ISSUE TITLE
sql: add memory monitoring to backfiller

### ISSUE THREAD

**Issue by lucy-zhang** [cockroachdb/cockroach#35665]
Memory monitoring should be added/configured for the backfiller for columns and indexes.

Related to #34901.

**Comment by lucy-zhang** [comment]
Also removing this from SQL Schema tracking since it seems purely backfill-related, but we could reevaluate.

**Comment by ajwerner** [comment]
Closed by https://github.com/cockroachdb/cockroach/pull/54692. cc @adityamaru
