### ISSUE TITLE
cli/sql: "failed to create statistics" errors printed in SQL shell (demo?)

### ISSUE THREAD

**Issue by lucy-zhang** [cockroachdb/cockroach#35668]
Automatic stats failures, including failures that seem harmless (e.g., due to a table being dropped), get logged to the SQL shell as errors at the default verbosity/logging level, which is potentially confusing. For instance:

```
E190312 01:57:34.138556 970 sql/stats/automatic_stats.go:411  failed to create statistics on table 52: create-stats: table is being dropped
```

**Comment by knz** [comment]
I think this is only true of `cockroach demo`, isn't it?

If so, I recommend to modify the `cockroach demo` initialization code to set up the in-memory demo cluster with stats disabled.

**Comment by knz** [comment]
cc @rytaft @jordanlewis

**Comment by knz** [comment]
Additionally, this particular log message should be turned into a warning. It's not really an error.

**Comment by lucy-zhang** [comment]
You're right: I was actually in `cockroach demo`, not `cockroach sql`.

I agree that this log message makes more sense as a warning. Maybe that's all that needs to be done (since running automatic stats in `demo` is itself fine), so feel free to close this issue for being trivial.

**Comment by knz** [comment]
I think turning the error into a warning is what's needed, because `cockroach demo` hides warnings by default. let's have the PR that does this fix this issue, no need to close it preemptively.
