### ISSUE TITLE
backupccl: investigate turning off time-bound iterator

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#35671]
As discovered recently during a customer investigation, full backups seem to be using time-bound iterators, which was never the intention. This is happening because https://github.com/cockroachdb/cockroach/blob/6be06f2c6dc6d70885e7b6165403a3772dd3cf89/pkg/ccl/storageccl/engineccl/mvcc.go#L89 unconditionally `Next`s the start timestamp. Instead, `Next` should only be called if the start time is non-empty.

Separately, we should consider disabling time-bound iterators for incremental backup. We recently made the decision to stop using the in changefeeds because we don't trust the correctness. Several bugs have been patched or worked around, but no-one seems to be convinced that there aren't more bugs lurking. In fact, there may be an issue in a workaround for a previous bug (#34819).

In theory time-bound iterators are perfect for incremental backup. In practice, most workloads will see a lot of compactions in any reasonable period for running backups (>1h), reducing the effectiveness. Certainly, it's easy to construct a worst case of a very large, almost static dataset, but that has to be balanced against the utmost importance of correctness in a backup system.

I reran some of the initial measurements of time-bound iterator impact on incremental backup. I installed tpcc-1000 on a 3 node n1-standard-16 cluster, then ran a full backup, then ran load for 1 hour, noting the time T. With load running, I ran 6 incremental backups from T alternating between tbi and no-tbi.

tbi incremental backup runtimes: 3m45s,3m56s,4m6s
no-tbi incremental backup runtimes: 6m45s,6m27s,6m48s

Here are selected graphs during that time. The beginning of the hour is the alternating incremental backups and the end is another full backup (which I ran for comparison). You can most clearly see the durations of the 6 inc + 1 full backups in the network graph. The order was tbi, no-tbi, tbi, no-tbi, tbi, no-tbi. There are some peaks and valleys in the latency percentiles, but they don't really line up with the backups, so I think they're noise. I've cancelled the full backup and am going to get some more screenshots with a baseline.

<img width="986" alt="Screen Shot 2019-03-12 at 3 48 20 PM" src="https://user-images.githubusercontent.com/52528/54241525-7a7dbd00-44de-11e9-98bc-6f826e563515.png">
<img width="988" alt="Screen Shot 2019-03-12 at 3 48 27 PM" src="https://user-images.githubusercontent.com/52528/54241526-7a7dbd00-44de-11e9-8264-ae140e433708.png">
<img width="985" alt="Screen Shot 2019-03-12 at 3 48 36 PM" src="https://user-images.githubusercontent.com/52528/54241527-7a7dbd00-44de-11e9-9f26-3f6a57cf5022.png">
<img width="996" alt="Screen Shot 2019-03-12 at 3 49 01 PM" src="https://user-images.githubusercontent.com/52528/54241528-7a7dbd00-44de-11e9-85e2-9d5023c53080.png">
<img width="990" alt="Screen Shot 2019-03-12 at 3 49 22 PM" src="https://user-images.githubusercontent.com/52528/54241529-7a7dbd00-44de-11e9-92b3-f11a5315e980.png">

**Comment by danhhz** [comment]
No backups running as of 22:50:30. Running any kind of backups clearly has an impact on latencies, but it's not clear to me that anything lines up with tbi vs no-tbi.

<img width="1003" alt="Screen Shot 2019-03-12 at 4 11 30 PM" src="https://user-images.githubusercontent.com/52528/54242356-86b74980-44e1-11e9-956d-b56fab5b7deb.png">
<img width="994" alt="Screen Shot 2019-03-12 at 4 11 13 PM" src="https://user-images.githubusercontent.com/52528/54242355-86b74980-44e1-11e9-940e-dfd981e58081.png">

**Comment by danhhz** [comment]
Oh! Here's the times of the actual backups. I realized there's one more in the graphs (a warmup one stuck in my screenshots), so it actually goes no-tbi, tbi, no-tbi, tbi, no-tbi, tbi, no-tbi, full. Maybe I actually can see a small correlation in increased latencies during the no-tbi ones.

```
              started              |             finished
+----------------------------------+----------------------------------+
  2019-03-12 21:47:04.919498+00:00 | 2019-03-12 21:54:37.935103+00:00
  2019-03-12 21:55:24.618205+00:00 | 2019-03-12 21:59:10.393316+00:00
  2019-03-12 21:59:21.524601+00:00 | 2019-03-12 22:06:07.236267+00:00
  2019-03-12 22:06:22.767007+00:00 | 2019-03-12 22:10:19.105245+00:00
  2019-03-12 22:10:43.104254+00:00 | 2019-03-12 22:17:10.633235+00:00
  2019-03-12 22:17:52.865208+00:00 | 2019-03-12 22:21:59.533304+00:00
  2019-03-12 22:30:48.803659+00:00 | 2019-03-12 22:37:37.20894+00:00
  2019-03-12 22:38:06.307097+00:00 | 2019-03-12 22:50:30.150053+00:00
```

**Comment by nvanbenschoten** [comment]
In my opinion, the effect on foreground traffic doesn't seem pronounced enough for us to risk correctness in the upcoming release. My only real concern from these tests is:
```
tbi incremental backup runtimes: 3m45s,3m56s,4m6s
no-tbi incremental backup runtimes: 6m45s,6m27s,6m48s
```

So we're seeing roughly a 2x hit to backup time. Is that something customers will care about? Will we have trouble explaining why their backups suddenly started taking twice as long when they upgraded?

**Comment by danhhz** [comment]
My guess is that this could be handled with docs, but I'd be interested in what @rolandcrosby thinks.

**Comment by rolandcrosby** [comment]
I'd like to get some more data about incremental backup usage before okaying this. If most users are spacing out their backups by >1h I'll be more comfortable with the change, but I worry that we may have users who incrementally back up more frequently than that. I'll see if I can get the reg data this afternoon.

**Comment by rolandcrosby** [comment]
^ Closing the loop on this, it doesn't look like we have a large number of clusters that run `BACKUP` more frequently than once an hour, so I endorse the plan of disabling TBI here for 19.1.
