### ISSUE TITLE
sql: Connection reset by peer while performing bulk inserts

### ISSUE THREAD

**Issue by vasantivmahajan** [cockroachdb/cockroach#35699]
Trying to perform a bulk insert for a very large dataset, where every query has around 10000 records to be inserted. Only the first batch of 10000 records is successfully inserted and then the error ` write: connection reset by peer` is incurred. Tried playing around with the batch size, but after a particular cap amount, the same error occurs again. How can this issue be resolved?

**Comment by tim-o** [comment]
@vasantivmahajan - can you give us a couple more details about the cluster?

- What version are you running?
- How many nodes are in the cluster?
- How is each node provisioned?
- What's the DDL for the table?

**Comment by andkononov** [comment]
@tim-o Let me answer:
1. Version 2.1.5
2. there are 3 nodes
3. The nodes provisioned in GCP and use secure profile
4. The table was created with `CREATE TABLE`

**Comment by tim-o** [comment]
@andkononov - thanks! I'm looking for the actual table itself, i.e. the output of `SHOW CREATE TABLE`. The names don't matter, I just need to know the data types, indexes / foreign keys, and the shape of the data.

it'd also be helpful to know the GCP machine type, and the logs from the cluster when it's at rest and healthy. You can collect these easily using [cockroach debug zip](https://www.cockroachlabs.com/docs/stable/debug-zip.html).

**Comment by andkononov** [comment]
@tim-o Seems We find the issue around the our application code, but I still cannot understand why I am unable to make only 10k-20k (the real limit is somewhere between) inserts per one transaction, as far as I know in cockroach 1.x was hardcoded limit for 100K insertions per transaction and in 2.x it was removed. May be you can suggest some cluster settings to increase this limitation?
PS I will attach table scheme and logs a little bit later.

**Comment by damienhollis** [comment]
@andkononov Cockroach changed from a row limit to a size limit.  The cluster setting is kv.transaction.max_intents_bytes, see this page https://www.cockroachlabs.com/docs/stable/cluster-settings.html

**Comment by andkononov** [comment]
@damienhollis seems it works in weird manner because I have following cluster setting:
``` kv.transaction.max_intents_bytes                     | 50000000000 |```
but my insertion data set is only:
```-rw-rw-r-- 1 ubuntu ubuntu 19M Mar 13 21:19 data/2-ds.sql```

**Comment by tim-o** [comment]
@andkononov thanks for clarifying. What's the CREATE TABLE statement for the table where you're encountering this error?

**Comment by twpayne** [comment]
I'm seeing this same error, also at 10000 inserts in batches of 1000 inside a single transaction against a local instance of the open source Cockroach binary running on my machine.

My table is:

```sql
CREATE TABLE IF NOT EXISTS pairs (
	key BYTEA PRIMARY KEY,
	value BYTEA NOT NULL
);
```

Keys are 64 bytes (SHA256 sums) and values are arbitrary byte values, typically 200B-2KB in size, although the largest is 5MB in size.

My insert statement is:

```sql
INSERT INTO pairs (key, value)
VALUES
	($1, $2),
	($3, $4),
	/* ...*/
	($1999, $2000)
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;
```

I do ten inserts inside a transaction. The connection reset occurs during execution of the last `INSERT`, not on the transaction's `COMMIT`.

The connection reset error is reliable. I have tried disabling replication but this has no effect - I still get the connection reset.

The inserts are happening from Go, using the `github.com/lib/pq` driver.

Please let me know if you would like exact code to replicate the problem.

**Comment by tim-o** [comment]
@twpayne an exact repro case is always appreciated, if you have code to share.

**Comment by twpayne** [comment]
Ack, will post.

For info, I did more digging and if I transfer less data (by truncating the values to zero in my case) then the insert succeeds. I think I'm hitting the max command size limit, although the connection reset is pretty brutal way of reporting the error :)

**Comment by twpayne** [comment]
@tim-o here is some test code that reliably reproduces the problem: https://gist.github.com/twpayne/7da8892eed03d948464671a51949e7e9.

This attempts to insert 10,000 key/value pairs with short keys and 16KB values in 10 batches of 1000. You can change these values at the top of the `TestCockroachDBBulkInsert` function.

To run it:

```sh
$ cockroach start --insecure --listen-addr=localhost &
$ echo "CREATE DATABASE testdb;" | psql -h localhost -p 26257 -U root
$ go test . # in the directory containing main_test.go from the gist
```

I reliably get:

```text
$ go test .
--- FAIL: TestCockroachDBBulkInsert (0.20s)
    require.go:794: 
                Error Trace:    main_test.go:94
                Error:          Received unexpected error:
                                write tcp 127.0.0.1:48700->127.0.0.1:26257: write: connection reset by peer
                Test:           TestCockroachDBBulkInsert
FAIL
FAIL    github.com/twpayne/go-experiments/cockroach-drop-connection     0.210s
```

This is CockroachDB's output on startup:

```
$ cockroach start --insecure --listen-addr=localhost 
*
* WARNING: RUNNING IN INSECURE MODE!
* 
* - Your cluster is open for any client that can access localhost.
* - Any user, even root, can log in without providing a password.
* - Any user, connecting as root, can read or write any data in your cluster.
* - There is no network encryption nor authentication, and thus no confidentiality.
* 
* Check out how to secure your cluster: https://www.cockroachlabs.com/docs/v2.1/secure-a-cluster.html
*
CockroachDB node starting at 2019-04-03 11:39:00.603227811 +0000 UTC (took 1.5s)
build:               CCL v2.1.6 @ 2019/03/04 23:21:07 (go1.10.7)
webui:               http://localhost:8080
sql:                 postgresql://root@localhost:26257?sslmode=disable
client flags:        cockroach <client cmd> --host=localhost:26257 --insecure
logs:                /home/twp/cockroach-data/logs
temp dir:            /home/twp/cockroach-data/cockroach-temp823704405
external I/O path:   /home/twp/cockroach-data/extern
store[0]:            path=/home/twp/cockroach-data
status:              restarted pre-existing node
clusterID:           a06e14da-c0dd-4e03-b90e-9faeaf6e417c
nodeID:              1
```

You can run the test against a different instance of CockroachDB or PostgreSQL using the `-dsn` option, for example:

```
$ go test . -dsn "postgres://testuser:testpassword@localhost/testdb?sslmode=disable"
ok      github.com/twpayne/go-experiments/cockroach-drop-connection     24.135s
```

Please let me know if you need any more info.

**Comment by twpayne** [comment]
Note that I still get the connection reset error if I set `kv.transaction.max_intents_bytes` and `kv.transaction.max_refresh_spans_bytes` to be twice the amount of raw data that I'm inserting:

```
testdb=# SET CLUSTER SETTING kv.transaction.max_intents_bytes = 2*10*1000*16384;
SET CLUSTER SETTING
testdb=# SET CLUSTER SETTING kv.transaction.max_refresh_spans_bytes = 2*10*1000*16384;
SET CLUSTER SETTING
testdb=# SHOW CLUSTER SETTING kv.transaction.max_intents_bytes;
 kv.transaction.max_intents_bytes 
----------------------------------
                        327680000
(1 row)

testdb=# SHOW CLUSTER SETTING kv.transaction.max_refresh_spans_bytes;
 kv.transaction.max_refresh_spans_bytes 
----------------------------------------
                              327680000
(1 row)

```

**Comment by twpayne** [comment]
If I try to insert 10,000 pairs using the above test code one by one, i.e.

```
	batchSize := 1
	numBatches := 10000
	valueSize := 16 * 1024
```

On inserting the 8182nd pair, I get the error:

```
--- FAIL: TestCockroachDBBulkInsert (84.78s)
    require.go:794: 
        	Error Trace:	main_test.go:96
        	Error:      	Received unexpected error:
        	            	pq: split failed while applying backpressure: could not find valid split key
        	Test:       	TestCockroachDBBulkInsert
FAIL
FAIL	github.com/twpayne/go-experiments/cockroach-drop-connection	84.789s
```

After this, all attempts at inserting fail with the same error.

**Comment by jordanlewis** [comment]
Thanks for this very nice reproduction case!

**Comment by fmzquant** [comment]
I have the same problem when inserting multiple data with one SQL statement

**Comment by knz** [comment]
we've worked on large transactions since this was filed.
If there are new symptoms, please file a new issue
