### ISSUE TITLE
Connection reset by peer while performing bulk inserts

### ISSUE THREAD

**Issue by vasantivmahajan** [cockroachdb/cockroach#35696]
Trying to perform a bulk insert for a very large dataset, where every query has around 10000 records to be inserted. Only the first batch of 10000 records is successfully inserted and then the error write: connection reset by peer is incurred. Tried playing around with the batch size, but after a particular cap amount, the same error occurs again. How can this issue be resolved?

**Comment by tim-o** [comment]
Closing in favor of #35699
