### ISSUE TITLE
opt: subqueries in ON conditions can get duplicated, executing mutations twice

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#35709]
```
root@127.0.0.1:63531/defaultdb> select * from w;
  q
+---+
(0 rows)

Time: 720µs

root@127.0.0.1:63531/defaultdb> select * from x inner join y on (select true from [insert into w values (1) returning 1]);
  a | b
+---+---+
  1 | 1
(1 row)

Time: 2.555ms

root@127.0.0.1:63531/defaultdb> select * from w;
  q
+---+
  1
  1
(2 rows)

Time: 661µs
```

What's happening is that `PushFilterIntoJoinLeftAndRight` is recognizing that the `ON` condition is bound by both sides of the join, and is duplicating it. I'm not sure if this causes problems in general but this here is a violation. We can either fix this by waiting for `With`, or by blocking `PushFilterIntoJoinLeftAndRight` from pushing down expressions with mutations. My preference is to fix this via `With`.

Jira issue: CRDB-4563

**Comment by RaduBerinde** [comment]
I agree that `With` work will fix mutation statements inside subqueries. But I think there are other sketchy cases, e.g. subqueries involving `nextval`. I am skeptical of allowing duplication, for example the transformation explicitly allowed in this comment doesn't seem acceptable to me: https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/opt/props/logical.go#L147
@andy-kimball do you remember of any specific reasons for allowing duplication of side-effecting expressions?

**Comment by andy-kimball** [comment]
If I remember correctly, Postgres' policy allows duplication of side-effecting expressions. However, they may or may not do it in any particular case (they don't duplicate in this particular case).

I'm open to modifying our policy, as long as we can state the rules simply and without ambiguity. The original idea was to give the optimizer as much freedom as possible, while giving the users tools (`WITH` and `CASE`) to force certain duplication/elimination/ordering behavior when needed.

In a case like this:
```
SELECT * FROM xy, xz WHERE xy.y=xz.z AND xy.y=nextval('foo');
```
Postgres does not duplicate in this case. But it does push down the `nextval` expression, which could change the number of times it's evaluated, which would change the results of the query. So where is the line? Why is duplicating expressions not OK but eliminating/reordering them is OK? Won't different users have different ideas about the "right" way to execute that query? To try and conform to one person's intuitions is likely to saddle us with a set of heuristics that will conflict with another person's intuitions.

**Comment by andy-kimball** [comment]
@RaduBerinde, here's the issue we were talking about the other day.

**Comment by jordanlewis** [comment]
No longer repros:

```
demo@127.0.0.1:26257/defaultdb> create table w (q int);
CREATE TABLE


Time: 14ms total (execution 13ms / network 0ms)

demo@127.0.0.1:26257/defaultdb> create table x (x int);
CREATE TABLE


Time: 6ms total (execution 6ms / network 0ms)

demo@127.0.0.1:26257/defaultdb> create table y (y int);
CREATE TABLE


Time: 6ms total (execution 6ms / network 0ms)

demo@127.0.0.1:26257/defaultdb> select * from x inner join y on (select true from [insert into w values (1) returning 1]);
  x | y
----+----
(0 rows)


Time: 15ms total (execution 15ms / network 0ms)

demo@127.0.0.1:26257/defaultdb> select * from w;
  q
-----
  1
(1 row)
```
