### ISSUE TITLE
sqlsmith: make crasher simplifier

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#35718]
Queries like the one in #35715, while hilarious, are a pain to test because the person debugging them needs to manually simplify the query to figure out what is going on.

We should make a tool that can automatically prune down a query to a minimal (or close) repro by making small changes and validating that they still cause a crash. This is tricky because the transformations must keep the entire tree valid. For instance, it's not valid to remove a column from a `VALUES` clause in isolation, since operators further up the tree might be making use of it.

In a perfect world, I think what this means is that such simplifications must be top-down: an operator higher up in the tree requests a simplified form of one of its inputs by eliminating a column from its output, and this simplification travels down the tree until the column can be pruned at its source.

That said I think we could get some easy wins without doing something complicated like that:
* Try removing rows from `VALUES` clauses. This is probably the easiest simplification we could do and would yield huge benefits, since big `VALUES` clauses are a big part of sqlsmith queries.
* Try replacing set operations with either their left or right side. This is an easy transformation since it doesn't change the signature of the set op.
* Replace `CASE` expressions with one of their arms. These are also a big part of what makes the queries so big.
* Replace some of the funky randDatum constants with simpler constants like `1` or `''`.
* Replace `INSERT...RETURNING` statements with selects.
* Inline `WITH`s.

**Comment by jordanlewis** [comment]
@mjibson closable right?
