### ISSUE TITLE
sql: 1ns treated like 0 in cluster settings

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#35732]
Not only is zero displayed, it appears to be treated like zero. The consistency queue stopped doing any work (as it would when zero is specified). Setting it to 1s worked as expected.

```
root@127.0.0.1:60495/defaultdb> select value from [ show all cluster settings ] where variable LIKE '%consis%';
   value
+---------+
  24h0m0s
(1 row)

Time: 1.324ms

root@127.0.0.1:60495/defaultdb> set cluster setting server.consistency_check.interval = '1ns';
SET CLUSTER SETTING

Time: 3.985ms

root@127.0.0.1:60495/defaultdb> select value from [ show all cluster settings ] where variable LIKE '%consis%';
  value
+-------+
  0s
(1 row)

Time: 1.094ms
```

PS if this is some technical limitation, I'm ok with that, but it should return an error. The behavioral change between `1ns` and `0` is often dramatic.

**Comment by knz** [comment]
@mjibson @ajwerner I think you changed this recently. Can you add the adequate stopgap to prevent silent failures here? thx

**Comment by ajwerner** [comment]
I don't know much about the precision change so I defer to @mjibson.

**Comment by mjibson** [comment]
This happened when we removed nanos from intervals. `1us` is now the smallest we can recognize. I think we (cockroach employees) need to retrain ourselves to use `1us` instead of `1ns` for anything like this.

But it also might be possible to do something that can recognize when a non-zero input is rounded down to 0.

**Comment by knz** [comment]
@mjibson I remember you wanted to remove the go parsing for intervals and only support the pg syntax. I believe this would solve the issue, because then the syntax `1ns` would simply not be supported any more. What do you think?

**Comment by tbg** [comment]
I think this was already fixed, shortly after I filed it:

```
root@127.0.0.1:62429/defaultdb> set cluster setting server.consistency_check.interval = '1ns';
pq: could not parse "1ns" as type interval: interval: unknown unit "ns" in duration "1ns"
```

**Comment by knz** [comment]
Oh well perfect then. Thanks for checking.
