### ISSUE TITLE
bulkio: show jobs for restore doesn't show parameters in string

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#35733]
I was attempting to restore registration data to another cluster:
```
root@cockroachdb-public:26257/registration> RESTORE TABLE registration.* FROM 's3://----/2019-03-13'
                                         -> ;
pq: failed to read backup descriptor: s3 uri missing "AWS_ACCESS_KEY_ID" parameter
```

I'd used this because I had seen this output from show jobs before:

```
show jobs;
        job_id       | job_type |                                description                                | user_name | status  | running_status |             created              |             started              | finished |             modified             |  fraction_completed  | error | coordinator_id
+--------------------+----------+---------------------------------------------------------------------------+-----------+---------+----------------+----------------------------------+----------------------------------+----------+----------------------------------+----------------------+-------+----------------+
  434170667416453121 | RESTORE  | RESTORE TABLE registration.* FROM 's3://----/2019-03-13' | root      | running | NULL           | 2019-03-14 13:06:12.624663+00:00 | 2019-03-14 13:06:12.648268+00:00 | NULL     | 2019-03-14 13:06:45.682243+00:00 | 0.012368377298116684 |       |              1
(1 row)

Time: 9.893042ms
```
I would expect show jobs to print something like `RESTORE TABLE registration.* FROM 's3://---/2019-03-13*AWS_ACCESS_KEY_ID=_&AWS_SECRET_ACCESS_KEY=_`

I also found the docs confusing:
https://www.cockroachlabs.com/docs/v2.1/restore.html#backup-file-urls
because it doesn't show the example right away and there wasn't a link to an example for aws. However, if you click the azure link you get to the aws example https://www.cockroachlabs.com/docs/v2.1/restore.html#example-file-urls

**Comment by rolandcrosby** [comment]
This would be a nice little UX fix for any URLs that contain sensitive parameters. Thanks for reporting, Andy.

**Comment by rolandcrosby** [comment]
we should mask the values for all parameters whenever we end up introducing this.

**Comment by dt** [comment]
44737
