### ISSUE TITLE
backupccl: Add a no-wait option to BACKUP command

### ISSUE THREAD

**Issue by bobvawter** [cockroachdb/cockroach#35748]
Customers using client APIs that don't offer a non-blocking interface, e.g. JDBC, must wait for the job to complete.  It would be nice if the `BACKUP` syntax supported a `NOWAIT` option which would make the command return once the job has been scheduled.

**Comment by gigatexal** [comment]
I wanted to add my support for this too!

**Comment by dt** [comment]
Dupe: #35048
