### ISSUE TITLE
sql: SHOW ZONE CONFIGURATION FOR TABLE <table_name> PARTITION <partition_name> doesn't work

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#35756]
**Describe the problem**

I partitioned a table, created replication zones for the partition, viewed one of the replication zones with the `SHOW ZONE CONFIGURATION FOR PARTITION <partition_name> OF TABLE <table_name>` syntax (this worked), and then tried to do the same thing with the `SHOW ZONE CONFIGURATION FOR TABLE <table_name> PARTITION <partition_name>` syntax (didn't work).

**Cockroach version**

```
~$ cockroach version
Build Tag:    v2.2.0-alpha.20190211-100-g10f8010fa5-dirty
Build Time:   2019/02/13 03:42:25
Distribution: CCL
Platform:     darwin amd64 (x86_64-apple-darwin17.7.0)
Go Version:   go1.11
C Compiler:   4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.10.44.4)
Build SHA-1:  10f8010fa5778e740c057905e2d7664b5fd5d647
Build Type:   development
```

**To Reproduce**

1. Start up a local cluster.

2. Open the SQL shell.

3. Set an enterprise license.

4. Create a database:

```
CREATE DATABASE roachlearn;
```

5. Create a table with partitions:

```
CREATE TABLE roachlearn.students (
    id INT DEFAULT unique_rowid(),
    name STRING,
    email STRING,
    country STRING,
    expected_graduation_date DATE,   
    PRIMARY KEY (country, id))
    PARTITION BY LIST (country) (
      PARTITION north_america VALUES IN ('CA','US'),
      PARTITION europe VALUES IN ('DE', 'CH'),
      PARTITION australia VALUES IN ('AU','NZ'),
      PARTITION DEFAULT VALUES IN (default)
    );
```

6. Create replication zones for partitions:

```
ALTER PARTITION north_america OF TABLE roachlearn.students     CONFIGURE ZONE USING constraints='[+region=us]';

ALTER PARTITION europe OF TABLE roachlearn.students     CONFIGURE ZONE USING constraints='[+region=de]';
ALTER PARTITION australia OF TABLE roachlearn.students     CONFIGURE ZONE USING constraints='[+region=aus]';
```

7. View the replication zone for one of the partitions:

```
SHOW ZONE CONFIGURATION FOR PARTITION north_america OF TABLE roachlearn.students;
              zone_name             |                                           config_sql
+-----------------------------------+------------------------------------------------------------------------------------------------+
  roachlearn.students.north_america | ALTER PARTITION north_america OF INDEX roachlearn.public.students@primary CONFIGURE ZONE USING
                                    |     range_min_bytes = 16777216,
                                    |     range_max_bytes = 67108864,
                                    |     gc.ttlseconds = 90000,
                                    |     num_replicas = 3,
                                    |     constraints = '[+region=us]',
                                    |     lease_preferences = '[]'
(1 row)
```

8. Try to use an alternative syntax to view the replication zone:

```
SHOW ZONE CONFIGURATION FOR TABLE roachlearn.students PARTITION north_america;
  zone_name |                config_sql
+-----------+------------------------------------------+
  .default  | ALTER RANGE default CONFIGURE ZONE USING
            |     range_min_bytes = 16777216,
            |     range_max_bytes = 67108864,
            |     gc.ttlseconds = 90000,
            |     num_replicas = 3,
            |     constraints = '[]',
            |     lease_preferences = '[]'
(1 row)
```

**Comment by nvanbenschoten** [comment]
I ran into this as well. The issue is that `generateZoneConfigIntrospectionValues` blindly prints out the `ZoneSpecifier` here: https://github.com/cockroachdb/cockroach/blob/01c915265aacdd07738591831af1b24ec82fa2fe/pkg/sql/show_zone_config.go#L183

This can result in `RANGE`, `DATABASE`, `INDEX`, or `TABLE` specifiers.

However, we can only parse `ALTER PARTITION ... OF TABLE`: https://github.com/cockroachdb/cockroach/blob/01c915265aacdd07738591831af1b24ec82fa2fe/pkg/sql/parser/sql.y#L1359

So the solution seems to be one of:
1. always print the `ZoneSpecifier` in a `ALTER PARTITION ... OF TABLE` format
2. parse all forms of `ZoneSpecifier`s in the `alter_zone_table_stmt` target

cc. @knz

**Comment by knz** [comment]
Oy that is a serious oversight. Thanks for spotting it!

**Comment by knz** [comment]
There were actually 4 separate bugs. Fixing in #36868.
