### ISSUE TITLE
opt: failed automatic stats attempts on JSON columns with inverted index

### ISSUE THREAD

**Issue by lucy-zhang** [cockroachdb/cockroach#35764]
I had a table with a JSON column where the automatic stats runs were all successful. After adding an inverted index to the column, the automatic stats run that happens after a schema change attempted to compute stats for the JSON column and failed with a `unable to encode table key: *tree.DJSON` error, similarly to #35150. Subsequent runs (which may have been retries of the first one that failed?) also failed with the same error. When I dropped the index, the resulting automatic stats run was successful again.

I took a quick look, and I'm not sure why #35212 doesn't cover this. When I try to manually add statistics to the JSON column with the inverted index, I do get the correct error (`CREATE STATISTICS is not supported for JSON columns`).

**Comment by knz** [comment]
The check is done while planning the CREATE STATS statement; no such check is present in the auto stats code.

@rytaft maybe it needs to be added there as well. 

(Also please add a link to #35844 with `pgerror.UnimplementedWithIssue...`)

**Comment by awoods187** [comment]
Good idea @knz --I think we should add this to make it easy for our users to understand what is happening.

**Comment by rytaft** [comment]
Thanks for filing this issue, @lucy-zhang!

@knz, Looks like you beat me to it on adding the issue to the existing error. Thanks for fixing that!
