### ISSUE TITLE
cannot use &memColumn literal (type *memColumn) as type Vec in assignment

### ISSUE THREAD

**Issue by jetora** [cockroachdb/cockroach#35778]
Branch:Master,
when I build from source,I got this error:

# github.com/cockroachdb/cockroach/pkg/sql/exec/coldata
pkg/sql/exec/coldata/vec.go:136:5: cannot use &memColumn literal (type *memColumn) as type Vec in assignment:
	*memColumn does not implement Vec (missing Append method)
pkg/sql/exec/coldata/vec.go:174:43: cannot use &memColumn literal (type *memColumn) as type Vec in return argument:
	*memColumn does not implement Vec (missing Append method)
pkg/sql/exec/coldata/vec.go:176:45: cannot use &memColumn literal (type *memColumn) as type Vec in return argument:
	*memColumn does not implement Vec (missing Append method)
pkg/sql/exec/coldata/vec.go:178:43: cannot use &memColumn literal (type *memColumn) as type Vec in return argument:
	*memColumn does not implement Vec (missing Append method)
pkg/sql/exec/coldata/vec.go:180:44: cannot use &memColumn literal (type *memColumn) as type Vec in return argument:
	*memColumn does not implement Vec (missing Append method)
pkg/sql/exec/coldata/vec.go:182:44: cannot use &memColumn literal (type *memColumn) as type Vec in return argument:
	*memColumn does not implement Vec (missing Append method)
pkg/sql/exec/coldata/vec.go:184:44: cannot use &memColumn literal (type *memColumn) as type Vec in return argument:
	*memColumn does not implement Vec (missing Append method)
pkg/sql/exec/coldata/vec.go:186:46: cannot use &memColumn literal (type *memColumn) as type Vec in return argument:
	*memColumn does not implement Vec (missing Append method)
pkg/sql/exec/coldata/vec.go:188:46: cannot use &memColumn literal (type *memColumn) as type Vec in return argument:
	*memColumn does not implement Vec (missing Append method)
pkg/sql/exec/coldata/vec.go:190:50: cannot use &memColumn literal (type *memColumn) as type Vec in return argument:
	*memColumn does not implement Vec (missing Append method)
pkg/sql/exec/coldata/vec.go:190:50: too many errors
# github.com/cockroachdb/cockroach/pkg/sql/lex
pkg/sql/lex/predicates.go:49:17: undefined: reservedKeywords

Compilation finished with exit code 2

**Comment by jordanlewis** [comment]
@jetora how are you building? Seems like you aren't using the Makefile. Try `make build`. And follow the CONTRIBUTING.md docs. Reopen if you have a problem again!
