### ISSUE TITLE
opt: Automatic statistics is now triggering rapidly 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#35795]
**Describe the problem**

I have a six node tpc-c cluster with 5000 warehouses loaded running tpc-c with 4000 active warehouses.

Jobs are triggering every couple of minutes:
![image](https://user-images.githubusercontent.com/22278911/54452886-86f75500-472c-11e9-9a16-6f111c20fc91.png)

**Comment by RaduBerinde** [comment]
If the tables are small (which they are since each job takes seconds) and there are frequent updates to them, this would be expected.

Maybe we should improve the threshold to be `500 + 10% of the table` so we don't have a ton of runs on small tables. I think @andy-kimball was in favor of this too. @rytaft what do you think?

**Comment by awoods187** [comment]
it's triggering so frequently that its failing concurrent jobs (which is good)

![image](https://user-images.githubusercontent.com/22278911/54453133-0d139b80-472d-11e9-89a8-5ff4e2a0920c.png)

**Comment by andy-kimball** [comment]
Here are SQL Server rules:
```
Up to SQL Server 2014 (12.x), SQL Server uses a threshold based on the percent of rows changed. This is regardless of the number of rows in the table. The threshold is:
If the table cardinality was 500 or less at the time statistics were evaluated, update for every 500 modifications.
If the table cardinality was above 500 at the time statistics were evaluated, update for every 500 + 20 percent of modifications.

Starting with SQL Server 2016 (13.x) and under the database compatibility level 130, SQL Server uses a decreasing, dynamic statistics update threshold that adjusts according to the number of rows in the table. This is calculated as the square root of the product of 1000 and the current table cardinality. For example if your table contains 2 million rows, then the calculation is  sqrt (1000 * 2000000) = 44721.359. With this change, statistics on large tables will be updated more often. However, if a database has a compatibility level below 130, then the SQL Server 2014 (12.x) threshold applies. 
```
