### ISSUE TITLE
opt: rename failed auto stats jobs due to concurrent jobs as cancelled 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#35796]
Automatic statistics jobs can be triggered so frequently that it causes two jobs to happen concurrently. We fail the second job as it is a waste of output but this can confuse the user:
![image](https://user-images.githubusercontent.com/22278911/54453241-4e0bb000-472d-11e9-8210-1d00a7453537.png)

We should instead say that the job is canceled. 

Note we are tracking reducing the frequency on concurrent jobs in https://github.com/cockroachdb/cockroach/issues/35795

Jira issue: CRDB-4556

**Comment by awoods187** [comment]
cc @celiala

**Comment by rytaft** [comment]
Still relevant.
