### ISSUE TITLE
opt: extend hints to ZigZag joins 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#35814]
We may want to offer some customers the ability to use zigzag joins for experimental purposes. If we do, we may want to force the selection of that join via hints. We can't currently do that:
```
root@localhost:26257/tpch> set experimental_enable_zigzag_join=true;
SET

Time: 593.804µs
root@localhost:26257/tpch> show experimental_enable_zigzag_join;
  experimental_enable_zigzag_join
+---------------------------------+
  on
(1 row)

Time: 1.00337ms
```
Then try with a hint:
```
root@localhost:26257/tpch> explain SELECT count(*) FROM lineitem INNER zigzag JOIN supplier ON l_suppkey = s_suppkey;
invalid syntax: statement ignored: syntax error at or near "zigzag"
DETAIL: source SQL:
explain SELECT count(*) FROM lineitem INNER zigzag JOIN supplier ON l_suppkey = s_suppkey
                                            ^
HINT: try \h <SOURCE>
```

**Comment by justinj** [comment]
This is a good idea! I think since zigzags as we support them today are an alternative to scans rather than joins, it might make sense for the syntax to be an extension of our index hint syntax rather than our join hint syntax, something like `SELECT * FROM foo@{a,b} WHERE a = 3 AND b = 7` or `SELECT * FROM foo@{ZIGZAG=foo_a_idx,foo_b_idx} WHERE a = 3 AND b = 7`.

**Comment by awoods187** [comment]
Good idea @justinj. After reviewing it more detail (https://github.com/cockroachdb/cockroach/issues/23520) it doesn't make sense to do it within the query like other hints since they do behave differently. I like the idea of extending them with the index syntax. I couldn't find an example of hints being used on zigzag joins in other DBs so we don't have the same compatibility concerns to worry about.

**Comment by rytaft** [comment]
Still relevant.
