### ISSUE TITLE
gossip: joining two initialized clusters

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#3583]
we have some checks in place to prevent a node from joining a Gossip network it doesn't belong to, but it gets more difficult when two initialized nodes happen to be put in the same Gossip network.
#3236 treats one instance of this, but an actual solution should happen on the connection level.

**Comment by bdarnell** [comment]
If we put the cluster ID in the TLS certificates, then we could validate this at the very beginning of the connection.
