### ISSUE TITLE
sql: use pg error codes / internal errors as appropriate

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#35847]
We want to use:

- pg internal errors to indicate assertion errors, so that they get automatically reported in sentry (bug reporting). **This is the most important.**
- pg error codes where appropriate, to enable clients that use them.

I have written a linter (see below) to analyze all the points where errors are produced without the machinery in `pgerror`. These need to be reviewed, and split up among the team for refactoring. There are too many for just one person to process.

```
  t.Run("TestPGErrors", func(t *testing.T) {
    t.Parallel()
    cmd, stderr, filter, err := dirCmd(
      pkgDir,
      "git",
      "grep",
      "-nE",
      `[^[:alnum:]](errors\.(New|Errorf|Wrap)|fmt\.Errorf)`,
      `--`,
      `sql`,
      `ccl`,
      `:!sql/pgwire/pgerror/*`,
      `:!*_test.go`,
      `:!*/execgen/*`,
      `:!*/optgen/*`,
      `:!*/langgen/*`,
      `:!sql/logictest/*`,
      `:!*/testutils/*`,
      `:!*/workloadccl/*`,
      `:!*/storageccl/*`,
      `:!*/baseccl/*`,
      `:!*/cdctest/*`,
      `:!*/cliccl/*`,
    )
    if err != nil {
      t.Fatal(err)
    }
    if err := cmd.Start(); err != nil {
      t.Fatal(err)
    }

    var buf bytes.Buffer
    if err := stream.ForEach(filter, func(s string) {
      fmt.Fprintf(&buf, "\n%s <- forbidden; use pgerror instead\n", s)
    }); err != nil {
      t.Error(err)
    }
    errs := buf.String()
    if len(errs) > 0 {
      t.Errorf("\n%s", errs)
    }

    if err := cmd.Wait(); err != nil {
      if out := stderr.String(); len(out) > 0 {
        t.Fatalf("err=%s, stderr=%s", err, out)
      }
    }
  })
```

**Comment by knz** [comment]
Here's the current linter report, there are a bit less than 800 errors to process.

[errors.log](https://github.com/cockroachdb/cockroach/files/2977148/errors.log)

**Comment by awoods187** [comment]
Can we close this issue now? If not, what is left to do?

**Comment by BramGruneir** [comment]
This probably should stay open if no linter yet exists.  All errors should
return an error code.  But that list of known errors is way too old now.

**Comment by knz** [comment]
I think we made progress on adding error codes in this release, increasing converage from less than 50% to perhaps 50% or 60%. There's still a long way to go.

**Comment by knz** [comment]
this has been largely addressed.
