### ISSUE TITLE
distsqlrun: deadlocks in Flow.cancel

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#35859]
While investigating a customer issue, @asubiotto and I discovered a couple of related deadlocks in Flow.cancel, which is called on flow timeout or cancellation.

The first is that, similar to #34041, there was a call to `Push` happening under the flow registry lock. This could lead to a deadlock (or at the very least, inefficiency) if one of the `Push` calls blocked temporarily or permanently.

The second, more subtle, deadlock is that the `cancel` method is designed to cancel all of its unconnected streams by sending a canceled metadata item via `Push`, once for each stream in a row. The trouble is that there are circumstances where the first unconnected stream might be unpushable because it's full, but nobody's reading from that stream because the single thread that's supposed to read from it is blocked waiting on somebody to push to the second unconnected stream.

For example, consider a hash join. The hash join algorithm needs to read at least some data from both of its inputs. Imagine that it reads a bunch of data from the left side, which is connected to a RowChannel and full of data, and then decides to start reading from the right side, which is also connected to a RowChannel but empty because the inbound stream to that RowChannel hasn't gotten established yet. At this point, the hash join will do nothing until it reads data on the right side.

Now, the flow is canceled, and it just so happens that the order of the inbound streams (which is arbitrary) is left, then right. At this point, the flow canceler will try to push a cancellation metadata message to the left RowChannel. This will be problematic if the left RowChannel is full, because the call to Push will block. If the call to Push blocks, then the canceler will never make it to call Push on the right RowChannel, which is the only one that the HashJoiner is listening on at that moment. So, boom, deadlock.

**Comment by jordanlewis** [comment]
The solution we came up with involves calling Push to each inbound stream in a separate goroutine, which does work, but it feels gross.

Another idea would be to extend RowChannel to have another channel for metadata, ensuring Pushes of metadata always go through.

@RaduBerinde do you have any other ideas here?

**Comment by RaduBerinde** [comment]
I don't see a problem with calling Push in separate gorutines if it happens only on cancellation or errors. 

Adding and selecting on another channel is likely non-trivial overhead, plus it will require a lot of refactoring inside the processors to actually achieve the goal of metadata always going through.

**Comment by jordanlewis** [comment]
Here is an EXPLAIN for one of the queries that got stalled, in case it helps:

```
root@:26257/callofduty> explain                                                               SELECT *, rank() OVER (ORDER BY stat_value DESC) + 0 AS stat_rank FROM (SELECT platform_id, user_id, username AS player_name, country_code, avatar_url, twitter, twitch, supporter_end_date, total_games_played AS matches, kills AS stat_value FROM bo4_careerstats AS tbl INNER JOIN bo4_account@primary AS acttbl ON tbl.id = acttbl.id WHERE (platform_id = 1) AND (acttbl.is_banned = false) ORDER BY kills DESC LIMIT 10 OFFSET 1) ORDER BY stat_rank;
                    tree                   |     field      |                description
+------------------------------------------+----------------+-------------------------------------------+
  sort                                     |                |
   │                                       | order          | +stat_rank
   └── window                              |                |
        └── render                         |                |
             └── limit                     |                |
                  │                        | count          | 10
                  │                        | offset         | 1
                  └── sort                 |                |
                       │                   | order          | -stat_value
                       └── render          |                |
                            └── merge-join |                |
                                 │         | type           | inner
                                 │         | equality       | (id) = (id)
                                 │         | mergeJoinOrder | +"(id=id)"
                                 ├── scan  |                |
                                 │         | table          | bo4_careerstats@primary
                                 │         | spans          | ALL
                                 └── scan  |                |
                                           | table          | bo4_account@primary
                                           | spans          | ALL
                                           | filter         | (platform_id = 1) AND (is_banned = false)
(21 rows)

Time: 3.071739ms
```

https://cockroachdb.github.io/distsqlplan/decode.html#eJzUVltu4zYU_e8qCKIfDoaGdfXwQ0AAZjAPJGntgWeAYjA0CkqiY6GO5FI06nSQNXQ9_elPlzGbKa4U12PZlqx4HsiPLVE893F47gE_0iSN1FDeqoz6HyhQRm3KqEMnjC50GqosSzV-KjZeRivqW4zGyWJpcHnCaJhqRf2P1MRmrqhP38lgrsZKRkp3LMpopIyM53n4hY5vpb7jQer-GkqtlM6MNBll9O1CJplP2h1BiRCrKPrzTojV1BFiBfBSiFUwFWLVl_lv1MGFrhCr0MPNuGiBoEQmEfFIamZKY9DR0viEA-N9xh2gk3tG06V5qHxTcHBHZjKbbZfKcf-E0czIG0V9uGePY8A5zIAMw3SZmO3uf8ywIyu7xvaj4b__YMNdhW_yAz4Hcc7JQ7fOpttX8dwo7ZMWt8k5Ad_3L4fv-mfkYviCtHiXnJOpnGfq7HNibMYdxl3Gu4z3GAdgHBzGwWUcvJMIsw8StomT6khpFZXjPMPER-3aw_3PSt-oqzROlO50tzFzNTUtDs_OznV8Myse_yfDywnoMj5gHKwHKuyCDmSpRMamUaeJMt6m2ijdGZSbsdqU0Z_i29gQKAt1k8p9PKdWez9dw7SdLjpgb-_f1Ye3lkh_w5C1qdkio-k0U4YcLt5rwtMvcRKlfyjdgdL8jC-G160z0hqNX7wck-fvCQdo75f0vpIPl9d9xDGCW6a50O7eBL2tBHC8g0BDDz3JQtGCrByNC_YbjIDmA-7o098hbsd40eA9Qgf5z3TXir6a8TagzWtgvB1BXxetiJXqzfAxwDaDK1xAgiQIkSBx087vSIcUwngFXb9NDe6yP_31HPGBROas6zwUIvvImp3befhAlf00XBu-i2v3vr1r18hqPe7Wl7Bt-3gJ280nfy24qOfkJhBcX-UXCPzJdSzz68XFK1Rqf635gSykjIvF9C_Xe4Pw9QX-IThAPYPD8hD4iAEAJ8XKYytBv-bwN2DObTb8x1-62o-2iqc0-PZ3Gfz-tx_8GkmtBx--9H1tT66xyhZpkqmtVIciW8ilim5UcUJZutSheqPTME9TvI5yXG5ukcpM8dUuXi6T4hMWeDx4cAoYnGo0NKjbbgYenAIu1b2Dtsto63P0Ntgqg51KsFvNmFsJ9qoze5XgbjW4WwmGmtS9UxRaDa5RaDW4TqH9UxRaDa5RaDW4TqGD6tOyqk8Ldsa6iUahyVg3Rdecdg261pB2JruRI1Wj6yypGl134lDtK-DWHHm1s5SPfHL_w38BAAD__5HPgQ0=
