### ISSUE TITLE
2 phase transaciton protocol

### ISSUE THREAD

**Issue by phamtai97** [cockroachdb/cockroach#35850]
I read and don't understand your 2 phase transaction protocol. In phase 2, when transaction record update to aborted? And i read `CockroachDB checks the running transaction's record to see if it's been ABORTED; if it has, it restarts the transaction`. when does a transaction restart occur? What if the restart is still aborted ?

And phase 3, if phase 2 has restarted transaciton when state transaciton record is aborted, How can phase 3 encounter the status of the transaction record is aborted.

I see conflicts. Can you explain me the 2pc process?

**Comment by jordanlewis** [comment]
Hi @phamtai97, can you move this question to our forum? GitHub isn't well suited to questions like this - it's more likely you'll get a response on the forum.

https://forum.cockroachlabs.com/

Thanks for your interest!

**Comment by phamtai97** [comment]
Oh, thank you.

Vào Th 2, 18 thg 3, 2019 lúc 21:18 Jordan Lewis <notifications@github.com>
đã viết:
