### ISSUE TITLE
Postgresql multiple schemas

### ISSUE THREAD

**Issue by irizzant** [cockroachdb/cockroach#35869]
Hello
we're trying to migrate our existing Postgresql DB into Cockroach and the dump file we created fails because it contains multiple schemas creation:
`CREATE SCHEMA xyz`

and the cli fails like this:
````
root@cockroachdb-1:26257/defaultdb> IMPORT PGDUMP 'http://xxxx/CockroachDB/glfci.sql';
pq: unimplemented at or near "crm"
source SQL:


--
-- Name: crm; Type: SCHEMA; Schema: -; Owner: webtng
--

CREATE SCHEMA crm;
````
I'm on Cockroach 2.1.6.
Would it be possible to add this feature?

**Comment by awoods187** [comment]
Hi @irizzant thank you for filing an issue. We are tracking this feature on https://github.com/cockroachdb/cockroach/issues/26443 .
