### ISSUE TITLE
sql: Reject interval nanoseconds specifier

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#35872]
Nanoseconds work in CRDB but not in PG (https://www.postgresql.org/docs/current/datatype-datetime.html)
```
SELECT
INTERVAL 
'6 years 5 months 4 days 3 hours 2 minutes 1 second 1 microsecond 1 nanosecond';
                ?column?
+---------------------------------------+
  6 years 5 mons 4 days 03:02:01.000001
(1 row)

Time: 2.014446ms
```
PG does not support (and rejects) the 'nanoseconds' specifier. Now that CRDB does not support nanoseconds any more, the specifier should also be rejected during parsing. Please file a separate issue.

**Comment by knz** [comment]
cc @mjibson what do you think?

**Comment by mjibson** [comment]
Yes, I agree. I think it's too late to do this for 19.1 though, do you agree?

As a side note, postgres does support fractional microseconds, which are kind of like nanos:

```
postgres=# select '0.1us'::interval, '0.9us'::interval;
 interval |    interval     
----------+-----------------
 00:00:00 | 00:00:00.000001
```

**Comment by knz** [comment]
> Yes, I agree. I think it's too late to do this for 19.1 though, do you agree?

I have no opinion. Andy thinks we should still do it, otherwise it's going to be hard claiming we completed the precision change.

**Comment by mjibson** [comment]
Thinking through this: doing this change could break some applications that have previously relied on being able to pass these strings as interval units. However our previous ns change already changed the behavior of what those units even meant. Arguably the previous change silently broke some behavior, and so this change will at least loudly complain about something that no longer works.

Ok, I think we could make and now backport this change. @bdarnell do you agree?

**Comment by bdarnell** [comment]
+1 to disallowing `nanoseconds` here for 19.1.
