### ISSUE TITLE
sql: add TypeORM canary tests to nightlies to ensure no regressions 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#35876]
We should add the TypeORM tests to our nightly suites to make sure we continue to support TypeORM well and to ensure we do not regress any functionality for the tool.

**Comment by BramGruneir** [comment]
Should I pin the canary test to a specific version of TypeORM or to master?

**Comment by awoods187** [comment]
@mjibson used some tool that let you decide dynamically which version of both CRDB and Third-party tool to point at. I think we should do our master and their latest stable (to keep us from breaking anything) and they can handle testing on their side to make sure their new versions don't break our setup.

**Comment by mjibson** [comment]
I have a commit [here](https://github.com/mjibson/cockroach/commit/f9679344416a3100b56c386e49bee4ff5f200b5d) that runs the typeorm cockroach example in docker-compose. It needs a bit of work but is a good starting point to do this in acceptance testing.

**Comment by BramGruneir** [comment]
Closed via #36003.
