### ISSUE TITLE
sql: unknown function: pg_terminate_backend()

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#35897]
This function shows up in psycopg tests. Unsure if we want to support it. See #26603.

**Comment by rafiss** [comment]
This is also used in pgjdbc tests

**Comment by pablo-sumup** [comment]
Hello, 
We need `pg_terminate_backend()` because sometimes we use libraries that do not disconnect as expected.
Do you have an ETA for implementing this function?

**Comment by rafiss** [comment]
Can you say more?  CockroachDB is quite different from Postgres when it comes to session management.

In Postgres, there is a separate process per connection, so there are more resources to clean up when a session ends.

In CockroachDB, a session is a goroutine, and if the session is disconnected (even uncleanly), all the server-side state associated with that session is automatically released.

**Comment by pablo-sumup** [comment]
Interesting. We use pg_terminate_backend() to close the connections before
deleting a test database.
It is part of some cleaning and GC on a set of tests.
I tried deleting the database, and it seems to work. Not sure if there are
open connections to it, though.
