### ISSUE TITLE
sql: encourage use of session variables and not cluster settings for testing

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#35914]
Session vars are only initialized when the client connects. 

Changing a cluster settings does not change session variables of already established sessions. 

This means that changing a cluster setting changes something for the entire cluster, but not for the user's current session.

This can be confusing as seen in https://github.com/cockroachdb/cockroach/issues/35813 as the user expected the cluster setting to have also changed the session.

We should encourage users testing features to use session variables and not cluster settings (and provide a warning in https://www.cockroachlabs.com/docs/v2.1/cluster-settings.html#main-content). This will allow them to experience new features without changing things for the entire cluster. 

We should also return a warning on cluster settings that says something to the effect of "warning this cluster setting does not apply to the current session. To apply this to the current setting use a session variable."

Also this has tripped up people previously: cockroachdb/cockroach#26900

**Comment by awoods187** [comment]
cc @rmloveland

**Comment by asubiotto** [comment]
Closing as this doesn't seem actionable on the engineering end
