### ISSUE TITLE
qa: preferring the closest index 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#35923]
I'm attempting to test [Preferring the Closest Index](http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1711b33c7a5dd8ae811b110f3a84f06c2f2e91b9/dev/cost-based-optimizer.html#preferring-the-nearest-index) using master (v19.1.0-beta.20190304-511-ged48858)

**Setup the cluster using roachprod:**
roachprod create $CLUSTER -n 4 --gce-machine-type=n1-standard-16 --geo
roachprod run $CLUSTER --  "DEV=$(mount | grep /mnt/data1 | awk '{print $1}'); sudo umount /mnt/data1; sudo mount -o discard,defaults,nobarrier ${DEV} /mnt/data1/; mount | grep /mnt/data1"

**Account for [--geo flag & roachprod](https://github.com/cockroachdb/cockroach/issues/35866)**
roachprod stage $CLUSTER:1,3-4 cockroach
roachprod stage $CLUSTER:2 workload

**Set up the closter with --locality**
roachprod start $CLUSTER:1 --args=--locality=region=east,dc=dc1
roachprod start $CLUSTER:3 --args=--locality=region=west,dc=dc2
roachprod start $CLUSTER:4 --args=--locality=region=europe,dc=dc3

**Load TPC-C**
roachprod adminurl --open $CLUSTER:1
roachprod run $CLUSTER:1 -- "./cockroach workload fixtures import tpcc --warehouses=2500 --db=tpcc"

**Create one index in each region**
Roachprod sql $CLUSTER:1
CREATE INDEX us_e_idx ON item (i_id, i_name);
CREATE INDEX us_w_idx ON item (i_id, i_name);
CREATE INDEX eu_idx ON item (i_id, i_name);
show index from item;

**[Partition the index](https://www.cockroachlabs.com/docs/v2.1/configure-replication-zones.html#create-a-replication-zone-for-a-secondary-index)** 
ALTER INDEX item@us_e_idx CONFIGURE ZONE USING constraints='["+region=east","+dc=dc1"]';
ALTER INDEX item@us_w_idx CONFIGURE ZONE USING constraints='["+region=west","+dc=dc2"]';
ALTER INDEX item@eu_idx CONFIGURE ZONE USING constraints='["+region=europe","+dc=dc3"]';

**See the CBO using the right secondary index**
`EXPLAIN SELECT * FROM item;`
```
  tree | field | description
+------+-------+--------------+
  scan |       |
       | table | item@primary
       | spans | ALL
(3 rows)

Time: 1.035984ms
```
Check the second node:
```
Roachprod sql $CLUSTER:3
Use tpcc;
EXPLAIN SELECT * FROM item;
```
```
  tree | field | description
+------+-------+--------------+
  scan |       |
       | table | item@primary
       | spans | ALL
(3 rows)

Time: 1.063093ms
```
Check the last node:
```
Roachprod sql $CLUSTER:4
Use tpcc;
EXPLAIN SELECT * FROM item;
```
```
  tree | field | description
+------+-------+--------------+
  scan |       |
       | table | item@primary
       | spans | ALL
(3 rows)

Time: 344.371431ms
```
**My expectation:**
See node 1 using us_e_idx
See node 3 using us_w_idx
See node 4 using eu_idx

**Comment by awoods187** [comment]
@andy-kimball what am I missing here?

**Comment by awoods187** [comment]
I modified the create index to use storing:

CREATE INDEX us_e_idx ON item (i_id) STORING (i_name);
CREATE INDEX us_w_idx ON item (i_id) STORING (i_name);
CREATE INDEX eu_idx ON item (i_id) STORING (i_name);

On node 3:
```
root@localhost:26257/tpcc> EXPLAIN SELECT * FROM item WHERE i_name='cnfsL9DUn42wjJpMnfOgDV7Z';
  tree | field  |             description
+------+--------+-------------------------------------+
  scan |        |
       | table  | item@primary
       | spans  | ALL
       | filter | i_name = 'cnfsL9DUn42wjJpMnfOgDV7Z'
(4 rows)
Time: 1.017665ms
```
and node 4
```
root@localhost:26257/tpcc> EXPLAIN SELECT * FROM item WHERE i_name='cnfsL9DUn42wjJpMnfOgDV7Z';
  tree | field  |             description
+------+--------+-------------------------------------+
  scan |        |
       | table  | item@primary
       | spans  | ALL
       | filter | i_name = 'cnfsL9DUn42wjJpMnfOgDV7Z'
(4 rows)

Time: 1.052596ms
```

**Comment by andy-kimball** [comment]
You’re selecting every column with *. That means the optimizer has no choice but to use the primary index. To use this feature, _every column_ the query uses must be part of the index.

**Comment by awoods187** [comment]
Oh interesting--that wasn't clear to me at all from the docs example. It uses a table with only those two items. Let's try it again:
```
root@localhost:26257/tpcc> explain SELECT i_id FROM item WHERE i_name='cnfsL9DUn42wjJpMnfOgDV7Z';
    tree    | field  |             description
+-----------+--------+-------------------------------------+
  render    |        |
   └── scan |        |
            | table  | item@us_e_idx
            | spans  | ALL
            | filter | i_name = 'cnfsL9DUn42wjJpMnfOgDV7Z'
(5 rows)

Time: 1.061441ms
```

Works perfectly!

**Comment by awoods187** [comment]
I went ahead and filed https://github.com/cockroachdb/docs/issues/4605 to explain that further. Will close this QA out now.
