### ISSUE TITLE
Sysbench test cases "tpcc" and "bulk_insert" against CockroachDB failed

### ISSUE THREAD

**Issue by GangLiCN** [cockroachdb/cockroach#35934]
I used "sysbench"(version: 1.0.16-2) to test against CockroachDB(version: 2.1.6), some test cases 
failed.

The detailed information is as below:

1) "bulk_insert" failed if running on multi thread test environment(setting the value of parameter "threads" to a number which is bigger than 1(e.g. 2,4,8,16,32,,,etc)  when running "sysbench"),
 the error message is:

**FATAL: `thread_run' function failed: /usr/share/sysbench/bulk_insert.lua:38: db_bulk_insert_next() failed**

2) all tpcc related test cases failed even running sysbench on "prepare" mode(setting extra running parameter "prepare" when calling "sysbench"), the error message is as below:

......
tpcc_check.lua.4thread.prepare.log:FATAL: PQexec() failed: 7 TransactionStatusError: transaction deadline exceeded (REASON_UNKNOWN)
tpcc_check.lua.4thread.prepare.log:FATAL: failed query was: INSERT INTO order_line1	  (ol_o_id, ol_d_id, ol_w_id, ol_number, ol_i_id, ol_supply_w_id, ol_delivery_d, 
tpcc_check.lua.4thread.prepare.log:           ol_quantity, ol_amount, ol_dist_info ) values(1593, 7, 8, 4, 27586, 8, NOW(), 5, 0.000000, 'jjjjjjjjjjjjjjjjjjjjjjjj' ),(1593, 7, 8, 5, 68870, 8, NOW(), 5, 0.000000, 'uuuuuuuuuuuuuuuuuuuuuuuu' ),(1593, 7, 8, 6, 5042, 8, NOW(), 5, 0.000000, 'iiiiiiiiiiiiiiiiiiiiiiii' ),(1593, 7, 8, 7, 54697, 8, NOW(), 5, 0.000000, 'dddddddddddddddddddddddd' ),(1593, 7, 8, 8, 50963, 8, NOW(), 5, 0.000000, 'bbbbbbbbbbbbbbbbbbbbbbbb' ),(1594, 7, 8, 1, 38511, 8, NOW(), 5, 0.000000, 'hhhhhhhhhhhhhhhhhhhhhhhh' ),(1594, 7, 8, 2, 81111, 8, NOW(), 5, 0.000000, 'gggggggggggggggggggggggg' ),(1594, 7, 8, 3, 18177, 8, NOW(), 5, 0.000000, 'yyyyyyyyyyyyyyyyyyyyyyyy' ),(1594, 7, 8, 4, 21079, 8, NOW(), 5, 0.000000, 'eeeeeeeeeeeeeeeeeeeeeeee' ),(1594, 7, 8, 5, 66889, 8, NOW(), 5, 0.000000, 'iiiiiiiiiiiiiiiiiiiiiiii' ),(1594, 7, 8, 6, 39182, 8, NOW(), 5, 0.000000, 'yyyyyyyyyyyyyyyyyyyyyyyy' ),(1594, 7, 8, 7, 85531, 8, NOW(), 5, 0.000000, 'jjjjjjjjjjjjjjjjjjjjjjjj' ),(1594, 7, 8, 8, 22502, 8, NOW(), 5, 0.000000, 'oooooooooooooooooooooooo' ),(1595, 7, 8, 1, 17178, 8, NOW(), 5, 0.000000, 'jjjjjjjjjjjjjjjjjjjjjjjj' ),(1595, 7, 8, 2, 12314, 8, NOW(), 5, 0.000000, 'hhhhhhhhhhhhhhhhhhhhhhhh' ),(1595, 7, 8, 3, 56485, 8, NOW(), 5, 0.000000, 'gggggggggggggggggggggggg' ),(1595, 7, 8, 4, 68992, 8, NOW(), 5, 0.000000, 'qqqqqqqqqqqqqqqqqqqqqqqq' ),(1595, 7, 8, 5, 98626, 8, NOW(), 5, 0.000000, 'yyyyyyyyyyyyyyyyyyyyyyyy' ),(1595, 7, 8, 6, 78018, 8, NOW(), 5, 0.000000, 'xxxxxxxxxxxxxxxxxxxxxxxx' ),(1595, 7, 8, 7, 21747, 8, NOW(), 5, 0.000000, 'kkkkkkkkkkkkkkkkkkkkkkkk' ),(1595, 7, 8, 8, 44807, 8, NOW(), 5, 0.000000, 'kkkkkkkkkkkkkkkkkkkkkkkk' ),(1595, 7, 8, 9, 59196, 8, NOW(), 5, 0.000000, 'oooooooooooooooooooooooo' ),(1595, 7, 8, 10, 91079, 8, NOW(), 5, 0.000000, 'jjjjjjjjjjjjjjjjjjjjjjjj' ),(1595, 7, 8, 11, 88817, 8, NOW(), 5, 0.000000, 'oooooooooooooooooooooooo' ),(1595, 7, 8, 12, 61227, 8, NOW(), 5, 0.000000, 'rrrrrrrrrrrrrrrrrrrrrrrr' ),(1596, 7, 8, 1, 56035, 8, NOW(), 5, 0.000000, 'tttttttttttttttttttttttt' ),(1596, 7, 8, 2, 39333, 8, NOW(), 5, 0.000000, 'xxxxxxxxxxxxxxxxxxxxxxxx' ),(1596, 7, 8, 3, 23509, 8, NOW(), 5, 0.000000, 'nnnnnnnnnnnnnnnnnnnnnnnn' ),(1596, 7, 8, 4, 52824, 8, NOW(), 5, 0.000000, 'ffffffffffffffffffffffff' ),(1596, 7, 8, 5, 63028, 8, NOW(), 5, 0.000000, 'tttttttttttttttttttttttt' ),(1597, 7, 8, 1, 68938, 8, NOW(), 5, 0.000000, 'pppppppppppppppppppppppp' ),(1597, 7, 8, 2, 67532, 8, NOW(), 5, 0.000000, 'aaaaaaaaaaaaaaaaaaaaaaaa' ),(1597, 7, 8, 3, 95027, 8, NOW(), 5, 0.000000, 'xxxxxxxxxxxxxxxxxxxxxxxx' ),(1597, 7, 8, 4, 29601, 8, NOW(), 5, 0.000000, 'gggggggggggggggggggggggg' ),(1597, 7, 8, 5, 33652, 8, NOW(), 5, 0.000000, 'zzzzzzzzzzzzzzzzzzzzzzzz' ),(1597, 7, 8, 6, 83285, 8, NOW(), 5, 0.000000, 'yyyyyyyyyyyyyyyyyyyyyyyy' ),(1597, 7, 8, 7, 27597, 8, NOW(), 5, 0.000000, 'ssssssssssssssssssssssss' ),(1597, 7, 8, 8, 5100, 8, NOW(), 5, 0.000000, 'uuuuuuuuuuuuuuuuuuuuuuuu' ),(1597, 7, 8, 9, 12925, 8, NOW(), 5, 0.000000, 'hhhhhhhhhhhhhhhhhhhhhhhh' ),(1597, 7, 8, 10, 15709, 8, NOW(), 5, 0.000000, 'qqqqqqqqqqqqqqqqqqqqqqqq' ),(1597, 7, 8, 11, 18960, 8, NOW(), 5, 0.000000, 'pppppppppppppppppppppppp' ),(1597, 7, 8, 12, 39906, 8, NOW(), 5, 0.000000, 'tttttttttttttttttttttttt' ),(1597, 7, 8, 13, 35845, 8, NOW(), 5, 0.000000, 'ffffffffffffffffffffffff' ),(1598, 7, 8, 1, 97372, 8, NOW(), 5, 0.000000, 'ssssssssssssssssssssssss' ),(1598, 7, 8, 2, 78256, 8, NOW(), 5, 0.000000, 'kkkkkkkkkkkkkkkkkkkkkkkk' ),(1598, 7, 8, 3, 32614, 8, NOW(), 5, 0.000000, 'nnnnnnnnnnnnnnnnnnnnnnnn' ),(1598, 7, 8, 4, 72912, 8, NOW(), 5, 0.000000, 'gggggggggggggggggggggggg' ),(1598, 7, 8, 5, 61891, 8, NOW(), 5, 0.000000, 'vvvvvvvvvvvvvvvvvvvvvvvv' ),(1598, 7, 8, 6, 32936, 8, NOW(), 5, 0.000000, 'dddddddddddddddddddddddd' ),(1598, 7, 8, 7, 54282, 8, NOW(), 5, 0.000000, 'qqqqqqqqqqqqqqqqqqqqqqqq' ),(1598, 7, 8, 8, 7908, 8, NOW(), 5, 0.000000, 'jjjjjjjjjjjjjjjjjjjjjjjj' ),(1599, 7, 8, 1, 2181, 8, NOW(), 5, 0.000000, 'bbbbbbbbbbbbbbbbbbbbbbbb' ),(1599, 7, 8,FATAL: `sysbench.cmdline.call_command' function failed: /usr/share/sysbench/tpcc_common.lua:561: db_bulk_insert_next() failed
.......

My questions are: 
1)  Is "sysbench" certified by offical as a perf/pressure test tool ?  
2) What does these errors mean ?  Do I need to test against PostgreSQL or MYSQL to confirm if this is a CockroachDB specific issue ?

**Comment by vivekmenezes** [comment]
closing this as the same as #18684
