### ISSUE TITLE
importccl,backupccl: import is erroneously relying on string compares to detect particular errors

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#35942]
The code for RESTORE (and thus IMPORT CSV) is using rocksdb ingest sst's built-in duplicate detection to report whether the ingested data is valid for a primary or unique index.

Any rocksdb error seems to be compared by a test on the text of the error message, it has to be prefixed specifically by `Invalid argument: Keys ...`.

The problem is that the `Invalid argument:` part is added by `errors.Wrap()`, so that if the error gets unwrapped it does not match any more.

The check for the error should be made more robust, for example using the mechanism introduced in #35920.

**Comment by knz** [comment]
cc @dt @danhhz

**Comment by dt** [comment]
So fortunately that code path can go away soon as we no longer need to handle that once we're on cluster version 19.1+

I thought that `Invalid argument: ` prefix came straight from rocksdb?

**Comment by knz** [comment]
Doesn't matter where it comes from if it gets stripped by errors.Cause. I'm glad the problem will go away though I'm left to ask: how?
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dt** [comment]
Huh, really? where does that happen?

**Comment by dt** [comment]
oh, sorry, I was thinking of a different `Invalid argument` rocksdb error we check (via string compare)  during SST _ingest_  -- I just realized the one you're talking about the one during SST creation. That one is _not_ going away.

**Comment by knz** [comment]
> That one is not going away.

It certainly can using the technique in #35920 or something like it.

**Comment by shermanCRL** [comment]
Closing for now, since it’s RocksDB. We think there might be improvements, but will track elsewhere.
