### ISSUE TITLE
opt: graphical plan viewer

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#35946]
I don't have a great idea for a name, but today the experience of using `explain (opt, verbose)` to diagnose planning issues can be a pain, since those plans are so horizontally wide that it causes wrapping and makes the plan nearly impossible to read. For complex plans like this where you need to view a lot of information, we should have some kind of graphical plan viewer similar to `explain (distsql)` that would provide a URL to a page that showed the plan with a bit more breathing room, and which allowed you to drill into the subplans and operators that you specifically want to know more about.

**Comment by knz** [comment]
we have a new EXPLAIN output now
