### ISSUE TITLE
cli: passwords with special characters cannot be passed in URL

### ISSUE THREAD

**Issue by joshimhoff** [cockroachdb/cockroach#35998]
**Describe the problem**

@vilterp @mberhault @nstewart

The managed console has a model that shows a `cockroach` command that lets the user connect securely to their cluster. Here is an example command, with a fake password:

> cockroach sql --url 'postgres://josh:password>@aws-us-east-1.laughing-ladybug.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full&sslrootcert=/Users/josh/Downloads/laughing-ladybug-ca.crt'

If your password has special characters in it (e.g. ">"), the cmd fails. I used a password manager to generate my password, and so it had five or so different special characters in it. The error message looks like this:

> Error: invalid argument "postgres://josh:password>@aws-us-east-1.laughing-ladybug.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full&sslrootcert=/Users/josh/Downloads/laughing-ladybug-ca.crt" for "--url" flag: parse postgres://josh:password>@aws-us-east-1.laughing-ladybug.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full&sslrootcert=/Users/josh/Downloads/laughing-ladybug-ca.crt: net/url: invalid userinfo
Failed running "sql"

It works with psql tho:

> psql 'postgres://josh:password>@aws-us-east-1.laughing-ladybug.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full&sslrootcert=/Users/josh/Downloads/laughing-ladybug-ca.crt'

`cockroach` works if you don't put the password in the URL; `cockroach` then prompts you for a password and there seems to be no issue even with special characters.

On the managed side, we are gonna work around this issue by not including the password in the `cockroach` command we display to users. Perhaps we should fix the broader issue tho.

Nate found the following issue on stackoverflow:

https://stackoverflow.com/questions/48671938/go-url-parsestring-fails-with-certain-user-names-or-passwords

The issue looks relevant. Could we call url.QueryEscape()?

**To Reproduce**

Connect to cluster with `cockroach` command with special character such as ">" in password part of connection URL. e.g.:

> cockroach sql --url 'postgres://josh:password>@aws-us-east-1.laughing-ladybug.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full&sslrootcert=/Users/josh/Downloads/laughing-ladybug-ca.crt'

**Expected behavior**

Ideally this would work without requiring user to escape the password. At the very least the error message could be clearer.

**Environment:**

> $ cockroach version
Build Tag:    v2.1.5
Build Time:   2019/02/19 16:35:28
Distribution: CCL
Platform:     darwin amd64 (x86_64-apple-darwin18.2.0)
Go Version:   go1.11.5
C Compiler:   4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)
Build SHA-1:  1634c6bbf48d82ef8994386f29750c9dc3f6163a
Build Type:   release

**Comment by knz** [comment]
the issue for this is in the go URL parser. We can't just blindly call an unescape function; this would make the behavior break for folk who were using `%` in their passwords previously.

**Comment by u007** [comment]
i encounter similar issue, ive to url encode my password

**Comment by knz** [comment]
we also now support the password as a query argument at the end
