### ISSUE TITLE
ui: Add setting to configure session timeouts in the Admin UI

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#36007]
A customer has noted that they would like to restrict the timeout window for sessions of users that are logged into the UI. The default timeout for a session is 168 hours. We should make this end user configurable.

Jira issue: CRDB-4535

**Comment by jetsetmonkey** [comment]
Please can there be 2 configurable timeouts in the Admin Web-UI:

1. Inactivity for a session timeout

2. An absolute timeout for a session (so someone doesn't stay logged in forever)

**Comment by celiala** [comment]
@piyush-singh looks like we already have a configurable setting for session timeout window:

`server.web_session_timeout` - the duration that a newly created web session will be valid (default 168h, 0m, 0s)



https://www.cockroachlabs.com/docs/v19.1/cluster-settings.html#settings

**Comment by jetsetmonkey** [comment]
@celiala Thank you.

Is the server.web_session_timeout an absolute timeout or will it extend if the user is logged into the web console and executing?

**Comment by celiala** [comment]
Hi @jetsetmonkey -

`server.web_session_timeout` is an absolute timeout, so regarding your requests from March 22:

> 1. Session timeout for user inactivity

Not yet implemented

> 2. An absolute timeout for a session (so someone doesn't stay logged in forever)

Implemented, via `server.web_session_timeout`.

**Comment by knz** [comment]
Rerouting to obs infra.

**Comment by knz** [comment]
@nkodali this is observability infra.
cc @dhartunian
