### ISSUE TITLE
opt: row count calculation for group by doesn't account for nulls

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#36047]
Until we fix #31746, we need to account for null values as separate "distinct" values. Currently, the row count for GROUP BY is estimated as the distinct count of its grouping columns. This should be fixed to be the distinct count + the null count.

**Comment by RaduBerinde** [comment]
NULLs are equal for the purposes of GROUP BY and DISTINCT. Isn't SQL great?
```
root@127.169.231.58:36891/defaultdb> select sum(a) from (values (1, 1), (2, NULL), (3, NULL)) AS v(a,b) GROUP BY b;
  sum  
+-----+
    1  
    5  
(2 rows)
```

I think that now that we're including NULL in the distinct count, there isn't anything to fix here.

**Comment by rytaft** [comment]
Yep, agreed. Closing this.
