### ISSUE TITLE
sql: table name cache is not populated after misses

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#36044]
Over the last few months we've observed strange performance dips during a wide variety of perf test runs. This was mystery until today when @nvanbenschoten decided to dig in to it.

![Screenshot_2019-02-26 roachperf](https://user-images.githubusercontent.com/1839234/54786452-45205000-4bff-11e9-8927-5610a6002742.png)
![Screenshot_2019-02-26 roachperf(1)](https://user-images.githubusercontent.com/1839234/54786456-4782aa00-4bff-11e9-81d7-14d3ccd67f03.png)
![Screenshot_2019-02-26 roachperf(2)](https://user-images.githubusercontent.com/1839234/54786464-4b163100-4bff-11e9-9a59-c6eee96d1c1d.png)
![Screenshot_2019-02-26 roachperf(3)](https://user-images.githubusercontent.com/1839234/54786470-4e112180-4bff-11e9-83fd-eaf8945577e2.png)

The first observation was that when the performance drop happen we see a doubling on distsql requests from a node and a similar doubling in kv requests on a different node. 

![Screenshot from 2019-03-21 17-37-19](https://user-images.githubusercontent.com/1839234/54787744-1c9a5500-4c03-11e9-8157-c1786a58de39.png)

Digging further in we find from a [goroutine_dump](https://github.com/cockroachdb/cockroach/files/2994149/goroutine_dump.zip) dump that these extract reads are coming from the need to resolve a table name (see [here](https://github.com/cockroachdb/cockroach/blob/a200cea4368ec90aaee12337d7ab5f9ca555108f/pkg/sql/lease.go#L1412)). 

I can't tell you why we fail to retrieve from the cache. It must be either that the entry doesn't exist (seems very unlikely) or that the entry is expired (seems likely but I have not yet verified). I am trying to repro and then dive in with delve to see what's going on inside that cache.

It seems to be the case that when we fail to resolve the table name from the cache and we go and resolve the name the result does not go back in to the cache and there doesn't seem to be any signal that the cache should be updated.

@vivekmenezes do you have thoughts?

**Comment by vivekmenezes** [comment]
Do you have any schema changes running for any of the tables? If it's pure tpcc that shouldn't be the case.

I'd suspect that the table decriptor range becomes unavailable or slow for the two minute duration slowing down table lease acquisitions. Or the table lease table is busy slowing down lease acquisitions, resulting in many requests hitting this path. I think we ought to use a singleflight.Group here to prevent more than one request hitting the range. They should all queue up behind one request for the table.

**Comment by ajwerner** [comment]
There are no schema changes. This is just a vanilla KV95 run. The above graphs come from roachtests like `kv95/enc=false/nodes=3`. It also happens under KV0 and has been observed in YCSB workloads as well.

**Comment by vivekmenezes** [comment]
I'll see what I can do. Thanks for reporting the problem. I might come by with some questions. thanks

**Comment by vivekmenezes** [comment]
I'm working on this presently

**Comment by vivekmenezes** [comment]
I've confirmed that this problem is indeed caused by a burst of table name resolutions sent over a period of approximately 2 minutes. I thought my PR fixed it but it's still being triggered. I've added a ton of logging and now re-running. Hopefully I will stumble upon the problem in my PR soon.

**Comment by vivekmenezes** [comment]
I've confirmed that #36531 solves this problem.
