### ISSUE TITLE
Self-tuning database

### ISSUE THREAD

**Issue by joelchen** [cockroachdb/cockroach#3606]
Is self-tuning feature possible in CockroachDB like in [Concourse][1], removing the need for database configurations?
[1]: https://github.com/cinchapi/concourse

**Comment by tschottdorf** [comment]
What exactly are you looking for? Schemaless or just no "configuration" to
get it running? I would argue that the latter is currently mostly true
(setting up TLS is always a bit tricky, but I think most other databases
just don't make that a default and get around it that way). If you give us
more details, we can answer you better.

**Comment by joelchen** [comment]
The goal is to improve performance as the data evolves over time, and cut time spent on database administration with automation.

**Comment by bdarnell** [comment]
Yes, our goal is for the database to tune itself as much as possible, although this will obviously be a long-term process.
