### ISSUE TITLE
sql: INSERT INTO subqueries , order of execution

### ISSUE THREAD

**Issue by pungggi** [cockroachdb/cockroach#36076]
**The problem**

Given that schema:
![image](https://user-images.githubusercontent.com/5635709/54862412-325a6800-4d32-11e9-9f1a-7fd4f8fb0079.png)

```sql
CREATE TABLE mpoint.user (
        email STRING,
        created TIMESTAMPTZ DEFAULT current_timestamp(),
        lastAccess TIMESTAMPTZ,
        name STRING,
        password STRING NOT NULL CHECK (password <> ''),
        data JSONB,
        PRIMARY KEY (email)
      );
CREATE TABLE mpoint.employee(
        id UUID DEFAULT gen_random_uuid(),
        email STRING,
        CONSTRAINT fk_user FOREIGN KEY (email) REFERENCES mpoint.user ON UPDATE CASCADE,
        PRIMARY KEY (id)
      );
CREATE TABLE mpoint.service(
        id UUID DEFAULT gen_random_uuid(),
        name STRING,
        PRIMARY KEY (id)
      );
CREATE TABLE mpoint.employeeServices(
        employee_id UUID,    
        service_id UUID,
        CONSTRAINT fk_resource FOREIGN KEY (employee_id) REFERENCES mpoint.employee,
        CONSTRAINT fk_service FOREIGN KEY (service_id) REFERENCES mpoint.service,
        PRIMARY KEY (employee_id, service_id)
      );
```
The following Query does not work as expected with the pg driver, for example in nodejs or in Dbeaver:
```sql
INSERT INTO mpoint.employeeServices(employee_id, service_id) 
    (SELECT 
      (SELECT * FROM
        [INSERT INTO employee(email) VALUES ('work.hard@cockroach.com') RETURNING id]
      ),
      (SELECT * FROM 
        [INSERT INTO service(name) VALUES ('Develop CRDB') RETURNING id]
      )
    );
```

it throws> 
`[42P01]: ERROR: relation "employee" does not exist`

Whereas **in CRDB SQL Client it works**. The email exists in user table.

**To Reproduce**
Using DBeaver
1. Create Tables
2. Send SQL ... Create an user 'work.hard@cockroach.com'
3. Execute Query above

Using crdb SQL Client
1. Send SQL
Notice it works.

**Expected behavior**
Same behavior as in the SQL Client of CRDB.
Execute the subqueries first.

**Comment by jordanlewis** [comment]
Hi @pungggi, what version of CRDB are you using?

Can you please reproduce with the flag `--vmodule=conn_executor=2` on the Cockroach server and send the logs during your attempt?

**Comment by pungggi** [comment]
@jordanlewis i am using 2.1.6 on windows here is the log:
Attempt to execute with DBeaver:
[cockroachexe.CHICO.CHICO_Alessandro.2019-03-26T13_36_37Z.001064.log](https://github.com/cockroachdb/cockroach/files/3008404/cockroachexe.CHICO.CHICO_Alessandro.2019-03-26T13_36_37Z.001064.log)

**Comment by jordanlewis** [comment]
@pungggi I think the problem is that you haven't connected to the `mpoint` database in dbeaver so the tables `employee` and `service` are ambiguous. Try using `mpoint.employee` instead of `employee`.

**Comment by pungggi** [comment]
oh. so obvious. I am closing. Thank you.
