### ISSUE TITLE
Warn user if enabling follower reads cluster setting without enterprise license

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#36071]
When enabling the cluster setting to allow follower reads, there is no indication that the cluster needs to have an enterprise license set in order for the feature to work. Since this setting is now enabled by default, it might be useful to:

1) Warn the user that this setting requires an enterprise license for follower reads when setting from false to true (if the setting is ever turned off)
2) Warn the user when they `show cluster setting` and the value for `kv.closed_timestamp.follower_reads_enabled` is true and there is no enterprise license set. Perhaps: "this feature will be unavailable until a license is set for the cluster."

cc @awoods187 for triage.

**Comment by awoods187** [comment]
@ajwerner thoughts on this? Is this a small patch to add the warning?

**Comment by ajwerner** [comment]
Technically this setting is low level and is beneath the enterprise code. Maybe we should just hide the setting?

**Comment by piyush-singh** [comment]
I think if the intention is to leave this as always true and gate based on enterprise license, it makes sense to hide this entirely. Having the setting set to true without an enterprise license is likely to just create confusion.

I'm voting for removing the setting.

**Comment by awoods187** [comment]
How does someone turn it off? Or is the argument that as long as they are not explicitly enabling the `experimental feature` it doesn't matter to the user if a portion of this is automatically a follower read?

**Comment by ajwerner** [comment]
The setting now defaults to true. The only reason a user should disable it now is as a mitigation of some unforeseen bug. Given that I suggest we close this issue. @piyush-singh thoughts?

**Comment by piyush-singh** [comment]
Makes sense; the only thing governing access to follower reads is now whether an enterprise license is present for the cluster. Dealing with potential bugs is a legitimate reason to keep this setting around. Closing.
