### ISSUE TITLE
performance: roachperf shows tpc-c regression in march

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#36097]
![image](https://user-images.githubusercontent.com/22278911/54922514-b81b1680-4ede-11e9-9b93-0fefe5fbb430.png)
https://crdb.io/perf/?filter=&view=tpccbench%2Fnodes%3D3%2Fcpu%3D4&cloud=gce

We hit ~470 from mid-November through the end of 2019. January and February dropped us to 410-440, and March dropped us below 400.

**Comment by awoods187** [comment]
Seems to be true for YCSB too 
![image](https://user-images.githubusercontent.com/22278911/54924297-6d030280-4ee2-11e9-9d74-c4ef2b8cc3a9.png)

**Comment by bdarnell** [comment]
For reference, automatic stats collection was enabled on Feb 4 (#34529). Then it was disabled on Feb 19 (#35019), throttling was added (#34928), and it was reenabled on Feb 28 (#35291). This was expected to cause some performance decrease (and for the w=max tpcc tests, it reduced the target number of warehouses for 3 GCE nodes from 1400 to 1350). 

There's a lot of noise here and it's difficult to assign responsibility to specific changes. Feb 6 scored higher than Feb 3, even though it had the unthrottled stats enabled. Feb 22 wasn't much better than Feb 19. It looks like automatic stats are probably contributing here, but they're not the whole story.

**Comment by awoods187** [comment]
With auto stats is first, turned off is second:
![image](https://user-images.githubusercontent.com/22278911/55184100-b4e68b80-5167-11e9-850a-6cca913a4a8e.png)

Auto stats seems to have an impact but it's still clearly bad regardless

**Comment by awoods187** [comment]
Run with auto stats turned off pre import:
![image](https://user-images.githubusercontent.com/22278911/55193264-d8680100-517c-11e9-86c7-17765fac7a6e.png)

**Comment by awoods187** [comment]
And similarly, I ran 10k on 15 nodes:

```
_elapsed_______tpmC____efc__avg(ms)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
  900.0s    94682.0  73.6%   6698.6   4160.7  16643.0  21474.8  33286.0 103079.2
```
![image](https://user-images.githubusercontent.com/22278911/55193308-f59ccf80-517c-11e9-8813-2ddb2d4394fd.png)

**Comment by awoods187** [comment]
Okay perhaps there was some sort of user error yesterday on 10k as today I had no problems:
```
_elapsed_______tpmC____efc__avg(ms)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
  900.0s   125143.6  97.3%    263.7    243.3    503.3    604.0    805.3   6979.3
```

**Comment by bdarnell** [comment]
A couple of data points from `tpccbench` (which is our script to discover the max supported warehouses): I've run it twice on the same build (a master build from a couple of days ago) and I got 1395 one time and 1315 the second. 

```
22:26:58 tpcc.go:717: --- FAIL: tpcc 1320 resulted in 12802.9 tpmC and failed due to efficiency value of 76.94691781122275 is below passing threshold of 85
22:26:58 tpcc.go:728: ------
MAX WAREHOUSES = 1315
------
```

**Comment by awoods187** [comment]
Closing this as it is no longer relevant
