### ISSUE TITLE
sql: index creation failed with mixed success error

### ISSUE THREAD

**Issue by roncrdb** [cockroachdb/cockroach#36100]
**Describe the problem**

 When creating a new index the job failed after some time with the following error:

`the batch experienced mixed success and failure`

**To Reproduce**

I attempted to reproduce, but it appears that the schema we have may be outdated as when I ran the create index query after creating all the tables it gave me an error that a specific column did not exist, we have the schema for the DB [here](https://github.com/cockroachlabs/kindred/blob/master/docs/partitioning/bank_pte_schema.sql). 

**Expected behavior**
Expected the index to be created

**Additional data / screenshots**
Logs of the issue can be found [here](https://drive.google.com/open?id=1v8TtxxpK-b4lGqvSs-KSsfiI67MmlsX8).  These logs are from the gateway node and shows the command issued, and where if failed. 

The full debug zip can be found [here](https://docs.google.com/document/d/1mWGjdHXT6a4ceH1yxTgeLYjICg-qViQcU0fT5wbT-2o/edit?usp=sharing).

**Environment:**
 - CockroachDB version 2.1

**Comment by vivekmenezes** [comment]
this is fixed through https://github.com/cockroachdb/cockroach/pull/32888

**Comment by vivekmenezes** [comment]
and backported to 2.1 through https://github.com/cockroachdb/cockroach/pull/34914

**Comment by awoods187** [comment]
Closing per @vivekmenezes s comments above
