### ISSUE TITLE
opt: infinite loop between normalization rules

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#36137]
I ran into this while trying to debug a different issue. It looks like `TryDecorrelateSelect` and `PushFilterIntoJoinLeftAndRight` are looping with each other. Can be reproduced as follows:

```
CREATE TABLE t (a INT, b INT, c INT, d INT, e INT);
CREATE TABLE u (a INT, b INT, c INT, d INT, e INT);

SELECT * FROM t JOIN u ON t.a = u.a
WHERE (t.a = u.a) OR (t.a IN (SELECT 5 FROM u WHERE a = b));
```

Not sure who should take this one, but maybe @andy-kimball has an idea about how to fix it.

cc @RaduBerinde, @justinj

**Comment by justinj** [comment]
Hrm, that's too bad, I ran into something similar in #35171 but I thought that it was only possible with another change. Is re-introducing `DetectCycle` for 19.1 feasible? I can't think of a safe quick-fix off the top of my head.
