### ISSUE TITLE
sql: TestPGPreparedQuery fails on release-2.1, but not on TC

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#36184]
I have no idea what's going on, but this test seems to fail constantly for me and several others on `release-2.1`. Except on TC it seems to pass reliably.

```
--- FAIL: TestPGPreparedQuery (2.14s)
    --- FAIL: TestPGPreparedQuery/prepare (0.83s)
        --- FAIL: TestPGPreparedQuery/prepare/SELECT_CASE_40+2_WHEN_42_THEN_51_ELSE_$1::INT_END (0.00s)
            --- FAIL: TestPGPreparedQuery/prepare/SELECT_CASE_40+2_WHEN_42_THEN_51_ELSE_$1::INT_END/0 (0.00s)
                pgwire_test.go:1013: SELECT CASE 40+2 WHEN 42 THEN 51 ELSE $1::INT END: []: expected error: sql: statement expects 1 inputs; got 0, got sql: expected 1 arguments, got 0
```

@knz would you mind finding a victim for this one?

**Comment by knz** [comment]
Radu knows where to look on this one.

Otherwise Matt

Andrei Matei <notifications@github.com> schreef op 26 maart 2019 22:36:55 CET:
>I have no idea what's going on, but this test seems to fail constantly
>for me and several others on `release-2.1`. Except on TC it seems to
>pass reliably.
>
>```
>--- FAIL: TestPGPreparedQuery (2.14s)
>    --- FAIL: TestPGPreparedQuery/prepare (0.83s)
>--- FAIL:
>TestPGPreparedQuery/prepare/SELECT_CASE_40+2_WHEN_42_THEN_51_ELSE_$1::INT_END
>(0.00s)
>--- FAIL:
>TestPGPreparedQuery/prepare/SELECT_CASE_40+2_WHEN_42_THEN_51_ELSE_$1::INT_END/0
>(0.00s)
>pgwire_test.go:1013: SELECT CASE 40+2 WHEN 42 THEN 51 ELSE $1::INT END:
>[]: expected error: sql: statement expects 1 inputs; got 0, got sql:
>expected 1 arguments, got 0
>```
>
>@knz would you mind finding a victim for this one?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/cockroachdb/cockroach/issues/36184

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by RaduBerinde** [comment]
This code generates the error expected by the test:
```
func wrongArgCountString(want, got int) string {
	if strings.HasPrefix(runtime.Version(), "go1.10") {
		return fmt.Sprintf("sql: expected %d arguments, got %d", want, got)
	}
	return fmt.Sprintf("sql: statement expects %d inputs; got %d", want, got)
}
```
This doesn't work with go1.11 (it's treated like an older version). It looks like even release-2.1 requires go1.10 now, so we can just remove the check altogether.
