### ISSUE TITLE
sql: exec_log doesn't print exact input SQL

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#36185]
When using `--vmodule=exec_log=2` to print incoming SQL, we have found it doesn't print the exact SQL. For example it changes `int` to `int8` and removed `::date` from a string. Getting the exact SQL is very important when trying to debug ORM errors. There should be a way to do this.

cc @BramGruneir @andreimatei

**Comment by BramGruneir** [comment]
The best example I have of this is this one:

```sql
# original
create table array_test (id integer, col timestamp without time zone[]);
insert into array_test values (1, array['2011-02-14']::date);

# printed in both vmodule and audit logs
CREATE TABLE array_test (id INT8, col TIMESTAMP[]);
INSERT INTO array_test VALUES (1, ARRAY['2011-02-14']);
```

The reason this is concerning is that the original will cause an error (in cockroach, not postgres), but the prettified one is actually valid in cockroach.

**Comment by BramGruneir** [comment]
One more point, `BEGIN` does not show up in either log.  
This also makes debugging more difficult.

**Comment by andreimatei** [comment]
FWIW, I believe recently Radu added some support to the parser for returning the original string together with the AST (if I remember correctly).

**Comment by RaduBerinde** [comment]
The exact SQL string should be available. We typically don't print that anywhere because it can contain passwords :/

**Comment by RaduBerinde** [comment]
We can definitely show it if it's only with a certain verbosity though.

**Comment by jordanlewis** [comment]
@mjibson, could you fix this please?

**Comment by knz** [comment]
we fixed this
