### ISSUE TITLE
storage: follower reads should respect transaction uncertainty window

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#36220]
Forked from #36022.

Currently, a follower read is allowed for a transaction as long as the transaction's read timestamp (`orig.forward(refresh)`) is closed out. This is insufficient to ensure that a transaction will see all writes in its uncertainty window. We should fix this in both `followerreadsccl. canSendToFollower` and `Replica.canServeFollowerRead`.

@bdarnell mentioned in the other issue:

> I think follower reads can only be safe if the entire uncertainty window is less than the closed timestamp. I'm not sure whether we can use ObservedTimestamps for this at all or if we have to use the worst-case MaxTimestamp for the transaction.

@bdarnell could you expand on this? I was thinking that we could use the ObservedTimestamp of the current leaseholder to enforce an upper bound on this uncertainty window. The logic would be similar to what we have in [`Replica.limitTxnMaxTimestamp`](https://github.com/cockroachdb/cockroach/blob/3dc90223414590b110985f29a8c469afb2b63b5d/pkg/storage/replica.go#L1290).

The determination of which observed timestamp is relevant is complicated though (especially on the client-side of this) so it's probably not worth being tricky here. Forwarding the minimum acceptable closed timestamp to the transaction's MaxTimestamp should be sufficient, so we should probably go with that to start.

**Comment by bdarnell** [comment]
> @bdarnell could you expand on this? I was thinking that we could use the ObservedTimestamp of the current leaseholder to enforce an upper bound on this uncertainty window.

That was my first thought too, but what if the last leaseholder our follower knows about has transferred the lease away? There are a lot of subtleties here. Since we're looking at adding a worst case of 500ms uncertainty offset to a closed timestamp that lags by 30+ seconds, it doesn't seem like it's worth the risk.

**Comment by ajwerner** [comment]
I posted a draft PR with no testing to make sure I understand the discussion here. PTAL.
