### ISSUE TITLE
opt: AssociateJoin should push down transitive equalities

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#36226]
Consider this schema+query:

```
exec-ddl
CREATE TABLE parent1 (pid1 INT PRIMARY KEY, pa1 INT)
----

exec-ddl
CREATE TABLE child1 (
  pid1 INT,
  cid1 INT,
  ca1 INT,
  PRIMARY KEY(pid1, cid1)
)
INTERLEAVE IN PARENT parent1 (pid1)
----

exec-ddl
CREATE TABLE grandchild1 (
  pid1 INT,
  cid1 INT,
  gcid1 INT,
  gca1 INT,
  PRIMARY KEY(pid1, cid1, gcid1)
)
INTERLEAVE IN PARENT child1 (pid1, cid1)
----

memo join-limit=4
SELECT * FROM grandchild1
JOIN child1 USING (pid1, cid1)
JOIN parent1 USING (pid1)
ORDER BY pid1
----
```

There's a transitive equality which in theory should get pushed down, but since the rule that generates those is a norm rule, it doesn't get applied to the expression generated by AssociateJoin, and we end up with a cross join where we shouldn't.

**Comment by RaduBerinde** [comment]
@rytaft this is the same as #38716 - can you confirm that #41250 fixes the case in this issue as well? (maybe add it as a test)

**Comment by rytaft** [comment]
Added as a test - thanks!
