### ISSUE TITLE
Prefix extractor / iterator broken on node restart with multiple stores configured

### ISSUE THREAD

**Issue by spencerkimball** [cockroachdb/cockroach#3624]
In three terms, execute the following commands:

Term 1: `rm -rf /tmp/d1 ; ./cockroach init --stores=ssd=/tmp/d1; ./cockroach start --stores=ssd=/tmp/d1  --addr=127.0.0.1:8001 --insecure --gossip=127.0.0.1:8001`

Term 2: `rm -rf /tmp/d2 ; ./cockroach start --stores=ssd=/tmp/d2  --addr=127.0.0.1:8002 --insecure --gossip=127.0.0.1:8001`

Term 3: `rm -rf /tmp/d3 /tmp/d4 ; ./cockroach start --stores=ssd=/tmp/d3,ssd=/tmp/d4  --addr=127.0.0.1:8003 --insecure --gossip=127.0.0.1:8001`

Then kill the running cockroach node in Term 3, and restart it with:

Term 3: `./cockroach start --stores=ssd=/tmp/d3,ssd=/tmp/d4  --addr=127.0.0.1:8003 --insecure --gossip=127.0.0.1:8001`

You'll notice that the node fails as soon as it tries to initialize the stores at `/tmp/d4`. From doing my own investigation, it appears that the `storeIdent` store metadata record is in fact present, but is not readable using `MVCCGet` (which uses the prefix iterator), only `engine.Scan` (which uses a total order iterator).

**Comment by tschottdorf** [comment]
this looks related to some issues I've been having running the acceptance tests with more than one store in #3582.

**Comment by petermattis** [comment]
Easier reproduction:

```
rm -rf /tmp/d1 /tmp/d2 ; ./cockroach init --stores=ssd=/tmp/d1; ./cockroach start --stores=ssd=/tmp/d1,ssd=/tmp/d2 --addr=127.0.0.1:8001 --insecure --gossip=127.0.0.1:8001
```

Wait till node is running and then kill and restart with:

```
./cockroach start --stores=ssd=/tmp/d1,ssd=/tmp/d2 --addr=127.0.0.1:8001 --insecure --gossip=127.0.0.1:8001
...
F0105 15:15:52.428235 52370 server/node.go:364  storage/store.go:805: store [ssd]=/tmp/d2 is not-empty and has invalid contents (first key: "/Local/Store/storeIdent")
```

Investigating...

**Comment by petermattis** [comment]
This is very very strange. I can reproduce by changing `Store.Bootstrap` to `Flush` the engine after writing the store-ident-key and then try to read it back again. And this fails. The key is definitely on disk, but rocksdb fails to find it when doing a "prefix" seek. Digging down into rocksdb I can definitely see that the key is in the sstable, but it isn't being found in the index due to the sequence number in the index being greater that the sequence number of the key being searched for. (These are internal rocksdb sequence numbers). Trying to track down what is going on with these sequence numbers, but this is all very strange.

**Comment by tschottdorf** [comment]
I'm amazed you even manage to dig down into RocksDB that deep. Would be interested in seeing what you're doing there.

**Comment by petermattis** [comment]
@tschottdorf: Slow printf debugging. :(

**Comment by petermattis** [comment]
Btw, since this seems to be a problem in RocksDB I checked whether it is still present in RocksDB 4.1. It is.

**Comment by petermattis** [comment]
Looks like this is a bug in RocksDB's handling of prefix iteration when the sstable index is very small. In this test above, the index contains a single entry (because the sstable contains a single entry). The fix is pretty small. Going to try and work up a test case to send upstream.

**Comment by tschottdorf** [comment]
Cool. That's a little scary though, are we on unchartered territory with
our use case there?

**Comment by petermattis** [comment]
I think we might just be tickling an obscure corner case. Maybe.

**Comment by petermattis** [comment]
https://github.com/facebook/rocksdb/pull/923

**Comment by spencerkimball** [comment]
Wow, impressive debugging! Thanks for fixing this.
