### ISSUE TITLE
storage: raftLogQueue locking causes contention on large machines

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#36251]
A mutex profile on a 3-node 32-core high CPU cluster running KV0 with 1024 splits (I ran it with a variety of concurrencies) reveals that the vast majority of time is spent waiting on the raftLogQueue.maybeAdd.

![Screenshot_2019-03-27 cockroach delay](https://user-images.githubusercontent.com/1839234/55116987-962cba00-50bf-11e9-9e15-b4e7545822ca.png)

It seems possible to reconsider this locking in a targeted way given that a CPU profile for this looks like it's mostly accessing system and replica state rather than queue state.

![Screenshot_2019-03-27 cockroach cpu(1)](https://user-images.githubusercontent.com/1839234/55116989-988f1400-50bf-11e9-8eee-36227c01938e.png)

**Comment by tbg** [comment]
https://github.com/cockroachdb/cockroach/issues/36262 should be of service with that because it can help us remove that queue altogether.

**Comment by tbg** [comment]
BTW, I'm curious how this looks on 19.2+, since I made that change to make adding to the queues async. (The work is still being done which is annoying, but at least it won't be blocking the hot path any more).
