### ISSUE TITLE
Crash Due to EvalContext.ActiveMemAcc on 2.1

### ISSUE THREAD

**Issue by cindyzqt** [cockroachdb/cockroach#36257]
We meed the crash issue due to EvalContext.ActiveMemAcc on Release 2.1. And I see you guys already check in the fix into the master branch:

https://github.com/cockroachdb/cockroach/pull/34935/commits

May I know when you guys are going to merge it into 2.1?

This is a bit urgent for us.

Thanks!

**Comment by yuzefovich** [comment]
cc @jordanlewis

**Comment by cindyzqt** [comment]
@yuzefovich thanks for the help!

@jordanlewis May I know when you are planning merge this fix into 2.1? The crash issue is blocking us.

**Comment by jordanlewis** [comment]
Hi @cindyzqt,

I'm working on it, unfortunately it's not a simple backport so it's taken a while. Can you provide a query and schema that causes the crash?

**Comment by cindyzqt** [comment]
@jordanlewis 
thanks for the reply! Attached are the schema and query. 
[problems.zip](https://github.com/cockroachdb/cockroach/files/3027607/problems.zip)

**Comment by cindyzqt** [comment]
Hi @jordanlewis ,
Here is the missing table schema.
[scenic.txt](https://github.com/cockroachdb/cockroach/files/3056922/scenic.txt)

**Comment by jordanlewis** [comment]
@cindyzqt sorry for the delay, I've merged the fix into the 2.1 release branch. If you can build yourself, you should be good to go - otherwise wait until the next 2.1 release is created.

**Comment by cindyzqt** [comment]
@jordanlewis 
thanks Jordon! We could build it by ourself. :)
