### ISSUE TITLE
stats: excessive SELECTs against the system.table_statistics

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#36284]
On a cluster running TPCC, we are seeing a huge number of queries against the table_statistics cache:

![image](https://user-images.githubusercontent.com/16544120/55181066-3d156280-5161-11e9-898a-bd1fd6ca2ad1.png)

Note that the latency of the query is huge (3s). I suspect that it's caused by the following: when we have a new statistic, we get a signal through gossip to invalidate that entry in the stats cache. At that point, every query that comes in will try to update the statistics by running the same SELECT query. This in turn makes this query really slow (it's hitting a single range very hard), which increases the window of time where we don't have a table statistic.

The fix is for just the first query to update the stats and have everyone else wait for that info to come in.

**Comment by ajwerner** [comment]
I feel relatively confident this is related to https://github.com/cockroachdb/cockroach/issues/35290

@awoods187 currently has a cluster which is failing TPC-C on a workload he suspects should pass and it too was experiencing a very high volume of these queries and was setting them also take seconds.

**Comment by RaduBerinde** [comment]
Another interesting piece of data, pointed out by @nvanbenschoten, a CPU usage graph:

![image](https://user-images.githubusercontent.com/16544120/55181655-77cbca80-5162-11e9-8e99-bbb88a1cbea6.png)

The valleys correspond to periods where auto stats were disabled. The yellow corresponds to the node that's the leaseholder for the `system.table_statistics` range.

**Comment by ajwerner** [comment]
![Screenshot_2019-03-28 Distributed Dashboard Cockroach Console(2)](https://user-images.githubusercontent.com/1839234/55182089-66cf8900-5163-11e9-9e77-d0fbca9a37da.png)

**Comment by andy-kimball** [comment]
Great job in figuring this one out.

**Comment by RaduBerinde** [comment]
I cooked up PR #36300 to fix this. It would be fantastic if we could try upgrading the cluster to a build with this patch and see what happens. I think this was @vivekmenezes's cluster?
