### ISSUE TITLE
sql: metrics for number of authenticated sessions by method

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#36280]
Authenticating SQL connections can be an expensive process, especially when using password auth (this is intentional, passwords checks are made expensive to deter brute force attacks).

We should expose a metric of the running count of authentication operations per method (password vs cert vs gssapi vs ...) and status (authentication succeeded or failed).

CC: @jordanlewis 

Jira issue: CRDB-4511

**Comment by Txiaozhe** [comment]
Hi @mberhault 
For this issue, my understanding is statistic the counts of authenticating SQL connections by(password, cert and gssapi ...) and display it in UI, maybe in order to prevent malicious attacks.
Is this your real intention?
And if you don't start implementing it yet, can I try it? Thanks :)

**Comment by mberhault** [comment]
Just having a metric recorded would be sufficient. The metrics are exported in the prometheus endpoint, and the UI knows how to fetch built-in metrics, so that part can be done separately. How and where to display it in the UI is still to be determined, we do not currently have a good mechanism to bring things to the operator's attention in the UI.

Go ahead, I wasn't planning on working on this anytime soon. Please let us know if you need any pointers.

**Comment by Txiaozhe** [comment]
Thank you for your attention and answer :) I will try it!

**Comment by piyush-singh** [comment]
This recently has come up several times with various customers having DoS issues when connections to the DB are not kept alive very long. The constant re-authentication can result in all sorts of weird symptoms. Tracking this as a request on the UI side as well. cc @rkruze @mattcrdb

**Comment by rafiss** [comment]
Related to https://github.com/cockroachdb/cockroach/issues/66014 which is for adding a connection latency metric (which includes time to authenticate)
