### ISSUE TITLE
backupccl,changefeedccl: use changefeeds for continuous backups

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#36290]
We currently support full backups and incremental backups, but now that we have all the infrastructure for changefeeds, we could build continuous backups. A very simple prototype of this could be a full backup + a cloud storage sink changefeed `WITH cursor=<backup timestamp>`. This requires no code change and could be run today. Then, to actually make use of it, we'd build somthing that restored the backup and then replayed the data in the cloud sink changefeed, correctly interpretly resolved timestamps.

**Comment by shermanCRL** [comment]
This describes what we intend to do in #56932.
