### ISSUE TITLE
sql: tuple mixing ints and floats causing panic

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#3633]
... and even when it doesn't crash, I think using an index when a type conversion is involved is completely broken, since the literals don't have their types inferred early enough and are encoded with the wrong type in the index spans. Unless I'm missing something?

```
CREATE TABLE a2 (a FLOAT PRIMARY KEY)
INSERT INTO a2 VALUES (2.1)
SELECT * FROM a2 WHERE a IN (1.1, 2)
```

```
panic: unsupported comparison: int to float

goroutine 8596 [running]:
github.com/cockroachdb/cockroach/sql/parser.DInt.Compare(0x2, 0x6d661b0, 0xc8203eac10, 0x0)
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/sql/parser/datum.go:153 +0x2b8
github.com/cockroachdb/cockroach/sql/parser.(*DInt).Compare(0xc8203eac20, 0x6d661b0, 0xc8203eac10, 0x58f9fa0)
	<autogenerated>:193 +0xa3
github.com/cockroachdb/cockroach/sql/parser.DTuple.Less(0xc8205a7760, 0x2, 0x2, 0x1, 0x0, 0x4f225d0)
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/sql/parser/datum.go:558 +0x77
github.com/cockroachdb/cockroach/sql/parser.(*DTuple).Less(0xc8205a77a0, 0x1, 0x0, 0x4fb0b60)
	<autogenerated>:148 +0xb5
sort.insertionSort(0x6db6cb0, 0xc8205a77a0, 0x0, 0x2)
	/usr/local/go/src/sort/sort.go:32 +0x6f
sort.quickSort(0x6db6cb0, 0xc8205a77a0, 0x0, 0x2, 0x4)
	/usr/local/go/src/sort/sort.go:184 +0x153
sort.Sort(0x6db6cb0, 0xc8205a77a0)
	/usr/local/go/src/sort/sort.go:199 +0x74
github.com/cockroachdb/cockroach/sql/parser.(*DTuple).Normalize(0xc8205a77a0)
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/sql/parser/datum.go:567 +0x48
github.com/cockroachdb/cockroach/sql/parser.(*ComparisonExpr).normalize(0xc8200fcb40, 0xc8201ae190, 0x0, 0x0)
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/sql/parser/normalize.go:195 +0xd0d
github.com/cockroachdb/cockroach/sql/parser.(*normalizeVisitor).Visit(0xc8201ae190, 0x6d66dc8, 0xc8200fcb40, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/sql/parser/normalize.go:330 +0x119
github.com/cockroachdb/cockroach/sql/parser.WalkExpr(0x6d66f40, 0xc8201ae190, 0x6d66dc8, 0xc8200fcb40, 0x0, 0x0)
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/sql/parser/walk.go:214 +0xce
github.com/cockroachdb/cockroach/sql/parser.(*Parser).NormalizeExpr(0xc8201aa0e8, 0x1, 0xece1e7385, 0x1382df66, 0x58cb600, 0xece1e7385, 0x1382df66, 0x58cb600, 0xc8200ff190, 0xc8204d05a0, ...)
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/sql/parser/parse.go:88 +0x102
github.com/cockroachdb/cockroach/sql.(*scanNode).initWhere(0xc8206523c0, 0xc8205a7320, 0x0, 0x0)
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/sql/scan.go:375 +0x2c6
github.com/cockroachdb/cockroach/sql.(*planner).selectWithScan(0xc8201aa000, 0xc8206523c0, 0xc8205a40a0, 0x0, 0x0, 0x0, 0x0)
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/sql/select.go:51 +0xfe
github.com/cockroachdb/cockroach/sql.(*planner).Select(0xc8201aa000, 0xc8205a40a0, 0x0, 0x0, 0x0, 0x0)
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/sql/select.go:43 +0xaf
github.com/cockroachdb/cockroach/sql.(*planner).makePlan(0xc8201aa000, 0x6d66e40, 0xc8205a40a0, 0x0, 0x0, 0x0, 0x0)
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/sql/plan.go:124 +0x136a
github.com/cockroachdb/cockroach/sql.(*Executor).execStmt.func1(0xece1e7385, 0xc81382df66, 0x58cb600, 0x0, 0x0)
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/sql/executor.go:310 +0xd9
github.com/cockroachdb/cockroach/sql.(*Executor).execStmt.func2(0xc8201d4c60, 0x0, 0x0)
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/sql/executor.go:386 +0x12e
```

**Comment by JackKrupansky** [comment]
Yeah, there really isn't any implicit type conversion in CockroachDB at this stage. I'm in the middle of doing some research on what Postgres does for type conversion and what CockroachDB does. Postgres is fairly rich, CockroachDB not so much at this stage.

The code is sorting the IN clause value list, which fails because the values are not all of the same type - you have a float and then an int.

Yeah, for now you need to manually make sure all your values are of the declared column type or explicitly cast them.

There is also a TODO in encodeIndexKey in table.go: "Need to convert the values[i] value to the type expected by the column." The encodeTableKey function in table.go simply uses the given value rather than the declared type of the column. Postgres does this implicit conversion.

**Comment by petermattis** [comment]
That `SELECT` statement should fail type-checking. Would be good to figure out why it isn't.

**Comment by andreimatei** [comment]
So there were two issues here: 1) this particular crash, having to do with tuple normalization that just sorts the elements using `datum.Compare()` instead of the `compOps` used elsewhere (which can handle mixed types) and 
2) we naively create index spans using the data type of the literals, as opposed to the data type of the column they map to. This didn't use to be a problem since the type-checker used to reject queries where the type of the literal didn't match, but since recently we started allowing comparing ints and floats (just comparing for now, no other arithmetic). Maybe this is also a problem for inserting data, as per the TODO @JackKrupansky pointed to, or maybe inserts that mix types still fail the type-checker; I'll verify.

Let's leave this bug for 1) and address 2) separately.

**Comment by petermattis** [comment]
I believe we expect this bug to be fixed by the new typing system, but that isn't targeted for beta. Is there a shorter term fix available?

**Comment by andreimatei** [comment]
yeah, there's got to be a way to avoid this crash by using compOps in Datum.Compare. Will do.
