### ISSUE TITLE
storage: SSTable to be imported has 6 live copies in memory

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#36347]
While investigating a cluster with a stuck AddSSTable request that's getting constantly reproposed and rejected by Raft (to be filed elsewhere) and looking at heap profiles, it would appear that an SSTable is present 6 times in memory. It's hard for me to say how many copies of the thing there should ideally be (I'm rooting for one), but 6 seems too damn much.

Check out the allocation flame graph:
![flame](https://user-images.githubusercontent.com/377201/55259440-052f1d80-523c-11e9-8022-d604e6a28b04.png)

All the highlighted regions are ~33MB slots, all presumably pertaining to one AddSSTable that's constantly being reproposed.

1: AddSSTable request in a BatchRequest
2: defaultSubmitProposalLocked makes a copy, held alive by the proposals map in the replica
3: refreshProposalsLocked makes a copy to repropose. reproposing because of RaftReady
4: raft.maybeSendAppend reads the log entry (from disk?) to decide if it needs to send proposals. This guy doesn't seem to need to deal with sideloaded data.
5: another reproposal, this time because of ReasonTick
6: protouil.Marshall. This is a copy of #5?

raw heap profile
[heap.zip](https://github.com/cockroachdb/cockroach/files/3024333/heap.zip)

cc @bdarnell @petermattis @dt @ajwerner @tbg @nvanbenschoten

**Comment by dt** [comment]
on the same topic, though I don't see it in that profile: I think there might be another copy made during `EvalAddSSTable` when we make a memory-backed "file" for the sst iterator and then "write" the content to said file. I've been meaning to dust off a branch that implements a leveldb "file" directly on top of a `[]byte` to avoid that copy.

**Comment by nvanbenschoten** [comment]
I've had a change to remove the copy in `defaultSubmitProposalLocked` floating around for a little while. I put part of it up in a PR here: #36392. This should address some of these highlighted regions.

:plause: for this issue. We should open more like it!
