### ISSUE TITLE
The probability description of MakePriority function does not hold

### ISSUE THREAD

**Issue by yaojingguo** [cockroachdb/cockroach#3643]
Comment one for `MakePriority` in [data.go]:

```
// MakePriority generates a random priority value, biased by the
// specified userPriority. If userPriority=100, the resulting
// priority is 100x more likely to be probabilistically greater
// than a similar invocation with userPriority=1.
```

The likelihood should be computed in the following way:

```
max = math.MaxInt32
top = max/userPriority # The fraction part of the quotient will be discarded here.
bottom = max-top
P(1's resulting priority is bigger that 100's) = (top/max) * (1-(1/top))/2
P(100's resulting priority is bigger that 1's) = bottom/max + P(1's resulting priority is bigger that 100's)
likelihood = P(100's resulting priority is bigger that 1's) / P(1's resulting priority is bigger that 100's)
```

So the likelihood should be roughly `199` instead of `100`. Another problem of the
comment is that for two big user priority values, the resulting priorities
are always equal to each other. For example, user priority `0x40000000` and user priority 
`0x5fffffff` always result the same priority `0x7fffffff`.

Comment two for `MakePriority` in [data.go]:

```
// The idea here is to bias selection of a random priority from the
// range [1, 2^31-1) such that if userPriority=100, it's 100x more
// likely to be a higher int32 than if userPriority=1. The formula
// below chooses random values according to the following table:
//   userPriority  |  range
//   1             |  all positive int32s
//   10            |  top 9/10ths of positive int32s
//   100           |  top 99/100ths of positive int32s
//   1000          |  top 999/1000ths of positive int32s
//   ...etc

```

The likelihood part has the problem as the previous comment. The range part of
the above comment should be:

```
//   userPriority  |  range
//   1             |  all positive int32s
//   10            |  top 1/10ths of positive int32s
//   100           |  top 1/100ths of positive int32s
//   1000          |  top 1/1000ths of positive int32s
//   ...etc
```

[data.go]: https://github.com/cockroachdb/cockroach/blob/master/roachpb/data.go

**Comment by spencerkimball** [comment]
@yaojingguo thanks for this great bug report. You're quite right that it was broken. I re-worked out the math and wrote a unittest and was about to send it for review but then I decided something was just really off with the way we were specifying priorities. For one thing, the multiple concept breaks down quickly as you increased the size of priority as you run into obvious limits. For another, there was no way to manually set a lower than average priority, which is something that's quite reasonable to do.

So I've replaced the previous notion of multiples of priority with just a manual priority value.

**Comment by spencerkimball** [comment]
I changed my mind on this. I've updated the associated PR to change user priority to a floating point value, which now allows us to bias to lower operation priorities (e.g. 0.1x). The floating point value is easier to reason about than just having an explicit int32 and it preserves the randomness between different operations with the same priorities.
