### ISSUE TITLE
View comments with SHOW

### ISSUE THREAD

**Issue by lhirata** [cockroachdb/cockroach#36439]
The `COMMENT ON` statement was added, which adds comments to a [database](https://github.com/cockroachdb/cockroach/pull/33057), [table](https://github.com/cockroachdb/docs/issues/4182),  or [column](https://github.com/cockroachdb/docs/issues/4262).

However, only `SHOW TABLES ... WITH COMMENTS` was added. We need also need to add:

- [ ] `SHOW DATABASES ... WITH COMMENTS`
- [ ] `SHOW COLUMNS ... WITH COMMENTS`

cc @knz

**Comment by Gurio** [comment]
@lhirata: This issue is obsolete due to #37174 and #37175 have been merged, isn't it?

**Comment by jordanlewis** [comment]
@Gurio yes, you are right. Thanks.
