### ISSUE TITLE
core: large imbalance of replicas after restore 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#36448]
I restored TPC-C 5k into an 8 node geo-distributed cluster and ended up with a large imbalance of replicas:
![image](https://user-images.githubusercontent.com/22278911/55447004-ff18a400-558f-11e9-9262-bb8057bf8780.png)

roachprod create $CLUSTER -n 10 --gce-machine-type=n1-standard-16 --geo
roachprod run $CLUSTER --  "DEV=$(mount | grep /mnt/data1 | awk '{print $1}'); sudo umount /mnt/data1; sudo mount -o discard,defaults,nobarrier ${DEV} /mnt/data1/; mount | grep /mnt/data1"
roachprod stage $CLUSTER:1,3-9 cockroach
roachprod stage $CLUSTER:2 workload
roachprod start $CLUSTER:1,3-9
roachprod adminurl --open $CLUSTER:1
roachprod run $CLUSTER:1 -- "./cockroach workload fixtures import tpcc --warehouses=5000 --db=tpcc"

I accidentally forgot to stage and start one node; which I did after the restore was completed. I don't expect this affected the above scenario but thought I'd mention in case it does. 
roachprod stage $CLUSTER:10 cockroach
roachprod start $CLUSTER:10

Version v19.1.0-beta.20190318-598-geef79e8

Debug.zip
https://drive.google.com/open?id=1BXoCoJaoxFMIG8D_7XKVgCNy-NUEM2-6

**Comment by awoods187** [comment]
Hm now that I think about it it's probably because there are only two nodes in those az (because I forgot to start the last node). So we would try to balance everything among AZ's but there are only two nodes for 1/3 of the replicas. 

```
  andy-okr4-0001	andy-okr4-0001.us-east1-b.cockroach-ephemeral	10.142.0.171	35.231.237.7
  andy-okr4-0002	andy-okr4-0002.us-east1-b.cockroach-ephemeral	10.142.0.169	35.237.35.164
  andy-okr4-0003	andy-okr4-0003.us-east1-b.cockroach-ephemeral	10.142.0.168	34.73.232.46
  andy-okr4-0004	andy-okr4-0004.us-east1-b.cockroach-ephemeral	10.142.0.170	35.237.36.166
  andy-okr4-0005	andy-okr4-0005.us-west1-b.cockroach-ephemeral	10.138.0.73	35.203.174.61
  andy-okr4-0006	andy-okr4-0006.us-west1-b.cockroach-ephemeral	10.138.0.74	35.197.87.162
  andy-okr4-0007	andy-okr4-0007.us-west1-b.cockroach-ephemeral	10.138.0.72	35.230.10.30
  andy-okr4-0008	andy-okr4-0008.europe-west2-b.cockroach-ephemeral	10.154.0.55	35.246.116.84
  andy-okr4-0009	andy-okr4-0009.europe-west2-b.cockroach-ephemeral	10.154.0.56	35.246.83.40
  andy-okr4-0010	andy-okr4-0010.europe-west2-b.cockroach-ephemeral	10.154.0.54	35.246.60.105
```

**Comment by tbg** [comment]
You have 4.5k*6 = 27k replicas in one locality and 13.5k in the other, which is exactly a 2:1 split. You have ~40k replicas in total, so around 13k ranges. Each of these ~13k ranges wants to have a replica in either locality, so you expect ~7k replicas on each of the two nodes in the small locality, which is consistent with what you're seeing. Beyond that, I suppose the allocator decides to put the other two replicas in the large locality because that's where all of the capacity is, basically. This decision seems to make sense given the circumstances.
