### ISSUE TITLE
sql: expose query plan in crdb_internal.stmt_statistics

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#36482]
This will be useful (I'd even guess *very useful*) because that will automatically include them in `debug zip`s. The data is already there, just not printed. We should generally print all of the data that we have in the internal table.

@jordanlewis this seems really simple, but there seems to be some "sensitive details" discussion involved that I'm not aware of, so tossing this your way.  Could be an easy starter project too (if you can live without it in 19.1.0).

Jira issue: CRDB-4497

**Comment by asubiotto** [comment]
Note: there are some UX concerns

**Comment by yuzefovich** [comment]
I think this was done long time ago in cb5a4b568ec8f581ff8df60f38e5f04f2f7f70d1.
