### ISSUE TITLE
Update labs that gave GUI URLs to include navigation steps

### ISSUE THREAD

**Issue by gpasmore** [cockroachdb/cockroach#36493]
**Is your feature request related to a problem? Please describe.**
This is a suggestion to make it easier to learn the Admin UI from the labs

**Describe the solution you'd like**
Many of the labs include navigaytion steps.  For instance, https://www.cockroachlabs.com/docs/stable/training/under-replication-troubleshooting.html shows the UI navigation in steps 1-3.

Some just give a URL.  https://www.cockroachlabs.com/docs/stable/training/data-unavailability-troubleshooting.html step 5 incudes the URL http://localhost:8080/#/reports/problemranges.

The problem with only giving the URL is that I could not figure out how to navigate to that screen. I can only get to it if I type in the url.

**Comment by piyush-singh** [comment]
Hey @gpasmore thanks for flagging this issue. I went ahead and opened a corresponding issue in our docs repo here cockroachdb/docs#4625

As a side note, the reason for these discrepancies is that the pages without navigation steps are exposed as experimental debug pages, and these pages were not navigable prior to our 2.1 release when we created navigation to link to our debug pages. Now that we have this link, some navigation instructions would certainly be helpful. Thank you for your suggestion.
