### ISSUE TITLE
ui: latency hits apparent reporting limit of 10s

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#36543]
It appears as if we hit a limit on reported latency:
![image](https://user-images.githubusercontent.com/22278911/55582971-be836c80-56ee-11e9-9229-724242688e59.png)

Perhaps this is due to sampling of the query stats? 
Perhaps its due to another sampling constraint? 

Either way it looks like we are underreporting here.

**Comment by vilterp** [comment]
I think this is a known issue with our histograms; remember Matt T mentioning it. Can't find the issue at the moment though.
