### ISSUE TITLE
ui: page becomes unavailable 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#36544]
On both GCP and AWS the admin will stop loading and present a blank page. I can only get to it by reopening with:

`roachprod adminurl --open $CLUSTER:1 --ips`

**Comment by vilterp** [comment]
So you were looking at the admin UI, it worked for a while, then went blank at some point? Which page were you looking at? Then, later you opened the admin UI again via roachprod, and it worked?

This sounds like a JS error. If you open the Chrome devtools and screenshot the output of the Console tab, we'll be able to see a traceback. With repro steps, maybe Piyush can get that.

![image](https://user-images.githubusercontent.com/7341/55591304-30fe4780-5703-11e9-984d-e28452d8c4c3.png)
