### ISSUE TITLE
engine: in tests: [rocksdb] Error when reading  dir

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#36568]
Run `make test PKG=./pkg/storage TESTFLAGS=-v` and look for

> E190405 10:57:48.941966 11027 storage/engine/rocksdb.go:105  [rocksdb] Error when reading  dir

This probably new with #36506. I assume the error is related to in-mem engines (which have an empty directory which looks like what's printed in the message).

This is mildly distracting, perhaps we can suppress these (or fix RocksDB to not log whatever this is as ERROR, it doesn't seem to cause any problems).

@ajkr, would you mind taking a look?

**Comment by tbg** [comment]
Heh, easier repro (and unfortunately very user-visible):

```
./cockroach-linux-2.6.32-gnu-amd64 demo
E190406 10:41:41.201004 1 storage/engine/rocksdb.go:105  [rocksdb] Error when reading  dir
E190406 10:41:41.216368 1 storage/engine/rocksdb.go:105  [rocksdb] Error when reading  dir
#
# Welcome to the CockroachDB demo database!
#
# You are connected to a temporary, in-memory CockroachDB
# instance. Your changes will not be saved!
#
# Web UI: http://127.62.170.67:42245
#
# Server version: CockroachDB CCL v19.1.0-beta.20190318-691-g5c2dfdd (x86_64-unknown-linux-gnu, built 2019/04/05 18:24:48, go1.11.6) (same version as client)
# Cluster ID: 07b9a699-8b1c-4580-bfcc-d2abb214cf50
#
# Enter \? for a brief introduction.
#
root@127.62.170.67:41729/defaultdb>
```

**Comment by andreimatei** [comment]
I've ran into this too and bisected it to #36408

**Comment by jordanlewis** [comment]
It also prints when you run `./cockroach demo` :)

**Comment by ajkr** [comment]
Ack will look tonight

**Comment by tbg** [comment]
> Ack will look tonight

How about you enjoy your Sunday instead :) This can wait until tomorrow.
