### ISSUE TITLE
storage: faux merge queue activity during import

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#36579]
This is the merge queue during https://github.com/cockroachdb/cockroach/pull/36565

<img width="776" alt="image" src="https://user-images.githubusercontent.com/5076964/55649097-6af24b00-57e2-11e9-858c-e7301ade5ec7.png">

My alarm bells went off because we're not supposed to be merging ranges during import. But now I'm tailing the logs and there aren't any merges going on. I think we're continually deciding not to merge, but somehow the graph makes this look as if merges were happening "successful actions".

This seems to be because the queue setup we use has no channel for communicating that processing can be a noop:

https://github.com/cockroachdb/cockroach/blob/447fe7d6023a3db7473445944ae3693f0f286d17/pkg/storage/queue.go#L752-L758

**Comment by irfansharif** [comment]
Looking at the `queueImpl` interface for processing Replicas, we see that it has no way of communicating if the processing was simply skipped/was a noop. We only return an error, which if nil, is interpreted to be a successful action.

```go
type queueImpl interface {
        // [...]

	// process accepts a replica, and the system config and executes
	// queue-specific work on it. The Replica is guaranteed to be initialized.
	process(context.Context, *Replica, *config.SystemConfig) error
```

Consider the merge queue implementation:
```go
func (mq *mergeQueue) process(
	ctx context.Context, lhsRepl *Replica, sysCfg *config.SystemConfig,
) error {
	// [...]

	lhsStats := lhsRepl.GetMVCCStats()
	minBytes := lhsRepl.GetMinBytes()
	if lhsStats.Total() >= minBytes {
		log.VEventf(ctx, 2, "skipping merge: LHS meets minimum size threshold %d with %d bytes",
			minBytes, lhsStats.Total())
		return nil
	}
```

Even if we're skipping the merge operation, we're going to increment our success counter metric, which makes for the confusing dashboard above. We could perhaps change the interface to return a bool alongside the error type to indicate if something was actually done. I suspect the other queue implementations would also benefit from such a thing. We'd want to test the queueImpl interface accordingly, and `pkg/kv/kvserver/queue_test.go` has other tests we could cargo cult from.

**Comment by irfansharif** [comment]
+cc @madelineliao, this is one of the starter projects I figured would be a good first thing to pick off.
