### ISSUE TITLE
decommissioning spike with over-provisioned cluster 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#36583]
Ran a decommissioning test with plenty of extra capacity:
![image](https://user-images.githubusercontent.com/22278911/55654046-41bfc380-57be-11e9-88ff-d05c5e6d0e73.png)

The test was able to produce short windows of extreme latency spikes during decommissioning. 

We see QPS drop when the node finally decommissions which is surprising to me because it should still be overprovisioned even though that AZ lost a node.

We also see very chunky replicas per node shifting including a ~1hr long flatline before dropping from 1000 replicas to zero. 

Decommissioning took 1hr26m (19:18-17:52).

```
set -euxo pipefail

export CLUSTER=andy-okr4
roachprod create $CLUSTER -n 10 --gce-machine-type=n1-standard-16 --geo --gce-zones=us-east1-b --gce-zones=us-east1-c --gce-zones=us-east1-d

roachprod run $CLUSTER --  "sudo umount /mnt/data1; sudo mount -o discard,defaults,nobarrier /mnt/data1/; mount | grep /mnt/data1"

roachprod stage $CLUSTER:1,3-10 cockroach
roachprod stage $CLUSTER:2 workload

roachprod start $CLUSTER:1,3-10 

roachprod adminurl --open $CLUSTER:1

roachprod run $CLUSTER:1 -- "./cockroach workload fixtures import tpcc --warehouses=3000 --db=tpcc"

roachprod run $CLUSTER:2 "./workload run tpcc --ramp=10m --warehouses=3000 --active-warehouses=3000 --tolerate-errors --duration=10h --split --scatter {pgurl:1,3-10}"

Wait 10m

Roachprod ssh $CLUSTER:3
./cockroach quit --decommission --insecure

```

Version:
v19.1.0-beta.20190318-684-gaf621b3

**Comment by awoods187** [comment]
CPU spike 
![image](https://user-images.githubusercontent.com/22278911/55655150-5d789900-57c1-11e9-92a8-30cb2b999604.png)

**Comment by awoods187** [comment]
The debug.zip is hung for at least 10m:
```
Andrews-MBP-2:~ andrewwoods$ roachprod run $CLUSTER:1 -- ./cockroach debug zip --url {pgurl:1} debug.zip
warning: --url specifies user/password, but command "zip" does not accept user/password details - details ignored
writing debug.zip
  debug/events.json
  debug/rangelog.json
  debug/liveness.json
  debug/settings.json
  debug/reports/problemranges.json
  ^- resulted in rpc error: code = DeadlineExceeded desc = context deadline exceeded
  debug/crdb_internal.cluster_queries.txt
  debug/crdb_internal.cluster_sessions.txt
  debug/crdb_internal.cluster_settings.txt
  debug/crdb_internal.jobs.txt
  debug/crdb_internal.kv_node_status.txt
  debug/crdb_internal.kv_store_status.txt
  debug/crdb_internal.schema_changes.txt
  debug/crdb_internal.partitions.txt
  debug/crdb_internal.zones.txt
  debug/nodes/1/status.json
  debug/nodes/1/crdb_internal.feature_usage.txt
  debug/nodes/1/crdb_internal.gossip_alerts.txt
  debug/nodes/1/crdb_internal.gossip_liveness.txt
  debug/nodes/1/crdb_internal.gossip_network.txt
  debug/nodes/1/crdb_internal.gossip_nodes.txt
  debug/nodes/1/crdb_internal.leases.txt
  debug/nodes/1/crdb_internal.node_statement_statistics.txt
  debug/nodes/1/crdb_internal.node_build_info.txt
```

**Comment by awoods187** [comment]
Also my nodes now look suspect even tho the cluster appears to be fine based on QPS:
![image](https://user-images.githubusercontent.com/22278911/55657407-1cd04e00-57c8-11e9-8809-66922a80477c.png)
![image](https://user-images.githubusercontent.com/22278911/55657421-2b1e6a00-57c8-11e9-8e9a-11b53d7be24c.png)

**Comment by awoods187** [comment]
Apparently, recommissioning is hung:
![image](https://user-images.githubusercontent.com/22278911/55657498-691b8e00-57c8-11e9-83bc-b6a43ae8d540.png)

**Comment by awoods187** [comment]
And this cluster also hit https://github.com/cockroachdb/cockroach/pull/36577

**Comment by awoods187** [comment]
I was able to repro this behavior (latency spike + uneven decommissioning) today:
![image](https://user-images.githubusercontent.com/22278911/55745830-25ae6300-5a06-11e9-9130-b3348b904e4f.png)
with the associated wide range in CPU:
![image](https://user-images.githubusercontent.com/22278911/55745865-437bc800-5a06-11e9-8900-01177980c331.png)

It took: 1 hr 7m (16:36 to 17:43) a bit faster than the above experiment

https://drive.google.com/open?id=11wtrUzAfvKxF7daUeT5ORisD0qMJUdha
Now I'm going to recommission the node.

**Comment by awoods187** [comment]
During recommissioning we see a latency spike/QPS drop as the node begins to add itself back to the cluster:
![image](https://user-images.githubusercontent.com/22278911/55747384-221cdb00-5a0a-11e9-87e1-d11db0bc4519.png)

**Comment by awoods187** [comment]
Major latency spike/qps drop during recommissioning:
![image](https://user-images.githubusercontent.com/22278911/55759538-93b75200-5a27-11e9-9bca-34baffec117a.png)

**Comment by awoods187** [comment]
The bad spikes were sustained toward the end of the experiment:
![image](https://user-images.githubusercontent.com/22278911/55763175-e7c83380-5a33-11e9-869b-9a5e4b035e30.png)

Recommissioning took 4hrs32m (22:47-18:15) as opposed to only 1hr to decommission the cluster from above.

**Comment by awoods187** [comment]
Tried `./cockroach node decommission 3 --insecure --wait all` today and saw it take 1hr51m (16:23-14:32) as opposed to the 1hr7m of `./cockroach quit --decommission --insecure`

**Comment by irfansharif** [comment]
I'm not sure what's to be done here. Decommissioning involves moving lots of data around and that can cause spikes in the system, unsurprisingly. Variability around how long a decommissioning process takes _is_ a problem but we not report, when done through the CLI, how many replicas are still left when trying to move them off a store. I'll close this.
