### ISSUE TITLE
Unexpected error when dropping an index

### ISSUE THREAD

**Issue by johnnylee** [cockroachdb/cockroach#36608]
**Describe the problem**

I was dropping some foreign key constraints and indexes from a table when I encountered this message: 

```pq: internal error: programmer error: not-searched index name found already qualified: core.public.pos_line_items@pos_line_items_auto_index_fk_locationid_ref_locations
DETAIL: resolver.go:421,resolver.go:392,resolver.go:140,resolver.go:391,drop_index.go:42,plan.go:799,plan.go:306,conn_executor_exec.go:770,conn_executor_exec.go:402,conn_executor_exec.go:96,conn_executor.go:1118,conn_executor.go:389,conn.go:313
HINT: You have encountered an unexpected error inside CockroachDB.

Please check https://github.com/cockroachdb/cockroach/issues to check
whether this problem is already tracked. If you cannot find it there,
please report the error with details at:

    https://github.com/cockroachdb/cockroach/issues/new/choose

If you would rather not post publicly, please contact us directly at:

    support@cockroachlabs.com

The Cockroach Labs team appreciates your feedback.
```

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**

I'm not certain how to reproduce the error. In our case we had a foreign key constraint on a table ~10GB in size. I altered the table to drop the constraint and then attempted to drop the index. 

**Expected behavior**

I expected to drop the index. 

**Additional data / screenshots**

**Environment:**
 - CockroachDB version 2.1.4
 - Server OS: Debian stable
 - Client app: cockroach sql interactive session

**Additional context**

It appears we have a DROP INDEX job that won't complete in our jobs list. Subsequent DROP INDEX calls on the same table appear to be blocked.

**Comment by vivekmenezes** [comment]
@johnnylee thanks for reporting this problem. It does appear that the drop index went through based on your reporting you see a DROP INDEX job in the jobs table. This job takes 24 hours to process by default so you should see it completed by now.

I'd appreciate it if you can paste the entire DROP INDEX command? thanks

**Comment by jordanlewis** [comment]
No repro available.
