### ISSUE TITLE
sql: count(*) returns syntax error when combined with parameters

### ISSUE THREAD

**Issue by mrtracy** [cockroachdb/cockroach#3660]
While testing, a parameterized query of the form:
```sql
SELECT COUNT(*)
FROM rangelog.event
WHERE eventType = $1
```

Fails with the following error:`pq: qualified name "*" not found`

The same query without parameters:
```sql
SELECT COUNT(*)
FROM rangelog.event
WHERE eventType = 'split'
```
Works as expected.

This was found while designing a test; I am going to use the non-parameterized form for now as a workaround.

**Comment by mjibson** [comment]
Should be fixed from #4037
