### ISSUE TITLE
backfill: canceled backfill job continues running on unstable cluster

### ISSUE THREAD

**Issue by lucy-zhang** [cockroachdb/cockroach#36621]
I encountered this on `release-19.1` (6da68d7fe2c9a29b85e2ec0c7e545a0d6bdc4c5c) while investigating #36091 (see that issue for more context).

Steps to reproduce:
```
roachprod create $CLUSTER -n 21
# (put cockroach and roachprod binaries)
roachprod run $CLUSTER:21 -- ./workload fixtures import bulkingest {pgurl:1} --a 2000000000 --b 1 --c 1 --index-b-c-a=false --payload-bytes 4
roachprod run $CLUSTER:21 -- ./workload run bulkingest {pgurl:1-20} --a 2000000000 --b 1 --c 1 --payload-bytes 4
```
Then in a sql shell:
```
create index on bulkingest.bulkingest (payload, a);
```
After about 2 hours, a few nodes OOMed and died (see https://github.com/cockroachdb/cockroach/issues/36091#issuecomment-480549352). At this point, I canceled the job. This didn't stop the index backfill immediately, and over the next 10 minutes, more nodes OOMed. I restarted the dead nodes, but due to a combination of rebalancing and continued high memory usage from the backfill, even more nodes died; I think one of the nodes that was restarted went from 0% to 70% RSS within 10 minutes. About 15 minutes after I first canceled the job, profiling revealed that every node was still spending time in AddSSTable calls.

I checked on the cluster again after an hour, and the AddSSTable calls had stopped, but I didn't see a rollback job in the jobs table, and more nodes had OOMed in the meantime.

I know that the index backfill job doesn't stop immediately when the job is canceled, but this amount of instability on a cluster that is already unhealthy due to the original job seems dangerous.

**Comment by vivekmenezes** [comment]
The OOMs were fixed by #36765
