### ISSUE TITLE
stability: long-period of over-replicated ranges during rebalancing 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#36623]
Thanks to @bdarnell's over-replication metric I noticed that during decommissioning we have a long period of time with over-replicated ranges: 

![image](https://user-images.githubusercontent.com/22278911/55745534-78d3e600-5a05-11e9-90b4-85b6eb09d1e5.png)

This is troubling due to our lack of atomic rebalancing (https://github.com/cockroachdb/cockroach/issues/12768).

v19.1.0-beta.20190318-701-g4eacf37

*Reproduction*
set -euxo pipefail

export CLUSTER=andy-okr4
roachprod create $CLUSTER -n 10 --gce-machine-type=n1-standard-16 --geo --gce-zones=us-east1-b --gce-zones=us-east1-c --gce-zones=us-east1-d
roachprod run $CLUSTER --  "sudo umount /mnt/data1; sudo mount -o discard,defaults,nobarrier /mnt/data1/; mount | grep /mnt/data1"
roachprod stage $CLUSTER:1,3-10 cockroach
roachprod stage $CLUSTER:2 workload
roachprod start $CLUSTER:1,3-10 
roachprod adminurl --open $CLUSTER:1
roachprod run $CLUSTER:1 -- "./cockroach workload fixtures import tpcc --warehouses=3000 --db=tpcc"
Roachprod ssh $CLUSTER:3
./cockroach quit --decommission --insecure

**Comment by bdarnell** [comment]
> This is troubling due to our lack of atomic rebalancing (#12768).

It's actually *caused by* the lack of atomic rebalancing. 

 The problem is this priority list: 

https://github.com/cockroachdb/cockroach/blob/365b2f9e2a5ed7ab1e2732be42e36a92be9b836d/pkg/storage/allocator.go#L54-L59

Removing an "extra" replica should actually be very high priority, probably between addMissingReplica and addDecommissioningReplacement.

**Comment by tbg** [comment]
@darinpp could you look into this? I think we'll want to have this rectified in 19.1.1, i.e. within the next month or so.

**Comment by darinpp** [comment]
Just bumping up the `removeExtraReplicaPriority` up the priority list doesn't have any effect. I'm taking another look into the logic to see why doesn't that have any effect.
![image](https://user-images.githubusercontent.com/7052693/56974951-b15a7180-6b24-11e9-977e-0e3b440d1ab5.png)

**Comment by darinpp** [comment]
I also tried scheduling the removal of the extra replica after a new one is added. This improved things a bit but there are still some replicas that linger while the queue is processed. 
![image](https://user-images.githubusercontent.com/7052693/57319617-d2d1d500-70b1-11e9-9be2-d159c3cedede.png)
