### ISSUE TITLE
schema: index backfill is taking 10 minutes to start

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#36667]
Just ran two schemachange/index/tpcc/w=100 runs on master and see that the CREATE INDEX is taking 10 minutes to start a backfill waiting on leases to expire on nodes. This is odd because when the schema change was written gossip should have updated the leases.

**Comment by lucy-zhang** [comment]
Closing this since I'm not sure we can repro this, and we're getting rid of gossip-based table lease updates soon anyway.
