### ISSUE TITLE
sql: several unimplemented features without a link to an issue

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#36664]
This list is in order of what customers have hit based on our telemetry.

- [ ] unimplemented.with recursive
- [ ] unimplemented.varbit_in()
- [ ] unimplemented.uuid_recv()
- [ ] unimplemented.uuid_in()
- [ ] unimplemented.textout()
- [ ] unimplemented.syntax.on conflict on constraint
- [ ] unimplemented.pg_catalog.pg_statio_user_tables
- [ ] unimplemented.pg_catalog.pg_sequences
- [ ] unimplemented.pg_catalog.pg_matviews
- [ ] unimplemented.oidin()
- [ ] unimplemented.namerecv()
- [ ] unimplemented.client_encoding latin1
- [ ] unimplemented.alter add fk
- [ ] unimplemented.varcharrecv()
- [ ] unimplemented.varcharin()
- [ ] unimplemented.varbit_recv()
- [ ] unimplemented.varbit_out()
- [ ] unimplemented.uuid_send()
- [ ] unimplemented.uuid_out()
- [ ] unimplemented.timestamptz_send()
- [ ] unimplemented.timestamptz_recv()
- [ ] unimplemented.timestamptz_out()
- [ ] unimplemented.timestamptz_in()
- [ ] unimplemented.timestamp_send()
- [ ] unimplemented.timestamp_recv()
- [ ] unimplemented.timestamp_out()
- [ ] unimplemented.timestamp_in()
- [ ] unimplemented.time_send()
- [ ] unimplemented.time_recv()
- [ ] unimplemented.time_out()
- [ ] unimplemented.time_in()
- [ ] unimplemented.textsend()
- [ ] unimplemented.textrecv()
- [ ] unimplemented.textin()
- [ ] unimplemented.syntax.set local
- [ ] unimplemented.syntax.set constraints
- [ ] unimplemented.syntax.interval with unit qualifier
- [ ] unimplemented.syntax.drop subscription
- [ ] unimplemented.syntax.drop rule
- [ ] unimplemented.syntax.drop publication
- [ ] unimplemented.syntax.drop operator
- [ ] unimplemented.syntax.drop foreign table
- [ ] unimplemented.syntax.drop extension if_p
- [ ] unimplemented.syntax.drop collation
- [ ] unimplemented.syntax.drop cast
- [ ] unimplemented.syntax.drop aggregate
- [ ] unimplemented.syntax.discard temp
- [ ] unimplemented.syntax.discard sequences
- [ ] unimplemented.syntax.discard plans
- [ ] unimplemented.syntax.create unlogged
- [ ] unimplemented.syntax.create table with oids
- [ ] unimplemented.syntax.create subscription
- [ ] unimplemented.syntax.create server
- [ ] unimplemented.syntax.create rule
- [ ] unimplemented.syntax.create publication
- [ ] unimplemented.syntax.create operator
- [ ] unimplemented.syntax.create foreign table
- [ ] unimplemented.syntax.create extension xmltable
- [ ] unimplemented.syntax.create extension xmlserialize
- [ ] unimplemented.syntax.create extension xmlpi
- [ ] unimplemented.syntax.create extension xmlparse
- [ ] unimplemented.syntax.create extension xmlattributes
- [ ] unimplemented.syntax.create extension time
- [ ] unimplemented.syntax.create extension temporary
- [ ] unimplemented.syntax.create extension substring
- [ ] unimplemented.syntax.create extension standalone_p
- [ ] unimplemented.syntax.create extension stable
- [ ] unimplemented.syntax.create extension show
- [ ] unimplemented.syntax.create extension sets
- [ ] unimplemented.syntax.create extension row
- [ ] unimplemented.syntax.create extension rollback
- [ ] unimplemented.syntax.create extension ref
- [ ] unimplemented.syntax.create extension pg_bigm
- [ ] unimplemented.syntax.create extension out_p
- [ ] unimplemented.syntax.create extension off
- [ ] unimplemented.syntax.create extension numeric
- [ ] unimplemented.syntax.create extension none
- [ ] unimplemented.syntax.create extension nchar
- [ ] unimplemented.syntax.create extension month_p
- [ ] unimplemented.syntax.create extension least
- [ ] unimplemented.syntax.create extension inout
- [ ] unimplemented.syntax.create extension if_p
- [ ] unimplemented.syntax.create extension ident
- [ ] unimplemented.syntax.create extension greatest
- [ ] unimplemented.syntax.create extension extract
- [ ] unimplemented.syntax.create extension exists
- [ ] unimplemented.syntax.create extension disable_p
- [ ] unimplemented.syntax.create extension continue_p
- [ ] unimplemented.syntax.create extension content_p
- [ ] unimplemented.syntax.create extension character
- [ ] unimplemented.syntax.create extension called
- [ ] unimplemented.syntax.create extension absolute_p
- [ ] unimplemented.syntax.create cast
- [ ] unimplemented.syntax.create aggregate
- [ ] unimplemented.syntax.alter table rename constraint
- [ ] unimplemented.set.row_security
- [ ] unimplemented.set.lock_timeout
- [ ] unimplemented.set.idle_in_transaction_session_timeout
- [ ] unimplemented.set.enable_sort
- [ ] unimplemented.set.enable_seqscan
- [ ] unimplemented.set.enable_bitmapscan
- [ ] unimplemented.set.default_tablespace
- [ ] unimplemented.set.check_function_bodies
- [ ] unimplemented.regtypesend()
- [ ] unimplemented.regtypeout()
- [ ] unimplemented.regprocsend()
- [ ] unimplemented.regproceduresend()
- [ ] unimplemented.regprocedurerecv()
- [ ] unimplemented.regprocedureout()
- [ ] unimplemented.regnamespacesend()
- [ ] unimplemented.regnamespaceout()
- [ ] unimplemented.regclasssend()
- [ ] unimplemented.regclassout()
- [ ] unimplemented.record_recv()
- [ ] unimplemented.record_out()
- [ ] unimplemented.record_in()
- [ ] unimplemented.pg_catalog.pg_prepared_xacts
- [ ] unimplemented.pg_catalog.pg_cursors
- [ ] unimplemented.pg_catalog.pg_cast
- [ ] unimplemented.oidvectorin()
- [ ] unimplemented.oidsend()
- [ ] unimplemented.oidrecv()
- [ ] unimplemented.oidout()
- [ ] unimplemented.numeric_send()
- [ ] unimplemented.numeric_recv()
- [ ] unimplemented.numeric_out()
- [ ] unimplemented.numeric_in()
- [ ] unimplemented.nested arrays
- [ ] unimplemented.namesend()
- [ ] unimplemented.namein()
- [ ] unimplemented.jsonb_send()
- [ ] unimplemented.jsonb_recv()
- [ ] unimplemented.jsonb_out()
- [ ] unimplemented.jsonb_in()
- [ ] unimplemented.interval_send()
- [ ] unimplemented.interval_recv()
- [ ] unimplemented.interval_out()
- [ ] unimplemented.interval_in()
- [ ] unimplemented.int8send()
- [ ] unimplemented.int8recv()
- [ ] unimplemented.int8out()
- [ ] unimplemented.int8in()
- [ ] unimplemented.int4recv()
- [ ] unimplemented.int4in()
- [ ] unimplemented.int2recv()
- [ ] unimplemented.int2in()
- [ ] unimplemented.information_schema.character_sets
- [ ] unimplemented.inetsend()
- [ ] unimplemented.inetrecv()
- [ ] unimplemented.inetout()
- [ ] unimplemented.inetin()
- [ ] unimplemented.import.format
- [ ] unimplemented.float8send()
- [ ] unimplemented.float8recv()
- [ ] unimplemented.float8out()
- [ ] unimplemented.float8in()
- [ ] unimplemented.date_send()
- [ ] unimplemented.date_recv()
- [ ] unimplemented.date_out()
- [ ] unimplemented.date_in()
- [ ] unimplemented.client_encoding utf8mb4
- [ ] unimplemented.client_encoding koi8
- [ ] unimplemented.client_encoding eucjp
- [ ] unimplemented.charin()
- [ ] unimplemented.bytearecv()
- [ ] unimplemented.byteaout()
- [ ] unimplemented.byteain()
- [ ] unimplemented.bpcharrecv()
- [ ] unimplemented.bpcharin()
- [ ] unimplemented.boolrecv()
- [ ] unimplemented.boolout()
- [ ] unimplemented.boolin()
- [ ] unimplemented.bit_send()
- [ ] unimplemented.bit_recv()
- [ ] unimplemented.bit_out()
- [ ] unimplemented.bit_in()
- [ ] unimplemented.anyelement_out()
- [ ] unimplemented.anyarray_recv()
- [ ] unimplemented.anyarray_in()
- [ ] unimplemented.alter column type

**Comment by jordanlewis** [comment]
@awoods187 what's the action item here? I don't understand

**Comment by knz** [comment]
@jordanlewis there are multiple action items here:

1. for some of these that do have an issue already, find out why the issue is not linked (e.g. "with recursive" and "alter column type" - we have issues for those)
2. for some of the others, create issues and add links to them (in particular all the syntax errors that are not `create extension` seem interesting)
3. gather the frequency of (attempted) use for the unsupported built-in functions, to find what needs to be worked on
4. gather the list of extensions used with `create extension` and their frequency, and push this to PMs for more analysis of what users are likely to want to add to crdb

Items 1-3 are engineering, item 4 is for Andy himself.

**Comment by awoods187** [comment]
Closing this as out of date
