### ISSUE TITLE
storage: Subsume request can fail to latch entire Range

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#36678]
A `Subsume` request relies on the fact that it [latches](https://github.com/cockroachdb/cockroach/blob/aaf3143f1ae07e007c63e87fc2c15502bca6a2e8/pkg/storage/batcheval/cmd_subsume.go#L37) its entire Range before evaluating. However, it uses the provided RangeDescriptor during span declaration to determine which key range to latch. As noted in the following TODO, this RangeDescriptor can change between span declaration and command evaluation: https://github.com/cockroachdb/cockroach/blob/aaf3143f1ae07e007c63e87fc2c15502bca6a2e8/pkg/storage/batcheval/command.go#L30-L31

`Subsume` request should be fixed to correctly latch its entire Range. This could be accomplished in one of two ways:
1. declare latches over the range [key-min, key-max) and [local-key-min, local-key-max). Even though these keys extend past the end of the range, this is fine (`EndTransaction` does the [same thing](https://github.com/cockroachdb/cockroach/blob/master/pkg/storage/batcheval/cmd_end_transaction.go#L58)).
2. provide an expected descriptor on Subsume request which we use when declaring keys and then compare to the real descriptor during evaluation (splits do the [same thing](https://github.com/cockroachdb/cockroach/blob/aaf3143f1ae07e007c63e87fc2c15502bca6a2e8/pkg/storage/batcheval/cmd_end_transaction.go#L771)).

@bdarnell has voiced support for the second option.

**Comment by bdarnell** [comment]
EndTransaction gets *some* latches outside its range, but it doesn't latch everything from keymin to keymax. I think that would be a performance problem since subsuming any range would stall everything else.

I don't agree with the comment that what EndTransaction is doing is OK - it's not too bad since it only affects spans where we have intents (and those intents would prevent most but not all other operations from usefully running), but it's still unnecessary contention. We should try to clip our spans into the appropriate range.

**Comment by nvanbenschoten** [comment]
> EndTransaction gets some latches outside its range, but it doesn't latch everything from keymin to keymax. I think that would be a performance problem since subsuming any range would stall everything else.

The `spanlatch.Manager` is a per-Range structure, though, so these latches should be harmless.

I'm actually not sure whether this could actually lead to any issues. The hazard is that the RHS of a merge is in the middle of its own merge which completes between the times that a `Subsume` request declares its keys and evaluates. I think this may be impossible because intents are written on the LHS and RHS descriptor of a merge before the merge can send a `Subsume` request or commit. These intents alone may be preventing the race.

**Comment by bdarnell** [comment]
> The spanlatch.Manager is a per-Range structure, though, so these latches should be harmless.

Ah, I had it mixed up with the tscache.  We might still want to move spanlatch.Manager to something global, though, to reduce allocations, so it would be nice to ensure that we only declare things that are in-bounds.

**Comment by nvanbenschoten** [comment]
> We might still want to move spanlatch.Manager to something global, though, to reduce allocations, so it would be nice to ensure that we only declare things that are in-bounds.

Doing so is complicated because of the race mentioned by the TODO.
