### ISSUE TITLE
storage: some confusion about newNotLeaseHolderError

### ISSUE THREAD

**Issue by YuleiXiao** [cockroachdb/cockroach#3670]
Why call ```FindReplica``` to get the leader, but not use ```l.Replica```? They are different?

```
func (r *Replica) newNotLeaderError(l *roachpb.Lease, originStoreID roachpb.StoreID) error {
	err := &roachpb.NotLeaderError{}
	if l != nil && l.Replica.ReplicaID != 0 {
		desc := r.Desc()

		err.RangeID = desc.RangeID
		_, err.Replica = desc.FindReplica(originStoreID)
		_, err.Leader = desc.FindReplica(l.Replica.StoreID)
	}
	return
```

**Comment by tschottdorf** [comment]
They should mostly be the same but the information from `desc` could be newer. I have a hard time coming up with an example where that would matter, though. You could trace the commit history and see whether this was consciously changed at some point, in which case you might find more information in the respective commit.

**Comment by bdarnell** [comment]
Yeah, I think this should just be `err.Leader = l.Replica`. This is probably just leftover from the refactoring that introduced the `ReplicaDescriptor` message.
