### ISSUE TITLE
storage: best-effort tooling to inspect inconsistent ranges

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#36713]
Replica consistency check failures should not occur in customer deployments (or ever); they are one of the most severe types of bugs in the wild in the sense that they can invalidate any assumptions made on the constraints for data stored within the cluster. For example, a consistency check may find that several kv pairs corresponding to the primary index of a table have gone missing on some replicas while they are still referenced from other tables.

Our general guidance towards resolving these situations is to restore from a backup. The reason for this is that it is generally impossible to decide which replica is "right" about the data -- they may all have diverged from what should be the correct state. Or, the inconsistency could affect internal data structures like the meta ranges, in which case a manual repair would be very difficult as wrong information might have leaked all over the place.

The general guidance should remain to restore from a backup. However, we may find inconsistencies in situations in which the user has not followed best practices and no backup is available, or in which there is a desire to try to capture another backup capturing the latest (perhaps inconsistent) data from which to manually capture the changes not included in the most recent consistent backup. (Note that even with incremental backups, it is not an easy task to decide which incremental backup first picked up the inconsistencies before they were detected). Then, on the other hand, we've seen inconsistencies that seem "benign" - a missing sample in a timeseries range, perhaps.

We should eventually provide basic tooling that allows a better understanding of these diffs, which in particular means pretty-printing the data contained in the inconsistent rows (for example, if a PK is inconsistent, manually checking what the secondary indexes or other constraints have to say about the row). We currently pretty-print the key but not the value since the consistency checker runs on the Replica level and does not have the information to decode the SQL values at hand. The diff could be printed in `crdb_internal.check_consistency` which already contains the "raw diff" today. I suspect that to print a good value for a SQL row it needs to know something about the schema, so the UX here will need some figuring out.

Here's an example of what they look like at the time of writing:

https://github.com/cockroachdb/cockroach/issues/35424#issuecomment-469717555

The standard procedure is to feed the hex key and value into `./cockroach debug  decode-value`, which gives a decent pretty printed version for all internally used value types. It doesn't work for SQL rows, so perhaps that's something to add there.

Note that many inconsistencies revolve around the internal MVCCStats field or transaction entries and never touch any user kv pairs, but it has happened.

If the divergence is found to not affect any SQL data (and no critical internal data such as, for example, meta ranges) then often a consistent backup can be made and restored into a new cluster. However, if SQL data is affected, creating a "correct" backup may require manually designating a "winner replica" among the inconsistent ones to avoid having to perform manual surgery on the created backup. Designating the winner replica should be straightforward using RelocateRange, which is already exposed for tables (though not individual ranges, which is necessary here). RelocateRange can force the range down to a single desired designated replica, thus making sure the backup will pick up the right data.

Under no circumstances is the suggestion to keep using the cluster after an inconsistency occurred.

**Comment by tbg** [comment]
@andy-kimball I wrote this up as a reaction to yesterday's meeting to give you an idea of how things work today and how we might extend it. I'm curious what other reqiurements @awoods187 will identify.

For what's written above, this would make a decent intern project.

**Comment by andreimatei** [comment]
> Under no circumstances is the suggestion to keep using the cluster after an inconsistency occurred.

This sounds too harsh to me. After throwing away replicas using `RelocateRange`, it seems to me that the cluster would probably be as good as any. If we're talking about customer requirements, the requirement in question was "no downtime" - so definitely not creating a backup, throwing away the cluster and starting a new cluster and restoring.

**Comment by tbg** [comment]
Related: https://github.com/cockroachdb/cockroach/issues/17186
