### ISSUE TITLE
docs: Add anchors to each setting's name in `settings.html` for direct linking

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/cockroach#36733]
In the docs, we'd like to be able to link to specific settings, as discussed during the review on https://github.com/cockroachdb/docs/pull/4635

It can be done by manually adding anchors to the settings file copy in the docs repo.  However, that file is auto-generated in this repo and then copied over periodically, so making edits via the docs repo would lead to conflicts that would need to be manually tracked and resolved.

Therefore this feature request is to add anchor tags to each setting in `docs/generated/settings/settings.html` so they can be linked to directly in the documentation.  A solution (verified to work in the PR linked above) would be to add an anchor with the same name as the setting, e.g.

```html
<tr><td><a name="sql.stats.automatic_collection.min_stale_rows"></a><code>sql.stats.automatic_collection.min_stale_rows</code></td><td>integer</td><td><code>500</code></td><td>target minimum number of stale rows per table that will trigger a statistics refresh</td></tr>
```

**Comment by arberiii** [comment]
How is `settings.html` file generated?

I found this line (https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/docgen/funcs.go#L218) which may be used to generate it but was not sure.

**Comment by rmloveland** [comment]
That looks like the place!

I think adding an anchor link somewhere in the `tr` might do it, e.g., something like the following (untested) code:

~~~ go
s := fmt.Sprintf("<tr><td><a name="%s"></a><code>%s(%s) &rarr; %s</code></td><td>%s</td></tr>", name, name, linkArguments(args), linkArguments(ret), extra)
~~~
