### ISSUE TITLE
workload: Rate-limit connection warmup

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#36745]
https://github.com/cockroachdb/cockroach/blob/bf399d2677783dc1eea7f5ede6d4561f95c0ea10/pkg/workload/pgx_helpers.go#L87-L104

`workload` eagerly initializes all the connections in its pools, and it does so by spawning new goroutines to initialize all connections in parallel. For large numbers of connections, this is enough to A) trigger SYN cookies DoS protection on the cockroach node and B) sometimes cause the connection to fail with a "connection reset by peer" message (even though the server is up throughout this process. I think this is a consequence of SYN cookies, but I'm not 100% sure). An error at this stage kills the workload regardless of the `tolerate-errors` flag.

We should add some sort of rate-limiting here so we don't overload the server. We may also want to be more tolerant of errors at this stage (at least if the `tolerate-errors` flag is set. We should also verify the number of connections required for optimal performance in TPCC. We currently use 2 connections per warehouse which seems really high to me. 

This issue manifests as a test failure like

```
		stdout:
		Error: read tcp 10.142.0.43:37862->10.142.0.112:26257: read: connection reset by peer
		Error:  exit status 1
```

early in a test run (no other output). It appears to be common in roachtests using tpcc-1000, including #35985, #35986, and #36094.

**Comment by bdarnell** [comment]
> We currently use 2 connections per warehouse which seems really high to me.

There are 10 workers per warehouse. Each worker spends a significant amount of time idle: depending on the type of transaction there is a required "keying time" and "thinking time", as well as a target maximum duration for the transaction (measured at p90). For the new-order transaction, there is a mean of 30 seconds of idleness per transaction. If the transaction took the entire 5s allowance, it would be only be in use (and need a connection) 14% of the time. Payment transactions have less keying time; they're only idle for 15s per transaction (and other transactions are even less, but they're a smaller part of the mix so we'll focus on new_order and payment). 

So if our transactions are using up to the 5s response time constraint, 2 connections per warehouse seems about right. But they're not: we show p99 latencies of 185ms and 637ms [for different configurations](https://www.cockroachlabs.com/docs/stable/performance-benchmarking-with-tpc-c.html#benchmark-a-small-cluster), and the means are closer to 100ms. Even if we allow for transactions taking 500ms, a worker processing payment transactions is only busy 3% of the time. So I think we only need 0.03 connections per warehouse, not 2.

**Comment by RaduBerinde** [comment]
I recently added a `--conns` flag so it should be easy to experiment with the max # of connections. In some experiments I ran, I saw very similar results even reducing the number of max connections by about 4x (but I wasn't confident enough to reduce the default).

We could add a semaphore to those warmup goroutines.

**Comment by bdarnell** [comment]
And what should the rate limit be? I think this is tied to `/proc/sys/net/core/somaxconn` which is normally 128, so we should not have more than 128 connection attempts outstanding (to a single host).

**Comment by RaduBerinde** [comment]
I'd probably start with something like 64 (one semaphore per `url`) to be safe. We could experiment on a cluster and see the difference in the setup time (there are now messages printed before and after the connection part). But making that as fast as possible isn't critical.

We should also consider increasing `somaxconn` on our machines (thinking especially of MSO).

**Comment by RaduBerinde** [comment]
Let me know if you want me to work on this.
