### ISSUE TITLE
IMPORT: fatal disk stall during CSV import

### ISSUE THREAD

**Issue by roncrdb** [cockroachdb/cockroach#36757]
**Describe the problem**

Importing CSV files that were about 100 GB in size, nodes on users cluster experienced a fatal error: 

```
F190410 12:47:46.929409 59667 util/log/clog.go:1275  disk stall detected: unable to sync log files within 30s
goroutine 59667 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0xc000502800, 0xc0005028a0, 0x53c4200, 0x10)
    /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:1020 +0xd4
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x5b41fc0, 0xc000000004, 0x53c427e, 0x10, 0x4fb, 0xc008624dc0, 0x38)
    /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:876 +0x95a
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x3a31a20, 0xc000056050, 0xc000000004, 0x2, 0x0, 0x0, 0xc00940cfb0, 0x1, 0x1)
    /go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:85 +0x2d8
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x3a31a20, 0xc000056050, 0x1, 0x4, 0x0, 0x0, 0xc0031c17b0, 0x1, 0x1)
    /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:71 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Shout(0x3a31a20, 0xc000056050, 0x4, 0xc0031c17b0, 0x1, 0x1)
    /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:89 +0xa5
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).flushAndSync.func1()
    /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:1275 +0x122
created by time.goFunc
    /usr/local/go/src/time/sleep.go:172 +0x44


****************************************************************************
```

**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. Set up CockroachDB cluster ...
2. Send SQL ... / CLI command ...
3. Look at UI / log file / client app ...

**Expected behavior**
Imports should be able to finish without nodes crashing. 

**Additional data / screenshots**
The user was advised to set the env var `COCKROACH_ENGINE_MAX_SYNC_DURATION=<TIME>` to `24h` as well as `set cluster setting kv.bulk_io_write.max_rate = <x>` which was set to `12MB` in this case. At the moment we do not have a default value for `kv.bulk_io_write.max_rate `, but perhaps one should be implemented. 

**Environment:**
 - CockroachDB v19.1rc2

**Comment by ajkr** [comment]
One of the roachtests also hit disk stalls during import and we investigated it in https://github.com/cockroachdb/cockroach/issues/34897. Long story short, we tried everything imaginable and eventually came up with a PR that was confirmed to prevent disk stalls in that test case: https://github.com/cockroachdb/rocksdb/pull/29. Perhaps it can help here too.

**Comment by irfansharif** [comment]
Closing this out due to inactivity (and I think the linked issues above provide better mitigations for inducing disk stalls). We can re-file if this pops up again.
