### ISSUE TITLE
release:v19.1.0-rc.3

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#36750]
Candidate SHA: `0c83360778c511ab79103aefd8f5e3a115990144` 0c83360778c511ab79103aefd8f5e3a115990144

Deployment status: deployed to roachprod. http://radu-release-v1910-rc3-0001.roachprod.crdb.io:26258/ vs previous http://radu-release-v1910-rc2-0001.roachprod.crdb.io:26258/

Release qualification suite: https://teamcity.cockroachdb.com/viewLog.html?buildId=1237097&buildTypeId=Cockroach_ReleaseQualification

Nightly Suite: https://teamcity.cockroachdb.com/viewLog.html?buildId=1237008&buildTypeId=Cockroach_Nightlies_NightlySuite
https://teamcity.cockroachdb.com/viewLog.html?buildId=1237074&buildTypeId=Cockroach_Nightlies_NightlySuite
 
[Release process checklist](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process)
 
Prep date: `4/11/2019`
- [x] [Pick a SHA](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-PickingaSHA), fill in `Candidate SHA` above, notify #release-process of SHA.
- [x] [Tag the provisional SHA](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-TagtheprovisionalSHA)
- [x] [Publish provisional binaries](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Publishtheprovisionalbinaries)
- [x] [Check binaries](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Checkbinaries)
- [x] [Deploy to test clusters](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-DeploytoTestClusters)
- [x] [Start release qualification suite](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-RuntheSuiteofNightlyRoachtests)
- [x] [Start nightly suite](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-RuntheSuiteofNightlyRoachtests)
- [ ] [Verify node crash reports](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Verifynodecrashreportsappearinsentry.io)
- [x] fill in `Deployment status` above with clusters and `Nightly Suite` with the link to Nightly TeamCity Job
 
- Keep an eye on clusters until release date. Do not proceed below until the release date.
 
Release date: `4/15/2019`
- [x] [Check cluster status](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Checkclusterstatus)
- [x] [Tag release](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Tagtherelease)
- [x] [Bless provisional binaries](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Blesstheprovisionalbinaries)
 
- ~~For production or stable releases in the latest major release series~~
  - [ ] ~~Update the [Homebrew Formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/cockroach.rb)~~
  - [ ] ~~Update the image tag in our [Orchestrator configurations](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Orchestratorconfigurations)~~
  - [ ] ~~Announce version to the [registration cluster](https://github.com/cockroachlabs/production#publishing-a-new-release-version)~~
  - [ ] ~~Upgrade the registration cluster (reg runs latest stable version)~~
 
- [x] Update docs
- [x] External communications for release

**Comment by RaduBerinde** [comment]
Nightly failures are existing issues #36697, #36822, #33501, #34702.

**Comment by nvanbenschoten** [comment]
We can ignore #36697. I just disabled it. See https://github.com/cockroachdb/cockroach/issues/36697#issuecomment-482806190.
