### ISSUE TITLE
cli/dump: `cockroach dump` produces unrestorable output with large records

### ISSUE THREAD

**Issue by rolandcrosby** [cockroachdb/cockroach#36762]
As described in the comments on #25524, `cockroach dump` can produce `INSERT` statements that are too long to be parsed either by CockroachDB's native SQL parser (when executing the statements in a dump file directly) or the parser used by `IMPORT PGDUMP`. `cockroach dump` should be updated to track the length of the statements it generates, ensuring that they can be parsed properly.

**Comment by mjibson** [comment]
`max_row_size` from https://www.cockroachlabs.com/docs/v2.1/import.html#import-options can be used to handle longer lines.

**Comment by miretskiy** [comment]
duplicate of #31676
