### ISSUE TITLE
prod: provide init scripts

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#3680]
One of the standard ways of running cockroach will be through init scripts.

We need to consider a few things:
- which type to support? systemd vs upstart vs ???
- how to do config? we may need to introduce a config file. Something that maps directly to cmdline flags would be nice.

**Comment by mberhault** [comment]
as far as I can tell, [https://github.com/spf13/viper](https://github.com/spf13/viper) can be used to populate `spf13/cobra` flags from a config file. This may be a good solution.

**Comment by alanhamlett** [comment]
👍

**Comment by knz** [comment]
This came up on the forum recently: https://forum.cockroachlabs.com/t/configuration-files-with-cockroachdb/506/4

**Comment by tschottdorf** [comment]
@petermattis which team owns this? Presumably due to the catchall nature of CF&S that's where it has ended up right now, but I'm unlikely to ever do anything about it.

**Comment by mberhault** [comment]
Systemd has been documented: https://www.cockroachlabs.com/docs/v2.0/deploy-cockroachdb-on-premises-insecure.html#systemd
Closing.
