### ISSUE TITLE
sql: Return PG-compatible OID values to clients

### ISSUE THREAD

**Issue by andy-kimball** [cockroachdb/cockroach#36811]
Once CRDB's type systems are unified (https://github.com/cockroachdb/cockroach/pull/36598), we will be in a position to return result column OID values that are more PG compatible than before. For example:
```
CREATE TABLE t (a INT2);
SELECT a FROM t;
```
Currently, this will return an OID of `T_int8` rather than `T_int2`. CRDB's type system did not sufficiently differentiate between the two before. But after type system unification, it's possible to return `T_int2`.

However, there is still more work to do before returning `T_int2`. The unified type system PR added a `mapResultOid` method to preserve backwards-compatibility with current behavior, since one goal of that PR was to avoid making non-trivial changes to typing behavior. Once we start returning "correct" OID's, it will cause various issues that we'll need to find and fix. There are three that I know of so far:

#1: libpq does not properly handle `T_float4`. It always returns it as a float64 value with garbage bits in the final 32 bits (because it uses strconv.ParseFloat with bitSize=32). Furthermore, there's no way for callers (like the CLI) to know whether this has happened in order to compensate, since libpq doesn't expose this information. This results in output like this for the value 1.2 (if the datatype of column "a" is float4 and extra digits = 2):
```
           a
+--------------------+
    1.2000000476837158
```
Note that before 19.2, mapping T_float4 to T_float8 was always occurring anyway, because earlier versions did not preserve OIDs in result types (with a couple exceptions, like Name and RegClass).

#2: `DataConversion.GetFloatPrec` needs to be extended to handle FLOAT4 values, something like this:
```
// GetFloatPrec computes a precision suitable for a call to
// strconv.FormatFloat() or for use with '%.*g' in a printf-like function. The
// bitSize argument can be either 32 (float4) or 64 (float8).
func (c *DataConversionConfig) GetFloatPrec(bitSize int) int {
	// The user-settable parameter ExtraFloatDigits indicates the number
	// of digits to be used to format the float value. PostgreSQL
	// combines this with %g.
	// The formula is <type>_DIG + extra_float_digits,
	// where <type> is either FLT (float4) or DBL (float8).

	// Also the value "3" in PostgreSQL is special and meant to mean
	// "all the precision needed to reproduce the float exactly". The Go
	// formatter uses the special value -1 for this and activates a
	// separate path in the formatter. We compare >= 3 here
	// just in case the value is not gated properly in the implementation
	// of SET.
	if c.ExtraFloatDigits >= 3 {
		return -1
	}

	// Go does not expose DBL_DIG or FLT_DIG, so we use the standard literal
	// constants for 32 and 64 bit floats.
	const StdFloatDigits = 6
	const StdDoubleDigits = 15

	var nDigits int
	if bitSize == 32 {
		nDigits = StdFloatDigits
	} else {
		nDigits = StdDoubleDigits
	}
	nDigits += c.ExtraFloatDigits
	if nDigits < 1 {
		// Ensure the value is clamped at 1: printf %g does not allow
		// values lower than 1. PostgreSQL does this too.
		nDigits = 1
	}
	return nDigits
}
```

#3: The `testArrayWithProps` Java acceptance test breaks when we return the correct OID. That will need to be updated to use `Integer[]` instead of `Long[]`.

There are undoubtedly other problems that returning correct OID types will uncover. We'll need to run all the external tests, like Hibernate, Flowable, etc. to uncover what we can.

**Comment by knz** [comment]
@mjibson this is the issue that interests you the most I think, since it's the one needed to "do the right thing" in pgwire. However as Andy found we need to 

1) fix libpq for Go clients that want to use CockroachDB

2) fix the java acceptance test

(Note that on point 1 I did not write "change the `cockroach` client to use another driver than `libpq`". Unfortunately even if we did so we still need to fix libpq for _other_ Go apps that may use it.)
