### ISSUE TITLE
sql: introduce a SHOW statement to query the event log

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#36814]
I would like to use `show` to see events/cluster setting history.

We can see events in the webui but would like to see it in the cli (and in the webui it masks what the events were set to).

**Workarounds**
You can scan `system.eventlog`.

**Comment by knz** [comment]
@jordanlewis this issue was mis-filed initially. It's really a SQL feature request. Can you check?

**Comment by knz** [comment]
we're deprecating the eventlog
