### ISSUE TITLE
acceptance: odd acceptance test failures

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#3682]
https://circleci.com/gh/cockroachdb/cockroach/10760

The above test failure is not clear about what failed and why. Debugging in chat we found:

```
case <-stopper:
        // The stopper was already closed, exit early.
        os.Exit(1)
```
line 438 in localcluster.go closes the stopper
then the previous snippet calls os.Exit

To fix this we probably need to not call os.Exit but instead t.Fatal.

**Comment by petermattis** [comment]
@mjibson Is this still happening?

**Comment by mjibson** [comment]
Nope, I think it got fixed.
