### ISSUE TITLE
goroutinedumper: Compress files

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#36846]
Goroutine dumps are large, but compress well. With default settings, the goroutine dumper will fire when there are 1000 goroutines, which produces a file of about 9MB that gzips down to 500KB. We should compress the files we write here (and probably reduce the `total_dump_size_limit` - spending half a gig on this is kind of silly when we only budget 100MB for logs in `util/log`). 

I'm noticing this because #35986 produces 400MB of goroutine dumps per run (twice the size of its log files), so stressing it keeps filling up my local disk.

**Comment by tbg** [comment]
@giorgosp -- if you're interested in knocking out another issue, this one would be a good follow-up to #36813. Basically in this code

https://github.com/cockroachdb/cockroach/blob/4dcde30772c3a75d632b3f50cbcc6259d79426d6/pkg/server/goroutinedumper/goroutinedumper.go#L177-L188

we wouldn't pass `f` to `WriteTo`, but we'd wrap `f` it in a [gzip.NewWriter](https://golang.org/pkg/compress/gzip/#NewWriter), and perform the necessary cosmetics (i.e. chose a filename ending in `.txt.gz`, adapt `debug zip` to use a `.txt.gz` ending as well). I think the `GetFiles` endpoint would just return the compressed files, which is what we want.
