### ISSUE TITLE
exec: wrap all non-supported specs with columnarizer/materializer

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#36869]
Currently, we wrap index and lookup join with columnarizers so that we can run those plans in the vectorized engine.

We should use this same strategy for all unsupported specs so that we can run all of the logic tests and so on, even though there are still things that aren't supported. This way, we'll be able to run all queries through the vectorized engine, which will help us find bugs as we'll be able to run the full test suite on the new engine.

**Comment by asubiotto** [comment]
This happens now with `vectorize=on`.
