### ISSUE TITLE
pkg/server failure

### ISSUE THREAD

**Issue by salamani** [cockroachdb/cockroach#36866]
Testcase failure

Build cocrroachdb of version v2.1.6 and run following command for test:

make test PKG=./pkg/server failed

Log is as follow
[make_test_cmd.log](https://github.com/cockroachdb/cockroach/files/3084351/make_test_cmd.log)

 any suggestion on this?

**Comment by jordanlewis** [comment]
You shouldn't need to run unit tests to use CockroachDB, but if you want to get to the bottom of it, try using `TESTFLAGS=-v` for more information. As an aside, every commit passes the full suite of unit tests on our CI servers before it is allowed to be merged. Going to close this, but feel free to keep posting to it if you're curious.

**Comment by salamani** [comment]
I am working on s390x by building it from source. Any input on this will be very useful.
`github.com/cockroachdb/cockroach/pkg/server` is failing 
Log using `TESTFLAGS=-v` is as follow:

[make_test_server_cmd.log](https://github.com/cockroachdb/cockroach/files/3089228/make_test_server_cmd.log)

**Comment by jordanlewis** [comment]
The test that's failing according to that log is this:
```
--- FAIL: TestReportUsage (46.40s)
    updates_test.go:401: condition failed to evaluate within 45s: expected non-zero sockets
        goroutine 48240 [running]:
        runtime/debug.Stack(0xa7a358200, 0xc0011a5b60, 0x34c5060)
        	/usr/local/go/src/runtime/debug/stack.go:24 +0xae
        github.com/cockroachdb/cockroach/pkg/testutils.SucceedsSoon(0x3511700, 0xc001568200, 0xc003468d70)
        	/home/test/src/github.com/cockroachdb/cockroach/pkg/testutils/soon.go:50 +0x11a
        github.com/cockroachdb/cockroach/pkg/server.TestReportUsage(0xc001568200)
        	/home/test/src/github.com/cockroachdb/cockroach/pkg/server/updates_test.go:401 +0x1cc2
        testing.tRunner(0xc001568200, 0x302e1e8)
        	/usr/local/go/src/testing/testing.go:827 +0xcc
        created by testing.(*T).Run
        	/usr/local/go/src/testing/testing.go:878 +0x37a
```

I'm not sure what that means, are you running on an unusual system?

If you're just building from source, `make build` will suffice.

**Comment by salamani** [comment]
**Environment:**
 - CockroachDB version [v2.1.6]
 - Server OS: [Linux]
 - Architecture: s390x
 - go version: v1.11.4
