### ISSUE TITLE
kv: client should look for deadline exceeded error not waiting until commit time

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#36871]
This is to prevent sending back to the user data from a transaction that will eventually restart.

In #18684 @andreimatei writes:

Yes. The question, of course, is who should create the errors, since "pushing" is a bit of a conflated term. For one, I think server-side code should probably stay unchanged, and all the handling of deadline-related issues should be relegated to the client.
For refreshes, I think `CanTransactionRetryAtRefreshedTimestamp` should probably return `false` here:
https://github.com/cockroachdb/cockroach/blob/36eb40c7a5d6c10f72c694c56612d4aa3ae78099/pkg/kv/txn_interceptor_span_refresher.go#L197

Then, I think `IsSerializablePushAndRefreshNotPossible()` should also become aware of the deadline.
https://github.com/cockroachdb/cockroach/blob/e4a2a4c29c4b0ed164c08684545aeb26a5e8759b/pkg/kv/txn_coord_sender.go#L1062

Then I think code around here should also always detect txns pushed above the deadline and return an error eagerly, although, as with all eager versus deferred error discussions, this is a judgement call.
https://github.com/cockroachdb/cockroach/blob/36eb40c7a5d6c10f72c694c56612d4aa3ae78099/pkg/kv/txn_interceptor_span_refresher.go#L151

**Comment by andreimatei** [comment]
The link for context: https://github.com/cockroachdb/cockroach/issues/18684#issuecomment-434729550

**Comment by andreimatei** [comment]
> This is to prevent sending back to the user data from a transaction that will eventually restart.

I think there's two separate things here:
1. A txn should not be allowed to operate outside its deadline because I think it could return garbage data (since it's operating outside its leases).
2. For minimizing `TransactionDeadlineExceeded` errors, I think we should have a mechanism for extending a txn's deadline when its leases are refreshed.

**Comment by rmloveland** [comment]
@pbardea since you filed #45278 I have a question:

you said that

> This may cause retry errors to appear on transactions which do not experience contention.

I am working on a retry error reference page for the docs.  I think I can cobble together a description of what is happening from your issue comment.  However, my question is:

What action(s) should a user / client application that encounters this situation take to deal with these restarts?  Is there anything they can do?

**Comment by rmloveland** [comment]
@lucy-zhang and/or @ajwerner:

I'm working on a retry error reference page for the docs (see cockroachdb/docs#5476) and have a couple of questions:

1. Paul said in #45278 that contention was not necessarily the issue causing the `RETRY_COMMIT_DEADLINE_EXCEEDED` error.  It sounds like long-running transactions in general might hit the error, whether they experience contention or not.  Is that correct?  If so, is there a user-facing-ish explanation we can offer beyond something along the lines of "they timed out"?

2. What action(s) should a user / client application that encounters this situation take to deal with these errors? Is there anything they can do beyond the standard "just retry" advice?

**Comment by pbardea** [comment]
My understanding of this is that when a transaction uses a table, its deadlines is set based on the the expiration of that node's lease on the table. The transaction will fail if it gets pushed beyond its deadline. The transaction may be pushed by contention, or by the closed timestamp mechanism. That's what I was referring to in my comment. I would defer to KV folks for more detail here.

In the absence of contention, I would naively assume that the user could try to increase the closed timestamp interval - but I would check in with someone more familiar. (Most of my understanding here has been from chats with @ajwerner and @irfansharif who certainly know more than I.)

**Comment by andreimatei** [comment]
It seems to me that a (non-readonly) txn running for longer than the descriptor lease time (5m) will continuously restart. At the very least, attempting to write the txn record at the end will run into the closed timestamp and be pushed above the deadline. The deadline is currently immutable, and so there's no refreshing this txn.

Which all sounds really bad. Is there a saving grace that I'm missing?
@ajwerner do you mind if I tag you for some thoughts? I think we really need to start extending this deadline with lease extensions.

**Comment by ajwerner** [comment]
I do not think there is a saving grace here except to say that if you run longer than 5m but you don't get pushed you'll be okay. With the closed timestamp that no longer seems likely.

>  I think we really need to start extending this deadline with lease extensions.

Yes, this. The KV client should take a closure or object that gives it an expiration when it goes to issue `EndTransaction`. There is no reason to early-bind the deadline the way we do today. It's crazy! All that being said, that object needs to be more careful about its leases. FWIW I think that this late-bound deadline facility will be extremely useful for other lease-backed abstractions we build in the future, likely on top of https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20200615_sql_liveness.md.

**Comment by ajwerner** [comment]
I've created https://github.com/cockroachdb/cockroach/issues/51042 to track the required work to obviate this issue.

**Comment by andreimatei** [comment]
> It seems to me that a txn running for longer than the descriptor lease time (5m) will continuously restart. At the very least, attempting to write the txn record at the end will run into the closed timestamp and be pushed above the deadline. 

I think I was wrong about the last part here - about "writing the txn record". The `EndTxn` does interact with the timestamp cache; it can operate below the closed timestamp.

**Comment by ajwerner** [comment]
I'm closing this now that we late-bound deadlines, this issue does not make sense.
