### ISSUE TITLE
changefeedccl: cdc/crdb-chaos sometimes takes a while to recover from chaos

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#36879]
I've seen the latency make it up to 10-20m before, but it really shouldn't ever go higher than 1-2m. Definitely something to look into here, easy enough to repro by extending the duration of the test.

Jira issue: CRDB-4477

**Comment by danhhz** [comment]
Okay, well first of all, something is bonkers about the test. The resolved timestamp it's looking at should never regress, so a 42m jump in 2s means something is broken.
```
changefeed: 21:13:54 cdc.go:833: end-to-end steady latency 1m42.086645442s; max steady latency so far 18m58.209893436s
changefeed: 21:13:56 cdc.go:833: end-to-end steady latency 43m54.855883321s; max steady latency so far 43m54.855883321s
```

**Comment by danhhz** [comment]
Started back into this and got a high-water checkpoint that's behind what the feed was restarted with. Still digging into why, but perhaps we want to make sure we `.Forward` the old progress as a safety net. It's still odd that this ever happened though.

```
I190422 19:02:23.407085 3713 ccl/changefeedccl/changefeed_dist.go:92  [n1] WIP starting changefeed from 1555959671.535291852,0 is behind by 1m11.871743607s
I190422 19:02:49.985172 3713 ccl/changefeedccl/changefeed.go:323  [n1] WIP wrote high-water checkpoint 1555959404.146301576,0 is behind by 6m5.83883919s
```

**Comment by danhhz** [comment]
A little overwhelmed with all the threads to pull on here, so just going to write them in here for now and follow up later. Just got an unexpectedly failed changefeed, with no useful stacktrace from the errors stuff. I _suspect_ this happened while trying to compute the spans to track (the `fetchSpansForTargets` call in `distChangefeedFlow`. `fetchSpansForTargets` uses db.Txn, so it should have retried anything retryable. This entire cluster is pretty new, so I'd hope the descriptor it's looking for has not been GC'd yet.

```
I190422 19:04:45.882727 5450 ccl/changefeedccl/changefeed_dist.go:92  [n1] WIP starting changefeed from 1555959404.146301576,0 is behind by 8m1.736391533s
W190422 19:04:45.883095 5450 ccl/changefeedccl/changefeed_stmt.go:459  [n1] CHANGEFEED job 445281624778735617 returning with error: descriptor not found
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.init
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/structured.go:179
```

**Comment by danhhz** [comment]
Progress! Figured out that RangeFeed will return checkpoints from before the timestamp you started it at because it just happily forwards closed timestamps as long as there are no outstanding intents before them. When combined with job restarts, this could cause the changefeed high-water to regress (since we don't initialize the spans in the `spanFrontier` at any particular timestamp). This is likely one cause of the very high end-to-end latencies in the roachtest. It remains to be seen if it's the only cause.

I currently have a local fix for changefeeds to throw out any rangefeed checkpoints from before the timestamp we started the rangefeed with. I also think it'd be appropriate to add a high-level assertion that the high-water never regresses (perhaps a Fatal in tests, Sentry in prod kind of thing).

@nvanbenschoten I can't really see a reason why a rangefeed would ever need to return checkpoints from below the timestamp specified in its request. What do you think about filtering these inside the rangefeed registration?

**Comment by nvanbenschoten** [comment]
Yeah, we very explicitly allow this situation:
https://github.com/cockroachdb/cockroach/blob/b46cf9eafa0dff487d5df7e8147f80cce215292d/pkg/storage/rangefeed/registry.go#L368-L369

I don't remember why though. I think I wrote it that way because it seemed like more information about resolved timestamps is always better than less. If that violates the rangefeed contract that consumers are expecting, I don't see a reason why we shouldn't change it.

The one case where this might come up is immediately after a rangefeed's catch-up scan. If we filter checkpoints with timestamps below the rangefeed's start timestamp, a rangefeed may be unable to signal that it has completed its catch-up scan. Is that ok?

**Comment by danhhz** [comment]
It's easy to argue that changefeeds should be doing this filtering (and like I mentioned above, that's where I have my fix right now). I'm wary of generalizing anything about what contract rangefeed consumers expect from only the changefeed data point. Given that you thought this was a good idea while this was most loaded up in your head, it's probably safest to keep the filtering in changefeed for now (and document this more loudly on at least some of RangeFeedRequest/RangeFeedCheckpoint/(*DistSender).RangeFeed). We can reconsider this later once Rangefeed has more consumers.

> The one case where this might come up is immediately after a rangefeed's catch-up scan. If we filter checkpoints with timestamps below the rangefeed's start timestamp, a rangefeed may be unable to signal that it has completed its catch-up scan. Is that ok?

Rangefeed currently signals the end of a catchup scan with an empty timestamp, no? I'd imagine it's not surprising to exempt this from the filtering if we did it.

**Comment by danhhz** [comment]
We're still seeing long recovery times on this test so I made it more lenient in #37498. Definitely a thread to pull on here, but it does seem to eventually recover, so not an emergency.

(Interestingly the last 3 are tightly grouped: 11m17s, 11m12s, 11m23s. The failure condition is 10m, so we wouldn't see anything less than that, but nothing between 10m and 11m or above 12m. There were a few failures with much longer times before the last round of fixes, so dunno whether to read anything into this.)

**Comment by ajwerner** [comment]
I do not know anything about this. I suspect it had to do with catch-up scans. Moving off my board.

**Comment by miretskiy** [comment]
Stale.
