### ISSUE TITLE
changefeedccl: `updated` timestamps, and a schema change committing at the same time as a user txn

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#36885]
When a schema change is run on a table being watched by a changefeed, something like the following happens (omitting irrelevant details):

- t1: schema change writes new table descriptor version (v1) with a mutation (ex add column)
- t2: some writes happen to the table
- t3: while live traffic continues to be served, a _schema change backfill_ and the schema change state machine is run
- t4: some writes happen to the table
- t5: schema change writes new table descriptor version (v2) with the mutation finalized as public

During `[t1,t5)` any changes to the kv for an individual row are interpreted and emitted using tabledesc v1. This includes any modifications written by the schema change backfill. Then, once the mutation goes public, a _changefeed backfill_ is run and every row in the table is emitted using tabledesc v2 and with an updated timestamp set to the ModificationTime of the tabledesc (which is t5 in this case).

If a transaction that modifies this table also commits at exactly t5, then a row will be emitted for it with an updated timestamp of t5. The _changefeed backfill_ will also emit a row at t5. My reading of the code right now is that, with RangeFeeds, these could be emitted in either order.

We should decide what the behavior should be here and make sure it happens. I think we simply want to make sure they're exact duplicates, which amounts to being careful about the `==` case between a changed kv and which table desc is used to interpret it. Specifically, if a user data kv is written at time `t`, it needs to be emitted using the first table descriptor with a `ModificationTime <= t` and when we do the changefeed backfill, it needs to run with the txn timestamp set to exactly the ModificationTime of the descriptor.

cc @nvanbenschoten @rolandcrosby I've mentioned this to both of you in passing. While I was writing it up, I realized both that the zombie job isn't necessary to include and it might be easier to fix than I was fearing.

Jira issue: CRDB-4476

**Comment by miretskiy** [comment]
Closing; stale.
