### ISSUE TITLE
changefeedccl: improve impl of changefeed.max_behind_nanos metric

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#36908]
It currently works by having each changefeed register itself in a map and the metric is a `FunctionalGauge` that checks for the smallest value in the map. This very critically depends on a changefeed de-registering when it stops/pauses, because this is otherwise indistinguishable from a changefeed that has stopped making progress. I'm not particularly comfortable that the current de-registration works in all cases. In fact, I think I saw this happen once, though I've lost the proof.

https://github.com/cockroachdb/cockroach/blob/4122a21b4e2d9350a09818a91953aec9bdc1083f/pkg/ccl/changefeedccl/changefeed_processors.go#L448-L464

For Stores, we have a goroutine that periodically polls and updates the various non-Functional Guages directly. I wonder if something similar could be done here. My first thought was to poll the jobs table, which is nice because then the metric always agrees with what we show in the admin ui, but this doesn't work for sinkless feeds, which don't get a jobs entry.

This metric is the main way that users monitor changefeeds, so it's worth thinking about ways for us to be more comfortable with its reliability.

Epic CRDB-8669

Jira issue: CRDB-4472

**Comment by danhhz** [comment]
The reason I'm uncomfortable with the deregistration is that there isn't a clear hook in the processor lifecycle that always gets called. It should be `close` but there is a lot of complex edge cases in making sure it gets called every time and most distsql processors doesn't leak resources when it's not, so it's hard to catch. However, if we can rely on close to always be called when a processor shuts down, that solves this problem for us. @tbg suggested offline that a finalizer could be used to assert that this happens (likely a panic in tests and a sentry report in prod), which makes it louder when we violate the invariant.

**Comment by danhhz** [comment]
I may be overthinking this. The Processor interface just has a Run method. The changefeed processors use ProcessorBase's Run impl, which calls Start and then repeatedly calls Next. If we make sure to do all resource allocation in Start, then we should be able to make sure nothing leaks by putting a defer in ProcessorBase.Run right after the Start call

**Comment by danhhz** [comment]
I think having better semantics here would also let us resolve the very unfortunate memory monitor semantics in https://github.com/cockroachdb/cockroach/blob/e62203c235032158913d32644172109be08dd5b9/pkg/ccl/changefeedccl/changefeed_processors.go#L162-L172

**Comment by miretskiy** [comment]
many problems w/ max_+behind metrics; but this won't addressed as part of this very old issue.
