### ISSUE TITLE
client: make roachpb.NewError work with wrapped ErrorDetailInterface errors

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#36918]
More generally, when calling into `client.DB` methods and using `client.SendWrappedWith`, it'd be nice if we could (for example) look for a `BatchTimestampBeforeGCError` in some sort of structured way. Right now, there are is an `error.Wrap` somewhere that's causing us to loose this structure. See https://github.com/cockroachdb/cockroach/pull/36132#pullrequestreview-219260407 for context

**Comment by danhhz** [comment]
Assigning @knz in case this is in scope for your current errors work. If it's not, feel free to unassign.

**Comment by knz** [comment]
yay!

**Comment by knz** [comment]
Covered in #36987

**Comment by knz** [comment]
Foldinig under #54939
