### ISSUE TITLE
changefeedccl: revisit sarama tunings

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#36917]
Sarama (our kafka client library) internally buffers every message you give it so it can send them out in a batch (which improves throughput). There are three options to control this batching, `Producer.Flush.Messages` which starts a flush whenever some number of messages have been buffered, `Producer.Flush.Bytes` which flushes when some byte limit of buffered messages has been reached, and `Producer.Flush.Frequency` which bound the amount of time a message can be buffered inside sarama. If multiple have been set, they're ORd, so if any of them are true, it flushes out the buffer.

Changefeeds are broken into a ChangeAggregator processor per node, which does the work of collecting changes and emitting them. All the ChangeAggregators then send range-level progress info to a ChangeFrontier processor, which aggregates them. To make sure that we don't lose any messages if a node shuts down, the ChangeAggregator can only forward a range-level progress message if it knows that everything it has handed to sarama has made it all the way to kafka and been acknowledged. Unfortuantely, sarama doesn't have a hint to tell it to flush, so the only way we can do this in a timely manner is to set `Producer.Flush.Messages` to 1, so it starts a flush after every message. This almost certainly kills our throughput.

It would be a quick experiment to remove this, change `Producer.Flush.Frequency` to something like 1s and run the cdc/initial-scan roachtest, comparing the throughput to the current tunings. If this makes a big difference, then we could productionize the change by getting a hook in sarama to manually start a flush.

While we're looking at these tunings, we should do this comment (additional context https://github.com/Shopify/sarama/issues/805): https://github.com/cockroachdb/cockroach/blob/e608c3bb6604555c242d317c9721f175e915485e/pkg/ccl/changefeedccl/sink.go#L364-L368

Epic CRDB-8665

Jira issue: CRDB-4470

**Comment by miretskiy** [comment]
I believe this was addressed, to some extent, by #63039 

I'm inclined to close this issue in favor of opening new ones around benchmarking + usabilty.  @amruss, @ajwerner thoughts re closing?

**Comment by miretskiy** [comment]
I’m realizing that with the recent kafka sink config change, we should be able to make kafka backfills more efficient (i.e. faster).  Even if you have a default “low latency” configuration for kafka, there is absolutely no reason to emit each event that comes in in efficient, and large ExportSpan responses, as a separate event.  Backfills, and to some extend catchup scans, simply are not “low latency” type events.  Perhaps we should have a mechanism to give sink a hint that a we’re doing e.g. backfill, so that the sink can handle things more efficiently.  This likely applies to kafka sink only.

**Comment by miretskiy** [comment]
Stale; we have various knobs to tune sarama, and we have a bit more smarts in our sink implementation.
