### ISSUE TITLE
optimizer: Query plan time is in the hundreds of milliseconds when using the locality aware optimizer

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/cockroach#36935]
**Describe the problem**
I have a promo_codes table with three indexes that are pinned to us east, west, and central regions in gce. When I query the table from a gateway node, I see that the optimizer is indeed preferring the closest index, however, the plan time is very high. 

I could understand if only the first plan time was high, but in this case the second plan time was high. If I apply consistent load the plan time is still dominates the cost of this query.

**To Reproduce**
Follow steps 1-18 for setting up a geo-distributed cluster - https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/109314241/Geo-Partitioning+a+Multi-Region+Cluster

Run `docker run -it --rm cockroachdb/movr:19.04.2 --app-name "movr-load" --url "postgres://root@[EASTCOASTLB]:26257/movr?sslmode=disable" load --num-users 1000 --num-rides 1000 --num-vehicles 100 --city "new york" --city chicago --city seattle`

Partition tables and create reference table indexes
`docker run -it --rm cockroachdb/movr:19.04.2 --app-name "movr-partition" --url "postgres://root@[EASTCOASTLB]:26257/movr?sslmode=disable" partition --region-city-pair "e:new york" --region-city-pair "c:chicago" --region-city-pair "w:seattle" --region-zone-pair "e:us-east1" --region-zone-pair "c:us-central1" --region-zone-pair "w:us-west1"`

![image](https://user-images.githubusercontent.com/894257/56383337-97956200-61e7-11e9-9bd5-b2df7a865a6d.png)

![image](https://user-images.githubusercontent.com/894257/56383413-ba277b00-61e7-11e9-853e-fdb76288520c.png)

Connect to the west coast load balancer with the SQL shell
`cockroach sql --url 'postgres://root@[WESTCOASTLB]:26257/movr?sslmode=disable&application_name=west_client'`

Grab a promo code:
`select code from promo_codes limit 1;`

and run a single query to get the full record using that code
`select code, description, creation_time, expiration_time, rules from promo_codes where code = 'American_focus_respond_1555612602.7240553';`

You'll see the correct index was used, and the plan time was very low (279 microseconds):
![image](https://user-images.githubusercontent.com/894257/56383611-3fab2b00-61e8-11e9-8e3b-ab5eb1de255d.png)

Run the same query again
`select code, description, creation_time, expiration_time, rules from promo_codes where code = 'American_focus_respond_1555612602.7240553';`

the plan time is now in the hundreds of ms.
![image](https://user-images.githubusercontent.com/894257/56383681-6cf7d900-61e8-11e9-9af6-f2067ae91d6c.png)

 - CockroachDB version:  `Server version: CockroachDB CCL v19.1.0-beta.20190318-950-gb47269e (x86_64-unknown-linux-gnu, built 2019/04/18 15:07:26, go1.11.6)`

cc @andy-kimball

**Comment by nstewart** [comment]
Running a third time is even higher: 
![image](https://user-images.githubusercontent.com/894257/56384526-974a9600-61ea-11e9-877c-6f45f5439117.png)

**Comment by awoods187** [comment]
@andy-kimball if this is in fact a bug do you think it could be fixed for `19.1.1`?

**Comment by nstewart** [comment]
Speaking with @andy-kimball  it like that these are the results of cache misses on the different nodes when ha proxy routes request to new machines. I have 3 modes here so unfortunately I got 3 misses.

I'm going to run some tests point load to a node directly and see what happens.

**Comment by nstewart** [comment]
Closing as the high latencies were due to cache misses on various machines. The web UI currently doesn't have time series for the statements page so this was evidenced by the standard deviation increase.

Here's what the statement page looks like after load has been running for some time. This is what I would have expected.

![image](https://user-images.githubusercontent.com/894257/56438319-8fedc000-62b0-11e9-8e99-06da5c296657.png)


Created https://github.com/cockroachdb/docs/issues/4672 to clarify for users.
