### ISSUE TITLE
pq: unknown signature: json_set(jsonb, string, string)

### ISSUE THREAD

**Issue by halleyshx** [cockroachdb/cockroach#36991]
hi，I hava a problem like tilte " pq: unknown signature: json_set(jsonb, string, jsonb)" when I do this update :
'''
**update sysbench01.programming set posts = json_set(posts, '{"c_birth_year"}','"6666"')::JSONB where posts @> '{"c_current_addr_sk":"2282946"}';
pq: unknown signature: json_set(jsonb, string, string)**
'''
Is there something wrong with it?
what can I do?

Enviorment:

1. cockroach 2.1.6
2. show create programming; 
  table_name  |                create_statement                 
+-------------+------------------------------------------------+
  programming | CREATE TABLE programming (                      
              |     id UUID NOT NULL DEFAULT uuid_v4()::UUID,   
              |     posts JSONB NULL,                           
              |     CONSTRAINT "primary" PRIMARY KEY (id ASC),  
              |     FAMILY "primary" (id, posts)                
              | )    
3. data   {"c_birth_year":"1936","c_current_addr_sk":"2282946","c_current_cdemo_sk":"980124"}

How can I update posts-c_birth_year-6666 ?
Thanks!

**Can you show some examples more and more in the https://www.cockroachlabs.com/docs/v2.0/functions-and-operators.html#jsonb-functions ?
Thanks very much!

**Comment by halleyshx** [comment]
Do it  like this,it's can success, bool not must in this:
### update sysbench01.programming set posts = json_set(posts, '{c_birth_year}'::STRING[], '"6666"', false) where posts @> '{"c_current_addr_sk":"3947999"}';

**Comment by dpkirchner** [comment]
This is old but I found it while trying to figure out this exact issue. Here's how I use json_set:

```
UPDATE foo
SET metadata = json_set(metadata, '{key}'::string[], to_json("value"::string))
WHERE bar = 'xyz'
```
