### ISSUE TITLE
changefeedccl: no key for deleted records in cloud storage sink

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#36994]
Kafka has a key and a value in each message, but there's no place to put the key in the cloud storage sink, which is just an ndjson file of the values. I'd intended to put the key in the value in this case, but looks like that got dropped. This would also be a nice `WITH option` to have for non-cloud storage changefeeds, too.

**Comment by rolandcrosby** [comment]
Thanks for filing. That's exactly the fix I was thinking of - an option like `WITH key_in_value` or something, which defaults to on for cloud storage and off for other sinks.

**Comment by danhhz** [comment]
I have a branch that fixes this, but defaulting the option on makes some of the errors talk about disallowing an option you didn't specify, which is pretty confusing. Still more thinking to be done here

https://github.com/danhhz/cockroach/blob/cdc_cloudstorage/pkg/ccl/changefeedccl/changefeed_test.go#L1447-L1459
