### ISSUE TITLE
ui: make timestamps consistently absolute

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#37019]
**Describe the problem**

In the Jobs table in the webui the information is timestamped with X hours ago:
![image](https://user-images.githubusercontent.com/22278911/56547493-a4011e00-654b-11e9-88f8-d4abd859981f.png)
This makes it really hard to look at the other graphs and understand what time certain events occured:
![image](https://user-images.githubusercontent.com/22278911/56547526-baa77500-654b-11e9-8ea1-4857ac837d45.png)

It'd be great if the jobs table printed the time the job started and completed so that we could easily compare it to the graph instead of guessing when the event happened to the cluster.

**Comment by piyush-singh** [comment]
Worth noting that this is a general inconsistency that arises throughout the UI. Renaming the issue to capture that. We should consistently use absolute time throughout the UI so that all timestamps can be easily compared with one another.

**Comment by tbg** [comment]
+1 just had this issue, I want to know when exactly this started:

<img width="248" alt="image" src="https://user-images.githubusercontent.com/5076964/72916056-95959c00-3d41-11ea-9cad-a72f8ea4b611.png">
