### ISSUE TITLE
Failed tests (10829): TestGetTruncatableIndexes: log was not correctly truncated, older first index:11, current first index:11

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#3702]
The following test appears to have failed:

[#10829](https://circleci.com/gh/cockroachdb/cockroach/10829):

```
I0108 12:56:12.917814 918 storage/replica.go:1574  gossiping first range from store 1, range 1
I0108 12:56:12.919978 918 storage/raft_log_queue.go:74  the raft group doesn't exist for range 100
I0108 12:56:12.929659 918 storage/raft_log_queue.go:133  truncating the raft log of range 1 to 22
I0108 12:56:12.931366 918 storage/raft_log_queue.go:74  the raft group doesn't exist for range 100
I0108 12:56:12.931908 918 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- FAIL: TestGetTruncatableIndexes (0.02s)
	raft_log_queue_test.go:96: log was not correctly truncated, older first index:11, current first index:11
=== RUN   TestIsRed
--- PASS: TestIsRed (0.00s)
=== RUN   TestReplaceNode
--- PASS: TestReplaceNode (0.00s)
=== RUN   TestRotateRight
--- PASS: TestRotateRight (0.00s)
=== RUN   TestRotateLeft
--- PASS: TestRotateLeft (0.00s)
=== RUN   TestSwapNodes
--
I0108 12:56:34.182716 918 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
I0108 12:56:34.182869 918 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestLeaderAfterSplit (0.24s)
=== RUN   Example_rebalancing
--- PASS: Example_rebalancing (0.80s)
FAIL
FAIL	github.com/cockroachdb/cockroach/storage	22.783s
=== RUN   TestBatchBasics
I0108 12:56:46.847311 977 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.01s)
=== RUN   TestBatchGet
I0108 12:56:46.851990 977 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.01s)
=== RUN   TestBatchMerge
I0108 12:56:46.858311 977 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestBatchMerge (0.00s)
=== RUN   TestBatchProto

```
Please assign, take a look and update the issue accordingly.

**Comment by tschottdorf** [comment]
I can't reproduce this locally, I always get #3694 instead. @dt, while you're at it (but this one second).

**Comment by dt** [comment]
Played with this for couple hours: my initial suspicion was cached TruncatedState but commenting out the `r.getCachedTruncatedState` didn't help. Still digging.

**Comment by dt** [comment]
So, duplicating the `ForceRaftLogScanAndProcess` call _does_ seem to fix it (75k runs w/ 0 failures) -- not exactly a root-cause fix but potentially interesting. I can keep digging next week, but if it's too flaky in the meantime I could send up a PR with that as a stop-gap?

**Comment by tschottdorf** [comment]
how many failures do you get per 1k runs without the duplication? Feel free to send a skip if you suspect it's going to happen often enough to annoy folks.

**Comment by dt** [comment]
As-is I generally am seeing ~1 failure per 10k runs, using `STRESSFLAGS='-p 16'`.

As far as short-term fix: my inclination is somewhat towards the duplicated flush (with a comment explaining that it is a hack), rather than skipping the test entirely?

**Comment by bdarnell** [comment]
In general I'd rather just skip the test than hack in a "fix" we don't fully understand.

**Comment by dt** [comment]
Figured it out:
If the processLoop beats the DrainQueue call to popping an event, DrainQueue may return
before the event is actually processed and the test can fail.

Waiting for the stopper to finish tasks before proceeding ensures that if this happens, the event
is still processed before the test proceeds.

**Comment by BramGruneir** [comment]
Nicely done!
