### ISSUE TITLE
exec: support window frames for window functions in vectorized engine

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#37037]

**Comment by yuzefovich** [comment]
@DrewKimball I reopened this issue because the already supported window functions also need to be taught about the window frames (e.g. `select rank() over (order by a range 1 preceding) from t;` is still currently handled by the rowexec windower).

**Comment by DrewKimball** [comment]
I see. Sounds good

**Comment by DrewKimball** [comment]
Oh, actually I think we're good to close this after all once first_value, last_value and nth_value are done. Non-aggregate window functions other than first_value, last_value and nth_value seem to all ignore the window frame:
```
postgres=# select x, y, rank() over (order by y ROWS BETWEEN 1000 FOLLOWING AND 1000 FOLLOWING) from t;
 x |          y          | rank
---+---------------------+------
 1 |                   1 |    1
 4 |                   1 |    1
 5 |                  20 |    3
 3 | 9223372036854775807 |    4
 2 |                     |    5
(5 rows)
```
Postgres doesn't really have any documentation for this, but here's a relevant quote from MySql docs:
>Standard SQL specifies that window functions that operate on the entire partition should have no frame clause. MySQL permits a frame clause for such functions but ignores it. These functions use the entire partition even if a frame is specified:
CUME_DIST()
DENSE_RANK()
LAG()
LEAD()
NTILE()
PERCENT_RANK()
RANK()
ROW_NUMBER()

**Comment by yuzefovich** [comment]
Oh yeah, I think you're right. We don't look at the frames for those window functions in the row engine either, and I guess we just unnecessarily prohibited frames for them in the vectorized engine.
