### ISSUE TITLE
sql: refactor window functions infrastructure

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#37038]
- [ ] It'd be great if we could pass a constant value as an argument to a window function once instead of rendering the full column for it
- [ ] fleshing out API about passing through columns

**Comment by yuzefovich** [comment]
As another idea, we could introduce a different planNode instead of modifying the existing windowNode.

cc @justinj add any requests/ideas to this issue.

**Comment by asubiotto** [comment]
@yuzefovich Is this issue still current?

**Comment by yuzefovich** [comment]
Hm, I think I imagined that Justin would put more things in this issue that would help with his work on window functions in the optimizer, but he was able to do that with the current "window functions infrastructure".

I think the first point of the issue is still valid and will be probably more of a concern when we start implementing window functions that take in arguments (we haven't done so yet) in the vectorized engine. The second point, though, could probably be dismissed.

**Comment by yuzefovich** [comment]
I think we should close this issue given that it was kept mostly because of the first point in how it relates to the vectorized engine, but we project constants but copying the value into every tuple in there, and I think the same will happen with window functions and seems acceptable.
