### ISSUE TITLE
ui: handle errors in overview stats gracefully

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#37043]
**Describe the problem**

In a cluster with a few nodes down, a user noted that several of their overview metrics were displaying "NaN" instead of meaningful values:
<img width="470" alt="image" src="https://user-images.githubusercontent.com/21692034/56604424-e10ef400-65cf-11e9-960e-f70187ad3ae4.png">
<img width="568" alt="image" src="https://user-images.githubusercontent.com/21692034/56604446-e8ce9880-65cf-11e9-89d8-779615cac59f.png">

Instead of NaN we should gracefully handle errors where we are unable to fetch these statistics. The cluster in question had 2 nodes that were down that might have caused the underlying issue responsible for the NaN values.

**Comment by vilterp** [comment]
This is where (some of) those numbers are added up:
https://github.com/cockroachdb/cockroach/blob/f320f08560a5832bb708df60c46b3be475b5eeb7/pkg/ui/src/redux/nodes.ts#L203-L204

This is the endpoint that loads the stats: https://github.com/cockroachdb/cockroach/blob/36f803d7fd39e5113b14e0b38bc2f8706798d9aa/pkg/server/status.go#L955-L957

The stats are being read from a certain range (the node status range) which stores info about the nodes, including all their latest metric values. It's updated by this: https://github.com/cockroachdb/cockroach/blob/079d40a075fc5d5d3ff971af88b431bae8730be2/pkg/server/status/recorder.go#L500-L502

The customer sent us a screenshot of a timeseries graph which showed 0 underreplicated and unavailable ranges for the cluster. So, my theory is that something is going wrong in `WriteNodeStatus` or the `Nodes` endpoint, s.t. those numbers aren't making it from the original metric (which is fine) to the node status range, to the UI.
