### ISSUE TITLE
exec: change null representation to be uint8s instead of uint64s for arrow compat

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#37045]
Arrow null bitmaps are represented as an array of bytes where each byte is read right to left (LSB first) as such:
```
is_valid[j] -> bitmap[j / 8] & (1 << (j % 8))
```
We do the same thing but in groups of 64 bits (int64):
```
intIdx := i >> 6
return ((m.nulls[intIdx] >> (i % 64)) & 1) == 1
```
equivalent to:
```
is_valid[j] -> bitmap[j / 64] & (1 << (j % 64))
```
Which means that even if we flip all the bits in a bitmap to our representation we will still have an issue. Take for example checking validity of the 0th index. This will be the 8th bit in the bitmap in arrow, but the 64th in ours.

This is an issue because we want to have arrow-compatible serialization to avoid changes down the line that will break backwards compatibility. Until we start planning this serialization, there is no correctness issue since we currently just blindly cast our null bitmap whenever we have any nulls, so there are no compatibility issues.

**Comment by solongordon** [comment]
I'm presuming we also want to flip the bits in our nulls representation to match Arrow, right?

**Comment by asubiotto** [comment]
Right! Essentially we want them to look like what is described here: https://arrow.apache.org/docs/memory_layout.html
