### ISSUE TITLE
config: default zone config should not be a global

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#37054]
We have a global default for zone config which is changed by tests. Code in various layers uses `config.DefaultZoneConfig()` directly. This leads to problem with parallel tests; this is a good example (in `TestServer.Start`)

```go
	// TODO(andrei): Running two TestServers concurrently with
	// PartOfCluster==false can result in the default zone config not be reset
	// properly. It would be nice if this were more robust.
	if !params.PartOfCluster {
		// Change the replication requirements so we don't get log spam about ranges
		// not being replicated enough.
		cfg := config.DefaultZoneConfig()
		cfg.NumReplicas = proto.Int32(1)
		fn := config.TestingSetDefaultZoneConfig(cfg)
		params.Stopper.AddCloser(stop.CloserFn(fn))
	}
```

The default zone config should be a property of a server/cluster rather than a global.

**Comment by RaduBerinde** [comment]
CC @andreimatei @andy-kimball seems like this is most relevant to core, not sure who to assign to.

**Comment by jeffrey-xiao** [comment]
I'm running into an issue with adding a default zone config object to a server config. The server config object lives in the base package (`server/config.go`) and the zone config object lives in the config package (`config/zone.pb.go`). If I include the config package in the base package, I get a import cycle. What's the best way to resolve this?

**Comment by nvanbenschoten** [comment]
Why do you need to import the `config` package from `base`? Don't you just need it in the `server` package?
