### ISSUE TITLE
support nested select statements

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#3707]
```
CREATE TABLE t (k INT PRIMARY KEY, v INT, w INT);
INSERT INTO t VALUES (1, 1, 1), (2, NULL, NULL);
SELECT * FROM t WHERE k > 0;
 k | v | w 
---+---+---
 1 | 1 | 1
 2 |   |  
(2 rows)

SELECT foo.k, foo.w FROM (SELECT * FROM t WHERE k > 0) AS foo;
 k | w 
---+---
 1 | 1
 2 |  
(2 rows)
```
Issue #2692 is a specific case of this.

**Comment by petermattis** [comment]
I think these would be more accurately described as nested selects as there is no self reference involved. Recursive selects use the `WITH` clause (see http://www.postgresql.org/docs/9.4/static/sql-select.html) and are further down the road.

**Comment by petermattis** [comment]
Looking at the documentation I linked to in my previous comment I see that Postgres uses the term sub-select.

**Comment by RaduBerinde** [comment]
Good point, corrected the title.

**Comment by RaduBerinde** [comment]
It looks like the way to go about doing this is to decouple the select code from the scanNode code. This would also make the code more modular and easier to work with.

The plan is roughly as follows:

- create a selectNode that will provide the functionality that scanNode currently provides. All code from scanNode that is generic select code and is not table-specific moves to select.go. This includes aliasing logic.

- selectNode stores a reference to a "from" planNode (will normally be a scanNode).

- at a high level, select code grabs column info and row data from the "from" node and processes it according to the filters, grouping etc. Of course, we still pass appropriate constraint data to scanNode so it can internally optimize table access but this optimization does not affect the logical hierarchy.

- when these changes are done, we should be able to easily add support for other "from" nodes: a nested selectNode or a valuesNode. These changes will also make it easier to add support for multiple FROMs.

I will try to break this up into smaller changes somehow.

**Comment by petermattis** [comment]
Sounds like a reasonable plan. I'll likely have comments on specifics. Definitely try to break this into smaller changes.
