### ISSUE TITLE
closedts: shorten default closed timestamp interval

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#37083]
The current closed timestamp interval is set to 30 seconds. This limit provides an upper bound on the duration of transactions which cannot be pushed. As far as I understand, there are some schema change operations which can be long running (potentially proportional to the size of the data which is being modified) and must currently observe their own timestamp (preventing pushes). In order to feel comfortable lowering this value, we need to ensure that the system does not create these un-pushable long-running transactions. I'm using this issue as a catch all to gather information about work required before we could consider lowering the value.

@dt could you help me identify which operations might currently fall in to that category so we can make a decision about whether this is a worthwhile goal?

cc @awoods187 @rolandcrosby

**Comment by awoods187** [comment]
@dt ping on this

**Comment by rolandcrosby** [comment]
Per conversation with @dt earlier this week, this may be a bit of a heavy lift - some long-running transactions in the schema change world depend on running at a particular time and can't easily be bumped. I'll let him chime in with additional details.

**Comment by dt** [comment]
Without knowing which specific transactions are causing problems, it is hard to say exactly how hard it will be to change them. Do we have any idea which ones were initially identified as areas of concern?

I guess if we don't know anything, just off the top of my head, I'd say spin up a tpcc1k cluster (or 2k if the schema changes are too quick on 1k) and go though adding an index, adding a column that does/n't have a default value (particularly a default that observes the clock), dropping a column, renaming a table, dropping a table, adding a foreign key, validating a foreign key, adding/validating a CHECK (particularly one that observes a clock)? Some of this stuff might have roachtest coverage but probably not at larger scales since those end up being more fixture loading than test running when done individually in nightlies.

one thing I do know is that many of our schema changes also write in txns that call `SetFixedTimestamp` with a timestamp in the past -- is that going to be a problem?

**Comment by bdarnell** [comment]
> one thing I do know is that many of our schema changes also write in txns that call SetFixedTimestamp with a timestamp in the past -- is that going to be a problem?

I think the main schema change concern is with writes that use SetFixedTimestamp - such a transaction can't commit if it's behind the closed timestamp. But then how does this work today for schema changes that take more than 30s? Are schema changes safe because we only use SetFixedTimestamp in empty keyspace, and we don't close out timestamps for ranges where no one's watching? 

There's also a concern for transactions that observe their OrigTimestamp (the schema change itself does, but the backfill doesn't, right?). These transactions have to restart instead of refreshing on push so if they take longer than the closed timestamp interval it doesn't really work.

**Comment by ajwerner** [comment]
>  But then how does this work today for schema changes that take more than 30s?

It's not clear that it does. Too much discussion about this topic has been offhand concerns. I believe the comment at the time was that we have no idea how many customers are being impacted by the current target duration and that the idea of lowering it further was scary.

My understanding was that some schema changes don't use a job for backfill but rather just do all of the work inside a big transaction which also happened to observe its timestamp. The concern was that there probably are some of these schema changes which may never complete.

Maybe this isn't actually a problem in practice and if customer's do experience it we can tell them to increase the closed timestamp interval. I believe there's a meeting tomorrow afternoon to try to get on the same page.

**Comment by dt** [comment]
Current plan from the schema change team:
Write a roachtest that creates and populates a cluster with some large table then runs (while the table is under load):
  - [ ] `CREATE TABLE ... REFERENCES t`
  - [ ] `CREATE INDEX ON t...`  
  - [ ] `ADD COLUMN DEFAULT 0`
  - [ ] `ADD CONSTRAINT ... CHECK`
  - [ ] `ADD CONSTRAINT ... FOREIGN KEY`
  - [ ] `VALIDATE CONSTRAINT` (on a CHECK)
  - [ ] `VALIDATE CONSTRAINT` (on an FK) 
  - [ ] `CREATE TABLE AS`

**Comment by ajwerner** [comment]
@tbg had a cool idea to adaptively change the interval here https://github.com/cockroachdb/cockroach/issues/36478. Posting to make sure we don't lose track of that work. 

In the meantime I'm running @adityamaru27's new roachtest with a closed timestamp interval of 2s to see how it goes.

**Comment by ajwerner** [comment]
I ran the `schemachange/mixed/tpcc` roachtest with `kv.closed_timestamp.target_duration` set to each of 30s, 10s, and 2s and all of them passed without issue. Anecdotally at first the 2s run seemed to take a bit longer to run the schema changes but the test ended up having about the same total duration. That observation was completely unscientific and the durations had quite a high variance.

I've also been experimenting with vanilla TPC-C especially running it close to its failure point. On 4-core aws machines (c5d.xlarge) at 500 warehouses (which is not at all at the breaking point) there was no observed difference in efficiency. I next experimented with 16-core aws machines (c5d.4xlarge) at 2300 warehouses (which is past the breaking point). Right up at the edge of TPC-C we see many more transaction restarts due to `Forwarded Timestamp` and tail latencies jump up dramatically. When transactions regularly take longer than the target duration they'll hit this need to restart.

As a baseline I ran the test with the default 30s target_duration and got the following barely not-passing result:

```
_elapsed_______tpmC____efc__avg(ms)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)            
  300.0s    25029.7  84.6%   3106.4   2952.8   5100.3   5905.6   9126.8  81604.4     
```

At a 2s target duration we observe a non-passing tpc-c efficiency of 69%:

```
_elapsed_______tpmC____efc__avg(ms)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
  300.0s    20490.9  69.3%   8243.1   5368.7  18253.6  23622.3  47244.6 103079.2
```

And interestingly a 92.7% efficicency with a target duration set to 5s:

```
_elapsed_______tpmC____efc__avg(ms)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
  300.0s    27420.4  92.7%    755.8    704.6   1409.3   1677.7   2415.9   7247.8
```

One contributing factor to this variance is that the 30s run happened first and over time leaseholder balance has improved. I suspect we have an issue today with our tpccbench roachtest where after the import our leaseholders are highly imbalanced. See the below chart for leaseholder balance over all of the runs I performed. 

![image](https://user-images.githubusercontent.com/1839234/62892584-a1068500-bd16-11e9-83a1-a7be093713b8.png)

I ran the 30s run again after the 5s run and found the following results:

```
_elapsed_______tpmC____efc__avg(ms)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
  300.0s    27581.8  93.3%    578.9    536.9   1040.2   1275.1   1677.7   5637.1
```

For posterity I re-ran the 2s test and got the following almost passing result:

```
_elapsed_______tpmC____efc__avg(ms)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
  300.0s    24137.1  81.6%   3105.2    704.6  10737.4  15569.3  31138.5  90194.3
```

Interestingly on this last run things looked great until a split in the last minute after which restarts and latencies exploded. 

![image](https://user-images.githubusercontent.com/1839234/62892757-0b1f2a00-bd17-11e9-9362-f1d948900d16.png)

Given it is quite possible to pass TPC-C with many query executions taking longer than 2s it is highly likely that such short interval will move the needle back somewhat for our passing TPC-C warehouse count. Once some rare event kicks the tail latency up too high it becomes hard to recover. That being said, 5s will affect far fewer queries than 2s and once we're at the point where transactions regularly take 5s we're close to not passing TPC-C. As we see above the 5s value doesn't seem to have a particularly pronounced impact at 2300 warehouses.

How do we feel about trying to change the default on master to 5s and seeing if there's any fallout? If there's not then we'll feel more confident that it's safe and can change the setting for 19.2.

**Comment by awoods187** [comment]
This is amazing work! I agree and think we should experiment with moving it up to 5 seconds.

**Comment by ajwerner** [comment]
As it happens we do have long-running schema changes which observe their timestamp. Namely `DROP DATABASE` and in a sense `DROP TABLE`. Anything which updates a schema descriptor seems to be a problem because of

https://github.com/cockroachdb/cockroach/blob/770ae0568c864e79c47e0828aa24598cff468967/pkg/sql/sqlbase/structured.go#L1496-L1509

We need to find a way to avoid observing the timestamp when updating table descriptors. Anybody have any clever ideas? On the whole it feels quite late in the game to change the protocol for this release.

**Comment by bdarnell** [comment]
> As it happens we do have long-running schema changes which observe their timestamp. Namely DROP DATABASE and in a sense DROP TABLE.

What makes these long-running? DROP TABLE is just a metadata operation, so it should be fast (unless it's in a transaction with other unrelated stuff).

I could imagine DROP DATABASE CASCADE being long running if there are a lot of tables (how much per-table work does it do in the transaction itself as opposed to the async job?), but I suspect that it's actually doing something stupid and could be made a lot more efficient (see #38984). Maybe we can make these fast enough that they can succeed on retry in spite of the fact that they observe their timestamp.

**Comment by ajwerner** [comment]
DROP TABLE may have to deal with foreign keys and indexes and interleaving did they exist but yes in general DROP DATABASE is much worse. If we could parallelize that work it might be enough.


> how much per-table work does it do in the transaction itself as opposed to the async job

It seems like it has to:

1) remove inbound and outbound fk references
2) remove interleave relationships 
3) remove sequence dependencies
4) remove the table/column comments 
5) get the zone config
6) get all of the ranges to remove the sticky bit if they have one
7) remove all of the sticky bits
8) potentially finish all pending mutation jobs
9) update the table descriptor
