### ISSUE TITLE
Login issue: psql: ERROR:  unimplemented client encoding: "sqlascii"

### ISSUE THREAD

**Issue by boomshadow** [cockroachdb/cockroach#37129]
I'm trying to simply log into CockroachDB using `psql`. I receive an error:
`psql: ERROR:  unimplemented client encoding: "sqlascii"`

Full log output is posted lower down.  I'm running CentOS7 with PostgreSQL's official postgresql10 client release: `psql (PostgreSQL) 10.7`

**To Reproduce**
Simply setup a port forward in 1 terminal, then tried to use `psql` to login in another terminal.

```
$ kubectl port-forward --namespace development cockroachdb-0 26257
# In another terminal, run the following:
$ psql -h localhost -p 26257 -U root
```

Here are my installation steps for `psql`

```
yum install -y https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7-x86_64/pgdg-centos10-10-2.noarch.rpm
yum install -y postgresql10 postgresql10-devel
```

**Additional data / screenshots**
```
[root@fc29988f4223 /]# psql -h localhost -p 26257 -U root
psql: ERROR:  unimplemented client encoding: "sqlascii"
HINT:  This feature is not yet implemented in CockroachDB.

Please check https://github.com/cockroachdb/cockroach/issues to check
whether this feature is already tracked. If you cannot find it there,
please report this error with reproduction steps at:

    https://github.com/cockroachdb/cockroach/issues/new/choose

If you would rather not post publicly, please contact us directly at:

    support@cockroachlabs.com

The Cockroach Labs team appreciates your feedback.
```

**Environment:**
 - CockroachDB version: `image: cockroachdb/cockroach:v2.1.6`
 - psql version: `psql (PostgreSQL) 10.7`
 - OS version: `CentOS 7`

**Comment by jordanlewis** [comment]
Hey @boomshadow, looks like `psql` learned a new feature that we don't have yet. Can you use an older version of `psql` for now, until we add support for `sqlascii`?

**Comment by jordanlewis** [comment]
Hmm, I also can't repro this:

```
[9:31:2]% psql -p 26257 -h localhost -U root       jordan@Jordans-MacBook-Pro:~
psql (11.2, server 9.5.0)
Type "help" for help.

root=#
```

**Comment by boomshadow** [comment]
I wonder if its because I'm specifically using psql 10.7, or on CentOS 7. I get the same problem from a fresh build. Try testing this for yourself. Here's a minimal Docker container that has this psql version installed: https://gist.github.com/boomshadow/3dd843b1aaa3ab6e818033b625ea1952

If I try to log into cockroach on that Docker container, I still get the error about "sqlascii"

**Comment by jordanlewis** [comment]
It looks like that version of `psql` was compiled to use the `sql_ascii` client encoding, which we don't support. We only support the `utf8` client encoding - it's unclear to me what `sql_ascii` should do or whether we should support it. Read https://www.postgresql.org/docs/9.6/multibyte.html for more details - if you can get a `psql` that was compiled with `utf8` support everything should work fine.

```
he SQL_ASCII setting behaves considerably differently from the other settings. When the server character set is SQL_ASCII, the server interprets byte values 0-127 according to the ASCII standard, while byte values 128-255 are taken as uninterpreted characters. No encoding conversion will be done when the setting is SQL_ASCII. Thus, this setting is not so much a declaration that a specific encoding is in use, as a declaration of ignorance about the encoding. In most cases, if you are working with any non-ASCII data, it is unwise to use the SQL_ASCII setting because PostgreSQL will be unable to help you by converting or validating non-ASCII characters.
```

**Comment by knz** [comment]
maybe check the `$LANG` and `$LC_...` env vars in your shell session. `psql` can derive encoding specs from that theoretically.

**Comment by jamiechapmanbrn** [comment]
This can be corrected by setting the PGCLINETENCODING environment variable to utf-8 like so:
`export PGCLIENTENCODING='utf-8'`
