### ISSUE TITLE
I want to know that the KV API can be invoked for external usage？Thanks

### ISSUE THREAD

**Issue by halleyshx** [cockroachdb/cockroach#37159]
From the source /pkg/internal/client/doc.go 
I see "Package client and its KV API have been deprecated for external usage."
I don't understand "deprecated" meaning?  It‘s meaning “can use but don‘t recommend” or “can't use,it deserted” ?
Thank you !

**Comment by andreimatei** [comment]
The `internal/client` package is very much in use, but only internally. The magic "internal" prefix means that the compiler won't let you use it in other projects anyway.

The only interface CRDB exposes to users is SQL.

Please feel free to reopen if you have more questions.
