### ISSUE TITLE
storage: TestLatchManager failure

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#37162]
```
    manager_test.go:137: latch acquisition should succeed
```
https://teamcity.cockroachdb.com/viewLog.html?buildId=1262066&buildTypeId=Cockroach_UnitTests

**Comment by nvanbenschoten** [comment]
Ran for 2,300,000 iterations without a failure with `roachprod-stress`. My best guess is that the machine was overloaded and that the [15ms timeout](https://github.com/cockroachdb/cockroach/blob/dff4132a80e62c6c5ad603ff6c608b09419d4e3e/pkg/storage/spanlatch/manager_test.go#L66) was insufficient. I'm going to bump that significantly and consider this flake resolved.
