### ISSUE TITLE
In product env, is a cluster for one user app or most of users use one cluster?

### ISSUE THREAD

**Issue by yangxuanjia** [cockroachdb/cockroach#37180]
In product env, is a cluster for one user app or most of users use one cluster?

**Comment by andreimatei** [comment]
Different users do different things. The obvious tradeoff is between resource isolation (many clusters) and operational simplicity (a single cluster). CRDB does not have any resource isolation features between client apps currently.
I don't have more specific guidance to give :|.

Please feel free to reopen if you have more specific questions.
