### ISSUE TITLE
Enhancing audit logging in CockroachDB

### ISSUE THREAD

**Issue by sanjimoh** [cockroachdb/cockroach#37209]
**Is your feature request related to a problem? Please describe.**
Audit logging is an essential feature for any production deployment. Unfortunately the existing experimental audit logging feature in CockroachDB doesn't seems to be adequate enough. It would be really nice to see it evolving for a better fit for a production deployment.

**Describe the solution you'd like**
The existing experimental audit logging in CockroachDB only supports READ & WRITE events on a table.

The following events would be really needed to allow an administrator to be able to capture as per his/her needs -

1. CONNECT - The ability to capture connection, disconnection & failed connection events.
2. DCL Queries - The ability to capture DCL queries like create user, drop user set password, 
                            grant/revoke commands.
3. DDL Queries - The ability to only capture DDL queries like create, alter, drop, rename & 
                            truncate commands.

**Comment by rolandcrosby** [comment]
Hi @sanjimoh, thanks for your interest in this feature area. We're looking at adding additional audit logging capabilities like the ones you've mentioned in a future release. Is your goal to capture this log data for security event analysis/auditing, or is there another purpose you have in mind?

**Comment by sanjimoh** [comment]
Hi @rolandcrosby , pretty much you mentioned! The idea currently is to first distinguish between different types of events for example a configuration change event (audit events) from a security related events (auth events) and then separately index those in elastic search to build on top use cases. Couple of use cases would be then like below (& many more) -
1. Bringing on visibility about these events in a dashboard like Kibana for the system administrators.
2. Making these logs available for external SIEM systems. 
Like I already indicated, we see this as a quite essential security feature and would really appreciate if this could be prioritized in the backlog.

**Comment by bobzilladev** [comment]
We would appreciate configurability based on users, as whitelist and/or blacklist. Than a high-throughput API service user could be made not to audit log at this layer, but any other local or admin users' activity would be.

**Comment by bobzilladev** [comment]
Looks like "#3 DDL Queries" may still not be covered.

**Comment by knz** [comment]
This has been addressed using the new structured logging features in v21.1
