### ISSUE TITLE
Mutex instead of RWMutex on Replica and Store

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#3722]
[from this discussion thread](https://github.com/cockroachdb/cockroach/pull/3710#issuecomment-170221620) via @bdarnell 

>
I would definitely make Replica use a Mutex. Store.mu makes a little more sense as a RWMutex since we intend to increase parallelism in the future, but it might be worth changing it to a Mutex for more immediate deadlock detection. Store.mu is on my hit list anyway; I need to refactor locking and the use of the processRaft goroutine.
>
@dt I've wanted to replace all our sync.Mutexes with a wrapper that adds an AssertHeld method; we could use a similar technique with build tags to replace RWMutex with a stricter version in some builds.
>
Maybe one day I'll get around to writing a go version of http://clang.llvm.org/docs/ThreadSafetyAnalysis.html

**Comment by BramGruneir** [comment]
I'll take this on tomorrow.  Should be a relatively easy change.

**Comment by BramGruneir** [comment]
I'm not going to touch the processRaft stuff.  I'll leave that for @bdarnell
