### ISSUE TITLE
distsqlrun: lookup semi and antijoin

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#37240]
Lookup joins currently don't support semi or antijoins. We should resolve this deficiency to give the optimizer more flexibility.

As a reminder, semijoin outputs a row on the left if there exists a match on the right, and antijoin outputs a row on the left if there does not exist a match on the right.

cc @RaduBerinde @justinj

**Comment by RaduBerinde** [comment]
Worth mentioning that both semi and anti only output the left side columns. In some ways it's like a filter for the left side.

**Comment by khalibartan** [comment]
@jordanlewis I would like to work on this.

**Comment by jordanlewis** [comment]
@khalibartan sure, we'll be happy to review contributions - thanks for volunteering!

You will need to modify `pkg/sql/distsqlrun/joinreader.go`. If `jr.joinType` is set to `LeftSemiJoin` or `LeftAntiJoin`, the code should perform a semi or antijoin.

There are unit tests in `pkg/sql/distsqlrun/joinreader_test.go` that you should add to in order to test your code. The tests already have a spot to modify the joinType, so adding new ones for semi / anti join should be straightforward.

Feel free to ping on this thread if you have any questions.

**Comment by jordanlewis** [comment]
Oh and you can run the tests in that package with `make test PKG=./pkg/sql/distsqlrun TESTS=TestJoinReader`.

**Comment by khalibartan** [comment]
@jordanlewis Should right side columns be null or I shouldn't return them at all?

**Comment by RaduBerinde** [comment]
The right side columns should not be part of the schema at all.

> @jordanlewis <https://github.com/jordanlewis> Should right side columns
> be null or I shouldn't return them at all?
>
