### ISSUE TITLE
opt: rewrite const OP ANY(subquery) as EXISTS(subquery WHERE ... OP const)

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#37241]
These two queries are equivalent:

```
root@127.0.0.1:58515/defaultdb> explain select exists(select * from y where b = 3);
       tree      |    field     |             description
+----------------+--------------+--------------------------------------+
  root           |              |
   ├── values    |              |
   │             | size         | 1 column, 1 row
   └── subquery  |              |
        │        | id           | @S1
        │        | original sql | EXISTS (SELECT * FROM y WHERE b = 3)
        │        | exec mode    | exists
        └── scan |              |
                 | table        | y@primary
                 | spans        | /3-/3/#
(10 rows)

Time: 1.24ms

root@127.0.0.1:58515/defaultdb> explain (opt) select 3 = any(select b from y);
           text
+-------------------------+
  values
   └── tuple
        └── any: eq
             ├── scan y
             └── const: 3
(5 rows)

Time: 597µs
```

However, the first is significantly better since it can generate spans.

It might be the case that it's better to address this by instead hoisting the subquery, which would be a more general solution, but wouldn't generate spans at plan time which might be valuable (and is also blocked in the common case by #37240).

Jira issue: CRDB-4443

**Comment by justinj** [comment]
Perhaps the cleaner way to do this would be to hoist the subquery and then add a rule that simplifies that kind of join with a `VALUES` clause into a `Select`,

**Comment by knz** [comment]
still exists in 21.1

**Comment by mgartner** [comment]
I think the following is a valid rewrite:

```
i = ANY (SELECT a FROM t)
=>
(SELECT count(*) > 0 AND
  CASE
  WHEN bool_or(a = i) THEN true
  ELSE (
    CASE
    WHEN bool_or(a IS NULL) THEN NULL
    ELSE (CASE WHEN i IS NULL THEN NULL ELSE false END)
    END
  )
  END
FROM t)
```

Here's some tests showing its equivalence (in Postgres): https://gist.github.com/mgartner/9dac0b802c087329a8e2ee4ff0204bbd

**Comment by mgartner** [comment]
I used this transformation in #98375. I don't think we should use it yet universally, though, because it can lead to plans with slow apply-joins.

Also, it doesn't provide the benefit originally described in this issue - it won't allow constrained scans to be performed. If columns can be prove to be non-NULL then a simpler transformation may be possible. For now I'm going to close this issue.
