### ISSUE TITLE
ui: cluster health endpoint

### ISSUE THREAD

**Issue by maxlang** [cockroachdb/cockroach#3726]
We need an endpoint to track overall cluster health.

Here's Elasticsearch's for reference: https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-health.html

My current plan is:
- Status: healthy/unhealthy
- Issues: if the cluster is unhealthy, this would be a list of the reasons it's in the unhealthy state - eg "not enough nodes for number of replicas," or "out of capacity."

**Comment by tamird** [comment]
Visiting for triage: this exists (in a very limited form), and was migrated to grpc in #6784.

@maxlang do you still intend to do some work here?

**Comment by maxlang** [comment]
@tamird I'm leaving this to track the creation of a more detailed health endpoint. Right now health is a binary, but in the future I expect the endpoint to carry more information.

**Comment by mrtracy** [comment]
Is this still something that needs tracking? This seems to be rotting, especially since nobody has yet outlined a clear need for a more complicated "health" endpoint.

**Comment by spencerkimball** [comment]
I'm closing this as there is no indication we need something more complicated.
