### ISSUE TITLE
sql: show all indexes on a database 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#37270]
**Describe the problem**
We have a `show index from table` command but it'd be useful to see all of the indexes on a database with a `show index from database` or something similar. It could work something like this underneath the hood from [MySQL](https://tableplus.io/blog/2018/08/mysql-how-to-list-all-indexes-from-table-or-schema.html):
```
SELECT
    DISTINCT TABLE_NAME,
    INDEX_NAME
FROM
    INFORMATION_SCHEMA.STATISTICS
WHERE
    TABLE_SCHEMA = `schema_name`;
```

And presents something like this:
```
  table_name | index_name | non_unique | seq_in_index | column_name | direction | storing | implicit
+------------+------------+------------+--------------+-------------+-----------+---------+----------+
  order      | primary    |   false    |            1 | o_w_id      | ASC       |  false  |  false
  order      | primary    |   false    |            2 | o_d_id      | ASC       |  false  |  false
  order      | primary    |   false    |            3 | o_id        | DESC      |  false  |  false
  warehouse  | primary    |   false    |            1 | w_id        | ASC       |  false  |  false
 history    | primary    |   false    |            1 | rowid       | ASC       |  false  |  false
```

**Comment by rohany** [comment]
what kind of syntax would you be looking for in this command? It is unclear how to support in the parser both `show indexes from <tablename>` and `show indexes from <databasename>` due to conflicts. I was considering the syntax `show indexes from db <databasename>`, if this sounds good to you.

**Comment by rohany** [comment]
Implement in  #37942. You can use the command `show indexes from database <database_name>` to see this information now.
