### ISSUE TITLE
storage: grab hlc timestamp outside of raftMu in tick

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#37278]
Contention on the hlc.Clock.Mutex shows up regularly in mutex profiles. Blocking while holding the raftMu is problematic for write performance. Currently the replica reads the hlc clock twice while holding the raftMu [in maybeTransferRaftLeadershipLocked](https://github.com/cockroachdb/cockroach/blob/38d473e5b07010a96a02278f540010479d5bba9c/pkg/storage/replica.go#L1580) and [in maybeQuiesceLocked](https://github.com/cockroachdb/cockroach/blob/38d473e5b07010a96a02278f540010479d5bba9c/pkg/storage/replica_raft_quiesce.go#L163). For both cases a potentially stale timestamp would be valid and can be grabbed before acquiring the replica mutexes.

Part of #37276.

**Comment by erikgrinaker** [comment]
Closing, see https://github.com/cockroachdb/cockroach/issues/37276#issuecomment-968078463.
