### ISSUE TITLE
storage: reduce hlc.Clock locking in Store.Send

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#37277]
As part of the goal of reducing hlc.Clock mutex contention, we should re-evaluate the hlc.Clock interactions in `storage.Store.Send()`. Currently `storage.Store.Send()` interacts with the clock twice when it could do it once. First it calls `hlc.Clock.Now()` to set the active timestamp [here](https://github.com/cockroachdb/cockroach/blob/38d473e5b07010a96a02278f540010479d5bba9c/pkg/storage/store.go#L2800) and the it calls Update in one of its forms [here](https://github.com/cockroachdb/cockroach/blob/38d473e5b07010a96a02278f540010479d5bba9c/pkg/storage/store.go#L2841).

Part of #37276

**Comment by erikgrinaker** [comment]
Closing, see https://github.com/cockroachdb/cockroach/issues/37276#issuecomment-968078463.
