### ISSUE TITLE
Java, data generation: HandledRetryableTxnError: TransactionRetryError: retry txn (RETRY_ASYNC_WRITE_FAILURE). JSON data is inserted (related to the problem or not).

### ISSUE THREAD

**Issue by Samusername** [cockroachdb/cockroach#37290]
What could cause following problem / error?

Works ok first
...
Obj / s: 1745.2066467831273
Obj / s: 1692.5619834710744
Then:
Exception in thread "main" org.postgresql.util.PSQLException: ERROR: restart transaction: HandledRetryableTxnError: TransactionRetryError: retry txn (RETRY_ASYNC_WRITE_FAILURE): "sql txn" id=24e83c48 key=/Table/108/1/106497/0 rw=true pri=0.00333418 iso=SERIALIZABLE stat=PENDING epo=0 ts=1556893588.784299626,0 orig=1556893588.784299626,0 max=1556893588.785428551,0 wto=false rop=false seq=4098
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgConnection.executeTransactionCommand(PgConnection.java:755)
	at org.postgresql.jdbc.PgConnection.commit(PgConnection.java:777)
	at GenerateData.main(GenerateData.java:91)

nodes status:

  id |     address      | build  |            started_at            |            updated_at            | is_available | is_live  
+----+------------------+--------+----------------------------------+----------------------------------+--------------+---------+
   1 | 172.21.0.4:26257 | v2.1.6 | 2019-05-03 06:06:44.012158+00:00 | 2019-05-03 13:35:14.055847+00:00 | true         | true     
   2 | 172.21.0.2:26258 | v2.1.6 | 2019-05-03 06:06:45.132575+00:00 | 2019-05-03 13:35:10.676226+00:00 | true         | true     
   3 | 172.21.0.3:26259 | v2.1.6 | 2019-05-03 06:06:44.141806+00:00 | 2019-05-03 13:35:09.714409+00:00 | true         | true  

nodes get started in following way:

start --cache=0.53 --max-sql-memory=.22  --certs-dir=/certs --join=172.21.0.4,172.21.0.2,172.21.0.3 --listen-addr=172.21.0.4
Listen addr is of course node dependent.

JDBC: postgresql-42.2.5.jar
Batch insert. JSON. Autocommit off, connection.commit().
No threads.
E.g. java 8 or java 10.

image: cockroachdb/cockroach:v2.1.6
docker
Linux, Ubuntu 16.04

I can send source codes of a small test applicaiont by email to Cockroach lab personnel. GenerateData.java. It does basic things with basic JDBC functionalities.

**Comment by Samusername** [comment]
Attachment, GenerateData.java

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.time.Duration;
import java.time.Instant;
import java.util.Properties;
import java.util.Random;


/*

  create table ABCD_TBL
  (
  id                        bigint not null,
  ts                        timestamp,
  person                    VARCHAR (32) not null,
  attributes                jsonb,
  PRIMARY KEY ( ID )
  );

*/


public class GenerateData {
    static Random rand = new Random();
    static long ctr = 0;

    public static String generateJsonContents () {
        String jsondata = "{ ";
        int amountP = 17;
        for(int g = 0; g <= amountP; g++) {
            jsondata += "\"paramName";
            jsondata += g;
            jsondata += "\":\"value";
            jsondata += rand.nextInt(1000000000);
            jsondata += "\"";
            if ( g < amountP ) {
                jsondata += ", ";
            }
        }
        jsondata += " }";
        return jsondata;
    }

    public static void main(String[] args)
            throws ClassNotFoundException, SQLException {

        // Load the Postgres JDBC driver.
        Class.forName("org.postgresql.Driver");

        // Connect to the "bank" database.
        Properties props = new Properties();
        props.setProperty("user", "spock");
        props.setProperty("sslmode", "require");
        props.setProperty("sslrootcert", "certs/ca.crt");
        props.setProperty("sslkey", "certs/client.spock.pk8");
        props.setProperty("sslcert", "certs/client.spock.crt");
        props.setProperty("ApplicationName", "roachtest");

        Connection connection = DriverManager
                 .getConnection("jdbc:postgresql://127.0.0.1:26257/test", props);
                // same error with:
                // .getConnection("jdbc:postgresql://127.0.0.1:26257/test?reWriteBatchedInserts=true", props);

        String insertSql = "INSERT INTO ABCD_TBL(id, person, attributes) "
                + "VALUES (?,?,?)";

        connection.setAutoCommit(false);

        try {
            PreparedStatement pStmt = connection.prepareStatement(insertSql);

            int amount = 4096;
            for(int j = 0; j < 150; j++){
                Instant start = Instant.now();
                for(int i = 0; i < amount; i++) {

                    ctr += 1;

                    String jsondata = generateJsonContents();

                    pStmt.setLong(1, ctr);
                    pStmt.setString(2, "person");
                    pStmt.setString(3, jsondata);
                    pStmt.addBatch();
                }
                Instant startExecute = Instant.now();

                pStmt.executeBatch();
                connection.commit();

                Instant finish = Instant.now();
                long timeElapsed = Duration.between(start, finish).toMillis();
                double timeElapsedExecute = Duration.between(startExecute, finish).toMillis();
                try {
                    double timeElapsedExecuteSeconds = timeElapsedExecute / 1000;
                    double objPerSecond = amount / timeElapsedExecuteSeconds;

                    //System.out.println ("Incl random num generation, ms: " + timeElapsed);
                    //System.out.println ("Execution, s: " + timeElapsedExecuteSeconds);
                    System.out.println ("Obj / s: " + objPerSecond);

                } finally { }

                pStmt.clearBatch();
            }

        } finally {
            // Close the database connection.
            connection.close();
        }
    }

}

**Comment by tim-o** [comment]
Hi @Samusername ,

A certain number of retry errors are expected and should be handled in the application code. It looks like you're following the best practices identified [here](https://forum.cockroachlabs.com/t/java-program-with-batch-inserts/2440/2?u=tim-o), though you might benefit from setting batch size to a power of two.

How are the nodes provisioned, and how many retries are you seeing? Is it happening once every hundred transactions, thousand, million? Ten million?

**Comment by Samusername** [comment]
Hi!
Ok, good to know about the "retry errors", which are expected and should be handled in the application code.
The problem occurred quite quickly. After few tens of test rounds.
I tested now with v19.1.0. The problem occurred after a little while with it also. Seem to work longer with the new version. (reWriteBatchedInserts=true)
236 test rounds. One test round == one batch: 4096 rows. --> 
 
| 966 656 rows
 |

And then gave an error:Exception in thread "main" org.postgresql.util.PSQLException: ERROR: restart transaction: TransactionRetryWithProtoRefreshError: TransactionAbortedError(ABORT_REASON_TIMESTAMP_CACHE_REJECTED_POSSIBLE_REPLAY): "sql txn" id=a76f935e key=/Table/54/1/970753/0 rw=true pri=0.06630621 stat=PENDING epo=0 ts=1556898606.165083833,1 orig=1556898606.155287034,0 max=1556898606.225345667,0 wto=false seq=4097
    at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
    at org.postgresql.jdbc.PgConnection.executeTransactionCommand(PgConnection.java:755)
    at org.postgresql.jdbc.PgConnection.commit(PgConnection.java:777)
    at GenerateData.main(GenerateData.java:91)


So, should the application just straightforwardly retry (the same whole batch?) when the error occurs? Are there instructions somewhere on cockroachdb pages how application should handle the situation? (Sorry, I am only starting with cockroachdb.)
batch size has already been power of two: 4096 = 2^12, in GenerateData.java.It would be really nice, if cockroachdb would somehow be able to handle the mentioned problem. But would such be possible by some means?

Thank you for comments!
Best Regards
Sam

    On Friday, May 3, 2019, 6:38:07 PM GMT+3, tim-o <notifications@github.com> wrote:  
 
 
Hi @Samusername ,

A certain number of retry errors are expected and should be handled in the application code. It looks like you're following the best practices identified here, though you might benefit from setting batch size to a power of two.

How are the nodes provisioned, and how many retries are you seeing? Is it happening once every hundred transactions, thousand, million? Ten million?

**Comment by Samusername** [comment]
nodes are started with following commands (if following was asked):

start --cache=0.53 --max-sql-memory=.22 --certs-dir=/certs --join=172.21.0.4,172.21.0.2,172.21.0.3 --listen-addr=172.21.0.4
Listen addr is of course node dependent.

I use docker-compose to start the cockroachdb nodes up: 3 nodes. 
Those are shown in original description in the ticket.

**Comment by Samusername** [comment]
I may have allowed too much memory usage for each node. I am running all three nodes on same laptop. So, those share the same memory. There was way too much memory allowed for each roachX node. Testing again with smaller amounts of memmory allocated for each process.

**Comment by Samusername** [comment]
The smaller memory limits have been defined and taken in use.

The problem / error occurred:

Exception.[Ljava.lang.StackTraceElement;@343f4d3d
Exception. Try again. Sleep first.0, mesg: ERROR: restart transaction: TransactionRetryWithProtoRefreshError: TransactionAbortedError(ABORT_REASON_TIMESTAMP_CACHE_REJECTED_POSSIBLE_REPLAY): "sql txn" id=6c5821db key=/Table/54/1/10448897/0 rw=true pri=0.00499054 stat=PENDING epo=0 ts=1557142331.059089130,1 orig=1557142331.019667428,0 max=1557142331.122216007,0 wto=false seq=4097
Try again. reverted ctr: 10448896

Retry was added and it seems to be able to insert the same batch again. 
Retry seems to work, all of the data ends up in DB ok, and application seems to be able to continue.

**Comment by Samusername** [comment]
Following error occurred now:
Obj / s: 6253.435114503816
Obj / s: 9122.49443207127
Obj / s: 6595.813204508857
Exception.[Ljava.lang.StackTraceElement;@53b32d7
Exception. Try again. Sleep first.0, mesg: ERROR: restart transaction: TransactionRetryWithProtoRefreshError: 
TransactionRetryError: 
retry txn (RETRY_ASYNC_WRITE_FAILURE): "sql txn" id=5b2aa068 key=/Table/54/1/26120193/0 rw=true pri=0.02977471 stat=PENDING epo=0 ts=1557144367.066919868,1 orig=1557144366.862997180,0 max=1557144367.362997180,0 wto=false seq=4096
Try again. reverted ctr: 26120192
Obj / s: 253.8895431723796
Obj / s: 9372.997711670481
Obj / s: 9869.87951807229

At row / id number:
26 120 192

Previous error occurred at id:
10 448 896

**Comment by Samusername** [comment]
After 26 million rows, there have not been errors.
Now there is: 61 566 976 rows in db.
I will re-execute tests again, later, from empty DB.

**Comment by tim-o** [comment]
Ok, glad to hear you were able to proceed. Let us know the results.

**Comment by tim-o** [comment]
Zendesk ticket #[3291](https://cockroachdb.zendesk.com/agent/tickets/3291) has been linked to this issue.

**Comment by Samusername** [comment]
On laptop

On laptop, once more. laptop was restarted.
Memory setting should be ok now again:
--cache=.15, --max-sql-memory=.12. 
Three roachX nodes. 16 GB RAM on laptop.
Failed once: ABORT_REASON_TIMESTAMP_CACHE_REJECTED_POSSIBLE_REPLAY. After ids: 48 million.
On same laptop, while inserting: also document was being edited in a browser. 
(Some swapping of browser usage? But did it affect CockroachDB, I do not know.)

In a "lab"

The error did not happen yet, during first test execution.
Each roachX node was running on separate Pod. Each Pod was running on separate server.
80 million rows was inserted.

**Comment by Samusername** [comment]
With "retry functionality",
There seems to happen also following error some times:
ERROR: duplicate key value
Background, testing: I delete a container at a time, and sleep, in a sequence. Insert at the same time.

Upsert seems to help.

Does someone know how much upsert affects on the performance? 
Batch inserts vs batch upserts.
How big performance penalty is there?
Side note, maybe a "combination" could be possible also on application side.

**Comment by tim-o** [comment]
@Samusername sorry for the delay here. Generally upsert is faster than insert, because we don't have to read before we write. 

The cost of insert vs. upsert is going to vary a lot depending on the schema, cluster topology, network latency, and other considerations. As far as a combination, you could also try `INSERT ON CONFLICT DO UPDATE`. The only difference between the two is that in cases when some columns that have default values are omitted from the insert/upsert statement, UPSERT will be faster.

Do you still need help here?

**Comment by Samusername** [comment]
When I tested, batch insert was five times faster than batch upsert. 
( Like originally:
On my laptop, with SSD. 3 cockroachdb nodes. 
DB connection URL: jdbc:postgresql://[ip]:[port]/[db]?reWriteBatchedInserts=true.
jsonb column, id column is bigint )

Should there be done some other steps in upserts? I only replaced "insert" with "upsert", and tested again. Of course table was truncated in between.

**Comment by ricardocrdb** [comment]
Hello @Samusername 

Apologies for the delay in response. We discuss the different considerations when using an `UPSERT` at our documentation page [here](https://www.cockroachlabs.com/docs/v19.1/upsert.html#considerations). The first thing I would ask is whether you are running a multi-row upsert or a single-row upset, as the multi-row is generally going to be faster. Please take a look and let me know if there are any other questions.

Cheers,
Ricardo

**Comment by Samusername** [comment]
Hi!

We do batch inserts in java. We do batch upserts in the same way. (In GenerateData.java.)

Are such batch operations multi row operations?

**Comment by ricardocrdb** [comment]
Hello @Samusername 

The batch inserts and upserts you mention could still be configured as single-row vs multiple-row. If multiple values are being passed into the `UPSERT`, then multiple rows are being modified in one command, and so that would be a multi-row mutation. Otherwise, the batches are still running and modifying 1 row at a time. Please review whether this is the case, and let me know what you find.

Cheers,
Ricardo

**Comment by ricardocrdb** [comment]
Hey @Samusername 

Did you have any other questions on this issue?

**Comment by Samusername** [comment]
No questions anymore. I may further investigate the performance of upserts topic later. 
Let's close this ticket.

Thank you!

**Comment by ricardocrdb** [comment]
Thanks for the update @Samusername, I will go ahead and close this issue.
