### ISSUE TITLE
exec: add memory monitoring

### ISSUE THREAD

**Issue by asubiotto** [cockroachdb/cockroach#37301]
Our current memory monitoring system has its shortcomings:
- It tries to be too exact. Due to limitations of go, there is no way we can exactly account for memory used from the OS perspective.
- Memory lifecycle is hard to manage and enforced too strictly. Forgetting to Close an account or double Closing would previously lead to server panics.

The easiest way to satisfy the need of memory accounting in vectorized execution is to use the existing memory accounting system by passing an allocator object to operators and accounting when returning batches (to avoid operators having to worry about memory accounting), but we would not get rid of any of the existing accounting problems. Another option for memory accounting could be to estimate the memory usage of operators and enforce that as a hard limit.

Each component (operator or hashRouter) would have a constant memory cost assigned to them. In the case of components that buffer (e.g. hash joiner, sorter), a 4MB block of memory will be added to the cost for each buffer (this could be tunable, similar to our work memory which is currently 64MB, or postgres’ 4MB). When planning a query, the memory cost would subtracted from the general (shared by all queries) account and an allocator is created with this cost. If the general account denies this memory reservation, we error out before running the query. The allocator will increment a “used” atomic counter local to it and deny an allocation if it would exceed the pre-reserved memory.

Advantages:
- Simple to implement and iterate on later with possible optimizer memory cost estimation to improve overestimation (note that estimation is a max, so we will never underestimate, but what happens if the optimizer underestimates?).
- The garbage problem is alleviated given that we provide a memory estimation for the query as a whole.
- Memory lifecycle is easy. You have one entry point where memory is reserved, and one exit point when the query finishes.

Disadvantages:
- We might easily overestimate and deny running queries when in fact we would be able to run them. However, the user would be able to tune the work memory for buffers.
- The garbage problem still exists, albeit at a coarser granularity than before (we will not account for garbage generated by a finished query). Unclear how big a problem this is.

Validation:
- We need to make sure that existing workloads do not fail this model.

Extra details
---
- The variable to configure the work memory of buffering operators could be set by session for different workloads.
- Accounting for batches of fixed-size datatypes is relatively easily, but variable length datatypes pose a small problem. For example, calculating the space taken by a slice of byte slices entails a linear iteration to aggregate the size of each slice. This will probably have to be the solution for now, with the allocator shouldering the responsibility of doing this, while we move to Arrow batches, that organize variable length data in a flat slice with offsets.
- From an operator perspective, the underlying accounting method does not matter. We could start by building out an allocator pattern with the current accounting system and iterate on that.

**Comment by yuzefovich** [comment]
I think this can now be closed, right @asubiotto?
