### ISSUE TITLE
exec: implement ordered synchronizer

### ISSUE THREAD

**Issue by asubiotto** [cockroachdb/cockroach#37304]
We need to build a component that has various operators as their input and performs an ordered merge on this input, exposing the result through an `exec.Operator` interface. This is needed in order to maintain an ordering on multiple ordered streams (e.g. as the input to an ordered aggregator.

This component is a requirement for planning distributed flows (at least ones where stream ordering is necessary).

**Comment by solongordon** [comment]
Closing this since we have a working implementation now, though there are still opportunities for optimization.
