### ISSUE TITLE
opt: Automatically add filters based on check constraints

### ISSUE THREAD

**Issue by andy-kimball** [cockroachdb/cockroach#37312]
### Suggestion
@lucy-zhang has confirmed that we can rely on the check constraint's `Validity` field to guarantee that the check constraint is enforced on every row. This means the optimizer can add additional filters to queries based on those check constraints. This can have dramatic impact on performance and make geo-distributed queries easier (and more natural/intuitive) to write.

### Use case
For example, consider the following table, which contains orders partitioned across multiple geographical regions:
```
CREATE TABLE "orders" (
  region STRING NOT NULL,
  id UUID DEFAULT gen_random_uuid() NOT NULL,
  total DECIMAL NOT NULL,
  created_at TIMESTAMP NOT NULL,
  PRIMARY KEY (region, id),
  UNIQUE INDEX orders_by_created_at (region, created_at, id) STORING (total),
  CHECK (region IN ('us-east1', 'us-west1', 'europe-west2'))
)
PARTITION BY LIST (region) (
  PARTITION us_east1 VALUES IN ('us-east1'),
  PARTITION us_west1 VALUES IN ('us-west1'),
  PARTITION europe_west2 VALUES IN ('europe-west2')
)
```
Say the business wishes to total up sales for a given day. The intuitive, but naive way to write the query would be like this:
```
EXPLAIN (OPT) SELECT sum(total) FROM "orders" WHERE created_at >= '2019-05-04' AND created_at < '2019-05-05';
                                                    text
+-----------------------------------------------------------------------------------------------------------+
  scalar-group-by
   ├── select
   │    ├── scan orders
   │    └── filters
   │         └── (created_at >= '2019-05-04 00:00:00+00:00') AND (created_at < '2019-05-05 00:00:00+00:00')
   └── aggregations
        └── sum
             └── variable: total
```
Notice that this requires a table scan, and so will be prohibitively expensive. However, if the possible `region` values are added as a filter to the query, the situation dramatically improves:
```
EXPLAIN (OPT) SELECT sum(total) FROM "orders" WHERE created_at >= '2019-05-04' AND created_at < '2019-05-05' AND region IN ('us-east1', 'us-west1', 'europe-west2');
                                                                                                                                                           text
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
  scalar-group-by
   ├── scan orders@orders_by_created_at
   │    └── constraint: /1/4/2: [/'europe-west2'/'2019-05-04 00:00:00+00:00' - /'europe-west2'/'2019-05-04 23:59:59.999999+00:00'] [/'us-east1'/'2019-05-04 00:00:00+00:00' - /'us-east1'/'2019-05-04 23:59:59.999999+00:00'] [/'us-west1'/'2019-05-04 00:00:00+00:00' - /'us-west1'/'2019-05-04 23:59:59.999999+00:00']
   └── aggregations
        └── sum
             └── variable: total
```
This query will use the `orders_by_created_at` index to only touch ranges and rows within those ranges that contain relevant data.

While it's possible for users to add the `region IN` predicate to their queries, it takes extra work and is easy to forget (or be ignorant of). It's also possible for users to create a view that adds the predicate, and then to always express queries over that view. But again, this is more work to create and maintain, and doesn't "make data easy".

Instead, we could upgrade the optimizer to notice check constraints that restrict a column to a (smallish) set of enumerated values. It could then automatically add a filter to queries over that table.

### Notes
1. There is some question of whether it's always OK to add the extra filter(s). It may slow down the query in some cases. We should spend time thinking about how to minimize that possibility. For example, we could notice cases where the check column is already constrained and not add additional filter(s) in that case.
2. It's important to think through impacts of NULL values. Check constraints succeed when they evaluate to NULL. Most likely, we'd want to restrict this optimization to NOT NULL columns.
3. Another idea is to add a bit of syntax to `PARTITION BY LIST` to instruct the SQL analyzer to automatically add a check constraint to the table that restricts the partition column to only values enumerated in the `VALUES IN` lists. Maybe something like the existing `DEFAULT` partitioning clause, except that rather than putting unenumerated values in a separate partition, the runtime would raise a check constraint error.

**Comment by RaduBerinde** [comment]
Even without a check constraint, we can rely on histogram info to know when there are only a few frequent values and use an "index skip scan". What this does is that for each known value, it only scans the specific subregion. It also scans in-between the values in case there are newer values not in the histogram. In this example, the spans would be:

```
[ - /'europe-west2')
[/'europe-west2'/'2019-05-04 00:00:00+00:00' - /'europe-west2'/'2019-05-04 23:59:59.999999+00:00']
[/'europe-west2\x00' - /'us-east1')
[/'us-east1'/'2019-05-04 00:00:00+00:00' - /'us-east1'/'2019-05-04 23:59:59.999999+00:00']
[/'us-east1\x00' - /'us-west1')
[/'us-west1'/'2019-05-04 00:00:00+00:00' - /'us-west1'/'2019-05-04 23:59:59.999999+00:00']
[/'us-west1\x00' - ]
```
The "in-between" spans guarantee correctness but they should contain no rows.

This can also be used with a subset of values (the most frequent ones), in which case the in-between spans do return rows.

CCing @danhhz (we once talked about something along these lines).

**Comment by danhhz** [comment]
The CHECK constraint idea is cool is we have one but if we can make things work automatically that seems like the better way to go. I'd lean toward radu's suggestion, possibly starting with the values listed in the partitioning and letting the histogram add in anything being caught by DEFAULT. Then if we also added the CHECK stuff, savvy users could use it to guarantee the good behavior.

Also note that the CHECK only works if you can exhaustively list all your values and my guess is that users will want to use DEFAULT. For example, if a user wanted to make it easy to add new datacenters, they could use a more granular partitioning column than "region". This lets them change the mapping of values to partitions without rewriting row data. We could check with SE to see if my instinct is correct.

**Comment by danhhz** [comment]
Also want to mention that I'm _really excited_ to see this get solved somehow. We've been anxious about this from day 1 of partitioning: https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20170921_sql_partitioning.md#query-planning-changes

**Comment by andy-kimball** [comment]
I think we shouldn't pick one or the other, but do both. The skip index idea is more general, but the constraint idea is more optimal (and doesn't require histogram support, which we don't yet have).

**Comment by bdarnell** [comment]
I have another use case for this that doesn't involve partitioning: breaking up hotspots for time-ordered indexes. Inserts to this table would have a bottleneck on the timestamp index for the range containing the current time:

```
create table t1 (
    id uuid primary key,
    created timestamp,
    index i1 (created),
)
```

This hotspot can be alleviated by sharding the index:
 
```
create table t2 (
    id uuid primary key,
    created timestamp,
    shard int, -- random value in range [0, 4) chosen at insertion time
    index i2 (shard, created),
)
```

However, this intrudes into queries. You need to say something like `select * from t2 where shard in (0, 1, 2, 3) order by created desc` (and all clients need to know the number of shards). It would be great if the planner could pick up on an appropriate CHECK constraint to do this automatically.

**Comment by andy-kimball** [comment]
Sharding for load distribution is another interesting use case. I don't think the CHECK constraint part of this would be too difficult, so we'll look for an opportunity to fit it in.

**Comment by andy-kimball** [comment]
It occurs to me that there's another interesting thing we could do. When `PARTITION BY LIST (col)` is used, the partition values are enumerated  as part of `PARTITION ... VALUES IN` clauses. We could use those to build the index skip scan that @RaduBerinde describes above. That way, even if the user does not define a check constraint, they'd still get much of the benefit. And we wouldn't need histograms to make it work (i.e. could be done today).

**Comment by RaduBerinde** [comment]
Yet another possibility suggested by @justinj: we could first discover the values in the first column by scanning one row at a time. In the example above, we would scan the first row and get `/'europe-west2'/..`. Then we would scan the first row in the span `[/'europe-west2\x00' - ]`, and so on. This is slower than the other methods but requires no information. This sounds like what Oracle documents for their [Index Skip Scan](https://oracle-base.com/articles/9i/index-skip-scanning#HowItWorks):
> Rather than restricting the search path using a predicate from the statement, Skip Scans are initiated by probing the index for distinct values of the prefix column. Each of these distinct values is then used as a starting point for a regular index search. The result is several separate searches of a single index that, when combined, eliminate the affect of the prefix column. Essentially, the index has been searched from the second level down.

**Comment by RaduBerinde** [comment]
@danhhz good call, filed #38744.
