### ISSUE TITLE
changefeedccl: expose retryable errors in jobs table

### ISSUE THREAD

**Issue by rolandcrosby** [cockroachdb/cockroach#37330]
We currently log retryable errors when communicating with sinks, but don't expose them in the web UI or the SQL interface. Need to figure out a good way to surface these sorts of errors.

Epic CRDB-2365

Jira issue: CRDB-4435

**Comment by mwang1026** [comment]
This could be any error, but the "silent retryable" ones are certainly where this would have the most value.

**Comment by amruss** [comment]
Maybe we can scope this issue down to: surface last retrying error in SHOW JOBS and jobs page

**Comment by miretskiy** [comment]
I believe this was done with my change to surface statuses? @amruss: if you agree, feel free to close. or correct me if i'm wrong.
