### ISSUE TITLE
split failed while applying backpressure: could not find valid split key

### ISSUE THREAD

**Issue by malexdev** [cockroachdb/cockroach#37337]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

I try to do any changes to schema in the table (including truncating tables) and receive the error:

```
split failed while applying backpressure: could not find valid split key
```

Running workarounds mentioned in other issues (namely, `ALTER RANGE default CONFIGURE ZONE USING gc.ttlseconds = 10` and `SET CLUSTER SETTING kv.range.backpressure_range_size_multiplier=0`) also fail with the same error (which is why I'm creating this as a new issue: I don't see the other issues mentioning this scenario).

**To Reproduce**

My company is trying to migrate an application to Cockroach, and it's currently the only application using the cluster.

Cockroach was running slowly when I came in today, so I performed a rolling restart of the clusters, which typically solves the slowness issue.

After doing this, I am now getting this error, although I can't say for certain if this was an issue before the restart.

I do not know of any specific instance of us "writing to the same row a lot", although I was making a fair number of schema changes and reloading the database as part of this pending migration so potentially. Although certainly not thousands.

If possible, provide steps to reproduce the behavior:

Unknown, as I do not have a scenario for what caused the error nor can I tell from the message what the problem area is.

**Expected behavior**

Ultimately, the ability to recover from this error or at least even see what the issue is.

**Additional data / screenshots**
None.

**Environment:**
 - CockroachDB version: 19.1
 - Server OS: Linux/CentOS 6
 - Client app: Go pq driver

**Additional context**
What was the impact?

Not a large impact as of yet since this doesn't affect the database usage, just schema changes.
But, it would make deploying application updates that require schema changes grind to a halt, which could be a rather large impact in the future.

**Comment by malexdev** [comment]
This issue has now resolved itself.  However, I would love to hear of any way I can resolve it quicker in the future :)

**Comment by andreimatei** [comment]
I think it's weird that `SET CLUSTER SETTING kv.range.backpressure_range_size_multiplier=0` didn't do anything. @nvanbenschoten ?

**Comment by roncrdb** [comment]
Hi @malexdev 

We've created a single master issue for this bug, I've linked it to this issue, but will be closing this particular issue out. 

Thanks!
