### ISSUE TITLE
roachtest: use strings instead of git tag to determine cockroach version

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#37359]
roachtest uses git to get the version of the cockroach binary right now:

https://github.com/cockroachdb/cockroach/blob/6bc48759ca307674fcc3b2b73b66560a7fd27a90/pkg/cmd/roachtest/test.go#L258-L273

This isn't a great idea, because in manual roachtest runs we're not guaranteed to be on the right branch belonging to the binary (I just wasted some time on this).

The version should be taken from the cockroach binary. How to do this was discussed over in https://github.com/cockroachdb/cockroach/pull/37354#issuecomment-490096745. The main problem that needs to be solved is that the binary may not be native (i.e. it could be a linux binary, but roachtest runs on darwin).

**Comment by knz** [comment]
Beware you can't use `strings` on the binary without some precaution. The fact that it seems to work in the linked comment from #37354 is an accident and was made possible by the unplanned/uncontrollable presence of a nul byte (part of a word containing zero, I presume) before the first character.

If the string was immediately following something that was ASCII-like, the output of `strings` would have been mangled.

The good solution requires enclosing the version string in delimiters.

**Comment by tbg** [comment]
Right, I linked to your comment which has all of the details.
