### ISSUE TITLE
cli: tab complete in cockroach CLI

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#37355]
I'd like to be able to tab complete in the CLI terminal so that I can save time as I'm working with my database. 

Postgres offers tab completion.

```
root@cockroachdb-public:26257/defaultdb> use reg
tab completion not supported; append '??' and press tab for contextual help

use registration;
SET

Time: 464.478µs
```
Epic: CRDB-12860

Jira issue: CRDB-6345

**Comment by kenliu** [comment]
@rohany did you ever merge your code for this?

**Comment by rohany** [comment]
No, we'll attempt to iterate on it in 20.2 (pr reference: #45186)
