### ISSUE TITLE
exec: nulls are set incorrectly for decimal in secondary index

### ISSUE THREAD

**Issue by solongordon** [cockroachdb/cockroach#37358]
I ran across this while implementing null handling for selections.
```
root@127.0.0.1:64223/defaultdb> create table t (x decimal);                                                           CREATE TABLE

Time: 2.658ms

root@127.0.0.1:64223/defaultdb> create index idx on t (x);                                                            CREATE INDEX

Time: 85.357ms

root@127.0.0.1:64223/defaultdb> insert into t values (1);                                                             INSERT 1

Time: 2.467ms

root@127.0.0.1:64223/defaultdb> set experimental_vectorize=on;                                                        SET

Time: 251µs

root@127.0.0.1:64223/defaultdb> select * from t@idx;
   x
+------+
  NULL
(1 row)
```
Does not happen when `x` is an INT or when selecting from the primary index.

**Comment by solongordon** [comment]
cc @jordanlewis in case you have an idea off the top of your head why this might be broken. Seems like an issue at the `cfetcher` level.

**Comment by jordanlewis** [comment]
Hmm... yeah I don't know for sure what's going on here. Perhaps it has to do with the fact that decimals have composite encodings, and live both in the key and the value of their row.

**Comment by solongordon** [comment]
Yeah, it seems related to exactly what you said. This is the relevant block: https://github.com/cockroachdb/cockroach/blob/90ba0620a49426af475d8dc2209f4182ba69d322/pkg/sql/row/cfetcher.go#L316-L323 When the column is composite it doesn't get removed from `neededValueColsByIdx` and then the value is ultimately filled with a null. Still need to figure out what the correct behavior is here. `fetcher.go` doesn't have this conditional: https://github.com/cockroachdb/cockroach/blob/90ba0620a49426af475d8dc2209f4182ba69d322/pkg/sql/row/fetcher.go#L353-L356

**Comment by jordanlewis** [comment]
Hmm.. I think there must be some subtlety with secondary indexes specifically, because as you point out, things seem to work okay with primaries.

**Comment by solongordon** [comment]
I removed the `if !compositeColumnIDs.Contains(int(id))` conditional and it doesn't seem like it broke any tests. 🤔 Do you remember why that logic was needed in `cfetcher` but not `fetcher`?

**Comment by jordanlewis** [comment]
I added several extra optimizations to `cfetcher` to try to make sure that only the minimal amount of work is done during decoding. `fetcher` does some amount of extra decoding because the bookkeeping is somewhat challenging.

While I don't fully remember (what's that quote about how your code isn't your code anymore after 6 months?), conceptually this makes sense - if a key column id isn't composite, then it doesn't belong in the set of columns to search for in the value.

**Comment by jordanlewis** [comment]
That being said, I regret not adding tests for that behavior 🙈

**Comment by solongordon** [comment]
Oh I should have been more clear—the change I made was to unconditionally remove the column from `neededValueColsByIdx` like `fetcher` does.
```
diff --git a/pkg/sql/row/cfetcher.go b/pkg/sql/row/cfetcher.go
index fff960685f..f678631b19 100644
--- a/pkg/sql/row/cfetcher.go
+++ b/pkg/sql/row/cfetcher.go
@@ -315,11 +315,7 @@ func (rf *CFetcher) Init(
       table.indexColOrdinals[i] = colIdx
       if neededCols.Contains(int(id)) {
         neededIndexCols++
-        if !compositeColumnIDs.Contains(int(id)) {
-          // A composite column lives both in the index and in the value; if
-          // its needed, it must also be decoded from the value.
-          table.neededValueColsByIdx.Remove(colIdx)
-        }
+        table.neededValueColsByIdx.Remove(colIdx)
       }
     } else {
       table.indexColOrdinals[i] = -1
```
That fixed this issue and didn't seem to break any tests. I'm trying to figure out if it broke something which isn't covered by our exec tests.

**Comment by jordanlewis** [comment]
Oh, huh. I guess I don't understand that. That diff seems like it would do the opposite of fix the issue? The way I read that, it's saying that if you need column `x` from the index columns, you never need column `x` from the value columns. Clearly the variable naming here doesn't reveal the entire problem...

Before we process the value component, we copy the `neededValueColsByIdx` into `remainingValueColsByIdx`, which is the set that contains all the value columns that has been decoded from the current row. That set is used to decide which value columns to decode, and which to skip. Also, at the end of processing a row, the columns left in that set get overwritten by NULL. What I don't understand is how your patch could work, given that it seems like the patch would instruct the fecther *not* to decode the value component of the decimal.

Reading further, it looks like `processValueBytes` actually uses `table.neededColsList` to determine what to decode, not `neededValueColsByIdx` or the `remaining` equivalent. Hmm...

**Comment by jordanlewis** [comment]
Anyway I'm okay with that patch, but if you see a way to clear up those 3 different "needed" sets I'd be all ears.

**Comment by solongordon** [comment]
Never mind, I thought I tested this before but turns out my patch breaks `processValueBytes` for secondary indexes. (`1.000` ends up getting rendered as `1`.) Needs further surgery.

**Comment by solongordon** [comment]
Oh, I think this is only broken when the value component of the composite key is empty. It works if you insert `'1.000'` into a decimal column but not `1`. This is because `processValueBytes` never gets called if the value is empty, so the column is never removed from `remainingValueColsByIdx`. I'll investigate how to properly update `remainingValueColsByIdx` in this case.

**Comment by jordanlewis** [comment]
Oh, nice! That makes perfect sense. I was unaware when writing that code that composite columns weren't *always* stored in both the key and the value, and that doesn't seem to be written about in `encoding.md` as far as I can see. Is this expected, I wonder?

**Comment by jordanlewis** [comment]
Oh cool - datums are actually marked as composite conditionally! the `IsComposite` contract is on datums, not on types.
