### ISSUE TITLE
sql: join reorder telemetry suspicious results

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#37364]
I'm attempting to understand how our join reorder telemetry works. I ran this query to look at it:
```
SELECT
    cluster, sum(uses), version, feature
FROM
    features
WHERE
    feature LIKE 'sql.plan.reorder-joins.set-limit-%'
    AND uptime >= 604800
    AND internal = false
GROUP BY
    cluster, version, feature;                                                                                                             
```
It returns these results:
```
                cluster                |  sum   |   version    |              feature
+--------------------------------------+--------+--------------+------------------------------------+
XXX |  37300 | v19.1.0-rc.1 | sql.plan.reorder-joins.set-limit-4
  YYY | 943800 | v19.1.0-rc.1 | sql.plan.reorder-joins.set-limit-4
  ZZZ |  55300 | v19.1.0-rc.1 | sql.plan.reorder-joins.set-limit-4
(3 rows)

Time: 13.14685251s
```

These sums seem quite high and suspicious.

Do we think this is caused by the session variable being set on session creation?

**Comment by RaduBerinde** [comment]
I looked through the code to see if we might inadvertently trigger the counter with the default value, but couldn't find any problem. It's very strange.

**Comment by justinj** [comment]
Now that the release has been out for a while, are there any additional clusters displaying this behaviour or still just the same ones as before?

**Comment by awoods187** [comment]
I see this in may telemetry data as well

**Comment by justinj** [comment]
@awoods187 how many clusters, and what proportion of clusters are displaying this behaviour?

**Comment by justinj** [comment]
Based on a discussion offline it seems that in May this was localized to only two clusters running 19.1 RC1 (it was three clusters running 19.1 RC1 in April). Seems fairly conclusive to me that this is a case of an individual doing something funky. I think we should close this issue.
