### ISSUE TITLE
roachprod: monitor `--oneshot` usually loops infinitely

### ISSUE THREAD

**Issue by ajkr** [cockroachdb/cockroach#37389]
**Describe the problem**

`cluster.FailOnDeadNodes` uses the `--oneshot` option with a one minute timeout. I manually tried the command it's using and the majority of times it gets stuck in an infinite loop printing the same node status over and over. The remaining times it prints each node's status once and then returns almost immediately. We should make sure the latter behavior is always the case. Then tests should fail more reliably if nodes are down (currently if it times out the error is ignored).

**Comment by tbg** [comment]
Huh, that's weird. Is this related to https://github.com/cockroachdb/cockroach/issues/37370?

**Comment by ajkr** [comment]
Not sure yet. I'll check whether that fix also solves this problem.

**Comment by ajkr** [comment]
Just checked. It is not fixed. Lots of times I still see output like:

```
$ go run ./pkg/cmd/roachprod monitor local --oneshot
1: 
1: 
1: 
1: 
1: 
1: 
1: 
1: 
1: 
1: 
1: 
1: 
1: 
1: 
1: 
1: 
1: 
1: 
```
