### ISSUE TITLE
rocksdb: investigate compaction under high write rate

### ISSUE THREAD

**Issue by ajkr** [cockroachdb/cockroach#37408]
**Describe the problem**

We have some evidence that RocksDB compaction is behaving suboptimally for large-value kv0 and for the temp-store during large imports. In particular, while investigating #34897 it appeared that slowing down compaction improved overall throughput. We should investigate more why this is. Perhaps we're incurring more compaction debt when compaction is slowed, in which case it's expected (less I/O spent on compactions means more is available for user operations), or perhaps we're making worse compaction choices when compaction rate is high. From looking at the logs, it appears to be the latter.

**Comment by petermattis** [comment]
IMPORT no longer uses the temp-store. I'm not aware of any suboptimal behavior with large-value kv0 workloads on RocksDB (though we are investigating perf issues with large value kv0 workloads on Pebble). I'm going to close this issue as stale and not actionable.
