### ISSUE TITLE
sql: provide metrics for bytes and rows read on all successful queries

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#37409]
To provide a metric for evaluating the overall goodput of the system, it's desirable to track the total number of bytes and rows read from disk across all successful queries.

Distsql already provides the number of rows read when EXPLAIN ANALYZE tracing is on. The ask here is twofold:

1. also track bytes read, by teaching the kvfetcher to keep track of that information
2. track this information unconditionally, regardless of whether tracing is on or off

Care must be taken to ensure that adding this information unconditionally doesn't meaningfully affect throughput.

See #37264 for a related effort.

cc @ajwerner to provide additional context if necessary.

**Comment by jordanlewis** [comment]
We should probably add something about these metrics to the statements page.

**Comment by yuzefovich** [comment]
Closing this issue since the ask has been addressed by #38002 and the follow-up work will be tracked by #38297.
