### ISSUE TITLE
test failures on Linux on IBM Z(s390x) system

### ISSUE THREAD

**Issue by salamani** [cockroachdb/cockroach#37423]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:
Working on s390x , built from source as documented here https://www.cockroachlabs.com/docs/stable/install-cockroachdb-linux.html#build-from-source
Observed some failures. Need help in fixing them.

**To Reproduce**

What did you do? Describe in your own words.
If possible, provide steps to reproduce the behavior:

1. Download source code on s390x system and extract it
2. Cleanup slice.s file (to fix go compilation error: slice.s:1: Error: junk at end of line, first unrecognized character is `/’)
3. Run `make build`
4. Run `make test`

following failures are observed:
1. testcases failed because of small difference in float value. Also discussed at [group_link](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/cockroach-db/6YS38tt2-0U/rLuVp639AwAJ)
      `pkg/sql`:TestLogic
      `pkg/sql/opt/xform`:TestExternal

2. One failure in `pkg/Server`: TestReportUsage.  Ignored this test as per discussion at [group_link](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/cockroach-db/NNVvOUrMBik)
3. One failure in `pkg/ts`:TestTimeSeriesRollupModelTest
```
$`make test PKG=./pkg/ts TESTS='TestTimeSeriesRollupModelTest$$' TESTFLAGS="-v -show-logs"`
Running make with -j4
GOPATH set to /home/test
GOFLAGS= go test  -tags ' gss make s390x_linux_gnu' -ldflags '-X github.com/cockroachdb/cockroach/pkg/build.typ=development -extldflags "" -X "github.com/cockroachdb/cockroach/pkg/build.tag=v19.1.0-dirty" -X "github.com/cockroachdb/cockroach/pkg/build.rev=25dd36f0139bf65b80758deeeccf35ee17ebd622" -X "github.com/cockroachdb/cockroach/pkg/build.cgoTargetTriple=s390x-linux-gnu"  ' -run "TestTimeSeriesRollupModelTest$"  -timeout 12m ./pkg/ts -v -show-logs
=== RUN   TestTimeSeriesRollupModelTest
I190508 14:57:36.574384 21 gossip/gossip.go:392  [n1] NodeDescriptor set to node_id:1 address:<network_field:"tcp" address_field:"invalid.invalid:26257" > attrs:<> locality:<> ServerVersion:<major_val:0 minor_val:0 patch:0 unstable:0 > build_tag:"" started_at:0
W190508 14:57:36.574913 114 storage/store.go:1525  [n1,s1,r6/1:/Table/{SystemConâ¦-11}] could not gossip system config: [NotLeaseHolderError] r6: replica (n1,s1):1 not lease holder; lease holder unknown
--- FAIL: TestTimeSeriesRollupModelTest (2.44s)
    model_test.go:249: ["\x04tsd\x12metric1\x00\x01\x8a\xf7D{source3"].RawBytes[80]: 148 != 149
    model_test.go:249: ["\x04tsd\x12metric2\x00\x01\x8a\xf7D{source3"].RawBytes[80]: 161 != 162
    model_test.go:249: ["\x04tsd\x12metric1\x00\x01\x8a\xf7D{source2"].RawBytes[80]: 204 != 202
    model_test.go:249: ["\x04tsd\x12metric2\x00\x01\x8a\xf7D{source2"].RawBytes[80]: 221 != 224
    model_test.go:249: ["\x04tsd\x12metric1\x00\x01\x8a\xf7D{source1"].RawBytes[80]: 67 != 66
    model_test.go:249: ["\x04tsd\x12metric1\x00\x01\x8a\xf7D{source4"].RawBytes[80]: 38 != 37
    model_test.go:249: ["\x04tsd\x12metric2\x00\x01\x8a\xf7D{source4"].RawBytes[80]: 124 != 126
FAIL
FAIL    github.com/cockroachdb/cockroach/pkg/ts 2.497s
Makefile:893: recipe for target 'test' failed
make: *** [test] Error 1
```
What is the severity of this testcase?  
      
**Expected behavior**
pass all testcases

**Environment:**
 - CockroachDB version [v19.1.0]
 - Server OS: [e.g. Linux/s390x, Ubuntu 18.04 LTS]

Jira issue: CRDB-4432

**Comment by knz** [comment]
The data errors are possibly related to your platform using a different format for 64-bit floating point. Is this arch not doing IEEE764? If not, is there a compiler flag you could add to force that format?

**Comment by e-desouza** [comment]
IBM Z does support IEEE764 issue (as it does support that) so this is really an endianness issue. s390x is big endian not little endian and it looks like those tests assume little endian.

**Comment by knz** [comment]
>  it looks like those tests assume little endian.

which tests? What's the evidence that enables you to propose that theory?

**Comment by e-desouza** [comment]
Not 100% sure its endianness but they are accessing bytes (`.RawBytes[80]`) and that changes depending on the endianness. It's interesting how the values are just off by one or two in most cases though so it could be something else..I can provide a s390x build machine for inclusion into the CI/CD pipeline if required - pls let me know!

**Comment by knz** [comment]
If the bytes were swapped, we'd observe very different values. In this case, they are off by just 1. This is not the type of mismatch I'd expect with a mere endianness failure.

Your proposal to include a s390x build machine is intriguing. How many parallel tasks does it support? Please understand that we customarily run 30-60 concurrent CI builds during busy development hours. I don't think we can afford to add a CI step that'd be bottlenecked by a single machine.

**Comment by knz** [comment]
(We could also include it on a daily/weekly CI run instead of the one ran on every PR. That might reduce the cost.)

**Comment by knz** [comment]
@e-desouza, we have a suggestion from @dt to run the test suite from the (simpler) package github.com/cockroachdb/pebble on the s390x platform as a first step. Since this is where the most sensitive data patterns are checked, you would already get some signal about compatibility from that simpler test suite.

**Comment by e-desouza** [comment]
> How many parallel tasks does it support? 

A single box can do 8M+ containers. Runs Mongo/PostgreSQL etc with 3x higher throughput per core, can run 20TB+ unsharded Mongo instances while having 20x lower latency (1.2-2ms). Also has 50%+ higher Java perf than amd64. I suspect Cockroach would have 2-3x higher throughput per core too.. s390x servers are already part of kubernetes and other large OSS projects CI and it's not a bottleneck there. Daily/weekly could work too..

> github.com/cockroachdb/pebble

Thanks, will try that one.
