### ISSUE TITLE
ui: Make clearer functional purpose of range in the admin UI range report page 

### ISSUE THREAD

**Issue by joshimhoff** [cockroachdb/cockroach#37445]
**Is your feature request related to a problem? Please describe.**
During a recent outage, managed service team was debugging an issue [1] with range 3. The user visible symptom of the outage was that CREATE DATABASE and CREATE TABLE calls were hanging. It turned out that the keyspace for range 3 included counters for allocating table IDs.

The feature request is to make clearer the functional purpose of a range of keys (especially important system ranges) in the admin UI's range report  page. @mberhault and @bdarnell were debugging with us, and based on the start and end of the key range, they didn't believe anything important was stored in range 3. This meant we couldn't directly link the broken range to the user visible symptom (though we strongly suspected it was the cause). There was no obvious indication in the admin UI that the counters for allocating table IDs were stored there.

If @mberhault and @bdarnell have trouble determining the functional purpose of a system range, so will other operators, such as CRDB SREs and CRDB customers running the DB themselves.

Here is a screenshot of the range report page at the time of the outage:

https://user-images.githubusercontent.com/1839234/56621470-935bb100-65fa-11e9-9bef-62d553d62dad.png

Unfortunately, the end of the key range is cutoff! I don't remember what it said. Maybe @ajwerner does. As can be seen, range 3 started at node liveness max.

**Describe the solution you'd like**
Perhaps start and end of the key range is not enough, since it requires knowing what is in between, which is not always easy. Perhaps documentation can help. Perhaps we should also yell louder about an important system range being an important system range somehow.

Happy to brainstorm with someone! @piyush-singh @ajwerner

**Additional context**
This is a postmortem [2] action item for the managed service team!

[1] https://github.com/cockroachdb/cockroach/issues/37056
[2] https://cockroachlabs.atlassian.net/wiki/spaces/MC/pages/115965953/2019-04-25+woolly-wombat+Wedged

**Comment by bdarnell** [comment]
All the system ranges are important in some way. (We've had some useless system ranges in the past, and I mistakenly thought this was one of them, but I think they're all gone now). Any problem on a system range must be treated as important. I'm not sure that we can explain what all the system ranges are used for in a way that will be useful. 

This range is kind of a miscellaneous bucket. It's necessary for table creation, which was the most visible symptom, but also for splits, which is a much bigger problem long-term. And there's some status keys and other stuff that I'm not even sure how it's used.

One easy thing we could do is name the boundary keys by what comes after them instead of what comes before (`/System/Counters` or `/System/Misc` instead of `/System/NodeLivenessMax`)

**Comment by mberhault** [comment]
I agree that documenting system ranges and what they're for is tricky. However, additional visibility is desired for non-system ranges as well. Rather than seeing `/Table/11 to /Table/12` as the key range for a range, the actual table names would be helpful. This would allow for better understanding of what is impacted when a range has issues.

**Comment by joshimhoff** [comment]
> but also for splits, which is a much bigger problem long-term.

Good to know!

> One easy thing we could do is name the boundary keys by what comes after them instead of what comes before (/System/Counters or /System/Misc instead of /System/NodeLivenessMax)

This sounds like a nice change.

> Rather than seeing /Table/11 to /Table/12 as the key range for a range, the actual table names would be helpful.

So does this! 

I have another question. Let's say we have three "buckets" of key values in one system range. e.g. range three holds the tail end of /System/NodeLiveness, all of /System/Counters, and the beginning /System/Jobs (or however that one is written).

With the current scheme, we would only see start and end keys, right? So we wouldn't know /System/Counters is in between unless you happened to know where it was located in the keyspace? If so, could we list all "buckets" of keys in a range somehow? Would that be useful in practice?

**Comment by bdarnell** [comment]
> With the current scheme, we would only see start and end keys, right? So we wouldn't know /System/Counters is in between unless you happened to know where it was located in the keyspace? If so, could we list all "buckets" of keys in a range somehow? Would that be useful in practice/could the situation hypothesized above happen in practice?

It's not organized into "buckets", there are individual keys that are alphabetized. It's just by accident that the timeseries data happens to be the last thing alphabetically in the system spans; if the keys were chosen differently some of these "counters" could be divided between the range before and after timeseries. 

There are mandatory splits at certain points, so node liveness is always in a range to itself, etc. So there's not too much mixing, except in this range that I'm calling /System/Counters. 

We can always add more documentation about this kind of thing, we just have to consider whether it's worth it. What would you (or any user) do with this knowledge? Where would we put this information so you could find it when you need it without overwhelming you with useless detail when you don't?

**Comment by joshimhoff** [comment]
Got it, thanks for explaining.

> We can always add more documentation about this kind of thing, we just have to consider whether it's worth it. What would you (or any user) do with this knowledge? Where would we put this information so you could find it when you need it without overwhelming you with useless detail when you don't?

I think documentation for SREs and users is different. For SREs, we really want to understand the database at a very deep level. This is obviously gonna take time (LOTS of time), especially since right now our main focus is on automation. I understand there is a lot of stuff to prioritize; maybe the main action item is simply to add some of the info I've learned here to a small SRE playbook on system ranges.
