### ISSUE TITLE
"SHOW SCHEMAS" displays no schemas for custom user

### ISSUE THREAD

**Issue by endeva-tech** [cockroachdb/cockroach#37443]
**The problem**

Empty schema list using SHOW SCHEMAS; command using CRDB CLI.

When I connect to localhost insecure cluster as custom user and I run SHOW SCHEMAS; command, it displays empty list. When I do the same as root user I can see correct list of schemas.

When I connect to CRDB using DBeaver 6.0.4 GUI using custom user Schema list in the left-side pane is empty. I can select from custom tables in database though.

When I do the same as root user I can see schemas (via CLI as well as via DBeaver)

**To Reproduce**

1. Set up CockroachDB localhost cluster and run it insecure:
cockroach start --insecure --listen-addr=localhost

2. Connect to it:
cockroach sql --insecure --host=localhost:26257 --database=custom --user=custom

3. execute command:
custom@localhost:26257/custom> SHOW SCHEMAS;

4. See problem:
schema_name  
+-------------+
(0 rows)

Time: 1.782848ms

**Expected behavior**
Based on the documentation here:
https://www.cockroachlabs.com/docs/stable/show-schemas.html

The command SHOW SCHEMAS; does not need any privileges.
I would expect this command show list of all schemas similarly as for the root user:

schema_name      
+--------------------+
  crdb_internal       
  information_schema  
  pg_catalog          
  public              
(4 rows)

**Environment:**
 - CockroachDB version: CCL v2.1.5 @ 2019/02/11 21:48:27 (go1.10.7)
 - Server OS: Ubuntu 18.04
 - Client app: `cockroach sql`, DBeaver 6.0.4

**Comment by jordanlewis** [comment]
Thanks for the report, this seems to still be broken.

**Comment by jordanlewis** [comment]
I think if anything this is just misreported in the docs. If you give that user any privilege on the database, it'll be able to see the schemas. cc @rmloveland - I think we should at least document this current behavior for now.

**Comment by jordanlewis** [comment]
This works even better now that we have user-defined schemas.

**Comment by rafiss** [comment]
I think this issue relates: https://github.com/cockroachdb/cockroach/issues/49313

In order to complete that issue, we would want to address this one first probably: https://github.com/cockroachdb/cockroach/issues/56020
