### ISSUE TITLE
colserde: TestArrowBatchConverterRandom compares null bitmap to itself

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#37458]
I tried hooking up the RecordBatchSerializer and the ArrowBatchConverter end-to-end and saw batches not roundtrip. It's pretty easy to repro with the following modification to one of the tests, but maybe I'm just misunderstanding something?

```
diff --git a/pkg/sql/exec/colserde/arrowbatchconverter_test.go b/pkg/sql/exec/colserde/arrowbatchconverter_test.go
index 21dad37daf..eb07d3ba82 100644
--- a/pkg/sql/exec/colserde/arrowbatchconverter_test.go
+++ b/pkg/sql/exec/colserde/arrowbatchconverter_test.go
@@ -15,6 +15,7 @@
 package colserde
 
 import (
+	"bytes"
 	"fmt"
 	"testing"
 
@@ -49,10 +50,16 @@ func TestArrowBatchConverterRandom(t *testing.T) {
 
 	b := exec.RandomBatch(rng, typs, rng.Intn(coldata.BatchSize)+1, rng.Float64())
 	c := NewArrowBatchConverter(typs)
+	rd, err := NewRecordBatchSerializer(typs)
+	require.NoError(t, err)
 
+	var buf bytes.Buffer
 	arrowData, err := c.BatchToArrow(b)
 	require.NoError(t, err)
-	result, err := c.ArrowToBatch(arrowData)
+	require.NoError(t, rd.Serialize(&buf, arrowData))
+	var roundtrippedArrow []*array.Data
+	require.NoError(t, rd.Deserialize(&roundtrippedArrow, buf.Bytes()))
+	result, err := c.ArrowToBatch(roundtrippedArrow)
 	require.NoError(t, err)
 	if result.Selection() != nil {
 		t.Fatal("violated invariant that batches have no selection vectors")
```

**Comment by danhhz** [comment]
Seems like it works if I comment out all the null stuff, so maybe it's related to #37428?

**Comment by asubiotto** [comment]
It's failing because `BatchToArrow` modifies `b`'s null bitmap in place to arrow format by inverting bits. We then compare this modified bitmap to `result`'s bitmap, which owns its own bitmap due to `bytes.Buffer` copying the null bitmap bytes. The difference is expected since we're comparing an arrow format null bitmap and our own. However, this brings up the issue that we're not really testing null bitmap conversion in the original test since we're just modifying the null bitmap in place and comparing it to itself.

**Comment by danhhz** [comment]
Ah, fascinating. I started looking into this because I have a flex friday impl of serde for the arrow file format and I was getting out of bounds panics. I wonder what happens if I copy the raw nulls stuff, do the serialization, then reset the nulls from the copy before comparing

**Comment by asubiotto** [comment]
There's an out of bounds panic for the null bitmap that I know of that I fix in https://github.com/cockroachdb/cockroach/pull/37296/commits/0bf2070e86f74836ff3c48d474aafede0caa4cf2. That should work, I'm playing around with that now.

**Comment by asubiotto** [comment]
It works apart from the fact that we don't zero out bits past the number of elements in a ColVec, so these stay as `1`s, which is part of the arrow format. We could modify `Slice`ing to zero bits past the "end" of the slice, but I think we should just wait until our bitmap representation changes (which should be soon).

**Comment by danhhz** [comment]
Okay, cool. I'll clean up and PR my arrow file serde stuff when I get a minute, but it might be friday before that happens. If we haven't gotten to the bitmap representation by then, I'll merge my unit tests as skipped and point them at this issue.

Thanks for looking into this!
