### ISSUE TITLE
cli: custom cert names accepted by cockroach sql --url but not discrete flags

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#37476]
When your `ca.crt` file has a custom name, you can connect via `cockroach sql --url=<url>` but not using discrete connection flags:

```
~/go/src/github.com/jseldess/several-rotations/flask$ cockroach sql --user=app --certs-dir=certs --host=gcp-us-east1.cheeky-chimp.cockroachlabs.cloud
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.
#
W190511 12:20:01.678215 1 security/certificate_loader.go:316  bad filename certs/cheeky-chimp-ca.crt: unknown prefix "cheeky-chimp-ca"
Error: cannot load certificates.
Check your certificate settings, set --certs-dir, or use --insecure for insecure clusters.

problem with CA certificate: not found
Failed running "sql"
~/go/src/github.com/jseldess/several-rotations/flask$ cockroach sql --url 'postgres://app@gcp-us-east1.cheeky-chimp.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full&sslrootcert=certs/cheeky-chimp-ca.crt'
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.
#
Enter password:
# Client version: CockroachDB CCL v19.1.0-beta.20190318-670-g5b83c8f8ac (x86_64-apple-darwin17.7.0, built 2019/04/04 22:12:17, go1.11)
# Server version: CockroachDB CCL v19.1.0 (x86_64-unknown-linux-gnu, built 2019/04/29 18:36:40, go1.11.6)
# Cluster ID: f4900233-f0d4-4bfe-a645-6e6d398f108a
# Organization: Cockroach Cloud production - cheeky-chimp
#
# Enter \? for a brief introduction.
#
app@gcp-us-east1.cheeky-chimp.cockroachlabs.cloud:26257/defaultdb>
```
This should work consistently across connection methods. Custom names is important for MSO because an admin might have multiple clusters and need to differentiate their CAs.

Related (truncated) discussion from Slack:

> Seems like the non-standard crt filename is a problem when not using `--url`…?
>
> Marc Berhault   [7 hours ago]
> yes. The cockroach binary always expects strict filenames for certs. Using `--url` bypasses all that and says "Just give this to libpq"
>
> ...
>
> Jesse Seldess   [14 minutes ago]
> Why don’t we just give them the standard ca.crt filename? Is there a reason to customize it with the cluster name?
>
> Nate Stewart   [14 minutes ago]
> What if you have many clusters?
>
> Nate Stewart   [13 minutes ago]
> Why can’t we make the binary take an arbitrary cert name?
>
> ...

Jira issue: CRDB-4427

**Comment by kannanlakshmi** [comment]
From Marc "We've pretty much gone all in on nomenclature for certificates with the cockroach binary, reversing that would just add confusion. Either we completely decouple `cockroach sql`, or we recommend using the URL. The latter is already the standard way of doing things for other clients."

**Comment by knz** [comment]
It's actually not so clear. Using custom file names with `--url` is only supported for the CLI commands that use SQL under the hood.

The parameter `--url` is supported for all CLI commands, but if you try to use it with a non-SQL command (e.g. `cockroach quit`) it will bark if you specify a non-standard file name.
