### ISSUE TITLE
Rework --addr for all CLI commands that take a sql address.

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#3748]
The CLI commands that talk sql (sql, user, zone) use `--addr` and simply build a `http` or `https` url using `root` and default cert path. All parameters should be configurable and specify the pgwire parameters.

There are a lot of options here:
* full url (eg: `<user>@<host>:<port>?cert=<certpath>`) vs individual flags (eg: `--user`, `--host`, `--port`, etc...)
* custom configuration vs `psql` (flags for host/port/user, env variable for certificate paths, or connection string. eg: `sslmode=require host=localhost dbname=test`) or `mysql` behavior (command-line flags for everything)
* required arguments (eg: full url as the a required arg) vs flags

I personally like urls as they are widely understood and fairly easy to parse. things like `sslmode` and `certpath` can be passed as options. user/host/port/dbname can all go in the url.

**Comment by tamird** [comment]
can we use the standard pg url scheme? see https://github.com/cockroachdb/cockroach/blob/79c15e3581c202f4081fefb8ac5595295fdd5090/sql/main_test.go#L159

**Comment by mberhault** [comment]
that would be my preferred choice. However, my (limited) digging around shows that this only holds for JDBC, other libraries doing just random stuff.

**Comment by tamird** [comment]
Really? I was sure this URL parsing comes down from libpq.

**Comment by bdarnell** [comment]
There's unfortunately not a standard here. JDBC uses `postgresql://`, as does `libpq`, but the go bindings in `github.com/lib/pq` use `postgres://` (looks like ruby does the same).

**Comment by bdarnell** [comment]
But `libpq` is as standard as it gets so we should probably follow that one instead of inventing something new. http://www.postgresql.org/docs/current/static/libpq-connect.html#LIBPQ-CONNSTRING

**Comment by mberhault** [comment]
Ok, sounds like the best we'll be able to do.
I'll do the following URL:
`postgres://<user>@<host>:<port>/<database>?sslmode=<mode>&sslcert=<path>&sslkey=<path>&sshrootcert=<path>`

With the following defaults if not specified:
* user: `root`
* host: `localhost`
* port: `15432`
* database: none
* sslmode: `verify-full` if `--insecure` is false. otherwise, `disable`
* sslcert/key/rootcert paths: `<value of --certs>/certname` if `--insecure` is false. otherwise, leave them out.

**Comment by bdarnell** [comment]
SGTM, but the scheme should probably be `postgresql` instead of `postgres`. `postgresql` is more standard and it turns out that the go `lib/pq` package supports both.

**Comment by mberhault** [comment]
ah. excellent. I was hoping that would be the case.

An alternative to my plan is of course to let users fill in everything. The `--insecure` and `--certs` flags may not make sense for client commands.

**Comment by mberhault** [comment]
Ok, modifying a passed-in url using other flags is really weird. How about the following instead:
you can specify `--url` which is passed unmodified to `sql.Open`.
If `--url` is empty, we use the following flags which all have defaults:
* `--host`: `localhost`
* `--port`: `15432`
* `--user`: `root` (might be better to default to the current user)
* `--insecure`: `false` (determines `sslmode`)
* `--certs`: `certs/` (determines cert paths along with `--insecure` and `--user`)

Both `psql` and `mysql` do the "many flags" option, while programatic interfaces tend to be the connection URL.

**Comment by tamird** [comment]
sgtm. probably should emit some warning if a user passes both url and any of the above
