### ISSUE TITLE
libroach: Synchronize DBSstFileWriterNew with options.cc

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#37497]
DBSstFileWriterNew constructs a `rocksdb::Options` that is different from the one in `options.cc`. Most of the differences don't matter for the purposes of sst generation, but some do. Specifically, the combination of `prefix_extractor` and `filter_policy` causes the sst to be generated with a prefix bloom filter, improving performance of subsequent reads. The performance difference is short-lived since compactions will rewrite the imported ssts with bloom filters, but we might as well make sure that we're using the same options whenever we create ssts.

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[4829](https://cockroachdb.zendesk.com/agent/tickets/4829) has been linked to this issue.

**Comment by petermattis** [comment]
@itsbilal I think this won't be an issue in 20.1 because we use Pebble to generate sstables, right? Can you confirm?

**Comment by itsbilal** [comment]
That's correct, we use Pebble exclusively for writing SSTables now. Writer options used are generally the same as those used to initialize Pebble, except for the backup/ingestion-related differences mentioned in `sst_writer.go`. Filter policy and prefix extractor is correctly set for most SSTs now (except for backup ones), so I'll go ahead and close this.
