### ISSUE TITLE
roachpb: abstraction over []ReplicaDescriptor

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#37499]
Currently, the replicas field of the `RangeDescriptor` proto is a slice of `ReplicaDescriptor` protos. This slice ends up being copied around in a number of places, particularly the allocator. We're about to introduce learner replicas, which will add a field to ReplicaDescriptor to indicate what kind of replica it is. In the learners PR, the various users of `[]ReplicaDescriptor` will all need to decide whether to include or exclude learners from whatever they were doing with the replicas.

Most places will likely include them, but things like computing quorum counts will want to exclude. There are O(100)s of these callsites, so auditing them without help from the compiler will be hard. As a result, this seems like a good time to introduce a bit of abstraction.

(Note: This is still a bit of a WIP)

Option 1:
```
type ReplicaDescriptors []ReplicaDescriptor
```
- pros: Least invasive change
- cons: Doesn't get us much. A range loop over a field that has changed from `[]ReplicaDescriptor` to `ReplicaDescriptors` will still compile, so we'd miss it in the audit.

Option 2:
```
type ReplicaDescriptors struct {
    replicas []ReplicaDescriptor
}
```
- pros: Every usage of a field/arg/value that changes from `[]ReplicaDescriptor` to `ReplicaDescriptors` will break, causing us to consider each of them.
- cons: I've prototyped this and the normal code changes are pretty clean, we can likely develop a minimal set of methods that cover what we need. However, the tests are going to be a nightmare, they do all sorts of manual setup on and changes directly to the `RangeDescriptor.Replicas` field.

I don't think this is worth doing unless we go with Option 2.

Happily, most (all?) of these `[]ReplicaDescriptor` slices come from the `Replicas` field on `RangeDescriptor` and there is a small-ish set of functions that take them as args, so switching `[]ReplicaDescriptor` references to `ReplicaDescriptors` should be tractable, modulo the following.

Ideally, we'd be able to use something like the `gogoproto.customtype` option to make this field on the generated `RangeDescriptor` struct directly into a `ReplicaDescriptors`. Unfortunately, customtype looks to only work with the elements in a generated repeated field and doesn't let you replace the generated field wholesale. Here are the remaining options as I see them.

Option 2A:
Rename the proto field in `RangeDescriptor` from Replicas to InternalReplicas. Add a `Replicas()` method to `RangeDescriptor` that returns the `ReplicaDescriptors` wrapper.
- pros: Works pretty well for reading the field.
- cons: Any construction of a`RangeDescriptor` breaks the abstraction. This happens all the time in tests. Perhaps this could be broken into a two step process where the second step takes the `RangeDescriptor` and adds the `ReplicaDescriptors`.
- todo: Is there a limited set of mutations we need to support? The allocator currently does all sorts of stuff directly to the slices.

Option 2B:
Rename `RangeDescriptor` to `InternalRangeDescriptor` and embed it in a new `RangeDescriptor` struct. This new struct would also have a `Replicas ReplicaDescriptors` field and implement the proto marshal/unmarshal methods necessary to use it as a `gogoproto.customtype` in other protos that use a `RangeDescriptor`. This is very similar to (and inspired by) what andyk did with `pkg/sql/types.T` and `pkg/sql/types.InternalType`.
- pros: Maintains the `ReplicaDescriptors` abstraction.
- cons: Seems like overkill. `RangeDescriptor`s are manually constructed in tests all over the place and these will all have to be updated to reflect the embedded InternalRangeDescriptor struct, which then leaks the RangeDescriptor abstraction. `pkg/sql/types` has the benefit of a much more limited set of ways they need to be constructed. Maybe there's a way to work through this?

Option 2C:
Add a `customslice` option to gogoproto that does what I say we want above.
- pros: Seems like the ideal option.
- cons: Currently unknown difficultly and complexity. Blocks on an external project (or forces us to fork).

I'm leaning toward 2A.

Open questions:
- What's the perf impact?
- Is there a small-ish set of `ReplicaDescriptors` constructors we could provide that would cover most/all of the current test usage?

**Comment by danhhz** [comment]
Hey @tbg, this is still unfinished, but wondering if you have any opinions on the above before I go too far down any one path.

**Comment by tbg** [comment]
I bet most of the test usages just want to initialize one and so you can replace them all with a constructor.

> The allocator currently does all sorts of stuff directly to the slices.

Where? Wasn't able to find it just like that. We probably mutate these slices in a few places, but do we do more than just remove, update, or add a replica?

I also think 2A is the way to go for the reasons you mentioned.

PS if we decide that the joint consensus state gets to leak into the RangeDescriptor, this might inform the decision here somewhat, but a) I think we're leaning towards stashing it elsewhere and b) we can deal with it if it does happen.

**Comment by tbg** [comment]
^- this still means that `RangeDescriptor` isn't the right object to call `.SomeQuorumRelatedMethod` on, but you can leave that refactor to me, for when we actually do introduce joint quorums.

**Comment by danhhz** [comment]
> > The allocator currently does all sorts of stuff directly to the slices.
> 
> Where? Wasn't able to find it just like that. We probably mutate these slices in a few places, but do we do more than just remove, update, or add a replica?

I went back to look and it wasn't as bad as I thought. There's some places where it does filtering, but that's easy to support as well. There's a few wonky things going on in the tests, but worst case we can initially leave them using the raw fields.

How performance sensitive is all this? If I replace something that directly range-loops/mutates the slice with something based on a closure, is that going to matter? I'd guess the scoring gets called often-ish, but I haven't grokked the queues yet to understand exactly how often that is.
