### ISSUE TITLE
cdc: large dates and timestamps are silently changed

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#37508]
The goavro library uses int32s when marshaling dates and timestamps. If they don't fit in that size they are silently truncated.

Jira issue: CRDB-4426

**Comment by mjibson** [comment]
This may actually be a problem with the call to .UnixNano, suggesting that goavro only handles dates and timestamps whose nanosecond representation fits in an int64.

**Comment by amruss** [comment]
@HonoreDB do we think this is still an issue? Otherwise lets close

**Comment by HonoreDB** [comment]
I'll look into it, I know goavro's improved their date handling on recent versions but they may not have fixed this.

**Comment by miretskiy** [comment]
@HonoreDB please close this issue if it's stale.

**Comment by miretskiy** [comment]
Close/stale -- will reopen if somebody complains.
