### ISSUE TITLE
why optimizer always choose the secondary index when the query will scan almost whole table?

### ISSUE THREAD

**Issue by lanzao** [cockroachdb/cockroach#37503]
**What is your situation?**
CockroachDB version: v2.1

```
root@:26257/mydb> explain select name from people where age<400000 and age >0;
    tree    | field |  description
+-----------+-------+----------------+
  render    |       |
   └── scan |       |
            | table | people@idx_age
            | spans | /1-/400000
```
table schema:
```
CREATE TABLE people (
	name STRING NOT NULL,
	age INT NULL,
	sex STRING NULL,
	CONSTRAINT "primary" PRIMARY KEY (name ASC),
	INDEX idx_age (age ASC),
	FAMILY "primary" (name, age, sex)
)
```
TABLE `people` have 500,001 rows with age from 0 to 500,000, so the result after filter `where age<400000 and age >0` still have about 400,000 rows. 

Whether CBO Optimizer is `on` or `off`, the plan of query always choose secondary index `idx_age`.
(By the way, I have create statistics on column people(age))

In this situation, I think, scanning the whole table is better than using secondary index which would perform twice scan on KV store.

I am more intersted in the situation using CBO optimizer. How does CBO optimizer calculate the cost of using different index and decide which index to use? (how can I trace this part of code?)

In our production environment(version 2.1, CBO optimizer on), CBO optimizer sometimes choose the wrong index.
for example: 
We have a Table t1 with 8,000,000 rows,then run the SQL `select * from t1 where xx<100` which only return 100 rows, and there is an secondary index idx_xx on column `xx`. 

However, the plan never use idx_xx but scanning whole table instead. 
When I turn off the CBO optimizer , the plan will correctly use idx_xx .

**Comment by tim-o** [comment]
@lanzao Can you send over the [statistics](https://www.cockroachlabs.com/docs/v2.1/show-statistics.html) on the people and t1 tables you mentioned, and the CREATE TABLE statement for t1?

The second issue sounds like a bug for sure given what you've said so far.. I just need the steps to reproduce it.

**Comment by RaduBerinde** [comment]
Hello @lanzao,

In the first case, I don't see the problem. The index contains all the needed columns (`name`, `age`), so it is actually faster to scan than the primary index (it contains less data). BTW you can use index hints to run both and see which is faster (`SELECT name FROM people@primary`).

In the second case - the optimizer does not yet use histograms, so it doesn't know the distribution of values and underestimates the selectivity of the filter. In this case I am guessing that the index does not contain all needed columns and an index join is required, which is fairly expensive when there are a lot of rows; so the optimizer decides that a full table scan is cheaper. We are working on adding histograms in future releases. In the meantime, you could work around this problem using an index hint (`SELECT * FROM t1@idx_xx`). Or, if the values are e.g. greater than 0, you could add `AND xx>0` to the query and that might result in a better estimation.

As for the costing code, it is here: https://github.com/cockroachdb/cockroach/blob/fb8e85da7bdd94dacdd38e27a53822785dc5078d/pkg/sql/opt/xform/coster.go#L261

Hope this helps!

**Comment by lanzao** [comment]
@tim-o  I am sorry that these data and schema are not suitable to be publicized, but the situation is just like that @RaduBerinde guessed :
"In this case I am guessing that the index does not contain all needed columns and an index join is required"

@RaduBerinde  Your help was greatly appreciate! Have you compared the performance of the two optimizers? Is there any relevant data?

**Comment by RaduBerinde** [comment]
The CBO (optimizer ON) should be better in most cases. It is definitely at least as good in the set of  cases we looked at. The old planner will be removed altogether in upcoming releases (OFF will no longer be an option).
