### ISSUE TITLE
storage: implementation of queues is not idiomatic

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#3752]
Our system of queues is currently implemented as a collection of classes which "inherit" from `baseQueue`. This is awkward and not very idiomatic in Go; it also makes it difficult to track down the queue implementation from logs, e.g.:

```
I0111 15:57:42.514974 34197 storage/queue.go:403  [split] range=1 [/Min-/Table/11): done: 134.38ms
```

storage/queue.go:403 points to the base queue, not the (in this case) splitQueue, which makes drilling down into the implementation annoying.

I'm not quite sure what the right way to refactor this is, but it might make for a good starter project.

**Comment by petermattis** [comment]
@tamird Maybe bump to the 1.0 milestone if this isn't urgent.

**Comment by tamird** [comment]
I'm just going to clear the milestone since there's no real deadline here.

**Comment by nvanbenschoten** [comment]
We don't have any plans to address this any time soon. Closing.
