### ISSUE TITLE
release: v19.1.1

### ISSUE THREAD

**Issue by ajkr** [cockroachdb/cockroach#37535]
Candidate SHA: c8bda1de440cfe90cf23a433119d77795cfa0047
Deployment status:

- Previous: http://andrewk-release-v1910-0001.roachprod.crdb.io:26258/
- Candidate: http://andrewk-release-v1911-0001.roachprod.crdb.io:26258/

Nightly Suite: https://teamcity.cockroachdb.com/viewLog.html?buildId=1294583&buildTypeId=Cockroach_Nightlies_NightlySuite

[Release process checklist](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process)

Prep date: Wednesday, May 15
- [x] [Pick a SHA](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-PickingaSHA), fill in `Candidate SHA` above, notify #release-process of SHA.
- [x] [Tag the provisional SHA](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-TagtheprovisionalSHA)
- [x] [Publish provisional binaries](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Publishtheprovisionalbinaries)
- [x] [Check binaries](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Checkbinaries)
- [x] [Deploy to test clusters](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-DeploytoTestClusters) (this step was changed to making a cluster that runs `workload tpcc`)
- [x] [Start release qualification suite](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-RuntheSuiteofNightlyRoachtests)
- [x] [Start nightly suite](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-RuntheSuiteofNightlyRoachtests)
- [x] [Verify node crash reports](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Verifynodecrashreportsappearinsentry.io)
- [x] fill in `Deployment status` above with clusters and `Nightly Suite` with the link to Nightly TeamCity Job

- Keep an eye on clusters until release date. Do not proceed below until the release date.

Release date: Monday, May 20
- [x] [Check cluster status](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Checkclusterstatus)
- [x] [Tag release](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Tagtherelease)
- [x] [Bless provisional binaries](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Blesstheprovisionalbinaries)

- For production or stable releases in the latest major release series
  - [ ] Update the [Homebrew Formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/cockroach.rb)
  - [ ] Update the image tag in our [Orchestrator configurations](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Orchestratorconfigurations)
  - [x] Announce version to the [registration cluster](https://github.com/cockroachlabs/production#publishing-a-new-release-version)
  - [x] Upgrade the registration cluster (reg runs latest stable version)

- [ ] Update docs
- [ ] External communications for release

**Comment by ajkr** [comment]
Here are the roachtests that failed in the nightly suite:

- https://github.com/cockroachdb/cockroach/issues/33501#issuecomment-493430338
- https://github.com/cockroachdb/cockroach/issues/37349#issuecomment-493392422
- https://github.com/cockroachdb/cockroach/issues/34359#issuecomment-493502872

**Comment by bdarnell** [comment]
Those have been failing a lot on different branches, so they shouldn't block the release. (on 19.1.x, only the tpcc headroom test has been designated a release blocker)

**Comment by ajkr** [comment]
Alright, I will go ahead with tagging then.

**Comment by tbg** [comment]
The release is out.
