### ISSUE TITLE
Is the version 19.1 not a spelling fail?

### ISSUE THREAD

**Issue by LukascraftHD** [cockroachdb/cockroach#37542]
I used in a cluster the version 19.1.0 but yeah, when I now try to update to 2.1.7 this error comes up.

* ERROR: cockroach server exited with error: inspecting engines: cockroach versi
on v2.1 is incompatible with data in store <no-attributes>=D:\60_cockroachDB\nod
e1; use version v19.1 or later

So is the version 19.1 simply a labeling fail or is it a different branch? idk.
Thanks for answering.

**To Reproduce**
Just create a cluster with 19.1.0 and then try to update to 2.1.7.

**Environment:**
 - CockroachDB version 19.1.0 to 2.1.7
 - Server OS: Windows Server 2012 R2 (latest Updates installed) and Ubuntu 18.04
cockco

**Comment by ricardocrdb** [comment]
Hello @LukascraftHD,

When performing the upgrade, did you set the CLUSTER SETTING `cluster.preserve_downgrade_option` as mentioned [here](https://www.cockroachlabs.com/docs/stable/upgrade-cockroach-version.html#step-3-decide-how-the-upgrade-will-be-finalized)? If not, then you can perform a downgrade to 2.1.x by restoring from a backup. 

Let me know if you have any other questions or concerns.

Cheers,
Ricardo

**Comment by knz** [comment]
@LukascraftHD for clarity, the version 19.1 is not a spelling mistake, and is more recent than 2.1. 
Therefore there is no such thing as "upgrading from 19.1 to 2.1" - this would be a *downgrade*.

We changed to calendar-based versioning as explained here: https://www.cockroachlabs.com/blog/calendar-versioning/

**Comment by LukascraftHD** [comment]
Thanks to your answers. @ricardocrdb and @knz.

I didn't saw the blog post or the Cluster Setting either, so yeah thanks for your clarification about the version numbers.

So in short, i can run my clusters safely on 19.1 and I'm able to receive the next Updates, right?

Thanks for the Reply's, for me that case is solved :D 👍
