### ISSUE TITLE
sql: incorrect float * interval with 

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#37540]
```
SELECT .5 * '1 mon 2 day 2:00:00'::INTERVAL
```

postgres:
```
16 days 01:00:00
```

cockroach:
```
1 day 01:00:00
```

Cockroach doesn't do the same month -> day conversion during float multiply that postgres does.

**Comment by hueypark** [comment]
@mjibson I create PR for this issue. Could you please review this one?
