### ISSUE TITLE
Parallelize CircleCI build

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#3758]
We could speed up our CI builds by running the tests across multiple VMs. This is a little tricky because a large fraction of our test time is taken up by the build steps (restoring the cache, etc), and we don't want to duplicate that work across multiple instances, but we could separate a few disjoint subsets of our build. For example, we could build and run the race tests on their own instance and then the other instances wouldn't have to build or cache any of the `-race` objects.

**Comment by tschottdorf** [comment]
I think something similar might be possible for the acceptance tests (with their own tag, they probably have their own, disjoint cache).

**Comment by petermattis** [comment]
@tschottdorf The acceptance tests share the cache with the normal (non-race) tests. I think. It should definitely be possible to parallelize the race and non-race tests, though. I'll take a look at this tomorrow

**Comment by bdarnell** [comment]
The acceptance tests have a tag, but not an `installsuffix` so I don't think they're getting built twice. I'm not sure, though.

Another likely win is to split the `make check`/`go generate` steps onto a dedicated worker. The main tests don't need npm stuff or the other miscellaneous commands.

**Comment by petermattis** [comment]
I'll probably have to cache the normal and race builds separately so that the caches don't stomp on each other.
