### ISSUE TITLE
cockroachlabs documentation https certificate broken

### ISSUE THREAD

**Issue by slbucur** [cockroachdb/cockroach#37581]
**Describe the problem**

The https certificate for cockroachlabs.com appears to be broken. 
I can't access it in Chrome mobile, and when adding an exception it's also blocked by my mobile carrier (Vodafone) 

**To Reproduce**

Access the cockroachlabs.com site from Chrome mobile or Firefox mobile. 
The invalid certificate problem happens rather randomly. For example, yesterday it worked, but the day before it didn't. 

**Expected behavior**
I am unable to access the site. If I add an exception (in Firefox, Chrome doesn't have that enabled), it's also blocked by my carrier, with a phishing error. 

**Additional data / screenshots**
```
Your connection is not private
Attackers might be trying to steal your information from www.cockroachlabs.com (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_AUTHORITY_INVALID
Subject: www.cockroachlabs.com

Issuer: allot.com/emailAddress=info@allot.com

Expires on: May 7, 2020

Current date: May 18, 2019

PEM encoded chain:
-----BEGIN CERTIFICATE-----
MIICojCCAYqgAwIBAgIRAPXb+1oAAAAAaFQAAAAAAAAwDQYJKoZIhvcNAQELBQAw
fzELMAkGA1UEBhMCRVMxDzANBgNVBAgMBk1hZHJpZDEPMA0GA1UEBwwGTWFkcmlk
MQ4wDAYDVQQKDAVBbGxvdDEOMAwGA1UECwwFQWxsb3QxLjAsBgNVBAMMJWFsbG90
LmNvbS9lbWFpbEFkZHJlc3M9aW5mb0BhbGxvdC5jb20wHhcNMTgwNTA4MDgxODM0
WhcNMjAwNTA3MDgxODM0WjAgMR4wHAYDVQQDDBV3d3cuY29ja3JvYWNobGFicy5j
b20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASKPG9hh5sjOhj1K6PRdhdpf2gP
OQkR/d5Q1/CHygZBSwi32wAvIlC8BVLqUMoRr35ByOEkL1XClVQhCs+fPK6jo0Mw
QTAgBgNVHREEGTAXghV3d3cuY29ja3JvYWNobGFicy5jb20wHQYDVR0OBBYEFOIG
W9E1Y03+x336rYGXa1r4ysoxMA0GCSqGSIb3DQEBCwUAA4IBAQCZgkTR3mnHCCV6
lo2lGJWxzkJX/M6XlWrs0eX6FfO+5QlRhnHnTbLm5opCvm3jj+Bca3sOx5GM8lIh
hTSddkGTIXFTWZaCkhq5jL2uA+oapyaAS8BO2UT749YLwej/KDnviWdd7N7lMzZD
N79Fa8WtC9gdZ83KF7C16PbuKHhtOtuK36gqYr8T0zslnjl6RGU3LI/ZYSS857US
MEheQImDTUQDdvE8g/99TvWcwoF1uX64ughn4saiTrhmp9QCLjvknrMByiTzyVW6
A8SFFgGWhipT8L2/wbx9RXvdcZNPVZOd7Ev2D2vFkpqMxahLXY7lbmQwsJUAf/Yu
Te1fxnJj
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIID3DCCAsSgAwIBAgIBATANBgkqhkiG9w0BAQsFADB/MQswCQYDVQQGEwJFUzEP
MA0GA1UECAwGTWFkcmlkMQ8wDQYDVQQHDAZNYWRyaWQxDjAMBgNVBAoMBUFsbG90
MQ4wDAYDVQQLDAVBbGxvdDEuMCwGA1UEAwwlYWxsb3QuY29tL2VtYWlsQWRkcmVz
cz1pbmZvQGFsbG90LmNvbTAeFw0xNjEyMTYxMzA3NDlaFw0yNjEyMTYxMzA3NDla
MH8xCzAJBgNVBAYTAkVTMQ8wDQYDVQQIDAZNYWRyaWQxDzANBgNVBAcMBk1hZHJp
ZDEOMAwGA1UECgwFQWxsb3QxDjAMBgNVBAsMBUFsbG90MS4wLAYDVQQDDCVhbGxv
dC5jb20vZW1haWxBZGRyZXNzPWluZm9AYWxsb3QuY29tMIIBIjANBgkqhkiG9w0B
AQEFAAOCAQ8AMIIBCgKCAQEAtckdwPaklW7lAUz/jjFnePUeGNG0w9E1ajLq4UZO
vol1ESRdiVXJhj43/4NtvFGiw0ujDwh8K5xErtaXx+W+Lk0yw2uXATBtdvr3pdDj
cxNjUVYl6iis0lxgKff02fsLHdLvy9hJX08wsBF6NKW9YetM6WznDsWztucfg8a1
QaUxFzwHxKjTaV9+RO1zosUgU6RIZwBJrXnyJPeMdbDeS7+WXIAQT1WlficRckAw
4VX7l90AVXzng+Kf+SErsD0DtOiMS/nawa/0tW6whd6zmSaCtPJg37EBp3BQkpdn
RvRCsG9h1aWkBUdFNb0mNbnHDP0dmWrDZEFKNmpeC6LmkQIDAQABo2MwYTAOBgNV
HQ8BAf8EBAMCAQYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUqLwqHQ0a0mcp
ebqXCx9QL1ibqvcwHwYDVR0jBBgwFoAUqLwqHQ0a0mcpebqXCx9QL1ibqvcwDQYJ
KoZIhvcNAQELBQADggEBAHJsGkbv+mGhMHfc5z1UZGsH0rkV0U+tl/6hwutyMHPO
tvHCwK30keSqiIz8E0grwkMAiS4Ir1w52hfJB0JndxWv1rBTk5gA5ASruhsNKcgv
hDgfuVBwSw7ILX9wkl5J2Eu/ew3TRB8lDO7XX4DF0p2L1DyZl+r0HSB9NgQH4kI7
HSxW0oo34bu+S/u3ycMZ1RjjzzVKtI5S6ydVz2qKVqhuSwuFJnndoKjrzMphwraN
cKSTLyIj77FK1IUtiivprXk15/lrlnoK+zIlrCzR/Yl5pBYDjb1VhTLUBzm8uNV/
dlYQqPygZFfK8Al/p1grILXWUHmdOaUX+AoWlitKDJo=
-----END CERTIFICATE-----

```

**Comment by slbucur** [comment]
I would like to mention that I've never experienced problems on my desktop browsers.

**Comment by mberhault** [comment]
Thanks for the report @slbucur.

This is likely traffic interception by Vodafone ([see a](https://community.cloudflare.com/t/err-cert-authority-invalid-only-with-vodafone/66900/8) [few](https://forum.vodafone.co.uk/t5/Pay-monthly/Website-security-certificate-coming-from-vodafone-content/td-p/2454980) [threads](https://forum.vodafone.co.uk/t5/Archive/Vodafone-broadband-content-control-injects-SSL-certificates-into/m-p/2582672) [about](https://bandaancha.eu/foros/vodafone-empieza-bloquear-sitios-1734725) [it](https://twitter.com/hookgab/status/1021799979646640130)).

The easiest solution (and safest for you) would be to use a real DNS provider. Cloudflare (1.1.1.1) or Google (4.4.4.4 or 8.8.8.8) are commonly recommended solutions.

If the problem still occurs after that, please let us know.

**Comment by slbucur** [comment]
Thanks for the reply 😄 .

Looks like that's the case. It works when I change the DNS provider on my wifi network.
Unfortunately, that doesn't work on my mobile network (4G/3G), as the DNS server can only be changed for wifi on android.
If you know a link where I can submit an issue to Vodafone about this please let me know.

In any case, I'm not sure if you can do anything about it, so you can close the issue.

**Comment by mberhault** [comment]
Sorry, I'm afraid there's indeed nothing we can do on our end.

On IOS, you may be able to find third-party apps that allow you to specify custom DNS servers on cellular, but I don't know of any myself.

As far as Vodafone is concerned you could try the forum or customer service but they are definitely doing this on purpose, will claim it's for your security, and are unlikely to stop. They will probably tell you simply to add their custom CA to your trusted store. I would urge you **not** to do that.
