### ISSUE TITLE
split failed while applying backpressure : split at key /Table/185/1/"xxxxx" failed: context deadline exceeded

### ISSUE THREAD

**Issue by heidawei** [cockroachdb/cockroach#37592]
**Describe the problem**

I insert some rows to a table, which has only one range. use 100 concurrent clients, there are 1000 values in each insert SQL. I got error "split failed while applying backpressure : split at key /Table/185/1/"xxxxx" failed: context deadline exceeded".  I do not stop insert, and the error always appear， and I see the table has one range before I rename the table name to keep the scene, I think it is equivalent to stop insert. the table range split to 22 ranges  a moment after I renamed the table name.

I check the log, I find the range try to split but failed for context deadline exceeded when I do insert, use different split key each time.

Oddly enough, new tables are created at this time（insert time）, and the same problem does not arise for testing.

I check the CPU , memory, dick IO status, network status。nothing unusual.

I check the latch manager and the batch write process, I can not find the problem.

**Environment:**
 - CockroachDB version 2.1
 - Server OS:  Linux
 - Client app cockroach sql, JDBC

**Comment by heidawei** [comment]
I think that even under heavy pressure, the split will still succeed before the timeout. At least after a few tries, it will succeed, because the split request will latch the whole range and prevent other writes from happening.

**Comment by heidawei** [comment]
when the range size is big, find split key will cost a lot of time, but what happed during its enlargement

**Comment by roncrdb** [comment]
Hi @heidawei 

We've created a single master issue for this bug, I've linked it to this issue, but will be closing this particular issue out. 

Thanks!

**Comment by roncrdb** [comment]
Hey @heidawei,

Just wanted to follow up here and see if you could provide us with the cockroach-data folder from this cluster, it would be very helpful in debugging this issue. 

You could email the folder to me [here](mailto:ron@cockroachlabs.com). 

Thanks!
