### ISSUE TITLE
Create method of exposing time to expiration for licenses

### ISSUE THREAD

**Issue by tim-o** [cockroachdb/cockroach#37688]
**Enhancement Request**

As an admin of a cluster using an enterprise license, I'd like to be able to see the expiration date of my license. One possible way of meeting this need would be to create a read-only cluster setting that automagically stores the current expiration date after the license is updated.

This Github issue is synchronized with Zendesk:

**Ticket ID:** [#3350](https://cockroachdb.zendesk.com/agent/tickets/3350)
**Group:** Support
**Requester:** mikael.sandstrom@unibet.com
**Issue escalated by:** Tim O'Brien

**Original ticket description:**

<blockquote><div class="zd-comment" dir="auto">Yeah, I’d be happy with just having the date exposed somewhere to start with (and a cluster setting sounds like a good idea)<br><br>---<br><br>Ticket created from a Slack <a href="https://cockroachlabs.slack.com/archives/G2N3Q10CA/p1558451575006500?thread_ts=1558445333.003600&amp;cid=G2N3Q10CA" rel="noreferrer">message</a> by <a href="https://cockroachlabs.slack.com/team/UAG3N1H37" rel="noreferrer">Tim O'Brien</a></div></blockquote>

Jira issue: CRDB-4422

**Comment by knz** [comment]
@piyush-singh this could become an item in the CLI roadmap. What do you think? Do you want to add it to the various docs?

**Comment by knz** [comment]
this is still relevant.
Which team though?

@mwang1026 do you know how to triage this?
