### ISSUE TITLE
jobs, *: refactor planning vs exec APIs

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#37691]
The hook plans generally get a limited version of planner (planHookState) some parts of which use the planner's txn.

They use this planner as part of the planning of the job they ultimately start, e.g. resolving the table name or or user privileges, etc that go in to determining if, how and on what the job will run.

Unfortunately, planner _usually_ assumes that it is used for the entirety of a normal SQL statement, so it's embedded txn is usually not committed until after the plan has run. This however means that when the hook plans start and run a job based on calls to this planner, they are running a job -- with side effects -- based on reads made with an uncommitted txn. 

However some jobs support being planned in a transaction, and then run after it commits, e.g. using `DETACHED`. In these cases, it is vital the limit all their planning to use the planner txn to avoid leaking side-effects.

Thus, *all job planning statements (BACKUP, IMPORT, RESTORE, etc) should be audited to ensure they _only_ use the planhook (planner) txn.*

Then, for those jobs which wish to execute during the statement execution to return results (i.e. non-detached), they should a) assert the planner txn is implicit and then b) commit it inline ala 1PC INSERTs, before running the job.

Separately, job _execution_ currently gets the same PlanHookState interface however, as this closes over a planner, it also closes over a planner transaction field, but as this is outside a statement execution, that field is nil. This has lead to crashes when method that reference that field are called, often indirectly via very non-obvious call-trees. 

Instead, job execution (i.e. `Resume()`) should be passed a different interface entirely from planning, which is not a planner at all and has potentially nil txn field.

**Comment by dt** [comment]
part of the problem here is that the conn executor has special code to execute "async" schema changes before sending the reply, making them appear synchronous: 
https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/conn_executor.go#L1996

This doesn't exist for jobs, so there is no way to a) commit a job record and then b) wait for its results currently -- the job can't run until its creation commits, but that doesn't currently have any way to block on its execution. Current jobs commit, run and block all during the statement creation them, but that is a gross mis-use of the planner txn -- which won't commit until later -- to plan the job.

**Comment by spaskob** [comment]
@ajwerner  pinging you on this as it may be related to #44739

**Comment by dt** [comment]
#55506
