### ISSUE TITLE
opt,distsql: lookup joiner should constrain spans based on filters

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#37727]
@RaduBerinde showed me this example:
```
root@127.129.186.234:34009/defaultdb> create table ab (a int, b int, c int, primary key (a,b,c));
root@127.129.186.234:34009/defaultdb> create table x (x int);
root@127.129.186.234:34009/defaultdb> explain (opt) select a,b,c FROM x INNER LOOKUP JOIN ab ON x=a AND b=10;
                     text                      
+---------------------------------------------+
  project                                      
   └── inner-join (lookup ab)                  
        ├── flags: no-merge-join;no-hash-join  
        ├── scan x                             
        └── filters                            
             └── b = 10                        
(6 rows)
```
In theory, the lookup joiner should be able to use the `b = 10` filter to constrain its seeks, rather than filtering on top.

What's more, the opposite order should also be true:
```
root@127.0.0.1:55293/defaultdb> explain (opt) select a,b,c FROM x INNER LOOKUP JOIN ab ON x=b AND a=10;
                       text
+------------------------------------------------+
  project
   └── inner-join
        ├── flags: no-merge-join;no-hash-join
        ├── scan x
        ├── scan ab
        │    └── constraint: /3/4/5: [/10 - /10]
        └── filters
             └── x = b
(8 rows)
```
This should be able to do a lookup to the values of `b` which are equal to `x`, rather than having a filter on top.

**Comment by khalibartan** [comment]
@justinj @ridwanmsharif  I would like to work on this one if its not on priority. 

> rather than filtering on top

@justinj  By this line did you mean that look up join should use these constraints while joining itself rather than filtering results later on post join?

**Comment by justinj** [comment]
@khalibartan that's correct, the lookup joiner should take care of those filters as part of its lookups, rather than filtering after the fact.

Thanks for your interest in contributing! This issue is fairly complex and involves touching several subsystems of Cockroach. I don't think it's a good issue for an external contributor to work on.

**Comment by justinj** [comment]
@solongordon thought of a really nice way to do this: the optimizer can just introduce the constant columns as projections on the input so that they can be treated as any other columns. Then there would be no changes required on the execution side.
