### ISSUE TITLE
While sync_file_range offset 0 bytes 557056

### ISSUE THREAD

**Issue by cevin** [cockroachdb/cockroach#37752]
**Describe the problem**

```
[n1,s1,r4/1:/System{/tsd-tse}] while committing batch: while committing batch: IO error: While sync_file_range offset 0 bytes 557056: /mnt/d/debian/store1/000003.log: Function not implemented
goroutine 212 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0xc0004b8000, 0xc0004b8060, 0x53d3200, 0x10)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:1020 +0xd4
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x5b5d300, 0xc000000004, 0x53d326d, 0x10, 0xe63, 0xc0009fa900, 0xbf)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:876 +0x95a
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x3a431c0, 0xc00a668ea0, 0x4, 0x2, 0x32c0ea2, 0x6, 0xc009587eb0, 0x2, 0x2)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:85 +0x2d8
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x3a431c0, 0xc00a668ea0, 0x1, 0x4, 0x32c0ea2, 0x6, 0xc009587eb0, 0x2, 0x2)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:71 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(0x3a431c0, 0xc00a668ea0, 0x32c0ea2, 0x6, 0xc009587eb0, 0x2, 0x2)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:182 +0x7e
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processReady(0xc000cc2000, 0x3a431c0, 0xc00a668ea0, 0x4)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3683 +0x4f4
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc000507600, 0x3a431c0, 0xc000c6c3f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:214 +0x258
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x3a431c0, 0xc000c6c3f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:165 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc0002194f0, 0xc0009bc000, 0xc0002194e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:200 +0xe1
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:193 +0xa8
```

**Additional data / screenshots**
![image](https://user-images.githubusercontent.com/338110/58227554-ea6db680-7d5d-11e9-8d72-a2ac3efd658f.png)

**Environment:**
 - CockroachDB version : 2.x
 - Server OS: windows wsl debian
 - Client app: psql

**Comment by petermattis** [comment]
@ajkr Looks like we're trying to use `sync_file_range` on windows (via windows wsl). Is there a way to disable that without recompiling?

**Comment by ajkr** [comment]
Yes we just need to pass rocksdb options `bytes_per_sync=0` and `wal_bytes_per_sync=0`. For example, here is a CLI invocation that'll set those options as mentioned. I verified with strace it does not try to `sync_file_range` anymore.

```
$ ./cockroach start --insecure --store='path=./cockroach-data,rocksdb=bytes_per_sync=0;wal_bytes_per_sync=0'
```

**Comment by petermattis** [comment]
@ajkr Great. Any ideas how to improve the auto-detection so this isn't necessary? Simply looking for an ext4 filesystem apparently isn't sufficient. Perhaps we should try to do a test call to `sync_file_range`.

**Comment by ajkr** [comment]
Are you familiar with this wsl build? Would it be the same binary we use for Linux, or something built specifically for that target?

**Comment by petermattis** [comment]
> Are you familiar with this wsl build? Would it be the same binary we use for Linux, or something built specifically for that target?

I presume it is the standard linux binary. @cevin can you clarify where this binary came from?

**Comment by ajkr** [comment]
OK, I guess it is using the same binary as Linux too since there's already a compile-time check that invoking `sync_file_range` succeeds.

**Comment by ajkr** [comment]
Maybe in `SanitizeOptions` we can invoke `sync_file_range` on the `CURRENT` file, then overwrite the options to zero if it fails.

**Comment by ajkr** [comment]
I believe https://github.com/cockroachdb/rocksdb/pull/33 will fix it, though haven't had a chance to test on WSL.
