### ISSUE TITLE
rpc: clock skew on EC2 leads to cluster death after 13h

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#3779]
3 nodes running on m3-large machines on EC2 (2cpu, 7GB ram, 1x30GB SSD).

First node crashed after 7 hours, the other two at 13h.

Panic message form each:
```
F0112 01:43:28.873120 7102 rpc/clock_offset.go:179  clock offset from the cluster time for remote clocks: map[172.31.58.172:46131:off=-0.000021365s, err=0.000061756s, at=2016-01-12 01:43:17 +0000 UTC ip-172-31-58-172:26257:off=0.000021365s, err=0.000061756s, at=2016-01-12 01:43:17 +0000 UTC 172.31.58.173:51288:off=-0.500369683s, err=0.000224381s, at=2016-01-12 01:43:19 +0000 UTC 172.31.58.173:51820:off=-0.500390491s, err=0.000233755s, at=2016-01-12 01:43:20 +0000 UTC ip-172-31-58-174:26257:off=-0.193694690s, err=0.000269777s, at=2016-01-12 01:43:20 +0000 UTC 172.31.58.174:39641:off=-0.193795403s, err=0.000280246s, at=2016-01-12 01:43:17 +0000 UTC 172.31.58.174:40138:off=-0.193703714s, err=0.000289655s, at=2016-01-12 01:43:09 +0000 UTC ip-172-31-58-173:26257:off=-0.500349900s, err=0.000272122s, at=2016-01-12 01:43:19 +0000 UTC] is in interval: {-443.964467ms, -250.156736ms}, which indicates that the true offset is greater than 250ms
```

```
F0112 05:15:59.291313 4884 rpc/clock_offset.go:172  clock offset from the cluster time for remote clocks map[172.31.58.174:46853:off=0.500712869s, err=0.000249557s, at=2016-01-12 05:15:47 +0000 UTC ip-172-31-58-174:26257:off=0.500667038s, err=0.000243563s, at=2016-01-12 05:15:41 +0000 UTC 172.31.58.173:48039:off=-0.000027485s, err=0.000069450s, at=2016-01-12 05:15:46 +0000 UTC ip-172-31-58-173:26257:off=0.000027485s, err=0.000069450s, at=2016-01-12 05:15:46 +0000 UTC] could not be determined: a majority of connected remote clocks have failed to encompass the true time for the cluster
```

```
F0112 05:16:00.371407 5060 rpc/clock_offset.go:179  clock offset from the cluster time for remote clocks: map[ip-172-31-58-173:26257:off=-0.500712869s, err=0.000249557s, at=2016-01-12 05:15:47 +0000 UTC 172.31.58.174:34904:off=-0.000031205s, err=0.000072812s, at=2016-01-12 05:15:55 +0000 UTC ip-172-31-58-174:26257:off=0.000031205s, err=0.000072812s, at=2016-01-12 05:15:55 +0000 UTC 172.31.58.173:33075:off=-0.500644422s, err=0.000267458s, at=2016-01-12 05:15:41 +0000 UTC 172.31.58.173:59476:off=-0.500667038s, err=0.000243563s, at=2016-01-12 05:15:41 +0000 UTC] is in interval: {-750.910601ms, -250.463312ms}, which indicates that the true offset is greater than 250ms
```

I have full logs as well.

**Comment by mberhault** [comment]
Soon after launching the cluster, I saw messages related to clock skew and ran ntpdate on each node. That got rid of them. However, EC2 instances have notoriously bad clocks.

**Comment by tschottdorf** [comment]
and are the clocks actually that skewed now that the cluster is dead?

**Comment by mberhault** [comment]
Given that even this command shows massively-different clocks: yes!

```
$ time for i in $hosts; do ssh -i ~/.ssh/cockroach-shared.pem ${i} date; done
Tue Jan 12 15:15:25 UTC 2016
Tue Jan 12 15:15:25 UTC 2016
Tue Jan 12 15:15:27 UTC 2016

real	0m1.381s
user	0m0.129s
sys	0m0.012s
```

**Comment by mberhault** [comment]
or to be more precise, here's what ntp wants to fix:
```
ec2-54-209-133-121.compute-1.amazonaws.com
12 Jan 15:19:04 ntpdate[7993]: adjust time server 24.56.178.140 offset 0.052378 sec

ec2-54-209-69-52.compute-1.amazonaws.com
12 Jan 15:19:09 ntpdate[7784]: step time server 128.138.141.172 offset 1.102124 sec

ec2-54-208-199-194.compute-1.amazonaws.com
12 Jan 15:19:18 ntpdate[9974]: step time server 24.56.178.140 offset -0.636221 sec
```

**Comment by mberhault** [comment]
interesting. ntp isn't running by default on those images. I'll do that and try again.

**Comment by tschottdorf** [comment]
and it looks like the second guy uses a different time server than the other two - maybe doesn't help

**Comment by mberhault** [comment]
nah, this was the output of `ntpdate -q time.nist.gov`. ntpd has the same config on all servers using 5 different time server.

**Comment by JackKrupansky** [comment]
Is it that the instances themselves have bad clocks or that periodic NTP updates are being flaky due to network congestion/issues?

I'm just wondering if occasionally an instance gets a bad update due to network issues and maybe the best strategy is to detect when the clock changes by more than the amount that a local hardware clock can be expected to drift and in such a case simply wait a bit or force an update and then wait until the clock updates settle down.

And then maybe the strategy should be to simply pause serving of requests until the clock has settled down rather than panic each and every time EC2 hiccups.

In any case, an automated solution rather than panic and manual intervention would help to... "make data easy."

Sounds like a roadmap issue to me.

**Comment by mberhault** [comment]
NTP wasn't actually running at the time of those crashes, so there was no clock correction whatsoever.
Still clock drift of over 1s in ~13h is mad.
I've installed ntp on all my nodes and trying again. So far, it seems to be able to keep up with the clocks skew, but it's only been a few hours.

Ultimately, I agree, we need a better way to handle this. Panic is probably not the best way to go.

**Comment by bdarnell** [comment]
I think panicking is a reasonable way to go: we want to make sure that the node doesn't try to process any requests while it is out of sync, so as long as its rare we can just kill the node and let the process manager restart it. If we don't panic we'll need to build in some other way to block everything from making progress (and make sure that clients don't keep retrying on a node that is out of sync).

**Comment by tschottdorf** [comment]
Maybe it's reasonable if one node panics, but not all of them. In a group of three, I'm not sure how good the outlier detection really is (haven't looked though).

**Comment by mberhault** [comment]
What should we do about this one? We'll definitely want to recommend that people run ntpd on their machines, but is there anything to address on our side?

**Comment by petermattis** [comment]
Does ntpd need to be running inside the same VM as cockroach? Can we check that ntpd is running?

**Comment by mberhault** [comment]
ideally, yes, although I don't expect cloud deployment to run inside yet another VM.
as for checking, we could try, but that may be fragile.

**Comment by petermattis** [comment]
I'm open to better ideas. I was thinking we could use `gosigar` to get a process list and then iterate over that to see if `ntpd` is present. Using `gosigar` would give us some measure of portability. I'd consider this low priority for the beta, but we probably want something for 1.0. Not having ntpd running on your machine is an obvious failure scenario.

**Comment by JackKrupansky** [comment]
I see this in the AWS doc: "_Network Time Protocol (NTP) is **configured by default on Amazon Linux instances**; however, an instance needs access to the Internet for the standard NTP configuration to work. Your instance's security group must also allow outbound UDP traffic on port 123 (NTP)._"

See:
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-time.html#configure_ntp

I've also seen the claim that instances get their time from their VM host, which itself has NTP running, in which case NTP is not technically running on the instance.

See:
https://www.quora.com/Why-isnt-NTP-enabled-by-default-on-AWS-EC2-instances

**Comment by bdarnell** [comment]
In containerized deployments I don't think ntpd would be visible from inside cockroachdb's container. I don't think we should try to test for the presence or absence of ntpd, but we do need monitoring of clock offsets whether ntpd is present or not.

**Comment by JackKrupansky** [comment]
Maybe an intermediate warning threshold as well, so if the clock is
starting to drift the user can take some action to synchronize at a
convenient time rather than recover from mass panic.

Does the UI have a display/metric for clock sync?

-- Jack Krupansky

**Comment by tamird** [comment]
Closing this as it's probably irrelevant now that https://github.com/cockroachdb/cockroach/pull/5512 is in.
