### ISSUE TITLE
sql: replace all map[sqlbase.ColumnID]int types with util.FastIntMap

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#37801]
`pkg/sql` is littered with mappings from column IDs to projection/row/other indexes. The package uses the type `map[sqlbase.ColumnID]int` to represent these mappings.

In almost all cases, we would be better off using `util.FastIntMap`, which can avoid a map allocation if the column ID never goes above 31 and the index never goes above 14. Any table that wouldn't be considered "wide" meets these requirements.

We should replace all instances of `map[sqlbase.ColumnID]int` with a `util.FastIntMap` in `pkg/sql`. It looks like `pkg/sql/opt` already does this and aliases `util.FastIntMap` to `ColMap`. We might consider sharing the same alias across these packages.

cc. @jordanlewis @RaduBerinde is there any reason that I'm missing not to do this?

**Comment by jordanlewis** [comment]
No, this generally seems like a pretty good idea to me.

**Comment by RaduBerinde** [comment]
In opt we would *really* like to have a version that uses ColumnID instead of int (casting is annoying and leads to occasional bugs which would have been caught by the type system). Last time we tried to write a wrapper, it was slower (some wrappers were not inlined); maybe this is better in more recent versions of Go.

**Comment by jordanlewis** [comment]
@RaduBerinde what do you mean by wrapper exactly? A thing that takes `ColumnID` and turns it into `int` to pass to the actual implementation?

We could use `execgen` to generate a couple of copies of `FastIntMap`, though this is pretty lame considering `ColumnID` is just an `int` under the hood...

**Comment by RaduBerinde** [comment]
Yeah, exactly. The wrapper would be another type and would have to reimplement all methods (passing them through with conversions). I was thinking about ColSet more than ColMap but I think it applies to both.

Yes, generating multiple versions is a possibility (though an annoying one).

**Comment by Hallicopter** [comment]
Is this being worked on? If not, I would like to help out, where could I get some context on this? Any resources? This is my first time here.

**Comment by nvanbenschoten** [comment]
@RaduBerinde We now have precedent for some minor generic container templating in https://github.com/cockroachdb/cockroach/tree/master/pkg/util/interval/generic.

Perhaps you could set that up to generate specialized `FastColumnIDSet` and `FastColumnIDMap` implementations and then have @Hallicopter help out with the refactor to start using these in SQL code.

**Comment by Hallicopter** [comment]
Would love to help in any way possible, thanks!
