### ISSUE TITLE
MakePriority scheme does not provide expected guarantee between non-1 priorities

### ISSUE THREAD

**Issue by yaojingguo** [cockroachdb/cockroach#3782]
MakePriority scheme does not provide expected guarantee between non-1 user priorities. As an example, someone with `user priority=1/4` will NEVER win against someone with `user priority=4` because the ranges don't overlap (low user priority will always choose below `2/5*max` and high user priority will always choose above `3/5*max`). User priority 1/4 should win `~1/16` of the time.

**Comment by RaduBerinde** [comment]
My comments in PR #3783:

> While this scheme generates the desired win/loss probabilities versus
> priority 1 it does NOT generate the desired probabilities between any
> priority values. As an example, someone with priority=1/4 will NEVER win
> against someone with priority=4 because the ranges don't overlap (low
> priority will always choose below 2/5*max and high priority will always
> choose above 3/5*max). The intention seems to be that it should win ~1/16
> of the time.

Proposed scheme is "return int32(math.Pow(rand.Float64(), 1.0/userPriority) * math.MaxInt32)"

**Comment by tschottdorf** [comment]
+1 if the math checks out (which it should)

**Comment by RaduBerinde** [comment]
The math works out for the x^1/pri scheme but for small priorities the generated values tend to be way too small (e.g. 0.9^1000 is ~2e-46) so we lose a lot when we map to integers. We can do something like x^0.01/pri scheme and that works better (the math works out just the same) but it's still not great and it results in large values (e.g. for priority 1, the values would usually be within 5-10% of MaxInt).

I found another scheme, based on the exponential distribution (for which rand already provides a generator). The math works out quite nicely, it is explained in code comments in PR #3910

**Comment by RaduBerinde** [comment]
Fixed in PR #3910
