### ISSUE TITLE
roachperf: compress stats.json files

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#37864]
The artifacts directories created nightly have been steadily growing in size which is leading to excessive disk usage on the shared host. We should increase the disk size on the shared host, but we should also compress the artifacts. Here are the directory sizes for the past few nights:

```
97M	20190517-1293898
27M	20190517-1294547
89M	20190518-1295056
98M	20190519-1295811
95M	20190520-1296592
32M	20190521-1298482
180M	20190522-1300930
157M	20190523-1303699
187M	20190524-1306250
```

Gzip'ing the stats.json files in `20190524-1306250` reduces the size of that directory to 11MB. Bzip'ing reduces the size to 7MB but was a lot slower.

I've freed up enough disk space on the shared host to give us breathing room for another week or so.

**Comment by ajwerner** [comment]
I can take a stab at storing and interacting with the data inside a compressed archive later this afternoon.
