### ISSUE TITLE
why only partition feature can not get different ranges?

### ISSUE THREAD

**Issue by leafji** [cockroachdb/cockroach#37878]
**Partition issue**

I would like to ask some question about Partition feature.
When I use Enterprise trial version to create a partition table, and SQL statement as below:

```
CREATE TABLE students (
id INT ,
country STRING,  
PRIMARY KEY (country))
PARTITION BY LIST (country) (
PARTITION north_america VALUES IN ('CA','US'),
PARTITION europe VALUES IN ('DE', 'CH'),
PARTITION australia VALUES IN ('AU','NZ'),
PARTITION DEFAULT VALUES IN (default)
);
```
this table has three partition when created, but i can't see any differ range from below query:

```
root@10.221.129.138:27257/defaultdb> SHOW EXPERIMENTAL_RANGES FROM TABLE students;
  start_key | end_key | range_id | replicas | lease_holder  
+-----------+---------+----------+----------+--------------+
  NULL      | NULL    |      148 | {1,2,3}  |            2  
```

however if i configure this tab-partition with a new zone using this sql:

_ALTER PARTITION north_america OF TABLE students CONFIGURE ZONE USING num_replicas=1;_

we will get differ ranges:

```
root@10.221.129.138:27257/defaultdb> SHOW EXPERIMENTAL_RANGES FROM TABLE students;
     start_key    |     end_key     | range_id | replicas | lease_holder  
+-----------------+-----------------+----------+----------+--------------+
  NULL            | /"CA"           |      157 | {1,2,3}  |            2  
  /"CA"           | /"CA"/PrefixEnd |      158 | {1}      |            1  
  /"CA"/PrefixEnd | /"US"           |      159 | {1,2,3}  |            2  
  /"US"           | /"US"/PrefixEnd |      160 | {1,2}    |            1  
  /"US"/PrefixEnd | NULL            |      171 | {1,2,3}  |            2  
(5 rows)

```
so, i want to ask one question: 

Only using partition feature can't  get different range. is that right ? If yes, how can i make a distinction between different partition? If not what 's the basic unit of partition in one table.

**Comment by ricardocrdb** [comment]
Hey @leafji 

I hope I can shed some light on how partitions work with ranges. A partition in CockroachDB is simply a label that gets added to certain rows. It's only when configuring replications zones where partitions can be leveraged to manipulate ranges as well. They describe this in a bit more detail on some of the documentation that can be found [here](https://www.cockroachlabs.com/docs/v19.1/partitioning.html#replication-zones).

As you alluded, configuring a replication zone using `CONFIGURE ZONE USING` is going to be how to control the partitions and their respective ranges. 

Let me know if you have any other questions.

Cheers,
Ricardo

**Comment by leafji** [comment]
Hey Ricardo:

Thanks your sharing, for more i want to ask why cockroach do not configure zone in create table stage?
such as below syntax as I think of:

```
CREATE TABLE students (
id INT ,
country STRING,  
PRIMARY KEY (country))
PARTITION BY LIST (country) (
PARTITION north_america VALUES IN ('CA','US')  **Locate in ....**,
PARTITION europe VALUES IN ('DE', 'CH') **Locate in ....,**,
PARTITION australia VALUES IN ('AU','NZ') **Locate in ....,**,
PARTITION DEFAULT VALUES IN (default) **Locate in ....**,
);

```
if do this, partition may be not a simply label then when it was created with table-creating stage.

Cheers,
leafji

**Comment by ricardocrdb** [comment]
Hey @leafji 

That's a great question. This feature is actually being reviewed and discussed in a different issue [37429](https://github.com/cockroachdb/cockroach/issues/37429). Since you have the answer to your questions, I will go ahead and close this issue out. Feel free to follow that issue for more info about configuring replication zones in the CREATE TABLE statement.

Cheers,
Ricardo
