### ISSUE TITLE
Nodes reported ready even if unreachable

### ISSUE THREAD

**Issue by sebastianblunt** [cockroachdb/cockroach#37899]
**Describe the problem**

If you have some cluster, and a "faulty" node that is able to connect to the cluster, but no node is able to connect to the faulty node (e.g. due to a misconfigured `--advertise-addr`, in my case it happened because of a DNS issue) then that faulty node will still be reported as ready even though it is unable to serve any queries.

**To Reproduce**

Start a new cluster:
```
cockroach start --insecure --listen-addr localhost
```
Start a second node that can reach the first, but where the first can't reach the new node.
```
cockroach start --store node-2 --insecure --listen-addr localhost:26258 --advertise-addr nonexistenthostname --join localhost --http-addr localhost:8081
```
The second node will join the first one, and both will show as Ready in the admin UI.
![Screen Shot 2019-05-28 at 4 27 23 PM](https://user-images.githubusercontent.com/47431204/58518830-a0257480-8165-11e9-8f4d-471cb9482269.png)

But notice that the new node has 0 replicas, it will never be able to sync.

The first node will show logs similar to
```
W190528 23:28:58.497408 2029 vendor/google.golang.org/grpc/clientconn.go:1304  grpc: addrConn.createTransport failed to connect to {nonexistenthostname:26258 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp: lookup nonexistenthostname: no such host". Reconnecting...
```

```
curl -v http://localhost:8081/health?ready=1
```
will return 200, but that node is not able to perform any queries:
```
> cockroach sql --host localhost:26258 --insecure
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.
#
# Server version: CockroachDB CCL v19.1.1 (x86_64-apple-darwin14, built 2019/05/15 20:21:46, go1.11.6) (same version as client)
# Cluster ID: 1c3b8d2c-f2d4-4204-aa01-4bfc998d0a3e
#
# Enter \? for a brief introduction.
#
root@localhost:26258/defaultdb> USE system;
SET

Time: 262µs

root@localhost:26258/system> SELECT * FROM users;
pq: no inbound stream connection // <- After waiting on a timeout
root@localhost:26258/system>
```

**Expected behavior**

The readiness check should return 503 if the node is not in a state where it is capable of doing anything.

**Environment:**
 - CockroachDB version: Tested on 19.1.0 and 19.1.1.
 - Server OS: Experienced on OS X and using the docker images
 - Client app: ^

**Additional context**

This is a problem because load balancers will send traffic to nodes that are not actually functioning.

**Comment by ricardocrdb** [comment]
Hello @sebastianblunt 

There is a GitHub issue for this that is already being worked on and tracked, which is issue # [36890](https://github.com/cockroachdb/cockroach/issues/36890). Please feel free to follow along on that issue and update there if necessary. I will go ahead and close this issue out.

Cheers,
Ricardo
