### ISSUE TITLE
Document usage of certificates

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#3792]
We should at the very least have the following:
* overview of cockroach security settings (insecure vs full certs: both client and server)
* for each `cockroach cert` command:
  * description of behavior
  * required files (eg: `create-node` and `create-client` need `ca.crt` and `ca.key`)
  * created files
  * equivalent openssl command and which fields are required for it to work

@mberhault will do a writeup and coordinate with @jseldess for integration into the docs.

**Comment by petermattis** [comment]
Moved to https://github.com/cockroachdb/docs/issues/45.
