### ISSUE TITLE
Track schema change rollbacks as jobs

### ISSUE THREAD

**Issue by roncrdb** [cockroachdb/cockroach#37937]
When a schema change is canceled and has to roll back, there's not a good way to track the progress of the rollback. This feature would let us track rollbacks using the jobs infrastructure so that users can understand the progress of these operations.

**Comment by tim-o** [comment]
Zendesk ticket #[3385](https://cockroachdb.zendesk.com/agent/tickets/3385) has been linked to this issue.

**Comment by jordanlewis** [comment]
Hey @spaskob, isn't this done?

**Comment by spaskob** [comment]
Yes it is! The rollback is part of the job now and is resumable/pausable and even cancellable.
