### ISSUE TITLE
Add node status to CLI

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#3794]
Paraphrasing @petermattis:

It'd be great if web UI stats (e.g. node stats) were also visible through the CLI.

I was thinking this would look like this:

`cockroach status nodes` would show the same metrics as the UI's Nodes tab

In the future, this could be extended as follows:

`cockroach status cluster`
`cockroach status databases`

**Comment by BramGruneir** [comment]
I like this idea.  Should be relatively easy to do.  Just look at the status endpoints.

**Comment by cuongdo** [comment]
Yes, the ease is why I'm tackling this first.

**Comment by petermattis** [comment]
I was thinking the structure would be inverted. Not quite sure why, that's just my natural inclination. 

```
cockroach nodes list
cockroach nodes stores
cockroach node status <nodeID>

cockroach stores list
cockroach store status <storeID>

cockroach cluster status

cockroach tables list [--user=...] [--database=...]
cockroach table schema <table-name>
cockroach table status <table-name>
```

**Comment by cuongdo** [comment]
Sounds reasonable. This matches the topology of the existing CLI commands, like user  and range.

I'm thinking that for 'cockroach node status', one would also be able to specify 'all' as the nodeID to get the same information you would get if you went to the nodes tab. Otherwise, a developer just starting out with CockroachDB would have to write a small shell script that listed the nodes, then ran 'node status' for all of those.
