### ISSUE TITLE
libroach: possibly missing directory sync for encryption at rest

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#37978]
[Noticed this in passing when inspecting the encryption at rest code for an unrelated purpose\.

The encryption at rest code persists a `COCKROACHDB_REGISTRY` file whenever a file is added or removed to the database. This is done with a `write+sync+rename` sequence in `SafeWriteStringToFile`:

```
rocksdb::Status SafeWriteStringToFile(rocksdb::Env* env, const std::string& filename,
                                      const std::string& contents) {
  std::string tmpname = filename + kTempFileNameSuffix;
  auto status = rocksdb::WriteStringToFile(env, contents, tmpname, true /* should_sync */);
  if (status.ok()) {
    status = env->RenameFile(tmpname, filename);
  }
  if (!status.ok()) {
    env->DeleteFile(tmpname);
  }
  return status;
}
```

Missing from the above is a sync of the parent directory. Without that sync, a restart could lose the rename operation.

It is possible that the directory sync isn't necessary here as we might already be covered by the directory syncs performed by RocksDB. If that is true, we should add a nice comment explaining that to `SafeWriteFileToString`.

**Comment by petermattis** [comment]
@sumeerbhola Can you take a look at this? It can likely be resolved quickly, either with a fix to the code, or an explanation of why the existing code is safe.

**Comment by sumeerbhola** [comment]
will do
