### ISSUE TITLE
opt: investigate a possible PushLimitIntoOffset rule

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#37980]
Currently, the most basic `LIMIT`/`OFFSET` query looks like this:
```
> explain (opt) select * from x limit 1 offset 2;
         text
+--------------------+
  limit
   ├── offset
   │    ├── scan x
   │    └── const: 2
   └── const: 1
(5 rows)
```

If we *don't* have an offset, then we push the `limit` operator into the scan itself:
```
> explain (opt) select * from x limit 1;
      text
+---------------+
  scan x
   └── limit: 1
(2 rows)
```

In the case where both the limit and offset have constant values (as they probably do in many common questionable pagination schemes), we can perform the following transformation:
```
(Limit
  (Offset
    $input
    (Const $offsetAmt)
  )
  (Const $limitAmt)
)
=>
(Offset
  (Limit
    $input
    (+ $offsetAmt $limitAmt)
  )
  $offsetAmt
)
```

Which gets the limit underneath the offset, and can give us a plan that looks more like this:
```
> explain (opt) select * from (select * from x limit 3) offset 2;
         text
+--------------------+
  offset
   ├── scan x
   │    └── limit: 3
   └── const: 2
(4 rows)
```
Which may or may not be preferable—I think investigation is required to determine if this is something we should do (maybe we only want to do it for scans).

**Comment by ridwanmsharif** [comment]
This is done by https://github.com/cockroachdb/cockroach/pull/38660 right? We could close this now.
