### ISSUE TITLE
pull request #37989 build error

### ISSUE THREAD

**Issue by leafji** [cockroachdb/cockroach#37994]
My pull request #37989 failed in GitHub CI (Cockroach):
https://teamcity.cockroachdb.com/viewLog.html?buildId=1321559&buildTypeId=Cockroach_UnitTests

I review the report and can not find out root reason about it,  all failed case are exit in Assert Workspace Clean stage, so how can I do about this? Is there any problem about my modification?

**Comment by tbg** [comment]
Hi @leafji, please ask these questions in the corresponding PR. I took a quick look and it seems that generated files weren't regenerated. This is typically done as part of `make build`, so see if that gives you a diff locally.
