### ISSUE TITLE
[Feature] cockroachdb router (like mysql-router) ?

### ISSUE THREAD

**Issue by kocoten1992** [cockroachdb/cockroach#38026]
Hi teams,

Mysql have `mysql-router`, serve as automatic database connector to `mysql innodb cluster`, I wonder if we have something like that ?

Ideally, deployment app will connect to localhost router, router will then route to cockroachdb node, when cockroachdb node go down, it should be transparent to application (router will route to another node automatically)

**Comment by ricardocrdb** [comment]
Hey @kocoten1992 

Sounds like you are referencing using a load balancer, which we discuss in our documentation pages at a very high level conceptually [here](https://www.cockroachlabs.com/docs/v19.1/cluster-topology-patterns.html). We also discuss a few specific load balancers as well, dependant on the cloud provider being used for the set of nodes you want to load balance. A few examples are the [GCP TCP Proxy Load Balancing](https://www.cockroachlabs.com/docs/v19.1/deploy-cockroachdb-on-google-cloud-platform.html#step-4-set-up-tcp-proxy-load-balancing) or the [AWS Load Balancer](https://www.cockroachlabs.com/docs/v19.1/deploy-cockroachdb-on-aws.html#step-4-set-up-load-balancing). You can also leverage [HAProxy](https://www.cockroachlabs.com/docs/v19.1/deploy-cockroachdb-on-premises-insecure.html#step-5-set-up-haproxy-load-balancers) yourself if you so choose.

Let me know if you have any other questions or concerns.

Cheers,
Ricardo
