### ISSUE TITLE
How can I debug cockroachDB? -- many goroutine jump each other

### ISSUE THREAD

**Issue by yangxuanjia** [cockroachdb/cockroach#38048]
When I use goland to debug cockroachDB,  many goroutine jump each other, pgwire goroutine and many internal goroutines jump each other,  it's disaster to me. 
I think may be cockroachDB has a knack whick I don't know, please tell me , please, please......

**Comment by ricardocrdb** [comment]
Hello @yangxuanjia 

I will do my best to help you out with your issue, but I would like to know is there a specific part of the cockroachDB that you are debugging? Is there a specific task or process that you are performing involving debugging? 

Cheers,
Ricardo

**Comment by yangxuanjia** [comment]
I debug conn.go, conn_executor.go, conn_executor_exec.go,  ohter file also has this proplem.
too many internal goroutines exec internal sql, it's terrible to debug code.

**Comment by yangxuanjia** [comment]
hello?

**Comment by leafji** [comment]
Our team also want to know how to do that?

**Comment by petermattis** [comment]
@yangxuanjia and @leafji you've asked a very general question that is extremely difficult to answer without more context. Yes, CockroachDB uses a lot of goroutines. Yes, debugging a distributed system as complex as CockroachDB is difficult. If you provide more specifics on what you're trying to debug, a more specific answer can be provided on what tools would be appropriate. In the meantime, see [How Cockroach Labs Debugs](https://www.cockroachlabs.com/docs/v19.1/training/how-cockroach-labs-debugs.html#main-content) for an overview of some tools and techniques we use.
