### ISSUE TITLE
core: metric for disk stall

### ISSUE THREAD

**Issue by DuskEagle** [cockroachdb/cockroach#38040]
In https://github.com/cockroachdb/cockroach/pull/36484, we changed the behavior of CockroachDB to log a warning when a disk stall is detected rather than crash.

In addition to the log message, it would be nice to have a count metric that reports when a disk stall is occurring, so this situation could be detected from a dashboard. Otherwise, it can be unclear what is wrong with a node without sifting through the logs. Since the ability to read or write to the log could also be affected by the disk stall, this metric could be the only way to detect the problem.

Even if the behavior is reverted so that a disk stall crashes CockroachDB, it would be nice if the disk stall metric was written after a few seconds, while the actual crash only occurred after a longer period of time (for example, the metric could be incremented after 10 seconds of disk stall, while Cockroach could be killed after only 120 seconds of disk stall, like it was before https://github.com/cockroachdb/cockroach/pull/36484).

**Comment by awoods187** [comment]
@andy-kimball this seems like a good project to pick up as a part of @andreimatei 's troubleshooting scope

**Comment by ajwerner** [comment]
I can pick this up, seems like something low risk we should try to slip into 19.2.
