### ISSUE TITLE
importccl: Secondary indexes broken in IMPORT INTO prototype

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#38044]
This a known-limitation of the WIP prototype, but breaking it out as there a plenty to discuss on this one.

If an a row in the importing data shadows an existing row (i.e. has same PK, so the key MVCC-shadows the prior key), currently AddSSTable's semantics mean we'll simply replace that row.

Replacing existing rows may or may not be the desired behavior in various cases of incremental import, but even when it it is, doing so poses a grave correctness problem with respect to secondary indexes, both non-unique and unique.

Typically when replacing a row (i.e. updating all its values) during normal UPDATE execution, we'd _read_ the prior values and the txn writing the updated row would also write  _replacements_ of the entires in secondary entires corresponding to its values -- i.e. deletions of the old entries and insertions of the new ones.

IMPORT easily creates new secondary index entires for the new rows it writes but part of what makes IMPORT so fast is that it does _not_ read existing rows and go row-by-row making its alterations to an existing DB -- it makes big, bulk batches of data an ingests them quickly. However in this case, doing that can leave orphaned index entries for values that have been replaced and result in invalid indexes (that contain too many entires).

Another issue arises with unique indexes where we generally expect to fail to to write a second entry for the same value. When blinding ingesting via AddSSTable, no conflict is raised on such a collision of an indexed value between two different rows and the opposite index problem happens: we end up with too few entries. This happens even without replacing a PK row, but rather when incorrectly replacing a unique secondary index row.

Thus replacement on both the PK and index data can create incorrect indexes. For tables with no secondary indexes, allowing the existing replacement behavior of AddSSTable is a potentially valid behavior -- we can just document that existing rows with the same PK are replaced -- but for tables with indexes, this is broken.

One option would be to disallow importing into a table with secondary indexes however this likely doesn't work for many or most users. 

A slightly better option might be to automatically drop indexes, then import and then automatically rebuild them before bringing the table back online. This may work for some use-cases, but for a very-large table, this could make using import-into actually much more expensive than just inserting for smaller amounts of data if it then has to rebuild the whole index.

We might be able to do a little better by optimistically just importing, then running validate on the indexes after. However this has a couple drawbacks: if they are found to be invalid, we need to drop and recreate them, and as before, this could be _very_ expensive depending on the table in question -- risking a massive index rebuild, which could mean effectively risking the table being unusable for some time depending on the application, might not be OK.

Even if we did this approach, unique indexes still pose an added wrinkle: if the newly imported rows added duplicate values, what happens? Does the index get dropped (since we can't rebuild it)? Do we need to drop all but one of the rows and/or null the offending values? If so, which, and how do we find them? In theory, we could find them via scanning the mvcc revisions on the duplicate index entries, though that would a) be new core functionality and b) require some more bookkeeping to protect them from GC in the meantime.

In either case, the risk of having to rebuild a massive index over the whole table when running any size of IMPORT still an issue, and will remain one as long as we might be creating orphans.

Another approach here might be to prevent the creation of orphans in the first place. That would involve ensuring that IMPORT INTO cannot change existing data, either in replacing an PK row or a unique index entry. This would likely involve augmenting AddSSTable to refuse to replace a key (i.e. write over it with a higher MVCC timestamp) -- in theory we could allow all the writes and search for duplicates after, but cleaning up after the fact might be harder in that case than simply preventing it in the first place (and, as above, we'd need to be sure we don't accidentally GC the original data before the cleanup de-shadowed it).

What this might end up looking like is:
a) regular incremental import fails on any duplicates (same pk or unique values)*
b) value-replacing incremental import is only available via a flag, and is only allowed when on tables with no secondary indexes (you can choose to drop and re-add indexes to use it you want to pay that cost)

* Note: this still doesn't solve the problem of detecting a collision too late, but it does limit it to unique indexes and catches it, hopefully, sooner, but we still need to think about, in general, handling rollbacks and ensuring the existing data sticks around until we're sure we don't rollback.

**Comment by dt** [comment]
@adityamaru27 we can close this, right?

**Comment by adityamaru27** [comment]
yes #39152 resolves this.
