### ISSUE TITLE
Cannot use UNNEST() in INSERT statement

### ISSUE THREAD

**Issue by xudongzheng** [cockroachdb/cockroach#38060]
**Is your feature request related to a problem? Please describe.**

It does not seem possible to insert using an array and UNNEST()

```
CREATE TABLE test (id int);
INSERT INTO test VALUES (UNNEST(ARRAY[1,2]::int[]));
```

Running the above command gives the error "pq: unnest(): generator functions are not allowed in VALUES"

**Comment by justinj** [comment]
Hi @xudongzheng,

I think what you're looking for is:
```
INSERT INTO test SELECT * FROM UNNEST(ARRAY[1,2]::int[]);
```
does that do what you want?

**Comment by xudongzheng** [comment]
Thank you. It didn't occur to me to do that. I ended up doing `SELECT UNNEST(...)` directly so there can be multiple array variables.
