### ISSUE TITLE
opt: add support for histograms 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#38082]
Histograms are an important input into a mature cost model for a CBO. The CBO can make inaccurate cost estimates without the data from histograms of each operator resulting in poor performance.

This issue tracks the implementation of histograms:

- [x] Creation of histograms for table data as part of statistics collection
- [x] Logic to estimate histograms for the output of each relational operator, given histogram data from the tables
- [x] Histogram testing to tune the CBO.

**Comment by mgartner** [comment]
The CBO has been using histograms for several releases. Closing.
