### ISSUE TITLE
ui: still logged in & working after deleting SQL user

### ISSUE THREAD

**Issue by vilterp** [cockroachdb/cockroach#38081]
**To Reproduce**

1. log in to the admin UI
2. delete the SQL user you are logged in as

**Expected behavior**
UI stops functioning, because its API calls no longer succeed, because they can't authenticate, because the session no longer exists, because the user it is for has been deleted.

**Actual Behavior**

UI continues to function.

**Workaround**

I believe a root user could revoke access by deleting the row in the sessions table corresponding to the deleted user.

**Fix**

When deleting a SQL user, delete all sessions for them.

discovered by @joshimhoff and @DuskEagle 

Jira issue: CRDB-5652

**Comment by andreimatei** [comment]
@vilterp please put a project on this sucker
