### ISSUE TITLE
distsql: Aggregate window function on NULL values

### ISSUE THREAD

**Issue by ridwanmsharif** [cockroachdb/cockroach#38103]
Consider the following table composition:
```
   col
+------+
     5
     4
     3
     2
     1
  NULL
(6 rows)
```
As we see, the min value is 1:
```
root@127.0.0.1:52658/defaultdb> SELECT min(col) FROM tab;
  min
+-----+
    1
(1 row)
```

However when the min aggregate is run as a window function we get NULL:
```
root@127.0.0.1:52658/defaultdb> SELECT DISTINCT min(col) OVER () FROM tab;
  min
+-----+
    NULL
(1 row)
```

Found this when debugging aggregates built using window functions for ordered aggregations (https://github.com/cockroachdb/cockroach/pull/38014). I confirmed this is a bug by comparing against postgres.

**Comment by justinj** [comment]
This strikes me as an execution bug—happens with the optimizer disabled as well:
```
root@127.0.0.1:57296/defaultdb> select min(a) over () from x;
  min
+------+
  NULL
  NULL
  NULL
  NULL
(4 rows)

Time: 1.568ms

root@127.0.0.1:57296/defaultdb> set optimizer = off;
SET

Time: 314µs

root@127.0.0.1:57296/defaultdb> select min(a) over () from x;
  min
+------+
  NULL
  NULL
  NULL
  NULL
(4 rows)

Time: 835µs
```

Going to assign to @yuzefovich, feel free to send back if you disagree!

**Comment by yuzefovich** [comment]
Yes, this is definitely an execution bug, thanks for finding!
