### ISSUE TITLE
sql:unable to delete rows with self-referring keys

### ISSUE THREAD

**Issue by RPIguitarhero** [cockroachdb/cockroach#38121]
When trying to delete rows with self-referring keys, the
```
CREATE TABLE user_Event (
  id INT PRIMARY KEY,
  parent INT REFERENCES user_Event(id),
  u_id INT FOREIGN KEY REFERENCES users(u_id)
);
INSERT INTO user_Event (id, parent, u_id) VALUES (1, NULL, 20);
INSERT INTO user_Event (id, parent, u_id) VALUES (2, 1, 20);
INSERT INTO user_Event (id, parent, u_id) VALUES (3, 1, 21);
INSERT INTO user_Event (id, parent, u_id) VALUES (4, 2, 20);
INSERT INTO user_Event (id, parent, u_id) VALUES (5, 3, 21);
DELETE FROM test;
```

These lines have executed on my previous SQL server, but an error prompt was received when running on CockroachDB:
`pq: foreign key violation: values [1] in columns [id] referenced in table "test"`

**Comment by jordanlewis** [comment]
Hi @RPIguitarhero, thanks for the report. This is a known limitation in 19.1 that will be lifted in 19.2, once the optimizer plans foreign key checks.

**Comment by RaduBerinde** [comment]
The optimizer will plan foreign key checks by default in 20.1 (unless cascades are in play, we are planning to address that in the following release).
