### ISSUE TITLE
Certificate validation error when using intermediate CA certificates

### ISSUE THREAD

**Issue by timaa2k** [cockroachdb/cockroach#38146]
**Describe the problem**

There is a regression in CockroachDB 2.1.x: TLS artifacts (certificate and key files) that worked with 2.0.7 and stopped working with 2.1.7.

We're deploying CockroachDB with a custom `client.root.crt` certificate signed by an intermediate CA certificate.
To create a valid certificate chain for authentication the `client.root.crt` file contains the end entity certificate with `CN=root` followed by the intermediate CA certificates with their own CN's.
This TLS artifact configuration for CockroachDB worked for us with 2.0 but stopped working with 2.1.

We see the following error with CockroachDB 2.1.7:

```
W190612 13:25:01.490332 1 security/certificate_loader.go:331  could not parse certificate for /run/dcos/pki/cockroach/client.root.crt: failed to validate certificate 1 in file client.root.crt: client certificate has Subject "CN=Integration Test Intermediate CA 02", expected "CN=root" (must match filename)
Error: connections with user root must use a client certificate
```

We've figured out that the reason our configuration stopped working was introduced with PR #24687.
CockroachDB's own SQL client now checks for the CN field for each certificate in the certificate chain in `client.root.crt` file to match the user name `root`.

Notably, this error does not seem to happen as part of a TLS handshake, but merely as part of a well-intended configuration validation check.
Once we removed the validation CockroachDB 2.1 works just as well as 2.0 did for our configuration.

```
diff --git a/pkg/security/certificate_loader.go b/pkg/security/certificate_loader.go
index 25a72bcf7e..def0fa9ff7 100644
--- a/pkg/security/certificate_loader.go
+++ b/pkg/security/certificate_loader.go
@@ -416,9 +416,6 @@ func parseCertificate(ci *CertInfo) error {
 			return makeErrorf(err, "failed to parse certificate %d in file %s", i, ci.Filename)
 		}
 
-		if err := validateCockroachCertificate(ci, x509Cert); err != nil {
-			return makeErrorf(err, "failed to validate certificate %d in file %s", i, ci.Filename)
-		}
 		if i == 0 {
 			// The first certificate is the effective one; use its expiration time.
 			expires = x509Cert.NotAfter
```

Details of any intermediate certificate should not be validated for these fields as there is no way to know in advance what the CN (and other details) should be.
The expected behavior would be to only check the CN field of the first certificate of the chain (`end entity certificate`), if anything.

In case of using a root certificate and no intermediate certificates to sign the client certificate CockroachDB 2.1.7 behaves correctly.
In that case `client.root.crt` only contains a single certificate with `CN` set to `root`.

**To Reproduce**

We are not providing a full reproduction because this is a lot of effort and we believe that the description may be clear enough for the problem to be understood.
However, if the description is not clear enough for a change to be made, we will create and share such a reproduction.

**Expected behavior**

We expected no error to be shown for the described configuration.

**Environment:**

 - CockroachDB version [e.g. 2.1.7] (we expect that this is also an issue in more recent versions, given code we have read)
 - Server OS: [e.g. CentOS 7] (we expect this to not be relevant)
 - Client app [`cockroach sql`]

**Additional context**

We cannot update DC/OS Enterprise to a recent CockroachDB version without a patch.
This is because one cannot access the database of a secure CockroachDB cluster with an intermediate certificate.

**Comment by mberhault** [comment]
Good catch, fix is on the way.
In the meantime, could you try adding the intermediate to the `ca.crt` and removing it from the client certs? That should work, but I haven't tested it.

**Comment by timaa2k** [comment]
Hey thank you @mberhault! We're aware that this would probably work but we would like to avoid this.

**Comment by mberhault** [comment]
This is merged and backported to the 2.1 and 19.1 branches. It should be included in 2.1.8 and 19.1.3 (too late for 19.1.2).

**Comment by timaa2k** [comment]
Cool, we really appreciate the fast turnaround on this one! Is there any ETA / minor version release schedule for 2.1.8? The past 2.1 minor versions seem to have a 1-2 month cycle.

**Comment by mberhault** [comment]
We don't have an exact release date yet, but 2.1.7 is from early May and we've accumulated a few patches.
@bdarnell may have more information.

**Comment by bdarnell** [comment]
19.1.2 just went out today; the next release 19.1.3 is scheduled for 4 weeks from now (8/15). We'll do 2.1.8 at the same time.

**Comment by jgehrcke** [comment]
Thanks for the quick fix also from my side.

**Comment by mberhault** [comment]
19.1.3 and 2.1.8 containing this fix were just released. You should now be able to provide a certificate chain, only the first certificate in the file will need to have the expected `CN`.

Thank you for your patience.
