### ISSUE TITLE
simple rules based warning for poor schema design

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/cockroach#38145]
**Is your feature request related to a problem? Please describe.**

The following are simple cases where AdminUI can be setup to provide alerts:

- no matching index on predicate
- no primary key when unique exists

Customers currently contact CRL for bad performance / scalability where the fix is simple,.  If the help is not provided or not provided in time, customer experience frustration and delays adoption of CockroachDB.

**Describe the solution you'd like**

AdminUI displays warning messages indicating schema may not be optimal 

**Describe alternatives you've considered**

**Additional context**

Below is an example of P99 latency where there is no matching index on predicate while more and more data is being added.

<img width="773" alt="Screen Shot 2019-06-13 at 10 03 05 AM" src="https://user-images.githubusercontent.com/6315124/59439068-9422ef00-8dc2-11e9-9521-af16a6390279.png">

**Comment by awoods187** [comment]
I love this idea! I think @rolandcrosby and I discussed something similar a few months back but we haven't investigated it much.

**Comment by jordanlewis** [comment]
> no primary key when unique exists

@robert-s-lee what do you mean by this?

**Comment by awoods187** [comment]
@jordanlewis pointed me to the ui having some warning today:
![image](https://user-images.githubusercontent.com/22278911/59727843-74962700-9205-11e9-9f7d-af1aba364e36.png)
However that requires you to click into the plan and notice the warning--two things that users might not know to do, especially if they are having full table scans. 

We could consider upleveling this warning and pairing it with the one discussed by @robert-s-lee above.

CC @piyush-singh

**Comment by robert-s-lee** [comment]
The table did not have a primary key define; however, there were two unique keys.  One of the unique was setup as primary which happen to match the where clause.  A unique key can serve as the primary if the primary key is not defined.
