### ISSUE TITLE
Using Helm to deploy secure cluster fails

### ISSUE THREAD

**Issue by jvhops** [cockroachdb/cockroach#38148]
Using 
https://github.com/helm/charts/tree/master/stable/cockroachdb
 Helm chart fails when using cockroachdb-statefulset-secure.yaml (provided by sales engineer). Installing an insecure cluster works fine. I used the RBAC setup and secure mode and the init process fails to complete. We are using Jenkins to run helm install. I will attach console output from the Jenkins job. Jenkins calls the script deploy-helm-chart-to-region.sh which i will attach also.
[deploy-helm-chart-to-region.txt](https://github.com/cockroachdb/cockroach/files/3287999/deploy-helm-chart-to-region.txt)
[cockroachdb-statefulset-secure.yaml.txt](https://github.com/cockroachdb/cockroach/files/3288020/cockroachdb-statefulset-secure.yaml.txt)

[Jenkins#23.txt](https://github.com/cockroachdb/cockroach/files/3287984/Jenkins.23.txt)

**Comment by joshimhoff** [comment]
Need more info on why the pods are pending. Can you  run `kubectl describe pods cockroachdb-0` and paste output here? https://kubernetes.io/docs/tasks/debug-application-cluster/debug-application/ is a good read too. 

Also, on what kind of k8s cluster are you running this? GKE? EKS? If something custom, can you describe it?

Thanks!

**Comment by jvhops** [comment]
I can use the default files in the helm chart and the install does create pods - however the ca.key file is not created nor is a client cert for the root account which according to the docs is supposed to get created during secure install/startup

jhopsmbpx1:templates jhops$ kubectl get pods -n stage|grep cockroach
stage-cockroachdb-cockroachdb-0                        1/1       Running     0          1h
stage-cockroachdb-cockroachdb-1                        1/1       Running     0          1h
stage-cockroachdb-cockroachdb-2                        1/1       Running     0          1h
stage-cockroachdb-cockroachdb-init-spct5               0/1       Completed   0          1h
jhopsmbpx1:templates jhops$ kubectl -n stage exec -it stage-cockroachdb-cockroachdb-0 /bin/bash
root@stage-cockroachdb-cockroachdb-0:/cockroach# cd /cockroach/cockroach-certs
root@stage-cockroachdb-cockroachdb-0:/cockroach/cockroach-certs# ls
ca.crt	ca.key	node.crt  node.key

**Comment by jvhops** [comment]
~$ cockroach sql --host=10.22.193.175 --certs-dir /cockroach/cockroach-certs
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.
#
Error: connections with user root must use a client certificate
Failed running "sql"

**Comment by jvhops** [comment]
jhopsmbpx1:~ jhops$ kubectl describe pods stage-cockroachdb-cockroachdb-0 -n stage
Name:               stage-cockroachdb-cockroachdb-0
Namespace:          stage
Priority:           0
PriorityClassName:  <none>
Node:               gke-allaccess-domestic-de-preview-api-120734eb-nbhx/10.22.192.34
Start Time:         Thu, 13 Jun 2019 17:39:20 -0700
Labels:             chart=cockroachdb-2.1.3
                    component=stage-cockroachdb-cockroachdb
                    controller-revision-hash=stage-cockroachdb-cockroachdb-55c4467485
                    heritage=Tiller
                    release=stage-cockroachdb
                    statefulset.kubernetes.io/pod-name=stage-cockroachdb-cockroachdb-0
Annotations:        <none>
Status:             Running
IP:                 10.8.44.28
Controlled By:      StatefulSet/stage-cockroachdb-cockroachdb
Init Containers:
  init-certs:
    Container ID:  docker://d16acf3418f81d560f8bda297aa73242738de4e212d6733594a84f1b11383b6a
    Image:         cockroachdb/cockroach-k8s-request-cert:0.4
    Image ID:      docker-pullable://cockroachdb/cockroach-k8s-request-cert@sha256:d512bc05c482a1c164544e68299ff7616d4a26325ac9aa2c2ddce89bc241c792
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/ash
      -ecx
      /request-cert -namespace=${POD_NAMESPACE} -certs-dir=/cockroach-certs -type=node -addresses=localhost,127.0.0.1,$(hostname -f),$(hostname -f|cut -f 1-2 -d '.'),stage-cockroachdb-cockroachdb-public,stage-cockroachdb-cockroachdb-public.$(hostname -f|cut -f 3- -d '.') -symlink-ca-from=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 13 Jun 2019 17:39:40 -0700
      Finished:     Thu, 13 Jun 2019 17:39:40 -0700
    Ready:          True
    Restart Count:  0
    Environment:
      POD_NAMESPACE:  stage (v1:metadata.namespace)
    Mounts:
      /cockroach-certs from certs (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from stage-cockroachdb-cockroachdb-token-dx9b4 (ro)
Containers:
  stage-cockroachdb-cockroachdb:
    Container ID:  docker://e1a4349ea03ac435370fa00f4688a664238fdad4ccaa235a8a2afcde940a0a3b
    Image:         cockroachdb/cockroach:v19.1.0
    Image ID:      docker-pullable://cockroachdb/cockroach@sha256:bcf114228b981b4c2a958407164415089c71f60ba745442a46fdf764b55e137d
    Ports:         26257/TCP, 8080/TCP
    Host Ports:    0/TCP, 0/TCP
    Command:
      /bin/bash
      -ecx
      exec /cockroach/cockroach start --logtostderr --certs-dir /cockroach/cockroach-certs --advertise-host $(hostname).${STATEFULSET_FQDN} --http-host 0.0.0.0 --http-port 8080 --port 26257 --cache 25% --max-sql-memory 25%  --join ${STATEFULSET_NAME}-0.${STATEFULSET_FQDN}:26257,${STATEFULSET_NAME}-1.${STATEFULSET_FQDN}:26257,${STATEFULSET_NAME}-2.${STATEFULSET_FQDN}:26257
    State:          Running
      Started:      Thu, 13 Jun 2019 17:39:41 -0700
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     16
      memory:  32Gi
    Requests:
      cpu:      2
      memory:   4Gi
    Liveness:   http-get https://:http/health delay=30s timeout=1s period=5s #success=1 #failure=3
    Readiness:  http-get https://:http/health%3Fready=1 delay=10s timeout=1s period=5s #success=1 #failure=2
    Environment:
      STATEFULSET_NAME:   stage-cockroachdb-cockroachdb
      STATEFULSET_FQDN:   stage-cockroachdb-cockroachdb.stage.svc.cluster.local
      COCKROACH_CHANNEL:  kubernetes-helm
    Mounts:
      /cockroach/cockroach-certs from certs (rw)
      /cockroach/cockroach-data from datadir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from stage-cockroachdb-cockroachdb-token-dx9b4 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  datadir:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  datadir-stage-cockroachdb-cockroachdb-0
    ReadOnly:   false
  certs:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:  
  stage-cockroachdb-cockroachdb-token-dx9b4:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  stage-cockroachdb-cockroachdb-token-dx9b4
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>
jhopsmbpx1:~ jhops$

**Comment by jvhops** [comment]
The pods are deployed in GCP gke using the helm chart downloaded from your
repo. We are using Jenkins to basically run helm install/upgrade

**Comment by joshimhoff** [comment]
> however the ca.key file is not created

There should NOT be a ca.key in /cockroach-certs. There should just be a public key (ca.crt).

> nor is a client cert for the root account which according to the docs is supposed to get created during secure install/startup

This surprises me. Can you please try deleting a single crdb pod? It should come right back up so long as you don't delete the statefulset. I am wondering if the cluster_init Job creates the root client certs. If so, maybe we just need to rerun the init container for the crdb pods. This should do the trick:

`kubectl delete pod/stage-cockroachdb-cockroachdb-0 -n stage`

After the pod comes up, can you check if the root cert and key are in /cockroach-certs by execing into the pod you delete?

Also, can you run the following command?

`kubectl get csr -n stage`

One last thing to try is to create a pod specifically for doing SQL client stuff. See instructions here:

https://www.cockroachlabs.com/docs/stable/orchestrate-cockroachdb-with-kubernetes.html#step-3-use-the-built-in-sql-client

You might need to approve a CSR after creating the client pod.

If those don't have client cert and key loaded, something is very  wrong.

**Comment by drewdeally** [comment]
Jamie please respond to Josh above - I have a 2nd question.  Earlier this week you had this issue

stage-cockroachdb-cockroachdb-0               0/1       Pending     0          21h
stage-cockroachdb-cockroachdb-1               0/1       Pending     0          21h
stage-cockroachdb-cockroachdb-2               0/1       Pending     0          21h
stage-cockroachdb-cockroachdb-init-vkvsm      1/1       Running     0          21h

cluster nodes stuck in a pending state with init running but not completing

what did you change to ge to the state

jhopsmbpx1:templates jhops$ kubectl get pods -n stage|grep cockroach
stage-cockroachdb-cockroachdb-0 1/1 Running 0 1h
stage-cockroachdb-cockroachdb-1 1/1 Running 0 1h
stage-cockroachdb-cockroachdb-2 1/1 Running 0 1h
stage-cockroachdb-cockroachdb-init-spct5 0/1 Completed 0 1h

**Comment by drewdeally** [comment]
PLEASE RUN THIS COMMAND
kubectl get pods -n stage|grep root
default.client.root

confirm it exists

then download 

curl -OOOOOOOOO https://raw.githubusercontent.com/cockroachdb/cockroach/master/cloud/kubernetes/client-secure.yaml

modify service name to stage-cockroachdb-cockroachdb

kubectl create -f client-secure.yaml

kubectl exec -it cockroachdb-client-secure -- bash 

and list contents of /cockroach-certs

**Comment by joshimhoff** [comment]
> nor is a client cert for the root account which according to the docs is supposed to get created during secure install/startup

Actually, this is also expected. Thanks, @drewdeally, for figuring this out. The root client certs will only be used by the init cluster job, which has already run, and the client pod. See Drew's message which is above and describes how to create the client pod.

**Comment by jvhops** [comment]
The pods get created and the cluster is up, however not all the certs get created. Only the ca.crt and node.crt and node.key files are on the pods. I cant run cockroach cert create-ca because the ca.crt file exists, and I cant run create-client because ca.key file does not exist

**Comment by jvhops** [comment]
OK I missed some updates. Confirm that the client certs only get created on the init pod?

jhopsmbpx1:cbssre-cockroachdb-helm jhops$ kubectl get pods -n stage|grep root
jhopsmbpx1:cbssre-cockroachdb-helm jhops$ kubectl get pods -n stage|grep cockroach
stage-cockroachdb-cockroachdb-0                        1/1       Running     0          21h
stage-cockroachdb-cockroachdb-1                        1/1       Running     0          21h
stage-cockroachdb-cockroachdb-2                        1/1       Running     0          21h
stage-cockroachdb-cockroachdb-init-pr26c               0/1       Completed   0          21h
jhopsmbpx1:cbssre-cockroachdb-helm jhops$ kubectl exec -it stage-cockroachdb-cockroachdb-init-pr26c /bin/bash
Error from server (NotFound): pods "stage-cockroachdb-cockroachdb-init-pr26c" not found

What we changed was using the template/cockroachdb-statefulset.yaml instead of statefulset-secure.yaml to get the pods to deploy

**Comment by jvhops** [comment]
The root certs have not been on any of the pods thus so far.

**Comment by drewdeally** [comment]
Jamie.   The problem is that a few steps are mixed between method.  Please redeploy with the helm upgrade passing the flag i sent earlier which is a parameter in your Jenkins scripts.  Please recheck you have specify use of the secure setup in the helm command.

**Comment by drewdeally** [comment]
Can you run the following command 

kubectl exec -it stage-cockroachdb-cockroachdb-0 -- ls cockroach-certs
kubectl exec -it stage-cockroachdb-cockroachdb-1 -- ls cockroach-certs
kubectl exec -it stage-cockroachdb-cockroachdb-2 -- ls cockroach-certs

if those show certs 
ca.crt	node.crt  node.key

then run the following commands


curl -OOOOOOOOO https://raw.githubusercontent.com/cockroachdb/cockroach/master/cloud/kubernetes/client-secure.yaml

modify service name to stage-cockroachdb-cockroachdb

kubectl create -f client-secure.yaml

kubectl exec -it cockroachdb-client-secure --  -- ls /cockroach-certs

here is example following your Jenkins scripts and charts you sent in a zip
helm upgrade --install drew -f values.yaml .

kubectl certificate approve default.node.cockroachdb-0
kubectl certificate approve default.node.cockroachdb-1
kubectl certificate approve default.node.cockroachdb-2

kubectl exec -it cockroachdb-0   -- ls cockroach-certs
ca.crt	node.crt  node.key
kubectl exec -it cockroachdb-1   -- ls cockroach-certs
ca.crt	node.crt  node.key





kubectl exec -it cockroachdb-client-secure   -- ls /cockroach-certs
ca.crt	client.root.crt  client.root.key


make sure if you are not passing **Secure.Enabled** in values

in your **values.yaml_dev-domestic**

set this

Secure:
  Enabled: false
  RequestCertsImage: "cockroachdb/cockroach-k8s-request-cert"
  RequestCertsImageTag: "0.4"


to 


Secure:
  **Enabled: true**
  RequestCertsImage: "cockroachdb/cockroach-k8s-request-cert"
  RequestCertsImageTag: "0.4"

**Comment by drewdeally** [comment]
Resolved

**Comment by marckan24** [comment]
@drewdeally i have a similar issue when using the helm chart for cockroachdb the job is crashing and node 0 and 1 are crashing
here the describe of the pod
$ kubectl describe pods crdb-cockroachdb-0 -n cockroachdb-os
Name:               crdb-cockroachdb-0
Namespace:          cockroachdb-os
Priority:           0
PriorityClassName:  <none>
Node:               dev-558gq-worker-eastus2-wz8tx/10.23.72.37
Start Time:         Wed, 06 May 2020 11:01:40 -0400
Labels:             app.kubernetes.io/component=cockroachdb
                    app.kubernetes.io/instance=crdb
                    app.kubernetes.io/name=cockroachdb
                    controller-revision-hash=crdb-cockroachdb-5d6c46997c
                    statefulset.kubernetes.io/pod-name=crdb-cockroachdb-0
Annotations:        openshift.io/scc: restricted
Status:             Pending
IP:                 172.16.8.107
Controlled By:      StatefulSet/crdb-cockroachdb
Init Containers:
  init-certs:
    Container ID:  cri-o://fd658313618531c871ad885c5c8e90818ca43b55f8f74d74e9839b88908b5377
    Image:         cockroachdb/cockroach-k8s-request-cert:0.4
    Image ID:      docker.io/cockroachdb/cockroach-k8s-request-cert@sha256:d512bc05c482a1c164544e68299ff7616d4a26325ac9aa2c2ddce89bc241c792
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/ash
      -ecx
      /request-cert -namespace=${POD_NAMESPACE} -certs-dir=/cockroach-certs/ -symlink-ca-from=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt -type=node -addresses=localhost,127.0.0.1,$(hostname -f),$(hostname -f|cut -f 1-2 -d '.'),crdb-cockroachdb-public,crdb-cockroachdb-public.$(hostname -f|cut -f 3- -d '.')
    State:          Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Wed, 06 May 2020 11:09:37 -0400
      Finished:     Wed, 06 May 2020 11:09:37 -0400
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Wed, 06 May 2020 11:08:45 -0400
      Finished:     Wed, 06 May 2020 11:08:45 -0400
    Ready:          False
    Restart Count:  4
    Environment:
      POD_NAMESPACE:  cockroachdb-os (v1:metadata.namespace)
    Mounts:
      /cockroach-certs/ from certs (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from crdb-cockroachdb-token-k2gt8 (ro)
Containers:
  db:
    Container ID:  
    Image:         cockroachdb/cockroach:v19.2.6
    Image ID:      
    Ports:         26257/TCP, 8080/TCP
    Host Ports:    0/TCP, 0/TCP
    Args:
      shell
      -ecx
      exec /cockroach/cockroach start --join=${STATEFULSET_NAME}-0.${STATEFULSET_FQDN}:26257,${STATEFULSET_NAME}-1.${STATEFULSET_FQDN}:26257,${STATEFULSET_NAME}-2.${STATEFULSET_FQDN}:26257 --advertise-host=$(hostname).${STATEFULSET_FQDN} --logtostderr=INFO --certs-dir=/cockroach/cockroach-certs/ --http-port=8080 --port=26257 --cache=25% --max-disk-temp-storage=0 --max-offset=500ms --max-sql-memory=25%
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Liveness:       http-get https://:http/health delay=30s timeout=1s period=5s #success=1 #failure=3
    Readiness:      http-get https://:http/health%3Fready=1 delay=10s timeout=1s period=5s #success=1 #failure=2
    Environment:
      STATEFULSET_NAME:   crdb-cockroachdb
      STATEFULSET_FQDN:   crdb-cockroachdb.cockroachdb-os.svc.cluster.local
      COCKROACH_CHANNEL:  kubernetes-helm
    Mounts:
      /cockroach/cockroach-certs/ from certs (rw)
      /cockroach/cockroach-data/ from datadir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from crdb-cockroachdb-token-k2gt8 (ro)
Conditions:
  Type              Status
  Initialized       False 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  datadir:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  datadir-crdb-cockroachdb-0
    ReadOnly:   false
  certs:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  crdb-cockroachdb-token-k2gt8:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  crdb-cockroachdb-token-k2gt8
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age                   From                                     Message
  ----     ------                  ----                  ----                                     -------
  Normal   Scheduled               8m6s                  default-scheduler                        Successfully assigned cockroachdb-os/crdb-cockroachdb-0 to dev-558gq-worker-eastus2-wz8tx
  Warning  FailedMount             3m46s (x2 over 6m3s)  kubelet, dev-558gq-worker-eastus2-wz8tx  Unable to mount volumes for pod "crdb-cockroachdb-0_cockroachdb-os(772dfd1f-8faa-11ea-bce1-000d3a1fb080)": timeout expired waiting for volumes to attach or mount for pod "cockroachdb-os"/"crdb-cockroachdb-0". list of unmounted volumes=[datadir]. list of unattached volumes=[datadir certs crdb-cockroachdb-token-k2gt8]
  Normal   SuccessfulAttachVolume  118s                  attachdetach-controller                  AttachVolume.Attach succeeded for volume "pvc-772bc57a-8faa-11ea-bce1-000d3a1fb080"
  Normal   Pulled                  9s (x5 over 104s)     kubelet, dev-558gq-worker-eastus2-wz8tx  Container image "cockroachdb/cockroach-k8s-request-cert:0.4" already present on machine
  Normal   Created                 9s (x5 over 104s)     kubelet, dev-558gq-worker-eastus2-wz8tx  Created container init-certs
  Normal   Started                 9s (x5 over 104s)     kubelet, dev-558gq-worker-eastus2-wz8tx  Started container init-certs
  Warning  BackOff                 8s (x9 over 102s)     kubelet, dev-558gq-worker-eastus2-wz8tx  Back-off restarting failed container


$ kubectl describe pods crdb-cockroachdb-init-dhpdf -n cockroachdb-os
Name:               crdb-cockroachdb-init-dhpdf
Namespace:          cockroachdb-os
Priority:           0
PriorityClassName:  <none>
Node:               dev-558gq-worker-eastus1-4q7zj/10.23.72.36
Start Time:         Wed, 06 May 2020 11:06:03 -0400
Labels:             app.kubernetes.io/component=init
                    app.kubernetes.io/instance=crdb
                    app.kubernetes.io/name=cockroachdb
                    controller-uid=77457d7e-8faa-11ea-ae88-000d3a1fb41f
                    job-name=crdb-cockroachdb-init
Annotations:        openshift.io/scc: restricted
Status:             Pending
IP:                 172.16.10.101
Controlled By:      Job/crdb-cockroachdb-init
Init Containers:
  init-certs:
    Container ID:  cri-o://11e0a3bec7f38af76676137bc55fb2a9cf7f2d73dc7498ee894e7fd62f5ba34c
    Image:         cockroachdb/cockroach-k8s-request-cert:0.4
    Image ID:      docker.io/cockroachdb/cockroach-k8s-request-cert@sha256:d512bc05c482a1c164544e68299ff7616d4a26325ac9aa2c2ddce89bc241c792
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/ash
      -ecx
      /request-cert -namespace=${POD_NAMESPACE} -certs-dir=/cockroach-certs/ -symlink-ca-from=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt -type=client -user=root
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Wed, 06 May 2020 11:09:07 -0400
      Finished:     Wed, 06 May 2020 11:09:07 -0400
    Ready:          False
    Restart Count:  5
    Environment:
      POD_NAMESPACE:  cockroachdb-os (v1:metadata.namespace)
    Mounts:
      /cockroach-certs/ from client-certs (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from crdb-cockroachdb-token-k2gt8 (ro)
Containers:
  cluster-init:
    Container ID:  
    Image:         cockroachdb/cockroach:v19.2.6
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/bash
      -c
      while true; do initOUT=$(set -x; /cockroach/cockroach init --certs-dir=/cockroach-certs/ --host=crdb-cockroachdb-0.crdb-cockroachdb:26257 2>&1); initRC="$?"; echo $initOUT; [[ "$initRC" == "0" ]] && exit 0; [[ "$initOUT" == *"cluster has already been initialized"* ]] && exit 0; sleep 5; done
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /cockroach-certs/ from client-certs (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from crdb-cockroachdb-token-k2gt8 (ro)
Conditions:
  Type              Status
  Initialized       False 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  client-certs:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  crdb-cockroachdb-token-k2gt8:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  crdb-cockroachdb-token-k2gt8
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                    From                                     Message
  ----     ------     ----                   ----                                     -------
  Normal   Scheduled  5m31s                  default-scheduler                        Successfully assigned cockroachdb-os/crdb-cockroachdb-init-dhpdf to dev-558gq-worker-eastus1-4q7zj
  Normal   Pulled     3m48s (x5 over 5m23s)  kubelet, dev-558gq-worker-eastus1-4q7zj  Container image "cockroachdb/cockroach-k8s-request-cert:0.4" already present on machine
  Normal   Created    3m48s (x5 over 5m23s)  kubelet, dev-558gq-worker-eastus1-4q7zj  Created container init-certs
  Normal   Started    3m48s (x5 over 5m23s)  kubelet, dev-558gq-worker-eastus1-4q7zj  Started container init-certs
  Warning  BackOff    18s (x25 over 5m21s)   kubelet, dev-558gq-worker-eastus1-4q7zj  Back-off restarting failed container
