### ISSUE TITLE
Sqllogictest currently times out on master

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#3822]
Running `TestLogic`'s big test currently times out after 1m10s after getting to `../../sqllogictest/test/index/between/10/slt_good_4.test: 5066`.

Investigating...

**Comment by nvanbenschoten** [comment]
False alarm, didn't realize there was a `bigtest` make target that bumps up the timeout in `/sql` that was supposed to be used.

**Comment by andreimatei** [comment]
btw it looks like my index changes broke the bigtest for the moment
