### ISSUE TITLE
cli: `cockroach demo` spams replication messages

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#38239]
`cockroach demo` periodically prints the following message to stderr:

    E190617 20:59:32.179324 111 storage/queue.go:1150  [n1,replicate] 19 replicas failing with "0 of 1 live stores are able to take a new replica for the range (1 already has a replica); likely not enough nodes in cluster"

Since this is known to be a single-node "cluster", `cockroach demo` should automatically set a zone configuration for a single replica. It [tries to do this](https://github.com/cockroachdb/cockroach/blob/119da2cff7e918132909a469927cb82a7dc6e3a1/pkg/cli/demo.go#L96-L109) but it doesn't seem to be working currently.

**Comment by tbg** [comment]
Shouldn't adaptive replication factors also avoid these warnings already?

**Comment by bdarnell** [comment]
Adaptive replication factors won't adapt below 3. Single-node clusters need an explicit zone config to be quiet.

https://github.com/cockroachdb/cockroach/blob/945b1fcd2226c9d91e5d2549b4a1396422a2c1ac/pkg/storage/allocator.go#L279-L281

**Comment by andreimatei** [comment]
@jeffrey-xiao I think you're a reasonable victim here since you've worked on the default zone configs. In fact maybe your work broke this?
If not interested, please unassign yourself.
