### ISSUE TITLE
core: roachperf not collecting data since 6/1

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#38252]
https://crdb.io/perf/?filter=&view=indexes%2F2%2Fnodes%3D6%2Fmulti-region&tab=gce

roachperf not collecting data since 6/1

**Comment by ajwerner** [comment]
The cron job was disabled. It has now been re-enabled and the data has been populated.

**Comment by kenliu** [comment]
thanks @ajwerner
