### ISSUE TITLE
sql: Queries that can benefit from the loose index scan optimizations

### ISSUE THREAD

**Issue by rohany** [cockroachdb/cockroach#38268]
Wanted to start an issue to collect all the sorts of queries that we have been discussing that can be improved with the loose index scan optimization.

Here is the most basic one.

```
CREATE TABLE t (x INT, y INT, PRIMARY KEY (x, y));
SELECT DISTINCT(x) from t;
```

This can be optimized by finding the smallest value of x, returning that row, and then seeking to the next largest value of x, instead of doing a full table scan.

**Comment by jordanlewis** [comment]
Another example:

```
CREATE TABLE t (x INT, y INT, PRIMARY KEY (x, y));
SELECT * FROM t WHERE y=1000;
```

In this case, a loose index scan (skip scan?) could be more efficient than our current strategy, full table scan. See https://github.com/cockroachdb/cockroach/issues/24584#issuecomment-498306406 for more details on how this could work.

**Comment by justinj** [comment]
Some other minor variations off the top of my head include:
```
CREATE TABLE t (x INT, y INT, PRIMARY KEY (x, y));
-- benefits from a reverse loose scan
SELECT * FROM t WHERE y=1000 ORDER BY x DESC;
-- benefits from a constrained loose scan
SELECT * FROM t WHERE y=1000 WHERE x > 10 AND x < 100;
-- requires multiple scans per "region"
SELECT * FROM t WHERE y IN (1, 10, 100);
```

**Comment by asubiotto** [comment]
Dup of #20068
