### ISSUE TITLE
Tiller already created message using k8s helm

### ISSUE THREAD

**Issue by kannanlakshmi** [cockroachdb/cockroach#38273]
I am creating a k8s cluster in GKE using our helm chart here https://www.cockroachlabs.com/docs/stable/orchestrate-cockroachdb-with-kubernetes-insecure.html 
When I create a service account tiller I get a warning message that tiller has already been installed in the cluster which is surprising. 

`$ helm init --service-account tiller
$HELM_HOME has been configured at /Users/lakshmi/.helm.
Warning: Tiller is already installed in the cluster.`
 
The next step of actually installing CockroachDB fails due to an RBAC error. It looks like CRDB is using the "default" service account in the "kube-system" namespace rather than the "tiller" service account I created in the rbac.yaml. 

`~$ helm install --name my-release stable/cockroachdb
Error: release my-release failed: namespaces "default" is forbidden: User "system:serviceaccount:kube-system:default" cannot get resource "namespaces" in API group "" in the namespace "default"`

I confirmed that k8s context is pointed at the cluster I just created 

`$ kubectl config current-context
gke_cockroach-shared_us-east1_lakshmitest`

I also confirmed that I created the clusterrolebinding below
`$ kubectl create clusterrolebinding $USER-cluster-admin-binding --clusterrole=cluster-admin --user=lakshmi@cockroachlabs.com
clusterrolebinding "lakshmi-cluster-admin-binding" created`

Unclear why this is failing, or what the RBAC error might be. 

cc @jseldess

**Comment by andreimatei** [comment]
@kannanlakshmi please put a project on this sucker (and probably also assign someone)
