### ISSUE TITLE
sql: enhance explain to warn users

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#38282]
Related to https://github.com/cockroachdb/cockroach/issues/38145#event-2410729563 we should consider enhancing explain to, for example, warn users that no predicates match an index. This would help users understand how their queries are interacting with the database and its' indexes.

**Comment by jordanlewis** [comment]
This is done now.
```
root@127.0.0.1:54210/defaultdb> explain select * From a;
  tree |    field    | description
-------+-------------+--------------
       | distributed | true
       | vectorized  | false
  scan |             |
       | table       | a@primary
       | spans       | FULL SCAN
(5 rows)
```
