### ISSUE TITLE
sql: tighter spans in index/lookup/zigzags joins

### ISSUE THREAD

**Issue by solongordon** [cockroachdb/cockroach#38280]
In #30744, we added an optimization for point lookups so that they would only scan as many column families as necessary rather than the entire row. This speeds up scans and reduces contention.

However, we're currently only getting this benefit in tablereader. We should apply the same optimization to other processors which do fetches: indexJoiner, joinReader (lookup joins), and zigzagJoiner. Ideally we can find an approach which doesn't add redundant code to all three places.

**Comment by rohany** [comment]
This optimization has been implemented in lookup and index joins, and it doesn't seem possible in zigzag joins, so I'm closing this issue.
