### ISSUE TITLE
ui: expose metrics about rows and bytes read on statement details page

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#38297]
Now that we're collecting number of bytes and rows read unconditionally, we should expose that information through the UI. One idea that was mentioned in #37409 was to expose it on statement details page.

Assigning @ajwerner for now.

**Comment by dhartunian** [comment]
Starting point for this before design takes a look:

Add new fields to the bottom of the right-hand panel on statement details
![Screen Shot 2020-04-30 at 10 54 19 AM](https://user-images.githubusercontent.com/986307/80725353-f36c1980-8ad0-11ea-8024-fec651de56e3.png)

**Comment by asubiotto** [comment]
This was done for 21.1.
