### ISSUE TITLE
prod: Windows support?

### ISSUE THREAD

**Issue by joeblew99** [cockroachdb/cockroach#3830]
I know its windows,but it would be useful to know if its supported. Just so people know if its possible option with their project planning

**Comment by tamird** [comment]
Hi @joeblew99, at this point windows is not explicitly supported, since none of us have actually tried to build the project on the platform. I experiment with cross-compiling to windows, but ran into some issues. See https://github.com/karalabe/xgo/issues/26 if you'd like help with this.

**Comment by tamird** [comment]
Updating this: windows cannot be supported with our current build system until https://github.com/golang/go/issues/14985 is resolved.

**Comment by ferdavs** [comment]
under window bash it starts but after some time stops running 

[logs.zip](https://github.com/cockroachdb/cockroach/files/863194/logs.zip)

**Comment by tamird** [comment]
Fixed by #14840.
