### ISSUE TITLE
[Feature Request] How to delete Time Series?

### ISSUE THREAD

**Issue by diyism** [cockroachdb/cockroach#38316]
```
defaultdb and system only occupied 1000 KB in my cluster,
while Non-Table Cluster Data(Time Series) occupied 200 MB,
is there any sql command to delete the Time Series?
```

**Comment by andreimatei** [comment]
> is there any sql command to delete the Time Series?

No.

There is `set cluster setting timeseries.storage.enabled = false`. I don't know what it does exactly / how it affects data that was already written.

There are also cluster settings for `timeseries.storage.resolution_10s.ttl` and `timeseries.storage.resolution_30m.ttl` that you can tweak to control the space taken by timeseries in the steady state (i.e. after a couple of days of operation).

Feel free to reopen if you have more questions.

**Comment by diyism** [comment]
Great, there's doc:
https://www.cockroachlabs.com/docs/v19.2/operational-faqs.html#disable-timeseries-storage-entirely
