### ISSUE TITLE
Roadmap page not accessible

### ISSUE THREAD

**Issue by xavierguarch** [cockroachdb/cockroach#38325]
**Describe the problem**

Trying to access the [Roadmap wiki page](https://github.com/cockroachdb/cockroach/wiki/Roadmap) gives me an error: `You do not have permission to update this wiki.`

**To Reproduce**

I was reading the blog post [Why we’re switching to calendar versioning](https://www.cockroachlabs.com/blog/calendar-versioning/) and tried accessing the Roadmap link that appears at the bottom of the post: https://github.com/cockroachdb/cockroach/wiki/Roadmap.

When I follow the link, I see this:

![image](https://user-images.githubusercontent.com/12254948/59874358-6c102e80-9374-11e9-9714-91cf1b7b1303.png)

**Expected behavior**

Have the Roadmap page properly shown.

**Additional data / screenshots**

Screenshot of the error I get when going to the Roadmap page:
![image](https://user-images.githubusercontent.com/12254948/59874486-abd71600-9374-11e9-8d4e-5a0a95f67e6a.png)

**Environment:**

N/A

**Additional context**

It's just a documentation problem.

**Comment by awoods187** [comment]
@xavierguarch we recently decided to remove the content from that link. I'll go ahead and remove the link on the right hand side.  Thanks for noticing and reaching out. If you have any other questions--let us know!
