### ISSUE TITLE
[Feature Request] Global flag for follower reads

### ISSUE THREAD

**Issue by tzilist** [cockroachdb/cockroach#38335]
**Is your feature request related to a problem? Please describe.**
Our current system doesn't require completely up to date data but does however require quick reads. Follower reads are the perfect solution but the requirement of adding extra SQL statements to our queries makes it difficult to implement and causes vendor lock-in to cockroach.

**Describe the solution you'd like**
Instead of adding `SELECT ... AS OF SYSTEM TIME experimental_follower_read_timestamp() ...;`, it would nice nice to just set a feature flag to always do follower reads for all queries. Or instead, set a flag that always does follower reads unless another sql statement is added, maybe like `SELECT ... AS OF LEASE HOLDER TIME ...;` or something along these lines.

**Describe alternatives you've considered**
I don't think there are any alternatives other than adding the extra SQL statements.

**Additional context**
N/A

**Comment by awoods187** [comment]
We could do this with a session variable that can apply settings on a per connection basis. We could imagine adding to this with a specification for follower reads in which we would always use a safe closed timestamp generated from that logic.

**Comment by andreimatei** [comment]
Does your code use any transactions?

**Comment by ajwerner** [comment]
To add more context to this issue, we have since discussed the use of `SET TRANSACTION AS OF SYSTEM TIME` with a transaction to ease adoption of follower reads. I typed up [this gist](https://gist.github.com/ajwerner/1b02589ab1cd83d95c7b116c90d5f83b) to demonstrate how it might be used with https://github.com/go-pg/pg/orm. @tzilist are you comfortable with me closing this issue?

**Comment by tzilist** [comment]
Yep, that is fine - we can certainly wrap things in transactions for now!
