### ISSUE TITLE
window 10 cockroach-v19.1.2.windows-6.2-amd64 can not export data 、import data 

### ISSUE THREAD

**Issue by lluck42** [cockroachdb/cockroach#38347]
use 
$./cockroach sql --user=root --host=localhost --port=26257 --insecure --echo-sql --database=bank < ./backup.sql
and nothing happen and no output

use dbeaver
export data output ：

DETAIL:  source SQL:
SELECT oid FROM pg_catalog.pg_namespace n
WHERE n.nspname OPERATOR(pg_catalog.~) '^(crdb_internal)$'
                ^
pg_dump: [archiver (db)] query was: SELECT oid FROM pg_catalog.pg_namespace n
WHERE n.nspname OPERATOR(pg_catalog.~) '^(crdb_internal)$'

input data output：
pg_restore: [archiver] did not find magic string in file header

use cockroach-v19.1.2.windows-6.2-amd64.zip

**Comment by ricardocrdb** [comment]
Hey @lluck42 

I wanted to leet you know that the latest 19.2.0 release should have addressed these issues. Please feel free to give them a try in Windows, and let me know if you have any issues.

Cheers,
Ricardo
