### ISSUE TITLE
sql: display postqueries in EXPLAIN

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#38340]
We're introducing postqueries in #38281, but they won't show up in the output of EXPLAIN at the moment. We should fix that.

**Comment by RaduBerinde** [comment]
We will need this soon (for writing tests for opt-driven FK checks).

**Comment by yuzefovich** [comment]
Sorry for the delay on this. I'll be working on this once I finish with finalizing vectorize settings to turn on a part of the engine by default.
