### ISSUE TITLE
storage: endless split caused by `alter table split at`

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#38360]
I've made a cluster go berzerk by attempting an `alter table split at`.

The log is continuously spammed by (look at that range number!):
```
I190621 18:42:06.427518 1377 storage/split_queue.go:146  [n1,split,s1,r21/1:/{Table/52-Max}] split saw concurrent descriptor modification; maybe retrying
I190621 18:42:06.427660 1604 storage/replica_command.go:256  [n1,split,s1,r21/1:/{Table/52-Max}] initiating a split of this range at key /Table/53 [r49667] (zone config)
```
and the split command fails after a few seconds with:
```
pq: split at key /Table/52/1/99 failed: unexpected value: raw_bytes:"\003\037\027\347\003\010\025\022\001\274\032\002\377\377\"\006\010\001\020\001\030\001(\0020\001" timestamp:<wall_time:1561140918005740000 >
```

What I've done is:
```
create table t (x int primary key);
alter table t split at values (99), (199);
```

I've tried to repro on another cluster and failed.
The cluster on which I've done it was on my laptop; I think it was empty, but it had been created at 19.1 (or some random older sha). And then I restarted it from master, at which point it updated the version automatically. And then I've done the split.

Maybe this is a `CPut` problem across versions? Was this the problem that I think separately @danhhz and @jeffrey-xiao were talking about?

Here's the data dir. When restarting the node, it'll continue to spam the logs. And also creating a new table and trying to split it leads to the same problem.
[split-failure-cockroach-data.zip](https://github.com/cockroachdb/cockroach/files/3315707/split-failure-cockroach-data.zip)

**Comment by ajwerner** [comment]
Which "master" SHA were you using?

**Comment by ajwerner** [comment]
In theory @danhhz's https://github.com/cockroachdb/cockroach/pull/38302 should address this. Is it possible that you were using a commit that preceded 8dc92a6068ada4dcda925d5526be351964dc3c0e?

**Comment by andreimatei** [comment]
Indeed, I was before that. I've synced to it, started again, and the split succeed.
Closing, thanks!
