### ISSUE TITLE
java. ABORT_REASON_CLIENT_REJECT, happens quite easily, UUID. Not so easily with golang and bigint?

### ISSUE THREAD

**Issue by Samusername** [cockroachdb/cockroach#38371]
Following error occurs quite easily with java generator:

restart transaction: TransactionRetryWithProtoRefreshError: TransactionAbortedError(ABORT_REASON_CLIENT_REJECT)

jdbc:postgresql://<mycockroach-svc>:26257/test?reWriteBatchedInserts=**true**

DB Table:
UUID
jsonb

20 million rows in DB table.

The error occurs quite quickly, e.g. before 2 minutes. Again and again.
Side note: I cannot rule out different load in the overall system. Others may use same resources at the same time.

reWriteBatchedInserts=true was removed. Error happened with that also after some minutes. 
Throughput is really bad without using such setting. (Throughput drops to less than 700 rows / s.)

bigint would be enough for us, instead of UUID. I have not tested similar java data generator with bigint yet.

It is possible to retry in case of such errors.
But, does such problem / error occur too easily with java?

One unexplained comment: it worked better few days ago.

CockroachDB nodes: 9.

CockroachDB: v19.1.1

Golang

Golang application seems to work better. I did not notice such errors when inserting data with golang data generator.
In golang data generator case, there was bigint in use - not UUID.

**Comment by ricardocrdb** [comment]
Hey @Samusername 

Apologies for the delay, let's get to the bottom of this. Firstly, let's get the details on how the 9 node Cockroach cluster is provisioned. Let me also know how many concurrent threads you are using, as well as the total batch size.

**Comment by ricardocrdb** [comment]
Hello @Samusername 

Do you have an update on the requested information in the previous email?

Cheers,
Ricardo

**Comment by Samusername** [comment]
Hi!
The exceptions occurred with even only one thread. (I recall so. It was weeks ago.)
Batch size e.g. 4096 (or twice that).
I would need to check the settings later, of the 9 nodes. I do not have access to the system now during this week. But I think we did not change default settings regarding RAM usage. It was installation with helm.
I only wanted to raise this topic up, in case there is something to be investigated. (This is not an urgent topic.)
BR Sam

 
 
  On pe, heinäk. 26, 2019 at 17:54, Ricardo Rocha<notifications@github.com> wrote:   
Hey @Samusername

Apologies for the delay, let's get to the bottom of this. Firstly, let's get the details on how the 9 node Cockroach cluster is provisioned. Let me also know how many concurrent threads you are using, as well as the total batch size.

**Comment by Samusername** [comment]
There is 10 k8s nodes in the system.
There are 9 cockroachdb nodes with:
 --cache 25% --max-sql-memory 25% 

Whole exec:
`exec /cockroach/cockroach start --logtostderr --certs-dir /cockroach/cockroach-certs
          --advertise-host $(hostname).${STATEFULSET_FQDN} --http-host 0.0.0.0 --http-port
          8080 --port 26257 --cache 25% --max-sql-memory 25%  --join ${STATEFULSET_NAME}-0.${STATEFULSET_FQDN}:26257,${STATEFULSET_NAME}-1.${STATEFULSET_FQDN}:26257,${STATEFULSET_NAME}-2.${STATEFULSET_FQDN}:26257`

**Comment by Samusername** [comment]
( We do not need to keep this ticket open, but wanted to mention this still. 
I am not certain will I use UUID in real use, in case the problem happens more easily only with UUIDs. )

**Comment by Samusername** [comment]
Currently there is pause in testing CockroachDB.
We can close this ticket at the moment. I can come back to the topic later, if it is seen needful.
