### ISSUE TITLE
exec: add memory accounting to BatchAllocator

### ISSUE THREAD

**Issue by solongordon** [cockroachdb/cockroach#38412]
When callers request or append to batches from `BatchAllocator`, the allocator should measure the size of the new data and draw down from its memory budget.

**Comment by asubiotto** [comment]
To consider this issue closed, we should implement a system where a buffering operator is denied an allocation with `vectorize=experimental_on` if attempting to allocate more than `work_mem` bytes. This allocation denial should be propagated back to the user.
