### ISSUE TITLE
sql: warn or forbid unpartitioned secondary indexes on partitioned tables

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#38475]
Unpartitioned secondary indexes can cause a cluster to perform slowly. Most of the time, users will want to partition any secondary index on a table. It is only in some rare occurrences that users would want to have a secondary index that is not partitioned on a partitioned table. 

@bdarnell  suggested that we should explore:

- Warning users that we've detected an unpartitioned secondary index
- Forbidding unpartitioned secondary indexes on a partitioned table unless some sort of opt-in keyword is used to indicate that this is desired.

**Comment by rohany** [comment]
Have we decided whether we want to produce a warning or an error in this case?

**Comment by bdarnell** [comment]
It's very difficult to make a warning in SQL that will actually get seen (client frameworks and migration tools have a habit of completely ignoring them). So in most cases I don't like warnings and would rather have an error with some override option. 

On the other hand, there will be some risk of false positives. Non-partitioned indexes are only bad with the geo-partitioned replicas topology pattern. If you're using geo-partitioned leaseholders (or non-geo partitioning schemes like date ranges), a non-partitioned index is generally fine. So maybe it should just be a warning unless we can also tie it to the particular way in which partitioning is being used.

**Comment by jordanlewis** [comment]
What about returning an error without an opt-in if there exists at one index that was partitioned *by value*?

**Comment by bdarnell** [comment]
Partitioning by list (i assume that's what you meant by "by value") could be either geo-distributed replicas or geo-distributed leaseholders. It's what's in the zone config that makes the difference, not the partitioning config itself.

**Comment by jordanlewis** [comment]
Yes, I meant by list. I forgot about the ambiguity you're talking about - I agree that we'd be at risk for false positives in this case, and trying to infer which case is intended by the zone configurations seems difficult. For example, what if somebody does all index creations first, and zone configures them later? In that case, if the inference required looking at zone configs, we wouldn't have enough information during index creation to take action.

I think a warning that's exposed to the Cockroach CLI is better than nothing, so maybe let's start with that.

**Comment by solongordon** [comment]
Another option I thought of would be to error out only if `sql_safe_updates` is on. But maybe there would still be enough false positives to make that an annoyance.

**Comment by bdarnell** [comment]
I think the false positives with `sql_safe_updates` would be OK; I'm more concerned about false negatives. That setting is mainly used in the interactive shell; it's unlikely that any migration tools would turn it on.

**Comment by solongordon** [comment]
Right, I just meant for this initial step where we expose a warning to the Cockroach CLI. I think I will go ahead with that as a first step if no one objects, since it should be very straightforward.

**Comment by bdarnell** [comment]
What's the opt-in if we tie it to sql_safe_updates? Just turn off sql_safe_updates entirely? I think everything we currently have behind that setting has some opt-in method that doesn't require turning safety off completely (e.g. adding `WHERE true` to an unqualified `DELETE`).

**Comment by solongordon** [comment]
I can't think of a good opt-in besides temporarily turning off `sql_safe_updates`. I think that's also the case for `ALTER TABLE DROP COLUMN`. But if we don't want to encourage that, I can look into just logging a warning to the CLI instead.

**Comment by solongordon** [comment]
Prospects for returning a warning to the CLI are looking a bit bleak. The mechanism the Postgres protocol provides for this is the `NoticeResponse` message type, but as far as I can tell `lib/pq` just drops those messages on the floor.

**Comment by solongordon** [comment]
I ended up going with the `sql_safe_updates` approach for this since I couldn't find a good alternative. I'm going to merge that for now, but I'm happy to iterate on it if we come up with a better tactic.
