### ISSUE TITLE
A backup of a database that includes a view which references another database fails on restore

### ISSUE THREAD

**Issue by rkruze** [cockroachdb/cockroach#38470]
**Describe the problem**

Currently today it is possible to have a view in one database which references tables in another database. If you create a backup which only contains the database which contains the view you are not able to restore the backup since the view wants to be able to restore all tables that it references but cannot since they are not included in the backup. 

**To Reproduce**

1. Create two databases, d1, and d2
2. Create tables in each. 
3. Create a view in one database d1 that references tables in d2. 
4. Create a backup of d1. 
5. Try to restore from backup. 
6. Will most likely get an error similar to `Error: pq: cannot restore "view_name" without restoring referenced table 25 in same operation`

You will see this error regardless if the tables which the views references are available or not. 

**Expected behavior**
I would expect to either have the backup fail since I didn't include the other database or for the restore to try to recreate the view and allow for me to skip the view creation if it is not possible. 

**Environment:**
 - CockroachDB version 19.1.1
 - Server OS: Linux
 - Client app [e.g. `cockroach sql`, JDBC, ...]

**Additional context**
The backup created in this scenario is invalid for restore.

**Comment by tim-o** [comment]
Not quite sure how to assess priority here - not being able to restore feels very bad to me, but I don't think many people are using views.

**Comment by rolandcrosby** [comment]
Note that the rest of the backup can still be restored by restoring specific tables one at a time. @lucy-zhang is going to mitigate this issue by adding an option to skip views when restoring backups, which will allow the entire database to be restored (without views). We will also prioritize an enhancement to `SHOW BACKUP` to display schemas, which will enable users to manually recreate views.

**Comment by lucy-zhang** [comment]
#38597 adds an option to skip views that can't be restored.
