### ISSUE TITLE
pgwire: empty query vs command ok

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#3849]
Looks like we're sending `PGRES_EMPTY_QUERY` instead of `PGRES_COMMAND_OK` for a `drop table if exists...`, causing code that checked for `PGRES_COMMAND_OK`, eg the setup in `pgbench`, to fail.

**Comment by dt** [comment]
cc @mjibson

**Comment by tamird** [comment]
Ah, yeah, this even bears a comment in the code https://github.com/cockroachdb/cockroach/blob/master/sql/pgwire/v3.go#L683

**Comment by dt** [comment]
I think it might actually be above that in the `Response_Result_DDL_` case.

**Comment by tamird** [comment]
Might be.

**Comment by mjibson** [comment]
Real postgres does indeed send back a `C` for `DROP`:

```
DEST: "Q\x00\x00\x00\x12drop table t;\x00"
SRC: "C\x00\x00\x00\x0fDROP TABLE\x00Z\x00\x00\x00\x05I"
```

**Comment by mjibson** [comment]
Inspection yields many other similar problems:

- when sending an empty query, we respond with command complete (`C`), postgres responds with empty query (`I`)
- for table mutation statements (drop, alter, create, rename), we respond with empty query (`I`), postgres responds with command complete (`C`)
