### ISSUE TITLE
backupccl: enable SHOW BACKUP to display schemas

### ISSUE THREAD

**Issue by rolandcrosby** [cockroachdb/cockroach#38517]
Simple enhancement to the [`SHOW BACKUP`](https://www.cockroachlabs.com/docs/stable/show-backup.html) statement: add an option to enable users to display the schemas of the tables and views in the backup. Mitigates #38470. Probably should not display by default, for brevity. Could be done by adding a `schema` column to the existing output, which is only displayed when the user passes an option like `SHOW BACKUP WITH SCHEMA` (alternative syntax proposals welcome).

**Comment by Gurio** [comment]
@rolandcrosby Hi, is someone working on it, or is it free to pick?

**Comment by rolandcrosby** [comment]
Hey @Gurio, thanks for your interest! Someone on our team has picked this up, but thanks for checking.

**Comment by Gurio** [comment]
@rolandcrosby Thanks for the answer!
