### ISSUE TITLE
roachdash: sync process failing on moved issue

### ISSUE THREAD

**Issue by kenliu** [cockroachdb/cockroach#38553]
error in server log: `github sync ending for cockroachdb/roachprod: GET https://api.github.com/repos/cockroachdb/roachprod/issues/186/comments?direction=asc&per_page=100&sort=updated: 404 Not Found []`

**Comment by bobvawter** [comment]
This is ultimately https://github.com/golang/go/issues/30184 in which the maintner library doesn't handle issues that have gone 404.  For the moment, I've worked around this by ignoring archived projects (which are the ones most likely to experience issues being removed entirely).

**Comment by kenliu** [comment]
oops, should have opened this in the `roachdash` repo. fixed. thanks @bobvawter
