### ISSUE TITLE
sql: Client-side retries with WriteTooOldError in UPDATE

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#38591]
`WriteTooOldErrors` are [handled specially](https://github.com/cockroachdb/cockroach/blob/701719bf1238fd945326d8faf1796e1e136df6e6/pkg/storage/replica_evaluate.go#L234): We try to delay returning this error until the end of the transaction in order to lay down more intents and do more discovery of conflicting timestamps. However, this delay undermines the SQL-level ["rewind"](https://github.com/cockroachdb/cockroach/blob/0e9bd94de008554f1a678d26d7b8ed17f91dcd67/pkg/sql/conn_executor.go#L149-L161) functionality which can transparently retry the first statement in a transaction. 

We have a strong preference for transparent retries whenever possible. In #22234, we disabled the delayed WriteTooOldError behavior for `CPut` and `Increment`, because we know that a transparent `RefreshSpans` will fail, and if we delay the WriteTooOldError to COMMIT, it will trigger a client-visible retry. This had the effect of ensuring that if the first statement was an INSERT, we'd retry internally, but if it was an UPDATE (including an UPDATE clause in an INSERT ON CONFLICT) we may trigger a retry at COMMIT time.

I think that #22234 didn't go far enough: Nearly all Put operations currently originated by SQL are logically "conditional puts" that are done in separate Get and Put steps. The RefreshSpans is guaranteed to fail just as it is for CPut. We should be returning WriteTooOldError immediately for these regular puts too. Doing this for all Puts effectively disables the "delayed WTOE" behavior, although I think Puts where the delayed WTOE would be beneficial are rare in our current usage.

I also think that #22234 went too far in making WTOE immediate for all CPuts. In the first statement of a transaction, an immediate WTOE maximizes our chance of a transparent retry. But in later statements, CPuts as well as regular Puts benefit from continuing to lay down intents. (This would prevent the `O(n^2)` behavior from https://github.com/cockroachdb/cockroach/pull/22234#issuecomment-362072350. In scenarios with high contention on multiple keys, we currently have quadratic behavior for operations using CPut but better performance for operations using Put)

I suggest addressing this in two parts. First, disable the "delayed WTOE" behavior for Puts (and probably just for everything). I think this is probably backportable (although it has the risk of making the aforementioned. `O(n^2)` behavior more likely for high-contention UPDATEs). Second, introduce a new flag to be plumbed down from SQL to indicate whether we are currently able to autoretry an immediate WTOE, and use this flag instead of the type of request to decide whether WTOEs are immediate or delayed. (I'll only do the first part myself; I need to hand off the latter part to someone else).

**Comment by awoods187** [comment]
cc @andy-kimball i think we should try to get this done for 19.2

**Comment by bdarnell** [comment]
The first part of this is trivial and I intend to get it into 19.1.3. I'm not sure the second part is worth trying to get into 19.2 at this stage in the development cycle.

**Comment by bdarnell** [comment]
The fix is in #38668. After working through the tests I'm a little less eager to get this into 19.1.3. I think it's probably still safe but I missed a few things on my initial implementation so it might be better to wait.

**Comment by awoods187** [comment]
> Second, introduce a new flag to be plumbed down from SQL to indicate whether we are currently able to autoretry an immediate WTOE, and use this flag instead of the type of request to decide whether WTOEs are immediate or delayed

@bdarnell could you clarify how big the work effort is for the second part?

**Comment by bdarnell** [comment]
I think it's fairly small, probably a couple days of work. But testing it may be tricky and it may get more complex than expected once you start pulling on that thread.

**Comment by bdarnell** [comment]
Copying this from https://github.com/cockroachdb/cockroach/pull/38668#pullrequestreview-259588707

> And FYI, we also have this code. It detects pushes while the txn can still auto-retry, but it doesn't do anything unless there's no chance for the refresh to succeed. Maybe instead of this patch we could improve that code - have it actually try a refresh (or, in the case of a write_too_old flag, just assume that the refresh will fail - which I guess would keep the write_too_old field somewhat useful). This way KV could continue to defer WTOE (and we would also defer them for CPut) and SQL would be in charge of deciding when deferring is no longer a good idea.

https://github.com/cockroachdb/cockroach/blob/d02410725d19b346a0f34e51fd5029b3a020b4cb/pkg/sql/conn_executor_exec.go#L425-L445
