### ISSUE TITLE
storage: incorrect RangeDescriptor equality due to InternalReplicas ordering

### ISSUE THREAD

**Issue by jeffrey-xiao** [cockroachdb/cockroach#38592]
In 19.1, there was no specific ordering to `InternalReplicas`. In 19.2, `InternalReplicas` is expected to be sorted first by type, then by replica ID ([`Voters()`](https://github.com/cockroachdb/cockroach/blob/d668aa9809a4afcfc1a938469ad8f6525ee54aee/pkg/roachpb/metadata_replicas.go#L46) and [`Learners()`](https://github.com/cockroachdb/cockroach/blob/d668aa9809a4afcfc1a938469ad8f6525ee54aee/pkg/roachpb/metadata_replicas.go#L57) depend on this). Calling `Replicas()` will implicitly sort `InternalReplicas`.

For a node on 19.2, these two factors can cause the in-memory copy of `RangeDescriptor` to be out-of-sync with the copy in kv. The `RangeDescriptor` in kv could be unsorted, then a call to `Replicas()` could sort the in-memory copy. Since the generated `Equal` for `RangeDescriptor` checks the ordering of `InternalReplicas`, the conditional get will fail.

Some solutions to clean this up:

1) Establish the invariant when unmarshalling.
2) Drop the invariant and sort it only when we need it sorted. Additionally, `Replicas()` should return a copy of the slice and leave the original alone.
3) Have a custom `Equal` method that ignores the ordering of `InternalReplicas`.

cc @danhhz

**Comment by nvanbenschoten** [comment]
Fixed by https://github.com/cockroachdb/cockroach/pull/39489.
