### ISSUE TITLE
util: Move union_find.go to separate repo

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#38606]
Third-party projects are now depending on `union_find.go` (see #38596). This is incompatible with our move to the BSL. We should move this file out to a separate apache-licensed repo so third parties can continue to use it (and so they don't have to pull in our large repo for this tiny dependency).

**Comment by RaduBerinde** [comment]
I looked around that project. I don't think they're using `union_find` at all, they are using other `util/` packages that probably depend on `util`: https://github.com/prometheus/prometheus/blob/10444e8b1dc69ffcddab93f09ba8dfa6a4a2fddb/vendor/

Ironically, `union_find` won't be needed anymore once we remove the heuristic planner (unless some other use of it pops up in the meantime).

**Comment by RaduBerinde** [comment]
`union_find.go` was removed a long time ago.
