### ISSUE TITLE
distsqlrun: ignore breaker when outbox dials node

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#38602]
https://github.com/cockroachdb/cockroach/blob/5a0ae02c62d8a1eb50e930eeda634d32be297d58/pkg/sql/distsqlrun/outbox.go#L220

When nodes in the cluster have recently restarted, the above dial can fail which results in the "dialee" failing with a "no inbound stream connection" error after a long timeout (10s).

In the outbox, one is relatively sure that the node is reachable (otherwise, the gateway probably would not have set the flow up that way), so it might be better in general to ignore the breaker, or to mitigate this somewhat.

See https://github.com/cockroachdb/cockroach/pull/38484#issuecomment-507592410

**Comment by jordanlewis** [comment]
This slipped through the cracks - would be nice to get a fix for this out in the next release.

@rafiss could you take a look at this?

**Comment by yuzefovich** [comment]
Oopsie, accidentally closed the issue when looking at our project board.

**Comment by knz** [comment]
I just ran into this during load testing with tpcc
