### ISSUE TITLE
sql: add locality to SHOW EXPERIMENTAL RANGES

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#38603]
`SHOW EXPERIMENTAL RANGES`provides a current output of:
```
+-----------+---------+----------+----------+--------------+
| start_key | end_key | range_id | replicas | lease_holder |
+-----------+---------+----------+----------+--------------+
| NULL      | /5      |      158 | {2,3,5}  |            5 |
| /5        | /10     |      159 | {3,4,5}  |            5 |
| /10       | /15     |      160 | {2,4,5}  |            5 |
| /15       | NULL    |      161 | {2,3,5}  |            5 |
+-----------+---------+----------+----------+--------------+
(4 rows)
```
[Source](https://www.cockroachlabs.com/docs/stable/show-experimental-ranges.html)

As @piyush-singh pointed out, this is annoying because it doesn't show locality information. We only list the nodes on which replicas are placed, we don't show localities which means users need to remember which nodes are where to see if their zone configs have finished applying. We should add this information to the command.

**Comment by rohany** [comment]
Done in #39060.
