### ISSUE TITLE
add support for END (alias for COMMIT) and START TRANSACTION.

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#3861]
http://www.postgresql.org/docs/9.5/static/sql-end.html

**Comment by petermattis** [comment]
What is the rationale here? Do we need/want to support postgres extensions?

**Comment by dt** [comment]
Rationale would be increasing postgres compatibility / allowing more things that run against postgres to run against cockroach out-of-the-box.

**Comment by petermattis** [comment]
Adding support for one such extension seems reasonable, yet where does it end? For example, should we support `BEGIN WORK` as an alias for `BEGIN [TRANSACTION]`? I also just noticed that `BEGIN TRANSACTION` is apparently a postgres extension and that the standard specifies `START TRANSACTION`.

**Comment by dt** [comment]
I guess my thinking was that where the marginal cost (including the long-term maintenance) is low it might make sense, depending on the benefit.

fwiw, SQLite also uses `END` and `COMMIT` interchangeably and makes `TRANSACTION` optional: https://www.sqlite.org/lang_transaction.html

**Comment by dt** [comment]
From #3922:
> Why add support for END without adding support for START? Where do we draw the line on compatibility work like this?

I guess my thinking it that specific cases either make sense or don't on depending on the effort required and the payoff, but that generally, more compatibility is generally desirable, if it means more things Just Work out of the box.

In this case, the `END` alias makes postgres' own benchmark work without recompiling it, which seems appealing?

**Comment by petermattis** [comment]
I'd rather add support for `START TRANSACTION` (which is the SQL standard) than `END`, but adding both doesn't seem too harmful when they essentially boil down to grammar changes. We'll want to call out in documentation that `END` is for compatibility purposes only.

**Comment by dt** [comment]
Added `START TRANSACTION` to the #3922 along with a few parse tests to confirm they all normalize to the same thing.
