### ISSUE TITLE
exec: handle nulls in top K sorter

### ISSUE THREAD

**Issue by solongordon** [cockroachdb/cockroach#38618]
The vectorized top K sorter doesn't take into account nulls when it compares rows. Nulls should sort before non-null values.

**Comment by solongordon** [comment]
I forgot that the top K's compare function actually does consider nulls, so we're already most of the way there. However, `Vec.Copy` does need an enhancement to handle copying with nulls at non-zero indices.

**Comment by rohany** [comment]
Done in #38654 and #38669
