### ISSUE TITLE
ui: Downgrade "Invalid lease" on problem ranges page?

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#38616]
The state that is reported as "invalid lease" on the problem ranges page is relatively normal and harmless - it can occur after node restarts and will eventually clear on its own but can take up to 24h  on idle clusters. This sometimes leads to user confusion/concern (https://forum.cockroachlabs.com/t/what-to-do-about-invalid-leases-on-the-problem-ranges-report/2886)

If you see anything but "invalid lease" (and maybe "no raft leader"?) on the problem ranges page, it's generally a cause for concern. We should remove "invalid lease" from this page or at least make it clear that this is less likely to be a true problem (for example, by relabeling it from "invalid lease" to "expired lease"). I don't recall "invalid lease" on its own ever being a useful indicator of a true problem, so I'd be inclined to just drop it.

**Comment by tim-o** [comment]
Zendesk ticket #[3485](https://cockroachdb.zendesk.com/agent/tickets/3485) has been linked to this issue.

**Comment by bdarnell** [comment]
This has come up multiple times recently.
