### ISSUE TITLE
Missing "with recursive" support in CockroachDB

### ISSUE THREAD

**Issue by sanjimoh** [cockroachdb/cockroach#38636]
While porting an application from MariaDB to CockroachDB, I realized the fact that in CockroachDB "with recursive" support is not there.

Meanwhile I had a look at an existing ticket raised around this [here](https://github.com/cockroachdb/cockroach/issues/21085).

and currently it looks like in the backlog but as low priority! We see this feature as quite crucial for our application for performance reasons.

Couple of queries around this -

1. Is there any better alternatives already available in the existing SW which could be tried out in the application? Current version of CockroachDB being used is v19.1.1
2. If not, then when can we expect this feature to be supported out of the box? Please help prioritizing this at earliest; otherwise it would be a show stopper for us in moving towards CockroachDB.

**Comment by andreimatei** [comment]
cc @awoods187

**Comment by RaduBerinde** [comment]
Unfortunately, even our non-recursive WITH support is spotty (we only support it when the CTE is used once). Given the current list of items we are working on, recursive CTEs won't make 19.2, but perhaps the following release.

As for 1, I think it depends heavily on the use case. If you can go into more details about how you are using them, perhaps with sample queries, that would be helpful.

**Comment by RaduBerinde** [comment]
Closing this as WITH RECURSIVE is already tracked by #21085.
