### ISSUE TITLE
exec: memory estimation for streaming operators

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#38658]
The first step to memory monitoring in the vectorized engine is to add a method for operators to report their static memory use: memory that the operators are guaranteed to use after initialization tells them the column layouts and so on.

I think it would be better to do this with a map or type switch approach than methods on the `Operator` interface, because not every operator needs to declare static memory (such as selection operators), but I'm not sure. There are downsides to that approach as well.

Once this is done, flow setup can collect the sum of the static memory use of all operators within the flow, and request that memory quantity from a memory monitor. This will provide good enough memory accounting for flows that contain only streaming operators.

This item tracks adding the infrastructure as well as hooking it up to a memory monitor during flow setup.

**Comment by rohany** [comment]
Done in #38796
