### ISSUE TITLE
cli: Give cockroach debug ballast a default file size

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#38661]
In response to the `cockroach debug ballast` [docs PR](https://github.com/cockroachdb/docs/pull/5000), @bdarnell suggested:

> In addition to moving this out of debug we should probably give it a default. There's no reason to make people choose a value here

**Comment by kenliu** [comment]
what would the default size be?

**Comment by bdarnell** [comment]
1GB seems reasonable to me.

**Comment by Gurio** [comment]
I would take, if no one else is already on it
