### ISSUE TITLE
opt: Synthesize equality conditions during AssociateJoin rule

### ISSUE THREAD

**Issue by andy-kimball** [cockroachdb/cockroach#38716]
When 3 or more tables are joined, it is not uncommon for 3 or more columns to be equivalent. For example:
```
SELECT * FROM a, b, c WHERE a.x=b.y AND b.y=c.z
```
The optimizer will consider these join orders:
```
1. (a join b) join c
2. a join (b join c)
```
But it will not consider `(a join c) join b`, because there is no explicit join condition between `a` and `c`. This could cause it to miss the best plan (in fact, it does miss the best plan for TPC-H Q9 for this reason).

The optimizer knows that columns (x, y, z) are all equivalent to one another. It can synthesize any missing equality conditions during the `AssociateJoin` rule, thus opening up new ordering possibilities.

For TPC-H Q9, adding the missing equality condition reduces execution time from ~120s to ~20s.

**Comment by justinj** [comment]
I think this is a dup of #36226 that Radu found, I've been meaning to look into it but haven't yet.

**Comment by rytaft** [comment]
I'm working on this now
