### ISSUE TITLE
opt: Improve row count estimation for common OR clause pattern

### ISSUE THREAD

**Issue by andy-kimball** [cockroachdb/cockroach#38722]
Consider this query, which uses TPC-H schema:
```
EXPLAIN (opt,types) SELECT * FROM nation WHERE n_name = 'FRANCE' OR n_name = 'GERMANY';
```
The optimizer estimates 8.33 rows will be returned from this query. However, if the query is changed to this:
```
EXPLAIN (opt,types) SELECT * FROM nation WHERE n_name IN ('FRANCE', 'GERMANY');
```
The optimizer correctly estimates 2 rows.

We should add an optimization rule that normalizes OR conditions as an IN clause where possible, since our statistics estimation is able to do a better job of estimation with IN clauses.

**Comment by rytaft** [comment]
I think the problem is that the constraint library currently handles IN but does not handle OR. Perhaps we should add the ability to extract constraints from OR expressions, using similar logic to the index constraints library.
