### ISSUE TITLE
Allow users with `SELECT` privilege on a table to view its ranges

### ISSUE THREAD

**Issue by rolandcrosby** [cockroachdb/cockroach#38731]
Currently, only the `admin` role is able to execute the `show (experimental|testing)_ranges` statement. It would be sensible to expand this and allow any user with the `SELECT` privilege on a table to view the ranges associated with the table and its indexes.

Current behavior:

```
root@127.0.0.1:58752/defaultdb> create user blah;
CREATE USER 1

root@127.0.0.1:58752/defaultdb> grant select on a to blah;
GRANT
```

```
blah@:58752/defaultdb> select * from a;
  a
+---+
(0 rows)


blah@:58752/defaultdb> show create table a;
  table_name |        create_statement
+------------+---------------------------------+
  a          | CREATE TABLE a (
             |     a INT8 NULL,
             |     INDEX a_a_idx (a ASC),
             |     FAMILY "primary" (a, rowid)
             | )
(1 row)

blah@:58752/defaultdb> show testing_ranges from table a;
pq: only superusers are allowed to read crdb_internal.ranges_no_leases

blah@:58752/defaultdb> show testing_ranges from index a@a_a_idx;
pq: only superusers are allowed to read crdb_internal.ranges_no_leases
```

**Comment by tim-o** [comment]
Zendesk ticket #[3472](https://cockroachdb.zendesk.com/agent/tickets/3472) has been linked to this issue.

**Comment by jordanlewis** [comment]
@rolandcrosby do you think it's worth introducing some new privileges to handle stuff like this and #37443? I haven't done a lot of research into what privileges other dbs have available, but it seems natural to me that you wouldn't want to keep overloading `SELECT` forever.

**Comment by rohany** [comment]
```
		if err := p.RequireAdminRole(ctx, "read crdb_internal.ranges_no_leases"); err != nil {
			return nil, err
		}
```
In the range_no_leases table generation. Does this table need to have admin only read permissions? show ranges itself already checks that the user has read permissions on the table, but that doesn't matter if the internal table blocks access.

**Comment by knz** [comment]
We don't allow users to look into ranges because it reveals operational data about the cluster, which is privileged.
