### ISSUE TITLE
opt: implement index skip scan using partition values

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#38744]
This bugs tracks implementing an index skip scan, as described in https://github.com/cockroachdb/cockroach/issues/37312#issuecomment-489354659

See that issue for more discussion.

We can start by using the list of values for partitioning.

**Comment by RaduBerinde** [comment]
CC @ridwanmsharif, this would be a natural extension of your work on #37312.

**Comment by RaduBerinde** [comment]
Oh, sorry, this is a dup of #38031.

**Comment by ridwanmsharif** [comment]
Is this an issue for a more general index-skip-scan? Perhaps we should change the title then.

**Comment by RaduBerinde** [comment]
No, it's a duplicate that I forgot to close.
