### ISSUE TITLE
DDL statement on one table prevents stmt on another unrelated table in same transaction

### ISSUE THREAD

**Issue by mguillemot-tel** [cockroachdb/cockroach#38768]
# Describe the problem

Inside a single transaction, DDL statements about one table prevent modifications on another totally unrelated table. 

**This is a regression that happened somewhere between 2.1.4 (which worked) and 19.1.2 (which exhibits the bug).**

# To Reproduce

Put the following in a `repro.sql` file:

```sql
BEGIN;

CREATE TABLE a ();

CREATE TABLE b (
    key INT
);
CREATE INDEX b_idx ON b (key);

COMMIT;

--------------------------------------------

BEGIN;

DROP TABLE a;
DROP INDEX b_idx CASCADE;

COMMIT;
```

Then execute it on Cockroach 19.1.2:

```bash
cockroach sql --insecure -e "drop database test; create database test;" && cockroach sql --insecure -d test < repro.sql
```

This will fail with the following message: `pq: relation "test.public.a" does not exist`

The error is raised when executing the DROP INDEX statement in the second transaction. But tables `a` and `b` have no relation whatsoever so an operation on `a` shouldn't prevent an operation on `b`.

The error message is also very confusing: the mention of `b` makes it seem that the error happens during the DROP TABLE statement, but it is actually about the DROP INDEX statement.

Currently it is necessary to split the second transaction into 2 different transactions for it to execute properly.

If executed on a Cockroach 2.1.4 server, the execution suceeds.

# Environment:
 - CockroachDB version 19.1.2
 - Server OS: macOS 10.14.5
 - Client app: `cockroach sql`

**Comment by pbardea** [comment]
Closed by #40516
