### ISSUE TITLE
roachprod: difficulty starting cluster with username containing non-alphanumeric characters (e.g. periods)

### ISSUE THREAD

**Issue by ericharmeling** [cockroachdb/cockroach#38771]
## Overview
`roachprod` requires that cluster names begin with authorized GCE account name. Cluster names cannot include certain characters (e.g. a period), so usernames with periods with have issues. Currently, you need to use the `--username` tag for usernames like this... 

For example, to start a cluster with the username `eric.harmeling`, you need to have the cluster name specified as `ericharmeling-cluster-name` and you need to use the `--username=ericharmeling` tag.

## Walkthrough

My cockroachlabs GCE account name is `eric.harmeling`:

``` shell
ericharmeling$ gcloud auth list
         Credentialed Accounts
ACTIVE  ACCOUNT
*       eric.harmeling@cockroachlabs.com

To set the active account, run:
    $ gcloud config set account `ACCOUNT`
```

I try to create a cluster using `ericharmeling` as the username that begins the cluster name:

``` shell
ericharmeling$ export CLUSTER="${USER}-geo-partitioning"
ericharmeling$ roachprod create $CLUSTER --geo --gce-zones=us-east1-b,us-east1-c,us-east1-d,us-central1-a,us-central1-b,us-central1-c,us-west1-a,us-west1-b,us-west1-c,us-east1-b,us-central1-a,us-west1-a --local-ssd --nodes=12
```

`roachprod` throws an error (from [here](https://github.com/cockroachdb/cockroach/blob/ea7ebb9276db0a0675eb80385b6f97d4c6c48c60/pkg/cmd/roachprod/main.go#L252)):

``` shell
Error:  malformed cluster name ericharmeling-geo-partitioning, did you mean one of [eric.harmeling-geo-partitioning]
```

I try again, with `eric.harmeling` as the username:

``` shell
ericharmeling$ export CLUSTER="eric.harmeling-geo-partitioning"
ericharmeling$ roachprod create $CLUSTER --geo --gce-zones=us-east1-b,us-east1-c,us-east1-d,us-central1-a,us-central1-b,us-central1-c,us-west1-a,us-west1-b,us-west1-c,us-east1-b,us-central1-a,us-west1-a --local-ssd --nodes=12
```

`roachprod` throws the following error (from [here](https://github.com/cockroachdb/cockroach/blob/ea7ebb9276db0a0675eb80385b6f97d4c6c48c60/pkg/cmd/roachprod/main.go#L203)):

``` shell
Error:  cluster name must match ^[a-zA-Z0-9\-]+$
```

I use the `--username` tag (AFAIK only documented [here](https://github.com/cockroachdb/cockroach/blob/ea7ebb9276db0a0675eb80385b6f97d4c6c48c60/pkg/cmd/roachprod/main.go#L189) and a little with `roachprod create --help`)):

``` shell
ericharmeling$ roachprod create $CLUSTER --geo --gce-zones=us-east1-b,us-east1-c,us-east1-d,us-central1-a,us-central1-b,us-central1-c,us-west1-a,us-west1-b,us-west1-c,us-east1-b,us-central1-a,us-west1-a --local-ssd --nodes=12 --username=ericharmeling
```

Success!

``` shell
Creating cluster ericharmeling-geo-partitioning with 12 nodes
```

**Comment by ajwerner** [comment]
We're not going to have a good time supporting `.`s in cluster names due to their use in DNS names but fortunately the `.` is not meaningful in google user account names and our usernames here are google accounts. The fix is going to be to remove any dots from usernames upon initialization. I'll get to it soon.
