### ISSUE TITLE
sql: audit and refactor addition/removal of FK references and backreferences

### ISSUE THREAD

**Issue by lucy-zhang** [cockroachdb/cockroach#38776]
#38733 is a bug that results from erroneously removing FK references without removing backreferences (or vice versa) during DROP INDEX. There are likely other bugs resulting from a failure to add/remove both the reference and backreference at the same time. We should audit all the places where we add/remove FK references or backreferences to ensure that they're updated in the same transaction, and refactor the existing code (which generally treats the two steps separately) to make it harder to introduce these bugs.

**Comment by otan** [comment]
I'm not sure how to best refactor adding FKs to avoid this kind of bug, since it's only in two places: create table, which adds forwards and back in `ResolveFK`, and `alter table add constraint`, which relies on the schema changer to do it in `done` and shares very little common logic.

I could see a way forward with removing, which has been added in the above PR.

**Comment by lucy-zhang** [comment]
@otan and I discussed in person. The plan is to basically proceed with the approach in #43983 to also add FKs to the table descriptor (which includes adding them to `{Outbound,Inbound}FKs` in the schema changer in addition to the two places mentioned above), and possibly for updating FKs when renaming or validating them. An ideal API for updating FKs would ensure that the same transaction is used for updating both table descs, but that would involve too much refactoring at this point. For now we will expect callers to do this without enforcing it.

**Comment by otan** [comment]
(silently dropping out for me to do for now since there's a new schema team who probably knows/has a better idea for later!, there is a reference PR for Out/Inbound FKs)

**Comment by postamar** [comment]
I believe we can close this now.
