### ISSUE TITLE
jobs: add a `SHOW JOB <jobid>` statement

### ISSUE THREAD

**Issue by rolandcrosby** [cockroachdb/cockroach#38802]
We currently provide `SHOW JOBS`, which allows a user to view all active jobs in a cluster, but there's currently no friendly way to query the state of a specific job. This is turning into more of an annoyance as we add more statements that return IDs of long-running jobs (e.g. `CREATE CHANGEFEED`, or `BACKUP/RESTORE ... RETURNING ID` after #35048 is implemented). We should build a `SHOW JOB <jobid>` statement that allows a user to view the state of a specific job by ID, regardless of the job's current state. It should return the job data immediately (i.e. not block or wait for the job to complete) in the same format as the existing `SHOW JOBS` output.

**Comment by spaskob** [comment]
Is there a similar PR I can look at that adds or modifies existing keyword semantics?

**Comment by adityamaru27** [comment]
I used the changes to `sql.y` in https://github.com/cockroachdb/cockroach/pull/37603/commits/d68329f68fdd29d2d6d3023b4c5c0112cf0d5051 as a reference when I made my first yacc change. It adds a keyword.

Something I recently added to the parser grammar was - https://github.com/cockroachdb/cockroach/pull/38589/commits/a111dacf331c28b62f2bafe949392ae776942d49
