### ISSUE TITLE
importccl: read SQL schema after planning phase

### ISSUE THREAD

**Issue by rolandcrosby** [cockroachdb/cockroach#38801]
When importing a MySQL or Postgres SQL dump file, or when importing a CSV file using the `CREATE USING` option, `IMPORT` currently reads the entire SQL file from cloud storage during the planning phase before actually kicking off a job. Because we eventually want to support asynchronous job management for `IMPORT` (i.e. support returning a job ID as early as possible, as in #35048), it will be necessary to move the initial schema read downstream of the initial planning phase. This will let us return a job ID without having to block on reading an entire SQL dump file (or schema file) from cloud storage.

This will also require us to plumb through any K/V options affecting the schema, since we will not have access to the planner once the job is started.

**Comment by dt** [comment]
#48598
