### ISSUE TITLE
jobs: add a `WAIT FOR JOB <jobid>` statement

### ISSUE THREAD

**Issue by rolandcrosby** [cockroachdb/cockroach#38803]
As a follow-on to #38802, it would be nice to add a `WAIT FOR JOB <jobid>` statement that blocks until the provided job ID reaches a terminal state, then returns that job state in the same format as the `SHOW JOBS` output. In combination with asynchronous job creation, this could make it easier to avoid polling when scripting long-running tasks like backup and restore.

**Comment by dt** [comment]
personally I think I have a slight preference towards a flag on the `SHOW JOB` (e.g. as a straw man `SHOW JOB 12345 WHEN COMPLETE`) rather than adding a new top-level statement. /2¢
