### ISSUE TITLE
"show database" fails in command-line client

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#3882]
Running `cockroach sql --insecure` then `show databases;`:

```
query error: util/encoding/encoding.go:426: did not find marker
```

That used to work a few days ago.

or with a previously created database `test`, `select database test;`:

```
query error: qualified name """.database" not found
```

The error is at best confusing, at worst likely incorrect.

**Comment by tschottdorf** [comment]
I0115 05:27:43.921338 72722 cli/start.go:142  build Tag:
 v0.1-alpha-424-g78ae391
I0115 05:27:43.921347 72722 cli/start.go:143  build Time: 2016/01/15
10:11:40

macts.local:26257> show databases;
I0115 05:27:55.517242 72795 context.go:168  running in insecure mode, this
is strongly discouraged. See --insecure and --certs.
+----------+
| Database |
+----------+
| system   |
+----------+
macts.local:26257> create database x;
I0115 05:28:21.580285 72917 context.go:168  running in insecure mode, this
is strongly discouraged. See --insecure and --certs.
OK
macts.local:26257> show databases;
+----------+
| Database |
+----------+
| system   |
| x        |
+----------+
macts.local:26257>


Did you do anything else?

**Comment by knz** [comment]
This is on an AWS instance freshly updated with `cockroach.78ae391f73d5a275b9eb6e9b95dc054653517933`.

**Comment by petermattis** [comment]
I think this is related to #3553 which changed the on-disk encoding. I think if you start a fresh cluster it should work fine. We need a better story about versioning here.

**Comment by knz** [comment]
Thanks for the explanation. What do I need to reset to "start a new cluster"? I erased all my data files named in --store but the error persists. Does cockroach write state in other locations as well?

**Comment by petermattis** [comment]
Hmm, that should be sufficient. Cockroach doesn't store anything outside of the store directories. This isn't happening for me either when I tested just now. I'm not sure what is going on. Can you locally build a cockroach binary and run it using `cockroach start --dev`? I'm curious if `SHOW DATABASES` fails for you there as well.

**Comment by knz** [comment]
Found the cause of the error, it was a consequence of #3909. Now working as expected.
