### ISSUE TITLE
roachprod doesn't respect specified availability zones on aws

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#38835]
In roachprod I specified different availability zones:

roachprod create $CLUSTER -n 12 --clouds=aws --aws-machine-type-ssd=c5d.4xlarge --geo --aws-zones=us-east-1a,us-east-1b,us-east-1c,eu-west-2a,eu-west-2b,eu-west-2c,ap-northeast-1a,ap-northeast-1c,ap-northeast-1d,us-east-1a,eu-west-2a,ap-northeast-1a 

But it doesn't respect them:
![image](https://user-images.githubusercontent.com/22278911/61088920-81bec400-a407-11e9-89bd-3792996c900a.png)

**Comment by ajwerner** [comment]
Fixed by #40931.
