### ISSUE TITLE
ui: latency of DML with RETURNING clause incorrectly tracked on statements page

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#38830]
I noticed that latency figures for INSERT and UPDATE statements on the statements page seemed to disagree with a load generator. It looks like adding a RETURNING clause to these statements somehow impacts the latency values that we attribute to them.

Here's an example of the same INSERT statement run a series of times with and without a RETURNING clause:

<img width="1422" alt="Screen Shot 2019-07-11 at 5 31 10 PM" src="https://user-images.githubusercontent.com/5438456/61086827-ea0aa700-a401-11e9-9350-2c6fb9cbe918.png">

Notice that the form without a RETURNING clause (the top one) is shown to take significantly more time. When issuing the statements, I observed latency that agreed with this value regardless of whether I included a RETURNING clause.

**Comment by piyush-singh** [comment]
Chatted with @jordanlewis briefly, this is likely an issue with our underlying telemetry that collects statement performance information

**Comment by jordanlewis** [comment]
I can't reproduce this with a simple scenario:

```
root@:26257/defaultdb> insert into t values(1);
INSERT 1

Time: 4.507ms

root@:26257/defaultdb> truncate t;
TRUNCATE

Time: 39.03ms

root@:26257/defaultdb> insert into t values(1) returning *;
  x |  y
+---+------+
  1 | NULL
(1 row)

Time: 3.95ms

root@:26257/defaultdb> select key, service_lat_avg,last_error from crdb_internal.node_statement_statistics where key like 'INSERT INTO t%';
                  key                  | service_lat_avg | last_error
+--------------------------------------+-----------------+------------+
  INSERT INTO t VALUES (_)             |         0.00433 | NULL
  INSERT INTO t VALUES (_) RETURNING * |        0.003196 | NULL
(2 rows)
```
