### ISSUE TITLE
builtins: add width_bucket builtin function

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#38855]
The `width_bucket` builtin is a super useful function that figures out where a number lies inside of a histogram given certain parameters.

We should implement these. It's a pretty simple task that will boost compatibility (and help make `ALTER TABLE SPLIT BY` a lot easier to run).

This is a great issue for new contributors. The implementation of this builtin (well, each of its 3 overloads defined in the Postgres docs below) should live in `pkg/sql/sem/builtins/builtins.go`.

https://www.postgresql.org/docs/11/functions-math.html

**Comment by Inconnu08** [comment]
I'll take on this

**Comment by jordanlewis** [comment]
@Inconnu08 great! Do let me know if you need pointers.

**Comment by Russiancold** [comment]
@jordanlewis Hi! What is the actual status of this issue?

**Comment by Inconnu08** [comment]
@Russiancold Hey, I'm still working on this. But I'll let you know if I can't. :)

**Comment by Russiancold** [comment]
@Inconnu08 Alright

**Comment by barbourkd** [comment]
Hope you don't mind, but I took a stab at this since there wasn't much movement on it. #39263 

@jordanlewis One thing I was unsure of is if it is necessary to have the overload for Numeric and Decimal? I created an overload for decimal and have been unable to find a situation where it doesn't work.

**Comment by Inconnu08** [comment]
Ahh, I was almost halfway there. Stuck with the tests. Hence I didn't PR until completely done. But it's completely fine. :)
