### ISSUE TITLE
Unable to use with update returning in following select clause "SQL Error [42P01]: ERROR: no data source matches prefix:"

### ISSUE THREAD

**Issue by dodtsair** [cockroachdb/cockroach#38860]
**Describe the problem**

I am updating a table, using returning to pull out fields, then attempting to use those fields in a following select clause.  However I get the error "ERROR: no data source matches prefix:"
    
```
WITH as_updated AS (UPDATE a_table SET value = '91377f81-1d04-48da-85e0-b2d55f5e7f5b'::UUID WHERE true RETURNING value);
SELECT * FROM a_table WHERE a_table.value = as_updated.value
```

**To Reproduce**

In a blank database run the following ddl and dml:
```
CREATE TABLE a_table (
    value UUID DEFAULT gen_random_uuid(),
    id UUID DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY
);
    
INSERT INTO a_table (id, value) VALUES 
    ('a3864e49-cb4c-430e-a9fe-feacdd4cd9e7'::UUID, '85a53d09-aa1e-483b-bb6a-f12b4a069e16'::UUID), 
    ('8b6b57d8-3ed9-4f40-9a42-1c6b0e324fad'::UUID, '93286909-3ddf-4289-b52d-858c63525899'::UUID); 

WITH as_updated AS (UPDATE a_table SET value = '91377f81-1d04-48da-85e0-b2d55f5e7f5b'::UUID WHERE true RETURNING value);
SELECT * FROM a_table WHERE a_table.value = as_updated.value
```

**Expected behavior**
Result set should be
```
91377f81-1d04-48da-85e0-b2d55f5e7f5b 
91377f81-1d04-48da-85e0-b2d55f5e7f5b
```

**Environment:**
 - CockroachDB version: CockroachDB CCL v19.1.2 (x86_64-unknown-linux-gnu, built 2019/06/07 17:32:15, go1.11.6)
 - Server OS: Linux/Docker (cockroachdb/cockroach:v19.1.2)
 - Client app: DBeaver

**Additional context**
In the broader use case not shown, I am trying to do a conditional update on one table, then use returning to pull out the ids of the records updated and join that against another table.  However I cannot seem to use a sql update returning in the with clause and use that in a following select.  I keep getting told that the with clause identifier data source does not exist.  Now if I remove the reference to the data source in the select statement I get another error saying I am not using cte with side effects:

```
WITH as_updated AS (UPDATE a_table SET value = '91377f81-1d04-48da-85e0-b2d55f5e7f5b'::UUID WHERE true RETURNING value)
SELECT * FROM a_table;
```

`SQL Error [0A000]: ERROR: unimplemented: common table expression "as_updated" with side effects was not used in query`

I searched the bug list of similar issues and found #28956 similar, except in his cause he is looking for the best way to get old value back, and encounters the same problem in what he sees has a hack/bad practice of using a with returning clause against the same table.

**Comment by jordanlewis** [comment]
You need to use a join in your original query. The following works for me:

```
WITH as_updated AS (UPDATE a_table SET value = '91377f81-1d04-48da-85e0-b2d55f5e7f5b'::UUID WHERE true RETURNING value)
SELECT * FROM a_table join as_updated on a_table.value = as_updated.value;
```

**Comment by idubrov** [comment]
@jordanlewis this query gives me `pq: no data source matches prefix: as_updated`.

CockroachDB: v19.1.5

**Comment by idubrov** [comment]
Seems to be working with v19.2.0.

**Comment by jordanlewis** [comment]
Thanks, yes we don't expect this to work in 19.1 - didn't realize earlier.
