### ISSUE TITLE
ui: improve 404 error message in Admin UI

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#38885]
@timveil was setting up a cluster via terraform and the Admin UI was showing consistent 404s when he tried to connect. It was unclear what exactly the problem was (trying to hit the overview page).

@vilterp had a hunch that the Admin UI hadn't finished initializing during the cluster startup and therefore was serving 404 errors. We should improve the error message here so that users can troubleshoot this issue.

Jira issue: CRDB-5602

**Comment by vilterp** [comment]
Yeah, I think that if the `Server.start` method gets blocked before it gets to these lines, you get a 404: https://github.com/cockroachdb/cockroach/blob/c097a16427f65e9070991f062716d222ea5903fe/pkg/server/server.go#L1694-L1701 (though I didn't think we started up the server until later, so I kind of would expect it not to connect at all… would need to read the code more to understand)

This is yet one more consequence of `Server.start` being a 700-line beast that no one understands 😛 

We could either make it not connect at all, or have a handler which serves a "service unavailable" until the real endpoints are registered…

**Comment by rolandcrosby** [comment]
@timveil and I hit this again the other day, this time after stopping a running cluster and attempting to restart the nodes after changing some flags. I was able to reproduce the behavior (or something close to it) in a roachprod cluster earlier this afternoon, let me know if the logs would help with anything.

**Comment by myles-mcdonnell** [comment]
I'm just running through the tutorials; I ran up a 3 node cluster, then I `kill -9` all the processes.  Then I `rm -rf` all the data dirs.  Then I uninstall and reinstall using brew but when I try to start a fresh cluster the admin UI just gives me 404.  Must be some corrupt state hanging around somewhere I guess? Will have to install a VM to get a fresh env (which I should have done in the first place anyway)
