### ISSUE TITLE
sql/pgwire: send proper tags when returning an Ack message

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#3890]
We currently have a comment [here](https://github.com/cockroachdb/cockroach/blob/master/sql/pgwire/v3.go#L676) which I have found to be incorrect in practice. For instance, Go's pg driver requires that these tags be returned for operations like BEGIN, COMMIT, or ROLLBACK. See [here](https://github.com/lib/pq/blob/master/conn.go#L517).

**Comment by tamird** [comment]
How come this doesn't manifest as a test failure? Can you reproduce this in a test?

**Comment by dt** [comment]
@mjibson and I were looking at this yesterday (in process of looking at #3849). The tag contents are documented on http://www.postgresql.org/docs/current/static/protocol-message-formats.html

**Comment by nvanbenschoten** [comment]
@tamird I don't think we ever use any of these commands in a test with a postgre driver. For instance, the only place in our entire codebase where we open a transaction from a sql/driver is when [testing the old cockroach driver](https://github.com/cockroachdb/cockroach/blob/master/sql/driver/driver_test.go#L375).

**Comment by tamird** [comment]
Ah, right. Seems like we send `BEGIN` as a "statement" in the logic tests, side-stepping this issue.

**Comment by dt** [comment]
like #3852, despite being pg-wire specific, this will probably want to get propagated through the driver and handled by the actual parser, right?

**Comment by nvanbenschoten** [comment]
It seems like the link @dt provided is missing some of the tags that are sent back by postgres. I'm not sure if that means postgres returns more than the actual protocol defines, but it seems like drivers are expecting more that the protocol. [Here's](https://github.com/postgres/postgres/blob/master/src/backend/tcop/utility.c#L1901) the list of all tags returned by postgres. It requires a handle on the parse tree, so I assume this would need to get propagated through the driver and handled by the parser.

**Comment by dt** [comment]
It's possible the go driver is unusual in actually looking at the tag and not just the result code:
looking at ruby's pg, (which leaves most of the work to libpq) it doesn't check.
psycopg2, if I've managed to follow all the c linked c modules, doesn't either https://github.com/psycopg/psycopg2/blob/master/psycopg/pqpath.c#L461

**Comment by nvanbenschoten** [comment]
I think you're right that it's not completely standard to check, but it seems to me like a good idea to comply with what Postgres sends if possible. Also, interestingly the [commit](https://github.com/lib/pq/commit/44ea1b5c0bf9099acec9e6c5f13b2c28008ca315) that introduced the tag checking to Go's primary sql/driver cited libpg as doing the same.

**Comment by dt** [comment]
I'm guessing that commit comment is referring to https://github.com/postgres/postgres/blob/master/src/interfaces/libpq/fe-protocol2.c#L1074 though it isn't completely clear to me what xactStatus is for -- I guess it is surfaced in `PQtransactionStatus` though.
