### ISSUE TITLE
exec: EXISTS hangs with distributed vectorize

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#38919]
Found when running `fakedist` config on `subquery` logic test with "streaming" by default.

To reproduce, I created a 3 node local cluster with (in 4 separate tabs):
`./cockroach start --insecure --store=node1 --listen-addr=localhost:26257 --http-addr=localhost:8080 --join=localhost:26257,localhost:26258,localhost:26259`
`./cockroach start --insecure --store=node2 --listen-addr=localhost:26258 --http-addr=localhost:8081 --join=localhost:26257,localhost:26258,localhost:26259`
`./cockroach start --insecure --store=node3 --listen-addr=localhost:26259 --http-addr=localhost:8082 --join=localhost:26257,localhost:26258,localhost:26259`
(this might not be necessary)
`./cockroach init --insecure --host=localhost:26257`

And run the following commands:
```
CREATE TABLE t (a INT PRIMARY KEY);
INSERT INTO t VALUES (1), (2), (3);
SELECT a FROM t WHERE EXISTS(SELECT * FROM t WHERE true);
```
This succeeds, but if we turn on vectorized, the last query hangs:
```
root@:26257/defaultdb> SELECT a FROM t WHERE EXISTS(SELECT * FROM t WHERE true);
  a  
+---+
  1  
  2  
  3  
(3 rows)

Time: 3.275ms

root@:26257/defaultdb> SET experimental_vectorize=on;
SET

Time: 350µs

root@:26257/defaultdb> SELECT a FROM t WHERE EXISTS(SELECT * FROM t WHERE true);
^C
```

**Comment by yuzefovich** [comment]
Probably a related failure occurs if we add `5node-dist-vec` config to `planner_test/distsql_subquery`:
```
                expected:
                    https://cockroachdb.github.io/distsqlplan/decode.html#eJyMj0FLxDAUhO_-ijKnXQmYXgNelIgFdaVdVJAcYvJYizUpeQkIS_-7bHMQD4LH-SaZmXdEiJ4e7Ccx1CtaGIE5RUfMMZ1QfdD5LygpMIa55BM2Ai4mgjoij3kiKDzZqRBfSAh4ynac1kTZXDUb2bj3Ej54C4GegqekGv3SDfthM-g7fb0_v-l39_bNPd_qXtvLdguzCMSSf-o42wNByUX8f1JPPMfA9GvS38lGgPyB6tkcS3L0mKJba6rcrf9W4IlzddsqulCtxSxn3wEAAP__zL5u_w==
                    
                but found (query options: "") :
                    https://cockroachdb.github.io/distsqlplan/decode.html#eJyMj7GKwzAQRPv7CjO14ORWf-DmLqQNKoS0GIOiNVopBIz-PVgq0rqcNzM77IHEgf7ckwTmgRlWYc_sSYTziUZgCW8YrbClvZYTWwXPmWAOlK1EgkFk7-L0crGSTPpXQyFQcVvs-abAtXzbUtxKMHNT1xfuJDsnoUuXdbMKFFYaXwjX7OmW2feZIf97r4NAUoY7D7GkYTXbfj4BAAD__xM4YY8=
```

**Comment by jordanlewis** [comment]
The goroutine that's hung is here:

```
goroutine 1850 [select]:
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Wait(0xc00180a000)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:675 +0x106
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Run(0xc00180a000, 0x7c22500, 0xc00141aea0, 0x750b0f8, 0x0, 0x0)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:659 +0x1fe
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc0005ccb40, 0xc001549080, 0xc0020c4e10, 0xc001670740, 0xc0011fd8c0, 0xc0016c7400, 0x0, 0x0)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:299 +0x368
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).planAndRunSubquery(0xc0005ccb40, 0x7c22500, 0xc00141a3f0, 0x0, 0xc00141a870, 0x1, 0x1, 0x7c24340, 0xc0012bb1e0, 0x0, ...)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:800 +0x7d5
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunSubqueries(0xc0005ccb40, 0x7c22500, 0xc00141a3f0, 0xc0019c0350, 0xc00044cfe0, 0xc0014a38c0, 0x1, 0x1, 0xc0011fcdc0, 0xc0019c0101, ...)
```

**Comment by jordanlewis** [comment]
This definitely has to do with fallback logic. `SELECT * FROM t WHERE true` is not supported by the vectorized engine, apparently, because we don't handle selections on booleans, and by the time the subquery trickles down to the execution engine it still contains a filter. That part is rather suspicious on its own, but for now, I think the fallback logic must be getting confused somehow.

**Comment by jordanlewis** [comment]
Once we applied the fix in #38977, this went away.

**Comment by yuzefovich** [comment]
If we turn vectorized "on" (with #38992), the issue remains.

Possibly a related difference:
```
                testdata/planner_test/distsql_subquery:21: SELECT url FROM [EXPLAIN ANALYZE (DISTSQL) SELECT EXISTS (SELECT max(a) FROM abc)]
                expected:
                    https://cockroachdb.github.io/distsqlplan/decode.html#eJyMj0FLAzEUhO_-imVOLQRMr7m1ngriSiteJIclGerimix5LyCU_e_SzUE8CB7nm2Rm3hUpRz4NnxS4N-zgDeaSA0VyuaH24Bi_4KzBmOaqN-wNQi6Eu0JHnQiH12GqlHsLg0gdxmlNtN2h29guvNf0IVsYnJgii-se9ueXjZbK_fnQ949b-MUgV_0pEB0uhLOL-f-IE2XOSfhrxN_J3oDxwnao5FoCn0sOa02T_fpvBZGizd01cUzNWvxy9x0AAP__guVrPA==
                    
                but found (query options: "") :
                    https://cockroachdb.github.io/distsqlplan/decode.html#eJyMj8FKAzEYhO8-xTKnFgKm19xaTwVxpRUvkkNIxrq4Jkv-BISy7y67OYgHocf5JpmZ_4qYAp_cFwXmDTtYhSknT5GUF9QeHMM3jFYY4lTLgq2CT5kwV5ShjITBqxsr5V5DIbC4YVwTdXfoNrrzHzV-yhYKJ8bAbLqH_fll8-5G4f586PvHLeyskGr5bZDiLoTRs7p9xYkypSj8s-L_ZKvAcGG7VFLNns85-bWmyX79t4JAKc3dNXGMzZrtfPcTAAD__-Z_a4c=
```

**Comment by yuzefovich** [comment]
The difference in explain is (I think) easily explained by #38858, so it probably was a false alarm.

**Comment by yuzefovich** [comment]
The difference in explain was a false alarm.

However, I'm concerned on how we handle subqueries. Here is what happens on `SELECT a FROM t WHERE EXISTS(SELECT * FROM t WHERE true)` with `vectorize=on`:
1. we attempt to run the subquery through vectorized
 - we check whether it is supported (and it is), so we attempt to set up vectorized flow. This fails when setting up outboxes with
```
  - zero length schema unsupported
    github.com/cockroachdb/cockroach/pkg/sql/exec/colserde.NewRecordBatchSerializer
    	/Users/yahoryuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/exec/colserde/record_batch.go:73
```
The reason is that we have a projection with no output columns and a limit 1. We create `colBatchScan` with a single `Int` output type, but then `columnTypes` are updated here:
https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/distsqlrun/column_exec_setup.go#L582-L589
 - so the vectorized setup fails, and we fallback to DistSQL. The subquery is now executed through the latter.
2. we attempt to run the main query through vectorized
 - we check whether it is supported, and it isn't because of `unable to columnarize filter expression "CAST(true AS BOOL)": unhandled selection expression type: *tree.DBool`
 - we go straight to using DistSQL

Now, my concerns are:
1. should the main query go straight to DistSQL if a subquery's vectorization failed for some reason?
2. what to do about zero-length schema with subqueries in `EXISTS` mode? cc @asubiotto

P.S. I think I saw subqueries hanging yesterday even with #38992 because I forgot about issues with in sync pools in `ReleaseSetupFlowRequest`.

**Comment by yuzefovich** [comment]
This hangs reliably on `fakedist-opt` config if we set `experimental_vectorize` to `on` in `exec_util.go`:
```
# LogicTest: fakedist-opt

statement ok
CREATE TABLE t (k INT PRIMARY KEY, v INT)

statement ok
INSERT INTO t VALUES (1, 10), (2, 20), (3, 30)

query B
SELECT EXISTS(SELECT * FROM t WHERE k > 2)
----
true
```

**Comment by yuzefovich** [comment]
Here is an updated reproduction (which should trigger the problem every time) with `experimental_vectorize=on` in `exec_util.go`:
```
# LogicTest: fakedist-opt

statement ok
CREATE TABLE t (k INT PRIMARY KEY, v INT)

statement ok
INSERT INTO t VALUES (1, 10), (2, 20), (3, 30)

statement ok
SET CLUSTER SETTING kv.range_merge.queue_enabled = false

statement ok
ALTER TABLE t SPLIT AT VALUES (2), (3)

statement ok
ALTER TABLE t EXPERIMENTAL_RELOCATE VALUES (ARRAY[1], 1), (ARRAY[2], 2), (ARRAY[3], 3)

query TTTI colnames
SELECT start_key, end_key, replicas, lease_holder from [SHOW EXPERIMENTAL_RANGES FROM TABLE t]
----
start_key  end_key  replicas  lease_holder
NULL       /2       {1}       1
/2         /3       {2}       2
/3         NULL     {3}       3

query B
SELECT EXISTS(SELECT * FROM t WHERE k > 2)
----
true
```
Before, there was a chance that the query ends up having a local flow because the data was on a single (gateway?) node.

**Comment by yuzefovich** [comment]
The repro above works very good (but not 100% of the time). Unfortunately, I can't seem to be able to reproduce it outside of logic tests.

**Comment by yuzefovich** [comment]
I think I managed to make some progress on why the query `SELECT EXISTS(SELECT * FROM t WHERE k > 2)` hangs. Here are important things to note:
- this query is supported through vectorized engine
- it hangs when `colBatchScan` for the subquery is planned on a remote node
- the subquery is run in `EXISTS` execution mode

Say `n1` is gateway and `n2` is the remote with `colBatchScan`. All the distributed infrastructure (i.e. `Inbox`es and `Outbox`es are set up correctly). However, I believe this particular scenario is not handled by `materializer`s/`Inbox`es correctly. This is what's happening:
- `n2` correctly reads the data and sends it through `Outbox`. The `Outbox` then gracefully terminates.
- `Inbox` on `n1` correctly receives a single row from `n2`, then `n1` propagates the row through a noop and a materializer and pushes it into `DistSQLReceiver`. Now, because the subquery is in `EXISTS` mode, the receiver returns `ConsumerClosed` status, `materializer.ConsumerClosed()` is called. It closes only base processors stuff, but the `Inbox` is left hanging. Forever.

I'm not sure how to fix it though. @asubiotto @jordanlewis any suggestions?

**Comment by asubiotto** [comment]
Where is the Inbox stuck and how does the Outbox terminate? Usually an EOF from the remote stream would unblock the Inbox. Also, ConsumerClosed should result in DrainMeta getting called on the Inbox, I would double check that that happens when the materializer gets ConsumerDone called.

**Comment by yuzefovich** [comment]
Here is a snapshot of logs:
```
I190724 15:08:23.742055 1730 sql/distsql_running.go:868  [n1,client=127.0.0.1:61859,user=root] running subquery
I190724 15:08:23.742080 1730 sql/distsql_running.go:340  [n1,client=127.0.0.1:61859,user=root] running DistSQL plan
I190724 15:08:23.742496 1871 sql/exec/colrpc/outbox.go:111  [n2,streamID=0] Outbox Dialing 1
I190724 15:08:23.742555 1871 sql/exec/colrpc/outbox.go:133  [n2,streamID=0] Outbox sending header
I190724 15:08:23.742645 1871 sql/exec/colrpc/outbox.go:146  [n2,streamID=0] Outbox starting normal operation
I190724 15:08:23.742714 1871 sql/exec/colrpc/outbox.go:196  [n2,streamID=0] Outbox is calling Next on its input
I190724 15:08:23.742775 2009 sql/exec/colrpc/inbox.go:168  [n1] Inbox handling stream
I190724 15:08:23.742796 1730 sql/exec/colrpc/inbox.go:234  [n1,client=127.0.0.1:61859,user=root] Inbox is calling Recv
I190724 15:08:23.742828 2009 sql/exec/colrpc/inbox.go:178  [n1] Inbox reader arrived
I190724 15:08:23.742903 2194 sql/exec/colrpc/outbox.go:272  [n2,streamID=0] Outbox received handshake: consumer_scheduled:true version:23 min_accepted_version:23 
I190724 15:08:23.799543 1871 sql/exec/colrpc/outbox.go:221  [n2,streamID=0] Outbox is sending a message
I190724 15:08:23.799589 1871 sql/exec/colrpc/outbox.go:196  [n2,streamID=0] Outbox is calling Next on its input
I190724 15:08:23.799606 1871 sql/exec/colrpc/outbox.go:202  [n2,streamID=0] Outbox received zero-length batch from its input
I190724 15:08:23.799617 1871 sql/exec/colrpc/outbox.go:283  [n2,streamID=0] Outbox terminated gracefully
I190724 15:08:23.799627 1871 sql/exec/colrpc/outbox.go:166  [n2,streamID=0] Outbox moved to draining
I190724 15:08:23.799636 1871 sql/exec/colrpc/outbox.go:293  [n2,streamID=0] Outbox is closing Send channel
I190724 15:08:23.799802 1730 sql/exec/colrpc/inbox.go:270  [n1,client=127.0.0.1:61859,user=root] Inbox is returning 3 30
I190724 15:08:23.799856 1730 sql/distsql_running.go:590  [n1,client=127.0.0.1:61859,user=root] DistSQLReceiver is pushing
```
So what happens is that Outbox receives a batch of length 1, sends it, then receives a zero-length batch and terminates gracefully. Inbox receives a batch of length 1, but `Next` is never get called on it again because `DistSQLReceiver` doesn't need more input from the source (a chain of `Inbox -> noopOperator -> materializer`). I believe Inbox gets stuck here https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/exec/colrpc/inbox.go#L183-L196:
```
	// Now wait for one of the events described in the method comment. If a
	// cancellation is encountered, nothing special must be done to cancel the
	// reader goroutine, as returning from the handler will close the stream.
	select {
	case err := <-i.errCh:
		// nil will be read from errCh when the channel is closed.
		return err
	case <-readerCtx.Done():
		// The reader canceled the stream.
		return fmt.Errorf("%s: readerCtx in Inbox stream handler (local reader canceled)", readerCtx.Err())
	case <-streamCtx.Done():
		// The client canceled the stream.
		return fmt.Errorf("%s: streamCtx in Inbox stream handler (remote client canceled)", streamCtx.Err())
	}
```
because none of the described termination events occur.

`DrainMeta` is never called on `Inbox` because we're in the case here https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/distsqlrun/base.go#L181-L184:
```
			case ConsumerClosed:
				src.ConsumerClosed()
				dst.ProducerDone()
				return
```
so `ConsumerClosed` is called on `materializer`, and it simply calls `InternalClose` which does not drain.

If I modify the method as follows:
```
 func (m *materializer) ConsumerClosed() {
+       m.trailingMetaCallback(m.Ctx)
        m.InternalClose()
 }
```
then `Inbox` gets drained and closed correctly, and the query succeeds. Does this seem like an appropriate fix?

**Comment by yuzefovich** [comment]
I've opened a PR with the fix I mentioned above, and it should unblock the "streaming" setting, but I think it is a hacky way of solving this problem, so I'll keep the issue open.
