### ISSUE TITLE
this is a test

### ISSUE THREAD

**Issue by RoachietheSupportRoach** [cockroachdb/cockroach#38928]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#3498](https://cockroachdb.zendesk.com/agent/tickets/3498)
**Group:** Support
**Requester:** support@cockroachlabs.com
**Issue escalated by:** RoachietheSupportRoach

**Original ticket description:**

<blockquote><div class="zd-comment" dir="auto">
<p dir="auto">this is a test</p>
<p dir="auto"><a href="mailto:support@cockroachlabs.com" rel="noreferrer">support@cockroachlabs.com</a></p>
</div></blockquote>

**Comment by ricardocrdb** [comment]
test update

**Comment by ricardocrdb** [comment]
test test

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[3498](https://cockroachdb.zendesk.com/agent/tickets/3498) has been linked to this issue.

**Comment by RoachietheSupportRoach** [comment]
*Comment made from Zendesk by Ricardo Rocha on 2019-07-18 at 14:13:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">test linking</p></div></blockquote>

**Comment by ricardocrdb** [comment]
bidirectional test?

**Comment by RoachietheSupportRoach** [comment]
*Comment made from Zendesk by Ricardo Rocha on 2019-07-18 at 14:15:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">test public</p></div></blockquote>
