### ISSUE TITLE
cli: need error message when trying to start single-node cluster with in-memory store

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#3893]
When you try to "manually" start a single-node cluster in the equivalent of dev mode by running `./cockroach start --insecure --stores=mem=10000 --gossip=self=`, it just hangs at `connecting to gossip network to verify cluster ID...`. @bdarnell suggested that we could detect when `--gossip=self` and `--stores=mem` and provide a better error. Maybe something like: 

It's not possible to initialize a single-node cluster with in-memory storage. Use the --dev flag instead.

**Comment by knz** [comment]
I have just tested using the latest master, with certificates generated first. You can cold-boot cockroach with `cockroach start --stores=mem=12312312`. There is no error and the database is functional.  Without certificates you run into  #4427 but that is a separate issue.
