### ISSUE TITLE
Support for Encrypted Certificates

### ISSUE THREAD

**Issue by roncrdb** [cockroachdb/cockroach#38930]
**Is your feature request related to a problem? Please describe.**
At the moment, if a user encrypts a certificate with a password, and then tries to use that cert with CRDB, an error is thrown. 

` problem using security settings: tls: failed to parse private key`

**Describe the solution you'd like**
We should add support for users who would like to use encrypted certs. 

It appears that the Go Standard Lib has a functions to detect and decrypt: 

[IsEncryptedPEMBlock](https://golang.org/pkg/crypto/x509/#IsEncryptedPEMBlock)
[DecryptPEMBlock](https://golang.org/pkg/crypto/x509/#DecryptPEMBlock)

**Describe alternatives you've considered**

**Additional context**
For context, here is the forum post where this came up: 

https://forum.cockroachlabs.com/t/does-cockroachdb-support-encyrpted-private-key/2928

Jira issue: CRDB-5601

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[3499](https://cockroachdb.zendesk.com/agent/tickets/3499) has been linked to this issue.

**Comment by knz** [comment]
cc @jtsiros for triage and tracking
