### ISSUE TITLE
Addtime in dynamic query

### ISSUE THREAD

**Issue by kishoresai438** [cockroachdb/cockroach#38982]
**Describe the problem**

Migrating from mysql to cockroachdb

**To Reproduce**

I want to add time to start time in same query. Currently I am using this in where condition

 ```
ADDTIME(start_at, SEC_TO_TIME(duration*60))
```

This function is not working in cockroach db. Can anyone suggest on this

**Comment by mattcrdb** [comment]
Hey @kishoresai438,

I replied to your forum thread from yesterday,but just in case you would like to have the discussion on Github, I will include my response here as well.

---
I can suggest utilizing our interval data type, the docs are here.

In your case, you would want to convert SEC_TO_TIME(duration*60) to an interval.

The supported time formats are listed in the docs.

The interval data type can also be cast, see below.

Example query with type casting:

SELECT now() + <time_to_add>::interval;
Let me know if this works for you!

Thanks,
Matt

---

**Comment by mattcrdb** [comment]
Checking in to see if you were able to use this as a workaround.

**Comment by mattcrdb** [comment]
I'm going to close this issue, please re-open if needed.
