### ISSUE TITLE
perf: impact of having 1 rocksdb instance / device

### ISSUE THREAD

**Issue by benoitc** [cockroachdb/cockroach#3900]
Why did you choose to have 1 instance / device instead of having 1 / db? Doesn't it limit the write concurrency?

**Comment by petermattis** [comment]
How are you defining the term `db`? A cockroach cluster spans many nodes, each node composed of 1 or more stores with each store being backed by a RocksDB instance. While RocksDB can be configured to store data in multiple directories (i.e. devices), I don't see any obvious advantage to doing so. Can you be more explicit in how you think the current setup might limit write concurrency? RocksDB is a single node system which is why I asked how you are defining the term `db`. We certainly couldn't have a single RocksDB instance for the entire cluster.

**Comment by benoitc** [comment]
@petermattis sorry I wasn't clear. 

In my understanding there is one store by device, on top of this K/V store you store ranges and do other K/V stup. On top of the K/V you're creating database and tables abstraction. Did I miss anything?

In such case I wondered why not having 1 store and group of ranges/DBs? Which impact does it have on the performance. How many keys should one node handle?

**Comment by petermattis** [comment]
I'm having a bit of trouble understanding your questions. Yes, cockroach places SQL tables and databases on top of the internal KV api. The internal KV system spreads data across multiple nodes and thus SQL tables and databases are spread across multiple nodes so there is no practical limit to the size of a table or database. The number of keys a single node can store is limited by the amount of disk available. For a node with 1 TB of disk and an average key/value size of 1 KB (which is probably high) a node would be able to store 1 billion key/value pairs.

**Comment by benoitc** [comment]
@petermattis I missed your response sorry. The thing I was trying to understand was the usage of 1 rocksdb instance / device. Indeed it means that you're using 1 WAL for all ranges on this instance, which somehow limit the number of concurrent writes. So I was curious what conducted that choice.

**Comment by petermattis** [comment]
@benoitc RocksDB is designed for one instance per storage device. Yes, there is only a single WAL per RocksDB instance, but individual write operations to RocksDB are batched in two different ways. The first is that Cockroach coalesces multiple writes for the same transaction (when possible) into a single `WriteBatch` operation. And RocksDB internally coalesces multiple `WriteBatch` objects being written concurrently by different threads into a single `WriteBatch` that is appended to the WAL.

**Comment by tamird** [comment]
Looks like the questions here were answered. #7531 notably changed some concurrency attributes that trickle down to RocksDB, but this is still being tuned in #7596.
