### ISSUE TITLE
exec: TestDistSQLRangeCachesIntegrationTest fails with vectorized enabled

### ISSUE THREAD

**Issue by solongordon** [cockroachdb/cockroach#39033]
When vectorized execution is enabled by default, `TestDistSQLRangeCachesIntegrationTest` fails. It looks like this tests that tablereaders can send metadata about misplanned ranges and the leaseholder cache is updated appropriately. `colBatchScan` has this logic as well, so it seems like the test should pass, but the test indicates that the cache is not getting updated.

To reproduce, change the default sql.defaults.experimental_vectorize value to on in exec_util.go and then run
```
make test PKG=./pkg/sql TESTS='TestDistSQLRangeCachesIntegrationTest'
```

**Comment by solongordon** [comment]
`TestSpanResolverUsesCaches` is also failing, though it's not clear to me if it's the same issue or not. (Note that you will want the fix from #38992, otherwise you're likely to run into a different failure.)

**Comment by solongordon** [comment]
It looks like `colBatchScan.DrainMeta` never gets called when this test is run, so there is no opportunity for the range metadata to get propagated. I'm looking into why.

cc @asubiotto @yuzefovich in case anyone knows off the top of their head why this might be the case.

**Comment by asubiotto** [comment]
Hmm, my guess would be that `colBatchScan` is probably wrapped in something that means that the resulting `op` from `newColOperator` does not implement `distsqlpb.MetadataSource` and therefore is not added to the queue. It's got to be something like that since we assert that we have no metadata sources left at the end of `setupVectorized`.

**Comment by solongordon** [comment]
Aha, I think you're exactly right: it's getting wrapped in a `CancelChecker`: https://github.com/cockroachdb/cockroach/blob/23defdb38d4359ea8883042ccadb6b7938299635/pkg/sql/distsqlrun/column_exec_setup.go#L139

**Comment by solongordon** [comment]
OK great, I made `CancelChecker` a metadata source which returns the metadata from its wrapped operator, and the test passes. I wonder if we need a more general solution to this issue though. It seems dangerous that an operator can implement `MetadataSource` and never get drained.

**Comment by asubiotto** [comment]
Yeah, definitely. This is probably another example where having a way to visit a tree of operators would be great.

**Comment by solongordon** [comment]
Unfortunately this did not fix `TestSpanResolverUsesCaches`. Opening a separate issue for that.
