### ISSUE TITLE
release: v19.2.0-alpha.20190805

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#39036]
Candidate SHA: 5bd37e8eb58ca66b9293c234bc572411057fec3a
Deployment status: testing on `nathan-release-v1920-alpha20190701` ([node 1](http://nathan-release-v1920-alpha20190701-0001.roachprod.crdb.io:26258)) and `nathan-release-v1920-alpha20190729` ([node 1](http://nathan-release-v1920-alpha20190729-0001.roachprod.crdb.io:26258))
Release Qualification Suite: [TeamCity](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_ReleaseQualification?branch=provisional_201908012151_v19.2.0-alpha.20190729) (**passed**)
Nightly Suite: [TeamCity](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_NightlySuite?branch=provisional_201908012151_v19.2.0-alpha.20190729) (**signing off**)
 
[Release process checklist](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process)
 
Prep date: `7/22/2019`
- [x] [Pick a SHA](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-PickingaSHA), fill in `Candidate SHA` above, notify #release-process of SHA.
- [x] [Tag the provisional SHA](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-TagtheprovisionalSHA)
- [x] [Publish provisional binaries](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Publishtheprovisionalbinaries)
- [x] [Check binaries](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Checkbinaries)
- [x] [Deploy to test clusters](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-DeploytoTestClusters)
- [x] [Start release qualification suite](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-RuntheSuiteofNightlyRoachtests)
- [x] [Start nightly suite](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-RuntheSuiteofNightlyRoachtests)
- [x] [Verify node crash reports](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Verifynodecrashreportsappearinsentry.io)
- [x] fill in `Deployment status` above with clusters and `Nightly Suite` with the link to Nightly TeamCity Job
 
- Keep an eye on clusters until release date. Do not proceed below until the release date.
 
Release date: `8/5/2019`
- [x] [Check cluster status](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Checkclusterstatus)
- [x] [Tag release](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Tagtherelease)
- [x] [Bless provisional binaries](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Blesstheprovisionalbinaries)
 
- [x] Update docs
- [x] External communications for release

**Comment by nvanbenschoten** [comment]
### Failed roachtest signoff

- [ ] `tpccbench/nodes=9/cpu=4/chaos/partition`
- [ ] `clearrange/checks=false`
- [ ] `clearrange/checks=true`
- [ ] `clock/jump/large_backward_enabled`
- [ ] `jepsen/register/split`

**Comment by nvanbenschoten** [comment]
`tpccbench/nodes=9/cpu=4/chaos/partition` failed when installing haproxy due to an apt-get failure.
```
Fetched 26.3 MB in 5s (5,069 kB/s)
Reading package lists...
E: Failed to fetch http://us-central1.gce.archive.ubuntu.com/ubuntu/dists/xenial/universe/binary-amd64/by-hash/SHA256/c8bc8c1425fef0712430d3991cf15ea96892aa5e13130b36c126fa90887ca756  Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.
Error:  exit status 100
06:37:56 test.go:269: test failure: 	tpcc.go:693,tpcc.go:559,test_runner.go:691: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod install teamcity-1564706298-09-n10cpu4:10 -- haproxy returned:
		stderr:
		
		stdout:
		iverse Translation-en [8,440 B]
		Get:38 http://us-central1.gce.archive.ubuntu.com/ubuntu xenial-backports/main Sources [4,848 B]
		Get:39 http://us-central1.gce.archive.ubuntu.com/ubuntu xenial-backports/universe Sources [6,740 B]
		Get:40 http://us-central1.gce.archive.ubuntu.com/ubuntu xenial-backports/main amd64 Packages [7,280 B]
		Get:41 http://us-central1.gce.archive.ubuntu.com/ubuntu xenial-backports/main Translation-en [4,456 B]
		Get:42 http://us-central1.gce.archive.ubuntu.com/ubuntu xenial-backports/universe amd64 Packages [7,804 B]
		Get:43 http://us-central1.gce.archive.ubuntu.com/ubuntu xenial-backports/universe Translation-en [4,184 B]
		Fetched 26.3 MB in 5s (5,069 kB/s)
		Reading package lists...
		E: Failed to fetch http://us-central1.gce.archive.ubuntu.com/ubuntu/dists/xenial/universe/binary-amd64/by-hash/SHA256/c8bc8c1425fef0712430d3991cf15ea96892aa5e13130b36c126fa90887ca756  Hash Sum mismatch
		E: Some index files failed to download. They have been ignored, or old ones used instead.
		Error:  exit status 100
		: exit status 1
```

**Comment by nvanbenschoten** [comment]
`clearrange/checks=true` failed due to a node hitting:
```
F190802 10:30:59.381932 105 storage/replica_raft.go:801  [n1,s1,r17332/4:/Table/53/1/4767{4005-6941}] while committing batch: IO error: No space left on deviceWhile appending to file: /mnt/data1/cockroach/029340.log: No space left on device
```

`clearrange/checks=false` timed out:
```
11:14:31 test.go:199: test worker status: dropping table
11:14:32 test.go:199: test worker status: computing number of ranges
1: 14929
8: 29732
3: 24382
10: 16741
6: 14114
2: 1042
4: 20558
7: 24278
9: 4540
5: 23522
11:14:32 test.go:199: test worker status: dropping bank table
11:47:43 test.go:290: test failure: 	test_runner.go:706: test timed out (6h30m0s)
```

@ajkr you've been looking into these tests in #38772 and #38720. Could you make a determination about whether these are concerning or expected, and whether they should block the release from going out?

**Comment by nvanbenschoten** [comment]
`clock/jump/large_backward_enabled` is what we're seeing in #38723: 
```
F190802 05:43:58.596975 167 util/hlc/hlc.go:241  detected forward time jump of 0.598804 seconds is not allowed with tolerance of 0.250000 seconds
```

@tbg could you make a determination about whether these are concerning or expected, and whether they should block the release from going out?

**Comment by nvanbenschoten** [comment]
`jepsen/register/split` crashed with the error:
```
10:37:18 jepsen.go:227: grabbing artifacts from controller. Tail of controller log:
10:37:18 cluster.go:315: > /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod run teamcity-1564706298-29-n6cpu4:6 -- tail -n 100 /mnt/data1/jepsen/cockroachdb/invoke.log
	at clojure.lang.RestFn.invoke(RestFn.java:425) [clojure-1.8.0.jar:na]
	at clojure.lang.AFn.applyToHelper(AFn.java:156) [clojure-1.8.0.jar:na]
	at clojure.lang.RestFn.applyTo(RestFn.java:132) [clojure-1.8.0.jar:na]
	at clojure.core$apply.invokeStatic(core.clj:650) [clojure-1.8.0.jar:na]
	at clojure.core$bound_fn_STAR_$fn__4671.doInvoke(core.clj:1911) [clojure-1.8.0.jar:na]
	at clojure.lang.RestFn.invoke(RestFn.java:397) [clojure-1.8.0.jar:na]
	at clojure.lang.AFn.run(AFn.java:22) [clojure-1.8.0.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_222]
...
ERROR [2019-08-02 10:37:15,724] main - jepsen.cli Oh jeez, I'm sorry, Jepsen broke. Here's why:
java.lang.InterruptedException: null
	at java.util.concurrent.CyclicBarrier.dowait(CyclicBarrier.java:211) ~[na:1.8.0_222]
	at java.util.concurrent.CyclicBarrier.await(CyclicBarrier.java:362) ~[na:1.8.0_222]
	at jepsen.generator.Synchronize.op(generator.clj:667) ~[jepsen-0.1.9-SNAPSHOT.jar:na]
	at jepsen.generator.Concat.op(generator.clj:609) ~[jepsen-0.1.9-SNAPSHOT.jar:na]
	at jepsen.generator$op_and_validate.invokeStatic(generator.clj:34) ~[jepsen-0.1.9-SNAPSHOT.jar:na]
	at jepsen.generator$op_and_validate.invoke(generator.clj:30) ~[jepsen-0.1.9-SNAPSHOT.jar:na]
	at jepsen.core.NemesisWorker.run_worker_BANG_(core.clj:442) ~[jepsen-0.1.9-SNAPSHOT.jar:na]
	at jepsen.core$do_worker_BANG_.invokeStatic(core.clj:175) ~[jepsen-0.1.9-SNAPSHOT.jar:na]
	at jepsen.core$do_worker_BANG_.invoke(core.clj:162) ~[jepsen-0.1.9-SNAPSHOT.jar:na]
	at jepsen.core$run_workers_BANG_$fn__4599$fn__4600.invoke(core.clj:228) ~[jepsen-0.1.9-SNAPSHOT.jar:na]
	at clojure.lang.AFn.applyToHelper(AFn.java:152) ~[clojure-1.8.0.jar:na]
	at clojure.lang.AFn.applyTo(AFn.java:144) ~[clojure-1.8.0.jar:na]
	at clojure.core$apply.invokeStatic(core.clj:646) ~[clojure-1.8.0.jar:na]
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1881) ~[clojure-1.8.0.jar:na]
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1881) ~[clojure-1.8.0.jar:na]
	at clojure.lang.RestFn.invoke(RestFn.java:425) ~[clojure-1.8.0.jar:na]
	at clojure.lang.AFn.applyToHelper(AFn.java:156) ~[clojure-1.8.0.jar:na]
	at clojure.lang.RestFn.applyTo(RestFn.java:132) ~[clojure-1.8.0.jar:na]
	at clojure.core$apply.invokeStatic(core.clj:650) ~[clojure-1.8.0.jar:na]
	at clojure.core$bound_fn_STAR_$fn__4671.doInvoke(core.clj:1911) ~[clojure-1.8.0.jar:na]
	at clojure.lang.RestFn.invoke(RestFn.java:397) ~[clojure-1.8.0.jar:na]
	at clojure.lang.AFn.run(AFn.java:22) ~[clojure-1.8.0.jar:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_222]
```
@ben could you make a determination about whether this is concerning and whether it should block the release from going out?

**Comment by ajkr** [comment]
> `clearrange/checks=true` failed due to a node hitting:
> 
> ```
> F190802 10:30:59.381932 105 storage/replica_raft.go:801  [n1,s1,r17332/4:/Table/53/1/4767{4005-6941}] while committing batch: IO error: No space left on deviceWhile appending to file: /mnt/data1/cockroach/029340.log: No space left on device
> ```
> 
> `clearrange/checks=false` timed out:
> 
> ```
> 11:14:31 test.go:199: test worker status: dropping table
> 11:14:32 test.go:199: test worker status: computing number of ranges
> 1: 14929
> 8: 29732
> 3: 24382
> 10: 16741
> 6: 14114
> 2: 1042
> 4: 20558
> 7: 24278
> 9: 4540
> 5: 23522
> 11:14:32 test.go:199: test worker status: dropping bank table
> 11:47:43 test.go:290: test failure: 	test_runner.go:706: test timed out (6h30m0s)
> ```
> 
> @ajkr you've been looking into these tests in #38772 and #38720. Could you make a determination about whether these are concerning or expected, and whether they should block the release from going out?

Those are expected. We're not yet able to import data as fast as that test wants.

**Comment by tbg** [comment]
@nvanbenschoten the jepsen failure is https://github.com/cockroachdb/cockroach/issues/30527

I'm relatively sure that https://github.com/cockroachdb/cockroach/issues/38723 will be something silly related to the roachtest rewrite. I believe that we'll sometimes run more than one of these tests on a cluster (sequentially) and that the contained ntp adjustments can leak between tests.

**Comment by bdarnell** [comment]
The jepsen failure is benign. It failed with an InterruptedException (which [doesn't fail the build](https://github.com/cockroachdb/cockroach/blob/229796754b7be30b79e90c2a4fc1d25577346d7b/pkg/cmd/roachtest/jepsen.go#L244), then it failed downloading logs. We should probably check the `ignoreError` flag if we fail while building failure-logs.tbz.

**Comment by nvanbenschoten** [comment]
I changed the release name while tagging the release. This forced me to re-publish provisional binaries. I'm re-running the release qualification build on these binaries [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=1423299&buildTypeId=Cockroach_ReleaseQualification).

**Comment by nvanbenschoten** [comment]
The release is out the door.

**Comment by kenliu** [comment]
thanks @nvanbenschoten
