### ISSUE TITLE
sql: total transaction time in conn_executor

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#39056]
We need to track the total transaction time the way we currently track the total statement time.

**Comment by yuzefovich** [comment]
@awoods187 could you please provide more context on what is the desired outcome of this issue?

Do we want to add another `Transaction` page to the Web UI? Do we want to display total transaction time next to each statement that was part of that transaction? Do we want to collect transaction statistics (like for transactions that consisted of the similar statement to show the mean and variance, etc). I'm a little unclear of what is the deliverable here.

@jordanlewis I realized that I might be going down the wrong path, so let's discuss this issue in more detail here, before I do anything.

**Comment by jordanlewis** [comment]
Sorry for the lack of specificity here.

The ask is to have enough information about transaction timing that a virtual table (or eventually the UI) could start to piece together information about transaction timings. Perhaps eventually there would be a way to correlate queries and transactions together, or something, I'm not sure. But for now, we just want to write down how long every transaction takes, start to finish, similar to how it is done in the `node_statement_statistics` table.

This is done in `conn_executor.phaseTimes` presently. I was imagining a new field that keeps track of transaction timings in a similar way.

Is that helpful?

**Comment by yuzefovich** [comment]
Thanks, I chatted with Jordan on Slack, and the ask for now is very simple: measure total transaction time and write it down somewhere. I'll do just that without overthinking it.

**Comment by awoods187** [comment]
But we do want to have it in the Webui--it's fine if its behind a debug page in a timeseries or something similar. cc @piyush-singh in case he has opinions. Long term, it will be on a transactions page that doesn't yet exist.

**Comment by piyush-singh** [comment]
To Andy's point, we do eventually want to expose this in several ways in the web UI. 

> Do we want to add another `Transactions` page to the Web UI? 
Yes! This is very much on our roadmap, but is pending staffing. So this may be a ways out, and I wouldn't worry about it yet.

> Do we want to display total transaction time next to each statement that was part of that transaction? 
I think this would also be useful - although we currently aggregate fingerprints regardless of the parent transaction (so theoretically across multiple transactions), so I'm not quite sure how we would show this in practice. 

> Do we want to collect transaction statistics (like for transactions that consisted of the similar statement to show the mean and variance, etc).
We did have the idea to fingerprint transactions and show aggregate statistics this way, but I wouldn't worry about that for now.

A simple addition would be to expose aggregate transaction latency as a time series similar to the ways we expose statement latencies (not sure how complicated it would be to do the P50, P90, and P99 values for this). This would provide at least some basic visibility, but I can understand if this is too much for 19.2.

**Comment by yuzefovich** [comment]
Thanks for context! I think I can implement the backend for the suggestion from the last paragraph but not sure about the frontend.
