### ISSUE TITLE
sql: show constraints doesn't show all constraints

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#39075]
For Movr, first we partition the users table:

```SQL
ALTER TABLE users PARTITION BY LIST (city) ( PARTITION new_york VALUES IN ('new york'), PARTITION chicago VALUES IN ('chicago'), PARTITION seattle VALUES IN ('seattle') );
```

Then we add constraints:

```SQL
ALTER PARTITION new_york OF TABLE movr.users CONFIGURE ZONE USING constraints='[+region=us-east1]'; ALTER PARTITION chicago OF TABLE movr.users CONFIGURE ZONE USING constraints='[+region=us-central1]'; ALTER PARTITION seattle OF TABLE movr.users CONFIGURE ZONE USING constraints='[+region=us-west1]';`) 
```

If you run `SHOW CONSTRAINTS FROM users` after adding constraints you will not see them:
```
root@localhost:26257/movr> show constraints from users;
  table_name | constraint_name | constraint_type |            details             | validated
+------------+-----------------+-----------------+--------------------------------+-----------+
  users      | primary         | PRIMARY KEY     | PRIMARY KEY (city ASC, id ASC) |   true
(1 row)

Time: 239.074341ms
```

**Comment by rohany** [comment]
I'm not sure that this is the appropriate place to display location constraints for partitions -- i think the show constraints command is meant instead for constraints on a table such as what columns need to be unique etc. The constraints term seems to just be overloaded here.

**Comment by jordanlewis** [comment]
+1, I don't think `SHOW CONSTRAINTS` should show anything to do with zone configurations.

**Comment by awoods187** [comment]
I think it will be confusing for users to see us use constraints in multiple settings. What more could we do here?

**Comment by jordanlewis** [comment]
I think SQL database users are generally used to the concept of a "relational constraint", which is what show constraints offers. I think including non-relational constraints (data placement) alongside them would actually create more confusion, as they're orthogonal topics.

Once we include the other information in show create table and so on, I feel like we'll be good to go. By the way, I think that the frequency of use of `SHOW CONSTRAINTS` is likely significantly lower than `SHOW CREATE TABLE`, so I think that our focus on `SHOW CONSTRAINTS` should be proportionally low compared to `SHOW CREATE TABLE`, which is really the workhorse here.

**Comment by rohany** [comment]
If this isn't going to be included, should we close the issue?

**Comment by jordanlewis** [comment]
Yes

**Comment by rmloveland** [comment]
This is already decided (and I agree!) -- just wanted to add for posterity that we do already have a [`SHOW ZONE CONFIGURATIONS`](https://www.cockroachlabs.com/docs/stable/show-zone-configurations.html) statement users can run to access the zone config stuff separately from `SHOW CONSTRAINTS`.
