### ISSUE TITLE
CREATE DATABASE without admin role throws superuser error

### ISSUE THREAD

**Issue by mattcrdb** [cockroachdb/cockroach#39099]
**Describe the problem**

When trying to create a database using create database syntax as any user other than the root or a user with the admin role, the following error is thrown:

`pq: only superusers are allowed to CREATE DATABASE`

Superuser is not a concept in CRDB

**To Reproduce**

1. Create a local cluster
2. Create a new user
3. Log in to cluster as that user
4. Try to create a database.

**Expected behavior**

The error that should be thrown is:

`pq: only users with the admin role are allowed to CREATE DATABASE`

This may cause confusion since as a core user, only the root user has the admin role, and granting roles is an enterprise feature. Might be possible to throw a different error depending on whether an enterprise license in enabled. 

**Environment:**
 - CockroachDB version 19.1.3

**Additional context**
Impact: causes confusion about the concept of superuser.

**Comment by Gurio** [comment]
@mattcrdb: Is this ticket just about changing one error description? (and adapting tests obviously)

**Comment by mattcrdb** [comment]
Yes

**Comment by Gurio** [comment]
ok, I'll take it
