### ISSUE TITLE
util/log: enable logging using the system TZ instead of UTC

### ISSUE THREAD

**Issue by mattcrdb** [cockroachdb/cockroach#39097]
Cockroach logs currently log in UTC time format.

An option to change this setting to log in system time would be very beneficial to users that have other logs using the same format.

The solution would allow a more simple debugging experience for folks with other application logs in system time.

Jira issue: CRDB-5594
Epic: CRDB-24406

**Comment by tim-o** [comment]
We've received two separate issues with similar requests: one asking for the ability to log in system time, another asking for the ability to display the Web UI in another timezone. One simple solution might be to have a cluster setting for the timezone that'd change both the logs and the UI TZ's.

This will have implications for our debugging, so we'd need to have a warning at the top of each log indicating what TZ the logs and UI are using.

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[3511](https://cockroachdb.zendesk.com/agent/tickets/3511) has been linked to this issue.

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[3523](https://cockroachdb.zendesk.com/agent/tickets/3523) has been linked to this issue.
