### ISSUE TITLE
exec: unordered synchronizer is blocked forever

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#39092]
If we add `fakedist-vec` config to `logic.go` as `{name: "fakedist-vec", numNodes: 3, useFakeSpanResolver: true, overrideDistSQLMode: "on", overrideOptimizerMode: "on", overrideAutoStats: "false", overrideExpVectorize: "on"},` and add this new config to `overflow` logic test, it hangs forever (every time when the data happened to be distributed).

Everything terminates gracefully except for the unordered synchronizer which remains blocked.
Here is my understanding of why:
- an aggregator encounters an overflow error and panics with it
- the panic is caught by materializer which moves into Draining state
- all metadata sources are drained correctly
- but the unordered synchronizer was never notified in any way that it should exit, so it hangs forever here:
https://github.com/cockroachdb/cockroach/blob/d170ae7ef5205239d650bfca892e2cb42f9c45bc/pkg/sql/exec/unorderedsynchronizer.go#L142-L153

We need some way to handle such a cancellation.

**Comment by jordanlewis** [comment]
Yeah, seems to me like we need to be cancelling the context that all of the blocking ops are waiting on. Would that help matters? That would be the main flow context, I think. @asubiotto thoughts on that?

**Comment by asubiotto** [comment]
Yes, I think that would help, although it seems cleaner to use the unordered synchronizer's cancel function. I think that exposing something like that as part of a principled approach to https://github.com/cockroachdb/cockroach/pull/39077#issuecomment-514833468 seems like the way to go.

**Comment by jordanlewis** [comment]
Well, just cancelling the unordered synchronizer's cancel function might not be enough - what if there were more things to cancel than just that? It seems like we want a way to cancel everybody in the flow all at once, which to me seems like a good use case for a single cancellable context per flow that gets passed to every operator's `Next`. Then, when we finish a flow for whatever reason, if we make sure to cancel that context, every blocking operation should be able to wrap up if we make sure that all of those blocking operations are listening on the context as well.

**Comment by asubiotto** [comment]
I think I'm onboard with that as long as we allow `DrainMeta` to be called before shutting down a flow. That probably means that we're going have to support concurrent `DrainMeta` and `Next` calls.

**Comment by yuzefovich** [comment]
It appears to me that we need to support concurrent `DrainMeta` and `Next` calls anyway. I encountered a race on `TestDistSQLRetryableError` on `vec-setting` branch:
```
Read at 0x00c01a5c0ff9 by goroutine 780:
  github.com/cockroachdb/cockroach/pkg/sql/exec/colrpc.(*Inbox).DrainMeta()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/exec/colrpc/inbox.go:287 +0x122
  github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.newMaterializer.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/materializer.go:85 +0xf0
  github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).moveToTrailingMeta()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:755 +0x191
  github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).MoveToDraining()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:657 +0x17c
  github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*materializer).Next()
...
Previous write at 0x00c01a5c0ff9 by goroutine 1677:
  github.com/cockroachdb/cockroach/pkg/sql/exec/colrpc.(*Inbox).Next()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/exec/colrpc/inbox.go:165 +0x81a
  github.com/cockroachdb/cockroach/pkg/sql/exec.(*UnorderedSynchronizer).init.func1.2()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/exec/unorderedsynchronizer.go:117 +0x8f
  github.com/cockroachdb/cockroach/pkg/sql/exec.CatchVectorizedRuntimeError()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/exec/error.go:80 +0x62
  github.com/cockroachdb/cockroach/pkg/sql/exec.(*UnorderedSynchronizer).init.func1()
      /go/src/github.com/cockroachdb/cockroach/pkg/sql/exec/unorderedsynchronizer.go:117 +0x170
```

**Comment by asubiotto** [comment]
I think this is an unexpected race fixed by https://github.com/cockroachdb/cockroach/pull/39093
