### ISSUE TITLE
sql: incorrect query plan selected for stockLevel transaction

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#39103]
When running a series of `tpcc/headroom/n4cpu16` tests with the SHA 26edea51118a0e16b61748c08068bfa6f76543ca I can see cluster performance split into two regimes - one fast, one slow. The slow clusters appear to be overloaded, with CPU utilization on each node saturated at 100%. Meanwhile, the fast clusters are doing fine, with CPU utilization hovering around 55%.

I believe I have tracked this down to the following difference in query planning for TPC-C's `stockLevel` transaction.

### Fast Cluster `stockLevel` Query Plan

![Screenshot_2019-07-25 Details Statements Cockroach Console](https://user-images.githubusercontent.com/5438456/61900860-7b8f1400-aeec-11e9-93ed-e4179432d435.png)

### Slow Cluster `stockLevel` Query Plan

![Screenshot_2019-07-25 Details Statements Cockroach Console(1)](https://user-images.githubusercontent.com/5438456/61900878-8053c800-aeec-11e9-8696-6e99db099cab.png)

This appears to be responsible for https://github.com/cockroachdb/cockroach/issues/37163 and maybe other TPC-C tests that are failing with similar symptoms. It is also blocking the next alpha release: https://github.com/cockroachdb/cockroach/issues/39036.

**Comment by nvanbenschoten** [comment]
I ran the following on both clusters:
```
EXPLAIN (OPT, ENV)
	SELECT
		count(*)
	FROM
		(
			SELECT
				DISTINCT s_i_id
			FROM
				order_line JOIN stock ON s_i_id = ol_i_id AND s_w_id = ol_w_id
			WHERE
				ol_w_id = 1
				AND ol_d_id = 1
				AND ol_o_id BETWEEN (100 - 20) AND (100 - 1)
				AND s_quantity < 5
		);
```

Here's the output on the fast cluster: [link](https://cockroachdb.github.io/text/decode.html#eJzsWl1vm0gXvi6_4sg3hfc19gDGgLu9oIRs6Tokstl-qKoQwSRhQxgvH3Wt1UrV_oZc7q_LL1nxNWBqV0q9pmupvrDOnOfMmZmHmWGeEa-9KPZxOAENu7cRdtybkxegaVP4yCkDfoBYJ1jeOAMecQqSeAXoT_LYHo_YNLwN8SpkAz9MP7HXYdqHy9QPEsgih0ga8iPgpAnPTwS5D9eYG3D8QGQoSpvpqqWDpb6Y6oCjhRfZgR96QFNPcGBj21-AYVoymOcWmL9Op_3cv9jhX-3wh-ndpRdtQ_wdNeJ0uQzWzYR1417gf_Sitb0AyzjT55Z6dkEjphHxe-qEiZ-s2zWdO5yGCZzomnGmTulxn2_WWvhxYvvhFQbtpTqj-REBtXNzbs1Uw7Sgt4z8Oyda9-BiZpyps3fwi_4O6Grs6lzrQ0VQVchZPNHLUsmFOteYzdRXt_bmwO3Iu7LjBLu3cHo-042fTdJYIypPmtHIwEw_1We6qelzyKvRcRkRFwF96olhnuhvGw-6yG9f3dr-4lM7NRmBXxa29ph0Nc_6RVdJHxeVgdud7eU1ezSugqvYstOn6pkxfdfgni6zbOYlLRUUk57nRpuxehblxWrK5IVinhRh1aRgKOYZRalTS5-VqyVZuu5gmV4GvjtorBzDfKVrFswt1TLmlqHN4el7CgDgj_w_-_VcHKR3YdybwHvizIFyFD3i_dBv1Io8J_EWtpP0JtDLVjaLJJYXgZMnApogZcDLnDLm_4_QBKFeo2Y2Cj90E9vNBtabAIcQauA3fpxg28WBnayXXpa9WTt07nKfbTtpgm17A0uDgGRtpozwivgFhBDHiTzK4T_7j6Gj8dx-sEJYwV3QwSuKchx0LLqZHcdBRrH7HZ4O8Tjo8LuYG4oyFuXj4KN-8R1-A_n3GZEVRRmNFfEAxFRHgMOvnOOYKMUp6PBLR5Z5YXwclJDT4MFZERCSJRl9R2KoD0-ftfRhoUVo6km8XbfF2wVgvF2QxQWdiPtCb1UIvxMRdiKjnYi4ExnvRKSdiLwTUXYhHNqCrJNFi5VCS7hh0vJH3h1OvC3AwkkceK3O8uQieoRsjRsyL_6KyiuwXOT5iXe3qfHiL9VnFkRvSs5CZ2YAEZtfb5HIypUTeTc4jb12s6t2sySSXu1UjnEpCWtpXEs_MiNrk69NoTZHtSnW5rg2pdqUa1MhJocyc53kHSAPPCvUTzkPdhLn68qzWJN7ic74W9WVOEGjgYR4hJT_nLrKWst_j93m4289MT6OjY5PjHvQsce56JGUdHgw2oOPco_oYr0IooSE41g05XbZASscGolKl-pzb1aEDnaTkYAk6QCC62CkjLpYQDwnCcIxbStiF6xIishzHSqLvVkZd_E6lkY81-F9596kSB2QIsiIQ8dEitzF-hkrAoeO6QWkHH6qyMoYjYTjONGWEqyTt7IyPpK38jrpQAIeBRNEj__gI-ejvpL4QUixfziJ08V7RlFEAX0_SoobYP3txVQ1TKDPL6w-6OZrBub6VNcsyKvR_2PgdHZ-BnTpPTHmlmFqVnWhmION7yNenRtmeZN8bpJLwOf1VyyqeUJuJp9X33Uw8OalPtOBpsm3Ns-BK4OrD24yT-3KP7t5oVtvdN0EmkMIWOBRiRdFjmFIe-SO-icQGeYZxbIsS8WuEzgRex3hdMleril4uP_74f7zw_1nqB4Yi8PM_VdG2cP9fYn6YehF7G_YD4EOML5Nl8WYGRILRYUqXew6YYOmdlgrvYvDOIkcP0wmMBSG_JDlhqMJvB9yQ26oKMBCbsnoQztRleHKDxIvijfhdp8I0VvD7klYkzuqgTjX15F37SQ-DmOqXS2fPmyEVzH1TwAAAP__b9zfrA==).
Here's the output on the slow cluster: [link](https://cockroachdb.github.io/text/decode.html#eJzsWN1um0gUvi5PceSbwq5xBvyL26xECdnSdXCE2f6oqhDBJKHBM14Y6lqrlao-Qy736fIkK_4GTIylSpusIm0vqjPnO-fMzDdnJv5460dxQPAUNOLdRMT1rk9egabN4Iuk9OQeEt1wfe32ZCQpaCwrwH-djJzRQEzwDSYbLIYBTr6KVzjpwkUShBTSyCM0PpIHII2nsjztT7pwRaSeJPeGAsdplq7aOtjqq5kOJFr6kRMG2Aeee0ZChzjBEgzTnoA5t8H8fTbrZv5li3_T4sfJ6sKP9iFBS0acrNfhtl6wmtwPgy9-tHWWYBtn-sJWz855JNQi_khcTAO6bWa6K5JgCie6ZpypM37UletZyyCmToAvCWivVYuXBwzU5ubCtlTDtKGzjoKVG207cG4ZZ6r1AX7TPwBf7l1daF0oCSoHGYsnejEquFAXmrBb-vLG2d24E_mXTkyJdwOnc0s3fjXZZLWorGhKowCWfqpbuqnpC8jS-LiIiPOALvfMME_097WDzus7lzdOsPzaLM12EBSDvStmS82q3lsqW-OyNEhzsZ0ss8OTMriMLRZ9qp4Zsw817vmiym5dNlNOMVt5ZjQZq7ooG5Ytkw3yPsnDyqYQOOEFx6kzW7eK20LXntdbJxdh4PVqN8cw3-iaDQtbtY2FbWgLeP6RAwD4M_s__dfxSJiscNyZwkfmzIBiFx3m_dStZUW-S_2l49LOFDrpzRbRWJSHIE2mA2U6GPcG0kBCg58RmiLUqWWmuwiwRx0v3VhnChJCqIZfBzEljkdCh27Xflq9no3dVeZzHDehxHF2sCQMWdV6yYhsmL-PEJKkoYwy-K_uj9BRO7f_WWGskMegQ1YU5WnQsXyc7ngaZOSv38PTMXwadASP0RuKMhpOngYf1R--h39A_n1GJoqiDEbK8AGIKX8CPPzNeRqNkv8KevirM5nI_dHToIT9GnxwVvoITcZDedT_z4jhPj1_0dCHuRbhuWfxft0W7xeA8X5BFud0Iume3ioRuRXptyKDVmTYioxakXErMmlFlDZEQnuQLV02WMm1hIdpwx_5K0L9PcDSpS68Va2s-BD9gGyNazIvPqDyciwTeQH1V7saL76vPtMgfldy5jozBZjYPDwjk5UbN_KvSRL7zWk3zWlZJL9pVY5xIQkraVxJP9aRlSlXZr8yB5U5rMxRZY4rc1KZCjMllJpbmi2AHXg6qE45C3ape1h55ndyn-jM7q_-_nymGibw83O7C7r5VoCFPktjs2vP_yTAqTU_A77wnqTppmaX7ZCBNXX7Zm6YxTswN9kRHlffIFTzhPXVcanKBXj3Wrd04Hn2peQYpCK4_FySeipX9tHklW6_03UTeAkhEEFGBZ4PJUFg87EX5iUMBeEFJ4qiyMWeG7qReBWRZC1ebDm4u_377vbb3e03KB9ckeDU_T198u5ubws0wNiPxM8kwMCHhNwk6xoHAkuAPKusuY7IZ9-jTfj7blTsh-1BzVjPxTnbh-Mby_cIjmnkBphO4UiSjyRpCh-PJBDhSPp0uFJZ4jIIqR_Fh4JhN2P3DFoSb3epCgjePwXs2dAUpGbswdU2TqfZqgeDWQf-cgwT1OjKl8egKMLe_HJBtS7nam736iryr9xi3_c2mWAqRmQTc_8EAAD__zSPHyU=).

**Comment by RaduBerinde** [comment]
@nvanbenschoten in the second link above, notice that there are no statistics for `stock`. That would explain the bad plan: `ALTER TABLE tpcc.public.stock INJECT STATISTICS '[]';`

**Comment by nvanbenschoten** [comment]
Here's a [debug.zip](https://github.com/cockroachdb/cockroach/files/3432967/debug.zip) from a struggling cluster.

**Comment by nvanbenschoten** [comment]
It looks like this cluster was populated using a RESTORE operation instead of an IMPORT operation. Unlike IMPORT, RESTORE doesn't attempt to inject table statistics, so there's a race between generating table stats so that `stockLevel` picks an efficient plan and the load ramping up. The race must be close enough that it doesn't always result in the same outcome.

**Comment by nvanbenschoten** [comment]
Fixed by https://github.com/cockroachdb/cockroach/pull/39106.
