### ISSUE TITLE
sql: allow for historical reads in select statements for INSERT/UPSERT into and CTAS/CVAS

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#39123]
- [ ] Allow INSERT and UPSERT into to use historical reads via AOST in the select statement
- [ ] Allow CREATE TABLE AS and CREATE VIEW AS to use historical reads in the select statement

This would be an explicit choice made by users to reduce contention and improve performance.

**Comment by bladefist** [comment]
This would be amazing. Thank you for considering.

**Comment by knz** [comment]
dup #35712
