### ISSUE TITLE
demo: webui shows 0 B for all tables

### ISSUE THREAD

**Issue by kenliu** [cockroachdb/cockroach#39155]
When running `cockroach demo movr` on 19.2 latest, all tables show up as 0 B, as well as database size. This is confusing for a new user especially when they are expecting a pre-loaded dataset.

![image](https://user-images.githubusercontent.com/47234/62083949-11e17380-b226-11e9-8d69-a5bb0b42befa.png)

![image](https://user-images.githubusercontent.com/47234/62084339-1c503d00-b227-11e9-9ab9-8458d16024b6.png)

Jira issue: CRDB-5591

**Comment by tharun208** [comment]
@asubiotto, I still see it is coming as `0B` in the latest version. I will work on this.
