### ISSUE TITLE
Feature: report what transaction statements are causing "transaction too large"

### ISSUE THREAD

**Issue by mattcrdb** [cockroachdb/cockroach#39207]
Transactions that issue many statements often return with a transaction too large error.

From what I understand this error comes from the kv layer.

This feature can allow debugging of those transactions, and indicate which statements within the transactions are causing the transaction to exceed the allowed size.

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[3544](https://cockroachdb.zendesk.com/agent/tickets/3544) has been linked to this issue.
