### ISSUE TITLE
New flag for limiting the log to information that matters

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#3921]
When running CockroachDB in a Docker container, we're keeping the docs simple and having users start the server and sql client in the same shell. The problem is that the logs sort of get in the way. 

I chatted with @bdarnell about this and asked if the docs should suggest they redirect the logs somewhere else. He said it'd be good to keep the logs visible if they included only information that matters. 

Ben's idea was to add a flag so you could pass something like `--log-level=warning` instead of redirecting all output.

**Comment by petermattis** [comment]
See #4336 and #4337.
