### ISSUE TITLE
sql: force_retry shouldn't require admin

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#39243]
We'd like to document the `force_retry()` function for people to test their transaction retry loops (as in cockroachdb/docs#5085). This function currently requires admin privileges, but there's no reason for this (it looks like it was copy/pasted from nearby `force_panic` and `force_log_fatal`, which do need restricted access). We should open this function up to all users.

**Comment by Gurio** [comment]
@bdarnell: so one should remove `checkPrivilegedUser` from `crdb_internal.force_retry` built-in, right?
I would like to take this issue

**Comment by bdarnell** [comment]
Yes, that's all that's needed, but @inconnu8 beat you to it with #39246.

**Comment by Gurio** [comment]
@bdarnell oh, right I didn't notice :)
also, I can see the reasons why not, but did you consider letting external contributors assign issues to themselves?

**Comment by bdarnell** [comment]
> also, I can see the reasons why not, but did you consider letting external contributors assign issues to themselves?

I think that's a github thing we don't have control over. You have to be a member of the organization to have issues assigned to you, so as a new external contributor you just have to comment on the issue.

**Comment by Inconnu08** [comment]
@Gurio I apologize for that. I should have commented first.
@bdarnell next time I will comment before making a move.

**Comment by Gurio** [comment]
@Inconnu08 no problem :)
