### ISSUE TITLE
TestLogic: improper/incomplete test for timezone errors

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#3925]
The `datetime` test in TestLogic expects an incorrect/invalid timezone to fail with "cannot find ..." from Go's time library. However due to the way Go's time library is written, combined with how the distrib's standard package installs Go on (at least) Ubuntu 15, this error cannot be produced upon selecting an invalid timezone; instead the error shows up as "unable to find zoneinfo.zip", and thus:

```
testdata/datetime:309: SET TIME ZONE 'foobar'
--- FAIL: TestLogic (1.89s)
        logic_test.go:459: testdata/datetime:309: expected "cannot find foobar.*", but found
                pq: open /usr/lib/go/lib/time/zoneinfo.zip: no such file or directory
```

The problem is that `zoneinfo.zip` is not necessary on Unix (and thus is not installed by Go's package on Ubuntu 15), yet time's lookup code will fall back to it if it cannot find the selected timezone in the standard locations. 

The proper fix / workaround is to accept an unavailable zoneinfo.zip as a correct error message for an invalid timezone.

**Comment by vivekmenezes** [comment]
Thanks for finding this.

https://github.com/cockroachdb/cockroach/blob/master/sql/set.go#L96

calls LoadLocation and we should probably standardize the error returned here. It's fine to prefix the error with something like "cannot find <name>: "
