### ISSUE TITLE
test: replace `sent` with `LoadInt64(&sent)` in `TestBackpressure`

### ISSUE THREAD

**Issue by yuzeming** [cockroachdb/cockroach#39279]
**Describe the problem**
https://github.com/cockroachdb/cockroach/blob/f00763648b174936fc0a95587cf5a8dce24da20d/pkg/internal/client/requestbatcher/batcher_test.go#L158-L181

L180 `assert.Equal(t, int64(0), sent)` checks that there is no request is sent at L165 and two `go send()` should blocking L166.
However, when L166 doesn't block for some reason, an non-atomic read of `sent` can't guarantee to observe the write of L167 without any synchronization , so we may miss a bug in test

We should replace `sent` in L180 and L185 with atomic.LoadInt64(&sent), can I submit a PR to fix it?

**Comment by yuzefovich** [comment]
cc @ajwerner

**Comment by nvanbenschoten** [comment]
@yuzeming thanks for the issue! It looks like we're expecting L166 to block, based on the comment that says:
> Shouldn't need to use atomics to read sent. A race would indicate a bug. 

So this isn't really a data race unless something is already broken with the test. Still, I don't see an issue with you replacing that comment with something like
```go
// We don't expect either of the calls to send to have finished yet.
assert.Equal(t, int64(0), atomic.LoadInt64(&sent)) 
```
Want to send a PR?

**Comment by yuzeming** [comment]
@nvanbenschoten Thinks for your response 
Sorry for this confusion. My point is that, if there is bug make L166 doesn't block, we should catch it at L180, but there is not guarantee we can read `sent==1` without any synchronization.

I'm glad to help.

**Comment by nvanbenschoten** [comment]
I don't think there's any confusion :) You're right that if L166 doesn't block, the read on `sent` won't be properly synchronized. However, even with proper data synchronization by using an atomic read, we're still not guaranteed to actually fail the assertion. The test would just become flaky and fail occasionally. So at its best, performing an atomic read would make the test... more reliably flaky if anything ever broke, I guess. That's what the comment was trying to say. Still, we'd happily accept a PR to perform the read using an atomic load.
