### ISSUE TITLE
test: fix data race of `exited in `TestTrackerDoubleRelease`

### ISSUE THREAD

**Issue by yuzeming** [cockroachdb/cockroach#39281]
**Describe the problem**

https://github.com/cockroachdb/cockroach/blob/802ae38f38bf297e5cb849315d5510c95b2d1e6f/pkg/storage/closedts/minprop/tracker_test.go#L86-L100

L88 and L98 share a bool variable `exited` in different thread.

However there is no guarantee that the write to `exited` will ever be observed by `TestTrackerDoubleRelease` , since there are no synchronization events between the two threads

We should use `atomic.Store` and `atomic.Load` to replace them. 
May I submit a PR to fix it?

**Comment by nvanbenschoten** [comment]
Hi @yuzeming! Thanks for the issue. Why do you say that the two accesses to `exited` are on different threads? If I'm reading this correctly, we expect the second call to `release` (line 96) to hit a `log.Fatal`, which should make it all the way [here](https://github.com/cockroachdb/cockroach/blob/32211071977a8cd801d7f6b9a2321887a2d1ab7f/pkg/util/log/clog.go#L898) and call into the function we provided to `SetExitFunc` on the same thread.

**Comment by yuzeming** [comment]
this log may help you
> /pkg/storage/closedts/minprop/tracker_test.go:87:6 new bool (exited)
/pkg/storage/closedts/minprop/tracker_test.go:88:52 Func: TestTrackerDoubleRelease$1
    # 0 /pkg/storage/closedts/minprop/tracker_test.go:94:29 (*Tracker).Track(t4, t3)
    # 1 /pkg/storage/closedts/minprop/tracker.go:277:12 github.com/cockroachdb/cockroach/pkg/util/log.Infof(ctx, "track: proposal o...":string, t29...)
    # 2 /pkg/util/log/log.go:95:10 logDepth(ctx, 1:int, 1:Severity, format, args)
    # 3 /pkg/util/log/log.go:69:15 addStructured(ctx, sev, t0, format, args)
    # 4 /pkg/util/log/structured.go:66:24 (*loggingT).outputLogEntry(logging, s, t2, t3, t5)
    # 5 /pkg/util/log/clog.go:907:3 go t54()
    # 6 /pkg/util/log/clog.go:912:12 t5(255:int)
    # 7 /pkg/storage/closedts/minprop/tracker_test.go:88:52 *exited = true:bool
------------
/pkg/storage/closedts/minprop/tracker_test.go:98:6 Func: TestTrackerDoubleRelease
    # 0 /pkg/storage/closedts/minprop/tracker_test.go:98:6 *t0
============

**Comment by yuzeming** [comment]
Is here?
https://github.com/cockroachdb/cockroach/blob/32211071977a8cd801d7f6b9a2321887a2d1ab7f/pkg/util/log/clog.go#L907-L914

I have a mock stack from static analysis

    # 0 /pkg/storage/closedts/minprop/tracker_test.go:94:29 (*Tracker).Track(t4, t3)
    # 1 /pkg/storage/closedts/minprop/tracker.go:277:12 github.com/cockroachdb/cockroach/pkg/util/log.Infof(ctx, "track: proposal o...":string, t29...)
    # 2 /pkg/util/log/log.go:95:10 logDepth(ctx, 1:int, 1:Severity, format, args)
    # 3 /pkg/util/log/log.go:69:15 addStructured(ctx, sev, t0, format, args)
    # 4 /pkg/util/log/structured.go:66:24 (*loggingT).outputLogEntry(logging, s, t2, t3, t5)
    # 5 /pkg/util/log/clog.go:907:3 go t54()
    # 6 /pkg/util/log/clog.go:912:12 t5(255:int)
    # 7 /pkg/storage/closedts/minprop/tracker_test.go:88:52 *exited = true:bool

**Comment by nvanbenschoten** [comment]
The synchronization comes from the lines right above that:
https://github.com/cockroachdb/cockroach/blob/32211071977a8cd801d7f6b9a2321887a2d1ab7f/pkg/util/log/clog.go#L902-L906

I'm impressed that the static analysis tool you're using (writing?) was able to detect this though! Is this something you'd be willing to share?

**Comment by yuzeming** [comment]
Yes, I see. L905 (recv chan) and L913 (close chan) provide a synchronization. This function create a thread and wait for it.
I'm writing a static analysis to find data race among anonymous functions. I'm glad to share when it's mature enough.
This case is a false positive I need to work.
Thanks to point it out.
