### ISSUE TITLE
Publish gogo-free proto files

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#393]
I started hacking on a python client and hit a wall with our protobufs. The gogoproto extensions are at best a hassle to build in any non-go language, and in Python there are problems that may be impossible to get around without a fork of both our protos and gogo.proto (and if it can't work with our protos as-is we might as well get rid of the gogoproto extensions instead of figuring out how to build them).

Once we commit to stability in our proto field numbering, we should make a new repo cockroach-proto which contains all our protos with the gogoproto bits stripped out. (proto3 will reduce our need for gogoproto and might allow us to remove it completely, although the separate repo is still a good idea even if the files are identical).

FYI, the python-specific issue here is that protoc's python support assumes that the proto directory structure and python package structure are the same: importing github.com/gogo/protobuf/gogoproto/gogo.proto in a proto file translates to "import github.com.gogo.protobuf.gogoproto.gogo_pb2" in python. Using "github" as a top-level python package is basically a non-starter. Even if this were fixed and the top-level package remapped to "gogoproto", someone would need to own the "gogoproto" python package; there's no clean way for cockroach-python to distribute its own vendored version of gogoproto.

**Comment by cockroach-team** [comment]
+1

I'm new here, and only took a quick stab at it, but I was having similar 
issues generating java protobuf classes.  protoc appears to have more 
flexible options for java than python, but it was still very messy.
On that note, is anyone working on a java client?  I would be happy to 
contribute in this area.

**Comment by bdarnell** [comment]
The C++ protobuf library has an API for converting a parsed descriptor back into a source file (http://stackoverflow.com/questions/19418655/restoring-proto-file-from-descriptor-string-possible). We can use this to robustly remove the gogo extensions, and potentially do other transformations as needed (e.g. if we need other language-specific options). This API is being updated in proto3 to be higher-fidelity (preserving comments, perhaps more).

Weekend hack (AKA learning cgo and forgetting the semicolon on every single line): https://github.com/bdarnell/proto-rewrite

**Comment by cockroach-team** [comment]
I'm happy to move away from gogoproto as long as it's a move to more
simplicity. Proto3 is an obvious choice. But the way that protobufs are
implemented in Go for v2.6 causes my gorge to rise. From what I've been
able to read about proto3 online, it solves most of the issues. I just need
to see what the generated code looks like.

**Comment by petermattis** [comment]
See https://github.com/grpc/grpc-go/blob/master/examples/route_guide/proto/route_guide.pb.go

**Comment by bdarnell** [comment]
Proto3 eliminates the need for the `nullable` option, but AFAIK it doesn't have an equivalent to the `embed` option, which we rely on to define common interfaces like proto.Request and proto.Response. I'm not sure how much of a pain it would be to move away from that pattern. It also doesn't let us customize naming, which we do in some places but is less critical.

I don't think we should ditch gogoproto just to constrain ourselves to the lowest common denominator. As we build out our client libraries we'll probably want to use other language-specific extensions along the way. We just need to do that in a way that doesn't impose build headaches on the other languages. This may mean a master copy of the protos with every kind of extension built in, and then scripts to strip out the irrelevant ones when building for different languages.

**Comment by jmank88** [comment]
That anonymous post was me, from the google group.  It also quoted away part of my post here on github.  I had also added: "On that note, is anyone working on a java client?  I would be happy to  contribute in this area."  Although this probably isn't the right place for that conversation.

**Comment by Linicks** [comment]
I'm not a protobuff expert by any means, but as I understand it, one of proto3's main design goals was to improve language interoperability and make it easier to use.  I think that this is particularly important for a database because there is no telling what language a user will need to use with it.  Making it as easy as possible to inter-operate with CockroachDB, will only bring more users which will bring more resources making it a better project.  I often use MongoDB as the poster child for a project that made the client developers experience great, and it's reaped the rewards from that.  If proto3 will help improve adoption, and not make internal development much harder, it seems like it may be worth the effort.  

As a side note, GRPC (http://www.grpc.io/) also looks very interesting.

**Comment by petermattis** [comment]
@jmank88 No one is working on a java client as far as I know. I suggest you create an issue ("Create a Java client") and assign it to yourself.

@Linicks We've been paying attention to the GRPC development. I totally agree that providing a great developer experience is important. That said, the protobuf stuff should be below the level most developers are interacting at.

**Comment by bdarnell** [comment]
I've put a snapshot of the proto files at https://github.com/cockroachdb/cockroach-proto with all the gogo options removed; these should be easier to work with in other languages.
