### ISSUE TITLE
IMPORT: retry (don't immediately fail) when connections fail

### ISSUE THREAD

**Issue by rolandcrosby** [cockroachdb/cockroach#39330]
In the current IMPORT implementation, if a single connection to an HTTP(S) or cloud storage endpoint times out or otherwise fails due to a network hiccup, the entire import job will fail. Since import jobs can touch tens or hundreds of large files, this can be extremely frustrating and unforgiving.

Instead of failing immediately, IMPORT should have some standard retry/backoff logic to be more robust to network issues.

**Comment by miretskiy** [comment]
I believe my recent changes to http storage (as well as gs) fixed transient errors
