### ISSUE TITLE
RESTORE throwing error on Rust Postgres Client

### ISSUE THREAD

**Issue by mattcrdb** [cockroachdb/cockroach#39339]
**Describe the problem**

Using the enterprise feature RESTORE runs into an error on the rust Postgres client. 

Errors we have seen thus far include: 

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Db(DbError { severity: "ERROR", parsed_severity: None, code: SqlState("42P01"), message: "relation \"customer\" does not exist", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("sql/sqlbase/errors.go"), line: Some(124), routine: Some("NewUndefinedRelationError") }))', src/libcore/result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

and 

``` 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Db(DbError { severity: "ERROR", parsed_severity: None, code: SqlState("25P02"), message: "current transaction is aborted, commands ignored until end of transaction block", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("sql/sqlbase/errors.go"), line: Some(59), routine: Some("NewTransactionAbortedError") })) 
```

The same RESTORE command successfully restored the database into CockroachDB in python's psycopg2. 

**To Reproduce**

1. set up a 3 node cluster in roachprod, running 19.1.3.
2. run a tpcc workload (~10 warehouses)
3. enable an enterprise license on the cluster
4. backup tpcc table into an s3 bucket or another cloud hosting
5. set up a rust app like [this](https://www.cockroachlabs.com/docs/v19.1/build-a-rust-app-with-cockroachdb.html#main-content)
6. connect to your clusters public ip address (take note of this when setting up cluster)
7. execute the following in the client:

```rust
    conn.execute(
        "RESTORE DATABASE tpcc FROM '<bucket_link_here>';",
        &[],
    ).unwrap();
```

**Expected behavior**

Expected the database to restore properly, without an error. 

**Environment:**
 - CockroachDB version 19.1.3
 - Client app: rust postgres driver

**Additional context**
Unable to successfully perform restores to your database.

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[3542](https://cockroachdb.zendesk.com/agent/tickets/3542) has been linked to this issue.

**Comment by ajwerner** [comment]
Did you set up the database for the connection properly?

**Comment by mattcrdb** [comment]
Closing this issue, the rust client works correctly.
