### ISSUE TITLE
storage: Ineffective assignments in replica_consistency and replica_raftstorage

### ISSUE THREAD

**Issue by xiemaisi** [cockroachdb/cockroach#39348]
**Describe the problem**

[These](https://github.com/cockroachdb/cockroach/blob/3db89b230b0c41e399354cbeb78c1e82c8e30004/pkg/storage/replica_consistency.go#L541) [two](https://github.com/cockroachdb/cockroach/blob/3db89b230b0c41e399354cbeb78c1e82c8e30004/pkg/storage/replica_consistency.go#L543) assignments in method `sha512` in `pkg/storage/replica_consistency.go` look like they have no effect, since the fields are not read in the same method, and `kv` is a local variable which does not escape.

The same goes for [this assignment](https://github.com/cockroachdb/cockroach/blob/3db89b230b0c41e399354cbeb78c1e82c8e30004/pkg/storage/replica_raftstorage.go#L531) in function `snapshot` in `pkg/storage/replica_raftstorage.go`.

**To Reproduce**

I found these issues using static analysis, so I'm afraid I cannot provide reproduction steps.

**Comment by tbg** [comment]
Thank you @xiemaisi!
