### ISSUE TITLE
release: v19.1.4

### ISSUE THREAD

**Issue by kenliu** [cockroachdb/cockroach#39341]
Candidate SHA: [51a6fde](https://github.com/cockroachdb/cockroach/commit/51a6fdedf0ce1d1329d40d801a7deaf8206b6b07)
Deployment status: `ken-release-v1914`
Nightly Suite: [TeamCity Nightly](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_NightlySuite?branch=provisional_201908060405_v19.1.4&buildTypeTab=overview)
 
[Release process checklist](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process)
 
Prep date: `WIP fill in date to roll out: usually Monday, a week before the release WIP`
- [x] [Pick a SHA](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-PickingaSHA), fill in `Candidate SHA` above, notify #release-process of SHA.
- [x] [Tag the provisional SHA](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-TagtheprovisionalSHA)
- [x] [Publish provisional binaries](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Publishtheprovisionalbinaries)
- [x] [Check binaries](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Checkbinaries)
- [x] [Deploy to test clusters](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-DeploytoTestClusters)
- [x] [Start release qualification suite](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-RuntheSuiteofNightlyRoachtests)
- [x] [Start nightly suite](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-RuntheSuiteofNightlyRoachtests)
- [x] [Verify node crash reports](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Verifynodecrashreportsappearinsentry.io)
- [x] fill in `Deployment status` above with clusters and `Nightly Suite` with the link to Nightly TeamCity Job
 
- Keep an eye on clusters until release date. Do not proceed below until the release date.
 
Release date: `WIP fill in date: usually Monday WIP`
- [x] [Check cluster status](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Checkclusterstatus)
- [x] [Tag release](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Tagtherelease)
- [x] [Bless provisional binaries](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Blesstheprovisionalbinaries)
 
- For production or stable releases in the latest major release series
  - [x] Update the [Homebrew Formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/cockroach.rb)
  - [x] Update the image tag in our [Orchestrator configurations](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Orchestratorconfigurations)
  - [x] Announce version to the [registration cluster](https://github.com/cockroachlabs/production#publishing-a-new-release-version)
  - [ ] Upgrade the registration cluster (reg runs latest stable version)
 
- [x] Update docs
- [ ] External communications for release

**Comment by kenliu** [comment]
12 roachtest failures in the nightly build here: https://teamcity.cockroachdb.com/viewLog.html?buildId=1428934&tab=buildResultsDiv&buildTypeId=Cockroach_Nightlies_WorkloadNightly

**Comment by kenliu** [comment]
- [ ] copy/bank/rows=10000000,nodes=9,txn=true
- [ ] hibernate
- [ ] import/experimental-direct-ingestion
- [ ] pgjdbc
- [ ] rebalance-leases-by-load
- [ ] rebalance-replicas-by-load
- [ ] splits/largerange/size=10GiB,nodes=3
- [ ] splits/load/sequential/nodes=3
- [ ] clearrange/checks=false
- [ ] clock/jump/large_backward_enabled
- [ ] tpchbench/tpchVec/nodes=3/cpu=4/sf=1

**Comment by kenliu** [comment]
related tracking issue from @rafiss for pgjdbc failures: https://github.com/cockroachdb/cockroach/issues/38288

**Comment by kenliu** [comment]
test clusters have been up and healthy since they were started. 
![image](https://user-images.githubusercontent.com/47234/62869043-05105580-bce5-11e9-9da0-a41cc2c817a2.png)

**Comment by bdarnell** [comment]
`clock/jump/large_backward_enabled` is #38723 and is not a release blocker.

**Comment by kenliu** [comment]
backwards compat changes for `show ranges`-related tests merged in #39568

**Comment by kenliu** [comment]
`clearrange/checks=false` is a test flake:

```
I190808 03:09:28.999008 1 ccl/workloadccl/cliccl/fixtures.go:324  starting import of 1 tables
		I190808 06:32:00.807565 14 ccl/workloadccl/fixture.go:516  imported bank (3h22m32s, 0 rows, 0 index entries, 0 B)
		Error: importing fixture: importing table bank: pq: communication error: rpc error: code = Canceled desc = context canceled
		Error:  exit status 1
```

**Comment by kenliu** [comment]
reran nightly - [build #1060](https://teamcity.cockroachdb.com/viewLog.html?buildId=1436116&buildTypeId=Cockroach_Nightlies_WorkloadNightly)

new test failures showing up in this run

**Comment by asubiotto** [comment]
Signing off on `hibernate` and `tpchVec` failures, the former needs an updated blacklist (as discussed on slack) while the latter is an unexpected syntax failure while setting the cluster setting. Neither of them are blockers.

**Comment by kenliu** [comment]
- [ ] acceptance/decommission
- [ ] clearrange/checks=true
- [ ] jepsen/monotonic/parts-start-kill-2
- [ ] scaledata/filesystem_simulator/nodes=6
- [ ] schemachange/mixed/tpcc
- [ ] ycsb/F/nodes=3
- [ ] ycsb/F/nodes=3/cpu=32
- [ ] clearrange/checks=false
- [ ] pgjdbc
- [ ] splits/largerange/size=10GiB,nodes=3

**Comment by jeffrey-xiao** [comment]
`ycsb/F/nodes=-3` and `ycsb/F/nodes=3/cpu=32` should be fixed by #39525. Shouldn't be a release blocker.

`splits/largerange/size=10GiB,nodes=3` is a backwards incompatible `SHOW RANGES` test that was missed in #39568.

**Comment by kenliu** [comment]
`clearrange/checks=false` appears to be a flake
![image](https://user-images.githubusercontent.com/47234/62969497-5c90ed00-bddb-11e9-914b-6cd7562d3b2e.png)

**Comment by kenliu** [comment]
Discussed with @bdarnell -- by definition since these new errors were not in the previous run on the same sha, these are flakes, so we are moving ahead with this release.

**Comment by bdarnell** [comment]
The jepsen one is benign. The test hit a whitelisted ssh error and then failed somewhere else in the debugging-collection phase (it's not obvious to me where the problem in the test is)

**Comment by kenliu** [comment]
homebrew merged here https://github.com/Homebrew/homebrew-core/pull/43076

**Comment by kenliu** [comment]
Docs are live.

Still left to do tomorrow: update helm chart and upgrade reg server to latest release.

**Comment by kenliu** [comment]
closing. 

@ajwerner FYI I never updated the helm chart for this release, we should do it for 19.1.5
