### ISSUE TITLE
workload: Ineffective field assignments in jsonLoad.Ops

### ISSUE THREAD

**Issue by xiemaisi** [cockroachdb/cockroach#39349]
**Describe the problem**

[These](https://github.com/cockroachdb/cockroach/blob/3db89b230b0c41e399354cbeb78c1e82c8e30004/pkg/workload/jsonload/json.go#L191) [two](https://github.com/cockroachdb/cockroach/blob/3db89b230b0c41e399354cbeb78c1e82c8e30004/pkg/workload/jsonload/json.go#L193) assignments to `op.g` in method `Ops` in `pkg/workload/jsonload/json.go` look like they have no effect, since the field is not read in the same method, and `op` is a local variable which does not escape.

**To Reproduce**

I found these issues using static analysis, so I'm afraid I cannot provide reproduction steps.

**Comment by jordanlewis** [comment]
Thanks @xiemaisi! I think this is a false positive - `op.run` is a function that has `op` as a pointer receiver. It gets appended to a slice and read later. This causes those assignments to be meaningful - `op` will escape to the heap and be read later.

**Comment by xiemaisi** [comment]
Oh, interesting. Thanks for the explanation!
