### ISSUE TITLE
sql: improve user experience for hash-sharded indexes

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#39340]
The work in https://github.com/cockroachdb/cockroach/issues/37312 to automatically add filters based on check constraints provides a wonderful mechanism to alleviate hot spots due to sequential write workloads. This is now much cleaner and easier to do than the manual addition of filters which preceded it and I look forward to seeing this feature [documented](https://github.com/cockroachdb/docs/issues/5145). 

This feature still requires some relatively unattractive syntax to manually add a computed column which will act as the shard key. Below we'll look at a use of a sharded index and then propose a new syntax to make this functionality easier to use. This issue comes from a discussion with @jordanlewis . 

Imagine we have an IOT application where are tracking devices we are tracking and each device creates events. Sometimes we want to know which devices published events in some time period. We might start with the following schema.

```
CREATE TABLE events (
    device_id
        UUID,
    event_id
        UUID,
    ts
        TIMESTAMP,
    data
        JSONB,
    PRIMARY KEY (device_id, ts, event_id),
    INDEX (ts)
);
```
This schema would have a hot spot on that `INDEX (ts)` which would be rather unfortunate. We can alleviate this hot spot by sharding this time ordered index.

```
CREATE TABLE events (
    device_id
        UUID,
    shard
        INT8
        AS (fnv32(device_id) % 8) STORED
        CHECK (shard IN (0, 1, 2, 3, 4, 5, 6, 7)),
    event_id
        UUID,
    ts
        TIMESTAMP,
    data
        JSONB,
    PRIMARY KEY (device_id, ts, event_id),
    INDEX (shard, ts)
);
```

This isn't too big of a lift here because the device ID is easy to hash in sql. Imagine instead we had a primary key based on some other features:
```

CREATE TABLE events (
    product_id
        INT8,
    owner
        UUID,
    serial_number
        VARCHAR,
    event_id
        UUID,
    ts
        TIMESTAMP,
    data
        JSONB,
    PRIMARY KEY (product_id, owner, serial_number, ts, event_id),
    INDEX (ts)
);
```

In order to shard this we'll need something like:

```
CREATE TABLE events (
    product_id
        INT8,
    owner
        UUID,
    serial_number
        VARCHAR,
    shard
        INT8
        AS (
            fnv32(
                concat(hex(product_id)),
                owner::STRING,
                serial_number
            )
            % 8
        ) STORED
        CHECK (shard IN (0, 1, 2, 3, 4, 5, 6, 7)),
    event_id
        UUID,
    ts
        TIMESTAMP,
    data
        JSONB,
    PRIMARY KEY (
        product_id,
        owner,
        serial_number,
        ts,
        event_id
    ),
    INDEX (shard, ts)
);
```

We can see that this is starting to get heavy. The proposal is that we shoulder the burden of hashing and installing a check constraint behind a new syntax:

```
CREATE TABLE events (
    product_id
        INT8,
    owner
        UUID,
    serial_number
        VARCHAR,
    event_id
        UUID,
    ts
        TIMESTAMP,
    data
        JSONB,
    PRIMARY KEY (product_id, owner, serial_number, ts, event_id),
    INDEX (ts) USING HASH (product_id, owner, serial_number) WITH (BUCKET_COUNT=8)
);
```

This proposed syntax borrows from both [Postgres](https://www.postgresql.org/docs/9.1/indexes-types.html) and [SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/determining-the-correct-bucket-count-for-hash-indexes?view=sql-server-2014). I'm in no way wedded to any syntax proposed here.

**Comment by rafiss** [comment]
This seems really useful! How would one query for, say the 10 most recent events across all shards, when the index is over `(shard, ts)` (or in the case if your ultimate proposal, the index is implicitly sharded). What I'm getting at is: does the query need to specify which shards to look at, or if not, where is that done?

**Comment by jordanlewis** [comment]
The optimizer already has smarts for this - if there's a `CHECK` constraint that forces a column to be in a particular set of values, the optimizer will emit a separate span for every single possible key prefix that the query needs. Here's a quick example in `cockroach demo`:

```
root@127.0.0.1:61581/movr> CREATE TABLE a (a INT, b INT, PRIMARY KEY (a, b), CHECK (a = 1 OR a = 5));
CREATE TABLE

Time: 2.649ms

root@127.0.0.1:61581/movr> EXPLAIN SELECT * from a WHERE b = 90;
  tree |    field    |         description
+------+-------------+-----------------------------+
       | distributed | false
       | vectorized  | false
  scan |             |
       | table       | a@primary
       | spans       | /1/90-/1/90/# /5/90-/5/90/#
       | parallel    |
(6 rows)
```

**Comment by danhhz** [comment]
A related piece for the optimizer is noting that the computed column here is a pure function, so if you're doing an exact lookup on `ts`, you can compute `shard` and use them both together to make the scan a single point lookup.

This is not super useful for the HASH index over ts as described here, but it would be critical if someone wanted a HASH index primary key. (And similarly would be useful in the context of a computed geopartition column).

**Comment by ajwerner** [comment]
If we offered a sql hash function (say `fnv32`) that had an overload for every single SQL datatype and was marked as pure (which it better be), then the hash can just be the sum of the hash of all of the columns. If we represented the shard column as a stored computed column with such an expression would the optimizer today be able to recognize and use functional dependencies? (cc @justinj)

**Comment by jordanlewis** [comment]
@rohany just added (or is in the process of adding) a builtin that turns an arbitrary set of datums into a key - we could use that, and hash the result.

**Comment by rohany** [comment]
The builtin is in here #40878 (not merged yet), and could be useful -- it needs a table ID and index ID though.

**Comment by nvanbenschoten** [comment]
It's worth enumerating all of the different pieces of intelligence we'd need out of the optimizer to make the UX around this useful. Here's an incomplete list to start:
```sql
###############################################################################
# 1) use check constraints to use and constrain index scans for point lookups
#    implemented: yes

root@127.0.0.1:53494/movr> CREATE TABLE a1 (a INT, b INT, PRIMARY KEY (a, b), CHECK (a = 1 OR a = 5));

root@127.0.0.1:53494/movr> EXPLAIN SELECT * from a1 WHERE b = 90;
  tree |    field    |         description
+------+-------------+-----------------------------+
       | distributed | false
       | vectorized  | false
  scan |             |
       | table       | a1@primary
       | spans       | /1/90-/1/90/# /5/90-/5/90/#
       | parallel    |

###############################################################################
# 2) use check constraints to use and constrain index scans for bounded lookups
#    implemented: yes

root@127.0.0.1:53494/movr> EXPLAIN SELECT * from a1 WHERE b > 90;
  tree |    field    |    description
+------+-------------+-------------------+
       | distributed | false
       | vectorized  | false
  scan |             |
       | table       | a1@primary
       | spans       | /1/91-/2 /5/91-/6

root@127.0.0.1:53494/movr> EXPLAIN SELECT * from a1 WHERE b < 90;
  tree |    field    |      description
+------+-------------+-----------------------+
       | distributed | false
       | vectorized  | false
  scan |             |
       | table       | a1@primary
       | spans       | /1-/1/89/# /5-/5/89/#

root@127.0.0.1:53494/movr> EXPLAIN SELECT * from a1 WHERE b BETWEEN 90 AND 91;
  tree |    field    |         description
+------+-------------+-----------------------------+
       | distributed | false
       | vectorized  | false
  scan |             |
       | table       | a1@primary
       | spans       | /1/90-/1/91/# /5/90-/5/91/#
       | parallel    |

###############################################################################
# 3) use check constraints to identify partial orderings to avoid full table scan and sort
#    implemented: no
#    desired: limit each partition and then merge partitions. Similar to how DistSQL
#             works with pushing down limits

root@127.0.0.1:53494/movr> EXPLAIN SELECT * from a1 ORDER BY b LIMIT 5;
       tree      |    field    | description
+----------------+-------------+-------------+
                 | distributed | true
                 | vectorized  | false
  limit          |             |
   │             | count       | 5
   └── sort      |             |
        │        | order       | +b
        └── scan |             |
                 | table       | a1@primary
                 | spans       | ALL

###############################################################################
# 4) derive computed columns when functionally dependent on known values
#    implemented: no
#    desired: should be able to compute derived columns and use them to
#             further constrain spans. Dan mentioned this above in
#             https://github.com/cockroachdb/cockroach/issues/39340#issuecomment-535168869.

root@127.0.0.1:53494/movr> CREATE TABLE a2 (
    even INT AS (CASE WHEN b%2 = 0 THEN 1 ELSE 0 END) STORED, 
    b INT, 
    PRIMARY KEY (even, b), 
    CHECK       (even IN (0, 1))
);

root@127.0.0.1:53494/movr> EXPLAIN SELECT * from a2 WHERE b = 90;
  tree |    field    |         description
+------+-------------+-----------------------------+
       | distributed | false
       | vectorized  | false
  scan |             |
       | table       | a2@primary
       | spans       | /0/90-/0/90/# /1/90-/1/90/#
       | parallel    |

###############################################################################
# 5) all of this to work for constraining spans used by mutations
#    implemented: yes

root@127.0.0.1:53494/movr> CREATE TABLE a3 (a INT, b INT, C INT, PRIMARY KEY (a, b), CHECK (a = 1 OR a = 5));

root@127.0.0.1:53494/movr> explain update a3 set c = 5 where b = 90;
         tree         |    field    |         description
+---------------------+-------------+-----------------------------+
                      | distributed | false
                      | vectorized  | false
  count               |             |
   └── update         |             |
        │             | table       | a3
        │             | set         | c
        │             | strategy    | updater
        └── render    |             |
             └── scan |             |
                      | table       | a3@primary
                      | spans       | /1/90-/1/90/# /5/90-/5/90/#
                      | parallel    |

root@127.0.0.1:53494/movr> explain delete from a3 where b = 90;
      tree     |    field    |         description
+--------------+-------------+-----------------------------+
               | distributed | false
               | vectorized  | false
  delete range |             |
               | from        | a3
               | spans       | /1/90-/1/90/# /5/90-/5/90/#

###############################################################################
# 6) anything else?
```

**Comment by justinj** [comment]
#4 is super cool. FWIW just to clarify, I think "functional dependencies" are not quite the right way to think about it. It's possible to have a computed column that's functionally dependent on the set of columns in an index, but still not be able to determine the value of that computed column without doing a lookup:
```
CREATE TABLE a (
  pk INT,
  a INT,
  b INT AS (a + 1) STORED,
  c INT,
  UNIQUE INDEX (c)
);
```
In this case, `c` functionally determines everything, but we can't determine the value of `b` solely from a given value of `c` (and `pk`) without doing a lookup. Perhaps this might be more accurately phrased as "derive value of computed columns when all columns they reference are available" (I'm kind of being pedantic here, doesn't matter that much)?
