### ISSUE TITLE
Add `reject` authentication mechanism for host-based authentication

### ISSUE THREAD

**Issue by rolandcrosby** [cockroachdb/cockroach#39363]
We have implemented a subset of the Postgres [host-based authentication functionality](https://www.postgresql.org/docs/10/auth-pg-hba-conf.html) via the `server.host_based_authentication.configuration` cluster setting. One handy feature that Postgres provides that we haven't implemented is a `reject` authentication mechanism that always rejects connections. This could be used to explicitly block certain users, hostnames, or IP ranges from connecting to the database.

**Comment by knz** [comment]
this has been achieved
