### ISSUE TITLE
cli: add warning about replication factor when starting a node with cockroach start-single-node

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#39379]
When starting a single node cluster with the new `cockroach start-single-node` command, we now set the default replication factor to 1. We should warn users about this on cluster startup so that they are not surprised by the lack of resiliency for their data if they choose to scale their cluster. 

Some existing warnings look like the following:
```
*
* WARNING: RUNNING IN INSECURE MODE!
* 
* - Your cluster is open for any client that can access <all your IP addresses>.
* - Any user, even root, can log in without providing a password.
* - Any user, connecting as root, can read or write any data in your cluster.
* - There is no network encryption nor authentication, and thus no confidentiality.
* 
* Check out how to secure your cluster: https://www.cockroachlabs.com/docs/v19.2/secure-a-cluster.html
*
*
* WARNING: neither --listen-addr nor --advertise-addr was specified.
* The server will advertise <name> to other nodes, is this routable?
* 
* Consider using:
* - for local-only servers:  --listen-addr=localhost
* - for multi-node clusters: --advertise-addr=<host/IP addr>
* 
*
```

My proposal for wording this warning would be something like:
```
* WARNING: The replication factor for single node clusters is set to 1 by default. 
* If adding nodes to this cluster, increase the replication factor to improve resiliency.
* 
* Learn more here: <link to cockroach start-single-node docs>
* 
```

Alternatively, it might be possible to overcome this problem by increasing the replication factor automatically to the previous default of 3 via a mechanism similar to the one we use to increase replication factor to 5 for system ranges.

cc @knz - we discussed this in person briefly today

**Comment by knz** [comment]
I'm going to improve this once #39404 is in
