### ISSUE TITLE
sql: support Squirrel SQL

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#39396]
[Squirrel SQL](http://squirrel-sql.sourceforge.net
) is a pure Java tool. It connects and mostly works with CRDB however it does error occasionally, particularly with displaying the content of some system tables.

**Comment by yuzefovich** [comment]
Last Friday, I poked around this tool a little bit and actually didn't encounter any issues. If someone runs into a problem, please document the steps to reproduce it :)

**Comment by awoods187** [comment]
Let's close this issue then until someone confirms a problem.
