### ISSUE TITLE
colrpc: clean up Outbox/Inbox log tags

### ISSUE THREAD

**Issue by asubiotto** [cockroachdb/cockroach#39399]
In a distributed plan nodes talk to each other with Outboxes (on the sending side) and Inboxes (on the receiving side). An Outbox/Inbox pair is identified with a `StreamID`. An outbox annotates its log tags with a stream ID here:
https://github.com/cockroachdb/cockroach/blob/9990dc7d7ec7459b4da8ce27bb67e8f8f1fc985f/pkg/sql/exec/colrpc/outbox.go#L119
The issue is that this annotation is only complete for `Outbox`es. `Inbox`es use the context passed in to `Next` for logging which, confusingly, if an `Outbox` is `Next`ing them, will be annotated with the wrong stream ID (that `Outbox`). A solution to this could be that the `Outbox` could derive a child context used for logging that it annotates with its stream ID but does not use to `Next` its input tree and that `Inbox`es are made aware of their stream ID for logging during construction and annotate their context in `maybeInit`.

**Comment by Gurio** [comment]
@asubiotto I would like to pick this, if it is still avaliable.
and few questions: 
* As far as I can see, `streamID` is transferred as part of ProducerMessage.Header, but only on establishing the connection. Should I just maybe put the Header in every message, and read it on the inbox side? 
* Are there tests for that?
* Is there a simple way to reproduce it locally? Like run two instances, with logs enabled, and run some requests. How to configure those two instances? Which requests to run?

**Comment by asubiotto** [comment]
It definitely is still available, thanks!
- The `streamID` is available at set up time when creating the inbox here: https://github.com/cockroachdb/cockroach/blob/a897b9c98015736af2e53f526d8bd078b4defcd7/pkg/sql/distsqlrun/column_exec_setup.go#L1206 I think you'd probably just want to plumb it into the constructor rather than sending it in every message.
- There are no tests for correct logging behavior.
- You could probably reproduce it if you start a 3-node cockroach cluster with the flag `--vmodule=outbox=2,inbox=2` and run a `SELECT COUNT(*)` on a table after [splitting](https://www.cockroachlabs.com/docs/stable/split-at.html) and [relocating](https://www.cockroachlabs.com/docs/v2.1/experimental-features.html#relocate-leases-and-replicas) the split ranges on to different nodes to force a distributed count. That will show that inboxes don't have stream IDs (i.e. the gateway node log messages won't be annotated). If you run a more complicated query like a join, you will probably see that some inbox log messages have stream IDs that you also find in outbox log messages (i.e. when getting data to join and then sending that back to the gateway) and some inboxes again won't have streamID annotations on the gateway. Note that you can run `EXPLAIN (DISTSQL) <QUERY>` to get the distributed execution plan.
- The above reproduction is not very simple so I think a better way would be to write a unit test that looks at the tags in the context that an outbox uses to call `Next` with by using a `CallbackOperator` (mocking out the input tree) to assert that there is no streamID in there (would fail with the current state of things), and then assert that an `Inbox` context does contain the expected streamID in `Next` and `DrainMeta` by reading from the `readerCtx` channel while asynchronously calling `Next` and then doing it again with `DrainMeta`.
