### ISSUE TITLE
Docker on Win10 failed to start with an error:

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#39409]
Docker on Win10 failed to start with an error:
`hardware assisted virtualization and data execution protection must be enbaled in the BIOS. See https://docs.docker.com/docker-for-windows/troubleshoot/#virtualization-must-be-enabled`
The underlying cause is Boot Camp's startup behavior--disabling hardware virtualization on cold win10 boot. However, if botting into MacOS, hardware virtualization is always enabled. 

As a workaround, the user was able to find this solution:
1. Fully power off
2. Power on holding Option key and boot to MacOS. This enables virtualization in hardware
3. Restart into Win10. Virtualization stays enabled and Hyper-V is present, Docker works.

Jira issue: CRDB-5577

**Comment by knz** [comment]
How is this a cockroachdb error? It seems like a docker issue.
