### ISSUE TITLE
sql: PSQL utility did not work with CRDB on Win10

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#39423]
PSQL utility did not work with CRDB on Win10. 

```
% psql postgresql://root@localhost:26257/postgres psql: ERROR: unimplemented client encoding: "win1252" HINT: This feature is not yet implemented in CockroachDB.
```

From a user:

> A git search shows several reports of similar issues (client encoding not matching the only supported “utf8”). However psql has a supported way to set client encoding in psqlrc.conf file. I set client encoding to “utf8” and checked with PG server – the SET instruction is delivered to the server. However when trying to connect to CockroachDB I received the same error message. This suggests that the core issue is CockroachDB server not processing SET client_encoding instruction from the client.

**Comment by darinpp** [comment]
It seems to be working when you request the encoding to be UTF8:
```
C:\>set PGCLIENTENCODING=UTF8

C:\>"c:\Program Files\PostgreSQL\11\bin\psql.exe" postgresql://root@10.211.55.3:26257/postgres
psql (11.5, server 9.5.0)
WARNING: Console code page (437) differs from Windows code page (1252)
         8-bit characters might not work correctly. See psql reference
         page "Notes for Windows users" for details.
Type "help" for help.
```

**Comment by darinpp** [comment]
I think that setting the client encoding to UTF8 in psqlrc.conf doesn't work with CockroachDB. The only option is to set it through the `PGCLIENTENCODING` environment variable. 
The reason why psqlrc.conf doesn't work is that the settings there are used after you are connected to the server. They would be useful if CockroachDB had a support for both win1252 and utf8. And in that case the initial connection would've been done with win1252 and switched then to utf8. As is now - CockroachDB doesn't support win1252 so there is no way to connect first with win1252 encoding and then switch to utf8.
