### ISSUE TITLE
sql: "SELECT *,rank() OVER(PARTITION BY i ORDER BY j desc) AS r FROM t1;" returns wrong results

### ISSUE THREAD

**Issue by eiDear** [cockroachdb/cockroach#39447]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

SQL **SELECT *,rank() OVER(PARTITION BY i ORDER BY j desc) AS r FROM t1;** returns the wrong results.

**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. start a local-single-node CockroachDB cluster
`cockroach start 
    --insecure 
    --advertise-addr=0.0.0.0:26257 
    --http-addr=0.0.0.0:8080`
2. log in cockroachdb with builtin client -sql.
```sql
cockroach sql --insecure
```
then create table `t1`, and insert data into `t1`
```sql
CREATE TABLE t1(i int, j int);
INSERT INTO t1 VALUES(2,1),(2,3),(2,3),(2,5),(3,2),(3,2),(3,2),(3,4),(3,1),(3,5);
```
execure select sql :
```sql
SELECT *,rank() OVER(PARTITION BY i ORDER BY j desc) AS r FROM t1;
```
3. the result is 
```sql
root@:26257/defaultdb> SELECT *,rank() OVER(PARTITION BY i ORDER BY j desc) AS r FROM t1;
  i | j | r  
+---+---+---+
  2 | 1 | 4  
  2 | 3 | 2  
  2 | 3 | 2  
  2 | 5 | 1  
  3 | 2 | 3  
  3 | 2 | 3  
  3 | 2 | 3  
  3 | 4 | 2  
  3 | 1 | 6  
  3 | 5 | 1  
(10 rows)

Time: 2.01894ms

```

4. the question (or bug)
the result showed that the records are partitioned by column i  into two groups- records are together with the same value in column `i` . However, the results do not order by column j descending bug mixed.  

**Expected behavior**
We except the results within partitioned by column `i`  order by another column `j`  descending like other database. e.g. , 
- MySQL8.0.17 does :
```sql
mysql> SELECT *,RANK() OVER(PARTITION BY i ORDER BY j desc) AS r FROM t1;
+------+------+---+
| i    | j    | r |
+------+------+---+
|    2 |    5 | 1 |
|    2 |    3 | 2 |
|    2 |    3 | 2 |
|    2 |    1 | 4 |
|    3 |    5 | 1 |
|    3 |    4 | 2 |
|    3 |    2 | 3 |
|    3 |    2 | 3 |
|    3 |    2 | 3 |
|    3 |    1 | 6 |
+------+------+---+
10 rows in set (0.00 sec)

```

- postgresql does:
```sql
postgres=# SELECT *,RANK() OVER(PARTITION BY i ORDER BY j desc) AS rank FROM t1;
 2 | 5 |    1
 2 | 3 |    2
 2 | 3 |    2
 2 | 1 |    4
 3 | 5 |    1
 3 | 4 |    2
 3 | 2 |    3
 3 | 2 |    3
 3 | 2 |    3
 3 | 1 |    6

```

**Additional data / screenshots**
None.

**Environment:**
 - CockroachDB version 
19.1.0, and 19.2.0(DEV)
 - Server OS
Linux version 3.10.0-957.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ) #1 SMP Thu Nov 8 23:39:32 UTC 2018
 - Client app
 `cockroach sql`

**Additional context**

None.

**Comment by jordanlewis** [comment]
Thanks for the report and sorry for the trouble.

cc @yuzefovich, please take an initial look when you have a chance.

**Comment by yuzefovich** [comment]
Thanks for the report!

If you take a closer look at the output of CockroachDB on the query, you'll notice that it consists of the same rows as the output of MySQL and PostgreSQL, just in a different order. And since `ORDER BY` is not specified for the query, actually both of the outputs are correct. In order to get the same output from CockroachDB as from the two other databases you can use this query:
`SELECT *,rank() OVER(PARTITION BY i ORDER BY j desc) AS r FROM t1 ORDER BY i, j DESC;`
(I haven't tried it, but I'm quite certain it'll work).

Please let me know if you have any follow-up questions.

**Comment by eiDear** [comment]
> Thanks for the report!
> 
> If you take a closer look at the output of CockroachDB on the query, you'll notice that it consists of the same rows as the output of MySQL and PostgreSQL, just in a different order. And since `ORDER BY` is not specified for the query, actually both of the outputs are correct. In order to get the same output from CockroachDB as from the two other databases you can use this query:
> `SELECT *,rank() OVER(PARTITION BY i ORDER BY j desc) AS r FROM t1 ORDER BY i, j DESC;`
> (I haven't tried it, but I'm quite certain it'll work).
> 
> Please let me know if you have any follow-up questions.

Thanks for your reply! 
"it consists of the same rows as the output of MySQL and PostgreSQL, just in a different order. "  from your reply is correctly what I wanted to say: **I am sure I want the ordered rows by column j descending.** 
> `SELECT *,rank() OVER(PARTITION BY i ORDER BY j desc) AS r FROM t1 ORDER BY i, j DESC;`
likely returns the same rows and the same effects, but I do not want to order by column i. I JUST WANT TO `PARTITION BY I` and `ORDER BY J DESCENDING`. the sql `SELECT *,rank() OVER(PARTITION BY i ORDER BY j desc) AS r FROM t1 ORDER BY i, j DESC;` seems doing some cumbersome work.

**Comment by yuzefovich** [comment]
So if you want to **guarantee** that the output rows are ordered by column `i` in ascending order first and the by column `j` in descending order, you **have to** specify `ORDER BY i, j DESC` with **any** database because without an explicit `ORDER BY` in the query, the output *can* be in any order.

It just so happens that both PostgreSQL and MySQL return the rows in an order that you expected. It is not a correctness issue in CockroachDB because SQL standard allows for returning the rows in any order if `ORDER BY` is omitted for a query.

**Comment by eiDear** [comment]
> So if you want to **guarantee** that the output rows are ordered by column `i` in ascending order first and then by column `j` in descending order, you **have to** specify `ORDER BY i, j DESC` with **any** database because without an explicit `ORDER BY` in the query, the output _can_ be in any order.
> 
> It just so happens that both PostgreSQL and MySQL return the rows in the order that you expected. It is not a correctness issue in CockroachDB because SQL standard allows for returning the rows in any order if `ORDER BY` is omitted in the query.

OK. I do another experiment and the result is :
```sql
> SELECT *,rank() OVER(PARTITION BY i ORDER BY i desc, j desc) AS r FROM t1;
  i | j | r  
+---+---+---+
  2 | 1 | 4  
  2 | 3 | 2  
  2 | 3 | 2  
  2 | 5 | 1  
  3 | 2 | 3  
  3 | 2 | 3  
  3 | 2 | 3  
  3 | 4 | 2  
  3 | 1 | 6  
  3 | 5 | 1  
  6 | 3 | 1  
  7 | 2 | 1 
```

the returned rows are not ordered with `order by i desc, j desc` in the windower `rank() over( partition by i )`. 
And I execute `explain analyze`, I find that the `order by` in windower `rank() over( partition by i )` does not generate physical plan.
`explain analyze SELECT *,rank() OVER(PARTITION BY i ORDER BY j desc) AS r FROM t1;`:
![1](https://user-images.githubusercontent.com/6024149/62774791-74652a00-bad8-11e9-9b49-55f4ab5f1a9e.png)
`explain analyze SELECT *,rank() OVER(PARTITION BY i ORDER BY i desc, j desc) AS r FROM t1;`:
![2](https://user-images.githubusercontent.com/6024149/62774819-8cd54480-bad8-11e9-93f8-d3858dd4df56.png)

however the sql you offered has an additional sorter. `explain analyze SELECT *,rank() OVER(PARTITION BY i ORDER BY j desc) AS r FROM t1 ORDER BY i, j DESC;`:
![3](https://user-images.githubusercontent.com/6024149/62774942-e3428300-bad8-11e9-8003-1d659516169b.png)
`explain analyze SELECT *,rank() OVER(PARTITION BY i) AS r FROM t1 ORDER BY i, j DESC;`:
![4](https://user-images.githubusercontent.com/6024149/62775160-7bd90300-bad9-11e9-8b8e-26721470b17a.png)

so I guess the `order by` in windower `rank() over( partition by i )` does not work.

**Comment by yuzefovich** [comment]
Everything you posted above behaves correctly and exactly as required by the SQL standard.

I think the issue here is that it's not intuitive to you that both a window function and a query can have `ORDER BY` specified. `ORDER BY` clause of a window function determines the order in which rows are processed by the window function, but it has *no influence* on the output order for the query. On the other side, `ORDER BY` for the whole query has no influence on the window function, but it determines the order in which the result rows are output.

Here is a simple example that might clarify things for you:
```
root@127.0.0.1:49466/defaultdb> CREATE TABLE t (a INT PRIMARY KEY);
CREATE TABLE

Time: 2.146ms

root@127.0.0.1:49466/defaultdb> INSERT INTO t VALUES (1), (2), (3);
INSERT 3

Time: 3.01ms

root@127.0.0.1:49466/defaultdb> SELECT a, rank() OVER (ORDER BY a) FROM t;
  a | rank  
+---+------+
  1 |    1  
  2 |    2  
  3 |    3  
(3 rows)

Time: 2.726ms

root@127.0.0.1:49466/defaultdb> SELECT a, rank() OVER (ORDER BY a DESC) FROM t;
  a | rank  
+---+------+
  1 |    3  
  2 |    2  
  3 |    1  
(3 rows)

Time: 595µs

root@127.0.0.1:49466/defaultdb> SELECT a, rank() OVER (ORDER BY a DESC) AS r FROM t ORDER BY r;
  a | r  
+---+---+
  3 | 1  
  2 | 2  
  1 | 3  
(3 rows)

Time: 2.377ms
```

I encourage you to read through our excellent documentation https://www.cockroachlabs.com/docs/stable/window-functions.html and https://www.cockroachlabs.com/docs/stable/query-order.html.

If you still have questions, please post them on our forum (https://forum.cockroachlabs.com/). I will close this issue because there is no correctness problem here.

**Comment by eiDear** [comment]
OK. Thank U very much @yuzefovich . Now I know it is right within SQL Standard. `Order by` in sub-query and window functions does not affect the returned rows from top-level query. Thank you.
It would be better if this works. 

> Everything you posted above behaves correctly and exactly as required by the SQL standard.
> 
> I think the issue here is that it's not intuitive to you that both a window function and a query can have `ORDER BY` specified. `ORDER BY` clause of a window function determines the order in which rows are processed by the window function, but it has _no influence_ on the output order for the query. On the other side, `ORDER BY` for the whole query has no influence on the window function, but it determines the order in which the result rows are output.
> 
> Here is a simple example that might clarify things for you:
> 
> ```
> root@127.0.0.1:49466/defaultdb> CREATE TABLE t (a INT PRIMARY KEY);
> CREATE TABLE
> 
> Time: 2.146ms
> 
> root@127.0.0.1:49466/defaultdb> INSERT INTO t VALUES (1), (2), (3);
> INSERT 3
> 
> Time: 3.01ms
> 
> root@127.0.0.1:49466/defaultdb> SELECT a, rank() OVER (ORDER BY a) FROM t;
>   a | rank  
> +---+------+
>   1 |    1  
>   2 |    2  
>   3 |    3  
> (3 rows)
> 
> Time: 2.726ms
> 
> root@127.0.0.1:49466/defaultdb> SELECT a, rank() OVER (ORDER BY a DESC) FROM t;
>   a | rank  
> +---+------+
>   1 |    3  
>   2 |    2  
>   3 |    1  
> (3 rows)
> 
> Time: 595µs
> 
> root@127.0.0.1:49466/defaultdb> SELECT a, rank() OVER (ORDER BY a DESC) AS r FROM t ORDER BY r;
>   a | r  
> +---+---+
>   3 | 1  
>   2 | 2  
>   1 | 3  
> (3 rows)
> 
> Time: 2.377ms
> ```
> 
> I encourage you to read through our excellent documentation https://www.cockroachlabs.com/docs/stable/window-functions.html and https://www.cockroachlabs.com/docs/stable/query-order.html.
> 
> If you still have questions, please post them on our forum (https://forum.cockroachlabs.com/). I will close this issue because there is no correctness problem here.

OK. Thank U very much @yuzefovich . Now I know it is right within SQL Standard. `Order by` in sub-query and window functions does not affect the returned rows from top-level query. Thank you.
It would be better if this works.
