### ISSUE TITLE
build (regression): arm64 build broken due to kerberos something

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#39480]
Repro:

`build/builder.sh mkrelease arm64-linux`

This fails with:

```
cd /go/native/aarch64-unknown-linux-gnueabi/krb5 && env -u CFLAGS -u CXXFLAGS /go/src/github.com/cockroachdb/cockroach/c-deps/krb5/src/configure   --host=aarch64-unknown-linu
x-gnueabi CC=aarch64-unknown-linux-gnueabi-cc CXX=aarch64-unknown-linux-gnueabi-c++ --enable-static --disable-shared
[...]
checking for constructor/destructor attribute support... configure: error: Cannot test for constructor/destructor support when cross compiling
Makefile:583: recipe for target '/go/native/aarch64-unknown-linux-gnueabi/krb5/Makefile' failed
```

I can work around by editing the Makefile to avoid building kerberos, by tweaking the match:
```diff
-ifeq "$(findstring linux-gnu,$(TARGET_TRIPLE))" "linux-gnu"
+ifeq "$(findstring linux-gnu,$(TARGET_TRIPLE))" "linux-gnuxx"
```

That said I'm pretty confident it's possible to build for kerberos. The `configure` check that's failing is an auto-detection, this check can be disabled by telling the configure script explicitly about whether the ctor/dtors are supported in the target (IIRC, they are).

cc @nvanbenschoten @mjibson

**Comment by benesch** [comment]
Setting the following environment variables should do the trick:

```
export krb5_cv_attr_constructor_destructor=yes
export ac_cv_func_regcomp=yes
export ac_cv_printf_positional=yes
```

(Assuming those are actually the correct values for the toolchain.)
