### ISSUE TITLE
Question: How custom node name?

### ISSUE THREAD

**Issue by cevin** [cockroachdb/cockroach#39494]
like `--name cn-west-node1` ?

**Comment by mattcrdb** [comment]
Hello @cevin,

Currently, we do not support naming nodes.

I can suggest setting up a local alias to reference that node using it's public IP address.

Is there something specific you are trying to do with the name?

Thanks,
Matt

**Comment by mattcrdb** [comment]
Hey, just checking in whether you were able to see this.

**Comment by mattcrdb** [comment]
I'm going to close this issue.

Please reopen if you would like to discuss further.
