### ISSUE TITLE
sql: old, truncated descriptors can become corrupt. is this a problem?

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#39498]
Consider the following scenario:

```
CREATE TABLE a (a INT PRIMARY KEY);
CREATE TABLE b (a INT PRIMARY KEY, b INT REFERENCES a(a));
INSERT INTO a VALUES(1);
TRUNCATE a;
```

This sequence of events produces 3 on-disk table descriptors:

1. `a` before truncation, with backreference to `b`. It's in the DROPPED state.
2. `a` after truncation (call it `a'`), with backreference to `b`
3. `b`, with forward reference to `a'`

Now, perform the following operation:

```
ALTER TABLE b DROP COLUMN b;
```

This operation modifies descriptors 2 and 3, by removing their forward and back references.

But, it leaves descriptor 1 alone! Descriptor 1 is now corrupt, since it contains a backreference to a table that has no corresponding forward reference.

Is this a problem? Do dropped tables need to be non-corrupt?

**Comment by jordanlewis** [comment]
cc @lucy-zhang.

**Comment by lucy-zhang** [comment]
Closing since we're not sure there's actually any user-facing impact from this; the old descriptor after TRUNCATE doesn't seem like it would be read or used for anything.
