### ISSUE TITLE
sql: Should the Div builtin function divide or return an integer quotient?

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#3950]
As @JackKrupansky noted in [this](https://github.com/cockroachdb/cockroach/pull/3902#issuecomment-172601849) post, Postgres implemented the `div(y numeric, x numeric)` builtin function as returning the "integer quotient of y/x". We currently have this function implemented in the same way as the division numerical operator (ie. `div(-1.0, 2.0)` gives `-0.5`). Was this an oversight or an intentional divergence?

**Comment by bdarnell** [comment]
I think div() should return an integer so it can be paired with mod().
Without that relationship what would be the point of a function that is
redundant with the / operator?
