### ISSUE TITLE
exec: UX for determining whether a particular query will run with vectorized or not

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#39523]
We need to make sure that our users can tell whether a particular query will run with the vectorized engine or not, so that our users understand and so that we'll be able to tell at a glance when an issue arises how to proceed.

Ideally, we could expose this in `explain`, but that will probably be tricky due to how early `explain` goes in the pipe.

At the very least, we should add it to `explain(vec)` (and maybe trim down the output of `explain(vec)` so that it's not completely impossible to parse at a glance.

**Comment by awoods187** [comment]
I'm interested in us trying to get it to be a part of the regular explain process because I already think we have a proliferation of explain types. That being said, if it needs to be an explain (vec) for now than we can do that. Perhaps we can check if vec is turned on and then run explain(vec) by default for explain and if not run regular explain.

**Comment by awoods187** [comment]
Also i think we need to do this prior to 19.2

**Comment by jordanlewis** [comment]
The problem is that `explain(vec)` isn't a suitable replacement for `explain` - it's more like debugging information. I agree we need something like this done for 19.2 - but just the boolean "will this be run w/ vectorized or not". I think it should probably also have a boolean about whether it'll be distributed or not, while we're at it.

**Comment by rafiss** [comment]
Where would we want these booleans to appear? `explain` returns rows that look like this. Is it possible to just have extra metadata strings apart from this return table?

```
               tree              |       field       |        description
+--------------------------------+-------------------+---------------------------+
  render                         |                   |
   └── group                     |                   |
        │                        | aggregate 0       | sum(column26)
        │                        | aggregate 1       | sum(column28)
        │                        | scalar            |
        └── render               |                   |
             └── hash-join       |                   |
                  │              | type              | inner
                  │              | equality          | (p_partkey) = (l_partkey)
                  │              | left cols are key |
                  ├── scan       |                   |
                  │              | table             | part@primary
                  │              | spans             | ALL
                  └── index-join |                   |
                       │         | table             | lineitem@primary
                       └── scan  |                   |
                                 | table             | lineitem@l_sd
                                 | spans             | /9374-/9404
```

**Comment by jordanlewis** [comment]
There's nothing that parses these things, so we can kind of do whatever we want. Can you search for some prior art in other databases? Are there explain plans that have other top level options to display?
