### ISSUE TITLE
Remove pprofport from `cockroach workload init [command] --help` output

### ISSUE THREAD

**Issue by ericharmeling** [cockroachdb/cockroach#39566]
The help output for all workload commands returns the flag `pprofport` as a viable option. This flag probably shouldn't be visible to customers.

e.g.
```
$ cockroach workload init bank --help
```
returns
```
--pprofport int       Port for pprof endpoint. (default 33333)
```
in its list of flags.

I'm removing these flags from the user reference documentation (https://github.com/cockroachdb/docs/issues/5207).

**Comment by tharun208** [comment]
is this issue closed or still open, if it is open, I like to give it a shot

**Comment by ajwerner** [comment]
Yes this issue is still open. Probably all that needs to happen here is a call to `MarkHidden` on the flagset for this flag. https://godoc.org/github.com/spf13/pflag#FlagSet.MarkHidden
