### ISSUE TITLE
storage: fix and re-enable rocksdb assertions

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#39564]
We just had to disable them again since they fail to re-establish some amount of sanity on `master`. We need to fix the underlying problems and reenable the assertions ASAP.

https://github.com/cockroachdb/cockroach/pull/39562

**Comment by ajkr** [comment]
Our preferred solution is https://github.com/facebook/rocksdb/pull/5539. I am fine waiting and seeing if it gets merged before backporting it and reenabling assertions.

**Comment by ajkr** [comment]
Fixed by #41153.
