### ISSUE TITLE
Getting brew to install all depencies

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#3959]
In a comment on [this pull request](https://github.com/cockroachdb/docs/pull/15), @petermattis showed me that you can use brew to install cockroachdb on os x: `brew install https://raw.githubusercontent.com/cockroachdb/cockroach/master/build/cockroach.rb)` 

When I ran that, brew seems to have checked for GO before getting the cockroach code. It would be great if brew could check for and install all dependencies:

- A C++ compiler that supports C++11 (GCC 4.9+ and clang 3.6+ are known to work). On Mac OS X, Xcode should suffice.
- A Go environment with a 64-bit version of Go 1.5. You can download the Go binary directly from the official site. On OS X, you can also use homebrew: brew install go.
- Git 1.8+

@mberhault, @bdarnell: If we're already doing this and I just missed it, feel free to close.

**Comment by tamird** [comment]
I believe with the execption of Go, these requirements are already required by homebrew itself.

**Comment by jseldess** [comment]
Ah, thanks, @tamird: Looks like you're right. Given the xcode is a prerequisite, and that gives you the C++ compiler and git. 

https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Installation.md
