### ISSUE TITLE
jobs: Use separate tables for cancellation and progress

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#39601]
We sometimes see issues like #36601 in which a job runs away updating its progress and renders the jobs table unwriteable. This is especially problematic because canceling a job requires a write to the jobs table. We should refactor things so that cancellation is managed through a separate table from the one used for progress updates (and/or provide a cancellation signal that's not table-based at all, such as using gossip).

I understand that this wouldn't help with #36601 because schema changes are not currently cancelable, but since issues like this have come up a few times it seems like a good idea to make this more robust for the future.

CC @dt @rolandcrosby 

Jira issue: CRDB-5571

**Comment by rolandcrosby** [comment]
cc @spaskob - something to think about as part of the jobs refactor. As David mentioned today, we already put progress in a separate column family to minimize impact on the main KV for the job record, but that doesn't help us with cancellation.

```
root@127.0.0.1:59936/defaultdb> show create table system.jobs;
      table_name     |                              create_statement
+--------------------+----------------------------------------------------------------------------+
  system.public.jobs | CREATE TABLE jobs (
                     |     id INT8 NOT NULL DEFAULT unique_rowid(),
                     |     status STRING NOT NULL,
                     |     created TIMESTAMP NOT NULL DEFAULT now():::TIMESTAMP,
                     |     payload BYTES NOT NULL,
                     |     progress BYTES NULL,
                     |     CONSTRAINT "primary" PRIMARY KEY (id ASC),
                     |     INDEX jobs_status_created_idx (status ASC, created ASC),
                     |     FAMILY fam_0_id_status_created_payload (id, status, created, payload),
                     |     FAMILY progress (progress)
                     | )
(1 row)
```

**Comment by dt** [comment]
I like the idea of two tables: job definition and running status in one, job state/progress in another.

**Comment by bdarnell** [comment]
> leave the special IDs for the tables that need them (we have 50 of which ~24 have been used

The only ones that really need reserved IDs are the "system config" tables (the first 10 of the 50 reserved IDs, of which 6 have been used). For the rest, I don't think there's any great reason for them to reserve IDs - it was just an attempt to minimize the differences between clusters that had gone through the migration path and those that were bootstrapped at a new version. (and "50 system tables ought to be enough for anybody")

So go ahead and use those last 26 table IDs; there's no reason to save them for a special purpose. We'll need to move to non-reserved ID assignments when we get that far (if we haven't already to simplify the migration code), but there's no need to rush that step.

**Comment by dt** [comment]
Hm, I think there is a chance that at some point in the future there is a new table where we want to be able to have deterministic IDs / use raw KVs to interact with it even if it isn't in the config range? If so, it'd be nice if there were still available constants left to assign, so I didn't see a reason to use the constants for tables that have exclusively normal SQL name resolution and interaction.

**Comment by bdarnell** [comment]
> Hm, I think there is a chance that at some point in the future there is a new table where we want to be able to have deterministic IDs / use raw KVs to interact with it even if it isn't in the config range? 

I suppose there's always a chance. But even when/if that occurs, will we know that at table creation time? One of the few dependencies we have on the table ID constants is actually in the default zone config we've been (ineffectively: #39605) setting on the jobs table since 2.0. Prior to the introduction of that zone config the jobs table was one of those sql-only tables that might have been given a non-reserved ID.

**Comment by dt** [comment]
Fair enough. I care more about the use of normal table creation of the descriptor and such than I do about the dynamic vs static ID allocation. My preference for not exhausting the available static IDs when it seems inevitable we'll switch to dynamic at some point anyway is a weak one.

**Comment by ajwerner** [comment]
fyi @spaskob

**Comment by amruss** [comment]
Closing this issue, we're planning on rewriting/working the jobs system during the 22.2 release cycle using lessons learned from this and similar problems that have popped up over the last few years
