### ISSUE TITLE
backup: build locality-specific RESTORE

### ISSUE THREAD

**Issue by rolandcrosby** [cockroachdb/cockroach#39602]
Followup issue to #17125. @lucy-zhang has built initial support for backup of table data to multiple storage locations based on the locality of the leaseholders of a table's ranges. We should now add functionality to RESTORE that enables the user to specify which localities each cloud storage URL should be restored to. Using no locality parameter in the cloud storage URL(s) should provide the 19.1 behavior (distributing the data arbitrarily across the cluster), while specifying a locality parameter in a URL should distribute the data from that URL across nodes/stores that match the specified locality constraint.

For 19.2, we are not going to explicitly back up or restore user-specified zone configurations applied to tables. @tyleroberts is currently working on a broader plan about how to back up and restore data that's not part of a table's schema/row data, so we will defer actual zone config backup and restore work until after that plan is finalized.

**Comment by pbardea** [comment]
I think that this basically works as described above. There remains an optimization that we could do in the case of full cluster that would minimize the rebalancing the restoring cluster would do, but I think that work should be tracked in #44990. Closing in favour of that issue.
