### ISSUE TITLE
Roachperf displaying old data for unstable clusters

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/cockroach#39628]
**Problem**
Roachperf is not displaying July and August data for unstable clusters

**To Reproduce**

Go to: https://roachperf.crdb.dev/?filter=&view=unstable+clusters&tab=stability

**Expected behavior**
Latest unstable cluster data shows.

**Additional data / screenshots**
![image](https://user-images.githubusercontent.com/1663752/62955150-969fc600-bdbe-11e9-9c19-9dc910a7300a.png)

**Environment:**
 - Client app: Chrome

**Additional context**
This is for the product council document.

**Comment by johnrk** [comment]
Hey @ajwerner , would you mind taking a look at this?

**Comment by ajwerner** [comment]
It seems like we're missing the raw data in s3:

```
$ aws s3 ls s3://cockroach-registration-metrics/stability/ | tail -n5                                                                                                                                    
2019-06-27 12:27:57      11499 2019-06-21
2019-06-27 12:28:42       8380 2019-06-22
2019-06-27 12:29:27       8129 2019-06-23
2019-06-27 12:30:13       8130 2019-06-24
2019-06-27 12:30:25         36 2019-06-25
```

@asubiotto do you know where that data comes from?

**Comment by ajwerner** [comment]
To close the loop on this, the data is generated manually by @BramGruneir by running against the reg cluster. There is something about waiting for an MSO registration cluster which is monitored before we automate running the query nightly.

**Comment by awoods187** [comment]
I know that is how we started but i thought we were pulling from the real reg cluster now--i guess we deem it too risky?

**Comment by BramGruneir** [comment]
Until we move the reg cluster to MSO, I was told to hold off.

If there is an available replica, I can run the script right now.

**Comment by awoods187** [comment]
Thanks for updating this @BramGruneir .
