### ISSUE TITLE
roachtest: acceptance/bank/node-restart flake

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#39632]
https://github.com/cockroachdb/cockroach/pull/39630#issuecomment-520920529

bank.go:387,bank.go:502,acceptance.go:69,test_runner.go:691: after 2.7s: pq: cannot transfer lease to replica of type LEARNER

looks like the test tries to manually run EXPERIMENTAL_RELOCATE, so I could see us getting this error from there

**Comment by tbg** [comment]
#41559
