### ISSUE TITLE
Continuous Fuzzing

### ISSUE THREAD

**Issue by yevgenypats** [cockroachdb/cockroach#39693]
Hi, I'm Yevgeny Pats Founder of [Fuzzit](https://fuzzit.dev) - Continuous fuzzing as a service platform.

We have a free plan for OSS and I would be happy to contribute a PR if that's interesting.
The PR will include the following
- [go-fuzz](https://github.com/dvyukov/go-fuzz) fuzzers
- Continuous Fuzzing of master branch which will generate new corpus and look for new crashes
- Regression on every PR that will run the fuzzers through all the generated corpus and fixed crashes from previous step. This will prevent new or old bugs from crippling into master.

You can see our basic example [here](https://github.com/fuzzitdev/example-go) and you can see an example of "in the wild" integration [here](https://github.com/google/syzkaller).

Let me know if this is something worth working on.

Also, we have a [reward](https://fuzzit.dev/2019/08/12/announcing-rewards-for-go-rust-oss-projects/) program. If you are interested in implementing the fuzzers and the integration yourself I’ll be happy to reward you as well as to get unbiased feedback on how smooth the integration was.

Cheers,
Yevgeny

**Comment by mjibson** [comment]
I am right now in the middle of a PR to start adding top-level fuzzing support to the whole codebase, so we can then start writing some fuzz functions. I have recently heard of your platform and will definitely be looking at it for this purpose. I think I'd like to try out fuzzit myself to see how the experience is and so we get some operational knowledge ourselves.

**Comment by yevgenypats** [comment]
sounds good. when you get to try our platform you can also join the [slack](https://slack.fuzzit.dev) and ask there any questions you have or other feature-request you have in mind.

**Comment by yevgenypats** [comment]
@mjibson let me know if you need a hand.

**Comment by mjibson** [comment]
I just pressed the button to merge our initial fuzzing support at #39702. I have to do some other stuff for a few days but then I'm going to come back to this and work on a thing that will hopefully magically register new Fuzz methods with fuzzit. That is, I want to be able to just write a new fuzz func anywhere in our codebase and something (nightly, on each PR, whatever) will register it with fuzzit. I don't want my fellow engineers here to have to know or care about our fuzzing infra beyond "just write a fuzz func".

**Comment by yevgenypats** [comment]
Sounds good, thanks for the detailed response. I think this would be totally possible with a small bash script and the Fuzzit CLI. I do think it will require adding this [flag](https://github.com/fuzzitdev/fuzzit/issues/25) to fuzzit so let me know once you get to it and I'll push this change to fuzzit CLI. If you think you need other change/feature for the "seamless fuzzing" you can ping me here or open an issue in our repo.
