### ISSUE TITLE
has_column_privilege() uses column index instead of attnum

### ISSUE THREAD

**Issue by jakob** [cockroachdb/cockroach#39703]
**Describe the problem**

It seems that CockroachDB interprets the second argument of `has_column_privilege(table, column, privilege)` as a column index instead of an attribute number. This is different from PostgreSQL.

Here is an excerpt from the [PostgreSQL docs for the function](https://www.postgresql.org/docs/current/functions-info.html):

> `has_column_privilege` checks whether a user can access a column in a particular way. Its argument possibilities are analogous to `has_table_privilege`, with the addition that the column can be specified **either by name or attribute number**. 

**To Reproduce**

```sql
drop table if exists hcp_test;

create table hcp_test(a int, b int, c int);

alter table hcp_test drop column b;

select attname, attnum from pg_attribute where attrelid = 'hcp_test'::regclass;
/*
 attname  | attnum
 ---------+-----
 a        | 1
 c        | 3
 rowid    | 4
*/


select has_column_privilege('hcp_test'::regclass, 1, 'SELECT'); 
/* TRUE */

select has_column_privilege('hcp_test'::regclass, 2, 'SELECT')
/* TRUE (I expect this to fail because there is no attnum 2) */

select has_column_privilege('hcp_test'::regclass, 3, 'SELECT');
/* TRUE */

select has_column_privilege('hcp_test'::regclass, 4, 'SELECT');
/* ERROR:  has_column_privilege(): column 4 of relation hcp_test does not exist */
```

**Environment:**
 - CCL v19.1.4 @ 2019/08/06 15:29:00 (go1.11.6)
 - macOS 10.14.6
 - Postico 

**Additional context**

This breaks compatibility with Postico. (I'm the developer of Postico)

PostgreSQL does not return an error when an invalid attnum is provided -- it just returns true. I think that the CockroachDB behavior of returning an error is better than PostgreSQL's behavior of ignoring errors, otherwise we probably wouldn't have discovered this issue.

**Comment by jordanlewis** [comment]
Thanks @jakob, this is indeed problematic.
