### ISSUE TITLE
Usability of core changefeeds

### ISSUE THREAD

**Issue by danielsonjh** [cockroachdb/cockroach#39727]
**Is your feature request related to a problem? Please describe.**
I love the idea of changefeeds, but the core changefeed feature currently seems like too much of a burden to integrate with.

So far the main problem I've encountered is that the streaming nature of the `EXPERIMENTAL CHANGEFEED FOR...` command does not appear to be compatible with JDBC. I did come across [this](https://stackoverflow.com/questions/57129234/consuming-cockroachdb-changefeed-via-jdbc) which suggests that this is being worked on in some form. For the time being, I've hacked together a workaround by embedding the cockroach binary in my app, and using the Java Process API to interact with it 🤢

**Describe the solution you'd like**
I understand the desire to separate enterprise and core CDC from a business perspective, but I don't think the two solutions need to have a different integration pattern. Ideally, the core CDC integration is the same as the enterprise CDC for the best developer experience, and ease of adoption.

Confluent has an interesting strategy which might be relevant here:
As of version 5.2 for [a single Kafka broker, enterprise features are free forever.](https://www.confluent.io/blog/introducing-confluent-platform-5-2) 😄 

I know this is a radical change, but would it be feasible to deprecate the core changefeed, and instead, change licensing rules around the enterprise changefeed to only require an enterprise license for crdb clusters with more than 1 node? The license check could even be `(cluster_size / replication_factor) == 1` since arguably one isn't getting the full benefits of crdb without horizontal scaling.

I tried putting together a list of cascading concerns in case it helps with discussing viability:
- What happens when the cluster size / replication factor changes to violate the new license rule?
- Should cluster size / replication factor be allowed to change when there is an active changefeed?
- If they are allowed to change, should active changefeeds stop immediately?
- How will the user be notified in a timely way if cluster / replication factor config changes stop active changefeeds? 

**Describe alternatives you've considered**
1. If the JDBC integration worked as expected, using the current core changefeed mechanism might not be as bad.
2. If using the cockroach binary is an acceptable solution (I hope not 😨), a `--format=json` with proper escaped values would be useful since parsing the changefeed console output with arbitrary column values is currently difficult. I can go into more detail if needed.

**Additional context**
This approach might be valuable for other enterprise features with multiple interfaces, such as backup & restore.
On the other hand, this approach may not make any sense for features like geo-partitioning.

**Comment by jordanlewis** [comment]
Hey @danielsonjh, thanks for the report!

As of #39639, I believe JDBC with core changefeeds should work, but nobody's tested it. Would you be so kind to try it out for us? You'd have to build from source on the master branch, let me know if you have trouble doing so.

**Comment by danielsonjh** [comment]
I just gave that a try using a Spring Boot app (v2.1.4) and it just hangs on `executeQuery`
In the following example `got result set` is never logged:

```java
var connection = jdbcTemplate.getDataSource().getConnection();
var statement = connection.createStatement();
statement.execute("SET CLUSTER SETTING kv.rangefeed.enabled = true;");
statement = connection.createStatement();
statement.setFetchSize(1);
log.info("fetching result set");
var resultSet = statement.executeQuery("EXPERIMENTAL CHANGEFEED FOR nodes, edges, idempotency_keys WITH updated;");
log.info("got result set");
while (resultSet.next()) {
	String table = resultSet.getString(0);
	log.info("table name: " + table);
}
```

On v19.1.3 I get the same behaviour.

**Comment by mjibson** [comment]
Support for `setFetchSize` is not yet in a publish release. It will be in our upcoming beta in a week or so. Also, it must be used with `conn.setAutoCommit(false)` (see https://jdbc.postgresql.org/documentation/head/query.html#query-with-cursor for examples). On our master branch, I can confirm that the following works as expected instead of hanging:

```
String url = "jdbc:postgresql://localhost:26257/defaultdb?ssl=false&user=root";
Connection conn = DriverManager.getConnection(url);

Statement st = conn.createStatement();
st.execute("SET CLUSTER SETTING kv.rangefeed.enabled = true;");
st.close();
conn.setAutoCommit(false);
st = conn.createStatement();
st.setFetchSize(1);
ResultSet rs = st.executeQuery("EXPERIMENTAL CHANGEFEED FOR t WITH updated, resolved;");
while (rs.next()) {
	System.out.println(rs.getString(1) + ", " + rs.getString(2) + ", " + rs.getString(3));
}
```

**Comment by danielsonjh** [comment]
I'm having trouble building the latest so I think I'll just wait for the beta release... :) Can you let me know which image that is when it's released?

**Comment by mjibson** [comment]
Our new beta is out finally: https://www.cockroachlabs.com/docs/releases/v19.2.0-beta.20190930.html

**Comment by danielsonjh** [comment]
Just gave it a try and it works as expected, thanks!
