### ISSUE TITLE
test failure: TestDockerCLI/test_log_config_msg.tcl  

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#39720]
Happened to me on CI here:
https://teamcity.cockroachdb.com/viewLog.html?buildId=1442417&buildTypeId=Cockroach_UnitTests

I guess this failure claims that the cluster ID was not printed in the logs... But I'm not sure how to check the get the logs...

```
TestDockerCLI/test_log_config_msg.tcl/runMode=docker

.190816 17:56:10.919356973 EXPECT TEST: BEGIN START SERVER
?column?
1

.190816 17:56:15.028047904 EXPECT TEST: START SERVER DONE

.190816 17:56:15.034128397 EXPECT TEST: BEGIN STOP SERVER
still waiting

.190816 17:56:16.380400178 EXPECT TEST: END STOP SERVER

.190816 17:56:16.386403861 EXPECT TEST: START TEST: Check that the cluster ID is reported at the start of the first log file.
child process exited abnormally
    while executing
"system "grep -qF '\[config\] clusterID:' logs/db/logs/cockroach.log""
    (file "/go/src/github.com/cockroachdb/cockroach/cli/interactive_tests/test_log_config_msg.tcl" line 12)
non-zero exit code: 1
        cli_test.go:88: non-zero exit code: 1
```

**Comment by knz** [comment]
@bobvawter somehow the TC config for acceptance test does not keep artifacts for TestDockerCLI. It used to (IIRC from my time debugging these tests in 2.1). How do you think I can investigate what changed?

**Comment by knz** [comment]
The build output is there but TC is being a bit obtuse about where it is.
The way I find this reliably:

1. click the test name
2. click "show build log" 
3. this brings up a page. ignore the build log itself, it's useless. Instead, click the "Artifacts" tab at the top
4. navigate to artifacts -> TestDockerCLI -> your test
5. look at the `console-output.log` and other log files.

I have no idea how to make this navigation easier, I wish that TC was showing the `acceptance` artifacts at the top level of the main screen.

**Comment by knz** [comment]
@irfansharif regarding this:

> Seems this is the current catch-all issue for TestDockerCLI.

No it's not. 
This present issue has the following symptom:
```
child process exited abnormally
    while executing
"system "grep -qF '\[config\] clusterID:' logs/db/logs/cockroach.log"
```

While your own from #40737 has symptom:
```
error when contacting licensing server: Get https://register.cockroachdb.com/api/license
```

They are different issues. Indeed yours is a dup of  #40734.
