### ISSUE TITLE
Support sql prepare for show statements

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#3972]
This is a followup to #3958 and #3819.
The jdbc driver generally talks to the database by means of prepare/bind/execute, *including for SHOW statements*. But at this moment this fails with cockroach with:

```
ERROR: sql/plan.go:161: prepare statement not supported: *parser.Show
```

**Comment by JackKrupansky** [comment]
Prepared statements are not currently even listed on the Beta/1.0 roadmap.

**Comment by mjibson** [comment]
We've already begun implementing prepared statements (https://github.com/cockroachdb/cockroach/pull/3482) and are attempting to complete them (https://github.com/cockroachdb/cockroach/pull/3958).

**Comment by mjibson** [comment]
Postgres doesn't appear to support prepared SHOW statements, so I'm inclined to not support this. Can you give me more details about the exact statement, and can you verify it works against a real postgres server?

**Comment by knz** [comment]
Ok I tested again and the SHOW statements goes through properly. Thanks.
