### ISSUE TITLE
sql: test date/timestamp expressions; prefer standard syntax to `::`

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#3973]
We support three ways to create date/time objects: `DATE '2016-01-01'`, `CAST('2016-01-01' AS DATE)`, and `'2016-01-01'::date`. The first two are standard, while the third is a postgres extension but is ubiquitous in our tests. The first form doesn't have any tests that I can see, so we should add some to `parser/eval_test.go`.  Additionally, we should prefer the standard forms to the `::` forms in our tests and especially our documentation.

**Comment by knz** [comment]
@nvanbenschoten I believe that's been done right?

**Comment by nvanbenschoten** [comment]
We've gotten better about using all forms of casts in logic tests in general, but for completeness of closing out this issue, I threw together #12754 to address Ben's point about `parser/eval_test.go`.
