### ISSUE TITLE
opt: consider the filters in the On conditions when collecting stats for Semi and Anti joins

### ISSUE THREAD

**Issue by ridwanmsharif** [cockroachdb/cockroach#39741]
Currently, we ignore the filters when we are building the stats for Semi and Anti Joins:
https://github.com/cockroachdb/cockroach/blob/4b3904dd14e023645e7e9191f7b48d0325a3e792/pkg/sql/opt/memo/statistics_builder.go#L834-L839

We should fix this since the `CommuteSemiJoin` exploration rule (https://github.com/cockroachdb/cockroach/pull/39411) creates an InnerJoin that doesn't suffer from the same issue and so that plan is chosen more aggressively.

**Comment by RaduBerinde** [comment]
@rytaft fixed this recently.
