### ISSUE TITLE
storage: use pebble sst builder to write ssts for snapshots

### ISSUE THREAD

**Issue by jeffrey-xiao** [cockroachdb/cockroach#39748]
We are already using pebble's sst builder to write ssts in bulk (#37528) and we can do the same for snapshots. There is some additional work to support incrementally writing ssts (I.E. truncating the sst after a certain size threshold) and range deletion tombstones.

**Comment by petermattis** [comment]
> There is some additional work to support incrementally writing ssts (I.E. truncating the sst after a certain size threshold) and range deletion tombstones.

Can you elaborate on this extra work? Is this additional functionality needed in the Pebble `sstable.Writer`, or something else?

**Comment by jeffrey-xiao** [comment]
I think the additional work is adding functionality to `pkg/storage/bulk/sst_writer.go`, but I'll look into it.

**Comment by ajwerner** [comment]
@itsbilal does https://github.com/cockroachdb/cockroach/pull/42252 fix this?

**Comment by itsbilal** [comment]
@ajwerner Yes, it does. Snapshots are written with the pebble writer now. Thanks for digging this up!
