### ISSUE TITLE
cli: incorrect read of node.key by `cockroach sql` upon startup

### ISSUE THREAD

**Issue by timaa2k** [cockroachdb/cockroach#39760]
**Describe the problem**

We found a regression from CockroachDB v2.0.7 to v2.1.8 in how the Cockroach SQL client handles a permission error on the `node.key` file if it is present in the specified `--certs-dir`.

We use a single `--certs-dir` directory with our CockroachDB v2.1.8 deployment which contains the `node.crt/key` as well as our `client.root.crt/key`.

The problem here is that, when using the `--certs-dir` flag with the CockroachDB v2.1.8 SQL client implementation the directory is scanned for any `.crt` files and corresponding `.key` files are being read despite not required for the client connection.

Our `client.root.crt/key` files are only readable by the SQL client Linux user while the `node.crt/key` files are only readable by a dedicated CockroachDB Linux user.

This leads to the following problem:
When we invoke the Cockroach SQL client with the aforementioned `--certs-dir` setup we see this error:
```
bash-4.2$ /opt/mesosphere/active/cockroach/bin/cockroach sql --host=172.17.0.2 --certs-dir=/run/dcos/pki/cockroach
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.
#
security/certificate_loader.go:334  error finding key for /run/dcos/pki/cockroach/node.crt: could not read key file /run/dcos/pki/cockroach/node.key: open /run/dcos/pki/cockroach/node.key: permission denied
Error: cannot load certificates.
Check your certificate settings, set --certs-dir, or use --insecure for insecure clusters.

problem using security settings: could not read key file /run/dcos/pki/cockroach/node.key: open /run/dcos/pki/cockroach/node.key: permission denied
Failed running "sql"
```

**To Reproduce**

The problem is easily reproduced and a workaround has been found copying the `--certs-dir` to another location while removing the `node.crt/key` files from it.

Good case scenario (non-fatal error) v2.0.7:
```
bash-4.2$ /opt/mesosphere/active/cockroach/bin/cockroach sql --certs-dir=/run/dcos/pki/cockroach --host=172.31.6.21
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.
#
W190820 10:17:51.605698 1 security/certificate_loader.go:251  error finding key for /run/dcos/pki/cockroach/node.crt: could not read key file /run/dcos/pki/cockroach/node.key: open /run/dcos/pki/cockroach/node.key: permission denied
# Server version: CockroachDB CCL v2.0.7 (x86_64-unknown-linux-gnu, built 2019/06/24 10:08:12, go1.11.5) (same version as client)
# Cluster ID: 22b02bfd-2475-41cb-ab75-301ba938949a
#
# Enter \? for a brief introduction.
#
warning: no current database set. Use SET database = <dbname> to change, CREATE DATABASE to make a new database.
root@172.31.6.21:26257/> 
```

Bad case scenario v2.1.8:
```
bash-4.2$ pwd
/run/dcos/pki/cockroach
bash-4.2$ ls -all
total 20
drwxr-xr-x. 2 root           root  140 Aug 19 15:55 .
drwxr-xr-x. 6 root           root  120 Aug 20 08:25 ..
-rw-r--r--. 1 root           root 1346 Aug 19 15:55 ca.crt
-rw-r--r--. 1 dcos_bouncer   root 1505 Aug 19 15:55 client.root.crt
-rw-------. 1 dcos_bouncer   root 1679 Aug 19 15:55 client.root.key
-rw-r--r--. 1 dcos_cockroach root 1505 Aug 19 15:55 node.crt
-rw-------. 1 dcos_cockroach root 1675 Aug 19 15:55 node.key
bash-4.2$ /opt/mesosphere/active/cockroach/bin/cockroach sql --host=172.17.0.2 --certs-dir=/run/dcos/pki/cockroach
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.
#
W190820 08:31:01.749018 1 security/certificate_loader.go:334  error finding key for /run/dcos/pki/cockroach/node.crt: could not read key file /run/dcos/pki/cockroach/node.key: open /run/dcos/pki/cockroach/node.key: permission denied
Error: cannot load certificates.
Check your certificate settings, set --certs-dir, or use --insecure for insecure clusters.

problem using security settings: could not read key file /run/dcos/pki/cockroach/node.key: open /run/dcos/pki/cockroach/node.key: permission denied
Failed running "sql"
```
Good case scenario v2.1.8:
```
bash-4.2$ pwd
/run/dcos/pki/test
bash-4.2$ ls -all
total 12
drwxr-xr-x. 2 root         root  100 Aug 20 08:26 .
drwxr-xr-x. 6 root         root  120 Aug 20 08:25 ..
-rw-r--r--. 1 root         root 1346 Aug 20 08:25 ca.crt
-rw-r--r--. 1 dcos_bouncer root 1505 Aug 20 08:25 client.root.crt
-rw-------. 1 dcos_bouncer root 1679 Aug 20 08:25 client.root.key
bash-4.2$ /opt/mesosphere/active/cockroach/bin/cockroach sql --host=172.17.0.2 --certs-dir=/run/dcos/pki/test
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.
#
# Server version: CockroachDB CCL v2.1.8 (x86_64-unknown-linux-gnu, built 2019/07/08 18:21:11, go1.10.7) (same version as client)
# Cluster ID: e6507834-0bc2-4cbf-9ddf-6e431dda91a7
#
# Enter \? for a brief introduction.
#
root@172.17.0.2:26257/defaultdb> 
```

**Expected behavior**
The expected behavior would have been that the Cockroach SQL client only reads the required `client.<user>.crt/key` in the given `--certs-dir` while ignoring any other `.crt/.key` files.

**Additional data / screenshots**
It appears as if the following piece of code causes this behavior:
https://github.com/cockroachdb/cockroach/blob/d554884a4e474cc06213230d5ba7d757a88e9e46/pkg/security/certificate_loader.go#L276
https://github.com/cockroachdb/cockroach/blob/d554884a4e474cc06213230d5ba7d757a88e9e46/pkg/security/certificate_loader.go#L333
Hence the code comment:
```
// Load examines all .crt files in the certs directory, determines their
// usage, and looks for their keys.
// It populates the certificates field.
```

**Environment:**
 - CockroachDB version: `CCL v2.1.8 (go1.10.7)`
 - Client app: `cockroach sql`

Jira issue: CRDB-5566

**Comment by dt** [comment]
@awoods187 BulkIO doesn't handle TLS config. I don't know who does... core?

**Comment by knz** [comment]
still current

**Comment by rafiss** [comment]
It seems like this issue would only occur if you use the same directory for the server certs and client certs. We recommend keeping those in different places (and in production setups, they likely would already be in different places anyway).

I will close this as not planned, but if you are still blocked, please leave a comment.
