### ISSUE TITLE
inequality operators can not use index 

### ISSUE THREAD

**Issue by qinzl1** [cockroachdb/cockroach#39761]
![image](https://user-images.githubusercontent.com/20242930/63343666-20343280-c381-11e9-8995-172e742fd134.png)
this about the index for column

![image](https://user-images.githubusercontent.com/20242930/63343728-44900f00-c381-11e9-8cd0-aa7f59112480.png)
why the inequality operators can not use the index(bp_ct)

![image](https://user-images.githubusercontent.com/20242930/63344198-735ab500-c382-11e9-8ede-2a102b9a6560.png)
equality operators can use the index

**Comment by mattcrdb** [comment]
Hi @qinzl1,

What version of CRDB are you running? 

If you could provide the full statements, that would be ideal so I can see what additional clauses you are adding to the query.

Depending on what version you are using, can you run `EXPLAIN (OPT, VERBOSE)` on your query and paste the outputs. Also depending on your version the cost-optimizer might choose a different path because its "faster". With that said you can provide a hint to your query to suggest it uses an index. See [this](https://www.cockroachlabs.com/docs/v19.1/table-expressions.html#force-index-selection).


Additionally, it doesn't seem like you are using the inequality operator. `!=` is what you're looking for.  

Matt

**Comment by qinzl1** [comment]
Hi ,@mattcrdb 
![image](https://user-images.githubusercontent.com/20242930/63399087-038c0f00-c402-11e9-9600-900d1ec7811b.png)

i fand that ,There is a field（bt_type） in the select statement ,It's not in index and it's not in storing too。when in where statement use  inequality operator(> or <) ,it will scan all primary not  scan by the second index

**Comment by mattcrdb** [comment]
Please run `EXPLAIN(OPT)` and paste output here for same queries above, ty.

**Comment by qinzl1** [comment]
equality operators:
  project                                                                                                    
   ├── columns: recode_type:18(string) dt:19(string!null) uv:15(int) num:17(int)                             
   ├── stats: [rows=9.5617925]                                                                               
   ├── cost: 53.3868538                                                                                      
   ├── key: (18)                                                                                             
   ├── fd: ()-->(19), (18)-->(15,17)                                                                         
   ├── prune: (15,17-19)                                                                                     
   ├── group-by                                                                                              
   │    ├── columns: count:15(int) count:17(int) column18:18(string)                                         
   │    ├── grouping columns: column18:18(string)                                                            
   │    ├── stats: [rows=9.5617925, distinct(18)=9.5617925]                                                  
   │    ├── cost: 53.1956179                                                                                 
   │    ├── key: (18)                                                                                        
   │    ├── fd: (18)-->(15,17)                                                                               
   │    ├── project                                                                                          
   │    │    ├── columns: column16:16(int!null) column18:18(string) bt_uid:8(int)                            
   │    │    ├── stats: [rows=10, distinct(18)=9.5617925]                                                    
   │    │    ├── cost: 52.7                                                                                  
   │    │    ├── fd: ()-->(16)                                                                               
   │    │    ├── prune: (8,16,18)                                                                            
   │    │    ├── interesting orderings: (+8)                                                                 
   │    │    ├── index-join b_bottle                                                                         
   │    │    │    ├── columns: bt_type:2(int) bt_uid:8(int) create_time:11(timestamptz!null)                 
   │    │    │    ├── stats: [rows=10, distinct(2)=9.5617925, distinct(11)=1]                                
   │    │    │    ├── cost: 52.4                                                                             
   │    │    │    ├── fd: ()-->(11)                                                                          
   │    │    │    ├── interesting orderings: (+8) (+11)                                                      
   │    │    │    └── scan b_bottle@bt_ct                                                                    
   │    │    │         ├── columns: bt_id:1(int!null) bt_uid:8(int) create_time:11(timestamptz!null)         
   │    │    │         ├── constraint: /11/1: [/'2019-08-20 00:00:00+00:00' - /'2019-08-20 00:00:00+00:00']  
   │    │    │         ├── stats: [rows=10, distinct(11)=1]                                                  
   │    │    │         ├── cost: 10.6                                                                        
   │    │    │         ├── key: (1)                                                                          
   │    │    │         └── fd: ()-->(11), (1)-->(8)                                                          
   │    │    └── projections [outer=(2,8)]                                                                   
   │    │         ├── const: 1 [type=int]                                                                    
   │    │         └── case [type=string, outer=(2)]                                                          
   │    │              ├── eq [type=bool, outer=(2)]                                                         
   │    │              │    ├── variable: bt_type [type=int, outer=(2)]                                      
   │    │              │    └── const: 1 [type=int]                                                          
   │    │              ├── when [type=string]                                                                
   │    │              │    ├── true [type=bool]                                                             
   │    │              │    └── const: e'D\U0000914D\U000065B9\U00005976' [type=string]                      
   │    │              └── const: e'C\U000074F6\U00005582\U00006BCD\U00004E73' [type=string]                 
   │    └── aggregations [outer=(8,16)]                                                                      
   │         ├── count [type=int, outer=(8)]                                                                 
   │         │    └── agg-distinct [type=int, outer=(8)]                                                     
   │         │         └── variable: bt_uid [type=int, outer=(8)]                                            
   │         └── count [type=int, outer=(16)]                                                                
   │              └── variable: column16 [type=int, outer=(16)]                                              
   └── projections [outer=(15,17,18)]                                                                        
        └── const: '2019-08-20' [type=string]         

inequality operators (<, >):
  project                                                                                                           
   ├── columns: recode_type:18(string) dt:19(string!null) uv:15(int) num:17(int)                                    
   ├── stats: [rows=98.265847]                                                                                      
   ├── cost: 1206.28131                                                                                             
   ├── key: (18)                                                                                                    
   ├── fd: ()-->(19), (18)-->(15,17)                                                                                
   ├── prune: (15,17-19)                                                                                            
   ├── group-by                                                                                                     
   │    ├── columns: count:15(int) count:17(int) column18:18(string)                                                
   │    ├── grouping columns: column18:18(string)                                                                   
   │    ├── stats: [rows=98.265847, distinct(18)=98.265847]                                                         
   │    ├── cost: 1204.31599                                                                                        
   │    ├── key: (18)                                                                                               
   │    ├── fd: (18)-->(15,17)                                                                                      
   │    ├── project                                                                                                 
   │    │    ├── columns: column16:16(int!null) column18:18(string) bt_uid:8(int)                                   
   │    │    ├── stats: [rows=333.333333, distinct(18)=98.265847]                                                   
   │    │    ├── cost: 1190                                                                                         
   │    │    ├── fd: ()-->(16)                                                                                      
   │    │    ├── prune: (8,16,18)                                                                                   
   │    │    ├── interesting orderings: (+8)                                                                        
   │    │    ├── select                                                                                             
   │    │    │    ├── columns: bt_type:2(int) bt_uid:8(int) create_time:11(timestamptz!null)                        
   │    │    │    ├── stats: [rows=333.333333, distinct(2)=98.265847]                                               
   │    │    │    ├── cost: 1180                                                                                    
   │    │    │    ├── interesting orderings: (+8) (+11)                                                             
   │    │    │    ├── scan b_bottle                                                                                 
   │    │    │    │    ├── columns: bt_type:2(int) bt_uid:8(int) create_time:11(timestamptz)                        
   │    │    │    │    ├── stats: [rows=1000, distinct(2)=100]                                                      
   │    │    │    │    ├── cost: 1170                                                                               
   │    │    │    │    ├── prune: (2,8,11)                                                                          
   │    │    │    │    └── interesting orderings: (+8) (+11)                                                        
   │    │    │    └── filters [type=bool, outer=(11), constraints=(/11: [/'2019-08-20 00:00:00+00:00' - ]; tight)]  
   │    │    │         └── ge [type=bool, outer=(11), constraints=(/11: [/'2019-08-20 00:00:00+00:00' - ]; tight)]  
   │    │    │              ├── variable: create_time [type=timestamptz, outer=(11)]                                
   │    │    │              └── const: '2019-08-20 00:00:00+00:00' [type=timestamptz]                               
   │    │    └── projections [outer=(2,8)]                                                                          
   │    │         ├── const: 1 [type=int]                                                                           
   │    │         └── case [type=string, outer=(2)]                                                                 
   │    │              ├── eq [type=bool, outer=(2)]                                                                
   │    │              │    ├── variable: bt_type [type=int, outer=(2)]                                             
   │    │              │    └── const: 1 [type=int]                                                                 
   │    │              ├── when [type=string]                                                                       
   │    │              │    ├── true [type=bool]                                                                    
   │    │              │    └── const: e'D\U0000914D\U000065B9\U00005976' [type=string]                             
   │    │              └── const: e'C\U000074F6\U00005582\U00006BCD\U00004E73' [type=string]                        
   │    └── aggregations [outer=(8,16)]                                                                             
   │         ├── count [type=int, outer=(8)]                                                                        
   │         │    └── agg-distinct [type=int, outer=(8)]                                                            
   │         │         └── variable: bt_uid [type=int, outer=(8)]                                                   
   │         └── count [type=int, outer=(16)]                                                                       
   │              └── variable: column16 [type=int, outer=(16)]                                                     
   └── projections [outer=(15,17,18)]                                                                               
        └── const: '2019-08-20' [type=string]

**Comment by mattcrdb** [comment]
Thanks for this.

As I mentioned earlier, in 19.1 you would be able to project the costs using the (opt, verbose) options and then see the cost of the same query while issuing the query with an index hint.

I suspect the optimizer is choosing the less expensive path. 

Let me know if you can upgrade.

**Comment by qinzl1** [comment]
tks.
At the moment, no upgrades are being considered
