### ISSUE TITLE
Randomized load generator

### ISSUE THREAD

**Issue by spencerkimball** [cockroachdb/cockroach#3976]
For long-running cluster load generation.

**Comment by vivekmenezes** [comment]
http://tsung.erlang-projects.org/

just saw this which seems to be a well supported open source option for load testing postgressql.

**Comment by spencerkimball** [comment]
# Proposed design for first version

## Schema
```
CREATE TABLE users (
    id INT PRIMARY KEY,
    photo_count INT,
    comment_count INT,
    name STRING,
    address STRING
);

CREATE TABLE photos (
    id EXPERIMENTAL_UUID_V4 PRIMARY KEY,
    user_id INT,
    comment_count INT,
    caption STRING,
    latitude FLOAT,
    longitude FLOAT,
    timestamp TIMESTAMP
);

CREATE UNIQUE INDEX photos_by_user_id ON photos (user_id);

CREATE TABLE comments (
    photo_id EXPERIMENTAL_UUID_V4 PRIMARY KEY,
    comment_id EXPERIMENTAL_UNIQUE_INT PRIMARY KEY,
    user_id INT,
    message STRING,
    timestamp TIMESTAMP
);
```

## Methodology

Using this simple schema, we generate load by simulating actions by users.

A client process carries out a series of user interactions,
possibly in parallel, according to an exponential distribution of
user IDs. User IDs are selected using `rand.ExpFloat64() /
rateParam`, where `rateParam = 1 / 2 * ExpNumUsers`. This
selection of User IDs will bias activity towards "earlier" user
IDs, making some data hot and away from "later" user IDs, making
some data likely to be written only once and then very rarely read.

Here is a summary of user actions:

### Create User

Called any time user lookup fails.

`INSERT INTO users VALUES (id, 0, name, address);`

### Create Photo

- Create user (if not already created)
- `INSERT INTO photos VALUES (DEFAULT, user.id, caption, lat, lon, NOW());`
- `UPDATE users SET photo_count = photo_count+1 WHERE id = user.id;`

### Create Comment (on the most recent photo)

- Create owner (if not already created)
- Create user (if not already created)
- `SELECT * FROM photos WHERE user_id=owner.id ORDER BY TIMESTAMP DESC LIMIT 1;
- If no photo exists, Create Photo
- `INSERT INTO comments VALUES (photo.id, DEFAULT, user.id, message, NOW());`
- `UPDATE photos SET comment_count = comment_count+1 WHERE id = photo.id;`
- `UPDATE users SET comment_count = comment_count+1 WHERE id=owner.id;`

### List Photos

- Generate user ID (for random selection)
- `SELECT * FROM users WHERE id < id ORDER BY id DESC LIMIT 1;`
- If no user, return empty
- `SELECT * FROM photos WHERE user_id = id SORT BY timestamp DESC  LIMIT 100;`

### List Comments

- List Photos
- Choose random photo from results
- `SELECT * FROM comments WHERE photo_id = photo.id SORT BY timestamp DESC LIMIT 100;`

### Update Photo

- List Photos
- Choose random photo from results
- `UPDATE photos SET caption = random_caption WHERE id = photo.id;`

### Update Comment

- List Comments
- Choose random comment from results
- `UPDATE comments SET message = random_message WHERE photo_id = comment.photo_id AND comment_id = comment.id;`

### Delete Photo

- List Photos
- Choose random photo from results
- `UPDATE users SET comment_count = comment_count - photo.comment_count WHERE id = photo.user_id;`
- `DELETE FROM comments WHERE photo_id = photo.id;`
- `DELETE FROM photos WHERE id = photo.id;`

### Delete Comment

- List Comments
- Choose random comment from results
- `UPDATE users SET comment_count = comment_count - 1 WHERE id = comment.user_id;`
- `UPDATE photos SET comment_count = comment_count - 1 WHERE id = comment.photo_id;`
- `DELETE FROM comments WHERE photo_id = comment.photo_id AND comment_id = comment.id;`

**Comment by dt** [comment]
fwiw, the `pgbench` tool produces randomized load across 4 tables, if we wanted to start with something off-the-shelf. it's schema: https://gist.github.com/dt/b69c79b16ba79428d853

**Comment by spencerkimball** [comment]
@dt what I'm looking to get out of this is something which looks like accumulated application load, not a performance benchmark.

**Comment by dt** [comment]
Yeah, fair enough. My thinking with `pgbench` was that it can be told to run continuously for, e.g. a week at some target QPS, but that doesn't give varied load like a real app would.
