### ISSUE TITLE
sql: Scan error on column index 1: unsupported Scan, storing driver.Value type []uint8 into type *[]string

### ISSUE THREAD

**Issue by cgebe** [cockroachdb/cockroach#39770]
**Describe the problem**

It is not possible to scan a TEXT ARRAY database column into a []string struct field.

**To Reproduce**

```
type Foo struct {
	Bars []string `json:"bars"`
}
```

```
CREATE TABLE IF NOT EXISTS foos (
  id BIGSERIAL NOT NULL,
  bars TEXT ARRAY NOT NULL,
  PRIMARY KEY (id)
);
```
```
...
for rows.Next() {
	var foo Foo
	if err := rows.Scan(&foo.Id, &foo.Bars); err != nil {
		return Foo{}, err
	}
	return foo, nil
}
```

**Expected behavior**
The TEXT Array field should be scanned into the []string slice.

**Additional data / screenshots**
Error:

```
sql: Scan error on column index 1: unsupported Scan, storing driver.Value type []uint8 into type *[]string
```

**Environment:**
 - CockroachDB version v19.1.3
 - Server OS: Debian
 - Client app: github.com/lib/pq 

**Additional context**
I suppose this error does not come from the driver, since i could not find any such issue in the `lib/pq` repo...

**Comment by jordanlewis** [comment]
I think this error comes from Go's `database/sql`. I'm not sure what the cause is, but I'm fairly sure that this isn't an issue with CockroachDB.

**Comment by cgebe** [comment]
@jordanlewis Thanks for the hint!
In fact the driver needs assistance with array types:

```
...
for rows.Next() {
	var foo Foo
	if err := rows.Scan(&foo.Id, pq.Array(&foo.Bars)); err != nil {
		return Foo{}, err
	}
	return foo, nil
}
```

**Comment by jordanlewis** [comment]
@cgebe no problem, glad you figured it out!

**Comment by dengsibao** [comment]
Bars pq.StringArray `json:"bars"`

**Comment by celesteking** [comment]
dengsibao  , you da man! That's exactly what was needed!

**Comment by hungdoansy** [comment]
> Bars pq.StringArray `json:"bars"`

Dang, spent hours without paying attention to this. Let me add a few more words

`Bars pq.StringArray json:"bars"`
=> Replace `[]string` with `pq.StringArray`

**Comment by th3coop** [comment]
Thank GOD for this ticket...I saw hours of debugging flash before my eyes when I saw this error in my tests...
