### ISSUE TITLE
Extreme performance degradation when using savepoints in transactions in select scenario

### ISSUE THREAD

**Issue by davidtemplin** [cockroachdb/cockroach#39774]
**Describe the problem**

I have developed a test for an application library which uses CockroachDB. The test runs in about 1 second when using transaction retries without savepoints, yet runs in about 45-60 seconds when using transaction retries with savepoints.

**To Reproduce**

I have developed a Go project directory which contains the test and will exhibit the problem. I am only able to reproduce the problem using this particular test which contains a small amount of proprietary code. I will send the directory privately to Andrew Deally at Cockroach Labs; please contact him to obtain it. The directory contains a `README.md` file with directions for reproducing the issue.

The test executes in one of two modes:

* savepoint - all transactions are retried when appropriate, and the https://github.com/cockroachdb/cockroach-go/tree/master/crdb library is used for retries in order to demonstrate that the problem is not necessarily limited to the library I typically use for retries
* non-savepoint - the test executes using the library that I typically use configured to use client-side retries without savepoints

The execution time in "savepoint" mode is about 45-60 seconds on my development machine, whereas the execution time is about 1 second in "non-savepoint" mode.

**Expected behavior**

The test should execute in roughly the same amount of time regardless of the mechanism used for transaction retries. However, the execution times differ by an extremely large factor.

**Environment:**

I am using Go 1.12.7, CRDB v19.1.3, macOS 10.14.4, and the `pq` driver version v1.2.0.

**Comment by mattcrdb** [comment]
Hello David,

Just wanted to update you that I've received the information from Andrew and will be looking into this.

**Comment by davidtemplin** [comment]
> Hello David,
> 
> Just wanted to give you an update that I've received the information from Andrew and will be looking into this.

Thanks, Matt!

**Comment by mattcrdb** [comment]
Hey David,

We are able to reproduce this issue in 19.1.3.

It seems there is no discrepancy in execution time in v2.1, v19.1.4 or the current master.

We are investigating the commit that fixed the issue and are looking into what may have caused this to happen.

If you upgrade your version of CRDB you should not run into this issue.

Thank you for bringing this to our attention!

Best,
Matt

**Comment by davidtemplin** [comment]
Thanks, Matt! I'll go ahead and upgrade. I really appreciate your prompt response!

**Comment by mattcrdb** [comment]
No problem at all.

Thank you for providing easy to follow steps to reproduce.

**Comment by nvanbenschoten** [comment]
The fix for this was https://github.com/cockroachdb/cockroach/commit/fe37b7631561fac1a1cc6a96d63afc19f9eb99de, which made it into v19.1.4. Without that change, we see severe client-side transaction retries. With it, the retries should be handled on the server.

**Comment by davidtemplin** [comment]
I have confirmed that the issue is no longer present in v19.1.4. I will go ahead and close the issue.
