### ISSUE TITLE
Improve cockroach demo nodes feature

### ISSUE THREAD

**Issue by rohany** [cockroachdb/cockroach#39780]
Right now, the cockroach demo takes in a --demo-locality argument which accepts a single locality tier for each node in the demo.

It would be better to allow for an arbitrary number of tiers to be assigned to each node, and to avoid abusing the parsing of the Locality flag, as brought up in comments on #39454.

A solution to do this is to use the syntax as follows, where colons separate the localities for each node.

```
./cockroach demo --nodes=3 --demo-localities=region=us-east1,az=1:region=us-east-1,az=2:region=us-east-1,az=3
```

**Comment by awoods187** [comment]
Thanks @andreimatei for point this out. Excited about demo getting more and more useful.
