### ISSUE TITLE
sql: parsing of negative constraints referencing attributes is broken

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#39801]
```
root@:26257/defaultdb> alter table t configure zone using constraints='["-x1"]';
pq: constraint "-x1" matches no existing nodes within the cluster - did you enter it correctly?
```
Yes computer, I've entered it correctly.

**Comment by rohany** [comment]
This makes sense, we shouldn't check that the current node has the constraint on a negative constraint input. I don't think this is a result of changes I made, but I'll fix this since I've been in that part of the code recently.

**Comment by rohany** [comment]
Does this not seem like intended behavior? This checks all the nodes in the cluster to see if at least 1 has this attribute. There should be an error if no nodes have the attribute you are forbidding, because that most likely means you mistyped an attribute that the nodes actually have.

**Comment by andreimatei** [comment]
I don't understand what's going on, but something's up.

```
./cockroach start --insecure --logtostderr --attrs=ssd:x1:x2:x3

root@:26257/defaultdb> alter table t configure zone using constraints='["-x5"]';
CONFIGURE ZONE 1

Time: 11.377ms

root@:26257/defaultdb> alter table t configure zone using constraints='["-x1"]';
pq: constraint "-x1" matches no existing nodes within the cluster - did you enter it correctly?
```

**Comment by rohany** [comment]
Ok, I found the cause of this -- the logic for validating these configs had a subtle flaw, and the tests for this behavior were passing due to luck i think. I'll put a fix out for this soon.
