### ISSUE TITLE
sql: validation of constraints referencing attributes is broken

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#39800]
```
root@:26257/defaultdb> alter table t configure zone using constraints='["+x1","+x2"]';
pq: incompatible zone constraints: "+x1" and "+x2"
```

There's nothing incompatible about those constraints. Based on some superficial debugging, I believe the problem is that we parse those constraints badly - we parse them as having an empty "key" and a populated "value". And then some validation code sees that there's two "conflicting" constraints using the same empty key.
Presumably this code was only tested with constraints referencing localities, not,

I find it very surprising that we'd want to populate the constraints' values and not their keys. Assuming this was always the case, I wonder if constraints referencing attributes work at all.

**Comment by andreimatei** [comment]
cc @solongordon

**Comment by andreimatei** [comment]
I guess the parsing into keys and values is as intended, since the Key has this comment:
```
// Key is only set if this is a constraint on locality.
```

**Comment by rohany** [comment]
To reproduce/test this, what is the syntax to give the node an attribute "+x1"? I'm only familiar with doing kv pairs.

**Comment by andreimatei** [comment]
Start your nodes with `--attrs=foo` and then `constraints='[+foo]'`
