### ISSUE TITLE
sql: "mixed success and failure" error while dropping database

### ISSUE THREAD

**Issue by glennfawcett** [cockroachdb/cockroach#39811]
**Describe the problem**

Trying to drop a database but it fails with:

```
root@:26257/defaultdb> drop database iri;
pq: job-insert: the batch experienced mixed success and failure: split failed while applying backpressure to [txn: 4533ba6d], ConditionalPut [/Table/15/1/479584715818696705/0,/Min), ConditionalPut [/Table/15/1/479584715818696705/1/1,/Min) on range r257:/Table/15/{1/479319152022552577-2/"failed"/2019-08-09T02:36:04.935676Z/475947876141170689} [(n1,s1):1, (n2,s2):2, (n3,s3):3, next=4, gen=4]: could not find valid split key
```

**To Reproduce**

1. Set up CockroachDB cluster 19.1.4
2. Create a database "mydb", run the script, then try to drop DB.

[cr_IRi_ddl.sql.gz](https://github.com/cockroachdb/cockroach/files/3527694/cr_IRi_ddl.sql.gz)

```
sql> create database iri;

$ cat cr_IRi_ddl.sql | cockroach sql --insecure -d iri

sql> drop database iri;
```

**Expected behavior**

I expect the DB to drop or at least there should be a *force* option to make it so.

**Environment:**
 - CockroachDB version 19.1.4
 - Server OS: OSx 10.14.6
 - Client app `cockroach sql`,

**Comment by jordanlewis** [comment]
Hi @glennfawcett, thanks for reporting this. I can't reproduce this on 20.1, so I'm going to declare it fixed. I don't think we'll be able to backport the fix unfortunately since we don't know what fixed it. :)
