### ISSUE TITLE
changefeedccl: support client certificates for kafka sink

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#39817]
We [currently support](https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/changefeedccl/sink.go#L318-L337) TLS connections with a CA certificate to verify broker identities.

However, we do not support client certificates for mutual auth. This is an alternative to SASL authentication.
Adding the client cert/key to the `tls.Config.Certificate` field should be sufficient. See [example](https://github.com/cockroachdb/cockroach/blob/master/pkg/security/tls.go#L155-L168) of this used by cockroach clients.

In single listener configurations (something that is not easily changed with some orchestrations), it is not possible to mix TLS client auth and SASL. This means that an existing kafka broker with TLS auth for other clients cannot be used by `CHANGEFEED` until we support client certificates.

CC: @rolandcrosby

**Comment by rolandcrosby** [comment]
Seems reasonably simple to build. I suppose we could sidestep certificate management headaches for now by base64-encoding the cert/key and passing them in the URL the way we do with the CA cert.
