### ISSUE TITLE
importccl: Inconsistent IMPORT CSV behavior related to quotation marks

### ISSUE THREAD

**Issue by rolandcrosby** [cockroachdb/cockroach#39820]
A forum user [had trouble](https://forum.cockroachlabs.com/t/incomplete-import/3039/) importing a TSV data set from IMDb - some lines in the input file containing quotation marks were being glued together. The user's specific issue can be reproduced in CockroachDB 19.2 as follows:

<details>

```
IMPORT TABLE title_basics (
	tconst STRING PRIMARY KEY,
	title_type STRING,
	primary_title STRING,
	original_title STRING,
	is_adult BOOL,
	start_year INT8,
	end_year INT8,
	runtime_minutes INT8,
	genres STRING
) CSV DATA ('https://datasets.imdbws.com/title.basics.tsv.gz')
WITH delimiter = e'\t', skip = '1', "nullif" = e'\\N';

select tconst, left(primary_title, 120) as left_of_primary_title from title_basics where tconst = 'tt0033122';
```

</details>

A more minimal reproduction shows that the issue arises when a column in a delimited file has a quoted string at the beginning of it:

```
col_a,col_b,col_c
1a,one b,one c
2a,"two b" is the string,two c
3a,three b,three c
4a,"four b",four c
5a,five "b",five c
6a,six b,six c
```

```
root@:26257/defaultdb> import table thing (a string primary key, b string, c string) csv data ('nodelocal:///thing.txt') with skip='1';
        job_id       |  status   | fraction_completed | rows | index_entries | system_records | bytes
+--------------------+-----------+--------------------+------+---------------+----------------+-------+
  479767674627817473 | succeeded |                  1 |    4 |             0 |              0 |   165
(1 row)

Time: 41.899ms

root@:26257/defaultdb> select * from thing;
  a  |             b              |   c
+----+----------------------------+--------+
  1a | one b                      | one c
  2a | two b" is the string,two c | four c
     | 3a,three b,three c         |
     | 4a,"four b                 |
  5a | five "b"                   | five c
  6a | six b                      | six c
(4 rows)

Time: 8.305ms
```

The input file here doesn't appear to treat double-quotes any differently than any other character. Our CSV parser has the following [requirements](https://www.cockroachlabs.com/docs/v19.1/migrate-from-csv.html#step-1-export-data-to-csv), which this file doesn't meet:

> If one of the following characters appears in a field, the field must be enclosed by double quotes:
> - delimiter (`,` by default)
> - double quote (`"`)
> - newline (`\n`)
> - carriage return (`\r`)
>
> If double quotes are used to enclose fields, then a double quote appearing inside a field must be escaped by preceding it with another double quote. For example: `"aaa","b""bb","ccc"`

Despite these requirements, we silently accept the input.

We could relax these requirements by adding a KV option to `IMPORT ... CSV` to allow the user to specify which character to use as the quote mark character (defaulting to `"`). Then, if the user specifies the empty string as the quote mark, we could suppress all logic around escaping. This would preclude the user from ever importing a column that contains the delimiter character, but for many import scenarios this is not a concern anyway.

**Comment by rolandcrosby** [comment]
Actually, in reading about the problem some more, I don't know that there's any value in allowing custom quote characters. The Go encoding/csv implementation is pretty specifically tailored to RFC 4180; [five years ago](https://github.com/golang/go/issues/8364#issuecomment-66096909), in response to other complaints about quote parsing issues, they said "Using encoding/csv to parse TSV doesn't really make sense". Maybe we just need to add a "dumber" delimited mode that splits at the delimiter, doesn't do any escaping, and doesn't treat quotes as special?

**Comment by rolandcrosby** [comment]
Per discussion with @spaskob, we're not going to offer custom quotation characters in this fix. Instead, we'll add a new `WITH verbatim` option that just splits on the specified delimiter character (defaulting to `,`) and preserves quotation marks exactly as they appeared in the input.

**Comment by spaskob** [comment]
Recap: the customer problem can be solved by using DELIMITED data import vs CSV:

```
IMPORT TABLE title_basics (
  tconst text primary key, title_type string, primary_title string, original_title string, is_adult int,
  start_year int, end_year int, runtime_minutes int, genres text
) DELIMITED DATA ('nodelocal:///title.basics.tsv') WITH fields_escaped_by ='\';

SELECT COUNT(*) FROM title_basics;
   count
+---------+
  6137393
```
