### ISSUE TITLE
observe High insert ( multivalue ) latency with oltpbenchmark

### ISSUE THREAD

**Issue by drewdeally** [cockroachdb/cockroach#39836]
During TPCC benchmark on 3 nodes Azure across 3 regions

@ https://github.com/timveil-cockroach/oltpbench

 java -jar oltpbench-2019.1-BETA.jar -b tpcc -c config/cockroachdb/cockroach_tpcc_config.xml --clear=true --create=true --load=true
[INFO] 2019-08-22 20:39:56,935 [main]  com.oltpbenchmark.DBWorkload main - ======================================================================

Benchmark:     TPCC {com.oltpbenchmark.benchmarks.tpcc.TPCCBenchmark}
Configuration: config/cockroachdb/cockroach_tpcc_config.xml
Type:          COCKROACHDB
Driver:        org.postgresql.Driver
URL:           jdbc:postgresql://localhost:26257/oltpb?ApplicationName=TPCC&reWriteBatchedInserts=true
Pool Size:     5
Isolation:     TRANSACTION_SERIALIZABLE
Scale Factor:  2.0

[INFO] 2019-08-22 20:39:56,936 [main]  com.oltpbenchmark.DBWorkload main - ======================================================================
[DEBUG] 2019-08-22 20:39:56,944 [main]  com.oltpbenchmark.DBWorkload main - Using the following transaction types: [com.oltpbenchmark.api.TransactionType$Invalid/00, com.oltpbenchmark.benchmarks.tpcc.procedures.NewOrder/01, com.oltpbenchmark.benchmarks.tpcc.procedures.Payment/02, com.oltpbenchmark.benchmarks.tpcc.procedures.OrderStatus/03, com.oltpbenchmark.benchmarks.tpcc.procedures.Delivery/04, com.oltpbenchmark.benchmarks.tpcc.procedures.StockLevel/05]
[DEBUG] 2019-08-22 20:39:56,945 [main]  com.oltpbenchmark.DBWorkload main - Num groupings: 0
[DEBUG] 2019-08-22 20:39:56,947 [main]  com.oltpbenchmark.DBWorkload isBooleanOptionSet - CommandLine has option 'create'. Checking whether set to true
[DEBUG] 2019-08-22 20:39:56,947 [main]  com.oltpbenchmark.DBWorkload isBooleanOptionSet - CommandLine create => true
[INFO] 2019-08-22 20:39:56,948 [main]  com.oltpbenchmark.DBWorkload main - Creating new TPCC database...
[DEBUG] 2019-08-22 20:39:56,948 [main]  com.oltpbenchmark.DBWorkload runCreator - Creating tpcc Database
[INFO] 2019-08-22 20:40:49,143 [main]  com.oltpbenchmark.DBWorkload main - Finished!
[INFO] 2019-08-22 20:40:49,144 [main]  com.oltpbenchmark.DBWorkload main - ======================================================================
[DEBUG] 2019-08-22 20:40:49,144 [main]  com.oltpbenchmark.DBWorkload isBooleanOptionSet - CommandLine has option 'clear'. Checking whether set to true
[DEBUG] 2019-08-22 20:40:49,144 [main]  com.oltpbenchmark.DBWorkload isBooleanOptionSet - CommandLine clear => true
[INFO] 2019-08-22 20:40:49,144 [main]  com.oltpbenchmark.DBWorkload main - Resetting TPCC database...
[INFO] 2019-08-22 20:40:50,810 [main]  com.oltpbenchmark.DBWorkload main - Finished!
[INFO] 2019-08-22 20:40:50,810 [main]  com.oltpbenchmark.DBWorkload main - ======================================================================
[DEBUG] 2019-08-22 20:40:50,810 [main]  com.oltpbenchmark.DBWorkload isBooleanOptionSet - CommandLine has option 'load'. Checking whether set to true
[DEBUG] 2019-08-22 20:40:50,812 [main]  com.oltpbenchmark.DBWorkload isBooleanOptionSet - CommandLine load => true
[INFO] 2019-08-22 20:40:50,812 [main]  com.oltpbenchmark.DBWorkload main - Loading data into TPCC database...
[DEBUG] 2019-08-22 20:40:50,812 [main]  com.oltpbenchmark.DBWorkload runLoader - Loading tpcc Database

Latency is high on inserts

![image](https://user-images.githubusercontent.com/39496073/63549111-c60cac00-c4fd-11e9-9698-173d7e586b33.png)

![image](https://user-images.githubusercontent.com/39496073/63549127-cd33ba00-c4fd-11e9-9dad-0205b85caa4d.png)

loading 2 warehouses with batched writes

HW does not seem to be issue

![image](https://user-images.githubusercontent.com/39496073/63549250-0cfaa180-c4fe-11e9-97d3-28876cfbe741.png)

![image](https://user-images.githubusercontent.com/39496073/63549267-14ba4600-c4fe-11e9-9c4d-840043906b45.png)

![image](https://user-images.githubusercontent.com/39496073/63549309-226fcb80-c4fe-11e9-9323-01464f72fc20.png)

Access to the cluster is open to drew and Matt Vardi

running a tpcc 2 or 100 warehouse load on the same cluster has minimal latency given the node latency map.

^C
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  997.1s        0           2117            2.1    794.3    838.9   1073.7   2281.7   5637.1  delivery
  997.1s        0          21039           21.1    557.7    503.3    838.9   1879.0   3623.9  newOrder
  997.1s        0           2123            2.1     62.3     67.1     92.3    142.6   1543.5  orderStatus
  997.1s        0          21239           21.3    402.2    369.1    637.5   1543.5   3758.1  payment
  997.1s        0           2101            2.1    105.0    100.7    176.2    385.9   1476.4  stockLevel

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__result
  997.1s        0          48619           48.8    458.9    402.7    872.4   1543.5   5637.1  
Audit check 9.2.1.7: SKIP: not enough delivery transactions to be statistically significant
Audit check 9.2.2.5.1: PASS
Audit check 9.2.2.5.2: PASS
Audit check 9.2.2.5.3: PASS
Audit check 9.2.2.5.4: PASS
Audit check 9.2.2.5.5: PASS
Audit check 9.2.2.5.6: SKIP: not enough order status transactions to be statistically significant

_elapsed_______tpmC____efc__avg(ms)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
  997.1s     1266.0  98.4%    557.7    503.3    771.8    838.9   1879.0   3623.9
[rahimim@n1 ~]$ 

100 warehouse 98.4%

cockroach workload can load 100 warehouse faster than oltpbenchmark warehouse =2  in this environment

**Comment by nvanbenschoten** [comment]
Thanks for the issue @drewdeally. I assume `workload` is able to load the tpcc dataset so much faster than this because it's not performing batches `INSERT` statements, it's using `IMPORT`. So they're not really comparable.

Here are a few suggestions for improving the performance when importing datasets using `INSERT` statements:
- Use `UPSERT` statements instead. This allows all writes to be blind.
- Don't add secondary indexes yet. Add them after importing the dataset.
- Definitely don't add foreign keys yet. Again, add them after importing the dataset. The `stock` table has two fks by default, and I assume that's where a lot of this latency is coming from.

Could you try those three things out and see if anything improves?

**Comment by drewdeally** [comment]
No this is not thew workload fixtures but cockroach workload init tpcc which is batched inserts

**Comment by lunevalex** [comment]
Closing due to age, TPCC performance has ben significantly improved over 19.1, not sure what to look at anymore.
