### ISSUE TITLE
Multi-Region Kubernetes For On-prem/Heterogeneous Environments

### ISSUE THREAD

**Issue by randmark** [cockroachdb/cockroach#39834]
When companies have multiple Kubernetes clusters in multiple regions on-prem, they would like to be able to join them together as regions to the cluster. The problem is that the Kubernetes containers get non-routable addresses which means the Cockroach Nodes don't have valid advertise addresses. 

CockroachDB doesn't have a design pattern to solve for this, although there are design patters for homogeneous environments such as GCP, AWS, etc.

Multiple companies run on-prem Kubernetes and need to be able to connect them together.

**Describe the solution you'd like**
Adjust the discovery to work with the public endpoints to be able to advertise routable advertise addresses for each node.

**Describe alternatives you've considered**
At this point, I discussed this with Bram, and wanted to capture the issue so that we can explore better solutions for it. A possible solution needs to be concepted and tested.

**Comment by nvanbenschoten** [comment]
Hi @randmark, have you read through https://www.cockroachlabs.com/docs/v19.1/orchestrate-cockroachdb-with-kubernetes-multi-cluster.html#main-content and https://www.cockroachlabs.com/blog/experience-report-running-across-multiple-kubernetes-clusters/?

I'm not too familiar with Kubernetes so there may be a subtlety in your question that I'm missing, but I think those might be able to answer your question.
