### ISSUE TITLE
cli: allow the user to customize the output format for command-line sql queries

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#3985]
Right now the interactive client pretty-prints results as tables with ASCII art, and -e emits results with simple tabs as separators.

To improve integration of the command-line clients it may be desirable to support multiple output formats, including e.g. JSON, CSV and XML/HTML, with proper quoting of string values.

(suggested by @tamird)

**Comment by spencerkimball** [comment]
@knz I recall you did some work on this? Has it been adequately addressed, or still an open issue? I'm removing the 1.0 milestone, but please prioritize this / assign it as necessary.

**Comment by knz** [comment]
Indeed, this was fixed in #13171.
