### ISSUE TITLE
demo: silence error and warning logs

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#39939]
Currently, error and I think warning logs make it to `stdout` in `cockroach demo`. There's really no need to do this - let's get rid of the behavior, as it looks gross and concerning if it happens to a user.

**Comment by knz** [comment]
Can you provide some example messages which you think are unnecessarily alarming. 

The truth is that if you think they are alarming in a terminal  they will be equally alarming in a log file viewer. The proper course of action may be to review the severity of the particular messages you have in mind.
