### ISSUE TITLE
Failed tests automation is broken (11918)

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#3994]
The following test appears to have failed:

[#11918](https://circleci.com/gh/cockroachdb/cockroach/11918):

```

```
Please assign, take a look and update the issue accordingly.

**Comment by tamird** [comment]
Hm, seems the recent build parallelism has messed with this automation. Node 2 posted this for no apparent reason.

**Comment by petermattis** [comment]
@tschottdorf Is this still broken? I've seen recent emails from CircleCI failures that look correct.

**Comment by tschottdorf** [comment]
I never looked into this, might've been a fluke. Seems safe to close and if it does reappear, we'll see it.
