### ISSUE TITLE
sql: create SHOW WEBUI command

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#39942]
Oftentimes I am in the SQL shell and realize that I would like to see the webui for different reasons such as debugging, checking performance, etc. It'd be great to have a command that shows the webui url so that I could go to the webui without having to leave the sql shell and go to the cli. It could also be returned on a per-node basis, so if I'm in the SQL shell on node 3 then I'd get the corresponding webui for that node. 

Strawman proposal:

SHOW WEBUI;
Web UI: http://XXX.X.X.X:XXXXX

This would also be beneficial in the context of Cockroach Demo if you didn't notice it when first accessing the SQL shell.

**Comment by knz** [comment]
A solution for this already exists:

```sql
select value 
  from crdb_internal.node_runtime_info 
 where component='UI' 
   and field='URL';
```

**Comment by rohany** [comment]
If this already exists, so we want this feature then Andy? It is slightly verbose to do this, so maybe an alias would be nice?

**Comment by bdarnell** [comment]
#39483 is a CLI version of this. We should use the same name in both places, whether it's `dashboard`, `webui` or `adminui`. 

And my comments on that issue still stand: on k8s, which is our most popular deployment platform, the resulting link is unlikely to actually work, and I don't think we should introduce convenience accessors for the web UI until we can make them work with our published k8s templates.

**Comment by awoods187** [comment]
I think there is an advantage for an easily remembered and understood command. I also agree with @bdarnell that we should align on the same name in the CLI and WebUI. I'm fine with any of the options. Perhaps @piyush-singh has thoughts on what this will be called longterm? I'm personally a fan of webui since adminui can be many things and dashboard sounds generic. But i'll defer to the team on what they like best.

**Comment by rohany** [comment]
On this topic, is there a way to look up a particular nodes admin url? For example, if I make a multi node demo cluster, I'm connected to one of its nodes. Is there a way to open the admin UI on a different node?

**Comment by awoods187** [comment]
I don't think so--I think you need to be on that node to get the webui or get it elsewhere.

**Comment by jordanlewis** [comment]
All of the nodes have exposed admin UI's - we just don't print them. Check out `setupTransientServers` - it just returns the admin url of the first server. We could change that if we wanted.

**Comment by rohany** [comment]
Hmm, I'll take a look at that. I'm looking at how can we show off the effects of geo-partitioning in demo without spoofing latencies between nodes.

**Comment by jordanlewis** [comment]
I'm not giving up on the latency spoofing thing! I honestly think it will be pretty easy. Let me whip up a patch idea.

**Comment by jordanlewis** [comment]
Okay, here's the patch. It doesn't seem to work yet, but I think something like this could be the right approach.

```
diff --git a/pkg/cli/demo.go b/pkg/cli/demo.go
index b35619a226..565ad2786f 100644
--- a/pkg/cli/demo.go
+++ b/pkg/cli/demo.go
@@ -20,6 +20,7 @@ import (
 	"github.com/cockroachdb/cockroach/pkg/base"
 	"github.com/cockroachdb/cockroach/pkg/cli/cliflags"
 	"github.com/cockroachdb/cockroach/pkg/roachpb"
+	"github.com/cockroachdb/cockroach/pkg/rpc"
 	"github.com/cockroachdb/cockroach/pkg/security"
 	"github.com/cockroachdb/cockroach/pkg/server"
 	"github.com/cockroachdb/cockroach/pkg/sql/sqlbase"
@@ -148,6 +149,11 @@ func setupTransientServers(
 		PartOfCluster: true,
 		Insecure:      true,
 		Stopper:       stopper,
+		Knobs: base.TestingKnobs{
+			Server: &server.TestingKnobs{
+				ContextTestingKnobs: rpc.ContextTestingKnobs{ArtificialLatencyMS: 100},
+			},
+		},
 	}
 
 	serverFactory := server.TestServerFactory
diff --git a/pkg/rpc/context.go b/pkg/rpc/context.go
index 48e3499b28..f5b00f6479 100644
--- a/pkg/rpc/context.go
+++ b/pkg/rpc/context.go
@@ -706,13 +706,29 @@ func (ctx *Context) grpcDialOptions(
 			unaryInterceptors = append(unaryInterceptors, testingUnaryInterceptor)
 		}
 	}
-	dialOpts = append(dialOpts, grpc.WithChainUnaryInterceptor(unaryInterceptors...))
 	if ctx.testingKnobs.StreamClientInterceptor != nil {
 		testingStreamInterceptor := ctx.testingKnobs.StreamClientInterceptor(target, class)
 		if testingStreamInterceptor != nil {
 			dialOpts = append(dialOpts, grpc.WithStreamInterceptor(testingStreamInterceptor))
 		}
 	}
+	if artificialLatency := int64(ctx.testingKnobs.ArtificialLatencyMS); artificialLatency != 0 {
+		fmt.Println("AHOY THERE")
+		unaryInterceptors = append(unaryInterceptors, func(ctx context.Context, method string, req, reply interface{},
+			cc *grpc.ClientConn, invoker grpc.UnaryInvoker, opts ...grpc.CallOption) error {
+			fmt.Println("sleeping unary")
+			time.Sleep(time.Duration(artificialLatency) * time.Millisecond)
+			return invoker(ctx, method, req, reply, cc, opts...)
+		})
+		dialOpts = append(dialOpts, grpc.WithStreamInterceptor(func(ctx context.Context, desc *grpc.StreamDesc,
+			cc *grpc.ClientConn, method string, streamer grpc.Streamer, opts ...grpc.CallOption) (grpc.ClientStream,
+			error) {
+			fmt.Println("sleeping sstream")
+			time.Sleep(time.Duration(artificialLatency) * time.Millisecond)
+			return streamer(ctx, desc, cc, method, opts...)
+		}))
+	}
+	dialOpts = append(dialOpts, grpc.WithChainUnaryInterceptor(unaryInterceptors...))
 	return dialOpts, nil
 }
 
diff --git a/pkg/rpc/context_testutils.go b/pkg/rpc/context_testutils.go
index 46db6de1bd..261092a01e 100644
--- a/pkg/rpc/context_testutils.go
+++ b/pkg/rpc/context_testutils.go
@@ -38,6 +38,8 @@ type ContextTestingKnobs struct {
 	// for a given target and class.
 	StreamClientInterceptor func(target string, class ConnectionClass) grpc.StreamClientInterceptor
 
+	ArtificialLatencyMS int
+
 	// ClusterID initializes the Context's ClusterID container to this value if
 	// non-nil at construction time.
 	ClusterID *uuid.UUID
diff --git a/pkg/server/server.go b/pkg/server/server.go
index 206d58e71e..dee96690ea 100644
--- a/pkg/server/server.go
+++ b/pkg/server/server.go
@@ -250,8 +250,16 @@ func NewServer(cfg Config, stopper *stop.Stopper) (*Server, error) {
 	// and after ValidateAddrs().
 	s.cfg.CheckCertificateAddrs(ctx)
 
-	s.rpcContext = rpc.NewContext(s.cfg.AmbientCtx, s.cfg.Config, s.clock, s.stopper,
-		&cfg.Settings.Version)
+	if knobs := s.cfg.TestingKnobs.Server; knobs != nil {
+		serverKnobs := knobs.(*TestingKnobs)
+		s.rpcContext = rpc.NewContextWithTestingKnobs(
+			s.cfg.AmbientCtx, s.cfg.Config, s.clock, s.stopper, &cfg.Settings.Version,
+			serverKnobs.ContextTestingKnobs,
+		)
+	} else {
+		s.rpcContext = rpc.NewContext(s.cfg.AmbientCtx, s.cfg.Config, s.clock, s.stopper,
+			&cfg.Settings.Version)
+	}
 	s.rpcContext.HeartbeatCB = func() {
 		if err := s.rpcContext.RemoteClocks.VerifyClockOffset(ctx); err != nil {
 			log.Fatal(ctx, err)
diff --git a/pkg/server/server_update.go b/pkg/server/server_update.go
index cf3fd94305..2388b79bc6 100644
--- a/pkg/server/server_update.go
+++ b/pkg/server/server_update.go
@@ -16,6 +16,7 @@ import (
 	"time"
 
 	"github.com/cockroachdb/cockroach/pkg/config"
+	"github.com/cockroachdb/cockroach/pkg/rpc"
 	"github.com/cockroachdb/cockroach/pkg/sql/sem/tree"
 	"github.com/cockroachdb/cockroach/pkg/storage/storagepb"
 	"github.com/cockroachdb/cockroach/pkg/util/log"
@@ -32,6 +33,8 @@ type TestingKnobs struct {
 	DefaultZoneConfigOverride *config.ZoneConfig
 	// DefaultSystemZoneConfigOverride, if set, overrides the default system zone config defined in `pkg/config/zone.go`
 	DefaultSystemZoneConfigOverride *config.ZoneConfig
+
+	ContextTestingKnobs rpc.ContextTestingKnobs
 }
 
 // ModuleTestingKnobs is part of the base.ModuleTestingKnobs interface.
```

I'm guessing the problem is that RPCs in between test cluster nodes go through a slightly different interface, but I'm not sure. @andreimatei do you know?

**Comment by rohany** [comment]
ok this is alot of code i never knew existed. Maybe we can get something to work here.

**Comment by bdarnell** [comment]
> On this topic, is there a way to look up a particular nodes admin url? For example, if I make a multi node demo cluster, I'm connected to one of its nodes. Is there a way to open the admin UI on a different node?

In general, we should aim to make all the nodes equivalent for admin UI purposes (remember that many deployments such as MSO will only have one node exposed). Instead of exposing multiple admin UI endpoints, we should make sure that other nodes' data is accessible no matter which node you're accessing.

**Comment by knz** [comment]
This is now possible via the `\demo ls` command.
