### ISSUE TITLE
demo: add flags for each of the topology patterns that start them by default in Cockroach Demo

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#39945]
Let's add flags to cockroach demo that correspond to each of the [topology patterns](https://www.cockroachlabs.com/docs/v19.1/topology-patterns.html).

Something like:

--Geo-partitioned-replicas
--Geo-partitioned-leaseholders
--Duplicate-indexes
--Follower-reads
--Follow-the-workload

Then you start Cockroach Demo with a command like this:
./cockroach demo --nodes 3 --geo-partitioned-replicas

And it's perfectly set up to work with load running by default. So this would include enterprise license and organization, localities, webui node map, partitioned tables, all with load directly running and visible in the webui.

**Comment by awoods187** [comment]
https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/165544052/Topology+Pattern+Tutorials

As discussed offline, let's just try this out with partitioning before expanding further.

**Comment by asubiotto** [comment]
Closing because I'm pretty sure this has been implemented. @rohany feel free to reopen if I'm wrong.
