### ISSUE TITLE
sql: add hardcoded map information to Cockroach Demo for standard multi-regions

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#39941]
For use both in https://github.com/cockroachdb/cockroach/issues/39938 and in other kinds of testing. We can set out a list of "known" locations with hardcoded lats/longs so that the webui map works.

In addition to the ones in #39938, I think we should add asia information as well.

If i user sets something like: 
`./cockroach demo movr --nodes 3 --demo-locality=region=us-east1,region=us-central1,region=us-west1`

Then we would hard code recognize us-east1 as a specific lat/long and insert it into the MovR database to enable the webui

**Comment by jordanlewis** [comment]
I actually just filed this as #39937 - sorry 😱

**Comment by awoods187** [comment]
cool will close this

**Comment by jordanlewis** [comment]
In other words, I don't think there's any reason to make this specific to the demo - I think hardcoded system.locations for all of the known region codes is a great idea for testing and prod. Right?
