### ISSUE TITLE
sql: Inconsistent num_replicas requirement when defining per-replica constraints

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#39994]
When you set a per-replica constraint on a database or table, CockroachDB requires you to also specify `num_replicas`. However, we you set a per-replica constraint on an index or partition, you don't run into this requirement. This is strange UX, and it's confusing to explain in the docs (we don't, currently). 

IMO, we shouldn't require `num_replicas` explicitly, since this variable is generally inherited, but we should check that the per-replica constraints don't add up to more than `num_replicas`. 

Chatted with @andreimatei and @irfansharif about this on Slack, so they might chime in here with other insights and ideas. 

Steps to reproduce:

1. Spin up a 3-node in-memory cluster:

```
~$ cockroach demo movr --nodes=3 --demo-locality=region=us-east1,region=us-central1,region=us-west1
#
# Welcome to the CockroachDB demo database!
#
# You are connected to a temporary, in-memory CockroachDB cluster of 3 nodes.
# The cluster has been preloaded with the "movr" dataset
# (MovR is a fictional ride sharing company).
#
# Your changes will not be saved!
#
# Web UI: http://127.0.0.1:51229
#
# Server version: CockroachDB CCL v19.2.0-alpha.20190606-1660-g3f1fcb37e1 (x86_64-apple-darwin17.7.0, built 2019/08/21 14:53:11, go1.12.6) (same version as client)
# Cluster ID: 3ef01c9d-7670-4474-8991-a06ff1f90370
#
# Enter \? for a brief introduction.
#
```
2. Apply an enterprise license:
```
root@127.0.0.1:51231/movr> SET CLUSTER SETTING cluster.organization = 'Cockroach Labs - Production Testing'; SET CLUSTER SETTING enterprise.license = 'XXXXX';
SET CLUSTER SETTING

Time: 19.334ms
```
3. Look at the `movr` tables:
```
root@127.0.0.1:51231/movr> show tables;
          table_name
+----------------------------+
  promo_codes
  rides
  user_promo_codes
  users
  vehicle_location_histories
  vehicles
(6 rows)

Time: 5.462ms
```
4. Create 2 secondary indexes on `promo_codes`:
```
root@127.0.0.1:51231/movr> CREATE INDEX promo_codes_idx_east ON promo_codes (code) STORING (description, creation_time, expiration_time, rules); CREATE INDEX promo_codes_idx_west ON promo_codes (code) STORING (description, creation_time, expiration_time, rules);

CREATE INDEX

Time: 402.639ms
```
5. Apply per-replica constraint to the primary index. Errors if you don't specify `num_replicas`:
```
root@127.0.0.1:51231/movr> ALTER TABLE promo_codes CONFIGURE ZONE USING constraints = '{"+region=us-central1": 1}', lease_preferences = '[[+region=us-central1]]';
pq: could not validate zone config: when per-replica constraints are set, num_replicas must be set as well
HINT: try ALTER ... CONFIGURE ZONE USING <field_name> = COPY FROM PARENT [, ...] to populate the field
root@127.0.0.1:51231/movr> ALTER TABLE promo_codes CONFIGURE ZONE USING num_replicas = 3, constraints = '{"+region=us-central1": 1}', lease_preferences = '[[+region=us-central1]]';
CONFIGURE ZONE 1

Time: 14.815ms
```
6. Apply per-replica constraint to the secondary indexes. No error if you don't specify `num_replicas`:
```
root@127.0.0.1:51231/movr> ALTER INDEX promo_codes@promo_codes_idx_east CONFIGURE ZONE USING constraints = '{"+region=us-east1": 1}', lease_preferences = '[[+region=us-east1]]'; ALTER INDEX promo_codes@promo_codes_idx_west CONFIGURE ZONE USING constraints = '{"+region=us-west1": 1}', lease_preferences = '[[+region=us-west1]]';
CONFIGURE ZONE 1

Time: 41.902ms
```
7. Partition the `users` table:
```
root@127.0.0.1:51231/movr> ALTER TABLE users PARTITION BY LIST (city) ( PARTITION new_york VALUES IN ('new york'), PARTITION chicago VALUES IN ('chicago'), PARTITION seattle VALUES IN ('seattle') );
ALTER TABLE

Time: 48.734ms
```
8. Apply per-replica constraint to the `new york` partition of `users`. No error if you don't specify `num_replicas`:

```
root@127.0.0.1:51231/movr> ALTER PARTITION new_york OF TABLE movr.users CONFIGURE ZONE USING constraints='{"+region=us-east1":1}', lease_preferences='[[+region=us-east1]]';
CONFIGURE ZONE 1

Time: 15.009ms
```

**Comment by ridwanmsharif** [comment]
This is certainly a bug.
<img width="575" alt="image" src="https://user-images.githubusercontent.com/18472685/63612423-3a9e2400-c5ac-11e9-9646-6759af69bfcd.png">

I tried setting just the `range_max_bytes` for the secondary index zone and it succeeded (it should've errored while validating it). If I change the parent's `range_min_bytes` to be greater than the `range_max_bytes` I set earlier, I notice that the index zone is just invalid (its min bytes is greater than its max).

**Comment by ridwanmsharif** [comment]
I see what's happening here:
https://github.com/cockroachdb/cockroach/blob/4c3053c8a0ad77e4a7c8e065d2695ad9a2b54c99/pkg/sql/set_zone_config.go#L467-L475

We're running `ValidateTandemFields` on the zone we're writing but not the subzones within them. From what I am seeing an index zone is a subzone inside a table zone config (even if a table doesn't have an explicitly created zone config - looks like there is a placeholder zone config in this case). I don't remember the structure exactly but I think just applying the `ValidateTandemFields` to all subzones  of the `zoneToWrite` should fix this? I haven't looked at this in a while.

cc @andreimatei because he's the only person I know who's touching this area.

**Comment by awoods187** [comment]
@andreimatei do you have any thoughts on the fix here? Or know where it should be passed to?

**Comment by rohany** [comment]
I can take this over, I've been touching code in this area recently.
