### ISSUE TITLE
http: graceful shutdown of server

### ISSUE THREAD

**Issue by andybons** [cockroachdb/cockroach#40]
From: https://code.google.com/p/go/issues/detail?id=4674:

> Status update: Go 1.3 will have all the necessary net/http changes (Server.ConnState and
> Server.SetKeepAlivesEnabled) for other people to implement graceful shutdown properly,
> outside the net/http package.

Go 1.3 is out and we are compiling against it. We should shut down the servers gracefully.

Take a look at `func (s *server) stop()` in server/server.go

**Comment by spencerkimball** [comment]
Closed by #636
