### ISSUE TITLE
sql: add support for hexadecimal literals

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#4017]
After switching to the postgres driver, I had to comment out the `Example_zone` in `cli/cli_test.go` (see: https://github.com/cockroachdb/cockroach/pull/3757/files#diff-7d7fb132e111ef7398af7150b1d54a32 L480-L535.

The actual statement being run is (from `cli/zone.go`, removing boilerplate error handling and other stuff):
```
  buf, err := proto.Marshal(&pbZoneConfig)
  // TODO(marc): switch to placeholders when they're fixed with pgwire.
  err = runPrettyQuery(db, os.Stdout,
    fmt.Sprintf(`INSERT INTO system.zones VALUES (%d, '%s'::bytes)`, id, string(buf)))
```

This now fails because the string version of `buf` contains a newline, so we get the error:
```
Query with %s: INSERT INTO system.zones VALUES (100, '


us-east-1a
ssd


us-east-1b
ssd


us-west-1b
ssd������ "'::bytes)
Query with %q: "INSERT INTO system.zones VALUES (100, '\n\x11\n\nus-east-1a\n\x03ssd\n\x11\n\nus-east-1b\n\x03ssd\n\x11\n\nus-west-1b\n\x03ssd\x10\x80\x80\x80\x04\x18\x80\x80\x80 \"\x02\b\x00'::bytes)"
E0128 15:35:10.743505 21079 cli/zone.go:239  statement error: pq: unterminated string
INSERT INTO system.zones VALUES (100, '
                                      ^
```

The long-term solution for this particular bit of code is to switch to placeholders. But for now, this should work as well. I tried switching to:
```
 err = runPrettyQuery(db, os.Stdout,
    fmt.Sprintf(`SET syntax = modern; INSERT INTO system.zones VALUES (%d, '''%s'''::bytes)`, id, string(buf)))
```

Which fails with:
```
Query with %s: SET syntax=modern; INSERT INTO system.zones VALUES (100, '''


us-east-1a
ssd


us-east-1b
ssd


us-west-1b
ssd������ "'''::bytes)
Query with %q: "SET syntax=modern; INSERT INTO system.zones VALUES (100, '''\n\x11\n\nus-east-1a\n\x03ssd\n\x11\n\nus-east-1b\n\x03ssd\n\x11\n\nus-west-1b\n\x03ssd\x10\x80\x80\x80\x04\x18\x80\x80\x80 \"\x02\b\x00'''::bytes)"
E0128 15:36:40.896367 21274 cli/zone.go:239  statement error: pq: unterminated string
SET syntax=modern; INSERT INTO system.zones VALUES (100, '''
                                                         ^

```

**Comment by petermattis** [comment]
In "modern" syntax, the string quote character is `"`, not `'`.

**Comment by bdarnell** [comment]
Can't the encoded protobuf contain more than just `\n`, including things like `'` to break out of the string literal? I thing you're going to have to encode the string somehow (base64 or hex) to be able to put the string directly in the query. I think we have some special syntax for hex-encoded byte literals.

**Comment by JackKrupansky** [comment]
Ah... the perils of using modern syntax when working with a Postgres interface. (Triple single quotes for a string containing newlines.)

One option would be to add support for PG dollar-quoted string constants, which do allow newlines and unescaped quotes as well:

INSERT INTO system.zones VALUES (100, $$\n\x11\n\nus-east-1a\n\x03ssd\n\x11\n\nus-east-1b\n\x03ssd\n\x11\n\nus-west-1b\n\x03ssd\x10\x80\x80\x80\x04\x18\x80\x80\x80 \"\x02\b\x00$$

(assuming all of those escapes are replaced with the actual raw character codes.)

Or,

**Comment by petermattis** [comment]
It's not special syntax. With the "traditional" syntax you can use an escaped string. Something like:

```
peters-imac.local:26257> select e'\x68\x65\x6c\x6c\x6f';
+---------+
| 'hello' |
+---------+
| hello   |
+---------+
```

**Comment by bdarnell** [comment]
I was thinking of mysql's `X` literals (https://dev.mysql.com/doc/refman/5.7/en/hexadecimal-literals.html)

**Comment by petermattis** [comment]
Yeah, we don't support that (yet).

**Comment by knz** [comment]
Wait this is only in the test suite right?
I have been using strings containing newlines from the CLI client for a while now without problems.
