### ISSUE TITLE
cli: refactor sql logic in cli

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#4018]
Just a few of many things to fix:
* saner handling of pgurl building (eg: query escape everything, use net.JoinHostPort, etc...) and share it with PGUrl testing function
* remove the spaghetti mess that is runQuery* functions
* cleaner sharing with cli/user and cli/zone.

**Comment by tamird** [comment]
pg url building (and use of net.JoinHostPort) is done, but the impl is not yet shared with `sqlutils.PGUrl`.

**Comment by petermattis** [comment]
pg url building has moved to `server.Context`. The spaghetti mess of `runQuery*` functions has been much reduced. I'm not sure if there is anything left to be done here, certainly nothing is pressing for Beta. I'm changing the milestone to 1.0, but please close unless there is a specific cleanup that remains.

**Comment by mberhault** [comment]
looks like we're all set.
