### ISSUE TITLE
storage: non-zero HardState.Commit on uninitialized replica

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#40213]
```
cockroach debug merge-logs *.logs/*.log | grep -F r3157
ip-10-12-37-237> I190822 21:27:54.723498 883796922 storage/store.go:2593  [n5,replicaGC,s5,r3157/2:/Table/57/1/9{2/99964-3/25360}] removing replica r3157/2
ip-10-12-37-237> I190822 21:27:54.724112 883796922 storage/replica_destroy.go:152  [n5,replicaGC,s5,r3157/2:/Table/57/1/9{2/99964-3/25360}] removed 25401 (25396+5) keys in 1ms [clear=0ms commit=0ms]
ip-10-12-37-237> F190823 18:30:39.636004 297 storage/replica_raft.go:668  [n5,s5,r3157/5:{-}] setting non-zero HardState.Commit on uninitialized replica [n5,s5,r3157/5:{-}]. HS={Term:7 Vote:0 Commit:66957 XXX_unrecognized:[]}
```

Seen on the release qualification cluster for https://github.com/cockroachdb/cockroach/issues/39781

Also seen in unit tests: https://github.com/cockroachdb/cockroach/issues/39660#issue-480716022

**Comment by tbg** [comment]
Just got a repro from my gceworker running

make stressrace PKG=./pkg/storage/ TESTS=TestNodeLivenessSetDecommissioning

(this test has other failure modes too, see https://github.com/cockroachdb/cockroach/issues/40191 https://github.com/cockroachdb/cockroach/issues/39660#issue-480716022)

**Comment by tbg** [comment]
Here's said repro restricted to r6

```
W190826 16:00:19.700267 265 storage/store.go:1546  [s1,r6/1:/Table/{SystemCon…-11}] could not gossip system config: [NotLeaseHolderError] r6: replica (n1,s1):1 not lease holder; lease holder unknown
W190826 16:00:19.758138 265 storage/store.go:1546  [s1,r6/1:/Table/{SystemCon…-11}] could not gossip system config: [NotLeaseHolderError] r6: replica (n1,s1):1 not lease holder; lease holder unknown
E190826 16:00:22.235320 1383 storage/replica_range_lease.go:339  [s1,r6/1:/Table/{SystemCon…-11}] heartbeat failed on epoch increment
W190826 16:00:22.831772 2082 storage/store.go:1546  [s1,r6/1:/Table/{SystemCon…-11}] could not gossip system config: [NotLeaseHolderError] r6: replica (n1,s1):1 not lease holder; lease holder unknown
W190826 16:00:22.884958 2082 storage/store.go:1546  [s1,r6/1:/Table/{SystemCon…-11}] could not gossip system config: [NotLeaseHolderError] r6: replica (n1,s1):1 not lease holder; lease holder unknown
I190826 16:00:24.143661 2132 storage/replica_command.go:1264  [replicate,s1,r6/1:/Table/{SystemCon…-11}] change replicas (add [(n2,s2):2LEARNER] remove []): existing descriptor r6:/Table/{SystemConfigSpan/Start-11} [(n1,s1):1, next=2, gen=0]
I190826 16:00:24.219212 2132 storage/replica_raft.go:291  [replicate,s1,r6/1:/Table/{SystemCon…-11},txn=5a84301f] proposing ADD_REPLICA[(n2,s2):2LEARNER]: after=[(n1,s1):1 (n2,s2):2LEARNER] next=3
I190826 16:00:24.346032 2132 storage/store_snapshot.go:995  [replicate,s1,r6/1:/Table/{SystemCon…-11}] sending LEARNER snapshot 03b9cc5e at applied index 16
I190826 16:00:24.357993 2132 storage/store_snapshot.go:1038  [replicate,s1,r6/1:/Table/{SystemCon…-11}] streamed snapshot to (n2,s2):2: kv pairs: 44, log entries: 0, rate-limit: 8.0 MiB/sec, 0.09s
I190826 16:00:24.452298 2865 storage/replica_raftstorage.go:808  [s2,r6/2:{-}] applying LEARNER snapshot [id=03b9cc5e index=16]
I190826 16:00:24.500233 2865 storage/replica_raftstorage.go:829  [s2,r6/2:/Table/{SystemCon…-11}] applied LEARNER snapshot [total=46ms ingestion=4@1ms id=03b9cc5e index=16]
I190826 16:00:24.645917 2132 storage/replica_command.go:1264  [replicate,s1,r6/1:/Table/{SystemCon…-11}] change replicas (add [(n2,s2):2] remove []): existing descriptor r6:/Table/{SystemConfigSpan/Start-11} [(n1,s1):1, (n2,s2):2LEARNER, next=3, gen=1]
F190826 16:00:24.818729 2886 storage/replica_raft.go:668  [s2,r6/2:{-}] setting non-zero HardState.Commit on uninitialized replica [n2,s2,r6/2:{-}]. HS={Term:6 Vote:0 Commit:18 XXX_unrecognized:[]}
```

It looks like we're applying a snapshot and then hitting the fatal, perhaps even in the same ready cycle. What's weird is that after a snapshot the replica is supposed to be initialized, but it isn't - the log tags show this (no key range) and also we don't hit the fatal if it is initialized.

**Comment by tbg** [comment]
It's worth mentioning that in the release cluster crash (first message), no such snapshot is seen just before the crash. The logs have been rotated heavily on the other nodes but n5 (the crashing one) has logs from four days ago and it would've logged any incoming snapshots for that range. Possibly it was being created through a split, but then it's even weirder that it would be uninitialized.

**Comment by tbg** [comment]
I have a crash with `vmodule=raft=5` (few minutes of running stressrace): https://gist.github.com/tbg/892014e57dde6d17debd0833d3053f3d

The real problem seems to 100% be related to the snapshot. We see r6/2 apply the snapshot:

```
I190826 16:11:12.325953 1910 storage/replica_raftstorage.go:829  [s2,r6/2:/Table/{SystemCon…-11}] applied LEARNER snaps
hot [total=19ms ingestion=4@18ms id=efbc68d5 index=17]
```

note how it has key bounds in the log tags. We see this emit an MsgAppResp to the leader as it should.

Then when the next raft message comes in, we see that the raft group is getting created again (I'm not sure why) and the replica is descriptorless (=uninited) again. The leader sends an MsgApp and that triggers the crash.

My working day is coming to a close and I'd like to focus on atomic replication changes anyway, so I'd like to hand this off at this point.

**Comment by tbg** [comment]
Thanks for investigating, shame that this isn't the same thing. Maybe you can go back to the original logs and look at the raft state for the given node. The interesting thing there is that n5 had a replica of that range a long time ago. The problem is that a commit idx is sent when we don't have a log yet and thus this is borked (so is there a log? Why is there no snapshot message? Where does this incoming request come from?). What if the commit idx comes from a quiesce heartbeat? I think we take that idx from the leader's Progress. Since the peer has a new ReplicaID after readding I don't see how a previous commit index could leak past the tombstone, but maybe looking at the code can reveal a way in which this can happen? Though I just looked and didn't see a way. Either way, the fact that n5 itself has nothing about that range for a while and then suddenly explodes means we're probably not looking at snapshots here.

**Comment by tbg** [comment]
The other option is that maybe the replicaGC was an error? If rx/5 was in fact a member all along (even though n5 only had rx/2) and replicaGC decided by accident to remove that data, then once the range unquiesced this error could get triggered, since the leaseholder would still have an old progress.


I was also looking into whether `progress.Match` (which is used by the quiesce heartbeat to lower the commit index to something "safe" for the follower) could perhaps exceed what the follower has actually acked. So far it seems that it's not doing that.

**Comment by tbg** [comment]
> I don't know enough about what changed between pre-emptive snapshot handling and learner snapshot handling to be able to pinpoint why this race only now materialized. Perhaps we never wrote any Raft state during pre-emptive snapshots? @tbg or @danhhz do you have any idea? This also doesn't really help us track down the crash in #39781, although perhaps the symptoms here might be helpful.

The learner snapshot generates an immediate MsgAppResp, so the leader is immediately able to append. I think in the olden days the preemptive snapshot wouldn't trigger such a thing and so the first communication would be figuring out what log index to append at, so this probably prevented the race "well enough".
The other ingredient here that doesn't seem necessary but is interesting is that with learners the leader gets to send "insta-commit appends" because the quorum is still 1 and so a command appended at the leader is immediately committed and can be sent "as committed" in one MsgApp.

**Comment by tbg** [comment]
@nvanbenschoten Remind me how this all works - a Raft tombstone would be written atomically with destroying all of the state of the replica, including the raft log, raft applied index, etc, no? And we'll only ever accept log entries after having received a snapshot, which also includes a range descriptor. So how does n5 and up with a range for which it has <some stuff including a HardState> but also a raft tombstone?
Is this maybe an old bug that is only exposed now because learners get to vote and hit the assertion when they do? If that replica is a fresh learner I'd expect it to not have any state except a raft tombstone (optionally), and perhaps a HardState, but with a zero Committed index. Hope I'm missing something big here.

**Comment by tbg** [comment]
By looking at the range log for that range, you should be able to figure out if that range was added as a learner. What makes me hesitant to declare this obvious is the lack of any snapshot related messages in n5's log, though maybe you're right and they raced and were thus never observed.

**Comment by tbg** [comment]
Sorry, I should've pointed this out more clearly above: I don't think anything is wrong here with that vote. What's wrong is the nonzero commit index. etcd/raft has the invariant that the leader will never send a Commit index above what the follower has acked in its log. For example, if the leader knows 100 is committed but it only knows that the follower has entry 90, it will make sure to only sent Commit: 90.

I think what you're seeing is that the MsgVote contained a higher Commit index. Could that be the problem?

**Comment by tbg** [comment]
Oh, they match? I missed that. I think that is good news. Let's say it was indeed an MsgVote that triggered the crash. The raft group was likely not initialized, due to the previous replicaGC (heck, nothing was initialized because the replica was supposedly completely erased). The MsgVote comes in and we create a replica and its raft group. I assume the RawNode first emits the current HardState as an update, even though it's already persisted (have to check). And boom we go, because now we see a Committed but we don't have a state which isn't supposed to happen.
The problem then is that the replicaGC missed some data, not that the vote arrived. Any message would've done it with the exception of MsgSnap perhaps.

**Comment by tbg** [comment]
Ah, the MsgVote did update the HardState -- via a new Term. So that explains why it's coming out. But the commit index comes from the raft log entries, which were not supposed to be there.

**Comment by tbg** [comment]
> The question is why this HardState is still here.

Yep, and log entries.

I wonder if we'd see this crash frequently if we added an assertion when the group is instantiated. A replica in that state seems very likely to catch a crash when it becomes part of the range again, so I'm not sure we would.

**Comment by tbg** [comment]
> So unless I'm missing something obvious, this all seems to point at a RangeDeletion tombstone being dropped

I was worried that that's where we'd end up with this, the trail you've found looks pretty solid.

As far as repro-ing goes, I think we might get some mileage out of adding `./cockroach debug check-store` into our roachtest harness and failing the test whenever it finds something. Unfortunately check-store isn't quite there yet, so we'd have to brush it up first, plus we'd only want to run this check when running the master or 19.2 binary.

**Comment by bdarnell** [comment]
I wonder if cockroachdb/rocksdb#43 missed a path through which the range deletion block could be read and cached. For example, if `verify_checksums_before_ingest` were true (it's not), we'd try to read the whole file to verify its checksums and wouldn't distinguish the range deletion block from other blocks (I haven't confirmed whether this would populate the cache or not). 

Maybe the TableReader in GetIngestedFileInfo should be created without a block cache so we don't cache anything from the sst before its global sequence number is assigned instead of setting specific reads to bypass the cache.

**Comment by nvanbenschoten** [comment]
> Or am I barking up the wrong tree here because the range tombstone here came from replica GC instead of from a snapshot ingestion?

Yes, exactly. This range deletion tombstone wasn't ingested in an SST.

**Comment by tbg** [comment]
For reproing this, it's probably a good idea to have a loop that takes RocksDB checkpoints at intervals on top of keeping the WAL forever. If the problem is related to compactions, the WAL itself won't tell us anything except that it can confirm that the tombstones *were* put down and *were* lost. For the exact mechanics of how they were lost, we would need logs about the RocksDB compactions (I assume we can crank up the Rocks log level to get that) and ideally also checkpoints "sort of close" to the event.

**Comment by petermattis** [comment]
If this is a problem with a lost range deletion tombstone, @ajkr should be involved.

**Comment by nvanbenschoten** [comment]
We saw this again on `cyan-06`. This time, the new assertion we added in #40441 fired when creating the replica. Just like before, we see the replica (`r2758/2`) get destroyed and then the assertion fires 12 hours later.

```
cockroach.cockroach-cyan-06.root.2019-09-09T07_08_49Z.096265.log:I190909 07:14:16.632329 67681 storage/store.go:2613  [n6,replicaGC,s6,r2758/2:/Table/53/1/-785{8180…-0161…}] removing replica r2758/2
cockroach.cockroach-cyan-06.root.2019-09-09T07_08_49Z.096265.log:I190909 07:14:16.635354 67681 storage/replica_destroy.go:152  [n6,replicaGC,s6,r2758/2:/Table/53/1/-785{8180…-0161…}] removed 179837 (179831+6) keys in 3ms [clear=1ms commit=2ms]
cockroach.cockroach-cyan-06.root.2019-09-09T17_10_53Z.005024.log:F190909 19:16:37.053891 247 storage/store.go:4053  [n6,s6] found non-zero HardState.Commit on uninitialized replica [n6,s6,r2758/?:{-}]. HS={Term:27 Vote:5 Commit:121484 XXX_unrecognized:[]}
```

**Comment by nvanbenschoten** [comment]
This appears to have the same symptoms. The Range local and userspace keys have been deleted but the RangeID local keys remain. 

@ajkr are you available to pair on debugging this further? Knowing where to look from here is hitting the limits of my knowledge.

**Comment by ajwerner** [comment]
Have we been fishing for a fast repro for this? If so, check out https://github.com/cockroachdb/cockroach/pull/40868, it seems to do it reliably.
