### ISSUE TITLE
type inference for ValArg doesn't work for some expressions: CASE, function application

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#4024]

**Comment by petermattis** [comment]
Can you provide some concrete examples? I recall there are difficulties in doing type inference for `CASE` expressions, though not the details.

**Comment by JackKrupansky** [comment]
A function with a single argument which is a ValArg. Normally type check would infer the type of the ValArg from other, non-ValArg function arguments. Or, a function where all arguments are ValArgs.

**Comment by vivekmenezes** [comment]
In the bank example while using the pgwire protocol the following doesn't work:

from := rand.Intn(*numAccounts)                                                       
          to := rand.Intn(*numAccounts - 1)                                                     
          if from == to {                                                                       
            to = *numAccounts - 1                                                               
          }                                                                                     
          amount := rand.Intn(*maxTransfer)                                                     
                                                                                                
          update := `                                                                           
UPDATE bank.accounts                                                                            
  SET balance = CASE id WHEN $1 THEN balance-$3 WHEN $2 THEN balance+$3 END                     
  WHERE id IN ($1, $2) AND (SELECT balance >= $3 FROM bank.accounts WHERE id = $1)              
`                                                                                               
          if _, err := clients[i].db.Exec(update, from, to, amount); err != nil {               
            return err                                                                          
          }                                                               

I see the error

incompatible condition types int, valarg

Looking into the code this appears to be the type checker while evaluating the WHEN clause.

**Comment by mjibson** [comment]
The fix I have for this only fixes CASE statements. Please make single issues for the other kinds of statements with examples for which prepare fails.

@vivekmenezes the bank example is now closer to working. Subqueries are failing with prepare. Working on that now.
