### ISSUE TITLE
sql: schema changes do not work safely during upgrades

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#40241]
**Describe the problem**

When a user performs a rolling upgrade while schema changes are ongoing, or if a schema change is issued during a rolling upgrade, it is possible to incur a non-recoverable state in the cluster.

This means that online schema changes are currently unsafe to use in combination with online upgrades.

**Expected behavior**

We should fix the behavior and augment the test suite to exercise schema changes during rolling upgrades.

As a temporary workaround we could introduce a cluster setting or flag that disables schema changes (or blocks/suspends them) until an upgrade is finalized.

Doc warning issue: https://github.com/cockroachdb/docs/issues/4839

**Comment by knz** [comment]
@rolandcrosby @awoods187 putting this into your radar. Given how much this comes up in support this seems to be a pretty big deal.

@timveil also FYI - this needs to be taken into account in technical discussions with customers, to set expectations upfront. We're not planning to fix this before 20.1 or later.

**Comment by knz** [comment]
@mberhault 	I'm also putting this in your radar, you probably don't want MSO cluster outages when users try to do reasonable things.

**Comment by knz** [comment]
> Can this occur during the entire window where the upgrade is not finalized, or only during a mixed binary version scenario?

I think it's mainly during mixed binary version.

@lucy-zhang @dt  Can you confirm?

**Comment by knz** [comment]
> it doesn't seem limited to major version upgrades. 

Correct

> This was specifically for 19.1.3 to 19.1.5, correct?

Today's discussion prompted me to search whether we had an issue filed already, and since we didn't have one I filed it.

However the problem is prevalent - we've observed problems before and every time were lucky that the errors would dissipate on their own after the upgrade. 

However we do have an ongoing issue of schema change jobs deadlocked due to an upgrade (resolution unclear? @BramGruneir would know) and more generally the descriptor versioning, job lifecycle and the overall integration of DDL with SQL txns has not been designed to work in mixed-version scenarios.

**Comment by knz** [comment]
> a non-recoverable state in the cluster.

thinking of the dead job

**Comment by dt** [comment]
As far as the general class of issue, we added a gentle warning to avoid un-needed schema changes during upgrades to the docs. However, given that we don't have specific broken examples right now (and we'd individually file and fix them if we did), I don't think there's anything else actionable here.
