### ISSUE TITLE
ui: Persist statement statistics beyond the current 1 hour limit

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#40245]
The current version of the statements page is governed by telemetry collection machinery. Statement fingerprints and stats are purged hourly by default. We have heard numerous requests to enable a longer history of statement performance data, with requests ranging from the past 24 hours to the past month. This issue will serve as a placeholder for the coming enhancement to improve statement performance histories. As we start work on this feature we will break this into smaller issues with more concrete scopes of work.

**Comment by awoods187** [comment]
I'm closing this issue in favor of https://github.com/cockroachdb/cockroach/issues/56219
