### ISSUE TITLE
sql: TestTruncateCompletion times out

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#40251]
This times out on master all of the time. Curiously no issues are being filed (I mentioned this in #dev-inf), but also cc @bobvawter @kenliu 

Here's a recent one: https://teamcity.cockroachdb.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=1456409&_focus=74362

**Comment by jordanlewis** [comment]
No instances of this in email since 2019, so closing until we see it again.
