### ISSUE TITLE
sql: add randomized correctness testing for TPCH queries

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#40299]
TPCH queries are interesting and produce tricky plans. We currently only test correctness on these queries by using the "standard" example placeholders provided by the test spec. We've found bugs using these queries already - but it seems like there's no guarantee that producing correct results for the standard example placeholders means that we'd produce correct results for all combinations of placeholders.

This issue tracks adding infrastructure to generate random variations on the TPCH queries and verify their results against the vectorized engine, the non-vectorized engine, and PostgreSQL.

**Comment by yuzefovich** [comment]
This has been implemented (`tpchvec/sqlsmith`).
