### ISSUE TITLE
--cache visibility and management

### ISSUE THREAD

**Issue by glennfawcett** [cockroachdb/cockroach#40308]
**Is your feature request related to a problem? Please describe.**
Lack of visibility to cache efficiency makes it more difficult to scale.

**Describe the solution you'd like**
Customer would like to be able to analyze the cache hit rate to determine how many logical vs physical reads are happening per database object - cache hit rate.  Having an overall accounting of the cache-hit rate as well as a breakdown by database object would be useful.

Once this is in place, they would like the ability to *pin* critical objects in the cache so they don't get aged out as often.  The ability to assign a priority to specific objects is useful.  If you have a small dimension table, it should be *pinned*.  If you have a table that is essentially a write only log table, then aging it out immediately would be preferred to wasting space in the cache.

**Describe alternatives you've considered**
This mostly comes from customers which are familiar with Oracle, Sybase, SQL Server, or DB2 as they have ways to control and visualize the caching of objects.

Jira issue: CRDB-5552

**Comment by knz** [comment]
this is an observability project

cc @thtruo for qualification and triage
