### ISSUE TITLE
Quiesce IO for storage snapshot backup

### ISSUE THREAD

**Issue by glennfawcett** [cockroachdb/cockroach#40310]
**Is your feature request related to a problem? Please describe.**
Ability to Quiesce IO to create a a consistent storage level point-in-time backup.

**Describe the solution you'd like**
Customer wishes to clone an entire cluster by having the ability to Quiesce IO and create a consistent storage level backup.  This will be used to provide QA test data.

**Describe alternatives you've considered**
-na-

**Additional context**
This is commonly done with Legacy databases.

**Comment by dt** [comment]
Duplicate: https://github.com/cockroachdb/cockroach/issues/36208

**Comment by dt** [comment]
Oh, I misread this: you meant take a _physical_ backup of the store directories? 
That was explicitly rejected as an option in cockroach for a couple reasons, among them that physical store directories contain _replicated_ data unlike a legacy, single-node system. If you really, really, really want to take store snaps, we already have a way to stop all IO: stop the node -- but physical store snaps are generally not a use case we prioritize.
