### ISSUE TITLE
Test and Qualify ora2pg github tool for DDL migration

### ISSUE THREAD

**Issue by glennfawcett** [cockroachdb/cockroach#40313]
**Is your feature request related to a problem? Please describe.**
There is no official tested recommended tool to migrate from Oracle to CockroachDB.

**Describe the solution you'd like**
Test and Qualify [ora2pg github](http://ora2pg.darold.net/) tool for DDL migration

Jira issue: CRDB-5551

**Comment by jordanlewis** [comment]
@glennfawcett have you been able to try this out yourself?
