### ISSUE TITLE
During TPCC run results in panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by drewdeally** [cockroachdb/cockroach#40326]
panic: runtime error: invalid memory address or nil pointer dereference

Please describe the issue you observed, and any steps we can take to reproduce it:

after setting a tpcc partition workload the above error occurred

andrewdeally@drew-cl-0001:~$ ./cockroach workload init tpcc --drop --partitions=3 --warehouses=9  --partition-strategy=leases  --zones=us-east1-b,us-central1-a,us-west1-a
andrewdeally@drew-cl-0001:~$ ./cockroach workload run tpcc --partition-affinity=0 --partitions=3 --warehouses=9
Initializing 18 connections...
Initializing 90 workers and preparing statements...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2aee60f]

goroutine 691 [running]:
github.com/cockroachdb/cockroach/pkg/workload/cli.workerRun(0x4513d60, 0xc00072ea40, 0xc00050e060, 0xc0002b1f60, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/workload/cli/run.go:229 +0x8f
github.com/cockroachdb/cockroach/pkg/workload/cli.runRun.func1.1(0xc0001edc60, 0x3c755b7, 0x4, 0xc00054ef00, 0x5a, 0x5a, 0x0, 0x0, 0x0, 0xc00050e060, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/workload/cli/run.go:380 +0xfd
created by github.com/cockroachdb/cockroach/pkg/workload/cli.runRun.func1
	/go/src/github.com/cockroachdb/cockroach/pkg/workload/cli/run.go:370 +0x133
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2aee60f]

goroutine 674 [running]:
github.com/cockroachdb/cockroach/pkg/workload/cli.workerRun(0x4513d60, 0xc00072ea40, 0xc00050e060, 0xc0002b1f60, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/workload/cli/run.go:229 +0x8f
github.com/cockroachdb/cockroach/pkg/workload/cli.runRun.func1.1(0xc0001edc60, 0x3c755b7, 0x4, 0xc00054ef00, 0x5a, 0x5a, 0x0, 0x0, 0x0, 0xc00050e060, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/workload/cli/run.go:380 +0xfd
created by github.com/cockroachdb/cockroach/pkg/workload/cli.runRun.func1
	/go/src/github.com/cockroachdb/cockroach/pkg/workload/cli/run.go:370 +0x133
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2aee60f]

goroutine 622 [running]:
github.com/cockroachdb/cockroach/pkg/workload/cli.workerRun(0x4513d60, 0xc00072ea40, 0xc00050e060, 0xc0002b1f60, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/workload/cli/run.go:229 +0x8f
github.com/cockroachdb/cockroach/pkg/workload/cli.runRun.func1.1(0xc0001edc60, 0x3c755b7, 0x4, 0xc00054ef00, 0x5a, 0x5a, 0x0, 0x0, 0x0, 0xc00050e060, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/workload/cli/run.go:380 +0xfd
created by github.com/cockroachdb/cockroach/pkg/workload/cli.runRun.func1
	/go/src/github.com/cockroachdb/cockroach/pkg/workload/cli/run.go:370 +0x133

./cockroach version
Build Tag:    v19.2.0-alpha.20190805
Build Time:   2019/08/05 15:48:44
Distribution: CCL
Platform:     linux amd64 (x86_64-unknown-linux-gnu)
Go Version:   go1.12.5
C Compiler:   gcc 6.3.0
Build SHA-1:  5bd37e8eb58ca66b9293c234bc572411057fec3a
Build Type:   release

**Comment by nvanbenschoten** [comment]
Could you try again with a recent version of Cockroach? The version you're using is a month old and this should have been fixed in https://github.com/cockroachdb/cockroach/pull/39649.

**Comment by nvanbenschoten** [comment]
And note that `cockroach` itself doesn't need to be updated, but `workload` does and it looks like you're running the `workload` that's embedded in the `cockroach` binary.

**Comment by nvanbenschoten** [comment]
Closing this since I'm pretty certain that's the issue, but please re-open if updating doesn't fix this.
