### ISSUE TITLE
sql: SHOW PARTITIONS doesn't show inherited constraints

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#40349]
It's misleading that it doesn't. I think it should show them to you, and it should also tell you when they're inherited. No?

**Comment by rohany** [comment]
What do you mean by inherited constraints?

**Comment by andreimatei** [comment]
https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20180919_cascading_zone_configs.md

**Comment by rohany** [comment]
Oh i see. It is misleading that it doesn't. We can take a look at this!

**Comment by awoods187** [comment]
Nice find @andreimatei . We should definitely do this.

**Comment by rohany** [comment]
To do this correctly, it feels like we need to solve #40377.

**Comment by andreimatei** [comment]
> To do this correctly, it feels like we need to solve #40377 first.

Why? We have an inheritance today, so we should reflect that. Whether or not extend it seems orthogonal enough.
But perhaps more generally I'd agree with you that the data model is extremely awkward, so ideally we'd start over somehow.

**Comment by rohany** [comment]
Yeah, I meant to "correctly" do this. Displaying the current inheritance chain should be doable (though the fact that partitions that don't have constraints don't show up in the system.zones table complicates this).

**Comment by andreimatei** [comment]
Well, inheritance is broken for *sub-partitions*, not for partitions in general. Regular partitions do inherit from their table/index.

**Comment by andreimatei** [comment]
Btw, depending how you get your hands on a zone config (i.e. if you get it through calls like `getZoneConfigForKey()` and not directly from the system table), you get inherited fields in there, and you even get an `InheritedConstraints` field that tells you whether you've inherited crap.

**Comment by rohany** [comment]
Right now we are just joining against the crdb_internal.zones table which is why it is incorrect. The show commands are implemented through just straight translation into a new sql statement which is why this is annoying.
