### ISSUE TITLE
Testing for new CLI demo features

### ISSUE THREAD

**Issue by rohany** [cockroachdb/cockroach#40352]
A lot of new features were added (or are being added) the CLI

- [ ] locality settings
- [ ] many nodes
- [ ] default locality and location settings
- [ ] sample workloads
- [x] demo license acquisition
- [x] automatic topology setup

It would be nice to add some rigorous tests for these.

**Comment by awoods187** [comment]
@rohany looks like you forgot to specify what you wanted to do here

**Comment by rohany** [comment]
Yeah, sorry I was going to update this later. It was just a placeholder for me to remember a bunch of things.

**Comment by rohany** [comment]
All of these are in open PR's or completed.
