### ISSUE TITLE
roachprod: refer to host by node

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#40369]
Roachprod is a convenient tool for testing and deploying multi-node geo clusters. In the partitioning example (https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/165609536/Multi-Region+Geo-Partitioned+Replicas+and+Duplicate+Indexes) users must repeadtely put in the host for different nodes. 

It would be time-saving if users could, instead of specifying a number, refer to the host of roachprod. Something like:

```SQL
roachprod run $CLUSTER:10 './cockroach sql --insecure --host=node:1 -e "CREATE DATABASE movr;"'
```

Instead of:
```SQL
roachprod run $CLUSTER:10 './cockroach sql --insecure --host=##.##$.#.## -e "CREATE DATABASE movr;"'
```

**Comment by petermattis** [comment]
Unless I'm misunderstanding, this already exists via the `{...}` syntax. For example:

```
roachprod run $CLUSTER:10 './cockroach sql --insecure --host={pghost:1} -e "CREATE DATABASE movr;"'
```

The current expansions are `pghost[:<nodes>]`, `pgurl[:<nodes>]`, `pgport[:<nodes>]`, `uiport[:<nodes>]`, `store-dir`, `log-dir`, `certs-dir`. Rather that specifying `--host={pghost:1}`, the normal way to do this is `--url={pgurl:1}` as this will work in `local` deployments where the port is different. You also shouldn't need to specify `--insecure` in that case.

**Comment by awoods187** [comment]
this is awesome! thanks for educating me! ccing @jseldess for the movr examples and future use
