### ISSUE TITLE
sql: UPSERT causes pq: duplicate key value (id, timestamp) violates unique constraint \"primary\"

### ISSUE THREAD

**Issue by cgebe** [cockroachdb/cockroach#40368]
**Describe the problem**

Executing UPSERT causes unique constraint violation on primary key:

```
pq: duplicate key value (id,timestamp)=(1305,1567171511957000000) violates unique constraint \"primary\"
```

**To Reproduce**

I am batch executing UPSERT (~500 rows) to import data into crdb. Since, some of the data is already in the database i am using UPSERT to avoid getting errors for the batch execution when doing INSERTs. The UPSERT is executed periodically.

**Expected behavior**
The command to finish without exception as described here: https://www.cockroachlabs.com/docs/stable/upsert.html#upsert-that-updates-a-row-conflict-on-primary-key

However, i get exactly the exception which UPSERT should prevent...

**Environment:**
 - CockroachDB: v19.1.4
 - Server OS: Debian 9
 - Client app: Go client

**Comment by cgebe** [comment]
My current workaround to this problem is splitting up the 500 rows into smaller batches (~10 rows), which so far does not cause the error on the second UPSERT.

**Comment by cgebe** [comment]
When investigating i found, that i fetch duplicates to upsert within one sql command which likely causes the error. However, i supposed to not encounter this error when upserting. If intended then this issue can be closed.

**Comment by knz** [comment]
cc @jordanlewis for triage

**Comment by karlseguin** [comment]
Not sure if this is the same issue, but it's easy to reproduce:

```
create table x (id int primary key);
insert into x values (1), (1) on conflict do nothing;
ERROR:  23505: duplicate key value (id)=(1) violates unique constraint "primary"
```

In PG, you get the expected behavior:
```
insert into x values (1), (1) on conflict do nothing;
INSERT 0 1
```

**Comment by knz** [comment]
@andy-kimball wasn't this addressed by your changes in 19.2?

**Comment by martskins** [comment]
Just found this issue as well, on, at least, 19.1.3 and 19.2.1.

Found a way to reproduce it too, with small batch sizes as well.

```
CREATE TABLE IF NOT EXISTS users ( id text NOT NULL, external_id integer NOT NULL, PRIMARY KEY (id, external_id));
INSERT INTO users (id, external_id) VALUES ('N1111', 1);
```
If the conflict is within the batch and within the existing rows as well, it runs fine:
`INSERT INTO users (id, external_id) VALUES ('N1111', 1), ('N1111', 1) ON CONFLICT (id, external_id) DO NOTHING;`

If the conflict is found only within the batch, it fails:
`INSERT INTO users (id, external_id) VALUES ('N2222', 1), ('N2222', 1) ON CONFLICT (id, external_id) DO NOTHING;`

**Comment by jordanlewis** [comment]
This is currently intended behavior. It's a duplicate of #37880. Please weigh in there - I think we should consider changing it to be the same as PostgreSQL.
