### ISSUE TITLE
Implement Jepsen testing for CockroachDB

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#4036]
Mentioned in #83, #2132.

**Comment by knz** [comment]
#83

**Comment by knz** [comment]
Some initial implementation in http://github.com/knz/jepsen

**Comment by petermattis** [comment]
I think that repo should live at http://github.com/cockroachdb/jepsen eventually.

**Comment by knz** [comment]
Pushed to https://github.com/cockroachdb/jepsen/commit/b7f33e8f0efb73bf318eb8650c2a6333cbb16bc4 .

Now this still to be updated to use pgwire over the network and extended to test multiple ranges. Still on it.

**Comment by knz** [comment]
Done in https://github.com/cockroachdb/jepsen/tree/master/cockroachdb.
