### ISSUE TITLE
build: CockroachDB requires too much RAM to build

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#40378]
**Describe the problem**

- folk have noticed that the link process gets killed when using the builder image (because most Docker installs limit the container to 2GB ram)
- @timveil 	measured memory usage and saw it spike to **6GB during a build**
- @vladdy and @irfansharif 	 had to waste time investigating this during their onboarding
- @justinj 	complains that the link phase can last up to 20s+ on his laptop
- when running other apps in parallel with a build, the resource consumption spikes to the point that RAM gets exhausted - with swap things become unbearably slow, and without swap processes get killed

**To Reproduce**

`make build`

**Expected behavior**

- the build should work without swap on a mid-range laptop with just 4 or 8GB RAM.

**Environment:**

`master` branch

**Additional context**

The resource consumption + related slowness is impacting the productivity of the eng team.

**Comment by knz** [comment]
cc @petermattis for triage

**Comment by knz** [comment]
cc @andy-kimball this might be part of the project to reduce overall resource usage - a large binary with too many assets will need to be reduced to also reduce the price point of deploying cockroachdb

**Comment by knz** [comment]
As a data point on my laptop the final binary file produced by `make build` is 175MB, and 122MB when stripped down. For reference, one or two versions ago this was below 80MB.

**Comment by knz** [comment]
I just tried to build on my laptop (8gb ram) with the builder image and the build with UI (`mkrelease`) is failing reliably if I don't have swap enabled. With swap, as expected everything becomes sluggish.  

`make buildshort` alleviates but doesn't produce a full executable nor does `mkrelease` offer a "short" option.

So I'd say the issue is maybe a bit more serious than it seems.

**Comment by knz** [comment]
from @tbg:

> FWIW, make test on my gceworker also gets signal:killed half of the time, probably because it builds a lot of stuff in parallel and it’s got lots of cores

**Comment by knz** [comment]
A suggestion was made to tweak the `make -j` parameter. This only partially alleviates ram usage but still runs into make exhaustion during link or tests.

There is a fundamental issue at hand:
- the `-j` parameter limits the amount of parallelism in the `make` jobs, whereas
- each individual `go`  invocation by `make` also floods the system up to `$GOMAXPROCS`

So we have the following:
- `-j1` without restricting `$GOMAXPROCS`: the `make` invocations up to the final `go build` compile/link phase will be limited, but the build fails in the `go` process
- restricting `$GOMAXPROCS=1` without changing `-j`: this usually alleviates (which strongly points most of the RAM consumption to happen in the `go` process) but then the build takes *forever*

It's possible to set both `-j1` and `GOMAXPROCS=1` but then the ram usage is still high during links, _and_ the build now takes forever when resources happen to be sufficient.

**Comment by knz** [comment]
Also I just checked manually and even when I set `GOMAXPROCS=1` (or 2 or 4, but lower than the 8 cores available) I still see the `go` process spawn threads and flood all available cores.

The reason for this is hidden in the internals of the Go runtime: when Go issues a syscall (e.g. a disk write) it will park the syscall into a separate thread created in excess of the limit set via `$GOMAXPROCS`. In fact there can be as many threads created as there are runnable goroutines currently issuing a syscall.

In an I/O heavy workload with a lot of logical concurrency (many goroutines) this causes many threads to be spawned and trigger parallel I/O regardless of the value of `$GOMAXPROCS`.

**Comment by knz** [comment]
I'd also like to point the obvious:

- we may have degraded our build experience by generating too much go code, or structured it in ways that trigger bad corner cases in the go compiler. This wasn't that bad in previous CockroachDB versions.

- AFAIK Go's ["pclntab problem"](https://science.raphael.poss.name/go-executable-size-visualization-with-d3.html) hasn't yet been solved, so the time/ram needed to build these tables is continuing to grow super-linearly with the number of source files.

**Comment by kenliu** [comment]
plan to revisit this issue post migration to bazel

**Comment by knz** [comment]
@dt ran into this yesterday

**Comment by petermattis** [comment]
I noticed today that compiling `sql/exec` uses 4-5GB of memory. I suspect this is because of the large amount of generated code in a single package. @jordanlewis Can we split up the `sql/exec` package?

Top 10 source file line counts per-package (only `.go` files, not including `_test.go` files):

```
   1078989 sql/exec
     75025 sql
     72636 roachpb
     44423 storage
     39312 server/serverpb
     33304 sql/opt/memo
     31264 sql/sem/tree
     25958 sql/distsqlpb
     25582 sql/parser
     25031 sql/sqlbase
```

Within the `sql/exec` package the top 10 files by line count:

```
  169944 mergejoiner_fullouter.eg.go
  142352 mergejoiner_leftanti.eg.go
  140290 mergejoiner_leftouter.eg.go
  139786 mergejoiner_rightouter.eg.go
  110680 mergejoiner_leftsemi.eg.go
  110110 mergejoiner_inner.eg.go
  107776 projection_ops.eg.go
  102669 selection_ops.eg.go
    9296 overloads_test_utils.eg.go
    6908 quicksort.eg.go
```

**Comment by jordanlewis** [comment]
We trimmed down the generated code size a lot. Is this still a problem?

**Comment by knz** [comment]
I confirm that the RAM usage is going down. The executable size, however is not.
Recall my _prediction_ from March 2019:


Year | 2017 | March 2019 | 2021 (projected)
-- | -- | -- | -- 
Total size | 32M | 71M | 157M
CockroachDB code in pkg/ | 16M (50%) | 32M (45%) | 64M (41%)
runtime.pclntab | 7.3M (23%) | 26M (36%) | 85M (54%)

Well it turns out we're ahead of schedule:

Year | 2017 | March 2019 | September 2019
-- | -- | -- | -- 
Total size | 32M | 71M | **163M**
CockroachDB code in pkg/ | 16M (50%) | 32M (45%) | **29M (32%)**
in `colexec` | | | 7.2M (7.9%)
`runtime.pclntab` | 7.3M (23%) | 26M (36%) | **33M (37%)**

So we've eliminated some code (thanks Radu!) but pclntab keeps growing, due to the overall growth in the number of functions.

Also we have to do something about dependencies. We bumped the executable size from 71M to 163M in just 6 months.

**Comment by knz** [comment]
Anyway this issue was focused on ram usage and it's not a problem any more. closing.

**Comment by knz** [comment]
Just for reference:
- compiling colexec now requires 2+ GB RAM (4+ previously)
- linking the final binaries requires ~2 GB RAM
