### ISSUE TITLE
flexibility in handling of `"` by the import command

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/cockroach#40373]
**Is your feature request related to a problem? Please describe.**

Flexibility in instructing IMPORT command how the `"` literal  should be treated.
 
**Describe the solution you'd like**

An option to instruct IMPORT command that:

- the quote should be treated as a literal and should loaded whether it is in the beginning, middle or end.  
- the delimiter is the only special character that should be quoted to escape

**Describe alternatives you've considered**

External program can be used to process to CSV to make the file CockroachDB IMPORT compliant; however, this would take extra time and cost in term so of processing.  As a reference, Oracle was able to process the CSV file as is.
 
**Additional context**

https://github.com/cockroachdb/docs/issues/5341

Jira issue: CRDB-5546

**Comment by spaskob** [comment]
See also https://github.com/cockroachdb/cockroach/issues/39820
