### ISSUE TITLE
SQL: support for CakePHP

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#40389]
A customer sent us this information:
```
Framework: CakePHP
Version: 3.8.2
I regularly use CakePHP, but I have used other frameworks before. The biggest issue with CakePHP is that I can't perform migrations as stated in the documentation: https://book.cakephp.org/migrations/2.x/en/index.html
```
```
Migrations - 2.x - book.cakephp.orgInstallation¶. By default Migrations is installed with the default application skeleton. If you’ve removed it and want to re-install it, you can do so by running the following from your application’s ROOT directory (where composer.json file is located):book.cakephp.org
--
```

> Migrations is a vital part of development and I can't [use CRDB] without it. I have set up all the migration files according to the tutorial and configured the database settings to point to cockroachdb on my localhost.
> When I try to run the migrations with the following command: bin/cake migrations migrate. I get the following error:
```
SQLSTATE[42883]: Undefined function: 7 ERROR:  unknown function: pg_get_serial_sequence() in [C:\wamp64\www\cockroachdbcake\vendor\cakephp\cakephp\src\Database\Schema\Collection.php, line 133]
```

> As a control, when I run the same commands on Postgres and MySQL databases, it works.

Jira issue: CRDB-5542

**Comment by jordanlewis** [comment]
`pg_get_serial_sequence` is now supported.
