### ISSUE TITLE
*: errors constructed from other errors with %v don't store details

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#40400]
**Describe the problem**

When an error is generated from another error with e.g. `errors.Newf("woo %v", otherErr)`, the details from `otherErr` are not systematically captured and reported to Sentry.

See an example here: https://sentry.io/organizations/cockroach-labs/issues/972297758/

![Screenshot_2019-09-02_13-37-35](https://user-images.githubusercontent.com/642886/64112150-e141ac00-cd86-11e9-955a-f785970597d5.png)

The stack trace is where the outer error is constructed but the details from the original error are lost.

**Expected behavior**

The original error should be preserved somehow.

For context, note that the [specific example linked above](https://sentry.io/organizations/cockroach-labs/issues/972297758/) is from crdb 19.1; in 19.2 _for that case specifically_ the behavior is different, as follows:

- the particular file `data.go` from that example now uses `github.com/cockroachdb/errors` instead of `github.com/pkg/errors` and
-  the function `safedetails.Redact()`  in `github.com/cockroachdb/errors`, which is invoked in those cases, knows how to extract the additional safe details from error causes. 

So we're expecting 19.2 to not produce detail-less reports for that particular case. However, other error constructions points are still affected:

- places that construct errors with `%v` but without using `github.com/cockroachdb/errors`
- places that construct a string with `fmt.Sprintf` and then build an error out of that

There are several avenues to explore:

- mandate uses of `github.com/cockroachdb/errors` with a linter
- audit the code and replaces uses of `fmt.Sprintf` with `errors.Newf` where applicable (or using the other error constructors)

**Comment by tbg** [comment]
What's the use of the pattern `return errors.Errorf("something blah blah error %v", actualErr)` as opposed to `errors.Wrapf(actualErr, "something blah blah")`? I see the UX value in making the formatters "implicitly wrap" errors, so maybe that's a strong enough justification, but with today's APIs, aren't you just supposed to use `.Wrap{,f}` to decorate errors further?

**Comment by knz** [comment]
It depends.
I'd say in most cases `Wrap` is the better choice.
However there _are_ cases where the original cause must be "hidden" and then the best approach is `errors.Handled` (introduce a barrier). Formatting the rror with `%v` is also a barrier (albeit crude).

In the new go 1.13 error logic, there is a special case: if you construct an error with `fmt.Errorf("...: %w", ..., err)` (notice `%w`) it will implicitly call `Wrap()`, otherwise (with `%v`) it will not.

Given that many Go programmers will more naturally reach out to formatting with `%v` (and perhaps, over time `%w`) than thinking about which constructor to use, I would recommend pushing for the error library to "do the right thing" automatically.

**Comment by knz** [comment]
this has been fixed
