### ISSUE TITLE
tpcc init --partitions=3 fails partition error

### ISSUE THREAD

**Issue by drewdeally** [cockroachdb/cockroach#40416]
it seems not all tables are partitioned and fails on zone config step

cockroach workload init tpcc --drop --partition-affinity=0 --partitions=3 --warehouses=30  --partition-strategy=leases  --zones=us-east1-b,us-central1-b,us-west1-b "postgres://root@drew-tpcc-0003:26257?sslmode=disable"
I190903 03:10:56.763945 1 workload/workloadsql/dataload.go:135  imported warehouse (0s, 30 rows)
I190903 03:10:56.973148 1 workload/workloadsql/dataload.go:135  imported district (0s, 300 rows)
I190903 03:12:21.255755 1 workload/workloadsql/dataload.go:135  imported customer (1m24s, 900000 rows)
I190903 03:13:13.880940 1 workload/workloadsql/dataload.go:135  imported history (53s, 900000 rows)
I190903 03:13:38.869174 1 workload/workloadsql/dataload.go:135  imported order (25s, 900000 rows)
I190903 03:13:42.319529 1 workload/workloadsql/dataload.go:135  imported new_order (3s, 270000 rows)
I190903 03:13:44.371986 1 workload/workloadsql/dataload.go:135  imported item (2s, 100000 rows)
I190903 03:16:45.401724 1 workload/workloadsql/dataload.go:135  imported stock (3m1s, 3000000 rows)

I190903 03:23:54.206866 1 workload/workloadsql/dataload.go:135  imported order_line (7m9s, 9002592 rows)
Error: Could not postload: could not partition tables: Couldn't exec "ALTER PARTITION p1_0 OF TABLE order_line CONFIGURE ZONE USING constraints = '{\"+zone=us-east1-b\":1}', lease_preferences = '[[+zone=us-east1-b]]'": pq: partition "p1_0" does not exist on index "primary"

Build Tag:    v19.2.0-alpha.20190606-1952-gd51fa78
Build Time:   2019/09/02 06:12:40
Distribution: CCL
Platform:     linux amd64 (x86_64-unknown-linux-gnu)
Go Version:   go1.12.5
C Compiler:   gcc 6.3.0
Build SHA-1:  d51fa78ff90a113c9009d263dfaf58d3672670a6
Build Type:   release
a

**Comment by solongordon** [comment]
Thanks @drewdeally, this is related to a recent syntax change to the partition commands. Same issue is affecting one of our nightly tests so I'll track the issue on that ticket: https://github.com/cockroachdb/cockroach/issues/40360

**Comment by drewdeally** [comment]
thanks @solongordon I suppose since data loaded I can modify the schema and proceed to partition run?

**Comment by solongordon** [comment]
That sounds right, if you know what the partitioning schema should be. The issue here is that we changed the syntax so you need to specify indexes explicitly when you run CONFIGURE ZONE. So rather than `ALTER PARTITION p1_0 OF TABLE order_line` here you would need to specify `ALTER PARTITION p1_0 OF INDEX order_line@order_line_stock_fk_idx`.

I'm thinking it was probably a mistake to break this backward compatibility so I will look into restoring the old behavior. I'll investigate this today.

**Comment by drewdeally** [comment]
Ok - the table itself is neither partitioned I noticed only 3 tables were updated

So it seems it loads the table, alter partition, and alter set zone sequentially

**Comment by solongordon** [comment]
OK, this should be fixed once
https://github.com/cockroachdb/cockroach/pull/40431 is merged.
