### ISSUE TITLE
ui:Allow arbitrary time ranges for metrics graphs in the UI console

### ISSUE THREAD

**Issue by jasobrown** [cockroachdb/cockroach#40422]
**Is your feature request related to a problem? Please describe.**
Users really like the CockroackDB UI console, but they would like more flexibility in the time ranges available. Currently the end time is fixed ('now'), and the start times are fixed as well ('Last 10 Min', 'Last 1 hour', and so on). Users would like to display arbitrary time ranges (within reason) of the metrics.

**Describe the solution you'd like**
We would like to have a UI widget where we can set the start/end time stamps for the graphs. 

**Describe alternatives you've considered**
We have our own internal metrics system, into which we scrape most, if not all, CockroachDB metrics. In that system we can slice and dice metrics any way we want, but users would like that in the Cockroach console, as well.

**Comment by piyush-singh** [comment]
We should have an update to the time picker for the metrics dashboards shortly. cc @Annebirzin

**Comment by piyush-singh** [comment]
@elkmaster @Annebirzin let's use this as the tracking/meta issue for the date/time picker work. Designs were linked via zeppelin, but adding a quick screenshot here for reference:

![image](https://user-images.githubusercontent.com/21692034/65546805-37b58c80-dee6-11e9-9652-acb009c98661.png)

The issues related to the update here are:

- [ ] #7778 (we can close out a 4 digit issue!) Adding query params to capture time selection
- [] #41070 Giving the user proper errors and warnings for invalid selections
