### ISSUE TITLE
cli: update demo error message for expired license

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#40434]
Demo now uses enterprise licenses by default. It comes with a one hour limit. If you attempt to use a feature that requires an enterprise license, you will receive this message:
```
pq: Use of replication zones on indexes or partitions requires an enterprise license. Your evaluation license expired on September 3, 2019. If you're interested in getting a new license, please contact subscriptions@cockroachlabs.com and we can help you out.
```

This may be confusing to demo users since they do not expressly get a license and its confusing that the license message will be for the same day. 

We should enhance this message to say something like this for demo:
```
Your enterprise license for Cockroach Demo expired after 1 hour. To obtain a full trial license click here or reach out to subscriptions@cockroachlabs.com and we can help you out.
```

Jira issue: CRDB-6341

**Comment by rohany** [comment]
cockroach demo has been changed to give a 24 hour license now. Will this still be an issue?

**Comment by awoods187** [comment]
I still think we should do this but it isnt a high priority issue
