### ISSUE TITLE
core: node showing up with inconsistent data leading to orphaned and corrupted data

### ISSUE THREAD

**Issue by roncrdb** [cockroachdb/cockroach#40433]
**Describe the problem**

A specific node on a cluster was experiencing inconsistent data. 

We were able to isolate which node it was by using the following grep command: 

`grep -RF 'consistency check failed with' . | sed -n 's/.*\[\(n[0-9]\).*with \([0-9]\) inconsistent.*/\2 \1/p' | sort | uniq`

Queries would return inconsistent data as well as orphaned data

Shutting down the specific node resolved the inconsistencies that the cluster was experiencing. 

If an inconsistency exists we expect to see strange behaviour. The bad replica can receive traffic and return incorrect results. 

The root cause of the inconsistency is not yet known and should be investigated. 

If the debug zip or directory dir is needed, please let me know! 

**Environment:**
 - CockroachDB : 2.1.4

**Comment by andy-kimball** [comment]
Closing due to age and no repro information or logs. We now have L2 support process for escalations as well.
