### ISSUE TITLE
stability: Don't restart after consistency check failure

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#40442]
When the consistency checker fails, nodes crash. This is suboptimal in a lot of ways, but especially because if the node automatically restarts (such as by systemd or k8s), it may come back up and serve inconsistent data before the consistency checker's next cycle detects the problem and crashes it again (the checker runs on a 24h cycle by default). If the operator is monitoring downtime or flapping instead of individual crashes, they may not even notice these relatively infrequent crashes.

Instead, until we can implement a more graceful solution to this problem, we may want to take steps to keep the node from restarting at all if its last failure was due to the consistency checker. This has two downsides: collateral unavailability if the consistency checker takes down multiple replicas (the checker doesn't currently try to identify the minority node(s)), and an increased risk that the downed node might lead to upreplication of an incorrect replica. The former downside seems OK (and is at least compatible with our CAP-consistent philosophy), although I'm not sure about the latter. 

This could be implemented by either writing a deathrattle file to disk before crashing the node and checking it on startup, or exiting with a special status code to tell systemd/k8s not to restart and to alert an operator.

**Comment by tbg** [comment]
We already write a RocksDB checkpoint in 19.1 onwards in this case. We could take the existence of a consistency-created checkpoint as a deathrattle.
The special status code option has the downside that it needs to be taught to users and in the absence of that there's a good chance that the corrupt node will be rebooted anyway.
