### ISSUE TITLE
sql: cannot parse output: TABLE error FOR KEY SHARE

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#40458]
RSG is reporting:

> cannot parse output of Format: sql="SELECT EXISTS ( ( ( ( TABLE error FOR KEY SHARE ) ) LIMIT ALL FOR KEY SHARE ) ) AS IS FROM ident ", formattedSQL="SELECT EXISTS ((((TABLE error FOR KEY SHARE)) FOR KEY SHARE)) AS is FROM ident": at or near "for": syntax error

This is a problem in probably our formatter (or maybe the parser) which isn't able to roundtrip format and parse one of the above statements.

**Comment by jordanlewis** [comment]
This isn't a valid SQL statement. Can you have RSG not generate ForLocked clauses if `SelectClause` isn't a normal select? Not sure how we're supposed to do that.

**Comment by mjibson** [comment]
> SELECT EXISTS ( ( ( ( TABLE error FOR KEY SHARE ) ) LIMIT ALL FOR KEY SHARE ) ) AS IS FROM ident

is valid SQL

> SELECT EXISTS ((((TABLE error FOR KEY SHARE)) FOR KEY SHARE)) AS is FROM ident

is not valid SQL:

```
invalid syntax: statement ignored: at or near "for": syntax error
DETAIL: source SQL:
SELECT EXISTS ((((TABLE error FOR KEY SHARE)) FOR KEY SHARE)) AS is FROM ident
```
