### ISSUE TITLE
sql: improve output of show ranges 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#40467]
We've made a number of improvements to SHOW RANGES in 19.2 including adding locality. As a result, this is the current output:

![image](https://user-images.githubusercontent.com/22278911/64257111-c2f8bf00-cef2-11e9-8817-56c405e7c8b3.png)

This output can be confusing because:

- The leaseholder column breaks up the replicas and localities columns
- Locality order follows the order of the replica column but it doesn't put the leseholder first which is the previous column. This ordering will invariably trip up users
- Leaseholder location is one of the most important performance indicators and it's not immediately obvious where that replica lives

I think we should put the leaseholder column first, follow it with a leaseholder locality column, add then follow with the remaining replicas and their locations.

Alternatively, it would be great if there was one way to represent this via one column. Or a way to convey leaseholder replicas in the replica list.

**Comment by rohany** [comment]
I think theres too much information to show for one column -- I think the leaseholder id, leaseholder locality, replicas list, replica localities makes the most sense

**Comment by awoods187** [comment]
This looks good:
![image](https://user-images.githubusercontent.com/22278911/64654056-10df5c80-d3f6-11e9-8570-36cfe3e25a42.png)
