### ISSUE TITLE
Nodes keep trying to contact decomissioned node

### ISSUE THREAD

**Issue by jasobrown** [cockroachdb/cockroach#40473]
**Describe the problem**

In a six node cluster, in one region, a node was terminated by AWS, and the ASG spawned a new instance which correctly joined the cockroach cluster. The previous node was in the 'dead' state for a few days (it was a test cluster), and the surviving nodes, correctly, kept trying to contact the terminated node. I then decommissioned the node, yet the remaining nodes are still trying to contact the the decommissioned node. I can tell this via the logs:

```
W190904 16:32:37.868433 4147063391 vendor/google.golang.org/grpc/clientconn.go:1304  grpc: addrConn.createTransport failed to connect to {100.66.XXX.XXX:7101 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 100.66.XXX.XXX:7101: connect: connection timed out". Reconnecting...
W190904 16:32:37.868555 4147063391 vendor/google.golang.org/grpc/clientconn.go:1304  grpc: addrConn.createTransport failed to connect to {100.66.XXX.XXX:7101 0  <nil>}. Err :connection error: desc = "transport: Error while dialing cannot reuse client connection". Reconnecting...
W190904 16:32:37.868596 4147063391 vendor/google.golang.org/grpc/clientconn.go:953  Failed to dial 100.66.XXX.XXX:7101: context canceled; please retry.
```

**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. Set up CockroachDB cluster in EC2, using Auto Scaling Groups
2. Terminate one of the nodes, wait for the ASG to launch a new instance, and let it join the Cockroach cluster
3. Observe that logs are looking for the terminated node
4. Decommission the terminated node via `cockroach node decommission <nodeId>`
5. Wait a few hours, and observe that logs are still looking for the terminated node

**Expected behavior**
After decommission I would expect the cluster to trying to contact the terminated node.

**Environment:**
 - CockroachDB version 19.1.2 + a few minor custom patches (nothing that would affect decommission)
 - Server OS: Linux/Ubuntu Xenial + kernel version 4.13.0-19-generic
 - Client app: Not applicable

**Additional context**
What was the impact? No real impact as far as i can tell, just noise in the log.

**Comment by ajwerner** [comment]
Relates to https://github.com/cockroachdb/cockroach/issues/39410. This is on our radar but probably won't make it for this release given the lack of implications. Unfortunately the only real way to destroy those connections is a rolling restart of the cluster which probably isn't advisable if only to avoid the log noise. We should do something about this for the next release either by detecting inactive connections or detecting connections to nodes which are not in the cluster.

**Comment by jasobrown** [comment]
As long we know this is just log noise, it's reasonable to punt. Also, fwiw, I noticed the the replacement node, that was spawned by the ASG after the terminated node, does *not* try to contact the decommissioned node (or at least, nothing is in the log).

This can be but in the backlog, then. Thanks!

**Comment by ajwerner** [comment]
> fwiw, I noticed the the replacement node, that was spawned by the ASG after the terminated node, does not try to contact the decommissioned node (or at least, nothing is in the log).

That's right. The decommissioned node's address is no longer gossiped and new nodes shouldn't learn about it. The re-connection is happening in the `rpc` package on the individual connection trying to heartbeat a previously established gRPC connection.

**Comment by ricardocrdb** [comment]
Hey @jasobrown 

Did you have any other questions on this, or is it ok to close out this issue, since we are tracking the decommissioned node noise in [#39410](https://github.com/cockroachdb/cockroach/issues/39410)? You can follow that issue for further updates. Please let me know if you have any other questions.

**Comment by jasobrown** [comment]
@ricardocrdb No other worries here, feel free to close out. thanks!

**Comment by ricardocrdb** [comment]
Awesome @jasobrown thanks for confirming. I will go ahead and close. Let us know if anything else comes up.
