### ISSUE TITLE
exec: a bug with nested CASE expression

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#40517]
On the following logic test:
```
# LogicTest: fakedist-vec

# Regression test for #38878 (incorrect span generation with OR and exclusive
# string boundaries).
statement ok
CREATE TABLE t38878 (k1 STRING, k2 STRING, v INT, PRIMARY KEY (k1, k2))

statement ok
INSERT INTO t38878 VALUES ('a', 'u', 1), ('b', 'v', 2), ('c', 'w', 3), ('d', 'x', 4), ('d', 'x2', 5)

query TTI rowsort
SELECT * FROM t38878 WHERE (k1 = 'd' AND k2 = 'x') OR k1 = 'b' OR (k1 > 'b' AND k1 < 'd')
----
b  v  2
c  w  3
d  x  4
```
we get this
```
pq: internal error: unexpected error from the vectorized runtime: runtime error: index out of range
```
I believe what's happening here is that we have "nested" ORs which are converted into nested CASEs which messes up the indices of the case arms.
cc @jordanlewis @solongordon

**Comment by jordanlewis** [comment]
Hmm, there shouldn't be a problem with that, but I'd believe that there is. @solongordon could you take a first look? I can try to help if the case stuff is confusing.

**Comment by solongordon** [comment]
Turns out this is unrelated to nested CASEs but rather to short-circuiting. If all rows in a batch satisfy the first condition, later conditions don't get evaluated, which may skip adding a column which is later expected to exist. Simpler repro:
```
# LogicTest: local-vec

statement ok
CREATE TABLE t (x INT);

statement ok
INSERT INTO t VALUES (0);

query I rowsort
SELECT * FROM t WHERE x = 0 OR x = 1 AND x = 2
----
0
```
Looking into a fix now.
