### ISSUE TITLE
importccl: pick up where we left off when resuming IMPORT

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#40524]
Currently IMPORT tracks progress as data moves though its multi-stage pipeline:
The input format implementations inform the row-converter/batch-sender of a percentage completed as well as a resume-row-offset and then the process that drains batches and flushes them to storage is responsible for then tracking what reported row offset has actually been flushed though the rest of the pipeline. 

Most of this plumbing is in place as of #39646, but it is up to each frontend to actually set a meaningful (to it) resume offset and then actually use that offset later, and what that is depends on the input format: for CSV it might be row of file while for mysqldump it might be a whole batch of rows in one insert statement. What is important is that it a) is a unit of skippable work for that frontend (if it reads row-by-row or parses whole statements or whatever) and b) it emits it only once that row has been pushed into the converter (so if that converter flushes, that means it is safe to skip that row on resume).

The part that is left to do here is teach each frontend to actually track such a value, emit it, and then plumb it back into those frontends on resume so they can use it.

**Comment by miretskiy** [comment]
All needed prs merged.
