### ISSUE TITLE
explain (debug) in sql console returns OK and no output rows

### ISSUE THREAD

**Issue by 2torus** [cockroachdb/cockroach#4052]
This used to work, is it the intended behavior?

```
root@:15432> select * from spam;
+----+----------+
| ID |   text   |
+----+----------+
|  1 | "tobias" |
|  2 | "jaja"   |
+----+----------+
root@:15432> explain (debug) select * from spam;
OK
```

**Comment by mberhault** [comment]
Ah, that's me. I recently changed the CLI to look at the first word of the sql query to see if we need to perform an `Execute` or a `Query`. I left out `EXPLAIN`. oops. Will fix.
