### ISSUE TITLE
Human friendly hot ranges screen

### ISSUE THREAD

**Issue by bra-fsn** [cockroachdb/cockroach#40536]
**Is your feature request related to a problem? Please describe.**
There's `/_status/hotranges`, which tells us the hot ranges, but it's quite hard to use that information to gather really usable data (mapping rangeId back to exact tables etc).

**Describe the solution you'd like**
It would be nice to have some intuitive UI for this data, which could be used to identify possible application design problems (like when most of the operations happen in only a small amount of ranges).

Epic CRDB-2323

Jira issue: CRDB-5534

**Comment by piyush-singh** [comment]
This is forthcoming in a future release. We usually first expose raw endpoints and then consume them in the Web UI to expose them more generally. Will update here as we make progress

**Comment by irfansharif** [comment]
We've had customers ask for this, that asides this sort of thing would comes in pretty handy for diagnosing query distribution/perf analysis.

**Comment by glennfawcett** [comment]
Related issue [#58630](https://github.com/cockroachdb/cockroach/issues/58630)
