### ISSUE TITLE
storage: TestTxnRecordLifecycleTransitions:  TxnMeta.Timestamp.Logical: 434 != 436

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#40537]
From failed master build for which the issue poster didn't fire (https://github.com/cockroachdb/cockroach/issues/40414#event-2611186443)

https://teamcity.cockroachdb.com/viewLog.html?buildId=1470353&buildTypeId=Cockroach_UnitTests

**Comment by nvanbenschoten** [comment]
I wasn't able to reproduce this on a stale `master` but am able to reproduce it immediately under stress on the current `master`, so this must be new. I'll bisect.

**Comment by nvanbenschoten** [comment]
If I had to guess, I'd say it was #40518.
