### ISSUE TITLE
sql: show jobs doesn't round trip format

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#40534]
RSG found the following error when trying to format and parse a generated AST:

cannot parse output of Format: sql="SHOW JOBS WHEN COMPLETE SELECT error FOR SHARE", formattedSQL="SHOW JOBS SELECT error FOR SHARE WHEN COMPLETE": at or near "when": syntax error

**Comment by spaskob** [comment]
Thanks Matt, can you explain what RSG is?

**Comment by mjibson** [comment]
RSG is the random syntax generator. It crawls our sql.y file and executes randomly generated statements. It then calls .Format on those, parses the result, and verifies that it is the same as the original. The above statement failed that last part. Looks like something having to do with `WITH COMPLETE` is either being incorrectly dropped or added.

**Comment by spaskob** [comment]
Thank you, I will try to reproduce it with a unit test and fix it.
