### ISSUE TITLE
sql: expand wildcard (@*) to SHOW RANGES 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#40544]
@jseldess suggested we extend the wildcard syntax to SHOW RANGES:

>It would be great to be able to run a single show ranges statement for all indexes of a table:
```SQL
SHOW RANGES FROM INDEX movr.vehicles@*
```
>or for all partitions of a table:
```SQL
SELECT * FROM [SHOW RANGES FROM INDEX movr.vehicles@*] WHERE  NOT LIKE '%Prefix%';
```

**Comment by rohany** [comment]
how is this different from `SHOW RANGES FROM TABLE t`?

**Comment by jseldess** [comment]
`show ranges from table t` only lists the ranges for the primary index, as far as I understand. You need `show ranges from index x` for each secondary index as well.

**Comment by rohany** [comment]
Oh i see -- thats not how I imagined it working based on the name.

**Comment by jseldess** [comment]
Yeah, it's not super intuitive. Docs clarify, for now: https://www.cockroachlabs.com/docs/v19.1/show-experimental-ranges.html#synopsis

**Comment by rohany** [comment]
So i think this information right now is actually available, except `show ranges from database d` does not show the index name right now. Once that is added you would be able to do `select * from [show ranges from database d] where table_name='t'`

**Comment by jseldess** [comment]
Nice. But the `SHOW RANGES FROM INDEX movr.vehicles@*` syntax would better match what we've done for efficiently creating zone configs for multiple partitions of the same name.

**Comment by rohany** [comment]
yeah agreed

**Comment by asubiotto** [comment]
Based on the discussion on the linked PR, it seems like the new syntax is not going to be merged. Since this information can be obtained through other means, I'm closing this issue.
