### ISSUE TITLE
support for uuid-ossp extention? 

### ISSUE THREAD

**Issue by bhavyabhatg** [cockroachdb/cockroach#40586]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mattcrdb** [comment]
Hello @bhavyabhatg ,

Is this what you're looking for?

https://www.cockroachlabs.com/docs/stable/functions-and-operators.html#id-generation-functions

Thanks,
Matt

**Comment by bhavyabhatg** [comment]
Hi Matt, 
I was using postgress ORM and was trying to generate UUID using "uuid-ossp". I could generate uuid using gen_random_uuid() method and without using "uuid-ossp" extension.

**Comment by mattcrdb** [comment]
Glad to hear you figured it out!
