### ISSUE TITLE
exec: create unit tests for all operators

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#40634]
A bunch of operators are missing unit tests. This should be fixed.

Higher priority (these will run with `auto` vectorize setting):
- [x] `andOp`
- [x] `caseOp`
- [x] `orOp`
- [x] `bufferOp`
- `vecComparators` (I don't think it's worth writing unit tests for this one since it is tested via an ordered synchronizer and top K sort)

Lower priority (these will run only with `experimental_on` vectorize setting):
- [x] `rank`
- [x] `row_number`
- `joinerFilter` (I don't think it's worth writing unit tests for this one since it is tested via ON expression tests for merge joiner)
- [x] `mergeJoiner` with ON expressions
- [x] `hashJoiner` with ON expressions
- `windowSortingPartitioner` (I don't think it's worth writing unit tests for this one since it is tested via window functions when they have PARTITION BY clause and the operator itself is just a combination of sorter and an ordered distinct)

**Comment by asubiotto** [comment]
Can this issue be closed?

**Comment by yuzefovich** [comment]
There is one more PR that should be merged that will close this issue.
