### ISSUE TITLE
schema: job duration is different in the sql shell and webui

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#40640]
Schema change time length is different in the shell and webui.

WebUI:
![image](https://user-images.githubusercontent.com/22278911/64635708-407a6e80-d3ce-11e9-8c36-08e5fe27b41d.png)

SQL Shell:
![image](https://user-images.githubusercontent.com/22278911/64635693-3b1d2400-d3ce-11e9-990c-7b6862470b9f.png)

**Comment by lucy-zhang** [comment]
This is basically the difference between how long the job takes (as shown in the web UI) and how long the statement itself takes, right? I'm inclined to say this isn't much of a problem. (The only slightly suspicious thing is that the statement took 3 additional minutes, which I guess could point to a lot of retries?)

**Comment by spaskob** [comment]
@awoods187  are you able to repro the 3 minutes difference between the job runtime and the statement runtime?

**Comment by awoods187** [comment]
I wasn't able to reproduce this last week but I think I forgot to close the issue.
