### ISSUE TITLE
Bugs existing the data type Serial and the data type Int of the Data Types section in the official documentation

### ISSUE THREAD

**Issue by Quinceyzhang** [cockroachdb/cockroach#40664]
MY QUESTION
As we can see in the additional picture:
<img width="322" alt="bugs" src="https://user-images.githubusercontent.com/33934796/64679056-780c1800-d4ad-11e9-976a-bf47122b838b.png">

1. the type SERIAL  is expected to correspond to the type INT,
2. the type SERIAL 2 and SMALLSERIAL are expected to correspond to the type INT2,
3. the type SERIAL 4 and SMALLSERIAL are expected to correspond to the type INT4,
4. the type SERIAL 8 and BIGSERIAL are expected to correspond to the type INT8

but in my actual exercise, no matter what kind of types I chose when creating database, it always apperas type INT8 
![run](https://user-images.githubusercontent.com/33934796/64681354-244ffd80-d4b2-11e9-93b5-4bc230c0e43b.png)

As the picture above shows, I used the type SERIAL4 as my "id"'s type, however, when I checked the table after that, It became the type INT8，which is expected to be INT4 instead.

And,the question appears when using the type SERIAL ,SERIAL2, SERIAL4, SERIAL8 ,SMALLSERIAL and BIGSERIAL. ALL of them would became type INT8.

I wonder whether there are some errors in this part or not. Thank you!

**Comment by awoods187** [comment]
@Quinceyzhang thank you for reaching out to us. In order to use these serial variables, you must enable a cluster setting:
```
root@127.0.0.1:52961/movr> SET experimental_serial_normalization = sql_sequence;
SET

Time: 298µs

root@127.0.0.1:52961/movr> create table test2 (id SERIAL4 NOT NULL);
CREATE TABLE

Time: 19.379ms

root@127.0.0.1:52961/movr> show create table test2;
  table_name |                        create_statement
+------------+----------------------------------------------------------------+
  test2      | CREATE TABLE test2 (
             |     id INT4 NOT NULL DEFAULT nextval('test2_id_seq':::STRING),
             |     FAMILY "primary" (id, rowid)
             | )
(1 row)

Time: 15.768ms
```

I think we could improve our documentation to explain this a bit better. A bit above the spot you linke it mentions these [session variables](https://www.cockroachlabs.com/docs/v19.1/serial.html#modes-of-operation).

I'm going to close this issue and open another docs issue to make sure it's better understood that users must set these variables first.

**Comment by awoods187** [comment]
Docs issue: https://github.com/cockroachdb/docs/issues/5410
