### ISSUE TITLE
roachprod: "stop" for crdb nodes also stops async commands launched with "run"

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#40667]
**Describe the problem**

Running:
1. `roachroad start`
2. `roachprod run` in a separate shell with long-running command
3. `roachprod stop`

The `stop` in step 3 also stops the command in step 2.
I could not find a way to ask roachprod to start/stop crdb nodes without also impacting asynchronous commands that I wish to remain running.

**Expected behavior**

`roachprod stop` should only impact the crdb nodes, not other commands.

**Comment by knz** [comment]
Maybe related to #40597.

cc @petermattis @ajwerner

**Comment by petermattis** [comment]
There is a -tag flag that can be passed to run and stop to limit which
processes are affected. The details escape me at the moment and I’m AFK,
but I can track this down later if this isn’t enough to go on.

Using cgroups would be nicer underlying technology rather than env vars and
ps. Unfortunately I wanted roachprod to work on Mac OS X as well. Portable
handling of processes and groups is apparently really hard.

**Comment by knz** [comment]
Thank you I was not aware of `--tag`. I will try this next.

**Comment by knz** [comment]
Ok I confirm that `--tag` seems to work, with the following caveat: `roachprod stop` without `--tag` will stop all other processes ran with `roachprod`, including those ran with `--tag`. It is as if the lack of `--tag` is equivalent to `--tag *`.

**Comment by petermattis** [comment]
> Ok I confirm that --tag seems to work, with the following caveat: roachprod stop without --tag will stop all other processes ran with roachprod, including those ran with --tag. It is as if the lack of --tag is equivalent to --tag *.

Correct. I think that was intentional. I believe I'm the only user of `--tag` (and I only use it rarely), so those semantics could be changed if they are confusing.

**Comment by knz** [comment]
I did not find it confusing and it is actually useful.
Not sure how to more clearly reveal its semantics to educate other users.
