### ISSUE TITLE
sql: Get range ID for a specific row

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#40679]
Currently, you can see how a table maps to underlying key-value ranges (`show ranges`). But you can't see which range contains the data for a specific row. This ability would let users validate, for example, that when you change the partition value of a row (e.g., `chicago` to `new york`), we move that record to the correct partition.

**Comment by jseldess** [comment]
I suppose it's just as important to be see which partition a row belongs to, not just which range.

**Comment by jseldess** [comment]
Related internal issue: https://github.com/cockroachlabs/cs/issues/7

**Comment by rohany** [comment]
How do you imagine that the syntax for this looks like?

```
SHOW RANGE FOR ROW VALUES (x, y, z ...)
```

Also, I think showing the range is more important than the partition -- a row can be in a partition, but until the range splits the partition's constraints won't apply

**Comment by robert-s-lee** [comment]
@drewdeally what is your take on row vs partition?  There could be thousands of ranges.  Agree to check on a range is important.  From the operational side, a partition check would lessen the burden of checking each and every range of the partition.  Locations of index would also need to be considered.

**Comment by drewdeally** [comment]
At this point in time, I am more concerned about the pk.  I just need a simple method to track the row.

**Comment by awoods187** [comment]
We need this command to be able to show each rows range ids, node ids, and locality ids.  This recently came up with a customer for them to prove locations based on the GDPR
