### ISSUE TITLE
rocksdb: hot loop leading to slow range

### ISSUE THREAD

**Issue by roncrdb** [cockroachdb/cockroach#40690]
**Describe the problem**

Hot loop in rocksdb is creating billions of compactions, may be related to: 

https://github.com/facebook/rocksdb/pull/4496

Hot loop may be causing slow range which is causing point queries to a key in this range to take > 60s.  

Compaction count is -2014598338 which is fairly close to the -2^31 (min int) of -2147483648. 

This is expected to overflow if rocksdb is stuck in infinite compaction loop. 
looks like integer overflow

CRDB version 2.0.7

We have advised user to connect to suspicious node and run: 

`select crdb_internal.set_vmodule('rocksdb=3');`

**Expected behavior**
Compactions shouldn't be happening at such a frequent interval.

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[3680](https://cockroachdb.zendesk.com/agent/tickets/3680) has been linked to this issue.
