### ISSUE TITLE
sql: applying similar zone configs across many tables is cumbersome

### ISSUE THREAD

**Issue by solongordon** [cockroachdb/cockroach#40703]
Forked from #39357.

We've made it easier to apply zone configs to analogous partitions across a table and its indexes. However it's also common to have analogous partitions across many tables, and that still requires running `CONFIGURE ZONE` statements for every single table. It would be great to make this less cumbersome.

Quoting @andreimatei:
> I think a key thing here is to somehow tie together all the "north_america" partitions of different tables and have all of them point to a single "zone config". As it stands, zone configs are defined by a start and end key, so there's no such thing as different tables or partitions pointing to the same zone config. But there should be.
> One has to be able to edit the constraints/attributes of all north_america partitions at once, and code that deals with zone (e.g. reporting) should be able to report only one zone for all the north_americas.

**Comment by knz** [comment]
still current

**Comment by ajwerner** [comment]
The feels decreasingly current with the new multi-region abstractions and the ability to configure tables. I feel inclined to close this as we've found more opinionated views on multi-region configuration abstractions lately. @awoods187 close if you agree?

**Comment by awoods187** [comment]
i think we can. Note, we do want the optimizer to be able to connect tables with partitions in the same region (analogous to the above) but I think that's handled separately.
