### ISSUE TITLE
sql: add Peewee tests to CockroachDB nightly test suite

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#40718]
Peewee is a popular Python ORM for Postgres

Let's add Peewee tests to the CockroachDB nightly test suite

Jira issue: CRDB-5517

**Comment by jordanlewis** [comment]
I downloaded and ran the Peewee sample app with its postgres driver against CockroachDB, which worked fine:

http://docs.peewee-orm.com/en/latest/peewee/example.html

Interestingly, it looks like Peewee has already tried using CockroachDB in their testing, judging by 26257 in this file: 

https://github.com/coleifer/peewee/blob/master/bench.py#L5

**Comment by awoods187** [comment]
interesting--nice find!
