### ISSUE TITLE
sql: Add jOOQ tests to CockroachDB nightly test suite

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#40721]
jOOQ is a popular Java ORM
Let's add jOOQ tests to CockroachDB nightly test suite

Jira issue: CRDB-5515

**Comment by rohany** [comment]
It doesn't seem like jOOQ tests are open source -- https://github.com/jOOQ/jOOQ/blob/master/CONTRIBUTING.md

**Comment by jordanlewis** [comment]
We have official jOOQ support (https://github.com/jOOQ/jOOQ/issues/8545) - tests are done on their end. That plus the closed source nature means we can close this.
