### ISSUE TITLE
ui: add telemetry to track loads of prometheus and health check endpoints

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#40731]
We should start capturing telemetry via segment on the backend when users make requests to the `/_status/vars` and `/health` endpoints. 

Understanding the usage of `/_status/vars` will help us figure out whether metrics are consumed via the prometheus endpoint in place of or in addition to users using the admin UI. 

Understanding usage of `/health` can help us understand whether clusters in the wild are employing load balancers.

Pete V pointed out that these pages have no JS, so it is slightly unclear why we see some data in our telemetry from these endpoints - they should not be able to trigger page loaded events. This telemetry will need to be plumbed via the backend to properly trigger events when the endpoint is accessed.

**Comment by nstewart** [comment]
Following up on our #telemetry discussion -- this can use the features API since we already have a library to do this easily. we do not need Segment here
