### ISSUE TITLE
sql: move indexJoiner into joinReader

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#40749]
The join reader has two somewhat distinct "modes" of operation (index join and general lookup join). The index join mode has some limitations: it expects that the input stream starts with the PK columns in order, and is not capable of "passing through" other values - we may have values for other columns available but the index join has to get and decode those again.

As we remove the heuristic planner, we can lift some of the restrictions around `indexJoinNode` (e.g. allow arbitrary (non-`scanNode`) input) and it is becoming a bit of a pain to deal with the limitations.

We should unify these two modes and make sure that any index-join-specific optimizations are carried over and can be applied whenever we are doing an index join (e.g. #40748, #39471).

**Comment by asubiotto** [comment]
We're planning on getting rid of the `indexJoiner` processor and instantiate a `joinReader` instead. Both processors use the same spec. At that point I think we can delete the `indexJoinerNode`, does that sound good to you?

**Comment by RaduBerinde** [comment]
Yeah, that'd be great!

**Comment by RaduBerinde** [comment]
We would probably want to preserve the EXPLAIN output for index join, so we may want to plumb a flag just for cosmetic purposes.
