### ISSUE TITLE
storage: some system ranges appear as under-replicated in 3-node clusters

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#40742]
The default system zone config has a replication factor of 5. This causes the `system.replication_stats` report to consider these ranges underreplicated in 3 node clusters.
They don't appear as underreplicated in the respective timeseries (the one that powers the front page of the admin UI) though ; I think we have custom logic for that.

We probably have a similar problem with all ranges in a single node cluster.
cc @darinpp 

Jira issue: CRDB-5512

**Comment by knz** [comment]
we discussed this recently, and it's still current.
