### ISSUE TITLE
Datum is not always comparable, but it's possible to cause the comparison and crash CockroachDB

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#4075]
The Datum type `DTuple` is not [comparable](https://golang.org/ref/spec#Comparison_operators) because it contains a slice. Still, throughout the TypeCheck routines, we compare sentinel variables of Datum (`DummyInt`, `DummyTuple`, etc.) to check/work with expressions' types. Whenever these comparisons are made between incomparable types, the type checking will panic and bring down the server.

Examples of queries that will currently cause this to crash:
- `SELECT CASE true WHEN true THEN (4, 4) ELSE (2,3) END;` will break [this](https://github.com/cockroachdb/cockroach/blob/master/sql/parser/type_check.go#L111) and [this](https://github.com/cockroachdb/cockroach/blob/master/sql/parser/type_check.go#L121)
- `SELECT NULLIF((1,2), (3,4));` will break [this](https://github.com/cockroachdb/cockroach/blob/master/sql/parser/type_check.go#L369)

While these two cases could be fixed pretty easily for `DTuple`, these crashes are a symptom of a more serious issue, which arose when I introduced an incomparable [DDecimal](https://github.com/cockroachdb/cockroach/pull/4045#issuecomment-177754419) Datum type. With a "non-special" incomparable type, a number of Datum comparisons also have the potential to fail (e.g. [here](https://github.com/cockroachdb/cockroach/blob/master/sql/values.go#L60) and [here](https://github.com/cockroachdb/cockroach/blob/master/sql/table.go#L161)). The required fix to this would be to either to:

- Rethink our TypeChecking approach, potentially passing around [`reflect.Value`](https://golang.org/pkg/reflect/#Value)s instead of sentinel Datum values to signify Datum types. This is a fairly invasive change, and would require us to rework a number of functions we share between the type checking stage and the evaluation stage, like [`foldComparisonExpr `](https://github.com/cockroachdb/cockroach/blob/master/sql/parser/type_check.go#L592). The performance impacts of extensive use of reflection are also not clear at this point. Note that it would not be possible to pass around `reflect.Type`s (although this is what should be compared), because of the need for the contained types in containers like `DTuple` to be inspected and recursively compared using [`Value.Index`](https://golang.org/pkg/reflect/#Value.Index).
- Guarantee that two incomparable types are never compared directly. This would continue to allow the type checking phase to pass around `Datum` and continue to allow comparisons against "safe" sentinel values (like `DNull` and `DummyDecimal`). However, whenever comparing two unknown Datum (often results of sub-`TypeCheck` calls) or whenever comparing against unsafe datum types (we currently never do the latter), we would need to make the comparison indirectly. This could either be by comparing reflect types like `reflect.TypeOf(a) == reflect.TypeOf(b)` or by comparing type strings like `a.Type() == b.Type()`. This way feels a lot more hacky, but at the moment would only require four changes across the code base. Still, I'm wary about fixing this issue so indirectly.

**Comment by nvanbenschoten** [comment]
Another option would be to add some type of unique `.TypeId` trait to each `Datum` type (probably pulling from some private enum), and compare these values during type checking instead of interface values directly. Even in cases that previously work like dealing with `DBool`/`DummyBool`, this approach seems more sound, because if a true valued `DBool` was ever accidentally introduced during type checking, a comparison with `DummyBool` would return the unexpected result of unequal. This example holds true for all other `Datum` types except for `DNull`. An argument could be made that comparing the strings from `.Type` has the same effect as a `.TypeId` trait, but a `.TypeId` has a number of advantages, including being an integer/enum comparison instead of a string comparison, and having a uniqueness guarantee across all types, instead of probable uniqueness as a byproduct of the method's implementation.

**Comment by petermattis** [comment]
I'm a little worried about using `reflect.Type` for our type comparisons as it limits the types to what we can statically represent in Go (you cannot dynamically add new types at runtime in Go). 

As for the second option, how about adding some sort of `Datum.TypeEqual(other Datum)` method. Lots of places to fix, though.
