### ISSUE TITLE
make: .pb.go files are being rebuilt unnecessarily

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#40764]
Whenever I go to a more recent `master`, the first time I build, all the `.pb.go` files are regenerated. This takes non-trivial time (in fact, I believe the main reason for having the `.pb.go` files in the repo is to avoid rebuilding them). I am using Linux (it's possible that this doesn't happen on MacOS).

**Comment by jordanlewis** [comment]
I think the makefile is working as expected - I can't reproduce this when moving between SHAs on recent master. Do you have two shas that you can repro with that don't have changes to `.proto` files?

**Comment by RaduBerinde** [comment]
I think it happens when there are changes in the `.proto` files between the commits I'm syncing to. But it shouldn't unless I change some .proto files. If it's expected that it always rebuilds them, why are we even checking in `.pb.go` files?

**Comment by jordanlewis** [comment]
Oh I see what you mean... yeah that's weird.
