### ISSUE TITLE
Default PK results in incompatibility with Postgres (/keycloak)

### ISSUE THREAD

**Issue by Freeaqingme** [cockroachdb/cockroach#40771]
**Describe the problem**

I'm trying to run Keycloak against Crdb (built off the last commit in master). It uses these queries: https://issues.jboss.org/secure/attachment/12437411/keycloak-database-update.sql

First it creates all tables, like this:
```
CREATE TABLE keycloak.REALM_SOCIAL_CONFIG (REALM_ID VARCHAR(36) NOT NULL, VALUE VARCHAR(255), NAME VARCHAR(255) NOT NULL);
```

Table now looks like:
```
\d keycloak.REALM_SOCIAL_CONFIG
  column_name |  data_type   | is_nullable | column_default | generation_expression |  indices  | is_hidden  
+-------------+--------------+-------------+----------------+-----------------------+-----------+-----------+
  realm_id    | VARCHAR(36)  |    false    | NULL           |                       | {}        |   false    
  value       | VARCHAR(255) |    true     | NULL           |                       | {}        |   false    
  name        | VARCHAR(255) |    false    | NULL           |                       | {}        |   false    
  rowid       | INT8         |    false    | unique_rowid() |                       | {primary} |   true     
(4 rows)
```

Afterwards, Keycloak attempts to define a Primary Key:
```
ALTER TABLE keycloak.REALM_SOCIAL_CONFIG ADD CONSTRAINT CONSTRAINT_1 PRIMARY KEY (REALM_ID, NAME);
pq: multiple primary keys for table "realm_social_config" are not allowed
```

Now I understand that it would make a lot more sense if one would define the primary key while initially defining the table, and I do understand why Crdb doesn't like a second Primary Key, but the combination of these factors does result in an incompatibility with Postgresql. 

Maybe it's possible to automatically delete the original PK when the 'second' PK is defined, if the first one was defined implicitly? 

**Environment:**
Build Tag:    v19.2.0-alpha.20190606-2265-g6853dc0
Build Time:   2019/09/14 22:45:20
Distribution: OSS
Platform:     linux amd64 (x86_64-pc-linux-gnu)
Go Version:   go1.12.5
C Compiler:   4.2.1 Compatible Clang 3.8.0 (tags/RELEASE_380/final)
Build SHA-1:  6853dc0063072c9856800a2cfe0889accde69a86
Build Type:   development

**Comment by jordanlewis** [comment]
Thanks @Freeaqingme - currently we don't support changing the primary key (See #19141) so this is indeed impossible. We're likely going to begin to address this in our next major release. I'm going to close this as a duplicate, but feel free to keep responding here and I'll get back to you - or add a comment to the main issue.
