### ISSUE TITLE
sql: codify how to safely include docs URLs in sql errors

### ISSUE THREAD

**Issue by solongordon** [cockroachdb/cockroach#40799]
When errors are clearly due to user error, it would often be helpful to point the user to the relevant section of our documentation. However, this brings with it some risks around accidentally pointing users to irrelevant docs or a broken URL. @knz suggested we put some guardrails in place before making this a standard practice.

Relevant Slack discussion:

**Solon Gordon 10:53 AM**
How do folks feel about including links to our docs in error messages? For example I’m improving a particular message and thought this would be nice:
```
root@127.0.0.1:52342/movr> alter table users configure zone using constraints = 'ssd';
pq: invalid constraints format
HINT: See https://www.cockroachlabs.com/docs/v19.2/configure-replication-zones.html#scope-of-constraints
```
But it seems like we don’t do this much so I wasn’t sure if there was a reason for that. One concern might be link rot if the docs URLs change between versions.

**Jesse Seldess 10:58 AM**
I like this idea VERY much in principle, for helping devs where they need it, but I think the danger of links breaking are real, especially if we’re linking to specific sections of a page like that.
@knz has explored this to some extent. Raphael, do you have opinions/insights?

**Raphael 'kena' Poss:city_sunrise: 11:03 AM**
we had CI tests to verify the validity of doc URLs before.
~We had to disable them due to a defect in our CI configuration (which noone has found time to fix yet). So today the risk of URL breakage is very real, and we don't have guardrails.~
note that  the engineers/doc writers who will think about this need to understand that error objects get reused across multiple areas. This means that if one adds a link to a doc page thinking to cover a particular use case, they may be inadvertently pointing to that doc page for completely unrelated features that would emit the same error message.
I would strongly recommend to not consider this project a trivial task, and do some homework of either:
- drawing an inventory of which error objects get reused where, and ensure (via engineering process) that the assumptions made in doc are not modified in code inadvertently, OR
- ensure that the links are attached only on the "return path" of specific features, instead of annotating the error objects when they are constructed/defined, OR
- scope down this down to SQL syntax errors only (edited) 
all in all the work will be a combination of research, thinking about engineering process, design and only then implementation. You'll want both someone from docs, and an eng TL
also I'd recommend filing an issue for this and copy/paste this discussion there. Slack has poor memory.

**Jesse Seldess 11:13 AM**
Thanks, @knz. I figured you’d have insights :slightly_smiling_face:. Solon, would you be willing to open a cockroach issue for this, and provide your current example for context? I agree with Raphael that we need to think this through and have processes in place for this to work. ~I didn’t know, for example, that CI is no longer checking for broken docs links in cockroach builds.~

Jira issue: CRDB-5508

**Comment by otan** [comment]
there is a `docs.URL` now, but we have to now make some sort of linter that processes all `docs.URL` (probably enforce they are all static strings) and check they have a corresponding docs page. this should probably be a nightly lint test.
