### ISSUE TITLE
storage: paginate GC of abort span entries

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#40815]
A user running 2.0.7 ran into a range with 1.5GB of abort span entries in a range, which made processing the range by the GC queue constantly hit the 1 minute default queue processing timeout. Worse, the GC queue loads all the abort span entries in memory, which causes large mem use. Everything else the GC queue does is paginated, to protect against this kind of pathology.
https://github.com/cockroachdb/cockroach/blob/eeecc927a5b786e788d7ffefab441f6b09e5a11f/pkg/storage/gc_queue.go#L441

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[3610](https://cockroachdb.zendesk.com/agent/tickets/3610) has been linked to this issue.

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[5041](https://cockroachdb.zendesk.com/agent/tickets/5041) has been linked to this issue.

**Comment by ajwerner** [comment]
Let's close this because of https://github.com/cockroachdb/cockroach/pull/45444 given we have #50376 to track what's left.

**Comment by ajwerner** [comment]
@lunevalex was there something not tracked in #50376 we wanted to do here?

**Comment by lunevalex** [comment]
@ajwerner that was it, I saw @madelineliao PR linked to this issue, which is why I reopened it. I will close it back down.
