### ISSUE TITLE
CI: make it easier to navigate to the artifacts of a failed test (especially TestDockerCLI)

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#40822]
Today when TestDockerCLI fails it is unclear where to find the log files.
The direct output in the build log is missing/useless.

Even if we were to propagate the test's stderr, there are still interesting+important artifacts in the artifacts directory, but it's unclear where to find them.

The naive/simple method to click on the "Artifacts" tab at the top of the TC home page for a failed run is useless - this gives me only two (unrelated) crdb binaries.

The way I currently find the artifacts is as follows:

1. click the test name
2. click the little down arrow on the right of the test
3. click "show build log"
4. this brings up a page. ignore the build log itself, it's useless. Instead, scroll up back to the top of the page
5. click the "Artifacts" tab at the top
6. navigate to artifacts -> TestDockerCLI -> your test
7. look at the console-output.log and other log files.

At least @rohany and @irfansharif encountered this problem recently (and it took myself a *long while* to figure out).

I would prefer if a test failure would give me a link to the artifacts directory for the failed test directly.

(I actually want this to be done for every failing test, not just this one)

**Comment by knz** [comment]
cc @jordanlewis this is what I was explaining on the other issue.
cc @bobvawter as you wanted to be aware of things in this area.

**Comment by jordanlewis** [comment]
The thing that confused you is that the first link you clicked was probably the "Publish Bleeding Edge" job that triggers GitHub CI, which in turns triggers the Unit Tests job that contains TestDockerCLI. The artifacts for the first two are empty because they don't run any tests.

What you did is navigate down two layers in the dependency graph and then click the artifacts.

Perhaps an easier way then this would be to 1. click the Dependencies tab 2. click the Unit Tests job 3. click Artifacts.

**Comment by knz** [comment]
Thanks that's indeed a few steps less.

Is there a way go get a link to the artifacts in the drop-down menu next to a failed test?

**Comment by jordanlewis** [comment]
I don't see a way to add a link to the drop down menu without writing a plugin :/

**Comment by irfansharif** [comment]
Related anecdote: while investigating a roachtest failure earlier (https://github.com/cockroachdb/cockroach/issues/38785), I couldn't figure out where the artifacts generated post failure were to be found (I don't even know if TC collects this). I ended up simply running the roachtests directly to generate said artifacts. This took a lot longer than I'd have liked, the particular issue was/still is hard to repro.

**Comment by irfansharif** [comment]
I just tried following both sets of steps above to gather artifacts from https://teamcity.cockroachdb.com/viewLog.html?buildId=1446993&tab=buildLog, specifically for the `roachtest: acceptance/bank/cluster-recovery` failure. I only see 'No user defined artifacts for this build'. What am I doing wrong?

**Comment by jordanlewis** [comment]
Not sure - looks like the GCE roachtests aren't publishing artifacts? I don't know how the roachtest infrastructure works very well. The AWS ones always post artifacts it seem like.

**Comment by irfansharif** [comment]
Created #40830.
