### ISSUE TITLE
CI: GCE roachtests not publishing artifacts

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#40830]
From https://github.com/cockroachdb/cockroach/issues/40822#issuecomment-532268137.

While investigating #38785 earlier, I couldn't figure out where the artifacts generated post failure were to be found. Looking at teamcity.cockroachdb.com/viewLog.html?buildId=1446993&tab=buildLog, specifically the `roachtest: acceptance/bank/cluster-recovery` failure, I only see 'No user defined artifacts for this build'. It seems the GCE roachtests aren't publishing artifacts.

**Comment by kenliu** [comment]
needs further investigation
