### ISSUE TITLE
sql: UNION freely parallelizes mutations, causing brokenness

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#40853]
Currently, the UNION statement causes parallelism of its inputs. This is problematic in the case of mutations, which cannot be parallelized without causing problems. Here is an easy repro of something broken, and there's likely more:

```
root@127.0.0.1:50495/defaultdb> create table a (a int primary key);
CREATE TABLE

Time: 2.448ms

root@127.0.0.1:50495/defaultdb> select * from [insert into a values(1) returning a] union select * from [insert into a values(1) returning a];
pq: duplicate key value (a)=(1) violates unique constraint "primary"
root@127.0.0.1:50495/defaultdb> select * from [insert into a values(1) returning a] union select * from [insert into a values(1) returning a];
pq: duplicate key value (a)=(1) violates unique constraint "primary"
root@127.0.0.1:50495/defaultdb> select * from [insert into a values(1) returning a] union select * from [insert into a values(1) returning a];
pq: duplicate key value (a)=(1) violates unique constraint "primary"
root@127.0.0.1:50495/defaultdb> select * from [insert into a values(1) returning a] union select * from [insert into a values(1) returning a];
pq: transaction 5321953d-8dd2-4614-9dff-7c50ae97c373 with sequence 2 missing an intent with lower sequence 1
```

I think the resolution of this issue should be to remove the UNION parallelism, which exists because UNION has no processor equivalent in DistSQL and merely causes a synchronizer to be planned which operates concurrently. UNION is the last such construct in our system that I'm aware of, so removing this bad behavior should isolate us from this problem completely.

Another alternative (cc @RaduBerinde) would be to ban mutations in the inputs of a UNION.

**Comment by RaduBerinde** [comment]
In 20.1, all mutations will be hoisted up as CTEs and executed before the main query (CC @justinj). This is already the case when `WITH` is used - we will just convert the `[ .. ]` syntax to be syntactic sugar for defining and selecting from a CTE.

**Comment by RaduBerinde** [comment]
(that worked is tracked in #35060)

**Comment by jordanlewis** [comment]
Ah, very nice. Maybe we should live with this for now then.

**Comment by RaduBerinde** [comment]
If we want a small 19.2 change to disable mutations under union, it's very easy to do from the opt side.

**Comment by asubiotto** [comment]
I think this issue can be closed. Feel free to reopen if not.
