### ISSUE TITLE
log: support to archive log instead of delete it only

### ISSUE THREAD

**Issue by seekingua** [cockroachdb/cockroach#40861]
(edited: @knz 2020-01-09)

This issue is to propose expanding CockroachDB's log file handling with another feature from [`logrotate(8)`](https://linux.die.net/man/8/logrotate): compression of the rotated log files.

In a nutshell:

1. the current log file should remain uncompressed;
2. the last rotated log file should also remain uncompressed;
3. all previous rotated log files before that are compressed;
4. older files, including compressed files, whose size cause the directory to exceed the configured `--log-dir-max-size` are still removed, as currently.

That is, the rotation behavior should be extended to compress the previously-rotated log file.
For example, a directory listing would look as follows:

```
cockroach.kenax.kena.2020-01-02T15_46_38Z.044260.log.gz
cockroach.kenax.kena.2020-01-02T15_46_45Z.044269.log.gz
cockroach.kenax.kena.2020-01-02T18_55_28Z.062609.log.gz
cockroach.kenax.kena.2020-01-03T12_50_04Z.042125.log
cockroach.kenax.kena.2020-01-03T12_50_04Z.042125.log
cockroach.log@ -> cockroach.kenax.kena.2020-01-03T12_50_04Z.042125.log
```

This behavior would be opt-in and activated by `--log-compress-old-files`.

The  issue does not suggest introducing a maximum number of log files (as in the default `logrotate` behavior), i.e. we propose to keep  `--log-dir-max-size` parameter as main capacity control. 

The two features can then be combined by users to keep all files around, compressed, by providing `--log-compress-old-files --log-dir-max-size=1TB` (or some other large value).

Jira issue: CRDB-5505

**Comment by seekingua** [comment]
all code include in this pr #40835

**Comment by knz** [comment]
After careful consideration of the first implementation of #40835, we have found that unconditional replacement of the GC logic by compression logic did not provide ideal UX and was too surprising for users.

I have rewritten the issue description with our new understanding.

**Comment by seekingua** [comment]
@knz thx for reply, i'll re-implement it based on feature from logrotate(8)

**Comment by knz** [comment]
Thank you, please have a look at the new top level description in issue #40835 to clarify.

**Comment by knz** [comment]
oh sorry I was mistaken please ignore my last comment

**Comment by weisslj** [comment]
As a workaround, we now use this cronjob (as cockroach user), that compresses every non-opened logfile with `bzip2`:

```
47 9 * * * find /var/log/cockroach -type f -name "*.log" ! -exec fuser -s {} \; -exec bzip2 {} \;
```

Maybe it is useful for others!
