### ISSUE TITLE
nightly cluster test is broken

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#4086]
this is due to maxing out on AWS spot instances (right now we're at 20/20). I can't ascertain that the test itself would fail if it had instances to run on, but I thought I tried ~2wks ago during the day without issues.

We should figure out what to do with this test; we can scale it down, but it should still be able to run.
Similarly, nobody is currently able to start any AWS instances at all unless others terminate first.
We should do something about that as well.

@mberhault, any ideas?

**Comment by tamird** [comment]
Why do we have a limit on spot instances? :fire: :moneybag:

**Comment by mberhault** [comment]
That's just an Amazon thing.

**Comment by tamird** [comment]
Could we use different regions for different tasks? The limited is per
region.

**Comment by petermattis** [comment]
@mberhault Is this fixed now?

**Comment by mberhault** [comment]
yup. just didn't run last night due to connectivity problems. The fix isn't
merged though: https://github.com/cockroachdb/cockroach/pull/4280

**Comment by petermattis** [comment]
Fixed by #4280.
