### ISSUE TITLE
security: Generated passwords with lower bcrypt cost

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#40873]
Password authentication in databases differs in a number of ways from password authentication on the web:

* Each connection authenticates independently; there is no process by which the password is exchanged for a cheaper-to-verify token.
* Connections may be long-lived, but common practice is to use a connection pool which will create a lot of connections in a burst.
* Passwords are used for machine-to-machine authentication so they are more likely to be high-entropy (and stored in a config file somewhere).

We currently store passwords with bcrypt (using the default cost factor of 10). We've seen users accidentally DoS themselves by warming up connection pools. Furthermore, this limits our ability to rate-limit password authentication to prevent brute-force guessing. (This is one reason we ask users of our managed cloud service to specify an IP whitelist so their cluster isn't open to the whole internet. But many users are ill-prepared to do this and end up whitelisting the whole world anyway).

It should be safe to reduce the bcrypt cost factor for high-entropy passwords. A conservative approach to this would be to introduce a statement like `CREATE USER `foo` WITH GENERATED PASSWORD` (returning the password) to generate a long random password and store it with a lower bcrypt cost. (Or we could call these something like "access tokens" instead of "passwords", but they should still fit into the "password" part of the postgres authentication protocol)

**Comment by knz** [comment]
discussed with Ben last week.
For CockroachCloud, we're considering having CC console generate passwords randomly, then set its own bcrypt cost. It can be written to the db via either a direct write to `system.users`, or (later) using the new `CREATE USER WITH PASSWORD ENCRYPTION` clause introduced with the SCRAM work.

**Comment by JeffSwenson** [comment]
[Hashed password caching was recently added to the database](https://github.com/cockroachdb/cockroach/commit/2b93d882d93d9f69d4f6678def1046bdf1086306). It is no longer possible to change hashing difficulty by writing directly to the system.users table. The system.users write is not picked up until after the sql pods are restarted.

**Comment by rafiss** [comment]
The caching added in https://github.com/cockroachdb/cockroach/commit/2b93d882d93d9f69d4f6678def1046bdf1086306 supports invalidation. For example, see [line 210 of alter_role.go](https://github.com/cockroachdb/cockroach/commit/2b93d882d93d9f69d4f6678def1046bdf1086306#diff-f9fb03181c31106c692699de1a31bc3703d022c69e58eb190423ca46708b469eR210). When there is a write to `system.users` the cache can be invalidated.

**Comment by JeffSwenson** [comment]
I would like to use a lower difficulty for randomly generated passwords. The idea was we would hash the password outside of CRDB and write it directly to the system.users table. I see go APIs for invalidating the cache. Is there a way to invalidate the cache from the SQL API after writing the new password to system.users?

**Comment by ajwerner** [comment]
> The idea was we would hash the password outside of CRDB and write it directly to the system.users table.

Rather than writing directly to the table, we should add a builtin or syntax to use which will write to the table and increment the descriptor version and wait, the usual invalidation dance.

**Comment by rafiss** [comment]
@JeffSwenson have you seen https://github.com/cockroachdb/cockroach/pull/72579 ? It might be what you want.

**Comment by knz** [comment]
yes that PR was exactly meant for that purpose. Can I get a review on it please?

**Comment by knz** [comment]
We've achieved this in CC in the control plane and offset the cost server-side by upgrading to SCRAM.
