### ISSUE TITLE
Track performance changes of master over time

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#4090]
Currently the nightly jobs run benchmarks but those results are not persisted in a way to easily determine how performance is changing over time.

**Comment by dt** [comment]
@mjibson and I discussed briefly the various options for collecting and surfacing timings.

One proposal for a quick MVP:
1. Fire up an off-the-shelf image with graphite on aws/gcloud.
1. grep/awk numbers out of existing runs in `benchmarks.sh`, post to said graphite.
1. use graphite / grafana to render historical timings.

**Comment by tamird** [comment]
How about something simpler like emailing output of benchstat to previous
day?

**Comment by bdarnell** [comment]
You might also want to take a look at https://github.com/tobami/codespeed. It's designed for this sort of thing so it can match benchmark results to git revisions, etc. I don't have any firsthand experience with it, though.

**Comment by dt** [comment]
Nice, that looks like pretty much exactly what I wanted and it looks like it exposes an http API for posting results so should be pretty easy to hook into existing script.

**Comment by dt** [comment]
done: benchmarks.dev.cockroachdb.com
