### ISSUE TITLE
sql: unpermissioned users can run {CANCEL,PAUSE,RESUME} JOB

### ISSUE THREAD

**Issue by solongordon** [cockroachdb/cockroach#40916]
Our docs state that only admin users can cancel, pause, or resume jobs. This is true in the sense that non-admin users cannot run SHOW JOBS to see job IDs. However, there is no privilege check on the CANCEL JOB, PAUSE JOB, or RESUME JOB commands themselves, so if a user does discover a job ID (for instance through the Admin UI), there is nothing to stop them from running these commands.

**Comment by solongordon** [comment]
@awoods187 @rolandcrosby Thoughts on whether this is severe enough to fix for 19.2?

**Comment by rolandcrosby** [comment]
Definitely worth fixing. Thank you, Solon.

**Comment by awoods187** [comment]
Agreed
