### ISSUE TITLE
SQL: `GRANT ALL ON TABLE testdb.* TO readwrite` crashes server

### ISSUE THREAD

**Issue by marcuswestin** [cockroachdb/cockroach#4093]
Database started in dev mode:
```
./cockroach start --dev
```

Small script to connect and crash db node:
```
package main

import (
	"database/sql"

	_ "github.com/lib/pq"
)

func main() {
	db, _ := sql.Open("postgres", "postgres://root@localhost:15432?sslmode=disable")
	db.Exec(`CREATE DATABASE IF NOT EXISTS testdb`)
	db.Exec(`GRANT ALL ON TABLE testdb.* TO readwrite`)
}
```

DB node stack trace (top of it):
```
panic: interface conversion: parser.IndirectionElem is parser.StarIndirection, not parser.NameIndirection

goroutine 147 [running]:
github.com/cockroachdb/cockroach/sql/parser.(*QualifiedName).Table(0xc8201408a0, 0x0, 0x0)
	github.com/cockroachdb/cockroach/sql/parser/expr.go:436 +0x1d7
github.com/cockroachdb/cockroach/sql.(*planner).getTableDesc(0xc820197000, 0xc8201408a0, 0xc82017c360, 0x1)
	github.com/cockroachdb/cockroach/sql/table.go:192 +0x14d
github.com/cockroachdb/cockroach/sql.(*planner).getDescriptorFromTargetList(0xc820197000, 0x0, 0x0, 0x0, 0xc82049e188, 0x1, 0x1, 0x0, 0x0, 0x3200000032)
	github.com/cockroachdb/cockroach/sql/descriptor.go:183 +0x29b
github.com/cockroachdb/cockroach/sql.(*planner).changePrivileges(0xc820197000, 0x0, 0x0, 0x0, 0xc82049e188, 0x1, 0x1, 0xc820248cf0, 0x1, 0x1, ...)
	github.com/cockroachdb/cockroach/sql/grant.go:26 +0x93
github.com/cockroachdb/cockroach/sql.(*planner).Grant(0xc820197000, 0xc820455500, 0x0, 0x0, 0x1)
	github.com/cockroachdb/cockroach/sql/grant.go:74 +0x90
github.com/cockroachdb/cockroach/sql.(*planner).makePlan(0xc820197000, 0x6e64df0, 0xc820455500, 0x145601, 0x0, 0x0, 0x145649)
	github.com/cockroachdb/cockroach/sql/plan.go:111 +0x8ad
github.com/cockroachdb/cockroach/sql.(*Executor).execStmt.func1(0xece43123f, 0x32a5a22d, 0x59aafa0, 0xc820140801, 0x28)
	github.com/cockroachdb/cockroach/sql/executor.go:403 +0xd0
github.com/cockroachdb/cockroach/sql.(*Executor).execStmt.func2(0xc8200ad540, 0x1)
	github.com/cockroachdb/cockroach/sql/executor.go:466 +0x121
github.com/cockroachdb/cockroach/client.(*Txn).exec(0xc8200ad540, 0xc82065e3b8, 0x14)
	github.com/cockroachdb/cockroach/client/txn.go:405 +0x2b2
github.com/cockroachdb/cockroach/client.(*DB).Txn(0xc8202ae580, 0xc82065e3b8, 0x6e64d60)
	github.com/cockroachdb/cockroach/client/db.go:463 +0x15b
github.com/cockroachdb/cockroach/sql.(*Executor).execStmt(0xc8202ae580, 0x6e64df0, 0xc820455500, 0xc820197000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/cockroachdb/cockroach/sql/executor.go:463 +0x600
github.com/cockroachdb/cockroach/sql.(*Executor).execStmts(0xc8202ae580, 0xc82067e025, 0x3b, 0xc820197000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/cockroachdb/cockroach/sql/executor.go:318 +0x33d
github.com/cockroachdb/cockroach/sql.(*Executor).ExecuteStatements(0xc8202ae580, 0xc8204d601e, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/cockroachdb/cockroach/sql/executor.go:266 +0x5e5
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).executeStatements(0xc82007e000, 0xc82067e025, 0x3b, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x69ac101, ...)
	github.com/cockroachdb/cockroach/sql/pgwire/v3.go:550 +0x1fb
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).handleSimpleQuery(0xc82007e000, 0xc82007e038, 0x0, 0x0)
	github.com/cockroachdb/cockroach/sql/pgwire/v3.go:274 +0xc5
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).serve(0xc82007e000, 0x0, 0x0, 0x0)
	github.com/cockroachdb/cockroach/sql/pgwire/v3.go:234 +0xf21
github.com/cockroachdb/cockroach/sql/pgwire.(*Server).serveConn(0xc8202a41b0, 0x7c001b8, 0xc82049e068, 0x0, 0x0)
	github.com/cockroachdb/cockroach/sql/pgwire/server.go:200 +0x9b5
github.com/cockroachdb/cockroach/sql/pgwire.(*Server).serve.func1(0xc8202a41b0, 0x7c001b8, 0xc82049e068)
	github.com/cockroachdb/cockroach/sql/pgwire/server.go:109 +0x90
created by github.com/cockroachdb/cockroach/sql/pgwire.(*Server).serve
	github.com/cockroachdb/cockroach/sql/pgwire/server.go:114 +0x20a
```

**Comment by petermattis** [comment]
Sounds like a bug. @andreimatei can you take a look?

**Comment by andreimatei** [comment]
looking

**Comment by andreimatei** [comment]
So obviously it's a bug that we panic.
I think it's less clear what syntax we want to support. Postgres doesn't support the star (`GRANT ALL ON TABLE testdb.*`). Instead, they have another form: `GRANT ... ON ALL TABLES IN SCHEMA schema_name`. Of course, we don't have "schemas".

Btw, besides the syntax issue, we haven't implemented any support for multiple GRANT targets, those will result in an error being reported (there's various TODOs from Marc about it).

So @petermattis @mberhault what do you guys think we should do?

1) Fix the panic by having the parser reject the query - by changing the grammar to not use a `qualified_name_list`, but a new version of qualified name that only permits `<x>.<y>`, not `a.*`, `a@b`, `a[1]`, `a[1:5]`
https://github.com/cockroachdb/cockroach/blob/master/sql/parser/sql.y#L3449

2) Fix the panic by converting the assertion to a user error.

3) Actually support multiple targets and introduce the star-qualified database syntax (`<database>.*`) ?

**Comment by mberhault** [comment]
While I like the idea of globs, our internal storage for privileges does not allow them. Instead, we inherit privileges from higher objects (table inherits from database).
We could fix this by implementing #2939, although that one would be nice even ignoring the glob syntax.

We should however support multiple targets, and qualified names as well. eg: I think `GRANT x ON db1` does not work right now.

**Comment by petermattis** [comment]
What's the problem with the wildcard? I would imagine that `GRANT ALL ON TABLE testdb.*` which expand `testdb.*` into the list of tables in `testdb`. Unless there is some problem with doing this, my preference would be to support that syntax.

**Comment by mberhault** [comment]
I believe mysql's behavior is a little more extensive than that. `testdb.*` also applies to future objects matching the pattern.
We can definite do globs for the case you mention, but we can't currently handle the mysql-like one right now.

**Comment by petermattis** [comment]
Whoa, that MySQL behavior is surprising. I would expect `GRANT ALL ON TABLE testdb.*` to only apply to existing tables, not future tables, just as `chmod foo/*` only applies to existing files, not future files. I don't see any reason to follow the MySQL behavior here. Let's just expand the wildcard when performing the `GRANT` and apply the operation to all of the resulting tables.

**Comment by andreimatei** [comment]
ok let me see what I can do

**Comment by marcuswestin** [comment]
Nice!
