### ISSUE TITLE
cockroach crash and restart failed

### ISSUE THREAD

**Issue by shidayi** [cockroachdb/cockroach#40958]
cockroach is crashed when we Perform parallel transactions with six nodes.The degree is 200.

stack is
 F190920 07:59:04.045839 660 storage/replica_evaluate.go:302  [n1,s1,r108/1:/Table/14{1-2}] received 3 results, limit was 2
goroutine 660 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0xc00051e800, 0xc00051e8a0, 0x544f900, 0x1b)
 /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:1020 +0xd4
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x5c5c8a0, 0xc000000004, 0x544f954, 0x1b, 0x12e, 0xc000058b40, 0x3d)
 /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:876 +0x95a......

**Comment by jordanlewis** [comment]
@shidayi what version of CockroachDB were you using?

```
		if maxKeys != math.MaxInt64 {
			retResults := reply.Header().NumKeys
			if retResults > maxKeys {
				log.Fatalf(ctx, "received %d results, limit was %d", retResults, maxKeys)
			}
			maxKeys -= retResults
		}
```

@tbg looks like this was changed in January, any ideas?

**Comment by nvanbenschoten** [comment]
Hi @shidayi, do you mind expanding on what you found? How was your memory hardware responsible for this issue?
