### ISSUE TITLE
cli: flags for setting disk usage

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#4095]
We need a flag when starting a store to specify the maximum amount of disk usage, either as a percentage or a total size.

This will be very useful for testing as well as a feature that is probably wanted by most sysadmins.  
Also set a default of 95% so we don't completely choke machines.

**Comment by tamird** [comment]
Nit: by default I'd set aside 500MB or 5% of disk, whichever is less.

**Comment by BramGruneir** [comment]
Sure, I'm going to investigate what the industry standards are.

**Comment by JackKrupansky** [comment]
Is this per-store and the same for all stores?

**Comment by BramGruneir** [comment]
Sorry, I should have specified, per store.

**Comment by BramGruneir** [comment]
This is done.
