### ISSUE TITLE
sql: support DELETE FROM ... USING

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#40963]
Add support for the `USING` clause on `DELETE`, which allows joining multiple tables for a `DELETE` clause.

This appears similar to #7841, which tracked adding joins to `UPDATE`.

https://www.postgresql.org/docs/10/sql-delete.html

Epic: CRDB-5498

**Comment by CyborgMaster** [comment]
Now that #7841 is completed, any plans to support this as well?

**Comment by andy-kimball** [comment]
Radu, this would make a good intern project.

**Comment by wodka** [comment]
will this make it into 21.1? we are using fusionauth with cockroach as primary database and the seemingly only remaining problem are such queries

**Comment by RaduBerinde** [comment]
Unfortunately, it won't be in 21.1. Can you explain your usecase? Is it not possible to rewrite the query to use a subquery, eg `DELETE WHERE x IN (SELECT ..)` ?

**Comment by wodka** [comment]
We are running FusionAuth in k8 and want to use cockroach together with it. Only Problem seem to be with queries for social logins - https://fusionauth.io/community/forum/topic/950/cockroach-compatibility-problem-on-connector-signin

As FusionAuth is closed source I cannot rewrite the query there - and also no clue / if or when they would change it.

**Comment by RaduBerinde** [comment]
I see, thanks. It shouldn't be a lot of work, perhaps we can get it done for a 21.1.x update.

**Comment by donbowman** [comment]
This syntax is also used in apache druid:
`DELETE FROM druid_tasklogs USING druid_tasks WHERE task_id = druid_tasks.id AND created_date < $1 and active = false`

**Comment by wodka** [comment]
@yuzefovich is there a way to help get this into 21.2?

**Comment by yuzefovich** [comment]
Unfortunately, I think it's unlikely given that there is little time (about 5-6 weeks) left before the code freeze for 21.2 and we have our hands full.

**Comment by MSeal** [comment]
Would love to see it in 21.3 then :)

**Comment by yuzefovich** [comment]
cc @vy-ton

**Comment by z0mb1ek** [comment]
need this for using with fusionauth

**Comment by Qasim-Aziz** [comment]
i am also looking for this solution, i also want to use fusionauth with cockroachdb

**Comment by mgartner** [comment]
We're expecting to support `DELETE .. USING` in version 23.1.
