### ISSUE TITLE
`GRANT SELECT ON ALL TABLES IN` not working

### ISSUE THREAD

**Issue by marcuswestin** [cockroachdb/cockroach#4096]
With postgres 9.0+ we should be able to grant privileges on all tables in a schema/database, e.g

```GRANT SELECT ON ALL TABLES IN SCHEMA testdb TO readonly```

For reference, see line 4 in synopsis block of http://www.postgresql.org/docs/9.0/static/sql-grant.html.

**Comment by petermattis** [comment]
CockroachDB SQL != Postgres SQL. The docs, which are still being written, will make this clear. It is mildly confusing that our SQL grammar was based originally on the Postgres grammar.

**Comment by marcuswestin** [comment]
Fair enough :)
