### ISSUE TITLE
roachtest: 2.1 bit rot

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#40977]
Several roachtests fail when run on the 2.1 branch due to recent master-branch changes. These need to be fixed to be compatible with older versions.

- `acceptance/decommission`: sensitive to number of columns in `cockroach node decommission` output
- `acceptance/gossip/restart-node-1`: alters zone config on a system table that didn't exist in 2.1
- `splits/largerange/size=10GiB,nodes=3`: `show experimental_ranges`/`show ranges` rename
- `hibernate`: updates in #40479 weren't applied to 2.1 blacklist

**Comment by nvanbenschoten** [comment]
Closing, as the 2.1 branch is long gone.
