### ISSUE TITLE
sql: control automatic statistics on a per-table basis 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#40989]
Currently, automatic statistics are applied on a cluster level instead of a per-table basis. This can be problematic because it removes manual control of statistics for particular tables. We should consider allowing users to control automatic statistics on a per-table basis. Our defaults would still be cluster-wide as this would be an advanced tool for users to employ in conjunction with injecting statistics. 

Epic: CRDB-9059

Jira issue: CRDB-5496

**Comment by rytaft** [comment]
This is still relevant.

**Comment by yuzefovich** [comment]
cc @vy-ton
