### ISSUE TITLE
storage/engine: sstIterator should use pebble/sstable, not golang/leveldb/table

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#40998]
`sstIterator` is used by import for iterating over the contents of a range to generate MVCC stats. Currently it uses `golang/leveldb/table` for this purpose. That code is the basis for `pebble/sstable`, but has not seen any development in years. We should change this code to use `pebble/sstable` so we can get rid of the `golang/leveldb` dependency.

While we're in this area of the code, import writes the sstable to disk, then reads it into memory so it can iterate over it. We should be able to iterate over the table directly on disk.

**Comment by ajkr** [comment]
Tests are working now. Just wanted to write one thing that confused me along the way was that `InternalIterator.SeekGE` argument is a user key and return value is an internal key. Is there any guidance on how to think about/remember this? Maybe internal key is never passed as []byte?

**Comment by petermattis** [comment]
> Maybe internal key is never passed as []byte?

That's correct. Internal keys are never passed in encoded form. A `[]byte` always refers to a user key.

**Comment by ajkr** [comment]
Wow, the test failures were due to passing 0 as `dbNum` and `fileNum` to `sstable.NewReader` which caused cache key conflict. I didn't even consider a lone sstable reader would use block cache. Cache key conflict needs to be the first box on my debugging checklist...
