### ISSUE TITLE
sql: allow users to change the status of their own jobs

### ISSUE THREAD

**Issue by solongordon** [cockroachdb/cockroach#40991]
@RaduBerinde brought this up in the review for #40978. Right now we only allow admin users to cancel, pause, or resume jobs. It would be nice to also let non-admin users perform these actions for jobs they created.

Note that non-admins also can't run SHOW JOBS, although they can see jobs in the Admin UI. Maybe it would make sense to allow SHOW JOBS but only show their own jobs.

Jira issue: CRDB-5495

**Comment by rolandcrosby** [comment]
This ties into a broader idea of object ownership that we have not yet implemented, and which sometimes yields surprising results (e.g. not having permission to drop a table that you created). Something to be sure to consider as we plan the work for increasing granularity of permissions.

**Comment by knz** [comment]
see also related #44335

**Comment by amruss** [comment]
Closing: we're doing a rethink of the way we do permissioning across the board in 22.2, including the jobs system. This will no longer be relevant
