### ISSUE TITLE
changefeedccl: Add support for "AS OF SYSTEM TIME" to changefeeds

### ISSUE THREAD

**Issue by aayushshah15** [cockroachdb/cockroach#41006]
Based on offline discussion with @ajwerner.

Currently, changefeeds do not support `AS OF SYSTEM TIME`. While working on #40696, I discovered a bug in our nemeses testing for `sinklessFeed`. The test works like this (see `pkg/ccl/changefeedccl/cdctest/nemeses.go`: It creates two tables (call them `original` and `fprint`), creates a changefeed that watches `original`, triggers a bunch of random actions that potentially change `original`, applies the changes that the changefeed emits to `fprint`, and periodically checks that `fprint` hashes the same as `original`. One of the events triggered by the nemeses is `eventPause` which pauses and then immediately resumes the underlying changefeed. 

Since `sinkless` changefeeds don't have a `job id` associated with them, the current testing system simply closes connection on the running changefeed to pause it and creates a new changefeed during the `Resume` call. Now consider the following case: Before any `resolved` timestamp is emitted, a `delete` action is triggered for a row in `original`, `eventPause` is triggered before this `delete` is emitted by the running changefeed (and thus is not applied to `fprint`), and a new changefeed is instead created. Now this new changefeed will only emit the current state of the table `original` during its initial scan, and the `delete` action will never end up being applied to `fprint`, causing a test failure.

Note that restarting the changefeed with `cursor=original_stmt_time` doesn't achieve the intended behavior either because passing a `cursor` to `CREATE CHANGEFEED` skips the initial table scan, which causes elision of pre-existing table state that should be applied to `fprint` at the beginning.

While we can hack our current approach of testing this, with `AS OF SYSTEM TIME` we could simply relaunch the changefeed from the original statement's timestamp and achieve intended behavior. Adding support for `AS OF SYSTEM TIME` allows us to correctly pause and unpause (and test) `sinkless` changefeeds.

**Comment by ajwerner** [comment]
I don't know if this is a bug. I'm not even really sure I get it. I think you can only reliably resume from an emitted resolved timestamp. If the sinkless feed kept track of what had been resolved and used a cursor it seems like it would be fine. To implement the verification for the sinkless resume we need to keep track of the last resolved timestamp.
