### ISSUE TITLE
sql: add query to explain analyze

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#41039]
Sometimes, customers need help with their query performance. We frequently ask for an `explain analyze` but this does not include the query. We should make it easy for users to share with us all the relevant information.

I think we should add the query to the top of the explain analyze to make sure they are never separate.

**Comment by awoods187** [comment]
We should also backport this to 19.1

**Comment by yuzefovich** [comment]
I think we already have "Show SQL" button, so this issue could be closed, right?
