### ISSUE TITLE
sql: returning an error from Flow.Start() causes server to not stop

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#41052]
By applying a dummy patch that makes some errors be returned from `FlowBase.Start()`, I can cause a `TestServer` to block while stopping. Don't know what's going on. It could be an issue with this particular test that I'm mucking with, although I did a minimal look to check that that's not the case.
If one applies the patch below on `83eb885f21b68c96dbba59a2afbd1fb5bf58ab02` and then does 
`make testshort PKG=./pkg/sql/rowexec TESTFLAGS=-v TESTS=TestDrainingProcessorSwallowsUncertaintyError/orize=true/dummy=true`, you'll see that stopping the `TestServer's` stopper blocks indefinitely. Don't know why.

Assuming it's not a testing issue (if it is, I apologize for the noise), this seems bad. An error from setting up a flow should not have such consequences.

The patch generates an error for flows with no processors (dealing with such a flow is how I got here). I don't know why this test produces such flows (it only happens in the `vectorize_flow=true` subtest), and it seems dubious, but that's incidental to the issue at hand.

```
diff --git a/pkg/sql/flowinfra/flow.go b/pkg/sql/flowinfra/flow.go
index fb4d8c979e..85fb10ce8e 100644
--- a/pkg/sql/flowinfra/flow.go
+++ b/pkg/sql/flowinfra/flow.go
@@ -304,6 +304,10 @@ func (f *FlowBase) IsVectorized() bool {

 // Start is part of the Flow interface.
 func (f *FlowBase) Start(ctx context.Context, doneFn func()) error {
+       if len(f.processors) == 0 {
+               return errors.Errorf("!!!")
+       }
+
```

@jordanlewis for triage

Jira issue: CRDB-5491

**Comment by jordanlewis** [comment]
@asubiotto could you take a look at this please, thanks!

**Comment by yuzefovich** [comment]
I looked into this briefly, and it seems to me that having no processors on some nodes in a vectorized flow is expected. What happens here is that on remote node 2 (the one with no processors) we have `colBatchScan -> colrpc.Outbox`, and the flow does have a startable corresponding to the outbox, yet we don't have any processors. On node 1, however, we have
```
colrpc.Inbox -----
                 | -> unordered synchronized -> materializer
colBatchScan ----
```
and that `materializer` is the processor.

I don't understand why it would get stuck though. By returning an error when `len(f.processors) == 0` we don't set up the part of the flow that lives on node 2. I think I'd expect for 10 seconds timeout to cancel the set up of the components on node 1 because `Inbox` would not get a connection.

**Comment by yuzefovich** [comment]
I just applied a similar diff:
```
diff --git a/pkg/sql/flowinfra/flow.go b/pkg/sql/flowinfra/flow.go
index c8944fdad9a..5b3c0bcfabd 100644
--- a/pkg/sql/flowinfra/flow.go
+++ b/pkg/sql/flowinfra/flow.go
@@ -526,6 +526,9 @@ func (f *FlowBase) IsLocal() bool {
 
 // Start is part of the Flow interface.
 func (f *FlowBase) Start(ctx context.Context) error {
+       if len(f.processors) == 0 {
+               return errors.New("injected error")
+       }
        return f.StartInternal(ctx, f.processors, f.outputs)
 }
 
diff --git a/pkg/sql/rowexec/processors_test.go b/pkg/sql/rowexec/processors_test.go
index 3db5a23dff7..9004483a9f2 100644
--- a/pkg/sql/rowexec/processors_test.go
+++ b/pkg/sql/rowexec/processors_test.go
@@ -413,7 +413,9 @@ func getPGXConnAndCleanupFunc(
 
 func populateRangeCacheAndDisableBuffering(t *testing.T, db *gosql.DB, tableName string) {
        t.Helper()
-       _, err := db.Exec("SELECT count(1) FROM " + tableName)
+       _, err := db.Exec("SET distsql=off")
+       require.NoError(t, err)
+       _, err = db.Exec("SELECT count(1) FROM " + tableName)
        require.NoError(t, err)
        // Disable results buffering - we want to ensure that the server doesn't do
        // any automatic retries, and also we use the client to know when to unblock
@@ -428,6 +430,7 @@ func populateRangeCacheAndDisableBuffering(t *testing.T, db *gosql.DB, tableName
 // interesting to test is the integration between DistSQL and KV.
 func TestDrainingProcessorSwallowsUncertaintyError(t *testing.T) {
        defer leaktest.AfterTest(t)()
+       defer log.Scope(t).Close(t)
 
        // We're going to test by running a query that selects rows 1..10 with limit
        // 5. Out of these, rows 1..5 are on node 1, 6..10 on node 2. We're going to
```
and the test didn't get stuck.
