### ISSUE TITLE
metrics: windowed count of histogram lack one after first rotation

### ISSUE THREAD

**Issue by SutraHsing** [cockroachdb/cockroach#41056]
To audit if threre are many CREATE DATABASE operations in a short time, I use metric.histogram to record times of operation. For example, operating 10 times in 5 seconds means a dangerous behaviour.
I find a stange problem through unit test. 
In the first loop with 5 CREATE DATABSE, cumulative and windowed histogram return reasonable results of total count. After 5 seconds sleep, I do the second loop with another 5 CREATE DATABASE. Although cumulative histogram return total count with expected results, windowed histogram gives me five total counts, each of them one less than expected.

**Comment by SutraHsing** [comment]
After some trials, we find that total count of windowed histogram only refreshes when the next operation makes total count of the cumulative histogram records the sample.
Would you help me with this problem?

**Comment by jordanlewis** [comment]
Sorry we never saw this. These days an issue will be auto-triaged by a bot. I'll close this, on the off chance if you're still looking at this please include a code snippet that you were trying. thanks!
