### ISSUE TITLE
opt: Mutations that reference variables outside statement scope should error

### ISSUE THREAD

**Issue by andy-kimball** [cockroachdb/cockroach#41074]
Repro:
```
CREATE TABLE xy (x INT PRIMARY KEY, y INT);
CREATE TABLE xz (x INT PRIMARY KEY, z INT);
SELECT *
FROM xy
WHERE EXISTS (
  SELECT *
  FROM [UPDATE xz SET z=y WHERE 1=1 RETURNING x, z]
);
```

EXPECTED: This should give an error, since the `UPDATE` statement references the outer select.
ACTUAL: No error, empty results returned.

It's important that we return an error in this case, since otherwise we'll be unable to hoist all mutations to the top-level.

**Comment by knz** [comment]
As discussed in #41078 this particular query would be transformed as follows:

1. turn the `[...]` into a `with ...` at the same level
2. apply the rule "no correlated mutation inside with"

**Comment by awoods187** [comment]
Can we get this error into 19.2?

**Comment by RaduBerinde** [comment]
@justinj is this fixed?

**Comment by RaduBerinde** [comment]
Verified that is fixed.
