### ISSUE TITLE
primary key default value

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#4112]
When I create a table with a column explicitly set as primary key and then `show columns`, I see that null is permitted as primary key and it's the default value.

```
create table table1 (column_a int primary key, column_b string);

show columns from table1;
+------------+----------+------+---------+
|   Field    |   Type   | Null | Default |
+------------+----------+------+---------+
| "column_a" | "INT"    | true | NULL    |
| "column_b" | "STRING" | true | NULL    |
+------------+----------+------+---------+
```

I'm able to insert a row with null set explicitly:

```
insert into table1 values (NULL, 'aaa');
```

When I try that again, I get an error, since a row already exists with null as primary key:

```
insert into table1 values (NULL, 'aaa');
query error: pq: duplicate key value (column_a)=(NULL) violates unique constraint "primary"
```

So null seems to be ok as the primary key value as long as it's unique. But I'm confused about the defaulting behavior for the primary key:

After removing all rows with null as the primary key value, when I insert a row and explicitly request the default, it works fine:

```
insert into table1 values(DEFAULT, DEFAULT);

select * from table1;
+----------+----------+
| column_a | column_b |
+----------+----------+
| NULL     | NULL     |
+----------+----------+
```

But after removing that row and trying again, this time excluding the primary key column from the statement, I get an error:

```
insert into table1 (column_b) values ('aaa');
query error: pq: missing "column_a" primary key column
```

Now sure why that's happening?

cc: @petermattis, @knz

**Comment by petermattis** [comment]
From http://www.postgresql.org/docs/9.5/static/ddl-constraints.html: `Technically, a primary key constraint is simply a combination of a unique constraint and a not-null constraint`.

**Comment by tamird** [comment]
So the bug is that our primary keys don't mark constituent columns non-null?

**Comment by jseldess** [comment]
I wasn't sure if we were following postgres here (primary key = unique and not null) or doing our own thing (primary key = unique and nullable). Since I was able to set the primary key to null explicitly (I tested this, too) and by explicitly requesting the null default, I suspected we wanted something different than postgres.

So what do we want? unique and not null or just unique?

**Comment by petermattis** [comment]
We want primary keys to be unique and not null. That is both the Postgres and MySQL behavior. I think this is a bug in our primary keys right now.

**Comment by rlowe** [comment]
ISO/IEC 9075 defines PRIMARY KEY as follows:

"A primary key constraint is a unique constraint that specifies PRIMARY KEY. A primary key constraint is
satisfied if and only if no two rows in a table have the same non-null values in the unique columns and none of the values in the specified column or columns are the null value."

So, to echo what @petermattis said, both UNIQUE and NOT NULL are required for "expected" behavior

**Comment by tamird** [comment]
:wave: @rlowe
