### ISSUE TITLE
CopyFrom STDIN produces an error

### ISSUE THREAD

**Issue by holtrdan** [cockroachdb/cockroach#41120]
**Describe the problem**

When running the below command, an error is thrown
Command
COPY app_app (appid, appversion, name, published, datecreated, datemodified, license, description, meta) FROM stdin;
appcenter	1	App Center	t	2018-02-13 05:20:07.822+00	2018-02-13 05:20:09.031+00	oRIgWuw8ed5OmS98TSZFxocskOFXU0v3VPneM0k80NqSBK2r6RhNzTNTryZkuj4W	\N	\N
Error
CopyFrom not supported in extended protocol mode

**To Reproduce**

Run the command above from intelJ

**Expected behavior**
Be able to copy from STDIN

**Additional data / screenshots**

![image](https://user-images.githubusercontent.com/53190806/65682270-86803500-e052-11e9-89cb-871df00f58d5.png)

**Environment:**
 - CockroachDB version [e.g. 2.0.x] = 19.1.4
 - Server OS: [e.g. Linux/Distrib]
 - Client app [e.g. `cockroach sql`, JDBC, ...] IntelJ

**Additional context**
Unable to Load data from STDIN

Radu Berinde asked me to file a BUG

**Comment by RaduBerinde** [comment]
A workaround here is to add `&preferQueryMode=simple` to the JDBC URL.

**Comment by holtrdan** [comment]
Using PGSQL Commandline interface works as a workaround

**Comment by vitruvvius** [comment]
Seeing this still

**Comment by jillxuu** [comment]
still seeing this issue with cockroach single node , rust-postgres
