### ISSUE TITLE
Add recommendations for seamless transaction retries in Java services

### ISSUE THREAD

**Issue by kai-niemi** [cockroachdb/cockroach#41135]
Tracking issue on improving documentation guidance for transaction retries. This one focus on the Java platform and in particular services based on the Spring Framework ecosystem, AspectJ, JPA and Hibernate or JDBC. 

Related issues include https://github.com/cockroachdb/docs/issues/5476 and https://github.com/cockroachdb/docs/issues/4331.

Contention workloads may cause retry errors in CockroachDB which is a [working by design](https://www.cockroachlabs.com/docs/v19.1/transactions.html#transaction-retries) concept. A good practise is therefore to be prepared to capture these errors on the application side and simply repeat the same atomic operations over and over, preferably with exponential backoff.  

Implementing cross-cutting retry logic by using the mentioned Java frameworks is quite straightforward and can be made fully transparent and non-intrusive by using AspectJ and the Spring wrapping around that. 

Rather than spreading retry loops across the codebase, the alternative approach is to capture the retry exception errors codes with a so called "around" advice on the [transactional](https://docs.spring.io/spring/docs/current/spring-framework-reference/data-access.html#tx-decl-explained) join points (methods annotated with @Transactional). These advices are "weaved" in at config/runtime by the frameworks. The Aspect can then perform the retry loops in a single place preferably with exponential backoffs. All of this could be placed in a common library shared by multiple services.

When using Spring regardless of underlying ORM or plain JDBC repositories, it's common to use annotations for transaction demarcation like:

```java
@Transactional(propagation = Propagation.REQUIRES_NEW)
void foo(ClientRequest req) {
    ..
}
```

Using aspects to implement retries means the method signature can remain unchanged and no loops are needed in the method blocks. It prevents cluttering the codebase and also applies the retry logic consistently around every "transactional" method. Furthermore, its captured application server-side instead of being propagated up the stack, potentially all the way to the calling client that would need to do the retries instead. 

For even more control, there are also options to use meta-annotations for transactional method demarcation:

```java
@Inherited
@Documented
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.TYPE, ElementType.METHOD})
@Transactional(propagation = Propagation.REQUIRES_NEW, timeout = 10, isolation = Isolation.SERIALIZABLE)
public @interface TransactionBoundary {
    /**
     * @return maximum backoff timeout in seconds
     */
    int timeout() default 30;

    /**
     * @return maximum number of times to retry transaction if needed
     */
    int retryAttempts() default 120;
}
```
 
Then it could be made more explicit that a method is in fact a boundary that is supposed to start and end transactions.

```java
@TransactionBoundary
void foo(ClientRequest req) {
    ..
} 
```

**Comment by awoods187** [comment]
@jseldess and @rmloveland for review

**Comment by damienhollis** [comment]
@kai-niemi this is a good idea.  We were going to build an aspect that applied the retry logic to `@Transactional` annotated methods but I really like the idea of a meta annotation.

Were you planning on building this or just writing up documentation?

**Comment by rafiss** [comment]
Closing this since this covered in docs now: https://www.cockroachlabs.com/docs/stable/build-a-spring-app-with-cockroachdb-jpa.html#transaction-management
