### ISSUE TITLE
sql: updating a JSON document rewrites all the entries in its inverted index

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#41161]
.. instead of computing a delta, like we do for regular (non-inverted) index entries.
Code around here
https://github.com/cockroachdb/cockroach/blob/13905b11379e4c68a0b8b7119a7b7f9342c4aba2/pkg/sql/row/updater.go#L419-L418

**Comment by jordanlewis** [comment]
I'll fix this in a bit, I've been doing a bunch with inverted indexes.

**Comment by jordanlewis** [comment]
This got closed by #47354
