### ISSUE TITLE
Clarify whether PRIMARY KEY is required

### ISSUE THREAD

**Issue by JackKrupansky** [cockroachdb/cockroach#4117]
Postgres does not require that a table have a PRIMARY KEY:

"Relational database theory dictates that every table must have a primary key. This rule is not enforced by PostgreSQL, but it is usually best to follow it."

See:
http://www.postgresql.org/docs/9.5/static/ddl-constraints.html

Does or should CockroachDB enforce the presence of at least one PRIMARY KEY column in each table?

I haven't yet checked whether MySQL, Oracle, MS SQL Server, et al require a PK per se.

Personally, I'd prefer requiring a PK, but in any case, the rule should be explicit for CockroachDB.

**Comment by petermattis** [comment]
A PRIMARY KEY is not required for a table. To be more specific, if a PRIMARY KEY is not specified, one will be provided for you (sort of like a public defender in the US legal system).
