### ISSUE TITLE
ERROR: unimplemented: execute row count limits not supported: 10000 of xxxx

### ISSUE THREAD

**Issue by qinzl1** [cockroachdb/cockroach#41188]
Query CRDB through JDBC ，when result row count more than 10000 ，it can not fetch the data。

**Comment by jordanlewis** [comment]
This will be resolved in the upcoming 19.2 release.

**Comment by qinzl1** [comment]
@jordanlewis 
community version like v2.1.8 will resolved  this error

**Comment by jordanlewis** [comment]
This won't be fixed in 2.1. You'll have to upgrade to 19.2.
