### ISSUE TITLE
Support using the Postgres Adapter in Ruby/Rails 

### ISSUE THREAD

**Issue by darinpp** [cockroachdb/cockroach#41193]
**Is your feature request related to a problem? Please describe.**
We do support the Postgres wire protocol but we don't have all required tables/functions needed to support Ruby/Rails. This issue https://cockroachdb.zendesk.com/agent/tickets/3732 shows customer trying to run rake tasks and failing because we don't support `max_identifier_length` (see here https://www.postgresql.org/docs/8.1/runtime-config-preset.html). 

**Describe the solution you'd like**
Add support for `max_identifier_length` as well as the other 
runtime config presets. The amount of work is relatively small but will unblock Ruby/Rails users to use CockroachDB.

**Describe alternatives you've considered**
A quick and dirty patch is already provided in https://cockroachdb.zendesk.com/agent/tickets/3732 (and attached)
[crdb.zip](https://github.com/cockroachdb/cockroach/files/3671442/crdb.zip)

**Additional context**

**Comment by rafiss** [comment]
https://github.com/cockroachdb/activerecord-cockroachdb-adapter now has support for CockroachDB
