### ISSUE TITLE
sql: improve EXPLAIN developer expereince

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#41201]
Currently, CockroachDB has multiple permutations for EXPLAIN including Verbose, Opt, Types, DistSQL as well as the intersections of these permutations (e.g., Opt ENV). This can be confusing to customers and can make it difficult to drive customers to consistently use EXPLAIN--a primary introspection tool for use understanding query planning and execution. 

Developers can be unsure which EXPLAIN variation should be used as their primary troubleshooting tool.

This is a tracking issue to discuss folding more information into EXPLAIN so that it contains all of the commonly needed information used to introspect query performance.

**Comment by jordanlewis** [comment]
I think the original goal of this issue is done now.
