### ISSUE TITLE
changefeedccl: HTTP sink should set application/x-ndjson MIME type

### ISSUE THREAD

**Issue by rolandcrosby** [cockroachdb/cockroach#41211]
**Is your feature request related to a problem? Please describe.**
When the HTTP changefeed sink makes requests, it doesn't set the content-type HTTP header. This can cause consumers to mis-parse the data they receive.

**Describe the solution you'd like**
Content of requests is [newline-delimited JSON](http://ndjson.org/), so the content-type should be set to `application/x-ndjson`, per the [ndjson spec](https://github.com/ndjson/ndjson-spec#33-mediatype-and-file-extensions).

**Describe alternatives you've considered**
I couldn't find an agreed-upon mime type for [JSON Lines](http://jsonlines.org/) (the other nearly-identical one-JSON-file-per-line format), so figured `application/x-ndjson` was the most logical choice.

Epic CRDB-7748

Jira issue: CRDB-5477

**Comment by Gurio** [comment]
@rolandcrosby: is there any howto, which describes how to setup changefeed, and trigger requests?

**Comment by rolandcrosby** [comment]
Hi @Gurio, you can find basic instructions in [this guide](https://www.cockroachlabs.com/docs/v19.1/change-data-capture.html#create-a-changefeed-connected-to-a-cloud-storage-sink) from our docs. To have CockroachDB send data to an arbitrary HTTPS endpoint, you'd use `experimental-https://` as the URI scheme in your `create changefeed` statement, instead of `experimental-s3` or other cloud storage URI schemes.

**Comment by miretskiy** [comment]
This is very stale; Closing this for now; if there is desire to have this
functionality, we can reopen and prioritize issue appropriately.
