### ISSUE TITLE
changefeedccl: Improve error message when cursor predates table creation

### ISSUE THREAD

**Issue by rolandcrosby** [cockroachdb/cockroach#41210]
**Is your feature request related to a problem? Please describe.**
When creating a changefeed using the `WITH cursor` option, if the cursor timestamp predates the creation of the table being watched, the user will receive a misleading error message that the table does not exist:

```
root@127.0.0.1:52575/defaultdb> CREATE CHANGEFEED FOR TABLE foo INTO 'experimental-https://foo.com' WITH cursor = '1568920310686945044.0000000000';
pq: table "foo" does not exist
```

**Describe the solution you'd like**
It would be easier to understand the issue if the `table "foo" does not exist` error message were more clear that it's referring to the state of the world as of the cursor time. When a cursor is passed, perhaps the error message could say something like `table "foo" does not exist as of system time 1568920310686945044.0000000000`, or even `table "foo" does not exist as of the time specified in the cursor`.

Epic CRDB-2365

**Comment by miretskiy** [comment]
I'm pretty sure this was fixed.
