### ISSUE TITLE
storage/engine: port timeseries merge operator from C++ to Go

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#41228]
The timeseries merge operator is currently implemented in [`c-deps/libroach/merge.cc`](https://github.com/cockroachdb/cockroach/blob/master/c-deps/libroach/merge.cc). The current work to port MVCC to Pebble is relying on the C++ version which is ok for correctness, but undesirable from a performance and maintainability standpoint. This merge operator needs to be ported from C++ to Go for use by Pebble.

**Comment by ajkr** [comment]
Read the code yesterday. I didn't understand the optimization for deferring sorting.

During a partial merge, it avoids sorting by time and simply concatenates lists together to produce a result. So, a partial merge's result may not be sorted.

In a full merge, it assumes the base value (i.e., the `Put()` below the merge operands), if there is one, is sorted. The full merge combines the already sorted base value with the unsorted merge operands, sorting and merging them into the base value until it produces a final fully sorted result.

In RocksDB partial merge is used during compaction when we don't have a full view of all a key's merge operands. Meanwhile, full merge typically happens during a user read. It may also happen during some compactions, in particular ones to the bottommost level when we have a base value.

So, what I believe this optimization effectively does is defer work that could've happened in the background during compaction to instead happen in the foreground during user reads. Not only that, but if we had done the work during compaction it'd only have to happen once and we'd persist the result. By doing it on each user read we cannot persist the result so have to redo it every time.

Anyways, by moving to Pebble, we don't have the opportunity to port this optimization as there's only one type of merge and it'll have to sort. But I wonder if it has some benefit that I totally misunderstood.

Also do we currently write timeseries samples out of order, or is this for handling a potential future use case?

**Comment by petermattis** [comment]
> Also do we currently write timeseries samples out of order, or is this for handling a potential future use case?

I'm not sure, and don't know of anybody who would be sure. I think you'll have to do a bit of reverse engineering.

> Anyways, by moving to Pebble, we don't have the opportunity to port this optimization as there's only one type of merge and it'll have to sort. But I wonder if it has some benefit that I totally misunderstood.

Don't forget that we can extend Pebble's implementation of merge. Before doing that, I think it would be good to better understand what this optimization is doing and how effective it is. It sounds like you're saying the "optimization" might be having the opposite effect of what was intended. Is that correct?

**Comment by ajkr** [comment]
> It sounds like you're saying the "optimization" might be having the opposite effect of what was intended. Is that correct?

Yes, that is my guess. Let me try to see if there are other differences between a base value and a merge operand's value. So far it looked like just the sorted-ness and IMO it looks beneficial to drop that distinction.

**Comment by petermattis** [comment]
> Let me try to see if there are other differences between a base value and a merge operand's value. So far it looked like just the sorted-ness and IMO it looks beneficial to drop that distinction.

Definitely worthwhile to verify your reading with instrumentation of the code.

**Comment by ajkr** [comment]
Sorry I couldn't find how `storage/engine.TestEngineMerge` is skipped today. I ran `make test PKG=./pkg/storage/engine/ TESTS=TestEngineMerge TESTFLAGS="-count 1 -test.v"`, printing the engine being used for merges and gets, and saw Pebble was being used. Not sure if it can be disabled somewhere externally, but grepping the repo for `TestEngineMerge` did not turn up anything suggesting it's disabled.

**Comment by itsbilal** [comment]
That comment is stale now - we had skipped `TestEngineMerge` for pebble back in early October since the output of Pebble's merges wasn't the same as the output of RocksDB's merges. I recall it getting unskipped shortly after you fixed merge ordering (maybe in the same PR), which made the outputs match.

**Comment by ajkr** [comment]
Great, thanks for the info, then this issue is finished :).
