### ISSUE TITLE
roachtest: file different github issues when a test fails to start, from when it finds an error

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#41227]
The following issues are caused by an I/O timeout during bulk i/o, which prevent the test to proceed beyond its initialization stage:

- #38720 roachtest `clearrange`
- #41123 roachtest `clearrange`
- #41154 roachtest `import/tpcc`
- #41152 roachtest `restore2TB`

Although the cause of these failures is serious and needs its own investigation, it is immaterial to the main feature being tested by the various roachtests.

To facilitate triage and enable different team members to focus on specific issues (as opposed to the same investigation of a common cause by many team members), it would be useful to ensure that **roachtest files separate github issues depending on which phase of a test fails**.

**Comment by knz** [comment]
cc @andy-kimball @kenliu  - I don't know how to route this issue, can you provide advice?

**Comment by petermattis** [comment]
This looks like a duplicate of #33377. Can you add a message there with your observations of the pain not fixing this causes? I've hoping to find some time in the next month to address it, though I'm more than welcome for someone else to beat to it.

**Comment by knz** [comment]
Thanks peter I was not aware of this other issue.

Dup #33377

**Comment by kenliu** [comment]
this is now closed, but in the future you can route issues related to roachtest to the Developer Infrastructure Tracker project here: https://github.com/orgs/cockroachdb/projects/3

**Comment by knz** [comment]
thanks ken
