### ISSUE TITLE
roachtest: stop making "unexpected passes" in nightly ORM test create a Github issue

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#41226]
Found while investigating failures for the 19.2 beta release (#41128).

The roachtest hibernate failures often fly under the radar because the most common failure mode is "NNN unexpected successes" (something in Hibernate that was known to fail previously, now succeeds, because of an improvement in CockroachDB). Arguably these failures are low priority and only necessitate an update to the whitelist.

For example, the majority of the TC reports on issue #40538 are of this kind.

However today we have one run with `373 tests failed unexpectedly` also on the same issue #40538. **This is a more serious failure** that is not low priority any more.

It inconvenient for triage that both types of severity are reported in the same github issue. The roachtest issue reporter should be given separate github title prefixes for both types of failures.

Jira issue: CRDB-5475

**Comment by knz** [comment]
cc @jordanlewis @kenliu for triage.

**Comment by rafiss** [comment]
I have revised the title of the issue, because after discussion in the AppDev team, we decided that we don't want/need Github issues for "unexpected passes."

**Comment by vy-ton** [comment]
@rafiss Can this issue be closed?

**Comment by rafiss** [comment]
We haven't made this change yet and I think it would still be good to do.

**Comment by rafiss** [comment]
Update: we now feel that it's a good thing that we get notified when tests unexpectedly pass. We feel that our process has improved enough such that the automatic issue creation from that no longer causes too much noise.
