### ISSUE TITLE
Virtual Tables providing conflicting information on leases 

### ISSUE THREAD

**Issue by roncrdb** [cockroachdb/cockroach#41246]
User has lease preferences for a specific region (us-east-1) however when he queries the virtual table `system.crdb_internal.ranges` about 15-20% of the leases are in other regions. 

Here are the constraints and lease prefrences: 

```
| constraints = '{+region=eu-west-1: 3, +region=us-east-1: 3, +region=us-west-2: 3}',

| lease_preferences = '[[+region=us-east-1]]'
```

When querying `system.crdb_internal.gossip_node` it seems to fit more into how they expected their leases to be, most of them in us-east-1 

Why is there conflicting information from these two virtual tables? 

Queries that were inttially run: 

```
root@localhost:7101/defaultdb> select lease_holder, count(lease_holder) from system.crdb_internal.ranges where database_name='perftest' group by (lease_holder) order by lease_holder;
lease_holder | count

+--------------+-------+
1 | 12

3 | 10

6 | 10

7 | 10

8 | 9

9 | 10

11 | 10

20 | 11

27 | 9

root@localhost:7101/system> select node_id, locality from system.crdb_internal.gossip_nodes where node_id in (1,3,6,7,8,9,11,20,27);
node_id | locality

+---------+---------------------------------------------+
1 | {"az": "us-east-1c", "region": "us-east-1"}

3 | {"az": "eu-west-1b", "region": "eu-west-1"}

6 | {"az": "us-east-1d", "region": "us-east-1"}

7 | {"az": "us-east-1e", "region": "us-east-1"}

8 | {"az": "eu-west-1c", "region": "eu-west-1"}

9 | {"az": "us-east-1c", "region": "us-east-1"}

11 | {"az": "us-east-1c", "region": "us-east-1"}

20 | {"az": "us-west-2c", "region": "us-west-2"}

27 | {"az": "us-east-1d", "region": "us-east-1"}
```

Query from `gossip_nodes` that showed what he was anticipating: 

```
root@localhost:7101/defaultdb> select node_id, attrs, locality, ranges, leases from system.crdb_internal.gossip_nodes;
node_id | attrs | locality | ranges | leases
+---------+-------+---------------------------------------------+--------+--------+
1 | [] | {"az": "us-east-1c", "region": "us-east-1"} | 854 | 277
2 | [] | {"az": "eu-west-1b", "region": "eu-west-1"} | 827 | 2
3 | [] | {"az": "eu-west-1b", "region": "eu-west-1"} | 734 | 0
4 | [] | {"az": "us-east-1e", "region": "us-east-1"} | 846 | 278
5 | [] | {"az": "us-west-2b", "region": "us-west-2"} | 813 | 19
6 | [] | {"az": "us-east-1d", "region": "us-east-1"} | 824 | 279
7 | [] | {"az": "us-east-1e", "region": "us-east-1"} | 801 | 264
8 | [] | {"az": "eu-west-1c", "region": "eu-west-1"} | 814 | 13
9 | [] | {"az": "us-east-1c", "region": "us-east-1"} | 798 | 271
10 | [] | {"az": "us-east-1e", "region": "us-east-1"} | 821 | 265
11 | [] | {"az": "us-east-1c", "region": "us-east-1"} | 821 | 260
12 | [] | {"az": "eu-west-1c", "region": "eu-west-1"} | 852 | 0
13 | [] | {"az": "eu-west-1a", "region": "eu-west-1"} | 810 | 5
14 | [] | {"az": "eu-west-1c", "region": "eu-west-1"} | 814 | 0
15 | [] | {"az": "us-west-2a", "region": "us-west-2"} | 823 | 1
16 | [] | {"az": "us-west-2a", "region": "us-west-2"} | 857 | 5
17 | [] | {"az": "eu-west-1b", "region": "eu-west-1"} | 856 | 2
18 | [] | {"az": "eu-west-1a", "region": "eu-west-1"} | 837 | 5
19 | [] | {"az": "eu-west-1a", "region": "eu-west-1"} | 819 | 1
20 | [] | {"az": "us-west-2c", "region": "us-west-2"} | 833 | 7
21 | [] | {"az": "us-east-1d", "region": "us-east-1"} | 847 | 277
22 | [] | {"az": "us-west-2b", "region": "us-west-2"} | 812 | 5
23 | [] | {"az": "us-west-2c", "region": "us-west-2"} | 824 | 3
24 | [] | {"az": "us-west-2b", "region": "us-west-2"} | 855 | 1
25 | [] | {"az": "us-west-2a", "region": "us-west-2"} | 789 | 8
26 | [] | {"az": "us-west-2c", "region": "us-west-2"} | 814 | 10
27 | [] | {"az": "us-east-1d", "region": "us-east-1"} | 808 | 269
(27 rows)
```

**Comment by solongordon** [comment]
@rohany Did you encounter anything like this during your recent work?

I took a short initial look and didn't see an obvious reason that these outputs shouldn't agree. I wonder if the `ranges` table is susceptible to stale leaseholder caches.

**Comment by rohany** [comment]
I've never seen anything like this either

**Comment by solongordon** [comment]
I'll take a deeper look. @roncrdb would it be possible to have the user restart the node they're querying against and then run the `ranges` query again? That would help suss out if the problem is related to caching.

**Comment by andreimatei** [comment]
> I wonder if the ranges table is susceptible to stale leaseholder caches.

Don't think so. Looking at the view definition you can see that it uses the `crdb_internal.lease_holder()` builtin, which sends a `LeaseInfo` request. That request is routed to the leaseholder or, in case it's running in an `ReadConsistency: roachpb.INCONSISTENT` batch, any replica (but that does not appear to be the case for the builtin).

@roncrdb, can you find an example range that's not where it should be according to `crdb_internal.ranges` and then look at the range report in the Admin UI and see what that one says?

And I got lost in the queries you provided; can you sum things and highlight the smoking diff? (the `gossip_nodes` refers to all ranges; the query you had from `crdb_internal.ranges` filter for one database).

**Comment by roncrdb** [comment]
@andreimatei 

I reached out to the user, he has been a bit busy these last few days so he hasn't been able to get back to me, but as soon as he does I'll update you.

**Comment by ajwerner** [comment]
Closing as stale.
