### ISSUE TITLE
sql: use the CBO to auto-detect needed indexes/unnecessary indexes 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#41259]
The CBO is an incredible tool for query planning. It's capable of evaluating hundreds of logically equivalent query plans through its memo structure by representing a forest of query plans compactly so that we can explore alternative query plans efficiently.

The CBO could create virtual indexes on all of the columns in the table and detect if they lead to dramatically improved query plans through evaluating the new plans in the memo against what would be currently planned. 

The opposite is true as well. The CBO could detect if an index is rarely helpful in picking the best query plan by virtually removing it and seeing if it degrades the available query plans. 

One method of engaging this behavior could be something on a per-query basis like:

EXPLAIN (INDEXES) QUERY

The output would be a dif of adding or removing indexes in the response to the client.

We could also run this automatically with heuristics and surface warnings in the webui. For example, run on any query that takes longer than X or is run as frequently as Y. 

Jira issue: CRDB-5470

**Comment by awoods187** [comment]
@andy-kimball and @RaduBerinde here is a mini-write up of this idea

**Comment by rmloveland** [comment]
Was looking for an issue like this!  A variant of this idea that I would love to have when writing SQL is:

- Create a session setting like "sql.enable_developer_style_warnings" or so (similar to `gcc -Wall` in spirit)
- When in this mode, return CRDB-specific ["Class 01 - warning" error codes](https://www.postgresql.org/docs/9.4/errcodes-appendix.html) to the client that warns when queries that are likely to affect performance are sent
- e.g., `01009 - no covering index` or `0100A - result set greater than 500 rows` or `0100F - full table scan` (the first two cases are specifically mentioned in Andy K's "Optimizing OLTP queries" doc)

**Comment by Bessonov** [comment]
I think it could be a great first step. Why don't get it further and let crdb automatically create or remove indexes on tables, sort of auto-tuning?

**Comment by jordanlewis** [comment]
We're accomplishing this via index add and drop recommendations now. 🎉
