### ISSUE TITLE
sql: Support aggregate functions for statistics

### ISSUE THREAD

**Issue by rohany** [cockroachdb/cockroach#41274]
Postgres has a good number of aggregate functions for statistics that we currently don't support -- https://www.postgresql.org/docs/9.1/functions-aggregate.html. These functions are offered by Django.

To implement these, add your code to `pkg/sql/sem/builtins/aggregate_builtins.go`

- [x] corr()
- [x] covar_pop()
- [x] covar_samp()
- [x] regr_avgx()
- [x] regr_avgy()
- [x] regr_count()
- [x] regr_intercept()
- [x] regr_r2()
- [x] regr_slope()
- [x] regr_sxx()
- [x] regr_syy()
- [x] regr_sxy()

**Comment by kaustubhkhare** [comment]
Hi @rohany @jordanlewis, can I pick up this issue?

**Comment by rohany** [comment]
Go ahead, I don't think anyone has claimed it!

**Comment by nnovoice** [comment]
Hi @kaustubhkhare, have you started working on this already?

**Comment by kaustubhkhare** [comment]
@nnovoice yes, I'm working my way through the code right now

**Comment by hueypark** [comment]
@rohany Can you complete the item `corr()`?

**Comment by mneverov** [comment]
hi, i'd like to work on this

**Comment by obahareth** [comment]
Hello, I'm going to work on `regr_avgx` and `regr_avgy` (in separate PRs of course).

**Comment by yuzefovich** [comment]
Hey @obahareth, are you still working on `regr_avgx` and `regr_avgy`? If not, maybe @mneverov could pick it up to finish off this issue?

**Comment by obahareth** [comment]
Hey @yuzefovich, I'm sorry I delayed this. I initially started when I had some time off and thought I could finish it then but I wasn't able to.

I think I managed to finish the regr_avgx part, I'll push a PR and tweak it based on your review and leave the Y version of it to @mneverov perhaps?

**Comment by yuzefovich** [comment]
@mneverov only `regr_avgy` remains here, are you interested in finishing off this issue? :)

**Comment by mneverov** [comment]
@yuzefovich sure, thanks!
