### ISSUE TITLE
util/log: report log dir in log.Fatal output

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#41287]
When logictests logs are redirected and a `log.Fatal()` happens, you're left in the dark about where the logs are.
We have code that prints some dirs after a panic, but that doesn't run after `log.Fatal()`. 
https://github.com/cockroachdb/cockroach/blob/c097a16427f65e9070991f062716d222ea5903fe/pkg/util/log/test_log_scope.go#L120

Can we print the logs dir in the beginning of the tests?

**Comment by jordanlewis** [comment]
Realistically @andreimatei, no one's going to get to this one unless they really want it (is that you?) so I'm taking it out of this project board. I also think we should close issues like this, but I'll leave that up to you.

**Comment by knz** [comment]
It's reasonable to take it out of SQL. This is purely a logging issue.

log.Fatal should report the location of the logging directory (in case
it's been redirected via the log scope).

I'll take it.

-- 
Raphael 'kena' Poss
