### ISSUE TITLE
sql: Support comparisons between arrays

### ISSUE THREAD

**Issue by rohany** [cockroachdb/cockroach#41280]
Postgres arrays allow for comparison operators (<, >, ...) -- https://www.postgresql.org/docs/9.2/functions-array.html. These are used by Django as well.

**Comment by rohany** [comment]
Additinonally, we would want to support the IN / NOT IN operators.

**Comment by jordanlewis** [comment]
We finished this one, right @rohany?

**Comment by rohany** [comment]
yup
