### ISSUE TITLE
sql: Support `unaccent()`

### ISSUE THREAD

**Issue by rohany** [cockroachdb/cockroach#41299]
`unaccent` is a text search module that removes accents from text -- https://www.postgresql.org/docs/9.6/unaccent.html. We currently don't support this, and it occurs in Django's postgres tests.

**Comment by elliotcourant** [comment]
What would represent a `$SHAREDIR` in the context of Cockroach? 

> RULES is the base name of the file containing the list of translation rules. This file must be stored in $SHAREDIR/tsearch_data/ (where $SHAREDIR means the PostgreSQL installation's shared-data directory).

Would this simply be in whatever the data directory is for Cockroach and then in a tsearch_data folder? Or should a flag or env variable be respected?

**Comment by rohany** [comment]
Hmm, not sure about this. Would a folder in `nodelocal` make sense @jordanlewis ?

**Comment by jordanlewis** [comment]
We should start by implementing `unaccent` using the hardcoded default Postgres rules. I don't like the idea of adding customizability here unless it's strictly necessary. If we do need it, we should implement it with a system table, not a file.

**Comment by mknycha** [comment]
Hi! I would like to work on this one.
There is just one thing I would like to clarify: from what I have checked `unaccent` dictionary in PostgreSQL has ~1500 keys, is that ok to hardcode it? If not, I would appreciate some point for reference on how to add system tables, as the codebase is new to me.

**Comment by otan** [comment]
i think it is ok to hardcode :)

**Comment by jordanlewis** [comment]
Closed by #54628. Thanks @mknycha!
