### ISSUE TITLE
sql: Support `using btree` postgres index syntax

### ISSUE THREAD

**Issue by rohany** [cockroachdb/cockroach#41294]
Postgres allows for users to specify the kind of index they want when creating an index. The postgres btree index type is similar to the indexes we currently create, but we just don't support the `using btree` syntax.

**Comment by jordanlewis** [comment]
I think this is actually already supported.

```
root@127.0.0.1:64872/defaultdb> create table a (a int);
CREATE TABLE

Time: 2.459ms

root@127.0.0.1:64872/defaultdb> create index on a using btree(a);
CREATE INDEX

Time: 64.562ms
```

**Comment by rohany** [comment]
hmm the error message made it seem like we didn't -- i'll take another look at it.

**Comment by knz** [comment]
I'd bet that the test is trying to create a b-tree index on a column that is not indexable in CockroachDB (array or JSON for example).

That's because CockroachDb does not actually use b-tree indexes, it uses LSM indexes. We're lying when we say we support B-trees.

**Comment by rohany** [comment]
I misread the output. The issue is this -- we don't support this `CREATE INDEX "integer_array_btree_fillfactor" ON "postgres_tests_charfieldmodel" USING btree ("field")WITH (fillfactor = 80)` "with fillfactor" condition. Based on this information about the argument https://www.postgresql.org/docs/9.3/sql-createindex.html it doesn't look like something we would support anyway

**Comment by awoods187** [comment]
Should we have some kind of noop here? Or will this fall into the category of need to be replaced with a CRDB dialect?

**Comment by jordanlewis** [comment]
I would be fine treating fillfactor as noop, but I doubt that it's really that important - I bet you have to explicitly ask for a fillfactor in django to get one. I think we're okay leaving this unimplemented.

**Comment by ASalihov** [comment]
Can anyone explain me why if we try generate sql for existing index we always get script like `CREATE INDEX "IX_index_name" ON table.name **USING btree** (column_name);` ?
[Here](https://www.cockroachlabs.com/docs/stable/create-index.html) is mentioned that it need **for compatibility with third-party tools**. But what does this mean exactly?
Thanks for any responses.

**Comment by knz** [comment]
I would agree that we don't need to output "USING btree" in the output of SHOW CREATE (pg does not have SHOW CREATE).

**Comment by knz** [comment]
@jordanlewis @otan I think the last comment by @ASalihov is something different from the original description. I believe the issue as originally filed can be closed, but the commenter is relating something legitimate. WDYT?

**Comment by otan** [comment]
Yep it's done!

**Comment by knz** [comment]
@otan what do you say about the idea that **we do not need to print out USING btree** when pretty-printing the AST in SHOW CREATE?

**Comment by otan** [comment]
i believe so -- PostgreSQL does too.

```

otan=# create table customers(a int primary key, b int);
CREATE TABLE
otan=# create index on customers (b);
CREATE INDEX
otan=# SELECT i.relname AS name,
       ix.indisprimary AS PRIMARY,
       ix.indisunique AS UNIQUE,
       ix.indkey AS indkey,
       array_agg(a.attnum) AS column_indexes,
       array_agg(a.attname) AS column_names,
       pg_get_indexdef(ix.indexrelid) AS definition
FROM pg_class t,
     pg_class i,
     pg_index ix,
     pg_attribute a
WHERE t.oid = ix.indrelid
AND   i.oid = ix.indexrelid
AND   a.attrelid = t.oid
AND   t.relkind = 'r'
AND   t.relname = 'customers' -- this query is run once for each table
GROUP BY i.relname,
         ix.indexrelid,
         ix.indisprimary,
         ix.indisunique,
         ix.indkey
ORDER BY i.relname;
      name       | primary | unique | indkey |     column_indexes      |              column_names               |                               definition
-----------------+---------+--------+--------+-------------------------+-----------------------------------------+------------------------------------------------------------------------
 customers_b_idx | f       | f      | 2      | {2,-6,-5,-4,-3,-2,-1,1} | {b,tableoid,cmax,xmax,cmin,xmin,ctid,a} | CREATE INDEX customers_b_idx ON public.customers USING btree (b)
 customers_pkey  | t       | t      | 1      | {-6,-5,-4,-3,-2,-1,1,2} | {tableoid,cmax,xmax,cmin,xmin,ctid,a,b} | CREATE UNIQUE INDEX customers_pkey ON public.customers USING btree (a)
```
