### ISSUE TITLE
sql: determine flakiness for and unskip sqlalchemy tests in examples-orms

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#41295]
The SQLAlchemy tests in examples-orms were flaky at one point in time. Determine why they're flaky and unskip if possible.

**Comment by solongordon** [comment]
The tests aren't currently skipped as far as I can tell. There were some issues in the past but they were resolved by @bobvawter in https://github.com/cockroachdb/examples-orms/pull/59.
