### ISSUE TITLE
Export into CSV query hangs, completes successfully when run on its own.

### ISSUE THREAD

**Issue by mattcrdb** [cockroachdb/cockroach#41302]
**Describe the problem**

A customer’s csv export is hanging on 19.1.4. The query contains some joins. The query itself executes in 15ms - however returns 0 rows. we’ve tested a much more naive version of the same query (which also returns 0 rows), and the export does not hang (it succeeds) 

DDL, Simple and more complex queries and explains are in https://cockroachdb.zendesk.com/agent/tickets/3605 due to privacy. 

**Environment:**
 - CockroachDB version 19.1.4
 - Server OS: [e.g. Linux/Distrib]
 - Client app: Cockroach sql

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[3605](https://cockroachdb.zendesk.com/agent/tickets/3605) has been linked to this issue.

**Comment by dt** [comment]
before 19.2, `EXPORT` doesn't use the optimizer. Does the query complete in 15ms _with the optimizer off_?

If so, we'd need a debug zip ideally (or at the very least a goroutine dump on every node) to debug why it is hanging.

**Comment by mattcrdb** [comment]
From the ticket:
```
The query performs about the same with or without the optimizer
(in fact, potentially faster without the optimizer).
```

[Here](https://cockroachlabs.sendsafely.com/receive/?thread=USME-355E&packageCode=LgHkbM3JSnPyTyICvhC2vGaqY9zohWl60nW03vJu0Zw#keyCode=zNcqYIzUD_KEkaPBd47udGHwP9iKKe7K1SnR0x0Irbk) Is the debug zip. The oncall credentials will work for access.

Thank you,
Matt

**Comment by dt** [comment]
Huh, looking at this debug zip, it looks like it was grabbed _after_ the EXPORT was cancelled? I don't see it in the running queries. Ideally we'd grab one _while_ the EXPORT is hung (i.e. after 20-30s) so that we can see where it is stuck.

**Comment by mattcrdb** [comment]
Thanks for taking a look, I will get back to the customer asking him to provide that and will update you.

**Comment by mwang1026** [comment]
closing
