### ISSUE TITLE
sql: lack of dynamic resizing makes large commands hard to read in the SQL shell

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#41305]
Consider the new command:
`SHOW PARTITIONS FROM TABLE rides;`

Now that it has the full_zone_config information it doesn't fit into the shell's window size:
![image](https://user-images.githubusercontent.com/22278911/66161073-81465b80-e5f9-11e9-8250-f2915dd283cb.png)

No amount of resizing bigger or smaller makes it easy to read.

We need to resize it with smaller text or otherwise make it easy for developers to be able to read the output of show commands

**Comment by awoods187** [comment]
Note you can make the window smaller with cmd -:
![image](https://user-images.githubusercontent.com/22278911/66161266-e8641000-e5f9-11e9-9188-655ee2e5d3f8.png)

**Comment by awoods187** [comment]
We could improve wrapping to keep the data in one column altogether instead of splitting it up:
Instead of two lines of"
constraints = '[+region=us-w
est, +az=2]',

We could make that stay together on the second line:
[blank]
constraints = '[+region=us-west, +az=2]'

**Comment by asubiotto** [comment]
Moving to CLI.

**Comment by jordanlewis** [comment]
This is fixable on the client side by setting your display format.

Like `/set display_format csv` and rerun your query.

```
  display_format | table       | the output format for tabular data (table, csv, tsv, html, sql, records, raw)
```
