### ISSUE TITLE
sql: measure client-gateway latency

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#41309]
@ajwerner just figured out that a performance regression we were seeing in our nightly tests was caused by cluster reuse in which the workload node would be in a different AZ than the cockroach node, resulting in a higher client-server latency. We couldn't figure this out from anything in our UI, though in hindsight the p50 exec latency should've reflected it.

Either way, we suspect that in global deployments knowing the client-gateway latency can be useful.

This latency is not exposed today; the debug network page only shows intra-node latencies. We should expose a client-gateway round trip latency in `SHOW SESSIONS`.

It's not entirely trivial to arrive at this number since (we think) the PG protocol does not allow the server to ask for an echo from the client. However, there might be initialization messages at hand-shake time that can be abused to that effect, though with the downside of not ever updating throughout the session. Perhaps there's something better we could do.

**Comment by jordanlewis** [comment]
We don't see a way to make this actionable at the moment, so we're going to close it despite it being a good idea.
