### ISSUE TITLE
Multi Region RoachPerf test is not rendering output.

### ISSUE THREAD

**Issue by isaactwong** [cockroachdb/cockroach#41312]
## Summary
The daily multi-region tpcc test "tpccbench/nodes=9/cpu=4/multi-region" is running, as there are logs from the run, and the test passes. But the output is not rendered in roach-perf.

## Steps to reproduce
1. Go to roach-perf and look up the test "tpccbench/nodes=9/cpu=4/multi-region"
2. The graph is blank.
3. Look at the logs for "tpccbench/nodes=9/cpu=4/multi-region" and verify the test passes.

## Expected Result
The daily run of "tpccbench/nodes=9/cpu=4/multi-region" should produce graphs and output in roach-perf.

**Comment by bobvawter** [comment]
Tracking in #44138
