### ISSUE TITLE
teamcity: failed test: TestLogic/fakedist-disk/upsert

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#41313]
```
testdata/logic_test/upsert:339: SELECT b FROM upsert_returning WHERE a = 1
                    expected:
                        1
                        
                    but found (query options: "") :
                        1
                        NULL
```

From https://teamcity.cockroachdb.com/viewLog.html?buildId=1520459&buildTypeId=Cockroach_UnitTests.

This seems bad. `a` is the primary key so there should never be more than one row returned.

@jordanlewis could I assign you to triage this within your team?

**Comment by jordanlewis** [comment]
I bet this is the new column family randomizer at work, cc @mjibson. Probably there's a bug with column families here.

**Comment by mjibson** [comment]
Definitely that. Probably #41277.

**Comment by jordanlewis** [comment]
Here's the repro. It only works with `fakedist` configs. Not sure what that means yet.

```
CREATE TABLE upsert_returning (a INT8 PRIMARY KEY, b INT8, c INT8, d INT8 DEFAULT -1, FAMILY (c), FAMILY (d), FAMILY (b));;
INSERT INTO upsert_returning VALUES (1, 1, NULL);
INSERT INTO upsert_returning (a, c) VALUES (1, 1), (2, 2) ON CONFLICT (a) DO UPDATE SET c = excluded.c RETURNING *;
        -- OK;
INSERT INTO upsert_returning (a, c) VALUES (1, 1), (3, 3) ON CONFLICT (a) DO NOTHING RETURNING *;
        -- OK;
UPSERT INTO upsert_returning (a, c) VALUES (1, 10), (3, 30) RETURNING *;
        -- OK;
SELECT b FROM upsert_returning WHERE a = 1;
        -- FAIL
--- done: testdata/logic_test/broken with config fakedist: 6 tests, 1 failures
--- total: 6 tests, 1 failures
test logs left over in: /var/folders/kz/_525lwtd4f7cxsb_qzwp0mv00000gn/T/logTestLogic609107079
--- FAIL: TestLogic (0.32s)
    test_log_scope.go:77: test logs captured to: /var/folders/kz/_525lwtd4f7cxsb_qzwp0mv00000gn/T/logTestLogic609107079
    test_log_scope.go:58: use -show-logs to present logs inline
    --- FAIL: TestLogic/fakedist (0.30s)
        --- FAIL: TestLogic/fakedist/broken (0.30s)
            logic.go:1655:

                testdata/logic_test/broken:28: SELECT b FROM upsert_returning WHERE a = 1
                expected:
                    1
                but found (query options: "") :
                    1
                    NULL
```

Here's the distsql plan for the failing query when it fails:

https://cockroachdb.github.io/distsqlplan/decode.html#eJykkF9LwzAUxd_9FOE-Z7Tp3gLCQCoOdJNu4IMUyZrLKHRJvElAGf3u0vRhf5gy9ank3Hvu-fXswb93IGFVPpZ3a7Zh99XyiUXnkcIbYYhkWrNlLw9lVTLFbpkADsZqXKgdepCvMAhTqDk4sg16b2mQ92lprj9A5hxa42IY5JpDYwlB7iG0oUOQsFabDitUGikbbmkMqu3SaUftTtHn7BwHOKycMl6yTGRFJibpUwCHZQySzQqoew42hkOqD2qLIEXPvyE7AEVjSSOhPoGp-wvsCzuxLgUfL16OLk6ixfWl5H8oJR8qEf8q5AJVhd5Z4_Gq_82HwlBvcWzX20gNPpNtUsz4XCZfEjT6ME7F-JibNEqAx2bxo3l6Ys7PzcWvkuv-5isAAP__vhUFrw==

**Comment by jordanlewis** [comment]
@solongordon could I get this into your queue?

**Comment by solongordon** [comment]
I think this is a bug in the `fakedist` configuration, not in CRDB itself. It looks like the fake span resolver is splitting a single row into multiple ranges, which should not be allowed.

Here is a more minimal repro:
```
# LogicTest: fakedist

statement ok
CREATE TABLE t (a INT PRIMARY KEY, b INT, c INT, FAMILY (a), FAMILY (b), FAMILY (c))

statement ok
INSERT INTO t VALUES (1, 1, 1)

query I
SELECT c FROM t WHERE a = 1
----
1
```
