### ISSUE TITLE
storage: merge less aggressively after load-based splitting

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#41317]
We're currently very aggressive about merging away split points due to load-based splitting immediately after the load is shut off. This can be an issue for benchmarking because splits created during a ramp-up period are often merged away before the workload begins running. This means that the system is not immediately ready for the workload when it does begin running.

Here's an example where load based splits are merged away almost immediately, which isn't desirable.
<img width="979" alt="Screen Shot 2019-10-04 at 1 02 45 AM" src="https://user-images.githubusercontent.com/5438456/66182427-0bff7880-e643-11e9-8ce1-df41f3c65131.png">

We can probably delay these merges by O(minutes) and still be completely fine.

**Comment by tbg** [comment]
Are you saying that these splits should use a larger sticky bit?

**Comment by tbg** [comment]
Hmm, no, you're not saying that. Even if a split happened 10 hours ago and the load dropped just now, you want to hold off on the merge. It sounds like it could be awkward to achieve that.

**Comment by nvanbenschoten** [comment]
Well, I think using a sticky bit would be a quick way to improve what we have here, even if it doesn't get us all the way there. Ideally, though, there would be some memory about historical load on a range.
