### ISSUE TITLE
sql: support missing JSON numeric scalar casts

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#41333]
It should be possible to cast JSON scalars to their corresponding SQL types, but it currently is not possible.

We should support:

JSON numeric -> int
JSON numeric -> float
JSON numeric -> decimal
JSON numeric -> string

This change should be pretty straightforward - `CastExpr.Eval` should be edited in `eval.go` to add the missing cases, and tests added to `pkg/sql/sem/tree/testdata/eval/cast`.

**Comment by 97amarnathk** [comment]
I would like to work on this.

**Comment by jordanlewis** [comment]
@97amarnathk I think @chrisseto has an ongoing patch for this. I'll assign him to prevent confusion.

**Comment by 97amarnathk** [comment]
Okay.
