### ISSUE TITLE
sql: support pgwire query cancellation

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#41335]
Postgres docs describe how `BackendKeyData` is initialized by the DB on startup and sent to the client so it can be used for cancellation requests later. 

https://www.postgresql.org/docs/12/protocol-flow.html

```
BackendKeyData

    This message provides secret-key data that the frontend must save if it wants to be able to issue cancel requests later. The frontend should not respond to this message, but should continue listening for a ReadyForQuery message.
```

CockroachDB has a separate [cancel query syntax](https://www.cockroachlabs.com/docs/stable/cancel-query.html). For increased compatibility, we should support the Postgres version too.

There have been other attempts at doing this in the past, but they had some issues.

See #13009 #13191 #17003 #34520 

Epic CRDB-7644

**Comment by awoods187** [comment]
@solongordon if this is relatively easy i'd be interested in picking it up because its used in part of the solution for #52240 and seems generally useful behavior for our drivers to posses.

**Comment by rafiss** [comment]
See #34520 for the latest attempt at implementing this. Eng has not really reached a consensus on how to do this. But I'm still hopeful!

**Comment by awoods187** [comment]
It's the top unimplemented feature: https://cockroachlabs.looker.com/looks/47
![image](https://user-images.githubusercontent.com/22278911/89486608-6bea1280-d771-11ea-95de-09ec6a5172fc.png)

We should prioritize this particularly if we have some prior art to draw upon.

**Comment by ajwerner** [comment]
Idea here on how to translate with the proxy https://github.com/cockroachdb/cockroach/pull/67501#issuecomment-984692819
