### ISSUE TITLE
multi-line editing in cockroach --sql is messed up.

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#4134]
If you type a command on 2 lines, hit enter, then hit up-arrow to get back the last command, all sorts of things are broken. For example, you can only edit the 2nd line of the command; pressing any key (including up arrow again) prints a completely new prompt line for no reason.

Also hitting enter on a line with no other characters initiates a multi-line command. What it should do is just give you a fresh prompt line.

**Comment by knz** [comment]
Terminal issue reported upstream as https://github.com/peterh/liner/issues/68
