### ISSUE TITLE
Stress Test Failure: TestClientDisconnectRedundant

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#4136]
=== RUN   TestClientDisconnectRedundant
I0204 04:07:33.963492 15714 gossip/gossip.go:218  setting node descriptor node_id:1 address:<network_field:"tcp" address_field:"127.0.0.1:0" > attrs:<> 
--- FAIL: TestClientDisconnectRedundant (0.01s)
	client_test.go:49: listen tcp 127.0.0.1:0: listen: address already in use

**Comment by tamird** [comment]
Can you post more information? This is not very much to go on. Did it
happen during stress or stressrace?

**Comment by BramGruneir** [comment]
Sorry, missed the line where it failed.  Added,

**Comment by tamird** [comment]
I would guess that this is a race between two processes in stress trying to listen on the same port.

**Comment by bdarnell** [comment]
But it's binding to port 0, which asks the kernel to (atomically) pick an unused port and bind to it. This can only fail with `EADDRINUSE` if all eligible ports are busy. I'm not sure how many ports a stress test run can chew through before `TIME_WAIT` sockets expire but this may turn out to be a recurring problem for us.
