### ISSUE TITLE
server,ui,pgwire: create an audit log for user logins

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#41378]
Requested on forum: https://forum.cockroachlabs.com/t/how-to-audit-login-attempts/3182/2

We need/want a log of success/failed login attempts and also user logouts (or conn dropped).

This is currently unavailable via the existing logging and audit facilities.

edit 2020-01-14: also connections via UI, and via RPC (CLI admin commands)

**Comment by knz** [comment]
@BramGruneir reported to me this morning that one of our large customers require this too.

**Comment by knz** [comment]
cc @rolandcrosby @piyush-singh

**Comment by knz** [comment]
Issue  #37209 says we should also emit an audit log for user account creation/drop/update.

**Comment by knz** [comment]
Fixed by #45193. User creation/update should be tracked separately via audit logging on system.users, system.roles and system.role_members.

**Comment by urysegal** [comment]
we just need to document to turn on audit log on system.users, system.roles and system.role_members
