### ISSUE TITLE
cli: cockroach demo doesn't return with global

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#41387]
Neither this:
```SQL
./cockroach demo —-nodes 9 —global
Error: unknown command "—-nodes" for "cockroach demo"
Failed running "demo"
```
or this work:
```
 ./cockroach demo —nodes 9 —global
Error: unknown command "—nodes" for "cockroach demo"
Failed running "demo"
```

**Comment by jordanlewis** [comment]
You're using a weird character for dash. Use `-`.

**Comment by awoods187** [comment]
I cut and pasted from the email @rohany sent. Looks like it was markdown conversion problems. I'll go ahead and close this issue as I was able to manually type it. As a side note, is there a way to improve this? Could we alias these weird mark down pastings as the things they represent/were before the copy paste messed them up?
