### ISSUE TITLE
server: stress test failure - TestIntentResolution

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#4138]
=== RUN   TestIntentResolution
I0204 05:56:28.262735 26861 server/node.go:320  store store=0:0 ([]=) not bootstrapped
I0204 05:56:28.264733 26861 storage/replica_command.go:1215  range 1: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC +1454565389.264s
I0204 05:56:28.265231 26861 server/node.go:263  **** cluster ea5227a4-b106-4523-b320-d8c603e393cb has been created
I0204 05:56:28.265256 26861 server/node.go:264  **** add additional nodes by specifying --join=127.0.0.1:34527
I0204 05:56:28.265792 26861 server/node.go:333  initialized store store=1:1 ([]=): {Capacity:8312655872 Available:5967110144 RangeCount:0}
I0204 05:56:28.265818 26861 server/node.go:236  node ID 1 initialized
I0204 05:56:28.265860 26861 gossip/gossip.go:218  setting node descriptor node_id:1 address:<network_field:"tcp" address_field:"127.0.0.1:34527" > attrs:<> 
I0204 05:56:28.265905 26861 storage/stores.go:274  read 0 node addresses from persistent storage
I0204 05:56:28.265950 26861 server/node.go:444  connecting to gossip network to verify cluster ID...
I0204 05:56:28.266030 26861 storage/stores.go:289  wrote 1 node addresses to persistent storage
I0204 05:56:28.266119 26861 server/node.go:461  node connected via gossip and verified as part of cluster "ea5227a4-b106-4523-b320-d8c603e393cb"
I0204 05:56:28.266156 26861 server/node.go:298  Started node with [[]=] engine(s) and attributes []
I0204 05:56:28.266206 26861 server/server.go:253  starting https server at 127.0.0.1:34527
I0204 05:56:28.266263 26861 storage/split_queue.go:97  splitting range=1 [/Min-/Max) at keys [/Table/11/0 /Table/12/0]
I0204 05:56:28.266377 26861 sql/pgwire/server.go:77  starting postgres server at 127.0.0.1:43172
I0204 05:56:28.286314 26861 storage/replica_command.go:1288  initiating a split of range=1 [/Min-/Max) at key /Table/11
I0204 05:56:28.297628 26861 storage/replica_command.go:1215  range 2: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC +1454565389.315s
I0204 05:56:28.297708 26861 storage/replica_command.go:1288  initiating a split of range=2 [/Table/11-/Max) at key /Table/12
I0204 05:56:28.349281 26861 storage/replica_command.go:1288  initiating a split of range=1 [/Min-/Table/11) at key "s"
I0204 05:56:28.353669 26861 storage/replica_command.go:1215  range 3: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC +1454565389.353s
W0204 05:56:28.354775 26861 storage/replica.go:1718  failed to push during intent resolution: conflicting intents on [/Meta1/Max]: resolved? false
I0204 05:56:29.372334 26861 storage/replica_command.go:1215  range 4: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC +1454565390.372s
I0204 05:56:29.373856 26861 stopper.go:273  draining; tasks left:
1      storage/replica.go:1755
W0204 05:56:29.374094 26861 storage/replica.go:1722  failed to resolve intents: failed to send RPC: too many errors encountered (1 of 1 total): server/node.go:549: node 1 stopped
--- FAIL: TestIntentResolution (1.12s)
intent_test.go:137: 0: unexpected non-local intents, expected [s x]: []

**Comment by tamird** [comment]
I can reproduce this locally after about 3 minutes using `make stressrace PKG=./server TESTS=TestIntentResolution`.

**Comment by tamird** [comment]
We have an auto-created copy of this in #4579.
