### ISSUE TITLE
sql: Support string values in extract arguments

### ISSUE THREAD

**Issue by rohany** [cockroachdb/cockroach#41408]
The extract function now requires keyword when using the `EXTRACT (month FROM x)` syntax. However, some ORMS generate queries like `EXTRACT ('month' FROM x)`. We should be able to support this, but don't currently.

**Comment by Gurio** [comment]
I would like to pick it up

**Comment by rohany** [comment]
I think someone else already took a stab at it

**Comment by Gurio** [comment]
seems so
