### ISSUE TITLE
sql: cast string to int[] or decimal[] when appropriate

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#41405]
The following works in postgres, but not CockroachDB.

```
> create table arrtest (intarr int[], decarr decimal(2,1)[], strarr text[]);
CREATE TABLE

> INSERT INTO arrtest VALUES ('{1,2,3}','{3.1,1.4}', '{abc,f''a,"fa\"b",def}');
pq: value type string doesn't match type int[] of column "intarr"
```

Adding explicit casts makes it work.

```
> INSERT INTO arrtest VALUES ('{1,2,3}'::int[],'{3.1,1.4}'::decimal[], '{abc,f''a,"fa\"b",def}');
INSERT 1
```

**Comment by jordanlewis** [comment]
This should work via our constant upcast mechanism, which currently only automatically upcasts strings into string arrays. This should be a relatively straightforward addition.

See `pkg/sql/sem/tree/constant.go`, and notice how only `StringArray` is present in `StrValAvailAllParsable`.
