### ISSUE TITLE
storage: Disable parallel commits for range descriptor transactions

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#41418]
The `unsafe-remove-dead-replicas` tool is unable to safely recover if it finds a transaction record in the STAGING state. We should avoid writing these for transactions that modify the range descriptor (Maybe we already do, but from discussion in #41266 @tbg and I couldn't see how/whether that's actually the case).

**Comment by nvanbenschoten** [comment]
We already disable parallel commits for any transaction that has a commit trigger. Does that include every transaction that modifies a range descriptor?

**Comment by bdarnell** [comment]
Every current modification to a range descriptor has a commit trigger, yes. So it sounds like we're covered here. It's a little subtle, but I can't think of a better way to centralize it reliably.
