### ISSUE TITLE
jepsen-monotonic failure when using RootTxn on the gateway

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#41424]
#41307 changed how DistSQL uses transactions. It's first commit https://github.com/cockroachdb/cockroach/commit/29e18f06a41f40ad9cc848916ae1460848d8c3fb makes a seemingly innocuous change about using RootTxns on the gateway more often than before. This change causes the `monotonic` jepsen test to fail. It fails about 50% with no nemesis, and always with some of the nemeses (e.g. `majority-ring`).

The test essentially uses two tables and runs transactions that read the maximum from both tables, increment by one, and write to one of the tables that maximum and the `cluster_logical_timestamp()`. It then verifies that both the maximum values and the timestamps increase monotonically. But lo and behold, they're no longer monotonic.

I have a theory about the cause: I believe it's because of this check intended to prevent refreshes when `cluster_logical_timestamp()` (or other things that lock a txn's timestamp) has been used
https://github.com/cockroachdb/cockroach/blob/e3346c1a307f16c7f553c0c5973f8faa020cb9d4/pkg/roachpb/data.go#L1284

I believe the check is looking at the wrong `txn` proto. It's looking at a proto coming from a `pErr`, but it's unlikely for that one to have the `OrigTimestampWasObserved` bit set. That bit is probably only set on the client, not the server.
If this theory is correct, this means that we've always had this bug, but #41307 exposed it more broadly. It used to be the case that only queries forced to be planned entirely on the gateway (e.g. mutations) would use the `RootTxn`, others would use the `LeafTxn`. Leaves don't do refreshes, and so they're safe (and suboptimal when a refresh would help).
Besides regular queries, schema changes used to use the `OrigTimestampWasObserved` bit too, so I think those probably are at risk in 19.1 and below.

If this theory is correct, this use of the wrong txn object steams from the fact that we put transactions in `pErrs`, for maximal confusion. It's always been a pet peeve of mine:
https://github.com/cockroachdb/cockroach/issues/18919#issuecomment-336558684

**Comment by knz** [comment]
I confirm this bug is present in `master` (post revert of Andrei's recent fixes),
also in 19.1! 

also I have written a simplified version of the jepsen test:

[monotonic_test.zip](https://github.com/cockroachdb/cockroach/files/3703101/monotonic_test.zip)

Now also testing 2.1 for good measure.

**Comment by bdarnell** [comment]
What do you mean by the bug being present in older releases? Just that we're looking at the wrong Transaction object, or is the monotonic test failing there too? If the latter, do you understand why this test is failing while the jepsen test has never (to my knowledge) hit this before on older versions?

**Comment by knz** [comment]
> What do you mean by the bug being present in older releases? Just that we're looking at the wrong Transaction object, or is the monotonic test failing there too? 

Both

> If the latter, do you understand why this test is failing while the jepsen test has never (to my knowledge) hit this before on older versions?

Yes I understand it.

The Jepsen test separates the phases in a multi-statement txn, using standalone SELECTs  first to find the max and then a separate INSERT for the mutation. These standalone SELECTs are using LeafTxn objects since at least 2.1 (ever since we use distsql to serve them, which may have been 2.0), so were _never_ able to auto-refresh (instead any conflict would have caused a client-side retry)

In order to tickle the bug, you need a read that encounters a refresh error on a RootTxn object with a mutation that also gets a call to `cluster_logical_timestamp()`. To get this, you need a SQL  that combines INSERT with cluster_logical_timestamp() (and possibly some SELECT too, I'm not sure), which is what my simplified Go code does:

```sql
INSERT INTO t.t%d(v, ts) SELECT max(x)+1, if(pg_sleep(0.005*random()), cluster_logical_timestamp(), 0)
  FROM (VALUES
   ((SELECT max(v) FROM t.t1)),
   ((SELECT max(v) FROM t.t2))
) AS x(x)
```

I'd say client apps that only use INSERT ... VALUES are unaffected.

However an UPDATE combined with cluster_logical_timestamp() is likely to be affected since 2.1 too.

**Comment by andreimatei** [comment]
The theory about us looking at `pErr.Txn` being wrong didn't quite pan out. On the response path, the DistSender [updates](https://github.com/cockroachdb/cockroach/blob/5119819560e40d5b6e4661d4dac08c8e9b6ebf4b/pkg/kv/dist_sender.go#L1188) `pErr.Txn` with the response's txn, which comes from the request's txn. I find all this very unlikely to be correct and I'll try to clean it up, but it's not our smoking gun. Fixing it does not make Jepsen happy.

However, I think the real problem is that `cluster_logical_timestamp()` is more clearly broken. It calls `TxnCoordSender.CommitTimestmp()`, which simply returns `txn.OrigTimestamp`. But, in case the txn already refreshed, the `OrigTimestamp` is not going to be the `CommitTimestamp`. The commit timestamp is:
```
commitTS := txn.OrigTimestamp
commitTS.Forward(txn.RefreshedTimestamp)
```

**Comment by bdarnell** [comment]
>  in case the txn already refreshed

Ah, that makes sense. Originally refreshes were only possible at the end of the transaction, but early refreshes/pushes are now possible.
