### ISSUE TITLE
sql: support unnest(anyarray, anyarray)

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#41434]
This form of `unnest` is unsupported by Cockroach. According to the Postgres docs, its functionality is to:

```
expand multiple arrays (possibly of different types) to a set of rows. This is only allowed in the FROM clause; see Section 7.2.1.4
```

This is needed for Django. See https://github.com/cockroachdb/cockroach-django/issues/10

**Comment by jordanlewis** [comment]
Actually it appears to be varargs.

> The special table function UNNEST may be called with any number of array parameters, and it returns a corresponding number of columns, as if UNNEST (Section 9.18) had been called on each parameter separately and combined using the ROWS FROM construct.

**Comment by giorgosp** [comment]
Hello, I would like to help with this ticket but please feel free to re-assign it if it is urgent. I will need a couple of days to get my head around the internals.

**Comment by jordanlewis** [comment]
@giorgosp, great. Please don't hesitate to ask for help.

**Comment by giorgosp** [comment]
After a second look, I found out it would be simple to completely remove the `ReturnLabels` which were hardcoded in `FunctionProperties` and give some flexibility as to what return labels will be used each time.

Opened a PR (https://github.com/cockroachdb/cockroach/pull/41861/) to await for your feedback.
