### ISSUE TITLE
[Documentation Bug] PRIMARY KEY does not allow NULL

### ISSUE THREAD

**Issue by rlowe** [cockroachdb/cockroach#4145]
https://grockdoc.com/cockroachdb/alpha/articles/create-table_dc1b1897-6e9e-4e9b-95ea-f59fbb7a04e4 states:

```
The primary key is a column that is UNIQUE. CockroachDB supports a NULL primary key, however at most one row may use NULL as its primary key.
```

This is not true anymore.

**Comment by jseldess** [comment]
These docs weren't written by CockroachDB but rather by a company called [GrocDoc](https://grockdoc.com/). @jess-edwards, @spencerkimball: I can reach out to have this corrected once I'm back from vacation, but first want to know if you know anything about them?

**Comment by rlowe** [comment]
aha.  I assumed it was something that you were in charged of.  No need to have this ticket remain open if this isn't in your direct control.  Closing ticket!
