### ISSUE TITLE
support: separate form for bug, feature, performance ticket types

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/cockroach#41493]
**Is your feature request related to a problem? Please describe.**

Public GitHub issues have bug, feature, performance ticket types.  Support portal priority (see below). 
<img width="564" alt="Screen Shot 2019-10-10 at 11 16 50 AM" src="https://user-images.githubusercontent.com/6315124/66582810-5b1c4080-eb50-11e9-9e4f-8a00d66688df.png">

Not having template of information to fill out by ticket type often leads to multiple interactions to collect necessary information.

**Describe the solution you'd like**

Support also having types of tickets as well as the priority would allow more efficient information transfer.

**Describe alternatives you've considered**

**Additional context**

Jira issue: CRDB-5442

**Comment by tim-o** [comment]
We're looking into how to make this happen. There's not an out of the box solution.

**Comment by mattcrdb** [comment]
I am exploring ways to do this using jQuery.

**Comment by mattcrdb** [comment]
The work is complete, waiting for a review and then will push to live zendesk.

**Comment by mattcrdb** [comment]
poor experience on ie 11 after pushing the changes, need to find a workaround.

**Comment by mattcrdb** [comment]
found the bug, waiting for a particular client to test the workflow.
