### ISSUE TITLE
sql: SHOW RANGES hangs if a table has any unavailable ranges

### ISSUE THREAD

**Issue by solongordon** [cockroachdb/cockroach#41518]
@kai-niemi highlighted the fact that the SHOW RANGES command completely hangs if any of the relevant ranges are unavailable. This is unfortunate since that command is one of the first ways a user might try to diagnose the availability issue. This is mentioned in [a comment](https://github.com/cockroachdb/cockroach/issues/19644#issuecomment-503242491) on #19644 but deserves its own issue.

Repro:
```
roachprod create local -n3
roachprod start local
roachprod stop local:2,3
echo 'show ranges from table system.users;' | roachprod sql local:1
```

Jira issue: CRDB-5439

**Comment by awoods187** [comment]
@solongordon do we have an idea on how to fix this?

**Comment by solongordon** [comment]
No, I haven't had a chance to dig into what the underlying issue is.

**Comment by tbg** [comment]
Actually I'm not sure this properly is a KV issue. The only interaction with KV here is that we scan the meta ranges:

https://github.com/cockroachdb/cockroach/blob/da982a55d490ae4d8d01567927aaafdcd86cd0a6/pkg/sql/crdb_internal.go#L2460

Clearly that can't succeed if some of these ranges are unavailable. However, KV already exposes inconsistent scans, for which any surviving replica can be contacted and will return results. This could be used here, but the results will be just that - possibly partially stale, so we probably would make yet another builtin here that is identical in every way other than that it is not authoritative.
