### ISSUE TITLE
FTBFS -Werror=array-bounds

### ISSUE THREAD

**Issue by ltworf** [cockroachdb/cockroach#41531]
I'm trying to build cockroachdb but compilation fails because of some C++ error.

Probably you are running an old gcc version so you don't get those checks.

```
gcc (Debian 9.2.1-8) 9.2.1 20190909
```

```
[  2%] Building CXX object CMakeFiles/roach.dir/protos/roachpb/data.pb.cc.o
/usr/bin/c++   -I/home/salvo/go/src/github.com/cockroachdb/cockroach/c-deps/libroach/./include -I/home/salvo/go/src/github.com/cockroachdb/cockroach/c-deps/libroach/../protobuf/src -I/home/salvo/go/src/github.com/cockroachdb/cockroach/c-deps/libroach/../rocksdb/include -I/home/salvo/go/src/github.com/cockroachdb/cockroach/c-deps/libroach/protos  -g1 -O3 -DNDEBUG   -Werror -Wall -Wno-sign-compare -std=c++11 -o CMakeFiles/roach.dir/protos/roachpb/data.pb.cc.o -c /home/salvo/go/src/github.com/cockroachdb/cockroach/c-deps/libroach/protos/roachpb/data.pb.cc
In member function 'void cockroach::roachpb::StoreIdent::SharedCtor()',
    inlined from 'cockroach::roachpb::StoreIdent::StoreIdent()' at /home/salvo/go/src/github.com/cockroachdb/cockroach/c-deps/libroach/protos/roachpb/data.pb.cc:1179:13,
    inlined from 'void protobuf_roachpb_2fdata_2eproto::InitDefaultsStoreIdent()' at /home/salvo/go/src/github.com/cockroachdb/cockroach/c-deps/libroach/protos/roachpb/data.pb.cc:1175:1:
/home/salvo/go/src/github.com/cockroachdb/cockroach/c-deps/libroach/protos/roachpb/data.pb.cc:1198:11: error: 'void* memset(void*, int, size_t)' offset [29, 32] from the object at 'cockroach::roachpb::_StoreIdent_default_instance_' is out of the bounds of referenced subobject 'cockroach::roachpb::StoreIdent::node_id_' with type 'int' at offset 24 [-Werror=array-bounds]
 1198 |   ::memset(&node_id_, 0, static_cast<size_t>(
      |   ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1199 |       reinterpret_cast<char*>(&store_id_) -
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1200 |       reinterpret_cast<char*>(&node_id_)) + sizeof(store_id_));
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Environment:**
 - CockroachDB version git master
 - debian bullseye

**Additional context**

I can't use it since I can't build it.

**Comment by petermattis** [comment]
Hi @ltworf. You're correct that we use an older version of gcc of compilation. The easiest workaround is to use our docker build environment. `build/builder.sh mkrelease`. Or, even easier, use one of the released binaries: https://www.cockroachlabs.com/docs/releases/.

The specific error is occurring in generated protobuf code. We'll have to track down whether that has been fixed in the protobuf library we use, or if we should disable this error.

**Comment by petermattis** [comment]
@ltworf https://github.com/petermattis/cockroach/tree/pmattis/wno-array-bounds might workaround this problem (by disabling the error). Can you take that for a spin?

**Comment by petermattis** [comment]
We're still using protobuf 3.6. I took a look at the latest release (3.9.2), and it generates similar code. Disabling the error seems like the way to go for now.

**Comment by ltworf** [comment]
Thanks!

I cherry picked your commit into my branch and it's working now. Well failing somewhere much later at least! :D

I might give the docker a shot.
