### ISSUE TITLE
storage: Preserve SSTableInfo level structure with GetSSTables

### ISSUE THREAD

**Issue by itsbilal** [cockroachdb/cockroach#41546]
The method `SSTables()` on Pebble DB instances returns SSTable info indexed by level. Currently, due to the `WithSSTables` interface-enforced return type on `GetSSTables()` (see `pkg/storage/engine/engine.go`), this information gets decomposed away into a flat slice, only to be later re-indexed in the compactor.

This extra work can be optimized if the level-based layout is preserved throughout. Would probably require changing the `WithSSTables` interface, as well as ensuring the output from RocksDB's `GetSSTables` is also indexed by level.

**Comment by petermattis** [comment]
@jbowens I think you might have done this already.

**Comment by jbowens** [comment]
Yeah, `GetSSTables` is no longer used except on RocksDB (and for posterity, RocksDB will be removed in the upcoming 20.2 release).
