### ISSUE TITLE
sql: 'infinity' returned as timestamp rather than 'infinity'

### ISSUE THREAD

**Issue by asubiotto** [cockroachdb/cockroach#41564]
Ran into this while running the `lib/pq` test suite:
Postgres:
```
asubiotto=# SELECT 'infinity'::timestamp;                                        
 timestamp 
-----------
 infinity
```
Cockroach:
```
root@:26257/defaultdb> SELECT 'infinity'::timestamp;
                  timestamp
+-------------------------------------------+
  -292277022365-05-08 08:17:07.854776+00:00
(1 row)
```

Jira issue: CRDB-5433

**Comment by otan** [comment]
`infinity` and `-infinity` is a special time that behaves like special, like 2400 time in TimeTZ.
they're bigger than other values and add/subtract to anything.

```

otan=# select 'infinity'::timestamp - '1 second'::interval;
 ?column?
----------
 infinity
(1 row)

otan=# select 'infinity'::timestamp - '2 second'::interval;
 ?column?
----------
 infinity
```

we'll probably want solve this given #46990 is in 20.2 (which makes this behaviour better).

**Comment by otan** [comment]
actually, i will make a stopgap that makes this the maximum/minimum supported time for now.

**Comment by otan** [comment]
Tagging as a good starter project. We'll need to introduce a new marker for "infinity" and "-infinity" in `pgdate`, and make sure comparators and binops treat infinity as > any other number and add/subtract to itself. `Min/Max` for the tree datums will need to change. And of course some testing...

**Comment by kylepl** [comment]
I found if you use `CREATE USER VALID UNTIL 'infinity'`, as discussed in the merged bug, that you can no longer do `SELECT * FROM pg_catalog.pg_roles;` - and I wasn't sure how to even clean up the broken user or identify it.
