### ISSUE TITLE
sql: timestamp with time zone does not include location

### ISSUE THREAD

**Issue by asubiotto** [cockroachdb/cockroach#41565]
Ran into this while running the `lib/pq` test suite:
```
--- FAIL: TestTimestampWithTimeZone (0.01s)
    encode_test.go:254: timestamps not equal: 2012-11-06 05:23:42.123456 -0500 EST != 2012-11-06 05:23:42.123456 -0500 -0500
```
The test sends a go `time.Time` as an argument to the database and expects the location information to be round tripped, which doesn't seem to be happening.

**Comment by rafiss** [comment]
I think it's possible the fixes in #42244 or #41663 fixed this too.

I say this because the test is passing now, see #42475
