### ISSUE TITLE
storage: panic from raftgroup.Campaign call to becomeLeader

### ISSUE THREAD

**Issue by peymanh** [cockroachdb/cockroach#41588]
Hi, we have 3 container replicas of cockroachdb on 3 different servers and manage them by _docker swarm_. Today after deploying latest changes to the system, suddenly our second container got stuck in "assigned to running" state. 
 
I tried to debug the problem by seeing the container logs. this is the result of **_docker service logs roach2 --tail 100 -f_** command: 

![cocroach](https://user-images.githubusercontent.com/5622410/66813082-fb9fa580-ef40-11e9-9f4b-c09a882927ad.png)

**Environment:**
 - CockroachDB version 2.1.5
 - Server OS: UBUNTU
 - Client app  `cockroach sql`

**Comment by tbg** [comment]
Hi @peymanh, what was it that you did in

>  Today after deploying latest changes to the system, 

Was this updating the version of CockroachDB, or deploying your app again? Am I understanding correctly that this node will crash in the same way every time you attempt to restart it?

Technical analysis so far:

The error indicates that this node has a single-member replica that is asked to campaign, but that this replica's raft group is improperly configured (I think its `r.id` does not match the entry it has for itself in `r.prs`, if it even has one).

I'd be interested in taking a look at the data directory for this node, if this is at all possible (I assume this contains production data).

**Comment by tbg** [comment]
@bdarnell does this error ring a bell? v2.1.5 is far from the most recent 2.1 release, but I don't remember us fixing something related to this bug. Note that v2.1.5 already has this code 

```go
func (r *Replica) maybeCampaignOnWakeLocked(ctx context.Context) {
	// Raft panics if a node that is not currently a member of the
	// group tries to campaign. That happens primarily when we apply
	// preemptive snapshots.
	if _, currentMember := r.mu.state.Desc.GetReplicaDescriptorByID(r.mu.replicaID); !currentMember {
		return
	}
```

**Comment by peymanh** [comment]
@tbg 

> Hi @peymanh, what was it that you did in
> 
> > Today after deploying latest changes to the system,
> 
> Was this updating the version of CockroachDB, or deploying your app again? Am I understanding correctly that this node will crash in the same way every time you attempt to restart it?

First we deployed our app again and our second replica of Cockroach went mad :(
In order to solve the problem we thought  that it was due the old version of the image! So we changed it `2.1.9`. I even rebooted our second server. But even changing the version didn't help.

Due the `healthcheck` that we provided for the container, it consistently tries to restart itself. but it never succeeds to go healthy.

**Comment by tbg** [comment]
Thanks @peymanh. You're not able to (privately) share the data directory with us, is that correct?

To "unblock" your issue, I would suggest taking a backup of the data dir (i.e. just copy it somewhere while the node is not running and not attempting to start). Then you can "reset" n2 by decommissioning it first (steps at https://www.cockroachlabs.com/docs/stable/remove-nodes.html#step-2-mark-the-dead-node-as-decommissioned) and then removing it physically (i.e. reset the data dir for that node). You should then be able to add it back to the cluster (it will get a new NodeID), and your cluster should become healthy again.

We can then discuss next steps. I would like to see the output of `./cockroach debug range-descriptors /your/data/dir/for/that/node`. You'll want to send this privately as the keys printed there can leak some private information. My email is tobias@cockroachlabs.com.

**Comment by tbg** [comment]
Hmm, that's a good point. @peymanh we'll at least need to see the logs for n2 leading up to the first instance of the crash. Could you submit that to https://support.cockroachlabs.com/hc/en-us? Please mention this issue in your message. Thank you.

**Comment by peymanh** [comment]
> To "unblock" your issue, I would suggest taking a backup of the data dir (i.e. just copy it somewhere while the node is not running and not attempting to start). Then you can "reset" n2 by decommissioning it first (steps at https://www.cockroachlabs.com/docs/stable/remove-nodes.html#step-2-mark-the-dead-node-as-decommissioned) and then removing it physically (i.e. reset the data dir for that node). You should then be able to add it back to the cluster (it will get a new NodeID), and your cluster should become healthy again.

@tbg We took a backup of data directory and then went to use the decommissioning command in n1 (one of our alive nodes). The problem is that after hours of waiting, decommissioning procedure never ended and was just printing dots after dots. 

Is there any other solution that decommissioning? We are thinking of removing our second instance container by `docker service rm` , removing the volume by `docker prune` adn finally deploy the stack again. Will it be another way for unblocking our issue?

**Comment by tbg** [comment]
Decommissioning only works when it can move the replicas to a new home. You indicated that you initially had three servers, now one is down. So you have two running but need three running. If you re-add the down node without its data directory things should normalize (and the decommissioning should finish).

**Comment by lunevalex** [comment]
Going to close this based on the last comment from @tbg
