### ISSUE TITLE
sql: add postgres options to users

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#41580]
Specifically, `nologin` and `valid until` would be very useful and should be relatively easy to add.

But let's consider adding as many options as possible from:
https://www.postgresql.org/docs/current/sql-alterrole.html

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[3849](https://cockroachdb.zendesk.com/agent/tickets/3849) has been linked to this issue.

**Comment by bdarnell** [comment]
Duplicate of #41396 (`nologin` and `valid until`) and #29633 ("as many options as possible")
