### ISSUE TITLE
sql: error for NULL IN subquery

### ISSUE THREAD

**Issue by solongordon** [cockroachdb/cockroach#41596]
The SQLAlchemy `test_null_in_empty_set_is_false` test exposed this error:
```
> SELECT NULL IN (SELECT 1);
pq: unsupported comparison operator: <unknown> IN <tuple{int}>
```
This appears to be related to #26733.

**Comment by rafiss** [comment]
fixed by https://github.com/cockroachdb/cockroach/pull/49814
