### ISSUE TITLE
sql: support more COPY syntax

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#41608]
#8585 added support for COPY, but we don't support the following queries:

```
COPY (SELECT generate_series(1,1000)) TO STDOUT
COPY copytest FROM STDIN with (FORMAT CSV, HEADER false)
COPY copytest TO STDOUT
```

There are also other COPY options we don't support yet

- [ ] FORMAT format_name
- [ ] OIDS [ boolean ]
- [ ] FREEZE [ boolean ]
- [x] HEADER [ boolean ] -- https://github.com/cockroachdb/cockroach/pull/82457
- [ ] QUOTE 'quote_character'
- [x] ESCAPE 'escape_character' -- https://github.com/cockroachdb/cockroach/pull/78303/
- [ ] FORCE_QUOTE { ( column_name [, ...] ) | * }
- [ ] FORCE_NOT_NULL ( column_name [, ...] )
- [ ] FORCE_NULL ( column_name [, ...] )
- [ ] ENCODING 'encoding_name'

---

Update:
- v22.1 will support the ESCAPE option

---

Jira issue: CRDB-5430

Epic CRDB-14477

**Comment by vy-ton** [comment]
Linking [related](comment) on a [closed issue](https://github.com/cockroachdb/cockroach/issues/8585)

**Comment by codyflynnNC** [comment]
@rafiss what is the alternatives to this syntax "COPY copytest FROM STDIN with (FORMAT CSV, HEADER false)" ? Im working with asyncpg and they use that syntax for COPY statements.

**Comment by rafiss** [comment]
We've added ESCAPE and HEADER. I'm closing this in favor of the following finer-grained issues

https://github.com/cockroachdb/cockroach/issues/85571
https://github.com/cockroachdb/cockroach/issues/85572
https://github.com/cockroachdb/cockroach/issues/85573
https://github.com/cockroachdb/cockroach/issues/85574
https://github.com/cockroachdb/cockroach/issues/85575

**Comment by rimadeodhar** [comment]
Do we have an issue to track support for the syntax `COPY (SELECT generate_series(1,1000)) TO STDOUT`?

**Comment by rafiss** [comment]
@rimadeodhar yes: https://github.com/cockroachdb/cockroach/issues/85571
