### ISSUE TITLE
ORMs: different behavior on go-pg tests on Mac vs linux

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#41619]
While working on adding a roachtest to run [go-pg](https://github.com/go-pg/pg) tests against Cockroach, I observed the following:
- when using `v19.1.5`:
  - running on Mac locally and on linux remotely had the same set of failures
- when using `v19.2-beta`
  - running on Mac locally failed 46 more tests that running on linux remotely
- when using current master (as of October 8th)
  - running on Mac locally failed more tests that running on linux remotely

All the failures return an error like `ERROR #42P07 relation "images" already exists` which suggests that tables are not properly dropped in-between different tests. The issue seems to be present only on 19.2 branches. There was no flakiness on different runs, so I didn't investigate further, but this does seem slightly concerning/confusing.

**Comment by rafiss** [comment]
Closing because of staleness
