### ISSUE TITLE
Facilitate netdata integration

### ISSUE THREAD

**Issue by hazcod** [cockroachdb/cockroach#41626]
**Is your feature request related to a problem? Please describe.**
https://github.com/netdata/netdata/issues/4696
Netdata is an awesome open source monitoring solution that supports a load of sources.
But cockroachdb is not one of these.
e.g. https://docs.datadoghq.com/integrations/cockroachdb/#metrics

**Describe the solution you'd like**
Cockroachdb already exports the required metrics, but these need to be interpreted by the netdata team.

**Additional context**
Can somebody sponsor this integration and mention what metrics are worth to export?

**Comment by awoods187** [comment]
@piyush-singh
