### ISSUE TITLE
FTBFS on Debian: yarn is called yarnpkg there

### ISSUE THREAD

**Issue by ltworf** [cockroachdb/cockroach#41640]
On debian systems, due to another previous command being called yarn, the js thing is called yarnpkg. As a consequence the makefile either fails to find yarn or finds the wrong one. Either way both end up in a failure.

I made a PR for this but some automated tool didn't run so it remained yellow forever.

https://github.com/cockroachdb/cockroach/pull/41464

**Comment by jordanlewis** [comment]
Closing due to age.
