### ISSUE TITLE
sql: missing support for CREATE MATERIALIZED VIEW

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#41649]
PostgreSQL supports materialized views with CREATE MATERIALIZED VIEW. CockroachDB is missing support for this feature. It is unclear if the semantics PostgreSQL provides would be good to add to CockroachDB, but this issue exists as a placeholder to point to when discussing this missing support.

**Comment by dbist** [comment]
@dt based on your comment in slack, should we add the reskin `CTAS` as part of this issue or a separate issue?

**Comment by timgraham** [comment]
Hi @rohany, materialized views aren't showing up in a `SHOW TABLES` qurery. Is it a bug?

**Comment by rohany** [comment]
Yes that looks like a bug. Can you please open an issue?

**Comment by timgraham** [comment]
Created https://github.com/cockroachdb/cockroach/issues/53610. Thanks!
