### ISSUE TITLE
gossip: cache unmarshalled descriptors for Gossip.GetNodeDescriptor

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#4164]
We call `Gossip.GetNodeDescriptor` for each replica of a range whenever `DistSender` wants to send an RPC to that range. Internally, `GetNodeDescriptor` retrieves the marshaled protobuf for the node ID and unmarshalss it. We should either cache the unmarshalled descriptor somewhere within `Gossip` or `DistSender` should watch for changes to node descriptor gossip keys and maintains its own cache.

**Comment by petermattis** [comment]
Note that having `DistSender` watch for changes to node descriptor keys has precedent in the way `StorePool` watches for changes to store descriptor keys.

**Comment by tschottdorf** [comment]
To not pollute the Gossip interface (if we cache it in Gossip, then implicit in that is that the value is read-only and nobody will ever change it), it looks most straightforward to have Gossip watch and maintain an LRU cache (which likely never fills) which is simply cleared on a NodeDescriptor update.
Or is this a general concern in a lot of other critical paths? Then maybe read-only semantics for `GetGossip` and a gossip-internal cache sound useful.

Does this show up noticeably in any benchmarks?

**Comment by bdarnell** [comment]
`server/raft_transport.go` also gets node descriptors from gossip but it doesn't re-query them for every message (it already assumes that the values never change, which may be a problem). If we did re-query for changed range descriptors, this would become a hot spot and a cache inside `Gossip` would be useful. On the other hand, once this moves to streaming RPCs the node descriptor lookup moves out of the hot path and would no longer be worth caching.

**Comment by petermattis** [comment]
Yes, this is showing up in various SQL benchmarks. It's not a huge overhead, but it is there and it is straightforward to fix.
