### ISSUE TITLE
do you have any plan to support utf8mb4?

### ISSUE THREAD

**Issue by yangxuanjia** [cockroachdb/cockroach#41672]
do you have any plan to support utf8mb4?

**Comment by jordanlewis** [comment]
Hi @yangxuanjia, not that I know of. What is utf8mb4? Can you provide more details? Thanks!

**Comment by yangxuanjia** [comment]
https://www.postgresql.org/message-id/201503051745459170125%40pconline.com.cn

**Comment by ricardocrdb** [comment]
Hey @yangxuanjia 
 
Apologies for the delayed response, the link you provided doesn't provide many more details on what utf8mb4 is. My understanding is that it is used for certain Chinese characters and emojis, is that correct?

Cheers,
Ricardo

**Comment by yangxuanjia** [comment]
yes

**Comment by knz** [comment]
The `utf-8` encoding in CockroachDB is a strict superset of MySQL's `utf8mb4`. Moreover, the encoding name `utf8mb4` is not supported in PostgreSQL, so there is no reason to support it in CockroachDB.
