### ISSUE TITLE
storage: Write to local RocksDB before updating liveness

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#41683]
#24591 attempted to ensure that a node with a stalled disk would not be considered live and would lose all its leases rather than stalling the rest of the cluster. (It did not work when introduced, but was fixed in #33122). It was later undone in #32978 because that PR included a stricter version of a similar check. #32978 was itself disabled by default (#36484), leaving us without even the weaker protection provided by #24591. We need to bring back the logic from #24591, and backport it to 19.1 and 19.2. (We also need to backport #33122 to 2.1 so that #24591 works in that branch)

**Comment by irfansharif** [comment]
@bdarnell: I can take this on if nobody else is.

**Comment by bdarnell** [comment]
@andreimatei said he might try next week but I don't think he's started yet, so it's yours.

**Comment by andreimatei** [comment]
go for it

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[3900](https://cockroachdb.zendesk.com/agent/tickets/3900) has been linked to this issue.

**Comment by irfansharif** [comment]
Fixed across #41761, #41734, #41764, #41765.
