### ISSUE TITLE
changefeedccl: bug in table history wrt fetching old table descriptor versions after a restart

### ISSUE THREAD

**Issue by aayushshah15** [cockroachdb/cockroach#41694]
In `poller.go` the poller constructs a `tableHistory` object and periodically calls `ExportRequest` with a `startTS` and `endTS` to fetch a list of table descriptors that *were modified* in this time window. Note that this doesn't fetch the table descriptor versions that were live at `startTS`.

Now, consider the case where a backfill is *detected*, but there is a job restart before the backfill is  *triggered*: the `poller` restarts at the previous globally resolved timestamp and starts calling `ExportRequest` again with `startTS` set to the aforementioned globally resolved timestamp. Now, since this `ExportRequest` call doesn't fetch the table descriptor version *live* at `startTS`, 
it is possible that this method only fetches the table descriptor(s) *after* the column backfill mutation has already been applied. 

If this happens, the `tableHistory` and `poller` have no way of detecting and triggering a backfill, which could lead to certain row updates simply never being emitted.

**Comment by aayushshah15** [comment]
@danhhz @ajwerner. Adding this to the release blockers list for now; also going to push my rough nemeses branch (that includes a fix for this) so @danhhz can start taking a look.

**Comment by ajwerner** [comment]
It's worth adding that this is no a problem on the initial session of the changefeed because it uses a zero `startTS` which ensures that it reads all descriptor versions.

**Comment by danhhz** [comment]
Gotcha! Is the fix that we need to prime the previousTableVersion map with the descriptors as of t1?

**Comment by ajwerner** [comment]
> Gotcha! Is the fix that we need to prime the previousTableVersion map with the descriptors as of t1?

Correct
