### ISSUE TITLE
opt: hash join instead of lookup join on small tables

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#41701]
On small tables, we get hash join when we would normally get a lookup join:

```
create table parent (p int primary key, data int);
insert into parent values (1,1);
create table t (a int, b int);
insert into t values (1,1);
create statistics foo from parent;
create statistics foo from t;
explain (opt) select 1 from parent, t where p=a;

           text           
+------------------------+
  project                 
   ├── inner-join (hash)  
   │    ├── scan parent   
   │    ├── scan t        
   │    └── filters       
   │         └── p = a    
   └── projections        
        └── const: 1      
```

With up to 5 rows in the parent, I still get a hash join. We need to adjust the costs so this doesn't happen. I think the root cause is that we add a `randIOCostFactor` per lookup but the scan doesn't have a `randIOCostFactor` component at all. Maybe we want to exempt the first lookup from that random cost.

**Comment by RaduBerinde** [comment]
@justin - could you take a look? I don't want to step over your costing work. I'm hoping it will be unaffected if the adjustment is not proportional to any row count.

This is particularly relevant for FK checks (where we join the parent table with the mutation input, which in many cases is one row).

**Comment by nvanbenschoten** [comment]
> This is particularly relevant for FK checks (where we join the parent table with the mutation input, which in many cases is one row).

I can confirm that we see this all over the place with TPC-E. Changing these cases to use a lookup join instead of a hash join would be a nice win.
