### ISSUE TITLE
sql: to_hex differs from postgres with negative inputs

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#41707]
```
postgres=# select to_hex(-1);
  to_hex  
----------
 ffffffff
```

```
root@:26257/postgres> select to_hex(-1);
  to_hex  
+--------+
  -1      
```

**Comment by memnoth** [comment]
Although @solongordon is the main assignee, I just gave it a try for the first PR because it has been about 8 days since it opened, but @solongordon looks busy. If you guys think that it is kinda rudely behavior, I am really sorry for that.  
A patch would be on the board sooner.

Thanks!
