### ISSUE TITLE
Is "init" no longer a thing?

### ISSUE THREAD

**Issue by rlowe** [cockroachdb/cockroach#4171]
Following the steps in the README.md to bring up a new cluster:

```
shilo:cockroach rlowe$ ./cockroach init --stores=ssd=/data
Error: unknown command "init" for "cockroach"

Did you mean this?
        quit

Run 'cockroach --help' for usage.
Failed running "init"
shilo:cockroach rlowe$ 
```

But https://github.com/cockroachdb/cockroach/commit/783d21b67b196043c90bcd373cf6c28a32aa2bca seems like it got rid of the init requirement?

**Comment by jseldess** [comment]
Yes, you're right, and the [readme](https://github.com/cockroachdb/cockroach/blob/master/README.md) is now up to date. Our [user documentation](http://www.cockroachlabs.com/docs/start-a-local-cluster.html), which is a work in progress, has the correct cluster startup process as well.
