### ISSUE TITLE
upgrade to go 1.12.11 for maintenance branches

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#41718]
This is to pick up the fix to https://github.com/golang/go/issues/34960. Go can crash when attempting to verify an invalid DSA public key in a certificate (client or server).

We should definitely upgrade in time for 19.2 and probably backport to 19.1.

**Comment by mberhault** [comment]
Ping. We should probably get this into 19.2 (and backported) soonish.

**Comment by mberhault** [comment]
Are we doing 19.1 as well?

**Comment by bobvawter** [comment]
The 19.1 branch is building from golang 1.11.  The golang security fix was only backported to the 1.12 and 1.13 branches.  Do we want to jump the 19.1 branch to a much newer golang runtime?  ISTM that we might instead want to change 19.1 to recover from this panic instead.

**Comment by bobvawter** [comment]
@bdarnell do you have a minute to weigh in on whether or not we should update the 19.1 branch from go 1.11.X to go 1.12.X?  Otherwise, we could try to create an invalid certificate and catch the relevant panic to prevent it from dropping the node.

**Comment by bdarnell** [comment]
Given the Go policy of only providing security fixes for the last two releases (and generally good backwards-compatibility), I think we need to advance the version of go used on older branches (19.1 and 2.1) so we stay on a supported version. I would not want to try and individually work up security patches/workarounds.

**Comment by kenliu** [comment]
Need to find out from product whether we need to backport a security fix back to 2.1 even though it is not officially a "supported" release right now.

**Comment by kenliu** [comment]
<deleted above comment, was in error>

**Comment by kenliu** [comment]
discussed in team meeting that we should upgrade 19.2 and 2.1 since these are supported releases

**Comment by kenliu** [comment]
19.2 is done.
2.1 is running into some complexity with vendor dependencies.

**Comment by kenliu** [comment]
@petermattis FYI we are not going to spend any further effort on upgrading 2.1. Let me know if that's an issue.
