### ISSUE TITLE
sql: Vectorized `with ordinality` mishandling limit

### ISSUE THREAD

**Issue by savoie** [cockroachdb/cockroach#41760]
The vectorized runtime may be generating the wrong number of ordinals in a `WITH ORDINALITY` column if the rows to be enumerated have been limited before the ordinality is applied.

The following logic test (in `TestLogic/ordinality`) runs as expected:
```
SELECT * FROM foo WITH ORDINALITY LIMIT 1
```

The following fails under vectorized:
```
SELECT * FROM (SELECT * FROM foo LIMIT 1) WITH ORDINALITY
```

```
pq: internal error: unexpected error from the vectorized runtime: runtime error: index out of range
```

**Comment by jordanlewis** [comment]
Thanks for the bug report!
