### ISSUE TITLE
sql: virtual schema table not implemented: pg_catalog.pg_prepared_statements

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#41778]
The PGJDBC test `testSelectPrepareThreshold0AutoCommitFalseFetchSizeNonZero` uses this catalog table, but it doesn't work.

**Comment by jordanlewis** [comment]
Adding `good_first_issue` as these are very simple to add. Any more details here besides "it doesn't work"? It seems like we're just missing the table implementation.
