### ISSUE TITLE
sql: invalid value for parameter "TimeZone": "GMT-08:00"

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#41776]
The `TimeZone` parameter should support `GMT-08:00` as a value, but it doesn't. This is used in a PGJDBC test. See https://github.com/pgjdbc/pgjdbc/blob/master/pgjdbc/src/test/java/org/postgresql/test/jdbc2/TimezoneTest.java

**Comment by jordanlewis** [comment]
Concrete repro of the issue (this is the same thing as what you're talking about with "parameter", right?):

```
root@127.0.0.1:57107/defaultdb> set timezone='GMT-08:00';
pq: invalid value for parameter "timezone": "'GMT-08:00'"
DETAIL: cannot find time zone "GMT-08:00": unknown time zone GMT-08:00
```

**Comment by droidnoob** [comment]
@jordanlewis I would like to pick this up. I'm new to this. Can you guide me through?

**Comment by rohany** [comment]
It looks like this error is thrown in `pkg/sql/set_var.go:226`. You would probably need to update the `timeutil.LoadLocation` function to fix this bug.

Let me know if you have any more questions!

**Comment by rafiss** [comment]
The fix for this particular issue could be pretty simple, but see #36864 for some additional context on a larger change we may want to do later.

**Comment by droidnoob** [comment]
So my guess is we need to take the input `GMT-08:00` and instead of setting timezone with that, we use `set timezone=-8`. @rafiss @rohany Am I on the right track?
