### ISSUE TITLE
sql: support dollar-quotes

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#41777]
Postgres supports the following:

> While the standard syntax for specifying string constants is usually convenient, it can be difficult to understand when the desired string contains many single quotes or backslashes, since each of those must be doubled. To allow more readable queries in such situations, PostgreSQL provides another way, called "dollar quoting", to write string constants. A dollar-quoted string constant consists of a dollar sign ($), an optional "tag" of zero or more characters, another dollar sign, an arbitrary sequence of characters that makes up the string content, a dollar sign, the same tag that began this dollar quote, and a dollar sign.

https://www.postgresql.org/docs/9.1/sql-syntax-lexical.html

**Comment by jordanlewis** [comment]
I wonder if these are commonly used. Either way, adding `good first issue` - this might be interesting for people who want to learn about how our lexical scanner works.

**Comment by avinashdhinwa** [comment]
@jordanlewis  Does this needs to be implemented in cockroachdb?

**Comment by rohany** [comment]
I'd start this by taking a look at `pkg/sql/parser/scan.go`, at the function `*scanner.scan`. This function is where we emit tokens to the lexing/parsing system.

**Comment by damienhollis** [comment]
@jordanlewis @rafiss @rohany I created a PR for this https://github.com/cockroachdb/cockroach/pull/44130
