### ISSUE TITLE
changefeedccl: error while purging table leases after job cancellation

### ISSUE THREAD

**Issue by aayushshah15** [cockroachdb/cockroach#41780]
Currently, any call to `acquireNodeLease()` in `lease.go` goes through a `singleflight.Group`. The group uses the `context.Context` of its first caller. The method `AcquireFreshestFromStore()` calls `acquireNodeLease()`.

Now, in `poller.go` and `table_history.go` we repeatedly call `leaseManager.AcquireFreshestFromStore()` in order to make sure the table descriptor is up to date with respect to a certain timestamp. Additionally, we also call `leaseManager.AcquireFreshestFromStore()` periodically inside `leaseManager.RefreshLeases()`.

Now consider the case where there is a job cancellation around the same time as a `RefreshLeases` call. Since the single flight group simply uses the `context` of its first caller, it's possible that it's using the changefeed job's context that's passed down into this call from the `poller`. Due to the job cancellation and because the single flight group is using the changefeed job's context, the `purgeOldVersions` call (called by `RefreshLeases`) also gets cancelled; this leaves a dangling table lease that doesn't get purged at the end of the call.

We can fix this problem by having `acquireNodeLease` create a new context inside of its single flight closure to make sure that this closure doesn't get cancelled, after copying the tags from the context it's handed.

**Comment by aayushshah15** [comment]
@danhhz @ajwerner

**Comment by danhhz** [comment]
Couldn't any caller of AcquireFreshestFromStore have this problem? It's worth considering if this should be fixed below changefeeds in `acquireNodeLease`. If so, inside the `DoChan` closure, it would copy the tags from the context it's handed but create a new one for cancellation purposes

**Comment by ajwerner** [comment]
The fix which @aayushshah15 and I discussed was indeed to not use the caller's context in `acquireNodeLease`.
