### ISSUE TITLE
Makefile ignores `glock` failures

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#4180]
If `glock` (or any part of the `.bootstrap` target) fails, `make` will not stop, because `.bootstrap` is not an explicit dependency of any other target, and the `-include` rule tells `make` to ignore errors if that file cannot be built. 

The most straightforward solution is to move `.bootstrap` from a magic `-include` rule to a regular dependency of all other targets. This allows for the possibility that we miss some, but as long as we cover the major targets of `build`, `test`, and `testrace` it will probably be fine.

**Comment by petermattis** [comment]
Can't we just change the `-include` to `include`?

**Comment by bdarnell** [comment]
I thought we needed the `-include` to handle the case when `.bootstrap` doesn't exist (as in a fresh checkout), but now that I try it it seems to work (albeit with a warning "Makefile:230: .bootstrap: No such file or directory" on the first run)
