### ISSUE TITLE
dev-inf: add k8s cron for roachprod gc

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#41804]
Need to create k8s cronjob for shared/binaries/cron_roachprod_gc.sh from https://github.com/cockroachlabs/production/pull/1071/files#diff-5b40ecdaef6a68c54fe2b83386d55712

**Comment by bobvawter** [comment]
Currently working on this.  We've had IT and Security give us a better way to manage these kinds of shared credentials.  The containers had been getting a tarball of .dirs from the old shared host dropped in; I'm reworking the setup and startup scripts to programmatically log into the various CLI systems.

**Comment by ajwerner** [comment]
Given that we fixed roachperf, this shouldn't be too much work, right? I just stumbled upon some very old clusters.
