### ISSUE TITLE
build: upgrade builder to go1.13.x

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#41808]
Title says it all. It is early in the release. We should upgrade the builder image to go1.13.3 (which is the latest at the time of writing). The issues blocking upgrade to go1.13 have been fixed, so this should just be a normal builder image Go version bump.

**Comment by kenliu** [comment]
@bobvawter can we prioritize this for week after roachconf

**Comment by bobvawter** [comment]
Working on this now.
