### ISSUE TITLE
storage, bulk: Use RocksDB format for SSTs meant for ingestion

### ISSUE THREAD

**Issue by itsbilal** [cockroachdb/cockroach#41814]
Currently, `SSTWriter` in package `bulk` uses the LevelDB format for all SSTables written by it. The RocksDB format is more appropriate for any SSTables written for ingestion (eg. snapshots).

As part of this issue, audit all usage of `SSTWriter` and change the SST format to RocksDB for any tables written for ingestion.

**Comment by dt** [comment]
Actually I just realized that with the switch to write backup (export) SSTs as close to the engine as possible (i.e. in c++) using `engine.ExportToSST`, I'm pretty sure _all_ users of SSTWriter on the Go side are now for ingestion.

**Comment by petermattis** [comment]
> Actually I just realized that with the switch to write backup (export) SSTs as close to the engine as possible (i.e. in c++) using engine.ExportToSST, I'm pretty sure all users of SSTWriter on the Go side are now for ingestion

For now. When we support `ExportToSst` for Pebble this will change.

**Comment by petermattis** [comment]
When we do this, we should also enable bloom filters for sstables meant for ingestion. Currently ingested sstables do not have bloom filters enabled.
