### ISSUE TITLE
sql: support log(b, x)

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#41837]
CockroachDB currently supports base-10 log; we should add the `log(b, x)` overload that permits specifying the log base. (https://www.postgresql.org/docs/12/functions-math.html)

This can be done by adding a new overload to `log` in `pkg/sql/sem/builtins/builtins.go`.

**Comment by avinashdhinwa** [comment]
@jordanlewis  I'm not sure if this issue is picked up. Can I pick it up if not picked by anyone else?

**Comment by awoods187** [comment]
@avinashdhinwa it looks like there is another PR already in progress here. We'd love for you to pick up another good first issue.

**Comment by otan** [comment]
seems like this is resolved by 8ce674a

**Comment by timgraham** [comment]
Shouldn't this remain open until the PR (#41848) is completed/merged? 
8ce674a is merely the latest commit in that PR.

**Comment by otan** [comment]
Sorry I misread what happened.
