### ISSUE TITLE
backup: s3 backups need the ability to be encrypted

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#41857]
From a customer:
Note that backups taken with the BACKUP statement are not encrypted even if Encryption at Rest is enabled. Encryption at Rest only applies to the CockroachDB node's data on the local disk. If you want encrypted backups, you will need to encrypt your backup files using your preferred encryption method.

This means that if the backup storage location is compromised (eg S3) there is no additional encryption protecting the data. We would like to ask that CockroachLabs prioritise the ability to encrypt backups using a similar/equivalent encryption solution to what's currently being used by the nodes eg:

**Comment by mwang1026** [comment]
being worked on here https://github.com/cockroachdb/cockroach/pull/44177

**Comment by dt** [comment]
44177
