### ISSUE TITLE
ui: support for single sign on

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#41856]
The admin ui needs to support single sign-on ideally via ADFS (OIDC / SAML).

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[3671](https://cockroachdb.zendesk.com/agent/tickets/3671) has been linked to this issue.

**Comment by dhartunian** [comment]
@piyush-singh re: telemetry on this feature, I've added a counter for the enable/disable setting. Do you think we should add to other settings?

**Comment by piyush-singh** [comment]
Would it be possible to measure successful logins using OIDC? I'd want to understand if after people enable the setting whether or not they are able to successfully configure it and login. 

A nice to have would be to see how often users attempt to login with the correct domain (e.g. @cockroachlabs.com) but without a corresponding user in the DB - if we see that over and over we could invest time into that error page to outline why a corresponding DB user is necessary and how to set that up (and link to docs probably).

**Comment by dhartunian** [comment]
Closing this issue since PR is merged, follow up require opening a new issue or using #54619
