### ISSUE TITLE
schema: force option for gc ttl jobs

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#41866]
A number of customers have been requesting a way to fast track a drop that's waiting for GC TTL.

It would be useful to either specify that you want to force the delete on the drop command (i.e.)

`DROP INDEX idx1 WITH FORCE` (or something like that)

And also be able to force a job that's already in flight but waiting on GC TTL.  
`FINISH JOB jobid/statement`

Jira issue: CRDB-5410

**Comment by BramGruneir** [comment]
@dt, feel free to reassign to SQL.  I'm not sure if this lands on bulk i/o or sql execution.

**Comment by dt** [comment]
I think the proposed `trash` db might be useful here: `DROP TABLE` would move things to trash db (instead of making a job) and maybe `DROP` on a table already in trash just kicks off the clear-range job right away. #26476

**Comment by BramGruneir** [comment]
That would work, but would be more difficult to use.  It would also be a confusing user experience.  (It's fine if we do this behind the scenes.)

**Comment by BramGruneir** [comment]
I'm thinking having to drop table twice is just weird.

**Comment by postamar** [comment]
We now have #62532 which should do the trick for tables and we've filed #77153 for indexes.
