### ISSUE TITLE
changefeeds: Changefeed creation succeeds even when kv.rangefeed.enabled is false

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#41871]
**Describe the problem**

Attempting to set up a changefeed on `laughing-ladybug`, a CockroachCloud cluster that we use internally to extract data from our roadmap in Airtable. Creating the changefeed succeeded despite some reasons that it shouldn't have:

- the `kv.rangefeed.enabled` setting was not set to `true`
- I was accessing the database as a user (`psingh`) without `admin` privileges

**To Reproduce**

1. Connect to laughing-ladybug as a non-admin user (confirm the `kv.rangefeed.enabled` cluster setting is set to false)
2. create changefeed `create changefeed for table epics into 'experimental-s3://airtable-cc/airtable-v1?AWS_ACCESS_KEY_ID=ABCD&AWS_SECRET_ACCESS_KEY=1234' with updated, resolved='5m'`
3. Changefeed is created successfully. Data appears in the above s3 bucket. 
4. The web UI will then eventually show an error on the changefeed:
<img width="1319" alt="image" src="https://user-images.githubusercontent.com/21692034/67425672-76526b80-f5a6-11e9-92b5-25493302ebef.png">

**Expected behavior**
@rolandcrosby pointed out that this should have failed at the outset since the rangefeed cluster setting was not set appropriately.

**Environment:**
 - CockroachCloud
 - CockroachDB version 19.1.4

cc @danhhz

**Comment by danhhz** [comment]
Looks like @aayushshah15 already has a fix out for returning the error earlier: https://github.com/cockroachdb/cockroach/pull/41272. We even had a test for this, but it wasn't testing what I thought it was!

The `admin` thing is news to me, that's concerning.

**Comment by danhhz** [comment]
There is a check for the admin role, I wonder what's going on. https://github.com/cockroachdb/cockroach/blob/15e4ff393d97572351b6067cf8b8bd36f34b3b75/pkg/ccl/changefeedccl/changefeed_stmt.go#L143-L145

**Comment by piyush-singh** [comment]
Did double check, can confirm that I am definitely not an admin. Changed the cluster setting and created a new changefeed yesterday, which succeeded and is still running.

```
psingh@<URI>/roadmap > show grants on role;
  role_name |     member      | is_admin  
+-----------+-----------------+----------+
  admin     | backupper       |  false    
  admin     | emily           |  false    
  admin     | joel            |  false    
  admin     | josh            |  false    
  admin     | lakshmi2        |  false    
  admin     | managed-service |  false    
  admin     | marc            |  false    
  admin     | nate            |  false    
  admin     | psingh          |  false    
  admin     | roland          |  false    
  admin     | root            |   true    
  admin     | vilterp         |  false    
(12 rows)

Time: 12.812ms
```
