### ISSUE TITLE
how to describe a table?  please document the supported sql syntax

### ISSUE THREAD

**Issue by glycerine** [cockroachdb/cockroach#4188]
Are there any docs on the SQL syntax that is supported? I can't figure out how to describe a table.
~~~
$ ./cockroach start --dev &

jaten@Jasons-MacBook-Pro:~/go/src/github.com/cockroachdb/cockroach$ ./cockroach sql --dev

****
**
** This node is being run in DEVELOPMENT mode.
**
** All data is ephemeral, and there is no security.
**
****

# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.
root@:15432> show databases;
+----------+
| Database |
+----------+
| "system" |
+----------+

...

root@:15432> create database hi;
OK
root@:15432> set database = hi;
OK
root@:15432> show tables;
+-------+
| Table |
+-------+
+-------+
root@:15432> create table hello (id string);
OK
root@:15432> desc hello;
query error: pq: syntax error at or near "desc"
desc hello;
^

root@:15432> describe hello;
query error: pq: syntax error at or near "describe"
describe hello;
^

root@:15432> show hello;
query error: pq: unknown variable: "HELLO"
root@:15432> show tables;
+---------+
|  Table  |
+---------+
| "hello" |
+---------+
root@:15432> desc table hello;
query error: pq: syntax error at or near "desc"
desc table hello;
^

root@:15432> 
~~~

**Comment by petermattis** [comment]
The syntax you're looking for is `SHOW COLUMNS FROM  <table>`. You can also do `SHOW INDEX FROM <table>` to display indices on a table.

**Comment by glycerine** [comment]
Oy, okay. 

Thanks for the syntax. Closing this out as this answered my question.

As a dramatic usability improvement, please consider implementing a simple "desc my-table" at some point in the future. It should show all the information about the table, including column names, types if any, and indexes.

**Comment by jseldess** [comment]
@glycerine, just want to mention that we're building out user docs on CockroachDB, including the CockroachDB SQL syntax. You can already find some basics here: http://www.cockroachlabs.com/docs/basic-sql-commands.html

**Comment by glycerine** [comment]
@jseldess Excellent, thanks a big help! Thank you.

**Comment by glycerine** [comment]
Quick question -- what is the syntax for creating an index during create
table?

Thanks!

Jason

**Comment by petermattis** [comment]
```
CREATE TABLE c (
  id INT PRIMARY KEY,
  foo INT,
  bar INT,
  INDEX c_foo_idx (foo),
  INDEX (foo),
  INDEX c_foo_bar_idx (foo ASC, bar DESC),
  UNIQUE (bar)
)
```

FYI, this was taken from https://github.com/cockroachdb/cockroach/blob/master/sql/testdata/table#L44-L52. While we don't have adequate documentation (yet), we do have a lot of test data.

**Comment by glycerine** [comment]
@petermattis Awesomeness. Thanks!
