### ISSUE TITLE
Bug of Database cache 

### ISSUE THREAD

**Issue by Cynthia-Lee97** [cockroachdb/cockroach#41894]
**Describe the problem**
When I started the three-node cluster, I created the database, and created a table under the database, and looked up the data in the table at Node1. Then I looked up the table, renamed the database, and looked up the table again at Node2. Finally, I looked up the table as the original name of the database at Node1, first to retrieve the table information, and second to show that it does not exist. 
**To Reproduce**
This means that the database cache does not update the database cache of this node when other nodes update the database and still looks for the old value first.

steps to reproduce the behavior(Each node is a session.Each line means the statements executed sequentially in the same session)

1. Set up CockroachDB cluster
2. Node1: create database a; create table a.t(a int);select * from a.t;
    Node2: select * from a.t; alter database a rename to b; select * from b.t;
    Node1: select * from a.t; (Now we can get the data in table a.t)
    Node1: select * from a.t; (Now we find that table a.t does not exist)

**Expected behavior**

After I change the database at Node2, the first time I look up the data of a.t at Node1, it should show the table does not exist.

**Environment:**
 - CockroachDB version [19.2.0]
 - Server OS: [Linux]
 - Client app [cockroach sql]

**Comment by ricardocrdb** [comment]
Hi @Cynthia-Lee97 

Apologies for the delayed response. We appreciate your testing of this and bringing it up to our team. There is issue [#41942](https://github.com/cockroachdb/cockroach/issues/41942) that has been opened to track this issue. Please feel free to follow that issue for further updates.

I will go ahead and close this issue.
