### ISSUE TITLE
sql: we support bigger range for OID than Postgres

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#41904]
Here is a simple repro:
```
root@127.0.0.1:49800/defaultdb> select 123456789012::OID;
      oid       
+--------------+
  123456789012  
(1 row)

Time: 322µs

root@127.0.0.1:49800/defaultdb> \q
Yahors-MacBook-Pro:cockroach yahoryuzefovich$ psql
psql (11.4)
Type "help" for help.

yahoryuzefovich=#  select 123456789012::OID;
ERROR:  OID out of range
```
As mentioned by Matt and Raphael, this can "bite us" in the future. The concerns are:
- we've had bugs in the past because our types were larger than postgres, but then they didn't end up fitting during text/binary encoding and we were silently truncating data
- apps that read an OID in one query into a 32-bit variable client-side, then use it to look up something else in pg_catalog and get disappointed

Epic CRDB-14489
Jira issue: CRDB-5408

**Comment by rafiss** [comment]
This is an example of a PR needed because this bit us: https://github.com/cockroachdb/cockroach/pull/61148

I added TODOs there about making the OID size 4 bytes. We should still do this.
