### ISSUE TITLE
ui: "Slow Command Queue Entries" no longer applicable

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#41911]
I see we have a "Slow Command Queue Entries" chart under the "Slow Requests" dashboard (metrics page). This is no longer applicable (has not been for a for a few releases now, though I'm not sure exactly when the Command Queue was ripped off). This should be removed.

**Comment by Koorosh** [comment]
`Slow Command Queue Entries` chart has been replaced with`Slow Latch Acquisitions` metric (https://github.com/cockroachdb/cockroach/commit/eb38f2002e2dd275dd4e47c0b96c0405b655f71c)
