### ISSUE TITLE
cli: how to configure a zone file to only expect local node (replica count 1) only

### ISSUE THREAD

**Issue by glycerine** [cockroachdb/cockroach#4192]
@tamird Would you elaborate on how to create a zone file to silence the replica 1 warnings in the log?

https://github.com/cockroachdb/cockroach/issues/3060

> You can silence the error by updating the zone config to replicate the data to just a single node. 

I can't seem to find any docs for this.

Thanks!

Jason

**Comment by tamird** [comment]
There have been some changes since that comment was made. Today, it is not possible to set the zone config for non-structured data (e.g. the first range). There are TODOs sprinkled in the code about this. cc @mberhault

**Comment by glycerine** [comment]
Thanks for the update. It seems like a natural stage in the development process to run fully configured on a single host -- all except for redundancy. With your blessing I'll leave this open as a feature request.

**Comment by petermattis** [comment]
As of #4866, you can do:

```
cockroach zone set .default "replicas: [attrs: []]"
```

Yes, that syntax is opaque, but it will configure the default zone to only use 1 replica.

**Comment by jseldess** [comment]
Doc updates:

- Replication zone configuration covered here: https://www.cockroachlabs.com/docs/configure-replication-zones.html
- Details about stopping log errors when running single-node cluster: https://www.cockroachlabs.com/docs/troubleshoot.html#replicas-failing-on-a-single-node-cluster

**Comment by glycerine** [comment]
Very nice. Thank you @jseldess.

A micro nit: To make it easier on users who may not be familiar with YAML, I would suggest telling them to use the single line syntax for arrays, rather than the one currently in the docs that uses an implicit newline and so could be harder for newbies to parse themselves correctly from the docs. I.e. use the syntax Peter suggested above:

```
$ ./cockroach zone set .default "replicas: [attrs: []]"
```
rather than the YAML `-` syntax for arrays with one element of the array on each new line. Currently:

```
$ ./cockroach zone set .default 'replicas:
- attrs: []'
```
which runs a small risk that the user may not see or realize that the 2nd line is needed too.

**Comment by jseldess** [comment]
Good point, @glycerine. I'll make that update soon.

**Comment by petermattis** [comment]
@jseldess Did the docs get updated? I'm reassigning to you. Feel free to close if this is now adequately addressed in the docs.

**Comment by jseldess** [comment]
@glycerine, sorry for the delay. It's true that the single line syntax works fine, and is more intuitive, for the case where you want to change to one replica. But I can't get that syntax to work for multi-replica cases. Neither of these work, for example:
```
$ cockroach zone set .default 'replicas: [attrs: [us-east-1a], attrs: [us-east-1b], attrs: [us-west-1a]]'
$ cockroach zone set .default 'replicas: [attrs: [us-east-1a]], [attrs: [us-east-1b]], [attrs: [us-west-1a]]'
```
Any ideas. Regardless, for the case where you want to change the default config to use one replica, I've updated the docs to use the simpler format: https://github.com/cockroachdb/docs/pull/434

**Comment by jseldess** [comment]
Disregard that last comment. Realized first one works fine:
```
$ cockroach zone set .default 'replicas: [attrs: [us-east-1a], attrs: [us-east-1b], attrs: [us-west-1a]]'
```
