### ISSUE TITLE
sql: database renames/drops are not transactional

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#41942]
This was discussed earlier on the forum: https://forum.cockroachlabs.com/t/renaming-database-in-a-transaction/2397/8
and noticed recently in #41894
However no issue was filed yet.

There are two phases during a database rename:

1. the database descriptor is updated, and announced to every other node
2. the system.namespace table is updated

The name of a database is both in the descriptor and the system.namespace table.

Step 1 is non-transactional. The rename will be announced to other nodes even if the transaction is aborted.

Step 2 is transactional, and will be rolled back if the transaction aborts.

This yields a surprising and undesirable behavior: when run inside begin…commit, it’s possible for a rename to be half-done - not persisted in storage, but visible to other nodes or other transactions. This violates A, C and I in ACID. Only D is guaranteed: if the transaction commits successfully, the new name will persist after that.

**Comment by knz** [comment]
cc @ajwerner for triage - maybe it was already established somewhere else?

**Comment by lucy-zhang** [comment]
Let's make this the issue for making database renames/drops transactional. This is all dependent on the new leasing system (#47149).
