### ISSUE TITLE
Can not restore empty database (but backup works)

### ISSUE THREAD

**Issue by mattcrdb** [cockroachdb/cockroach#41962]
**Describe the problem**

Currently, our enterprise backup will backup an empty database to an s3 bucket, but will run into an error when trying to restore.

For example if you backup defaultdb: 
```
pq: no tables found: DATABASE defaultdb
```

this presents a problem for those running a script that runs a show databases command and then backs up all of them, and at a certain point in time then restores all of those backed up.

As we are aware, the backup/restore works on a database level so one can cherry-pick those that they know are not empty, but this is not a strong solution. Setting up exclusions for `defaultdb` and `postgres` databases will also not suffice as we've seen a use case from one of our customers where there are multiple other user-created databases that are just left empty.

**To Reproduce**

Try to backup an empty database to s3 and then restore it. 

**Expected behavior**
potentially an empty database to be created and the script running this not to halt.

**Additional context**
Client restore script is halting.

**Comment by mattcrdb** [comment]
cc @BramGruneir for more information on this use case.

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[3921](https://cockroachdb.zendesk.com/agent/tickets/3921) has been linked to this issue.

**Comment by lucy-zhang** [comment]
I think this behavior was intentional, but it's also not the right behavior, apparently. What we should really do is short-circuit and just do nothing with no error in this case.
