### ISSUE TITLE
Enterprise BACKUP returns secret keys in error message

### ISSUE THREAD

**Issue by mattcrdb** [cockroachdb/cockroach#41998]
**Is your feature request related to a problem? Please describe.**
Currently when performing an enterprise backup, if there is an error in the s3 secret key, then the key id and the key itself are returned to the client. This causes a privacy concern for those abstracting the keys away and entering them as environment variables.

a customer(C) has seen the keys returned in an error in the following scenarios:

1. There is a syntax error in the statement 
2. A backup with the same name already exists
3. The bucket doesn't exist or is in a different region

They are calling the backup using `cockroach sql -e "BACKUP DATABASE db_name to s3://bucket"

**Describe the solution you'd like**
An option for a less verbose mode in the backup flag, potentially to suppress errors like this exposing keys. 

**Describe alternatives you've considered**
As the keys need to be provided from the client, they can scrape the stderr and obfuscate it away.

**Additional context**
A chat with @dt revealed that the reason this is exposed is the way AWS handles `+` as spaces and it's used for debugging purposes.

**Comment by mattcrdb** [comment]
cc @rkruze for any additional information he wants to add.

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[3934](https://cockroachdb.zendesk.com/agent/tickets/3934) has been linked to this issue.

**Comment by shermanCRL** [comment]
@dt’s point is valid, that debugging credential failures is a use case. He also points out that we are simply echoing back a secret that the caller already knows.

My feeling is that we should redact them and accept the trade-off of debugging difficulty. Perhaps the error message can advise something like ‘if your secret key contains a `+`, it needs to be escaped like so.

What is the answer for that escaping problem, btw? Replace the `+` with `%2b`? If the caller has a url encoding utility at their disposal, they should probably use that.

Next step is for an engineer to track down those error messages and deal with this narrow case first.

**Comment by shermanCRL** [comment]
I believe the error in question is returned by [checkForPreviousBackup](https://github.com/cockroachdb/cockroach/blob/c9f689fa3fe672f53b4dc74951d717ecd502c665/pkg/ccl/backupccl/manifest_handling.go#L975).

As I’m browsing the code, I think a starting place should be that URI’s are of the [`url.URL`](https://golang.org/pkg/net/url/) type as much as possible. For example, [getURIsByLocalityKV](https://github.com/cockroachdb/cockroach/blob/39cd953bdf9057874d531ed2868d08aaa13a647d/pkg/ccl/backupccl/backup_planning.go#L227) should return URIs.
