### ISSUE TITLE
"Can't parse available memory from cgroups" during client startup

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#4201]
Just upgraded to dbe4513631028099ec4e7fbcdd6f45b52a88507a. Upon starting `cockroach sql` (not server) the following is reported first:

```
I0207 18:33:39.670121 8644 server/context.go:160  can't parse available memory from cgroups (strconv.ParseUint: parsing "9223372036854771712\n": invalid syntax), setting default rocksdb cache size to 30108MB (half of system memory)
```

Output from the command `free`:

```
             total       used       free     shared    buffers     cached
Mem:           58G       2.2G        56G        19M        36M       1.8G
-/+ buffers/cache:       390M        58G
Swap:           0B         0B         0B
```

**Comment by tamird** [comment]
Looks like we need to strip that newline. @knz care to work up a PR?

**Comment by bdarnell** [comment]
The client shouldn't even be hitting this code path. Looks like we need some refactoring in the `cli` package to avoid initializing any server configuration until we know we're running a server-side command.

**Comment by knz** [comment]
@bdarnell let's look at this in #4203.
