### ISSUE TITLE
sql: recommend/hint how to configure the changefeed poll interval

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#42025]
Recommended/suggested by @nvanbenschoten :

> In order to get changefeeds responding with low latency (~20ms response times instead of ~1s response times), I had to make the following cluster setting changes. Again, this second cluster setting would probably be a show-stopper for anyone who didn't work on CockroachDB. The first is at least listed in an error if not already set when running CREATE CHANGEFEED.

> ```
> SET CLUSTER SETTING kv.rangefeed.enabled = true;
> SET CLUSTER SETTING changefeed.experimental_poll_interval = '20ms';
> ```

A couple action items would probably help:

- in the contextual help of the CREATE CHANGEFEED statement we could point to the cluster setting
- in docs, we could mention the cluster setting too
- the SQL shell could inspect the current value and display it at the top of a changefeed result stream, with a suggestion of how to change it (see also #42024)

Jira issue: CRDB-6337

**Comment by knz** [comment]
Also related: #28844

**Comment by knz** [comment]
This is made hard(er) by the use of a changefeed inside a sub-query see #42026

**Comment by knz** [comment]
@otan another candidate for notices?

**Comment by otan** [comment]
sounds like an idea! should we document this before adding it as a notice?
alternatively, any messaging you have in mind for the meantime? not as experienced in this area and the wording should probably come from someone who knows it better

**Comment by ajwerner** [comment]
We should not recommend `SET CLUSTER SETTING changefeed.experimental_poll_interval = '20ms';` in the general case. That will be very expensive for many clusters. Users of changefeeds aren't definitely looking for low latency. If they are, the unfortunate truth is that our current implementation can only provide it at a very high cost.

**Comment by ajwerner** [comment]
A changefeed will pull all table descriptors (not just the ones you're interested in) that have changed over the interval every interval. With TBI maybe that's no so bad (and we do now have TBI again for this request).
