### ISSUE TITLE
sql: document using the sinkless CREATE CHANGEFEED as CTE

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#42026]
Requested by @nvanbenschoten :

> it would have been nice to create changefeeds that didn't listen to the entire table. Again, I think we're aware of this limitation and it used to (?) be possible to write a statement like the following, but it won't scale to large tables:

> ```
> SELECT * FROM [CREATE CHANGEFEED FOR TABLE kv] WHERE k > 10
> ```

> We should add support for predicate pushdown on changefeeds. Is there already an issue for this? I'm having trouble finding one.

It's already possible in the syntax, and seems to run properly:

```sql
WITH a AS (CREATE CHANGEFEED FOR rides)
SELECT * FROM a WHERE WHERE k::STRING LIKE '%a%'
```

This correctly produces the following plan:

```
        tree       |    field    |        description
+------------------+-------------+---------------------------+
                   | distributed | false
                   | vectorized  | false
  render           |             |
   └── filter      |             |
        │          | filter      | key::STRING LIKE '%a%'
        └── plugin |             |
```

However, there are two separate issues that need to be handled:

- [ ] it's not documented - there should be some contextual help for it
- [ ] it really makes it hard to fix #42024 and #42025

Jira issue: CRDB-5400

**Comment by jordanlewis** [comment]
cc @vilterp

**Comment by knz** [comment]
@nvanbenschoten I updated the PR description. It turns out (as @RaduBerinde helped me discover) this is already possible.

**Comment by nvanbenschoten** [comment]
The bigger ask here is to push the predicate all the way into the changefeed so that we're only watching a small part of the table. As is, this will place a filter on top of a table-wide changefeed, which will be unusable for large tables.

**Comment by ajwerner** [comment]
> The bigger ask here is to push the predicate all the way into the changefeed so that we're only watching a small part of the table. As is, this will place a filter on top of a table-wide changefeed, which will be unusable for large tables.

Definitely agree. Perhaps we should split that off into its own issue. There are lots of use cases unlocked by filtered changefeeds. Here's a bit of a dump of my thoughts on the problem. 

Firstly we should make sure we keep this tightly scopes lest we end up setting out to build an unprincipled Materialize. The statement should only allow a single table reference and the predicates, at least initially, should not permit any subqueries. 

I envision the grammar being extended to include an `opt_where_clause` on the `create_changefeed_stmt`. This is currently hard to express directly in the grammar but essentially we need to ensure that the `expr` in the `where_clause` does not contain any `select_no_parens` as a child anywhere. 

A first step to implementing any of this is likely to port the changefeed code to use the optimizer. Currently the planning and execution logic is very tightly coupled. See https://github.com/cockroachdb/cockroach/blob/d887d910ac77447798c790925b162bd6a5153976/pkg/ccl/changefeedccl/changefeed_stmt.go#L95

Adopting the optimizer is likely going to be similar in spirit to the work done in this PR which adopted the optimizer for EXPORT: https://github.com/cockroachdb/cockroach/pull/39312. My sense is we'll want to ensure that the optimizer only looks at the primary index for the purposes of planning. 

After that I'm hopeful that (and I'm sure many details I haven't accounted for) we can have a plan which will at least give us a smaller set of spans on which we'll need to subscribe for event.

Once we have a constrained set of spans for the changefeed we need to do the actual row-level filtering. I'm not totally clear on where this should live. We could imagine putting it as low as in the poller which might allow us to track fewer intents. A probably easier approach would be to do the filtering in the changeAggregator.

**Comment by knz** [comment]
still current

**Comment by ajwerner** [comment]
This relates pretty closely to https://github.com/cockroachdb/cockroach/issues/77849. It's make the pattern much easier to reason about. Of course, there's always the issue of making the query constraints map down to the table so we can scan an index or something, but that's a different thing altogether ([#56949 CDC: Support Filters for Changefeeds](https://github.com/cockroachdb/cockroach/issues/56949))

**Comment by miretskiy** [comment]
Even though we (still) don't recommend changefeeds as CTEs, the recent work around
changefeed predicates (including integration with optimizer), probably means
that this issue should be closed.

I also suspect that it is not as simple as "allow CTE" -- in particular, I think addressing
changefeed as cte would require us to think through the implications of performing
streaming joins.

Feel free to reopen if i'm utterly wrong.
