### ISSUE TITLE
cli/sql: concurrent SQL shells overwrite each other's history

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#42027]
Reported by @nvanbenschoten 

> Because the CREATE CHANGEFEED statement never finishes cleanly, the only way to exit it is to kill the SQL shell. This has the result of forgetting to add the statement to the shell history, presumably because the shell history is updated on the successful completion of a statement.

This problem also exists for other statements.

Strangely, this problem should not exist, because the call to `addHistory()` in the shell is performed _at the beginning_ (before the SQL is executed). This was done specifically to address this problem. Therefore I am labeling this as a bug.

We need to dig into the readline code to see whether that code mistakenly fails to flush the data to file at the same time.

**Comment by knz** [comment]
@nvanbenschoten can you double check this? A casual test locally confirms that it works fine.

**Comment by nvanbenschoten** [comment]
Thanks for prompting me to confirm. Upon closer inspection, this seems to be due to the behavior of the shell history when multiple shells are active. With only a single shell creating and canceling a changefeed, things work ok. However, when I start a changefeed in one shell and then manipulate a table in another, the changefeed statement appears to be overwritten in the shell history. When the changefeed is canceled and restarted, the statement is nowhere to be found in the shell history. Do you know how this is supposed to work? Is this the expected behavior?

**Comment by knz** [comment]
> However, when I start a changefeed in one shell and then manipulate a table in another, the changefeed statement appears to be overwritten in the shell history. 
> When the changefeed is canceled and restarted, the statement is nowhere to be found in the shell history. Do you know how this is supposed to work? Is this the expected behavior?

Yes, access to the history file is not protected between multiple processes.  The thing writes its entire history buffer to the history file on each command. 

Your shell has the same limitation.

I don't know that improvements to the history system are the right way to go about this. Interactive query cancellation seems to be a better direction?

But nevertheless I'll rename the PR accordingly.

**Comment by knz** [comment]
As a workaround, you can set the env var `COCKROACH_SQL_CLI_HISTORY` to different values in the two different shells, so that they don't overwrite each other's history. The default value is `.cockroachsql_history`.

**Comment by jseldess** [comment]
Documented in https://github.com/cockroachdb/docs/pull/7118.

**Comment by knz** [comment]
In light of the existence of the env var COCKROACH_SQL_CLI_HISTORY
and the documented known limitation,
and the fact this behavior is shared with other unix shells
we'll close this issue without code change
