### ISSUE TITLE
colexec: add projections for TIMESTAMP

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#42044]
When #41662 is merged, we will have the support for `TIMESTAMP` type, but projections with timestamps will not be supported because other types (like `INTERVAL`) that are alongside the timestamps in the binary operations are still unsupported.

**Comment by jordanlewis** [comment]
Surely we can still support stuff like `timestamp < timestamp` right? Comparison projections.

**Comment by yuzefovich** [comment]
Yes, the comparison (between two timestamps) operator projections should work, but the binary operator projections are missing (since those exist only with unsupported types).
