### ISSUE TITLE
colexec: TPCH query 20 returns different results with vec on and off

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#42047]
While looking at #42022, I (accidentally looking at the wrong query) noticed that we return different results for query 20 of TPC-H benchmark with the vectorized (232 rows, correct) and with the row-by-row (186 rows, correct) engines. I thought that maybe flat bytes PR is to blame, but reverting back to `d9bf3e90bd6d6ddf16d0a0cef0e4f5a95158d62d` (just before the flat bytes PR on master) didn't help - now vectorized returned 233 rows.

I'm not quite sure what the culprit is, but I'd guess it's a hash join (the query has INNER, SEMI, and RIGHT OUTER joins).

**Comment by asubiotto** [comment]
Looking into this

**Comment by asubiotto** [comment]
Simplifying the query a little bit (and making the filter all-inclusive) to:
```
SELECT
                        ps_suppkey
                FROM
                        partsupp
                WHERE
                        ps_partkey IN (
                                SELECT
                                        p_partkey
                                FROM
                                        part
                                WHERE
                                        p_name LIKE 'forest%'
                        )
                        AND ps_availqty >= (
                                SELECT
                                        0.0 * sum(l_quantity)
                                FROM
                                        lineitem
                                WHERE
                                        l_partkey = ps_partkey
                                        AND l_suppkey = ps_suppkey
                                        AND l_shipdate >= DATE '1994-01-01'
                                        AND l_shipdate < DATE '1994-01-01' + INTERVAL '1' YEAR
                        );
```
Results in a disconnect between the `EXPLAIN ANALYZE` similar to #42191. In the vectorized plan:
![image](https://user-images.githubusercontent.com/10560359/68402902-13d2a100-014a-11ea-8d3c-97b9ca4a4ddb.png)

`Aggregator/4` outputs 712317 tuples, while in the non-vectorized case:
![image](https://user-images.githubusercontent.com/10560359/68403357-ce62a380-014a-11ea-8e3e-7864d80fbe2c.png)

The same aggregator outputs 543210 tuples

**Comment by asubiotto** [comment]
I wonder if we can reproduce this with a simple `RIGHT OUTER JOIN`
