### ISSUE TITLE
colexec: incorrect interaction between aggregates and flat bytes

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#42049]
While looking into https://github.com/cockroachdb/cockroach/issues/41108#issuecomment-547760479, I noticed that there is an incorrect interaction between aggregate functions and flat bytes:
```
root@:26257/tpch> SELECT c_custkey, c_name, sum(l_extendedprice * (1 - l_discount)) AS revenue, c_acctbal, n_name, c_address, c_phone, c_comment FROM customer, orders, lineitem,
nation WHERE c_custkey = o_custkey AND l_orderkey = o_orderkey AND o_orderDATE >= DATE '1993-10-01' AND o_orderDATE < DATE '1993-10-01' + INTERVAL '3' MONTH AND l_returnflag = 'R' AND c_nationkey = n_nationkey GROUP BY c_custkey, c_name, c_acctbal, c_phone, n_name, c_address, c_comment ORDER BY revenue DESC LIMIT 20;
pq: internal error: unexpected error from the vectorized runtime: cannot overwrite value on flat Bytes: maxSetIndex=1304, setIndex=281, consider using Reset
```
This can be reproduced by running query 10 of TPCH benchmark.

Here is what I'm seeing:
1. an `orderedAggregator` processes several batches until it has at least 1024 tuples to return (in the case above that number happens to be 1304)
2. the aggregator then returns first 1024 tuples from `a.scratch` and copies over the remaining 280 into the beginning of the scratch
3. however, the bytes do this `copy` in a special way - the data is copied over, but `maxSetIndex` is not overridden
4. when the aggregate function tries to set (what it thinks the next index is) at position 281, we panic because flat bytes thinks that it has data up to 1304 position.

It feels to me that, in general, flat bytes are behaving as expected, but in this particular case, we need to have a way to specify the length of the "slice" after copying. Roughly, I'm thinking the interaction would be as:
```
copy(destBytes[destIdx:], srcBytes[srcStartIdx:srcEndIdx])
destBytes = destBytes[:srcEndIdx-srcStartIdx]
```
which would translate into
```
destBytes.CopySlice(srcBytes, destIdx, srcStartIdx, srcEndIdx)
destBytes.SetLength(srcEndIdx-srcStartIdx)
```
In the particular case of the aggregate functions, `destIdx = 0`, `srcStartIdx = a.scratch.outputSize`, `srcEndIdx = a.scratch.resumeIdx + 1`.

@asubiotto thoughts?

**Comment by asubiotto** [comment]
I think we should be using `append` in this case, which does truncate past the last element of the destination slice:
```
func main() {
	a := []int{1, 2, 3, 4, 5}
	b := []int{6}
	fmt.Println(append(a[:0], b...))
	copy(a[:1], b)
	fmt.Println(a)
}
---
[6]
[6 2 3 4 5]
```

**Comment by yuzefovich** [comment]
Yes, great suggestion, thanks!
