### ISSUE TITLE
sql: Dropping an Index fails with "transaction is too large to complete; try splitting into pieces" error

### ISSUE THREAD

**Issue by ricardocrdb** [cockroachdb/cockroach#42064]
User is using v19.1.3 and is attempting to drop an index on a table that contains 500+ million rows, and is receiving the following error from the cockroach sql shell:
`job-insert: transaction is too large to complete; try splitting into pieces`

A job for the schema change doesn't appear in any logging, nor does it appear in the `events.json` or `crdb_internal.jobs.txt` output files from the debug zip.

DDL and debug zip are located [here](https://drive.google.com/drive/u/0/folders/1UN_KC_BsnqRfC6Z9MNcqchleUv69NrpT)

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[3961](https://cockroachdb.zendesk.com/agent/tickets/3961) has been linked to this issue.

**Comment by knz** [comment]
I suspect the error occurs because they ran DROP INDEX inside BEGIN...COMMIT _alongside_ other DDL statements (perhaps other DROPs, maybe some UPDATE/INSERT?)

Can you ask how they ran the "drop index" instead of asking the table CREATE.

**Comment by ricardocrdb** [comment]
According to the user, the steps in which the command were tested were simply:

1 - cockroach sql --certs-dir <my certs dir> --url <my url>

2 - drop index my_index;

The user had reattempted using these steps and is able to reproduce the same error as above.

**Comment by knz** [comment]
Ok I looked into the debug.zip. There are 7 nodes (out of 13) still running CockroachDB 2.1.

This means they haven't upgraded to 19.1 fully yet, and they are thus still restricted by txn limits in 2.1 that were lifted in 19.1.

I'd recommend completing the upgrade to 19.1, bump the cluster version and then try again.

**Comment by ricardocrdb** [comment]
Hey @knz 

The user claims that there are 5 active nodes in the cluster, all on 19.1.3. Please see the screenshots provided by the user showing the 5 active nodes, and the 8 decommissioned nodes. These screenshots are located in the same Google drive location as previously linked. Let me know if there is anything else needed to troubleshoot this further.

**Comment by lucy-zhang** [comment]
Closing as I doubt we will be able to ever repro this issue.
