### ISSUE TITLE
sql: provide a way to reject or pause all DDL statements while upgrading a cluster

### ISSUE THREAD

**Issue by rkruze** [cockroachdb/cockroach#42065]
**Is your feature request related to a problem? Please describe.**
Currently, it is not recommended to issue DDL statements while the cluster is undergoing an upgrade. 

**Describe the solution you'd like**
Instead of asking all users to stop issuing DDL statements, we should provide a way in which we could pause or reject all DDL statements for a given set of time until the upgrade has finished. 

Jira issue: CRDB-5392

**Comment by dt** [comment]
paused is certainly much better than _running_: we don't need to worry about in-flight work, inter-node RPCs and coordination, etc. The _least-possible risk_ would be even further: have nothing in-progress -- either running or paused -- from before the upgrade. That would mean there is no chance of pre- and post-upgrade state representations causing problems when it is resumed. That said, just being paused would go a long way: we'd just need to ensure the state in job itself is correctly handled, and not have all the RPCs and behavior of the processors to consider.

**Comment by postamar** [comment]
Is this still relevant? I thought that the expectation was that everything fully works in mixed-version clusters.

**Comment by ajwerner** [comment]
I think this is less relevant. I do think we need to talk about jobs and their version support. That task is represented by https://github.com/cockroachdb/cockroach/issues/73808, and, to a lesser extent, https://github.com/cockroachdb/cockroach/issues/74151.
