### ISSUE TITLE
teamcity/example-orms: example-orms isn't a pinned revision when running CI

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#42083]
https://github.com/cockroachdb/cockroach/pull/42042, a backport to `release-v2.1` was failing on TC due to Example ORM tests. Debugging that I noticed that our TC setup does not use a pinned revision of example-orms when running the test suite (it simply picks up whatever is on `master`). This means that any and every change pushed out to https://github.com/cockroachdb/examples-orms is what gets used for all future TC runs against all branches (including all the way back to `release-v2.1`). This is probably not what we want (https://github.com/cockroachdb/cockroach/pull/42042#issuecomment-548589338).

Jira issue: CRDB-5389

**Comment by irfansharif** [comment]
+cc @rohany, @rafiss for triage.

**Comment by kenliu** [comment]
@apantel I think this is related to the work you are doing with pinning versions
