### ISSUE TITLE
hope to update multi-table in one sql

### ISSUE THREAD

**Issue by yangxuanjia** [cockroachdb/cockroach#42095]
[1] update t11,t12 set t11.c=t12.cc where t11.a=t12.aa and t11.b=t12.bb;
[2] update t11,t12 set t12.cc=t11.c where t11.a=t12.aa and t11.b=t12.bb;
[3] update t11,t12 set t11.c=999,t12.cc=888 where t11.a=t12.aa and t11.b=t12.bb;

I modify the cockroachDB code,  implement the label 1, like:
```sql
select * from t11;
+------+------+------+
| a    | b    | c    |
+------+------+------+
|    1 | a1   |  100 |
|    2 | a2   |  100 |
|    3 | a3   |  100 |
|    4 | a4   |  100 |
|    5 | a5   |  100 |
|    6 | a6   |  100 |
+------+------+------+
6 rows in set (0.00 sec)

select * from t12;
+------+------+------+
| aa   | bb   | cc   |
+------+------+------+
|    3 | a3   |  333 |
|    1 | a1   |  111 |
|    4 | a4   |  444 |
+------+------+------+
3 rows in set (0.00 sec)

update t11,t12 set t11.c=t12.cc where t12.aa=t11.a and t12.bb=t11.b;
Query OK, 3 rows affected (0.07 sec)

select * from t11;
+------+------+------+
| a    | b    | c    |
+------+------+------+
|    1 | a1   |  111 |
|    2 | a2   |  100 |
|    3 | a3   |  333 |
|    4 | a4   |  444 |
|    5 | a5   |  100 |
|    6 | a6   |  100 |
+------+------+------+
6 rows in set (0.00 sec)

select * from t12;
+------+------+------+
| aa   | bb   | cc   |
+------+------+------+
|    3 | a3   |  333 |
|    1 | a1   |  111 |
|    4 | a4   |  444 |
+------+------+------+
3 rows in set (0.00 sec)
```
But label 2 and label 3 is too hard for me, because the lower code all design for single table.

**Comment by ajwerner** [comment]
I'm having a hard time understanding your question. What do you mean by `I modify the cockroachDB code`?

In general it'd be better to ask this sort of question in the [Forum](https://forum.cockroachlabs.com/) or perhaps a bit worse, [Gitter](https://gitter.im/cockroachdb/cockroach). I encourage you to take a look at https://www.cockroachlabs.com/docs/stable/common-table-expressions.html as they can be helpful for more complex queries.
[1] update t11,t12 set t11.c=t12.cc where t11.a=t12.aa and t11.b=t12.bb;
```
UPSERT INTO t11 (SELECT  t11.a, t11.b, t12.cc AS c FROM t11 JOIN t12 ON (t11.a = t12.aa AND t11.b = t12.bb));
```
[2] update t11,t12 set t12.cc=t11.c where t11.a=t12.aa and t11.b=t12.bb;
```
UPSERT INTO t12 (SELECT  t12.aa, t12.bb, t11.c AS cc FROM t12 JOIN t11 ON (t11.a = t12.aa AND t11.b = t12.bb));
```
[3] update t11,t12 set t11.c=999,t12.cc=888 where t11.a=t12.aa and t11.b=t12.bb;
This one says, for all rows in the intersection of the two tables, set both of their c values to some constant. You could do this one using a common table expression like so:
```

WITH
    joined AS (SELECT t11.a, t11.b FROM t11 JOIN t12 ON t11.a = t12.aa AND t11.b = t12.bb),
    t11_update AS (UPSERT INTO t11 (SELECT a, b, 999 AS c FROM joined) RETURNING NULL),
    t12_update AS (UPSERT INTO t12 (SELECT a AS aa, b AS bb, 888 AS cc FROM joined) RETURNING NULL)
SELECT
    count(*) AS updated
FROM
    joined;
```
