### ISSUE TITLE
cli: recommendations for bulk loading

### ISSUE THREAD

**Issue by glycerine** [cockroachdb/cockroach#4213]
Two quick questions --

When bulk loading an initial dataset, in the RDBMS world it is recommended one wait to add indexes until after the initial load, to make indexing faster (later) in batch.  Is there a similar recommendation in force for cockroachdb?

When loading bulk data into MySQL (say from a .csv comma separated file), there is a separate LOAD DATA INFILE facility to make this task easier.  Is there comparable bulk loading functionality for cockroachdb?

Thanks!

Jason

**Comment by vivekmenezes** [comment]
Jason,

We don't have a bulk update facility at the moment, but we plan on working
on a few of them post beta launch. What data file type would you like to to
be able to bulk update into cockroach? Thanks

**Comment by glycerine** [comment]
Hi @vivekmenezes, good to know, thanks. And thanks for asking what I'd like to see. I would find much use for

1. a CSV loader
2. a loader for messagepack and json records
3. a loader for the time-series TMFRAME standard binary format; I wrote this recently for time series applications, see https://github.com/glycerine/tmframe There is go marshaling and unmarshaling code there already.

Re the first question, any thoughts on batch loading vis-a-vis indexes?

**Comment by vivekmenezes** [comment]
Thanks for sharing your needs.

Regarding working with the current setup it is better to define the entire
schema (including all indexes) before bulk uploading the data using SQL
INSERTs.

In the future I imagine we could add in a better facility to backfill
secondary indexes more efficiently, but that hasn't been done yet.

Thanks!

**Comment by knz** [comment]
I think this issue should be converted to a doc bug. We should:
1) explain what are the recommended approaches to get data into CockroachDB
2) tell users about backup/restore functionality

**Comment by knz** [comment]
@glycerine FYI we are working on enterprise-grade backup/restore. Also we will put more information about bulk loading in our docs. 

To answer your initial question, at this point we recommend loading the data first and then adding indexes afterwards. 

Then regarding your question about which formats to bulk load from, I have filed a separate issue for this: #10261.

Is there more you are expecting from us with regard to this issue?

**Comment by glycerine** [comment]
> Is there more you are expecting from us with regard to this issue?

Hi @knz, I think you've covered it.

**Comment by knz** [comment]
Amazing, thanks. Feel free to chime in again any time.

**Comment by glycerine** [comment]
I thought this became a doc bug. Is there an open doc bug for these questions, or perhaps they are already in the docs?
