### ISSUE TITLE
Issue during Django migrate ("DEFERRABLE INITIALLY DEFERRED" for constraints)

### ISSUE THREAD

**Issue by deepeshanandparab** [cockroachdb/cockroach#42133]
"DEFERRABLE INITIALLY DEFERRED" for constraints

> django.db.utils.NotSupportedError: syntax error: unimplemented: unimplemented at or near "deferred"
> DETAIL:  source SQL:
> ALTER TABLE "auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_2f476e4b_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED

**Comment by rohany** [comment]
are you using the cockroach django driver -- https://github.com/cockroachdb/cockroach-django?

**Comment by deepeshanandparab** [comment]
Yes. Its psycopg2 for cockroachdb. I tried to to migrations locally and everything works well. But when i do django migrate it gives me an error mentioned above.

**Comment by rohany** [comment]
not the pyscopg2 driver, the cockroachdb django driver i linked above

**Comment by rohany** [comment]
Following up, are you still running into this problem?

**Comment by deepeshanandparab** [comment]
Thanks it worked for me. Closing the issue.
