### ISSUE TITLE
distsql: zigzagjoiner misuses index IDs

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#42164]
The zig zag joiner is using an index ID (minus 1) as an index *ordinal*. These are the same only if we don't remove/add indexes.

https://github.com/cockroachdb/cockroach/blob/83fcaaa3a27168ebfdc52887696d5dba82d202aa/pkg/sql/rowexec/zigzagjoiner.go#L440

Repro:
```
DROP INDEX a@a_idx;
DROP INDEX a@b_idx;
CREATE INDEX c_idx ON a(c);
CREATE INDEX a_idx_2 ON a(a);
CREATE INDEX b_idx_2 ON a(b);
SELECT n,a,b FROM a WHERE a = 4 AND b = 1;
```
Error: `logic.go:2299: pq: invalid indexIdx 4`

**Comment by RaduBerinde** [comment]
Very similar to #37196..

**Comment by mjibson** [comment]
Converting an index id to an integer is a code smell. Is it ever correct? I could write a linter to prevent this. We should definitely never be doing arithmetic on index ids, right?

**Comment by RaduBerinde** [comment]
Converting to integer might be necessary (e.g. for use with `FastIntSet`), but doing arithmetic on them is definitely dubious.
