### ISSUE TITLE
ui: pre-auth HTTP requests spam log with missing cookie error

### ISSUE THREAD

**Issue by mattcrdb** [cockroachdb/cockroach#42161]
**Describe the problem**

On 19.1.5 and 19.2 rc2 the following error gets spammed to the logs in this scenario:
`191104 20:20:20.736355 877 server/authentication.go:369  Web session error: http: named cookie not present`

This occurs on a secure cluster when trying to access the admin UI but have not logged in yet with my SQL user. Once I login with my SQL user it does not spam the logs. 

The spamming is 2-3 times per second.
**To Reproduce**

1. start a secure cluster
2. try to access the admin UI, but do not log in with a SQL user.
3. observe the logs for the cockroach node (of which you accessed the UI from)

**Expected behavior**

from @knz :
```
my reading of the code says that yes, it's expected with the current code, but it's also unintended behavior and a UX bug. (The thing complains the cookie is not set because, indeed, there is no cookie registered before the authentication. By design. So really the code should be changed so it should not complain.)
```

**Environment:**
 - CockroachDB version: 19.1.5 and 19.2 rc2
 - Client app: Cockroach sql

**Additional context**

Logs are spammed 2-3 times per second and can cause confusion for users observing the logs.

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[4029](https://cockroachdb.zendesk.com/agent/tickets/4029) has been linked to this issue.

**Comment by knz** [comment]
@rolandcrosby since this is partially security-related you may have a thought on this.

**Comment by BramGruneir** [comment]
@dhartunian Any updates on this?

**Comment by knz** [comment]
not in 20.2, but I think I have a PR out which will help in 21.1

**Comment by dhartunian** [comment]
@BramGruneir is this just a matter of removing the word "Error" in the log for this particular message? these lines are logged at `Info` level so I can see how a customer who is filtering logs might get confused.

**Comment by BramGruneir** [comment]
The wording is fine. 

I think the bigger concern is the amount of times they appear in the log.  
> Logs are spammed 2-3 times per second and can cause confusion for users observing the logs.
