### ISSUE TITLE
ui: support display of graphs using client localtime

### ISSUE THREAD

**Issue by yangxuanjia** [cockroachdb/cockroach#42177]
how can i see local time in ui monitor graph? I only can see the monitor graph in UTC time, 
I want to see the x label in local time, +7 or +8 hours. 
how can I setting?
maybe log also can use local time to show.

**Comment by yangxuanjia** [comment]
http://localhost:8080/#/metrics/overview/cluster

**Comment by yangxuanjia** [comment]
cockroach/pkg/ui/src/views/cluster/components/linegraph/index.tsx
```javascript
mouseMove = (e: any) => {
result = moment(new Date(series[index]));
result = result.utcOffset(8, true);
result = result.parseZone();
result = result.hour(12);
}

drawLine = () => {
hoverTime = hoverTime.utcOffset(8, false);
hoverTime = hoverTime.parseZone()
hoverTime = hoverTime.utcOffset(8, true);
hoverTime = hoverTime.hour(12);
}

```
I modify some place, but nothing changed, may I modify the wrong place?

**Comment by ricardocrdb** [comment]
Hey @yangxuanjia 

Apologies for the delayed response. We currently have another issue tracking this feature, which you can find [here](https://github.com/cockroachdb/cockroach/issues/39097). Feel free to follow along that issue for further news of this feature. Let me know if there are any other questions.

**Comment by knz** [comment]
@ricardocrdb I think it's reasonable to support localtime-display in the UI without changing the time zone of log files. I recommend keeping this issue separate. I'll relabel it accordingly.

**Comment by knz** [comment]
cc @dhartunian @piyush-singh for triage
