### ISSUE TITLE
dead link: cockroach cloud management console links to "managed" instead of "cockroachcloud" in url

### ISSUE THREAD

**Issue by mattcrdb** [cockroachdb/cockroach#42204]
**Describe the problem**

On the cockroach cloud management console, when you are viewing the connect options, the following text box:

```
Download the CA certificate blah-ca.crt to connect securely to the cluster.  
Alternatively, you can setsslmode=require. See our docs for more details.
```
links to the wrong URL when you click "our docs".

Currently it links to `https://www.cockroachlabs.com/docs/cockroachcloud/stable/managed-connect-to-your-cluster.html#generate-the-connection-string`

It should link to `https://www.cockroachlabs.com/docs/cockroachcloud/stable/cockroachcloud-connect-to-your-cluster.html#generate-the-connection-string`

**To Reproduce**
use the management console and click "our docs" under the connection parameters.

**Expected behavior**
the correct link.

**Additional data / screenshots**

This problem is related to the rebranding to cockroach cloud and the URL's that we changed for our documentation. any other places that reference the link as `managed` should be changed to `cockroachcloud` as well.

**Comment by kannanlakshmi** [comment]
Closing here and opening in the managed-service repo so we can keep track easier.
