### ISSUE TITLE
sql: incorrect handling of timezones when extracting day from current date

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#42244]
#42006 added improved handling for timezones with date_trunc, but it also broke some assumptions about time zones and the current date.

The problem seems to be that `datum.go#MakeDTimestampTZFromDate()` takes the current date, and uses the time zone offset to convert it to a timestamptz that has a date value from the previous day.

Expected behavior (from Postgres)

```
> set time zone -5;
SET

> select
         (cast(extract(year
     from
         current_date) as varchar)||'-'||cast(extract(month
     from
         current_date) as varchar)||'-'||cast(extract(day
     from
         current_date) as varchar)) as final;
+------------+
| final      |
|------------|
| 2019-11-6  |
+------------+
```

Undesired behavior (from CockroachDB):
```
> set time zone -5;
SET

> select
        (cast(extract(year
    from
        current_date) as varchar)||'-'||cast(extract(month
    from
        current_date) as varchar)||'-'||cast(extract(day
    from
        current_date) as varchar)) as final;
  final
+-----------+
  2019-11-5
(1 row)
```

**Comment by jordanlewis** [comment]
@otan could you please follow up on fixing this?
