### ISSUE TITLE
cli: add latency to restarted transientCluster nodes

### ISSUE THREAD

**Issue by otan** [cockroachdb/cockroach#42243]
In #42230, we added an experimental feature for \demo_node to have shutdown and restart-esque commands.

However, we did not incorporate the simulate latency flags, so nodes brought down and restarted no longer have latencies added despite the flag being passed in.

Jira issue: CRDB-6336

**Comment by knz** [comment]
@otan is this still current?

**Comment by knz** [comment]
we have achieved this.
