### ISSUE TITLE
roachperf: no data since 10/23

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#42290]
![image](https://user-images.githubusercontent.com/22278911/68436305-a5aece00-018b-11ea-858c-89b793885bc1.png)
https://roachperf.crdb.dev/?filter=&view=tpccbench%2Fnodes%3D3%2Fcpu%3D16&tab=aws

TPC-C data from our nightlies hasn't been added to roachperf since 10/23

**Comment by ajwerner** [comment]
This is https://github.com/cockroachdb/roachperf/issues/41.

**Comment by awoods187** [comment]
Ping on this--we are approaching a month without graphical information to make sure we don't have any regressions. @kenliu

**Comment by ajwerner** [comment]
The good news is that at least we have all of the raw data. As soon as we fix the authentication for the roachperf job it should all show up.

**Comment by awoods187** [comment]
I assume the unstable cluster metric is blocked by the same thing:
https://github.com/cockroachdb/cockroach/issues/42290

Can we get an eta on this?

**Comment by bobvawter** [comment]
Oops.  I misunderstood the previous and thought that ajwerner was running this down.  We've synced up on this and I'll pick it up.

**Comment by kenliu** [comment]
@awoods187 really sorry I missed this issue!

**Comment by kenliu** [comment]
@bobvawter any update on this issue?

**Comment by bobvawter** [comment]
Currently working on this.

**Comment by bobvawter** [comment]
Backfilling is underway.

**Comment by bobvawter** [comment]
Backfilled.
