### ISSUE TITLE
util/uuid: consider removing in favor of github.com/satori/go.uuid

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#4230]
Not sure if we need any of the extra functionality.

**Comment by soniabhishek** [comment]
Yes so do i need to modify all the `util.uuid` functionality with `satori/go.uuid `
and make changes as per their use case . @petermattis 
i am new to this

**Comment by soniabhishek** [comment]
Hey @petermattis and @tamird i have updated the source by removing `util/uuid` and modifying all the files depending on it by adding `github.com/satori/go.uuid`. as required .
i used glock save after that 
Now what further i need to do to make a commit
these are my changes -
`
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   GLOCKFILE
	modified:   client/txn_test.go
	modified:   keys/keys_test.go
	modified:   roachpb/data.go
	modified:   roachpb/data_test.go
	modified:   server/node.go
	modified:   sql/parser/builtins.go
	modified:   storage/replica_test.go
	modified:   storage/sequence_cache_test.go
	modified:   storage/store_test.go
	modified:   storage/timestamp_cache_test.go
	deleted:    util/uuid/uuid.go
	deleted:    util/uuid/uuid_test.go

`

**Comment by tamird** [comment]
https://help.github.com/articles/creating-a-pull-request/

**Comment by soniabhishek** [comment]
Hey @tamird i just made a pull request #4318 
have a look and suggest some changes or corrections
